### PR TITLE
8337027: Parallel: Obsolete BaseFootPrintEstimate

### PR DESCRIPTION
**Pull request by albertnetymk**
Simple obsoleting a Parallel GC product flag.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8337028](https://bugs.openjdk.org/browse/JDK-8337028) to be approved

### Issues
 * [JDK-8337027](https://bugs.openjdk.org/browse/JDK-8337027): Parallel: Obsolete BaseFootPrintEstimate (**Enhancement** - P4)
 * [JDK-8337028](https://bugs.openjdk.org/browse/JDK-8337028): Parallel: Obsolete BaseFootPrintEstimate (**CSR**)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) 🔄 Re-review required (review applies to [10720a6d](https://git.openjdk.org/jdk/pull/20299/files/10720a6d114b56573407a310f7c9b5082d608895))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20299/head:pull/20299` \
`$ git checkout pull/20299`

Update a local copy of the PR: \
`$ git checkout pull/20299` \
`$ git pull https://git.openjdk.org/jdk.git pull/20299/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20299`

View PR using the GUI difftool: \
`$ git pr show -t 20299`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20299.diff">https://git.openjdk.org/jdk/pull/20299.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20299#issuecomment-2245387817)

### CODE REVIEW

**Comment by tschatzl** [comment]
The flag needs to be added to the obsolete flags table too, not only removed.

**Review by tschatzl — APPROVED** [review]

**Review by kimbarrett — APPROVED** [review]
Looks good.

I assume you will be updating copyrights before integration?

**Review by tschatzl — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
