### PR TITLE
8267123: Remove RMI Activation

### PR DESCRIPTION
**Pull request by stuart-marks**
This is the implementation of [JEP 407](https://openjdk.java.net/jeps/407).

This is a fairly straightforward removal of this component.
 - Activation implementation classes removed
 - Activation tests removed
 - adjustments to various comments to remove references to Activation
 - adjustments to some code to remove special-case support for Activation from core RMI
 - adjustments to several tests to remove testing and support for, and mentions of Activation
 - remove `rmid` tool

(Personally, I found that reviewing using the webrev was easier than navigating github's diff viewer.)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267123](https://bugs.openjdk.java.net/browse/JDK-8267123): Remove RMI Activation

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4194/head:pull/4194` \
`$ git checkout pull/4194`

Update a local copy of the PR: \
`$ git checkout pull/4194` \
`$ git pull https://git.openjdk.java.net/jdk pull/4194/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4194`

View PR using the GUI difftool: \
`$ git pr show -t 4194`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4194.diff">https://git.openjdk.java.net/jdk/pull/4194.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]
Build changes look good.

**Comment by AlanBateman** [comment]
One other test that might need an update is test/jdk/sun/rmi/log/ReliableLog/LogAlignmentTest.java, it might be just the summary.

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Comment by stuart-marks** [comment]
AlanBateman wrote:

> test/jdk/sun/rmi/log/ReliableLog/LogAlignmentTest.java

Oh yes, this test mentions `rmid`, but it is basically a direct test of the `ReliableLog` stuff and it doesn't actually use or depend on Activation or `rmid`. The test still runs and passes.

I'll do a followup pass to see if anything in the system uses anything in the `sun.rmi.log` package. Maybe the only user was Activation.

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
