### PR TITLE
8261462: GCM ByteBuffer decryption problems

### PR DESCRIPTION
**Pull request by ascarpino**
Hi,

I need a review of these two simple fixes.  One just sets the input bytebuffer position to the limit upon completion of decryption.  The second calls the CipherCore method to clear the state from the previous operation.

Thanks

Tony

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261462](https://bugs.openjdk.java.net/browse/JDK-8261462): GCM ByteBuffer decryption problems

### Reviewers
 * [Valerie Peng](https://openjdk.java.net/census#valeriep) (@valeriepeng - **Reviewer**) ⚠️ Review applies to b9aa4914b4b0be63a3567766205d0b44947e7ac0

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2487/head:pull/2487`
`$ git checkout pull/2487`

### CODE REVIEW

**Comment by ascarpino** [comment]
Ping

**Comment by valeriepeng** [comment]
I will take a look. Thanks!

**Review by valeriepeng — APPROVED** [review]
Changes look good. Only nit is the copyright year of the 2 source files should be updated.

**Pull request closed without merging**
