### PR TITLE
8293036: x86_64: Move Continuation-related stub methods to MacroAssembler

### PR DESCRIPTION
**Pull request by iwanowww**
Move Continuation-related methods from `stubGenerator_x86_64.cpp` under `MacroAssembler`.

Testing: hs-tier1 - hs-tier2

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293036](https://bugs.openjdk.org/browse/JDK-8293036): x86_64: Move Continuation-related stub methods to MacroAssembler

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10066/head:pull/10066` \
`$ git checkout pull/10066`

Update a local copy of the PR: \
`$ git checkout pull/10066` \
`$ git pull https://git.openjdk.org/jdk pull/10066/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10066`

View PR using the GUI difftool: \
`$ git pr show -t 10066`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10066.diff">https://git.openjdk.org/jdk/pull/10066.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]
It looks good, but I'm curious, what's the motivation?

**Comment by iwanowww** [comment]
Thanks for the review, Dean.

> It looks good, but I'm curious, what's the motivation?

It's a worthwhile cleanup per se, but it'll also benefit forthcoming cleanups in  `stubGenerator_x86_64.cpp`.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by iwanowww** [comment]
Thanks for the review, Vladimir.

/integrate

**Pull request closed without merging**
