### PR TITLE
8323835: Updating ASM to 9.6 for JDK 23

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
Updating ASM to version 9.6,

Thanks in advance for the reviews,
Vicente

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323835](https://bugs.openjdk.org/browse/JDK-8323835): Updating ASM to 9.6 for JDK 23 (**Bug** - P3)

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17453/head:pull/17453` \
`$ git checkout pull/17453`

Update a local copy of the PR: \
`$ git checkout pull/17453` \
`$ git pull https://git.openjdk.org/jdk.git pull/17453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17453`

View PR using the GUI difftool: \
`$ git pr show -t 17453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17453.diff">https://git.openjdk.org/jdk/pull/17453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17453#issuecomment-1896106012)

### CODE REVIEW

**Comment by mlchung** [comment]
The change looks okay to me.   Most of the changes are doc change.  I see many files are updated just to remove the empty line at the end of the file - is that intentional, imported from this upgrade?     

Any need to update the copyright header?   The new file CheckFrameAnalyzer.java still has the same copyright header years as other files.  I assume no need then?

**Comment by vicente-romero-oracle** [comment]
hi Mandy, thanks for your comments,

> The change looks okay to me. Most of the changes are doc change. I see many files are updated just to remove the empty line at the end of the file - is that intentional, imported from this upgrade?

yes this is intentional, this change somehow aligns with what we do with our sources that's why I kept it 

> 
> Any need to update the copyright header? The new file CheckFrameAnalyzer.java still has the same copyright header years as other files. I assume no need then?

yes there is no need to update them, we never update the year on the copyright of ASM sources

**Review by mlchung — APPROVED** [review]
Looks okay to me.   I would rely on your testing for verification.

**Comment by vicente-romero-oracle** [comment]
> Looks okay to me. I would rely on your testing for verification.

I have run tier1-6 tests, they look OK

**Pull request closed without merging**
