### PR TITLE
8286424: GetVersionEx is deprecated

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to explicitly disable deprecation warnings for the
two uses of GetVersionEx in HotSpot code. This is a step toward being able to
remove the global (to HotSpot) disable of deprecation warnings for Windows.
(It is because of that global disable that these uses don't currently generate
warnings.)

There are uses of this function in non-HotSpot parts of the JDK. These are not
being changed. They all disable the warning in some fashion, as appropriate to
that area's usage.  This change is only about HotSpot usage, and wanting to
remove global deprecation disabling from HotSpot builds.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286424](https://bugs.openjdk.java.net/browse/JDK-8286424): GetVersionEx is deprecated

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8611/head:pull/8611` \
`$ git checkout pull/8611`

Update a local copy of the PR: \
`$ git checkout pull/8611` \
`$ git pull https://git.openjdk.java.net/jdk pull/8611/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8611`

View PR using the GUI difftool: \
`$ git pr show -t 8611`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8611.diff">https://git.openjdk.java.net/jdk/pull/8611.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Kim,

AFAICS both uses of this only try to determine whether we are running a server or client/workstation version - and for that the `IsWindowsServer()` API exists:

 https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindowsserver
 
 But the fix itself is fine for silencing the deprecation warning (a deprecation that I didn't find documented ??).

Thanks.

**Comment by kimbarrett** [comment]
> AFAICS both uses of this only try to determine whether we are running a server or client/workstation version - and for that the `IsWindowsServer()` API exists:
> 
> https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindowsserver

You are right!  I just assumed that in print_windows_version it was making
further use of the info from GetVersionEx further down.  But it's not!

Because of that, I missed that IsWindowsServer could serve as a replacement.
Thanks for spotting that; I'll make that change instead.

> But the fix itself is fine for silencing the deprecation warning (a deprecation that I didn't find documented ??).

https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa
"GetVersionExA may be altered or unavailable for releases after Windows 8.1. Instead, use the Version Helper functions."

That sounds like "deprecated" without actually using that word, and a reasonable excuse for the compiler warning.

**Review by dholmes-ora — APPROVED** [review]
Looks good.

That "deprecation" is why we don't actually use `GetVersionEx` to get the version - see JDK-8059803.  I guess the existence of `IsWindowsServer` was overlooked at the time.

Thanks.

**Review by hseigel — APPROVED** [review]
LGTM!
Thanks, Harold

**Comment by kimbarrett** [comment]
Thanks @dholmes-ora and @hseigel for reviews.

**Pull request closed without merging**
