### PR TITLE
8333542: Breakpoint in parallel code does not work

### PR DESCRIPTION
**Pull request by coleenp**
Revert the change for JDK-8288064 "Class initialization locking".  JVMTI class prepare event relies on a lock being held through setting the state of the class to 'linked' and the JVMTI event posting. The only usable lock is the Java object init_lock, which was removed.  This change restores the lock and fixes all the conflicts in code that's changed since.

Tested with tier1-7.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333542](https://bugs.openjdk.org/browse/JDK-8333542): Breakpoint in parallel code does not work (**Bug** - P3)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)

### Contributors
 * Chris Plummer `<cjplummer@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19755/head:pull/19755` \
`$ git checkout pull/19755`

Update a local copy of the PR: \
`$ git checkout pull/19755` \
`$ git pull https://git.openjdk.org/jdk.git pull/19755/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19755`

View PR using the GUI difftool: \
`$ git pr show -t 19755`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19755.diff">https://git.openjdk.org/jdk/pull/19755.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19755#issuecomment-2183131447)

### CODE REVIEW

**Comment by coleenp** [comment]
/contributor add @plummercj 

Chris wrote the test.

**Comment by dean-long** [comment]
There may be a simpler way to fix this.  What if we pretend that any class with a deferred breakpoint automatically has a static initializer?  Then as part of the "injected" static initializer, the class does the prepare event and sets up the breakpoint.  In the mean time, other threads trying to execute methods in that class are blocked because of the static initializer protocol.  I don't think this introduces new deadlocks unless the prepare event does something strange.

**Comment by coleenp** [comment]
I had a version of the fix that you described and it works well with the test case.   Unfortunately, there are other class prepare events that are expected at link time before the class is initialized.  Luckily we have a robust set of tests.   One such test is vmTestbase/nsk/jvmti/scenarios/events/EM01/em01t001.

If we want to remove the ObjectLocker in a future release, I think the RecursiveLock mechanism would be the way to do it.  I chose a backout for this because it's also broken in JDK 21 and Chris thinks it's important to fix there also.

**Review by dholmes-ora — APPROVED** [review]
This reversion to the OL code looks good to me.

Thanks

**Review by plummercj — COMMENTED** [review]
The changes pass all my jdi, jdwp, jdb, and jvmti testing, including running most of the test suites 10 times or more.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thanks David and Vladimir for the reviews, and Chris for the report, test and testing.
/integrate

**Pull request closed without merging**
