### PR TITLE
8257806: Optimize x86 allTrue and anyTrue vector mask operations of Vector API

### PR DESCRIPTION
**Pull request by sviswa7**
The allTrue and anyTrue operations are implemented using ptest/vptest instruction. 
Two optimizations are possible:

1) The ptest instruction minimum size is 128 bit.
Smaller < 128 bit size operations can be implemented by first broadcasting (duplicating) the input to 128 bits.
The two inputs to these operations are:
  a) Vector mask being tested
  b) All ones
For allTrue operation, both the inputs need to be broadcasted.
For anyTrue operation, only the first input (vector mask) need to be broadcasted.

2) The anyTrue operation followed by comparison with zero can use the zero flag generated by ptest/vptest directly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257806](https://bugs.openjdk.java.net/browse/JDK-8257806): Optimize x86 allTrue and anyTrue vector mask operations of Vector API 

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * psandoz - **Reviewer** ⚠️ Added manually

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1656/head:pull/1656`
`$ git checkout pull/1656`

### CODE REVIEW

**Comment by PaulSandoz** [comment]
Verified locally that code gen looks good. Due to some internal configuration changes this PR likely needs to be rebased to ensure correct test execution (open and internal configs are out of sync due to some recent configuration changes).

**Comment by sviswa7** [comment]
@PaulSandoz I have rebased the patch, please let me know if this looks ok.
@iwanowww Looking forward to your comments on this patch.

**Comment by PaulSandoz** [comment]
> @PaulSandoz I have rebased the patch, please let me know if this looks ok.

That unblocked things, tests are good.

**Comment by sviswa7** [comment]
@vnkozlov Looking forward to your comments on this patch.

**Review by vnkozlov — COMMENTED** [review]
I have concerns about GitHub testing failures. And I don't see in the RFE links to testing.
I understand and agree with changes in general but I can't judge correctness of code.

**Comment by sviswa7** [comment]
@vnkozlov The patch is Vector API specific. I have run the Vector API tests on all our platforms with this patch (non avx, avx, avx512) and they all pass. The github test failures seem to be unrelated to the patch. e.g. the Linux x64 seems to show the following as log: 
Run if ! grep --include=test-summary.txt -lqr build/*/test-results -e "TEST SUCCESS" ; then
# newfailures.txt
tools/javac/diags/CheckExamples.java 
Error: Process completed with exit code 1.
I will try to reissue the github tests.

**Comment by sviswa7** [comment]
May be rebasing the pull request will trigger the test. I will try that.

**Review by vnkozlov — APPROVED** [review]
Passed tier1-3 testing I ran.
Good.

**Comment by sviswa7** [comment]
@vnkozlov thanks a lot!

**Pull request closed without merging**
