### PR TITLE
8255343: java/util/stream/SpliteratorTest.java fails on 32-bit platforms with "Misaligned access at address: 12"

### PR DESCRIPTION
**Pull request by shipilev**
It currently fails on x86_32 with `java.lang.IllegalStateException: Misaligned access at address: 12`. I checked that once JDK-8254162 integrates, that issue is gone. Until then, having clean x86_32 testing is beneficial for other work.

Testing:
 - [x] `java/util/stream` tests on Linux x86_64 (still passes)
 - [x] `java/util/stream` tests on Linux x86_32 (start to pass)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255343](https://bugs.openjdk.java.net/browse/JDK-8255343): java/util/stream/SpliteratorTest.java fails on 32-bit platforms with "Misaligned access at address: 12"

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Contributors
 * Maurizio Cimadamore `<mcimadamore@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/836/head:pull/836`
`$ git checkout pull/836`

### CODE REVIEW

**Comment by mcimadamore** [comment]
I'm not sure I get as to why the test fails on 32 bits - in the sense that it does not seem to rely on platform specific assumptions (at least on a quick look). On top of my head I'm not aware of what might have caused this to start working again in JDK-8254162, so maybe some more investigation is required?

At the very least we should only disable the problematic spliterator test, which is, I believe "testSegmentSpliterator" - and leave the other running, which is useful, as this is an important stress test for spliterators.

**Comment by mcimadamore** [comment]
Ok - I understand at least why JDK-8254162 fixed it - JDK-8254162 uses a new API to access memory (MemoryAccess) which disables alignment checks, so that's why the issue doesn't happen. But that means that there could be a latent issue in the test. Looking deeper.

**Comment by shipilev** [comment]
Thing is, I don't think there is a way to problem list the _TestNG_ testcase, is it? There is only a way to problem list the entire jtreg test or its separate `@run` with ID. Which is what the patch does. I would think that `generic-i586` only touches `x86_32`, and thus the test, while disabled there, is still operational on every other platform.

I would love if there is was pointed fix that resolves the actual issue, though.

**Comment by mcimadamore** [comment]
Can you see if this helps?

```
diff --git a/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java b/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
index 2d2d33d0ab7..c5410865a2b 100644
--- a/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
+++ b/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
@@ -40,12 +40,12 @@ import org.testng.annotations.DataProvider;
 public class SegmentTestDataProvider {
 
     static VarHandle BYTE_HANDLE = MemoryLayouts.JAVA_BYTE.varHandle(byte.class);
-    static VarHandle CHAR_HANDLE = MemoryLayouts.JAVA_CHAR.varHandle(char.class);
-    static VarHandle SHORT_HANDLE = MemoryLayouts.JAVA_SHORT.varHandle(short.class);
-    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.varHandle(int.class);
-    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.varHandle(long.class);
-    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.varHandle(float.class);
-    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.varHandle(double.class);
+    static VarHandle CHAR_HANDLE = MemoryLayouts.JAVA_CHAR.withBitAlignment(8).varHandle(char.class);
+    static VarHandle SHORT_HANDLE = MemoryLayouts.JAVA_SHORT.withBitAlignment(8).varHandle(short.class);
+    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.withBitAlignment(8).varHandle(int.class);
+    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.withBitAlignment(8).varHandle(long.class);
+    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.withBitAlignment(8).varHandle(float.class);
+    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.withBitAlignment(8).varHandle(double.class);
 
     static boolean compareSegmentsByte(Collection<MemorySegment> segments1, Collection<MemorySegment> segments2, boolean isOrdered) {
:
ass);
-    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.varHandle(int.class);
-    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.varHandle(long.class);
-    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.varHandle(float.class);
-    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.varHandle(double.class);
+    static VarHandle CHAR_HANDLE = MemoryLayouts.JAVA_CHAR.withBitAlignment(8).varHandle(char.class);
+    static VarHandle SHORT_HANDLE = MemoryLayouts.JAVA_SHORT.withBitAlignment(8).varHandle(short.class);
+    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.withBitAlignment(8).varHandle(int.class);
+    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.withBitAlignment(8).varHandle(long.class);
+    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.withBitAlignment(8).varHandle(float.class);
+    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.withBitAlignment(8).varHandle(double.class);
 
     static boolean compareSegmentsByte(Collection<MemorySegment> segments1, Collection<MemorySegment> segments2, boolean isOrdered) {
         Function<MemorySegment, Byte> mapper = segment -> (byte)BYTE_HANDLE.get(segment.baseAddress());
```

**Comment by shipilev** [comment]
> Can you see if this helps?
>      static boolean compareSegmentsByte(Collection<MemorySegment> segments1, Collection<MemorySegment> segments2, boolean isOrdered) {
> :
> ass);

I can, but the patch is corrupted near this line.

**Comment by shipilev** [comment]
Yes, this makes the test pass:

```
diff --git a/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java b/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
index 2d2d33d0ab7..c5410865a2b 100644
--- a/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
+++ b/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/SegmentTestDataProvider.java
@@ -40,12 +40,12 @@ import org.testng.annotations.DataProvider;
 public class SegmentTestDataProvider {
 
     static VarHandle BYTE_HANDLE = MemoryLayouts.JAVA_BYTE.varHandle(byte.class);
-    static VarHandle CHAR_HANDLE = MemoryLayouts.JAVA_CHAR.varHandle(char.class);
-    static VarHandle SHORT_HANDLE = MemoryLayouts.JAVA_SHORT.varHandle(short.class);
-    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.varHandle(int.class);
-    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.varHandle(long.class);
-    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.varHandle(float.class);
-    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.varHandle(double.class);
+    static VarHandle CHAR_HANDLE = MemoryLayouts.JAVA_CHAR.withBitAlignment(8).varHandle(char.class);
+    static VarHandle SHORT_HANDLE = MemoryLayouts.JAVA_SHORT.withBitAlignment(8).varHandle(short.class);
+    static VarHandle INT_HANDLE = MemoryLayouts.JAVA_INT.withBitAlignment(8).varHandle(int.class);
+    static VarHandle LONG_HANDLE = MemoryLayouts.JAVA_LONG.withBitAlignment(8).varHandle(long.class);
+    static VarHandle FLOAT_HANDLE = MemoryLayouts.JAVA_FLOAT.withBitAlignment(8).varHandle(float.class);
+    static VarHandle DOUBLE_HANDLE = MemoryLayouts.JAVA_DOUBLE.withBitAlignment(8).varHandle(double.class);
 
     static boolean compareSegmentsByte(Collection<MemorySegment> segments1, Collection<MemorySegment> segments2, boolean isOrdered) {
         Function<MemorySegment, Byte> mapper = segment -> (byte)BYTE_HANDLE.get(segment.baseAddress());
```

I can fix the whole thing thus, without problem listing the test then. Agree?

**Comment by mcimadamore** [comment]
> I can fix the whole thing thus, without problem listing the test then. Agree?

Yes - another thing worth considering though is: if 32bit alignment is the best we can ask a 32bit VM (e.g. a 32bit VM doesn't really 64-bit align a double[] it seems, from what you are getting), then I think an even better fix would be to just make the constants JAVA_LONG and JAVA_DOUBLE aligned to 32 or 64 depending on the platform (and leave the test unchanged).

**Comment by shipilev** [comment]
> Yes - another thing worth considering though is: if 32bit alignment is the best we can ask a 32bit VM (e.g. a 32bit VM doesn't really 64-bit align a double[] it seems, from what you are getting), then I think an even better fix would be to just make the constants JAVA_LONG and JAVA_DOUBLE aligned to 32 or 64 depending on the platform (and leave the test unchanged).

Please see the new revision. It passes `java/util/stream` tests on both `x86_32` and `x86_64`. 

What 32-bit VM is able to do is implementation-dependent, no? I do wonder if long[]/double[] have to be aligned by 8 anyway, since we can do a VarHandle atomic access over its elements, and it is supposed to go correctly. Let's figure that out separately? Filed [JDK-8255350](https://bugs.openjdk.java.net/browse/JDK-8255350).

**Comment by mcimadamore** [comment]
Looks good to me

**Comment by shipilev** [comment]
> /approve

"Files Changed" on top -> "Review Changes" -> "Approve" :)

**Review by mcimadamore — APPROVED** [review]
Looks good

**Comment by mcimadamore** [comment]
> > /approve
> 
> "Files Changed" on top -> "Review Changes" -> "Approve" :)

I must be going mad :-)

**Pull request closed without merging**
