### PR TITLE
8312976: MatchResult produces StringIndexOutOfBoundsException for groups outside match

### PR DESCRIPTION
**Pull request by rgiulietti**
Fixes a bug showing up after [JDK-8132995](https://bugs.openjdk.org/browse/JDK-8132995) when there are capturing groups outside the match.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312976](https://bugs.openjdk.org/browse/JDK-8312976): MatchResult produces StringIndexOutOfBoundsException for groups outside match (**Bug** - P2)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Stuart Marks](https://openjdk.org/census#smarks) (@stuart-marks - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15053/head:pull/15053` \
`$ git checkout pull/15053`

Update a local copy of the PR: \
`$ git checkout pull/15053` \
`$ git pull https://git.openjdk.org/jdk.git pull/15053/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15053`

View PR using the GUI difftool: \
`$ git pr show -t 15053`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15053.diff">https://git.openjdk.org/jdk/pull/15053.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15053#issuecomment-1653436167)

### CODE REVIEW

**Comment by rgiulietti** [comment]
Once integrated in mainline, the fix should be backported to 21, where the bug was introduced.

**Review by AlanBateman — APPROVED** [review]
This looks okay. I think its would be useful to get another reviewer to also look over this in case there is any other issues.

**Comment by stuart-marks** [comment]
OK, changes and tests look good. Who knew, a capturing group could have bounds outside the matched string!

I did notice something that we might want to look at in the future. `MatchResult` has `first` and `last` fields; these seem redundant with the `group[0]` and `group[1]` entries. Indeed, `Matcher` also has `first` and `last` and the `group[]` array; `start()` returns `first` and `end()` returns `last`; while `start(0)` returns `group[0]` and `end(0)` returns `group[1]`. But the javadocs say that `start()` and `start(0)` are equivalent and that `end()` and `end(0)` are also equivalent. So `Matcher` also appears to have this redundancy. Since these values are all set by the matching engine in `Pattern` it seems like the redundancy is spread throughout the code.

Conceptually it might be possible for `MatchResult` to omit `first` and `last` and just use the first two `group` array entries, but it's really hard to verify this. Unclear whether this is worthwhile (and it's certainly not worth trying to include in this  bugfix).

**Review by stuart-marks — APPROVED** [review]

**Comment by rgiulietti** [comment]
Yes, I noticed that as well.

There's another [PR](https://git.openjdk.org/jdk/pull/14894) aimed to reduce the length of the `groups` array when possible (currently, it is always sized for at least 10 pairs of (`start`, `end`) entries, even when only one pair is needed for group 0). That one is slated for >= 22, so I might be coordinated the future PR for the removal of the redundant `first` and `last` fields with that PR.

**Pull request closed without merging**
