### PR TITLE
8298468: Clean up class_loader parameters

### PR DESCRIPTION
**Pull request by coleenp**
This patch passes ClassLoaderData* rather than Handle class_loader to the LoaderConstraintTable and to some functions in SystemDictionary that only need ClassLoaderData.  In general, class loading uses ClassLoaderData unless it has to call up to Java in loadClass().  There were a lot of unnecessary conversions back and forth.
Tested with tier1-4.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298468](https://bugs.openjdk.org/browse/JDK-8298468): Clean up class_loader parameters

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11672/head:pull/11672` \
`$ git checkout pull/11672`

Update a local copy of the PR: \
`$ git checkout pull/11672` \
`$ git pull https://git.openjdk.org/jdk pull/11672/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11672`

View PR using the GUI difftool: \
`$ git pr show -t 11672`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11672.diff">https://git.openjdk.org/jdk/pull/11672.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks like a good cleanup. Thanks.

**Comment by coleenp** [comment]
Thanks David!

**Review by iklam — APPROVED** [review]
LGTM

**Comment by coleenp** [comment]
Thanks Ioi!
/integrate

**Pull request closed without merging**
