### PR TITLE
8320577: Improve MessageHeader's toString() function to make HttpURLConnection's debug log readable

### PR DESCRIPTION
**Pull request by oliverlockwood**
At the moment, if you have debug logging turned on for the `HttpURLConnection` class, then from [line 746](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L746) a log message like this is generated:
> sun.net.www.MessageHeader@49c4f2906 pairs: {null: HTTP/1.1 200}{Content-Type: application/json}{Transfer-Encoding: chunked}{Date: Thu, 09 Nov 2023 11:50:00 GMT}{Keep-Alive: timeout=60}{Connection: keep-alive}

The lack of separation after the `Object.toString()` output makes it hard to realise from the above that it's trying to say "6 pairs". 
The change proposed by this PR would make the same log operation output this, instead:
> sun.net.www.MessageHeader@49c4f290 6 pairs: {null: HTTP/1.1 200}{Content-Type: application/json}{Transfer-Encoding: chunked}{Date: Thu, 09 Nov 2023 11:50:00 GMT}{Keep-Alive: timeout=60}{Connection: keep-alive}

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320577](https://bugs.openjdk.org/browse/JDK-8320577): Improve MessageHeader's toString() function to make HttpURLConnection's debug log readable (**Bug** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [5cb93c0f](https://git.openjdk.org/jdk/pull/16615/files/5cb93c0f53afdee7d8f3de12a9a712ae4ac724f5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16615/head:pull/16615` \
`$ git checkout pull/16615`

Update a local copy of the PR: \
`$ git checkout pull/16615` \
`$ git pull https://git.openjdk.org/jdk.git pull/16615/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16615`

View PR using the GUI difftool: \
`$ git pr show -t 16615`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16615.diff">https://git.openjdk.org/jdk/pull/16615.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16615#issuecomment-1822393126)

### CODE REVIEW

**Comment by djelinski** [comment]
Hi @oliverlockwood all PRs need to be associated to a Java Bug System ticket; I created one for you. Please change the PR title to `8320577` to mark this PR as ready for review.

**Comment by oliverlockwood** [comment]
Hi @djelinski, thank you for taking the time to do this on my behalf.  I have now formed the title to be like `issue number: message` as per the check and other open PRs that I can see.  Please let me know if you need me to jump through any other hurdles 😄

**Review by dfuch — COMMENTED** [review]
Looks reasonable to me. Can you update the Copyright Years in the file? (change 2021 into 2023).

**Review by jaikiran — APPROVED** [review]
Good catch. I've seen that log message in the log files a few times before and it never occurred to me that it was trying to say that there are "X" number of message header pairs.
Change looks good to me other than what Daniel already noted about the copyright year.

**Comment by oliverlockwood** [comment]
@dfuch @jaikiran can you please clarify?  The copyright year line currently has:
` * Copyright (c) 1995, 2021, Oracle and/or its affiliates. All rights reserved.`

Do you want this changing to:

1. ` * Copyright (c) 1995, 2023, Oracle and/or its affiliates. All rights reserved.` or
2. ` * Copyright (c) 1995, 2021, 2023, Oracle and/or its affiliates. All rights reserved.` ?

**Comment by dfuch** [comment]
> 1.  * Copyright (c) 1995, 2023, Oracle and/or its affiliates. All rights reserved.

1. is the correct alternative. Thanks!

**Review by dfuch — APPROVED** [review]
Thanks for the fix! If you need a sponsor, please drop a message here after integrating.

**Pull request closed without merging**
