### PR TITLE
8302508: Add timestamp to the output TraceCompilerThreads

### PR DESCRIPTION
**Pull request by vnkozlov**
Having timestamps added to the output of TraceCompilerThreads will be helpful in understanding how frequently the compiler threads are being added or removed.

I did that and also added UL output.

```
java -XX:+TraceCompilerThreads -XX:+PrintCompilation -version

     86 Added initial compiler thread C2 CompilerThread0
     86 Added initial compiler thread C1 CompilerThread0
     92    1       3       java.lang.Object::<init> (1 bytes)
     96    2       3       java.lang.String::coder (15 bytes)

java -Xlog:jit+thread=debug -Xlog:jit+compilation=debug -version

[0.078s][debug][jit,thread] Added initial compiler thread C2 CompilerThread0
[0.078s][debug][jit,thread] Added initial compiler thread C1 CompilerThread0
[0.083s][debug][jit,compilation]    1       3       java.lang.Object::<init> (1 bytes)
[0.087s][debug][jit,compilation]    2       3       java.lang.String::coder (15 bytes)
```

Tested tier1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302508](https://bugs.openjdk.org/browse/JDK-8302508): Add timestamp to the output TraceCompilerThreads

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12898/head:pull/12898` \
`$ git checkout pull/12898`

Update a local copy of the PR: \
`$ git checkout pull/12898` \
`$ git pull https://git.openjdk.org/jdk pull/12898/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12898`

View PR using the GUI difftool: \
`$ git pr show -t 12898`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12898.diff">https://git.openjdk.org/jdk/pull/12898.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by poonamparhar** [comment]
The changes look good to me!

**Comment by vnkozlov** [comment]
Thank you @TobiHartmann  and @poonamparhar for reviews.

**Pull request closed without merging**
