### PR TITLE
8256017: Remove unused elapsedTimer constructor

### PR DESCRIPTION
**Pull request by cl4es**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256017](https://bugs.openjdk.java.net/browse/JDK-8256017): Remove unused elapsedTimer constructor

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to ae7e057ee17f9e67ee392a9ba7f7cfa03b1a37ac
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to ae7e057ee17f9e67ee392a9ba7f7cfa03b1a37ac

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1112/head:pull/1112`
`$ git checkout pull/1112`

### CODE REVIEW

**Comment by cl4es** [comment]
elapsedTimer(jlong time, jlong timeUnitsPerSecond) was added by JDK-8136421 but the only use has disappeared since.

**Review by tschatzl — APPROVED** [review]
Lgtm. Maybe the copyright dates can be updated too, but feel free to ignore.

**Review by hseigel — APPROVED** [review]
Changes look good.

**Comment by cl4es** [comment]
@tschatzl @hseigel: thank you both for reviewing.

/integrate

**Pull request closed without merging**
