### PR TITLE
8327391: Add SipHash attribution file

### PR DESCRIPTION
**Pull request by JesperIRL**
SipHash attribution file added in src/hotspot/share/legal/

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327391](https://bugs.openjdk.org/browse/JDK-8327391): Add SipHash attribution file (**Bug** - P3)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Lois Foltan](https://openjdk.org/census#lfoltan) (@lfoltan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18129/head:pull/18129` \
`$ git checkout pull/18129`

Update a local copy of the PR: \
`$ git checkout pull/18129` \
`$ git pull https://git.openjdk.org/jdk.git pull/18129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18129`

View PR using the GUI difftool: \
`$ git pr show -t 18129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18129.diff">https://git.openjdk.org/jdk/pull/18129.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Okay.

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Comment by gnu-andrew** [comment]
The copyright notice in the attribution file seems to be out of sync with that in `altHashing.cpp`.

The one in `altHashing.cpp` has gone back and forth between the two, and was most recently updated by [JDK-8297887](https://github.com/openjdk/jdk/commit/bacf652311a74d93f6f802c51a1a2150522704cb) to the single 2016 copyright which matches the upstream [halfsiphash.c](https://github.com/veorq/SipHash/blob/master/halfsiphash.c)

This commit adds the copyright from [siphash.c](https://github.com/veorq/SipHash/blob/master/siphash.c) as was also done in [JDK-8273341: Update Siphash to version 1.0](https://git.openjdk.java.net/jdk/commit/6cf4cd1aa46414d9af17f3704b27d0d381a17ee8) before being changed back in JDK-8297887.

I believe the one from `halfsiphash.c` is what we want as that's what is used in `altHashing.cpp`.

**Comment by JesperIRL** [comment]
@gnu-andrew Thanks! See https://bugs.openjdk.org/browse/JDK-8328812

**Pull request closed without merging**
