### PR TITLE
8293939: Move continuation_enter_setup and friends

### PR DESCRIPTION
**Pull request by coleenp**
Please review this trivial change. I moved these functions to sharedRuntime_<cpu>.cpp just before they are used.
Tested with tier1 on x86 and aarch64, and locally test/hotspot/jtreg:hotspot_loom.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293939](https://bugs.openjdk.org/browse/JDK-8293939): Move continuation_enter_setup and friends

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10770/head:pull/10770` \
`$ git checkout pull/10770`

Update a local copy of the PR: \
`$ git checkout pull/10770` \
`$ git pull https://git.openjdk.org/jdk pull/10770/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10770`

View PR using the GUI difftool: \
`$ git pr show -t 10770`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10770.diff">https://git.openjdk.org/jdk/pull/10770.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thanks Dean.

**Review by pchilano — APPROVED** [review]
Looks good to me.

**Comment by coleenp** [comment]
Thanks Patricio.
/integrate

**Pull request closed without merging**
