### PR TITLE
8309259: Reduce calls to MethodHandles.lookup() in jdk.internal.net.http.Stream

### PR DESCRIPTION
**Pull request by nizarbenalla**
Please review this simple enhancement that is just reducing the number of times we call the `MethodHandles.lookup()` method, as it can be a bit slow.
Passes tier 1-3

TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309259](https://bugs.openjdk.org/browse/JDK-8309259): Reduce calls to MethodHandles.lookup() in jdk.internal.net.http.Stream (**Enhancement** - P5)

### Reviewers
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18862/head:pull/18862` \
`$ git checkout pull/18862`

Update a local copy of the PR: \
`$ git checkout pull/18862` \
`$ git pull https://git.openjdk.org/jdk.git pull/18862/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18862`

View PR using the GUI difftool: \
`$ git pr show -t 18862`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18862.diff">https://git.openjdk.org/jdk/pull/18862.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18862#issuecomment-2068905780)

### CODE REVIEW

**Review by minborg — APPROVED** [review]
Nice cleanup. LGTM.

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
