### PR TITLE
8345577: Additional clarification to the com.sun.net.httpserver.HttpExchange.getAttribute() and setAttribute() methods after JDK-8235786

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this doc-only change which proposes to address https://bugs.openjdk.org/browse/JDK-8345577?

As noted in that issue, a recent update (in the current JDK mainline) to the javadoc of these methods made some existing external subclasses overridding these methods to contradict the specification of the methods. The update in this current PR relaxes the normative text and clarifies the JDK built-in implementation through a `@implSpec`.

No new tests have been added given the nature of this change. The CSR is ready for review https://bugs.openjdk.org/browse/JDK-8345582.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 25 to be approved (needs to be created)

### Issue
 * [JDK-8345577](https://bugs.openjdk.org/browse/JDK-8345577): Additional clarification to the com.sun.net.httpserver.HttpExchange.getAttribute() and setAttribute() methods after JDK-8235786 (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22577/head:pull/22577` \
`$ git checkout pull/22577`

Update a local copy of the PR: \
`$ git checkout pull/22577` \
`$ git pull https://git.openjdk.org/jdk.git pull/22577/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22577`

View PR using the GUI difftool: \
`$ git pr show -t 22577`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22577.diff">https://git.openjdk.org/jdk/pull/22577.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22577#issuecomment-2520337707)
</details>

### CODE REVIEW

**Comment by bowbahdoe** [comment]
A doc only change does not address the issue, it merely tries to define it out of existence. What is happening here?

**Comment by jaikiran** [comment]
Hello Ethan,

> A doc only change does not address the issue, it merely tries to define it out of existence.

The intention of this PR and the previous update in https://bugs.openjdk.org/browse/JDK-8235786 isn't to change the current JDK built-in implementation. Instead it is to document the current behaviour.

The current implementation has been around for several releases. As a future and separate work, as noted in the CSR, alternatives will be considered to provide a way to set per exchange attributes.

**Comment by Michael-Mc-Mahon** [comment]
We're going to revert the doc change that this PR was going to clarify (in another PR) in 24. So this PR will be closed and we will take another approach towards the original issue in 25.

**Comment by jaikiran** [comment]
Withdrawing this PR in favour of https://bugs.openjdk.org/browse/JDK-8345794.

**Pull request closed without merging**
