### PR TITLE
8278119: ProblemList few headful test failing in macosx12-aarch64 system

### PR DESCRIPTION
**Pull request by prsadhuk**
Few tests are failing on macos12-aarch64 systems due to mismatch in color value obtained from robot.getPixelColor and expected color.
More details on the failures can be seen in JDK-8277816. Till the root cause is investigated, it is better to problemlist it as it causing failures in CI run.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278119](https://bugs.openjdk.java.net/browse/JDK-8278119): ProblemList few headful test failing in macosx12-aarch64 system

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6663/head:pull/6663` \
`$ git checkout pull/6663`

Update a local copy of the PR: \
`$ git checkout pull/6663` \
`$ git pull https://git.openjdk.java.net/jdk pull/6663/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6663`

View PR using the GUI difftool: \
`$ git pr show -t 6663`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6663.diff">https://git.openjdk.java.net/jdk/pull/6663.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — CHANGES_REQUESTED** [review]
javax/swing/JTree/4908142/bug4908142.java has
also shown up in some of the sightings on these
machines. You should add that one also.

java/awt/GraphicsDevice/CheckDisplayModes.java has also been
showing up recently, but it has a different failure "exit code 133".
I don't know if you want to include that one.

So there are 8 pretty much solid failures and 2 others that also
show up, but not in every run.

**Comment by prsadhuk** [comment]
javax/swing/JTree/4908142/bug4908142.java I have a separate review going on for that https://github.com/openjdk/jdk/pull/6661..It has different issue and not color related..
java/awt/GraphicsDevice/CheckDisplayModes.java also has different root cause unlike present in JDK-8277816 so I would like it to be not here..

**Review by dcubed-ojdk — APPROVED** [review]
Thanks for the clarifications!

**Pull request closed without merging**
