### PR TITLE
JDK-8264055: backout JDK-8248904 in order to resubmit with additional attribution.

### PR DESCRIPTION
**Pull request by andyherrick**
We are backing out the fix to "JDK-8248904 Add support to jpackage for the Mac App Store " in order to resubmit with added contributor attribution for Erwin Morrhey
This is the backout.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264055](https://bugs.openjdk.java.net/browse/JDK-8264055): backout JDK-8248904 in order to resubmit with additional attribution.

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - Author)
 * [Alexey Semenyuk](https://openjdk.java.net/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3159/head:pull/3159`
`$ git checkout pull/3159`

To update a local copy of the PR:
`$ git checkout pull/3159`
`$ git pull https://git.openjdk.java.net/jdk pull/3159/head`

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good, although i see the following wasn't backed out:

```
src/jdk.jpackage/macosx/classes/jdk/jpackage/internal/resources/JavaApp.icns
```

If this is intentional, then no need to worry about it.

**Comment by andyherrick** [comment]
> Looks good, although i see the following wasn't backed out:
> 
> ```
> src/jdk.jpackage/macosx/classes/jdk/jpackage/internal/resources/JavaApp.icns
> ```

yes - look again - it was renamed back to java.icns (the 12'th or 22 files changed above)

**Comment by kevinrushforth** [comment]
As long as there are no transient build/test failures, it will be fine. I was just comparing the results with what `git revert 11c8c78c47f21fcd87a5969a859b5c4fced5e47d` generated and noticed this difference.

**Comment by victordyakov** [comment]
@sashamatveev please review

**Comment by victordyakov** [comment]
@alexeysemenyukoracle please review

**Review by alexeysemenyukoracle — APPROVED** [review]

**Pull request closed without merging**
