### PR TITLE
8296426: x86: Narrow UseAVX and UseSSE flags

### PR DESCRIPTION
**Pull request by cl4es**
This patch narrows down the UseAVX and UseSSE flags to their actual supported range and uses int rather than intx for their type. This avoids need for some silly casts, and surprisingly has a small beneficial effect to binary size (-4kb libjvm on linux-x64)

This changes behavior of previously in-range values: `-XX:UseAVX=4` would emit a strongly worded warning, but with the proposed change we'll instead terminate the JVM with an error similar to `-XX:UseAVX=100`. I believe this is too trivial for a CSR, since it only changes behavior for unsupported values.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296426](https://bugs.openjdk.org/browse/JDK-8296426): x86: Narrow UseAVX and UseSSE flags

### Reviewers
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to [38939310](https://git.openjdk.org/jdk/pull/10997/files/3893931063c82a28fc5742c3ae717cbac5d41674)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10997/head:pull/10997` \
`$ git checkout pull/10997`

Update a local copy of the PR: \
`$ git checkout pull/10997` \
`$ git pull https://git.openjdk.org/jdk pull/10997/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10997`

View PR using the GUI difftool: \
`$ git pr show -t 10997`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10997.diff">https://git.openjdk.org/jdk/pull/10997.diff</a>

</details>

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Nice! Looks good.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
You need to fix these flags type in JVMCI too. JVMCI tests failed.

**Comment by cl4es** [comment]
> You need to fix these flags type in JVMCI too. JVMCI tests failed.

Fixed. Interestingly the only use of these that I could find assume the flags are `int` already (perhaps a misunderstanding of `intx`): https://github.com/openjdk/jdk/blob/master/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot.amd64/src/jdk/vm/ci/hotspot/amd64/AMD64HotSpotVMConfig.java#L45

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by cl4es** [comment]
Thanks!
/integrate

**Pull request closed without merging**
