### PR TITLE
8262476: Add filter to speed up CompileCommand lookup

### PR DESCRIPTION
**Pull request by neliasso**
This was reported as "Regression in class loading micro in 16-b27"

When adding Improving the CompileCommand flag in JDK-8256508 all commands was put in the same list (instead of an array of lists that would have been long and sparsely populated). Since commands are very uncommon that seemed like a reasonable thing - but I forgot about the JMH use case that adds a lot of inlining commands. With all commands in the same list, 1000 inlining commands will cause look-ups of all commands to take a lot of time.

This PR adds a filter so that we can quickly check if a command is present or not.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262476](https://bugs.openjdk.java.net/browse/JDK-8262476): Add filter to speed up CompileCommand lookup

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3057/head:pull/3057`
`$ git checkout pull/3057`

To update a local copy of the PR:
`$ git checkout pull/3057`
`$ git pull https://git.openjdk.java.net/jdk pull/3057/head`

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Caching information during commands registration and using it is correct fix.

From what I see `has_command()` can use `filter_check()` too.
May be rename `filter_set()` into `set_command()` or something.
Rename `filter_check()` to `has_command()` and remove old `has_command()` method.

If I understand this code correctly.

**Comment by neliasso** [comment]
> From what I see `has_command()` can use `filter_check()` too.

Good observation! That simplifies it further - and the method name is freed.

> May be rename `filter_set()` into `set_command()` or something.
> Rename `filter_check()` to `has_command()` and remove old `has_command()` method.
> 
> If I understand this code correctly.

Yes - this makes the patch even better!

Thanks!

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by neliasso** [comment]
> Looks good.

Thank you Tobias!

**Pull request closed without merging**
