### PR TITLE
8260306: Do not include osThread.hpp in thread.hpp

### PR DESCRIPTION
**Pull request by iklam**
thread.hpp is a popular header file (included by 856 out of 1000 HotSpot.o file), so we should try to minimize what files are included by thread.hpp.

We can replace the inclusion of osThread.hpp with a forward declaration of the OSThread class.

This reduces the number of .o files that include osThread.hpp to 42.

Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5. Also locally: aarch64, arm, ppc64, s390, x86, and zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260306](https://bugs.openjdk.java.net/browse/JDK-8260306): Do not include osThread.hpp in thread.hpp

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 4da3fecb438be3a065ee523098149b4744060790
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to 4da3fecb438be3a065ee523098149b4744060790

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2198/head:pull/2198`
`$ git checkout pull/2198`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good!

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Comment by iklam** [comment]
Thanks @lfoltan and @coleenp for the review!
/integrate

**Pull request closed without merging**
