### PR TITLE
8292305: [BACKOUT] JDK-8289208 Test DrawRotatedStringUsingRotatedFont.java occasionally crashes on MacOS

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit 00decca46a77ea9390081655b069008aacfea525.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292305](https://bugs.openjdk.org/browse/JDK-8292305): [BACKOUT] JDK-8289208 Test DrawRotatedStringUsingRotatedFont.java occasionally crashes on MacOS

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9864/head:pull/9864` \
`$ git checkout pull/9864`

Update a local copy of the PR: \
`$ git checkout pull/9864` \
`$ git pull https://git.openjdk.org/jdk pull/9864/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9864`

View PR using the GUI difftool: \
`$ git pr show -t 9864`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9864.diff">https://git.openjdk.org/jdk/pull/9864.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@prrace - Thanks for the fast review.

**Review by dholmes-ora — APPROVED** [review]
Backout looks accurate

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - Thanks for the review.

/integrate

**Pull request closed without merging**
