### PR TITLE
8277627: Fix copyright years in some jvmci files

### PR DESCRIPTION
**Pull request by eme64**
Fixed copyright years from "xxxx, xxxx" to "xxxx" (if same year mentioned twice), according to copyright year specification.
Updated the second year (last edit) where missing (thanks @vnkozlov for catching this).

Checked that tests are not affected.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277627](https://bugs.openjdk.java.net/browse/JDK-8277627): Fix copyright years in some jvmci files

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6985/head:pull/6985` \
`$ git checkout pull/6985`

Update a local copy of the PR: \
`$ git checkout pull/6985` \
`$ git pull https://git.openjdk.java.net/jdk pull/6985/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6985`

View PR using the GUI difftool: \
`$ git pr show -t 6985`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6985.diff">https://git.openjdk.java.net/jdk/pull/6985.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
I suggest to look on history of these files changes and update second year accordingly.
For example, `MemoryBarriers.java` was update last in 2016 based on 'Blame':
https://github.com/openjdk/jdk/commit/1d60ce77a0e169da6f1564a294f842f10e29b699

**Comment by eme64** [comment]
Thanks Vladimir (@vnkozlov) for the review, I updated the patch according to your suggestion.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Pull request closed without merging**
