### PR TITLE
8302495: update for deprecated sprintf for java.desktop

### PR DESCRIPTION
**Pull request by XueleiFan**
Hi,

May I have this update reviewed?

The sprintf is deprecated in Xcode 14 because of security concerns. The issue was addressed in [JDK-8296812](https://bugs.openjdk.org/browse/JDK-8296812) for building failure, and [JDK-8299378](https://bugs.openjdk.org/browse/JDK-8299378)/[JDK-8299635](https://bugs.openjdk.org/browse/JDK-8299635)/[JDK-8301132](https://bugs.openjdk.org/browse/JDK-8301132) for testing issues . This is a break-down update for sprintf uses in java.desktop components.

Thanks,
Xuelei

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302495](https://bugs.openjdk.org/browse/JDK-8302495): update for deprecated sprintf for java.desktop

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12565/head:pull/12565` \
`$ git checkout pull/12565`

Update a local copy of the PR: \
`$ git checkout pull/12565` \
`$ git pull https://git.openjdk.org/jdk pull/12565/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12565`

View PR using the GUI difftool: \
`$ git pr show -t 12565`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12565.diff">https://git.openjdk.org/jdk/pull/12565.diff</a>

</details>

### CODE REVIEW

**Comment by SWinxy** [comment]
Looks good.

**Comment by prrace** [comment]
This is a fairly extensive set of changes so I'll contact you off-line to make sure you have done adequate testing.

Also the changes in freetype must be reverted. This is a 3rd party library.

**Comment by XueleiFan** [comment]
> This is a fairly extensive set of changes so I'll contact you off-line to make sure you have done adequate testing.

Thank you for your looking into the issue.

I'm new to java.desktop.  Exception the regression tests, what else should I run to make sure everything is OK?  Can someone in Oracle help me run Mach5 jobs for tier1, tier2 and jdk_desktop?

> Also the changes in freetype must be reverted. This is a 3rd party library.

The update in freetype was reverted.

**Comment by prrace** [comment]
> > This is a fairly extensive set of changes so I'll contact you off-line to make sure you have done adequate testing.
> 
> Thank you for your looking into the issue.
> 
> I'm new to java.desktop. Exception the regression tests, what else should I run to make sure everything is OK? Can someone in Oracle help me run Mach5 jobs for tier1, tier2 and jdk_desktop?
> 
> > Also the changes in freetype must be reverted. This is a 3rd party library.
> 
> The update in freetype was reverted.

Sorry, I got sidetracked away from this, so let me submit a test job to our internal CI system which should cover this.
Note that "tier1 and tier2" are utterly irrelevant to any code in the java.desktop module.  A complete waste of time running them.
Same for github actions.

**Review by prrace — APPROVED** [review]
Testing looks good. Approved.

**Pull request closed without merging**
