### PR TITLE
8320317: ObjectMonitor NotRunnable is not really an optimization

### PR DESCRIPTION
**Pull request by fbredber**
The performance on stable / reproducible performance tests increase with up to 12% on x86 based platforms if we remove ObjectMonitor::NotRunnable(). The performance decrease seen on AArch64 based macOS can be fixed by implementing SpinPause() (see: JDK-8321371).

This PR removes ObjectMonitor::NotRunnable().

Tested successfully on tier1-tier5.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320317](https://bugs.openjdk.org/browse/JDK-8320317): ObjectMonitor NotRunnable is not really an optimization (**Enhancement** - P4)

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17050/head:pull/17050` \
`$ git checkout pull/17050`

Update a local copy of the PR: \
`$ git checkout pull/17050` \
`$ git pull https://git.openjdk.org/jdk.git pull/17050/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17050`

View PR using the GUI difftool: \
`$ git pr show -t 17050`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17050.diff">https://git.openjdk.org/jdk/pull/17050.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17050#issuecomment-1850226196)

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Red lines are the bestkind of lines. Looks great!

**Review by dholmes-ora — APPROVED** [review]
Looks good! Thanks for the performance results.

**Review by shipilev — APPROVED** [review]
Gonna miss those salty comments:

```
// Spinning while the owner is OFFPROC is idiocy.
```

**Comment by fbredber** [comment]
Thanks for the review guys. But I don't want to integrate it before the SpinPause() discussions in https://github.com/openjdk/jdk/pull/16994 is resolved, because that would lead to a regression on AArch64 based MacOSX.

As soon as I feel more confident working in this code base I will try to add some salty comments, it certainly does adds some enjoyment to the source code reading experience. It also makes you remember the code better, which is always a good thing.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

If removing `NotRunnable()` resulted in better performance on macosx-aarch64,
that implies that the optimization "worked" for some reason on that platform
while it did not "work" on linux-x64 or windows-x64. The perf comment in the
JBS doesn't mention perf results for macosx-x64 one way or the other.

I understand the `SpinPause()` fix (see: [JDK-8321371](https://bugs.openjdk.org/browse/JDK-8321371))
helps macosx-aarch64, but do we understand exactly what helped
macosx-aarch64 in `NotRunnable()`? Similarly, do we understand exactly
what hurt linux-x64 and windows-x64 in `NotRunnable()`?

**Pull request closed without merging**
