### PR TITLE
8298913: Add override qualifiers to Relocation classes

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the Relocation classes, adding `override`
qualifiers to all overriding virtual function declarations.

Testing:
mach5 tier1

Note that building with clang (on macosx) subjected these changes to clang's
`-Winconsistent-missing-override` option.

Note that there are a lot of member functions missing `const` qualifiers in
the Relocation hierarchy.  I may look at improving const-correctness later.
After doing a little exploration down that path, it looks like it might be a
bit messy.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298913](https://bugs.openjdk.org/browse/JDK-8298913): Add override qualifiers to Relocation classes

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [236514d5](https://git.openjdk.org/jdk/pull/11716/files/236514d511f36f2b231fd87b7729178ed29d01e5)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer) ⚠️ Review applies to [236514d5](https://git.openjdk.org/jdk/pull/11716/files/236514d511f36f2b231fd87b7729178ed29d01e5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11716/head:pull/11716` \
`$ git checkout pull/11716`

Update a local copy of the PR: \
`$ git checkout pull/11716` \
`$ git pull https://git.openjdk.org/jdk pull/11716/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11716`

View PR using the GUI difftool: \
`$ git pr show -t 11716`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11716.diff">https://git.openjdk.org/jdk/pull/11716.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Comment by kimbarrett** [comment]
Thanks for reviews @vnkozlov and @xmas92 .

**Pull request closed without merging**
