### PR TITLE
8334357: Use NonInterleavingLogStream for report_metadata_oome

### PR DESCRIPTION
**Pull request by xmas92**
When `report_metadata_oome` occurs it usually occurs for multiple threads at once. Unless `tid` is used in the logging output it is very hard to understand what logging belongs together.

Log using a `NonInterleavingLogStream` so that the multi-line and multi-level logging from each thread does not get interleaved.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334357](https://bugs.openjdk.org/browse/JDK-8334357): Use NonInterleavingLogStream for report_metadata_oome (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19770/head:pull/19770` \
`$ git checkout pull/19770`

Update a local copy of the PR: \
`$ git checkout pull/19770` \
`$ git pull https://git.openjdk.org/jdk.git pull/19770/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19770`

View PR using the GUI difftool: \
`$ git pr show -t 19770`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19770.diff">https://git.openjdk.org/jdk/pull/19770.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19770#issuecomment-2175993434)

### CODE REVIEW

**Review by jdksjolen — APPROVED** [review]

**Comment by jdksjolen** [comment]
The NonInterleavingLogStream works by buffering its output before flushing to output, so is there a risk that the logging itself will fail since this is an OOME?

**Comment by xmas92** [comment]
> The NonInterleavingLogStream works by buffering its output before flushing to output, so is there a risk that the logging itself will fail since this is an OOME?

I tried to reason about this as well. The common reason to get here should be that we are hitting JVM limits on metaspace, not because of native memory exhaustion. It seems unlikely that we would even manage to get to this point if the system resources are so constrained that a buffer cannot be allocated. (We run a whole GC cycle before throwing the OOME).

**Comment by xmas92** [comment]
@tstuefe Maybe you can give a second review here.

**Comment by tstuefe** [comment]
> @tstuefe Maybe you can give a second review here.

I'm enjoying post-JVMLS flu; may take me some time to get to it

**Comment by xmas92** [comment]
> > @tstuefe Maybe you can give a second review here.
> 
> I'm enjoying post-JVMLS flu; may take me some time to get to it

Yeah no problem. Get well soon!

**Review by tstuefe — APPROVED** [review]
Looks reasonable

**Comment by xmas92** [comment]
Thanks for the reviews.
/integrate

**Pull request closed without merging**
