### PR TITLE
8305341: Alignment should be enforced by alignas instead of compiler specific attributes

### PR DESCRIPTION
**Pull request by TheShermanTanker**
C11 has been stable for a long time on all platforms, so native code can use the standard alignas operator for alignment requirements

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305341](https://bugs.openjdk.org/browse/JDK-8305341): Alignment should be enforced by alignas instead of compiler specific attributes (**Enhancement** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13258/head:pull/13258` \
`$ git checkout pull/13258`

Update a local copy of the PR: \
`$ git checkout pull/13258` \
`$ git pull https://git.openjdk.org/jdk.git pull/13258/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13258`

View PR using the GUI difftool: \
`$ git pr show -t 13258`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13258.diff">https://git.openjdk.org/jdk/pull/13258.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13258#issuecomment-1491356232)

### CODE REVIEW

**Comment by plummercj** [comment]
I don't have any comments on this change in general (it's not something I've dealt with in the past), but I did notice that there are a couple of places you missed:

```
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:119:#define ATTRIBUTE_ALIGNED(x) __declspec(align(x))
src/java.desktop/share/native/libfreetype/include/freetype/internal/ftvalid.h:82:  /* __declspec(align())' in order to compile cleanly with */
src/java.desktop/share/native/libfreetype/src/smooth/ftgrays.c:484:  /* __declspec(align())' in order to compile cleanly with */
```

For the 2nd and 3rd ones you would want to remove all of the following:

```
#if defined( _MSC_VER )      /* Visual C++ (and Intel C++) */
  /* We disable the warning `structure was padded due to   */
  /* __declspec(align())' in order to compile cleanly with */
  /* the maximum level of warnings.                        */
#pragma warning( push )
#pragma warning( disable : 4324 )
#endif /* _MSC_VER */
...
#if defined( _MSC_VER )
#pragma warning( pop )
#endif
```

**Comment by TheShermanTanker** [comment]
I don't think I can touch the freetype code since I think it's an external library that was imported. HotSpot requires a special review for changes like this, so it's not done here, but instead at https://github.com/openjdk/jdk/pull/11431 (Which has dried up for a long time now, would be great if someone finally looked at that PR...)

**Comment by TheShermanTanker** [comment]
Just checked, the pragmas in the freetype code now seems to be pointless since there is no alignment specified in the code it's supposed to guard. Maybe upstream will fix this someday :/

**Comment by plummercj** [comment]
> I don't think I can touch the freetype code since I think it's an external library that was imported. HotSpot requires a special review for changes like this, so it's not done here, but instead at #11431 (Which has dried up for a long time now, would be great if someone finally looked at that PR...)

Ok. What about the globalDefinitions_visCPP.hpp reference?

**Comment by TheShermanTanker** [comment]
globalDefinitions_visCPP.hpp (and the corresponding globalDefinitions file for gcc based compilers) are both hotspot code, which require special review and are done in another Pull Request: https://github.com/openjdk/jdk/pull/11431

It would be great if Reviewers would take a look at that PR though...

**Comment by plummercj** [comment]
I'm not sure what you mean by hotspot requiring a special review, but serviceability code does require two reviewers just like hotspot does. Also, you don't need to split the PR because of that. If you get one person to review the jdk changes and 2 to review the hostpot/svc changes, then you are good to go.

**Comment by TheShermanTanker** [comment]
Hmm, right I'll link that issue into this one as well then

**Comment by kimbarrett** [comment]
I was pretty confused by the C changes for a while, since I didn't know or had
forgotten that the 32bit Windows ABI only guarantees 4 byte stack alignment,
and permits "misaligned" local variables for types such as long long and
double.  (And I failed to find any definitive documentation for that.)  Yuck!

What is the purpose of removing `defined(_MSC_VER)` from the conditionals?  Is
this to allow for other compilers that similarly only ensure 4 byte alignment
of the stack?  If so, it would have been nice to mention that separate concern
in the PR description, rather than making reviewers guess.  And do such
compilers actually exist?  A bit of research suggests gcc (at least) maintains
16 byte alignment (and may warrant the use of -mstackrealign or other hoops).
See, for example, https://github.com/uTox/uTox/issues/1304.

Is `defined(_WIN32)` really the right conditional?  That's true for pretty
much any Visual Studio supported target, both 32bit and 64bit.  But the
alignment spec is effectively a nop for 64bit platforms, so harmless.

**Comment by TheShermanTanker** [comment]
> What is the purpose of removing `defined(_MSC_VER)` from the conditionals? Is this to allow for other compilers that similarly only ensure 4 byte alignment of the stack? If so, it would have been nice to mention that separate concern in the PR description, rather than making reviewers guess. And do such compilers actually exist? A bit of research suggests gcc (at least) maintains 16 byte alignment (and may warrant the use of -mstackrealign or other hoops). See, for example, [uTox/uTox#1304](https://github.com/uTox/uTox/issues/1304).

Admittedly I wasn't sure what the alignment specifier here was for either, but assumed that it was something that was simply required for Windows code, and since _MSC_VER is always the only compiler (for now) that can compile Windows code, the check seemed pretty pointless. It seemed logical then that even if another compiler was added to the mix Windows code would still be under said ABI restrictions, hence the removal of that conditional. I'm now no longer as certain that this is always the case and can revert those changes if that check turns out to be correct

> Is `defined(_WIN32)` really the right conditional? That's true for pretty much any Visual Studio supported target, both 32bit and 64bit. But the alignment spec is effectively a nop for 64bit platforms, so harmless.

Perhaps, since this pretty much specifies that only Windows code should be affected by the alignment (Irrespective of this change). Others might disagree here, though

> I was pretty confused by the C changes for a while, since I didn't know or had forgotten that the 32bit Windows ABI only guarantees 4 byte stack alignment, and permits "misaligned" local variables for types such as long long and double. (And I failed to find any definitive documentation for that.) Yuck!

Haha, that's Microsoft for you ;)

**Comment by TheShermanTanker** [comment]
Well, that's unfortunate

**Comment by TheShermanTanker** [comment]
Bumping

**Comment by TheShermanTanker** [comment]
Anyone?

**Comment by TheShermanTanker** [comment]
Bumping

**Comment by TheShermanTanker** [comment]
@djelinski Sorry for the tag, it's just that this PR has been collecting dust for months now

**Comment by djelinski** [comment]
Hi @TheShermanTanker these alignment instructions were introduced in JDK-8220348 and JDK-8239856 to deal with Windows 32 failures. Windows 32 build is going away soon. As far as I could tell, the declspec was only introduced to deal with an overzealous assert.

@TheRealMDoerr @RealCLanger @tstuefe @sspitsyn since you were responsible for the introduction of the alignment specifiers, could you help with reviewing this?

**Comment by TheShermanTanker** [comment]
Bumping

**Review by TheRealMDoerr — APPROVED** [review]

**Comment by dholmes-ora** [comment]
@TheShermanTanker  this is causing build failures in our CI in tier1:
```
 c:\sb\prod\1687737602\workspace\open\src\jdk.jdwp.agent\share\native\libjdwp\ArrayReferenceImpl.c(26): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory
```

**Comment by dholmes-ora** [comment]
Filed: [JDK-8310863](https://bugs.openjdk.org/browse/JDK-8310863)

**Pull request closed without merging**
