### PR TITLE
8257140: Crash in JvmtiTagMap::flush_object_free_events()

### PR DESCRIPTION
**Pull request by coleenp**
The JvmtiTagMap can be deleted while it is posting.  The JvmtiEnv is still on the list but the env is "disposed" of and the tag_map is deleted to save memory until the JvmtiEnv can be reclaimed at a safepoint and taken off the list.

There's a check JvmtiEnvBase::check_for_periodic_clean_up() that determines whether the JvmtiEnv can be taken off the list and that check looks for whether threads are in the middle of JvmtiEnvIterator which sets Thread::jvmti_env_iteration_count.  So this part is safe for the JvmtiTagMap changes.

The fix is to clear the JvmtiTagMapTable of the entries inside the table lock to save memory but leave JvmtiTagMap intact so that we can load a valid pointer when iterating through JvmtiEnvIterator.  We could also not do this at all and let the JvmtiTagMap destructor delete the table when the JvmtiEnv is also deleted, but we don't know what customer situation led to this code in the first place.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257140](https://bugs.openjdk.java.net/browse/JDK-8257140): Crash in JvmtiTagMap::flush_object_free_events()

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1539/head:pull/1539`
`$ git checkout pull/1539`

### CODE REVIEW

**Comment by coleenp** [comment]
Test passed tier1-3 with no failures.

**Comment by dcubed-ojdk** [comment]
> Test passed tier1-3 with no failures.
Tier5 and Tier6 have more JPDA testing (JVM/TI, JDWP, JDI, ...)

**Comment by coleenp** [comment]
tier 4,5,6 pass with no failures.

**Review by sspitsyn — COMMENTED** [review]
Hi Coleen,

The JVMTI environment can be disposed with DisposeEnvironment:
  https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#DisposeEnvironment
It seems to me that this operation is better to wait until posting is finished. Otherwise, the information is going to be lost in the report. Of course, we could blame the agent to call the DisposeEnvironment too early but then the agent needs a way to check if posting is finished.

Thanks,
Serguei

**Review by sspitsyn — APPROVED** [review]
This is reasonable. Thank you for the explanation!
The fix looks good to me.

> When the event is disposed, it calls set_event_callbacks()...
You, probably meant "environment" is disposed, not "event".
This correction is for other readers.  :)

**Review by kimbarrett — APPROVED** [review]

**Comment by coleenp** [comment]
Thanks Serguei and Kim for the reviews.
/integrate

**Pull request closed without merging**
