### PR TITLE
8245026: PsAdaptiveSizePolicy::_old_gen_policy_is_ready is unused

### PR DESCRIPTION
**Pull request by jaokim**
`PsAdaptiveSizePolicy::_old_gen_policy_is_ready` is initialized, is assigned, and has an accessor, but is never read and the accessor is never called. 
Browsing through some repository history, shows no apparent evidence of it ever being used.

Testing: tier1, tier2, tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ❌ (2/2 failed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x64 (build debug)](https://github.com/jaokim/jdk/runs/1453606716)
- [Linux x64 (build release)](https://github.com/jaokim/jdk/runs/1453606697)
- [Linux x86 (build debug)](https://github.com/jaokim/jdk/runs/1453606877)
- [Linux x86 (build release)](https://github.com/jaokim/jdk/runs/1453606851)

### Issue
 * [JDK-8245026](https://bugs.openjdk.java.net/browse/JDK-8245026): PsAdaptiveSizePolicy::_old_gen_policy_is_ready is unused

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1434/head:pull/1434`
`$ git checkout pull/1434`

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good.

**Review by pliden — APPROVED** [review]
Looks good.

**Comment by jaokim** [comment]
Thank you @kstefanj and @pliden!

/integrate

**Pull request closed without merging**
