### PR TITLE
8300032: DwarfParser resource leak

### PR DESCRIPTION
**Pull request by djelinski**
Please review this fix for DwarfParser cleaner.

The original code registered the cleaner using a lambda that captured a reference to the parser object; as a result, the object was never GCed, and the cleaner never ran.

In this version I moved the lambda creation to a static method, so that it can't capture a reference to the parser.

Additionally, the new code uses a static cleaner; the cleaner object creation and cleanup are heavy operations (every cleaner comes with its own thread), and it's preferable to use a single shared cleaner where possible.

I verified manually that the native `destroyDwarfContext` method is called after this fix. No new automated test. Existing tier1-2 tests continue to pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300032](https://bugs.openjdk.org/browse/JDK-8300032): DwarfParser resource leak

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11965/head:pull/11965` \
`$ git checkout pull/11965`

Update a local copy of the PR: \
`$ git checkout pull/11965` \
`$ git pull https://git.openjdk.org/jdk pull/11965/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11965`

View PR using the GUI difftool: \
`$ git pr show -t 11965`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11965.diff">https://git.openjdk.org/jdk/pull/11965.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — COMMENTED** [review]
Though I am not a usual reviewer for this area I believe the logic of your change is good.
Please obtain the review from a maintainer of the area before integrating.

**Review by plummercj — COMMENTED** [review]
This seems like a pretty serious flaw with using Lambdas and Cleaners that probably should be brought up with the libs and language teams. I see other occurrences of this issue in these files (I may have missed some):

src/java.base/share/classes/com/sun/crypto/provider/*Key.java (4 files)
src/java.base/windows/classes/java/lang/ProcessImpl.java
src/java.desktop/share/classes/javax/swing/border/TitledBorder.java
src/java.desktop/share/classes/javax/swing/filechooser/FileSystemView.java

**Review by sspitsyn — APPROVED** [review]
This looks good modulo there can be more issues like that as Chris mentioned.
Thanks,
Serguei

**Comment by djelinski** [comment]
> This seems like a pretty serious flaw with using Lambdas and Cleaners that probably should be brought up with the libs and language teams.

They are aware of this issue; it's even mentioned in [this article](https://inside.java/2022/05/25/clean-cleaner/):
> For example, if `chars` is a field, the lambda could refer to `this.chars` inadvertently capturing `this`. [...] One way to ensure that this is not captured is to create the lambda in a static method. Its scope does not have this so it cannot accidentally be captured.

As far as I could tell, the cleaners you pointed out use local variables only. As long as the lambda does not reference any object fields or instance methods, `this` is not captured.

**Comment by plummercj** [comment]
> As far as I could tell, the cleaners you pointed out use local variables only. As long as the lambda does not reference any object fields or instance methods, `this` is not captured.

Ok. So the lambda needs to reference a field of the `this` in order to capture `this`. I guess that's why you see hacks like this:

        // Register a cleaning function to close the handle
        final long local_handle = handle;    // local to prevent capture of this
        CleanerFactory.cleaner().register(this, () -> closeHandle(local_handle));

**Review by plummercj — APPROVED** [review]

**Pull request closed without merging**
