### PR TITLE
8283728: jdk.hotspot.agent: Wrong location for RISCV64ThreadContext.java

### PR DESCRIPTION
**Pull request by RealCLanger**
Fix risv64 -> riscv64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283728](https://bugs.openjdk.java.net/browse/JDK-8283728): jdk.hotspot.agent: Wrong location for RISCV64ThreadContext.java

### Reviewers
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - Committer)
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7977/head:pull/7977` \
`$ git checkout pull/7977`

Update a local copy of the PR: \
`$ git checkout pull/7977` \
`$ git pull https://git.openjdk.java.net/jdk pull/7977/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7977`

View PR using the GUI difftool: \
`$ git pr show -t 7977`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7977.diff">https://git.openjdk.java.net/jdk/pull/7977.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Thanks for finding this typo. 
Looks good to me. (Not a JDK Reviewer)

**Review by DamonFool — APPROVED** [review]
Looks reasonable to me.

**Review by dholmes-ora — APPROVED** [review]
Good catch!

**Comment by RealCLanger** [comment]
Interestingly, the thing compiles as the package name inside of RISCV64ThreadContext.java is correct and the compiler doesn't bother about the path. Only my Eclipse IDE complained.

Thanks for the reviews.

/integrate

**Pull request closed without merging**
