### PR TITLE
8306457: Classfile API components implementations should not be exposed

### PR DESCRIPTION
**Pull request by liach**
The jdk.internal.classfile.components package's interfaces have implementations in their nested classes, which are implicitly public and exported with the package. They are now moved to the impl package to avoid unwanted exposures. Fixed a few minor javadoc issues in the interfaces as well.

In conflict with #13021; one needs updating if the other is merged.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306457](https://bugs.openjdk.org/browse/JDK-8306457): Classfile API components implementations should not be exposed

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13541/head:pull/13541` \
`$ git checkout pull/13541`

Update a local copy of the PR: \
`$ git checkout pull/13541` \
`$ git pull https://git.openjdk.org/jdk.git pull/13541/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13541`

View PR using the GUI difftool: \
`$ git pr show -t 13541`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13541.diff">https://git.openjdk.org/jdk/pull/13541.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13541#issuecomment-1515082727)

### CODE REVIEW

**Comment by liach** [comment]
@asotona Can you take a look at this proposal to move implementation records to the impl package since they shouldn't be public nested members of interfaces?

**Review by asotona — COMMENTED** [review]
I would prefer to keep formatting when moving large block of code from one source file to another. It is very hard to diff and requires deep review otherwise.

**Comment by liach** [comment]
I've kept the formatting by simply removing the extra indent in the beginning. However, the two implementation constructors need to be promoted to public in order to be accessible from outside of the impl package.

**Comment by liach** [comment]
/integrate

Fyi a similar accessibility issue for interfaces is tracked at https://bugs.openjdk.org/browse/JDK-8308040
Luckily, we don't appear to have package-private interfaces or classes in the (planned to be) exported packages of Classfile API, so we should be safe aside from this component implementation.

**Pull request closed without merging**
