### PR TITLE
8268094: Some vmTestbase/nsk tests fail after ACC_STRICT/strictfp changes

### PR DESCRIPTION
**Pull request by dholmes-ora**
Part of the JEP-306 integration wasn't tested past tier 3 and missed some changes needed in the vmTestbase/nsk tests. The crux of the changes for JEP-306 are that the strictfp modifier has no affect any more (all fp math is strict) and is not observable as a modifier. At the VM level ACC_STRICT is no longer defined for classfiles version 61+ (ie JDK 17+).

Affected tests:

- vmTestbase/nsk/jvmti/GetMethodModifiers/methmod001/

This test has a part that expects to read the ACC_STRICT modifier for a strictfp method - so that part is just deleted.

Other jvmti test files refer to ACC_STRICT (but don't test anything) and so those references are also deleted.

- vmTestbase/nsk/jdi/VirtualMachine/redefineClasses/redefineclasses007.java
- vmTestbase/nsk/jdi/VirtualMachine/redefineClasses/redefineclasses008.java

These each have two subtests (07 and 08) that test changing the strictfp modifier on a method. These subtests are just deleted.

Testing:
 - local testing of affected test areas
 - tiers 1-5 also submitted for good measure (but may take a while to run and should not delay getting these fixes in places so that the CI returns to normal - thanks).

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268094](https://bugs.openjdk.java.net/browse/JDK-8268094): Some vmTestbase/nsk tests fail after ACC_STRICT/strictfp changes

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Robbin Ehn](https://openjdk.java.net/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4302/head:pull/4302` \
`$ git checkout pull/4302`

Update a local copy of the PR: \
`$ git checkout pull/4302` \
`$ git pull https://git.openjdk.java.net/jdk pull/4302/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4302`

View PR using the GUI difftool: \
`$ git pr show -t 4302`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4302.diff">https://git.openjdk.java.net/jdk/pull/4302.diff</a>

</details>

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by dholmes-ora** [comment]
Thanks @iwanowww !

**Review by robehn — APPROVED** [review]
Seems good!

**Pull request closed without merging**
