### PR TITLE
8317535 Shenandoah: Remove unused code

### PR DESCRIPTION
**Pull request by earthling-amzn**
Tested with `hotspot_gc_shenandoah`, `specjbb`, `specjvm`, `dacapo`, `extremem` and `heapothesys`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317535](https://bugs.openjdk.org/browse/JDK-8317535): Shenandoah: Remove unused code (**Task** - P4)

### Reviewers
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16104/head:pull/16104` \
`$ git checkout pull/16104`

Update a local copy of the PR: \
`$ git checkout pull/16104` \
`$ git pull https://git.openjdk.org/jdk.git pull/16104/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16104`

View PR using the GUI difftool: \
`$ git pr show -t 16104`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16104.diff">https://git.openjdk.org/jdk/pull/16104.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16104#issuecomment-1753353978)

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Nice cleanup! Thank you!
I'm really quite baffled by some of it, but OTOH, in all cases it looks obviously ok if compiler doesn't complain. *shrugs*

**Review by ysramakrishna — APPROVED** [review]
Nice clean up indeed; thank you!

I am in awe of how you found these (discarded) needles in the proverbial haystack.

**Comment by earthling-amzn** [comment]
/integrate

The power of the IDE!

**Pull request closed without merging**
