### PR TITLE
JDK-8277420: Provide a way to copy the hyperlink to a doc element to the clipboard

### PR DESCRIPTION
**Pull request by hns**
This is a CSS/JavaScript only change to implement copy-to-clipboard functionality for all headers (`h1` - `h6`) that have an `id` attribute associated with them. The following element-attribute patterns are supported (using `<h2>` as an example):

 - `<section id="..."><h2>` (generated by javadoc)
 - `<h2 id="...">` (commonly used)
 - `<h2><a id="...">` (legacy)

The change includes a consolidation of the CSS styles used to render copy-to-clipboard buttons, of which we have now three kinds: for snippets, for the link on the search page, and for headers. There is now a base CSS class called "copy" that defines the styles shared by all copy-to-clipboard buttons, and additional CSS properties for the concrete "subclasses". 

API docs generated with this change can be viewed here (top level files and java.base module):
http://cr.openjdk.java.net/~hannesw/8277420/api.03/

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8277420](https://bugs.openjdk.java.net/browse/JDK-8277420): Provide a way to copy the hyperlink to a doc element to the clipboard

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8817/head:pull/8817` \
`$ git checkout pull/8817`

Update a local copy of the PR: \
`$ git checkout pull/8817` \
`$ git pull https://git.openjdk.java.net/jdk pull/8817/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8817`

View PR using the GUI difftool: \
`$ git pr show -t 8817`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8817.diff">https://git.openjdk.java.net/jdk/pull/8817.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
Very nice!

I'm trying this out by getting a link to the "Signature Polymorphism" section in the class javadoc here: http://cr.openjdk.java.net/~hannesw/8277420/api.02/java.base/java/lang/invoke/MethodHandle.html

The source for that is `<h2><a id="sigpoly"></a>Signature polymorphism</h2>` but no link/copy button seems to be generated. Shouldn't this also have a button? (seems to fall in the legacy category)

**Comment by JornVernee** [comment]
It seems to work in other cases, like here: http://cr.openjdk.java.net/~hannesw/8277420/api.02/java.base/java/lang/foreign/Linker.html

Where the text is contained within the `<a>` tag.

---

Also, I notice that the button only appears after hovering over the text of the heading in the case above, but not when just hovering over the place where the button would appear itself (and not touching the text). The hover area feels a bit small. Would it be possible to make the area bigger? For instance, the entire width of the page at the height of the header? For methods this already seems to be the case as well.

**Comment by hns** [comment]
Thanks for the valuable feedback, @JornVernee! It turns out that both problems you observed (empty `<a id=...` not working at all and other "legacy" headers only showing the icon when hovering over the text) had the same cause, which was that the hover event handler was registered on the `<a>` element instead of the header. 

I've added a fix for this, you can test it here:
http://cr.openjdk.java.net/~hannesw/8277420/api.03/java.base/java/lang/invoke/MethodHandle.html#sigpoly

Regarding the size of the icon/button, it's true that it's on the smaller side. The reason is that I tried to fit it into the line size of the header both for visual and technical reasons (easier to size using relative rather than absolute measures). If it was any bigger, the header line height would increase when hovering over it. If it turns out that more people find it too small we can increase the size with a bit more work (absolute positioning and sizing).

**Comment by JornVernee** [comment]
> Regarding the size of the icon/button, it's true that it's on the smaller side. The reason is that I tried to fit it into the line size of the header both for visual and technical reasons (easier to size using relative rather than absolute measures). If it was any bigger, the header line height would increase when hovering over it. If it turns out that more people find it too small we can increase the size with a bit more work (absolute positioning and sizing).

I don't think the icon is too small. I just meant that the area where you needed to hover the mouse to make it appear seemed small. But, with your latest version it seems good to me, now that the copy button will show up when hovering anywhere on the line of the header.

**Comment by pavelrappo** [comment]
Ensure TestSnippetUnnamedPackage passes before integrating.

**Review by pavelrappo — APPROVED** [review]

**Pull request closed without merging**
