### PR TITLE
8239927: Product variable PrefetchFieldsAhead is unused and should be removed

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
The product variable "PrefetchFieldsAhead" is defined in gc_globals.hpp and set in vm_version_x86.cpp. 
But as it's not used anywhere, removing this option from the JDK source.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8239927](https://bugs.openjdk.java.net/browse/JDK-8239927): Product variable PrefetchFieldsAhead is unused and should be removed
 * [JDK-8278332](https://bugs.openjdk.java.net/browse/JDK-8278332): Product variable PrefetchFieldsAhead is unused and should be removed (**CSR**)

### Reviewers
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer) ⚠️ Review applies to bd81befb76de5ccb3b198c7b91cdc1b83f8e43b4
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6783/head:pull/6783` \
`$ git checkout pull/6783`

Update a local copy of the PR: \
`$ git checkout pull/6783` \
`$ git pull https://git.openjdk.java.net/jdk pull/6783/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6783`

View PR using the GUI difftool: \
`$ git pr show -t 6783`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6783.diff">https://git.openjdk.java.net/jdk/pull/6783.diff</a>

</details>

### CODE REVIEW

**Comment by stooart-mon** [comment]
I understand this might be a trivial fix, but reviews would be appreciated.

**Review by nsjian — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Looks good and trivial.

Thanks,
David

**Pull request closed without merging**
