### PR TITLE
8279607: Existing optimization "~x+1" -> "-x" can be generalized to "~x+c" -> "(c-1)-x".

### PR DESCRIPTION
**Pull request by CptGit**
Hi all,

Existing optimization `~x+1 -> -x` can be generalized to `~x+c -> (c-1)-x`. I included both microbenchmark and jtreg tests.

```cpp
// Convert (~x+c) into (c-1)-x. Note there isn't a bitwise not
// bytecode, "~x" would typically represented as "x^(-1)", so (~x+c)
// will be (x^(-1))+c.
if (op1 == Op_Xor(bt) &&
    (in2->Opcode() == Op_ConI || in2->Opcode() == Op_ConL) &&
    phase->type(in1->in(2)) == TypeInteger::minus_1(bt)) {
  Node* c_minus_one = phase->makecon(add_ring(phase->type(in(2)), TypeInteger::minus_1(bt)));
  return SubNode::make(c_minus_one, in1->in(1), bt);
}
```

Thank you for reviewing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279607](https://bugs.openjdk.java.net/browse/JDK-8279607): Existing optimization "~x+1" -> "-x" can be generalized to "~x+c" -> "(c-1)-x".

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6858/head:pull/6858` \
`$ git checkout pull/6858`

Update a local copy of the PR: \
`$ git checkout pull/6858` \
`$ git pull https://git.openjdk.java.net/jdk pull/6858/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6858`

View PR using the GUI difftool: \
`$ git pr show -t 6858`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6858.diff">https://git.openjdk.java.net/jdk/pull/6858.diff</a>

</details>

### CODE REVIEW

**Comment by CptGit** [comment]
Attach benchmark results:

Baseline:
```
Benchmark                       Mode  Cnt  Score   Error  Units
AddIdealNotXPlusC.baselineInt   avgt   60  1.479 ± 0.004  ns/op
AddIdealNotXPlusC.baselineLong  avgt   60  1.479 ± 0.006  ns/op
AddIdealNotXPlusC.testInt       avgt   60  3.142 ± 0.019  ns/op
AddIdealNotXPlusC.testLong      avgt   60  3.150 ± 0.019  ns/op
```

Patch:
```
Benchmark                       Mode  Cnt  Score   Error  Units
AddIdealNotXPlusC.baselineInt   avgt   60  1.489 ± 0.008  ns/op
AddIdealNotXPlusC.baselineLong  avgt   60  1.488 ± 0.007  ns/op
AddIdealNotXPlusC.testInt       avgt   60  0.343 ± 0.001  ns/op
AddIdealNotXPlusC.testLong      avgt   60  0.343 ± 0.001  ns/op
```

**Review by TobiHartmann — COMMENTED** [review]
Isn't the same applicable to the corresponding `XoINode` and `XorLNode` optimizations?

https://github.com/openjdk/jdk/blob/126328cb6218a93d23ed6169d7e52fb2719528ed/src/hotspot/share/opto/addnode.cpp#L877-883

**Comment by CptGit** [comment]
> Isn't the same applicable to the corresponding `XoINode` and `XorLNode` optimizations?
> 
> https://github.com/openjdk/jdk/blob/126328cb6218a93d23ed6169d7e52fb2719528ed/src/hotspot/share/opto/addnode.cpp#L877-L883

Great catch, thanks. I included similar transformation for `XorINode` and `XorLNode`.

**Review by TobiHartmann — APPROVED** [review]
That looks good to me and all testing passed.

You need a second review.

**Comment by CptGit** [comment]
> That looks good to me and all testing passed.
> 
> You need a second review.

Thanks for reviewing.

**Review by vnkozlov — APPROVED** [review]
Good.

**Pull request closed without merging**
