### PR TITLE
8274396: Suppress more warnings on non-serializable non-transient instance fields in client libs

### PR DESCRIPTION
**Pull request by jddarcy**
Follow-up changes to JDK-8231334. , augmentations to javac's Xlint:serial checking are out for review (#5709) and various client libraries would need some changes to pass under the expanded checks.

The changes are to suppress warnings where non-transient fields in serializable types are not declared with a type statically known to be serializable. That isn't necessarily a correctness issues, but it does merit further scrutiny.

I'll run a script to update the copyright year before pushing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274396](https://bugs.openjdk.java.net/browse/JDK-8274396): Suppress more warnings on non-serializable non-transient instance fields in client libs

### Reviewers
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**) ⚠️ Review applies to ab72612d52cb2f53a65079f7820f38f9278bcf4b
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to ab72612d52cb2f53a65079f7820f38f9278bcf4b
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5723/head:pull/5723` \
`$ git checkout pull/5723`

Update a local copy of the PR: \
`$ git checkout pull/5723` \
`$ git pull https://git.openjdk.java.net/jdk pull/5723/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5723`

View PR using the GUI difftool: \
`$ git pr show -t 5723`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5723.diff">https://git.openjdk.java.net/jdk/pull/5723.diff</a>

</details>

### CODE REVIEW

**Review by bplb — APPROVED** [review]

**Review by naotoj — APPROVED** [review]

**Comment by mrserb** [comment]
Can we add comments to SuppressWarnings on why it was added? Previously we use this text
> // Not statically typed as Serializable

**Review by mrserb — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
I like the comments indicating why the suppression is needed.

**Pull request closed without merging**
