### PR TITLE
8267726: ZGC: array_copy_requires_gc_barriers too strict

### PR DESCRIPTION
**Pull request by neliasso**
I found some cases where an arraycopy clone is eliminated with G1 but not with ZGC. This is probably something that wasn't updated fully after the transition to late gc barrier insertion.

During parse and optimizaton phases array_copy_requires_gc_barriers should return false for clones of oop-arrays. Clone of oop-arrays should be treated the same way as clones of primitive-arrays. During optimization phase - only clones of instances should return true - and that's because they can't be reduced to a raw bulk copy, Clones of instances must either become deconstructed into field copies, or be handled in a special call.

During expansion array_copy_requires_gc_barriers must return true - because we must use a copy with barriers.

To fix this I had to add an extra field to array_copy_requires_gc_barriers to be able to handle instance clones separately. I will follow up with a cleanup. The intersection of arraycopy-kinds and array_copy_requires_gc_barriers-method is the source of much unnecessary complexity. 

Please review,
Best regards,
Nils Eliasson

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267726](https://bugs.openjdk.java.net/browse/JDK-8267726): ZGC: array_copy_requires_gc_barriers too strict

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4230/head:pull/4230` \
`$ git checkout pull/4230`

Update a local copy of the PR: \
`$ git checkout pull/4230` \
`$ git pull https://git.openjdk.java.net/jdk pull/4230/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4230`

View PR using the GUI difftool: \
`$ git pr show -t 4230`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4230.diff">https://git.openjdk.java.net/jdk/pull/4230.diff</a>

</details>

### CODE REVIEW

**Comment by neliasso** [comment]
Moved to hotspot-compiler

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. Please file a cleanup RFE and link it to this bug. Also, this might be a good candidate for adding a regression test once the IR verification framework is there.

**Comment by neliasso** [comment]
I filed RFE https://bugs.openjdk.java.net/browse/JDK-8268020

Yes - all the arraycopy and clone tests should be ported to IR verification. I might do that as a part of the RFE.

Thanks for the review Tobias!

**Comment by neliasso** [comment]
Thanks for the reviews, Tobias and Vladimir.

/integrate

**Pull request closed without merging**
