### PR TITLE
8263203: jconsole Online User Guide has wrong URL

### PR DESCRIPTION
**Pull request by plummercj**
The URL for the users guide, referenced from both the About dialog and from the "Help -> Online Users Guide" menu item, has not functioned for a few releases due the restructuring of the JDK online docs. This PR fixes the URL. Note I also filed JDK-8268351 to get rid of the URL, but for 17 I prefer to just fix the URL.

BTW, the change to MANAGE_HOTSPOT_MBEANS_IN_COLON_ is just my editor automatically getting rid of an extra space at the end of the line.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263203](https://bugs.openjdk.java.net/browse/JDK-8263203): jconsole Online User Guide has wrong URL

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4399/head:pull/4399` \
`$ git checkout pull/4399`

Update a local copy of the PR: \
`$ git checkout pull/4399` \
`$ git pull https://git.openjdk.java.net/jdk pull/4399/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4399`

View PR using the GUI difftool: \
`$ git pr show -t 4399`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4399.diff">https://git.openjdk.java.net/jdk/pull/4399.diff</a>

</details>

### CODE REVIEW

**Comment by mlchung** [comment]
Hi Chris, 

It has been a while but I think this may intend to link to the User Guide (not the tool reference)
   https://docs.oracle.com/en/java/javase/16/management/using-jconsole.html

**Comment by plummercj** [comment]
> Hi Chris,
> 
> It has been a while but I think this may intend to link to the User Guide (not the tool reference)
> https://docs.oracle.com/en/java/javase/16/management/using-jconsole.html

I think you are right. And there is a reference to jconsole.html from using-jconsole.html, so  you can still get to it. I'll make the switch.

**Comment by plummercj** [comment]
...although I'm uncertain how to get to .../management/using-jconsole.html using the "lookup" syntax as was done for getting to jconsole.html. Will need to ask someone on the docs teame.

**Comment by plummercj** [comment]
> Try "using_jconsole"

I already did. No luck.

**Comment by plummercj** [comment]
Actually that does work. My URL was using 17, which doesn't exist yet, but it seems to work with 16.

**Review by mlchung — APPROVED** [review]
Looks good.

**Comment by AlanBateman** [comment]
No objection to this change but I think we should create a follow-on issue to drop this link from the About page. That will also avoid needing to periodically test that the link still works.

**Comment by plummercj** [comment]
Thanks Mandy!

Can I get one more review please?

**Review by dholmes-ora — APPROVED** [review]
LGTM!

Thanks,
David

**Pull request closed without merging**
