### PR TITLE
8308906: Make CIPrintCompilerName a diagnostic flag

### PR DESCRIPTION
**Pull request by iklam**
Please review a very simple change. This makes it easy to see which JIT compiler is used to compile each method:

```
java -XX:+UnlockDiagnosticVMOptions -XX:+PrintCompilation -XX:+CIPrintCompilerName  -jar MyApp.java
```

CSR is not needed because this is a diagnostic VM option.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308906](https://bugs.openjdk.org/browse/JDK-8308906): Make CIPrintCompilerName a diagnostic flag

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14161/head:pull/14161` \
`$ git checkout pull/14161`

Update a local copy of the PR: \
`$ git checkout pull/14161` \
`$ git pull https://git.openjdk.org/jdk.git pull/14161/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14161`

View PR using the GUI difftool: \
`$ git pr show -t 14161`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14161.diff">https://git.openjdk.org/jdk/pull/14161.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14161#issuecomment-1563496209)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Please, also fix name duplication in output:
```
C1:     79 C1:   1       3       java.lang.Object::<init> (1 bytes)
```

**Comment by vnkozlov** [comment]
UL output is correct (no duplication):
```
[0.055s][debug][jit,compilation] C1:   1       3       java.lang.Object::<init> (1 bytes)
```

**Comment by iklam** [comment]
> Please, also fix name duplication in output:
> 
> ```
> C1:     79 C1:   1       3       java.lang.Object::<init> (1 bytes)
> ```

Fixed.

**Review by tstuefe — APPROVED** [review]
That is very useful.

**Comment by iklam** [comment]
Thanks @vnkozlov and @tstuefe for the review.
/integrate

**Pull request closed without merging**
