### PR TITLE
8256843: [PPC64] runtime/logging/RedefineClasses.java fails with assert: registers not saved on stack

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Method handle logging is broken in fastdebug builds. Problem is that os::current_frame() doesn't return the right frame in fastdebug builds.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8256843](https://bugs.openjdk.java.net/browse/JDK-8256843): [PPC64] runtime/logging/RedefineClasses.java fails with assert: registers not saved on stack

### Reviewers
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - Committer) ⚠️ Review applies to 99f9a85bde274c3bf492c4b73e0d68a59785235f

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1394/head:pull/1394`
`$ git checkout pull/1394`

### CODE REVIEW

**Review by reinrich — APPROVED** [review]
Looks good to me.

**Comment by TheRealMDoerr** [comment]
Thanks for the review!
Unfortunatly, it's still not fully tested because PPC build is currently broken. I'll check again later.

**Comment by TheRealMDoerr** [comment]
Tests have passed in the meantime.

**Comment by TheRealMDoerr** [comment]
This solution still breaks NMT stack traces which require special os::current_frame().

**Pull request closed without merging**
