### PR TITLE
8262379: Add regression test for JDK-8257746

### PR DESCRIPTION
**Pull request by jerboaa**
Fails prior the patch of JDK-8257746, passes after. As expected.

Thoughts?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262379](https://bugs.openjdk.java.net/browse/JDK-8262379): Add regression test for JDK-8257746

### Reviewers
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2725/head:pull/2725`
`$ git checkout pull/2725`

### CODE REVIEW

**Comment by jerboaa** [comment]
@poonamparhar @hseigel Could you please take a look? It's just a simple regression test for the JDK-8257746 NPE regression.

**Review by hseigel — APPROVED** [review]
The new tests looks good.  Thanks for adding it.

Harold

**Comment by jerboaa** [comment]
Thanks for the review @hseigel!

**Pull request closed without merging**
