### PR TITLE
8306632: Add a JDK Property for specifying DTD support

### PR DESCRIPTION
**Pull request by JoeWang-Java**
Add a JDK Impl specific property 'jdk.xml.dtd.support' for applications to specify how DTDs are handled. This property is uniformly supported across the JDK XML libraries. It complements, rather than replaces, the existing properties that are supportDTD for StAX and disallow-doctype-decl for DOM and SAX processors, which means the later will continue to work as they were and that if they are set, the new property will have no effect. Applications that use the existing properties continue to work as expected.

   This patch continues the path made previously with Xalan and XPath in which functions were moved into the jdk/xml classes. Similar changes are now made with the Xerces and XML classes, consolidating functions into the jdk/xml classes, reducing duplicate code for easier future maintenance.

Tests: new tests are added to cover the various processors.
       Existing tests pass. Only one was updated due to the change to the property impl.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8306633](https://bugs.openjdk.org/browse/JDK-8306633) to be approved

### Issues
 * [JDK-8306632](https://bugs.openjdk.org/browse/JDK-8306632): Add a JDK Property for specifying DTD support (**Enhancement** - P4)
 * [JDK-8306633](https://bugs.openjdk.org/browse/JDK-8306633): Add a JDK Property for specifying DTD support (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Stuart Marks](https://openjdk.org/census#smarks) (@stuart-marks - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15075/head:pull/15075` \
`$ git checkout pull/15075`

Update a local copy of the PR: \
`$ git checkout pull/15075` \
`$ git pull https://git.openjdk.org/jdk.git pull/15075/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15075`

View PR using the GUI difftool: \
`$ git pr show -t 15075`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15075.diff">https://git.openjdk.org/jdk/pull/15075.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15075#issuecomment-1656292152)

### CODE REVIEW

**Comment by AlanBateman** [comment]
I think you've got this to a good place and brings uniformity to configuring how all the processors deal with DTDs. The proposal in the CSR is approved now so hopefully you'll get Reviewer cycles to help move forward on this.

**Comment by JoeWang-Java** [comment]
> I think you've got this to a good place and brings uniformity to configuring how all the processors deal with DTDs. The proposal in the CSR is approved now so hopefully you'll get Reviewer cycles to help move forward on this.

Thanks Alan!  And with that, you voided Git bot's warning (inactive for more than 4 weeks, blah) :-)

**Review by LanceAndersen — APPROVED** [review]
Hi Joe,

I have made a few passes through the code and overall I think it is OK.

Nothing jumped out and was glaringly wrong given you have touched a large number  of classes and added a fair amount of additional tests

**Review by stuart-marks — APPROVED** [review]
OK I looked through a bunch of the code and I didn't see anything that needs to be changed right now. However I did spot a number of issues for future work. :-)

Good to see the duplicate XMLSecurityManager has been removed. However (not part of this diff) I note that there are two XMLSecurityPropertyManager classes in xerces and xalan. The code between them seems quite similar, so this might be an opportunity for future deduplication.

Most of the logic around handling of properties and config settings looks like it's in jdk/xml/internal. There are bunches of enums here and String arrays indexed by enum ordinals, plus things that search the enum values() arrays. It seems like some things could be done to improve the internal representation of this information, both to reduce the amount of code, and to make things easier for clients of this information.

It looks like ValueMapper1 is unused.

In XMLDTDScannerImpl.java line 391 this line is inserted:

```
   fEntityScanner = fEntityManager.getEntityScanner();
```

The addition of this line kind of sticks out. The initial value of this field is null. This assignment is done repeatedly in a bunch of places; but other places just assume the field has been initialized. Was this an NPE, and are there possibilities of NPE in other code paths?

I think the thing to do is to integrate this code as is, since it's already been tested, and then identify a few candidates for cleanup work. Then chip away at some cleanups in parallel with pursuing other design activities (e.g., Catalog).

**Comment by JoeWang-Java** [comment]
Thanks Stuart! Will integrate after re-run tests. Will look into the cleanups, along with the ones you suggested during the last review.

**Comment by JoeWang-Java** [comment]
Tier1 and Tier3 passed! Tier2 with one known failure (intermittent).

**Pull request closed without merging**
