### PR TITLE
8274299: Make Method/Constructor/Field accessors @Stable

### PR DESCRIPTION
**Pull request by plevart**
This patch improves reflective access speed as shown by the included benchmarks:

https://jmh.morethan.io/?gists=902f4b43519c4f96c7abcd14cdc2d27d,ac490481e3001c710d75d6071c10b23a

... and is also a prerequisite to make JEP 416 (Reimplement Core Reflection with Method Handle) perform better in some circumstances.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274299](https://bugs.openjdk.java.net/browse/JDK-8274299): Make Method/Constructor/Field accessors @Stable

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5694/head:pull/5694` \
`$ git checkout pull/5694`

Update a local copy of the PR: \
`$ git checkout pull/5694` \
`$ git pull https://git.openjdk.java.net/jdk pull/5694/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5694`

View PR using the GUI difftool: \
`$ git pr show -t 5694`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5694.diff">https://git.openjdk.java.net/jdk/pull/5694.diff</a>

</details>

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
This looks good, assuming Mandy is OK with extracting and adding to the microbenchmarks from JEP 416

A stray thought is why not most fields in `Field`/`Method`/`Constructor` are `final`, as my IDE suggests. I can't find any hotspot code that injects values to these fields. Experimentally changing most fields in `Field` to final seem to pass at least all the java/lang/reflect tests. Since this is a trusted package `@Stable` should then be pointless.

**Comment by mlchung** [comment]
Adding to Peter's description - separating this patch from JEP 416 will give some bake time on this change of the existing core reflection implementation.  When JEP 416 is integrated, it will switch the new implementation and the changes in `*AccessorImpl` will not be exercised.   In addition, this will make the backport easier if desirable.

**Comment by mlchung** [comment]
> This looks good, assuming Mandy is OK with extracting and adding to the microbenchmarks from JEP 416

I'm okay to include these microbenchmarks in this patch.   I will merge the change with JEP 416.

> A stray thought is why not most fields in `Field`/`Method`/`Constructor` are `final`, as my IDE suggests. I can't find any hotspot code that injects values to these fields. 

See `Reflection::new_method` and `Reflection::new_field`.

> Experimentally changing most fields in `Field` to final seem to pass at least all the java/lang/reflect tests. Since this is a trusted package `@Stable` should then be pointless.
   
This reminds to double check [1] and realized that `java.lang.reflect` is not in the list of trusted packages for `@Stable`.  I'll add that in JEP 416.

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/ci/ciField.cpp#L219

**Review by mlchung — APPROVED** [review]
Looks good to me.   Very nice performance improvement.

One minor comment: I think the change in `UnsafeFieldAccessorImpl.java` and `UnsafeStaticFieldAccessorImpl.java` isn't necessary since they're final fields.

**Comment by mlchung** [comment]
> A stray thought is why not most fields in `Field`/`Method`/`Constructor` are `final`, as my IDE suggests. I can't find any hotspot code that injects values to these fields. Experimentally changing most fields in `Field` to final seem to pass at least all the java/lang/reflect tests. Since this is a trusted package `@Stable` should then be pointless.

This is a good observation.  I took another look.    The only place to set those fields are in `Reflection:new_field/new_method/new_constructor`.    Making the fields that set by the Method/Field/Constructor constructor be final is a good idea!  Those final fields don't need to be `@Stable`.   

One thing I'm puzzling is why the performance result is better but `java.lang.reflect` is not in the TNSFF package list.

**Comment by cl4es** [comment]
> One thing I'm puzzling is why the performance result is better but `java.lang.reflect` is not in the TNSFF package list.

I think for deciding if a field can be treated as constant, `@Stable` has equal weight as a final in a TNSFF package, see https://github.com/openjdk/jdk/blob/master/src/hotspot/share/ci/ciField.cpp#L287

Adding java/lang/reflect to the trusted package list seem reasonable, though.

**Comment by cl4es** [comment]
This looks good, assuming Mandy is OK with extracting and adding to the microbenchmarks from JEP 416

A stray thought is why not most fields in `Field`/`Method`/`Constructor` are `final`, as my IDE suggests. I can't find any hotspot code that injects values to these fields. Experimentally changing most fields in `Field` to final seem to pass at least all the java/lang/reflect tests. 

> This reminds to double check [1] and realized that `java.lang.reflect` is not in the list of trusted packages for `@Stable`. I'll add that in JEP 416.
> 
> [1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/ci/ciField.cpp#L219

Gotcha, I misremembered it as-if all packages under java/lang were already considered to be in that list.

**Comment by plevart** [comment]
> Looks good to me. Very nice performance improvement.
> 
> One minor comment: I think the change in `UnsafeFieldAccessorImpl.java` and `UnsafeStaticFieldAccessorImpl.java` isn't necessary since they're final fields. It can be reverted.

There are two changes in `UnsafeFieldAccessorImpl.java` and `UnsafeStaticFieldAccessorImpl.java`. One is making `fieldOffset` and `base` (for static fields) @Stable and the other is moving `field` one level up to `FieldAccessorImpl` and making it @Stable. This later change is not necessary for this patch, but I noticed that you did that in JEP 416 so that `field` is common to all subclasses of `FieldAccessorImpl` including those that you are adding in JEP 416. I can undo this later change. But making fields @Stable does improve performance since `jdk.internal.reflect` and `java.lang.reflect` are not final-field-trusted packages as you noted above. If JEP 416 makes them trusted, it can also remove the @Stable annotations. But for backporting, they better stay there. WDYT?

**Comment by plevart** [comment]
> A stray thought is why not most fields in `Field`/`Method`/`Constructor` are `final`, as my IDE suggests. I can't find any hotspot code that injects values to these fields. Experimentally changing most fields in `Field` to final seem to pass at least all the java/lang/reflect tests. Since this is a trusted package `@Stable` should then be pointless.

I made them final in newly added patch now. So we can either merge this or previous commit if desired.

**Comment by cl4es** [comment]
Does `Reflection::new_method/...` (which are natively implemented constructors) need any special treatment for them to follow the same semantics as a Java-based constructor w.r.t. final field writes? Or could they be rewritten to call the equivalent java constructor in each case?

We lack a microbenchmark for `Constructor`, but I suspect it might be a similar improvement to annotate the same fields in `Constructor` with  `@Stable`. If not else it seems prudent to be consistent.

**Comment by plevart** [comment]
> Does `Reflection::new_method/...` (which are natively implemented constructors) need any special treatment for them to follow the same semantics as a Java-based constructor w.r.t. final field writes? Or could they be rewritten to call the equivalent java constructor in each case?
> 

I don't think they need special treatment currently. The Method/Constructor/Field instances created by native code and returned via native methods are always the `root` objects that are never handed to user code. They are used internally in the caches and are published to other threads via volatile field write/read (see `java.lang.Class.ReflectionData`). User code only sees copies of those objects which are performed using constructors.

**Comment by mlchung** [comment]
> making fields @stable does improve performance since `jdk.internal.reflect` and `java.lang.reflect` are not final-field-trusted packages as you noted above. If JEP 416 makes them trusted, it can also remove the @stable annotations. But for backporting, they better stay there. WDYT?

Thanks for clarifying it.   Okay to keep those changes. 

> I made them final in newly added patch now. So we can either merge this or previous commit if desired.

I would suggest to use the previous commit so that this patch focuses on this specific change - making the accessor @Stable.   We can make the fields final together with adding `jdk.internal.reflect` and `java.lang.reflect` in the trusted packages for TNSFF in JEP 416.

**Comment by cl4es** [comment]
I'm fine with going back to the previous iteration. I'd add `@Stable` to the same fields in `Constructor`, too, though.

**Comment by plevart** [comment]
> I'm fine with going back to the previous iteration. I'd add `@Stable` to the same fields in `Constructor`, too, though.

Good catch. I'll add @stable to select Constructor fields. They are important for optimizing `Const` use cases. I'll also extend benchmarks to include Constructor accesses.

**Comment by plevart** [comment]
> > I'm fine with going back to the previous iteration. I'd add `@Stable` to the same fields in `Constructor`, too, though.
> 
> Good catch. I'll add @stable to select Constructor fields. They are important for optimizing `Const` use cases.

I checked the git history. `@Stable` annotation was added to `Method::clazz` and `Method::modifiers` fields as part of "JDK-8159746: (proxy) Support for default methods" to speed-up checks since Method instances in Proxy class are assigned to static final fields so this is an example of "Const" use case. But reflective access uses those two fields to perform access checks too, so it makes sense to add @stable to those fields in Field and Constructor classes too.

**Comment by mlchung** [comment]
> One way this could be improved is to "stamp" the modifiers field with an additional bit (say 0x8000_0000) to always hold a non-zero value. Method::getModifiers() would then clear that bit in a returned value to stay compatible. Native Method/Field/Constructor construction would have to be modified too.

Alternatively, it'd become a non-issue when `java.lang.reflect` and `jdk.internal.reflect` are added to the trusted final-field packages.

**Comment by forax** [comment]
Can you surreptitiously add "java.lang" too (asking for a friend)

**Comment by mlchung** [comment]
`java.lang` is already trusted [1].

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/ci/ciField.cpp#L219

**Comment by forax** [comment]
I miss that, that very cool.

**Comment by plevart** [comment]
I added Constructor benchmarks in latest commit. Here are the results:

https://jmh.morethan.io/?gists=f57a49ce833d5a53a01ce996570c11d2,de4a8a4b7ddc4bec1090d2113d9c50e6

I rest now, waiting for comments.

**Review by mlchung — APPROVED** [review]
Looks good.

**Review by cl4es — APPROVED** [review]
Excellent, thanks!

**Pull request closed without merging**
