### PR TITLE
8340843: [PPC64/s390x] Error: ShouldNotReachHere() in TemplateInterpreterGenerator::generate_math_entry after 8338694

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
[JDK-8338694](https://bugs.openjdk.org/browse/JDK-8338694) introduced `Interpreter::java_lang_math_tanh` which needs to be handled by the interpreter. Unfortunately, `SharedRuntime::dtanh` does not exist, so we need to fallback to the normal interpreter entry (as before JDK-8338694).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340843](https://bugs.openjdk.org/browse/JDK-8340843): [PPC64/s390x] Error: ShouldNotReachHere() in TemplateInterpreterGenerator::generate_math_entry after 8338694 (**Bug** - P1)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21168/head:pull/21168` \
`$ git checkout pull/21168`

Update a local copy of the PR: \
`$ git checkout pull/21168` \
`$ git pull https://git.openjdk.org/jdk.git pull/21168/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21168`

View PR using the GUI difftool: \
`$ git pr show -t 21168`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21168.diff">https://git.openjdk.org/jdk/pull/21168.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21168#issuecomment-2372306585)

### CODE REVIEW

**Comment by offamitkumar** [comment]
@TheRealMDoerr can you include change for s390x as well, please: 
```diff
diff --git a/src/hotspot/cpu/s390/templateInterpreterGenerator_s390.cpp b/src/hotspot/cpu/s390/templateInterpreterGenerator_s390.cpp
index c16e4449045..0f35393a460 100644
--- a/src/hotspot/cpu/s390/templateInterpreterGenerator_s390.cpp
+++ b/src/hotspot/cpu/s390/templateInterpreterGenerator_s390.cpp
@@ -1224,6 +1224,7 @@ address TemplateInterpreterGenerator::generate_math_entry(AbstractInterpreter::M
     case Interpreter::java_lang_math_sin  : runtime_entry = CAST_FROM_FN_PTR(address, SharedRuntime::dsin);   break;
     case Interpreter::java_lang_math_cos  : runtime_entry = CAST_FROM_FN_PTR(address, SharedRuntime::dcos);   break;
     case Interpreter::java_lang_math_tan  : runtime_entry = CAST_FROM_FN_PTR(address, SharedRuntime::dtan);   break;
+    case Interpreter::java_lang_math_tanh : /* run interpreted */ break;
     case Interpreter::java_lang_math_abs  : /* run interpreted */ break;
     case Interpreter::java_lang_math_sqrt : /* runtime_entry = CAST_FROM_FN_PTR(address, SharedRuntime::dsqrt); not available */ break;
     case Interpreter::java_lang_math_log  : runtime_entry = CAST_FROM_FN_PTR(address, SharedRuntime::dlog);   break;
```

**Comment by TheRealMDoerr** [comment]
@offamitkumar: Please review!

**Review by MBaesken — APPROVED** [review]

**Review by offamitkumar — APPROVED** [review]
Thank you  for adding the s390x changes :-)

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews! Pre-submit cross build for s390x is successful.
/integrate

**Pull request closed without merging**
