### PR TITLE
8295269: G1: Improve slow startup due to predictor initialization

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that decreases the time it takes to adapt the predictors to actual values during startup.

Currently predictors are initialized using compiled-in values. These values are extremely conservative as they have been based on some SPARC test runs on specjbb2000(?) or so, which means that it takes a while until the weights from these values are "gone" from the predictor sequences. (This can take 20-30 GCs).

The change modifies prediction so that only the first prediction will use these pre-baked values, after that use live values.

This makes G1 adapt much more quickly to the current application/environment.

The drawback is that there may be differences (including regressions) in out-of-box performance because the initial garbage collections heavily impact heap expansion, potentially expanding the heap much less, resulting in less throughput. I.e. in the old policy we may do many more GCs during startup, causing higher cpu time ratio at that time, expanding more (than necessary).

GC cpu usage with the new policy is still well within allowed range wrt to cpu time ratio.

This also does not impact reasonable test setups.

Testing: gha, internal performance benchmarks mostly show no change or improvements. There are some regressions that are "fixed" by setting min/max heap size indicating this is a heap sizing difference caused by differences due to faster startup.

Hth,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295269](https://bugs.openjdk.org/browse/JDK-8295269): G1: Improve slow startup due to predictor initialization (**Enhancement** - P4)

### Reviewers
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)
 * [Stefan Johansson](https://openjdk.org/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21518/head:pull/21518` \
`$ git checkout pull/21518`

Update a local copy of the PR: \
`$ git checkout pull/21518` \
`$ git pull https://git.openjdk.org/jdk.git pull/21518/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21518`

View PR using the GUI difftool: \
`$ git pr show -t 21518`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21518.diff">https://git.openjdk.org/jdk/pull/21518.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21518#issuecomment-2421771618)

### CODE REVIEW

**Comment by tschatzl** [comment]
The GHA failures are due to some script not being found i.e. infrastructure issue afaict.

**Review by walulyai — APPROVED** [review]
LGTM!

**Review by kstefanj — APPROVED** [review]
Looks good.

**Comment by tschatzl** [comment]
Thanks @kstefanj @walulyai for your reviews.

/integrate

**Pull request closed without merging**
