### PR TITLE
8258814: Compilation logging crashes for thread suspension / debugging tests

### PR DESCRIPTION
**Pull request by yftsai**
A compile task skips the compilation if breakpoints are present in the method to compile. Since logging, enabled by +LogCompilation, expects a failure reason if the compilation was not successful, an assertion is triggered. This fix sets the failure reason for this case.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258814](https://bugs.openjdk.java.net/browse/JDK-8258814): Compilation logging crashes for thread suspension / debugging tests

### Reviewers
 * [Xin Liu](https://openjdk.java.net/census#xliu) (@navyxliu - Committer)
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7137/head:pull/7137` \
`$ git checkout pull/7137`

Update a local copy of the PR: \
`$ git checkout pull/7137` \
`$ git pull https://git.openjdk.java.net/jdk pull/7137/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7137`

View PR using the GUI difftool: \
`$ git pr show -t 7137`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7137.diff">https://git.openjdk.java.net/jdk/pull/7137.diff</a>

</details>

### CODE REVIEW

**Review by navyxliu — APPROVED** [review]
That code change looks reasonable to me. 
I am not a reviewer. We still need other reviewers approve it.

**Review by phohensee — APPROVED** [review]
Lgtm.

**Pull request closed without merging**
