### PR TITLE
8341199: Use ClassFile's new API loadConstant(int)

### PR DESCRIPTION
**Pull request by wenshao**
The new API loadConstant(int) can shorten the calling path and can replace ldc when the parameter is of int/Integer type.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341199](https://bugs.openjdk.org/browse/JDK-8341199): Use ClassFile's new API loadConstant(int) (**Enhancement** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21259/head:pull/21259` \
`$ git checkout pull/21259`

Update a local copy of the PR: \
`$ git checkout pull/21259` \
`$ git pull https://git.openjdk.org/jdk.git pull/21259/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21259`

View PR using the GUI difftool: \
`$ git pr show -t 21259`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21259.diff">https://git.openjdk.org/jdk/pull/21259.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21259#issuecomment-2382876404)

### CODE REVIEW

**Review by liach — APPROVED** [review]
Indeed, loadConstant was invented to be more optimized than ldc. This can also avoid cp entries for small values and use 2-byte bipush or 1-byte constants, both smaller in size.

**Comment by cl4es** [comment]
> This can also avoid cp entries for small values and use 2-byte bipush or 1-byte constants, both smaller in size.

Yikes, I was unaware `ldc` wouldn't optimize the emitted bytecode but reading through the code and docs it's pretty obvious. Still.. why?!

**Review by cl4es — APPROVED** [review]

**Comment by wenshao** [comment]
I think loadConstant should be renamed to ldc

**Comment by dmlloyd** [comment]
I was also curious about a few other seemingly "obvious" small optimizations, like loading `-1L` as `iconst_m1; i2l` and a few other things like that. Some of these depend on whether you happen to already have a constant pool entry for a value, but some (like this example) are either equivalent or better (in size) under all circumstances.

**Comment by cl4es** [comment]
I consider this a bug in the API, too. Perhaps we could assert against usage that would have been better expressed as a `loadConstant`?

**Comment by cl4es** [comment]
I'm in favor of removing `ldc(ConstantDesc)`, keeping the `ldc(LoadableConstantEntry)` for advanced uses. It's easier to add something back in once the API has finalized if it's really needed than to remove it, but if we leave this as-is we'll be doomed to trip over this over and over.

**Comment by liach** [comment]
@wenshao You can integrate this patch early even though it's much less than 24 hours. I have another patch that removes `ldc(ConstantDesc)`. It depends on your patch being integrated first.

**Pull request closed without merging**
