### PR TITLE
8285915: failure_handler: gather the contents of /etc/hosts file

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which addresses https://bugs.openjdk.java.net/browse/JDK-8285915?

With this change, the environment details collected by the failure handler will now include the contents of the `/etc/hosts/` file, which can be useful in certain cases when debugging network tests that fail.

Testing done (on macOS):

```
cd test/failure_handler 
make test
```
Then verified that the generated environment.html had the `/etc/hosts` file content

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285915](https://bugs.openjdk.java.net/browse/JDK-8285915): failure_handler: gather the contents of /etc/hosts file

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 673fd0bdedc8555862d1c9079e8f0539e72d0488
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8466/head:pull/8466` \
`$ git checkout pull/8466`

Update a local copy of the PR: \
`$ git checkout pull/8466` \
`$ git pull https://git.openjdk.java.net/jdk pull/8466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8466`

View PR using the GUI difftool: \
`$ git pr show -t 8466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8466.diff">https://git.openjdk.java.net/jdk/pull/8466.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by jaikiran** [comment]
Hello Erik,

> Not sure if it's relevant, but did you consider doing this for Windows as well? The file is located at `"$WINDIR/System32/drivers/etc/hosts"`.

I hadn't investigated what the corresponding command would be for Windows, so had left it out. Quick question - the path you note, is that even applicable for x64? I see that it has a "System32" so just curious. I'll experiment a bit shortly against some CI setups to see how this goes on Windows.

**Comment by erikj79** [comment]
> Quick question - the path you note, is that even applicable for x64? I see that it has a "System32" so just curious. 

Yes, System32 is not related to 32 vs 64 bit. As I understand it, that name was introduced when moving from 16 to 32 bit.

**Comment by jaikiran** [comment]
Hello Erik, I've updated the PR to include capturing the contents of hosts file even on Windows. I've tested this against an internal Windows system where it correct shows the content:

```
----------------------------------------
[2022-05-02 06:08:52] [C:\cygwin\bin\bash.exe, -c, cat $WINDIR/System32/drivers/etc/hosts] timeout=20000
----------------------------------------
# ....

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
----------------------------------------
[2022-05-02 06:08:52] exit code: 0 time: 57 ms
----------------------------------------
```

**Comment by jaikiran** [comment]
Thank you Erik and Daniel for the reviews.

**Pull request closed without merging**
