### PR TITLE
8331735: UpcallLinker::on_exit races with GC when copying frame anchor

### PR DESCRIPTION
**Pull request by JornVernee**
There is a subtle race in `UpcallLinker::on_exit` between copying of the old frame anchor back into place, and the GC. Since this copy is not atomic, it may briefly appear as if a thread has no last Java frame, while still in the `_thread_in_native` state, which leads to the GC skipping processing of any active Java frames.

This code was originally adapted from `JavaCallWrapper::!JavaCallWrapper` - the JNI mechanism for upcalls - but in that case the frame anchor copy happens in the `_thread_in_vm` state, which means the GC will wait for the thread to get to a safepoint.

The solution proposed here is to do the frame anchor copy in the java thread state, before transitioning  back to the native state. The java thread state, like the vm thread state, is also 'safe' i.e. the GC will wait for the thread to get to a safepoint, so we can safely do our non-atomic copy of the frame anchor.

Additionally, this PR resolves a similar issue in `on_entry`, by moving the clearing of the pending exception (in case native code use a JNI API and didn't handle the exception afterwards). We now also skip checking for async exceptions when transitioning from native to java, so we don't immediately clear them. Any async exceptions will be picked up at the next safepoint instead.

Special thanks to @stefank and @fisk for finding the root cause, and @jaikiran for testing and debugging.

Testing: tier 1-4, 20k runs of the failing test on linux-aarch64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8331735](https://bugs.openjdk.org/browse/JDK-8331735): UpcallLinker::on_exit races with GC when copying frame anchor (**Bug** - P3)
 * [JDK-8343144](https://bugs.openjdk.org/browse/JDK-8343144): UpcallLinker::on_entry racingly clears pending exception with GC safepoints (**Bug** - P4)
 * [JDK-8286875](https://bugs.openjdk.org/browse/JDK-8286875): ProgrammableUpcallHandler::on_entry/on_exit access thread fields from native (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21742/head:pull/21742` \
`$ git checkout pull/21742`

Update a local copy of the PR: \
`$ git checkout pull/21742` \
`$ git pull https://git.openjdk.org/jdk.git pull/21742/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21742`

View PR using the GUI difftool: \
`$ git pr show -t 21742`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21742.diff">https://git.openjdk.org/jdk/pull/21742.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21742#issuecomment-2482946451)
</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Happy to see this addressed and as Jorn noted, thanks to Stefan and Erik for finding the root cause of this issue which was hard to reproduce and debug.

**Comment by JornVernee** [comment]
> I wonder if we can assert we are in a safepoint-safe state when doing so?

I think we can do this. I've prototyped this here: https://github.com/openjdk/jdk/compare/pr/21742...JornVernee:jdk:SafeFrameAnchor+assert

This catches the issue fixed by this patch, and it passes at least tier 1. We'd need something similar in assembly where we touch the frame anchor, is `MacroAssembler::set_last_Java_frame` and `MacroAssembler::reset_last_Java_frame`.

**Comment by JornVernee** [comment]
> > I wonder if we can assert we are in a safepoint-safe state when doing so?
> 
> I think we can do this. I've prototyped this here: [pr/21742...JornVernee:jdk:SafeFrameAnchor+assert](https://github.com/openjdk/jdk/compare/pr/21742...JornVernee:jdk:SafeFrameAnchor+assert)
> 
> This catches the issue fixed by this patch, and it passes at least tier 1. We'd need something similar in assembly where we touch the frame anchor, is `MacroAssembler::set_last_Java_frame` and `MacroAssembler::reset_last_Java_frame`.

Thinking some more about this: there might be other instances of `JavaFrameAnchor` that are fine to touch when the thread is in the native state. It's just the frame anchor inside a `JavaThread` that can not be touched if that thread is in a certain state. It might be possible to encapsulate the `JavaFrameAnchor` instance inside the thread, and then guard any accesses to it. But, that seems like a much more invasive change, so I'll hold off on that and focus this PR on fixing the issue.

**Review by xmas92 — APPROVED** [review]
lgtm.

Would be nice if if we could assert that we are not in native or blocked when touching the oops as well. Similarly to modifications of the frame anchor. But I agree that it should be done separately.

**Pull request closed without merging**
