### PR TITLE
8292738 : JInternalFrame backgroundShadowBorder & foregroundShadowBorder line is longer in Mac Look and Feel

### PR DESCRIPTION
**Pull request by lawrence-andrew**
Border line is seen outside  round Rectangle both for JInternalFrame backgroundShadowBorder & foregroundShadowBorder line in mac L&F.
Screen Shot 2022-08-22 at 4 17 49 PM

I have circled the extra part of the line. To make it more visible I changed the color of the backgroundShadowBorder to red
Screen Shot 2022-08-22 at 4 17 37 PM

Fixed the extra length of the line 
Fixed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292738](https://bugs.openjdk.org/browse/JDK-8292738): JInternalFrame backgroundShadowBorder & foregroundShadowBorder line is longer in Mac Look and Feel

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9971/head:pull/9971` \
`$ git checkout pull/9971`

Update a local copy of the PR: \
`$ git checkout pull/9971` \
`$ git pull https://git.openjdk.org/jdk pull/9971/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9971`

View PR using the GUI difftool: \
`$ git pr show -t 9971`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9971.diff">https://git.openjdk.org/jdk/pull/9971.diff</a>

</details>

### CODE REVIEW

**Comment by honkar-jdk** [comment]
Tested on SwingSet2. The overhang is not prominent unless the color of the line is changed (to test & check the difference).
Overall the fix looks good. The only question might be - Is overhang the desired appearance in Aqua LAF?

**Comment by mrserb** [comment]
I assume this is not a regression and reproduced since jdk8?

**Comment by lawrence-andrew** [comment]
Yes, this is not a regression & I was able to reproduce this from 1.8.0_201

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
