### PR TITLE
New class for handling infinite-precision rationals

### PR DESCRIPTION
**Pull request by fabioromano1**
Immutable, infinite-precision signed rational numbers.

The Rational class provides operations for arithmetic, rounding, comparison, hashing, and format conversion. The toString method provides a canonical representation of a Rational. All the calculations performed have an exact result, except for the square and nth roots, in which the user can specify the rounding behavior.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11982/head:pull/11982` \
`$ git checkout pull/11982`

Update a local copy of the PR: \
`$ git checkout pull/11982` \
`$ git pull https://git.openjdk.org/jdk pull/11982/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11982`

View PR using the GUI difftool: \
`$ git pr show -t 11982`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11982.diff">https://git.openjdk.org/jdk/pull/11982.diff</a>

</details>

### CODE REVIEW

**Comment by ExE-Boss** [comment]
I think that this should use only factory methods instead of constructors, so that it can more easily migrated to a value class in the future.

**Comment by fabioromano1** [comment]
> I think that this should use only factory methods instead of constructors, so that it can more easily migrated to a value class in the future.

What do you mean by "it can more easily migrated to a value class in the future"?

**Comment by ExE-Boss** [comment]
> What do you mean by "it can more easily be migrated to a value class in the future"?

See https://openjdk.org/jeps/8277163 and https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/doc-files/ValueBased.html

**Comment by fabioromano1** [comment]
> 

Ok, but all the other numerical classes have at least a visible constructor... why this class shouldn't have one?

**Pull request closed without merging**
