### PR TITLE
8339741: RISC-V: C ABI breakage for integer on stack

### PR DESCRIPTION
**Pull request by robehn**
Hi please review,

When calling a native function using integers smaller than 64,
they must be loaded from a Java stack slot and widen to 64-bit, sign-extended.
In the interpreter case we only store 32-bit, which means the top 32-bit are 'random'.
In the compiler case we do an ld and grab random top 32-bit.
These should be loaded with a lw from Java stack, thus proper sign extended and then stored with sd into the native stack.

I found the intrepter bug first, wrote a test case for it, which found the compiler bug.

Here you can see the difference, both are legal todo from a compiler:
https://godbolt.org/z/85aMhja5f
Relevant specs:
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc
> integer scalars narrower than XLEN bits are widened according to the sign of their type up to 32 bits, then sign-extended to XLEN bits.

I checked floats also, they seems fine, but please go ahead and do a check regarding floats.

Passes ./test/hotspot/jtreg/compiler/calls/, runnnig t1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339741](https://bugs.openjdk.org/browse/JDK-8339741): RISC-V: C ABI breakage for integer on stack (**Bug** - P3)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20912/head:pull/20912` \
`$ git checkout pull/20912`

Update a local copy of the PR: \
`$ git checkout pull/20912` \
`$ git pull https://git.openjdk.org/jdk.git pull/20912/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20912`

View PR using the GUI difftool: \
`$ git pr show -t 20912`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20912.diff">https://git.openjdk.org/jdk/pull/20912.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20912#issuecomment-2337848459)

### CODE REVIEW

**Review by RealFYang — COMMENTED** [review]
Nice catch! Thanks Robbin. I am trying it on my machines. BTW: Seems this fix deserves a small code comment.

**Comment by robehn** [comment]
> Nice catch! Thanks Robbin. I am trying it on my machines. BTW: Seems this fix deserves a small code comment.

Added comment, is this what you had in mind?

**Comment by robehn** [comment]
Oh, so I have question here:
```
  } else if (dst.first()->is_stack()) {
    // reg to stack
    sd(src.first()->as_Register(), Address(sp, reg2offset_out(dst.first())));
  } else {
    if (dst.first() != src.first()) {
      sign_extend(dst.first()->as_Register(), src.first()->as_Register(), 32);
    }
  }
```
The sd is done without any sign extension, hence we must have C ABI representation in the register.
But that means the register to register case, where we have sign_extend(), is actually just a move.
AFAIK this is the case, which I hope, otherwise we have third bug here.
So I think we should use `mv` to be clear about what we are doing.

?

**Review by luhenry — APPROVED** [review]

**Comment by RealFYang** [comment]
> Oh, so I have question here:
> 
> ```
>   } else if (dst.first()->is_stack()) {
>     // reg to stack
>     sd(src.first()->as_Register(), Address(sp, reg2offset_out(dst.first())));
>   } else {
>     if (dst.first() != src.first()) {
>       sign_extend(dst.first()->as_Register(), src.first()->as_Register(), 32);
>     }
>   }
> ```
> 
> The sd is done without any sign extension, hence we must have C ABI representation in the register. But that means the register to register case, where we have sign_extend(), is actually just a move. AFAIK this is the case, which I hope, otherwise we have third bug here. So I think we should use `mv` to be clear about what we are doing.
> 
> ?

The sign_extend call here is effectively a `sext.w` instruction which simply write the sign-extension of the lower 32 bits of source into the destination. I think it's a `mv` when the source is 32-bit signed operand as in our case. So I don't see an issue here.

**Review by RealFYang — APPROVED** [review]

**Comment by robehn** [comment]
Thanks @luhenry and @RealFYang !

> (PS: Having said that, a `mv` does seem more obvious. Your call)

Thinking about it, I see sign/zero extensions bugs still pop-up in major oss, kernel, gcc, etc.., expecting us to have fixed all is a bit naive, and they are pretty easy to introduce. So my suggestion would be to go further; adding MASM methods to check register or an address for proper representation otherwise 'asserting' (in debug builds).

~Pseudo code for this case:
```
expect_state_s32(dst.first()->is_stack() ? dst.first()->as_Register() : Address(sp, reg2offset_out(dst.first())))
```

**Comment by RealFYang** [comment]
> Thanks @luhenry and @RealFYang !
> 
> > (PS: Having said that, a `mv` does seem more obvious. Your call)
> 
> Thinking about it, I see sign/zero extensions bugs still pop-up in major oss, kernel, gcc, etc.., expecting us to have fixed all is a bit naive, and they are pretty easy to introduce. So my suggestion would be to go further; adding MASM methods to check register or an address for proper representation otherwise 'asserting' (in debug builds).
> 
> ~Pseudo code for this case:
> 
> ```
> expect_state_s32(dst.first()->is_stack() ? dst.first()->as_Register() : Address(sp, reg2offset_out(dst.first())))
> ```

Yeah, that makes sense to me especially for sign extension cases. And we already have simple checks for address like in movptr: https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L1883.

**Pull request closed without merging**
