### PR TITLE
8284772: GHA: Use GCC Major Version Dependencies Only

### PR DESCRIPTION
**Pull request by gnu-andrew**
GHA regularly breaks because we specify a very explicit GCC version, even down to the release versioning of the Ubuntu package.  In just this last week, it has caused issues with the testing of PRs on 11u (https://github.com/openjdk/jdk11u-dev/pull/2084) and 17u (https://github.com/openjdk/jdk17u-dev/pull/1672)

Rather than bumping this yet again like [JDK-8313428](https://bugs.openjdk.org/browse/JDK-8313428), this PR suggests dropping the specific version as we did some time ago in 8u and have now done in 11u (https://github.com/openjdk/jdk11u-dev/pull/2087). The requirement still specifies a specific major version of GCC. It just means the dependency isn't broken every time Ubuntu bumps to a new minor release or even just makes a minor change to the package alone.

Note that the current setup does not guarantee sticking with an exact version of GCC anyway, because - as seen by recent GHA breakage - older versions get removed from the package repository. All we get from this exact version requirement is sporadic breakage of testing and developer time wasted fixing & reviewing (and, in the case of backport trees, approving). If we truly want a static version of GCC, we need to provide our own - or maybe even a full devkit - as we do with the JDK.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8284772](https://bugs.openjdk.org/browse/JDK-8284772): GHA: Use GCC Major Version Dependencies Only (**Bug** - P4)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15374/head:pull/15374` \
`$ git checkout pull/15374`

Update a local copy of the PR: \
`$ git checkout pull/15374` \
`$ git pull https://git.openjdk.org/jdk.git pull/15374/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15374`

View PR using the GUI difftool: \
`$ git pr show -t 15374`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15374.diff">https://git.openjdk.org/jdk/pull/15374.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15374#issuecomment-1687315559)

### CODE REVIEW

**Review by TheShermanTanker — APPROVED** [review]
Looks Good, but you'll need another review

**Comment by shipilev** [comment]
> Looks good.
> 
> Anyone knows whats up with riscv64, though? It worked on my GHA run from this morning https://github.com/openjdk/jdk/pull/15041/checks?check_run_id=16096790652

It's #15378, manifests in official Debian repository.

**Comment by gnu-andrew** [comment]
> This looks okay.
> 

Thanks.

> That said, it is rather unnatural to forward-port the patches. Next time, I would like to see a clean mainline RFE, which would then be cleanly backported to each of the JDK updates trees.

Agreed. I think we must have been in a rush to unbreak GHA in 8u originally and expected more pushback from trunk. No excuse though really.

**Review by erikj79 — APPROVED** [review]
In principle I very much prefer locking down dependency versions to keep the build as reliable as possible. Unfortunately, as we have experienced so far, this isn't possible with GHA because the exact package versions aren't kept available for very long. I suppose it would be possible with very diligent watching for new versions and manually testing and updating before the old version disappears, but that doesn't seem feasible in practice. On the other hand, I don't think we have actually seen any problems when bumping the versions so far, so I'm now inclined to agree with this change.

**Comment by simonis** [comment]
> In principle I very much prefer locking down dependency versions to keep the build as reliable as possible. Unfortunately, as we have experienced so far, this isn't possible with GHA because the exact package versions aren't kept available for very long. I suppose it would be possible with very diligent watching for new versions and manually testing and updating before the old version disappears, but that doesn't seem feasible in practice. On the other hand, I don't think we have actually seen any problems when bumping the versions so far, so I'm now inclined to agree with this change.

Maybe we could use [devkits](https://github.com/openjdk/jdk/blob/master/doc/building.md#cross-compiling-the-easy-way-with-openjdk-devkits) to pin the compiler version? I'm not sure how feasible that is in the GHA context. It might have a negative performance impact?

**Comment by erikj79** [comment]
> Maybe we could use [devkits](https://github.com/openjdk/jdk/blob/master/doc/building.md#cross-compiling-the-easy-way-with-openjdk-devkits) to pin the compiler version? I'm not sure how feasible that is in the GHA context. It might have a negative performance impact?

That would be preferable to me, but the main problem I see is hosting of the devkits. I can't publish such binaries. My understanding is that OpenJDK doesn't have the legal framework for hosting binaries publicly. Building them dynamically for each GHA run is definitely not feasible.

**Comment by gnu-andrew** [comment]
> In principle I very much prefer locking down dependency versions to keep the build as reliable as possible. Unfortunately, as we have experienced so far, this isn't possible with GHA because the exact package versions aren't kept available for very long. I suppose it would be possible with very diligent watching for new versions and manually testing and updating before the old version disappears, but that doesn't seem feasible in practice. On the other hand, I don't think we have actually seen any problems when bumping the versions so far, so I'm now inclined to agree with this change.

Thanks Erik. For the record, I would prefer the build environment was as stable as possible as well. I just don't think the current setup is actually achieving that, because we don't have control of these packages. As I mentioned in the PR description, if we really want that to work, we likely need to build our own compiler - or maybe even a full devkit - and provide it to the build as we do with the JDK.

My experience of working with these shifting build environments in Fedora & RHEL over the years is that versions within the same major version tend to be stable, and we've experienced all kinds of weird & wonderful breakage when Fedora brings in some new major version of GCC.  I believe this is why Ubuntu has the versioned GCC packages like `gcc-10` and I can't recall a GCC issue on RHEL, despite the GCC team providing updated builds of the same major version. If one was to occur, then it would seem preferable to catch it early in GHA and such a failure would be useful to us.

I don't think the current missing package failures we're seeing are useful and they are a particular pain in the update releases where - for good reason - it takes more work to get a change in and there is less visibility.

**Review by mrserb — APPROVED** [review]
That is great!

**Comment by gnu-andrew** [comment]
Thanks for all the reviews. I'll integrate now it's been open >24 hours.
/integrate

**Pull request closed without merging**
