### PR TITLE
8297481: Create a regression test for JDK-4424517

### PR DESCRIPTION
**Pull request by srmandal**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297481](https://bugs.openjdk.org/browse/JDK-8297481): Create a regression test for JDK-4424517

### Reviewers
 * @kiraka42 (no known github.com user name / role)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11313/head:pull/11313` \
`$ git checkout pull/11313`

Update a local copy of the PR: \
`$ git checkout pull/11313` \
`$ git pull https://git.openjdk.org/jdk pull/11313/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11313`

View PR using the GUI difftool: \
`$ git pr show -t 11313`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11313.diff">https://git.openjdk.org/jdk/pull/11313.diff</a>

</details>

### CODE REVIEW

**Comment by srmandal** [comment]
Create a regression test for JDK-4424517
Test is to verify the mapping of various KeyEvents with their KeyLocations
Test triggers events or the various Keys and ensures the KeyLocation mapping to these are accurate.

This review is for migrating tests from a closed test suite to open.

Mach5 Test Results (60 repetitions across 3 platforms)
https://mach5.us.oracle.com/mdash/jobs/jpg-closedjdk_mainline-20221123-0508-38875640

**Review by kiraka42 — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Comment by srmandal** [comment]
@mrserb  Can you please psonsor this request ?

**Comment by srmandal** [comment]
Any volunteers for sponsoring this PR ?

**Pull request closed without merging**
