### PR TITLE
8198666: Many java/awt/Modal/OnTop/ test fails on mac

### PR DESCRIPTION
**Pull request by alisenchung**
Removed passing tests from problem list

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8198666](https://bugs.openjdk.java.net/browse/JDK-8198666): Many java/awt/Modal/OnTop/ test fails on mac

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8368/head:pull/8368` \
`$ git checkout pull/8368`

Update a local copy of the PR: \
`$ git checkout pull/8368` \
`$ git pull https://git.openjdk.java.net/jdk pull/8368/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8368`

View PR using the GUI difftool: \
`$ git pr show -t 8368`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8368.diff">https://git.openjdk.java.net/jdk/pull/8368.diff</a>

</details>

### CODE REVIEW

**Review by azuev-java — APPROVED** [review]

**Comment by mrserb** [comment]
When these tests were added to the problem list all of them fail at least once in a couple of iterations, see [JDK-8198693](https://bugs.openjdk.java.net/browse/JDK-8198693). Please make sure that they are stable enough via many iterations.

**Comment by prrace** [comment]
Yeah, these modal tests were VERY unstable.  I can't think of anything we fixed which would make them stable again,
so we should repeat these tests maybe 100 times to make sure they pass before removing them.

**Comment by alisenchung** [comment]
Tests were run 100 times and passed

**Review by mrserb — APPROVED** [review]
Good to know that these tests become stable.

**Pull request closed without merging**
