### PR TITLE
8292362: java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1 failed on some platforms

### PR DESCRIPTION
**Pull request by theaoqi**
For example, java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1 failed on LoongArch64 (probably other platforms unsupported in src/java.base/share/classes/jdk/internal/foreign/CABI.java might have the same issue):
 
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported os, arch, or address size: Linux, loongarch64, 64
at java.base/jdk.internal.foreign.CABI.current(CABI.java:69)
at java.base/jdk.internal.foreign.abi.SharedUtils.getSystemLinker(SharedUtils.java:237)
at java.base/java.lang.foreign.Linker.nativeLinker(Linker.java:198)
at ImplicitAttach.main(ImplicitAttach.java:48)
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292362](https://bugs.openjdk.org/browse/JDK-8292362): java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1 failed on some platforms

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Contributors
 * Alan Bateman `<alanb@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9877/head:pull/9877` \
`$ git checkout pull/9877`

Update a local copy of the PR: \
`$ git checkout pull/9877` \
`$ git pull https://git.openjdk.org/jdk pull/9877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9877`

View PR using the GUI difftool: \
`$ git pr show -t 9877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9877.diff">https://git.openjdk.org/jdk/pull/9877.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
Linker.nativeLinker is currently specified to throw UOE so you might find the following will avoid ports needing to change the test:

```
--- a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java
+++ b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java
@@ -45,7 +45,13 @@ public class ImplicitAttach {
         }
         latch = new CountDownLatch(threadCount);
 
-        Linker abi = Linker.nativeLinker();
+        Linker abi;
+        try {
+            abi = Linker.nativeLinker();
+        } catch (UnsupportedOperationException e) {
+            System.out.println("Test skipped, no native linker on this platform");
+            return;
+        }
 
         // stub to invoke callback
         MethodHandle callback = MethodHandles.lookup()
```

**Comment by theaoqi** [comment]
> Linker.nativeLinker is currently specified to throw UOE so you might find the following will avoid ports needing to change the test less often:
> 
> ```
> --- a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java
> +++ b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java
> @@ -45,7 +45,13 @@ public class ImplicitAttach {
>          }
>          latch = new CountDownLatch(threadCount);
>  
> -        Linker abi = Linker.nativeLinker();
> +        Linker abi;
> +        try {
> +            abi = Linker.nativeLinker();
> +        } catch (UnsupportedOperationException e) {
> +            System.out.println("Test skipped, no native linker on this platform");
> +            return;
> +        }
>  
>          // stub to invoke callback
>          MethodHandle callback = MethodHandles.lookup()
> ```

This worked. Thanks, @AlanBateman ! `java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1` passed:

```
Output and diagnostic info for process 9917 was saved into 'pid-9917-output.log'
Test skipped, no native linker on this platform


[2022-08-15T13:17:02.430832622Z] Waiting for completion for process 9917
[2022-08-15T13:17:02.430922220Z] Waiting for completion finished for process 9917
STDERR:

JavaTest Message: Test complete.


TEST RESULT: Passed. Execution successful
```

**Comment by dholmes-ora** [comment]
Shouldn't we throw a SkippedException in this case?

**Comment by theaoqi** [comment]
> > Shouldn't we throw a SkippedException in this case?
> 
> It's the child VM that skips so throwing SkippedException would require special handling in the parent.

Like this?
```
diff --git a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
index b93e7918014..156bbe35c62 100644
--- a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
+++ b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
@@ -48,6 +48,8 @@ import java.util.stream.Stream;
 import jdk.test.lib.process.ProcessTools;
 import jdk.test.lib.process.OutputAnalyzer;
 
+import jtreg.SkippedException;
+
 public class AttachTest {
     static final String TEST_CLASSES = System.getProperty("test.classes");
     static final String JAVA_LIBRARY_PATH = System.getProperty("java.library.path");
@@ -63,6 +65,9 @@ public class AttachTest {
                 .executeTestJava(opts)
                 .outputTo(System.out)
                 .errorTo(System.out);
+        if (outputAnalyzer.getOutput().contains("Test skipped, no native linker on this platform")) {
+            throw new SkippedException("Test skipped, no native linker on this platform");
+        }
         outputAnalyzer.shouldHaveExitValue(0);
     }
 }
```
Do I need to add this change?

**Comment by AlanBateman** [comment]
> > > Shouldn't we throw a SkippedException in this case?
> > 
> > 
> > It's the child VM that skips so throwing SkippedException would require special handling in the parent.
> 
> Like this?
> 
> ```
> diff --git a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
> index b93e7918014..156bbe35c62 100644
> --- a/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
> +++ b/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
> @@ -48,6 +48,8 @@ import java.util.stream.Stream;
>  import jdk.test.lib.process.ProcessTools;
>  import jdk.test.lib.process.OutputAnalyzer;
>  
> +import jtreg.SkippedException;
> +
>  public class AttachTest {
>      static final String TEST_CLASSES = System.getProperty("test.classes");
>      static final String JAVA_LIBRARY_PATH = System.getProperty("java.library.path");
> @@ -63,6 +65,9 @@ public class AttachTest {
>                  .executeTestJava(opts)
>                  .outputTo(System.out)
>                  .errorTo(System.out);
> +        if (outputAnalyzer.getOutput().contains("Test skipped, no native linker on this platform")) {
> +            throw new SkippedException("Test skipped, no native linker on this platform");
> +        }
>          outputAnalyzer.shouldHaveExitValue(0);
>      }
>  }
> ```
> 
> Do I need to add this change?

That would work too but I think what you have in the PR now is okay.

**Review by AlanBateman — APPROVED** [review]

**Comment by theaoqi** [comment]
Thanks to @AlanBateman  for the review.
/integrate

**Pull request closed without merging**
