### PR TITLE
8315004: Runtime.halt() debug logging

### PR DESCRIPTION
**Pull request by masyano**
I want to add a log output similar to JDK-8301627 to Runtime.halt().
To avoid double logging of Runtime.exit(), add a flag to indicate whether logging was done, and fix it so that logging is done only once.
Could someone please review this fix?

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315004](https://bugs.openjdk.org/browse/JDK-8315004): Runtime.halt() debug logging (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15426/head:pull/15426` \
`$ git checkout pull/15426`

Update a local copy of the PR: \
`$ git checkout pull/15426` \
`$ git pull https://git.openjdk.org/jdk.git pull/15426/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15426`

View PR using the GUI difftool: \
`$ git pr show -t 15426`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15426.diff">https://git.openjdk.org/jdk/pull/15426.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15426#issuecomment-1693086562)

### CODE REVIEW

**Comment by AlanBateman** [comment]
I think you may have missed the comment in the JBS issue. Logging means running potentially arbitrary code, doing this at Runtime.halt time is problematic. I thought the conclusion from the work on Runtime.exit was not to log in Runtime.halt?

**Comment by masyano** [comment]
@AlanBateman Sorry for missing your comment on JBS. I can't find any discussion of the need for logs in Runtime.halt in JDK-8301627, so I'm not sure if it was intentional that no logging output was added to Runtime.halt.
However, if Runtime.halt is overlooked without discussion, I think it should be added after considering the need.
I think it's the same problem as Runtime.exit when it comes to executing arbitrary code.
Are there any issues specific to Runtime.halt?

**Comment by RogerRiggs** [comment]
As @AlanBateman said, the purpose of halt is to immediately exit.
If there are concerns about use of System.halt() a static scan of the class files will identify its use.

**Comment by masyano** [comment]
I agree that Runtime.halt() should be terminated immediately.
However, I don't think this logging feature is for normal use, but for troubleshooting when we can't find where Runtime.halt() is called.
So I don't think it will prevent Runtime.halt() from exiting immediately in normal operation.

**Comment by masyano** [comment]
@AlanBateman @RogerRiggs Could you comment on the above?

**Comment by merykitty** [comment]
@masyano Probably in that case a diagnostic flag that defaulted to `false` may be more reasonable.

**Comment by AlanBateman** [comment]
> @AlanBateman @RogerRiggs Could you comment on the above?

Changing Runtime.halt to log means it would not terminate immediately. It's worse: Logging is pluggable so it means logging can potentially run "faraway" and arbitrary code. We have to super cautious with logging in core classes. The conclusion from the work on Runtime.exit was to not add this logging to Runtime.halt. So I don't think the changes in the PR should be integrated.

**Comment by RogerRiggs** [comment]
As commented [above](https://github.com/openjdk/jdk/pull/15426#issuecomment-1703133971), this change should not be integrated.

**Pull request closed without merging**
