### PR TITLE
8325186: JVMTI VirtualThreadGetThreadStateClosure class is no longer used and should be removed

### PR DESCRIPTION
**Pull request by jyukutyo**
This pull request removes an unused class. 

I have investigated when this class was no longer in use. In the initial push of the virtual thread code (21972f45a64741ec3002499ef532e363cc3e9f93), there was only the definition of this class. I also checked subsequent commits, and it has never been used since the push.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325186](https://bugs.openjdk.org/browse/JDK-8325186): JVMTI VirtualThreadGetThreadStateClosure class is no longer used and should be removed (**Enhancement** - P5)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to [09af50a0](https://git.openjdk.org/jdk/pull/18341/files/09af50a0b40bca18f4c325742d5778b2ebcd6c29)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [09af50a0](https://git.openjdk.org/jdk/pull/18341/files/09af50a0b40bca18f4c325742d5778b2ebcd6c29)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18341/head:pull/18341` \
`$ git checkout pull/18341`

Update a local copy of the PR: \
`$ git checkout pull/18341` \
`$ git pull https://git.openjdk.org/jdk.git pull/18341/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18341`

View PR using the GUI difftool: \
`$ git pr show -t 18341`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18341.diff">https://git.openjdk.org/jdk/pull/18341.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18341#issuecomment-2017897456)

### CODE REVIEW

**Review by plummercj — COMMENTED** [review]
Please update copyright dates.

**Review by lmesnik — APPROVED** [review]

**Comment by sspitsyn** [comment]
> Please update copyright dates.

Need to merge with the main line which has the updated copyright headers. :)

**Review by sspitsyn — APPROVED** [review]
Looks good. Thank you for taking care about it!

**Comment by jyukutyo** [comment]
Thank you for reviewing this pull request. I've updated the copyright year.

/integrate

**Pull request closed without merging**
