### PR TITLE
8333886: Explicitly specify that asSlice and reinterpret return a memory segment backed by the same region of memory.

### PR DESCRIPTION
**Pull request by minborg**
This PR proposes to explicitly state that returned segments form the `asSlice` and `reinterpret` method share memory regions with `this` memory segment.

Note: The term "subset"  means a true subset or the same set.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warning
&nbsp;⚠️ Found trailing period in issue title for `8333886: Explicitly specify that asSlice and reinterpret return a memory segment backed by the same region of memory.`

### Issue
 * [JDK-8333886](https://bugs.openjdk.org/browse/JDK-8333886): Explicitly specify that asSlice and reinterpret return a memory segment backed by the same region of memory. (**Enhancement** - P4)

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19633/head:pull/19633` \
`$ git checkout pull/19633`

Update a local copy of the PR: \
`$ git checkout pull/19633` \
`$ git pull https://git.openjdk.org/jdk.git pull/19633/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19633`

View PR using the GUI difftool: \
`$ git pr show -t 19633`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19633.diff">https://git.openjdk.org/jdk/pull/19633.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19633#issuecomment-2158722267)

### CODE REVIEW

**Comment by JornVernee** [comment]
The term 'subset' doesn't feel right to me here, since we're only talking about a single memory region (not a set of memory region**s**). I suggest 'sub-region' instead.

**Comment by JornVernee** [comment]
> The term 'subset' doesn't feel right to me here, since we're only talking about a single memory region (not a set of memory region**s**). I suggest 'sub-region' instead.

Actually, nvm, that doesn't work for `reinterpret` since the returned segment can also cover a larger region of memory.

**Comment by tkslaw** [comment]
> > The term 'subset' doesn't feel right to me here, since we're only talking about a single memory region (not a set of memory region**s**). I suggest 'sub-region' instead.
> 
> Actually, nvm, that doesn't work for `reinterpret` since the returned segment can also cover a larger region of memory.

In my opinion, any 'sub' terminology is misleading since, as you pointed out, one can (and often will) `reinterpret` to a *larger* size. Wouldn't something like, "The returned memory segment is backed by the same region of memory that backs this memory segment", be sufficiently accurate? Could even append, "No memory will be allocated or deallocated", to really hammer the point home.

**Comment by minborg** [comment]
> In my opinion, any 'sub' terminology is misleading since, as you pointed out, one can (and often will) `reinterpret` to a _larger_ size. Wouldn't something like, "The returned memory segment is backed by the same region of memory that backs this memory segment", be sufficiently accurate? Could even append, "No memory will be allocated or deallocated", to really hammer the point home.
> 
> Using 'subset' for `asSlice` makes sense. Though possibly unnecessary.

If a segment is reinterpreted to be *larger* than `this` segment, then the extra memory is not a part of `this` segment's backing part. So, in this case the total memory is a subset (but not a _proper subset_ but rather the same) of `this` backing memory _plus_ some additional memory.

If a segment is reinterpreted to be *smaller* than `this` segment, then the reduced memory is a proper subset.

So, strictly the proposed text is correct. The proposition "The returned memory segment is backed by the same region of memory that backs this memory segment" appears to be incorrect if a _smaller_ chunk is carved out?

Maybe something more neutral like "The returned memory segment shares a region of backing memory with this segment"?

Adding text similar to "No memory will be allocated or deallocated" sounds like a good idea.

**Comment by JornVernee** [comment]
> If a segment is reinterpreted to be larger than this segment, then the extra memory is not a part of this segment's backing part.

Another way to think about this is: a segment's backing region can be larger or smaller than the bounds specified by the segment itself. Though, in most cases they are the same. For example, If we allocate 10 bytes of memory in native code, and return it to the Java side, I'd argue that the backing region of the memory segment we get back is still 10 bytes in size, even though the `byteSize()` of the memory segment is `0`. `reinterpret` can be used to adjust the size of the _segment_, but it doesn't change the size of the underlying memory region, which remains 10 bytes.

**Review by JornVernee — APPROVED** [review]
Latest version looks good to me.

**Review by mcimadamore — APPROVED** [review]

**Pull request closed without merging**
