### PR TITLE
8331202: Support for Duration until another Instant

### PR DESCRIPTION
**Pull request by naotoj**
A new method on Instant to return the duration `until` another Instant is suggested per the following discussion thread:

https://mail.openjdk.org/pipermail/core-libs-dev/2024-April/122131.html

A CSR has also been drafted.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8331215](https://bugs.openjdk.org/browse/JDK-8331215) to be approved

### Issues
 * [JDK-8331202](https://bugs.openjdk.org/browse/JDK-8331202): Support for Duration until another Instant (**Enhancement** - P4)
 * [JDK-8331215](https://bugs.openjdk.org/browse/JDK-8331215): Support for Duration until another Instant (**CSR**)

### Reviewers
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**) ⚠️ Review applies to [df2c1157](https://git.openjdk.org/jdk/pull/19007/files/df2c115765fc1486484829dee5dd8425e995b35f)
 * [Stephen Colebourne](https://openjdk.org/census#scolebourne) (@jodastephen - Author) ⚠️ Review applies to [df2c1157](https://git.openjdk.org/jdk/pull/19007/files/df2c115765fc1486484829dee5dd8425e995b35f)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19007/head:pull/19007` \
`$ git checkout pull/19007`

Update a local copy of the PR: \
`$ git checkout pull/19007` \
`$ git pull https://git.openjdk.org/jdk.git pull/19007/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19007`

View PR using the GUI difftool: \
`$ git pr show -t 19007`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19007.diff">https://git.openjdk.org/jdk/pull/19007.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19007#issuecomment-2083531518)

### CODE REVIEW

**Review by JoeWang-Java — APPROVED** [review]

**Review by jodastephen — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Comment by kluever** [comment]
Hey folks --- I'd like to have some further discussions about this proposal on the core-libs-dev mailing list. Any chance we can hold off on submitting this until those discussions are resolved? Thanks a ton!

**Comment by eamonnmcmanus** [comment]
Hi, I'm on the same team as Kurt (@kluever) and I'd like to note that we think this PR is a little premature. Discussion on the core-jdk-libs thread wasn't conclusive and we're not yet convinced that `until` is better than the `minus` that was originally proposed. Can we hold off for a bit while discussion on the thread continues?

**Comment by RogerRiggs** [comment]
@kluever Your comment isn't visible yet, there's a checkbox to accept OpenJDK terms.
It would be good to know what you've commented.

My reservation about `minus(Instant)` is that all of the current `minus(...)` methods return an `Instant` as do the `plus(...)` methods.
Adding a `minus` method that returns `Duration` adds a bit of fuzziness to the plus and minus method uses.
A similar concern could be raised about adding `Duration until(Instant)` as there is already a `until(Temporarl, TemporalUnit)` method. But there is smaller opportunity to mix them up.

**Comment by naotoj** [comment]
+1 to Roger's observation. Adding a conceptually different `minus` method would be confusing.

**Comment by naotoj** [comment]
Hearing no further comments, integrating this PR.
/integrate

**Pull request closed without merging**
