### PR TITLE
8332785: Replace naked uses of UseSharedSpaces with CDSConfig::is_using_archive

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi folks, 

This PR addresses [8332785](https://bugs.openjdk.org/browse/JDK-8332785) replacing all naked uses for ```UseSharedSpaces``` with ```CDSConfig::is_using_archive```. 

Testing: 
- [x] Tier 1 with GHA. 

Thanks, 
Sonia

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332785](https://bugs.openjdk.org/browse/JDK-8332785): Replace naked uses of UseSharedSpaces with CDSConfig::is_using_archive (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [f3e6b17c](https://git.openjdk.org/jdk/pull/19463/files/f3e6b17c7c24c220c0bd59f1f4daf35cb9c9bbc1)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [f3e6b17c](https://git.openjdk.org/jdk/pull/19463/files/f3e6b17c7c24c220c0bd59f1f4daf35cb9c9bbc1)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19463/head:pull/19463` \
`$ git checkout pull/19463`

Update a local copy of the PR: \
`$ git checkout pull/19463` \
`$ git pull https://git.openjdk.org/jdk.git pull/19463/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19463`

View PR using the GUI difftool: \
`$ git pr show -t 19463`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19463.diff">https://git.openjdk.org/jdk/pull/19463.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19463#issuecomment-2140836789)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
One minor nit but otherwise looks good.

Thanks

**Review by tstuefe — APPROVED** [review]
Looks good, minus the nit @dholmes-ora mentioned. Please make sure Copyrights are updated.

**Review by sspitsyn — APPROVED** [review]
Looks good.

**Pull request closed without merging**
