### PR TITLE
8303169: Remove Windows specific workaround from libdt

### PR DESCRIPTION
**Pull request by TheShermanTanker**
We no longer need to define PrId64 ourselves since the Visual C++ compiler supports inttypes.h on the only versions we support, so we can just replace it with an include to the standard header instead

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303169](https://bugs.openjdk.org/browse/JDK-8303169): Remove Windows specific workaround from libdt

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [e6b8b2a4](https://git.openjdk.org/jdk/pull/12744/files/e6b8b2a437dfd47c3f173d0da4c7fa35efa446a0)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [e6b8b2a4](https://git.openjdk.org/jdk/pull/12744/files/e6b8b2a437dfd47c3f173d0da4c7fa35efa446a0)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [e6b8b2a4](https://git.openjdk.org/jdk/pull/12744/files/e6b8b2a437dfd47c3f173d0da4c7fa35efa446a0)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12744/head:pull/12744` \
`$ git checkout pull/12744`

Update a local copy of the PR: \
`$ git checkout pull/12744` \
`$ git pull https://git.openjdk.org/jdk pull/12744/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12744`

View PR using the GUI difftool: \
`$ git pr show -t 12744`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12744.diff">https://git.openjdk.org/jdk/pull/12744.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]
Looks okay to me.
Thanks,
Serguei

**Comment by TheShermanTanker** [comment]
Little bit of a quick note from me before integration, I found it strange that for other platforms no inttypes.h include was needed for PRId64 to work properly, but after more in depth checking to see whether the inttypes.h include should go elsewhere to match where the other platforms have it, apparently this is a Windows only library, making it all the more strange that a Windows conditional define was here at all in the first place. Just to be extra safe, is there confirmation that this will always be Windows only, and the the shared native code is somehow a mistake or leftover from long ago?

**Comment by TheShermanTanker** [comment]
@RealCLanger Sorry for the ping, just wanted to check since you're the original commit Author for the format string, is there someplace else where inttypes.h or stdint.h is included or should be included that I missed?

**Comment by RealCLanger** [comment]
> @RealCLanger Sorry for the ping, just wanted to check since you're the original commit Author for the format string, is there someplace else where inttypes.h or stdint.h is included or should be included that I missed?

Hah, that was a long time ago. 😄 I think this change is fine - and I'm not aware of other places. But that doesn't mean a lot. 😉

**Comment by RealCLanger** [comment]
PS I guess you should update the copyright year before pushing.

**Comment by TheShermanTanker** [comment]
> PS I guess you should update the copyright year before pushing.

Ah right, thanks for the reminder



> > @RealCLanger Sorry for the ping, just wanted to check since you're the original commit Author for the format string, is there someplace else where inttypes.h or stdint.h is included or should be included that I missed?
> 
> Hah, that was a long time ago. 😄 I think this change is fine - and I'm not aware of other places. But that doesn't mean a lot. 😉

I see haha, I was just worried since that's what the ifdef implied. Strange that the check was a `#ifdef _WIN32` though since this is Windows only code (in fact I'm wondering why this file and the others in the same directory as it is in shared native code at all)

**Comment by TheShermanTanker** [comment]
Ah I see, was the initial commit made with the assumption that inttypes.h was already included? It's just a final confirmation before integration

**Comment by RealCLanger** [comment]
> Ah I see, was the initial commit made with the assumption that inttypes.h was already included? It's just a final confirmation before integration

Could be.

**Pull request closed without merging**
