### PR TITLE
8334708: FFM: two javadoc problems

### PR DESCRIPTION
**Pull request by SirYwell**
Hi all,

This pull request contains a backport of commit [72ca7baf](https://github.com/openjdk/jdk/commit/72ca7bafcd49a98c1fe09da72e4e47683f052e9d) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Hannes Greule on 22 Jun 2024 and was reviewed by Maurizio Cimadamore.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334708](https://bugs.openjdk.org/browse/JDK-8334708): FFM: two javadoc problems (**Bug** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19846/head:pull/19846` \
`$ git checkout pull/19846`

Update a local copy of the PR: \
`$ git checkout pull/19846` \
`$ git pull https://git.openjdk.org/jdk.git pull/19846/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19846`

View PR using the GUI difftool: \
`$ git pr show -t 19846`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19846.diff">https://git.openjdk.org/jdk/pull/19846.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19846#issuecomment-2184679549)

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
This doc-only clean backport looks fine to me for 23.

**Comment by SirYwell** [comment]
Thank you for your review.
/integrate

**Comment by mcimadamore** [comment]
Thanks!

**Pull request closed without merging**
