### PR TITLE
8286556: Remove EagerInitialization develop option

### PR DESCRIPTION
**Pull request by coleenp**
This is a long unused option which interferes with code I'm trying to replace, so removing it.
Tested with tier1-4.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286556](https://bugs.openjdk.java.net/browse/JDK-8286556): Remove EagerInitialization develop option

### Reviewers
 * [Robbin Ehn](https://openjdk.java.net/census#rehn) (@robehn - **Reviewer**)
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8653/head:pull/8653` \
`$ git checkout pull/8653`

Update a local copy of the PR: \
`$ git checkout pull/8653` \
`$ git pull https://git.openjdk.java.net/jdk pull/8653/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8653`

View PR using the GUI difftool: \
`$ git pr show -t 8653`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8653.diff">https://git.openjdk.java.net/jdk/pull/8653.diff</a>

</details>

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
Nice!

**Comment by cl4es** [comment]
> Do I hear a trivial?

Sure!

**Comment by coleenp** [comment]
Thanks!
/integrate

**Comment by dholmes-ora** [comment]
Interesting - for some reason I thought eager initialization was always on as it seemed a useful optimization

**Comment by cl4es** [comment]
@dholmes-ora: If this eager initialization mechanism lead to the initialization of every class that gets loaded, say for the purpose of class verification, then it could - or rather would - lead to fascinating cascades of a lot of things getting eagerly loaded (and initialized) in turn - things that would typically never be loaded or initialized otherwise. Doesn't seem very helpful as an optimization. 

Not to mention that we have roped off some initialization to inner Holder classes in tricky places of the libraries to defer the initialization of certain things until things are up and running to avoid bootstrap issues, which means forced and eager initialization might lead to any number of bootstrapping bugs.

**Comment by coleenp** [comment]
Eager initialization was sort of funny in that it only tried to initialize classes without a <clinint> function, so could provoke some class loading during linking these classes.  It wasn't all of the classes. It also had a dubious way of handling link-time exceptions.  I tried to make sense of this code, which is a waste of time, so removed it instead.

**Comment by cl4es** [comment]
Perhaps someone ran into some bootstrapping issues when it was unconstrained and tried limiting its reach like that to keep it working and still being somewhat useful? Either way I think you're right that removing it is preferable at this point (I'm biased against all the unused/untested diagnostic/develop flags, though).

**Comment by dholmes-ora** [comment]
@cl4es as Coleen explained this was an optimisation for classes with empty clinit, the intent being to mark the class as initialized upfront so that we can skip all those places where we have to check a class is initialized before we use it - that could potentially be of benefit and doesn't lead to the problems you outline. But the eager linking could potentially cause more class loading to occur at the time. 
@coleenp  if I'm reading things right if eager linking got any exceptions it would reset the state so that we'd try to re-link at the regular time. I'm not sure how valid that actually is.
In any case it was unused code so removing it is definitely the right thing.

**Pull request closed without merging**
