### PR TITLE
8332499: Gtest codestrings.validate_vm fail on linux x64 when hsdis is present

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,
  There's some arch-specific code to trim trailing entries as descripted in [JDK-8332499](https://bugs.openjdk.org/browse/JDK-8332499). Only change the gtest testcase, the risk is low.

On linux x86_64, before this PR, after deal with `std::regex_replace(tmp4, std::regex("\\s+<addr>:\\s+hlt[ \\t]+(?!\\n\\s+;;)"), "")`, the output differents because the first output has trailing empty spaces, show as below:
```log
-  <addr>:   nop    
+  <addr>:   nop
```
So we need to delete the empty spaces after `<addr>:   nop` use `std::regex_replace(tmp5, std::regex("(\\s+<addr>:\\s+nop)[ \\t]*"), "$1")`

Additional test:
- [x] codestrings.validate_vm on linux x64
- [x] codestrings.validate_vm on linux aarch64
- [x] codestrings.validate_vm on linux riscv64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8332499](https://bugs.openjdk.org/browse/JDK-8332499): Gtest codestrings.validate_vm fail on linux x64 when hsdis is present (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19309/head:pull/19309` \
`$ git checkout pull/19309`

Update a local copy of the PR: \
`$ git checkout pull/19309` \
`$ git pull https://git.openjdk.org/jdk.git pull/19309/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19309`

View PR using the GUI difftool: \
`$ git pr show -t 19309`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19309.diff">https://git.openjdk.org/jdk/pull/19309.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19309#issuecomment-2120366173)

### CODE REVIEW

**Comment by sendaoYan** [comment]
Hi, can anyone take a look at this change.

**Comment by sendaoYan** [comment]
The GHA test runner report two failures:

- gc/stringdedup/TestStringDeduplicationInterned.java#Shenandoah fails on linux x86_32: Deduplication has not occurred, load history: min: 0.9901123046875, max: 1.079345703125, I create a [jbs](https://bugs.openjdk.org/browse/JDK-8333040) to record this issue. This failure unrelarate to this PR.
- serviceability/jvmti/ObjectMonitorUsage/ObjectMonitorUsage.java fails, which has been recorded by [JDK-8328741](https://bugs.openjdk.org/browse/JDK-8328741), unrelate to this PR.

**Comment by TobiHartmann** [comment]
Could you please explain why the test fails and how your fix addresses the issue?

**Comment by sendaoYan** [comment]
> Could you please explain why the test fails and how your fix addresses the issue?

On linux x86_64, before this PR, after deal with `std::regex_replace(tmp4, std::regex("\\s+<addr>:\\s+hlt[ \\t]+(?!\\n\\s+;;)"), "")`, the output differents because the first output has trailing empty space, show as below:
```log
-  <addr>:   nop    
+  <addr>:   nop
```
So we need to delete the empty spaces after `<addr>:   nop` use `std::regex_replace(tmp5, std::regex("(\\s+<addr>:\\s+nop)[ \\t]*"), "$1")`

**Comment by eme64** [comment]
Could we have a regression test for this?

**Comment by TobiHartmann** [comment]
Thanks for the details. So this is similar to [JDK-8274039](https://bugs.openjdk.org/browse/JDK-8274039). Do you know why this only shows up now?

**Comment by sendaoYan** [comment]
> Thanks for the details. So this is similar to [JDK-8274039](https://bugs.openjdk.org/browse/JDK-8274039). Do you know why this only shows up now?

I think this failure has existed for a while, not just recently. This failure reproduce need two conditions, 1. fastdebug or slowdebug linux x64 binary type; 2. run the gtest with hsdis-amd64.so is present

**Comment by sendaoYan** [comment]
> Okay. Looks good to me.
> 
> /reviewers 2

Thanks for the review.

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too.

**Comment by sendaoYan** [comment]
Thanks all for the review.
/integrate

**Pull request closed without merging**
