### PR TITLE
8155259: Suspicious buffer allocation in com.sun.tools.javac.file.BaseFileManager

### PR DESCRIPTION
**Pull request by archiecobbs**
JDK-8155259 notes that in `BaseFileManager` this code:
```java
ByteBuffer.allocate(capacity + capacity>>1)
```
is actually equivalent (assuming no overflow) to:
```java
ByteBuffer.allocate(capacity)
```
because in Java the `+` operator has higher precedence than the `>>` operator.

In the bug it is suggested that this be changed to reflect the presumed original intent to over-allocate by 50%, i.e.:
```java
ByteBuffer.allocate(capacity + (capacity>>1))
```
however, this patch is more conservative in that it leaves the existing behavior alone and instead just simplifies it to:
```java
ByteBuffer.allocate(capacity)
```
allowing us to at least resolve JDK-8155259.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8155259](https://bugs.openjdk.org/browse/JDK-8155259): Suspicious buffer allocation in com.sun.tools.javac.file.BaseFileManager
 * [JDK-8172106](https://bugs.openjdk.org/browse/JDK-8172106): javac throws exception when compiling source file of size 1.5G

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10803/head:pull/10803` \
`$ git checkout pull/10803`

Update a local copy of the PR: \
`$ git checkout pull/10803` \
`$ git pull https://git.openjdk.org/jdk pull/10803/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10803`

View PR using the GUI difftool: \
`$ git pr show -t 10803`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10803.diff">https://git.openjdk.org/jdk/pull/10803.diff</a>

</details>

### CODE REVIEW

**Comment by archiecobbs** [comment]
I just realized this change actually fixes another bug:

> [JDK-8172106](https://bugs.openjdk.org/browse/JDK-8172106) - javac throws exception when compiling source file of size 1.5G

**Comment by archiecobbs** [comment]
keepalive

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Pull request closed without merging**
