### PR TITLE
8335530: Java file extension missing in AuthenticatorTest

### PR DESCRIPTION
**Pull request by dfuch**
This trivial test was pushed without a .java file extension and none of us spotted this.

This change renames the test to add the proper file extension, converts it to use jupiter APIs instead of TestNG, and fixes a small mistake (s/principal.getName()/principal.getUsername()/).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335530](https://bugs.openjdk.org/browse/JDK-8335530): Java file extension missing in AuthenticatorTest (**Bug** - P4)

### Reviewers
 * [Christian Stein](https://openjdk.org/census#cstein) (@sormuras - Committer) ⚠️ Review applies to [6b944e6e](https://git.openjdk.org/jdk/pull/19984/files/6b944e6eb2d986dc16b8defd9e5facb27072f1b4)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19984/head:pull/19984` \
`$ git checkout pull/19984`

Update a local copy of the PR: \
`$ git checkout pull/19984` \
`$ git pull https://git.openjdk.org/jdk.git pull/19984/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19984`

View PR using the GUI difftool: \
`$ git pr show -t 19984`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19984.diff">https://git.openjdk.org/jdk/pull/19984.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19984#issuecomment-2202408646)

### CODE REVIEW

**Review by sormuras — APPROVED** [review]
Looks good to me.

**Review by jaikiran — APPROVED** [review]
Looks good to me.

**Comment by dfuch** [comment]
Thanks @jaikiran and @sormuras .

**Pull request closed without merging**
