### PR TITLE
8256538: Fix annoying awk warning in configure for java versions

### PR DESCRIPTION
**Pull request by magicus**
The change from grep to awk in JDK-8244248 and further bug fixed in JDK-8244756 still has invalid syntax. This causes some awk (most notably gawk, the most commonly used) to complain:

gawk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator

This is annoying and should be fixed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256538](https://bugs.openjdk.java.net/browse/JDK-8256538): Fix annoying awk warning in configure for java versions

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to 9d5fd4fcabf7bdf580e2fff8e12c2cf130ef44c9

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1285/head:pull/1285`
`$ git checkout pull/1285`

### CODE REVIEW

**Comment by magicus** [comment]
I have gotten confirmation from Martin Doerr that this also works on AIX, which has an awk that previously complained about this pattern. And I've tested it on all platforms used in the Oracle CI system.

**Review by erikj79 — APPROVED** [review]

**Comment by lewurm** [comment]
Thank you Magnus, this is something that has bugged me as well.

FWIW the same problem exists here with the build JDK detection: https://github.com/openjdk/jdk/blob/9d5fd4fcabf7bdf580e2fff8e12c2cf130ef44c9/make/autoconf/boot-jdk.m4#L519

Would you mind fixing it as part of this PR too?

**Comment by magicus** [comment]
@lewurm Thanks! I had not noticed that one. (In fact, I'm unsure when we got such a huge chunk of duplicated code... *sigh* Should look into it some day, I think.)

**Pull request closed without merging**
