### PR TITLE
8273506: java Robot API did the 'm' keypress and caused /awt/event/KeyEvent/KeyCharTest/KeyCharTest.html is timing out on macOS 12

### PR DESCRIPTION
**Pull request by azuev-java**
Clear the kCGEventFlagMaskSecondaryFn flag if it is set before posting keyboard events to the system queue.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 reviews required, with at least 1 reviewer)

### Issue
 * [JDK-8273506](https://bugs.openjdk.java.net/browse/JDK-8273506): java Robot API did the 'm' keypress and caused /awt/event/KeyEvent/KeyCharTest/KeyCharTest.html is timing out on macOS 12

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8320/head:pull/8320` \
`$ git checkout pull/8320`

Update a local copy of the PR: \
`$ git checkout pull/8320` \
`$ git pull https://git.openjdk.java.net/jdk pull/8320/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8320`

View PR using the GUI difftool: \
`$ git pr show -t 8320`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8320.diff">https://git.openjdk.java.net/jdk/pull/8320.diff</a>

</details>

### CODE REVIEW

**Comment by JB-Dmitry** [comment]
Just a note - with the proposed fix, some generated events will be different from those generated by a real keyboard - namely events for arrow keys and F1-F12 keys, as those have 'inherent' Fn modifier set, regardless of whether Fn key was pressed during event generation. This won't be observable from Java applications, as Java APIs don't expose Fn modifier in `KeyEvent`-s, but can theoretically make some difference when interacting with other apps (I don't know about any problematic cases currently though). If this can be considered a problem, it's possible to improve the fix by not clearing Fn flag for key events 'inherently' having that Fn modifier. Simple approach might just hard-code them, and a more robust one (but a bit more complicated as well) can determine the set of affected keycodes on Robot startup, by examining flags set by `CGEventCreateKeyboardEvent` in a 'clear' event source state.

**Comment by azuev-java** [comment]
> Just a note - with the proposed fix, some generated events will be different from those generated by a real keyboard - namely events for arrow keys and F1-F12 keys

As far as i can tell they are not different, the Quartz layer adds these flags back for the composite keys so functionally there is no difference even when we interact with the external applications. The problem was that Quartz code does not clear them when events are processed and that is what caused the issue on AWT Robot side of things.

**Comment by JB-Dmitry** [comment]
I assumed that whatever keys we set on an event being posted using `CGEventPost`, are delivered unchanged to the 'receiving' applications. But I did a test, and that doesn't seem to be the case. You're right, Quartz (or some other subsystem) does set those flags before delivering the events. Sorry for the noise.
Interestingly, extending the fix to NumPad flag (that 'sticks' in the global state similarly) doesn't work in the same way - the flag isn't being added automatically for arrow keys' KeyUp event by Quartz, but that's out of scope.

**Comment by mrserb** [comment]
I am not sure do we need to discard the possibility to press the shortcuts via the FN key, if the user may press them then why the robot cannot do the same? Looks like the behavior of this key is similar to the capslock which can be toggled on/off and may have a similar issue? If yes then we can press that button in the test twice to set an initial state(similar to how could fix the same issue for the capslock).

**Comment by azuev-java** [comment]
> I am not sure do we need to discard the possibility to press the shortcuts via the FN key, if the user may press them then why the robot cannot do the same? Looks like the behavior of this key is similar to the capslock which can be toggled on/off and may have a similar issue? If yes then we can press that button in the test twice to set an initial state(similar to how could fix the same issue for the capslock).

Ok, starting from the beginning - there is no possibility to press the Function key with Robot, the corresponding key code (OSX_Function - 0x3F) has not mapped to any of the keys available to Robot. Function key does not act like a caps lock - it acts like a shift. Just like a shift, it can only be fixated by the accessibility feature "sticky keys". Once Function key is released the global state should be changed in a way as if this key is not active. We do not issue key press or key release event for the Function key. The reason of why global state is being changed this way when we issue key press/key release sequence or a totally unrelated key (OSX_DownArrow - 0x7D) is unknown, it happens in the native code outside of our control. All we can do is to eliminate the consequences of this action that started to cause problems in Mac OS X 12.

**Comment by mrserb** [comment]
> Ok, starting from the beginning - there is no possibility to press the Function key with Robot, the corresponding key code (OSX_Function - 0x3F) has not mapped to any of the keys available to Robot. Function key does not act like a caps lock - it acts like a shift. Just like a shift, it can only be fixated by the accessibility feature "sticky keys". Once Function key is released the global state should be changed in a way as if this key is not active. We do not issue key press or key release event for the Function key. The reason of why global state is being changed this way when we issue key press/key release sequence for a totally unrelated key (OSX_DownArrow - 0x7D) is unknown, it happens in the native code outside of our control. All we can do is to eliminate the consequences of this action that started to cause problems in Mac OS X 12.

That description is very helpful, thank you. Based on that it looks like this is a bug in the macOS, did we report it to the Apple?

**Comment by azuev-java** [comment]
> That description is very helpful, thank you. Based on that it looks like this is a bug in the macOS, did we report it to the Apple?

No, we did not. I probably will but it is unlikely it will be addressed quickly so fixing this issue on out side seems to be required anyways.

**Review by mrserb — APPROVED** [review]

**Comment by mrserb** [comment]
> d not. I probably will but it is unlikely it will be addressed quickly so fixing this issue on our side seems to be required anyways.

Please add a "feedback id" to the JBS, so it will be possible to refer that macOS bug later.

**Pull request closed without merging**
