### PR TITLE
8283587: [BACKOUT] Invalid generic signature for redefined classes

### PR DESCRIPTION
**Pull request by alexmenkov**
The change reverts the fix for JDK-8282241 which causes regression

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283587](https://bugs.openjdk.java.net/browse/JDK-8283587): [BACKOUT] Invalid generic signature for redefined classes

### Reviewers
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7934/head:pull/7934` \
`$ git checkout pull/7934`

Update a local copy of the PR: \
`$ git checkout pull/7934` \
`$ git pull https://git.openjdk.java.net/jdk pull/7934/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7934`

View PR using the GUI difftool: \
`$ git pr show -t 7934`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7934.diff">https://git.openjdk.java.net/jdk/pull/7934.diff</a>

</details>

### CODE REVIEW

**Review by lmesnik — APPROVED** [review]
Although I think it is a test problem, backout is fine.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. Looks like a clean [BACKOUT] so this is a trivial fix.

**Review by sspitsyn — APPROVED** [review]
Hi Alex,
The back out is clean.
Thanks,
Serguei

**Pull request closed without merging**
