### PR TITLE
8306008: Several Vector API tests fail for client VM after JDK-8304450

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

Please review this patch which fixes the errors on machines where TypeMaxVector has a length of 64 bits. I take an extra cautious approach and fall back to putting elements one by one if the length is an unexpected value.

All jdk/incubator/vector tests passed with MaxVectorSize=8, which fails without this patch.

Thanks a lot.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306008](https://bugs.openjdk.org/browse/JDK-8306008): Several Vector API tests fail for client VM after JDK-8304450

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13508/head:pull/13508` \
`$ git checkout pull/13508`

Update a local copy of the PR: \
`$ git checkout pull/13508` \
`$ git pull https://git.openjdk.org/jdk.git pull/13508/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13508`

View PR using the GUI difftool: \
`$ git pr show -t 13508`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13508.diff">https://git.openjdk.org/jdk/pull/13508.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13508#issuecomment-1513046213)

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Thanks for fixing it! This PR fixes the issues in Vector64ConversionTests on PPC64.

**Comment by DingliZhang** [comment]
Thanks for this patch! This PR fixes the issue on RISC-V (qemu and unmatched without useRVV).

**Comment by zifeihan** [comment]
I have tested the x86-64,aarch64,riscv client vm, and several test cases that reported errors before have passed properly.

**Comment by merykitty** [comment]
Thanks a lot for your reviews and testings, I will integrate the patch.

**Pull request closed without merging**
