### PR TITLE
8284303: runtime/Thread/AsyncExceptionTest.java timed out

### PR DESCRIPTION
**Pull request by pchilano**
Please review this small fix to test runtime/Thread/AsyncExceptionTest.java. On rare cases the methods never reach the desired compilation level so the worker thread just gets blocked and the test times out.
I added a bail out after a couple of seconds of waiting.
Was able to reproduce the issue and checked the test doesn't timeout anymore with the fix.

Thanks,
Patricio

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284303](https://bugs.openjdk.java.net/browse/JDK-8284303): runtime/Thread/AsyncExceptionTest.java timed out

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8097/head:pull/8097` \
`$ git checkout pull/8097`

Update a local copy of the PR: \
`$ git checkout pull/8097` \
`$ git pull https://git.openjdk.java.net/jdk pull/8097/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8097`

View PR using the GUI difftool: \
`$ git pr show -t 8097`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8097.diff">https://git.openjdk.java.net/jdk/pull/8097.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
I'm okay with this bail out change as a means of getting the
test out of the periodic infinite loop which will solve the
current failures that we see in the CI.

If I understand the test correctly, you're trying to hold up
the test until the two target methods have been compiled
to CompilerUtils.getMaxCompilationLevel() which could be
either C1 level or C2 level. So by bailing out, if the max level
is C2 level, then you could bail out at Int or C1 level. Similarly,
if the max level is C1 level, then you could bail out at Int level.

I suspect that if CompilerUtils.getMaxCompilationLevel() is
Int level, i.e. we're in -Xint mode, then the current test
(without your fix) will always hang. You may want to add a
bail out that detects when the test is in -Xint mode.

You might also ping @vnkozlov for ideas on how to
"encourage" the test to reach your target compilation level.

**Comment by dcubed-ojdk** [comment]
Another thought occurred to me. You're delaying a fixed 20 seconds when
you should probably be scaling that to the environment timeoutFactor. You
can do something like what I did here:

test/hotspot/jtreg/runtime/8176717/TestInheritFD.java:    public static float timeoutFactor = Float.parseFloat(System.getProperty("test.timeout.factor", "1.0"));
test/hotspot/jtreg/runtime/8176717/TestInheritFD.java:    public static long subProcessTimeout = (long)(15L * timeoutFactor);

and then the delay is scaled: 20 seconds for a timeoutFactor of 1, 40 seconds
for a timeout factor of 2, etc...

**Comment by pchilano** [comment]
Thanks for the review Dan. Yes, I could do the scaling. It's just that from what I measured we almost do no waiting at all or the thread just waits forever in the failing cases.
I noticed that adding -Xcomp to the test also fixes the timeout cases. That would also fix the case where the test is run within a task that uses -Xint.

**Comment by vnkozlov** [comment]
The test is very non-deterministic. Depending on CPU speed and other factors `thread.stop` may arrive at any time (compilation is not blocking from what I see).
Do you want to test it when methods in Interpreter, compiled by C1 or C2, or all these cases? Then you need to test each such case separately and not depend on luck. You can do it by requiring present of C1 and C2 (or simply looking what compilation levels are available). And then run testing thread with different compilation level (including 0 - Interpreter) to make sure `Thread.stop` is delivered in all modes (if that is what you are looking for).

Why you included compilation request into testing thread? You can precompile methods in main() so you don't need to check it during testing time and use `receivedThreadDeathinInternal2` and `realRun`. There are WB API for compiling methods instead of calling them in loop.

**Comment by pchilano** [comment]
Thanks for taking a look at this @vnkozlov. 

> The test is very non-deterministic. Depending on CPU speed and other factors `thread.stop` may arrive at any time (compilation is not blocking from what I see). 
>
The worker actually waits in checkCompLevel() until the methods are compiled, before the real run. So either the methods are compiled or the worker will just wait and hence the timeout in these cases. I could have moved it to the main thread though as you mentioned below and use the WB methods to compile directly.

>Do you want to test it when methods in Interpreter, compiled by C1 or C2, or all these cases? Then you need to test each such case separately and not depend on luck. You can do it by requiring present of C1 and C2 (or simply looking what compilation levels are available). And then run testing thread with different compilation level (including 0 - Interpreter) to make sure `Thread.stop` is delivered in all modes (if that is what you are looking for).
> 
I want to run the test with those methods() compiled(internalRun2/internalRun1), don't really care if C1 or C2.

**Comment by vnkozlov** [comment]
Okay. So you want to test only compiled code. Note, since code path in tests methods is different (depends on `realRun`) methods could be recompiled again during `real` run. I suggest to use `-Xcomp` since you want them compiled always. 

1) add `@requires vm.compiler1.enabled | vm.compiler2.enabled`
2) add flags to `@run` command (blocking compilation for test methods only): 
```
-Xcomp -XX:CompileCommand=dontinline,AsyncExceptionTest::internalRun2
-XX:CompileCommand=compileonly,AsyncExceptionTest::internalRun1
-XX:CompileCommand=compileonly,AsyncExceptionTest::internalRun2
```
3) With Xcomp methods will be compiled on first call - you can skip pre-compilation (as I said, they will be recompiled anyway).
4) I don't think you need to check that methods are compiled - `-Xcomp` should guarantee it.

**Comment by vnkozlov** [comment]
Note, you don't need second `dontinline` command because only these 2 methods will be compiled.

**Review by dcubed-ojdk — APPROVED** [review]
The revised test is much simpler. Very cool. Thumbs up.

**Comment by pchilano** [comment]
Thanks for the reviews @vnkozlov and @dcubed-ojdk!

**Pull request closed without merging**
