### PR TITLE
8342979: Start of release updates for JDK 25

### PR DESCRIPTION
**Pull request by pavelrappo**
Prepare for JDK 25.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8343000](https://bugs.openjdk.org/browse/JDK-8343000) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8343029](https://bugs.openjdk.org/browse/JDK-8343029) to be approved
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8342999](https://bugs.openjdk.org/browse/JDK-8342999) to be approved

### Issues
 * [JDK-8342979](https://bugs.openjdk.org/browse/JDK-8342979): Start of release updates for JDK 25 (**Bug** - P4)
 * [JDK-8342982](https://bugs.openjdk.org/browse/JDK-8342982): Add SourceVersion.RELEASE_25 (**Sub-task** - P4)
 * [JDK-8342983](https://bugs.openjdk.org/browse/JDK-8342983): Add source 25 and target 25 to javac (**Sub-task** - P4)
 * [JDK-8343029](https://bugs.openjdk.org/browse/JDK-8343029): Start of release updates for JDK 25 (**CSR**)
 * [JDK-8343000](https://bugs.openjdk.org/browse/JDK-8343000): Add source 25 and target 25 to javac (**CSR**)
 * [JDK-8342999](https://bugs.openjdk.org/browse/JDK-8342999): Add SourceVersion.RELEASE_25 (**CSR**)

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) Review applies to [64e9326b](https://git.openjdk.org/jdk/pull/21763/files/64e9326bfa92109849f0e010ef1db687a317b300)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) Review applies to [64e9326b](https://git.openjdk.org/jdk/pull/21763/files/64e9326bfa92109849f0e010ef1db687a317b300)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Contributors
 * Joe Darcy `<darcy@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21763/head:pull/21763` \
`$ git checkout pull/21763`

Update a local copy of the PR: \
`$ git checkout pull/21763` \
`$ git pull https://git.openjdk.org/jdk.git pull/21763/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21763`

View PR using the GUI difftool: \
`$ git pr show -t 21763`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21763.diff">https://git.openjdk.org/jdk/pull/21763.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21763#issuecomment-2444247956)
</details>

### CODE REVIEW

**Review by irisclark — APPROVED** [review]
Congratulations on accepting the baton from Joe!

Confirmed everything as expected.

**Review by erikj79 — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Hotspot changes are fine.

Thanks

**Review by irisclark — APPROVED** [review]
Additional changes (all autogenerated) look good.

**Review by jddarcy — APPROVED** [review]
I skimmed over the new symbol information and the results look plausible.

**Review by irisclark — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by jddarcy — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by jddarcy — APPROVED** [review]

**Pull request closed without merging**
