### PR TITLE
8280568: IGV: Phi inputs and pinned nodes are not scheduled correctly

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset improves the accuracy of IGV's schedule approximation algorithm by

1) scheduling pinned nodes in the same block as their corresponding control nodes (or in the immediate successor block for nodes pinned to block projections); and
2) scheduling phi input nodes above the phi block, in their corresponding control path.

The combined effect of these scheduling improvements can be seen in the example below. In the current version of IGV **(before)**, `135 ClearArray` is wrongly scheduled in the same block as its output phi node (`91 Phi`). After this changeset **(after)**, `135 ClearArray` is correctly scheduled above the phi node, in its corresponding control path. Since `135 ClearArray` is pinned to the block projection `151 True`, a new block is created between `151 True` and `91 Phi` to accommodate it.

fix

Additionally, the changeset introduces checks on graph invariants that are assumed by scheduling approximation (e.g. each block projection has a single control successor), warning the IGV user if these invariants are broken. Warning and gracefully degrading the approximated schedule is preferred to just failing since one of IGV's main use cases is debugging graphs which might be ill-formed. The warnings are reported both textually in the IGV log and visually for each node, if the corresponding filter ("Show node warnings") is active:

warning

Node warnings are implemented as a general filter and can be used in custom filters for other purposes, for example highlighting nodes that match a certain property of interest.

##### Functionality

- Tested manually that phi inputs and pinned nodes are scheduled correctly for a few selected graphs (included the reported one).

- Tested automatically that scheduling tens of thousands of graphs (by instrumenting IGV to schedule parsed graphs eagerly and running `java -Xcomp -XX:-TieredCompilation -XX:PrintIdealGraphLevel=4`) does not trigger any assertion failure and does not warn with the message "Phi input that does not dominate the phi's input block".

##### Performance

Measured that the scheduling time is not slowed down for a selection of 89 large graphs (2511-7329 nodes). The performance results are attached (note that each measurement in the sheet corresponds to the median of ten runs).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280568](https://bugs.openjdk.java.net/browse/JDK-8280568): IGV: Phi inputs and pinned nodes are not scheduled correctly

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7493/head:pull/7493` \
`$ git checkout pull/7493`

Update a local copy of the PR: \
`$ git checkout pull/7493` \
`$ git pull https://git.openjdk.java.net/jdk pull/7493/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7493`

View PR using the GUI difftool: \
`$ git pr show -t 7493`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7493.diff">https://git.openjdk.java.net/jdk/pull/7493.diff</a>

</details>

### CODE REVIEW

**Comment by robcasloz** [comment]
Switching back to draft mode to incorporate some offline feedback about reporting of scheduling warnings, and possibly generalize the scheduling algorithm to cover additional, related cases.

**Comment by robcasloz** [comment]
This PR is open for review again. Please find the updated description in [the GitHub page](https://github.com/openjdk/jdk/pull/7493).

**Review by vnkozlov — APPROVED** [review]
Approved.

**Comment by robcasloz** [comment]
> Approved.

Thanks, Vladimir!

**Review by TobiHartmann — APPROVED** [review]
Awesome, looks good to me.

**Comment by robcasloz** [comment]
> Awesome, looks good to me.

Thanks, Tobias!

**Pull request closed without merging**
