### PR TITLE
8302664: Fix several incorrect usages of Preconditions.checkFromIndexSize

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which fixes the usage of `Preconditions.checkFromIndexSize`? This addresses https://bugs.openjdk.org/browse/JDK-8302664.

There was an oversight when these changes were introduced in https://github.com/openjdk/jdk/pull/4507. I have now gone through that patch again to make sure the relevant places where this fix is needed has been addressed in this current PR.

I have also looked into other changes in that PR, just to be sure that there aren't any similar fixes needed for other method calls that were introduced in it - they all look fine.

tier1,tier2 and tier3 testing with this change passed successfully. I thought (and experimented a bit) to add new tests for Deflater/Inflater to catch these byte array indexing issues, but it wasn't straight forward and I would have to write the entire inflate/deflate test just to verify this issue. So I decided to leave out new tests for now in this PR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302664](https://bugs.openjdk.org/browse/JDK-8302664): Fix several incorrect usages of Preconditions.checkFromIndexSize

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - Committer)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12595/head:pull/12595` \
`$ git checkout pull/12595`

Update a local copy of the PR: \
`$ git checkout pull/12595` \
`$ git pull https://git.openjdk.org/jdk pull/12595/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12595`

View PR using the GUI difftool: \
`$ git pr show -t 12595`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12595.diff">https://git.openjdk.org/jdk/pull/12595.diff</a>

</details>

### CODE REVIEW

**Review by djelinski — APPROVED** [review]
As far as I could tell, this only changes the generated exception message. The condition is (off+len<=size), so the exception will be thrown on the same input as before.

LGTM.

**Review by dfuch — APPROVED** [review]
As Daniel noted the computation is symmetrical which explains why it worked. But passing inverted parameters was confusing. LGTM2.

**Review by AlanBateman — APPROVED** [review]
It's easy to get the parameters wrong to these methods but if the fromIndex and size are mixed up then it should just impact the exception message.

**Comment by jaikiran** [comment]
Thank you all for the reviews.

**Pull request closed without merging**
