### PR TITLE
8297294: compiler/c2/irTests/TestMulNodeIdealization.java failed compilation

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
Given that the reported issue is intermittent I think we have two options here:

1 - change the most probable use of a non-deterministic data structure that could be provoking this bug, to a deterministic one
2 - change all uses of non-deterministic data structures

I first tried option `1` but TBH after going again to the code I can't find a clear suspect. I thought we had reduced the options for non-determinism in the inference engine to zero, rien, niente. But it seems like that's not the case. So I have gone for option `2`.

Comments?
TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297294](https://bugs.openjdk.org/browse/JDK-8297294): compiler/c2/irTests/TestMulNodeIdealization.java failed compilation

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11437/head:pull/11437` \
`$ git checkout pull/11437`

Update a local copy of the PR: \
`$ git checkout pull/11437` \
`$ git pull https://git.openjdk.org/jdk pull/11437/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11437`

View PR using the GUI difftool: \
`$ git pr show -t 11437`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11437.diff">https://git.openjdk.org/jdk/pull/11437.diff</a>

</details>

### CODE REVIEW

**Comment by archiecobbs** [comment]
So just to confirm: while clearly changing `HashSet` to `LinkedHashSet` is going to eliminate some non-determinism, it also fixes the actual compiler logic bug rather than "papering over" it, correct?

If not - then is more investigation warranted?

If so - then doesn't that imply that the code that invokes `closure()` contains an implicit assumption about the ordering of the elements of that returned `Set`? And if so, since that's a fairly subtle and suspicious assumption about a `Set`, shouldn't that assumption least be documented in a comment somewhere (or ideally, corrected by sorting the `Set` into a `List` or something)? Otherwise it seems a variant of this bug could easily crop up again.

**Comment by vicente-romero-oracle** [comment]
> So just to confirm: while clearly changing `HashSet` to `LinkedHashSet` is going to eliminate some non-determinism, it also fixes the actual compiler logic bug rather than "papering over" it, correct?
> 
> If not - then is more investigation warranted?
> 
> If so - then doesn't that imply that the code that invokes `closure()` contains an implicit assumption about the ordering of the elements of that returned `Set`? And if so, since that's a fairly subtle and suspicious assumption about a `Set`, shouldn't that assumption least be documented in a comment somewhere (or ideally, corrected by sorting the `Set` into a `List` or something)? Otherwise it seems a variant of this bug could easily crop up again.

It is not clear that there is a compiler bug as the code is compiled sometimes and sometimes not. This patch is not claiming to fix the bug as a compiler failure can't be reproduced. All I want is to make the inference engine as reliable as possible.

**Review by mcimadamore — APPROVED** [review]
Looks good

**Pull request closed without merging**
