### PR TITLE
8257531: Super word not applied to a loop of simple Buffer operations

### PR DESCRIPTION
**Pull request by vnkozlov**
In Buffer case there is additional (loop invariant) load from java/nio/IntBuffer.offset field.
SuperWord did not handle loop's invariants in complex address expressions (only when vectorization is forced):

`AddP(addr, AddP(addr, addr, LShiftL(ConvI2L(CastII(AddI(AddI(iv_phi, invariant_LoadI), incr))), shift)), 16)`

Invariant reference is used to make sure all memory accesses in vectors use the same one. And only when alignment code is generated in pre-loop it is used for code generatin. But that code did not take into account that invariant have to be scaled if needed as in this example (invariant_LoadI << shift).

I propose to record scaling (left shift) for invariant when it is present and use it to compare invariants and in pre-loop alignment code generation. I also slightly modified tracing output code for invariants.

This allow vectorize Java code which uses Buffer.

I added new test based on @PaulSandoz example. It tests presence of new vectors and correctness of vectorized code.
I included case (ByteBuffer.allocateDirect()) which is not vectorized because it uses Unsafe access - SuperWord complains about CastX2P(AddL) nodes which it sees instead of AddP.  We may consider vectorizing such code too later.

Testing: tier1-4, precheckin-comp (-Xcomp), renaissance test

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257531](https://bugs.openjdk.java.net/browse/JDK-8257531): Super word not applied to a loop of simple Buffer operations 

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to 9b9219da566649ccdb9955ce2169ec9c5999f960
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1618/head:pull/1618`
`$ git checkout pull/1618`

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by PaulSandoz — APPROVED** [review]
Java test looks good.

**Comment by vnkozlov** [comment]
Thank you @PaulSandoz and @rwestrel for reviews.

**Pull request closed without merging**
