### PR TITLE
8329528: G1 does not update TAMS correctly when dropping retained regions during Concurrent Start pause

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change to fix the problem that when g1 ages out regions from the retained region collection set candidate list during a concurrent start gc, the `TAMS`es of these regions are not set correctly.

The change achieves this by changing the order of some calculations in `G1YoungCollector::pre_evacuate_collection_set`: instead of setting `TAMS`es before collection set calculation, do it later, adjusting the predicate determining whether to update the `TAMS`es at concurrent start pause start to exclude regions in the collection set.

Several attempts for different fixes were tried, one of them is still viewable by only considering the changesets before the "alternate implementation" commit. However they quickly grew to fairly large size and complicated the code a lot.

Testing: tier1-3, test case not failing any more

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329528](https://bugs.openjdk.org/browse/JDK-8329528): G1 does not update TAMS correctly when dropping retained regions during Concurrent Start pause (**Bug** - P1)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18692/head:pull/18692` \
`$ git checkout pull/18692`

Update a local copy of the PR: \
`$ git checkout pull/18692` \
`$ git pull https://git.openjdk.org/jdk.git pull/18692/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18692`

View PR using the GUI difftool: \
`$ git pr show -t 18692`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18692.diff">https://git.openjdk.org/jdk/pull/18692.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18692#issuecomment-2047200881)

### CODE REVIEW

**Review by albertnetymk — COMMENTED** [review]
The fix looks good. However, in the long run, pulling out the logic around `G1NumCollectionsKeepPinned` from the cset construction seems cleaner. Also, `NoteStartOfMarkHRClosure` can keep the original simpler condition.

**Review by walulyai — APPROVED** [review]
LGTM!

**Comment by tschatzl** [comment]
> The fix looks good. However, in the long run, pulling out the logic around `G1NumCollectionsKeepPinned` from the cset construction seems cleaner.

That is true at first glance, but when trying that out for this change, to me the drawbacks outweighed the cleanliness argument that resulted in much more code:
  * extra loop over the collection set candidates, where that loop is at a different place in the code, called from `pre_evacuate_collection_set`. This creates an extra additional dependency when tracking dependencies there. One could imagine to add time tracking for this phase as well, resulting in more extra code.
  * logging of this filtering will become disjointed from collection set selection. Dropping a region from the collection set candidates implies not selecting it, and reflecting this properly in the selection process takes additional effort unless one agrees with having separate log messages. (E.g. it is a bit surprising that when you know that there were pinned regions, the cset selection may actually tell you that there were none).
  * this is very little extra code piggybacking it on the collection set selection

I think I considered this extra step for filtering when implementing this the first time, rejected it for all the extra effort (probably in the range of 100 LOC, see the diff for the https://github.com/openjdk/jdk/pull/18692/commits/0c46d6a653365472421123f021cda414834fac15 change - which is incomplete btw as it does not adjust the regression test and potentially add proper timing/logging) just to basically avoid this single `if` clause there.

Anyway, modifying this in this change at least it detracts from the problem at hand. I will file an RFE.

>Also, `NoteStartOfMarkHRClosure` can keep the original simpler condition.

The additional clause is an arbitrary requirement/assumption by the existing code, asserting somewhere that cset regions do not have tams set initially.
All code paths for regions in the collection set update the TAMS, either clear again when freeing the region, or set it properly during evacuation failure, afair. I wanted to keep the initial assumption of cset regions having tams == bottom throughout.

Could you approve the change if it looks good to you?

**Review by albertnetymk — APPROVED** [review]
The fix is small and easy to backport; can probably further improve the logic around pinning&cset at later PRs.

**Comment by tschatzl** [comment]
Thanks @albertnetymk @walulyai for your reviews
/integrate

**Pull request closed without merging**
