### PR TITLE
Skip normalization of nanos for already normalized values

### PR DESCRIPTION
**Pull request by plokhotnyuk**
In most cases when users provide already normalized values it could save ~20 cycles on contemporary Intel CPUs

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11986/head:pull/11986` \
`$ git checkout pull/11986`

Update a local copy of the PR: \
`$ git checkout pull/11986` \
`$ git pull https://git.openjdk.org/jdk pull/11986/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11986`

View PR using the GUI difftool: \
`$ git pr show -t 11986`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11986.diff">https://git.openjdk.org/jdk/pull/11986.diff</a>

</details>

### CODE REVIEW

**Comment by stsypanov** [comment]
Is there any benchmark measuring both branches in the modified method?

**Comment by plokhotnyuk** [comment]
@stsypanov In fact, I've spot the problem by running [this](https://github.com/plokhotnyuk/jsoniter-scala/blob/59f206630567b68eb1cf22b2ff9832a83200cc08/jsoniter-scala-benchmark/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/benchmark/ArrayOfInstantsReading.scala#L60-L66) benchmark with async-profiler using the following command:
```
sbt jsoniter-scala-benchmarkJVM/clean 'jsoniter-scala-benchmarkJVM/jmh:run -prof "async:dir=target/async-reports;interval=1000000;output=flamegraph;libPath=/opt/async-profiler/build/libasyncProfiler.so" --p size=128 -jvmArgsAppend "-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints" -wi 5 -i 10 ArrayOfInstantsReading.jsoniterScala'
```
It shows that during parsing of `java.time.Instance` values from JSON about 10% of CPU cycles are burned for normalization.

I can modify it to test the instantiation of `java.time.Instant` values for both branches... or do you mean that need to provide such benchmark in the PR?

**Comment by stsypanov** [comment]
> do you mean that need to provide such benchmark in the PR?

I think it'd be enough just to put its code here along with benchmarking results.

**Comment by plokhotnyuk** [comment]
Please anybody help me to pass jcheck.
I have resubmitted my OCA signatory more than month ago
Also I don't have an account to create the issue in the bug DB.
What's missing to pass the review?

**Comment by ExE-Boss** [comment]
@plokhotnyuk You can’t re‑open a PR when the source branch doesn’t exist.

**Pull request closed without merging**
