### PR TITLE
8334629: [BACKOUT] PhaseIdealLoop::conditional_move is too conservative

### PR DESCRIPTION
**Pull request by TobiHartmann**
Hi all,

This pull request contains a backport of commit [933eabab](https://github.com/openjdk/jdk/commit/933eababf2b79586a911082af36fdcc41763c7b9) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Quan Anh Mai on 25 Jun 2024 and was reviewed by Emanuel Peter, Tobias Hartmann and Jasmine Karthikeyan.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334629](https://bugs.openjdk.org/browse/JDK-8334629): [BACKOUT] PhaseIdealLoop::conditional_move is too conservative (**Sub-task** - P3)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Quan Anh Mai](https://openjdk.org/census#qamai) (@merykitty - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19896/head:pull/19896` \
`$ git checkout pull/19896`

Update a local copy of the PR: \
`$ git checkout pull/19896` \
`$ git pull https://git.openjdk.org/jdk.git pull/19896/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19896`

View PR using the GUI difftool: \
`$ git pr show -t 19896`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19896.diff">https://git.openjdk.org/jdk/pull/19896.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19896#issuecomment-2190906646)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks Christian!

**Comment by TobiHartmann** [comment]
Thanks Quan Anh!

**Pull request closed without merging**
