### PR TITLE
8271855: [TESTBUG] Wrong weakCompareAndSet assumption in UnsafeIntrinsicsTest

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
We need a fix for test failures due to wrong assumption. (See JBS issue for details.) I suggest to give weakCompareAndSet several chances.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271855](https://bugs.openjdk.java.net/browse/JDK-8271855): [TESTBUG] Wrong weakCompareAndSet assumption in UnsafeIntrinsicsTest

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4992/head:pull/4992` \
`$ git checkout pull/4992`

Update a local copy of the PR: \
`$ git checkout pull/4992` \
`$ git pull https://git.openjdk.java.net/jdk pull/4992/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4992`

View PR using the GUI difftool: \
`$ git pr show -t 4992`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4992.diff">https://git.openjdk.java.net/jdk/pull/4992.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi Martin, 
why do you think 4 iterations are what you need?
I think you should add 8271855 to @bug.
Best regards,
  Goetz

**Comment by TheRealMDoerr** [comment]
The test should usually pass within 2 iterations. It could happen that 2 different reasons make it fail (e.g. GC touches the cache line, OS takes the process from the CPU, interrupt occurs, ...). So, I think 2 iterations should usually work, 3 ones should be enough to prevent very sporadic failures in the future.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews!
/integrate

**Pull request closed without merging**
