### PR TITLE
8252657: JVMTI agent is not unloaded when Agent_OnAttach is failed

### PR DESCRIPTION
**Pull request by YaSuenag**
If `Agent_OnAttach()` in JVMTI agent which is attempted to load via JVMTI.agent_load dcmd is failed, it would not be unloaded.  
We've [discussed it on serviceability-dev](https://mail.openjdk.java.net/pipermail/serviceability-dev/2020-September/032839.html). This PR is a continuation of that.

This PR also includes to call `Agent_OnUnload()` when `Agent_OnAttach()` failed.

How to reproduce:

1. Build JVMTI agent for test
```
$ git clone https://github.com/YaSuenag/jvmti-examples.git
$ cd jvmti-examples/helloworld/out/build
$ cmake ../..
```

2. Run JShell

3. Load JVMTI agent via `jcmd <PID> JVMTI.agent_load` with "error" ("error" means `Agent_OnAttach()` returns JNI_ERR)
```
$ jcmd
89456 jdk.jshell.execution.RemoteExecutionControl 45651
89547 sun.tools.jcmd.JCmd
89436 jdk.jshell/jdk.internal.jshell.tool.JShellToolProvider
$ jcmd 89436 JVMTI.agent_load `pwd`/libhelloworld.so error
89436:
return code: -1
```

4. Check loaded libraries via `jcmd <PID> VM.dynlibs`
```
$ jcmd 89436 VM.dynlibs | grep libhelloworld
7f2f8b06b000-7f2f8b06c000 r--p 00000000 fd:00 11818202 /home/ysuenaga/github/jvmti-examples/helloworld/out/build/libhelloworld.so
7f2f8b06c000-7f2f8b06d000 r-xp 00001000 fd:00 11818202 /home/ysuenaga/github/jvmti-examples/helloworld/out/build/libhelloworld.so
7f2f8b06d000-7f2f8b06e000 r--p 00002000 fd:00 11818202 /home/ysuenaga/github/jvmti-examples/helloworld/out/build/libhelloworld.so
7f2f8b06e000-7f2f8b06f000 r--p 00002000 fd:00 11818202 /home/ysuenaga/github/jvmti-examples/helloworld/out/build/libhelloworld.so
7f2f8b06f000-7f2f8b070000 rw-p 00003000 fd:00 11818202 /home/ysuenaga/github/jvmti-examples/helloworld/out/build/libhelloworld.so
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252657](https://bugs.openjdk.java.net/browse/JDK-8252657): JVMTI agent is not unloaded when Agent_OnAttach is failed

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/19/head:pull/19`
`$ git checkout pull/19`

### CODE REVIEW

**Comment by YaSuenag** [comment]
@edvbld Can you approve me to run tier1 tests with /test PR command again?

**Comment by sspitsyn** [comment]
I was initially wrong by supporting this, and now I share David's concerns about unclear semantics of this. The questions are:
 - Q1: Is it necessary to call the Agent_OnUnload()?
 - Q2: Would it be a JVMTI spec violation to call the Agent_OnAttach() multiple times? (It seems to be the case to me.)
 - Q3: What has to be done for statically linked agent?
 - Q4: Should the agent be correctly loadable in the first place? What were the reasons its loading to fail?
Yes, at least, a CSR is needed for this.

**Comment by YaSuenag** [comment]
> * Q1: Is it necessary to call the Agent_OnUnload()?

[JVMTI spec of Agent_OnUnload()](https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#onunload) says this function will be called when the agent library will be unloaded by platform specific mechanism. OTOH it also says `Agent_OnUnload()` will be called both at VM termination and **by other reasons**.
The spec don't say for the case if `Agent_OnAttach()` would be failed. IMHO `Agent_OnUnload()` should be called because this PR would unload library if `Agent_OnAttach()` failed.

> * Q2: Would it be a JVMTI spec violation to call the Agent_OnAttach() multiple times? (It seems to be the case to me.)

`Agent_OnAttach()` should be called only once per attach request, but VM should accept multiple attach request for same agent library.

For example, we can add multiple `-agentlib` and `-agentpath` request as below. JVMTI agent might change behavior due to arguments or configuration file.

```
-agentlib:test=profile=A -agentlib:test=profile=B -agentpath:/path/to/libtest=profile=C
```

Agent developers should have responsibility for the behavior when more than one agent is loaded at a time.

> * Q3: What has to be done for statically linked agent?

JVMTI spec says "unless it is statically linked into the executable", so I think we can ignore about Agent_OnUnload_L() in this PR.

> * Q4: Should the agent be correctly loadable in the first place? What were the reasons its loading to fail?

Agent (`Agent_OnAttach()`) might fail due to error in agent logic. For example, some agents load configuration file at initialization. If the user gives wrong value, it will fail.

> Yes, at least, a CSR is needed for this.

I will file CSR for this PR after this discussion.

**Comment by YaSuenag** [comment]
If we can change the spec that agent library would not be unloaded when `Agent_OnAttach()` failed, we can change like [webrev.00](https://cr.openjdk.java.net/~ysuenaga/JDK-8252657/webrev.00/). It is simple, and similar behavior with `Agent_OnLoad()`. It might be prefer for JVMTI agent developers.

**Comment by YaSuenag** [comment]
In case of `Agent_OnLoad()`, if it is failed (it returns other than zero), JVM is aborted and `Agent_OnUnload()` is not called. I think it is compliant with [JVMTI spec of Agent_OnUnload()](https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#onunload) which says uncontrolled shutdown (aborting JVM) is an exception to this rule.

I will add CSR for this fix, but I want to discuss what we should do before. I like that `Agent_OnUnload()` wouldn't be called when `Agent_OnAttach()` is failed if we can change the spec - it is consistent and friendly with `Agent_OnUnload()`.

**Comment by YaSuenag** [comment]
I added [CSR for this PR](https://wiki.openjdk.java.net/display/csr/Main) and updated patch. Could you review it?
I think it is reasonable to clarify the spec not to call `Agent_OnUnload()` when `Agent_OnLoad()` or `Agent_OnAttach()` are failed. It is nature for me, and it does not change current behavior in HotSpot.

**Comment by plummercj** [comment]
> > * Q3: What has to be done for statically linked agent?
> 
> JVMTI spec says "unless it is statically linked into the executable", so I think we can ignore about Agent_OnUnload_L() in this PR.

I don't think that makes sense. If you call it for dynamically linked then you need to call it for statically linked also.

**Comment by YaSuenag** [comment]
@dholmes-ora Thank you for explanation! I updated [CSR](https://bugs.openjdk.java.net/browse/JDK-8256918). Could you review it?

**Comment by YaSuenag** [comment]
CSR has been approved. I updated jvmti.xml to follow it (I haven't make any changes in other files in latest commit)
Could you review again?

**Review by dholmes-ora — APPROVED** [review]
Hi Yasumasa,

Spec update looks good.

VM tweak to call dll_unload on failure looks good.

I don't understand the test change though.

Thanks,
David

**Comment by YaSuenag** [comment]
> Hi Yasumasa,
> 
> Spec update looks good.
> 
> VM tweak to call dll_unload on failure looks good.

Thanks!

> I don't understand the test change though.

To check the agent is unloaded, call VM.dynlibs dcmd and check whether agent path is not contained.
libReturnError.so would be loaded only once in AttachReturnError.java, so it is expected to unload when `Agent_OnAttach()` fails.

**Review by sspitsyn — APPROVED** [review]
Hi Yasumasa,

Both the CSR and the fix look good.
Thank you for your patience with the process.

Thanks,
Serguei

**Pull request closed without merging**
