### PR TITLE
8316206: Test StretchedFontTest.java fails for Baekmuk font

### PR DESCRIPTION
**Pull request by aivanov-jdk**
**Root cause**

The _Baekmuk Headline_ font maps `\u6f22` (漢) to glyph id 16950 which has zero length.

The test fails if the right half of the image with the rendered glyph contains only pixels of background colour. In this case, the left half of the image is also blank. It's somewhat false positive because of the broken font.

**Fix**

Ignore fonts which don't render the glyph correctly. If the left half of the image contains pixels of the background colour only, it is expected that the right half also contains background-coloured pixels only.

The updated test does not fail with the _Baekmuk Headline_ font. It still detects the original problem and fails on builds without the fix for [JDK-8312555](https://bugs.openjdk.org/browse/JDK-8312555).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316206](https://bugs.openjdk.org/browse/JDK-8316206): Test StretchedFontTest.java fails for Baekmuk font (**Bug** - P4)

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**) ⚠️ Review applies to [6c866aea](https://git.openjdk.org/jdk/pull/15818/files/6c866aeacc294bd74a1c78a2796078c5ce4e1055)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15818/head:pull/15818` \
`$ git checkout pull/15818`

Update a local copy of the PR: \
`$ git checkout pull/15818` \
`$ git pull https://git.openjdk.org/jdk.git pull/15818/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15818`

View PR using the GUI difftool: \
`$ git pr show -t 15818`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15818.diff">https://git.openjdk.org/jdk/pull/15818.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15818#issuecomment-1725621642)

### CODE REVIEW

**Comment by prrace** [comment]
I was thinking of a more direct font-oriented verification like this
import java.awt.*;
import java.awt.font.*;

public class GO {
  public static void main(String args[]) {
    Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 20);
    FontRenderContext frc = new FontRenderContext(null, false, false);
    GlyphVector gv = font.createGlyphVector(frc, "o");
    boolean empty = gv.getVisualBounds().isEmpty();
    System.out.println("empty="+empty);
  }
}

% java GO      
empty=true

**Review by azvegint — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
> I was thinking of a more direct font-oriented verification like this
>
> ```java
> import java.awt.*;
> import java.awt.font.*;
> 
> public class GO {
>     public static void main(String args[]) {
>         Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 20);
>         FontRenderContext frc = new FontRenderContext(null, false, false);
>         GlyphVector gv = font.createGlyphVector(frc, "o");
>         boolean empty = gv.getVisualBounds().isEmpty();
>         System.out.println("empty="+empty);
>     }
> }
> ```
> ```text
> % java GO
> empty=true
> ```

@prrace Thank you! It's a much cleaner approach. I've updated the PR.

When I run the test on Linux with, I get the a diagnostic message:
```text
~/work/jdk-dev$ ~/dev/tools/jdk20/bin/java test/jdk/java/awt/Font/FontScaling/StretchedFontTest.java
Broken font: Baekmuk Headline
```

**Comment by aivanov-jdk** [comment]
/summary
Ignore broken fonts, i.e. the fonts for which
GlyphVector(TEXT).getVisualBounds().isEmpty() returns true

**Review by prrace — APPROVED** [review]

**Review by GoeLin — APPROVED** [review]
The test passes with this patch on our machine. LGTM.

**Comment by GoeLin** [comment]
Thanks for this timely fix!

**Pull request closed without merging**
