### PR TITLE
8325108: POSIX map_memory_to_file calls release_memory incorrectly

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

This PR fixes a small bug where `os::map_memory_to_file` attempts to unmap an incorrect mapping by calling `os::release_memory`. If NMT is turned on this will lead to a JVM crash, as the region was not previously mapped.

I'm fairly sure that this branch is actually dead code as `MAP_FIXED` is appended to the flags of the mmap call, and according to my man pages on mmap this will lead to mmap failing instead of giving another mapping to the address. However, I'd rather be on the safe side than sorry so I only do the minimal changes necessary to fix the bug.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325108](https://bugs.openjdk.org/browse/JDK-8325108): POSIX map_memory_to_file calls release_memory incorrectly (**Bug** - P4)(⚠️ The fixVersion in this issue is [25] but the fixVersion in .jcheck/conf is 24, a new backport will be created when this pr is integrated.)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17669/head:pull/17669` \
`$ git checkout pull/17669`

Update a local copy of the PR: \
`$ git checkout pull/17669` \
`$ git pull https://git.openjdk.org/jdk.git pull/17669/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17669`

View PR using the GUI difftool: \
`$ git pr show -t 17669`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17669.diff">https://git.openjdk.org/jdk/pull/17669.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17669#issuecomment-1921157904)
</details>

### CODE REVIEW

**Review by stefank — APPROVED** [review]

**Comment by gerard-ziemski** [comment]
So we don't have any instances of actual crashes, this is purely theoretical?

**Comment by gerard-ziemski** [comment]
The fix itself looks good to me.

I do have some comments, however:

I see 2 call chains:

```
char* os::map_memory_to_file(size_t bytes, int file_desc, MEMFLAGS flag) {
  static char* map_memory_to_file(char* base = nullptr, size_t size = bytes, int fd = file_desc);
```

and

```
static char* reserve_memory(char* requested_address, const size_t size, const size_t alignment, int fd, bool exec) {
  static char* attempt_map_or_reserve_memory_at(char* base = requested_address, size_t size = size, int fd = fd, bool executable = exec) {
    char* os::attempt_map_memory_to_file_at(char* addr = base, size_t bytes = size, int file_desc = fd, MEMFLAGS flag) {
      char* os::pd_attempt_map_memory_to_file_at(char* requested_addr = addr, size_t bytes = bytes, int file_desc = file_desc) {
        if (result != nullptr)
        char* os::replace_existing_mapping_with_file_mapping(char* base = result, size_t size = bytes, int fd = file_desc) {
          static char* map_memory_to_file(char* base = base, size_t size = size, int fd = fd);
```

so it does not look like dead code to me.

Also, not 100% sure about the `MAP_FIXED` comment, my `man` page (on macOS) only talks about deleting previous mappings and that `Use of this option is discouraged.` though hotspot seems to be using `MAP_FIXED` in several places already.

**Review by gerard-ziemski — APPROVED** [review]

**Comment by tstuefe** [comment]
> I'm fairly sure that this branch is actually dead code as `MAP_FIXED` is appended to the flags of the mmap call, and according to my man pages on mmap this will lead to mmap failing instead of giving another mapping to the address. However, I'd rather be on the safe side than sorry so I only do the minimal changes necessary to fix the bug.

Yes, this can never happen. Its POSIX (https://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html):

"When MAP_FIXED is set in the flags argument, the implementation is informed that the value of pa shall be addr, exactly. If MAP_FIXED is set, mmap() may return MAP_FAILED and set errno to [EINVAL]. If a MAP_FIXED request is successful, the mapping established by mmap() replaces any previous mappings for the process' pages in the range [pa,pa+len)."

MAP_FIXED uses the address given. If it works, the resulting mapping starts at address. I would just assert here. Handling something that cannot happen makes little sense, and it is confusing to read.

BTW, MAP_FIXED is optional, but all OpenJDK Posix platforms must implement it since it is the base for mmap-based reserving and committing. 

> Also, not 100% sure about the MAP_FIXED comment, my man page (on macOS) only talks about deleting previous mappings and that Use of this option is discouraged. though hotspot seems to be using MAP_FIXED in several places already.

MAP_FIXED is essential in writing your own memory management. There is no other way to change mapping properties. How would you commit otherwise? Comments like these in official man pages really lower my already low opinion of Apple.

**Comment by jdksjolen** [comment]
>MAP_FIXED uses the address given. If it works, the resulting mapping starts at address. I would just assert here. Handling something that cannot happen makes little sense, and it is confusing to read.

Good to hear that someone else shares the same interpretation of those docs. I changed the code to assert instead.

**Review by tstuefe — APPROVED** [review]
Good

**Comment by jdksjolen** [comment]
> Good

Gah, I messed up the assert. It's "if base != nullptr then addr == base" aka `base == nullptr || addr == base`.

**Review by stefank — APPROVED** [review]

**Review by tstuefe — APPROVED** [review]
+1 (embarrassing... how did I miss that.)

**Review by gerard-ziemski — APPROVED** [review]

**Comment by jdksjolen** [comment]
Not yet.

**Pull request closed without merging**
