### PR TITLE
8342074: Fix runtime/Thread/TestAlwaysPreTouchStacks.java to be flagless or accept VM flags

### PR DESCRIPTION
**Pull request by afshin-zafari**
`createTestJavaProcessBuilder` is used for creating and running a new Java process that accepts flags.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342074](https://bugs.openjdk.org/browse/JDK-8342074): Fix runtime/Thread/TestAlwaysPreTouchStacks.java to be flagless or accept VM flags (**Sub-task** - P4)

### Reviewers
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21945/head:pull/21945` \
`$ git checkout pull/21945`

Update a local copy of the PR: \
`$ git checkout pull/21945` \
`$ git pull https://git.openjdk.org/jdk.git pull/21945/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21945`

View PR using the GUI difftool: \
`$ git pr show -t 21945`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21945.diff">https://git.openjdk.org/jdk/pull/21945.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21945#issuecomment-2461749227)
</details>

### CODE REVIEW

**Review by gerard-ziemski — APPROVED** [review]
LGTM

I traced the differences in PeocessTool code path to make sure that the fix does the right thing. Looks like the new code path uses VM flags as requested.


```
given:

ArrayList<String> vmArgs = new ArrayList<>();


from:

ProcessBuilder pb = ProcessTools.createLimitedTestJavaProcessBuilder(vmArgs);

    public static ProcessBuilder createLimitedTestJavaProcessBuilder(List<String> command) {
        return createLimitedTestJavaProcessBuilder(command.toArray(String[]::new));
    }

    public static ProcessBuilder createLimitedTestJavaProcessBuilder(String... command) {
        return createJavaProcessBuilder(command);
    }

    private static ProcessBuilder createJavaProcessBuilder(String... command) {
      ...
    }


to:

ProcessBuilder pb = ProcessTools.createTestJavaProcessBuilder(vmArgs);

    public static ProcessBuilder createTestJavaProcessBuilder(List<String> command) {
        return createTestJavaProcessBuilder(command.toArray(String[]::new));
    }

    public static ProcessBuilder createTestJavaProcessBuilder(String... command) {
        return createJavaProcessBuilder(Utils.prependTestJavaOpts(command));
    }

    private static ProcessBuilder createJavaProcessBuilder(String... command) {
      ...
    }

```

**Comment by gerard-ziemski** [comment]
Can you please double check the failures to make 100% sure it's not due to this fix?

**Review by lmesnik — APPROVED** [review]

**Comment by afshin-zafari** [comment]
> Can you please double check the failures to make 100% sure it's not due to this fix?

The GHA failures are about not finding developer directory which is not related to this PR. Thanks for catching them.

**Comment by afshin-zafari** [comment]
Thanks @gerard-ziemski and @lmesnik for your review.
GHA failure is not relevant.
/integrate

**Pull request closed without merging**
