### PR TITLE
8282538: PKCS11 tests fail on CentOS Stream 9

### PR DESCRIPTION
**Pull request by omikhaltsova**
I would like to add cert9.db and key4.db to /test/jdk/sun/security/pkcs11/nss/db/ to fix the PKCS11 tests failure on CentOS Stream 9.
Starting from NSS 3.35 cert9.db and key4.db files may be targeted instead of cert8.db and key3.db.
In case of CentOS Stream 9 the lowest available version of NSS for downgrade is 3.67 and cert9.db, key4.db are targeted.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282538](https://bugs.openjdk.java.net/browse/JDK-8282538): PKCS11 tests fail on CentOS Stream 9

### Reviewers
 * [Sean Mullan](https://openjdk.java.net/census#mullan) (@seanjmullan - **Reviewer**)
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7658/head:pull/7658` \
`$ git checkout pull/7658`

Update a local copy of the PR: \
`$ git checkout pull/7658` \
`$ git pull https://git.openjdk.java.net/jdk pull/7658/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7658`

View PR using the GUI difftool: \
`$ git pr show -t 7658`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7658.diff">https://git.openjdk.java.net/jdk/pull/7658.diff</a>

</details>

### CODE REVIEW

**Comment by omikhaltsova** [comment]
gentle ping; pls review this pr!

**Comment by XueleiFan** [comment]
what are included int the cert9.db and key4.db? Imported/copied from cert8.db and key3.db or generated on the fly?

**Comment by omikhaltsova** [comment]
These files are just copied from another place of the repo as shown in the comments to JDK-8282538. They already exist. 
```
[olga@localhost projects]$ cp ./jdk-fork/test/jdk/sun/security/pkcs11/Secmod/cert9.db ./jdk-fork/test/jdk/sun/security/pkcs11/nss/db/ 
[olga@localhost projects]$ cp ./jdk-fork/test/jdk/sun/security/pkcs11/Secmod/key4.db ./jdk-fork/test/jdk/sun/security/pkcs11/nss/db/ 
```

**Comment by seanjmullan** [comment]
Ok, thanks for the clarification. This change seems fine to me then.

**Review by seanjmullan — APPROVED** [review]

**Review by XueleiFan — APPROVED** [review]
It looks good to me if the db files are copied from Secmod.

**Pull request closed without merging**
