### PR TITLE
8246585: ForkJoin updates

### PR DESCRIPTION
**Pull request by Martin-Buchholz**
/cc core-libs

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8246585](https://bugs.openjdk.java.net/browse/JDK-8246585): ForkJoin updates
 * [JDK-8229253](https://bugs.openjdk.java.net/browse/JDK-8229253): forkjoin/FJExceptionTableLeak.java fails "AssertionError: failed to satisfy condition"

### Reviewers
 * [Doug Lea](https://openjdk.java.net/census#dl) (@DougLea - **Reviewer**) ⚠️ Review applies to c4d417b2d93fdaa76f152f02bfb71b6a9b5f2296

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1646/head:pull/1646`
`$ git checkout pull/1646`

### CODE REVIEW

**Comment by shipilev** [comment]
It would be nice to get it tested with GH Actions. "Checks" tabs should have those testing results automatically on push, but it is empty. Probably because your fork is not configured for it. Please go to https://github.com/Martin-Buchholz/jdk/actions -- and see if it says anything suspicious? Triggering the (only) workflow manually against your branch would help too.

**Review by DougLea — APPROVED** [review]

**Pull request closed without merging**
