### PR TITLE
8315863: [GHA] Update checkout action to use v4

### PR DESCRIPTION
**Pull request by sormuras**
Please review this change to update all workflows to use `actions/checkout@v4`.

Find the associated release notes here: https://github.com/actions/checkout/releases/tag/v4.0.0

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315863](https://bugs.openjdk.org/browse/JDK-8315863): [GHA] Update checkout action to use v4 (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15620/head:pull/15620` \
`$ git checkout pull/15620`

Update a local copy of the PR: \
`$ git checkout pull/15620` \
`$ git pull https://git.openjdk.org/jdk.git pull/15620/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15620`

View PR using the GUI difftool: \
`$ git pr show -t 15620`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15620.diff">https://git.openjdk.org/jdk/pull/15620.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15620#issuecomment-1710322572)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
I guess we can do this, but does it fix any actual bug or gives us improvements we can us?

**Comment by sormuras** [comment]
Mainly because the underlying Node version used by `actions/checkout` will reach EOL soon:

Copied from https://github.com/actions/checkout/pull/1436
> Node12 was deleted from runner. Node20 was added to Actions Runner on v2.308.0.
> Node16 has en end of life on 11 Sep 2023.

**Review by shipilev — APPROVED** [review]
Oh, okay then!

**Comment by shipilev** [comment]
Please wait for GHA to complete before integrating GHA patches!

**Comment by sormuras** [comment]
> Please wait for GHA to complete before integrating GHA patches!

Yes, sure. Next time, I'll wait for completion - this time, I checked that `actions/checkout@v4` steps were successfully run in https://github.com/openjdk/jdk/pull/15620/checks

**Comment by shipilev** [comment]
> > Please wait for GHA to complete before integrating GHA patches!
> 
> Yes, sure. Next time, I'll wait for completion - this time, I checked that `actions/checkout@v4` steps were successfully run in https://github.com/openjdk/jdk/pull/15620/checks

Yeah, the problem with some GH action steps is that they have "epilog" steps that run at the end of the pipe. So when changing GH action stuff, it is important to see that all steps have completed, which usually means the complete run.

**Pull request closed without merging**
