### PR TITLE
8344575: Examine usage of ReflectUtil.forName() in java.sql.rowset - XmlReaderContentHandler

### PR DESCRIPTION
**Pull request by bchristi-git**
`XmlReaderContentHandler.endElement()` routes a `Class.forName()` call through `ReflectUtil.forName()`. When `sun.reflect.misc.ReflectUtil.forName()` calls the 1-arg `Class.forName()`, it is doing so from `java.base`, and so using the boot loader.

Changing `XmlReaderContentHandler` to use the 3-arg `Class.forName()` method with a null classloader should yield equivalent behavior.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344575](https://bugs.openjdk.org/browse/JDK-8344575): Examine usage of ReflectUtil.forName() in java.sql.rowset - XmlReaderContentHandler (**Bug** - P4)

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) Review applies to [8202d66b](https://git.openjdk.org/jdk/pull/22585/files/8202d66bba5c034b4fe14d792b7499ad5fddafb3)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) Review applies to [8202d66b](https://git.openjdk.org/jdk/pull/22585/files/8202d66bba5c034b4fe14d792b7499ad5fddafb3)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**) Review applies to [8202d66b](https://git.openjdk.org/jdk/pull/22585/files/8202d66bba5c034b4fe14d792b7499ad5fddafb3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22585/head:pull/22585` \
`$ git checkout pull/22585`

Update a local copy of the PR: \
`$ git checkout pull/22585` \
`$ git pull https://git.openjdk.org/jdk.git pull/22585/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22585`

View PR using the GUI difftool: \
`$ git pr show -t 22585`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22585.diff">https://git.openjdk.org/jdk/pull/22585.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22585#issuecomment-2521520142)
</details>

### CODE REVIEW

**Review by mlchung — APPROVED** [review]

**Comment by AlanBateman** [comment]
ReflectUtil.forName can be removed as this is the last usage. Also java.base no longer needs to import sun.reflect.misc to java.sql.rowset.

**Comment by bchristi-git** [comment]
> ReflectUtil.forName can be removed as this is the last usage. Also java.base no longer needs to export sun.reflect.misc to java.sql.rowset.

Right, thanks.
Done.

**Review by AlanBateman — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]
Looks OK Brent, you will need to add a label to the JBS issue to mark the issue as noreg-cleanup noreg-trivial  etc..., otherwise, at some point someone will be looking for a test with this change

**Review by liach — APPROVED** [review]
The change to ReflectUtil looks good.

**Review by LanceAndersen — APPROVED** [review]

**Pull request closed without merging**
