### PR TITLE
8298709: Fix typos in src/java.desktop/ and various test classes of client component

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review for this change which only fixes typos? The original PR for this change is https://github.com/openjdk/jdk/pull/10029. However, that PR included changes to multiple different files in different areas of the JDK and as a result didn't see progress.

This current PR splits off those changes and includes only client area related typo fixes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298709](https://bugs.openjdk.org/browse/JDK-8298709): Fix typos in src/java.desktop/ and various test classes of client component

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Contributors
 * Michael Ernst `<mernst@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11661/head:pull/11661` \
`$ git checkout pull/11661`

Update a local copy of the PR: \
`$ git checkout pull/11661` \
`$ git pull https://git.openjdk.org/jdk pull/11661/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11661`

View PR using the GUI difftool: \
`$ git pr show -t 11661`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11661.diff">https://git.openjdk.org/jdk/pull/11661.diff</a>

</details>

### CODE REVIEW

**Review by irisclark — APPROVED** [review]
Thanks for the stutter elimination.

**Review by prrace — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you Iris and Phil for the reviews.

**Pull request closed without merging**
