### PR TITLE
8310711: [IR Framework] Remove safepoint while printing handling

### PR DESCRIPTION
**Pull request by chhagedorn**
This clean-up PR removes the handling of the `<!-- safepoint while printing -->` message in the IR framework. It is no longer required since we dump the output of `PrintIdeal` to the hotspot_pid file differently since [JDK-8306922](https://bugs.openjdk.org/browse/JDK-8306922). There is no interrupting `<!-- safepoint while printing -->` message anymore. I removed the corresponding now unneeded code together with the previously added test case for it.

Testing: tier1-4

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310711](https://bugs.openjdk.org/browse/JDK-8310711): [IR Framework] Remove safepoint while printing handling (**Enhancement** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16921/head:pull/16921` \
`$ git checkout pull/16921`

Update a local copy of the PR: \
`$ git checkout pull/16921` \
`$ git pull https://git.openjdk.org/jdk.git pull/16921/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16921`

View PR using the GUI difftool: \
`$ git pr show -t 16921`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16921.diff">https://git.openjdk.org/jdk/pull/16921.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16921#issuecomment-1836073270)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Nice cleanup, looks good to me.

**Comment by chhagedorn** [comment]
Thanks Tobias for your review!

**Review by eme64 — APPROVED** [review]
Thanks for the cleanup @chhagedorn , LGTM!

**Comment by chhagedorn** [comment]
Thanks Emanuel for your review! I will integrate this in the new year when I'm back again.

**Review by TobiHartmann — APPROVED** [review]

**Review by eme64 — APPROVED** [review]

**Pull request closed without merging**
