### PR TITLE
8290482: Update JNI Specification of DestroyJavaVM for better alignment with JLS, JVMS, and Java SE API Specifications

### PR DESCRIPTION
**Pull request by dholmes-ora**
This update is primarily about changes to the JNI Invocation API specification, mainly in relation to `DestroyJavaVM`. The motivation for the changes is to align with changes being made to the JLS, JVMS and `java.lang.Runtime`, specifications in relation to VM termination - ref:

JDK-8290196 12.8: Clarify the definition of program exit
https://bugs.openjdk.org/browse/JDK-8290196

JDK-8290388 5.7: Clarify the definition of JVM termination
https://bugs.openjdk.org/browse/JDK-8290388

JDK-8290036 Define and specify Runtime shutdown sequence
https://bugs.openjdk.org/browse/JDK-8290036

Mostly these are just non-normative changes to the JNI spec prose but there are two actual specification changes:

1.  The fact it is an error to detach a thread with active Java frames was only mentioned in the overview section, not in the actual `DetachCurrentThread` specification. (Just an oversight - the VM already checked this)

2.  We need to make it an error to call `DestroyJavaVM` from an attached thread with active Java frames (as this can't work for the same reason we disallow `DetachCurrentThread`). This requires an implementation change in Hotspot.

Issue 2 covers the code change, and regression test, in this PR.

In addition the specification changes can be seen here:

- specdiff: http://cr.openjdk.java.net/~dholmes/8290482/8290482-jni-spec/diff.html
- original: http://cr.openjdk.java.net/~dholmes/8290482/8290482-jni-spec/jni-invocation-original.html
- new: http://cr.openjdk.java.net/~dholmes/8290482/8290482-jni-spec/jni-invocation-new.html

The specification itself is not open but comments on the spec changes are welcome - though please see the JBS issue and CSR request first. The revised wording has already been extensively reviewed/negotiated between Alex Buckley, Stuart Marks and myself, so any change must either be a glaring error/problem or else a trivial adjustment.

Thank you.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8290482](https://bugs.openjdk.org/browse/JDK-8290482): Update JNI Specification of DestroyJavaVM for better alignment with JLS, JVMS, and Java SE API Specifications
 * [JDK-8292897](https://bugs.openjdk.org/browse/JDK-8292897): Update JNI Specification of DestroyJavaVM for better alignment with JLS, JVMS, and Java SE API Specifications (**CSR**)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10352/head:pull/10352` \
`$ git checkout pull/10352`

Update a local copy of the PR: \
`$ git checkout pull/10352` \
`$ git pull https://git.openjdk.org/jdk pull/10352/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10352`

View PR using the GUI difftool: \
`$ git pr show -t 10352`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10352.diff">https://git.openjdk.org/jdk/pull/10352.diff</a>

</details>

### CODE REVIEW

**Review by robehn — APPROVED** [review]
Looks good, thank you!

**Comment by dholmes-ora** [comment]
Thanks @robehn !

**Review by coleenp — APPROVED** [review]
This seems good.  I looked at the specification changes and they looked okay also.

**Comment by dholmes-ora** [comment]
Thanks @coleenp !

**Comment by dholmes-ora** [comment]
CSR is now approved.

**Pull request closed without merging**
