### PR TITLE
8304835 jdk/jfr/event/oldobject/TestArrayInformation.java fails with "Could not find event with class ... as (leak) object"

### PR DESCRIPTION
**Pull request by egahlin**
Could I have a review of a test fix?

The test fails intermittently because it's hard to guarantee that an object is being sampled. Fix is to repeat until one is found.

Testing: jdk/jdk/event/oldObject/TestArrayInformation.java

Thanks
Erik

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304835](https://bugs.openjdk.org/browse/JDK-8304835): jdk/jfr/event/oldobject/TestArrayInformation.java fails with "Could not find event with class ... as (leak) object" (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [f7cfa4f7](https://git.openjdk.org/jdk/pull/14467/files/f7cfa4f7a78e832dfe6a8e5b4665c2c9859dd5e7)
 * [Markus Grönlund](https://openjdk.org/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14467/head:pull/14467` \
`$ git checkout pull/14467`

Update a local copy of the PR: \
`$ git checkout pull/14467` \
`$ git pull https://git.openjdk.org/jdk.git pull/14467/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14467`

View PR using the GUI difftool: \
`$ git pr show -t 14467`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14467.diff">https://git.openjdk.org/jdk/pull/14467.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14467#issuecomment-1591171487)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
So now the "failing" test would timeout? This does not look right.

How many tries it usually takes to get a lucky sample? Take that estimate and do about 10x more iterations and fail, if still not found?

**Comment by shipilev** [comment]
> > So now the "failing" test would timeout? This does not look right.
> > How many tries it usually takes to get a lucky sample? Take that estimate and do about 10x more iterations and fail, if still not found?
> 
> The test will timeout, not sure that is a problem. Looking at the log, it's obvious why. I don't know how many times are needed, so why not run as many as possible? This is the pattern we have used for other jfr tests.

Well, my concern is that timeouts are mostly treated as the infrastructural problems. I don't think anyone expects the test failure to manifest as timeout: the expectation is that tests complete in reasonable time, whether they pass or fail. Running until timeout is reached also makes the test dependent on TIMEOUT_FACTOR and other infrastructural tunings.

But you're right, JFR tests already do this, so it makes little sense in trying to address it in this PR. It would be nice to see if JFR tests can avoid timeouting on failure, some time later, though.

**Comment by shipilev** [comment]
Merge from master to get Windows GHA builds, and thus Windows GHA tests fixed.

**Review by shipilev — APPROVED** [review]
Apart from a stylistic nit below, looks fine.

**Review by mgronlun — APPROVED** [review]

**Pull request closed without merging**
