### PR TITLE
8309956: Shenandoah: Strengthen the mark word check in string dedup

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for details.

Additional testing:
 - [x] macos-aarch64-server-fastdebug, `hotspot_gc_shenandoah`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309956](https://bugs.openjdk.org/browse/JDK-8309956): Shenandoah: Strengthen the mark word check in string dedup (**Enhancement** - P4)

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - no project role)
 * [Zhengyu Gu](https://openjdk.org/census#zgu) (@zhengyu123 - **Reviewer**)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14455/head:pull/14455` \
`$ git checkout pull/14455`

Update a local copy of the PR: \
`$ git checkout pull/14455` \
`$ git pull https://git.openjdk.org/jdk.git pull/14455/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14455`

View PR using the GUI difftool: \
`$ git pr show -t 14455`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14455.diff">https://git.openjdk.org/jdk/pull/14455.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14455#issuecomment-1589884766)

### CODE REVIEW

**Review by earthling-amzn — APPROVED** [review]
LGTM.

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Review by ysramakrishna — APPROVED** [review]
🚢

**Comment by shipilev** [comment]
Thank you all!

/integrate

**Pull request closed without merging**
