### PR TITLE
8253905: Update sanity test suite to not place windows at (0,0)

### PR DESCRIPTION
**Pull request by amresh-sahu**
Four files has been modified:
        modified:   test/jdk/sanity/client/lib/SwingSet3/src/com/sun/swingset3/demos/dialog/DialogDemo.java
        modified:   test/jdk/sanity/client/lib/SwingSet3/src/com/sun/swingset3/demos/frame/FrameDemo.java
        modified:   test/jdk/sanity/client/lib/SwingSet3/src/com/sun/swingset3/demos/table/TableDemo.java
        modified:   test/jdk/sanity/client/lib/SwingSet3/src/com/sun/swingset3/demos/window/WindowDemo.java

Tested on Mach5 and all tests passes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253905](https://bugs.openjdk.java.net/browse/JDK-8253905): Update sanity test suite to not place windows at (0,0)

### Reviewers
 * [Alexandre Iline](https://openjdk.java.net/census#shurailine) (@shurymury - Committer)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/625/head:pull/625`
`$ git checkout pull/625`

### CODE REVIEW

**Review by shurymury — APPROVED** [review]

**Comment by amresh-sahu** [comment]
@mrserb @akolarkunnu 

Please review my code changes.

**Comment by robilad** [comment]
Hi, can you let me know under whose OCA your contributions would be covered via e-mail to dalibor.topic@oracle.com, please? Then I can verify your account. Thanks!

**Comment by kevinrushforth** [comment]
@robilad Amresh is an Oracle employee.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
