### PR TITLE
8322927: Unused code in LIR_Assembler::verify_oop_map

### PR DESCRIPTION
**Pull request by jyukutyo**
This is a trivial change to remove unused code.

Methods like as_string() or freeze() are not called for the stringStream object, so these are unused code. The object was used before the SPARC port was removed (071bd521bca).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322927](https://bugs.openjdk.org/browse/JDK-8322927): Unused code in LIR_Assembler::verify_oop_map (**Enhancement** - P4)

### Reviewers
 * [Tobias Holenstein](https://openjdk.org/census#tholenstein) (@tobiasholenstein - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17721/head:pull/17721` \
`$ git checkout pull/17721`

Update a local copy of the PR: \
`$ git checkout pull/17721` \
`$ git pull https://git.openjdk.org/jdk.git pull/17721/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17721`

View PR using the GUI difftool: \
`$ git pr show -t 17721`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17721.diff">https://git.openjdk.org/jdk/pull/17721.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17721#issuecomment-1931394624)

### CODE REVIEW

**Review by tobiasholenstein — APPROVED** [review]
Look good to me

**Review by chhagedorn — APPROVED** [review]
Looks good and trivial.

**Comment by jyukutyo** [comment]
Thank you for your reviews!

**Pull request closed without merging**
