### PR TITLE
8283466: C2: missing skeleton predicates in peeled loop

### PR DESCRIPTION
**Pull request by eme64**
Implemented initializing skeleton predicates for the peeled loop.

We have some predicates / checks before loops that are dependent on the range of the loop, they are checked at runtime. When we split a loop (eg. peeling, pre/main/post, unswitching) one of the sub-loops may get impossible data types and remove the data flow. For static type analysis for the control flow, we need so called skeleton predicates that implement these loop checks before each split off loop. If we do not do this static analysis we generally get `bad graph` asserts, as only removing data flow and not control flow leads to broken graphs.

This was already implemented for pre/main/post loops and loop unswitching, but not for peeling.

Ran large test suite.
Manual inspection shows that the instantiated skeleton predicate indeed collapses, in the provided regression test.

Rerunning some tests now...

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283466](https://bugs.openjdk.java.net/browse/JDK-8283466): C2: missing skeleton predicates in peeled loop

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8783/head:pull/8783` \
`$ git checkout pull/8783`

Update a local copy of the PR: \
`$ git checkout pull/8783` \
`$ git pull https://git.openjdk.java.net/jdk pull/8783/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8783`

View PR using the GUI difftool: \
`$ git pr show -t 8783`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8783.diff">https://git.openjdk.java.net/jdk/pull/8783.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by eme64** [comment]
/integrate
Thanks @rwestrel  and @chhagedorn for the help and review.

**Comment by eme64** [comment]
/sponsor
I just got committer status so this could work

**Comment by eme64** [comment]
/integrate
trying it this way then

**Pull request closed without merging**
