### PR TITLE
8256986: [PPC64] C2 crashes when accessing nonexisting jvms of CallLeafDirectNode

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
observe_safepoint() is called with jvms == NULL from fill_buffer with mach = CallLeafDirectNode.
That node represents a leaf call and does not safepoint.
"_guaranteed_safepoint" needs to get set correctly for all MachCallNodes after JDK-8254231. 

In addition MachCallRuntimeNode::ret_addr_offset() need update for the new assertion in output.cpp.
This was already fixed on some other platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ❌ (6/6 failed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x64 (build debug)](https://github.com/TheRealMDoerr/jdk/runs/1463223645)
- [Linux x64 (build hotspot minimal)](https://github.com/TheRealMDoerr/jdk/runs/1463223757)
- [Linux x64 (build hotspot no-pch)](https://github.com/TheRealMDoerr/jdk/runs/1463223673)
- [Linux x64 (build hotspot optimized)](https://github.com/TheRealMDoerr/jdk/runs/1463223779)
- [Linux x64 (build hotspot zero)](https://github.com/TheRealMDoerr/jdk/runs/1463223718)
- [Linux x64 (build release)](https://github.com/TheRealMDoerr/jdk/runs/1463223604)
- [Linux x86 (build debug)](https://github.com/TheRealMDoerr/jdk/runs/1463223557)
- [Linux x86 (build release)](https://github.com/TheRealMDoerr/jdk/runs/1463223536)

### Issue
 * [JDK-8256986](https://bugs.openjdk.java.net/browse/JDK-8256986): [PPC64] C2 crashes when accessing nonexisting jvms of CallLeafDirectNode

### Reviewers
 * @jrziviani (no known github.com user name / role)
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1418/head:pull/1418`
`$ git checkout pull/1418`

### CODE REVIEW

**Review by jrziviani — APPROVED** [review]
Looks good to me

**Review by jrziviani — APPROVED** [review]
Thanks for fixing it. Before this patch I was getting
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffff73a50ec, pid=3812898, tid=3812899
```
I was trying to find the issue. Thank you!

**Review by RealCLanger — APPROVED** [review]
LGTM

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews!
/integrate

**Pull request closed without merging**
