### PR TITLE
8300644: Remove gc/shenandoah/jni/TestStringCriticalWithDedup.java

### PR DESCRIPTION
**Pull request by fisk**
The gc/shenandoah/jni/TestStringCriticalWithDedup.java test was designed to catch failure to pin strings being passed out to JNI critical users, because that used to be dangerous. After [JDK-8299673](https://bugs.openjdk.org/browse/JDK-8299673) that is not dangerous any longer. Conversely, now we kind of want deduplication to proceed regardless of JNI critical, which defeats the purpose of this test. It should be removed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300644](https://bugs.openjdk.org/browse/JDK-8300644): Remove gc/shenandoah/jni/TestStringCriticalWithDedup.java

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - no project role)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [ca12e310](https://git.openjdk.org/jdk/pull/12089/files/ca12e310f839674500dbd82bc846d6a142231d68)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12089/head:pull/12089` \
`$ git checkout pull/12089`

Update a local copy of the PR: \
`$ git checkout pull/12089` \
`$ git pull https://git.openjdk.org/jdk pull/12089/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12089`

View PR using the GUI difftool: \
`$ git pr show -t 12089`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12089.diff">https://git.openjdk.org/jdk/pull/12089.diff</a>

</details>

### CODE REVIEW

**Review by earthling-amzn — CHANGES_REQUESTED** [review]
Looks like it will also be safe to delete `libTestStringCriticalWithDedup.c`.

**Review by MBaesken — APPROVED** [review]
LGTM

**Comment by fisk** [comment]
> Looks like it will also be safe to delete `libTestStringCriticalWithDedup.c`.

Ah yeah, look at that. Fixed.

**Comment by fisk** [comment]
Thanks for the reviews, @MBaesken and @earthling-amzn!

**Review by earthling-amzn — APPROVED** [review]

**Pull request closed without merging**
