### PR TITLE
8297292: java/nio/channels/FileChannel/FileExtensionAndMap.java is too slow

### PR DESCRIPTION
**Pull request by bplb**
Reduce the test’s disk space requirement by one third and the total number of files tested by half. With this change, the test was observed to still fail with a SIGBUS using JDK 11.0.15 on Linux 5.15.0-58. The test’s run time decreased by about two thirds: for one sample run from 29m56s to 10m13s in the CI on Linux-x64. A run with 50 repeats had no failures.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297292](https://bugs.openjdk.org/browse/JDK-8297292): java/nio/channels/FileChannel/FileExtensionAndMap.java is too slow

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [31d5700b](https://git.openjdk.org/jdk/pull/12479/files/31d5700b176e1227443d4913cce5379bb3177613)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12479/head:pull/12479` \
`$ git checkout pull/12479`

Update a local copy of the PR: \
`$ git checkout pull/12479` \
`$ git pull https://git.openjdk.org/jdk pull/12479/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12479`

View PR using the GUI difftool: \
`$ git pr show -t 12479`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12479.diff">https://git.openjdk.org/jdk/pull/12479.diff</a>

</details>

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Brian, the change looks fine to me. FileExtensionAndMap.java will need a copyright year update before integrating.

**Comment by AlanBateman** [comment]
10mins is still very slow for a test in this area, I wonder if there is a better way to test this scenario that would run in a much short time.

**Comment by bplb** [comment]
`FileExtensionAndMap.java` was added by the change which resolved [JDK-8168628](https://bugs.openjdk.org/browse/JDK-8168628). That change was backed out of JDK 11 because it broke sparse files. The underlying issue was really `Unsafe::copy[Swap]Memory` not using memory guards which was tracked in [JDK-8191278](https://bugs.openjdk.org/browse/JDK-8191278). The fix for this latter issue added the test `test/hotspot/jtreg/runtime/Unsafe/InternalErrorTest.java` which is presumably sufficient to test for the underlying cause for which `FileExtensionAndMap.java` is also testing. Given this quasi duplication, it appears safe to simply remove `FileExtensionAndMap.java` altogether.

**Review by AlanBateman — COMMENTED** [review]
The deletion looks fine.

**Pull request closed without merging**
