### PR TITLE
8277906: Incorrect type for IV phi of long counted loops after CCP

### PR DESCRIPTION
**Pull request by rwestrel**
This failure occurs because the iv phi of a long counted loop has the
wrong type after CCP. That happens because, during CCP, after the type
of the limit of the counted loop is updated, the type of the iv phi is
not recomputed. The fix is to apply to long counted loops the logic
that already exists for int counted loop.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277906](https://bugs.openjdk.java.net/browse/JDK-8277906): Incorrect type for IV phi of long counted loops after CCP

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6632/head:pull/6632` \
`$ git checkout pull/6632`

Update a local copy of the PR: \
`$ git checkout pull/6632` \
`$ git pull https://git.openjdk.java.net/jdk pull/6632/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6632`

View PR using the GUI difftool: \
`$ git pr show -t 6632`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6632.diff">https://git.openjdk.java.net/jdk/pull/6632.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — COMMENTED** [review]
Looks good to me but what about this code?

https://github.com/openjdk/jdk/blob/37ff7f3b66eaa74d62d6a93f2f34ec744db21834/src/hotspot/share/opto/phaseX.cpp#L1573-L1575

**Comment by rwestrel** [comment]
Thanks for the review.

> Looks good to me but what about this code?

Good catch. I didn't notice that one. I think it is specific to int counted loops when the pre/main/post loops are created.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by rwestrel** [comment]
@TobiHartmann @chhagedorn thanks for the reviews.

**Pull request closed without merging**
