### PR TITLE
8286314: Trampoline not created for far runtime targets outside small CodeCache

### PR DESCRIPTION
**Pull request by eastig**
`relocInfo::runtime_call_type` calls can have targets inside or outside CodeCache. If offsets to the targets are not in range, trampoline calls must be used. Currently trampolines for calls are generated based on the size of CodeCache and the maximum possible branch range. If the size of CodeCache is smaller than the range, no trampoline is generated. This works well if a target is inside CodeCache. It does not work if a target is outside CodeCache and CodeCache size is smaller than the maximum possible branch range.

### Solution
Runtime call sites are always in CodeCache. In case of a target outside small CodeCache, we can find the start of the longest possible branch from CodeCache. Then we check with `reachable_from_branch_at` whether a target is reachable. If not, a trampoline is needed.

### Testing
It is tested with the release and fastdebug builds. Release builds have the maximum possible branch range 128M. Fastdebug builds have it 2M for the purpose of testing trampolines.
Results:
- `gtest`: Passed
- `tier1`: Passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286314](https://bugs.openjdk.org/browse/JDK-8286314): Trampoline not created for far runtime targets outside small CodeCache

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9235/head:pull/9235` \
`$ git checkout pull/9235`

Update a local copy of the PR: \
`$ git checkout pull/9235` \
`$ git pull https://git.openjdk.org/jdk pull/9235/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9235`

View PR using the GUI difftool: \
`$ git pr show -t 9235`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9235.diff">https://git.openjdk.org/jdk/pull/9235.diff</a>

</details>

### CODE REVIEW

**Comment by eastig** [comment]
Hi Andrew(@theRealAph),
Could you please review the fix?

Thank you,
Evgeny

**Review by theRealAph — APPROVED** [review]
Looks good. Nice commenting too.

I guess we'll need backports. Has this bug ever materialized on old releases?

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by phohensee** [comment]
MacOS debug build failure looks unrelated.

**Comment by theRealAph** [comment]
> > I guess we'll need backports. Has this bug ever materialized on old releases?
> 
> I have not found any bug reports. I guess most of applications run with 240M CodeCache. Applications at risk are those which turn off tiered compilation. By default they get 48M CodeCache. They might have been lucky the whole code is within 128M range.

OK, so I'd probably not backport, then. I know it feels a bit weird to leave a known bug, but perhaps it's better to let sleeping dogs lie. What do you think?

**Comment by eastig** [comment]
> OK, so I'd probably not backport, then. I know it feels a bit weird to leave a known bug, but perhaps it's better to let sleeping dogs lie. What do you think?

We have `guarantee` which will catch the bug. However ASLR might make difficult to reproduce the bug.
I think it is not critical for 8 and 11. We are working to make JVM performance with 240M CodeCache similar to the performance with smaller CodeCache. This will decrease chances that people will use small CodeCache. We will be backporting enhancement to 17. 
It looks to me, risks are mitigated in old releases. There is no need for backports.

**Pull request closed without merging**
