### PR TITLE
8332237: [nmt] Remove the need for ThreadStackTracker::track_as_vm() 

### PR DESCRIPTION
**Pull request by tstuefe**
This PR simplifies NMT by removing a bunch of code needed only to track thread stacks on AIX (`ThreadStackTracker::track_as_vm()` is actually `#ifndef AIX` in disguise).

NMT has two ways to track thread stacks:
A) piggybacking on the virtual memory accounting
B) piggybacking on malloc accounting

(A) is done on all platforms except AIX. (B) is AIX.

This is because on AIX, thread stacks (more precisely, the boundaries of thread stacks as the JVM knows them) are not page-aligned. Therefore we track these stacks as if they had been allocated with malloc. This special handling adds a lot of complex coding to NMT.

We (@zhengyu123 and me) originally decided on this approach to keep NMT versatile and able to deal with platforms that place thread stacks wherever. Or with the hypothetical that the JVM manages its own thread stacks. The latter never manifested - for a number of reasons, the thread library tends to be better at managing thread stacks than the application.

In practice, we only ever did this for AIX. The irony is that with this method, we track stacks as if they were fully alive. So, arguably, this method is just a rather complicated way of iterating all live threads and adding up their thread stack sizes.

On all other platforms, we track thread stacks as virtual memory. For every thread stack tracked, we also query memory liveness via `os::committed_in_range` (on closer inspection, another misnomer since this function does not query commit state but liveness). `os::committed_in_range` is implemented on Linux and Windows, and a fallback variant exists that just acts as if the whole range were committed.

Solving the thread-stacks-not-page-aligned problem can be done in a much simpler way by aligning thread stack boundaries - for the purpose of NMT - inward to the next inner page boundaries. We pay a very small loss in fidelity. But we can now use the same method all other platforms use. We can throw away a bunch of code. And, if we ever implement `os::committed_in_range` for AIX, we get real thread stack liveness tracking for free.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332237](https://bugs.openjdk.org/browse/JDK-8332237): [nmt] Remove the need for ThreadStackTracker::track_as_vm() (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Afshin Zafari](https://openjdk.org/census#azafari) (@afshin-zafari - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19231/head:pull/19231` \
`$ git checkout pull/19231`

Update a local copy of the PR: \
`$ git checkout pull/19231` \
`$ git pull https://git.openjdk.org/jdk.git pull/19231/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19231`

View PR using the GUI difftool: \
`$ git pr show -t 19231`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19231.diff">https://git.openjdk.org/jdk/pull/19231.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19231#issuecomment-2114878400)

### CODE REVIEW

**Comment by tstuefe** [comment]
Ping @jdksjolen @afshin-zafari @gerard-ziemski

**Comment by tstuefe** [comment]
Thanks to @JoKern65 for running this through the AIX CI at SAP

**Review by jdksjolen — COMMENTED** [review]
Hi,

I'm very happy to see this simplification being made in NMT, thank you for doing this! Code looks good to me, have you run this through any non-AIX CI?

**Review by jdksjolen — APPROVED** [review]

**Comment by tstuefe** [comment]
> Hi,
> 
> I'm very happy to see this simplification being made in NMT, thank you for doing this! Code looks good to me, have you run this through any non-AIX CI?

Yes, it ran the full gamut of tests over at SAP. They test on a ton of platforms.

**Comment by jdksjolen** [comment]
> > Hi,
> > I'm very happy to see this simplification being made in NMT, thank you for doing this! Code looks good to me, have you run this through any non-AIX CI?
> 
> Yes, it ran the full gamut of tests over at SAP. They test on a ton of platforms.

Ship it! (after receiving another review)

**Comment by tstuefe** [comment]
Thanks @jdksjolen and @afshin-zafari . I'll wait the obligatory 24, and maybe for @zhengyu123 to chime in in case I got some of the history wrong.

**Pull request closed without merging**
