### PR TITLE
8316523: Relativize esp in interpreter frames (PowerPC only)

### PR DESCRIPTION
**Pull request by fbredber**
Relativize esp (Expression Stack Pointer on PowerPC) in interpreter frames.

By changing the "esp" member in interpreter frames from being an absolute address into an offset that is relative to the frame pointer, we don't need to change the value as we freeze and thaw frames of virtual threads. This is since we might freeze and thaw from and to different worker threads, so the absolute address to locals might change, but the offset from the frame pointer will be constant.

This subtask only handles "esp" on PowerPC. The relativization of other interpreter frame members are handled in other subtasks to [JDK-8289296](https://bugs.openjdk.org/browse/JDK-8289296).

It has been sanity tested onr PowerPC using Qemu.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316523](https://bugs.openjdk.org/browse/JDK-8316523): Relativize esp in interpreter frames (PowerPC only) (**Sub-task** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15999/head:pull/15999` \
`$ git checkout pull/15999`

Update a local copy of the PR: \
`$ git checkout pull/15999` \
`$ git pull https://git.openjdk.org/jdk.git pull/15999/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15999`

View PR using the GUI difftool: \
`$ git pr show -t 15999`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15999.diff">https://git.openjdk.org/jdk/pull/15999.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15999#issuecomment-1741758952)

### CODE REVIEW

**Comment by fbredber** [comment]
Since this is a PowerPC only PR, I think this needs to be reviewed by @TheRealMDoerr.

**Comment by TheRealMDoerr** [comment]
Thanks for taking care of PPC64! Looks correct. Seems like `relativize_one` and `derelativize_one` are no longer used and should better get removed?

**Review by TheRealMDoerr — APPROVED** [review]
Thanks! This looks good.
@reinrich: Maybe you can provide a 2nd review?

**Review by fisk — APPROVED** [review]
Seems reasonable.

**Comment by fbredber** [comment]
Hi @TheRealMDoerr, do you want to wait some more for @reinrich to review this PR, or do you think it's ready to be integrated?

**Comment by TheRealMDoerr** [comment]
Ship it!

**Comment by reinrich** [comment]
> Hi @TheRealMDoerr, do you want to wait some more for @reinrich to review this PR, or do you think it's ready to be integrated?

Thanks for doing this!
No need to wait for me after Martin has given his thumbs-up.
Cheers, Richard.

**Comment by fbredber** [comment]
About taking care of PPC64. If I get something to work on x86 and aarch64, it's often not too much work to get it to run on the other platforms (like ppc), and by doing so I get a much better understanding of the general concepts, since the concepts may be more thoroughly described in some cpu port than in others. And, if you're new to a large code base, any method that makes you understand the concepts better, is a good thing. As usual, I still need a sponsor to get the show on the road.
Cheers guys, Fredrik

**Pull request closed without merging**
