### PR TITLE
8269923: runtime/jni/checked/TestPrimitiveArrayCriticalWithBadParam.java failed with "FATAL ERROR in native method: Primitive type array expected but not received for JNI array operation"

### PR DESCRIPTION
**Pull request by zhengyu123**
On Posix compatible platforms, when abort with code dump, it exits with os:abort(), which has exit code 134.
```
  if (dump_core) {
    LINUX_ONLY(if (DumpPrivateMappingsInCore) ClassLoader::close_jrt_image();)
    ::abort(); // dump core
  }

```
but not on Windows, where it still exits with 1.

```
  CloseHandle(dumpFile);
  win32::exit_process_or_thread(win32::EPT_PROCESS, 1);
```

The test expects exit code 134 when jni check fails, so it fails on Windows. Maybe we should have Windows also to return 134 for consistence?

The fix changes the check to non-zero exit code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269923](https://bugs.openjdk.java.net/browse/JDK-8269923): runtime/jni/checked/TestPrimitiveArrayCriticalWithBadParam.java failed with "FATAL ERROR in native method: Primitive type array expected but not received for JNI array operation"

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4696/head:pull/4696` \
`$ git checkout pull/4696`

Update a local copy of the PR: \
`$ git checkout pull/4696` \
`$ git pull https://git.openjdk.java.net/jdk pull/4696/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4696`

View PR using the GUI difftool: \
`$ git pr show -t 4696`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4696.diff">https://git.openjdk.java.net/jdk/pull/4696.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Comment by dcubed-ojdk** [comment]
@zhengyu123 - I forgot to ask about what testing has been done?

**Review by dholmes-ora — APPROVED** [review]
The fix is good.

The 134 exit code on Posix systems comes from the fact that abort() raises SIGABRT, which is signal number 6 (b0110) . The exit code of the process is set by the OS in the lower 8 bits of the return value: bits 0-6 contains the signal number; bit 7 is set if a core dump occurs. So we have  an exit value of b10000110 == decimal 134.

It is debatable whether we should make Windows behave the same for our os::abort.

Thanks,
David

**Comment by zhengyu123** [comment]
@dcubed-ojdk @dholmes-ora  Thanks for the reviews. GHA all clean.

**Pull request closed without merging**
