### PR TITLE
8338236: Compile error in cgroup code on Linux when using clang

### PR DESCRIPTION
**Pull request by MBaesken**
When building with
Ubuntu clang version 14.0.0-1ubuntu1.1

we run into the following compile error (seen on Linux ppc64le, probably also an error on x86_64) :

/jdk/src/hotspot/os/linux/cgroupV1Subsystem_linux.hpp:65:10: error: 'is_read_only' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    bool is_read_only() { return _read_only; }
         ^
/jdk/src/hotspot/os/linux/cgroupSubsystem_linux.hpp:108:18: note: overridden virtual function is here
    virtual bool is_read_only() = 0;
                 ^
In file included from /jdk/src/hotspot/os/linux/cgroupSubsystem_linux.cpp:30:
/jdk/src/hotspot/os/linux/cgroupV2Subsystem_linux.hpp:131:54: error: 'memory_controller' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    CachingCgroupController<CgroupMemoryController>* memory_controller() { return _memory; }
                                                     ^
/jdk/src/hotspot/os/linux/cgroupSubsystem_linux.hpp:235:62: note: overridden virtual function is here
    virtual CachingCgroupController<CgroupMemoryController>* memory_controller() = 0;

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338236](https://bugs.openjdk.org/browse/JDK-8338236): Compile error in cgroup code on Linux when using clang (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20562/head:pull/20562` \
`$ git checkout pull/20562`

Update a local copy of the PR: \
`$ git checkout pull/20562` \
`$ git pull https://git.openjdk.org/jdk.git pull/20562/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20562`

View PR using the GUI difftool: \
`$ git pr show -t 20562`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20562.diff">https://git.openjdk.org/jdk/pull/20562.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20562#issuecomment-2285611733)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
I'm surprised we're checking function overrides. But, I think it makes sense.

**Comment by MBaesken** [comment]
Seems there is a flag
'-Wsuggest-override'
Warn about overriding virtual functions that are not marked with the override keyword.
https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wsuggest-override
in gcc that looks at least similar; we could look into this.

**Comment by TheRealMDoerr** [comment]
Using override should do no harm. It actually improves the code. I wonder why it only complains about those 2 files. Aren't there more?

**Review by jerboaa — APPROVED** [review]
Looks good. Please fix the JBS issue title warning (uppercase letter in `compile`). Thanks!

**Comment by dholmes-ora** [comment]
Please do not doing anything that requires marking all overrides! Bring it up in a style guide discussion if you want to propose it.

**Comment by MBaesken** [comment]
> Please do not doing anything that requires marking all overrides! Bring it up in a style guide discussion if you want to propose it.

We have ~ 100 overrides already in the HS C++ code.  
Of course we can search for a flag that switches off the warning. But then I wonder why we have already so many override in the code ?

>  I wonder why it only complains about those 2 files. Aren't there more?

No more were found. Probably at those 2 locations in the code we have the special case, that they are not already covered by clang/macOS because it is Linux only code.

**Comment by MBaesken** [comment]
I tested with clang 14  on Linux,  and clang 15 on macOS.
Both show the  "overrides a member function but is not marked 'override'"   warning even  without setting -Wall or any special warning flags.
So it is just what we get from using current clang  on some platforms.
Switching off this warning, if this is desired,  could be handled in another PR.
Enabling the warning for more consistency on gcc, MSVC etc. is also another issue.

**Comment by stefank** [comment]
> > I wonder why it only complains about those 2 files. Aren't there more?
> 
> No more were found. Probably at those 3 locations in the code we have the special case, that they are not already covered by clang/macOS because it is Linux-only code.

It's not clear to me if you noticed that this warns about the "inconsistent" usage of `override`. It doesn't warn about using `override`. Some of the overridden functions where marked with `override` but not all. You can silence this warning by either doing what you did in this PR, or by removing the previously added `override` in those classes.

**Pull request closed without merging**
