### PR TITLE
8259482: jni_Set/GetField_probe are the same as their _nh versions

### PR DESCRIPTION
**Pull request by coleenp**
Remove the _nh versions.  Tested with tier1 and vmTestbase/nsk/jdi,jvmti tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259482](https://bugs.openjdk.java.net/browse/JDK-8259482): jni_Set/GetField_probe are the same as their _nh versions

### Reviewers
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2008/head:pull/2008`
`$ git checkout pull/2008`

### CODE REVIEW

**Review by hseigel — APPROVED** [review]
The changes look good!
Thanks, Harold

**Review by sspitsyn — APPROVED** [review]
LGTM++

Thanks,
Serguei

**Review by dholmes-ora — APPROVED** [review]
Cleanup looks good.

Thanks,
David

**Comment by coleenp** [comment]
Thanks Harold, Serguei and David.
/Integrate

**Pull request closed without merging**
