### PR TITLE
JDK-8299386: Refactor metaprogramming to use <type_traits>

### PR DESCRIPTION
**Pull request by jcking**
Cleanup `metaprogramming/` to just use implementations from `<type_traits>` that are available in C++11 and onward.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299386](https://bugs.openjdk.org/browse/JDK-8299386): Refactor metaprogramming to use <type_traits>

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11794/head:pull/11794` \
`$ git checkout pull/11794`

Update a local copy of the PR: \
`$ git checkout pull/11794` \
`$ git pull https://git.openjdk.org/jdk pull/11794/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11794`

View PR using the GUI difftool: \
`$ git pr show -t 11794`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11794.diff">https://git.openjdk.org/jdk/pull/11794.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — COMMENTED** [review]
I started out intending to suggest replacing some of these changes by instead
updating the uses of a couple that are rarely used, and getting rid of the
associated pre-C++11 synonyms entirely. But it turns out most are rarely used,
leading me to question this change almost in its entirety.

I think better would be a series of changes to replace uses of the synonyms
with the corresponding element from <type_traits> and delete the synonyms.  I
say "a series of changes" because I would prefer it not be done all in one
changeset, for easier reviewing.

I suggest making an exception for EnableIf, because of the number of uses and
because I'm hoping we'll be able to revise them in a better way in the not too
distant future. Many of the uses are for function SFINAE, where the syntax is
pretty horrible. We have the newer form of function SFINAE available (see
ENABLE_IF), but I think in many/most cases even better would be to use C++17
constexpr if. That's why I haven't proposed rewriting any of them using
ENABLE_IF. I'm hopeful that using C++17 isn't too far away, now that there
seems to be a compiler available for the aix-ppc port.

**Comment by jcking** [comment]
@kimbarrett I created 6 separate issues and associated PRs to deal with parts of them in isolation, so far.

JDK-8299399, JDK-8299396, JDK-8299395, JDK-8299398, JDK-8299402, and JDK-8299397.

Once those are in I'll re-visit this and see how we can chop the remaining work and remove most of what remains of metaprogramming/, minus enableIf.hpp, logic.hpp, and primitiveConversions.hpp.

**Comment by jcking** [comment]
@kimbarrett Though once its just those three files, it begs the question of whether having `metaprogramming/` itself is necessary. Maybe it makes more sense to have a single header under utilities/?

**Comment by kimbarrett** [comment]
> @kimbarrett Though once its just those three files, it begs the question of whether having `metaprogramming/` itself is necessary. Maybe it makes more sense to have a single header under `utilities/`?

I'm hopeful that we'll soon have C++17, which will similarly remove the need for logical.hpp.  There aren't many uses of those metafunctions either.  So I think there's no point in moving it.

I've already described what I think should be done with EnableIf, so again no point in moving it.

PrimitiveConversions::cast<T> => std::bit_cast<T>, but that's in C++20, so likely still some way out for us.
And the PrimitiveConversions::Translate is our own thing.
So it might make sense to move that someday, but I don't see any need to hurry.

**Comment by kimbarrett** [comment]
> @kimbarrett I created 6 separate issues and associated PRs to deal with parts of them in isolation, so far.
> 
> JDK-8299399, JDK-8299396, JDK-8299395, JDK-8299398, JDK-8299402, and JDK-8299397.
> 
> Once those are in I'll re-visit this and see how we can chop the remaining work and remove most of what remains of `metaprogramming/`, minus `enableIf.hpp`, `logic.hpp`, and `primitiveConversions.hpp`.

Thanks.  Those PRs were very easy to review.

**Comment by xmas92** [comment]
Just a general question with regards too our style guide. What is the goal/idea behind this line? https://github.com/openjdk/jdk/blame/2ee34f14880cccca02e2933f80b000979f33c6d1/doc/hotspot-style.md#L578
> TODO: Rather than directly #including (permitted) Standard Library headers, use a convention of #including wrapper headers (in some location like hotspot/shared/stdcpp). This provides a single place for dealing with issues we might have for any given header, esp. platform-specific issues.

And is it relevant for any/all of these <type_trait> / metaprogramming changes?

**Comment by kimbarrett** [comment]
> Just a general question with regards too our style guide. What is the goal/idea behind this line? https://github.com/openjdk/jdk/blame/2ee34f14880cccca02e2933f80b000979f33c6d1/doc/hotspot-style.md#L578
> 
> > TODO: Rather than directly #including (permitted) Standard Library headers, use a convention of #including wrapper headers (in some location like hotspot/shared/stdcpp). This provides a single place for dealing with issues we might have for any given header, esp. platform-specific issues.
> 
> And is it relevant for any/all of these <type_trait> / metaprogramming changes?

This is kind of a hint / reminder / statement of intent for future direction,
particularly if/when we start permitting the use of more of the Standard
Library.  There were questions about whether we were going to do that and how
we might control it, back when I was doing the large revision of this document
for C++14 support.  It currently has no real force (it's a TODO item after all),
and probably doesn't really belong in the current document.  But there are
continuing discussions about opening up some amount of StdLib usage.

**Comment by jcking** [comment]
Backing out since this is being addressed in multiple separate PRs.

**Pull request closed without merging**
