### PR TITLE
8306036: Use @apiNote in String.toLowerCase, String.toUpperCase

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which suggests to use `@apiNote` in the `String.toLowerCase()` and `String.toUpperCase()` API docs.

These methods include important usage notes which today are encoded using `<b>Note:</b>`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306036](https://bugs.openjdk.org/browse/JDK-8306036): Use @apiNote in String.toLowerCase, String.toUpperCase

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13487/head:pull/13487` \
`$ git checkout pull/13487`

Update a local copy of the PR: \
`$ git checkout pull/13487` \
`$ git pull https://git.openjdk.org/jdk.git pull/13487/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13487`

View PR using the GUI difftool: \
`$ git pr show -t 13487`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13487.diff">https://git.openjdk.org/jdk/pull/13487.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13487#issuecomment-1509625024)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Replaces bolded-"Note" with "API Note" so looks reasonable. There may be a few like this around the JDK that pre-date the apiNote tag.

**Comment by eirbjo** [comment]
> There may be a few like this around the JDK that pre-date the apiNote tag.

There are 44 matches in 12 files in `src/java.base/share/classes/java`, including classes such as `HttpURLConnection`, `Character`, `SimpleDateFormat`, `Locale` and `ResourceBundle`.

Would you prefer that I expand this PR to take care of at least a few of those? Happy to do so, but it will require more reviewer cycles. (Although changes should be fairly straightforward).

**Comment by AlanBateman** [comment]
> Would you prefer that I expand this PR to take care of at least a few of those? Happy to do so, but it will require more reviewer cycles. (Although changes should be fairly straightforward).

Gosh no, my comment was to say that there are likely many other cases where a bolded-"Note" is used to communicate an API note as that was the norm before the apiNote tag was added. Not important but they could be looked at in other PRs, the main thing is to ensure that notes for implementors aren't accidentally changed to API notes, or that text that follows a "Note" doesn't accidentally become part of an API note.

**Comment by eirbjo** [comment]
Thanks for your review Alan, I have integrated as-is. Perhaps you could sponsor?

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
