### PR TITLE
8266973: Migrate to ClassHierarchyIterator when enumerating subclasses

### PR DESCRIPTION
**Pull request by iwanowww**
Replace ad-hoc recursion when enumerating subclasses with `ClassHierarchyIterator`.

Found 3 occurrences:
- `Dependencies::find_finalizable_subclass()`
- `reinitialize_vtable_of()`
- `VM_RedefineClasses::increment_class_counter()`

Testing:
- [x] hs-tier1 - hs-tier4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266973](https://bugs.openjdk.java.net/browse/JDK-8266973): Migrate to ClassHierarchyIterator when enumerating subclasses

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to cb586871d2557e3e9687df0d68b5d4ecc61323a0
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 54a4bdddd7df21d63ac206571264f9a0862739e9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3995/head:pull/3995` \
`$ git checkout pull/3995`

Update a local copy of the PR: \
`$ git checkout pull/3995` \
`$ git pull https://git.openjdk.java.net/jdk pull/3995/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3995`

View PR using the GUI difftool: \
`$ git pr show -t 3995`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3995.diff">https://git.openjdk.java.net/jdk/pull/3995.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Seems good.
I don't see link to testing in RFE.

**Comment by iwanowww** [comment]
Thanks for the review, Vladimir.

> I don't see link to testing in RFE.

Fixed.

**Review by coleenp — APPROVED** [review]
This looks really good.  I wonder if you can now make subklass() and next_sibling() functions private to Klass with it having ClassHierarchyIterator as a friend.  If not, I still approve.

**Comment by iwanowww** [comment]
> I wonder if you can now make subklass() and next_sibling() functions private to Klass with it having ClassHierarchyIterator as a friend.

There are some usages of `subklass()`/`next_sibling()` which don't benefit much from migration to `ClassHierarchyIterator` (e.g., `Dependencies::check_leaf_type()` and `ciInstanceKlass::dump_replay_data()`). I decided to leave them intact.

Nevertheless, I spotted 2 more occurrences (in JFR code) that benefit from migration to `ClassHierarchyIterator`. 

(Passed `hs-tier5-rt` - `hs-tier7-rt` testing.)

**Review by coleenp — APPROVED** [review]
good also!

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Coleen.

/integrate

**Pull request closed without merging**
