### PR TITLE
8340801: Disable ubsan checks in some awt/2d coding

### PR DESCRIPTION
**Pull request by MBaesken**
There is some old awt/2d coding where warnings occur when running with ubsan enabled binaries.
However at most of these locations the coding should work (at least on our supported platform set) so the warnings can be disabled at least for now.

The change adds a macro ATTRIBUTE_NO_UBSAN  similar to what we already use in Hotspot coding.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (3 reviews required, with at least 3 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8340801](https://bugs.openjdk.org/browse/JDK-8340801): Disable ubsan checks in some awt/2d coding (**Bug** - P4)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer) Review applies to [a2f89ecf](https://git.openjdk.org/jdk/pull/21184/files/a2f89ecfc06f637aa7e373ddd62aea8fe26a7aaf)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21184/head:pull/21184` \
`$ git checkout pull/21184`

Update a local copy of the PR: \
`$ git checkout pull/21184` \
`$ git pull https://git.openjdk.org/jdk.git pull/21184/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21184`

View PR using the GUI difftool: \
`$ git pr show -t 21184`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21184.diff">https://git.openjdk.org/jdk/pull/21184.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21184#issuecomment-2373936693)

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
jni\_md.h seems like a pretty big sledgehammer for something that seems to only be in one file, for just java.desktop. Is this macro planned to be used outside of java.desktop?

**Comment by MBaesken** [comment]
> jni_md.h seems like a pretty big sledgehammer for something that seems to only be in one file, for just java.desktop. Is this macro planned to be used outside of java.desktop?

Yes I have a couple (currently 2) more I would like to exclude as well .
The exclusions should work (similar to HS) for the whole  JDK C codebase.

**Comment by MBaesken** [comment]
> The exclusions should work (similar to HS) for the whole JDK C codebase.

Maybe we can offer a separate header ub.hpp next to jni_md.h  that contains the macro/attribute stuff.
Similar to sanitizers/ub.hpp in HS.  This header is then included in the few files were the macro/attributes are needed.

**Comment by TheShermanTanker** [comment]
> > jni_md.h seems like a pretty big sledgehammer for something that seems to only be in one file, for just java.desktop. Is this macro planned to be used outside of java.desktop?
> 
> Yes I have a couple (currently 2) more I would like to exclude as well . The exclusions should work (similar to HS) for the whole JDK C codebase.

Alright, if this is planned to be used across the entire JDK and not just in java.desktop then I guess this should be ok. Indeed, perhaps a ubsan.h header would be appropriate for a macro like this. I'll leave that up to further discussion

**Review by TheShermanTanker — APPROVED** [review]

**Comment by prrace** [comment]
/Reviewers 3 reviewers

This needs careful thinking about by various parties.
I am not sold on it, and the build team have indicated they do not support --enable-ubsan and my experience with that and similar options is that they are a nightmare to find a system on which they build and produce a working binary.

Until there's solid committed support by the leads of the build team I don't think we should be considering these kinds of PRs.

**Comment by MBaesken** [comment]
> build team have indicated they do not support --enable-ubsan 

What 'build team' are you talking about ? Some Oracle internal build team?
The ubsan support came in 2023, so nothing new (change was from Justin King)
https://github.com/openjdk/jdk/commit/7a85d95e828283d57e1df0344be454626470675d
And it was reviewed by erikj and ihse, I think those are members of the OpenJDK build group and very competent OpenJDK reviewers.
So the flag is as good or bad as any other configure flag of OpenJDK .

>and my experience with that and similar options is that they are a nightmare to find a system on which they build

We use and run this regularly on SUSE and Ubuntu Linux and have VERY good experience with it. It works (at least on recent Linux distros) very well. (on macOS our experience is a bit different there I had a couple of issues with ubsan)
A lot of large C/C++ based OSS projects support it like Linux kernel, Android, Chromium etc.
https://docs.kernel.org/dev-tools/ubsan.html
https://source.android.com/docs/security/test/ubsan
https://www.chromium.org/developers/testing/undefinedbehaviorsanitizer/

and btw.  Oracle blogs happily about it too and recommends it 
https://blogs.oracle.com/linux/post/improving-application-security-with-undefinedbehaviorsanitizer-ubsan-and-gcc
So it is a well established tool in the OSS world.

**Comment by TheShermanTanker** [comment]
> And it was reviewed by erikj and ihse, I think those are members of the OpenJDK build group

Erik and Magnus are indeed part of the build team. Erik is the Skara tool lead but does build work as well, while Magnus is pretty much the face of the build team at this point



> very competent OpenJDK reviewers

If only I could be a competent reviewer one of these days :(

**Comment by MBaesken** [comment]
Btw regarding the function/method exclusion, this was introduced in HS some time ago 
https://bugs.openjdk.org/browse/JDK-8334239
We just needed in HS codebase a couple of places where we use/keep undefined behavior  (e.g. im vmError.cpp where it is intentionally used).  Obviously, the mentioned HS change does not work for the other C libs so this is some kind of follow up.
In HS we use the ATTRIBUTE_NO_UBSAN macro currently at 4 code locations.  So it is not intended or likely that this macro would go to a lot of places of the JDK libs, just a small number comparable to usage in HS.
Regarding putting  it into jni_md.h, probably it would moving it from there to a separate header like it is done in HS would be better, I can do that if this is preferred.

**Comment by dholmes-ora** [comment]
`jni_md.h` is shipped as part of every JDK distribution - this change does NOT belong in that file.

**Comment by MBaesken** [comment]
> `jni_md.h` is shipped as part of every JDK distribution - this change does NOT belong in that file.

Hi David, should I introduce a separate ub.hpp  (similar to what we have in Hotspot) ?

**Comment by dholmes-ora** [comment]
> Hi David, should I introduce a separate ub.hpp (similar to what we have in Hotspot) ?

As previously discussed above a separate header would be best, though I'm not sure where it would be placed if you are using this across code in different modules.

**Comment by dholmes-ora** [comment]
@MBaesken my understanding is that src/java.base/share/native/include is for exported header files, it is not a general location to put this new header.

**Comment by MBaesken** [comment]
> @MBaesken my understanding is that src/java.base/share/native/include is for exported header files, it is not a general location to put this new header.

Seems the include directories
src/java.base/unix/native/libjava
and also hotspot/os/posix/include  and  src/hotspot/share/include 
show up in the  '-I'  settings of these C compilation units in jdk.  And from what I see those are not exported
Should I move the header to  some of these ?
Putting it into some hotspot location sounds odd  because we have already 'sanitizers/ub.hpp'    in hotspot.
So maybe src/java.base/unix/native/libjava  ?

**Comment by dholmes-ora** [comment]
`hotspot/share/include` contains the headers that hotspot exports to the jdk. `os/posix/include/` has the platform specific header that hotspot exports to the jdk.

> So maybe src/java.base/unix/native/libjava

That is header files for libjava.

This is why I said it would be hard to find a shared location where this can be used across different modules - because there presently isn't one.

**Comment by dholmes-ora** [comment]
jni_util.h is used across all modules but it is located in `java.base/share/native/libjava` not `java.base/unix/native/libjava`. 

I think you could probably place ub.h along-side jni_util.h in that directory.

**Comment by MBaesken** [comment]
> I think you could probably place ub.h along-side jni_util.h in that directory.

I moved the header to the better location.

**Comment by magicus** [comment]
@prrace 

>  the build team have indicated they do not support --enable-ubsan and my experience with that and similar options is that they are a nightmare to find a system on which they build and produce a working binary.

The UBSan functionality is well supported, as such, in the build system. As you say, actually building and running a JDK with UBSan functionality is not trivial. This just means that we are unlikely to e.g. run it continuously on our CI in the foreseeable future, not that any changes towards improving support for detecting undefined behavior should be stopped.

**Comment by magicus** [comment]
As a general note, we have discussed multiple times if, or rather how, we could have a generic library that is shared by native code across all Java modules, and Hotspot code alike, but no satisfactory solution has been found as of yet.

In this particular case, where all that is needed is an additional header file, I think the currently suggested solution of putting it in libjava makes sense. The majority of other JDK native libraries already depend on libjava.

**Review by magicus — APPROVED** [review]
From a build point of view, this looks good. 

I'm not commenting if it is correct to disable ub checking for `DEFINE_SOLID_DRAWGLYPHLISTAA` instead of trying to fix them.

**Comment by MBaesken** [comment]
>The UBSan functionality is well supported, as such, in the build system. As you say, actually building and running a JDK with 
> UBSan functionality is not trivial. This just means that we are unlikely to e.g. run it continuously on our CI

We are running it for some weeks now at least once a week in our central builds/tests  (so far only on Linux x86_64).
If you have a recent SUSE or Ubuntu ubsan works nicely with OpenJDK .  But I haven't checked on all popular distros.
In the past we had just too many ubsan-related issues in the OpenJDK codebase that even hindered doing a build, but this situation has improved a lot over the last months.

**Comment by magicus** [comment]
> We are running it for some weeks now at least once a week in our central builds/tests (so far only on Linux x86_64).

That is good to hear. Kudos to you for all your hard work on getting it there!

**Comment by MBaesken** [comment]
> jni_util.h is used across all modules but it is located in `java.base/share/native/libjava` not `java.base/unix/native/libjava`.
> 
> I think you could probably place ub.h along-side jni_util.h in that directory.


Hi David, are you fine with the latest version ?

**Review by TheShermanTanker — COMMENTED** [review]
I do wonder why the header both here and inside HotSpot is named ub.h instead of ubsan.h. Latter sounds better to me, but it doesn't really matter much

**Comment by magicus** [comment]
> I do wonder why the header both here and inside HotSpot is named ub.h instead of ubsan.h. Latter sounds better to me, but it doesn't really matter much

I agree it would have probably been better from the start, but at this point consistency with hotspot is more important.

**Comment by MBaesken** [comment]
In the review of the HS PR ubsan.hpp was discussed
https://github.com/openjdk/jdk/pull/19722
but then it was changed to ub.hpp .

**Comment by kimbarrett** [comment]
Not a review, just commenting.

I very much support the work @MBaesken has done with ubsan in HotSpot.
There's a bit of a chicken or egg problem with this kind of thing.  ubsan
isn't really usable and in any way supported or supportable until the code has
been made pretty much ubsan-clean.  Matthias has made substantial progress
toward that for HotSpot, and I thank him for this effort.

There are currently four uses of the disabling attribute in HotSpot.  Two are
for intentional things (writing to address zero intentionally, for testing
signal handling and the like).  One is for a known issue that is being worked
on, with an associated JBS issue; the attribute is being used to reduce
testing noise in the meantime.  The fourth is related to some of my recent
work (adjacent to, not caused by), and something that I think ought to be
fixed.  I'll be filing a JBS issue.  Along the way there have been a
substantial number of real bugs uncovered and addressed.

My only complaint has been a tendency to be a bit too quick to reach for the
disabling attribute, without sufficient analysis and attempt to resolve in a
way that corrects the problem.  Of the issues I've observed, the result of a
real fix nearly always ben a straight-up improvement.

**Comment by RealLucy** [comment]
I agree with @kimbarrett in his fear that a convenience macro may lower the hurdle of just suppressing an ubsan complaint. On the other hand, using a macro makes the code look cleaner. Should there ever be a need to change how ubsan is quiesced, it can be done at one place with the use of a macro. I therefore will give the change a LGTM.

**Comment by mrserb** [comment]
Can you please add a comment to the jbs - what warning is actually fixed by this change, and how to reproduce that?

**Comment by MBaesken** [comment]
@dholmes-ora  are you fine with the latest version ?

**Comment by dholmes-ora** [comment]
> @dholmes-ora are you fine with the latest version ?

Sorry just back from vacation. Noting further from me - header placement seems fine.

**Review by GoeLin — APPROVED** [review]
LGTM

**Pull request closed without merging**
