### PR TITLE
4130823: Not painting focus when the radio button has only icon

### PR DESCRIPTION
**Pull request by prsadhuk**
Although the issue here is asking about not painting focus when it has icon, however it seems Windows does not draw focus rect for radiobutton at all so instead of closing this as "Not an issue" it is made to not draw the focusrect even when there is text

This is what can be seen in windows system setting

systemsetting-nofocusrect

and notepad

notepad-nofocus

We have currently

beforefix-dashrect

and after fix

afterfix-nodashrect

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-4130823](https://bugs.openjdk.org/browse/JDK-4130823): Not painting focus when the radio button has only icon

### Reviewers
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer) ⚠️ Review applies to [4fbd354f](https://git.openjdk.org/jdk/pull/13153/files/4fbd354f7360141df160993b64489448df620ab2)
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer) ⚠️ Review applies to [4fbd354f](https://git.openjdk.org/jdk/pull/13153/files/4fbd354f7360141df160993b64489448df620ab2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13153/head:pull/13153` \
`$ git checkout pull/13153`

Update a local copy of the PR: \
`$ git checkout pull/13153` \
`$ git pull https://git.openjdk.org/jdk.git pull/13153/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13153`

View PR using the GUI difftool: \
`$ git pr show -t 13153`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13153.diff">https://git.openjdk.org/jdk/pull/13153.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13153#issuecomment-1480661216)

### CODE REVIEW

**Review by TejeshR13 — APPROVED** [review]
Fix is working as expected. Looks Good to me.

**Review by DamonGuy — APPROVED** [review]
Tested changes and confirmed it works as expected. I noticed the focus still shows for Metal & Motif. Should Metal be updated to reflect the same change?

**Comment by TejeshR13** [comment]
> Tested changes and confirmed it works as expected. I noticed the focus still shows for Metal & Motif. Should Metal be updated to reflect the same change?

Yeah, it's because the fix is Windows OS specific.

**Comment by DamonGuy** [comment]
> > Tested changes and confirmed it works as expected. I noticed the focus still shows for Metal & Motif. Should Metal be updated to reflect the same change?
> 
> Yeah, it's because the fix is Windows OS specific (Changes applied in Windows L&F).

Looks good to me then.

**Comment by DevCharly** [comment]
👎 👎 👎 

This is a bad idea IMHO.
If you remove focus rect from radiobutton and checkbox, **how can the user see where the focus is**? He can not!

And why removing focus rect only for radiobutton and checkbox, but not for button, slider, list, tree, table, etc?
There are a lot of components that show focus rect. It makes no sense to remove it from one component, but not from others.


>... however it seems Windows does not draw focus rect for radiobutton at all ...

This is not true.

Windows 11 Explorer file properties:

grafik

Windows 11 System settings (the rounded rectangle is the focus indicator; it is hidden by default, but shown when pressing TAB key):

grafik

**Comment by prsadhuk** [comment]
OK. I see the focusrect when TAB is pressed and it makes sense to show the focusrect to indicate where's the focus..I got misled by default no focusrect on the system settings.
I guess back to the original bug, then we have to draw the focus for only icons (without text) too but I couldn't find any system settings with that, how they behave..Did you happen to see any such settings?

**Pull request closed without merging**
