### PR TITLE
8271161: [BACKOUT] JDK-8249634 doclint should report implicit constructor as missing javadoc comments

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit c1c404896ca2791ad348a4cf482beb2c2ad98464.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271161](https://bugs.openjdk.java.net/browse/JDK-8271161): [BACKOUT] JDK-8249634 doclint should report implicit constructor as missing javadoc comments

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4880/head:pull/4880` \
`$ git checkout pull/4880`

Update a local copy of the PR: \
`$ git checkout pull/4880` \
`$ git pull https://git.openjdk.java.net/jdk pull/4880/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4880`

View PR using the GUI difftool: \
`$ git pr show -t 4880`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4880.diff">https://git.openjdk.java.net/jdk/pull/4880.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
The Mach5 Tier1 job has PASSed.

**Review by iignatev — APPROVED** [review]

**Comment by pavelrappo** [comment]
I think I know where the problem is: a hardcoded file separator, which is system dependent. Did the original patch for 8249634 fail on a Windows machine?

**Comment by dcubed-ojdk** [comment]
The fix for:

JDK-8249634 doclint should report implicit constructor as missing javadoc comments

failed on every OS in Mach5 Tier1. Not just Windows. This patch was clearly
not properly tested before being integrated. A [BACKOUT] is appropriate in
this situation.

**Comment by dcubed-ojdk** [comment]
@jonathan-gibbons has said that he is okay with a [BACKOUT] or a ProblemListing.
The [BACKOUT] is tested and ready so I'm going with it.

/integrate

**Comment by pavelrappo** [comment]
> This patch was clearly not properly tested before being integrated.

It seems that the patch was integrated without prior synchronization with the mainline, which had diverged in the relevant areas since the patch was last updated.

And no, it seems that the failure has nothing to do with the file separator. Sorry for the noise.

**Pull request closed without merging**
