### PR TITLE
8295665: [BACKOUT] JDK-8293409 [vectorapi] Intrinsify VectorSupport.indexVector

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit 857b0f9b05bc711f3282a0da85fcff131fffab91.

This [BACKOUT] was created via:
`git revert 857b0f9b05bc711f3282a0da85fcff131fffab91`
and there were no conflicts detected.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295665](https://bugs.openjdk.org/browse/JDK-8295665): [BACKOUT] JDK-8293409 [vectorapi] Intrinsify VectorSupport.indexVector

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10765/head:pull/10765` \
`$ git checkout pull/10765`

Update a local copy of the PR: \
`$ git checkout pull/10765` \
`$ git pull https://git.openjdk.org/jdk pull/10765/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10765`

View PR using the GUI difftool: \
`$ git pr show -t 10765`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10765.diff">https://git.openjdk.org/jdk/pull/10765.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by merykitty** [comment]
Can you check if #10764 fix the issue? Thanks a lot.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by dcubed-ojdk** [comment]
Sounds like a good plan to me.

**Comment by dcubed-ojdk** [comment]
My Tier1 testing for the [BACKOUT] has passed with no failures. I'm still in a holding
pattern for integration of the [BACKOUT] for now.

**Comment by chhagedorn** [comment]
Testing of #10764 looked good! Tier1 and 2 is completed and tier 3 is almost completed but the relevant tasks were successful. @merykitty you can proceed with the integration of #10764.

Thanks,
Christian

**Comment by merykitty** [comment]
Thanks a lot for your testing, I will integrate now

**Comment by dcubed-ojdk** [comment]
The fix for the following bug: 

[JDK-8295662](https://bugs.openjdk.org/browse/JDK-8295662) jdk/incubator/vector tests fail "assert(VM_Version::supports_avx512vlbw()) failed" 

has been reviewed and tested so we no longer need this [BACKOUT].

**Pull request closed without merging**
