### PR TITLE
8330107: Separate out "awt" libraries from Awt2dLibraries.gmk

### PR DESCRIPTION
**Pull request by magicus**
The file to build most of the java.desktop native libraries, Awt2dLibraries.gmk, is large and unstructured, making it hard to navigate.

I want to split it into two parts, one for the AWT libraries, and one for the 2D libraries. I also used this opportunity to change the order to be more logical (e.g. grouping "image" libraries and "font" libraries in 2D).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330107](https://bugs.openjdk.org/browse/JDK-8330107): Separate out "awt" libraries from Awt2dLibraries.gmk (**Enhancement** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18743/head:pull/18743` \
`$ git checkout pull/18743`

Update a local copy of the PR: \
`$ git checkout pull/18743` \
`$ git pull https://git.openjdk.org/jdk.git pull/18743/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18743`

View PR using the GUI difftool: \
`$ git pr show -t 18743`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18743.diff">https://git.openjdk.org/jdk/pull/18743.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18743#issuecomment-2049759603)

### CODE REVIEW

**Comment by magicus** [comment]
The default github review screen makes this a bit difficult to understand, especially AwtLibraries which it sees as a diff from the old Awt2d one. I recommend viewing the new file in its entirety instead: https://github.com/openjdk/jdk/blob/8180274092fa955cb7ff002bbdf3c32053dd337e/make/modules/java.desktop/lib/AwtLibraries.gmk

Also to clarify: I have only moved the individual library compilations around, and made no other changes.

**Comment by magicus** [comment]
@prrace I will need your assistance in confirming that my understanding about the AWT vs 2D split is correct. In particular, `libosxui` gave me some headache, but after trying to dig into the code my understanding ended up being that this is part of Swing which is considered part of AWT, not 2D.

I also looked at `libosx` and `libosxapp` which are located in the general `Lib.gmk` file. I could not easily see that they should have been placed in either 2d or Awt, so my assumption is that they are correctly placed outside these two new files.

**Comment by prrace** [comment]
> @prrace I will need your assistance in confirming that my understanding about the AWT vs 2D split is correct. In particular, `libosxui` gave me some headache, but after trying to dig into the code my understanding ended up being that this is part of Swing which is considered part of AWT, not 2D.
> 
> I also looked at `libosx` and `libosxapp` which are located in the general `Lib.gmk` file. I could not easily see that they should have been placed in either 2d or Awt, so my assumption is that they are correctly placed outside these two new files.

Swing isn't part of AWT. They are separate entities.
Swing is built on top of 2D as much as it is built on top of AWT.

Any hope of finding a neat dividing line will be arbitrary and not really reflecting reality

And in some ways AWT is more closely tied to AWT than 2D is.

And things are not the same across platforms either.
You've determined splashscreen is 2D functionality which it most certainly is not.

Awtlibraries is setting up the shaders which for the Metal rendering pipeline which is 100% 2D.

And it seems to be building OpenGL, etc as well ..

and generally I see so manay references to 2D in the AWT file and vice versa.

it isn't even true that "libawt" is awt. Libawt  is mostly a misnomer, in one case more than mostly. It ought to be called "lib2d"

So I think this change will just cause confusion and doesn't seem right to me. It ought to "not happen".

**Comment by magicus** [comment]
But the current solution is no good, either. For instance, the ordering is strange. awt_xawt and awt_lwawt is placed in opposite ends of the file, even though they are in some sense just platform specific variants of the same thing. And the entire file is huge and hard to navigate.

> and generally I see so manay references to 2D in the AWT file and vice versa.
> it isn't even true that "libawt" is awt. Libawt is mostly a misnomer, in one case more than mostly. It ought to be called "lib2d"

If this is the case, then it is clearly hopeless to try and split up the native code based on which area the source code used to compile it came from.

So let's go back to another approach: My starting point for this split was to take everything with "awt" in the name, and move it to a separate file. (I naively assumed that libs named "awt" belonged to AWT.) After reviewing the other libraries, my conclusion was to move yet another library there. But let's get that away from there.

So what if we keep the libraries named "awt" in a separate file, and all other in another file -- mostly this separation, but we agree that the reason for separation is not due to source code provenance, but just the name of the resulting libraries, and it does not need to signify anything but a need to be able to navigate in complex make files. And let's rename the "2dLibraries.gmk" file to `ClientLibraries.gmk` instead, so it is clear that there is no pretending that this is supposed to represent a 2D/AWT split.

Would that sound okay to you?

**Comment by magicus** [comment]
To rephrase myself: The goal here is to bring a huge Makefile into manageable chunks. I thought this could be done by separating AWT and 2D, but if that is not possible then any kind of predictable split is fine. I could just as well order libraries alphabetically by name and split the file half way down.

**Comment by magicus** [comment]
@prrace I tried implementing my suggestion: making the split based purely on having "awt" in the library name. I also clearly documented that the reason for the split do not imply anything about the source code. Would this be okay to you?

**Comment by prrace** [comment]
I still find this artificial, arbitrary, inconsistent, and even wrong.
The name "awt" in a library isn't a good way to divide it, but I don't have an alternative proposal
because there is no good way to divide it.
And I just don't agree with the premise. Or at least it is far outweighed by everything else.
I see it just sowing confusion and having to change 2 files etc.
So I don't support this change in any variation.

**Comment by magicus** [comment]
And just to put some perspective here: The .gmk files for all other modules are at an average of 2 kB. The Awt2dLibraries.gmk file is 32 kB. Even with the split the two remaining parts will be 16 kB, which is still larger than the next biggest file (java.base/gensrc/GensrcBuffer.gmk) at 14 kB. So this is really an outlier.

**Review by erikj79 — APPROVED** [review]
This looks good to me. The split may be arbitrary from a functional point of view, but will make navigating the makefiles easier.

**Comment by magicus** [comment]
Yes, I really want to do this. I am sorry that we could not reach an agreement, but I need to be able to work with these files in a better way than is currently possible.

Thanks Erik and Phil.

/integrate

**Comment by TheShermanTanker** [comment]
> There is no good IDE support for Makefiles, especially not with the level of customization that we have done to make. I am positively struggling with navigating this file, time and time again.

I find Eclipse CDT to be rather helpful with Makefile syntax highlighting, if that helps. Just have to set the .gmk extension to be recognized as a Makefile, and then you should be good to go

**Pull request closed without merging**
