### PR TITLE
8261448: Preserve GC stack watermark across safepoints in StackWalk

### PR DESCRIPTION
**Pull request by rkennke**
I am observing the following assert:

```
# Internal Error (/home/rkennke/src/openjdk/loom/src/hotspot/share/runtime/stackWatermark.cpp:178), pid=54418, tid=54534
# assert(is_frame_safe(f)) failed: Frame must be safe
```

(see issue for full hs_err)

In StackWalk::fetchNextBatch() we prepare the entire stack to be processed by calling StackWatermarkSet::finish_processing(jt, NULL, StackWatermarkKind::gc), but then subsequently, during frames scan, perform allocations to fill in the frame information (fill_in_frames => LiveFrameStream::fill_frame => fill_live_stackframe) at where we could safepoint for GC, which could reset the stack watermark.

This is only relevant for GCs that use the StackWatermark, e.g. ZGC and Shenandoah at the moment.

Solution is to preserve the stack-watermark across safepoints in StackWalk::fetchNextBatch(). StackWalk::fetchFirstBatch() doesn't look to be affected by this: it is not using the stack-watermark.

Testing:
 - [x] StackWalk tests with Shenandoah/aggressive
 - [x] StackWalk tests with ZGC/aggressive
 - [x] tier1 (+Shenandoah/ZGC)
 - [x] tier2 (+Shenandoah/ZGC)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261448](https://bugs.openjdk.java.net/browse/JDK-8261448): Preserve GC stack watermark across safepoints in StackWalk

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)
 * [Stefan Karlsson](https://openjdk.java.net/census#stefank) (@stefank - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2500/head:pull/2500`
`$ git checkout pull/2500`

### CODE REVIEW

**Comment by rkennke** [comment]
I'm converting back to draft. The Loom tests (test/jdk/java/lang/Continuation/*) are still failing and it looks like fetchFirstBatch() does indeed require treatment, and it's complicated because fetchFirstBatch() may end up calling fetchNextBatch() and the KeepStackGCProcessedMark is not reentrant.

**Comment by rkennke** [comment]
I tested the original patch in Loom with tests that use stack-walking and it failed because we'd need another KeepStackGCProcessedMark in fetchFirstBatch() too. Unfortunately, fetchFirstBatch() can wind up calling fetchNextBatch() recursively, but we *also* can call fetchNextBatch() without calling fetchFirstBatch() on outer frame, thus we need KeepStackGCProcessedMark to be reentrant. I achieved this by linking together nested linked watermark. I am not sure this is the right way to achieve it. It fixes all tests in Loom *and* mainline JDK though.

**Comment by fisk** [comment]
I think this solution is wrong, regarding nesting. There is only a single node but it looks like you think there are multiple. The result is seemingly that the unlink function won't unlink anything, which permanently disables incremental stack scanning on that thread.
Is there any way the mark can be placed closer to the problematic allocation so we don't need nesting?

**Review by fisk — CHANGES_REQUESTED** [review]
Nesting code looks wrong.

**Comment by stefank** [comment]
I incorrectly read Erik's comment as "Nesting code looks **good**", so I created a unit test to show the problem with the patch:
https://github.com/stefank/jdk/commit/8760f1b0409b3cccf76a8ea417b90e66da31af72

Maybe you could build a few more test based on this?

**Comment by rkennke** [comment]
> I think this solution is wrong, regarding nesting. There is only a single node but it looks like you think there are multiple. The result is seemingly that the unlink function won't unlink anything, which permanently disables incremental stack scanning on that thread.
> Is there any way the mark can be placed closer to the problematic allocation so we don't need nesting?

I just realized that the reentrancy comes from the Java call lower in fetchFirstBatch(). The problem can be easily avoided by putting the KeepStackGCProcessedMark in sensible scope that excludes the call.

**Review by stefank — APPROVED** [review]
Looks good.

**Comment by rkennke** [comment]
> Looks good.

Thanks, Stefan!

@fisk also good?

**Review by fisk — APPROVED** [review]
Also good!

**Pull request closed without merging**
