### PR TITLE
8340687: Open source closed frame tests #1

### PR DESCRIPTION
**Pull request by azvegint**
few more tests to open source

Testing looks good

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340687](https://bugs.openjdk.org/browse/JDK-8340687): Open source closed frame tests #1 (**Bug** - P4)

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21180/head:pull/21180` \
`$ git checkout pull/21180`

Update a local copy of the PR: \
`$ git checkout pull/21180` \
`$ git pull https://git.openjdk.org/jdk.git pull/21180/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21180`

View PR using the GUI difftool: \
`$ git pr show -t 21180`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21180.diff">https://git.openjdk.org/jdk/pull/21180.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21180#issuecomment-2373750560)

### CODE REVIEW

**Comment by aivanov-jdk** [comment]
GitHub doesn't like `#1` in the subject of the JBS issue — it links it to the first PR in the JDK project.

**Comment by azvegint** [comment]
> GitHub doesn't like `#1` in the subject of the JBS issue — it links it to the first PR in the JDK project.

I know, but it's just visual, the PR can be integrated without any issue

**Comment by aivanov-jdk** [comment]
> > GitHub doesn't like `#1` in the subject of the JBS issue — it links it to the first PR in the JDK project.
> 
> I know, but it's just visual, the PR can be integrated without any issue

But it looks frightening and confusing, especially with the red marker.

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
