### PR TITLE
8256392: C2: Various Node cleanups

### PR DESCRIPTION
**Pull request by cl4es**
- Unused methods:
 Node::walk, walk_, nop, lookup, rpop
 Node_Array::reset, sort
- Disallowing 0 as values to OptoNodeListSize and OptoBlockListSize can simplify some logic: e.g., Node_Array::_max > 0 becomes an invariant (with reset unused and removed)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ⏳ (9/9 running) | ⏳ (9/9 running) | ⏳ (9/9 running) |

### Issue
 * [JDK-8256392](https://bugs.openjdk.java.net/browse/JDK-8256392): C2: Various Node cleanups

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1223/head:pull/1223`
`$ git checkout pull/1223`

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good!

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Review by neliasso — APPROVED** [review]
Looks good.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by cl4es** [comment]
@neliasso @TobiHartmann @iwanowww - thank you for reviewing! Just waiting for the PPC build to turn green

**Pull request closed without merging**
