### PR TITLE
8297912: HotSpot Style Guide should permit alignas (Second Proposal Attempt)

### PR DESCRIPTION
**Pull request by TheShermanTanker**
[8252584](https://bugs.openjdk.org/browse/JDK-8252584) was integrated too early due to a mistake on my part, we should redo it and go through the proper approval process this time

(The changes in this commit are exactly identical to 8252584)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297912](https://bugs.openjdk.org/browse/JDK-8297912): HotSpot Style Guide should permit alignas (Second Proposal Attempt)

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [2fb10863](https://git.openjdk.org/jdk/pull/11446/files/2fb108633431735ecf7f449856b3b319597a450c)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [792b96a2](https://git.openjdk.org/jdk/pull/11446/files/792b96a2b35820d165290da3cfeb8b72515452a6)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11446/head:pull/11446` \
`$ git checkout pull/11446`

Update a local copy of the PR: \
`$ git checkout pull/11446` \
`$ git pull https://git.openjdk.org/jdk pull/11446/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11446`

View PR using the GUI difftool: \
`$ git pr show -t 11446`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11446.diff">https://git.openjdk.org/jdk/pull/11446.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Hi Julian, 

could you give this PR/JBS please a speaking name, e.g. "HotSpot Style Guide should permit alignas
 (second attempt)". Nobody remembers all JBS issue numbers :)

Also, @rose00 voiced concerns in the original PR (https://github.com/openjdk/jdk/pull/11315#issuecomment-1332982465) which should be addressed first. I cautiously share his concerns for the moment.

Cheers, Thomas

**Comment by kimbarrett** [comment]
> could you give this PR/JBS please a speaking name, e.g. "HotSpot Style Guide should permit alignas (second attempt)". Nobody remembers all JBS issue numbers :)

+1

> Also, @rose00 voiced concerns in the original PR ([#11315 (comment)](https://github.com/openjdk/jdk/pull/11315#issuecomment-1332982465)) which should be addressed first. I cautiously share his concerns for the moment.

I had somewhat similar concerns to @rose00 at one point. We have
`ATTRIBUTE_ALIGNED` for this sort of thing; is `alignas` actually better? I
think it is, though perhaps weakly. It's a bit shorter and less noisy (which
some might not consider a positive). It is in most respects equivalent to our
macro, and will work for other compilers (I think there are some) without
needing to specialize the macro.

The proposal seems like a lot of words, describing significant restrictions.
The thing is, very nearly all of those words apply to our `ATTRIBUTE_ALIGNED`
macro too, but aren't written down anywhere.

So I approve of this change, though I won't be heartbroken if it is rejected.
If it's rejected, I'll mine it for documentation comments for our macro.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by TheShermanTanker** [comment]
> Also, @rose00 voiced concerns in the original PR ([#11315 (comment)](https://github.com/openjdk/jdk/pull/11315#issuecomment-1332982465)) which should be addressed first. I cautiously share his concerns for the moment.

I actually missed John's concerns, but it seems like @kimbarrett has already beaten me to it in remarking that there's almost no difference (if at all) between `alignas` and the different syntax `ATTRIBUTE_ALIGNED` expands to, except for the former being a little stricter in certain cases (but this is not always a bad thing). For what it's worth though, Visual C++ does explicitly mention that both the __declspec and `alignas` are identical, and [strongly encourages using the C++ keyword instead](https://learn.microsoft.com/en-us/cpp/cpp/alignment-cpp-declarations?view=msvc-170)

I feel like this is one of those instances where there isn't much that would make one lean more towards either rejecting or accepting the change, but `alignas` is somewhat better defined than the compiler extensions, which is (at least to me) a small win

**Comment by vnkozlov** [comment]
I would vote for using C++ feature which provides similar functionality just to avoid supporting our own implementation.
To have our own implementation was justified before as John R. commented.
That is assuming **ALL** C++ compilers we use today to compile HotSpot code do exactly the same thing.
So before approving this change we need to make sure we (Oracle and OpenJDK community) test #11431 on all our platforms.

**Comment by kimbarrett** [comment]
The MSVC implementation of `ATTRIBUTE_ALIGNED` using `__declspec(align(N))` has the same
limitation of needing the alignment value, and not being usable for types.

I happened to run into both the limitation to alignment values problem and
the lack of an XLC definition for ATTRIBUTE_ALIGNED today.

**Review by tstuefe — APPROVED** [review]
Okay, I'm convinced.

**Comment by TheShermanTanker** [comment]
Don't mind me, just making it look a little better

**Comment by TheShermanTanker** [comment]
I'll leave integration of this up to someone else, for convenience

**Review by vnkozlov — APPROVED** [review]
Per process I approve these changes.

**Comment by TheShermanTanker** [comment]
@kimbarrett Now that alignas has officially been approved, is there anything I need to do with https://github.com/openjdk/jdk/pull/11431? I'm not sure if there's anything else needed on my part for that issue

**Comment by TheShermanTanker** [comment]
@kimbarrett Now that alignas has officially been approved, is there anything I need to do with [8250269: Replace ATTRIBUTE_ALIGNED with alignas](https://github.com/openjdk/jdk/pull/11431)? I'm not sure if there's anything else needed on my part for that issue

**Pull request closed without merging**
