### PR TITLE
8288078: linux-aarch64-optimized build fails in Tier5 after JDK-8287567

### PR DESCRIPTION
**Pull request by theRealAph**
Because neither ASSERT nor PRODUCT are defined in 'optimized' builds , this needs to be surrounded by ASSERT ifdefs, not PRODUCT.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288078](https://bugs.openjdk.org/browse/JDK-8288078): linux-aarch64-optimized build fails in Tier5 after JDK-8287567

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9103/head:pull/9103` \
`$ git checkout pull/9103`

Update a local copy of the PR: \
`$ git checkout pull/9103` \
`$ git pull https://git.openjdk.java.net/jdk pull/9103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9103`

View PR using the GUI difftool: \
`$ git pr show -t 9103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9103.diff">https://git.openjdk.java.net/jdk/pull/9103.diff</a>

</details>

### CODE REVIEW

**Comment by adinn** [comment]
@theRealAph 

> Because PRODUCT is defined in 'optimized' builds, this needs to be surrounded by ASSERT ifdefs, not PRODUCT.

I am not sure that comment is correct even though I agree the fix is right. I'll provide my explanation just to be sure I have understood the fix. The error is happening because:

1. `PRODUCT` is *not* defined in 'optimized' builds
2. `assert` is defined as an empty macro in 'optimized' builds

This means that when doing an 'optimized' build the declaration of `is_movk_to_zr` is included but the uses of it inside the call to `assert` gets elided.

The fix works because:

1. ASSERT is not defined in 'optimized' builds
2. `assert` is defined as an empty macro in 'optimized' builds
3. A fortiori the call to `assert` is not compiled in anyway.

So, with the patch the net result is that both the declaration of  `is_movk_to_zr` and its use are omitted in 'optimized' builds.

I'm approving the patch on that basis. can you confirm I have understood it correctly?

**Review by adinn — APPROVED** [review]
Patch looks good.

**Comment by theRealAph** [comment]
> @theRealAph
> 
> > Because PRODUCT is defined in 'optimized' builds, this needs to be surrounded by ASSERT ifdefs, not PRODUCT.
> 
> I am not sure that comment is correct even though I agree the fix is right. I'll provide my explanation just to be sure I have understood the fix. The error is happening because:
>     1. `PRODUCT` is _not_ defined in 'optimized' builds
> 
>     2. `assert` is defined as an empty macro in 'optimized' builds

Exactly, thanks. I changed my summary text to fit.

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable. Would be nice to get this in before the fork later today.

**Comment by theRealAph** [comment]
> Looks reasonable. Would be nice to get this in before the fork later today.

I know, but tests are still running. It looks safe to me.

**Pull request closed without merging**
