### PR TITLE
8206447: InflaterInputStream.skip receives long but it's limited to Integer.MAX_VALUE

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which updates the API specification of `java.util.zip.InflaterInputStream.skip()` method to match its current implementation?

`InflaterInputStream.skip()`, just like `DeflaterInputStream.skip()`, takes a `long` value `n` representing the number of bytes to skip. When a value greater than `Integer.MAX_VALUE` is passed to this `InflaterInputStream.skip()` method, the current implementation in that method only skips at most `Integer.MAX_VALUE` bytes. `DeflaterInputStream.skip()` too has the same behaviour. However, in the case of `DeflaterInputStream.skip()`, this semantic is clearly noted in that method's API documentation. `InflaterInputStream.skip()` currently doesn't specify this behaviour.

The commit in this PR updates the `InflaterInputStream.skip()` to specify the current implementation.

I'll open a CSR for this change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8333400](https://bugs.openjdk.org/browse/JDK-8333400) to be approved

### Issues
 * [JDK-8206447](https://bugs.openjdk.org/browse/JDK-8206447): InflaterInputStream.skip receives long but it's limited to Integer.MAX_VALUE (**Enhancement** - P4)
 * [JDK-8333400](https://bugs.openjdk.org/browse/JDK-8333400): InflaterInputStream.skip receives long but it's limited to Integer.MAX_VALUE (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19515/head:pull/19515` \
`$ git checkout pull/19515`

Update a local copy of the PR: \
`$ git checkout pull/19515` \
`$ git pull https://git.openjdk.org/jdk.git pull/19515/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19515`

View PR using the GUI difftool: \
`$ git pr show -t 19515`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19515.diff">https://git.openjdk.org/jdk/pull/19515.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19515#issuecomment-2144294234)

### CODE REVIEW

**Comment by jaikiran** [comment]
The CSR is available for review at https://bugs.openjdk.org/browse/JDK-8333400

**Review by LanceAndersen — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]
This went through a few iterations in the CSR issue, looking good now.

**Review by LanceAndersen — APPROVED** [review]
latest update looks good.  Thank you and Alan for the additional wordsmithing

**Comment by jaikiran** [comment]
Thank you all for the reviews and the inputs to the specification text. The CSR has been approved, so I'll integrate this now.

**Pull request closed without merging**
