### PR TITLE
8266232: compiler.c1.TestRangeCheckEliminated should be run in driver mode

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review this small patch that changes `compiler.c1.TestRangeCheckEliminated` to be run in driver mode (as the actual testing is done in the JVMs spawned by it, `TestRangeCheckEliminated` just verifies their output)? the patch also makes a few small code style changes.

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266232](https://bugs.openjdk.java.net/browse/JDK-8266232): compiler.c1.TestRangeCheckEliminated should be run in driver mode

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3772/head:pull/3772` \
`$ git checkout pull/3772`

Update a local copy of the PR: \
`$ git checkout pull/3772` \
`$ git pull https://git.openjdk.java.net/jdk pull/3772/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3772`

View PR using the GUI difftool: \
`$ git pr show -t 3772`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3772.diff">https://git.openjdk.java.net/jdk/pull/3772.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Add Oracle copyright line.

What about `@requires vm.flagless` ?

**Comment by iignatev** [comment]
> Add Oracle copyright line.

sure, I can do that. but I personally don't see this patch as significant enough to add Oracle's copyright.

> What about `@requires vm.flagless` ?

I want to keep adding `vm.flagless` change as self-contained as possible for ease of review and ease of backporting. but yes, I'll add `@requires vm.flagless` to this test as well.

-- Igor

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by iignatev** [comment]
thanks, Vladimir.

/integrate

**Pull request closed without merging**
