### PR TITLE
8287398: Allow concurrent execution of hotspot docker tests

### PR DESCRIPTION
**Pull request by iklam**
Remove the `exclusiveAccess.dirs=.` configuration (and thus the entire TEST.properties file) so that the  test/hotspot/jtreg/containers/docker/*.java tests can be executed concurrently. This reduces total execution from about 8 minuets to about 2.5 minuets on my machine.

In early days of JDK support for docker, we disabled concurrent execution as a precaution to avoid collisions in docker operations, such as building an image. Such collisions should no longer happen (each image is uniquely named).

In comparison, in tests/jdk/jdk/internal/platform/docker there are no such limitations, and the 6 docker tests there can be executed in parallel without issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287398](https://bugs.openjdk.java.net/browse/JDK-8287398): Allow concurrent execution of hotspot docker tests

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Mikhailo Seledtsov](https://openjdk.java.net/census#mseledtsov) (@mseledts - Committer)
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8914/head:pull/8914` \
`$ git checkout pull/8914`

Update a local copy of the PR: \
`$ git checkout pull/8914` \
`$ git pull https://git.openjdk.java.net/jdk pull/8914/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8914`

View PR using the GUI difftool: \
`$ git pr show -t 8914`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8914.diff">https://git.openjdk.java.net/jdk/pull/8914.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
Unfortunately, collisions still happen, see the uses of `Common.imageName`. I see at least two conflicts:
 - `TestMemoryAwareness` and `TestMemoryWithCgroupV1`
 - `TestPids` and `TestPidsLimit`

The first pair of tests nearly reliably fails on sufficiently large desktop after this patch. Please take a large machine and maybe test with `make test TEST=containers/docker JTREG="REPEAT_COUNT=50"`?

**Comment by iklam** [comment]
> Unfortunately, collisions still happen, see the uses of `Common.imageName`. I see at least two conflicts:
> 
> * `TestMemoryAwareness` and `TestMemoryWithCgroupV1`
> * `TestPids` and `TestPidsLimit`
> 
> The first pair of tests nearly reliably fails on sufficiently large desktop after this patch. Please take a large machine and maybe test with `make test TEST=containers/docker JTREG="REPEAT_COUNT=50"`?

I updated `Common.imageName()` to generate a unique name using the `"test.name"` system property. The `suffix` parameter isn't necessary anymore, but I left it there to avoid modifying all the test cases.

**Review by mseledts — APPROVED** [review]
Looks good to me, thanks.

**Review by shipilev — APPROVED** [review]
Okay, as long as multiple iterations of these tests pass.

**Review by jerboaa — APPROVED** [review]
Seems fine.

**Comment by iklam** [comment]
> Okay, as long as multiple iterations of these tests pass.

I tested with `make test TEST=containers/docker JTREG="REPEAT_COUNT=50"` on a machine with 32 threads and it passed after 157 minuets.

**Comment by iklam** [comment]
Thanks @mseledts @shipilev @jerboaa for the review.
/integrate

**Pull request closed without merging**
