### PR TITLE
8304174: Remove delays from httpserver tests

### PR DESCRIPTION
**Pull request by djelinski**
This change improves the running time of many httpserver tests; it removes the one second delay introduced by `delay()` calls, and performs immediate httpserver stop by calling `stop(0)`.

For example, `com/sun/net/httpserver/Test1.java` usually takes 20-30 seconds without this change; with this change it completes in 5-8 seconds.

Tiers 1-3 still green.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304174](https://bugs.openjdk.org/browse/JDK-8304174): Remove delays from httpserver tests

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/13028/head:pull/13028` \
`$ git checkout pull/13028`

Update a local copy of the PR: \
`$ git checkout pull/13028` \
`$ git pull https://git.openjdk.org/jdk pull/13028/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13028`

View PR using the GUI difftool: \
`$ git pr show -t 13028`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13028.diff">https://git.openjdk.org/jdk/pull/13028.diff</a>

</details>

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Daniel, the changes look good to me. Like you note, I don't see any of these tests relying on the delay of server `stop()` for their tests. It's a bit surprising that a lot of these tests were using those delays, but I guess that's because one test influencing the code in another test.

**Comment by jaikiran** [comment]
> For example, com/sun/net/httpserver/Test1.java usually takes 20-30 seconds without this change; with this change it completes in 5-8 seconds.

**Comment by msheppar** [comment]
From my observations, typically these delays have been used to provide a level of synchronicity between the main thread and various background processing threads. Thus, allowing background processing to conclude prior to the actual shutdown in the server. For example, if you analyse the HttpServerTest, there exists some potential for race conditions to occur. An influencing factor, in all this, is the load on the test system and the number of threads executing. With these changes there may be some intermittent failures -- so one to watch !!

**Comment by djelinski** [comment]
Thanks for your comments!
In most of the tests, all requests are done when we stop the server.
I checked the `HttpServerTest`; moved `serverStopped.await();` before `is.readAllBytes();` to make sure the wrong side wins the race. The test still passed.
If the tests start failing, we will fix the races using the proper synchronization objects like `CountDownLatch`. For now, after 50 reps of `com/sun/net/httpserver` tests I have zero failures.

I plan to revisit `HttpServer::stop` in [JDK-8304065](https://bugs.openjdk.org/browse/JDK-8304065). However, even when implemented correctly, `stop(1)` will be slightly slower than `stop(0)`.

**Comment by djelinski** [comment]
50 repeats of tests using SimpleHttpServer also passed. Removing the delays appears to have no effect on test stability.

**Review by dfuch — APPROVED** [review]

**Pull request closed without merging**
