### PR TITLE
8291799: IGV: make "Selection mode" a toggle button

### PR DESCRIPTION
**Pull request by tobiasholenstein**
In IGV, an open graph has two modes for interaction:
`Panning mode` where the user can move the graph with the mouse.
Old Panning Mode

`Selection mode` where the user can draw a selection rectangle with the mouse to select multiple nodes. This mode can also be accessed by holding down the `CMD/Ctrl` key on the keyboard.
Old Selection Mode

We remove the `Panning Mode` button (and the action `PanModeAction.java`) and make the `Select Mode` button (triggers `SelectionModeAction.java`) a toggle button:
When it is selected, the user is in `Selection Mode`
New Selection Mode

Otherwise the user is in `Panning Mode` (default)
New Panning Mode

This image shows a user that is selecting multiple nodes using the `Panning Mode` toggle button:
selecting

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291799](https://bugs.openjdk.org/browse/JDK-8291799): IGV: make "Selection mode" a toggle button

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9725/head:pull/9725` \
`$ git checkout pull/9725`

Update a local copy of the PR: \
`$ git checkout pull/9725` \
`$ git pull https://git.openjdk.org/jdk pull/9725/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9725`

View PR using the GUI difftool: \
`$ git pr show -t 9725`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9725.diff">https://git.openjdk.org/jdk/pull/9725.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too!

**Review by robcasloz — APPROVED** [review]
Looks good!

**Comment by tobiasholenstein** [comment]
Thanks @vnkozlov, @robcasloz and @TobiHartmann for the reviews!

**Pull request closed without merging**
