### PR TITLE
8277310: ciReplay: @cpi MethodHandle references not resolved

### PR DESCRIPTION
**Pull request by dean-long**
It turns out replay was resolving constant pool entries for "@bci <bsm>" references, but not for "@cpi" references.  These changes fix that.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277310](https://bugs.openjdk.java.net/browse/JDK-8277310): ciReplay: @cpi MethodHandle references not resolved

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6423/head:pull/6423` \
`$ git checkout pull/6423`

Update a local copy of the PR: \
`$ git checkout pull/6423` \
`$ git pull https://git.openjdk.java.net/jdk pull/6423/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6423`

View PR using the GUI difftool: \
`$ git pr show -t 6423`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6423.diff">https://git.openjdk.java.net/jdk/pull/6423.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by dean-long** [comment]
Thanks, Christian and Tobias.

**Pull request closed without merging**
