### PR TITLE
8311631: When multiple users run tools/jpackage/share/LicenseTest.java, Permission denied for writing /var/tmp/*.files

### PR DESCRIPTION
**Pull request by yaqsun**
The prerequisite is to install the rpmbuild command, when multiple users switch to write /var/tmp/*.files will have the permission forbidden.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311631](https://bugs.openjdk.org/browse/JDK-8311631): When multiple users run tools/jpackage/share/LicenseTest.java, Permission denied for writing /var/tmp/*.files (**Bug** - P4)

### Reviewers
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)
 * [Alexander Matveev](https://openjdk.org/census#almatvee) (@sashamatveev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14802/head:pull/14802` \
`$ git checkout pull/14802`

Update a local copy of the PR: \
`$ git checkout pull/14802` \
`$ git pull https://git.openjdk.org/jdk.git pull/14802/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14802`

View PR using the GUI difftool: \
`$ git pr show -t 14802`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14802.diff">https://git.openjdk.org/jdk/pull/14802.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14802#issuecomment-1627056134)

### CODE REVIEW

**Comment by alexeysemenyukoracle** [comment]
The change affects jpackage rpm spec template file. It is misleading to state that this change is `Low risk, only test changes.`

**Review by alexeysemenyukoracle — CHANGES_REQUESTED** [review]
How about `%{buildroot}`? Shouldn't it be user-specific as well?

**Comment by yaqsun** [comment]
> The change affects jpackage rpm spec template file. It is misleading to state that this change is `Low risk, only test changes.`

My mistake, I will modify the initial comment.

**Comment by alexeysemenyukoracle** [comment]
I believe the problem is the use of `%{_tmppath}` for the root of intermediate files. Should be changed to `%{_builddir}` or some other user-specific directory

**Comment by yaqsun** [comment]
How about JTwork(if achievable)? Files created in JTwork do not need to be cleaned when the "rpmbuild" command completes.

**Comment by alexeysemenyukoracle** [comment]
The fix with `%{_builddir}` looks better. Did it resolve the issue?

**Comment by yaqsun** [comment]
> The fix with `%{_builddir}` looks better. Did it resolve the issue?

Yes, it solved. The root of intermediate files changed to /tmp/jdk.jpackage16701381473798822/BUILD/commonlicensetest.filesystem.files.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Review by sashamatveev — APPROVED** [review]

**Comment by theaoqi** [comment]
@alexeysemenyukoracle , could you help to sponsor this? Thanks!

**Comment by theaoqi** [comment]
@yaqsun , I suggest you enable GHA and trigger a run, before this patch is merged.

**Pull request closed without merging**
