### PR TITLE
8219586: CodeHeap State Analytics processes dead nmethods

### PR DESCRIPTION
**Pull request by RealLucy**
This change was already fully reviewed before the transition Mercurial to Git happened.
Reviewed-by: thartmann (TobiHartmann), eosterlund (Git name unknown)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8219586](https://bugs.openjdk.java.net/browse/JDK-8219586): CodeHeap State Analytics processes dead nmethods

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/325/head:pull/325`
`$ git checkout pull/325`

### CODE REVIEW

**Comment by stefank** [comment]
CC @fisk

**Review by TobiHartmann — APPROVED** [review]
Still looks good.

**Review by fisk — APPROVED** [review]
Looks good.

**Comment by RealLucy** [comment]
Thank you, Tobias and Erik, for re-checking this fix.

**Pull request closed without merging**
