### PR TITLE
8314837: 5 compiled/codecache tests ignore VM flags

### PR DESCRIPTION
**Pull request by yftsai**
3 codecache/cli tests are marked with `@requires vm.flagless` as they ignore VM flags. These tests enumerate combinations of flags, and some (e.g. `-Xint`) are incompatible with flags of compiler modes.

External VM flags are passed to the created processes in CodeCacheFullCountTest and CheckCodeCacheInfo. The former creates the process with code cache flushing disabled, and is compatible with flags except the interpreter mode. The later creates a process to print verbose code cache info, and the feature is independent of other flags.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314837](https://bugs.openjdk.org/browse/JDK-8314837): 5 compiled/codecache tests ignore VM flags (**Sub-task** - P5)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [ab642336](https://git.openjdk.org/jdk/pull/15485/files/ab642336f8e5d22fd1f61d312fbb000fc3d5a341)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15485/head:pull/15485` \
`$ git checkout pull/15485`

Update a local copy of the PR: \
`$ git checkout pull/15485` \
`$ git pull https://git.openjdk.org/jdk.git pull/15485/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15485`

View PR using the GUI difftool: \
`$ git pr show -t 15485`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15485.diff">https://git.openjdk.org/jdk/pull/15485.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15485#issuecomment-1698858367)

### CODE REVIEW

**Comment by vnkozlov** [comment]
I think your description is not accurate. I sounds like this change will prevent passing external test flags into tests.
But synopsis of this RFE correctly says `tests ignore VM flags`. And main RFE [8314823](https://bugs.openjdk.org/browse/JDK-8314823) has even more explicit synopsis `Update or mark as vm.flagless tests which ignores external VM flags`.

So adding `@requires vm.flagless` simply marks tests which ignore external flags and don't run them in configurations with external flags specified.

I suggest to add comment to CheckCodeCacheInfo.java before `ProcessTools.createTestJvm()` call to say that:
```
ProcessTools.createTestJvm - creates a ProcessBuilder to run java with all the test framework arguments applied. 
```
this text is from David H. comment in 8314823.

**Comment by yftsai** [comment]
I marked CheckCodeCacheInfo with `vm.flagless`. The tested feature doesn't depend on other flags. The flag 'UnlockDiagnosticVMOptions' is also removed.

**Comment by vnkozlov** [comment]
> I marked CheckCodeCacheInfo with `vm.flagless`. The tested feature doesn't depend on other flags. The irrelevant flag `UnlockDiagnosticVMOptions` is also removed.

Okay, this will do.

**Review by vnkozlov — APPROVED** [review]
Good. You need second review.

**Comment by vnkozlov** [comment]
@lmesnik, please look.

**Comment by lmesnik** [comment]
@yftsai The preferred fix is to use 'ProcessTools.createTestJvm ' to fork JVM with tested flags for most of tests 
It helps to ensure that corresponding functionality works for different modes like C2/C1 only, JMCI compiler and other modes. I think it would be better just to use it for
test/hotspot/jtreg/compiler/codecache/CheckCodeCacheInfo.java
test/hotspot/jtreg/compiler/codecache/CodeCacheFullCountTest.java. 

The vm.flagless is usually used for tests which are incompatible with any or most of external flags. It is fine to use it for cli tests.

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
