### PR TITLE
8326983: Unused operands reported after JDK-8326135

### PR DESCRIPTION
**Pull request by kuaiwei**
Remove all unused operands reported by adlc. I'm testing x86_64 and aarch64. So far no failure found in tier1.
I tried to clean unused operands for all platform. A special case is immLRot2 in arm, it's not used, but appeared in many todo comments. So I keep it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326983](https://bugs.openjdk.org/browse/JDK-8326983): Unused operands reported after JDK-8326135 (**Bug** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18075/head:pull/18075` \
`$ git checkout pull/18075`

Update a local copy of the PR: \
`$ git checkout pull/18075` \
`$ git pull https://git.openjdk.org/jdk.git pull/18075/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18075`

View PR using the GUI difftool: \
`$ git pr show -t 18075`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18075.diff">https://git.openjdk.org/jdk/pull/18075.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18075#issuecomment-1972557234)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
For aarch64 do we need also change *.m4 files?
Anything in aarch64_vector* files?

I will run our testing with current patch.

**Comment by vnkozlov** [comment]
My testing shows that when we do **cross compilation** on linux-x64 I got:
```
Warning: unused operand (no_rax_RegP)
```
Normal linux-x64 build passed.

The operand is used only in one place in ZGC barriers code: `src/hotspot/cpu/x86/gc/z/z_x86_64.ad`
May be it is not include during cross compilation.

**Comment by vnkozlov** [comment]
I am testing the move `operand no_rax_RegP` into `z_x86_64.ad`.

**Comment by vnkozlov** [comment]
FTR, I also bailout from adlc parser when we have unused operand to force build failure:
```
+++ b/src/hotspot/share/adlc/archDesc.cpp
@@ -773,8 +774,11 @@ bool ArchDesc::check_usage() {
       cnt++;
     }
   }
-  if (cnt) fprintf(stderr, "\n-------Warning: total %d unused operands\n", cnt);
-
+  if (cnt) {
+    fprintf(stderr, "\n-------Warning: total %d unused operands\n", cnt);
+    _semantic_errs++;
+    return false;
+  }
   return true;
 }

```
I don't think we need it in these changes but it helped me to catch the missing case.

**Comment by vnkozlov** [comment]
Testing build with moved `operand no_rax_RegP` passed. Please update changes with this:
```
diff --git a/src/hotspot/cpu/x86/x86_64.ad b/src/hotspot/cpu/x86/x86_64.ad
index d43929efd3e..aef3453b0b1 100644
--- a/src/hotspot/cpu/x86/x86_64.ad
+++ b/src/hotspot/cpu/x86/x86_64.ad
@@ -2663,18 +2561,6 @@ operand rRegN() %{
 // the RBP is used as a proper frame pointer and is not included in ptr_reg. As a
 // result, RBP is not included in the output of the instruction either.
 
-operand no_rax_RegP()
-%{
-  constraint(ALLOC_IN_RC(ptr_no_rax_reg));
-  match(RegP);
-  match(rbx_RegP);
-  match(rsi_RegP);
-  match(rdi_RegP);
-
-  format %{ %}
-  interface(REG_INTER);
-%}
-
 // This operand is not allowed to use RBP even if
 // RBP is not used to hold the frame pointer.
 operand no_rbp_RegP()
diff --git a/src/hotspot/cpu/x86/gc/z/z_x86_64.ad b/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
index d178805dfc7..fc8d3d15d5a 100644
--- a/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
+++ b/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
@@ -99,6 +99,23 @@ static void z_store_barrier(MacroAssembler& _masm, const MachNode* node, Address
 
 %}
 
+register %{
+
+operand no_rax_RegP()
+%{
+  constraint(ALLOC_IN_RC(ptr_no_rax_reg));
+  match(RegP);
+  match(rbx_RegP);
+  match(rsi_RegP);
+  match(rdi_RegP);
+
+  format %{ %}
+  interface(REG_INTER);
+%}
+
+%}
+
+
 // Load Pointer
 instruct zLoadP(rRegP dst, memory mem, rFlagsReg cr)
 %{
```

**Review by RealFYang — COMMENTED** [review]
The RISC-V part of the change looks fine. Note that GHA failure is infrastructual. Debian sid is broken for now: https://bugs.openjdk.org/browse/JDK-8326960

**Comment by kuaiwei** [comment]
> For aarch64 do we need also change _.m4 files? Anything in aarch64_vector_ files?
> 
> I will run our testing with current patch.

I'm not clear about m4 file. How do we use it?
The build script of jdk will combine all ad file into one single file and adlc will compile it. So aarch64_vector.ad will be checked as well.

**Comment by kuaiwei** [comment]
> My testing shows that when we do **cross compilation** on linux-x64 I got:
> 
> ```
> Warning: unused operand (no_rax_RegP)
> ```
> 
> Normal linux-x64 build passed.
> 
> The operand is used only in one place in ZGC barriers code: `src/hotspot/cpu/x86/gc/z/z_x86_64.ad` May be it is not include during cross compilation.

Does the cross compilation disable zgc feature? In my test, it's used by zgc and no warning about it.

**Comment by kuaiwei** [comment]
> Testing build with moved `operand no_rax_RegP` passed. Please update changes with this:
> 
> ```
> diff --git a/src/hotspot/cpu/x86/x86_64.ad b/src/hotspot/cpu/x86/x86_64.ad
> index d43929efd3e..aef3453b0b1 100644
> --- a/src/hotspot/cpu/x86/x86_64.ad
> +++ b/src/hotspot/cpu/x86/x86_64.ad
> @@ -2663,18 +2561,6 @@ operand rRegN() %{
>  // the RBP is used as a proper frame pointer and is not included in ptr_reg. As a
>  // result, RBP is not included in the output of the instruction either.
>  
> -operand no_rax_RegP()
> -%{
> -  constraint(ALLOC_IN_RC(ptr_no_rax_reg));
> -  match(RegP);
> -  match(rbx_RegP);
> -  match(rsi_RegP);
> -  match(rdi_RegP);
> -
> -  format %{ %}
> -  interface(REG_INTER);
> -%}
> -
>  // This operand is not allowed to use RBP even if
>  // RBP is not used to hold the frame pointer.
>  operand no_rbp_RegP()
> diff --git a/src/hotspot/cpu/x86/gc/z/z_x86_64.ad b/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
> index d178805dfc7..0cc2ea03b35 100644
> --- a/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
> +++ b/src/hotspot/cpu/x86/gc/z/z_x86_64.ad
> @@ -99,6 +99,18 @@ static void z_store_barrier(MacroAssembler& _masm, const MachNode* node, Address
>  
>  %}
>  
> +operand no_rax_RegP()
> +%{
> +  constraint(ALLOC_IN_RC(ptr_no_rax_reg));
> +  match(RegP);
> +  match(rbx_RegP);
> +  match(rsi_RegP);
> +  match(rdi_RegP);
> +
> +  format %{ %}
> +  interface(REG_INTER);
> +%}
> +
>  // Load Pointer
>  instruct zLoadP(rRegP dst, memory mem, rFlagsReg cr)
>  %{
> ```

updated.

**Comment by vnkozlov** [comment]
What are latest changes (commented `operand immLRot2()`) in `arm_32.ad` for?

**Comment by vnkozlov** [comment]
>> The operand is used only in one place in ZGC barriers code: src/hotspot/cpu/x86/gc/z/z_x86_64.ad May be it is not include during cross compilation.
> Does the cross compilation disable zgc feature? In my test, it's used by zgc and no warning about it.

I am not sure what happened there in our testing and did not have time to investigate. The patch worked and it was enough for me.

**Comment by vnkozlov** [comment]
@dholmes-ora asked to disable warning by default and I agree.

We can use `AD._disable_warnings` flag to guard these warnings and add corresponding `-w` flag to `adlc` command in `GensrcAdlc.gmk`

**Comment by vnkozlov** [comment]
> I'm not clear about m4 file. How do we use it?
> The build script of jdk will combine all ad file into one single file and adlc will compile it. So aarch64_vector.ad will be checked as well.

Aarch64 m4 files are used to manually update .ad files. My concern was that could be overlapped code in m4 files which may overwrite your changes in .ad when someone do such manual update in a future. 
Fortunately `aarch64_ad.m4` does not have operand definitions so your changes are fine.
But `aarch64_vector_ad.m4` has them so if  we need to change `aarch64_vector.ad` we need to modify m4 file too.

**Comment by dholmes-ora** [comment]
> @dholmes-ora asked to disable warning by default and I agree.

What I said was that until all the known issues are resolved then the warning should be disabled. If this PR fixes every warning that has been spotted then that is fine - the warning can remain on the detect new problems creeping in. Otherwise issues should be filed to fix all remaining warnings and the warning disabled until they are all addressed. We have been lucky that these unexpected warnings have only caused minimal disruption to our builds.

**Comment by kuaiwei** [comment]
> 



> What are latest changes (commented `operand immLRot2()`) in `arm_32.ad` for?

I want to comment out immLRot2. It's mentioned in many todo comments. So I want to keep it without warning. I uses a wrong comment syntax. It's fixed in next patch.

**Comment by kuaiwei** [comment]
> > I'm not clear about m4 file. How do we use it?
> > The build script of jdk will combine all ad file into one single file and adlc will compile it. So aarch64_vector.ad will be checked as well.
> 
> Aarch64 m4 files are used to manually update .ad files. My concern was that could be overlapped code in m4 files which may overwrite your changes in .ad when someone do such manual update in a future. Fortunately `aarch64_ad.m4` does not have operand definitions so your changes are fine. But `aarch64_vector_ad.m4` has them so if we need to change `aarch64_vector.ad` we need to modify m4 file too.

I checked all 44 removed operands in aarch64 and find none of them in m4 file. I just grep them and only "indOffI" and "indOffL" appeared because of "vmemA_indOffI4" and "vmemA_indOffL4" . So we need not change m4 file.

**Comment by kuaiwei** [comment]
> @dholmes-ora asked to disable warning by default and I agree.
> 
> We can use `AD._disable_warnings` flag to guard these warnings and add corresponding `-w` flag to `adlc` command in `GensrcAdlc.gmk`

I added check of _disable_warnings in adlc. But not enable it in build script.

**Review by vnkozlov — APPROVED** [review]
This looks good now.

**Comment by offamitkumar** [comment]
@kuaiwei  you need one more approval from **R**eviewer, before integrating hotspot change.

**Comment by kuaiwei** [comment]
> @kuaiwei you need one more approval from **R**eviewer, before integrating hotspot change.

Ok , I will wait for another review. May I rollback the integrate request?

**Comment by lgxbslgx** [comment]
> Ok , I will wait for another review. May I rollback the integrate request?

You can use the command `/reviewers 2 reviewer` to impose restriction.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by iwanowww** [comment]
No need to retract integration request. As the robot reported earlier, you need a Commiter to sponsor the PR. But, please, wait until @vnkozlov confirms that testing results are good.

**Comment by vnkozlov** [comment]
Latest version v03 testing passed.

**Pull request closed without merging**
