### PR TITLE
8254883: ZGC: Make the ZArrayIterator reusable for ZRelocationSetIterators

### PR DESCRIPTION
**Pull request by pliden**
The ZRelocationSetIterators are mostly just duplicate implementations of the ZArrayIterators. With some slight adjustments to ZArrayIteratorImpl we can make that code reusable for ZRelocationSetIteratorImpl.

Note that this PR builds/depends on "8254878: Move last piece of ZArray to GrowableArray", which is out for review as a separate PR (https://github.com/openjdk/jdk/pull/694).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254883](https://bugs.openjdk.java.net/browse/JDK-8254883): ZGC: Make the ZArrayIterator reusable for ZRelocationSetIterators

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/697/head:pull/697`
`$ git checkout pull/697`

### CODE REVIEW

**Comment by pliden** [comment]
Updated to make the iterator take const arrays.

**Comment by pliden** [comment]
Rebased, folded, and updated ZGranuleMapIterator to also use ZArrayIterator.

**Review by fisk — APPROVED** [review]
Looks good.

**Pull request closed without merging**
