### PR TITLE
8271368: [BACKOUT] JDK-8266054 VectorAPI rotate operation optimization

### PR DESCRIPTION
**Pull request by vnkozlov**
Backout the following changes due to vector tests failures in tier 2 and later: 
[JDK-8266054](https://bugs.openjdk.java.net/browse/JDK-8266054) VectorAPI rotate operation optimization 

Changes also caused copyright header validation failure in Tier1 due to missing `,` after copyright year in new test.

Currently running testing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271368](https://bugs.openjdk.java.net/browse/JDK-8271368): [BACKOUT] JDK-8266054 VectorAPI rotate operation optimization

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4915/head:pull/4915` \
`$ git checkout pull/4915`

Update a local copy of the PR: \
`$ git checkout pull/4915` \
`$ git pull https://git.openjdk.java.net/jdk pull/4915/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4915`

View PR using the GUI difftool: \
`$ git pr show -t 4915`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4915.diff">https://git.openjdk.java.net/jdk/pull/4915.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Backout looks good.

Thanks,
David

**Review by iklam — APPROVED** [review]
LGTM

**Comment by jatin-bhateja** [comment]
- Thanks for reporting it, should it be ok to move those tests to ProblemList.txt and let me fix this as a follow up issue ?

**Comment by vnkozlov** [comment]
> * Thanks for reporting it, should it be ok to move those tests to ProblemList.txt and let me fix this as a follow up issue instead of a revert ?

@jatin-bhateja We did not test original changes in our testing infra. There could be other issues in high tiers which we don't know.
I prefer that you use 8271366 to prepare changes with fixed reported failure, file PR and let me run testing.

**Pull request closed without merging**
