### PR TITLE
8252002: remove usage of PropertyResolvingWrapper in vmTestbase/nsk/jdwp

### PR DESCRIPTION
**Pull request by iignatev**
the patch removes `PropertyResolvingWrapper` from `vmTestbase/nsk/jdwp` tests and cleans up/reformats the touched files.

testing:  ✅ `vmTestbase/nsk/jdwp` on `{linux,windows,macos}-x64`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252002](https://bugs.openjdk.java.net/browse/JDK-8252002): remove usage of PropertyResolvingWrapper in vmTestbase/nsk/jdwp

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/351/head:pull/351`
`$ git checkout pull/351`

### CODE REVIEW

**Comment by iignatev** [comment]
ping?

**Review by plummercj — APPROVED** [review]
The changes look good, although I wouldn't have preferred multiple RFRs for these changes. Yes, you have separate commits which did make them easier to review, but Skara is going to collapse them all into one commit.

**Comment by sspitsyn** [comment]
Igor, this update looks good.

**Review by sspitsyn — APPROVED** [review]

**Comment by iignatev** [comment]
Chris, Serguei, thank you for your reviews.

/integrate

**Pull request closed without merging**
