### PR TITLE
8285373: Create an automated test for JDK-4702233

### PR DESCRIPTION
**Pull request by srmandal**
Create an automated test for [JDK-4702233](https://bugs.openjdk.java.net/browse/JDK-4702233)

Several new AccessibleRole and AccessibleRelation constants are needed in those classes in the java.accessibility package. These new contants codify additions made in the GNOME, Netscape, and UNO (StarOffice) accessibility APIs.
StarOffice 6.1 and GNOME accessibility require new role, state and relation
constants in the javax.accessibility package. The existing constants are
inadequate for providing accessibility to StarOffice and GNOME applications
as required by Section 508.

Solution
--------
Define new constants in the javax.accessibility package.
AccessibleRelation
AccessibleRoles
AccessibleState
AccessibleAction
AccessibleContext

The test validates the public fields of the above AccessibleConstants.

This review is for migrating tests from a closed test suite to open.

Testing:
The test ran successfully on Mach5 with multiple runs (30) on windows-x64, linux-x64 and macos-x64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285373](https://bugs.openjdk.java.net/browse/JDK-8285373): Create an automated test for JDK-4702233

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8342/head:pull/8342` \
`$ git checkout pull/8342`

Update a local copy of the PR: \
`$ git checkout pull/8342` \
`$ git pull https://git.openjdk.java.net/jdk pull/8342/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8342`

View PR using the GUI difftool: \
`$ git pr show -t 8342`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8342.diff">https://git.openjdk.java.net/jdk/pull/8342.diff</a>

</details>

### CODE REVIEW

**Comment by srmandal** [comment]
Hi! Can someone please take a look at this PR and provide their valuable feedback ?

**Comment by srmandal** [comment]
Hi! Can someone please take a look at this PR and provide their valuable feedback ?

**Comment by srmandal** [comment]
Hi! Can someone please take a look at this PR and provide their valuable feedback ?

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
