### PR TITLE
JDK-8267163: Rename anonymous loader tests to hidden loader tests

### PR DESCRIPTION
**Pull request by mseledts**
Please review this simple change that renames vm/mlvm tests and test package name from anonymous to hidden.
Testing:
  Ran open/test/hotspot/jtreg/vmTestbase/vm/mlvm on MacOS-x64: PASS
  Running open/test/hotspot/jtreg/vmTestbase/vm/mlvm on multiple platforms: in progress ...

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267163](https://bugs.openjdk.java.net/browse/JDK-8267163): Rename anonymous loader tests to hidden loader tests

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 959604ef9d3d6320eb5362ec7b8b180061c75cff
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to 959604ef9d3d6320eb5362ec7b8b180061c75cff

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5570/head:pull/5570` \
`$ git checkout pull/5570`

Update a local copy of the PR: \
`$ git checkout pull/5570` \
`$ git pull https://git.openjdk.java.net/jdk pull/5570/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5570`

View PR using the GUI difftool: \
`$ git pr show -t 5570`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5570.diff">https://git.openjdk.java.net/jdk/pull/5570.diff</a>

</details>

### CODE REVIEW

**Comment by mseledts** [comment]
@hseigel Harold, please review when you have a chance.

**Review by dholmes-ora — APPROVED** [review]
Hi Misha,

This renaming seems fine.

Thanks,
David

**Review by hseigel — APPROVED** [review]
The changes look good.  Thanks for doing this.
Harold

**Comment by mseledts** [comment]
David, Harold, thank you for review. All testing passed.

/integrate

**Pull request closed without merging**
