### PR TITLE
8323616: [JVMCI] TestInvalidJVMCIOption.java fails intermittently with NPE

### PR DESCRIPTION
**Pull request by dougxc**
This PR changes callSystemExit to call `vm_exit_during_initialization()` instead of `System.exit` if the module system has not been initialized. This avoids an NPE in the `System.exit` code path where it is assumed that the `Class.module` field is non-null for `java.lang.Shutdown`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323616](https://bugs.openjdk.org/browse/JDK-8323616): [JVMCI] TestInvalidJVMCIOption.java fails intermittently with NPE (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [91be4c2d](https://git.openjdk.org/jdk/pull/17397/files/91be4c2d8036c5ee50e48ee4523a76bad448c6f4)
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17397/head:pull/17397` \
`$ git checkout pull/17397`

Update a local copy of the PR: \
`$ git checkout pull/17397` \
`$ git pull https://git.openjdk.org/jdk.git pull/17397/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17397`

View PR using the GUI difftool: \
`$ git pr show -t 17397`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17397.diff">https://git.openjdk.org/jdk/pull/17397.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17397#issuecomment-1889373707)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good and trivial.

**Comment by dougxc** [comment]
@TobiHartmann I've changed the PR based on further discussion in https://bugs.openjdk.org/browse/JDK-8323616 - please re-review.

@tkrodriguez can you also please review this PR.

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable.

**Review by tkrodriguez — APPROVED** [review]
Looks good.

**Comment by dougxc** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
