### PR TITLE
8270519: Move several vector helper methods to shared header file

### PR DESCRIPTION
**Pull request by XiaohongGong**
Hi, could anyone please take a look at this simple patch?

This is a followed-up patch to [1] which added several arch independent vector methods (e.g. `vector_length/vector_element_basic_type`). Since these methods also exist in x86.ad and are widely used in their match rules, it's better to move the shared methods to a common shared place.

[1] https://bugs.openjdk.java.net/browse/JDK-8269725

Tested tier1 and jdk:tier3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270519](https://bugs.openjdk.java.net/browse/JDK-8270519): Move several vector helper methods to shared header file

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4822/head:pull/4822` \
`$ git checkout pull/4822`

Update a local copy of the PR: \
`$ git checkout pull/4822` \
`$ git pull https://git.openjdk.java.net/jdk pull/4822/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4822`

View PR using the GUI difftool: \
`$ git pr show -t 4822`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4822.diff">https://git.openjdk.java.net/jdk/pull/4822.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
Looks reasonable to me.
Thanks.

**Comment by XiaohongGong** [comment]
Hi @theRealAph , could you please take a look at this patch especially the AArch64 part? Thanks so much!

**Comment by XiaohongGong** [comment]
Thanks for the review @DamonFool !

**Review by nsjian — APPROVED** [review]

**Comment by XiaohongGong** [comment]
Thanks for the review @nsjian !

**Comment by DamonFool** [comment]
See no objection, so sponsor it.
/sponsor

**Pull request closed without merging**
