### PR TITLE
8327729: Remove deprecated xxxObject methods from jdk.internal.misc.Unsafe

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which removes the 19 deprecated `xxObject*` alias methods from `jdk.internal.misc.Unsafe`.

These methods were added in JDK-8213043 (JDK 12), presumably to allow `jsr166.jar` to be used across JDK versions. This was a follow-up fix after JDK-8207146 had renamed these methods to `xxReference*'.

Since OpenJDK is now the single source of truth for `java.util.concurrent`, time has come to remove these deprecated alias methods.

This change was initially discussed here: https://mail.openjdk.org/pipermail/core-libs-dev/2024-March/119993.html

Testing: This is a pure deletion of deprecated methods, so the PR includes no test changes and the `noreg-cleanup` label is added in the JBS. I have verified that all `test/jdk/java/util/concurrent/*` tests pass.

Tagging @DougLea and @Martin-Buchholz to verify that this removal is timely.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327729](https://bugs.openjdk.org/browse/JDK-8327729): Remove deprecated xxxObject methods from jdk.internal.misc.Unsafe (**Enhancement** - P4)

### Reviewers
 * [Martin Buchholz](https://openjdk.org/census#martin) (@Martin-Buchholz - **Reviewer**) ⚠️ Review applies to [997056d5](https://git.openjdk.org/jdk/pull/18176/files/997056d579dc5e62ac5725592ac564094196e814)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [997056d5](https://git.openjdk.org/jdk/pull/18176/files/997056d579dc5e62ac5725592ac564094196e814)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18176/head:pull/18176` \
`$ git checkout pull/18176`

Update a local copy of the PR: \
`$ git checkout pull/18176` \
`$ git pull https://git.openjdk.org/jdk.git pull/18176/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18176`

View PR using the GUI difftool: \
`$ git pr show -t 18176`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18176.diff">https://git.openjdk.org/jdk/pull/18176.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18176#issuecomment-1987105787)

### CODE REVIEW

**Review by Martin-Buchholz — APPROVED** [review]
Thanks for the tidying - I agree the time is right.

**Review by AlanBateman — APPROVED** [review]
Removal of unused methods from an internal class, no impact to sun.misc.Unsafe.

**Comment by eirbjo** [comment]
Thanks for reviewing, Martin and Alan.

GHA revealed two call sites for ` getAndSetIObject` in the test `test/hotspot/jtreg/gc/shenandoah/compiler/TestUnsafeLoadStoreMergedHeapStableTests.java`. 

I have replaced these with the `getAndSetReference`, grepped for any remaining uses without finding anything. Let's see what GHA says.

**Comment by jaikiran** [comment]
Hello Eirik, I've triggered internal CI testing of the current state of this PR to run tier1, tier2 and tier3.

**Comment by AlanBateman** [comment]
> GHA revealed two call sites for `getAndSetObject` in the test `test/hotspot/jtreg/gc/shenandoah/compiler/TestUnsafeLoadStoreMergedHeapStableTests.java`.
> 
> I have replaced these with the `getAndSetReference`, grepped for any remaining uses without finding anything. Let's see what GHA says.

Yes, you'll need to run all tests to make sure that there aren't any others, e.g. test/hotspot/jtreg/compiler/stable/TestUnstableStable.java.

**Comment by eirbjo** [comment]
> Yes, you'll need to run all tests to make sure that there aren't any others, e.g. test/hotspot/jtreg/compiler/stable/TestUnstableStable.java.

I've updated `TestUnstableStable` to use `putReference` and also fixed a stray code comment reference to `Unsafe.compareAndSetObject` in `BufferedInputStream`.

**Comment by DougLea** [comment]
OK with me.

**Comment by jaikiran** [comment]
> @jaikiran Expect TestUnstableStable above to fail your CI run.

Right, that's the only test that failed (with a compilation error) on all platforms.

**Review by mlchung — APPROVED** [review]
This should wait for @jaikiran approval confirming the test result is good.

**Comment by jaikiran** [comment]
Hello Eirik, Mandy, tier1, tier2, tier3 testing of the latest approved state of this PR passed without failures.

**Comment by eirbjo** [comment]
Thanks for helping out with this cleanup effort, Jaikiran, Alan, Mandy, Doug and Martin!

/integrate

**Pull request closed without merging**
