### PR TITLE
8269416: [JVMCI] capture libjvmci crash data to a file

### PR DESCRIPTION
**Pull request by dougxc**
When a fatal error occurs in libgraal, it writes a crash dump to `tty`. Instead, it should be captured in a separate log file that is then referenced in the HotSpot crash summary (just like the hs_err_pid and CI replay compile log files are). This allows libgraal crash data to be more easily submitted along with VM crash reports.

For example:
```
> java -Dlibgraal.CrashAtIsFatal=true -Dgraal.CrashAt=String.equals -cp bin CountUppercase skjdf
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (jvmciRuntime.cpp:909), pid=36298, tid=41219
#  fatal error: thread 41219: Fatal error in JVMCI shared library
#
# JRE version: OpenJDK Runtime Environment GraalVM LIBGRAAL 21.3.0-dev (16.0.2) (build 16.0.2-internal+0-adhoc.dnsimon.labsjdk-ce-16)
# Java VM: OpenJDK 64-Bit Server VM GraalVM LIBGRAAL 21.3.0-dev (16.0.2-internal+0-adhoc.dnsimon.labsjdk-ce-16, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dnsimon/graal/graal/compiler/hs_err_pid36298.log
#
# The JVMCI shared library error data is saved as:
# /Users/dnsimon/graal/graal/compiler/hs_err_pid36298_libjvmci.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269416](https://bugs.openjdk.java.net/browse/JDK-8269416): [JVMCI] capture libjvmci crash data to a file

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to ba004ef0b39f2d8d526a8195b497f9e4f2e56b3e
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to ba004ef0b39f2d8d526a8195b497f9e4f2e56b3e

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4620/head:pull/4620` \
`$ git checkout pull/4620`

Update a local copy of the PR: \
`$ git checkout pull/4620` \
`$ git pull https://git.openjdk.java.net/jdk pull/4620/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4620`

View PR using the GUI difftool: \
`$ git pr show -t 4620`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4620.diff">https://git.openjdk.java.net/jdk/pull/4620.diff</a>

</details>

### CODE REVIEW

**Comment by dougxc** [comment]
> Someone from Runtime group may have good suggestions for this changes.
> I think you need to follow (or create JVMCI specific flags) flags used for error reporting:
> 
> SuppressFatalErrorMessage

I don't think extra handling is needed for that flag. It cuts off all paths that lead to libjvmci error handling.

> ErrorFileToStdout
> ErrorFileToStderr

I will push a change to respect these flags in `JVMCI::fatal_log`.

> ShowMessageBoxOnError
> UseOSErrorReporting

It's not clear to me that I need to worry about these - advice welcome.

**Review by vnkozlov — APPROVED** [review]
Okay. this is fine.

Still you need review from Runtime group. I will ping them.

**Comment by dholmes-ora** [comment]
Personally I think JVMCI error reporting can be handled independently of the other VM error reporting flags etc. No need to interact with ErrorFileToStdOut/Err as this is not the error file that flag refers to.

I will take a look at the changes in more detail.

Thanks,
David

**Review by dholmes-ora — APPROVED** [review]
This is predominantly a compiler change so I can only approve the shared runtime changes in vmError.

I have no concerns about this change from a runtime perspective.

Thanks,
David

**Comment by dougxc** [comment]
Thanks for the review David. If it's all the same, I'll keep the ErrorFileToStdOut/Err behavior for this libjvmci error reporting. Looking at the rationale for https://bugs.openjdk.java.net/browse/JDK-8220786, it makes sense for libjvmci error reporting to go to the console when retrieving log files from container environments is problematic. It might even be worth having CI compiler replay respect these flags but that's a separate question that I leave up to @vnkozlov.

**Pull request closed without merging**
