### PR TITLE
JDK-8280534: Enable compile-time doclint reference checking

### PR DESCRIPTION
**Pull request by jddarcy**
The changes in this PR on top of the out-for-review changes in https://git.openjdk.java.net/jdk/pull/7222 allow compile-time doclint checking to be enabled in all JDK modules.

Typically, a @SuppressWarnings("doclint:refernce") annotation is added to declaration with javadoc blocks that have already had distinguished cross-module links added (JDK-8280492).

One exception is in src/java.base/share/classes/java/net/package-info.java where the cross-module link was (for now) removed. Currently the SuppressWarnings annotation type is not declared to allow its annotations to be applied to package declarations. I'll look into amending that, but in the mean time, I think it is beneficial for the JDK build, and the base module in particular, to have compile-time doclint protections turned on.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280534](https://bugs.openjdk.java.net/browse/JDK-8280534): Enable compile-time doclint reference checking

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to 70e9fb4ae12cea78e24f49b969d25b101fd02700
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to 70e9fb4ae12cea78e24f49b969d25b101fd02700
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to 70e9fb4ae12cea78e24f49b969d25b101fd02700
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to d03401c6ac90c81a97c5d7cb143a0ed50dee664c
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to d03401c6ac90c81a97c5d7cb143a0ed50dee664c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7237/head:pull/7237` \
`$ git checkout pull/7237`

Update a local copy of the PR: \
`$ git checkout pull/7237` \
`$ git pull https://git.openjdk.java.net/jdk pull/7237/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7237`

View PR using the GUI difftool: \
`$ git pr show -t 7237`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7237.diff">https://git.openjdk.java.net/jdk/pull/7237.diff</a>

</details>

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Review by naotoj — APPROVED** [review]
Looks fine. Nit: some files need copyright year updates.

**Comment by jddarcy** [comment]
> Looks fine. Nit: some files need copyright year updates.

Acknowledged; I'll run a copyright update script before pushing (I tend to run that close to pushing to avoid spurious, if minor, merge conflicts). Thanks.

**Review by mlchung — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
