### PR TITLE
8330155: Serial: Remove TenuredSpace

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

This patch removes the class `TenuredSpace` and adjusts its usages. After removing `TenuredSpace`, the file `space.inline.hpp` is empty, so I remove this file and change the included header file to `space.hpp`.

The test `make test-tier1_gc` passed locally. Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330155](https://bugs.openjdk.org/browse/JDK-8330155): Serial: Remove TenuredSpace (**Enhancement** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [f1bd3517](https://git.openjdk.org/jdk/pull/18894/files/f1bd3517cc10345ff5cc6eec9e8fb12b38e6f4ec)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [f1bd3517](https://git.openjdk.org/jdk/pull/18894/files/f1bd3517cc10345ff5cc6eec9e8fb12b38e6f4ec)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18894/head:pull/18894` \
`$ git checkout pull/18894`

Update a local copy of the PR: \
`$ git checkout pull/18894` \
`$ git pull https://git.openjdk.org/jdk.git pull/18894/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18894`

View PR using the GUI difftool: \
`$ git pr show -t 18894`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18894.diff">https://git.openjdk.org/jdk/pull/18894.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18894#issuecomment-2070137352)

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]

**Review by plummercj — APPROVED** [review]
SA changes look good.

**Comment by lgxbslgx** [comment]
I merged the master branch in order to solve the file conflict and added the missed header file after merging. Please take a look at the newest code.

**Review by albertnetymk — APPROVED** [review]

**Comment by lgxbslgx** [comment]
Thanks for the reviews. Integrating.

/integrate

**Pull request closed without merging**
