### PR TITLE
8286636: MacroAssembler::post_call_nop should have InstructionMark

### PR DESCRIPTION
**Pull request by shipilev**
`InstructionMark` checks the instruction boundaries, which is important for relocatable instructions. Everywhere where we do any (?) sort of relocation, we do `InstructionMark`. I found that newly added `MacroAssembler::post_call_nop` does not have it, and thus some new code in x86_32 Loom prototype fails with missing instruction mark / instruction overlapping checks. 

If we add it to `InstructionMark` in AArch64 code, then "overlapping instructions" asserts start to fire, because Loom inserted `post_call_nops` when there was an active instruction mark. x86_64 solves this by [resetting the mark before the nop](https://github.com/openjdk/jdk/blob/40f43c6b1ffc88d55dd3223f5d0259ae73cf0356/src/hotspot/cpu/x86/x86_64.ad#L2084), this patch does the same.

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux AArch64 fastdebug `tier1`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286636](https://bugs.openjdk.java.net/browse/JDK-8286636): MacroAssembler::post_call_nop should have InstructionMark

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8678/head:pull/8678` \
`$ git checkout pull/8678`

Update a local copy of the PR: \
`$ git checkout pull/8678` \
`$ git pull https://git.openjdk.java.net/jdk pull/8678/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8678`

View PR using the GUI difftool: \
`$ git pr show -t 8678`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8678.diff">https://git.openjdk.java.net/jdk/pull/8678.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
> On 5/12/22 14:00, Aleksey Shipilev wrote:
> > `InstructionMark` checks the instruction boundaries, which is important for relocatable instructions. Everywhere where we do any (?) sort of relocation, we do `InstructionMark`. I found that newly ad
> 
> What is the meaning of "checks the instruction boundaries"? Just that we make sure that we cannot ever have multiple relocations of the same address, or something more subtle than that?

AFAICS, among other things, yes, we are making sure no more than one relocation per instruction happens.

> Or, how would overlapping instructions happen?

Pretty easy, this is what I had in x86_32 and AArch64: we expand the "instruction" through the .ad / macroAssembler, and then circle back to `MacroAssembler::post_call_nop`, which is a relocation-bearing instruction in its own right. `InstructionMark` in `post_call_nop` then rightfully asserts that we are in the middle of emitting another "instruction". AFAICS, this whole thing is an optional check that protects us from calling into `Assembler`/`MacroAssembler` haphazardly.

**Comment by shipilev** [comment]
> Pretty easy, this is what I had in x86_32 and AArch64: we expand the "instruction" through the .ad / macroAssembler, and then circle back to `MacroAssembler::post_call_nop`, which is a relocation-bearing instruction in its own right. `InstructionMark` in `post_call_nop` then rightfully asserts that we are in the middle of emitting another "instruction". AFAICS, this whole thing is an optional check that protects us from calling into `Assembler`/`MacroAssembler` haphazardly.

Oh, and to add to that, on x86_32 another thing also happens: calls to `relocate` check there is an `InstructionMark` in place. So we either relax that assert (dubious), or we do `InstructionMark` everywhere we do `relocate()`.

**Comment by shipilev** [comment]
Any comments?

**Comment by shipilev** [comment]
> Looks good. And your analysis is correct.

Thanks! @theRealAph, are you good with this discussion?

**Comment by shipilev** [comment]
I would like a second Reviewer, please.

**Review by fisk — APPROVED** [review]
Looks good.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
