### PR TITLE
8295714: GHA ::set-output is deprecated and will be removed

### PR DESCRIPTION
**Pull request by magicus**
We need to transition to use the new `$GITHUB_OUTPUT` method instead. 

This needs to be fixed since it is currently spamming the summary with warnings, and will stop working soon.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295714](https://bugs.openjdk.org/browse/JDK-8295714): GHA ::set-output is deprecated and will be removed

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [9d51fadf](https://git.openjdk.org/jdk/pull/10785/files/9d51fadf2f3f4f4d1346ce703dafd59acf128849)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10785/head:pull/10785` \
`$ git checkout pull/10785`

Update a local copy of the PR: \
`$ git checkout pull/10785` \
`$ git pull https://git.openjdk.org/jdk pull/10785/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10785`

View PR using the GUI difftool: \
`$ git pr show -t 10785`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10785.diff">https://git.openjdk.org/jdk/pull/10785.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Thanks! Looks fine, provided GHAs are green.

**Comment by shipilev** [comment]
> My fixes were green, but all of the annoying log spam was not gone. After some digging, it turned out that GitHub's own `download-artifact@v3` was not clean, so I've upgraded it to `download-artifact@v3.0.1` which was released just hours (!) ago. (Luckily I did not try to research this yesterday...)

Hah, DevOps goes brrrrr.

I would then wait for `@v3` to catch up with the latest version, instead of sticking the `@v3.0.1` that would keep us at outdated version as newer versions appear. We can try to re-test this PR next week, maybe?

**Comment by magicus** [comment]
*digging some more* 

Actually, the `v3` tag is already identical to `v3.0.1`, so there's probably just some caching at work here. I'll revert the latest commit, and then I say we're good to go. The upload-artifact issue will resolve itself, eventually, and we do not need to delay this fix awaiting that.

**Comment by shipilev** [comment]
Fine by me.

**Pull request closed without merging**
