### PR TITLE
8261229: MethodData is not correctly initialized with TieredStopAtLevel=3

### PR DESCRIPTION
**Pull request by veresov**
Mostly a typo in compilation mode ergonomics that selected a quick-only mode essentially when the user specified TieredStopAtLevel={1,2,3}. The quick-only mode has an optimization that eliminates parts of the MDO since they are not needed. Meanwhile, the WB API considered it a fair game to request a level 3 compile, that requires a full MDO.

The fix corrects the original issue and also tries to be extra defensive with WB API (since it's semantics is not clearly specified) by always allocating full MDO if WB API is on.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261229](https://bugs.openjdk.java.net/browse/JDK-8261229): MethodData is not correctly initialized with TieredStopAtLevel=3

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2444/head:pull/2444`
`$ git checkout pull/2444`

### CODE REVIEW

**Comment by iignatev** [comment]
I don't think we should adjust the product code to behave differently just to satisfy the incorrect assumptions of WhiteBox. it also kinda defeats the purpose of WhiteBox API as we won't be able to go thru the same code path.

-- Igor

**Comment by veresov** [comment]
> I don't think we should adjust the product code to behave differently just to satisfy the incorrect assumptions of WhiteBox. it also kinda defeats the purpose of WhiteBox API as we won't be able to go thru the same code path.
> 
> -- Igor

Ok, fair enough, I'll remove it. But we should probably make WB more robust in this department - it needs to be throwing exceptions in cases when the user tries to submit compilation requests for unsupported levels.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by TobiHartmann** [comment]
Just wondering if we should add a regression test (i.e. add a `TieredStopAtLeveL=3`) run to the test(s) you've mentioned in the bug comments?

**Comment by veresov** [comment]
> Just wondering if we should add a regression test (i.e. add a `TieredStopAtLeveL=3`) run to the test(s) you've mentioned in the bug comments?

I think we should rather start running the existing tests in compiler/whitebox and compiler/tiered with TieredStopAtLevel={1, 2,3} instead. Many of them failed when I did that, 3 of them failed because of this particular problem.

**Comment by TobiHartmann** [comment]
Okay, even better.

**Pull request closed without merging**
