### PR TITLE
8281275: Upgrading from 8 to 11 no longer accepts '/' as filepath separator in gc paths

### PR DESCRIPTION
**Pull request by dholmes-ora**
Please review this trivial fix for UL parsing logic on Windows. We already special-cased paths like c:\logfile but didn't allow for c:/logfile. As noted in the bug report this is a regression from using -Xloggc where the c:/ path was allowed (and it even worked when Xloggc was converted internally to use UL - because it skipped the parsing logic and just directly set the file output!).

Testing:
  - new gtest added by expanding existing parsing gtest
  - tiers 1-3 Windows

Verified that new gtest fails without the fix.

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281275](https://bugs.openjdk.java.net/browse/JDK-8281275): Upgrading from 8 to 11 no longer accepts '/' as filepath separator in gc paths

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7415/head:pull/7415` \
`$ git checkout pull/7415`

Update a local copy of the PR: \
`$ git checkout pull/7415` \
`$ git pull https://git.openjdk.java.net/jdk pull/7415/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7415`

View PR using the GUI difftool: \
`$ git pr show -t 7415`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7415.diff">https://git.openjdk.java.net/jdk/pull/7415.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks good.

**Comment by dholmes-ora** [comment]
Thanks for the review @shipilev !

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Comment by dholmes-ora** [comment]
Thanks for the review @dcubed-ojdk !

/integrate

**Pull request closed without merging**
