### PR TITLE
JDK-8319437: NMT should show library names in call stacks

### PR DESCRIPTION
**Pull request by tstuefe**
With this tiny enhancement, NMT shows library names in callstacks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319437](https://bugs.openjdk.org/browse/JDK-8319437): NMT should show library names in call stacks (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.org/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16508/head:pull/16508` \
`$ git checkout pull/16508`

Update a local copy of the PR: \
`$ git checkout pull/16508` \
`$ git pull https://git.openjdk.org/jdk.git pull/16508/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16508`

View PR using the GUI difftool: \
`$ git pr show -t 16508`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16508.diff">https://git.openjdk.org/jdk/pull/16508.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16508#issuecomment-1794548924)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable.

Thanks

**Comment by tstuefe** [comment]
> Seems reasonable.
> 
> Thanks

Thank you, David! 

Need a second review.

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Comment by tstuefe** [comment]
Thanks @zhengyu123 and @dholmes-ora !

/integrate

**Pull request closed without merging**
