### PR TITLE
8339683: Simplify class data generation in InvokerBytecodeGenerator

### PR DESCRIPTION
**Pull request by liach**
Elide duplicate field CP entry creation, and reuse elements in the field CP entry for field generation.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339683](https://bugs.openjdk.org/browse/JDK-8339683): Simplify class data generation in InvokerBytecodeGenerator (**Sub-task** - P4)

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20896/head:pull/20896` \
`$ git checkout pull/20896`

Update a local copy of the PR: \
`$ git checkout pull/20896` \
`$ git pull https://git.openjdk.org/jdk.git pull/20896/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20896`

View PR using the GUI difftool: \
`$ git pr show -t 20896`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20896.diff">https://git.openjdk.org/jdk/pull/20896.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20896#issuecomment-2334656256)

### CODE REVIEW

**Comment by cl4es** [comment]
Can you explain the semantics of not generating classData when pre-generating LFs?

**Comment by liach** [comment]
pregen never kept class data, as they never call clinit generation. so this was silently discarded in pregen. The class name and class desc are wrong for pregen but they happen to be never used. new logic generates unused and wrong fieldref in invoker holder, and this update fixes it.

**Comment by cl4es** [comment]
Right, for pre-generated forms we don't need any tricks to keep the form and the implementation class alive together as these methods are added to the Holder class. So this is good. 

Maybe we should assert against attempting to add classData fields to a pre-generated LF? 

Which class name is wrong? I don't see it.

**Comment by liach** [comment]
For pregen we pass in the Holder class name for ctor parameter name. They then get a Lambdaform$ prefix.

**Review by cl4es — APPROVED** [review]
Looks good. And getting `Utf8Entry`s from the `FieldRefEntry` should help reduce constant pool lookups a bit.

**Comment by liach** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
