### PR TITLE
JDK-8320309: AIX: pthreads created by foreign test library don't work as expected

### PR DESCRIPTION
**Pull request by varada1110**
Following test fails due to missing pthread attributes on AIX :
java/foreign/TestUpcallAsync.java
java/foreign/stackwalk/TestAsyncStackWalk.java
java/foreign/loaderLookup/TestLoaderLookupJNI.java
java/foreign/enablenativeaccess/TestEnableNativeAccessJarManifest.java
java/foreign/enablenativeaccess/TestEnableNativeAccess.java

Note : Test needs the changes from [pull/16579](https://github.com/openjdk/jdk/pull/16579) and [pull/16414](https://github.com/openjdk/jdk/pull/16414 )

JBS Issue : [JDK-8320309](https://bugs.openjdk.org/browse/JDK-8320309)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320309](https://bugs.openjdk.org/browse/JDK-8320309): AIX: pthreads created by foreign test library don't work as expected (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16757/head:pull/16757` \
`$ git checkout pull/16757`

Update a local copy of the PR: \
`$ git checkout pull/16757` \
`$ git pull https://git.openjdk.org/jdk.git pull/16757/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16757`

View PR using the GUI difftool: \
`$ git pr show -t 16757`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16757.diff">https://git.openjdk.org/jdk/pull/16757.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16757#issuecomment-1822440227)

### CODE REVIEW

**Comment by varada1110** [comment]
That's a good news. I have added `pthread_attr_destroy` as well. Should I wait for Suchi's PRs to be merged or can I make this PR "Ready for Review"?

**Comment by TheRealMDoerr** [comment]
> @TheRealMDoerr : That's a good news. I have added `pthread_attr_destroy` as well. Should I wait for Suchi's PRs to be merged or can I make this PR "Ready for Review"?

It's good to go.

**Review by MBaesken — APPROVED** [review]
LGTM

**Review by tstuefe — APPROVED** [review]
+1

**Comment by varada1110** [comment]
Thanks all
/integrate

**Pull request closed without merging**
