### PR TITLE
8264063: Outer Safepoint poll load should not reference the head of inner strip mined loop.

### PR DESCRIPTION
**Pull request by vnkozlov**
When loop is "strip mined" polling address load ([parse1.cpp#L2280](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/parse1.cpp#L2280)) should be cloned together with safepoint node and pinned outside inner loop. Otherwise we have issues like [8263352](https://bugs.openjdk.java.net/browse/JDK-8263352)

I also remove leftover (unused needs_polling_address_input() method) from  [8220051](https://bugs.openjdk.java.net/browse/JDK-8220051) changes.

Tested hs-tier1-4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264063](https://bugs.openjdk.java.net/browse/JDK-8264063): Outer Safepoint poll load should not reference the head of inner strip mined loop.

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3365/head:pull/3365` \
`$ git checkout pull/3365`

Update a local copy of the PR: \
`$ git checkout pull/3365` \
`$ git pull https://git.openjdk.java.net/jdk pull/3365/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3365`

View PR using the GUI difftool: \
`$ git pr show -t 3365`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3365.diff">https://git.openjdk.java.net/jdk/pull/3365.diff</a>

</details>

### CODE REVIEW

**Comment by pfustc** [comment]
Should we also remove below part of code in `loopTransform.cpp` in this patch?

```
3704         if (n->is_CountedLoop() && n->as_CountedLoop()->is_strip_mined()) {
3705           // In strip-mined counted loops, the CountedLoopNode may be
3706           // used by the address polling node of the outer safepoint.
3707           // Skip this use because it's safe.
3708           Node* sfpt = n->as_CountedLoop()->outer_safepoint();
3709           Node* polladr = sfpt->in(TypeFunc::Parms+0);
3710           if (use == polladr) {
3711             continue;
3712           }
3713         }
```

**Comment by vnkozlov** [comment]
> Should we also remove below part of code in `loopTransform.cpp` in this patch?
> 
> ```
> 3704         if (n->is_CountedLoop() && n->as_CountedLoop()->is_strip_mined()) {
> 3705           // In strip-mined counted loops, the CountedLoopNode may be
> 3706           // used by the address polling node of the outer safepoint.
> 3707           // Skip this use because it's safe.
> 3708           Node* sfpt = n->as_CountedLoop()->outer_safepoint();
> 3709           Node* polladr = sfpt->in(TypeFunc::Parms+0);
> 3710           if (use == polladr) {
> 3711             continue;
> 3712           }
> 3713         }
> ```

I thought that is does not harm to have this code but on other hand it will be not executed anymore.
I will removed it and I will run ArrayFill.java to make sure optimization works with strip mined loops.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
Thank you Vladimir and Roland.

**Pull request closed without merging**
