### PR TITLE
8278065: Refactor subclassAudits to use ClassValue

### PR DESCRIPTION
**Pull request by rkennke**
As a follow-up to #6375, this change refactors java.io.ObjectInputStream.Caches#subclassAudits and java.io.ObjectOutputStream.Caches#subclassAudits to use ClassValue instead of SoftReference, similar to what we did in #6375 for java.io.ObjectStreamClass.Caches#localDescs. Then we can now also remove the common machinery java.io.ObjectStreamClass#processQueue and java.io.ObjectStreamClass.WeakClassKey.

Testing:
 - [x] tier1
 - [x] tier2
 - [ ] tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278065](https://bugs.openjdk.java.net/browse/JDK-8278065): Refactor subclassAudits to use ClassValue

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**) ⚠️ Review applies to 10b905cdfc9dd34fd61ea9968fcb1f79b2351a97
 * [Peter Levart](https://openjdk.java.net/census#plevart) (@plevart - **Reviewer**) ⚠️ Review applies to 6b37d520dd39ff89da796f21ec6759e375c18147

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6637/head:pull/6637` \
`$ git checkout pull/6637`

Update a local copy of the PR: \
`$ git checkout pull/6637` \
`$ git pull https://git.openjdk.java.net/jdk pull/6637/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6637`

View PR using the GUI difftool: \
`$ git pr show -t 6637`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6637.diff">https://git.openjdk.java.net/jdk/pull/6637.diff</a>

</details>

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
Looks good.

**Comment by rkennke** [comment]
> Looks good.

Thank you!
I believe it makes sense to also use the ClassCache here, just as I did in #6375. I'll change this PR accordingly tomorrow.

**Comment by RogerRiggs** [comment]
The ClassValues are simple Booleans, that won't make much of difference if there's memory pressure and the ClassCache adds more objects and overhead of processing the queue, so I don't think its beneficial.

**Comment by rkennke** [comment]
> The ClassValues are simple Booleans, that won't make much of difference if there's memory pressure and the ClassCache adds more objects and overhead of processing the queue, so I don't think its beneficial.

Right. Ok thanks, let's wait for #6375 then.

**Comment by plevart** [comment]
> The ClassValues are simple Booleans, that won't make much of difference if there's memory pressure and the ClassCache adds more objects and overhead of processing the queue, so I don't think its beneficial.

Right, SoftReference object has a bigger footprint than Boolean object (more fields). ObjectStreamClass was another beast. So it is actually detrimental to efficiency to keep Boolean inside SoftReference just to be able to release Boolean, since SoftReference will stay until associated Class or ClassValue goes away...

What you could do is to half the footprint of those two caches if you merge them both into a single cache with a value holding two primitive booleans. Such object has the same foorprint as Boolean (because of padding) and you only need one ClassValue instance which would halve the number of ClassValueMap entries in existence.

What do you think?

**Comment by plevart** [comment]
...well I tried to do that. And it is not so simple. Here's what I came up with:

```java
public final class ClassFlags {

    private static final class AtomicByte {
        private static final VarHandle VALUE;

        static {
            try {
                VALUE = MethodHandles.lookup().findVarHandle(AtomicByte.class, "value", byte.class);
            } catch (NoSuchFieldException | IllegalAccessException e) {
                throw new InternalError(e);
            }
        }

        private volatile byte value;

        byte get() {
            return value;
        }

        byte compareAndExchange(byte expectedValue, byte newValue) {
            return (byte) VALUE.compareAndExchange(this, (byte) expectedValue, (byte) newValue);
        }
    }

    private final Predicate<? super Class<?>>[] typePredicates;
    private final ClassValue<AtomicByte> flagsCV = new ClassValue<>() {
        @Override
        protected AtomicByte computeValue(Class<?> type) {
            return new AtomicByte();
        }
    };

    @SafeVarargs
    public ClassFlags(Predicate<? super Class<?>>... typePredicates) {
        if (typePredicates.length > 4) {
            throw new IllegalArgumentException("Up to 4 flags are supported in a single ClassFlags instance");
        }
        this.typePredicates = typePredicates;
    }

    public boolean get(Class<?> type, int index) {
        Objects.checkIndex(index, typePredicates.length);

        AtomicByte flags = flagsCV.get(type);
        int f = flags.get() & 0xFF;
        int falseMask = 0x1 << (index + index);
        int trueMask = falseMask << 1;
        int mask = falseMask | trueMask;
        int value = 0;
        while ((f & mask) == 0) {
            if (value == 0) {
                value = typePredicates[index].test(type) ? trueMask : falseMask;
            }
            int fn = (f & ~mask) | value;
            int fv = flags.compareAndExchange((byte) f, (byte) fn) & 0xFF;
            if (fv == f) {
                f = fn;
                break;
            } else {
                f = fv;
            }
        }
        return (f & trueMask) != 0;
    }
}
```

So I don't know if it's worth it... Simplicity of your implementation probably out-weights the footprint savings of above code.

Regards, Peter

**Comment by erikj79** [comment]
Skara is failing to run jcheck on this PR. I think this is ultimately a bug in Skara, that gets tickled by your source branch being quite far behind jdk:master, in combination with 62a7f5d3236ab2248518a475b1d8b71cb4bf1313 recently going in. If you merge jdk:master into your branch, I believe this will resolve itself for now.

**Comment by erikj79** [comment]
> Skara is failing to run jcheck on this PR. I think this is ultimately a bug in Skara, that gets tickled by your source branch being quite far behind jdk:master, in combination with [62a7f5d](https://github.com/openjdk/jdk/commit/62a7f5d3236ab2248518a475b1d8b71cb4bf1313) recently going in. If you merge jdk:master into your branch, I believe this will resolve itself for now.

I've investigated further and filed https://bugs.openjdk.java.net/browse/SKARA-1281. Once fixed you would get an error message in this PR telling you to rebase your source branch.

**Comment by rkennke** [comment]
I think we shoul

> ...well I tried to do that. And it is not so simple. Here's what I came up with:
> 
> ```java
> public final class ClassFlags {
> 
>     private static final class AtomicByte {
>         private static final VarHandle VALUE;
> 
>         static {
>             try {
>                 VALUE = MethodHandles.lookup().findVarHandle(AtomicByte.class, "value", byte.class);
>             } catch (NoSuchFieldException | IllegalAccessException e) {
>                 throw new InternalError(e);
>             }
>         }
> 
>         private volatile byte value;
> 
>         byte get() {
>             return value;
>         }
> 
>         byte compareAndExchange(byte expectedValue, byte newValue) {
>             return (byte) VALUE.compareAndExchange(this, (byte) expectedValue, (byte) newValue);
>         }
>     }
> 
>     private final Predicate<? super Class<?>>[] typePredicates;
>     private final ClassValue<AtomicByte> flagsCV = new ClassValue<>() {
>         @Override
>         protected AtomicByte computeValue(Class<?> type) {
>             return new AtomicByte();
>         }
>     };
> 
>     @SafeVarargs
>     public ClassFlags(Predicate<? super Class<?>>... typePredicates) {
>         if (typePredicates.length > 4) {
>             throw new IllegalArgumentException("Up to 4 flags are supported in a single ClassFlags instance");
>         }
>         this.typePredicates = typePredicates;
>     }
> 
>     public boolean get(Class<?> type, int index) {
>         Objects.checkIndex(index, typePredicates.length);
> 
>         AtomicByte flags = flagsCV.get(type);
>         int f = flags.get() & 0xFF;
>         int falseMask = 0x1 << (index + index);
>         int trueMask = falseMask << 1;
>         int mask = falseMask | trueMask;
>         int value = 0;
>         while ((f & mask) == 0) {
>             if (value == 0) {
>                 value = typePredicates[index].test(type) ? trueMask : falseMask;
>             }
>             int fn = (f & ~mask) | value;
>             int fv = flags.compareAndExchange((byte) f, (byte) fn) & 0xFF;
>             if (fv == f) {
>                 f = fn;
>                 break;
>             } else {
>                 f = fv;
>             }
>         }
>         return (f & trueMask) != 0;
>     }
> }
> ```
> 
> So I don't know if it's worth it... Simplicity of your implementation probably out-weights the footprint savings of above code.
> 
> Regards, Peter

I think I'd rather keep it simple. Can you please give it a review, too? Thanks, Roman

**Comment by plevart** [comment]
I think this looks good. Reviewed. Only a minor nit if you think it would be better, but not necessary if you don't. The following combo:

```
        Boolean result = Caches.subclassAudits.get(cl);
        assert result != null;
```

could be written as:

```
        boolean result = Caches.subclassAudits.get(cl);
```

...and it would give the same "message" to the reader. WDYT? No need for another round of reviews if you change this.

**Review by plevart — APPROVED** [review]

**Comment by rkennke** [comment]
> I think this looks good. Reviewed. Only a minor nit if you think it would be better, but not necessary if you don't. The following combo:
> 
> ```
>         Boolean result = Caches.subclassAudits.get(cl);
>         assert result != null;
> ```
> 
> could be written as:
> 
> ```
>         boolean result = Caches.subclassAudits.get(cl);
> ```
> 
> ...and it would give the same "message" to the reader. WDYT? No need for another round of reviews if you change this.

Right! I changed it.

BTW, I noticed that Thread.java has a similar subclassAudits machinery with WeakClassKey, which would also benefit from using ClassValue instead. I filed JDK-8279917 to track it.

**Comment by RogerRiggs** [comment]
I would have appreciated a chance to review the latest changes.

**Comment by rkennke** [comment]
> I would have appreciated a chance to review the latest changes.

Oh, ok, I'm sorry. I will wait some more next time that I get into a similar situation. I hope you're ok with the changes?

**Pull request closed without merging**
