### PR TITLE
8313810: BoxLayout uses <blockquote> instead of list for layout options

### PR DESCRIPTION
**Pull request by aivanov-jdk**
A clean-up of documentation for [`BoxLayout`](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/BoxLayout.html#class-description):

1. Use the `<ul>` element instead of `<blockquote>` to list layout options or axes.
2. Add links to `GridBagLayout` and `Box` classes.
3. Markup references to classes, mostly `BoxLayout` itself, with `{@code}`.
4. Separate the introduction to layout description from the description of horizontal layout. They're now in different paragraphs for easier scanning.
5. Add the missing ‘a’ articles.
6. Organise imports, including expanding the wildcard import.

The updated version: [**`BoxLayout.html`**](https://cr.openjdk.org/~aivanov/8313810/api/java.desktop/javax/swing/BoxLayout.html#class-description) (without the CSS).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8313810](https://bugs.openjdk.org/browse/JDK-8313810): BoxLayout uses &lt;blockquote&gt; instead of list for layout options (**Bug** - P4)
 * [JDK-8313811](https://bugs.openjdk.org/browse/JDK-8313811): Improve description of how BoxLayout lays out components (**Bug** - P5)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15182/head:pull/15182` \
`$ git checkout pull/15182`

Update a local copy of the PR: \
`$ git checkout pull/15182` \
`$ git pull https://git.openjdk.org/jdk.git pull/15182/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15182`

View PR using the GUI difftool: \
`$ git pr show -t 15182`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15182.diff">https://git.openjdk.org/jdk/pull/15182.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15182#issuecomment-1668482573)

### CODE REVIEW

**Comment by aivanov-jdk** [comment]
An alternative version [**`BoxLayout.html`**](https://cr.openjdk.org/~aivanov/8313810/api/java.desktop/javax/swing/BoxLayout-layout-list.html#class-description) which uses *a list* to describe the layout.

**Review by prrace — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
Anyone else?

Or may I integrate with one reviewer only?

**Pull request closed without merging**
