### PR TITLE
8258805: Japanese characters not entered by mouse click on Windows 10

### PR DESCRIPTION
**Pull request by dmarkov20**
Problem description:
The IME behaviour has changed starting from recent Windows 10 builds. In particular if the complex characters (Japanese, Chinese, etc.) are entered to some component and the focus is transferred to another component (which does not support the IM) the IM is disabled and the unconfirmed composition string gets discarded.
On previous Windows versions in the same situation the composition string is not discarded.

Fix:
It is necessary to take care of unconfirmed composition string once the IME is going to be disabled.

Testing:
All our automated regression and JCK tests passed with the proposed change.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258805](https://bugs.openjdk.java.net/browse/JDK-8258805): Japanese characters not entered by mouse click on Windows 10

### Reviewers
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2142/head:pull/2142`
`$ git checkout pull/2142`

### CODE REVIEW

**Comment by aivanov-jdk** [comment]
> Fix:
> It is necessary to take care of unconfirmed composition string once the IME is going to be disabled.

The fix commits the unconfirmed composition string. Committing is better than discarding. Is it possible to preserve the state and to leave the string uncommitted?

**Comment by dmarkov20** [comment]
> > Fix:
> > It is necessary to take care of unconfirmed composition string once the IME is going to be disabled.
> 
> The fix commits the unconfirmed composition string. Committing is better than discarding. Is it possible to preserve the 
state and to leave the string uncommitted?

The fix reverts the previous (correct) behaviour back. It is unnecessary to store the state and keep the string. That activity may be quite complicated and requires additional resources especially if there are several components with active IME

**Comment by takiguc** [comment]
Hello Dmitry.
Sorry, I should use GitHub instead of mailing list.
I tested your fix, I saw side effect by committing preedit string.
I'll give you detail information.

**Comment by takiguc** [comment]
I tried attached testcase.
```java
import java.awt.*;
import java.awt.event.*;

public class AWTTextTest1 extends Frame {
    AWTTextTest1() {
        setTitle("AWTTextTest1");
        setLayout(new GridLayout(0, 1));
        add(new TextField());
        add(new TextField());
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                System.exit(0);
            }
        });
        setSize(400, 300);
        setVisible(true);
    }
    public static void main(String[] args) {
        new AWTTextTest1();
    }
}
```
1. Start testcase
2. Click upper TextField, turn on IME, type some character (In case of Japanese, type "aiu")
3. Click lower TextField, preedit string is committed into lower TextField.

Without the fix, preedit string was canceled by above operation.

**Comment by mrserb** [comment]
How do the native components work in that case like awt textarea or external apps like notepad?

**Comment by takiguc** [comment]
> How do the native components work in that case like awt textarea or external apps like notepad?
I tested TextField+TextField, TextArea+TextArea, TextArea+TextField.
Without fix: Preedit string was cancel by input focus change.
With fix: Preedit string was committed into clicked component.

For external application, I used Sakura Editor, because it can create 2 editor panes on one window.
Preedit string was committed before moving input focus.

**Comment by dmarkov20** [comment]
> I tried attached testcase.
> 
> ```java
> import java.awt.*;
> import java.awt.event.*;
> 
> public class AWTTextTest1 extends Frame {
>     AWTTextTest1() {
>         setTitle("AWTTextTest1");
>         setLayout(new GridLayout(0, 1));
>         add(new TextField());
>         add(new TextField());
>         addWindowListener(new WindowAdapter() {
>             public void windowClosing(WindowEvent we) {
>                 System.exit(0);
>             }
>         });
>         setSize(400, 300);
>         setVisible(true);
>     }
>     public static void main(String[] args) {
>         new AWTTextTest1();
>     }
> }
> ```
> 
> 1. Start testcase
> 2. Click upper TextField, turn on IME, type some character (In case of Japanese, type "aiu")
> 3. Click lower TextField, preedit string is committed into lower TextField.
> 
> Without the fix, preedit string was canceled by above operation.

Hello Ichiroh,

Thank you for the details. I can reproduce it. I will look into this..

Regards,
Dmitry

**Comment by aivanov-jdk** [comment]
> > The fix commits the unconfirmed composition string. Committing is better than discarding. Is it possible to preserve the
> > state and to leave the string uncommitted?
> 
> The fix reverts the previous (correct) behaviour back.

According to bug description, it used to stay in uncommitted state.

> It is unnecessary to store the state and keep the string. That activity may be quite complicated and requires additional resources especially if there are several components with active IME

I definitely agree that committing a text is better behaviour than discarding uncommitted text.

I am for accepting these changes unless we can keep the text uncommitted and allow the user to work with text when the focus moves back to the text component.

**Comment by dmarkov20** [comment]
An interesting thing is that the test (see AWTTextTest1.java) behaves like a native application if TextField is replaced with JTextField. It appears AWT and Swing components behave directly while processing input method requests. That’s a great topic to discuss but it is out of scope for this PR. We can open a separate bug for it, if any.

Going back to the current PR. I updated the fix. Now we will commit the composition string if there is an active client. That changes eliminates the issue described in JDK-8258805. Also the behaviour of AWTTextTest1 is the same as it used to be on the previous versions w/o the fix.

**Comment by aivanov-jdk** [comment]
> Now we will commit the composition string if there is an active client. That changes eliminates the issue described in JDK-8258805. Also the behaviour of AWTTextTest1 is the same as it used to be on the previous versions w/o the fix.

Just to confirm: the updated behaviour is similar to what was happening in previous versions of Windows 10, that is if a compositing text isn't committed, it remains uncommitted in the text component when the focus changes instead of being committed as it was the case in the previous iteration. Is my understanding correct?

**Comment by dmarkov20** [comment]
> > Now we will commit the composition string if there is an active client. That changes eliminates the issue described in JDK-8258805. Also the behaviour of AWTTextTest1 is the same as it used to be on the previous versions w/o the fix.
> 
> Just to confirm: the updated behaviour is similar to what was happening in previous versions of Windows 10, that is if a compositing text isn't committed, it remains uncommitted in the text component when the focus changes instead of being committed as it was the case in the previous iteration. Is my understanding correct?

I am sorry but you didn't get it right. The behaviour, which was introduced in previous iteration, is still in place. It is required to get rid of the problem described in  JDK-8258805
The purpose of of the second iteration is to eliminate negative side effect (more details here https://github.com/openjdk/jdk/pull/2142#issuecomment-763340186 ) introduced by the first version of the fix.

**Comment by aivanov-jdk** [comment]
> > > Now we will commit the composition string if there is an active client. That changes eliminates the issue described in JDK-8258805. Also the behaviour of AWTTextTest1 is the same as it used to be on the previous versions w/o the fix.
> > 
> > 
> > Just to confirm: the updated behaviour is similar to what was happening in previous versions of Windows 10, that is if a compositing text isn't committed, it remains uncommitted in the text component when the focus changes instead of being committed as it was the case in the previous iteration. Is my understanding correct?
> 
> I am sorry but you didn't get it right. The behaviour, which was introduced in previous iteration, is still in place. It is required to get rid of the problem described in JDK-8258805
> The purpose of of the second iteration is to eliminate negative side effect (more details here [#2142 (comment)](https://github.com/openjdk/jdk/pull/2142#issuecomment-763340186) ) introduced by the first version of the fix.

I admit I am even more confused now. To me, the description in the comment above is nearly the same as in [JBS comment](https://bugs.openjdk.java.net/browse/JDK-8258805?focusedCommentId=14391025&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14391025). Is the difference that the original test case disabled IME for the middle JTextField whereas in the test case above all JTextField support IME?

In the updated version of the fix, we always commit the text on any focus change whether the newly focused component supports IME or not.

**Comment by dmarkov20** [comment]
> I admit I am even more confused now. To me, the description in the comment above is nearly the same as in [JBS comment](https://bugs.openjdk.java.net/browse/JDK-8258805?focusedCommentId=14391025&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14391025). Is the difference that the original test case disabled IME for the middle JTextField whereas in the test case above all JTextField support IME?

Well.. I think the main difference between tests is that the [test attached to the bug](https://bugs.openjdk.java.net/browse/JDK-8258805?focusedCommentId=14391025&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14391025) uses `JTextField` (Swing) and the [test provided above](https://github.com/openjdk/jdk/pull/2142#issuecomment-763491615) uses `TextField` (AWT). The same input method events are processed differently for Swing and AWT text components. Good example is the following test:

```java
import java.awt.*;
import java.awt.event.*;

public class AWTTextTest1 extends Frame {
    AWTTextTest1() {
        setTitle("AWTTextTest1");
        setLayout(new GridLayout(0, 1));
        add(new TextField());
        add(new TextField());
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                System.exit(0);
            }
        });
        setSize(400, 300);
        setVisible(true);
    }
    public static void main(String[] args) {
        new AWTTextTest1();
    }
}
```

1. Run test (originally it uses `TextField`)
2. Click upper `TextField`, turn on IME, type some character (In case of Japanese, type "aiu") 
3. Click lower `TextField`, the string is canceled. 
4. Replace `TextField` with `JTextField` in the test. Compile and run it again.
5. Click upper `JTextField`, turn on IME, type some character (In case of Japanese, type "aiu")
6. Click lower `JTextField`, the string is committed before focus transition.

> 
> In the updated version of the fix, we always commit the text on any focus change whether the newly focused component supports IME or not.

That’s not quite right. Actually we commit the text if the current IM client is “active client”. For example, `JTextField` is an “active client” but `TextField`  - NOT. The status “active client” depends on the implementation of getInputMethodRequests() method.

**Comment by naotoj** [comment]
Hi,

AWT's `TextComponent` is a `peered` input client, and Swing's `JTextComponent` is an `active` input client. Thus it is OK to behave differently. I would expect that AWT's one behaves as the same as native Windows apps, and Swing's one should commit text into the component that has lost the focus.

**Review by aivanov-jdk — APPROVED** [review]

**Comment by dmarkov20** [comment]
> Hi,
> 
> AWT's `TextComponent` is a `peered` input client, and Swing's `JTextComponent` is an `active` input client. Thus it is OK to behave differently. I would expect that AWT's one behaves as the same as native Windows apps, and Swing's one should commit text into the component that has lost the focus.

Thank you for confirmation! With the fix we have the same behaviour as you described.

**Comment by takiguc** [comment]
Thanks, Dmitry.
I tested your new fix.
It's fine now on Swing and AWT.

**Pull request closed without merging**
