### PR TITLE
8274632: Possible pointer overflow in PretouchTask chunk claiming

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to PretouchTask, fixing the mechanism used to
claim chunks for parallel touching.  The old mechanism unconditionally added
a potentially large value to the current pointer and then checked the result
for overflow.  But since pointer arithmetic overflow is UB, that's not a
reliable approach.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274632](https://bugs.openjdk.java.net/browse/JDK-8274632): Possible pointer overflow in PretouchTask chunk claiming

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to b3e5e12a99a45fc1949d7f3c0a6f8d2dd515019d
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to b3e5e12a99a45fc1949d7f3c0a6f8d2dd515019d

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5791/head:pull/5791` \
`$ git checkout pull/5791`

Update a local copy of the PR: \
`$ git checkout pull/5791` \
`$ git pull https://git.openjdk.java.net/jdk pull/5791/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5791`

View PR using the GUI difftool: \
`$ git pr show -t 5791`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5791.diff">https://git.openjdk.java.net/jdk/pull/5791.diff</a>

</details>

### CODE REVIEW

**Comment by kimbarrett** [comment]
Also removed the no longer used _start_addr member.  And I just realized
the overflow check was doubly bad, since it was using that value, and
the potential wrap-around could exceed it.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by albertnetymk — APPROVED** [review]
Using `<newline> + if` instead of `else if` makes the early-return more visible, IMO.

**Comment by kimbarrett** [comment]
> Using `<newline> + if` instead of `else if` makes the early-return more visible, IMO.

That doesn't seem like an improvement to me.  And it's not an early-return as I would use that term.

**Comment by kimbarrett** [comment]
Thanks for reviews @tschatzl and @albertnetymk

**Pull request closed without merging**
