### PR TITLE
8252584: HotSpot Style Guide should permit alignas

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Add alignas to the permitted features set with some restrictions. (Thanks @kimbarrett for the help)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8252584](https://bugs.openjdk.org/browse/JDK-8252584): HotSpot Style Guide should permit alignas

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [cec044b4](https://git.openjdk.org/jdk/pull/11404/files/cec044b4aacc2d10886b55ca67fdcfeb08efd0ae)

### Contributors
 * Kim Barrett `<kbarrett@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11404/head:pull/11404` \
`$ git checkout pull/11404`

Update a local copy of the PR: \
`$ git checkout pull/11404` \
`$ git pull https://git.openjdk.org/jdk pull/11404/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11404`

View PR using the GUI difftool: \
`$ git pr show -t 11404`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11404.diff">https://git.openjdk.org/jdk/pull/11404.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
I think this is okay (not surprisingly).  Please add me as a contributor.

**Comment by kimbarrett** [comment]
This should not have been integrated yet.  Changes to the Style Guide have an approval process that is described in that document, including a 2 week voting period and final approval by the HotSpot lead.

**Comment by TheShermanTanker** [comment]
Oops, I did not realize that

Temporarily back this out for now?

**Comment by TheShermanTanker** [comment]
I've created an "emergency" revert at https://github.com/openjdk/jdk/pull/11433, sorry for the mistake

**Pull request closed without merging**
