### PR TITLE
JDK-8266779: Use <wbr> instead of ZERO_WIDTH_SPACE

### PR DESCRIPTION
**Pull request by hns**
This replaces usages of the zero-width space character (ZWSP, entity `&#8203;`) with the HTML5 `<wbr>` element. `<wbr>` acts as a word break opportunity without adding characters to the text content like ZWSP does. It is supported in all modern browsers, the only browser I  know of which doesn't support is are old versions of Internet Explorer. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr
https://caniuse.com/wbr-element

I have tested the output (both layout and copy-paste behaviour) on Firefox, Safari, and Chrome on Mac OS X.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266779](https://bugs.openjdk.java.net/browse/JDK-8266779): Use <wbr> instead of ZERO_WIDTH_SPACE

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**) ⚠️ Review applies to 095f16d2e7a70af39d0c6b5e114194a7632519da

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3946/head:pull/3946` \
`$ git checkout pull/3946`

Update a local copy of the PR: \
`$ git checkout pull/3946` \
`$ git pull https://git.openjdk.java.net/jdk pull/3946/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3946`

View PR using the GUI difftool: \
`$ git pr show -t 3946`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3946.diff">https://git.openjdk.java.net/jdk/pull/3946.diff</a>

</details>

### CODE REVIEW

**Review by pavelrappo — APPROVED** [review]
It's unfortunate that the text blocks in tests are formatted for a fixed width; diffs are filled with unrelated changes. Update copyright years and you're good to go. Thanks for fixing this, Hannes.

**Comment by hns** [comment]
I’d rather not. I don’t think it’s a huge improvement, there’s only 4 usages of this tag, and … it’s late and I’d like to close the issue :) 

I think there are some elements that are much more often used that don’t have a factory method. Maybe another cleanup task?

Hannes

**Comment by pavelrappo** [comment]
> I’d rather not. I don’t think it’s a huge improvement, there’s only 4 usages of this tag, and … it’s late and I’d like to close the issue :) I think there are some elements that are much more often used that don’t have a factory method. Maybe another cleanup task? Hannes

Up to you. I have reviewed it already.

**Review by jonathan-gibbons — COMMENTED** [review]
Nice

**Pull request closed without merging**
