### PR TITLE
8308716: ProblemList java/util/concurrent/ScheduledThreadPoolExecutor/BasicCancelTest.java with genzgc on windows-x64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial fixes to ProblemList some tests:
[JDK-8308716](https://bugs.openjdk.org/browse/JDK-8308716) ProblemList java/util/concurrent/ScheduledThreadPoolExecutor/BasicCancelTest.java with genzgc on windows-x64
[JDK-8308718](https://bugs.openjdk.org/browse/JDK-8308718) ProblemList three mlvm/indy/func/jvmti tests on windows-x64 in Xcomp mode
[JDK-8308720](https://bugs.openjdk.org/browse/JDK-8308720) ProblemList java/awt/event/SequencedEvent/MultipleContextsFunctionalTest.java on macosx-x64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8308716](https://bugs.openjdk.org/browse/JDK-8308716): ProblemList java/util/concurrent/ScheduledThreadPoolExecutor/BasicCancelTest.java with genzgc on windows-x64
 * [JDK-8308718](https://bugs.openjdk.org/browse/JDK-8308718): ProblemList three mlvm/indy/func/jvmti tests on windows-x64 in Xcomp mode
 * [JDK-8308720](https://bugs.openjdk.org/browse/JDK-8308720): ProblemList java/awt/event/SequencedEvent/MultipleContextsFunctionalTest.java on macosx-x64

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14106/head:pull/14106` \
`$ git checkout pull/14106`

Update a local copy of the PR: \
`$ git checkout pull/14106` \
`$ git pull https://git.openjdk.org/jdk.git pull/14106/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14106`

View PR using the GUI difftool: \
`$ git pr show -t 14106`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14106.diff">https://git.openjdk.org/jdk/pull/14106.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
/label add hotspot-runtime
/label add hotspot-compiler
label add core-libs
/label add client

**Review by azvegint — APPROVED** [review]

**Review by jddarcy — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@azvegint and @jddarcy - Thanks for the fast reviews!

/integrate

**Pull request closed without merging**
