### PR TITLE
8315801: [PPC64] JNI code should be more similar to the Panama implementation

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
This PR removes writing parameters to stack which are passed in registers. (See JBS issue for more details.) This allows us to get rid of the extra parameter for `c_calling_convention`.

We can also remove the extra space for the Parameter Save Area in some ABIv2 cases (ppc64le). Note that JNI and runtime calls don't support VarArgs (except as array object for JNI), so this optimization is valid (unlike in downcalls for Panama).

The offset of floats on stack can be put into a constant and used by interpreter and `c_calling_convention`. Panama handles this in the CallArranger. Added comment which resolves a Panama "todo".

Tests have passed on linux ppc64 and ppc64le and AIX.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315801](https://bugs.openjdk.org/browse/JDK-8315801): [PPC64] JNI code should be more similar to the Panama implementation (**Enhancement** - P4)

### Reviewers
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15599/head:pull/15599` \
`$ git checkout pull/15599`

Update a local copy of the PR: \
`$ git checkout pull/15599` \
`$ git pull https://git.openjdk.org/jdk.git pull/15599/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15599`

View PR using the GUI difftool: \
`$ git pr show -t 15599`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15599.diff">https://git.openjdk.org/jdk/pull/15599.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15599#issuecomment-1709031601)

### CODE REVIEW

**Review by reinrich — COMMENTED** [review]
Hi Martin,

I've only got 2 questions on an outdated version of this pr. They relate to usages of `Argument::float_on_stack_offset_in_bytes_c`.

Thanks, Richard.

**Comment by TheRealMDoerr** [comment]
Right, the float load and store instructions can access a Java frame. That was wrong for linux on PPC64 big endian in the older version of this PR. This is one of the reasons why it's better to compute the precise address in CallArranger.java.

**Comment by reinrich** [comment]
Thanks for explaining!

**Review by reinrich — APPROVED** [review]
Looks good to me.
Thanks, Richard.

**Review by RealLucy — APPROVED** [review]
Changes look good.

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews! I think I can integrate it soon if there are no further comments.

**Pull request closed without merging**
