### PR TITLE
8294959: java.base java.lang.Module uses ASM to load module-info.class

### PR DESCRIPTION
**Pull request by asotona**
java.base java.lang.Module uses ASM to load module-info.class and this patch converts it to use Classfile API.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294959](https://bugs.openjdk.org/browse/JDK-8294959): java.base java.lang.Module uses ASM to load module-info.class

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11367/head:pull/11367` \
`$ git checkout pull/11367`

Update a local copy of the PR: \
`$ git checkout pull/11367` \
`$ git pull https://git.openjdk.org/jdk pull/11367/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11367`

View PR using the GUI difftool: \
`$ git pr show -t 11367`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11367.diff">https://git.openjdk.org/jdk/pull/11367.diff</a>

</details>

### CODE REVIEW

**Review by mlchung — COMMENTED** [review]
This change looks good.

**Review by mlchung — APPROVED** [review]
LGTM

**Comment by eirbjo** [comment]
This PR seems to have broken `make docs`:

```
Generating JDK_API javadoc for 60 modules
src/java.base/share/classes/java/lang/Module.java:1596: error: patterns in switch statements are a preview feature and are disabled by default.
                case AccessFlags af -> clb.withFlags(AccessFlag.INTERFACE,
                     ^
  (use --enable-preview to enable patterns in switch statements)
```

**Comment by asotona** [comment]
> This PR seems to have broken `make docs`

It has been fixed by https://github.com/openjdk/jdk/pull/12957

**Comment by eirbjo** [comment]
> It has been fixed by #12957

🤦

**Pull request closed without merging**
