### PR TITLE
8343344: Windows attach logic failed to handle a failed open on a pipe

### PR DESCRIPTION
**Pull request by alexmenkov**
The fix adds correct handling of "could not open pipe" errors in attach listener instead of assert which causes target VM crash.

testing: tier1,tier2,hs-tier5-svc

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343344](https://bugs.openjdk.org/browse/JDK-8343344): Windows attach logic failed to handle a failed open on a pipe (**Bug** - P4)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21888/head:pull/21888` \
`$ git checkout pull/21888`

Update a local copy of the PR: \
`$ git checkout pull/21888` \
`$ git pull https://git.openjdk.org/jdk.git pull/21888/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21888`

View PR using the GUI difftool: \
`$ git pr show -t 21888`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21888.diff">https://git.openjdk.org/jdk/pull/21888.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21888#issuecomment-2455994302)
</details>

### CODE REVIEW

**Review by kevinjwalls — COMMENTED** [review]
Hi,

List of tests doesn't mention tier4 where the failures were first noticed?


When PipeChannel::open logs error, and returns false, then Win32AttachOperation::open_pipe returns that value, then Win32AttachListener::dequeue() also logs that there was an error?
Is that message just a less detailed duplicate?
(it states whether it's v1 or v2, but maybe that's not that interesting?)

In the v2 case, Win32AttachListener::dequeue()  will log if open succeeded, if !op->read_request().
But AttachOperation::read_request mostly logs its own errors as well.
I think it's only this one:
639     if (buffer_size < 0) {
640       return false;
...where it does not log when returning false. Maybe it should log then, and Win32AttachListener::dequeue() does not need to log?



While are are here, is it possible to address these at the same time?
open/src/hotspot/share/services/attachListener.cpp

typo "ot" -> "or"
631   case ATTACH_API_V2: // <ver>0<size>0<cmd>0<arg>0<arg>0<arg>0
632     if (AttachListener::get_supported_version() < 2) {
633         log_error(attach)("Failed to read request: v2 is unsupported ot disabled"); 

exact -> "exactly"
649     // Must contain exact 'buffer_size' bytes.


Also, is the line 631 comment, with 3 args, misleading? (moving away from exactly 3 arguments...)

Thanks!

**Comment by alexmenkov** [comment]
> List of tests doesn't mention tier4 where the failures were first noticed?

Good point. Run it now, but it takes time to complete.

> When PipeChannel::open logs error, and returns false, then Win32AttachOperation::open_pipe returns that value, then Win32AttachListener::dequeue() also logs that there was an error? Is that message just a less detailed duplicate? (it states whether it's v1 or v2, but maybe that's not that interesting?)
> In the v2 case, Win32AttachListener::dequeue() will log if open succeeded, if !op->read_request(). But AttachOperation::read_request mostly logs its own errors as well. I think it's only this one: 639 if (buffer_size < 0) { 640 return false; ...where it does not log when returning false. Maybe it should log then, and Win32AttachListener::dequeue() does not need to log?

Ok, done.
Also added error logging in PipeChannel:: read and write (AttachOperation::read_request_data does not logs IO errors)

> While are are here, is it possible to address these at the same time? open/src/hotspot/share/services/attachListener.cpp
> typo "ot" -> "or" 631 case ATTACH_API_V2: // 000000 632 if (AttachListener::get_supported_version() < 2) { 633 log_error(attach)("Failed to read request: v2 is unsupported ot disabled");

Fixed.

> exact -> "exactly" 649 // Must contain exact 'buffer_size' bytes.

Fixed.


> Also, is the line 631 comment, with 3 args, misleading? (moving away from exactly 3 arguments...)

Fixed.

**Review by kevinjwalls — APPROVED** [review]
Thanks Alex, looks good.

**Review by plummercj — APPROVED** [review]
Looks good.

**Pull request closed without merging**
