### PR TITLE
8293098: GHA: Harmonize GCC version handling for host and cross builds

### PR DESCRIPTION
**Pull request by shipilev**
Caught this headache while trying to bump to Ubuntu 22.04, which required touching way too many surprising places. 

Current GHA scripts define `apt-gcc-version` a bit weirdly: host and cross builds version differ in carrying the "gcc-major-version" inside of it. That is, "host" builds do `apt-gcc-version: '10=10.3.0-1ubuntu1~20.04'`, while cross builds do `apt-gcc-version: default: '10.3.0-1ubuntu1~20.04'`

I propose we harmonize these to simplify GCC updates: split out the `gcc-major-version` for host builds, and pull the versions from cross builds into `main`, where all other versions belong. Additionally, this handles the x86_32 case that requires "-multilib" package, which is currently hacked through the "version" string.

Additional testing:
 - [ ] GHA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293098](https://bugs.openjdk.org/browse/JDK-8293098): GHA: Harmonize GCC version handling for host and cross builds

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10083/head:pull/10083` \
`$ git checkout pull/10083`

Update a local copy of the PR: \
`$ git checkout pull/10083` \
`$ git pull https://git.openjdk.org/jdk pull/10083/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10083`

View PR using the GUI difftool: \
`$ git pr show -t 10083`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10083.diff">https://git.openjdk.org/jdk/pull/10083.diff</a>

</details>

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Seems like a good cleanup. I never fully got to the end of making this part nice when I rewrote the GHA script.

If you want to unify this even more, I think (iirc) that it possible to e.g. set a top-level `env` section defining the gcc version we use, and reference it in the `jobs:*:with` sections.

**Comment by magicus** [comment]
> I would prefer to do it later, as there are dependent PRs riding on this one, and testing takes quite a while...

That's up to you. I'm okay with this change as-is.

**Review by RealCLanger — APPROVED** [review]
Looks good. Nice cleanup.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
