### PR TITLE
8318528: Rename TestUnstructuredLocking test

### PR DESCRIPTION
**Pull request by shipilev**
Low-priority house-keeping. See the rationale in the bug.

Additional testing:
 - [x] macos-aarch64-server-fastdebug, affected test passes

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318528](https://bugs.openjdk.org/browse/JDK-8318528): Rename TestUnstructuredLocking test (**Enhancement** - P5)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [d820bd4a](https://git.openjdk.org/jdk/pull/16273/files/d820bd4a0fb197d2410414dc89195c975a4e6e82)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16273/head:pull/16273` \
`$ git checkout pull/16273`

Update a local copy of the PR: \
`$ git checkout pull/16273` \
`$ git pull https://git.openjdk.org/jdk.git pull/16273/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16273`

View PR using the GUI difftool: \
`$ git pr show -t 16273`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16273.diff">https://git.openjdk.org/jdk/pull/16273.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16273#issuecomment-1771502850)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Trivial.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
"unbalanced" is not right here either IMO but it depends on how you define it. To me balanced locking is the same as structured locking as defined by JVMS: number of locks == number of unlocks by the end of the method (they are balanced), and you have to have a lock preceding each unlock.

I would have used unstructured locking to describe this test case because it does not follow the block-structure imposed by the Java language - hence is unstructured.

The locking pattern of `lock(A)->lock(B)->unlock(A)->unlock(B)` is known as chained-locking, or hand-over-hand locking in the literature.

I guess the test could be called  `TestOutOfOrderUnlocking` as that is what is actually tests.

**Comment by shipilev** [comment]
> I guess the test could be called `TestOutOfOrderUnlocking` as that is what is actually tests.

Yeah, we can do that, see new commit. I am fine with any name that does not mention "structured locking" :)

**Comment by dholmes-ora** [comment]
It is out-of-order un-locking not locking though.

**Comment by shipilev** [comment]
> It is out-of-order un-locking not locking though.

Gah. Okay, renamed!

**Review by dholmes-ora — APPROVED** [review]
Thank you.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
