### PR TITLE
dummy: fix 'objectmonitor' -> 'ObjectMonitor' typos.

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Test pull request that I'm planning to delete if I can figure out how to do that.

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
The auto-close since the repo is a read-only mirror is cool. I did expect _something_ to squawk at me since I submitted a changeset comment that would not pass jcheck:

dummy: fix 'objectmonitor' -> 'ObjectMonitor' typos.

but that didn't happen. Is this something that would have happened if the destination repo was actually live?

**Comment by kevinrushforth** [comment]
When the Skara PR bot runs `jcheck` it doesn't check the commit message (doesn't care). What it would have complained about was the fact that your PR title didn't start with a Bug ID.

**Comment by dcubed-ojdk** [comment]
So the Skara PR bot would have rejected the pull request due to the bad title which is the same as the first line of (old style) commit message right? (Just trying to understand how the new thing works)...

**Comment by kevinrushforth** [comment]
Yes, the PR title is what will be used as the first line of the commit. Btw, it wouldn't have actually rejected it, it would just have noted that it didn't have a proper issue ID, so no rfr yet.

**Comment by kevinrushforth** [comment]
Here is an example of one without a valid subject:
https://github.com/openjdk/jfx/pull/185

Here is one with a valid subject for comparison:
https://github.com/openjdk/jfx/pull/288

**Comment by Titaniumtown** [comment]
Hello, I don't really know where to put this, besides https://bugreport.java.com/bugreport/ but that says ``` This page is for reporting bugs in implementations of the Java Platform, Standard Edition, as distributed on the Java Development Kit Builds page ``` but my bug is about failing to build openjdk, which doesn't seem to apply. I run a repository for Arch Linux Arm focused towards the Raspberry Pi 4 aarch64 kernel builds (which aren't officially supported, but works fine). I also provide a package for openjdk 15 and the HEAD of openjdk (atm openjdk 16).

I've been encountering some issue building openjdk 16 lately (for a few days) where I get the error: 
```
Building targets 'images legacy-jre-image' in configuration 'linux-aarch64-server-release'
Creating support/modules_libs/java.base/server/libjvm.so from 1004 file(s)
/mnt/hdd/raspi4_pkgbuilds/java-openjdk-git/src/jdk/src/java.base/share/classes/java/lang/Double.java:104: error: floating point number too small
    public static final double MIN_VALUE = 0x0.0000000000001P-1022; // 4.9e-324
                                           ^
/mnt/hdd/raspi4_pkgbuilds/java-openjdk-git/src/jdk/src/java.base/share/classes/java/lang/Float.java:101: error: floating point number too small
    public static final float MIN_VALUE = 0x0.000002P-126f; // 1.4e-45f
```
The bug is reproducible with openjdk 16 being the bootjdk, openjdk 14 as the boot jdk compiles fine.
I don't know were else to report it because the official bug report page is about the distributed builds, and not errors while compiling it.

I know commenting on a PR to ask for help/report a bug isn't what you're supposed to do, but I don't really know where else to put this. If there's a better place for me to report this, please tell me. If there isn't a better place to report it (there probably is), maybe a blank github repo could be created to report bugs that don't fall under the umbrella of those terms on https://bugreport.java.com/bugreport
Thanks!

**Comment by Titaniumtown** [comment]
Anyone know where I can properly report that error?

**Pull request closed without merging**
