### PR TITLE
8266957: SA has not followed JDK-8220587 and JDK-8224965

### PR DESCRIPTION
**Pull request by YaSuenag**
Following jtreg tests for SA would fail because SA has not followed [JDK-8220587](https://bugs.openjdk.java.net/browse/JDK-8220587) and [JDK-8224965](https://bugs.openjdk.java.net/browse/JDK-8224965).

* serviceability/sa/ClhsdbDumpheap.java
* serviceability/sa/ClhsdbFindPC.java
* serviceability/sa/ClhsdbInspect.java
* serviceability/sa/ClhsdbSymbol.java
* serviceability/sa/TestHeapDumpForInvokeDynamic.java
* serviceability/sa/TestJmapCore.java
* serviceability/sa/TestJmapCoreMetaspace.java

They need to handle relocated objects and/or live regions (pages). SA should handle them.

This change passes serviceability/sa jtreg tests on Linux x64 with -vmoption:-XX:+UseZGC, but I want to know this change works fine on testbed for ZGC in Oracle. Could you help?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266957](https://bugs.openjdk.java.net/browse/JDK-8266957): SA has not followed JDK-8220587 and JDK-8224965

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4057/head:pull/4057` \
`$ git checkout pull/4057`

Update a local copy of the PR: \
`$ git checkout pull/4057` \
`$ git pull https://git.openjdk.java.net/jdk pull/4057/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4057`

View PR using the GUI difftool: \
`$ git pr show -t 4057`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4057.diff">https://git.openjdk.java.net/jdk/pull/4057.diff</a>

</details>

### CODE REVIEW

**Comment by YaSuenag** [comment]
Ping: could you review this change?
I know this is too big to review, so it is also welcome to comment to divide this PR.

This PR would fix [JDK-8267045](https://bugs.openjdk.java.net/browse/JDK-8267045) which is marked as P3. If we can mark P3 to this PR, we can get more time to review.
I think SA should support ZGC as possible in next major release.

**Review by plummercj — APPROVED** [review]

**Comment by YaSuenag** [comment]
Thanks @plummercj for the review!
May I get the review from ZGC folks?

**Comment by plummercj** [comment]
>  May I get the review from ZGC folks?

The ZGC team won't be doing SA code reviews. I'll have someone else from the svc team do a second review, but keep in mind these reviews are primarily just to make sure the changes won't break anything (other than SA support for ZGC).

**Review by sspitsyn — APPROVED** [review]
Hi Yasumasa,
This looks okay to me.
Thanks,
Serguei

**Pull request closed without merging**
