### PR TITLE
8255208: CodeStrings passed to Disassembler::decode are ignored

### PR DESCRIPTION
**Pull request by cl4es**
CodeStrings passed directly to Disassembler::decode are wrongly ignored.

This patch started out as a cleanup to clean out CodeStrings, but I realized as I was about to remove the suspiciously unused CodeStrings in the disassembler that them being unused was likely a bug.

For example, -XX:+PrintInterpreter (on debug builds) included messages which can help digesting the output (if not else by emitting text hooks to the place in the source code where the asm is generated):

```
  0x00007f1f7093becb: je 0x00007f1f7093bee5
 ;; call_VM_base: heap base corrupted?                                <<< omitted
  0x00007f1f7093bed1: mov $0x7f1f90c7ecb8,%rdi
  0x00007f1f7093bedb: and $0xfffffffffffffff0,%rsp
  0x00007f1f7093bedf: callq 0x00007f1f9046c0a0 = MacroAssembler::debug64(char*, long, long*) 
```

While PrintInterpreter is the only case that appears directly affected, restoring this capability seems useful in general.

The cleaning up of the code also has some nice side-effects such as reducing the size of a CodeBuffer from 432 to 408 bytes and marginally improving the static size of the JVM (as measured on linux-x64)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (hs/tier1 compiler)](https://github.com/cl4es/jdk/runs/1290119343)

### Issue
 * [JDK-8255208](https://bugs.openjdk.java.net/browse/JDK-8255208): CodeStrings passed to Disassembler::decode are ignored

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/788/head:pull/788`
`$ git checkout pull/788`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
very nice clean up

**Comment by cl4es** [comment]
> very nice clean up

Thanks!

**Review by iklam — APPROVED** [review]
LGTM

**Comment by cl4es** [comment]
@vnkozlov @iklam - thank you for reviewing!

/integrate

**Pull request closed without merging**
