### PR TITLE
8327499: MethodHandleStatics.traceLambdaForm includes methods that cannot be generated

### PR DESCRIPTION
**Pull request by liach**
GenerateJLIClassesHelper has been making wrong assumptions about Invoker's LambdaForm method type parameters. Since they are distinct from those of Linkers, they are now tracked and generated separately. It seems that no proper invoker was ever generated before, except it happens that most invoker signatures can be taken as linker signature so we never detected it.

Requesting @iklam for a review; since I don't know how to deal with CDS, I have to relay to someone else to ensure this fixes the problem from the CDS side as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327499](https://bugs.openjdk.org/browse/JDK-8327499): MethodHandleStatics.traceLambdaForm includes methods that cannot be generated (**Bug** - P4)

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19164/head:pull/19164` \
`$ git checkout pull/19164`

Update a local copy of the PR: \
`$ git checkout pull/19164` \
`$ git pull https://git.openjdk.org/jdk.git pull/19164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19164`

View PR using the GUI difftool: \
`$ git pr show -t 19164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19164.diff">https://git.openjdk.org/jdk/pull/19164.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19164#issuecomment-2103659866)

### CODE REVIEW

**Comment by iklam** [comment]
pinging @cl4es 

@liach, could you add a jtreg test case? I think you can use https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/runtime/cds/appcds/dynamicArchive/CDSLambdaInvoker.java

**Comment by liach** [comment]
@iklam I have expanded the given case and it passes on my device locally. Since CDS doesn't have an easy way to find out the methods archived in a class, I resorted to enabling invoke's logging and checking the resolution output instead. Does this approach look good?

**Review by iklam — APPROVED** [review]
Looks good to me. Thanks for adding the CDS test.

**Comment by liach** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
