### PR TITLE
8255617: Zero: purge the remaining bytecode interpreter profiling support

### PR DESCRIPTION
**Pull request by shipilev**
All the stubs in `interpreter/zero/bytecodeInterpreterProfiling.hpp` are empty. History shows the whole thing gradually moved to template interpreter. We can probably simplify Zero code by dropping these empty stubs altogether. Arguably, this makes porting to new architectures a bit harder, but it seems that the proper stepping stone after Zero is implementing template interpreter anyway.

On my TR 3970X, this improves:
 - Linux x86_64 Zero "make images" times from ~18 minutes to ~17.5 minutes

I would like to have the opinion of @GoeLin who added this for PPC64 porting back in 8u. And probably @DamonFool who is usually interested in Zero. And @jerboaa, @gnu-andrew who deal with Zero from time to time.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255617](https://bugs.openjdk.java.net/browse/JDK-8255617): Zero: purge the remaining bytecode interpreter profiling support

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to 2bcc4e31aa53d17c23e4e78a4ac0517c951da7ab
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/944/head:pull/944`
`$ git checkout pull/944`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
I left this code from the C++ interpreter because I had a dream that we could someday hook zero up to c1/c2 someday, but if so, there would be a more work than adding these back.  I'd be interested to see what these other people with interest in Zero think.  But this LGTM.

**Comment by shipilev** [comment]
> I left this code from the C++ interpreter because I had a dream that we could someday hook zero up to c1/c2 someday, but if so, there would be a more work than adding these back. I'd be interested to see what these other people with interest in Zero think. But this LGTM.

It is my understanding that Zero had basically backed off to be the "pure" interpreter without any support for compilers, and thus the most portable thing, for example for architectures that have no compiler ports whatsoever. Template interpreter seems to be the thing that hooks up in C1/C2. So, porting is basically: a) get Zero buildable and executable, work out class library problems; b) get template interpreter working; c) get C1 working; d) get C2 working. 

So in this sense, getting compiler hooks (like this interpreter profile support) penalizes Zero execution for nothing. If that continues, I'd say we can also purge deopt support from Zero. 

Need more thoughts about this, so:

/reviewers 3

**Comment by shipilev** [comment]
@DamonFool, @GoeLin, do you have an opinion here?

**Comment by DamonFool** [comment]
> @DamonFool, @GoeLin, do you have an opinion here?

Hi @shipilev ，

Sorry, I missed this PR before.
I'll have a look and do some experiments and will let you know soon.

Thanks.

**Comment by DamonFool** [comment]
> > I left this code from the C++ interpreter because I had a dream that we could someday hook zero up to c1/c2 someday, but if so, there would be a more work than adding these back. I'd be interested to see what these other people with interest in Zero think. But this LGTM.
> 
> It is my understanding that Zero had basically stepped back to be the "pure" interpreter without any support for compilers, and thus becoming the most portable thing, for example for architectures that have no arch-specific code implemented whatsoever. When one needs an interpreter that hooks into C1/C2, they have to go to template interpreter and start implementing arch-specific stuff. So, porting is basically: a) get Zero working; b) get template interpreter working; c) get C1 working; d) get C2 working. On each of these steps you have something that works, with every step much harder to get it right, but better for performance.
> 
> So in this sense, having compiler hooks (like this interpreter profile support) penalizes Zero execution for nothing. If we continue it further, I'd say we can also purge deopt support from Zero too.
> 
> Need more thoughts about this, so:
> 
> /reviewers 3

+1

All tests for Zero VM passed in our CI/CD.
And the build time for zero-release vm reduced 20s ~ 30s on our platforms.
Thanks.

**Review by DamonFool — APPROVED** [review]

**Comment by shipilev** [comment]
I also figured we don't need `mdx` field in `BytecodeInterpreter` now. Removed. Plus a few comments/variables removed. Please take a look again, if you can.

**Review by DamonFool — APPROVED** [review]
Still looks good.

**Review by coleenp — APPROVED** [review]
Still looks good.

**Comment by shipilev** [comment]
Thanks folks!

/integrate

**Pull request closed without merging**
