### PR TITLE
8330569: Rename Nix to Posix in platform-dependent attachListener code

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

Revert the rename performed in 8324683.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330569](https://bugs.openjdk.org/browse/JDK-8330569): Rename Nix to Posix in platform-dependent attachListener code (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18836/head:pull/18836` \
`$ git checkout pull/18836`

Update a local copy of the PR: \
`$ git checkout pull/18836` \
`$ git pull https://git.openjdk.org/jdk.git pull/18836/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18836`

View PR using the GUI difftool: \
`$ git pr show -t 18836`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18836.diff">https://git.openjdk.org/jdk/pull/18836.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18836#issuecomment-2063691576)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. In the long term, I'd prefer to switch to _unix as suggested by https://github.com/openjdk/jdk/pull/18283#issuecomment-2063523915

**Review by tstuefe — APPROVED** [review]
Good and trivial. 

I prefer Posix to Unix.

**Review by coleenp — APPROVED** [review]
Looks good!

**Comment by jdksjolen** [comment]
Thanks.

/merge

**Comment by jdksjolen** [comment]
/integrate

Of course.

**Pull request closed without merging**
