### PR TITLE
8267166: Remove test file vmTestbase/vm/mlvm/tools/LoadClass.java

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small change to remove unused LoadClass.java and remove comments that reference it.  Mach5 tiers 1-3 were run to sanity check that LoadClass.java is not used.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267166](https://bugs.openjdk.java.net/browse/JDK-8267166): Remove test file vmTestbase/vm/mlvm/tools/LoadClass.java

### Reviewers
 * [Gerard Ziemski](https://openjdk.java.net/census#gziemski) (@gerard-ziemski - Committer)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4059/head:pull/4059` \
`$ git checkout pull/4059`

Update a local copy of the PR: \
`$ git checkout pull/4059` \
`$ git pull https://git.openjdk.java.net/jdk pull/4059/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4059`

View PR using the GUI difftool: \
`$ git pr show -t 4059`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4059.diff">https://git.openjdk.java.net/jdk/pull/4059.diff</a>

</details>

### CODE REVIEW

**Review by gerard-ziemski — APPROVED** [review]
I grepped `test/hotspot` for **LoadClass** and I think that you got them all, thanks!

**Review by coleenp — APPROVED** [review]
Looks good plus trivial to check in.

**Comment by hseigel** [comment]
Thanks Gerard and Coleen for reviewing this!

/integrate

**Pull request closed without merging**
