### PR TITLE
8279043: Some Security Exception Messages Miss Spaces

### PR DESCRIPTION
**Pull request by djelinski**
Trivial change. Issue reported by [lgtm.com](https://lgtm.com/projects/g/openjdk/jdk/alerts/?mode=tree&lang=java&ruleFocus=1952840153).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279043](https://bugs.openjdk.java.net/browse/JDK-8279043): Some Security Exception Messages Miss Spaces

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6894/head:pull/6894` \
`$ git checkout pull/6894`

Update a local copy of the PR: \
`$ git checkout pull/6894` \
`$ git pull https://git.openjdk.java.net/jdk pull/6894/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6894`

View PR using the GUI difftool: \
`$ git pr show -t 6894`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6894.diff">https://git.openjdk.java.net/jdk/pull/6894.diff</a>

</details>

### CODE REVIEW

**Review by wangweij — APPROVED** [review]
Change looks good. Please add a colon after the bug ID in the title. Otherwise Skara might not integrate it.

**Comment by djelinski** [comment]
Thanks! bug title fixed.

/integrate

**Comment by wangweij** [comment]
Thanks. I'll run some tests before sponsoring it. Hopefully no one uses the exact exception message as a golden copy.

**Pull request closed without merging**
