### PR TITLE
8261154: Memory leak in Java_java_lang_ClassLoader_defineClass0 with long class names

### PR DESCRIPTION
**Pull request by cl4es**
This patch resolves a potential memory leak in Java_java_lang_ClassLoader_defineClass0

I've not figured a good way to write a regression test. A crude way to manually verify the leak and the fix is provided by the added microbenchmark that triggers the malloc in ClassLoader.c and the associated leak.

E.g., running this with `/usr/bin/time -v $BUILD_DIR/images/jdk/bin/java -Xmx256m -jar $BUILD_DIR/images/test/micro/benchmarks.jar LookupDef.*WeakClass.loadLong -f 0 -i  N | grep "Maximum resident set"` yields:

```
Baseline:
N = 20     Maximum resident set size (kbytes): 544860
N = 50     Maximum resident set size (kbytes): 818532
N = 100    Maximum resident set size (kbytes): 1388560
N = 200    Maximum resident set size (kbytes): 2124296
Patch:
N = 20     Maximum resident set size (kbytes): 480476
N = 50     Maximum resident set size (kbytes): 764040
N = 100    Maximum resident set size (kbytes): 782920
N = 200    Maximum resident set size (kbytes): 921272
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261154](https://bugs.openjdk.java.net/browse/JDK-8261154): Memory leak in Java_java_lang_ClassLoader_defineClass0 with long class names

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2407/head:pull/2407`
`$ git checkout pull/2407`

### CODE REVIEW

**Review by tstuefe — COMMENTED** [review]
Hi Cleas,

looks good but why changing the the NULL comparisons? 

If you wanted to simplify you could completely omit the NULL checks since free(NULL) is a noop. And potentially merge the labels - where there are two - into one.

Cheers, Thomas

**Comment by cl4es** [comment]
I'm not sure every platform have always agreed free(NULL) is a noop. I suspect all the currently supported ones do, though?

**Comment by tstuefe** [comment]
> I'm not sure every platform have always agreed free(NULL) is a noop. I suspect all the currently supported ones do, though?

Its standard behavior.

Posix: https://pubs.opengroup.org/onlinepubs/009695399/functions/free.html "If ptr is a null pointer, no action shall occur. "
Windows: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/free?view=msvc-160 " If memblock is NULL, the pointer is ignored and free immediately returns. "

So it should be okay.

**Comment by cl4es** [comment]
Right. I dialed back the changes here since this is a bug fix that should be kept minimal. I have another change in the pipeline that will touch code here that can double down on cleaning up.

**Review by ChrisHegarty — APPROVED** [review]
LGTM.

**Review by tstuefe — APPROVED** [review]
Looks good!

**Review by mlchung — APPROVED** [review]
Looks good.  Thanks for fixing this.

**Comment by cl4es** [comment]
@tstuefe, @ChrisHegarty, @mlchung - thanks for reviewing!

/integrate

**Pull request closed without merging**
