### PR TITLE
8336499: Failure when creating non-CRT RSA private keys in SunPKCS11

### PR DESCRIPTION
**Pull request by martinuy**
Hi,

I'd like to make a proposal to fix [JDK-8336499](https://bugs.openjdk.org/browse/JDK-8336499).

With the proposed change, a non-sensitive RSA private key is first interpreted as a CRT key. If that fails (e.g. one of the attributes is not available), a second attempt is made to interpret the key as a non-CRT key. In this second attempt, only the required attributes (`CKA_MODULUS` and `CKA_PRIVATE_EXPONENT`) are queried. If this still fails, the key is handled as an opaque key. Most non-sensitive key cases will require a single query, retaining the performance improvement made in [8271566](https://bugs.openjdk.org/browse/JDK-8271566). No changes were made to sensitive keys: they are still handled as opaque keys.

No regressions observed in `jdk/sun/security/pkcs11`.

As explained in a [JBS comment](https://bugs.openjdk.org/browse/JDK-8336499?focusedId=14690278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14690278), a regression test for this fix is not easy because the NSS Software Token cannot create non-CRT RSA private keys without a `CKA_PUBLIC_EXPONENT` (as required by the PKCS 11 standard v2.40 and above). A call to `P11RSAKeyFactory::generatePrivate` would fail and the key is never wrapped in a `P11Key` object. A PKCS 11 library implementing a standard previous to 2.40 would be required. With that said, I manually exercised the `asNonCRT` path in the proposed change by using a CRT key and forcing `asCRT` to fail with the debugger.

Thanks,
Martin.-

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336499](https://bugs.openjdk.org/browse/JDK-8336499): Failure when creating non-CRT RSA private keys in SunPKCS11 (**Bug** - P4)

### Reviewers
 * [Francisco Ferrari Bihurriet](https://openjdk.org/census#fferrari) (@franferrax - Author)
 * [Valerie Peng](https://openjdk.org/census#valeriep) (@valeriepeng - **Reviewer**)

### Contributors
 * Francisco Ferrari Bihurriet `<fferrari@openjdk.org>`
 * Martin Balao `<mbalao@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20204/head:pull/20204` \
`$ git checkout pull/20204`

Update a local copy of the PR: \
`$ git checkout pull/20204` \
`$ git pull https://git.openjdk.org/jdk.git pull/20204/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20204`

View PR using the GUI difftool: \
`$ git pr show -t 20204`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20204.diff">https://git.openjdk.org/jdk/pull/20204.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20204#issuecomment-2232039223)

### CODE REVIEW

**Comment by martinuy** [comment]
Pushed a minor refactoring and simplification suggestion made by @franferrax .

**Review by franferrax — APPROVED** [review]
Looks good to me.

**Comment by valeriepeng** [comment]
I will take a look as well.

**Review by valeriepeng — APPROVED** [review]
Looks good. Thanks~

**Pull request closed without merging**
