### PR TITLE
8295382: Implement SHA-256 Intrinsic on RISC-V

### PR DESCRIPTION
**Pull request by luhenry**
This has been tested with patches currently being submitted to QEMU to add support for Zvkb and Zvknha extensions.

The documentation for the Vector Crypto extension's instructions is available at https://github.com/riscv/riscv-crypto/tree/master/doc/vector/insns

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295382](https://bugs.openjdk.org/browse/JDK-8295382): Implement SHA-256 Intrinsic on RISC-V

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12208/head:pull/12208` \
`$ git checkout pull/12208`

Update a local copy of the PR: \
`$ git checkout pull/12208` \
`$ git pull https://git.openjdk.org/jdk.git pull/12208/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12208`

View PR using the GUI difftool: \
`$ git pr show -t 12208`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12208.diff">https://git.openjdk.org/jdk/pull/12208.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12208#issuecomment-1404465986)

### CODE REVIEW

**Comment by RealFYang** [comment]
But looks like this extension is still in Draft status? We should only consider RISC-V extensions that are at least in the Ratified status as extensions in Draft status are expected to change before ratification.

**Comment by VladimirKempik** [comment]
> But looks like this extension is still in draft status? We should only consider using RISC-V extensions that are at least in the ratified status. Extensions in draft status are expected to change before ratification. 

I agree with @RealFYang. 
This is good and needed patch, just a little too early.

**Comment by luhenry** [comment]
Agreed that it's still draft. It's getting really close to being ratified (the 45 days period was triggered between December and early January) and there is no expected changes. Happy to let this PR sit idle until it's fully ratified.

I've prepared patches for SHA-512 as well, and currently working on AES instrinsics.

Also, this is targeting vector crypto but not scalar crypto. We should support both given vector crypto is targeting larger machines.

**Comment by RealFYang** [comment]
@luhenry : Hi, that's great to hear! I am happy to take another look once it's ratified. Also, thanks for sharing your work update!

**Comment by VladimirKempik** [comment]
Looks like the extension was ratofoed recently, Ludovic, do you plan to return to these intrisics ?

**Comment by luhenry** [comment]
@VladimirKempik yes, I saw that as well. Planning to get back to it by end of month (this one and sha512).

**Pull request closed without merging**
