### PR TITLE
8267153: Problemlist jdk/jfr/event/gc/collection/TestG1ParallelPhases.java to remove the noise from CI 

### PR DESCRIPTION
**Pull request by tschatzl**
Hi,
  can I have reviews for this small change that problemlists jdk/jfr/event/gc/collection/TestG1ParallelPhases.java to remove noise from the CI.

Thanks,
  Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267153](https://bugs.openjdk.java.net/browse/JDK-8267153): Problemlist jdk/jfr/event/gc/collection/TestG1ParallelPhases.java to remove the noise from CI

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4031/head:pull/4031` \
`$ git checkout pull/4031`

Update a local copy of the PR: \
`$ git checkout pull/4031` \
`$ git pull https://git.openjdk.java.net/jdk pull/4031/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4031`

View PR using the GUI difftool: \
`$ git pr show -t 4031`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4031.diff">https://git.openjdk.java.net/jdk/pull/4031.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This is a trivial fix.

**Review by DamonFool — APPROVED** [review]

**Comment by dholmes-ora** [comment]
JDK-8267218 is also now filed against this test.

**Pull request closed without merging**
