### PR TITLE
8263167: IGV: build fails with "taskdef AutoUpdate cannot be found"

### PR DESCRIPTION
**Pull request by robcasloz**
As part of the [recent transition](https://netbeans.apache.org/about/oracle-transition.html) of the NetBeans project to the Apache fundation, [http://bits.netbeans.org](http://bits.netbeans.org) has stopped serving the `tasks.jar` file used to download IGV's build dependencies. This change updates the IGV build configuration to use the [nbm-maven-harness](https://mvnrepository.com/artifact/org.codehaus.mojo/nbm-maven-harness) Maven artifact instead, which provides the same functionality.

Tested manually on linux-x64.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263167](https://bugs.openjdk.java.net/browse/JDK-8263167): IGV: build fails with "taskdef AutoUpdate cannot be found"

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2869/head:pull/2869`
`$ git checkout pull/2869`

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good! On my machine, I first had to delete the old `tasks.jar` in order to build again:

```
$ ant build
Buildfile: /home/christian/valhalla/open/src/utils/IdealGraphVisualizer/build.xml

download:
     [echo] Downloading clusters ide|platform
      [get] Getting: https://repo.maven.apache.org/maven2/org/codehaus/mojo/nbm-maven-harness/7.4/nbm-maven-harness-7.4.jar
      [get] To: /tmp/tasks.jar
      [get] local file date : Fri Mar 05 06:41:46 CET 2021
      [get] Not modified - so not downloaded

BUILD FAILED
/home/christian/valhalla/open/src/utils/IdealGraphVisualizer/build.xml:7: The following error occurred while executing this line:
/home/christian/valhalla/open/src/utils/IdealGraphVisualizer/nbproject/build-impl.xml:41: The following error occurred while executing this line:
/home/christian/valhalla/open/src/utils/IdealGraphVisualizer/nbproject/platform.xml:28: taskdef class org.netbeans.nbbuild.AutoUpdate cannot be found
 using the classloader AntClassLoader[/tmp/tasks.jar]

$ rm /tmp/tasks.jar
$ ant build
....
BUILD SUCCESSFUL
Total time: 3 minutes 53 seconds
```

After deleting `/tmp/tasks.jar`, it took some time to download everything but the build worked again.

**Comment by robcasloz** [comment]
> Looks good!

Thanks for reviewing, Christian!

> On my machine, I first had to delete the old `tasks.jar` in order to build again:

Thanks, I made a comment about that in the JBS report.

**Review by reinrich — APPROVED** [review]
Looks good. I've tested the change on Linux x86_64. I also had to remove /tmp/tasks.jar but then the build succeeded.

Thanks for fixing!

**Comment by robcasloz** [comment]
> Looks good. I've tested the change on Linux x86_64. I also had to remove /tmp/tasks.jar but then the build succeeded.
> 
> Thanks for fixing!

Thanks for reviewing, Richard.

**Comment by robcasloz** [comment]
/summary
Update IGV build configuration to use the nbm-maven-harness Maven artifact.

**Pull request closed without merging**
