### PR TITLE
8264396: Use the blessed modifier order in jdk.internal.jvmstat

### PR DESCRIPTION
**Pull request by alblue**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264396](https://bugs.openjdk.java.net/browse/JDK-8264396): Use the blessed modifier order in jdk.internal.jvmstat

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to 0583ebcc5c00c4e6d2bf602013c5b27effd137c5
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3252/head:pull/3252` \
`$ git checkout pull/3252`

Update a local copy of the PR: \
`$ git checkout pull/3252` \
`$ git pull https://git.openjdk.java.net/jdk pull/3252/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3252`

View PR using the GUI difftool: \
`$ git pr show -t 3252`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3252.diff">https://git.openjdk.java.net/jdk/pull/3252.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — CHANGES_REQUESTED** [review]
The changes look fine, but you need to fix the CR number. It should be JDK-8264396. Also copyrights need updating.

**Review by kevinjwalls — APPROVED** [review]
Agreed, change looks good.

**Review by shipilev — APPROVED** [review]
Looks fine to me as well.

**Comment by alblue** [comment]
Going to upstream this patch into opendjk/panama-foreign

**Comment by alblue** [comment]
Sorry, closed the wrong PR. This one should be good to go 🙄

**Review by plummercj — APPROVED** [review]

**Pull request closed without merging**
