### PR TITLE
8282008: Incorrect handling of quoted arguments in ProcessBuilder

### PR DESCRIPTION
**Pull request by omikhaltsova**
This fix made equal processing of strings such as "\"C:\\Program Files\\Git\\\"" before and after JDK-8250568.

For example, it's needed to execute the following command on Windows:
`C:\Windows\SysWOW64\WScript.exe "MyVB.vbs" "C:\Program Files\Git\" "Test"`
it's equal to:
`new ProcessBuilder("C:\\Windows\\SysWOW64\\WScript.exe", "MyVB.vbs", "\"C:\\Program Files\\Git\\\"", "Test").start();`

While processing, the 3rd argument "\"C:\\Program Files\\Git\\\"" treated as unquoted due to the condition added in JDK-8250568.
```
    private static String unQuote(String str) {
    .. 
       if (str.endsWith("\\\"")) {
            return str;    // not properly quoted, treat as unquoted
        }
    ..
    }

```
that leads to the additional surrounding by quotes in ProcessImpl::createCommandLine(..) because needsEscaping(..) returns true due to the space inside the string argument.
As a result the native function CreateProcessW (src/java.base/windows/native/libjava/ProcessImpl_md.c) gets the incorrectly quoted argument: 
```
pcmd = C:\Windows\SysWOW64\WScript.exe MyVB.vbs ""C:\Program Files\Git\"" Test
(jdk.lang.Process.allowAmbiguousCommands = true)
pcmd = "C:\Windows\SysWOW64\WScript.exe" MyVB.vbs "\"C:\Program Files\Git\\\"" Test
(jdk.lang.Process.allowAmbiguousCommands = false)
```

Obviously, a string ending with `"\\\""` must not be started with `"\""` to treat as unquoted overwise it’s should be treated as properly quoted.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8282008](https://bugs.openjdk.java.net/browse/JDK-8282008): Incorrect handling of quoted arguments in ProcessBuilder

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7504/head:pull/7504` \
`$ git checkout pull/7504`

Update a local copy of the PR: \
`$ git checkout pull/7504` \
`$ git pull https://git.openjdk.java.net/jdk pull/7504/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7504`

View PR using the GUI difftool: \
`$ git pr show -t 7504`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7504.diff">https://git.openjdk.java.net/jdk/pull/7504.diff</a>

</details>

### CODE REVIEW

**Comment by RogerRiggs** [comment]
The fix looks right. 
The PR should include a test.  Can you write a standalone test in jdk/test/java/lang/ProcessBuilder/... to confirm the fix.
Possibly it could be added to Basic.java but that file is pretty large and doesn't seem like the correct place to add.
It may be sufficient to invoke echo with that 3rd argument and verify the output.

**Comment by omikhaltsova** [comment]
Roger, thanks for your comments! But in this case how it is possible to present a path ending with '\\' and including a space inside?

**Comment by RogerRiggs** [comment]
Please close this PR; the proposed change to the application should resolve the issue.
The issue should be closed as "not-an-issue".

**Comment by omikhaltsova** [comment]
Roger, writing a test via echo was not a good idea obviously for this particular case because of the fact well shown in the doc "4. Everyone Parses Differently", https://daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULESMSEX. The task is more complicated than it seems at the first glance. The same command line correctly parsed in an app written in C/C++ might be incorrectly parsed in a VBS app etc. 

The suggestion not to use the path-argument surroundings with `'\"'` doesn't fix the issue in case of VBS. It leads to a resulting path-argument ending with the doubled backslash in a VBS app according to the rules "10.1 The WSH Command Line Parameter Parsing Rules", https://daviddeley.com/autohotkey/parameters/parameters.htm#WSH.

Below there are some experiments with an app attached to JDK-8282008: 

NO FIX
```
1. new ProcessBuilder("C:\\Windows\\SysWOW64\\WScript.exe", "MyVB.vbs", "\"C:\\Program Files\\Git\\\"", "Test").start();

1.1 allowAmbiguousCommands = false
   arg[0] = \C:\Program 
   arg[1] = Files\Git1\\\  
CreateProcessW: pcmd = "C:\Windows\SysWOW64\WScript.exe" MyVB.vbs "\"C:\Program Files\Git1\\\"" Test   

1.2 allowAmbiguousCommands = true
   arg[0] = C:\Program 
   arg[1] = Files\Git1\  
CreateProcessW: pcmd = C:\Windows\SysWOW64\WScript.exe MyVB.vbs ""C:\Program Files\Git1\"" Test   

2. new ProcessBuilder("C:\\Windows\\SysWOW64\\WScript.exe", "MyVB.vbs", "C:\\Program Files\\Git\\", "Test").start();

2.1 allowAmbiguousCommands = false
   arg[0] = C:\Program Files\Git1\\ 
   arg[1] = Test  
CreateProcessW: pcmd = "C:\Windows\SysWOW64\WScript.exe" MyVB.vbs "C:\Program Files\Git1\\" Test   

2.2 allowAmbiguousCommands = true
   arg[0] = C:\Program Files\Git1\\ 
   arg[1] = Test 
CreateProcessW: pcmd = C:\Windows\SysWOW64\WScript.exe MyVB.vbs "C:\Program Files\Git1\\" Test   
```

FIXED (as in pr)
```
1. new ProcessBuilder("C:\\Windows\\SysWOW64\\WScript.exe", "MyVB.vbs", "\"C:\\Program Files\\Git\\\"", "Test").start();

1.1 allowAmbiguousCommands = false
   arg[0] = C:\Program Files\Git1\ 
   arg[1] = Test 
CreateProcessW: pcmd = "C:\Windows\SysWOW64\WScript.exe" MyVB.vbs "C:\Program Files\Git1\" Test   

1.2 allowAmbiguousCommands = true
 arg[0] = C:\Program Files\Git1\ 
 arg[1] = Test 
CreateProcessW: pcmd = C:\Windows\SysWOW64\WScript.exe MyVB.vbs "C:\Program Files\Git1\" Test  
``` 

Reading the code of unQuote() in terms of logic: "no beginning or ending quote, or too short => not quoted", - and it seems that if all these conditions are just opposite (starting and ending quotes and long enough) then a string should be treated as quoted but it's not. One exception was added and it's strange that it's applied even in case of paired quotes. Is it truly necessary for the security fix to skip (=to treat as unquoted) a string starting and ending with `'\"'` in case of a `"\\\""` tail?

This proposed fix returns back possibility (as was previously) to use surrounding with `'\"'` as an argument mark-up that allows to pass correctly a path with a space inside in case of VBS. Roger, would you be so kind to take a look at this small fix once again, please, and to pay attention to VBS parsing arguments problem?!

**Comment by mkartashev** [comment]
It is apparent there is no one "correct" way to quote, but one of the key features of the Java ecosystem has been its backwards compatibility. In that light, this change allows our clients to continue doing what they did the way they did it without the need for modification of their Java code or their (maybe even foreign) native code. FWIW.

Separately from the above, I wonder if this change would make the fix less controversial?
```Java
-        if (str.endsWith("\\\"")) {
+        if (str.endsWith("\\\"") && !str.endsWith("\\\\\"")) {
```
This way we verify that the end quote is really just an escaped quote, while correctly identifying escaped backslash as having nothing to do with the following quote.

**Comment by mkartashev** [comment]
Actually, this change should be made even more generic because the string might end with any even number of the backslash characters followed by a free-standing quote, in which case additional quoting should not be required.

**Comment by RogerRiggs** [comment]
(I'm still working on a more nuanced fix that works with .exe, .cmd, and with allowAmbiguousCommands both true and false).

The suggested workaround was to remove the application quotes and let ProcessBuilder do the quoting.
That resulted in an extra "\" at the end of a file path. In my investigation, the extra "\" doesn't prevent the 
string from being correctly used as a directory path in either VisualBasic or cmd.exe.
So I'm curious, in the original application that uncovered this problem, what is/was reported as the error?
Was the original application retested with the workaround?

The case of the backslash at the end of an argument occurs mainly in a directory path.
Yes, the argument is different, but does it make a difference that matters in the context in which it appears.

**Comment by mkartashev** [comment]
@RogerRiggs 
Our use case was something like this `java -classpath "C:\Program Files\MySQL\JDBC\\" ...`. More specifically, while this works after JDK-8250568 (the string ends with `"`)
```Java
    ProcessBuilder("java.exe", "-classpath", "\"C:\\New folder\"", "Test", "test");
```
this doesn't and, as I understand, shouldn't (the string ends with `\"`):
```Java
    ProcessBuilder("java.exe", "-classpath", "\"C:\\New folder\\\"", "Test", "test");
```
and produces errors like these
```
Error: Could not find or load main class folder"" Test test
Caused by: java.lang.ClassNotFoundException: folder"" Test test
```
However, the following still doesn't work, but, I believe, should (the string ends with `\\"`):
```Java
    ProcessBuilder("java.exe", "-classpath", "\"C:\\New folder\\\\\"", "Test", "test");
```

**Comment by RogerRiggs** [comment]
As an alternative fix, please take a look at Draft PR: https://github.com/openjdk/jdk/pull/7709.

In the default handling of arguments, the check for what is quoted is reverted to prior to 8255068. First and last quotes are sufficient to identify a "quoted" string. The check for a backslash ("\\") is removed.
This original check is sufficient for `jdk.lang.Process.allowAmbiguousCommands = true`.

For the case where the system property `jdk.lang.Process.allowAmbiguousCommands = false`
and the argument has first and last quotes, a backslash ("\\") before the final quote must not allow the quote to interpreted as a literal quote and merge the following argument.  The backslashes will doubled to prevent the interpretation of the quote as a literal.  This is the correct encoding if the command uses the ".exe" encoding, when reparsing the arguments the doubled backslashes are reduced to the original contents.
When the command is using the simpler parsing that does not support literal quotes, the backslash before the quote is typically is a trailing backslash on a file path and in that case the additional backslash is redundant and has no effect on the interpretation of the argument as a directory path.

The PR includes a test of the 12 combinations of invoking an "java"/.exe program, a .cmd script, and a Visual Basic script (which uses the .exe rules but different command line parser); with and without application quotes and compares the actual results with the expected arguments.

**Comment by mkartashev** [comment]
@RogerRiggs I believe your patch fixes the use case(s) we are interested in. Would be good to see it merged into `master`.

**Comment by omikhaltsova** [comment]
@RogerRiggs Sorry for the delay! I also checked, the test-case with VBS, that raised this issue, successfully workes with your patch. It would be great to have it asap.

**Comment by omikhaltsova** [comment]
Closed due to an alternative fix #7709.

**Comment by RogerRiggs** [comment]
Thanks for the followup and confirmation. I'll move #7709 to review from draft.

**Pull request closed without merging**
