### PR TITLE
8264752: SIGFPE crash with option FlightRecorderOptions:threadbuffersize=30M

### PR DESCRIPTION
**Pull request by huishi-hs**
…ize=30M

Fix misc explicit JFR memory option caused crash and assertion (https://bugs.openjdk.java.net/browse/JDK-8241773).

1. Fix SIGFPE crash in div_total_by_per_unit.
   a) In valid_memory_relations, check threadbuffersize should not larger than memorysize.
   b) In "void thread_buffer_size(JfrMemoryOptions* options)", calculate memorysize if it isn't configured, avoid SIGFPE when thread buffer size is larger than default memorysize.
   
2. Fix "assert(free_size() == size, "invariant");" in JfrBuffer::initialize.
   Limit globalbuffersize and threadbuffersize under 2G, avoid size_t to u4 coversion lost.
   
3. Check and report possible inconsistent conditions after jfr memory size adjustment.
   a) globalbuffercount < MIN_BUFFER_COUNT
   b) globalbuffersize < threadbuffersize

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264752](https://bugs.openjdk.java.net/browse/JDK-8264752): SIGFPE crash with option FlightRecorderOptions:threadbuffersize=30M

### Reviewers
 * [Markus Grönlund](https://openjdk.java.net/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3432/head:pull/3432` \
`$ git checkout pull/3432`

Update a local copy of the PR: \
`$ git checkout pull/3432` \
`$ git pull https://git.openjdk.java.net/jdk pull/3432/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3432`

View PR using the GUI difftool: \
`$ git pr show -t 3432`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3432.diff">https://git.openjdk.java.net/jdk/pull/3432.diff</a>

</details>

### CODE REVIEW

**Review by mgronlun — APPROVED** [review]
Hi Hui, looks good - thank you for testing and making this a bit more robust.

**Comment by mgronlun** [comment]
I did see this test fail when running on linux-aarch64:

[2021-04-16T12:55:44,162Z] java.lang.RuntimeException: 'Decrease globalbuffersize or increase memorysize or adjust global/threadbuffersize' missing from stdout/stderr 
[2021-04-16T12:55:44,163Z] 
[2021-04-16T12:55:44,163Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:206)
[2021-04-16T12:55:44,163Z] 	at jdk.jfr.startupargs.TestBadOptionValues.test(TestBadOptionValues.java:56)
[2021-04-16T12:55:44,163Z] 	at jdk.jfr.startupargs.TestBadOptionValues.main(TestBadOptionValues.java:139)
[2021-04-16T12:55:44,163Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-16T12:55:44,163Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-16T12:55:44,163Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-16T12:55:44,164Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-16T12:55:44,164Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-04-16T12:55:44,164Z] 	at java.base/java.lang.Thread.run(Thread.java:831)
[2021-04-16T12:55:44,164Z] 
[2021-04-16T12:55:44,164Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-04-16T12:55:44,165Z] JavaTest Message: shutting down test

**Comment by huishi-hs** [comment]
@mgronlun Thanks for your reivew and test!

Is default page size larger than 4k in your aarch64 enivronment? I found an aarch64 mchine default page size 64k.
In this case both local/global buffer size is aligned to 64K page size and not fail. 
Fix is checking vm page size isn't larger than 4K before running test "memorysize=1m,numglobalbuffers=256".

./build/linux-aarch64-server-release/jdk/bin/java -XX:StartFlightRecording -XX:FlightRecorderOptions:memorysize=1m,numglobalbuffers=256 -Xlog:arguments=trace -version
[0.157s][trace][arguments] Memory size (original) 1048576 B (user defined: true)
[0.157s][trace][arguments] Memory size (adjusted) 1048576 B (modified: false)
[0.157s][trace][arguments] Memory size (adjustment) +0 B
[0.157s][trace][arguments] Global buffer size (original) 524288 B (user defined: false)
[0.157s][trace][arguments] Global buffer size (adjusted) 65536 B (modified: true)
[0.157s][trace][arguments] Global buffer size (adjustment) -458752 B
[0.157s][trace][arguments] Thread local buffer size (original) 8192 B (user defined: false)
[0.157s][trace][arguments] Thread local buffer size (adjusted) 65536 B (modified: true)
[0.157s][trace][arguments] Thread local buffer size (adjustment) +57344 B
[0.157s][trace][arguments] Number of global buffers (original) 256 (user defined: true)
[0.157s][trace][arguments] Number of global buffers (adjusted) 16 (modified: true)
[0.157s][trace][arguments] Number of global buffers (adjustment) -240
Started recording 1. No limit specified, using maxsize=250MB as default.

**Comment by huishi-hs** [comment]
@mgronlun Could you please help review again for updated commit?

**Review by mgronlun — APPROVED** [review]
Tests are green after the update - thank you.

**Comment by huishi-hs** [comment]
> Tests are green after the update - thank you.

Thanks for your review!

**Comment by huishi-hs** [comment]
Could someone give a second review before integrate this?

**Pull request closed without merging**
