### PR TITLE
8339960: GenShen: Fix inconsistencies in generational Shenandoah behavior

### PR DESCRIPTION
**Pull request by kdnilsen**
This fixes some bugs found in recent code review and playback of an assertion failure.

See also https://github.com/openjdk/shenandoah/pull/497

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339960](https://bugs.openjdk.org/browse/JDK-8339960): GenShen: Fix inconsistencies in generational Shenandoah behavior (**Bug** - P4) ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20974/head:pull/20974` \
`$ git checkout pull/20974`

Update a local copy of the PR: \
`$ git checkout pull/20974` \
`$ git pull https://git.openjdk.org/jdk.git pull/20974/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20974`

View PR using the GUI difftool: \
`$ git pr show -t 20974`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20974.diff">https://git.openjdk.org/jdk/pull/20974.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20974#issuecomment-2347182351)

### CODE REVIEW

**Review by earthling-amzn — APPROVED** [review]
Looks good to me.

**Review by rkennke — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
