### PR TITLE
8263587: C2: JVMS not cloned when needs_clone_jvms() is true

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
We need a C2 fix to prevent crashes because JVMS doesn't get cloned as needed. See linked issue for details.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263587](https://bugs.openjdk.java.net/browse/JDK-8263587): C2: JVMS not cloned when needs_clone_jvms() is true

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**) ⚠️ Review applies to bafcce9f1923af6deedf3c0fd23aefcac00c2f18
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/3009/head:pull/3009`
`$ git checkout pull/3009`

### CODE REVIEW

**Review by GoeLin — APPROVED** [review]
LGTM

**Review by iwanowww — APPROVED** [review]
Looks good.

Cleanup idea: `CallNode::clone_jvms()` overrides differ only in the guarding condition. Extract node type dependent checks into a new helper method (`CallNode::needs_clone_jvms()`) and use it from now non-virtual `CallNode::clone_jvms()`.

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews and the cleanup proposal! Please take a look at my updated version.

**Review by iwanowww — APPROVED** [review]
Even better!

**Pull request closed without merging**
