### PR TITLE
6355567: AdobeMarkerSegment causes failure to read valid JPEG

### PR DESCRIPTION
**Pull request by cushon**
Please review this fix for JDK-6355567, which updates AdobeMarkerSegment to use the reported length of the segment instead of assuming it's always exactly 14 bytes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6355567](https://bugs.openjdk.org/browse/JDK-6355567): AdobeMarkerSegment causes failure to read valid JPEG (**Bug** - P4)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to [24a77ead](https://git.openjdk.org/jdk/pull/14779/files/24a77ead7b8d4ab758ce336e882addab0ce13c06)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14779/head:pull/14779` \
`$ git checkout pull/14779`

Update a local copy of the PR: \
`$ git checkout pull/14779` \
`$ git pull https://git.openjdk.org/jdk.git pull/14779/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14779`

View PR using the GUI difftool: \
`$ git pr show -t 14779`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14779.diff">https://git.openjdk.org/jdk/pull/14779.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14779#issuecomment-1622672257)

### CODE REVIEW

**Comment by prrace** [comment]
The provided image for the test looks to me like a down-sized version of the image seen here https://thedisabledlist.com/2005/sinus-cavities. 
As such I don't see how you can provide it under the terms of the OCA as I then presume you don't own it.

**Comment by cushon** [comment]
Thanks, I have removed the test

**Review by prrace — APPROVED** [review]
lgtm.
I'd like @jayathirthrao to be 2nd reviewer.

**Review by mrserb — APPROVED** [review]

**Comment by mickleness** [comment]
Does anyone want to reinstate a test for this? I created a simple 10x10 black jpeg that reproduces the problem:

https://drive.google.com/file/d/15rhf9-aMqajgoc3OKFhJq92hIu4OmG32/view?usp=sharing

**Comment by cushon** [comment]
> Does anyone want to reinstate a test for this? I created a simple 10x10 black jpeg that reproduces the problem:
> 
> https://drive.google.com/file/d/15rhf9-aMqajgoc3OKFhJq92hIu4OmG32/view?usp=sharing

Thanks! I have reinstated the test with that jpeg

**Review by prrace — APPROVED** [review]
re-approving with test

**Comment by prrace** [comment]
Since Sergey also reviewed, this is OK to push now.

**Pull request closed without merging**
