### PR TITLE
8264271: Avoid creating non_oop_word oops

### PR DESCRIPTION
**Pull request by stefank**
Some parts of the JVM puts an marker to show that a location does not contain a valid oop. The code that handles this typically look like this:

oop* p = ...
if (*p != Universe::non_oop_word())

This means that sometimes the *p will create an oop that contains the non_oop_word. This makes it problematic to add stricter oop verification. I propose that we add a new function that checks the value of locations without converting it to an oop. 

(Note: I'm testing the new dependent pull Skara feature with this PR. It builds depends on the pr/3214 branch)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264271](https://bugs.openjdk.java.net/browse/JDK-8264271): Avoid creating non_oop_word oops

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to b3c1b292bfb50bcf8d088cfb1fa4774d7774dfdf
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**) ⚠️ Review applies to 41ce5fd17d927601764ba15b6f74bb4f4f98208b

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3215/head:pull/3215` \
`$ git checkout pull/3215`

Update a local copy of the PR: \
`$ git checkout pull/3215` \
`$ git pull https://git.openjdk.java.net/jdk pull/3215/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3215`

View PR using the GUI difftool: \
`$ git pr show -t 3215`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3215.diff">https://git.openjdk.java.net/jdk/pull/3215.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by stefank** [comment]
Thanks, Kim. Now lets see what happens now that #3214 has been updated ...

**Comment by stefank** [comment]
The bots accidentally closed this. The PR will be reopened today or tomorrow.

**Review by pliden — APPROVED** [review]
Looks good!

**Comment by stefank** [comment]
Thanks, Per. I'm working with Robin to fix this branch. Currently it shows changes from the dependent branch, but after a merge with openjdk/master, this should hopefully be solved.

**Pull request closed without merging**
