### PR TITLE
8256387: Unexpected result if patching an entire instruction on AArch64

### PR DESCRIPTION
**Pull request by erik1iu**
This patch fixed some potential risks in assembler_aarch64.hpp.

According to the C standard, shift operation is undefined if the shift
count greater than or equals to the length in bits of the promoted left
operand.

In assembler_aarch64.hpp, there are some utility functions for easily
operating the encoded instructions. E.g.

        Instruction_aarch64::patch(address, int, int, uint64_t)

All those functions use `(1U << nbits) - 1` to calculate mask which may
have some potential risks if `nbits` equals 32. That would be an
unexpected result if someone intends to deal with an entire instruction.

To fix this issue, this patch simply uses `1ULL` to replace `1U`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256387](https://bugs.openjdk.java.net/browse/JDK-8256387): Unexpected result if patching an entire instruction on AArch64

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1248/head:pull/1248`
`$ git checkout pull/1248`

### CODE REVIEW

**Comment by erik1iu** [comment]
Hi, could anyone please take a look at this trivial PR? Thanks very much!

**Review by shipilev — COMMENTED** [review]
So there is a global `right_n_bits` macro that apparently does what we want? @theRealAph might want to look at this issue (probably in disgust).

**Comment by theRealAph** [comment]
> So there is a global `right_n_bits` macro that apparently does what we want? @theRealAph might want to look at this issue (probably in disgust).

True, it looks like what we want, written using some horrible macros. Fine by me.

**Review by theRealAph — APPROVED** [review]

**Comment by shipilev** [comment]
I am running `tier1` on `aarch64` here, will sponsor once tests complete.

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
