### PR TITLE
8272369: java/io/File/GetXSpace.java failed with "RuntimeException: java.nio.file.NoSuchFileException: /run/user/0"

### PR DESCRIPTION
**Pull request by bplb**
This change proposes to exclude `/run/user` mounts from the test when run on Linux as they can "disappear" while the test is running.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272369](https://bugs.openjdk.java.net/browse/JDK-8272369): java/io/File/GetXSpace.java failed with "RuntimeException: java.nio.file.NoSuchFileException: /run/user/0"

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5136/head:pull/5136` \
`$ git checkout pull/5136`

Update a local copy of the PR: \
`$ git checkout pull/5136` \
`$ git pull https://git.openjdk.java.net/jdk pull/5136/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5136`

View PR using the GUI difftool: \
`$ git pr show -t 5136`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5136.diff">https://git.openjdk.java.net/jdk/pull/5136.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
/run/user/$UID seems to be created by pam_systemd. If these mounts disappear during a test run then I assume it might impact other tests too, have you looked at the FileStore tests?

**Comment by bplb** [comment]
That's correct, it's [pam_systemd](https://www.man7.org/linux/man-pages/man8/pam_systemd.8.html). I have not yet examined any other tests.

**Comment by AlanBateman** [comment]
The change looks okay but I suspect a similar change will require in a few other tests. It may be worth trying to identify those tests while the issue the understood.

**Review by AlanBateman — APPROVED** [review]

**Comment by bplb** [comment]
There is no other occurrence of `df` in the `java/io` or the `java/nio` tests that I can find. The test `java/nio/file/FileStore/Basic.java` does however have this construct:

```
                // check space attributes are accessible
                try {
                    store.getTotalSpace();
                    store.getUnallocatedSpace();
                    store.getUsableSpace();
                } catch (NoSuchFileException nsfe) {
                    // ignore exception as the store could have been
                    // deleted since the iterator was instantiated
                    System.err.format("%s was not found\n", store);
                } catch (AccessDeniedException ade) {
                    // ignore exception as the lack of ability to access the
                    // store due to lack of file permission or similar does not
                    // reflect whether the space attributes would be accessible
                    // were access to be permitted
                    System.err.format("%s is inaccessible\n", store);
                }
```
which might be a better way to handle the current problem, i.e., don't filter out the `/run/user` mounts up front, but ignore the NSFE if it occurs on one of them

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
