### PR TITLE
8299254: Support dealing with standard assert macro

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to provide and use mechanisms for dealing with uses
of the standard assert macro (from <assert.h> or <cassert>) in 3rd party code
that we use in HotSpot.

We provide a pair of utility header files, to be included before and after a
header that may use (and so include) the standard assert macro.  These new
headers provide a scope in which the HotSpot assert macro is not defined, and
then reinstated after.

We also define NDEBUG in release builds of HotSpot, so any uses of the
standard assert macro in such 3rd party code will be disabled.

Finally, we use the new utility headers in some gtests and in our gtest
wrapper header (unittest.hpp), eliminating problems the gtest implementation
and with some versions of some standard libraries that the tests use.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254): Support dealing with standard assert macro

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [8b9a2d60](https://git.openjdk.org/jdk/pull/11770/files/8b9a2d606f713d8ad15a7a4a59049ae15618af23)
 * [Xue-Lei Andrew Fan](https://openjdk.org/census#xuelei) (@XueleiFan - **Reviewer**) ⚠️ Review applies to [8b9a2d60](https://git.openjdk.org/jdk/pull/11770/files/8b9a2d606f713d8ad15a7a4a59049ae15618af23)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [8b9a2d60](https://git.openjdk.org/jdk/pull/11770/files/8b9a2d606f713d8ad15a7a4a59049ae15618af23)
 * [Mikael Vidstedt](https://openjdk.org/census#mikael) (@vidmik - **Reviewer**) ⚠️ Review applies to [8b9a2d60](https://git.openjdk.org/jdk/pull/11770/files/8b9a2d606f713d8ad15a7a4a59049ae15618af23)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11770/head:pull/11770` \
`$ git checkout pull/11770`

Update a local copy of the PR: \
`$ git checkout pull/11770` \
`$ git pull https://git.openjdk.org/jdk pull/11770/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11770`

View PR using the GUI difftool: \
`$ git pr show -t 11770`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11770.diff">https://git.openjdk.org/jdk/pull/11770.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by XueleiFan — APPROVED** [review]
The patch passed for my build on MacOSX13.1/M1 (See JDK-8299380).  Thanks!

**Review by dholmes-ora — APPROVED** [review]
Not pretty, but effective.

Do we need some text added to the hotspot style guide to describe this usage? Should we bracket all includes of system headers with these, or only those known to cause a problem?

Thanks.

**Comment by kimbarrett** [comment]
> Not pretty, but effective.
> 
> Do we need some text added to the hotspot style guide to describe this usage? Should we bracket all includes of system headers with these, or only those known to cause a problem?

Most of the uses are currently violations of the style guide (e.g. using the
Standard Library (other than the C++ wrappers for standard C headers)). The
only exception to that is the wrapper around the gtest header inclusions. So
no, I don't think we need to do anything about this in the style guide. (My
prototype / proposal for permitting more use of the Standard Library makes use
of this same mechanism. The new helper files originated there, and this change
lets me eliminate one of the commits in that work.)

**Review by vidmik — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks for reviews @XueleiFan , @dholmes-ora , @erikj79 , and @vidmik .

**Pull request closed without merging**
