### PR TITLE
8260263: Remove PtrQueue::_qset

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  can I have reviews for this trivial(?) removal of dead code pertaining to and including `PtrQueue::_qset`?

Testing: local compilation, tier1

Thanks,
  Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260263](https://bugs.openjdk.java.net/browse/JDK-8260263): Remove PtrQueue::_qset

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to bdd856851bef72d2fe108e86e93f383b6a71fc74
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to bdd856851bef72d2fe108e86e93f383b6a71fc74

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2194/head:pull/2194`
`$ git checkout pull/2194`

### CODE REVIEW

**Comment by tschatzl** [comment]
/summary Remove dead code related to PtrQueue::_qset and itself.

**Review by kimbarrett — APPROVED** [review]
I hadn't realized the `_qset` was quite this dead.  And this doesn't appear to depend on JDK-8258742 (still waiting for a 2nd reviewer), or even have merge conflicts with it.  Cool!

**Review by kstefanj — APPROVED** [review]
Nice cleanup.

**Comment by tschatzl** [comment]
Thanks @kimbarrett @kstefanj for your reviews.

/integrate

**Pull request closed without merging**
