### PR TITLE
8297984: Turn on warnings as errors for javadoc

### PR DESCRIPTION
**Pull request by magicus**
For some reason, we never turned on `-Werror` for javadoc. It is high time to do so.

This PR also fixes a recent issue with the javadoc in JFR that caused a warning, and enables building of javadoc on GHA. (It takes about 3 minutes, as a separate build job.)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297984](https://bugs.openjdk.org/browse/JDK-8297984): Turn on warnings as errors for javadoc

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to [20bc7222](https://git.openjdk.org/jdk/pull/11468/files/20bc7222a54a239a83ea7c514a83671ad9d6c378)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [20bc7222](https://git.openjdk.org/jdk/pull/11468/files/20bc7222a54a239a83ea7c514a83671ad9d6c378)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11468/head:pull/11468` \
`$ git checkout pull/11468`

Update a local copy of the PR: \
`$ git checkout pull/11468` \
`$ git pull https://git.openjdk.org/jdk pull/11468/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11468`

View PR using the GUI difftool: \
`$ git pr show -t 11468`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11468.diff">https://git.openjdk.org/jdk/pull/11468.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
If you would like to exercise the full-docs build in GHA, you could make that build depend on the linux-x64 build and set `--with-build-jdk` and `--with-docs-reference-jdk` to point to it. That's how we do it internally at Oracle.

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
> If you would like to exercise the full-docs build in GHA, you could make that build depend on the linux-x64 build and set `--with-build-jdk` and `--with-docs-reference-jdk` to point to it.

Good point. I don't think it's worth it, though. Since the output is not saved but thrown away, we will just be wasting CPU cycles. The full docs graph generation is unlikely to start failing as a result of general changes in the code, only if some of the code that generates the graphs were to be changed, and such PRs can test this separately.

**Comment by magicus** [comment]
Since we do not do "apt install graphviz", configure will automatically determine that full docs is impossible. My intent were to keep it that way, since if for some reason "dot" were to be installed on the GHA image, then suddenly the build time would jump from 3 minutes to 60, so I wanted to make it clear that we never want this to happen. 

However, I realize my comment might be misunderstood as if full docs is impossible to do without the cost of rebuilding everything. I'll see if I can clarify it without turning it into an essay about the reasoning.

**Pull request closed without merging**
