### PR TITLE
8345269: Fix -Wzero-as-null-pointer-constant warnings in ppc code

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to remove -Wzero-as-null-pointer-constant warnings
in ppc code.

Most places involve just changing literal 0 to nullptr.

Removed a dead return after ShouldNotReachHere() that is no longer needed.

Removed some unused Address constructors that had a default address argument
with literal 0 as the default value.  These could have been changed to use
nullptr as the default value, but since they aren't used...

Testing:
GHA sanity test build, with and without -Wzero-as-null-pointer-constant enabled.
I don't have the capability to run tests for this platform, so hoping someone
from the aix-ppc maintainers can do more testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345269](https://bugs.openjdk.org/browse/JDK-8345269): Fix -Wzero-as-null-pointer-constant warnings in ppc code (**Enhancement** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22466/head:pull/22466` \
`$ git checkout pull/22466`

Update a local copy of the PR: \
`$ git checkout pull/22466` \
`$ git pull https://git.openjdk.org/jdk.git pull/22466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22466`

View PR using the GUI difftool: \
`$ git pr show -t 22466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22466.diff">https://git.openjdk.org/jdk/pull/22466.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22466#issuecomment-2509079744)
</details>

### CODE REVIEW

**Comment by kimbarrett** [comment]
Anyone?  Especially somebody from the aix-ppc folks?

**Review by TheRealMDoerr — APPROVED** [review]
Thanks for fixing it! LGTM.

**Comment by kimbarrett** [comment]
Thanks for reviews @MBaesken and @TheRealMDoerr

**Pull request closed without merging**
