### PR TITLE
8287028: AArch64: [vectorapi] Backend implementation of VectorMask.fromLong with SVE2

### PR DESCRIPTION
**Pull request by theRealELiu**
This patch implements AArch64 codegen for VectorLongToMask using the
SVE2 BitPerm feature. With this patch, the final code (generated on an
SVE vector reg size of 512-bit QEMU emulator) is shown as below:

        mov     z17.b, #0
        mov     v17.d[0], x13
        sunpklo z17.h, z17.b
        sunpklo z17.s, z17.h
        sunpklo z17.d, z17.s
        mov     z16.b, #1
        bdep    z17.d, z17.d, z16.d
        cmpne   p0.b, p7/z, z17.b, #0

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287028](https://bugs.openjdk.org/browse/JDK-8287028): AArch64: [vectorapi] Backend implementation of VectorMask.fromLong with SVE2

### Reviewers
 * [Xiaohong Gong](https://openjdk.java.net/census#xgong) (@XiaohongGong - Committer)
 * [Nick Gasson](https://openjdk.java.net/census#ngasson) (@nick-arm - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/8789/head:pull/8789` \
`$ git checkout pull/8789`

Update a local copy of the PR: \
`$ git checkout pull/8789` \
`$ git pull https://git.openjdk.org/jdk pull/8789/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8789`

View PR using the GUI difftool: \
`$ git pr show -t 8789`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/8789.diff">https://git.openjdk.org/jdk/pull/8789.diff</a>

</details>

### CODE REVIEW

**Comment by XiaohongGong** [comment]
@theRealELiu , could you please rebase this patch and resolve the conflict? Thanks!

**Review by XiaohongGong — APPROVED** [review]
LGTM!

**Review by nick-arm — APPROVED** [review]

**Pull request closed without merging**
