### PR TITLE
8330242: RISC-V: Simplify and remove CORRECT_COMPILER_ATOMIC_SUPPORT in atomic_linux_riscv.hpp

### PR DESCRIPTION
**Pull request by zifeihan**
Previously, we fixed JDK-8326936 with a workaround for one GCC bug [1]. We define a new `CORRECT_COMPILER_ATOMIC_SUPPORT` macro when building with GCC >= 14. Now this bug has been fixed in gcc trunk and has been backported to GCC-13 branch. The `__atomic_compare_exchange` atomic operation will be usable for the next GCC-13.3 release. So we should relax the condition and require GCC > 13.2. This will also help remove `CORRECT_COMPILER_ATOMIC_SUPPORT` macro and reuse a single `FULL_COMPILER_ATOMIC_SUPPORT` macro.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114130

### Testing

- [x] The affected jtreg test cases all pass with jdk release built with latest gcc-13 development branch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330242](https://bugs.openjdk.org/browse/JDK-8330242): RISC-V: Simplify and remove CORRECT_COMPILER_ATOMIC_SUPPORT in atomic_linux_riscv.hpp (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18780/head:pull/18780` \
`$ git checkout pull/18780`

Update a local copy of the PR: \
`$ git checkout pull/18780` \
`$ git pull https://git.openjdk.org/jdk.git pull/18780/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18780`

View PR using the GUI difftool: \
`$ git pr show -t 18780`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18780.diff">https://git.openjdk.org/jdk/pull/18780.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18780#issuecomment-2056037632)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks fine to me. Thanks for the cleanup.

**Review by robehn — APPROVED** [review]
Thanks!

**Comment by zifeihan** [comment]
@RealFYang @robehn : Thanks for the review.
/integrate

**Pull request closed without merging**
