### PR TITLE
8270870: Simplify G1ServiceThread

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this simplification of the internal control structure of
G1ServiceThread, particularly around the entry and exit of monitor contexts.

In addition, the run_task logging now includes the delay between the
scheduled time to run and the actual, as that seems like useful information
to have sometimes.

I also changed the monitor rank from nonleaf to leaf.  There was no reason
to use nonleaf, and leaf avoids questions about why nonleaf was used.

Testing:
mach5 tier1-3.  This includes the gtest for G1ServiceThread.

Ran a test program with gc+task logging enabled and checked that the logging
output looked okay.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270870](https://bugs.openjdk.java.net/browse/JDK-8270870): Simplify G1ServiceThread

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 1a2e4e18c530d3b776cd75a0258045105fc08256
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to 1a2e4e18c530d3b776cd75a0258045105fc08256

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4868/head:pull/4868` \
`$ git checkout pull/4868`

Update a local copy of the PR: \
`$ git checkout pull/4868` \
`$ git pull https://git.openjdk.java.net/jdk pull/4868/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4868`

View PR using the GUI difftool: \
`$ git pr show -t 4868`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4868.diff">https://git.openjdk.java.net/jdk/pull/4868.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @walulyai  for reviews.

**Pull request closed without merging**
