### PR TITLE
8255741: Zero: print signal name in unhandled signal handler

### PR DESCRIPTION
**Pull request by shipilev**
At least one test -- `runtime/Safepoint/TestAbortVMOnSafepointTimeout.java` -- fails on Zero with:

```
# Internal Error (/home/shade/trunks/jdk/src/hotspot/os_cpu/linux_zero/os_linux_zero.cpp:250), pid=560280, tid=560281
# fatal error: caught unhandled signal 4
```

The test expects "SIGKILL (sent by kill)" in the test output.

Additional testing:
 - [x] `TestAbortVMOnSafepointTimeout.java` now passes on Linux x86_64 Zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255741](https://bugs.openjdk.java.net/browse/JDK-8255741): Zero: print signal name in unhandled signal handler

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to 89de8c271c279c9b39bd3b85770d43375314be85

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1001/head:pull/1001`
`$ git checkout pull/1001`

### CODE REVIEW

**Review by tstuefe — COMMENTED** [review]
Okay I guess, but note that I am currently rewriting all that coding for https://bugs.openjdk.java.net/browse/JDK-8255711 . Which would, as a side effect, fix this bug too.

(The real bug here is that we invoke fatal() instead of calling VMError::report_and_die(), which means we won't see the real register content from the fault point in the hs-err file).

See current draft: https://github.com/openjdk/jdk/pull/982

Part of the change will be to heave fatal error handler invocation out of platform dependent up to shared code (and note how I took explicit care to preserve robot and cat on zero :) .

Cheers, Thomas

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by shipilev** [comment]
Thanks! I was not aware of #982 -- that would be very good to have. Maybe push this simple patch to ease backporting? Making Zero pass tier1 in 11u would be nice. I suspect #982 would not be backportable?

**Pull request closed without merging**
