### PR TITLE
JDK-8303051: Stop saving 5 chunks in each ChunkPool

### PR DESCRIPTION
**Pull request by jdksjolen**
In the 4 pre-defined ChunkPools the pruner save 5 chunks for re-use later in the program. The pruner runs every 5 seconds and saves the first 5 chunks that were last freed and put into the pool. In other words: The lifetime of these 5 chunks are indeterminate, we don't know when these will be freed. This is a problem, because these chunks are allocated with os::malloc(). We might be clobbering our underlying malloc's capacity to shrink its own arena sizes because of the placement of these chunks, and it would be very difficult for us to know whether this is the case.

I suggest that we stop saving these 4*5 chunks and always remove all free chunks when cleaning the pools.

Passes Arena gtests, running tier1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303051](https://bugs.openjdk.org/browse/JDK-8303051): Stop saving 5 chunks in each ChunkPool

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12710/head:pull/12710` \
`$ git checkout pull/12710`

Update a local copy of the PR: \
`$ git checkout pull/12710` \
`$ git pull https://git.openjdk.org/jdk pull/12710/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12710`

View PR using the GUI difftool: \
`$ git pr show -t 12710`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12710.diff">https://git.openjdk.org/jdk/pull/12710.diff</a>

</details>

### CODE REVIEW

**Review by robehn — APPROVED** [review]
Thank you.

**Comment by jdksjolen** [comment]
Passes tier1.

**Comment by jcking** [comment]
I question whether we should be saving any chunks at all ina central cache. Most malloc have per thread caches. By allocating in one thread and freeing in another thread whose sole purpose is deallocation we are kind of defeating the per thread caches purpose.

We should benchmark just removing the cache entirely in the future. In the past it distant past this could have been useful, but I question it now.

**Review by coleenp — APPROVED** [review]
Yes, this looks good. Nice find.

**Comment by jdksjolen** [comment]
> I question whether we should be saving any chunks at all in a central cache. Most malloc have per thread caches. By allocating in one thread and freeing in another thread whose sole purpose is deallocation we are kind of defeating the per thread caches purpose.
> 
> We should benchmark just removing the cache entirely in the future. In the distant past this could have been useful, but I question it now.

This was my intuition too :-). I tried removing the ChunkPool but my (very basic) experiments showed that this is in fact slower.  Note that this chunk cache is shared across the whole program, so checking whether there is a free chunk requires grabbing a mutex. We see a large increase in mallocs early in the lifetime of a program if it's entirely removed, and this happened to outpace the cost of holding a mutex. So the non-benefit of the `ChunkPool` wasn't trivial to prove. Apparently CDS complicates the situation more.

**Comment by jdksjolen** [comment]
No protests have arrived, integrating this!

/integrate

**Pull request closed without merging**
