### PR TITLE
8296611: Problemlist several sun/security tests until JDK-8295343 is resolved

### PR DESCRIPTION
**Pull request by mseledts**
Trivial change, updated jdk problem list.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296611](https://bugs.openjdk.org/browse/JDK-8296611): Problemlist several sun/security tests until JDK-8295343 is resolved

### Reviewers
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11045/head:pull/11045` \
`$ git checkout pull/11045`

Update a local copy of the PR: \
`$ git checkout pull/11045` \
`$ git pull https://git.openjdk.org/jdk pull/11045/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11045`

View PR using the GUI difftool: \
`$ git pr show -t 11045`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11045.diff">https://git.openjdk.org/jdk/pull/11045.diff</a>

</details>

### CODE REVIEW

**Comment by seanjmullan** [comment]
The `java/security/cert/pkix/policyChanges/TestPolicy.java`  and `java/security/cert/CertPathBuilder/targetConstraints/BuildEEBasicConstraints.java` test failures are already fixed. There is no need to ProblemList them.

**Comment by mseledts** [comment]
Thanks Sean. I will remove the fixed tests from the list.

**Comment by mseledts** [comment]
I have updated the problem list to exclude fixed tests. Please review when you have a chance.

**Comment by rhalade** [comment]
Please update the PR commit message in summary. I updated JBS bug summary to indicate only sun/security tests failed.

**Review by rhalade — APPROVED** [review]

**Comment by mseledts** [comment]
Thank you Rajan.

/integrate

**Pull request closed without merging**
