### PR TITLE
8335390: C2 MergeStores: wrong result with Unsafe

### PR DESCRIPTION
**Pull request by eme64**
In JDK23, I introduced `MergeStores` [JDK-8318446](https://bugs.openjdk.org/browse/JDK-8318446) https://github.com/openjdk/jdk/pull/16245.

I now realized that the pointer-parsing has some issues with `Unsafe` stores. Thus, I disable the optimization for those for now.

**Future Work**
In [JDK-8335392](https://bugs.openjdk.org/browse/JDK-8335392), I plan to redesign the pointer-parsing, and enable more features, including `Unsafe` stores.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335390](https://bugs.openjdk.org/browse/JDK-8335390): C2 MergeStores: wrong result with Unsafe (**Bug** - P2)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [ec5cc941](https://git.openjdk.org/jdk/pull/19964/files/ec5cc94128e3627878a0d0232835fae5cdefbe9d)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19964/head:pull/19964` \
`$ git checkout pull/19964`

Update a local copy of the PR: \
`$ git checkout pull/19964` \
`$ git pull https://git.openjdk.org/jdk.git pull/19964/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19964`

View PR using the GUI difftool: \
`$ git pr show -t 19964`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19964.diff">https://git.openjdk.org/jdk/pull/19964.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19964#issuecomment-2200063308)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by eme64** [comment]
Thanks @vnkozlov @TobiHartmann @chhagedorn for the reviews!
/integrate

**Pull request closed without merging**
