### PR TITLE
8261527: Record page size used for underlying mapping in ReservedSpace 

### PR DESCRIPTION
**Pull request by kstefanj**
Please review this change to use the actual page size rather than `bool large` when creating and initializing `ReservedSpace`. This allows us to then get rid of the helper `ReservedSpace::actual_reserved_page_size()` and instead use the "real" page size for logging and other use.

The PR consist of two commits, one that changes `ReservedSpace` to use and store a page size and one that removes `actual_reserved_page_size()` and instead uses `ReservedSpace::page_size()`. Hopefully this might help ease the review a bit. 

There are two changes in behavior:
* In `JfrVirtualMemorySegment::initialize()` we now always pass down `os::vm_page_size()` which means never use large pages. This differs from the old condition where large pages were enabled if transparent huge pages were enabled. This change has been discussed with the JFR team and they will later investigate how to re-enable large page use.
* In `ReservedSpace::reserve()`, if a file is used, the page size is always set to `os::vm_page_size()`. So when logging the page_size for such mapping it will not report a large page size. This was incorrectly done in the past when using `ReservedSpace::actual_reserved_page_size()` to figure out the page size. This makes the `runtime/os/TestTracePageSizes.java` test pass even if run with `-XX:AllocateHeapAt=/tmp`.

**Testing**
Mach5 tier1-4 and a lot of local testing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261527](https://bugs.openjdk.java.net/browse/JDK-8261527): Record page size used for underlying mapping in ReservedSpace

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3802/head:pull/3802` \
`$ git checkout pull/3802`

Update a local copy of the PR: \
`$ git checkout pull/3802` \
`$ git pull https://git.openjdk.java.net/jdk pull/3802/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3802`

View PR using the GUI difftool: \
`$ git pr show -t 3802`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3802.diff">https://git.openjdk.java.net/jdk/pull/3802.diff</a>

</details>

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good to me.

**Review by walulyai — APPROVED** [review]
lgtm!

**Comment by kstefanj** [comment]
Thanks for the reviews @rkennke and @walulyai.

/integrate

**Review by tstuefe — COMMENTED** [review]
I see you were too fast for me :) 

Good patch. Much cleaner now.

Thanks, Thomas

**Comment by kstefanj** [comment]
Thanks @tstuefe =)

**Pull request closed without merging**
