### PR TITLE
8266578: Disambiguate BigDecimal description of scale

### PR DESCRIPTION
**Pull request by ignasi35**
The API Docs for `BigDecimal` introduce the meaning of `scale`. The current writeup can be missleading when presenting the meaning of a `scale` value that's negative. Hopefully, with this PR, the sentence is more clear.

The ambiguity is on this sentence:

> If negative, the unscaled value of the number is ...

Instead, I suggest the more verbose:

> If the scale is negative, the unscaled value of the number is ...

To keep symmetry, I've also reviewed the positive case from:

> If zero or positive, the scale is the number of digits ...

to: 

> If the scale is zero or positive, the scale is the number of digits ...

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266578](https://bugs.openjdk.java.net/browse/JDK-8266578): Disambiguate BigDecimal description of scale

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/582/head:pull/582` \
`$ git checkout pull/582`

Update a local copy of the PR: \
`$ git checkout pull/582` \
`$ git pull https://git.openjdk.java.net/jdk pull/582/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 582`

View PR using the GUI difftool: \
`$ git pr show -t 582`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/582.diff">https://git.openjdk.java.net/jdk/pull/582.diff</a>

</details>

### CODE REVIEW

**Comment by ignasi35** [comment]
I'm trying to see what's the cause for the Check failure in `jcheck` but clicking `Details` opens http://openjdk.java.net/ without too much information to point me to the actual issue causing the check failure.

**Comment by bplb** [comment]
The `jcheck` test fails because "The commit message does not reference any issue. To add an issue reference to this PR, edit the title to be of the format `issue number: message`."

**Comment by ignasi35** [comment]
Thanks @bplb. I'm afraid I'm not an [author](http://openjdk.java.net/bylaws#author) or have access to create or read the issues in [JIRA](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1).

I am a first-time crontributor and I'm unfamiliar with the specifics on contributing.

**Comment by bplb** [comment]
@ignasi35 Do you wish to continue this PR? If so I will file an issue. Thanks.

**Comment by ignasi35** [comment]
> @ignasi35 Do you wish to continue this PR? If so I will file an issue. Thanks.

Hi @bplb, this completely fell through the cracks. If you could file the issue for me I'd really appreciate it. Thanks.

**Comment by bplb** [comment]
@ignasi35 I have created JDK-8266578. Please change the name of this PR to:

`8266578: Disambiguate BigDecimal description of scale`

Please resolve any conflicts and commit the updated file. Once the update is available, I will file a CSR and mark this PR accordingly.

**Comment by ignasi35** [comment]
Thanks @bplb for doing the heavy lifting. I've updated the PR title and solved the conflict.

**Review by jddarcy — APPROVED** [review]

**Review by bplb — APPROVED** [review]

**Comment by bplb** [comment]
@ignasi35 This PR has been approved, so once you have issued the [integrate](https://wiki.openjdk.java.net/display/SKARA/Pull+Request+Commands#PullRequestCommands-/integrate) command I can sponsor it. Thanks.

**Comment by bplb** [comment]
@ignasi35 Friendly reminder that this PR cannot progress until you issue the [integrate](https://wiki.openjdk.java.net/display/SKARA/Pull+Request+Commands#PullRequestCommands-/integrate) command. Thanks.

**Comment by ignasi35** [comment]
Apologies on the incredible delay. I've been offline on sick leave and barely returning to work.

**Pull request closed without merging**
