### PR TITLE
8293295: Add type check asserts to java_lang_ref_Reference accessors

### PR DESCRIPTION
**Pull request by xmas92**
From a discussion in [JDK-8293207](https://bugs.openjdk.org/browse/JDK-8293207) / #10117 it was brought up that the Weak/Soft and Phantom specific accessor in java_lang_ref_Reference does not assert that the type is valid.

Testing: Oracle platforms tier 1-4

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293295](https://bugs.openjdk.org/browse/JDK-8293295): Add type check asserts to java_lang_ref_Reference accessors

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10139/head:pull/10139` \
`$ git checkout pull/10139`

Update a local copy of the PR: \
`$ git checkout pull/10139` \
`$ git pull https://git.openjdk.org/jdk pull/10139/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10139`

View PR using the GUI difftool: \
`$ git pr show -t 10139`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10139.diff">https://git.openjdk.org/jdk/pull/10139.diff</a>

</details>

### CODE REVIEW

**Review by stefank — CHANGES_REQUESTED** [review]
Given that "!is_phantom" returns true for FinalReferences, maybe we should change this to explicitly check if the ref is Weak or Soft?

**Comment by xmas92** [comment]
> Given that "!is_phantom" returns true for FinalReferences, maybe we should change this to explicitly check if the ref is Weak or Soft?

Added `is_weak` and `is_soft` to make it more correct with respect to `FinalReference`. This will also be more correct if a `REF_NONE` ever finds its way into these accessors.

**Review by stefank — APPROVED** [review]
Looks good!

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by coleenp — APPROVED** [review]

**Pull request closed without merging**
