### PR TITLE
8279662: serviceability/sa/ClhsdbScanOops.java can fail do to unexpected GC

### PR DESCRIPTION
**Pull request by plummercj**
The test is failing to find certain types in the scanoops output when run with -Xcomp. This is happening in the loom repo. The reason it is happening there is because loom introduced a full GC during codecache sweeping. The test only runs scanoops on the eden gen, and the full GC is causing objects of certain expected types to no longer be present in the eden gen. The fix is to also check the old gen.

The logic of the test had to be reworked a bit to accomplish checking the output of two scanoops commands together. It was relying on the ClhsdbLauncher class to check the output for expected strings, but in this case we need to accumulate the output of the two scanoops commands and check the combined output for the expected strings, so now the checking is done directly by the test and not by ClhsdbLauncher.

I'm choosing to fix this in the jdk repo rather than the loom repo since it is a latent bug that theoretically could occur even without the loom changes, and also to help reduce the amount of changes to be reviewed when loom is integrated into jdk.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279662](https://bugs.openjdk.java.net/browse/JDK-8279662): serviceability/sa/ClhsdbScanOops.java can fail do to unexpected GC

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7295/head:pull/7295` \
`$ git checkout pull/7295`

Update a local copy of the PR: \
`$ git checkout pull/7295` \
`$ git pull https://git.openjdk.java.net/jdk pull/7295/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7295`

View PR using the GUI difftool: \
`$ git pr show -t 7295`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7295.diff">https://git.openjdk.java.net/jdk/pull/7295.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Looks reasonable to me.
There is minor duplication but it is okay as there is no good way to get rid of it.
Thanks,
Serguei

**Comment by plummercj** [comment]
> There is minor duplication but it is okay as there is no good way to get rid of it.

I considered a loop or common method, but it seemed not to be worth it and likely less readable.

**Comment by sspitsyn** [comment]
Agreed.

**Review by kevinjwalls — APPROVED** [review]
Looks good.  
For the scanoops for a type, it seems like a reasonable assumption that there will be a String in the old gen!

**Comment by plummercj** [comment]
> For the scanoops for a type, it seems like a reasonable assumption that there will be a String in the old gen!

Actually it's not, and that's why I check the Eden gen. If a GC is not triggered, the old gen will be empty. It not actually guaranteed that a String will be in the Eden gen either, but at least at the moment that appears to be the case whether or not a GC is triggered.

**Comment by kevinjwalls** [comment]
> Actually it's not, and that's why I check the Eden gen.

Yes sorry, should have said it's a good bet to find a String when only checking one generation.  Carry on...

**Pull request closed without merging**
