### PR TITLE
8304840: Dangling `CharacterCodingException` in a few javadoc descriptions

### PR DESCRIPTION
**Pull request by naotoj**
Fixing a documentation bug for `CharacterCodingException` without any description to it as attached. A corresponding CSR is also drafted.

Screenshot 2023-03-28 at 11 19 00 AM

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8305099](https://bugs.openjdk.org/browse/JDK-8305099) to be approved

### Issues
 * [JDK-8304840](https://bugs.openjdk.org/browse/JDK-8304840): Dangling `CharacterCodingException` in a few javadoc descriptions
 * [JDK-8305099](https://bugs.openjdk.org/browse/JDK-8305099): Dangling `CharacterCodingException` in a few javadoc descriptions (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [eb0053de](https://git.openjdk.org/jdk/pull/13214/files/eb0053de9f3b742175ee308ffa414d726aca3e5e)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to [eb0053de](https://git.openjdk.org/jdk/pull/13214/files/eb0053de9f3b742175ee308ffa414d726aca3e5e)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**) ⚠️ Review applies to [eb0053de](https://git.openjdk.org/jdk/pull/13214/files/eb0053de9f3b742175ee308ffa414d726aca3e5e)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [eb0053de](https://git.openjdk.org/jdk/pull/13214/files/eb0053de9f3b742175ee308ffa414d726aca3e5e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13214/head:pull/13214` \
`$ git checkout pull/13214`

Update a local copy of the PR: \
`$ git checkout pull/13214` \
`$ git pull https://git.openjdk.org/jdk.git pull/13214/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13214`

View PR using the GUI difftool: \
`$ git pr show -t 13214`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13214.diff">https://git.openjdk.org/jdk/pull/13214.diff</a>

</details>

### CODE REVIEW

**Review by irisclark — APPROVED** [review]
Associated CSR also Reviewed.

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
