### PR TITLE
8263995: Incorrect double-checked locking in Types.arraySuperType()

### PR DESCRIPTION
**Pull request by shipilev**
In Types.arraySuperType(), SonarCloud reports:
 Remove this dangerous instance of double-checked locking.

Indeed, the `arraySuperType` is not `volatile`, while `IntersectionClassType` has non-`final` fields (both in itself and in superclasses). This is an incorrect DCL.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263995](https://bugs.openjdk.java.net/browse/JDK-8263995): Incorrect double-checked locking in Types.arraySuperType()

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3129/head:pull/3129`
`$ git checkout pull/3129`

To update a local copy of the PR:
`$ git checkout pull/3129`
`$ git pull https://git.openjdk.java.net/jdk pull/3129/head`

### CODE REVIEW

**Review by mcimadamore — COMMENTED** [review]
I'm a bit surprised to see use of volatile/synchronized here as I'm pretty sure that javac is *not* thread safe.
It seems like the synchronized block has been there from a long time (e.g. it was there since the dawn of OpenJDK :-)). I wonder if a better fix would be simply to drop synchronization and volatileness.

**Comment by shipilev** [comment]
> I'm a bit surprised to see use of volatile/synchronized here as I'm pretty sure that javac is _not_ thread safe.
> It seems like the synchronized block has been there from a long time (e.g. it was there since the dawn of OpenJDK :-)). I wonder if a better fix would be simply to drop synchronization and volatileness.

Yeah, I just did the most obvious semantics-preserving thing in this first patch. See new commit that drops `synchronized` instead as to not confuse both humans and tools about this. Still passes `langtools:tier1`.

**Review by lahodaj — APPROVED** [review]
Looks good to me!

**Review by mcimadamore — APPROVED** [review]
Looks good

**Pull request closed without merging**
