### PR TITLE
8268293: VectorAPI cast operation on mask and shuffle is broken

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Existing implementation of VectoMask.cast and VectorShuffle.cast operation do not generate correct mask compliant with the species passed as the argument.

This patch fixes the implementation and adds the corresponding  cast operation test cases to VectorAPI regression suite.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8268293](https://bugs.openjdk.java.net/browse/JDK-8268293): VectorAPI cast operation on mask and shuffle is broken

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4392/head:pull/4392` \
`$ git checkout pull/4392`

Update a local copy of the PR: \
`$ git checkout pull/4392` \
`$ git pull https://git.openjdk.java.net/jdk pull/4392/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4392`

View PR using the GUI difftool: \
`$ git pr show -t 4392`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4392.diff">https://git.openjdk.java.net/jdk/pull/4392.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — COMMENTED** [review]
Rather than introducing optional tests, can we make them all required and increase the testing scope to also test for an exception? I think that would simplify the test generation logic.
Thus we push the size checks into the test methods. For the case of when an exception is expected we just need to call the cast once.

**Comment by jatin-bhateja** [comment]
> Rather than introducing optional tests, can we make them all req

Hi @PaulSandoz 
Should it be ok to add few -ve cases as a part of smokeTests on the lines of "bitwiseDivByZeroSmokeTest()" and keep all the +ve legal cases as they are being emitted currently, this shall cover the entire ground.

**Comment by PaulSandoz** [comment]
What concerns me is the additional complexity of the bash script. I would prefer not to increase the complexity and keep it as simple as possible, and place such conditions within Java test code which is more easily maintainable.

In fact i wonder if it makes sense to add such tests to the Vector*ConversionTests?

**Comment by jatin-bhateja** [comment]
> What concerns me is the additional complexity of the bash script. I would prefer not to increase the complexity and keep it as simple as possible, and place such conditions within Java test code which is more easily maintainable.
> 
> In fact i wonder if it makes sense to add such tests to the Vector*ConversionTests?

I understand your point, proposed changes demonstrate flexibility of the infrastructure to support various use cases.
Simple unit testcase will also easy debugging in case of a failure as logic for legality is part or test generation script. Additionally the negative cases are part of smoke tests.

Tests  generated using scripts will always better maintainable.

**Comment by PaulSandoz** [comment]
I don't agree in this case expanding logic in the bash scripts. Such complexity is less maintainable. The scripts and templates are already complicated and hard to maintain.

The testing of exception or non-exception cases could be separated out. I was suggesting combing as a convenient way to avoid increasing the complexity in the bash scripts.

i think a better alternative is to explore adding such tests to Vector*ConversionTests, with an additional data provider that provides species arguments for creating the mask and the cast argument, we can have separate data providers for exceptional and non-exceptional cases. Those data providers would embed similar logic that is currently within the bash script.

**Comment by jatin-bhateja** [comment]
Withdrawing from JDK-MAINLINE , PR created on JDK-17 branch

**Pull request closed without merging**
