### PR TITLE
8256956: RegisterImpl::max_slots_per_register is incorrect on AMD64

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

The bug was found while I was learning @iwanowww 's patch [1].

As we know, the slot-size is 32-bit and the registers are 64-bit on AMD64.
So RegisterImpl::max_slots_per_register [2] should be 2 on AMD64.

It would be better to fix it.

Testing:
  - tier1~3 on Linux/x64

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/pull/1132
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/register_x86.hpp#L53

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (8/8 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (2/9 failed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x86 (hs/tier1 compiler)](https://github.com/DamonFool/jdk/runs/1456467692)
- [Linux x86 (jdk/tier1 part 3)](https://github.com/DamonFool/jdk/runs/1456467656)

### Issue
 * [JDK-8256956](https://bugs.openjdk.java.net/browse/JDK-8256956): RegisterImpl::max_slots_per_register is incorrect on AMD64

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to 915e653ae34489ce9076c2a5af2178cf79eb42d1
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to 915e653ae34489ce9076c2a5af2178cf79eb42d1

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1413/head:pull/1413`
`$ git checkout pull/1413`

### CODE REVIEW

**Comment by shipilev** [comment]
Please wait for #1266 integration to get this tested on x86_32. (I think current patch does not affect it directly, but better be safe than sorry).

**Comment by TobiHartmann** [comment]
Just wondering, is that value even used? I did a quick search and couldn't find any usages.

**Comment by shipilev** [comment]
> Just wondering, is that value even used? I did a quick search and couldn't find any usages.

When I grep for `ConcreteRegisterImpl::number_of_registers`, it seems to have quite a few hits in x86 and shared code.

**Comment by TobiHartmann** [comment]
Indeed. I've searched for the wrong value.

**Comment by DamonFool** [comment]
Hi @TobiHartmann and @shipilev ,

Thanks for looking at this.

The wrong value really confused me while I was trying to understand the code.

Before this fix, RegisterImpl::max_slots_per_register seems not to be used directly on x86.
That may be why the bug didn't get exposed before.

I've notice that RegisterImpl::max_slots_per_register is used to calculate the value of ConcreteRegisterImpl::number_of_registers in aarch64 [1].
So I think it a good idea to use it in x86 to eliminate '#ifdef AMD64' [2], which seems to improve the readability of the code.

What do you think?

Thanks.
Best regards, 
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/aarch64/register_aarch64.hpp#L295
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/register_x86.hpp#L260

**Comment by TobiHartmann** [comment]
Right, so `RegisterImpl::max_slots_per_register` which was introduced in JDK 9 by [JDK-8076276](https://bugs.openjdk.java.net/browse/JDK-8076276) does indeed not have any usages in current code. That explains why this was never an issue.

Your fix looks good to me.

**Review by TobiHartmann — APPROVED** [review]

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by DamonFool** [comment]
Thanks @TobiHartmann and @iwanowww for your review.
Will push it soon since there seems no regression (tier1~tier3) on Linux/x86 due to this change. @shipilev

**Pull request closed without merging**
