### PR TITLE
8150303: Rewrite test/tools/javac/Paths/Diagnostics.sh

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

This patch rewrites Diagnostics.sh to java code by using ToolBox API.
And I have a question: What does the `elts` mean in the following comments? Is it `elements`?
I think that a meaningful name should be used.

```
// Warn for missing elts in user-specified paths
// No warning for missing elts in "system" paths
```

Thank you for taking the time to review.

Best Regards.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8150303](https://bugs.openjdk.java.net/browse/JDK-8150303): Rewrite test/tools/javac/Paths/Diagnostics.sh

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/1959/head:pull/1959` \
`$ git checkout pull/1959`

Update a local copy of the PR: \
`$ git checkout pull/1959` \
`$ git pull https://git.openjdk.java.net/jdk pull/1959/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1959`

View PR using the GUI difftool: \
`$ git pr show -t 1959`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/1959.diff">https://git.openjdk.java.net/jdk/pull/1959.diff</a>

</details>

### CODE REVIEW

**Comment by jonathan-gibbons** [comment]
> This patch rewrites Diagnostics.sh to java code by using ToolBox API.
> And I have a question: What does the elts mean in the following comments? Is it elements?
> I think that a meaningful name should be used.

Brave person. There's a reason no one has converted this test so far.

To answer your specific question: yes, `elts` should be read as an abbreviation for `elements` and yes, it would be good to clarify it.

**Comment by lgxbslgx** [comment]
@jonathan-gibbons Thank you for your answer. I modify `elts` to `elements`.

And I revise the test code about line separator because the test failed at windows in the pre-submit tests.

**Comment by lgxbslgx** [comment]
I merged the `master` branch to run the test locally and the test passed.

Ping for review.

**Pull request closed without merging**
