### PR TITLE
6436374: Graphics.setColor(null) is not documented

### PR DESCRIPTION
**Pull request by prsadhuk**
Document setting null setColor similar to way setFont(null) is documented.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-6436374](https://bugs.openjdk.java.net/browse/JDK-6436374): Graphics.setColor(null) is not documented

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Pankaj Bansal](https://openjdk.java.net/census#pbansal) (@pankaj-bansal - **Reviewer**) ⚠️ Review applies to dc4fe3c5c17ce4b63e5fd0b93adb507b96bbf2c7

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2371/head:pull/2371`
`$ git checkout pull/2371`

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Review by pankaj-bansal — APPROVED** [review]

**Comment by prsadhuk** [comment]
> 
> 
> @mrserb has indicated that a [compatibility and specification](https://wiki.openjdk.java.net/display/csr/Main) (CSR) request is needed for this pull request.
> @prsadhuk please create a CSR request and add link to it in [JDK-6436374](https://bugs.openjdk.java.net/browse/JDK-6436374). This pull request cannot be integrated until the CSR request is approved.

Done..JDK-8261018...Please review...

**Comment by mrserb** [comment]
While CSR is under review, maybe we can add a small test?

**Comment by prsadhuk** [comment]
What will be the objective of the test...It's just documentation change..no code is changed...setting null will be ignored before this and after this change...

**Comment by mrserb** [comment]
This change added a statement to the specification, which could not be tested before. So this new test will be the first one that passes a null to this method, how we will know that it is actually ignored?

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
