### PR TITLE
8260576: Typo in compiler/runtime/safepoints/TestRegisterRestoring.java

### PR DESCRIPTION
**Pull request by xpbob**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260576](https://bugs.openjdk.java.net/browse/JDK-8260576): Typo in compiler/runtime/safepoints/TestRegisterRestoring.java

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2286/head:pull/2286`
`$ git checkout pull/2286`

### CODE REVIEW

**Review by TobiHartmann — CHANGES_REQUESTED** [review]

**Review by TobiHartmann — APPROVED** [review]

**Review by DamonFool — APPROVED** [review]
Looks good and trivial.
Will sponsor it.

**Pull request closed without merging**
