### PR TITLE
JDK-8264181: javadoc tool Incorrect error message about malformed link

### PR DESCRIPTION
**Pull request by hns**
The primary problem was that key `compiler.err.dc.ref.bad.parens` had the wrong message "')' missing in reference". That error message is not used when the right parenthesis is missing, but when it occurs before the end of the signature. The missing parenthesis case is caught earlier by the parens balancing code in `DocCommentParser#reference` and uses message `compiler.err.dc.unterminated.signature` ("unterminated signature").

I changed the message for `compiler.err.dc.ref.bad.parens` to "unexpected parenthesis". 

A secondary problem was that `DocCommentParser#reference` also threw "unterminated signature" when there were too many closing angle brackets or parentheses. These cases are now passed through in`DocCommentParser#reference` so that `ReferenceParser#parse` can throw a more appropriate error ("unexpected parenthesis" or "unexpected input"). 

Here's a list of what references now cause what error messages:

 - `#foo(int`     `unterminated signature`
 - `#foo((int))`   `unexpected parenthesis`
 - `#foo(int))`   `unexpected parenthesis`
 - `#foo(int)x`   `unexpected parenthesis`
 - `F<T`        `unterminated signature`
 - `F<T>>`    `unexpected input`

I added two new tests for the cases with too many closing brackets/parens that used to fail with "unterminated signature".

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264181](https://bugs.openjdk.java.net/browse/JDK-8264181): javadoc tool Incorrect error message about malformed link

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4068/head:pull/4068` \
`$ git checkout pull/4068`

Update a local copy of the PR: \
`$ git checkout pull/4068` \
`$ git pull https://git.openjdk.java.net/jdk pull/4068/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4068`

View PR using the GUI difftool: \
`$ git pr show -t 4068`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4068.diff">https://git.openjdk.java.net/jdk/pull/4068.diff</a>

</details>

### CODE REVIEW

**Comment by pavelrappo** [comment]
1. I think this error is a counterintuitive:

       #foo(int)x
       error: unexpected parenthesis

It's `x` that is unexpected, not the parenthesis. It looks correct here, but only coincidentally:

       #foo(int))
       error: unexpected parenthesis

2. The latter case in your list, `F<T>>`, yields "unexpected text", not "unexpected input".
3. Why is there an asymmetry between wording for angle brackets and that of parenthesis?

**Comment by hns** [comment]
Thanks for reviewing, Pavel!

>     1. I think this error is a counterintuitive:
>        ```
>        #foo(int)x
>        error: unexpected parenthesis
>        ```
> 
> 
> It's `x` that is unexpected, not the parenthesis. It looks correct here, but only coincidentally:
> 
> ```
>    #foo(int))
>    error: unexpected parenthesis
> ```

Yes, you can look at it both ways, either there is a closing parenthesis where it shouldn't be, or there is text following a correctly placed closing parenthesis. We tend to see one or the other depending on whether the text up to the closing parenthesis looks like a proper signature, but it's not as clear to the parser. 

I still like the more specific message. We can use a more generic "unexpected text" message, but I think it is less useful.

>     1. The latter case in your list, `F<T>>`, yields "unexpected text", not "unexpected input".

That's my mistake, the resource key ends with `unexpected.input` but the English message is "unexpected text".

>     2. Why is there an asymmetry between wording for angle brackets and that of parenthesis?

See my answer to point 1, I like the message to be as specific as possible.

**Comment by hns** [comment]
> I still like the more specific message. We can use a more generic "unexpected text" message, but I think it is less useful.

Maybe something like "unexpected text after parenthesis"?

**Comment by pavelrappo** [comment]
> Yes, you can look at it both ways, either there is a closing parenthesis where it shouldn't be, or there is text following a correctly placed closing parenthesis. We tend to see one or the other depending on whether the text up to the closing parenthesis looks like a proper signature, but it's not as clear to the parser.

I'd expect the parser to report the leftmost problematic character.

**Comment by hns** [comment]
I changed the error message to "unexpected text after parenthesis".  This is a more informative variant of the existing "unexpected text" and always correct as the error is thrown when there is text following the first closing parenthesis.

**Comment by pavelrappo** [comment]
Thanks for updating the error message, Hannes. This PR adds tests for 2 out of 6 items from your list. I think it makes sense to ensure that the remaining 4 items are also tested. I can see that one more item is covered by the existing RefBadParens. That said, I couldn't find tests that cover these 3 cases:

    #foo(int
    #foo(int)x
    F<T

**Comment by hns** [comment]
> ```
> #foo(int
> #foo(int)x
> F<T
> ```

Missing closing parenthesis is tested in `UnterminatedSignature`. I've added `UnterminatedSignature1` for the missing right angle bracket case. Text after closing parens is handled in `RefBadParens1` (it doesn't matter which character follows the closing parenthesis; I changed the test reference to look more like the one above).

**Review by pavelrappo — APPROVED** [review]

**Pull request closed without merging**
