### PR TITLE
8268017: C2: assert(phi_type->isa_int() || phi_type->isa_ptr() || phi_type->isa_long()) failed: bad phi type

### PR DESCRIPTION
**Pull request by rwestrel**
PhiNode::Ideal() needs to support Cast nodes that were added recently.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268017](https://bugs.openjdk.java.net/browse/JDK-8268017): C2: assert(phi_type->isa_int() || phi_type->isa_ptr() || phi_type->isa_long()) failed: bad phi type

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Wang Huang](https://openjdk.java.net/census#whuang) (@Wanghuang-Huawei - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4409/head:pull/4409` \
`$ git checkout pull/4409`

Update a local copy of the PR: \
`$ git checkout pull/4409` \
`$ git pull https://git.openjdk.java.net/jdk pull/4409/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4409`

View PR using the GUI difftool: \
`$ git pr show -t 4409`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4409.diff">https://git.openjdk.java.net/jdk/pull/4409.diff</a>

</details>

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Review by chhagedorn — APPROVED** [review]
Looks good.

**Review by Wanghuang-Huawei — APPROVED** [review]
Looks good to me.

**Comment by rwestrel** [comment]
@iwanowww @chhagedorn @Wanghuang-Huawei thanks for the reviews

**Pull request closed without merging**
