### PR TITLE
JDK-8265394: G1: Improve assert in HeapRegion::reset_not_compacted_after_full_gc

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is a trivial assert message improvement/fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265394](https://bugs.openjdk.java.net/browse/JDK-8265394): G1: Improve assert in HeapRegion::reset_not_compacted_after_full_gc

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 7a4276963835d7731d2daa5e96288e12b3905d15

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3680/head:pull/3680` \
`$ git checkout pull/3680`

Update a local copy of the PR: \
`$ git checkout pull/3680` \
`$ git pull https://git.openjdk.java.net/jdk pull/3680/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3680`

View PR using the GUI difftool: \
`$ git pr show -t 3680`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3680.diff">https://git.openjdk.java.net/jdk/pull/3680.diff</a>

</details>

### CODE REVIEW

**Comment by Hamlin-Li** [comment]
seems that the Build failure on mac is not related to this change.

**Review by tschatzl — APPROVED** [review]
Lgtm and trivial.

**Comment by Hamlin-Li** [comment]
Thanks Thomas for your review.

**Pull request closed without merging**
