### PR TITLE
8323637: Capture hotspot replay files in GHA

### PR DESCRIPTION
**Pull request by magicus**
From the bug report:

jdk/.github/scripts/gen-test-results.sh is capable of capture hs_err_* file for erroneous and failed tests. They are also exposed under tag `<details><summary>View HotSpot error log</summary>`.

I think we can do the same thing for replay files. A replay file is automatically generated when compiler threads encounter a fatal error. sometimes, we can only trigger the compilation error on GHA. attached replay file is invaluable. 

---

I have not figured out how to provoke a replay file on GHA, so this is untested, but since it is based on the hs_err logic I'm pretty confident that it works. If it turns out to be problematic, let's fix it in a follow up.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323637](https://bugs.openjdk.org/browse/JDK-8323637): Capture hotspot replay files in GHA (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17392/head:pull/17392` \
`$ git checkout pull/17392`

Update a local copy of the PR: \
`$ git checkout pull/17392` \
`$ git pull https://git.openjdk.org/jdk.git pull/17392/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17392`

View PR using the GUI difftool: \
`$ git pr show -t 17392`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17392.diff">https://git.openjdk.org/jdk/pull/17392.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17392#issuecomment-1888810498)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks good. 

Except that current GHA is broken, and we would want to give it as spin before integrating. I sent a note to ops@ about this yesterday, but got no reply. Maybe you can poke them a bit? The problem is the git.openjdk.java.net forwarder not working...

**Comment by magicus** [comment]
I agree, we want to see green checks for GHA. I thought it looked like my GHA runs on another branch was working, so maybe it is fixed now. Trying to get GHA to rerun by pushing an empty commit; I have forgotten if this in fact works. :)

**Comment by magicus** [comment]
(Sorry for the force push, I added a dummy commit locally touching real files, but I never intended to push it to this branch)

**Comment by shipilev** [comment]
BTW, you can just go to https://github.com/magicus/jdk/actions/workflows/main.yml -- and trigger the workflow by hand, without doing any commits.

**Comment by magicus** [comment]
I did not think such a run would show up in the check status in the PR..? But maybe the bots are more intelligent than I give them credit for. 🤖  I'll try that next time, thanks!

**Comment by shipilev** [comment]
> I did not think such a run would show up in the check status in the PR..? But maybe the bots are more intelligent than I give them credit for. 🤖 I'll try that next time, thanks!

They would show up here, just not instantaneously. I do that for both initial and workflow re-runs all the time.

**Pull request closed without merging**
