### PR TITLE
8336465: C2: EA incorrectly/unnecessarily checks for clinits

### PR DESCRIPTION
**Pull request by shipilev**
As shown in [JDK-8336103](https://bugs.openjdk.org/browse/JDK-8336103), EA code uses `is_initializer` where we expect to only check for constructors. This PR rewrites it appropriately. This nominally changes the EA behavior, but I do not think it would actually show up anywhere.

Additional testing:
 - [x] Linux AArch64 server fastdebug, all (includes Fuzzer and CTW tests), passed as part of JDK-8336103 testing

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336465](https://bugs.openjdk.org/browse/JDK-8336465): C2: EA incorrectly/unnecessarily checks for clinits (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20190/head:pull/20190` \
`$ git checkout pull/20190`

Update a local copy of the PR: \
`$ git checkout pull/20190` \
`$ git pull https://git.openjdk.org/jdk.git pull/20190/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20190`

View PR using the GUI difftool: \
`$ git pr show -t 20190`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20190.diff">https://git.openjdk.org/jdk/pull/20190.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20190#issuecomment-2230529811)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

When this code was written there was no `is_object_initializer()` method.
Since `<clinit>` is executed only once we never compile them (may be with `-Xcomp).

**Comment by shipilev** [comment]
Thanks! I need a second reviewer, I think.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too. I submitted this through our testing and will report back once it passed.

**Comment by TobiHartmann** [comment]
All tests passed.

**Comment by shipilev** [comment]
Thanks! I am integrating then.

/integrate

**Pull request closed without merging**
