### PR TITLE
8247402: rewrite the implementation requirements for Map::compute()

### PR DESCRIPTION
**Pull request by johnlinp**
This is from the mailing list: http://mail.openjdk.java.net/pipermail/core-libs-dev/2020-June/067213.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Integration blockers
&nbsp;⚠️ The change requires a CSR request to be approved.
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8247402](https://bugs.openjdk.java.net/browse/JDK-8247402)

### Issue
 * [JDK-8247402](https://bugs.openjdk.java.net/browse/JDK-8247402): Documentation for Map::compute contains confusing implementation requirements ⚠️ Title mismatch between PR and JBS.

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/451/head:pull/451`
`$ git checkout pull/451`

### CODE REVIEW

**Comment by pavelrappo** [comment]
The proposed implementation behaves differently from the existing implementation in the case of `null` value. That is, when `map.containsKey(key) == true && map.get(key) == null`. The difference is that the proposed implementation will remove the `(key, null)` mapping if `newValue == null`, whereas the existing implementation will not.

**Comment by pavelrappo** [comment]
Perhaps I should clarify my previous comment. When I said "implementation" what I meant was that pseudo-code inside the `@implSpec` tag, not the actual body of `default V compute(K key, BiFunction<? super K, ? super V, ? extends V> remappingFunction)`.

**Comment by stuart-marks** [comment]
/csr

This change is to a normative portion of the specification, and as such will require a CSR.

**Comment by johnlinp** [comment]
Hi @pavelrappo & @stuart-marks,

Thank you for the review. When I first proposed this patch in the mailing list, the patch looked like this:

```diff
# HG changeset patch
# User John Lin <johnl...@gmail.com>
# Date 1591923561 -28800
#      Fri Jun 12 08:59:21 2020 +0800
# Node ID 03c9b5c9e632a0d6e33a1f13c98bb3b31b1bf659
# Parent  49a68abdb0ba68351db0f140ddac793b1c391bd5
8247402: Rewrite the implementation requirements for Map::compute()

diff --git a/src/java.base/share/classes/java/util/Map.java
b/src/java.base/share/classes/java/util/Map.java
--- a/src/java.base/share/classes/java/util/Map.java
+++ b/src/java.base/share/classes/java/util/Map.java
@@ -1113,17 +1113,12 @@ public interface Map<K, V> {
      * <pre> {@code
      * V oldValue = map.get(key);
      * V newValue = remappingFunction.apply(key, oldValue);
-     * if (oldValue != null) {
-     *    if (newValue != null)
-     *       map.put(key, newValue);
-     *    else
-     *       map.remove(key);
-     * } else {
-     *    if (newValue != null)
-     *       map.put(key, newValue);
-     *    else
-     *       return null;
+     * if (newValue != null) {
+     *     map.put(key, newValue);
+     * } else if (oldValue != null) {
+     *     map.remove(key);
      * }
+     * return newValue;
      * }</pre>
      *
      * <p>The default implementation makes no guarantees about detecting if the
```

which didn't change the pseudo-code implementation.

However, Martin Buchholz reviewed my patch and suggested me to modify it to match the real implementation in HashMap:
https://www.mail-archive.com/core-libs-dev@openjdk.java.net/msg66197.html
https://www.mail-archive.com/core-libs-dev@openjdk.java.net/msg66199.html
https://www.mail-archive.com/core-libs-dev@openjdk.java.net/msg66210.html
Therefore, I modified my patch and submitted it in the original mailing list and in this PR.

I don't think creating a CSR is in the scope of JDK-8247402. I'll create another PR with my original patch. Thanks.

**Comment by johnlinp** [comment]
I've created https://github.com/openjdk/jdk/pull/714.

**Pull request closed without merging**
