### PR TITLE
8305783: x86_64: Optimize AbsI and AbsL

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

This patch optimizes the sequence emitted by `AbsINode` and `AbsLNode` to save some instructions and 1 temp register. Please take a look and kindly leave your reviews.

Thanks a lot.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305783](https://bugs.openjdk.org/browse/JDK-8305783): x86_64: Optimize AbsI and AbsL

### Reviewers
 * [Jasmine Karthikeyan](https://openjdk.org/census#jkarthikeyan) (@jaskarth - Author)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13402/head:pull/13402` \
`$ git checkout pull/13402`

Update a local copy of the PR: \
`$ git checkout pull/13402` \
`$ git pull https://git.openjdk.org/jdk.git pull/13402/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13402`

View PR using the GUI difftool: \
`$ git pr show -t 13402`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13402.diff">https://git.openjdk.org/jdk/pull/13402.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13402#issuecomment-1501089241)

### CODE REVIEW

**Comment by merykitty** [comment]
Running the patch on `org.openjdk.bench.java.lang.MathBench` shows noticeable improvement:

                                            Before                    After
    Benchmark           Mode  Cnt        Score       Error        Score       Error   Units   Change
    MathBench.absInt   thrpt    8  2848176.368 ± 18552.810  3442310.540 ± 65838.237  ops/ms  +20.86%
    MathBench.absLong  thrpt    8  2851886.891 ± 17565.736  3389983.543 ± 36466.553  ops/ms  +18.87%

**Review by jaskarth — COMMENTED** [review]
Patch looks nice! (I am not a reviewer.) I have one comment with the code.

I was also thinking that the unconditional usage of cmov here may lead to performance issues if the abs is part of a loop-carried dependency, as I've seen that happen before with MinI/MaxI nodes before. I did a [small test](https://gist.github.com/jaskarth/d502adfe3a0e82c30b885ce660262161) to see if that was the case here and it seems there's no regression, so very nice!

**Comment by jaskarth** [comment]
Great, thank you!

**Review by jaskarth — APPROVED** [review]

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by merykitty** [comment]
@TobiHartmann Thanks for your review, I will integrate the change

**Pull request closed without merging**
