### PR TITLE
8288707: javax/swing/JToolBar/4529206/bug4529206.java: setFloating does not work correctly

### PR DESCRIPTION
**Pull request by prsadhuk**
Test was failing intermittently around 1 or 2 out of 30 runs. 
Fixed by adding stability code, wait for a sec after frame is visible, set frame to center.
Modified test has run at least 50 times in all platforms and 100 times in linux (where it is seen intermittently) without any issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288707](https://bugs.openjdk.org/browse/JDK-8288707): javax/swing/JToolBar/4529206/bug4529206.java: setFloating does not work correctly

### Reviewers
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Author)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9269/head:pull/9269` \
`$ git checkout pull/9269`

Update a local copy of the PR: \
`$ git checkout pull/9269` \
`$ git pull https://git.openjdk.org/jdk pull/9269/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9269`

View PR using the GUI difftool: \
`$ git pr show -t 9269`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9269.diff">https://git.openjdk.org/jdk/pull/9269.diff</a>

</details>

### CODE REVIEW

**Review by TejeshR13 — COMMENTED** [review]
How does` frame.isFocused()` indicate failure test? Can the test case fail status depend on `ui.Floating() == false`..?

**Comment by mrserb** [comment]
Is it possible to check that the initial bug 4529206 can be verified by the updated test?

**Comment by prsadhuk** [comment]
Yes, initial bug still fails with the updated test

**Review by mrserb — APPROVED** [review]

**Review by TejeshR13 — APPROVED** [review]

**Pull request closed without merging**
