### PR TITLE
8337287: Update image in javax.swing.text.Document.insert

### PR DESCRIPTION
**Pull request by aivanov-jdk**
This changeset updates the image in the documentation for the `Document.insert` method. The image in `Document.remove` was updated by [JDK-4622866](https://bugs.openjdk.org/browse/JDK-4622866) in PR #15701.

Now the illustration of inserting looks similar to removing. The new image is in SVG format.

For reference:

- [`Document.insert` in JDK 22](https://docs.oracle.com/en/java/javase/22/docs/api/java.desktop/javax/swing/text/Document.html#insertString(int,java.lang.String,javax.swing.text.AttributeSet));
- [Updated docs for JDK 24](https://cr.openjdk.org/~aivanov/8337287/api/java.desktop/javax/swing/text/Document.html#insertString(int,java.lang.String,javax.swing.text.AttributeSet)).

As in the case with `remove`, I marked up to classes and members with `{@code}`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337287](https://bugs.openjdk.org/browse/JDK-8337287): Update image in javax.swing.text.Document.insert (**Enhancement** - P4)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) Review applies to [697da25b](https://git.openjdk.org/jdk/pull/20376/files/697da25b8217ea27c237443ca9e9ad72d76417a6)
 * [Abhishek Kumar](https://openjdk.org/census#abhiscxk) (@kumarabhi006 - **Reviewer**) Review applies to [697da25b](https://git.openjdk.org/jdk/pull/20376/files/697da25b8217ea27c237443ca9e9ad72d76417a6)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20376/head:pull/20376` \
`$ git checkout pull/20376`

Update a local copy of the PR: \
`$ git checkout pull/20376` \
`$ git pull https://git.openjdk.org/jdk.git pull/20376/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20376`

View PR using the GUI difftool: \
`$ git pr show -t 20376`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20376.diff">https://git.openjdk.org/jdk/pull/20376.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20376#issuecomment-2256000503)
</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
@prrace Does it make sense to add a sentence which describes the image? I added one for `remove` to explain all the `Position`s in the removed area are collapsed.

Inserting a string is more straightforward: all the `Position`s at and after the insertion point are moved by the length of the inserted string.

**Comment by prrace** [comment]
> @prrace Does it make sense to add a sentence which describes the image? I added one for `remove` to explain all the `Position`s in the removed area are collapsed.
> 
> Inserting a string is more straightforward: all the `Position`s at and after the insertion point are moved by the length of the inserted string.

I missed this question. Yes, sure.

**Comment by mrserb** [comment]
Just curious why the chars are not in the middle of the boxes?

**Comment by aivanov-jdk** [comment]
> Just curious why the chars are not in the middle of the boxes?

They're aligned according to CSS rules:

```css
            text-anchor: middle;
            dominant-baseline: middle;
```

The text is positioned in the middle of the box -0.5 pixels.

However, I agree the text looks visually unbalanced. Indeed, at 200% scale and Arial font, there are 4 pixels on top of ‘T’ and ‘h’, but there are 8 pixels on the bottom of ‘q’. If I use Calibri font, the values are 8 and 9 pixels correspondingly. So it depends on the font used. The situation is similar on macOS.

**Comment by aivanov-jdk** [comment]
> The text is positioned in the middle of the box -0.5 pixels.

Moving the text position by 0.5 seems to help, and the values become equal: 7 on either side.

This needs to be done for the image in `remove` too, so I'd rather do that separately, at a later time.

At this time, the diagrams for `insertString` and `remove` look the same.

**Comment by aivanov-jdk** [comment]
> > > Just curious why the chars are not in the middle of the boxes?
> > 
> > The text is positioned in the middle of the box -0.5 pixels.
> 
> Moving the text position by 0.5 seems to help, and the values become equal: 7 on either side.
> 
> This needs to be done for the image in `remove` too, so I'd rather do that separately, at a later time.

Submitted [JDK-8340580](https://bugs.openjdk.org/browse/JDK-8340580): *Characters in Document diagrams not in the middle*.

**Comment by aivanov-jdk** [comment]
> > Does it make sense to add a sentence which describes the image? I added one for `remove` to explain all the `Position`s in the removed area are collapsed.
> 
> I missed this question. Yes, sure.

@prrace I updated the PR with an example, look for “For example, if the document contains the text…”.

**Comment by aivanov-jdk** [comment]
@mrserb Do you have any other questions?

I'll update the position of text in `Document-insert.svg` and ``Document-remove.svg` separately after this PR is integrated.

**Comment by aivanov-jdk** [comment]
Pinging… Do you, @prrace and @mrserb, have any additional comments?

**Review by mrserb — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
> > > Does it make sense to add a sentence which describes the image? I added one for `remove` to explain all the `Position`s in the removed area are collapsed.
> > 
> > 
> > I missed this question. Yes, sure.
> 
> I updated the PR with an example, look for “For example, if the document contains the text…”.

@prrace Did you have a chance to look at the updated text? The newly added paragraph starts at [line 482](https://github.com/openjdk/jdk/pull/20376/files#diff-db4af1927b99dc7cdea095238dce3e6060258058feaaf587d3b6848562fc1453R482).

**Pull request closed without merging**
