### PR TITLE
8325163: Enable -Wpedantic on clang

### PR DESCRIPTION
**Pull request by magicus**
Inspired by (the later backed-out) [JDK-8296115](https://bugs.openjdk.org/browse/JDK-8296115), I propose to enable `-Wpedantic` for clang. This has already found some irregularities in the code, like mistakenly using `#import` instead of `#include`. In this patch, I disable warnings for these individual buggy or badly written files, but I intend to post follow-up issues on the respective teams to have them properly fixed.

Unfortunately, it is not possible to enable `-Wpedantic` on gcc, since individual warnings in `-Wpedantic` cannot be disabled. This means that code like this:

```
#define DEBUG_ONLY(code) code;

DEBUG_ONLY(foo());
```

will result in a `; ;`. This breaks the C standard, but is benign, and we use it all over the place. On clang, we can ignore this by `-Wno-extra-semi`, but this is not available on gcc.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Whitespace errors (failed with updated jcheck configuration in pull request)

### Issue
 * [JDK-8325163](https://bugs.openjdk.org/browse/JDK-8325163): Enable -Wpedantic on clang (**Enhancement** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [4de3c446](https://git.openjdk.org/jdk/pull/17687/files/4de3c44632640fa1623b8b03b2726224433b64cf)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17687/head:pull/17687` \
`$ git checkout pull/17687`

Update a local copy of the PR: \
`$ git checkout pull/17687` \
`$ git pull https://git.openjdk.org/jdk.git pull/17687/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17687`

View PR using the GUI difftool: \
`$ git pr show -t 17687`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17687.diff">https://git.openjdk.org/jdk/pull/17687.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17687#issuecomment-1924100159)

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
+++++1 for this, anything to help Standard conformance is great! Just a few questions...

**Comment by TheShermanTanker** [comment]
Guess I could work on the gcc counterpart and find a way around the inability to disable \-Wpedantic with it in tandem with this change...

**Review by erikj79 — APPROVED** [review]

**Review by erikj79 — COMMENTED** [review]
Looks like GHA found some more issues.

**Comment by magicus** [comment]
Ah, dtrace triggers `dollar-in-identifier-extension`. Of course...  *sigh*

I actually had this disabled for hotspot on an earlier version of the patch (that had lied dormant in my personal fork for about a year), but I could not reproduce the problem it was supposed to solve now, so I removed it again. Now I know why I had it.

**Comment by magicus** [comment]
> Guess I could work on the gcc counterpart and find a way around the inability to disable -Wpedantic with it in tandem with this change...

I don't think that is possible. The double semicolon rule can only be disabled by disabling pedantic completely. This is not the first time we've run into trouble because gcc do not have fine-grained enough warnings. :( (While clang has always excelled in this area.)

**Comment by kimbarrett** [comment]
> #define DEBUG_ONLY(code) code;
> 
> DEBUG_ONLY(foo());
> ```
> 
> will result in a `; ;`. This breaks the C standard, but is benign, and we use it all over the place. On clang, we can ignore this by `-Wno-extra-semi`, but this is not available on gcc.

All of the -Wpedantic warnings for extra ';' in C++ code I looked at look to
me like a gcc bug (or bugs). C++11 added "empty-declaration", which is
permitted anywhere a normal declaration is permitted (C++14 7), as well as for
class member declarations (C++14 9.2).

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96068
seems to have fixed some, but not all, cases.  It looks like it only removed
the warnings for empty declarations at namespace scope.  I couldn't find
anything for other cases, including empty class member declarations.

I consider the "format '%p' expects argument of type 'void*" warnings to be
not at all helpful.  Fortunately we don't use '%p' in HotSpot, but I don't
know how other groups might feel having this inflicted on them.

Because of the vast numbers of those, I ran out of patience trying to find and
examine other warnings triggered by this option.

Based on that, I'm not feeling very keen on this change.

**Comment by kimbarrett** [comment]
> Inspired by (the later backed-out) [JDK-8296115](https://bugs.openjdk.org/browse/JDK-8296115), I propose to enable `-Wpedantic` for clang. This has already found some irregularities in the code, like mistakenly using `#import` instead of `#include`. In this patch, I disable warnings for these individual buggy or badly written files, but I intend to post follow-up issues on the respective teams to have them properly fixed.

Rather than first turning on pedantic warnings and then (maybe) going back and perhaps fixing things, I'd really prefer
things be done in the other order.  (That's how I handled the recent `-Wparentheses` changes, for example.)

**Comment by dholmes-ora** [comment]
> I consider the "format '%p' expects argument of type 'void*" warnings to be not at all helpful. Fortunately we don't use '%p' in HotSpot,

We do use it in hotspot. Not a huge amount as we have the legacy format specifiers for PTR_FORMAT etc.

**Comment by TheShermanTanker** [comment]
> > Guess I could work on the gcc counterpart and find a way around the inability to disable -Wpedantic with it in tandem with this change...
> 
> I don't think that is possible. The double semicolon rule can only be disabled by disabling pedantic completely. This is not the first time we've run into trouble because gcc do not have fine-grained enough warnings. :( (While clang has always excelled in this area.)

I tried compiling this on both Linux and Windows, and it seems like there are only a few places where the double semicolons are actually a problem (The strangest case was in a NOT\_LP64 macro in mallocHeader.hpp where gcc exploded when parsing a perfectly valid semicolon). This is more of a code style cleanliness check than anything, but as Kim said, it is probably a bug within gcc somewhere. I'll file a gcc bug for this in the meantime

**Comment by TheShermanTanker** [comment]
Created https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113760
Interestingly a gcc maintainer cannot reproduce the issue at all

**Comment by TheShermanTanker** [comment]
@kimbarrett quoting the gcc maintainers

> Yes because the C++ defect report was only for `Spurious semicolons at namespace scope should be allowed`.  See https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#569 .
> 
> 
> ```
> struct f
> {
>   int t;  ;
> };
> ```
> 
> Is not allowed by the C++ standard currently and is a GCC extension, maybe it should have a seperate flag to control that but I am not 100% sure.

**Comment by magicus** [comment]
> at least not for a future version applying to gcc builds.

@kimbarrett @TheShermanTanker Please do not drag gcc into this PR. This is just about clang. Unless gcc makes a serious effort to shape up their inferior warning handling, I don't think we will ever be able to do something similar for gcc. 

But that is not a reason to avoid doing it on clang. In general, we have tried to utilize the strength of every compiler, regardless of if all the other compilers could detect the same problem or not.

**Comment by magicus** [comment]
Also, a general note about the parts of `pedantic` that is globally disabled in this PR (like `extra-semi` and `format-pedantic`). It might very well be that the offending code is restricted to a few places (if these places are in commonly included header files, I was forced to disable the warning globally), and that it can be rather easily fixed.

All the better! But there is still no reason to do that *before* checking in this PR. Let's just get the minimum bar raised first. Then we can adress the issue of fixing the code to get rid of the exceptions for `extra-semi` and `format-pedantic`, if it is possible and if we want it. The latter is not at all clear; the rest of the list of globally disabled warnings (like `unused-parameter`) are warnings that we have agreed is useless, and only unfortunately dragged in with a catch-all flag like `-Wall` or `-Wextra`. From my PoV, the same could be said about `extra-semi`.

**Comment by TheShermanTanker** [comment]
> > at least not for a future version applying to gcc builds.
> 
> @kimbarrett @TheShermanTanker Please do not drag gcc into this PR. This is just about clang. Unless gcc makes a serious effort to shape up their inferior warning handling, I don't think we will ever be able to do something similar for gcc.
> 
> But that is not a reason to avoid doing it on clang. In general, we have tried to utilize the strength of every compiler, regardless of if all the other compilers could detect the same problem or not.

Hey, I never said anything about gcc compatibility being a blocker for this changeset :)
(I do have however a couple a questions which are listed above)

**Comment by magicus** [comment]
I am sorry, but all I can see is:

> Just a few questions...

and then your comment ends. And I can't find any other comment with a list of questions.

**Comment by magicus** [comment]
> The other concern I had was that there are a ton of disabled warnings added by this change, but I guess that's already been answered by that other reply

Just to be clear: these warnings have never been turned on. They are implicitly turned on by `-Wpedantic`; and this works fine with most files, but this improved scrutiny catches issues in some files. My idea is to file bugs on these individual disabled warnings, to have the actual problem fixed, but as follow up to this PR.

**Comment by TheShermanTanker** [comment]
> > Shouldn't this be -pedantic -Wpedantic, and wouldn't this be better positioned at where HotSpot currently sets -permissive- for Microsoft Visual C++ (In other words, TOOLCHAIN_CFLAGS_JVM and TOOLCHAIN_CFLAGS_JDK)? The 2 options are not the same, at least on gcc, and I'm unsure if the same is true for clang
> 
> (It is really weird, I cannot find that original comment anywhere in the Github PR :-()
> 
> As far as I have been able to determine, -Wpedantic and -pedantic are aliases on gcc > 5, and the same is true for clang. -Wpedantic seems to be the preferred way nowadays.
> 
> `TOOLCHAIN_CFLAGS_JVM` is arguably if not wrong so at least not the best place to put `-permissive-`. `-Wpermissive` belongs with `-Wall -Wextra`.

TOOLCHAIN\_CFLAGS\_JVM and TOOLCHAIN\_CFLAGS\_JDK have, until now, been where the \-Zc: conformance options are passed, which is why I recommended adding them there, to match what Visual C++ does at the moment. Maybe I have it the other way around, and it is Visual C++ that needs to be changed to match clang (Both for permissive\- and \-Zc: options)

**Comment by TheShermanTanker** [comment]
The following is all that I was able to find, on the latest gcc docs. Nothing came up for clang for the search term "\-pedantic vs \-Wpedantic"

> -pedantic-errors
> Give an error whenever the base standard (see -Wpedantic) requires a diagnostic, in some cases where there is undefined behavior at compile-time and in some other cases that do not prevent compilation of programs that are valid according to the standard. This is not equivalent to -Werror=pedantic: the latter option is unlikely to be useful, as it only makes errors of the diagnostics that are controlled by -Wpedantic, whereas this option also affects required diagnostics that are always enabled or controlled by options other than -Wpedantic.

**Comment by magicus** [comment]
The split in different categories of flags is perhaps not perfect, and more a heuristic to help us manage them. However, I think we are talking about two different categories here. The `/Z` flags change the behavior of the compiler to be more standards compliant (similar to `-std=c++1` on gcc/clang). The `-Wpedantic" flag enables a batch of additional warnings on top of `-Wall` and `-Wextra`. The only way this makes it more "standards compliant" is that the standard requires the compiler to produce a warning in these situations. But that is not really why we want to turn it on; we want it to be able to catch bad or suboptimal code.

**Comment by kimbarrett** [comment]
> @kimbarrett quoting the gcc maintainers
> 
> > Yes because the C++ defect report was only for `Spurious semicolons at namespace scope should be allowed`.  See https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#569 .
> > ```
> > struct f
> > {
> >   int t;  ;
> > };
> > ```
> >   
> > Is not allowed by the C++ standard currently and is a GCC extension, maybe it should have a seperate flag to control that but I am not 100% sure.

That's incorrect, and I've replied in the gcc bug.  C++14 added "empty-declaration" to "member-declaration" (C++ 9.2).

**Comment by kimbarrett** [comment]
> > I consider the "format '%p' expects argument of type 'void*" warnings to be not at all helpful. Fortunately we don't use '%p' in HotSpot,
> 
> We do use it in hotspot. Not a huge amount as we have the legacy format specifiers for PTR_FORMAT etc.

You are correct, we do use "%p" a fair amount (107 lines today).

I thought we didn't, because we were instead supposed to use INTPTR_FORMAT and
the (currently?) equivalent PTR_FORMAT. Those macros aren't legacy, they are
to provide consistent output across platforms. "%p" provides implementation
defined output. For example, if I remember correctly, gcc "%p" prints "(null)"
for nullptr, with no mechanism (such as a conversion flag) to control that. If
you are printing a table of pointers, and you expect only numeric values
because you are going to be processing the table or copying it into a
spreadsheet or the like, that gcc-specific behavior isn't very helpful.

Instead, we're "supposed" to use the `p2i` function and PTR_FORMAT for
printing pointers, to get the same output on all platforms. That idiom also
avoids the not very helpful -Wpedantic warnings.

**Comment by kimbarrett** [comment]
> > @kimbarrett quoting the gcc maintainers
> > > Yes because the C++ defect report was only for `Spurious semicolons at namespace scope should be allowed`.  See https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#569 .
> > > ```
> > > struct f
> > > {
> > >   int t;  ;
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is not allowed by the C++ standard currently and is a GCC extension, maybe it should have a seperate flag to control that but I am not 100% sure.
> 
> That's incorrect, and I've replied in the gcc bug. C++14 added "empty-declaration" to "member-declaration" (C++ 9.2).

With my additional information the gcc bug has now been confirmed.

**Comment by TheShermanTanker** [comment]
I can't seem to find the post now but there was one mentioning about needing information on what warnings \-Wpedantic enables, and well... It's quite a lot: https://clang.llvm.org/docs/DiagnosticsReference.html#wpedantic

I also have Jonathan Wakely's confirmation that \-pedantic and \-Wpedantic aren't the same, but this may not be as relevant to the discussion at hand

**Comment by magicus** [comment]
This PR triggered a lot of discussion about C++ standards, gcc behavior, and possible breaches of coding standards in Hotspot -- but not a lot of discussion about the actual content of the PR.

Is there anything in this proposed PR that you gentlemen disagree with or object to? Or is this fine to push as a step in our ongoing pursuit of increasing the code quality, that can (and will) be followed by many more?

**Review by TheShermanTanker — APPROVED** [review]
No objections from me, though I still think \-pedantic \-Wpedantic should be placed where Visual Studio currently places \-permissive\- for HotSpot

**Comment by kimbarrett** [comment]
> Is there anything in this proposed PR that you gentlemen disagree with or object to? Or is this fine to push as a step in our ongoing pursuit of increasing the code quality, that can (and will) be followed by many more?

Yes.  As I said earlier:
"Without knowing what the actual warnings are that are being triggered and then
suppressed, I can't even begin to evaluate this change."

**Comment by magicus** [comment]
Here is the full list: https://clang.llvm.org/docs/DiagnosticsReference.html#wpedantic

**Comment by dholmes-ora** [comment]
> I thought we didn't, because we were instead supposed to use INTPTR_FORMAT and
the (currently?) equivalent PTR_FORMAT. Those macros aren't legacy, they are
to provide consistent output across platforms. "%p" provides implementation
defined output. 

My understanding/recollection was that those issues with `%p` had gone away and so we could start using it.

**Comment by dholmes-ora** [comment]
I think given the warnings have been enabled globally, but disabled locally where they cause build failures, and JBS issues will be filed for each of those special cases, then this is a reasonable change to make. It is then up to component teams to fix code where applicable, and enable disabled warnings in the future.

**Comment by kimbarrett** [comment]
> Here is the full list: https://clang.llvm.org/docs/DiagnosticsReference.html#wpedantic

I know about that list, and that's not what I was asking for. I want to
understand the impact on *our* code. What warnings are arising from *our*
code, how difficult are the fixes, and how beneficial are the fixes.

Looking through the list of warnings it can generate, I don't see much that
looks useful. I'm inclined to agree with Andrew Haley's comment in (draft)
https://github.com/openjdk/jdk/pull/17727#issuecomment-1929178213. It might be
that there are some specific warning options that are part of it that might be
worth turning on (or working toward), but it's mostly uncompelling.

The two that had bazillions of occurrences when I tried with gcc were (1) a
gcc bug (incorrect warning about extra semis), and (2) a completely non-useful
requirement that "%p" format spec only accepts exactly void*, with no implicit
conversions from other pointer types. Clang presumably doesn't have the
former, and I don't know about the latter.

**Review by prrace — APPROVED** [review]
OK, although it would have been nice if you could have summarised what -pedantic and vla-extension are, so I didn't have to go and do research.

**Comment by magicus** [comment]
Keep it for a bit more, bot.

**Comment by magicus** [comment]
I'll close this now. I guess if we want to make progress on this, we will probably have to evaluate every individual warning separately, and add those which does make sense (e.g. `import-preprocessor-directive-pedantic`), and ignore the rest. I personally will not have time nor interest in driving this forward, at least not right now.

**Pull request closed without merging**
