### PR TITLE
8324811: java/nio/file/Files/CopyMoveVariations.java fails run with non-root user

### PR DESCRIPTION
**Pull request by sendaoYan**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324811](https://bugs.openjdk.org/browse/JDK-8324811): java/nio/file/Files/CopyMoveVariations.java fails run with non-root user (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17606/head:pull/17606` \
`$ git checkout pull/17606`

Update a local copy of the PR: \
`$ git checkout pull/17606` \
`$ git pull https://git.openjdk.org/jdk.git pull/17606/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17606`

View PR using the GUI difftool: \
`$ git pr show -t 17606`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17606.diff">https://git.openjdk.org/jdk/pull/17606.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17606#issuecomment-1913645243)

### CODE REVIEW

**Comment by sendaoYan** [comment]
Before this PR, this testcase run fail with non-root user. I think the this testcase author run this testcase with root user or privilege users. I think it's necessary to make tests run pass with non-root users.

When run this test case with root user, it will not cause java.nio.file.AccessDeniedException in any cases, do the test case bug will not expose.


Before the patch apply, the testcase run fail with non-root user:

image


After the patch apply, the testcase run pass with non-root user:

image

**Comment by sendaoYan** [comment]
This PR only change the testcase, the testcase change has been verified. Please review this PR.

**Comment by AlanBateman** [comment]
> This PR only change the testcase, the testcase change has been verified. Please review this PR.

@bplb Did you ever run into this? I don't run the tests with root access and haven't seen this. The current changes in pull/17235 aren't complete but if that change goes in then the test won't be testing /tmp.

**Comment by sendaoYan** [comment]
> > This PR only change the testcase, the testcase change has been verified. Please review this PR.
> 
> @bplb Did you ever run into this? I don't run the tests with root access and haven't seen this. The current changes in pull/17235 aren't complete but if that change goes in then the test won't be testing /tmp.



Only the jtreg work directory and the /tmp on the different disk partition can replay this fail.


image


The first jtreg test, the jtreg work directory is in /dev/vda3, and the tmp is in /dev/loop0, so this test run fail. 
The second jtreg test, use -w options make jtreg directoey point to same to /tmp, this test run success.

**Comment by bplb** [comment]
> Obviously the testcase author run this testcase with root user or privilege users.

How could this conjecture be obvious?

I am the author of this test and I **never** run tests under anything but my own login, and certainly not as `root` or any other privileged user.

**Comment by sendaoYan** [comment]
> > Obviously the testcase author run this testcase with root user or privilege users.
> 
> How could this conjecture be obvious?
> 
> I am the author of this test and I **never** run tests under anything but my own login, and certainly not as `root` or any other privileged user.

Only the jtreg work directory and the /tmp on the different disk partition can replay this fail. As I decsripte https://github.com/openjdk/jdk/pull/17606#issuecomment-1959414716

**Comment by sendaoYan** [comment]
> > This testcase include 3 `Files.move(source, target, options` operations(line 195, line 212, line 232), only the line 195 miss `try catch AccessDeniedException` surround.
> 
> This is because `AccessDeniedException` is not expected. For a file move operation there is no permission requirement unless the source is a directory, in which case it must be writable.
> 
> > And for the line 219, when there is a `AccessDeniedException`, then the source file should miss read permission, so `mode.charAt(1) != 'r'` , rather than `mode.charAt(1) != 'w'`.
> 
> The modes are defined by
> 
> ```
>  99             String[] modes = new String[] {
> 100                 "---------", "r--r--r--", "-w--w--w-", "rw-rw-rw-"
> 101             };
> ```
> 
> so I do not see how `mode.charAt(1)` could ever return `r`. Anyway, as a directory and not a file is being moved, the requirement is that the source directory be wrotable so `w` is correct.
> 
> > So, it seems that it's a testcase bug cause this testcase run fail at some situation.
> 
> As previously mentioned, we have not seen this in any reasonable scenario.
> 
> > Maybe this PR is more reasonable than #17235
> 
> Actually I think #17235 is more reasonable and that this PR should be withdrawn.

In the Linux operating system environment, the file operation permissions may be different if the source and target are in different partitions and if the source and target are in the same partition. I am not professional in this area, so this PR is closed.

**Pull request closed without merging**
