### PR TITLE
8303919: Instant.ofEpochMilli says it can throw an exception that it can't

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
Instant.ofEpochMilli says this:

```
@throws DateTimeException if the instant exceeds the maximum or minimum instant
```

But that can't happen. Even given `Long.MIN_VALUE` or `Long.MAX_VALUE` it does not throw. That's already implicitly tested in [`TestInstant`](https://github.com/openjdk/jdk/blob/a9dba565688a29bef8626488c47519008dcadbe8/test/jdk/java/time/test/java/time/TestInstant.java#L84), which calls it with both those values.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8303926](https://bugs.openjdk.org/browse/JDK-8303926) to be approved

### Issues
 * [JDK-8303919](https://bugs.openjdk.org/browse/JDK-8303919): Instant.ofEpochMilli says it can throw an exception that it can't
 * [JDK-8303926](https://bugs.openjdk.org/browse/JDK-8303926): Instant.ofEpochMilli says it can throw an exception that it can't (**CSR**)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12958/head:pull/12958` \
`$ git checkout pull/12958`

Update a local copy of the PR: \
`$ git checkout pull/12958` \
`$ git pull https://git.openjdk.org/jdk.git pull/12958/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12958`

View PR using the GUI difftool: \
`$ git pr show -t 12958`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12958.diff">https://git.openjdk.org/jdk/pull/12958.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12958#issuecomment-1462691112)

### CODE REVIEW

**Comment by eamonnmcmanus** [comment]
> You're picking on a fine point here that is data dependent, and there's not much value in changing it.

Could you elaborate on this a bit? The way I see it, the argument to `ofEpochMillis` is a `long` with the same meaning as `System.currentTimeMillis()` and the like. Every `long` value is valid, but the current spec implies otherwise. That means that people may waste their time trying to handle the documented exception even though it can never happen.

**Comment by RogerRiggs** [comment]
I see your point, but no one has stumbled into/over it before.
Rationalizing here...
The presence of the exception is a reminder that there are values of epoch milliseconds that `Instant` can not represent.
It is also the case that `long` cannot represent them either.
For example  `Instant.MIN.toEpochMilli()` throws and the method `Instant.ofEpochSecond(sec, nanos)` throws with Long.MIN_VALUE and Long.MAX_VALUE.

**Comment by AlanBateman** [comment]
> I see your point, but no one has stumbled into/over it before.
> Rationalizing here...
> The presence of the exception is a reminder that there are values of epoch milliseconds that `Instant` can not represent.
> It is also the case that `long` cannot represent them either.
> For example `Instant.MIN.toEpochMilli()` throws and the method `Instant.ofEpochSecond(sec, nanos)` throws with Long.MIN_VALUE and Long.MAX_VALUE.

I'm surprised it hasn't come up as declaring that it throws DateTimeException "if the instant exceeds the maximum or minimum instant" is a testable assertion. Maybe as part of this removal there should be an apiNote will some verbiage on what can be represented.

**Comment by AlanBateman** [comment]
I see this PR is timing out but I think the spec should be changed as "throws DateTimeException if ..." is testable and there are no inputs where this exception is thrown.

**Comment by eamonnmcmanus** [comment]
What do I need to do to help the CSR [JDK-8303926](https://bugs.openjdk.org/browse/JDK-8303926) progress?

**Comment by RogerRiggs** [comment]
It slipped too far down in my list.  
I Reviewed the CSR; you can mark it finalized.

**Comment by eamonnmcmanus** [comment]
Done. Thanks!

**Review by RogerRiggs — APPROVED** [review]
Looks good to me.  Thanks

**Pull request closed without merging**
