### PR TITLE
8273314: Add tier4 test groups

### PR DESCRIPTION
**Pull request by shipilev**
During the review of JDK-8272914 that added hotspot:tier{2,3} groups, @iignatev suggested to create tier4 groups that capture all tests not in tiers{1,2,3}. 

Caveats:
 - I excluded `applications` from `hotspot:tier4`, because they require test dependencies (e.g. jcstress).
 - `jdk:tier4` only runs well with `JTREG_KEYWORDS=\!headful` or reduced concurrency with `TEST_JOBS=1`, because headful tests cannot run in parallel

Sample run with `JTREG_KEYWORDS=\!headful`:

```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
>> jtreg:test/hotspot/jtreg:tier4                     3585  3584     0     1 <<
>> jtreg:test/jdk:tier4                               2893  2887     5     1 <<
   jtreg:test/langtools:tier4                            0     0     0     0   
   jtreg:test/jaxp:tier4                                 0     0     0     0   
==============================

real	699m39.462s
user	6626m8.448s
sys	1110m43.704s
```

There are interesting test failures on my machine, which I would address separately.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273314](https://bugs.openjdk.java.net/browse/JDK-8273314): Add tier4 test groups

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5357/head:pull/5357` \
`$ git checkout pull/5357`

Update a local copy of the PR: \
`$ git checkout pull/5357` \
`$ git pull https://git.openjdk.java.net/jdk pull/5357/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5357`

View PR using the GUI difftool: \
`$ git pr show -t 5357`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5357.diff">https://git.openjdk.java.net/jdk/pull/5357.diff</a>

</details>

### CODE REVIEW

**Comment by iignatev** [comment]
> <...> I have excluded `vmTestbase` and `hotspot:tier4`<...>  I have also excluded `applications` from `hotspot:tier4` <...> 

assuming the goal of tier4 is to catch the rest of the tests, I don't think we should exclude `vmTestbase`, `applications` or any other tests from tier4. unless you also want to create tier5 for them.

-- Igor

**Comment by shipilev** [comment]
> > <...> I have excluded `vmTestbase` and `hotspot:tier4`<...>  I have also excluded `applications` from `hotspot:tier4` <...>
> 
> assuming the goal of tier4 is to catch the rest of the tests, I don't think we should exclude `vmTestbase`, `applications` or any other tests from tier4. unless you also want to create tier5 for them.

Apart from practicality of using `tier4`, I think `vmTestbase` and `applications` are separate test suites in their own right. `tier4` is catching all the assorted Hotspot tests that are not part of larger suites. Makes sense?

**Comment by mrserb** [comment]
it looks like the results above do not include the headful tests did you filter them out?
>> jtreg:test/jdk:tier4                               2891  2885     4     2 <<

**Comment by iignatev** [comment]
> > > <...> I have excluded `vmTestbase` and `hotspot:tier4`<...>  I have also excluded `applications` from `hotspot:tier4` <...>
> > 
> > 
> > assuming the goal of tier4 is to catch the rest of the tests, I don't think we should exclude `vmTestbase`, `applications` or any other tests from tier4. unless you also want to create tier5 for them.
> 
> Apart from practicality of using `tier4`, I think `vmTestbase` and `applications` are separate test suites in their own right. `tier4` is catching all the assorted Hotspot tests that are not part of larger suites. Makes sense?

to some extent. I agree that `applications` tests can/should be seen as a separate test suite, yet I differ on `vmTestbase` as the end goal for `vmTestbase` tests is (and always was) to become just another test within hotspot jtreg test suite, hence I don't think we should treat them any different than other jtreg tests. there is also a plan (which I need to formalize and share w/ a broader audience) to rearrange `vmTestbase` tests so they will be placed within the corresponding component subdirectories, which would bring us closer to the end goal and at the same time make it slightly harder to select all `vmTestbase` tests.

-- Igor

**Comment by dholmes-ora** [comment]
Hi Aleksey,

This seems rather arbitrary and subjective to me. The tier 1-3 groupings were driven by existing tier 1-3 notions. But here the definition of tier 4 as "all the rest except ..." is not really a well-defined meaning for tier 4. I don't see that it adds any value. Perhaps there is a need for a group that is "everything except tier 1, tier 2, tier 3, applications, ..." but I wouldn't call that tier 4.

Cheers,
David

**Comment by shipilev** [comment]
@iignatev: OK, I reinstated `vmTestbase` and left `applications` out of `hotspot:tier4`.
@dholmes-ora: Generally speaking, all `tierX` definitions are rather arbitrary, as there seem to be nothing intrinsic about the tests to be in a particular tier. In other words, what `tierX` consists of is a matter of agreement. I'd say `hotspot:tier4` is "all assorted Hotspot tests that are not application-specific suites"
@mrserb: Yes, I ran this on a headless config, so headful tests were skipped, apparently. I'll try to arrange runs on my desktop.

Please see new commit. As `hotspot:tier4` is now much longer, it would take me a while to verify everything works there.

**Comment by mrserb** [comment]
> @mrserb: Yes, I ran this on a headless config, so headful tests were skipped, apparently. I'll try to arrange runs on my desktop.

Then you probably need to skip "printer" tests as well. BTW it will be really good somehow to execute headless tests in tier4 concurrently, and run the headful tests in tier5 sequentially.

**Comment by iignatev** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-dev](mailto:hotspot-dev@mail.openjdk.java.net):_
> 
> On 7/09/2021 1:17 am, Aleksey Shipilev wrote:
> 
> > @dholmes-ora: Generally speaking, all `tierX` definitions are rather arbitrary, as there seem to be nothing intrinsic about the tests to be in a particular tier. In other words, what `tierX` consists of is a matter of agreement. I'd say `hotspot:tier4` is "all assorted Hotspot tests that are not application-specific suites"
> 
> The difference is that your previous work just consolidated the existing
> subsystem tier 1-3 definitions, but here you are choosing to define "all
> the rest" as tier 4. I don't think it is actually helpful/useful to
> anyone - and it bears no resemblance whatsoever to what we call "tier
> 4", so that will just lead to unnecessary confusion IMO.

@dholmes-ora , although I fully agree that this might lead to some misunderstanding b/w Oracle and non-Oracle folks, I don't see how it's different from the previous patch, which introduced `hotspot:tier2` and `hotspot:tier3`. even if we reduce `tierN` to just a set of tests, the test groups added by 8272914 bear as much resemblance to the test sets used in Oracle's tier2-3 as the suggested `hotspot:tier4` groups in this patch to the actual `tier4` definition used in Oracle's internal system, e.g. `hotspot:tier2` group has 0 tests from `test/hotspot/jtreg/compiler`, but Oracle's `tier2` does include a number of  `test/hotspot/jtreg/compiler` tests (which aren't part of `:tier1`). I believe that this patch actually moves us closer to a convergence point, as the union of `hotspot:tier1` -- `hotspot:tier4` test groups is very close to the test sets used in hotspot parts of Oracle's `tier1`  -- `tier4` definitions. 

Thanks,
-- Igor

**Comment by shipilev** [comment]
Once again, the disconnect between Oracle and OpenJDK test definitions seems to be the problem for Oracle's side. Rectifying that disconnect might fall under the scope of this PR, but I have to point out that it is a courtesy of upstream open-source project to care about proprietary downstream definitions.

More to the point: since `tier4` as "catch-all-the-rest" was Igor's idea, I assumed that would be in agreement with Oracle's test definitions. Following this discussion, it seems I assumed wrong. So it puts me in a weird position to be between two Oracle engineers arguing about proprietary test definitions I cannot really know about, and have no decision power about. For all I care for OpenJDK, we might as well model `tier4` after what Oracle does, as to minimize confusion for Oracle engineers. But then again, I have no idea what Oracle means by `tier4`. So as the alternative, I can postpone this PR until you folks have a coherent view on this, or I can just give up on this PR and re-assign the RFE to Igor, assuming he is willing to work this out.

Tell me what you want me to do here.

**Comment by dholmes-ora** [comment]
Hi Aleksey,

I've discussed this with Igor and while I don't agree with the rationale I won't "block it".

Cheers,
David

**Comment by shipilev** [comment]
Progress: 
 a) `hotspot:tier4` still runs cleanly, and a bit faster due to recent `vmTestbase` parallelism improvements.
 b) `jdk:tier4` has a lot of failures in headful mode, probably because the tests do not like to run in parallel, see for example #5533. It would take a while to resolve for all GUI tests. If we are in agreement that current `tier4` definition is good, maybe it would be proper to integrate this PR, and then make `tier4` clean for headful mode?

**Comment by shipilev** [comment]
All right, I am convinced that current patch is as good as it gets. GUI tests still do not run well with default parallelism, but I see no reason to block this integration before that is resolved. Either run `tier4` in headless mode, or limit the parallelism.

@iignatev, @mrserb, @dholmes-ora -- are you good with this?

**Review by mrserb — APPROVED** [review]
It is fine to run headful and headless tests separately.

**Review by iignatev — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
I abstain - you have your reviews.

Cheers,
David

**Comment by shipilev** [comment]
All right, there goes.

/integrate

**Pull request closed without merging**
