### PR TITLE
8345700: tier{1,2,3}_compiler don't cover all compiler tests

### PR DESCRIPTION
**Pull request by lmesnik**
Hi, 
could you please review following fix that update
tier3_compiler test group
so :hotspot_compiler is always a sum of
tier1_compiler, tier2_compiler, tier3_compiler
This is natural splitting of tests into 3 layers. 
The fix is done to execution :hotspot_compiler into 3 tiers with corresponding group names.

New tests in tier3:
9 tests in compiler/ccp/
22 test in ompiler/predicates/
8 tests in compiler/splitif/
So the number is not increased significantly.

The new group
` tier2_ctw`
was introduced for ctw testing. 
It is different from tests in hotspot_compiler, and usually executed separately, So I added it as separate sub-test of tier2.

I moved ctw from tier3 to tier2 to correspond current tiers of Hotspot CI in our system. 
If anyone thinks it should be part of tier3 - we can discuss in PR comments how do deal with it.

@shipilev, could you please take a look and check if these changes are ok to you since you the author of tier2/tier3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345700](https://bugs.openjdk.org/browse/JDK-8345700): tier{1,2,3}_compiler don't cover all compiler tests (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22614/head:pull/22614` \
`$ git checkout pull/22614`

Update a local copy of the PR: \
`$ git checkout pull/22614` \
`$ git pull https://git.openjdk.org/jdk.git pull/22614/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22614`

View PR using the GUI difftool: \
`$ git pr show -t 22614`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22614.diff">https://git.openjdk.org/jdk/pull/22614.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22614#issuecomment-2524085508)
</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
@lmesnik  so this is now going to run all the slow tests in tier3?

**Comment by lmesnik** [comment]
The
 :hotspot_slow_compiler  
is already in tier3.

The are only few groups has been added ad I wrote in description. They are not slow.
The problem is that currently for hotspot compiler tier1 + tier2 + tier3 are not all tests and there is no tier4_compiler.

**Comment by dholmes-ora** [comment]
> The :hotspot_slow_compiler is already in tier3.

Sorry I misread things.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
I don't think the ctw tests should be moved up to tier2. IIUC these are quite heavyweight tests and they will run too often in tier2 compared to tier3.

**Comment by lmesnik** [comment]
> I don't think the ctw tests should be moved up to tier2. IIUC these are quite heavyweight tests and they will run too often in tier2 compared to tier3.

Sorry, it was a typo in description:
`I moved id from tier3 to tier2 to correspond current tiers of Hotspot CI in our system. `
updated to
`I moved ctw from tier3 to tier2 to correspond current tiers of Hotspot CI in our system. `

So fix just align ctw tier to current state.

**Review by dholmes-ora — APPROVED** [review]
Okay - from Oracle perspective changes seem fine as they align with our existing testing.

Need to see how this impacts others.

**Comment by shipilev** [comment]
A good test for these changes is looking at GHA usages and see how well the tests are balanced between the groups. See for example here: https://github.com/lmesnik/jdk/actions/runs/12205347403/usage. I am not sure if this is pre-existing or not, but it looks like `hs/tier1 compiler part 3` is twice as long as `part 1` or `part 2`.

**Comment by lmesnik** [comment]
Thanks, Alexey. I filed https://bugs.openjdk.org/browse/JDK-8345824 to re-balance tier1 parts.
However, it is not related to current issue that fix tier2/3 testing only.

**Comment by shipilev** [comment]
OK, thanks. I'll approve once I see clean GHA run. I think you have already fixed the Xcomp failure, so just pull from master and see what happens?

**Review by shipilev — APPROVED** [review]
Looks fine, assuming GHA turns out green.

**Pull request closed without merging**
