### PR TITLE
JDK-8322366: Add IEEE rounding mode corruption check to JNI checks

### PR DESCRIPTION
**Pull request by MBaesken**
In the review of [JDK-8321017](https://bugs.openjdk.org/browse/JDK-8321017) the idea was introduced to enhance the JNI checker (-Xcheck:jni) by adding IEEE rounding mode corruption checks.
See also https://bugs.openjdk.org/browse/JDK-8295159 for more details on these issues.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322366](https://bugs.openjdk.org/browse/JDK-8322366): Add IEEE rounding mode corruption check to JNI checks (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17391/head:pull/17391` \
`$ git checkout pull/17391`

Update a local copy of the PR: \
`$ git checkout pull/17391` \
`$ git pull https://git.openjdk.org/jdk.git pull/17391/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17391`

View PR using the GUI difftool: \
`$ git pr show -t 17391`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17391.diff">https://git.openjdk.org/jdk/pull/17391.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17391#issuecomment-1888709008)

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Do we not want to print the stack the way we do with `ReportJNIWarning` in `jniCheck.cpp`? Otherwise the warning itself seems of little help in locating the source of the problem.

Also a shame we have to duplicate essentially the same message three times in the function.

**Comment by MBaesken** [comment]
> Do we not want to print the stack the way we do with `ReportJNIWarning` in `jniCheck.cpp`? Otherwise the warning itself seems of little help in locating the source of the problem.
> 

Hi David, sounds like a good suggestion.  But copying the  `ReportJNIWarning`  code  is not really nice , do you think we can reuse the coding ?  Btw. hope it is not a stupid question, where would we get the JavaThread* from that is used in the `ReportJNIWarning`  code ?

**Comment by dholmes-ora** [comment]
>  But copying the ReportJNIWarning code is not really nice , do you think we can reuse the coding ? 

Not really. It is C code and just a static function in a file. To reuse it we would have to expose it as an API in the global namespace. It is only two lines.

> Btw. hope it is not a stupid question, where would we get the JavaThread* from that is used in the ReportJNIWarning code ?

`JavaThread::current()` - at least I assume we always have a `JavaThread`. If not then we would need to use:
```
Thread* current = Thread::current();
if (current->is_Java_thread()) {
  JavaThread::cast(current)->print_jni_stack();
}
```

**Comment by MBaesken** [comment]
Hi David, I added the` print_jni_stack ` output.

**Review by dholmes-ora — APPROVED** [review]
The code duplication is unfortunate. But I can live with it.

Thanks

**Review by RealLucy — APPROVED** [review]
Looks good.

**Comment by MBaesken** [comment]
Hi Lucy and David, thanks for the reviews !

/integrate

**Pull request closed without merging**
