### PR TITLE
8305839: Add application/sql MIME type for SQL file extension

### PR DESCRIPTION
**Pull request by IzumiDIA**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with the updated jcheck configuration)

### Issue
 * [JDK-8305839](https://bugs.openjdk.org/browse/JDK-8305839): Add application/sql MIME type for SQL file extension (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16563/head:pull/16563` \
`$ git checkout pull/16563`

Update a local copy of the PR: \
`$ git checkout pull/16563` \
`$ git pull https://git.openjdk.org/jdk.git pull/16563/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16563`

View PR using the GUI difftool: \
`$ git pr show -t 16563`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16563.diff">https://git.openjdk.org/jdk/pull/16563.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16563#issuecomment-1802188784)

### CODE REVIEW

**Comment by RogerRiggs** [comment]
This looks pretty straight-forward, a review by a member of the network group would be useful.

**Comment by dfuch** [comment]
Have you run tier2 tests? We had random test failures in the past when modifying this table: on some system some of the tests rely on the platform notion of mime-types, and where an extension can legitimately be mapped to different mime types some of the tests will fail.

**Comment by IzumiDIA** [comment]
> 您运行过 tier2 测试吗？过去，我们在修改此表时遇到过随机测试失败：在某些系统上，某些测试依赖于 mime 类型的平台概念，而在扩展可以合法映射到不同 mime 类型的情况下，某些测试将失败。

**Comment by IzumiDIA** [comment]
> Have you run tier2 tests? We had random test failures in the past when modifying this table: on some systems some of the tests rely on the platform notion of mime-types, and where an extension can legitimately be mapped to different mime types some of the tests will fail.

This is my first time participating in open source contribution. Sorry I don't know how to run tier2 tests. But The Internet Assigned Numbers Authority (IANA) registered the ".sql" file extension 10 years ago. That is, ".sql" can uniquely identify a Structured Query Language file. I'm referring to [](https://www.iana.org/assignments/media-types/application/sql).

**Comment by RogerRiggs** [comment]
Read through <repo>/doc/testing.md.

You should be able to build and test something like:
`make test TEST=tier2`

**Pull request closed without merging**
