### PR TITLE
8309268: C2: "assert(in_bb(n)) failed: must be" after JDK-8306302

### PR DESCRIPTION
**Pull request by eme64**
This is the fix to a regression caused in the CMoveV fix JDK-8306302.

I had implicitly assumed that all `Cmp` in the loop also have their `in(1)` inside the loop (`in_bb`). This is not always true, and hence we hit the assert.

**Solution**

However, we know that at least one of the two inputs of a `Cmp` must also be in the loop, else the `Cmp` would float outside the loop. So if `in(1)` is not in the loop then we can just pick `in(2)` for the `velt_type`.

**Testing**
I added 2 regression tests that were provided in the bug, and also extended `TestVectorConditionalMove.java` (though it is currently problemlisted because of an IR framework bug). This extension also triggered the assert, and now properly vectorizes.

I tested up to tier6 and stress testing. I ran the tests both with `TestVectorConditionalMove` problemlisted and without the problemlisting.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309268](https://bugs.openjdk.org/browse/JDK-8309268): C2: "assert(in_bb(n)) failed: must be" after JDK-8306302

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14268/head:pull/14268` \
`$ git checkout pull/14268`

Update a local copy of the PR: \
`$ git checkout pull/14268` \
`$ git pull https://git.openjdk.org/jdk.git pull/14268/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14268`

View PR using the GUI difftool: \
`$ git pr show -t 14268`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14268.diff">https://git.openjdk.org/jdk/pull/14268.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14268#issuecomment-1573253153)

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good, I just have a few minor suggestions.

**Review by robcasloz — APPROVED** [review]
Thanks for addressing my suggestions, looks good!

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by vnkozlov — APPROVED** [review]
Update is good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by eme64** [comment]
Thanks @robcasloz for the review and suggestions!
Thanks @TobiHartmann @vnkozlov for the reviews!
/integrate

**Pull request closed without merging**
