### PR TITLE
8320534: fatal error for the NMTBenchmark test run for the mainline build

### PR DESCRIPTION
**Pull request by afshin-zafari**
This benchmark creates and manages threads internally. So, the number of threads is determined by the benchmark and cannot be set in command line arguments.
The number of threads in BenchmarkParams is checked and an exception is thrown if it is invalid.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320534](https://bugs.openjdk.org/browse/JDK-8320534): fatal error for the NMTBenchmark test run for the mainline build (**Bug** - P3)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17824/head:pull/17824` \
`$ git checkout pull/17824`

Update a local copy of the PR: \
`$ git checkout pull/17824` \
`$ git pull https://git.openjdk.org/jdk.git pull/17824/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17824`

View PR using the GUI difftool: \
`$ git pr show -t 17824`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17824.diff">https://git.openjdk.org/jdk/pull/17824.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17824#issuecomment-1941238212)

### CODE REVIEW

**Comment by jdksjolen** [comment]
How does this resolve the bug?

**Comment by afshin-zafari** [comment]
> How does this resolve the bug?

The bug is when the benchmark runs in multi-threaded using command line number of threads. This benchmark handles and controls the thread internally. So, if externally runs with 1+ threads it will throw exception to notify the user.

**Comment by tstuefe** [comment]
> > How does this resolve the bug?
> 
> The bug is when the benchmark runs in multi-threaded using command line number of threads. This benchmark handles and controls the thread internally. So, if externally runs with 1+ threads it will throw exception to notify the user.

@afshin-zafari Still unclear, sorry. Since there is no bug analysis on the issue, could you explain what the bug is, what causes the memory corruption, and how your patch fixes it?

**Comment by afshin-zafari** [comment]
> @afshin-zafari Still unclear, sorry. Since there is no bug analysis on the issue, could you explain what the bug is, what causes the memory corruption, and how your patch fixes it?

The benchmark (like any other jmh benchmark) can be run from command line. In command line it is possible to set the number of threads that concurrently run every test (method of a Java class) inside the benchmark. In this benchmark, every method creates and manages the threads itself. Simply, there is a THREADS parameter inside the benchmark which accepts values of `{1,2,4,8}` where 1 means single threaded. There is also possible to set the NO-OF-THREADS thru the command line. So, when the benchmark supposed to run with 1 thread but externally the NO-OF-THREADS set to 1+, the program crashes or memory is not safely/correctly shared between threads.
The fix here, reads the NO-OF-THREADS cmd-line arg  and if it is not 1, exits the benchmark by throwing an exception.

**Comment by tstuefe** [comment]
> > @afshin-zafari Still unclear, sorry. Since there is no bug analysis on the issue, could you explain what the bug is, what causes the memory corruption, and how your patch fixes it?
> 
> The benchmark (like any other jmh benchmark) can be run from command line. In command line it is possible to set the number of threads that concurrently run every test (method of a Java class) inside the benchmark. In this benchmark, every method creates and manages the threads itself. Simply, there is a THREADS parameter inside the benchmark which accepts values of `{1,2,4,8}` where 1 means single threaded. There is also possible to set the NO-OF-THREADS thru the command line. So, when the benchmark supposed to run with 1 thread but externally the NO-OF-THREADS set to 1+, the program crashes or memory is not safely/correctly shared between threads. The fix here, reads the NO-OF-THREADS cmd-line arg and if it is not 1, exits the benchmark by throwing an exception.

Sorry, not clear. The thread argument mechanic is, but not why we crash. I would like to prevent this error from being hidden instead of solved, therefore I would like to understand why we crash.

The benchmark calls whitebox APIs, right? Which call os::reserve, os::commit, etc? None of which should be having problems with being called from multiple threads. None of which should result in an overwritten malloc header that in turn crashes the JVM.

**Comment by afshin-zafari** [comment]
> Sorry, not clear. The thread argument mechanic is, but not why we crash. I would like to prevent this error from being hidden instead of solved, therefore I would like to understand why we crash.

The crash is because the part of the benchmark code which is written for sequential run is executed with multiple threads. Even though the code handles/creates/manages the thread internally, when it is run externally (thru command line) with multiple threads, the sequential part will crash.

**Comment by afshin-zafari** [comment]
> The benchmark calls whitebox APIs, right? Which call os::reserve, os::commit, etc? None of which should be having problems with being called from multiple threads. None of which should result in an overwritten malloc header that in turn crashes the JVM.

This benchmark uses `Unsafe` API for `malloc/realloc/free` calls. There is another benchmark (`NMTBenchmark_wb.java`) where the `WhiteBox` API is used for calling NMT virtual memory operations.

**Comment by afshin-zafari** [comment]
@tstuefe, do you have any further comments on this?

**Comment by xmas92** [comment]
I am curious if this whole issue could be solved with:
```diff
diff --git a/test/micro/org/openjdk/bench/vm/runtime/NMTBenchmark.java b/test/micro/org/openjdk/bench/vm/runtime/NMTBenchmark.java
index 9337b4df531..512697db891 100644
--- a/test/micro/org/openjdk/bench/vm/runtime/NMTBenchmark.java
+++ b/test/micro/org/openjdk/bench/vm/runtime/NMTBenchmark.java
@@ -35,7 +35,7 @@
 
 @BenchmarkMode(Mode.AverageTime)
 @OutputTimeUnit(TimeUnit.MILLISECONDS)
-@State(Scope.Benchmark)
+@State(Scope.Thread)
 @Warmup(iterations = 2, time = 1, timeUnit = TimeUnit.SECONDS)
 @Measurement(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)
 public abstract class NMTBenchmark {
```

My experience with JMH is very limited but reading the documentation of [scope](https://javadoc.io/doc/org.openjdk.jmh/jmh-core/latest/org/openjdk/jmh/annotations/Scope.html) when it the state scope is Thread all instances will be distinct across the worker threads so the `long addresses[];` will be distinct per worker thread. While right now this will be shared across the worker threads, so we may have multiple threads freeing the same memory.

**Comment by tstuefe** [comment]
> @tstuefe, do you have any further comments on this?

So the problem is not the invocation of os::malloc, etc, which should be threadsafe? The problem is that we share a single address array across multiple threads in the java part of the benchmark?

If so, okay. I like @xmas92 proposal, if that is possible.

**Comment by afshin-zafari** [comment]
Thank you @xmas92 for your great help. I misunderstood the meaning of the Thread scope.
@tstuefe, the suggested help from @xmas92 is the solution.

**Comment by tstuefe** [comment]
> Thank you @xmas92 for your great help. I misunderstood the meaning of the Thread scope. @tstuefe, the suggested help from @xmas92 is the solution.

Neat! Nice small patch.

**Review by tstuefe — APPROVED** [review]

**Review by xmas92 — APPROVED** [review]
Glad this worked.

**Comment by afshin-zafari** [comment]
Thank you @xmas92 for your help and thank you @tstuefe for your review.
/integrate

**Pull request closed without merging**
