### PR TITLE
8303278: Imprecise bottom type of ExtractB/UB

### PR DESCRIPTION
**Pull request by theRealELiu**
This is a trivial patch, which fixes the bottom type of ExtractB/UB nodes.

ExtractNode can be generated by Vector API Vector.lane(int), which gets the lane element at the given index. A more precise type of range can help to optimize out unnecessary type conversion in some cases.

Below shows a typical case used ExtractBNode

```
  public static byte byteLt16() {
   ByteVector vecb = ByteVector.broadcast(ByteVector.SPECIES_128, 1);
   return vecb.lane(1);
  }

```
In this case, c2 constructs IR graph like:

    ExtractB  ConI(24)
       |     __|
       |    /  |
    LShiftI  __|
       |    /
    RShiftI

which generates AArch64 code:

  movi    v16.16b, #0x1
  smov    x11, v16.b[1]
  sxtb    w0, w11

with this patch, this shift pair can be optimized out by RShiftI's identity [1]. The code is optimized to:

  movi    v16.16b, #0x1
  smov    x0, v16.b[1]

[TEST]

Full jtreg passed except 4 files on x86:

jdk/incubator/vector/Byte128VectorTests.java
jdk/incubator/vector/Byte256VectorTests.java
jdk/incubator/vector/Byte512VectorTests.java
jdk/incubator/vector/Byte64VectorTests.java

They are caused by a known issue on x86 [2].

[1] https://github.com/openjdk/jdk/blob/742bc041eaba1ff9beb7f5b6d896e4f382b030ea/src/hotspot/share/opto/mulnode.cpp#L1052
[2] https://bugs.openjdk.org/browse/JDK-8303508

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303278](https://bugs.openjdk.org/browse/JDK-8303278): Imprecise bottom type of ExtractB/UB

### Reviewers
 * [Quan Anh Mai](https://openjdk.org/census#qamai) (@merykitty - Committer) ⚠️ Review applies to [29e99153](https://git.openjdk.org/jdk/pull/13070/files/29e991531e969f5a028f96d0adf1c41877304b3b)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13070/head:pull/13070` \
`$ git checkout pull/13070`

Update a local copy of the PR: \
`$ git checkout pull/13070` \
`$ git pull https://git.openjdk.org/jdk.git pull/13070/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13070`

View PR using the GUI difftool: \
`$ git pr show -t 13070`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13070.diff">https://git.openjdk.org/jdk/pull/13070.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13070#issuecomment-1473218415)

### CODE REVIEW

**Review by merykitty — APPROVED** [review]

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Review by TobiHartmann — CHANGES_REQUESTED** [review]
This triggers failures in testing.

**Comment by theRealELiu** [comment]
> This triggers failures in testing:
> 
> ```
> jdk/incubator/vector/Byte64VectorTests.java
> 
> java.lang.Exception: failures: 1
> 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:95)
> 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
> 	at java.base/java.lang.Thread.run(Thread.java:1623)
> ```


I think this should be caused by https://bugs.openjdk.org/browse/JDK-8303508. The removed narrowing exposed this issue on x86, that the generated code of ExtractB perhaps does not handle sign-bit correctly. TBH I'm not familiar with x86 instructions... @jatin-bhateja Could you help to take a look at this bug?

**Comment by merykitty** [comment]
Yes x86 does not handle signed extension correctly. `pextrb` and `pextrw` zeroes the upper bits instead of signed extending them. A simple fix is to add `movsx` after those.

https://github.com/openjdk/jdk/blob/bbca7c3ede338a04d140abfe3e19cb27c628a0f5/src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp#L2247

**Comment by jatin-bhateja** [comment]
> Yes x86 does not handle signed extension correctly. `pextrb` and `pextrw` zeroes the upper bits instead of signed extending them. A simple fix is to add `movsx` after those.
> 
> >https://github.com/openjdk/jdk/blob/bbca7c3ede338a04d140abfe3e19cb27c628a0f5/src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp#L2247

image

There are multiple issues in the compilation pipeline here 
- As can be seen above C2 creates ExtractS node with TypeInt::SHORT which is then succeeded by  ConvI2L  node since expander returns a long value.
- Return value is again down casted back short value though an explicit cast operation in java code.

image
  

Currently C2 folds following IR sequence 

```
ExtractS  -> ConvI2L -> ConvL2I ->  LShift (16) -> RShift(16)                   ==>  ExtractS -> return_value
    [Inline expander]    [ Java side down cast long to short -> l2i + i2s]  
```

Because ideal type of ExtractS is TypeInt::SHORT hence entire chain of conversion operations are folded by compiler during idealizations.

There are two ways to address this issue:-
1)  We can set the ideal type of ExtractS node to TypeInt::INT as is done for ExtractB/UB since subsequent java code will handle down casting to generate correct result. This will also fix [JDK-8303508](https://bugs.openjdk.org/browse/JDK-8303508).
2)  Enforce strict semantics of ExtractS/B IR node and thus backends should emit an explicit sign extension instruction movsx for sub-word types.

I agree with @merykitty that 2) solution looks more robust since it will enforce accurate semantics of ExtractS IR.

**Review by TobiHartmann — COMMENTED** [review]
Sure, I'll re-run testing.

**Review by TobiHartmann — APPROVED** [review]
Looks good. All tests passed.

**Pull request closed without merging**
