### PR TITLE
8339678: Update runtime/condy tests to be executed with VM flags

### PR DESCRIPTION
**Pull request by lmesnik**
The tests updated to accept VM flags.
The test runtime.condy.TestEscapeThroughInvokeWithCondy crashes with -Xcomp 
Edited: After @coleenp comments
I filed  bug  https://bugs.openjdk.org/browse/JDK-8339694 for the failure and problemlisted failing test.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339678](https://bugs.openjdk.org/browse/JDK-8339678): Update runtime/condy tests to be executed with VM flags (**Enhancement** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20894/head:pull/20894` \
`$ git checkout pull/20894`

Update a local copy of the PR: \
`$ git checkout pull/20894` \
`$ git pull https://git.openjdk.org/jdk.git pull/20894/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20894`

View PR using the GUI difftool: \
`$ git pr show -t 20894`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20894.diff">https://git.openjdk.org/jdk/pull/20894.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20894#issuecomment-2334564234)

### CODE REVIEW

**Comment by coleenp** [comment]
Are you going to have to problem list these tests?  Shouldn't you file the bug first, and these tests can be pushed with the fix for the crashes?

**Comment by lmesnik** [comment]
I filed and problemlisted failing test.

**Review by coleenp — APPROVED** [review]
Looks good, thank you for problem listing the tests.

**Pull request closed without merging**
