### PR TITLE
8254112: javax/swing/plaf/basic/BasicComboPopup/JComboBoxPopupLocation/JComboBoxPopupLocation.java fails on windows

### PR DESCRIPTION
**Pull request by prsadhuk**
Please review a test issue where the test was seen to be failing on windows mach5 system in hidpi mode. 
I have ran the test locally with different scale factors without reproducing the issue. Also, mach5 job running this test for several iterations works ok.
So, proposing to remove the test from ProblemList.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8254112](https://bugs.openjdk.java.net/browse/JDK-8254112): javax/swing/plaf/basic/BasicComboPopup/JComboBoxPopupLocation/JComboBoxPopupLocation.java fails on windows

### Reviewers
 * [Tejpal Rebari](https://openjdk.java.net/census#trebari) (@trebari - Committer)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/535/head:pull/535`
`$ git checkout pull/535`

### CODE REVIEW

**Comment by prsadhuk** [comment]
mach5 job link is in JBS

**Review by trebari — APPROVED** [review]

**Comment by pankaj-bansal** [comment]
Hello Prasanta,

Should not we try to find what has changed that test was failing few days back and is passing now. Is it sure that it will not fail again like mentioned in https://bugs.openjdk.java.net/browse/JDK-8238720, specially when nothing is really being changed here. It can be an intermittent failure and may fail again even though passing in mach5 job you have run.

**Comment by prsadhuk** [comment]
There might be some lab issue on that day which caused it to fail. There is no mach5 job listed in JDK-8238720 for this test for me to investigate. So,whatever is in my hand I am trying. I have tried to run several iterations and it passed in mach5. Needless to say it is not reproducible locally.

**Comment by pankaj-bansal** [comment]
The bug description in JDK-8238720 says that tests are failing repeatedly on Windows hi-dpi. So if Phil has filled a bug with these tests, they must have failed few times. So finding link to mach5 job should be possible. Most of the intermittent failures are not reproducible locally, so that should not really counts here. Anyway, if you think it is all that can be done here, please go ahead with the exiting reviews or when someone else reviews.

Thanks,
Pankaj

**Review by mrserb — APPROVED** [review]
Let's see how it is going on

**Pull request closed without merging**
