### PR TITLE
JDK-8274320: os::fork_and_exec() should be using posix_spawn

### PR DESCRIPTION
**Pull request by tstuefe**
Hi, may I have reviews for this small patch please?

`os::fork_and_exec()`, used in the hotspot to spawn child programs (scripts etc) in error situations, should be using `posix_spawn()`. 

ATM it uses either `fork()` or `vfork()`. `vfork()` got deprecated on MacOS and we get build errors (JDK-8274293) - even though in this case it would be completely fine to use. This leaves us with `fork()` for MacOS, which has the known problems with large-footprint-parents. This matters here especially since we also use os::fork_and_exec to implement `-XX:OnError` for OOM situations.

We already use posix_spawn() as default for Runtime.exec() since JDK 15, and it is available on all our Unices. We also should use it here.

I kept the name of the function (fork_and_exec) since people know it, even though it's more incorrect now than before.

Tests:
- manual tests using -XX:OnError with various scripts, including checking that env variables are passed correctly
- manually ran runtime/ErrorHandling tests
- GHAs

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274320](https://bugs.openjdk.java.net/browse/JDK-8274320): os::fork_and_exec() should be using posix_spawn

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5698/head:pull/5698` \
`$ git checkout pull/5698`

Update a local copy of the PR: \
`$ git checkout pull/5698` \
`$ git pull https://git.openjdk.java.net/jdk pull/5698/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5698`

View PR using the GUI difftool: \
`$ git pr show -t 5698`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5698.diff">https://git.openjdk.java.net/jdk/pull/5698.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi Thomas,

There is a crucial difference between the requirements of os::fork_and_exec versus the Java Runtime.exec call - in the VM we need to use an async-signal-safe function where possible. fork() is async-signal-safe but posix_spawn is not.

Cheers,
David

**Comment by tstuefe** [comment]
> Hi Thomas,
> 
> There is a crucial difference between the requirements of os::fork_and_exec versus the Java Runtime.exec call - in the VM we need to use an async-signal-safe function where possible. fork() is async-signal-safe but posix_spawn is not.
> 
> Cheers, David

Hi David,

fork() is not async-signal safe either. Since fork() can cause the execution of at-fork handlers.

https://man7.org/linux/man-pages/man7/signal-safety.7.html

```
       *  POSIX.1-2001 TC1 clarified that if an application calls
          fork(2) from a signal handler and any of the fork handlers
          registered by pthread_atfork(3) calls a function that is not
          async-signal-safe, the behavior is undefined. A future
          revision of the standard is likely to remove fork(2) from the
          list of async-signal-safe functions.
```

Therefore I think we don't lose anything by moving to posix_spawn(). But we gain reliability in high-footprint scenarios.

For me, this is an important point. Analysis options such as OnError should be very reliable. They are often used in support situations where time is short and customer patience is limited. Failing analysis causes more iterations or may make analysis even impossible.

Cheers, Thomas

**Comment by tstuefe** [comment]
Hi Xin, thanks for giving this an eye.

> When it comes to Linux/glibc, Linux kernel has Copy-On-Write feature, doesn't it? So this change can't improve Linux further.
> 

Not completely true, since AFAIU you need to at least copy the page tables. posix_spawn (if it uses clone(VFORK) under the hood) should not need to copy the page tables.

> On the other side, Darwin can take benefit from it by changing from fork() to posix_spawn(). If so, why not just use ifdef **APPLE** posix_spwarn() on Darwin? VMError has already used the macro for the vfork issue.

My aim was to simplify the code, not make it more complex. If the argument is "posix_spawn is dangerous during error reporting" we should not use it at all. If that argument does not hold, we can use it on all platforms.

Thanks, Thomas

**Comment by tstuefe** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@mail.openjdk.java.net):_
> 
> Hi Thomas,
> 
> On 29/10/2021 8:47 pm, Thomas Stuefe wrote:
> 
> > On Fri, 29 Oct 2021 10:29:14 GMT, Martin Doerr <mdoerr at openjdk.org> wrote:
> > > Change looks technically good to me, but I can not judge if we can rely on async-signal-safety of posix_spawn. I guess we have to wait until glibc folks have discussed that.
> > 
> > 
> > Thank you Martin.
> > @dholmes-ora : do you have an idea how we could resolve this deadlock? Even with input from the glibc folks, a number of questions will remain unanswered (eg what about the other libcs).
> 
> I've withdrawn my objection to this patch (see response to Florian). Given the advantage of posix_spawn in terms of memory management, and the fact no solution is guaranteed async-signal-safe, you may as well give this a go.
> 
> Cheers, David

Thank you David! Would you then approve it or should I look for a second Reviewer?

**Review by dholmes-ora — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Hi Thomas,

I've approved it so we can start baking it. I hope it will get sufficient test coverage.

Thanks,
David

**Comment by tstuefe** [comment]
Thanks @dholmes-ora. We should extend the OnError tests somewhat.

/integrate

**Pull request closed without merging**
