### PR TITLE
8323645: Remove unused internal sun.net.www.protocol.jar.URLJarFileCallBack interface

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which removes unused code from `sun.net.www.protocol.jar.URLJarFile` and removes `sun.net.www.protocol.jar.URLJarFileCallBack`?

As noted in the linked issue https://bugs.openjdk.org/browse/JDK-8323645 the `sun.net.www.protocol.jar.URLJarFileCallBack` was relevant and used only by Java Plugin code (the "deploy" module in JDK 8) which hasn't been in the JDK for several releases now. Effectively this interface and its sole usage in an internal class of the JDK has been a leftover.

The commit in this PR removes that leftover code. No new tests have been added, given the nature of this change. tier1, tier2, tier3 continue to pass with this change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323645](https://bugs.openjdk.org/browse/JDK-8323645): Remove unused internal sun.net.www.protocol.jar.URLJarFileCallBack interface (**Task** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17396/head:pull/17396` \
`$ git checkout pull/17396`

Update a local copy of the PR: \
`$ git checkout pull/17396` \
`$ git pull https://git.openjdk.org/jdk.git pull/17396/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17396`

View PR using the GUI difftool: \
`$ git pr show -t 17396`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17396.diff">https://git.openjdk.org/jdk/pull/17396.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17396#issuecomment-1889289871)

### CODE REVIEW

**Comment by AlanBateman** [comment]
I think this looks okay, it does seems to a left over from plugin/deploy usage.

**Review by AlanBateman — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
This looks reasonable to me: it removes dead code and add some simplification. We can always reintroduce something like that if we ever need it again.

**Comment by jaikiran** [comment]
Thank you Alan and Daniel for the reviews.

**Pull request closed without merging**
