### PR TITLE
JDK-8315321: [aix] os::attempt_reserve_memory_at must map at the requested address or fail

### PR DESCRIPTION
**Pull request by tstuefe**
There is a long-standing bug on our AIX-port that may cause `os::attempt_reserve_memory_at()` to return a different address than requested.

All other implementations - usually just using mmap(2) - will unmap again if the attach address differs from the requested one.

On AIX, we use either mmap or shmat, depending on some internal logic and our page size goal. If we use shmat (mostly this is the default nowadays on AIX since we need to use System V APIs for 64K pages), we may end up with an address mapped to the next lower segment boundary. Not only may this round down the requested address by SHMLBA, but it has been observed to result in a very high address if the requested address had been very low (e.g. attempting to map below 0x20_0000 gave us 0xa00_0100_a000_0000). I assume (not having the sources to the AIX kernel) that this is either the result of a wraparound while looking for the next lower segment boundary or it is a segment chosen at random.

Whatever the reason for that behavior, the contract for `os::attempt_reserve_memory_at()` is to return either the wish address or NULL, not some other address.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315321](https://bugs.openjdk.org/browse/JDK-8315321): [aix] os::attempt_reserve_memory_at must map at the requested address or fail (**Enhancement** - P4)

### Reviewers
 * @TOatGithub (no known openjdk.org user name / role)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15481/head:pull/15481` \
`$ git checkout pull/15481`

Update a local copy of the PR: \
`$ git checkout pull/15481` \
`$ git pull https://git.openjdk.org/jdk.git pull/15481/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15481`

View PR using the GUI difftool: \
`$ git pr show -t 15481`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15481.diff">https://git.openjdk.org/jdk/pull/15481.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15481#issuecomment-1698717803)

### CODE REVIEW

**Comment by tstuefe** [comment]
Pinging @backwaterred - could you please test this fix?

**Comment by tstuefe** [comment]
Pinging @JoKern65 and @TOatGithub . Could you please review and possibly test this?

**Comment by JoKern65** [comment]
@tstuefe At least the build was fine, but the team is still running the test suite.

**Comment by tstuefe** [comment]
> @tstuefe At least the build was fine, but the team is still running the test suite.

Cool. Thanks!

**Review by TOatGithub — APPROVED** [review]
code seems reasonable to me just from viewing at it

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for fixing it! Are you planning to resolve the `#ifndef AIX` code in https://github.com/openjdk/jdk/commit/89d18ea40f3508f4053824fd47f0b0f85fe1d7c2 separately?

**Comment by tstuefe** [comment]
> LGTM. Thanks for fixing it!

Thanks, Martin! 

> Are you planning to resolve the `#ifndef AIX` code in [89d18ea](https://github.com/openjdk/jdk/commit/89d18ea40f3508f4053824fd47f0b0f85fe1d7c2) separately?

Yes, let's do it after my vacation.

**Comment by TheRealMDoerr** [comment]
Ok, will you file a JBS issue or should I do it?
Please use "/integrate delegate" in case you can't integrate before your vacation.

**Comment by tstuefe** [comment]
> Ok, will you file a JBS issue or should I do it? 

Done https://bugs.openjdk.org/browse/JDK-8315524

> Please use "/integrate delegate" in case you can't integrate before your vacation.

I'll just integrate now. Thanks @JoKern65 @TOatGithub @TheRealMDoerr !

/integrate

**Pull request closed without merging**
