### PR TITLE
8265767: compiler/eliminateAutobox/TestIntBoxing.java crashes on arm32 after 8264649 in debug VMs

### PR DESCRIPTION
**Pull request by huishi-hs**
This patch fix failure exposed by JDK-8264649.

compiler/eliminateAutobox/TestIntBoxing.java crashes on arm32 in Compile::check_no_dead_use assertion.
In LoadNode::eliminate_autobox, early "result" is dead after line 1450 but not added into PhaseGVN worklist for optimization.
Its out_cnt is 0. If it isn't removed, will trigger assertion in Compile::check_no_dead_use.

```
1443             } else if (result->is_Add() && result->in(2)->is_Con() &&
1444                        result->in(1)->Opcode() == Op_LShiftX &&
1445                        result->in(1)->in(2) == phase->intcon(shift)) {
1446               // We can't do general optimization: ((X<<Z) + Y) >> Z ==> X + (Y>>Z)
1447               // but for boxing cache access we know that X<<Z will not overflow
1448               // (there is range check) so we do this optimizatrion by hand here.
1449               Node* add_con = new RShiftXNode(result->in(2), phase->intcon(shift));
                       --- result before is  dead and might not removed
1450               result = new AddXNode(result->in(1)->in(1), phase->transform(add_con)); 
1451             } else 
```

Detail analysis is in https://bugs.openjdk.java.net/browse/JDK-8265767 

@mychris  I have verified compiler/eliminateAutobox/TestIntBoxing.java on qemu, it failed with same assertion and now passes with this fix. Would you please help verify it on arm32 machine?

Testing:
- Passed Tier1-3 on Linux x86_64, release and fastdebug build,  default option and -XX:-TieredCompilation.
- compiler/eliminateAutobox/TestIntBoxing.java on arm32 release/fastdebug/slowdebug

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265767](https://bugs.openjdk.java.net/browse/JDK-8265767): compiler/eliminateAutobox/TestIntBoxing.java crashes on arm32 after 8264649 in debug VMs

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3818/head:pull/3818` \
`$ git checkout pull/3818`

Update a local copy of the PR: \
`$ git checkout pull/3818` \
`$ git pull https://git.openjdk.java.net/jdk pull/3818/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3818`

View PR using the GUI difftool: \
`$ git pr show -t 3818`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3818.diff">https://git.openjdk.java.net/jdk/pull/3818.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
The fix is reasonable.
Add comment `// remove dead node later`
Pass `PhaseIterGVN* igvn` instead of `eliminate_autobox(PhaseGVN* phase)` to simplify code. Note, `can_reshape == true` only for PhaseIterGVN.

**Comment by huishi-hs** [comment]
> The fix is reasonable.
> Add comment `// remove dead node later`
> Pass `PhaseIterGVN* igvn` instead of `eliminate_autobox(PhaseGVN* phase)` to simplify code. Note, `can_reshape == true` only for PhaseIterGVN.

@vnkozlov Thanks for your review! All comments are fixed and pass Tier1-3 on Linux x86_64, release and fastdebug build, default option and -XX:-TieredCompilation.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by mychris** [comment]
Thanks for looking into this issue.
I am currently testing on an ARMv7-A target, and `compiler/eliminateAutobox/TestIntBoxing.java` is passing now :thumbsup:. The whole hotspot tier1 suite will take some time, so I will report back later today, or tomorrow.

**Comment by mychris** [comment]
Hi @huishi-hs, hotspot tier1 passes on my ARMv7-A targets.

**Comment by huishi-hs** [comment]
@mychris Thanks for help verification! 
@vnkozlov Thanks for review! 
Does this patch need a second review before integrate?

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by huishi-hs** [comment]
@TobiHartmann  Thanks!

**Pull request closed without merging**
