### PR TITLE
8254084: Remove TemplateTable::pd_initialize

### PR DESCRIPTION
**Pull request by cl4es**
TemplateTable::pd_initialize is empty on all platforms, and has been so for some time. I suggest removing them.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254084](https://bugs.openjdk.java.net/browse/JDK-8254084): Remove TemplateTable::pd_initialize

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to b50edaf934b46848c07a03d3900b7f7b56635a57

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/529/head:pull/529`
`$ git checkout pull/529`

### CODE REVIEW

**Review by TheRealMDoerr — CHANGES_REQUESTED** [review]
Thanks for cleaning this up. Should get removed from templateTable.hpp, too.

**Review by coleenp — APPROVED** [review]
Echo @TheRealMDoerr wrt templateTable.hpp.   Also trivial.

**Comment by cl4es** [comment]
> Thanks for cleaning this up. Should get removed from templateTable.hpp, 

Fixed

**Review by TheRealMDoerr — APPROVED** [review]

**Pull request closed without merging**
