### PR TITLE
8244675: assert(IncrementalInline || (_late_inlines.length() == 0 && !has_mh_late_inlines()))

### PR DESCRIPTION
**Pull request by iwanowww**
Avoid populating late inline candidates list when post-parse inlining is disabled.  

Testing: hs-tier1 - hs-tier4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8244675](https://bugs.openjdk.java.net/browse/JDK-8244675): assert(IncrementalInline || (_late_inlines.length() == 0 && !has_mh_late_inlines()))

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to b80d2464b03fea69fa0c2a965737aefcd075b310

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5249/head:pull/5249` \
`$ git checkout pull/5249`

Update a local copy of the PR: \
`$ git checkout pull/5249` \
`$ git pull https://git.openjdk.java.net/jdk pull/5249/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5249`

View PR using the GUI difftool: \
`$ git pr show -t 5249`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5249.diff">https://git.openjdk.java.net/jdk/pull/5249.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by iwanowww** [comment]
I have to remote the assert in `LateInlineCallGenerator` ctor because `LateInlineStringCallGenerator` and `LateInlineBoxingCallGenerator` don't depend on `IncrementalInline` flag.

**Review by vnkozlov — APPROVED** [review]
Okay.

**Review by vnkozlov — COMMENTED** [review]
I suggest to move test into `compiler/inlining` directory.

**Comment by iwanowww** [comment]
> I suggest to move test into compiler/inlining directory.

The bug is in Vector API-specific code, so putting the test under compiler/vectorapi looks well-justified.

**Comment by vnkozlov** [comment]
> > I suggest to move test into compiler/inlining directory.
> 
> 
> 
> The bug is in Vector API-specific code, so putting the test under compiler/vectorapi looks well-justified.

Okay.

**Comment by iwanowww** [comment]
Thanks for the reviews, Dean and Vladimir.

/integrate

**Pull request closed without merging**
