### PR TITLE
8294198: Implement isFinite intrinsic for RISC-V

### PR DESCRIPTION
**Pull request by voitylov**
Unlike on x86 (see 8285868 and the discussion in review), isFinite intrinsic turned out to be profitable on RISC-V using the same fclass instruction as for 8293695 (isInfinite instrinsic). Therefore, I'm proposing to have it added on RISC-V in this PR.

benchmark results:

before:

Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  52.824 ± 1.744  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15  16.104 ± 0.358  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15  14.366 ± 2.174  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  49.821 ± 0.330  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15  14.702 ± 0.335  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15  14.749 ± 0.496  ns/op

after:

DoubleClassCheck.testIsFiniteBranch    avgt   15  48.921 ± 0.557  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15  13.716 ± 0.304  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   9.152 ± 0.158  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  47.740 ± 2.028  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15  13.299 ± 0.282  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   9.185 ± 0.396  ns/op

Existing isInfinite jtreg test was altered to be able to use common code for isFinite test and fine-grained requires tag filtering. Existing benchmark was modified to include isFinite case. A typo ("Atleast" -> "At least") was fixed on the way.

Test passed on both release and fastdebug builds. Hotspot tier1 tests were run on x86_64 and RISC-V with no issues.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294198](https://bugs.openjdk.org/browse/JDK-8294198): Implement isFinite intrinsic for RISC-V

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * @AryanP45 (no known github.com user name / role)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10391/head:pull/10391` \
`$ git checkout pull/10391`

Update a local copy of the PR: \
`$ git checkout pull/10391` \
`$ git pull https://git.openjdk.org/jdk pull/10391/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10391`

View PR using the GUI difftool: \
`$ git pr show -t 10391`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10391.diff">https://git.openjdk.org/jdk/pull/10391.diff</a>

</details>

### CODE REVIEW

**Comment by RealFYang** [comment]
May I ask on which platform was the JMH test performed? I see some fluctuations on SiFive Unmatched board:

Before:
Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  32.114 ± 3.514  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   8.656 ± 0.023  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   7.757 ± 1.691  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  32.446 ± 3.130  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.801 ± 0.011  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   7.279 ± 1.483  ns/op

Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  33.724 ± 5.157  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   8.642 ± 0.012  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   7.765 ± 1.711  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  31.401 ± 4.104  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.799 ± 0.014  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   8.234 ± 0.023  ns/op

Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  32.461 ± 3.688  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   8.643 ± 0.007  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   7.772 ± 1.701  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  33.258 ± 3.131  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.815 ± 0.014  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   6.343 ± 1.475  ns/op

After:
Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  33.915 ± 4.193  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   7.736 ± 0.012  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   5.931 ± 0.007  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  33.845 ± 3.449  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.543 ± 0.013  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   6.035 ± 0.006  ns/op

Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  33.421 ± 4.262  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   7.734 ± 0.012  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   5.940 ± 0.010  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  33.348 ± 2.656  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.542 ± 0.013  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   6.040 ± 0.004  ns/op

Benchmark                              Mode  Cnt   Score   Error  Units
DoubleClassCheck.testIsFiniteBranch    avgt   15  31.669 ± 2.517  ns/op
DoubleClassCheck.testIsFiniteCMov      avgt   15   7.761 ± 0.092  ns/op
DoubleClassCheck.testIsFiniteStore     avgt   15   5.940 ± 0.007  ns/op
FloatClassCheck.testIsFiniteBranch     avgt   15  33.508 ± 3.680  ns/op
FloatClassCheck.testIsFiniteCMov       avgt   15   7.534 ± 0.009  ns/op
FloatClassCheck.testIsFiniteStore      avgt   15   6.031 ± 0.007  ns/op

**Comment by voitylov** [comment]
Good you checked on SiFive HW, as I could only check their cookbook for instruction costs. I was using C906.

You're not observing any statistically significant difference in the first benchmark from this change due to higher latency of fclass instruction on SiFive CPU (4 cycles, while C906 has 3 cycles latency for fclass). However, it is still profitable in general as we replace 2 relatively expensive FP instructions with 1 FP + 2 cheap GPR instructions. That's what the rest of the cases demonstrate on both SiFive and C906.

Overall, as the platform matures the instructions costs tend to decrease, so I'd assume fclass will take less cycles in most future implementations.

**Review by RealFYang — APPROVED** [review]
I find the cause of the fluctuations for 'testIsFiniteBranch' lies in randomness of the input.

    @Benchmark
    @OperationsPerInvocation(BUFFER_SIZE)
    public void testIsFiniteBranch() {
        for (int i = 0; i < BUFFER_SIZE; i++) {
            cmovOutputs[i] = Float.isFinite(inputs[i]) ? call() : 7;
        }
    }

Here the C2 JIT code for invoking 'call()' has changed with this patch. The register allocation is
different and hence the difference of saving and restoring of live registers around the method call. So the probability of invoking this method call will affect the JMH result, which is not the case for the other two JMH tests.

For the other two JMH tests, I see the performance gain comes from C2 loop unrolling on SiFive platform. Since your change benefit the other two JMH tests on both SiFive and C906 platforms, looks good to me.

**Review by AryanP45 — APPROVED** [review]
Hi @AryanP45, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user AryanP45 for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Comment by voitylov** [comment]
@vnkozlov could you or someone familiar with C2 look at shared C2 HotSpot changes? I did test it on x86, but any extra testing could help as well.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
I don't think old tests TestFloatClassCheck.java and TestDoubleClassCheck.java are modified correctly - they do nothing now. They have to run compiled methods and verify results.

Other then that changes seem fine.

**Review by vnkozlov — COMMENTED** [review]
Not enough coffee at the morning ;^)
Finally noticed how new and old test interact.
Changes are fine and I submitted testing.

**Review by vnkozlov — APPROVED** [review]
Testing passed.

**Comment by voitylov** [comment]
Thank you @jddarcy @RealFYang @vnkozlov for your reviews.

I also ran the benchmarks with -XX:LoopUnrollLimit=0 -XX:LoopMaxUnroll=0 and see the improvement with these flags as well.

**Pull request closed without merging**
