### PR TITLE
8272417: ZGC: fastdebug build crashes when printing ClassLoaderData

### PR DESCRIPTION
**Pull request by tbzhang**
Following test fails on fastdebug build with the options: "-XX:+UseZGC -XX:+VerifyAfterGC -Xlog:gc*=trace". It crashes on the unknown claim value of the ClassLoaderData

public class A {
    public static void main(String... args) {
        System.gc();
    }
}

The unknown claim value  of the ClassLoaderData is "ClassLoaderData::_claim_other | ClassLoaderData::_claim_strong" which is introduced by the ZVerifyOopClosure. This patch clears the CLD's claimed marks after the ZGC verification

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272417](https://bugs.openjdk.java.net/browse/JDK-8272417): ZGC: fastdebug build crashes when printing ClassLoaderData

### Reviewers
 * [Stefan Karlsson](https://openjdk.java.net/census#stefank) (@stefank - **Reviewer**)
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5107/head:pull/5107` \
`$ git checkout pull/5107`

Update a local copy of the PR: \
`$ git checkout pull/5107` \
`$ git pull https://git.openjdk.java.net/jdk pull/5107/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5107`

View PR using the GUI difftool: \
`$ git pr show -t 5107`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5107.diff">https://git.openjdk.java.net/jdk/pull/5107.diff</a>

</details>

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please contact me at Dalibor.Topic@oracle.com so that I can mark your account as verified.

**Comment by tbzhang** [comment]
> Hi, please contact me at [Dalibor.Topic@oracle.com](mailto:Dalibor.Topic@oracle.com) so that I can mark your account as verified.

Thank you!

**Review by stefank — CHANGES_REQUESTED** [review]
I mentioned in the bug report that this is not enough to correctly fix this bug. Could you fix the printing code instead?

**Comment by tbzhang** [comment]
> I mentioned in the bug report that this is not enough to correctly fix this bug. Could you fix the printing code instead?

Yes, Thanks for your advice!

**Review by stefank — APPROVED** [review]
Looks good. Thanks.

**Review by pliden — APPROVED** [review]
Looks good.

**Pull request closed without merging**
