### PR TITLE
8276848: sun.net.httpserver.simpleserver.CommandLinePositiveTest: test does not specify port

### PR DESCRIPTION
**Pull request by FrauBoes**
This change corrects the server configuration in `testBindAllInterfaces` to specify the port. Additionally, a manual test is added for the case where the port is not specified and the server uses the default port 8000, which might already be in use by another test. To avoid this scenario and the resulting BindException, the test is made manual.

Testing: Tier 1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276848](https://bugs.openjdk.java.net/browse/JDK-8276848): sun.net.httpserver.simpleserver.CommandLinePositiveTest: test does not specify port

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 8e63599f6f14a394b4811a1b3939647af5a584d8

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6361/head:pull/6361` \
`$ git checkout pull/6361`

Update a local copy of the PR: \
`$ git checkout pull/6361` \
`$ git pull https://git.openjdk.java.net/jdk pull/6361/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6361`

View PR using the GUI difftool: \
`$ git pr show -t 6361`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6361.diff">https://git.openjdk.java.net/jdk/pull/6361.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM

**Comment by jaikiran** [comment]
Hello Julia,
Is it intentional that this new manual test and the existing tests in "simpleserver" don't have a `@bug` id noted on their test definition?

**Comment by FrauBoes** [comment]
> Is it intentional that this new manual test and the existing tests in "simpleserver" don't have a `@bug` id noted on their test definition?

I don't think the `@bug` tag is necessary for tests that are added as part of a JEP, but I added it for the new manual test. Thanks!

**Comment by jaikiran** [comment]
Thank you, I didn't know that.

**Pull request closed without merging**
