### PR TITLE
8273361: InfoOptsTest is failing in tier1

### PR DESCRIPTION
**Pull request by shipilev**
Current test checks that informational messages are not printed twice. The failing tests verifies that by checking `java.specification.version` is not present twice in the version string. Effectively, it searches for `18`. But a second `18` could get to version string from anywhere: the Git hash, the user name, etc. It is failing in current GHA due to Git hash containing `18`.

I believe the test should be more conservative: look for more unique strings, and check that the lines start with it. "javac" and "javac full version" seem unique enough. Checking that lines start with "javac" handles the case of accidental version strings that includes that string (think username that includes "javac" for some reason, who are we to judge...).

Additional testing:
 - [x] Affected test passes with default version string
 - [x] Affected test fails with JDK-8266239 reverted
 - [x] Affected test passes with `--with-version-opt=javac`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273361](https://bugs.openjdk.java.net/browse/JDK-8273361): InfoOptsTest is failing in tier1

### Reviewers
 * [Jaikiran Pai](https://openjdk.java.net/census#jpai) (@jaikiran - Committer) ⚠️ Review applies to a3558a440cd59e2fe4810089eba588475c475c75
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5381/head:pull/5381` \
`$ git checkout pull/5381`

Update a local copy of the PR: \
`$ git checkout pull/5381` \
`$ git pull https://git.openjdk.java.net/jdk pull/5381/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5381`

View PR using the GUI difftool: \
`$ git pr show -t 5381`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5381.diff">https://git.openjdk.java.net/jdk/pull/5381.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
I'm not a Reviewer, nor an expert in this area, but this change looks OK to me.

**Comment by shipilev** [comment]
Thanks for review, @jaikiran. Any formal Reviewer wants to chime in? Would be nice to get GHA all green again.

**Review by magicus — APPROVED** [review]

**Comment by lahodaj** [comment]
I would seem better to me if the test didn't depend on hardcoded localized strings (e.g. by printing the content of e.g. `javac --help` and checking the result is the same for `javac --help --help`; or by reading the bundle and using it as a template; or by checking if there are any duplicate line if the output), but since the test didn't do it originally, I don't think it is a stopper.

**Comment by shipilev** [comment]
> by printing the content of e.g. `javac --help` and checking the result is the same for `javac --help --help`; 

Oh, I like that idea. See new commit.

**Review by lahodaj — APPROVED** [review]
Looks good to me.

**Review by magicus — APPROVED** [review]

**Comment by shipilev** [comment]
GHA checks are green, I am integrating.

/integrate

**Pull request closed without merging**
