### PR TITLE
8260264: Move common os_<unix> inline methods to a common posix source file

### PR DESCRIPTION
**Pull request by hseigel**
Please review this fix for JDK-8260264 to move common functions from os_<unix>.inline.hpp files to os_posix.inline.hpp.  Functions ftruncate() and the two numa* functions could also be moved to os_posix.inline.hpp but would require BSD_ONLY and AIX_ONLY macros because of minor differences.

The change was tested by running Mach5 tiers 1,2 on Linux, Mac OS, and Windows, and tiers 3-5 on Linux x64.  Additionally, builds were done on Linux-s390x, Linux-ppc, Linux-arm32, and linux-x86.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260264](https://bugs.openjdk.java.net/browse/JDK-8260264): Move common os_<unix> inline methods to a common posix source file

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to d9597254f92fc87ca3dc9c9570b6bb3da12be8db
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to d9597254f92fc87ca3dc9c9570b6bb3da12be8db
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2267/head:pull/2267`
`$ git checkout pull/2267`

### CODE REVIEW

**Review by iklam — APPROVED** [review]
LGTM

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Hi Harold,

I would suggest not trying to share the guard-page or shadow-page functions so that all such functions reside together in the OS specific header file, and you can see the full situation at a glance.

The I/O function changes seem mostly okay but in a couple of cases you have replaced ::foo64 with ::foo and it is not obvious that is a correct change to make, so please confirm that.

Minor macro use is acceptable if you want to look again at the NUMA and ftruncate cases.

Thanks,
David

**Review by coleenp — APPROVED** [review]
Looks good to me.

**Review by iklam — APPROVED** [review]

**Comment by hseigel** [comment]
Thanks Ioi, David, and Coleen for looking at this change.

I updated the change to restore the guard-page and shadow-page functions to their OS specific header files, restored lseek to lseek64 for non-BSD platforms in os_posix.inline.hpp, and consolidated ftruncate() and the numa functions into os_posix.inline.hpp.

Harold

**Review by dholmes-ora — APPROVED** [review]
Hi Harold,
Thanks for making those updates.  The use of lseek on Linux would have broken 32-bit builds. I don't know if AIX also supports 32-bit builds. On all our 64-bit platforms off_t is 64-bits so we could just use lseek/ftruncate, and only use the "64" variants for 32-bit builds. But what you have also works.

David

**Review by tstuefe — APPROVED** [review]
There is an AIX 32bit but its not supported by the OpenJDK.

The change looks good. Thanks for this cleanup. I tested on AIX, seems to build and work fine.

..Thomas

**Comment by hseigel** [comment]
Thanks Ioi, David, Coleen, and Thomas for the reviews!

/integrate

**Pull request closed without merging**
