### PR TITLE
8265104: CpuLoad and SystemCpuLoad in OperatingSystem MXBean returns -1.0

### PR DESCRIPTION
**Pull request by YaSuenag**
I got -1.0 from both CpuLoad and SystemCpuLoad in OperatingSystem MXBean when I run the application on Fedora 33 x64 which is installed cgroups V2.

jconsole-cpuload

I do not run the application in the container, nor do not run with resource limitation on cgroups, so JMX should report CPU load on host value in this case.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265104](https://bugs.openjdk.java.net/browse/JDK-8265104): CpuLoad and SystemCpuLoad in OperatingSystem MXBean returns -1.0

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3447/head:pull/3447` \
`$ git checkout pull/3447`

Update a local copy of the PR: \
`$ git checkout pull/3447` \
`$ git pull https://git.openjdk.java.net/jdk pull/3447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3447`

View PR using the GUI difftool: \
`$ git pr show -t 3447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3447.diff">https://git.openjdk.java.net/jdk/pull/3447.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Hi Yasumasa,

This strikes me as the wrong fix to the problem. isCpuSetSameAsHostCpuSet is only intended to be used as a simple optimization when the configured cpuset happens to match the hosts. What you are looking for is a fix to the problem when there is no cpuset set at all. It strikes me that in getCpuLoad() if there are no quotas and no effective-cpu-set and no cpusets.cpus value, then it should fallback to using the host values rather than returning -1. That said, the problem may also be that we have a containerMetrics object when no container is actually active! Perhaps that is the true bug here?

Thanks,
David

David

**Comment by YaSuenag** [comment]
> This strikes me as the wrong fix to the problem. isCpuSetSameAsHostCpuSet is only intended to be used as a simple optimization when the configured cpuset happens to match the hosts. What you are looking for is a fix to the problem when there is no cpuset set at all.

I pushed new commit to move the fix into `getCpuLoad()`.

> It strikes me that in getCpuLoad() if there are no quotas and no effective-cpu-set and no cpusets.cpus value, then it should fallback to using the host values rather than returning -1. That said, the problem may also be that we have a containerMetrics object when no container is actually active! Perhaps that is the true bug here?

I think this problem is similar to [JDK-8264482](https://bugs.openjdk.java.net/browse/JDK-8264482) (PR #3280 ). Currently both HotSpot and MBean check whether cgroups exists, but the the host (not into the container) might have it. We've discussed about it in #3280 , then I think it is difficult to modify to check whether the VM is in the container. Thus I think it is reasonable to just return host CPU load value at here.

**Review by jerboaa — APPROVED** [review]
This looks reasonable to me.

**Review by dholmes-ora — APPROVED** [review]
Thanks Yasumasa, this seems a much better approach.

David

**Pull request closed without merging**
