### PR TITLE
8336036: Synthetic documentation for a record's equals is incorrect for floating-point types

### PR DESCRIPTION
**Pull request by liach**
Fixes to Javadoc's default documentation on record classes, that all primitives are compared as if with their wrapper classes' `compare` method by default.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336036](https://bugs.openjdk.org/browse/JDK-8336036): Synthetic documentation for a record's equals is incorrect for floating-point types (**Bug** - P3)

### Reviewers
 * [Pavel Rappo](https://openjdk.org/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20129/head:pull/20129` \
`$ git checkout pull/20129`

Update a local copy of the PR: \
`$ git checkout pull/20129` \
`$ git pull https://git.openjdk.org/jdk.git pull/20129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20129`

View PR using the GUI difftool: \
`$ git pr show -t 20129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20129.diff">https://git.openjdk.org/jdk/pull/20129.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20129#issuecomment-2221700576)

### CODE REVIEW

**Comment by cushon** [comment]
This looks good to me, FWIW. Thanks for the fix!

**Review by pavelrappo — APPROVED** [review]
Looks good.

**Pull request closed without merging**
