### PR TITLE
8255274: [PPC64, s390] wrong StringLatin1.indexOf version matched

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
PPC64 and s390 currently match indexOfChar_U also for StrIntrinsicNode::L. This leads to incorrect results of StringLatin1.indexOf and alreads breaks builds:
Optimizing the exploded image
Error occurred during initialization of boot layer

We need separate match rules for StrIntrinsicNode::U and StrIntrinsicNode::L.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255274](https://bugs.openjdk.java.net/browse/JDK-8255274): [PPC64, s390] wrong StringLatin1.indexOf version matched

### Reviewers
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to b051bd40fa67d02972be59a1c62ee11b50c37c86
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - Committer) ⚠️ Review applies to b051bd40fa67d02972be59a1c62ee11b50c37c86

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/820/head:pull/820`
`$ git checkout pull/820`

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Thanks for fixing this!

**Comment by reinrich** [comment]
The fix looks correct.
But you are adding another 20 lines to an already humonguous file by duplicating a complex instruction form and the diff between the 2 variants is very small. This makes the file hardly readable... at least for humans.
Wouldn't it be possible to have just one instruction form that matches both variants and feed the predicate expression to the `is_byte` parameter of `string_indexof_char`?

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews.
@reinrich That would be nice, but I'm not aware of an easy way to do this. I can't use "((StrIndexOfCharNode*)n)->encoding()" in the "ins_encode" because the Ideal node is only visible during "match".

**Review by reinrich — APPROVED** [review]
Ok, I see. Would be a worthwhile enhancement to preserve information that allows for having just one instruction form.
You might want to change to format string to indicate which version is used. I leave it to your discretion.
Thanks again for fixing.

**Comment by TheRealMDoerr** [comment]
Thanks. I've adapted the format strings.

**Pull request closed without merging**
