### PR TITLE
8251861: Remove unused jdk.internal.ref.SoftCleanable and WeakCleanable

### PR DESCRIPTION
**Pull request by kiranoracle**
Hi Guys,

Please review the fix to remove jdk.internal.ref.SoftCleanable and WeakCleanable classes as there is no visible usage of them in JDK. Currently, only PhantomCleanable is used.

More information can be viewed at https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-August/067997.html

Bug: https://bugs.openjdk.java.net/browse/JDK-8251861

Thanks,
Kiran

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251861](https://bugs.openjdk.java.net/browse/JDK-8251861): Remove unused jdk.internal.ref.SoftCleanable and WeakCleanable

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/616/head:pull/616`
`$ git checkout pull/616`

### CODE REVIEW

**Review by mlchung — APPROVED** [review]
Thanks for taking this one.  Looks okay.

**Review by RogerRiggs — APPROVED** [review]

**Comment by kiranoracle** [comment]
Thanks guys

**Pull request closed without merging**
