### PR TITLE
8308022: update for deprecated sprintf for java.base

### PR DESCRIPTION
**Pull request by XueleiFan**
Hi,

May I have this update reviewed?

The sprintf is deprecated in Xcode 14, and Microsoft Virtual Studio, because of security concerns. The issue was addressed in [JDK-8296812](https://bugs.openjdk.org/browse/JDK-8296812) for building failure, and [JDK-8299378](https://bugs.openjdk.org/browse/JDK-8299378)/[JDK-8299635](https://bugs.openjdk.org/browse/JDK-8299635)/[JDK-8301132](https://bugs.openjdk.org/browse/JDK-8301132) for testing issues . This is a break-down update for sprintf uses in the java.base module.

Thanks,
Xuelei

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308022](https://bugs.openjdk.org/browse/JDK-8308022): update for deprecated sprintf for java.base

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13963/head:pull/13963` \
`$ git checkout pull/13963`

Update a local copy of the PR: \
`$ git checkout pull/13963` \
`$ git pull https://git.openjdk.org/jdk.git pull/13963/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13963`

View PR using the GUI difftool: \
`$ git pr show -t 13963`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13963.diff">https://git.openjdk.org/jdk/pull/13963.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13963#issuecomment-1546215263)

### CODE REVIEW

**Review by naotoj — COMMENTED** [review]
Looked at TimeZone_md.c and Console_md.c, and the changes look reasonable.

**Review by dfuch — COMMENTED** [review]
The libnet changes look reasonable to me.

**Comment by XueleiFan** [comment]
> The libnet changes look reasonable to me.

@dfuch Thank you for the review.  This patch may be still too big as it cross a few components.  To easy to review process, I opened a new PR for libnet update, and will reverse the libnet changes in this PR.  Please review the [new PR](https://github.com/openjdk/jdk/pull/14132).

**Comment by XueleiFan** [comment]
ping ...

**Review by naotoj — APPROVED** [review]
LGTM

**Pull request closed without merging**
