### PR TITLE
JDK-8255544: Create a checked cast

### PR DESCRIPTION
**Pull request by theRealAph**
In many places we've added C-style casts to silence compiler warnings, for example when truncating a size_t to an int when we know the size_t is a small struct. Such casts are inherently risky, because they effectively disable useful compiler warnings. We should add a form of cast that checks at runtime that a truncation does not overflow.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255544](https://bugs.openjdk.java.net/browse/JDK-8255544): Create a checked cast

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/904/head:pull/904`
`$ git checkout pull/904`

### CODE REVIEW

**Comment by theRealAph** [comment]
One thing I should have said: the need for this was triggered by a recent patch to silence many warnings emitted the MSVC AArch64 compiler. It would have been possible to put the checks into the AArch64 back end, but I think we need a centralized way to do it.

**Review by adinn — APPROVED** [review]
This is great. All we need now is to get hotspot devs to use it :-)

**Review by iklam — CHANGES_REQUESTED** [review]
Can we change one place in HotSpot to use this function (preferably in a frequently-used code path), to verity that it really works?

**Comment by theRealAph** [comment]
> Can we change one place in HotSpot to use this function (preferably in a frequently-used code path), to verity that it really works?

How about this?

**Review by iklam — APPROVED** [review]
LGTM

**Review by adinn — APPROVED** [review]
Still looking good

**Review by coleenp — APPROVED** [review]
Looks good to me.

**Comment by mrserb** [comment]
I guess this PR should be closed?

**Pull request closed without merging**
