### PR TITLE
8266257: Fix foreign linker build issues for ppc and s390

### PR DESCRIPTION
**Pull request by mcimadamore**
This patch addresses some build issues introduced by integration of JEP-412.
The support for JEP-412 turns some static functions (e.g.`float_move`, `long_move`) in sharedRuntime into proper member functions, as they need to be referenced by the new support for Panama upcall handlers. Sadly, not all Hotspot ports agree on the number of parameters these functions take - most notably, ppc and s390 have incompatible signatures, and, because of that, failt to build.

A simpler solution is to move these functions to the x86 macro assembler - after all, these functions are specific to a given platform, and excessive sharing should be avoided. This patch does that - and fixes other remaining issues with non-standard hotspot builds (e.g. by adding stab implementation for some unimplemented Panama support).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266257](https://bugs.openjdk.java.net/browse/JDK-8266257): Fix foreign linker build issues for ppc and s390

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4303/head:pull/4303` \
`$ git checkout pull/4303`

Update a local copy of the PR: \
`$ git checkout pull/4303` \
`$ git pull https://git.openjdk.java.net/jdk pull/4303/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4303`

View PR using the GUI difftool: \
`$ git pr show -t 4303`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4303.diff">https://git.openjdk.java.net/jdk/pull/4303.diff</a>

</details>

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
LGTM!

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by TheRealMDoerr** [comment]
I just verified that it builds on real machines. Thanks for fixing!

**Pull request closed without merging**
