### PR TITLE
8326065: Merge Space into ContiguousSpace

### PR DESCRIPTION
**Pull request by albertnetymk**
Merging a super class into its single sub class.

Test: tier1-6

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326065](https://bugs.openjdk.org/browse/JDK-8326065): Merge Space into ContiguousSpace (**Enhancement** - P4)

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Stefan Johansson](https://openjdk.org/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17891/head:pull/17891` \
`$ git checkout pull/17891`

Update a local copy of the PR: \
`$ git checkout pull/17891` \
`$ git pull https://git.openjdk.org/jdk.git pull/17891/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17891`

View PR using the GUI difftool: \
`$ git pr show -t 17891`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17891.diff">https://git.openjdk.org/jdk/pull/17891.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17891#issuecomment-1948898468)

### CODE REVIEW

**Review by plummercj — APPROVED** [review]
The changes look good. It looks like the GenerationFactory removal is something that should have previously been done. Is that the case, or is there something about Space/ContiguousSpace merger that made it possible to remove GenerationFactory?

**Comment by albertnetymk** [comment]
> It looks like the GenerationFactory removal is something that should have previously been done.

True; I overlooked it until the removal of `SpaceClosure` in this PR.

**Review by kstefanj — APPROVED** [review]
Looks good, feels like the files should change name as well. Now when there no longer is a `Space`. But maybe that's even better to do once we have moved `TenuredSpace` into Serial.

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
