### PR TITLE
8282944: GHA: Add Alpine Linux x86_64 pre-integration check

### PR DESCRIPTION
**Pull request by gdams**
Adds Alpine build CI job to the GitHub actions submit.yml. I can add tests too if people think that would be useful but for now I've left it as just build.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8282944](https://bugs.openjdk.java.net/browse/JDK-8282944): GHA: Add Alpine Linux x86_64 pre-integration check

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7771/head:pull/7771` \
`$ git checkout pull/7771`

Update a local copy of the PR: \
`$ git checkout pull/7771` \
`$ git pull https://git.openjdk.java.net/jdk pull/7771/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7771`

View PR using the GUI difftool: \
`$ git pr show -t 7771`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7771.diff">https://git.openjdk.java.net/jdk/pull/7771.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
While to code itself looks like its doing what it claims to do, I wonder about the reason for doing this. This will slurp up even more CPU minutes from the individual OpenJDK contributors free GitHub allowance, and potentially make the pre-submit tests even slower. For what gain?

**Comment by gdams** [comment]
> While to code itself looks like its doing what it claims to do, I wonder about the reason for doing this. This will slurp up even more CPU minutes from the individual OpenJDK contributors free GitHub allowance, and potentially make the pre-submit tests even slower. For what gain?

I think that testing on Alpine is valuable here, it allows us to capture musl-specific edge-cases. I would argue that it's likely more valuable to test the musl code than it is to test the Linux x86 code (maybe we should ramp that down)

**Comment by magicus** [comment]
Do you need to test the entire JDK, or just hotspot?

**Comment by gdams** [comment]
> Do you need to test the entire JDK, or just hotspot?

We could get away with just testing hotspot, I would reiterate my previous comments though around ramping down some of the Linux x86 testing if you're concerned about executor time. There is a far larger group of Alpine Linux users out there then x86 (at least in today's world). This action can also be backported to 11 (and eventually 8) as part of the musl backport which should make things simpler to test.

**Comment by magicus** [comment]
I was not very fond of adding x86 testing to GHA either. :-) I will not enter the fight if that should be removed. (But my personal opinion is that it makes a whole lot more sense to test on a 32-bit architecture than just a different libc.)

If you can change this to just test hotspot, it'd definitely be an improvement. Building hotspot requires just a fraction of the resources needed to build the entire JDK.

**Comment by gdams** [comment]
> I was not very fond of adding x86 testing to GHA either. :-) I will not enter the fight if that should be removed. (But my personal opinion is that it makes a whole lot more sense to test on a 32-bit architecture than just a different libc.)
> 
> If you can change this to just test hotspot, it'd definitely be an improvement. Building hotspot requires just a fraction of the resources needed to build the entire JDK.

@magicus I've refactored this PR and switched it to testing hotspot only: https://github.com/openjdk/jdk/pull/20577

**Pull request closed without merging**
