### PR TITLE
8334647: C2: CastII added by PhaseIdealLoop::add_template_assertion_predicate() should have control

### PR DESCRIPTION
**Pull request by rwestrel**
`PhaseIdealLoop::add_template_assertion_predicate()` creates a new
`CastII` but doesn't set its control. I think it's good practice to
always set the control of a `CastII` when it narrows the type of its
input (it has to be control dependent on some condition that makes the
narrowing possible). This is also motivated by
https://bugs.openjdk.org/browse/JDK-8275202 where a node that becomes
top is used as an indication that control flow where the node changes
type can constant fold. This only works if control is set correctly.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334647](https://bugs.openjdk.org/browse/JDK-8334647): C2: CastII added by PhaseIdealLoop::add_template_assertion_predicate() should have control (**Bug** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19808/head:pull/19808` \
`$ git checkout pull/19808`

Update a local copy of the PR: \
`$ git checkout pull/19808` \
`$ git pull https://git.openjdk.org/jdk.git pull/19808/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19808`

View PR using the GUI difftool: \
`$ git pr show -t 19808`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19808.diff">https://git.openjdk.org/jdk/pull/19808.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19808#issuecomment-2180913858)

### CODE REVIEW

**Comment by chhagedorn** [comment]
IIUC, the rational behind it is that when a `CastII` becomes top, then some control path must also be folded to not end up with a broken graph. And the control path to be folded should be the one on which the `CastII` is control dependent on with a control input?

Are there other places where a `CastII` is currently without control input? If so, should we fix those as well?

**Comment by rwestrel** [comment]
> IIUC, the rational behind it is that when a `CastII` becomes top, then some control path must also be folded to not end up with a broken graph. And the control path to be folded should be the one on which the `CastII` is control dependent on with a control input?

Right.

> Are there other places where a `CastII` is currently without control input? If so, should we fix those as well?

I found this one with manual inspection:

https://github.com/rwestrel/jdk/blob/b05cf955d68034ba014cc63486797876d492ca5f/src/hotspot/share/opto/loopTransform.cpp#L3007

And, yes I think it should have a control because if it's narrowing its input type, then it has to be dependent on some condition.
There are also 2 in `LibraryCallKit::inline_vector_insert()` but I'm not sure what to do with these ones.

**Comment by chhagedorn** [comment]
> > Are there other places where a `CastII` is currently without control input? If so, should we fix those as well?
> 
> I found this one with manual inspection:
> 
> https://github.com/rwestrel/jdk/blob/b05cf955d68034ba014cc63486797876d492ca5f/src/hotspot/share/opto/loopTransform.cpp#L3007
> 
> And, yes I think it should have a control because if it's narrowing its input type, then it has to be dependent on some condition. 

Okay, this looks similar the the case in the current patch. Maybe we can also fix this now?
 
> There are also 2 in `LibraryCallKit::inline_vector_insert()` but I'm not sure what to do with these ones.

Hm okay, hard to tell. But are these `CastII` nodes even required? Can't we just set the type of the `ConvL2I` directly to `TypeInt::BYTE` and `TypeInt::SHORT`?

https://github.com/openjdk/jdk/blob/863b2a991df9204560c4680fc10dd0f68b260217/src/hotspot/share/opto/vectorIntrinsics.cpp#L2487-L2492

Looking at the history, it seems that the code was added when `ConvL2I` was still a non-type node.

Given that we could get rid of those two in `inline_vector_insert()` and only ending up with `CastII` nodes with a control input, we maybe want to force users to always set the control input. What do you think?

**Comment by rwestrel** [comment]
> Given that we could get rid of those two in `inline_vector_insert()` and only ending up with `CastII` nodes with a control input, we maybe want to force users to always set the control input. What do you think?

That sounds reasonable. Does the new commit implement what you have in mind?

**Review by chhagedorn — APPROVED** [review]
That looks good to me, thanks for the updates!

I'll submit some testing.

**Comment by chhagedorn** [comment]
Just thought about it again. What about ensuring that all `ConstraintCastNode` always set a control? I've had a quick look and it seems that we only have one `CastPP` where we do not set a control input. AFAICT, all other nodes set a control:

https://github.com/openjdk/jdk/blob/ca5a438e5a4612c66f70c70a9d425eca0e49e84d/src/hotspot/share/opto/vector.cpp#L491

**Comment by rwestrel** [comment]
> Just thought about it again. What about ensuring that all `ConstraintCastNode` always set a control? I've had a quick look and it seems that we only have one `CastPP` where we do not set a control input. AFAICT, all other nodes set a control:
> 
> https://github.com/openjdk/jdk/blob/ca5a438e5a4612c66f70c70a9d425eca0e49e84d/src/hotspot/share/opto/vector.cpp#L491

Mandating control on all `ConstraintCastNode` sounds reasonable but I have no idea what control would make sense for the case above so maybe it's too constraining to always have to set the control.

**Comment by chhagedorn** [comment]
> Mandating control on all `ConstraintCastNode` sounds reasonable but I have no idea what control would make sense for the case above so maybe it's too constraining to always have to set the control.

Maybe it is, I'm not sure about this case, either. But if this is the only case we could think about just adding the same assert you've inserted for `CastII/LL` at the other `ConstraintCastNodes` (except for `CastPP` due to this unclear case). What do you think about that? This could ensure that if someone is adding any such node without control, they need a good reason to not add a control instead of the other way round.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by rwestrel** [comment]
> > Mandating control on all `ConstraintCastNode` sounds reasonable but I have no idea what control would make sense for the case above so maybe it's too constraining to always have to set the control.
> 
> Maybe it is, I'm not sure about this case, either. But if this is the only case we could think about just adding the same assert you've inserted for `CastII/LL` at the other `ConstraintCastNodes` (except for `CastPP` due to this unclear case). What do you think about that? This could ensure that if someone is adding any such node without control, they need a good reason to not add a control instead of the other way round.

I added what you suggest in the commit.

**Review by chhagedorn — APPROVED** [review]
The update looks good, thanks!

**Comment by rwestrel** [comment]
@chhagedorn thanks for the review. @vnkozlov still good?

**Review by vnkozlov — APPROVED** [review]
Still good. ;^)

**Comment by rwestrel** [comment]
Thanks Vladimir.

**Pull request closed without merging**
