### PR TITLE
8292914: Introduce a system property that enables stable names for lambda proxy classes

### PR DESCRIPTION
**Pull request by sstanoje**
This PR introduces an option to output stable names for the lambda classes in the JDK. A stable name consists of two parts: The first part is the predefined value `$$Lambda$` appended to the lambda capturing class, and the second is a 64-bit hash part of the name. Thus, it looks like `lambdaCapturingClass$$Lambda$hashValue`.
Parameters used to create a stable hash are a superset of the parameters used for lambda class archiving when the CDS dumping option is enabled. During this process, all the mutual parameters are in the same form as they are in the low-level implementation (`SystemDictionaryShared::add_lambda_proxy_class`) of the archiving process.
We decided to use a well-specified `CRC32` algorithm from the standard Java library. We created two 32-bit hashes from the parameters used to create stable names. Then, we combined those two 32-bit hashes into one 64-bit hash value.
We chose `CRC32` because it is a well-specified hash function, and we don't need to write additional code in the JDK. `SHA-256, MD5`, and all other hash functions that rely on `MessageDigest` use lambdas in the implementation, so they are unsuitable for our purpose. We also considered a few different hash functions with a low collision rate. All these functions would require at least 100 lines of additional code in the JDK. The best alternative we found is 64-bit` MurmurHash2`: https://commons.apache.org/proper/commons-codec/jacoco/org.apache.commons.codec.digest/MurmurHash2.java.html.  In case adding a new hash implementation (e.g., Murmur2) to the JDK is preferred, this PR can be easily modified.
We found the post (https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed/145633#145633) that compares different hash functions.
We also tested the `CRC32` hash function against half a billion generated strings, and there were no collisions. Note that the capturing-class name is also part of the lambda class name, so the potential collisions can only appear in a single class. Thus, we do not expect to have name collisions due to a relatively low number of lambdas per class. Every tool that uses this feature should handle potential collisions on its own.  
We found an overall approximation of the collision rate too. You can find it here: https://preshing.com/20110504/hash-collision-probabilities/.

JDK currently adds an atomic integer after `$$Lambda$`, and the names of the lambdas depend on the creation order. In the `TestStableLambdaNames`, we generate all the lambdas two times. In the first run, the method createPlainLambdas generate the following lambdas:

- TestStableLambdaNames$$Lambda$1/0x0000000800c00400
- TestStableLambdaNames$$Lambda$2/0x0000000800c01800
- TestStableLambdaNames$$Lambda$3/0x0000000800c01a38
The same method in the second run generates lambdas with different names:
- TestStableLambdaNames$$Lambda$1471/0x0000000800d10000
- TestStableLambdaNames$$Lambda$1472/0x0000000800d10238
- TestStableLambdaNames$$Lambda$1473/0x0000000800d10470

If we use the introduced flag, generated lambdas are:
- TestStableLambdaNames$$Lambda$65ba26bbc6c7500d/0x0000000800c00400
- TestStableLambdaNames$$Lambda$1569c8c4abe3ab18/0x0000000800c01800
- TestStableLambdaNames$$Lambda$493c0ecaaf682428/0x0000000800c01a38
In the second run of the method, generated lambdas are:
- TestStableLambdaNames$$Lambda$65ba26bbc6c7500d/0x0000000800d10000
- TestStableLambdaNames$$Lambda$1569c8c4abe3ab18/0x0000000800d10238
- TestStableLambdaNames$$Lambda$493c0ecaaf682428/0x0000000800d10470

We can see that the introduced hash value does not change between two calls of the method `createPlainLambdas`. That was not the case in the JDK run without this change. Those lambdas are extracted directly from the test.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blockers
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8292914](https://bugs.openjdk.org/browse/JDK-8292914)
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with the updated jcheck configuration)
&nbsp;⚠️ Whitespace errors (failed with the updated jcheck configuration)

### Issue
 * [JDK-8292914](https://bugs.openjdk.org/browse/JDK-8292914): Lambda proxies have unstable names (**Enhancement** - P4) ⚠️ Title mismatch between PR and JBS. ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/10024/head:pull/10024` \
`$ git checkout pull/10024`

Update a local copy of the PR: \
`$ git checkout pull/10024` \
`$ git pull https://git.openjdk.org/jdk.git pull/10024/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10024`

View PR using the GUI difftool: \
`$ git pr show -t 10024`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10024.diff">https://git.openjdk.org/jdk/pull/10024.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/10024#issuecomment-1237254604)

### CODE REVIEW

**Comment by iklam** [comment]
Have you tested with method references? Two references to the same method will result in a single `JVM_CONSTANT_InvokeDynamic` constant pool entry in the classfile, but it's invoked by two callsites. As a result, two different lambda proxy classes will be generated, as the JVMS requires the invokedynamic resolution to be per callsite, not per constantpool entry.

```
public class ShareBSM {
  public static void main(String args[]) {
    doit1(ShareBSM::func);
    doit2(ShareBSM::func);
  }
  static void func() {  Thread.dumpStack();  }
  static void doit1(Runnable r) {  r.run();  }
  static void doit2(Runnable r) {  r.run();  }
}
```

Here's the output:

```
$ java -cp . -XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames ShareBSM
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
	at ShareBSM.func(ShareBSM.java:8)
	at ShareBSM$$Lambda$1/0x0000000800c009f0.run(Unknown Source)
	at ShareBSM.doit1(ShareBSM.java:12)
	at ShareBSM.main(ShareBSM.java:3)
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
	at ShareBSM.func(ShareBSM.java:8)
	at ShareBSM$$Lambda$2/0x0000000800c00bf8.run(Unknown Source)
	at ShareBSM.doit2(ShareBSM.java:15)
	at ShareBSM.main(ShareBSM.java:4)
```

Will you patch generate the same name for both callsites? Does this matter for your use case?

**Comment by sstanoje** [comment]
> Have you tested with method references? Two references to the same method will result in a single `JVM_CONSTANT_InvokeDynamic` constant pool entry in the classfile, but it's invoked by two callsites. As a result, two different lambda proxy classes will be generated, as the JVMS requires the invokedynamic resolution to be per callsite, not per constantpool entry.
> 
> ```
> public class ShareBSM {
>   public static void main(String args[]) {
>     doit1(ShareBSM::func);
>     doit2(ShareBSM::func);
>   }
>   static void func() {  Thread.dumpStack();  }
>   static void doit1(Runnable r) {  r.run();  }
>   static void doit2(Runnable r) {  r.run();  }
> }
> ```
> 
> Here's the output:
> 
> ```
> $ java -cp . -XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames ShareBSM
> java.lang.Exception: Stack trace
> 	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
> 	at ShareBSM.func(ShareBSM.java:8)
> 	at ShareBSM$$Lambda$1/0x0000000800c009f0.run(Unknown Source)
> 	at ShareBSM.doit1(ShareBSM.java:12)
> 	at ShareBSM.main(ShareBSM.java:3)
> java.lang.Exception: Stack trace
> 	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
> 	at ShareBSM.func(ShareBSM.java:8)
> 	at ShareBSM$$Lambda$2/0x0000000800c00bf8.run(Unknown Source)
> 	at ShareBSM.doit2(ShareBSM.java:15)
> 	at ShareBSM.main(ShareBSM.java:4)
> ```
> 
> Will you patch generate the same name for both callsites? Does this matter for your use case?

@iklam Yes, I tested it against method references too. The patch produces the same names as it should. I enhanced the test with one additional method that will explicitly use method references. We don't want confusion about this in the future.

**Comment by sstanoje** [comment]
Hello, any news regarding this PR? Is there anything else I should do on my side?

**Comment by sstanoje** [comment]
Hi @iklam, is there any additional work I can do on this PR?

**Comment by sstanoje** [comment]
Dummy comment to keep the PR alive.

**Comment by dmlloyd** [comment]
Looking at the code for `InnerClassLambdaMetafactory`, I don't think that the numerical suffix is necessary _at all_. These lambda classes are defined as _hidden_ classes, in which case the class is already created with a unique "name" (in the form of a suffix comprising `/` and some unique identifying digits).

From my own experiments, I simply removed the counter altogether and everything continues to work with the classes simply being named `xxx/xxx/Xxx$$Lambda`. So perhaps the entire mechanism (which consists of ` + counter.incrementAndGet()` within `InnerClassLambdaMetafactory#lambdaClassName`) is unneeded?

I'll also add this comment on to the original issue as well.

**Comment by briangoetz** [comment]
David Llloyd's proposed solution is dramatically less intrusive, so it should be preferred over the one here.

**Comment by thomaswue** [comment]
Having a stable numeric suffix for the lambda class name improves debuggability of the system compared to a solution where all lambdas have the same class name. The stable hash function can probably be simplified given that collisions are less problematic because of #12579.

**Comment by koutheir** [comment]
Dummy comment to keep the PR alive.

**Comment by thomaswue** [comment]
@briangoetz

**Pull request closed without merging**
