### PR TITLE
8280743: HSDB "Monitor Cache Dump" command might throw NPE

### PR DESCRIPTION
**Pull request by plummercj**
ObjectMonitor.object() can be null so we need to defend against it. This bug was discovered by code inspection while working on [JDK-8280555](https://bugs.openjdk.org/browse/JDK-8280555).  We have no test for this, and I'm not sure how to reproduce this with HSDB like the [JDK-8280555](https://bugs.openjdk.org/browse/JDK-8280555) test did.  I did at least verify that the HSDB "Monitor Cache Dump" feature still works after this fix, although none of the monitors had a null object.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280743](https://bugs.openjdk.org/browse/JDK-8280743): HSDB "Monitor Cache Dump" command might throw NPE (**Bug** - P5)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to [a3f3f0e9](https://git.openjdk.org/jdk/pull/15369/files/a3f3f0e9d45afd2446c40f490270d2944cf43ebf)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15369/head:pull/15369` \
`$ git checkout pull/15369`

Update a local copy of the PR: \
`$ git checkout pull/15369` \
`$ git pull https://git.openjdk.org/jdk.git pull/15369/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15369`

View PR using the GUI difftool: \
`$ git pr show -t 15369`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15369.diff">https://git.openjdk.org/jdk/pull/15369.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15369#issuecomment-1686960822)

### CODE REVIEW

**Review by kevinjwalls — APPROVED** [review]
I see ObjectHeap accepts and handles a null, returning null, so the newOop() call is OK to pass a null, though it could be moved to inside the else.  
Maybe you're saying it's best that the Heap decides if null handle means null oop. 8-)

**Comment by plummercj** [comment]
> I see ObjectHeap accepts and handles a null, returning null, so the newOop() call is OK to pass a null, though it could be moved to inside the else.

Ok. I moved it inside the else block.

**Review by sspitsyn — APPROVED** [review]
Looks good and safe to fix. :)
Thanks,
Serguei

**Comment by plummercj** [comment]
Thanks for the reviews Kevin and Serguei!

/integrate

**Pull request closed without merging**
