### PR TITLE
8257057: C2: Improve safepoint processing during vector scalarization pass

### PR DESCRIPTION
**Pull request by iwanowww**
Cast nodes (`CheckCastPP`/`CastPP`) hinders scalarization of vectors since they aren't taken into account when affected safepoints are enumerated.

Proposed fix implements a reversed variant of `Node::uncast()` to find all safepoints which have vectors referenced from their debug info and then uses `Node::uncast()` when iterating over debug edges.  It is safe to ignore cast nodes (even the ones which carry control dependency): `VectorBox` already contains the most precise type information and the vector value it represents is immutable. So, it's safe to replace a fully constructed boxed vector instance with the vector value it contains and rematerialize the equivalent box instance if deoptimization happens.    

Testing:
- `jdk/incubator/vector` tests w/ different flag combinations (no flags, `-Xcomp`, `-XX:+DeoptimizeALot`); 
- tier1-4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (8/8 passed) | ✔️ (2/2 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x86 (build debug)](https://github.com/iwanowww/jdk/runs/1459083353)
- [Linux x86 (build release)](https://github.com/iwanowww/jdk/runs/1459083324)

### Issue
 * [JDK-8257057](https://bugs.openjdk.java.net/browse/JDK-8257057): C2: Improve safepoint processing during vector scalarization pass

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1456/head:pull/1456`
`$ git checkout pull/1456`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Tobias.

**Pull request closed without merging**
