### PR TITLE
8266542: Remove broken -XX:-UseLoopSafepoints flag

### PR DESCRIPTION
**Pull request by TobiHartmann**
Simply running `java -XX:-UseLoopSafepoints` already asserts and more sophisticated testing triggers all kinds of asserts and crashes in various places. [JDK-6232281](https://bugs.openjdk.java.net/browse/JDK-6232281) made an attempt of fixing a common case. I had a quick look on what it would take to fix all cases and it's definitely non trivial. Also, we would need to make sure that new optimizations work without safepoints in loops. I don't see much value in keeping the flag for debugging either because disabling safepoints in loops has massive side-effects on other optimizations.

I therefore propose to remove the flag.

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266542](https://bugs.openjdk.java.net/browse/JDK-8266542): Remove broken -XX:-UseLoopSafepoints flag

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3871/head:pull/3871` \
`$ git checkout pull/3871`

Update a local copy of the PR: \
`$ git checkout pull/3871` \
`$ git pull https://git.openjdk.java.net/jdk pull/3871/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3871`

View PR using the GUI difftool: \
`$ git pr show -t 3871`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3871.diff">https://git.openjdk.java.net/jdk/pull/3871.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by TobiHartmann** [comment]
Thanks for the review, Thomas!

**Review by vnkozlov — APPROVED** [review]
Note, `UseLoopSafepoints` is debug flag so we don't need CSR for removing it.

Consider removing `OptoRemoveUseless` debug flag too because it is related to safepoints and we never used it AFAIK:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/parse1.cpp#L2291

**Comment by kelthuzadx** [comment]
> Consider removing OptoRemoveUseless debug flag too because it is related to safepoints and we never used it AFAIK:

Agree!
FYI: C2 crashes in many places if turned off OptoRemoveUseless, it would takes a lot of time to fix this.

**Pull request closed without merging**
