### PR TITLE
8340552: Harden TzdbZoneRulesCompiler against missing zone names

### PR DESCRIPTION
**Pull request by fweimer-rh**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340552](https://bugs.openjdk.org/browse/JDK-8340552): Harden TzdbZoneRulesCompiler against missing zone names (**Bug** - P5)

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**) Review applies to [04e2e2e0](https://git.openjdk.org/jdk/pull/21112/files/04e2e2e0dec6701d6ba64e194b30d589ddcf33b3)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21112/head:pull/21112` \
`$ git checkout pull/21112`

Update a local copy of the PR: \
`$ git checkout pull/21112` \
`$ git pull https://git.openjdk.org/jdk.git pull/21112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21112`

View PR using the GUI difftool: \
`$ git pr show -t 21112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21112.diff">https://git.openjdk.org/jdk/pull/21112.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21112#issuecomment-2364079121)

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
Looks good. Please update the copyright year before the push. Also, add a "noreg-build" label to the JBS issue if you are not going to add a regression test.

**Review by justin-curtis-lu — APPROVED** [review]
LGTM. I agree that this is difficult to test and being able to build with this change is sufficient testing.

**Review by gnu-andrew — APPROVED** [review]
Copyright year change looks good.

**Pull request closed without merging**
