### PR TITLE
8346304: SA doesn't need a copy of getModifierFlags

### PR DESCRIPTION
**Pull request by coleenp**
Please review this trivial change to remove unused SA code.  Ran serviceability/sa tests, tier1 testing in progress.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8346304](https://bugs.openjdk.org/browse/JDK-8346304): SA doesn't need a copy of getModifierFlags (**Enhancement** - P4)

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22772/head:pull/22772` \
`$ git checkout pull/22772`

Update a local copy of the PR: \
`$ git checkout pull/22772` \
`$ git pull https://git.openjdk.org/jdk.git pull/22772/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22772`

View PR using the GUI difftool: \
`$ git pr show -t 22772`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22772.diff">https://git.openjdk.org/jdk/pull/22772.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22772#issuecomment-2546688717)
</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Looks okay to me.

**Comment by coleenp** [comment]
Do you agree it's trivial?  GHA almost complete/passed.

**Comment by sspitsyn** [comment]
> Do you agree it's trivial?

I'm not sure about it.

**Comment by coleenp** [comment]
ok, I'll wait and see what @plummercj says.

**Review by plummercj — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thanks Chris and Serguei.
/integrate

**Pull request closed without merging**
