### PR TITLE
8335802: Improve startup speed HexFormat uses boolean instead of enum

### PR DESCRIPTION
**Pull request by wenshao**
The current HexFormat defines an Enum to represent LowerCase and UpperCase

```java
class HexFormat {
    private enum Case {
        LOWERCASE,
        UPPERCASE
    }
}
```

This will cause the JVM to load one more class when it starts, which can be seen as follows

```java
public class Startup {
    public static void main(String[] args) {}
}
```

```sh
java -verbose:class Startup
```

```
[0.094s][info][class,load] java.util.HexFormat$Case source: /Users/.../jdk/modules/java.base
```

There are only two cases here, which can be represented by boolean, which is clearer and can improve the startup speed a little bit.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335802](https://bugs.openjdk.org/browse/JDK-8335802): Improve startup speed HexFormat uses boolean instead of enum (**Enhancement** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20060/head:pull/20060` \
`$ git checkout pull/20060`

Update a local copy of the PR: \
`$ git checkout pull/20060` \
`$ git pull https://git.openjdk.org/jdk.git pull/20060/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20060`

View PR using the GUI difftool: \
`$ git pr show -t 20060`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20060.diff">https://git.openjdk.org/jdk/pull/20060.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20060#issuecomment-2211495500)

### CODE REVIEW

**Review by liach — COMMENTED** [review]
The internal enum representation is an unnecessary abstraction; a boolean for uppercase is used for all public endpoints in `isUpperCase` and `toString`, so using the same boolean internally makes sense.

Do you think we should call this field `ucase` or `uppercase`?

**Comment by wenshao** [comment]
> The internal enum representation is an unnecessary abstraction; a boolean for uppercase is used for all public endpoints in `isUpperCase` and `toString`, so using the same boolean internally makes sense.
> 
> Do you think we should call this field `ucase` or `uppercase`?

`ucase` is a name that has been used in this class. It is used in the formatOptDelimiter method. `ucase` is an abbreviation, but it is easy to understand. Using the name `ucase` also requires fewer changes than `uppercase`.

**Review by liach — APPROVED** [review]
Thanks for the detailed rationale and explanations! Runs fine on CI.

**Pull request closed without merging**
