### PR TITLE
8292313: 2 runtime/cds/appcds tests fail after JDK-8284313

### PR DESCRIPTION
**Pull request by calvinccheung**
The tests failed due to the presence of the -Xlog:cds flag. 

In the WrongTopClasspath.java test, it expects the following warning: 
`[warning][cds] shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure) `

with -Xlog:cds enabled, the log statement becomes: 
`[info][cds] UseSharedSpaces: shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)` 

Since both tests are running in both Tiers 2 and 3 and the tests are not testing any of the VM flags settings in Tier4, I think we can simply add the following @requires to the tests: 
    vm.flagless

This message going to different channels (warning vs log) issue will be addressed in [JDK-8292269](https://bugs.openjdk.org/browse/JDK-8292269).

Passed tier2 testing and tested with `-Xlog:cds` locally on linux-x64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292313](https://bugs.openjdk.org/browse/JDK-8292313): 2 runtime/cds/appcds tests fail after JDK-8284313

### Reviewers
 * [Harold Seigel](https://openjdk.org/census#hseigel) (@hseigel - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9884/head:pull/9884` \
`$ git checkout pull/9884`

Update a local copy of the PR: \
`$ git checkout pull/9884` \
`$ git pull https://git.openjdk.org/jdk pull/9884/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9884`

View PR using the GUI difftool: \
`$ git pr show -t 9884`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9884.diff">https://git.openjdk.org/jdk/pull/9884.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Maybe the tests should be fixed to check for only "shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)"? That way we don't need to put arbitrary limitations on the tests.

**Comment by calvinccheung** [comment]
> Maybe the tests should be fixed to check for only "shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)"? That way we don't need to put arbitrary limitations on the tests.

This essentially relaxes the checks in the test and should work too. I've pushed an update. Thanks.

**Review by hseigel — APPROVED** [review]
LGTM
Thanks, Harold

**Review by iklam — APPROVED** [review]

**Comment by iklam** [comment]
> > Maybe the tests should be fixed to check for only "shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)"? That way we don't need to put arbitrary limitations on the tests.
> 
> This essentially relaxes the checks in the test and should work too. I've pushed an update. Thanks.

I think that's OK, as the affected tests are more about the actual content of the message, and not the log level of the message.

**Comment by calvinccheung** [comment]
Thanks @iklam, @hseigel.

/integrate

**Comment by dholmes-ora** [comment]
Sorry I missed this. You ended up with the better solution. Thanks.

**Pull request closed without merging**
