### PR TITLE
8286781: Replace the deprecated/obsolete gethostbyname and inet_addr calls

### PR DESCRIPTION
**Pull request by dholmes-ora**
We can replace `gethostbyname`, which is deprecated on Windows and Linux, with `getaddrinfo`. This API is available on all supported platforms and so can be placed in shared code. @djelinski pointed out that `getaddrinfo` can resolve both IP addresses and host names so the two step approach used in `networkStream::connect` is not necessary and we can do away with `os::get_host_by_name()` completely.

The build is updated to enable winsock deprecation warnings, and now we need to use `ws2_32.lib` we can drop `wsock32.lib` (as it is basically a subset - again thanks @djelinski ).

Testing
    - all Oracle builds in tiers 1-5
    - All GHA builds

The actual code change has to be manually tested because the code is only used by Ideal Graph Printing to connect to the Ideal Graph Visualizer. I've manually tested on Windows and Linux and @tobiasholenstein tested macOS.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286781](https://bugs.openjdk.org/browse/JDK-8286781): Replace the deprecated/obsolete gethostbyname and inet_addr calls

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [81f15e05](https://git.openjdk.org/jdk/pull/12842/files/81f15e05db32e630c7b421e60c5ccb823e06de49)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - Committer)

### Contributors
 * Daniel Jeliński `<djelinski@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12842/head:pull/12842` \
`$ git checkout pull/12842`

Update a local copy of the PR: \
`$ git checkout pull/12842` \
`$ git pull https://git.openjdk.org/jdk pull/12842/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12842`

View PR using the GUI difftool: \
`$ git pr show -t 12842`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12842.diff">https://git.openjdk.org/jdk/pull/12842.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
I forgot to mention I have no way to test on AIX so if someone were able to do that, that would be good. Thanks. I know it builds okay.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by djelinski — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the reviews @kimbarrett  and @djelinski ! I'll leave this till early next week to integrate.

**Pull request closed without merging**
