### PR TITLE
8253881: Hotspot/Serviceability Terminology Refresh

### PR DESCRIPTION
**Pull request by vidmik**
This is part of an effort in the JDK to replace archaic/non-inclusive words with more neutral terms (see JDK-8253315 for details).

Here are the changes covering hotspot code and tests. Terms were changed as follows:

1. whitelist -> removed or changed to allow-list/allowed
2. blacklist -> removed
3. chop-chop -> removed

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253881](https://bugs.openjdk.java.net/browse/JDK-8253881): Hotspot/Serviceability Terminology Refresh

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 421dcc279a1890f2efce3b535b36e5c1f33e3641
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 421dcc279a1890f2efce3b535b36e5c1f33e3641
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 421dcc279a1890f2efce3b535b36e5c1f33e3641
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to 421dcc279a1890f2efce3b535b36e5c1f33e3641
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 421dcc279a1890f2efce3b535b36e5c1f33e3641

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1798/head:pull/1798`
`$ git checkout pull/1798`

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
LGTM.

Thanks,
David

**Review by lfoltan — APPROVED** [review]
LGTM.
Lois

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. Looks about the same as your prelim...

**Comment by pavelrappo** [comment]
Although I'm not an expert in this area, I'm concerned whether the words remaining in `test/hotspot/jtreg/compiler/c2/stemmer/words` make up for the ones being deleted. If they don't (i.e. the removal of words results in test cases being discarded), then new words should be added to compensate.

**Comment by vidmik** [comment]
I've checked with @vnkozlov and the removal of these few words should not affect the effectiveness of the test, so I'll leave it as-is.

**Pull request closed without merging**
