### PR TITLE
JDK-8312394: [linux] SIGSEGV if kernel was built without hugepage support

### PR DESCRIPTION
**Pull request by tstuefe**
Somewhat trivial fixes. Hugepage detection crashes on systems whose kernels have no support compiled in for them.

- check the result of opendir() before using
- don't scan for hugepages at all if we don't have a default hugepage.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312394](https://bugs.openjdk.org/browse/JDK-8312394): [linux] SIGSEGV if kernel was built without hugepage support (**Bug** - P3)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14936/head:pull/14936` \
`$ git checkout pull/14936`

Update a local copy of the PR: \
`$ git checkout pull/14936` \
`$ git pull https://git.openjdk.org/jdk.git pull/14936/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14936`

View PR using the GUI difftool: \
`$ git pr show -t 14936`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14936.diff">https://git.openjdk.org/jdk/pull/14936.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14936#issuecomment-1642388271)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable. But does the logging output in print_on need updating to reflect this special case?

Thanks.

**Comment by tstuefe** [comment]
Thanks, David!

> Seems reasonable. But does the logging output in print_on need updating to reflect this special case?

Yes. Tested on an ARM32 SBC.

> 
> Thanks.

**Comment by tstuefe** [comment]
Could I have a second review? I'd like to get this out of the door quickly.

**Review by shipilev — APPROVED** [review]
Looks reasonable.

**Comment by tstuefe** [comment]
Thanks @dholmes-ora and @shipilev.

/integrate

**Pull request closed without merging**
