### PR TITLE
8287840: Dead copy region node blocks IfNode's fold-compares

### PR DESCRIPTION
**Pull request by navyxliu**
IfNode::fold_compares() requires ctrl has a single output. I found some fold-compares case postpone to IterGVN2. The reason is that a dead region prevents IfNode::fold_compares() from transforming code.  The dead node is removed in IterGVN, but it's too late. 

This PR extends Node::has_special_unique_user() so `PhaseIterGVN::remove_globally_dead_node()` puts IfNode back to worklist. The following attempt will carry out fold-compares().

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287840](https://bugs.openjdk.org/browse/JDK-8287840): Dead copy region node blocks IfNode's fold-compares

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9035/head:pull/9035` \
`$ git checkout pull/9035`

Update a local copy of the PR: \
`$ git checkout pull/9035` \
`$ git pull https://git.openjdk.java.net/jdk pull/9035/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9035`

View PR using the GUI difftool: \
`$ git pr show -t 9035`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9035.diff">https://git.openjdk.java.net/jdk/pull/9035.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Looks good. Let me test it.

**Review by vnkozlov — APPROVED** [review]
Testing results are good.

**Comment by navyxliu** [comment]
@vnkozlov , 
Thank you for reviewing this.  

I found this issue for this method: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/time/temporal/ChronoField.java#L687

Without this change, c2 processes the IfNode in IterGVN2 after CCP because `PhaseCCP::transform_once` put all IfNode to worklist.  I think it is good idea to get one thing done in one pass of IterGVN. 

thanks,
--lx

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Pull request closed without merging**
