### PR TITLE
8278475: G1 dirty card refinement by Java threads may get unnecessarily paused

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to avoid attempts to refine dirty cards by Java
threads when there is an active STS yield request, as the attempt will just
end up being paused.  When going into a safepoint this avoids wasted work and
transfer of buffers into the paused list.  More importantly, when coming out
of a pause this avoids deferring buffers to after the next safepoint, due to
the yield request being cleared after Java threads are restarted.

Testing:
mach5 tier1

Lots of testing as part of investigation of JDK-8273383.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278475](https://bugs.openjdk.java.net/browse/JDK-8278475): G1 dirty card refinement by Java threads may get unnecessarily paused

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to ebadd0aaf25e4e71b0d2179408e2660307cbc47b
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to 4ef92931f5d92c9e6e514eb1ca783c5a26d1e064

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7148/head:pull/7148` \
`$ git checkout pull/7148`

Update a local copy of the PR: \
`$ git checkout pull/7148` \
`$ git pull https://git.openjdk.java.net/jdk pull/7148/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7148`

View PR using the GUI difftool: \
`$ git pr show -t 7148`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7148.diff">https://git.openjdk.java.net/jdk/pull/7148.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Comment by kimbarrett** [comment]
Thanks @walulyai and @tschatzl for reviews.

**Pull request closed without merging**
