### PR TITLE
JDK-8289798: Update to use jtreg 7

### PR DESCRIPTION
**Pull request by sormuras**
Please review the change to update to using jtreg 7.

The primary change is to the `jib-profiles.js` file, which specifies the version of jtreg to use, for those systems that rely on this file. In addition, the `requiredVersion` has been updated in the various `TEST.ROOT` files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289798](https://bugs.openjdk.org/browse/JDK-8289798): Update to use jtreg 7

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [bbf53448](https://git.openjdk.org/jdk/pull/9393/files/bbf534486b48224b9e64cf5e5341afaea3336950)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [bbf53448](https://git.openjdk.org/jdk/pull/9393/files/bbf534486b48224b9e64cf5e5341afaea3336950)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9393/head:pull/9393` \
`$ git checkout pull/9393`

Update a local copy of the PR: \
`$ git checkout pull/9393` \
`$ git pull https://git.openjdk.org/jdk pull/9393/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9393`

View PR using the GUI difftool: \
`$ git pr show -t 9393`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9393.diff">https://git.openjdk.org/jdk/pull/9393.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
Have you run all the tiers to make sure there aren't any issues?

**Comment by sormuras** [comment]
No. I'll mark this PR ready for review when all tiers ran successfully.

**Comment by jaikiran** [comment]
Hello Christian, more out of curiosity - what are some of the changes that jtreg 7 brings in?

**Comment by sormuras** [comment]
Besides the usual bug fixes, updates, and minor improvements (see [changes since jtreg 6.2](https://github.com/openjdk/jtreg/compare/jtreg-6.2+1...jtreg-7+1)) the sole major new feature of jtreg 7 is:
- Run tests annotated with `@run junit` via JUnit Platform's Launcher (version `1.8.2`). This enables writing tests using the Jupiter API (version `5.8.2`) in addition to writing and running JUnit 4-based tests.

**Comment by sormuras** [comment]
The change in `junit.java` will be superseded by https://github.com/openjdk/jdk/pull/9944 which deletes that file.

**Comment by magicus** [comment]
I think the configure script should verify that we got the minimum jtreg needed. This is not really related to the change, but seeing this PR got me thinking about it. I also think a change such as this might bite people who have local setups with older jtreg installations, and then it would be nice for it to fail early in configure.

If you are interested in including such a check, I could contribute the code for the configure script.

I just want to check one thing: I see there are multiple `requiredVersion` in different TEST.ROOT files. Does this new requirement apply to *all* our jtreg tests?

**Comment by magicus** [comment]
Actually, lets do that separately. I opened https://bugs.openjdk.org/browse/JDK-8292716.

**Review by magicus — APPROVED** [review]

**Comment by jaikiran** [comment]
Hello Christian, is it intentional that in some file the minimum required jtreg version is represented as `7` (`lib-tests.m4`) and in some other files as `7+1` (GitHub actions config file, then the TEST.ROOT files)?

**Comment by sormuras** [comment]
> Hello Christian, is it intentional that in some file the minimum required jtreg version is represented as `7` (`lib-tests.m4`) and in some other files as `7+1` (GitHub actions config file, then the TEST.ROOT files)?

Yes. Some systems require the exact version tag `7+1` others only the short version string `7`.

**Review by jaikiran — APPROVED** [review]

**Comment by tstuefe** [comment]
Is jtreg 7 downward compatible? Can I use it to test older JDKs, if yes, down to which version?

Thanks!

**Comment by sormuras** [comment]
> Is jtreg 7 downward compatible? Can I use it to test older JDKs, if yes, down to which version?

Yes, down to JDK 11.

Quote from [Coming soon: jtreg 7](https://mail.openjdk.org/pipermail/jdk-dev/2022-August/006869.html)

> Also starting with version 7, jtreg is compiled with JDK 11 and so requires a recent release of JDK 11 to run it.

And it should have said more correctly: _...requires a recent release of JDK 11 **or later** to run it._

**Comment by tstuefe** [comment]
> > Is jtreg 7 downward compatible? Can I use it to test older JDKs, if yes, down to which version?
> 
> Yes, down to JDK 11.
> 
> Quote from [Coming soon: jtreg 7](https://mail.openjdk.org/pipermail/jdk-dev/2022-August/006869.html)
> 
> > Also starting with version 7, jtreg is compiled with JDK 11 and so requires a recent release of JDK 11 to run it.

I read this to mean JT_JAVA, so the JVM running jtreg, not the testee VM.

But you are saying that the testee VM (`-jdk` option) can be JDK11 or later? I wonder whether I can use jtreg7 to test downport JDKs, especially since you wrote 

"This did affect some existing JDK tests, but those tests that
relied on specific jar file names have already been updated."

So I guess at the minimum we would have to downport those test changes to be able to test older JDKs with the new jtreg, right?

**Comment by sormuras** [comment]
> So I guess at the minimum we would have to downport those test changes to be able to test older JDKs with the new jtreg, right?

Yes. Otherwise those tests will fail as they still do depend on hard-coded names of 3rd-party JAR files. Find backport candidates listed as Sub-Tasks number 3 to 5 at https://bugs.openjdk.org/browse/JDK-8289798 (Sub-Tasks number 1 and 2 were closed without changes.)

**Pull request closed without merging**
