### PR TITLE
8278020: ~13% variation in Renaissance-Scrabble

### PR DESCRIPTION
**Pull request by iklam**
We found that when CDS is enabled, there is a ~13% variation in the Renaissance-Scrabble benchmark between different builds of the JDK. In one example, only two core-lib classes, unrelated to the benchmark, changed between two builds, but one build is consistently faster than the other.

When CDS is disabled, we do not see such variations.

In the slow case, there seems to be frequent dcache misses when loading the `Klass::_vtable_len` field, which is at offset 24 from the beginning of the Klass (see [bug report](https://bugs.openjdk.java.net/browse/JDK-8278020) for details). 

We suspect that the problem is with the layout of the CDS archive. Specifically, in CDS, Klass objects are inter-mixed with other metadata objects (such as Methods). In contrast, when CDS is disabled, (on 64-bit platforms with compressed klass pointers), Klass objects are allocated in their own space, separated from other metadata objects.

My theory is: when CDS is enabled, perhaps the modification of an object that sits immediately above the Klass invalidates the cacheline that holds `Klass::_vtable_len`. In a different JDK build, the exact addresses of the metadata objects in the CDS archive may be slightly nudged so we don't see the cacheline effect anymore.

As an experiment, I swapped `Klass::_vtable_len` with `Klass::_modifier_flags` (which was at offset 164 before this patch), and the variation stopped. Both fields are 32 bits in size.

I have no concrete proof that my theory is correct, but this change seems to be harmless. @ericcaspole has run all the benchmarks in Oracle's CI and found consistent improvement with Renaissance-Scrabble, and no degradation in other benchmarks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278020](https://bugs.openjdk.java.net/browse/JDK-8278020): ~13% variation in Renaissance-Scrabble

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6838/head:pull/6838` \
`$ git checkout pull/6838`

Update a local copy of the PR: \
`$ git checkout pull/6838` \
`$ git pull https://git.openjdk.java.net/jdk pull/6838/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6838`

View PR using the GUI difftool: \
`$ git pr show -t 6838`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6838.diff">https://git.openjdk.java.net/jdk/pull/6838.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
I would have kept the two fields together after the switch so that you can add a comment. Seems totally bizarre that two such separated fields would have such an affect.

Isn't this needed in 18 though?

**Comment by vnkozlov** [comment]
Yes, this small change is good for JDK 18.
Is it possible for JDK 19 (or later) to make CDS segmented to separate different types of data (Klass, Method, etc)?

**Comment by vnkozlov** [comment]
An other experiment could be done is to add padding (space) before Klass data to make sure it is in different cache line.

**Comment by iklam** [comment]
> I would have kept the two fields together after the switch so that you can add a comment. Seems totally bizarre that two such separated fields would have such an affect.
> 
> Isn't this needed in 18 though?

David, if my theory is correct, the contention does not happen between the two fields. It happens between the `_vtable_len` field, and the object that immediately precedes the Klass. I have not found out what that other object is. Eric is writing a simplified version of the benchmark and I hope to use that to narrow down the problem.

I have added comments near _vtable_len to explain why it's placed there inside the Klass.

I swapped it with `_modifier_flags` because they are the same size, and `_modifier_flags` doesn't seem to be accessed nearly as often as `_vtable_len`.

**Comment by iklam** [comment]
> Yes, this small change is good for JDK 18. Is it possible for JDK 19 (or later) to make CDS segmented to separate different types of data (Klass, Method, etc)?

It's possible to make CDS segmented so that the Klasses are allocated together. That can be done in 19.

**Comment by iklam** [comment]
> An other experiment could be done is to add padding (space) before Klass data to make sure it is in different cache line.

That's a good idea. I will try that to see if it has the same effect as the current patch.

**Review by dholmes-ora — APPROVED** [review]

**Comment by dholmes-ora** [comment]
I approved but still think this should be targeted at 18 - assuming this was a performance regression in 18.

Padding may have the same performance affect but will also impact footprint potentially - which in turn may impact the caching behaviour.

**Review by tstuefe — APPROVED** [review]
Hi Ioi,

The fix looks fine.

this is interesting to me, because in the context of Lilliput (https://github.com/openjdk/lilliput/pull/13) I was kind of counting on CDS to intermix Klass and non-class metadata, since that way CDS uses the larger Klass alignment gaps. In fact, I have this wild idea to shape metaspace in that form, merging Klass and non-class metadata into one larger class space. It would be really good to have a better idea of these interactions.

What tool did you use to measure the dcache misses?

Cheers, Thomas

**Comment by vnkozlov** [comment]
> I approved but still think this should be targeted at 18 - assuming this was a performance regression in 18.
> 
> Padding may have the same performance affect but will also impact footprint potentially - which in turn may impact the caching behaviour.

I suggested padding only as experiment to prove Ioi's theory.  Current changes are good as the fix.

**Review by vnkozlov — APPROVED** [review]

**Comment by iklam** [comment]
> I approved but still think this should be targeted at 18 - assuming this was a performance regression in 18.
> 
> Padding may have the same performance affect but will also impact footprint potentially - which in turn may impact the caching behaviour.

@ericcaspole checked our benchmark database and the regression seems to have started around JDK 15. So yes, I will backport the fix to 17 and 18. I want to integrate into the mainline first so it can be baked a little before the backport.

**Comment by tstuefe** [comment]
> My theory is: when CDS is enabled, perhaps the modification of an object that sits immediately above the Klass invalidates the cacheline that holds `Klass::_vtable_len`. In a different JDK build, the exact addresses of the metadata objects in the CDS archive may be slightly nudged so we don't see the cacheline effect anymore.

BTW you could test that theory, if you wanted, by repeating the test with CDS off and disabling compressed class pointers.

**Comment by iklam** [comment]
> Hi Ioi,
> 
> The fix looks fine.
> 
> this is interesting to me, because in the context of Lilliput ([openjdk/lilliput#13](https://github.com/openjdk/lilliput/pull/13)) I was kind of counting on CDS to intermix Klass and non-class metadata, since that way CDS uses the larger Klass alignment gaps. In fact, I have this wild idea to shape metaspace in that form, merging Klass and non-class metadata into one larger class space. It would be really good to have a better idea of these interactions.
> 
> What tool did you use to measure the dcache misses?
> 
> Cheers, Thomas

Hi Thomas,

@ericcaspole did the measurements so he will have more information, but I believe he used https://github.com/jvm-profiling-tools/async-profiler to generate traces like this (which I pasted into the bug report):

```
 Column 1: cycles (125424 events)
 Column 2: l1d_pend_miss.pending_cycles (56716 events)
 Column 3: CYCLE_ACTIVITY.CYCLES_L2_MISS (66170 events)

  0.08%   0.02%   0.03%     0x00007f488cda2dc8:  mov  0x10(%r10),%r11d
 12.26%  16.97%  16.23%     0x00007f488cda2dcc:  lea  0x1b8(%r10,%r11,8),%r11
```

@vnkozlov I found that most Klasses in CDS are preceded by a Method. Does the jitted code write into a Method often?

**Comment by tstuefe** [comment]
> > Hi Ioi,
> > The fix looks fine.
> > this is interesting to me, because in the context of Lilliput ([openjdk/lilliput#13](https://github.com/openjdk/lilliput/pull/13)) I was kind of counting on CDS to intermix Klass and non-class metadata, since that way CDS uses the larger Klass alignment gaps. In fact, I have this wild idea to shape metaspace in that form, merging Klass and non-class metadata into one larger class space. It would be really good to have a better idea of these interactions.
> > What tool did you use to measure the dcache misses?
> > Cheers, Thomas
> 
> Hi Thomas,
> 
> @ericcaspole did the measurements so he will have more information, but I believe he used https://github.com/jvm-profiling-tools/async-profiler to generate traces like this (which I pasted into the bug report):
> 
> ```
>  Column 1: cycles (125424 events)
>  Column 2: l1d_pend_miss.pending_cycles (56716 events)
>  Column 3: CYCLE_ACTIVITY.CYCLES_L2_MISS (66170 events)
> 
>   0.08%   0.02%   0.03%     0x00007f488cda2dc8:  mov  0x10(%r10),%r11d
>  12.26%  16.97%  16.23%     0x00007f488cda2dcc:  lea  0x1b8(%r10,%r11,8),%r11
> ```

Okay, thanks.

> 
> @vnkozlov I found that most Klasses in CDS are preceded by a Method. Does the jitted code write into a Method often?

Method counters? May be worth spreading them out better, or to pad them to prevent false sharing.

**Comment by iklam** [comment]
Thanks @dholmes-ora @vnkozlov @tstuefe for the review.
/integrate

**Comment by vnkozlov** [comment]
>> @vnkozlov I found that most Klasses in CDS are preceded by a Method. Does the jitted code write into a Method often?
> Method counters? May be worth spreading them out better, or to pad them to prevent false sharing.

I don't think compiled code updates something in Method. We need to look on fields layout.
Compiled code do update frequently MethodCounters (invocations, loops) and  MethodData (profiling counters for bytecode). Both are allocated in metaspace as classes.

**Pull request closed without merging**
