### PR TITLE
8315117: Update Zlib Data Compression Library to Version 1.3

### PR DESCRIPTION
**Pull request by LanceAndersen**
Hi all,

Please review this PR which updates zlib from 1.2.13 to 1.3 in openJDK

The [Zlib Data Compression Library](https://github.com/madler/zlib ) has released Zlib 1.3 on August 18, 2023.

There are a [small number of updates](https://github.com/madler/zlib/compare/v1.2.13...master ) between 1.2.13 and 1.3 

Mach5 tiers1-6 have run clean as do the JCK tests

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315117](https://bugs.openjdk.org/browse/JDK-8315117): Update Zlib Data Compression Library to Version 1.3 (**Enhancement** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15453/head:pull/15453` \
`$ git checkout pull/15453`

Update a local copy of the PR: \
`$ git checkout pull/15453` \
`$ git pull https://git.openjdk.org/jdk.git pull/15453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15453`

View PR using the GUI difftool: \
`$ git pr show -t 15453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15453.diff">https://git.openjdk.org/jdk/pull/15453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15453#issuecomment-1696013559)

### CODE REVIEW

**Comment by AlanBateman** [comment]
Are there any changes from the upstream zlib 1.3 code that should be called out or is zlib 1.3 copied in without any changes?

**Comment by LanceAndersen** [comment]
> Are there any changes from the upstream zlib 1.3 code that should be called out or is zlib 1.3 copied in without any changes?

It was a clean copy(which I have been able to do as of zlib 1.2.13).  Sorry I should have mentioned this in the PR request

**Comment by AlanBateman** [comment]
> It was a clean copy(which I have been able to do as of zlib 1.2.13). Sorry I should have mentioned this in the PR request

That's okay, I just wanted to check to be sure that the ChangeLog_java (renamed adler32.c -> zadler32.c, crc32c -> zcrc32.c) is everything.

**Review by AlanBateman — APPROVED** [review]
Okay, assuming tests are passing on windows-x64 and macos-aarch64 as these are the two that will usually use the bundled zlib.

**Comment by LanceAndersen** [comment]
> Okay, assuming tests are passing on windows-x64 and macos-aarch64 as these are the two that will usually use the bundled zlib.

Yes, both were clean in my mach5 runs

**Pull request closed without merging**
