### PR TITLE
8255559: Leak File Descriptors Because of ResolverLocalFilesystem#engineResolveURI()

### PR DESCRIPTION
**Pull request by pkumaraswamy**
…ineResolveURI().

Actual fix looks like this, due to git diff there are lot  of changes( mostly because of the spaces) being displayed.

--- a/src/share/classes/org/jcp/xml/dsig/internal/dom/DOMReference.java
+++ b/src/share/classes/org/jcp/xml/dsig/internal/dom/DOMReference.java
@@ -500,6 +500,7 @@
                 }
 
                 boolean secVal = Utils.secureValidation(context);
+                try {
                 xi.setSecureValidation(secVal);
                 if (context instanceof XMLSignContext && c14n11
                     && !xi.isOctetStream() && !xi.isOutputStreamSet()) {
@@ -533,6 +534,11 @@
                 } else {
                     xi.updateOutputStream(os);
                 }
+                } finally {
+                    if(xi.getOctetStreamReal() != null) {
+                        xi.getOctetStreamReal().close();
+                    }
+                }
             }

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255559](https://bugs.openjdk.java.net/browse/JDK-8255559): Leak File Descriptors Because of ResolverLocalFilesystem#engineResolveURI()

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1142/head:pull/1142`
`$ git checkout pull/1142`

### CODE REVIEW

**Comment by pkumaraswamy** [comment]
/reviewers 3 @coffeys , @wangweij , @seanjmullan

**Comment by wangweij** [comment]
FYI: https://github.com/apache/santuario-xml-security-java/pull/9/files

**Comment by pkumaraswamy** [comment]
Thanks Max, I guess there are additional changes in Apache code and will sync our code base with same changes.
I'll make appropriate changes and push it again.

**Review by wangweij — APPROVED** [review]

**Comment by wangweij** [comment]
> Thanks Max, I guess there are additional changes in Apache code and will sync our code base with same changes.
> I'll make appropriate changes and push it again.

No worry. Next time we sync with Santuario, when I found the problem is already fixed upstream, our patch will not be applied.

**Pull request closed without merging**
