### PR TITLE
8252661: Change SafepointMechanism terminology to talk less about "blocking"

### PR DESCRIPTION
**Pull request by fisk**
Migrating this review from the mailing list into a pull request. So far, the favourite terminology is to talk about "process", but without "operation".

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252661](https://bugs.openjdk.java.net/browse/JDK-8252661): Change SafepointMechanism terminology to talk less about "blocking"

### Reviewers
 * [Robbin Ehn](https://openjdk.java.net/census#rehn) (@robehn - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * dholmes - **Reviewer** ⚠️ Added manually

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/54/head:pull/54`
`$ git checkout pull/54`

### CODE REVIEW

**Comment by shipilev** [comment]
Okay, I am somewhat confused how Skara is supposed to register my review here. Reviewed!

**Review by robehn — APPROVED** [review]
I think we can do better then "process".
I can't think anything now, so ship it.

Thanks

**Review by shipilev — APPROVED** [review]

**Comment by fisk** [comment]
Thanks for the reviews, @shipilev  and @robehn. I'll add David Holmes as reviewer too, as the final name suggestion was his.

**Pull request closed without merging**
