### PR TITLE
8334772: Change Class::signers to an explicit field

### PR DESCRIPTION
**Pull request by liach**
`Class` has 2 VM-injected fields that can be made explicit: `Object[] signers` and `ProtectionDomain protectionDomain`. We make the signers field explicit. (The ProtectionDomain can be revisited when SecurityManager is removed, as SecurityManager is accessing it via JNI as well.)

Migrate the JNI code to Java. The getter previously had a redundant primitive type check, which is dropped in the migrated Java code. The `Object[] getSigners` is no longer `native`, thus requiring a CSR record. Reviewers please help review the associated CSR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issues
 * [JDK-8334772](https://bugs.openjdk.org/browse/JDK-8334772): Change Class::signers to an explicit field (**Enhancement** - P4)
 * [JDK-8336676](https://bugs.openjdk.org/browse/JDK-8336676): Remove native modifier from Class::getSigners method (**CSR**) (Withdrawn)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) 🔄 Re-review required (review applies to [86b3a248](https://git.openjdk.org/jdk/pull/20223/files/86b3a2488081e2089ad4423f9e34c8d7aedd53f8))
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20223/head:pull/20223` \
`$ git checkout pull/20223`

Update a local copy of the PR: \
`$ git checkout pull/20223` \
`$ git pull https://git.openjdk.org/jdk.git pull/20223/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20223`

View PR using the GUI difftool: \
`$ git pr show -t 20223`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20223.diff">https://git.openjdk.org/jdk/pull/20223.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20223#issuecomment-2234142051)

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
The relocation of the field to Java looks good. But I am concerned that the field is now exposed to reflection.

**Comment by AlanBateman** [comment]
Signers dates back to JDK 1.1, touching it now will shine light on long standing technical debt and other issues.

I think the main thing that is jumping in out is that ClassLoader.setSigners (protected final method so may be called in subclasses) isn't fully specified and it is also missing a number of important checks. The method doesn't specify that the method ignores array classes or class objects for primitives. It doesn't say anything about the elements that aren't a Certificate are ignored. It doesn't specify null behavior either and doesn't say anything that the signers can change at any time. What's worse is that in the hands of a cowboy builder, it can be used to set or clear the signers for any Class, or keep a reference to the signers array and muck with them mid-flight. So lots of issues there.

Technical debt aside, I think the transformation looks okay, just a bit confusing to have signers declared under a comment "Set by VM", it's not clear the comment applies only to the classData before it. At some point I think we should put a question mark on the JVMTI JVMTI_HEAP_REFERENCE_SIGNERS heap ref and the HPROF heap dump CLASS record where there is a slot the signer array. I don't see any need for these in 2024 and could be potentially be null'ed in the future (would require a JVM TI spec change of course).

On David's comment about exposing the field to code using Class.getDecalredField or Class.getDeclaredFields. Nosy code can use these methods to a reference to the Field but it's not accessible by default. For now, code can using sun.misc.Unsafe but that is temporary and will go away. I don't have a strong opinion and no objection to adding it to the filter (which I think is what David is wondering about).

**Review by coleenp — COMMENTED** [review]
I thought we moved this already.  There's a change in the heapDumper.cpp that probably has to change also, because I think we're now dumping signers twice (two lines).  The one in jvmtiTagMap.cpp reports the SIGNERS tag so that has to stay.

**Comment by AlanBateman** [comment]
> There's a change in the heapDumper.cpp that probably has to change also, because I think we're now dumping signers twice (two lines).

The HPROF heap dump has a slot for signers so have to keep that to avoid breakage. So yes, it means two refs as the signers will be in the instance fields list too. The HPROF format could be rev'ed but may not be worth it.

**Review by coleenp — APPROVED** [review]
Ok.  It's not obvious from the code but I don't think it's worth commenting.

**Review by RogerRiggs — APPROVED** [review]
lgtm

**Review by dholmes-ora — COMMENTED** [review]
On the JVMTI side and the heapDumper ... I see that heapDumper explicitly fills in a slot for the classloader, but that is also an explicit field. Does that mean that the classloader appears twice, or does the fact it is filtered by reflection mean that the heapDumper doesn't see it when dumping fields? If the latter then it suggests to me that we should be doing the same for the signers. Otherwise I don't know what the implications might be for having the field listed twice.

**Review by dholmes-ora — APPROVED** [review]
I am not a hprof expert but AFAICS the  `HPROF_GC_CLASS_DUMP` contains an explicit id for the classloader, signers, and pd, of the class, and then later a list of all fields declared in the class. AFAICS there is no real connection between these, so it doesn't matter if the classloader/signers/pd is an injected field, a regular Java field, or not a field at all. So in that regard it seems `signers` will now be handled the same way as `classloader` and so that should be fine.

**Comment by liach** [comment]
Thanks for the reviews! I will go ahead and integrate.

/integrate

**Pull request closed without merging**
