### PR TITLE
8291444: GHA builds/tests won't run manually if disabled from automatic running

### PR DESCRIPTION
**Pull request by RealCLanger**
This is an attempt to fix the issue reported in JDK-8291444.

The check for secrets.JDK_SUBMIT_FILTER should only be applied to the push event but not on e.g. workflow_dispatch.
Currently setting JDK_SUBMIT_FILTER would lead to setting every platform to 'false', even when manually triggering the GHA run via workflow_dispatch.

I furthermore propose to relax the check for unknown events. In OpenJDK we only use/define workflow_dispatch and push. Other events would hence not trigger the workflow anyway. However, downstream vendors (like us in SapMachine) might use other events such as pull_request and they would then need to patch this away. This kind of downstream issue was also reported by [Amazon](https://mail.openjdk.org/pipermail/build-dev/2022-August/035102.html). If you agree, I would remove the commented lines 91-93. Otherwise I have to uncomment them.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291444](https://bugs.openjdk.org/browse/JDK-8291444): GHA builds/tests won't run manually if disabled from automatic running

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to [5369e338](https://git.openjdk.org/jdk/pull/11365/files/5369e3386578d107d1ae4e561351a79308f8f412)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [5369e338](https://git.openjdk.org/jdk/pull/11365/files/5369e3386578d107d1ae4e561351a79308f8f412)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [5369e338](https://git.openjdk.org/jdk/pull/11365/files/5369e3386578d107d1ae4e561351a79308f8f412)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11365/head:pull/11365` \
`$ git checkout pull/11365`

Update a local copy of the PR: \
`$ git checkout pull/11365` \
`$ git pull https://git.openjdk.org/jdk pull/11365/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11365`

View PR using the GUI difftool: \
`$ git pr show -t 11365`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11365.diff">https://git.openjdk.org/jdk/pull/11365.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
@magicus @dholmes-ora FYA

**Review by mrserb — APPROVED** [review]
This should be reviewed by the build team. But I can confirm this change solve the problem I mentioned [here](https://mail.openjdk.org/pipermail/build-dev/2022-August/035102.html).

**Comment by RealCLanger** [comment]
Ping. Anybody from build group up to take a look?

**Review by erikj79 — APPROVED** [review]

**Review by magicus — APPROVED** [review]

**Comment by RealCLanger** [comment]
Thanks for the reviews. I removed the commented lines. Will integrate later today.

**Comment by RealCLanger** [comment]
GHA error seems unrelated (langtools).
/integrate

**Comment by dholmes-ora** [comment]
This change does not appear to have the fixed the issue it was filed to fix. The GHA tests still do not run for me when I choose a manual run.

**Pull request closed without merging**
