### PR TITLE
8292297: Fix up loading of override java.security properties file

### PR DESCRIPTION
**Pull request by coffeys**
Ensure that security properties are only overridden if the override security properties file exists. 
Refactored some of the code in Security class initialization also.
Extra test coverage for security properties file options.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292297](https://bugs.openjdk.org/browse/JDK-8292297): Fix up loading of override java.security properties file

### Reviewers
 * [Xue-Lei Andrew Fan](https://openjdk.org/census#xuelei) (@XueleiFan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10251/head:pull/10251` \
`$ git checkout pull/10251`

Update a local copy of the PR: \
`$ git checkout pull/10251` \
`$ git pull https://git.openjdk.org/jdk pull/10251/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10251`

View PR using the GUI difftool: \
`$ git pr show -t 10251`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10251.diff">https://git.openjdk.org/jdk/pull/10251.diff</a>

</details>

### CODE REVIEW

**Comment by XueleiFan** [comment]
Is it a behavioral change that requires CSR approval?

**Comment by coffeys** [comment]
> Is it a behavioral change that requires CSR approval?

I considered the CSR impact before logging this PR. This issue corrects a bug where security properties had potential to be lost if an incorrect URL/resource was specified for the secondary/override security conf file. The system was already working with bad user config in such a case. Don't think it needs a CSR but open to correction.

**Review by XueleiFan — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
