### PR TITLE
8239596: PARAMETER annotation on receiver type does not cause error

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

`TypeAnnotationsValidator::visitMethodDef`  uses `checkForDeclarationAnnotations` incorrectly so that the check could not work as expected and some related errors are not reported. This patch fixes it and adds a corresponding test case.

Thank you for taking the time to review.

Best Regards.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8239596](https://bugs.openjdk.java.net/browse/JDK-8239596): PARAMETER annotation on receiver type does not cause error

### Reviewers
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/1881/head:pull/1881` \
`$ git checkout pull/1881`

Update a local copy of the PR: \
`$ git checkout pull/1881` \
`$ git pull https://git.openjdk.java.net/jdk pull/1881/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1881`

View PR using the GUI difftool: \
`$ git pr show -t 1881`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/1881.diff">https://git.openjdk.java.net/jdk/pull/1881.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks sensible

**Comment by lgxbslgx** [comment]
@vicente-romero-oracle Thank you for your review. Could I get your help to sponsor this patch?

/integrate

**Pull request closed without merging**
