### PR TITLE
8321685: Missing ResourceMark in code called from JvmtiEnvBase::get_vthread_jvf

### PR DESCRIPTION
**Pull request by sspitsyn**
This fix adds a ResourceMark missing in the `SetFramePopClosure::do_thread` and `SetFramePopClosure::do_vthread`.

Testing:
 - TBD to submit tiers: 1-5

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321685](https://bugs.openjdk.org/browse/JDK-8321685): Missing ResourceMark in code called from JvmtiEnvBase::get_vthread_jvf (**Bug** - P3)

### Reviewers
 * [Alex Menkov](https://openjdk.org/census#amenkov) (@alexmenkov - **Reviewer**) ⚠️ Review applies to [dd838135](https://git.openjdk.org/jdk/pull/17332/files/dd838135719076415f487702ba8f94853b14cd02)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [dd838135](https://git.openjdk.org/jdk/pull/17332/files/dd838135719076415f487702ba8f94853b14cd02)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17332/head:pull/17332` \
`$ git checkout pull/17332`

Update a local copy of the PR: \
`$ git checkout pull/17332` \
`$ git pull https://git.openjdk.org/jdk.git pull/17332/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17332`

View PR using the GUI difftool: \
`$ git pr show -t 17332`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17332.diff">https://git.openjdk.org/jdk/pull/17332.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17332#issuecomment-1883975175)

### CODE REVIEW

**Review by alexmenkov — APPROVED** [review]

**Review by plummercj — APPROVED** [review]
Looks good. Note, it would be good if the jvmti code added comments explaining why a ResourceMark is needed. For these two cases I had to search around until I stumbled across the following in some unrelated code:

  // vframes are resource allocated
  Thread* current_thread = Thread::current();
  ResourceMark rm(current_thread);

This looks very much like the code you are updating, except the updated code is lacking the comment.

**Comment by sspitsyn** [comment]
Alex and Chris, thank you for review!
Chris, I'll add similar comments as you noted. I agree, it will be helpful.

**Pull request closed without merging**
