### PR TITLE
8328865: [c2] No need to convert "(x+1)+y" into "(x+y)+1" when y is a CallNode

### PR DESCRIPTION
**Pull request by sunny868**
This patch prohibits the conversion from  "(x+1)+y" into "(x+y)+1" when y is a CallNode to reduce unnecessary spillcode and ADDNode.

Testing: tier1-3 in x86_64 and LoongArch64

JMH in x86_64:
<pre>
before:
Benchmark           Mode  Cnt      Score   Error  Units
CallNode.test      thrpt    2  26397.733          ops/s

after:
Benchmark           Mode  Cnt      Score   Error  Units
CallNode.test      thrpt    2  27839.337          ops/s
</pre>

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328865](https://bugs.openjdk.org/browse/JDK-8328865): [c2] No need to convert "(x+1)+y" into "(x+y)+1" when y is a CallNode (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18482/head:pull/18482` \
`$ git checkout pull/18482`

Update a local copy of the PR: \
`$ git checkout pull/18482` \
`$ git pull https://git.openjdk.org/jdk.git pull/18482/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18482`

View PR using the GUI difftool: \
`$ git pr show -t 18482`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18482.diff">https://git.openjdk.org/jdk/pull/18482.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18482#issuecomment-2019550714)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I think it is not a call node but (x+1) result is used by debug info of call node.
For example, next code could be the same issue (I did not verified it):
```
     static int y = 0;
...
     int foo(int x, int z) {
         int a = x + 1;
         y = a;
         return a + z;
     }
```

**Comment by eme64** [comment]
@sunny868 do you have a benchmark where you can show the difference? Does spilling matter that much if we are already doing a call anyway?
I'm just worried that we prevent the constants from sinking down, and commoning (folding together) with other constants further down. In some cases this is also expected by patter matching in some optimizations, though there would surely be ways to improve those if need be.

**Comment by eme64** [comment]
Ah, I just saw your attached benchmark. Will have a look at it later.

**Comment by eme64** [comment]
A possible counter-example:

```
x1 = something
y1 = someCall

for (int i = 0; i < a.length; i++) {
  a[i] = (x + 1) + y) + ((x + 2) + y) + ((x + 2) + y) + ((x + 3) + y) + ((x + 4) + y)
}
```
The call is outside the loop, so folding would not be costly at all. And I fear that the 4 terms would not common up, and so be slower after your change. And I think there are probably other examples. But I have not benchmarked anything, so I could be quite wrong.

What exactly is it that gives you the speedup in your benchmark? Spilling? Fewer add instructions? Would be nice to understand that better, and see what are potential examples where we would have regressions with your patch.

**Comment by sunny868** [comment]
> 
> What exactly is it that gives you the speedup in your benchmark? Spilling? Fewer add instructions? Would be nice to understand that better, and see what are potential examples where we would have regressions with your patch.

That is fewer spilling and add instructions make the benchmark speedup.
before opto:
<pre>
	   subq    rsp, #32	# Create frame
02a     movq    RBP, [RSI + #16 (8-bit)]	# long ! Field: CallNode.val
02e     leaq    R10, [RBP + #3]
032     movq    [rsp + #0], R10	# spill
        nop 	# 1 bytes pad for loops and calls
037     call,static  CallNode::callNoInlineMethod
        # CallNode::test @ bci:10 (line 11) L[0]=_ L[1]=rsp + #0 L[2]=_
        # OopMap {off=60/0x3c}

044     B2: #	out( N41 ) <- in( B1 )  Freq: 0.99998
        # Block is sole successor of call
044     addq    RAX, RBP	# long
047     addq    RAX, #3	# long
04b     addq    rsp, 32	# Destroy frame
</pre>

after opto:
<pre>
  	   subq    rsp, #16	# Create frame
02a     movl    RBP, #3	# long (unsigned 32-bit)
02f     addq    RBP, [RSI + #16 (8-bit)]	# long
033     call,static  CallNode::callNoInlineMethod
        # CallNode::test @ bci:10 (line 11) L[0]=_ L[1]=RBP L[2]=_
        # OopMap {off=56/0x38}

040     B2: #	out( N36 ) <- in( B1 )  Freq: 0.99998
        # Block is sole successor of call
040     addq    RAX, RBP	# long
043     addq    rsp, 16	# Destroy frame

</pre>

**Comment by dean-long** [comment]
Why only (x+1)+y and not also x+(y+1)?  I agree with @eme64 about breaking other optimizations if we don't move constants to the right.  (x+1)+(y+1) no longer becomes (x+y)+2.  To reduce spills, I would think we would want to move Calls to the left.  (x+1)+y and x+(y+1) both become y+x+1.

**Comment by dean-long** [comment]
The difference in generate code above seems very x86-specific, depending on differences between 2-operand ADD vs 3-operand LEA.  It's not obvious to me why this change would necessarily generate better code, even in some cases.  And the requirement should be leaning towards better or no worse code in all cases on all platforms.

**Comment by sunny868** [comment]
> Why only (x+1)+y and not also x+(y+1)? I agree with @eme64 about breaking other optimizations if we don't move constants to the right. (x+1)+(y+1) no longer becomes (x+y)+2. 

Previously, I didn't have a deep understanding of constant folding, but now it seems that this PR will cause performance regression. 

> To reduce spills, I would think we would want to move Calls to the left. (x+1)+y and x+(y+1) both become y+x+1.

This is a good idea. But my idea is, can we delete add1 after `add1->clone()` ? https://github.com/openjdk/jdk/pull/18482/files#diff-c59303cb42c3e35f20bc530628dc611003e21819e84cedb2279e69cde0345410L183

**Comment by eme64** [comment]
@sunny868 @dean-long I also like the idea of moving calls to the left. Though even that may not always be an improvement. It would be nice to have a series of benchmarks with all sorts of combinations of calls inside the loop, or outside the loop, adding together with variables inside the loop, or invariants from outside the loop. What we would like is that:

1. everything loop invariant is added up outside the loop, and only loop variant things are added inside the loop.
2. Constants should always go to the right.
3. And calls should go to the left.

These 3 ideas seem to contradict each other at times, so I wonder if there is a more general heuristic here?

Examples for contradiction (`invar`: loop invariant, `var`: loop variant, changes in each loop iteration):

1. `invar + var + con`: `(invar + con) + var` would take everything loop invariant out of the loop, but the constant would not be on the very right.
2. `invar1 + invar2 + call`: assume the call is inside the loop, but `invar1` and `invar2` are before/outside the loop. Moving the `call` to the very left `(call + invar1) + invar2` would mean we have to do more addition work inside the loop (2 additions per iteration), but `(invar1 + invar2) + call` would have the invariants added up before the loop, and only the call value added to that in every loop iteration.

I'm not sure how significant all of this is. You really would need some benchmarks to get more insight.  And writing a good benchmark is not easy.

**Comment by eme64** [comment]
@sunny868 You will have to change the title anyway. Can you write `C2` instead of `[c2]`, please? ;)

**Comment by dean-long** [comment]
In general, we can't move a call left or right past something with side-effects or memory effects, right?  This seems like the wrong place to be moving a Call, except relative to easy values like constants.

For loop invariants, it seems like they could be grouped together on either side, but don't loop optimizations take care of that already?

And it seems like a comprehensive cost analysis would need to take into account the cost of a spill vs an add.  If we can rematerialize a value using (reg + reg) instead of a load from memory, that seems like a win, but for more complicated expressions that can be done outside the loop, rematerializing from memory could be best.

So does this change really belong in AddNode::Ideal()?

**Pull request closed without merging**
