### PR TITLE
8339261: Logs truncated in test javax/net/ssl/DTLS/DTLSRehandshakeTest.java

### PR DESCRIPTION
**Pull request by fguallini**
The test javax/net/ssl/DTLS/DTLSRehandshakeTest.java runs multiple scenarios, generating a large amount of logging as a result. Since Jtreg truncates the output when it becomes too large, the logs are often not useful for debugging in case of failure.

This PR updates the maxOutputSize for the DTLS test directory, including DTLSRehandshakeTest.java. Incrementing the maxOutputSize results in more logs, with an approximate size increase of ~0.6MB when compressed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339261](https://bugs.openjdk.org/browse/JDK-8339261): Logs truncated in test javax/net/ssl/DTLS/DTLSRehandshakeTest.java (**Sub-task** - P4)

### Reviewers
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)
 * [Hai-May Chao](https://openjdk.org/census#hchao) (@haimaychao - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20838/head:pull/20838` \
`$ git checkout pull/20838`

Update a local copy of the PR: \
`$ git checkout pull/20838` \
`$ git pull https://git.openjdk.org/jdk.git pull/20838/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20838`

View PR using the GUI difftool: \
`$ git pr show -t 20838`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20838.diff">https://git.openjdk.org/jdk/pull/20838.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20838#issuecomment-2331098039)

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Fernando, I'm not familiar with this test or the area, but if this change is just to make available jtreg logs (in a separate file) to allow for debugging a currently intermittent test failure, then there are ways to change the jtreg output log limit in our CI, without having to change the test code - I can show you the command, offline, to do that.

As far as I remember, we don't have a precedence of changing tests to write out to additional locations to bypass the jtreg log limit.

**Comment by fguallini** [comment]
> maxOutputSize

Thanks for the review. I removed the additional file and updated the test properties to increment maxOutputSize. This approach is more commonly used in other tests.

**Review by rhalade — APPROVED** [review]

**Review by haimaychao — APPROVED** [review]

**Pull request closed without merging**
