### PR TITLE
8316414: C2: large byte array clone triggers "failed: malformed control flow" assertion failure on linux-x86

### PR DESCRIPTION
**Pull request by rwestrel**
`GraphKit::new_array()` computes the maximum array length as:

```
BasicType bt = ary_type->isa_aryptr()->elem()->array_element_basic_type();
jint max = TypeAryPtr::max_array_length(bt);
```

while `AllocateArrayNode::make_ideal_length()` calls
`TypeAryPtr::narrow_size_type()` which in turn uses:

```
jint max_hi = max_array_length(elem()->basic_type());
```

That is, one uses `elem()->array_element_basic_type()` and the other
`elem()->basic_type()`. As a result, the test that guarantees a new
array allocation doesn't exceed the maximum array size and the
`CastII` that narrows the length on the success path for the
allocation don't use the same maximum array size values. The `CastII`
one is lower and it is transformed to top. The fallthrough path should
die but doesn't.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316414](https://bugs.openjdk.org/browse/JDK-8316414): C2: large byte array clone triggers "failed: malformed control flow" assertion failure on linux-x86 (**Bug** - P3)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Contributors
 * Roberto Castañeda Lozano `<rcastanedalo@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15914/head:pull/15914` \
`$ git checkout pull/15914`

Update a local copy of the PR: \
`$ git checkout pull/15914` \
`$ git pull https://git.openjdk.org/jdk.git pull/15914/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15914`

View PR using the GUI difftool: \
`$ git pr show -t 15914`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15914.diff">https://git.openjdk.org/jdk/pull/15914.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15914#issuecomment-1735113264)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good and trivial to me.

**Comment by rwestrel** [comment]
@TobiHartmann thanks for the review

**Pull request closed without merging**
