### PR TITLE
JDK-8305484: Compiler::init_c1_runtime unnecessarily uses an Arena that lives for the lifetime of the process

### PR DESCRIPTION
**Pull request by jcking**
Remove unnecessary usage of Arena for globals that live the lifetime of the process and are initialized once.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305484](https://bugs.openjdk.org/browse/JDK-8305484): Compiler::init_c1_runtime unnecessarily uses an Arena that lives for the lifetime of the process

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13300/head:pull/13300` \
`$ git checkout pull/13300`

Update a local copy of the PR: \
`$ git checkout pull/13300` \
`$ git pull https://git.openjdk.org/jdk.git pull/13300/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13300`

View PR using the GUI difftool: \
`$ git pr show -t 13300`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13300.diff">https://git.openjdk.org/jdk/pull/13300.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13300#issuecomment-1494541210)

### CODE REVIEW

**Comment by jcking** [comment]
Actually, let me double check this isn't per-thread.

**Comment by jcking** [comment]
Looks like its only ever executed by a single thread.

**Review by vnkozlov — APPROVED** [review]
It is good for me too.

**Pull request closed without merging**
