### PR TITLE
8272358: Some tests may fail when executed with other locales than the US

### PR DESCRIPTION
**Pull request by mrserb**
As mentioned in the bug report this issue was reported a few times, I have checked all tests in tier1/tier2/tier3 and found these four tests which fail because of non-US locale. The common issue is that the output depends on the locale(ex: 3.14 VS 3,14).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272358](https://bugs.openjdk.java.net/browse/JDK-8272358): Some tests may fail when executed with other locales than the US

### Reviewers
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**) ⚠️ Review applies to 1254951aa3a12bd517f6ac7ecad1d89e3549978c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5098/head:pull/5098` \
`$ git checkout pull/5098`

Update a local copy of the PR: \
`$ git checkout pull/5098` \
`$ git pull https://git.openjdk.java.net/jdk pull/5098/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5098`

View PR using the GUI difftool: \
`$ git pr show -t 5098`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5098.diff">https://git.openjdk.java.net/jdk/pull/5098.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
There are still 1500+ failures due to non-US locale after this patch.

So my question is: does it make sense to fix only 4 of them?
Thanks.

**Comment by mrserb** [comment]
These are the only tests reported in Fr and Ru locales in t1/t2/t3. Are you sure that 1500 failures are caused by the tests issues and not a problem in JDK?

**Comment by DamonFool** [comment]
> These are the only tests reported in Fr and Ru locales in t1/t2/t3. Are you sure that 1500 failures are caused by the tests issues and not a problem in JDK?

If I test with `JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US"`, most of the failures would disappear.

make test  TEST="tier1 tier2 tier3" with your patch
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR
>> jtreg:test/hotspot/jtreg:tier1                     1810  1809     1     0 <<
>> jtreg:test/jdk:tier1                               2069  2065     4     0 <<
>> jtreg:test/langtools:tier1                         4238  2643  1593     2 <<
   jtreg:test/jaxp:tier1                                 0     0     0     0
   jtreg:test/lib-test:tier1                             0     0     0     0
   jtreg:test/hotspot/jtreg:tier2                      444   444     0     0
>> jtreg:test/jdk:tier2                               3765  3727    38     0 <<
>> jtreg:test/langtools:tier2                           12    10     2     0 <<
>> jtreg:test/jaxp:tier2                               452   449     3     0 <<
   jtreg:test/hotspot/jtreg:tier3                       85    85     0     0
   jtreg:test/jdk:tier3                                174   174     0     0
   jtreg:test/langtools:tier3                            0     0     0     0
   jtreg:test/jaxp:tier3                                 0     0     0     0
==============================
TEST FAILURE
```

------

make test JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US" TEST="tier1 tier2 tier3" with your patch
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR
>> jtreg:test/hotspot/jtreg:tier1                     1810  1809     1     0 <<
   jtreg:test/jdk:tier1                               2069  2069     0     0
>> jtreg:test/langtools:tier1                         4238  4230     8     0 <<
   jtreg:test/jaxp:tier1                                 0     0     0     0
   jtreg:test/lib-test:tier1                             0     0     0     0
   jtreg:test/hotspot/jtreg:tier2                      444   444     0     0
>> jtreg:test/jdk:tier2                               3765  3747    18     0 <<
   jtreg:test/langtools:tier2                           12    12     0     0
>> jtreg:test/jaxp:tier2                               452   451     1     0 <<
   jtreg:test/hotspot/jtreg:tier3                       85    85     0     0   
   jtreg:test/jdk:tier3                                174   174     0     0
   jtreg:test/langtools:tier3                            0     0     0     0
   jtreg:test/jaxp:tier3                                 0     0     0     0
==============================
TEST FAILURE
```

**Comment by mrserb** [comment]
> If I test with `JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US"`, most of the failures would disappear.

If the failure disappeared if the "user.language=en" is used does not mean that this is not a JDK bug or some other bugs in the tests. What is the reason for the falure?

**Comment by DamonFool** [comment]
> > If I test with `JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US"`, most of the failures would disappear.
> 
> If the failure disappeared if the "user.language=en" is used does not mean that this is not a JDK bug or some other bugs in the tests. What is the reason for the falure?

An important reason is that the expected output doesn't match due to different languages.
```
 STDERR:
  stdout: [];
  stderr: [??: ?? emptynumbootstrapmethods1 ???? main ??, ?? main ?????:
    public static void main(String[] args) 
 ?? JavaFX ?????????javafx.application.Application
 ]
  exitValue = 1
 
 java.lang.RuntimeException: 'Main method not found in class emptynumbootstrapmethods1' missing from stdout/stderr 
 
        at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
        at TestEmptyBootstrapMethodsAttr.main(TestEmptyBootstrapMethodsAttr.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
 JavaTest Message: Test threw exception: java.lang.RuntimeException
 JavaTest Message: shutting down test
 
 
 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Main method not found in class emptynumbootstrapmethods1' missing from stdout/stderr
```

E.g., Test runtime/classFileParserBug/TestEmptyBootstrapMethodsAttr.java with the locale:
```
LANG=en_US.UTF-8 \
LC_ALL=C \
```

**Comment by mrserb** [comment]
> There are still 1500+ failures due to non-US locale after this patch.
> 
> So my question is: does it make sense to fix only 4 of them?

This error means that your OpenJDK build contains the translation for your locale, and different tools use the resource bundles to translate different outputs. Looks like nobody validates that the translated output is correct for the various cases since the tests fail on non-US translated locales. I guess in the ideal world that tests should be updated to validate the output for each locale, or probably even better they should check that the output is correct for some specific "key" in the resource bundle.

The current issue is different, it fixes the tests depended on some specific float format and has no dependency on the resource bundles.

**Comment by DamonFool** [comment]
> > There are still 1500+ failures due to non-US locale after this patch.
> > So my question is: does it make sense to fix only 4 of them?
> 
> This error means that your OpenJDK build contains the translation for your locale, and different tools use the resource bundles to translate different outputs. Looks like nobody validates that the translated output is correct for the various cases since the tests fail on non-US translated locales. I guess in the ideal world that tests should be updated to validate the output for each locale, or probably even better they should check that the output is correct for some specific "key" in the resource bundle.
> 
> The current issue is different, it fixes the tests depended on some specific float format and has no dependency on the resource bundles.

I still don't understand why the failures are different.

But the fix doesn't work even with these 4 tests.


* Before this fix: make test TEST="..."
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR
   jtreg:test/langtools/jdk/jshell/ToolBasicTest.java
>>                                                       1     0     1     0 <<
   jtreg:test/langtools/jdk/jshell/ToolSimpleTest.java
>>                                                       1     0     1     0 <<
   jtreg:test/langtools/tools/javac/lambda/lambdaExecution/LambdaTranslationTest1.java
                                                         1     1     0     0
   jtreg:test/langtools/tools/javac/lambda/lambdaExecution/LambdaTranslationTest2.java
                                                         1     1     0     0
==============================
TEST FAILURE
```


* After this fix: make test TEST="..."
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR
   jtreg:test/langtools/jdk/jshell/ToolBasicTest.java
>>                                                       1     0     1     0 <<
   jtreg:test/langtools/jdk/jshell/ToolSimpleTest.java
>>                                                       1     0     1     0 <<
   jtreg:test/langtools/tools/javac/lambda/lambdaExecution/LambdaTranslationTest1.java
                                                         1     1     0     0
   jtreg:test/langtools/tools/javac/lambda/lambdaExecution/LambdaTranslationTest2.java
                                                         1     1     0     0
==============================
TEST FAILURE
```

But if I run with make test JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US" TEST="...", all of them get passed.

**Comment by mrserb** [comment]
> I still don't understand why the failures are different.

The difference is that if the test uses golden data for EN locale only while the tested tool like javac supports more than one locale for some specific output message then the test should check that specific localized message.

> But the fix doesn't work even with these 4 tests.

Look like you use one of ja or zh_CN locales since only for these locales there are translations, the test should take it into account. It is not strictly correct to run add "-Duser.language=en -Duser.country=US" to it to fix such issues.

**Comment by DamonFool** [comment]
> > I still don't understand why the failures are different.
> 
> The difference is that if the test uses golden data for EN locale only while the tested tool like javac supports more than one locale for some specific output message then the test should check that specific localized message.
> 
> > But the fix doesn't work even with these 4 tests.
> 
> Look like you use one of ja or zh_CN locales since only for these locales there are translations, the test should take it into account. It is not strictly correct to run add "-Duser.language=en -Duser.country=US" to it to fix such issues.

Thanks @mrserb for your clarification.

Shall we also fix ToolBasicTest.java and ToolSimpleTest.java just as what is done for LambdaTranslationTest1.java and LambdaTranslationTest2.java?
If so, the 4 tests would be also fixed on our MacOS platforms.

And do you test the fix on Linux?
Thanks.

**Comment by mrserb** [comment]
> Shall we also fix ToolBasicTest.java and ToolSimpleTest.java just as what is done for LambdaTranslationTest1.java and LambdaTranslationTest2.java? If so, the 4 tests would be also fixed on our MacOS platforms.

I do not want to add a global locale parameter to the places which may trigger loading of the different translations.
Probably we missed the bugs like this(not exactly but similar to) https://bugs.openjdk.java.net/browse/JDK-8274544 because everybody passes US locale to the tests. Probably we missed some other bugs as well.

> And do you test the fix on Linux? Thanks.

On Linux  I have checked "JA" and "RU" locales, nothing changed for "JA" it uses the same float format as the US, so the LambdaTranslationTest1/LambdaTranslationTest2 passed before/after the fix and the ToolBasicTest/ToolSimpleTest failed in the "JA" locale, one of the subtests compare the expected output saved for US locale with the real output of the test.

For RU locale the tests fail before the fix and passed after because there is no specific translation so the US text is used, and this PR fixes the problem in the float format.

**Comment by DamonFool** [comment]
So this change doesn't fix the failure with Chinese and JA locales.

**Comment by mrserb** [comment]
> So this change doesn't fix the failure with Chinese and JA locales.

Yes, I can rephrase it as "it fixes the locales which do not have translations".

**Comment by DamonFool** [comment]
> > So this change doesn't fix the failure with Chinese and JA locales.
> 
> Yes, I can rephrase it as "it fixes the locales which do not have translations".

Then people with RU locale should look at this fix.

**Comment by mrserb** [comment]
@aivanov-jdk please take a look

**Review by aivanov-jdk — APPROVED** [review]
I can confirm that these fixes make these tests pass in Russian locale.

Two of the tests fail with timeout for me: `ToolBasicTest.java` and `ToolSimpleTest.java`; the other two `LambdaTranslationTest{1,2}.java` fail without the fix and pass with the proposed fix applied. I'm inclined to trust that the first pair also passes successfully with the fix.

**Pull request closed without merging**
