### PR TITLE
8303410: Remove ContentSigner APIs and jarsigner -altsigner and -altsignerpath options

### PR DESCRIPTION
**Pull request by eirbjo**
The `-altsigner` and `-altsignerpath` options in JarSigner with the underlying `ContentSigner` mechanism were deprected in Java 9, for removal in Java 15. See [JDK-8076535](https://bugs.openjdk.org/browse/JDK-8076535), [JDK-8242260](https://bugs.openjdk.org/browse/JDK-8242260).

This PR suggests it's time to remove this code:

- The package `com/sun/jarsigner` is removed. This contained the `ContentSigner` and `ContentSignerParameters` along with a `package-info.java` file.
- `JarSigner.java` is updated to remove processing of the `-altsigner` and `-altsignerpath` options and the loading and processing of the custom `ContentSigner`.
- Similarly `c.s.s.t.jarsigner.Main` is updated to remove processing and mentioning of `-altsigner` and `-altsignerpath` options.
- Mentions of the options in Resource files in the same directory is removed
- The `jarsigner.1` man page is updated to remove the section on the deprecated options
- The `Spec` and `Options` tests are update to remove usage of the `-altsigner` and `-altsignerpath` options.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8303469](https://bugs.openjdk.org/browse/JDK-8303469) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8303410](https://bugs.openjdk.org/browse/JDK-8303410): Remove ContentSigner APIs and jarsigner -altsigner and -altsignerpath options ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).
 * [JDK-8303469](https://bugs.openjdk.org/browse/JDK-8303469): Remove ContentSigner APIs and jarsigner -altsigner and -altsignerpath options (**CSR**)

### Reviewers
 * [Weijun Wang](https://openjdk.org/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12791/head:pull/12791` \
`$ git checkout pull/12791`

Update a local copy of the PR: \
`$ git checkout pull/12791` \
`$ git pull https://git.openjdk.org/jdk pull/12791/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12791`

View PR using the GUI difftool: \
`$ git pr show -t 12791`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12791.diff">https://git.openjdk.org/jdk/pull/12791.diff</a>

</details>

### CODE REVIEW

**Comment by eirbjo** [comment]
Suggested release note:

Release Note: Removal of the -altsigner mechanism in jarsigner

The `jarsigner` options `-altsigner` and `-altsignerpath` have been removed, along with the underlying `ContentSigner` API in the package `com.sun.jarsigner` . The mechanism was deprecated in JDK 9 and marked for removal in JDK 15.

**Comment by eirbjo** [comment]
Suggested CSR:

### Compatibility Kind: 
source, binary, behavioral

### Compatibility Risk
minimal

### Compatibility Risk Description
The APIs were deprecated in JDK 9 with no known existing use. The probability that they have been used after that time is low.

### Summary
The `ContentSigner` API in `com.sun.jarsigner` and the accompanying `jarsigner` options `-altsigner` and `-altsignerpath` options have been deprecated for removal since JDK 15 and should be removed.

### Problem
This extension mechanism was deprecated in JDK 9 since it was deemed too low-level and had no known use. Removing it will reduce maintainence costs for jarsigner. 

### Solution
Remove the terminally deprecated classes `com.sun.jarsigner.ContentSigner`, `com.sun.jarsigner.ContentSignerParameters`and the associated `package-info.java` file.

Remove the `-altsigner` and `-altsignerpath` options from jarsigner tool. Remove any mention of these options from the jarsigner man page.

### Specification

The classes `com.sun.jarsigner.ContentSigner` and `com.sun.jarsigner.ContentSignerParameters` are removed. Any class implementing these interfaces will fail to compile.

`jarsigner --help` no longer list the -altsigner or -altsigner options.

`jarsigner -altsigner` will fail with an 'illegal option' message:

```
% jarsigner -altsigner
Illegal option: -altsigner
```

**Comment by eirbjo** [comment]
I noticed that the `-altsigner` and `-altsigner` were deprectated for removal in JDK 15, but their `@Deprecated` annotations say `since="16"`.  Is inconsistency something we need to worry about?

**Comment by LanceAndersen** [comment]
> I noticed that the `-altsigner` and `-altsigner` were deprectated for removal in JDK 15, but their `@Deprecated` annotations say `since="16"`. Is inconsistency something we need to worry about?
> 
> ```java
> @Deprecated(since="16", forRemoval=true)
> private final String altSignerPath;
> @Deprecated(since="16", forRemoval=true)
> private final String altSigner;
> ```

I don't see an issue with a different version and given this was done in JDK 16 we are now 3 soon to be 4 releases past the notification

**Comment by LanceAndersen** [comment]
> Suggested CSR:
> 
> ### Compatibility Kind:
> source, binary, behavioral
> 
> ### Compatibility Risk
> minimal
> 
> ### Compatibility Risk Description
> The APIs were deprecated in JDK 9 with no known existing use. The probability that they have been used after that time is low.
> 
> ### Summary
> The `ContentSigner` API in `com.sun.jarsigner` and the accompanying `jarsigner` options `-altsigner` and `-altsignerpath` options have been deprecated for removal since JDK 15 and should be removed.
> 
> ### Problem
> This extension mechanism was deprecated in JDK 9 since it was deemed too low-level and had no known use. Removing it will reduce maintainence costs for jarsigner.
> 
> ### Solution
> Remove the terminally deprecated classes `com.sun.jarsigner.ContentSigner`, `com.sun.jarsigner.ContentSignerParameters`and the associated `package-info.java` file.
> 
> Remove the `-altsigner` and `-altsignerpath` options from jarsigner tool. Remove any mention of these options from the jarsigner man page.
> 
> ### Specification
> The classes `com.sun.jarsigner.ContentSigner` and `com.sun.jarsigner.ContentSignerParameters` are removed. Any class implementing these interfaces will fail to compile.
> 
> `jarsigner --help` no longer list the -altsigner or -altsigner options.
> 
> `jarsigner -altsigner` will fail with an 'illegal option' message:
> 
> ```
> % jarsigner -altsigner
> Illegal option: -altsigner
> ```

This looks good overall.  I would probably make the compatibility risk _low_.  

For your spec changes, I might borrow the format I used in [JDK-8193757](https://bugs.openjdk.org/browse/JDK-8193757)

**Comment by eirbjo** [comment]
> For your spec changes, I might borrow the format I used in [JDK-8193757](https://bugs.openjdk.org/browse/JDK-8193757)

I updated the Specification section to use the list-style format from JDK-8193757. I also included a mention of the jarsigner deprectated options section.

**Comment by LanceAndersen** [comment]
> > For your spec changes, I might borrow the format I used in [JDK-8193757](https://bugs.openjdk.org/browse/JDK-8193757)
> 
> I updated the Specification section to use the list-style format from JDK-8193757. I also included a mention of the jarsigner deprectated options section.
> 
> I'm assuming the Specification section should focus on externally visible changes, not implementation-internal removals.

Thank you for the quick updates :-)

Yes the Specification section addresses the changes to the spec that impact  users

**Comment by seanjmullan** [comment]
I would add more words to the title of the issue to cover the changes, ex: "Remove ContentSigner APIs and jarsigner -altsigner and -altsignerpath options"

**Comment by eirbjo** [comment]
The CSR seems to be approved, so I guess it should be OK to proceeed with reviewing the actual deletions now?

**Comment by eirbjo** [comment]
> BTW, you don't need to touch `jarsigner.1`. It is auto-generated and another team maintains the source.

Thanks, I was not aware. I have reverted the changes to this file and trust it will be updated through some other channel.

**Comment by eirbjo** [comment]
> `src/jdk.jartool/share/classes/module-info.java` and `test/jdk/TEST.groups` still reference `com.sun.jarsigner`.

Well spotted, I have removed these references.

I'm assuming the references in the jdk.compiler symbol tables will be updated through some form of automation.

**Comment by eirbjo** [comment]
Oops, I removed those!

**Comment by eirbjo** [comment]
Thanks for reviewing Weijun!

I'll let this simmer for a bit before integrating just in case someone else would want to have a look.

**Comment by eirbjo** [comment]
I see that the Release Note for this PR did not seem to get any review comments or edits. Probably it's ok, but perhaps a Reviewer could take an extra look anyway:

https://bugs.openjdk.org/browse/JDK-8303536

**Pull request closed without merging**
