### PR TITLE
8314759: VirtualThread.parkNanos timeout adjustment when pinned should be replaced

### PR DESCRIPTION
**Pull request by AlanBateman**
If yielding fails due to the pinning then VirtualThread.parkNanos parks on the carrier thread with the remaining time. The calculation of the remaining time needs to be replaced so that it obviously uses the difference between the start and end time in the calculation. The current code isn't correct for cases where System.nanoTimes return a negative value or when parking for durations close to Long.MAX_VALUE (292 years). The change isn't really testable so there aren't any test changes included.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314759](https://bugs.openjdk.org/browse/JDK-8314759): VirtualThread.parkNanos timeout adjustment when pinned should be replaced (**Bug** - P4)

### Reviewers
 * [Andrey Turbanov](https://openjdk.org/census#aturbanov) (@turbanoff - Committer)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15405/head:pull/15405` \
`$ git checkout pull/15405`

Update a local copy of the PR: \
`$ git checkout pull/15405` \
`$ git pull https://git.openjdk.org/jdk.git pull/15405/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15405`

View PR using the GUI difftool: \
`$ git pr show -t 15405`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15405.diff">https://git.openjdk.org/jdk/pull/15405.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15405#issuecomment-1691093757)

### CODE REVIEW

**Review by turbanoff — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
LGTM

**Comment by dfuch** [comment]
Although... what happens if parkOnCarrierThread is called with a negative value (as that could happen here)?

**Pull request closed without merging**
