### PR TITLE
8342042: PPC64: compiler_fast_unlock_object flags failure instead of success

### PR DESCRIPTION
**Pull request by reinrich**
This change inverts the `EQ` bit in `flag` with a condition register nand instruction in order to meet the post condition given at L2751-L2752:

```
  // flag == EQ indicates success, decrement held monitor count
  // flag == NE indicates failure
```

The fix passed our CI testing with LockingMode set to LM_LEGACY
Tier1-4 of hotspot and jdk. All of Langtools and jaxp. Renaissance Suite and SAP specific tests.
Testing was done on the main platforms and also on Linux/PPC64le and AIX.

The test runtime/logging/MonitorInflationTest.java failed on all platforms. Apparently it has issues with LM_LEGACY.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342042](https://bugs.openjdk.org/browse/JDK-8342042): PPC64: compiler_fast_unlock_object flags failure instead of success (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)
 * [Fredrik Bredberg](https://openjdk.org/census#fbredberg) (@fbredber - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21496/head:pull/21496` \
`$ git checkout pull/21496`

Update a local copy of the PR: \
`$ git checkout pull/21496` \
`$ git pull https://git.openjdk.org/jdk.git pull/21496/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21496`

View PR using the GUI difftool: \
`$ git pr show -t 21496`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21496.diff">https://git.openjdk.org/jdk/pull/21496.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21496#issuecomment-2413047305)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Good catch! LGTM.

**Comment by reinrich** [comment]
Thanks for the quick review!

**Comment by xmas92** [comment]
Seems like `compiler_fast_unlock_lightweight_object` could do the same. 

It does the same branch, but correctly, by going through a `crorc(CCR0, Assembler::equal, CCR0, Assembler::equal)` in the success path.

**Comment by reinrich** [comment]
> Seems like `compiler_fast_unlock_lightweight_object` could do the same.
> 
> It does the same branch, but correctly, by going through a `crorc(CCR0, Assembler::equal, CCR0, Assembler::equal)` in the success path.

I think you're right. I wanted to see if [`set_eq_unlocked`](https://github.com/openjdk/jdk/blob/dcac4b0a532f2ca6cb374da7ece331e8266ab351/src/hotspot/cpu/ppc/macroAssembler_ppc.cpp#L3087) could be eliminated and then forgot about it.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for improving it!

**Review by xmas92 — APPROVED** [review]

**Comment by fbredber** [comment]
@reinrich 
Thank you for finding and fixing this. Also sorry for not finding this when I tested my PR.

**Review by fbredber — APPROVED** [review]

**Comment by reinrich** [comment]
> @reinrich Thank you for finding and fixing this. Also sorry for not finding this when I tested my PR.

Thanks for looking at this @fbredber. Even with the assertions from https://github.com/openjdk/jdk/pull/21494 this didn't cause failures testing jdk 24. So no worries about the testing of your PR.
I found the issue working on the PPC port of the vthread monitor support in the loom repo. There an assertion in the runtime failed when the slow path was taken. I don't know why though.

**Comment by reinrich** [comment]
Thanks again for the reviews.
/integrate

**Pull request closed without merging**
