### PR TITLE
8292635: Run ArchivedEnumTest.java in jdk tier testing

### PR DESCRIPTION
**Pull request by calvinccheung**
Moving the `ArchivedEnumTest.java` from `runtime/cds/appcds/cacheObject` to `jdk/internal/misc/CDS` so that the test will be run in jdk-tier1. This is to avoid inadvertently breakage of the test like in JDK-8292499.

Since jdk tier testing runs with product builds, the CDSHeapVerifier::verify() needs to be enabled with product builds. 
Currently, the verify() function only checks built-in classes. 

Testing: jdk-tier1, tier3, tier4.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292635](https://bugs.openjdk.org/browse/JDK-8292635): Run ArchivedEnumTest.java in jdk tier testing

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11999/head:pull/11999` \
`$ git checkout pull/11999`

Update a local copy of the PR: \
`$ git checkout pull/11999` \
`$ git pull https://git.openjdk.org/jdk pull/11999/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11999`

View PR using the GUI difftool: \
`$ git pr show -t 11999`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11999.diff">https://git.openjdk.org/jdk/pull/11999.diff</a>

</details>

### CODE REVIEW

**Review by iklam — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
I'm a bit confused. The JBS issue lists two things to do to improve verification, but all this PR seems to do is move the test - in which case the JBS issue should be updated.

This PR also changes the verification logic to be available in product builds - presumably because JDK testing uses product builds not debug ones - but this is not mentioned. Can I assume this change in itself has no impact unless verification is explicitly requested?

**Comment by calvinccheung** [comment]
> I'm a bit confused. The JBS issue lists two things to do to improve verification, but all this PR seems to do is move the test - in which case the JBS issue should be updated.
> 

We will only address item [2] in the bug description in JDK 21.
I've updated both the bug and PR titles to reflect what is being done.

> This PR also changes the verification logic to be available in product builds - presumably because JDK testing uses product builds not debug ones - but this is not mentioned. Can I assume this change in itself has no impact unless verification is explicitly requested?

Yes, jdk-tier1 testing uses product builds.

**Review by dholmes-ora — APPROVED** [review]
Thanks for the updates to JBS and the PR regarding the change in verification behaviour.

Looks good.

**Comment by calvinccheung** [comment]
Thanks @iklam and @dholmes-ora for the review.

/integrate

**Pull request closed without merging**
