### PR TITLE
8270848: Redundant unsafe opmask register allocation in some instruction patterns.

### PR DESCRIPTION
**Pull request by jatin-bhateja**
- Some string compare/array equality patters in x86_[32/64].ad files accept the temporary opmark register operands, instructions using these registers are guarded by target feature checks.
- Even if control path leading to these instructions is not chosen, RA will still allocate physical registers to these temporary operands.
- Pulling out the feature checks upto the instruction level can save redundant allocations which may effect spilling decisions.
- Also existing platform dependent routine Matcher::has_predicated_vector() check the existence of AVX512VL feature which is not required.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270848](https://bugs.openjdk.java.net/browse/JDK-8270848): Redundant unsafe opmask register allocation in some instruction patterns.

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to 865cfbd15e5a843a8d54a7f79ebdc606f38345e5
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4813/head:pull/4813` \
`$ git checkout pull/4813`

Update a local copy of the PR: \
`$ git checkout pull/4813` \
`$ git pull https://git.openjdk.java.net/jdk pull/4813/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4813`

View PR using the GUI difftool: \
`$ git pr show -t 4813`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4813.diff">https://git.openjdk.java.net/jdk/pull/4813.diff</a>

</details>

### CODE REVIEW

**Comment by sviswa7** [comment]
The patch looks good to me.

**Review by sviswa7 — APPROVED** [review]

**Comment by jatin-bhateja** [comment]
Thanks @sviswa7 , do we need one more reviewer consent here.

**Comment by jatin-bhateja** [comment]
Hi @vnkozlov , can you kindly review the patch.

**Review by vnkozlov — COMMENTED** [review]
From correctness point of view changes are good - we should check features instead of `UseAVX` flag. As we found hard way, not all avx512 CPUs supports all avx512 features.
But it means that this change is only useful on KNL cpus. Or you have other cases?

**Comment by jatin-bhateja** [comment]
> From correctness point of view changes are good - we should check features instead of `UseAVX` flag. As we found hard way, not all avx512 CPUs supports all avx512 features.
> But it means that this change is only useful on KNL cpus. Or you have other cases?

Problem will mainly be seen on KNL since they lack VL feature, thus Matcher::has_predicate_register will return a false,  but for these patterns opmaks argument will still get allocated. Pulling the feature check out up till the predicate level will guide the matcher to select appropriate patterns without opmask operands for KNL. 

Your suggested changes have been incorporated.

**Review by vnkozlov — APPROVED** [review]
Looks good.
Let me test it before you push.

**Comment by vnkozlov** [comment]
Testing passed clean.

**Comment by jatin-bhateja** [comment]
> Looks good.
> Let me test it before you push.

Thanks for your help!

**Pull request closed without merging**
