### PR TITLE
8331855: Convert jdk.jdeps jdeprscan and jdeps to use the Classfile API

### PR DESCRIPTION
**Pull request by liach**
Summary of the changes:
 - Moved `com.sun.tools.classfile.Dependency` and `Dependencies` to jdeps; they are exclusively used by jdeps in sources, and they are not used in any tests too. This will ease the removal of `com.sun.tools.classfile` later.
 - A few visitor patterns have been rewritten with pattern matching, notably in:
   - `CPEntries`/`CPSelector` (removed)
   - `Dependencies.BasicDependencyFinder.Visitor` has been rewritten to use pattern matching to capture dependencies.
 - `MethodSig` and its tests have been removed in favor of `MethodTypeDesc`.
 - Otherwise, the changes are mostly mechanical replacements.

All tests in `test/langtools/tools/jdeprscan` and `test/langtools/tools/jdeps` pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331855](https://bugs.openjdk.org/browse/JDK-8331855): Convert jdk.jdeps jdeprscan and jdeps to use the Classfile API (**Sub-task** - P4)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19193/head:pull/19193` \
`$ git checkout pull/19193`

Update a local copy of the PR: \
`$ git checkout pull/19193` \
`$ git pull https://git.openjdk.org/jdk.git pull/19193/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19193`

View PR using the GUI difftool: \
`$ git pr show -t 19193`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19193.diff">https://git.openjdk.org/jdk/pull/19193.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19193#issuecomment-2106002118)

### CODE REVIEW

**Comment by liach** [comment]
@asotona Requesting your review for this and the other test migration patch.

**Review by asotona — APPROVED** [review]
Looks good to me, thanks!

**Comment by liach** [comment]
Thanks for the review!

/integrate

**Pull request closed without merging**
