### PR TITLE
8263236: runtime/os/TestTracePageSizes.java fails on old kernels

### PR DESCRIPTION
**Pull request by shipilev**
See the bug report for details. On some kernels, we have trouble parsing madvise tags from `/proc/smaps`.

Additional testing:
 - [x] Test with kernel 5.4.0 (still passes)
 - [x] Test with kernel 4.9.0 (used to fail, now passes)
 - [x] Test with kernel 4.15 (still passes)
 - [x] Test with kernel 4.14.17 (used to fail, now passes)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263236](https://bugs.openjdk.java.net/browse/JDK-8263236): runtime/os/TestTracePageSizes.java fails on old kernels

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 6db67d612cc4f09264033d5a56a43c90fbade8e5
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to 5bf7827c12d721759d3ba6519f33199ce9bffb69

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3415/head:pull/3415` \
`$ git checkout pull/3415`

Update a local copy of the PR: \
`$ git checkout pull/3415` \
`$ git pull https://git.openjdk.java.net/jdk pull/3415/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3415`

View PR using the GUI difftool: \
`$ git pr show -t 3415`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3415.diff">https://git.openjdk.java.net/jdk/pull/3415.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Anyone? :)

**Comment by shipilev** [comment]
Anyone? This unfortunately breaks `tier1` on some of our testing hosts.

**Review by dholmes-ora — APPROVED** [review]
Hi Aleksey,

I can't really evaluate the changes as I'm not familiar with the information that is being queried. I get the gist of things and as this is a test the real question is whether the test now passes okay. So on that basis I'll approve it.

Thanks,
David

**Comment by tstuefe** [comment]
I try to understand this. So:

AnonHugePages - number of huge pages mapped into area, THP or explicit
ht - this area is mapped with explicit huge pages
hg - this area is mapped with madvise(huge_pages), which indicates THP

Therefore: !ht && AnonHugePages > 0 -> THP?

What confuses me is that the kernel patch you refer to: https://github.com/torvalds/linux/commit/50f8b92f21d23789bd4ada593e8ddc56cc4f79fe sounds like the flag is not passed down to the memory management layer. Would this not effectively switch off THP for the region, and the resulting mapping would use small pages? In which case the failing test would have been correct, since we specified UseTransparentHugePages but it did not work?

Sorry for my confusion.

..Thomas

**Comment by shipilev** [comment]
(sighs) The recent pull made the test fail again even with this patch. Let me see what is up there...

**Comment by pfustc** [comment]
This test is in tier1. Shall we ProblemList it if we can't fix it in a short time?

**Comment by tstuefe** [comment]
We cannot problemlist it for older kernels only, unfortunately.
@kstefanj could you have a look at this?

**Comment by kstefanj** [comment]
Sorry, totally missed this PR. I saw the bug-report a while back and hoped my recent refactoring would help the situation, but I guess it only made things worse? Will take a look.

**Comment by shipilev** [comment]
I notice that the failures are like this with debug turned on:

```
From logfile: [0.004s][info][pagesize] CodeHeap 'non-nmethods':  min=4M max=8M base=0x00007fffd9200000 page_size=2M size=8M
From smaps: [7fffd9200000, 7fffd9600000) anonHugePages = 0 pageSize=4KB isTHP=false isHUGETLB=false
```

```
From logfile: [0.011s][info][pagesize] Block Offset Table: req_size=2580K base=0x00007fffd7400000 page_size=2M alignment=2M size=4M
From smaps: [7fffd7400000, 7fffd7600000) anonHugePages = 0 pageSize=4KB isTHP=false isHUGETLB=false
```

So these probably are not committed yet, because `-XX:+AlwaysPreTouch` (set by test) do not affect them. (sighs)

**Comment by kstefanj** [comment]
@shipilev, do you know which change did break the test again, I did a few different cleanup that are related.

**Comment by kstefanj** [comment]
@shipilev, that sounds like a valid theory. But not sure why that should have changed recently.

**Comment by shipilev** [comment]
> @shipilev, do you know which change did break the test again, I did a few different cleanup that are related.

Don't know yet. But I think this kind of failure highlights that tracking `AnonHugePages` is not fool-proof either: we implicitly rely on allocations/commit happen in that area to have AHP != 0. Which is doable for Java heap with `-XX:+AlwaysPreTouch`, but not for VM areas. There are various -XX:+Zap* flags, but they do not cover every VM area. 

> @shipilev, that sounds like a valid theory. But not sure why that should have changed recently.

I am now not even sure that the test passed reliably during my first attempt. All 6 subtests intermittently pass/fails with this patch.

Let me mull over this a bit. Maybe the saner way out would be checking the kernel version and bailing on older kernels.

**Comment by kstefanj** [comment]
> Let me mull over this a bit. Maybe the saner way out would be checking the kernel version and bailing on older kernels.

That would be one approach, when I first started to think about supporting THP for the test I looked at a few different ways including `AnonHugePages` but the one that was most reliable was to check the flag. I would be totally ok with excluding the test for older kernels, not sure if we have a good way to figure this out or if we have to do some parsing.

**Comment by shipilev** [comment]
Ran out of ideas. New version checks for kernel version and bails on kernels lower than 5.x. I shall try and see if I can find the more precise kernel version where this was fixed. Meanwhile, would the coarse check like this work, if I could not find a more precise version?

**Review by kstefanj — APPROVED** [review]
Looks good to me. The `isLinux()` check should not be needed since we require this to only run on Linux. But it won't hurt and makes it more clear so I'm good with it.

**Review by tstuefe — APPROVED** [review]
Looks good to me too.

**Comment by kstefanj** [comment]
Just realized one thing... you might be able to solve it with just adding to the `@requires` line as well, something like:
`@requires os.family == "linux" & os.simpleVersion >= 5` 
But I'm not sure if `>=` is allowed for `simpleVersion` and I'm not at all sure how `simpleVersion`is made available. Maybe it is a Mac thing, the only tests using it only matters for Mac. Maybe `os.versionMajor` is available to use. If you like this approach maybe you can try and see if it works.

**Comment by tstuefe** [comment]
Should we just handle AlwaysPretouch directly in os::reserve_memory() instead of having each caller do this? Or would this interfere with concurrent pretouching?

**Comment by kstefanj** [comment]
In theory this would be good, but as you say it would make parallel/concurrent pre-touch harder. Or at least we would have to extend a lot of APIs to pass down the needed work gang.

**Comment by shipilev** [comment]
Okay, I did a rough bisect over pre-built Debian kernels, and that points to `4.15` as the first kernel that works. I updated the PR changeset and PR description accordingly. I am still struggling to find a particular commit that solved it, so I can explain to myself why this works... Anyhow, the version check would not get more precise that this, since we only have major and minor OS versions.

**Review by kstefanj — APPROVED** [review]
👍

**Comment by tstuefe** [comment]
> In theory this would be good, but as you say it would make parallel/concurrent pre-touch harder. Or at least we would have to extend a lot of APIs to pass down the needed work gang.

Or make this an optional part of reservation, to be controlled by yet anther argument (sigh - maybe not :)

**Comment by shipilev** [comment]
> Okay, I did a rough bisect over pre-built Debian kernels, and that points to `4.15` as the first kernel that works. I updated the PR changeset and PR description accordingly. I am still struggling to find a particular commit that solved it, so I can explain to myself why this works...

All right. Here is a kicker. Vanilla `4.14.17` kernel is passing the tests, while Debian's `4.14.17` fails it! Looking at Debian kernel patches, I see a few suspicious ones. Applying [these patches](https://salsa.debian.org/kernel-team/linux/-/commit/3f937de4507cf678ebfa53654bee5ffe20d76ad6) to vanilla `4.14.17` also makes it fail. This hunk from that kernel patch is the problem:

```
diff --git a/include/linux/mman.h b/include/linux/mman.h
index 7c87b6652244..f22c15d5e24c 100644
--- a/include/linux/mman.h
+++ b/include/linux/mman.h
@@ -87,7 +87,8 @@ calc_vm_flag_bits(unsigned long flags)
 {
 	return _calc_vm_trans(flags, MAP_GROWSDOWN,  VM_GROWSDOWN ) |
 	       _calc_vm_trans(flags, MAP_DENYWRITE,  VM_DENYWRITE ) |
-	       _calc_vm_trans(flags, MAP_LOCKED,     VM_LOCKED    );
+	       _calc_vm_trans(flags, MAP_LOCKED,     VM_LOCKED    ) |
+	       _calc_vm_trans(flags, MAP_FIXED,      VM_FIXED     );
 }
```

It copies the mmap tags to the VMA flag. Now, that thing is getting printed in [show_smap_vma_flags](https://github.com/torvalds/linux/blob/master/fs/proc/task_mmu.c#L603-L681). Notice how that method prepares itself for missing flag cases by [printing `??`](https://github.com/torvalds/linux/blob/master/fs/proc/task_mmu.c#L609-L612). Indeed, Debian patch misses that addition, so we see `??` for some entries in `/proc/smaps`.

How's that a problem for this test? Stare at this regexp:

```
        String smapsPatternString = "(\\w+)-(\\w+).*?" +
                                    "KernelPageSize:\\s*(\\d*) kB.*?" +
                                    "VmFlags: ([\\w ]*)";
```

`?` is _not_ `\w`, so the entire thing mismatches the moment the VMA flags have `??` in them. 

And this only happens on some Debian kernels, because you have to have that new unhandled flag. This also explains why `4.15` works, the [later commit](https://salsa.debian.org/kernel-team/linux/-/commit/7dd9b58675f9c285944cd6b12199481765c932a0#b23bf90ba1c0322d4a1bb8ace6fac27f98426b10_21_21) redefined that new flag to existing, handled value for `VM_ARCH`.

So this is deserves a simple fix in the regexp itself:

```
-                                    "VmFlags: ([\\w ]*)";
+                                    "VmFlags: ([\\w\\? ]*)";
```

Testing that now...

**Review by kstefanj — APPROVED** [review]
Great dig @shipilev 👍 

So the `hg` vmFlag is present for all kernels we care about?

**Comment by shipilev** [comment]
> So the `hg` vmFlag is present for all kernels we care about?

Apparently. It is the test regexp that mismatches when kernel replies `??` for any other VMA flag.

**Comment by kstefanj** [comment]
> > So the `hg` vmFlag is present for all kernels we care about?
> 
> Apparently. It is the test regexp that mismatches when kernel replies `??` for any other VMA flag.

Got that. Just wanted to make sure noone else had this problem because they were on an even older kernel where `ht` actually wasn't added. But even if that is the case this fix is good =)

**Comment by shipilev** [comment]
> > > So the `hg` vmFlag is present for all kernels we care about?
> > 
> > 
> > Apparently. It is the test regexp that mismatches when kernel replies `??` for any other VMA flag.
> 
> Got that. Just wanted to make sure noone else had this problem because they were on an even older kernel where `ht` actually wasn't added.

The way I see the kernel sources, `ht` is available since the day `VmFlags` field [was introduced](https://github.com/torvalds/linux/commit/834f82e2aa9a8ede94b17b656329f850c1471514) in the smaps. Unless there is a bug that corrupts the VMA flag somewhere, we should be good.

**Comment by tstuefe** [comment]
Hah. Beautiful. And somewhat ironic, what are the odds that the offending patch was actually a workaround for a hotspot issue.

+1.

**Pull request closed without merging**
