### PR TITLE
8344471: Remove SecurityManager related code from java.compiler module

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which cleans up the SecurityManager related usages from the `java.compiler` module? 

No new tests have been introduced and existing tests in tier1, tier2 and tier3 continue to pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344471](https://bugs.openjdk.org/browse/JDK-8344471): Remove SecurityManager related code from java.compiler module (**Bug** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22229/head:pull/22229` \
`$ git checkout pull/22229`

Update a local copy of the PR: \
`$ git checkout pull/22229` \
`$ git pull https://git.openjdk.org/jdk.git pull/22229/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22229`

View PR using the GUI difftool: \
`$ git pr show -t 22229`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22229.diff">https://git.openjdk.org/jdk/pull/22229.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22229#issuecomment-2484977564)
</details>

### CODE REVIEW

**Review by RogerRiggs — COMMENTED** [review]
With only 1 caller the static matches() method could be inlined.
(No local variables are needed).

**Comment by jaikiran** [comment]
> With only 1 caller the static matches() method could be inlined.

Done - I've removed that private method and inlined that implementation.

**Review by RogerRiggs — APPROVED** [review]
Looks good, thanks

**Comment by jaikiran** [comment]
Thank you Roger for the review. 

Could someone from the compiler team too take a look and see if this trivial change looks OK?

**Review by lahodaj — APPROVED** [review]
Looks OK to me.

**Review by jonathan-gibbons — APPROVED** [review]
Looks good to em

**Comment by jaikiran** [comment]
Thank you all for the reviews.

**Pull request closed without merging**
