### PR TITLE
8256009: Remove src/hotspot/share/adlc/Test/i486.ad

### PR DESCRIPTION
**Pull request by DamonFool**
src/hotspot/share/adlc/Test/i486.ad is empty.
It might be better to remove it.
Thanks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ❌ (1/2 failed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |    | 

**Failed test task**
- [macOS x64 (build debug)](https://github.com/DamonFool/jdk/runs/1373767215)

### Issue
 * [JDK-8256009](https://bugs.openjdk.java.net/browse/JDK-8256009): Remove src/hotspot/share/adlc/Test/i486.ad

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1107/head:pull/1107`
`$ git checkout pull/1107`

### CODE REVIEW

**Comment by shipilev** [comment]
Might also be a good time to rewrite the references to `x486.ad` to either `x86.ad` or `x86_32.ad` or `x86_64.ad`:

```
$ ack i486.ad src
src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
343:          // TODO: The encoding of D2I in i486.ad can cause an exception

src/hotspot/os_cpu/bsd_x86/os_bsd_x86.cpp
552:          // TODO: The encoding of D2I in i486.ad can cause an exception

src/hotspot/cpu/ppc/ppc.ad
3891:  // Comment taken from i486.ad:
3903:  // Comment taken from i486.ad:

src/hotspot/share/opto/parse2.cpp
2340:      // For i486.ad, FILD doesn't restrict precision to 24 or 53 bits.
2355:    // For i486.ad, rounding is always necessary (see _l2f above).

src/hotspot/share/opto/machnode.hpp
154:  // Only returns non-null value for i486.ad's indOffset32X

src/hotspot/share/opto/machnode.cpp
298:    // In i486.ad, indOffset32X uses base==RegI and disp==RegP,

src/hotspot/share/adlc/output_c.cpp
3003:      // See BugId 4796752, operand indOffset32X in i486.ad

src/hotspot/share/runtime/synchronizer.cpp
62:// variants of the enter-exit fast-path operations.  See i486.ad fast_lock(),
```

**Comment by DamonFool** [comment]
> Might also be a good time to rewrite the references to `x486.ad` to either `x86.ad` or `x86_32.ad` or `x86_64.ad`:
> 
> ```
> $ ack i486.ad src
> src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
> 343:          // TODO: The encoding of D2I in i486.ad can cause an exception
> 
> src/hotspot/os_cpu/bsd_x86/os_bsd_x86.cpp
> 552:          // TODO: The encoding of D2I in i486.ad can cause an exception
> 
> src/hotspot/cpu/ppc/ppc.ad
> 3891:  // Comment taken from i486.ad:
> 3903:  // Comment taken from i486.ad:
> 
> src/hotspot/share/opto/parse2.cpp
> 2340:      // For i486.ad, FILD doesn't restrict precision to 24 or 53 bits.
> 2355:    // For i486.ad, rounding is always necessary (see _l2f above).
> 
> src/hotspot/share/opto/machnode.hpp
> 154:  // Only returns non-null value for i486.ad's indOffset32X
> 
> src/hotspot/share/opto/machnode.cpp
> 298:    // In i486.ad, indOffset32X uses base==RegI and disp==RegP,
> 
> src/hotspot/share/adlc/output_c.cpp
> 3003:      // See BugId 4796752, operand indOffset32X in i486.ad
> 
> src/hotspot/share/runtime/synchronizer.cpp
> 62:// variants of the enter-exit fast-path operations.  See i486.ad fast_lock(),
> ```

Good idea. 
Updated.
Thanks.

**Review by shipilev — APPROVED** [review]
I like this, thanks! Make sure compiler folks approve this.

**Comment by DamonFool** [comment]
> I like this, thanks! Make sure compiler folks approve this.

Thanks @shipilev for your review.

May I get one more review from the hotspot compiler team?
Thanks.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by DamonFool** [comment]
Thanks @TobiHartmann for your review.
/integrate

**Pull request closed without merging**
