### PR TITLE
8257509: Strengthen requirements to call G1HeapVerifier::verify(VerifyOption)

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  can I have reviews for this little change to strengthen the requirements for calling G1HeapVerifier::verify(VerifyOption)?

In particular, instead of the failed attempt to abort verification if we are not at a safepoint, assert that we are at a safepoint.

Testing: tier1-5 with no failures

Thanks,
  Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257509](https://bugs.openjdk.java.net/browse/JDK-8257509): Strengthen requirements to call G1HeapVerifier::verify(VerifyOption)

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to 2fba7cc35c50776f54217e753fe1fcd960cc1d6b
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Author) ⚠️ Review applies to 93da0d17cbde2c79a5f46f93957cefa657ef5c67

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1590/head:pull/1590`
`$ git checkout pull/1590`

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good. I would prefer if you remove the blank line between the asserts (line 475) before integrating.

**Review by albertnetymk — APPROVED** [review]
I wonder if it's possible/beneficial to use `assert_at_safepoint_on_vm_thread` to cover two assertions here.

**Comment by tschatzl** [comment]
Changed to use `assert_at_safepoint_on_vm_thread`. Thanks. Good catch!

**Pull request closed without merging**
