### PR TITLE
8269478: Shenandoah: gc/shenandoah/mxbeans tests should be more resilient

### PR DESCRIPTION
**Pull request by shipilev**
After JDK-8259954, some mxbeans tests wait in the effectively infinite loop for the notifications to arrive. If notifications are broken, it would wait forever, and test would timeout. We need to make such failure mode more straightforward.

Additional testing: 
 - [x] Linux x86_64 fastdebug `gc/shenandoah/mxbeans` 
 - [x] Linux x86_64 fastdebug `gc/shenandoah/mxbeans`, `-Xcomp`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269478](https://bugs.openjdk.java.net/browse/JDK-8269478): Shenandoah: gc/shenandoah/mxbeans tests should be more resilient

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4611/head:pull/4611` \
`$ git checkout pull/4611`

Update a local copy of the PR: \
`$ git checkout pull/4611` \
`$ git pull https://git.openjdk.java.net/jdk pull/4611/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4611`

View PR using the GUI difftool: \
`$ git pr show -t 4611`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4611.diff">https://git.openjdk.java.net/jdk/pull/4611.diff</a>

</details>

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good. Thanks!

**Comment by shipilev** [comment]
I have rewritten the tests so that they pass `slowdebug` + `-Xcomp`. Also they are looking at the actual timeout configuration for the test, so users can control how long to wait with usual `timeoutFactor`.

**Comment by shipilev** [comment]
Rewrote the `PauseNotification` test to capture notification counts, not pause times. Mostly because the 1ms resolution is not enough to guarantee non-zero sum of pauses.

**Comment by shipilev** [comment]
@rkennke, @zhengyu123, need another review here, I think.

**Review by rkennke — APPROVED** [review]

**Pull request closed without merging**
