### PR TITLE
8260341: CDS dump VM init code does not check exceptions

### PR DESCRIPTION
**Pull request by iklam**
When CDS dumping is enabled, special initialization happens during VM init. However, many of these calls do not properly check for exception. Instead, they rely on the implicit knowledge that `metaspace::allocate()` will exit the VM when allocation fails during CDS dumping. This makes the code hard to understand and tightly coupled to `metaspace::allocate()`.

The fix is: all code that makes allocation should be using CHECK macros, so each block of code can be individually understood without considering the behavior of `metaspace::allocate()`.

I added `TRAPS` to a bunch of CDS-related functions that are called during VM init. In some cases, I changed `Thread* THREAD` to `TRAPS`. This also eliminated a few `Thread* THREAD = Thread::current()` calls.

The "root" of these calls, such as `MetaspaceShared::prepare_for_dumping()`, now follows this pattern:

```
  EXCEPTION_MARK;
  ClassLoader::initialize_shared_path(THREAD);
  if (HAS_PENDING_EXCEPTION) {
    java_lang_Throwable::print(PENDING_EXCEPTION, tty);
    vm_exit_during_initialization("ClassLoader::initialize_shared_path() failed unexpectedly");
  }
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260341](https://bugs.openjdk.java.net/browse/JDK-8260341): CDS dump VM init code does not check exceptions

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 218af58f9bf89f1ab3e8ad4d05bf17ef3e855a04
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to 218af58f9bf89f1ab3e8ad4d05bf17ef3e855a04

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2494/head:pull/2494`
`$ git checkout pull/2494`

### CODE REVIEW

**Comment by hseigel** [comment]
Hi Ioi,
Do you avoid using CHECK if it's the last line of a function?  For example, why is THREAD used instead of CHECK at line 1506?
Thanks, Harold

1503 void ClassLoader::initialize_module_path(TRAPS) {
1504   if (Arguments::is_dumping_archive()) {
1505     ClassLoaderExt::setup_module_paths(CHECK);
1506     FileMapInfo::allocate_shared_path_table(THREAD);
1507   }
1508 }

**Comment by iklam** [comment]
> Hi Ioi,
> Do you avoid using CHECK if it's the last line of a function? For example, why is THREAD used instead of CHECK at line 1506?
> Thanks, Harold
> 
> 1503 void ClassLoader::initialize_module_path(TRAPS) {
> 1504 if (Arguments::is_dumping_archive()) {
> 1505 ClassLoaderExt::setup_module_paths(CHECK);
> 1506 FileMapInfo::allocate_shared_path_table(THREAD);
> 1507 }
> 1508 }

I thought it was a commonly used coding convention, but I could only find a few cases where the code wasn't written by me :-(

- https://github.com/openjdk/jdk/blame/b9d4211bc1aa92e257ddfe86c7a2b4e4e60598a0/src/hotspot/share/prims/jvm.cpp#L311
- https://github.com/openjdk/jdk/blame/f03e839e481f905358ce7d95a5d1f5179e7f46fe/src/hotspot/share/classfile/javaClasses.cpp#L2415

I will go back to `CHECK`, since the C++ compiler will elide the last `CHECK` anyway: in both cases, gcc compiles the last call to a direct branch to FileMapInfo::allocate_shared_path_table (i.e., a tail call).

Using `CHECK` makes the code easier to maintain (if you add new code below it).

**Review by coleenp — APPROVED** [review]
What Harold said. We use THREAD if the call is the last call in the function because I thought there was a tail call problem with one of the compilers once.  I think this was the bug I was thinking about and it's only in the return statement:
https://bugs.openjdk.java.net/browse/JDK-6889002
If you verified that the HAS_PENDING_EXCEPTION check evaporates, that's fine then, and better to have CHECK.  As you say, someone might add some code after it.

**Review by hseigel — APPROVED** [review]
The changes look good.  Thanks!
Harold

**Comment by iklam** [comment]
> What Harold said. We use THREAD if the call is the last call in the function because I thought there was a tail call problem with one of the compilers once. I think this was the bug I was thinking about and it's only in the return statement:
> https://bugs.openjdk.java.net/browse/JDK-6889002
> If you verified that the HAS_PENDING_EXCEPTION check evaporates, that's fine then, and better to have CHECK. As you say, someone might add some code after it.

I think the problem in JDK-6889002 is only with using `CHECK` in a return statement like this that produces unreachable source code.

```
    return foobar(1, 2, 3, CHECK_0);
```

->

```
    return foobar(1, 2, 3, THREAD);
    if (HAS_PENDING_EXCEPTION) return 0;
```

The cases that I have changed in this PR are functions with `void` returns.

```
void f(TRAPS)  {
    g(1, 2, 3, CHECK);
}
```

would be expanded to

```
void f(TRAPS)  {
    g(1, 2, 3, THREAD);
    if (HAS_PENDING_EXCEPTION) return;
}
```

I suppose any C++ compiler that can compile HotSpot will elide the `if` line.

**Comment by iklam** [comment]
Thanks @hseigel and @coleenp for the review!
/integrate

**Comment by tstuefe** [comment]
Could we then get rid of the special CDS handling in `Metaspace::allocate()`:
https://github.com/openjdk/jdk/blob/837bd8930d0a010110f1318b947c036609d3aa33/src/hotspot/share/memory/metaspace.cpp#L825-L836
?

**Comment by iklam** [comment]
> Could we then get rid of the special CDS handling in `Metaspace::allocate()`:
> https://github.com/openjdk/jdk/blob/837bd8930d0a010110f1318b947c036609d3aa33/src/hotspot/share/memory/metaspace.cpp#L825-L836
> 

I filed https://bugs.openjdk.java.net/browse/JDK-8261551 . We need to fix JDK-8261480 first, since we still have some inappropriate use of THREAD during dumping. I split the work into several steps so that the review can be easier.

**Comment by tstuefe** [comment]
> > Could we then get rid of the special CDS handling in `Metaspace::allocate()`:
> > https://github.com/openjdk/jdk/blob/837bd8930d0a010110f1318b947c036609d3aa33/src/hotspot/share/memory/metaspace.cpp#L825-L836
> 
> I filed https://bugs.openjdk.java.net/browse/JDK-8261551 . We need to fix JDK-8261480 first, since we still have some inappropriate use of THREAD during dumping. I split the work into several steps so that the review can be easier.

Okay, thanks.

**Pull request closed without merging**
