### PR TITLE
8334708: FFM: two javadoc problems

### PR DESCRIPTION
**Pull request by SirYwell**
Addresses two simple problems regarding javadocs in the FFM API.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334708](https://bugs.openjdk.org/browse/JDK-8334708): FFM: two javadoc problems (**Bug** - P4)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19820/head:pull/19820` \
`$ git checkout pull/19820`

Update a local copy of the PR: \
`$ git checkout pull/19820` \
`$ git pull https://git.openjdk.org/jdk.git pull/19820/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19820`

View PR using the GUI difftool: \
`$ git pr show -t 19820`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19820.diff">https://git.openjdk.org/jdk/pull/19820.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19820#issuecomment-2182194383)

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Thanks! Should we backport to 23?

**Comment by SirYwell** [comment]
Thank you for your review.

> Should we backport to 23?

I leave that up to you, I don't know how those things are handled normally. But a backport would be very simple in this case.

**Comment by liach** [comment]
I think we can safely backport this to 23, as this is a doc-only fix (I've labeled the JBS issue noreg-doc as well) allowed by JEP-3 for RDP 1 and 2.

**Comment by mcimadamore** [comment]
Yes, javadoc fixes such as this can be backported. Just use the /backport command:

https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/backport

**Pull request closed without merging**
