### PR TITLE
JDK-8261238: NMT should not limit baselining by size threshold

### PR DESCRIPTION
**Pull request by tstuefe**
NMT is a very useful tool to detect memory leaks. Its easy to use, relatively cheap and requires almost zero setup.

But it artificially limits output to call sites with >1K total memory consumption. That is not helpful, as it confuses the developer and obscures possible memory leaks. It also introduces subtle display errors in that callsites suddenly seem to appear, when comparing to the baseline, with a load of >1K when in fact they had been there already when the baseline was taken.

I propose to remove the 1K limit completely. This will marginally increase the costs of taking "detail" NMT reports by about 210K for a single report, 420K for a report done using a baseline.

If this is really a problem preventing us from getting more precise NMT output (really?) there are possibilities to decrease the cost again by sharing call stacks by reference instead of copying them around. I have a patch in work which does just that (https://bugs.openjdk.java.net/browse/JDK-8261491), but I honestly think adding 200-400K *temporarily* during NMT detail reporting would not be such a big deal.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261238](https://bugs.openjdk.java.net/browse/JDK-8261238): NMT should not limit baselining by size threshold

### Reviewers
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**) ⚠️ Review applies to 8df3f4bc7a04c980765a30e5e84d340b917c7509
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to 8df3f4bc7a04c980765a30e5e84d340b917c7509

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2428/head:pull/2428` \
`$ git checkout pull/2428`

Update a local copy of the PR: \
`$ git checkout pull/2428` \
`$ git pull https://git.openjdk.java.net/jdk pull/2428/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2428`

View PR using the GUI difftool: \
`$ git pr show -t 2428`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2428.diff">https://git.openjdk.java.net/jdk/pull/2428.diff</a>

</details>

### CODE REVIEW

**Review by zhengyu123 — COMMENTED** [review]
The threshold was put in place purely due to memory consumption concerns. 
There was a memory overhead requirement in original document (prior to JEP, Oracle private). If this is no longer a concern, I am good with this change.

**Comment by tstuefe** [comment]
> The threshold was put in place purely due to memory consumption concerns.
> There was a memory overhead requirement in original document (prior to JEP, Oracle private). If this is no longer a concern, I am good with this change.

Great, Zhengyu, thanks!

**Comment by tstuefe** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@openjdk.java.net):_
> 
> On 9/02/2021 2:29 am, Thomas Stuefe wrote:
> 
> > On Mon, 8 Feb 2021 16:03:59 GMT, Zhengyu Gu <zgu at openjdk.org> wrote:
> > > The threshold was put in place purely due to memory consumption concerns.
> > > There was a memory overhead requirement in original document (prior to JEP, Oracle private). If this is no longer a concern, I am good with this change.
> > 
> > 
> > Great, Zhengyu, thanks!
> 
> To know if this is still a concern we know to know what the original
> concern was.
> 
> David

Yes, it would be helpful to know what the initial memory requirements were as well as the considerations behind it. NMT tries to be very slim; which is good, but at various places we trade performance for memory footprint (eg. live with a load factor of 5+ in the malloc site table rather than spending an additional 4-12K to broaden the table). Without knowing these requirements and without deciding if they are still valid improving NMT is difficult.

**Comment by tstuefe** [comment]
I am currently working on a patch which reduces cost of baselining: https://bugs.openjdk.java.net/browse/JDK-8261491 which should be more than enough to mitigate the modest footprint increase of this patch.

So, can we get this patch approved please, unless there are other technical considerations I am not seeing?

**Comment by tstuefe** [comment]
I split out non-controversial display changes into JDK-8262165.

**Comment by tstuefe** [comment]
Gentle Ping.

**Comment by tstuefe** [comment]
Gentle Ping. Could I please have reviews?

**Comment by gerard-ziemski** [comment]
Would it be easier for everyone to accept this change if you introduced a runtime flag to control the threshold size, and left it at 1K by default to match the current behavior?

This way the default behavior does not change, but those who care can tweak it at runtime all the way to 0 to get the use case they want.

**Comment by tstuefe** [comment]
> Would it be easier for everyone to accept this change if you introduced a runtime flag to control the threshold size, and left it at 1K by default to match the current behavior?
> 
> This way the default behavior does not change, but those who care can tweak it at runtime all the way to 0 to get the use case they want.

Not sure. I think the problem may be that no-one beside @zhengyu123 and me knows the code base.

@zhengyu123 what do you think, would you be more amenable toward this patch if it were guarded by an optional "-XX:+PreciseNMTButMoreMemory" switch? (Naming is facetious of course :-)

**Review by TheRealMDoerr — APPROVED** [review]
I'm convinced that Thomas' version is better. Especially after his additional enhancement he has promised (JDK-8261491).
NMT should be able to dectect memory leaks caused by small allocations. So using no threshold should be default IMHO. And I prefer not to add a switch.

**Comment by zhengyu123** [comment]
> > Would it be easier for everyone to accept this change if you introduced a runtime flag to control the threshold size, and left it at 1K by default to match the current behavior?
> > This way the default behavior does not change, but those who care can tweak it at runtime all the way to 0 to get the use case they want.
> 
> Not sure. I think the problem may be that no-one beside @zhengyu123 and me knows the code base.
> 
> @zhengyu123 what do you think, would you be more amenable toward this patch if it were guarded by an optional "-XX:+PreciseNMTButMoreMemory" switch? (Naming is facetious of course :-)

Seems no one raised concerns on memory consumption, I am good.

**Review by zhengyu123 — APPROVED** [review]

**Comment by tstuefe** [comment]
Thanks @TheRealMDoerr  and @zhengyu123 !

I'll wait until tomorrow. If nobody objects, I will merge this change.

**Pull request closed without merging**
