### PR TITLE
8302822: Method/Field/Constructor/RecordComponent::getGenericInfo() is not thread safe

### PR DESCRIPTION
**Pull request by liach**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302822](https://bugs.openjdk.org/browse/JDK-8302822): Method/Field/Constructor/RecordComponent::getGenericInfo() is not thread safe

### Reviewers
 * [Sergey Tsypanov](https://openjdk.org/census#stsypanov) (@stsypanov - Author) ⚠️ Review applies to [f8e05eff](https://git.openjdk.org/jdk/pull/12643/files/f8e05eff5d1022f7221b10c7c72175e5f676db2a)
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to [f8e05eff](https://git.openjdk.org/jdk/pull/12643/files/f8e05eff5d1022f7221b10c7c72175e5f676db2a)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12643/head:pull/12643` \
`$ git checkout pull/12643`

Update a local copy of the PR: \
`$ git checkout pull/12643` \
`$ git pull https://git.openjdk.org/jdk.git pull/12643/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12643`

View PR using the GUI difftool: \
`$ git pr show -t 12643`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12643.diff">https://git.openjdk.org/jdk/pull/12643.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12643#issuecomment-1436063871)

### CODE REVIEW

**Review by stsypanov — APPROVED** [review]

**Review by cl4es — APPROVED** [review]

**Comment by jaikiran** [comment]
Hello @liach, I don't follow what this change is achieving. I think I might be missing something though. I read through the linked JIRA which states:

> In the getGenericInfo() methods of Method, Field, Constructor, and RecordComponent, the genericInfo field is read twice, and the second read returned may be null under race conditions.
Considering the `Constructor` class as an example, which looks like this:

```
@Override
    ConstructorRepository getGenericInfo() {
        // lazily initialize repository if necessary
        if (genericInfo == null) {
            // create and cache generic info repository
            genericInfo =
                ConstructorRepository.make(getSignature(),
                                           getFactory());
        }
        return genericInfo; //return cached repository
    }
```
I can understand that the `ConstructorRepository.make(getSignature(), getFactory());` might end up getting called more than once in case of race (or if ConstructorRepository.make(getSignature(), getFactory()) really returns null), but those should be harmless races. Plus, the getSignature() isn't expensive, since it returns an already assigned `final` field.
Is there some other race condition here?

The JBS issue also states:
> Class::getGenericInfo() originally had the same issue, but was fixed in 8016236.
I had a look at the RFR https://mail.openjdk.org/pipermail/core-libs-dev/2013-June/017798.html. That's a slightly different issue, from what I understand. In that case, the call to getGenericInfo() was being preceded by a call to some other expensive method. The change there proposed to first call getGenericInfo() and let it be initialized and only then decide whether to call the other expensive methods.
In that change, I can see that the `getGenericInfo()` method on the `Class` class was changed too and that change is almost similar to what's being proposed in this current PR. However, `Class.genericInfo` field is `volatile` and I think that's why Doug changed that method to first write it to a local field and then use that local field for the rest of the work. In the current PR however, which touches `Field`, `Method`, `Constructor` and `RecordComponent`, the `genericInfo` isn't a `volatile` field, so I don't see why this local assignment is needed or would help. Am I missing something?

**Comment by cl4es** [comment]
I think of this pattern of reading a to-be-lazily-initialized value into a local as simple hygiene, `volatile` or not. The code might seem solid without it - but stranger things than eliding a field load has happened. Storing into the local variable removes some doubt about how this code will be executed.

**Comment by dholmes-ora** [comment]
The field needs to be volatile for these construction races to be thread-safe, otherwise no guarantee that seeing a non-null genericInfo will mean you see any writes done by the factory methods.

**Comment by liach** [comment]
We don't fear calling the factory twice for benign races, as the distinct constructor factory instances are behaviorally the same.

The true issue lies in the double getfield operations: Java memory model doesn't require the second read to happen-after a write reflected in the first read, so return this.genericInfo may return null while this.genericInfo == null evaluates to false, in case genericInfo is initialized lazily by another thread. See https://bugs.openjdk.org/browse/JDK-8261404

**Comment by plevart** [comment]
Hi @liach,

I think @dholmes-ora is worried about the fields in the object being returned by the getGenericInfo() method and similar. In above case this means fields in class ConstructorRepository.
I checked it and the entire hierarchy based on sun.reflect.generics.repository.AbstractRepository with subclasses including ConstructorRepository is modeled such that all fields are either:
- volatile and lazily initialized; or
- final and initialized in constructor

Such objects may be published via data race and still be seen consistent on the accepting side.

**Comment by dholmes-ora** [comment]
Thanks @plevart  that was exactly my concern but I didn't have time to check whether the returned object could be safely published regardless of any race condition. Is it specified that way, or just a fortuitous occurrence?

I would also be concerned about the guarantee of idempotency from the factory method - I hope its requirements in that area are clearly documented.

**Comment by AlanBateman** [comment]
> I would also be concerned about the guarantee of idempotency from the factory method - I hope its requirements in that area are clearly documented.

The spec for the getGenericXXX methods are "Return a" rather than "Return the" so there shouldn't be any expectation on identity. The question about idempotency might be worth checking into as the underlying factory for reflective generic type objects does interact with the defining class loader.

**Comment by liach** [comment]
I've updated the fields to be volatile.

> > I would also be concerned about the guarantee of idempotency from the factory method - I hope its requirements in that area are clearly documented.
> 
> The spec for the getGenericXXX methods are "Return a" rather than "Return the" so there shouldn't be any expectation on identity. The question about idempotency might be worth checking into as the underlying factory for reflective generic type objects does interact with the defining class loader.

These objects should always be resolving types with the class loader of the declaring class in [CoreReflectionsFctory::getDeclsLoader](https://github.com/openjdk/jdk/blob/065d3e0d58c96b8a84f3c02bb8704fab6459eaa7/src/java.base/share/classes/sun/reflect/generics/factory/CoreReflectionFactory.java#L61), so the resolved Class instances should be always the same. As far as I see, Type instances are otherwise compared by equals instead of identity, so returning distinct but equal type instances should be safe.

**Comment by liach** [comment]
keep-alive. Using volatile to ensure correctness of program order is still better than reading `null` on the second non-volatile read at return.

**Pull request closed without merging**
