### PR TITLE
8338286: GHA: Demote x86_32 to hotspot build only

### PR DESCRIPTION
**Pull request by shipilev**
As planned in [JDK-8338285](https://bugs.openjdk.org/browse/JDK-8338285), we are about to deprecate the port for removal. It makes little sense to continue testing the port, and thus block development and integration of new features.

Ahead of that JEP, we can separately decide to disable the x86_32 test jobs in GHA. This effectively demotes x86_32 to any other port that only builds Hotspot and relies on port maintainers to provide the runtime testing. Building hotspot in both release and debug modes still gives us some level of 32-bit cleanliness checks.

This is deliberately separate change, so that Update Releases could decide to demote their x86_32 jobs as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338286](https://bugs.openjdk.org/browse/JDK-8338286): GHA: Demote x86_32 to hotspot build only (**Enhancement** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20563/head:pull/20563` \
`$ git checkout pull/20563`

Update a local copy of the PR: \
`$ git checkout pull/20563` \
`$ git pull https://git.openjdk.org/jdk.git pull/20563/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20563`

View PR using the GUI difftool: \
`$ git pr show -t 20563`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20563.diff">https://git.openjdk.org/jdk/pull/20563.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20563#issuecomment-2285819587)

### CODE REVIEW

**Review by magicus — APPROVED** [review]
This sounds reasonable. The implementation seems correct.

**Comment by gdams** [comment]
This is great to see! thanks for pushing it through @shipilev. I wonder if it's time for me to reboot my PR about testing Alpine Linux if we're dropping back on the actions usage here: https://github.com/openjdk/jdk/pull/7771

**Comment by shipilev** [comment]
Thanks! Any other opinions on this?

**Comment by shipilev** [comment]
By the powers vested in me as x86_32 maintainer I declare this PR integrateable. :)

/integrate

**Comment by TheShermanTanker** [comment]
Sad to see a port start to go, but it had to be done, You were good, x86\_32 port :)

**Pull request closed without merging**
