### PR TITLE
JDK-8280019: Remove unused code from metaspace

### PR DESCRIPTION
**Pull request by tstuefe**
Sonarcloud-inspired code grooming. Trivial removal of unused code in metaspace.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280019](https://bugs.openjdk.java.net/browse/JDK-8280019): Remove unused code from metaspace

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to a69dd0ebad1ccb9657fe656197ecc6642fa657c7
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to a69dd0ebad1ccb9657fe656197ecc6642fa657c7

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7085/head:pull/7085` \
`$ git checkout pull/7085`

Update a local copy of the PR: \
`$ git checkout pull/7085` \
`$ git pull https://git.openjdk.java.net/jdk pull/7085/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7085`

View PR using the GUI difftool: \
`$ git pr show -t 7085`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7085.diff">https://git.openjdk.java.net/jdk/pull/7085.diff</a>

</details>

### CODE REVIEW

**Comment by hseigel** [comment]
Change looks good but was any testing done for this change?
Thanks, Harold

**Review by coleenp — APPROVED** [review]
Great! Looks trivial.

**Comment by tstuefe** [comment]
> Change looks good but was any testing done for this change? Thanks, Harold

Hi Harold,

well, I manually built several configurations (x64, x86, release, fastdebug) and ran gtests. Beyond that, I would not have thought tests to be necessary since the removed coding was never used.

I also know this coding quite well since all I added it for JEP 387, so I am confident nothing vital was cut.

In GHAs, I see one failure on x86 where we crash in jdk/javadoc/doclet/testLinkPlatform/TestLinkPlatform.java 
 with "Overflow during reference processing", but that is unrelated to my change and also happens to others, see e.g. https://github.com/openjdk/jdk/pull/7059.

Thanks, Thomas

**Comment by hseigel** [comment]
Hi Thomas,
Your testing is more than sufficient.  Thanks for doing this.
Harold

**Review by hseigel — APPROVED** [review]
LGTM

**Pull request closed without merging**
