### PR TITLE
8282716: [macos] Enable javax/swing/JScrollPane/TestMouseWheelScroll.java on macos

### PR DESCRIPTION
**Pull request by prsadhuk**
The test was failing on macos and was excluded in macos because the viewposition was not changed after mouse wheel scroll. Seems like mouse wheel scroll direction is opposite in macos compared to windows etc so if we try to down-wheel scroll in macos when view position is at center of viewport (say element 3 is selected out of visible 7 elements), it cannot change viewposition as it cannot "scroll up" (since we are already at topmost viewport) whereas in windows, when we do down-wheel scroll in mouse wheel, it "scroll down" the viewport so viewposition is changed.

Fix is to use opposite scrolling motion in macos to check mouse wheel scroll is happening, which is what the testcase is meant for. CI testing of this test on all platform is ok.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282716](https://bugs.openjdk.java.net/browse/JDK-8282716): [macos] Enable javax/swing/JScrollPane/TestMouseWheelScroll.java on macos

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8123/head:pull/8123` \
`$ git checkout pull/8123`

Update a local copy of the PR: \
`$ git checkout pull/8123` \
`$ git pull https://git.openjdk.java.net/jdk pull/8123/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8123`

View PR using the GUI difftool: \
`$ git pr show -t 8123`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8123.diff">https://git.openjdk.java.net/jdk/pull/8123.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
The scroll direction on macOS can be configured, can the test check what type of scroll is used on the current system and then use that to verify the old fix?

**Comment by prsadhuk** [comment]
> The scroll direction on macOS can be configured, can the test check what type of scroll is used on the current system and then use that to verify the old fix?

I see "Scroll direction: Natural" check in mouse in SystemPreference which is by default checked, 
which causes down-wheel scroll to "move up" and up-wheel scroll to "move down" and if unchecked, then it causes reverse.
But I could not find anyway to find in Java in Robot how to get scroll type of macos or for other platforms. 
If you are aware, let me know..
I guess we always test with default settings..

**Comment by prsadhuk** [comment]
> > The scroll direction on macOS can be configured, can the test check what type of scroll is used on the current system and then use that to verify the old fix?
> 
> I see "Scroll direction: Natural" check in mouse in SystemPreference which is by default checked, which causes down-wheel scroll to "move up" and up-wheel scroll to "move down" and if unchecked, then it causes reverse. But I could not find anyway to find in Java in Robot how to get scroll type of macos or for other platforms. If you are aware, let me know.. I guess we always test with default settings..

I have updated test to check wheel scroll type at runtime

**Comment by prsadhuk** [comment]
Any more comments @mrserb ?

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
