### PR TITLE
8281322: C2: always construct strip mined loop initially (even if strip mining is disabled)

### PR DESCRIPTION
**Pull request by rwestrel**
Some of the long range check transformations take advantage of the
safepoint captured by loop strip mining to extract jvm state (in order
to add back empty predicates to the inner loop of a loop nest). As a
consequence, irTests/TestLongRangeChecks.java fails with strip mining
off and users might experience performance anomalies where changing
GCs affect purely computational code.

The strip mined loop nest creation is a 2 step process:

1- when a CountedLoop is created, an OuterStripMinedLoop is also added
  but it's not fully constructed

2- at macro expansion time, the OuterStripMinedLoop is turned into an
  actual loop by adding Phis and a proper exit condition

I propose always doing 1- whether loop strip mining is enabled or
not. This causes the safepoint to always be captured. Loop strip ming
is not expected to get in the way of loop transformations so this
change in itself should be performance neutral. Then at 2-, if loop
strip mining is not enabled, the OuterStripMinedLoop can be removed
and the safepoint moved back into the loop in case
LoopStripMiningIter=1 or simply removed too.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281322](https://bugs.openjdk.java.net/browse/JDK-8281322): C2: always construct strip mined loop initially (even if strip mining is disabled)

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to 62d8d87553097e273d7cd197cc53aa3dd50903eb

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7364/head:pull/7364` \
`$ git checkout pull/7364`

Update a local copy of the PR: \
`$ git checkout pull/7364` \
`$ git pull https://git.openjdk.java.net/jdk pull/7364/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7364`

View PR using the GUI difftool: \
`$ git pr show -t 7364`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7364.diff">https://git.openjdk.java.net/jdk/pull/7364.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
That looks reasonable. I'll submit some testing.

**Comment by TobiHartmann** [comment]
For the record: Christian's testing found issues (he reported them to Roland already).

I think it would be good to change the bug title to something more descriptive.

**Comment by rwestrel** [comment]
> For the record: Christian's testing found issues (he reported them to Roland already).

8282045 (When loop strip mining fails, safepoints are removed from loop anyway) is an underlying issue that Christian's testing caught.

**Comment by rwestrel** [comment]
I pushed a number of new commits that address 3 issues (with LoopStripMiningIter=1):
1- the previous logic would drop nodes pinned on the backedge when the loop nest is transformed back to a single loop.
2- sunk stores need to be moved back into the loop which requires the inner loop's memory graph to be updated. I reused existing logic for that (OuterStripMinedLoopNode::fix_sunk_stores())
3- long counted loop support has a similar transform from a loop nest back to a single counted loop. That transform didn't have part 2 above. I'm not sure if it can cause actually bugs as I expect the counted loop to be transformed back to a loop nest next. In any case, rather than duplicate the logic, I refactored the code so it calls the new OuterStripMinedLoopNode::transform_to_counted_loop() instead. Having it callable from both igvn and loop opts requires some care.

**Review by TobiHartmann — APPROVED** [review]
This looks reasonable to me. All tests passed.

**Review by chhagedorn — APPROVED** [review]
Apart from some minor code style things, the update looks good to me!

**Comment by rwestrel** [comment]
> Apart from some minor code style things, the update looks good to me!

Thanks. The new commit should take care of your comments.

**Review by chhagedorn — APPROVED** [review]
Thanks for the updates, looks good!

**Comment by rwestrel** [comment]
@TobiHartmann @chhagedorn thanks for the reviews

**Pull request closed without merging**
