### PR TITLE
8317246: Cleanup java.net.URLEncoder and URLDecoder use of file.encoding property

### PR DESCRIPTION
**Pull request by Glavo**
`DEFAULT_ENCODING_NAME ` in `URLEncoder` and `URLDecoder` can be replaced with `Charset.defaultCharset()`, which removes unnecessary static fields and avoid looking up charset when calling `URLDecoder.decode(String)` and `URLEncoder.encode(String)`.

This PR is trivial, since `Charset.defaultCharset()` is also initialized with `StaticProperty.fileEncoding()`, this causes no change in behavior. 

Moreover, the javadoc of `URLDecoder.decode(String)` and `URLEncoder.encode(String)` say that they use the default charset, so this change is semantically consistent with the documentation.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317246](https://bugs.openjdk.org/browse/JDK-8317246): Cleanup java.net.URLEncoder and URLDecoder use of file.encoding property (**Enhancement** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15353/head:pull/15353` \
`$ git checkout pull/15353`

Update a local copy of the PR: \
`$ git checkout pull/15353` \
`$ git pull https://git.openjdk.org/jdk.git pull/15353/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15353`

View PR using the GUI difftool: \
`$ git pr show -t 15353`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15353.diff">https://git.openjdk.org/jdk/pull/15353.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15353#issuecomment-1739796863)

### CODE REVIEW

**Comment by cl4es** [comment]
I'm not sure this is advisable. The `StaticProperty.fileEncoding()` value is fixed during startup to the platform native encoding and can't be overridden like `defaultCharset()` so I think this will have subtle compatibility implications. What gain - if any - do you see from this?

**Comment by Glavo** [comment]
I want to make changes to `Charset` like below in another PR:

```java
public abstract class Charset {
  // ...
  private static class DefaultCharsetHolder {
    static final Charset defaultCharset;
    static {
      Charset cs = lookup(StaticProperty.fileEncoding())
      if (cs != null)
        defaultCharset = cs;
      else
        defaultCharset = sun.nio.cs.UTF_8.INSTANCE;
    }
  }

  public static Charset defaultCharset() {
    return DefaultCharsetHolder.defaultCharset;
  }
  //...
}
```

Perhaps I should discuss this change first before considering this PR?

**Comment by Glavo** [comment]
@cl4es I found that the `defaultCharset` is already initialized using `StaticProperty.fileEncoding()`, so this PR is a secure change.

**Comment by cl4es** [comment]
There are mysterious interactions with `-Dfile.encoding=COMPAT` and `native.encoding` that I don't fully understand, but it does seem odd that `URLDecoder/-Encoder` rely directly on the `StaticProperty.fileEncoding()` string. I'll have to defer to @RogerRiggs and @AlanBateman if changing to `Charset.defaultCharset()` is appropriate or not.

**Comment by AlanBateman** [comment]
> There are mysterious interactions with `-Dfile.encoding=COMPAT` and `native.encoding` that I don't fully understand, but it does seem odd that `URLDecoder/-Encoder` rely directly on the `StaticProperty.fileEncoding()` string. I'll have to defer to @RogerRiggs and @AlanBateman if changing to `Charset.defaultCharset()` is appropriate or not.

The deprecated encode/decode methods are specified to use the default charset.  The motivation for the change in the PR is vague.

**Comment by cl4es** [comment]
Right, this only affects deprecated methods, so it's unclear who'd benefit. A little less code and a couple of constants less is nice, I guess.

**Comment by Glavo** [comment]
I'm just hoping to clean up the redundant code with this PR.

Additionally, by searching on GitHub, I found that there appear to be some use cases for this method (although most may be misused). This PR can also slightly optimize these use cases.

**Comment by RogerRiggs** [comment]
BTW, the PR description is quite lacking. It should explain the issue and benefit without having to go read the code.
Write the description with details that would be in the issue.

**Comment by Glavo** [comment]
Can someone help create a issue on JBS?

**Comment by RogerRiggs** [comment]
Created, note change in title.
[8317246](https://bugs.openjdk.org/browse/JDK-8317246) Cleanup java.net.URLEncoder and URLDecoder use of file.encoding property

**Comment by dfuch** [comment]
This looks reasonable. Have you run tier2?

**Comment by Glavo** [comment]
> This looks reasonable. Have you run tier2?

Yes. Almost all tests passed except for one seemingly unrelated (`ThreadCountLimit`).

**Review by naotoj — APPROVED** [review]

**Comment by Glavo** [comment]
Can anyone sponsor this PR?

**Comment by dfuch** [comment]
I ran tests in our CI and observed no failures linked to this PR - I would have sponsored today but @cl4es beat me to it :-)

**Pull request closed without merging**
