### PR TITLE
JDK-8321975: Print when add_reserved_region fails even in product mode

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

We recently had a user e-mail hotspot-dev about a JVM crash which hit `ShouldNotReachHere` in `add_reserved_region`. As the logging is disabled in product builds the user couldn't supply us with all of the available information, quite unfortunate for us. I propose that we print the region information unconditionally and print the stacks also.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321975](https://bugs.openjdk.org/browse/JDK-8321975): Print when add_reserved_region fails even in product mode (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17086/head:pull/17086` \
`$ git checkout pull/17086`

Update a local copy of the PR: \
`$ git checkout pull/17086` \
`$ git pull https://git.openjdk.org/jdk.git pull/17086/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17086`

View PR using the GUI difftool: \
`$ git pr show -t 17086`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17086.diff">https://git.openjdk.org/jdk/pull/17086.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17086#issuecomment-1853983865)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable as long as all the associated `print_on` logic is available in product builds too.

Thanks

**Review by tstuefe — APPROVED** [review]
+1

good to push. I would like it if the printing were contained in something like VirtualMemoryRegion::print_on().

**Comment by jdksjolen** [comment]
Thank you!

/integrate

**Pull request closed without merging**
