### PR TITLE
8264331: Use the blessed modifier order in jdk.compiler

### PR DESCRIPTION
**Pull request by alblue**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264331](https://bugs.openjdk.java.net/browse/JDK-8264331): Use the blessed modifier order in jdk.compiler

### Reviewers
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3235/head:pull/3235` \
`$ git checkout pull/3235`

Update a local copy of the PR: \
`$ git checkout pull/3235` \
`$ git pull https://git.openjdk.java.net/jdk pull/3235/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3235`

View PR using the GUI difftool: \
`$ git pr show -t 3235`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3235.diff">https://git.openjdk.java.net/jdk/pull/3235.diff</a>

</details>

### CODE REVIEW

**Comment by alblue** [comment]
Would anyone mind reviewing this change, please? It swaps the order of "final static" for "static final" across a bunch of files.

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Review by irisclark — APPROVED** [review]

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
