### PR TITLE
8283929: GHA: Add RISC-V build config

### PR DESCRIPTION
**Pull request by luhenry**
It adds CI for cross-compiling to linux-riscv64. It requires to use Ubuntu repositories for the debootstrap image because Debian doesn't have riscv64 packages on https://httpredir.debian.org/debian/. We can follow up on this change with switching to http://ports.ubuntu.com/ubuntu-ports for all cross-compiled architectures.

This change also does not require nor blocks switching to Ubuntu 22.04.

From talking with @shipilev, this replaces https://github.com/openjdk/jdk/pull/10086.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283929](https://bugs.openjdk.org/browse/JDK-8283929): GHA: Add RISC-V build config

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10168/head:pull/10168` \
`$ git checkout pull/10168`

Update a local copy of the PR: \
`$ git checkout pull/10168` \
`$ git pull https://git.openjdk.org/jdk pull/10168/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10168`

View PR using the GUI difftool: \
`$ git pr show -t 10168`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10168.diff">https://git.openjdk.org/jdk/pull/10168.diff</a>

</details>

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Looks good.

(Also: what! Ubuntu has better platform support than Debian?!?)

**Comment by VladimirKempik** [comment]
Finally we will have at least build test for risc-v, thanks @luhenry

**Comment by luhenry** [comment]
> (Also: what! Ubuntu has better platform support than Debian?!?)

I'm exploring using Debian ports repository, but it's not as straightforward as I expected.
https://github.com/rivosinc/jdk/compare/dev/ludovic/ci-cross-compile-riscv64...rivosinc:jdk:dev/ludovic/ci-cross-compile-riscv64-2

> are you going to backport this to jdk19u ?

I definitely would like it, yes.

**Comment by luhenry** [comment]
I got it working with using the Debian repositories instead of Ubuntu's.

**Review by magicus — APPROVED** [review]

**Review by shipilev — APPROVED** [review]
Looks good to me, thanks.

**Pull request closed without merging**
