### PR TITLE
8334180: NMT gtests introduced with 8312132 should be labeled as NMT

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

This PR prepends NMT to all recently introduced NMT-related tests, so that they're easy to run as one unit.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334180](https://bugs.openjdk.org/browse/JDK-8334180): NMT gtests introduced with 8312132 should be labeled as NMT (**Enhancement** - P4)

### Reviewers
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - Committer)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19688/head:pull/19688` \
`$ git checkout pull/19688`

Update a local copy of the PR: \
`$ git checkout pull/19688` \
`$ git pull https://git.openjdk.org/jdk.git pull/19688/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19688`

View PR using the GUI difftool: \
`$ git pr show -t 19688`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19688.diff">https://git.openjdk.org/jdk/pull/19688.diff</a>

</details>

### CODE REVIEW

**Comment by jdksjolen** [comment]
```#  assert(maximum_depth_found - expected_maximum_depth <= 3) failed: depth unexpectedly large for treap of node count 5000000, was: 62, expected between 53 and 56```

Oh wow, it actually failed on this!

**Comment by jdksjolen** [comment]
Ping @gerard-ziemski, @afshin-zafari, @tstuefe 

May I have a review for this?

**Review by gerard-ziemski — APPROVED** [review]
LGTM

Just one question, what's the issue with the pre-submit tests?

**Review by tstuefe — APPROVED** [review]
Good. I would like the hs tier1 common tests be green before pushing, though. These contain the gtests.

**Comment by jdksjolen** [comment]
> LGTM
> 
> Just one question, what's the issue with the pre-submit tests?

It seems that we're experiencing *slightly* worse behavior on the treap than expected sometimes. We expect depth to be at most `2.5 * log_2(n)` where `n` is number of nodes. With a depth of `62` we're experiencing a slightly worse factor of `2.8`. As a treap is sensitive to the quality of the random number generation, it must be that it sometimes receives a slightly worse seed number. This seed number depends on the ordering of random operations between the threads in the VM. The choice of RNG and seed is the critical part of making a Treap perform well.

**Comment by tstuefe** [comment]
> > > LGTM
> > > Just one question, what's the issue with the pre-submit tests?
> > 
> > 
> > It seems that we're experiencing _slightly_ worse behavior on the treap than expected sometimes. We expect depth to be at most `2.5 * log_2(n)` where `n` is number of nodes. With a depth of `62` we're experiencing a slightly worse factor of `2.8`. As a treap is sensitive to the quality of the random number generation, it must be that it sometimes receives a slightly worse seed number. This seed number depends on the ordering of random operations between the threads in the VM. The choice of RNG and seed is the critical part of making a Treap perform well.
> 
> Okay. But why and since when did these start failing? AFAICS they don't fail in my PRs.

Ah, wait, okay. We now execute them more often. But still, we should have seen failures like that before.

**Comment by jdksjolen** [comment]
/integrate

Thanks for the reviews

**Pull request closed without merging**
