### PR TITLE
8294920: Missing SP value in Linux x86_32 thread context

### PR DESCRIPTION
**Pull request by shipilev**
See the description in the bug. This fixes only Linux x86_32, because only there I could reproduce the failure. Windows x86_32 seems to be fine. I have no access to BSD x86_32.

Additional testing:
 - [x] Linux x86 fastdebug `serviceability/sa` now cleanly passes

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294920](https://bugs.openjdk.org/browse/JDK-8294920): Missing SP value in Linux x86_32 thread context

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10598/head:pull/10598` \
`$ git checkout pull/10598`

Update a local copy of the PR: \
`$ git checkout pull/10598` \
`$ git pull https://git.openjdk.org/jdk pull/10598/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10598`

View PR using the GUI difftool: \
`$ git pr show -t 10598`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10598.diff">https://git.openjdk.org/jdk/pull/10598.diff</a>

</details>

### CODE REVIEW

**Comment by plummercj** [comment]
[JDK-8208091](https://bugs.openjdk.org/browse/JDK-8208091) also addressed windows-x86. Any reason not to do the same here? I see bsd-x86 was neglected for [JDK-8208091](https://bugs.openjdk.org/browse/JDK-8208091). Would have been nice if it hadn't been just to keep the ports consistent, although I'm not sure if anyone cares about bsd-x86.

**Comment by shipilev** [comment]
> [JDK-8208091](https://bugs.openjdk.org/browse/JDK-8208091) also addressed windows-x86. Any reason not to do the same here? I see bsd-x86 was neglected for [JDK-8208091](https://bugs.openjdk.org/browse/JDK-8208091). Would have been nice if it hadn't been just to keep the ports consistent, although I'm not sure if anyone cares about bsd-x86.

I tested Windows x86_32, and the test passes there without this fix. I think this is Linux-specific, given how ESP/UESP split exists there? So, I opted to fix only the actual bugs that I was able to reproduce.

**Review by plummercj — APPROVED** [review]
Please update the copyright before integrating.

**Review by sspitsyn — APPROVED** [review]

**Review by plummercj — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks! I am integrating to hopefully get cleaner weekend test runs.

/integrate

**Pull request closed without merging**
