### PR TITLE
8264565: Templatize num_arguments() functions of DCmd subclasses

### PR DESCRIPTION
**Pull request by iklam**
We have many version of `num_arguments()` for the `DCmd` subclasses. They all have identical structure. We should templatize them to reduce duplicated code and avoid cut-and-paste errors.

It's still possible to write a customized `num_arguments()` function (although none of the existing cases needs to do that). The rules are described here:

```
class DCmd : public ResourceObj {
  ...
  // num_arguments() is used by the DCmdFactoryImpl::get_num_arguments() template functions.
  // - For subclasses of DCmdWithParser, it's calculated by DCmdParser::num_arguments().
  // - Other subclasses of DCmd have zero arguments by default. You can change this
  //   by defining your own version of MyDCmd::num_arguments().
  static int num_arguments()        { return 0; }

```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264565](https://bugs.openjdk.java.net/browse/JDK-8264565): Templatize num_arguments() functions of DCmd subclasses

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to ec38f55eb664c9ee3ba063987b7fba1576892570
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to ec38f55eb664c9ee3ba063987b7fba1576892570

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3312/head:pull/3312` \
`$ git checkout pull/3312`

Update a local copy of the PR: \
`$ git checkout pull/3312` \
`$ git pull https://git.openjdk.java.net/jdk pull/3312/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3312`

View PR using the GUI difftool: \
`$ git pr show -t 3312`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3312.diff">https://git.openjdk.java.net/jdk/pull/3312.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
For verification, I added code in an earlier commit (hence removed) to print out the `num_arguments()` of each `DCmd`. The results are identical with and without this patch.

https://github.com/openjdk/jdk/blob/25920cdd8296901bcd64d5cf277a616bc90bea90/src/hotspot/share/services/diagnosticFramework.cpp#L521-L523

**Review by coleenp — APPROVED** [review]
Wow cool and nice.

**Review by dholmes-ora — APPROVED** [review]
Looks like a good cleanup!

Thanks,
David

**Comment by iklam** [comment]
Thanks @coleenp and @dholmes-ora for the review.
/integrate

**Pull request closed without merging**
