### PR TITLE
8256379: Replace SIZE_FORMAT with 'z' length modifier

### PR DESCRIPTION
**Pull request by coleenp**
Replace SIZE_FORMAT with %zu and SIZE_FORMAT_X with 0x%zx using a 4 line sed script:

  sed -e 's/" SIZE_FORMAT "/%zu/g' -e 's/" SIZE_FORMAT,/%zu",/' \
      -e 's/print(SIZE_FORMAT "/print("%zu/g' \
      -e 's/" SIZE_FORMAT_X "/0x%zx/g' -e 's/" SIZE_FORMAT_X,/0x%zx",/g' \
      -e 's/" SIZE_FORMAT$/%zu"/' \
       $f >$f.new

Minor fixups afterwards.  I didn't change SIZE_FORMAT_W(number) because it would have required a better sed script.

The definitions in globalDefinitions.hpp can be removed with a later PR, once all instances are cleaned out.  This is partial so that people start using %zu instead.

Tested with tier1 on Oracle supported platforms.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8256379](https://bugs.openjdk.org/browse/JDK-8256379): Replace SIZE_FORMAT with 'z' length modifier (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15115/head:pull/15115` \
`$ git checkout pull/15115`

Update a local copy of the PR: \
`$ git checkout pull/15115` \
`$ git pull https://git.openjdk.org/jdk.git pull/15115/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15115`

View PR using the GUI difftool: \
`$ git pr show -t 15115`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15115.diff">https://git.openjdk.org/jdk/pull/15115.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15115#issuecomment-1663124447)

### CODE REVIEW

**Comment by coleenp** [comment]
Do we want this?

**Comment by tstuefe** [comment]
> Do we want this?

It won't surprise you that I'm not a fan. This will cause many otherwise painless backports across this commit not to be cleanly mergeable.

I'm warming to the %z notion, provided all our compilers can do that. But my vote would be for doing this when writing new code or changing code.

**Comment by gnu-andrew** [comment]
I actually agree with using `%z` for this, but this seems an unusual way to approach it. The `SIZE_FORMAT` is an abstraction which allows the actual format specifier to be anything defined in `globalDefinitions.hpp`. Removing it to hardcode a format thus seems like a bit of a backward step to me.

I've actually had a patch hanging around for the best part of a decade that uses `%z` as the format specifier, but only on s390 (31-bit). As you may know, `size_t` and `int` aren't interchangeable on s390, which used to throw up all sorts of errors with the casts in HotSpot. On that platform, it really is necessary to use `%z` for the size format.

The patch pretty much got dropped on the floor as we didn't build on s390 on newer JDKs and obviously we'd need to start there to get it upstream and then backport. The actual patch was pretty simple though:

~~~
diff --git openjdk.orig/hotspot/src/share/vm/utilities/globalDefinitions.hpp openjdk/hotspot/src/share/vm/utilities/globalDefinitions.hpp
--- openjdk.orig/hotspot/src/share/vm/utilities/globalDefinitions.hpp
+++ openjdk/hotspot/src/share/vm/utilities/globalDefinitions.hpp
@@ -1389,12 +1389,21 @@
 
 #define INTPTR_FORMAT_W(width)   "%" #width PRIxPTR
 
+#if defined(S390) && !defined(_LP64)
+#define SSIZE_FORMAT          "%z"   PRIdPTR
+#define SIZE_FORMAT           "%z"   PRIuPTR
+#define SIZE_FORMAT_HEX       "0x%z" PRIxPTR
+#define SSIZE_FORMAT_W(width) "%"   #width "z" PRIdPTR
+#define SIZE_FORMAT_W(width)  "%"   #width "z" PRIuPTR
+#define SIZE_FORMAT_HEX_W(width) "0x%" #width "z" PRIxPTR
+#else   // !S390
 #define SSIZE_FORMAT          "%"   PRIdPTR
 #define SIZE_FORMAT           "%"   PRIuPTR
 #define SIZE_FORMAT_HEX       "0x%" PRIxPTR
 #define SSIZE_FORMAT_W(width) "%"   #width PRIdPTR
 #define SIZE_FORMAT_W(width)  "%"   #width PRIuPTR
 #define SIZE_FORMAT_HEX_W(width) "0x%" #width PRIxPTR
+#endif  // S390
 
 #define INTX_FORMAT           "%" PRIdPTR
 #define UINTX_FORMAT          "%" PRIuPTR
~~~

plus a bunch of cases where the wrong format was being used in the `printf` statements (likely resolved now anyway; this was against 8u)

I think you could do something similar and include backwards compatibility by detecting whether `%z` is usable during `configure` and then adding a similar `#ifdef` but based on something defined by `configure`.

I'd be happy to propose something if you don't already have an alternate solution in the works.

**Comment by dholmes-ora** [comment]
> Removing it to hardcode a format thus seems like a bit of a backward step to me.

But we only defined abstract things like `SIZE_FORMAT` because there was no single specifier accepted by all C runtimes and which behaves in the same (or similar enough) way. Once we have use of `%zu` or %zd`  available everywhere then we no longer need the abstraction.

**Pull request closed without merging**
