### PR TITLE
JDK-8272703: StressSeed should be set via FLAG_SET_ERGO

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Set the `StressSeed` (added by JDK-8252219) via `FLAG_SET_ERGO` if the seed is generated by the VM (i.e., not set via the command line). This way, `StressSeed` will be added to the "[Global flags]" section of the hs_err file on crash and can be used to reproduce the issue.

If `RepeatCompilation` is on and no `StressSeed` is set, a new `StressSeed` is generated for every compilation. The reason for this is that some Bugs are only triggered intermittent, because they depend on the `StressSeed`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272703](https://bugs.openjdk.java.net/browse/JDK-8272703): StressSeed should be set via FLAG_SET_ERGO

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5599/head:pull/5599` \
`$ git checkout pull/5599`

Update a local copy of the PR: \
`$ git checkout pull/5599` \
`$ git pull https://git.openjdk.java.net/jdk pull/5599/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5599`

View PR using the GUI difftool: \
`$ git pr show -t 5599`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5599.diff">https://git.openjdk.java.net/jdk/pull/5599.diff</a>

</details>

### CODE REVIEW

**Comment by tobiasholenstein** [comment]
> That looks good to me. I think it's valuable to still generate new seeds when running with `RepeatCompilation` which helped quite a lot to reproduce bugs in the past which were otherwise hard to trigger.

Thanks! @chhagedorn

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
