### PR TITLE
8331348: Some incremental builds deposit files in the make directory

### PR DESCRIPTION
**Pull request by nizarbenalla**
Please review this small change. Passes tier 1-3.

In case of fatal errors or if a hidden option is passed to the compiler, a report with the parameters passed to it is printed to a file in the `@-file` format, this makes it easier for us to reproduce the bug. And for users submitting bug reports.
Some of these files were being deposited in the current directory during OpenJDK builds, now they are moved to the temp dir.
Writing to the console only is not an option because of the large number of arguments that can be passed to the compiler.
By convention, a number of arguments is printed to the console if an error occurs while writing to the file.
Some also suggested adding a message as to why this file exist.

TIA

I see the bot is complaining due to the fix version but I think it can be changed, if this is approved.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331348](https://bugs.openjdk.org/browse/JDK-8331348): Some incremental builds deposit files in the make directory (**Bug** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19338/head:pull/19338` \
`$ git checkout pull/19338`

Update a local copy of the PR: \
`$ git checkout pull/19338` \
`$ git pull https://git.openjdk.org/jdk.git pull/19338/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19338`

View PR using the GUI difftool: \
`$ git pr show -t 19338`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19338.diff">https://git.openjdk.org/jdk/pull/19338.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19338#issuecomment-2123721304)

### CODE REVIEW

**Comment by magicus** [comment]
Please close one of the bug issues as a dup rather than adding an additional issue here, thanks.

**Comment by magicus** [comment]
As far as I am aware, we do not set `java.io.tmpdir` in the build system. What will it default to? Have you verified that this actually solves the problem?

**Comment by nizarbenalla** [comment]
I think the property `java.io.tmpdir ` is set to an appropriate value in all JVMs, so it would always find a directory.

**Review by magicus — APPROVED** [review]
Looks good to me, but let's also hear what @jonathan-gibbons has to say.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm, but yes I think that we should double check where the file is written to during builds

**Comment by lahodaj** [comment]
FWIW, I don't have a strong opinion on where the diagnostic file should be written. But it would be good to investigate why javac crashes, and fix that, not only move the files.

**Comment by magicus** [comment]
@lahodaj Absolutely! But that is a completely separate issue from this, that deals with how javac spews log files all around itself...

**Comment by magicus** [comment]
I have created a complement to this bug in [JDK-8332808](https://bugs.openjdk.org/browse/JDK-8332808). There I will make sure that `java.io.tmpdir` is set to point to a suitable place inside the build output directory. These two fixes in tandem will provide a good solution to this, I think.

@vicente-romero-oracle I think this will serve as an answer to you.

**Comment by nizarbenalla** [comment]
Thanks magnus, now the changes can take effect immediately.

**Comment by nizarbenalla** [comment]
The other patch is ready to be integrated, I will start here

/integrate

**Pull request closed without merging**
