### PR TITLE
8327239: Obsolete unused GCLockerEdenExpansionPercent product option

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change to obsolete the unused flag GCLockerEdenExpansionPercent. Please also review the CSR.

Testing: local compilation, grepping sources for occurrences

Thanks,
  Thomas8327239-obsolete-gclockeredenexpansionpercent

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8327293](https://bugs.openjdk.org/browse/JDK-8327293) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8327239](https://bugs.openjdk.org/browse/JDK-8327239): Obsolete unused GCLockerEdenExpansionPercent product option (**Enhancement** - P4)
 * [JDK-8327293](https://bugs.openjdk.org/browse/JDK-8327293): Obsolete unused GCLockerEdenExpansionPercent product option (**CSR**)

### Reviewers
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18117/head:pull/18117` \
`$ git checkout pull/18117`

Update a local copy of the PR: \
`$ git checkout pull/18117` \
`$ git pull https://git.openjdk.org/jdk.git pull/18117/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18117`

View PR using the GUI difftool: \
`$ git pr show -t 18117`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18117.diff">https://git.openjdk.org/jdk/pull/18117.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18117#issuecomment-1978349974)

### CODE REVIEW

**Comment by albertnetymk** [comment]
`TestNewRatioFlag.java` uses this flag. Should tests be updated in this PR as well?

**Comment by lgxbslgx** [comment]
> `TestNewRatioFlag.java` uses this flag. Should tests be updated in this PR as well?

`TestNewSizeFlags.java` and `TestSurvivorRatioFlag.java` use this flag too.

**Review by lgxbslgx — APPROVED** [review]
Looks good.

**Review by albertnetymk — APPROVED** [review]

**Comment by tschatzl** [comment]
Thanks @albertnetymk @lgxbslgx for your reviews
/integrate

**Pull request closed without merging**
