### PR TITLE
8254699: Suboptimal PreTouchParallelChunkSize defaults and limits

### PR DESCRIPTION
**Pull request by amitdpawar**
This PR fixes lower and default value of JVM flag PreTouchParallelChunkSize. Its default value is 1GB and is used by both G1GC and ParallelGC to pretouch the pages. Following test showed that reducing the chunk size improves JVM startup time and GC pause time.

Tests are: (Test machine 2P 64C/128T with 1TB memory)
1. JVM startup time test with AdaptiveSizePolicy disabled: Pretouch 1TB of memory with/without transparent large page support and used time command to measure the time taken.
Command: time ./jdk/bin/java -XX:+AlwaysPreTouch -XX:+<UseParallelGC or UseG1GC>-Xmx900g -Xms900g -Xmn800g -XX:SurvivorRatio=400 -Xlog:gc*=debug:file=gc.log -XX:ParallelGCThreads=128 -XX:PreTouchParallelChunkSize=<chunk size> -version
2. JVM startup and GC pause time test with AdaptiveSizePolicy enabled: SPECjbb composite run with 1TB heap and transparent large page support was enabled.

Test results are recorded in XL file. [PreTouchParallelChunkSize_TestResults.xlsx](https://github.com/openjdk/jdk/files/5612448/PreTouchParallelChunkSize_TestResults.xlsx)

Test results shows:
1. With AdaptiveSizePolicy disabled.
    1. G1GC improved upto ~14% on large page disabled and ~5% on enabled.
    2. ParallelGC improved upto ~15% on large page disabled and ~5% on enabled.
    3. Tests showed improvement from 64KB for default page size and 2MB for lage page size.
    4. Please check "JVM_Startup_Summary" sheet in XL file for more detail.

2. SPECjbb composite test with UseAdaptiveSizePolicy + UseLargePages enabled.
   1. Pretouch takes up-to 30-90% less time for memory range 32MB-4GB. This happens because memory less than 1GB also pretouched with multiple threads.
   2. Same also helps to bring down GC pause time and this is dependent on memory size. Effect is larger when expansion size is smaller.
   3. Please check SPECjbb_Summary sheet in XL file for more detail.

Default value of PreTouchParallelChunkSize is changed to 4MB and based your suggestion it can be changed to right value. Please check and review this PR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254699](https://bugs.openjdk.java.net/browse/JDK-8254699): Suboptimal PreTouchParallelChunkSize defaults and limits

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to ef6fa419273e3af3b0be15127de42b6fc8aeb141
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1503/head:pull/1503`
`$ git checkout pull/1503`

### CODE REVIEW

**Review by tschatzl — CHANGES_REQUESTED** [review]
Looks good, but could you undo the changes in pretouchTask.cpp? These break the rule to have all gang tasks with a "Running .... with ... workers" message. Also, this message is then printed for all pretouch actions - even when resizing the heap which can be quite annoying.

Instead, the method could use a `GCTraceTime` instance to time the method. However I do not think this is really necessary or desired - imho in this case the caller should decide on whether it wants some log output, but others may have a different opinion :)

Since a CSR is needed for changes to product flags like this, I started one with [JDK-8257419](https://bugs.openjdk.java.net/browse/JDK-8257419). Probably also needs a release note.

/csr needed

**Comment by amitdpawar** [comment]
Thanks Thomas for your reply. Log message was changed to include the time to make it easier for testing and reviewing. If not required will revert it back. Please suggest.

Thanks,
Amit

**Comment by tschatzl** [comment]
Please remove this what looks like debug code.

**Comment by kstefanj** [comment]
> Thanks Thomas for your reply. Log message was changed to include the time to make it easier for testing and reviewing. If not required will revert it back. Please suggest.

I agree with Thomas, I think we should revert the changes done in `pretouchTask.cpp`.

**Comment by amitdpawar** [comment]
Done.

Thanks,
Amit

**Review by tschatzl — APPROVED** [review]
Lgtm.

We need to wait until the CSR has been approved. This typically happens on Thursdays.

**Comment by amitdpawar** [comment]
Thanks Thomas and Stefan for reviewing and approving the changes. Will wait until csr approval.

**Comment by kstefanj** [comment]
I did some performance runs and found that on Windows this change will not speed up pre-touching. I see some quite big regressions in some cases. So I don't think we can do this change for all platforms without doing more benchmarking. 

But since it looks good on Linux, one solution would be to make `PreTouchParallelChunkSize` a platform-dependent flag and set it to 4M for Linux and keep it at 1G for the others until we can do more investigations. 

For guidance on how to make it a platform-dependent flag you can look at how `UseLargePages` is handled.

**Comment by amitdpawar** [comment]
I was doubtful about the improvement regarding other platforms and thanks for testing and verifying. I will make it platform-specific as per your suggestion. 

On other platform, this improvement is not seen for smaller or lesser memory range also right ? similar too SPECJbb_Summary sheet in Excel file.

**Comment by kstefanj** [comment]
I have not done extensive measurements, I basically ran some startup benchmarks with:
```
-XX:+AlwaysPreTouch -Xms8g -Xmx8g
-XX:+AlwaysPreTouch -Xms8g -Xmx8g -XX:PreTouchParallelChunkSize=4m
-XX:+AlwaysPreTouch -Xms8g -Xmx8g -XX:PreTouchParallelChunkSize=128m
```

And on Windows going with the current default is the clear winner, while on Linux using 4M gives best results. Given that and your tests I think it is fairly safe to use 4M for Linux, but for the other OSes we need to do more measurements before changing to a different value.

**Comment by amitdpawar** [comment]
OK and I will make it platform specific as suggested.

Thanks,
Amit

**Comment by amitdpawar** [comment]
PreTouchParallelChunkSize is changed to platform-dependent as suggested. Please check now.

To make testing easier created two scripts and attached as zip file [run_pretouch_test.zip](https://github.com/openjdk/jdk/files/5635703/run_pretouch_test.zip).
1. Script "run_pretouch_test.sh" will run pretouch test by configuring **"from space"**  to 1MB to 8GB  for chunk sizes 64KB to 1GB. Tested only on Linux for both default and large pages.
2. Script "print_timetaken.sh" will collect and print time taken from all the generated GC log files. Time taken will be extracted for only **"from space"** and it will print table similar to shown in Excel file. [PreTouchWithDifferentMemorySize.xlsx](https://github.com/openjdk/jdk/files/5635750/PreTouchWithDifferentMemorySize.xlsx)
3. Should have build using git id "8ef5ed7c64808c6b039baa0751afa7ff017b318d" else it wont work. This particular revision dumps time for PretouchTask.

Thanks,
Amit

**Review by kstefanj — APPROVED** [review]
Looks good.

**Comment by amitdpawar** [comment]
Thanks for approving and will issue Integrate command now.

**Pull request closed without merging**
