### PR TITLE
8316142: Enable parallelism in vmTestbase/nsk/monitoring/stress/lowmem tests

### PR DESCRIPTION
**Pull request by shipilev**
Similar to [JDK-8315437](https://bugs.openjdk.org/browse/JDK-8315437), current vmTestbase/nsk/monitoring/stress/lowmem tests contains 36 tests, each running exclusively. This drags the tier4 test times up. There seem to be no reason to run these tests exclusively, though: they complete in reasonable time, are moderately-threaded, and consume the usual amount of memory.

We should consider enabling parallelism for them and get improved test performance. Currently it is blocked by TEST.properties with exclusiveAccess.dirs directives in them.

Current run on 18-core machine:
 6385.39s user 8568.61s system 1308% cpu 19:02.97 total

Fully parallel:
 3885.67s user 295.13s system 2772% cpu 2:30.77 total 

Additional testing:
 - [x] 100x Linux x86_64 fastdebug, `vmTestbase/nsk/monitoring/stress/lowmem`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316142](https://bugs.openjdk.org/browse/JDK-8316142): Enable parallelism in vmTestbase/nsk/monitoring/stress/lowmem tests (**Enhancement** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15689/head:pull/15689` \
`$ git checkout pull/15689`

Update a local copy of the PR: \
`$ git checkout pull/15689` \
`$ git pull https://git.openjdk.org/jdk.git pull/15689/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15689`

View PR using the GUI difftool: \
`$ git pr show -t 15689`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15689.diff">https://git.openjdk.org/jdk/pull/15689.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15689#issuecomment-1716984324)

### CODE REVIEW

**Comment by lmesnik** [comment]
I start testing of fix in CI and approve once it is completed.

**Comment by shipilev** [comment]
> I start testing of fix in CI and approve once it is completed.

Thank you!

**Review by lmesnik — APPROVED** [review]

**Comment by shipilev** [comment]
I think we want to have the review from serviceability area reviewers. @plummercj, maybe?

**Review by plummercj — APPROVED** [review]

**Comment by dholmes-ora** [comment]
>  and consume the usual amount of memory.

And how much is that? And at what concurrency level will we not be able to run these tests in parallel without potentially impacting the way they run i.e. running out of memory sooner than expected?

I'm concerned that these set of PRs to remove exclusive testing are going to cause a headache for those of us who have to monitor and triage CI testing. If I see one of these tests fail after this change goes in, there is nothing to give me any hint as to what has changed - no git log for the test file will show me something was modified!

**Comment by shipilev** [comment]
> > and consume the usual amount of memory.
> 
> And how much is that? And at what concurrency level will we not be able to run these tests in parallel without potentially impacting the way they run i.e. running out of memory sooner than expected?

They run at the standard heap sizes for the tests, driven by `MaxRAMPercentage` setup by build system. On my 18-core test servers, most of them run with ~700 MB RSS, sometimes peaking at ~1.1G. AFAICS, this is a common RSS for VM/GC tests. These tests eat Java heap / class memory and exit as soon as they catch OOME or load all the classes. The extended parallelism might delay that a bit, but I don't see this manifesting in practice. 

> I'm concerned that these set of PRs to remove exclusive testing are going to cause a headache for those of us who have to monitor and triage CI testing. If I see one of these tests fail after this change goes in, there is nothing to give me any hint as to what has changed - no git log for the test file will show me something was modified!

True. That's one of the reasons to avoid external test configs, whether it is `TEST.properties` near the tests, or the settings in global suite `TEST.ROOT`.

There are two bonus points from maintenance perspective:

 1. (technical) Note that the current `exclusiveDirs` limit the _in-group_ parallelism. This means that there is a random chance something else is running concurrently with these tests, if that test is outside of the this test group. So it is not like we are deciding if these tests should run in complete resource isolation from everything else or not -- they already are not isolated. Which means, if tests experience resource starvation, it would manifest pretty randomly, depending on what had been running in parallel. Unblocking the _in-group_ parallelism allows us to make these conditions manifesting more reliably. Which, I argue, benefits tests maintainability: if test can fail due to resource starvation, they would do so more often than once in a blue moon. We verify that is unlikely to happen by stress-testing multiple iterations of these tests.
 
 2. (organizational) Due to these parallelism blockages, `tier4` is remarkably slow. It is >10x slower than `tier3`, for example, and it gets worse as more untapped parallelism there is on the machine. Which is why I see both ad-hoc developer and vendor testing pipelines do not run `tier4` as frequently as they run `tier{1,2,3}`. Making `tier4` more parallel, and thus faster to run, means more frequent testing, more attention to test failures there, and thus _less_ individual headache for a handful of people who actually run and have to analyze `tier4` failures.
 
As the stability check for all of this, I have been running `tier4` with _all_ `TEST.properties` removed, and it did not fail once (yet?), while running >5x times faster. Making `tier4` run under 1 hour on heavily parallel machine would be my dream goal. With these PRs, we are slowly chipping away towards that. The intent was to get parallelism limitations lifted gradually, test group by test group, so we can backtrack if problems arise. If you want to go slower, we can.

I hope that gives a broader context for this.

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - To make the issue more complicated (sorry), the "tier4" that
@shipilev is talking about is not the same as the Mach5 Tier4 that we use in
our Oracle build/test farm.

@lmesnik should be able to shed light on where in Mach5 he has tested these
recent fixes so that the Oracle GKs know where to be vigilent. I suspect we
won't see these changes until Tier[678], but that's just a guess.

**Comment by dholmes-ora** [comment]
@shipilev  thanks for the broader context, but what platforms and configurations are you actually testing on?

**Comment by shipilev** [comment]
> @shipilev thanks for the broader context, but what platforms and configurations are you actually testing on?

Mostly 16..32-core x86_64 and AArch64 EC2 instances, similar to where the bulk of our testing runs. Testing with fastdebug binaries, sometimes juggling the GC and JIT selections.

**Comment by shipilev** [comment]
All right, so what do we do with this PR? I would like to integrate it, if there are no objections.

**Comment by dholmes-ora** [comment]
No objections here. We will just have to be vigilant about the tests modified here.

**Comment by shipilev** [comment]
Good. I'll integrate then, and keep an eye on regression reports. Please loop me in, if I miss any.

/integrate

**Pull request closed without merging**
