### PR TITLE
8302004: InlineTree should consult replay file in release build

### PR DESCRIPTION
**Pull request by MDBijman**
This removes the guards around the replay logic in InlineTree::should_inline and InlineTree:should_not_inline, as discussed in JDK-8302004.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302004](https://bugs.openjdk.org/browse/JDK-8302004): InlineTree should consult replay file in release build

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Xin Liu](https://openjdk.org/census#xliu) (@navyxliu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12492/head:pull/12492` \
`$ git checkout pull/12492`

Update a local copy of the PR: \
`$ git checkout pull/12492` \
`$ git pull https://git.openjdk.org/jdk pull/12492/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12492`

View PR using the GUI difftool: \
`$ git pr show -t 12492`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12492.diff">https://git.openjdk.org/jdk/pull/12492.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Review by navyxliu — APPROVED** [review]
LGTM. I am not a reviewer.

**Pull request closed without merging**
