### PR TITLE
8225235: Unused field defaultIndex in NetworkInterface

### PR DESCRIPTION
**Pull request by viktorklang-ora**
Removes the `defaultIndex`since it is no longer used.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8225235](https://bugs.openjdk.org/browse/JDK-8225235): Unused field defaultIndex in NetworkInterface

### Reviewers
 * [Chris Hegarty](https://openjdk.org/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to [3a9fe9ac](https://git.openjdk.org/jdk/pull/10471/files/3a9fe9ac069e83744231fa4b602e3bea4d037150)
 * [Vyom Tewari](https://openjdk.org/census#vtewari) (@vyommani - Committer) ⚠️ Review applies to [3a9fe9ac](https://git.openjdk.org/jdk/pull/10471/files/3a9fe9ac069e83744231fa4b602e3bea4d037150)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to [3a9fe9ac](https://git.openjdk.org/jdk/pull/10471/files/3a9fe9ac069e83744231fa4b602e3bea4d037150)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10471/head:pull/10471` \
`$ git checkout pull/10471`

Update a local copy of the PR: \
`$ git checkout pull/10471` \
`$ git pull https://git.openjdk.org/jdk pull/10471/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10471`

View PR using the GUI difftool: \
`$ git pr show -t 10471`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10471.diff">https://git.openjdk.org/jdk/pull/10471.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Viktor, the change looks OK to me. For the `NetworkInterface.java` file change, could you also update the copyright year from the current `2000, 2021,` to `2000, 2022,`?

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Review by vyommani — APPROVED** [review]
Looks OK to me.

**Comment by viktorklang-ora** [comment]
@dfuch @vyommani @ChrisHegarty Commit added which updates copyright year to 2022 in NetworkInterface.java :+1:

**Comment by dfuch** [comment]
Thanks! Please integrate and one of us will sponsor.

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
I'll run our internal CI tests to be sure nothing breaks, before sponsoring this.

**Comment by jaikiran** [comment]
The relevant tests in tier1, tier2 and tier3 completed without any failures.

**Pull request closed without merging**
