### PR TITLE
JDK-8280488: doclint reference checks withstand warning suppression

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a small modification to the way that bad references are reported by DocLint.

A new "mode" is introduced, `strictReferenceChecks`.   

If the mode is _not_ set, references that explicitly include a module name when that module name is not resolved in the module graph will be reported with a (suppressible) warning instead of an error.  All other issues with references will be reported as errors. This is the mode used by javac.

If the mode is set, all issues with references will be reported as errors. This is the mode used by javadoc.

This will need to be documented in the tool guide (man page).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280488](https://bugs.openjdk.java.net/browse/JDK-8280488): doclint reference checks withstand warning suppression

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7222/head:pull/7222` \
`$ git checkout pull/7222`

Update a local copy of the PR: \
`$ git checkout pull/7222` \
`$ git pull https://git.openjdk.java.net/jdk pull/7222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7222`

View PR using the GUI difftool: \
`$ git pr show -t 7222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7222.diff">https://git.openjdk.java.net/jdk/pull/7222.diff</a>

</details>

### CODE REVIEW

**Comment by jddarcy** [comment]
Question: for the JDK use case in particular, to turn all the doclint warning on during compilation, the cross-module references need to be SuppressWarning'ed?

**Comment by jonathan-gibbons** [comment]
> Question: for the JDK use case in particular, to turn all the doclint warning on during compilation, the cross-module references need to be SuppressWarning'ed?

Only forward references, where the target module is not on the module path, will need a `@SuppressWarnings` annotation.  (For example, a reference to `java.desktop` from `java.base`.   If the cross-module reference is to a module that is on the module path, you will get an error if the reference as whole cannot be resolved. (For a reference to `java.base/java.lang.OObject`  in `java.desktop` (or any module) will always cause an error.

**Comment by jddarcy** [comment]
FYI, the build completes with the changes in this PR, expanding the target set of of SuppressWarnings (JDK-8280744), and https://github.com/openjdk/jdk/pull/7237.

**Review by jddarcy — APPROVED** [review]

**Pull request closed without merging**
