### PR TITLE
8285850 : [AIX] unreachable code in basic_tools.m4 -> BASIC_CHECK_TAR

### PR DESCRIPTION
**Pull request by deepa181**
basic_tools.m4 contains the line 'elif test "x$TAR_TYPE" = "aix";...' The comparison "x$TAR_TYPE" = "aix" can never be true. Adding an 'x' to both sides of the comparison prevents an erroneous match when the variable is the empty string.

Verified the test after successful build and reflecting changes 'elif test "x$TAR_TYPE" = "xaix";...' on generated-configure.sh file.

Reported Issue : [JDK-8285850](https://bugs.openjdk.org/browse/JDK-8285850)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285850](https://bugs.openjdk.org/browse/JDK-8285850): [AIX] unreachable code in basic_tools.m4 -> BASIC_CHECK_TAR

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Tyler Steele](https://openjdk.org/census#tsteele) (@backwaterred - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12146/head:pull/12146` \
`$ git checkout pull/12146`

Update a local copy of the PR: \
`$ git checkout pull/12146` \
`$ git pull https://git.openjdk.org/jdk pull/12146/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12146`

View PR using the GUI difftool: \
`$ git pr show -t 12146`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12146.diff">https://git.openjdk.org/jdk/pull/12146.diff</a>

</details>

### CODE REVIEW

**Comment by deepa181** [comment]
basic_tools.m4 contains the line 'elif test "x$TAR_TYPE" = "aix";...' The comparison "x$TAR_TYPE" = "aix" can never be true. Adding an 'x' to both sides of the comparison prevents an erroneous match when the variable is the empty string.

Reported Issue : [JDK-8285850](https://bugs.openjdk.org/browse/JDK-8285850)

**Comment by deepa181** [comment]
> Hi @deepa181, welcome to this OpenJDK project and thanks for contributing!
> 
> We do not recognize you as [Contributor](https://openjdk.java.net/bylaws#contributor) and need to ensure you have signed the Oracle Contributor Agreement (OCA). If you have not signed the OCA, please follow [the instructions](https://oca.opensource.oracle.com/). Please fill in your GitHub username in the "Username" field of the application. Once you have signed the OCA, please let us know by writing `/signed` in a comment in this pull request.
> 
> If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please use "Add GitHub user deepa181" as summary for the issue.
> 
> If you are contributing this work on behalf of your employer and your employer has signed the OCA, please let us know by writing `/covered` in a comment in this pull request.

**Review by erikj79 — APPROVED** [review]
That is indeed a mistake, thanks for spotting it. Makes me wonder if the build worked on AIX.

**Review by backwaterred — APPROVED** [review]

**Pull request closed without merging**
