### PR TITLE
8274122: java/io/File/createTempFile/SpecialTempFile.java fails in Windows 11

### PR DESCRIPTION
**Pull request by bplb**
Windows 11 does not reserve as many names as prior versions of Windows so do not expect exceptions for COM7 and LPT1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8274122](https://bugs.openjdk.org/browse/JDK-8274122): java/io/File/createTempFile/SpecialTempFile.java fails in Windows 11 (**Bug** - P3)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to [1d18442c](https://git.openjdk.org/jdk/pull/15460/files/1d18442c40c3b843b14087d99adbe3af468ca9e8)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15460/head:pull/15460` \
`$ git checkout pull/15460`

Update a local copy of the PR: \
`$ git checkout pull/15460` \
`$ git pull https://git.openjdk.org/jdk.git pull/15460/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15460`

View PR using the GUI difftool: \
`$ git pr show -t 15460`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15460.diff">https://git.openjdk.org/jdk/pull/15460.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15460#issuecomment-1696582206)

### CODE REVIEW

**Comment by bplb** [comment]
I am not sure what else could be done here. Does anyone have any suggestions? Thanks.

**Review by LanceAndersen — APPROVED** [review]

**Review by djelinski — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]
There are newer jdk.internal.util APIs to check OS and version but they need jtreg to open up java.base.  See OperatingSystem and OSVersion if interested.

**Comment by bplb** [comment]
Thanks  @LanceAndersen , @djelinski , and @RogerRiggs . I will look at `OSVersion`.

**Comment by bplb** [comment]
On Windows 11 hardware `jdk/internal/util/OSTest.java` prints
```
STARTED    OSTest::checkOsVersion 'checkOsVersion()'
os.version: 10.0, version().toString(): 10.0
SUCCESSFUL OSTest::checkOsVersion 'checkOsVersion()'
```
as the kernel version is still 10.

**Comment by bplb** [comment]
To allow creation of files with reserved names, it appears that the OS must be Windows 11, or some future variant with a kernel version > 10. Windows 10 and 11, and Server 2019 and 2022 all appear to have kernel version 10, but from what I've seen only Windows 11 allows creation of these files. This test will probably break again in the future, but commit 7d3b243 passed 102 repeats.

**Review by RogerRiggs — APPROVED** [review]
Thanks for trying out the OSVersion API.  (Though it doesn't seem to cover all the cases).

**Review by djelinski — APPROVED** [review]

**Pull request closed without merging**
