### PR TITLE
8332123: [nmt] Move mallocLimit code to the nmt subdir

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR addresses [8332123](https://bugs.openjdk.org/browse/JDK-8332123) moving malloc limit code under the nmt subdirectory. 

Thanks, 
Sonia

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332123](https://bugs.openjdk.org/browse/JDK-8332123): [nmt] Move mallocLimit code to the nmt subdir (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [672a0a50](https://git.openjdk.org/jdk/pull/19462/files/672a0a508c879f2592724e630f5335157ef5593a)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19462/head:pull/19462` \
`$ git checkout pull/19462`

Update a local copy of the PR: \
`$ git checkout pull/19462` \
`$ git pull https://git.openjdk.org/jdk.git pull/19462/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19462`

View PR using the GUI difftool: \
`$ git pr show -t 19462`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19462.diff">https://git.openjdk.org/jdk/pull/19462.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19462#issuecomment-2140525343)

### CODE REVIEW

**Comment by SoniaZaldana** [comment]
Just want to note that GHA failures are unrelated to this PR.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Where an included file is renamed you need to reposition it to preserve the sort order of the include files. Thanks.

**Comment by tstuefe** [comment]
I think mallocLimit.hpp needs either `class outputStream;` forward decl (which is what we usually do for outputStream) or include ostream.hpp.

**Review by dholmes-ora — APPROVED** [review]
That seems fine to me.

Thanks

**Comment by tstuefe** [comment]
> That seems fine to me.
> 
> Thanks

Builds are broken, still.

**Comment by SoniaZaldana** [comment]
Thanks @tstuefe, @dholmes-ora! Just noting the GHA serviceability test failure is unrelated to this patch.

**Comment by dholmes-ora** [comment]
@tstuefe what builds are broken? I see your comment above but no context for it. The GHA builds are all fine. I also can't see how this rename could induce an unrelated build failure due to a missing include.

**Comment by dholmes-ora** [comment]
Hmm github was hiding comments from me. I still don't see how this rename could require those latest changes though. ??

**Comment by dholmes-ora** [comment]
Ah! Moving the include earlier in the list exposed missing dependencies that were being provided by includes later in the list.

**Comment by SoniaZaldana** [comment]
Thanks @dholmes-ora, @tstuefe!

**Pull request closed without merging**
