### PR TITLE
8253397: Ensure LogTag types are sorted

### PR DESCRIPTION
**Pull request by cl4es**
- Sort LogTag type enum alphabetically
- Assert that the tags are sorted instead of sorting

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253397](https://bugs.openjdk.java.net/browse/JDK-8253397): Ensure LogTag types are sorted

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to af642fb653e177cb45c7c1b32c16b2170884590f
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to af642fb653e177cb45c7c1b32c16b2170884590f
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to af642fb653e177cb45c7c1b32c16b2170884590f

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/274/head:pull/274`
`$ git checkout pull/274`

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems fine.

Thanks

**Review by kimbarrett — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Comment by dholmes-ora** [comment]
@cl4es  Please do not force push updates to a PR. There is no way for reviewers to see what, if anything, differs between the final commit and the commit that they reviewed. If you want to merge with mainline/master then just merge and push the new commit to your personal fork. The commits will be flattened as part of the actual integration. Thanks.

**Comment by tschatzl** [comment]
@dholmes-ora: fwiw, there is: click on the actual commit link (e.g. https://github.com/openjdk/jdk/pull/274/commits/19d37e729150dc330efbd494ef4e3a08b3017886 in this case) and you'll get a diff in github. There is an enhancement/bug open on skara for better support of diffs for force pushes.

**Comment by cl4es** [comment]
@dholmes-ora once I ended up in a state where force-push seemed like the only option it was too late. I assure you there were no changes from the reviewed changeset, and since there were no inline comments little I figured little was lost.

I believe a `git rebase` was the cause of this, and will use `git merge` in my workflow instead. I got into the habit of continually rebasing rather than merging in mercurial in order to avoid merge commits, but here those will be squashed anyhow. I will refrain from rebasing after opening a PR from now on.

**Comment by dholmes-ora** [comment]
> @dholmes-ora: fwiw, there is: click on the actual commit link (e.g. [19d37e7](https://github.com/openjdk/jdk/commit/19d37e729150dc330efbd494ef4e3a08b3017886) in this case where it says " cl4es added 2 commits 4 days ago ") and you'll get a diff in github. There is an enhancement/bug open on skara for better support of diffs for force pushes.

That is a diff for one of the commits that was force-pushed over the original. I can see diffs both of those commits but what I cannot see is how those commits differ to the original one that was overwritten. Further if I click on "Show changes since your last review" I get an error page:

"We went looking everywhere, but couldn’t find those commits.
Sometimes commits can disappear after a force-push. Head back to the latest changes here."

We don't need better support for forced pushes IMO we just need to not do them. Cheers.

**Pull request closed without merging**
