### PR TITLE
8283463: x86 intrinsics for toUnsignedLong and toUnsignedInt for various types of integer classes

### PR DESCRIPTION
**Pull request by vamsi-parasa**
The PR implements optimized x86 intrinsics for toUnsignedLong() and toUnsignedInt() methods in various types of integer classes.

---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8283463](https://bugs.openjdk.java.net/browse/JDK-8283463): x86 intrinsics for toUnsignedLong and toUnsignedInt for various types of integer classes

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7893/head:pull/7893` \
`$ git checkout pull/7893`

Update a local copy of the PR: \
`$ git checkout pull/7893` \
`$ git pull https://git.openjdk.java.net/jdk pull/7893/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7893`

View PR using the GUI difftool: \
`$ git pr show -t 7893`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7893.diff">https://git.openjdk.java.net/jdk/pull/7893.diff</a>

</details>

### CODE REVIEW

**Comment by jatin-bhateja** [comment]
Hi @vamsi-parasa , Nice work!
Just a suggestion, instead of taking intrinsic route can we handle them in a more generic manner during idealization of AndI/L nodes.

**Comment by vamsi-parasa** [comment]
commenting to keep the PR active

**Comment by vamsi-parasa** [comment]
Comment to keep the PR active

**Pull request closed without merging**
