### PR TITLE
8319077: Incorrect link in building.md

### PR DESCRIPTION
**Pull request by RamAnvesh**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Error
&nbsp;⚠️ This PR contains no changes

### Issue
 * [JDK-8319077](https://bugs.openjdk.org/browse/JDK-8319077): Incorrect link in building.md (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16003/head:pull/16003` \
`$ git checkout pull/16003`

Update a local copy of the PR: \
`$ git checkout pull/16003` \
`$ git pull https://git.openjdk.org/jdk.git pull/16003/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16003`

View PR using the GUI difftool: \
`$ git pr show -t 16003`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16003.diff">https://git.openjdk.org/jdk/pull/16003.diff</a>

</details>

### CODE REVIEW

**Comment by RamAnvesh** [comment]
Does this need an issue to be created? If yes, can someone please share the sop to follow?

**Comment by jaikiran** [comment]
Hello Ram, I've created https://bugs.openjdk.org/browse/JDK-8319077 to track this. Please update the title of this PR to `8319077: Incorrect link in building.md` so that it triggers the official review process.

**Comment by RamAnvesh** [comment]
> Hello Ram, I've created https://bugs.openjdk.org/browse/JDK-8319077 to track this. Please update the title of this PR to `8319077: Incorrect link in building.md` so that it triggers the official review process.

Done

**Comment by RamAnvesh** [comment]
This seems to have been fixed in master. Closing this PR

**Pull request closed without merging**
