### PR TITLE
8278826: Print error if Shenandoah flags are empty (instead of crashing)

### PR DESCRIPTION
**Pull request by dchuyko**
ShouldNotReachHere() is replaced by vm_exit_during_initialization() in few places where ShenandoahGCMode and ShenandoahGCHeuristics are examined.

Generic testing: gc/shenandoah jtreg tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278826](https://bugs.openjdk.java.net/browse/JDK-8278826): Print error if Shenandoah flags are empty (instead of crashing)

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to 5823d5dc0a4c6084555321bcefea53d33c5c1871
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**) ⚠️ Review applies to 5823d5dc0a4c6084555321bcefea53d33c5c1871

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6842/head:pull/6842` \
`$ git checkout pull/6842`

Update a local copy of the PR: \
`$ git checkout pull/6842` \
`$ git pull https://git.openjdk.java.net/jdk pull/6842/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6842`

View PR using the GUI difftool: \
`$ git pr show -t 6842`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6842.diff">https://git.openjdk.java.net/jdk/pull/6842.diff</a>

</details>

### CODE REVIEW

**Review by rkennke — COMMENTED** [review]
How did you trigger those ShouldNotReachHere()? How can those options become NULL, if they have a default value?

**Comment by dchuyko** [comment]
It is 'Flag='. Consider following command lines:

java -XX:+UseShenandoahGC -XX:ShenandoahGCMode= -version
java -XX:+UseShenandoahGC -XX:ShenandoahGCMode=satb -XX:ShenandoahGCHeuristics= -version
java -XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:ShenandoahGCMode=iu -XX:ShenandoahGCHeuristics= -version
java -XX:+UseShenandoahGC -XX:+UnlockDiagnosticVMOptions -XX:ShenandoahGCMode=passive -XX:ShenandoahGCHeuristics= -version

**Review by rkennke — APPROVED** [review]
OK, makes sense, then. Thank you!

**Review by Hamlin-Li — APPROVED** [review]
Looks good.
Seems by changing `if (ShenandoahGCHeuristics != NULL)` to `if (ShenandoahGCHeuristics == NULL)`, the trailing `return NULL;` could be removed.

**Comment by dchuyko** [comment]
Thanks. I pushed a commit that flips the condition in all 3 modes though 'return NULL;' is eliminated only in PassiveMode.

**Comment by Hamlin-Li** [comment]
Thanks for updating, still good.

**Pull request closed without merging**
