### PR TITLE
8311175: Move BufWriter::asByteBuffer to BufWriterImpl

### PR DESCRIPTION
**Pull request by liach**
As discussed on the mailing list https://mail.openjdk.org/pipermail/classfile-api-dev/2023-June/000381.html, BufWriter::asByteBuffer has a behavior not suitable for API and is only used by internal StackMapGenerator/StackCounter, so it will be converted to an internal API.

Somehow the ByteBuffer needs to be sliced, or StackMapGenerator encounters IOOBE. Not sure what the exact cause was.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8331867](https://bugs.openjdk.org/browse/JDK-8331867) to be approved

### Issues
 * [JDK-8311175](https://bugs.openjdk.org/browse/JDK-8311175): Move BufWriter::asByteBuffer to BufWriterImpl (**Bug** - P4)
 * [JDK-8331867](https://bugs.openjdk.org/browse/JDK-8331867): Remove BufWriter::asByteBuffer (**CSR**)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**) ⚠️ Review applies to [d82789c3](https://git.openjdk.org/jdk/pull/14736/files/d82789c397aa9aee55a48b47b22b6211ba7b2795)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14736/head:pull/14736` \
`$ git checkout pull/14736`

Update a local copy of the PR: \
`$ git checkout pull/14736` \
`$ git pull https://git.openjdk.org/jdk.git pull/14736/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14736`

View PR using the GUI difftool: \
`$ git pr show -t 14736`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14736.diff">https://git.openjdk.org/jdk/pull/14736.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14736#issuecomment-1614767504)

### CODE REVIEW

**Comment by asotona** [comment]
@liach Do you have any plans with this PR?

**Comment by liach** [comment]
Indeed, I should revive this patch.

/open

**Comment by liach** [comment]
@asotona classfile tests pass, can you review this patch and its associated CSR?

**Pull request closed without merging**
