### PR TITLE
8317698: Optimization for URLEncoder

### PR DESCRIPTION
**Pull request by wenshao**
@cl4es and @Glavo have already made some very good optimizations to URLEncoder, but we can continue to improve.

The current URLEncoder's Predicate for DONT_NEED_ENCODING is based on BitSet, which is actually a table lookup. The actual performance may not be as good as microbench. 

The character value range of DONT_NEED_ENCODING is between [45-122]. We can construct two long type constants to do the work of BitSet. This can improve performance by about 7% to 30%.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317698](https://bugs.openjdk.org/browse/JDK-8317698): Optimization for URLEncoder (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16082/head:pull/16082` \
`$ git checkout pull/16082`

Update a local copy of the PR: \
`$ git checkout pull/16082` \
`$ git pull https://git.openjdk.org/jdk.git pull/16082/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16082`

View PR using the GUI difftool: \
`$ git pr show -t 16082`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16082.diff">https://git.openjdk.org/jdk/pull/16082.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16082#issuecomment-1751887864)

### CODE REVIEW

**Comment by wenshao** [comment]
Performance numbers running on MacBook M1 Pro:

```diff
-Benchmark                         (encodeChars)  (maxLength)  (unchanged)  Mode  Cnt  Score    Error  Units (baseline)
-URLEncodeDecode.testEncodeLatin1              6         1024            0  avgt   15  2.222 ?  0.035  ms/op
-URLEncodeDecode.testEncodeLatin1              6         1024           75  avgt   15  1.019 ?  0.065  ms/op
-URLEncodeDecode.testEncodeLatin1              6         1024          100  avgt   15  0.414 ?  0.001  ms/op

+Benchmark                         (encodeChars)  (maxLength)  (unchanged)  Mode  Cnt  Score   Error  Units (optimized)
+URLEncodeDecode.testEncodeLatin1              6         1024            0  avgt   15  2.065 ? 0.068  ms/op (+7.61)
+URLEncodeDecode.testEncodeLatin1              6         1024           75  avgt   15  0.844 ? 0.003  ms/op (+20.74)
+URLEncodeDecode.testEncodeLatin1              6         1024          100  avgt   15  0.317 ? 0.001  ms/op (+30.60)
```

**Comment by DamonFool** [comment]
JBS: https://bugs.openjdk.org/browse/JDK-8317698

**Comment by cl4es** [comment]
I think this is a step in the wrong direction, duplicating code from a shared utility class in order to get a marginal improvement.

Could you instead analyze *why* this is a win and then see if we can improve the utility class (`ImmutableBitSetPredicate`) instead?

**Comment by cl4es** [comment]
I drafted a PR that pulls off more or less the same optimization but does so by adding a variant to `ImmutableBitSetPredicate`. This ensures other `BitSet`-based predicates of 128 elements or less would get the similar benefit, and better contains the added complexity.

**Comment by wenshao** [comment]
My problem is that ImmutableBitSetPredicate as a jdk.internal class is only used in URLEncoder

**Comment by cl4es** [comment]
It was recently conceived specifically to help `URLEncoder`, and it was implemented as an internal utility to give it time to mature/evolve and to make the decision to turn it into a public API independent from getting a quick win on JDK-internal code. It seems natural and logical that we keep improving this abstraction rather than manually inline the logic into `URLEncoder`.

**Comment by wenshao** [comment]
Can we find another use case of ImmutableBitSetPredicate in java.base?

**Comment by cl4es** [comment]
I can't find any in the java.base module, but outside of java.base there are a few candidate such as `javax.management.remote.JMXServiceURL` and `com.sun.tools.javac.jvm.PoolReader`. Why?

**Comment by wenshao** [comment]
OK, I agree with you, this optimization should be handled in ImmutableBitSetPredicate, I will close this PR.

**Pull request closed without merging**
