### PR TITLE
8312626: Resolve multiple definition of 'start_timer' when statically linking JDK native libraries with user code

### PR DESCRIPTION
**Pull request by jianglizhou**
Please review the simple fix that changes start|stop_timer to static.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312626](https://bugs.openjdk.org/browse/JDK-8312626): Resolve multiple definition of 'start_timer' when statically linking JDK native libraries with user code (**Bug** - P4)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15006/head:pull/15006` \
`$ git checkout pull/15006`

Update a local copy of the PR: \
`$ git checkout pull/15006` \
`$ git pull https://git.openjdk.org/jdk.git pull/15006/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15006`

View PR using the GUI difftool: \
`$ git pr show -t 15006`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15006.diff">https://git.openjdk.org/jdk/pull/15006.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15006#issuecomment-1648789655)

### CODE REVIEW

**Comment by mrserb** [comment]
I was thinking of asking you to see if there are any other variables or functions in this file that could be made static, but it looks like xx_timer are the only one left. Can you please confirm?

**Comment by jianglizhou** [comment]
> I was thinking of asking you to see if there are any other variables or functions in this file that could be made static, but it looks like xx_timer are the only one left. Can you please confirm?

@mrserb, thanks for looking into it. I just iterated though awt_ImagingLib.c as well and came to the same conclusion as yours.

**Comment by jianglizhou** [comment]
@mrserb and other reviewers, please help approve the PR if no additional questions. Thanks.

**Review by mrserb — APPROVED** [review]

**Comment by jianglizhou** [comment]
Thanks for the review and approval.

**Pull request closed without merging**
