### PR TITLE
8327370: (ch) sun.nio.ch.Poller.register throws AssertionError

### PR DESCRIPTION
**Pull request by dfuch**
Please find here an almost trivial change that fixes an intermittent AssertionError observed in `sun.nio.ch.Poller`.

This change (in the mist of a bigger fix) was contributed by @AlanBateman to the loom repo two weeks ago.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327370](https://bugs.openjdk.org/browse/JDK-8327370): (ch) sun.nio.ch.Poller.register throws AssertionError (**Bug** - P3)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)

### Contributors
 * Alan Bateman `<alanb@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19792/head:pull/19792` \
`$ git checkout pull/19792`

Update a local copy of the PR: \
`$ git checkout pull/19792` \
`$ git pull https://git.openjdk.org/jdk.git pull/19792/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19792`

View PR using the GUI difftool: \
`$ git pr show -t 19792`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19792.diff">https://git.openjdk.org/jdk/pull/19792.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19792#issuecomment-2180382205)

### CODE REVIEW

**Comment by AlanBateman** [comment]
There have been a few sightings. One possible theory on macOS is that kevent(2) if failing with ENOMEM although it doesn't appear to have been caught in any logs.

**Review by AlanBateman — APPROVED** [review]
Thanks for fixing this in the main line, I assume it will need someone else to review.

**Review by jaikiran — APPROVED** [review]
The change looks reasonable to me and looking at the code that's the only place where an entry would be inserted into the map, so this change isn't needed in any other call sites.

**Comment by dfuch** [comment]
Thanks @jaikiran

**Review by djelinski — APPROVED** [review]

**Comment by dfuch** [comment]
Thanks @djelinski

**Pull request closed without merging**
