### PR TITLE
8271353: PerfDataManager::destroy crashes in VM_Exit

### PR DESCRIPTION
**Pull request by navyxliu**
This patch check PerfDataManager::_sampled and _constants is NULL. if it is,
return -1. 

When the user enables UL `-Xlog:perf+datacreation=debug`, it may crash in
PerfDataManager::destroy(). The following line will crash when _sampled is NULL.

```
  log_debug(perf, datacreation)("Total = %d, Sampled = %d, Constants = %d",
                                _all->length(), _sampled->length(), _constants->length());
```

This only happens when UsePerfData is on and PerfDataManager::destroy() is invoked before
StatSampler::initialize() which initializes PerfDataManager::_sampled.
PerfDataManager::destroy() is called by VM_Exit which can be triggered by SIGINT on Linux anytime.

A reproducible: invoke the following command and keep pressing Ctrl-c.
$perf stat -r 100 java -Xlog:perf+datacreation=debug --version

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271353](https://bugs.openjdk.java.net/browse/JDK-8271353): PerfDataManager::destroy crashes in VM_Exit

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to d94c9d35097018c3c7bfa82ce13e80eef3ef4457
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4913/head:pull/4913` \
`$ git checkout pull/4913`

Update a local copy of the PR: \
`$ git checkout pull/4913` \
`$ git pull https://git.openjdk.java.net/jdk pull/4913/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4913`

View PR using the GUI difftool: \
`$ git pr show -t 4913`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4913.diff">https://git.openjdk.java.net/jdk/pull/4913.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
The additional NULL checks seem fine and trivial.

Thanks,
David

**Review by tstuefe — APPROVED** [review]
+1

**Review by yminqi — COMMENTED** [review]
Hi, Xin
  The copyright year needs updated. 
  Maybe '0' is more meaningful than '-1'?

**Comment by navyxliu** [comment]
> Hi, Xin
> The copyright year needs updated.
> Maybe '0' is more meaningful than '-1'?

Thanks for the head-up.  I agree that 0 is easier to understand.  I will update it. 
PerfDataManager::add_item() "appends" a PerfData.  if _sampled is not NULL, it should be at least 1.

**Review by yminqi — APPROVED** [review]

**Comment by navyxliu** [comment]
Thank all reviewers.

**Review by dholmes-ora — APPROVED** [review]
I actually preferred the -1 to indicate "not available", but  it doesn't really matter.

Thanks,
David

**Comment by navyxliu** [comment]
I have a same thought at first, but 0 isn't normal state. We can use 0 for N/A.

**Pull request closed without merging**
