### PR TITLE
8340923: The class LogSelection copies uninitialized memory

### PR DESCRIPTION
**Pull request by jdksjolen**
The class LogSelection's custom constructor does not initialize the whole _tags array but is lacking a custom copy constructor and assignment operator. This means that any copy will copy uninitialized memory, which is undefined behavior. UBSAN has seen this happen, as reported by Matthias Baesken.

For some surrounding context: Unified Logging uses a statically defined array size (`LogTag::MaxTag`) but uses the `LogTag::__NO_TAG` to signify the end of the array. Think "NULL-terminated string but log tags".

We fill the whole array to avoid this issue. Specifically, we filll the remainder of the array with `LogTag::__NO_TAG`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340923](https://bugs.openjdk.org/browse/JDK-8340923): The class LogSelection copies uninitialized memory (**Bug** - P4)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21185/head:pull/21185` \
`$ git checkout pull/21185`

Update a local copy of the PR: \
`$ git checkout pull/21185` \
`$ git pull https://git.openjdk.org/jdk.git pull/21185/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21185`

View PR using the GUI difftool: \
`$ git pr show -t 21185`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21185.diff">https://git.openjdk.org/jdk/pull/21185.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21185#issuecomment-2374155806)

### CODE REVIEW

**Comment by MBaesken** [comment]
Should be `LogTag::MaxTags` I guess, not   `_LogTag::MaxTags ` ?

**Comment by MBaesken** [comment]
After fixing the mentioned compile issues, and building with ubsan enabled,  I can confirm that the mentioned ubsan errors  from https://bugs.openjdk.org/browse/JDK-8333090  (seen when running the HS cds/appcds  tests)  are gone.

**Comment by jdksjolen** [comment]
> Should be `LogTag::MaxTags` I guess, not `_LogTag::MaxTags ` ? And in the for loop we need `size_t i` , otherwise gcc complains with a warning as error.

Jeeze, I didn't see the underscore because of the red squigglies in my IDE and I assumed it was the IDE that was buggy 😅. Thank you for taking the time to run the tests.

**Review by MBaesken — APPROVED** [review]

**Review by TheShermanTanker — APPROVED** [review]

**Review by stefank — CHANGES_REQUESTED** [review]
I think it would be nicer if you just add `_tags()` to the initializer list.

**Review by stefank — COMMENTED** [review]
You also need to fix `LogSelection::LogSelection()`

**Comment by jdksjolen** [comment]
That is indeed simpler. Thank you for the catch.

**Review by abdelhak-zaaim — CHANGES_REQUESTED** [review]
I suggest using std::fill(_tags + _ntags, _tags + LogTag::MaxTags, LogTag::__NO_TAG); instead of the manual loop. Its cleaner, easier to read  and takes advantage of the standard library.

**Review by stefank — APPROVED** [review]
Looks good.

**Comment by TheShermanTanker** [comment]
@abdelhak-zaaim HotSpot code is not allowed to use the vast majority of the C++ Standard Library

**Comment by MBaesken** [comment]
> @abdelhak-zaaim HotSpot code is not allowed to use the vast majority of the C++ Standard Library

Would we need to adjust linker settings (in case it would be allowed) ?

**Review by MBaesken — APPROVED** [review]

**Comment by TheShermanTanker** [comment]
> > @abdelhak-zaaim HotSpot code is not allowed to use the vast majority of the C++ Standard Library
> 
> Would we need to adjust linker settings when using std::fill (in case it would be allowed) ?

I don't believe linker settings have to be changed, HotSpot does already link with the C++ Standard Library in the few cases where it's used, typically statically if I'm not wrong. But compiler settings might prove to be a challenge, because std::fill throws exceptions, and HotSpot currently restricts exception usage, they're forcefully disabled on the command line to enforce this rule. I do have an experiment where exceptions and RTTI are not disabled for HotSpot, and in those tests there are red crosses all over the runners, so I believe doing this would not be an easy undertaking

**Review by TheShermanTanker — APPROVED** [review]

**Comment by jdksjolen** [comment]
The failing GHA is unrelated to these changes. Thank you for the quick reviews and help.

/integrate

**Pull request closed without merging**
