### PR TITLE
8260934: java/lang/StringBuilder/HugeCapacity.java fails without Compact Strings

### PR DESCRIPTION
**Pull request by shipilev**
```
$ CONF=linux-x86_64-server-fastdebug make run-test TEST=java/lang/StringBuilder/HugeCapacity.java TEST_VM_OPTS=-XX:-CompactStrings

STDERR:
java.lang.OutOfMemoryError: Required length exceeds implementation limit
at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:259)
at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:229)
at java.base/java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:213)
at java.base/java.lang.StringBuilder.ensureCapacity(StringBuilder.java:87)
at HugeCapacity.testLatin1(HugeCapacity.java:49)
at HugeCapacity.main(HugeCapacity.java:37)
```

I went back and forth in fixing this test, and I think the best we can do is sense the current setting on `CompactStrings` and choose the test configuration based on that. The alternative is to use `WhiteBox` within the test (tried, it is quite a bit ugly). Note that this test deliberately does not run `-XX:-CompactStrings` even when `vm.opt.final.CompactStrings` returns true (= "available"), because that might mean `TEST_VM_OPTS=-XX:+CompactStrings` is in effect, and we have the VM option conflict.

Additional testing:
 - [x] Linux x86_64, affected test (default), passes
 - [x] Linux x86_64, affected test (`-XX:-CompactStrings`), passes
 - [x] Linux x86_64, affected test (`-XX:+CompactStrings`), passes

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260934](https://bugs.openjdk.java.net/browse/JDK-8260934): java/lang/StringBuilder/HugeCapacity.java fails without Compact Strings

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2355/head:pull/2355`
`$ git checkout pull/2355`

### CODE REVIEW

**Comment by shipilev** [comment]
Anyone? :)

**Comment by iklam** [comment]
Having two `@test` blocks makes the maintenance more difficult. I had to do a diff to find out the difference between the two blocks.

There's an existing test that explicitly tests both `-XX:+CompactStrings` and `-XX:-CompactStrings`. Maybe we can do the same thing?

https://github.com/openjdk/jdk/blob/8f4c15f6417e471b372f74460fa94b9d84c4811d/test/hotspot/jtreg/runtime/CompactStrings/TestMethodNames.java#L29

```
* @run main/othervm -Xms5G -Xmx5G -XX:+CompactStrings HugeCapacity true
* @run main/othervm -Xms5G -Xmx5G -XX:-CompactStrings HugeCapacity false
```

**Comment by shipilev** [comment]
> Having two `@test` blocks makes the maintenance more difficult. I had to do a diff to find out the difference between the two blocks.
> 
> There's an existing test that explicitly tests both `-XX:+CompactStrings` and `-XX:-CompactStrings`. Maybe we can do the same thing?

No, I don't think we can. In other tests, the conflict between `-XX:+CompactStrings` and `-XX:-CompactStrings` would select one of the modes, so both test configurations would degenerate into one config (run twice). In this test, however, the compact strings mode defines whether the affected subtest would pass or fail, because it pokes at the allocation limit. So, we have to sense the actual setting of `CompactStrings` here. 

As I said, the alternative would be sensing it programmatically via `WhiteBox`, at expense at single `@test` config, but with `WhiteBox` ceremony.

**Comment by iklam** [comment]
> > There's an existing test that explicitly tests both `-XX:+CompactStrings` and `-XX:-CompactStrings`. Maybe we can do the same thing?
> 
> No, I don't think we can. In other tests, the conflict between `-XX:+CompactStrings` and `-XX:-CompactStrings` would select one of the modes, so both test configurations would degenerate into one config (run twice).

I tried running `jtreg -vmoptions:-XX:+CompactStrings TestMethodNames.java` and the log file shows:

```
(the first @test)
-XX:+CompactStrings \
-XX:+CompactStrings \
com.sun.javatest.regtest.agent.MainWrapper /jdk2/tmp/jtreg/work/runtime/CompactStrings/TestMethodNames.d/main.0.jta

(the second @test)
-XX:+CompactStrings \
-XX:-CompactStrings \
com.sun.javatest.regtest.agent.MainWrapper /jdk2/tmp/jtreg/work/runtime/CompactStrings/TestMethodNames.d/main.1.jta
```

The VM options specified by the `@test` line are appended after the options specified by `-vmoptions`. So this test is executed in two different configurations (not twice in the same configuration).

**Comment by shipilev** [comment]
> The VM options specified by the `@test` line are appended after the options specified by `-vmoptions`. So this test is executed in two different configurations (not twice in the same configuration).

Right, okay, so the last option wins, this is good. We can do what the updated version does. ...but then we also need to handle platforms where `-XX:-CompactStrings` is set by platform config (e.g. on ARM). `-XX:+CompactStrings` would be ignored there, and we cannot run test with `true` then. I think only ARM32 is affected, so it would be filtered by existing `@requires`, so it can be resolved later.

**Review by iklam — APPROVED** [review]

**Pull request closed without merging**
