### PR TITLE
8328074: Add jcheck whitespace checking for assembly files

### PR DESCRIPTION
**Pull request by magicus**
As part of the ongoing effort to enable jcheck whitespace checking to all text files, it is now time to address assembly (.S) files. The hotspot assembly files were fixed as part of the hotspot mapfile removal, so only a single incorrect jdk library remains.

The main issue with `libjsvml` was inconsistent line starts, sometimes using tabs. I used the `expand` unix command line tool to replace these with spaces.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328074](https://bugs.openjdk.org/browse/JDK-8328074): Add jcheck whitespace checking for assembly files (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18268/head:pull/18268` \
`$ git checkout pull/18268`

Update a local copy of the PR: \
`$ git checkout pull/18268` \
`$ git pull https://git.openjdk.org/jdk.git pull/18268/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18268`

View PR using the GUI difftool: \
`$ git pr show -t 18268`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18268.diff">https://git.openjdk.org/jdk/pull/18268.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18268#issuecomment-1994153705)

### CODE REVIEW

**Comment by magicus** [comment]
(Apologies for the force push; I mistakenly added commits to this PR that was intended to go on another branch)

**Comment by magicus** [comment]
I tagged this `core-libs` as that is what @sviswa7 did for changes to libjsvml in https://github.com/openjdk/jdk/pull/8508. I hope this is correct. (We should really add rules to Skara for this library.)

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
Maybe someone in Hotspot wants to take a look?
/label +hotspot

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Comment by magicus** [comment]
Thanks @sviswa7!

/integrate

**Pull request closed without merging**
