### PR TITLE
8305858: Resolve multiple definition of 'handleSocketError' when statically linking with JDK native libraries

### PR DESCRIPTION
**Pull request by jianglizhou**
Rename 'handleSocketError' to 'sctpHandleSocketError' in libsctp. This resolves the related duplicate symbol failures when both libnio and libsctp are statically linked with the launcher.

Remove #include "nio_util.h" from SctpChannelImpl.c and SctpNet.c. Looks like that's only needed for handleSocketError() declaration. Declare sctpHandleSocketError() in Sctp.h.

(Sorry about the earlier RFR/Withdrawn noise.)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305858](https://bugs.openjdk.org/browse/JDK-8305858): Resolve multiple definition of 'handleSocketError' when statically linking with JDK native libraries

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13438/head:pull/13438` \
`$ git checkout pull/13438`

Update a local copy of the PR: \
`$ git checkout pull/13438` \
`$ git pull https://git.openjdk.org/jdk.git pull/13438/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13438`

View PR using the GUI difftool: \
`$ git pr show -t 13438`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13438.diff">https://git.openjdk.org/jdk/pull/13438.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13438#issuecomment-1504526144)

### CODE REVIEW

**Comment by jianglizhou** [comment]
I noticed there is a presubmit test failure: https://github.com/jianglizhou/jdk/actions/runs/4672962155#user-content-java_lang_thread_virtual_tracevirtualthreadlocals for linux-x86. It appears to be unrelated. Will file a bug tomorrow if there is not existing bug (will check before filing).

**Comment by AlanBateman** [comment]
This looks okay but it makes me wonder about loadSocketExtensionFuncs. Maybe we should remove that from Sctp.h and change loadSocketExtensionFuncs in SctpNet.c to be static.

**Comment by jianglizhou** [comment]
> This looks okay but it makes me wonder about loadSocketExtensionFuncs. Maybe we should remove that from Sctp.h and change loadSocketExtensionFuncs in SctpNet.c to be static.

Changed loadSocketExtensionFuncs to be static as suggested.

**Comment by AlanBateman** [comment]
> Changed loadSocketExtensionFuncs to be static as suggested.

Thanks, that avoids having inconsistent naming in the header file.

**Review by AlanBateman — APPROVED** [review]

**Comment by jianglizhou** [comment]
Thanks for the review.

**Comment by jianglizhou** [comment]
> I noticed there is a presubmit test failure: https://github.com/jianglizhou/jdk/actions/runs/4672962155#user-content-java_lang_thread_virtual_tracevirtualthreadlocals for linux-x86. It appears to be unrelated. Will file a bug tomorrow if there is not existing bug (will check before filing).

I found there is the existing https://bugs.openjdk.org/browse/JDK-8305875.

**Pull request closed without merging**
