### PR TITLE
8253876: jdk/test/lib/hexdump/ASN1FormatterTest.java fails with "AssertionError: Lines expected [126] but found [202]"

### PR DESCRIPTION
**Pull request by RogerRiggs**
The HexPrinter test utility should be ignoring \r characters from the formatter.
It looks for \n and generates System.lineSeparator() at the end of each line.

With this fix, the ASN1FormatterTest can be removed from the ProblemList.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (langtools/tier1)](https://github.com/RogerRiggs/jdk/runs/1221843816)

### Issue
 * [JDK-8253876](https://bugs.openjdk.java.net/browse/JDK-8253876): jdk/test/lib/hexdump/ASN1FormatterTest.java fails with "AssertionError: Lines expected [126] but found [202]"

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 6f1f564d255f01545e50227e107e1d09df1f3a21
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/486/head:pull/486`
`$ git checkout pull/486`

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
I am puzzled about this change. I feels weird to drop proper line separator from `ASN1Formatter` to please the test. And it does not even look complete, because `ASN1Formatter` still uses `String.format("...%n", ...)` sometimes, that still uses system line separator.

Can the test be made resilient by watching out for `lineSeparator()`, instead of just `\n`?

**Comment by RogerRiggs** [comment]
The real fix for the test failing was the change in HexPrinter to ignore the <CR> when it is breaking lines from the formatter.
HexPrinter expected only /n from the formatter.

However, since the formatters can be used independently of HexPrinter, they should use System.lineSeparator() to work consistently.  I'll put back the System.lineSepartor() use and re-test.

**Review by shipilev — APPROVED** [review]
This looks significantly better, thanks!

**Review by LanceAndersen — APPROVED** [review]

**Pull request closed without merging**
