### PR TITLE
8264548: Dependencies: ClassHierarchyWalker::is_witness() cleanups

### PR DESCRIPTION
**Pull request by iwanowww**
Simplify `ClassHierarchyWalker::is_witness()`.

Testing: hs-tier1 - hs-tier4.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264548](https://bugs.openjdk.java.net/browse/JDK-8264548): Dependencies: ClassHierarchyWalker::is_witness() cleanups

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3297/head:pull/3297` \
`$ git checkout pull/3297`

Update a local copy of the PR: \
`$ git checkout pull/3297` \
`$ git pull https://git.openjdk.java.net/jdk pull/3297/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3297`

View PR using the GUI difftool: \
`$ git pr show -t 3297`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3297.diff">https://git.openjdk.java.net/jdk/pull/3297.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Looks like it has changes from: https://git.openjdk.java.net/jdk/pull/3293

**Comment by iwanowww** [comment]
I created it as a dependent PR. 

I think that's the way it works (https://github.com/openjdk/skara/pull/1087 which was used as an example in [1] looks similar). 

[1] https://mail.openjdk.java.net/pipermail/jdk-dev/2021-March/005232.html

**Comment by iwanowww** [comment]
Anyway, I rebased and force-pushed the patch since #3293 is integrated now.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by vnkozlov** [comment]
> I created it as a dependent PR.
> 
> I think that's the way it works ([openjdk/skara#1087](https://github.com/openjdk/skara/pull/1087) which was used as an example in [1] looks similar).
> 
> [1] https://mail.openjdk.java.net/pipermail/jdk-dev/2021-March/005232.html

As I understand when you are creating PR which based on an other PR you have to change `base:` from `master` to corresponding `pr/3293`  so that only difference of current PR are seen.

**Comment by iwanowww** [comment]
Thanks, Vladimir.

**Pull request closed without merging**
