### PR TITLE
8300267: Remove duplicated setter/getter for do_not_unlock

### PR DESCRIPTION
**Pull request by robehn**
Hi please consider.

Testing t1 + zero build

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300267](https://bugs.openjdk.org/browse/JDK-8300267): Remove duplicated setter/getter for do_not_unlock

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [8ac52b2b](https://git.openjdk.org/jdk/pull/12044/files/8ac52b2bf5553b81e98da4942441b9b5a0d70143)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [8ac52b2b](https://git.openjdk.org/jdk/pull/12044/files/8ac52b2bf5553b81e98da4942441b9b5a0d70143)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12044/head:pull/12044` \
`$ git checkout pull/12044`

Update a local copy of the PR: \
`$ git checkout pull/12044` \
`$ git pull https://git.openjdk.org/jdk pull/12044/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12044`

View PR using the GUI difftool: \
`$ git pr show -t 12044`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12044.diff">https://git.openjdk.org/jdk/pull/12044.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good!

**Review by dholmes-ora — APPROVED** [review]
LGTM. Thanks

**Comment by robehn** [comment]
Thank @dholmes-ora, @coleenp !

**Pull request closed without merging**
