### PR TITLE
8318383: Remove duplicated checks in os::get_native_stack() in posix implementation

### PR DESCRIPTION
**Pull request by zhengyu123**
Trivial cleanup that removes duplicated checkings.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318383](https://bugs.openjdk.org/browse/JDK-8318383): Remove duplicated checks in os::get_native_stack() in posix implementation (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16232/head:pull/16232` \
`$ git checkout pull/16232`

Update a local copy of the PR: \
`$ git checkout pull/16232` \
`$ git pull https://git.openjdk.org/jdk.git pull/16232/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16232`

View PR using the GUI difftool: \
`$ git pr show -t 16232`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16232.diff">https://git.openjdk.org/jdk/pull/16232.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16232#issuecomment-1767384731)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Took me a few minutes to convince myself but looks good. :)

Thanks

**Comment by dholmes-ora** [comment]
Please fix the typo in JBS and PR title: implemenation -> implementation

**Comment by zhengyu123** [comment]
> Please fix the typo in JBS and PR title: implemenation -> implementation

Fixed.

Thanks, @dholmes-ora

**Review by tstuefe — COMMENTED** [review]
Hi Zhengyu,

This is not trivial :)

let
A=> fp == null
B=> cb != null
C=> sender-pc == null
D=> is_first_frame

Old:
if (A || B || C || D) break;
if (!C && !D) get_sender_for...;

New:
if (A || B || C || D) break;
get_sender...

Not sure if that is correct, but it is at least not equivalent, so not a simple cleanup.

(note that I support any cleanup, the old code is terrible).

**Comment by zhengyu123** [comment]
> Hi Zhengyu,
> 
> This is not trivial :)
> 
> let A=> fp == null B=> cb != null C=> sender-pc == null D=> is_first_frame
> 
> Old: if (A || B || C || D) break; if (!C && !D) get_sender_for...;
> 
> New: if (A || B || C || D) break; get_sender...
> 
> Not sure if that is correct, but it is at least not equivalent, so not a simple cleanup.
> 
> (note that I support any cleanup, the old code is terrible).

I agree it is confusing, I stared at it for quite a long while. I think I copied it from somewhere.

In the old code, when it arrives to the second check, it must have:

`fr.send_pc() != nullptr` and `os::is_first_C_frame(&fr) == false`

so `if (fr.sender_pc() && !os::is_first_C_frame(&fr))` check is always `true`, no?

**Comment by zhengyu123** [comment]
> Hi Zhengyu,
> 
> This is not trivial :)
> 
> let A=> fp == null B=> cb != null C=> sender-pc == null D=> is_first_frame
> 
> Old: if (A || B || C || D) break; if (!C && !D) get_sender_for...;
> 
> New: if (A || B || C || D) break; get_sender...
> 
> Not sure if that is correct, but it is at least not equivalent, so not a simple cleanup.
> 
> (note that I support any cleanup, the old code is terrible).

I agree it is confusing, I stared at it for quite a long while. I think I copied it from somewhere.

In the old code, when it arrives to the second check, it must have:

`fr.send_pc() != nullptr` and `os::is_first_C_frame(&fr) == false`

so `if (fr.sender_pc() && !os::is_first_C_frame(&fr))` check is always `true`, no?

**Comment by dholmes-ora** [comment]
@tstuefe It took me a while to get it too. If we don't break then the two conditions we were checking must be true - else we would not reach that check.

**Comment by tstuefe** [comment]
@zhengyu123 @dholmes-ora Okay, I think you are right.

**Review by tstuefe — APPROVED** [review]

**Pull request closed without merging**
