### PR TITLE
8321396: Retire test/jdk/java/util/zip/NoExtensionSignature.java

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which suggests we retire the ZIP test `NoExtensionSignature` along with its `test.jar` test vector. 

The concern of a missing data descriptor signature is covered by the recently updated  `DataDescriptorSignatureMissing` test, see #12959. That test is more complete, includes more documentation and uses a programmatically generated test vector.

Careful analysis of the deleted `test.jar` test vector revealed that it contains a local header with non-zero `compressed size` and `uncompressed size` fields for a streaming-mode entry. `APPNOTE.TXT` mandates that when bit 3 of the general purpose bit flag is set, then these fields and the `crc` field should all be set to zero. 

By injecting assertions into `ZipInputStream.readLOC` I was able to determine that `NoExtensionSignature` is the only test currently parsing a ZIP file with such non-zero fields in streaming mode. 

Because of this, and out of caution, this PR introduces a new test `DataDescriptorIgnoreCrcAndSizeFields` which  explicitly verifies that `ZipInputStream` does not read any non-zero `crc`, `compressed size` or `uncompressed size` field values from a local header when in streaming mode. `ZipInputStream` should ignore these values and it would be good to have a test which asserts that this invariant holds even when the fields are non-zero.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321396](https://bugs.openjdk.org/browse/JDK-8321396): Retire test/jdk/java/util/zip/NoExtensionSignature.java (**Enhancement** - P4)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16975/head:pull/16975` \
`$ git checkout pull/16975`

Update a local copy of the PR: \
`$ git checkout pull/16975` \
`$ git pull https://git.openjdk.org/jdk.git pull/16975/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16975`

View PR using the GUI difftool: \
`$ git pr show -t 16975`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16975.diff">https://git.openjdk.org/jdk/pull/16975.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16975#issuecomment-1845725154)

### CODE REVIEW

**Comment by eirbjo** [comment]
> Eirik, Could you add a reference to [PR 12959](https://github.com/openjdk/jdk/pull/12959/) or to [JDK-8303920](https://bugs.openjdk.org/browse/JDK-8303920) in the above

Thanks, that makes sense!

**Comment by eirbjo** [comment]
Here's the relevant section from `APPNOTE.TXT`:

```
4.4.4 general purpose bit flag: (2 bytes)
[..]
Bit 3: If this bit is set, the fields crc-32, compressed 
       size and uncompressed size are set to zero in the 
       local header. The correct values are put in the 
       data descriptor immediately following the compressed
       data.
```
One could argue we should validate and throw a `ZipException` for such entries, but that is perhaps a question for another PR.

**Review by LanceAndersen — APPROVED** [review]

**Pull request closed without merging**
