### PR TITLE
8309854: ciReplay TestServerVM test fails with Graal

### PR DESCRIPTION
**Pull request by TobiHartmann**
We hit an assert in the test because the VM does not crash with` -XX:CICrashAt=1` with Graal as JIT. Also, Graal does not support replay compilation (see [JDK-8181747](https://bugs.openjdk.org/browse/JDK-8181747)), so the test should simply be excluded with Graal.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309854](https://bugs.openjdk.org/browse/JDK-8309854): ciReplay TestServerVM test fails with Graal (**Bug** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14447/head:pull/14447` \
`$ git checkout pull/14447`

Update a local copy of the PR: \
`$ git checkout pull/14447` \
`$ git pull https://git.openjdk.org/jdk.git pull/14447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14447`

View PR using the GUI difftool: \
`$ git pr show -t 14447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14447.diff">https://git.openjdk.org/jdk/pull/14447.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14447#issuecomment-1589308991)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good and trivial!

**Comment by TobiHartmann** [comment]
Thanks, Christian!

**Review by vnkozlov — APPROVED** [review]
Agree.

**Comment by TobiHartmann** [comment]
Thanks, Vladimir!

**Pull request closed without merging**
