### PR TITLE
8343343: Misc crash dump improvements on more platforms after JDK-8294160

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
[JDK-8294160](https://bugs.openjdk.org/browse/JDK-8294160) has improved `os::print_tos_pc` for some platforms. This PR extends it to more platforms. I have moved it into shared code and made it generic.
In addition, `fetch_frame_from_context(const void* ucVoid)` checks the pc on more platforms, now. If it's bad, we use the caller PC instead.

Note that the address 0 is readable on AIX. Therefore, it requires an extra null check. Tested by
```diff
diff --git a/src/hotspot/cpu/ppc/ppc.ad b/src/hotspot/cpu/ppc/ppc.ad
index 6d3daa025e8..0f8de648d53 100644
--- a/src/hotspot/cpu/ppc/ppc.ad
+++ b/src/hotspot/cpu/ppc/ppc.ad
@@ -1557,6 +1557,12 @@ void MachPrologNode::emit(C2_MacroAssembler *masm, PhaseRegAlloc *ra_) const {
     __ std(return_pc, _abi0(lr), callers_sp);
   }
 
+  if (UseNewCode) {
+    __ li(R0, 0);
+    __ mtctr(R0);
+    __ bctrl();
+  }
+
   if (C->stub_function() == nullptr) {
     BarrierSetAssembler* bs = BarrierSet::barrier_set()->barrier_set_assembler();
     bs->nmethod_entry_barrier(masm, push_frame_temp);
```

The new version shows the "Instructions:" section at the caller PC which was missing on some platforms before this PR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343343](https://bugs.openjdk.org/browse/JDK-8343343): Misc crash dump improvements on more platforms after JDK-8294160 (**Bug** - P4)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**) Review applies to [62eee71a](https://git.openjdk.org/jdk/pull/21809/files/62eee71a0f9221a84f2e1483d3a797f5e0fe7297)
 * [Joachim Kern](https://openjdk.org/census#jkern) (@JoKern65 - Committer)

### Contributors
 * Boris Ulasevich `<bulasevich@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21809/head:pull/21809` \
`$ git checkout pull/21809`

Update a local copy of the PR: \
`$ git checkout pull/21809` \
`$ git pull https://git.openjdk.org/jdk.git pull/21809/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21809`

View PR using the GUI difftool: \
`$ git pr show -t 21809`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21809.diff">https://git.openjdk.org/jdk/pull/21809.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21809#issuecomment-2450144189)
</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
@bulasevich, @mo-beck: `os::fetch_frame_from_context` is missing on arm and Windows aarch64. Therefore, I have reverted the change for these 2 platforms (see 3rd commit). In addition, the unified `os::print_tos_pc` prints more instructions than the previous Windows aarch64 version. Let me know if you want to provide code for these parts.

**Comment by TheRealMDoerr** [comment]
> the bsd zero code had previously this
> 
> ```
> void os::print_tos_pc(outputStream *st, const void *context) {
>   ShouldNotCallThis();
> }
> ```
> 
> Is the new common / unified coding now working there? Or is it not called anyway ?

It's not called. And the new implementation calls `fetch_frame_from_context` which also contains `ShouldNotCallThis();`. So, it's basically no change for zero.

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for the review! I'll wait a bit. Maybe we'll get an arm32 part from @bulasevich.
Maybe @dean-long as the author of [JDK-8294160](https://bugs.openjdk.org/browse/JDK-8294160) would like to take a look, too?

**Review by dean-long — APPROVED** [review]
This looks fine, including the new print_tos_pc refactor.

**Comment by bulasevich** [comment]
> Maybe we'll get an arm32 part from @bulasevich.

Hi Martin,

I believe this would be the appropriate change for ARM32:

```diff
--- a/src/hotspot/os_cpu/linux_arm/os_linux_arm.cpp
+++ b/src/hotspot/os_cpu/linux_arm/os_linux_arm.cpp
@@ -188,9 +188,27 @@ frame os::fetch_frame_from_context(const void* ucVoid) {
   intptr_t* sp;
   intptr_t* fp;
   address epc = fetch_frame_from_context(ucVoid, &sp, &fp);
+  if (!is_readable_pointer(epc)) {
+    // Try to recover from calling into bad memory
+    // Assume new frame has not been set up, the same as
+    // compiled frame stack bang
+    return fetch_compiled_frame_from_context(ucVoid);
+  }
   return frame(sp, fp, epc);
 }

+frame os::fetch_compiled_frame_from_context(const void* ucVoid) {
+  const ucontext_t* uc = (const ucontext_t*)ucVoid;
+  // In compiled code, the stack banging is performed before LR
+  // has been saved in the frame.  LR is live, and SP and FP
+  // belong to the caller.
+  intptr_t* fp = os::Linux::ucontext_get_fp(uc);
+  intptr_t* sp = os::Linux::ucontext_get_sp(uc);
+  address pc = (address)(uc->uc_mcontext.arm_lr
+                         - NativeInstruction::instruction_size);
+  return frame(sp, fp, pc);
+}
+
 frame os::get_sender_for_C_frame(frame* fr) {
 #ifdef __thumb__
   // We can't reliably get anything from a thumb C frame.
```

**Review by JoKern65 — APPROVED** [review]
LGTM on AIX

**Comment by TheRealMDoerr** [comment]
GHA failure is unrelated: Unable to download artifact(s): Artifact not found for name: bundles-jtreg-7.4+1

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews! Linux arm32 build has passed. I think I can integrate, soon.

**Comment by dean-long** [comment]
BTW, after this change, it looks like we can hook up the get_frame_at_stack_banging_point() code in os_posix.cpp that was previously disabled for ARM.

**Comment by TheRealMDoerr** [comment]
That would be nice. At least, we have one obstacle less, now. I guess it will still need to be evaluated and tested on an ARM32 machine.

**Pull request closed without merging**
