### PR TITLE
8262256: C2 intrinsincs should not modify IR when bailing out

### PR DESCRIPTION
**Pull request by TobiHartmann**
While investigating [JDK-8262231](https://bugs.openjdk.java.net/browse/JDK-8262231) in project Valhalla, I've noticed that the unsafe access C2 intrinsics sometimes emit code before then bailing out, leaving control flow before the slow call that might lead to deoptimization or an inconsistent JVMState. I've added an assert to catch this and fixed the corresponding intrinsic code (in that case null checks in `make_unsafe_address` are the culprit).

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262256](https://bugs.openjdk.java.net/browse/JDK-8262256): C2 intrinsincs should not modify IR when bailing out

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2775/head:pull/2775`
`$ git checkout pull/2775`

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me

**Comment by TobiHartmann** [comment]
Thanks for the review, Roland!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by TobiHartmann** [comment]
Thanks, Vladimir!

**Pull request closed without merging**
