### PR TITLE
8344233: Remove calls to SecurityManager and doPrivileged in java.net.ProxySelector and sun.net.spi.DefaultProxySelector after JEP 486 integration

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which removes calls to `SecurityManager` and `AccessController.doPrivileged()` from the `ProxySelector` and `DefaultProxySelector` classes?

Apart from the trivial removing of those calls, the commit in this PR also removes the `getProxySelector` and `setProxySelector` named `NetPermission`s. These 2 named permissions, were previously only documented on the `ProxySelector.getDefault()` and `ProxySelector.setDefault()` methods. With the removal of SecurityManager, the specification of these named properties ceases to exist. Having said that, would removal of these named NetPermission(s) require a CSR linked to this current issue?

The other major chunk of this change is moving the proxy determination logic in `DefaultProxySelector` into a private method from the previous `doPriveleged()` call block.

No new tests have been introduced. Existing tests in tier1 and tier2 continue to pass with this change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344233](https://bugs.openjdk.org/browse/JDK-8344233): Remove calls to SecurityManager and doPrivileged in java.net.ProxySelector and sun.net.spi.DefaultProxySelector after JEP 486 integration (**Sub-task** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22145/head:pull/22145` \
`$ git checkout pull/22145`

Update a local copy of the PR: \
`$ git checkout pull/22145` \
`$ git pull https://git.openjdk.org/jdk.git pull/22145/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22145`

View PR using the GUI difftool: \
`$ git pr show -t 22145`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22145.diff">https://git.openjdk.org/jdk/pull/22145.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22145#issuecomment-2478521376)
</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
> No CSR needed for removing those permissions. There's no visible change to the public APIs, and no behavior change that was not already covered by JEP 486 CSR, since permissions checks have now become deadcode. Or am I missing something?

I believe you are right. The `Permission` classes themselves haven't been deprecated, so I was just curious whether the removal of these named permissions that relate to such classes need to be handled in any specific manner.

**Comment by seanjmullan** [comment]
> > No CSR needed for removing those permissions. There's no visible change to the public APIs, and no behavior change that was not already covered by JEP 486 CSR, since permissions checks have now become deadcode. Or am I missing something?
> 
> I believe you are right. The `Permission` classes themselves haven't been deprecated, so I was just curious whether the removal of these named permissions that relate to such classes need to be handled in any specific manner.

Those permission target names have already been removed from `NetPermission` and were listed as removed in the [JEP 486 CSR](https://bugs.openjdk.org/browse/JDK-8338412) - see the text that starts with "The standard permission target names of several subclasses ...". So no CSR should be needed.

**Comment by jaikiran** [comment]
Thank you Sean, I had missed that part from the JEP 486 CSR.

**Comment by jaikiran** [comment]
There were merge conflicts in this PR in the `SecurityConstants.java` file due to a recent integration in mainline. I've now resolved them and updated this PR.

**Comment by dfuch** [comment]
LGTM

**Review by dfuch — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you Daniel for the review.

**Pull request closed without merging**
