### PR TITLE
8301117: Remove old_size param from ResizeableResourceHashtable::resize()

### PR DESCRIPTION
**Pull request by afshin-zafari**
`old_size` is removed from the function parameters in definitions and calls.
`table_size` is used as old size.
### Test
mach5 tiers 1-5.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301117](https://bugs.openjdk.org/browse/JDK-8301117): Remove old_size param from ResizeableResourceHashtable::resize()

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12635/head:pull/12635` \
`$ git checkout pull/12635`

Update a local copy of the PR: \
`$ git checkout pull/12635` \
`$ git pull https://git.openjdk.org/jdk pull/12635/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12635`

View PR using the GUI difftool: \
`$ git pr show -t 12635`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12635.diff">https://git.openjdk.org/jdk/pull/12635.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Changes look good - thanks.

Seems to me that if anyone ever passed an old_size that was not the current table-size then we would lose part of the table when we grew it!

**Review by coleenp — APPROVED** [review]
Looks good!

**Pull request closed without merging**
