### PR TITLE
8264873: Dependencies: Split ClassHierarchyWalker

### PR DESCRIPTION
**Pull request by iwanowww**
Split ClassHierarchyWalker into ConcreteMethodFinder and ConcreteSubtypeFinder.

Testing:
- [x] hs-tier1 - hs-tier4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264873](https://bugs.openjdk.java.net/browse/JDK-8264873): Dependencies: Split ClassHierarchyWalker

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 071de4cdcd7b4e11f5a29449181a94bc244b0182
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to e38b995cb6293a6e183b034836bc71395be07a7c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3387/head:pull/3387` \
`$ git checkout pull/3387`

Update a local copy of the PR: \
`$ git checkout pull/3387` \
`$ git pull https://git.openjdk.java.net/jdk pull/3387/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3387`

View PR using the GUI difftool: \
`$ git pr show -t 3387`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3387.diff">https://git.openjdk.java.net/jdk/pull/3387.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Tobias.

**Pull request closed without merging**
