### PR TITLE
8296084: javax/swing/JSpinner/4788637/bug4788637.java fails intermittently on a VM

### PR DESCRIPTION
**Pull request by prsadhuk**
Test seems to fail intermittently in ubuntu OCI VM although it passes locally and in other physical system. 
Although I am not able to reproduce it on VM, tried some robot safeguards used in other tests.
Modified tests passed several iterations in couple of OCI VM hosts and other physical systems , link of whose jobs are in JBS
so we can deproblemlist it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296084](https://bugs.openjdk.org/browse/JDK-8296084): javax/swing/JSpinner/4788637/bug4788637.java fails intermittently on a VM

### Reviewers
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11455/head:pull/11455` \
`$ git checkout pull/11455`

Update a local copy of the PR: \
`$ git checkout pull/11455` \
`$ git pull https://git.openjdk.org/jdk pull/11455/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11455`

View PR using the GUI difftool: \
`$ git pr show -t 11455`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11455.diff">https://git.openjdk.org/jdk/pull/11455.diff</a>

</details>

### CODE REVIEW

**Review by TejeshR13 — APPROVED** [review]
Looks fine to me.

**Comment by mrserb** [comment]
The image from the failure handler attached to the issue shows that the screen was locked during test execution, could it be a root cause?

**Comment by prsadhuk** [comment]
> The image from the failure handler attached to the issue shows that the screen was locked during test execution, could it be a root cause?

Lock screen was a known issue with how this lot of OCI VMs are churned but strange thing was it did not affect any other test. We could just deproblemlist it citing this but thought of adding more safeguards and screenshot at actual time of failure to verify, if it fails again for some reason..

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
