### PR TITLE
8210253: Clipped UI rendering with X11 pipeline and HiDPI

### PR DESCRIPTION
**Pull request by mrserb**
The fix for https://bugs.openjdk.java.net/browse/JDK-8137571 where HiDPI support on Linux was implemented missed the change in the X11 pipeline, only XRender pipeline was updated. The same logic should be implemented in X11SurfaceData:

 - The size of the native surface should be scaled based on scale factor, except the TEXTURE type, because it is used for managed(cached) images.

See the old change:
https://github.com/openjdk/jdk/commit/d48c3fcafbf93177919b0e37785a340e0789789b#diff-8e84507066ac1c725caee14aa6a3323b0fb06f2082a33e0c5dbe2c662bdc53ccR545

I hit this bug on my local system, and confirm that this change cures it. mach5 is green.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8210253](https://bugs.openjdk.java.net/browse/JDK-8210253): Clipped UI rendering with X11 pipeline and HiDPI

### Reviewers
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1284/head:pull/1284`
`$ git checkout pull/1284`

### CODE REVIEW

**Comment by mrserb** [comment]
Any volunteers for a review?

**Comment by victordyakov** [comment]
@prsadhuk @kizune please review

**Review by aivanov-jdk — APPROVED** [review]
The changes are similar to Xrender, looks reasonable.

**Review by azuev-java — APPROVED** [review]
Looks ok.

**Pull request closed without merging**
