### PR TITLE
8277353: java/security/MessageDigest/ThreadSafetyTest.java test times out

### PR DESCRIPTION
**Pull request by sisahoo**
This Test gets timeout during low cpu availability. It is modified to support extended timeout period during JTREG execution.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277353](https://bugs.openjdk.java.net/browse/JDK-8277353): java/security/MessageDigest/ThreadSafetyTest.java test times out

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6626/head:pull/6626` \
`$ git checkout pull/6626`

Update a local copy of the PR: \
`$ git checkout pull/6626` \
`$ git pull https://git.openjdk.java.net/jdk pull/6626/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6626`

View PR using the GUI difftool: \
`$ git pr show -t 6626`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6626.diff">https://git.openjdk.java.net/jdk/pull/6626.diff</a>

</details>

### CODE REVIEW

**Comment by wangweij** [comment]
Can you lower the `threadsFactor` or `duration`? Or set an upper limit for `nTasks`?

**Comment by sisahoo** [comment]
> Can you lower the `threadsFactor` or `duration`? Or set an upper limit for `nTasks`?

I can reduce the threadFactor and duration to close to half(threadsFactor=2 and duration=2 Or hardcode nTasks=20) and i think there still will be enough threads to verify threadsafety. In that case default JTREG timeout period should be enough and no need for any additional timeout with @run tag.

**Comment by wangweij** [comment]
> > Can you lower the `threadsFactor` or `duration`? Or set an upper limit for `nTasks`?
> 
> I can reduce the threadFactor and duration to close to half(threadsFactor=2 and duration=2 Or hardcode nTasks=20) and i think there still will be enough threads to verify threadsafety. In that case default JTREG timeout period should be enough and no need for any additional timeout with @run tag.

Maybe you can contact the author of this test to see if that's enough.

**Comment by alexeybakhtin** [comment]
Hi @sisahoo,
Yes, I think the number of threads and duration can be lowered. For example like this:

diff --git a/test/jdk/java/security/MessageDigest/ThreadSafetyTest.java b/test/jdk/java/security/MessageDigest/ThreadSafetyTest.java
index 41ecbca2677..f179bd54257 100644
--- a/test/jdk/java/security/MessageDigest/ThreadSafetyTest.java
+++ b/test/jdk/java/security/MessageDigest/ThreadSafetyTest.java
@@ -25,7 +25,7 @@
  \* @test
  \* @bug 8241960
  \* @summary Confirm that java.security.MessageDigest is thread-safe after clone.
\- \* @run main/othervm ThreadSafetyTest 5 4
\+ \* @run main/othervm ThreadSafetyTest 5 2
  \*/
 
 import java.security.MessageDigest;
@@ -56,7 +56,7 @@ public class ThreadSafetyTest {
             duration = Integer.parseInt(args[1]);
         }
         int nProcessors = Runtime.getRuntime().availableProcessors();
\-        int nTasks = nProcessors * threadsFactor;
\+        int nTasks = Math.min(nProcessors, 4) * threadsFactor;
         System.out.println("Testing with " + nTasks + " threads on " +
                            nProcessors + " processors for " + duration +

**Comment by sisahoo** [comment]
Thanks Alexey, I have updated the threadsFactor=4 and duration=2. With this change the Test is completing ~50 seconds in my laptop which is 50% improvement over original.

**Comment by alexeybakhtin** [comment]
Thank you. Looks good to me, but I'm not a reviewer

**Review by wangweij — APPROVED** [review]
Looks good. Thanks.

**Pull request closed without merging**
