### PR TITLE
8253169: [BACKOUT] Improve large object handling during evacuation

### PR DESCRIPTION
**Pull request by kimbarrett**
Revert "8027545: Improve object array chunking test in G1's copy_to_survivor_space"
Revert "8158045: Improve large object handling during evacuation"
Revert "8027761: Investigate fast-path for scanning only objects with references during gc"

This reverts commit dafcf1056f5cb1772eb61fca9ee46fe24c83fc09.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253169](https://bugs.openjdk.java.net/browse/JDK-8253169): [BACKOUT] Improve large object handling during evacuation

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/181/head:pull/181`
`$ git checkout pull/181`

### CODE REVIEW

**Comment by kimbarrett** [comment]
/summary
Revert "8027545: Improve object array chunking test in G1's copy_to_survivor_space"
Revert "8158045: Improve large object handling during evacuation"
Revert "8027761: Investigate fast-path for scanning only objects with references during gc"

**Comment by kimbarrett** [comment]
Currently doing test builds of all Oracle supported platforms.

**Review by tschatzl — APPROVED** [review]
Looks like a legit backout.

**Review by kstefanj — APPROVED** [review]
Looks good.

**Pull request closed without merging**
