### PR TITLE
8255338: CodeSections are never frozen

### PR DESCRIPTION
**Pull request by cl4es**
CodeSections are never actually frozen, so code for freezing can be removed along with some assertions and guarantees.

A few other minor cleanups, too.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255338](https://bugs.openjdk.java.net/browse/JDK-8255338): CodeSections are never frozen

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 37aca0c21cec03b99ea6810fb43d226f36559c3a
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/834/head:pull/834`
`$ git checkout pull/834`

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good. 

Remove the additional methods I sent, if you like.

**Comment by cl4es** [comment]
> Looks good.

Thanks!

> Remove the additional methods I sent, if you like.

Done.

**Review by vnkozlov — APPROVED** [review]
Good. It was part of original implementation of CodeBuffer. It was used for very short time in C1.

**Comment by cl4es** [comment]
@neliasso @vnkozlov - thank you for reviewing!

/integrate

**Pull request closed without merging**
