### PR TITLE
8332959: C2: ZGC fails with 'Incorrect load shift' when invoking Object.clone() reflectively on an array

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset enforces cloned arrays to be initialized at allocation time when their type is unknown, as expected by ZGC in this scenario (see the [JBS issue](https://bugs.openjdk.org/projects/JDK/issues/JDK-8332959) for further details). Array clones with unknown type may arise from compiling the array-guarded branch of a reflective `Object.clone()` invocation, as illustrated by the included test.

#### Testing
- tier1-5, stress test (windows-x64, linux-x64, linux-aarch64, macosx-x64, macosx-aarch64; release and debug mode).
- tier6-7 (windows-x64, linux-x64, linux-aarch64, macosx-x64, macosx-aarch64; release and debug mode; ZGC tests only).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332959](https://bugs.openjdk.org/browse/JDK-8332959): C2: ZGC fails with 'Incorrect load shift' when invoking Object.clone() reflectively on an array (**Bug** - P3)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)

### Contributors
 * Axel Boldt-Christmas `<aboldtch@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19486/head:pull/19486` \
`$ git checkout pull/19486`

Update a local copy of the PR: \
`$ git checkout pull/19486` \
`$ git pull https://git.openjdk.org/jdk.git pull/19486/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19486`

View PR using the GUI difftool: \
`$ git pr show -t 19486`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19486.diff">https://git.openjdk.org/jdk/pull/19486.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19486#issuecomment-2141225556)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. Great that you were able to come up with a test!

**Comment by robcasloz** [comment]
Thanks for reviewing, Vladimir and Tobias!

**Review by xmas92 — APPROVED** [review]

**Comment by robcasloz** [comment]
Thanks for reviewing (and proposing the fix), Axel!

**Pull request closed without merging**
