### PR TITLE
8302979: (fs) Files usage of SUPPORTED_CHARSETS could be simplified

### PR DESCRIPTION
**Pull request by stsypanov**
Code of `Files.lines()` could be slightly simplified:

- use charsets instead of their names
- use `Set.of()` instead of `HashSet` in `FileChannelLinesSpliterator`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302979](https://bugs.openjdk.org/browse/JDK-8302979): (fs) Files usage of SUPPORTED_CHARSETS could be simplified

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [a4a2b389](https://git.openjdk.org/jdk/pull/12688/files/a4a2b3890ffd4ba1846af38fac443dd2d8398b5e)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12688/head:pull/12688` \
`$ git checkout pull/12688`

Update a local copy of the PR: \
`$ git checkout pull/12688` \
`$ git pull https://git.openjdk.org/jdk pull/12688/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12688`

View PR using the GUI difftool: \
`$ git pr show -t 12688`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12688.diff">https://git.openjdk.org/jdk/pull/12688.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Comment by AlanBateman** [comment]
@stsypanov Can you fix the description to match the JBS issue?

**Comment by stsypanov** [comment]
@AlanBateman done!

**Comment by TheShermanTanker** [comment]
Looks fine to me, doesn't seem like the Set used to store the supported charsets is concerned about having anything added to it, so this should pretty much behave the same as before as Alan said

**Review by TheShermanTanker — APPROVED** [review]
Small nit before sponsoring, perhaps when initializing `SUPPORTED_CHARSETS`, have the charset instances use an indentation of 4 spaces instead of 8

**Comment by stsypanov** [comment]
@TheShermanTanker done!

**Comment by TheShermanTanker** [comment]
Alright, thanks for the fixes :)

**Review by TheShermanTanker — APPROVED** [review]

**Pull request closed without merging**
