### PR TITLE
8282860: Write a regression test for JDK-4164779

### PR DESCRIPTION
**Pull request by manukumarvs**
Write a regression test for [JDK-4164779](https://bugs.openjdk.java.net/browse/JDK-4164779) : JSplitPane keyboard navigation does not support F6 and Ctrl+Tab

Issue:
The specified keyboard support for JSplitPane also requires F6 and Ctrl+Tab (navigate out) for the JSplitPane. Those are currently not implemented.

F6 is supposed to move the focus from the current focused component on one side of the JSplitPane to the other side of the JSplitPane without having to tab through to that.

Ctrl+Tab is supposed to move the input focus from whatever component inside the JSplitPane that has the focus to the next component outside the JSplitPane.

Testing:
Java 1.4.0 -> Test Failed.
$ ./j2sdk1.4.0/bin/java JSplitPaneTest
Verifier 1 failed
Verifier 2 failed
Verifier 3 failed
Verifier 4 failed
Test Failed.

Java 1.4.1 -> Test Passed.
$ ./j2sdk1.4.1/bin/java JSplitPaneTest
Verifier 1 passed
Verifier 2 passed
Verifier 3 passed
Verifier 4 passed
Test Passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282860](https://bugs.openjdk.java.net/browse/JDK-8282860): Write a regression test for JDK-4164779

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7801/head:pull/7801` \
`$ git checkout pull/7801`

Update a local copy of the PR: \
`$ git checkout pull/7801` \
`$ git pull https://git.openjdk.java.net/jdk pull/7801/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7801`

View PR using the GUI difftool: \
`$ git pr show -t 7801`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7801.diff">https://git.openjdk.java.net/jdk/pull/7801.diff</a>

</details>

### CODE REVIEW

**Review by mrserb — APPROVED** [review]
Looks fine. I assume that mach5 is green

**Comment by manukumarvs** [comment]
> * JDK-8282860

Yes @mrserb, tested 10 times each in macos,windows and linux platforms using mach5 and got all pass.

**Pull request closed without merging**
