### PR TITLE
8255072: [TESTBUG] com/sun/jdi/EATests.java should not fail if expected VMOutOfMemoryException is not thrown

### PR DESCRIPTION
**Pull request by reinrich**
The following test cases try to provoke VMOutOfMemoryException during object reallocation because of JVMTI PopFrame / ForceEarlyReturn:

EAPopFrameNotInlinedReallocFailure
EAPopInlinedMethodWithScalarReplacedObjectsReallocFailure
EAForceEarlyReturnOfInlinedMethodWithScalarReplacedObjectsReallocFailure

For ZGC (so far) this is not 100% reliable.

Just ignoring the runs where the expected OOME was not raised was not accepted.

Summary of the now accepted solution:

- The 3 problematic test cases are skipped if ZGC is selected.

- They are also skipped if no OOME during object reallocation can be expected because allocations are not eliminated.

- In consumeAllMemory, as a last step, empty LinkedList nodes are created without long array to fill up small blocks of free memory.

- EATests.java is removed from the problem list for ZGC.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (hs/tier1 compiler)](https://github.com/reinrich/jdk/runs/1327612620)

### Issue
 * [JDK-8255072](https://bugs.openjdk.java.net/browse/JDK-8255072): [TESTBUG] com/sun/jdi/EATests.java should not fail if expected VMOutOfMemoryException is not thrown

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to 33ceb741a83388e2580f5843ebf81e50ff59414a
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to 33ceb741a83388e2580f5843ebf81e50ff59414a
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/775/head:pull/775`
`$ git checkout pull/775`

### CODE REVIEW

**Comment by plummercj** [comment]
If the test does not throw OOME, has it actually tested anything in that case? My concern with any test that allows for what is suppose to be an occasional failure it that it will not detect if something breaks and causes that failure to happen every time, often rendering the test useless.

**Comment by reinrich** [comment]
> If the test does not throw OOME, has it actually tested anything in that
> case?

If an OOME is expected then it has tested object reallocation in frames affected
by PopFrame/ForceEarlyReturn.

But there are runs where OOME is not expected. I added a new commit which skips
the test cases then.

> My concern with any test that allows for what is suppose to be an
> occasional failure it that it will not detect if something breaks and causes
> that failure to happen every time, often rendering the test useless.

I can follow that concern. My problem is that I cannot reproduce the
failure. Note also that the OOME is successfully generated during object
reallocation a couple of times before (search "run args" in attachments
to the JBS issue).

I'd think the approach to prove the OOME during the PopFrame/ForceEarlyReturn
[1] is relatively reliable knowing how smart GCs try to be with avoiding it.

I've tried to make it even more reliable with a second commit in this pr.

Would that be ok? Maybe you would know a better way?

Thanks, Richard.

[1] https://github.com/openjdk/jdk/blob/7e2640432bf4fb5115c2ff694c09937234e6d1c5/test/jdk/com/sun/jdi/EATests.java#L1089

**Comment by plummercj** [comment]
I'm not following how the introduction of LinkedListOfLongArrays is making the OOME even more reliable. Can you please elaborate?

Is consumeAllMemory() being called from a different thread than the one doing the forceEarlyReturn? If so, you might be running into an issue because the tlab still has available memory to allocate.

**Comment by dcubed-ojdk** [comment]
@reinrich - when your reviewers have agreed to a fix, please remove the
ProblemListing that I did via: https://github.com/openjdk/jdk/pull/787

**Comment by reinrich** [comment]
> 
> 
> I'm not following how the introduction of LinkedListOfLongArrays is making the OOME even more reliable. Can you please elaborate?

The new LinkedListOfLongArrays is created by renaming LinkedList to
LinkedListOfLongArrays. The new LinkedList is a list node without payload, so it
is smaller than a LinkedListOfLongArrays node. I try to fill the last free
blocks with these. But yeah, this won't make that much of a difference.

> Is consumeAllMemory() being called from a different thread than the one doing
> the forceEarlyReturn? If so, you might be running into an issue because the
> tlab still has available memory to allocate.

Yes, the threads are different (well observed :)). As far as I know tlabs are
retired before gc. I'd expect that they are allocated lazily. So the jdwp agent
thread that does the forceEarlyReturn should not have a tlab at hand. Certainly
these are just assumptions. It would be easy to implement the gc interface(*)
with different heuristics.

(*) Roman Kennke and Aleksey Shipilev demo'ed implementing the gc interface in a
FOSDEM talk.

**Comment by reinrich** [comment]
> 
> 
> @reinrich - when your reviewers have agreed to a fix, please remove the
> ProblemListing that I did via: #787

I will. Thanks for doing it.

**Comment by plummercj** [comment]
> The new LinkedListOfLongArrays is created by renaming LinkedList to
> LinkedListOfLongArrays. The new LinkedList is a list node without payload, so it
> is smaller than a LinkedListOfLongArrays node. I try to fill the last free
> blocks with these. But yeah, this won't make that much of a difference.

Ok. However, since you can't reproduce the initial problem it's hard to say if this will fix it. You would need to remove it from the problem list with this PR and see what happens.

Earlier you said:

> Note also that the OOME is successfully generated during object
> reallocation a couple of times before (search "run args" in attachments
> to the JBS issue).

So I suppose in that case it's ok if this one test case allows for no OOME just as long as other test cases still require it.

**Comment by reinrich** [comment]
> Earlier you said:
> 
> > Note also that the OOME is successfully generated during object
> > reallocation a couple of times before (search "run args" in attachments
> > to the JBS issue).
> 
> So I suppose in that case it's ok if this one test case allows for no OOME just as long as other test cases still require it.

With that I wanted to state that the probability to get the OOME is not too bad
for meaningful testing. It should be the same for the 3 test cases.

What about repeating a test case if the expected OOME is not raised and let it
fail after 10x retries?

**Comment by reinrich** [comment]
You mentioned the possibility that the OOME is not thrown because it is another thread that consumes all memory than the one calling forceEarlyReturn() which is supposed to fail with OOME. TLAB could be an issue then. In general GC could have a heuristic in place to raise OOME in greedy threads when another thread would still be able to allocate successfully. I think I could change the debugger part to call consumeAllMemory() in the debuggee. This should be executed in the same jdwp agent thread as the later forceEarlyReturn.

But honestly I don't think it is worth it and I cannot even test if it fixes the issues. I'd prefer to skip the 3 test cases if running with ZGC. Please let me know what you prefer.

**Comment by plummercj** [comment]
> But honestly I don't think it is worth it and I cannot even test if it fixes the issues. I'd prefer to skip the 3 test cases if running with ZGC. Please let me know what you prefer.

That's one option if this only happens with ZGC. You also mentioned doing retries. I would only suggest that if you think you can limit the chances of the OOME not happening to be so unlikely that we are no likely to ever see it happen.

**Comment by reinrich** [comment]
With the last commit the combined change is

- The 3 problematic test cases are skipped if ZGC is selected.

- They are also skipped if no OOME during object reallocation can be expected
  because allocations are not eliminated.

- In consumeAllMemory, as a last step, empty LinkedList nodes are created
  without long array to fill up small blocks of free memory.

- EATests.java is removed from the problem list for ZGC.

**Review by plummercj — APPROVED** [review]
Looks good.

**Comment by reinrich** [comment]
> 
> 
> Looks good.

Thank you. I'll wait for a second review assuming it's required.

**Comment by plummercj** [comment]
> Thank you. I'll wait for a second review assuming it's required.

You might want to add the compiler and/or gc teams to the review

**Comment by reinrich** [comment]
Following @plummercj advice to add compiler/gc teams.

/label hotspot-gc hotspot-compiler

**Review by sspitsyn — APPROVED** [review]
Hi Richard,
It looks good to me.
One nit:
```
     public static final boolean DoEscapeAnalysis     = unbox(WB.getBooleanVMFlag("DoEscapeAnalysis"), UseJVMCICompiler);
     public static final boolean EliminateAllocations = unbox(WB.getBooleanVMFlag("EliminateAllocations"), UseJVMCICompiler); // read by debugger
     public static final boolean DeoptimizeObjectsALot   = WB.getBooleanVMFlag("DeoptimizeObjectsALot");                      // read by debugger
     public static final long BiasedLockingBulkRebiasThreshold = WB.getIntxVMFlag("BiasedLockingBulkRebiasThreshold");
     public static final long BiasedLockingBulkRevokeThreshold = WB.getIntxVMFlag("BiasedLockingBulkRevokeThreshold");
+    public static final boolean ZGCIsSelected        = GC.Z.isSelected();
```
There are unneeded spaces before '=' sign.

Thanks,
Serguei

**Comment by reinrich** [comment]
Hi Serguei,

thanks for reviewing. I'll remove the whitespace.

I'm able now to reproduce the issue but only with ZGC. So far my attempts(*) to reliably get the OOME during ForceEarlyReturn/PopFrame because of object reallocation failed though. So I'm still in favour of the current solution which is: skip the 3 problematic testcases if ZGC is selected in the target vm. I'm still open for suggestions also though. I'll wait a few more days and then I'll integrate.

Thanks, Richard.

(*) I tried:

- disable TLAB
- call WhiteBox.fullGC() in consumeAllMemory() before the last round of allocations.
- Check if the memory can be allocated by the thread doing the PopFrame/ForceEarlyReturn. com.sun.jdi.ThreadReference::invokeMethod() cannot be used. A target thread has to be specified and the jdwp threads are not visible through jdi. Only a dedicated native test JVMTI agent can consume all memory and then do the PopFrame/ForceEarlyReturn.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Please change @requires for testing with Graal to `vm.graal.enabled` instead of `vm.jvmci`

**Comment by reinrich** [comment]
> 
> 
> Please change @requires for testing with Graal to `vm.graal.enabled` instead of `vm.jvmci`

Sure. I've done that now.

**Review by vnkozlov — APPROVED** [review]
Good

**Comment by reinrich** [comment]
> Good

Thanks for reviewing. Will integrate beginning of next week.

**Pull request closed without merging**
