### PR TITLE
JDK-8280583: Always build NMT

### PR DESCRIPTION
**Pull request by tstuefe**
After discussing this on hotspot-runtime-dev [1], the general opinion seems to be that it would be worthwhile to get rid of INCLUDE_NMT and make NMT unconditional. This affects minimal builds only. As pointed out in the mail thread, the overhead is very small and it would get rid of one configuration to build and test.

[1] https://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2022-January/053504.html

Patch removes INCLUDE_NMT from hotspot, as well as dependent macros, as well as the associated build option.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280583](https://bugs.openjdk.java.net/browse/JDK-8280583): Always build NMT

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7213/head:pull/7213` \
`$ git checkout pull/7213`

Update a local copy of the PR: \
`$ git checkout pull/7213` \
`$ git pull https://git.openjdk.java.net/jdk pull/7213/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7213`

View PR using the GUI difftool: \
`$ git pr show -t 7213`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7213.diff">https://git.openjdk.java.net/jdk/pull/7213.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
There is some major weirdness in this PR: it includes a lot of unrelated changes. Consider rebasing to current master and force-pushing?

**Comment by tstuefe** [comment]
> There is some major weirdness in this PR: it includes a lot of unrelated changes. Consider rebasing to current master and force-pushing?

Done.

I wondered about that, I did merge master - normally, this shows up as a single merge change. Not sure what happened.

**Review by shipilev — APPROVED** [review]
This looks fine to me.

**Comment by tstuefe** [comment]
> This looks fine to me.

Thanks, Aleksey!

**Review by magicus — APPROVED** [review]
Build changes look fine. Good riddance!

**Review by zhengyu123 — APPROVED** [review]
Good to me.

**Comment by tstuefe** [comment]
Thanks @shipilev, @magicus and @zhengyu123 !

/integrate

**Pull request closed without merging**
