### PR TITLE
8255067: Restore Copyright line in file modified by 8253191

### PR DESCRIPTION
**Pull request by iwanowww**
Make it crystal clear that  8253191 test case doesn't have anything in common with the original version of the test case for 8204479:
  * restore original test case
  * add 8253191 test case as a separate file

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ❌ (3/5 failed) | ✔️ (2/2 passed) | ❌ (1/2 failed) |
| Test (tier1) |    |  ❌ (2/9 failed) |    | 

**Failed test tasks**
- [Linux x64 (build debug)](https://github.com/iwanowww/jdk/runs/1282874535)
- [Linux x64 (build hotspot zero)](https://github.com/iwanowww/jdk/runs/1282874598)
- [Linux x64 (build release)](https://github.com/iwanowww/jdk/runs/1282874514)
- [Windows x64 (jdk/tier1 part 1)](https://github.com/iwanowww/jdk/runs/1283148434)
- [Windows x64 (jdk/tier1 part 3)](https://github.com/iwanowww/jdk/runs/1283148467)
- [macOS x64 (build debug)](https://github.com/iwanowww/jdk/runs/1282874420)

### Issue
 * [JDK-8255067](https://bugs.openjdk.java.net/browse/JDK-8255067): Restore Copyright line in file modified by 8253191

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/771/head:pull/771`
`$ git checkout pull/771`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by shipilev — APPROVED** [review]
Looks good, but maybe call the new test `TestUnsignedByteCompare2`? The other test is kinda "first".

**Pull request closed without merging**
