### PR TITLE
8276795: Deprecate seldom used CDS flags

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small change to deprecate seldom used CDS flags.  The flags will be deprecated in 18, obsoleted in 19, and removed in a later release.

The changes were tested with Mach5 tiers 1-2 on Linux, Mac OS, and Windows, and Mach5 tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276795](https://bugs.openjdk.java.net/browse/JDK-8276795): Deprecate seldom used CDS flags

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6390/head:pull/6390` \
`$ git checkout pull/6390`

Update a local copy of the PR: \
`$ git checkout pull/6390` \
`$ git pull https://git.openjdk.java.net/jdk pull/6390/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6390`

View PR using the GUI difftool: \
`$ git pr show -t 6390`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6390.diff">https://git.openjdk.java.net/jdk/pull/6390.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Hi Harold,

You also need to add "(Deprecated)" to the description of these flags in globals.hpp.

You should also add these flags to the VMDeprecatedOptions.java test.

Thanks,
David

**Comment by hseigel** [comment]
David, thanks for looking at this change.  Please review the updated commit. It contains the needed additional changes that you pointed out.
Thanks, Harold

**Review by calvinccheung — APPROVED** [review]
LGTM.

**Review by iklam — APPROVED** [review]
LGTM

**Review by dholmes-ora — APPROVED** [review]
Sorry for the delay - updates look good.

Thanks,
David

**Comment by hseigel** [comment]
Thanks Calvin, Ioi, and David for the reviews.

/integrate

**Pull request closed without merging**
