### PR TITLE
8344647: Make java.se participate in the preview language feature `requires transitive java.base`

### PR DESCRIPTION
**Pull request by lahodaj**
There is a new preview language feature, `requires transitive java.base;`. And the `java.se` module is permitted to use the feature, without being marked as preview (i.e. the `java.se` module participates in preview). This is currently implemented by the common "participates in preview" way, by checking that `java.base` is exporting `jdk.internal.javac` package to `java.se`.

This common way works OK for internal preview feature and API usage, but turns out it may not be appropriate for this feature: the qualified export of the `jdk.internal.javac` package is not a specified API, it is an implementation detail; and the JLS itself specifies that the `java.se` module is participating in preview.

So this PR proposes to change the way javac handles the `java.se` module: it permits the use of the preview feature based on the module name, instead relying on the internal qualified export.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344647](https://bugs.openjdk.org/browse/JDK-8344647): Make java.se participate in the preview language feature `requires transitive java.base` (**Bug** - P3)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22322/head:pull/22322` \
`$ git checkout pull/22322`

Update a local copy of the PR: \
`$ git checkout pull/22322` \
`$ git pull https://git.openjdk.org/jdk.git pull/22322/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22322`

View PR using the GUI difftool: \
`$ git pr show -t 22322`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22322.diff">https://git.openjdk.org/jdk/pull/22322.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22322#issuecomment-2493809310)
</details>

### CODE REVIEW

**Comment by cushon** [comment]
LGTM, thanks!

I verified this fixes the original issue I was seeing.

**Review by asotona — APPROVED** [review]
Looks good to me.
JEP 494 puts java.se into a special position related to the preview participation and that position should not depend on java.base internal annotation.

**Review by jddarcy — APPROVED** [review]

**Comment by lahodaj** [comment]
Thanks for the reviews!

**Pull request closed without merging**
