### PR TITLE
8283794: CCE in XRTextRenderer.drawGlyphList and XRMaskFill.MaskFill

### PR DESCRIPTION
**Pull request by avu**
Throwing InvalidPipeException for incompatible surfaces

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283794](https://bugs.openjdk.java.net/browse/JDK-8283794): CCE in XRTextRenderer.drawGlyphList and XRMaskFill.MaskFill

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to d9a132efe331ec0c00ae6b4bf87da9ac34e45420
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8015/head:pull/8015` \
`$ git checkout pull/8015`

Update a local copy of the PR: \
`$ git checkout pull/8015` \
`$ git pull https://git.openjdk.java.net/jdk pull/8015/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8015`

View PR using the GUI difftool: \
`$ git pr show -t 8015`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8015.diff">https://git.openjdk.java.net/jdk/pull/8015.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Since this is the third cast-related issue then probably it will be useful to create a method to convert the `surfaceData `to the (XRSurfaceData) and throw `InvalidPipeException `if needed? We have many other places where we use the same casts.

**Comment by avu** [comment]
> Since this is the third cast-related issue then probably it will be useful to create a method to convert the `surfaceData `to the (XRSurfaceData) and throw `InvalidPipeException `if needed? We have many other places where we use the same casts.

Yes, agree. Also, I think we need to update similar cases in MTLRenderer, MTLMaskFill, OGLMaskFill, OGLRenderer, XRPMBlitLoops, D3DMaskFill, D3DRenderer, GDIRenderer.

The conversion can be done using generics in SurfaceData:
SurfaceData.convertTo(XRSurfaceData.class, sg2d.surfaceData);

or by providing separate conversion methods for each  SurfaceData subclass
XRSurfaceData x11sd = XRSurfaceData.toXRSurfaceData(sData);

**Comment by avu** [comment]
> Yes, agree. Also, I think we need to update similar cases in MTLRenderer, MTLMaskFill, OGLMaskFill, OGLRenderer, XRPMBlitLoops, D3DMaskFill, D3DRenderer, GDIRenderer.
> 
> The conversion can be done using generics in SurfaceData:
> SurfaceData.convertTo(XRSurfaceData.class, sg2d.surfaceData);
> 

Implemented a more compact solution via generics.

**Review by mrserb — APPROVED** [review]
Looks fine, I suggest checking the fix via mach5. @aghaisas please take a look.

**Comment by avu** [comment]
@aghaisas could you please help with running the necessary tests.

**Comment by aghaisas** [comment]
I am on vacation this week. I will review this PR on priority next week.

**Comment by avu** [comment]
Thank you very much @aghaisas !

**Comment by aghaisas** [comment]
> Looks fine, I suggest checking the fix via mach5. @aghaisas please take a look.

The fix looks good. Also, the mach5 run is green with this change.
@avu, is it possible to add an automated test?

**Comment by avu** [comment]
@aghaisas actually we have one test/jdk/sun/java2d/ClassCastExceptionForInvalidSurface.java

**Review by aghaisas — APPROVED** [review]

**Pull request closed without merging**
