### PR TITLE
8318964: Fix build failures caused by 8315097

### PR DESCRIPTION
**Pull request by lkorinth**
Update method name after huge renaming conflict

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318964](https://bugs.openjdk.org/browse/JDK-8318964): Fix build failures caused by 8315097 (**Enhancement** - P4)

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16395/head:pull/16395` \
`$ git checkout pull/16395`

Update a local copy of the PR: \
`$ git checkout pull/16395` \
`$ git pull https://git.openjdk.org/jdk.git pull/16395/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16395`

View PR using the GUI difftool: \
`$ git pr show -t 16395`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16395.diff">https://git.openjdk.org/jdk/pull/16395.diff</a>

</details>

### CODE REVIEW

**Review by xmas92 — APPROVED** [review]

**Comment by xmas92** [comment]
Trivial fix.

**Review by robcasloz — APPROVED** [review]
Looks good and trivial.

**Comment by lkorinth** [comment]
Thanks!!!

**Pull request closed without merging**
