### PR TITLE
8294954: Remove superfluous ResourceMarks when using LogStream

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

I went through all of the places where LogStreams are created and removed the unnecessary ResourceMarks. I also added a ResourceMark in one place, where it was needed because of a call to `::name_and_sig_as_C_string` and moved one to the smallest scope where it is used.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294954](https://bugs.openjdk.org/browse/JDK-8294954): Remove superfluous ResourceMarks when using LogStream

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10602/head:pull/10602` \
`$ git checkout pull/10602`

Update a local copy of the PR: \
`$ git checkout pull/10602` \
`$ git pull https://git.openjdk.org/jdk pull/10602/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10602`

View PR using the GUI difftool: \
`$ git pr show -t 10602`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10602.diff">https://git.openjdk.org/jdk/pull/10602.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
How are you defining "unnecessary"? Are these unnecessary because there is zero resource allocation involved? Or "unnecessary" because a ResourceMark higher up the call stack covers it?

**Comment by dholmes-ora** [comment]
I see now the bug report suggests these RM were in place because the stream itself may have needed them but that this is no longer the case. So was that the only reason for all these RMs?

**Comment by jdksjolen** [comment]
>I see now the bug report suggests these RM were in place because the stream itself may have needed them but that this is no longer the case. So was that the only reason for all these RMs?

There are RMs that I've looked at but left intact because they did have other reasons for being there (typically: string allocating functions). So yes, `LogStream` should be the only reason for all these RMs.

**Comment by jdksjolen** [comment]
This PR does remove the RM in `VM_Operation::evaluate`, and I haven't checked all of the VM operations to see if anyone uses it.

**Comment by jdksjolen** [comment]
I put back the ResourceMark in `VM_Operation::evaluate` as looking through each VM Operation for unprotected resource usage is infeasible.

**Pull request closed without merging**
