### PR TITLE
JDK-8320054: Remove unused _count from NMT walker classes

### PR DESCRIPTION
**Pull request by tstuefe**
Trivial cleanup of unused code, found by @gerard-ziemski while reviewing https://github.com/openjdk/jdk/pull/16480

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320054](https://bugs.openjdk.org/browse/JDK-8320054): Remove unused _count from NMT walker classes (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16653/head:pull/16653` \
`$ git checkout pull/16653`

Update a local copy of the PR: \
`$ git checkout pull/16653` \
`$ git pull https://git.openjdk.org/jdk.git pull/16653/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16653`

View PR using the GUI difftool: \
`$ git pr show -t 16653`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16653.diff">https://git.openjdk.org/jdk/pull/16653.diff</a>

</details>

### CODE REVIEW

**Review by jdksjolen — APPROVED** [review]
LGTM and trivial.

**Review by gerard-ziemski — APPROVED** [review]
LGTM thank you for fixing this.

**Comment by tstuefe** [comment]
Uff, you guys are fast. :-)

Thanks @jdksjolen and @gerard-ziemski

**Pull request closed without merging**
