### PR TITLE
8329718: Incorrect `@since` tags in elements in jdk.compiler and java.compiler

### PR DESCRIPTION
**Pull request by nizarbenalla**
This PR aims to add `@since` tags in elements in both `jdk.compiler` and `java.compiler`.
A lot of these changes have to do with handling of preview features.

The existing rules for handling of `@since` for preview elements:
- When an element is still marked as preview, the `@since` should be the first JDK release where the element was added.
- If the element is no longer marked as preview, the `@since` should be the first JDK release where it was no longer preview.

It is tricky to check these, the way preview elements were annotated before the inroduction of `@Previewfeature` in JDK 17:
- in jdk 12-13 they were annotated with `@Deprecated(forRemoval=true, since=...)`
- in jdk 14-15 they were annotated with `@jdk.internal.preview` or with `{@preview Associated with ....` in the `javadoc` comment

If you're reviewing these changes, Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329718](https://bugs.openjdk.org/browse/JDK-8329718): Incorrect `@<!---->since` tags in elements in jdk.compiler and java.compiler (**Sub-task** - P4)

### Reviewers
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to [558abe6e](https://git.openjdk.org/jdk/pull/18972/files/558abe6edfc3b38cbee8275e71e050def93e6489)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**) ⚠️ Review applies to [558abe6e](https://git.openjdk.org/jdk/pull/18972/files/558abe6edfc3b38cbee8275e71e050def93e6489)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18972/head:pull/18972` \
`$ git checkout pull/18972`

Update a local copy of the PR: \
`$ git checkout pull/18972` \
`$ git pull https://git.openjdk.org/jdk.git pull/18972/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18972`

View PR using the GUI difftool: \
`$ git pr show -t 18972`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18972.diff">https://git.openjdk.org/jdk/pull/18972.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18972#issuecomment-2090902310)

### CODE REVIEW

**Review by jddarcy — APPROVED** [review]
The java.compiler changes looks fine.

**Comment by nizarbenalla** [comment]
Thanks Joe

**Review by jonathan-gibbons — COMMENTED** [review]
`jdk.compiler` changes look OK

**Review by jonathan-gibbons — APPROVED** [review]

**Comment by nizarbenalla** [comment]
I did an other pass over these and I made a small change to `visitYield`, it went out of preview in JDK 14, not JDK 15. I hope it's fine.

Here it is[ in preview](https://github.com/openjdk/jdk13/blob/dcd4014cd8a6f49a564cbb95387ad01a80a20bed/src/jdk.compiler/share/classes/com/sun/source/tree/TreeVisitor.java#L573)
Here it is [out of preview](https://github.com/openjdk/jdk14/blob/abc56193174dd6a11a8453bd5036fc8618ecca61/src/jdk.compiler/share/classes/com/sun/source/tree/TreeVisitor.java#L576)

/integrate

**Pull request closed without merging**
