### PR TITLE
8280241: (aio) AsynchronousSocketChannel init fails in IPv6 only Windows env

### PR DESCRIPTION
**Pull request by djelinski**
When IPv4 is disabled on a Windows system, `socket(AF_INET,...)` calls fail with `WSAEAFNOSUPPORT`.
The socket is only needed to retrieve the address of ConnectEx method, and an IPv6 socket serves that purpose equally well.

The patch was verified on a Windows 10 machine with IPv4 disabled using `netsh interface ipv4 uninstall`. Some tests are still failing, but `TestAsyncSocketChannels` is passing now.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280241](https://bugs.openjdk.java.net/browse/JDK-8280241): (aio) AsynchronousSocketChannel init fails in IPv6 only Windows env

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7197/head:pull/7197` \
`$ git checkout pull/7197`

Update a local copy of the PR: \
`$ git checkout pull/7197` \
`$ git pull https://git.openjdk.java.net/jdk pull/7197/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7197`

View PR using the GUI difftool: \
`$ git pr show -t 7197`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7197.diff">https://git.openjdk.java.net/jdk/pull/7197.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM. Could you please add `8280241` to the `@bug` list in `java/foreign/channels/TestAsyncSocketChannels.java` - and update the copyright years in the modified files if needed?

**Comment by AlanBateman** [comment]
> Could you please add `8280241` to the `@bug` list in `java/foreign/channels/TestAsyncSocketChannels.java` - and update the copyright years in the modified files if needed?

I would expect all tests that use AsynchronousSocketChannel to fail when IPv4 is disabled, I assume it's not specific to this test.

**Comment by djelinski** [comment]
> > Could you please add `8280241` to the `@bug` list in `java/foreign/channels/TestAsyncSocketChannels.java` - and update the copyright years in the modified files if needed?
> 
> I would expect all tests that use AsynchronousSocketChannel to fail when IPv4 is disabled, I assume it's not specific to this test.

That's correct. `TestAsyncSocketChannels` is just the only tier1 test that uses `AsynchronousSocketChannel`.

**Review by AlanBateman — APPROVED** [review]

**Comment by djelinski** [comment]
Updated the copyright dates. @dfuch please confirm if you still want me to add the bug ID to the test.

**Review by dfuch — APPROVED** [review]
LGTM. The test will only verify your changes if IPv4 is disabled - and I see Alan has marked the issue as noreg-hard so I'm OK with not updating the `@bug` list in the test. I can sponsor the change if you integrate it.

**Pull request closed without merging**
