### PR TITLE
8294068: Unconditional and eager load of nio library since JDK-8264744

### PR DESCRIPTION
**Pull request by bplb**
Move `LinuxFileSystem` native code to `LinuxNativeDispatcher`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294068](https://bugs.openjdk.org/browse/JDK-8294068): Unconditional and eager load of nio library since JDK-8264744

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10362/head:pull/10362` \
`$ git checkout pull/10362`

Update a local copy of the PR: \
`$ git checkout pull/10362` \
`$ git pull https://git.openjdk.org/jdk pull/10362/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10362`

View PR using the GUI difftool: \
`$ git pr show -t 10362`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10362.diff">https://git.openjdk.org/jdk/pull/10362.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Moving it to LinuxNativeDispatcher is better so I think the change is okay. That said, libnio will likely be loaded early in any significant program.

**Review by cl4es — APPROVED** [review]
LGTM

**Comment by YuHui936** [comment]
Files.copy() fails with EOPNOTSUPP on NFS when copy_file_range is unsupported by kernel

Detailed Description
**Environment:**
 - JDK Version: OpenJDK 21.0.3 
 - OS: Alpine Linux 3.20 (kernel 3.10) 
 - Filesystem: NFS 
 - Glibc: 2.36 (supports `copy_file_range` syscall) 
 - Container Environment: Alpine 3.20 with kernel 3.10 (lacks `copy_file_range` support)  
 **Problem:** When invoking `Files.copy(Path, Path, CopyOption)` on an NFS filesystem, the operation fails with:   
 `java.io.IOException: Operation not supported` due to error code `EOPNOTSUPP`.  
 **Root Cause Analysis:** 
 - JDK 21's `LinuxNativeDispatcher.directCopy0` attempts to use the `copy_file_range` syscall.   
 - The NFS driver in older kernels (e.g., 3.10) returns `EOPNOTSUPP` (indicating unsupported operation).   
 - JDK currently handles `EINVAL`, `ENOSYS`, and `EXDEV` by falling back to `sendfile64`, but **ignores `EOPNOTSUPP`**, leading to an unchecked exception.    **Expected Behavior:**   JDK should RESTARTABLE to `sendfile64`  when encountering `EOPNOTSUPP`.  
 **Steps to Reproduce:** 
 1. Mount an NFS filesystem in an Alpine 3.20 container (kernel 3.10).   
 2. Run the following Java code with JDK 21:      ```java    Path src = Path.of("/nfs/src.txt");    Path dst = Path.of("/nfs/dst.txt");    Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING); 
 3. Observe the exception:     java.io.IOException: Operation not supported         at java.base/sun.nio.fs.LinuxNativeDispatcher.directCopy0(Native Method)         ... (full stack trace)

Additional Context
Attach the full exception stack trace (provided in the problem description). Relevant kernel code snippet (from nfs42_proc_copy):     if (!nfs_server_capable(file_inode(dst), NFS_CAP_COPY))         return -EOPNOTSUPP; // Kernel returns EOPNOTSUPP for unsupported copy

Suggested Fix
Extend error handling in directCopy0 to catch EOPNOTSUPP.

**Pull request closed without merging**
