### PR TITLE
JDK-8297911: Memory leak in JfrUpcalls::on_retransform

### PR DESCRIPTION
**Pull request by jcking**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297911](https://bugs.openjdk.org/browse/JDK-8297911): Memory leak in JfrUpcalls::on_retransform

### Reviewers
 * [Markus Grönlund](https://openjdk.org/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11445/head:pull/11445` \
`$ git checkout pull/11445`

Update a local copy of the PR: \
`$ git checkout pull/11445` \
`$ git pull https://git.openjdk.org/jdk pull/11445/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11445`

View PR using the GUI difftool: \
`$ git pr show -t 11445`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11445.diff">https://git.openjdk.org/jdk/pull/11445.diff</a>

</details>

### CODE REVIEW

**Comment by jcking** [comment]
Waiting on another test run to verify I got the memory leak. I think the approach is correct, but I need an adult to confirm.

**Comment by jcking** [comment]
> Waiting on another test run to verify I got the memory leak.

Test run looks good, no more leak.

**Comment by mgronlun** [comment]
Hi Justin, thanks for bringing this to our attention.
I wrote a note in the JIRA issue and am currently investigating.

**Review by mgronlun — APPROVED** [review]
Looks good, thanks for fixing this.

**Pull request closed without merging**
