### PR TITLE
8335136: Underscore as parameter name in one-parameter functional types fails to compile

### PR DESCRIPTION
**Pull request by Evemose**
Seems like this bug been around for quite a bunch of time now. Basically, in JavacParser, UNDERSCORE case havent been present in block parsing switch statement, so it was treated as default and it wasnt recognized as part of yield statement. This simple fix adds UNDERSCORE case right next to IDENTIFIER case to solve this problem. Syntax like yield _ = 3 is still invalid.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335136](https://bugs.openjdk.org/browse/JDK-8335136): Underscore as parameter name in one-parameter functional types fails to compile (**Bug** - P4)

### Reviewers
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19878/head:pull/19878` \
`$ git checkout pull/19878`

Update a local copy of the PR: \
`$ git checkout pull/19878` \
`$ git pull https://git.openjdk.org/jdk.git pull/19878/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19878`

View PR using the GUI difftool: \
`$ git pr show -t 19878`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19878.diff">https://git.openjdk.org/jdk/pull/19878.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19878#issuecomment-2191255114)

### CODE REVIEW

**Comment by lahodaj** [comment]
Hi,

the change looks sensible to me, thanks. A test will be needed, though. One possible location for the test may be `test/langtools/tools/javac/switchexpr/ExpressionSwitch.java`.

**Comment by Evemose** [comment]
> Hi,
> 
> the change looks sensible to me, thanks. A test will be needed, though. One possible location for the test may be `test/langtools/tools/javac/switchexpr/ExpressionSwitch.java`.

I have added testcase, but in separate class. As described in ExpressionSwitch, this class specializes on testing behaviour of nexted switch expresssions, and also all of them are valid by default. So i decided to create new class, and also added some negative tests for underscore after yield as it is now a valid follow-up token, so it will guard from unexpected bugs in javac related to underscore in yield from now on. Also, now or test to run I have added random bug id, because itherwise runner wont start. I have added a TODO to replace it with actual one when the issue is published

PS: I have tried to use record patterns in for loop, but compilation of test failed for some reason. Not surew if its expected behaviour or not.

**Comment by Evemose** [comment]
@lahodaj could you review pls?

**Review by lahodaj — APPROVED** [review]
Looks good to me, thanks!

**Pull request closed without merging**
