### PR TITLE
8278049: G1: add precondition to set_remainder_to_point_to_start

### PR DESCRIPTION
**Pull request by albertnetymk**
Simple change of converting always-false conditions to assertions.

Test: hotspot_gc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278049](https://bugs.openjdk.java.net/browse/JDK-8278049): G1: add precondition to set_remainder_to_point_to_start

### Reviewers
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**) ⚠️ Review applies to 9cc3bd7ca46f04970d92bd2eb25b34128c5330db
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6630/head:pull/6630` \
`$ git checkout pull/6630`

Update a local copy of the PR: \
`$ git checkout pull/6630` \
`$ git pull https://git.openjdk.java.net/jdk pull/6630/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6630`

View PR using the GUI difftool: \
`$ git pr show -t 6630`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6630.diff">https://git.openjdk.java.net/jdk/pull/6630.diff</a>

</details>

### CODE REVIEW

**Comment by tschatzl** [comment]
Please run this through at least tier1-5. This increases the chance to catch potential edge cases quite a bit compared to just `hotspot_gc`.

**Review by Hamlin-Li — APPROVED** [review]
I think this is good.

**Review by tschatzl — APPROVED** [review]
Lgtm.

My first reaction to run more testing (which isn't bad) has been an overreaction; after some looking at the caller I agree that the case that has been removed can never happen.

Maybe update the copyright date too.

**Comment by albertnetymk** [comment]
Tier1-5 pass; copyright year updated.

**Review by tschatzl — APPROVED** [review]
Still good ;)

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
