### PR TITLE
8301756: Missed constructor from 8301659

### PR DESCRIPTION
**Pull request by TheShermanTanker**
8301659 has missed a reordered constructor defined inside libawt

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301756](https://bugs.openjdk.org/browse/JDK-8301756): Missed constructor from 8301659

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12405/head:pull/12405` \
`$ git checkout pull/12405`

Update a local copy of the PR: \
`$ git checkout pull/12405` \
`$ git pull https://git.openjdk.org/jdk pull/12405/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12405`

View PR using the GUI difftool: \
`$ git pr show -t 12405`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12405.diff">https://git.openjdk.org/jdk/pull/12405.diff</a>

</details>

### CODE REVIEW

**Comment by prrace** [comment]
1) How did you miss this ?
2) Bigger question, why is it important ? We are never going to support gcc for compiling on Windows .. no one is going to care if it breaks and no one is going to put any effort into making sure it works at all. Not until the day Microsoft replaces VC with gcc ..

**Comment by TheShermanTanker** [comment]
> How did you miss this ?

Oversight, my mistake, it happens sometimes



> Bigger question, why is it important ?

Code quality, constructors in C++ should generally have the initializer list in the same order as their declaration. It helps deduce class layout and initialization order at a quick glance when reviewing code with the constructor in an implementation file away from the class itself, as is the case here, ignoring everything about gcc (You could very easily disable the warning on this file in Awt2dLibraries and be done with it instead if you really wanted to anyway, but I don't think it's good to do that). Common pitfalls in C++ should really be avoided when it comes to JDK code as a whole, or at least that's my opinion. Convention within the JDK has largely been to initialize class members in the correct order too, which is what this patch intends to help with



> ...no one is going to care if it breaks and no one is going to put any effort into making sure it works at all.

[What makes you](https://bugs.openjdk.org/browse/JDK-8288293) [so sure](https://github.com/TheShermanTanker/jdk/tree/compiler)?

**Review by aivanov-jdk — APPROVED** [review]

**Comment by TheShermanTanker** [comment]
Thanks aivanov!

**Pull request closed without merging**
