### PR TITLE
8292564: x86: Remove redundant casts in Assembler usages

### PR DESCRIPTION
**Pull request by iwanowww**
Clean up Assembler API and remove redundant at use sites.
 
They are not needed anymore because implicit casts between Register and integrals are forbidden now.

Some of the casts are turned into `static_cast`s to assert that constants are small enough to fit into 32-bit immediate.

Testing: hs-tier1 - hs-tier4

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292564](https://bugs.openjdk.org/browse/JDK-8292564): x86: Remove redundant casts in Assembler usages

### Reviewers
 * [Igor Veresov](https://openjdk.org/census#iveresov) (@veresov - **Reviewer**) ⚠️ Review applies to [67065764](https://git.openjdk.org/jdk/pull/9909/files/67065764c13ec5f080c096a9f8208ab0f4913be3)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [67065764](https://git.openjdk.org/jdk/pull/9909/files/67065764c13ec5f080c096a9f8208ab0f4913be3)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9909/head:pull/9909` \
`$ git checkout pull/9909`

Update a local copy of the PR: \
`$ git checkout pull/9909` \
`$ git pull https://git.openjdk.org/jdk pull/9909/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9909`

View PR using the GUI difftool: \
`$ git pr show -t 9909`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9909.diff">https://git.openjdk.org/jdk/pull/9909.diff</a>

</details>

### CODE REVIEW

**Review by veresov — APPROVED** [review]
Looks good.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
> Some of the casts are turned into `static_cast`s to assert that constants are small enough to fit into 32-bit immediate.

This confuses me a bit: I thought narrowing (implicit) conversions with `static_cast` would not assert safety in these cases. We have `checked_cast` for these.

**Comment by iwanowww** [comment]
Good catch, Aleksey. I intended to use `checked_cast`, but misremembered the name. Fixed.

**Review by shipilev — APPROVED** [review]
Looks fine. I also tested with Alpine builds, that are known to get funky with `intptr_t` conversions.

**Comment by iwanowww** [comment]
Thanks for the reviews, Igor, Vladimir, and Aleksey.

/integrate

**Pull request closed without merging**
