### PR TITLE
8315843: C1: Use MDO offsets as int consts instead of intptr consts

### PR DESCRIPTION
**Pull request by shipilev**
Noticed this when looking at C1 profiling code. We use MDO offsets as `intptrConst`, despite them being very small. This leads to loads with `movabs` with large immediates on x86. We can instead just load them as `intConst`-s. This affects tier3 profiling code only. 

Sample branch profiling hunk from C1 tier3 on x86_64:

```
Before:
   0x00007f269065ed02:   test   %edx,%edx
   0x00007f269065ed04:   movabs $0x7f260a4ddd68,%rax  ;   {metadata(method data for {method} …
   0x00007f269065ed0e:   movabs $0x138,%rsi
 ╭ 0x00007f269065ed18:   je     0x00007f269065ed24
 │ 0x00007f269065ed1a:   movabs $0x148,%rsi
 ↘ 0x00007f269065ed24:   mov    (%rax,%rsi,1),%rdi
   0x00007f269065ed28:   lea    0x1(%rdi),%rdi
   0x00007f269065ed2c:   mov    %rdi,(%rax,%rsi,1)
   0x00007f269065ed30:   je     0x00007f269065ed4e     

After:
   0x00007f1370dcd782:   test   %edx,%edx
   0x00007f1370dcd784:   movabs $0x7f12f64ddd68,%rax   ;   {metadata(method data for {method} …
   0x00007f1370dcd78e:   mov    $0x138,%esi
 ╭ 0x00007f1370dcd793:   je     0x00007f1370dcd79a        
 │ 0x00007f1370dcd795:   mov    $0x148,%esi
 ↘ 0x00007f1370dcd79a:   mov    (%rax,%rsi,1),%rdi        
   0x00007f1370dcd79e:   lea    0x1(%rdi),%rdi
   0x00007f1370dcd7a2:   mov    %rdi,(%rax,%rsi,1)       
   0x00007f1370dcd7a6:   je     0x00007f1370dcd7c4 
```

In the hunk above, this saves about 8 bytes. This leads to observable code space savings on larger tests, e.g. on `-Xcomp -XX:TieredStopAtLevel=... HelloWorld`.

```
# Before
tier1: nmethod code size         :   426448 bytes
tier2: nmethod code size         :   463008 bytes
tier3: nmethod code size         :   910656 bytes

# After
tier1: nmethod code size         :   426448 bytes
tier2: nmethod code size         :   463008 bytes
tier3: nmethod code size         :   892448 bytes (-2.0%)
```

Additional testing:
 - [ ] Linux x86_64 fastdebug `tier1 tier2 tier3`
 - [ ] Linux AArch64 fastdebug `tier1 tier2 tier3`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315843](https://bugs.openjdk.org/browse/JDK-8315843): C1: Use MDO offsets as int consts instead of intptr consts (**Enhancement** - P4) ⚠️ Issue is not open.

### Reviewers
 * [Igor Veresov](https://openjdk.org/census#iveresov) (@veresov - **Reviewer**) ⚠️ Review applies to [f4b94d01](https://git.openjdk.org/jdk/pull/15612/files/f4b94d0126b7bed2ef71caf8d09392be720f3691)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15612/head:pull/15612` \
`$ git checkout pull/15612`

Update a local copy of the PR: \
`$ git checkout pull/15612` \
`$ git pull https://git.openjdk.org/jdk.git pull/15612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15612`

View PR using the GUI difftool: \
`$ git pr show -t 15612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15612.diff">https://git.openjdk.org/jdk/pull/15612.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15612#issuecomment-1709769279)

### CODE REVIEW

**Comment by merykitty** [comment]
How about hiding `Assembler::mov64` in `MacroAssembler` with a method that conditionally uses equivalent instructions (`movl`, `movq`) if feasible. I remember there is some places in C2 where we use `mov64(r, -1)` which may be benefit from this, too.

Thanks.

**Comment by shipilev** [comment]
> How about hiding `Assembler::mov64` in `MacroAssembler` with a method that conditionally uses equivalent instructions (`movl`, `movq`) if feasible. I remember there are some places in C2 where we use `mov64(r, -1)` which may be benefit from this, too.

Could be done.

But this thing looks better, because it does improvement on LIR level, which allows all arches to benefit from shorter constants. In other words, it is better to feed LIR assemblers with smaller constants to begin with, instead of relying on LIR assemblers to optimize for us. (Having said that, I have a separate improvement for AArch64 to use "non-patchable" shorter `movk` sequences for these loads.)

**Review by veresov — APPROVED** [review]

**Comment by TobiHartmann** [comment]
I'm seeing failures during build:

```
[2023-09-07T10:47:14,379Z] # A fatal error has been detected by the Java Runtime Environment:
[2023-09-07T10:47:14,379Z] #
[2023-09-07T10:47:14,379Z] #  Internal Error (/opt/mach5/mesos/work_dir/slaves/cd627e65-f015-4fb1-a1d2-b6c9b8127f98-S160475/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/e6602a1f-a21e-4e8c-a2e5-b8831688b712/runs/f932837c-4440-466e-accb-1c91993e1290/workspace/open/src/hotspot/cpu/x86/c1_LIR_x86.cpp:64), pid=10906, tid=11011
[2023-09-07T10:47:14,379Z] #  assert(index()->is_illegal() || index()->is_double_cpu()) failed: wrong index operand
[2023-09-07T10:47:14,379Z] #
[2023-09-07T10:47:14,379Z] # JRE version: Java(TM) SE Runtime Environment (22.0) (fastdebug build 22-internal-2023-09-07-1002041.tobias.hartmann.jdk2)
[2023-09-07T10:47:14,379Z] # Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 22-internal-2023-09-07-1002041.tobias.hartmann.jdk2, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
[2023-09-07T10:47:14,379Z] # Problematic frame:
[2023-09-07T10:47:14,380Z] # V  [libjvm.so+0x7c514b]  LIR_Address::verify() const+0x2bb
```

**Comment by shipilev** [comment]
> I'm seeing failures during build:

Yes, that's weird, because it used to work well for me locally. I am looking.

**Comment by shipilev** [comment]
> I'm seeing failures during build:

OK, I think I know what that is: https://github.com/openjdk/jdk/blob/726c9c977dbaab75a2df4a931e3414ccabb7db44/src/hotspot/cpu/x86/c1_LIR_x86.cpp#L64 -- why are not we allowing `is_single_cpu` indexes? I see RISC-V and AArch64 allow these: https://github.com/openjdk/jdk/blob/726c9c977dbaab75a2df4a931e3414ccabb7db44/src/hotspot/cpu/aarch64/c1_LIR_aarch64.cpp#L50, while other platforms don't.

I ran fastdebug on aarch64, that's why I did not see it.

**Comment by shipilev** [comment]
If I relax that assert like in new commit, the x86_64 build works, and test run (in progress). But x86_64 is not the only arch that needs this relaxation. So maybe the lateral move would be indeed handling these smaller constants in x86 parts specifically. I'll let the tests run meanwhile.

**Comment by shipilev** [comment]
I think it should be subsumed by more generic x86 fix: [JDK-8319406](https://bugs.openjdk.org/browse/JDK-8319406).

**Pull request closed without merging**
