### PR TITLE
8260502: [s390] NativeMovRegMem::verify() fails because it's too strict

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
"fatal error: this is not a `NativeMovRegMem' site" was observed while testing the debug build without CompressedOops.
NativeMovRegMem::verify() tries to verify instructions beyond the load_const at a place at which we don't have valid instructions. See bug for details.
I suggest to remove the wrong part of the verification.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260502](https://bugs.openjdk.java.net/browse/JDK-8260502): [s390] NativeMovRegMem::verify() fails because it's too strict

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to 54fa039c826cf7face6291dde83237194a808757
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2258/head:pull/2258`
`$ git checkout pull/2258`

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Looks good to me.
Thanks for finding and fixing.

**Review by reinrich — COMMENTED** [review]
The fix looks good to me.

The comment before the declaration of NativeMovRegMem seems to be wrong. I'd suggest to change it like this:

s/optional, load only/optional, store only/

```
// The instruction sequence looks like this:
//   iihf        %r1,$bits1              ; load offset for mem access
//   iilf        %r1,$bits2
//   [compress oop]                      ; optional, store only
//   load/store  %r2,0(%r1,%r2)          ; memory access
```

I noticed that on x86 encoding/decoding the T_OBJECT field value in reg2mem/mem2reg is done before/after the code that is to be patched. Changing the s390/PPC versions to do the same may have solved JDK-8233081 as well. This wouldn't have increased the complexity of the already extremely complex C1 patching mechanics. But it is like it is.

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews! I've fixed the comment as suggested. Thanks.

**Review by reinrich — APPROVED** [review]
LGTM, Thanks.

**Pull request closed without merging**
