### PR TITLE
8251392: Consolidate Metaspace Statistics

### PR DESCRIPTION
**Pull request by tstuefe**
There is a lot of duplicate coding when it comes to the consumption of Metaspace Statistics.

Metaspace offers statistical APIs via `MetaspaceUtils::(reserved|committed|used)_(words|bytes)` for either the whole metaspace or non-class/class space separately. But many callers need some sort of combination of these values, which they keep in data holder structures which all are named "Metaspace" something and all do a very similar job. In particular, we have:

- MetaspaceSizesSnapshot (used for gc logs)
- MetaspaceSnapshot (used in NMT)
- MetaspaceSizes, MetaspaceSummary, JFRMetaspaceSummary (JFR)
- MetaspaceCounters, CompressedClassSpaceCounters, MetaspacePerfCounters (jstat performance counters)
- CompressedKlassSpacePool and MetaspacePool (used for MXBeans)

As much as possible coding should be unified.

In addition to that, all these callers share a common problem, in that retrieving individual statistical values via `MetaspaceUtils::(reserved|committed|used)_(words|bytes)` may yield inconsistent values. For example, "reserved" < "committed", or "committed" < "used". This is the cause of a variety of rare intermittent test errors in different areas, e.g. Performance counters (JDK-8163413, JDK-8153323), the gc log, the MemoryPoolMXBean and NMT (JDK-8237872).

-----------------------

This patch introduces two new data holder structures:
- `MetaspaceStats` holds reserved/committed/used counter
- `MetaspaceCombinedStats` holds an expression of these counters for class- and non-class metaspace each, as well as total counter.

Furthermore, the patch introduces two new APIs in MetaspaceUtils:
- `MetaspaceStats get_statistics(type)`
- `MetaspaceCombinedStats get_combined_statistics()`
The former is used to get statistics for either non-class-space or class space; the latter gets statistics for the whole, including total values. Both APIs guarantee consistent values - reserved >= committed >= used - and never lock.

The patch uses these new data holders and these APIs to consolidate, clean up and simplify a lot of caller code, in addition to making that code resistant against inconsistent statistics:

- GC Log: class `MetaspaceSizesSnapshot` in *metaspace/metaspaceSizesSnapshot.cpp/hpp* had been used to hold metaspace statistics. Its default constructor sneakishly queried all values. `MetaspaceSizesSnapshot` has neem removed, caller code rewritten for MetaspaceCombinedStats and explicit value querying.

- NMT had class `MetaspaceSnapshot` to keep metaspace statistics and to print out baseline diffs. 
   - `MetaspaceSizesSnapshot` was removed and replaced with `MetaspaceCombinedStats`.
   - `MemSummaryDiffReporter::print_metaspace_diff()` has been modified: fixed a potential div-by-zero, removed the "free" statistics which is meaningless, and massaged the code a bit.
   - Similar fixes have been done in `MemSummaryReporter::report_metadata()` (which, if backported, should fix JDK-8237872).

- jstat & co: Metaspace performance counters are realized by `MetaspaceCounters` and `CompressedClassSpaceCounters`, implementation resides in `MetaspacePerfCounters` (metaspace/metaspaceCounters.hpp/cpp). 
	- I completely removed `CompressedClassSpaceCounters` since there is no need for two APIs, class space is part of metaspace.
	- I simplified the counter coding a lot. I think the complexity was not needed.
	- The Metaspace counters are now retrieved in a consistent manner. This should take care of JDK-8163413, JDK-8153323 and similar bugs.

- `MetaspaceMemoryPool`, `CompressedClassSpaceMemoryPool` used in MxBeans: I changed the implementation to return consistent values. 

- JFR reports metaspace allocations (which, confusingly, uses a different terminology: "data_space" == non-class portion of metaspace). It used `MetaspaceSummary` to hold the statistics, which were composed of `MetaspaceSizes`.
	- I completely removed `MetaspaceSizes`
	- I rewrote `MetaspaceSummary` to use `MetaspaceCombinedStats`

- MetaspaceUtils::print_on() has been used to print metaspace statistics (by GCs). Function has been corrected to print consistent values.

- Added a simple gtest for the new APIs

Tests: 
- manually executed hotspot tier1 tests
- explicitly tested runtime/Metaspace, gc/metaspace, runtime/NMT
- SAP tests ran for several weeks on all our platforms

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251392](https://bugs.openjdk.java.net/browse/JDK-8251392): Consolidate Metaspace Statistics

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3786/head:pull/3786` \
`$ git checkout pull/3786`

Update a local copy of the PR: \
`$ git checkout pull/3786` \
`$ git pull https://git.openjdk.java.net/jdk pull/3786/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3786`

View PR using the GUI difftool: \
`$ git pr show -t 3786`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3786.diff">https://git.openjdk.java.net/jdk/pull/3786.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
@zhengyu123 : could you take a look at the NMT part of this change? Thanks!

**Comment by tstuefe** [comment]
Gentle ping.

**Review by coleenp — APPROVED** [review]
This looks good to me.  Nice cleanup removing duplicated metaspace counting code!

**Comment by tstuefe** [comment]
> This looks good to me. Nice cleanup removing duplicated metaspace counting code!

Thank you Coleen!

**Review by zhengyu123 — APPROVED** [review]
Looks good.

**Comment by tstuefe** [comment]
> Looks good.

Thanks Zhengyu!

**Comment by tstuefe** [comment]
Okay, I waited but no more reviews are forthcoming. Our nightlies show no errors attributable to this change.

/integrate

**Pull request closed without merging**
