### PR TITLE
8300866: Declare some classes final in java.io

### PR DESCRIPTION
**Pull request by minborg**
This PR proposes declaring some internal classes in java.io as `final`, explicitly indicating that they are not intended for sub-classing. 

If you think declaring classes final is just "static noice", please see http://minborgsjavapot.blogspot.com/2021/12/why-general-inheritance-is-flawed-and.html first and then come back and comment on the issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300866](https://bugs.openjdk.org/browse/JDK-8300866): Declare some classes final in java.io

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [a77aa151](https://git.openjdk.org/jdk/pull/12141/files/a77aa151f5d81b37f35aefd31d4bfee6e176bffa)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12141/head:pull/12141` \
`$ git checkout pull/12141`

Update a local copy of the PR: \
`$ git checkout pull/12141` \
`$ git pull https://git.openjdk.org/jdk pull/12141/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12141`

View PR using the GUI difftool: \
`$ git pr show -t 12141`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12141.diff">https://git.openjdk.org/jdk/pull/12141.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Look okay. We should probably think about removing ExpiringCache as it hasn't been used for many releases.

**Comment by minborg** [comment]
> Look okay. We should probably think about removing ExpiringCache as it hasn't been used for many releases.

It looks like CE is used in `UnixFileSystem` via the system property "sun.io.useCanonCaches" ?

**Comment by AlanBateman** [comment]
> It looks like CE is used in `UnixFileSystem` via the system property "sun.io.useCanonCaches" ?

It was disabled in JDK 12 and the general plan was to eventually remove it eventually.

**Pull request closed without merging**
