### PR TITLE
8337642: Remove unused APIs of GCPolicyCounters

### PR DESCRIPTION
**Pull request by albertnetymk**
Trivial removing an empty method call. (Only subclasses have non-empty method body, which is not used by Serial.)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337642](https://bugs.openjdk.org/browse/JDK-8337642): Remove unused APIs of GCPolicyCounters (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20416/head:pull/20416` \
`$ git checkout pull/20416`

Update a local copy of the PR: \
`$ git checkout pull/20416` \
`$ git pull https://git.openjdk.org/jdk.git pull/20416/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20416`

View PR using the GUI difftool: \
`$ git pr show -t 20416`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20416.diff">https://git.openjdk.org/jdk/pull/20416.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20416#issuecomment-2262280928)

### CODE REVIEW

**Review by tschatzl — COMMENTED** [review]
I disagree with this change: when using `GCPolicyCounters`, the implied contract seems to be that `update_counters` is called at appropriate locations (e.g. `gc_epilogue`), even if empty, exactly to abstract away differences in the collectors wrt to usage.

Looking at the users, it rather seems G1 being wrong in not calling this.

**Comment by albertnetymk** [comment]
> the implied contract seems to be that update_counters is called at appropriate locations

Mabye we can remove it from the base class. Callers of this method always live in gc-specific location where the concrete policy-counter type is known.

**Comment by tschatzl** [comment]
> > the implied contract seems to be that update_counters is called at appropriate locations
> 
> Mabye we can remove it from the base class. Callers of this method always live in gc-specific location where the concrete policy-counter type is known.

Imo the point of this and similar APIs to avoid the need to think about whether a given collector uses a particular implementation, so that would run counter to the intent of such generic API about handling? I.e. that regardless of type of `GCPolicyCounters` that is actually used, one can be sure that everything is fine as long as you call that `update` method, not needing to think about the concrete policy type.

Is the single empty call that much of a (performance) issue?

**Comment by albertnetymk** [comment]
> so that would run counter to the intent of such generic API about handling

One can view `GCPolicyCounters` as a plain data-structure with only getters. The only two non-getter methods are the empty `update_counters` and the unused `kind`. If both are removed, `GCPolicyCounters` doesn't expose any action-related APIs any more.

> one can be sure that everything is fine as long as you call that update method,

That's a false sense of security. The two actual vars, `_tenuring_threshold` and `_desired_survivor_size`, that requires updating, are updated in two diff places in Serial and G1, after and before young-gc. IOW, diff GCs differ enough so that not exposing an `update` API, i.e. treating `GCPolicyCounters` as plain-old-data, offers more flexibility, IMO.

> Is the single empty call that much of a (performance) issue?

It's more about removing effectively dead code to simplify the logic.

**Comment by tschatzl** [comment]
> > so that would run counter to the intent of such generic API about handling
> 
> One can view `GCPolicyCounters` as a plain data-structure with only getters. The only two non-getter methods are the empty `update_counters` and the unused `kind`. If both are removed, `GCPolicyCounters` doesn't expose any action-related APIs any more.

Then let's do that instead of removing only the call. The `update_counters` API as it is used now does not seem to help at all.

The `gc_overhead_limit_exceeded_counter` could also be moved into the Parallel specific class because it's only used there.

I object to only remove the call and keep the bad API; removing them isn't that much more work.

**Review by tschatzl — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
