### PR TITLE
8301012: [vectorapi]: Intrinsify CompressBitsV/ExpandBitsV and add the AArch64 SVE backend implementation

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
This patch adds mid-end compiler vector IR nodes for the scalar CompressBits and ExpandBits nodes - CompressBitsV and ExpandBitsV and also adds aarch64 backend support for these nodes using SVE2 instructions (included in the svebitperm feature). As there are direct instructions in SVE2 that map to these operations, a huge speed up in performance can be observed and it might significantly benefit all those workloads that extensively run these operations on an SVE2(with svebitperm feature) supporting machine.

All the JTREG tests under "test/jdk/jdk/incubator/vector" pass successfully with this patch on an SVE2 machine.
The JMH tests - COMPRESS_BITS and EXPAND_BITS from [1] and [2] were run on a 128-bit vector length, SVE2 and svebitperm supporting aarch64 machine. Following are the gains observed with this patch -

```
Benchmark                       (length)  Mode    Cnt   Gain
IntMaxVector.COMPRESS_BITS      1024      thrpt   15    81.68x
IntMaxVector.EXPAND_BITS        1024      thrpt   15    85.65x
LongMaxVector.COMPRESS_BITS     1024      thrpt   15    70.78x
LongMaxVector.EXPAND_BITS       1024      thrpt   15    76.31x
```

The "Gain" column is the ratio between the throughput of benchmark runs with this patch and that of benchmark runs without this patch. This patch does not change the performance of these operations for all other machines that do not support these instructions or when run on a different architecture.

This patch enables the generation of optimized SVE2 instructions for CompressBits and ExpandBits operations through vectorapi but at the same time with the addition of scalar implementation of CompressBits andExpandBits in the aarch64 backend with this commit - https://github.com/openjdk/jdk/commit/bbd8ae78200e4128d4eddf8694835956b5c5f142, it also enabes auto-vectorization of these nodes on aarch64 SVE2 supporting machines.

Measured the performance of the following benchmarks with the master branch (auto-vectorization not enabled) with this patch
(auto-vectorization enabled) -
    
```
        @Benchmark
        public void testCompInt() {
            for (int i = 0; i < length; i++) {
                ir[i] = Integer.compress(ia[i], ib[i]);
            }
        }
    
        @Benchmark
        public void testExpInt() {
            for (int i = 0; i < length; i++) {
                ir[i] = Integer.expand(ia[i], ib[i]);
            }
        }
    
        @Benchmark
        public void testCompLong() {
            for (int i = 0; i < length; i++) {
                lr[i] = Long.compress(la[i], lb[i]);
            }
        }
    
        @Benchmark
        public void testExpLong() {
            for (int i = 0; i < length; i++) {
                lr[i] = Long.expand(la[i], lb[i]);
            }
        }
    
    Benchmark                               (length)  Mode     Cnt   Gain
    VectorCompressExpand.testCompInt        2048      thrpt    15    9.97x
    VectorCompressExpand.testCompLong       2048      thrpt    15    5.63x
    VectorCompressExpand.testExpInt         2048      thrpt    15    9.70x
    VectorCompressExpand.testExpLong        2048      thrpt    15    5.66x

```    
    
Gain column is the ratio between the throughput of this patch and that of the master branch.
With vectorization enabled (either through Superword or Vectorapi), significant gains can be observed for CompressBits and ExpandBits.

[1] https://github.com/openjdk/panama-vector/blob/vectorIntrinsics/test/micro/org/openjdk/bench/jdk/incubator/vector/operation/IntMaxVector.java 
[2] https://github.com/openjdk/panama-vector/blob/vectorIntrinsics/test/micro/org/openjdk/bench/jdk/incubator/vector/operation/LongMaxVector.java

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301012](https://bugs.openjdk.org/browse/JDK-8301012): [vectorapi]: Intrinsify CompressBitsV/ExpandBitsV and add the AArch64 SVE backend implementation

### Reviewers
 * [Nick Gasson](https://openjdk.org/census#ngasson) (@nick-arm - **Reviewer**) ⚠️ Review applies to [28274614](https://git.openjdk.org/jdk/pull/12446/files/282746147900d01d19aaf5d48f0c161b74256c94)
 * [Eric Liu](https://openjdk.org/census#eliu) (@theRealELiu - Committer) ⚠️ Review applies to [28274614](https://git.openjdk.org/jdk/pull/12446/files/282746147900d01d19aaf5d48f0c161b74256c94)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Contributors
 * Xiaohong Gong `<xgong@openjdk.org>`
 * Jatin Bhateja `<jbhateja@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12446/head:pull/12446` \
`$ git checkout pull/12446`

Update a local copy of the PR: \
`$ git checkout pull/12446` \
`$ git pull https://git.openjdk.org/jdk.git pull/12446/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12446`

View PR using the GUI difftool: \
`$ git pr show -t 12446`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12446.diff">https://git.openjdk.org/jdk/pull/12446.diff</a>

</details>

### CODE REVIEW

**Review by nick-arm — APPROVED** [review]
The test and changes under `cpu/aarch64` look OK to me but needs someone else to review the C2 changes.

**Review by theRealELiu — APPROVED** [review]

**Comment by Bhavana-Kilambi** [comment]
Hi @TobiHartmann , could you please take a look at the C2 related changes in this PR please? Thank you ..

**Review by TobiHartmann — APPROVED** [review]
I'm not an expert in SVE and we don't have the corresponding hardware to test this. But the changes look reasonable to me and pass our testing.

**Comment by theRealELiu** [comment]
> I'm not an expert in SVE and we don't have the corresponding hardware to test this. But the changes look reasonable to me and pass our testing.

A typical "team-working" review :P

**Comment by Bhavana-Kilambi** [comment]
Thank you for reviewing ..

**Pull request closed without merging**
