### PR TITLE
8287440: Typo in package-info.java of java.util.random

### PR DESCRIPTION
**Pull request by anthonyvdotbe**
The change is trivial, but I'll need help from someone to create a JBS issue & sponsor this PR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287440](https://bugs.openjdk.java.net/browse/JDK-8287440): Typo in package-info.java of java.util.random

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to [1ed395f3](https://git.openjdk.java.net/jdk/pull/8766/files/1ed395f3db3d22690d4f62ad667232bd330c128c)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to [1ed395f3](https://git.openjdk.java.net/jdk/pull/8766/files/1ed395f3db3d22690d4f62ad667232bd330c128c)
 * [Jaikiran Pai](https://openjdk.java.net/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8766/head:pull/8766` \
`$ git checkout pull/8766`

Update a local copy of the PR: \
`$ git checkout pull/8766` \
`$ git pull https://git.openjdk.java.net/jdk pull/8766/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8766`

View PR using the GUI difftool: \
`$ git pr show -t 8766`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8766.diff">https://git.openjdk.java.net/jdk/pull/8766.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello @anthonyvdotbe, I've created https://bugs.openjdk.java.net/browse/JDK-8287440 for this change. Please edit the title of this PR to "8287440: Typo in package-info.java of java.util.random" so that it triggers the review process.

**Review by jddarcy — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by jaikiran** [comment]
@anthonyvdotbe, can you also please change the copyright year on that file from `Copyright (c) 2021,` to `Copyright (c) 2021, 2022,`

**Comment by anthonyvdotbe** [comment]
Thanks for the heads-up @jaikiran I've fixed the copyright year

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you for the changes. Looks fine to me. Please go ahead and issue the integrate command and one of us will sponsor this change.

**Pull request closed without merging**
