### PR TITLE
8295737: macOS: Print content cut off when width > height with portrait orientation

### PR DESCRIPTION
**Pull request by AlexanderScherbatiy**
A printed content is truncated on macOS if the content paper size width larger than height with portrait orientation or width is less than height with landscape orientation.

To reproduce the issue run the [CutOffImage](https://bugs.openjdk.org/secure/attachment/101145/CutOffImage.java) sample on MacOS.

Four rectangles are printed:
1. size 300x100, portrait orientation
2. size 300x100, landscape orientation
3. size 100x300, portrait orientation
4. size 100x300, landscape orientation

The first and fourth rectangles are truncated: [cut off content](https://bugs.openjdk.org/secure/attachment/101153/before-fix-all.pdf)

The reason is that NSPrintInfo class does not allow to set paper size and orientation independently.
Setting paper size width large than height changes NSPrintInfo orientation to landscape.
Setting paper size width less than height changes NSPrintInfo orientation to portrait.
Updating NSPrintInfo orientation from landscape to portrait or from portrait to landscape swaps NSPrintInfo paper width and height.

The Cocoa code that shows NSPrintInfo behavior:
```
#import <Cocoa/Cocoa.h>

int main()
{
    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
    NSApp = [NSApplication sharedApplication];

    #ifdef __MAC_10_9 // code for SDK 10.9 or newer
    #define NS_PORTRAIT NSPaperOrientationPortrait
    #define NS_LANDSCAPE NSPaperOrientationLandscape
    #else // code for SDK 10.8 or older
    #define NS_PORTRAIT NSPortraitOrientation
    #define NS_LANDSCAPE NSLandscapeOrientation
    #endif

    printf("NS_PORTRAIT: %d\n", NS_PORTRAIT);
    printf("NS_LANDSCAPE: %d\n", NS_LANDSCAPE);

    printf("create default print info\n");
    NSPrintInfo* defaultPrintInfo = [[NSPrintInfo sharedPrintInfo] copy];
    NSSize size = [defaultPrintInfo paperSize];
    printf("orientation: %d, paper size: [%f, %f]\n", [defaultPrintInfo orientation], size.width, size.height);

    printf("call setUpPrintOperationDefaultValues\n");
    [defaultPrintInfo setUpPrintOperationDefaultValues];
    size = [defaultPrintInfo paperSize];
    printf("orientation: %d, paper size: [%f, %f]\n", [defaultPrintInfo orientation], size.width, size.height);

    double w = 300.0;
    double h = 100.0;
    printf("set size: [%f, %f]\n", w, h);
    [defaultPrintInfo setPaperSize:NSMakeSize(w, h)];
    size = [defaultPrintInfo paperSize];
    printf("orientation: %d, paper size: [%f, %f]\n", [defaultPrintInfo orientation], size.width, size.height);

    printf("Set NS_PORTRAIT orientation\n");
    [defaultPrintInfo setOrientation: NS_PORTRAIT];
    size = [defaultPrintInfo paperSize];
    printf("orientation: %d, paper size: [%f, %f]\n", [defaultPrintInfo orientation], size.width, size.height);

    [NSApp run];

    [NSApp release];
    [pool release];
    return(EXIT_SUCCESS);
} 
```

On macOS Mojave 10.14.5 it prints:

```
NS_PORTRAIT: 0
NS_LANDSCAPE: 1
create default print info
orientation: 0, paper size: [612.000000, 792.000000]
call setUpPrintOperationDefaultValues
orientation: 0, paper size: [612.000000, 792.000000]
set size: [300.000000, 100.000000]
orientation: 1, paper size: [300.000000, 100.000000] // orientation flip
Set NS_PORTRAIT orientation
orientation: 0, paper size: [100.000000, 300.000000] // size flip
``` 

There are four possible cases for printing a rectangle with different size and orientation:
1. Input: paper size: (w > h), orientation portrait
  [dstPrintInfo setPaperSize: NSMakeSize(w, h)]  // size: (w, h), orientation: landscape
  [dstPrintInfo setOrientation: NS_PORTRAIT]     // size: (h, w), orientation: portrait
  Note: width and height are swapped
2. Input: paper size: (w > h), orientation landscape
  [dstPrintInfo setPaperSize: NSMakeSize(h, w)]  // size: (h, w), orientation: portrait
  [dstPrintInfo setOrientation: NS_LANDSCAPE]  // size: (w, h), orientation: landscape
3. Input: paper size: (w < h), orientation portrait
  [dstPrintInfo setPaperSize: NSMakeSize(w, h)]  // size: (w, h), orientation: portrait
  [dstPrintInfo setOrientation: NS_PORTRAIT]     // size: (w, h), orientation: portrait
4. Input: paper size: (w < h), orientation landscape
  [dstPrintInfo setPaperSize: NSMakeSize(h, w)]  // size: (h, w), orientation: landscape
  [dstPrintInfo setOrientation: NS_LANDSCAPE]  // size: (h, w), orientation: landscape
  Note: width and height are swapped

Only for cases 1 and 4 the final width and height are swapped.
The proposed fix enlarges height for cases 1 and 4 to not cut the printed rectangle.

It is not full fix which draws rectangles for cases 1 and 4 in the requested size.
Setting requested size leads that subsequent orientation flips width and height.
The fix only enlarges the truncated area in height direction. The enlarged area in width is preserved as before the fix.

Printed rectangles before and after the fix:
1. size 300x100, portrait orientation: [before-fix-1.pdf](https://bugs.openjdk.org/secure/attachment/101157/before-fix-1.pdf),  [after-fix-1.pdf](https://bugs.openjdk.org/secure/attachment/101162/after-fix-1.pdf)
2. size 300x100, landscape orientation: [before-fix-2.pdf](https://bugs.openjdk.org/secure/attachment/101156/before-fix-2.pdf),  [after-fix-2.pdf](https://bugs.openjdk.org/secure/attachment/101161/after-fix-2.pdf)
3. size 100x300, portrait orientation: [before-fix-3.pdf](https://bugs.openjdk.org/secure/attachment/101155/before-fix-3.pdf),  [after-fix-3.pdf](https://bugs.openjdk.org/secure/attachment/101160/after-fix-3.pdf)
4. size 100x300, landscape orientation: [before-fix-4.pdf](https://bugs.openjdk.org/secure/attachment/101154/before-fix-4.pdf),  [after-fix-4.pdf](https://bugs.openjdk.org/secure/attachment/101159/after-fix-4.pdf)

All four rectangles: [before-fix-all.pdf](https://bugs.openjdk.org/secure/attachment/101153/before-fix-all.pdf),  [after-fix-all.pdf](https://bugs.openjdk.org/secure/attachment/101158/after-fix-all.pdf)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295737](https://bugs.openjdk.org/browse/JDK-8295737): macOS: Print content cut off when width &gt; height with portrait orientation

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10808/head:pull/10808` \
`$ git checkout pull/10808`

Update a local copy of the PR: \
`$ git checkout pull/10808` \
`$ git pull https://git.openjdk.org/jdk pull/10808/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10808`

View PR using the GUI difftool: \
`$ git pr show -t 10808`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10808.diff">https://git.openjdk.org/jdk/pull/10808.diff</a>

</details>

### CODE REVIEW

**Comment by prrace** [comment]
The analysis of the problem sounds fine but then it all gets confusing to me when I come to the fix.

So first you capture the intended orientation in the switch but do not set it to the printer context.
And I am lost as to why you do this
    NSPaperOrientation orientation = [dstPrintInfo orientation];

but promptly over-write the result in the switch statement.

Then we get to this code :-
      NSSize size = [dstPrintInfo paperSize];
     // Enlarge height only for cases 1 and 4.
     if ([dstPrintInfo orientation] == NS_LANDSCAPE && size.width > size.height) {
         size.height = size.width + ((orientation == NS_PORTRAIT) ? 1 : 0);
         [dstPrintInfo setPaperSize: size];

So case 1 is intended orientation of PORTRAIT but
(1) You are only checking for landscape and
(2) You are doing it on the current printer context, not what is intended.

I am probably missing something but I'd like you to point out what it is.

Also that last "+ .." condition is odd and un-explained.

But then we get to the bigger question(s)
Are all the settings in sync / agreement after this ?
Is the clip correct ?
What if the changed size now matches a different paper ? - The ability to
set paper size at all here is a relic of when there was no way to find out the
real paper sizes. Papers which don't exist should not be used.
Continuous feed is probably the only reason for this and there we get into
more complications.

And why can't we handle all this by just applying an appropriate transform rather
than hacking a non-existent size ?

**Comment by AlexanderScherbatiy** [comment]
> The analysis of the problem sounds fine but then it all gets confusing to me when I come to the fix.
> 
> So first you capture the intended orientation in the switch but do not set it to the printer context. 

The captured orientation is set to `dstPrintInfo` after code for enlarging the paper size in the end of the fix:
```
 [dstPrintInfo setOrientation:orientation];
```

> And I am lost as to why you do this NSPaperOrientation orientation = [dstPrintInfo orientation];
> but promptly over-write the result in the switch statement.

Yes. The default value is not necessary for orientation in this case. I will update the code to `NSPaperOrientation orientation;`

> Then we get to this code :
```
    NSSize size = [dstPrintInfo paperSize];
    // Enlarge height only for cases 1 and 4.
    if ([dstPrintInfo orientation] == NS_LANDSCAPE && size.width > size.height) {
        size.height = size.width + ((orientation == NS_PORTRAIT) ? 1 : 0);
        [dstPrintInfo setPaperSize: size];
    }
```
> So case 1 is intended orientation of PORTRAIT but (1) You are only checking for landscape and
 
The `dstPrintInfo` orientation value is checked after the paper size is applied but before the requested java orientation is set. The `dstPrintInfo` orientation at this point solely depends on the `dstPrintInfo` paper size. For the case 1 the `dstPrintInfo` orientation is landscape (width is greater than height).

> (2) You are doing it on the current printer context, not what is intended. 
> I am probably missing something but I'd like you to point out what it is.

This is the idea of the proposed fix. The fix checks  if the `dstPrintInfo`  page size is consistent with the requested orientation (for example, paper size with width > height does not work with portrait orientation) and enlarge the size for this case.

> Also that last "+ .." condition is odd and un-explained.

For the case 1. where width is greater than height and `dstPrintInfo` orientation is landscape (w>h) enlarging the paper size to [width x width] leaves the `dstPrintInfo` orientation as landscape and setting the requested portrait orientation leads that the rotated image is printed. Enlarging the paper size to [width x (width + 1)] updates the `dstPrintInfo` orientation to portrait which allows to print non rotated image after setting the requested portrait orientation.
The idea of the "+" sign is to enlarge the paper size to be consistent with the requested orientation which is set after that.
 
> But then we get to the bigger question(s) Are all the settings in sync / agreement after this ? Is the clip correct ? What if the changed size now matches a different paper ? - The ability to set paper size at all here is a relic of when there was no way to find out the real paper sizes. Papers which don't exist should not be used. Continuous feed is probably the only reason for this and there we get into more complications.

The proposed fix suggests some intermediate solution between the right behavior (requested paper size and orientation are used) and the initial behavior where the default page size was always used (before JDK-8167102 and its dependent fixes).
It is not clear for me how the right behavior can be implemented with NSPrintInfo class which does not allow to have both a paper size with width is greater than height and a portrait orientation at the same time.

I agree that it would be better to find the solution which does not affect the requested paper size.

To discuss the issue in general I prepared the pure Objective-C code which uses Cocoa NSPrint and NSPrintInfo classes to print an image and illustrates the issue with the paper size and orientation: [main.m](https://bugs.openjdk.org/secure/attachment/101275/main.m).
The instruction to run the code on macOS is described in [JDK-8295737](https://bugs.openjdk.org/browse/JDK-8295737?focusedCommentId=14533578&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14533578).

The code first sets the NSPrintInfo size to 300x100 and the orientation to portrait:
```
    [printInfo setPaperSize: imageSize];
    [printInfo setOrientation: NS_PORTRAIT]; 
```
The output is:
```
 print info: set image size [300.000000, 100.000000]
 print info orientation: [1] NS_LANDSCAPE, size: [300.000000, 100.000000]
 print info: set orientation NS_PORTRAIT
 print info orientation: [0] NS_PORTRAIT, size: [100.000000, 300.000000] 
```

The papers size is changed from the requested 300x100 to 100x300.

If the order of setting the paper size and orientation is manually reversed in the code:
```
    [printInfo setOrientation: NS_PORTRAIT];
    [printInfo setPaperSize: imageSize];
```
The output is:
```
 print info: set orientation NS_PORTRAIT
 print info orientation: [0] NS_PORTRAIT, size: [612.000000, 792.000000]
 print info: set image size [300.000000, 100.000000]
 print info orientation: [1] NS_LANDSCAPE, size: [300.000000, 100.000000] 
```
The resulting orientation is landscape.

What is not clear for me, what is the right way to set both 300x100 paper size and the portrait orientation in this case?

> And why can't we handle all this by just applying an appropriate transform rather than hacking a non-existent size ?

This is interesting idea. Could you give more details about it?

What I see that the issue is not that a printed output is rotated in some way.
The issue is that setting the paper size (width is greater than height) to NSPrintInfo first and the Portrait orientation after that leads to the swapped paper size in NSPrintInfo. So the image is correctly placed on the page but the paper size has been updated because it is not consistent with the requested orientation.
Could transformations improve the situation?

**Comment by prrace** [comment]
The printer doesn't pull paper from a different physically oriented tray when you
request landscape.

Landscape is just portrait rotated by +/- 90 degrees. And vice versa.
Ultimately a transform is being applied to rotate the rendering so rather than
changing the width and height instead rotate by 90 degrees.

I'd have to hunt it down but somewhere .. some case .. some platform in the
printing code I recall we do this for cases where the platform doesn't support
an orientation -  REVERSE_LANDSCAPE.
That might help a little but I think that may be in shared code ..
hmm .. looks like macOS code doesn't attempt to support that mode at all.
>        // AppKit printing doesn't support REVERSE_LANDSCAPE. Radar 2960295.

Something else that could be fixed via a transform

I am not 100% sure it can still be done solely in macOS specific code,
It may need to touch something in the macOS CPrint* java classes
if the Java-level graphics transform is what would need to be adjusted.

But it could perhaps be handled by specifying a transform on
the PrinterView (JDK's subclass of NSView)

I don't have any more specific pointer than that .. I'd have to go try it .. which
isn't on my radar ..

**Comment by AlexanderScherbatiy** [comment]
Suppose there is an [image](https://bugs.openjdk.org/secure/attachment/101295/image-PORTRAIT-600x200.png) with size 600x200. It is necessary to print only region [0, 0, 300, 100] of the image using page size 300x100 and portrait orientation (case 1).

The java code which prints only part of the image with the given page size and orientation could look like:
```
        PageFormat pageFormat = printerJob.getPageFormat(null);
        pageFormat.setOrientation(PageFormat.PORTRAIT);
        Paper paper = pageFormat.getPaper();
        paper.setSize(300, 100);
        paper.setImageableArea(0, 0, 300, 100);
        pageFormat.setPaper(paper);
```

First, I would check how the image can be printed with pure Cocoa code using NSImageView, NSPrintInfo, and NSPrintOperation classes and transformations.

The NSImageView rotation can be implemented as:
```
@interface SampleImageView : NSImageView
@end

@implementation SampleImageView
 - (void)drawRect:(NSRect)dirtyRect {
    NSAffineTransform *transform = [[NSAffineTransform alloc] init];
    [transform rotateByDegrees: 90.0];
    [transform concat]; 
    [super drawRect:dirtyRect];
}
@end
```

The Cocoa pseudo code which prints the image is:
```
NSImageView *nsImageView = // create NSImageView with the given image
// apply clip and transformations to the nsImageView
NSPrintInfo* printInfo = // create NSPrintInfo
// set printInfo page size
NSPrintOperation* loop = [NSPrintOperation printOperationWithView:nsImageView printInfo:printInfo];
```

The question which is not clear for me, which page size needs to be used for the code `// set printInfo page size`?

Should it be the requested size 300x100? Setting page size 300x100 to NSPrintInfo implies that it is applied to landscape orientation. The result page size is rotated by 90 degree comparing to the portrait orientation. May be there are transforms which can be applied to NSPrintInfo for page size rotation?

Should the default page size be used instead? So the NSImageView is translated, rotated, and clipped but it is printed to the page with default page size?

**Comment by AlexanderScherbatiy** [comment]
This is the comment which I found in the NSPrintInfo.h file from MacOSX sdk:
```
/* Set or get the values of the paper attributes. Because an NSPrintInfo's paper name,
 paper size, and orientation attributes must be kept consistent, invocation of any of
 the setting methods in this group may affect the values returned by subsequent invocations
 of any of the getting methods in this group. For example, paper name and paper size
 must always agree, and the value returned by -paperSize always takes
 orientation into account.
*/
@property (nullable, copy) NSPrinterPaperName paperName;
@property NSSize paperSize;
@property NSPaperOrientation orientation;
```

macOS Mojave, version 10.14.5
file: `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Versions/C/Headers/NSPrintInfo.h`

**Comment by AlexanderScherbatiy** [comment]
This is an example which is written in JavaFX and prints a rectangle on page with paper size 300x100 with portrait orientation [FxPrintImageWithHelper.java](https://bugs.openjdk.org/secure/attachment/101461/FxPrintImageWithHelper.java).
Actually JavaFX has set of predefined paper sizes all of which have width less than height: [Paper.java](https://github.com/openjdk/jfx/blob/7f17447aa44fbf5b09aaa2b699266dac8b50cea1/modules/javafx.graphics/src/main/java/javafx/print/Paper.java#L127). `Paper` class does not allow to create a paper with arbitrary paper size because its constructor has default access modifier.

`FxPrintImageWithHelper`  sample uses [PrintHelper.java](https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/com/sun/javafx/print/PrintHelper.java) helper class from `com.sun.javafx.print` package with public `createPaper(...)` method.

The sample properly prints a rectangle on Linux. The rectangle is truncated when it is printed on macOS.

Run `FxPrintImageWithHelper` with jdk8:
```
<jdk8>/bin/java FxPrintImageWithHelper
```
Printed page on macOS: [jfx-image-300x100-portrait-jdk8.pdf](https://bugs.openjdk.org/secure/attachment/101463/jfx-image-300x100-portrait-jdk8.pdf)


Run `FxPrintImageWithHelper` with jdk17:
```
<jdk17>/bin/java --add-exports javafx.graphics/com.sun.javafx.print=ALL-UNNAMED  FxPrintImageWithHelper
```
Printed page on macOS: [jfx-image-300x100-portrait-jdk17.pdf](https://bugs.openjdk.org/secure/attachment/101462/jfx-image-300x100-portrait-jdk17.pdf)

**Comment by AlexanderScherbatiy** [comment]
Could you review the updated fix?

I updated the sample which prints 4 rectangles: [PrintArrowPaperA5](https://bugs.openjdk.org/secure/attachment/101839/PrintArrowPaperA5.java).
The main difference with the previous sample [CutOffImage](https://bugs.openjdk.org/secure/attachment/101145/CutOffImage.java) is that the image generation is based on the provided PageFormat class passed to the `Printable.print(Graphics graphics, PageFormat pageFormat, int index)` method:
``` 
    private static void paintImage(Graphics2D g, PageFormat page, int pageIndex) {
        BufferedImage img = createImage((int) page.getWidth(), (int) page.getHeight(), page.getOrientation(), pageIndex);
        g.drawImage(img, 0, 0, null);
    }

    private static class TestPrintable implements Printable {

        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int index) {
            paintImage((Graphics2D) graphics, pageFormat, index);
            return PAGE_EXISTS;
        }
    }
``` 
PrintArrowPaperA5 sample uses A5 paper size which allows to test it with real printer where A5 paper could be palced horizontally or vertically in the paper tray.

PrintArrowPaperA5 sample prints  four rectangles
1. size 5.8 × 8.3 inches (width < height), portrait orientation
2. size 5.8 × 8.3 inches (width < height), landscape orientation
3. size 8.3 × 5.8 inches (width > height), portrait orientation
4. size 8.3 × 5.8 inches (width > height), landscape orientation

jdk 19 only correctly prints rectangles 1 and 2 (width < height) on macOS: [print-arrow-paper-a5-macos-jdk19.pdf](https://bugs.openjdk.org/secure/attachment/101840/print-arrow-paper-a5-macos-jdk19.pdf)
Rectangles 3 and 4 (width > height) are truncated.

MacOS NSPrintInfo class has one to one correspondence between a paper size and its orientation:
a. (w < h) <-> portrait
b. (w > h) <-> landscape

The proposed fix adds FlipPageFormat class which is intermediate between PageFormat and NSPrintInfo and is created only if PageFormat contains a paper with width greater than height.

FlipPageFormat establish the following relations:

3. PageFormat: (width > height), portrait orientation
-> FlipPageFormat: (width < height), landscape orientation
-> NSPrintInfo: (width > height) (landscape orientation)

4. PageFormat: (width > height), landscape orientation
-> FlipPageFormat: (width < height), portrait orientation
-> NSPrintInfo: (width < height) (portrait orientation)

FlipPageFormat preserves the original PageFormat class to pass it to a user defined `Printable.print(Graphics, PageFormat, int)` method.

`PageFormat pageFormat = pageable.getPageFormat(pageIndex);` line is changed to 
`PageFormat pageFormat = getPageFormat(pageIndex);` 
in the method `getPageformatPrintablePeekgraphics(final int pageIndex)`
to uniformly get FlipPageFormat class from `private PageFormat getPageFormat(int pageIndex)` method.

With the fix PrintArrowPaperA5 sample prints pages with paper width greater than height without truncation on macOS: [print-arrow-paper-a5-macos-jdk-fix.pdf](https://bugs.openjdk.org/secure/attachment/101841/print-arrow-paper-a5-macos-jdk-fix.pdf).

**Comment by tresf** [comment]
Bumping for bots.

**Comment by tresf** [comment]
Bumping for bots

**Comment by tresf** [comment]
Bumping for bots

**Comment by AlexanderScherbatiy** [comment]
Could you review the updated fix?

Initially A5 paper size was used because if a printer supports both A4 and A5 paper sizes it is possible to orient A5 paper with both ways (horizontally and vertically) in the printer paper tray.
The test is able to reproduce the issue with A4 paper size as well.
The test is updated to use A4 paper size and renamed to PrintContentCutOffTest.

The test drew a message with incorrect size because it used PageFormat size which returns the transformed Paper size.
I have updated the test to draw both the Paper and the PageFormat size.
The test itself uses PageFormat size to get drawn image area. This looks consistent with the [2D Basic Printing Program](https://docs.oracle.com/javase/tutorial/2d/printing/printable.html). The Basic Printing Program uses PageFormat.getImageableX()/Y() values in `print(Graphics g, PageFormat pf, int page)` method and PageFormat.getImageableX()/Y() methods also return transformed Paper.getImageableX()/Y() values.

This is the updated test printed to PDF on macOS with
- [jdk-19 without the fix](https://bugs.openjdk.org/secure/attachment/102808/print-a4-jdk19.pdf)
- [built jdk with the fix](https://bugs.openjdk.org/secure/attachment/102809/print-a4-jdk-fix.pdf)

P3 has portrait orientation with Paper width greater than height
P4 has landscape orientation with Paper width greater than height

**Review by prrace — COMMENTED** [review]
This is better. 
I have some test instruction improvements to suggest to avoid bug reports
I suggest that for (3) in the test instructions you make the text :

3. Check that 4 printed rectangles (one per page) have fully drawn 8 vertical areas labeled from 1 to 8,
   and that the blue diagonal lines end at the corners of the yellow rectangle.
  [Note: those are the pass/fail criteria. The messages printed in red are only informative and should not be used as a reason to file a bug].

I'm hoping that will avoid any confusion along the lines of "Page 3 says it is portrait but
it looks landscape to me, so I think I will file a bug report".

FWIW my mac's print-to-pdf is only offering Letter .. but it seems to work anyway.

**Comment by AlexanderScherbatiy** [comment]
The test instruction improvements are added to the test.

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
