### PR TITLE
8327380: Add tests for Shenandoah barrier expansion optimization

### PR DESCRIPTION
**Pull request by tabjy**
The Ideal graph for Shenandoah barrier expansion is optimized so that unnecessary checks are eliminated; however, currently there is no test cases to determine these optimizations are in effect.

Adding unit tests with the IR test framework will support related code changes in the future.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327380](https://bugs.openjdk.org/browse/JDK-8327380): Add tests for Shenandoah barrier expansion optimization (**Enhancement** - P5)

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18814/head:pull/18814` \
`$ git checkout pull/18814`

Update a local copy of the PR: \
`$ git checkout pull/18814` \
`$ git pull https://git.openjdk.org/jdk.git pull/18814/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18814`

View PR using the GUI difftool: \
`$ git pr show -t 18814`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18814.diff">https://git.openjdk.org/jdk/pull/18814.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18814#issuecomment-2122777366)

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by shipilev — APPROVED** [review]

**Comment by shipilev** [comment]
Please merge from current master to get a clean test re-run first?

**Comment by shipilev** [comment]
OK, thanks. Please re-issue `/integrate`.

**Comment by tabjy** [comment]
> OK, thanks. Please re-issue /integrate.

Oops I forgot to do that. Thanks for the reminder (and the review)!

**Pull request closed without merging**
