### PR TITLE
8286401: Address possibly lossy conversions in Microbenchmarks

### PR DESCRIPTION
**Pull request by cl4es**
#8599 would add a new warning. This address the conversions in the microbenchmark component by means of making the types precise or adding explicit casts. There's quite a few changes in the ByteBuffers benchmarks, but the real change is in the template as these are generated.

I've run through a subset of the affected benchmarks and verified that the results are either neutral or improve somewhat (seem to be the case in a few of the ByteBuffer micros).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286401](https://bugs.openjdk.java.net/browse/JDK-8286401): Address possibly lossy conversions in Microbenchmarks

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Eric Caspole](https://openjdk.java.net/census#ecaspole) (@ericcaspole - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8654/head:pull/8654` \
`$ git checkout pull/8654`

Update a local copy of the PR: \
`$ git checkout pull/8654` \
`$ git pull https://git.openjdk.java.net/jdk pull/8654/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8654`

View PR using the GUI difftool: \
`$ git pr show -t 8654`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8654.diff">https://git.openjdk.java.net/jdk/pull/8654.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
I have questions. Also, copyright dates are not consistently updated in affected files?

**Review by shipilev — APPROVED** [review]

**Comment by cl4es** [comment]
Thanks for reviewing. I'll let the GHA tests complete and integrate this tomorrow if all is clear.

**Comment by ericcaspole** [comment]
Looks good.

**Review by ericcaspole — APPROVED** [review]
Looks good, thanks for fixing this.

**Comment by shipilev** [comment]
> Thanks for reviewing. I'll let the GHA tests complete and integrate this tomorrow if all is clear.

I don't think GHA builds any microbenchmarks (because JMH is not enabled there), so there is no point to wait for those.

**Comment by cl4es** [comment]
> > Thanks for reviewing. I'll let the GHA tests complete and integrate this tomorrow if all is clear.
> 
> I don't think GHA builds any microbenchmarks (because JMH is not enabled there), so there is no point to wait for those.

Good to know, thanks. 

/integrate

**Pull request closed without merging**
