### PR TITLE
8286200: SequenceInputStream::read(b, off, 0) returns -1 at EOF

### PR DESCRIPTION
**Pull request by bplb**
Modify the specification of `SequenceInputStream.read(byte[],int,int)` to indicate that `-1` is returned at the EOF of the last stream even if `len` is zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8286200](https://bugs.openjdk.java.net/browse/JDK-8286200): SequenceInputStream::read(b, off, 0) returns -1 at EOF
 * [JDK-8286675](https://bugs.openjdk.java.net/browse/JDK-8286675): SequenceInputStream::read(b, off, 0) returns -1 at EOF (**CSR**)

### Reviewers
 * @rgiulietti (no known github.com user name / role)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8664/head:pull/8664` \
`$ git checkout pull/8664`

Update a local copy of the PR: \
`$ git checkout pull/8664` \
`$ git pull https://git.openjdk.java.net/jdk pull/8664/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8664`

View PR using the GUI difftool: \
`$ git pr show -t 8664`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8664.diff">https://git.openjdk.java.net/jdk/pull/8664.diff</a>

</details>

### CODE REVIEW

**Comment by bplb** [comment]
The `InputStream.read(byte[],int,int)` specification indicates

```
If len is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt
to read at least one byte. If no byte is available because the stream is at end of file,
the value -1 is returned; otherwise, at least one byte is read and stored into b.
```

so that zero should be returned if `len` is zero regardless of anything else. `SequenceInputStream` does not follow this so its specification should be modified to document the existing, longstanding behavior.

A CSR will be filed once there is consensus here.

**Comment by rgiulietti** [comment]
Also, in the current implementation, when the end of the last contained stream has been reached and `-1` is returned, none of the arguments is checked, so a caller can pass `null` for `b` or out of bounds indices `off` and `len`. This is at odd with the `@throws` clauses.

**Comment by bplb** [comment]
> I think the same change shall apply to the `@throws NullPointerException` clause.

Yeah looks like it.

**Comment by bplb** [comment]
> > I think the same change shall apply to the `@throws NullPointerException` clause.
> 
> Yeah looks like it.

Fixed by commit 111ea3e2f4203f05d17431953a5ffaa868176f98.

**Review by rgiulietti — APPROVED** [review]
_(not a reviewer)_
Looks good

**Comment by bplb** [comment]
> In the throws clauses, I think I would have put the additional conditional at the end of the sentence since the existing throws text corresponds to the exception. But the logic is correct as is.

I put it at the beginning as that is the ordering but I see  your point.

**Pull request closed without merging**
