### PR TITLE
8279887: 2 Null pointer dereference defect groups in os_posix.cpp

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small fix to prevent possible Null pointer dereferences.  The fix adds a Null check to prevent trying to park a Null thread.  The Null check is needed because UNSAFE_ENTRY calls thread_from_jni_environment(), which returns NULL if the env thread is terminated. 

The fix was tested with Mach5 tiers 1-2 on Linux, Mac OS, and Windows, and Mach5 tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279887](https://bugs.openjdk.java.net/browse/JDK-8279887): 2 Null pointer dereference defect groups in os_posix.cpp

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to fcde3737703f9268f7237bdbadf2751ca053bbf3

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7129/head:pull/7129` \
`$ git checkout pull/7129`

Update a local copy of the PR: \
`$ git checkout pull/7129` \
`$ git pull https://git.openjdk.java.net/jdk pull/7129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7129`

View PR using the GUI difftool: \
`$ git pr show -t 7129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7129.diff">https://git.openjdk.java.net/jdk/pull/7129.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good to me. Seems like returning NULL for an impossible case is ok, since that's what UnPark does.

**Comment by dholmes-ora** [comment]
Hi Harold,

This is a false positive - you can only park the current thread hence it can never be NULL.

Cheers,
David

**Comment by coleenp** [comment]
> This is a false positive - you can only park the current thread hence it can never be NULL.

I don't think the static analysis tools can know that, but adding a comment and returning NULL seems to be a fix that can please both the static analysis tools and readers of the code.

**Comment by dholmes-ora** [comment]
When the static analysis tool is wrong we ignore it and give feedback to the tool authors. We don't pollute our code with unnecessary checks for impossible situations. We have hit this many times in the past with parfait because it it could not track state across the Java->VM boundary.

**Comment by chhagedorn** [comment]
Could turning this into a sanity assertion check with the comment as a failure message be an option instead?

**Comment by dholmes-ora** [comment]
> Could turning this into a sanity assertion check with the comment as a failure message be an option instead?

You mean as a way to circumvent the tool? Perhaps - though I would not want to do that either as this is a problem that could be seen in many call-chains that use JVM_ENTRY (and other cases) to get the "thread". In any case this has been reported as a false positive now.

What I may do is a RFE to add `current_thread_from_jni_environment` which will never return NULL and so avoid the issue altogether.

Cheers,
David

**Comment by chhagedorn** [comment]
> > Could turning this into a sanity assertion check with the comment as a failure message be an option instead?
> 
> You mean as a way to circumvent the tool? 

Yes.

> Perhaps - though I would not want to do that either as this is a problem that could be seen in many call-chains that use JVM_ENTRY (and other cases) to get the "thread". In any case this has been reported as a false positive now.

I see, thanks for the explanation David! Then I think it was the right way to report it as false positive.

**Comment by hseigel** [comment]
Closing this pull request because this is not an issue.  It's a false positive reported by the static analysis tool.

**Pull request closed without merging**
