### PR TITLE
8247872: Upgrade HarfBuzz to the latest 2.7.2

### PR DESCRIPTION
**Pull request by prrace**
This upgrades JDK to import the current 2.7.2 version of harfbuzz - an OpenType text shaping library

https://bugs.openjdk.java.net/browse/JDK-8247872

This has passed building and headless and headful automated tests on all platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8247872](https://bugs.openjdk.java.net/browse/JDK-8247872): Upgrade HarfBuzz to the latest 2.7.2

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/993/head:pull/993`
`$ git checkout pull/993`

### CODE REVIEW

**Comment by prrace** [comment]
Aside from the code change there is a small build change is to remove some obsolete defines

**Review by magicus — APPROVED** [review]
Build changes look good.

**Review by magicus — COMMENTED** [review]
I'm just a bit curious about the added, empty, `src/java.desktop/share/native/libharfbuzz/abc.txt`...

If it really is in upstream source, I'm not saying you should remove it. It just looks very odd. It's not a merge artifact?

(I could not even add review comments to an empty file in github!  😮)

**Comment by prrace** [comment]
> I'm just a bit curious about the added, empty, `src/java.desktop/share/native/libharfbuzz/abc.txt`...
> 
> If it really is in upstream source, I'm not saying you should remove it. It just looks very odd. It's not a merge artifact?
> 
> (I could not even add review comments to an empty file in github! 😮)

oops. that should not have been in that folder. It was me practicing a different white space removal script.
I thought I checked for any extraneous files. I'll get rid of it now.

**Comment by mrserb** [comment]
Looks like the build on macOS via GitHub will be broken by this fix?

**Comment by magicus** [comment]
@mrserb Good catch! Yes indeed, it looks like `range-loop-analysis` needs to be disabled for clang for Xcode 12 to not complain.

**Comment by prrace** [comment]
I added that to the disabled warnings .. now I suppose the actions will re-run but I don't see any sign of it yet.
Just that the results that were there are now gone.
A few thoughts on this 
- github sends so many messages that it is easy to miss the important ones
- using the default for github we are at the whim of when ever they switch and if this change
   had been pushed 6 weeks ago likely it would have passed until the day github upgraded.
- it also means passing a github build does not guarantee it will pass on the "official" toolchains.

**Comment by magicus** [comment]
@prrace I agree, the github actions are a double-edged sword -- at best. At worst, it's a clear regression in terms of how we work. :-(

We might need to take a step back and rethink this.

Anyway, your changes looks good from a build PoV now.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
