### PR TITLE
8305481: gtest is_first_C_frame failing on ARM

### PR DESCRIPTION
**Pull request by vpa1977**
os::current_frame() is stubbed out on the Linux Arm Thumb platform [1]
This causes gtest 'is_first_C_frame' to fail. 

```
[ RUN      ] os.is_first_C_frame_vm
./test/hotspot/gtest/runtime/test_os.cpp:890: Failure
Value of: os::is_first_C_frame(&cur_frame)
  Actual: true
Expected: false
[  FAILED  ] os.is_first_C_frame_vm (0 ms)
```
This pull request disables the test for ARM Thumb.

[1] https://github.com/openjdk/jdk/blob/0deb648985b018653ccdaf193dc13b3cf21c088a/src/hotspot/os_cpu/linux_arm/os_linux_arm.cpp#L219

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305481](https://bugs.openjdk.org/browse/JDK-8305481): gtest is_first_C_frame failing on ARM

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13292/head:pull/13292` \
`$ git checkout pull/13292`

Update a local copy of the PR: \
`$ git checkout pull/13292` \
`$ git pull https://git.openjdk.org/jdk.git pull/13292/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13292`

View PR using the GUI difftool: \
`$ git pr show -t 13292`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13292.diff">https://git.openjdk.org/jdk/pull/13292.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13292#issuecomment-1494942019)

### CODE REVIEW

**Comment by jerboaa** [comment]
Created this bug for you so you can add it to this PR. https://bugs.openjdk.org/browse/JDK-8305481

**Comment by vpa1977** [comment]
Pipeline fails with due to 'runtime/ErrorHandling/TestDwarf.java' failure.

**Review by tstuefe — APPROVED** [review]
Ok and trivial (meaning you only need one Reviewer).

**Pull request closed without merging**
