### PR TITLE
8342181: Update tests to use stronger Key and Salt size

### PR DESCRIPTION
**Pull request by fguallini**
Several tests currently use weak key and salt sizes. Since the purpose of these tests is not to evaluate weak keys, they can be updated to use stronger keys length (2048-bits) and stronger Salt (16 bytes). This PR does not intend to update the tests to use stronger algorithms.

There is no significant increase in tests run time, those still complete consistently fast (few seconds).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342181](https://bugs.openjdk.org/browse/JDK-8342181): Update tests to use stronger Key and Salt size (**Sub-task** - P2)

### Reviewers
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)
 * [Anthony Scarpino](https://openjdk.org/census#ascarpino) (@ascarpino - **Reviewer**) Review applies to [7c42d581](https://git.openjdk.org/jdk/pull/21537/files/7c42d5815ab73948d1bc1b50b765c2aed81bec8b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21537/head:pull/21537` \
`$ git checkout pull/21537`

Update a local copy of the PR: \
`$ git checkout pull/21537` \
`$ git pull https://git.openjdk.org/jdk.git pull/21537/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21537`

View PR using the GUI difftool: \
`$ git pr show -t 21537`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21537.diff">https://git.openjdk.org/jdk/pull/21537.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21537#issuecomment-2419279355)
</details>

### CODE REVIEW

**Comment by rhalade** [comment]
Can key size and salt size be configurable somehow; either as system property or a constant? This will make it easier to modify in future without updating all these tests again.

**Comment by wangweij** [comment]
Have you timed the differences? I remember we've deliberately used small key sizes for RSA and DSA in some tests because large sizes could be very slow.

**Comment by fguallini** [comment]
@wangweij Yes, test execution time was taken into consideration. A few tests were generating keys in a loop, which significantly increased their execution time; so those tests were not included in this PR. Only tests that did not have a significant impact on execution time, only a for few seconds, were included. None of these test run for longer than 30 seconds, and the **total** execution time for the group has only increased by 10-30 seconds depending on the platform

**Review by rhalade — APPROVED** [review]
Thanks for the updates Fernando! LGTM.

**Review by ascarpino — APPROVED** [review]

**Review by rhalade — APPROVED** [review]

**Pull request closed without merging**
