### PR TITLE
8261532: Archived superinterface class cannot be accessed

### PR DESCRIPTION
**Pull request by calvinccheung**
Problem: If an interface is in the CDS archive but not the class which implements the interface. During runtime, IllegalAccessError will result when the class is being loaded.

Fix:
In `InstanceKlass::set_packge()` when checking if we can use a saved copy of the` _package_entry`, add a NULL check for `_package_entry` before returning. In `SystemDictionaryShared::prepare_shared_lambda_proxy_class()`, we can obtain the `_package_entry` directly from the `caller_ik` instead of calling `get_package_entry_from_class()`.

Testing: passed mach5 tiers 1 - 4 tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261532](https://bugs.openjdk.java.net/browse/JDK-8261532): Archived superinterface class cannot be accessed

### Reviewers
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2820/head:pull/2820`
`$ git checkout pull/2820`

### CODE REVIEW

**Review by yminqi — APPROVED** [review]
LGTM.

**Review by iklam — APPROVED** [review]
Looks good to me.

**Comment by calvinccheung** [comment]
@yminqi @iklam Thanks for your review!

**Pull request closed without merging**
