### PR TITLE
8260501: [Vector API] Improve register usage for shift operations on x86

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

I found the register usage is less optimized for some shift operations.
```
For example, vshiftL_imm [1]/vshiftI_imm require dst != src.
But it's actually fine for the register allocator to assign dst == src.

Also, vshiftL [2]/vshiftI/vshiftS require dst != src.
But it's actually required for UseAVX==0 only.
For the most common cases (UseAVX > 0), it's fine to assign dst == src.
```

The fix splits vshiftS/vshiftI/vshiftL into UseAVX > 0 and UseAVX == 0 cases.
And just removes the unreasonable requirement for vshiftI_imm and vshiftL_imm. 

Testing:
  - jdk/incubator/vector/ on x64 with UseAVX=3/2/1/0, no regression

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L6058
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L6037

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260501](https://bugs.openjdk.java.net/browse/JDK-8260501): [Vector API] Improve register usage for shift operations on x86

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2257/head:pull/2257`
`$ git checkout pull/2257`

### CODE REVIEW

**Comment by iwanowww** [comment]
IIRC AD instructions for variable shifts were deliberately merged to reduce static footprint of the JVM on x86 (JVM library size). IMO it's preferable to leave them as they are.

**Comment by DamonFool** [comment]
> IIRC AD instructions for variable shifts were deliberately merged to reduce static footprint of the JVM on x86 (JVM library size). IMO it's preferable to leave them as they are.

Hi @iwanowww  ,

I didn't know that variable shifts were deliberately merged to reduce the size of libjvm.so.
Thanks for your clarification.

With the original patch, the size of libjvm.so on Linux/x64 will be increased by ~0.085%.

However, vshiftL_imm and vshiftI_imm can still be optimized without increasing the binary size.
And the size of libjvm.so will be further decreased by ~0.003% with the updated patch on Linux/x64.
So are you OK with it?

Thanks.
Best regards,
Jie

**Comment by iwanowww** [comment]
> With the original patch, the size of libjvm.so on Linux/x64 will be increased by ~0.085%.

Just wanted to point out that it was a deliberate compromise. Small things quickly add up and there was a noticeable static footprint increase from Vector API support due to numerous new AD instructions added. (There's still room for improvement, but the refactorings targeted at reducing the overall number of AD instructions allowed to keep it under control.)

There were other cases where generated code quality could worsen a bit and I don't want to see subsequent patches to revert those changes unless there are compelling code quality improvements.  

> However, vshiftL_imm and vshiftI_imm can still be optimized without increasing the binary size.
> And the size of libjvm.so will be further decreased by ~0.003% with the updated patch on Linux/x64.
> So are you OK with it?

Yes, I do. And normally I don't have concerns about footprint increase from adding individual AD instructions. It's specific to vectorization support that stretches C2 in unusual ways on x86.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by DamonFool** [comment]
> > With the original patch, the size of libjvm.so on Linux/x64 will be increased by ~0.085%.
> 
> Just wanted to point out that it was a deliberate compromise. Small things quickly add up and there was a noticeable static footprint increase from Vector API support due to numerous new AD instructions added. (There's still room for improvement, but the refactorings targeted at reducing the overall number of AD instructions allowed to keep it under control.)
> 
> There were other cases where generated code quality could worsen a bit and I don't want to see subsequent patches to revert those changes unless there are compelling code quality improvements.
> 
> > However, vshiftL_imm and vshiftI_imm can still be optimized without increasing the binary size.
> > And the size of libjvm.so will be further decreased by ~0.003% with the updated patch on Linux/x64.
> > So are you OK with it?
> 
> Yes, I do. And normally I don't have concerns about footprint increase from adding individual AD instructions. It's specific to vectorization support that stretches C2 in unusual ways on x86.

Got it and I totally agree with you @iwanowww .
Thanks for your review and comments.

**Review by vnkozlov — APPROVED** [review]
Looks fine to me.
@iwanowww please submit mach5 testing for this change before integration.

**Comment by DamonFool** [comment]
> Looks fine to me.
> @iwanowww please submit mach5 testing for this change before integration.

Thanks @vnkozlov for your review.

@iwanowww , please let me know if it's OK on mach5.
Thanks.

**Comment by iwanowww** [comment]
Test results (hs-tier1 - hs-tier4) are good.

**Comment by DamonFool** [comment]
Thanks @iwanowww .
/integrate

**Pull request closed without merging**
