### PR TITLE
8281469: aarch64: Improve interpreter stack banging

### PR DESCRIPTION
**Pull request by shipilev**
This is the AArch64 counterpart of X86 change: https://github.com/openjdk/jdk/commit/3a13425bc9088cbb6d95e1a46248d7eba27fb1a6.

Motivational performance improvements on Raspberry Pi 3:

```
 Performance counter stats for 'baseline/bin/java -version' (10 runs):

            476.96 msec task-clock                #    1.288 CPUs utilized            ( +-  0.11% )
               166      context-switches          #    0.348 K/sec                    ( +-  0.93% )
                 8      cpu-migrations            #    0.017 K/sec                    ( +-  9.33% )
             2,954      page-faults               #    0.006 M/sec                    ( +-  0.04% )
       560,690,251      cycles                    #    1.176 GHz                      ( +-  0.07% )
       239,068,958      instructions              #    0.43  insn per cycle           ( +-  0.04% )
        30,236,426      branches                  #   63.394 M/sec                    ( +-  0.05% )
         4,145,994      branch-misses             #   13.71% of all branches          ( +-  0.09% )

          0.370225 +- 0.000285 seconds time elapsed  ( +-  0.08% )

 Performance counter stats for 'patched/bin/java -version' (10 runs):

            456.01 msec task-clock                #    1.283 CPUs utilized            ( +-  0.12% )
               156      context-switches          #    0.341 K/sec                    ( +-  0.99% )
                 8      cpu-migrations            #    0.018 K/sec                    ( +-  4.30% )
             2,957      page-faults               #    0.006 M/sec                    ( +-  0.07% )
       536,970,476      cycles                    #    1.178 GHz                      ( +-  0.12% )
       236,527,954      instructions              #    0.44  insn per cycle           ( +-  0.04% )
        30,195,820      branches                  #   66.218 M/sec                    ( +-  0.04% )
         4,128,388      branch-misses             #   13.67% of all branches          ( +-  0.13% )

          0.355460 +- 0.000741 seconds time elapsed  ( +-  0.21% )
```

SPECjvm2008 with `-Xint`:

```
Compress: +54%
Serial: +56%
```

Additional testing:
 - [x] Linux aarch64 fastdebug, `tier1`
 - [x] Linux aarch64 fastdebug, `tier2`
 - [x] Ad-hoc benchmarks

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281469](https://bugs.openjdk.java.net/browse/JDK-8281469): aarch64: Improve interpreter stack banging

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)
 * [Xin Liu](https://openjdk.java.net/census#xliu) (@navyxliu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8001/head:pull/8001` \
`$ git checkout pull/8001`

Update a local copy of the PR: \
`$ git checkout pull/8001` \
`$ git pull https://git.openjdk.java.net/jdk pull/8001/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8001`

View PR using the GUI difftool: \
`$ git pr show -t 8001`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8001.diff">https://git.openjdk.java.net/jdk/pull/8001.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]
Hard to argue with that.

**Review by navyxliu — APPROVED** [review]
LGTM. I am not a reviwer. need other reviewer to approve it. 

One subtlety is that sub can only encode uimm24.  I think it's safe for page size = 4k because it can support up to 2^12 p.

**Comment by theRealAph** [comment]
> LGTM. I am not a reviwer. need other reviewer to approve it.
> 
> One subtlety is that sub can only encode uimm24. I think it's safe for page size = 4k because it can support up to 2^12 p.

It'll be fine. See `MacroAssembler::sub(Register Rd, Register Rn, RegisterOrConstant decrement)`

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
