### PR TITLE
JDK-8314194: Reusing CyclicBarrier, it should be possible to change the barrierCommand

### PR DESCRIPTION
**Pull request by chenggwang**
Sorry, my description in Issue JDK-8314194(which I submitted) is ambiguous and makes you think of Phaser. My intention is that each generation of CyclicBarrier barrierCommand can change. Let me give you a scenario
For example, the U.S. Army 'Gordon Sullivan Cup'.
Five tanks competing.
1. The first round is for artillery strikes against targets.
2. Second round of anti-aircraft machine gun targets.
3. The third round is minefield racing.
The scoring criteria are different for each round, so the CyclicBarrier's barrierCommand should be different for each round. But in the current code, `private final Runnable barrierCommand`, constructing the CyclicBarrier instance is already determined to be unchangeable.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314194](https://bugs.openjdk.org/browse/JDK-8314194): Reusing CyclicBarrier, it should be possible to change the barrierCommand (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15239/head:pull/15239` \
`$ git checkout pull/15239`

Update a local copy of the PR: \
`$ git checkout pull/15239` \
`$ git pull https://git.openjdk.org/jdk.git pull/15239/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15239`

View PR using the GUI difftool: \
`$ git pr show -t 15239`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15239.diff">https://git.openjdk.org/jdk/pull/15239.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15239#issuecomment-1697272226)

### CODE REVIEW

**Comment by chenggwang** [comment]
> Hi, please send an e-mail to [dalibor.topic@oracle.com](mailto:dalibor.topic@oracle.com) so that I can mark your OCA as verified.

Hi! I have completed my personal information and re-signed the OCA, which is currently in UNDER REVIEW status. And I have also replied to the email to [dalibor.topic@oracle.com](mailto:dalibor.topic@oracle.com) about the OCA re-signing.

**Comment by chenggwang** [comment]
> Hi, please send an e-mail to [dalibor.topic@oracle.com](mailto:dalibor.topic@oracle.com) so that I can mark your OCA as verified.

Hi! I have completed my personal information and re-signed the OCA, which is currently in UNDER REVIEW status. And I have also replied to the email to [dalibor.topic@oracle.com](mailto:dalibor.topic@oracle.com) about the OCA re-signing.I'm sorry for the trouble.

**Comment by chenggwang** [comment]
@vicente-romero-oracle  @albertnetymk  Hi, can you take a look at this PR for me?

**Comment by chenggwang** [comment]
Hi Can anyone help me to review this PR @sormuras @asotona or any other reviewer?

**Comment by chenggwang** [comment]
> 

AlanBateman，First thank you for coming to review, in this case use:
    For example, the U.S. Army 'Gordon Sullivan Cup'.
  Five tanks competing.
  1. The first round is for artillery strikes against targets.
  2. Second round of anti-aircraft machine gun targets.
  3. The third round is minefield racing.  
  
It takes five threads to represent five tanks in a race,
1. When all five threads reach the first Barrier, execute the first barrierCommand to score and rank the artillery firing.
2. Then continue the second round of anti-aircraft machine gun competition, five threads have reached the second Barrier, and the anti-aircraft machine gun score is determined and ranked.
3. Finally, race in the tank minefield, reach the third Barrier, score and rank

The above three rounds only need to use one CyclicBarrier, because it can open the next generation at the end of each generation, so the CyclicBarrier can be reused, but the barrierCommand is final. Passing barrierCommand when a CyclicBarrier object is created through the constructor is an immutable object that cannot be used with a new barrierCommand every generation. But artillery attacks, anti-aircraft machine guns, minefield scoring rules are different, we need a variable barrierCommand

With the Phaser API, I'm not talking about using it. Instead, someone commented under my bugreport on using Phaser instead of CyclicBarrier. I mention Phaser here, feeling that it can dynamically add and subtract threads, but it doesn't fit my problem with this five-tank race

So you can ignore the phaser I mentioned and go all out to review the five tank races, each scoring criteria is different, that is, barrierCommand should be able to change, but the current version of barrierCommand is final and immutable

**Comment by chenggwang** [comment]
> > Hi Can anyone help me to review this PR @sormuras @asotona or any other reviewer?
> 
> I think you first need to make a case for changing the CyclicBarrier API as opposed to dealing with the phases in your BarrierAction or using the Phaser API.

@AlanBateman，First thank you for coming to review, in this case use:
For example, the U.S. Army 'Gordon Sullivan Cup'.
Five tanks competing.

1. The first round is for artillery strikes against targets.
2. Second round of anti-aircraft machine gun targets.
3. The third round is minefield racing.
It takes five threads to represent five tanks in a race,

1. When all five threads reach the first Barrier, execute the first barrierCommand to score and rank the artillery firing.
2. Then continue the second round of anti-aircraft machine gun competition, five threads have reached the second Barrier, and the anti-aircraft machine gun score is determined and ranked.
3. Finally, race in the tank minefield, reach the third Barrier, score and rank

The above three rounds only need to use one CyclicBarrier, because it can open the next generation at the end of each generation, so the CyclicBarrier can be reused, but the barrierCommand is final. Passing barrierCommand when a CyclicBarrier object is created through the constructor is an immutable object that cannot be used with a new barrierCommand every generation. But artillery attacks, anti-aircraft machine guns, minefield scoring rules are different, we need a variable barrierCommand

With the Phaser API, I'm not talking about using it. Instead, someone commented under my bugreport on using Phaser instead of CyclicBarrier. I mention Phaser here, feeling that it can dynamically add and subtract threads, but it doesn't fit my problem with this five-tank race

So you can ignore the phaser I mentioned and go all out to review the five tank races, each scoring criteria is different, that is, barrierCommand should be able to change, but the current version of barrierCommand is final and immutable

**Comment by chenggwang** [comment]
> > Hi Can anyone help me to review this PR @sormuras @asotona or any other reviewer?
> 
> I think you first need to make a case for changing the CyclicBarrier API as opposed to dealing with the phases in your BarrierAction or using the Phaser API.

Hi @AlanBateman，First thank you for coming to review, in this case use:
For example, the U.S. Army 'Gordon Sullivan Cup'.
Five tanks competing.
1. The first round is for artillery strikes against targets.
2. Second round of anti-aircraft machine gun targets.
3. The third round is minefield racing.

It takes five threads to represent five tanks in a race,
① When all five threads reach the first Barrier, execute the first barrierCommand to score and rank the artillery firing.
② Then continue the second round of anti-aircraft machine gun competition, five threads have reached the second Barrier, and the anti-aircraft machine gun score is determined and ranked.
③ Finally, race in the tank minefield, reach the third Barrier, score and rank

The above three rounds only need to use one CyclicBarrier, because it can open the next generation at the end of each generation, so the CyclicBarrier can be reused, but the barrierCommand is final. Passing barrierCommand when a CyclicBarrier object is created through the constructor is an immutable object that cannot be used with a new barrierCommand every generation. But artillery attacks, anti-aircraft machine guns, minefield scoring rules are different, we need a variable barrierCommand

With the Phaser API, I'm not talking about using it. Instead, someone commented under my bugreport on using Phaser instead of CyclicBarrier. I mention Phaser here, feeling that it can dynamically add and subtract threads, but it doesn't fit my problem with this five-tank race

So you can ignore the phaser I mentioned and go all out to review the five tank races, each scoring criteria is different, that is, barrierCommand should be able to change, but the current version of barrierCommand is final and immutable

**Comment by dholmes-ora** [comment]
As I wrote in the JBS issue and as Alan mentioned again above you can use the single `BarrierAction` object to track the state changes and count the generations/phase:
```
Runnable barrierAction = new Runnable() {
  int phase = 0;
  public void run() {
    switch(phase++) {
      case 0: doArtillery(); break;
      case 1: doAntiAircraft(); nreak;
      case 2: doMinefield(); break;
    }
   void doArtillery() { ... }
   ...
  }
```
I do not believe there is sufficient justification for expanding the `CyclicBarrier` API as proposed.

Happy to hear what @DougLea and @martin-buchholz think about this though.

**Comment by viktorklang-ora** [comment]
I agree with @dholmes-ora — the transition is in/belongs to the action, not the barrier.

**Comment by chenggwang** [comment]
> As I wrote in the JBS issue and as Alan mentioned again above you can use the single `BarrierAction` object to track the state changes and count the generations/phase:
> 
> ```
> Runnable barrierAction = new Runnable() {
>   int phase = 0;
>   public void run() {
>     switch(phase++) {
>       case 0: doArtillery(); break;
>       case 1: doAntiAircraft(); nreak;
>       case 2: doMinefield(); break;
>     }
>    void doArtillery() { ... }
>    ...
>   }
> ```
> 
> I do not believe there is sufficient justification for expanding the `CyclicBarrier` API as proposed.
> 
> Happy to hear what @DougLea and @Martin-Buchholz think about this though.

yeah！

> 



> As I wrote in the JBS issue and as Alan mentioned again above you can use the single `BarrierAction` object to track the state changes and count the generations/phase:
> 
> ```
> Runnable barrierAction = new Runnable() {
>   int phase = 0;
>   public void run() {
>     switch(phase++) {
>       case 0: doArtillery(); break;
>       case 1: doAntiAircraft(); nreak;
>       case 2: doMinefield(); break;
>     }
>    void doArtillery() { ... }
>    ...
>   }
> ```
> 
> I do not believe there is sufficient justification for expanding the `CyclicBarrier` API as proposed.
> 
> Happy to hear what @DougLea and @Martin-Buchholz think about this though.


Thank you @dholmes-ora @viktorklang-ora Your proposal is indeed a good solution! Enhancements and improvements became less urgent.

> As I wrote in the JBS issue and as Alan mentioned again above you can use the single `BarrierAction` object to track the state changes and count the generations/phase:
> 
> ```
> Runnable barrierAction = new Runnable() {
>   int phase = 0;
>   public void run() {
>     switch(phase++) {
>       case 0: doArtillery(); break;
>       case 1: doAntiAircraft(); nreak;
>       case 2: doMinefield(); break;
>     }
>    void doArtillery() { ... }
>    ...
>   }
> ```
> 
> I do not believe there is sufficient justification for expanding the `CyclicBarrier` API as proposed.
> 
> Happy to hear what @DougLea and @Martin-Buchholz think about this though.

Thank you @dholmes-ora @viktorklang-ora Your proposal is indeed a good solution! Enhancements and improvements became less urgent.

**Comment by chenggwang** [comment]
> As I wrote in the JBS issue and as Alan mentioned again above you can use the single `BarrierAction` object to track the state changes and count the generations/phase:
> 
> ```
> Runnable barrierAction = new Runnable() {
>   int phase = 0;
>   public void run() {
>     switch(phase++) {
>       case 0: doArtillery(); break;
>       case 1: doAntiAircraft(); nreak;
>       case 2: doMinefield(); break;
>     }
>    void doArtillery() { ... }
>    ...
>   }
> ```
> 
> I do not believe there is sufficient justification for expanding the `CyclicBarrier` API as proposed.
> 
> Happy to hear what @DougLea and @Martin-Buchholz think about this though.

Thank you @dholmes-ora @viktorklang-ora Your proposal is indeed a good solution! Enhancements and improvements became less urgent.

**Comment by dholmes-ora** [comment]
@chenggwang can you please close this PR and the associated Enhancement request. Thanks

**Comment by Martin-Buchholz** [comment]
We should try to retain designed immutability in concurrency classes.
Having had the experience of having fixed many bugs with knobs tunable at runtime.
If you make a field mutable, you need to think not just about "set", but also about "compare and set", "freeze" and security implications of adding a new form of attack.

So let's leave CyclicBarrier unchanged.

**Comment by chenggwang** [comment]
> We should try to retain designed immutability in concurrency classes. Having had the experience of having fixed many bugs with knobs tunable at runtime. If you make a field mutable, you need to think not just about "set", but also about "compare and set", "freeze" and security implications of adding a new form of attack.
> 
> So let's leave CyclicBarrier unchanged.

Thank you very much, it's an honor to be guided by you, I did overlook the potential safety risks posed by mutable

**Pull request closed without merging**
