### PR TITLE
8345803: Update copyright year to 2024 for security in files where it was missed

### PR DESCRIPTION
**Pull request by magicus**
Some files have been modified in 2024, but the copyright year has not been properly updated. This should be fixed. 

I have located these modified files using:
```
git log --since="Jan 1" --name-only --pretty=format: | sort -u > file.list
```
and then run a script to update the copyright year to 2024 on these files.

I have made a manual sampling of files in the list to verify that they have indeed been modified in 2024.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345803](https://bugs.openjdk.org/browse/JDK-8345803): Update copyright year to 2024 for security in files where it was missed (**Bug** - P4)

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22642/head:pull/22642` \
`$ git checkout pull/22642`

Update a local copy of the PR: \
`$ git checkout pull/22642` \
`$ git pull https://git.openjdk.org/jdk.git pull/22642/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22642`

View PR using the GUI difftool: \
`$ git pr show -t 22642`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22642.diff">https://git.openjdk.org/jdk/pull/22642.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22642#issuecomment-2527855888)
</details>

### CODE REVIEW

**Comment by seanjmullan** [comment]
Have you checked that the Authors are all from Oracle?

**Comment by wangweij** [comment]
```
>>> src/jdk.crypto.cryptoki/share/native/libj2pkcs11/p11_keymgmt.c
* 13cf0707f90 - 8328556: Do not extract large CKO_SECRET_KEY keys from the NSS Software Token (9 months ago) <Martin Balao>
>>> test/jdk/java/security/KeyStore/CheckMacOSKeyChainTrust.java
* 4210e507a0e - 8320362: Load anchor certificates from Keychain keystore (9 months ago) <Alexey Bakhtin>
>>> test/micro/org/openjdk/bench/java/security/SSLHandshake.java
* 06dd7353427 - 8322766: Micro bench SSLHandshake should use default algorithms (11 months ago) <John Jiang>
>>> test/micro/org/openjdk/bench/java/security/TestCertificates.java
* 06dd7353427 - 8322766: Micro bench SSLHandshake should use default algorithms (11 months ago) <John Jiang>
>>> test/micro/org/openjdk/bench/javax/crypto/full/AESGCMBench.java
* a6b318863fa - 8337632: AES-GCM Algorithm optimization for x86_64 (2 months ago) <Smita Kamath>
>>> test/micro/org/openjdk/bench/javax/crypto/full/BenchBase.java
* a6b318863fa - 8337632: AES-GCM Algorithm optimization for x86_64 (2 months ago) <Smita Kamath>
```
These people are probably not from Oracle.

**Comment by magicus** [comment]
> Have you checked that the Authors are all from Oracle?

My understanding is that this is not relevant. Let's continue this discussion off-line.

**Comment by seanjmullan** [comment]
> > Have you checked that the Authors are all from Oracle?
> 
> My understanding is that this is not relevant. Let's continue this discussion off-line.

Thanks for checking. LGTM.

**Review by seanjmullan — APPROVED** [review]

**Pull request closed without merging**
