### PR TITLE
8307458: Add periodic heap usage JFR events

### PR DESCRIPTION
**Pull request by edvbld**
Hi all,

please review this patch that adds two new JFR events:

- `GCHeapMemoryUsage`
- `GCHeapMemoryPoolUsage`

The two new events are periodic (period configurable as usual) and should contain the same information as a call to [`MemoryMXBean.getHeapMemoryUsage`](https://docs.oracle.com/en/java/javase/20/docs/api/java.management/java/lang/management/MemoryMXBean.html#getHeapMemoryUsage()) and/or [`MemoryPoolMXBean.getUsage`](https://docs.oracle.com/en/java/javase/20/docs/api/java.management/java/lang/management/MemoryPoolMXBean.html#getUsage()). Having this data accessible via JFR (in addition to MXBeans) is useful for tools working primarily with JFR recordings, for example [JMC](https://openjdk.org/projects/jmc/).

### Testing
- [x] Tier 1 - 3 on Linux x64, Linux aarch64, Windows x64, macOS aarch64
- [x] Added two new JTReg tests for the new events
- [x] Local testing on macOS aarch64

Thanks,
Erik

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307458](https://bugs.openjdk.org/browse/JDK-8307458): Add periodic heap usage JFR events

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13867/head:pull/13867` \
`$ git checkout pull/13867`

Update a local copy of the PR: \
`$ git checkout pull/13867` \
`$ git pull https://git.openjdk.org/jdk.git pull/13867/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13867`

View PR using the GUI difftool: \
`$ git pr show -t 13867`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13867.diff">https://git.openjdk.org/jdk/pull/13867.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13867#issuecomment-1538444791)

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Review by xmas92 — COMMENTED** [review]
looks good. Just one comment to use `UNTIMED`. Not sure if it matters.
Cannot comment on the default control groups, as I am unsure of their purpose.
But nice to be able to have this information in the JFR recordings.

**Comment by edvbld** [comment]
Thanks @stefank and @xmas92 for reviewing! I added `UNTIMED` to the event instances, thanks @xmas92 for catching this  (and you are correct, it would have worked anyhow, but it is better to be explicit).

**Review by stefank — APPROVED** [review]

**Comment by edvbld** [comment]
Thanks @stefank and @xmas92 for re-reviewing!

/integrate

**Pull request closed without merging**
