### PR TITLE
8271722: [TESTBUG] gc/g1/TestMixedGCLiveThreshold.java can fail if G1 Full GC uses >1 workers

### PR DESCRIPTION
**Pull request by reinrich**
I tried to make this pr is dependent on #4968. Hope this works...

The change fixes a test issue in gc/g1/TestMixedGCLiveThreshold.java by adding
the option `-XX:ParallelGCThreads=1`. This prevents the full gc from running
with more than one worker because if it would do that, live data could be
distributed into several regions and one of them could be selected for
collection which is unexpected with `-XX:G1MixedGCLiveThresholdPercent=25`.

Please refer to the JBS-Item for more details.

Thanks, Richard.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271722](https://bugs.openjdk.java.net/browse/JDK-8271722): [TESTBUG] gc/g1/TestMixedGCLiveThreshold.java can fail if G1 Full GC uses >1 workers

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer) ⚠️ Review applies to 7d7599757c2fdb4768619b2dece6730cb8f5789a
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 7d7599757c2fdb4768619b2dece6730cb8f5789a

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4971/head:pull/4971` \
`$ git checkout pull/4971`

Update a local copy of the PR: \
`$ git checkout pull/4971` \
`$ git pull https://git.openjdk.java.net/jdk pull/4971/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4971`

View PR using the GUI difftool: \
`$ git pr show -t 4971`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4971.diff">https://git.openjdk.java.net/jdk/pull/4971.diff</a>

</details>

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by NikolayTach** [comment]
Can use curl to watch this?

**Comment by reinrich** [comment]
> 
> 
> Can use curl to watch this?

I guess you could...

**Comment by reinrich** [comment]
> 
> 
> The dependent pull request has now been integrated, and the target branch of this pull request has been updated. This means that changes from the dependent pull request can start to show up as belonging to this pull request, which may be confusing for reviewers. To remedy this situation, simply merge the latest changes from the new target branch into this pull request by running commands similar to these in the local repository for your personal fork:
> 
> ```shell
> git checkout JDK-8271721-split-TestMixedGCLiveThreshold
> git fetch https://git.openjdk.java.net/jdk master
> git merge FETCH_HEAD
> # if there are conflicts, follow the instructions given by git merge
> git commit -m "Merge master"
> git push
> ```

Hi @edvbld,

this is my first dependent pr. So far it went well but now I've got issues with the procedure above.

First: ist there a `-b` missing in `git checkout JDK-8271721-split-TestMixedGCLiveThreshold`?

I've executed all the steps above (with -b in the first command) but I still see a commit from #4968 in this pr's commits.

Besides that I don't quite understand how it would help to create that new branch and push it to my personal fork.

I expected merging master into this pr's branch (https://github.com/reinrich/jdk/tree/8271722__TESTBUG__gc_g1_TestMixedGCLiveThreshold_java_can_fail_if_G1_Full_GC_uses__gt_1_workers) would help but that didn't.

Can you help to get rid of the 'start' commit by @tstuefe in this pr's commits?

Cheers, Richard.

**Comment by reinrich** [comment]
> 
> 
> > The dependent pull request has now been integrated, and the target branch of this pull request has been updated. This means that changes from the dependent pull request can start to show up as belonging to this pull request, which may be confusing for reviewers. To remedy this situation, simply merge the latest changes from the new target branch into this pull request by running commands similar to these in the local repository for your personal fork:
> > ```shell
> > git checkout JDK-8271721-split-TestMixedGCLiveThreshold
> > git fetch https://git.openjdk.java.net/jdk master
> > git merge FETCH_HEAD
> > # if there are conflicts, follow the instructions given by git merge
> > git commit -m "Merge master"
> > git push
> > ```
> 
> Hi @edvbld,
> 
> this is my first dependent pr. So far it went well but now I've got issues with the procedure above.
> 
> First: ist there a `-b` missing in `git checkout JDK-8271721-split-TestMixedGCLiveThreshold`?
> 
> I've executed all the steps above (with -b in the first command) but I still see a commit from #4968 in this pr's commits.
> 
> Besides that I don't quite understand how it would help to create that new branch and push it to my personal fork.
> 
> I expected merging master into this pr's branch (https://github.com/reinrich/jdk/tree/8271722__TESTBUG__gc_g1_TestMixedGCLiveThreshold_java_can_fail_if_G1_Full_GC_uses__gt_1_workers) would help but that didn't.
> 
> Can you help to get rid of the 'start' commit by @tstuefe in this pr's commits?
> 
> Cheers, Richard.

Hi @kevinrushforth and @erikj79,

@edvbld seems to be less engaged with skara recently. Maybe you can help me out with the issues described above?

Thanks, Richard.

**Comment by reinrich** [comment]
Thanks for the reviews Albert and Thomas!

/integrate

**Pull request closed without merging**
