### PR TITLE
8251464: make Node::dump(int depth) support indent

### PR DESCRIPTION
**Pull request by navyxliu**
Node::dump(depth) indents 2 whitespaces for each level.
The function isnot on until the depth of the ideal graph isnot greater
than PrintIdealIndentThreshold (0 by default).

/cc hotspot-compiler

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251464](https://bugs.openjdk.java.net/browse/JDK-8251464): make Node::dump(int depth) support indent

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to 2c5376f092f50a6e918f6730a472de9a64cca6ee

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/371/head:pull/371`
`$ git checkout pull/371`

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
This looks good to me but please make sure that there are no other tests depending on the tab character in the output.

**Comment by navyxliu** [comment]
Thanks Tobias!
I ran tier1 test and it looks good. Let me verify it using submit repo before I integrate it.

**Comment by navyxliu** [comment]
pass all tests: https://github.com/navyxliu/jdk/actions/runs/283309901
/integrate

**Pull request closed without merging**
