### PR TITLE
8237842: Separate definitions for default cache line and padding sizes

### PR DESCRIPTION
**Pull request by shipilev**
[JDK-8321137](https://bugs.openjdk.org/browse/JDK-8321137) needs a clean separation between cache line sizes and padding sizes. At least on x86, there is a wrinkle with "assuming" the cache line size is 128 bytes to cater for prefetchers. Cleanly separating cache line size and padding size resolves this. I rewrote uses of `DEFAULT_CACHE_LINE_SIZE` in padding contexts to new macro.

The goal for this patch is to avoid actual values changes as much as possible. One of the changes come from cleaning up some of the old cases in x86 definition, thus simplifying the definition. I think the LP64 split is still useful there.

Additional testing:
 - [x] Large build matrix of server/zero builds
 - [x] Linux AArch64 server fastdebug, `tier{1,2}`
 - [x] Linux x86_64 server fastdebug, `tier{1,2}`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8237842](https://bugs.openjdk.org/browse/JDK-8237842): Separate definitions for default cache line and padding sizes (**Enhancement** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [0e8929a5](https://git.openjdk.org/jdk/pull/16973/files/0e8929a5906480b572b630a3f136aa8366417979)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [0e8929a5](https://git.openjdk.org/jdk/pull/16973/files/0e8929a5906480b572b630a3f136aa8366417979)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [0e8929a5](https://git.openjdk.org/jdk/pull/16973/files/0e8929a5906480b572b630a3f136aa8366417979)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [0e8929a5](https://git.openjdk.org/jdk/pull/16973/files/0e8929a5906480b572b630a3f136aa8366417979)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16973/head:pull/16973` \
`$ git checkout pull/16973`

Update a local copy of the PR: \
`$ git checkout pull/16973` \
`$ git pull https://git.openjdk.org/jdk.git pull/16973/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16973`

View PR using the GUI difftool: \
`$ git pr show -t 16973`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16973.diff">https://git.openjdk.org/jdk/pull/16973.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16973#issuecomment-1840844760)

### CODE REVIEW

**Comment by stefank** [comment]
The *2 has been a contentious point for a long time. This is what I think happened:

In 'JDK-8049737: Contended Locking reorder and cache line bucket'

DEFAULT_CACHE_LINE was increased from 64 to 128. This was done for the ObjectMonitors, but it had an effect on other data structures in other parts of the JVM (Esp. in the GC). There were performance measurements done to try to see if the 64 to 128 change made any difference, but AFAIK, no performance difference could be seen, but the *2 change was left in place anyways.

And then 'JDK-8235931: add OM_CACHE_LINE_SIZE and use smaller size on SPARCv9 and X64' came along and changed the ObjectMonitor code to use its own define without the *2 but leaving the DEFAULT_CACHE_LINE_SIZE and padding code to still use *2!

We have asked Intel if really should be padding with two cache lines as we say here:
```
// Hardware prefetchers on current implementations may pull 2 cache lines
// on access, therefore we pessimistically assume twice the cache line size
// for padding.
#define DEFAULT_PADDING_SIZE (DEFAULT_CACHE_LINE_SIZE*2)
```

and their answer was that their hardware stopped doing that over 10 years ago (this question was asked a few years ago).

For ZGC we tried to poke at his a bit but gave up and added our own:
```
const size_t ZPlatformCacheLineSize    = 64;
```

So, with all that said. Do we really need to keep this *2 in the x64 code?

**Comment by stefank** [comment]
Sure. It think it is a good patch. However, given that you added this commment:
```
// Hardware prefetchers on current implementations may pull 2 cache lines
// on access, therefore we pessimistically assume twice the cache line size
// for padding.
```
Do you have anything that backs up the claim that this is the case for "current implementations"? Maybe @sviswa7 can help answering if this is still the case for Intel hardware?

**Comment by shipilev** [comment]
> Sure. It think it is a good patch. However, given that you added this commment:
> 
> ```
> // Hardware prefetchers on current implementations may pull 2 cache lines
> // on access, therefore we pessimistically assume twice the cache line size
> // for padding.
> ```
> 
> Do you have anything that backs up the claim that this is the case for "current implementations"? 

I was merely trying to explain why `*2` is even there. The common explanation is referring to a "common wisdom" about adjacent cache line prefetchers. Granted, that might have been true only in last few decades, and it might not hold true anymore. I can change "current" to "some" or "some old" if you think that is more neutral.

Again, I don't think this PR should be discussing `*2` thing. It should be a separate deep dive and clear few-liner change later. It would probably also affect the default for `ContendedPaddingWidth`, which we also need to tie into `DEFAULT_PADDING_SIZE` once this lands. We should not be doing it here, though, because it would have footprint implications on platforms with large cache lines, like S390X.

**Comment by stefank** [comment]
> > Sure. It think it is a good patch. However, given that you added this commment:
> > ```
> > // Hardware prefetchers on current implementations may pull 2 cache lines
> > // on access, therefore we pessimistically assume twice the cache line size
> > // for padding.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have anything that backs up the claim that this is the case for "current implementations"?
> 
> I was merely trying to explain why `*2` is even there. The common explanation is referring to a "common wisdom" about adjacent cache line prefetchers. Granted, that might have been true only a decade ago, and it might not hold true anymore. I can change "current" to "some" or "some old" if you think that is more neutral.
> 
> Again, I don't think this PR should be discussing `*2` thing. It should be a separate deep dive and clear few-liner change later. That reminds me we would probably change the default for `ContendedPaddingWidth`, probably by tying it to `DEFAULT_PADDING_SIZE` once this lands. We should not be doing it here, though, because it would have footprint implications on platforms with large cache lines, like S390X.

Well I bring this up because you are adding a comment that further sediments the understanding of the need to use *2. As I said I think the patch looks good and I'm just taking the opportunity to talk about this not that someone is yet again juggling around this *2 value. Changing to "some" is probably a good idea.

**Review by stefank — APPROVED** [review]

**Comment by shipilev** [comment]
> Well I bring this up because you are adding a comment that further sediments the understanding of the need to use *2. As I said I think the patch looks good and I'm just taking the opportunity to talk about this now that someone is yet again juggling around this *2 value. Changing to "some" is probably a good idea.

Yes, true. I rewrote the comment to hopefully much weaker wording that now implies we are not actually that sure `*2` adjustment is needed.

**Review by stefank — APPROVED** [review]

**Comment by shipilev** [comment]
> My few cents about `x2` ;^) Looking on [JDK-8049737](https://bugs.openjdk.org/browse/JDK-8049737) changes and it is used to make sure that padding is greater then cache line. 

Yes, I think the intent was the same: cater for weird prefetcher interactions.

> In `padded.hpp` we have several macros `DEFINE_PAD_MINUS_SIZE` and `PADDED_END_SIZE` which calculate offset as (default_padding - size) .

Sure, I think this PR covers these paths too, or am I missing something there?

**Comment by vnkozlov** [comment]
Orignal changes also use double size for SPARCv9.

**Comment by shipilev** [comment]
> If intention of original changes (add padding) was to avoid false sharing why we do it only for x64? From [JDK-8049737](https://bugs.openjdk.org/browse/JDK-8049737):

I don't understand the question. We add padding for all architectures to avoid false sharing. Avoiding false sharing _nominally_ requires padding by cache line size. That is why the default for `DEFAULT_PADDING_SIZE` is `DEFAULT_CACHE_SIZE`. x86 has (had?) a peculiarity with adjacent cache line hardware prefetchers that did require padding for *twice* the cache size to avoid false sharing in those unusual circumstances.

**Comment by shipilev** [comment]
I submitted the RFE for lifting the `*2` padding for x86_64 here:
https://bugs.openjdk.org/browse/JDK-8321481

**Comment by sviswa7** [comment]
> Sure. It think it is a good patch. However, given that you added this commment:
> 
> ```
> // Hardware prefetchers on current implementations may pull 2 cache lines
> // on access, therefore we pessimistically assume twice the cache line size
> // for padding.
> ```
> 
> Do you have anything that backs up the claim that this is the case for "current implementations"? Maybe @sviswa7 can help answering if this is still the case for Intel hardware?

From my understanding:
Padding to 64 byte is needed to avoid cache line false sharing.
Padding to 256 byte is recommended for heavily accessed contended data to avoid false sharing induced by prefetchers.
Padding to 128 byte may be sufficient for general contended data.

**Comment by stefank** [comment]
> > Sure. It think it is a good patch. However, given that you added this commment:
> > ```
> > // Hardware prefetchers on current implementations may pull 2 cache lines
> > // on access, therefore we pessimistically assume twice the cache line size
> > // for padding.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have anything that backs up the claim that this is the case for "current implementations"? Maybe @sviswa7 can help answering if this is still the case for Intel hardware?
> 
> From my understanding: Padding to 64 byte is needed to avoid cache line false sharing. Padding to 256 byte is recommended for heavily accessed contended data to avoid false sharing induced by prefetchers. Padding to 128 byte may be sufficient for general contended data.

Thanks, Sandhya.

I think I found the statement that I was remembering:
https://mail.openjdk.org/pipermail/zgc-dev/2018-March/000184.html

>FWIW, adjacent cache line prefetching is usually enabled for clients (desktops, laptops) and disabled for servers.  It has been this way for a long time.  For servers, the bandwidth penalty of adjacent cache line prefetching was likely the determining factor in this difference.

**Comment by shipilev** [comment]
Folks, I submitted https://bugs.openjdk.org/browse/JDK-8321481 yesterday to figure out the padding situation on x86_64. Please migrate your comments about `*2` there, so they are not lost. I transplanted some of the comments from this PR there.

Let's not allow to scope creep here. This PR is very specifically for splitting the definitions _without_ the actual value changes, and it allows to clearly set the padding size if we decide it should not really match the cache line size.

**Review by vnkozlov — APPROVED** [review]
Agree.

**Review by tstuefe — APPROVED** [review]
I need this too.

Lets ship this.

**Review by tschatzl — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
> @dcubed-ojdk, as author of [JDK-8049737](https://bugs.openjdk.org/browse/JDK-8049737) changes, do you remember why we use double cacheline for padding?

Sorry, I've been pretty much off the air w.r.t e-mail due to problems with my MBP13.

We used double cache line size way back then because some hardware fetched two cache
lines worth. I believe that was true of some Intel versions and SPARCV9. I got the two cache
line worth request from Dave Dice.

Way back in the time frame of JDK-8049737 I wrote some micro benchmarks that we tested
with no padding, with one cache line worth of padding and two cache lines worth of padding
and we saw performance improvements on linux-x64, solaris-sparc64, solaris-x64 and I think
smaller improvements on windows-x64. We tried to convert my microbenchmarks into JMHs
without success.

**Comment by shipilev** [comment]
I had to resolve some merge conflicts in `g1ConcurrentMark.hpp` due to recent changes. I am planning to integrate this after GHA turn back green.

**Pull request closed without merging**
