### PR TITLE
8259928: compiler/jvmci tests fail with -Xint

### PR DESCRIPTION
**Pull request by shipilev**
I was getting Zero VM close to run tier1, and before that I wanted to see that tier{1,2} pass with -Xint. Some test are failing due to timeouts, but compiler/jvmci tests cannot run with -Xint at all. (Zero avoids this by not having VM feature flags "jvmci").

If you run the VM with `-Xint` and JVMCI, this would happen:

```
$ build/linux-x86_64-server-fastdebug/images/jdk/bin/java -Xint -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI
OpenJDK 64-Bit Server VM warning: JVMCI Compiler disabled due to -Xint.
```

Additional testing:
 - [x] `compiler/jvmci` with `TEST_VM_OPTS=-Xint` (now disabled)
 - [x] `compiler/jvmci` with default options (still run and pass)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259928](https://bugs.openjdk.java.net/browse/JDK-8259928): compiler/jvmci tests fail with -Xint

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2132/head:pull/2132`
`$ git checkout pull/2132`

### CODE REVIEW

**Comment by vnkozlov** [comment]
I would like to hear @iignatev opinion on this. `vm.aot` and `vm.jvmci` are checks for presence of JVMCI and AOT in JDK build. And you added VM flag check.
In general I am fine with it because it avoids updating a lot of tests.

**Comment by iignatev** [comment]
I highly doubt we need to update tests within `hotspot/compiler` directory to ignore obviously incompatible configuration, `-Xint`. they are compiler tests by definitions and having all of them saying `@requires  vm.compMode != "Xint"` (or its equivalent) would be, to say the least, strange.

as of the change, Vladimir is right, `vm.aot` and `vm.jvmci` properties represent build compatibility, and one can still enable jvmci with `-Xint` (granted it won't be used, but that's beyond the point here) hence it shouldn't depend on `Xint`. alternative if we change hotspot to disable jvmci flags when one specifies `Xint` or reports them as conflicted, then your changes would be fine. as wrt AOT, I actually see inability to use AOT together w/ -Xint as a product bug.

**Comment by shipilev** [comment]
> alternative if we change hotspot to disable jvmci flags when one specifies `Xint` or reports them as conflicted, then your changes would be fine. 

If you run `compiler/jvmci` or `compiler/aot` tests with `-Xint`, then VM would already say:

```
$ CONF=linux-x86_64-server-fastdebug make images run-test TEST=compiler/aot TEST_VM_OPTS=-Xint
...
OpenJDK 64-Bit Server VM warning: JVMCI Compiler disabled due to -Xint.
Exception in thread "main" java.lang.Error: The EnableJVMCI VM option must be true (i.e., -XX:+EnableJVMCI) to use JVMCI
	at jdk.internal.vm.ci/jdk.vm.ci.services.Services.checkJVMCIEnabled(Services.java:83)
	at jdk.internal.vm.ci/jdk.vm.ci.services.Services.getSavedProperties(Services.java:91)
	at jdk.internal.vm.ci/jdk.vm.ci.services.Services.getSavedProperty(Services.java:123)
	at jdk.internal.vm.ci/jdk.vm.ci.common.InitTimer.isEnabled(InitTimer.java:76)
	at jdk.internal.vm.ci/jdk.vm.ci.common.InitTimer.timer(InitTimer.java:63)
	at jdk.internal.vm.compiler@17-internal/org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.parseOptions(HotSpotGraalOptionValues.java:102)
	at jdk.internal.vm.compiler@17-internal/org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.initializeOptions(HotSpotGraalOptionValues.java:156)
	at jdk.internal.vm.compiler@17-internal/org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.defaultOptions(HotSpotGraalOptionValues.java:84)
	at jdk.aot@17-internal/jdk.tools.jaotc.Main.run(Main.java:173)
	at jdk.aot@17-internal/jdk.tools.jaotc.Main.run(Main.java:136)
	at jdk.aot@17-internal/jdk.tools.jaotc.Main.main(Main.java:92)
```

It seems to me that using AOT implies using JVMCI?

**Comment by iignatev** [comment]
oh, I see what happened: when I checked if you can enable jvmci w/ `-Xint`, I looked at `UseJVMCICompiler`, which you can enable by some reason, but `EnableJVMCI` will be set to false when you use `-Xint`, so I agree that `vm.jvmci` should check for `-Xint` flag. it might make sense to change this behavior and set all jvmci flags to false whenever `Xint` is used.

for `vm.aot`, I still think it's a product bug if one can't run `jaotc` w/ `Xint`. @vnkozlov, what do you think?
on top of that, I also think that we have a test bug, as options like `Xint` should not be passed to `jaotc` in the majority of aot tests. I'll take closer look at them later today.

Cheers,
-- Igor

**Comment by vnkozlov** [comment]
> oh, I see what happened: when I checked if you can enable jvmci w/ `-Xint`, I looked at `UseJVMCICompiler`, which you can enable by some reason, but `EnableJVMCI` will be set to false when you use `-Xint`, so I agree that `vm.jvmci` should check for `-Xint` flag. it might make sense to change this behavior and set all jvmci flags to false whenever `Xint` is used.
> 
> for `vm.aot`, I still think it's a product bug if one can't run `jaotc` w/ `Xint`. @vnkozlov, what do you think?
> on top of that, I also think that we have a test bug, as options like `Xint` should not be passed to `jaotc` in the majority of aot tests. I'll take closer look at them later today.
> 
> Cheers,
> -- Igor

JAOTC tool requires JVMCI because it use it with Graal. JAOTC launcher explicitly  enable JVMCI. We may need to add `-Xmixed` there:

https://github.com/openjdk/jdk/blob/master/make/modules/jdk.aot/Launcher.gmk#L33

But most AOT tests use AOT compiler wrapper which sets `-Xmixed` (to avoid running with `-Xcomp`):

https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/compiler/aot/AotCompiler.java#L120

So I am not sure why -Xint overwrite -Xmixed in AOT tests in your example. I used jtreg to run AOT test and it passed:
```
$ jtreg -testjdk:/scratch/jdk15u/build/fastdebug/images/jdk/ -va -javaoptions:'-server -Xint' compiler/aot/DeoptimizationTest.java
...
Command line: [/scratch/jdk15u/build/fastdebug/images/jdk/bin/jaotc -J-server -J-Xint -J-XX:-UseCompressedOops -J-classpath -J/scratch/jdk15u/open/test/hotspot/jtreg/JTwork/classes/compiler/aot/DeoptimizationTest.d:/scratch/jdk15u/open/test/hotspot/jtreg/JTwork/classes/test/lib:/scratch/jdk15u/open/test/hotspot/jtreg/JTwork/classes/testlibrary:/scratch/jdk15u/open/test/hotspot/jtreg/JTwork/classes:/scratch/jdk15u/open/test/hotspot/jtreg/compiler/aot --compile-with-assertions --info --output libDeoptimizationTest.so --compile-commands methodsList.txt --class-name compiler.aot.DeoptimizationTest -J-ea -J-esa -J-Xmixed]
```

I can't test with JDK 16 and latest because AOT is not included anymore.

There is issue with using AOTed libraries in other AOT tests which does not have `-Xmixed` in `@run` command when `-Xint` passed because `-XX:+UseAOT` is switched off in such case.

**Comment by vnkozlov** [comment]
I suggest to fix only `vm.jvmci` since AOT is not part of JDK any more.

**Comment by shipilev** [comment]
Okay, I reduced this PR to only handle `vm.jvmci`.

Also submitted https://bugs.openjdk.java.net/browse/JDK-8260224 -- and assigned it to @iignatev.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by iignatev — APPROVED** [review]

**Pull request closed without merging**
