### PR TITLE
8339587: runtime/reflect/ReflectOutOfMemoryError.java fails with "bootstrap method initialization exception"

### PR DESCRIPTION
**Pull request by dholmes-ora**
Please review this simple test fix. The test provokes OOME but it was sometimes getting encountered in a context that led to a secondary exception - like the "bootstrap method initialization exception". The fix is to check the chain of exceptions to see if OOME was the cause.

Testing:
 - test itself 5x on each platform
 - manual testing with use of ParallelGC and disabling compressed oops as per the bug report.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339587](https://bugs.openjdk.org/browse/JDK-8339587): runtime/reflect/ReflectOutOfMemoryError.java fails with "bootstrap method initialization exception" (**Bug** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20881/head:pull/20881` \
`$ git checkout pull/20881`

Update a local copy of the PR: \
`$ git checkout pull/20881` \
`$ git pull https://git.openjdk.org/jdk.git pull/20881/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20881`

View PR using the GUI difftool: \
`$ git pr show -t 20881`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20881.diff">https://git.openjdk.org/jdk/pull/20881.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20881#issuecomment-2333207161)

### CODE REVIEW

**Review by lmesnik — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]
Please update copyrights.

**Comment by dholmes-ora** [comment]
Thanks for the review @lmesnik ! Copyright updated.

**Review by calvinccheung — APPROVED** [review]
Looks good.

**Review by lmesnik — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the review @calvinccheung !

/integrate

**Pull request closed without merging**
