### PR TITLE
8261300: jpackage: rewrite while(0)/while(false) to proper blocks

### PR DESCRIPTION
**Pull request by shipilev**
After JDK-8254702, SonarCloud instance complains about blocks like these: "Change this loop body so that it can be executed more than once."

```
    int initJvmlLauncherData(JvmlLauncherData* ptr) const {
        // Store path to JLI library just behind JvmlLauncherData header.
        char* curPtr = reinterpret_cast<char*>(ptr + 1);
        do {
            const size_t count = sizeof(char)
                    * (jliLibPath.size() + 1 /* trailing zero */);
            if (ptr) {
                std::memcpy(curPtr, jliLibPath.c_str(), count);
                ptr->jliLibPath = curPtr;
            }
            curPtr += count;
        } while (false); // <---- here
```

There is no sense in having `while(false)` here, where the syntactic `{}` block would do. There are also other uses in the jpackage code that employ `while(0)` for this, and then they also trigger the inspection about the implicit conversion of zero int to boolean.

Additional testing:
 - [x] Linux x86_64 (Ubuntu) tools/jpackage

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261300](https://bugs.openjdk.java.net/browse/JDK-8261300): jpackage: rewrite while(0)/while(false) to proper blocks

### Reviewers
 * [Andy Herrick](https://openjdk.java.net/census#herrick) (@andyherrick - **Reviewer**) ⚠️ Review applies to d895c44a76fdbbee921c3d16fa67873d929dc737
 * [Alexey Semenyuk](https://openjdk.java.net/census#asemenyuk) (@alexeysemenyukoracle - Committer)
 * [Alexander Matveev](https://openjdk.java.net/census#almatvee) (@sashamatveev - Committer) ⚠️ Review applies to d895c44a76fdbbee921c3d16fa67873d929dc737

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2454/head:pull/2454`
`$ git checkout pull/2454`

### CODE REVIEW

**Comment by andyherrick** [comment]
There are also instances of "while(0)" (without space) in app.cpp tstrings.cpp. abd in ErrorHandling.h

**Comment by shipilev** [comment]
> There are also instances of "while(0)" (without space) in app.cpp, tstrings.cpp. and ErrorHandling.h

Right. I removed more things in `tstrings.cpp`, but in other places, `while(0)` are in `#define`-s, and that is one place where those make sense: they guard from syntax/semantic errors during macro expansion.

**Review by andyherrick — APPROVED** [review]
OK - looks good to me.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Review by sashamatveev — APPROVED** [review]

**Comment by shipilev** [comment]
I had to redo `tstrings.cpp` to fix Windows failure. Turns out there was a `break` that exited the fake loop. I streamlined that code.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Pull request closed without merging**
