### PR TITLE
8299419: Thread.sleep(millis) may throw OOME

### PR DESCRIPTION
**Pull request by viktorklang-ora**
This PR applies @AlanBateman's patch from the JBS issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299419](https://bugs.openjdk.org/browse/JDK-8299419): Thread.sleep(millis) may throw OOME (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20923/head:pull/20923` \
`$ git checkout pull/20923`

Update a local copy of the PR: \
`$ git checkout pull/20923` \
`$ git pull https://git.openjdk.org/jdk.git pull/20923/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20923`

View PR using the GUI difftool: \
`$ git pr show -t 20923`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20923.diff">https://git.openjdk.org/jdk/pull/20923.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20923#issuecomment-2340021464)

### CODE REVIEW

**Comment by viktorklang-ora** [comment]
@DougLea @AlanBateman This patch seems to side-step the issues we saw with OOME-on-sleep. Which coincidentally should also harden TestDisposerRace.java so if we get this patch merged we should be able to close that one as a duplicate.

**Comment by AlanBateman** [comment]
I hope that someone will take pity on the following tests, sadly they need to be updated as they depend methods observed in the call stack.

test/hotspot/jtreg//vmTestbase/nsk/monitoring/stress/thread/strace001.java
test/hotspot/jtreg//vmTestbase/nsk/monitoring/share/ThreadController.java
test/hotspot/jtreg//vmTestbase/nsk/monitoring/share/thread/SleepingThread.java

**Review by dholmes-ora — COMMENTED** [review]
With regards to the nsk tests, are `beforeSleep` and `afterSleep` still potential candidates now that it is impossible for them to throw OOME?

**Comment by AlanBateman** [comment]
> With regards to the nsk tests, are `beforeSleep` and `afterSleep` still potential candidates now that it is impossible for them to throw OOME?

These tests are sampling and checking for specific methods and call stacks, I don't think they are provoke OOME. So the changes just are cleanup as these it won't sample frames with these methods with the code change. I don't think ThreadSleepEvent.<clinit> will be sampled now but maybe ThreadSleepEvent.<init> will.

These tests are crying out to be replaced as they make too hard to do changes in this area.

**Comment by dholmes-ora** [comment]
If these are just methods that might be seen in a stackdump then we still need `ThreadSleepEvent.isEnabled` and `ThreadSleepEvent.<init>`.

**Comment by AlanBateman** [comment]
> If these are just methods that might be seen in a stackdump then we still need `ThreadSleepEvent.isEnabled` and `ThreadSleepEvent.<init>`.

I think minimal here is to just drop isTurnedOn from lists in these tests. From what I can tell, the tests are sampling in a loop and can tolerate up to a limit. Hopefully someone will step up some day and replace them.

**Comment by dholmes-ora** [comment]
This change exposed an existing bug in the strace tests with a missing constructor - [JDK-8340072](https://bugs.openjdk.org/browse/JDK-8340072)

**Pull request closed without merging**
