### PR TITLE
8256146: Cleanup test/jdk/java/nio/channels/DatagramChannel/Connect.java

### PR DESCRIPTION
**Pull request by dfuch**
Hi,

Please find here a trivial cleanup change for  test/jdk/java/nio/channels/DatagramChannel/Connect.java
The change caters for possible evolution of the test - if we ever decided to bind the Reactor to the wildcard address;
(the reactor is currently bound to the loopback).

I would usually not bother but I had this experiment in my local workspace: it could as well be pushed as it cleans up the Actor logic which no longer has to depend on the fact that the Reactor is not bound to the wildcard.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8256146](https://bugs.openjdk.java.net/browse/JDK-8256146):  Cleanup test/jdk/java/nio/channels/DatagramChannel/Connect.java

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to c884adb03e2e8f7ee0f1f97fb216f5cd92de2adc

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1144/head:pull/1144`
`$ git checkout pull/1144`

### CODE REVIEW

**Comment by msheppar** [comment]
Looks like a reasonable future proofing change :-)

Couple of minor observations and comments:

Actor constructor parameter name change: from socketAddress to either peerSocketAddress or connectSocketAddress or reactorSocketAddress to convey some semantics of its purpose.

Change of Actor member variable name from socketAddress to connectSocketAddress - again more explicit semantic description

When I saw the previous changes for this test  and saw Reactor, the immediate thought was of
Reactor pattern, but it is not. Names are somewhat 
idiosyncratic but Actor/Reactor don’t convey immediate semantics of the test.
The more conventional Sender/Receiver, or if one seeks a bit of OSI nostalgia
and more abstract terminology Initiator/Responder would convey clearer semantics of sending and receiving!

**Review by AlanBateman — APPROVED** [review]
Looks okay.

**Comment by dfuch** [comment]
@msheppar Good suggestions! I have updated the PR.

**Comment by AlanBateman** [comment]
The previous iteration was a cleaner but okay.

**Pull request closed without merging**
