### PR TITLE
8213531: Test javax/swing/border/TestTitledBorderLeak.java fails

### PR DESCRIPTION
**Pull request by prsadhuk**
Test was failing in linux citing `java.lang.RuntimeException: Expected Total TitledBorder to be freed : 10 Freed 9 `
As per the fix done in JDK-8204963 http://hg.openjdk.java.net/jdk/jdk/rev/cd7d2f9154fd
there was no platform specific code done for the fix and logs in `TitledBorder.installPropertyChangeListeners` shows it was called 10 times for the test but `CleanerFactory.cleaner().register` action was only called 9 times in linux causing it to fail.

Modified the test to not show the frame which cause the problem to go away and also it can still be used as 8204963 regression test as it still fails without the fix and pass with it. Modified test has passed in all platforms for several iterations.

Also removed the deprecated `System.runFinalization`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8213531](https://bugs.openjdk.java.net/browse/JDK-8213531): Test javax/swing/border/TestTitledBorderLeak.java fails

### Reviewers
 * @kristylee88 (no known github.com user name / role)
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8450/head:pull/8450` \
`$ git checkout pull/8450`

Update a local copy of the PR: \
`$ git checkout pull/8450` \
`$ git pull https://git.openjdk.java.net/jdk pull/8450/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8450`

View PR using the GUI difftool: \
`$ git pr show -t 8450`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8450.diff">https://git.openjdk.java.net/jdk/pull/8450.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
> Modified the test to not show the frame which cause the problem to go away

Does it mean that setVisible(true) cause some memory leak since it prevents the window to be disposed?

**Comment by prrace** [comment]
> > Modified the test to not show the frame which cause the problem to go away
> 
> Does it mean that setVisible(true) cause some memory leak since it prevents the window to be disposed?

Since 9 windows are freed .. I doubt it .. but what's the hold up with #10 ?
I wonder if you need an extra System.gc() cycle ?

**Comment by mrserb** [comment]
> > Does it mean that setVisible(true) cause some memory leak since it prevents the window to be disposed?
> 
> Since 9 windows are freed .. I doubt it .. but what's the hold up with #10 ? I wonder if you need an extra System.gc() cycle 

Then why we delete the "setVisible(true)"?  probably we leak the latest visible window?

**Comment by prrace** [comment]
Can you confirm we still need the Frame ? I mean when does the used-to-be-leaky listener get installed ?
If it is sufficient to add it to the panel and the panel doesn't need to be added to the frame then the test can be headless.
But we need to be sure that doesn't skip what we want to test.

**Comment by prsadhuk** [comment]
> Can you confirm we still need the Frame ? I mean when does the used-to-be-leaky listener get installed ? If it is sufficient to add it to the panel and the panel doesn't need to be added to the frame then the test can be headless. But we need to be sure that doesn't skip what we want to test.

No, we dont need the frame. The leaky listener gets installed when we call `new TitledBorder()`

I have made the test headless which still fails without the fix and passes with TitledBorder fix and also pass in all CI headless platforms

**Review by kristylee88 — APPROVED** [review]

**Review by prrace — APPROVED** [review]

**Comment by mrserb** [comment]
> Even if we remove TitledBorder code from the test and only keep JFrame, then also I see

So it means that the last visible but already disposed frame is sitting in the memory/leaked and this test catch that, isn't it?

**Comment by prsadhuk** [comment]
Have added JDK-8287707 for JFrame leak but it is seem playing around with Thread.sleep, the freed count varies from 7-9 so it can be a test issue too.

**Pull request closed without merging**
