### PR TITLE
8296548: Improve MD5 intrinsic for x86_64

### PR DESCRIPTION
**Pull request by yftsai**
The LEA instruction loads the effective address, but MD5 intrinsic uses it for computing values than addresses. This usage potentially uses more cycles than ADDs and reduces the throughput.

This change replaces
    LEA:  r1 = r1 + rsi * 1 + t
with
    ADDs: r1 += t; r1 += rsi.

Microbenchmark evaluation shows ~40% performance improvement on Haswell, Broadwell, Skylake, and Cascade Lake. There is ~20% improvement on 2nd gen Epyc.

No performance change for the same microbenchmark on Ice Lake and 3rd gen Epyc.

Similar results can be observed with TestMD5Intrinsics and TestMD5MultiBlockIntrinsics. There is ~15% improvement in throughput on Haswell, Broadwell, Skylake, and Cascade Lake.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296548](https://bugs.openjdk.org/browse/JDK-8296548): Improve MD5 intrinsic for x86_64

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [6ed4348c](https://git.openjdk.org/jdk/pull/11054/files/6ed4348c5abe093318e35a0e50e4205f082dc179)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to [6ed4348c](https://git.openjdk.org/jdk/pull/11054/files/6ed4348c5abe093318e35a0e50e4205f082dc179)
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Author) ⚠️ Review applies to [6ed4348c](https://git.openjdk.org/jdk/pull/11054/files/6ed4348c5abe093318e35a0e50e4205f082dc179)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11054/head:pull/11054` \
`$ git checkout pull/11054`

Update a local copy of the PR: \
`$ git checkout pull/11054` \
`$ git pull https://git.openjdk.org/jdk pull/11054/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11054`

View PR using the GUI difftool: \
`$ git pr show -t 11054`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11054.diff">https://git.openjdk.org/jdk/pull/11054.diff</a>

</details>

### CODE REVIEW

**Comment by luhenry** [comment]
Could you please post JMH microbenchmarks with and without this change? You can run them with `org.openjdk.bench.java.security.MessageDigests` [1]

[1] https://github.com/openjdk/jdk/blob/master/test/micro/org/openjdk/bench/java/security/MessageDigests.java

**Comment by vnkozlov** [comment]
Yes, please, post performance data.
Note, TestMD5Intrinsics and TestMD5MultiBlockIntrinsics are regression/correctness tests.
Would be nice to have proper JMH benchmarks to show improvement.

**Comment by vnkozlov** [comment]
@sviswa7 or @jatin-bhateja do you agree with these changes?

**Comment by jnimeh** [comment]
There appears to be a microbenchmark that covers MD5 (among others) in `test/micro/org/openjdk/bench/javax/crypto/full/MessageDigestBench.java`.  It looks like it only does single-part 1MB jobs, but that might be good enough to see the impact of these changes.  Or the size range can be expanded to cover other sizes, though the getInstance and other calls will take an increasingly large portion of the measurement.  It should still show a speed difference between old and new intrinsics.

**Comment by jatin-bhateja** [comment]
> @sviswa7 or @jatin-bhateja do you agree with these changes?

```
Patch shows significant improvement and better port utilization with 3+ micro ops on CLX.

JDK-With-opt:
Benchmark              (digesterName)  (length)  (provider)   Mode  Cnt     Score   Error   Units
MessageDigests.digest             md5        64     DEFAULT  thrpt    2  5613.517          ops/ms
MessageDigests.digest             md5     16384     DEFAULT  thrpt    2    50.026          ops/ms

   43,24,11,23,563      exe_activity.1_ports_util                                     (79.97%)
   54,01,28,04,330      exe_activity.2_ports_util                                     (80.22%)
   25,20,63,64,512      exe_activity.3_ports_util                                     (80.00%)
    6,42,47,64,948      exe_activity.4_ports_util                                     (79.83%)

JDK-baseline:
Benchmark              (digesterName)  (length)  (provider)   Mode  Cnt     Score   Error   Units
MessageDigests.digest             md5        64     DEFAULT  thrpt    2  4087.112          ops/ms
MessageDigests.digest             md5     16384     DEFAULT  thrpt    2    35.291          ops/ms

   50,76,35,89,853      exe_activity.1_ports_util                                     (80.09%)
   36,59,68,98,931      exe_activity.2_ports_util                                     (79.89%)
    9,61,69,23,581      exe_activity.3_ports_util                                     (80.02%)
    1,88,94,94,202      exe_activity.4_ports_util                                     (79.98%)

```

**Comment by yftsai** [comment]
Performance without the optimization on Cascade Lake:
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt     Score     Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   15  3315.328 ±  65.799  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   15    27.482 ±   0.006  ops/ms
MessageDigests.getAndDigest             md5        64     DEFAULT  thrpt   15  2916.207 ± 127.293  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   15    27.381 ±   0.003  ops/ms
```

Performance with optimization on Cascade Lake:
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt     Score     Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   15  4474.780 ±  17.583  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   15    38.926 ±   0.005  ops/ms
MessageDigests.getAndDigest             md5        64     DEFAULT  thrpt   15  3796.684 ± 153.887  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   15    38.724 ±   0.005  ops/ms
```

**Comment by yftsai** [comment]
Performance without the optimization on Ice Lake:
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt     Score    Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   15  5402.018 ± 17.033  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   15    43.722 ±  0.003  ops/ms
MessageDigests.getAndDigest             md5        64     DEFAULT  thrpt   15  4652.620 ± 35.432  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   15    43.573 ±  0.016  ops/ms
```

Performance with optimization on Ice Lake:
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt     Score    Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   15  5348.594 ± 14.303  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   15    43.671 ±  0.008  ops/ms
MessageDigests.getAndDigest             md5        64     DEFAULT  thrpt   15  4583.530 ± 12.752  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   15    43.545 ±  0.006  ops/ms
```

**Review by vnkozlov — APPROVED** [review]
Thank you all for providing performance data. Looks good. I will run testing.

**Comment by vnkozlov** [comment]
Do we have other intrinsics which use LEA (not for this fix)?

**Comment by vnkozlov** [comment]
@yftsai can you merge latest JDK sources? Some of GHA testing failures should be fixed.

**Comment by eastig** [comment]
> Do we have other intrinsics which use LEA (not for this fix)?

I have plans to look at other uses of LEA in Hotspot. I have not started yet due to other urgent work.

**Comment by eastig** [comment]
> > Do we have other intrinsics which use LEA (not for this fix)?
> 
> My pending ChaCha20 intrinsics ( #7702 ) use LEA for getting the address of constant data to be loaded into SIMD registers. That happens before the 10-iteration loop that implements the 20 rounds (which is the critical section of the intrinsic).

From #7702, I see they are not 3 operand LEA. No need to change them.

**Comment by sviswa7** [comment]
> Do we have other intrinsics which use LEA (not for this fix)?

There is a VM_Version::supports_fast_2op_lea() and VM_Version::supports_fast_3op_lea() check available which is used to do lea optimizations.

**Comment by vnkozlov** [comment]
> > Do we have other intrinsics which use LEA (not for this fix)?
> 
> There is a VM_Version::supports_fast_2op_lea() and VM_Version::supports_fast_3op_lea() check available which is used to do lea optimizations.

Thanks you @sviswa7

For this fix, based on IceLake data provided by @yftsai, `supports_fast_3op_lea()` potential help is not enough to justify increase complexity of code. May be in other places it would be more useful but not here IMHO.

**Comment by sviswa7** [comment]
> > > Do we have other intrinsics which use LEA (not for this fix)?
> > 
> > 
> > There is a VM_Version::supports_fast_2op_lea() and VM_Version::supports_fast_3op_lea() check available which is used to do lea optimizations.
> 
> Thanks you @sviswa7
> 
> For this fix, based on IceLake data provided by @yftsai, `supports_fast_3op_lea()` potential help is not enough to justify increase complexity of code. May be in other places it would be more useful but not here IMHO.

Yes, I agree. The PR looks good to me.

**Review by sviswa7 — APPROVED** [review]

**Review by luhenry — APPROVED** [review]

**Comment by vnkozlov** [comment]
My testing passed.

**Pull request closed without merging**
