### PR TITLE
8304031: Classfile API cannot encode Primitive Class as Condy

### PR DESCRIPTION
**Pull request by liach**
Without this patch, the Classfile API tries to encode PrimitiveClassDesc as CONSTANT_Class_info and error in `toInternalName`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304031](https://bugs.openjdk.org/browse/JDK-8304031): Classfile API cannot encode Primitive Class as Condy

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**) ⚠️ Review applies to [8f4e1642](https://git.openjdk.org/jdk/pull/12996/files/8f4e1642f327b2b7794796176a0068ed196f584b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12996/head:pull/12996` \
`$ git checkout pull/12996`

Update a local copy of the PR: \
`$ git checkout pull/12996` \
`$ git pull https://git.openjdk.org/jdk.git pull/12996/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12996`

View PR using the GUI difftool: \
`$ git pr show -t 12996`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12996.diff">https://git.openjdk.org/jdk/pull/12996.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12996#issuecomment-1465697378)

### CODE REVIEW

**Comment by liach** [comment]
@asotona Would you mind review this?

**Comment by ExE-Boss** [comment]
Arguably, the `instanceof DynamicConstantDesc` check should go first, as there can be only one superclass, but multiple implemented interfaces.

**Comment by liach** [comment]
> Arguably, the `instanceof DynamicConstantDesc` check should go first, as there can be only one superclass, but multiple implemented interfaces.

I think this ordering is rather ranked by their relative frequency in bytecode. Having integer constants to undergo `instanceof DynamicConstantDesc` checks would be less efficient.

**Comment by ExE-Boss** [comment]
I meant that `instanceof DynamicConstantDesc` would go after concrete classes (`Integer`, `Long`, `Float`, `Double`, and `String`), but before the `ConstantDesc` interfaces.

**Comment by liach** [comment]
> I meant that `instanceof DynamicConstantDesc` would go after concrete classes (`Integer`, `Long`, `Float`, `Double`, and `String`), but before the `ConstantDesc` interfaces.

Still not feasible to make ReferenceClassDescImpl to go through all these previous instanceof checks.

**Comment by liach** [comment]
Seems this bug exists in `ConstantPoolBuilder::constantValueEntry` as well.

**Comment by liach** [comment]
Keep-alive.

**Pull request closed without merging**
