### PR TITLE
8314828: Mark 3 jcmd command-line options test as vm.flagless

### PR DESCRIPTION
**Pull request by lmesnik**
Mark 3 tests as flagless to don't run them if not needed. Also, small clean up.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314828](https://bugs.openjdk.org/browse/JDK-8314828): Mark 3 jcmd command-line options test as vm.flagless (**Sub-task** - P4)

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15407/head:pull/15407` \
`$ git checkout pull/15407`

Update a local copy of the PR: \
`$ git checkout pull/15407` \
`$ git pull https://git.openjdk.org/jdk.git pull/15407/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15407`

View PR using the GUI difftool: \
`$ git pr show -t 15407`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15407.diff">https://git.openjdk.org/jdk/pull/15407.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15407#issuecomment-1690755584)

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
I fixed the typo in the bug's synopsis line. You can use "/issue JDK-8314828" to fix it easily here.

**Review by dcubed-ojdk — CHANGES_REQUESTED** [review]
Would be nice to have an explanation for why "@library /vmTestbase" is no longer needed.
A comment in the PR would suffice.

**Comment by lmesnik** [comment]
> Would be nice to have an explanation for why "@library /vmTestbase" is no longer needed. A comment in the PR would suffice.

It is just not used, probably someone forgot to remove it or added by mistake.

**Comment by plummercj** [comment]
Is this proper use of `vm.flagless`? From existing uses, it seems to be actually specifying a real requirement. In other words, the test may not run properly if flags are specified. I can understand wanting to reduce test repetition in CI, but this also results in the test not being run in cases where the user decides to specify a flag, and still expects these tests to be run.

**Comment by lmesnik** [comment]
It is the original intention of vm.flagless to mark all tests that ignore VM flags. See https://bugs.openjdk.org/browse/JDK-8151707 and https://bugs.openjdk.org/browse/JDK-8246497. The idea is not only to reduce time but also to provide correct information about coverage. If the user specifies it usually expects that a test would be executed using this flag and actually testing the feature. If you feel that it makes sense to run these/or any  tests with external flags, we could update them to fork VM using tested vm options.

**Comment by plummercj** [comment]
So vm.flagless is to be used for any test that spawns a process and does not pass the vm flags on to that process? I understand the rationale, but still have my concern that these tests not running if any flags are specified. Perhaps vm.flagless could be combined with some other JTREG flag that has to be explicitly set to indicate not to run vm.flagless tests if a vm flag is set. CI could pass this flag (because it knows there is at least one test task that will run the test), but regular users of `make test` would not set the flag, allowing the vm.flagless tests to run. Maybe something like JTREG_RUN_VM_FLAGLESS. Have it default to true. Let CI set it to false. The end result of JTREG_RUN_VM_FLAGLESS=false would be to set vm.flagless true even if flags are specified.

**Comment by lmesnik** [comment]
You could use TEST_VM_FLAGLESS=false to forcibly ignore any vm.flagless and run them in testing.  Or configure behavior in VMProps file. Currently, options like 'MaxRAMPercentage' and 'CreateCoredumpOnCrash' are ignored and the list could be extended.

**Comment by plummercj** [comment]
Ok, so it sounds like you already have the needed flag in place, although I would suggest by default it be set false and require that CI set true. The goal here is not to have something unexpected for the user.

**Comment by lmesnik** [comment]
We certainly could do it.  I just don't know what would be the 'expected" behaviour here.

**Comment by plummercj** [comment]
Is there a reason we don't want to run the subprocess with the test flags?

**Comment by lmesnik** [comment]
these 3 tests  verifies command-line options only like help, version, invalid versions. I don't think they any value by runnign with different flags. But  If you think it makes sense just to start process with vm flags, I am fine to fix them.

**Comment by plummercj** [comment]
As long as we have other test coverage for passing the flags to the sub process then I think these can do without.

**Review by plummercj — APPROVED** [review]

**Pull request closed without merging**
