### PR TITLE
8342601: AArch64: Micro-optimize bit shift in copy_memory

### PR DESCRIPTION
**Pull request by chadrako**
[JDK-8342601](https://bugs.openjdk.org/browse/JDK-8342601)

Fix minor inefficiency in `copy_memory` by adding check before doing bit shift to see if we are able to do a move instruction instead. Change is low risk because of the low complexity of the change

Ran array copy and tier 1 on aarch64 machine
```
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/compiler/arraycopy          49    49     0     0   
==============================

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg:tier1                     2591  2591     0     0   
   jtreg:test/jdk:tier1                               2436  2436     0     0   
   jtreg:test/langtools:tier1                         4577  4577     0     0   
   jtreg:test/jaxp:tier1                                 0     0     0     0   
   jtreg:test/lib-test:tier1                            34    34     0     0   
==============================

```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8342601](https://bugs.openjdk.org/browse/JDK-8342601): AArch64: Micro-optimize bit shift in copy_memory (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) Review applies to [461e2a53](https://git.openjdk.org/jdk/pull/21589/files/461e2a536fbe0cb39f6535de9b9ef08b80fd7409)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21589/head:pull/21589` \
`$ git checkout pull/21589`

Update a local copy of the PR: \
`$ git checkout pull/21589` \
`$ git pull https://git.openjdk.org/jdk.git pull/21589/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21589`

View PR using the GUI difftool: \
`$ git pr show -t 21589`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21589.diff">https://git.openjdk.org/jdk/pull/21589.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21589#issuecomment-2423091020)

### CODE REVIEW

**Comment by dean-long** [comment]
Please quantify the performance improvement, if any.  I would expect this to make 0 difference, but if it does, then perhaps we should consider checking for a shift of 0 inside `lsr`?

**Comment by rose00** [comment]
A general principle for our work here:  Keep it simple.  Simplicity is maintainability.  Only make it more complex if you can demonstrate a practical win.  Otherwise, keep the hands away from the keyboard.

It probably never ever makes a difference, to replace shift-by-0 with move, likewise an add-with-0 or an xor-with-0.  On most RISC machines for the last 4 decades, mov is just a macro for such an ALU operation, and all of them take the same number of cycles and go through the same circuitry (with different mode lines enabled).

In other words, the cost model justifying this supposed improvement is probably about a half century out of date.  Maybe an expert on AARCH64 can correct me on this point?

So I'm against this change as unnecessary, unless there is a performance test that shows a significant benefit.  Changes like this only make the sources harder to read and maintain.

If we think multiple people will have an overwhelming urge to tweak the code, even after the tweak is proven unnecessary, then add a comment to future maintainers explaining why there is no need here for a tweak.  A semi-useless comment is easier to maintain than a useless if/then/else.

Dean's suggestion is somewhat reasonable, to have the assembler desugar shift-by-zero to mov.  The only effect of that would be to make the disassembly slightly easier to read, for less experienced readers of disassembly.  We did some things like that with the SPARC port, but did so under new assembler API points (what used to be called pseudo-instructions).  For example, we had a mov-or-nop instruction, which nopped itself if the source and destination of the move were the same register.  There is huge benefit to having the assembler API do exactly what it says, and not second-guess the user (swapping other instructions behind the user's back).  Using that process, you'd introduce a shift-or-mov instruction, explicitly. Which is obviously not worth it. So, again, I'd say no change is needed here, not even Dean's.

**Comment by dean-long** [comment]
> In other words, the cost model justifying this supposed improvement is probably about a half century out of date. Maybe an expert on AARCH64 can correct me on this point?

Apparently some moves are "0 latency" and skip the pipeline on some aarch64 hardware.

Yes, we usually expect Assembler APIs to do exactly what we ask, but when the API is in MacroAssembler and doesn't correspond to an actual aarch64 instruction or alias, I think we normally allow optimizations.  As LSR is an alias, I think we would expect it to generate the underlying `ubfm` encoding, so if we were going to optimize based on the shift value, we could introduce a new API with a name like shift_right().

**Comment by rose00** [comment]
Thanks Dean.  If there is a specific forwarding mechanism for some moves but not all move-like instructions, then a micro-optimization like this is worth considering.  (We'd still want evidence from perf tests.)  I think it would belong inside the macro-assembler, though, so we don't play whack-a-mole finding all the places where we could reduce a quasi-move to a real forwardable move.  Also the comments documenting this decision belong in the macro-assembler, and not just in PR conversations or comments on random use-sites of the macro-assembler.

Again, for SPARC, we made the distinction between assembler and macro-assembler.  The assembler never did anything "smart", that was left to the macro-assembler.  Occasionally the same name would mean different things at the two levels of assembler.  That may or may not be good C++ practice.

**Comment by theRealAph** [comment]
> Thanks Dean. If there is a specific forwarding mechanism for some moves but not all move-like instructions, then a micro-optimization like this is worth considering. (We'd still want evidence from perf tests.) 

Here's how it works, on recent high-end Arm and Apple silicon. Full-width mov instructions do not issue at all: instead, they are handled by the renamer at decode time. In effect they have no latency at execution time, although they do occupy slots in the decoder. Partial width (e.g. 32-bit) mov instructions do issue because they do some work: they clear the top half of the destination register, and they need an ALU to do that.

There is some theoretical advantage to turning a full-width shift of 0 into a full-width mov. For example, Apple M1 can decode 8 instructions and can execute 6 integer ops per clock. Shift instructions have a latency of one clock. But given that these CPUs have very wide issue as well as many integer ALUs, it may be impossible to gain any performance advantage in real-world code. It is possible, with a carefully-written assembly-code benchmark, to measure some performance advantage, but it is unlikely to gain much in practice.

**Review by shipilev — COMMENTED** [review]
There is `if (shift) __ lsr(...)`  above at line 1376, please fix it as `shift > 0` as well.

**Comment by shipilev** [comment]
> If there is a specific forwarding mechanism for some moves but not all move-like instructions, then a micro-optimization like this is worth considering. (We'd still want evidence from perf tests.) I think it would belong inside the macro-assembler, though, so we don't play whack-a-mole finding all the places where we could reduce a quasi-move to a real forwardable move.

If you look at linked issues JBS, you'll see that I initially did [JDK-8341893](https://bugs.openjdk.org/browse/JDK-8341893) as the fix on compressed ptr decoding path, and [JDK-8341895](https://bugs.openjdk.org/browse/JDK-8341895) as the generic fix in `MacroAssembler`. Then I realized we _only_ reach that pattern from one place in `copy_memory`, which this PR tidies up. Not going for a generic `MacroAssembler` fix is saner here, because with only a single use we do not have a good test coverage for the generic translation. "Failed to pass the cost/benefit bar" is exactly why I backed off doing [JDK-8341895](https://bugs.openjdk.org/browse/JDK-8341895), and instead assigned Chad to touch up the only place where this conversion can at all matter.

Looking at this differently: if I wrote the `copy_memory` stub from scratch today, would I do this optimization? Answering personally, I probably would. The original authors apparently did a similar `lsr` -> "nothing" conversion in one of the places already: https://github.com/openjdk/jdk/blob/aa060f22d302789c4f80dd1ebaa233a97b6b0073/src/hotspot/cpu/aarch64/stubGenerator_aarch64.cpp#L1376-L1377

Philosophically, the performance optimizations usually fall into three broad categories: "so bad they show up in common tests", "can be measured in targeted tests without trying hard", and "death by a thousand (paper) cuts, you might probably show the impact if you really, really try". Only the first two could be reasonably measured in isolation. The effort required to make a performance-test-based decision for third category usually grossly outweigh their impact. I believe it is a waste of engineering time to even try. Note it does not mean third category can be summarily ignored: adding up hundreds of paper-cut inefficiency fixes is how you get incremental performance improvements as you go. For issues like these, if you can spare a (micro-)instruction on a fairly generic path, do so and move on. I advise all of us to do exactly this.

**Comment by theRealAph** [comment]
> Looking at this differently: if I wrote the `copy_memory` stub from scratch today, would I do this optimization? Answering personally, I probably would.

I wonder if that's too low a bar for whether we should change it now, though. If we adopt "would I have done it this way, first time around?" as an appropriate threshold for a change, it gives permission for endless churn with tiny issues. Churn _in itself_ is bad.

**Comment by shipilev** [comment]
> > Looking at this differently: if I wrote the `copy_memory` stub from scratch today, would I do this optimization? Answering personally, I probably would.
> 
> I wonder if that's too low a bar for whether we should change it now, though. If we adopt "would I have done it this way, first time around?" as an appropriate threshold for a change, it gives permission for endless churn with tiny issues. 

I don't think about this in slippery slope terms. There is always a cost/benefit calculation for every change. Contributors' costs are not zero (see the testing that goes into these), which is a part of back-pressure against doing this often. Reviewers costs are not zero either, but that cost is in control of reviewers -- _that's us!_ -- themselves. In that sense, tiny patches become a problem only when we collectively spend disproportionate amount of time on them, like in this PR. I advocate for taking low-benefit patches quickly, without accidentally inflating their costs.

With regards for post-integration touchups, I think the reverse policy would be worse, if not straight-up chilling: we will have to be extra-stringent on getting every little detail absolutely, un-changeably right during every review, if the amendments would not pass the contribution bar. I don't believe this is the outcome we want either.

**Comment by theRealAph** [comment]
> I don't think about this in slippery slope terms. There is always a cost/benefit calculation for every change. Contributors' costs are not zero (see the testing that goes into these), which is a part of back-pressure against doing this often. Reviewers costs are not zero either, but that cost is in control of reviewers -- _that's us!_ -- themselves. 

> In that sense, tiny patches become a problem only when we collectively spend disproportionate amount of time on them, like in this PR.

I'm not sure about that. Even if you were to discount the cost of the PR review process entirely, there's the long-term cost of churn in the change logs, etc. We've all done archaeology, trying to figure out why and when a change was made, and every patch costs something. I certainly would much prefer to read a cleanup patch with twenty small changes in it than twenty small patches scattered in between more significant contributions.

> I advocate for taking low-benefit patches quickly, without accidentally inflating their costs.

I think that you are at one end of the range of opinions, judging by the other comments to this post. I held a workshop session about low-benefit patches at the most recent committers' workshop, and there was a good deal of opinion, with many people advocating some pushback against then.
 
> With regards for post-integration touchups, I think the reverse policy would be worse, if not straight-up chilling: we will have to be extra-stringent on getting every little detail absolutely, un-changeably right during every review, if the amendments would not pass the contribution bar. I don't believe this is the outcome we want either.

True enough, but I don't think anyone was proposing a change to the _de facto_ current policy. @dean-long and @rose00 were raising a skeptical eyebrow about this change.

**Comment by shipilev** [comment]
> I'm not sure about that. Even if you were to discount the cost of the PR review process entirely, there's the long-term cost of churn in the change logs, etc. We've all done archaeology, trying to figure out why and when a change was made, and every patch costs something. I certainly would much prefer to read a cleanup patch with twenty small changes in it than twenty small patches scattered in between more significant contributions.

Noted. Speaking of archaeology, nearly all of my archaeological digs start either with `git bisect`, or with "History for selection" for a particular hunk. In both these steps having 20 atomic commits is palpably easier to deal with than with 20 small cleanups clobbered together.

Anyway, I still believe that patch is good, that we are spending way too much time here, so I am approving and moving on. If nobody else agrees, I am OK with abandoning this patch as well.

/reviewers 2

**Review by shipilev — APPROVED** [review]

**Review by dean-long — APPROVED** [review]
If I had known about aarch64 optimizations like Neoverse 0 latency moves when I first looked at this, I would have approved it, so some code comments hinting at why we are doing this not-completely-obvious optimization would be appreciated.

**Comment by dean-long** [comment]
BTW, apparently Neoverse has 0 latency moves even for 32-bit registers, so they must do something clever with clearing the high bits.

**Review by dean-long — APPROVED** [review]

**Comment by theRealAph** [comment]
> BTW, apparently Neoverse has 0 latency moves even for 32-bit registers, so they must do something clever with clearing the high bits.

So they are. Some dark magic there. :-)

**Review by theRealAph — APPROVED** [review]
I agree, let's commit this. The advantage of Zero Latency MOVs on some implementations (e.g. Arm Neoverse V2 optimization guide, 4.12) is worth having.

**Comment by rose00** [comment]
The motivating comment helps, thanks.  The fact that ORR is special-cased (on some chip we care about) is important.  This is linked to the ARM convention that MOV is sugar for ORR (in these cases).

A couple of possible principles come to mind about this little exercise.  I will risk further PR churn here because they are fairly generally applicable.

Possible Lesson 1: Document (briefly) the motivation for a micro-optimization that is not self-evident, so future maintainers know why it is there, and conversely when it might be time to simplify or reformulate it.  Or even repeat it: There might be more places for this micro-optimization in the future, such as C2 or C1 backends, or additional assembly intrinsics.  Some comments should hint what is the comment thread, if the trick is repeated.

Possible Lesson 2: Consider factoring dependencies on special CPU knowledge (for micro-optimizations) to places where the ISA is made available (macro-assembler) instead of sprinkled where we are emitting instructions.  In an extreme case, a micro-opt which is specific to one hardware implementation can use the VM-version bits to say, "am I doing this micro-opt today"?  Clearly such a test is more closely relevant to the macro-assembler than it is to some bit-copy or oop-compress code.

> [Dean] As LSR is an alias, I think we would expect it to generate the underlying ubfm encoding, so if we were going to optimize based on the shift value, we could introduce a new API with a name like shift_right().

As an example, FWIW, back in the days when I thought about the SPARC port full time, I might have reached (in a case like this) for a helper method called `maybe_lsr` and refactored the new if/then/else here as `__ maybe_lsr(r15, count, shift);`.  For extra benefit, I might add a guard suppressing the `mov` if source and destination are identical, all because the `maybe_` is a clear enough signal that the emitted code is not 1-1 with the stated instruction.  The body of `maybe_lsr` might have discussion of move-forwarding. It might also call another local API point `maybe_mov` which has the guard.  I would have done this even if it was used only in one place, because of the possibility, as the system grew (it was early days) of having to perform the same micro-optimization more than once.

But, there are also plenty of reasons not to do it that way, and I admit that (with the warning comment added) what we have now is completely workable.

Aleksey, I looked at your proposed patch in [JDK-8341895](https://bugs.openjdk.org/browse/JDK-8341895).  If I were doing it (but I'm not) I might pick a slightly more informative name (`maybe_ubfm`, `ubfm_or_mov`, or something like that), depending on how the actual uses would read.  Also, the term `lsr` is a little higher level (more like a C op), and maybe such work with helper functions belongs at that upper level.  ARM has lots of pseudo-instructions like `lsr` (for `ubfm`) and `mov` (for `orr`), and it would seem to be lots of unused effort to make magic versions of all the lowerings.

HTH

**Comment by theRealAph** [comment]
Thought about your thoughts:

Just to be clear: `ORR` isn't special cased by the hardware, `MOV` is. The front end has logic to recognize just the bit pattern that corresponds to a register-register `MOV`.

Re Possible Lesson 1, I guess it would be sufficient to say "`// Take advantage of zero-latency MOVs if we can`".

Re Possible Lesson 2. I've been eager to push back against special-case tweaks for individual microarchitectures, on the grounds that it'll mess up the AArch64 port, leading to complexity that is hard to justify. Having said that, there are not many companies designing AArch64 cores, and the optimizations they do are fairly similar, some more advanced than others but all going in the same general direction. So we can usually simply do the optimization for all, and no one is hurt by that.

Re optimizations in MacroAssembler. We already have quite a few, and they are very useful. The most successful ones have been load/store instruction fusion to `LDP`/`STP` and memory fence fusion. The latter is a significant performance gain in real-world benchmarks.

Because register-register `MOV` is already a macro rather than an instruction, we've generated nothing for `MOV Rx, Rx` since the beginning.

Where we really need to generate a certain instruction, we'll use an explicit call to `Assembler::`.

**Pull request closed without merging**
