### PR TITLE
8306772: Remove sun.security.x509.CertException, sun.security.x509.CertParseError

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this patch which removes the classes `sun.security.x509.CertException` and `sun.security.x509.CertParseError`.

These classes have been deprecated since before OpenJDK. They are internal classes which are not supported externally and strongly encapsulated by default.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306772](https://bugs.openjdk.org/browse/JDK-8306772): Remove sun.security.x509.CertException, sun.security.x509.CertParseError

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13624/head:pull/13624` \
`$ git checkout pull/13624`

Update a local copy of the PR: \
`$ git checkout pull/13624` \
`$ git pull https://git.openjdk.org/jdk.git pull/13624/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13624`

View PR using the GUI difftool: \
`$ git pr show -t 13624`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13624.diff">https://git.openjdk.org/jdk/pull/13624.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13624#issuecomment-1520664177)

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]
Add a `noreg` label to the issue. Otherwise, LGTM. Just for added assurance, I also ran a search on usages of these classes in Maven artifacts using an internal tool, and it found 0 matches.

**Comment by eirbjo** [comment]
> Add a `noreg` label to the issue. Otherwise, LGTM.

Added "noreg-cleanup" with an small justification in the description.

**Pull request closed without merging**
