### PR TITLE
8346739: jpackage tests failed after JDK-8345259

### PR DESCRIPTION
**Pull request by mlchung**
A few jpackage tests invoke `jlink --add-modules ALL-MODULE-PATH` without `--module-path` and they now fail because of JDK-8345259 which requires `--module-path` to be set when `ALL-MODULE-PATH` is used.  The fix is to add `--add-modules $JAVA_HOME/jmods` which was the default before JDK-8345259.  A separate issue is needed to skip these tests when running on a linkable runtime image without the packaged modules.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8346739: jpackage tests failed after JDK-8345259`

### Issue
 * [JDK-8346739](https://bugs.openjdk.org/browse/JDK-8346739): jpackage tests failed after JDK-8345259 (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - Author)
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22853/head:pull/22853` \
`$ git checkout pull/22853`

Update a local copy of the PR: \
`$ git checkout pull/22853` \
`$ git pull https://git.openjdk.org/jdk.git pull/22853/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22853`

View PR using the GUI difftool: \
`$ git pr show -t 22853`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22853.diff">https://git.openjdk.org/jdk/pull/22853.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22853#issuecomment-2557573177)
</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@alexeysemenyukoracle @jerboaa Can you review?

**Comment by mlchung** [comment]
Thanks Kevin.

You point out that PR [22644](https://github.com/openjdk/jdk/pull/22644) changes `ALL-MODULE-PATH` to use `java.desktop`.  I prefer to keep this PR to focus on fixing the tests by adding `--module-path` as that's the expected test cases.  I will let @jerboaa to do the proper fix for these tests via JDK-8345185.

**Comment by kevinrushforth** [comment]
Yes, that seems like the best approach to get these failing tests running again.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Comment by alexeysemenyukoracle** [comment]
Looks good. Thank you for the fix!

**Comment by mlchung** [comment]
Thanks for the review.

**Pull request closed without merging**
