### PR TITLE
8343242: RISC-V: Refactor materialization of literal address

### PR DESCRIPTION
**Pull request by RealFYang**
Hi, please consider this refactoring work.

Currently, we have both `la(address)` and `la(Address)`. They both accept and materialize literal address.
While `la(Address)` always emit a movptr sequence, `la(address)` is a bit complex: it checks whether the target is
reachable from anywhere within the code cache (`is_32bit_offset_from_codecache`) and emits pc-relative auipc+addi
pair or movptr sequence. This makes it not that obvious at places where we want a more accurate estimation about
the size of code emitted like when we prepare code stubs like C2SafepointPollStub or C2EntryBarrierStub (See: https://github.com/openjdk/jdk/pull/21732).

I would suggest we keep `la(address)` simple and let it only emit auipc+addi pair, which will be consistent with the
`RISC-V Assembly Programmer's Handbook`. I think It's more reasonable to move the distance check to `la(Address)`.
Furthermore, I would also suggest that we make the distance check simpler. The approach taken here is to only check
whether the target is inside the code cache. This way we will be more certain about code emitted with `la(Address)`
as well. This will help keep the risk of this change low as all `la(Address)` callsites with literal address outside of code
cache won't be affected. And I don't think the original distance check from code cache will benefit us much more.
Eyeballed all `la(Address)` callsites, I think we are fine.

Benefits:
1. We have a simpler `la(address)` which is kind of spec compatible;
2. We are consistent in target distance check when doing `j(Address)`, `la(Address)`, `ld/st(Address)` and `rt_call`;
3. We don't need explicit use of `relocate` with lambda for most of the places;

Note that there are several places where we want explicit `movptr` sequence:
1. In `SignatureHandlerGenerator::generate()` where the emitted code is simply copied without relocation [1];
2. In `movoop` and `mov_metadata` where we want patching afterwards;

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/interpreter/interpreterRuntime.cpp#L1313

Testing on linux-riscv64:
- [x] hotspot:tier1 (fastdebug)
- [x] tier1-tier3, hotspot:tier4 (release)
- [x] specjbb2015, dacapo, renaissance (release)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343242](https://bugs.openjdk.org/browse/JDK-8343242): RISC-V: Refactor materialization of literal address (**Enhancement** - P4)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21777/head:pull/21777` \
`$ git checkout pull/21777`

Update a local copy of the PR: \
`$ git checkout pull/21777` \
`$ git pull https://git.openjdk.org/jdk.git pull/21777/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21777`

View PR using the GUI difftool: \
`$ git pr show -t 21777`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21777.diff">https://git.openjdk.org/jdk/pull/21777.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21777#issuecomment-2445638584)
</details>

### CODE REVIEW

**Comment by robehn** [comment]
Hi, I agree with the sentiment of the CR.

Thinking about the is_32bit_offset_from_codecache vs CodeCache::contains change.

**Comment by RealFYang** [comment]
> Hi, I agree with the sentiment of the CR.
> 
> Thinking about the is_32bit_offset_from_codecache vs CodeCache::contains change.

Thanks! Note that I didn't remove this `is_32bit_offset_from_codecache` check as I am guessing that we might find a better way of using this check after this change.

**Comment by robehn** [comment]
Did you run any micro benchmarks? Maybe skynet just to check VTs.
And did you do any measurement on code cache size?

I can't find anything that would matter, but I'll look a bit more.

**Comment by RealFYang** [comment]
> Did you run any micro benchmarks? Maybe skynet just to check VTs. And did you do any measurement on code cache size?

 No obvious change witnessed on Skynet JMH with this change. Let me know if there are others we might want a try.

> And did you do any measurement on code cache size?

 Good suggestion. I just tried dacapo and renaissance with `-XX:+PrintCodeCache -XX:-TieredCompilation` and compared the `max_used` of code cache. I didn't see a big difference with this change either.

> I can't find anything that would matter, but I'll look a bit more.

Thanks. I merged master. Take your time!

**Review by robehn — APPROVED** [review]
Looks good, thanks!

**Review by feilongjiang — APPROVED** [review]
It looks much cleaner now. Thank you!

**Comment by RealFYang** [comment]
@robehn @feilongjiang : Thanks for the review! I also tried NetBeans and Eclipse. Both IDEs work fine with this change. Let's move on.
/integrate

**Pull request closed without merging**
