### PR TITLE
8264028: Typo in javax.management.relation.RelationService::purgeRelations

### PR DESCRIPTION
**Pull request by horizonzy**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264028](https://bugs.openjdk.java.net/browse/JDK-8264028): Typo in javax.management.relation.RelationService::purgeRelations

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2765/head:pull/2765` \
`$ git checkout pull/2765`

Update a local copy of the PR: \
`$ git checkout pull/2765` \
`$ git pull https://git.openjdk.java.net/jdk pull/2765/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2765`

View PR using the GUI difftool: \
`$ git pr show -t 2765`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2765.diff">https://git.openjdk.java.net/jdk/pull/2765.diff</a>

</details>

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please contact me at Dalibor.topic@oracle.com so that I can validate your OCA.

**Comment by shqking** [comment]
Hi. Just a reminder for you that the copyright year should be updated to 2021.

**Comment by horizonzy** [comment]
> Hi. Just a reminder for you that the copyright year should be updated to 2021.

thanks

**Comment by shipilev** [comment]
Hi, I have submitted the bug for it: https://bugs.openjdk.java.net/browse/JDK-8264028 -- please change the PR synopsis to "8264028: Typo in javax.management.relation.RelationService::purgeRelations" to get it properly hooked to PR metadata. After that, bots should tell what is next.

**Comment by horizonzy** [comment]
> Hi, I have submitted the bug for it: https://bugs.openjdk.java.net/browse/JDK-8264028 -- please change the PR synopsis to "8264028: Typo in javax.management.relation.RelationService::purgeRelations" to get it properly hooked to PR metadata. After that, bots should tell what is next.

ok, thanks.

**Comment by shqking** [comment]
You may want to enable the GitHub Actions. Please go to https://github.com/shqking/jdk/actions and then trigger the test workflow on your branch.

It would be fine if you do not run the test for this PR since only typo errors are fixed. 
But I suggest enabling this and in this way all the necessary tests would be run automatically for your new PRs in the near future once they are submitted.

**Comment by horizonzy** [comment]
> You may want to enable the GitHub Actions. Please go to https://github.com/horizonzy/jdk/actions and then trigger the test workflow on your branch.
> 
> It would be fine if you do not run the test for this PR since only typo errors are fixed.
> But I suggest enabling this and in this way all the necessary tests would be run automatically for your new PRs in the near future once they are submitted.

thanks for your suggest.

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thanks,
Serguei

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
