### PR TITLE
8307489: ProblemList jdk/incubator/vector/LoadJsvmlTest.java on windows-x64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial fixes to ProblemList a few tests:
- [JDK-8307489](https://bugs.openjdk.org/browse/JDK-8307489) ProblemList jdk/incubator/vector/LoadJsvmlTest.java on windows-x64
- [JDK-8307490](https://bugs.openjdk.org/browse/JDK-8307490) ProblemList sun/security/pkcs11/Cipher/TestKATForGCM.java on linux-x64 and macosx-x64
- [JDK-8307491](https://bugs.openjdk.org/browse/JDK-8307491) ProblemList sanity/client/SwingSet/src/EditorPaneDemoTest.java on linux-x64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8307489](https://bugs.openjdk.org/browse/JDK-8307489): ProblemList jdk/incubator/vector/LoadJsvmlTest.java on windows-x64
 * [JDK-8307490](https://bugs.openjdk.org/browse/JDK-8307490): ProblemList sun/security/pkcs11/Cipher/TestKATForGCM.java on linux-x64 and macosx-x64
 * [JDK-8307491](https://bugs.openjdk.org/browse/JDK-8307491): ProblemList sanity/client/SwingSet/src/EditorPaneDemoTest.java on linux-x64

### Reviewers
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13816/head:pull/13816` \
`$ git checkout pull/13816`

Update a local copy of the PR: \
`$ git checkout pull/13816` \
`$ git pull https://git.openjdk.org/jdk.git pull/13816/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13816`

View PR using the GUI difftool: \
`$ git pr show -t 13816`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13816.diff">https://git.openjdk.org/jdk/pull/13816.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13816#issuecomment-1535420066)

### CODE REVIEW

**Review by jddarcy — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@jddarcy - Thanks for the review!

/integrate

**Pull request closed without merging**
