### PR TITLE
8307196: Dangling pointer warning for MetadataAllocationRequest

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to work around a false positive -Wdangling-pointer
warning from gcc13.1. The approach being taken is to suppress the warning,
with a comment describing why it's a false positive.

As with JDK-8307147 I tried various code modifications to avoid the warning,
but they were either obscure, or didn't seem reliably future-proof against
further changes in gcc's analysis.

Testing:
mach5 tier1-3 with gcc11.2 (current default in Oracle's CI)

Local (linux-x64) tier1 with gcc13.1, and verified the relevant warnings are
not reported during the build. This required disabling compiler warnings as
errors, as there are other new warnings from gcc13.1: JDK-8307210.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307196](https://bugs.openjdk.org/browse/JDK-8307196): Dangling pointer warning for MetadataAllocationRequest

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13789/head:pull/13789` \
`$ git checkout pull/13789`

Update a local copy of the PR: \
`$ git checkout pull/13789` \
`$ git pull https://git.openjdk.org/jdk.git pull/13789/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13789`

View PR using the GUI difftool: \
`$ git pr show -t 13789`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13789.diff">https://git.openjdk.org/jdk/pull/13789.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13789#issuecomment-1534109951)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable. Thanks.

**Review by fisk — APPROVED** [review]
Looks... okay.

**Comment by kimbarrett** [comment]
Thanks for reviews @fisk and @dholmes-ora .

**Pull request closed without merging**
