### PR TITLE
8267806: C1: Relax inlining checks for not yet initialized classes

### PR DESCRIPTION
**Pull request by iwanowww**
The checks which guide inlining decisions in C1 are too strong: declaring holder class is required to be fully initialized while JVMS only mandates an initialization barrier on resolved class in `invokestatic` case.

The fix relaxes the checks to rule out only not yet linked classes unless it is an `invokestatic` call site.

Testing:
- [x] hs-tier1 - hs-tier9

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267806](https://bugs.openjdk.java.net/browse/JDK-8267806): C1: Relax inlining checks for not yet initialized classes

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4211/head:pull/4211` \
`$ git checkout pull/4211`

Update a local copy of the PR: \
`$ git checkout pull/4211` \
`$ git pull https://git.openjdk.java.net/jdk pull/4211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4211`

View PR using the GUI difftool: \
`$ git pr show -t 4211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4211.diff">https://git.openjdk.java.net/jdk/pull/4211.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by iwanowww** [comment]
Thanks for the reviews, Roland and Tobias.

/integrate

**Pull request closed without merging**
