### PR TITLE
8333775: Small improvement to outputStream auto-indentation mode

### PR DESCRIPTION
**Pull request by tstuefe**
Almost trivial enhancement.

[JDK-8333211](https://bugs.openjdk.org/browse/JDK-8333211) added automatic indentation. Some changes to complement that:

- let outputStream::set_autoindent() return the old value for later restoration
- add an RAII object to enable autoindent and restore the old state when leaving.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333775](https://bugs.openjdk.org/browse/JDK-8333775): Small improvement to outputStream auto-indentation mode (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**) ⚠️ Review applies to [4d70ec07](https://git.openjdk.org/jdk/pull/19592/files/4d70ec072b936bc820ca47deb1da6c84c16f25e1)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [4d70ec07](https://git.openjdk.org/jdk/pull/19592/files/4d70ec072b936bc820ca47deb1da6c84c16f25e1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19592/head:pull/19592` \
`$ git checkout pull/19592`

Update a local copy of the PR: \
`$ git checkout pull/19592` \
`$ git pull https://git.openjdk.org/jdk.git pull/19592/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19592`

View PR using the GUI difftool: \
`$ git pr show -t 19592`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19592.diff">https://git.openjdk.org/jdk/pull/19592.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19592#issuecomment-2155260529)

### CODE REVIEW

**Review by jdksjolen — APPROVED** [review]
Hi Thomas,

LGTM but can you make the `StreamAutoIndentor` `NONCOPYABLE' also? Copying it makes no sense. Trivial.

**Review by MBaesken — APPROVED** [review]

**Comment by txominpelu** [comment]
@tstuefe I was wondering if you think that it would make sense to include an `auto_indent` field in the `streamIndentor` object, rather than having a `StreamAutoIndentor` ? 

The reason why I'm suggesting that is that I cannot think of a valid case where I'd want to use the `streamIndentor` with `auto_indent` disabled.

**Comment by tstuefe** [comment]
> @tstuefe I was wondering if you think that it would make sense to include an `auto_indent` field in the `streamIndentor` object, rather than having a `StreamAutoIndentor` ?
> 
> The reason why I'm suggesting that is that I cannot think of a valid case where I'd want to use the `streamIndentor` with `auto_indent` disabled.

IIRC there are existing users of streamIndentor that don't expect automatic indentation.

**Pull request closed without merging**
