### PR TITLE
8253899: Make IsClassUnloadingEnabled signature match specification

### PR DESCRIPTION
**Pull request by VladimirKempik**
Please review this change for hotspot and one test.
There is few JVMTI callback/event functions in jdk which signature doesn't match specification.
for example:
static jvmtiError JNICALL IsClassUnloadingEnabled(const jvmtiEnv* env, jboolean* enabled, ...)
but according to jvmti specs it should be:
static jvmtiError JNICALL IsClassUnloadingEnabled(const jvmtiEnv* env, ...)
same with ClassUnload(jvmtiEnv* jvmti_env, JNIEnv* jni_env, const char* name, ...)  in tests
for many years that didn't matter but with coming JEP-391 it becomes important to make it match the spec
https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code
This commit makes the above mentioned functions to have signature matching jvmti specification

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ⏳ (2/9 running) | ⏳ (7/9 running) | ⏳ (1/9 running) |

### Issue
 * [JDK-8253899](https://bugs.openjdk.java.net/browse/JDK-8253899): Make IsClassUnloadingEnabled signature match specification

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to 1ef832d21f65f9f91b2f387068def7cab02b69ce
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/466/head:pull/466`
`$ git checkout pull/466`

### CODE REVIEW

**Comment by sspitsyn** [comment]
David,
I think, Vladimir is referring to the JVMTI extension mechanism spec:
  https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#jvmtiExtensionFunction

**Review by sspitsyn — APPROVED** [review]
Vladimir, it looks good to me.

**Comment by VladimirKempik** [comment]
> David,
> I think, Vladimir is referring to the JVMTI extension mechanism spec:
> https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#jvmtiExtensionFunction
> https://docs.oracle.com/en/java/javase/15/docs/specs/jvmti.html#jvmtiExtensionEvent

Hello Serguei, you are right, I was talking about this documents.
Thank you.

**Comment by dholmes-ora** [comment]
Okay but look at the example that documentation gives:

> For example, if the jvmtiParamInfo returned by GetExtensionEvents indicates that there is a jint parameter, the event handler should be declared:
> 
>         void JNICALL myHandler(jvmtiEnv* jvmti_env, jint myInt, ...)

The myInt is explicit, just as our "jboolean* enabled" is explicit. I think they key point is that the signature must end with "..." which it does.

I don't see anything here that needs to be fixed.

**Comment by VladimirKempik** [comment]
> Okay but look at the example that documentation gives:
> 
> > For example, if the jvmtiParamInfo returned by GetExtensionEvents indicates that there is a jint parameter, the event handler should be declared:
> > ```
> >     void JNICALL myHandler(jvmtiEnv* jvmti_env, jint myInt, ...)
> > ```
> 
> The myInt is explicit, just as our "jboolean* enabled" is explicit. I think they key point is that the signature must end with "..." which it does.
> 
> I don't see anything here that needs to be fixed.

Hello David. On majority of platforms this would be fine.

But on some platforms, variadic arguments and non variadic arguments are passed differently ( for example on macos-aarch64, variadic args are passed always on stack, non variadic on registers (and on stack for 9th+ arg) , that causes issues.

If you still see no issues here we can delay and make this changeset part of JEP-391.
But since this changeset isn't much macos-aarch64 specific, I thought it would be good to integrate it separately from jep-391.

Regards, Vladimir

**Comment by VladimirKempik** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-dev](mailto:hotspot-dev@openjdk.java.net):_
> 
> Hi Vladimir,
> 
> On 2/10/2020 5:37 pm, Vladimir Kempik wrote:
> 
> > On Fri, 2 Oct 2020 07:27:17 GMT, David Holmes <dholmes at openjdk.org> wrote:
> > > Okay but look at the example that documentation gives:
> > > > For example, if the jvmtiParamInfo returned by GetExtensionEvents indicates that there is a jint parameter, the event
> > > > handler should be declared: ```
> > > > void JNICALL myHandler(jvmtiEnv* jvmti_env, jint myInt, ...)
> > > > ```
> > > 
> > > 
> > > The myInt is explicit, just as our "jboolean* enabled" is explicit. I think they key point is that the signature must
> > > end with "..." which it does.
> > > I don't see anything here that needs to be fixed.
> > 
> > 
> > Hello David. On majority of platforms this would be fine.
> > But on some platforms, variadic arguments and non variadic arguments are passed differently ( for example on
> > macos-aarch64, variadic args are passed always on stack, non variadic on registers (and on stack for 9th+ arg) , that
> > causes issues.
> 
> Okay - I see the potential for a problme here but ...
> 
> > If you still see no issues here we can delay and make this changeset part of JEP-391.
> > But since this changeset isn't much macos-aarch64 specific, I thought it would be good to integrate it separately from
> > jep-391.
> 
> ... this change actually goes against the example in the spec, so if you
> make this change it indicates the spec needs to be updated too.
> 
> Cheers,
> David
> -----

Hello David

I really believe the problem is in document here ( in examples)
first, the doc clearly specify the type

typedef jvmtiError (JNICALL *jvmtiExtensionFunction)
    (jvmtiEnv* jvmti_env,
      ...);

then in examples it declares the function not matching this spec.

Is it a good idea to update the docs in a separate bug ?

Thanks, Vladimir

**Comment by VladimirKempik** [comment]
Hello David
I have created CSR draft
https://bugs.openjdk.java.net/browse/JDK-8254014

Regards, Vladimir

**Comment by VladimirKempik** [comment]
Hello
I have updated the PR with changes from spec of CSR

Regards, Vladimir

**Review by dholmes-ora — APPROVED** [review]
Looks good.
Thanks,
David

**Pull request closed without merging**
