### PR TITLE
8344330: Remove AccessController.doPrivileged() from jdk.charsets module

### PR DESCRIPTION
**Pull request by naotoj**
Removing a `AccessController.doPrivileged()` call from jdk.charsets module after JEP486 integration.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344330](https://bugs.openjdk.org/browse/JDK-8344330): Remove AccessController.doPrivileged() from jdk.charsets module (**Enhancement** - P3)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22162/head:pull/22162` \
`$ git checkout pull/22162`

Update a local copy of the PR: \
`$ git checkout pull/22162` \
`$ git pull https://git.openjdk.org/jdk.git pull/22162/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22162`

View PR using the GUI difftool: \
`$ git pr show -t 22162`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22162.diff">https://git.openjdk.org/jdk/pull/22162.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22162#issuecomment-2479778830)
</details>

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by bplb — APPROVED** [review]
Looks fine.

**Review by RogerRiggs — APPROVED** [review]
looks good.

**Review by bplb — APPROVED** [review]
Updated version looks fine.

**Review by LanceAndersen — APPROVED** [review]

**Review by justin-curtis-lu — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Comment by naotoj** [comment]
Thank you for your reviews!
/integrate

**Pull request closed without merging**
