### PR TITLE
8029301: Confusing error message for array creation method reference

### PR DESCRIPTION
**Pull request by archiecobbs**
The error for an invalid constructor reference of an array type looks like this:
```java
Test.java:3: error: incompatible types: invalid constructor reference
        Runnable r = String[]::new;
                     ^
    constructor Array in class Array cannot be applied to given types
      required: int
      found:    no arguments
      reason: actual and formal argument lists differ in length
```
The phrase "constructor Array in class Array" is somewhat confusing.

This is a simple patch to reword this type of error to look like this instead:
```java
Test.java:3: error: incompatible types: invalid constructor reference
        Runnable r = String[]::new;
                     ^
    cannot create array from given types
      required: int
      found:    no arguments
      reason:   actual and formal argument lists differ in length
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8029301](https://bugs.openjdk.org/browse/JDK-8029301): Confusing error message for array creation method reference

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [4c6e1377](https://git.openjdk.org/jdk/pull/12646/files/4c6e1377408e37e3d273e3910f64be6c64b772e0)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12646/head:pull/12646` \
`$ git checkout pull/12646`

Update a local copy of the PR: \
`$ git checkout pull/12646` \
`$ git pull https://git.openjdk.org/jdk.git pull/12646/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12646`

View PR using the GUI difftool: \
`$ git pr show -t 12646`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12646.diff">https://git.openjdk.org/jdk/pull/12646.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Comment by archiecobbs** [comment]
> @archiecobbs The “[sponsor](https://github.com/openjdk/jdk/labels/sponsor)” label has been removed.

Yeah I saw that. Wasn't sure what I was supposed to do but figured out another`/integrate` was needed...

Thanks for the hint.

**Pull request closed without merging**
