### PR TITLE
8260308: Update LogCompilation junit to 4.13.1

### PR DESCRIPTION
**Pull request by lutkerd**
Build and tested on Centos8.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260308](https://bugs.openjdk.java.net/browse/JDK-8260308): Update LogCompilation junit to 4.13.1

### Reviewers
 * [Eric Caspole](https://openjdk.java.net/census#ecaspole) (@ericcaspole - Committer)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2199/head:pull/2199`
`$ git checkout pull/2199`

### CODE REVIEW

**Comment by iignatev** [comment]
@ericcaspole, as a person who has been involved w/ LogCompilation tool recently, could you please take a look at this PR?

**Review by ericcaspole — APPROVED** [review]
Good. Thanks for keeping it up to date.

**Review by iignatev — APPROVED** [review]

**Pull request closed without merging**
