### PR TITLE
8223077: module path support for dynamic CDS archive

### PR DESCRIPTION
**Pull request by calvinccheung**
Please review this patch for adding module path support for CDS dynamic archive.
Before this patch, if a module path was specified when creating a base archive, the user
won't be able to create a dynamic archive based on the base archive.
VM will issue the following warning:
"Dynamic archiving is disabled because base layer archive has module path"

This patch adds checking of the module patsh in the base archive and the ones specified
for dynamic dumping. If the module paths are the same, dynamic archive will be created.

Testing: tiers 1, 2.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8223077](https://bugs.openjdk.java.net/browse/JDK-8223077): module path support for dynamic CDS archive

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to fe11eb6daa6e861f75ed3f0ea13f2758bef6e018
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7437/head:pull/7437` \
`$ git checkout pull/7437`

Update a local copy of the PR: \
`$ git checkout pull/7437` \
`$ git pull https://git.openjdk.java.net/jdk pull/7437/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7437`

View PR using the GUI difftool: \
`$ git pr show -t 7437`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7437.diff">https://git.openjdk.java.net/jdk/pull/7437.diff</a>

</details>

### CODE REVIEW

**Review by yminqi — APPROVED** [review]
LGTM
TestCommon.java and UnsupportedBaseArchive.java need copyright year update.

**Comment by calvinccheung** [comment]
> LGTM. Instead of "investigate ...", I think the name of the issue should describe the change.

Thanks for the review. I've dropped the word "Investigate" from the title.

**Review by yminqi — APPROVED** [review]
Change LG.

**Pull request closed without merging**
