### PR TITLE
8275662: remove test/lib/sun/hotspot

### PR DESCRIPTION
**Pull request by coleenp**
This change removes the last remnants of sun/hotspot/WhiteBox.java and other classes, and uses the versions in jdk/test/whitebox.
I used sed to change sun.hotspot.{gc,code,cpuinfo} to jdk.test.whitebox and deleted the old files and some references to sun.hotspot.
Tested with tier1-4.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8275662](https://bugs.openjdk.org/browse/JDK-8275662): remove test/lib/sun/hotspot

### Reviewers
 * [Mikhailo Seledtsov](https://openjdk.org/census#mseledtsov) (@mseledts - Committer)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9434/head:pull/9434` \
`$ git checkout pull/9434`

Update a local copy of the PR: \
`$ git checkout pull/9434` \
`$ git pull https://git.openjdk.org/jdk pull/9434/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9434`

View PR using the GUI difftool: \
`$ git pr show -t 9434`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9434.diff">https://git.openjdk.org/jdk/pull/9434.diff</a>

</details>

### CODE REVIEW

**Review by mseledts — APPROVED** [review]
Changes look good to me. Thank you.

**Comment by coleenp** [comment]
Thanks Misha!

**Review by sspitsyn — APPROVED** [review]
This looks good.
Thanks,
Serguei

**Review by lmesnik — APPROVED** [review]

**Comment by coleenp** [comment]
Thanks Serguei and Leonid.
/integrate

**Pull request closed without merging**
