### PR TITLE
8198622: java/awt/Focus/TypeAhead/TestFocusFreeze.java fails on mac

### PR DESCRIPTION
**Pull request by alisenchung**
test passes, so removing from problem list

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8198622](https://bugs.openjdk.java.net/browse/JDK-8198622): java/awt/Focus/TypeAhead/TestFocusFreeze.java fails on mac
 * [JDK-6447537](https://bugs.openjdk.java.net/browse/JDK-6447537): EnqueueWithDialogTest & TestFocusFreeze fail

### Reviewers
 * [Jayathirth D V](https://openjdk.java.net/census#jdv) (@jayathirthrao - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8254/head:pull/8254` \
`$ git checkout pull/8254`

Update a local copy of the PR: \
`$ git checkout pull/8254` \
`$ git pull https://git.openjdk.java.net/jdk pull/8254/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8254`

View PR using the GUI difftool: \
`$ git pr show -t 8254`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8254.diff">https://git.openjdk.java.net/jdk/pull/8254.diff</a>

</details>

### CODE REVIEW

**Comment by prrace** [comment]
Hmm .. so no idea why it passes now ? 4 years since this bug was filed but the info then was minimal. 
Can you see if it reproduces with JDK 11 ? If yes, then try later JDKs one by one until you find what fixed it.

**Comment by jayathirthrao** [comment]
We should add https://bugs.openjdk.java.net/browse/JDK-6447537 also in the PR and decouple test/java/awt/KeyboardFocusmanager/TypeAhead/EnqueueWithDialogTest failure into new bug. https://bugs.openjdk.java.net/browse/JDK-8198622 captures failure only specific to macOS.

https://bugs.openjdk.java.net/browse/JDK-6447537 captures history of why this test started failing in Windows & Linux which might give idea about how it is not failing now. Also its better to run the test multiple times since we are de-problem listing on all platforms.

**Comment by alisenchung** [comment]
The test passes in jdk8 through jdk11 on macos.

**Comment by alisenchung** [comment]
Heres the decoupled bug: https://bugs.openjdk.java.net/browse/JDK-8285278

**Review by jayathirthrao — APPROVED** [review]

**Pull request closed without merging**
