### PR TITLE
8305672: Surprising definite assignment error after JDK-8043179

### PR DESCRIPTION
**Pull request by archiecobbs**
The fix for [JDK-8043179](https://bugs.openjdk.org/browse/JDK-8043179) is to clear the DU flags for all variables when entering a lamba. This reflects the fact that the lamba's actual execution could be arbitrarily far in the future, so we can't assume anything that is DU when the lambda is created is still DU when the lambda actually executes.

However, this fix created a new bug. The problem is that `visitLambda()` does not save & restore the `uninitsTry` bits, which are used by `visitTry()` to track DU variables within `try { }` blocks. So if there is a `try { }` block outside the lambda and a `try { }` block inside the lambda, the latter can "leak" DU state up to the former via this field. As a result, a final variable that should still be DU at the completion of the outer `try { }` block can be incorrectly recorded as not DU, leading to the bogus "might already have been assigned" error.

This patch fixes that by adding the necessary save & restore logic.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305672](https://bugs.openjdk.org/browse/JDK-8305672): Surprising definite assignment error after JDK-8043179

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - Author) ⚠️ Review applies to [a07bdb78](https://git.openjdk.org/jdk/pull/13366/files/a07bdb7839a7c6cdea23c41fa1dccc2feb246f08)
 * @gafter (no known openjdk.org user name / role)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13366/head:pull/13366` \
`$ git checkout pull/13366`

Update a local copy of the PR: \
`$ git checkout pull/13366` \
`$ git pull https://git.openjdk.org/jdk.git pull/13366/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13366`

View PR using the GUI difftool: \
`$ git pr show -t 13366`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13366.diff">https://git.openjdk.org/jdk/pull/13366.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13366#issuecomment-1498252489)

### CODE REVIEW

**Comment by cushon** [comment]
I'm not a Reviewer, but this looks good to me. I confirmed this fixes the original issue that I minimized for JDK-8305672.

**Comment by caoman** [comment]
Could any Reviewer from compiler-dev@ review this change?

We run large-scale tests against recent OpenJDK commits with our internal workload. This bug has caused several failures and blocked us from updating to the latest OpenJDK tip.

**Comment by kevinrushforth** [comment]
We just ran into this bug trying to compile JavaFX 21 with JDK 21. I raised the priority of the bug to P2, since this is a serious regression with no obvious workaround.

@vicente-romero-oracle since you reviewed and sponsored the fix for [JDK-8043179](https://bugs.openjdk.org/browse/JDK-8043179) in PR #10381 would you be able to review this?

**Review by kevinrushforth — APPROVED** [review]
I don't know this code area at all (and am not a jdk Reviewer), but I can confirm that this PR fixes the bug for me. After applying this patch and building a local JDK, I am able to compile JavaFX again.

**Comment by vicente-romero-oracle** [comment]
the fix looks good to me, running regression tests now to make sure nothing breaks, will approve if all green

**Review by gafter — APPROVED** [review]
Hi @gafter, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user gafter for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Comment by archiecobbs** [comment]
Thanks for the review @vicente-romero-oracle !

/integrate

**Comment by vicente-romero-oracle** [comment]
> Thanks for the review @vicente-romero-oracle !
> 
> /integrate

sure thanks @kevinrushforth and @neil too

**Pull request closed without merging**
