### PR TITLE
8295344: Harden runtime/StackGuardPages/TestStackGuardPages.java

### PR DESCRIPTION
**Pull request by jdksjolen**
There are multiple ways which the stack guard pages tests can be hardened:
- Rewritten the Java part of the test using ProcessTools.executeProcess(ProcessBuilder pb) which will make stdout/stderr be consistently logged and debugging much easier.
- Split up initial/other thread into 2 tests
- Split up Java thread tests and native thread tests into two separate files
- Check more error conditions in the C code
- Instead of recursing and creating stack frames, just `alloca()` and poke until we hit a `SIGSEGV`.

The goal is that this will help us out with  [JDK-8293452](https://bugs.openjdk.org/browse/JDK-8293452).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295344](https://bugs.openjdk.org/browse/JDK-8295344): Harden runtime/StackGuardPages/TestStackGuardPages.java

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12386/head:pull/12386` \
`$ git checkout pull/12386`

Update a local copy of the PR: \
`$ git checkout pull/12386` \
`$ git pull https://git.openjdk.org/jdk pull/12386/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12386`

View PR using the GUI difftool: \
`$ git pr show -t 12386`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12386.diff">https://git.openjdk.org/jdk/pull/12386.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
All seems quite reasonable. Thanks.

**Review by dholmes-ora — APPROVED** [review]
So effectively this issue replaces JDK-8293452 and if the failure no longer shows up then JDK-8293452 will be closed as d uplicate of this issue?

**Comment by jdksjolen** [comment]
> So effectively this issue replaces JDK-8293452 and if the failure no longer shows up then JDK-8293452 will be closed as duplicate of this issue?

Sure, closing it as a Duplicate if the issue no longer shows up sounds OK to me.If it does show up, I was planning to solve it and submit the PR as JDK-8293452.

**Review by robehn — APPROVED** [review]
Seems ok!

**Comment by jdksjolen** [comment]
/integrate

Thanks!

**Pull request closed without merging**
