### PR TITLE
8345647: Fix recent NULL usage backsliding in Shenandoah

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR addresses [8345647](https://bugs.openjdk.org/browse/JDK-8345647) addressing uses of `NULL` in Shenandoah. These should be replaced to `null`. 

I verified where those uses are with: 
`git show <commit-id> --name-only | while read file; do echo "File: $file"; git diff <commit-id> -- "$file" | grep -n -F 'NULL'; done`

The relevant output: 
```
File: src/hotspot/cpu/ppc/gc/shenandoah/shenandoahBarrierSetAssembler_ppc.cpp
9:-  // No need for post barrier if storing NULL
File: src/hotspot/share/gc/shenandoah/c2/shenandoahBarrierSetC2.cpp
9:-    // must be either an oop or NULL
12:     if (t == TypePtr::NULL_PTR || t == Type::TOP)
```

Changes affect comments only. 

Thanks, 
Sonia

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345647](https://bugs.openjdk.org/browse/JDK-8345647): Fix recent NULL usage backsliding in Shenandoah (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22647/head:pull/22647` \
`$ git checkout pull/22647`

Update a local copy of the PR: \
`$ git checkout pull/22647` \
`$ git pull https://git.openjdk.org/jdk.git pull/22647/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22647`

View PR using the GUI difftool: \
`$ git pr show -t 22647`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22647.diff">https://git.openjdk.org/jdk/pull/22647.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22647#issuecomment-2531923921)
</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Well, it is not technically a `NULL -> nullptr` changes we handle with PRs like these, but I guess it is good to have a consistent wording.

**Review by TheShermanTanker — APPROVED** [review]
Not really sure if just a comment change warrants a Pull Request, but since it is already done and is trivial why not

**Review by Hamlin-Li — APPROVED** [review]
Looks good.

**Comment by kimbarrett** [comment]
> Well, it is not technically a `NULL -> nullptr` changes we handle with PRs like these, but I guess it is good to have a consistent wording.

We've also been changing "NULL" in comments and strings.  This avoids having an identifier in those that isn't actually
present in code.  Perhaps more importantly, it prepares for JDK-8343802.  In comments and strings we sometimes use
"null" and sometimes use "nullptr", depending on whether the context code-like or not.

**Comment by kimbarrett** [comment]
> Not really sure if just a comment change warrants a Pull Request, but since it is already done and is trivial why not

*Any* change requires a JBS issue and a PR.  Sometimes something simple like this can be folded into another change.

**Comment by kimbarrett** [comment]
Unfortunately, this change was incomplete.  It missed these:

./share/gc/shenandoah/shenandoahFreeSet.cpp:  // Overwrite with non-zero (non-NULL) values only if necessary for allocation bookkeeping.
./share/gc/shenandoah/shenandoahGenerationalEvacuationTask.cpp:      assert(obj->klass() != nullptr, "klass should not be NULL");

In both of those lines, s/NULL/null/

Sorry I didn't point this out before this PR was integrated.  I only noticed the PR this morning.

**Comment by kimbarrett** [comment]
New JBS issue for the missed cases:
https://bugs.openjdk.org/browse/JDK-8346008

**Comment by SoniaZaldana** [comment]
Hi @kimbarrett, thanks for taking a look. Apologies for missing those. I can follow up with a PR for the remaining changes.

**Pull request closed without merging**
