### PR TITLE
8335628: C2 SuperWord: cleanup: remove SuperWord::longer_type_for_conversion

### PR DESCRIPTION
**Pull request by eme64**
After [JDK-8325155](https://bugs.openjdk.org/browse/JDK-8325155), there is now only a single use of `SuperWord::longer_type_for_conversion`.
The check there is rather useless,  and we should just remove it for the sake of code complexity.

**What did this check do?**
It checks if the input-type of a node is larger than the output type, relevant in these cases:
- `is_convert_opcode`
- `is_scalar_op_that_returns_int_but_vector_op_returns_long`

If there is a larger type, it checks if this larger type can even create vectors of at least size 2:
- `Matcher::max_vector_size_auto_vectorization(longer_bt) < 2)`

Of course if there cannot be vectors for this larger type, then we could avoid creating these vectors.

**Why is it rather useless?**
On most modern platforms, all types have vectors of at least length 2. So this would never fail on those platforms.
And even if this check fails: we would pack the nodes and later reject those packs when we do the `implemented` checks. Hence, we do not wrongly vectorize anyway. The cost of removing this check is that on most platforms we do not have to do this check, and the few that it would fail for just have a bit more compilation time (but very very minimal increase). I think this is worth the reduction in complexity. But we could always revert this change if there are problems because of it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335628](https://bugs.openjdk.org/browse/JDK-8335628): C2 SuperWord: cleanup: remove SuperWord::longer_type_for_conversion (**Enhancement** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20009/head:pull/20009` \
`$ git checkout pull/20009`

Update a local copy of the PR: \
`$ git checkout pull/20009` \
`$ git pull https://git.openjdk.org/jdk.git pull/20009/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20009`

View PR using the GUI difftool: \
`$ git pr show -t 20009`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20009.diff">https://git.openjdk.org/jdk/pull/20009.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20009#issuecomment-2208178522)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
That looks reasonable to me.

**Review by vnkozlov — COMMENTED** [review]
There was micro `TypeVectorOperations.java ` in [8283091](https://github.com/openjdk/jdk/commit/a1795901ee292fa6272768cef2fedcaaf8044074) changes. Can you check that there is no regression on our supported platforms?

**Comment by eme64** [comment]
Ok, I'll run it on a few platforms and report back!

**Comment by eme64** [comment]
@vnkozlov I ran that benchmark both on x64 (AVX512) and aarch64 (neon). There is no significant difference. (i.e. the difference between the SuperWord and non-SuperWord runs of that benchmark is in factors 2x-10x, the difference between master and patch of the SuperWord run is in the normal noise range).

**Review by vnkozlov — APPROVED** [review]
Thank you for additional performance testing.

**Comment by eme64** [comment]
Thanks @vnkozlov @chhagedorn for the reviews.
/integrate

**Pull request closed without merging**
