### PR TITLE
8284090: com/sun/security/auth/module/AllPlatforms.java fails to compile

### PR DESCRIPTION
**Pull request by DamonFool**
Please review this trivial change which fixes the compilation failure of the test.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284090](https://bugs.openjdk.java.net/browse/JDK-8284090): com/sun/security/auth/module/AllPlatforms.java fails to compile

### Reviewers
 * [Sean Mullan](https://openjdk.java.net/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8057/head:pull/8057` \
`$ git checkout pull/8057`

Update a local copy of the PR: \
`$ git checkout pull/8057` \
`$ git pull https://git.openjdk.java.net/jdk pull/8057/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8057`

View PR using the GUI difftool: \
`$ git pr show -t 8057`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8057.diff">https://git.openjdk.java.net/jdk/pull/8057.diff</a>

</details>

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]
This PR has not appeared on the security-dev alias, so there might be a problem with Skara - will report it. Approving anyway.

**Comment by DamonFool** [comment]
> This PR has not appeared on the security-dev alias, so there might be a problem with Skara - will report it. Approving anyway.

Thanks @seanjmullan .
Shall we push it right now?

**Comment by seanjmullan** [comment]
Yes, go ahead and integrate.

**Pull request closed without merging**
