### PR TITLE
8257726: Make -XX:+StressLdcRewrite option a diagnostic option

### PR DESCRIPTION
**Pull request by coleenp**
See bug for details.  Tested:

$ java -XX:+StressLdcRewrite -version
Error: VM option 'StressLdcRewrite' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
Error: The unlock option must precede 'StressLdcRewrite'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ java -XX:+UnlockDiagnosticVMOptions -XX:+StressLdcRewrite -version
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-2020-12-15-1356558.coleen...)
OpenJDK 64-Bit Server VM (build 16-internal+0-2020-12-15-1356558.coleen..., mixed mode, sharing)

Also, java/lang/instrument which has a test using StressLdcRewrite and tier1.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257726](https://bugs.openjdk.java.net/browse/JDK-8257726): Make -XX:+StressLdcRewrite option a diagnostic option

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1783/head:pull/1783`
`$ git checkout pull/1783`

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
Looks good Coleen.
Lois

**Review by tstuefe — APPROVED** [review]
Looks right to me, and trivial. This should not be a product option.
I cannot believe anyone uses this option in earnest in production. Still, out of sheer fascination I googled but did not find any serious usage.

**Comment by coleenp** [comment]
> I cannot believe anyone uses this option in earnest in production. Still, out of sheer fascination I googled but did not find any serious usage.
I discussed this with @dcubed-ojdk who added this for a customer situation and this was his request.
Thanks for the code review.
Coleen

**Review by yminqi — COMMENTED** [review]
jvmtiRedfineClasses.cpp use it.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up!

**Comment by coleenp** [comment]
Thanks Lois, Thomas and Dan.
/integrate

**Pull request closed without merging**
