### PR TITLE
8314319: LogCompilation doesn't reset lateInlining when it encounters a failure.

### PR DESCRIPTION
**Pull request by navyxliu**
This patch fixed a bug in LogCompilation. A compilation may encounter a failure after it processes 
'<late_inline>' tag. Sometimes, C2 compiler would retry after tweaking options. In this case, it would retry it 
without subsume_load. If we don't reset lateInlining, we may have trouble in the retry run. 

We also develop a unittest to verify that. A strip jit.xml is placed in test/resources/ directory. 

It's worth noting that 'mvn test' reports the 2 tests passed even without this patch. We can see the stacktrace
of exceptions. This isn't an accident.  There are 2 reasons: 
1. LogParser::parse swallows any throwable in its exception handler.
2. surefire runs in parallel and can't capture the failure.

I am not sure they are by design. I manage to fix those 2 problems, but fixing them is beyond the scope of this
patch. I would like to hear reviewer's feedbacks first.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314319](https://bugs.openjdk.org/browse/JDK-8314319): LogCompilation doesn't reset lateInlining when it encounters a failure. (**Bug** - P4)

### Reviewers
 * [Eric Caspole](https://openjdk.org/census#ecaspole) (@ericcaspole - Committer)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15375/head:pull/15375` \
`$ git checkout pull/15375`

Update a local copy of the PR: \
`$ git checkout pull/15375` \
`$ git pull https://git.openjdk.org/jdk.git pull/15375/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15375`

View PR using the GUI difftool: \
`$ git pr show -t 15375`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15375.diff">https://git.openjdk.org/jdk/pull/15375.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15375#issuecomment-1687343588)

### CODE REVIEW

**Comment by navyxliu** [comment]
Hi, 
Can I get reviewed for this change? 
thanks,
--lx

**Review by ericcaspole — APPROVED** [review]
Looks good, thanks for figuring this out.

**Review by vnkozlov — APPROVED** [review]
Looks good.
I ran tier1 testing to make sure it passed our source code validation (for your new test). It passed.

**Comment by navyxliu** [comment]
thank you for reviewing this!

**Pull request closed without merging**
