### PR TITLE
8255878: FilterInputStream is missing implementations of Java 9 InputStream methods

### PR DESCRIPTION
**Pull request by bplb**
This request proposes to modify `java.io.FilterInputStream` to override `readAllBytes()`, `readNBytes(int)`, `skipNBytes(long)`, and `transferTo(OutputStream)` in order to leverage any performance advantage that the wrapped stream might have over the `java.io.InputStream` implementations of these methods.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Integration blocker
&nbsp;⚠️ The change requires a CSR request to be approved.

### Issue
 * [JDK-8255878](https://bugs.openjdk.java.net/browse/JDK-8255878): FilterInputStream is missing implementations of Java 9 InputStream methods

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5367/head:pull/5367` \
`$ git checkout pull/5367`

Update a local copy of the PR: \
`$ git checkout pull/5367` \
`$ git pull https://git.openjdk.java.net/jdk pull/5367/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5367`

View PR using the GUI difftool: \
`$ git pr show -t 5367`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5367.diff">https://git.openjdk.java.net/jdk/pull/5367.diff</a>

</details>

### CODE REVIEW

**Comment by bplb** [comment]
A quick and dirty benchmark of `readAllBytes()` and `readNBytes(int)` revealed throughput thrice that of the version without these overrides. The benchmark consisted of calling these methods on a `BufferedInputStream` with a buffer size of 1 MB wrapping a `FileInputStream` opened on a file of size 1 MB.

**Before:**
```
Benchmark                 Mode  Cnt     Score    Error  Units
ReadNBytes.readAllBytes  thrpt    5  2735.935 ± 26.461  ops/s
ReadNBytes.readNBytes    thrpt    5  2735.949 ± 16.348  ops/s
```
**After:**
```
Benchmark                 Mode  Cnt     Score     Error  Units
ReadNBytes.readAllBytes  thrpt    5  8245.034 ± 135.084  ops/s
ReadNBytes.readNBytes    thrpt    5  8320.554 ± 104.707  ops/s
```

**Comment by dfuch** [comment]
This will probably break all existing subclasses that assume that they only need to override the single 
`int read()` method - because overriding this single method will now no longer be sufficient.

Did you conduct a survey of existing subclasses of FilterInputStream (recursively), in the JDK and elsewhere, to evaluate the impact of this change?

**Comment by AlanBateman** [comment]
> This may potentially break any existing subclasses that assume that they only need to override the three
> `int read()` and `int read(byte[], int, it)` and `int skip(int)` methods - because overriding only these three methods will now no longer be sufficient.

Can you explain this a bit further? InputStream has one abstract method so that's the minimum that has to be implemented. It has base implementations of readAllBytes and readNBytes that would be very inefficient if the 3-arg read is not overridden but I wouldn't expect a correctness issue.

**Comment by dfuch** [comment]
> Can you explain this a bit further? InputStream has one abstract method so that's the minimum that has to be implemented. It has base implementations of readAllBytes and readNBytes that would be very inefficient if the 3-arg read is not overridden but I wouldn't expect a correctness issue.

readAllBytes/readNBytes no longer call any variant of `this.read` - so any subclass that implement the two `read` methods to do something more than what `in.read` might fail in unexpected ways if `readAllBytes` or `readNBytes` are called. I'm especially concerned with subclasses like e.g. `KeepAliveStream` / `MetteredStream` in `sun.net.www.http`

**Comment by AlanBateman** [comment]
> readAllBytes/readNBytes no longer call any variant of `this.read` - so any subclass that implement the two `read` methods to do something more than what `in.read` does might fail in unexpected ways if `readAllBytes` or `readNBytes` are called. I'm especially concerned with subclasses like e.g. `KeepAliveStream` / `MetteredStream` in `sun.net.www.http`

Ah yes, I think you are right. In that case JDK-8255878 can be closed as WNF or else FilterInputStream provides implementations of these methods that don't directly delegate.

**Comment by dfuch** [comment]
> Ah yes, I think you are right. In that case JDK-8255878 can be closed as WNF or else FilterInputStream provides implementations of these methods that don't directly delegate.

We could set a boolean in the constructor if `this.getClass() == FilterInputStream.class` and only delegate in that case. On the other hand - FilterInputStream seems to be intended for subclassing, so maybe that optimization should be done in its subclasses instead, when possible. That said - I see that the class level documentation of FilterInputStream says:

> The class FilterInputStream itself simply overrides all methods of InputStream with versions that pass all requests to the contained input stream.

which is no longer strictly true - should this sentence be amended to reflect what really happens?

**Comment by bplb** [comment]
Created [JDK-8273513](https://bugs.openjdk.java.net/browse/JDK-8273513). Closing this ill-conceived PR as being of too little value compared to the risk of subclass breakage.

**Pull request closed without merging**
