### PR TITLE
8287453: RenderPerfTest incorrectly measures performance

### PR DESCRIPTION
**Pull request by avu**
Improved RenderPerfTest:
  - removed RenderPerfLCD.java (we have LCD tests in RenderPerfTest.java)
  - corrected and simplified test logic
  - added timeout on low performant rendering
  - used several markers to recover from missing frames
  - protected measurements from multiple paint invocations

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287453](https://bugs.openjdk.java.net/browse/JDK-8287453): RenderPerfTest incorrectly measures performance

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8928/head:pull/8928` \
`$ git checkout pull/8928`

Update a local copy of the PR: \
`$ git checkout pull/8928` \
`$ git pull https://git.openjdk.java.net/jdk pull/8928/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8928`

View PR using the GUI difftool: \
`$ git pr show -t 8928`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8928.diff">https://git.openjdk.java.net/jdk/pull/8928.diff</a>

</details>

### CODE REVIEW

**Comment by aghaisas** [comment]
Is it only a test stabilization fix? or were you able to uncover any performance issue (either with OpenGL or with Metal pipeline) with this change? Can you please provide before/after numbers?

**Comment by avu** [comment]
> Is it only a test stabilization fix? or were you able to uncover any performance issue (either with OpenGL or with Metal pipeline) with this change? Can you please provide before/after numbers?

Initially it was a stabilization fix. However, I found couple of issues: missing frames (I have minimal test case and going to file an issue) and low performance in some  test cases comparing with OGL. I've attached the results to  this issue.

**Review by prrace — APPROVED** [review]

**Comment by aghaisas** [comment]
> > Is it only a test stabilization fix? or were you able to uncover any performance issue (either with OpenGL or with Metal pipeline) with this change? Can you please provide before/after numbers?
> 
> Initially it was a stabilization fix. However, I've found couple of issues: missing frames (I have minimal test case and here is the issue [JDK-8287600](https://bugs.openjdk.java.net/browse/JDK-8287600) ) and low performance in some test cases comparing with OGL. I've attached the results to this issue.

Thanks for providing the performance numbers in JBS and filing the issue for missing frame.

Another bug needs to be filed for tests having lower performance with the Metal pipeline as compared to OpenGL pipeline.
It's a surprise that the modified RenderPerf test shows considerable performance difference (whereas J2DBench tests show difference only in some cases)

**Comment by avu** [comment]
> > > Is it only a test stabilization fix? or were you able to uncover any performance issue (either with OpenGL or with Metal pipeline) with this change? Can you please provide before/after numbers?
> > 
> > 
> > Initially it was a stabilization fix. However, I've found couple of issues: missing frames (I have minimal test case and here is the issue [JDK-8287600](https://bugs.openjdk.java.net/browse/JDK-8287600) ) and low performance in some test cases comparing with OGL. I've attached the results to this issue.
> 
> Thanks for providing the performance numbers in JBS and filing the issue for missing frame.
> 
> Another bug needs to be filed for tests having lower performance with the Metal pipeline as compared to OpenGL pipeline. It's a surprise that the modified RenderPerf test shows considerable performance difference (whereas J2DBench tests show difference only in some cases)

Yes, it was a surprise. We've enabled metal in EAP of our IDEs and got some complains about the performance. So, I've decided to revise our measurements. I have fixes for the problems above, but they are not complete yet. (still fighting with some regressions)

**Comment by avu** [comment]
> Another bug needs to be filed for tests having lower performance with the Metal pipeline as compared to OpenGL pipeline.
I've filed [JDK-8287694](https://bugs.openjdk.java.net/browse/JDK-8287694)

**Pull request closed without merging**
