### PR TITLE
JDK-8259569: gtest os.dll_address_to_function_and_library_name_vm fails

### PR DESCRIPTION
**Pull request by tstuefe**
May I have reviews please for this small and trivial change.

With JDK-8258606 (https://bugs.openjdk.java.net/browse/JDK-8258606), I added a new function to print a function pointer, as well as gtests. Turns out the gtests are too fragile, e.g. depend on the existence of the demangle library on AIX - so I remove some parts of them. 

Thanks, Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259569](https://bugs.openjdk.java.net/browse/JDK-8259569): gtest os.dll_address_to_function_and_library_name_vm fails

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2044/head:pull/2044`
`$ git checkout pull/2044`

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
Is your repo out of date? I don't see a reversal of the change that
I integrated yesterday to disable the subtest:

JDK-8259586 ProblemList dll_address_to_function_and_library_name
https://bugs.openjdk.java.net/browse/JDK-8259586

**Comment by tstuefe** [comment]
> Is your repo out of date? I don't see a reversal of the change that
> I integrated yesterday to disable the subtest:
> 
> JDK-8259586 ProblemList dll_address_to_function_and_library_name
> https://bugs.openjdk.java.net/browse/JDK-8259586

Hi Dan, yes, I missed that. I re-enabled the test.

Thanks, Thomas

**Comment by tstuefe** [comment]
Ping. May I please have reviews, this patch is trivial. 

Thanks!

**Review by dcubed-ojdk — APPROVED** [review]
The changes look simple enough.

I've kicked off a Mach5 Tier1 to make sure we don't have any Tier1 failures.

**Review by dcubed-ojdk — CHANGES_REQUESTED** [review]
Waiting for Mach5 Tier1 results before approving. Sorry for the confusion.

**Review by dcubed-ojdk — APPROVED** [review]
Tested with a Mach5 Tier1 job set.
No failures.
gtest/GTestWrapper.java ran in 8 different configs.

Verified that the os.dll_address_to_function_and_library_name_vm subtest passed on macOSX config:

[ RUN ] os.dll_address_to_function_and_library_name_vm
[ OK ] os.dll_address_to_function_and_library_name_vm (22 ms)

**Comment by dcubed-ojdk** [comment]
And I concur that this is a trivial change.

**Comment by tstuefe** [comment]
Thank you Dan!

/integrate

**Pull request closed without merging**
