### PR TITLE
8276301: G1: Refine implementation of G1CardSetFreePool::memory_sizes()

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Implementation of G1CardSetFreePool::memory_sizes() is not straight, this is to refine the implementation.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276301](https://bugs.openjdk.java.net/browse/JDK-8276301): G1: Refine implementation of G1CardSetFreePool::memory_sizes()

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6225/head:pull/6225` \
`$ git checkout pull/6225`

Update a local copy of the PR: \
`$ git checkout pull/6225` \
`$ git pull https://git.openjdk.java.net/jdk pull/6225/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6225`

View PR using the GUI difftool: \
`$ git pr show -t 6225`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6225.diff">https://git.openjdk.java.net/jdk/pull/6225.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by Hamlin-Li** [comment]
Is someone else available to have a look on this change? Thanks

**Review by albertnetymk — APPROVED** [review]
Nice cleanup.

**Comment by Hamlin-Li** [comment]
Thanks @tschatzl @albertnetymk for your reviews.

/integrate

**Pull request closed without merging**
