### PR TITLE
8325201: (zipfs) Disable TestPosix.setPermissionsShouldConvertToUnix which fails on Windows

### PR DESCRIPTION
**Pull request by eirbjo**
Can I please get a review for this trivial change to disable the test `TestPosix.setPermissionsShouldConvertToUnix` on Windows?

This test was recently introduced in [JDK-8324635](https://bugs.openjdk.org/browse/JDK-8324635), but fails intermittently on Windows CI runs. (See [JDK-8325199](https://bugs.openjdk.org/browse/JDK-8325199))

To reduce CI noise, I suggest we simply disable this test on Windows for now.  The actual fix of the failing test will be investigated and fixed as a follow-up PR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325201](https://bugs.openjdk.org/browse/JDK-8325201): (zipfs) Disable TestPosix.setPermissionsShouldConvertToUnix which fails on Windows (**Bug** - P4)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17700/head:pull/17700` \
`$ git checkout pull/17700`

Update a local copy of the PR: \
`$ git checkout pull/17700` \
`$ git pull https://git.openjdk.org/jdk.git pull/17700/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17700`

View PR using the GUI difftool: \
`$ git pr show -t 17700`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17700.diff">https://git.openjdk.org/jdk/pull/17700.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17700#issuecomment-1925823432)

### CODE REVIEW

**Review by LanceAndersen — COMMENTED** [review]
Hi Eirik,

I think disabling the tests makes sense for now or perhaps just  disable for windows.

I think we should use a separate PR to disable the test and keep this bug open

**Comment by eirbjo** [comment]
> I think we should use a separate PR to disable the test and keep this bug open

Lance,

I did create a separate issue for this PR to disable the test. We can keep the other bug open, yes. Or did I misunderstand something here..?

I’m not sure how to disable this test specially for Windows.

**Comment by LanceAndersen** [comment]
> > I think we should use a separate PR to disable the test and keep this bug open
> 
> Lance,
> 
> I did create a separate issue for this PR to disable the test. We can keep the other bug open, yes. Or did I misunderstand something here..?

Hi Eirik,

Apologies for not being clearer

Sorry I missed that, thank you :-)
> 
> I’m not sure how to disable this test specially for Windows.

You could:
` private static final boolean isWindows = System.getProperty("os.name") .startsWith("Windows");
`
and in the test:

```
if(isWindows) {
   return;  
}
```

You could also use the jtreg SkippedException

```
import jtreg.SkippedException;

if(isWindows) {
   throw new SkippedException("Running on windows, temporarily by-passing running this test");  
}
```

See the [JTREG FAQ](https://openjdk.org/jtreg/faq.html) 4.34

**Comment by eirbjo** [comment]
Thanks Lance, I've pushed a commit which skips the test selectively on Windows. Since this test runs with a security manager, I needed to add a property read permission for `os.name`.

**Review by LanceAndersen — APPROVED** [review]
Thank you for the update Eirik,  That looks good.  I would also link this bug to the open bug in JBS when you have a moment,

**Comment by eirbjo** [comment]
> I would also link this bug to the open bug in JBS when you have a moment

This bug, [8325201](https://bugs.openjdk.org/browse/JDK-8325201) already has a "related to" link to the open test failure bug [JDK-8325199](https://bugs.openjdk.org/browse/JDK-8325199).

Does that look OK to you, or did you mean something else?

**Comment by LanceAndersen** [comment]
> > I would also link this bug to the open bug in JBS when you have a moment
> 
> This bug, [8325201](https://bugs.openjdk.org/browse/JDK-8325201) already has a "related to" link to the open test failure bug [JDK-8325199](https://bugs.openjdk.org/browse/JDK-8325199).
> 
> Does that look OK to you, or did you mean something else?

It looks fine, I checked before I submitted the approval so must have been a timing issue.  Thank you for the above

**Pull request closed without merging**
