### PR TITLE
8261106: Reduce inclusion of jniHandles.hpp

### PR DESCRIPTION
**Pull request by iklam**
niHandles.hpp is included by about 800 out of 1000 HotSpot .o files. Most of these are transitively included from these header files, which don't actually need to include jniHandles.hpp.

- ci/ciBaseObject.hpp
- ci/ciMetadata.hpp
- ci/ciObject.hpp
- classfile/moduleEntry.hpp
- gc/shared/gcVMOperations.hpp
- jvmci/jvmciJavaClasses.hpp
- runtime/thread.hpp
- services/threadService.hpp

Fixing these headers reduces the number of .o files that include jniHandles.hpp to 145.

Note: 43 files were changed in this PR. Most of them were using jniHandles.hpp but were not including it directly.

Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5. Also locally: aarch64, arm, ppc64, s390, x86, and zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261106](https://bugs.openjdk.java.net/browse/JDK-8261106): Reduce inclusion of jniHandles.hpp

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to e7f2d097e5ba3a3cc39653825dbfcf0c315c4c69
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to e7f2d097e5ba3a3cc39653825dbfcf0c315c4c69

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2393/head:pull/2393`
`$ git checkout pull/2393`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Ok!  Seems trivial since I assume you've built this everywhere.

**Review by hseigel — APPROVED** [review]
LGTM!
Harold

**Comment by iklam** [comment]
Thanks @coleenp and @hseigel for the review.
/integrate

**Pull request closed without merging**
