### PR TITLE
8315273: (fs) Path.toRealPath(LinkOption.NOFOLLOW_LINKS) fails when "../../" follows a link (win)

### PR DESCRIPTION
**Pull request by bplb**
Windows implementation of integrated pull request #15397. The test java/nio/file/Path/ToRealPath.java is also removed from the problem list.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315273](https://bugs.openjdk.org/browse/JDK-8315273): (fs) Path.toRealPath(LinkOption.NOFOLLOW_LINKS) fails when "../../" follows a link (win) (**Bug** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15525/head:pull/15525` \
`$ git checkout pull/15525`

Update a local copy of the PR: \
`$ git checkout pull/15525` \
`$ git pull https://git.openjdk.org/jdk.git pull/15525/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15525`

View PR using the GUI difftool: \
`$ git pr show -t 15525`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15525.diff">https://git.openjdk.org/jdk/pull/15525.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15525#issuecomment-1701883079)

### CODE REVIEW

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
continue;

**Comment by bplb** [comment]
Consider this case:
```
CWD = C:\Users\bpb\dev\bugs:

1. Create these directories, file, and link in the CWD:

file
dir\subdir
link -> dir\subdir
path = link\..\..\file

2. Invoke path.toRealPath:
2.1 mainline results

follow links     C:\Users\bpb\dev\file
no follow links  C:\Users\bpb\dev\file

2.2 PR results

follow links      C:\Users\bpb\dev\bugs\file
no follow links   C:\Users\bpb\dev\bugs\link\..\..\file
```
The results of the current mainline are incorrect as they locate a non-existent file. The results of the PR version both correctly locate the file.

**Comment by djelinski** [comment]
Well let me show you a counterexample:
Setup:
```
C:\>mkdir tmp\cwd\dir\subdir

C:\>cd tmp\cwd

C:\tmp\cwd>mklink /d link dir\subdir
symbolic link created for link <<===>> dir\subdir

C:\tmp\cwd>jshell.exe
```
Before your changes:
```
jshell> Path.of("link/../../file")
$1 ==> link\..\..\file

jshell> Files.createFile($1)
$2 ==> link\..\..\file

jshell> Files.exists($1)
$3 ==> true

jshell> Files.exists($1.toRealPath())
$4 ==> true
```
After your changes:
```
jshell> Path.of("link/../../file")
$1 ==> link\..\..\file

jshell> Files.createFile($1)
$2 ==> link\..\..\file

jshell> Files.exists($1)
$3 ==> true

jshell> Files.exists($1.toRealPath())
|  Exception java.nio.file.NoSuchFileException: C:\tmp\cwd\file
|        at WindowsException.translateToIOException (WindowsException.java:85)
|        at WindowsException.rethrowAsIOException (WindowsException.java:103)
|        at WindowsException.rethrowAsIOException (WindowsException.java:108)
|        at WindowsLinkSupport.collapseDots (WindowsLinkSupport.java:238)
|        at WindowsLinkSupport.getRealPath (WindowsLinkSupport.java:285)
|        at WindowsPath.toRealPath (WindowsPath.java:944)
|        at WindowsPath.toRealPath (WindowsPath.java:42)
|        at (#4:1)
```
`path` and `path.toRealPath()` are supposed to point to the same file, but as you can see, this does not happen here.

I guess you could adjust all the methods in `Files` class to be consistent with the new `toRealPath` implementation, but this would break consistency with other Windows apps, see for example:
```
C:\tmp\cwd>type file
The system cannot find the file specified.

C:\tmp\cwd>type link\..\..\file

C:\tmp\cwd>
```
Based on the above, I think the current `toRealPath` implementation on Windows is doing just fine, only the `ToRealPath` test needs to be fixed.

As far as I could tell, `Path.toRealPath` does not make any promises about what the resulting path should be. The only requirement is that the path should refer to the same file, so the current implementation does not violate the spec.

**Comment by bplb** [comment]
This does not address your example above with respect to `toRealPath`, but the behavior it shows seems inconsistent. 

The setup is the same:

`/tmp/cwd/dir/subdir` or `C:\tmp\cwd\dir\subdir` where `link` is a symbolic link in `cwd` with the relatve target `dir/subdir`.

Then running jshell in `cwd`, the call

`Files.createFile(Path.of("link/../../file")`

creates `/tmp/cwd/file` on macOS whereas on Windows it creates `C:\tmp\file`.

**Comment by bplb** [comment]
> Based on the above, I think the current `toRealPath` implementation on Windows is doing just fine, only the `ToRealPath` test needs to be fixed.

Based on these comments in [WindowsPath](https://github.com/openjdk/jdk/blob/81ff91ef27a6a856ae2c453a9a9b8333b91da3ab/src/java.base/windows/classes/sun/nio/fs/WindowsPath.java#L202)
```
        // Long paths need to have "." and ".." removed and be prefixed with
        // "\\?\". Note that it is okay to remove ".." even when it follows
        // a link - for example, it is okay for foo/link/../bar to be changed
        // to foo/bar. The reason is that Win32 APIs to access foo/link/../bar
        // will access foo/bar anyway (which differs to Unix systems)
```
it seems safe to say that the current `toRealPath()` implementation is, as you say, all right as is. If these comments are correct, then it appears that on Unix the `link` in `foo/link/../bar` would first be resolved and then the `..` would be removed along with the element preceding it, but on Windows, `link` is just treated as a name element without resolution and is summarily removed along with `..`. This is consistent with the `Files.createFile(Path.of("link/../../file"))` example I posted above.

**Comment by bplb** [comment]
> [...] only the `ToRealPath` test needs to be fixed.
> 
> As far as I could tell, `Path.toRealPath` does not make any promises about what the resulting path should be. The only requirement is that the path should refer to the same file, so the current implementation does not violate the spec.

At this point, I tend to agree.

**Review by djelinski — APPROVED** [review]

**Comment by bplb** [comment]
In `C:\Users\bpb\dev\bugs`, create `dir`, `dir\subdir`, and `link -> dir\subdir`. Then running a simple native test using `CreateFileW` to create a new file `C:\Users\bpb\dev\bugs\link\..\file.txt` actually creates `C:\Users\bpb\dev\bugs\file.txt`, which corroborates the conclusion of this PR. The initial version of this PR incorrectly expected that `file.txt` would be `C:\Users\bpb\dev\bugs\dir\file.txt`.

**Pull request closed without merging**
