### PR TITLE
8244706: GZIP "OS" header flag hard-coded to 0 instead of 255 (RFC 1952 non-compliance)

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review and a sponsor for this patch which fixes the issue reported in https://bugs.openjdk.java.net/browse/JDK-8244706?

The commit here sets the `OS` header flag to `255` (which represents `unknown`) as noted in [1]. A new test has been included in this commit to verify the change. Furthermore, this doesn't impact the `java.util.zip.GZIPInputStream` since it ignores [2] this header value while reading the headers from the stream.

[1] https://tools.ietf.org/html/rfc1952#page-7
[2] https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/GZIPInputStream.java#L173

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8244706](https://bugs.openjdk.java.net/browse/JDK-8244706): GZIP "OS" header flag hard-coded to 0 instead of 255 (RFC 1952 non-compliance)

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Brent Christian](https://openjdk.java.net/census#bchristi) (@bchristi-git - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/130/head:pull/130`
`$ git checkout pull/130`

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]
Hi Jaikiran,

The change seems fine an inline with the RFC.  I can sponsor this once we have another review.

I have run the JCK tests for Zip/Gzip/Jar and Mach5 JDK tier1, tier2 and tier3

**Comment by jaikiran** [comment]
Thank you Lance for the review and running the tests. I'll wait for another review before initiating the integrate command.

**Comment by jaikiran** [comment]
I received some useful suggestions, offline, from Lance and Brent on this change and have updated this PR to include those suggestions. Please ignore the intermediate commits though (I accidentally added an unwanted file to this PR, which I have then removed in a subsequent commit). This is ready for a review now.

**Review by bchristi-git — COMMENTED** [review]
Reviewed.  Thanks for reworking the change into the existing out.write() call.

**Review by bchristi-git — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]
Thank you for making the changes that Brent and I suggested.  This looks good.  I have submitted, a [CSR](https://bugs.openjdk.java.net/browse/JDK-8253142) to track the change.

I have also created a [Release Note](https://bugs.openjdk.java.net/browse/JDK-8253185) as well.

Once the CSR has been approved, I will sponsor your change

**Comment by jaikiran** [comment]
Thank you Lance for taking care of the CSR and the release notes. Given that the CSR has been approved, I'm initating the integrate command.

/integrate

**Pull request closed without merging**
