### PR TITLE
8341619: C2: remove unused StoreCM node

### PR DESCRIPTION
**Pull request by robcasloz**
This cleanup removes C2's `StoreCM` (store card mark) node and all its special handling code. This node used to model card mark stores in early-expanded G1 post-barriers, and is no longer needed after [JEP 475](https://openjdk.org/jeps/475).

__Testing:__ tier1-5 (linux-x64, linux-aarch64, windows-x64, macosx-x64, and macosx-aarch64; release and debug mode).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341619](https://bugs.openjdk.org/browse/JDK-8341619): C2: remove unused StoreCM node (**Enhancement** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21385/head:pull/21385` \
`$ git checkout pull/21385`

Update a local copy of the PR: \
`$ git checkout pull/21385` \
`$ git pull https://git.openjdk.org/jdk.git pull/21385/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21385`

View PR using the GUI difftool: \
`$ git pr show -t 21385`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21385.diff">https://git.openjdk.org/jdk/pull/21385.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21385#issuecomment-2399011356)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by robcasloz** [comment]
> Looks good!

Thanks, Christian!

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by robcasloz** [comment]
> Looks good to me too.

Thanks, Tobias!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks, Vladimir!

**Pull request closed without merging**
