### PR TITLE
8272137: Make Collection and Optional classes streamable

### PR DESCRIPTION
**Pull request by CC007**
create Streamable and ParallelStreamable interface and use them in Collection and Optional

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Integration blocker
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8272137](https://bugs.openjdk.java.net/browse/JDK-8272137)

### Issue
 * [JDK-8272137](https://bugs.openjdk.java.net/browse/JDK-8272137): Make Iterable classes streamable ⚠️ Title mismatch between PR and JBS.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5050/head:pull/5050` \
`$ git checkout pull/5050`

Update a local copy of the PR: \
`$ git checkout pull/5050` \
`$ git pull https://git.openjdk.java.net/jdk pull/5050/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5050`

View PR using the GUI difftool: \
`$ git pr show -t 5050`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5050.diff">https://git.openjdk.java.net/jdk/pull/5050.diff</a>

</details>

### CODE REVIEW

**Comment by CC007** [comment]
Something seemed to have gone wrong with the jcheck

**Comment by CC007** [comment]
I couldn't think of any, but if there are more places where these interfaces could be used, please tell me, so I can add them.

**Comment by liach** [comment]
Aren't all iterable implementations effectively streamable if they properly implement `spliterator`? And the spliterator implementation can always be sequential or parallel, dependent on how you feed it into `StreamSupport`.

**Comment by forax** [comment]
Hi Rick,
I do not think that such interfaces are a good addition to the JDK,
we do not want to promote the fact that you can create a Stream from an Iterable because the resulting Stream is not efficient (or is not as efficient as it could be) and we can already uses a Supplier<Stream> if we want to to represent a factory of streams

**Comment by CC007** [comment]
The name of this pull request is a bit wrong, but it had to be the same as the JBS name. 

The interfaces don't make the Iterable have stream and parallelStream methods, but are two separate interfaces to denote that an object can be streamed. These interfaces are fully decoupled from the Iterable interface and it is merely suggested that these can be used together in cases that an object is both Iterable and Streamable. No implementation is implied and has to be provided by the object or its superclasses or other interfaces (like collection).

**Comment by CC007** [comment]
> Aren't all iterable implementations effectively streamable if they properly implement `spliterator`? And the spliterator implementation can always be sequential or parallel, dependent on how you feed it into `StreamSupport`.

Yes indeed, but to add extra methods to the Iterable interface itself could have compatibility or possible security issues depending on whether these methods are abstract or not resp.

Therefore I made it a fully separate interface here and used it in places with known implementations (Collection and Optional) so that there's no changes in the exposed API of the other classes. The only difference is that you can now make use of the fact that these interfaces extend Streamable and/or ParallelStreamable

**Review by briangoetz — CHANGES_REQUESTED** [review]
I object to this change.  These issues were explored in the JSR 335 EG and it was agreed that this abstraction did not carry its weight.  In any case, it is premature to bring a PR for a significant API change that has not been discussed first on corelibs-dev.  Please withdraw the PR, and if you want to continue the discussion, bring it to corelibs-dev.

**Comment by CC007** [comment]
> I object to this change. These issues were explored in the JSR 335 EG and it was agreed that this abstraction did not carry its weight. In any case, it is premature to bring a PR for a significant API change that has not been discussed first on corelibs-dev. Please withdraw the PR, and if you want to continue the discussion, bring it to corelibs-dev.

I agree with the spliterator performance issues and the ability to be able to create IntStreams from Iterable<Integer>. Therefore option 1 and 2 from JDK-8272137 seem fairly unfeasible to implement. This was already hinted at there, but for different reasons. 

This PR however implements option 4: an option that doesn't actually make the Iterable class have a stream method, but instead abstracts the stream method to an interface. This method is then implemented by Collection and Optional. It also allows other code to implement this interface.

Using this implementation, you don't have the issues that the JSR 335 EG specified that would be present if Iterable itself were to be made Streamable. You wouldn't want that anyway, because streamability and iterability are two similar but very separate concerns in Java.

**Comment by CC007** [comment]
Changed the title, since it seemed to cause confusion.

**Comment by briangoetz** [comment]
I understand what you are proposing. I do not believe Streamable carries its weight.

**Comment by CC007** [comment]
> I understand what you are proposing. I do not believe Streamable carries its weight.

That argument seems subjective. Could you elaborate on that in an objective manner?

**Comment by briangoetz** [comment]
To reiterate: These issues were explored in the JSR 335 EG and it was agreed that this abstraction did not carry its weight. In any case, it is premature to bring a PR for a significant API change that has not been discussed first on corelibs-dev. Please withdraw the PR, and if you want to continue the discussion, bring it to corelibs-dev.

**Comment by CC007** [comment]
I read through [these posts](http://mail.openjdk.java.net/pipermail/lambda-libs-spec-experts/2013-June/thread.html#1910) and while I did see good reasons for not moving stream to Iterable, I didn't see any mention of a separate Streamable-like interface, so could you elaborate on that it "did not carry its weight"?

**Comment by amaembo** [comment]
Mostly agreed with Brian. Judging from 7 years of using Stream API, I can say that this abstraction would not solve any real problem. If you need a way to create many identical streams on demand, just accept `Supplier<Stream<T>>`. This allows more flexibility for clients. They can not only supply `myCollection::stream` or `myOptional::stream` but also `() -> Arrays.stream(myArray)`, `() -> IntStream.range(...).boxed()`, `() -> myCollection.stream().filter(something)` or whatever else. A dedicated `Streamable` interface is too limited and will require adapters in many cases but you can already adapt anything to `Supplier<Stream<T>>`. People already use `Supplier<Stream<T>>` idiom pretty often, so creating a new `Streamable` interface would add an API mess: some people would stick with `Supplier` and others would migrate to `Streamable`. So I vote to reject this PR.

I said "mostly" because I think that PR is a good starting point for discussion. It's much easier to explain which enhancement you are proposing if you already present some code. And we are already at corelibs-dev, as PR comments are mirrored there, and for some people, it's more comfortable to discuss via GitHub interface, as you don't have to subscribe and get tons of unrelated e-mails, you can concentrate on a single discussion only. So in my opinion, it's completely ok to write code and create a PR before the discussion, even if it's likely to be thrown away.

**Comment by kevinrushforth** [comment]
@CC007 Please follow the course of action that @briangoetz has requested. This needs to be discussed on the appropriate mailing list (core-libs-dev in this case) prior to submitting a pull request. It is premature to review this PR.

I invite you to refer to the [OpenJDK Developers' Guide](https://openjdk.java.net/guide/), specifically the [Socialize your change](https://openjdk.java.net/guide/#socialize-your-change) section.

**Comment by PaulSandoz** [comment]
> To reiterate: These issues were explored in the JSR 335 EG and it was agreed that this abstraction did not carry its weight. 

Yes, we explored this when the Stream API was being designed. It's hard, if not impossible, to capture all decisions for posterity. In the passing years I don't think anything significantly new has arisen for us to revisit that decision.

**Comment by CC007** [comment]
It is fine that the pull request is closed for now, but I agree with @amaembo that if this conversation is indeed mirrored there, then it shouldn't be a problem to discuss the proposal here, along with the proposed changes.

I actually worked out a usecase (See: https://github.com/CC007/InterfaceSegregationDemo), where I partially reimagined the Collection interface stack and its neighboring interfaces/classes. I also added a `Demo` class to show how I imagined to use these interfaces and to show how the granularity of these interfaces can be useful.

The fact that I have to create copies of interfaces and delegates for implementations makes me feel like something is lacking in the collection stack and that for this usecase `Supplier<E>` wouldn't cut it, but feel free to fork and refactor my code to prove me wrong.

PS: while creating the Demo class, I noticed that it couldn't be analyzed if the return value of a method with type `<T extends Streamable<String> & Addable<String> & Iterable<String> & RandomAccess>` could be safely cast to a new local variable with type `<SA extends Streamable<String> & Addable<String>` and that you can't declare variables of type `<? extends Streamable<String> & Addable<String>` (it won't let you use the `&` when using the `?`), but I digress.

**Comment by CC007** [comment]
Also, sorry for my Millennial lack of knowledge of older communication methods, but if I wanted to reply to a specific thread in a mailing list, how would I do that? Does it require certain content in the subject and/or quoted text in the message body?

It does feel way less intuitive than just clicking the comment box or clicking `... -> Quote reply` on a comment in this PR

**Comment by liach** [comment]
You can view the mailing lists at https://mail.openjdk.java.net/mailman/listinfo and subscribe there.
If you want to send a mail, just send one to say `jdk-dev` at `openjdk.java.net` (and carbon copy if you reply to a specific person so the list can see a copy)

----------------

On a separate note, @CC007 your model falls back to the fairly-old inheritance vs embodiment (extending a class vs using it as a field) debate. Nowadays, I think Java has evolved to reduce excessive reliances on inheritances, as there can be clashes (for example, a class cannot implement a comparator for two different type arguments). Also due to these potential of clashing, in a lot of java code, interface implementation classes avoid implementing multiple interfaces at once.

**Comment by CC007** [comment]
The List and Collection interface was almost directly taken from java.util (apart from the small feature interfaces, that I extracted from them), so it would make sense that those classes use an older design.

Are you suggesting that there are deeper architectural issues with the hierarchy-heavy collection stack? Would it be better if a list contained a collection, rather than inheriting from it? If that is the case, anything that is proposed in this PR is merely aiming at symptoms of a possibility much larger underlying problem, which might require going back to the drawing board for all collection related features.

**Comment by liach** [comment]
With modern java, you can always create a `Streamable` on your own (and have specifications/documentations that a simple `Supplier` lacks) and implement it like:
```java
public interface Streamable<T> {
  Stream<T> stream();
  static Streamable<T> ofIterable(Iterable<T> iterable) {
    return () -> StreamSupport.stream(iterable.spliterator(), false);
  }
}
```
The lack of such an interface in the JDK is not really a problem.

> Are you suggesting that there are deeper architectural issues with the hierarchy-heavy collection stack?

I am saying that your sample project has unnecessarily many interfaces for your collection model, where many of them have little virtue on their own. This interface mash is susceptible to accidentally introducing unwanted features into the hierarchy and having method or specification clashes for implementation.

Looking back on identifying efficiently streamable objects, people can usually find efficient streams by the method return types. Your interface doesn't allow people to identify `BufferedReader.lines()` as an efficiently streamable target, for instance.
In addition, I think the main purpose of `Optional.stream()` is to allow using it in stream flatmapping than to promote stream creation with optionals.

**Comment by CC007** [comment]
Ah ok, I see your point. In the case that you want to have something be only `Streamable`, you can create an interface like this (fixed missing method type param and added `ofCollection`:
```
public interface Streamable<T> {
    
    Stream<T> stream();

    static <T> Streamable<T> ofIterable(Iterable<T> iterable) {
        return () -> StreamSupport.stream(iterable.spliterator(), false);
    }

    static <T> Streamable<T> ofCollection(Collection<T> collection) {
        return collection::stream;
    }
}
```
This will indeed allow you to only expose the `stream()` method, even to the degree that you can't even expose the other methods with type casting, which is a nice side effect. You could also add a static method for `ofOptional`, if required, but you made a good point about `Optional.stream`'s general use case (though it could still be used as a stream when needed).

At first I didn't fully understand how that would resolve the issue for whenever you need something that is both `Iterable` and `Streamable`, but after rereading your comment I came up with the following interface: 

```
/**
 * This is an interface that specifies that its content can be traversed and acted upon,
 * either through iteration or using streams
 */
public interface Traversable<T> extends Streamable<T>, Iterable<T> {

    static <T> Traversable<T> ofIterable(Iterable<T> iterable) {
        return new Traversable<T>() {
            @Override
            public Stream<T> stream() {
                return StreamSupport.stream(iterable.spliterator(), false);
            }

            @Override
            public Iterator<T> iterator() {
                return iterable.iterator();
            }
        };
    }

    static <T> Traversable<T> ofStreamable(Streamable<T> streamable) {
        return new Traversable<T>() {
            @Override
            public Stream<T> stream() {
                return streamable.stream();
            }

            @Override
            public Iterator<T> iterator() {
                return streamable.stream().iterator();
            }
        };
    }

    static <T> Traversable<T> ofCollection(Collection<T> collection) {
        return new Traversable<T>() {
            @Override
            public Stream<T> stream() {
                return collection.stream();
            }

            @Override
            public Iterator<T> iterator() {
                return collection.iterator();
            }
        };
    }
}
```

For anyone who's doubtful about the arguments against this change, you can find this code in use in demo2 in my demo repo: https://github.com/CC007/InterfaceSegregationDemo/tree/master/src/main/java/com/github/cc007/interfacesegregationdemo/demo2

**Comment by CC007** [comment]
I believe that the accompanying JBS issue (JDK-8272137) can be closed. Maybe a mention of how the discussion in this PR was resolved (with code examples) could be added there before closing it.

**Comment by CC007** [comment]
> _Mailing list message from [Alan Snyder](mailto:javalists@cbfiddle.com) on [core-libs-dev](mailto:core-libs-dev@mail.openjdk.java.net):_
> 
> Ah, if only one could define a type alias Streamable<T> = Supplier<Stream<T>>...

If you use that, you'd lose some semantics that the method name would have given you. I feel that @liach 's solution is cleaner, since that preserves this method name.

**Pull request closed without merging**
