### PR TITLE
8286967: Unproblemlist compiler/c2/irTests/TestSkeletonPredicates.java and add additional test for JDK-8286638

### PR DESCRIPTION
**Pull request by chhagedorn**
[JDK-8286361](https://bugs.openjdk.java.net/browse/JDK-8286361) could be traced back to the same underlying problem as in [JDK-8286638](https://bugs.openjdk.java.net/browse/JDK-8286638). Pulling in the change fixed the problem.

This patch unproblemlists the previously failing test and adds a new test for JDK-8286638 (extracted from compiler/c2/irTests/TestSkeletonPredicates.java) that I've used for analyzing JDK-8286361.

Testing with latest JDK:
- hs-tier1-4 flags for the new test
- hs-tier7+8 flags for compiler/c2/irTests/TestSkeletonPredicates.java

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286967](https://bugs.openjdk.org/browse/JDK-8286967): Unproblemlist compiler/c2/irTests/TestSkeletonPredicates.java and add additional test for JDK-8286638

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8806/head:pull/8806` \
`$ git checkout pull/8806`

Update a local copy of the PR: \
`$ git checkout pull/8806` \
`$ git pull https://git.openjdk.java.net/jdk pull/8806/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8806`

View PR using the GUI difftool: \
`$ git pr show -t 8806`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8806.diff">https://git.openjdk.java.net/jdk/pull/8806.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Okay.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by chhagedorn** [comment]
Thanks Vladimir and Tobias for your reviews!

**Pull request closed without merging**
