### PR TITLE
8286331: jni_GetStringUTFChars() uses wrong heap allocator

### PR DESCRIPTION
**Pull request by zhengyu123**
jni_GetStringUTFChars()  calls `AllocateHeap(length + 1, mtInternal, 0, AllocFailStrategy::RETURN_NULL);` to allocate memory, where it passes `0` as `NativeCallStack` reference, that results construction of `NativeCallStack`.

In `NativeCallStack`'s constructor, it performs stack walk to capture native call stack. This is unnecessary, if NMT detail tracking is not enabled.

It should use `char* AllocateHeap(size_t size,
                   MEMFLAGS flags,
                   AllocFailType alloc_failmode /* = AllocFailStrategy::EXIT_OOM*/)` heap allocator instead.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286331](https://bugs.openjdk.java.net/browse/JDK-8286331): jni_GetStringUTFChars() uses wrong heap allocator

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [df1b8c33](https://git.openjdk.java.net/jdk/pull/8579/files/df1b8c33e6fe7111dadffa2017887bc8fe67f341)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8579/head:pull/8579` \
`$ git checkout pull/8579`

Update a local copy of the PR: \
`$ git checkout pull/8579` \
`$ git pull https://git.openjdk.java.net/jdk pull/8579/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8579`

View PR using the GUI difftool: \
`$ git pr show -t 8579`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8579.diff">https://git.openjdk.java.net/jdk/pull/8579.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — CHANGES_REQUESTED** [review]
The changes looks correct, but I don't think it will give the desired behavior.  It looks like there is a bug in the 3-parameter version of AllocateHeap where it ignores the alloc_failmode argument.  You will need to fix that too for your change to work correctly.  Try forcing at allocation failure and verify that it returns NULL instead of exiting with OOM.

**Comment by zhengyu123** [comment]
> 

You are right, filed [JDK-8286346](https://bugs.openjdk.java.net/browse/JDK-8286346).

**Comment by tstuefe** [comment]
So, we accidentally call `NativeCallStack(int toSkip);` ? If yes, and we don't like that, should we declare that constructor as explicit?

**Review by tstuefe — APPROVED** [review]
Change looks good.

**Comment by zhengyu123** [comment]
> So, we accidentally call `NativeCallStack(int toSkip);` ? If yes, and we don't like that, should we declare that constructor as explicit?

Good point, fixed.

Thanks

**Comment by zhengyu123** [comment]
> > 
> 
> You are right, filed [JDK-8286346](https://bugs.openjdk.java.net/browse/JDK-8286346).

@dean-long JDK-8286346 has been integrated.

**Review by dean-long — APPROVED** [review]

**Pull request closed without merging**
