### PR TITLE
8281803: AArch64: Optimize masked vector NOT/AND_NOT for SVE

### PR DESCRIPTION
**Pull request by XiaohongGong**
Currently the vector lanewise `NOT` is implemented with `"v.xor(-1)"` and `AND_NOT ` is implemented with `"v1.and(v2.xor(-1))"`. With SVE they can be respectively implemented with `"not/bic"` instructions, and we have already optimized the non-masked operations before (see [1]).

Consider the SVE also supports the `predicated` `"not/bic"`, we can apply the same optimizations for the masked `NOT/AND_NOT` by adding match rules. So this patch adds the rules for the following optimizations:

For `NOT `with int type:
```
  mov z16.s, #-1
  eor z18.s, p0/m, z18.s, z16.s  ==>  not z18.s, p0/m, z18.s
```
For `AND_NOT `with int type:
```
  not z16.d, p7/m, z16.d
  and z17.s, p0/m, z17.s, z16.s  ==>  bic z17.s, p0/m, z16.s
```
Here is the performance gain for the `"NOT/AND_NOT"` benchmarks (see [2][3] for byte type) with SVE 512-bit:
```
Benchmark                    Gain
LongMaxVector.NOTMasked      1.005
ShortMaxVector.NOTMasked     1.017
IntMaxVector.NOTMasked       1.022
ByteMaxVector.NOTMasked      1.023
LongMaxVector.AND_NOTMasked  1.063
IntMaxVector.AND_NOTMasked   1.047
ShortMaxVector.AND_NOTMasked 1.059
ByteMaxVector.AND_NOTMasked  1.030
```
[1] https://github.com/openjdk/jdk/pull/3370
[2] https://github.com/openjdk/panama-vector/blob/vectorIntrinsics/test/micro/org/openjdk/bench/jdk/incubator/vector/operation/ByteMaxVector.java#L1963
[3] https://github.com/openjdk/panama-vector/blob/vectorIntrinsics/test/micro/org/openjdk/bench/jdk/incubator/vector/operation/ByteMaxVector.java#L362

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281803](https://bugs.openjdk.java.net/browse/JDK-8281803): AArch64: Optimize masked vector NOT/AND_NOT for SVE

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to 5475d8f81d1d62a696971a3b31daeb7d8a061738
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7486/head:pull/7486` \
`$ git checkout pull/7486`

Update a local copy of the PR: \
`$ git checkout pull/7486` \
`$ git pull https://git.openjdk.java.net/jdk pull/7486/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7486`

View PR using the GUI difftool: \
`$ git pr show -t 7486`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7486.diff">https://git.openjdk.java.net/jdk/pull/7486.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]

**Comment by XiaohongGong** [comment]
Thanks for the review @theRealAph !

**Review by nsjian — APPROVED** [review]

**Comment by XiaohongGong** [comment]
Thanks for the review @nsjian !

**Pull request closed without merging**
