### PR TITLE
8308187: jdi/EventSet/resume/resume008 failed with "EventHandler> Unexpected event: ThreadStartEvent in thread resume008-thread0"

### PR DESCRIPTION
**Pull request by plummercj**
resume008 test is failing because of an unexpected Cleaner-1 thread being created:

` # ERROR: debugger> ERROR: ThreadStartEvent is not for expected thread: Cleaner-1 `

Threads like Cleaner-1 are suppose to be filtered out so the test doesn't see them. Cleaner-1 had been missed by the filter since it never turned up in testing before. For some reason it started turning up 3 days ago. I'm not sure why, but it doesn't really matter since it should be filtered.

Testing

- Ran test 200 times. Before fix failed 13 times in 200 runs.
- Ran  all the tier5 svc tests, which is where this issue has been turning up.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308187](https://bugs.openjdk.org/browse/JDK-8308187): jdi/EventSet/resume/resume008 failed with "EventHandler&gt; Unexpected event: ThreadStartEvent in thread resume008-thread0"

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14048/head:pull/14048` \
`$ git checkout pull/14048`

Update a local copy of the PR: \
`$ git checkout pull/14048` \
`$ git pull https://git.openjdk.org/jdk.git pull/14048/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14048`

View PR using the GUI difftool: \
`$ git pr show -t 14048`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14048.diff">https://git.openjdk.org/jdk/pull/14048.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14048#issuecomment-1553334204)

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This fix is trivial.

**Comment by dcubed-ojdk** [comment]
The code that creates the "Cleaner-N" threads is from 202.02.04 so a very
long time ago. This failure first showed up in jdk-21+23-1950-tier5 and I can't
find anything remotely obvious that could have caused these failures to start
happening.

**Comment by plummercj** [comment]
> The code that creates the "Cleaner-N" threads is from 202.02.04 so a very
long time ago. This failure first showed up in jdk-21+23-1950-tier5 and I can't
find anything remotely obvious that could have caused these failures to start
happening.

There are two different types of cleaner threads that can be created: Cleaner-<n> and Common-Cleaner. They have both been around for a long time. We'd seen the Common-Cleaner thread creation popup before during the debugger tests, but not Cleaner-<n>. Something changed, probably in the libraries, that is now triggering the creation of Cleaner-<n> when this test is run where previously it did not. But I don't think it is worth tracking down. The thread creation itself is not a bug. The bug is that it never made it into the filter list.

**Comment by plummercj** [comment]
> Thumbs up. This fix is trivial.

Thanks, Dan!

/integrate

**Comment by dcubed-ojdk** [comment]
> I don't think it is worth tracking down.
I figured I would spend a couple of minutes researching because I just hate
not having a least a guess why a failure started happening...

**Pull request closed without merging**
