### PR TITLE
8343296: IGV: Show pre/main/post at CountedLoopNodes

### PR DESCRIPTION
**Pull request by chhagedorn**
It's sometimes difficult to keep track of which counted loops are pre, main or post loops. This patch adds this property to `CountedLoops`, similarly to the other node info that we print, for example, like a method name for a `CallStaticJava`.

This is achieved by emitting a new property to `CountedLoopNodes` and then extending the node info filter in IGV. This will show the pre/main/post info like the other node info below the node name:

image

Thanks to @robcasloz for helping me with the IGV filter changes!

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343296](https://bugs.openjdk.org/browse/JDK-8343296): IGV: Show pre/main/post at CountedLoopNodes (**Enhancement** - P4)

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Contributors
 * Roberto Castañeda Lozano `<rcastanedalo@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21788/head:pull/21788` \
`$ git checkout pull/21788`

Update a local copy of the PR: \
`$ git checkout pull/21788` \
`$ git pull https://git.openjdk.org/jdk.git pull/21788/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21788`

View PR using the GUI difftool: \
`$ git pr show -t 21788`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21788.diff">https://git.openjdk.org/jdk/pull/21788.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21788#issuecomment-2447204814)

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good otherwise, thanks for doing this Christian!

**Comment by chhagedorn** [comment]
Thanks Roberto for your review!

**Review by robcasloz — APPROVED** [review]

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review!

/integrate

**Pull request closed without merging**
