### PR TITLE
8329113: Deprecate -XX:+UseNotificationThread

### PR DESCRIPTION
**Pull request by alexmenkov**
The fix deprecates -XX:+UseNotificationThread VM option

Testing: tier1-3,hs-tier5-svc

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8330281](https://bugs.openjdk.org/browse/JDK-8330281) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8329113](https://bugs.openjdk.org/browse/JDK-8329113): Deprecate -XX:+UseNotificationThread (**Enhancement** - P4)
 * [JDK-8330281](https://bugs.openjdk.org/browse/JDK-8330281): Deprecate -XX:+UseNotificationThread (**CSR**)

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to [ddacca6d](https://git.openjdk.org/jdk/pull/18852/files/ddacca6d8e5c1336ff8029d28f195ab2c284e05e)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [ddacca6d](https://git.openjdk.org/jdk/pull/18852/files/ddacca6d8e5c1336ff8029d28f195ab2c284e05e)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [ddacca6d](https://git.openjdk.org/jdk/pull/18852/files/ddacca6d8e5c1336ff8029d28f195ab2c284e05e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18852/head:pull/18852` \
`$ git checkout pull/18852`

Update a local copy of the PR: \
`$ git checkout pull/18852` \
`$ git pull https://git.openjdk.org/jdk.git pull/18852/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18852`

View PR using the GUI difftool: \
`$ git pr show -t 18852`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18852.diff">https://git.openjdk.org/jdk/pull/18852.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18852#issuecomment-2065577352)

### CODE REVIEW

**Comment by alexmenkov** [comment]
> Have you looked for any tests that are using this option?

No tests use the option

**Comment by dholmes-ora** [comment]
> > Have you looked for any tests that are using this option?
> 
> No tests use the option

Well they do but it is done via a task definition in hs-tier5-svc.js.

**Review by dholmes-ora — APPROVED** [review]
Changes look good but please ensure tier5 svc tests pass with the warning enabled

Thanks.

**Review by coleenp — APPROVED** [review]
Looks good.  Thank you for doing this.

**Pull request closed without merging**
