### PR TITLE
8176026: SA: Huge heap sizes cause a negative value to be displayed in the jhisto heap total

### PR DESCRIPTION
**Pull request by jyukutyo**
When a heap is used more than about 2.1GB, clhsdb jhisto shows a negative number in the total field.

```
$ java -Xmx20g Sample

$ jhsdb clhsdb --pid 5773
Attaching to process 5773, please wait...
hsdb> jhisto
...
299:            1       16      jdk.internal.misc.Unsafe
300:            3402    10737610256     byte[]
Total :         15823   -2146661280
Heap traversal took 1.793 seconds.
```
(Incidentally, the Sample is a program that only allocates many objects.)

#### Details
This is because in ObjectHistogram class the totalSize variable is int type.

The total size is the total of ObjectHistogramElement#getSize() and getSize() returns long. So I changed int to long in the ObjectHistogram class.

Additionally, I changed the type of the totalCount. This doesn't cause a bug, but ObjectHistogramElement#getCount() also returns long. So it doesn't need to treat it as int, I think. ObjectHistogramElement#compare() also do the same thing, so a class that is a huge size show the bottom of the list.

#### Tests
The jtreg test was successful.
```
$ sudo make run-test TEST=serviceability/sa/ClhsdbJhisto.java

$ cat build/linux-x86_64-server-fastdebug/test-results/jtreg_test_hotspot_jtreg_serviceability_sa_ClhsdbJhisto_java/text/summary.txt
serviceability/sa/ClhsdbJhisto.java  Passed. Execution successful
```

I confirmed the output with the same program.

```
$ ./jdk/build/linux-x86_64-server-fastdebug/jdk/bin/java -Xmx20g Sample
$ ./jdk/build/linux-x86_64-server-fastdebug/jdk/bin/jhsdb clhsdb --pid 10196
Attaching to process 10196, please wait...
hsdb> jhisto
Object Histogram:

num       #instances    #bytes  Class description
--------------------------------------------------------------------------
1:              3405    13958838400     byte[]
2:              887     109032  java.lang.Class
...
300:            1       16      jdk.internal.misc.Unsafe
Total :         15827   13959470288
Heap traversal took 1.72 seconds.
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8176026](https://bugs.openjdk.java.net/browse/JDK-8176026): SA: Huge heap sizes cause a negative value to be displayed in the jhisto heap total

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to 248d49fe336f8376001a42247643e709d30de453
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to a9447ca48b008efbd3799a3d92451b3d345f8bd0
 * @mgkwill (no known github.com user name / role) ⚠️ Review applies to 248d49fe336f8376001a42247643e709d30de453
 * [Yasumasa Suenaga](https://openjdk.java.net/census#ysuenaga) (@YaSuenag - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3087/head:pull/3087` \
`$ git checkout pull/3087`

Update a local copy of the PR: \
`$ git checkout pull/3087` \
`$ git pull https://git.openjdk.java.net/jdk pull/3087/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3087`

View PR using the GUI difftool: \
`$ git pr show -t 3087`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3087.diff">https://git.openjdk.java.net/jdk/pull/3087.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — COMMENTED** [review]
I see another cast-to-int related bug, and it's visible in your jhisto output (both before and after):

```
304: 1 16 jdk.internal.perf.Perf
305: 1 16 java.util.jar.JavaUtilJarAccessImpl
306: 254 2863336944 int[]
Total : 22803 -1430650672 
```

The large `int[]` array should be at the top of the list, not the bottom. The issue is in ObjectHistogramElement.java:

```
  public int compare(ObjectHistogramElement other) {
    return (int) (other.size - size);
  }
```

So this will result in the returned value having the wrong sign if the difference between `other.size` and `size` is too large.  In ObjectHistogram.java, just above the code you fixed, we have:

```
  public List<ObjectHistogramElement> getElements() {
    List<ObjectHistogramElement> list = new ArrayList<>();
    list.addAll(map.values());
    Collections.sort(list, new Comparator<>() {
      public int compare(ObjectHistogramElement o1, ObjectHistogramElement o2) {
        return o1.compare(o2);
      }
    });
    return list;
  }
```
So it looks like this is calling the buggy `compare()` method. I think the fix is to have `compare()` return -1, 0, or 1 depending on the `long` value of `(other.size - size)`, rather than just trying to return `(other.size - size)`.

**Comment by jyukutyo** [comment]
@plummercj That is right! I fixed that bug and pasted the latest output of jhisto to the body. Of course I re-ran the jtreg test.

**Review by plummercj — APPROVED** [review]
The copyright needs updating in ObjectHistogramElement.java. Otherwise the changes look good.

**Review by mgkwill — APPROVED** [review]

**Comment by jyukutyo** [comment]
I just updated the copyright.

**Comment by jyukutyo** [comment]
Could someone sponsor this pull request? It is ready.

**Review by YaSuenag — APPROVED** [review]
Looks good. I will sponsor you.

**Pull request closed without merging**
