### PR TITLE
8308819: add JDWP and JDI virtual thread support for ThreadReference.ForceEarlyReturn

### PR DESCRIPTION
**Pull request by plummercj**
Improve ThreadReference.ForceEarlyReturn to support virtual threads as long as they are suspended and mounted.

[JDK-8308400](https://bugs.openjdk.org/browse/JDK-8308400) improved JVMTI ForceEarlyReturn support for virtual threads. The spec now says it is supported if the thread is suspended at an event (not a specific event as previously spec'd), and additional support may also be provided. The implementation now just requires that the virtual thread be mounted, so this covers being suspended at an event, but also other situations in which the virtual thread is mounted.

JDWP and JDI need to line up with JVMTI. Only spec changes will be needed.

A new test was added mostly to cover the unmounted virtual thread case that results in OpaqueFrameException.

forceEarlyReturn002 test had previously been updated for virtual threads to expect OpaqueFrameException. These changes have all been undone since the test now runs the same when using virtual threads as with platform threads.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8308973](https://bugs.openjdk.org/browse/JDK-8308973) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8308819](https://bugs.openjdk.org/browse/JDK-8308819): add JDWP and JDI virtual thread support for ThreadReference.ForceEarlyReturn
 * [JDK-8308973](https://bugs.openjdk.org/browse/JDK-8308973): add JDWP and JDI virtual thread support for ThreadReference.ForceEarlyReturn (**CSR**)

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14167/head:pull/14167` \
`$ git checkout pull/14167`

Update a local copy of the PR: \
`$ git checkout pull/14167` \
`$ git pull https://git.openjdk.org/jdk.git pull/14167/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14167`

View PR using the GUI difftool: \
`$ git pr show -t 14167`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14167.diff">https://git.openjdk.org/jdk/pull/14167.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14167#issuecomment-1563764910)

### CODE REVIEW

**Review by sspitsyn — COMMENTED** [review]
This looks pretty good. Still need to review new test though.
I guess, you are going to file a CSR for this.

**Comment by plummercj** [comment]
> I guess, you are in process to file a CSR for this.

CSR is now ready for review.

**Review by sspitsyn — APPROVED** [review]
The fix looks good.
Thanks,
Serguei

**Review by AlanBateman — APPROVED** [review]

**Comment by plummercj** [comment]
Thanks for the reviews Alan and Serguei!

/integrate

**Pull request closed without merging**
