### PR TITLE
8279189: Inaccurate comment about class VMThread

### PR DESCRIPTION
**Pull request by navyxliu**
The comment is inaccurate now. VMThread is different from the primordial thread. I guess the comment is based on the old codebase.
Because VMThread is singleton, I put the Constructor and Destructor in "private" section. clients use static member functions create/destroy.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279189](https://bugs.openjdk.java.net/browse/JDK-8279189): Inaccurate comment about class VMThread

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 8c26760b6f20d5717c6b94ae8e1b444580943d6b
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6922/head:pull/6922` \
`$ git checkout pull/6922`

Update a local copy of the PR: \
`$ git checkout pull/6922` \
`$ git pull https://git.openjdk.java.net/jdk pull/6922/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6922`

View PR using the GUI difftool: \
`$ git pr show -t 6922`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6922.diff">https://git.openjdk.java.net/jdk/pull/6922.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
I don't know if that comment has ever been accurate :)

Changes look fine and trivial IMO. I think loop() could/should also be private.

Thanks,
David

**Comment by navyxliu** [comment]
Reasonable. Tuck away VMThread::loop() in the private section as well.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Pull request closed without merging**
