### PR TITLE
8295663 Rephrase introduction to testing.md

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Old one made little sense for a new reader

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295663](https://bugs.openjdk.org/browse/JDK-8295663): Rephrase introduction to testing.md

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10763/head:pull/10763` \
`$ git checkout pull/10763`

Update a local copy of the PR: \
`$ git checkout pull/10763` \
`$ git pull https://git.openjdk.org/jdk pull/10763/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10763`

View PR using the GUI difftool: \
`$ git pr show -t 10763`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10763.diff">https://git.openjdk.org/jdk/pull/10763.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
Could you tidy up the formatting of the markdown version? The line lengths are rather uneven.

**Comment by magicus** [comment]
Good point; I didn't notice. We try to keep the line length of markdown files below 79, if possible, so that they can be properly viewed on a 80-wide viewport.

Many editors have a "reflow lines" or similar function, that can help you.

**Comment by LudwikJaniuk** [comment]
Sure thing, done.

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
