### PR TITLE
8339847: Broken link to the dieharder distribution website in SplittableRandom

### PR DESCRIPTION
**Pull request by nizarbenalla**
Could I get a review for this small change?
The page linked in `SplittableRandom` was moved at some point, this change points to the correct page to avoid redirects.

TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339847](https://bugs.openjdk.org/browse/JDK-8339847): Broken link to the dieharder distribution website in SplittableRandom (**Sub-task** - P4)

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21000/head:pull/21000` \
`$ git checkout pull/21000`

Update a local copy of the PR: \
`$ git checkout pull/21000` \
`$ git pull https://git.openjdk.org/jdk.git pull/21000/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21000`

View PR using the GUI difftool: \
`$ git pr show -t 21000`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21000.diff">https://git.openjdk.org/jdk/pull/21000.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21000#issuecomment-2349181535)

### CODE REVIEW

**Review by irisclark — APPROVED** [review]
Confirmed.  New link appears to be correct.

**Comment by nizarbenalla** [comment]
I think this counts as "trivial" change and can be integrated without waiting for 24, if you agree Iris

/integrate

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
Requesting @rgiulietti to sanity check before integration.

**Comment by rgiulietti** [comment]
Looks good

**Comment by liach** [comment]
Thanks Raffaello for the confirmation.

/sponsor

**Pull request closed without merging**
