### PR TITLE
8254085: javax/swing/text/Caret/TestCaretPositionJTextPane.java failed with "RuntimeException:  Wrong caret position"

### PR DESCRIPTION
**Pull request by azuev-java**
Please review fix for the test issue. This test fails on machines with low display resolution.
Limiting of the length of the line to 30 characters prevents it from wrapping the line 
for a second time which fixes the problem. I tested solution on different modes from 1024x768 to 3840x2160.

/cc swing

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254085](https://bugs.openjdk.java.net/browse/JDK-8254085): javax/swing/text/Caret/TestCaretPositionJTextPane.java failed with "RuntimeException:  Wrong caret position"

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/716/head:pull/716`
`$ git checkout pull/716`

### CODE REVIEW

**Comment by prsadhuk** [comment]
Hi Alex, 
With this modification, it passes even without the fix for JDK-8232243

**Comment by azuev-java** [comment]
> Hi Alex,
> With this modification, it passes even without the fix for JDK-8232243

Fixed. By shifting click position left i'm avoiding clicking an empty space on low resolution displays and test passes with fix and fails without it.

**Comment by prsadhuk** [comment]
ok. But since this is mach5 issue it will be better to get a mach5 stability check through a mach5 job running several iterations on all platforms.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
