### PR TITLE
8198617: java/awt/Focus/6382144/EndlessLoopTest.java fails on mac

### PR DESCRIPTION
**Pull request by prsadhuk**
This test was failing earlier in our nightly testing citing "java.lang.RuntimeException: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location "
Updated test to 
use swing components in EDT, 
setAutoDelay for mouse events, 
add a delay after frame is made visible,
move the frame to center of screen 
and dispose of the frame finally.

Several iterations of the test pass in all platforms. Link in JBS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8198617](https://bugs.openjdk.java.net/browse/JDK-8198617): java/awt/Focus/6382144/EndlessLoopTest.java fails on mac

### Reviewers
 * [Jayathirth D V](https://openjdk.java.net/census#jdv) (@jayathirthrao - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3614/head:pull/3614` \
`$ git checkout pull/3614`

Update a local copy of the PR: \
`$ git checkout pull/3614` \
`$ git pull https://git.openjdk.java.net/jdk pull/3614/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3614`

View PR using the GUI difftool: \
`$ git pr show -t 3614`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3614.diff">https://git.openjdk.java.net/jdk/pull/3614.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Please check that 6382144 can be verified by the updated test.

**Comment by prsadhuk** [comment]
> 
> 
> Please check that 6382144 can be verified by the updated test.

Build without 6382144  fix still fails with the updated test.

**Comment by prsadhuk** [comment]
Any further comment on this?

**Review by jayathirthrao — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
