### PR TITLE
JDK-8311893: Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name

### PR DESCRIPTION
**Pull request by psoujany**
Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name in javadoc which is failing Accessibility checks.
https://bugs.openjdk.org/browse/JDK-8311893
https://bugs.openjdk.org/browse/JDK-8311894

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311893](https://bugs.openjdk.org/browse/JDK-8311893): Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name (**Enhancement** - P4)

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.org/census#hannesw) (@hns - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16148/head:pull/16148` \
`$ git checkout pull/16148`

Update a local copy of the PR: \
`$ git checkout pull/16148` \
`$ git pull https://git.openjdk.org/jdk.git pull/16148/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16148`

View PR using the GUI difftool: \
`$ git pr show -t 16148`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16148.diff">https://git.openjdk.org/jdk/pull/16148.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16148#issuecomment-1757600349)

### CODE REVIEW

**Comment by psoujany** [comment]
@RealCLanger Could you please review my changes. Thank you.

**Comment by RealCLanger** [comment]
> @RealCLanger Could you please review my changes. Thank you.

Sorry, that's not my turf. Somebody from javadoc area should pick this up. However, could you please enable Github Actions testing for your repo? Thanks.

**Comment by psoujany** [comment]
@jonathan-gibbons Could you please review my changes. Thank you.

**Comment by psoujany** [comment]
Can anyone review this PR.

**Comment by psoujany** [comment]
Can anyone review this PR. Thanks.

**Comment by jonathan-gibbons** [comment]
@hns ?

**Comment by jonathan-gibbons** [comment]
As a general rule, whenever a change like this is made, we provide or update a regression test, to verify the fix works as expected, and to ensure that it stays fixed.

**Comment by psoujany** [comment]
Thank you @jonathan-gibbons. I'll check on the regression tests.

**Comment by hns** [comment]
I don't think the proposed solution is correct:

 - The `aria-labelledby` attribute of the tab panel is set to its own id, which does not add any useful information as the tab panel does not contain a human-readable label.
 - The `aria-labelledby` attribute of the table is set to the default tab which is correct in the default view, but it should be updated to the current tab when one other than the default tab is selected.

Looking at [this example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example) as a blueprint, I think the solution should be the following:

 - Add an `aria-label` attribute to the tab panel explaining its purpose, e.g. "Tabs for selecting table contents".
 - Keep the `aria-labelledby` attribute in the table with the id of the default tab as in the current PR.
 - Add code in `script.js` to update the table `aria-labelledby` attribute when a different tab is selected.

**Comment by hns** [comment]
There are quite a few tests failing because of this change, which need to be updated once we agree on the proper solution.

**Comment by psoujany** [comment]
@hns Thanks for your review. Will look into the changes.

**Comment by hns** [comment]
@psoujany some of the additional changes such as updating `script.js` and the failing tests are probably quite involved and easier to by someone familiar with the code, so I could contribute these changes if that's ok with you.

**Comment by psoujany** [comment]
@hns As this PR addresses below comment. I want this PR to be contributed with the below proposal.
`Move the aria-labelledby attribute from the embedded <div> to the <div role="tab-panel"> as proposed, but maintain its current default value (the id of the default tab).`

Others you can take handle. Please let me know if this is fine with you. Thank you.

**Comment by hns** [comment]
@psoujany just to make sure we're on the same page, you'll also update the tests required by this change?

**Comment by psoujany** [comment]
Hi @hns , yes I'm trying to run jtreg testcases with this code changes. I would like to fix the testcase as well, I'll reach out to you for help in case of any queries. Thank you.

**Comment by psoujany** [comment]
@hns I've modified regression tests with the code changes and see langtools jtreg tests passing with the new fixes. Could you please review this PR. Thank you.

**Comment by hns** [comment]
@psoujany I still get two failing tests, possibly because I updated my local repository by merging the current master branch  before running tests. This PR is based on a very outdated branch, so we should definitely merge the master branch before integrating. The failing tests I get on my up-to-date branch are these:

jdk/javadoc/doclet/testPreview/TestPreview.java
jdk/javadoc/doclet/testSpecTag/TestSpecTag.java

**Comment by psoujany** [comment]
@hns I've updated my branch and modified the failing tests. Now all tests seems passing with the changes. Thank you.

**Comment by hns** [comment]
Thanks @psoujany, this looks good now. Although `script.js` only requires a very small change to set the `aria-labelledby` attribute in the new element, I unfortunately detected an additional bug where the attribute is set to the wrong value when switching back to the default tab. I'm currently deciding whether to fix this in this PR or file a new issue.

**Comment by hns** [comment]
@psoujany the last thing that needs to be updated is to change `script.js` to update the `aria-labelledby` attribute in the correct element as I did [in this pull request](https://github.com/psoujany/jdk/pull/1/files). Feel free to make the change yourself if there are problems with the pull request (github complains that I haven't signed the Eclipse Contributors Agreement, but that shouldn't be an issue for this OpenJDK change).

**Comment by psoujany** [comment]
@hns Thank you for the help. I've updated your suggested change to `script.js`.

**Review by hns — APPROVED** [review]
Thanks for fixing the tests, @psoujany! This looks good now.

**Comment by psoujany** [comment]
@hns Could you please sponsor this PR. Thank you.

**Pull request closed without merging**
