### PR TITLE
8329672: Only call SetupNativeCompilation from SetupJdkNativeCompilation

### PR DESCRIPTION
**Pull request by magicus**
This patch will fix the few remaining places where a "raw" call to SetupNativeCompilation was made, instead of going via SetupJdkNativeCompilation. This include repairing the poor old X11Wrapper, which has been broken for some time.

After this we can finally make SetupNativeCompilation an "inner macro" of SetupJdkNativeCompilation, and stop exposing two different ways of compiling native code.

I have also added standard header comments to some places where I have missed it, and corrected an incorrect indentation (all things I found while double-checking all SetupJdkNativeCompilation calls).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329672](https://bugs.openjdk.org/browse/JDK-8329672): Only call SetupNativeCompilation from SetupJdkNativeCompilation (**Bug** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18631/head:pull/18631` \
`$ git checkout pull/18631`

Update a local copy of the PR: \
`$ git checkout pull/18631` \
`$ git pull https://git.openjdk.org/jdk.git pull/18631/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18631`

View PR using the GUI difftool: \
`$ git pr show -t 18631`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18631.diff">https://git.openjdk.org/jdk/pull/18631.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18631#issuecomment-2037637517)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by erikj79 — CHANGES_REQUESTED** [review]
Looks like windows build is failing in GHA.

**Comment by magicus** [comment]
> Looks like windows build is failing in GHA.

I see. I thought it passed on my local Windows testing, but I might have done some changes (that I thought were "trivial") afterwards, since I see that it breaks there now as well. :-(

**Comment by magicus** [comment]
Just to confirm; this PR now passes with byte-by-byte identical builds compared to master.

**Review by erikj79 — APPROVED** [review]

**Pull request closed without merging**
