### PR TITLE
8324304: RISC-V: add hw probe flags

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this simple patch to add hw probe flags?
Thanks!

Per https://github.com/torvalds/linux/blob/master/arch/riscv/include/uapi/asm/hwprobe.h, several extensions were already added in kernel code, we have several intrinsics or funtionalities depends on these extension, it's ready to add these hw probe flags already used in jdk into jdk code.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324304](https://bugs.openjdk.org/browse/JDK-8324304): RISC-V: add hw probe flags (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17519/head:pull/17519` \
`$ git checkout pull/17519`

Update a local copy of the PR: \
`$ git checkout pull/17519` \
`$ git pull https://git.openjdk.org/jdk.git pull/17519/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17519`

View PR using the GUI difftool: \
`$ git pr show -t 17519`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17519.diff">https://git.openjdk.org/jdk/pull/17519.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17519#issuecomment-1904220851)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
LGTM. Any test performed?
BTW: Seems that probe for option `UseZvkn` could also be added which consists of `Zvkned`, `Zvknhb`, `Zvkb` and `Zvkt`. I see these are also there in https://github.com/torvalds/linux/blob/master/arch/riscv/include/uapi/asm/hwprobe.h.

PS: I just realized that this will auto-enable experimental options like `UseZtso` when the feature is available, something which I think we shouldn't do for now. Those experimental options are not fully tested on real hardwares.

**Comment by RealFYang** [comment]
PS: I just realized that this will auto-enable experimental RV-specific JVM options like `UseZtso`, `UseZacas`, etc. when the features are available, something which I think we shouldn't do for now. Those experimental options are not fully tested on real hardwares yet. Maybe remove `UPDATE_DEFAULT(UseZtso)`, `UPDATE_DEFAULT(UseZtso)` from `ext_Ztso`, `ext_Zacas` declarations at the same time?

**Comment by Hamlin-Li** [comment]
I just tested on `Lichee Pi 4A`, seems the default behaviour is to disable them.

```
echo "enable explicitly ......"
TEST_OPTIONS="-XX:+UseZicboz -XX:+UseZtso -XX:+UseZacas -XX:+UseZfh"
$J_H/bin/java -XX:+PrintFlagsFinal -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions ${TEST_OPTIONS} -version | grep -e UseZicboz -e UseZtso -e UseZacas -e UseZfh

echo "by default ......"
TEST_OPTIONS=""
$J_H/bin/java -XX:+PrintFlagsFinal -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions ${TEST_OPTIONS} -version | grep -e UseZicboz -e UseZtso -e UseZacas -e UseZfh
```

output is as below:
```
enable explicitly ......
     bool UseZacas                                 = true                            {ARCH experimental} {command line}
     bool UseZfh                                   = true                                 {ARCH product} {command line}
     bool UseZicboz                                = true                            {ARCH experimental} {command line}
     bool UseZtso                                  = true                            {ARCH experimental} {command line}
by default ......
     bool UseZacas                                 = false                           {ARCH experimental} {default}
     bool UseZfh                                   = false                                {ARCH product} {default}
     bool UseZicboz                                = false                           {ARCH experimental} {default}
     bool UseZtso                                  = false                           {ARCH experimental} {default}
```

**Comment by Hamlin-Li** [comment]
> LGTM. Any test performed? BTW: Seems that probe for option `UseZvkn` could also be added which consists of `Zvkned`, `Zvknhb`, `Zvkb` and `Zvkt`. I see these are also there in https://github.com/torvalds/linux/blob/master/arch/riscv/include/uapi/asm/hwprobe.h.

Yes, I tested `test/hotspot/jtreg/compiler/` via qemu, no failures related to this options are found.
The reason other flags are not added is that we don't have them in jdk yet.

**Comment by RealFYang** [comment]
> I just tested on `Lichee Pi 4A`, seems the default behaviour is to disable them.
> 
> ```
> echo "enable explicitly ......"
> TEST_OPTIONS="-XX:+UseZicboz -XX:+UseZtso -XX:+UseZacas -XX:+UseZfh"
> $J_H/bin/java -XX:+PrintFlagsFinal -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions ${TEST_OPTIONS} -version | grep -e UseZicboz -e UseZtso -e UseZacas -e UseZfh
> 
> echo "by default ......"
> TEST_OPTIONS=""
> $J_H/bin/java -XX:+PrintFlagsFinal -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions ${TEST_OPTIONS} -version | grep -e UseZicboz -e UseZtso -e UseZacas -e UseZfh
> ```
> 
> output is as below:
> 
> ```
> enable explicitly ......
>      bool UseZacas                                 = true                            {ARCH experimental} {command line}
>      bool UseZfh                                   = true                                 {ARCH product} {command line}
>      bool UseZicboz                                = true                            {ARCH experimental} {command line}
>      bool UseZtso                                  = true                            {ARCH experimental} {command line}
> by default ......
>      bool UseZacas                                 = false                           {ARCH experimental} {default}
>      bool UseZfh                                   = false                                {ARCH product} {default}
>      bool UseZicboz                                = false                           {ARCH experimental} {default}
>      bool UseZtso                                  = false                           {ARCH experimental} {default}
> ```

Say, when you are running some latest kernel with the hwprobe capability on some new RISC-V hardwares with those extensions. 
Then these JVM options will be auto-enabled, right? But I think we need some time to fully test them before that happens. AFAIK, Lichee Pi 4A is not equipped with those extensions and is running some older kernel.

**Comment by Hamlin-Li** [comment]
It makes sense, removed UPDATE_DEFAULT for these extensions.

**Comment by RealFYang** [comment]
> It makes sense, removed UPDATE_DEFAULT for these extensions.

Thanks for the update. Would you mind one more tweak? I think we should also remove the auto-enablement of `UseZic64b`, `UseZicbom`, `UseZicbop` and `UseZihintpause` which are also experimental options for now.

**Comment by Hamlin-Li** [comment]
I'm not sure, as these vm options (UseZic64b, UseZicbom, UseZicbop and UseZihintpause) are not `enable`d in RiscvHwprobe::add_features_from_query_result(), so I think they are not enabled automatically even if the hw supports these features, unless a vendor want to enable them.

So, I think it's good to keep auto-enablement of Zicboz/Ztso/Zacas in vm_version_riscv.hpp, and remove the enable code of these options in RiscvHwprobe::add_features_from_query_result() in this patch?

**Comment by RealFYang** [comment]
> I'm not sure, as these vm options (UseZic64b, UseZicbom, UseZicbop and UseZihintpause) are not `enable`d in RiscvHwprobe::add_features_from_query_result(), so I think they are not enabled automatically even if the hw supports these features, unless a vendor want to enable them.

Sorry, I missed that before. I think you are right.

> So, I think it's good to keep auto-enablement of Zicboz/Ztso/Zacas in vm_version_riscv.hpp, and remove the enable code of these options in RiscvHwprobe::add_features_from_query_result() in this patch?

Yeah, that will be more consistent.

**Comment by Hamlin-Li** [comment]
Updated, please take a look again.

**Review by robehn — APPROVED** [review]
Seems alright, thanks!

**Comment by Hamlin-Li** [comment]
Thanks @RealFYang @robehn for your reviewing.

/integrate

**Pull request closed without merging**
