### PR TITLE
8264999: GeneralPath.lineTo() to itself produces jagged lines

### PR DESCRIPTION
**Pull request by mickleness**
Previously when you drew a line that moved exactly (+0, +0) with a miter stroke the Stroker class acted like a horizontal miter was appropriate. Now we abort instead, so no miter is applied.

The new unit test tests the original steps plus several variations.

I'm a little nervous about this change because it looks like someone previously considered this exact condition and implemented a different behavior. I don't think I understand the original rationale.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8264999](https://bugs.openjdk.org/browse/JDK-8264999): GeneralPath.lineTo() to itself produces jagged lines

### Reviewers
 * [Laurent Bourgès](https://openjdk.org/census#lbourges) (@bourgesl - Committer)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/8943/head:pull/8943` \
`$ git checkout pull/8943`

Update a local copy of the PR: \
`$ git checkout pull/8943` \
`$ git pull https://git.openjdk.org/jdk pull/8943/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8943`

View PR using the GUI difftool: \
`$ git pr show -t 8943`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/8943.diff">https://git.openjdk.org/jdk/pull/8943.diff</a>

</details>

### CODE REVIEW

**Comment by mickleness** [comment]
@bourgesl as the (or one of the?) resident Marlin experts: what do you think of this approach and the accompanying unit test?

**Comment by mickleness** [comment]
Sorry I must have missed that code review.

I just pushed an update with your proposal.

On further review: I was dissatisfied with the unit tests, so I rewrote them. Some fail now. (Both before and after this commit.)

I commented out the failing test scenarios in this commit. They are not strictly required to resolve this ticket, so I'm not sure what our protocol is. (We could try to resolve these unit tests now so everything passes? Or we could submit a separate ticket for the remaining scenarios? Or something else?)

I'm open to suggestions regarding next steps.

**Comment by bourgesl** [comment]
I will try your test code today and see why some tests fail.

**Comment by bourgesl** [comment]
Jeremy,
I fixed the bug in the marlin renderer repository, see the Stroker fix:
https://github.com/bourgesl/marlin-renderer/commit/b7adf5e606ca0b809118dfe5ab85d4fcf71bd12b#diff-17283d07a3ba6855b0e01eb58cc579c0543b6fae142eb7192dbaa9c9a55e8ef0

Moreover I confirm your 4 disabled tests fail for a good reason: the expected path ignores [...] but the tested path not.
In these cases, the expected path (move only) draws nothing, but the tested path (m + ...) will draw something !
Maybe @prrace could confirm ?

Here is the passing test on my side: https://github.com/bourgesl/marlin-renderer/commit/b7adf5e606ca0b809118dfe5ab85d4fcf71bd12b#diff-38152f6e0b7e1a267ef1391ec7fea12086ce9b573a55d0bbb7f84bb7eb15170e

Please fix the Stroker as proposed, the fix looks good to me (not a reviewer)

**Comment by bourgesl** [comment]
Concerning the test cases where the expected output is unknown, we could test java2d pipeline without antialiasing (not marlin renderer) or compare with other svg renderers like browsers or image magick (linux). 
Reference images could be generated by other tools and loaded as png images ?

Finally it is possible to compare with former Ductus AA renderer if tests are run on oracle jdk8.

**Review by bourgesl — APPROVED** [review]
Looks good

**Comment by bourgesl** [comment]
@prrace please review this PR officially, LGTM

**Review by prrace — APPROVED** [review]
Testing looks good.

**Pull request closed without merging**
