### PR TITLE
8256205: Simplify compiler calling convention handling

### PR DESCRIPTION
**Pull request by cl4es**
Clean up and simplify some of the calling convention handling:

- Remove Matcher::calling_convention/c_calling_convention and replace select few call sites with direct calls to SharedRuntime
- Remove unused is_outgoing args. Since the SPARC removal the is_outgoing has no effect on the calling_convention or return_value methods.
- Move in_preserved_stack_slots to SharedRuntime to match out_preserved_stack_slots. 

This has a tiny positive impact by reducing calls and improving inlining (at least gcc has a hard time inlining anything that goes in the .ad files, even when it's defined to the same class), but is mainly a cleanup effort.

Testing: Oracle tier1-2 testing; S390, PPC and ARM32 builds

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8256205](https://bugs.openjdk.java.net/browse/JDK-8256205): Simplify compiler calling convention handling

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1168/head:pull/1168`
`$ git checkout pull/1168`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Nice clean up.

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by cl4es** [comment]
@vnkozlov @neliasso - thank you for reviewing!

/integrate

**Pull request closed without merging**
