### PR TITLE
JDK-8310460: Remove jdeps -profile option

### PR DESCRIPTION
**Pull request by mlchung**
Compact profiles are defined in Java SE 8 and are legacy in Java SE 9. jdeps -profile option was deprecated for removal in JDK 21. This option can be removed in JDK 22. Customers can use jdeps to find the set of modules required by their applications instead.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8310461](https://bugs.openjdk.org/browse/JDK-8310461) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8310460](https://bugs.openjdk.org/browse/JDK-8310460): Remove jdeps -profile option (**Enhancement** - P4)
 * [JDK-8310461](https://bugs.openjdk.org/browse/JDK-8310461): Remove jdeps -profile option (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14570/head:pull/14570` \
`$ git checkout pull/14570`

Update a local copy of the PR: \
`$ git checkout pull/14570` \
`$ git pull https://git.openjdk.org/jdk.git pull/14570/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14570`

View PR using the GUI difftool: \
`$ git pr show -t 14570`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14570.diff">https://git.openjdk.org/jdk/pull/14570.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14570#issuecomment-1599339319)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Removal looks okay, I didn't spot anything else that needs to be updated.

**Comment by mlchung** [comment]
Thanks for the quick review.

**Pull request closed without merging**
