### PR TITLE
8267894: Skip work for empty regions in G1 Full GC

### PR DESCRIPTION
**Pull request by walulyai**
Hi all,

Please review this change to skip doing work on regions that were empty at the beginning of the Full GC in phases that execute on a per-region basis.

Testing: Tier 1-3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267894](https://bugs.openjdk.java.net/browse/JDK-8267894): Skip work for empty regions in G1 Full GC

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5143/head:pull/5143` \
`$ git checkout pull/5143`

Update a local copy of the PR: \
`$ git checkout pull/5143` \
`$ git pull https://git.openjdk.java.net/jdk pull/5143/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5143`

View PR using the GUI difftool: \
`$ git pr show -t 5143`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5143.diff">https://git.openjdk.java.net/jdk/pull/5143.diff</a>

</details>

### CODE REVIEW

**Review by kstefanj — COMMENTED** [review]
I think the change looks good in general, but maybe we should go with a "named" state for free regions. Either we change the name for the default value in `G1FullGCHeapRegionAttr` or we add a new state that we set for free regions. What do you think?

**Comment by walulyai** [comment]
> I think the change looks good in general, but maybe we should go with a "named" state for free regions. Either we change the name for the default value in `G1FullGCHeapRegionAttr` or we add a new state that we set for free regions. What do you think?


AFAIK, changing the default value to "Free" instead of  "Invalid" would suffice, however, need to clarify on how that is handled by `assert(!is_invalid(obj), "not initialized yet");` which indicate some sort of transition from "Invalid" to "initialized".

**Comment by kstefanj** [comment]
I think the text "not initialized yet" is a bit wrong. We should never call is_skip_marking() for objects in "Invalid" regions, because there can't be any objects there. Same goes for "Free" regions. So I would change the assert to something like: ```
assert(!is_free(obj), "Should be no objects in free regions."); 
```

I agree that changing the default value should work. One benefit of using a new state could be to have a difference between free and not committed regions. But not sure it is worth the effort right now.

**Review by kstefanj — APPROVED** [review]
Looks good to me.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by walulyai** [comment]
Thanks @kstefanj and @tschatzl for the reviews

 /integrate

**Pull request closed without merging**
