### PR TITLE
8262328: Templatize JVMFlag boilerplate access methods

### PR DESCRIPTION
**Pull request by iklam**
We have a bunch of boilerplate method like:

```
JVMFlagAccess::boolAtPut (JVMFlag* f, bool* v, JVMFlagOrigin origin)
JVMFlagAccess::intAtPut (JVMFlag* f, int* v, JVMFlagOrigin origin)
JVMFlagAccess::uintAtPut (JVMFlag* f, uint* v, JVMFlagOrigin origin)
...
```

Similarly, we also have 8 different functions: JVMFlag::{set_bool, set_int, set_intx, ...}

We should replace such patterns with

```
template <typename T>
JVMFlagAccess::set(JVMFlag* f, T* value, JVMFlagOrigin origin)
```

This would allow us to templatize the 8x boilerplate functions in writeableFlags.cpp.

The flag access code in whitebox.cpp can also be improved.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262328](https://bugs.openjdk.java.net/browse/JDK-8262328): Templatize JVMFlag boilerplate access methods

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 4c0c8ae22272a31991ed34a3dfb922fb223e17fb
 * [Gerard Ziemski](https://openjdk.java.net/census#gziemski) (@gerard-ziemski - Committer) ⚠️ Review applies to 4c0c8ae22272a31991ed34a3dfb922fb223e17fb

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3318/head:pull/3318` \
`$ git checkout pull/3318`

Update a local copy of the PR: \
`$ git checkout pull/3318` \
`$ git pull https://git.openjdk.java.net/jdk pull/3318/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3318`

View PR using the GUI difftool: \
`$ git pr show -t 3318`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3318.diff">https://git.openjdk.java.net/jdk/pull/3318.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
I need to work on this PR so more. Closing it for now.

**Comment by iklam** [comment]
I've updated the patch and the JVMFlagAccess API should have identical behavior as before. Now it's ready to be reviewed again.

**Review by dholmes-ora — COMMENTED** [review]
Hi Ioi,

In terms of readability and writeability I prefer \<type>AtPut() over set<JVM_FLAG_TYPE(type)>(). Is there any way to push the JVM_FLAG_TYPE down a level so it doesn't shout at you when reading the code? set\<type>() would look much much better.

Thanks,
David

**Comment by iklam** [comment]
> Hi Ioi,
> 
> In terms of readability and writeability I prefer <type>AtPut() over set<JVM_FLAG_TYPE(type)>(). Is there any way to push the JVM_FLAG_TYPE down a level so it doesn't shout at you when reading the code? set<type>() would look much much better.
> 
> Thanks,
> David

I added the `JVMFlagAccess::set_<type>()` functions back (they are the same as the old `<type>AtPut` functions, but with a more consistent naming style).

Now I use the more low-level `set<JVM_FLAG_TYPE(type)>()` only in templates where the type is not statically known. E.g, `WriteableFlags::set_flag_impl()`.

* * *

A related note: in an [earlier version](https://webrevs.openjdk.java.net/?repo=jdk&pr=3318&range=00), I tried to get rid of the `<JVM_FLAG_TYPE(type)>` altogether, where the code is much cleaner with template type inference.

```
JVMFlag* flag = someSizetFlag;
size_t s = 0;
JVMFlagAccess::set(flag, &s, origin);
```

However, this may allow type mismatch like the following, on platforms that use the exact same type for `size_t` and `uint`:

```
JVMFlag* flag = someSizetFlag;
uint s = 0;
JVMFlagAccess::set(flag, &s, origin);
```

but you will get a runtime failure on platforms where `size_t` is not the same as `uint`. So I decided against this design due to non-portability.

**Review by dholmes-ora — APPROVED** [review]
Hi Ioi,

This latest version looks good to me.

Thanks,
David

**Comment by gerard-ziemski** [comment]
I'm taking a look at your fix Ioi. Building it locally, wanted to check out a few things...

**Review by gerard-ziemski — APPROVED** [review]
Very nice! With all this reduction and "templatization" effort, soon we will be left with one line of a template code at this rate :-)

The only feedback I have is that I wish we could replace `int type_enum` with `FlagType type_enum`

**Comment by iklam** [comment]
> Very nice! With all this reduction and "templatization" effort, soon we will be left with one line of a template code at this rate :-)
> 
> The only feedback I have is that I wish we could replace `int type_enum` with `FlagType type_enum`

Hi Gerard, thanks for the review. Replacing the int with enum will cause quite a bit of changes, so I would probably do that in a separate RFE.

**Comment by iklam** [comment]
Thanks @dholmes-ora and @gerard-ziemski for the review!
/integrate

**Pull request closed without merging**
