### PR TITLE
8326836: Incorrect `@since` tags for ClassSignature methods

### PR DESCRIPTION
**Pull request by nizarbenalla**
# Issue
- [JDK-8326836](https://bugs.openjdk.org/browse/JDK-8326836): changes were made to the method signatures but this modification isn't reflected in the @ since tags. The @ since tags need to be updated.

I changed the `@since` tags to better accurately show when the methods were introduced. This is similar to #18032 and #18373 

For context, I am writing tests to check for accurate use of `@since` tags in documentation comments in source code.
We're following these rules for now:

### Rule 1: Introduction of New Elements

- If an element is new in JDK N, with no equivalent in JDK N-1, it must include `@since N`.
  - Exception: Member elements (fields, methods, nested classes) may omit `@since` if their version matches the value specified for the enclosing class or interface.

### Rule 2: Existing Elements in Subsequent JDK Versions

- If an element exists in JDK N, with an equivalent in JDK N-1, it should not include `@since N`.

### Rule 3: Handling Missing `@since` Tags in methods if there is no `@since`

- When inspecting methods, prioritize the `@since` annotation of the supertype's overridden method.
- If unavailable or if the enclosing class's `@since` is newer, use the enclosing element's `@since`.

  I.e. if A extends B, and we add a method to B in JDK N, and add an override of the method to A in JDK M (M > N), we will use N as the effective `@since` for the method.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326836](https://bugs.openjdk.org/browse/JDK-8326836): Incorrect `@<!---->since` tags for ClassSignature methods (**Bug** - P4)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**) ⚠️ Review applies to [f73ce11a](https://git.openjdk.org/jdk/pull/18030/files/f73ce11a6f30622c8df09d5180db692926c56f44)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18030/head:pull/18030` \
`$ git checkout pull/18030`

Update a local copy of the PR: \
`$ git checkout pull/18030` \
`$ git pull https://git.openjdk.org/jdk.git pull/18030/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18030`

View PR using the GUI difftool: \
`$ git pr show -t 18030`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18030.diff">https://git.openjdk.org/jdk/pull/18030.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18030#issuecomment-1988913696)

### CODE REVIEW

**Comment by liach** [comment]
Good spotting! I didn't think this was necessary as FFM API had similar new method additions before, yet they didn't add `@since` tags in existing files :(

First, the `ClassSig superclassSignature()` method has replaced the old one returning `TypeSig`, thus it's a new method (different descriptors, breaking binary compatibility, somewhat source compatible) and should get a `@since` tag.

Also, what's the definition of a signature? Do we introduce a new `@since` tag if the generic signature differs, i.e. `List<RefTypeSig>` vs `List<ClassTypeSig>`?

If we do introduce a `@since` tag for a generic signature change (but no change in bytecode descriptor), we should add a `@since` tag to `List<Signature.ClassTypeSig> superinterfaceSignatures()`, as its generic signature has changed.

**Comment by lahodaj** [comment]
We would like to have an automated way to check `@since` tags, for that, the existing mistakes should be cleaned. It is true there were some mistakes in FFM (and there are some mistakes even in production code elsewhere), but those that persist in the mainline should be cleaned as well.

I think I'd also add that `java.lang.classfile.ClassFile.JAVA_23_VERSION` should also have `@since 23`.

Regarding that is the definition of "a new method" - I would say one reasonable way to detect new methods is based on JVM descriptors. There are some methods in the JDK that have been retrofitted from non-generic to generic in a binary compatible way, and it seems unfounded to require `@since` for that.

**Comment by nizarbenalla** [comment]
`/covered`

**Comment by liach** [comment]
@nizarbenalla Why don't you add since tags for `superclassSignature` and `superinterfaceSignatures` methods, both of which have their signatures changed like the two `of` methods?

**Comment by pavelrappo** [comment]
Trivially, what's the reason you capitalised the word "tags" in the PR title and the respective JBS issue?

**Comment by nizarbenalla** [comment]
@liach good find! maybe I should look more carefully into members of Classes annotated with `@PreviewFeature`, I'll keep those for now. Until I can get my tool to programmatically pickup on them.

**Comment by nizarbenalla** [comment]
@pavelrappo no real reason, that's just how I wrote it in my notes and it persisted until now.
I can change it here if you change it in the JBS

**Comment by pavelrappo** [comment]
> @pavelrappo no real reason, that's just how I wrote it in my notes and it persisted until now. I can change it here if you change it in the JBS

Done.

**Pull request closed without merging**
