### PR TITLE
8298274: Problem list TestSPISigned on Windows

### PR DESCRIPTION
**Pull request by jerboaa**
The test is failing on Windows. Problem list it until it can get properly analyzed and fixed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298274](https://bugs.openjdk.org/browse/JDK-8298274): Problem list TestSPISigned on Windows

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11560/head:pull/11560` \
`$ git checkout pull/11560`

Update a local copy of the PR: \
`$ git checkout pull/11560` \
`$ git pull https://git.openjdk.org/jdk pull/11560/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11560`

View PR using the GUI difftool: \
`$ git pr show -t 11560`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11560.diff">https://git.openjdk.org/jdk/pull/11560.diff</a>

</details>

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This is a trivial fix.

**Comment by jerboaa** [comment]
If somebody could test that the problem list entry works as expected on Windows, I'd appreciate it (I'm not touching those files much).

**Comment by jerboaa** [comment]
OK.

/integrate

**Pull request closed without merging**
