### PR TITLE
8308464: Shared array class should not always be loaded in boot loader

### PR DESCRIPTION
**Pull request by calvinccheung**
Please review this fix for using the appropriate class loader when loading a shared array class. The log output from -`Xlog:cds+unshareable=trace` is also updated to include the class loader information.

For example:
before:
`[0.203s][trace][cds,unshareable ] restore: ArrayKlassesApp`

after:
`[0.203s][trace][cds,unshareable ] restore: ArrayKlassesApp with class loader: jdk.internal.loader.ClassLoaders$AppClassLoader`

Passed tiers 1- 3 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308464](https://bugs.openjdk.org/browse/JDK-8308464): Shared array class should not always be loaded in boot loader (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15421/head:pull/15421` \
`$ git checkout pull/15421`

Update a local copy of the PR: \
`$ git checkout pull/15421` \
`$ git pull https://git.openjdk.org/jdk.git pull/15421/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15421`

View PR using the GUI difftool: \
`$ git pr show -t 15421`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15421.diff">https://git.openjdk.org/jdk/pull/15421.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15421#issuecomment-1693612529)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
LGTM. Thanks.

**Review by iklam — APPROVED** [review]
LGTM.

**Comment by calvinccheung** [comment]
Thanks @dholmes-ora, @iklam for the review!

/integrate

**Pull request closed without merging**
