### PR TITLE
8317837: Leftover FFM implementation-only changes

### PR DESCRIPTION
**Pull request by JornVernee**
Port of miscellaneous leftover implementation-only changes from the panama-foreign repo:

These four related to improving the performance of the internal `strlen` implementation:

  - https://github.com/openjdk/panama-foreign/pull/862
  - https://github.com/openjdk/panama-foreign/pull/860
  - https://github.com/openjdk/panama-foreign/pull/858
  - https://github.com/openjdk/panama-foreign/pull/857
  
Adding new benchmarks:
  
  - https://github.com/openjdk/panama-foreign/pull/874
  - https://github.com/openjdk/panama-foreign/pull/870

Other misc. changes:

  - https://github.com/openjdk/panama-foreign/pull/885
  - https://github.com/openjdk/panama-foreign/pull/886
  - https://github.com/openjdk/panama-foreign/pull/864
  - https://github.com/openjdk/panama-foreign/pull/903
  - https://github.com/openjdk/panama-foreign/pull/890 (note that this is a javadoc block in the implementation only)
  - https://github.com/openjdk/panama-foreign/pull/908
  - https://github.com/openjdk/panama-foreign/pull/910
  
Testing: `jdk_foreign`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317837](https://bugs.openjdk.org/browse/JDK-8317837): Leftover FFM implementation-only changes (**Enhancement** - P3)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Contributors
 * Maurizio Cimadamore `<mcimadamore@openjdk.org>`
 * Per Minborg `<pminborg@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16128/head:pull/16128` \
`$ git checkout pull/16128`

Update a local copy of the PR: \
`$ git checkout pull/16128` \
`$ git pull https://git.openjdk.org/jdk.git pull/16128/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16128`

View PR using the GUI difftool: \
`$ git pr show -t 16128`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16128.diff">https://git.openjdk.org/jdk/pull/16128.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16128#issuecomment-1760343798)

### CODE REVIEW

**Review by mcimadamore — COMMENTED** [review]
Looks good.
It seems like this PR is missing some string optimizations:
https://git.openjdk.org/panama-foreign/pull/875

**Comment by JornVernee** [comment]
Thanks for the review. I've added the missing patch now

**Comment by mcimadamore** [comment]
This seems to have been missed too? https://github.com/openjdk/panama-foreign/pull/897

**Comment by mcimadamore** [comment]
> This seems to have been missed too? [openjdk/panama-foreign#897](https://github.com/openjdk/panama-foreign/pull/897)

I also don't see https://git.openjdk.org/panama-foreign/pull/894

Perhaps you are planning a different PR for "style" only changes?

**Comment by JornVernee** [comment]
Yes, both of those are planned for the style-only PR.

**Review by mcimadamore — APPROVED** [review]

**Pull request closed without merging**
