### PR TITLE
8336928: GHA: Bundle artifacts removal broken

### PR DESCRIPTION
**Pull request by zzambers**
GHA code, which tries to remove bundle artifacts no longer works. It probably broke after [JDK-8324723](https://bugs.openjdk.org/browse/JDK-8324723) (GHA: Upgrade some actions to avoid deprecated Node 16).

**Details:**
Seems like there were some backend architecture changes in [artifact actions in v4](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new). As result old code to remove artifacts no longer works. However there is [REST API](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28) available, which works.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336928](https://bugs.openjdk.org/browse/JDK-8336928): GHA: Bundle artifacts removal broken (**Bug** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20281/head:pull/20281` \
`$ git checkout pull/20281`

Update a local copy of the PR: \
`$ git checkout pull/20281` \
`$ git pull https://git.openjdk.org/jdk.git pull/20281/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20281`

View PR using the GUI difftool: \
`$ git pr show -t 20281`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20281.diff">https://git.openjdk.org/jdk/pull/20281.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20281#issuecomment-2243765457)

### CODE REVIEW

**Review by magicus — APPROVED** [review]
The code looks sane. Have you been able to test this? (Trying out GHA changes is sometimes a bit tricky)

**Comment by zzambers** [comment]
@magicus I have tested it by having GHA enabled on my fork/branch, as usual. I can see that right number of artifacts has been removed in ["Remove bundle artifacts"](https://github.com/zzambers/jdk/actions/runs/10048035882/job/27776568302) step. And there are no "bundles-*" artifacts in [Summary](https://github.com/zzambers/jdk/actions/runs/10048035882). (Unlike in other test runs, without this change, e.g. [here](https://github.com/egahlin/jdk/actions/runs/10246511374).)

**Comment by magicus** [comment]
Great, thanks! The build system does not need a secondary review so you are free to integrate.

**Comment by zzambers** [comment]
@magicus thanks
/integrate

**Pull request closed without merging**
