### PR TITLE
8328318: Wrong description in X509Extension.getExtensionValue method javadoc

### PR DESCRIPTION
**Pull request by blperez01**
Removed `PrivateKeyUsagePeriod` from method javadoc and added several commonly used extensions

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328318](https://bugs.openjdk.org/browse/JDK-8328318): Wrong description in X509Extension.getExtensionValue method javadoc (**Bug** - P4)

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)
 * [Bradford Wetmore](https://openjdk.org/census#wetmore) (@bradfordwetmore - **Reviewer**) ⚠️ Review applies to [272d1663](https://git.openjdk.org/jdk/pull/18565/files/272d1663bbd77a5771ce94426ab393e118ac4578)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18565/head:pull/18565` \
`$ git checkout pull/18565`

Update a local copy of the PR: \
`$ git checkout pull/18565` \
`$ git pull https://git.openjdk.org/jdk.git pull/18565/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18565`

View PR using the GUI difftool: \
`$ git pr show -t 18565`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18565.diff">https://git.openjdk.org/jdk/pull/18565.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18565#issuecomment-2030273356)

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]
Looks good other than the copyright date.

**Review by seanjmullan — APPROVED** [review]

**Comment by bradfordwetmore** [comment]
Minor comments, otherwise I'm ok.

Sean's comment in the bug mentioned [AuthorityInformationAccess](https://www.rfc-editor.org/rfc/rfc5280.html#section-4.2.2.1), did you decide against it?

**Review by bradfordwetmore — APPROVED** [review]

**Review by seanjmullan — APPROVED** [review]

**Pull request closed without merging**
