### PR TITLE
8191460: crash in Annotate with duplicate declaration and annotation processing enabled

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
This PR is removing an assertion in `com.sun.tools.javac.comp.Annotate`. The assertion is being thrown for a special, corner-ish, case. Basically having:
```
package p;
@Deprecated class T {}  // see that class T is annotated
```
and:
```
package p;
class Y {
    @interface A {}
    @interface A {} // error: class A is already defined
    T t;
}
```
class `Y` has a duplicate definition of annotation `A`. Now if class `T` is compiled first as in:

`javac -d out/ p/T.java`

and then we do:
`javac -processor P -cp p:out/:. p/Y.java p/T.java`

where P is the simplest possible annotation processor, basically doing nothing. IMO what is happening here is that during the second compilation, once the compiler find type `T` in class `Y`, given that T.class is in the classpath, it is loaded and the `@Deprecated` annotation is attached to symbol for type `T`. Then when the source for `T.java` is being compiled and its annotations are being processed we get to the code where the assertion is. Here the symbol for `T` is not a package but its metadata is not empty and so the assertion is thrown. The fix here is just removing the assertion as as shown by this example it is not an invariant.

TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8191460](https://bugs.openjdk.org/browse/JDK-8191460): crash in Annotate with duplicate declaration and annotation processing enabled (**Bug** - P3)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**)

### Contributors
 * Jan Lahoda `<jlahoda@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16443/head:pull/16443` \
`$ git checkout pull/16443`

Update a local copy of the PR: \
`$ git checkout pull/16443` \
`$ git pull https://git.openjdk.org/jdk.git pull/16443/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16443`

View PR using the GUI difftool: \
`$ git pr show -t 16443`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16443.diff">https://git.openjdk.org/jdk/pull/16443.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16443#issuecomment-1788406655)

### CODE REVIEW

**Comment by vicente-romero-oracle** [comment]
@lahodaj thanks for the proposed fix, I think it is spot on!

**Review by asotona — APPROVED** [review]
Looks good.

**Pull request closed without merging**
