### PR TITLE
8344188: Cleanup sun.net.www.protocol.jar.JarFileFactory after JEP 486 integration

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which removes SM permission checking from `s.n.w.p.j.JarFileFactory`.

This removes the permission checking happening in `JarFileFactory::getCachedJarFile` and also removes the associated private `getPermission` method, (sadly including the cute `// gulp`). The import of `java.security.Permission` is also removed.

Testing: `test/jdk/sun/net/www/protocol/jar` runs green, GHA results pending.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344188](https://bugs.openjdk.org/browse/JDK-8344188): Cleanup sun.net.www.protocol.jar.JarFileFactory after JEP 486 integration (**Sub-task** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22135/head:pull/22135` \
`$ git checkout pull/22135`

Update a local copy of the PR: \
`$ git checkout pull/22135` \
`$ git pull https://git.openjdk.org/jdk.git pull/22135/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22135`

View PR using the GUI difftool: \
`$ git pr show -t 22135`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22135.diff">https://git.openjdk.org/jdk/pull/22135.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22135#issuecomment-2478183021)
</details>

### CODE REVIEW

**Comment by dfuch** [comment]
Changes look good, but since this is linked to JarURLConnection it would be good to run tier1,tier2 to validate.

**Review by jaikiran — APPROVED** [review]

**Comment by eirbjo** [comment]
> Changes look good, but since this is linked to JarURLConnection it would be good to run tier1,tier2 to validate.

Ran tests `jtreg:test/jdk:tier2`, results look okay:

* `VerifyJimage` fail with the same error as in the `FtpClient` PR
* `AsynchronousChannelGroup/Unbounded` fails with a timeout, probably intermittent
* `NamedGroupsWithCipherSuite` fails with a timeout, probably intermittent

**Review by dfuch — APPROVED** [review]
I ran tier2 in our CI too and didn't spot any failure

**Pull request closed without merging**
