### PR TITLE
8343479: Remove unnecessary @SuppressWarnings annotations (hotspot)

### PR DESCRIPTION
**Pull request by archiecobbs**
Please review this patch which removes unnecessary `@SuppressWarnings` annotations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343479](https://bugs.openjdk.org/browse/JDK-8343479): Remove unnecessary @SuppressWarnings annotations (hotspot) (**Sub-task** - P5)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21853/head:pull/21853` \
`$ git checkout pull/21853`

Update a local copy of the PR: \
`$ git checkout pull/21853` \
`$ git pull https://git.openjdk.org/jdk.git pull/21853/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21853`

View PR using the GUI difftool: \
`$ git pr show -t 21853`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21853.diff">https://git.openjdk.org/jdk/pull/21853.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21853#issuecomment-2453030376)
</details>

### CODE REVIEW

**Comment by eme64** [comment]
Hi @archiecobbs can you please give some more info about why these were introduced, and why they are now not needed any more?

**Comment by archiecobbs** [comment]
Hi @eme64,

> Hi @archiecobbs can you please give some more info about why these were introduced, and why they are now not needed any more?

FYI there are [several other](https://github.com/openjdk/jdk/pulls?q=author%3Aarchiecobbs+is%3Apr+%22Remove+unnecessary%22+in%3Atitle+) PR's like this one. I haven't checked exhaustively, but all of the ones I've checked appear to be due to either (a) the warning was never needed, or (b) a subsequent refinement of the warning itself which made the code no longer qualify as "warnable".

For an example of (a) see commit 8fb70c710afa which added `@SuppressWarnings("unchecked")` for a cast to type `Key`, even though `Key` is not a generic type and so the cast was never unchecked in the first place.

For an example of (b), see commit b431c6929d12 which added `@SuppressWarnings("serial")` because an anonymous class did not declare `serialVersionUID`, but then later the warning was was changed to no longer trigger in that situation by [JDK-7152104](https://bugs.openjdk.org/browse/JDK-7152104), but the annotation was not removed as part of that commit.

In this particular PR, it looks like (for example) the useless `@SuppressWarnings("try")` annotations on `compileMethod()` was [added in this commit](https://github.com/openjdk/jdk/commit/3b0ee5a6d8b89a52b0dacc51399955631d6aa597#diff-4d3a3b7e7e12e1d5b4cf3e4677d9e0de5e9df3bbf1bbfa0d8d43d12098d67dc4) - probably a copy & paste error. This is typical.

I guess the only other possibility is that the warning stopped working at some point due to a bug, but I haven't seen any examples of that.

**Comment by archiecobbs** [comment]
> but all of the ones I've checked appear to be ...

Correction - there is actually one case that revealed a compiler bug: [JDK-8343286](https://bugs.openjdk.org/browse/JDK-8343286).

**Review by chhagedorn — APPROVED** [review]
Looks reasonable.

**Review by eme64 — APPROVED** [review]
Ok, thanks for the explanation. Sounds reasonable.

**Comment by archiecobbs** [comment]
Thanks for the reviews.

**Pull request closed without merging**
