### PR TITLE
JDK-8273745: VerifyLocale.java occasionally times out

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a simple test-only update, to reduce the number of locales tested, and thereby reduce the number of javadoc-invocations

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273745](https://bugs.openjdk.java.net/browse/JDK-8273745): VerifyLocale.java occasionally times out

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5814/head:pull/5814` \
`$ git checkout pull/5814`

Update a local copy of the PR: \
`$ git checkout pull/5814` \
`$ git pull https://git.openjdk.java.net/jdk pull/5814/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5814`

View PR using the GUI difftool: \
`$ git pr show -t 5814`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5814.diff">https://git.openjdk.java.net/jdk/pull/5814.diff</a>

</details>

### CODE REVIEW

**Review by pavelrappo — APPROVED** [review]
Looks better than it was.

The test indeed seems to use too many resources for the value it provides. Here's what the test reports on my machine. Before the change:
```
Skipped 1 locales
Tested 1015 locales
```
After the change:
```
Skipped 623 locales
Tested 393 locales
```
For me, the change cuts the execution time from 20 seconds to 13. While it's good, it is still too long to reasonably test that the locale passed as an argument to javax.tools.DocumentationTool#getTask will reach the doclet. BTW, is there a test that exercises passing the locale through the CLI?

**Comment by jonathan-gibbons** [comment]
I agree that the test is overweight for the benefit, but I couldn't think of a better way to reduce the number of invocations of javadoc and still have a chance of catching any problem values.  

I was alerted to this test because I did see it occasionally timing out (on my local system), and so the intent was to reduce the execution time to avoid that kind of spurious test failure. I'm open to applying further improvements if we can come up with any good suggestions.  Meanwhile, I propose to integrate this fix as is.

**Comment by pavelrappo** [comment]
> I agree that the test is overweight for the benefit, but I couldn't think of a better way to reduce the number of invocations of javadoc and still have a chance of catching any problem values.

What would such problem values be? Have we seen any? I thought that this test simply verifies that if we put a locale on the one end (options), we will receive that same locale on the other end (doclet). Is there more to this test?

> I was alerted to this test because I did see it occasionally timing out (on my local system), and so the intent was to reduce the execution time to avoid that kind of spurious test failure. I'm open to applying further improvements if we can come up with any good suggestions. Meanwhile, I propose to integrate this fix as is.

The fact that this tests occasionally timed out on your machine surprises me. I mean, it used to take 20 seconds for me. Did it occasionally take more than 300 seconds for you? (AFAIK the default jtreg timeout is 5 minutes.)

**Pull request closed without merging**
