### PR TITLE
8280863: Update build README to reflect that MSYS2 is supported

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Ever since [JDK-8257679](https://bugs.openjdk.java.net/browse/JDK-8257679) was merged in 16, MSYS2 became capable of building a functional JDK on Windows. This PR updates some outdated documentation in building.html and building.md to reflect that change.

I appreciate any reviews, and would like to know how I might be able to improve the wording of both updated docs, if possible.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280863](https://bugs.openjdk.java.net/browse/JDK-8280863): Update build README to reflect that MSYS2 is supported

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7242/head:pull/7242` \
`$ git checkout pull/7242`

Update a local copy of the PR: \
`$ git checkout pull/7242` \
`$ git pull https://git.openjdk.java.net/jdk pull/7242/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7242`

View PR using the GUI difftool: \
`$ git pr show -t 7242`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7242.diff">https://git.openjdk.java.net/jdk/pull/7242.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
The updated wording seems fine to me.

The html file should not be edited by hand, but generated (by pandoc) using the make target `update-build-docs`. If you don't have access to pandoc, I can help you regenerate the file.

It looks like you are trying to reuse an existing and already resolved BugID for this change. That is not possible. A new bug must be filed for each change in OpenJDK.

**Comment by magicus** [comment]
@TheShermanTanker Some comments in no particular order.

* The MSYS2 project calls themselves "MSYS2"; I think it'd be proper to reflect this capitalization/lack of space before the 2. 

* This PR has technical problems. You are trying to reuse the old JBS bug issue. You'll need a new bug entry for the problem you are trying to solve here. If you do not have access to the bug system, let me know and I can help you.

* I have actually a similar fix on a personal branch, where I'm updating several omissions in the build README. However, when I went to try building on an MSYS2 installation with the mainline head, it actually failed.. :-( Have you successfully built on MSYS2 with the mainline JDK?

**Comment by TheShermanTanker** [comment]
> The updated wording seems fine to me.
> 
> The html file should not be edited by hand, but generated (by pandoc) using the make target `update-build-docs`. If you don't have access to pandoc, I can help you regenerate the file.
> 
> It looks like you are trying to reuse an existing and already resolved BugID for this change. That is not possible. A new bug must be filed for each change in OpenJDK.

@erikj79 I don't have access to pandoc, would be appreciated if you could help me out with that!



> @TheShermanTanker Some comments in no particular order.
> 
> * The MSYS2 project calls themselves "MSYS2"; I think it'd be proper to reflect this capitalization/lack of space before the 2.
> * This PR has technical problems. You are trying to reuse the old JBS bug issue. You'll need a new bug entry for the problem you are trying to solve here. If you do not have access to the bug system, let me know and I can help you.
> * I have actually a similar fix on a personal branch, where I'm updating several omissions in the build README. However, when I went to try building on an MSYS2 installation with the mainline head, it actually failed.. :-( Have you successfully built on MSYS2 with the mainline JDK?

@magicus
-Noted, will update the PR to reflect that soon
-I don't have access to the bug system unfortunately, would be great if you could help me file a new one. How do I get access to it for any future PRs?
-Yep, I initially used it since i did want to try building the JDK with gcc, but then found out gcc wasn't supported on Windows, but building it with the default MSVC worked well. Odd that it didn't work for you though, what was the failure?

**Comment by magicus** [comment]
@TheShermanTanker I have now created https://bugs.openjdk.java.net/browse/JDK-8280863 for you. To get access, you need to get Author status in the JDK project, which you can get by submitting repeated high-quality PRs.

Please update the bug title to read "8280863" and the proper format will be filled in for you.

**Comment by TheShermanTanker** [comment]
Updated MSYS2 name and prettify building.md (html left out as requested)

@magicus Thank you!

**Comment by magicus** [comment]
Also, please do not rebase or force-push to a PR; this makes reviewing much harder. Use merge instead. 

https://openjdk.java.net/guide/ is a great start to read if you want to contribute to OpenJDK projects.

**Comment by magicus** [comment]
You don't need to give the `/issue` command. That is only used if you want to resolve multiple issues with one fix. The issue number is extracted from the bug title. Now the same issue is listed twice (!). Try removing it by `/issue remove 8280863`

**Comment by magicus** [comment]
I'm not quite sure of the best way to help you with the html part. I've pushed a fix to https://github.com/magicus/jdk/tree/pull/7242, it is available as commit https://github.com/openjdk/jdk/commit/85024eb1e84425ead40fcc2278ca085ca8fbb5df. Try merging that into your branch.

**Review by magicus — APPROVED** [review]
Looks good now. Continue by giving the `/integrate` command, I'll sponsor it for you.

**Comment by TheShermanTanker** [comment]
@magicus Thank you!

**Pull request closed without merging**
