### PR TITLE
8281061: [s390] JFR runs into assertions while validating interpreter frames

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
s390 implementation requires small changes to avoid running into assertions in debug builds. See JBS for details.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281061](https://bugs.openjdk.java.net/browse/JDK-8281061): [s390] JFR runs into assertions while validating interpreter frames

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to 6d9446a819a470389a4d9ce84f91f9d88ffcb558
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**) ⚠️ Review applies to 6d9446a819a470389a4d9ce84f91f9d88ffcb558

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7312/head:pull/7312` \
`$ git checkout pull/7312`

Update a local copy of the PR: \
`$ git checkout pull/7312` \
`$ git pull https://git.openjdk.java.net/jdk pull/7312/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7312`

View PR using the GUI difftool: \
`$ git pr show -t 7312`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7312.diff">https://git.openjdk.java.net/jdk/pull/7312.diff</a>

</details>

### CODE REVIEW

**Review by RealLucy — CHANGES_REQUESTED** [review]
Changes look good to me. Is there a chance to "officially" run some JFR jtreg tests?

**Comment by TheRealMDoerr** [comment]
I had ran a couple of JFR jtreg tests. But obviously not enough ones. I'll try more. "officially", we don't test on s390 any more.

**Comment by RealLucy** [comment]
Yes, I know. I was hoping for support from IBM / Red Hat. Tyler Steele had been helpful in the past. He seems to have changed name. "backwaterred" is not known anymore.

**Comment by TheRealMDoerr** [comment]
@backwaterred is still there. But now with picture and real name. I've got a lot of the JFR jtreg tests passing, but I'll try to run more over the weekend. Additional testing would still be appreciated, though.

**Comment by backwaterred** [comment]
Hello :wave:. I am happy to do some official testing. I have set up a run for tier1 and jfr tests on our s390 machines. I will let you know what I find.

**Comment by TheRealMDoerr** [comment]
Awesome! Thanks a lot for testing! I have also run all JFR jtreg tests I found and the have passed. So, I will need reviews to proceed. I'll backport to 17u and 11u (together with the other JFR related fixes).

**Review by RealLucy — APPROVED** [review]
Changes look good. 
As you mentioned, jtreg tests are green.

**Review by reinrich — APPROVED** [review]
Hi Martin,

changes look reasonable. `thread_linux_s390.cpp` needs copyright header update.

Cheers, Richard.

**Comment by TheRealMDoerr** [comment]
Copyright updated. Thank you for the reviews!

**Pull request closed without merging**
