### PR TITLE
JDK-8279641: Create manual JTReg tests for Swing accessibility

### PR DESCRIPTION
**Pull request by shurymury**
Tests are based on SwingSet2 application. 
Test instructions are loaded from HTML files. 

See readme for more info.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279641](https://bugs.openjdk.java.net/browse/JDK-8279641): Create manual JTReg tests for Swing accessibility

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6993/head:pull/6993` \
`$ git checkout pull/6993`

Update a local copy of the PR: \
`$ git checkout pull/6993` \
`$ git pull https://git.openjdk.java.net/jdk pull/6993/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6993`

View PR using the GUI difftool: \
`$ git pr show -t 6993`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6993.diff">https://git.openjdk.java.net/jdk/pull/6993.diff</a>

</details>

### CODE REVIEW

**Comment by shurymury** [comment]
@prrace Can you take a look?

**Comment by mrserb** [comment]
An initial question, which look and feel are we expected to test? Do we need to cover the default one, or it is up to someone to pass the correct L&F?

**Comment by prrace** [comment]
> An initial question, which look and feel are we expected to test? Do we need to cover the default one, or it is up to someone to pass the correct L&F?

Need in what context ? Who is "we"  ? 
Test which ever L&Fs your distro wants to certify as accessible. It isn't like a TCK test.
It is optional as far as JDK is concerned but maybe not for some hypothetical consumer of your release.

**Comment by shurymury** [comment]
> An initial question, which look and feel are we expected to test? Do we need to cover the default one, or it is up to someone to pass the correct L&F?

This current implementation does not do anything to support different LAFs.

A test executor can still specify the LAF through -vmoption:"-Dswing.defaultlaf=..." JTReg option.

**Comment by mrserb** [comment]
> This current implementation does not do anything to support different LAFs.
Even if it is do nothing for the L&F by itself it is expected that these test passed on the

**Comment by shurymury** [comment]
> > This current implementation does not do anything to support different LAFs.
> 
> Even if the tests do nothing it is expected that these tests will pass on the default L&Fs like Aqua/Metal. If it is expected to pass on all L&F why not iterate over all installed L&F and prove that?

Changes suggested by this review only cover default LAF by default, unless LAF is specified explicitly. There may be improvements later which would suggest rotating LAFs, that would be a subject of a follow-up reviews.

**Review by mrserb — APPROVED** [review]

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
