### PR TITLE
8330420: Inverted use of DisplayVMOutputToStderr in ostream_exit

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR addresses the inverted clauses in the in ostream_exit. 

Thanks, 
Sonia

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330420](https://bugs.openjdk.org/browse/JDK-8330420): Inverted use of DisplayVMOutputToStderr in ostream_exit (**Bug** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18897/head:pull/18897` \
`$ git checkout pull/18897`

Update a local copy of the PR: \
`$ git checkout pull/18897` \
`$ git pull https://git.openjdk.org/jdk.git pull/18897/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18897`

View PR using the GUI difftool: \
`$ git pr show -t 18897`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18897.diff">https://git.openjdk.org/jdk/pull/18897.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18897#issuecomment-2150130558)

### CODE REVIEW

**Review by jdksjolen — APPROVED** [review]
Oops :-). I'm not very experienced with this code, I hope that someone can declare this to be trivial so that you can merge it without the 24-hour window.

@coleenp, what do you think? Trivial?

Thanks.

**Review by tstuefe — APPROVED** [review]
Hah. Good catch.

I wondered whether we should be concerned about backward compatibilities here, since this seems to be a very old bug and folks may be used to how this works. But this only affects a small time window at the end of VM exit. It's probably okay.

**Comment by tstuefe** [comment]
> Oops :-). I'm not very experienced with this code, I hope that someone can declare this to be trivial so that you can merge it without the 24-hour window.
> 
> @coleenp, what do you think? Trivial?
> 
> Thanks.

I would not push it for 23. Lets give it some cooking time in 24. Even though remote, I worry about backward compatibility issues with programs that expect the JVM output to be the way its now.

**Pull request closed without merging**
