### PR TITLE
JDK-8310321: make JDKOPT_CHECK_CODESIGN_PARAMS more verbose

### PR DESCRIPTION
**Pull request by MBaesken**
We were running into some issues with the configure checks checking the codesign tool. Unfortunately the output is a bit limited and should be enhanced, especially printing what is really called.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310321](https://bugs.openjdk.org/browse/JDK-8310321): make JDKOPT_CHECK_CODESIGN_PARAMS more verbose (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14541/head:pull/14541` \
`$ git checkout pull/14541`

Update a local copy of the PR: \
`$ git checkout pull/14541` \
`$ git pull https://git.openjdk.org/jdk.git pull/14541/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14541`

View PR using the GUI difftool: \
`$ git pr show -t 14541`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14541.diff">https://git.openjdk.org/jdk/pull/14541.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14541#issuecomment-1597273825)

### CODE REVIEW

**Comment by MBaesken** [comment]
A related question, maybe someone has seen this ; we get

configure:150634: calling /usr/bin/codesign -s - /open_jdk/build_dir/configure-support/codesign-testfile
/open_jdk/build_dir/configure-support/codesign-testfile: Operation not permitted
configure:150640: checking if debug mode codesign is possible
configure:150646: result: no

In the checking code (this is already with enhanced output).
Has someone seen the same 'operation not permitted' output and was able to fix this ?

**Comment by MBaesken** [comment]
Hi Erik, the added codesign tool  calls are already printed into the rather verbose config.log.
In the main configure output we see only what we saw before

checking for macosx code signing mode... auto, default
checking for macosx code signing identity... openjdk_codesign, default
checking if codesign with hardened runtime is possible... no
checking if debug mode codesign is possible... no
checking for macosx code signing mode... disabled

**Comment by erikj79** [comment]
> Hi Erik, the added codesign tool calls are already printed into the rather verbose config.log. In the main configure output we see only what we saw before
> 
> checking for macosx code signing mode... auto, default checking for macosx code signing identity... openjdk_codesign, default checking if codesign with hardened runtime is possible... no checking if debug mode codesign is possible... no checking for macosx code signing mode... disabled

With your patch, configure.log and my console has this output:

```
checking for macosx code signing identity... openjdk_codesign, default
configure: check codesign, calling /usr/bin/codesign -s - /Users/erik/dev/jdk/build/macosx-aarch64-debug/configure-support/codesign-testfile
checking if debug mode codesign is possible... yes
checking for macosx code signing mode... debug
```

I think printing the command line used to probe codesign fits in config.log but not in the console output. This is the model used by the builtin macros in autoconf, such as probing for compiler flags. You can achieve this by something like:
```
echo $CODESIGN $PARAMS $CODESIGN_TESTFILE > $AS_MESSAGE_LOG_FD
```

**Comment by MBaesken** [comment]
Hi Erik,  I agree that logging this to config.log is sufficient. I am not sure why this looked different on my setup.
I adjusted the output.

**Review by erikj79 — APPROVED** [review]

**Comment by MBaesken** [comment]
Hi Erik, thanks for the review !

**Pull request closed without merging**
