### PR TITLE
8253740: [PPC64] Minor interpreter cleanup

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Template interpreter on PPC64 can be cleaned up after JDK-8253540:
unlock_object has a parameter check_for_exceptions which is now unused.

In addition to that, restore_interpreter_state is redundant after
call_VM(R4_ARG2, CAST_FROM_FN_PTR(address, InterpreterRuntime::member_name_arg_or_null) because it's already included in call_VM. 

https://bugs.openjdk.java.net/browse/JDK-8253740

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8253740](https://bugs.openjdk.java.net/browse/JDK-8253740): [PPC64] Minor interpreter cleanup

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/385/head:pull/385`
`$ git checkout pull/385`

### CODE REVIEW

**Comment by coleenp** [comment]
This looks good but I also noticed that ppc and s390 pass an extra parameter to InterpreterRuntime::monitorenter() also.

**Comment by TheRealMDoerr** [comment]
That's an interesting point: call_VM(monitorenter) uses check_for_exceptions=true on PPC64 and check_for_exceptions=false on s390. check_for_exceptions=true is default, so it's equivalent to omitting the explicit parameter. So PPC64 is implemented like x86 in this matter.
Seems like we have optimized the exception check out for s390. This should be valid because monitorenter uses JRT_ENTRY_NO_ASYNC and doesn't throw any exception. Note that the JIT compiler's version uses assert(!HAS_PENDING_EXCEPTION, "Should have no exception here") in SharedRuntime::monitor_enter_helper.
I think we could assert that in the interpreter's version and use check_for_exceptions=false on all platforms. It's probably not worth optimizing this, but maybe it'd be a good simplification wrt. complexity and readability of the gererated assembly code.
But that's a bit out of scope for this issue.

**Comment by TheRealMDoerr** [comment]
Hi David,
thanks for reminding me of JVMTI event callbacks. So we need to check s390 code.
And in SharedRuntime::monitor_enter_helper it doesn't make sense to use CHECK macro and then assert(!HAS_PENDING_EXCEPTION, "Should have no exception here").
But this is unrelated to this PPC64 cleanup change.

**Comment by TheRealMDoerr** [comment]
Hi Coleen,
I've removed the explicit check_exceptions=true parameters on PPC64 so it looks more like x86.
I'll take a look at s390 separately.

Hi David,
the assert(!HAS_PENDING_EXCEPTION, "Should have no exception here") is not wrong, but confusing IMHO.

Thanks for looking at this.

**Review by RealLucy — APPROVED** [review]
The change looks good to me. 
Thank you for the cleanup work.

**Pull request closed without merging**
