### PR TITLE
JDK-8326389: [test] improve assertEquals failure output

### PR DESCRIPTION
**Pull request by MBaesken**
Currently assertEquals has in the failure case sometimes confusing output like :

java.lang.RuntimeException: VM output should contain exactly one RTM locking statistics entry for method compiler.rtm.locking.TestRTMTotalCountIncrRate$Test::lock: expected 0 to equal 1
       at jdk.test.lib.Asserts.fail(Asserts.java:634)
       at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)

(I don't think we really expected that for some reason 0 equals 1)
This should be improved.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326389](https://bugs.openjdk.org/browse/JDK-8326389): [test] improve assertEquals failure output (**Bug** - P4)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17952/head:pull/17952` \
`$ git checkout pull/17952`

Update a local copy of the PR: \
`$ git checkout pull/17952` \
`$ git pull https://git.openjdk.org/jdk.git pull/17952/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17952`

View PR using the GUI difftool: \
`$ git pr show -t 17952`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17952.diff">https://git.openjdk.org/jdk/pull/17952.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17952#issuecomment-1956954510)

### CODE REVIEW

**Comment by MBaesken** [comment]
> I think it is a good idea to improve this. I was irritated by that output more than once.
> 
> Maybe a better message would be ... _"..." is not equal to "..."_ ?

Thanks , I adjusted the output .

**Comment by MBaesken** [comment]
now the error output is like
java.lang.RuntimeException: VM output should contain two rtm locking statistics entries for method compiler.testlibrary.rtm.XAbortProvoker::forceAbort: object "0" is not equal to "2"

looks much better to me.

**Review by RealCLanger — APPROVED** [review]
Looks good from my end.

**Comment by MBaesken** [comment]
Hi Christoph, thanks for the review !
Any other opinions/comments/reviews ?

**Comment by jaikiran** [comment]
Hello Matthias, the proposal to improve that failure message looks OK to me. However, I feel that the newly proposed error message isn't too different than what it was earlier. Perhaps, we could do something like:

```diff
diff --git a/test/lib/jdk/test/lib/Asserts.java b/test/lib/jdk/test/lib/Asserts.java
index d503ea8e544..3b45d7f4129 100644
--- a/test/lib/jdk/test/lib/Asserts.java
+++ b/test/lib/jdk/test/lib/Asserts.java
@@ -199,10 +199,11 @@ public static void assertEquals(Object lhs, Object rhs) {
      */
     public static void assertEquals(Object lhs, Object rhs, String msg) {
         if ((lhs != rhs) && ((lhs == null) || !(lhs.equals(rhs)))) {
-            msg = Objects.toString(msg, "assertEquals")
-                    + ": expected " + Objects.toString(lhs)
-                    + " to equal " + Objects.toString(rhs);
-            fail(msg);
+            if (msg != null) {
+                fail(msg);
+            } else {
+                fail("assertEquals expected: " + lhs + " but was: " + rhs);
+            }
         }
     }

```

This is similar to what other test libraries usually report for such failures.

**Comment by RealCLanger** [comment]
> This is similar to what other test libraries usually report for such failures.

But in the case of a non-empty `msg` you would not see the actual values any more which I think could be helpful in a lot of cases...

**Comment by jaikiran** [comment]
Hello Christoph, in that case the `if` block I proposed can be removed. Does the alternate proposed error message look better to you and Matthias?

**Comment by RealCLanger** [comment]
Then maybe it should be

> ```diff
> +            fail((msg == null ? "assertEquals" : msg) + " expected: " + lhs + " but was: " + rhs);
> ```

?

**Comment by jaikiran** [comment]
Hello Christoph, yes that looks fine to me.

**Comment by dholmes-ora** [comment]
Does "expected 0 to equal 1" really cause that much consternation? I just read it as "expected 0 to be equal to 1".

Aren't there existing test libraries that already "standardise" these kinds of utilities that we can emulate? testng? junit?

**Comment by jaikiran** [comment]
Hello David, the updated text that I proposed to Matthias, of the form "expected: ... but was: ..." was borrowed from what junit5 reports for such assertion failures https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionFailureBuilder.java#L174

**Comment by MBaesken** [comment]
> Hello Christoph, yes that looks fine to me.

I adjusted it to the given suggestion.

**Review by jaikiran — APPROVED** [review]
Thank you Matthias. This looks good to me. I haven't checked references for this internal `Asserts` class. Before integrating, please run relevant tests that use this class just to be sure no test relies (and now fails) on the message being printed by the failing assertion.

**Review by RealCLanger — APPROVED** [review]

**Comment by MBaesken** [comment]
Thanks for the reviews !

/integrate

**Comment by MBaesken** [comment]
> Hello David, the updated text that I proposed to Matthias, of the form "expected: ... but was: ..." was borrowed from what junit5

Unfortunately we get now error messages like this 

java.lang.RuntimeException: VM output should contain exactly one rtm locking statistics entry for method compiler.testlibrary.rtm.XAbortProvoker::forceAbort expected: 0 but was: 1

It should be ... expected: 1 but was: 0 ; the assertEquals has this interface `assertEquals(Object lhs, Object rhs, String msg)`  so we have a left hand and a right hand side of a comparison but was is expected and what is what we got is not defined  .

**Pull request closed without merging**
