### PR TITLE
8305085: Suppress removal warning for finalize() from  test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineFinalizer.java

### PR DESCRIPTION
**Pull request by afshin-zafari**
The warning message is suppressed out.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305085](https://bugs.openjdk.org/browse/JDK-8305085): Suppress removal warning for finalize() from  test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineFinalizer.java

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13422/head:pull/13422` \
`$ git checkout pull/13422`

Update a local copy of the PR: \
`$ git checkout pull/13422` \
`$ git pull https://git.openjdk.org/jdk.git pull/13422/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13422`

View PR using the GUI difftool: \
`$ git pr show -t 13422`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13422.diff">https://git.openjdk.org/jdk/pull/13422.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13422#issuecomment-1504945042)

### CODE REVIEW

**Comment by plummercj** [comment]
I'm not  sure of the current plan to actually remove finalize() support, but unless it is going away in 21, it seems this test should remain in place for now.

**Comment by dholmes-ora** [comment]
I agree with @plummercj  this is a test of finalization and so should be kept (with the warning suppressed) until finalization itself is removed.

**Comment by afshin-zafari** [comment]
> The CR synopsis needs to be updated.

The titles updated.

**Review by plummercj — APPROVED** [review]

**Comment by plummercj** [comment]
> The whole test is removed.

I just noticed that the PR description also needs to be updated.

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks.

**Comment by afshin-zafari** [comment]
Thank you David and Chris for your reviews.
/integrate

**Pull request closed without merging**
