### PR TITLE
8321712: C2: "failed: Multiple uses of register" in C2_MacroAssembler::vminmax_fp

### PR DESCRIPTION
**Pull request by sviswa7**
The C2_MacroAssembler::vminmax_fp and evminmax_fp were incorrectly checking for the two USE operand registers to be different and thus resulting in assertion failure.

In x86_64.ad:
```
instruct maxF_reg(legRegF dst, legRegF a, legRegF b, legRegF tmp, legRegF atmp, legRegF btmp) %{
  ...
  effect(USE a, USE b, TEMP tmp, TEMP atmp, TEMP btmp);
  ...
    __ vminmax_fp(Op_MaxV, T_FLOAT, $dst$$XMMRegister, $a$$XMMRegister, $b$$XMMRegister, $tmp$$XMMRegister, $atmp$$XMMRegister, $btmp$$XMMRegister, Assembler::AVX_128bit);
%}

```
Changing the assert in vminmax_fp from:
  assert_different_registers(a, b, tmp, atmp, btmp);
to:
  assert_different_registers(a, tmp, atmp, btmp);
  assert_different_registers(b, tmp, atmp, btmp);
fixes the issue.

Similar change done in evminmax_fp.

Please review.

Best Regards,
Sandhya

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321712](https://bugs.openjdk.org/browse/JDK-8321712): C2: "failed: Multiple uses of register" in C2_MacroAssembler::vminmax_fp (**Bug** - P2)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [43462531](https://git.openjdk.org/jdk/pull/17315/files/43462531712294f422d4bae41eeec24329d26eec)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)
 * [Jatin Bhateja](https://openjdk.org/census#jbhateja) (@jatin-bhateja - **Reviewer**)

### Contributors
 * Volodymyr Paprotski `<vpaprotski@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17315/head:pull/17315` \
`$ git checkout pull/17315`

Update a local copy of the PR: \
`$ git checkout pull/17315` \
`$ git pull https://git.openjdk.org/jdk.git pull/17315/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17315`

View PR using the GUI difftool: \
`$ git pr show -t 17315`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17315.diff">https://git.openjdk.org/jdk/pull/17315.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17315#issuecomment-1882017519)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Should we "short cut" code when registers are the same?

**Comment by jatin-bhateja** [comment]
> Should we "short cut" code when registers are the same?

Hi @sviswa7 , An identity transformation may be useful here to prevent generating MaxF/D in case both the arguments are same.

**Comment by eme64** [comment]
Also: do you have a regression test for this?

**Comment by sviswa7** [comment]
@vnkozlov @jatin-bhateja Your review comments are addressed, please take a look.

**Comment by eme64** [comment]
@sviswa7 but is the "same address" not an indication of a missing ideal transformation? Hence, the assert may actually be ok, and the root cause be fixed in the ideal transformation. I think this maybe what @jatin-bhateja was suggesting.

**Comment by sviswa7** [comment]
@eme64 Probably, but my goal here is limited. We have to fix this PR within RDP2 i.e. asap. That is why I kept the changes to minimum. On Vladimir's request I have added a minimum change to handle the case when a and b are same.

**Comment by eme64** [comment]
@sviswa7 Ok, I understand. But a regression test would still be good. We should just reduce the regression test attached to https://bugs.openjdk.org/browse/JDK-8322090, @TobiHartmann mentioned it on JIRA.

I guess we can also file a follow up RFE to improve the Ideal transformations.

**Comment by sviswa7** [comment]
@eme64 No, I don't have a regression test for this. I followed the ctw.sh mechanism provided in the bug report by Roland Westrelin to reproduce and verify.

**Review by vnkozlov — COMMENTED** [review]
Actually Ideal transformation fix could be smaller than these changes. You will not need to change platform specific code. Hmm, may be NaN values could be a problem. Have to check for them as we do in other operations. Even suggested "short cut" (use move) could be wrong for NaN.

Okay, lets go to the first version of these changes: only assert fix. And file separate RFE to make changes in Ideal graph.

And we need regression test as @eme64 pointed.

**Comment by sviswa7** [comment]
RFE filed: https://bugs.openjdk.org/browse/JDK-8323429

**Comment by sviswa7** [comment]
@vnkozlov I have reverted the changes to just asserts and added a test case to the existing test. The new test case fails without this PR and passes with the PR changes.
@eme64 I have verified that [Test_276.java](https://bugs.openjdk.org/secure/attachment/107681/Test_276.java) fails without this PR with the given arguments in the [JBS Bug Entry](https://bugs.openjdk.org/browse/JDK-8322090) and passes with the PR changes. 
I have filed an [RFE](https://bugs.openjdk.org/browse/JDK-8323429) for future optimization as requested.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by sviswa7** [comment]
Thanks a lot @vnkozlov.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. Thanks for including a test. I submitted some testing and will report back once it passed.

**Review by eme64 — APPROVED** [review]
@sviswa7 Thanks for filing the follow up RFE!

Nice, the reproducer fails without, and passes with your patch :)

I also verified that the reproducer `Test_276.java` fails without, and passes with the patch.

==> LGTM :rocket:

**Comment by sviswa7** [comment]
Thanks a lot @eme64 and @TobiHartmann for the review, I will wait for the test results before integrating.

**Review by jatin-bhateja — APPROVED** [review]
Thanks for filing RFE, LGTM

**Comment by sviswa7** [comment]
Thanks a lot @jatin-bhateja for the review.

**Comment by TobiHartmann** [comment]
Testing all passed.

**Pull request closed without merging**
