### PR TITLE
JDK-8292715: Cleanup Problemlist

### PR DESCRIPTION
**Pull request by prsadhuk**
Cleanup of Problemlist

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292715](https://bugs.openjdk.org/browse/JDK-8292715): Cleanup Problemlist

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9963/head:pull/9963` \
`$ git checkout pull/9963`

Update a local copy of the PR: \
`$ git checkout pull/9963` \
`$ git pull https://git.openjdk.org/jdk pull/9963/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9963`

View PR using the GUI difftool: \
`$ git pr show -t 9963`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9963.diff">https://git.openjdk.org/jdk/pull/9963.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]
Approved on the understanding (since you did not say) that you have verified all de-listed tests do pass.

**Comment by prsadhuk** [comment]
> Approved on the understanding (since you did not say) that you have verified all de-listed tests do pass.

Since I listed the mach5 job in the closed PR running all tests both open and closed which has passed so I did not mention explicitly here.

**Pull request closed without merging**
