### PR TITLE
8283223: gc/stringdedup/TestStringDeduplicationFullGC.java#Parallel failed with "RuntimeException: String verification failed"

### PR DESCRIPTION
**Pull request by lkorinth**
I have tried to reproduce the problem by adding load to the system but I have failed. Thomas have reproduced similar problems by adding some fairly large delays in the string deduplication service thread (https://bugs.openjdk.org/browse/JDK-8275684). In this patch I added the `systemLoad()` method and the `minMax()` method so that we can log the load when the problem appears. If the failure reappears (I can see no resent failures). We can use those methods to make the test pass on too high load.

`getSystemLoadAverage()` is a bit blunt and gives an average over one minute, but ought to work if we eventually would like to silence test failures on over-commissioned machines.

Do you think this is okay, or should I change the test to directly skip the testcase instead of adding the load log on failure, maybe that is better?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283223](https://bugs.openjdk.org/browse/JDK-8283223): gc/stringdedup/TestStringDeduplicationFullGC.java#Parallel failed with "RuntimeException: String verification failed" (**Bug** - P2)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18327/head:pull/18327` \
`$ git checkout pull/18327`

Update a local copy of the PR: \
`$ git checkout pull/18327` \
`$ git pull https://git.openjdk.org/jdk.git pull/18327/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18327`

View PR using the GUI difftool: \
`$ git pr show -t 18327`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18327.diff">https://git.openjdk.org/jdk/pull/18327.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18327#issuecomment-1999830581)

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm. Thanks for adding diagnosis code.

**Comment by lkorinth** [comment]
Let us see if github actions clear up after this merge

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by lkorinth** [comment]
Thanks Thomas and Kim!

**Pull request closed without merging**
