### PR TITLE
8346712: Remove com/sun/net/httpserver/TcpNoDelayNotRequired.java test

### PR DESCRIPTION
**Pull request by MBaesken**
Here [JDK-8333864](https://bugs.openjdk.org/browse/JDK-8333864) it has been discussed that the test TcpNoDelayNotRequired.java is not giving us much benefit these days so it could be removed.
From 8333864
"I suppose we could remove this test, and label the original issue as noreg-perf. The test does nothing but verify that its run time is below a certain threshold anyway."

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8346712](https://bugs.openjdk.org/browse/JDK-8346712): Remove com/sun/net/httpserver/TcpNoDelayNotRequired.java test (**Bug** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22846/head:pull/22846` \
`$ git checkout pull/22846`

Update a local copy of the PR: \
`$ git checkout pull/22846` \
`$ git pull https://git.openjdk.org/jdk.git pull/22846/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22846`

View PR using the GUI difftool: \
`$ git pr show -t 22846`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22846.diff">https://git.openjdk.org/jdk/pull/22846.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22846#issuecomment-2556812294)
</details>

### CODE REVIEW

**Review by djelinski — APPROVED** [review]
Fine by me.

**Review by RealLucy — APPROVED** [review]
LGTM:
It's always good to remove stuff that potentially adds confusion instead of adding value.

**Review by jaikiran — APPROVED** [review]
I think this is reasonable.

**Comment by MBaesken** [comment]
Thanks for the reviews !

/integrate

**Pull request closed without merging**
