### PR TITLE
8307926: Support byte-sized atomic bitset operations

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to add support Atomic byte-sized bitset operations.
The existing default implementation using cmpxchg already (by accident) works
on such values, because cmpxchg supports byte-sized operations.  Any future
platform specializations of these operations will need to deal with this size
too.

The changes consist of updating the requirements documentation for the
operations and adding gtests for the newly supported size.

Testing:
mach5 tier1-3
GHA testing

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307926](https://bugs.openjdk.org/browse/JDK-8307926): Support byte-sized atomic bitset operations

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13952/head:pull/13952` \
`$ git checkout pull/13952`

Update a local copy of the PR: \
`$ git checkout pull/13952` \
`$ git pull https://git.openjdk.org/jdk.git pull/13952/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13952`

View PR using the GUI difftool: \
`$ git pr show -t 13952`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13952.diff">https://git.openjdk.org/jdk/pull/13952.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13952#issuecomment-1545500146)

### CODE REVIEW

**Review by xmas92 — APPROVED** [review]
lgtm.

Is there some reason this requirement cannot be statically asserted?

**Review by coleenp — APPROVED** [review]
Thank you!

**Comment by kimbarrett** [comment]
> Is there some reason this requirement cannot be statically asserted?

We don't static_assert the size of T here for the same reason we don't do so elsewhere in this class.  Documenting the supported sizes is a requirement that the platform implementation support those sizes.  A static_assert in the public API doesn't do anything to verify the platform implementation meets that requirement.

**Comment by kimbarrett** [comment]
Thanks for reviews, @xmas92 and @coleenp .

**Comment by dholmes-ora** [comment]
Sorry but I don't see how this can work in general for byte. Yes you can update an individual byte as part of a CAS, but on some platforms the address may need to be aligned to 32-bit boundary. It also requires that the byte to be updated is surrounded by other writeable bytes, and that byte-tearing is not an issue. ???

**Comment by dholmes-ora** [comment]
Correction "byte-tearing" is not an issue - the CAS will only update the value of the byte in question. If any other byte is modified concurrently then the CAS will fail.

**Pull request closed without merging**
