### PR TITLE
8282143: Objects.requireNonNull should be ForceInline

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

`Objects.requireNonNull` may fail to be inlined. The call is expensive and may lead to objects escaping to the heap while the null check is cheap and is often elided. I have observed this when using the vector API when a call to `Objects.requireNonNull` leads to vectors being materialised in a hot loop.

Should the other `requireNonNull` be `ForceInline` as well?

Thank you very much.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282143](https://bugs.openjdk.java.net/browse/JDK-8282143): Objects.requireNonNull should be ForceInline

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7543/head:pull/7543` \
`$ git checkout pull/7543`

Update a local copy of the PR: \
`$ git checkout pull/7543` \
`$ git pull https://git.openjdk.java.net/jdk pull/7543/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7543`

View PR using the GUI difftool: \
`$ git pr show -t 7543`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7543.diff">https://git.openjdk.java.net/jdk/pull/7543.diff</a>

</details>

### CODE REVIEW

**Comment by ExE-Boss** [comment]
> Should the other `requireNonNull` be `ForceInline` as well?

Probably yes.

**Comment by rose00** [comment]
Very simple methods like this are almost always inlined, but I suppose there are depth cutoffs that may cause inlining to fail.

Yes, it should always be inlined.  The optimizer works hard to track null-ness conditions, and making this call go out of line "breaks the thread of thought" in the optimizer's reasoning about null.

Yes, both versions of `O::cNN` should be marked this way; the only difference is in how the exception is constructed.

(A similar point goes for index-checking functions, which are also force-inlined so that simple index checks of the form `i*K+L <u R` can be strength-reduced by loop iteration range splitting.)

**Comment by PaulSandoz** [comment]
`Objects.requireNonNull` is also used on the critical path of VarHandles, and other places in `j.l.invoke` so I think this is generally beneficial beyond use by the Vector API.

**Comment by merykitty** [comment]
I have applied the change for the other one as well. Thanks a lot.

**Comment by ExE-Boss** [comment]
I think `@ForceInline` should also be applied to the overload that takes the message supplier, and probably also `requireNonNullElse` and `requireNonNullElseGet`.

**Review by PaulSandoz — APPROVED** [review]

**Comment by merykitty** [comment]
Thanks a lot for your reviews, do I need a second review for this?
@ExE-Boss IMO generally we only decorate `ForceInline` on functions of which inlining is crucial since inlining decision is a hard problem and often not solvable from the local point of view, especially from the callee's one.
/integrate

**Comment by PaulSandoz** [comment]
@merykitty it's good.
/sponsor

**Pull request closed without merging**
