### PR TITLE
8315877: ProblemList vmTestbase/nsk/jvmti/InterruptThread/intrpthrd003/TestDescription.java on macosx-aarch64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial fixes to ProblemList some tests:
- [JDK-8315877](https://bugs.openjdk.org/browse/JDK-8315877) ProblemList vmTestbase/nsk/jvmti/InterruptThread/intrpthrd003/TestDescription.java on macosx-aarch64
- [JDK-8315879](https://bugs.openjdk.org/browse/JDK-8315879) ProblemList java/awt/PopupMenu/PopupMenuLocation.java on macosx-aarch64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8315877](https://bugs.openjdk.org/browse/JDK-8315877): ProblemList vmTestbase/nsk/jvmti/InterruptThread/intrpthrd003/TestDescription.java on macosx-aarch64 (**Sub-task** - P4)
 * [JDK-8315879](https://bugs.openjdk.org/browse/JDK-8315879): ProblemList java/awt/PopupMenu/PopupMenuLocation.java on macosx-aarch64 (**Sub-task** - P4)

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15627/head:pull/15627` \
`$ git checkout pull/15627`

Update a local copy of the PR: \
`$ git checkout pull/15627` \
`$ git pull https://git.openjdk.org/jdk.git pull/15627/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15627`

View PR using the GUI difftool: \
`$ git pr show -t 15627`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15627.diff">https://git.openjdk.org/jdk/pull/15627.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15627#issuecomment-1710707422)

### CODE REVIEW

**Review by azvegint — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Review by calvinccheung — APPROVED** [review]
Looks good and trivial.

**Pull request closed without merging**
