### PR TITLE
8296645: org.openjdk.bench.javax.tools.Javac leaves class files in current directory

### PR DESCRIPTION
**Pull request by shipilev**
```
$ java -jar ../build/linux-x86_64-server-release/images/test/micro/benchmarks.jar org.openjdk.bench.javax.tools.Javac.testCompile -f 1 -r 1s -w 1s
...

$ ls
Apan.class
``` 

Additional testing:
 - [x] Eyeballing CWD and `/tmp` contents after the benchmark -- no leftovers

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296645](https://bugs.openjdk.org/browse/JDK-8296645): org.openjdk.bench.javax.tools.Javac leaves class files in current directory

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11055/head:pull/11055` \
`$ git checkout pull/11055`

Update a local copy of the PR: \
`$ git checkout pull/11055` \
`$ git pull https://git.openjdk.org/jdk pull/11055/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11055`

View PR using the GUI difftool: \
`$ git pr show -t 11055`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11055.diff">https://git.openjdk.org/jdk/pull/11055.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Any takers? :)

**Comment by shipilev** [comment]
Anyone? :)

**Review by cl4es — APPROVED** [review]
LGTM

**Review by jaikiran — APPROVED** [review]
Looks fine to me. The copyright year will need an update.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
