### PR TITLE
8295124: Atomic::add to pointer type may return wrong value

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the handling of Atomic pointer arithmetic. When
the value being modified is a pointer `P*`, the type of the value in the
destination passed to the platform operation is `const char*`, so a pointer
type whose pointee is size 1. This allows the platform operation to just treat
the arithmetic as a simple byte adjustment.

To demonstrate the problem described in the bug (possible incorrect result for
Atomic pointer arithmetic) and show that it is now fixed, this change also
includes some gtests for Atomic operations, including pointer arithmetic which
fails before the change and succeeds after.

Testing: mach5 tier1-3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295124](https://bugs.openjdk.org/browse/JDK-8295124): Atomic::add to pointer type may return wrong value

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [e44e81cd](https://git.openjdk.org/jdk/pull/10667/files/e44e81cdf086f5b5762f9f509ccc2735206c2d13)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [e44e81cd](https://git.openjdk.org/jdk/pull/10667/files/e44e81cdf086f5b5762f9f509ccc2735206c2d13)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10667/head:pull/10667` \
`$ git checkout pull/10667`

Update a local copy of the PR: \
`$ git checkout pull/10667` \
`$ git pull https://git.openjdk.org/jdk pull/10667/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10667`

View PR using the GUI difftool: \
`$ git pr show -t 10667`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10667.diff">https://git.openjdk.org/jdk/pull/10667.diff</a>

</details>

### CODE REVIEW

**Comment by kimbarrett** [comment]
Poke - any takers.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by coleenp — APPROVED** [review]
I get it!  Looks good.

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @coleenp for reviews.

**Pull request closed without merging**
