### PR TITLE
8326941: Remove StringUTF16::isBigEndian

### PR DESCRIPTION
**Pull request by minborg**
This PR proposes to remove the native method `StringUTF16::isBigEndian` and its corresponding C implementation and instead rely on the `jdk.internal.misc.Unsafe::isBigEndian` method.

This PR passes tier1-3 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326941](https://bugs.openjdk.org/browse/JDK-8326941): Remove StringUTF16::isBigEndian (**Enhancement** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18348/head:pull/18348` \
`$ git checkout pull/18348`

Update a local copy of the PR: \
`$ git checkout pull/18348` \
`$ git pull https://git.openjdk.org/jdk.git pull/18348/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18348`

View PR using the GUI difftool: \
`$ git pr show -t 18348`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18348.diff">https://git.openjdk.org/jdk/pull/18348.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18348#issuecomment-2004034644)

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
Nice Cleanup.

**Comment by cl4es** [comment]
Does this change how early `Unsafe` is initialized, and does it in turn have dependencies on `StringUTF16`? `StringUTF16` is loaded very early, especially if `-XX:-CompactStrings` is supplied and I would assume the only reason this was added in the first place was to avoid some bootstrapping issue.

**Comment by minborg** [comment]
> Does this change how early `Unsafe` is initialized, and does it in turn have dependencies on `StringUTF16`? `StringUTF16` is loaded very early, especially if `-XX:-CompactStrings` is supplied and I would assume the only reason this was added in the first place was to avoid some bootstrapping issue.

I am unsure of the initialization order. Unsafe was added 2015, a few weeks before the explicit C code was added. This might indicate the previous solution was deliberate or it might be the case, the new method was not known by the author at the time.

**Comment by cl4es** [comment]
> Initialization order

```java -Xlog:class+init -XX:-CompactStrings -version```:

Before:
```
[0.015s][info][class,init] 71 Initializing 'java/lang/StringUTF16' (0x000000ff00063a20) by thread "main"
[0.015s][info][class,init] 72 Initializing 'jdk/internal/util/ArraysSupport' (0x000000ff00063c20) by thread "main"
[0.015s][info][class,init] 73 Initializing 'jdk/internal/misc/Unsafe' (0x000000ff00050de0) by thread "main"
```

After:
```[0.018s][info][class,init] 71 Initializing 'java/lang/StringUTF16' (0x0000000400063a30) by thread "main"
[0.018s][info][class,init] 72 Initializing 'jdk/internal/misc/Unsafe' (0x0000000400050de0) by thread "main"
[0.018s][info][class,init] 73 Initializing 'jdk/internal/util/ArraysSupport' (0x0000000400063c30) by thread "main"
```
Seems the order only changes subtly. 

> Unsafe was added 2015, a few weeks before the explicit C code was added. This might indicate the previous solution was deliberate or it might be the case, the new method was not known by the author at the time.

`sun.misc.Unsafe::isBigEndian` has existed longer, and was removed when `jdk.internal.misc.Unsafe` was added. `StringUTF16::isBigEndian` was added by JEP 254 by a group of people who I believe would have been well aware of its existence. It doesn't seem that having `StringUTF16` have a `<clinit>` dependency on `Unsafe` is problematic today, though. Perhaps `sun.misc.Unsafe` did more weird things back in 2015.

**Comment by minborg** [comment]
Thanks for the clarifications @cl4es!

**Pull request closed without merging**
