### PR TITLE
8254976: Re-enable swing jtreg tests which were broken due to samevm mode

### PR DESCRIPTION
**Pull request by prsadhuk**
Few tests were problemlisted in an earlier test sprint due to those failing in mach5 testing.
It was found out that these test were failing due to those jtreg tests being run in same vm mode.
The bug was fixed by the adding client tests to the "othervm.dirs" in the TEST.ROOT so there is no need to keep those tests problem listed.
mach5 job running these tests was ok. Link in JBS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ⏳ (5/5 running) | ⏳ (2/2 running) | ⏳ (2/2 running) |

### Issue
 * [JDK-8254976](https://bugs.openjdk.java.net/browse/JDK-8254976): Re-enable swing jtreg tests which were broken due to samevm mode

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to 2354ad1cee6fd1f176d862fb231bd8c8e8b40fb9

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/733/head:pull/733`
`$ git checkout pull/733`

### CODE REVIEW

**Comment by prrace** [comment]
Since this re-enables quite a few tests,  please can we run the jtreg desktop tests several times on each platform to be
sure it is at least moderately stable. If we get breakage out of this it there'll be a bunch of candidates !

**Comment by prsadhuk** [comment]
I have rerun the open jtreg tests several times (link in JBS) and those are stable apart from one test which I have added back.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
