### PR TITLE
8277863: Deprecate sun.misc.Unsafe methods that return offsets

### PR DESCRIPTION
**Pull request by AlanBateman**
Deprecate the sun.misc.Unsafe methods that return field offsets. These method are an impediment to possible future changes. Layout may not be fixed in the future, the VM should be allowed to re-layout dynamically based on patterns of usage. We also have the issue of libraries using these methods to get offsets (sometimes of classes with the same layout as JDK classes) so they can directly access the fields of privileged classes. It's untenable for libraries to rely on this going forward.

The java.lang.invoke.VarHandle API (added in Java 9) provides a strongly typed reference to a variable that is a safe and a much better alternative to many cases that use these methods. Deprecating these method provides a gentle nudge in that directory. Once the Panama memory APIs are permanent then we can look at terminally deprecating and removing these methods, along with the accessors.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8277863](https://bugs.openjdk.java.net/browse/JDK-8277863): Deprecate sun.misc.Unsafe methods that return offsets
 * [JDK-8278223](https://bugs.openjdk.java.net/browse/JDK-8278223): Deprecate sun.misc.Unsafe methods that return offsets (**CSR**)

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6700/head:pull/6700` \
`$ git checkout pull/6700`

Update a local copy of the PR: \
`$ git checkout pull/6700` \
`$ git pull https://git.openjdk.java.net/jdk pull/6700/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6700`

View PR using the GUI difftool: \
`$ git pr show -t 6700`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6700.diff">https://git.openjdk.java.net/jdk/pull/6700.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — COMMENTED** [review]
Slowly chipping away... but we are getting really close to being able to deprecate all the unsafe accessor methods.

Did you also consider the method `staticFieldBase` and the field `INVALID_FIELD_OFFSET`? I think those could also be included since the aim is to discourage unsafe access to fields of objects.

**Comment by AlanBateman** [comment]
Yes, we have to keep chipping away at this. Most of the on-heap usages that I found could have been replaced with VarHandles a long time ago but many of these projects are still building to old JDK releases and maybe MR JARs are still problematic in the build. The great progress on the memory API in Project Panama means it won't be long before those accessors are needed for off-heap. So yes, a few more releases and we should be able to make more progress.

I toyed with including staticFieldBase but I didn't find anything like the usage as the offset methods. Easy to include if you think it's worth doing.

**Comment by PaulSandoz** [comment]
> I toyed with including staticFieldBase but I didn't find anything like the usage as the offset methods. Easy to include if you think it's worth doing.

Yes, I think you should include it, it's part of this set of functionality (since base is used in conjunction with offsets)

**Comment by AlanBateman** [comment]
> Yes, I think you should include it, it's part of this set of functionality (since base is used in conjunction with offsets)

Okay, done.

**Review by mlchung — APPROVED** [review]
It's okay to leave `INVALID_FIELD_OFFSET` as is as it's also for `arrayBaseOffset`.

**Review by PaulSandoz — APPROVED** [review]

**Pull request closed without merging**
