### PR TITLE
8323680: SA PointerFinder code can do a better job of leveraging existing code to determine if an address is in the TLAB

### PR DESCRIPTION
**Pull request by plummercj**
In PointerFinder.java we have some code to determine if a pointer is in a TLAB, but it only executes for the SerialGC. It should work for all GCs, so I moved the code out of the SerialGC block.

I also cleaned up the printing in PointerLocation. java a bit so when not using verbose mode not as much info about the tlab address is printed. This is consistent with other addresses, such as java stack addresses, which is what I modeled this change on.

It's hard to test this change since it is hard to consistently get an address to be in the tlab. I wrote a little test program that just sits in a loop doing allocations. I attached to it with clhsdb and ran the threadcontext command, which does a fincpc on each register. About half the time the main thread was suspended in a frame where some registers where pointing into the tlab, and I confirmed this was the case for both SerialGC and G1. Here's an example of one register with verbose off and verbose on:

rsi: 0x000000008a5d4448: In TLAB for thread "main" sun.jvm.hotspot.runtime.JavaThread@0x00007ffa24029000

rsi: 0x000000008a5d4448: In TLAB for thread ("main" #1 prio=5 tid=0x00007ffa24029000 nid=25392 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_in_java
)  [0x000000008a5d4448,0x000000008ab724b8,0x000000008b0c0250,{0x000000008b0c0490})

For testing I ran all tier1, tier2, and tier5 svc tests (still in progress)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323680](https://bugs.openjdk.org/browse/JDK-8323680): SA PointerFinder code can do a better job of leveraging existing code to determine if an address is in the TLAB (**Enhancement** - P4)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**) ⚠️ Review applies to [ed620194](https://git.openjdk.org/jdk/pull/17494/files/ed6201942007f7c319caa343ba078fdc841d2bb0)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17494/head:pull/17494` \
`$ git checkout pull/17494`

Update a local copy of the PR: \
`$ git checkout pull/17494` \
`$ git pull https://git.openjdk.org/jdk.git pull/17494/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17494`

View PR using the GUI difftool: \
`$ git pr show -t 17494`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17494.diff">https://git.openjdk.org/jdk/pull/17494.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17494#issuecomment-1899352779)

### CODE REVIEW

**Comment by plummercj** [comment]
Ping! I still need 2 reviews. Thanks!

**Review by kevinjwalls — APPROVED** [review]
Looks good to me.

(Not critical, but maybe PointerLocation doesn't need the boolean inTlab.  It could use that its tlab is not null, like the isInHeap/stack/metadata checks that something is not null.)

**Comment by plummercj** [comment]
> (Not critical, but maybe PointerLocation doesn't need the boolean inTlab. It could use that its tlab is not null, like the isInHeap/stack/metadata checks that something is not null.)

Ok. I made that change.

**Comment by plummercj** [comment]
Thanks for the review Kevin. Can I get one more review please? Thanks!

**Review by sspitsyn — APPROVED** [review]
The fix looks good.

**Comment by plummercj** [comment]
Thanks for the reviews Kevin and Seguei!

/integrate

**Pull request closed without merging**
