### PR TITLE
8327049: Only export debug.cpp functions on Windows

### PR DESCRIPTION
**Pull request by magicus**
This is a partial backout of [JDK-8326509](https://bugs.openjdk.org/browse/JDK-8326509). It turned out that starting to export the functions from debug.cpp could have unintended consequences in certain circumstances, so revert back to the original situation where these functions were only exported on Windows.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327049](https://bugs.openjdk.org/browse/JDK-8327049): Only export debug.cpp functions on Windows (**Bug** - P2)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18062/head:pull/18062` \
`$ git checkout pull/18062`

Update a local copy of the PR: \
`$ git checkout pull/18062` \
`$ git pull https://git.openjdk.org/jdk.git pull/18062/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18062`

View PR using the GUI difftool: \
`$ git pr show -t 18062`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18062.diff">https://git.openjdk.org/jdk/pull/18062.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18062#issuecomment-1971140418)

### CODE REVIEW

**Review by TheShermanTanker — APPROVED** [review]
Wouldn't it be better to do WINDOWS\_ONLY(JNIEXPORT) instead? Other than that, +1

**Comment by magicus** [comment]
I guess that is mostly a matter of style, but sure, it is a bit shorter. And coming from you, I assume it is more relevant wrt a non-Microsoft-toolchain Windows port.

**Comment by TheShermanTanker** [comment]
> I guess that is mostly a matter of style, but sure, it is a bit shorter. And coming from you, I assume it is more relevant wrt a non-Microsoft-toolchain Windows port.

Not at all, was just trying to help out since there are utility macros in HotSpot that make this sort of thing less cumbersome :)

**Review by TheShermanTanker — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
I had expected to see an actual reversion to the undef of JNIEXPORT but this will do albeit more extensive a change.

**Comment by dholmes-ora** [comment]
Actually what about non-Windows non-gcc? Shouldn't this only affect Linux?

**Comment by magicus** [comment]
My takeaway from the problem we encountered was that contrary to the assumption in [JDK-8326509](https://bugs.openjdk.org/browse/JDK-8326509), it is better *not* to export these functions on all platforms, but only do so where it is required by the debugger, i.e. on Windows. In fact, since we are still exporting them on Windows, we can still run into the same kind on conflict -- we have just limited the exposure surface to Windows-only. But there seems to be no way around this due to limitations in the Visual Studio debugger. :-(

So this will restore the functionality that has been for a long time -- the debug functions are only exported on Windows. (Previously, this was achieved by marking the functions JNIEXPORT, but leaving them out from the symbol files, which made them non-exported on all compilers except visual studio).

**Comment by magicus** [comment]
> I had expected to see an actual reversion to the undef of JNIEXPORT but this will do albeit more extensive a change.

To me, `#undef` is really the worst kind of hack that should be used only when you do not have full control over the source code where it is defined. Arbitrarily removal of macro definitions makes it much harder to reason about the source code.

It was put in place just to get ahead of the mapfile removal with minimal changes, and the intention to remove it as soon as possible.

**Comment by eme64** [comment]
> unintended consequences in certain circumstances

Can you say what these are? Could not find any info about that in any related JBS or GitHub places.

**Comment by magicus** [comment]
> Can you say what these are? Could not find any info about that in any related JBS or GitHub places.

We spotted a problem with an Oracle-internal testing tool that exported a function named `debug`, which ended up calling the exported `debug` function from Hotspot instead. But the problem could theoretically apply to any code out there that links with libjvm.so and has conflicting symbols defined. Normally, the symbols exported from Hotspot are named `JVM_<foo>` to minimize the risk of this theoretical conflict becoming real, but the functions in debug.cpp has much shorter and more common names (for simple usage in the debugger), so the risk of actual conflicts are much higher.

**Review by eme64 — APPROVED** [review]
Ah ok. Sounds reasonable, thanks for the explanation!

**Pull request closed without merging**
