### PR TITLE
8310019: MIPS builds are broken after JDK-8304913

### PR DESCRIPTION
**Pull request by RogerRiggs**
Add mipsel and mips64el to the Architecture enum.
(Later to be backported to JDK 21)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310019](https://bugs.openjdk.org/browse/JDK-8310019): MIPS builds are broken after JDK-8304913 (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [4c18377a](https://git.openjdk.org/jdk/pull/14471/files/4c18377a78b7d22b8fa41dc36c934794974b3877)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [ce8d31fa](https://git.openjdk.org/jdk/pull/14471/files/ce8d31fae1f4e607788622436b937ed1d0b78cca)
 * [Ao Qi](https://openjdk.org/census#aoqi) (@theaoqi - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14471/head:pull/14471` \
`$ git checkout pull/14471`

Update a local copy of the PR: \
`$ git checkout pull/14471` \
`$ git pull https://git.openjdk.org/jdk.git pull/14471/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14471`

View PR using the GUI difftool: \
`$ git pr show -t 14471`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14471.diff">https://git.openjdk.org/jdk/pull/14471.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14471#issuecomment-1591437076)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
Looking at how other platforms do it, I think this patch is incomplete. See e.g. ARM32 patch: https://github.com/openjdk/jdk/commit/83c096d6e20cd6e1164bc666df1be197a10431eb

**Review by shipilev — APPROVED** [review]
Looks fine. We want/need the original reporter to confirm it works now?

**Comment by theaoqi** [comment]
> Looks fine. We want/need the original reporter to confirm it works now?

Build `linux-mips64el-zero-release` passed after the fix. I'm not the original reporter.

**Review by theaoqi — APPROVED** [review]
Thanks, the test passed.

**Comment by vpa1977** [comment]
[mipsel](https://buildd.debian.org/status/fetch.php?pkg=openjdk-21&arch=mipsel&ver=21%7E27ea-4&stamp=1687097215&raw=0) and [mips64el](https://buildd.debian.org/status/fetch.php?pkg=openjdk-21&arch=mips64el&ver=21%7E27ea-4&stamp=1687090389&raw=0) builds were successful after applying this MR patch.

**Comment by shipilev** [comment]
Hey @RogerRiggs, could you ask bots to backport to JDK 21? I'll then review that one as well.

**Comment by RogerRiggs** [comment]
@shipilev Thanks for the reminder; 
Backport PR https://github.com/openjdk/jdk21/pull/40

**Pull request closed without merging**
