### PR TITLE
8262998: Vector API intrinsincs should not modify IR when bailing out

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

While I was learning [1], I found similar bugs in Vector API.
The reason is the same that make_unsafe_address [2][3] may modify IR when bailing out.
Let's fix it.

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/pull/2775/
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/vectorIntrinsics.cpp#L782
[3] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/vectorIntrinsics.cpp#L612

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262998](https://bugs.openjdk.java.net/browse/JDK-8262998): Vector API intrinsincs should not modify IR when bailing out

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2823/head:pull/2823`
`$ git checkout pull/2823`

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Good catch. Looks good to me.

**Comment by DamonFool** [comment]
> Good catch. Looks good to me.

Thanks @TobiHartmann for your review.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by DamonFool** [comment]
> Looks good.

Thanks @iwanowww .

**Pull request closed without merging**
