### PR TITLE
JDK-8322943: runtime/CompressedOops/CompressedClassPointers.java fails on AIX

### PR DESCRIPTION
**Pull request by JoKern65**
Even after recent fixes like
https://bugs.openjdk.org/browse/JDK-8305765
the test runtime/CompressedOops/CompressedClassPointers.java fails on AIX.

This error results from the fact, that on AIX the shmat() allocation granularity is 256MB instead of the standard Pagesize (4KB or 64KB).

Because my first proposal (PR 17708) of introducing a new method os::vm_shm_allocation_granularity() in the shared hotspot code was rejected I now encapsulate the difference in ifdef AIX brackets.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322943](https://bugs.openjdk.org/browse/JDK-8322943): runtime/CompressedOops/CompressedClassPointers.java fails on AIX (**Bug** - P4)

### Reviewers
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer) ⚠️ Review applies to [0aa55745](https://git.openjdk.org/jdk/pull/18105/files/0aa55745a0323ccad9141eacb0bd3b5cc9d7ed2c)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18105/head:pull/18105` \
`$ git checkout pull/18105`

Update a local copy of the PR: \
`$ git checkout pull/18105` \
`$ git pull https://git.openjdk.org/jdk.git pull/18105/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18105`

View PR using the GUI difftool: \
`$ git pr show -t 18105`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18105.diff">https://git.openjdk.org/jdk/pull/18105.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18105#issuecomment-1976238932)

### CODE REVIEW

**Review by lgxbslgx — APPROVED** [review]
I don't have a AIX device to run the related test. But the patch looks good.

A trivially possible problem is that it seems not so good to repeat the same comments in all the code places. But I don't have a better alternative way to solve such issue. So I am OK with it now.

**Comment by GoeLin** [comment]
Hi @tstuefe, this is a fix for an existing issue. Changing the behavior of the AIX allocation is not the intention of this fix.  Modernizing the AIX memory allocation is a possible follow-up. Also we need to backport this, so it should be fix-only. Thus I think we should really do the 4K/256M distiction here to match the allocation implemented in os_aix.cpp.

**Comment by GoeLin** [comment]
Hi @tstuefe, I read and understood all of your reply. I was referring to your "I don't think we need to cater to the 4K page mode." statement.  The 4K page mode is current state of the AIX implementation, and in my eyes the error is in virtualspace and os.cpp to use a  wrong alignement for the attach points, not in os_aix.cpp.  
Also, for the attach point randomization, it well makes a difference if you use 4K or 256M. There are less than 16 attach points aligned to 256M in 4G, which makes  allocation in the lowest 4G fail.
I was not aware the os.cpp problem appeard only after 21.

For the n-times copied logic: There are only two places in the JVM coding. The others are in tests. Obviously, the tests must be adapted to the JVM coding.
Joachim's original proposal was to encapsulate this in a new function. This moves the logic into the aix coding. You voted against this. So what to do now?

**Comment by JoKern65** [comment]
With my new commit I tried to be less verbose.
And indeed `os::attempt_reserve_memory_between()` is not in jdk21, but introduced by you, Thomas some months ago.

**Review by tstuefe — APPROVED** [review]
Okay. Thanks for reducing the patch size.

**Pull request closed without merging**
