### PR TITLE
8282225: GHA: Allow one concurrent run per PR only

### PR DESCRIPTION
**Pull request by shipilev**
Since last year, GHA allows concurrency control over GHA runs:
 https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Our GHA workflows trigger on every PR update, sometimes doing multiple runs per PR. This is seldom useful and wastes resources with our very large jobs. For example, one can push a commit, quickly realize there is a mistake, push another commit, and this would do *two* GHA runs, both taking many hours.

I think we can say that only one run per branch is good, and all running/pending runs should be cancelled when a new run starts.

Additional testing:
 - [x] Verified queued run gets cancelled on new commit
 - [x] Verified in-progress run gets cancelled on new commit
 - [x] Verified in-progress run gets cancelled on merge
 - [x] Verified in-progress run gets cancelled on rebase + force-push

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282225](https://bugs.openjdk.java.net/browse/JDK-8282225): GHA: Allow one concurrent run per PR only

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7570/head:pull/7570` \
`$ git checkout pull/7570`

Update a local copy of the PR: \
`$ git checkout pull/7570` \
`$ git pull https://git.openjdk.java.net/jdk pull/7570/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7570`

View PR using the GUI difftool: \
`$ git pr show -t 7570`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7570.diff">https://git.openjdk.java.net/jdk/pull/7570.diff</a>

</details>

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Looks good.

**Comment by shipilev** [comment]
I realized that we would be better off specializing by workflow name as well. While we only have one workflow in the upstream repo, others might have more than one referenced by the same concurrency key. To avoid surprises, we can should also mix in `github.workflow`.

**Review by magicus — APPROVED** [review]

**Comment by shipilev** [comment]
I think this is pretty simple, so I shall be integrating with one review. Or anyone else may put stamp their review on it :)

**Comment by magicus** [comment]
The two reviewer rule is specific to hotspot code. In build code, we're okay with a single reviewer and no 24h waiting (with the risk of having to amend the fix later), since so few people are available to review build code.

**Comment by magicus** [comment]
Of course, the more the merrier. :-) Especially if you are making a big or controversial change, it's good to wait for more reviewers. It's also good to wait for reviewers from the build group (sometimes developers from other teams approve build changes, but they might miss subtleties). But if you think that one reviewer is enough, you don't really need to ask permission to integrate with just one reviewer.

**Pull request closed without merging**
