### PR TITLE
8293922: Extend barrier-less Java thread transitions to native transitions

### PR DESCRIPTION
**Pull request by robehn**
As suggested by @TheRealMDoerr, avoid the fence for native trans when UseSystemMemoryBarrier is enabled.

Locally I can see methods like Thread.holdsLock() getting a 4 ns speed boost, (~20% faster).

Running t1-5 with UseSystemMemoryBarrier on.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293922](https://bugs.openjdk.org/browse/JDK-8293922): Extend barrier-less Java thread transitions to native transitions

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10302/head:pull/10302` \
`$ git checkout pull/10302`

Update a local copy of the PR: \
`$ git checkout pull/10302` \
`$ git pull https://git.openjdk.org/jdk pull/10302/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10302`

View PR using the GUI difftool: \
`$ git pr show -t 10302`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10302.diff">https://git.openjdk.org/jdk/pull/10302.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Very cool! Both, `_thread_state` and `_polling_word` are volatile, so the C++ compiler is not allowed to mess up the accesses. The speedup should more than justify the overhead of the `SYS_membarrier` call. I hope that we can use it in production at some point of time.

**Comment by robehn** [comment]
Thanks, great.

But since you bring it up. We should use correct accessors for _thread_state.
Fixed that, please have a second look @TheRealMDoerr.

**Review by TheRealMDoerr — APPROVED** [review]
Thanks for cleaning it up!

**Comment by robehn** [comment]
> Thanks for cleaning it up!

Thank you!

**Review by pchilano — COMMENTED** [review]
Looks good. Can't we do the same in ~ThreadBlockInVMPreprocess() for the blocked transition?

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

I do have to wonder why we had those casts that you removed.

**Comment by dcubed-ojdk** [comment]
> Can't we do the same in ~ThreadBlockInVMPreprocess() for the blocked transition?

Perhaps, but please use a new RFE/bug for that.

**Comment by robehn** [comment]
The casts came from the time when the atomics didn't use templates, so it only supported integer types.

TBIVM should not really notice any difference, since it mostly used together with VM Mutex, thus most emit a fence on front edge. As Dan says, do a separate RFE if you like it to be consistent.

Thanks for reviewing!

**Review by pchilano — APPROVED** [review]

**Comment by robehn** [comment]
Thanks!

**Pull request closed without merging**
