### PR TITLE
8283700: Add final or sealed modifier to appropriate java.awt API classes

### PR DESCRIPTION
**Pull request by prrace**
JDK 17 delivered JEP 409: Sealed Classes : https://openjdk.java.net/jeps/409
In essence this JEP allows a class to limit which classes can subclass it.
If a class has no subclasses and cannot be subclassed outside the JDK it can also be made final.
Suitable classes across the JDK are being retro-fitted to be sealed (or made final) where it can be done compatibly.
This fix takes care of several AWT classes which were identified.
If later we need to remove sealed or make a class non-final that will also be a compatible change,
so we aren't locking ourselves into this.

All our automated regression tests - plus JCK tests have been run.

This will require a CSR

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8283700](https://bugs.openjdk.java.net/browse/JDK-8283700): Add final or sealed modifier to appropriate java.awt API classes
 * [JDK-8283813](https://bugs.openjdk.java.net/browse/JDK-8283813): Add final or sealed modifier to appropriate java.awt API classes (**CSR**)

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Prasanta Sadhukhan](https://openjdk.java.net/census#psadhukhan) (@prsadhuk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7998/head:pull/7998` \
`$ git checkout pull/7998`

Update a local copy of the PR: \
`$ git checkout pull/7998` \
`$ git pull https://git.openjdk.java.net/jdk pull/7998/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7998`

View PR using the GUI difftool: \
`$ git pr show -t 7998`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7998.diff">https://git.openjdk.java.net/jdk/pull/7998.diff</a>

</details>

### CODE REVIEW

**Review by aivanov-jdk — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Comment by mrserb** [comment]
I wonder do we have some javac checks which may show some warnings related to these updated classes like not all subclasses are covered by the switch/unnecessary default branch/etc?

**Comment by forax** [comment]
@mrserb, you mean to detect that you can not add a new subclass without breaking the source backward compatibility.
You can add a test that switch over all the cases with no "default", if a new subclass is added, the test will not compile anymore.

**Comment by prrace** [comment]
I *think* Sergey is asking how javac identifies classes that are sub-classing the sealed class but not listed in the permits clause ?

**Comment by jddarcy** [comment]
> I _think_ Sergey is asking how javac identifies classes that are sub-classing the sealed class but not listed in the permits clause ?

If a sealed class does not have a permits clause, the allowed subclasses must be in the same file as the class in question, e.g. nested classes that were also subclasses or auxiliary classes. This is described in the JEP.

**Comment by mrserb** [comment]
Thank you for clarification

**Comment by prrace** [comment]
The CSR is now ready for review : https://bugs.openjdk.java.net/browse/JDK-8283813

**Review by prsadhuk — APPROVED** [review]
> Suitable classes across the JDK are being retro-fitted to be sealed 
How does this "suitability" check done? Are these exhaustive or more awt classes will be added?
Do we need to do the same for swing classes too?

**Comment by jddarcy** [comment]
> > Suitable classes across the JDK are being retro-fitted to be sealed
> 
> How does this "suitability" check done? Are these exhaustive or more awt classes will be added? Do we need to do the same for swing classes too?

I wrote an annotation processor to look for candidates to make sealed (public classes with no public or protected constructors and at least one package access constructor). Phil has filed bugs for swing (JDK-8283706) and other client areas.

**Pull request closed without merging**
