### PR TITLE
8318692: Add instructions for creating Ubuntu-based sysroot for cross compilation

### PR DESCRIPTION
**Pull request by caizixian**
Sometimes it's useful to have a Ubuntu-based chroot when you want to ensure compatibility of your deployment target and/or have access to packages that might not be in Debian upstream for some architectures.

Ubuntu-based sysroot warrants a separate instruction because `symlinks` is in the `universe` repository, and without that, `debootstrap` might fail with package not found, but it's not immediately obvious why.

This should be merged after #16332 for consistent formatting. Once #16332 is merged, I will update this PR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318692](https://bugs.openjdk.org/browse/JDK-8318692): Add instructions for creating Ubuntu-based sysroot for cross compilation (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [3148ecda](https://git.openjdk.org/jdk/pull/16331/files/3148ecda006340b1af3662d63a54413645d531a6)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16331/head:pull/16331` \
`$ git checkout pull/16331`

Update a local copy of the PR: \
`$ git checkout pull/16331` \
`$ git pull https://git.openjdk.org/jdk.git pull/16331/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16331`

View PR using the GUI difftool: \
`$ git pr show -t 16331`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16331.diff">https://git.openjdk.org/jdk/pull/16331.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16331#issuecomment-1776392538)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by caizixian** [comment]
This is updated to follow the same formatting per #16332

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
