### PR TITLE
JDK-8287337: SnippetUtils should throw exceptions if snippets not found

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a simple change for `SnippetUtils` to throw a checked exception if a snippet cannot be found.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287337](https://bugs.openjdk.java.net/browse/JDK-8287337): SnippetUtils should throw exceptions if snippets not found

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.java.net/census#hannesw) (@hns - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8892/head:pull/8892` \
`$ git checkout pull/8892`

Update a local copy of the PR: \
`$ git checkout pull/8892` \
`$ git pull https://git.openjdk.java.net/jdk pull/8892/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8892`

View PR using the GUI difftool: \
`$ git pr show -t 8892`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8892.diff">https://git.openjdk.java.net/jdk/pull/8892.diff</a>

</details>

### CODE REVIEW

**Review by hns — APPROVED** [review]
Looks good to me. I'm not sure the `requireNonNull` method carries its own weight given that one `getSnippetById` method could by implemented by calling the other, but that's a minor stylistic concern.

**Comment by jonathan-gibbons** [comment]
> Looks good to me. I'm not sure the `requireNonNull` method carries its own weight given that one `getSnippetById` method could by implemented by calling the other, but that's a minor stylistic concern.

Note that the `requireNonNull` method is a local method to ensure the intended specific exception is thrown. It is not plain old `Objects.requireNonNull` that throws plain old NPE.

**Comment by jonathan-gibbons** [comment]
> Looks good to me. I'm not sure the `requireNonNull` method carries its own weight given that one `getSnippetById` method could by implemented by calling the other, but that's a minor stylistic concern.

OK, I looked at this again, and now see what you mean. I'll look at simplifying this.

**Review by hns — APPROVED** [review]
The new version looks good to me. I hadn't even thought about the case of the missing comment, I like that it's handled explicitly now.

**Pull request closed without merging**
