### PR TITLE
8264091: Use the blessed modifier order in java.logging

### PR DESCRIPTION
**Pull request by alblue**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264091](https://bugs.openjdk.java.net/browse/JDK-8264091): Use the blessed modifier order in java.logging

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3163/head:pull/3163`
`$ git checkout pull/3163`

To update a local copy of the PR:
`$ git checkout pull/3163`
`$ git pull https://git.openjdk.java.net/jdk pull/3163/head`

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by alblue** [comment]
/integrate

>

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
