### PR TITLE
8276455: C2: iterative EA

### PR DESCRIPTION
**Pull request by vnkozlov**
Resolve C2 issue with nested initialization when Escape Analysis can not scalarize allocations: `new A(new B( new C)))`
Implemented iterative EA when C2 invokes it again if there are progress and candidates.

I added JMH microbenchmark with cases which show improvements. Improvements are due to removed allocation code.

Before: 
```
Benchmark          Mode  Cnt     Score     Error  Units
IterativeEA.test1  avgt    5    11.489 ±   3.037  ns/op
IterativeEA.test2  avgt    5    16.103 ±   3.686  ns/op
IterativeEA.test3  avgt    5  1988.827 ± 217.831  ns/op
```
With these changes: 
```
IterativeEA.test1  avgt    5    2.182 ± 0.022  ns/op
IterativeEA.test2  avgt    5    2.375 ± 0.001  ns/op
IterativeEA.test3  avgt    5  821.011 ± 8.268  ns/op
```

An other JMH test:
```
PointerBenchmarkFlat.test      avgt   30  23.232 ± 6.507  ms/op
```
vs
```
PointerBenchmarkFlat.test      avgt   30  0.299 ±  0.001  ms/op
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276455](https://bugs.openjdk.java.net/browse/JDK-8276455): C2: iterative EA

### Reviewers
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**) ⚠️ Review applies to 5e3a1740ff0fc52f9b935eef3d80ae8fa5dd60d5
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 5e3a1740ff0fc52f9b935eef3d80ae8fa5dd60d5
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6222/head:pull/6222` \
`$ git checkout pull/6222`

Update a local copy of the PR: \
`$ git checkout pull/6222` \
`$ git pull https://git.openjdk.java.net/jdk pull/6222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6222`

View PR using the GUI difftool: \
`$ git pr show -t 6222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6222.diff">https://git.openjdk.java.net/jdk/pull/6222.diff</a>

</details>

### CODE REVIEW

**Review by veresov — APPROVED** [review]
Looks reasonable.

**Review by neliasso — APPROVED** [review]
Looks good

**Review by rwestrel — APPROVED** [review]
That looks good to me.
Have you measured how compile time is affected?

**Comment by vnkozlov** [comment]
> That looks good to me.
> Have you measured how compile time is affected?

Thank you, Roland, for review.

Originally I was also concerned about that. I even added bailout if following iterations take a time. But after collecting times data I found that majority of time is spent in first iteration (as before). Following iterations takes only fraction of time because smaller EA's Connection Graph after allocations were removed during first iteration.

**Pull request closed without merging**
