### PR TITLE
8346048: test/lib/containers/docker/DockerRunOptions.java uses addJavaOpts() from ctor

### PR DESCRIPTION
**Pull request by lmesnik**
Trivial fix to avoid using methods from DockerRunOptions().

Don't methods final, just  for using them in ctor.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8346048](https://bugs.openjdk.org/browse/JDK-8346048): test/lib/containers/docker/DockerRunOptions.java uses addJavaOpts() from ctor (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22748/head:pull/22748` \
`$ git checkout pull/22748`

Update a local copy of the PR: \
`$ git checkout pull/22748` \
`$ git pull https://git.openjdk.org/jdk.git pull/22748/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22748`

View PR using the GUI difftool: \
`$ git pr show -t 22748`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22748.diff">https://git.openjdk.org/jdk/pull/22748.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22748#issuecomment-2542585349)
</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
> Don't methods final, just for using them in ctor.

I would be more inclined to make them final because there is no reason for them to be overridden. Took me a while to realize what was being complained about here: potential invocation of  a subclass implementation of the method before the instance is fully initialized.

**Comment by lmesnik** [comment]
Yes, should be mentioned that it is just to fix javac warning. I am not sure if anyone going extend this class, so let make the methods final. If anyone wants to override them they should deal with javac warnings/errors/

**Review by dholmes-ora — APPROVED** [review]
Seems fine to me. Thanks

**Pull request closed without merging**
