### PR TITLE
8258254: Move PtrQueue flush to PtrQueueSet subclasses

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the PtrQueue hierarchy, changing queue flushing
from an intrinsic operation of the queue to an operation the qset performs on
a queue.  This is a piece of the refactoring being done under JDK-8258251,
separated out for easier review.

This change also removes a couple of no longer used internal helper functions
from PtrQueue.

Testing:
mach5 tier1
local (linux-x64) hotspot:tier1 with -XX:+UseShenandoahGC

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258254](https://bugs.openjdk.java.net/browse/JDK-8258254): Move PtrQueue flush to PtrQueueSet subclasses

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 9b51552f1979286cbacf6517af6508454e4f7d9b
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 9b51552f1979286cbacf6517af6508454e4f7d9b

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1851/head:pull/1851`
`$ git checkout pull/1851`

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by shipilev — APPROVED** [review]
Shenandoah parts look fine.

**Comment by kimbarrett** [comment]
Thanks @shipilev and @tschatzl  for reviewing.

**Pull request closed without merging**
