### PR TITLE
8307625: Redundant receiver null check in LibraryCallKit::generate_method_call

### PR DESCRIPTION
**Pull request by enothum**
The null_check_receiver() calls in generate_method_call are redundant as all callers of generate_method_call already perform this check. For future uses of generate_method_call a new assert is introduced that fails if the caller does not null check the receiver.
Also generally null_check_receiver() should be combined with stopped(), which was not the case here.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307625](https://bugs.openjdk.org/browse/JDK-8307625): Redundant receiver null check in LibraryCallKit::generate_method_call (**Enhancement** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [5763fde8](https://git.openjdk.org/jdk/pull/14542/files/5763fde8430431593b29cd6b8045c89c245d1bd8)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14542/head:pull/14542` \
`$ git checkout pull/14542`

Update a local copy of the PR: \
`$ git checkout pull/14542` \
`$ git pull https://git.openjdk.org/jdk.git pull/14542/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14542`

View PR using the GUI difftool: \
`$ git pr show -t 14542`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14542.diff">https://git.openjdk.org/jdk/pull/14542.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14542#issuecomment-1606833242)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by TobiHartmann** [comment]
Just FTR: The intrinsified `Unsafe::allocateUninitializedArray0` can currently not be called with a null receiver because it's private and only ever called from `Unsafe::allocateUninitializedArray` which would throw a NPE. But to be on the safe side in case this ever changes, we should emit a null check.

**Comment by enothum** [comment]
Thanks for the clarifications and reviews!

**Pull request closed without merging**
