### PR TITLE
8257731: Remove excessive include of stubRoutines.hpp

### PR DESCRIPTION
**Pull request by iklam**
stubRoutines.hpp is unnecessarily included by thread.hpp and copy.hpp. This causes a large number of header files related to native code generation to be included by almost all HotSpot .o files.

- Before the fix, stubRoutines.hpp is included by 803 .o files.
- After the fix, stubRoutines.hpp is included by 117 .o files.

The total number of included header files decreased from 252893 to 247631, or about 2%.

Note: the main change is the removal of stubRoutines.hpp in thread.hpp and copy.hpp. Unfortunately I have to fix quite a few missing dependencies in other source files that are revealed by the removal.

Testing: I've tested tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5 on mach5, plus locally building arm, aarch64, s390, ppc64, and zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257731](https://bugs.openjdk.java.net/browse/JDK-8257731): Remove excessive include of stubRoutines.hpp

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 9baf9a50139c7d034245c8ed06ddee57f9107b07
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 9baf9a50139c7d034245c8ed06ddee57f9107b07

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1610/head:pull/1610`
`$ git checkout pull/1610`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good to me, if you did a test build of zero and maybe ppc at least.

**Review by vnkozlov — APPROVED** [review]
Make sure all builds are passed.

**Comment by iklam** [comment]
> Make sure all builds are passed.

@vnkozlov @coleenp I've tested tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5 on mach5, plus locally building arm, aarch64, s390, ppc64, and zero.

**Comment by vnkozlov** [comment]
> > Make sure all builds are passed.
> 
> @vnkozlov @coleenp I've tested tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5 on mach5, plus locally building arm, aarch64, s390, ppc64, and zero.

Good. Please, list testing in your PR descriptions so that we know what you did.

**Comment by iklam** [comment]
> > > Make sure all builds are passed.
> > 
> > 
> > @vnkozlov @coleenp I've tested tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5 on mach5, plus locally building arm, aarch64, s390, ppc64, and zero.
> 
> Good. Please, list testing in your PR descriptions so that we know what you did.

Done. I updated the PR descriptions.

**Comment by shipilev** [comment]
I have a suggestion: let's wait until JDK 16 forks for stabilization before we do any `#include` reshuffling? There are build breakages from these changes, so it would be nice to have these breakages away from the stabilizing repository.

**Comment by iklam** [comment]
> I have a suggestion: let's wait until JDK 16 forks for stabilization before we do any `#include` reshuffling? There are build breakages from these changes, so it would be nice to have these breakages away from the stabilizing repository.

OK, I'll push in JDK 17.

**Comment by cl4es** [comment]
> With sufficient pre-integration testing this should not be an issue. It
> seems for JDK-8257563 no GitHub actions were run and so numerous build
> variants were missed.

And since there's likely going to be some churn happening in tandem in both mainline and stabilization fork in the coming weeks, wouldn't it be better to get changes like these pushed _before_ rather than right after the JDK 16 stabilization fork is created? The second best option might be to hold off with large cleanups/reshuffling until RDP2 starts.

**Comment by shipilev** [comment]
I don't mind pushing it for JDK 16. I was just suggesting that we defer somewhat intrusive cleanups to JDK 17, as it customary to do (at least in my vicinity) in order to have everyone else build/test based on clean master in the days coming to JDK 16 cutoff. But we could instead pay more attention to the state of master and fix the follow-up build failure bugs even more promptly this week.

**Comment by iklam** [comment]
Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5 on mach5, plus locally building arm, aarch64, s390, ppc64, and zero.
/integrate

**Pull request closed without merging**
