### PR TITLE
8286873: Improve websocket test execution time

### PR DESCRIPTION
**Pull request by djelinski**
This PR improves the execution time of jdk_net tests (and, by extension, tier2) by about 3 minutes.

Tests located under `jdk/java/net/httpclient/websocket` are never run in parallel. Each of the 8 modified `Pending***` tests originally required 40 seconds to complete. After the proposed changes, they usually complete in 15 seconds.

This PR modifies the tests to initially run with 1 second timeout. If the test fails with 1 second timeout, it is retried with timeout increased to 10 seconds (the original value).

The modified tests were executed at least 10 times on each of: Windows, Linux (both x64 and aarch64), MacOS (both x64 and aarch64). No failures were observed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286873](https://bugs.openjdk.java.net/browse/JDK-8286873): Improve websocket test execution time

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to [52b735bf](https://git.openjdk.java.net/jdk/pull/8746/files/52b735bf7eebb9e8a5b2ecb6ee09059dddf4c207)
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8746/head:pull/8746` \
`$ git checkout pull/8746`

Update a local copy of the PR: \
`$ git checkout pull/8746` \
`$ git pull https://git.openjdk.java.net/jdk pull/8746/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8746`

View PR using the GUI difftool: \
`$ git pr show -t 8746`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8746.diff">https://git.openjdk.java.net/jdk/pull/8746.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
Looks ok-ish. The idea of starting with a small timeout is a good one. I am a bit less sure about moving the post-asserts inside the loop - or closing before asserting that the cf hangs, but if I understand the logic correctly it seems ok too. Maybe give some time for @pavelrappo to chime in before integrating.

**Review by pavelrappo — CHANGES_REQUESTED** [review]
I have poor recollection of the mechanics of these tests.

The source of wait is timed get and `assertHang`. You are reducing the former. That looks good.

What looks questionable is rearrangement of asserts: when `assertHangs` moves down. assertNotDone(cfClose) can transitorry pass even if ping has not hung. 

Tiriviality: since you are here, please remove

  1. superfluous "are" on BlowupOutputQueue:60
  2. "the a" on BlowupOutputQueue:63

**Comment by djelinski** [comment]
> I am a bit less sure about moving the post-asserts inside the loop

I moved them because they too can fail if the original blocked future suddenly completes.
Side effect of this change is that any failures that happen after websocket.abort will be retried (isDone will return true). I think this is acceptable.

> or closing before asserting that the cf hangs, but if I understand the logic correctly it seems ok too.

`assertHangs` essentially just waits for five seconds to see if the future finishes in the meantime. With the proposed change we are waiting for 2 futures at the same time.

**Comment by djelinski** [comment]
> What looks questionable is rearrangement of asserts: when `assertHangs` moves down. assertNotDone(cfClose) can transitorry pass even if ping has not hung.

`assertHangs` either waits for 5 seconds or throws an exception, so `assertNotDone` after `assertHangs` is pretty much equivalent to `assertHangs`

**Comment by pavelrappo** [comment]
> > What looks questionable is rearrangement of asserts: when `assertHangs` moves down. assertNotDone(cfClose) can transitorry pass even if ping has not hung.
> 
> `assertHangs` either waits for 5 seconds or throws an exception, so `assertNotDone` after `assertHangs` is pretty much equivalent to `assertHangs`

The order of these checks is important. On the other hand, I'm not sure how important that importance is for the tests. With the proposed change, the test might become more permissive than it should've been.

Separately, why does this PR change `assertHangs(cfClose)` to `assertNotDone(cfClose)`?

The fact that you say that the tests still pass gives me some confidence. I'm just trying to make sure that the tests still test what we think they test.

**Comment by djelinski** [comment]
> > > What looks questionable is rearrangement of asserts: when `assertHangs` moves down. assertNotDone(cfClose) can transitorry pass even if ping has not hung.
> > 
> > 
> > `assertHangs` either waits for 5 seconds or throws an exception, so `assertNotDone` after `assertHangs` is pretty much equivalent to `assertHangs`
> 
> The order of these checks is important. On the other hand, I'm not sure how important that importance is for the tests. With the proposed change, the test might become more permissive than it should've been.
> 
> Separately, why does this PR change `assertHangs(cfClose)` to `assertNotDone(cfClose)`?
> 
> The fact that you say that the tests still pass gives me some confidence. I'm just trying to make sure that the tests still test what we think they test.

Modified the tests to make it clear that we expect both CFs to hang. Let me know if that addresses your concerns.

**Review by pavelrappo — APPROVED** [review]

**Pull request closed without merging**
