### PR TITLE
8268725: jshell does not support the --enable-native-access option

### PR DESCRIPTION
**Pull request by lahodaj**
Adding `--enable-native-access` option to JShell. Set as a parameter to the remote agent (`--enable-native-access=ALL-UNNAMED`), but not the compiler, as the compiler does not have this option.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268725](https://bugs.openjdk.java.net/browse/JDK-8268725): jshell does not support the --enable-native-access option

### Reviewers
 * [Athijegannathan Sundararajan](https://openjdk.java.net/census#sundar) (@sundararajana - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4810/head:pull/4810` \
`$ git checkout pull/4810`

Update a local copy of the PR: \
`$ git checkout pull/4810` \
`$ git pull https://git.openjdk.java.net/jdk pull/4810/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4810`

View PR using the GUI difftool: \
`$ git pr show -t 4810`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4810.diff">https://git.openjdk.java.net/jdk/pull/4810.diff</a>

</details>

### CODE REVIEW

**Review by sundararajana — APPROVED** [review]
LGTM


Is this consistent with other module specific options? enable native access can be specified per module basis as well (in addition to ALL-UNNAMED)

**Comment by lahodaj** [comment]
> LGTM
> 
> Is this consistent with other module specific options? enable native access can be specified per module basis as well (in addition to ALL-UNNAMED)

That is a good question. I don't think we have a module-specific option quite like this - we have `--add-modules`, but that is significantly different. I suspect most code run in JShell runs in the(/an) unnamed module, and having simple `--enable-native-access` helps with that. If the users want add modules, they need to use `--add-modules`, and they may have to use `-R--enable-native-access=<module-name>`, but I suspect that will be a small minority of users.

**Review by sundararajana — APPROVED** [review]

**Comment by forax** [comment]
I don't like the fact that --enable-native-access will behave differently with java and jshell,
in fact, it's worst, for jshell, --enable-native-access and -R--enable-native-access will behave differently.

For me, either "--enable-native-access" is a valid syntax and in case both  java and jshell should support it,
or the shortcut to use the unnamed module does not worth the cost and in that case, it should not be implemented.

**Comment by lahodaj** [comment]
> I don't like the fact that --enable-native-access will behave differently with java and jshell,
> in fact, it's worst, for jshell, --enable-native-access and -R--enable-native-access will behave differently.
> 
> For me, either "--enable-native-access" is a valid syntax and in case both java and jshell should support it,
> or the shortcut to use the unnamed module does not worth the cost and in that case, it should not be implemented.

I was struggling with that a bit also. But, in general, I don't think JShell says/advertises the snippets run in an unnamed module. So, requiring this knowledge from the user does not seem right, and would not be a big help over the currently working `-R--enable-preview=ALL-UNNAMED`. Also, the (existing) `--add-exports` option in JShell also does not accept the target module, only the source module and package. And `--enable-preview` also works slightly differently in runtime/JShell and at compile time. So there are already differences between options, and while it is not particularly nice to have another difference, it does not seem so bad to me.

**Comment by forax** [comment]
For me, the code that can require enable-native-access can be either a code written in jshell or a library/module used by the code written by jshell.
Having '-R--enable-preview=ALL-UNNAMED' will only cover the former use case not the later.

**Pull request closed without merging**
