### PR TITLE
8281146: Replace StringCoding.hasNegatives with countPositives

### PR DESCRIPTION
**Pull request by cl4es**
I'm requesting comments and, hopefully, some help with this patch to replace `StringCoding.hasNegatives` with `countPositives`. The new method does a very similar pass, but alters the intrinsic to return the number of leading bytes in the `byte[]` range which only has positive bytes. This allows for dealing much more efficiently with those `byte[]`s that has a ASCII prefix, with no measurable cost on ASCII-only or latin1/UTF16-mostly input.

Microbenchmark results: https://jmh.morethan.io/?gists=428b487e92e3e47ccb7f169501600a88,3c585de7435506d3a3bdb32160fe8904

- Only implemented on x86 for now, but I want to verify that implementations of `countPositives` can be implemented with similar efficiency on all platforms that today implement a `hasNegatives` intrinsic (aarch64, ppc etc) before moving ahead. This pretty much means holding up this until it's implemented on all platforms, which can either contributed to this PR or as dependent follow-ups.

- An alternative to holding up until all platforms are on board is to allow the implementation of `StringCoding.hasNegatives` and `countPositives` to be implemented so that the non-intrinsified method calls into the intrinsified. This requires structuring the implementations differently based on which intrinsic - if any - is actually implemented. One way to do this could be to mimic how `java.nio` handles unaligned accesses and expose which intrinsic is available via `Unsafe` into a `static final` field.

- There are a few minor regressions (~5%) in the x86 implementation on `encode-/decodeLatin1Short`. Those regressions disappear when mixing inputs, for example `encode-/decodeShortMixed` even see a minor improvement, which makes me consider those corner case regressions with little real world implications (if you have latin1 Strings, you're likely to also have ASCII-only strings in your mix).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281146](https://bugs.openjdk.java.net/browse/JDK-8281146): Replace StringCoding.hasNegatives with countPositives

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 685795cefcd771c37d0fcebbd73d2371d1e779f8
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to 934b5b8adb848feb7e624c1aa5b8886de079c2a2
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**) ⚠️ Review applies to bc5a8c80a6f1134d3a0581caad76812c4ec2d6f0

### Contributors
 * Lutz Schmidt `<lucy@openjdk.org>`
 * Martin Doerr `<mdoerr@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7231/head:pull/7231` \
`$ git checkout pull/7231`

Update a local copy of the PR: \
`$ git checkout pull/7231` \
`$ git pull https://git.openjdk.java.net/jdk pull/7231/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7231`

View PR using the GUI difftool: \
`$ git pr show -t 7231`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7231.diff">https://git.openjdk.java.net/jdk/pull/7231.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
Seeing good improvement on the microbenchmarks here in combination with #7034, which was recently integrated. With #7034 the difference in inlining that caused a 10-15% regression on `decodeLatin1StartLong` also seem to be diminished or gone, though more stringent testing is needed

master:
```
Benchmark                           (charsetName)  Mode  Cnt     Score     Error  Units
StringDecode.decodeLatin1EndLong            UTF-8  avgt    5  3920.209 ± 168.283  ns/op
StringDecode.decodeLatin1StartLong          UTF-8  avgt    5  4012.003 ± 208.978  ns/op
```
count_positives:
```
Benchmark                           (charsetName)  Mode  Cnt     Score     Error  Units
StringDecode.decodeLatin1EndLong            UTF-8  avgt    5  1417.673 ± 109.368  ns/op
StringDecode.decodeLatin1StartLong          UTF-8  avgt    5  4021.632 ± 232.554  ns/op
```

**Comment by TheRealMDoerr** [comment]
Hi Claes, it can get implemented similarly on PPC64: https://github.com/openjdk/jdk/pull/7430
You can integrate it if you prefer that, but better after it got a Review.

**Comment by cl4es** [comment]
> Hi Claes, it can get implemented similarly on PPC64: #7430 You can integrate it if you prefer that, but better after it got a Review.

Hi Martin, perfect!

Ideally we can get all platforms that has a `hasNegatives` intrinsic moved over so we can just switch it over big-bang style: remove the `@IntrinsicCandidate`, avoid contortions to pick the "right" implementation on the Java level based on which intrinsic is available and drop all VM-internal scaffolding for `hasNegatives`. Then it makes perfect sense to fold your patch into this PR, rather than have a tail of follow-ups.

**Comment by TheRealMDoerr** [comment]
Hi Claes,
doing it for all platforms and cleaning it up sounds good. My PPC64 contribution is already tested and reviewed. I'll try to find a volunteer for s390 which uses exactly the same algorithm as PPC64.

**Comment by cl4es** [comment]
Good! I'm currently reading up on aarch64 asm and trying to port that intrinsic over. It might take some time..

**Comment by RealLucy** [comment]
Hi Claes,
I'm working on the s390 implementation. I hoped to have it ready, but tests are failing. I'll post a PR once I believe my work is worth to be reviewed. 

Just for clarification: the return value must be the index of the first negative byte?

**Comment by cl4es** [comment]
> Hi Claes, I'm working on the s390 implementation. 

Awesome, thanks!

> 
> Just for clarification: the return value must be the index of the first negative byte?

Yes, or the length if there are no such bytes. 

I've considered (and am still considering) writing the spec of `countPositives` to allow intrinsics to do an early return of a value that is less than the index if it's prohibitively expensive or complicated to implement the intrinsic to be precise in the case where it finds a negative byte. While it must be precise w.r.t. returning the full length if it's all positive bytes, no call site would break if the intrinsic returned 0 or some convenient number less than the first negative index (my first experiments with the x86 intrinsic did it like this, but since the semantics of the intrinsic would then differ from the java code I was asked to try and make it precise). The aarch64 algorithm is proving to be a challenge to work with and I might ask again for some leeway in a first implementation there.

**Comment by RealLucy** [comment]
Well, with the existing implementations for ppc and s390, I do not see a complexity advantage with a relaxed spec. The code would have to be there anyway. 

When it comes to cost, the worst case would be an array of length n, a loop unroll factor of (u==n) and the first (and only) negative byte at index (n-1). All bytes would then be checked twice. With growing n, the overhead diminishes. After all, you want profile-based stub generation - with actual load matching the profile, of course.

**Comment by cl4es** [comment]
> Well, with the existing implementations for ppc and s390, I do not see a complexity advantage with a relaxed spec. The code would have to be there anyway.

Same for x86.

> 
> When it comes to cost, the worst case would be an array of length n, a loop unroll factor of (u==n) and the first (and only) negative byte at index (n-1). All bytes would then be checked twice. With growing n, the overhead diminishes. After all, you want profile-based stub generation - with actual load matching the profile, of course.

Sounds about right. I've explored the cost of this in a few microbenchmarks. In `StringDecode/-Encode` such double-checking would happen anyhow later on in the java code. So for most of the prominent use such double-checking is performance neutral even in the worst case. 

There are a few places where we don't productively use the count and continue to lean on a `hasNegatives` predicate which calls into `countPositives`. This will mean a small amount of useless computation on certain inputs. For the 16- and 32-byte vectors I've benchmarked extensively on x86 (AVX2) the worst case overhead landed in the vicinity of 20 cycles (7.5-15ns @ 2.4Ghz). Allowing for imprecision _could_ improve a few such corner cases, but I've not found a performance sensitive place where it would really matter.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
@theRealAph , @a74nh  or someone familiar with aarch64 code, please review aarch64 changes.

**Comment by RealLucy** [comment]
@cl4ea How do you plan to proceed with the PPC (PR#7430) and s390 (PR#7604) intrinsic implementations? We (Martin and myself) would not object if you would just integrate the changes into this PR.

**Comment by cl4es** [comment]
> @theRealAph , @a74nh or someone familiar with aarch64 code, please review aarch64 changes.

Note that the aarch64 changes I've put in for now implements `countPositives` to return `0` if there's a negative value anywhere, otherwise `len`. This way we can remove the intrinsic scaffolding for `hasNegatives` once I integrate s390 and ppc changes, but since no precise calculation is implemented for aarch64 then there's no speed-up on micros such as `encodeLatin1LongEnd` for now. I would like to defer such optimization work to a follow-up.

@RealLucy yes, I'd like to integrate your changes into this patch and drop the `HasNegativesNode` et.c. You mentioned in e-mail some issue with the code generation on s390 - has that been resolved or identified?

**Comment by RealLucy** [comment]
@cl4es This issue in code generation (checking the intrinsic return value for < 0 where it only can be >= 0) is not specific to s390. It is as well visible on x86_64 and on ppc. It happens with the SPECjvm2008 sub-benchmark compiler.sunflow. What's specific to s390 is the fact that this obviously erroneous check causes the benchmark to fail. x86_64 and ppc seem to be immune. Where the immunity comes from is not yet understood.

**Comment by cl4es** [comment]
> 

Making the `bottom_type()` of `CountPositivesNode` more precise (`TypeInt::INT` -> `TypeInt::POS`) might help, then. Seems like something we want to do regardless.

**Comment by theRealAph** [comment]
> > @theRealAph , @a74nh or someone familiar with aarch64 code, please review aarch64 changes.
> 
> Note that the aarch64 changes I've put in for now implements `countPositives` to return `0` if there's a negative value anywhere, otherwise `len`. This way we can remove the intrinsic scaffolding for `hasNegatives` once I integrate s390 and ppc 

Sure. And we don't have to check which of the 8 bytes in a word has its top bit set, so we don't have to do any more work, just return the count when we stopped searching. So there's no possible performance regression on AArch64 as far as I can see.

**Comment by RealLucy** [comment]
@cl4es Looks like you forgot to remove the "@IntrinsicCandidate" annotation for has_negatives.

**Comment by cl4es** [comment]
> @cl4es Looks like you forgot to remove the "@IntrinsicCandidate" annotation for has_negatives.

I was going back and forth on this since the annotation might be used as a useful marker by other JVM implementors, so wasn't sure if removing the annotation would need to go through a deprecation cycle. I've removed it now; let's see if there are any objections to that.

**Comment by theRealAph** [comment]
>     * There are a few minor regressions (~5%) in the x86 implementation on `encode-/decodeLatin1Short`. Those regressions disappear when mixing inputs, for example `encode-/decodeShortMixed` even see a minor improvement, which makes me consider those corner case regressions with little real world implications (if you have latin1 Strings, you're likely to also have ASCII-only strings in your mix).

I'm not sure that we can disregard such cases. You're probably right, but it'd be interesting to know the actual cause of the problem, perhaps with perfasm. Or do you know already?

**Comment by cl4es** [comment]
> > ```
> > * There are a few minor regressions (~5%) in the x86 implementation on `encode-/decodeLatin1Short`. Those regressions disappear when mixing inputs, for example `encode-/decodeShortMixed` even see a minor improvement, which makes me consider those corner case regressions with little real world implications (if you have latin1 Strings, you're likely to also have ASCII-only strings in your mix).
> > ```
> 
> I'm not sure that we can disregard such cases. You're probably right, but it'd be interesting to know the actual cause of the problem, perhaps with perfasm. Or do you know already?

Still looking into it in detail, but the shape of the code at the bytecode level is different, so generated code looks quite different, which means the logical branches can be laid out differently, or just placed in a different order. The 5% in this particular test could easily be due to getting a different order of the tests for determining if a byte is ascii or latin1. 

I'm also in the process of measuring in detail after narrowing down the `bottom_type()` of the intrinsic and a few other recent fixes that could affect code generation in C2. Will also benchmark on aarch64 and report back.

**Comment by RealLucy** [comment]
> > @cl4es Looks like you forgot to remove the "@IntrinsicCandidate" annotation for has_negatives.
> 
> I was going back and forth ...

Well, it just didn't build. With the annotation being present, you also need an intrinsic implementation. That's what the error message is saying...

**Comment by cl4es** [comment]
> Well, it just didn't build. With the annotation being present, you also need an intrinsic implementation. That's what the error message is saying...

Doh, I had no idea the presence of `@IntrinsicCandidate` was mandating the VM has an intrinsic implementation these days (Why?! Not much of a _candidate_ if it's required..). I also seem to have built-and-tested locally without that patch properly applied. Sorry for the noise, should be fixed now.

**Comment by theRealAph** [comment]
> > Well, it just didn't build. With the annotation being present, you also need an intrinsic implementation. That's what the error message is saying...
> 
> Doh, I had no idea the presence of `@IntrinsicCandidate` was mandating the VM has an intrinsic implementation these days (Why?! Not much of a _candidate_ if it's required..).

I don't think the intrinsic has to be implemented on every target, but AFAICR it does have to be declared as an intrinsic in HotSpot.

**Comment by RealLucy** [comment]
> > > Well, it just didn't build. With the annotation being present, you also need an intrinsic implementation. That's what the error message is saying...
> > 
> > 
> > Doh, I had no idea the presence of `@IntrinsicCandidate` was mandating the VM has an intrinsic implementation these days (Why?! Not much of a _candidate_ if it's required..).
> 
> I don't think the intrinsic has to be implemented on every target, but AFAICR it does have to be declared as an intrinsic in HotSpot.

Yes, sorry for the imprecise wording: the declaration must be there. Use of the intrinsic is then controlled via has_match_rule(opcode) and match_rule_supported(opcode).

**Comment by cl4es** [comment]
> I don't think the intrinsic has to be implemented on every target, but AFAICR it does have to be declared as an intrinsic in HotSpot.

Yeah, I got confused. To me it looks like a declaration of intent, and thought the only strict requirement was that HotSpot can't define an intrinsic if there's no annotation. It also seems odd to hardwire it to what HotSpot does - wasn't the purpose of renaming from `@HotSpotIntrinsicCandidate` to decouple things a bit better?

Either way.. I'm re-running tests and benchmarks and seeing if I can improve the aarch64 impl to return a decent approximation rather than always-0 when there are negative bytes.

**Comment by cl4es** [comment]
aarch64: https://jmh.morethan.io/?gists=281ac3c29ef85f9f64c0440cd7f8c247,0a2c7d3b803f9cd5799f6af95eb6a90a

Brings decent gains on the "sunshine case" and the mixed microbenchmarks, but there are a few glaring exceptions which I'm still investigating.

**Review by RealLucy — APPROVED** [review]
Changes look good. 
Due to lack of specific expertise, I can't fully approve aarch64 and x86 changes.

**Comment by cl4es** [comment]
The regressions I observe on aarch64 in `encodeLatin1Short` and a few others are not in the intrinsic itself but due changes to the surrounding code. Reverting the changes to `String.encodeUTF8` removes the regressions (but also the improvements).  Seems some loop optimization is not taking place like it should. Going back to check I see that x64 is also affected, meaning this is something that has come in when syncing up with master. 

I've experimented with adjusting the code to try and workaround and improve code gen, but with only partial success. I'll back out the changes to `String.encodeUTF8`, see if we can deal with the loop opt regression (separately) and return to do the `encodeUTF8` optimization later on.

**Comment by cl4es** [comment]
Reverting changes to `String.encodeUTF8` brought all `encode`-micros down to effectively no change: https://jmh.morethan.io/?gist=b957cb9457c31141ac71d47f2e10486a (which proves implementing `hasNegatives` using `countPositives != len` has no measurable cost)

I consider this the final version for this PR (assuming tests pass). I need someone to review the aarch64 changes in particular, and perhaps someone from the core library team should sign off on the String changes (less of those now).

**Comment by cl4es** [comment]
Gentle reminder that I need a review of the aarch64 changes.

**Comment by cl4es** [comment]
Thanks @RogerRiggs 

I intend to push this soon regardless, but would appreciate an explicit review of the aarch64 changes from an aarch64 maintainer.

**Pull request closed without merging**
