### PR TITLE
8256304: should MonitorUsedDeflationThreshold be experimental or diagnostic

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
A pair of trivial fixes for a couple of ObjectMonitor cleanups.

Tested with Mach5 Tier[1-3].

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8256304](https://bugs.openjdk.java.net/browse/JDK-8256304): should MonitorUsedDeflationThreshold be experimental or diagnostic
 * [JDK-8256301](https://bugs.openjdk.java.net/browse/JDK-8256301): ObjectMonitor::is_busy() should return bool

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.java.net/census#pchilanomate) (@pchilano - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4137/head:pull/4137` \
`$ git checkout pull/4137`

Update a local copy of the PR: \
`$ git checkout pull/4137` \
`$ git pull https://git.openjdk.java.net/jdk pull/4137/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4137`

View PR using the GUI difftool: \
`$ git pr show -t 4137`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4137.diff">https://git.openjdk.java.net/jdk/pull/4137.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Thank you!  Looks good!

**Comment by dcubed-ojdk** [comment]
@coleenp - Thanks for the review.

**Comment by pchilano** [comment]
Looks good to me!

**Review by pchilano — APPROVED** [review]
Looks good to me!

**Comment by dcubed-ojdk** [comment]
@pchilano - Do you agree this is trivial? (I don't want to wait 24 hours...)

**Comment by pchilano** [comment]
> @pchilano - Thanks for the review!
> Do you agree this is trivial? (I don't want to wait 24 hours...)
Yes, I agree.

**Comment by coleenp** [comment]
Yes, I agree it's trivial also.

**Comment by dcubed-ojdk** [comment]
@coleenp and @pchilano - Thanks for the reviews and for concurrence on the
triviality of this fix.

/integrate

**Pull request closed without merging**
