### PR TITLE
8304448: Kitchensink failed: assert(!thread->is_in_any_VTMS_transition()) failed: class prepare events are not allowed in any VTMS transition

### PR DESCRIPTION
**Pull request by sspitsyn**
The fix was suggested/provided by @AlanBateman.
Continuation should use Unsafe.compareAndSetReference rather than a VH here.
We had to change CHM and VT back to Unsafe for similar reasons.

Testing: Mach5 runs of tiers 1-6 are in progress

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304448](https://bugs.openjdk.org/browse/JDK-8304448): Kitchensink failed: assert(!thread-&gt;is_in_any_VTMS_transition()) failed: class prepare events are not allowed in any VTMS transition

### Reviewers
 * [Ron Pressler](https://openjdk.org/census#rpressler) (@pron - Committer)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Contributors
 * Alan Bateman `<alanb@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13154/head:pull/13154` \
`$ git checkout pull/13154`

Update a local copy of the PR: \
`$ git checkout pull/13154` \
`$ git pull https://git.openjdk.org/jdk.git pull/13154/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13154`

View PR using the GUI difftool: \
`$ git pr show -t 13154`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13154.diff">https://git.openjdk.org/jdk/pull/13154.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
Yes, using VH in this code is problematic as first usage will load classes and there is also possible interaction with the method type cache.

**Review by pron — APPROVED** [review]

**Comment by sspitsyn** [comment]
Ron, thank you for review!

**Review by AlanBateman — APPROVED** [review]

**Comment by sspitsyn** [comment]
Thank you for review, Alan. :)

**Pull request closed without merging**
