### PR TITLE
8278532: Fix some typos in compiler comments

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is a trivial patch to fix some typos in C1 comments.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278532](https://bugs.openjdk.java.net/browse/JDK-8278532): Fix some typos in compiler comments

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6793/head:pull/6793` \
`$ git checkout pull/6793`

Update a local copy of the PR: \
`$ git checkout pull/6793` \
`$ git pull https://git.openjdk.java.net/jdk pull/6793/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6793`

View PR using the GUI difftool: \
`$ git pr show -t 6793`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6793.diff">https://git.openjdk.java.net/jdk/pull/6793.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
Looks good.

How about fixing this typo (`shoudl` --> `should`) together in this pr https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/phaseX.hpp#L244 .
Thanks.

**Comment by Hamlin-Li** [comment]
Thanks @DamonFool , I will go through comments in C2 later, how about I fix them in another pr, I created https://bugs.openjdk.java.net/browse/JDK-8278535 to track the issue.

This one is trivial, right?

**Comment by DamonFool** [comment]
> Thanks @DamonFool , I will go through comments in C2 later, how about I fix them in another pr, I created https://bugs.openjdk.java.net/browse/JDK-8278535 to track the issue.
> 
> This one is trivial, right?

I would suggest fixing them together in only one PR.
The JBS title can be adjusted as something like: Fix some typos in compiler comments

**Comment by Hamlin-Li** [comment]
Thanks for your opinion.
Normally, we don't include code in many areas in one pr unless there are strong reasons to do that. I will hold on for another reviewer's opinion.

**Comment by DamonFool** [comment]
> Normally, we don't include code in many areas in one pr unless there are strong reasons to do that.

These typos belong to hotspot compiler area.
So I don't think they are in different areas.

**Comment by vnkozlov** [comment]
> > Normally, we don't include code in many areas in one pr unless there are strong reasons to do that.
> 
> These typos belong to hotspot compiler area. So I don't think they are in different areas.

I agree. The changes are not so big to be separated. Next directories belong to compiler are: `c1, ci, code, compiler, opto`. If you find typos there, fix it here in one PR.

**Comment by Hamlin-Li** [comment]
Thanks Vladimir for confirmation.

**Comment by DamonFool** [comment]
Thanks @Hamlin-Li for your update.

It would be better to change the JBS title since you also fix a typo in C2 comments.

**Comment by Hamlin-Li** [comment]
Thanks @DamonFool for reminding, it's updated.

**Review by vnkozlov — APPROVED** [review]

**Review by DamonFool — APPROVED** [review]
Looks good and trivial.

**Comment by Hamlin-Li** [comment]
Thanks Vladimir, @DamonFool for your reviews.

/integrate

**Pull request closed without merging**
