### PR TITLE
8325159: C2 SuperWord: measure time for CITime

### PR DESCRIPTION
**Pull request by eme64**
I want to add SuperWord / AutoVectorization time to `CITime`.

This is for @vnkozlov who requested I measure the time difference for https://github.com/openjdk/jdk/pull/17624

Example:
```
...
    C2 Compile Time:        2.757 s
       Parse:                 0.027 s
       Optimize:              2.505 s
         Escape Analysis:       0.000 s
           Conn Graph:            0.000 s
           Macro Eliminate:       0.000 s
         GVN 1:                 0.007 s
         Incremental Inline:    0.000 s
           IdealLoop:             0.000 s
          (IGVN:                  0.000 s)
          (Inline:                0.000 s)
          (Prune Useless:         0.000 s)
           Other:                 0.000 s
         Vector:                0.000 s
           Box elimination:     0.000 s
             IGVN:              0.000 s
             Prune Useless:     0.000 s
         Renumber Live:         0.000 s
         IdealLoop:             2.345 s
           AutoVectorize:       1.507 s       <------------ added this
         IdealLoop Verify:      0.000 s
         Cond Const Prop:       0.014 s
         GVN 2:                 0.008 s
         Macro Expand:          0.023 s
         Barrier Expand:        0.000 s
         Graph Reshape:         0.004 s
         Other:                 0.103 s
...
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325159](https://bugs.openjdk.org/browse/JDK-8325159): C2 SuperWord: measure time for CITime (**Enhancement** - P4)

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17683/head:pull/17683` \
`$ git checkout pull/17683`

Update a local copy of the PR: \
`$ git checkout pull/17683` \
`$ git pull https://git.openjdk.org/jdk.git pull/17683/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17683`

View PR using the GUI difftool: \
`$ git pr show -t 17683`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17683.diff">https://git.openjdk.org/jdk/pull/17683.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17683#issuecomment-1923567768)

### CODE REVIEW

**Review by robcasloz — COMMENTED** [review]
Looks good, thanks! Just a question: shouldn't we also include the time taken by the call from `IdealLoopTree::policy_unroll_slp_analysis()`?

**Comment by eme64** [comment]
@robcasloz thanks for reviewing. I thought it was only a very small part of the runtime. But I'm adding it now for completeness :)

**Comment by robcasloz** [comment]
> @robcasloz thanks for reviewing. I thought it was only a very small part of the runtime. But I'm adding it now for completeness :)

Thanks for adding it, looks good!

**Review by robcasloz — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by eme64** [comment]
Thanks for the reviews @robcasloz @vnkozlov !
/integrate

**Pull request closed without merging**
