### PR TITLE
8254146: Avoid unnecessary volatile write on new AtomicBoolean(false)

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

the following PR optimizes `new AtomicBoolean(boolean)` by avoiding the volatile write in case `false` is passed. Essentially, it changes the ternary operator to a simple `if` without the `else` that would cause the volatile write.

The resulting bytecode seems to also benefit from the change:
```
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: aload_0
       5: iload_1
       6: ifeq          13
       9: iconst_1
      10: goto          14
      13: iconst_0
      14: putfield      #7                  // Field value:I
      17: return
```

After:
```
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: iload_1
       5: ifeq          13
       8: aload_0
       9: iconst_1
      10: putfield      #7                  // Field value:I
      13: return
```

A simple benchmark that returns `new AtomicBoolean(false)` shows the following results, that brings it on par to `new AtomicBoolean()`:
```
MyBenchmark.empty                                         avgt   10     3,103 ±   0,246   ns/op
MyBenchmark.explicitNew                                   avgt   10     2,966 ±   0,071   ns/op
MyBenchmark.explicitOld                                   avgt   10     7,738 ±   0,321   ns/op
```

In case you think this is worthwhile I'd be happy if this is sponsored.
Cheers,
Christoph

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254146](https://bugs.openjdk.java.net/browse/JDK-8254146): Avoid unnecessary volatile write on new AtomicBoolean(false)

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/510/head:pull/510`
`$ git checkout pull/510`

### CODE REVIEW

**Comment by dreis2211** [comment]
I have contributed before the move to GitHub and signed the OCA there. Can anybody tell me what the process is for this case?

**Comment by jerboaa** [comment]
@dreis2211 Have you tried what the bot suggested?

```
Once you have signed the OCA, please let us know by writing /signed in a comment in this pull request.
```

**Comment by dreis2211** [comment]
@jerboaa Since I have signed the OCA before the move to GitHub there is no connection to my GitHub handle, so I was confused by that if that means I have to completely sign the OCA again.

**Review by cl4es — APPROVED** [review]

**Comment by AlanBateman** [comment]
I assume this should be coordinated with an update to the jsr166 CVS too.

**Comment by dreis2211** [comment]
@AlanBateman What would be the label (or workflow) for that now?

**Review by RogerRiggs — APPROVED** [review]

**Comment by cl4es** [comment]
> @AlanBateman What would be the label (or workflow) for that now?

@dreis2211 what Alan reminded us of here is that all of j.u.concurrent is maintained upstream from the OpenJDK, and that this change needs to be coordinated with the maintainers there. Either by getting an OK to go ahead and push this as-is, or by contributing this patch to the JSR166 repo directly (which will then be integrated back into the OpenJDK at some point). See http://gee.cs.oswego.edu/dl/concurrency-interest/ 

This isn't anything new since the GitHub migration: Various bits and pieces of the OpenJDK sources are maintained upstream, and it's not always easy to igure out exactly where or how to go about upstreaming a change.

**Comment by dreis2211** [comment]
@cl4es Thanks. My question was more referring to how the PR tooling should be used these days to notify the maintainers. As JSR166 is a crucial piece of the JDK I was wondering if there might be a way already via a label or something.
Or if this needs some good old mail (to concurrency-interest@cs.oswego.edu I suppose?)

**Comment by shipilev** [comment]
You can probably go ahead and ping @DougLea (like this).

**Comment by DougLea** [comment]
I'm a little hesitant about the precedent of checking for 0 in every ctor argument for a volatile field.
An alternative here worth measuring is: VALUE.setRelease(this, initialValue ? 1 : 0);

**Comment by dreis2211** [comment]
> I'm a little hesitant about the precedent of checking for 0 in every ctor argument for a volatile field.

I'm confused by this if I'm entirely honest @DougLea . Where do we check for 0 in the proposed change?

**Comment by DougLea** [comment]
As in: If unnecessarily writing 0 to a voltaile field in a ctor is expensive enough for a code work-around here, don't you think it would be better to teach a compiler to avoid it?

**Comment by dreis2211** [comment]
I see what you mean now - thanks! Given that there exists already an empty `AtomicBoolean` constructor that avoids the volatile write, I didn't see that as a big problem to be honest. Also: The proposed "workaround" doesn't seem to be overly complicated - personally I find the empty constructor to be the bigger workaround and less explicit.

The same argument applies to initializing volatile fields with their default value, if I'm thinking about it longer. Of course one would wish that the compiler would be able to avoid it, but there have been examples in the past already where the explicit volatile write was avoided (e.g. in [JDK-8145680](https://bugs.openjdk.java.net/browse/JDK-8145680) instead of working on [JDK-8145948](https://bugs.openjdk.java.net/browse/JDK-8145948) for example).

Overall, I think it's a reasonably simple improvement with a good performance gain for relatively little cost, but after all I'm in your hands when it comes to approving the proposed change.

**Comment by DougLea** [comment]
OK. I won't resist doing this as a one-shot. We'll include in jsr166 sources, so it won't matter if done now or later along with integration pass. (Well, except the braces, which are stylistically not used in j.u.c. code)

**Review by ChrisHegarty — APPROVED** [review]

**Comment by stsypanov** [comment]
I appologise for writing this to already closed issue, but Christoph's approach seems to be applicable for at leas `AtomicInteger` and `AtomicLong`, because they are often explicitly zeroed at creation time (see one of my previous PRs https://github.com/spring-projects/spring-framework/pull/25846) and there we have the same effect as in `AtomicBoolean`:
```
@State(Scope.Thread)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@BenchmarkMode(value = Mode.AverageTime)
public class AtomicBenchmark {
  @Benchmark
  public Object defaultValue() {
    return new AtomicInteger();
  }
  @Benchmark
  public Object explicitValue() {
    return new AtomicInteger(0);
  }
}
```
Semantically both new AtomicInteger() and new AtomicInteger(0) are the same, but explicitValue() is much slower:
```
Benchmark                      Mode  Cnt   Score   Error  Units
AtomicBenchmark.defaultValue   avgt   30   4.778 ± 0.403  ns/op
AtomicBenchmark.explicitValue  avgt   30  11.846 ± 0.273  ns/op
```
So the same pattern as we used here could be applied for `AtomicInteger`:
```java
public AtomicInteger(int initialValue) {
  if (initialValue != 0 {
    value = initialValue;
  }
}
```
What do you think?

**Comment by cl4es** [comment]
> What do you think?

For `AtomicBoolean`, this optimization piggy-backed on an existing test, just rewriting it so that no action is taken when none is needed. So it's never a pessimization, and even improves bytecode size marginally. So it'll be a marginal gain even if the current overhead of writing to a volatile field in a constructor is removed/reduced. 

For `AtomicInteger/-Long`, we'd have to add a test that's not there, so we'd pessimize non-zero cases by adding some bytecode and a branch to remove the overhead. An overhead that can already be avoided by calling the empty constructor instead. So I think it's questionable to do this.

In the short term we could consider a point fix to replace existing use of `new AtomicInteger/-Long(0)` with `new AtomicInteger/-Long()`, but in the long term we should really try and optimize our JITs so that writing to a volatile field in constructors can be made cheaper.

**Comment by dreis2211** [comment]
@stsypanov What Claes said: I explicitly only did it for `AtomicBoolean` as the conditional expression was already present.

I don't think we should do it for the other Atomic classes for the mentioned reasons. Let's rather work on the JIT for future optimizations in this area. The `AtomicBoolean` was really just an exception.

**Comment by stsypanov** [comment]
@cl4es , @dreis2211 thanks for explanation!

**Comment by cl4es** [comment]
> On 15/10/2020 11:41, Claes Redestad wrote:
> 
> > In the short term we could consider a point fix to replace existing
> > use of `new AtomicInteger/-Long(0)` with `new
> > AtomicInteger/-Long()`, but in the long term we should really try
> > and optimize our JITs so that writing to a volatile field in
> > constructors can be made cheaper.
> 
> I guess it all depends on whether there's a happens-before
> relationship between the volatile store to Field X in a constructor
> and any subsequent get() of Field X in another thread. Intuitively I
> would have thought so, but I can't find any guarantee in the spec.
> Nonetheless, I think we'd have little gain by changing this and it
> might break (arguably incorrect) programs.

I misphrased somewhat: I think we should try and remove explicit stores of default values to volatile fields in constructors, as suggested by https://bugs.openjdk.java.net/browse/JDK-8145948 

I can't think of a way this would break any program (even arguably incorrect ones), and would net us the gains shown in comments here without any point fixes.

**Comment by stsypanov** [comment]
@cl4es could I ask one more question? Would it be helpful to create a separate PR about removal of explicit zeroing of Atomic* classes (excluding AtomicBoolean), e.g. somethin like this https://github.com/openjdk/jdk/compare/master...stsypanov:atom-simpl ?

**Comment by cl4es** [comment]
> @cl4es could I ask one more question? Would it be helpful to create a separate PR about removal of explicit zeroing of Atomic* classes (excluding AtomicBoolean), e.g. somethin like this [master...stsypanov:atom-simpl](https://github.com/openjdk/jdk/compare/master...stsypanov:atom-simpl) ?

Sure. Fixing `static final`s is unlikely to matter much, but it's a trivial change and as long as it has a performance advantage it's good to be consistent.

General advice is to limit sweeping changes to related modules, and not include code maintained in some upstream repo. What you have here looks fine.

**Comment by stsypanov** [comment]
DOne https://github.com/openjdk/jdk/pull/818

**Pull request closed without merging**
