### PR TITLE
JDK-8258645: Bring Jemmy 1.3.11 to JDK test base

### PR DESCRIPTION
**Pull request by shurymury**
Some changes to JSliderDemoTest: set a non-default driver and additional diagnostics

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258645](https://bugs.openjdk.java.net/browse/JDK-8258645): Bring Jemmy 1.3.11 to JDK test base

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1831/head:pull/1831`
`$ git checkout pull/1831`

### CODE REVIEW

**Comment by shurymury** [comment]
@amresh-sahu @akolarkunnu , if you can take a look that would be great

**Review by mrserb — APPROVED** [review]

**Comment by akolarkunnu** [comment]
Some general comments: 
JBS CODETOOLS tasks are still in NEW status, but corresponding codes are already checkedin
https://bugs.openjdk.java.net/browse/CODETOOLS-7902736
https://bugs.openjdk.java.net/browse/CODETOOLS-7902811 

A little info in JBS task/RFR, better to list all CODETOOLS(jemmy) fixes are integrating as part of this.

**Comment by amresh-sahu** [comment]
LGTM.

**Comment by shurymury** [comment]
Linked the related issued form the bug.

Thanks

**Pull request closed without merging**
