### PR TITLE
8278627: Shenandoah: TestHeapDump test failed

### PR DESCRIPTION
**Pull request by zhengyu123**
This intermittent failure seems to be observed only on Linux ppc64le, but it is **not** ppc specific problem.

With concurrent thread stack scanning/updating, nmtehod entry barrier has to be applied prior to thread stack/code roots scanning during heap iteration, to ensure scanner only sees to-space objects.

The patch also cleanup the use of `nmethod::oops_do_marking_prologue/epilogue()`, which should be used with `nmethod::oops_do_try_claim()` and closures that use the nmethod, e.g. `MarkingCodeBlobClosure`. Since `Shenandoah` switched to concurrent code root iteration, they are no longer applied.

Test:
The failure on Linux ppc64le is intermittent, usually sees a failure about 3 `hotspot_gc_shenandoah` runs. I have yet seen any failures after 10 runs with the patch.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278627](https://bugs.openjdk.java.net/browse/JDK-8278627): Shenandoah: TestHeapDump test failed

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6864/head:pull/6864` \
`$ git checkout pull/6864`

Update a local copy of the PR: \
`$ git checkout pull/6864` \
`$ git pull https://git.openjdk.java.net/jdk pull/6864/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6864`

View PR using the GUI difftool: \
`$ git pr show -t 6864`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6864.diff">https://git.openjdk.java.net/jdk/pull/6864.diff</a>

</details>

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good to me. Thank you!

**Review by shipilev — APPROVED** [review]
Okay, but shouldn't this be in JDK 18?

**Comment by zhengyu123** [comment]
> Okay, but shouldn't this be in JDK 18?

Yes, it should go to JDK 18 as I upgraded priority to P2.  So I should close this one and fix in 18 repo, right?

I am still waiting for SAP's test results.

**Comment by shipilev** [comment]
> Yes, it should go to JDK 18 as I upgraded priority to P2. So I should close this one and fix in 18 repo, right?

Yes, you need to do a PR against openjdk/jdk18.

**Comment by zhengyu123** [comment]
Moved PR to jdk18.

**Comment by shipilev** [comment]
JDK 18 PR is here: https://github.com/openjdk/jdk18/pull/56

**Pull request closed without merging**
