### PR TITLE
8255616: Disable AOT and Graal in Oracle OpenJDK

### PR DESCRIPTION
**Pull request by vnkozlov**
We shipped Ahead-of-Time compilation (the jaotc tool) in JDK 9, as an experimental feature. We shipped Graal as an experimental JIT compiler in JDK 10. We haven't seen much use of these features, and the effort required to support and enhance them is significant. We therefore intend to disable these features in Oracle builds as of JDK 16. 

We'll leave the sources for these features in the repository, in case any one else is interested in building them. But we will not update or test them.

We'll continue to build and ship JVMCI as an experimental feature in Oracle builds.

Tested changes in all tiers.

I verified that with these changes I still able to build Graal in open repo and run graalunit testing: 

`open$ bash test/hotspot/jtreg/compiler/graalunit/downloadLibs.sh /mydir/graalunit_lib/`
`open$ bash configure --with-debug-level=fastdebug --with-graalunit-lib=/mydir/graalunit_lib/ --with-jtreg=/mydir/jtreg`
`open$ make jdk-image`
`open$ make test-image`
`open$ make run-test TEST=compiler/graalunit/HotspotTest.java`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255616](https://bugs.openjdk.java.net/browse/JDK-8255616): Disable AOT and Graal in Oracle OpenJDK

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/960/head:pull/960`
`$ git checkout pull/960`

### CODE REVIEW

**Comment by katyapav** [comment]
Looks good.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Review by veresov — APPROVED** [review]

**Comment by vnkozlov** [comment]
Thank you for reviews.

**Review by magicus — APPROVED** [review]
Build changes look good.

**Pull request closed without merging**
