### PR TITLE
8256660: Disable DTLS 1.0

### PR DESCRIPTION
**Pull request by seanjmullan**
Disable DTLS 1.0 by default. This version of DTLS has weakened over time and lacks support for stronger cipher suites. DTLS 1.0 correlates with version 1.1 of TLS which has already been disabled by default in JDK 16. The IETF has deprecated this version of DTLS (along with TLS 1.0 and 1.1) in RFC 8996: https://www.rfc-editor.org/rfc/rfc8996.html.

CSR: https://bugs.openjdk.org/browse/JDK-8280507

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8256660](https://bugs.openjdk.org/browse/JDK-8256660): Disable DTLS 1.0
 * [JDK-8280507](https://bugs.openjdk.org/browse/JDK-8280507): Disable DTLS 1.0 (**CSR**)

### Reviewers
 * [Xue-Lei Andrew Fan](https://openjdk.org/census#xuelei) (@XueleiFan - **Reviewer**)
 * [Hai-May Chao](https://openjdk.org/census#hchao) (@haimaychao - Committer)
 * [Bradford Wetmore](https://openjdk.org/census#wetmore) (@bradfordwetmore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10905/head:pull/10905` \
`$ git checkout pull/10905`

Update a local copy of the PR: \
`$ git checkout pull/10905` \
`$ git pull https://git.openjdk.org/jdk pull/10905/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10905`

View PR using the GUI difftool: \
`$ git pr show -t 10905`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10905.diff">https://git.openjdk.org/jdk/pull/10905.diff</a>

</details>

### CODE REVIEW

**Review by XueleiFan — APPROVED** [review]
Looks good to me.

**Review by haimaychao — APPROVED** [review]

**Comment by haimaychao** [comment]
Looks good.

**Review by bradfordwetmore — APPROVED** [review]
LGTM, also.

Took a bit to figure out 1352, but got it now.

**Pull request closed without merging**
