### PR TITLE
8250596: Update remaining manpage references from "OS X" to "macOS"

### PR DESCRIPTION
**Pull request by asotona**
Most of the manpages were updated a few years ago but some references remain.
This patch renames remaining references to "macOS".

Please review.

Thanks,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8250596](https://bugs.openjdk.org/browse/JDK-8250596): Update remaining manpage references from "OS X" to "macOS"

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**) ⚠️ Review applies to [88c2d42c](https://git.openjdk.org/jdk/pull/13807/files/88c2d42c9d193110530e0499e94a0566f3a3d424)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [88c2d42c](https://git.openjdk.org/jdk/pull/13807/files/88c2d42c9d193110530e0499e94a0566f3a3d424)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [88c2d42c](https://git.openjdk.org/jdk/pull/13807/files/88c2d42c9d193110530e0499e94a0566f3a3d424)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [88c2d42c](https://git.openjdk.org/jdk/pull/13807/files/88c2d42c9d193110530e0499e94a0566f3a3d424)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13807/head:pull/13807` \
`$ git checkout pull/13807`

Update a local copy of the PR: \
`$ git checkout pull/13807` \
`$ git pull https://git.openjdk.org/jdk.git pull/13807/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13807`

View PR using the GUI difftool: \
`$ git pr show -t 13807`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13807.diff">https://git.openjdk.org/jdk/pull/13807.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13807#issuecomment-1535025112)

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]
keytool and jarsigner docs look good.

**Review by plummercj — APPROVED** [review]
The jstatd.1 and jstat.1 files look good.

Copyrights need updating on all the files.

**Review by dholmes-ora — APPROVED** [review]
Looks good.

**Review by sspitsyn — APPROVED** [review]

**Pull request closed without merging**
