### PR TITLE
8297556: Parse::check_interpreter_type fails with assert "must constrain OSR typestate"

### PR DESCRIPTION
**Pull request by rwestrel**
With 6312651 (Compiler should only use verified interface types for
optimization), I changed when the _klass field for an array in the
type system would be null. Before, there was an assumption that any
type (other than top, bottom) could be represented with a non null
_klass field. With 6312651, there are types that are impossible to
represent with a single klass pointer so now, the _klass field is only
guaranteed non null for an array of basic type. When I made that
change, I went over uses of the _klass field for anything other than
an array of basic type and fixed the code so it uses something other
than the _klass field. This is a place I missed.

(I made some of the changes for the _klass field after Vladimir I ran
extensive testing for the patch so that could explain why this issue
was missed)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297556](https://bugs.openjdk.org/browse/JDK-8297556): Parse::check_interpreter_type fails with assert "must constrain OSR typestate"

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11356/head:pull/11356` \
`$ git checkout pull/11356`

Update a local copy of the PR: \
`$ git checkout pull/11356` \
`$ git pull https://git.openjdk.org/jdk pull/11356/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11356`

View PR using the GUI difftool: \
`$ git pr show -t 11356`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11356.diff">https://git.openjdk.org/jdk/pull/11356.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. All tests passed.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by rwestrel** [comment]
@TobiHartmann @iwanowww thanks for the reviews

**Pull request closed without merging**
