### PR TITLE
8295007: javax/swing/JRadioButton/4314194/bug4314194.java fails in mach5 for WIndowLookAndFeel

### PR DESCRIPTION
**Pull request by prsadhuk**
javax/swing/JRadioButton/4314194/bug4314194.java correct color pixels pixel % varies between 30% for Metal to about 20% for Nimbus to about 19% for Windows L&F. But Nimbus in linux correct color pixel % falls to about 14%
so adjusted % tolerance check to 10
Also, JDK-8075916 is fixed for NimbusL&F but same issue is present for GTK L&F which is to be addressed separately as JDK-8295006 so problemlisted for now

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295007](https://bugs.openjdk.org/browse/JDK-8295007): javax/swing/JRadioButton/4314194/bug4314194.java fails in mach5 for WIndowLookAndFeel

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Author) ⚠️ Review applies to [a50ad3eb](https://git.openjdk.org/jdk/pull/10618/files/a50ad3ebf31377579d02aeebda693485a89b0ac2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10618/head:pull/10618` \
`$ git checkout pull/10618`

Update a local copy of the PR: \
`$ git checkout pull/10618` \
`$ git pull https://git.openjdk.org/jdk pull/10618/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10618`

View PR using the GUI difftool: \
`$ git pr show -t 10618`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10618.diff">https://git.openjdk.org/jdk/pull/10618.diff</a>

</details>

### CODE REVIEW

**Review by aivanov-jdk — CHANGES_REQUESTED** [review]
I propose using the ‘full block’ character (U+2588 █) which results in a text filled with the selected color. _The tolerance_ could be even increased in this case.

```java
        checkBox = new JCheckBox("\u2588".repeat(5));
        radioButton = new JRadioButton("\u2588".repeat(5));
```

Otherwise, the test depends on the font used, if the strokes are thin, it may fail.

As I posted in the comment, the test should disable antialiasing and count the pixels of the correct color, it should ignore the pixels of the background color. To accommodate for anti-aliasing on macOS and rendering of the control itself, the tolerance which is already in place could be used. I can take on this improvement. Changing the text of the controls should already make the test robust enough.

**Review by TejeshR13 — APPROVED** [review]

**Comment by mrserb** [comment]
I suggest to recheck that the final version of this change will be able to verify an initial bug.

**Comment by prsadhuk** [comment]
> propose using the ‘full block’ character (U+2588 █)

OK, modified...Seems good, also regression can still be tested..Have kept the tolerance same, although it could have been increased. Maybe during improvement PR....

**Comment by aivanov-jdk** [comment]
> Have kept the tolerance same

You've kept the updated value of 10 compared to the original one of 20.

I propose keeping 20 as it was before. The use of the ‘full block’ character ensures there are many pixels of the correct color.

**Comment by aivanov-jdk** [comment]
> I suggest to recheck that the final version of this change will be able to verify an initial bug.

I believe this is implied, isn't it?

**Review by aivanov-jdk — APPROVED** [review]
Looks good to me.

The only question is the value of `tolerance`: the original one vs. the updated one.

**Comment by aivanov-jdk** [comment]
> Tolerance has been kept same as in the original closed test

Yes, I'm sorry I didn't notice that change has been removed. Thank you.

**Pull request closed without merging**
