### PR TITLE
8301752: [IR Framework] Add more IR framework examples

### PR DESCRIPTION
**Pull request by chhagedorn**
This patch adds some more examples to the already existing IR framework usage examples. I also improved some comments.

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301752](https://bugs.openjdk.org/browse/JDK-8301752): [IR Framework] Add more IR framework examples

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12406/head:pull/12406` \
`$ git checkout pull/12406`

Update a local copy of the PR: \
`$ git checkout pull/12406` \
`$ git pull https://git.openjdk.org/jdk pull/12406/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12406`

View PR using the GUI difftool: \
`$ git pr show -t 12406`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12406.diff">https://git.openjdk.org/jdk/pull/12406.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by chhagedorn** [comment]
Thanks Vladimir and Tobias for your reviews!

**Pull request closed without merging**
