### PR TITLE
8261672: Reduce inclusion of classLoaderData.hpp

### PR DESCRIPTION
**Pull request by iklam**
classLoaderData.hpp is included by about 700 out of 1000 .o files in HotSpot. Most of these are transitively included through klass.hpp, typeArrayKlass.hpp and instanceKlass.hpp.

These headers can be refactored by moving inline functions that depend on ClassLoaderData to xxx.inline.hpp. This reduces the .o files that include classLoaderData.hpp to about 260.

(I also removed a bunch of unnecessary inclusion of classLoader.hpp from a few C files).
 
Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5. Also locally: aarch64, arm, ppc64, s390, x86, and zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261672](https://bugs.openjdk.java.net/browse/JDK-8261672): Reduce inclusion of classLoaderData.hpp

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to 96f3b680b8c6dd1ece56ee6dbf37882840929a5a
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 96f3b680b8c6dd1ece56ee6dbf37882840929a5a

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2555/head:pull/2555`
`$ git checkout pull/2555`

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
LGTM.
Lois

**Review by coleenp — APPROVED** [review]
Looks good.  I think adding compiledICHolder.inline.hpp is worth doing because performance matters to its caller in compiledMethod.cpp.

**Comment by iklam** [comment]
Thanks @coleenp and @lfoltan for the review.
/integrate

**Pull request closed without merging**
