### PR TITLE
8262259: Remove unused variable in MethodLiveness::BasicBlock::compute_gen_kill_single

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this trivial patch that removes unused/dead local variable.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262259](https://bugs.openjdk.java.net/browse/JDK-8262259): Remove unused variable in MethodLiveness::BasicBlock::compute_gen_kill_single

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2698/head:pull/2698`
`$ git checkout pull/2698`

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Seems fine and trivial.
..Thomas

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by zhengyu123** [comment]
Thanks, @tstuefe  @TobiHartmann

**Pull request closed without merging**
