### PR TITLE
8336926: jdk/internal/util/ReferencedKeyTest.java can fail with ConcurrentModificationException

### PR DESCRIPTION
**Pull request by RogerRiggs**
The original test fails intermittently, the reproducer failed consistently.
With the fix, the failure was not observed in the test or reproducer.

In jdk.internal.util.ReferencedKeyMap.entrySet() and toString() methods, avoid removing stale references that would modify the keyset while it is being iterated over. 
If GC removes the key, iterating or streaming over the keyset might get a ConcurrentModificationException.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336926](https://bugs.openjdk.org/browse/JDK-8336926): jdk/internal/util/ReferencedKeyTest.java can fail with ConcurrentModificationException (**Bug** - P4)

### Reviewers
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20499/head:pull/20499` \
`$ git checkout pull/20499`

Update a local copy of the PR: \
`$ git checkout pull/20499` \
`$ git pull https://git.openjdk.org/jdk.git pull/20499/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20499`

View PR using the GUI difftool: \
`$ git pr show -t 20499`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20499.diff">https://git.openjdk.org/jdk/pull/20499.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20499#issuecomment-2274203119)

### CODE REVIEW

**Review by bplb — APPROVED** [review]
Looks reasonable.

**Review by shipilev — APPROVED** [review]
Looks good. Comprehension check: only the methods that call back to `ReferencedKeyMap.get` are affected. So methods like `filterKeySet` itself are not affected, because they do `ReferenceKey::get`, not `ReferenceKeyMap::get`.

**Review by shipilev — CHANGES_REQUESTED** [review]
Wait a sec, I think this PR should include the un-problemlisting, e.g. reverting #20488?

**Comment by jaikiran** [comment]
Hello Aleksey,
> Wait a sec, I think this PR should include the un-problemlisting, e.g. reverting #20488?

#20488 wasn't integrated and was instead closed in favour of this current PR.

**Review by shipilev — APPROVED** [review]
All right then. I got confused by the PR status.

**Review by dfuch — APPROVED** [review]
The proposed changes look reasonable to me. Those seem to be the only method where removeStaleReferences() could have been indirectly called while looping over the entries.

**Comment by RogerRiggs** [comment]
The robustness of the non-collecting parts of the test as suggested in the Jira comments is covered by a new issue JDK-8338060.

**Pull request closed without merging**
