### PR TITLE
8333805: Replaying compilation with null static final fields results in a crash

### PR DESCRIPTION
**Pull request by rwestrel**
When dumping a replay file, if a static field is null the "null"
string is appended to the line for the field. When replaying the
compilation, this breaks for:

- string fields: instead of null, the field is initialized with a
  "null" string
  
- object fields: the jvm crashes because it treats "null" as a class
  name.
  
- array fields: the jvm crashes because it expects an array length
  where the "null" string is.
  
This patch fixes it by:

- leaving out the "null" string when the field is null. When the
  compilation is replayed, the missing field value is taken as meaning
  the field is null.
  
- setting the length to -1 for a null array which on the replay side
  is used as an indication that the field is null.
  
I also noticed, for object arrays, that the actual type of the array
(for a non null field) is included in the replay file (given it can
differ from the field type) but not used when replaying. I changed
that.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333805](https://bugs.openjdk.org/browse/JDK-8333805): Replaying compilation with null static final fields results in a crash (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19601/head:pull/19601` \
`$ git checkout pull/19601`

Update a local copy of the PR: \
`$ git checkout pull/19601` \
`$ git pull https://git.openjdk.org/jdk.git pull/19601/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19601`

View PR using the GUI difftool: \
`$ git pr show -t 19601`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19601.diff">https://git.openjdk.org/jdk/pull/19601.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19601#issuecomment-2155073221)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. I submitted testing and will report back once it passed.

**Comment by TobiHartmann** [comment]
All green.

**Comment by rwestrel** [comment]
@TobiHartmann thanks for the review & tests.
Anyone else for a review?

**Review by dean-long — APPROVED** [review]
LGTM.

**Comment by rwestrel** [comment]
@dean-long thanks for the review

**Pull request closed without merging**
