### PR TITLE
8275775: VM.metaspace prints flag 'f' for classes that have non-trivial finalize()

### PR DESCRIPTION
**Pull request by kelthuzadx**
Some customers want to observe which loaded classes have overridden the finalize() method. I found that VM.metaspace can output detailed classes. It seems feasible to add 'f' flag to it. With this patch, I found that ZipFileSystem left a finalize after applying this patch, which was obsolete 5 years ago, maybe we should remove it?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275775](https://bugs.openjdk.java.net/browse/JDK-8275775): VM.metaspace prints flag 'f' for classes that have non-trivial finalize()

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 51c959b1123acaf7539c4c8351b1e5ec2ef3571f

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6075/head:pull/6075` \
`$ git checkout pull/6075`

Update a local copy of the PR: \
`$ git checkout pull/6075` \
`$ git pull https://git.openjdk.java.net/jdk pull/6075/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6075`

View PR using the GUI difftool: \
`$ git pr show -t 6075`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6075.diff">https://git.openjdk.java.net/jdk/pull/6075.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Do we have sufficient class information to combine with the finalize() status, remembering that we will be reporting on every single class, to make VM.classes worthwhile? Would a simple command to list all non-trivially-finalizable classes be useful in itself? VM.finalizable_classes?

**Comment by kelthuzadx** [comment]
Hi David,

> Do we have sufficient class information to combine with the finalize() status, remembering that we will be reporting on every single class, to make VM.classes worthwhile? Would a simple command to list all non-trivially-finalizable classes be useful in itself? VM.finalizable_classes?

VM.finalizable_classes seems to be too ad-hoc. The only purpose is to print the class that has non-trivial finalize() method. If, maybe one day in the future, we want to know which classes have miranda method, we may need to add another VM.miranda_classes command. VM.classes can print detailed information of all loaded classes of the JVM, which looks more extensible and flexible.

Thanks.

**Comment by dholmes-ora** [comment]
> I like this (also the succinct name). Unfortunately, this would need a CSR, but if you have not yet done that we can help with this.

@tstuefe We do not use CSR requests with jcmd changes as they are deemed diagnostic commands - ref JDK-8203682 :)

**Comment by iklam** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@mail.openjdk.java.net):_
> 
> On 2/11/2021 7:55 am, David Holmes wrote:
> 
> > On 1/11/2021 5:19 pm, Yi Yang wrote:
> > > On Wed, 27 Oct 2021 01:30:37 GMT, Yi Yang <yyang at openjdk.org> wrote:
> > > > > Some customers want to observe which loaded classes have overridden
> > > > > the finalize() method. I found that VM.metaspace can output detailed
> > > > > classes. It seems feasible to add 'f' flag to it. With this patch, I
> > > > > found that ZipFileSystem left a finalize after applying this patch,
> > > > > which was obsolete 5 years ago, maybe we should remove it?
> > > > 
> > > > 
> > > > Yi Yang has updated the pull request incrementally with one
> > > > additional commit since the last revision:
> > > > ?? typo
> > > 
> > > 
> > > Hi David,
> > > > Do we have sufficient class information to combine with the
> > > > finalize() status, remembering that we will be reporting on every
> > > > single class, to make VM.classes worthwhile? Would a simple command
> > > > to list all non-trivially-finalizable classes be useful in itself?
> > > > VM.finalizable_classes?
> > > 
> > > 
> > > VM.finalizable_classes seems to be too ad-hoc. The only purpose is to
> > > print the class that has non-trivial finalize() method. If, maybe one
> > > day in the future, we want to know which classes have miranda method,
> > > we may need to add another VM.miranda_classes command. VM.classes can
> > > print detailed information of all loaded classes of the JVM, which
> > > looks more extensible and flexible.
> > 
> > 
> > My concern is there will be too much information to be useful if you
> > simply list and flag every single loaded class. We are basically trying
> > to make a decision whether to add a command that asks a specific query
> > (show me all finalizable classes), versus a command that just produces a
> > class dump and the user then has to manually apply their query to that
> > raw data. There are pros and cons to each approach.
> 
> It has been pointed out (thanks Alex) that we already have VM.class_hierarchy to print all classes, so perhaps that could be augmented to add a decorator for finalizable classes?
> 
> David
> 
> > This also seems more of a serviceability issue so I've cc'd that mailing
> > list.
> > Also this now relates to the new JEP on finalization removal:
> > https://openjdk.java.net/jeps/421
> > as a tool to help users see where finalizers exist will be useful to
> > that effort.
> > Cheers,
> > David

In general, I think it’s better to have a generic command that can be easily adapted by the user to look for the desired information. We can augment an existing command that already prints out all classes to add the finalization info. It should be pretty easy to grep for “finalizable”, etc, from the output. I would not worry about “too much information being printed”. That can be dealt pretty easily.

For usability, it would be much better than to ask the user to remember many distinct commands for querying related but different information. Also, the VM implementation will be simpler.

**Comment by kelthuzadx** [comment]
Personally and ideally, I hope JCMD can provide several types of general commands, allow users to quickly find what they want, and then we can add more subcommands for advanced usages.

For example, we provide:
```
VM.classes
VM.classloaders
VM.stringtable
VM.symboltable
VM.cds
VM.metaspace
```
It’s easy to know what it does and what users want. Then we add some subcommands for debugging/diagnostic support. In this way, we can further simplify the current commands, such as:

1. VM.classloaders = VM.classloaders + VM.classloader_stats

VM.classloaders prints current class loaders(VM.classloader_stats), we can also provide some advanced argument such as "hierarchy"(actually what VM.classloaders does now), "details" to print more information.

2. VM.command_line += VM.flags

VM Arguments:
jvm_args: -agentlib:jdwp=transport=dt_socket,address=localhost:23158
jvm_flag: <<<<<what VM.flags does>>>>
java_command: jdk.jshell.execution.RemoteExecutionControl 33170
java_class_path (initial):.
Launcher Type: SUN_STANDARD

Roughly thoughts.

**Comment by tstuefe** [comment]
> > I like this (also the succinct name). Unfortunately, this would need a CSR, but if you have not yet done that we can help with this.
> 
> @tstuefe We do not use CSR requests with jcmd changes as they are deemed diagnostic commands - ref JDK-8203682 :)

Seems odd since these are outside interfaces, used in scripts and whatnot. IMHO one of the places where CSR really makes sense.

**Comment by tstuefe** [comment]
> Personally and ideally, I hope JCMD can provide several types of general commands, allow users to quickly find what they want, and then we can add more subcommands for advanced usages.
> 
> For example, we provide:
> 
> ```
> VM.classes
> VM.classloaders
> VM.stringtable
> VM.symboltable
> VM.cds
> VM.metaspace
> ```
> 
> It’s easy to know what it does and what users want. Then we add some subcommands for debugging/diagnostic support. In this way, we can further simplify the current commands, such as:
> 
> 1. VM.classloaders = VM.classloaders + VM.classloader_stats
> 
> VM.classloaders prints current class loaders(VM.classloader_stats), we can also provide some advanced argument such as "hierarchy"(actually what VM.classloaders does now), "details" to print more information.

Both commands do different things. VM.classloaders prints out a tree-like structure, not a table. I added VM.classloaders 
because we needed a quick way at SAP to display our sometimes insanely complex loader hierarchy. Printing that tree-like structure requires a different logic for printing a simple table, since it is not stateless (see classLoaderHierarchyDCmd.cpp). 
Code-wise I doubt you save a lot complexity by combining those commands. As for simplifying user-facing commands, it is a matter of taste, see below (but note that changing existing commands introduces backward compatibility issues).

> 
> 1. VM.command_line += VM.flags
> 
> VM Arguments: jvm_args: -agentlib:jdwp=transport=dt_socket,address=localhost:23158 jvm_flag: <<<<>>> java_command: jdk.jshell.execution.RemoteExecutionControl 33170 java_class_path (initial):. Launcher Type: SUN_STANDARD
> 
> Roughly thoughts.

Do you want tiny minimalist commands doing one thing and that well? Or do you want a meta-command for one area and hide all the functionality in sub options? It is a matter of taste, mostly.

There are some advantages to the minimalist approach. E.g. you can just query the hotspot for capabilities by getting a list of commands. That makes outside scripting wrt different hotspot versions easier. But with a meta-command, you don't have that.

We have similar decisions in other areas too, e.g. command line switches. Most hotspot command line switches are atomar. They describe one thing. But there are meta-switches, e.g. -Xlog or -XX:StartFlightRecording. There, a bunch of sub options was packed under one flag, requiring extra parsing code for these and, for me, are always more difficult since they follow an own logic (e.g. I always have to look up Xlog syntax).

I'm not saying jcmd is perfect. To me, jcmd feels like a framework where we never really agreed on one syntax, and as a result the commands feel a bit arbitrary. E.g. we have meta commands (VM.metaspace) and atomar commands. But instead of combining commands, maybe one could introduce command groups. E.g 
`VM.classloaders.stats`. `VM.classloaders.tree`. Etc. 

Even only a visual separation when printing the command list would help already. E.g. combining all classloader-related commands under one header. Though deciding what goes where may be difficult, e.g. for VM.metaspace.

 Just a thought.

**Comment by kelthuzadx** [comment]
> > Personally and ideally, I hope JCMD can provide several types of general commands, allow users to quickly find what they want, and then we can add more subcommands for advanced usages.
> > For example, we provide:
> > ```
> > VM.classes
> > VM.classloaders
> > VM.stringtable
> > VM.symboltable
> > VM.cds
> > VM.metaspace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It’s easy to know what it does and what users want. Then we add some subcommands for debugging/diagnostic support. In this way, we can further simplify the current commands, such as:
> > 
> > 1. VM.classloaders = VM.classloaders + VM.classloader_stats
> > 
> > VM.classloaders prints current class loaders(VM.classloader_stats), we can also provide some advanced argument such as "hierarchy"(actually what VM.classloaders does now), "details" to print more information.
> 
> Both commands do different things. VM.classloaders prints out a tree-like structure, not a table. I added VM.classloaders because we needed a quick way at SAP to display our sometimes insanely complex loader hierarchy. Printing that tree-like structure requires a different logic for printing a simple table, since it is not stateless (see classLoaderHierarchyDCmd.cpp). Code-wise I doubt you save a lot complexity by combining those commands. As for simplifying user-facing commands, it is a matter of taste, see below (but note that changing existing commands introduces backward compatibility issues).
> 
> > 1. VM.command_line += VM.flags
> > 
> > VM Arguments: jvm_args: -agentlib:jdwp=transport=dt_socket,address=localhost:23158 jvm_flag: <<<<>>> java_command: jdk.jshell.execution.RemoteExecutionControl 33170 java_class_path (initial):. Launcher Type: SUN_STANDARD
> > Roughly thoughts.
> 
> Do you want tiny minimalist commands doing one thing and that well? Or do you want a meta-command for one area and hide all the functionality in sub options? It is a matter of taste, mostly.
> 
> There are some advantages to the minimalist approach. E.g. you can just query the hotspot for capabilities by getting a list of commands. That makes outside scripting wrt different hotspot versions easier. But with a meta-command, you don't have that.
> 
> We have similar decisions in other areas too, e.g. command line switches. Most hotspot command line switches are atomar. They describe one thing. But there are meta-switches, e.g. -Xlog or -XX:StartFlightRecording. There, a bunch of sub options was packed under one flag, requiring extra parsing code for these and, for me, are always more difficult since they follow an own logic (e.g. I always have to look up Xlog syntax).
> 
> I'm not saying jcmd is perfect. To me, jcmd feels like a framework where we never really agreed on one syntax, and as a result the commands feel a bit arbitrary. E.g. we have meta commands (VM.metaspace) and atomar commands. But instead of combining commands, maybe one could introduce command groups. E.g `VM.classloaders.stats`. `VM.classloaders.tree`. Etc.
> 
> Even only a visual separation when printing the command list would help already. E.g. combining all classloader-related commands under one header. Though deciding what goes where may be difficult, e.g. for VM.metaspace.
> 
> Just a thought.

I agree that this is a matter of taste. I prefer the minimalist command list, but I don't have a strong desire to make such changes, just a rough idea. The current jcmd commands are somewhat arbitrary, we are able to normalize it in some way in the future.

Going back to our topic, I think if possible, using the new command VM.classes instead of adding decorators to VM.class_hierarchy might be a better choice.

**Comment by kelthuzadx** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@mail.openjdk.java.net):_
> 
> On 2/11/2021 3:26 pm, Thomas Stuefe wrote:
> 
> > On Tue, 2 Nov 2021 00:14:48 GMT, David Holmes <dholmes at openjdk.org> wrote:
> > > > I like this (also the succinct name). Unfortunately, this would need a CSR, but if you have not yet done that we can help with this.
> > > 
> > > 
> > > @tstuefe We do not use CSR requests with jcmd changes as they are deemed diagnostic commands - ref JDK-8203682 :)
> > 
> > 
> > Seems odd since these are outside interfaces, used in scripts and whatnot. IMHO one of the places where CSR really makes sense.
> 
> From [1]
> 
> David > 1. Have we previously established whether a CSR request is needed for a new Dcmd?
> 
> Thomas > "My feeling is no, since this adds a new command, so there can be no backward compat issues."
> 
> :)
>
> [1] http://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2018-May/028190.html
> 
> Everyone is entitled to change their mind of course, but new commands don't have compatibility issues as you point out. And diagnostic interfaces don't need to go through the CSR process. So ...
> 
> Cheers, David

So let me try to do that~ People can still leave their comments on PR. Thanks.

**Comment by tstuefe** [comment]
> > > 
> > > 
> > > @tstuefe We do not use CSR requests with jcmd changes as they are deemed diagnostic commands - ref JDK-8203682 :)
> > 
> > 
> > Seems odd since these are outside interfaces, used in scripts and whatnot. IMHO one of the places where CSR really makes sense.
> 
> From [1]
> 
> David > 1. Have we previously established whether a CSR request is needed for a new Dcmd?
> 
> Thomas > "My feeling is no, since this adds a new command, so there can be no backward compat issues."
> 
> :)

Hah, that's embarrassing :-) 

I actually changed my mind with the asynchronous -Xlog discussions recently (https://bugs.openjdk.java.net/browse/JDK-8229517). CSR seemed to work well here, a good way to get more eyes for the user-facing command syntax. But I know that CSR is not the perfect process either (slow, arduous, and arguably new commands are not a backward compatibility issue).

**Comment by iklam** [comment]
> > Thomas > "My feeling is no, since this adds a new command, so there can be no backward compat issues."
> > :)
> 
> Hah, that's embarrassing :-)
> 
> I actually changed my mind with the asynchronous -Xlog discussions recently (https://bugs.openjdk.java.net/browse/JDK-8229517). CSR seemed to work well here, a good way to get more eyes for the user-facing command syntax. But I know that CSR is not the perfect process either (slow, arduous, and arguably new commands are not a backward compatibility issue).

I don't know about jcmd, but in general new interfaces should be discussed in CSR. We don't want to get stuck with an interface that's difficult to evolve (e.g., have forward compatibility issues).

https://wiki.openjdk.java.net/display/csr/CSR+FAQs

**Pull request closed without merging**
