### PR TITLE
8340981: Update citations to "Hacker's Delight"

### PR DESCRIPTION
**Pull request by jddarcy**
Add citation of the second edition of "Hacker's Delight".

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340981](https://bugs.openjdk.org/browse/JDK-8340981): Update citations to "Hacker's Delight" (**Bug** - P4)

### Reviewers
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21194/head:pull/21194` \
`$ git checkout pull/21194`

Update a local copy of the PR: \
`$ git checkout pull/21194` \
`$ git pull https://git.openjdk.org/jdk.git pull/21194/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21194`

View PR using the GUI difftool: \
`$ git pr show -t 21194`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21194.diff">https://git.openjdk.org/jdk/pull/21194.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21194#issuecomment-2375420706)

### CODE REVIEW

**Comment by liach** [comment]
Can we update the references in `compress` and `expand`? They refer to this book's sections, and seems they are from different sections in different editions.

**Review by bplb — APPROVED** [review]
Looks fine.

**Review by bplb — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by liach — APPROVED** [review]
The section number reference 7.7 to the Sheep and Goats operation is correct.

**Review by TheShermanTanker — APPROVED** [review]
Interesting Pull Request for sure :)

**Pull request closed without merging**
