### PR TITLE
8296758: [BACKOUT] Revert 8296115

### PR DESCRIPTION
**Pull request by TheShermanTanker**
8296115 unfortunately did not prove to be as useful as expected, revert it and reopen 8241499 for a future change (which I'll likely address soon).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296758](https://bugs.openjdk.org/browse/JDK-8296758): [BACKOUT] Revert 8296115

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11077/head:pull/11077` \
`$ git checkout pull/11077`

Update a local copy of the PR: \
`$ git checkout pull/11077` \
`$ git pull https://git.openjdk.org/jdk pull/11077/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11077`

View PR using the GUI difftool: \
`$ git pr show -t 11077`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11077.diff">https://git.openjdk.org/jdk/pull/11077.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Can you remove the `Support for checking standards conforming code` addition to the build documentation as well?

**Comment by TheShermanTanker** [comment]
> Can you remove the `Support for checking standards conforming code` addition to the build documentation as well?

Oops - forgot about that, will do in a moment

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
