### PR TITLE
8250914: Matcher::stack_direction() is unused

### PR DESCRIPTION
**Pull request by robcasloz**
Remove unused `Matcher::stack_direction()` together with related ADL entries and
ADLC support.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8250914](https://bugs.openjdk.java.net/browse/JDK-8250914): Matcher::stack_direction() is unused

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/125/head:pull/125`
`$ git checkout pull/125`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]

**Comment by iwanowww** [comment]
Looks good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by robcasloz** [comment]
Thanks Vladimir and Tobias!

**Comment by robcasloz** [comment]
/summary
Remove unused Matcher::stack_direction() together with related ADL entries and
ADLC support.

**Pull request closed without merging**
