### PR TITLE
8328177: Move LDFLAGS_JDK[LIB/EXE] to JdkNativeCompilation.gmk

### PR DESCRIPTION
**Pull request by magicus**
Similar to [JDK-8328157](https://bugs.openjdk.org/browse/JDK-8328157), we want to move the setting of LDFLAGS to LDFLAGS_JDK[LIB/EXE into SetupJdkLibrary and SetupJdkExecutable.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328177](https://bugs.openjdk.org/browse/JDK-8328177): Move LDFLAGS_JDK[LIB/EXE] to JdkNativeCompilation.gmk (**Bug** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18343/head:pull/18343` \
`$ git checkout pull/18343`

Update a local copy of the PR: \
`$ git checkout pull/18343` \
`$ git pull https://git.openjdk.org/jdk.git pull/18343/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18343`

View PR using the GUI difftool: \
`$ git pr show -t 18343`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18343.diff">https://git.openjdk.org/jdk/pull/18343.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18343#issuecomment-2003600650)

### CODE REVIEW

**Comment by magicus** [comment]
I have verified with COMPARE_BUILD that there is no change whatsoever in the resulting binaries, for all platforms in Oracle CI: Linux x64/aarch64, macOS x64/aarch64 and Windows x64.

**Comment by magicus** [comment]
Also, to be clear, my intention is to try and remove quirks and workarounds like `APPEND_LDFLAGS`; but to do that I want to focus on cleaning up one library at the time. Now I just want to lay the groundwork of having a sane API.

**Review by erikj79 — APPROVED** [review]

**Pull request closed without merging**
