### PR TITLE
8331331: :tier1 target explanation in doc/testing.md is incorrect

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,

In doc/testing.md file, it says:

As an example, :tier1 will expand to jtreg:$(TOPDIR)/test/hotspot/jtreg:tier1 jtreg:$(TOPDIR)/test/jdk:tier1 jtreg:$(TOPDIR)/test/langtools:tier1 jtreg:$(TOPDIR)/test/nashorn:tier1 jtreg:$(TOPDIR)/test/jaxp:tier1.

The actual situation is :tier1 doesn't contains test/nashorn:tier1, and the document missed test/lib-test:tier1

$ make -n test-tier1 &> test-tier1.log
$ grep "Running test " test-tier1.log
Running test 'jtreg:test/hotspot/jtreg:tier1'
Running test 'jtreg:test/jdk:tier1'
Running test 'jtreg:test/langtools:tier1'
Running test 'jtreg:test/jaxp:tier1'
Running test 'jtreg:test/lib-test:tier1'

Only change the document, no risk.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331): :tier1 target explanation in doc/testing.md is incorrect (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19002/head:pull/19002` \
`$ git checkout pull/19002`

Update a local copy of the PR: \
`$ git checkout pull/19002` \
`$ git pull https://git.openjdk.org/jdk.git pull/19002/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19002`

View PR using the GUI difftool: \
`$ git pr show -t 19002`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19002.diff">https://git.openjdk.org/jdk/pull/19002.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19002#issuecomment-2083153703)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by dholmes-ora — COMMENTED** [review]
Perhaps we should rephrase this so it is not an exhaustive list that has to be updated if the test groupings change. Suggestion:
```
As an example, <code>:tier1</code> will expand to include all subcomponent test directories that define `tier1`, for example:
<code>jtreg:$(TOPDIR)/test/hotspot/jtreg:tier1 jtreg:$(TOPDIR)/test/jdk:tier1 jtreg:$(TOPDIR)/test/langtools:tier1 ...</code>.
```

**Comment by magicus** [comment]
This fix works, but I like David's idea better. It was meant as an example, not necessarily kept up to date, so by deliberately making it shorter and ading `...` we show that this is not am exhaustive list.

**Comment by erikj79** [comment]
I agree with Magnus and David, that is a better approach.

**Comment by sendaoYan** [comment]
> Perhaps we should rephrase this so it is not an exhaustive list that has to be updated if the test groupings change. Suggestion:
> 
> ```
> As an example, <code>:tier1</code> will expand to include all subcomponent test directories that define `tier1`, for example:
> <code>jtreg:$(TOPDIR)/test/hotspot/jtreg:tier1 jtreg:$(TOPDIR)/test/jdk:tier1 jtreg:$(TOPDIR)/test/langtools:tier1 ...</code>.
> ```

Thanks for the review and advice. The doc files has been updated by the advice. @erikj79 @dholmes-ora @magicus

**Comment by sendaoYan** [comment]
The GHA runner shows that

**Review by dholmes-ora — APPROVED** [review]
LGTM. Thanks

**Review by magicus — APPROVED** [review]
Thanks!

**Review by erikj79 — APPROVED** [review]

**Pull request closed without merging**
