### PR TITLE
8284930: Re-examine FilterInputStream mark/reset

### PR DESCRIPTION
**Pull request by bplb**
Remove the `synchronized` keyword from the `mark(int)` and `reset()` methods of `java.io.FilterInputStream`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8284930](https://bugs.openjdk.java.net/browse/JDK-8284930): Re-examine FilterInputStream mark/reset
 * [JDK-8285286](https://bugs.openjdk.java.net/browse/JDK-8285286): Re-examine FilterInputStream mark/reset (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.java.net/census#jpai) (@jaikiran - Committer)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8309/head:pull/8309` \
`$ git checkout pull/8309`

Update a local copy of the PR: \
`$ git checkout pull/8309` \
`$ git pull https://git.openjdk.java.net/jdk pull/8309/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8309`

View PR using the GUI difftool: \
`$ git pr show -t 8309`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8309.diff">https://git.openjdk.java.net/jdk/pull/8309.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
I wonder if it should be removed from InputStream at the same time.

**Comment by dfuch** [comment]
> As for the changes to `FilterInputStream`, would this change require a CSR?

There might be a case where a subclass of `FilterInputStream` has overridden all other methods to add `synchronized` but has not overridden `mark` and `reset`, relying on the synchronization of the super class. I have skimmed over subclasses in the JDK, and have found no evidence of such behavior (though I have not looked exhaustively at all subclasses). Of course such subclasses could exist in the wild, but that would be both odd and fragile, since synchronization is not specified. In this particular case I don't believe that we would need a CSR to remove a synchronized keyword: whether a method is synchronized or not is not documented and not part of the spec: https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/io/FilterInputStream.html#mark(int) - and `FilterInputStream` says nothing about synchronization.

I agree with Alan that `InputStream` should be modified similarly.

**Comment by AlanBateman** [comment]
Thanks for the update. I can't think how anything could depend on this but unfortunately it's been like that since early JDK releases. We will need a release note, I'm sure Joe will give his opinion on whether a CSR should be created.

**Comment by jddarcy** [comment]
> Thanks for the update. I can't think how anything could depend on this but unfortunately it's been like that since early JDK releases. We will need a release note, I'm sure Joe will give his opinion on whether a CSR should be created.

Hmm. It is true that the presence or absence of the "synchronized" modifier is not part of a method's contract. However, the multi-thread safety, or not, of a class is part of its behavioral contract.

Without a lot of investigation, my current inclination is to run a CSR for this change for the (small) behavioral compatibility hazard.

**Comment by stuart-marks** [comment]
I think it's a vanishingly small possibility that anything is relying on the synchronization in these methods. Synchronization here would provide proper memory visibility effects across threads. To use input streams from multiple threads without interleaving operations, one would have to provide some other means of coordination among those threads, which itself would likely ensure proper memory visibility. I'm hard pressed to see how threads could coordinate solely via use of the `mark` and `reset` methods. Therefore, I think it's safe to remove synchronization from them.

This reasoning also applies to `InputStream`. Perhaps synchronization can be removed from there too.

I agree that a CSR is probably warranted to capture the behavior change and analysis.

**Comment by bplb** [comment]
>

> I think it's a vanishingly small possibility that anything is relying on the synchronization in these methods. Synchronization here would provide proper memory visibility effects across threads. To use input streams from multiple threads without interleaving operations, one would have to provide some other means of coordination among those threads, which itself would likely ensure proper memory visibility. I'm hard pressed to see how threads could coordinate solely via use of the `mark` and `reset` methods. Therefore, I think it's safe to remove synchronization from them.
> 
> This reasoning also applies to `InputStream`. Perhaps synchronization can be removed from there too.
> 
> I agree that a CSR is probably warranted to capture the behavior change and analysis.

Commit f210cbf5f6bf58326a379b4b3f55fddf49d30f5c removed the synchronization from `InputStream`'s `mark()` and `reset()`; a CSR is on file.

**Comment by stuart-marks** [comment]
Oh, sorry, I had missed that synchronization had already been removed from the `InputStream` methods. Needless to say, I approve. :-)

**Review by AlanBateman — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]

**Review by dfuch — APPROVED** [review]

**Comment by bplb** [comment]
> Looks fine Brian. Any thoughts as to whether a release note is warranted?

Thanks, @LanceAndersen. The issue is labelled as needing a release note so you are spot on.

**Pull request closed without merging**
