### PR TITLE
8259009: G1 heap summary should be shown in "Heap Parameters" window on HSDB

### PR DESCRIPTION
**Pull request by YaSuenag**
G1 heap summary (G1 Heap, summaries for each spaces) is shown on console even though I chosen "Heap Parameters" menu on HSDB. It should be shown on "Heap Parameters" window on HSDB.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259009](https://bugs.openjdk.java.net/browse/JDK-8259009): G1 heap summary should be shown in "Heap Parameters" window on HSDB

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to 4d8d484fc8fa86bceafa32a26c1dd8fe9677c5ac
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1911/head:pull/1911`
`$ git checkout pull/1911`

### CODE REVIEW

**Comment by YaSuenag** [comment]
PING: could you review it?

**Review by plummercj — APPROVED** [review]
Copyrights need updating. Otherwise looks good.

**Comment by YaSuenag** [comment]
@plummercj Thank you for the review! I updated copyright year in new commit.

**Review by tschatzl — CHANGES_REQUESTED** [review]
I would prefer to make the order of parameters uniform in `printG1HeapSummary(G1CollectedHeap g1h, PrintStream tty) {` too. I.e. there does not seem to be a reason to have only this function have `tty` as second parameter.

**Comment by YaSuenag** [comment]
@tschatzl Thanks for the comment! I fixed it.

**Review by tschatzl — APPROVED** [review]

**Pull request closed without merging**
