### PR TITLE
8342439: Build failure after 8338023

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Fix failing build. 

Due to notification problem with integration system.

Thanks,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342439](https://bugs.openjdk.org/browse/JDK-8342439): Build failure after 8338023 (**Bug** - P1)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21547/head:pull/21547` \
`$ git checkout pull/21547`

Update a local copy of the PR: \
`$ git checkout pull/21547` \
`$ git pull https://git.openjdk.org/jdk.git pull/21547/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21547`

View PR using the GUI difftool: \
`$ git pr show -t 21547`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21547.diff">https://git.openjdk.org/jdk/pull/21547.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21547#issuecomment-2417590503)

### CODE REVIEW

**Comment by liach** [comment]
Can we change the title of the JBS issue to be more descriptive, like "Build failure after 8338023"? So the PR title will be like `8342439: Build failure after 8338023`.

This is in part our fault, that we should test in CI after merging master.

**Comment by jatin-bhateja** [comment]
@vnkozlov , @liach , Kindly approve.

**Comment by liach** [comment]
Yep, running a build locally with your branch merged into master. Will approve once build passes.

**Review by liach — APPROVED** [review]
Build fixed in my local OracleJDK linux-x64 setup.

**Pull request closed without merging**
