### PR TITLE
JDK-8312044: Simplify toolkit Builder/Writer world

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a medium-sized but conceptually simple change to simplify the overall class hierarchy of the `doclet` world.

As described in detail in the JBS entry, the classes in `toolkit.builder.*Builder` and corresponding writer interfaces in `toolkit.*Writer` provide little useful benefit, and only serve to clutter a somewhat chaotic situation.

In this patch, the following is done:
* the `builder` methods in `toolkit/builders/---Builder.java` are moved into the corresponding `formats/html/---WriterImpl.java` class. Generally, the insertion was done "early" in the file, typically after the constructor(s).
* the `writer` interfaces in `toolkit/---Writer.java` are deleted and references to them in `implements` clauses removed.
* the `writer` classes in `formats/html/---WriterImpl.java` are renamed to `formats/html/---Writer.java` and in a couple of anomalous cases, the `writer` classes in `formats/html/Html---Writer.java` are also renamed to `formats/html/---Writer.java`.
* the markup root class `Content` no longer needs to be in `toolkit` and is moved to `formats/html`. (It's a close call whether it is better there or in `formats/html/markup`.

* Because of the class renaming, one test had to be updated; no other tests were affected by these changes.
* Because of the class renaming, the `<meta name="generator" ...>` information changes; there are no other changes to the generated JDK API documentation.

The changes to the `doclets` class hierarchy are shown in two attachments in the JBS entry.  In those images, you can see the "clutter" of the `builder` world and `writer` world being simplified.

The following tables show the changes in the number of files and the number of lines of code resulting from this refactoring.

### # files
|              | before | after | change | %before |
|-------------:|-------:|------:|-------:|--------:|
|      toolkit |     79 |    46 |    -33 |     58% |
| formats/html |    108 |   109 |      1 |    101% |
|      doclets |    189 |   157 |    -32 |     83% |

### # lines of code

|              | before | after | change | %before |
|-------------:|-------:|------:|-------:|--------:|
|      toolkit |  21445 | 15597 |  -5848 |     73% |
| formats/html |  29805 | 31968 |   2163 |    107% |
|      doclets |  51325 | 47640 |  -3685 |     93% |

This generally completes the recent large-scale refactoring and simplification that was started in 
[JDK-8309566](https://bugs.openjdk.org/browse/JDK-8309566). While large-scale refactoring like this may be hard to review, and complicate any future code-archaeology and back-porting, in this case the benefits of the simplification outweigh any future costs of not doing it. 

Now that some of the clutter has been moved away, we may be able to retrofit some abstract members to root classes like `HtmlDocletWriter` and `AbstractMemberWriter`.  For example, `HtmlDoclet` should be able to call a common/standard method to generate each (kind of) page, and likewise, `SubWriterHolderWriter` should be able to call a common/standard method to handle each kind of member. See [JDK-8312201](https://bugs.openjdk.org/browse/JDK-8312201) for a follow-up issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312044](https://bugs.openjdk.org/browse/JDK-8312044): Simplify toolkit Builder/Writer world (**Enhancement** - P4)

### Reviewers
 * [Pavel Rappo](https://openjdk.org/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14913/head:pull/14913` \
`$ git checkout pull/14913`

Update a local copy of the PR: \
`$ git checkout pull/14913` \
`$ git pull https://git.openjdk.org/jdk.git pull/14913/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14913`

View PR using the GUI difftool: \
`$ git pr show -t 14913`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14913.diff">https://git.openjdk.org/jdk/pull/14913.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14913#issuecomment-1640394570)

### CODE REVIEW

**Comment by pavelrappo** [comment]
> Please review a medium-sized but conceptually simple change to simplify the overall class hierarchy of the `doclet` world.

This PR looks like a welcome and long-overdue simplification. In fact, I expect more aggressive cleanup soon so that the overall jdk.javadoc becomes much, much leaner.

> * Because of the class renaming, the `<meta name="generator" ...>` information changes; there are no other changes to the generated JDK API documentation.

I wonder what purpose that "generator" meta tag serves. Do we need it in its current form?

**Comment by jonathan-gibbons** [comment]
> > Please review a medium-sized but conceptually simple change to simplify the overall class hierarchy of the `doclet` world.
> 
> This PR looks like a welcome and long-overdue simplification. In fact, I expect more aggressive cleanup soon so that the overall jdk.javadoc becomes much, much leaner.
> 
> > * Because of the class renaming, the `<meta name="generator" ...>` information changes; there are no other changes to the generated JDK API documentation.
> 
> I wonder what purpose that "generator" meta tag serves. Do we need it in its current form?

It's not strictly required, but I would prefer not to delete it at this time. It's effectively just a logging comment to help indicate who created the file.

**Review by pavelrappo — APPROVED** [review]
Looks good.

**Comment by pavelrappo** [comment]
> It's not strictly required, but I would prefer not to delete it at this time. It's effectively just a logging comment to help indicate who created the file.

Sure, it's OK to address it later. Judging by the spec ( https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names ), we can probably say content="jdk.javadoc" or some such. If nothing else, it would keep tests unaffected by changes like that.

**Comment by jonathan-gibbons** [comment]
> > It's not strictly required, but I would prefer not to delete it at this time. It's effectively just a logging comment to help indicate who created the file.
> 
> Sure, it's OK to address it later. Judging by the spec ( https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names ), we can probably say `content="jdk.javadoc"` or some such. If nothing else, it would keep tests unaffected by changes like that.

It has been useful in times past to identify the part of javadoc that generates the file. Having to modify the test occasionally on the very rare occasions when we rename classes seems like not a big deal.

**Comment by pavelrappo** [comment]
> It has been useful in times past to identify the part of javadoc that generates the file. Having to modify the test occasionally on the very rare occasions when we rename classes seems like not a big deal.

One would think that such a use suits jdk.javadoc developers, who ironically are positioned better than anyone else to derive such information from source code :)

**Pull request closed without merging**
