### PR TITLE
JDK-8274249: ZGC: Bulk free empty relocated pages

### PR DESCRIPTION
**Pull request by casparcwang**
Similar to JDK-8255237, bulk free empty relocated pages can amortize the cost of freeing a page and speed up the relocation stage.

The following is the result of specjbb2015 after applying the patch (the tests turn off  the option`UseDynamicNumberOfGCThreads`): the average relocation time speeds up 14%, and the max relocation time speeds up 18%.
```
patch:
[2021-09-18T13:11:51.736+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       373.180 / 569.855     275.312 / 569.855     275.312 / 569.855     ms
[2021-09-18T15:30:07.168+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       381.266 / 577.812     277.272 / 577.812     277.272 / 577.812     ms
[2021-09-18T17:37:56.305+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       345.037 / 494.135     259.497 / 506.815     259.497 / 506.815     ms


origin:
[2021-09-18T01:01:32.897+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       429.099 / 662.120     327.213 / 759.723     327.213 / 759.723     ms
[2021-09-18T03:11:10.433+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       413.014 / 613.035     307.625 / 613.035     307.625 / 613.035     ms
[2021-09-18T05:21:12.743+0800][info][gc,stats    ]       Phase: Concurrent Relocate                           0.000 / 0.000       411.745 / 642.242     308.986 / 642.242     308.986 / 642.242     ms
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8274249](https://bugs.openjdk.java.net/browse/JDK-8274249): ZGC: Bulk free empty relocated pages

### Contributors
 * Per Liden `<pliden@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5670/head:pull/5670` \
`$ git checkout pull/5670`

Update a local copy of the PR: \
`$ git checkout pull/5670` \
`$ git pull https://git.openjdk.java.net/jdk pull/5670/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5670`

View PR using the GUI difftool: \
`$ git pr show -t 5670`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5670.diff">https://git.openjdk.java.net/jdk/pull/5670.diff</a>

</details>

### CODE REVIEW

**Comment by pliden** [comment]
1)  Instead of checking for the allocator type in the general code, this whole thing could be moved into the ZRelocateSmallAllocator, like this: https://github.com/openjdk/jdk/compare/master...pliden:8274249_zgc_bulk_free_empty_pages

2) How did you arrive at the bulk limit of 32? Did you try other numbers and this worked the best?

3) Freeing in bulk feels like a reasonable thing to do, and I'm sure it will cause less contention on the page cache lock. So this will probably help in the normal case. However, in the case were memory is low, GC workers are now hogging free memory could cause allocation stalls to be longer than needed and cause in-place relocation to happen more often than needed. This hogging also gets worse the more GC workers we have. So, I'm a bit hesitant to bring this in without some more thought. For example, instead of having a fixed bulk free limit (like 32) we might instead want to look at other ways of limiting the amount of times `free_page()` is called. I suspect the main problem with calling `free_page()` comes in the beginning of the relocation phase, where we might be relocating a lot very sparse pages. I.e. the time between calls to `free_page()` becomes very short. Later in the relocation phase, as pages get less and less sparse and we spend more and more time copying objects, the calls to `free_page()` becomes less frequent. So, perhaps we could instead track number of relocated bytes, and call `free_pages()` once we pass some limit (say 2M). They we get a fairly uniform time between the calls to `free_page()` and avoid hogging memory for too long. This is just a thought, there might be other/better strategies they would work too. One would have to implement and benchmark to figure out which works best.

**Comment by casparcwang** [comment]
Thank your for your review and suggestions.

> * Instead of checking for the allocator type in the general code, this whole thing could be moved into the ZRelocateSmallAllocator, like this: [master...pliden:8274249_zgc_bulk_free_empty_pages](https://github.com/openjdk/jdk/compare/master...pliden:8274249_zgc_bulk_free_empty_pages)

`ZRelocateSmallAllocator` is a shared object between different relocated tasks, if the logic is moved to `ZRelocateSmallAllocator`, it will need lock-free structures to hold bulk free pages. So I think keep it in the thread local closure make things simpler.

> * How did you arrive at the bulk limit of 32? Did you try other numbers and this worked the best?

64 produces better result than 32 in my testing, but 128 produce the same result as 64. I choose 32 because the worry about in-place relocation in low memory corner cases.

> * Freeing in bulk feels like a reasonable thing to do, and I'm sure it will cause less contention on the page cache lock. So this will probably help in the normal case. However, in the case were memory is low, GC workers are now hogging free memory could cause allocation stalls to be longer than needed and cause in-place relocation to happen more often than needed. This hogging also gets worse the more GC workers we have. So, I'm a bit hesitant to bring this in without some more thought. For example, instead of having a fixed bulk free limit (like 32) we might instead want to look at other ways of limiting the amount of times `free_page()` is called.

Buffering the relocated pages in a local private structure will cause in-place relocation and allocation stall happen more if the memory is low.  So I add a check to exit bulk free mode if in-place relocation happens.

>  I suspect the main problem with calling `free_page()` comes in the beginning of the relocation phase, where we might be relocating a lot very sparse pages. I.e. the time between calls to `free_page()` becomes very short. Later in the relocation phase, as pages get less and less sparse and we spend more and more time copying objects, the calls to `free_page()` becomes less frequent. So, perhaps we could instead track number of relocated bytes, and call `free_pages()` once we pass some limit (say 2M). They we get a fairly uniform time between the calls to `free_page()` and avoid hogging memory for too long. This is just a thought, there might be other/better strategies they would work too. One would have to implement and benchmark to figure out which works best.

Use relocated bytes to control the frequency of bulk free, that's a good idea, I will test it.

**Comment by casparcwang** [comment]
> * Instead of checking for the allocator type in the general code, this whole thing could be moved into the ZRelocateSmallAllocator, like this: [master...pliden:8274249_zgc_bulk_free_empty_pages](https://github.com/openjdk/jdk/compare/master...pliden:8274249_zgc_bulk_free_empty_pages)

Move into `ZRelocateSmallAllocator` make code cleaner and easier to understand. It's a more elegant. So I changed to your provided version, and use `ZPerWorker ` to avoid the contention between the gc workers.

>  However, in the case were memory is low, GC workers are now hogging free memory could cause allocation stalls to be longer than needed and cause in-place relocation to happen more often than needed. 

If in-place relocation has happened, the pages are always freed directly.

**Comment by casparcwang** [comment]
hi, can I have more review of this pr?

**Comment by pliden** [comment]
Sorry for the delay on this. All of us are busy working on generational ZGC, so none of us has had time to look deeper into what impact of this change might have Java threads in cases where memory is scares. Hopefully we can have another look at this at a later time.

**Comment by casparcwang** [comment]
> Sorry for the delay on this. All of us are busy working on generational ZGC, so none of us has had time to look deeper into what impact of this change might have Java threads in cases where memory is scares. Hopefully we can have another look at this at a later time.

Thanks for the reply. Looking forward to use generational ZGC in our clusters in the near future.

**Pull request closed without merging**
