### PR TITLE
8236142: DocTrees should provide getCharacters(EntityTree) 

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
A new method is added to the `DocTrees` utility class to return the characters represented by a named or numeric entity, as represented in an `EntityTree`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8236142](https://bugs.openjdk.java.net/browse/JDK-8236142): DocTrees should provide getCharacters(EntityTree)

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/122/head:pull/122`
`$ git checkout pull/122`

### CODE REVIEW

**Comment by jonathan-gibbons** [comment]
Note that as well as the simple move for the `Entity.java` file, the init for the class is optimized to be significantly smaller byte codes. That particular change was automated: there should be no change to the set of strings that are accepted by the class.

**Review by pavelrappo — APPROVED** [review]

**Pull request closed without merging**
