### PR TITLE
8273606: Zero: SPARC64 build fails with si_band type mismatch

### PR DESCRIPTION
**Pull request by shipilev**
This is actually caught by `-Werror=format` that is enabled by default.

```
$  sh ./configure --with-debug-level=slowdebug --with-boot-jdk=/home/shade/Install/jdk16-16.0.2-ea/ --openjdk-target=sparc64-linux-gnu --with-sysroot=/chroots/sparc64/ --with-jvm-variants=zero
$ make images

/home/shade/trunks/jdk/src/hotspot/os/posix/signals_posix.cpp: In static member function 'static void os::print_siginfo(outputStream*, const void*)':
/home/shade/trunks/jdk/src/hotspot/os/posix/signals_posix.cpp:1148:29: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Werror=format=]
 1148 |     os->print(", si_band: %ld", si->si_band);
      |                           ~~^
      |                             |
      |                             long int
      |                           %d

man sigaction says:

siginfo_t {
    ...
               long     si_band;      /* Band event (was int in
                                         glibc 2.3.2 and earlier) */
    ...
}
```

I see that was already reported as [glibc bug #23821](https://sourceware.org/bugzilla/show_bug.cgi?id=23821), and glibc maintainers decided not to fix it. So, we can still make a defensive cast to (long), which would be no-op if the type is in fact long.

I looked at how Debian folks avoid this problem, and I think there is Debian patch that just disables `-Werror` wholesale. Right, @glaubitz? :)

Additional testing: 
 - [x] Linux sparc64 Zero cross-compilation now passes

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273606](https://bugs.openjdk.java.net/browse/JDK-8273606): Zero: SPARC64 build fails with si_band type mismatch

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to b1c72819dffca2c6ed809fe8959cdebcd713a93a

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5470/head:pull/5470` \
`$ git checkout pull/5470`

Update a local copy of the PR: \
`$ git checkout pull/5470` \
`$ git pull https://git.openjdk.java.net/jdk pull/5470/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5470`

View PR using the GUI difftool: \
`$ git pr show -t 5470`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5470.diff">https://git.openjdk.java.net/jdk/pull/5470.diff</a>

</details>

### CODE REVIEW

**Comment by glaubitz** [comment]
> Apparently, it was never fixed in glibc for sparc64? We can still make a defensive cast to `long`.

Can you file a bug report to the glibc bug tracker?

> I looked at how Debian folks avoid this problem, and I think there is Debian patch that just disables `-Werror` wholesale. Right, @glaubitz? :)

Yes, that's correct. See: https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-16/debian/patches/hotspot-disable-werror.diff

**Comment by magicus** [comment]
> Yes, that's correct. See: https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-16/debian/patches/hotspot-disable-werror.diff

@glaubitz That patch seems unlikely to work on modern JDK?! The old hotspot build system was removed ages ago.

**Review by tstuefe — APPROVED** [review]
Patch itself seems fine and trivial.

Lest someone removes the cast, maybe add a comment that this is for the sake of glibc problems on sparc? Leave it up to you.

**Comment by shipilev** [comment]
> > Apparently, it was never fixed in glibc for sparc64? We can still make a defensive cast to `long`.
> 
> Can you file a bug report to the glibc bug tracker?

I see that was already reported as [glibc bug #23821](https://sourceware.org/bugzilla/show_bug.cgi?id=23821), and glibc maintainers decided not to fix it. So, we can still make a defensive cast to (long), which would be no-op if the type is in fact long.

I verified that latest glibc sources still have:

```
sysdeps/unix/sysv/linux/bits/types/siginfo_t.h
110:	    __SI_BAND_TYPE si_band;	/* Band event for SIGPOLL.  */

sysdeps/unix/sysv/linux/sparc/bits/siginfo-arch.h
9:# define __SI_BAND_TYPE int
```

**Comment by shipilev** [comment]
> Lest someone removes the cast, maybe add a comment that this is for the sake of glibc problems on sparc? Leave it up to you.

Yes. I added a comment block describing what happens here, plus a link to glibc bugtracker.

**Comment by glaubitz** [comment]
> > Yes, that's correct. See: https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-16/debian/patches/hotspot-disable-werror.diff
> 
> @glaubitz That patch seems unlikely to work on modern JDK?! The old hotspot build system was removed ages ago.

This is for OpenJDK-16, was that changed recently.

In any case, Matthias Klose is the maintainer of the package in Debian and Ubuntu. I will let him know.

**Comment by shipilev** [comment]
All right, I suppose everyone is happy with this patch? I'll be integrating it soon.

**Comment by glaubitz** [comment]
> All right, I suppose everyone is happy with this patch? I'll be integrating it soon.

Yep, fine with me. Thanks for taking care of this.

**Pull request closed without merging**
