### PR TITLE
8326100: DeflaterDictionaryTests should use Deflater.getBytesWritten instead of Deflater.getTotalOut

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this test-only cleanup PR in preparation for deprecating `Deflater.getTotalOut()` in JDK-8326096.

This PR replaces various calls in`test/jdk/java/util/zip/DeflaterDictionaryTests.java` to `Deflater.getTotalOut()` with calls to `Deflater.getBytesWritten()` when formatting some debugging output lines. 

Additionally, various debug output lines claim to print the result of calling `Deflater.getAdler`, but instead prints the output of `Deflater.getTotalOut'. This PR fixes this to print the actual Adler value instead.

Testing and verification: This is a test-only fix affecting only debug output. I have added the `noreg-self` label to the issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326100](https://bugs.openjdk.org/browse/JDK-8326100): DeflaterDictionaryTests should use Deflater.getBytesWritten instead of Deflater.getTotalOut (**Enhancement** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17901/head:pull/17901` \
`$ git checkout pull/17901`

Update a local copy of the PR: \
`$ git checkout pull/17901` \
`$ git pull https://git.openjdk.org/jdk.git pull/17901/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17901`

View PR using the GUI difftool: \
`$ git pr show -t 17901`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17901.diff">https://git.openjdk.org/jdk/pull/17901.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17901#issuecomment-1950122230)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
The hazard when the format specifiers are all %s.

**Comment by eirbjo** [comment]
Thanks for your review Alan! 

> The hazard when the format specifiers are all %s.

Not sure I understand your comment since all arguments are of the same type (int) anyhow, I guess they would still be easy to get wrong or in the wrong order. Was that the hazard you refer to?

Anyhow, I went ahead and replaced the %s specifiers with the more specific decimal integer specifier %d.

WDYT?

**Review by jaikiran — APPROVED** [review]
The changes look good to me.

**Comment by AlanBateman** [comment]
> Thanks for your review Alan!
> 
> > The hazard when the format specifiers are all %s.
> 
> Not sure I understand your comment since all arguments are of the same type (int) anyhow, I guess they would still be easy to get wrong or in the wrong order. Was that the hazard you refer to?

Yes, it's easy to get a silent mismatch. In this case, the first message printed by testByteArray, the second parameter should have been the Adler but it was actually printing the number of bytes written. You've fixed it, and switched to %d, so all good.

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
