### PR TITLE
8302464: Parallel: Remove unreachable code in callers of numa_has_static_binding

### PR DESCRIPTION
**Pull request by albertnetymk**
Trivial removing dead code.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302464](https://bugs.openjdk.org/browse/JDK-8302464): Parallel: Remove unreachable code in callers of numa_has_static_binding

### Reviewers
 * [Leo Korinth](https://openjdk.org/census#lkorinth) (@lkorinth - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12559/head:pull/12559` \
`$ git checkout pull/12559`

Update a local copy of the PR: \
`$ git checkout pull/12559` \
`$ git pull https://git.openjdk.org/jdk pull/12559/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12559`

View PR using the GUI difftool: \
`$ git pr show -t 12559`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12559.diff">https://git.openjdk.org/jdk/pull/12559.diff</a>

</details>

### CODE REVIEW

**Comment by lkorinth** [comment]
I can not see the removal of `os::numa_has_static_binding()` itself, only the usage of it.

**Comment by albertnetymk** [comment]
Removing an `os` API can be controversial (even if it's unused), so I kept it outside of this gc-only PR.

**Comment by lkorinth** [comment]
> Removing an `os` API can be controversial (even if it's unused), so I kept it outside of this gc-only PR.

If we are to support non static NUMA bindings, the predicate methods are themself easier to restore than the code we now remove. If we remove them in this fix, we can later easier see the context of _why_ the predicate was removed, and _what_ it was used for. It will be easier to follow version control history. If we have no non-gc users of this method, I think we can see it as effecting gc only.

**Review by lkorinth — APPROVED** [review]
Looks great, thanks for removing the method as well. I will create an investigation enhancement to see if  `MutableNUMASpace::update()`  can be removed as well. Approved!

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
