### PR TITLE
8300819: -Dfile.encoding=Cp943C option does not work as expected since jdk18

### PR DESCRIPTION
**Pull request by takiguc**
On jdk17, following testcase works fine on Linux platform.

Testcase
```
$ cat cstest1.java
import java.nio.charset.*;

public class cstest1 {
  public static void main(String[] args) throws Exception {
    Charset cs = Charset.defaultCharset();
    System.out.println(cs + ", " + cs.getClass() + ", " + cs.getClass().getModule());
  }
}
```
```
$ ~/jdk-17.0.6+10/bin/java -Dfile.encoding=Cp943C -showversion cstest1
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
x-IBM943C, class sun.nio.cs.ext.IBM943C, module jdk.charsets
```

But it does not work as expected on jdk18 and jdk21b06
```
$ ~/jdk-18.0.2.1+1/bin/java -Dfile.encoding=Cp943C -showversion cstest1
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
UTF-8, class sun.nio.cs.UTF_8, module java.base
$ ~/jdk-21/bin/java -Dfile.encoding=Cp943C -showversion cstest1
openjdk version "21-ea" 2023-09-19
OpenJDK Runtime Environment (build 21-ea+6-365)
OpenJDK 64-Bit Server VM (build 21-ea+6-365, mixed mode, sharing)
UTF-8, class sun.nio.cs.UTF_8, module java.base
```

Fixed result is as follows:
```
$ java -Dfile.encoding=Cp943C -showversion PrintDefaultCharset
openjdk version "21-internal" 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.jdktest.jdk)
OpenJDK 64-Bit Server VM (build 21-internal-adhoc.jdktest.jdk, mixed mode, sharing)
x-IBM943C
```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300819](https://bugs.openjdk.org/browse/JDK-8300819): -Dfile.encoding=Cp943C option does not work as expected since jdk18 ⚠️ Issue is not open.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12132/head:pull/12132` \
`$ git checkout pull/12132`

Update a local copy of the PR: \
`$ git checkout pull/12132` \
`$ git pull https://git.openjdk.org/jdk.git pull/12132/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12132`

View PR using the GUI difftool: \
`$ git pr show -t 12132`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12132.diff">https://git.openjdk.org/jdk/pull/12132.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12132#issuecomment-1399521907)

### CODE REVIEW

**Comment by AlanBateman** [comment]
I don't think this is the right thing to do.

In terms of setup, there wasn't a documented/supported way to change the default charset in JDK 17 or earlier. JDK 18 was the first release where it documented (via an implNote) that it is possible to start with -Dfile.encoding=COMPAT to derive the default charset from native.encoding (which in turns depends on the locale and charset of the underlying operating system).

The second point is that it is too fragile to assume that Charset.defaultCharset won't be called until after phase 2 of startup. For the system to be reliable, the default charset must be in java.base. The proposed test may work in some cases but it won't work in cases where there are command line options and Java code executed at startup that indirectly uses Charset.defaultCharset.

That said, the change does highlight an issue in StaticProperty.<clinit> where it calls Charset.defaultCharset(), which in turn will StaticProperty.FILE_ENCODING before that class is fully initialized. This is nothing to do with trying to run with -Dfile.encoding=Cp943C of course but this part of the initialization will need to be re-examined to avoid issues.

**Comment by takiguc** [comment]
First, Sorry I forgot to change Copyright date.

@AlanBateman , I appreciate your reply.
In my understanding,

- io stream side can use native.encoding system property.
- Now file.encoding system property is used for non-io stream.

This issue is related #11908 .
I need a solution to use the Cp943C charset as default charset.
Please give me some suggestion.

**Comment by AlanBateman** [comment]
I'm trying to understand what the real issue is. The java.base module on Linux builds includes SJIS, MS932, and PCK. Is there a Linux configuration in Japanese environments where the default charset in any JDK release is IBM943C? Same question for AIX builds that is the only build that includes IBM943C in java.base.

**Comment by takiguc** [comment]
Hello @AlanBateman .
Sorry for your confusion.

Java8 works `-Dfile.encoding=Cp943C` option on Linux. Since many users are migrating from Java8, I'm getting similar requests from my clients. Cp943C is not supported by Linux natively, but some clients want to use same encoding with Linux and AIX.

Japanese AIX environment supports IBM-943(Cp943C)/IBM-eucJP(Cp29626C)/UTF-8 encoding.
Cp943C and Cp29626C are in base.base module on AIX platform.

**Comment by AlanBateman** [comment]
> Java8 works `-Dfile.encoding=Cp943C` option on Linux. Since many users are migrating from Java8, I'm getting similar requests from my clients. Cp943C is not supported by Linux natively, but some clients want to use same encoding with Linux and AIX.
> 
> Japanese AIX environment supports IBM-943(Cp943C)/IBM-eucJP(Cp29626C)/UTF-8 encoding. Cp943C and Cp29626C are in base.base module on AIX platform.

It's never been supported to run with -Dfile.encoding=Cp943C. It may have worked in JDK 8 but I doubt it could have worked consistently since JDK 9 because the default charset is derived before it's possible to locate charset implementations outside of java.base.

I think it would be useful to know a bit more about the environment. It sounds like it might be AIX -> Linux migration but I'm curious if you have any insight into why these applications depend on default charset being Cp943C. Is it text files that are opened without specifying the charset or is is something else?

**Comment by naotoj** [comment]
For the `jnuCharset` initialization revisit, I filed an issue: https://bugs.openjdk.org/browse/JDK-8300916

**Comment by AlanBateman** [comment]
> As described before, JDK17 worked with `-Dfile.encoding=Cp943C`, and JDK18 changed the behavior. I heard some apps had already ported on JDK17 with the option, and works.

It's bug that this "worked" in JDK 9+ as the default charset needs to be in java.base.

**Comment by takiguc** [comment]
> Do you know if there is any configuration on AIX that would derive Cp943C as the default charset? That is, are they running with -Dfile.encoding=Cp943C on the AIX systems or is it chosen by default. This goes to the question as to whether they just moving these applications to Linux and expecting the default charset to be the same.

In my understanding, my client uses `-Dfile.encoding=Cp943C` option on Japanese IBM-943 locale on AIX.
Default charset on Japanese IBM-943 locale with IBM Java8 and OpenJDK JDK11+ is x-IBM943C(Cp943C).
(We need to use `-Dfile.encoding=Cp943C` for OpenJDK JDK8.)
We never thought we could just move to Linux because of JEP-400. But we don't move the apps all at once to Linux.
We expected that we could change default charset by `-Dfile.encoding=Cp943C`, at least until Java8 EOS.

> Do you know which APIs they are using? We filled in the gaps many releases ago so that all APIs that do encoding/decoding allow the charset to be specified and I'm wondering why they don't use those.

We checked String.getByte()/new String(...)/Reader/Writer/ByteArrayOutputStream.toString()...
Is there good way to pick up which parts need to be fixed ?

**Comment by AlanBateman** [comment]
> We checked String.getByte()/new String(...)/Reader/Writer/ByteArrayOutputStream.toString()... Is there good way to pick up which parts need to be fixed ?

I don't think there is so you may have to audit the classes that use Charset.defaultCharset. Do you have any information on what it does, that might help narrow it down.

**Comment by AlanBateman** [comment]
I think this PR can be closed as the default charset must be in java.base.

**Pull request closed without merging**
