### PR TITLE
8264827: Large mapped buffer/segment crash the VM when calling isLoaded

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Avoid overflow when calculating the number of pages for large mapped segment sizes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264827](https://bugs.openjdk.java.net/browse/JDK-8264827): Large mapped buffer/segment crash the VM when calling isLoaded

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 1816b200a9da028df6a64e2f625d6ca053dfb328
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3378/head:pull/3378` \
`$ git checkout pull/3378`

Update a local copy of the PR: \
`$ git checkout pull/3378` \
`$ git pull https://git.openjdk.java.net/jdk pull/3378/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3378`

View PR using the GUI difftool: \
`$ git pr show -t 3378`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3378.diff">https://git.openjdk.java.net/jdk/pull/3378.diff</a>

</details>

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Note for reviewers on the test. A 3GB file is sufficient to demonstrate the issue in the old code, as follows (with a 4K page size, since the narrowing cast of size is the significant issue):

```
jshell> int pageSize() { return 4 * 1024; }
|  created method pageSize()

jshell> int pageCount(long size) { return (int)(size + (long)pageSize() - 1L) / pageSize(); }
|  created method pageCount(long)

jshell> pageCount(3L * 1024L * 1024L * 1024L)
$3 ==> -262143
```

**Review by AlanBateman — APPROVED** [review]
Looks okay to me.

**Review by mcimadamore — APPROVED** [review]
Looks good - thanks for fixing.

**Pull request closed without merging**
