### PR TITLE
6560981: (cal) unused local variables in GregorianCalendar, etc.

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
Problem: Unused variables in GregorianCalendar, JapaneseImperialCalendar, and Base Calendar.

Fix: Removed all unused variables in bug description except normalizedYear in JapaneseImpericalCalendar.getActualMaximum.() as there was no matching unused variable within that method.

Additionally removed realDayOfYear in GregorianCalendar.computeFields.() due to redundancy.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6560981](https://bugs.openjdk.org/browse/JDK-6560981): (cal) unused local variables in GregorianCalendar, etc.

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Brent Christian](https://openjdk.org/census#bchristi) (@bchristi-git - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10585/head:pull/10585` \
`$ git checkout pull/10585`

Update a local copy of the PR: \
`$ git checkout pull/10585` \
`$ git pull https://git.openjdk.org/jdk pull/10585/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10585`

View PR using the GUI difftool: \
`$ git pr show -t 10585`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10585.diff">https://git.openjdk.org/jdk/pull/10585.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
LGTM

**Review by bchristi-git — APPROVED** [review]
Looks fine

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
