### PR TITLE
17927：update ArrayList.java constructor annotation

### PR DESCRIPTION
**Pull request by isxiaoxina**
/isxiaoxina@gmail.com I have signed the OCA. My githup name is isxiaoxina. I observed that the arraylist code was modified after version 1.6, but the comments were not modified accordingly. Although it is reflected in add, it is not rigorous.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17930/head:pull/17930` \
`$ git checkout pull/17930`

Update a local copy of the PR: \
`$ git checkout pull/17930` \
`$ git pull https://git.openjdk.org/jdk.git pull/17930/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17930`

View PR using the GUI difftool: \
`$ git pr show -t 17930`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17930.diff">https://git.openjdk.org/jdk/pull/17930.diff</a>

</details>

### CODE REVIEW

**Comment by isxiaoxina** [comment]
Hello.



I have signed the OCA and I confirm that this submission follows the terms of the OCA. You can view my signature history here: [Provide OCA signature link or related information]


My githup name：isxiaoxina
Thank you for your review!

**Comment by liach** [comment]
See https://bugs.openjdk.org/browse/JDK-8143020 (So your title would be `8143020:
no-arg ArrayList constructor specification has confusing wording about capacity`)

The description that it has capacity of 10 is correct, it's just that the actual backing array is lazily allocated. So the wording would be like:

```java
/**
 * Constructs an empty list with an initial capacity of ten.
 *
 * @implNote The internal array is lazily allocated upon first element addition.
 */
```

**Comment by isxiaoxina** [comment]
> See https://bugs.openjdk.org/browse/JDK-8143020 (So your title would be `8143020: no-arg ArrayList constructor specification has confusing wording about capacity`)
> 
> The description that it has capacity of 10 is correct, it's just that the actual backing array is lazily allocated. So the wording would be like:
> 
> ```java
> /**
>  * Constructs an empty list with an initial capacity of ten.
>  *
>  * @implNote The internal array is lazily allocated upon first element addition.
>  */
> ```

Thank you,i konw。

**Comment by liach** [comment]
You can also type `/signed` in a line in a comment, so the bot will add an `oca-verify` label, before you can contribute.

**Comment by robilad** [comment]
> Hello.
> 
> I have signed the OCA and I confirm that this submission follows the terms of the OCA. You can view my signature history here: [Provide OCA signature link or related information]
> 
> My githup name：isxiaoxina Thank you for your review!

Hi, since your OCA submission could not be processed, you'd need to resubmit the OCA, please. See e-mail for details.

**Pull request closed without merging**
