### PR TITLE
8264018: AArch64: NEON loadV2 and storeV2 addressing is wrong

### PR DESCRIPTION
**Pull request by nsjian**
AArch64 c2 loadV2 and storeV2 are used for Vector API mask value load/store with size of halfword. Their load/store immediate offset should be similar to other vector load/store, e.g. loadV4/storeV4, valid only for unscaled signed offset of imm9 or scaled unsigned offset of imm12:scale. This patch also groups other loadVs/storeVs together in the ad file.

Verified with tier1 and jtreg vector api cases, though I cannot reproduce this issue.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264018](https://bugs.openjdk.java.net/browse/JDK-8264018): AArch64: NEON loadV2 and storeV2 addressing is wrong

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3168/head:pull/3168`
`$ git checkout pull/3168`

To update a local copy of the PR:
`$ git checkout pull/3168`
`$ git pull https://git.openjdk.java.net/jdk pull/3168/head`

### CODE REVIEW

**Comment by theRealAph** [comment]
I admire your decision to tidy up the files, but I can't easily see what exactly has changed.

**Comment by adinn** [comment]
The change is to the memory operand of the first load and store rules. It was special cased to memory and is now vmem2 (just as the relocated rules used vmem4, vmem8 etc).

**Review by adinn — APPROVED** [review]
Looks good.

**Comment by nsjian** [comment]
> I admire your decision to tidy up the files, but I can't easily see what exactly has changed.

I should explain the change in my PR comment better. I have two commits in this PR, the first commit is the main change to fix the issue, which adds vmem2 opclass for loadv2 and storev2, as their imm address ranges should be different from others. The second commit is the code tidy up.

**Comment by theRealAph** [comment]
> > I admire your decision to tidy up the files, but I can't easily see what exactly has changed.
> 
> I should explain the change in my PR comment better. I have two commits in this PR, the first commit is the main change to fix the issue, which adds vmem2 opclass for loadv2 and storev2, as their imm address ranges should be different from others. The second commit is the code tidy up.

Ah, so it is. My mistake.

**Review by theRealAph — APPROVED** [review]

**Comment by nsjian** [comment]
Thank you for the review! @adinn @theRealAph

**Pull request closed without merging**
