### PR TITLE
8300204: Sealed-class hierarchy graph missing nodes

### PR DESCRIPTION
**Pull request by liach**
Please review this simple patch that fixes the package determination for nested classes in the `@sealedGraph` taglet.

Current JDK 21:
https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/foreign/MemoryLayout.html
https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/foreign/ValueLayout.html
image

This patch:
https://cr.openjdk.org/~liach/8300204/java.base/java/lang/foreign/MemoryLayout.html
https://cr.openjdk.org/~liach/8300204/java.base/java/lang/foreign/ValueLayout.html
image

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300204](https://bugs.openjdk.org/browse/JDK-8300204): Sealed-class hierarchy graph missing nodes

### Reviewers
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13875/head:pull/13875` \
`$ git checkout pull/13875`

Update a local copy of the PR: \
`$ git checkout pull/13875` \
`$ git pull https://git.openjdk.org/jdk.git pull/13875/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13875`

View PR using the GUI difftool: \
`$ git pr show -t 13875`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13875.diff">https://git.openjdk.org/jdk/pull/13875.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13875#issuecomment-1539328431)

### CODE REVIEW

**Comment by minborg** [comment]
Looks good to me! Thanks for providing this patch. Unfortunately, I am not a reviewer so we have to get someone else to review it.

**Comment by jonathan-gibbons** [comment]
I'll sponsor this, given the comment by @minborg 
https://github.com/openjdk/jdk/pull/13875#issuecomment-1539537777

**Comment by jonathan-gibbons** [comment]
> Looks good to me! Thanks for providing this patch. Unfortunately, I am not a reviewer so we have to get someone else to review it.

@minborg You may not be an OpenJDK "R"eviewer yet, but you can still "review" changes and report whether you approve the changes.

**Pull request closed without merging**
