### PR TITLE
8281122: [IR Framework] Cleanup IR matching code in preparation for JDK-8280378

### PR DESCRIPTION
**Pull request by chhagedorn**
This patch does some restructurings and refactorings of the `IRMatcher.java` class in preparation for adding IR matching support on different compile phases with [JDK-8280378](https://bugs.openjdk.java.net/browse/JDK-8280378). There are no semantic changes of how IR matching is eventually done on regexes and how the results are checked with the `failOn` and `counts` constraints provided by the user. The only user-visible change is an improved output format of matching failures.

The old format also did not report a `counts` constraint failure correctly. It wrongly used the format of `failOn` failures which was misleading. This is also fixed by this patch.

**Example:**
```
@Test
@IR(counts = {IRNode.STORE_F, "!= 1"}) // fails
@IR(counts = {IRNode.STORE_F, "2", IRNode.LOAD_F, "> 1"}) // both constraints fail
public void test1() {
    fFld = 4.2f;
}

@Test
@IR(failOn = IRNode.ALLOC, counts = {IRNode.STORE_F, ">= 2"}) // failOn and counts fail
public void test2() {
    fFld = 4.2f;
    o = new Object();
}
````
_Failure outputs:_
<details>
  <summary>Old format</summary>

```
Failed IR Rules (3)
------------------
- Method "public void ir_framework.tests.Testi.test1()":
  * @IR rule 1: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", "!= 1"}, applyIfNot={})"
    - counts: Graph contains wrong number of nodes:
        Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
        Expected 1 but found 1 node:
          25  StoreF  ===  5  7  24  21  [[ 16 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test1 @ bci:3 (line 48)
  * @IR rule 2: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", "2", "(\\d+(\\s){2}(LoadF.*)+(\\s){2}===.*)", "> 1"}, applyIfNot={})"
    - counts: Graph contains wrong number of nodes:
        Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
        Expected 2 but found 1 node:
          25  StoreF  ===  5  7  24  21  [[ 16 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test1 @ bci:3 (line 48)
        Regex 2: (\d+(\s){2}(LoadF.*)+(\s){2}===.*)
        Expected 1 but found 0 nodes.

- Method "public void ir_framework.tests.Testi.test2()":
  * @IR rule 1: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={"(.*precise .*\\R((.*(?i:mov|xorl|nop|spill).*|\\s*|.*LGHI.*)\\R)*.*(?i:call,static).*wrapper for: _new_instance_Java)"}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", ">= 2"}, applyIfNot={})"
    - failOn: Graph contains forbidden nodes:
        Regex 1: (.*precise .*\R((.*(?i:mov|xorl|nop|spill).*|\s*|.*LGHI.*)\R)*.*(?i:call,static).*wrapper for: _new_instance_Java)
        Matched forbidden node:
          1a5     movq    RSI, precise java/lang/Object: 0x00007fb188007318:Constant:exact *	# ptr
    1af     call,static  wrapper for: _new_instance_Java
    - counts: Graph contains wrong number of nodes:
        Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
        Expected 2 but found 1 node:
          25  StoreF  ===  5  7  24  21  [[ 19  236  36  179  220 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test2 @ bci:3 (line 55)
```
</details>
<details>
  <summary>New format</summary>

```
Failed IR Rules (3) of Methods (2)
----------------------------------
1) Method "public void ir_framework.tests.Testi.test1()" - [Failed IR rules: 2]:
   * @IR rule 1: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", "!= 1"}, applyIfNot={})"
     - counts: Graph contains wrong number of nodes:
       * Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
         - Failed comparison: [found] 1 != 1 [given]
         - Matched node:
           * 25  StoreF  ===  5  7  24  21  [[ 16 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test1 @ bci:3 (line 48)
   * @IR rule 2: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", "2", "(\\d+(\\s){2}(LoadF.*)+(\\s){2}===.*)", "> 1"}, applyIfNot={})"
     - counts: Graph contains wrong number of nodes:
       * Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
         - Failed comparison: [found] 1 = 2 [given]
         - Matched node:
           * 25  StoreF  ===  5  7  24  21  [[ 16 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test1 @ bci:3 (line 48)
       * Regex 2: (\d+(\s){2}(LoadF.*)+(\s){2}===.*)
         - Failed comparison: [found] 0 > 1 [given]
         - No nodes matched!

2) Method "public void ir_framework.tests.Testi.test2()" - [Failed IR rules: 1]:
   * @IR rule 1: "@compiler.lib.ir_framework.IR(applyIf={}, applyIfAnd={}, failOn={"(.*precise .*\\R((.*(?i:mov|xorl|nop|spill).*|\\s*|.*LGHI.*)\\R)*.*(?i:call,static).*wrapper for: _new_instance_Java)"}, applyIfOr={}, counts={"(\\d+(\\s){2}(StoreF.*)+(\\s){2}===.*)", ">= 2"}, applyIfNot={})"
     - failOn: Graph contains forbidden nodes:
       * Regex 1: (.*precise .*\R((.*(?i:mov|xorl|nop|spill).*|\s*|.*LGHI.*)\R)*.*(?i:call,static).*wrapper for: _new_instance_Java)
         - Matched forbidden node:
           * 1a5     movq    RSI, precise java/lang/Object: 0x00007fd3c4007318:Constant:exact *	# ptr
             1af     call,static  wrapper for: _new_instance_Java
     - counts: Graph contains wrong number of nodes:
       * Regex 1: (\d+(\s){2}(StoreF.*)+(\s){2}===.*)
         - Failed comparison: [found] 1 >= 2 [given]
         - Matched node:
           * 25  StoreF  ===  5  7  24  21  [[ 19  236  36  179  220 ]]  @ir_framework/tests/Testi+12 *, name=fFld, idx=4;  Memory: @ir_framework/tests/Testi:NotNull+12 *, name=fFld, idx=4; !jvms: Testi::test2 @ bci:3 (line 55)
```
</details>

**New class structure:**

The old `IRMatcher` class mixed different tasks such as parsing, IR annotation verification, IR matching and failure reporting together. This made it difficult to extend the existing code to add IR matching support on different compile phases. Therefore, the class was split to separate the different tasks:
- parser classes (`IREncodingParser`, `HotSpotPidFileParser`, `IRMethodParser` etc.)
- entity classes for the different parts of an `@IR` annotation (`IRMethod`, `IRRule`, `Counts`, `FailOn` etc.)
- match result classes for each entity class to provide a formatted failure message (`IRMethodMatchResult`, `IRRuleMatchResult` etc.)

The main structure of the new classes will be kept in JDK-8280378 but will be further improved to match the new needs.

**Testing:**
- Normal tier testing including tier5 and 6 where the IR framework tests are executed.
- Testing of this patch in Valhalla with tier1-3 + some Valhalla-specific stress testing

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281122](https://bugs.openjdk.java.net/browse/JDK-8281122): [IR Framework] Cleanup IR matching code in preparation for JDK-8280378

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7533/head:pull/7533` \
`$ git checkout pull/7533`

Update a local copy of the PR: \
`$ git checkout pull/7533` \
`$ git pull https://git.openjdk.java.net/jdk pull/7533/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7533`

View PR using the GUI difftool: \
`$ git pr show -t 7533`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7533.diff">https://git.openjdk.java.net/jdk/pull/7533.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Great work! It's hard to review though so I'm trusting your expertise in this area. Approved.

**Comment by chhagedorn** [comment]
Thanks a lot for your review Tobias! Yes, unfortunately, it is quite an extensive cleanup which makes it hard to review.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review!

**Pull request closed without merging**
