### PR TITLE
8282657: Code cleanup: removing double semicolons at the end of lines

### PR DESCRIPTION
**Pull request by matteobaccan**
Hi

I have reviewed the code for removing double semicolons at the end of lines

all the best
matteo

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282657](https://bugs.openjdk.java.net/browse/JDK-8282657): Code cleanup: removing double semicolons at the end of lines

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Bradford Wetmore](https://openjdk.java.net/census#wetmore) (@bradfordwetmore - **Reviewer**)
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7268/head:pull/7268` \
`$ git checkout pull/7268`

Update a local copy of the PR: \
`$ git checkout pull/7268` \
`$ git pull https://git.openjdk.java.net/jdk pull/7268/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7268`

View PR using the GUI difftool: \
`$ git pr show -t 7268`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7268.diff">https://git.openjdk.java.net/jdk/pull/7268.diff</a>

</details>

### CODE REVIEW

**Comment by matteobaccan** [comment]
Hi

I have pushed this PR about 1 month ago. Only 3 days ago OCA was accepted.
Now: what is the next step?

This is a cleanup PR that removes some double semicolons at the end of some lines inside the JDK code.

ciao
matteo

**Comment by TheShermanTanker** [comment]
Hi @matteobaccan

The next step would be to create a relevant issue on the tracker and set it to track this PR. Since you don't have the ability to create new issues on the JBS yet I'll help you create one, please rename your PR title to 8282657 and the system should take care of the rest and automatically mark your PR as ready for review after setting it to track the corresponding JBS entry.

**Review by LanceAndersen — APPROVED** [review]
The changes look OK.  The copyright year probably should be updated as part of this PR

**Comment by matteobaccan** [comment]
Hi Lance

I can make a second commit updating the copyright year

Tell me if this is necessary

ciao
matteo

**Review by RogerRiggs — CHANGES_REQUESTED** [review]
We usually request that these be be broken up by area to attract the appropriate reviewers and avoid eye-strain.  The client modules are usually separated out, as are hotspot.
And corresponding tests.
This kind of change is pretty low value for the code base and requires the involvement of quite a few reviewers.
If you had ask ahead of time, I would have suggested finding something with more value.

**Comment by magicus** [comment]
@RogerRiggs Otoh, this change is really trivial. I have verified that all changes are replacing trailing ";;" in Java code. These are all clearly typos. I think it's nice that we try to strive for a high quality, and while you are correct this is maybe not the most pressing issue, I think it's nice to get a cleanup like this done. 

I'd argue that this is a trivial change. If you are worried, let's get a couple of more reviewers. I can't see the need to split this up per area.

**Review by magicus — APPROVED** [review]
/reviewers 2

**Comment by prrace** [comment]
Looks like  there's only one client source code file touched
Most of the client changes are only in jtreg tests - and this is very trivial, so I'm OK with them being included here.

**Review by prrace — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Nice tidy of the code.

Is there anything that can be done to prevent re-introduction of this trivial problem?  Perhaps a new Skara bot jcheck option similar to what is already in place for trailing whitespace?

**Review by bradfordwetmore — APPROVED** [review]
LGTM also.  

Similar suggestion for updating copyrights.

**Review by jddarcy — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
I eyeballed the diff file and all seems okay.

Thanks,
David

**Comment by TheShermanTanker** [comment]
Nice, good work matteo

Should I change the JBS issue title to match the PR title, or is it preferred for the PR title to change?

**Comment by miraculix0815** [comment]
This PR changes a comment in javax/swing/RepaintManager.java. This commented out code should be removed altogether in another PR? Because its an System.out.println and because its commented out code.

**Comment by erikj79** [comment]
> Should I change the JBS issue title to match the PR title, or is it preferred for the PR title to change?

They need to match. You can either do it manually, or change the title to just the bug number and the bot will change it for you.

**Comment by TheShermanTanker** [comment]
> > Should I change the JBS issue title to match the PR title, or is it preferred for the PR title to change?
> 
> They need to match. You can either do it manually, or change the title to just the bug number and the bot will change it for you.

Alright, I can't change the title of the PR, I guess it'll be easier for me to change the issue instead

**Comment by kevinrushforth** [comment]
> What problem are you having editing the PR header? You should be able to do so as the author of the PR

Exactly. You should see an "Edit" button near the right edge of the PR title. See the attached image:

PR-title

**Comment by kevinrushforth** [comment]
But as the JBS title and PR title now match, this is a moot point.

**Pull request closed without merging**
