### PR TITLE
8297301: Cleanup unused methods in JavaUtilJarAccess

### PR DESCRIPTION
**Pull request by pandaapo**
The cache named `signerToCodeSource` in `JarVerifier` is never used now.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297301](https://bugs.openjdk.org/browse/JDK-8297301): Cleanup unused methods in JavaUtilJarAccess

### Reviewers
 * [Weijun Wang](https://openjdk.org/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11072/head:pull/11072` \
`$ git checkout pull/11072`

Update a local copy of the PR: \
`$ git checkout pull/11072` \
`$ git pull https://git.openjdk.org/jdk pull/11072/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11072`

View PR using the GUI difftool: \
`$ git pr show -t 11072`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11072.diff">https://git.openjdk.org/jdk/pull/11072.diff</a>

</details>

### CODE REVIEW

**Comment by pandaapo** [comment]
> The method is not called since JDK 9, and that's why I set Affected Version/s to 8-pool. We don't intend to fix this in the current release.

Oh. Could you tell me where I should submit this PR? `jdk8u`?

**Comment by seanjmullan** [comment]
If you want to instead do some general cleanup in this class for JDK 20, you could instead remove this method and several other unused methods from `JarVerifier`.

**Comment by pandaapo** [comment]
> If you want to instead do some general cleanup in this class for JDK 20, you could instead remove this method and several other unused methods from `JarVerifier`.

Before I began to make general cleanup, I looked up from this unused method `JarVerifier#mapSignersToCodeSource()`and found all related call stacks:
未命名文件
Can I remove these method in `JarFile`, `JavaUtilJarAccess` and its only implementation `JavaUtilJarAccessImpl`?

**Comment by seanjmullan** [comment]
> > If you want to instead do some general cleanup in this class for JDK 20, you could instead remove this method and several other unused methods from `JarVerifier`.
> 
> Before I began to make general cleanup, I looked up from this unused method `JarVerifier#mapSignersToCodeSource()`and found all related call stacks: 未命名文件 Can I also remove these methods from `JarFile`, `JavaUtilJarAccess` and its only implementation `JavaUtilJarAccessImpl`?

Yes. I believe the `setEagerValidation` method can also be removed and all code that calls it.

**Comment by seanjmullan** [comment]
> Because `JarVerifier#setEagerValidation` will be removed, the field `eagerValidation` will always be false.
> 
> There are some codes using this field: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/jar/JarVerifier.java#L361-L381 Can I remove the `eagerValidation` condition from `if(eagerValidation && sigFileSigners.get(name) != null)`?

You can remove the whole if block since `eagerValidation` will never be true, and this block was only performed if it was true.

> 
> If I can, can I remove this field from `JarVerifier` then?

Yes.

**Pull request closed without merging**
