### PR TITLE
8308978: regression with a deadlock involving FollowReferences

### PR DESCRIPTION
**Pull request by alexmenkov**
The change fixes regression from JDK-8299414.
There is a deadlock between JvmtiVTMSTransitionDisabler and EscapeBarrier when virtual threads are in mount/unmount transition:
EscapeBarrier requests deoptimization which requires thread suspension.
JvmtiVTMSTransitionDisabler ctor waits until all in progress VTMS transitions complete, but they cannot be completed as thread is suspended.
To avoid the deadlock mount/unmount transitions should be completed before EscapeBarrier stuff.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308978](https://bugs.openjdk.org/browse/JDK-8308978): regression with a deadlock involving FollowReferences

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [b2df4fd6](https://git.openjdk.org/jdk/pull/14233/files/b2df4fd68e19decbc1202ffb7524410af3fd1ed5)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14233/head:pull/14233` \
`$ git checkout pull/14233`

Update a local copy of the PR: \
`$ git checkout pull/14233` \
`$ git pull https://git.openjdk.org/jdk.git pull/14233/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14233`

View PR using the GUI difftool: \
`$ git pr show -t 14233`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14233.diff">https://git.openjdk.org/jdk/pull/14233.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14233#issuecomment-1569250467)

### CODE REVIEW

**Review by sspitsyn — COMMENTED** [review]
The fix itself looks good.
However, the following tests must be removed from the `test/hotspot/jtreg/ProblemList-Virtual.txt`:
```
vmTestbase/nsk/jdi/ObjectReference/referringObjects/referringObjects001/referringObjects001.java 8308978 generic-all
vmTestbase/nsk/jdi/ReferenceType/instances/instances001/instances001.java 8308978 generic-all
vmTestbase/nsk/jdi/ReferenceType/instances/instances003/instances003.java 8308978 generic-all
vmTestbase/nsk/jdi/ReferenceType/instances/instances004/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/MonitorWaitedRequest/addThreadFilter/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/VirtualMachine/instanceCounts/instancecounts002/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/stress/serial/monitorEvents002/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/stress/serial/heapwalking001/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/stress/serial/heapwalking002/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jdi/stress/serial/mixed001/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jvmti/scenarios/allocation/AP04/ap04t001/TestDescription.java 8308978 generic-all
vmTestbase/nsk/jvmti/scenarios/allocation/AP04/ap04t002/TestDescription.java 8308978 generic-all
```
Thanks,
Serguei

**Review by sspitsyn — APPROVED** [review]
It looks good now.
Thanks,
Serguei

**Comment by dholmes-ora** [comment]
Please ensure tier 1-5 testing been carried out before this is integrated and re-enables all those tests! Thanks.

**Review by lmesnik — APPROVED** [review]

**Comment by alexmenkov** [comment]
Something went wrong after 1st merge, testing failed with OOMEInAQS (which is problem-listed)
Remerged and rerun testing

**Comment by sspitsyn** [comment]
> Something went wrong after 1st merge, testing failed with OOMEInAQS (which is problem-listed)

How do you run tests? Do you run tiers 1-6 or something else as well?
Please, remember that the tier-5 runs the needed SVC tests with `main.wrapper=virtual`.

**Comment by alexmenkov** [comment]
> > Something went wrong after 1st merge, testing failed with OOMEInAQS (which is problem-listed)
> 
> How do you run tests? Do you run tiers 1-5 or something else as well? Please, remember that the tier-5 runs the needed SVC tests with `main.wrapper=virtual`.

tier1-tier5 as per David's request
initial fix (before the test were problem-listed) was tested with JTREG_TEST_THREAD_FACTORY=Virtual

**Comment by alexmenkov** [comment]
tier 1-5 passed (there are 3 failed tests, but they are not related to FollowReferences)

**Pull request closed without merging**
