### PR TITLE
8265440: IGV: make node selection more visible

### PR DESCRIPTION
**Pull request by jyukutyo**
This pull request makes node selection more visible.

At present when selecting node, node name is bolder. In addition to that, thickness of the border is bolder after applying this code.

I tested manually. Here are the images that I took before and after applying this patch as follows.

### After Applying the Code
スクリーンショット 2021-06-02 14 40 28スクリーンショット 2021-06-02 14 40 43

Left: "0 Root" and "3 Start" are selected.
Right: "0 Root" and "3 Start" are selected. "3 Start" and "7 Parm" are highlighted.

スクリーンショット 2021-06-02 14 44 04スクリーンショット 2021-06-02 14 44 11

Left: The upper right slot of "20 MergeMem" are selected.
Right: The upper right slot of "20 MergeMem" are selected and highlighted.

### Before Applying the Code
スクリーンショット 2021-06-02 14 41 55スクリーンショット 2021-06-02 14 42 29

Left: "0 Root" and "3 Start" are selected.
Right: "0 Root" and "3 Start" are selected. "3 Start" and "7 Parm" are highlighted.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265440](https://bugs.openjdk.java.net/browse/JDK-8265440): IGV: make node selection more visible

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4298/head:pull/4298` \
`$ git checkout pull/4298`

Update a local copy of the PR: \
`$ git checkout pull/4298` \
`$ git pull https://git.openjdk.java.net/jdk pull/4298/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4298`

View PR using the GUI difftool: \
`$ git pr show -t 4298`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4298.diff">https://git.openjdk.java.net/jdk/pull/4298.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by neliasso — APPROVED** [review]
Good.

**Comment by jyukutyo** [comment]
Thanks for your reviews, Christian and Nils.

**Comment by jyukutyo** [comment]
Could someone possibly sponsor this pull request?

Thanks,
Koichi

**Comment by jyukutyo** [comment]
Thank you for your cooperation, Christian!

**Pull request closed without merging**
