### PR TITLE
8294461: wrong effectively final determination by javac

### PR DESCRIPTION
**Pull request by archiecobbs**
This bug involves DA/DU analysis and the concept of "effectively final".

Here's the test case, which the compiler currently but incorrectly accepts:
```java
    for (int i = 0; i < 10; i++) {
        Runnable r = () -> System.out.println(i);   // variable i is NOT effectively final
        break;                                      // even though "i++" is never reached
    }
```

For the purposes of "effectively final", it doesn't matter whether an assignment statement that makes a variable no longer effectively final is actually reachable or not. In cases like the `i++` above, a statement can be actually unreachable yet not "unreachable" according to the JLS, and so it does not generate an "unreachable statement" compiler error (which would otherwise hide this bug).

JLS §4.12.4 states:

> A local variable declared by a statement and whose declarator has an initializer ... is effectively final if all of the following are true:
> ...
> • It never occurs as the operand of a prefix or postfix increment or decrement operator (§15.14, §15.15).

So clearly `i` is not effectively final.

However, the way we calculate effective finality does not involve actually looking for increment/decrement operators. Instead, it's determined during DA/DU analysis: non-final variables have an `EFFECTIVELY_FINAL` flag which is initialized to `true` and then cleared if/when we encounter contrary evidence - e.g., an assignment when not DU.

For simplicity, the DA/DU analysis works like this:
* Variables with initializers are treated like variables without initializers followed by an assignment
* Increment/decrement operators are treated as a normal read followed by a normal assignment.

These are reasonable. However, it means this clause of JLS §4.12.4 effectively applies:

> A local variable declared by a statement and whose declarator lacks an initializer is effectively final if all of the following are true:
> ...
> • Whenever it occurs as the left hand side in an assignment expression, it is definitely unassigned and not definitely assigned before the assignment...

The bug with the current code is that when we see an assignment to a variable with the `EFFECTIVELY_FINAL` flag still set, we clear the flag if the variable is not DU, but we are _not_ clearing the flag if the variable is DA, as required above. This happens with the `i++` statement because, by virtue of it being actually unreachable, `i` is both DA and DU before that statement.

This patch corrects that omission.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294461](https://bugs.openjdk.org/browse/JDK-8294461): wrong effectively final determination by javac

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [449a5efb](https://git.openjdk.org/jdk/pull/10856/files/449a5efbd28c6d7eb2ec702c861afbb3447e4702)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10856/head:pull/10856` \
`$ git checkout pull/10856`

Update a local copy of the PR: \
`$ git checkout pull/10856` \
`$ git pull https://git.openjdk.org/jdk pull/10856/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10856`

View PR using the GUI difftool: \
`$ git pr show -t 10856`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10856.diff">https://git.openjdk.org/jdk/pull/10856.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks sensible

**Comment by archiecobbs** [comment]
Thanks for the review.

**Comment by jddarcy** [comment]
Should this change have a (retroactive) CSR and/or release note?

**Comment by archiecobbs** [comment]
There shouldn't be any spec change implied by this change. From my understanding, the compiler was not following the spec, which says that the variable `i` in the example is not effectively final. This change makes the compiler follow the spec and generate a "local variables referenced from a lambda expression must be final or effectively final" error.

Regarding release notes, I'll let someone else who has more familiarity with the release process comment on that.

**Comment by vicente-romero-oracle** [comment]
> Should this change have a (retroactive) CSR and/or release note?

well on similar cases we have done a CSR, I didn't realize during the review, sorry. I guess a CSR should probably be enough. I can help reviewing it

**Comment by jddarcy** [comment]
> There shouldn't be any spec change implied by this change. From my understanding, the compiler was not following the spec, which says that the variable `i` in the example is not effectively final. This change makes the compiler follow the spec and generate a "local variables referenced from a lambda expression must be final or effectively final" error.
> 
> Regarding release notes, I'll let someone else who has more familiarity with the release process comment on that.

Adding some additional context, there CSR reviews both specification changes and behavioral changes considered to have sufficiently high compatibility impact.

This change renders code that previously (if erroneously) compiled into a compilation error, which is a source compatibility concern. (Changing code that compiles into code that doesn't compile is considered a more serious change than the reverse.)

Offhand, I don't know how often such coding patterns may appear in practice; we should some internal tooling which can help gauge that. A modification that may be suggested is only doing the updated check for source level 20 and higher.

HTH

**Pull request closed without merging**
