### PR TITLE
8267657: Add missing PrintC1Statistics before incrementing counters

### PR DESCRIPTION
**Pull request by kelthuzadx**
Trivial change to add missing PrintC1Statistics before incrementing counters.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267657](https://bugs.openjdk.java.net/browse/JDK-8267657): Add missing PrintC1Statistics before incrementing counters

### Reviewers
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4178/head:pull/4178` \
`$ git checkout pull/4178`

Update a local copy of the PR: \
`$ git checkout pull/4178` \
`$ git pull https://git.openjdk.java.net/jdk pull/4178/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4178`

View PR using the GUI difftool: \
`$ git pr show -t 4178`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4178.diff">https://git.openjdk.java.net/jdk/pull/4178.diff</a>

</details>

### CODE REVIEW

**Comment by kelthuzadx** [comment]
PING：Can I have a review of this trivial change？Thanks.

**Review by veresov — APPROVED** [review]
Looks good.

**Comment by kelthuzadx** [comment]
Thank you Igor for the review!

**Pull request closed without merging**
