### PR TITLE
8324723: GHA: Upgrade some actions to avoid deprecated Node 16

### PR DESCRIPTION
**Pull request by shipilev**
Current GHA runs produce lots of warnings:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3, actions/download-artifact@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

We can upgrade to new actions to get the Node20.

Release/migration notes:
https://github.com/actions/cache#whats-new
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
https://github.com/actions/github-script#breaking-changes

There is also msys2/setup-msys2, which was pinned by [JDK-8310259](https://bugs.openjdk.org/browse/JDK-8310259). We need at least 2.21.0 to get Node 20:
https://github.com/msys2/setup-msys2/blob/main/CHANGELOG.md. I think we can unpin msys2 at this point.

I don't think any of the migration problems outlined in those notes apply to our workflows.

Additional testing:
 - [x] 3x GHA with cleaned caches
 - [x]  3x GHA with populated caches (default)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324723](https://bugs.openjdk.org/browse/JDK-8324723): GHA: Upgrade some actions to avoid deprecated Node 16 (**Enhancement** - P4)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17572/head:pull/17572` \
`$ git checkout pull/17572`

Update a local copy of the PR: \
`$ git checkout pull/17572` \
`$ git pull https://git.openjdk.org/jdk.git pull/17572/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17572`

View PR using the GUI difftool: \
`$ git pr show -t 17572`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17572.diff">https://git.openjdk.org/jdk/pull/17572.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17572#issuecomment-1911652323)

### CODE REVIEW

**Comment by magicus** [comment]
Thanks for looking into this.

**Comment by shipilev** [comment]
Sure. I am now running multiple GHA iterations and trying to see if msys2 is stable enough to unpin.

**Comment by shipilev** [comment]
I think this is ready for review now.

**Review by jerboaa — APPROVED** [review]
Thanks for doing this cleanup! Seems fine to me. Not really sure how to test the msys2 pinning issue...

**Comment by jaikiran** [comment]
Hello Severin,

> Not really sure how to test the msys2 pinning issue...

I think as long as the GitHub actions jobs complete successfully, that should be enough. However, it's not a guarantee that the issue won't happen again (previously, we have had a case where it worked for a few hours or maybe a day when Java 17 was used https://bugs.openjdk.org/browse/JDK-8309934 before it started failing again). If it does happen again, in a subsequent PR, we can always pin it back and spend some more time investigating what's going on.

**Comment by shipilev** [comment]
> Thanks for doing this cleanup! Seems fine to me. Not really sure how to test the msys2 pinning issue...

[We pinned it](https://bugs.openjdk.org/browse/JDK-8310259) because there were weird failures in jtreg builds on Windows due to msys2 bug. This is why I tested GHA multiple times, every time clearing the caches to trigger jtreg rebuild. msys2 had fixed lots of possibly related path conversion bugs recently, but it is really hard to pin-point what went into latest release. Example of msys2 fix: https://github.com/msys2/MSYS2-packages/pull/4200 -- done in Nov 2023, so the current release hopefully has all these.

**Comment by shipilev** [comment]
> [We pinned it](https://bugs.openjdk.org/browse/JDK-8310259) because there were weird failures in jtreg builds on Windows due to msys2 bug. This is why I tested GHA multiple times, every time clearing the caches to trigger jtreg rebuild. msys2 had fixed lots of possibly related path conversion bugs recently, but it is really hard to pin-point what went into latest release. Example of msys2 fix: [msys2/MSYS2-packages#4200](https://github.com/msys2/MSYS2-packages/pull/4200) -- done in Nov 2023, so the current release hopefully has all these.

Ah-ha! Here we go. This PR proposes updating to `v2.22.0` (Update base distribution to 20240113). So the easy test for the hypothesis that November fixes got there is trying with `v2.21.0` (Update base distribution to 20231026). Tried it right now, and Windows jtreg build [immediately failed](https://github.com/shipilev/jdk/actions/runs/7694685053/job/20965966992):

```
/bin/cp /d/a/jdk/jdk/jtreg/src/build/deps/jtharness/build/binaries/lib/javatest.jar D:/a/jdk/jdk/jtreg/src/build/images/jtreg/lib/javatest.jar
CLASSPATH="D:/a/jdk/jdk/jtreg/src/build/classes;D:/a/jdk/jdk/jtreg/src/build/deps/jtharness/build/binaries/lib/javatest.jar;" \
    C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/17.0.10-7/x64/bin/javac --release 11 -Xlint:all,-options,-deprecation -Werror \
	-d D:/a/jdk/jdk/jtreg/src/build/classes \
	-encoding ASCII \
	../src/share/classes/com/sun/javatest/diff/Diff.java ../src/share/classes/com/sun/javatest/diff/DiffReader.java ../src/share/classes/com/sun/javatest/diff/Fault.java ../src/share/classes/com/sun/javatest/diff/Help.java ../src/share/classes/com/sun/javatest/diff/HTMLReporter.java ../src/share/classes/com/sun/javatest/diff/HTMLWriter.java ../src/share/classes/com/sun/javatest/diff/Main.java ../src/share/classes/com/sun/javatest/diff/MultiMap.java ../src/share/classes/com/sun/javatest/diff/Reporter.java ../src/share/classes/com/sun/javatest/diff/ReportReader.java ../src/share/classes/com/sun/javatest/diff/SimpleReporter.java ../src/share/classes/com/sun/javatest/diff/StandardDiff.java ../src/share/classes/com/sun/javatest/diff/StatusComparator.java ../src/share/classes/com/sun/javatest/diff/SuperDiff.java ../src/share/classes/com/sun/javatest/diff/WorkDirectoryReader.java
/bin/sh: line 1: C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/17.0.10-7/x64/bin/javac: Bad address
make: *** [jtdiff.gmk:36: D:/a/jdk/jdk/jtreg/src/build/classes.com.sun.javatest.diff.ok] Error 126
```

This gives me even more confidence in msys2 unpinning :)

**Comment by jerboaa** [comment]
> This gives me even more confidence in msys2 unpinning :)

Sounds great! As @jaikiran said, we could pin again if it re-surfaces.

**Comment by shipilev** [comment]
I think this would be a sane plan going forward. Push this PR to mainline. Wait 4 weeks and see if there is any fallout from this. Provided there is no fallout, backport this to 21u-dev, 17u-dev, 11u-dev. This gets the changes to update releases repos and starts testing it there. The April releases would not be affected, since we would plan for integration past the fork for April stabilization. Provided there is no fallout in update release treese, we would have all pipelines at Node 20 actions by June release. 

I don't think GitHub has set a firm date for Node 16 removal -- the [note](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) says "Our plan is to transition all actions to run on Node 20 by Spring 2024." -- which I assume means there would be some window while older actions still run.

**Review by magicus — APPROVED** [review]
Looks good to me. 

I'm not even sure why you are calling this "unpinning" of msys. You are fixing it at `@v2.22.0`. Unless the msys action is in the habit of releasing new updates with the same patch version, then this is in effect a pin. The difference is just that the previous pin was for a specific commit, rather than a released version, which is (in my eyes) a markedly worse strategy. (I guess we did that, instead of reverting to a specific released version, due to problems finding a working version, but I don't remember).

To really "unpin" msys would be to require just a specific major version, like `msys2/setup-msys2@v2`. You are not doing that, and I don't recommend doing that. :-)

**Comment by shipilev** [comment]
> To really "unpin" msys would be to require just a specific major version, like `msys2/setup-msys2@v2`. You are not doing that, and I don't recommend doing that. :-)

Right. I meant to say that we are effectively undoing the latest pin to a particular commit, that we did for reasons, and those reasons do not seem to apply anymore.

**Comment by shipilev** [comment]
All right, let's see what happens.

/integrate

**Pull request closed without merging**
