### PR TITLE
8268301: Closed test: compiler/c2/6371167/Test.java fails after JDK-8267904

### PR DESCRIPTION
**Pull request by huishi-hs**
…after loop"

This reverts commit b05fa02e7413fdcc40969645309e3e9d4442c78d.

This trigger an assertion in Oracle Closed test, see JBS https://bugs.openjdk.java.net/browse/JDK-8268301

will submit again after fixing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268301](https://bugs.openjdk.java.net/browse/JDK-8268301): Closed test: compiler/c2/6371167/Test.java fails after JDK-8267904

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4384/head:pull/4384` \
`$ git checkout pull/4384`

Update a local copy of the PR: \
`$ git checkout pull/4384` \
`$ git pull https://git.openjdk.java.net/jdk pull/4384/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4384`

View PR using the GUI difftool: \
`$ git pr show -t 4384`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4384.diff">https://git.openjdk.java.net/jdk/pull/4384.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

Please, fix PR's title - it is truncated.

**Review by dean-long — APPROVED** [review]
The back-out change looks correct.

**Comment by dean-long** [comment]
The JBS title needs to be changed to match the PR title, right?

**Comment by dean-long** [comment]
I think you’re good to integrate now.

**Comment by huishi-hs** [comment]
gc/shenandoah/compiler/TestLinkToNativeRBP.java  failes on LinuxX64 and MacOs X64. Might releated with https://bugs.openjdk.java.net/browse/JDK-8268279.

Tested locally on LinuxX64 it fails with/without this revert.

**Pull request closed without merging**
