### PR TITLE
8342588: Shenandoah: Pull shared closures together in one header

### PR DESCRIPTION
**Pull request by shipilev**
Currently we have shenandoahClosures.hpp and shenandoahOopClosures.hpp, each of which have some closure inside. There is no reason to have this separation, and we should really just merge everything in one header. I also did a bit of mechanical renames. There should be no semantic change with this patch.

Additional testing:
 - [x] Linux x86_64 server fastdebug, `hotspot_gc_shenandoah`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342588](https://bugs.openjdk.org/browse/JDK-8342588): Shenandoah: Pull shared closures together in one header (**Enhancement** - P4)

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Author)
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21579/head:pull/21579` \
`$ git checkout pull/21579`

Update a local copy of the PR: \
`$ git checkout pull/21579` \
`$ git pull https://git.openjdk.org/jdk.git pull/21579/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21579`

View PR using the GUI difftool: \
`$ git pr show -t 21579`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21579.diff">https://git.openjdk.org/jdk/pull/21579.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21579#issuecomment-2421941392)

### CODE REVIEW

**Review by earthling-amzn — APPROVED** [review]

**Review by kdnilsen — APPROVED** [review]
Thanks.

**Review by simonis — APPROVED** [review]
In general looks good. The only thing I'd recommend (if you haven't done that already anyway) would be to configure with `--disable-precompiled-headers` and see if the build still works (i.e. if all the inline functions are still all available in all the compilation units).

**Comment by shipilev** [comment]
> In general looks good. The only thing I'd recommend (if you haven't done that already anyway) would be to configure with `--disable-precompiled-headers` and see if the build still works (i.e. if all the inline functions are still all available in all the compilation units).

Yup, thanks! GHA also does it for us.

**Comment by shipilev** [comment]
Thanks all!

/integrate

**Pull request closed without merging**
