### PR TITLE
8264734: Some SA classes could use better hashCode() implementation

### PR DESCRIPTION
**Pull request by kariya-mitsuru**
The current `hashCode` implementation of SA's Address subclasses ignores the upper 32 bits of the long value.
This PR changes to use `Long.hashCode` instead.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264734](https://bugs.openjdk.java.net/browse/JDK-8264734): Some SA classes could use better hashCode() implementation

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to ac5c266025ca76c862b36de0ed428d9a33f0ceec

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3522/head:pull/3522` \
`$ git checkout pull/3522`

Update a local copy of the PR: \
`$ git checkout pull/3522` \
`$ git pull https://git.openjdk.java.net/jdk pull/3522/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3522`

View PR using the GUI difftool: \
`$ git pr show -t 3522`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3522.diff">https://git.openjdk.java.net/jdk/pull/3522.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — CHANGES_REQUESTED** [review]
Please update all copyright dates to 2021. Only the latest year need to be updated. For example:

`  * Copyright (c) 2002, 2013, Oracle and/or its affiliates. All rights reserved.`

 becomes
  
`  * Copyright (c) 2002, 2021, Oracle and/or its affiliates. All rights reserved.`

**Comment by plummercj** [comment]
Also, please give a proper description of the PR. Right now it just says "…tation"

**Comment by plummercj** [comment]
@kariya-mitsuru Please enable github actions on your jdk personal fork to enable the pre-submit testing. Start with the following link:

https://github.com/kariya-mitsuru/jdk/actions

Click on "Settings" tab and then click on "Actions" from the list of settings (not the "Actions" tab). Then enable "Allow all Actions".

**Comment by kariya-mitsuru** [comment]
> Please update all copyright dates to 2021.

Thank you for your advice.
I just updated the copyright.

**Comment by kariya-mitsuru** [comment]
> Also, please give a proper description of the PR. Right now it just says "…tation"

Oh, I'm embarrassed to say that I completely overlooked this.
I just updated the description.

**Comment by kariya-mitsuru** [comment]
> Please enable github actions on your jdk personal fork to enable the pre-submit testing.

I've changed the settings.

**Comment by kevinjwalls** [comment]
Hi -
There are a few more places where a long is cast to an int and used as the hashCode:
  
open/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/windbg/amd64/WindbgAMD64Thread.java
  
  public int hashCode() {
    return (int) getThreadID();
  }
 
open/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/windbg/x86/WindbgX86Thread.java 
open/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/gc/shenandoah/ShenandoahHeapRegion.java

open/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/RemoteDebuggerClient.java
  getThreadHashCode(long id) returns a truncated long if it caught a RemoteException.

If you have time, these could all use the same change?

**Comment by kariya-mitsuru** [comment]
> If you have time, these could all use the same change?

I have enough time to change them.
May I mix that fix into this pull request?

**Comment by kevinjwalls** [comment]
Thanks, yes it can definitely be an update to this change.

We can update the bug title, as I notice that is specific to Address classes, but as there are only a few more methods doing the same truncation, it makes sense to include them. e.g.  "Some SA classes could use better hashCode() implementation."

**Comment by kariya-mitsuru** [comment]
I found that `WindbgAARCH64Thread` is the same, so I changed it together.

**Comment by kariya-mitsuru** [comment]
I have changed the title of this PR but I cannot change the title of issue JDK-8264734.
Would it have been better if I hadn't changed the title?

**Review by kevinjwalls — APPROVED** [review]

**Comment by kevinjwalls** [comment]
No problem.  I updated the JBS title to match this.  I think the warning about title mismatch has gone.

**Comment by kariya-mitsuru** [comment]
@plummercj Would you please check the changes again?
Also, should I issue the /contributor command?

**Comment by plummercj** [comment]
Some of the more recently changed files need updates to the Oracle copyrights. WindbgAARCH64Thread.java is a bit different in that it currently only has a 2020 date. It should be changed to the following:

` * Copyright (c) 2020, 2021, Oracle and/or its affiliates. All rights reserved.`

Note I'm only requesting updates to the Oracle copyrights.

**Comment by kariya-mitsuru** [comment]
Hi,

Would anyone sponsor it?

Best regards,
Mitsuru

**Comment by kariya-mitsuru** [comment]
Thanks a lot!

**Pull request closed without merging**
