### PR TITLE
8308960: Decouple internal Version and OperatingSystem classes

### PR DESCRIPTION
**Pull request by RogerRiggs**
Decouple the jdk.internal.util OperatingSystem and Version classes to simplify class loading and avoid an indirect cyclic initialization.

Move the method to get the current OS version from OperatingSystem to the Version class and its initialization.
Revert to using String.toUpperCase() instead of custom code to uppercase.

Update the uses of OperatingSystem.version to be Version.current.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308960](https://bugs.openjdk.org/browse/JDK-8308960): Decouple internal Version and OperatingSystem classes

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to [f6332cd9](https://git.openjdk.org/jdk/pull/14181/files/f6332cd94ff5b7ce6e122e2c5bba0db7de46a88f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14181/head:pull/14181` \
`$ git checkout pull/14181`

Update a local copy of the PR: \
`$ git checkout pull/14181` \
`$ git pull https://git.openjdk.org/jdk.git pull/14181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14181`

View PR using the GUI difftool: \
`$ git pr show -t 14181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14181.diff">https://git.openjdk.org/jdk/pull/14181.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14181#issuecomment-1564531188)

### CODE REVIEW

**Comment by dfuch** [comment]
Should we take this opportunity to rename jdk.internal.util.Version into something like `OsVersion` to make it more clear what the `current()` method actually returns?

**Comment by RogerRiggs** [comment]
> Should we take this opportunity to rename `jdk.internal.util.Version` into something like `OsVersion` to make it more clear what its `current()` method actually returns?

ok, it will give a bit more flavor; there are already multiple version classes with little to distinguish them.

**Review by mlchung — APPROVED** [review]
Looks good.  Thanks for fixing this.  It will allow ClassFileDumper to use `Path`.

**Comment by mlchung** [comment]
> Should we take this opportunity to rename `jdk.internal.util.Version` into something like `OsVersion` to make it more clear what its `current()` method actually returns?

Alternatively, move `Version` record as a nested class in `OperatingSystem`.

**Comment by dfuch** [comment]
> Alternatively, move `Version` record as a nested class in `OperatingSystem`.

That would work WRT naming, but I thought the point was to not have to load OperatingSystem in order to load Version?

**Comment by mlchung** [comment]
I mean static member class of `OperatingSystem`.

**Comment by RogerRiggs** [comment]
For the time being, I think they should be independent and clearly named.
The nesting creates a very unwieldy and long name.  (Not withstanding imports)

**Review by dfuch — COMMENTED** [review]
Thanks for renaming the class. The renaming LGTM.

**Pull request closed without merging**
