### PR TITLE
8313927: Examine if Arrays.mismatch can be simplified

### PR DESCRIPTION
**Pull request by cl4es**
On various microbenchmarks we've seen that Arrays.mismatch slightly underperform naive loops for small array inputs, both on x86 and aarch64. Since small arrays may be more common this hampers adoption in performance-sensitive locales that want to take more explicit advantage of mismatch vectorization.

One contributor appears to be some extra branchy logic outside of the intrinsified Arrays.vectorizedMismatch method. Simplifying the outside logic so that we always call the intrinsified code seem to be a win on x86 and aarch64 in C1 and C2 modes. There's a cost for such small inputs in the interpreter.

Benchmark results will be added in comments.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313927](https://bugs.openjdk.org/browse/JDK-8313927): Examine if Arrays.mismatch can be simplified (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15197/head:pull/15197` \
`$ git checkout pull/15197`

Update a local copy of the PR: \
`$ git checkout pull/15197` \
`$ git pull https://git.openjdk.org/jdk.git pull/15197/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15197`

View PR using the GUI difftool: \
`$ git pr show -t 15197`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15197.diff">https://git.openjdk.org/jdk/pull/15197.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
x86_64, sandybridge:
```
Name                                 (size) (utf16) Cnt    Base   Error     Test   Error  Unit  Diff%
StringComparisons.endsWith                6    true  15   8.523 ± 0.111    8.063 ± 0.110 ns/op   5.4% (p = 0.000*)
StringComparisons.endsWith                6   false  15  10.793 ± 0.084    7.898 ± 0.415 ns/op  26.8% (p = 0.000*)
StringComparisons.endsWith               15    true  15  10.986 ± 0.053   10.942 ± 0.797 ns/op   0.4% (p = 0.825 )
StringComparisons.endsWith               15   false  15  10.992 ± 0.880   11.355 ± 0.727 ns/op  -3.3% (p = 0.199 )
StringComparisons.endsWith             1024    true  15  63.550 ± 0.959   63.310 ± 0.509 ns/op   0.4% (p = 0.371 )
StringComparisons.endsWith             1024   false  15  40.272 ± 0.600   38.922 ± 2.698 ns/op   3.4% (p = 0.061 )
StringComparisons.endsWithMismatch        6    true  15   9.565 ± 0.772    8.758 ± 0.484 ns/op   8.4% (p = 0.001*)
StringComparisons.endsWithMismatch        6   false  15  10.713 ± 0.638    8.600 ± 0.313 ns/op  19.7% (p = 0.000*)
StringComparisons.endsWithMismatch       15    true  15   9.790 ± 0.320    9.649 ± 0.221 ns/op   1.4% (p = 0.144 )
StringComparisons.endsWithMismatch       15   false  15   9.677 ± 0.089    9.636 ± 0.382 ns/op   0.4% (p = 0.670 )
StringComparisons.endsWithMismatch     1024    true  15  71.572 ± 2.778   69.448 ± 5.667 ns/op   3.0% (p = 0.179 )
StringComparisons.endsWithMismatch     1024   false  15  32.988 ± 0.924   33.865 ± 0.198 ns/op  -2.7% (p = 0.002*)
StringComparisons.regionMatches           6    true  15   8.443 ± 0.011    8.014 ± 0.204 ns/op   5.1% (p = 0.000*)
StringComparisons.regionMatches           6   false  15   9.801 ± 0.090    8.928 ± 0.378 ns/op   8.9% (p = 0.000*)
StringComparisons.regionMatches          15    true  15   8.659 ± 0.098    7.170 ± 0.571 ns/op  17.2% (p = 0.000*)
StringComparisons.regionMatches          15   false  15   8.138 ± 0.181    7.613 ± 0.804 ns/op   6.5% (p = 0.018 )
StringComparisons.regionMatches        1024    true  15  59.811 ± 0.606   57.994 ± 0.799 ns/op   3.0% (p = 0.000*)
StringComparisons.regionMatches        1024   false  15  31.782 ± 0.515   31.660 ± 0.710 ns/op   0.4% (p = 0.570 )
StringComparisons.regionMatchesCI         6    true  15  10.426 ± 0.080   10.405 ± 0.030 ns/op   0.2% (p = 0.327 )
StringComparisons.regionMatchesCI         6   false  15   9.226 ± 0.146    9.245 ± 0.142 ns/op  -0.2% (p = 0.701 )
StringComparisons.regionMatchesCI        15    true  15  13.235 ± 0.062   13.253 ± 0.156 ns/op  -0.1% (p = 0.665 )
StringComparisons.regionMatchesCI        15   false  15  12.592 ± 0.026   12.621 ± 0.074 ns/op  -0.2% (p = 0.134 )
StringComparisons.regionMatchesCI      1024    true  15 339.770 ± 1.547  340.371 ± 2.343 ns/op  -0.2% (p = 0.384 )
StringComparisons.regionMatchesCI      1024   false  15 353.729 ± 4.022  354.651 ± 4.828 ns/op  -0.3% (p = 0.548 )
StringComparisons.regionMatchesRange      6    true  15   9.875 ± 0.256    8.768 ± 0.626 ns/op  11.2% (p = 0.000*)
StringComparisons.regionMatchesRange      6   false  15  10.383 ± 0.017    8.528 ± 0.510 ns/op  17.9% (p = 0.000*)
StringComparisons.regionMatchesRange     15    true  15  11.623 ± 0.175   11.130 ± 0.138 ns/op   4.2% (p = 0.000*)
StringComparisons.regionMatchesRange     15   false  15  10.691 ± 0.110   10.205 ± 0.014 ns/op   4.5% (p = 0.000*)
StringComparisons.regionMatchesRange   1024    true  15  64.434 ± 2.220   65.707 ± 0.402 ns/op  -2.0% (p = 0.034 )
StringComparisons.regionMatchesRange   1024   false  15  38.242 ± 0.606   38.528 ± 0.182 ns/op  -0.7% (p = 0.079 )
StringComparisons.startsWith              6    true  15   8.602 ± 0.014    7.162 ± 0.688 ns/op  16.7% (p = 0.000*)
StringComparisons.startsWith              6   false  15   8.946 ± 0.096    7.754 ± 0.493 ns/op  13.3% (p = 0.000*)
StringComparisons.startsWith             15    true  15  10.478 ± 0.060    8.945 ± 0.611 ns/op  14.6% (p = 0.000*)
StringComparisons.startsWith             15   false  15   9.827 ± 0.061    8.942 ± 1.205 ns/op   9.0% (p = 0.009*)
StringComparisons.startsWith           1024    true  15  63.273 ± 0.182   61.558 ± 1.647 ns/op   2.7% (p = 0.001*)
StringComparisons.startsWith           1024   false  15  38.911 ± 0.975   37.304 ± 1.194 ns/op   4.1% (p = 0.000*)
StringComparisons.startsWithMismatch      6    true  15   8.472 ± 0.210    7.327 ± 0.539 ns/op  13.5% (p = 0.000*)
StringComparisons.startsWithMismatch      6   false  15   9.054 ± 0.101    8.532 ± 0.774 ns/op   5.8% (p = 0.015 )
StringComparisons.startsWithMismatch     15    true  15   8.653 ± 0.319    7.477 ± 0.409 ns/op  13.6% (p = 0.000*)
StringComparisons.startsWithMismatch     15   false  15   8.041 ± 0.014    7.137 ± 0.631 ns/op  11.2% (p = 0.000*)
StringComparisons.startsWithMismatch   1024    true  15  59.921 ± 0.910   58.817 ± 0.793 ns/op   1.8% (p = 0.001*)
StringComparisons.startsWithMismatch   1024   false  15  32.124 ± 0.047   31.864 ± 0.296 ns/op   0.8% (p = 0.003*)
  * = significant
```

**Comment by cl4es** [comment]
Mac M1:
```
Name                                 (size) (utf16) Cnt    Base   Error     Test   Error  Unit  Diff%
StringComparisons.endsWith                6    true  15   3,280 ± 0,061    2,960 ± 0,012 ns/op   9,7% (p = 0,000*)
StringComparisons.endsWith                6   false  15   4,303 ± 0,009    4,219 ± 0,019 ns/op   1,9% (p = 0,000*)
StringComparisons.endsWith               15    true  15   6,125 ± 0,112    5,674 ± 0,009 ns/op   7,4% (p = 0,000*)
StringComparisons.endsWith               15   false  15   5,811 ± 0,088    5,445 ± 0,020 ns/op   6,3% (p = 0,000*)
StringComparisons.endsWith             1024    true  15  61,115 ± 0,190   60,976 ± 0,437 ns/op   0,2% (p = 0,243 )
StringComparisons.endsWith             1024   false  15  32,536 ± 0,164   32,373 ± 0,089 ns/op   0,5% (p = 0,002*)
StringComparisons.endsWithMismatch        6    true  15   3,302 ± 0,017    2,921 ± 0,005 ns/op  11,5% (p = 0,000*)
StringComparisons.endsWithMismatch        6   false  15   4,288 ± 0,027    4,105 ± 0,018 ns/op   4,3% (p = 0,000*)
StringComparisons.endsWithMismatch       15    true  15   4,961 ± 0,018    4,647 ± 0,017 ns/op   6,3% (p = 0,000*)
StringComparisons.endsWithMismatch       15   false  15   5,798 ± 0,078    5,505 ± 0,042 ns/op   5,1% (p = 0,000*)
StringComparisons.endsWithMismatch     1024    true  15  58,977 ± 0,822   58,102 ± 0,482 ns/op   1,5% (p = 0,001*)
StringComparisons.endsWithMismatch     1024   false  15  31,858 ± 0,483   31,109 ± 0,124 ns/op   2,3% (p = 0,000*)
StringComparisons.regionMatches           6    true  15   4,035 ± 0,111    3,742 ± 0,004 ns/op   7,2% (p = 0,000*)
StringComparisons.regionMatches           6   false  15   4,601 ± 0,086    3,955 ± 0,033 ns/op  14,0% (p = 0,000*)
StringComparisons.regionMatches          15    true  15   3,628 ± 0,036    3,230 ± 0,029 ns/op  11,0% (p = 0,000*)
StringComparisons.regionMatches          15   false  15   2,823 ± 0,049    2,521 ± 0,004 ns/op  10,7% (p = 0,000*)
StringComparisons.regionMatches        1024    true  15  57,878 ± 0,808   57,438 ± 1,080 ns/op   0,8% (p = 0,188 )
StringComparisons.regionMatches        1024   false  15  30,997 ± 0,425   30,557 ± 0,640 ns/op   1,4% (p = 0,026 )
StringComparisons.regionMatchesCI         6    true  15   5,765 ± 0,056    5,726 ± 0,021 ns/op   0,7% (p = 0,014 )
StringComparisons.regionMatchesCI         6   false  15   4,721 ± 0,026    4,700 ± 0,023 ns/op   0,5% (p = 0,016 )
StringComparisons.regionMatchesCI        15    true  15   8,001 ± 0,142    7,801 ± 0,024 ns/op   2,5% (p = 0,000*)
StringComparisons.regionMatchesCI        15   false  15   7,312 ± 0,144    7,145 ± 0,134 ns/op   2,3% (p = 0,002*)
StringComparisons.regionMatchesCI      1024    true  15 225,555 ± 3,320  224,817 ± 2,366 ns/op   0,3% (p = 0,461 )
StringComparisons.regionMatchesCI      1024   false  15 224,146 ± 2,854  223,373 ± 0,816 ns/op   0,3% (p = 0,296 )
StringComparisons.regionMatchesRange      6    true  15   3,589 ± 0,032    3,295 ± 0,007 ns/op   8,2% (p = 0,000*)
StringComparisons.regionMatchesRange      6   false  15   4,653 ± 0,142    4,062 ± 0,010 ns/op  12,7% (p = 0,000*)
StringComparisons.regionMatchesRange     15    true  15   6,266 ± 0,190    5,782 ± 0,009 ns/op   7,7% (p = 0,000*)
StringComparisons.regionMatchesRange     15   false  15   5,825 ± 0,128    5,435 ± 0,007 ns/op   6,7% (p = 0,000*)
StringComparisons.regionMatchesRange   1024    true  15  57,537 ± 0,637   56,552 ± 0,080 ns/op   1,7% (p = 0,000*)
StringComparisons.regionMatchesRange   1024   false  15  30,861 ± 0,498   30,118 ± 0,321 ns/op   2,4% (p = 0,000*)
StringComparisons.startsWith              6    true  15   3,062 ± 0,139    2,811 ± 0,010 ns/op   8,2% (p = 0,000*)
StringComparisons.startsWith              6   false  15   4,144 ± 0,072    3,580 ± 0,038 ns/op  13,6% (p = 0,000*)
StringComparisons.startsWith             15    true  15   5,414 ± 0,130    4,991 ± 0,013 ns/op   7,8% (p = 0,000*)
StringComparisons.startsWith             15   false  15   5,275 ± 0,094    4,852 ± 0,066 ns/op   8,0% (p = 0,000*)
StringComparisons.startsWith           1024    true  15  58,642 ± 1,569   57,142 ± 0,842 ns/op   2,6% (p = 0,002*)
StringComparisons.startsWith           1024   false  15  30,439 ± 0,364   30,063 ± 0,055 ns/op   1,2% (p = 0,001*)
StringComparisons.startsWithMismatch      6    true  15   3,858 ± 0,047    3,480 ± 0,004 ns/op   9,8% (p = 0,000*)
StringComparisons.startsWithMismatch      6   false  15   4,437 ± 0,070    3,790 ± 0,007 ns/op  14,6% (p = 0,000*)
StringComparisons.startsWithMismatch     15    true  15   3,428 ± 0,012    3,118 ± 0,004 ns/op   9,0% (p = 0,000*)
StringComparisons.startsWithMismatch     15   false  15   2,815 ± 0,020    2,559 ± 0,006 ns/op   9,1% (p = 0,000*)
StringComparisons.startsWithMismatch   1024    true  15  57,075 ± 0,182   56,930 ± 0,066 ns/op   0,3% (p = 0,006*)
StringComparisons.startsWithMismatch   1024   false  15  30,465 ± 0,425   30,344 ± 0,089 ns/op   0,4% (p = 0,267 )
  * = significant
  ```

**Comment by cl4es** [comment]
On both x64 and aarch64 we see the largest relative speedup on arrays small enough that they would previously not call into the intrinsified routine, suggesting these code stubs are now so optimized that they are always beneficial to call into. On larger arrays the overhead reductions gradually fall into noise, which is to be expected.

**Comment by cl4es** [comment]
`-Xint` results show that taking the detour through `ArraysSupport.vectorizedMismatch` can be detrimental for some cases that were very quick (in the interpreter) before, aligning with the interpreted performance of slightly larger input values. 

x64, -Xint:
```Name                                 (size) (utf16) Cnt       Base       Error        Test      Error  Unit    Diff%
StringComparisons.endsWith                6    true   5   1568.653 ±   127.050    1464.435 ±   75.249 ns/op     6.6% (p = 0.001*)
StringComparisons.endsWith                6   false   5    564.056 ±    32.321    1147.247 ±   84.530 ns/op  -103.4% (p = 0.000*)
StringComparisons.endsWith               15    true   5   2462.130 ±   235.203    2413.817 ±   18.651 ns/op     2.0% (p = 0.152 )
StringComparisons.endsWith               15   false   5   2073.025 ±    87.980    1990.092 ±   36.326 ns/op     4.0% (p = 0.001*)
StringComparisons.endsWith             1024    true   5 128004.474 ± 10582.659  127376.377 ± 6591.056 ns/op     0.5% (p = 0.678 )
StringComparisons.endsWith             1024   false   5 105830.372 ±  1843.849  106674.660 ± 7257.990 ns/op    -0.8% (p = 0.381 )
StringComparisons.endsWithMismatch        6    true   5   1512.033 ±    76.363    1505.446 ±   37.668 ns/op     0.4% (p = 0.531 )
StringComparisons.endsWithMismatch        6   false   5    555.011 ±    23.099    1112.218 ±   64.643 ns/op  -100.4% (p = 0.000*)
StringComparisons.endsWithMismatch       15    true   5   2449.731 ±   154.661    2386.531 ±   31.439 ns/op     2.6% (p = 0.023 )
StringComparisons.endsWithMismatch       15   false   5   2031.198 ±   109.483    2048.614 ±  100.374 ns/op    -0.9% (p = 0.342 )
StringComparisons.endsWithMismatch     1024    true   5 128096.462 ±  6423.022  127035.168 ± 7104.161 ns/op     0.8% (p = 0.368 )
StringComparisons.endsWithMismatch     1024   false   5 105970.976 ±  1211.821  106290.510 ± 4451.850 ns/op    -0.3% (p = 0.579 )
StringComparisons.regionMatches           6    true   5    941.031 ±    62.551     879.448 ±   39.890 ns/op     6.5% (p = 0.000*)
StringComparisons.regionMatches           6   false   5    502.372 ±    33.192     700.408 ±   39.066 ns/op   -39.4% (p = 0.000*)
StringComparisons.regionMatches          15    true   5   1302.911 ±    67.815    1290.073 ±   73.624 ns/op     1.0% (p = 0.302 )
StringComparisons.regionMatches          15   false   5    954.553 ±    57.958     933.754 ±   57.012 ns/op     2.2% (p = 0.059 )
StringComparisons.regionMatches        1024    true   5  44940.664 ±  7307.489   48292.221 ± 2999.269 ns/op    -7.5% (p = 0.013 )
StringComparisons.regionMatches        1024   false   5  23251.832 ±  2775.125   23457.162 ± 1092.978 ns/op    -0.9% (p = 0.578 )
StringComparisons.regionMatchesCI         6    true   5   2171.587 ±   118.025    2182.973 ±  125.483 ns/op    -0.5% (p = 0.585 )
StringComparisons.regionMatchesCI         6   false   5    659.026 ±    29.518     677.080 ±   34.289 ns/op    -2.7% (p = 0.009*)
StringComparisons.regionMatchesCI        15    true   5   3316.190 ±   126.979    3338.906 ±  179.539 ns/op    -0.7% (p = 0.402 )
StringComparisons.regionMatchesCI        15   false   5    999.622 ±    39.462     985.132 ±   49.939 ns/op     1.4% (p = 0.088 )
StringComparisons.regionMatchesCI      1024    true   5 132560.034 ±  3179.059  133062.069 ± 4542.555 ns/op    -0.4% (p = 0.461 )
StringComparisons.regionMatchesCI      1024   false   5  40867.816 ± 18494.604   37105.479 ± 1591.780 ns/op     9.2% (p = 0.155 )
StringComparisons.regionMatchesRange      6    true   5   1400.137 ±    78.665    1369.264 ±   85.685 ns/op     2.2% (p = 0.052 )
StringComparisons.regionMatchesRange      6   false   5    475.986 ±    23.308    1031.590 ±   55.475 ns/op  -116.7% (p = 0.000*)
StringComparisons.regionMatchesRange     15    true   5   2378.868 ±   108.970    2392.585 ±  144.331 ns/op    -0.6% (p = 0.533 )
StringComparisons.regionMatchesRange     15   false   5   1967.029 ±   103.875    1926.716 ±   25.789 ns/op     2.0% (p = 0.027 )
StringComparisons.regionMatchesRange   1024    true   5 128639.042 ±  4801.156  132522.749 ± 8948.498 ns/op    -3.0% (p = 0.016 )
StringComparisons.regionMatchesRange   1024   false   5 107125.591 ±   877.750  105996.820 ± 4416.158 ns/op     1.1% (p = 0.092 )
StringComparisons.startsWith              6    true   5    837.313 ±    40.708     850.138 ±   47.825 ns/op    -1.5% (p = 0.118 )
StringComparisons.startsWith              6   false   5    438.343 ±    19.971     667.655 ±   34.169 ns/op   -52.3% (p = 0.000*)
StringComparisons.startsWith             15    true   5   1256.429 ±    27.330    1216.876 ±   14.396 ns/op     3.1% (p = 0.000*)
StringComparisons.startsWith             15   false   5    890.834 ±    49.165     889.586 ±   31.341 ns/op     0.1% (p = 0.859 )
StringComparisons.startsWith           1024    true   5  51796.409 ±  5744.873   48263.556 ±  975.353 ns/op     6.8% (p = 0.006*)
StringComparisons.startsWith           1024   false   5  24906.245 ±  3413.337   22785.315 ±  664.385 ns/op     8.5% (p = 0.005*)
StringComparisons.startsWithMismatch      6    true   5    849.399 ±    35.434     837.293 ±   55.320 ns/op     1.4% (p = 0.158 )
StringComparisons.startsWithMismatch      6   false   5    466.091 ±    33.924     661.335 ±   47.606 ns/op   -41.9% (p = 0.000*)
StringComparisons.startsWithMismatch     15    true   5   1257.138 ±    56.729    1257.662 ±   63.112 ns/op    -0.0% (p = 0.959 )
StringComparisons.startsWithMismatch     15   false   5    875.666 ±    37.947     871.318 ±   35.945 ns/op     0.5% (p = 0.494 )
StringComparisons.startsWithMismatch   1024    true   5  46011.740 ±  2145.188   46009.297 ± 3811.407 ns/op     0.0% (p = 0.996 )
StringComparisons.startsWithMismatch   1024   false   5  23411.179 ±  2723.430   23155.355 ± 1026.738 ns/op     1.1% (p = 0.483 )
```

**Comment by pavelrappo** [comment]
I hope that this will reverse performance degradation that I've seen in `equals` and `compareTo` for small-magnitude BigInteger in (not-yet-integrated) https://github.com/openjdk/jdk/pull/14630.

**Comment by cl4es** [comment]
This idea didn't pan out as well as I'd hoped. For example there's a regression on size = 1 arrays. I'll close this and draft a new PR with less intrusive, performance neutral changes.

**Pull request closed without merging**
