### PR TITLE
8312023: Parallel pretouch should shortcut when only 1 thread is needed

### PR DESCRIPTION
**Pull request by shipilev**
This is a follow-up for code introduced in JDK 16 by [JDK-8252221](https://bugs.openjdk.org/browse/JDK-8252221). 

Unfortunately, we do pre-touch not only at startup, but also during the application lifetime when space boundary moves, see [JDK-8312021](https://bugs.openjdk.org/browse/JDK-8312021). From that code, we start the pre-touch threads unconditionally, even when we only need one thread anyway. This is clearly visible with `-Xlog:gc+heap=debug`. The actual pretouch takes single-digit microseconds, but the round-trip through the worker pool incurs latency of about 100us (2x 50us) in my setups. This is significant for very short GC pauses.

Additional testing:
 - [x] Ad-hoc benchmarks
 - [x] Linux x86_64 server fastdebug, `tier{1,2,3}` with `-XX:+UseParallelGC -XX:+AlwaysPreTouch`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312023](https://bugs.openjdk.org/browse/JDK-8312023): Parallel pretouch should shortcut when only 1 thread is needed (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16882/head:pull/16882` \
`$ git checkout pull/16882`

Update a local copy of the PR: \
`$ git checkout pull/16882` \
`$ git pull https://git.openjdk.org/jdk.git pull/16882/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16882`

View PR using the GUI difftool: \
`$ git pr show -t 16882`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16882.diff">https://git.openjdk.org/jdk/pull/16882.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16882#issuecomment-1831859264)

### CODE REVIEW

**Comment by shipilev** [comment]
> There may have been some concern that some task might care about the kind of thread it runs on?

Exactly, in generic case you don't know if caller thread is set up to do the task in the way the worker threads are. This pretouching code is one of the cases where we know running in caller is fine. Existing code even does it when no worker pool is available.
 
> So I'm not convinced this change should be made.

I believe we want to do it. Round-tripping to worker pool is asking for a latency hiccup. Even if things go well, we lose double-digit microseconds on this path. This is a common optimization we do. Last time [we did it in safepoints](https://bugs.openjdk.org/browse/JDK-8306738) with [great results](https://github.com/openjdk/jdk/pull/13616#issuecomment-1538206572).

**Comment by kimbarrett** [comment]
> > There may have been some concern that some task might care about the kind of thread it runs on?
> 
> Exactly, in generic case you don't know if caller thread is set up to do the task in the way the worker threads are. This pretouching code is one of the cases where we know running in caller is fine. Existing code even does it when no worker pool is available.

That's easily dealt with.  Provide a configuration mechanism (a boolean argument for run_task or a variant of
run_task with a different name) that controls whether running on the current thread is permitted and defaults
to no.  Then let clients opt in to that feature.  In my opinion that's a lot better than having each client that can
run on the current thread provide an ad hoc implementation for doing so.

**Comment by tschatzl** [comment]
> > > There may have been some concern that some task might care about the kind of thread it runs on?
> > 
> > 
> > Exactly, in generic case you don't know if caller thread is set up to do the task in the way the worker threads are. This pretouching code is one of the cases where we know running in caller is fine. Existing code even does it when no worker pool is available.
> 
> That's easily dealt with. Provide a configuration mechanism (a boolean argument for run_task or a variant of run_task with a different name) that controls whether running on the current thread is permitted and defaults to no. Then let clients opt in to that feature. In my opinion that's a lot better than having each client that can run on the current thread provide an ad hoc implementation for doing so.

I concur with @kimbarrett: although being guilty of accepting such changes, there has been an effort in the past to *remove* the per-caller `task.work(0)` for the reason that it just adds lots of code duplication, with the goal of eventually providing a way to have any client interested opt in without code duplication. Please add a way to have clients opt in for any task as Kim suggests.

**Review by Hamlin-Li — APPROVED** [review]

**Comment by shipilev** [comment]
> I concur with @kimbarrett: although being guilty of accepting such changes, there has been an effort in the past to _remove_ the per-caller `task.work(0)` for the reason that it just adds lots of code duplication, with the goal of eventually providing a way to have any client interested opt in without code duplication. Please add a way to have clients opt in for any task as Kim suggests.

All right, that would be [JDK-8321242](https://bugs.openjdk.org/browse/JDK-8321242) and #16945. I'll leave this PR to actually flip the switch for pretouch tasks.

**Pull request closed without merging**
