### PR TITLE
JDK-8292498: java/lang/invoke/lambda/LogGeneratedClassesTest.java failed with "AssertionError: only show error once expected [1] but found [0]"

### PR DESCRIPTION
**Pull request by jddarcy**
The use of lambda's in the initialization of AccessFlag runs afoul of CDS in some cases due to occurring early in the platform's initialization. Instead of lambdas, using anonymous classes gets around the issue.

Clean tier1 and tier 2 Mach 5 run with these changes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292498](https://bugs.openjdk.org/browse/JDK-8292498): java/lang/invoke/lambda/LogGeneratedClassesTest.java failed with "AssertionError: only show error once expected [1] but found [0]"

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**) ⚠️ Review applies to [66e90435](https://git.openjdk.org/jdk/pull/9911/files/66e904351df1eacea16f2c9a62c928625ae1c565)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9911/head:pull/9911` \
`$ git checkout pull/9911`

Update a local copy of the PR: \
`$ git checkout pull/9911` \
`$ git pull https://git.openjdk.org/jdk pull/9911/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9911`

View PR using the GUI difftool: \
`$ git pr show -t 9911`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9911.diff">https://git.openjdk.org/jdk/pull/9911.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
Its a shame. Code changes look good. I recommend adding an internal comment within the top of the class declaration indicating why anon inner classes are used, esp. since this there is more action at a distance than the usual case where lambdas are used too early in the JDK initialization process.

**Comment by RogerRiggs** [comment]
This is very unfortunate, the reason to use Lambdas was to avoid creating all the subclasses that would be generated by subclassing the location() method.  At least in this form, the subclasses are not initialized until they are used.

**Comment by jddarcy** [comment]
> Its a shame. Code changes look good. I recommend adding an internal comment within the top of the class declaration indicating why anon inner classes are used, esp. since this there is more action at a distance than the usual case where lambdas are used too early in the JDK initialization process.

Agree that adding an explanatory comment is a good practice; I thought the same myself shortly after creating the PR :-)

**Review by mlchung — APPROVED** [review]
Indeed this is unfortunate.   The change looks good.

**Review by jaikiran — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Comment by dfuch** [comment]
Stupid question: it seems none of these lambdas/anonymous classes capture any parameters, all are stateless, and several seems to be identical.  Would it make the code cleaner to use static inner classes?

**Comment by RogerRiggs** [comment]
> Stupid question: it seems none of these lambdas/anonymous classes capture any parameters, all are stateless, and several seems to be identical. Would it make the code cleaner to use static inner classes?

Keeping the source for the function/body close to or nested in the declaration of each enum is very desirable.

**Comment by jddarcy** [comment]
> > Stupid question: it seems none of these lambdas/anonymous classes capture any parameters, all are stateless, and several seems to be identical. Would it make the code cleaner to use static inner classes?
> 
> Keeping the source for the function/body close to or nested in the declaration of each enum is very desirable.

Yes, the enum's method was coded in approximately this way to help with maintenance and readability. If this proves to be troublesome over time, there are harder-to-read/understand refactorings that could be used instead.

**Pull request closed without merging**
