### PR TITLE
8208565: [TEST_BUG] javax\swing\PopupFactory\6276087\NonOpaquePopupMenuTest.java throws NPE

### PR DESCRIPTION
**Pull request by prsadhuk**
Test was failing in the past owing to NPE while accessing JMenu probably owing to fact the test did not wait for UI to be visible before starting the test, so added a delay after the frame is made visible. Also, added disposal of frame.
Also, it seems JDK-8213535 fix might be having a positive impact on this test.

Several iterations of this test in all platforms have passed (link in JBS).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8208565](https://bugs.openjdk.java.net/browse/JDK-8208565): [TEST_BUG] javax\swing\PopupFactory\6276087\NonOpaquePopupMenuTest.java throws NPE
 * [JDK-8065099](https://bugs.openjdk.java.net/browse/JDK-8065099): [macos] javax/swing/PopupFactory/6276087/NonOpaquePopupMenuTest.java fails: no background shine through

### Reviewers
 * [Jayathirth D V](https://openjdk.java.net/census#jdv) (@jayathirthrao - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8282/head:pull/8282` \
`$ git checkout pull/8282`

Update a local copy of the PR: \
`$ git checkout pull/8282` \
`$ git pull https://git.openjdk.java.net/jdk pull/8282/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8282`

View PR using the GUI difftool: \
`$ git pr show -t 8282`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8282.diff">https://git.openjdk.java.net/jdk/pull/8282.diff</a>

</details>

### CODE REVIEW

**Comment by prsadhuk** [comment]
Any reviewers for this test fix?

**Comment by prsadhuk** [comment]
Any reviewers?

**Comment by jayathirthrao** [comment]
We should link JDK-8065099 also in this PR. As we are de-problemlisting that bug also.

**Review by jayathirthrao — APPROVED** [review]

**Pull request closed without merging**
