### PR TITLE
8319925: CSS.BackgroundImage incorrectly uses double-checked locking

### PR DESCRIPTION
**Pull request by prsadhuk**
CSS.BackgroundImage.getImage uses double-checked locking but the loadedImage field isn't declared as volatile. Without the volatile modifier, double-checked locking implementation is broken.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319925](https://bugs.openjdk.org/browse/JDK-8319925): CSS.BackgroundImage incorrectly uses double-checked locking (**Bug** - P4)

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16917/head:pull/16917` \
`$ git checkout pull/16917`

Update a local copy of the PR: \
`$ git checkout pull/16917` \
`$ git pull https://git.openjdk.org/jdk.git pull/16917/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16917`

View PR using the GUI difftool: \
`$ git pr show -t 16917`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16917.diff">https://git.openjdk.org/jdk/pull/16917.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16917#issuecomment-1835548544)

### CODE REVIEW

**Review by aivanov-jdk — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
> > That code does not look like double-checked lock, it is something different. It checks/init/sets one field and then returns another one. Even if both will be marked as volatile the method may return null, since the loadedImage is set to true before init of image.
> 
> I think the field `loadedImage` still needs to be volatile as it is accessed multiple time even though it can be argued to be non-DCL in classical way

Yep.

It is a DCL, essentially, but it uses a different field to protect access to another field whereas the classic DCL uses the same field that it protects.

> Even if both will be marked as volatile the method may return null, since the loadedImage is set to true before init of image.

This is correct. *Good catch!* I missed it.

*For correctness*, the assignment

https://github.com/openjdk/jdk/blob/96d69bcf8cbf1ab20b1577196120c60e072bbe78/src/java.desktop/share/classes/javax/swing/text/html/CSS.java#L2955

has to be moved below the if-statement:

```java
                    if (!loadedImage) {
                        URL url = CSS.getURL(base, svalue);
                        if (url != null) {
                            image = new ImageIcon();
                            Image tmpImg = Toolkit.getDefaultToolkit().createImage(url);
                            if (tmpImg != null) {
                                image.setImage(tmpImg);
                            }
                        }
                        loadedImage = true;
                    }
```
Otherwise, the returned `image` may still be in an inconsistent state. This way, `loadedImage` is assigned `true` after `image` is initialised; that way if another thread reads `loadedImage` and its value is `true`, it can safely access `image`.

**Review by aivanov-jdk — CHANGES_REQUESTED** [review]
Based on my recent comment, the code needs updating.

Thanks @mrserb for catching another mistake.

**Comment by mrserb** [comment]
It is probably easy just drop the usage of loadedImage and use the image instead?

**Comment by aivanov-jdk** [comment]
> It is probably easy just drop the usage of loadedImage and use the image instead?

Ideally. Yet there's a corner case: if `url` is null, there's nothing to load; and it doesn't make sense to re-try, the URL won't change. If it were not for this case, the `image` field alone would do the job.

**Comment by mrserb** [comment]
> > It is probably easy just drop the usage of loadedImage and use the image instead?
> 
> Ideally. Yet there's a corner case: if `url` is null, there's nothing to load; and it doesn't make sense to re-try, the URL won't change. If it were not for this case, the `image` field alone would do the job.

Not sure how it is expected to work, the url is a parameter and can be changed on the fly(see the usage of base in the StyleSheet.java)

**Comment by prsadhuk** [comment]
> > > It is probably easy just drop the usage of loadedImage and use the image instead?
> > 
> > 
> > Ideally. Yet there's a corner case: if `url` is null, there's nothing to load; and it doesn't make sense to re-try, the URL won't change. If it were not for this case, the `image` field alone would do the job.
> 
> Not sure how it is expected to work, the url is a parameter and can be changed on the fly(see the usage of base in the StyleSheet.java)

Yes, seems like setBase can be used to change image URL on the fly...Modified to use image field for DCL...

**Comment by aivanov-jdk** [comment]
> > > > It is probably easy just drop the usage of loadedImage and use the image instead?
> > > 
> > > 
> > > Ideally. Yet there's a corner case: if `url` is null, there's nothing to load; and it doesn't make sense to re-try, the URL won't change. If it were not for this case, the `image` field alone would do the job.
> > 
> > 
> > Not sure how it is expected to work, the url is a parameter and can be changed on the fly(see the usage of base in the StyleSheet.java)
> 
> Yes, seems like setBase can be used to change image URL on the fly...Modified to use image field for DCL...

I am against this latest change: it doesn't fix much but it would cause creating the URL each time `getImage` is called if the URL is invalid for whatever reason.

Usually, `setBase` isn't changed on the fly, it's set once when the `StyleSheet` and/or `HTMLDocument` is created. If `StyleSheet.setBase` is called to modify the base, the image needs reloading *whether it's already loaded or not* — the latest change doesn't address this problem in any way: if the image is successfully loaded, it's what's returned even though the base has been changed; and only if the image couldn't be loaded with the old base, the image will be re-loaded again.

This is asymmetric: in one case, it's re-loaded, in another — it isn't.

I'm for keeping the current behaviour: if the URL is invalid, the image isn't loaded and will never be for this instance of` CSS.BackgroundImage`; if the URL is valid, the image gets loaded.

**Comment by prsadhuk** [comment]
> if the URL is invalid, the image isn't loaded
```
if (!loadedImage) {
                        URL url = CSS.getURL(base, svalue);
                        if (url != null) {
                            image = new ImageIcon();
                            Image tmpImg = Toolkit.getDefaultToolkit().createImage(url);
                            if (tmpImg != null) {
                                image.setImage(tmpImg);
                            }
                        }
                        loadedImage = true;
                    }
```
As per your change, if URL is invalid ie url = null, image is not loaded but `loadedImage` is set to true so it will not give another chance to load the URL again via `CSS.getURL` just in case user decides to call setBase with a valid URL

**Comment by aivanov-jdk** [comment]
> > if the URL is invalid, the image isn't loaded
> 
> As per your change, if URL is invalid ie url = null, image is not loaded but `loadedImage` is set to true so it will not give another chance to load the URL again via `CSS.getURL` just in case user decides to call setBase with a valid URL (after finding `getImage `returning null)

Exactly! The image is **never** given a chance to load for a second time.

It is how the code has always worked.

With your proposed change, the image has a chance to re-load if and only if `url == null`. And it tries re-loading over and over again until `url` becomes non-`null`. At the same time, the change to `base` is ignored if the `url` wasn't `null`… even though the image itself may not have been loaded successfully.

I do not think this is correct or desirable.

**Comment by prsadhuk** [comment]
> > > if the URL is invalid, the image isn't loaded
> > 
> > 
> > As per your change, if URL is invalid ie url = null, image is not loaded but `loadedImage` is set to true so it will not give another chance to load the URL again via `CSS.getURL` just in case user decides to call setBase with a valid URL (after finding `getImage `returning null)
> 
> Exactly! The image is **never** given a chance to load for a second time.
> 
> It is how the code has always worked.
>
But it can be a bug in the code that it never gave a chance second time..I think it should get a chance to reload the URL again in case it is invalid the 1st time so I guess the change should be the one where if url is invalid, `loadedImage ` should not be set and it will need a relook at the url (to be set by user)

                  ```
if (!loadedImage) {
                        URL url = CSS.getURL(base, svalue);
                        if (url != null) {
                            image = new ImageIcon();
                            Image tmpImg = Toolkit.getDefaultToolkit().createImage(url);
                            if (tmpImg != null) {
                                image.setImage(tmpImg);
                            }
                            loadedImage = true;
                        }
                    }
```

**Comment by aivanov-jdk** [comment]
> But it can be a bug in the code that it never gave a chance second time..I think it should get a chance to reload the URL again in case it is invalid the 1st time so I guess the change should be the one where if url is invalid, `loadedImage ` should not be set and it will need a relook at the url (to be set by user)

My point is it must re-load the image **whenever base is changed**, as @mrserb pointed out.

If you want to implement this feature, submit a new bug — it is out of scope for this issue. Better yet, just submit the new bug to document the discovered problem.

Re-loading the image if and only if the `url` is `null` is inconsistent. I strongly believe the image is to be re-loaded either *always* or *never* at all rather than sometimes.

Currently, it's in *never* mode. I am for preserving the current behaviour rather than adding a half-baked solution.

**Comment by prsadhuk** [comment]
> > But it can be a bug in the code that it never gave a chance second time..I think it should get a chance to reload the URL again in case it is invalid the 1st time so I guess the change should be the one where if url is invalid, `loadedImage ` should not be set and it will need a relook at the url (to be set by user)
> 
> My point is it must re-load the image **whenever base is changed**, as @mrserb pointed out.
> 
> If you want to implement this feature, submit a new bug — it is out of scope for this issue. Better yet, just submit the new bug to document the discovered problem.
> 
> Re-loading the image if and only if the `url` is `null` is inconsistent. I strongly believe the image is to be re-loaded either _always_ or _never_ at all rather than sometimes.
> 
> Currently, it's in _never_ mode. I am for preserving the current behaviour rather than adding a half-baked solution.

OK. I have had my doubts but I agree to keep it as similar to code we have it now..Modified the PR..

**Pull request closed without merging**
