### PR TITLE
8287206: Use WrongThreadException for confinement errors

### PR DESCRIPTION
**Pull request by mcimadamore**
This patch tweaks the foreign API to use the newly added `WrongThreadException` instead of `IllegalStateException` to report confinement errors.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8287206](https://bugs.openjdk.java.net/browse/JDK-8287206): Use WrongThreadException for confinement errors
 * [JDK-8287207](https://bugs.openjdk.java.net/browse/JDK-8287207): Use WrongThreadException for confinement errors (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8865/head:pull/8865` \
`$ git checkout pull/8865`

Update a local copy of the PR: \
`$ git checkout pull/8865` \
`$ git pull https://git.openjdk.java.net/jdk pull/8865/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8865`

View PR using the GUI difftool: \
`$ git pr show -t 8865`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8865.diff">https://git.openjdk.java.net/jdk/pull/8865.diff</a>

</details>

### CODE REVIEW

**Comment by mcimadamore** [comment]
javadoc:

http://cr.openjdk.java.net/~mcimadamore/8287206/v1/javadoc/java.base/module-summary.html

specdiff:

http://cr.openjdk.java.net/~mcimadamore/8287206/v1/specdiff_out/overview-summary.html

**Review by mlchung — APPROVED** [review]

**Comment by uschindler** [comment]
I have seen this PR now: Would it be also a good idea to replace the `IllegalStateException` by some special exception. In Lucene we catch `IllegalStateException` in out IO layer, check if message contains "closed", example:
- https://github.com/apache/lucene/blob/d182134bf88a44bf76ebd1c1d40b225ecdca1f4b/lucene/core/src/java/org/apache/lucene/store/MemorySegmentIndexInput.java#L137 (catch)
- https://github.com/apache/lucene/blob/d182134bf88a44bf76ebd1c1d40b225ecdca1f4b/lucene/core/src/java/org/apache/lucene/store/MemorySegmentIndexInput.java#L93-L103 (that's the hack)

The check using `ex.getMessage().contains("closed")` feels bad...

**Comment by uschindler** [comment]
Thinking more about it: `IllegalStateException` is fine for a closed `MemorySession`. If used by wrong thread the exception was indeed confusing. Now that the abiguity is gone, I can change our (Lucene) code and just transform every ISE to an already closed in our code. I just wanted to bring up that issue here.

PR is here: https://github.com/apache/lucene/pull/912

**Comment by mcimadamore** [comment]
> Thinking more about it: `IllegalStateException` is fine for a closed `MemorySession`. If used by wrong thread the exception was indeed confusing. Now that the abiguity is gone, I can change our (Lucene) code and just transform every ISE to an already closed in our code. I just wanted to bring up that issue here.
> 
> PR is here: [apache/lucene#912](https://github.com/apache/lucene/pull/912)

I've been thinking something similar. I'd suggest to keep the API as is, and maybe revise it at a later point if lack of a specific exception for the "already closed" case proves to be too cumbersome to workaround.

**Comment by uschindler** [comment]
I changed the PR on our side, `IllegalStateException` is fine, if you catch it as close as possible to the code calling varhandles and so on (which is the case for Lucene). Thanks for this PR, makes life much easier!

**Pull request closed without merging**
