### PR TITLE
JDK-8312466: /bin/nm usage in AIX makes needs -X64 flag

### PR DESCRIPTION
**Pull request by ansteiner**
On AIX the 'nm' needs -X64 option.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312466](https://bugs.openjdk.org/browse/JDK-8312466): /bin/nm  usage in AIX makes needs -X64 flag (**Bug** - P4)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15036/head:pull/15036` \
`$ git checkout pull/15036`

Update a local copy of the PR: \
`$ git checkout pull/15036` \
`$ git pull https://git.openjdk.org/jdk.git pull/15036/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15036`

View PR using the GUI difftool: \
`$ git pr show -t 15036`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15036.diff">https://git.openjdk.org/jdk/pull/15036.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15036#issuecomment-1651177650)

### CODE REVIEW

**Comment by MBaesken** [comment]
Hi Andreas, thanks for addressing this.
Should it be 'needs' instead of 'need' in the comment you added ?

Btw did you look at the naming of the mangled symbols we check for (SetupOperatorNewDeleteCheck)  , are those names really the same on AIX ?

**Comment by TheShermanTanker** [comment]
I am fairly certain there is a better spot for this, but I cannot remember where at the moment. Is this for JvmMapfile.gmk where we dump the symbols of object files, or for something else?

**Comment by MBaesken** [comment]
> I am fairly certain there is a better spot for this, but I cannot remember where at the moment. Is this for JvmMapfile.gmk where we dump the symbols of object files, or for something else?


It is needed for the SetupOperatorNewDeleteCheck  (check for unwanted global new/delete operators in HS objects).

**Comment by TheShermanTanker** [comment]
Right, thanks for jolting my memory

**Comment by ansteiner** [comment]
> Hi Andreas, thanks for addressing this. Should it be 'needs' instead of 'need' in the comment you added ?
> 
> Btw did you look at the naming of the mangled symbols we check for (SetupOperatorNewDeleteCheck) , are those names really the same on AIX ?
Yes, the naming is the same.

**Review by MBaesken — APPROVED** [review]

**Review by tstuefe — APPROVED** [review]
+1

**Review by dholmes-ora — COMMENTED** [review]
I don't think this is the right place to make this change. Shouldn't it be handled at configure time in ./autoconf/toolchain.m4 ? There is also a BUILD_NM variable that will not be fixed by the proposed change.

**Comment by RealCLanger** [comment]
I agree, this should be handled in toochain.m4

**Comment by MBaesken** [comment]
> I don't think this is the right place to make this change. Shouldn't it be handled at configure time in ./autoconf/toolchain.m4 ? There is also a BUILD_NM variable that will not be fixed by the proposed change.

Currently  all needed flags for calling NM are set directly in the makefile, see

common/NativeCompilation.gmk:51:    $(NM) $$($1_TARGET) | $(GREP)  " T " | \
common/NativeCompilation.gmk:56:    $(NM) -m $$($1_TARGET) | $(GREP)  "__TEXT" | \
hotspot/lib/CompileJvm.gmk:287:	      $$(NM) $$<  2>&1 | $$(GREP) $$(addprefix -e , $$(MANGLED_SYMS)) | $$(GREP) $$(UNDEF_PATTERN) > $1.op_check || true)
hotspot/lib/CompileJvm.gmk:290:	    $$(NM) $$< | $$(CXXFILT) | $$(EGREP) '$$(DEMANGLED_REGEXP)' | $$(GREP) $$(UNDEF_PATTERN); \
hotspot/lib/JvmMapfile.gmk:56:  DUMP_SYMBOLS_CMD := $(NM) --defined-only *$(OBJ_SUFFIX)
hotspot/lib/JvmMapfile.gmk:70:  DUMP_SYMBOLS_CMD := $(NM) -Uj *$(OBJ_SUFFIX) 2> /dev/null
hotspot/lib/JvmMapfile.gmk:92:  DUMP_SYMBOLS_CMD := $(NM) -X64 -B -C *$(OBJ_SUFFIX)

so Andreas was just following the current practise. Regarding BUILD_NM , I cannot find usage of it in the makefiles, so probably nothing to fix at the moment.

**Comment by TheShermanTanker** [comment]
Rather than toolchain.m4, this might actually be better suited for flags-other.m4, if there isn't already a flag for nm set there. This might be only in one location, but it might help future ports to have an nm flag that can be conveniently set, much like strip and rc already have their flags set there. That's my humble opinion, at least

**Comment by RealCLanger** [comment]
No, I don't think flags-other.m4 is suited. If at all, it should be handled in toolchain.m4 if we understand the -X64 flag on AIX as unconditional for every nm call. Then we could also remove -X64 in JvmMapFile.gmk.

Also, maybe we should check if we can remove BUILD_NM and/or unify BUILD_NM and NM - as I see it now, BUILD_NM is not used anywhere. But I don't know all the history and maybe I'm overseeing something.

OTOH, this cleanup could be done in another PR. For now, the code as it is would be ok, too.

**Comment by MBaesken** [comment]
> OTOH, this cleanup could be done in another PR. For now, the code as it is would be ok, too.

I agree, let's do the flags / macro adjustment in another issue. Andreas, I can open one for you if you want.

**Comment by ansteiner** [comment]
> > OTOH, this cleanup could be done in another PR. For now, the code as it is would be ok, too.
> 
> I agree, let's do the flags / macro adjustment in another issue. Andreas, I can open one for you if you want.

I would prefer to integrate this as is. To get the check working on AIX at all and do the BUILD_NM/NM cleanup in another PR.
@MBaesken: Feel free to open another issue for this cleanup.

**Comment by MBaesken** [comment]
There might be room for improvement for the general handling of NM flags, I opened
https://bugs.openjdk.org/browse/JDK-8313244
8313244: NM flags handling in configure process

**Review by TheShermanTanker — APPROVED** [review]

**Pull request closed without merging**
