### PR TITLE
8283612: IGV: Remove Graal module

### PR DESCRIPTION
**Pull request by jyukutyo**
This pull request removes Graal module in Ideal Graph Visualizer. I think you might know that Graal JIT compiler was removed from OpenJDK in version 17. So IGV doesn't need to support Graal's dump files any more. It is noted that GraalVM has its own version of IGV (https://www.graalvm.org/22.1/tools/igv/).

It seems that there are no test cases related to Graal module. I've built IGV, run it and opened the graphs. Those were all successful.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283612](https://bugs.openjdk.org/browse/JDK-8283612): IGV: remove Graal module

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.java.net/census#rcastanedalo) (@robcasloz - Committer)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9119/head:pull/9119` \
`$ git checkout pull/9119`

Update a local copy of the PR: \
`$ git checkout pull/9119` \
`$ git pull https://git.openjdk.org/jdk pull/9119/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9119`

View PR using the GUI difftool: \
`$ git pr show -t 9119`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9119.diff">https://git.openjdk.org/jdk/pull/9119.diff</a>

</details>

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good! Thank you for this and your previous contributions to IGV, Koichi.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by jyukutyo** [comment]
Thank you for the reviews, Roberto and Christian!

**Pull request closed without merging**
