### PR TITLE
8280474: Garbage value passed to getLocaleInfoWrapper in HostLocaleProviderAdapter_md

### PR DESCRIPTION
**Pull request by djelinski**
Reported by clang-tidy. Verified manually by running
```
        Calendar c = Calendar.getInstance();
        System.out.println (c.getDisplayNames(Calendar.MONTH, Calendar.SHORT_STANDALONE, Locale.getDefault()));
```
with `-Djava.locale.providers=HOST`

Without the fix the WINAPI functions fail, and [this block](https://github.com/openjdk/jdk/blame/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/windows/native/libjava/HostLocaleProviderAdapter_md.c#L857) is never entered. With the fix this block is entered and sensible values are stored in the returned array.

No test because the observable effect with and without the fix was the same; apparently there's a fallback to another provider that works.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280474](https://bugs.openjdk.java.net/browse/JDK-8280474): Garbage value passed to getLocaleInfoWrapper in HostLocaleProviderAdapter_md

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7184/head:pull/7184` \
`$ git checkout pull/7184`

Update a local copy of the PR: \
`$ git checkout pull/7184` \
`$ git pull https://git.openjdk.java.net/jdk pull/7184/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7184`

View PR using the GUI difftool: \
`$ git pr show -t 7184`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7184.diff">https://git.openjdk.java.net/jdk/pull/7184.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
Looks good. The difference would be observable for locales that have different month names for standalone/format, such as Polish 😀
I'd add `noreg-hard` label to the JBS issue, as it would require Windows to be set to those locales.

**Review by AlanBateman — APPROVED** [review]
Good find.

**Pull request closed without merging**
