### PR TITLE
8344994: Remove most uses of RuntimePermission checks in java.desktop

### PR DESCRIPTION
**Pull request by prrace**
More clean up after JEP 486 (SecurityManager disabling).
FilePermission is the most common RuntimePermission checked in java.desktop

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344994](https://bugs.openjdk.org/browse/JDK-8344994): Remove most uses of RuntimePermission checks in java.desktop (**Bug** - P4)

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22373/head:pull/22373` \
`$ git checkout pull/22373`

Update a local copy of the PR: \
`$ git checkout pull/22373` \
`$ git pull https://git.openjdk.org/jdk.git pull/22373/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22373`

View PR using the GUI difftool: \
`$ git pr show -t 22373`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22373.diff">https://git.openjdk.org/jdk/pull/22373.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22373#issuecomment-2499121697)
</details>

### CODE REVIEW

**Review by azvegint — APPROVED** [review]
One test still uses runtime permission:

```
./test/jdk/java/awt/print/PrinterJob/PrintToDir.java:129:                security.checkPermission(new FilePermission("<<ALL FILES>>", "read,write"));
./test/jdk/java/awt/print/PrinterJob/PrintToDir.java:130:                security.checkPermission(new PropertyPermission("user.dir", "read"));
```

**Comment by azvegint** [comment]
This is outside the scope of this PR, but I took a look at what else can be done regarding SecurityManager removal in files affected by this PR:

----
`src/java.desktop/share/classes/java/awt/Font#hasTempPermission` already has an issue [JDK-8344146
](https://bugs.openjdk.org/browse/JDK-8344146)

---

I couldn't find JBS issues for the following two:

---
`src/java.desktop/macosx/classes/com/apple/eawt/Application.java` methods:

- setFileTypeAndCreator
- setFileType
- setFileCreato
- getFileType
- getFileCreator
- moveToTrash
- revealInFinder

---
`src/java.desktop/share/classes/sun/print/PrintJob2D.java#initPrintJob2D`

**Comment by prrace** [comment]
> This is outside the scope of this PR, but I took a look at what else can be done regarding SecurityManager removal in files affected by this PR:
> 
> `src/java.desktop/share/classes/java/awt/Font#hasTempPermission` already has an issue [JDK-8344146 ](https://bugs.openjdk.org/browse/JDK-8344146)
> 
> I couldn't find JBS issues for the following two:
> 
> `src/java.desktop/macosx/classes/com/apple/eawt/Application.java` methods:
> 
> * setFileTypeAndCreator
> * setFileType
> * setFileCreato
> * getFileType
> * getFileCreator
> * moveToTrash
> * revealInFinder
> 
> `src/java.desktop/share/classes/sun/print/PrintJob2D.java#initPrintJob2D`

I know that there's some things some in some of the files here but I was trying to deal with cases for this, not files, although I was very tempted ..

However the point is, not forgotten, not overlooked, and next on the list.

**Comment by prrace** [comment]
> One test still uses runtime permission:
> 
> ```
> ./test/jdk/java/awt/print/PrinterJob/PrintToDir.java:129:                security.checkPermission(new FilePermission("<<ALL FILES>>", "read,write"));
> ./test/jdk/java/awt/print/PrinterJob/PrintToDir.java:130:                security.checkPermission(new PropertyPermission("user.dir", "read"));
> ```

Keep grepping. I'll also do a grep over the various client test directories soon.

**Pull request closed without merging**
