### PR TITLE
8252996: Thread safety problem in java.net.ProxySelector

### PR DESCRIPTION
**Pull request by dmlloyd**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252996](https://bugs.openjdk.java.net/browse/JDK-8252996): Thread safety problem in java.net.ProxySelector

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/184/head:pull/184`
`$ git checkout pull/184`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Seems like an oversight when proxy selector was added

**Comment by dfuch** [comment]
Hi David, 

I can sponsor this for you - unless you already have a sponsor?

best regards,
-- daniel

**Comment by dmlloyd** [comment]
No, I do not (though @ChrisHegarty did take a peek at my original ML post).

**Comment by dfuch** [comment]
/sponsor

Done.

**Pull request closed without merging**
