### PR TITLE
8277239: SIGSEGV in vrshift_reg_maskedNode::emit

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Currently instruction selector differentiates between the two kinds of vector shift operations i.e. one with vector shift count and other with scalar shift count passed though LShiftCntV/RShiftCntV nodes by looking at the ideal opcode of shift count node.

A more robust scheme is to set a flag over vector shift node if it has variable vector shift count and replace the opcode based check with flag based check in various shift instruction selection patterns.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277239](https://bugs.openjdk.java.net/browse/JDK-8277239): SIGSEGV in vrshift_reg_maskedNode::emit

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to 97dce5caec35e10cac064d7458edf1321d2b92c3
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6431/head:pull/6431` \
`$ git checkout pull/6431`

Update a local copy of the PR: \
`$ git checkout pull/6431` \
`$ git pull https://git.openjdk.java.net/jdk pull/6431/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6431`

View PR using the GUI difftool: \
`$ git pr show -t 6431`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6431.diff">https://git.openjdk.java.net/jdk/pull/6431.diff</a>

</details>

### CODE REVIEW

**Comment by PaulSandoz** [comment]
Running tests to verify.

**Review by sviswa7 — APPROVED** [review]
The patch looks good to me.

**Comment by PaulSandoz** [comment]
Tests passed. Needs another HotSpot reviewer.

**Review by dean-long — CHANGES_REQUESTED** [review]

**Review by dean-long — APPROVED** [review]

**Comment by jatin-bhateja** [comment]
Thanks @sviswa7  and @dean-long

**Pull request closed without merging**
