### PR TITLE
8332099: since-checker - Add @ since to package-info in jdk.jsobject

### PR DESCRIPTION
**Pull request by nizarbenalla**
Simple code cleanup.
If you're reviewing this, thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332099](https://bugs.openjdk.org/browse/JDK-8332099): since-checker - Add @ since to package-info in jdk.jsobject (**Sub-task** - P4)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19197/head:pull/19197` \
`$ git checkout pull/19197`

Update a local copy of the PR: \
`$ git checkout pull/19197` \
`$ git pull https://git.openjdk.org/jdk.git pull/19197/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19197`

View PR using the GUI difftool: \
`$ git pr show -t 19197`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19197.diff">https://git.openjdk.org/jdk/pull/19197.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19197#issuecomment-2106783828)

### CODE REVIEW

**Comment by nizarbenalla** [comment]
keep alive

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
