### PR TITLE
8338902: CDS flags are reported with wrong flag category

### PR DESCRIPTION
**Pull request by shipilev**
Noticed this little oddity when looking through Leyden crash reports:

```
$ build/macosx-aarch64-server-fastdebug/images/jdk/bin/java -XX:+PrintFlagsFinal 2>&1 | grep ArchiveRelocationMode  
      int ArchiveRelocationMode                    = 1                                {JVMCI diagnostic} {default}
```

This is a flag from `cds_globals.hpp`, but it is reported as `JVMCI`. Depending on build, these flags seem to be attributed to different categories. I think this bug also skews all other flag categories, since we don't account for CDS flags being in the middle of the table here: https://github.com/openjdk/jdk/blob/916f1aa04f6fcc6da9bf9d725e3639cf4c0755a1/src/hotspot/share/runtime/flags/allFlags.hpp#L60-L66 The order in that table is important, since we have this matcher: https://github.com/openjdk/jdk/blob/916f1aa04f6fcc6da9bf9d725e3639cf4c0755a1/src/hotspot/share/runtime/flags/jvmFlag.cpp#L455-L478

My initial patch was to introduce the `CDS` category, but I think that is excessive. We can just move the CDS flags below the specialized flags, so they are reported as "other", i.e. without a category.

After the fix:

```
% build/macosx-aarch64-server-fastdebug/images/jdk/bin/java -XX:+PrintFlagsFinal 2>&1 | grep ArchiveRelocationMode
      int ArchiveRelocationMode                    = 1                                      {diagnostic} {default}
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338902](https://bugs.openjdk.org/browse/JDK-8338902): CDS flags are reported with wrong flag category (**Bug** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20692/head:pull/20692` \
`$ git checkout pull/20692`

Update a local copy of the PR: \
`$ git checkout pull/20692` \
`$ git pull https://git.openjdk.org/jdk.git pull/20692/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20692`

View PR using the GUI difftool: \
`$ git pr show -t 20692`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20692.diff">https://git.openjdk.org/jdk/pull/20692.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20692#issuecomment-2306898370)

### CODE REVIEW

**Comment by shipilev** [comment]
Ping? :) @iklam, maybe?

**Review by iklam — APPROVED** [review]
LGTM. Maybe we should add a comment above ALL_FLAGS saying that it should match the order of the other macro?

**Comment by shipilev** [comment]
> LGTM. Maybe we should add a comment above ALL_FLAGS saying that it should match the order of the other macro?

Thanks. There is already a comment like this, but it apparently does not help :)

https://github.com/openjdk/jdk/blob/9e1af8cc7cc9f63453097bd35eb3cf29f945d765/src/hotspot/share/runtime/flags/allFlags.hpp#L35-L36

**Comment by shipilev** [comment]
Anyone else to review, please? Thanks.

**Review by adinn — APPROVED** [review]
Yes, fix looks good.

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
