### PR TITLE
8262950: Restructure compiler/intrinsics/TestRotate.java for easier compilation

### PR DESCRIPTION
**Pull request by shipilev**
It seems that after [JDK-8256438](https://bugs.openjdk.java.net/browse/JDK-8256438) this test is very slow. See [JDK-8262465 ](https://bugs.openjdk.java.net/browse/JDK-8262465) for more evidence of this.
I believe the underlying cause is that `main()` is way too busy with test cases, so this eventually happens:

```
$ javac test/hotspot/jtreg/compiler/intrinsics/TestRotate.java
$ java -XX:-TieredCompilation -XX:CompileThreshold=1000 -Xbatch -XX:+PrintCompilation -cp test/hotspot/jtreg compiler.intrinsics.TestRotate
 ...
   6112 112 % !b compiler.intrinsics.TestRotate::main @ 1494 (3008 bytes) COMPILE SKIPPED: out of nodes during split (retry at different tier)
```

So, while the test is intended to test rotate intrinsics, I think it never gets there because compilation bails. And this also makes the test slow. This is tier1 test, and so its performance is somewhat important for developer experience.

This improvement restructures the test to be easier to JIT compile. This drops the test run time from ~4 minutes to ~20 seconds on my desktop. Plus, additional diagnostic flag verifies that compiler does not bail anywhere.

Attn @theRealELiu.

Additional testing:
  - [x] Linux x86_64 fastdebug, affected test
  - [x] Linux x86_64 release, affected test
  - [x] Linux aarch64 fastdebug, affected test

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262950](https://bugs.openjdk.java.net/browse/JDK-8262950): Restructure compiler/intrinsics/TestRotate.java for easier compilation

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2811/head:pull/2811`
`$ git checkout pull/2811`

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I completely agree with optimizing these tests. But what you did is not enough.

`ITER = 500,000;` is too much. C2 compilation will be triggered at 10,000. If you want to be completely sure use 50,000 which is more than enough.

Second, `verify()` should be called only after compilation. Why to call it for Interpreter? You can.

Third, `ITER` and `*_VALUES` loops should be inverted - hot loop will be inner.

Fourth, `verify()` error message could be part of `new Error()` message instead of separate print line. It will be ease to see.

Something like this (indents could be wrong):
```
    public static void testRorOrInts() {
         for (int i = 0; i < INT_VALUES.length; i++) {
             int val = INT_VALUES[i];
             verify("testRorOrInt1(" + val + ")",  testRorOrInt1(val),  TEST_ROR_OR_INT_1_EXPECTED[i]);
             verify("testRorOrInt16(" + val + ")", testRorOrInt16(val), TEST_ROR_OR_INT_16_EXPECTED[i]);
             verify("testRorOrInt31(" + val + ")", testRorOrInt31(val), TEST_ROR_OR_INT_31_EXPECTED[i]);
             verify("testRorOrInt32(" + val + ")", testRorOrInt32(val), TEST_ROR_OR_INT_32_EXPECTED[i]);
             for (int count = 0; count < ITERS; count++) {
                  testRorOrInt1(val);
                  testRorOrInt16(val);
                  testRorOrInt31(val);
                  testRorOrInt32(val);
             }
             verify("testRorOrInt1(" + val + ")",  testRorOrInt1(val),  TEST_ROR_OR_INT_1_EXPECTED[i]);
             verify("testRorOrInt16(" + val + ")", testRorOrInt16(val), TEST_ROR_OR_INT_16_EXPECTED[i]);
             verify("testRorOrInt31(" + val + ")", testRorOrInt31(val), TEST_ROR_OR_INT_31_EXPECTED[i]);
             verify("testRorOrInt32(" + val + ")", testRorOrInt32(val), TEST_ROR_OR_INT_32_EXPECTED[i]);
         }
     }
```

**Comment by shipilev** [comment]
By "not enough" you probably mean "while we are at it, we can do even better"? Because current version definitely helps JIT compilation, as evidenced by test times and the absence of compilation aborts.

Off the top of my head:
 - Dropping `ITERS` one order of magnitude down to 50K does not improve test times, AFAICS.
 - Verifying each on each step verifies OSR compilations as well, which must be good.
 - Having a test call not in triplicate (how you suggest) but in singular (how it is in this PR) seems more readable.

I can take a look at these later, but honestly, I think the current patch is an acceptable thing to make `tier1` run fast again.

**Comment by vnkozlov** [comment]
500,000 vs 50,000 ITER with your changes:
```
elapsed time (seconds): 22.664
vs
elapsed time (seconds): 6.683
```

**Comment by shipilev** [comment]
Yup, that only seems to improve when I run the test separately. jtreg adds a lot of constant overhead, which masks this improvement:

```
# 500K
$ time CONF=linux-x86_64-server-fastdebug make run-test TEST=compiler/intrinsics/TestRotate.java
...
real	0m24.330s
user	0m51.197s
sys	0m3.607s

# 50K
$ time CONF=linux-x86_64-server-fastdebug make run-test TEST=compiler/intrinsics/TestRotate.java
...
real	0m19.109s
user	0m45.391s
sys	0m3.787s
```

No matter, new patch dropped `ITERS` to `50K`.

**Review by vnkozlov — APPROVED** [review]
Okay.

**Comment by theRealELiu** [comment]
Thanks for the discussion, this makes more sense to me now.

**Comment by theRealELiu** [comment]
> So, while the test is intended to test rotate intrinsics, I think it never gets there because compilation bails.

Agree. The rotate was intended to be implemented by intrinsics but finally by those dedicated nodes instead[1][2].

I was wondering if it's time to move this case out of 'intrinsics' package. Perhaps 'compiler.c2' is a more proper place .

[1] http://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-July/038963.html
[2] https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-July/039048.html

**Comment by shipilev** [comment]
I think the test is fine at its current place, in case we ever consider C1 intrinsics. I am integrating this fix to make `tier1` sane again.

/integrate

**Pull request closed without merging**
