### PR TITLE
8322989: New test serviceability/HeapDump/FullGCHeapDumpLimitTest.java fails

### PR DESCRIPTION
**Pull request by D-D-H**
Hi,

Please help review this patch that fixes the failures of FullGCHeapDumpLimitTest.java caused by passing other gc flags.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322989](https://bugs.openjdk.org/browse/JDK-8322989): New test serviceability/HeapDump/FullGCHeapDumpLimitTest.java fails (**Bug** - P3)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [734f1d7e](https://git.openjdk.org/jdk/pull/17263/files/734f1d7eff45db500d95d2f2335ce4387ab93b5d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17263/head:pull/17263` \
`$ git checkout pull/17263`

Update a local copy of the PR: \
`$ git checkout pull/17263` \
`$ git pull https://git.openjdk.org/jdk.git pull/17263/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17263`

View PR using the GUI difftool: \
`$ git pr show -t 17263`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17263.diff">https://git.openjdk.org/jdk/pull/17263.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17263#issuecomment-1876675901)

### CODE REVIEW

**Review by stefank — CHANGES_REQUESTED** [review]
I prefer if we stay away from using `@requires vm.flagless` if possible. For this test I think we can just add `@requires vm.gc.Serial`? Could you try that instead?

**Comment by dholmes-ora** [comment]
> For this test I think we can just add @requires vm.gc.Serial

@stefank but it doesn't require that, it explicitly sets that. The test requires that no specific GC has been requested.

**Comment by D-D-H** [comment]
I found other tests that set -XX:+UseSerialGC explicitly have `@requires vm.gc.Serial` or  `vm.gc == "Serial" | vm.gc == "null"`

**Comment by D-D-H** [comment]
And for this test, I think `@requires vm.opt.DisableExplicitGC != "true"` is also needed.

**Comment by stefank** [comment]
> > For this test I think we can just add @requires vm.gc.Serial
> 
> @stefank but it doesn't require that, it explicitly sets that. The test requires that no specific GC has been requested.

@dholmes-ora `@requires vm.gc.Serial` doesn't mean that it requires Serial to be set. It's more subtle than that. It means that either Serial is set (and available) or it can be set (because no other GC has been selected). It is the correct requires line to use when you explicitly set the GC in the test. Look at our other GC tests.

For example:
test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java

Without selecting a GC, the test is run:
```
$ make -C ../build/fastdebug test TEST=test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java JTREG="JAVA_OPTIONS=-Xmx128m"
...
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:open/test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java
                                                         1     1     0     0  
```

With Serial as the selected GC, the test is run:
```
$ make -C ../build/fastdebug test TEST=test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java JTREG="JAVA_OPTIONS=-Xmx128m -XX:+UseSerialGC"
...
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:open/test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java
                                                         1     1     0     0   
```

With G1 as the selected GC, the test is excluded:
```
$ make -C ../build/fastdebug test TEST=test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java JTREG="JAVA_OPTIONS=-Xmx128m -XX:+UseG1GC"
...
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:open/test/hotspot/jtreg/gc/arguments/TestNewSizeThreadIncrease.java
                                                         0     0     0     0   
```

**Comment by dcubed-ojdk** [comment]
We're up to 48 test failures so far (8 x 6 Tier3 buildIDs) which is very, very noisy.
Since it looks like this PR is still being discussed, I'm going to ProblemList this
test in order to get the noise level back down.

**Comment by D-D-H** [comment]
> We're up to 48 test failures so far (8 x 6 Tier3 buildIDs) which is very, very noisy. Since it looks like this PR is still being discussed, I'm going to ProblemList this test in order to get the noise level back down.

sorry for that :-(

**Comment by dcubed-ojdk** [comment]
ProblemListing PR has been approved and should integrate shortly:
https://github.com/openjdk/jdk/pull/17269
Please update your repo to include that fix so that you can remove the
test from the ProblemList.txt file in your PR.

**Comment by dholmes-ora** [comment]
> It means that either Serial is set (and available) or it can be set 

@stefank that is subtle - and unintuitive. Thanks for explaining.

**Comment by D-D-H** [comment]
> ProblemListing PR has been approved and should integrate shortly: #17269 Please update your repo to include that fix so that you can remove the test from the ProblemList.txt file in your PR.

Done.

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable based on previous discussions.

You may need to update the Alibaba copyright header now it is 2024 (depends on their rules, whatever they may be).

Thanks

**Comment by D-D-H** [comment]
@dholmes-ora Thanks for the review.

This change only involves the test part. Do I need a second review?

**Comment by dholmes-ora** [comment]
@D-D-H given the discussion it would be best if @stefank also approved it. Thanks.

**Review by stefank — APPROVED** [review]

**Comment by D-D-H** [comment]
/integrate

Thanks for the review.

**Pull request closed without merging**
