### PR TITLE
8267151: C2: Don't create dummy Opaque1Node for outmost unswitched IfNode

### PR DESCRIPTION
**Pull request by kelthuzadx**
In create_slow_version_of_loop(), C2 creates the outmost unswitched IfNode(i.e. **if(xx)**{ for{} }else{ for{} }) with a dummy opaque bool node as its condition input.

https://github.com/openjdk/jdk/blob/cd1c17c0a6416a8d16cf2035f3e97dba95b6b8af/src/hotspot/share/opto/loopUnswitch.cpp#L265-L271

After that, it sets the _prob(missing _fcnt?) of the outmost unswitched IfNode in do_unswitching().

https://github.com/openjdk/jdk/blob/cd1c17c0a6416a8d16cf2035f3e97dba95b6b8af/src/hotspot/share/opto/loopUnswitch.cpp#L186-L191

I think we can merge these two steps into a single step, that is, create the outmost unswitched IfNode meanwhile setting its condition input, _prob and _fcnt w/ creating the dummy opaque bool node.

Testing:
- hotspot/jtreg/compiler(slowdebug)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267151](https://bugs.openjdk.java.net/browse/JDK-8267151): C2: Don't create dummy Opaque1Node for outmost unswitched IfNode

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4079/head:pull/4079` \
`$ git checkout pull/4079`

Update a local copy of the PR: \
`$ git checkout pull/4079` \
`$ git pull https://git.openjdk.java.net/jdk pull/4079/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4079`

View PR using the GUI difftool: \
`$ git pr show -t 4079`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4079.diff">https://git.openjdk.java.net/jdk/pull/4079.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by neliasso — APPROVED** [review]
Looks good.

**Comment by kelthuzadx** [comment]
Thank you Nils and Tobias for taking the time to review this patch! 

/integrate

**Pull request closed without merging**
