### PR TITLE
8248122: java.base should not handle JavaFX application in a specific way

### PR DESCRIPTION
**Pull request by amCap1712**
JavaFX is no longer a part of OpenJDK. It makes sense to not treat it specially in the JDK. Hence, refactoring the Launcher class to remove JavaFX specific code.

Further investigation reveals that some JavaFX specific code is also present in the `javadoc` tool. For instance,
https://github.com/openjdk/jdk/blob/master/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/BaseOptions.java#L90-L96
https://github.com/openjdk/jdk/blob/master/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/BaseOptions.java#L347-L353
I think we should remove this code as well and the related tests for it.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8248122](https://bugs.openjdk.java.net/browse/JDK-8248122): java.base should not handle JavaFX application in a specific way

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/978/head:pull/978`
`$ git checkout pull/978`

### CODE REVIEW

**Comment by AlanBateman** [comment]
label add core-libs

**Comment by AlanBateman** [comment]
Please start a discussion on core-libs-dev before proposing this patch.

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
This will cause a regression in behavior. It will break existing JavaFX applications that do not have a main program. It could also break applications that create or use certain JavaFX objects in the class initializer of their JavaFX application.

There was [some initial discussion](https://bugs.openjdk.java.net/browse/JDK-8202553?focusedCommentId=14176584&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14176584) around doing this as a follow-on to the removal of JavaFX from JDK 11, but if it is to be done, it needs to be discussed first. It would need to be done using a process similar to deprecation-for-removal. We would need to make changes in the JDK and/or JavaFX to warn about this in one release, and then remove it in the following. A CSR would be needed for both steps.

I note that while I disagree with the rationale described in [JDK-8248122](https://bugs.openjdk.java.net/browse/JDK-8248122) for making this change, I am not necessarily opposed to the change itself.

**Comment by kevinrushforth** [comment]
This also needs to be discussed on the openjfx-dev mailing list, since it will have behavioral compatibility implications for JavaFX.

**Comment by prrace** [comment]
Indeed this is very much of out the blue and the pre-existence of a bug report discussing this does not mean it
has been accepted to be done .. 

And launcher changes need to be done carefully. I would expect them to come from someone who has a long history of contributions in this area and has had extensive discussions with stakeholders before moving on to code ..

**Pull request closed without merging**
