### PR TITLE
JDK-8330795 : C2: assert((uint)type <= T_CONFLICT && _zero_type[type] != nullptr) failed: bad type with -XX:-UseCompressedClassPointers

### PR DESCRIPTION
**Pull request by JohnTortugo**
The `assert((uint)type <= T_CONFLICT && _zero_type[type] != nullptr) failed: bad type` failure was caused by the fact that we didn't have a "zero value" for the type T_METADATA. The RAM patch uses that data when it creates a Phi node merging Klass loads and UseCompressedClassPointers is disabled.

Tested with JTREG tier1-4 on Linux x86_64 & ARM64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330795](https://bugs.openjdk.org/browse/JDK-8330795): C2: assert((uint)type &lt;= T_CONFLICT &amp;&amp; _zero_type[type] != nullptr) failed: bad type with -XX:-UseCompressedClassPointers (**Bug** - P3)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19148/head:pull/19148` \
`$ git checkout pull/19148`

Update a local copy of the PR: \
`$ git checkout pull/19148` \
`$ git pull https://git.openjdk.org/jdk.git pull/19148/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19148`

View PR using the GUI difftool: \
`$ git pr show -t 19148`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19148.diff">https://git.openjdk.org/jdk/pull/19148.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19148#issuecomment-2101674457)

### CODE REVIEW

**Comment by vnkozlov** [comment]
New test failed in GHA with 32-bit VM because:
```
Unrecognized VM option 'UseCompressedClassPointers'
```
You can add `-XX:+IgnoreUnrecognizedVMOptions` to run test on all platforms.

**Comment by vnkozlov** [comment]
@JohnTortugo, thank you for adding new test. But it would be nice also add additional run with `-XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedClassPointers` to failed test `test/hotspot/jtreg/compiler/c2/irTests/scalarReplacement/AllocationMergesTests.java`

Also why you require to run test only with compressed oops on?:
```
* @requires vm.debug == true & vm.bits == 64 & vm.compiler2.enabled & vm.opt.final.UseCompressedOops & vm.opt.final.EliminateAllocations
```

**Comment by vnkozlov** [comment]
> @JohnTortugo, thank you for adding new test. But it would be nice also add additional run with `-XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedClassPointers` to failed test `test/hotspot/jtreg/compiler/c2/irTests/scalarReplacement/AllocationMergesTests.java`
 
Actually `-XX:+IgnoreUnrecognizedVMOptions` is not needed because you require `vm.bits == 64` in the test.

**Comment by JohnTortugo** [comment]
> @JohnTortugo, thank you for adding new test. But it would be nice also add additional run with -XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedClassPointers to failed test test/hotspot/jtreg/compiler/c2/irTests/scalarReplacement/AllocationMergesTests.java

Thank you @vnkozlov , I'll work on that.

**Comment by JohnTortugo** [comment]
@vnkozlov - I updated the patch by adding new tests with CompressedOops/CompressedClassPointers enabled and disabled.

**Comment by vnkozlov** [comment]
@JohnTortugo This looks reasonable. Can you explain more why having klass field load is bad for your code?

Is it because you need klass as constant for deoptimization?

Is it possible to handle such case (loading klass) as separate RFE later?

**Comment by JohnTortugo** [comment]
> Can you explain more why having klass field load is bad for your code?

The issue involves LoadNKlass, DecodeNKlass and NULL NKlass. It happens when splitting a LoadNKlass through a nullable Phi. In that process another "nullable" Phi of type TypeNarrowKlass may be created merging the "Klass'es" of the original Phi inputs. A NULL NarrowKlass seems to be something not quite well defined: for instance, there is no definition of "_zero_type" for T_METADATA which is the basic type of TypeNarrowKlass. The first commit in this PR was to add this definition. 

However, I think a better approach - than the one from first commit - maybe to instead of creating a Phi of type NarrowKlass create a Phi of type TypePtr that merges DecodeNKlass. By doing so I won't need to create a Phi with a NULL **NKlass** so the original patch isn't necessary. However, in my opinion, doing that is better left for a separate RFE + PR.

> Is it possible to handle such case (loading klass) as separate RFE later?

Yes, I think we can do it as a separate RFE. However, in my experiments klass field loading doesn't appear very often in the benchmarks and therefore may not be much worth the added complication.

**Comment by vnkozlov** [comment]
> However, in my experiments klass field loading doesn't appear very often in the benchmarks and therefore may not be much worth the added complication.

It may be true for code with new allocations but in general case when an object is passed as argument or loaded from field klass loading is common case.

**Comment by vnkozlov** [comment]
Thank you for explaining issue you have with klass loading.
I will run our testing with you current version.

**Review by vnkozlov — APPROVED** [review]
My testing passed.

**Pull request closed without merging**
