### PR TITLE
8312424: 80% throughput decrease in Arrays.hashCode(Object[]) after JDK-8312164

### PR DESCRIPTION
**Pull request by Glavo**
The changes to `Arrays.hashCode(Object[])` in JDK-8312164 caused its performance  is reduced by about 80%.

This PR reverts this change.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312424](https://bugs.openjdk.org/browse/JDK-8312424): 80% throughput decrease in Arrays.hashCode(Object[]) after JDK-8312164 (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14944/head:pull/14944` \
`$ git checkout pull/14944`

Update a local copy of the PR: \
`$ git checkout pull/14944` \
`$ git pull https://git.openjdk.org/jdk.git pull/14944/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14944`

View PR using the GUI difftool: \
`$ git pr show -t 14944`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14944.diff">https://git.openjdk.org/jdk/pull/14944.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14944#issuecomment-1642976052)

### CODE REVIEW

**Comment by Glavo** [comment]
JMH Benchmark:

```java
public class HashCode {
    @Param({"1", "10", "100", "10000"})
    private int size;

    private Object[] objects;

    @Setup
    public void setup() {
        objects = new Object[size];

        Random rnd = new Random(0);
        for (int i = 0; i < size; i++) {
            int next = rnd.nextInt();
            objects[i] = next;
        }
    }
    @Benchmark
    public int objects() {
        return Arrays.hashCode(objects);
    }
}
```

```
                                                (JDK-8312164)                      (This PR)
Benchmark         (size)   Mode  Cnt       Score      Error   Units           Score      Error   Units
HashCode.objects       1  thrpt    5  230185.853 ± 3452.863  ops/ms      646049.006 ± 3964.138  ops/ms
HashCode.objects      10  thrpt    5   25745.466 ±   38.342  ops/ms      121587.901 ± 1114.723  ops/ms
HashCode.objects     100  thrpt    5    2558.474 ±   21.726  ops/ms       11914.620 ±  233.365  ops/ms
HashCode.objects   10000  thrpt    5      27.592 ±    0.116  ops/ms         125.938 ±    0.145  ops/ms
```

**Comment by liach** [comment]
A similar performance decrease have been discussed here: https://github.com/openjdk/jdk/pull/14752#discussion_r1250888931

Can you check whether adding `@ForceInline` on `Objects.equals` help with JIT? If it helps, then I think adding `@ForceInline` might be a better solution.

**Comment by Glavo** [comment]
> A similar performance decrease have been discussed here: [#14752 (comment)](https://github.com/openjdk/jdk/pull/14752#discussion_r1250888931)
> 
> Can you check whether adding `@ForceInline` on `Objects.equals` help with JIT? If it helps, then I think adding `@ForceInline` might be a better solution.

I added `@ForceInline` on `Objects.hashCode(Object)`, but the JMH results did not change.

**Comment by liach** [comment]
Created JBS issue for you: https://bugs.openjdk.org/browse/JDK-8312424

I chose a generic title which applies to both reverting the last patch or updating Objects methods.

**Comment by liach** [comment]
@Glavo I have created a test case with polymorphic objects in an array: https://github.com/liachmodded/jdk/tree/explore/arrays-hash-poly
Can you see if you can produce the same outcome on your patch, and how the existing `Objects.equals` behave on the polymorphicObjects case?

````
Benchmark               (size)  Mode  Cnt     Score    Error  Units
ArraysHashCode.objects       1  avgt   15     0.770 ±  0.011  ns/op
ArraysHashCode.objects      10  avgt   15     4.704 ±  0.059  ns/op
ArraysHashCode.objects     100  avgt   15    54.610 ±  0.384  ns/op
ArraysHashCode.objects   10000  avgt   15  6053.742 ± 35.244  ns/op
````

```
Benchmark                          (size)  Mode  Cnt      Score      Error  Units
ArraysHashCode.polymorphicObjects       1  avgt   15      0.921 ±    0.069  ns/op
ArraysHashCode.polymorphicObjects      10  avgt   15     23.322 ±    1.076  ns/op
ArraysHashCode.polymorphicObjects     100  avgt   15    211.325 ±    2.200  ns/op
ArraysHashCode.polymorphicObjects   10000  avgt   15  81850.916 ± 2427.661  ns/op
```

**Comment by Glavo** [comment]
@liach 

JMH Result:

```
                                                           (JDK-8312164)                  (This PR)
Benchmark                    (size)   Mode  Cnt       Score    Error   Units         Score      Error   Units
HashCode.polymorphicObjects       1  thrpt    5  148056.877 ±  8.046  ops/ms    546370.781 ± 2682.146  ops/ms
HashCode.polymorphicObjects      10  thrpt    5   21207.629 ± 39.585  ops/ms     21491.320 ±   66.698  ops/ms
HashCode.polymorphicObjects     100  thrpt    5    1467.886 ± 21.025  ops/ms      1509.838 ±   11.098  ops/ms
HashCode.polymorphicObjects   10000  thrpt    5       9.037 ±  0.006  ops/ms         9.123 ±    0.022  ops/ms

```

**Comment by JornVernee** [comment]
With a size of `1`, the polymorphic version is not really polymorphic. This seems to be about profile pollution inside `Objects.hashCode(Object)`. But, the same pollution can happen for `Arrays.hashCode(Object[])` as well, unless an application only ever calls this method with arrays with the same element type (seems unlikely).

To create a representative 'polluted' benchmark, you should create at least 2 other arrays that hold instances of another type than `Integer`, and then call `Arrays.hashCode` a bunch (like 10K times) in the setup method. [1]. Note how the polluted case is exactly the same with the old code:

```
Objects.hashCode(Object)

Benchmark               (pollute)  (size)  Mode  Cnt      Score    Error  Units
ArraysHashCode.objects       true       1  avgt   15      3.053 ±  0.011  ns/op
ArraysHashCode.objects       true      10  avgt   15     26.955 ±  0.192  ns/op
ArraysHashCode.objects       true     100  avgt   15    269.441 ±  1.788  ns/op
ArraysHashCode.objects       true   10000  avgt   15  26419.822 ± 56.444  ns/op
ArraysHashCode.objects      false       1  avgt   15      3.049 ±  0.007  ns/op
ArraysHashCode.objects      false      10  avgt   15     26.797 ±  0.040  ns/op
ArraysHashCode.objects      false     100  avgt   15    268.127 ±  0.351  ns/op
ArraysHashCode.objects      false   10000  avgt   15  26446.978 ± 66.340  ns/op
```
```
(element == null ? 0 : element.hashCode())

Benchmark               (pollute)  (size)  Mode  Cnt      Score     Error  Units
ArraysHashCode.objects       true       1  avgt   15      3.056 ±   0.015  ns/op
ArraysHashCode.objects       true      10  avgt   15     26.840 ±   0.081  ns/op
ArraysHashCode.objects       true     100  avgt   15    268.204 ±   0.462  ns/op
ArraysHashCode.objects       true   10000  avgt   15  26410.336 ±  77.897  ns/op
ArraysHashCode.objects      false       1  avgt   15      0.818 ±   0.001  ns/op
ArraysHashCode.objects      false      10  avgt   15      5.130 ±   0.013  ns/op
ArraysHashCode.objects      false     100  avgt   15     58.394 ±   0.508  ns/op
ArraysHashCode.objects      false   10000  avgt   15   6274.471 ± 427.928  ns/op
```

If you look at `PrintInlining` output:

Non-polluted:
    
                            @ 1   java.util.Arrays::hashCode (56 bytes)   inline (hot)
                              @ 43   java.lang.Integer::hashCode (8 bytes)   inline (hot)
                               \-> TypeProfile (15360/15360 counts) = java/lang/Integer
                                @ 4   java.lang.Integer::hashCode (2 bytes)   inline (hot)
                                
 Polluted:
 
                             @ 1   java.util.Arrays::hashCode (56 bytes)   inline (hot)
                              @ 43   java.lang.Object::hashCode (0 bytes)   (intrinsic, virtual)

i.e. `Arrays::hashCode(Object[])` is still susceptible to pollution, and I don't really think that the benchmark you've added in this PR is representative of a real world scenario since it only uses one element type. I don't think using `Objects.hashCode` is really that much of a problem here. Though, I'll grant that it at least has an observable difference.

[1]: https://github.com/openjdk/jdk/compare/master...JornVernee:jdk:PollutedBenchmark

**Pull request closed without merging**
