### PR TITLE
8313752: InstanceKlassFlags::print_on doesn't print the flag names

### PR DESCRIPTION
**Pull request by stefank**
I've found that our misc flags printing is broken. This can be seen in our hs_err files:
```
RCX=0x00007f86bf0073c8 is a pointer to class: 
java.lang.Class {0x00007f86bf0073c8}
 - instance size:     22
 - klass size:        97
 - access:            public final synchronized 
 - flags:              ##name  ##name  ##name  ##name  ##name  ##name 
```

With this fix the flags are now printed as expected:
```
java.util.Hashtable {0x00007f5fff00e8c0}
 - instance size:     8
 - klass size:        123
 - access:            public synchronized 
 - flags:              rewritten  has_nonstatic_fields  has_nonstatic_concrete_methods  is_shared_boot_class  has_localvariable_table  has_final_method 
```

The indentation doesn't look that great, so if you want me to change it I can do so in this patch as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313752](https://bugs.openjdk.org/browse/JDK-8313752): InstanceKlassFlags::print_on doesn't print the flag names (**Bug** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [beae18c2](https://git.openjdk.org/jdk/pull/15153/files/beae18c2e01f2d5603613cba8e90cb237cfa216a)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15153/head:pull/15153` \
`$ git checkout pull/15153`

Update a local copy of the PR: \
`$ git checkout pull/15153` \
`$ git pull https://git.openjdk.org/jdk.git pull/15153/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15153`

View PR using the GUI difftool: \
`$ git pr show -t 15153`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15153.diff">https://git.openjdk.org/jdk/pull/15153.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15153#issuecomment-1665464700)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Good! And thanks for the test.

I'm unemotional about the indentation. Up to you.

**Review by shipilev — APPROVED** [review]
Whoops. Yes, just drop the leading space, if you can?

**Comment by shipilev** [comment]
Seems like introduced by https://github.com/openjdk/jdk/commit/316d303c1da550c9589c9be56b65650964e3886b#diff-1986c820f9f6ad5652414e734fa6d18cde5808bf943e220bcd99f8cd6e1c9eedR57

If we change the spaces, then `ConstMethodFlags::print_on` might need a change too.

**Comment by stefank** [comment]
OK. Thanks for reviewing! I'll wait for @coleenp to chime in.

**Review by coleenp — APPROVED** [review]
Thank you for finding and fixing this also can be considered trivial.

**Comment by stefank** [comment]
I've tweaked the output slightly so that it looks nicer:
```
 - access:            public interface abstract 
 - flags:             rewritten is_shared_boot_class 
 - state:             linked
```

Manually inspected the output of InstanceKlassFlags::print_on and 
MethodFlags::print_on.

ConstMethod::print_on doesn't seem to be explicitly called. Also note that ConstMethod::print_on isn't an "override" because ConstMethod inherits from MetaspaceObj and not Metadata.

**Comment by tstuefe** [comment]
Still good

**Review by shipilev — APPROVED** [review]
Still fine.

**Comment by stefank** [comment]
Thanks for reviewing!
/integrate

**Pull request closed without merging**
