### PR TITLE
JDK-8304828: Lots of constant static data not declared static const in cpu/x86

### PR DESCRIPTION
**Pull request by jcking**
Simple refactor that updates declarations and definitions for data that is effectively static and constant to be `static` and/or `const`. Helps make sure we do not break the one definition rule and helps the compiler/linker to place the data in read-only sections of the executable.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8304828](https://bugs.openjdk.org/browse/JDK-8304828): Lots of constant static data not declared static const in cpu/x86

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13163/head:pull/13163` \
`$ git checkout pull/13163`

Update a local copy of the PR: \
`$ git checkout pull/13163` \
`$ git pull https://git.openjdk.org/jdk.git pull/13163/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13163`

View PR using the GUI difftool: \
`$ git pr show -t 13163`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13163.diff">https://git.openjdk.org/jdk/pull/13163.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems okay. I don;t know how disruptive this may be for backports.

Thanks

**Review by vnkozlov — COMMENTED** [review]
Changes looks good. But please restart GHA testing. Something went wrong there.

**Comment by vnkozlov** [comment]
Good. I submitted our testing.

**Review by vnkozlov — APPROVED** [review]
My testing passed.

**Pull request closed without merging**
