### PR TITLE
8331142: Add test for number of loader threads in BasicDirectoryModel

### PR DESCRIPTION
**Pull request by aivanov-jdk**
This PR provides a regression test for [JDK-8325179](https://bugs.openjdk.org/browse/JDK-8325179): _Race in BasicDirectoryModel.validateFileCache_ reviewed in #18111.

The test is inspired and based on `ConcurrentModification` that I wrote for [JDK-8327137](https://bugs.openjdk.org/browse/JDK-8327137) / [JDK-8323670](https://bugs.openjdk.org/browse/JDK-8323670).

**How the test works**

The test creates a temporary directory in the current directory and creates a number of files in it. (The number of files is controlled by `NUMBER_OF_THREADS` constant). Then the test creates `JFileChooser` in the temporary directory.

The test starts several scanner threads, the number is controlled by `NUMBER_OF_THREADS`, which repeatedly call `fileChooser.rescanCurrentDirectory()`. This results in calling `BasicDirectoryModel.validateFileCache` which starts a background thread — "Basic L&F File Loading Thread" — to enumerate the files.

The test runner thread and scanner threads are synchronised with `CyclicBarrier`, this ensures all the scanner threads start at the same time. After a short delay, the runner thread takes a snapshot of live threads. After a longer delay, the operation is repeated. See the `getThreadSnapshot` method. (The number of snapshots is controlled by `SNAPSHOTS` constant.)

The number of File Loading Threads in each snapshot is counted. There should be no more than two threads. It is possible that thread two such threads after JDK-8325179 is fixed: the existing thread is interrupted but hasn't exited yet, and a new thread is already created.

The test fails consistently without the fix for JDK-8325179. On Windows, the output looks like this:

```text
Number of snapshots: 20
Number of snapshots where number of loader threads:
  = 1: 0
  = 2: 0
  > 2: 20
java.lang.RuntimeException: Detected 20 snapshots with several loading threads
        at LoaderThreadCount.runTest(LoaderThreadCount.java:132)
        at LoaderThreadCount.wrapper(LoaderThreadCount.java:72)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

On Linux and macOS, there's more variation, for example I got the following output on one of Linux systems:

```text
Number of snapshots: 15
Number of snapshots where number of loader threads:
  = 1: 7
  = 2: 2
  > 2: 6
```

The test passes on the builds where JDK-8325179 is present.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331142](https://bugs.openjdk.org/browse/JDK-8331142): Add test for number of loader threads in BasicDirectoryModel (**Bug** - P4)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to [49723a37](https://git.openjdk.org/jdk/pull/18957/files/49723a3782c2278399e717df540099b8d0c07fd6)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18957/head:pull/18957` \
`$ git checkout pull/18957`

Update a local copy of the PR: \
`$ git checkout pull/18957` \
`$ git pull https://git.openjdk.org/jdk.git pull/18957/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18957`

View PR using the GUI difftool: \
`$ git pr show -t 18957`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18957.diff">https://git.openjdk.org/jdk/pull/18957.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18957#issuecomment-2077733268)

### CODE REVIEW

**Comment by aivanov-jdk** [comment]
Could you, @mrserb and @TejeshR13, take a look? You reviewed the test for [JDK-8323670](https://bugs.openjdk.org/browse/JDK-8323670) in #18109.

Those who reviewed [JDK-8325179](https://bugs.openjdk.org/browse/JDK-8325179) in #18111 — @prrace and @turbanoff — could be interested too.

**Review by mrserb — APPROVED** [review]

**Review by TejeshR13 — COMMENTED** [review]
Is it necessary to create dummy files here in this test? Can't we just create JFileChooser without creating dummy files and proceed with loader test?

**Comment by aivanov-jdk** [comment]
> Is it necessary to create dummy files here in this test? Can't we just create JFileChooser without creating dummy files and proceed with loader test? Because I tested without using dummy files and getting exception without JDK-8325179 fix.

Yes, it is necessary to create the dummy files. The background threads need to run for a while; if there are no files, the threads may complete before the snapshot is created.

Windows is usually less affected because all scanning on Windows is serialized via the COM thread. Linux and macOS aren't stable enough without the files. Even with the files, in one of the runs on Linux, there were only 4 snapshots which contained the File Loader threads. That is 4 out of 20 snapshots taken. Without the files and with less files, the test could pass where it should fail.

**Comment by TejeshR13** [comment]
> > Is it necessary to create dummy files here in this test? Can't we just create JFileChooser without creating dummy files and proceed with loader test? Because I tested without using dummy files and getting exception without JDK-8325179 fix.
> 
> Yes, it is necessary to create the dummy files. The background threads need to run for a while; if there are no files, the threads may complete before the snapshot is created.
> 
> Windows is usually less affected because all scanning on Windows is serialized via the COM thread. Linux and macOS aren't stable enough without the files. Even with the files, in one of the runs on Linux, there were only 4 snapshots which contained the File Loader threads. That is 4 out of 20 snapshots taken. Without the files and with less files, the test could pass where it should fail.

Yeah, my observation was w.r.t windows. Will have to test in Linux then.

**Comment by TejeshR13** [comment]
> > Is it necessary to create dummy files here in this test? Can't we just create JFileChooser without creating dummy files and proceed with loader test? Because I tested without using dummy files and getting exception without JDK-8325179 fix.
> 
> Yes, it is necessary to create the dummy files. The background threads need to run for a while; if there are no files, the threads may complete before the snapshot is created.
> 
> Windows is usually less affected because all scanning on Windows is serialized via the COM thread. Linux and macOS aren't stable enough without the files. Even with the files, in one of the runs on Linux, there were only 4 snapshots which contained the File Loader threads. That is 4 out of 20 snapshots taken. Without the files and with less files, the test could pass where it should fail.

You are right, failure is unpredictable in linux unlike in Windows.  Test looks good to me.

**Review by TejeshR13 — APPROVED** [review]

**Review by TejeshR13 — APPROVED** [review]
Looks Good to me.

**Review by TejeshR13 — APPROVED** [review]

**Pull request closed without merging**
