### PR TITLE
8284584: Avoid duplicate node_idx_t definitions

### PR DESCRIPTION
**Pull request by shipilev**
While looking at `Node`, I realized there are two definitions for node_idx_t, another one added by [JDK-8076284](https://bugs.openjdk.java.net/browse/JDK-8076284). These should be de-duplicated to avoid confusion.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284584](https://bugs.openjdk.java.net/browse/JDK-8284584): Avoid duplicate node_idx_t definitions

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8164/head:pull/8164` \
`$ git checkout pull/8164`

Update a local copy of the PR: \
`$ git checkout pull/8164` \
`$ git pull https://git.openjdk.java.net/jdk pull/8164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8164`

View PR using the GUI difftool: \
`$ git pr show -t 8164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8164.diff">https://git.openjdk.java.net/jdk/pull/8164.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I am not sure we want to move C2's specific type to general code.
`node.hpp` includes `compile.hpp` so may be leave definition there only.

**Comment by shipilev** [comment]
> I am not sure we want to move C2's specific type to general code. `node.hpp` includes `compile.hpp` so may be leave definition there only.

`compile.hpp` looks like a dumping ground for everything global to C2, right? If so, it indeed makes sense to leave the only definition there. Please see new commit.

**Comment by shipilev** [comment]
Thank you! Simple/trivial, or do I need another reviewer?

**Review by cl4es — APPROVED** [review]
Looks good and trivial

**Comment by shipilev** [comment]
Thanks!
/integrate

**Pull request closed without merging**
