### PR TITLE
8301067: RISC-V: better error message when reporting unsupported satp modes

### PR DESCRIPTION
**Pull request by feilongjiang**
Add more detailed information to the error log when reporting unsupported stap modes.
Currently, RISC-V port only supports up to sv48.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301067](https://bugs.openjdk.org/browse/JDK-8301067): RISC-V: better error message when reporting unsupported satp modes

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Yadong Wang](https://openjdk.org/census#yadongwang) (@yadongw - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12247/head:pull/12247` \
`$ git checkout pull/12247`

Update a local copy of the PR: \
`$ git checkout pull/12247` \
`$ git pull https://git.openjdk.org/jdk pull/12247/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12247`

View PR using the GUI difftool: \
`$ git pr show -t 12247`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12247.diff">https://git.openjdk.org/jdk/pull/12247.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — COMMENTED** [review]
Don't forget to update the copyright years.

**Comment by feilongjiang** [comment]
> Don't forget to update the copyright years.

I have merged master and now the copyright looks updated.

**Review by RealFYang — APPROVED** [review]

**Review by yadongw — APPROVED** [review]
lgtm

**Comment by feilongjiang** [comment]
@RealFYang @yadongw -- Thanks for the reviews!
/integrate

**Pull request closed without merging**
