### PR TITLE
8284992: Fix misleading Vector API doc for LSHR operator

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

The Current Vector API doc for `LSHR` is
```
Produce a>>>(n&(ESIZE*8-1)). Integral only.
```

This is misleading which may lead to bugs for Java developers.
This is because for negative byte/short elements, the results computed by `LSHR` will be different from that of `>>>`.
For more details, please see https://github.com/openjdk/jdk/pull/8276#issue-1206391831 .

After the patch, the doc for `LSHR` is
```
Produce zero-extended right shift of a by (n&(ESIZE*8-1)) bits. Integral only.
```

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8284992](https://bugs.openjdk.java.net/browse/JDK-8284992): Fix misleading Vector API doc for LSHR operator
 * [JDK-8285771](https://bugs.openjdk.java.net/browse/JDK-8285771): Fix misleading Vector API doc for LSHR operator (**CSR**)

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8291/head:pull/8291` \
`$ git checkout pull/8291`

Update a local copy of the PR: \
`$ git checkout pull/8291` \
`$ git pull https://git.openjdk.java.net/jdk pull/8291/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8291`

View PR using the GUI difftool: \
`$ git pr show -t 8291`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8291.diff">https://git.openjdk.java.net/jdk/pull/8291.diff</a>

</details>

### CODE REVIEW

**Comment by PaulSandoz** [comment]
I need to think a little more about this. The specification is not accurate and likely requires a CSR.

My initial thoughts are I would prefer the operation to retain reference to the succinct definition using the logical right shift operator but we add additional specification explaining the cases for `byte` and `short`, namely that the result is widened to an `int` as if by `(a & ((1 << ESIZE) - 1))` and the result narrowed. That's commonly (at least for the widening part) how `>>>` is used with `byte` and `short`, and i think would be clearer to be explicit in that regard.

**Comment by DamonFool** [comment]
> I need to think a little more about this. The specification is not accurate and likely requires a CSR.
> 
> My initial thoughts are I would prefer the operation to retain reference to the succinct definition using the logical right shift operator but we add additional specification explaining the cases for `byte` and `short`, namely that the result is widened to an `int` as if by `(a & ((1 << ESIZE) - 1))` and the result narrowed. That's commonly (at least for the widening part) how `>>>` is used with `byte` and `short`, and i think would be clearer to be explicit in that regard.

OK.
To avoid confusing I would prefer using the description of `>>>` in the new vector operator, which would perform the same behavior as the scalar `>>>`.

**Comment by PaulSandoz** [comment]
The intended pattern for the operator tokens is to present a short symbolic description using Java operators and common methods. It would be good to try and keep with this pattern, and clarify for the extra cases. Here's what i had in mind:

    /** Produce {@code a>>>(n&(ESIZE*8-1))}.  Integral only. 
      * <p>
      * For operand types {@code byte} and {@code short} the operation behaves as if the operand is first implicitly widened  
      * to an {@code int} value with {@code (a & ((1 << ESIZE) - 1))} the result of which is then applied as the operand to this 
      * operation, the result of the operation is then narrowed from {@code int} to the operand type using an explicit cast.
      */
    public static final /*bitwise*/ Binary LSHR;

**Comment by DamonFool** [comment]
> The intended pattern for the operator tokens is to present a short symbolic description using Java operators and common methods. It would be good to try and keep with this pattern, and clarify for the extra cases. Here's what i had in mind:
> 
> ```
> /** Produce {@code a>>>(n&(ESIZE*8-1))}.  Integral only. 
>   * <p>
>   * For operand types {@code byte} and {@code short} the operation behaves as if the operand is first implicitly widened  
>   * to an {@code int} value with {@code (a & ((1 << ESIZE) - 1))} the result of which is then applied as the operand to this 
>   * operation, the result of the operation is then narrowed from {@code int} to the operand type using an explicit cast.
>   */
> public static final /*bitwise*/ Binary LSHR;
> ```

This works only if people would like to read the detailed description of `LSHR` carefully.

Actually, most developers would still see the brief description first.
image
 
If they don't click out the detailed description further or don't read it carefully, it's still misleading.

Maybe, we'd better not to use `>>>` in the brief description since `LSHR` behaves differently with the common used `>>>`.
What do you think?

**Comment by PaulSandoz** [comment]
We can raise attention to that:
```
/** Produce {@code a>>>(n&(ESIZE*8-1))} 
  * (The operand and result are converted if the operand type is {@code byte} or {@code short}, see below).  Integral only.
  * ...
  */
```

**Comment by DamonFool** [comment]
Add hotspot-compiler since the JBS has been moved there.
/label add hotspot-compiler

**Comment by DamonFool** [comment]
> We can raise attention to that:
> 
> ```
> /** Produce {@code a>>>(n&(ESIZE*8-1))} 
>   * (The operand and result are converted if the operand type is {@code byte} or {@code short}, see below).  Integral only.
>   * ...
>   */
> ```


It seems still misleading if we don't change the brief description of `LSHR`.
How about adding 'see details for attention' like this?
WeChatWorkScreenshot_96b57c88-445e-4b14-a956-35e421279744

And the patch had been updated.
Thanks.

**Comment by DamonFool** [comment]
Hi @PaulSandoz ,

I add a piece of notice at the end of the brief description of `LSHR` since not everyone would click and see the details without the change.
What do you think?
Thanks.

**Comment by PaulSandoz** [comment]
After talking with John here's what we think is a better approach than what I originally had in mind:
1. In the class doc of `VectorOperators` add a definition for `EMASK` occurring after the definition for `ESIZE`:
```
 * <li>{@code EMASK} &mdash; the bit mask of the operand type, where {@code EMASK=(1<<ESIZE*8)-1} 
```
2. Change `LSHR` to be:
```
/** Produce {@code (a&EMASK)>>>(n&(ESIZE*8-1))}.  Integral only. */
```
That more clearly gets across operating in the correct domain for sub-word operand types, which was the original intention (e.g. the right shift value).

**Comment by DamonFool** [comment]
> After talking with John here's what we think is a better approach than what I originally had in mind:
> 
> 1. In the class doc of `VectorOperators` add a definition for `EMASK` occurring after the definition for `ESIZE`:
> 
> ```
>  * <li>{@code EMASK} &mdash; the bit mask of the operand type, where {@code EMASK=(1<<ESIZE*8)-1} 
> ```
> 
> 2. Change `LSHR` to be:
> 
> ```
> /** Produce {@code (a&EMASK)>>>(n&(ESIZE*8-1))}.  Integral only. */
> ```
> 
> That more clearly gets across operating in the correct domain for sub-word operand types, which was the original intention (e.g. the right shift value).

Good suggestion!
This makes sense to me.

Updated.
Thanks.

**Comment by DamonFool** [comment]
> Thanks, looks good, we will need to create a CSR. Have you done that before?

No, and I don't know much about a CSR.
Is there any example for a doc fix CSR to follow?
Thanks.

**Comment by PaulSandoz** [comment]
I created one, filled it in, and assigned it to you (for other examples you can search in the issue tracker, this one quite is simple so i thought it was quicker to do myself to show you). For any specification change we need to review and track that change (independent of any implementation changes, if any).

If you are ok with it I can add myself as reviewer, then you can "Finalize" it (see button on same line as "Edit"), triggering a review request, from which we may receive comments to address, and once addressed and final, it will unblock the PR for integration.

**Comment by DamonFool** [comment]
> I created one, filled it in, and assigned it to you (for other examples you can search in the issue tracker, this one quite is simple so i thought it was quicker to do myself to show you). For any specification change we need to review and track that change (independent of any implementation changes, if any).
> 
> If you are ok with it I can add myself as reviewer, then you can "Finalize" it (see button on same line as "Edit"), triggering a review request, from which we may receive comments to address, and once addressed and final, it will unblock the PR for integration.

Thanks @PaulSandoz for your help.

Yes, I think it's good enough.

I made a small change which just adding a `(`.
image

Thanks.

**Comment by PaulSandoz** [comment]
It should be possible for you finalize now.

**Comment by DamonFool** [comment]
> It should be possible for you finalize now.

Done.
Thanks @PaulSandoz .

**Comment by DamonFool** [comment]
Hi @PaulSandoz , the CSR had been approved and I pushed one more commit to address the CSR review comments.
Thanks.

**Review by PaulSandoz — APPROVED** [review]

**Comment by DamonFool** [comment]
Thanks @PaulSandoz for the review and help.
/integrate

**Pull request closed without merging**
