### PR TITLE
8269657: Test java/nio/channels/DatagramChannel/Loopback.java failed: Unexpected message

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [c798316b](https://github.com/openjdk/jdk/commit/c798316bc4cb33fd902f926030d8a0b6870d661a) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by SendaoYan on 28 Jun 2024 and was reviewed by Daniel Fuchs.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8269657](https://bugs.openjdk.org/browse/JDK-8269657): Test java/nio/channels/DatagramChannel/Loopback.java failed: Unexpected message (**Bug** - P3)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19936/head:pull/19936` \
`$ git checkout pull/19936`

Update a local copy of the PR: \
`$ git checkout pull/19936` \
`$ git pull https://git.openjdk.org/jdk.git pull/19936/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19936`

View PR using the GUI difftool: \
`$ git pr show -t 19936`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19936.diff">https://git.openjdk.org/jdk/pull/19936.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19936#issuecomment-2196538872)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Backport to jdk23 to fix the test intermittent failure, only change the testcase, no risk.

**Comment by sendaoYan** [comment]
Clean backport from jdk-tip to jdk23, can anyone take look this PR.

**Comment by sendaoYan** [comment]
Clean backport to fix the testcase bug and solve the intermittent failure, no risk.

**Review by jaikiran — APPROVED** [review]
This is a clean backport of a test-only fix that was integrated into master branch 3 weeks back. Looks OK to me for JDK 23.

**Comment by sendaoYan** [comment]
> is a clean backport of a test-only fix that was integrated into master

Thanks for the review.
/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
