### PR TITLE
8340426: ZGC: Move defragment out of the allocation path

### PR DESCRIPTION
**Pull request by kstefanj**
Please review this change to move defragmentation of small pages out of the allocation path,

**Summary**
In ZGC small pages are allocated at lower addresses while medium and large pages are allocated at higher addresses. Sometimes when memory usage is high or the distribution of pages in the cache demand it, small pages can be split out from medium or large pages. When this happens the small page is defragmented by remapping it to a lower address if it resides at a too high address. This is done to avoid fragmentation, but doing it in the allocation path comes with a cost since the remapping involves system calls.

This change moves the remapping away from the allocation path to when the pages are freed after being garbage collected. This can increase the fragmentation a bit, since small pages are allowed to reside at higher addresses for a period time. The expectation is that since small pages are frequently collected the period should be short enough to not cause any problems.

I've done detailed experiments with temporary JFR events to look at the cost of doing the defrag/remapping of pages. One problem is that by default we don't get a lot of defrags (unless we run out of memory), and to better investigate this I also altered the allocation path to force more defragmentation. These tests showed that moving defrag out of the allocation path not only have the positive effect of reducing the time spent allocating, but also spaced out the defragmentation a bit more.  The reason for this is that now we will defrag when a page is freed by the GC, instead of when the page is allocated and the tests show that often many threads allocate at the same time (and then also defrag at the same time). This in turn leads to many concurrent calls down to the system to remap the memory, and this increases the cost of the actual mapping (seen by adding JFR events).

**Additional testing**

- Functional testing in mach5 tier1-7
- Sanity performance testing in aurora

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340426](https://bugs.openjdk.org/browse/JDK-8340426): ZGC: Move defragment out of the allocation path (**Enhancement** - P4)

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)
 * [Joel Sikström](https://openjdk.org/census#jsikstro) (@jsikstro - Author)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21191/head:pull/21191` \
`$ git checkout pull/21191`

Update a local copy of the PR: \
`$ git checkout pull/21191` \
`$ git pull https://git.openjdk.org/jdk.git pull/21191/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21191`

View PR using the GUI difftool: \
`$ git pr show -t 21191`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21191.diff">https://git.openjdk.org/jdk/pull/21191.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21191#issuecomment-2375159256)

### CODE REVIEW

**Comment by stefank** [comment]
Thanks for fixing this!

I would like to suggest the following style changes:
https://github.com/openjdk/jdk/commit/996688ae541d9fc9f88268f1d090af409c5ee65a
https://github.com/openjdk/jdk/compare/master...stefank:jdk:pull/21191

My main motivation for the suggestions is to get rid of the addition of the if / else block in the `free_page[s]` functions. The addition of them lead to code duplication, non-const initialization of the local variable, a disproportionate amount of lines compared to the rest of the code, which all lead to readability taking a hit, IMHO.

**Comment by kstefanj** [comment]
Me and StefanK discussed his proposal and did some additional changes with regards to naming and structure.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Review by jsikstro — APPROVED** [review]

**Review by fisk — APPROVED** [review]
Looks good.

**Comment by kstefanj** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
