### PR TITLE
8266561: Remove Compile::_save_argument_registers

### PR DESCRIPTION
**Pull request by cl4es**
Compile::_save_argument_registers is always false, so I suggest removing it.

It was used in the past for certain stubs, but the last use appears to have been removed with [JDK-8136406](https://bugs.openjdk.java.net/browse/JDK-8136406)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266561](https://bugs.openjdk.java.net/browse/JDK-8266561): Remove Compile::_save_argument_registers

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3884/head:pull/3884` \
`$ git checkout pull/3884`

Update a local copy of the PR: \
`$ git checkout pull/3884` \
`$ git pull https://git.openjdk.java.net/jdk pull/3884/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3884`

View PR using the GUI difftool: \
`$ git pr show -t 3884`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3884.diff">https://git.openjdk.java.net/jdk/pull/3884.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
These are C2 changes and they look fine.

I thought we may do more clean up but C1 may pass must_gc_arguments to `RuntimeStub::new_runtime_stub()`.

**Comment by cl4es** [comment]
> These are C2 changes and they look fine.

Thanks!

> I thought we may do more clean up but C1 may pass must_gc_arguments to `RuntimeStub::new_runtime_stub()`.

Yes, I started pulling at that thread, but it wasn't obvious if it would unravel nicely. And even if so it seemed more appropriate for a follow-up.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by cl4es** [comment]
@vnkozlov @TobiHartmann - thanks for reviewing!

/integrate

**Pull request closed without merging**
