### PR TITLE
8284167: Make internal javac exceptions stackless

### PR DESCRIPTION
**Pull request by shipilev**
async-profiling of SPECjvm2008 benchmarks (heavily modified to run with newer JDKs) shows that a considerable time is spent creating and throwing internal exceptions like:
  - `Infer$InferenceException`
  - `Resolve$InapplicableMethodException`
  - `Types$FunctionDescriptorLookupError`

These exceptions do not seem to leak outside javac and are only used to deliver asynchronous errors and related diagnostics. Stack trace does not seem relevant there and can be omitted. 

This patch improves `Compiler.compiler` and `Compiler.sunflow` benchmarks for about +4.3%. There is no measurable impact on JDK build times.

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug `tier2`
 - [x] Linux x86_64 fastdebug `tier3`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284167](https://bugs.openjdk.java.net/browse/JDK-8284167): Make internal javac exceptions stackless

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8072/head:pull/8072` \
`$ git checkout pull/8072`

Update a local copy of the PR: \
`$ git checkout pull/8072` \
`$ git pull https://git.openjdk.java.net/jdk pull/8072/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8072`

View PR using the GUI difftool: \
`$ git pr show -t 8072`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8072.diff">https://git.openjdk.java.net/jdk/pull/8072.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Nice idea - for one of them (NodeNotFoundException) a singleton will probably do, since we're not using that exception contents in any meaningful way.

**Comment by mcimadamore** [comment]
Also applying same treatment to Infer.InferenceException might lead to improvements.

**Comment by shipilev** [comment]
> Also applying same treatment to Infer.InferenceException might lead to improvements.

`InferenceException extends InapplicableMethodException`, which is handled by this patch already.

**Review by mcimadamore — APPROVED** [review]
LGTM

**Comment by shipilev** [comment]
Any more reviews? I'll integrate today, if there are no complaints.

**Pull request closed without merging**
