### PR TITLE
8275509: ModuleDescriptor.hashCode isn't reproducible across builds

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review for this change which fixes the issue reported in https://bugs.openjdk.java.net/browse/JDK-8275509?

The `ModuleDescriptor.hashCode()` method uses the hash code of its various components to compute the final hash code. While doing so it ends up calling hashCode() on (collection of) various `enum` types. Since the hashCode() of enum types is generated from a call to `java.lang.Object.hashCode()`, their value isn't guaranteed to stay the same across multiple JVM runs.

The commit here proposes to use the ordinal of the enum as the hash code. As Alan notes in the mailing list discussion, any changes to the ordinal of the enum (either due to addition of new value, removal of a value or just reordering existing values, all of which I think will be rare in these specific enum types) isn't expected to produce the same hash code across those changed runtimes and that should be okay. 

The rest of the ModuleDescriptor.hashCode() has been reviewed too and apart from calls to the enum types hashCode(), rest of the calls in that implementation, either directly or indirectly end up as calls on `java.lang.String.hashCode()` and as such aren't expected to cause non-deterministic values.

A new jtreg test has been added to reproduce this issue and verify the fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275509](https://bugs.openjdk.java.net/browse/JDK-8275509): ModuleDescriptor.hashCode isn't reproducible across builds

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6078/head:pull/6078` \
`$ git checkout pull/6078`

Update a local copy of the PR: \
`$ git checkout pull/6078` \
`$ git pull https://git.openjdk.java.net/jdk pull/6078/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6078`

View PR using the GUI difftool: \
`$ git pr show -t 6078`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6078.diff">https://git.openjdk.java.net/jdk/pull/6078.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
> Do you mean the jtreg `driver` style this test is using? I used it because it was necessary to compare output (the hashCode value) between multiple JVM runs. I use the `driver` along with the `ProcessBuilder` to capture the output between multiple JVM runs and compare those.

No, I mean the test needs cleanup so it can easily be maintained. For starters I think the main method can take a parameter to indicate its the child process. HashCodeChecker.main becomes a method in ModuleDescriptorHashCodeTest.  You'll see several examples of this in the test suite.

assertTestPrerequisite tests if the modules requires has modifiers so let's rename the method to make this clearer. Also "requirements" should be "requires". 

fromBootLayer returns the "java.sql" module so should be renamed to something clearer, or changed to take a parameter with the module name.  The dependency on the java.sql module means the test needs "@modules java.sql"

Style wise, the over-use of the "final" modifier is annoying, most/all of them aren't needed.

**Comment by AlanBateman** [comment]
Thanks for the update to the test. Instead of launching 50 VMs, what would you think about tossing the use of ProcessTools and just changing the test description so that the test runs twice, once with the default, the second with CDS disabled, as, in:

@run ModuleDescriptorHashCodeTest
@run main/othervm -Xshare:off ModuleDescriptorHashCodeTest

The tests are run by many people every day, they are run continuously on all platforms in several CI systems. So I think you'll get much more variability that way rather than launching 50 VMs.

I also feel like the test could be re-written to test the module descriptors of all modules in the boot layer. That would avoid having a dependency on the java.sql module as it would be testing every module.

**Comment by AlanBateman** [comment]
> So I decided to stick with using the ordinal modifiers in the hashCode() computation. However, I'm not an expert on the performance aspects of the Collections and how much using the modifiers for hashCode() will improve the performance in this case. Perhaps that's what you meant by it not giving a good (enough) spread? If so, do let me know and I'll go ahead and update the PR to remove using the modifiers in the hashCode() computation and also update the javadoc of each of those hashCode() methods which state that the modifiers are used in the hashCode() computation.

Okay, but we may have to re-visit this some time because summing the ordinals won't give a good spread, e.g. STATIC+SYNTHETIC will give the same value as TRANSITIVE. This is why I was saying it would be nearly the same to just leave them out. So let's go with it for now.

Thanks for the update to the test. The assertNotSame to check that they aren't the same instance looks a bit odd but at least you have a comment to explain it. I guess we should add an assertEquals to check that the 2 descriptors are equals too. Then I think we are done.

**Comment by jaikiran** [comment]
> > So I decided to stick with using the ordinal modifiers in the hashCode() computation. However, I'm not an expert on the performance aspects of the Collections and how much using the modifiers for hashCode() will improve the performance in this case. Perhaps that's what you meant by it not giving a good (enough) spread? If so, do let me know and I'll go ahead and update the PR to remove using the modifiers in the hashCode() computation and also update the javadoc of each of those hashCode() methods which state that the modifiers are used in the hashCode() computation.
> 
> Okay, but we may have to re-visit this some time because summing the ordinals won't give a good spread, e.g. STATIC+SYNTHETIC will give the same value as TRANSITIVE. This is why I was saying it would be nearly the same to just leave them out.

That's a good point and thank you for explaining that part. So to address that, how about not leaving them out, but instead of using `Enum#ordinal()` for the hashCode generation, we use `Enum#name()` which would translate to a `String#hashCode()`. Something like:

```
private static int modsHashCode(Iterable<? extends Enum<?>> enums) {
        int h = 0;
        for (Enum<?> e : enums) {
            h = h * 43 + Objects.hashCode(e.name());
        }
        return h;
    }
```
That way the hashCode isn't dependent on the Object identity (which is what the original issue was), is still reproducible across JVM runs and at the same tie should provide a good spread for examples like the one you noted. Furthermore, unlike the usage of `ordinal` where any reordering of the enum values would have changed the hashCode value (which was OK), this usage of `name()` doesn't exhibit that nature (which again should be OK).

I've updated the PR to use this construct. The test continues to pass. Let me know if this looks fine or if you prefer doing it differently.

**Comment by AlanBateman** [comment]
> That's a good point and thank you for explaining that part. So to address that, how about not leaving them out, but instead of using `Enum#ordinal()` for the hashCode generation, we use `Enum#name()` which would translate to a `String#hashCode()`. 

Moving to the hashCode of the names of the values is good.

**Review by AlanBateman — APPROVED** [review]
One final thought on this is whether we should remove the tools/jlink/JLinkReproducibleXXX tests from the exclude list.

**Review by magicus — APPROVED** [review]

**Comment by jaikiran** [comment]
> One final thought on this is whether we should remove the tools/jlink/JLinkReproducibleXXX tests from the exclude list.

Yes, I'm working on it in a separate PR.

**Comment by jaikiran** [comment]
FWIW, the GitHub Actions job failure for Windows is due to an unrelated reason:

```
2021-11-04T05:22:48.5273779Z /usr/bin/bash: line 1:  1174 Segmentation fault      (core dumped) /usr/bin/make -s -r -R -I /cygdrive/d/a/jdk/jdk/jdk/make/common SPEC=/cygdrive/d/a/jdk/jdk/jdk/build/windows-x64/spec.gmk MAKE_LOG_FLAGS="-s" -f ModuleWrapper.gmk -I /cygdrive/d/a/jdk/jdk/jdk/make/common/modules -I/cygdrive/d/a/jdk/jdk/jdk/make/modules/java.base MODULE=java.base MAKEFILE_PREFIX=Copy
2021-11-04T05:22:48.5304517Z make[2]: *** [make/Main.gmk:157: java.base-copy] Error 139
2021-11-04T05:22:48.5305851Z make[2]: *** Waiting for unfinished jobs....
2021-11-04T05:22:48.8158343Z Compiling 12 properties into resource bundles for jdk.jdeps
2021-11-04T05:22:49.2707959Z 
2021-11-04T05:22:49.2712144Z ERROR: Build failed for target 'default (product-bundles test-bundles)' in configuration 'windows-x64' (exit code 2) 
2021-11-04T05:22:49.8818435Z 
2021-11-04T05:22:49.8823500Z No indication of failed target found.
2021-11-04T05:22:49.8845292Z Hint: Try searching the build log for '] Error'.
2021-11-04T05:22:49.9156326Z Hint: See doc/building.html#troubleshooting for assistance.
2021-11-04T05:22:49.9156822Z 
2021-11-04T05:22:49.9206739Z make[1]: *** [/cygdrive/d/a/jdk/jdk/jdk/make/Init.gmk:315: main] Error 2
2021-11-04T05:22:49.9249924Z make: *** [/cygdrive/d/a/jdk/jdk/jdk/make/Init.gmk:186: default] Error 2
2021-11-04T05:22:50.0054100Z ##[error]Process completed with exit code 1.
```
Going ahead with the merge of this PR.

**Comment by jaikiran** [comment]
Thank you Alan and Magnus for the inputs and the reviews.

**Pull request closed without merging**
