### PR TITLE
8293107: GHA: Bump to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by shipilev**
WIP, depends on #10083.

At this point, we can switch to Ubuntu 22.04 as the base for GHA runners. GHA would switch `ubuntu-latest` soon:
 https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

This gives us several benefits:
  - we can expect that the availability of 20.04 runners would decline in future, while 22.04 enabled runners would become more available;
  - toolchains would now include GCC 11;
  - RISC-V cross-builds would become available; 

Additional testing:
 - [ ] GHA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293107](https://bugs.openjdk.org/browse/JDK-8293107): GHA: Bump to Ubuntu 22.04

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [072b4939](https://git.openjdk.org/jdk/pull/10084/files/072b4939ee1fdc33c76b7daad7832940912708fb)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10084/head:pull/10084` \
`$ git checkout pull/10084`

Update a local copy of the PR: \
`$ git checkout pull/10084` \
`$ git pull https://git.openjdk.org/jdk pull/10084/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10084`

View PR using the GUI difftool: \
`$ git pr show -t 10084`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10084.diff">https://git.openjdk.org/jdk/pull/10084.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
I realized some ports still not able to build cleanly with GCC 11, so I retracted that bit from this PR, leaving only the update to Ubuntu version. We can switch to GCC 11 separately.

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
There were a failure in the GHA build, [runtime/ErrorHandling/TestDwarf](https://github.com/shipilev/jdk/actions/runs/2962910324#user-content-runtime_errorhandling_testdwarf). I assume this is not caused by this change..?

**Comment by shipilev** [comment]
> @shipilev Nevermind, I just noticed #10099. :)

Turns out, #10099 only fixes it for 20.04. For 22.04, #10113 fixes it... Argh. Merging and re-testing.

**Comment by shipilev** [comment]
> > @shipilev Nevermind, I just noticed #10099. :)
> 
> Turns out, #10099 only fixes it for 20.04. For 22.04, #10113 fixes it... Argh. Merging and re-testing.

It is finally clean! 

I'll wait for more reviews, I think.

**Comment by magicus** [comment]
You can integrate with just my review. I don't think there's anyone else that really cares about GHA left to review. 😉

**Comment by shipilev** [comment]
All right then!

/integrate

**Pull request closed without merging**
