### PR TITLE
8294406: Test runtime/handshake/HandshakeDirectTest.java failed: JVMTI_ERROR_WRONG_PHASE

### PR DESCRIPTION
**Pull request by lmesnik**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294406](https://bugs.openjdk.org/browse/JDK-8294406): Test runtime/handshake/HandshakeDirectTest.java failed: JVMTI_ERROR_WRONG_PHASE

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10502/head:pull/10502` \
`$ git checkout pull/10502`

Update a local copy of the PR: \
`$ git checkout pull/10502` \
`$ git pull https://git.openjdk.org/jdk pull/10502/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10502`

View PR using the GUI difftool: \
`$ git pr show -t 10502`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10502.diff">https://git.openjdk.org/jdk/pull/10502.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Why is `JVMTI_ERROR_WRONG_PHASE` a valid result here?

**Comment by sspitsyn** [comment]
> Why is `JVMTI_ERROR_WRONG_PHASE` a valid result here?

I think, it is because the testing `suspendResumeThread` tread is a daemon thread.
I'm not sure why it was set to be a daemon thread though.

**Comment by robehn** [comment]
The reason for it to be a daemon is that this thread should try to suspend/resume when we are terminating, thus trying to hit those rare exit parts where we do thread exits with a pending suspend.

**Comment by sspitsyn** [comment]
Thanks, Robbin. I see the point.

**Comment by dholmes-ora** [comment]
So what is the "wrong phase" that we are in? I don't like just accepting any wrong phase because only termination phases are expected to be encountered not startup phases.

**Comment by sspitsyn** [comment]
The wrong phase that we are in can be only JVMTI_PHASE_DEAD. It can't be any phase before JVMTI_PHASE_LIVE because it happens when we execute a java code. The WRONG_PHASE error code has to be always expected by any tests that use JVM TI.

**Comment by dholmes-ora** [comment]
Okay so because this is a daemon thread it can be hit up to when the final termination safepoint is initiated, and this is after the VM is marked as "dead". Thanks.

**Review by dholmes-ora — APPROVED** [review]

**Pull request closed without merging**
