### PR TITLE
8286182: [BACKOUT] x86: Handle integral division overflow during parsing

### PR DESCRIPTION
**Pull request by merykitty**
This patch backs out the changes made by [JDK-8285390](https://bugs.openjdk.java.net/browse/JDK-8285390) and [JDK-8284742](https://bugs.openjdk.java.net/browse/JDK-8284742) since there are failures due to div nodes floating above their validity checks.

Thanks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8286182](https://bugs.openjdk.java.net/browse/JDK-8286182): [BACKOUT] x86: Handle integral division overflow during parsing
 * [JDK-8287035](https://bugs.openjdk.java.net/browse/JDK-8287035): [BACKOUT] PPC64: Handle integral division overflow during parsing

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to [bf963e6b](https://git.openjdk.java.net/jdk/pull/8774/files/bf963e6b4565e31d014d6698a55c96747d5f004e)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [bf963e6b](https://git.openjdk.java.net/jdk/pull/8774/files/bf963e6b4565e31d014d6698a55c96747d5f004e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8774/head:pull/8774` \
`$ git checkout pull/8774`

Update a local copy of the PR: \
`$ git checkout pull/8774` \
`$ git pull https://git.openjdk.java.net/jdk pull/8774/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8774`

View PR using the GUI difftool: \
`$ git pr show -t 8774`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8774.diff">https://git.openjdk.java.net/jdk/pull/8774.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too but the backout should adhere to the process defined here: https://openjdk.java.net/guide/#backing-out-a-change

I would suggest "Alternative 2" of 3.

**Review by chhagedorn — CHANGES_REQUESTED** [review]
Backout looks good except that you did not remove the test `test/hotspot/jtreg/compiler/integerArithmetic/TestDivision.java` which you've added here:
https://github.com/openjdk/jdk/commit/b4a85cdae14eee895a0de2f26a2ffdd62b72bebc#diff-4daba70b215edefe9fd70b24f1e1052a51effdd48a1809e2ce5a06bc21a755c5

It's just a correctness test, so it would be okay to leave it in. But I guess it's better to backout everything.

**Comment by merykitty** [comment]
I have backed out also the division test and created JBS issues as instructed in the developer guide. Hope I have done it correctly. Thanks a lot for your reviews.
/integrate

**Pull request closed without merging**
