### PR TITLE
8303068: Memory leak in DwarfFile::LineNumberProgram::run_line_number_program

### PR DESCRIPTION
**Pull request by dholmes-ora**
After allocating:
```
_state = new (std::nothrow) LineNumberProgramState(_header);
```
we need to `delete _state` before returning.

Testing: tiers 1-3

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303068](https://bugs.openjdk.org/browse/JDK-8303068): Memory leak in DwarfFile::LineNumberProgram::run_line_number_program

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - Committer)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12738/head:pull/12738` \
`$ git checkout pull/12738`

Update a local copy of the PR: \
`$ git checkout pull/12738` \
`$ git pull https://git.openjdk.org/jdk pull/12738/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12738`

View PR using the GUI difftool: \
`$ git pr show -t 12738`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12738.diff">https://git.openjdk.org/jdk/pull/12738.diff</a>

</details>

### CODE REVIEW

**Comment by jdksjolen** [comment]
Hi David,

`LineNumberProgram` is used in `elFile.cpp:704`, is stack allocated and has exactly one entry point: `find_filename_and_line_number`. `LineNumberProgramState` is used only internally by `LineNumberProgramState`.

`LineNumberProgram`'s current size is 120 bytes. The size of `LineNumberProgramState` is 48 bytes.

Can't we change the type of `_state` to `LineNumberProgramState`? This bloats the size up to 168 bytes, but we no longer have to care about tracking the resource or have another heap allocation call. Yes, we have to change `->` to `.`, so the change is larger, but it's conceptually simpler.

FWIW, `_state` is also always re-allocated, so I don't see why we even need the `reset()` method on it, but that's a future RFE.

**Comment by dholmes-ora** [comment]
> Can't we change the type of _state to LineNumberProgramState? 

I think you meant change to `LineNumberProgram` ?

I'm not really familiar with this code and just want to fix the memory leak that was detected. Any redesign of the code really needs to be a separate RFE.

**Comment by jcking** [comment]
> > Can't we change the type of _state to LineNumberProgramState?
> 
> I think you meant change to `LineNumberProgram` ?
> 
> I'm not really familiar with this code and just want to fix the memory leak that was detected. Any redesign of the code really needs to be a separate RFE.

I agree. Let's take the path of least resistance to removing the leak and follow up with simplification in another PR.

**Review by jdksjolen — APPROVED** [review]
OK, that's fair to me, thanks for the changes.

**Comment by jdksjolen** [comment]
```
 #else
   DWARF_LOG_DEBUG("Address:              Line:    Column:   File:");
 #endif
-  _state = new (std::nothrow) LineNumberProgramState(_header);
+  LineNumberProgramState state{_header};
+  _state = &state;
   if (_state == nullptr) {
     DWARF_LOG_ERROR("Failed to create new LineNumberProgramState object");
     return false;
```

Isn't this equivalent?

**Comment by jcking** [comment]
> ```
>  #else
>    DWARF_LOG_DEBUG("Address:              Line:    Column:   File:");
>  #endif
> -  _state = new (std::nothrow) LineNumberProgramState(_header);
> +  LineNumberProgramState state{_header};
> +  _state = &state;
>    if (_state == nullptr) {
>      DWARF_LOG_ERROR("Failed to create new LineNumberProgramState object");
>      return false;
> ```
> 
> Isn't this equivalent?

You'd have to clear _state before returning from the function for safety.

**Comment by dholmes-ora** [comment]
I'm going to have to look at this in much more detail. I thought `_state` was just locally used but it isn't. So I can't just delete it in the non-error cases, and probably need to reset to `nullptr` as well. That also prevents using the trick @jdksjolen  suggested with the stack allocated instance.

**Comment by dholmes-ora** [comment]
Okay I just pushed a much simpler, cleaner and more robust fix, by adding a destructor for `LineNumberProgram`.

**Review by jdksjolen — APPROVED** [review]
Re-approving

**Review by tschatzl — APPROVED** [review]

**Pull request closed without merging**
