### PR TITLE
8303509: Socket setTrafficClass does not work for IPv4 connections when IPv6 enabled

### PR DESCRIPTION
**Pull request by JackyWoo**
### Issue
This pr try to fix [JDK-8303509](https://bugs.openjdk.org/browse/JDK-8303509): Socket setTrafficClass does not work for IPv4 connections when IPv6 enabled.

### Change Log
When setting traffic class with IPv6 enabled, also set to IPv4 family.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303509](https://bugs.openjdk.org/browse/JDK-8303509): Socket setTrafficClass does not work for IPv4 connections when IPv6 enabled

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12852/head:pull/12852` \
`$ git checkout pull/12852`

Update a local copy of the PR: \
`$ git checkout pull/12852` \
`$ git pull https://git.openjdk.org/jdk pull/12852/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12852`

View PR using the GUI difftool: \
`$ git pr show -t 12852`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12852.diff">https://git.openjdk.org/jdk/pull/12852.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
You will need to change the title of your PR, which you might as well do while waiting for your OCA to be confirmed. First, add a space after the "8303509:". Second, change the rest of it to _exactly_ match the title of the bug, meaning do not use the word "fix" in the title, nor use back-ticks for code style. Putting that all together, the title should be exactly the following:

8303509: Socket setTrafficClass does not work for IPv4 connections when IPv6 enabled

**Comment by AlanBateman** [comment]
[PR 12872](https://github.com/openjdk/jdk/pull/12872) is already under review for this issue.

**Comment by JackyWoo** [comment]
@AlanBateman I encountered the problem in my production environment, so I reported the bug.  

Thanks for your fix. And I will close my PR.

**Comment by JackyWoo** [comment]
@kevinrushforth Thanks for you help to my first open JDK PR.

**Pull request closed without merging**
