### PR TITLE
8267468: Rename refill waster counters in ThreadLocalAllocBuffer

### PR DESCRIPTION
**Pull request by albertnetymk**
Followup of https://bugs.openjdk.java.net/browse/JDK-8234532 (https://github.com/openjdk/jdk/pull/3756), dropping the "slow" segment in various counter names.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267468](https://bugs.openjdk.java.net/browse/JDK-8267468): Rename refill waster counters in ThreadLocalAllocBuffer

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4146/head:pull/4146` \
`$ git checkout pull/4146`

Update a local copy of the PR: \
`$ git checkout pull/4146` \
`$ git pull https://git.openjdk.java.net/jdk pull/4146/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4146`

View PR using the GUI difftool: \
`$ git pr show -t 4146`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4146.diff">https://git.openjdk.java.net/jdk/pull/4146.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by sspitsyn — APPROVED** [review]
Hi Albert,
Looks good.
Thanks,
Serguei

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
