### PR TITLE
8269574: C2: Avoid redundant uncommon traps in GraphKit::builtin_throw() for JVMTI exception events

### PR DESCRIPTION
**Pull request by reinrich**
This change moves the first uncommon trap in `GraphKit::builtin_throw()` to the block where it is actually needed because it has a return statement.

Other paths reach the second uncommon trap at the end of `GraphKit::builtin_throw()`. On these paths the first UCT is not needed.

The change improves performance if the VM can post exceptions to JVMTI agents.
E.g. I found that the change improves the score for the compiler.compiler benchmark of SPECjvm2008 by 4% if the JDWP agent is loaded (see attachment in JBS).

Note that with the change we can trap with `Deoptimization::Action_maybe_recompile` if we don't throw a preallocated exception where before we would have trapped with `Deoptimization::Action_none` if it was for posting the exception to JVMTI. I'd think this is preferable.

The fix passed our CI testing: JCK and JTREG, also in Xcomp mode, SPECjvm2008, SPECjbb2015, Renaissance Suite,
SAP specific tests with fastdebug and release builds on all platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269574](https://bugs.openjdk.java.net/browse/JDK-8269574): C2: Avoid redundant uncommon traps in GraphKit::builtin_throw() for JVMTI exception events

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4623/head:pull/4623` \
`$ git checkout pull/4623`

Update a local copy of the PR: \
`$ git checkout pull/4623` \
`$ git pull https://git.openjdk.java.net/jdk pull/4623/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4623`

View PR using the GUI difftool: \
`$ git pr show -t 4623`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4623.diff">https://git.openjdk.java.net/jdk/pull/4623.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good. Let me run some tests before push.

**Comment by vnkozlov** [comment]
tier1-3 testing passed clean.

You need second review.

**Comment by reinrich** [comment]
> 
> 
> tier1-3 testing passed clean.
> 
> You need second review.

Thank you for reviewing and testing. I'll wait for another review.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by reinrich** [comment]
> 
> 
> Looks good to me.

Thanks!

**Review by neliasso — APPROVED** [review]
Looks good.

**Comment by reinrich** [comment]
> 
> 
> Looks good.

Thanks Nils!

**Pull request closed without merging**
