### PR TITLE
8332066: AArch64: Math test failures since JDK-8331558

### PR DESCRIPTION
**Pull request by theRealAph**
Revert "8331558: AArch64: optimize integer remainder"
This reverts commit dab92c51c70767abcda3b1a91dd7d1a9b40290c1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332066](https://bugs.openjdk.org/browse/JDK-8332066): AArch64: Math test failures since JDK-8331558 (**Bug** - P1)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19177/head:pull/19177` \
`$ git checkout pull/19177`

Update a local copy of the PR: \
`$ git checkout pull/19177` \
`$ git pull https://git.openjdk.org/jdk.git pull/19177/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19177`

View PR using the GUI difftool: \
`$ git pr show -t 19177`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19177.diff">https://git.openjdk.org/jdk/pull/19177.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19177#issuecomment-2104593430)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good and trivial.

**Comment by dholmes-ora** [comment]
If this was a backout of the earlier change then it should have followed the official process for backing out a change:
https://openjdk.org/guide/#backing-out-a-change

**Comment by theRealAph** [comment]
> If this was a backout of the earlier change then it should have followed the official process for backing out a change: https://openjdk.org/guide/#backing-out-a-change

What does that mean in this case? There was an issue raised about the regression, [JDK-8332066](https://bugs.openjdk.org/browse/JDK-8332066), but the process doesn't mention an issue of this kind. What should happen to it? Should an _additional_ backout issue have been created? Or should JDK-8332066 have been renamed?

**Comment by dcubed-ojdk** [comment]
[JDK-8332066](https://bugs.openjdk.org/browse/JDK-8332066) should have been renamed to:

    [BACKOUT] AArch64: optimize integer remainder

or

    [BACKOUT] JDK-8331558 AArch64: optimize integer remainder

I believe that this scenario is covered by:

```
Alternative 2 - an investigation issue was created (I), and during the investigation backing out the change is identified as the best solution.

    Use the investigation issue (I) for the backout.
    Change summary of (I) to the same as (O) and prefix with [BACKOUT].
    Move and change type of (I) to become a sub-task of (R).
```

**Comment by theRealAph** [comment]
> [JDK-8332066](https://bugs.openjdk.org/browse/JDK-8332066) should have been renamed to:

Mmm, but the core problems are that this is a manual process, it's different from the "normal" GitHub backouts and, worst of all, can't be corrected if anyone messes up the manual process.

**Pull request closed without merging**
