### PR TITLE
8316427: Duplicated code for {obj,type}ArrayKlass::array_klass

### PR DESCRIPTION
**Pull request by coleenp**
Please review this trivial change to move duplicated array_klass().  Tested with tier1 on Oracle supported platforms.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316427](https://bugs.openjdk.org/browse/JDK-8316427): Duplicated code for {obj,type}ArrayKlass::array_klass (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15791/head:pull/15791` \
`$ git checkout pull/15791`

Update a local copy of the PR: \
`$ git checkout pull/15791` \
`$ git pull https://git.openjdk.org/jdk.git pull/15791/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15791`

View PR using the GUI difftool: \
`$ git pr show -t 15791`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15791.diff">https://git.openjdk.org/jdk/pull/15791.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15791#issuecomment-1723930898)

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
I have to wonder if it is in fact a bug that  `TypeArrayKlass::array_klass` invokes `ObjArrayKlass::allocate_objArray_klass` when that creates the wrong type of array???

**Comment by adinn** [comment]
Why is it the wrong type?

If the type array is, say, int[] then its array class is int[][] which is an array of int[] i.e. of objects.

This patch looks fine to me.

**Comment by coleenp** [comment]
What Andrew said.  An array of int[][] is an array of objects, so an ObjArrayKlass.  The reason that array_klass can't return an ObjArrayKlass instead of ArrayKlass, is that a single dimension primitive type array returns TypeArrayKlass.
Thanks Andrew.

**Review by adinn — APPROVED** [review]

**Comment by dholmes-ora** [comment]
It creates an `objArrayKlass` not a `typeArrayKlass`. I guess I don't understand what these two things each represent.

**Comment by dholmes-ora** [comment]
Okay `typeArrayKlass` presents an array of primitive type. `objArrayKlass` represents an array of reference type. For a multi-dimensional array we are dealing with an array of object references (each of which is an array of some other type). Got it.

**Review by dholmes-ora — APPROVED** [review]
Okay - refactoring looks good.

Thanks.

**Pull request closed without merging**
