### PR TITLE
8266498: Make debug ps() call print_stack

### PR DESCRIPTION
**Pull request by coleenp**
Fix ps() call print_stack.  Tested manually and with fastdebug and debug.  Also removed hsfind() because find() is the same thing and nobody's using dbx anymore (and the overload that made me add it might be long gone).
Tested with tier1 sanity.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266498](https://bugs.openjdk.java.net/browse/JDK-8266498): Make debug ps() call print_stack

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3861/head:pull/3861` \
`$ git checkout pull/3861`

Update a local copy of the PR: \
`$ git checkout pull/3861` \
`$ git pull https://git.openjdk.java.net/jdk pull/3861/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3861`

View PR using the GUI difftool: \
`$ git pr show -t 3861`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3861.diff">https://git.openjdk.java.net/jdk/pull/3861.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Looks fine to me.

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Comment by coleenp** [comment]
Thanks Lois and Thomas.

**Pull request closed without merging**
