### PR TITLE
8282583: Update BCEL md to include the copyright notice

### PR DESCRIPTION
**Pull request by JoeWang-Java**
Update BCEL md to include the copyright notice.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282583](https://bugs.openjdk.java.net/browse/JDK-8282583): Update BCEL md to include the copyright notice

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7681/head:pull/7681` \
`$ git checkout pull/7681`

Update a local copy of the PR: \
`$ git checkout pull/7681` \
`$ git pull https://git.openjdk.java.net/jdk pull/7681/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7681`

View PR using the GUI difftool: \
`$ git pr show -t 7681`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7681.diff">https://git.openjdk.java.net/jdk/pull/7681.diff</a>

</details>

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]
Looks fine.  I assume the 2020 vs 2022 is intentional?

**Review by irisclark — APPROVED** [review]
Confirm 2020, not 2022.  Otherwise, looks good.

**Comment by JoeWang-Java** [comment]
Yes, it's 2020. The latest release, 6.5.0, was released in 2020. The text comes from the NOTICE.txt file in the BCEL 6.5.0 release.

**Comment by LanceAndersen** [comment]
> Yes, it's 2020. The latest release, 6.5.0, was released in 2020. The text comes from the NOTICE.txt file in the BCEL 6.5.0 release.

Thank you for the confirmation Joe!

**Comment by JoeWang-Java** [comment]
> > Yes, it's 2020. The latest release, 6.5.0, was released in 2020. The text comes from the NOTICE.txt file in the BCEL 6.5.0 release.
> 
> Thank you for the confirmation Joe!

Thanks Lance, and Iris!

**Review by naotoj — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
