### PR TITLE
8345984: Remove redundant checkXXX methods from java.management Util class

### PR DESCRIPTION
**Pull request by kevinjwalls**
A post-SecurityManager removal cleanup task, to remove checkAccess(), checkMonitorAccess() and checkControlAccess() from src/java.management/share/classes/sun/management/Util.java (methods are already no-ops).

While here, there are a few imports of Util that are unnecessary.

No changes to the module visibility/exports.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345984](https://bugs.openjdk.org/browse/JDK-8345984): Remove redundant checkXXX methods from java.management Util class (**Enhancement** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22680/head:pull/22680` \
`$ git checkout pull/22680`

Update a local copy of the PR: \
`$ git checkout pull/22680` \
`$ git pull https://git.openjdk.org/jdk.git pull/22680/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22680`

View PR using the GUI difftool: \
`$ git pr show -t 22680`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22680.diff">https://git.openjdk.org/jdk/pull/22680.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22680#issuecomment-2535851354)
</details>

### CODE REVIEW

**Comment by kevinjwalls** [comment]
> This looks okay, you might have to bump the copyright on a few files.

Thanks, yes I think the GcInfoBuilder.java file, will update.

**Review by AlanBateman — APPROVED** [review]

**Review by mlchung — APPROVED** [review]
LGTM

**Comment by kevinjwalls** [comment]
Thanks Alan and Mandy!

**Review by plummercj — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]

**Pull request closed without merging**
