### PR TITLE
JDK-8283415: Update java.lang.ref to use sealed classes

### PR DESCRIPTION
**Pull request by jddarcy**
Another refactoring to use sealed classes where possible, this time in the java.lang.ref package.

Copyright dates will be updated, if needed, before a push.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8283415](https://bugs.openjdk.java.net/browse/JDK-8283415): Update java.lang.ref to use sealed classes
 * [JDK-8283428](https://bugs.openjdk.java.net/browse/JDK-8283428): Update java.lang.ref to use sealed classes (**CSR**)

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 8dc83e5f17d74975f157d350dba35a3c7d00d522
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 8dc83e5f17d74975f157d350dba35a3c7d00d522

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7874/head:pull/7874` \
`$ git checkout pull/7874`

Update a local copy of the PR: \
`$ git checkout pull/7874` \
`$ git pull https://git.openjdk.java.net/jdk pull/7874/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7874`

View PR using the GUI difftool: \
`$ git pr show -t 7874`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7874.diff">https://git.openjdk.java.net/jdk/pull/7874.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by AlanBateman — APPROVED** [review]

**Comment by jddarcy** [comment]
PS @AlanBateman and @kimbarrett , please also review the CSR https://bugs.openjdk.java.net/browse/JDK-8283428
Thanks.

**Pull request closed without merging**
