### PR TITLE
8326947: Minimize MakeBase.gmk

### PR DESCRIPTION
**Pull request by magicus**
This is part of a general "spring cleaning" of the build system, addressing old code that has bit-rotted, been subject to lava flow, or just had bad or smelly code that we've never gotten around to fix.

This particular patch tries to make MakeBase truly minimal; only including the core parts of the build system that all makefiles will need. This is now limited to essential functionality for named parameter functions, variable dependency, tool execution, logging and fixpath functionality. MakeBase still includes Utils.gmk and FileUtils.gmk, and thus "provides" this functionality as well. Separating these out as well will be the subject of a future patch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326947](https://bugs.openjdk.org/browse/JDK-8326947): Minimize MakeBase.gmk (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [8c25c87c](https://git.openjdk.org/jdk/pull/18041/files/8c25c87cb41e3620352d2075cb19ce21ffed4728)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18041/head:pull/18041` \
`$ git checkout pull/18041`

Update a local copy of the PR: \
`$ git checkout pull/18041` \
`$ git pull https://git.openjdk.org/jdk.git pull/18041/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18041`

View PR using the GUI difftool: \
`$ git pr show -t 18041`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18041.diff">https://git.openjdk.org/jdk/pull/18041.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18041#issuecomment-1968789451)

### CODE REVIEW

**Comment by magicus** [comment]
I have verified using `COMPARE_BUILD` on windows-x64, linux-x64, linux-aarch64, macosx-x64 and macosx-aarch64 that there are no differences in the resulting build.

**Review by erikj79 — COMMENTED** [review]
The distinction between Utils.gmk and BaseUtils.gmk seems a bit arbitrary at a glance, especially since both are still included from MakeBase.gmk. How would you know in which file to add a new macro?

**Comment by magicus** [comment]
The distinction was that BaseUtils.gmk are needed for MakeBase.gmk, Utils.gmk and FileUtils.gmk, but these three are not dependent on anything else. My initial goal was to stop having MakeBase.gmk include Utils.gmk as well, but it required a lot of extra includes and I did not want to do that in this PR. (Maybe it is not a good idea at all; I have not yet really decided).

I agree that the split seems a bit arbitrary. Maybe it was a bad idea. Let me ponder it for a while.

**Pull request closed without merging**
