### PR TITLE
8309048: Remove malloc locker test case

### PR DESCRIPTION
**Pull request by lkorinth**
There is a bunch of tests that are used to test critical section/gc locker. One of the test is named malloc. In that test, JNI code is doing a loop of `malloc()` followed `sleep()` followed by a `free()`. There is no JVM lock implementation to be tested on malloc/free. Let us save test time, code complexity and confusion by removing this test. 

(Oracle) hs-tier5 testing passed on x86-64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309048](https://bugs.openjdk.org/browse/JDK-8309048): Remove malloc locker test case

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14201/head:pull/14201` \
`$ git checkout pull/14201`

Update a local copy of the PR: \
`$ git checkout pull/14201` \
`$ git pull https://git.openjdk.org/jdk.git pull/14201/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14201`

View PR using the GUI difftool: \
`$ git pr show -t 14201`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14201.diff">https://git.openjdk.org/jdk/pull/14201.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14201#issuecomment-1567135985)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks fine. I couldn't find anything explaining the history of this test.

Thanks.

**Review by tschatzl — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]

**Comment by lkorinth** [comment]
Thanks David, Coleen and Leonid! I am looking into further cleanups...

**Pull request closed without merging**
