### PR TITLE
8294376: Minimize disabled warnings in java.base

### PR DESCRIPTION
**Pull request by magicus**
After [JDK-8294281](https://bugs.openjdk.org/browse/JDK-8294281), it is now possible to disable warnings for individual files instead for whole libraries. I used this opportunity to go through all disabled warnings in java.base native libraries.

Any warnings that were only triggered in a few files were removed from the library as a whole, and changed to be only disabled for those files.

Some warnings didn't trigger in any file anymore, and could just be removed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294376](https://bugs.openjdk.org/browse/JDK-8294376): Minimize disabled warnings in java.base

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10426/head:pull/10426` \
`$ git checkout pull/10426`

Update a local copy of the PR: \
`$ git checkout pull/10426` \
`$ git pull https://git.openjdk.org/jdk pull/10426/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10426`

View PR using the GUI difftool: \
`$ git pr show -t 10426`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10426.diff">https://git.openjdk.org/jdk/pull/10426.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by shipilev — COMMENTED** [review]
Hold on, I'll test these on various Linux-es.

**Comment by magicus** [comment]
@shipilev Thanks. I will also wait for someone from core-libs to chime in.

**Comment by shipilev** [comment]
> @shipilev Thanks. I will also wait for someone from core-libs to chime in.

GCC 10 in various arches/modes is fine.

**Pull request closed without merging**
