### PR TITLE
8170432: Class java.util.UUID & @Override

### PR DESCRIPTION
**Pull request by Fleshgrinder**
Adds `@Override` annotation to all methods in `java.util.UUID` that implement methods from the implemented interfaces.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (8/8 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test task**
- [Linux x86 (hs/tier1 compiler)](https://github.com/Fleshgrinder/jdk/runs/1460354241)

### Issue
 * [JDK-8170432](https://bugs.openjdk.java.net/browse/JDK-8170432): Class java.util.UUID & @Override

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1463/head:pull/1463`
`$ git checkout pull/1463`

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
Hi,

This looks reasonable to me.

best regards,

-- daniel

**Review by LanceAndersen — APPROVED** [review]
Looks fine.  It appears you need a sponsor so I can do that once you integrate

**Pull request closed without merging**
