### PR TITLE
8327250: assert(!method->is_old()) failed: Should not be installing old methods

### PR DESCRIPTION
**Pull request by coleenp**
When the [JDK-8322630](https://bugs.openjdk.org/browse/JDK-8322630) ICStubs and safepoints were removed, a check to ignore redefined methods was removed (is_old() check), but that check was in the wrong place.  The LinkResolver finds a Method to call through resolution and selection and saves that Method in the returned CallInfo.  The CallInfo object is temporary until the method is stored somewhere "safe", ie somewhere redefinition knows how to replace the method with a new method or deoptimize. At any safepoint, the Method could be redefined, so the CallInfo return should check for old methods and only return the equivalent new method.

This change removes the one check in the interpreter and moves it to the CallInfo accessors.

Tested with the failing test case with options: "-Xcomp -ea -esa -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -XX:TieredStopAtLevel=2", all vmTestBase/nsk/jvmti tests with these options, and ran tiers 1-8.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327250](https://bugs.openjdk.org/browse/JDK-8327250): assert(!method-&gt;is_old()) failed: Should not be installing old methods (**Bug** - P4)

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to [c4161ccf](https://git.openjdk.org/jdk/pull/18719/files/c4161ccf2101edb8920c9d189386d9609abe76b5)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18719/head:pull/18719` \
`$ git checkout pull/18719`

Update a local copy of the PR: \
`$ git checkout pull/18719` \
`$ git pull https://git.openjdk.org/jdk.git pull/18719/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18719`

View PR using the GUI difftool: \
`$ git pr show -t 18719`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18719.diff">https://git.openjdk.org/jdk/pull/18719.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18719#issuecomment-2047470494)

### CODE REVIEW

**Review by fisk — APPROVED** [review]
This looks great. Thanks for fixing this!

**Comment by fisk** [comment]
Looks like there is a missing include for JvmtiExport. I don't need to see the update.

**Review by sspitsyn — APPROVED** [review]
This looks good.
Thank you for fixing it quickly!

**Comment by coleenp** [comment]
Thanks for reviewing, Erik and Serguei, and thanks for diagnosing the problem, Erik.

**Pull request closed without merging**
