### PR TITLE
8333828: Use value javadoc tag in java.lang.{Float, Double}

### PR DESCRIPTION
**Pull request by jddarcy**
Use the value tag to make the javadoc for various format-related constants more informative to readers. Currently the information is available by following the "Constant Field Values" link.

I'll reflow the paragraphs before a push.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333828](https://bugs.openjdk.org/browse/JDK-8333828): Use value javadoc tag in java.lang.{Float, Double} (**Enhancement** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - Author) ⚠️ Review applies to [ea23aaf0](https://git.openjdk.org/jdk/pull/19607/files/ea23aaf06c3ae8961e57d85f9e5095a7dff9784d)
 * [Raffaello Giulietti](https://openjdk.org/census#rgiulietti) (@rgiulietti - **Reviewer**) ⚠️ Review applies to [ea23aaf0](https://git.openjdk.org/jdk/pull/19607/files/ea23aaf06c3ae8961e57d85f9e5095a7dff9784d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19607/head:pull/19607` \
`$ git checkout pull/19607`

Update a local copy of the PR: \
`$ git checkout pull/19607` \
`$ git pull https://git.openjdk.org/jdk.git pull/19607/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19607`

View PR using the GUI difftool: \
`$ git pr show -t 19607`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19607.diff">https://git.openjdk.org/jdk/pull/19607.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19607#issuecomment-2155558024)

### CODE REVIEW

**Comment by liach** [comment]
Since you are using the value tag on the field themselves to display their own value, I believe a `{@value}` suffices. See the example in java.lang.constant.ConstantDescs: https://github.com/openjdk/jdk/blob/cf677c901e70d98404ec9cc3d75a93926e02fcd2/src/java.base/share/classes/java/lang/constant/ConstantDescs.java#L307
https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/constant/ConstantDescs.html#INIT_NAME

**Review by jonathan-gibbons — COMMENTED** [review]
You can omit the field name from a `{@value ...}` tag if the tag is in the doc comment for that field.   Thus is most if not all the cases here, you can simplify all tags to just `{@value}`.

**Review by liach — APPROVED** [review]
Thanks for this simplification!

**Review by rgiulietti — APPROVED** [review]
LGTM

**Pull request closed without merging**
