### PR TITLE
8312777: notifyJvmtiMount before notifyJvmtiUnmount

### PR DESCRIPTION
**Pull request by AlanBateman**
JVMTI is notified after a virtual thread unmounts. Right not, this notification is done after the virtual thread has finished parking or yielding so it's possible for the virtual to continue, and be mounted on a different carrier, before the unmount notification has completed on the original carrier. If this happens it means the the JVMTI mount and unmount notifications will race and it's possible they could be unbalanced. The unmount notification needs to move to after the unmount and before the virtual thread state is changed.

While in the area, I've removed @ChangesCurrentThread from VirtualThread.run. This annotation was in place to workaround an issue with the notifyJvmtiXXX instrinsics, fixed recently by JDK-8316130.

Testing: tier1-6.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312777](https://bugs.openjdk.org/browse/JDK-8312777): notifyJvmtiMount before notifyJvmtiUnmount (**Bug** - P3)

### Reviewers
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**) ⚠️ Review applies to [aa9587b7](https://git.openjdk.org/jdk/pull/16194/files/aa9587b714484280f6ebfdb01c3dae06a350e52c)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16194/head:pull/16194` \
`$ git checkout pull/16194`

Update a local copy of the PR: \
`$ git checkout pull/16194` \
`$ git pull https://git.openjdk.org/jdk.git pull/16194/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16194`

View PR using the GUI difftool: \
`$ git pr show -t 16194`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16194.diff">https://git.openjdk.org/jdk/pull/16194.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16194#issuecomment-1763195186)

### CODE REVIEW

**Review by Hamlin-Li — APPROVED** [review]
LGTM.

**Review by sspitsyn — APPROVED** [review]
Looks good. It is more elegant now.
I was thinking if it'd make sense to move:
 - `notifyJvmtiMount(/*hide*/true);` at start of `mount()`
 -  `notifyJvmtiUnmount(/*hide*/false);` at end of unmount()
but I guess you wanted to have them at the `runContinuation()` level.

Thanks,
Serguei

**Comment by AlanBateman** [comment]
> Looks good. It is more elegant now. I was thinking if it'd make sense to move:
> 
> * `notifyJvmtiMount(/*hide*/true);` at start of `mount()`
> * `notifyJvmtiUnmount(/*hide*/false);` at end of unmount()
>   but I guess you wanted to have them at the `runContinuation()` level.

I'd be happy to move them to mount/unmount. As I recall, this wasn't possible because it lead to unbalanced method enter/exit, e.g. enter mount, exit unmount. I can re-test with to see what issues we might have but I suspect you will remember the issues with balancing the enter/exit.

**Comment by AlanBateman** [comment]
I tested tier1-tier6 with the JVMTI notifications moved to mount/unmount and don't see any failures. So if you are okay with that then it would be a bit nicer. The main thing is that the notification is done before the virtual thread state changes.

**Pull request closed without merging**
