### PR TITLE
8275448: [REDO] AArch64: Implement string_compare intrinsic in SVE

### PR DESCRIPTION
**Pull request by tatwaichong**
After JDK-8269559 was integrated there are failures in tier1 testing
across Mac OS X 11.4 (aarch64) machines. Please see JDK-8275263.

This patch is NOT functional; rather, this tends to verify potential
toolchain issues as the original patch pass testing on other
platforms.

In this patch, we remove new SVE-related matching rules and register
class introduced in the original patch to minimally affect the
non-SVE part.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275448](https://bugs.openjdk.java.net/browse/JDK-8275448): [REDO] AArch64: Implement string_compare intrinsic in SVE

### Reviewers
 * [Nick Gasson](https://openjdk.java.net/census#ngasson) (@nick-arm - **Reviewer**) ⚠️ Review applies to c5f61f57e055d9da1119cdc537fe21a1af520dde
 * aph - **Reviewer** ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6072/head:pull/6072` \
`$ git checkout pull/6072`

Update a local copy of the PR: \
`$ git checkout pull/6072` \
`$ git pull https://git.openjdk.java.net/jdk pull/6072/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6072`

View PR using the GUI difftool: \
`$ git pr show -t 6072`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6072.diff">https://git.openjdk.java.net/jdk/pull/6072.diff</a>

</details>

### CODE REVIEW

**Comment by tatwaichong** [comment]
@TobiHartmann, The latest patch is the final version. Could you re-run testing again? Many thanks.

**Comment by TobiHartmann** [comment]
@tatwaichong All tests passed.

**Comment by tatwaichong** [comment]
@TobiHartmann @dholmes-ora, This patch is more or less identical to the original patch (https://github.com/openjdk/jdk/pull/5129). Now, this has passed all tests mentioned above. Do these tests cover failures that appeared on the original patch (https://bugs.openjdk.java.net/browse/JDK-8275263)? If these failures have disappeared, it may be safe to submit?

**Comment by TobiHartmann** [comment]
Yes, I executed the same testing (and much more) that triggered the failures with your original test. But I'll re-run just to make sure.

**Comment by tatwaichong** [comment]
Sound good. Let me know when the result came out, please.  Then I merge this PR.

**Comment by TobiHartmann** [comment]
All tests passed. Is there any difference between this version of the patch and the version that previously triggered failures?

**Comment by tatwaichong** [comment]
They are almost identical except the comparison in the stub code has been changed from "if (!UseSVE)"  to "if (UseSVE == 0)". 
It doesn't mean that that is the cause of these failures. The generated codes from Toolchains are different from patch to patch.
They should be equivalent but as I'm not familiar macOS toolchain, this change can avoid unnecessarily casting from `uint` to `bool`.
Please see [UseSVE](https://github.com/openjdk/jdk/blob/673ce7efa56e7eb54266af6fe795d46d57f51bdc/src/hotspot/cpu/aarch64/globals_aarch64.hpp#L101)

**Comment by tatwaichong** [comment]
/reviewer credit @theRealAph
/reviewer credit @nick-arm
Hi there, Could you give a code review of this patch, please? Thanks in advance.

**Review by nick-arm — APPROVED** [review]

**Comment by TobiHartmann** [comment]
> They are almost identical except the comparison in the stub code has been changed from "if (!UseSVE)" to "if (UseSVE == 0)". It doesn't mean that is the cause of these failures. The generated codes from Toolchains are different from patch to patch. They should be equivalent but as I'm not familiar macOS toolchain, this change can avoid unnecessary casting from `uint` to `bool`. Please see [UseSVE](https://github.com/openjdk/jdk/blob/673ce7efa56e7eb54266af6fe795d46d57f51bdc/src/hotspot/cpu/aarch64/globals_aarch64.hpp#L101)

I undid that change and re-executed testing. No failures. Integrating this again without knowing the root cause of the previous failures is a bit concerning.

**Comment by theRealAph** [comment]
> > They are almost identical except the comparison in the stub code has been changed from "if (!UseSVE)" to "if (UseSVE == 0)". It doesn't mean that is the cause of these failures. The generated codes from Toolchains are different from patch to patch. They should be equivalent but as I'm not familiar macOS toolchain, this change can avoid unnecessary casting from `uint` to `bool`. Please see [UseSVE](https://github.com/openjdk/jdk/blob/673ce7efa56e7eb54266af6fe795d46d57f51bdc/src/hotspot/cpu/aarch64/globals_aarch64.hpp#L101)
> 
> I undid that change and re-executed testing. No failures. Integrating this again without knowing the root cause of the previous failures is a bit concerning.

True, but there never was much chance that this change directly caused the failures. My money is still on a toolchain problem.

**Comment by nick-arm** [comment]
> 
> I undid that change and re-executed testing. No failures. Integrating this again without knowing the root cause of the previous failures is a bit concerning.

Is it possible to re-test the exact commit that caused the problem? 8b1b6f9fb

**Comment by TobiHartmann** [comment]
> Is it possible to re-test the exact commit that caused the problem? [8b1b6f9](https://github.com/openjdk/jdk/commit/8b1b6f9fb375bbc2de339ad8f526ca4d5f83dc70)

Yes, I just did that and the failures reproduce immediately.

**Comment by TobiHartmann** [comment]
Okay, it seems to be different failures from what has been reported in [JDK-8275263](https://bugs.openjdk.java.net/browse/JDK-8275263). Now, only the `gtest/GTestWrapper.java` fails in `AssemblerAArch64::validate_vm`. Either the failures reported by JDK-8275263 are spurious or they have been fixed by another change.

**Comment by nick-arm** [comment]
> Now, only the `gtest/GTestWrapper.java` fails in `AssemblerAArch64::validate_vm`.

That is still quite strange. I just tried `gtest/GTestWrapper.java` on that commit on an M1 Mac and it passed (both fastdebug and release build). Could you post the log of the failing test?

**Comment by tatwaichong** [comment]
I haven't caught up. I'm confused that above mentioned all tests passed on the latest patch. Is gtest/GTestWrapper.java not included?

**Comment by nick-arm** [comment]
@tatwaichong the `gtest/GTestWrapper.java` failure was on a re-test of your original commit, 8b1b6f9. This latest PR seems fine.

**Comment by TobiHartmann** [comment]
> Could you post the log of the failing test?

The log file is not too helpful, it just contains:

```
java.lang.AssertionError: gtest execution failed; exit code = 2. the failed tests: [AssemblerAArch64::validate_vm, ... AssemblerAArch64::validate_vm, AssemblerAArch64::validate_vm]
	at GTestWrapper.main(GTestWrapper.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Where the `AssemblerAArch64::validate_vm` is repeated many times.

> @tatwaichong the `gtest/GTestWrapper.java` failure was on a re-test of your original commit, [8b1b6f9](https://github.com/openjdk/jdk/commit/8b1b6f9fb375bbc2de339ad8f526ca4d5f83dc70). This latest PR seems fine.

Yes, exactly.

As this change seems stable, I'm fine with integrating it.

**Comment by tatwaichong** [comment]
@TobiHartmann, @merykitty Hi, could you have a look at the failure of Linux x86 (hs/tier1 compiler) in compiler/c2/irTests/TestUnsignedComparison.java?

It seems that failure isn't introduced by this patch.

**Comment by TobiHartmann** [comment]
I had a look at the artifacts and the test fails because the VM crashes with:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/runner/work/jdk/jdk/jdk/src/hotspot/share/opto/matcher.cpp:1714), pid=36076, tid=36091
#  assert(false) failed: bad AD file
#
# JRE version: OpenJDK Runtime Environment (18.0) (fastdebug build 18-internal+0-tatwaichong-009443ec6847694c2b0b0cd058dc1768dd5c5e34)
# Java VM: OpenJDK Server VM (fastdebug 18-internal+0-tatwaichong-009443ec6847694c2b0b0cd058dc1768dd5c5e34, mixed mode, sharing, tiered, g1 gc, linux-x86)
# Problematic frame:
# V  [libjvm.so+0x11bc845]  Matcher::Label_Root(Node const*, State*, Node*, Node*&)+0x565

Current CompileTask:
C2:   1067  644    b  4       compiler.c2.irTests.TestUnsignedComparison::testLongVarLT (20 bytes)

Stack: [0x92f3f000,0x93000000],  sp=0x92ffd130,  free space=760k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x11bc845]  Matcher::Label_Root(Node const*, State*, Node*, Node*&)+0x565
V  [libjvm.so+0x11bd194]  Matcher::match_tree(Node const*)+0x214
V  [libjvm.so+0x11c8ee5]  Matcher::xform(Node*, int)+0x1115
V  [libjvm.so+0x11d2a65]  Matcher::match()+0x37a5
V  [libjvm.so+0x966a72]  Compile::Code_Gen()+0xa2
V  [libjvm.so+0x973a20]  Compile::Compile(ciEnv*, ciMethod*, int, Options, DirectiveSet*)+0x17f0
V  [libjvm.so+0x799283]  C2Compiler::compile_method(ciEnv*, ciMethod*, int, bool, DirectiveSet*)+0x853
V  [libjvm.so+0x98499b]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0xe6b
V  [libjvm.so+0x985a31]  CompileBroker::compiler_thread_loop()+0x761
V  [libjvm.so+0x9ae5fb]  CompilerThread::thread_entry(JavaThread*, JavaThread*)+0x2b
V  [libjvm.so+0x16f60b2]  JavaThread::thread_main_inner()+0x262
V  [libjvm.so+0x16ff71e]  Thread::call_run()+0xfe
V  [libjvm.so+0x1326943]  thread_native_entry(Thread*)+0x123
C  [libpthread.so.0+0x860a]  start_thread+0xea
```

That looks unrelated to this change, I filed [JDK-8277324](https://bugs.openjdk.java.net/browse/JDK-8277324).

**Pull request closed without merging**
