### PR TITLE
8264017: Correctly report inlined frame in JFR sampling

### PR DESCRIPTION
**Pull request by tkrodriguez**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264017](https://bugs.openjdk.java.net/browse/JDK-8264017): Correctly report inlined frame in JFR sampling

### Reviewers
 * [Jaroslav Bachorik](https://openjdk.java.net/census#jbachorik) (@jbachorik - **Reviewer**)
 * [Markus Grönlund](https://openjdk.java.net/census#mgronlun) (@mgronlun - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3148/head:pull/3148`
`$ git checkout pull/3148`

To update a local copy of the PR:
`$ git checkout pull/3148`
`$ git pull https://git.openjdk.java.net/jdk pull/3148/head`

### CODE REVIEW

**Review by jbachorik — APPROVED** [review]

**Review by mgronlun — APPROVED** [review]
Hi Tom, looks good, thank you for this improvement.

**Comment by tkrodriguez** [comment]
Should I perform any additional testing related to JFR?

**Comment by mgronlun** [comment]
The tests located in test/jdk/jdk/jfr should be sufficient.

**Comment by tkrodriguez** [comment]
The tests were clean.

**Comment by mgronlun** [comment]
Great, please proceed with integration.

**Pull request closed without merging**
