### PR TITLE
8257794: Zero: assert(istate->_stack_limit == istate->_thread->last_Java_sp() + 1) failed: wrong on Linux/x86_32

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

Zero debug build on Linux/x86_32 is broken due to an incorrect assert [1].

'istate->_stack_limit' is set here [2] as 'stack->sp() - 1'.
'istate->_thread->last_Java_sp()' is set here [3], which is actually 'stack->sp()' according to [4].

So the correct assert should be:
  assert(istate->_stack_limit == istate->_thread->last_Java_sp() - 1)

It would be better to fix it.

Testing:
   - Zero fastdebug build passed on Linux/x86_32

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/interpreter/zero/bytecodeInterpreter.cpp#L422
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/zero/zeroInterpreter_zero.cpp#L819
[3] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/zero/zeroInterpreter_zero.cpp#L194
[4] https://github.com/openjdk/jdk/blob/master/src/hotspot/os_cpu/linux_zero/thread_linux_zero.hpp#L65

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257794](https://bugs.openjdk.java.net/browse/JDK-8257794): Zero: assert(istate->_stack_limit == istate->_thread->last_Java_sp() + 1) failed: wrong on Linux/x86_32

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1637/head:pull/1637`
`$ git checkout pull/1637`

### CODE REVIEW

**Comment by shipilev** [comment]
Hold on a sec, I meant to see why the assert is there, and why it is in that form, and why it is `IA32_ONLY`. It should either be a generic assert (if it is good assert), or removed completely (if it is a superfluous assert). Code history should reveal the answer to that...

**Comment by shipilev** [comment]
@DamonFool, I don't think `/test` works here, or even makes sense: no current testing runs `Zero`. Please try to `make bootcycle-images` on platforms you can reach.

**Comment by DamonFool** [comment]
> @DamonFool, I don't think `/test` works here, or even makes sense: no current testing runs `Zero`. Please try to `make bootcycle-images` on platforms you can reach.

'make bootcycle-images' have been done on Linux/86_32,64 and MacOS.
All passed.

**Comment by DamonFool** [comment]
> Hold on a sec, I meant to see why the assert is there, and why it is in that form, and why it is `IA32_ONLY`. It should either be a generic assert (if it is good assert), or removed completely (if it is a superfluous assert). Code history should reveal the answer to that...

The assert seems to be there at the creation of the OpenJDK repo.
It was checked in at the second commit:
```
commit 8153779ad32d1e8ddd37ced826c76c7aafc61894
Author: J. Duke <duke@openjdk.org>
Date:   Sat Dec 1 00:00:00 2007 +0000

    Initial load
```

I had checked the debug version of jdk8's zero on Linx/x86_32 finding that it crashed due to the same reason.
Maybe, the debug version of zero for x86_32 was broken at the very beginning.

**Comment by shipilev** [comment]
All right, this makes more sense to me. @dholmes-ora, could you do us a favor and see why this line: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/interpreter/zero/bytecodeInterpreter.cpp#L422

...was added? We don't have access to pre-OpenJDK history to get it ourselves.

**Comment by DamonFool** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@openjdk.java.net):_
> 
> On 7/12/2020 5:59 pm, Aleksey Shipilev wrote:
> 
> > On Mon, 7 Dec 2020 07:38:03 GMT, Jie Fu <jiefu at openjdk.org> wrote:
> > > > Hold on a sec, I meant to see why the assert is there, and why it is in that form, and why it is `IA32_ONLY`. It should either be a generic assert (if it is good assert), or removed completely (if it is a superfluous assert). Code history should reveal the answer to that...
> > > 
> > > 
> > > > Hold on a sec, I meant to see why the assert is there, and why it is in that form, and why it is `IA32_ONLY`. It should either be a generic assert (if it is good assert), or removed completely (if it is a superfluous assert). Code history should reveal the answer to that...
> > > 
> > > 
> > > The assert seems to be there at the creation of the OpenJDK repo.
> > > It was checked in at the second commit:
> > > commit [8153779](https://github.com/openjdk/jdk/commit/8153779ad32d1e8ddd37ced826c76c7aafc61894)
> > > Author: J. Duke <duke at openjdk.org>
> > > Date:   Sat Dec 1 00:00:00 2007 +0000
> > > ```
> > >  Initial load
> > > ```
> > > 
> > > 
> > > I had checked the debug version of jdk8's zero on Linx/x86_32 finding that it crashed due to the same reason.
> > > Maybe, the debug version of zero for x86_32 was broken at the very beginning.
> > 
> > 
> > All right, this makes more sense to me. @dholmes-ora, could you do us a favor and see why this line: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/interpreter/zero/bytecodeInterpreter.cpp#L422
> > ...was added? We don't have access to pre-OpenJDK history to get it ourselves.
> 
> It came in as part of:
> 
> https://bugs.openjdk.java.net/browse/JDK-6571248
> 
> but there is no additional information.
> 
> Cheers,
> David

I will have a look.
Thanks.

**Review by shipilev — CHANGES_REQUESTED** [review]
After looking closer, I think this assert is not very useful, it is already disabled on all platforms except x86_32, and it is probably a leftover after many bulk Zero integrations. I think it is fine, safer, faster to remove it for all platforms. Do it, and I'll approve.

**Review by shipilev — APPROVED** [review]

**Comment by DamonFool** [comment]
> After looking closer, I think this assert is not very useful, it is already disabled on all platforms except x86_32, and it is probably a leftover after many bulk Zero integrations. I think it is fine, safer, faster to remove it for all platforms. Do it, and I'll approve.

Yes, I agree.
Done. Thanks.

**Pull request closed without merging**
