### PR TITLE
8325570: Update to Graphviz 9.0.0

### PR DESCRIPTION
**Pull request by vidmik**
Graphviz (aka. dotty/dot) is used when building "full" docs, and in particular for creating various module graph images (.svg). This change upgrades the Graphviz version used to 9.0.0 (latest).

In particular, the change:

* Updates the createGraphvizBundle.sh script (currently broken) to build graphviz from source
* Updates doc/building.{md,html} to reflect the role of Graphviz and Pandoc in the build
* The version of of the graphviz dependency used when building at Oracle (in jib-profiles.js)

Since, in addition to the changes in this PR itself, the exact version of Graphviz has an effect on the generated images, I have uploaded the docs generated by graphviz 9.0.0 here: https://cr.openjdk.org/~mikael/graphviz-9.0.0/cmp-v1/docs/api/. For baseline the latest jdk23 docs, which uses graphviz 2.38.0, should do the trick: https://download.java.net/java/early_access/jdk23/docs/api/.

For example, picking a random .svg file:

baseline (graphviz 2.38.0): https://download.java.net/java/early_access/jdk23/docs/api/java.base/java/lang/classfile/Signature/RefTypeSig-sealed-graph.svg
new (graphviz 9.0.0): https://cr.openjdk.org/~mikael/graphviz-9.0.0/cmp-v1/docs/api/java.base/java/lang/classfile/Signature/RefTypeSig-sealed-graph.svg

Testing: tier1, manual inspection of a few of the generated .svg files

As far as I can tell there are only very minor differences between the old (2.38.0) and new (9.0.0) .svg files. In particular, it seems like the new graphs are ever so slightly (5-10% or so) larger, but otherwise appear to be identical.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325570](https://bugs.openjdk.org/browse/JDK-8325570): Update to Graphviz 9.0.0 (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17794/head:pull/17794` \
`$ git checkout pull/17794`

Update a local copy of the PR: \
`$ git checkout pull/17794` \
`$ git pull https://git.openjdk.org/jdk.git pull/17794/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17794`

View PR using the GUI difftool: \
`$ git pr show -t 17794`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17794.diff">https://git.openjdk.org/jdk/pull/17794.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17794#issuecomment-1936459998)

### CODE REVIEW

**Comment by liach** [comment]
Quick question, since configure scans for dot, will platform-specific pandoc (like Windows pandoc) lead to different image outputs?

**Review by erikj79 — APPROVED** [review]
Build changes and generator script look good to me. I don't want to be the judge of the difference in svg output.

**Review by minborg — APPROVED** [review]
I have reviewed the image output for some classes (e.g. MemoryLayout) and there is a small scale difference and some minor changes in the appearance of rendered objects. As the rendering is not strictly defined, the effect of the proposed changes looks good to me.

**Review by magicus — APPROVED** [review]
LGTM. Thanks for updating the build documentation!

**Review by mlchung — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
This is the java.se module graph generated by the previous version of Graphviz

[https://cr.openjdk.org/~iris/se/22/latestSpec/images/java.se-graph.svg](https://cr.openjdk.org/~iris/se/22/latestSpec/images/java.se-graph.svg)

and the new version:

[https://cr.openjdk.org/~mikael/graphviz-9.0.0/cmp-v1/docs/api/java.se/module-graph.svg](https://cr.openjdk.org/~mikael/graphviz-9.0.0/cmp-v1/docs/api/java.se/module-graph.svg).

They appear to be topologically identical.  The only differences I see is a slight increase in size, as noted by @vidmik in his original PR comment and a few crossed edges on the lower right side (e.g. java.net.http -> java.base, java.prefs -> java.base).

I think it's a minor price to pay for moving to the more recent version.

Thanks for moving to the newer version!

**Pull request closed without merging**
