### PR TITLE
8335493: check_gc_overhead_limit should reset SoftRefPolicy::_should_clear_all_soft_refs

### PR DESCRIPTION
**Pull request by mmyxym**
It's for fixing the issue should_clear_all_soft_refs is not reset after Parallel Full GC.

Tested test/hotspot/jtreg/gc with -XX:+UseParallelGC

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335493](https://bugs.openjdk.org/browse/JDK-8335493): check_gc_overhead_limit should reset SoftRefPolicy::_should_clear_all_soft_refs (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19982/head:pull/19982` \
`$ git checkout pull/19982`

Update a local copy of the PR: \
`$ git checkout pull/19982` \
`$ git pull https://git.openjdk.org/jdk.git pull/19982/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19982`

View PR using the GUI difftool: \
`$ git pr show -t 19982`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19982.diff">https://git.openjdk.org/jdk/pull/19982.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19982#issuecomment-2202111395)

### CODE REVIEW

**Comment by mmyxym** [comment]
> Inspecting the existing call chains of `set_should_clear_all_soft_refs`, I can see that Parallel full-gc already invokes it via adaptive-size-policy.

Yes, set_should_clear_all_soft_refs will be set to true adaptively but never reset to false.

**Comment by albertnetymk** [comment]
> set_should_clear_all_soft_refs will be set to true adaptively but never reset to false.

I see; does it make sense to reset to false inside `check_gc_overhead_limit` so that callers of `set_should_clear_all_soft_refs` are in the same scope? (Other callers of `set_should_clear_all_soft_refs` always invokes it in pairs.)

If this reset-to-false occurs in the destructor as in your PR, who sets it to true for Parallel or other GCs?

**Comment by mmyxym** [comment]
> > set_should_clear_all_soft_refs will be set to true adaptively but never reset to false.
> 
> I see; does it make sense to reset to false inside `check_gc_overhead_limit` so that callers of `set_should_clear_all_soft_refs` are in the same scope? (Other callers of `set_should_clear_all_soft_refs` always invokes it in pairs.)
I guess the GC cannot be guranteed to happen because of GC Locker for Parallel GC so resetting in ~ClearedAllSoftRefs might be better.
> 
> If this reset-to-false occurs in the destructor as in your PR, who sets it to true for Parallel or other GCs?
As you mentioned, check_gc_overhead_limit sets it for Parallel GC. Shenandoah explicitly sets true/false since it doesn't have the gc lock blocking issue.

**Comment by albertnetymk** [comment]
`set_should_clear_all_soft_refs` should match in pairs. If it's reset in the destructor, where is corresponding set-to-true?

(In the Parallel case, the destructor is invoked after `check_gc_overhead_limit` so the reset would overwrite the set-to-true there.)

**Comment by mmyxym** [comment]
> `set_should_clear_all_soft_refs` should match in pairs. If it's reset in the destructor, where is corresponding set-to-true?
> 
> (In the Parallel case, the destructor is invoked after `check_gc_overhead_limit` so the reset would overwrite the set-to-true there.)

check_gc_overhead_limit sets should_clear_all_soft_refs to true and the sucessful full gc will reset should_clear_all_soft_refs. I didn't the get the point...

**Comment by albertnetymk** [comment]
In `PSParallelCompact::invoke_no_policy`, the structure is essentially:

```
{
  ClearedAllSoftRefs ...
  check_gc_overhead_limit; // set-to-true
}
```

The destructor (as in this PR) would cancel out the clear-soft-ref in the upcoming GCs.

> the sucessful full gc

When does "unsuccessful" full-gc occur?

**Comment by mmyxym** [comment]
> In `PSParallelCompact::invoke_no_policy`, the structure is essentially:
> 
> ```
> {
>   ClearedAllSoftRefs ...
>   check_gc_overhead_limit; // set-to-true
> }
> ```
> 
> The destructor (as in this PR) would cancel out the clear-soft-ref in the upcoming GCs.
> 
> > the sucessful full gc
> 
> When does "unsuccessful" full-gc occur?

Thanks, I see. Do you think reset should_clear_all_soft_refs in constructor of ClearedAllSoftRefs is a better way?

   ClearedAllSoftRefs(bool clear_all_soft_refs, SoftRefPolicy* soft_ref_policy) :
     _clear_all_soft_refs(clear_all_soft_refs),
-    _soft_ref_policy(soft_ref_policy) {}
+    _soft_ref_policy(soft_ref_policy) {
+    if (_clear_all_soft_refs) {
+      _soft_ref_policy->set_should_clear_all_soft_refs(false);
+    }
+  }

**Comment by albertnetymk** [comment]
Personally, I believe ClearedAllSoftRefs will not be necessary in the long run, as it is only used by the full GC of Parallel and G1.

To address the missing `set_should_clear_all_soft_refs(false)` in Parallel, a quick fix might be to modify the code around `check_gc_overhead_limit` so that both setters (true and false) are visible within the same scope. However, a more comprehensive improvement, in my opinion, would be to enhance the GC overhead checking in Parallel. This could be done by invoking the check at the beginning of the GC pause. This way, the decision to clear soft references can be made at the start of the GC pause and applied to the *current* GC pause, instead of deferring it to future GCs. While I believe this approach is viable, it would require further performance testing to confirm its effectiveness once a prototype is ready.

**Comment by mmyxym** [comment]
> Personally, I believe ClearedAllSoftRefs will not be necessary in the long run, as it is only used by the full GC of Parallel and G1.
> 
> To address the missing `set_should_clear_all_soft_refs(false)` in Parallel, a quick fix might be to modify the code around `check_gc_overhead_limit` so that both setters (true and false) are visible within the same scope. However, a more comprehensive improvement, in my opinion, would be to enhance the GC overhead checking in Parallel. This could be done by invoking the check at the beginning of the GC pause. This way, the decision to clear soft references can be made at the start of the GC pause and applied to the _current_ GC pause, instead of deferring it to future GCs. While I believe this approach is viable, it would require further performance testing to confirm its effectiveness once a prototype is ready.

I have made the reset in `check_gc_overhead_limit`.

**Review by albertnetymk — APPROVED** [review]

**Comment by kimbarrett** [comment]
@D-D-H - Did you review this change before sponsoring?  HotSpot changes generally require 2 reviewers.

**Comment by mmyxym** [comment]
> @D-D-H - Did you review this change before sponsoring? HotSpot changes generally require 2 reviewers.

@kimbarrett Sorry, I think it's not critical and kind of trivial so integrate without another reviewer.

**Comment by kimbarrett** [comment]
At a quick glance it looks okay, but I've not looked at it carefully enough to say I've reviewed it.  Given the amount of
discussion I can't agree with it being "trivial".  Small, yes, but with potentially significant impact.  And HotSpot rules
around trivial changes and bypassing some of the review process requires agreement by the Reviewer, of which
there is none recorded in the discussion here.

**Comment by D-D-H** [comment]
@kimbarrett 

Sorry about that. I overlooked the rule that hotspot non-trivial changes require reviews from at least two reviewers.
I'll be more careful in the future to follow the rules strictly.
﻿

**Comment by mmyxym** [comment]
> At a quick glance it looks okay, but I've not looked at it carefully enough to say I've reviewed it. Given the amount of discussion I can't agree with it being "trivial". Small, yes, but with potentially significant impact. And HotSpot rules around trivial changes and bypassing some of the review process requires agreement by the Reviewer, of which there is none recorded in the discussion here.

@kimbarrett Thanks for the clarification. I would follow the exact progress next time.

**Review by kimbarrett — COMMENTED** [review]
Post-integration 2nd review - looks good.

**Comment by leelamv** [comment]
Hi @D-D-H / @mmyxym / @albertnetymk / @kimbarrett 

My name is Leela Mohan Venati. I am part of Service Now JDK team (@zhengyu123  is also part of it) . I found this issue few weeks back. We were trying to file this bug upstream to fix it. In the meantime, Good to see this fix coming. Thanks. 

As part of fixing the bug, I did some archeology to understand how this issue occurred.  This bug was introduced as [8198515: Extract SoftReferencePolicy code out of CollectorPolicy ](https://github.com/openjdk/jdk17/commit/f408526f3073acdeda1e001ab53dc360ea6f1eb2). As the name suggests, this change introduced new classes SoftRefPolicy  and SoftRefGenPolicy. These classes factored out CollectorPolicy classes.  These new classes  importantly hold two important attributes - 
a) "_all_soft_refs_clear" -  Boolean value enabled after the successful completion of "clear all" soft ref policy enabled Full GC.  
b) " _should_clear_all_soft_refs" - Boolean value which is enabled ergonomically by overhead checker. Note that Overhead checker is only applicable for parallelGC and only after full GC and when adaptive sizing policy is enabled only.  This value is used for future FullGC. 

Note that first flag is generally be applicable for any GC algorithm irrespective of overhead checker is available or not. Reason:  "Allocation failure" GC requests can ask for "clear all" soft ref policy Full GCs.  It is internally called "max compaction" Full GC.  
However, second flag is only applicable if there is overhead checker which ergonomically enables "clear all" policy. 

GC algorithms which don't have the overhead checker are expected to use SoftRefPolicy type for "_soft_ref_policy" field. Using SoftRefPolicy, there is no need of "resetting" of "_should_clear_all_soft_refs" after Full GC is completed. Check the SoftRefPolicy::cleared_all_soft_refs().   GenCollectedHeap (which is for Serial GC) should have used SoftRefPolicy instead of SoftRefGenPolicy [here](https://github.com/openjdk/jdk17/commit/f408526f3073acdeda1e001ab53dc360ea6f1eb2#diff-983a579a9bfabca3b17e9e6d6ff3b554c35a32e92ff0a0eec1d113064aca21b0R74)

GC algorithms which have the overhead checker are expected to use SoftRefGenPolicy for "_soft_ref_policy" field. This allows "resetting" of "_should_clear_all_soft_refs" after  Full GC is completed.  Check the [SoftRefGenPolicy::cleared_all_soft_refs](https://github.com/openjdk/jdk17/commit/f408526f3073acdeda1e001ab53dc360ea6f1eb2#diff-343f154ae8ddb14a561b33cbe2a667c8eb349d628358282a891f0f19193004eeR30) . Also note that , it handles "near overhead limit" to reset for not.  ParallelScavengeHeap (which is for Parallel GC) should have used SoftRefGenPolicy instead of SoftRefPolicy [here](https://github.com/openjdk/jdk17/commit/f408526f3073acdeda1e001ab53dc360ea6f1eb2#diff-f6a37dd865cabd1f1b1274cf87cdd3119f423be40a66759cd688408560badd13R63).  That's the bug. 

Except for the introduction of the bug, [change](https://github.com/openjdk/jdk17/commit/f408526f3073acdeda1e001ab53dc360ea6f1eb2) itself is nice cleanup change.  

Now why am i explaining this back story ?

I would have liked this change to be fixed using SoftRefGenPolicy type for "_soft_ref_policy" field in ParallelScavengeHeap. However, i do notice that SoftRefGenPolicy is removed in the master that means, we need add the file which was removed.

On jdk17u branch, i made a patch (see the attachment) which renames SoftGenRefPolicy as "PSSoftRefPolicy" (following the convention of parallel GC specific class) and used PSSoftRefPolicy for "soft_ref_policy" field . 
[patch.txt](https://github.com/user-attachments/files/16170231/patch.txt)

**Comment by mmyxym** [comment]
Hi @leelamv , I just want to fix the unpaired set/reset of clear-soft-ref for Parallel GC. You can still refactor the policy on Parallel GC and @albertnetymk had some suggestions in review comments. I think that would be quite welcome.

**Pull request closed without merging**
