### PR TITLE
8275170: Some jtreg sound tests should be marked with sound keyword

### PR DESCRIPTION
**Pull request by prrace**
This fix adds "headful sound" keywords to a number of javax/sound jtreg tests

The jtreg javax.sound tests are written in such a way that if a needed audio device
or other platform resource is not available, they just exit with a "pass" for the test.
It is as if headful tests just swallowed HeadlessException and issued a pass.
If we allowed that we'd be effectively testing almost nothing of real importance.

Currently almost  all sound tests have no keyword like "headful" to indicate they
may need access to a hardware resource to do anything useful so a similar
situation arises there except when someone runs those tests manually on
a local system which has audio devices.

Of course "headful" and "audio device" aren't exactly interchangeable terms
but if tests are allowed to be run - or worse usually or always run - in a situation
where they potentially are on a system without an audio device (a headless VM) or are running in
a session which doesn't have full desktop access - which may in some
cases be how audio device access is granted, then they are more likely
to be running in this scenario where the testing isn't valid.

Another point is that headful tests must be run one at a time - no concurrency because
you can't have multiple tests moving the mouse at the same time
Whereas for headless tests, a test harness may choose to run concurrently - perhaps even in the same VM
When tests that really need access to an audio device are run it is probably safer to consider
the headful attribute as implying one test at a time is best .. granted on a desktop it isn't
usual for a single app to be able to monopolize access to a speaker, but for input devices
that is what you'd generally expect.

By no means am I sure that the tests being updated here are the full set that need tagging.
There are a lot of tests and they are all known to pass on systems with NO audio
devices, so the search has been for tests which call APIs which will definitely
need access to some device in order to do anything useful.
So likely there are more to be added - either by a reviewer pointing them out or by later discovery.
Alternatively we could mark ALL sound tests headful .. but given where we are starting from
that might be erring unnecessarily far in the opposite direction.

By adding both headful and sound keywords it gives options to someone who
wants to identify the tests and perhaps run just tests which need "sound" on some
config they know supports audio but isn't headful.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8275170](https://bugs.openjdk.java.net/browse/JDK-8275170): Some jtreg sound tests should be marked with sound keyword

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**) ⚠️ Review applies to [98d02ae2](https://git.openjdk.java.net/jdk/pull/6086/files/98d02ae28c70a9df9458b514fc96ac10ca65e6da)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6086/head:pull/6086` \
`$ git checkout pull/6086`

Update a local copy of the PR: \
`$ git checkout pull/6086` \
`$ git pull https://git.openjdk.java.net/jdk pull/6086/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6086`

View PR using the GUI difftool: \
`$ git pr show -t 6086`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6086.diff">https://git.openjdk.java.net/jdk/pull/6086.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
I am not sure this is the right thing to do, as you pointed out the headless system may or may not have the sound configured, similar to the headful system may not have a sound. I see a lot of headful systems in the cloud where the audio device is not configured, and the opposite where the headless system actually has some audio devices. And this change just makes things complicated by assignee the headful keyword to the unrelated sound system.

Actually, it is the step in the opposite direction that was done when these tests were moved to tier3, at that the headful keyword was removed from these tests to make tier3 coverage as much as possible.

I am still not sure what problem do you want to solve? If the problem is to run the tests on the system where the sound is configured then just run them there, so it will not be necessary to validate each test does it really need a sound/headful keyword or not, otherwise what is the benefit?

**Review by azuev-java — APPROVED** [review]
Looks right to me.

**Comment by prrace** [comment]
The current version only adds the 'sound' keyword.
So it doesn't carry any of the implications of headful.

**Review by mrserb — APPROVED** [review]
Looks fine.

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
