### PR TITLE
8317340: Windows builds are not reproducible if MS VS compiler install path differs

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
When doing a reproducible Windows build on two different machines, that
happen to have MS Visual Studio installed in different paths, the resulting
builds are not identical. This is due to the System include paths, eg:
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime_new.h
```
appearing in the compiler obj as part of debug info.

This PR tests when doing a Windows no-Absolute paths allowed build, and then
adds -pathmap:\<VS_include_long_path\>=vsi entries to re-map those entries in
the compiler object.
The VS cl compiler generates these paths as standard Windows "long path" entries,
and must be pathmap'd as such.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317340](https://bugs.openjdk.org/browse/JDK-8317340): Windows builds are not reproducible if MS VS compiler install path differs (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16008/head:pull/16008` \
`$ git checkout pull/16008`

Update a local copy of the PR: \
`$ git checkout pull/16008` \
`$ git pull https://git.openjdk.org/jdk.git pull/16008/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16008`

View PR using the GUI difftool: \
`$ git pr show -t 16008`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16008.diff">https://git.openjdk.org/jdk/pull/16008.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16008#issuecomment-1742779698)

### CODE REVIEW

**Comment by erikj79** [comment]
What effect will this have on debugging?

**Comment by andrew-m-leonard** [comment]
> What effect will this have on debugging?

Hi @erikj79 
So this is the same as we pathmap the openjdk workspace source just above, in that we only do it when ALLOW_ABSOLUTE_PATHS_IN_OUTPUT is "false", which is for release builds.
For "debug" builds it is "true" and no pathmap'ing occurs, see: https://github.com/openjdk/jdk/blob/2637e8ddc4ffe102418139f501fc0be8e9c5317b/make/autoconf/jdk-options.m4#L696

**Comment by andrew-m-leonard** [comment]
https://github.com/openjdk/jdk/blob/2637e8ddc4ffe102418139f501fc0be8e9c5317b/make/autoconf/flags-cflags.m4#L830

**Comment by erikj79** [comment]
> > What effect will this have on debugging?
> 
> Hi @erikj79 So this is the same as we pathmap the openjdk workspace source just above, in that we only do it when ALLOW_ABSOLUTE_PATHS_IN_OUTPUT is "false", which is for release builds. For "debug" builds it is "true" and no pathmap'ing occurs, see:

Yes, I'm aware of that. I was just curious if you had tested and investigated the consequences of doing this when trying to debug a "release" build. I'm not against this change, but it would be good to understand any consequences.

**Comment by andrew-m-leonard** [comment]
> > > What effect will this have on debugging?
> > 
> > 
> > Hi @erikj79 So this is the same as we pathmap the openjdk workspace source just above, in that we only do it when ALLOW_ABSOLUTE_PATHS_IN_OUTPUT is "false", which is for release builds. For "debug" builds it is "true" and no pathmap'ing occurs, see:
> 
> Yes, I'm aware of that. I was just curious if you had tested and investigated the consequences of doing this when trying to debug a "release" build. I'm not against this change, but it would be good to understand any consequences.

Ah I see :-) So for debugging a release it would mean potentially any VS

**Comment by andrew-m-leonard** [comment]
@erikj79 I shell run a debug session on a release image and see what if anything it causes.

**Comment by andrew-m-leonard** [comment]
> > > What effect will this have on debugging?
> > 
> > 
> > Hi @erikj79 So this is the same as we pathmap the openjdk workspace source just above, in that we only do it when ALLOW_ABSOLUTE_PATHS_IN_OUTPUT is "false", which is for release builds. For "debug" builds it is "true" and no pathmap'ing occurs, see:
> 
> Yes, I'm aware of that. I was just curious if you had tested and investigated the consequences of doing this when trying to debug a "release" build. I'm not against this change, but it would be good to understand any consequences.

@erikj79 So I started up a VS2022 debugging session for a java.exe process, and the vcruntime140 debugging information is loaded via the Microsoft Symbol Server anyway, same with debug src. Your VS2022 tools debugging source PATH for the VC tools is also pointing at your local VS2022 include folder.

**Comment by andrew-m-leonard** [comment]
@erikj79 So done some debugging of the main Java os_windows.cpp thread and debugging is fine, openjdk pdb's loaded fine, and vcruntime symbols loaded from Symbol Server. Also, did a debug session without these changes, and all behaves identically.

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
It looks like this change broke the build on WSL. The pathtool in WSL (wslpath) does not support the `-l` option.

**Pull request closed without merging**
