### PR TITLE
8321823: Remove redundant PhaseGVN transform_no_reclaim

### PR DESCRIPTION
**Pull request by caojoshua**
`PhaseGVN::transform` is just a one line wrapper around `PhaseGVN::transform_no_reclaim`. Looking at the history, they had different functionality in 2008, but since have become the same thing. We prefer to keep `PhaseGVN::transform` because it has hundreds of callsites, while the other only has a few callsites that are shown in the PR.

Passes tier1 locally on my Linux machine.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321823](https://bugs.openjdk.org/browse/JDK-8321823): Remove redundant PhaseGVN transform_no_reclaim (**Enhancement** - P5)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17071/head:pull/17071` \
`$ git checkout pull/17071`

Update a local copy of the PR: \
`$ git checkout pull/17071` \
`$ git pull https://git.openjdk.org/jdk.git pull/17071/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17071`

View PR using the GUI difftool: \
`$ git pr show -t 17071`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17071.diff">https://git.openjdk.org/jdk/pull/17071.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17071#issuecomment-1851123639)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
The title of the RFE is a little bit misleading as it suggests that both are redundant. Maybe you can change that into just mentioning that `PhaseGVN::transform_no_reclaim()` is redundant. 

Otherwise, looks good!

**Review by chhagedorn — APPROVED** [review]
Thanks for the update, still looks good.

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
There are a couple of GHA failures that look compiler related. I approved the PR before looking at these because the patch is trivial on its face, but now I'm suspicious.

**Comment by merykitty** [comment]
@phohensee Those are [JDK-8321820](https://bugs.openjdk.org/browse/JDK-8321820) and [JDK-8321542](https://bugs.openjdk.org/browse/JDK-8321542).

**Comment by caojoshua** [comment]
Merged from master. This should pass the failing test with https://github.com/openjdk/jdk/commit/d632d743e018c69ecf423af75b65354e8ffaefc8

**Comment by ysramakrishna** [comment]
Since GHA passes, and @phohensee has reviewed, I'm happy to:

/sponsor

**Pull request closed without merging**
