### PR TITLE
8322983: Virtual Threads: exclude 2 tests

### PR DESCRIPTION
**Pull request by lepestock**
Tests
runtime/classFileParserBug/TestEmptyBootstrapMethodsAttr.java
runtime/logging/LoaderConstraintsTest.java

fail with virtual threads. Shouldn't be executed in this mode.

Testing: tiers 1 through 3 and tier5, all passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322983](https://bugs.openjdk.org/browse/JDK-8322983): Virtual Threads: exclude 2 tests (**Bug** - P4)

### Reviewers
 * [SendaoYan](https://openjdk.org/census#syan) (@sendaoYan - Committer) Review applies to [9ef7d5ee](https://git.openjdk.org/jdk/pull/22782/files/9ef7d5ee1732d1dbe512260f6763052fd561bc68)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22782/head:pull/22782` \
`$ git checkout pull/22782`

Update a local copy of the PR: \
`$ git checkout pull/22782` \
`$ git pull https://git.openjdk.org/jdk.git pull/22782/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22782`

View PR using the GUI difftool: \
`$ git pr show -t 22782`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22782.diff">https://git.openjdk.org/jdk/pull/22782.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22782#issuecomment-2548512269)
</details>

### CODE REVIEW

**Review by sendaoYan — APPROVED** [review]
These two tests also observed by ours CI, which has been recorded by https://bugs.openjdk.org/browse/JDK-8343119

**Comment by jaikiran** [comment]
Looking at the linked JBS issue it appears that it was filed almost a year back (for JDK 22 release?). So that would mean that these 2 tests should be failing in virtual thread execution of jtreg currently in mainline. I hadn't seen reports of the failures of these 2 tests before, so I went and looked in our CI runs and indeed these 2 have been failing forever.

Problem listing these 2 for virtual thread execution mode I think is the right thing to do. Please wait for additional reviews from someone else from this area.

At some later date I think these 2 tests (or at least the TestEmptyBootstrapMethodsAttr test) could be updated to make them pass with virtual thread execution mode as well. Looking at that failure and the test itself, it doesn't really have anything to do with virtual threads, so it would be good to address that test failure at some later date.

**Review by jaikiran — APPROVED** [review]

**Comment by lepestock** [comment]
> At some later date I think these 2 tests ... could be updated to make them pass with virtual thread execution mode as well

Raised the https://bugs.openjdk.org/browse/JDK-8346442, updated the case labels.

**Review by lmesnik — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]
Thank you for filing the additional issue to address the test failures in future.
This current change still looks good to me.

**Pull request closed without merging**
