### PR TITLE
JDK-8268461: ARM32: vector intrinsics reaches ShouldNotReachHere

### PR DESCRIPTION
**Pull request by mychris**
This fixes C2 vector intrinsics for 32-bit ARM.
Since the problem exists in mainline, I guess it should be fixed here first and will later be merged into the panama repository.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268461](https://bugs.openjdk.java.net/browse/JDK-8268461): ARM32: vector intrinsics reaches ShouldNotReachHere

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4430/head:pull/4430` \
`$ git checkout pull/4430`

Update a local copy of the PR: \
`$ git checkout pull/4430` \
`$ git pull https://git.openjdk.java.net/jdk pull/4430/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4430`

View PR using the GUI difftool: \
`$ git pr show -t 4430`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4430.diff">https://git.openjdk.java.net/jdk/pull/4430.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
LGTM

**Review by nsjian — APPROVED** [review]

**Comment by mychris** [comment]
Thanks for the reviews.
@DamonFool Is this trivial enough to integrate right away with only one approval of a reviewer?

**Comment by DamonFool** [comment]
> Thanks for the reviews.
> @DamonFool Is this trivial enough to integrate right away with only one approval of a reviewer?

Yes, it's trivial IMO.
And I think it's fine to go since it has already been reviewed by @nsjian .
Thanks.

**Pull request closed without merging**
