### PR TITLE
8270204: [macos11] JTabbedPane selected tab text is barely legible (again)

### PR DESCRIPTION
**Pull request by prsadhuk**
The JTabbedPane background color was fixed in JDK-8251377 but it actually relies on os.version being returned by JVM as 10.16. However, JVM has been modified since to return 11.x for MacOSX Bigsur release so we need to update code to rely on modified version.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8270204](https://bugs.openjdk.java.net/browse/JDK-8270204): [macos11] JTabbedPane selected tab text is barely legible (again)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4824/head:pull/4824` \
`$ git checkout pull/4824`

Update a local copy of the PR: \
`$ git checkout pull/4824` \
`$ git pull https://git.openjdk.java.net/jdk pull/4824/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4824`

View PR using the GUI difftool: \
`$ git pr show -t 4824`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4824.diff">https://git.openjdk.java.net/jdk/pull/4824.diff</a>

</details>

### CODE REVIEW

**Comment by prsadhuk** [comment]
@prrace Could you please review?

Seems no email is sent to mailing lists due to global outage and backlog will take some time to clear, need to ask individually.

**Comment by prrace** [comment]
So the fix relied on the version being 10.16. When the JDK was fixed under
https://bugs.openjdk.java.net/browse/JDK-8253702
to report 11.x then that broke this  fix ?

Well I think you ought to be aware of this bug too : https://bugs.openjdk.java.net/browse/JDK-8269850

If we change to look for os version 11 and above, then until that bug is fixed this will regress again.
And what if the same happens with macOS 13 ?

So maybe we should make this fix check for 10.16 or higher ??

**Comment by prrace** [comment]
> > So maybe we should make this fix check for 10.16 or higher ??
> 
> That is exactly what i did in my fix for #4833 - it works on both 11 and 12+

OK. So we only need it fixed once.
However now I understand what happened its clear this is a P2 that needs to be fixed in 17, so your reward is you get to do a critical request and extra testing :-)

**Comment by prsadhuk** [comment]
This fix works for 11 and above...I guess eventually JDK-8269850 will be fixed by backporting JDK-8253702 so we will not need 10.16 check but till then if we need to support 10.16 or above, I guess PR#4833 addresses that and there's no need to have duplicate effort to fix this, so closing this.

**Pull request closed without merging**
