### PR TITLE
JDK-8313691: use close after failing os::fdopen in vmError and ciEnv

### PR DESCRIPTION
**Pull request by MBaesken**
In vmError.cpp we use os::fdopen and in case this is successful pass the returned file pointer to a fileStream constructor.
The fileStream object calls fclose on our file pointer  in destruction (and this closes also the underlying file descriptor fd).

However in case of failing os::fdopen we do not create (and later destruct)  a fileStream object so direct call to close might be needed. I also adjusted a comment to make it  even clearer that the fileStream object fcloses the file pointer on the destructor.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313691](https://bugs.openjdk.org/browse/JDK-8313691): use close after failing os::fdopen in vmError and ciEnv (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15139/head:pull/15139` \
`$ git checkout pull/15139`

Update a local copy of the PR: \
`$ git checkout pull/15139` \
`$ git pull https://git.openjdk.org/jdk.git pull/15139/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15139`

View PR using the GUI difftool: \
`$ git pr show -t 15139`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15139.diff">https://git.openjdk.org/jdk/pull/15139.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15139#issuecomment-1664055010)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Functional fix is fine but the comment change is not needed IMO and becomes inconsistent with similar uses in ciEnv.cpp

Thanks

**Comment by TobiHartmann** [comment]
Should we re-add the close in the failing case that we backed out with https://github.com/openjdk/jdk/commit/4577147993c2f87e6ba298a664acad5decc968f0?

**Comment by MBaesken** [comment]
> Should we re-add the close in the failing case that we backed out with [4577147](https://github.com/openjdk/jdk/commit/4577147993c2f87e6ba298a664acad5decc968f0)?

I re-added them and adjusted the comment.
(and thanks for doing the backout, doing fclose  twice was not a good thing )

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. I'll run some testing and report back once it passed.

**Review by dholmes-ora — APPROVED** [review]
Looks good. I'd missed the other PR initially.

Thanks.

**Comment by TobiHartmann** [comment]
All tests passed.

**Comment by MBaesken** [comment]
Hi David and Tobias, thanks for the reviews and for checking the tests on your side too.

/integrate

**Pull request closed without merging**
