### PR TITLE
8344315: Clean up sun.net.www.protocol.jrt.JavaRuntimeURLConnection after JEP 486 integration

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which removes references to `AccessController.doPriveleged()` and also removes a security check?

Specifically:

- The `AccessController.doPriveleged()` has been removed from the implementation.
- The overridden `getPermission()` method has been removed from this internal implementation class.
- The call to `URLClassPath.checkURL()` which used to invoke a SecurityManager check in the presence of a SecurityManager has been removed.

No new test has been introduced and tier1 and tier2 testing is currently in progress.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344315](https://bugs.openjdk.org/browse/JDK-8344315): Clean up sun.net.www.protocol.jrt.JavaRuntimeURLConnection after JEP 486 integration (**Sub-task** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22151/head:pull/22151` \
`$ git checkout pull/22151`

Update a local copy of the PR: \
`$ git checkout pull/22151` \
`$ git pull https://git.openjdk.org/jdk.git pull/22151/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22151`

View PR using the GUI difftool: \
`$ git pr show -t 22151`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22151.diff">https://git.openjdk.org/jdk/pull/22151.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22151#issuecomment-2479308163)
</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM. Would be goot to have @AlanBateman review too.

**Review by AlanBateman — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you Alan and Daniel for the reviews. tier1 and tier2 testing came back fine. 
There's one unrelated failure in this PR's GitHub actions job in `GetStackTraceALotWhenBlocking` which has timed out. I will check to see if a separate issue needs to be created to track that.

**Comment by AlanBateman** [comment]
> Thank you Alan and Daniel for the reviews. tier1 and tier2 testing came back fine. There's one unrelated failure in this PR's GitHub actions job in `GetStackTraceALotWhenBlocking` which has timed out. I will check to see if a separate issue needs to be created to track that.

Patricio and I are looking at the execution time of GetStackTraceALotWhenBlocking and GetStackTraceALotWhenPinned on macox-x64 as both tests make slow progress under some conditions.

**Pull request closed without merging**
