### PR TITLE
8318420 : AbstractPipeline invokes overridden method in constructor

### PR DESCRIPTION
**Pull request by viktorklang-ora**
This PR corrects so that `opIsStateful()` is not invoked as a part of the java.util.stream.AbstractPipeline constructor—as `opIsStateful()` is intended to be overridden by subclasses, and as their own constructors have not run when their superclass constructor runs, this means that `opIsStateful()` cannot base its return value on any class members of the subclass.

Since `opIsStateful()` is only needed for parallel streams, we can therefor defer the invocation of `opIsStateful()` until evaluation-time, and as such we can remove the need for having an instance field to store the result of the invocation—making Stream instances potentially a tiny bit smaller, reducing Stream-construction overhead, while still preserving semantics.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318420](https://bugs.openjdk.org/browse/JDK-8318420): AbstractPipeline invokes overridden method in constructor (**Enhancement** - P5)

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16239/head:pull/16239` \
`$ git checkout pull/16239`

Update a local copy of the PR: \
`$ git checkout pull/16239` \
`$ git pull https://git.openjdk.org/jdk.git pull/16239/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16239`

View PR using the GUI difftool: \
`$ git pr show -t 16239`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16239.diff">https://git.openjdk.org/jdk/pull/16239.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16239#issuecomment-1770427419)

### CODE REVIEW

**Comment by viktorklang-ora** [comment]
@PaulSandoz Would you be up for reviewing this one? :)

**Review by PaulSandoz — APPROVED** [review]

**Comment by viktorklang-ora** [comment]
Pre-submit test seems unrelated to PR

**Pull request closed without merging**
