### PR TITLE
8264223: CodeHeap::verify fails extra_hops assertion in fastdebug test

### PR DESCRIPTION
**Pull request by huishi-hs**
When test with -XX:+VerifyCodeCache, many tests fail due to extra_hops assertion in CodeHeap::verify. See full dump in JBS.

# Internal Error (src/hotspot/share/memory/heap.cpp:838), pid=1525697, tid=1525715
# assert((count == 0) || (extra_hops < (16 + 2*count))) failed: CodeHeap: many extra hops due to optimization. blocks: 234, extra hops: 484.
Discussion in https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2019-October/035508.html doesn't tell where assertion (extra_hops < (16 + 2*count) comes from.

In CodeHeap::mark_segmap_as_used wehn is_FreeBlock_join is true,  it creates extra hops in _segmap. _fragmentation_count in inced and trigger defrag_segmap when reach threshold. In my understanding, extra hop can not guarantee under (16 + 2*count). 

In following extreme case, before HeapBlock free, segmap is all 0 (each blob use 1 smallest segment), suppose free action is applied from right to left. This increase 9 unnecessary hop for 1 continous HeapBlock.  assertion (extra_hops < (16 + 2*count)  is not safe.
|0|0|0|0|0|0|0|0|0|0|
after free, it will be
|0|1|1|1|1|1|1|1|1|1|

Proposed fix is assert extra hops not exceed _fragmentation_count. And if it exceeds (16 + 2 * count), give warning on two many extra hops.

fastdebug tier1, tier2 with VerifyCodeCache passed on X86_64 linux, no extra assertion found.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264223](https://bugs.openjdk.java.net/browse/JDK-8264223): CodeHeap::verify fails extra_hops assertion in fastdebug test

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3212/head:pull/3212` \
`$ git checkout pull/3212`

Update a local copy of the PR: \
`$ git checkout pull/3212` \
`$ git pull https://git.openjdk.java.net/jdk pull/3212/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3212`

View PR using the GUI difftool: \
`$ git pr show -t 3212`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3212.diff">https://git.openjdk.java.net/jdk/pull/3212.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
It would be better to add a test run with `-XX:+VerifyCodeCache` into one of the failing tests.
Thanks.

**Comment by huishi-hs** [comment]
> It would be better to add a test run with `-XX:+VerifyCodeCache` into one of the failing tests.
> Thanks.

Thanks! Test is addded for one previously fail case.

**Comment by DamonFool** [comment]
> Thanks! Test is addded for one previously fail case.

Thanks for your update.

**Comment by dcubed-ojdk** [comment]
This is a hotspot/compiler bug. This review should have gone to the hotspot-compiler
alias and not the hotspot-runtime alias.

**Comment by huishi-hs** [comment]
> This is a hotspot/compiler bug. This review should have gone to the hotspot-compiler
> alias and not the hotspot-runtime alias.

Thanks! Daniel

**Comment by dholmes-ora** [comment]
> 
> 
> This is a hotspot/compiler bug. This review should have gone to the hotspot-compiler
> alias and not the hotspot-runtime alias.

@dcubed-ojdk The bot assigned it to runtime, so we probably need to check the file matching rules.

**Comment by huishi-hs** [comment]
Would someone help review this PR?

@RealLucy the failure assertion is introduced in CodeHeap management earlier, could you help comment and review?

**Comment by RealLucy** [comment]
Will look into this and comment/review asap.

**Comment by huishi-hs** [comment]
> Will look into this and comment/review asap.

Thanks!

**Review by RealLucy — APPROVED** [review]
The change looks good to me.
Thank you for digging into the tricky code to understand what's happening. The previous limit (16+2*count) was purely heuristic. Obviously, you have a more pathological test case.

**Comment by RealLucy** [comment]
I would volunteer to sponsor this PR

**Comment by huishi-hs** [comment]
> The change looks good to me.
> Thank you for digging into the tricky code to understand what's happening. The previous limit (16+2*count) was purely heuristic. Obviously, you have a more pathological test case.

Thanks! The entire CodeHeap optimization is great!

**Comment by RealLucy** [comment]
You will need a second review before the fix can be integrated.

**Review by shipilev — COMMENTED** [review]
It looks fine. But I have a question: are we reasonably sure that `extra_hops <= _fragmentation_count` always. More specifically, when `_fragmentation_count` drops to `0`, are `extra_hops` guaranteed to be `0` as well?

**Comment by RealLucy** [comment]
@shipilev Short answer: yes.
Long answer:
_fragmentation_count is incremented every time the segment map becomes _potentially_ more fragmented by introducing an additional chunk, see mark_segmap_as_used(). Therefore, _fragmentation_count overestimates the actual segmap fragmentation.
 
Once _fragmentation_count hits the limit, defragmentation is triggered (defrag_segmap(true)) and the counter is set to zero. After defragmentation, segmap should not contain any extra hops - that's the purpose of defragmentation. If is does, I would classify that as a bug.

**Review by shipilev — APPROVED** [review]
Okay then, thanks.

**Pull request closed without merging**
