### PR TITLE
8286185: The Java manpage can be more platform inclusive

### PR DESCRIPTION
**Pull request by dholmes-ora**
This is mainly an expansion of the included platforms by changing "linux and macOS" to "Non-Windows". There are a few additional examples, and clarification that they are just examples. There are also some minor edits and corrections I spotted.

One actual fix relates to the "control-break" -> "control-\" change. I can factor that out if needed (or just add an additional issue to the PR).

This doesn't attempt to give complete platform recognition for all OpenJDK platforms. Two areas where anyone interested could file a further RFE is the support of DTrace on BSD systems other than macOS; and the use of RTM locking on Power8 architecture (existing documentation is all about Intel TSX on x86).

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286185](https://bugs.openjdk.org/browse/JDK-8286185): The Java manpage can be more platform inclusive

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11340/head:pull/11340` \
`$ git checkout pull/11340`

Update a local copy of the PR: \
`$ git checkout pull/11340` \
`$ git pull https://git.openjdk.org/jdk pull/11340/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11340`

View PR using the GUI difftool: \
`$ git pr show -t 11340`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11340.diff">https://git.openjdk.org/jdk/pull/11340.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Nice doc update.
Looks good to me.
Thanks,
Serguei

**Comment by dholmes-ora** [comment]
Thanks for looking at this @sspitsyn !

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by dholmes-ora** [comment]
Thanks @vnkozlov !

**Review by iklam — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
Thanks @iklam !

/integrate

**Pull request closed without merging**
