### PR TITLE
JDK-8280373: Update Xalan serializer / SystemIDResolver to align with JDK-8270492

### PR DESCRIPTION
**Pull request by MBaesken**
After 8270492
https://github.com/openjdk/jdk/commit/78b2c8419bc69436873e6fc9c542480949d140c5
has been pushed, we should adjust src/java.xml/share/classes/com/sun/org/apache/xml/internal/serializer/utils/SystemIDResolver.java getAbsoluteURI to what has been done in 8270492 to src/java.xml/share/classes/com/sun/org/apache/xml/internal/utils/SystemIDResolver.java

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280373](https://bugs.openjdk.java.net/browse/JDK-8280373): Update Xalan serializer / SystemIDResolver to align with JDK-8270492

### Reviewers
 * [Yuri Nesterenko](https://openjdk.java.net/census#yan) (@yan-too - **Reviewer**) ⚠️ Review applies to 666fdee0a71c0a4f8f1b5ff40758c2173d672f1e
 * [Joe Wang](https://openjdk.java.net/census#joehw) (@JoeWang-Java - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7155/head:pull/7155` \
`$ git checkout pull/7155`

Update a local copy of the PR: \
`$ git checkout pull/7155` \
`$ git pull https://git.openjdk.java.net/jdk pull/7155/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7155`

View PR using the GUI difftool: \
`$ git pr show -t 7155`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7155.diff">https://git.openjdk.java.net/jdk/pull/7155.diff</a>

</details>

### CODE REVIEW

**Review by yan-too — APPROVED** [review]
LGTM!

**Comment by AlanBateman** [comment]
It would be useful if Joe Wang can review this, just in case the security changes did not touch this code for some reason.

**Comment by JoeWang-Java** [comment]
Thanks Alan for the reminder. The change looks good. Please add a copyright header and the LastModified tag as the other class did.

**Comment by MBaesken** [comment]
> Thanks Alan for the reminder. The change looks good. Please add a copyright header and the LastModified tag as the other class did.

Hi, I added the header and LastModified.
Best regards, Matthias

**Review by JoeWang-Java — APPROVED** [review]

**Pull request closed without merging**
