### PR TITLE
JDK-8257539: tools/jpackage/windows/WinL10nTest.java unpack.bat failed with Exit code: 1618

### PR DESCRIPTION
**Pull request by andyherrick**
increase retries and timeout increasing in runMsiexecWithRetries

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8257539](https://bugs.openjdk.java.net/browse/JDK-8257539): tools/jpackage/windows/WinL10nTest.java unpack.bat failed with Exit code: 1618

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1676/head:pull/1676`
`$ git checkout pull/1676`

### CODE REVIEW

**Comment by sashamatveev** [comment]
Looks like test failed due to:
[Fatal Error] b.wxl:3:1: XML document structures must start and end within the same entity.
So, I am not sure how increased repeat will help. Do we know why it failed to parse XML?

**Comment by andyherrick** [comment]
> 
> 
> Looks like test failed due to:
> [Fatal Error] b.wxl:3:1: XML document structures must start and end within the same entity.
> So, I am not sure how increased repeat will help. Do we know why it failed to parse XML?

If you scroll down from that error - you can see that that is the expected error and the return code from jpackage is asserted to be 1, and it is asserted that the resulting WinL10NTest.msi does not exist.

the @Parameters for "data" cause instance of this test to be run 8 times with different args.  This instances is expected to fail since allWxlFilesValid is false.
later in the log (https://mach5.us.oracle.com:10060/api/v1/results/mach5-one-jdk-16+26-1740-tier2-20201124-1335-16116386-open_test_jdk_tier2_part2-windows-x64-125-1606226621-1556/log) you can see the timeout, where unpack.bat is run three times with 3 second delay and returns 1618 each time:
**13:58:30.303] TRACE: exec: Execute [cmd /c .\\test.3563aceb\\unpacked-msi\\unpack.bat](3); discard I/O...
[13:58:33.469] TRACE: exec: Done. Exit code: 1618
[13:58:36.492] TRACE: exec: Execute [cmd /c .\\test.3563aceb\\unpacked-msi\\unpack.bat](3); discard I/O...
[13:58:39.636] TRACE: exec: Done. Exit code: 1618
[13:58:42.652] TRACE: exec: Execute [cmd /c .\\test.3563aceb\\unpacked-msi\\unpack.bat](3); discard I/O...
[13:58:45.803] TRACE: exec: Done. Exit code: 1618
[13:58:48.832] ERROR: Expected [0]. Actual [1618]: Check command [cmd /c .\\test.3563aceb\\unpacked-msi\\unpack.bat](3) exited with 0 code
[13:58:48.832] [  FAILED  ] WinL10nTest([name=a.wxl; culture=fr, name=b.wxl; culture=fr](length=2), fr;en-us, null).test; checks=17
[13:58:48.832] [ RUN      ] WinL10nTest([name=a.wxl; culture=fr, name=b.wxl; culture=it, name=c.wxl; culture=fr, name=d.wxl; culture=it](length=4), fr;it;en-us,**

running unpack.bat with msiexec command in it succeed for one test instance after the expected failure, then got 1618 return on the second test instance after the expected failure with the above timeout.

**Comment by andyherrick** [comment]
I converted to draft because somehow merging with master caused a mess - since is simple change in one test file I may create a new branch and new pull request cleanly again.

**Pull request closed without merging**
