### PR TITLE
8306688: Support Windows serialized keystores (SST files)

### PR DESCRIPTION
**Pull request by macarte**
Added ability to load keystores from SST files on Windows.  Example usage:

KeyStore keyStore = KeyStore.getInstance("Windows-SST");
try (FileInputStream fis = new FileInputStream("mykeystore.sst")) {
   keyStore.load(fis, null);
}

Note that its not limited to file streams, it can be any stream.

The feature is behind a runtime flag ("sun.security.mscapi.keyStoreSSTSupport") as the KeyStore must have an input stream, but the JCK tests assume an input stream is optional

tier1 tests for linux/macos/Windows for x86_64

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 22 to be approved (needs to be created)

### Issue
 * [JDK-8306688](https://bugs.openjdk.org/browse/JDK-8306688): Support Windows serialized keystores (SST files) (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14187/head:pull/14187` \
`$ git checkout pull/14187`

Update a local copy of the PR: \
`$ git checkout pull/14187` \
`$ git pull https://git.openjdk.org/jdk.git pull/14187/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14187`

View PR using the GUI difftool: \
`$ git pr show -t 14187`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14187.diff">https://git.openjdk.org/jdk/pull/14187.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14187#issuecomment-1564973973)

### CODE REVIEW

**Comment by seanjmullan** [comment]
This Enhancement requires a CSR as you are introducing a new KeyStore type and system property. RDP 1 for JDK 21 is on June 8, so there is not much time left to review and approve the CSR and code for this issue. I recommend you retarget this to JDK 22.

**Comment by macarte** [comment]
@wangweij - the set and delete will modify the in memory store instance.  However as of now, the store is a nop - historically as setting/removing from the MY/ROOT stores persists the changes (but not the case for in-memory stores using SST).

So I see three ways forward, either (1) leave as is, (2) open the memory store with CERT_STORE_READONLY_FLAG [exceptions will be thrown when trying to modify the store] or (3) support persisting the store to an output stream. 

(1) has value as it allows you to create in memory stores on Windows using windows APIs (vs PKS etc) 

(2) seems limited - but supports my customer needs

(3) expands beyond my current needs, but might offer the most flexibility

In cases (1) and (3): perhaps we should allow in-memory stores that don't need to be loaded from SST, ie create them empty.

**Comment by macarte** [comment]
The SunMSCAPI CKeyStore which implements KeyStoreSpi does nothing in the engineStore, ie. its essential a NOP (No Operation), so right now the dev cannot overwrite original SST file

**Comment by macarte** [comment]
Thanks for the explanation, I understand your point now. I'll make changes to support writing to the SST

**Review by ecki — COMMENTED** [review]
Can a SST file actually contain keys? According to the Powershell page you linked it only exports certs.

**Comment by macarte** [comment]
Removed

From: Weijun Wang ***@***.***>
Date: Monday, December 4, 2023 at 7:01 AM
To: openjdk/jdk ***@***.***>
Cc: Mat Carter ***@***.***>, Mention ***@***.***>
Subject: Re: [openjdk/jdk] 8306688: Support Windows serialized keystores (SST files) (PR #14187)

@macarte<https://github.com/macarte> Please remove the Fix Version/s field of this bug now that it will not go into jdk22.

**Pull request closed without merging**
