### PR TITLE
8323438: Enhance assertions for Windows sync API failures

### PR DESCRIPTION
**Pull request by dholmes-ora**
Using the assertion pattern employed in windows_semaphore.cpp, the other (inadequately checked) calls to WaitForSingleObject are checked more thoroughly so that the actual failure mode is reported.

The only tricky part of these changes is a change to the if/else control flow so that the result of the call can be checked, in one section. Otherwise we just expand existing assertions or guarantees.

Testing: Windows tiers 1-4 sanity

Thanks

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323438](https://bugs.openjdk.org/browse/JDK-8323438): Enhance assertions for Windows sync API failures (**Sub-task** - P4)

### Reviewers
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to [95c92091](https://git.openjdk.org/jdk/pull/17457/files/95c92091b354066068b89494290e25a7c81cdc99)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17457/head:pull/17457` \
`$ git checkout pull/17457`

Update a local copy of the PR: \
`$ git checkout pull/17457` \
`$ git pull https://git.openjdk.org/jdk.git pull/17457/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17457`

View PR using the GUI difftool: \
`$ git pr show -t 17457`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17457.diff">https://git.openjdk.org/jdk/pull/17457.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17457#issuecomment-1894785034)

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
Looks good. Just couple of nits:

- for clarity, should `GetLastError()` be `::GetLastError()`? (I saw both ways in the existing code)
- copyright year needs to be updated.

**Comment by dholmes-ora** [comment]
> Looks good. Just couple of nits:

Thanks for looking at this  @calvinccheung !

>     * for clarity, should `GetLastError()` be `::GetLastError()`? (I saw both ways in the existing code)

There is no need, and many existing usages without the `::`.
 
>     * copyright year needs to be updated.

Fixed. Thanks

**Review by TheShermanTanker — APPROVED** [review]
Not that it means much since this is coming from me, but given this is an easy to review change and is in Windows code I figured why not. Have a +1, especially for the proper %lu format specifiers :)

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. Thanks for fixing this to provide more diagnostic info.

**Comment by dholmes-ora** [comment]
> Not that it means much since this is coming from me, but given this is an easy to review change and is in Windows code I figured why not. Have a +1, especially for the proper %lu format specifiers :)

Extra eyes are always appreciated, especially when we don't have many folk that familiar with Windows code.

I can't take credit for the `%lu` format specifier, as I said I copied the pattern from windows_semaphore.cpp. :)

**Comment by dholmes-ora** [comment]
Thanks for the reviews @dcubed-ojdk  and @TheShermanTanker .

/integrate

**Pull request closed without merging**
