### PR TITLE
8261600: NMT: Relax memory order for updating MemoryCounter and fix racy updating of peak values

### PR DESCRIPTION
**Pull request by zhengyu123**
Currently, MemoryCounter is updated with default memory_order_conservative, it is too strong for updating a counter.

Also, updating peak values with regular assignment, which is racy and broken.

- [x] hotspot_nmt on Linux x86_64 and aarch64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261600](https://bugs.openjdk.java.net/browse/JDK-8261600): NMT: Relax memory order for updating MemoryCounter and fix racy updating of peak values

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2527/head:pull/2527`
`$ git checkout pull/2527`

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Zhengyu,

This seems okay. 

Thanks,
David

**Review by shipilev — APPROVED** [review]
This looks fine to me too.

**Comment by zhengyu123** [comment]
Thanks for reviewing, @dholmes-ora and @shipilev

**Pull request closed without merging**
