### PR TITLE
8345110: RISC-V: Optimize and and clean up byte reverse assembler routines

### PR DESCRIPTION
**Pull request by RealFYang**
Hi, Could you please help review this change?

MacroAssembler routines `revb_w` and `revb_w_w` will emit 32 and 17 instructions respectively without Zbb.

Major changes:
1. There is no need for `revb_w` to reverse bytes for each 32-bit word in the 64-bit register.
   All the callers only care about the lower 32-bit word. This reimplement `revb_w` so that it only
   reverses bytes in lower 32-bit word and sign-extends the result (14 instructions). This makes `revb_w_w` duplicate.
2. Removed some assembler routines that are unused or become unnecessary (`revb_h`, `revb_h_helper`, `revb_h_h`, `revb_w_w`).
3. Adapted callers of these removed assembler routines in file `riscv_b.ad` to emit Zbb instructions directly.

Will look into `revb_h_h_u` and `revb_h_w_u` after this change. Seems to me they could be factored out as well.

Testing on linux-riscv64 platform:
- [x] tier1 (release)
- [x] hotspot:tier1 (fastdebug)
- [x] non-trivial benchmark workloads like Dacapo, SpecJBB, Renaissance (release)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345110](https://bugs.openjdk.org/browse/JDK-8345110): RISC-V: Optimize and and clean up byte reverse assembler routines (**Enhancement** - P4)

### Reviewers
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**) Review applies to [f737241a](https://git.openjdk.org/jdk/pull/22410/files/f737241a837c5e8cdc509d84ff92e85e627fc6dc)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22410/head:pull/22410` \
`$ git checkout pull/22410`

Update a local copy of the PR: \
`$ git checkout pull/22410` \
`$ git pull https://git.openjdk.org/jdk.git pull/22410/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22410`

View PR using the GUI difftool: \
`$ git pr show -t 22410`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22410.diff">https://git.openjdk.org/jdk/pull/22410.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22410#issuecomment-2505038786)
</details>

### CODE REVIEW

**Review by Hamlin-Li — COMMENTED** [review]
Thanks for cleanup!
Not sure if I understand correctly, just have some questions, in upstream code at [1] [2], seems they both not expect a signed-extending?

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/templateTable_riscv.cpp#L1935
```
  // set counter
  __ lwu(x11, Address(x9, BytesPerInt));
  __ revb_w(x11, x11);
  __ j(loop_entry);
  // table search
  __ bind(loop);
  __ shadd(t0, x11, x9, t0, 3);
```
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/templateTable_riscv.cpp#L2009
```
  // Initialize i & j
  __ mv(i, zr);                            // i = 0
  __ lwu(j, Address(array, -BytesPerInt)); // j = length(array)

  // Convert j into native byteordering
  __ revb_w(j, j);

```

**Review by robehn — APPROVED** [review]
Thanks!

I liked that you used rev8 directly in AD because it makes it very clear that we do not clobber t1. (as it otherwise it is one of the default registers)

As all uses of revb_w use dst == src, please consider a helper version which only needs one registers passed.
I.e. "__ revb_w(temp);"

**Comment by RealFYang** [comment]
> Thanks for cleanup! Not sure if I understand correctly, just have some questions, in upstream code at [1] [2], seems they both not expect a signed-extending?

Sorry, I should have explained that in the PR description. For these two use cases, we are are loading the 32-bit `npairs` which are specified to be greater than or equal to 0 by the JVM spec [1]. So there isn't no difference whether we use sign-extension or zero-extension. Hope that answers the question :-)

[1] https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.lookupswitch

**Comment by Hamlin-Li** [comment]
> > Thanks for cleanup! Not sure if I understand correctly, just have some questions, in upstream code at [1] [2], seems they both not expect a signed-extending?
> 
> Sorry, I should have explained that in the PR description. For these two cases, we are are loading the 32-bit `npairs` of bytecode `lookupswitch` which are specified to be greater than or equal to 0 by the JVMS [1]. So there is no difference whether we use sign-extension or zero-extension. Hope that answers the question :-)
> 
> [1] https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.lookupswitch

I see, I guessed that might be the answer.
It might be helpful to add some comment in these places to state clearly what we expect, because `revb_w` now has the comment `reverse bytes in lower word, sign-extend`.

**Comment by RealFYang** [comment]
> > > Thanks for cleanup! Not sure if I understand correctly, just have some questions, in upstream code at [1] [2], seems they both not expect a signed-extending?
> > 
> > 
> > Sorry, I should have explained that in the PR description. For these two cases, we are are loading the 32-bit `npairs` of bytecode `lookupswitch` which are specified to be greater than or equal to 0 by the JVMS [1]. So there is no difference whether we use sign-extension or zero-extension. Hope that answers the question :-)
> > [1] https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.lookupswitch
> 
> I see, I guessed that might be the answer. It might be helpful to add some comment in these places to state clearly what we expect, because `revb_w` now has the comment `reverse bytes in lower word, sign-extend`.

Make sense. I have just added some code comments to help clarify. Thanks for the suggestions.

**Comment by RealFYang** [comment]
@Hamlin-Li @robehn : Thanks for the review!
/integrate

**Pull request closed without merging**
