### PR TITLE
8284933: Improve debug in jdk.crypto.cryptoki

### PR DESCRIPTION
**Pull request by XueleiFan**
Hi,

May I have the simple update reviewed?

In the jdk.crypto.cryptoki module implementation, some of the debug information could be calculated even if the debug is not enabled, which is not resource friendly.

Thanks,
Xuelei

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284933](https://bugs.openjdk.java.net/browse/JDK-8284933): Improve debug in jdk.crypto.cryptoki

### Reviewers
 * [Valerie Peng](https://openjdk.java.net/census#valeriep) (@valeriepeng - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8277/head:pull/8277` \
`$ git checkout pull/8277`

Update a local copy of the PR: \
`$ git checkout pull/8277` \
`$ git pull https://git.openjdk.java.net/jdk pull/8277/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8277`

View PR using the GUI difftool: \
`$ git pr show -t 8277`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8277.diff">https://git.openjdk.java.net/jdk/pull/8277.diff</a>

</details>

### CODE REVIEW

**Review by seanjmullan — COMMENTED** [review]
DEBUG is final, so it is not intended to be configurable at runtime. I'm ok with this, but will defer to someone else more familiar with this code for approval.

**Comment by valeriepeng** [comment]
With this change, I see no reason to have debug(...) method. May as well just remove it and simply do a "System.out.println(...);"?

**Comment by XueleiFan** [comment]
> With this change, I see no reason to have debug(...) method. May as well just remove it and simply do a "System.out.println(...);"?

Yes, that's my preferred style as well.  Updated.

**Review by valeriepeng — APPROVED** [review]
Looks good to me. Thanks~

**Pull request closed without merging**
