### PR TITLE
8254882: ZGC: Use static_assert instead of guarantee

### PR DESCRIPTION
**Pull request by pliden**
The ZMarkStackAllocator uses guarantee(), which can be turned into static_assert(). I took the opportunity to also change three exsisting uses of STATIC_ASSERT to static_assert, and adjust some neighbouring "typedefs" to "using".

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254882](https://bugs.openjdk.java.net/browse/JDK-8254882): ZGC: Use static_assert instead of guarantee

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 61a60d44c83d82e7a169ead72c6e8c14dda5c8f3
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to b2e1a7463616cb259395eba1a1b6ad8c607d556c

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/696/head:pull/696`
`$ git checkout pull/696`

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Comment by pliden** [comment]
Pushed an update which adds messages to the static_asserts, since I noticed that message-less static_assert is a C++17 feature. As a side-note, I noticed that vm_version_linux_aarch64.cpp contains a few message-less static_asserts, but gcc doesn't seem to warn about it.

**Review by kimbarrett — APPROVED** [review]
Looks better - sorry I missed that.  Do any of Oracle's supported compiler configurations complain?  If not, I'm sure this will keep happening.

**Comment by pliden** [comment]
@kimbarrett Yes, both clang and msvc complain, but not gcc.

**Pull request closed without merging**
