### PR TITLE
8253923: C2 doesn't always run loop opts for compilations that include loops

### PR DESCRIPTION
**Pull request by rwestrel**
/cc hotspot-compiler

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (hs/tier1 serviceability)](https://github.com/rwestrel/jdk/runs/1207921102)

### Issue
 * [JDK-8253923](https://bugs.openjdk.java.net/browse/JDK-8253923): C2 doesn't always run loop opts for compilations that include loops

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 6ca8b0b43039ff60dee718a5d5ccb5ef374484f3
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/478/head:pull/478`
`$ git checkout pull/478`

### CODE REVIEW

**Comment by rwestrel** [comment]
I noticed that c2 wouldn't always run loop opts when the compilation include loops. Compile::has_loops() is what controls whether loop opts are executed. It's initially false and then set to true as parsing finds new loops. The flag is updated with the result ciMethod::has_loops() of inlined method but:

- with bimorphic inlining, the has_loops flag is not set based the methods that are actually inlined but from the virtual method the call resolve statically to.

- there's a least one intrinsics that's predicated and falls back to inlining of the method, in which case the has_loops() is not set.

- sometimes loops are built manually rather than by parsing bytecodes

- when the backedge is a branch of a switch or an exception edge, ciMethod::has_loops() doesn't return true

**Review by neliasso — APPROVED** [review]
Thanks for fixing! 

Extra credit for the verification that will catch this problem type in the future.

Reviewed.

**Comment by rwestrel** [comment]
Hi Nils,

> Reviewed.

Thanks for reviewing. I actually made this a draft PR because I realized when I created it that there was a simple fix (which is to set the has_loops flag when parsing of a method starts). Can you take a look at the new change?

**Comment by neliasso** [comment]
> Thanks for reviewing. I actually made this a draft PR because I realized when I created it that there was a simpler fix (which is to set the has_loops flag when parsing of a method starts). Can you take a look at the new change?

Where do I find the new change? I see no updated files.

**Comment by rwestrel** [comment]
> > Thanks for reviewing. I actually made this a draft PR because I realized when I created it that there was a simpler fix (which is to set the has_loops flag when parsing of a method starts). Can you take a look at the new change?
> 
> Where do I find the new change? I see no updated files.

I updated the change in place (force pushed).
https://openjdk.github.io/cr/?repo=jdk&pr=478&range=00 is the new change.

**Comment by neliasso** [comment]
> I updated the change in place (force pushed).
> https://openjdk.github.io/cr/?repo=jdk&pr=478&range=00 is the new change.

That looks exactly like the code I reviewed.

**Comment by rwestrel** [comment]
> > I updated the change in place (force pushed).
> > https://openjdk.github.io/cr/?repo=jdk&pr=478&range=00 is the new change.
> 
> That looks exactly like the code I reviewed.

The initial change would set the has_loops flag before inlining. The current one sets it when a new method is parsed (so once inlining has happened). In any case, I take it you're fine with the current change. Thanks for the review.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by rwestrel** [comment]
> Looks good to me.

Thanks for the review.

**Pull request closed without merging**
