### PR TITLE
8297020: Rename GrowableArray::on_stack

### PR DESCRIPTION
**Pull request by stefank**
GrowableArray::on_stack is confusing. It returns true if the backing elements are allocated in the stack's resource area. We typically call this resource allocations, not stack allocations. I propose that we rename it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297020](https://bugs.openjdk.org/browse/JDK-8297020): Rename GrowableArray::on_stack

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11161/head:pull/11161` \
`$ git checkout pull/11161`

Update a local copy of the PR: \
`$ git checkout pull/11161` \
`$ git pull https://git.openjdk.org/jdk pull/11161/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11161`

View PR using the GUI difftool: \
`$ git pr show -t 11161`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11161.diff">https://git.openjdk.org/jdk/pull/11161.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
+1

**Comment by stefank** [comment]
Thanks for the reviews!

**Comment by tstuefe** [comment]
> Thanks for the reviews!

Thanks for doing all this!

**Pull request closed without merging**
