### PR TITLE
JDK-8272984: javadoc support for SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a relatively simple patch to support the standard SOURCE_DATE_EPOCH environment variable, used by those who are interested in reproducible builds. (See https://reproducible-builds.org)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed
- [ ] Change requires a CSR request to be approved

### Issues
 * [JDK-8272984](https://bugs.openjdk.java.net/browse/JDK-8272984): javadoc support for SOURCE_DATE_EPOCH
 * [JDK-8279048](https://bugs.openjdk.java.net/browse/JDK-8279048): javadoc support for SOURCE_DATE_EPOCH (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6905/head:pull/6905` \
`$ git checkout pull/6905`

Update a local copy of the PR: \
`$ git checkout pull/6905` \
`$ git pull https://git.openjdk.java.net/jdk pull/6905/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6905`

View PR using the GUI difftool: \
`$ git pr show -t 6905`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6905.diff">https://git.openjdk.java.net/jdk/pull/6905.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
I think this issue will require wider discussion because all previous investigation into this topic have concluded with the JDK not reading the env variable directly, instead providing an way to configure the timestamp. For the jar and jmod tools the option --date is used to specify a fixed timestamp for entries when reproducible builds are required. The Properties.store API specifies to read the system property java.properties.date so that date/timestamp in the comment uses a fixed date.

**Comment by jonathan-gibbons** [comment]
> I think this issue will require wider discussion because all previous investigation into this topic have concluded with the JDK not reading the env variable directly, instead providing a way to configure the timestamp. For the jar and jmod tools the option --date is used to specify a fixed timestamp for entries when reproducible builds are required. The Properties.store API specifies to read the system property java.properties.date so that date/timestamp in the comment uses a fixed date.

Noted.

**Comment by hns** [comment]
I think this PR should be closed as it has been superseded by #7171.

**Pull request closed without merging**
