### PR TITLE
8257924: Use full path when running external executable from jpackage

### PR DESCRIPTION
**Pull request by sashamatveev**
Changed all external executables to run via full path to avoid potential issues.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257924](https://bugs.openjdk.java.net/browse/JDK-8257924): Use full path when running external executable from jpackage

### Reviewers
 * [Andy Herrick](https://openjdk.java.net/census#herrick) (@andyherrick - **Reviewer**)
 * [Alexey Semenyuk](https://openjdk.java.net/census#asemenyuk) (@alexeysemenyukoracle - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1710/head:pull/1710`
`$ git checkout pull/1710`

### CODE REVIEW

**Review by andyherrick — COMMENTED** [review]
as long as your sure these are always in /usr/bin this is fine.
If there is any chance of them being somewhere else instead we need a findTool type mechanism

**Comment by alexeysemenyukoracle** [comment]
What if users would like to use not the default tools with jpackage?

**Comment by sashamatveev** [comment]
I did not found any information if it is possible for these tools to locate somewhere else. These tools a part of macOS, so I do not think that it is possible to use some non-default tools and I am not aware that such substitute tools even exist.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Review by andyherrick — APPROVED** [review]

**Pull request closed without merging**
