### PR TITLE
8287520: Shrink x86_32 problemlists after JDK-8287437

### PR DESCRIPTION
**Pull request by shipilev**
[JDK-8287137](https://bugs.openjdk.java.net/browse/JDK-8287137) added a bunch of tests into problemlist. Those lists basically exclude every test that runs with --enable-preview. [JDK-8287437](https://bugs.openjdk.java.net/browse/JDK-8287437) makes it better: it only disables Loom parts, even with --enable-preview. This allows testing x86_32 on other preview features and avoids accidental bug slippage in non-Loom code paths. We can and should shrink the problem lists now.

Additional testing:
 - [x] Removed tests with Linux x86_32 fastdebug; mostly pass, some non-Loom failures
 - [x] Linux x86_32 fastdebug `tier1`
 - [x] GHA run

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287520](https://bugs.openjdk.java.net/browse/JDK-8287520): Shrink x86_32 problemlists after JDK-8287437

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [7c90ead6](https://git.openjdk.java.net/jdk/pull/8946/files/7c90ead6e99db53e9a569c80af4d8d0d574108f7)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8946/head:pull/8946` \
`$ git checkout pull/8946`

Update a local copy of the PR: \
`$ git checkout pull/8946` \
`$ git pull https://git.openjdk.java.net/jdk pull/8946/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8946`

View PR using the GUI difftool: \
`$ git pr show -t 8946`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8946.diff">https://git.openjdk.java.net/jdk/pull/8946.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Open for reviews. The test failures on Windows x64 are known and are solved separately.

**Review by AlanBateman — APPROVED** [review]
This looks okay.  If we get PR8939 in then it should be possible to do more clear out of the exclude lists.

**Pull request closed without merging**
