### PR TITLE
8261250: Dependencies: Remove unused dependency types

### PR DESCRIPTION
**Pull request by iwanowww**
Remove support of unused dependency types from Dependencies.

Testing: 
- [x] hs-precheckin-comp, hs-tier1, hs-tier2.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261250](https://bugs.openjdk.java.net/browse/JDK-8261250): Dependencies: Remove unused dependency types

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2431/head:pull/2431`
`$ git checkout pull/2431`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Nice cleanup, looks good!

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Tobias.

**Pull request closed without merging**
