### PR TITLE
JDK-8290010: IGV: Fix UndoRedo Action

### PR DESCRIPTION
**Pull request by tobiasholenstein**
# Problem
- The history of the Undo Action did not start at zero when opening a new graph.
- In the "Show sea of nodes" view you could press Undo once before doing any changes. 
- In the "Show control view graph" you could even go back many times when opening a new graph, ending up in wired state of the graph. 
- Selecting a node should not be added to the history. You could select X different nodes in a row and then go back X times in history without that anything changed. 

# Overview UndoRedo
Different `ChangedEvent<DiagramViewModel>` events are fired in `DiagramViewModel` that trigger the `DiagramScene` to update its state. After those updates `DiagramScene` calls  `addUndo()` to save the new state of the `DiagramViewModel` as well as the scrolling position of the `DiagramScene` in a `DiagramUndoRedo` object. `undo()` / `redo()` can then be used to restore the saved state.

One problem was that selecting nodes triggered a `ChangedEvent<DiagramViewModel>` event that caused a recording to the history but the selection itself was not part of the saved state. Another problem was that switching between different views (CFG view, sea-of-nodes view) as well as applying filters also triggered an `addUndo()` - The recording of filters and view switches is however not implemented. 

# Solution
We now only record when the graph itself changes (not the view) - like when opening a new graph or creating a difference graph. And we also record changes in the selection of the visible nodes. 

We refactored the `ChangedEvent<DiagramViewModel>` events in `DiagramViewModel`: 
- `graphChangedEvent` now is fired when the graph changes and triggers an `addUndo()`
- `hiddenNodesChangedEvent` is now fired when the selection of visible nodes changes and also triggers an `addUndo()`

`DiagramUndoRedo` previously stored a deep copy of the `DiagramViewModel` for every datapoint in the history. Besides using a lot of memory, most of the stored objects were redundant or not used. Now, we introduced a new `ModelState` object that stores the id of the visible nodes in `Set<Integer> hiddenNodes` as well as the opened graph. For the graph we only need `int firstPos` and `int secondPos` which indicate the position of the difference graph within the group. If we don't use a difference graph `firstPos` == `secondPos`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290010](https://bugs.openjdk.org/browse/JDK-8290010): IGV: Fix UndoRedo Action

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10813/head:pull/10813` \
`$ git checkout pull/10813`

Update a local copy of the PR: \
`$ git checkout pull/10813` \
`$ git pull https://git.openjdk.org/jdk pull/10813/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10813`

View PR using the GUI difftool: \
`$ git pr show -t 10813`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10813.diff">https://git.openjdk.org/jdk/pull/10813.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — CHANGES_REQUESTED** [review]
I gave this a quick test and clicking on a different phase and then reverting back and forth to the previous phase via the undo/redo buttons does not work anymore after doing it twice.

**Review by TobiHartmann — CHANGES_REQUESTED** [review]
In general, it seems that when going backwards (undo) multiple steps, going forwards (redo) does not work anymore after one step forward.

**Comment by tobiasholenstein** [comment]
> In general, it seems that when going backwards (undo) multiple steps, going forwards (redo) does not work anymore after one step forward.

Hi @TobiHartmann 
Thanks for trying it out and reporting. It should be fixed now!

The problem was that during `undo()`/ `redo()` we recorded new states to the history with `addUndo()`
The fix is to disable `addUndo()` while performing `undo()`/ `redo()`

When we now call `redo()` should we have now the following behavior:
1. (1)->(2)->**(3)**   &rarr;  _undo (2), redo (-)_
- we select _undo (2)_
2. (1)->**(2)**   &rarr;   _undo (1), redo (3)_
- if we now redo (3) we end up in 1.
- if we change the selection or the graph we override state (3) in the history and end up in 3.
3. (1)->(2)->**(4)** &rarr;  _undo (2), redo (-)_
- we select _undo (2)_
4. (1)->**(2)**   &rarr;   _undo (1), redo (4)_
- state (3) cannot be reached anymore because we rewrote the history

(Nr) represents a saved state, -> is a recording with `addUndo()`, right of  &rarr; are the possible actions at the **bold** state

**Review by TobiHartmann — APPROVED** [review]
Thanks, the new version works like a charm. Looks good to me.

**Review by robcasloz — APPROVED** [review]
Thanks for making the undo/redo functionality usable!

**Comment by tobiasholenstein** [comment]
Thanks @TobiHartmann and @robcasloz for the reviews!

/integrate

**Pull request closed without merging**
