### PR TITLE
8279622: C2: miscompilation of map pattern as a vector reduction

### PR DESCRIPTION
**Pull request by robcasloz**
The node reduction flag (`Node::Flag_is_reduction`) is only valid as long as the node remains within the reduction loop in which it was originally marked. This changeset ensures that reduction nodes are unmarked as such if they are extracted out of their associated reduction loop by the peel/main/post loop transformation (`PhaseIdealLoop::insert_pre_post_loops()`). This prevents SLP from wrongly vectorizing, as parallel reductions, outer non-reduction loops to which reduction nodes have been extracted. A more detailed analysis of the failure is available in the [JBS bug report](https://bugs.openjdk.java.net/browse/JDK-8279622).

The issue could be alternatively fixed at the IGVN level by unmarking reduction nodes as soon as they are decoupled from their corresponding phi and counted loop nodes, but the fix proposed here is simpler and less intrusive.

The changeset also introduces an assertion at the use point (`SuperWord::transform_loop()`) to check that loops containing reduction nodes are marked as reductions. This invariant could be alternatively placed together with other assertions under `-XX:+VerifyLoopOptimizations`, but [this option is known to be broken](https://bugs.openjdk.java.net/browse/JDK-8173709).

IR verification using the IR test framework is not feasible for the proposed test case, since the failure is triggered on a OSR compilation, [for which IR verification does not seem to be supported](https://github.com/openjdk/jdk/blob/e7c3b9de649d4b28ba16844e042afcf3c89323e5/test/hotspot/jtreg/compiler/lib/ir_framework/driver/irmatching/parser/Line.java#L56-L58). The assertion described above compensates this limitation.

##### Functionality

- hs-tier1-3 (windows-x64, linux-x64, linux-aarch64, and macosx-x64; release and debug mode).
- hs-tier4-7 (linux-x64; debug mode).

##### Performance

- No significant regression on a set of standard benchmark suites (DaCapo, SPECjbb2015, SPECjvm2008, ...) and on windows-x64, linux-x64, linux-aarch64, and macosx-x64.
- No significant difference in generated number of vector instructions when comparing the output of `compiler/vectorization` and `compiler/loopopts/superword` tests using `-XX:+TraceNewVectors` on linux-x64.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279622](https://bugs.openjdk.java.net/browse/JDK-8279622): C2: miscompilation of map pattern as a vector reduction

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8464/head:pull/8464` \
`$ git checkout pull/8464`

Update a local copy of the PR: \
`$ git checkout pull/8464` \
`$ git pull https://git.openjdk.java.net/jdk pull/8464/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8464`

View PR using the GUI difftool: \
`$ git pr show -t 8464`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8464.diff">https://git.openjdk.java.net/jdk/pull/8464.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
That looks good to me.

**Comment by robcasloz** [comment]
> That looks good to me.

Thanks for the review, Roland!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks for reviewing, Vladimir!

**Review by TobiHartmann — APPROVED** [review]
Nice analysis, looks good to me!

**Comment by robcasloz** [comment]
> Nice analysis, looks good to me!

Thanks, Tobias!

**Pull request closed without merging**
