### PR TITLE
8287091: aarch64 : guarantee(val < (1ULL << nbits)) failed: Field too big for insn

### PR DESCRIPTION
**Pull request by theRealAph**
This is fallout from the patch for JDK-8285923.

The root cause of this bug is that there is a template definition of `cmp(register, immediate)` but there is not a template definition of `cmn(register, immediate)`. Given that we are close to rampdown, this patch fixes the bug in the most minimal way possible, by using `adds(zr, register, immediate)`, which correctly handles 64-bit operands.

In the next release cycle we should tidy up `cmn()` in the same way that was done for JDK-8206895.

Alternatively, we could back out JDK-8285923. I'd rather not, given that it fixes a real (if latent) bug, but if needs be I'll do so.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8287091](https://bugs.openjdk.java.net/browse/JDK-8287091): aarch64 : guarantee(val < (1ULL << nbits)) failed: Field too big for insn

### Reviewers
 * [Nick Gasson](https://openjdk.java.net/census#ngasson) (@nick-arm - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8845/head:pull/8845` \
`$ git checkout pull/8845`

Update a local copy of the PR: \
`$ git checkout pull/8845` \
`$ git pull https://git.openjdk.java.net/jdk pull/8845/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8845`

View PR using the GUI difftool: \
`$ git pr show -t 8845`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8845.diff">https://git.openjdk.java.net/jdk/pull/8845.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
All right, so we just store to the result to `zr`, which is effectively no-op, and ride on the updated flags of `add*s*`. Looks fine.

**Comment by nick-arm** [comment]
> All right, so we just store the result to `zr`, which is effectively no-op, and ride on the updated flags done by `add*s*`. 

It's actually the same instruction: `cmn reg, imm` is an alias for `adds zr, reg, imm`.

**Comment by shipilev** [comment]
> > All right, so we just store the result to `zr`, which is effectively no-op, and ride on the updated flags done by `add*s*`.
> 
> It's actually the same instruction: `cmn reg, imm` is an alias for `adds zr, reg, imm`.

Nice. Even better then.

**Pull request closed without merging**
