### PR TITLE
8270321: Startup regressions in 18-b5 caused by JDK-8266310

### PR DESCRIPTION
**Pull request by sercher**
Dear colleagues,

Please review the patch that replaces the lambdas with anonymous classes which solves the startup time regression as shown below.

I attached the Bytestacks flamegraphs for both original (regression) and fixed versions. The flamegraphs clearly show the lambdas were causing the performance issue.

[bytestacks_flamegraphs.zip](https://github.com/openjdk/jdk/files/6870446/bytestacks_flamegraphs.zip)

Although the proposed JDK-8270321 patch fixes the startup time (it might appear even better than it was before the regression was introduced, i.e. before JDK-8266310) and generally fixes the footprint regression, it may increase MaxRSS slightly compared to the version before JDK-8266310, which is shown in the below graphs. (updated)

StartupTime2

MaxRSS

(update: added ZGC graphs)

StartupTime_ZGC

MaxRSS_ZGC

I additionally include the heap objects histograms to show the change does not increase the total live objects size significantly with only 1000 bytes the total difference, namely 1116128 bytes in 25002 live objects after the proposed fix JDK-8270321 compared to 1115128 bytes in 24990 objects in the version with the original patch reverted (i.e. before JDK-8266310).

[histograms.zip](https://github.com/openjdk/jdk/files/6870457/histograms.zip)

The patch was tested w/hotspot/tier1/tier2 test groups.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270321](https://bugs.openjdk.java.net/browse/JDK-8270321): Startup regressions in 18-b5 caused by JDK-8266310

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4893/head:pull/4893` \
`$ git checkout pull/4893`

Update a local copy of the PR: \
`$ git checkout pull/4893` \
`$ git pull https://git.openjdk.java.net/jdk pull/4893/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4893`

View PR using the GUI difftool: \
`$ git pr show -t 4893`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4893.diff">https://git.openjdk.java.net/jdk/pull/4893.diff</a>

</details>

### CODE REVIEW

**Comment by forax** [comment]
I don't understand your analysis, you are testing the startup time with -Xint which disable JITs, but there is no mention of -Xint in the bug report.
It's obvious to me that there is a regression with -Xint given that the lambda creation is using invokedynamic which is only optimizable by JITs. 

I think you should first try to reproduce the issue with the correct flags and then follow the advice from Mandy on how to implement the fix. Using an anonymous class may introduce more allocation than using a lambda once the code is JITed.

**Comment by sercher** [comment]
Hi Rémi,
> 
> I don't understand your analysis, you are testing the startup time with -Xint which disable JITs, but there is no mention of -Xint in the bug report.
> It's obvious to me that there is a regression with -Xint given that the lambda creation is using invokedynamic which is only optimizable by JITs.

I apologize, perhaps I wasn't quite clear describing the analysis. Also, there was a faulty picture, -Xint was only used to grab the opcode traces to build the flamegraphs. I replaced the faulty image and posted additional graphs with -XX:+UseZGC.
Performance (startup) testing, as well as the live objects dumps were obtained with JIT enabled and with G1GC and ZGC. Would you think more data is needed with -Xint? (in addition to the flamegraphs which are obtained with -Xint)

> 
> I think you should first try to reproduce the issue with the correct flags and then follow the advice from Mandy on how to implement the fix.

In my opinion removing computeXXX methods defeats the purpose of the entire deadlock fix. It is sufficient to avoid using lambdas in order not to trigger the method handles initialization, which is what Mandy Chung is really suggesting in the first note in [JBS](https://bugs.openjdk.java.net/browse/JDK-8270321).

> 
> Using an anonymous class may introduce more allocation than using a lambda once the code is JITed.

I provided live objects dumps after noop.jar has been loaded with JIT enabled. Please see the attached histograms. The difference is always the same after full GC (1000 bytes in 12 objects compared to pre JDK-8266310 version tested w/G1) and it doesn't change with subsequent executions. The patch resolves the memory regression as you may observe in RSS graphs and heap dumps. Please see 'fixed.histogram' in comparison with the object dump before the fix (post JDK-8266310) in 'original.histogram'.

**Comment by AlanBateman** [comment]
> I don't understand your analysis, you are testing the startup time with -Xint which disable JITs, but there is no mention of -Xint in the bug report.
> It's obvious to me that there is a regression with -Xint given that the lambda creation is using invokedynamic which is only optimizable by JITs.

Eric Caspole (the submitter) may be able to share more data but the startup regression looks plausible given that this code executes early in the startup.

**Comment by mlchung** [comment]
NativeLibraries was called early during VM startup and the startup benchmark is just a Noop.   So the lambda creation by NativeLibraries is likely still running in interpreted mode.

Looks like replacing it with an anonymous class may be an alternative.  I ran a few startup benchmarks on linux x64 with this patch.   It does show that the startup regression is fixed and also the footprint benchmark I included does not show any regression.

**Comment by forax** [comment]
Hi Sergey,
thanks for the explanation, i don't think there is a need for more data with -Xint.

Using anonymous classes instead of lambdas is good for me.

**Review by mlchung — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]

**Comment by voitylov** [comment]
Thanks Sergey for dealing with this while I was on vacation, and sorry for causing this regression! Looks good (not a reviewer).

**Pull request closed without merging**
