### PR TITLE
8262442: (windows) Use all proxy configuration sources when java.net.useSystemProxies=true

### PR DESCRIPTION
**Pull request by djelinski**
With this patch DefaultProxySelector first attempts to use proxy config autodetection (http://wpad/wpad.dat) when that is configured and available.
If proxy config autodetection is unavailable, selector tries to use configured proxy script (again, if configured and available)
If both the above options fail, selector uses the configured proxy.

Verified on Windows 10 that:
- when `fAutoDetect` is true, http://wpad/wpad.dat refers to an existing file, the file has correct syntax and returns a proxy, that proxy is used
- when `fAutoDetect` is true, but the autoconfig file is not available / unusable for any reason, selector fails over to the next configured method
- when `lpszAutoConfigUrl` is set and usable, the proxy returned is used
- when `lpszAutoConfigUrl` is not set or unusable, selector fails over to next method
- when `lpszProxy` is configured, that proxy is used
- otherwise selector uses direct connection

The proxy configuration scripts are cached on system level, so testing (alternating between good and broken autoconfig script) may require waiting for the caches to invalidate.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262442](https://bugs.openjdk.java.net/browse/JDK-8262442): (windows) Use all proxy configuration sources when java.net.useSystemProxies=true

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5995/head:pull/5995` \
`$ git checkout pull/5995`

Update a local copy of the PR: \
`$ git checkout pull/5995` \
`$ git pull https://git.openjdk.java.net/jdk pull/5995/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5995`

View PR using the GUI difftool: \
`$ git pr show -t 5995`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5995.diff">https://git.openjdk.java.net/jdk/pull/5995.diff</a>

</details>

### CODE REVIEW

**Comment by djelinski** [comment]
No automatic tests; to test this manually I used 2 proxy autoconfig files of form:
```
function FindProxyForURL(url, host) {
  if (url.includes("example")) {
    return "PROXY 10.4.5.6:8192";
  } else {
    return "DIRECT";
  }
}
```
one named `wpad.dat`, other named `proxy.pac`, returning different proxy addresses so that I could figure out which one was used. These files were served by a http server running on localhost, conveniently set up with `python -m http.server 80`.
Next, I added the following line to `c:\Windows\System32\drivers\etc\hosts`:
```
127.0.0.1 wpad
```
Next, I used the little Java program found in [JDK-8262442](https://bugs.openjdk.java.net/browse/JDK-8262442) to test what ProxySelector returned with different combinations of proxy configuration options.

**Comment by djelinski** [comment]
Any comments on this one?

**Comment by dfuch** [comment]
See my comment on https://github.com/openjdk/jdk/pull/6090#issuecomment-981595461
Again - this looks like a good fix - but we would fill more comfortable integrating it in the early development phase of JDK 19, in a few days...

**Comment by djelinski** [comment]
bump

**Comment by dfuch** [comment]
Hi Daniel - could you update the second copyright year in the file header to 2022?
Thanks!

**Review by dfuch — APPROVED** [review]

**Comment by djelinski** [comment]
Thanks!

/integrate

**Pull request closed without merging**
