### PR TITLE
8253271: vm_version_x86.hpp should not include globals_extension.hpp

### PR DESCRIPTION
**Pull request by iklam**
[vm_version_x86.hpp](https://github.com/openjdk/jdk/blob/b87a1599674b8a73f489330decf051d1be9e9fba/src/hotspot/cpu/x86/vm_version_x86.hpp#L30) is a popular header file (which in itself is a problem but I'll fix that in a separate RFE) and it unnecessarily includes globals_extension.hpp.

Removing this dependency reduces the number of cpp files that include globals_extension.hpp from 814 to 67.

I need to fix cpp files that use macros like FLAG_SET_ERGO but forgot to include  globals_extension.hpp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253271](https://bugs.openjdk.java.net/browse/JDK-8253271): vm_version_x86.hpp should not include globals_extension.hpp

### Reviewers
 * @JohnTortugo (no known github.com user name / role) ⚠️ Review applies to a5a2f03ebe9644467db63d27f8682a9a9ec9b161
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to a5a2f03ebe9644467db63d27f8682a9a9ec9b161

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/217/head:pull/217`
`$ git checkout pull/217`

### CODE REVIEW

**Review by JohnTortugo — APPROVED** [review]
LGTM :-)

**Review by dholmes-ora — APPROVED** [review]
Looks good - and trivial assuming all builds are good.

**Comment by iklam** [comment]
[ce1508a](https://github.com/openjdk/jdk/pull/217/commits/ce1508afeb9089bfe5e276eb06de34b9bfe0459a) passed tiers1/2 in our CI pipeline. I also tested with a local build with shenandoah enabled.

**Pull request closed without merging**
