### PR TITLE
8266510: Nimbus JTree default tree cell renderer does not use selected text color

### PR DESCRIPTION
**Pull request by trebari**
Please review the following fix for JDK-18.
This is revert of the fix for  nimbus jtree renderer properties persist across L&F(https://bugs.openjdk.java.net/browse/JDK-8249674), This fixed caused nimbus jtree default tree cell renderer to not use the selected text color, which was white originally and changed to black after the fix. Reverted the change to match original behaviour.

Tested on MacOS , Windows and Linux.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266510](https://bugs.openjdk.java.net/browse/JDK-8266510): Nimbus JTree default tree cell renderer does not use selected text color

### Reviewers
 * [Prasanta Sadhukhan](https://openjdk.java.net/census#psadhukhan) (@prsadhuk - **Reviewer**)
 * [Pankaj Bansal](https://openjdk.java.net/census#pbansal) (@pankaj-bansal - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4903/head:pull/4903` \
`$ git checkout pull/4903`

Update a local copy of the PR: \
`$ git checkout pull/4903` \
`$ git pull https://git.openjdk.java.net/jdk pull/4903/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4903`

View PR using the GUI difftool: \
`$ git pr show -t 4903`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4903.diff">https://git.openjdk.java.net/jdk/pull/4903.diff</a>

</details>

### CODE REVIEW

**Review by prsadhuk — APPROVED** [review]

**Review by pankaj-bansal — APPROVED** [review]

**Comment by mrserb** [comment]
Do we have a new bug to redo the https://bugs.openjdk.java.net/browse/JDK-8249674 again?

**Comment by trebari** [comment]
> Do we have a new bug to redo the https://bugs.openjdk.java.net/browse/JDK-8249674 again?

Yes, https://bugs.openjdk.java.net/browse/JDK-8271315.

**Comment by mrserb** [comment]
> Yes, https://bugs.openjdk.java.net/browse/JDK-8271315.

Thank you, looks fine.

**Pull request closed without merging**
