### PR TITLE
8278131: runtime/cds/appcds/dynamicArchive/* tests failing in loom repo

### PR DESCRIPTION
**Pull request by calvinccheung**
A few dynamic archive CDS tests are failing in the loom repo due to more aggressive GC of code cache
which leads to unloading of some classes before being written into a dynamic CDS archive.

This change is to make the affected tests more reliable by ensuring the test classes are not unloaded
during dynamic CDS dump time.

Testing: Oracle CI tiers 1,2,4.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278131](https://bugs.openjdk.java.net/browse/JDK-8278131): runtime/cds/appcds/dynamicArchive/* tests failing in loom repo

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to 998817f4449d9da12345ac3fedbdd75e93a83016
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**) ⚠️ Review applies to e947fe065c150967829d6f9d9265cbb236c47da1

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6843/head:pull/6843` \
`$ git checkout pull/6843`

Update a local copy of the PR: \
`$ git checkout pull/6843` \
`$ git pull https://git.openjdk.java.net/jdk pull/6843/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6843`

View PR using the GUI difftool: \
`$ git pr show -t 6843`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6843.diff">https://git.openjdk.java.net/jdk/pull/6843.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Sorry but this isn't making any sense to me. You can't GC a class until its classloader becomes unreachable - at which point the classloader and all its loaded classes become unreachable together. So you can't keep a class alive by storing a reference to it in a static field of a class loaded by the same classloader - it was already kept alive.

David

**Comment by iklam** [comment]
> Sorry but this isn't making any sense to me. You can't GC a class until its classloader becomes unreachable - at which point the classloader and all its loaded classes become unreachable together. So you can't keep a class alive by storing a reference to it in a static field of a class loaded by the same classloader - it was already kept alive.
> 
> David

Hi David,

```
        URLClassLoader urlClassLoader =
            new URLClassLoader("HelloClassLoader", urls, null);
        Class c = Class.forName(className, true, urlClassLoader);
+       if (keepAlive) {
+           keptC = c;
+       }
```
The class `c` is defined by a custom class loader (`urlClassLoader`). Before this patch, when `urlClassLoader` and `c` fall out of scope, this class becomes eligible for garbage collection.

The class that runs the above code (`HelloUnload`) is loaded by the app class loader. By referencing `c` in a static field of `HelloUnload`, we make sure `c` is never unloaded.

**Review by iklam — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
Sorry should have been more specific. I'm looking at  test/hotspot/jtreg/runtime/HiddenClasses/InstantiateHiddenClass.java where the hidden class is stored in the new field.

**Comment by dholmes-ora** [comment]
> Sorry should have been more specific. I'm looking at test/hotspot/jtreg/runtime/HiddenClasses/InstantiateHiddenClass.java where the hidden class is stored in the new field.

Okay so that test has nothing to do with dynamic dumping. But if you wanted to keep the hidden classes alive you create with STRONG so they are strongly associated with their classloader. But I can't see why that test would need that anyway.

**Comment by AlanBateman** [comment]
> The class `c` is defined by a custom class loader (`urlClassLoader`). Before this patch, when `urlClassLoader` and `c` fall out of scope, this class becomes eligible for garbage collection.

Using a static field in this context is okay. Another useful approach would be use Reference.reachabilityFence at the end of the method to keep c alive.

**Comment by calvinccheung** [comment]
> > Sorry should have been more specific. I'm looking at test/hotspot/jtreg/runtime/HiddenClasses/InstantiateHiddenClass.java where the hidden class is stored in the new field.
> 
> Okay so that test has nothing to do with dynamic dumping. But if you wanted to keep the hidden classes alive you create with STRONG so they are strongly associated with their classloader. But I can't see why that test would need that anyway.

The appcds/dynamicArchive/RegularHiddenClass.java test makes use of the InstantitateHiddenClass and attempts
to dump a hidden class into the dynamic archive.

I've tried your suggestion on using the STRONG `ClassOption` as follows and it also works. Will update the webrev.

```
-        Class<?> c1 = lookup.defineHiddenClass(klassbuf, false, NESTMATE).lookupClass();
-        Class<?> c2 = lookup.defineHiddenClass(klassbuf, false, NESTMATE).lookupClass();
+        ClassOption classOption = keepAlive ? STRONG : NESTMATE;
+        Class<?> c1 = lookup.defineHiddenClass(klassbuf, false, classOption).lookupClass();
+        Class<?> c2 = lookup.defineHiddenClass(klassbuf, false, classOption).lookupClass();
```

**Comment by dholmes-ora** [comment]
> The appcds/dynamicArchive/RegularHiddenClass.java test makes use of the InstantitateHiddenClass and attempts
to dump a hidden class into the dynamic archive.

Ah I see - that makes more sense. May I suggest that a comment is added in InstantiateHiddenClass.java to indicate that it is also used by RegularHiddenClass which will pass the keep-alive option. Otherwise it looks very odd to expect a parameter that is seemingly not passed and for which there is no obvious reason for passing. Thanks.

**Comment by dholmes-ora** [comment]
I find the overall handling of the extra keep-alive parameter somewhat awkward. It is far from clear which tests will be invoked with what set of parameters, and whether "keep-alive" is always passed, or only sometimes. If none of these tests actually rely on performing class unloading, then it would be simpler if they all unconditionally keep the classes alive.

David

**Comment by calvinccheung** [comment]
> > The appcds/dynamicArchive/RegularHiddenClass.java test makes use of the InstantitateHiddenClass and attempts
> > to dump a hidden class into the dynamic archive.
> 
> Ah I see - that makes more sense. May I suggest that a comment is added in InstantiateHiddenClass.java to indicate that it is also used by RegularHiddenClass which will pass the keep-alive option. Otherwise it looks very odd to expect a parameter that is seemingly not passed and for which there is no obvious reason for passing. Thanks.

I've added the following comment:
```
    public static void main(String[] args) throws Throwable {
        // This class is also used by the appcds/dynamicArchive/RegularHiddenClass.java
        // test which will pass the "keep-alive" argument during dynamic CDS dump
        // for preventing from being GC'ed prior to the dumping operation.
```

**Comment by calvinccheung** [comment]
> I find the overall handling of the extra keep-alive parameter somewhat awkward. It is far from clear which tests will be invoked with what set of parameters, and whether "keep-alive" is always passed, or only sometimes. If none of these tests actually rely on performing class unloading, then it would be simpler if they all unconditionally keep the classes alive.
> 
> David

The "keep-alive" is needed only for dynamic CDS dumping; it is not required during runtime or static dumping. So I think
it is better to keep the "keep-alive" parameter so that other tests won't be impacted.
I've added some comments to the help classes.

thanks,
Calvin

**Review by dholmes-ora — APPROVED** [review]
The test changes are acceptable and so the PR "approved" on that basis.

But I can't help but wonder what this class unloading issue means for dynamic dumping in general? Seems like the dump contents will depend on a GC race.

Thanks,
David

**Review by yminqi — APPROVED** [review]
LGTM.

**Comment by calvinccheung** [comment]
> The test changes are acceptable and so the PR "approved" on that basis.

Thanks!

> 
> But I can't help but wonder what this class unloading issue means for dynamic dumping in general? Seems like the dump contents will depend on a GC race.
> 
Yes, there have been couple of bugs in this area. Hopefully the upcoming fix for [JDK-8278602](https://bugs.openjdk.java.net/browse/JDK-8278602)
will address this issue.

**Comment by calvinccheung** [comment]
@iklam, @dholmes-ora, @yminqi Thanks for the review.
/integrate

**Pull request closed without merging**
