### PR TITLE
8257502: Builds fail with new warnings after JDK-8256254

### PR DESCRIPTION
**Pull request by shipilev**
Default `x86_32` and `s390x` builds fail after JDK-8256254, because of the new warning:

x86_32:

```
/home/shade/trunks/jdk/src/hotspot/cpu/x86/sharedRuntime_x86_32.cpp: In function 'void gen_special_dispatch(MacroAssembler*, const methodHandle&, const BasicType*, const VMRegPair*)':
/home/shade/trunks/jdk/src/hotspot/cpu/x86/sharedRuntime_x86_32.cpp:1291:11: error: format '%d' expects argument of type 'int', but argument 4 has type 'vmIntrinsics::ID' {aka 'vmIntrinsicID'} [-Werror=format=]
 1291 | fatal("unexpected intrinsic id %d", iid);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~
      | |
      | vmIntrinsics::ID {aka vmIntrinsicID}
   ... (rest of output omitted)
```

s390x:

```
/home/shade/trunks/jdk/src/hotspot/cpu/s390/sharedRuntime_s390.cpp: In function 'void gen_special_dispatch(MacroAssembler*, int, vmIntrinsics::ID, const BasicType*, const VMRegPair*)':
/home/shade/trunks/jdk/src/hotspot/cpu/s390/sharedRuntime_s390.cpp:923:15: error: format '%d' expects argument of type 'int', but argument 5 has type 'vmIntrinsics::ID' {aka 'vmIntrinsicID'} [-Werror=format=]
  923 | "special_dispatch=%d", special_dispatch);
      | ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
      | |
   ... (rest of output omitted)
```
The fix is pretty trivial: do the same as other arches. I think it would have been caught by GH actions in #1237, if they actually ran...

Testing:
 - [x] Linux x86_32 fastdebug build
 - [x] Linux s390x fastdebug build

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257502](https://bugs.openjdk.java.net/browse/JDK-8257502): Builds fail with new warnings after JDK-8256254

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - Committer)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1536/head:pull/1536`
`$ git checkout pull/1536`

### CODE REVIEW

**Comment by hltj** [comment]
There is similar issue at  https://github.com/openjdk/jdk/blob/ecdff112fc806faf1f601b66df6d74e69384b9a5/src/hotspot/cpu/s390/sharedRuntime_s390.cpp#L923 , could you fix it together?

**Review by DamonFool — APPROVED** [review]
Build passed with this fix.
Thanks.

**Comment by shipilev** [comment]
> There is similar issue at
> 
> https://github.com/openjdk/jdk/blob/ecdff112fc806faf1f601b66df6d74e69384b9a5/src/hotspot/cpu/s390/sharedRuntime_s390.cpp#L923

Ah. I would need to test that separately with s390x cross-compilation. Would try to do that in a separate PR.

**Comment by hltj** [comment]
> > There is similar issue at
> > https://github.com/openjdk/jdk/blob/ecdff112fc806faf1f601b66df6d74e69384b9a5/src/hotspot/cpu/s390/sharedRuntime_s390.cpp#L923
> 
> Ah. I would need to test that separately with s390x cross-compilation. Would try to do that in a separate PR.

Thanks, I just noticed there's another similar issue when [manual trigger the Github action 'Pre-submit tests'](https://github.com/hltj-bak/jdk/runs/1478401868?check_suite_focus=true).

**Comment by shipilev** [comment]
> > > There is similar issue at
> > > https://github.com/openjdk/jdk/blob/ecdff112fc806faf1f601b66df6d74e69384b9a5/src/hotspot/cpu/s390/sharedRuntime_s390.cpp#L923
> > 
> > 
> > Ah. I would need to test that separately with s390x cross-compilation. Would try to do that in a separate PR.
> 
> Thanks, I just noticed there's another similar issue when [manual trigger the Github action 'Pre-submit tests'](https://github.com/hltj-bak/jdk/runs/1478401868?check_suite_focus=true).

Thanks! So only s390x is additionally affected, I will merge the fix into this PR then.

**Review by DamonFool — APPROVED** [review]

**Review by tstuefe — APPROVED** [review]
Thanks Aleksey. LGTM.

**Comment by shipilev** [comment]
Trivial, right? So I can push as soon as tests go green?

**Comment by tstuefe** [comment]
> Trivial, right? So I can push as soon as tests go green?

Please do.

**Comment by shipilev** [comment]
`x86_32` build-test and `s390x` build passed in GH Actions. I would not wait for Windows tests to catch up.

/integrate

**Pull request closed without merging**
