### PR TITLE
8334777: Test javax/management/remote/mandatory/notif/NotifReconnectDeadlockTest.java failed with NullPointerException

### PR DESCRIPTION
**Pull request by kevinjwalls**
Disable running this test with -Xcomp.

The NPE seen in this test is due to a timeout establishing the connection.  ServerCommunicatorAdmin hits its timeout, during an addNotificationListener call on a new connection.

-Xcomp causes this slowdown and the failure is reproducible.  There is no need to test this test with -Xcomp, we should exclude it as we do for various other tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334777](https://bugs.openjdk.org/browse/JDK-8334777): Test javax/management/remote/mandatory/notif/NotifReconnectDeadlockTest.java failed with NullPointerException (**Bug** - P4)

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19930/head:pull/19930` \
`$ git checkout pull/19930`

Update a local copy of the PR: \
`$ git checkout pull/19930` \
`$ git pull https://git.openjdk.org/jdk.git pull/19930/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19930`

View PR using the GUI difftool: \
`$ git pr show -t 19930`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19930.diff">https://git.openjdk.org/jdk/pull/19930.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19930#issuecomment-2195091535)

### CODE REVIEW

**Review by plummercj — COMMENTED** [review]
My main concern is that for the reader of this test it's not obvious why it can't be run with -Xcomp. Maybe add an @comment explaining why.

**Comment by kevinjwalls** [comment]
Yes sure, I've added a short comment, so it's clear this is intentional and we know -Xcomp causes a specific timeout.  Checked test still runs OK, and skips with -Xcomp.

**Review by plummercj — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Okay

**Comment by kevinjwalls** [comment]
Thanks for the reviews!

**Pull request closed without merging**
