### PR TITLE
8276628: Use blessed modifier order in serviceability code

### PR DESCRIPTION
**Pull request by magicus**
I ran bin/blessed-modifier-order.sh on source owned by serviceability. This scripts verifies that modifiers are in the "blessed" order, and fixes it otherwise. I have manually checked the changes made by the script to make sure they are sound.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276628](https://bugs.openjdk.java.net/browse/JDK-8276628): Use blessed modifier order in serviceability code

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to cf5db105e2e418f8613c47dbd78ad8ade5597938
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6249/head:pull/6249` \
`$ git checkout pull/6249`

Update a local copy of the PR: \
`$ git checkout pull/6249` \
`$ git pull https://git.openjdk.java.net/jdk pull/6249/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6249`

View PR using the GUI difftool: \
`$ git pr show -t 6249`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6249.diff">https://git.openjdk.java.net/jdk/pull/6249.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks fine to me.

Thanks,
David

**Review by lmesnik — APPROVED** [review]

**Review by plummercj — COMMENTED** [review]
Copyright updates?

**Comment by magicus** [comment]
@plummercj That's really kind of an edge case, considering the triviality of these changes. But yes, the norm in the JDK is to update the copyright year for all changes, so you're right, I should do that.

(And we *really* ought to wrangle free some resources to write tooling for us to do all the copyright dances...)

**Review by plummercj — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Good catch on copyright updates @plummercj ! We always have to update when we modify a file - the one exception is changing the wording of the copyright notice itself.

Looks good.

David

**Comment by AnirvanSarkar** [comment]
> (And we _really_ ought to wrangle free some resources to write tooling for us to do all the copyright dances...)

OpenJFX team seems to have a copyright update script[1].
Maybe @kevinrushforth can tell if it can be retrofitted and used by OpenJDK project.

[1] : https://bugs.openjdk.java.net/browse/JDK-8214793?focusedCommentId=14233661&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14233661

**Pull request closed without merging**
