### PR TITLE
8315698: Crash when comparing BasicType as int after JDK-8310577

### PR DESCRIPTION
**Pull request by djelinski**
Please review this patch that fixes the handling of result type parameter in `call_stub` on x64.

Since 5a82fa3bb278b5b80b9ede0619f364fe13cdbede the parameter only needs one byte, and Windows ABI does not require the caller to clear the remaining bytes of the parameter register.

Clang clears the remainder of the register in release mode, but does not clear it in debug mode.
MSVC... [It's complicated](https://godbolt.org/z/6YEcMcM13). Apparently MSVC-generated code clears the high bytes of the parameter register here.

This patch fixes the crashes with clang. (MSVC) Windows-x64 and (gcc) Linux-x64 builds still work, tiers 1-3 report no new failures.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315698](https://bugs.openjdk.org/browse/JDK-8315698): Crash when comparing BasicType as int after JDK-8310577 (**Bug** - P2)

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15568/head:pull/15568` \
`$ git checkout pull/15568`

Update a local copy of the PR: \
`$ git checkout pull/15568` \
`$ git pull https://git.openjdk.org/jdk.git pull/15568/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15568`

View PR using the GUI difftool: \
`$ git pr show -t 15568`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15568.diff">https://git.openjdk.org/jdk/pull/15568.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15568#issuecomment-1706941354)

### CODE REVIEW

**Comment by dean-long** [comment]
I don't think there's much advantage to using an 8-bit value in the assembly code.  How about changing the CallStub typedef to take "int" like the assembly code expects?  That way all platforms are fixed, not just x86.

**Comment by djelinski** [comment]
@dean-long Thanks for the suggestion. I updated the code.

**Review by dean-long — APPROVED** [review]

**Review by coleenp — APPROVED** [review]
Thank you for finding and fixing this.

**Comment by djelinski** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
