### PR TITLE
8255900: x86: Reduce impact when VerifyOops is disabled

### PR DESCRIPTION
**Pull request by cl4es**
- Don't generate stub _verify_oop_subroutine_entry on startup if -VerifyOops
- Make VerifyOops check in calls to MacroAssembler::verify_oop inlineable. (VerifyOops is a develop flag, so this allows more aggressive code elimination in a few place)
- (trivial pile-on) remove unused set_word_if_not_zero

Slightly improves static footprint, gets rid of a stub and reduce jitter during jitting in product builds.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ⏳ (2/2 running) | ✔️ (2/2 passed) |
| Test (tier1) | ⏳ (9/9 running) | ⏳ (8/9 running) |    |  ⏳ (8/9 running) |

### Issue
 * [JDK-8255900](https://bugs.openjdk.java.net/browse/JDK-8255900): x86: Reduce impact when VerifyOops is disabled

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 0e083d99331d66a236993ec84914570ba70ec4a9
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**) ⚠️ Review applies to 0e083d99331d66a236993ec84914570ba70ec4a9
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 0e083d99331d66a236993ec84914570ba70ec4a9

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1058/head:pull/1058`
`$ git checkout pull/1058`

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good!

**Review by yminqi — COMMENTED** [review]
Why only for x86_64 not including other platforms?

**Comment by cl4es** [comment]
> Why only for x86_64 not including other platforms?

It's uneasy changing platforms I don't have access to to test. Generally it seems more appropriate that someone with access ports the changes. This case might be trivial enough to port without testing, but I looked at aarch64 which does not use the same macro structure, for example, so I backed away from attempting that.

**Review by yminqi — APPROVED** [review]
Then looks good to me.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by cl4es** [comment]
@vnkozlov @neliasso @yminqi - thank you for reviews!

/integrate

**Pull request closed without merging**
