### PR TITLE
8253572: [windows] CDS archive may fail to open with long file names

### PR DESCRIPTION
**Pull request by tstuefe**
Hi all,

there is a long standing bug in the windows version of os::pd_map_memory() which may cause it to fail if the path to the underlying file is longer than the OS limit. This is mainly of interest for CDS, which uses this functionality to map in sections of the archive into the memory. This bug may cause the CDS mapping to fail. See also https://bugs.openjdk.java.net/browse/JDK-8249943.

As with similar cases, the fix is to translate the input file name to a wide character UNC path name and use the Unicode variant of CreateFile which accepts long path names.

/issue add 8253572, 8249943
/test tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8253572](https://bugs.openjdk.java.net/browse/JDK-8253572): [windows] CDS archive may fail to open with long file names
 * [JDK-8249943](https://bugs.openjdk.java.net/browse/JDK-8249943): [TESTBUG] runtime/cds/serviceability/transformRelatedClasses/TransformInterfaceAndImplementor.java

### Reviewers
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/332/head:pull/332`
`$ git checkout pull/332`

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
Thanks for identifying the bug and fixing it. The patch looks good.

**Comment by tstuefe** [comment]
> Thanks for identifying the bug and fixing it. The patch looks good.

Thank you Calvin!

**Comment by tstuefe** [comment]
Ping... may I have a second review please?

**Review by iklam — APPROVED** [review]
LGTM

**Comment by tstuefe** [comment]
> LGTM

Thanks Ioi!

**Pull request closed without merging**
