### PR TITLE
8292878: x86: Make scratch register usage explicit in assembler code

### PR DESCRIPTION
**Pull request by iwanowww**
Improve MacroAssembler API and make scratch register usages explicit at use sites.

Different parts of JVM have different assumptions about scratch registers and
implicit assumptions in MacroAssembler makes it harder to reason about the
correctness of generated code.

Most of scratch register usages relate to `AddressLiteral` on x86_64.  In such case the argument is turned into a default one (with `noreg` as a default) and implementation asserts that scratch register should be provided when the address is not guaranteed to be always reachable.

Otherwise, scratch register argument is required to be explicitly provided.

The only case left (mostly) intact is `call(AddressLiteral)`, but I switched it from `rscratch` (`r10`) to `rax`.

Testing:
- [x] hs-tier1 - hs-tier4 (w/ -XX:+-ForceUnreachable)
- [x] x86_32 build

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292878](https://bugs.openjdk.org/browse/JDK-8292878): x86: Make scratch register usage explicit in assembler code

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [ed4dc939](https://git.openjdk.org/jdk/pull/10003/files/ed4dc939c9f3f66317f70e02c2a6c8702805f5ae)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10003/head:pull/10003` \
`$ git checkout pull/10003`

Update a local copy of the PR: \
`$ git checkout pull/10003` \
`$ git pull https://git.openjdk.org/jdk pull/10003/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10003`

View PR using the GUI difftool: \
`$ git pr show -t 10003`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10003.diff">https://git.openjdk.org/jdk/pull/10003.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
I hope you did not do this all by hand ;)

Good.

**Comment by iwanowww** [comment]
Accidentally, introduced a bug by turning some `AddressLiteral`s into lvals.

Reverted relevant chanages, plus made the scratch register argument required for  `cmpptr(Address,AddressLiteral,Register)`. 

Improved `Assembler::reachable`/`Assembler::always_reachable` to properly handle lvals.

Also, applied a minor refactoring around `CompressedOops::ptrs_base_addr()`.

**Review by vnkozlov — APPROVED** [review]
Still good.

**Comment by iwanowww** [comment]
Thanks for the review, Vladimir.

@shipilev Aleksey, do you plan to look into x86_32-specific changes? Otherwise, I'll integrate the patch.

**Comment by shipilev** [comment]
> @shipilev Aleksey, do you plan to look into x86_32-specific changes? Otherwise, I'll integrate the patch.

Missed this comment, sorry. Are you looking for a similar change on x86_32-specific code? I believe x86_32 code does not use scratch registers (they are `#define`-d to `noreg`), so there seem to be nothing to do. I see GHA infra barfed up on x86_32 tests, I'll run some tests locally.

**Comment by iwanowww** [comment]
Thanks. Just wanted to hear from you since it affects x86_32 in a non-trivial way.

**Review by shipilev — APPROVED** [review]
I think we are fine. `tier1` and `tier2` pass on x86_32.

**Comment by iwanowww** [comment]
Thanks, Aleksey.

/integrate

**Pull request closed without merging**
