### PR TITLE
JDK-8327071: [Testbug] g-tests for cgroup leave files in /tmp on linux

### PR DESCRIPTION
**Pull request by ArnoZeller**
After each run of the g-tests for cgroups on Linux there are three new files left in /tmp.

cgroups-test-jdk.pid<pid>.cgroupTest.SubSystemFileLineContentsSingleLine
cgroups-test-jdk.pid<pid>.cgroupTest.SubSystemFileLineContentsMultipleLinesSuccessCases
cgroups-test-jdk.pid<pid>.cgroupTest.SubSystemFileLineContentsMultipleLinesErrorCases

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327071](https://bugs.openjdk.org/browse/JDK-8327071): [Testbug] g-tests for cgroup leave files in /tmp on linux (**Bug** - P4)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [4d9dadd2](https://git.openjdk.org/jdk/pull/18077/files/4d9dadd2ed52d2f5fe383dcf0eb306ec349de2c4)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18077/head:pull/18077` \
`$ git checkout pull/18077`

Update a local copy of the PR: \
`$ git checkout pull/18077` \
`$ git pull https://git.openjdk.org/jdk.git pull/18077/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18077`

View PR using the GUI difftool: \
`$ git pr show -t 18077`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18077.diff">https://git.openjdk.org/jdk/pull/18077.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18077#issuecomment-1973103715)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]
Looks okay to me ; while at it please fix also the typo in comment line in this file ( 'generaed by' ) .

**Review by lgxbslgx — APPROVED** [review]
Looks good.

**Comment by tstuefe** [comment]
Hi @ArnoZeller, I wonder why these files have to live in tmp. Why can't they not live in the current directory, that way if we run gtest via jtreg tests, they would be cleaned automatically, and be subject to `-retain` if needed. @jdksjolen do you know why ?

Other than that, if they have to live in temp, the patch is of course fine.

**Comment by jdksjolen** [comment]
Hi,

The reasoning behind that is simple: I was not aware that JTReg deletes files created in the current directory.

**Comment by ArnoZeller** [comment]
Hi @tstuefe,
I must admit that I do not know what is normally expected from GTests.
- Should they cleanup in case of no error? (I guess yes)
- Where should GTests normally write temporary files?
- Does everybody run GTests only with JTReg or are they normally executed manually? (I myself always use JTReg, but only because I am used to JTReg).
Probably we could move the test to write to the current directory but I am not sure if this is a good idea when the test is not executed by JTReg. Perhaps someone with more GTests knowledge could assist here?

**Comment by MBaesken** [comment]
looks like a couple of other gtests use the tmp dir too

```
grep -nH -r get_temp_directory  *
logging/logTestFixture.cpp:40:                         os::get_temp_directory(), os::file_separator(), os::current_process_id(),
logging/logTestUtils.inline.hpp:93:static const char* tmp_dir = os::get_temp_directory();
logging/test_logFileOutput.cpp:173:  ss.print("%s%s%s%d", os::get_temp_directory(), os::file_separator(), "tmplogdir", os::current_process_id());
os/linux/test_cgroupSubsystem_linux.cpp:45:  path.print_raw(os::get_temp_directory());
```

but seems the others at least clean up the created files as far as I can see.

**Comment by tstuefe** [comment]
> looks like a couple of other gtests use the tmp dir too
> 
> ```
> grep -nH -r get_temp_directory  *
> logging/logTestFixture.cpp:40:                         os::get_temp_directory(), os::file_separator(), os::current_process_id(),
> logging/logTestUtils.inline.hpp:93:static const char* tmp_dir = os::get_temp_directory();
> logging/test_logFileOutput.cpp:173:  ss.print("%s%s%s%d", os::get_temp_directory(), os::file_separator(), "tmplogdir", os::current_process_id());
> os/linux/test_cgroupSubsystem_linux.cpp:45:  path.print_raw(os::get_temp_directory());
> ```
> 
> but seems the others at least clean up the created files as far as I can see.

Okay, if it is established practice, let's do it here too. When in Rome...

What I like most about the current-directory solution is the ability to keep files with -retain, for post-test analysis. But if we change this, we should change it for all tests, and that is beyond the scope of this RFR.

Cheers, Thomas

**Review by tstuefe — APPROVED** [review]

**Comment by ArnoZeller** [comment]
Thanks to all for reviewing! 
@MBaesken: Would you please sponsor it?

**Pull request closed without merging**
