### PR TITLE
8271459: C2: Missing NegativeArraySizeException when creating StringBuilder with negative capacity

### PR DESCRIPTION
**Pull request by chhagedorn**
Stringopts does not take into account that a negative `int` argument for `StringBuilder(int)` results in a `NegativeArraySizeException` when optimizing away `StringBuilder` usages into single strings.

The suggested fix does the following:
- Bailout of Stringopts if C2 knows that an `int` argument is always negative.
- Apply stringopts but insert an additional runtime check with an UCT if C2 cannot tell if an `int` argument is positive or negative.

I added some IR tests to verify the fix and also ran some standard benchmarks.

I also updated `TestIRMatching` to test the new and updated default regexes.

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271459](https://bugs.openjdk.java.net/browse/JDK-8271459): C2: Missing NegativeArraySizeException when creating StringBuilder with negative capacity

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to ab8b6f8acf7388988b0b9db30377d58f93af8474
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5652/head:pull/5652` \
`$ git checkout pull/5652`

Update a local copy of the PR: \
`$ git checkout pull/5652` \
`$ git pull https://git.openjdk.java.net/jdk pull/5652/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5652`

View PR using the GUI difftool: \
`$ git pr show -t 5652`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5652.diff">https://git.openjdk.java.net/jdk/pull/5652.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks reasonable to me.

**Comment by chhagedorn** [comment]
Thanks Roland for your review!

**Comment by neliasso** [comment]
If we hit the uncommontrap - should we recompile without applying strconcat? Or is this code so uncommon that we don't want to add complexity for that case?

**Comment by chhagedorn** [comment]
I guess we could do that by changing the UCT from `Action_none` to `Action_maybe_recompile`. I pushed an update.

**Review by TobiHartmann — APPROVED** [review]
That looks good to me given that we check for `too_many_traps` in `StringConcat::validate_control_flow()`.

**Comment by chhagedorn** [comment]
Thanks for your review Tobias! Right, that should prevent the application of stringopts again.

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by chhagedorn** [comment]
Thanks Nils for your review!

**Pull request closed without merging**
