### PR TITLE
8277930: Add unsafe allocation event to jfr

### PR DESCRIPTION
**Pull request by xpbob**
Unsafe is used in many Java frameworks.
When the framework has a unsafe memory leak , there is no way to know what code is causing it.
Add unsafe allocation event to jfr.
Records the size and stack allocated.
This event is off by default

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8277930](https://bugs.openjdk.java.net/browse/JDK-8277930): Add unsafe allocation event to jfr

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6591/head:pull/6591` \
`$ git checkout pull/6591`

Update a local copy of the PR: \
`$ git checkout pull/6591` \
`$ git pull https://git.openjdk.java.net/jdk pull/6591/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6591`

View PR using the GUI difftool: \
`$ git pr show -t 6591`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6591.diff">https://git.openjdk.java.net/jdk/pull/6591.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
An event like this would help to find allocation sites.

I'd suggest also adding an event for `Unsafe::freeMemory`, as well as recording the memory address in both event types. With that, it should be possible to match up allocations with frees, and leaks could be identified by looking for allocations that don't have a corresponding free with the same address.

**Comment by D-D-H** [comment]
> I'd suggest also adding an event for `Unsafe::freeMemory`, as well as recording the memory address in both event types. With that, it should be possible to match up allocations with frees, and leaks could be identified by looking for allocations that don't have a corresponding free with the same address.

Unsafe also support reallocating memory, which complexes the analysis of direct memory leak.

And I think we need a mechanism to filter events by allocation size, but  AFAIK, there is no general mechanism to achieve it at present.

**Comment by xpbob** [comment]
Thanks
I added 3 events
|event|stack|addr|size|
|-|-|-|-|
|Allocation|true|alloc|true|
|Reallocate|true|before realloc,after realloc|true|
|Free|true|free addr|false|

**Comment by egahlin** [comment]
What about overhead (if JFR is disabled)? 

This looks like it could be a hot path for some applications.

**Comment by xpbob** [comment]
> What about overhead (if JFR is disabled)?
> 
> This looks like it could be a hot path for some applications.

Thanks

**result:**
|jdk|cores|
|-|-|
|disable jfr(--disable-jvm-feature-jfr)|3.032 ± 0.059|
|remove unsafe event|2.938 ± 0.071|
|unsafe event|2.938 ± 0.065|

**env:**
os: mac os
mem:  16g 
cpu:2.6 GHz 6core Intel Core i7
framework:jmh



**testcode:**

```java
@BenchmarkMode(Mode.Throughput)
@Warmup(iterations = 3)
@Measurement(iterations = 10, time = 5, timeUnit = TimeUnit.SECONDS)
@Threads(8)
@Fork(2)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
public class UnsafeTest {

    @Benchmark
    public void mallocAndFree() throws Exception {
        Field field = Unsafe.class.getDeclaredField("theUnsafe");
        field.setAccessible(true);
        Unsafe unsafe = (Unsafe) field.get(null);
        for (int i = 0; i < 10000; i++) {
            long l = unsafe.allocateMemory(1000);
            unsafe.freeMemory(l);
        }
    }
}

```

**Comment by JornVernee** [comment]
I ran some benchmarks as well: http://cr.openjdk.java.net/~jvernee/UnsafeTest.java

I see about a 6 ns increase in benchmark times with the new coded added in (regardless of allocation size), which sounds about right. An unsafe allocation and free takes about 90 ns on my machine with the latest JDK, so the regression is ~6%. (I'm not sure if that's worth worrying about, see below).

Whether this is a hot path or not: I think most user applications that use these APIs are doing so indirectly through direct ByteBuffers, and most of those that I've seen use memory pools to avoid doing BB allocations (which can be slow due to the need to wait for reference processing for instance).

I can't really say if direct calls, or indirect call through other paths than direct ByteBuffers are a hot path in applications, but I'd be surprised if they were, tbh, since generally people seem to think of `malloc` as slow (something I've observed in practice as well), and try to build their own allocators on top if they want more speed.

Maybe it's an idea to implement these events in Java code instead? (using the JFR mirror events). I think the overhead should always be zero if the events are disabled in that case, right?

**Comment by D-D-H** [comment]
> Maybe it's an idea to implement these events in Java code instead? (using the JFR mirror events). I think the overhead should always be zero if the events are disabled in that case, right?

In my opinion, these events will be enabled when direct memory leak occurs during application running. In other words, users will not enable them at startup. 

So if these events are implemented by Java layer, some methods will be deoptimized which causes performance degradation of the application for a period of time if I understand correctly.

**Comment by egahlin** [comment]
> I ran some benchmarks as well: http://cr.openjdk.java.net/~jvernee/UnsafeTest.java
> 
> I see about a 6 ns increase in benchmark times with the new coded added in (regardless of allocation size), which sounds about right. An unsafe allocation and free takes about 90 ns on my machine with the latest JDK, so the regression is ~6%. (I'm not sure if that's worth worrying about, see below).
> 
> Whether this is a hot path or not: I think most user applications that use these APIs are doing so indirectly through direct ByteBuffers, and most of those that I've seen use memory pools to avoid doing BB allocations (which can be slow due to the need to wait for reference processing for instance).
> 
> I can't really say if direct calls, or indirect call through other paths than direct ByteBuffers are a hot path in applications, but I'd be surprised if they were, tbh, since generally people seem to think of `malloc` as slow (something I've observed in practice as well), and try to build their own allocators on top if they want more speed.
> 
> Maybe it's an idea to implement these events in Java code instead? (using the JFR mirror events). I think the overhead should always be zero if the events are disabled in that case, right?

Thanks, that were the numbers I was looking for!

We could do them at zero cost in Java if we use bytecode instrumentation. If we use mirror events, it may not always work out due to inlining depth. There is also additional startup cost when using Java events.

My worry is that very few people will actually turn these events on, but the rest of the world (99,9999%) will pay the additional 6 ns overhead for every native allocation. We are planning some rewrites for JDK 19 when comes to Java events to reduce the startup cost. It could worth to see if they could be turned into Java events (with zero overhead), similar to the SocketRead/SocketWrite events.

I also wonder if the events should be called NativeAllocation, NativeReallocation and NativeFree, so they are not tied so hard to the Unsafe implementation.

**Comment by theRealAph** [comment]
> I ran some benchmarks as well: http://cr.openjdk.java.net/~jvernee/UnsafeTest.java
> 
> I see about a 6 ns increase in benchmark times with the new coded added in (regardless of allocation size), which sounds about right. An unsafe allocation and free takes about 90 ns on my machine with the latest JDK, so the regression is ~6%. (I'm not sure if that's worth worrying about, see below).

Computers can get a lot done in 6ns. Why can't the JFR event be conditional on a simple flag?

**Comment by tstuefe** [comment]
> When the framework has a unsafe memory leak , there is no way to know what code is causing it.

Just a note, this is tracked by NMT (category `mtOther`). 

> Computers can get a lot done in 6ns. Why can't the JFR event be conditional on a simple flag?

Yes, I dislike paying for something I don't use. We have seen customers using these APIs a lot, so it can be a hot path. The fact that malloc is used is an implementation detail not known to everyone.

@egahlin 
> I also wonder if the events should be called NativeAllocation, NativeReallocation and NativeFree, so they are not tied so hard to the Unsafe implementation.

But you would still limit this to allocations done by outside code, right? Otherwise, again, we have NMT for tracking native memory in the VM.

**Comment by egahlin** [comment]
> > I ran some benchmarks as well: http://cr.openjdk.java.net/~jvernee/UnsafeTest.java
> > I see about a 6 ns increase in benchmark times with the new coded added in (regardless of allocation size), which sounds about right. An unsafe allocation and free takes about 90 ns on my machine with the latest JDK, so the regression is ~6%. (I'm not sure if that's worth worrying about, see below).
> 
> Computers can get a lot done in 6ns. Why can't the JFR event be conditional on a simple flag?

If they are written like this, it should be simple check: 

    EventUnsafeReallocate event;
    if (event.should_commit()) {
      event.set_allocationSize(sz);
      event.set_freeAddr(addr);
      event.set_allocAddr(reallocAddr);
      event.commit()
    }

**Comment by egahlin** [comment]
> > When the framework has a unsafe memory leak , there is no way to know what code is causing it.
> 
> Just a note, this is tracked by NMT (category `mtOther`).
> 
> > Computers can get a lot done in 6ns. Why can't the JFR event be conditional on a simple flag?
> 
> Yes, I dislike paying for something I don't use. We have seen customers using these APIs a lot, so it can be a hot path. The fact that malloc is used is an implementation detail not known to everyone.
> 
> @egahlin
> 
> > I also wonder if the events should be called NativeAllocation, NativeReallocation and NativeFree, so they are not tied so hard to the Unsafe implementation.
> 
> But you would still limit this to allocations done by outside code, right? Otherwise, again, we have NMT for tracking native memory in the VM.

Yes, NativeAllocation could be misleading, perhaps JavaNativeAllocation? There is already JavaExceptionThrow

**Comment by xpbob** [comment]
Thanks


I use  http://cr.openjdk.java.net/~jvernee/UnsafeTest.java

The results were about the same with and without the checking


I want to implement the  java event and test it again


env:linux


code without unsafe event
---

c.unsafe.UnsafeTest.mallocAndFree                 8   avgt   20  66.237 ± 0.672   ns/op
c.unsafe.UnsafeTest.mallocAndFree                12   avgt   20  66.596 ± 0.286   ns/op
c.unsafe.UnsafeTest.mallocAndFree                16   avgt   20  66.219 ± 0.621   ns/op
c.unsafe.UnsafeTest.mallocAndFree                24   avgt   20  66.715 ± 0.329   ns/op
c.unsafe.UnsafeTest.mallocAndFree                32   avgt   20  65.959 ± 0.714   ns/op
c.unsafe.UnsafeTest.mallocAndFree              4096   avgt   20  71.858 ± 3.306   ns/op

---
code with event commit
----

c.unsafe.UnsafeTest.mallocAndFree                 8   avgt   20  68.402 ± 0.257   ns/op
c.unsafe.UnsafeTest.mallocAndFree                12   avgt   20  68.414 ± 0.276   ns/op
c.unsafe.UnsafeTest.mallocAndFree                16   avgt   20  68.405 ± 0.216   ns/op
c.unsafe.UnsafeTest.mallocAndFree                24   avgt   20  68.427 ± 0.219   ns/op
c.unsafe.UnsafeTest.mallocAndFree                32   avgt   20  68.339 ± 0.207   ns/op
c.unsafe.UnsafeTest.mallocAndFree              4096   avgt   20  74.645 ± 3.285   ns/op

----
code wtih should_commit
---
c.unsafe.UnsafeTest.mallocAndFree                 8   avgt   20  68.342 ± 0.273   ns/op
c.unsafe.UnsafeTest.mallocAndFree                12   avgt   20  68.653 ± 0.359   ns/op
c.unsafe.UnsafeTest.mallocAndFree                16   avgt   20  68.421 ± 0.237   ns/op
c.unsafe.UnsafeTest.mallocAndFree                24   avgt   20  68.496 ± 0.205   ns/op
c.unsafe.UnsafeTest.mallocAndFree                32   avgt   20  68.370 ± 0.238   ns/op
c.unsafe.UnsafeTest.mallocAndFree              4096   avgt   20  75.110 ± 2.866   ns/op

**Comment by xpbob** [comment]
code without unsafe event
----
c.unsafe.UnsafeTest.mallocAndFree 8 avgt 20 66.237 ± 0.672 ns/op
c.unsafe.UnsafeTest.mallocAndFree 12 avgt 20 66.596 ± 0.286 ns/op
c.unsafe.UnsafeTest.mallocAndFree 16 avgt 20 66.219 ± 0.621 ns/op
c.unsafe.UnsafeTest.mallocAndFree 24 avgt 20 66.715 ± 0.329 ns/op
c.unsafe.UnsafeTest.mallocAndFree 32 avgt 20 65.959 ± 0.714 ns/op
c.unsafe.UnsafeTest.mallocAndFree 4096 avgt 20 71.858 ± 3.306 ns/op



code with java event
---
c.unsafe.UnsafeTest.mallocAndFree                 8   avgt   20  66.705 ± 0.213   ns/op
c.unsafe.UnsafeTest.mallocAndFree                12   avgt   20  66.621 ± 0.340   ns/op
c.unsafe.UnsafeTest.mallocAndFree                16   avgt   20  66.693 ± 0.197   ns/op
c.unsafe.UnsafeTest.mallocAndFree                24   avgt   20  66.039 ± 0.683   ns/op
c.unsafe.UnsafeTest.mallocAndFree                32   avgt   20  66.035 ± 0.593   ns/op
c.unsafe.UnsafeTest.mallocAndFree              4096   avgt   20  71.809 ± 3.535   ns/op

**Comment by egahlin** [comment]
Nice to see the runtime cost being eliminated when JFR is disabled.

Each additional Java event adds startup cost, and we have been reluctant to add more JFR events, until we have a solution for this. It's not just these events, but others as well.

My plan is to reduce the startup cost by eliminating the need for the handler classes and weave the bytecode at build time. The task is high priority as it blocks several enhancements. I've already done some prototyping, and plan is to have this in place for JDK 19, but no guarantees.

There will be another mechanism than the Handlers class to avoid allocation.

My suggestion is to revisit this PR when it has been checked in.

**Comment by xpbob** [comment]
Thanks, please let me know if you have checked in your enhancement.

**Pull request closed without merging**
