### PR TITLE
JDK-8328786: [AIX] move some important warnings/errors from trcVerbose to UL

### PR DESCRIPTION
**Pull request by MBaesken**
trcVerbose is a macro that can be used in the AIX OpenJDK codebase.
It boils down to `if (Verbose) { <print message> } ;`
However this means that it can only be used in non product JVM because Verbose is a develop flag.
So more important warning/error/info messages should better be moved e.g. to UL so that they are usable in product JVMs too,

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328786](https://bugs.openjdk.org/browse/JDK-8328786): [AIX] move some important warnings/errors from trcVerbose to UL (**Bug** - P4)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18517/head:pull/18517` \
`$ git checkout pull/18517`

Update a local copy of the PR: \
`$ git checkout pull/18517` \
`$ git pull https://git.openjdk.org/jdk.git pull/18517/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18517`

View PR using the GUI difftool: \
`$ git pr show -t 18517`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18517.diff">https://git.openjdk.org/jdk/pull/18517.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18517#issuecomment-2023096683)

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
I think that there were problems with UL during early initialization. I guess that `trcVerbose` has been used as workaround. Did you check if the log messages get still printed?
@tstuefe may know more about why this is used.

**Review by RealLucy — APPROVED** [review]
LGTM.

**Comment by MBaesken** [comment]
> I think that there were problems with UL during early initialization. I guess that `trcVerbose` has been used as workaround. Did you check if the log messages get still printed? @tstuefe may know more about why this is used.

Yes very early in the JVM runtime, the UL is not working (means: no output).  But this is even true to some extent for  `-XX:+Verbose`  . Example  -  I added UL  , trcVerbose AND print at  libperfstat::init  (this is one place I want to change in the PR) 

```
bool libperfstat::init() {
  const char* libperfstat = "/usr/lib/libperfstat.a(shr_64.o)";
  char ebuf[512];
  g_libhandle = os::dll_load(libperfstat, ebuf, sizeof(ebuf));
  log_warning(os)("Loaded libperfstat");
  printf("trace via printf - Loaded libperfstat\n");
  trcVerbose("trace verbose - Loaded libperfstat");
```

Unfortunately only the printf  output is visible;  UL and traceVerbose  is not visible.

**Review by tstuefe — APPROVED** [review]
okay

**Pull request closed without merging**
