### PR TITLE
8269851: OperatingSystemMXBean getProcessCpuLoad reports incorrect process cpu usage in containers

### PR DESCRIPTION
**Pull request by xpbob**
…ocess cpu usage inside a container

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8269851](https://bugs.openjdk.java.net/browse/JDK-8269851): OperatingSystemMXBean getProcessCpuLoad reports incorrect process cpu usage in containers

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4700/head:pull/4700` \
`$ git checkout pull/4700`

Update a local copy of the PR: \
`$ git checkout pull/4700` \
`$ git pull https://git.openjdk.java.net/jdk pull/4700/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4700`

View PR using the GUI difftool: \
`$ git pr show -t 4700`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4700.diff">https://git.openjdk.java.net/jdk/pull/4700.diff</a>

</details>

### CODE REVIEW

**Comment by xpbob** [comment]
getProcessCpuLoad return jvm cpu load。
8 core in machine, set 1 core for container。
Run same program, the getProcessCpuLoad return the same value。

expected 
same program run in machine,value 0.12
run in  1 core container,value 0.99

**Comment by xpbob** [comment]
ProcessCpuLoad  is associative container setting

**Comment by dholmes-ora** [comment]
@YaSuenag and @jerboaa could you please take a look at this one.

**Comment by dholmes-ora** [comment]
This has moved to https://github.com/openjdk/jdk/pull/4702

**Pull request closed without merging**
