### PR TITLE
8255086: Update the root locale display names

### PR DESCRIPTION
**Pull request by naotoj**
Hi,

Please review the changes to the subject issue. The fix replaces the obsolete/incorrect English language/region/script display names in the COMPAT root locale bundle. The data are derived from CLDR's English names.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (hs/tier1 compiler)](https://github.com/naotoj/jdk/runs/1289946703)

### Issue
 * [JDK-8255086](https://bugs.openjdk.java.net/browse/JDK-8255086): Update the root locale display names

### Reviewers
 * [Brent Christian](https://openjdk.java.net/census#bchristi) (@bchristi-git - **Reviewer**)
 * [Joe Wang](https://openjdk.java.net/census#joehw) (@JoeWang-Java - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/786/head:pull/786`
`$ git checkout pull/786`

### CODE REVIEW

**Comment by bchristi-git** [comment]
Hi, Naoto

What is the source for the updated values in LocaleNames.properties?

Also, could the bug synopsis be updated to be more descriptive?

Thanks,
-Brent

**Comment by naotoj** [comment]
Hi Brent,

> What is the source for the updated values in LocaleNames.properties?

The source is CLDR v37, which is currently used in the latest JDK release. They are extracted with a code snippet (https://bugs.openjdk.java.net/browse/JDK-8255086?focusedCommentId=14375906&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14375906), and non-ASCII chars are Unicode escaped.

> Also, could the bug synopsis be updated to be more descriptive?

Modified the synopsis. Hope it made sense.

Naoto

**Comment by bchristi-git** [comment]
Looks good.

**Review by bchristi-git — APPROVED** [review]

**Comment by JoeWang-Java** [comment]
Hi Naoto,

Do we need a test similar to ISO3166 where display names of Locale.ROOT and Locale.US are compared? I see LocaleEnhanceTest.java has references to Locale.ROOT and a few selected names were updated. But we don't seem to have a test like ISO3166 that does a straight-forward comparison.

The code you used to generate the updated LocaleNames.properties (in the comment section), I wonder if there's a better way to preserve it, as part of the manual tool, or maybe put it back into the repo as part of a test?

**Comment by naotoj** [comment]
Hi Joe,

> Do we need a test similar to ISO3166 where display names of Locale.ROOT and Locale.US are compared? I see LocaleEnhanceTest.java has references to Locale.ROOT and a few selected names were updated. But we don't seem to have a test like ISO3166 that does a straight-forward comparison.

test/jdk/sun/text/resources/LocaleData validates all the changes with this changeset (added lines at the end), by checking the names in the resource bundle.

> 
> The code you used to generate the updated LocaleNames.properties (in the comment section), that seems to be valuable. I wonder if there's a better way to preserve it, as part of the manual tool, or maybe put it back into the repo as part of a test?

Yeah, but I cannot think of a better location to preserve it. The reason is that it cannot be used as a test because CLDR's English names and COMPAT's root names can inherently be different. I just regard the code to be one-off to retrieve authentic English names for those language ids.

Naoto

**Comment by JoeWang-Java** [comment]
> Hi Joe,
> 
> > Do we need a test similar to ISO3166 where display names of Locale.ROOT and Locale.US are compared? I see LocaleEnhanceTest.java has references to Locale.ROOT and a few selected names were updated. But we don't seem to have a test like ISO3166 that does a straight-forward comparison.
> 
> test/jdk/sun/text/resources/LocaleData validates all the changes with this changeset (added lines at the end), by checking the names in the resource bundle.

Saw the test and thought ISO3166 would be more direct. But you're right, as you said below, since it's one-off thing, can't really use a test like ISO3166 for a complete comparison.
> 
> > The code you used to generate the updated LocaleNames.properties (in the comment section), that seems to be valuable. I wonder if there's a better way to preserve it, as part of the manual tool, or maybe put it back into the repo as part of a test?
> 
> Yeah, but I cannot think of a better location to preserve it. The reason is that it cannot be used as a test because CLDR's English names and COMPAT's root names can inherently be different. I just regard the code to be one-off to retrieve authentic English names for those language ids.

I see. Thanks.

Joe

> 
> Naoto

**Review by JoeWang-Java — APPROVED** [review]

**Pull request closed without merging**
