### PR TITLE
8324280: RISC-V: Incorrect implementation in VM_Version::parse_satp_mode

### PR DESCRIPTION
**Pull request by MaxXSoft**
Currently, method `VM_Version::os_uarch_additional_features` uses `fgets` to read the contents of `/proc/cpuinfo`, then calls `parse_satp_mode` with a string with the leading "mmu" and whitespaces removed, like ": sv39\n". However, `parse_satp_mode` compares this string directly to "sv39", which always fails and returns `VM_MBARE`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324280](https://bugs.openjdk.org/browse/JDK-8324280): RISC-V: Incorrect implementation in VM_Version::parse_satp_mode (**Bug** - P4)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**) ⚠️ Review applies to [5d1a8f27](https://git.openjdk.org/jdk/pull/17513/files/5d1a8f2771ad80f5022c36f4c9e71a41a9084100)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17513/head:pull/17513` \
`$ git checkout pull/17513`

Update a local copy of the PR: \
`$ git checkout pull/17513` \
`$ git pull https://git.openjdk.org/jdk.git pull/17513/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17513`

View PR using the GUI difftool: \
`$ git pr show -t 17513`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17513.diff">https://git.openjdk.org/jdk/pull/17513.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17513#issuecomment-1909117348)

### CODE REVIEW

**Comment by RealFYang** [comment]
Verified that this happens after fix for: https://bugs.openjdk.org/browse/JDK-8309258. Note: @robehn

**Review by robehn — APPROVED** [review]
Ah, thanks! (you need to fix the OCA: https://openjdk.org/contribute/)

I asked for a bunch of extensions in hwprobe and got allmost all.
I forgot about this one, I'll ask for it to be included in hwprobe.
Another approach seems to be to use mmap + hint.

Maybe use strncmp(vm_mode, 4, "svXX").

**Comment by MaxXSoft** [comment]
@RealFYang @robehn Thanks for your review!

I'm still waiting for my OCA to pass. Also I'v updated this PR to use `strncmp`.

**Review by RealFYang — APPROVED** [review]

**Pull request closed without merging**
