### PR TITLE
8276209: Some call sites doesn't pass the parameter 'size' to SharedRuntime::dtrace_object_alloc(_base)

### PR DESCRIPTION
**Pull request by D-D-H**
Hi,

Could I have a review of this fix that corrects the oop size value of dtrace_object_alloc(_base).

JDK-8039904 added a new parameter 'size' to SharedRuntime::dtrace_object_alloc and dtrace_object_alloc_base, but didn't modified the callsites(interpreter/c1/c2).

To make this fix as simple as possible, I overloaded dtrace_object_alloc_base rather than dtrace_object_alloc.

Thanks,
Denghui

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276209](https://bugs.openjdk.java.net/browse/JDK-8276209): Some call sites doesn't pass the parameter 'size' to SharedRuntime::dtrace_object_alloc(_base)

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6181/head:pull/6181` \
`$ git checkout pull/6181`

Update a local copy of the PR: \
`$ git checkout pull/6181` \
`$ git pull https://git.openjdk.java.net/jdk pull/6181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6181`

View PR using the GUI difftool: \
`$ git pr show -t 6181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6181.diff">https://git.openjdk.java.net/jdk/pull/6181.diff</a>

</details>

### CODE REVIEW

**Comment by D-D-H** [comment]
Gentle ping?
This problem seems to have existed for a long time. I think it's because there are few users, so it's not reported
As far as I know, a BCC's tool relies on this probe.
https://github.com/iovisor/bcc/blob/master/tools/lib/uobjnew.py#L110

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
To me something like `dtrace_object_alloc_base` should not be called directly (like a foo_impl function) but only as the implementation of the real API entry points. If that isn't the case here then lets drop the "base" part and just have a set of overloaded `dtrace_object_alloc` functions.

Thanks,
David

**Comment by D-D-H** [comment]
> To me something like `dtrace_object_alloc_base` should not be called directly (like a foo_impl function) but only as the implementation of the real API entry points. If that isn't the case here then lets drop the "base" part and just have a set of overloaded `dtrace_object_alloc` functions.
> 
> Thanks, David

Changed.

Thanks,
Denghui

**Comment by dholmes-ora** [comment]
Did your change actually work? I just realized that you can't use this:

```__ call(RuntimeAddress(CAST_FROM_FN_PTR(address, static_cast<int (*)(oopDesc*)>(SharedRuntime::dtrace_object_alloc))));```

because it has no idea what overload of `dtrace_object_alloc` needs to be invoked.

David

**Comment by dholmes-ora** [comment]
Sorry ignore that. I see that is what the static_cast is intended to do. I got confused by the need to change the additional call-sites that already used `dtrace_object_alloc`, because they were the ones previously calling the two-arg function but only passing one arg!

**Review by dholmes-ora — APPROVED** [review]
I understand now what you meant by the additional overload complicating the fix - I hadn't appreciated that may have been the reason for using different names for the functions originally.

I'm still unclear why the lack of the size argument did not cause problems? I guess whatever random value was next on the stack got read as the size, but reading it caused no harm it was just incorrect.

These changes look good to me now.

Thanks,
David

**Comment by D-D-H** [comment]
Thank you, David.

Could I have another review?

**Review by coleenp — APPROVED** [review]
These casts are hard to look at but it seems fine.

**Pull request closed without merging**
