### PR TITLE
8273575: memory leak in appendBootClassPath(), paths must be deallocated

### PR DESCRIPTION
**Pull request by sspitsyn**
The memory allocated and hold in the paths local variable of function appendBootClassPath() is never deallocated:
    splitPathList(pathList, &count, &paths);
So, it is a memory leak which needs to be fixed.
The fix is to add one line at the end of function: 
    free(paths);

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273575](https://bugs.openjdk.java.net/browse/JDK-8273575): memory leak in appendBootClassPath(), paths must be deallocated

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Alex Menkov](https://openjdk.java.net/census#amenkov) (@alexmenkov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5516/head:pull/5516` \
`$ git checkout pull/5516`

Update a local copy of the PR: \
`$ git checkout pull/5516` \
`$ git pull https://git.openjdk.java.net/jdk pull/5516/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5516`

View PR using the GUI difftool: \
`$ git pr show -t 5516`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5516.diff">https://git.openjdk.java.net/jdk/pull/5516.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,
David

**Comment by fmatte1** [comment]
Changes looks good to me.

**Review by alexmenkov — APPROVED** [review]

**Comment by sspitsyn** [comment]
David, Fairoz and Alex, thank you for review!

**Pull request closed without merging**
