### PR TITLE
8266675: Optimize IntHashTable for encapsulation and ease of use

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

Currently, the class `com.sun.tools.javac.util.IntHashTable` exposes methods `hash(Object key)` and `lookup(Object key)` to users. It is not good because they are internal methods to achieve the features.

On the other hand, the index of the mapping (key or value) is the internal data struct. The users should not know or use it actually. So the parameters of the following methods should be revised.

1. lookup(Object key, int hash) -> lookup(Object key)
2. getFromIndex(int index) -> get(Object key)
3. putAtIndex(Object key, int value, int index) -> put(Object key, int value)

And the corresponding places where they are used need to be adjusted too.

The patch optimizes them, adds some comments and cleans the code.
Thank you for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266675](https://bugs.openjdk.java.net/browse/JDK-8266675): Optimize IntHashTable for encapsulation and ease of use

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3912/head:pull/3912` \
`$ git checkout pull/3912`

Update a local copy of the PR: \
`$ git checkout pull/3912` \
`$ git pull https://git.openjdk.java.net/jdk pull/3912/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3912`

View PR using the GUI difftool: \
`$ git pr show -t 3912`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3912.diff">https://git.openjdk.java.net/jdk/pull/3912.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Looks good!

**Comment by lgxbslgx** [comment]
@mcimadamore Thanks for your review. Could I get your help to sponsor this patch?

/integrate

**Pull request closed without merging**
