### PR TITLE
8264220: jdk/javadoc/doclet/testRelatedPackages/TestRelatedPackages.java fails to compile

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

jdk/javadoc/doclet/testRelatedPackages/TestRelatedPackages.java fails to compile.
Let's fix it.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264220](https://bugs.openjdk.java.net/browse/JDK-8264220): jdk/javadoc/doclet/testRelatedPackages/TestRelatedPackages.java fails to compile

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.java.net/census#hannesw) (@hns - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3208/head:pull/3208`
`$ git checkout pull/3208`

To update a local copy of the PR:
`$ git checkout pull/3208`
`$ git pull https://git.openjdk.java.net/jdk pull/3208/head`

### CODE REVIEW

**Review by hns — APPROVED** [review]
Sorry for the inconvenience, and thanks for looking into this and fixing it. It's quite easy to trip over how jtreg caches libraries.

**Comment by DamonFool** [comment]
Thanks @hns for your review.

Do you think it's trivial and can be pushed right now?
Thanks.

**Comment by hns** [comment]
I have tested the fix running jtreg in standalone mode and without precompiled test libraries. I verified the fix solves the problem, so yes, I think this can be pushed. 

What I do not understand is why there are other javadoc tests that build `toolbox.ToolBox` and do not have the `jdk.compiler` @modules tags, but still work in standalone mode without preexisiting JTwork directory. But that's a different problem, so I think it's safe to push this change.

**Comment by DamonFool** [comment]
Thanks @hns .
/integrate

**Pull request closed without merging**
