### PR TITLE
8252835: Revert fix for JDK-8246051

### PR DESCRIPTION
**Pull request by sandlerwang**
Reverting JDK-8246051(SIGBUS by unaligned Unsafe compare_and_swap) because it may cause some
runtime issues.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252835](https://bugs.openjdk.java.net/browse/JDK-8252835): Revert fix for JDK-8246051

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Mikael Vidstedt](https://openjdk.java.net/census#mikael) (@vidmik - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/297/head:pull/297`
`$ git checkout pull/297`

### CODE REVIEW

**Comment by sandlerwang** [comment]
https://bugs.openjdk.java.net/browse/JDK-8252835

**Review by PaulSandoz — APPROVED** [review]

**Comment by dholmes-ora** [comment]
The PR title needs to be edited to a space before "Revert in "8252835:Revert"

**Review by dholmes-ora — APPROVED** [review]
Reverting of changes looks good. Thanks.

**Review by vidmik — APPROVED** [review]

**Pull request closed without merging**
