### PR TITLE
8292407: Improve Weak CAS VarHandle/Unsafe tests resilience under spurious failures

### PR DESCRIPTION
**Pull request by shipilev**
We have a few reports that existing Weak* VarHandle tests are still flaky, for example on large AArch64 machines or small RISC-V machines.

The flakiness is intrinsic to the nature of Weak* operations under tests, that can spuriously fail. The last attempt to fix these was [JDK-8155739](https://bugs.openjdk.org/browse/JDK-8155739). We need to strengthen these a bit more.

The actual values depend on the successful testing on known-failing platforms. I ballparked bumping the attempts 5x and introducing the delay would help without exploding test time in worst cases.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292407](https://bugs.openjdk.org/browse/JDK-8292407): Improve Weak CAS VarHandle/Unsafe tests resilience under spurious failures

### Reviewers
 * [Yadong Wang](https://openjdk.org/census#yadongwang) (@yadongw - Author) ⚠️ Review applies to [b4f3890c](https://git.openjdk.org/jdk/pull/9889/files/b4f3890c670d84348b8d9c8dd568d2e52d312625)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [f049379b](https://git.openjdk.org/jdk/pull/9889/files/f049379b9e66e9aa359ce140b927a3b80251f60f)
 * [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - Committer) ⚠️ Review applies to [f049379b](https://git.openjdk.org/jdk/pull/9889/files/f049379b9e66e9aa359ce140b927a3b80251f60f)
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9889/head:pull/9889` \
`$ git checkout pull/9889`

Update a local copy of the PR: \
`$ git checkout pull/9889` \
`$ git pull https://git.openjdk.org/jdk pull/9889/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9889`

View PR using the GUI difftool: \
`$ git pr show -t 9889`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9889.diff">https://git.openjdk.org/jdk/pull/9889.diff</a>

</details>

### CODE REVIEW

**Comment by VladimirKempik** [comment]
Will test on hifive. and let you know the results, meanwhile, can you include these tests into your patch? , they fail with similar symptoms:

hotspot/jtreg/compiler/unsafe/JdkInternalMiscUnsafeAccessTest*.java

**Comment by VladimirKempik** [comment]
Results on hifive, running all tests in VarHandles dir:

Test results: passed: 22; failed: 2; error: 14

many tests timed out:

`VarHandleTestAccessChar.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 127589ms).
VarHandleTestAccessInt.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122091ms).
VarHandleTestAccessLong.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122116ms).
VarHandleTestByteArrayAsFloat.jtr:test result: Error. Program `bin/java' timed out (timeout set to 360000ms, elapsed time including timeout handling was 362103ms).
VarHandleTestByteArrayAsInt.jtr:test result: Error. Program `bin/java' timed out (timeout set to 360000ms, elapsed time including timeout handling was 362061ms).
VarHandleTestMethodHandleAccessBoolean.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122087ms).
VarHandleTestMethodHandleAccessByte.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122059ms).
VarHandleTestMethodHandleAccessChar.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122106ms).
VarHandleTestMethodHandleAccessDouble.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122093ms).
VarHandleTestMethodHandleAccessFloat.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122092ms).
VarHandleTestMethodHandleAccessInt.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122081ms).
VarHandleTestMethodHandleAccessLong.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122123ms).
VarHandleTestMethodHandleAccessShort.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122096ms).
VarHandleTestMethodHandleAccessString.jtr:test result: Error. Program `bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 122217ms).`

-------

two failed as before:

`
test VarHandleTestAccessShort.testAccess("VarHandle -> Array", VarHandle -> Array): failure
java.lang.AssertionError: weakCompareAndSetRelease short expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertEqualsImpl(Assert.java:140)
        at org.testng.Assert.assertEquals(Assert.java:122)
        at org.testng.Assert.assertEquals(Assert.java:819)
        at VarHandleTestAccessShort.testArray(VarHandleTestAccessShort.java:1073)
        at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:421)
        at VarHandleTestAccessShort.testAccess(VarHandleTestAccessShort.java:288)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
        at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:764)
        at org.testng.TestRunner.run(TestRunner.java:585)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.runSuites(TestNG.java:1069)
        at org.testng.TestNG.run(TestNG.java:1037)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:1589)
`

similar with  VarHandleTestAccessChar: 

java.lang.AssertionError: weakCompareAndSetRelease char expected [true] but found [false]

**Comment by snazarkin** [comment]
Tested aarch64 on AWS a1.xlarge instance: the issue is gone completely.

**Comment by VladimirKempik** [comment]
new patch test results: thead rvb-ice - all good.
hifive unmatched: some tests still fail intermittently:
VarHandleTestAccessShort.java
VarHandleTestMethodHandleAccess*.java

Will probably have to ignore these in test runs.

**Review by yadongw — APPROVED** [review]
lgtm.

**Review by RealFYang — APPROVED** [review]
The latest changes look good to me. I see all these tests pass stably on my aarch64-linux server.
This wll also improve the case for my riscv64-linux unmatched board: except for VarHandleTestMethodHandleAccess*.java, the other tests could also pass stably now.

**Comment by shipilev** [comment]
Yes, so I have reworked this to please more machines. I have clean run on RPi 4 (AArch64), and semi-clean run on HiFive Unmatched board (there are still some timeouts, but no weak failures). I believe the `VarHandleTestMethodHandleAccess` are slow themselves, and pairing them with a very slow board would run into problems. I'll look into speeding up `VarHandles` tests even more in separate PR.

If anyone is interested how this PR behaves on their platforms, feel free to test it! Thanks.

**Review by VladimirKempik — APPROVED** [review]
Same result as @RealFYang 's, VarHandleTestAccessShort.java is ok now
VarHandleTestMethodHandleAccess*.java time out

**Comment by TheRealMDoerr** [comment]
In general, I appreciate making these tests more resilient.
However, I wonder about such large numbers for retry attempts. Smells like more than just sporadic failures. Are we sure there is no bug which causes more failures? Does it really make sense to have a weak implementation on platforms with such high failure rates?

**Comment by shipilev** [comment]
> In general, I appreciate making these tests more resilient. However, I wonder about such large numbers for retry attempts. Smells like more than just sporadic failures. Are we sure there is no bug which causes more failures? Does it really make sense to have a weak implementation on platforms with such high failure rates?

I suspect we are dealing with the accidental cache line sharing, or context switching, or cache capacity limits that "break" LL/SC weak implementations. Backoff and more retries seems to help to pull ourselves out of this mess.

As the alternative, we can provide the whitelist of platforms where weak CAS is guaranteed to succeed. (We need to dig through if, for example, AArch64 LSE atomics provide more resilient progress behavior.) That would, unfortunately, stop to verify that some LL/SC implementations _ever_ succeed.

**Comment by TheRealMDoerr** [comment]
> > In general, I appreciate making these tests more resilient. However, I wonder about such large numbers for retry attempts. Smells like more than just sporadic failures. Are we sure there is no bug which causes more failures? Does it really make sense to have a weak implementation on platforms with such high failure rates?
> 
> I suspect we are dealing with the accidental cache line sharing, or context switching, or cache capacity limits that "break" LL/SC weak implementations. Backoff and more retries seems to help to pull ourselves out of this mess.
> 
> As the alternative, we can provide the whitelist of platforms where weak CAS is guaranteed to succeed. (We need to dig through if, for example, AArch64 LSE atomics provide more resilient progress behavior.) That would, unfortunately, stop to verify that some LL/SC implementations _ever_ succeed.

My concern is that we may not notice implementation problems any more when retrying so often. Accidental cache line sharing should better get fixed in the tests if possible. Context switching or cache capacity limits may cause 1 failure, not 100. What do you think?

**Comment by shipilev** [comment]
> My concern is that we may not notice implementation problems any more when retrying so often. Accidental cache line sharing should better get fixed in the tests if possible. Context switching or cache capacity limits may cause 1 failure, not 100. What do you think?

I would not dare to say that 100 retries is going to be enough for everything; I don't even dare to say that is "too many", my test experiments ran with tens of thousands retries before.

Here is a thing, though: for weak LL/SC hardware, we would enter the same kind (but unbounded!) retry loop inside strong CAS implementation. If the implementation is laggy, we would spin there a lot. In fact, I don't think anyone actually measured how much retries we need to succeed at strong CAS on such platforms. But as long as such CAS eventually succeeds, it looks to be a performance question, not the functionality one. The tests affected by this PR are testing the functional part: weak CAS _eventually_ succeeds after aggressive retries/backoffs.

The failing platforms I have (RISC-V) are remarkably slow to dissect what might be going on there. We can dive there, for sure, but I reckon that would take weeks to resolve. It can wait, if you feel strongly about it.

**Comment by PaulSandoz** [comment]
It's awkward to manage this across various hardware, esp. if the hardware is less mature (perhaps combined with a less mature HotSpot implementation). The approach looks reasonable, but it would be nice if we could just increase the values on weak LL/SC hardware or at least follow up with something like that later on.

As a quick experiment could we annotate fields with @Contended and see if that reduces the number of retries?

**Comment by shipilev** [comment]
I have found the related RISC-V issue that makes the tests very slow -- https://github.com/openjdk/jdk/pull/9970 -- I think we should let that one first, and then reconsider what backoffs we do here. Looks to me with that patch, HiFive Unmatched is fine with 1ms backoff delay, not 100ms as this PR proposes.

**Comment by TheRealMDoerr** [comment]
Excellent! Thank you!

**Comment by shipilev** [comment]
So, I have been playing with HiFive Unmatched board, and I can see that even in the single-threaded mode there weak CASes can spuriously fail when JIT compiler threads are very active at the same time. I suspect L1-tagging LR/SC fails just because we context-switch out a lot. 

On HiFive Unmatched, without any delay, it is common to see the long-tailed attempt counts that exceed 200 attempts. Adding the 1ms delay drops that long tail to fit under 10 attempts; I suspect because it provides a natural backoff on over-subscribed system, as thread would return back later if no resources are currently available. Still, that does not seem to hold when the rest of the system is running other parallel tests. Running `java/lang/invoke/VarHandles` with 50 attempts and 1ms delay still ocassionally fails the weak CAS tests. 

Running with 100 attempts and 1ms delay seems to pass it well (tried several times) -- which is what current version does. I think this is as good as it gets for a default mode. I also ran other platform tests, and there spurious failures are either not observed at all (x86 and friends), or we have 1..2 retries very rarely. This means the current 100 attempts would almost never be taken on those platforms, and thus we can avoid introducing any platform-specific test config selection.

**Comment by shipilev** [comment]
@PaulSandoz, @TheRealMDoerr -- are you okay with this?

**Review by PaulSandoz — APPROVED** [review]

**Comment by PaulSandoz** [comment]
@shipilev yes, seems reasonable, since spurious failures are rare on other platforms. Good effort digging into the RISC-V issues.

**Comment by TheRealMDoerr** [comment]
@shipilev yes, looks much better, now. Thanks for the extra effort!

**Comment by shipilev** [comment]
Thanks! I'll integrate then.

/integrate

**Pull request closed without merging**
