### PR TITLE
8326000: Remove obsolete comments for class sun.security.ssl.SunJSSE

### PR DESCRIPTION
**Pull request by RealCLanger**
The experimental SunJSSE FIPS compliant mode was removed in JDK13 with [JDK-8217835](https://bugs.openjdk.org/browse/JDK-8217835).
It seems the removal of some comments had been missed at that time. This could be irritating to readers of the code.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326000](https://bugs.openjdk.org/browse/JDK-8326000): Remove obsolete comments for class sun.security.ssl.SunJSSE (**Bug** - P4)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Anthony Scarpino](https://openjdk.org/census#ascarpino) (@ascarpino - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17885/head:pull/17885` \
`$ git checkout pull/17885`

Update a local copy of the PR: \
`$ git checkout pull/17885` \
`$ git pull https://git.openjdk.org/jdk.git pull/17885/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17885`

View PR using the GUI difftool: \
`$ git pr show -t 17885`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17885.diff">https://git.openjdk.org/jdk/pull/17885.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17885#issuecomment-1947451660)

### CODE REVIEW

**Comment by ascarpino** [comment]
You will need to update the copyright on the file.

**Comment by RealCLanger** [comment]
> You will need to update the copyright on the file.

Right. Updated.

**Review by MBaesken — APPROVED** [review]
Makes sense to remove the comment, it is more historical these days.
Or is there still a way to use SunJSSE FIPS compliant mode ?

**Comment by ascarpino** [comment]
> Makes sense to remove the comment, it is more historical these days. Or is there still a way to use SunJSSE FIPS compliant mode ?

There is no FIPS compliant mode.  This was a experimental feature that was never supported.

**Review by ascarpino — APPROVED** [review]

**Pull request closed without merging**
