### PR TITLE
8271217: Fix race between G1PeriodicGCTask checks and GC request

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to remove a race involving G1PeriodicGCTask.  The
task performs various checks to determine whether a periodic GC should be
performed.  If they pass, then it requests the GC by calling try_collect.
The problem is that an unrelated GC could occur after the task's checks but
before its request is processed.  In that case we don't want to do the
periodic GC after all, but there's nothing to prevent it.

This change lets the task capture the various GC counters as part of its
checking, and pass them to try_collect for use in detecting an intervening
GC.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271217](https://bugs.openjdk.java.net/browse/JDK-8271217): Fix race between G1PeriodicGCTask checks and GC request

### Reviewers
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to 0152fd58948c36f5aea0a7480423861333ac3631
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 0152fd58948c36f5aea0a7480423861333ac3631
 * [Leo Korinth](https://openjdk.java.net/census#lkorinth) (@lkorinth - **Reviewer**) ⚠️ Review applies to 0152fd58948c36f5aea0a7480423861333ac3631

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4905/head:pull/4905` \
`$ git checkout pull/4905`

Update a local copy of the PR: \
`$ git checkout pull/4905` \
`$ git pull https://git.openjdk.java.net/jdk pull/4905/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4905`

View PR using the GUI difftool: \
`$ git pr show -t 4905`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4905.diff">https://git.openjdk.java.net/jdk/pull/4905.diff</a>

</details>

### CODE REVIEW

**Review by walulyai — APPROVED** [review]
Lgtm!

**Review by tschatzl — APPROVED** [review]

**Review by lkorinth — APPROVED** [review]
Looks good to me.

If you like, you could initialize the values of the counters in the default constructor (to zero for example).

**Comment by kimbarrett** [comment]
> If you like, you could initialize the values of the counters in the default constructor (to zero for example).

I think initialized to zero is no better than uninitialized here. Either
way, a default-constructed object of this type shouldn't be given to
try_collect. In an unpublished development version I had a debug-only
is_initialized flag that was set appropriately by the constructors and
checked by the accessors, but decided it more clutter than it was worth and
dropped it.

**Comment by kimbarrett** [comment]
Thanks @walulyai , @tschatzl , and @lkorinth for reviews.

**Pull request closed without merging**
