### PR TITLE
JDK-8276649: MethodHandles.Lookup docs: replace the table in the cross-module access check section with list

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Inferring from the flow of the text, the table should have been a list all along, so I've made it that way. Before and after for comparison:
image
image

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276649](https://bugs.openjdk.java.net/browse/JDK-8276649): MethodHandles.Lookup docs: replace the table in the cross-module access check section with list

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6260/head:pull/6260` \
`$ git checkout pull/6260`

Update a local copy of the PR: \
`$ git checkout pull/6260` \
`$ git pull https://git.openjdk.java.net/jdk pull/6260/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6260`

View PR using the GUI difftool: \
`$ git pr show -t 6260`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6260.diff">https://git.openjdk.java.net/jdk/pull/6260.diff</a>

</details>

### CODE REVIEW

**Review by mlchung — COMMENTED** [review]
Replacing this single-column table with a list is okay. 

Is there a reason why you want to make it a list?

**Comment by LudwikJaniuk** [comment]
It was flagged as an accessibility issue by a scanning tool. I don't think it's going to make a world of difference, but if the tool says it's better, I suppose why not change it. Also, just feels more natural.

**Comment by mlchung** [comment]
That's what I suspect related to accessibility.  Thanks.

**Review by mlchung — APPROVED** [review]

**Comment by LudwikJaniuk** [comment]
@mlchung Could I ask you to sponsor this change?

**Comment by mlchung** [comment]
BTW, I updated the summary of JBS issue.  You will need to update this PR title to match it before integration.

**Pull request closed without merging**
