### PR TITLE
8276629: Use blessed modifier order in core-libs code

### PR DESCRIPTION
**Pull request by magicus**
I ran bin/blessed-modifier-order.sh on source owned by core-libs. This scripts verifies that modifiers are in the "blessed" order, and fixes it otherwise. I have manually checked the changes made by the script to make sure they are sound.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276629](https://bugs.openjdk.java.net/browse/JDK-8276629): Use blessed modifier order in core-libs code

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksei Efimov](https://openjdk.java.net/census#aefimov) (@AlekseiEfimov - Committer)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6250/head:pull/6250` \
`$ git checkout pull/6250`

Update a local copy of the PR: \
`$ git checkout pull/6250` \
`$ git pull https://git.openjdk.java.net/jdk pull/6250/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6250`

View PR using the GUI difftool: \
`$ git pr show -t 6250`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6250.diff">https://git.openjdk.java.net/jdk/pull/6250.diff</a>

</details>

### CODE REVIEW

**Comment by pavelrappo** [comment]
I can see that this PR changes java.naming. Another bug to change java.naming, JDK-8276552, was filed yesterday. Please check with its reporter to see if they were planning to make similar changes.

**Review by dholmes-ora — APPROVED** [review]
Looks fine to me.

Thanks,
David

**Comment by AlekseiEfimov** [comment]
> I can see that this PR changes java.naming. Another bug to change java.naming, JDK-8276552, was filed yesterday. Please check with its reporter and coordinate this effort if necessary.

@magicus I'm ok with having `java.naming` changes integrated as part of this PR.  I'll close `JDK-8276552` as duplicate. 
The changes looks fine to me.

**Review by AlekseiEfimov — APPROVED** [review]

**Comment by magicus** [comment]
@AlekseiEfimov Thanks! I tried to search for open PRs with blessed ordering, but I did not search open bugs...

**Review by dfuch — APPROVED** [review]

**Review by mlchung — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
