### PR TITLE
8295413: com/sun/jdi/EATests.java fails with compiler flag -XX:+StressReflectiveCode

### PR DESCRIPTION
**Pull request by reinrich**
With `StressReflectiveCode` C2 has inexact type information which can prevent ea
based optimizations (see `ConnectionGraph::add_call_node()`)

This pr changes the test jdk/com/sun/jdi/EATests.java to read the flag
`StressReflectiveCode`. If enabled it shall neither expect ea based optimizations
of allocations nor deoptimization of corresponding frames upon debugger access.

Tested on the standard platforms with fastdebug and release builds.

```
make test TEST=test/jdk/com/sun/jdi/EATests.java TEST_VM_OPTS="-XX:+IgnoreUnrecognizedVMOptions -XX:+StressReflectiveCode"
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295413](https://bugs.openjdk.org/browse/JDK-8295413): com/sun/jdi/EATests.java fails with compiler flag -XX:+StressReflectiveCode

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to [9071e5b4](https://git.openjdk.org/jdk/pull/10769/files/9071e5b45aa797d5cbfd489e4df32157a1a8f027)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10769/head:pull/10769` \
`$ git checkout pull/10769`

Update a local copy of the PR: \
`$ git checkout pull/10769` \
`$ git pull https://git.openjdk.org/jdk pull/10769/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10769`

View PR using the GUI difftool: \
`$ git pr show -t 10769`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10769.diff">https://git.openjdk.org/jdk/pull/10769.diff</a>

</details>

### CODE REVIEW

**Comment by reinrich** [comment]
The tests haven't finished in 12h. Not sure if they ever will...
Local testing (see above) was good though.

**Review by lmesnik — APPROVED** [review]

**Comment by reinrich** [comment]
> Should we add check for `StressReflectiveCode` to all `shouldSkip()` methods too? Similar to `DeoptimizeObjectsALot` flag.

I'd be ok to skip all testcases (by checking for `StressReflectiveCode` in the base classes' `shouldSkip()`). The tests' purpose is to check if ea based optimizations are reverted appropriately. Doesn't help much to run them with `StressReflectiveCode` except for random fuzzing.

Would you like me to skip all test cases if running with `StressReflectiveCode`?

**Comment by vnkozlov** [comment]
> > Should we add check for `StressReflectiveCode` to all `shouldSkip()` methods too? Similar to `DeoptimizeObjectsALot` flag.
> 
> I'd be ok to skip all testcases (by checking for `StressReflectiveCode` in the base classes' `shouldSkip()`). The tests' purpose is to check if ea based optimizations are reverted appropriately. Doesn't help much to run them with `StressReflectiveCode` except for random fuzzing.
> 
> Would you like me to skip all test cases if running with `StressReflectiveCode`?

Yes. If this flag essentially disables EA I don't see a reason to run EA related tests.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thanks,
Serguei

**Pull request closed without merging**
