### PR TITLE
8266496: WBIsKlassAliveClosure.do_klass() fails for hidden classes

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small fix for JDK-8266496.  The fix changes WBIsKlassAliveClosure.do_klass() so that when it compares the specified name with the name of a hidden class, it truncates the hidden class's name at the first '+' character before doing the comparison.  This should work except in the rare case when the pre-mangled hidden class name contains a '+' character.

The fix was tested with Mach5 tiers 1 and 2 on Linux, Mac OS, and Windows, and tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266496](https://bugs.openjdk.java.net/browse/JDK-8266496): WBIsKlassAliveClosure.do_klass() fails for hidden classes

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to c5e96925bc96e89837bc57a6fb592eceec549183
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Mikhailo Seledtsov](https://openjdk.java.net/census#mseledtsov) (@mseledts - Committer)
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3882/head:pull/3882` \
`$ git checkout pull/3882`

Update a local copy of the PR: \
`$ git checkout pull/3882` \
`$ git pull https://git.openjdk.java.net/jdk pull/3882/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3882`

View PR using the GUI difftool: \
`$ git pr show -t 3882`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3882.diff">https://git.openjdk.java.net/jdk/pull/3882.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Harold,

Fix seems fine - certainly good enough for whitebox purposes.

Does the test need to generate the classfile? can't you just define a class in the same source file and then read the class file from disk? Whenever I see asm being used I wonder what it is about the class that prevented it being written in Java.

Thanks,
David

**Comment by hseigel** [comment]
Hi David,
Thanks for reviewing this.  The test doesn't need to use asm.  It could load the class from disk as you suggested, or even use InMemoryJavaCompiler.  Please let me know if I should change the test.

Thanks, Harold

**Review by coleenp — APPROVED** [review]
LGTM!

**Review by mseledts — APPROVED** [review]
Change looks good to me.

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Comment by dholmes-ora** [comment]
No need to change test.

Thanks,
David

**Comment by hseigel** [comment]
Thanks David, Coleen, Misha and Lois for the reviews.

/integrate

**Pull request closed without merging**
