### PR TITLE
8273656: Improve java.lang.invoke.MethodType.parameterList() and its usage

### PR DESCRIPTION
**Pull request by stsypanov**
Currently the method is implemented like
```java
public List<Class<?>> parameterList() {
  return Collections.unmodifiableList(Arrays.asList(ptypes.clone()));
}
```
This seems to be excessive, as three objects are allocated here. Instead we can use `List.of(ptypes)` which doesn't allocate anything for empty array and for one of length 1 and 2 it allocates lightweight objects with 2 fields, still copying longer arrays. This is likely to be fruitful as most of methods have 0-2 parameters.

Also there is a couple of cases when `MethodType.parameterLis()` is called to get its size, which is excessive either as we can use `MethodType.parameterCount()` instead.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273656](https://bugs.openjdk.java.net/browse/JDK-8273656): Improve java.lang.invoke.MethodType.parameterList() and its usage

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5489/head:pull/5489` \
`$ git checkout pull/5489`

Update a local copy of the PR: \
`$ git checkout pull/5489` \
`$ git pull https://git.openjdk.java.net/jdk pull/5489/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5489`

View PR using the GUI difftool: \
`$ git pr show -t 5489`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5489.diff">https://git.openjdk.java.net/jdk/pull/5489.diff</a>

</details>

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
LGTM

**Comment by JornVernee** [comment]
I'm also running a test job for this change. If that comes back green I'll sponsor the PR after the 24 hour review period (in case anybody else wants to comment).

**Review by iwanowww — APPROVED** [review]
Looks good.

BTW it can be improved even further by caching the immutable List view of parameters.

**Review by mlchung — APPROVED** [review]
Looks good to me.

**Comment by cl4es** [comment]
This change introduces a subtle behavior change in that `List.of` produce a `null`-hostile list, for example `list.contains(null)` will throw NPE. Does this need to be spelled out? (FTR I think such null-hostile behavior should be reconsidered)

**Comment by stsypanov** [comment]
@cl4es null-issue was the one I was afraid most of all in this case. I think that the initial array `ptypes` never contains null elements due to it's business meaning (we cannot have a param without type). Also we do explicit null-check in `checkPtypes()` method, called from `makeImpl()`.

**Comment by JornVernee** [comment]
> Mailing list message from John Rose on core-libs-dev:
> 
> On Sep 13, 2021, at 10:24 AM, Vladimir Ivanov <vlivanov at openjdk.java.net<mailto:vlivanov at openjdk.java.net>> wrote:
> 
> BTW it can be improved even further by caching the immutable List view of parameters.
> 
> I would go further: If I were writing MethodType.java today
> I would probably use List.of as the backing store for the
> parameters, instead of the private array. So ptypes should
> be List<Class<?>> not Class<?>[]. I don?t think the footprint
> or polymorphism effects would be dealbreakers, and the
> code would (I think) be simpler overall. But that?s a messy
> change, since the array representation is dug in.

Another thing that makes this change hard is that `MethodType` is mapped directly in HotSpot, so that HotSpot can retrieve for instance the parameter types [1]. The VM already knows how to dig into arrays, but adding support for `List` as well seems more cumbersome, since the list internals can change, and AFAIK most VM code can not just call `List::get`.

[1] : https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/javaClasses.cpp#L4135-L4137

**Comment by JornVernee** [comment]
The null-hostile-ness of `contains` is not something I thought about. It would have been good to mention that in the PR body as well. FWIW, I did a search on grep.app for `parameterList()` calls in java [1] and don't really see any calls to `contains`.

I think process-wise creating a CSR would be good as documentation, and shouldn't be too much work. Though, I'm not familiar with the process of filing a CSR after a patch has already been merged.

[1] : https://grep.app/search?q=.parameterList%28%29&filter[lang][0]=Java

**Comment by cl4es** [comment]
I think it's OK and even expected to file a CSRs retroactively when you realize post integration that there's a behavior change. I recall doing so at least once in the past.

**Pull request closed without merging**
