### PR TITLE
8267112: JVMCI compiler modules should be kept upgradable

### PR DESCRIPTION
**Pull request by vnkozlov**
[JDK-8264806](https://bugs.openjdk.java.net/browse/JDK-8264806) changes removed sources and also removed JVMCI compiler from list of upgradable modules. JVMCI compiler modules should be upgradable in JDK to work with GraalVM. 

Make these modules upgradable again and empty by leaving only reference to JVMCI (jdk.internal.vm.ci) module. It does not restore sources - only `module-info.java` files are kept.

Note, we continue discussion about [JDK-8265091](https://bugs.openjdk.java.net/browse/JDK-8265091): "Use Module API to export JVMCI packages at runtime" to see if we can remove these `module-info.java` files.

Changes were proposed by @dougxc after testing [JDK-8264806](https://bugs.openjdk.java.net/browse/JDK-8264806) changes with GraalVM.
I restored related code in some tests for them to pass.

Testing: full tier1-tier3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267112](https://bugs.openjdk.java.net/browse/JDK-8267112): JVMCI compiler modules should be kept upgradable

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * dnsimon - Committer ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4014/head:pull/4014` \
`$ git checkout pull/4014`

Update a local copy of the PR: \
`$ git checkout pull/4014` \
`$ git pull https://git.openjdk.java.net/jdk pull/4014/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4014`

View PR using the GUI difftool: \
`$ git pr show -t 4014`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4014.diff">https://git.openjdk.java.net/jdk/pull/4014.diff</a>

</details>

### CODE REVIEW

**Comment by dougxc** [comment]
Looks good. My only suggestion would have been to avoid mentioning "Graal" in the PR title and description. This is really about making `jdk.internal.vm.compiler` a placeholder module for any JVMCI based compiler, of which Graal is one example.

**Review by mlchung — APPROVED** [review]

**Comment by vnkozlov** [comment]
Thank you, Mandy.

**Comment by vnkozlov** [comment]
@erikj79, are you okay with these changes?

**Review by erikj79 — APPROVED** [review]

**Comment by vnkozlov** [comment]
Thank you, Erik.

**Pull request closed without merging**
