### PR TITLE
8344583: Make ArchiveWorkers lifecycle robust

### PR DESCRIPTION
**Pull request by shipilev**
It is obvious from the bug report that `ArchiveWorkers` lifecycle is not robust enough. Looks like archive workers escape their normal shutdown sequence when an unusual VM exit path is taken. We have tried to capture this in before_exit, but that is obviously not enough.

This PR reworks the lifecycle a bit: we now use the scoped object to manage `ArchiveWorkers` state. Previous version was carrying `ArchiveWorkers` for the entire lifecycle of CDS archive load path, but that runs into problems when VM exits in the middle of it. This PR shortens the lifecycle of `ArchiveWorkers` to the only place where they are used. To avoid the loss of usefulness, we now allow multiple pool restarts, so if any other code would need these workers, they can restart the pool again. New gtest checks this works.

Additional testing:
 - [x] macos-aarch64-server-fastdebug: reported failing tests are not failing anymore
 - [x] macos-aarch64-server-fastdebug, `tier{1,2}`
 - [x] linux-x86_64-server-fastdebug, `all`

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344583](https://bugs.openjdk.org/browse/JDK-8344583): Make ArchiveWorkers lifecycle robust (**Bug** - P2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22276/head:pull/22276` \
`$ git checkout pull/22276`

Update a local copy of the PR: \
`$ git checkout pull/22276` \
`$ git pull https://git.openjdk.org/jdk.git pull/22276/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22276`

View PR using the GUI difftool: \
`$ git pr show -t 22276`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22276.diff">https://git.openjdk.org/jdk/pull/22276.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22276#issuecomment-2488531484)
</details>

### CODE REVIEW

**Comment by shipilev** [comment]
>  ⚠️ OCA signatory status must be verified

Wait, really? @robilad, something is off here.

**Review by dholmes-ora — COMMENTED** [review]
I'm struggling to see the complete picture with this code (and I still have concerns about the impact of this new thread pool on startup!).

As far as I can tell the crash arises because we have a static `ArchiveWorkers` which embeds two `Semaphore`s. When the VM terminates and the static destructors are run, those `Semaphore`s get blown away. If the `ArchiveWorkerThreads are still running in the process when that happens they trigger the crash.

I can't determine from this PR how the changes prevent that from happening. ??

Also with this code:
```
ArchiveWorkerThread::ArchiveWorkerThread(ArchiveWorkers* pool) : NamedThread(), _pool(pool) {
  set_name("ArchiveWorkerThread");
  os::create_thread(this, os::os_thread);
  os::start_thread(this);
}
```
please note the cautionary comment in os.cpp:
```
// The INITIALIZED state is distinguished from the SUSPENDED state because the
// conditions in which a thread is first started are different from those in which
// a suspension is resumed.  These differences make it hard for us to apply the
// tougher checks when starting threads that we want to do when resuming them.
// However, when start_thread is called as a result of Thread.start, on a Java
// thread, the operation is synchronized on the Java Thread object.  So there
// cannot be a race to start the thread and hence for the thread to exit while
// we are working on it.  **Non-Java threads that start Java threads either have
// to do so in a context in which races are impossible, or should do appropriate
// locking.**

void os::start_thread(Thread* thread) {
```

It could perhaps be made clearer that it applies to creation/starting of all threads in this way: you must ensure the thread being started cannot run to completion and terminate and be deallocated before the starting thread can fully return from the synchronization code that is part of the thread startup protocol.

**Comment by shipilev** [comment]
> I'm struggling to see the complete picture with this code (and I still have concerns about the impact of this new thread pool on startup!).

We _are_ doing this to optimize startup, because we spend a lot of time relocating CDS archive, see the original https://github.com/openjdk/jdk/pull/21302#issuecomment-2388349450. 

I have now re-measured it to see if moving the mark exactly near the only current use still helps startup, and it does, at the same level. So we can make the lifecycle even tighter, and never start the pool if we do not need relocations, or `-XX:-AOTCacheParallelRelocation` is deliberately specified. This insulates us from issues even further. Done this in new commit.

**Comment by dholmes-ora** [comment]
I don't think the issue is the normal operation of this pool. Let your pool be active and the workers working away quite merrily. Unrelated to the pool an error is encountered, the VM crashes and the process starts to terminate. We run the static dtors while your pool threads are still active and trying to use the Semaphores that have now been deleted.

This seems to be causing a lot of failures in our higher tier testing now.

**Comment by shipilev** [comment]
All right, we are backing out with [JDK-8344830](https://bugs.openjdk.org/browse/JDK-8344830). I am going to fold this PR into redo: [JDK-8344831](https://bugs.openjdk.org/browse/JDK-8344831).

**Pull request closed without merging**
