### PR TITLE
8299330: Minor improvements in MSYS2 Workflow handling

### PR DESCRIPTION
**Pull request by TheShermanTanker**
MSYS2 should be more appropriately installed into the runner's temporary directory rather than inside the newly checked out repository containing all the JDK's source code, as doing so may interfere with the build process and cause weird corner cases in the submitted actions workflow. On windows, the bash it uses is also not run properly, which we should address

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299330](https://bugs.openjdk.org/browse/JDK-8299330): Minor improvements in MSYS2 Workflow handling

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [1d1b10cc](https://git.openjdk.org/jdk/pull/11782/files/1d1b10ccdd91b817f1729d08ed9d625fa13ab273)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11782/head:pull/11782` \
`$ git checkout pull/11782`

Update a local copy of the PR: \
`$ git checkout pull/11782` \
`$ git pull https://git.openjdk.org/jdk pull/11782/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11782`

View PR using the GUI difftool: \
`$ git pr show -t 11782`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11782.diff">https://git.openjdk.org/jdk/pull/11782.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Looks good to me. But you should wait for approval of somebody from the build group.

**Comment by TheShermanTanker** [comment]
Thanks for the review, will do :)

**Comment by TheShermanTanker** [comment]
build-dev has been unusually quiet these past few days, hopefully everything on their end is alright

**Comment by shipilev** [comment]
I don't quite understand what is the issue here. We do drop quite a bit of things in the OpenJDK root: bootjdk, gtest, jtreg, etc. How is msys2 different here? I would be more concerned about depleting the tmp space on the runner after this patch.

**Comment by TheShermanTanker** [comment]
> I don't quite understand what is the issue here. We do drop quite a bit of things in the OpenJDK root: bootjdk, gtest, jtreg, etc. How is msys2 different here?

Unlike the compiled JDK and those other utilities MSYS2 happens to be oddly sensitive to the paths being used in general, particularly when competing with the preinstalled tools that come with the runner, and has not fared very well from inside the source directory itself, to the point where tools that we explicitly request from MSYS2 are entirely ignored for tools that come with the preinstalled Git (tar is one such example). Another is the environment setup that it's bash seems to require, which caused a massive fiasco with https://github.com/openjdk/jdk/pull/11020 (the amount of test failures on Windows there is astounding). We've only been avoiding a guaranteed chance of Windows tests always failing during configure because prior to https://github.com/openjdk/jdk/pull/11020 the configure process somehow managed to function with a barely functional Unix environment. I don't know why MSYS2 is so sensitive, but installing it outside of the source directory seems to help with some of these issues

> I would be more concerned about depleting the tmp space on the runner after this patch.

Runners typically have a temporary cache size of 14GB, while the MSYS2 that we install for workflows is around 400MB in terms of size, base installation and all utils combined, so the chance of that happening isn't particularly high. That said, that is a good catch, since I overlooked the actual tool cache, which is provided by the runner for the tools one might need in an action and also reset with every run. That's probably more appropriate for installing MSYS into than the temp directory, and also uses the same (much larger) disk as the rest of the workflow, which (hopefully) addresses the concern that it might deplete disk space entirely mid-run

> We do drop quite a bit of things in the OpenJDK root: bootjdk, gtest, jtreg, etc

To be honest, I'm not very fond of those being placed into the source directory either, but I guess that's a discussion for another day

**Comment by TheShermanTanker** [comment]
Pinging @magicus when he returns, since this is related to https://github.com/openjdk/jdk/pull/11020

**Comment by magicus** [comment]
Hi, I'm back today from vacation and is trying to catch up, so your timing was excellent. ;)

This looks good. I have seen your attempt at fighting with GHA in #11020, and I am impressed with your patience and stubborness. :-) I'm glad it panned out in a solution.

I deliberately designed the GHA code so that each action that installs some part returns the path. This means it should be trivial to move where gtest, jtreg etc is installed as well. I did not specifically study the different storage roots provided by GHA, so it might very well be the case that all of these should be stored in the tool cache as well. If this is your conclusion, feel free to open a new PR where you update them in the same way.

**Review by magicus — APPROVED** [review]

**Review by magicus — CHANGES_REQUESTED** [review]
Actually, hold your horses. I checked the GHA run, and there were a lot of failures on windows... `tar` did not work, and seems it tried to pick up one from the Git unix env.

**Comment by magicus** [comment]
```
windows-aarch64 / build (debug)
 Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
--
windows-x64 / build (release)
Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

etc...

**Comment by TheShermanTanker** [comment]
> Hi, I'm back today from vacation and is trying to catch up, so your timing was excellent. ;)

Haha, Merry Christmas and a Happy New Year, hope you had a good time with your family :)

> This looks good. I have seen your attempt at fighting with GHA in #11020, and I am impressed with your patience and stubbornness. :-) I'm glad it panned out in a solution.

I don't think I've ever been able to sleep whenever I've run into a problem with anything about the JDK that doesn't initially work :P
Maybe I should apply for a job at Oracle and work full time on the Java Platform, wonder how that will turn out, heh

> I deliberately designed the GHA code so that each action that installs some part returns the path. This means it should be trivial to move where gtest, jtreg etc is installed as well. I did not specifically study the different storage roots provided by GHA, so it might very well be the case that all of these should be stored in the tool cache as well. If this is your conclusion, feel free to open a new PR where you update them in the same way.

It depends, if we are using a GitHub hosted runner (which I am very confident we are) the tool cache would be more appropriate for dumping all our required utils than the source directory

> Actually, hold your horses. I checked the GHA run, and there were a lot of failures on windows... `tar` did not work, and seems it tried to pick up one from the Git unix env.

Uh oh, that isn't good. Part of the reason for the changes here is to fix that issue (I've checked the Actions and this issue is pretty much always there on Windows). Strange, I checked the early GHA runs of this PR and it did fix the problem, why the regression now? Sigh...

**Comment by TheShermanTanker** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/a33d7fe0-8616-4417-9d7c-63878a5dda1d/_apis/pipelines/1/runs/813/signedlogcontent/33?urlExpires=2023-01-12T14%3A04%3A42.7284558Z&urlSigningMethod=HMACV1&urlSignature=JbidJc3t8aoT0Jkwb64W9u7vu6dCOQ5%2F01i7Juxy1as%3D

Linking the log from another unrelated PR of mine (https://github.com/openjdk/jdk/pull/11431) to confirm that the tar issue isn't related to this change. Maybe we need to selectively disable some of the Git tools for this to truly work properly?

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
> > Hi, I'm back today from vacation and is trying to catch up, so your timing was excellent. ;)
> 
> Haha, Merry Christmas and a Happy New Year, hope you had a good time with your family :)

Actually, I spent most of the time isolated getting a too intimate time with the SARS-CoV-2 virus. :-( Worst holiday ever, would rate 1/5. (And this was despite triple vaccines...) 

> It depends, if we are using a GitHub hosted runner (which I am very confident we are) the tool cache would be more appropriate for dumping all our required utils than the source directory

Yes we are. At least the normal OpenJDK GHA system. I assume someone could pay Github and setup personally hosted runners, in theory.

> Linking the log from another unrelated PR of mine (https://github.com/TheShermanTanker/jdk/actions/runs/3892586367/jobs/6644178546) to confirm that the tar issue isn't related to this change.

That's good news. I approved this PR now.

> Maybe we need to selectively disable some of the Git tools for this to truly work properly?

If that is a separate issue, that happens intermittently, I don't even know how to address it. Strange that it happened on multiple separate machines at the same time, even though it seems to be a runner-local problem. But in any case it is a separate issue from this.

**Review by magicus — APPROVED** [review]

**Comment by TheShermanTanker** [comment]
Aw :( Hope you're feeling better now at least

In any case, thanks for the review, I'll probably take the tar issue to build-dev so others can chip in, because I am at a loss as well. Will let the tests run and check the configure step on Windows one last time before integrating

**Comment by TheShermanTanker** [comment]
Alright, configure stage passes. @ GitHub for the love of god, please implement setting `merge_commit_sha` from the API so we can mark our Pull Requests as having been properly merged

**Comment by RealCLanger** [comment]
Regarding the tar issue: It happens in the post steps, when GHA does the caching. So I believe caching is broken. Somehow some msys2 libraries conflict with git's cygwin version of tar. I guess the fix would be to find a way to update the PATH to exclude msys2 again after our work is done and before the caching post steps run...

**Comment by magicus** [comment]
@RealCLanger Oh, thanks for the analysis! I believe it should be possible to update the PATH; it might require a bit of trickery/ugliness, as so many other things in this yaml "programming language", but it can most likely be done.

**Pull request closed without merging**
