### PR TITLE
8230486: G1BarrierSetAssembler::g1_write_barrier_post unnecessarily pushes/pops new_val

### PR DESCRIPTION
**Pull request by albertnetymk**
Removes the unnecessary push/pop instruction.

Test: hotspot_gc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8230486](https://bugs.openjdk.java.net/browse/JDK-8230486): G1BarrierSetAssembler::g1_write_barrier_post unnecessarily pushes/pops new_val

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4063/head:pull/4063` \
`$ git checkout pull/4063`

Update a local copy of the PR: \
`$ git checkout pull/4063` \
`$ git pull https://git.openjdk.java.net/jdk pull/4063/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4063`

View PR using the GUI difftool: \
`$ git pr show -t 4063`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4063.diff">https://git.openjdk.java.net/jdk/pull/4063.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — COMMENTED** [review]
aarch64 looks like it has the same problem.  I think other platforms don't.

**Review by tschatzl — APPROVED** [review]
Looks good.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
