### PR TITLE
8297313: Refactor APIs for calculating address of CDS archive heap regions

### PR DESCRIPTION
**Pull request by iklam**
In anticipation of the following RFEs:

- [JDK-8296263](https://bugs.openjdk.org/browse/JDK-8296263): Uniform APIs for using archived heap regions
- [JDK-8296344](https://bugs.openjdk.org/browse/JDK-8296344): Remove dependency on G1 for writing the CDS archive heap

We need to clean up the APIs for calculating the addresses of CDS archive heap regions.  The current APIs have confusing names and the implementation is convoluted.

The proposal is to change the above to three APIs with easy-to-understand semantics:
```
// The actual address of this region during dump time.
address heap_region_dumptime_address(FileMapRegion* r)

// The address where this region can be mapped into the runtime heap without
// patching any of the pointers that are embedded in this region.
address heap_region_requested_address(FileMapRegion* r)

// The address where this shared heap region is actually mapped at runtime.
address heap_region_mapped_address(FileMapRegion* r)
```

The meaning of the `CDSFileMapRegion::_mapping_offset` field is changed slightly to simplify the implementation of the above 3 functions. Comments are improved explain what's going on.

With the above changes, `FileMapInfo::map_heap_regions_impl()` can also be simplified significantly.

****
Testing: tiers 1-4
****
Misc changes:
- added more assertions about exactly which combinations of collector and oop encoding mode are supported
  - Specifically, uncompressed oops for non-G1 collectors are currently not supported;
  - Change error message accordingly when the user selects an unsupported combination.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297313](https://bugs.openjdk.org/browse/JDK-8297313): Refactor APIs for calculating address of CDS archive heap regions

### Reviewers
 * [Matias Saavedra Silva](https://openjdk.org/census#matsaave) (@matias9927 - Author) ⚠️ Review applies to [07891986](https://git.openjdk.org/jdk/pull/11257/files/07891986cf0e517ee099a89f5d1da95f74963f89)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to [07891986](https://git.openjdk.org/jdk/pull/11257/files/07891986cf0e517ee099a89f5d1da95f74963f89)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11257/head:pull/11257` \
`$ git checkout pull/11257`

Update a local copy of the PR: \
`$ git checkout pull/11257` \
`$ git pull https://git.openjdk.org/jdk pull/11257/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11257`

View PR using the GUI difftool: \
`$ git pr show -t 11257`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11257.diff">https://git.openjdk.org/jdk/pull/11257.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Note: this is a redo of the withdrawn  RFE [JDK-8296155](https://bugs.openjdk.org/browse/JDK-8296155) (Simplify CDS heap region address calculation, see #10923).

While reviewing [JDK-8296263](https://bugs.openjdk.org/browse/JDK-8296263) (Uniform APIs for using archived heap regions, see #10970) and discussing with its author, @ashu-mehra, I realized that the the APIs for calculating the addresses of CDS archive heap regions are problematic and will hinder further development. I also realized that [JDK-8296155](https://bugs.openjdk.org/browse/JDK-8296155) was not fixing the problem in the right direction. Therefore, I withdrew [JDK-8296155](https://bugs.openjdk.org/browse/JDK-8296155) and I am trying again with this RFE.

Thanks to @ashu-mehra for his insights and contributions to the proposed design.

**Review by matias9927 — APPROVED** [review]
Looks good to me!

**Review by calvinccheung — APPROVED** [review]
Looks good. One nit below.

**Comment by iklam** [comment]
Thanks @matias9927 and @calvinccheung for the review.
/integrate

**Pull request closed without merging**
