### PR TITLE
8270874: JFrame paint artifacts when dragged from standard monitor to HiDPI monitor

### PR DESCRIPTION
**Pull request by mrserb**
The bug occurs more often if initially the window is moved partly outside of the first screen(let's name this part as the invisible part), and then slowly moved to the second screen where that invisible part became visible on the second screen.

The problem is how we try to repaint the frame. The Windows send us coordinates to repaint in the device space, if the width/height values are less than a unit in the user's space, we round it to the empty rectangle and skip it.

Solution: request to repaint the smallest non-empty bounding box in the user's space around the region of pixels.

Workaround: repaint the whole window on the component resize/move event or at the end of the drag.

Notes:
 * It is not reproducible(at least much less often) when d3d is enabled because the d3d pipeline sends repaint events more often (example https://github.com/openjdk/jdk/pull/6064). That hides the current issue.
 * It started to be reproducible during the drag from one screen to another after JDK-8211999 because before JDK-8211999 we make a resize at the end of the drag, which caused the full repaint of the window.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270874](https://bugs.openjdk.java.net/browse/JDK-8270874): JFrame paint artifacts when dragged from standard monitor to HiDPI monitor

### Reviewers
 * [Jayathirth D V](https://openjdk.java.net/census#jdv) (@jayathirthrao - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6339/head:pull/6339` \
`$ git checkout pull/6339`

Update a local copy of the PR: \
`$ git checkout pull/6339` \
`$ git pull https://git.openjdk.java.net/jdk pull/6339/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6339`

View PR using the GUI difftool: \
`$ git pr show -t 6339`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6339.diff">https://git.openjdk.java.net/jdk/pull/6339.diff</a>

</details>

### CODE REVIEW

**Comment by jayathirthrao** [comment]
Please correct my understanding. Does this refined repaint logic apply even for overlapping Windows? What happens when 2 windows are overlapping and we move top window slowly? Any performance/power impact?

**Comment by mrserb** [comment]
> Please correct my understanding. Does this refined repaint logic apply even for overlapping Windows? What happens when 2 windows are overlapping and we move top window slowly? Any performance/power impact?

Initially, this code was used just for that, to make a fast blit of the content from the Swing back buffer to the native window, when some other window is moved over the Swing and damaged it (the fix for the "grey rectangle" JDK-4967886). But since Windows Vista the Windows itself maintain such doublebuffer and the content is not damaged when windows overlap, so this callback is not called.

**Comment by jayathirthrao** [comment]
> > Please correct my understanding. Does this refined repaint logic apply even for overlapping Windows? What happens when 2 windows are overlapping and we move top window slowly? Any performance/power impact?
> 
> Initially, this code was used just for that, to make a fast blit of the content from the Swing back buffer to the native window, when some other window is moved over the Swing and damaged it (the fix for the "grey rectangle" JDK-4967886). But since Windows Vista the Windows itself maintain such doublebuffer and the content is not damaged when windows overlap, so this callback is not called.

Thanks for the clarification

**Review by jayathirthrao — APPROVED** [review]

**Pull request closed without merging**
