### PR TITLE
8310225: Reduce inclusion of oopMapCache.hpp and generateOopMap.hpp

### PR DESCRIPTION
**Pull request by iklam**
These includes aren't necessary and should be removed:

frame_x86.inline.hpp -> oopMapCache.hpp -> generateOopMap.hpp.

Before:
frame_x86.inline.hpp included 571 times
oopMapCache.hpp included 571 times
generateOopMap.hpp included 571 times

After:
frame_x86.inline.hpp included 571 times
oopMapCache.hpp included 21 times
generateOopMap.hpp included 21 times

(as calculated by https://github.com/iklam/tools/blob/main/headers/whoincludes.tcl)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310225](https://bugs.openjdk.org/browse/JDK-8310225): Reduce inclusion of oopMapCache.hpp and generateOopMap.hpp (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14525/head:pull/14525` \
`$ git checkout pull/14525`

Update a local copy of the PR: \
`$ git checkout pull/14525` \
`$ git pull https://git.openjdk.org/jdk.git pull/14525/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14525`

View PR using the GUI difftool: \
`$ git pr show -t 14525`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14525.diff">https://git.openjdk.org/jdk/pull/14525.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14525#issuecomment-1595046222)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Good!

**Comment by tstuefe** [comment]
Failing GHAs could be related to JDK-8310183.

**Review by coleenp — APPROVED** [review]
Good!

**Comment by iklam** [comment]
Thanks @tstuefe and @coleenp for the review!

Merged with mainline and reran tier1 + builds-tier5 tests.

/integrate

**Pull request closed without merging**
