### PR TITLE
8286559: Re-examine synchronization of mark and reset methods on InflaterInputStream

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change that addresses https://bugs.openjdk.java.net/browse/JDK-8286559? 

The commit here removes the `synchronized` on `mark` and `reset` methods of `InflaterInputStream`. The `mark` method is a no-op method and the `reset` method only always throws a `IOException`. So `synchronized` isn't adding any value here. 

Additionally, the commit does a minor change to the javadoc of these methods to use `@implNote` to describe what the implementation does. Please let me know if the `@implNote` is unnecessary, in which case, I'll revert that part.

This change is similar to what was recently done for `FilterInputStream` https://github.com/openjdk/jdk/pull/8309 and `PushbackInputStream` https://github.com/openjdk/jdk/pull/8433

tier1, tier2 and tier3 tests were run and no related failures were noticed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8286559](https://bugs.openjdk.java.net/browse/JDK-8286559): Re-examine synchronization of mark and reset methods on InflaterInputStream
 * [JDK-8286579](https://bugs.openjdk.java.net/browse/JDK-8286579): Re-examine synchronization of mark and reset methods on InflaterInputStream (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to [89de6078](https://git.openjdk.java.net/jdk/pull/8649/files/89de6078d4ff242de5fbe44bdea26ef43409b07f)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8649/head:pull/8649` \
`$ git checkout pull/8649`

Update a local copy of the PR: \
`$ git checkout pull/8649` \
`$ git pull https://git.openjdk.java.net/jdk pull/8649/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8649`

View PR using the GUI difftool: \
`$ git pr show -t 8649`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8649.diff">https://git.openjdk.java.net/jdk/pull/8649.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Lance, thank you for the review. I have created a CSR for this now - https://bugs.openjdk.java.net/browse/JDK-8286579

**Review by AlanBateman — APPROVED** [review]

**Review by bplb — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you everyone for the reviews here and on the CSR.

**Pull request closed without merging**
