### PR TITLE
8278351: Add function to retrieve worker_id from any context

### PR DESCRIPTION
**Pull request by pliden**
The `worker_id` argument passed to `WorkerTask::work(uint worker_id)` is sometimes needed in contexts where it today can't be easily accessed, mainly because it's not feasible to pass this argument through many layers of semi-unrelated code. To solve this, I propose that we make the current `worker_id` accessible though a static function `WorkerThread::worker_id()`.

By doing this, we also pave the way for ZGC to remove its `ZTask` and `ZThread`, which are helper class to make the `worker_id` easily accessible in any context.

At the same time I propose that we remove `WorkerThread::_id`. This id identifies the actual worker thread. There is currently only one user of `WorkerThread::_id`, the `ReferenceProcessor`. However, we should use `WorkerThread::worker_id()` here instead. The only reason it doesn't use `worker_id` today is that it's not easily accessible in that context (the discover path).

Testing: Passed Tier1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278351](https://bugs.openjdk.java.net/browse/JDK-8278351): Add function to retrieve worker_id from any context

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to 67d3299cf05f135fe1fa7bb775875722635fb482
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to f669780d6a1a37f514039c8cc36199f80469ebdf
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to 67d3299cf05f135fe1fa7bb775875722635fb482

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6747/head:pull/6747` \
`$ git checkout pull/6747`

Update a local copy of the PR: \
`$ git checkout pull/6747` \
`$ git pull https://git.openjdk.java.net/jdk pull/6747/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6747`

View PR using the GUI difftool: \
`$ git pr show -t 6747`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6747.diff">https://git.openjdk.java.net/jdk/pull/6747.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by pliden** [comment]
Updated after comments from @albertnetymk, who through `which` wasn't a good name. Renamed it to `name_suffix` and added a separate `on_create_worker()` hook to avoid exposing that number outside of the `WorkerThreads`.

**Review by albertnetymk — APPROVED** [review]

**Review by fisk — APPROVED** [review]

**Comment by pliden** [comment]
Thanks for reviewing!

/integrate

**Pull request closed without merging**
