### PR TITLE
8295006: Colored text is not shown on disabled checkbox and radio button with GTK LAF for bug4314194.

### PR DESCRIPTION
**Pull request by kumarabhi006**
Existing test `open/test/jdk/javax/swing/JRadioButton/4314194/bug4314194.java` was not showing colored text for disabled checkbox and radiobutton in GTK LAF.

The fix is to get the disabled state color for checkbox and radiobutton from UIManager if it exists. 

Test case `open/test/jdk/javax/swing/JRadioButton/4314194/bug4314194.java` has been checked in CI pipeline. Link is attached in JBS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295006](https://bugs.openjdk.org/browse/JDK-8295006): Colored text is not shown on disabled checkbox and radio button with GTK LAF for bug4314194.

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10755/head:pull/10755` \
`$ git checkout pull/10755`

Update a local copy of the PR: \
`$ git checkout pull/10755` \
`$ git pull https://git.openjdk.org/jdk pull/10755/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10755`

View PR using the GUI difftool: \
`$ git pr show -t 10755`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10755.diff">https://git.openjdk.org/jdk/pull/10755.diff</a>

</details>

### CODE REVIEW

**Comment by kumarabhi006** [comment]
@TejeshR13 @prsadhuk Please review the PR.

**Comment by mrserb** [comment]
Why we did not get this colors from the native system? I also suggest to check an initial [fix](https://github.com/openjdk/jdk/pull/10177#issuecomment-1276765550). looks like it contradicts the specification.

**Comment by kumarabhi006** [comment]
> Why we did not get this colors from the native system? I also suggest to check an initial [fix](https://github.com/openjdk/jdk/pull/10177#issuecomment-1276765550). looks like it contradicts the specification.

The color returned from the native system is `grey` even though the user has explicitly set it to be some other color in GTK LAF. So, `UIManager.getColor` is used to retrieve the color for disabled checkbox and radiobutton if property is set by user else `getColorForState` will return the appropriate color.

**Comment by mrserb** [comment]
For example maybe the test should uses the properties [supported](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/_nimbusDefaults.html) by the L&F? what happen if the test sets `RadioButton[Disabled].textForeground` to some value?

**Comment by mrserb** [comment]
Something like this should work I think:
```
        checkBox = new JCheckBox("\u2588".repeat(5));
        UIDefaults checkBoxDefaults = new UIDefaults();
        checkBoxDefaults.put("CheckBox.textForeground", checkboxColor);
        checkBox.putClientProperty("Nimbus.Overrides",checkBoxDefaults);

        radioButton = new JRadioButton("\u2588".repeat(5));
        UIDefaults radioDefaults = new UIDefaults();
        radioDefaults.put("RadioButton.textForeground", radioButtonColor);
        radioButton.putClientProperty("Nimbus.Overrides",radioDefaults);
```

**Comment by kumarabhi006** [comment]
> I wonder do the GTK/Nimbus L&F actually use that UIDefault properties or they all based on SynthContext/SynthStyle? I see that all usages of UIManager.getColor() is added there by @prsadhuk, any reason why it was not used before?

I am not sure about it, maybe @prsadhuk can add his opinion.

**Comment by prsadhuk** [comment]
As per https://docs.oracle.com/en/java/javase/19/docs/api/java.desktop/javax/swing/plaf/nimbus/package-summary.html
it seems UIDefaults (ie UIManager.getDefaults) should be honoured first which can be overridden by altering the table via UIManager.put. There's also client property named "Nimbus.Overrides" which override the UIManager settings, so as I interpret it the UIManager.getDefaults() should be honoured unless it is overridden by Nimbus.Overrides which was not the case in my fix.

**Comment by mrserb** [comment]
It is interesting that the next line works fine in 11 and 19, but does not work in 20.
UIManager.getDefaults().put("CheckBox.textForeground", Color.RED);
I think that previouse fixes should be updated.

**Comment by mrserb** [comment]
The next line is also does not work in 20
UIManager.getDefaults().put("CheckBox[Enabled].textForeground", Color.GREEN);

**Comment by kumarabhi006** [comment]
@mrserb I think what you are suggesting is for Nimbus LAF. In case of GTK LAF, as I mentioned earlier that native system returned gray color for disabled checkbox and radio button.

As per my understanding I think user defined color should have precedence over native system color.
What should I do?

**Comment by mrserb** [comment]
The current change mostly replicates the previous fix in Nimbus L&F. Since that fix is questionable we should rethink it first. The open questions are:
 - Why did the Nimbus properties above stop working in 20
 - Why the "[Disabled]" does not work as expected
 - Why Nimbus should honor "CheckBox.disabledText" property and not [these](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/_nimbusDefaults.html) properties
 
After that we can answer the next question: "what property GTK L&F should honor". The GTK implementation is based on SynthContext/SynthStyle so I assume it should use the same props as Nimbus, and provide a way to override it by the user when needed(same as Nimbus).

**Comment by mrserb** [comment]
The similar fix https://github.com/openjdk/jdk/pull/9900, as in this one we should check is it necessary to support the property expected by the test or the property from the "Nimbus list" above should be supported.

**Review by prrace — APPROVED** [review]
"test/jdk/javax/swing/JRadioButton/4314194/bug4314194.java has been checked"

I hope you ran ALL Swing tests .. not just this single one .. ??

**Comment by kumarabhi006** [comment]
> "test/jdk/javax/swing/JRadioButton/4314194/bug4314194.java has been checked"
> 
> I hope you ran ALL Swing tests .. not just this single one .. ??

Yeah, I ran all swing tests.

**Comment by mrserb** [comment]
Does anybody look into the regression in jdk20 reported above? The fork will be done soon, it is better to fix it early than later, if the fix is not known it is probably better to roll back some changes.

Instead of fixing the product due to the test expectations, the test should be updated to use the correct properties for Nimbus and GTK.

**Comment by prsadhuk** [comment]
> Instead of fixing the product due to the test expectations, the test should be updated to use the correct properties for Nimbus and GTK.

If you believe it's test issue, can you please raise a PR updating the test to what it should have using the "correct properties"? 
We can then roll back the product changes if need be..

**Comment by kumarabhi006** [comment]
@prrace Just a minor change in condition check. Updated to bitwise operator to check if component is disabled as it has been done for other widget. 
CI testing looks fine.

**Review by TejeshR13 — APPROVED** [review]

**Comment by TejeshR13** [comment]
Fix is tested and working fine.

**Review by prrace — APPROVED** [review]

**Comment by mrserb** [comment]
> If you believe it's test issue, can you please raise a PR updating the test to what it should have using the "correct properties"?
> We can then roll back the product changes if need be or you also can rollback in the same PR the changes you think are incorrect

I will update the test case and also will file a bug to fix the usage of the Synth properties.

**Pull request closed without merging**
