### PR TITLE
8277654: Shenandoah: Don't produce new memory state in C2 LRB runtime call

### PR DESCRIPTION
**Pull request by rkennke**
The runtime call in expanded Shenandoah LRB doesn't need to produce (and consume) raw memory state. I believe this is a left-over from when the LRB (or WB) allocated from TLABs, and would mess with TLAB pointers, when not ordered correctly. (Also, we used to require ordering with RBs back when we had them, but we already removed that memory dependency on -8 offset)

Testing:
 - [x] hotspot_gc_shenandoah
 - [x] specjvm -XX:+UseShenandoahGC
 - [x] tier1
 - [x] tier2
 - [x] tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277654](https://bugs.openjdk.java.net/browse/JDK-8277654): Shenandoah: Don't produce new memory state in C2 LRB runtime call

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6526/head:pull/6526` \
`$ git checkout pull/6526`

Update a local copy of the PR: \
`$ git checkout pull/6526` \
`$ git pull https://git.openjdk.java.net/jdk pull/6526/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6526`

View PR using the GUI difftool: \
`$ git pr show -t 6526`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6526.diff">https://git.openjdk.java.net/jdk/pull/6526.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by shipilev — APPROVED** [review]
Looks okay. Does it affect performance in any way?

**Comment by rkennke** [comment]
> Looks okay. Does it affect performance in any way?

I couldn't see any benefits or regressions in specjvm.

**Pull request closed without merging**
