### PR TITLE
8290497: some tests in com/sun/jdi fail on localized Windows platform

### PR DESCRIPTION
**Pull request by tkiriyama**
Failed tests call java.lang.ProcessBuilder in direct, so not used command options specified when jtreg command run. 
To run non-localized tests, the locale options should be added in ProcessBuilder.

Could you review this fix, please?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290497](https://bugs.openjdk.org/browse/JDK-8290497): some tests in com/sun/jdi fail on localized Windows platform

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [b539d15a](https://git.openjdk.org/jdk/pull/9549/files/b539d15a2a6c7b4786b15e0bb732fbe60520f9e9)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Alex Menkov](https://openjdk.org/census#amenkov) (@alexmenkov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9549/head:pull/9549` \
`$ git checkout pull/9549`

Update a local copy of the PR: \
`$ git checkout pull/9549` \
`$ git pull https://git.openjdk.org/jdk pull/9549/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9549`

View PR using the GUI difftool: \
`$ git pr show -t 9549`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9549.diff">https://git.openjdk.org/jdk/pull/9549.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
This looks good.
Thanks,
Serguei

**Comment by tkiriyama** [comment]
@sspitsyn 
Thank you for your review. Coud you integrate this fix, please?

**Comment by sspitsyn** [comment]
@tkiriyama Normally, two reviews are required in Serviceability area.

**Comment by alexmenkov** [comment]
I agree with Chris, it would be nice to see the failure logs to understand the issue.
Also I see 2 tests which use lib.jdb.Jdb class directly: JdbArgTest and JdbOptions.
So it would be better to fix Jdb class itself and not JdbTest

**Comment by tkiriyama** [comment]
@plummercj @alexmenkov 

> Why is it that some jdb tests (and many non-jdb tests) require the -J-Duser.language=en -J-Duser.country=US and some don't? I'm just trying to better understand the problem.

This problem ocuurs only when the output of jdb command is localized, such as the usage. Some tests expect non-localized output, such as "Usage:"

> Also, can you include more log output in the CR if it would be useful in clarifying what is going wrong when running the test. Is there any useful output other than the exception, which isn't very informative.

Many tests use jdk.test.lib.process.OutputAnalyzer to check the output of jdb command. OutputAnalyzer prints the localized output of jdb command. We can use this output in the log.

> I agree with Chris, it would be nice to see the failure logs to understand the issue. Also I see 2 tests which use lib.jdb.Jdb class directly: JdbArgTest and JdbOptions. So it would be better to fix Jdb class itself and not JdbTest

The output of jdb command in JdbArgTest and JdbOptions is not localizes. Therefore, 2 tests are passed on localized environment. However, I think it would be better to fix Jdb class itself. I fixed it.

**Review by plummercj — APPROVED** [review]

**Review by alexmenkov — APPROVED** [review]

**Comment by tkiriyama** [comment]
@sspitsyn
Can I ask you again to integrate this fix?

**Comment by sspitsyn** [comment]
I've sponsored your fix. It will be integrated now, I hope.

**Pull request closed without merging**
