### PR TITLE
8334872: BigEndian: java/lang/invoke/condy Tests failing since JDK-8294960

### PR DESCRIPTION
**Pull request by asotona**
After JDK-8294960 is java.lang.invoke.ClassSpecializer using lamdas for code generation and unfortunately it causes StackOverflow on BigEndian platforms.

This patch converts all lambdas in ClassSpecializer into anonymous inner classes.

Please review and test on a BigEndian platform.

Thanks,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334872](https://bugs.openjdk.org/browse/JDK-8334872): BigEndian: java/lang/invoke/condy Tests failing since JDK-8294960 (**Bug** - P2)

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to [ac8fb2d5](https://git.openjdk.org/jdk/pull/19863/files/ac8fb2d589413316bcb018c7d032e85b9bc1b0d0)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19863/head:pull/19863` \
`$ git checkout pull/19863`

Update a local copy of the PR: \
`$ git checkout pull/19863` \
`$ git pull https://git.openjdk.org/jdk.git pull/19863/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19863`

View PR using the GUI difftool: \
`$ git pr show -t 19863`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19863.diff">https://git.openjdk.org/jdk/pull/19863.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19863#issuecomment-2186921303)

### CODE REVIEW

**Review by cl4es — APPROVED** [review]

**Comment by reinrich** [comment]
Hi Adam,

I've tested this change on a Linux PPC64 big endian system. Sadly I still get StackOverflowErrors.
I've run only test/jdk/java/lang/invoke/condy/ConstantBootstrapsTest.java. I've experimented with `ThreadStackSize` and `VMThreadStackSize` without success.

When running the test standalone I get the following message:

```
./jdk/bin/java
-cp testclasses:jtreg_latest/lib/testng-7.3.0.jar:jtreg_latest/lib/jcommander-1.82.jar
-XX:+UnlockDiagnosticVMOptions
-XX:UseBootstrapCallInfo=3
-Xint
org.testng.TestNG
-testclass
ConstantBootstrapsTest
Error occurred during initialization of boot layer
java.lang.StackOverflowError
```

It's likely not a byte ordering problem since @offamitkumar cannot reproduce the failures on s390x.

**Comment by liach** [comment]
@reinrich Could you try running with `-XX:+ShowHiddenFrames` and share the full stacktrace again?

**Comment by reinrich** [comment]
> @reinrich Could you try running with `-XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames` and share the full stacktrace again?

I've done that now. Please find it in the description/attachment of the [JBS-item](https://bugs.openjdk.org/browse/JDK-8334872).

**Comment by cl4es** [comment]
Looks like there is a bootstrap cycle initializing this lambda in ClassBuilder: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/classfile/ClassBuilder.java#L202

I'm not sure, but it looks like the PPC VM might be passing args to the bootstrap method differently, which triggers adapting code in BootstrapMethodInvoker::pushMePullYou - this might be enough to start this cycle.

**Comment by asotona** [comment]
Yes, I'm working on it. Class-File API avoids lambdas on critical JDK paths only. Unfortunately we did not have the full map of the critical paths on all platforms.

**Comment by asotona** [comment]
More lambdas converted, hopefully it is the last round.
@reinrich Please re-test.

Thank you.

**Comment by reinrich** [comment]
Unfortunately it is still failing. This is the exception stack trace:
[StackOverflow2.log](https://github.com/user-attachments/files/15971514/StackOverflow2.log)

Thanks, Richard.

**Comment by asotona** [comment]
Thanks for the report and patience.
Yes, CodeBuilder::withMethodBody is also internally using lambda.
Another version of the patch is ready for test.

Thanks!

**Comment by TheRealMDoerr** [comment]
Thanks! This looks better. `jtreg:test/jdk/java/lang/invoke/condy` have passed on linux ppc64 Big Endian. I'll put it in our nightly tests to run it on AIX, too.

**Comment by TheRealMDoerr** [comment]
The tests have passed on AIX, too.

**Comment by asotona** [comment]
Thank you for confirmation.

**Pull request closed without merging**
