### PR TITLE
8328705: GHA: Cross-compilation jobs do not require build JDK

### PR DESCRIPTION
**Pull request by shipilev**
Noticed this while fixing other GHA issues.

We pass build JDK to cross-compilation jobs, which makes them dependent on Linux-x64 builds. But we only build hotspot in all those jobs, so AFAICS there is no need for build JDK, and therefore no need for the dependency. Untying cross-compilation jobs from Linux-x64 builds make GHA more parallel. 

Additional testing:
 - [x] GHA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328705](https://bugs.openjdk.org/browse/JDK-8328705): GHA: Cross-compilation jobs do not require build JDK (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18437/head:pull/18437` \
`$ git checkout pull/18437`

Update a local copy of the PR: \
`$ git checkout pull/18437` \
`$ git pull https://git.openjdk.org/jdk.git pull/18437/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18437`

View PR using the GUI difftool: \
`$ git pr show -t 18437`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18437.diff">https://git.openjdk.org/jdk/pull/18437.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18437#issuecomment-2013030173)

### CODE REVIEW

**Comment by shipilev** [comment]
GHAs pass for this, but RISC-V would be only fixed after #18435 lands.

**Review by erikj79 — APPROVED** [review]
I'm not familiar enough with workflow code to fully understand the changes, but on a conceptual level I agree with this, and I could verify that the cross compile tasks in this PR didn't end up building a build jdk.

**Comment by shipilev** [comment]
Thanks! I would like another sanity check, maybe @magicus can take a look?

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
