### PR TITLE
JDK-8275854: C2: assert(stride_con != 0) failed: missed some peephole opt

### PR DESCRIPTION
**Pull request by casparcwang**
`If subsume` optimization will eliminate `LongCountedLoopEndNode` node by mistake, which will lead to `PhaseIdealLoop` optimization crash.

For example, the test of node 538 and node 553 will become the same after the first `PhaseIdealLoop` optimization. Node 555 is the back edge to the loop, and node 553 will be replaced by a `LongCountedLoopEndNode` node.
image

 In the next `PhaseIdealLoop` optimization, node 538 find node 553 is redundant, and will subsume node 553. Then the `PhaseIdealLoop` optimization will crash, because there is no loop end node.
image

There are two way to fix the crash, the first is like the way in this pr, just exit `IFNode subsume` optimization when it's a `LongCountedLoopEndNode` node. The second possible fix is that exchange the dominating `IF` node with the `LongCountedLoopEndNode` node:
```
diff --git a/src/hotspot/share/opto/ifnode.cpp b/src/hotspot/share/opto/ifnode.cpp
index 38b40a6..31ff172 100644
--- a/src/hotspot/share/opto/ifnode.cpp
+++ b/src/hotspot/share/opto/ifnode.cpp
@@ -1674,6 +1674,21 @@ Node* IfNode::simple_subsuming(PhaseIterGVN* igvn) {
     }
   }
 
+  if (is_LongCountedLoopEnd()) {
+    set_req(0, dom->in(0));
+    set_req(1, dom->in(1));
+    dom->set_req(0, pre);
+    dom->set_req(1, igvn->intcon(is_always_true ? 1 : 0));
+    Node* proj0 = raw_out(0);
+    Node* proj1 = raw_out(1);
+    Node* dom_proj0 = dom->raw_out(0);
+    Node* dom_proj1 = dom->raw_out(1);
+    dom_proj0->set_req(0, this);
+    dom_proj1->set_req(0, this);
+    proj0->set_req(0, dom);
+    proj1->set_req(0, dom);
+  }
+
   if (bol->outcnt() == 0) {
     igvn->remove_dead_node(bol);    // Kill the BoolNode.
   }
diff --git a/src/hotspot/share/opto/loopnode.cpp b/src/hotspot/share/opto/loopnode.cpp
index 6f7e34d..7955722 100644
--- a/src/hotspot/share/opto/loopnode.cpp
+++ b/src/hotspot/share/opto/loopnode.cpp
@@ -802,7 +802,7 @@ bool PhaseIdealLoop::transform_long_counted_loop(IdealLoopTree* loop, Node_List
   Node* back_control = head->in(LoopNode::LoopBackControl);
 
   // data nodes on back branch not supported
-  if (back_control->outcnt() > 1) {
+  if (back_control->outcnt() > 1 || back_control->Opcode() != Op_IfTrue) {
     return false;
   }
 
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275854](https://bugs.openjdk.java.net/browse/JDK-8275854): C2: assert(stride_con != 0) failed: missed some peephole opt

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to 8c81c883dc1738ea7e3ee5bfa05f31d8e0f4f48f
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to ccfa6f106744dddcdb7f1b00706399f51852d825

### Contributors
 * Roland Westrelin `<roland@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6099/head:pull/6099` \
`$ git checkout pull/6099`

Update a local copy of the PR: \
`$ git checkout pull/6099` \
`$ git pull https://git.openjdk.java.net/jdk pull/6099/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6099`

View PR using the GUI difftool: \
`$ git pr show -t 6099`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6099.diff">https://git.openjdk.java.net/jdk/pull/6099.diff</a>

</details>

### CODE REVIEW

**Comment by casparcwang** [comment]
ping, can I have more review of this pr?

**Review by TobiHartmann — APPROVED** [review]
That looks reasonable to me but please add a comment to the new code.

I'll run some testing in the meantime.

**Review by vnkozlov — APPROVED** [review]
Looks good. But please wait tests results from Tobias.

**Comment by casparcwang** [comment]
> That looks reasonable to me but please add a comment to the new code.
> 
> I'll run some testing in the meantime.

Thank you very much for your review and testing. I have added some comment to the newly added code.

**Comment by casparcwang** [comment]
> Looks good. But please wait tests results from Tobias.

Thank you very much for your review and work. I have passed jtreg and some test-suite on my server, and it's always a good thing to run more tests.

**Review by TobiHartmann — APPROVED** [review]
The comment looks good and all tests passed.

**Pull request closed without merging**
