### PR TITLE
JDK-8299402: Remove metaprogramming/isVolatile.hpp

### PR DESCRIPTION
**Pull request by jcking**
Code cleanup of pre-C++11 <type_traits> implementations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299402](https://bugs.openjdk.org/browse/JDK-8299402): Remove metaprogramming/isVolatile.hpp

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11801/head:pull/11801` \
`$ git checkout pull/11801`

Update a local copy of the PR: \
`$ git checkout pull/11801` \
`$ git pull https://git.openjdk.org/jdk pull/11801/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11801`

View PR using the GUI difftool: \
`$ git pr show -t 11801`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11801.diff">https://git.openjdk.org/jdk/pull/11801.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by walulyai — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
/sponsor

**Pull request closed without merging**
