### PR TITLE
8289562: Change bugs.java.com and bugreport.java.com URL's to https

### PR DESCRIPTION
**Pull request by jcherian-se**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289562](https://bugs.openjdk.org/browse/JDK-8289562): Change bugs.java.com and bugreport.java.com URL's to https

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to [324f877c](https://git.openjdk.org/jdk/pull/9445/files/324f877c91f01d8c3d74427941b13093d9ed72d9)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**) ⚠️ Review applies to [324f877c](https://git.openjdk.org/jdk/pull/9445/files/324f877c91f01d8c3d74427941b13093d9ed72d9)
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to [324f877c](https://git.openjdk.org/jdk/pull/9445/files/324f877c91f01d8c3d74427941b13093d9ed72d9)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to [324f877c](https://git.openjdk.org/jdk/pull/9445/files/324f877c91f01d8c3d74427941b13093d9ed72d9)

### Contributors
 * Joe Cherian `<joe.cherian@oracle.com>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9445/head:pull/9445` \
`$ git checkout pull/9445`

Update a local copy of the PR: \
`$ git checkout pull/9445` \
`$ git pull https://git.openjdk.org/jdk pull/9445/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9445`

View PR using the GUI difftool: \
`$ git pr show -t 9445`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9445.diff">https://git.openjdk.org/jdk/pull/9445.diff</a>

</details>

### CODE REVIEW

**Comment by fmatte1** [comment]
It is a trivial change and looks good to me (I am not a reviewer).

**Review by prrace — APPROVED** [review]
Looks fine to me. However the langtools / javadoc folks seem like they should be primary reviewers since it is mostly messages from the tools.

**Review by naotoj — APPROVED** [review]
Those `.properties` bundle changes look good.

**Pull request closed without merging**
