### PR TITLE
8298907: nsk JDI tests pass if the debuggee failed to launch

### PR DESCRIPTION
**Pull request by lmesnik**
Updated run() to return exitCode and make testExitCode non-static to don't use it in run()

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298907](https://bugs.openjdk.org/browse/JDK-8298907): nsk JDI tests pass if the debuggee failed to launch

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12270/head:pull/12270` \
`$ git checkout pull/12270`

Update a local copy of the PR: \
`$ git checkout pull/12270` \
`$ git pull https://git.openjdk.org/jdk pull/12270/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12270`

View PR using the GUI difftool: \
`$ git pr show -t 12270`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12270.diff">https://git.openjdk.org/jdk/pull/12270.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — COMMENTED** [review]
Thanks for cleaning this up. The changes look good. Did you experiment with any of the tests to make sure an invalid arg passed to the debuggee results in a failure? You can add the arg to the start of `-debugee.vmkeys` in TestDescriptions.java.

**Comment by lmesnik** [comment]
> Thanks for cleaning this up. The changes look good. Did you experiment with any of the tests to make sure an invalid arg passed to the debuggee results in a failure? You can add the arg to the start of `-debugee.vmkeys` in TestDescriptions.java.
Yes, test fails with
# ERROR: ##> debugger: ERROR: Exception : nsk.share.Failure: Caught exception while starting debugee VM:
# ERROR:        com.sun.jdi.connect.VMStartException: VM initialization failed for: /home/lmesnik/ws/jdk-jdi/build/linux-x64/images/jdk/bin/java -XX:MaxRAMPercentage=1.5625 -Dtest.boot.jdk=/var/tmp/jib-lmesnik/install/jdk/19/36/bundles/linux-x64/jdk-19_l
inux-x64_bin.tar.gz/jdk-19 -Djava.io.tmpdir=/home/lmesnik/ws/jdk-jdi/build/linux-x64/test-support/jtreg_open_test_hotspot_jtreg_vmTestbase_nsk_jdi_DoubleType_itself_doubletype001_TestDescription_java/tmp -XX:NONE -Xdebug -Xrunjdwp:transport=dt_socket,add
ress=localhost:48711,suspend=y,includevirtualthreads=y nsk.jdi.DoubleType._itself_.doubletype001a -vbs -verbose -arch=linux-x64 -waittime=5 -debugee.vmkind=java -transport.address=dynamic -debugee.vmkeys="-XX:MaxRAMPercentage=1.5625 -Dtest.boot.jdk=/var/
tmp/jib-lmesnik/install/jdk/19/36/bundles/linux-x64/jdk-19_linux-x64_bin.tar.gz/jdk-19 -Djava.io.tmpdir=/home/lmesnik/ws/jdk-jdi/build/linux-x64/test-support/jtreg_open_test_hotspot_jtreg_vmTestbase_nsk_jdi_DoubleType_itself_doubletype001_TestDescription
_java/tmp -XX:NONE" -pipe.port=43001
# ERROR:        stdout:
# ERROR:        stderr: Unrecognized VM option 'NONE'
# ERROR: Error: Could not create the Java Virtual Machine.
# ERROR: Error: A fatal exception has occurred. Program will exit.

**Comment by plummercj** [comment]
Ok. thanks!

**Review by plummercj — APPROVED** [review]

**Review by kevinjwalls — APPROVED** [review]
Looks good 8-)

**Pull request closed without merging**
