### PR TITLE
8270991: G1 Full GC always performs heap verification after JDK-8269295 

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  can I have reviews for this fix that removes always-on heap verification for g1 full gcs caused by any reason?

JDK-8269295 refactored some code in that area, and existing tests only checked that verification is properly enabled or disabled for young gc only.

This change fixes the problem and improves the existing test accordingly.

Testing: new test case

Thanks,
  Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270991](https://bugs.openjdk.java.net/browse/JDK-8270991): G1 Full GC always performs heap verification after JDK-8269295

### Reviewers
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer)
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4856/head:pull/4856` \
`$ git checkout pull/4856`

Update a local copy of the PR: \
`$ git checkout pull/4856` \
`$ git pull https://git.openjdk.java.net/jdk pull/4856/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4856`

View PR using the GUI difftool: \
`$ git pr show -t 4856`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4856.diff">https://git.openjdk.java.net/jdk/pull/4856.diff</a>

</details>

### CODE REVIEW

**Review by walulyai — APPROVED** [review]
Lgtm!

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by kimbarrett** [comment]
Consider pushing this without waiting for the usual HotSpot 24 hour rule.

**Comment by tschatzl** [comment]
I'll push forgoing the 24 hour rule since it is a very small fix, and fairly disruptive when benchmarking.

Thanks @kimbarrett and @walulyai for your reviews.

/integrate

**Pull request closed without merging**
