### PR TITLE
8278469: Test java/nio/channels/FileChannel/LargeGatheringWrite.java times out

### PR DESCRIPTION
**Pull request by bplb**
Modify test directives so that `LargeGatheringWrite` and `MapTest` in `java/nio/channels/FileChannel` are not run concurrently with other tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8278469](https://bugs.openjdk.org/browse/JDK-8278469): Test java/nio/channels/FileChannel/LargeGatheringWrite.java times out
 * [JDK-8289526](https://bugs.openjdk.org/browse/JDK-8289526): java/nio/channels/FileChannel/MapTest.java times out

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9416/head:pull/9416` \
`$ git checkout pull/9416`

Update a local copy of the PR: \
`$ git checkout pull/9416` \
`$ git pull https://git.openjdk.org/jdk pull/9416/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9416`

View PR using the GUI difftool: \
`$ git pr show -t 9416`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9416.diff">https://git.openjdk.org/jdk/pull/9416.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. I didn't realize that other test dirs already had the mechanism
in place to isolate the resource hogs. I'm looking forward to seeing this in
action.

I just realized this is targeted at jdk/jdk (JDK20). Can you please close this
PR and create a new one for JDK19?

**Comment by bplb** [comment]
> I just realized this is targeted at jdk/jdk (JDK20). Can you please close this PR and create a new one for JDK19?

Done.

**Review by AlanBateman — COMMENTED** [review]
Are you sure MapTest needs a lot of memory? It's a unit test and doesn't have anything in its jtreg test description to require a lot of resources. I wonder if it's just the victim.

**Comment by bplb** [comment]
> Are you sure MapTest needs a lot of memory? It's a unit test and doesn't have anything in its jtreg test description to require a lot of resources. I wonder if it's just the victim.

We can see whether they both stop failing regularly after this change and if so move `MapTest` out of the large memory list.

**Comment by AlanBateman** [comment]
> We can see whether they both stop failing regularly after this change and if so move `MapTest` out of the large memory list.

I suspect it's a victim and shouldn't in the largeMemory directory but let's see if there are issues in the coming days. My preference is to keep the unit tests in the original location and the only tests in largeMemory are the tests that really need a lot of memory.

**Comment by bplb** [comment]
> My preference is to keep the unit tests in the original location and the only tests in largeMemory are the tests that really need a lot of memory.

Likewise.

**Pull request closed without merging**
