### PR TITLE
8308429: jvmti/StopThread/stopthrd007 failed with "NoClassDefFoundError: Could not initialize class jdk.internal.misc.VirtualThreads"

### PR DESCRIPTION
**Pull request by lmesnik**
The test fails because ThreadDeath is raised during class jdk.internal.misc.VirtualThreads initialization. The proposed fix is to pre-initialize this step to avoid such failures. See more details in the bug.
I reproduced the original problem and verified that it is not reproduced after fix. 
Tested with tier5 and running nsk/jvmti tests with and without virtual test thread factory.

I don't think that more complex fix is needed. There is a plan to review nsk/jvmti stopThread tests and see if 
./serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java 
might be improved to cover them.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308429](https://bugs.openjdk.org/browse/JDK-8308429): jvmti/StopThread/stopthrd007 failed with "NoClassDefFoundError: Could not initialize class jdk.internal.misc.VirtualThreads" (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15966/head:pull/15966` \
`$ git checkout pull/15966`

Update a local copy of the PR: \
`$ git checkout pull/15966` \
`$ git pull https://git.openjdk.org/jdk.git pull/15966/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15966`

View PR using the GUI difftool: \
`$ git pr show -t 15966`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15966.diff">https://git.openjdk.org/jdk/pull/15966.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15966#issuecomment-1739712534)

### CODE REVIEW

**Comment by plummercj** [comment]
@AlanBateman should look at this. I'm just wondering if there might be an argument for making sure that the VirtualThread class (or LockSupport class) always loads the VirtualThreads class.

**Comment by lmesnik** [comment]
I thought about this, but not sure that it is worth for applications which don't use virtual threads. Let check with Alan.

**Review by dholmes-ora — APPROVED** [review]
This is a reasonable workaround but I think there is a problem with the VirtualThread code that should be changed as well (or even instead). That code should be balanced in park/unpark paths such that any classloading happens on the park path IMO.

**Review by sspitsyn — APPROVED** [review]
The work around looks okay to me. I've notified Alan about this PR.
Thanks,
Serguei

**Review by sspitsyn — APPROVED** [review]

**Comment by AlanBateman** [comment]
jdk.internal.misc.VirtualThreads is a supporting class for LockSupport.park/unpark. It came about because of bootstrapping issues with LockSupport being loaded early in the startup. A lot of code has changed since it was added and it might be time to look at it again, meaning LockSupport changed to use the JLA shared secret and checking for startup/bootstrapping issues.

On the class loading. If a virtual thread parks with LockSupport.park then it will trigger any supporting classes to be loaded on first usage. It looks like this test involves a virtual thread being unparked with LockSupport.unpark before it parks with LockSupport.park. This scenario does lead to the supporting class being loaded when unparking, problematic in this test because of JVMTI StopThread and the async exception.

**Comment by AlanBateman** [comment]
One other general comment is that "stop" has been removed from the user-facing APIs for several releases. The use-case for JVMTI StopThread (and the JDWP/JDI equivalents) is mostly the debugger scenario where a thread is at a breakpoint and the developer wants to test how the code behaves when an exception is thrown, e.g. ask the debugger to throw IllegalArgumentException or SQLException at this point. This is a bit more controlled than shooting an arrow at the executing code as that leads to very unpredictable behavior. So I guess my point is that there may be merit is "degrading" StopThread to only require that it be supported when the target thread is suspended at an event. This would align it where we got to with virtual threads.  There may also be merit is re-examining the tests that are sending async exceptions as sending the terminally deprecated ThreadDeath is troublesome, it may be better to have tests for StopThread focus on cases where the target thread is suspended at an event.

**Comment by lmesnik** [comment]
Alan, thank you for the explanation.  We just wanted to ensure that it is not a problem in other cases.

**Pull request closed without merging**
