### PR TITLE
8295319: pending_cards_at_gc_start doesn't include cards in thread buffers

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to G1 to include the per-thread buffers in the
number of pending cards at the start of a young GC.

DCQS::concatenate_logs has been renamed to concatenate_logs_and_stats, and now
also merges the per-thread refinement stats during the thread walk to flush
buffers.  That replaces the separate thread walk to merge and record these
stats earlier in the GC.  The merged stats and related info don't seem to be
needed until after the buffer flushing.

Also, when abandoning dirty card buffers and stats because of a full GC, fixed
to also abandon an buffers in the paused buffers lists.

Testing:
mach5 tier1-3
performance testing found no significant changes, as expected.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295319](https://bugs.openjdk.org/browse/JDK-8295319): pending_cards_at_gc_start doesn't include cards in thread buffers

### Reviewers
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to [34a4b994](https://git.openjdk.org/jdk/pull/10914/files/34a4b994ac0e18f2134bdbd6fc141e8752fd15c8)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [34a4b994](https://git.openjdk.org/jdk/pull/10914/files/34a4b994ac0e18f2134bdbd6fc141e8752fd15c8)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10914/head:pull/10914` \
`$ git checkout pull/10914`

Update a local copy of the PR: \
`$ git checkout pull/10914` \
`$ git pull https://git.openjdk.org/jdk pull/10914/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10914`

View PR using the GUI difftool: \
`$ git pr show -t 10914`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10914.diff">https://git.openjdk.org/jdk/pull/10914.diff</a>

</details>

### CODE REVIEW

**Comment by walulyai** [comment]
`calculate_collection_set` -> `finalize_initial_collection_set` -> `finalize_young_part`:
`size_t pending_cards = _policy->pending_cards_at_gc_start() + _g1h->hot_card_cache()->num_entries();`

called before `pre_evacuate_collection_set`

`flush_dirty_card_logs_and_stats` needs to be called before `calculate_collection_set`

**Comment by kimbarrett** [comment]
> > `calculate_collection_set` -> `finalize_initial_collection_set` -> `finalize_young_part`: `size_t pending_cards = _policy->pending_cards_at_gc_start() + _g1h->hot_card_cache()->num_entries();`
> > called before `pre_evacuate_collection_set`
> > `flush_dirty_card_logs_and_stats` needs to be called before `calculate_collection_set`
> 
> Sigh! Looks like I got lost while tracking down the callers and call chains.

Fixed now.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by kimbarrett** [comment]
Thanks @walulyai and @tschatzl for reviews.

**Pull request closed without merging**
