### PR TITLE
JDK-8284944: assert(cnt++ < 40) failed: infinite cycle in loop optimization

### PR DESCRIPTION
**Pull request by tobiasholenstein**
`_loop_opts_cnt` is set to `LoopOptsCount` which can have a maximum value of 43. `_loop_opts_cnt` is decremented in `PHASE_PHASEIDEALLOOP1`, `PHASE_PHASEIDEALLOOP2` and `PHASE_PHASEIDEALLOOP3` before it reaches `PHASE_PHASEIDEALLOOP_ITERATIONS` where it is decremented further in a loop until `_loop_opts_cnt` is 0. The assert assumes that `_loop_opts_cnt` has max. value 40 in `PHASE_PHASEIDEALLOOP_ITERATIONS`. But when `PartialPeelLoop` is turned off `PHASE_PHASEIDEALLOOP2` is skipped and `_loop_opts_cnt` can have max. value 41 in `PHASE_PHASEIDEALLOOP_ITERATIONS`. Therefore the assert is wrong. 

I propose to remove the assert entirely since the loop already has a condition `_loop_opts_cnt > 0` and `_loop_opts_cnt` is decremented in every iteration.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8284944](https://bugs.openjdk.java.net/browse/JDK-8284944): assert(cnt++ < 40) failed: infinite cycle in loop optimization

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8767/head:pull/8767` \
`$ git checkout pull/8767`

Update a local copy of the PR: \
`$ git checkout pull/8767` \
`$ git pull https://git.openjdk.java.net/jdk pull/8767/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8767`

View PR using the GUI difftool: \
`$ git pr show -t 8767`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8767.diff">https://git.openjdk.java.net/jdk/pull/8767.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Having > 40 cycles in loopopts is bug - something wrong gone there. That is what this assert for. We should detect such case in loop opts and stop early.
I don't think removing this assert is correct thing.

**Comment by tobiasholenstein** [comment]
> Having > 40 cycles in loopopts is bug - something wrong gone there. That is what this assert for. We should detect such case in loop opts and stop early.
> I don't think removing this assert is correct thing.

I have attached the the output of `TestMaxLoopOptsCountReached.java` run with `-XX:+TraceLoopOpts` in JIRA: https://bugs.openjdk.java.net/secure/attachment/99052/Output%20TraceLoopOpts.txt

It does a lot of loop unswitching but it seems that all loop optimizations are valid. The way the assert is implemented it can only be triggered if `PartialPeelLoop` is turned off. When `PartialPeelLoop` is turned on the assert can never be triggered and the loop optimizations are stopped after `LoopOptsCount` iterations (see PR description). I don't think it necessarily means that there is a bug if `LoopOptsCount` many loop optimizations are performed. 

I agree that this could help detect potential bugs, but there can also be false positives (e.g. TestMaxLoopOptsCountReached.java). I am not sure if there is a reliable way to detect such false positives. What do you think?

**Comment by vnkozlov** [comment]
As I commented in bug report, it took 54 (cnt == 52) iterations to finish compilation TestMaxLoopOptsCountReached::test method.
Should we just rise default LoopOptsCount flag's value and limit in the assert?

**Comment by vnkozlov** [comment]
The original Test.java did not finish after 1000 iterations and I don't see what loop opts it executed.

**Comment by vnkozlov** [comment]
I think first thing to do is to make sure we got report about what cause `major_progress` to be `true` in those loop opts iteration. Currently I see only repeated output in Test.java.

I also found that without "Strip Mining" (I used -XX:+UseParallelGC because I can't find how to switch it off otherwise) the Test.java finished in 9 iterations (cnt == 7) !!!   So it is definitely something wrong when we use "Strip Mining" in this test.

**Comment by vnkozlov** [comment]
And I don't know how they reproduced failure with JDK 8 and 11.
I run it with `java -XX:+TraceLoopOpts -Xcomp -XX:-PartialPeelLoop -XX:+PrintCompilation -XX:+UseParallelGC Test`

**Comment by vnkozlov** [comment]
> * Remove the assert for now (given that it has never worked as it was supposed to work) and file an RFE to check if we can reintroduce it once the known cases/bugs are fixed and we have some confidence to not hit it again (could include tweaking the `LoopOptsCount` max value or introducing some other heuristics to avoid false positives).
> * Keep the assert as we have it today and just defer this bug and treat it like the RFE above.
> 
> I would opt for option 1 given that the assert has no real value as of today.

Okay, I agree.

**Review by vnkozlov — APPROVED** [review]

**Review by chhagedorn — APPROVED** [review]

**Comment by tobiasholenstein** [comment]
Thanks @vnkozlov and @chhagedorn for you feedback. I will file a follow-up RFE to reintroduce a better check for loop optimization progress and a Bug for the infinite loop in loop optimizations. 

/integrate

**Pull request closed without merging**
