### PR TITLE
8291597: [BACKOUT] JDK-8289996: Fix array range check hoisting for some scaled loop iv

### PR DESCRIPTION
**Pull request by pfustc**
This reverts JDK-8289996 as multiple jtreg fails after that change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291597](https://bugs.openjdk.org/browse/JDK-8291597): [BACKOUT] JDK-8289996: Fix array range check hoisting for some scaled loop iv

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9696/head:pull/9696` \
`$ git checkout pull/9696`

Update a local copy of the PR: \
`$ git checkout pull/9696` \
`$ git pull https://git.openjdk.org/jdk pull/9696/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9696`

View PR using the GUI difftool: \
`$ git pr show -t 9696`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9696.diff">https://git.openjdk.org/jdk/pull/9696.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Good. I submitted testing.

**Comment by vnkozlov** [comment]
I also verified that test cases from [8291466](https://bugs.openjdk.org/browse/JDK-8291466) and [8291510](https://bugs.openjdk.org/browse/JDK-8291510) passed with this backout.

**Review by TobiHartmann — APPROVED** [review]
Looks good. Vladimir's testing passed.

**Comment by TobiHartmann** [comment]
The backout issue needs to be a sub-task. Please follow the steps described by https://openjdk.org/guide/#backing-out-a-change.

**Review by vnkozlov — APPROVED** [review]
Testing passed.

**Comment by pfustc** [comment]
> The backout issue needs to be a sub-task. Please follow the steps described by https://openjdk.org/guide/#backing-out-a-change.

Thanks for reminding. It's a sub-task now.

**Comment by pfustc** [comment]
Thank you for the review. I will do the backout now and add a REDO later after investigations.

**Comment by pfustc** [comment]
I've moved the BACKOUT to a sub-task of REDO now.

**Pull request closed without merging**
