### PR TITLE
8278143: Remove unused "argc" from ConstantPool::copy_bootstrap_arguments_at_impl

### PR DESCRIPTION
**Pull request by shipilev**
SonarCloud complains about variable initialization in large conditional statements. In that tower of if-expressions, it is not even clear to me that `argc` would be properly initialized. Seems better to clean that up.

Additional testing:
 - [x] Linux x86_64 fastdebug build
 - [x] GHA

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278143](https://bugs.openjdk.java.net/browse/JDK-8278143): Remove unused "argc" from ConstantPool::copy_bootstrap_arguments_at_impl

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to 18fba172cd42b72e6a39f238c40054ac55bd3788
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6671/head:pull/6671` \
`$ git checkout pull/6671`

Update a local copy of the PR: \
`$ git checkout pull/6671` \
`$ git pull https://git.openjdk.java.net/jdk pull/6671/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6671`

View PR using the GUI difftool: \
`$ git pr show -t 6671`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6671.diff">https://git.openjdk.java.net/jdk/pull/6671.diff</a>

</details>

### CODE REVIEW

**Review by lfoltan — COMMENTED** [review]
Looks good.
Lois

**Review by lfoltan — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Good catch! :) It has been unused since it was introduced by JDK-8186209

argc is still mentioned in the comment on line 1183.

Thanks,
David

**Comment by shipilev** [comment]
> argc is still mentioned in the comment on line 1183.

Right! Fixed in new commit.

**Review by dholmes-ora — APPROVED** [review]

**Pull request closed without merging**
