### PR TITLE
JDK-8263389 IGV: Zooming changes the point that is currently centered

### PR DESCRIPTION
**Pull request by jtfuller111**
Fixing the zoom issue on IGV. I tested this on Windows and Linux and zooming now works as expected.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263389](https://bugs.openjdk.java.net/browse/JDK-8263389): IGV: Zooming changes the point that is currently centered

### Reviewers
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4291/head:pull/4291` \
`$ git checkout pull/4291`

Update a local copy of the PR: \
`$ git checkout pull/4291` \
`$ git pull https://git.openjdk.java.net/jdk pull/4291/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4291`

View PR using the GUI difftool: \
`$ git pr show -t 4291`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4291.diff">https://git.openjdk.java.net/jdk/pull/4291.diff</a>

</details>

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please send an e-mail to Dalibor.topic@oracle.com so that I can mark your account as verified.

**Comment by jtfuller111** [comment]
Hello, could anyone kindly take a look at this?

**Comment by reinrich** [comment]
Hi @jtfuller111,

I've tested the fix and found that it eliminates the random moves of the view port when zooming. Thumbs up for that. It still changes the point that is centered though. You might want to fix that also if possible.

Thanks, Richard.

**Comment by jtfuller111** [comment]
> Hi @jtfuller111,
> 
> I've tested the fix and found that it eliminates the random moves of the view port when zooming. Thumbs up for that. It still changes the point that is centered though. You might want to fix that also if possible.
> 
> Thanks, Richard.

Hello! I pushed a change to also keeps the current center point centered when zooming.

**Review by reinrich — APPROVED** [review]
The fix looks good to me.

Thanks, Richard.

**Comment by reinrich** [comment]
Hi @jtfuller111,
I'd offer to sponsor your fix. We should wait for a 2nd review though.
Thanks, Richard.

**Review by neliasso — APPROVED** [review]
Looks good.

**Pull request closed without merging**
