### PR TITLE
8316582: Minor startup regression in 22-b15 due JDK-8310929

### PR DESCRIPTION
**Pull request by cl4es**
This patch reverts the use of `ByteArrayLittleEndian` in `StringLatin1`. 

This use is the cause of a small (~1.5ms) startup regression in 22-b15. While a manageable startup regression in and of itself, the use of `VarHandles` in core utility classes brings an increased risk of bootstrap circularity issues, for example disqualifying the use of things like `Integers.toString` in some places.

Reverting this partially rolls back the performance improvement gained by JDK-8310929. It seems reasonable that the compiler can be enhanced to gain that loss back.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316582](https://bugs.openjdk.org/browse/JDK-8316582): Minor startup regression in 22-b15 due JDK-8310929 (**Bug** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - Author)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15836/head:pull/15836` \
`$ git checkout pull/15836`

Update a local copy of the PR: \
`$ git checkout pull/15836` \
`$ git pull https://git.openjdk.org/jdk.git pull/15836/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15836`

View PR using the GUI difftool: \
`$ git pr show -t 15836`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15836.diff">https://git.openjdk.org/jdk/pull/15836.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
This PR vs a 22-b15 baseline:
```
Name                   Cnt  Base   Error   Test   Error  Unit   Diff%
Integers.toStringBig    15 5,318 ± 0,043  6,628 ± 0,127 us/op  -24,6% (p = 0,000*)
Integers.toStringSmall  15 3,202 ± 0,018  3,562 ± 0,027 us/op  -11,2% (p = 0,000*)
Integers.toStringTiny   15 2,286 ± 0,017  2,352 ± 0,024 us/op   -2,9% (p = 0,000*)
  * = significant
```

This PR vs a 22-b14 baseline:
```
Name                   Cnt   Base   Error   Test   Error  Unit   Diff%
Integers.toStringBig    15 12,313 ± 0,143  6,628 ± 0,127 us/op   46,2% (p = 0,000*)
Integers.toStringSmall  15  4,816 ± 0,074  3,562 ± 0,027 us/op   26,0% (p = 0,000*)
Integers.toStringTiny   15  2,611 ± 0,022  2,352 ± 0,024 us/op    9,9% (p = 0,000*)
  * = significant
```

There's still a substantial win compared to 22-b14, stemming from the use of a packed lookup table rather than two disjoint tables for tens and single digit numbers.

**Comment by liach** [comment]
Can #14636 be a solution to avoid early VH initialization?

Also curious how you created such a "Base vs Test" metrics table, could you teach me how?

**Comment by cl4es** [comment]
> Can #14636 be a solution to avoid early VH initialization?

I think #14636 would more or less solve the startup regression, yes, but the jury is out on whether we want to accept that. There's value in taking steps to make `VH` indistinguishable from `Unsafe` w.r.t. start-up and other performance characteristics. The issue with using `ByteArray*` in `Integer/StringLatin1` is also more one of bootstrap dependencies. 

We also really need to analyze why the JIT doesn't generate as good code for pair-wise `byte[]` stores as for `ByteArray.setShort` and then try to fix this in the JIT. This would be much preferably to having to pull out a power tool like `ByteArrayLittleEndian` for something so trivial. It might be a good exercise for anyone who want to dive into JITs to get these to perform equally. 

> Also curious how you created such a "Base vs Test" metrics table, could you teach me how?

It's a tool I've written that parses JMH json output and allows comparisons. It's currently part of a larger benchmark running toolkit that we probably can't open source, but I could probably extract the simple parser + printer and put it under the OpenJDK somewhere if there's interest.

**Comment by cl4es** [comment]
Startup numbers improve with the above patch to levels on par with 22-b14:
```
Name                Cnt          Base         Error           Test         Error         Unit   Diff%
Perfstartup-Noop-G1  20        30,000 ±       0,000         28,500 ±       3,181        ms/op    5,0% (p = 0,083 )
  :.cycles           20  88166516,750 ± 2119868,114   84226439,550 ± 1792195,203       cycles   -4,5% (p = 0,000*)
  :.instructions     20 204321816,400 ±  248867,819  195313416,200 ±  196361,902 instructions   -4,4% (p = 0,000*)
  :.taskclock        20        12,000 ±       4,543         10,000 ±       0,000           ms  -16,7% (p = 0,104 )
  * = significant
```
(This is simply a Noop/Hello World program in a loop, with stats collected by `/usr/bin/time -l`, run on a MacBook M1)

**Review by liach — APPROVED** [review]
Looks good. I also wonder if storing digit pairs in platform endianness is better; currently only Unsafe support writing multibytes with platform endianness.

**Comment by cl4es** [comment]
FWIW when initializing `DIGITS` directly (`DIGITS = new byte[] { ...`)  the `DecimalDigits` class is 2610 bytes, with the for loop in a `static` block it drops down to 2112 bytes. Array constants like this generate sad and bloated bytecode:
```
         0: bipush        100
         2: newarray       short
         4: dup
         5: iconst_0
         6: sipush        12336
         9: sastore
         ...
        40: dup
        41: bipush        6
        43: sipush        13872
        46: sastore
        ...
       691: dup
       692: bipush        99
       694: sipush        14649
       697: sastore
       698: putstatic     #13                 // Field DIGITS:[S
```

**Review by RogerRiggs — APPROVED** [review]
Thanks for tracking down the regression.

**Comment by wenshao** [comment]
digitPair and Unsafe.putShort are a good combination. Can Unsafe be used here?

```java
   public static void writeDigitPair(byte[] buf, int charPos, int value) {
        Unsafe.putShortUnaligned(
                buf,
                Unsafe.ARRAY_BYTE_BASE_OFFSET + pos,
                digitPair(value),
                false);
    }
```

**Comment by cl4es** [comment]
I'd like us to take a step back and instead of reaching for and sprinkling `Unsafe`, `ByteArrayLittleEndian` and `VarHandles` all over the place to instead consider differences in performance on trivial code like this as compiler bugs. We need to investigate if there's anything we can do to have the JIT generate better code here for idiomatic java, and only once we thoroughly understand if and why that's not possible to reach for other options.

**Pull request closed without merging**
