### PR TITLE
8338731: MemoryLayout::offsetHandle can return a negative offset

### PR DESCRIPTION
**Pull request by mcimadamore**
When working on startup improvements, I noticed that the method handle returned by `MemoryLayout::offsetHandle` can overflow if the client calls the handle with a base offset that is too big.

In other similar situations, the layout API always fails with `ArithmeticException` (see `MemoryLayout::scale`), so we should do the same here.

The fix is to use a `Math::addExact(long, long)` for the outermost add operation in the computation of the offset method handle. That outermost computation in fact is the only one that can overflow: it is an addition between a user-provided base offset `B` and a layout offset `L`. `L` is guaranteed not to overflow, by construction (as `L` is derived from a layout path). But `B` + `L` might overflow, so the new logic checks for that.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8338742](https://bugs.openjdk.org/browse/JDK-8338742) to be approved

### Issues
 * [JDK-8338731](https://bugs.openjdk.org/browse/JDK-8338731): MemoryLayout::offsetHandle can return a negative offset (**Enhancement** - P3)
 * [JDK-8338742](https://bugs.openjdk.org/browse/JDK-8338742): MemoryLayout::offsetHandle can return a negative offset (**CSR**)

### Reviewers
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - **Reviewer**)
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**) Review applies to [8ac9d262](https://git.openjdk.org/jdk/pull/20662/files/8ac9d26209f15d4d3947ab4d292e7bcc85029057)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20662/head:pull/20662` \
`$ git checkout pull/20662`

Update a local copy of the PR: \
`$ git checkout pull/20662` \
`$ git pull https://git.openjdk.org/jdk.git pull/20662/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20662`

View PR using the GUI difftool: \
`$ git pr show -t 20662`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20662.diff">https://git.openjdk.org/jdk/pull/20662.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20662#issuecomment-2302069637)

### CODE REVIEW

**Review by minborg — APPROVED** [review]
Nice catch.

**Comment by minborg** [comment]
Unrelated: I wonder if the performance of:

```
MH_ADD = lookup.findStatic(Long.class, "sum",
                    MethodType.methodType(long.class, long.class, long.class));
                    
```

and 

```
MH_ADD = MethodHandles.publicLookup().findStatic(Long.class, "sum",
                    MethodType.methodType(long.class, long.class, long.class));
```
Differ?

**Comment by liach** [comment]
They should have the same performance characteristics. They have different permissions for access checks, and since `Long` is exported public API and `sum` is public both will pass.

**Review by PaulSandoz — APPROVED** [review]

**Review by minborg — APPROVED** [review]
Merge ok ;-)

**Pull request closed without merging**
