### PR TITLE
8267943: Improve performance of EventWriter by improving varint encoding implementation

### PR DESCRIPTION
**Pull request by richardstartin**
This PR improves the performance of committing events with numeric correlation ids by precomputing the number of continuation bytes required by each varint and storing them in a lookup table addressable by the input `long`'s leading zero count. In some rough [benchmarks](https://github.com/richardstartin/jfr-events/blob/master/src/main/java/io/github/richardstartin/jfrevents/CommitEventBenchmark.java), this shows a negligible regression for committing empty events, but a 15% improvement for committing an event with two random 64 bit identifiers.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8267943](https://bugs.openjdk.java.net/browse/JDK-8267943): Improve performance of EventWriter by improving varint encoding implementation

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4251/head:pull/4251` \
`$ git checkout pull/4251`

Update a local copy of the PR: \
`$ git checkout pull/4251` \
`$ git pull https://git.openjdk.java.net/jdk pull/4251/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4251`

View PR using the GUI difftool: \
`$ git pr show -t 4251`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4251.diff">https://git.openjdk.java.net/jdk/pull/4251.diff</a>

</details>

### CODE REVIEW

**Comment by D-D-H** [comment]
Hi @richardstartin ,

I am not a reviewer. I just want to suggest a potential improvement.
Maybe we can use `switch` instead of `for`, like this:
```
        switch (length) {
            case 9:
                putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
                v >>>= 7;
            case 8:
                putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
                v >>>= 7;
            case 7:
                putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
                v >>>= 7;
            ...
        }
```

I think this can eliminate some jump instructions.

Best,
Denghui

**Comment by D-D-H** [comment]
> Hi @richardstartin ,
> 
> I am not a reviewer. I just want to suggest a potential improvement.
> Maybe we can use `switch` instead of `for`, like this:
> 
> ```
>         switch (length) {
>             case 9:
>                 putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
>                 v >>>= 7;
>             case 8:
>                 putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
>                 v >>>= 7;
>             case 7:
>                 putUncheckedByte(((byte) ((v & 0x7F) | 0x80)));
>                 v >>>= 7;
>             ...
>         }
> ```
> 
> I think this can eliminate some jump instructions.
> 
> Best,
> Denghui

Hmm... After doing a preliminary test, I found your version performs better on JDK 17, so please ignore this suggestion.

Denghui

**Comment by richardstartin** [comment]
After the second commit this no longer regresses on committing empty events and is still faster on those with random identifiers. 

Are there any performance regression tests I can use to demonstrate this doesn't regress on typical use cases?

**Comment by mgronlun** [comment]
Sorry, the github bots take care of asking for OCA nowadays.

**Comment by jbachorik** [comment]
@mgronlun no worries. AFAIK, DataDog has a company wide OCA so it should cover also this work.

**Comment by richardstartin** [comment]
Hi Markus, I am committing this as a Datadog employee and believe I am covered by a company wide OCA.

We store trace and span identifiers which are uniformly distributed in [0, 2^63), so over 99.9% of these have the 8th byte set, so this represents a decent performance improvement for our use case, but obviously this shouldn't regress on core applications of this method, like stack traces and string fields. I am working on a benchmark with lots of `String` fields in the events so the majority of varints encoded are very short, to demonstrate this won't regress. It would be very helpful to run your internal benchmarks on this branch.

**Comment by egahlin** [comment]
Data is not random, it is typically small integers, in particular 0, and almost never negative. 

Do you have a benchmark on realistic numbers?

**Comment by richardstartin** [comment]
> Data is not random, it is typically small integers, in particular 0, and almost never negative.

@egahlin random ids as found in distributed tracing systems (i.e. user defined data in events) are certainly random. 

> Do you have a benchmark on realistic numbers?

The benchmark used is realistic for an integration with a distributed tracing system. I will produce benchmarks for events which contain strings to simulate typical offsets into the constant pool. If there are any benchmarks used for regression testing JFR events, it would be handy to run them on this patch.

**Comment by richardstartin** [comment]
While this is clearly beneficial to distributed tracing use cases of user defined JFR events, the gain isn't worth the bother of demonstrating conclusively that this does not regress elsewhere.

**Pull request closed without merging**
