### PR TITLE
8260307: Do not include method.hpp in frame.hpp

### PR DESCRIPTION
**Pull request by iklam**
frame.hpp is a popular header file (included by 876 out of 1000 HotSpot.o file). It includes method.hpp, which in turn pulls in all the class metadata types such as instanceKlass.hpp, constantPool.hpp, etc.

We can replace the inclusion of method.hpp with a forward declaration of the Method class.

This reduces the number of .o files that include method.hpp from 882 to 586.

HotSpot build time is reduced by more than 2%.

Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5. Also locally: aarch64, arm, ppc64, s390, x86, and zero.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260307](https://bugs.openjdk.java.net/browse/JDK-8260307): Do not include method.hpp in frame.hpp

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to fed529d03cb403cf48533145a87f9f75904fe5e0
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to fed529d03cb403cf48533145a87f9f75904fe5e0

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2201/head:pull/2201`
`$ git checkout pull/2201`

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Review by coleenp — APPROVED** [review]
This looks good!

**Comment by iklam** [comment]
Thanks @coleenp and @lfoltan for the review.
/integrate

**Pull request closed without merging**
