### PR TITLE
8250859: Address reliance on default constructors in the Accessibility APIs

### PR DESCRIPTION
**Pull request by ccleary-oracle**
This issue relates to JDK-8250639 '☂ Address reliance on default constructors in the java.desktop module'. The following classes have had an explicit no-arg constructor added, with a protected access modifier and accompanying API description:
 - Default ctor on com.sun.java.accessibility.util.SwingEventMonitor
 - Default ctor on javax.accessibility.AccessibleContext 
 - Default ctor on javax.accessibility.AccessibleHyperlink

The following classes have had an explicit no-arg constructor added, with a public access modifier and accompanying API description:
 - Default ctor on javax.accessibility.AccessibleResourceBundle
 - Default ctor on com.sun.java.accessibility.util.AWTEventMonitor
 - Default ctor on com.sun.java.accessibility.util.AccessibilityEventMonitor
 - Default ctor on com.sun.java.accessibility.util.AccessibilityListenerList
 - Default ctor on com.sun.java.accessibility.util.EventID

specdiff: http://cr.openjdk.java.net/~ccleary/issues/webrevs-store/8250859/webrevs/webrev.00/specdiff/overview-summary.html
bug: https://bugs.openjdk.java.net/browse/JDK-8250859

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8250859](https://bugs.openjdk.java.net/browse/JDK-8250859): Address reliance on default constructors in the Accessibility APIs

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to a2946acae8b43773b65857ca4444835d52ebbe00

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/174/head:pull/174`
`$ git checkout pull/174`

### CODE REVIEW

**Comment by ccleary-oracle** [comment]
Change requires approval of CSR, can't request that requirement myself as I am not a reviewer

**Review by prrace — APPROVED** [review]
This looks OK but the CSR needs updates first.

**Comment by ChrisHegarty** [comment]
The CSR lists `com.sun.java.accessibility.util.SwingEventMonitor` as being changed, but I cannot find that class in this PR.

**Comment by ccleary-oracle** [comment]
> The CSR lists `com.sun.java.accessibility.util.SwingEventMonitor` as being changed, but I cannot find that class in this PR.

Changes to this class were indeed missing. This has now been addressed. Thanks for spotting that!

**Pull request closed without merging**
