### PR TITLE
6453901: (cal) clean up sun.util.calendar classes

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
This PR includes cleanup changes to the sun.util.calendar package only.

The changes include removing unused methods, imports, adjusting incorrect links, and using newer syntax patterns. Since there are no plans to promote any of these classes to java.calendar, these unused methods can be removed.

Mach5: https://mach5.us.oracle.com/mdash/jobs/jclu-jdk2-20230228-2223-42671403

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6453901](https://bugs.openjdk.org/browse/JDK-6453901): (cal) clean up sun.util.calendar classes

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12817/head:pull/12817` \
`$ git checkout pull/12817`

Update a local copy of the PR: \
`$ git checkout pull/12817` \
`$ git pull https://git.openjdk.org/jdk pull/12817/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12817`

View PR using the GUI difftool: \
`$ git pr show -t 12817`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12817.diff">https://git.openjdk.org/jdk/pull/12817.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
Nice cleanup for removing dead code.

**Review by LanceAndersen — APPROVED** [review]

**Pull request closed without merging**
