### PR TITLE
8278433: Use snippets in jdk.incubator.foreign documentation

### PR DESCRIPTION
**Pull request by FrauBoes**
This change replaces `<pre>{@code ...}</pre>` blocks with the new `@snippet` tag. The change was applied to the panama-foreign repo with [1], now we bring it to the mainline. API doc (and Specdiff - not very informative) for reference [2]. 

[1] https://bugs.openjdk.java.net/browse/JDK-8277945
[2] http://cr.openjdk.java.net/~jboes/webrevs/8278433

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278433](https://bugs.openjdk.java.net/browse/JDK-8278433): Use snippets in jdk.incubator.foreign documentation

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**) ⚠️ Review applies to 0aaf866d22e1457a74068bba93407d23fac9f4e0

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6771/head:pull/6771` \
`$ git checkout pull/6771`

Update a local copy of the PR: \
`$ git checkout pull/6771` \
`$ git pull https://git.openjdk.java.net/jdk pull/6771/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6771`

View PR using the GUI difftool: \
`$ git pr show -t 6771`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6771.diff">https://git.openjdk.java.net/jdk/pull/6771.diff</a>

</details>

### CODE REVIEW

**Comment by pavelrappo** [comment]
Are differences in indentation between "before" and "after" intentional?

**Comment by pavelrappo** [comment]
Unrelated: this codebase could enjoy the inline version of the `@return` tag too; see JDK-8075778.

**Review by mcimadamore — APPROVED** [review]
Looks good (already reviewed it on panama-dev)

**Comment by mcimadamore** [comment]
> Are differences in indentation between "before" and "after" intentional?

I believe so.

> Unrelated: this codebase could enjoy the inline version of the `@return` tag too; see JDK-8075778.

Nice suggestion, thanks!

**Comment by FrauBoes** [comment]
> Are differences in indentation between "before" and "after" intentional?

Yes, there are a few places where I touched up the indentation.

**Pull request closed without merging**
