### PR TITLE
8254286: Wrong inference in switch expression with "null" arm

### PR DESCRIPTION
**Pull request by lahodaj**
Basically, for code like:

        var t1 = switch (s) {
            case 1 -> i1;
            case 2 -> null;
            default -> i2;
        };

Attr.condType is currently passing <type-of-i1>, BOT, <type-of-i2> to Types.lub. But Types.lub needs the list without BOT, so filtering BOT(s) out of the list.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ❌ (2/5 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x64 (build hotspot minimal)](https://github.com/lahodaj/jdk/runs/1241682393)
- [Linux x64 (build hotspot zero)](https://github.com/lahodaj/jdk/runs/1241682376)

### Issue
 * [JDK-8254286](https://bugs.openjdk.java.net/browse/JDK-8254286): Wrong inference in switch expression with "null" arm

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/583/head:pull/583`
`$ git checkout pull/583`

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
The fix looks fine. Note that in method inference we also skip the erroneous case:

```
@Override
        public boolean accepts(Type t) {
            return !t.isErroneous() && !inferenceContext.free(t) &&
                    !t.hasTag(BOT);
        }
```

Not sure whether this applies here too - maybe erroneous types are already skipped earlier?

**Comment by lahodaj** [comment]
> The fix looks fine. Note that in method inference we also skip the erroneous case:
> 
> ```
> @Override
>         public boolean accepts(Type t) {
>             return !t.isErroneous() && !inferenceContext.free(t) &&
>                     !t.hasTag(BOT);
>         }
> ```
> 
> Not sure whether this applies here too - maybe erroneous types are already skipped earlier?

Right - I believe errors are handled by the preceding conditions in condType.

**Review by vicente-romero-oracle — APPROVED** [review]
looks sensible

**Pull request closed without merging**
