### PR TITLE
8309698: [S390X] Test hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java fails after JDK-8299089

### PR DESCRIPTION
**Pull request by mmatti-sw**
On s390 the testcase "VirtualAllocCommitMerge.java" when run under Interpreter with option -Xint fails. But when run as compiled with option -Xcomp -Xbatch it Passes.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309698](https://bugs.openjdk.org/browse/JDK-8309698): [S390X] Test hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java fails after JDK-8299089 (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20096/head:pull/20096` \
`$ git checkout pull/20096`

Update a local copy of the PR: \
`$ git checkout pull/20096` \
`$ git pull https://git.openjdk.org/jdk.git pull/20096/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20096`

View PR using the GUI difftool: \
`$ git pr show -t 20096`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20096.diff">https://git.openjdk.org/jdk/pull/20096.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20096#issuecomment-2217186792)

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
I see the comment saying this is in alternative but we will need to test it again in our CI.

Given this test specifically chooses the compilation mode it should also exclude being run under other modes, or even specify `@requires vm.flagless` - as it makes no sense to have the `-Xint` overridden.

**Comment by dholmes-ora** [comment]
Testing in our CI was good.

**Comment by tstuefe** [comment]
Did anyone actually analyze this problem? What is the root cause? Switching the JIT on and off at random should have no bearing on how NMT functions.

I see, looking at the test output, that it fails with 

```
java.lang.RuntimeException: '\\[0x[0]*40dafa4000 - 0x[0]*40db004000\\] committed 384KB from.*' missing from stdout/stderr
```

But the output is there, in the virtual mapping printout:

```
[0x00000040dafa4000 - 0x00000040db3a4000] reserved 4096KB for Test 

	[0x00000040dafa4000 - 0x00000040db004000] committed 384KB 
```

But I guess the callstack is missing? So I would like to understand why, and whats preventing the callstack from being shown, and why switching on the JIT helps?

NMT is an important component. Just disabling tests that indicate problems is good.

**Comment by dholmes-ora** [comment]
> Switching the JIT on and off at random should have no bearing on how NMT functions.

The existing comment in the test indicates the test either needs nothing compiled, or everything, else it can't do what it intended.

I agree there is some utility in understanding why S390 interpreter behaviour doesn't meet the test's expectations.

**Comment by tstuefe** [comment]
> > Switching the JIT on and off at random should have no bearing on how NMT functions.
> 
> The existing comment in the test indicates the test either needs nothing compiled, or everything, else it can't do what it intended.
> 
> I agree there is some utility in understanding why S390 interpreter behaviour doesn't meet the test's expectations.

But that's not the reason the test fails. And it should have worked with -Xint. 

Here, we don't have a stack at all. That is a different error. And when did it start failing? I see that some stacks are printed. Is stack printing broken for some cases on s390?

**Comment by tstuefe** [comment]
I also like Xint more, since stacks are more stable - we take the JIT out of the equation. Compile decisions could be different between different runs. If not today, it is not guaranteed never to happen - nobody guarantees exactly how the JIT optimizes and that it is bound to repeat the same decisions on every run.

**Comment by mmatti-sw** [comment]
> Did anyone actually analyze this problem? What is the root cause? Switching the JIT on and off at random should have no bearing on how NMT functions.

Let me have a look at this.

**Comment by tstuefe** [comment]
> > Did anyone actually analyze this problem? What is the root cause? Switching the JIT on and off at random should have no bearing on how NMT functions.
> 
> Let me have a look at this.

It would be interesting to know if this is something that started to happen recently, and if yes, which patch broke it.

**Comment by mmatti-sw** [comment]
> It would be interesting to know if this is something that started to happen recently, and if yes, which patch broke it.

According to the issue https://bugs.openjdk.org/browse/JDK-8309698, the commit https://github.com/openjdk/jdk/commit/c7056737e33d3d5a6ec24639d46b9e3e7a8da01a broke this!

**Comment by offamitkumar** [comment]
I can reproduce it on `jdk11u-dev` head as well. So I guess this is coming from far back than that commit.

**Comment by tstuefe** [comment]
> I can reproduce it on `jdk11u-dev` head as well. So I guess this is coming from far back than that commit.

Huh that's weird. Is this a particular hardware configuration that is new, or a new compiler?

What happens:

We use NativeCallStack to get a stack at the point os::commit_memory is called:

https://github.com/openjdk/jdk/blob/2928753bd95356467e4fe42ee391e45d1cb6e89c/src/hotspot/share/runtime/os.cpp#L2117

CALLER_PC evaluates NativeCallStack(1), which walks the stack starting one frame above. If that fails, the stack will have 0 in its first slot (https://github.com/openjdk/jdk/blob/2928753bd95356467e4fe42ee391e45d1cb6e89c/src/hotspot/share/utilities/nativeCallStack.hpp#L59) and printing will stop right away (https://github.com/openjdk/jdk/blob/2928753bd95356467e4fe42ee391e45d1cb6e89c/src/hotspot/share/nmt/memReporter.cpp#L427-L432).

But according to the printout, there is no general problem with stack printing, since I see callstacks ending in os::commit_memory (see the many "committed xxx from").

In this case, the stack should show the whitebox function `WB_NMTCommitMemory` which calls `os::commit_memory()` (https://github.com/openjdk/jdk/blob/62cbf70346e78ca94ce6ea4ba5a308ea0a2bbfa8/src/hotspot/share/prims/whitebox.cpp#L715-L718)

So, the task would be to find out whats so special about this function that it does not show up in the callstack.

**Comment by mmatti-sw** [comment]
I think the  os::current_stack_pointer() implementation for s390 needs to be looked into along with NativeCallStack::NativeCallStack(int toSkip).

**Comment by TheShermanTanker** [comment]
> I think the os::current_stack_pointer() implementation for s390 needs to be looked into along with NativeCallStack::NativeCallStack(int toSkip).

I've been thinking of looking at and possibly improving the implementations of os::current\_stack\_pointer for each platform recently, let me know if you plan on changing the implementation of s390x

**Review by tstuefe — CHANGES_REQUESTED** [review]
I still disagree with the patch as it is now. The error should be analyzed, understood, and fixed. E.g. I don't get the relationship to JDK-8299089. What in JDK-8299089 can have caused stack walking on s390 to fail?

This fix is not terribly urgent, since the error just affects stacks in NMT virtual allocation printouts, and only some stacks at that. So, if you want to get the s390 CI clean, it would be fine to problem-list the test for s390. That is usually how we mute problems that we cannot fix immediately.

I just want to prevent uncommented "cargo-cult-programming" to slip into NMT tests: things we do but we don't know why. That does not help anyone, it just adds a layer of obfuscation.

Thanks, Thomas

**Pull request closed without merging**
