### PR TITLE
8302262: Remove -XX:SuppressErrorAt develop option

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change which removes the -XX:SuppressErrorAt develop option
and the associated implementation.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302262](https://bugs.openjdk.org/browse/JDK-8302262): Remove -XX:SuppressErrorAt develop option

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [c7163aa3](https://git.openjdk.org/jdk/pull/12521/files/c7163aa3f15abd133aea3e8e38a8e8c36ec063ad)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [c7163aa3](https://git.openjdk.org/jdk/pull/12521/files/c7163aa3f15abd133aea3e8e38a8e8c36ec063ad)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [c7163aa3](https://git.openjdk.org/jdk/pull/12521/files/c7163aa3f15abd133aea3e8e38a8e8c36ec063ad)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12521/head:pull/12521` \
`$ git checkout pull/12521`

Update a local copy of the PR: \
`$ git checkout pull/12521` \
`$ git pull https://git.openjdk.org/jdk pull/12521/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12521`

View PR using the GUI difftool: \
`$ git pr show -t 12521`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12521.diff">https://git.openjdk.org/jdk/pull/12521.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
While I have used it rarely, I found it useful the few times I did.

Its useful in situations where I analyzed a problem, ran into an assert, but obtaining a new build was difficult or just time-consuming - slow hardware, or a customer's machine. E.g., I used this switch when porting to AIX since rebuilding the VM took about an hour and some asserts could be waived.

Quoting from[ JDK-8302189](https://bugs.openjdk.org/browse/JDK-8302189):
> "This also addresses the problems encountered in [JDK-8294031](https://bugs.openjdk.org/browse/JDK-8294031). Because the failure reporting function used by assert is not "noreturn", the compiler is analyzing the continuation from a failed assert as potentially having the values that would result in an assertion failure (in this case, a variable having a null value). Doing so, it discovers a use of that variable in a context where a null value is UB, and so issues a warning."

I don't understand why this is not a problem for release builds. Relying on assert in this case is not sufficient anyway, you'd need to handle the nullptr in release builds too.

> "This matters even for production, since some of the operations (such as `guarantee` and `ShouldNotReachHere`) are present in product builds, not just debug builds. "

I can see that. But `guarantee` is rare, so maybe a compromise would be to make `guarantee` `noreturn` but leave `assert` as it is?

**Comment by kimbarrett** [comment]
> While I have used it rarely, I found it useful the few times I did.
> 
> Its useful in situations where I analyzed a problem, ran into an assert, but obtaining a new build was difficult or just time-consuming - slow hardware, or a customer's machine. E.g., I used this switch when porting to AIX since rebuilding the VM took about an hour and some asserts could be waived.
> 
> Quoting from[ JDK-8302189](https://bugs.openjdk.org/browse/JDK-8302189):
> 
> > "This also addresses the problems encountered in [JDK-8294031](https://bugs.openjdk.org/browse/JDK-8294031). Because the failure reporting function used by assert is not "noreturn", the compiler is analyzing the continuation from a failed assert as potentially having the values that would result in an assertion failure (in this case, a variable having a null value). Doing so, it discovers a use of that variable in a context where a null value is UB, and so issues a warning."
> 
> I don't understand why this is not a problem for release builds. Relying on assert in this case is not sufficient anyway, you'd need to handle the nullptr in release builds too.

In the example from JDK-8294031 the value shouldn’t be null. But the existence
of the not-null assertion indicates that it was null on the failed assertion
branch of the conditional. That branch doesn’t terminate in a
noreturn/unreachable black hole. The compiler can separately treat the
post-assertion rejoin point as two different continuations, one of which
definitely has a null value (because of the lack of the black hole). And that
leads to discovering later code that is unhappy with that null value, and
warning about it. That kind of splitting and value propagation is a normal
thing that can happen for all kinds of value, not just checks for non-null.
For example, an index in-bounds assertion could run into exactly the same
issue.

In a release build there isn't a null check, so the compiler has no
information either way, and _assumes_ the code doesn't invoke UB, and doesn't
check for it either.
 
> > "This matters even for production, since some of the operations (such as `guarantee` and `ShouldNotReachHere`) are present in product builds, not just debug builds. "
> 
> I can see that. But `guarantee` is rare, so maybe a compromise would be to make `guarantee` `noreturn` but leave `assert` as it is?

Also `ShouldNotReachHere`, `fatal`, &etc. which are pretty common.

**Comment by tstuefe** [comment]
> > While I have used it rarely, I found it useful the few times I did.
> > Its useful in situations where I analyzed a problem, ran into an assert, but obtaining a new build was difficult or just time-consuming - slow hardware, or a customer's machine. E.g., I used this switch when porting to AIX since rebuilding the VM took about an hour and some asserts could be waived.
> > Quoting from[ JDK-8302189](https://bugs.openjdk.org/browse/JDK-8302189):
> > > "This also addresses the problems encountered in [JDK-8294031](https://bugs.openjdk.org/browse/JDK-8294031). Because the failure reporting function used by assert is not "noreturn", the compiler is analyzing the continuation from a failed assert as potentially having the values that would result in an assertion failure (in this case, a variable having a null value). Doing so, it discovers a use of that variable in a context where a null value is UB, and so issues a warning."
> > 
> > 
> > I don't understand why this is not a problem for release builds. Relying on assert in this case is not sufficient anyway, you'd need to handle the nullptr in release builds too.
> 
> In the example from JDK-8294031 the value shouldn’t be null. But the existence of the not-null assertion indicates that it was null on the failed assertion branch of the conditional. That branch doesn’t terminate in a noreturn/unreachable black hole. The compiler can separately treat the post-assertion rejoin point as two different continuations, one of which definitely has a null value (because of the lack of the black hole). And that leads to discovering later code that is unhappy with that null value, and warning about it. That kind of splitting and value propagation is a normal thing that can happen for all kinds of value, not just checks for non-null. For example, an index in-bounds assertion could run into exactly the same issue.
> 
> In a release build there isn't a null check, so the compiler has no information either way, and _assumes_ the code doesn't invoke UB, and doesn't check for it either.

Interesting. Thanks for explaining this. So the fact that we set the assert triggers the compiler check.

> 
> > > "This matters even for production, since some of the operations (such as `guarantee` and `ShouldNotReachHere`) are present in product builds, not just debug builds. "
> > 
> > 
> > I can see that. But `guarantee` is rare, so maybe a compromise would be to make `guarantee` `noreturn` but leave `assert` as it is?
> 
> Also `ShouldNotReachHere`, `fatal`, &etc. which are pretty common.

In the light of your explanation, I think loosing the switch could be an acceptable price. I see the C-asserts in glibc also use noreturn attributes. Less code is also nice.

**Comment by tstuefe** [comment]
Stupid question, what happens if a function is decorated with noreturn and you return? E.g. in case of the `Debugging` switch? Or by just falling off the function, failing to call exit or abort?

**Comment by kimbarrett** [comment]
> Stupid question, what happens if a function is decorated with noreturn and you return? E.g. in case of the `Debugging` switch? Or by just falling off the function, failing to call exit or abort?

Undefined behavior.  gcc warns about this (with the warning levels we currently have).  I didn't experiment with others.

The `Debugging` variable is another thing that will need to be addressed in order to make the failed assertion reporters
noreturn.  Also Windows-only `UseOSErrorReporting`.  (My in-progress prototype for JDK-8302189 retains those
features in a different form, rather than outright deletion as being done here for `SuppressErrorAt`.)

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
> Interesting. Thanks for explaining this. So the fact that we set the assert triggers the compiler check.

For the public record I was a supporter of the use of `SuppressErrorAt` as I have often found it useful when reproducing product failures on debug builds. I was also frustrated that the assertion triggers the extra compiler checks - a classic example, to me, of the compiler trying to be too clever/helpful and actually just causing problems.

But I have been persuaded that the trade-offs come down (slightly) in favour of removing `SuppressErrorAt`, even though for me build times are slow enough that disabling the problem  assertion is still an inconvenience.

**Review by dholmes-ora — APPROVED** [review]
Changes look good - smaller than I had envisaged. Getting rid of the archaic test comments is fine too.

Thanks.

**Comment by jcking** [comment]
Drive by comment. Glad to see this, was going to propose this at some point as well.

**Review by tschatzl — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks for reviews.

**Pull request closed without merging**
