### PR TITLE
8270098: ZGC: ZBarrierSetC2::clone_at_expansion fails with "Guard against surprises" assert

### PR DESCRIPTION
**Pull request by TobiHartmann**
The fix for [JDK-8268125](https://bugs.openjdk.java.net/browse/JDK-8268125) ([PR 53](https://git.openjdk.java.net/jdk17/pull/53)) assumed that only dead code can have a clone array with an unknown array ptr type at expansion time. As `TestObjectArrayClone::testCloneObject` proves, that is not true because we can invoke `Object::clone` on any object, including arrays.

As a result, invoking `Object::clone` on an Object array leads to triggering the "Guard against surprises" assert in debug and to incorrectly using the `T_LONG` copy stub (without GC barriers) in product. I was not able to trigger a crash in product but a corresponding runtime check (see [patch](https://bugs.openjdk.java.net/secure/attachment/95954/runtime_check.patch)) triggered reliably.

The fix is to fall back to `ZBarrierSetRuntime::clone` if the array ptr type is unknown. I will backport this fix to JDK 17u.

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270098](https://bugs.openjdk.java.net/browse/JDK-8270098): ZGC: ZBarrierSetC2::clone_at_expansion fails with "Guard against surprises" assert

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5048/head:pull/5048` \
`$ git checkout pull/5048`

Update a local copy of the PR: \
`$ git checkout pull/5048` \
`$ git pull https://git.openjdk.java.net/jdk pull/5048/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5048`

View PR using the GUI difftool: \
`$ git pr show -t 5048`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5048.diff">https://git.openjdk.java.net/jdk/pull/5048.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks for the review, Nils!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by TobiHartmann** [comment]
Thanks for the review, Vladimir!

**Pull request closed without merging**
