### PR TITLE
8132984: incorrect type for Reference.discovered

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change which fixes the type of the private
Reference.discovered field.  It was Reference<T>, but that's wrong because
it can be any Reference object.

I've changed it to Reference<?> and let that flow through, updating some
other variables that were previously somewhat incorrectly typed (usually
with an Object type parameter). The interesting change is to the
ReferenceQueue.enqueue parameter, which is now also Reference<?>.

This ultimately end up with a provably safe and correct, but uncheckable,
cast in ReferenceQueue.enqueue.

An alternative might be to use a raw type for the discovered field, but I
think that ends up with more @SuppressWarnings of various flavors.  I think
the unbounded wildcard approach is clearer and cleaner.

Note that all of the pending list handling, including the discovered field,
could be moved into a non-public, non-generic, sealed(?) base class of
Reference<T>.  The pending list handling has nothing to do with the generic
parameter T.

Testing:
mach5 tier1 and tier4 (tier4 is where vmTestbase_vm_gc_ref tests are run)

/label core-libs
/summary Use unbounded wildcard placeholders and final safe but unchecked cast.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8132984](https://bugs.openjdk.java.net/browse/JDK-8132984): incorrect type for Reference.discovered

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to b95f5140df945b8e4782a59747a98f20339d157d
 * [Peter Levart](https://openjdk.java.net/census#plevart) (@plevart - **Reviewer**) ⚠️ Review applies to b95f5140df945b8e4782a59747a98f20339d157d
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**) ⚠️ Review applies to b95f5140df945b8e4782a59747a98f20339d157d
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to b95f5140df945b8e4782a59747a98f20339d157d

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1897/head:pull/1897`
`$ git checkout pull/1897`

### CODE REVIEW

**Comment by plevart** [comment]
Hi Kim,

If you introduce a private method in Reference:

```
    private void enqueueFromPending() {
        var q = queue;
        if (q != ReferenceQueue.NULL) q.enqueue(this);
    }
```

...and use it Reference.processPendingReferences while loop like this:

```
            if (ref instanceof Cleaner) {
                ...
            } else {
                ref.enqueueFromPending();
            }
```

Then you can keep the signature of `ReferenceQueue.enqueue(Reference<? extends T> r)` and no unchecked casts are needed there.

But what you have is OK and much better than what was before.

**Review by rkennke — APPROVED** [review]
Looks good to me!

**Review by plevart — APPROVED** [review]
This looks good.

**Review by RogerRiggs — APPROVED** [review]

**Review by mlchung — APPROVED** [review]
Looks good.

**Comment by kimbarrett** [comment]
Thanks @plevart , @rkennke , @RogerRiggs , and @mlchung for reviews.

**Comment by kimbarrett** [comment]
/summary Use unbounded wildcard placeholders, plus a new helper to get back to the Reference<T> domain.

**Pull request closed without merging**
