### PR TITLE
8327794: RISC-V: enable extension features based on impid (Rivos specific change)

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you review the patch? it enables extension features based on impid.
Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327794](https://bugs.openjdk.org/browse/JDK-8327794): RISC-V: enable extension features based on impid (Rivos specific change) (**Enhancement** - P4)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)
 * [Antonios Printezis](https://openjdk.org/census#tonyp) (@gctony - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18191/head:pull/18191` \
`$ git checkout pull/18191`

Update a local copy of the PR: \
`$ git checkout pull/18191` \
`$ git pull https://git.openjdk.org/jdk.git pull/18191/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18191`

View PR using the GUI difftool: \
`$ git pr show -t 18191`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18191.diff">https://git.openjdk.org/jdk/pull/18191.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18191#issuecomment-1988281466)

### CODE REVIEW

**Review by robehn — APPROVED** [review]
Thanks!

**Review by luhenry — APPROVED** [review]
Can you change the title of the issue + PR to mention it's a Rivos specific change?

**Comment by Hamlin-Li** [comment]
> Can you change the title of the issue + PR to mention it's a Rivos specific change?

Done.

**Review by lgxbslgx — APPROVED** [review]

**Comment by RealFYang** [comment]
> > Hi Hamlin, Could you please merge master? That will retrigger the GHA testing automatically and hopefully pass linux-cross-compile for linux-riscv64.
> 
> Done.

Hmm ... Seems that the new GHA run blocked. But the changes looks OK.

**Comment by Hamlin-Li** [comment]
Thanks everyone for your reviewing!

/integrate

**Pull request closed without merging**
