### PR TITLE
8305527: HarfBuzz: Remove trailing comma from the enum in hb-paint.h

### PR DESCRIPTION
**Pull request by dmarkov20**
Port the fix from the upstream/HarfBuzz repo.

More info can be obtained here:
https://github.com/harfbuzz/harfbuzz/discussions/4188 
https://github.com/harfbuzz/harfbuzz/commit/04a47932a3844f7e73e3af8b05fb98c8b54fb779

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305527](https://bugs.openjdk.org/browse/JDK-8305527): HarfBuzz: Remove trailing comma from the enum in hb-paint.h

### Reviewers
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - Committer)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13328/head:pull/13328` \
`$ git checkout pull/13328`

Update a local copy of the PR: \
`$ git checkout pull/13328` \
`$ git pull https://git.openjdk.org/jdk.git pull/13328/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13328`

View PR using the GUI difftool: \
`$ git pr show -t 13328`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13328.diff">https://git.openjdk.org/jdk/pull/13328.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13328#issuecomment-1496220977)

### CODE REVIEW

**Review by honkar-jdk — APPROVED** [review]

**Review by prrace — CHANGES_REQUESTED** [review]
I don't see why we need this in mainline. I'd prefer to not have it unless we need it.

**Comment by mrserb** [comment]
> I don't see why we need this in mainline. I'd prefer to not have it unless we need it.

One reason is that It will be easy to backport to the old versions where the old compilers are used.

**Comment by prrace** [comment]
> > I don't see why we need this in mainline. I'd prefer to not have it unless we need it.
> 
> I believe it is better to have all JDK branches in sync if it's possible. This change is harmless and as Sergey mentioned it would simplify backport process.

We'll get it anyway when we upgrade .. that's why we only apply changes that are accepted upstream.
And if we upgrade to a version that pre-dates it then we'll have to manually re-apply it for no reason.
It is just unnecessary.

**Comment by honkar-jdk** [comment]
> > > I don't see why we need this in mainline. I'd prefer to not have it unless we need it.
> > 
> > 
> > I believe it is better to have all JDK branches in sync if it's possible. This change is harmless and as Sergey mentioned it would simplify backport process.
> 
> We'll get it anyway when we upgrade .. that's why we only apply changes that are accepted upstream. And if we upgrade to a version that pre-dates it then we'll have to manually re-apply it for no reason. It is just unnecessary.

@dmarkov20 We will be having a HarfBuzz upgrade to mainline soon. As @prrace suggested, this might be unnecessary at this point then. 

@prrace What about patching it to other branches -17, 20u, will we be backporting the next planned upgrade changes to these branches too?

**Comment by prrace** [comment]
> @dmarkov20 We will be having a HarfBuzz upgrade to mainline soon. As @prrace suggested, this might be unnecessary at this point then.

I think it extremely likely we'll do a HB update before JDK 21 RDP1 so, yes.

**Comment by dmarkov20** [comment]
OK, I will am this PR then

> > @dmarkov20 We will be having a HarfBuzz upgrade to mainline soon. As @prrace suggested, this might be unnecessary at this point then.
> 
> I think it extremely likely we'll do a HB update before JDK 21 RDP1 so, yes.

OK, I am closing this one then

**Pull request closed without merging**
