### PR TITLE
8344215: Remove calls to SecurityManager and doPrivileged in java.net.Socket and java.net.ServerSocket after JEP 486 integration

### PR DESCRIPTION
**Pull request by vy**
I'd appreciate a review of this change set removing `SecurityManager` et al. from `java.net.Socket` and `java.net.ServerSocket`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344215](https://bugs.openjdk.org/browse/JDK-8344215): Remove calls to SecurityManager and doPrivileged in java.net.Socket and java.net.ServerSocket after JEP 486 integration (**Sub-task** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22254/head:pull/22254` \
`$ git checkout pull/22254`

Update a local copy of the PR: \
`$ git checkout pull/22254` \
`$ git pull https://git.openjdk.org/jdk.git pull/22254/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22254`

View PR using the GUI difftool: \
`$ git pr show -t 22254`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22254.diff">https://git.openjdk.org/jdk/pull/22254.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22254#issuecomment-2486627796)
</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
Hi @dfuch, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user dfuch" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Review by AlanBateman — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]

**Comment by vy** [comment]
@dfuch, `tier2` tests passed, added the link to the ticket.

**Comment by dfuch** [comment]
Thanks Volkan! If you integrate I'll sponsor it.

**Comment by vy** [comment]
@dfuch, thanks so much for assisting me! (I was waiting for the GitHub Actions to give a green light. I will `/integrate` promptly.)

**Pull request closed without merging**
