### PR TITLE
8327098: GTest needs larger combination limit

### PR DESCRIPTION
**Pull request by kdnilsen**
The current value of LogSelectionList::MaxSelections is too small, causing GTest failures.  This increases the value from 256 to 320.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327098](https://bugs.openjdk.org/browse/JDK-8327098): GTest needs larger combination limit (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18083/head:pull/18083` \
`$ git checkout pull/18083`

Update a local copy of the PR: \
`$ git checkout pull/18083` \
`$ git pull https://git.openjdk.org/jdk.git pull/18083/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18083`

View PR using the GUI difftool: \
`$ git pr show -t 18083`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18083.diff">https://git.openjdk.org/jdk/pull/18083.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18083#issuecomment-1973355721)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
It looks okay, but I have questions: 
 1. Does it happen in mainline right now?
 2. Why are we hitting it with [JDK-8324649](https://bugs.openjdk.org/browse/JDK-8324649) PR? I don't see new logging tags added there.

**Comment by kdnilsen** [comment]
@shipilev: @earthling-amzn shares that he has seen this same failure on our Shenandoah repository and have applied a similar fix there.  It may be that the new ShenandoahFreeSet introduces more combinations of log tags than had been present previously.

**Comment by shipilev** [comment]
> @shipilev: @earthling-amzn shares that he has seen this same failure on our Shenandoah repository and have applied a similar fix there. It may be that the new ShenandoahFreeSet introduces more combinations of log tags than had been present previously.

Weird, I just tried to run all tests with #17561, and it passes well without these adjustments. Puzzling.

**Review by shipilev — COMMENTED** [review]
Not clear why this needed, so I am rescinding review for a while.

**Comment by kdnilsen** [comment]
On https://github.com/openjdk/jdk/pull/17561, commit https://github.com/openjdk/jdk/pull/17561/commits/42af76b4d529be7ed70015aecc8490f1cda9d703 incorporates this change in order to test whether this change addresses the regressions.  With this change, we now pass all GHA on that PR.

**Comment by phohensee** [comment]
GHA failures are unrelated.

**Comment by xmas92** [comment]
Note that there is also: [JDK-8325490](https://bugs.openjdk.org/browse/JDK-8325490)

**Pull request closed without merging**
