### PR TITLE
8248876: LoadObject with bad base address created for exec file on linux

### PR DESCRIPTION
**Pull request by YaSuenag**
We could see NPE on `LinuxCDebugger::loadObjectContainingPC` which is used mainly by the clhsdb `findpc` command. (See [JDK-8248876](https://bugs.openjdk.java.net/browse/JDK-8248876) for more details)

It is caused by PIE executable handling.

Currently we use virtual address of top of PT_LOAD in executable as base address - it is valid for ET_EXEC binary.
However, in case of ET_DYN binary (PIE binary), we should handle it like a shared library.
In GDB, base address of executable would be calculated by dynamic section. SA should also do so.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8248876](https://bugs.openjdk.java.net/browse/JDK-8248876): LoadObject with bad base address created for exec file on linux

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to ed352edd00aff22748df2352901327cbe3800afd
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to ed352edd00aff22748df2352901327cbe3800afd

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2366/head:pull/2366`
`$ git checkout pull/2366`

### CODE REVIEW

**Review by plummercj — APPROVED** [review]

**Comment by kevinjwalls** [comment]
Hi!
I found the "svr4_exec_displacement() in GDB" more confusing than informative, maybe this is the same technique GDB uses...  But I followed our dynamic_addr setting and agree with the new changes.

An alternative comment could be this, which would also removes the "substract" typo (which was not yours!):

ps_core.c 509

```
    } else { // ET_DYN
      // dynamic_addr was initially set to entry point (AT_ENTRY).
      // Now subtract the entry point offset to get load address:
      result = ph->core->dynamic_addr - exec_ehdr->e_entry;
      // Find actual dynamic_addr:
      ph->core->dynamic_addr += exec_php->p_vaddr - exec_ehdr->e_entry;
    }
```

**Review by kevinjwalls — APPROVED** [review]
Looks good, I made a suggestions elsewhere in the PR about the comments at line 510...

**Comment by YaSuenag** [comment]
@kevinjwalls Thank you for the comment!

> I found the "svr4_exec_displacement() in GDB" more confusing than informative, maybe this is the same technique GDB uses... But I followed our dynamic_addr setting and agree with the new changes.

I removed it in new commit.

> An alternative comment could be this, which would also removes the "substract" typo (which was not yours!):

It's my change in [JDK-8173941](https://bugs.openjdk.java.net/browse/JDK-8173941).
I removed it too.

**Comment by kevinjwalls** [comment]
Oops, I didn't mean to suggest  the comment should go entirely.  It's actually very useful to say something here, as the way we use the dynamic field, setting it then fixing it up.
Is it possible to re-add the comment in a new change?

**Comment by YaSuenag** [comment]
> Oops, I didn't mean to suggest the comment should go entirely. It's actually very useful to say something here, as the way we use the dynamic field, setting it then fixing it up.
> Is it possible to re-add the comment in a new change?

I thought your thumbs-up emoji means to agree to remove all comments.

As you know, I've integrated this PR, so we need to file as a new ticket.
I will do it and send a PR with following patch if you are ok.

```
diff --git a/src/jdk.hotspot.agent/linux/native/libsaproc/ps_core.c b/src/jdk.hotspot.agent/linux/native/libsaproc/ps_core.c
index dff4cb3eeca..9f7c4050ef2 100644
--- a/src/jdk.hotspot.agent/linux/native/libsaproc/ps_core.c
+++ b/src/jdk.hotspot.agent/linux/native/libsaproc/ps_core.c
@@ -507,7 +507,11 @@ static uintptr_t read_exec_segments(struct ps_prochandle* ph, ELF_EHDR* exec_ehd
         result = exec_php->p_vaddr;
         ph->core->dynamic_addr = exec_php->p_vaddr;
       } else { // ET_DYN
+        // Base address of executable is based on entry point (AT_ENTRY).
         result = ph->core->dynamic_addr - exec_ehdr->e_entry;
+
+        // dynamic_addr has entry point of executable.
+        // Thus we should subtract it.
         ph->core->dynamic_addr += exec_php->p_vaddr - exec_ehdr->e_entry;
       }
       print_debug("address of _DYNAMIC is 0x%lx\n", ph->core->dynamic_addr);
```

**Comment by kevinjwalls** [comment]
Thanks!

**Comment by YaSuenag** [comment]
@kevinjwalls I've sent PR about adding comments in #2478. I hope you review it!

**Pull request closed without merging**
