### PR TITLE
8325162: Remove duplicate GCMParameters class

### PR DESCRIPTION
**Pull request by djelinski**
Currently we have 2 GCMParameters classes in java.base, one in sun.security.util package, the other in com.sun.crypto.provider.

This PR merges the changes from the sun.security.util copy into com.sun.crypto.provider, and removes the sun.security.util class.

As far as I could tell, the sun.security.util class was added to avoid exporting com.sun.crypto.provider to jdk.crypto.cryptoki. The export was introduced later in [JDK-8259319](https://bugs.openjdk.org/browse/JDK-8259319), so there's no reason to keep both copies.

No new tests. Tier1-3 tests continue to pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325162](https://bugs.openjdk.org/browse/JDK-8325162): Remove duplicate GCMParameters class (**Enhancement** - P4)

### Reviewers
 * [Weijun Wang](https://openjdk.org/census#weijun) (@wangweij - **Reviewer**)
 * [Valerie Peng](https://openjdk.org/census#valeriep) (@valeriepeng - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17802/head:pull/17802` \
`$ git checkout pull/17802`

Update a local copy of the PR: \
`$ git checkout pull/17802` \
`$ git pull https://git.openjdk.org/jdk.git pull/17802/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17802`

View PR using the GUI difftool: \
`$ git pr show -t 17802`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17802.diff">https://git.openjdk.org/jdk/pull/17802.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17802#issuecomment-1938437651)

### CODE REVIEW

**Comment by djelinski** [comment]
mostly because the com.sun.crypto.provider was older (copyright 2013 vs 2019 on the other one). but I don't have a strong preference. I can keep the other one if you think it makes sense.

**Comment by djelinski** [comment]
alright then, I'll make the changes shortly.

Should I change the copyright and the `@since 13` tag? Given that the files are almost identical, it feels wrong to have 2 different copyrights, and `@since` doesn't make much sense on a non-public SPI class.

**Comment by johnshajiang** [comment]
Not review this change, but just a thought.

GCMParameters is a SPI implementation.
`com.sun.crypto.provider.GCMParameters` implies that class is a part of `SunJCE` provider, however `sun.security.util.GCMParameters` looks not.

**Comment by djelinski** [comment]
> `com.sun.crypto.provider.GCMParameters` implies that class is a part of `SunJCE` provider, however `sun.security.util.GCMParameters` looks not.

True. Also, the only other Parameters class in `sun.security.util` is `ECParameters`, which was moved to that package in 3d60beae0d773ba2f626a213e952fbf0e9f1db2b to avoid exporting `sun.security.ec` package to `jdk.crypto.cryptoki` module.

SunPKCS11 is already importing [com.sun.crypto.provider.ChaCha20Poly1305Parameters](https://github.com/openjdk/jdk/blob/ea4193222f36b0663a8bcbf45db86def9e645945/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java#L707), and in #17816 I'm proposing to import another parameters class from `com.sun.crypto.provider`.

I guess it would make sense to decide here if we want to move parameters shared between SunPKCS11 and some other provider to `sun.security.util`, or if we want to keep them in their original location.

**Comment by valeriepeng** [comment]
It's nice to consolidate and have only one impl for each algorithm. SunPKCS11 provider relies on other default JDK providers for algorithm parameters implementations. Having the spi impl under a specific provider's package implies the main ownership. Having the spi impl under sun.security.util implies that it's a shared utility class or library. Both has merits. I tend to go with majority since it minimizes the needed changes. As for GCMParameters, sun.security.util version contains newer changes, so we should keep that one (regardless of the package discussion).

**Comment by djelinski** [comment]
Thanks for the discussion.

/integrate

**Pull request closed without merging**
