### PR TITLE
8293061: Combine CDSOptions and AppCDSOptions test utility classes

### PR DESCRIPTION
**Pull request by matias9927**
AppCDSOptions class was moved into the CDSOptions class and relevant tests were updated. The updated tests pass. Verified with tier 1-4 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293061](https://bugs.openjdk.org/browse/JDK-8293061): Combine CDSOptions and AppCDSOptions test utility classes

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10515/head:pull/10515` \
`$ git checkout pull/10515`

Update a local copy of the PR: \
`$ git checkout pull/10515` \
`$ git pull https://git.openjdk.org/jdk pull/10515/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10515`

View PR using the GUI difftool: \
`$ git pr show -t 10515`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10515.diff">https://git.openjdk.org/jdk/pull/10515.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Code relocation looks accurate.

Thanks.

**Review by iklam — APPROVED** [review]
LGTM

**Review by calvinccheung — APPROVED** [review]
Thanks for fixing this. Looks good.

**Pull request closed without merging**
