### PR TITLE
8315442: Enable parallelism in vmTestbase/nsk/monitoring/stress/thread tests

### PR DESCRIPTION
**Pull request by shipilev**
Current vmTestbase/nsk/monitoring/stress/thread tests contains 21 tests, each running exclusively. This drags the tier4 test times up. There seem to be no reason to run these tests exclusively, though: they complete in reasonable time, are lightly-threaded, and consume the usual amount of memory.

We should consider enabling parallelism for them and get improved test performance. Currently it is blocked by TEST.properties with exclusiveAccess.dirs directives in them.

Current run on 18-core machine:
 1025.63s user 97.23s system 586% cpu 3:11.60 total

Fully parallel:
 1125.04s user 107.60s system 1583% cpu 1:17.83 total 

Additional testing:
 - [x]  50x iterations of Linux x86_64 fastdebug `vmTestbase/nsk/monitoring/stress/thread`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315442](https://bugs.openjdk.org/browse/JDK-8315442): Enable parallelism in vmTestbase/nsk/monitoring/stress/thread tests (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15508/head:pull/15508` \
`$ git checkout pull/15508`

Update a local copy of the PR: \
`$ git checkout pull/15508` \
`$ git pull https://git.openjdk.org/jdk.git pull/15508/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15508`

View PR using the GUI difftool: \
`$ git pr show -t 15508`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15508.diff">https://git.openjdk.org/jdk/pull/15508.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15508#issuecomment-1700723001)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
I think this is fine, but it may inconvenience some test maintainers since we may now run against  /proc/sys/kernel/threads-max or whatever other limits there are. Or do we do worse things already in other tests?

**Review by lmesnik — APPROVED** [review]

**Review by dholmes-ora — COMMENTED** [review]
There is no explanation as to why these were run exclusively when first introduced, unfortunately. I'm always concerned about running multiple "stress" tests concurrently however.

@lmesnik can you test this in our CI please? (I would but am starting vacation in a few hours).

**Comment by shipilev** [comment]
> I think this is fine, but it may inconvenience some test maintainers since we may now run against /proc/sys/kernel/threads-max or whatever other limits there are. Or do we do worse things already in other tests?

Yeah, I think we do worse, e.g. GC stress tests in tier3, which can hog CPUs for minutes, without ill effects. Not sure if we stress out huge amount of threads.

Anyway, this is similar to other parallelism improvements we did over the previous years, e.g. https://bugs.openjdk.org/browse/JDK-8273433, https://bugs.openjdk.org/browse/JDK-8273438 -- so I gradually continue this one test directory after another :)

**Comment by shipilev** [comment]
> @lmesnik can you test this in our CI please? (I would but am starting vacation in a few hours).

Yes, that would be nice. I did my own stability testing (see PR "Additional testing"), and that passed well. 

Given the prior experience with these parallelism improvements, I expect no problems. ...and we can revert this change if found problematic. Which would also give us a bug trail why these needed to be sequential.

**Comment by lmesnik** [comment]
I tested fix in CI, no issues.

**Comment by shipilev** [comment]
Thanks! I'll integrate this one then.

/integrate

**Pull request closed without merging**
