### PR TITLE
8289688: jfr command hangs when it processes invalid file

### PR DESCRIPTION
**Pull request by YaSuenag**
jfr command was in infinite loop when I passed invalid file which are in JFR repository of GraalVM Native Image (I attached the recording file to JBS).

CPU usage was 100% when jfr hanged, and I got following thread stacks:

```
"main" #1 prio=5 os_prio=0 cpu=10333.35ms elapsed=10.67s tid=0x00007f4994013810 nid=10079 runnable [0x00007f499adfe000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.seek0([java.base@18.0.1](mailto:java.base@18.0.1)/Native Method)
        at java.io.RandomAccessFile.seek([java.base@18.0.1](mailto:java.base@18.0.1)/RandomAccessFile.java:591)
        at jdk.jfr.internal.consumer.RecordingInput.positionPhysical([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/RecordingInput.java:102)
        at jdk.jfr.internal.consumer.ChunkHeader.refresh([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/ChunkHeader.java:124)
        at jdk.jfr.internal.consumer.ChunkHeader.<init>([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/ChunkHeader.java:108)
        at jdk.jfr.internal.consumer.ChunkHeader.<init>([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/ChunkHeader.java:66)
        at jdk.jfr.internal.consumer.ChunkParser.<init>([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/ChunkParser.java:117)
        at jdk.jfr.internal.consumer.ChunkParser.<init>([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/ChunkParser.java:113)
        at jdk.jfr.consumer.RecordingFile.findNext([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/RecordingFile.java:256)
        at jdk.jfr.consumer.RecordingFile.<init>([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/RecordingFile.java:89)
        at jdk.jfr.internal.tool.EventPrintWriter.print([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/EventPrintWriter.java:72)
        at jdk.jfr.internal.tool.Print.execute([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/Print.java:164)
        at jdk.jfr.internal.tool.Main.main([jdk.jfr@18.0.1](mailto:jdk.jfr@18.0.1)/Main.java:87)
```

And also I got following log with `-J-Xlog:"jfr*=info"` - chunk size was 0, and the parser hanged in processing first chunk (id = 0):

```
$ jfr -J-Xlog:"jfr*=info" print ~/2022_07_04_18_05_11.jfr
[0.353s][info][jfr,system,parser] Chunk: 0
[0.353s][info][jfr,system,parser] Chunk: file=/home/ysuenaga/2022_07_04_18_05_11.jfr
[0.353s][info][jfr,system,parser] Chunk: startPosition=0
[0.353s][info][jfr,system,parser] Chunk: major=2
[0.353s][info][jfr,system,parser] Chunk: minor=0
[0.353s][info][jfr,system,parser] Chunk: chunkSize=0
[0.353s][info][jfr,system,parser] Chunk: constantPoolPosition=0
[0.353s][info][jfr,system,parser] Chunk: metadataPosition=0
[0.353s][info][jfr,system,parser] Chunk: startNanos=0
[0.353s][info][jfr,system,parser] Chunk: durationNanos=0
[0.354s][info][jfr,system,parser] Chunk: startTicks=9410187
[0.354s][info][jfr,system,parser] Chunk: ticksPerSecond=1000000000
```

We should abort the process when invalid chunk was detected.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289688](https://bugs.openjdk.org/browse/JDK-8289688): jfr command hangs when it processes invalid file

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9363/head:pull/9363` \
`$ git checkout pull/9363`

Update a local copy of the PR: \
`$ git checkout pull/9363` \
`$ git pull https://git.openjdk.org/jdk pull/9363/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9363`

View PR using the GUI difftool: \
`$ git pr show -t 9363`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9363.diff">https://git.openjdk.org/jdk/pull/9363.diff</a>

</details>

### CODE REVIEW

**Comment by egahlin** [comment]
It looks like the real problem is how GraalVM Native Image writes recording data.

If the header is complete, is 68 bytes or more, the size of the field should be larger than 0. If the size filed is updated during a recording, it should use the proper protocol (modifying the file state in the header) to make sure the update is atomic.

The new check (c <= 0) is added where the value is read for logging, which is an "unreliable" read. The JVM might be modifying bytes in the header at the same time as it is being read by the parser, so it can be incorrect. Not sure we should add checks here. The magic and version are checked today, but they never change for a recording.

I would try to change this in GraalVM Native Image image instead.

**Comment by YaSuenag** [comment]
> It looks like the real problem is how GraalVM Native Image writes recording data.

Agree.


> If the header is complete, is 68 bytes or more, the size of the field should be larger than 0. If the size filed is updated during a recording, it should use the proper protocol (modifying the file state in the header) to make sure the update is atomic.
> 
> The new check (c <= 0) is added where the value is read for logging, which is an "unreliable" read. The JVM might be modifying bytes in the header at the same time as it is being read by the parser, so it can be incorrect. Not sure we should add checks here. The magic and version are checked today, but they never change for a recording.

Did you say JVM would write recording file with random access?
Even if that is the case, it means recording file might be "unreliable" when it conflicts reading / writing, isn't it? I think jfr command should throw an error in that case.

> I would try to change this in GraalVM Native Image image instead.

I agree with you to fix GraalVM Native Image.
However, according to your comment, recording file might be invalid in corner case, so I think it is better to handle it.

In JMC, we can see error dialog in that case.
jmc

**Comment by YaSuenag** [comment]
I debug'ed JfrHtmlRulesReport in JMC to know how JMC detects the chunk is broken.  
I found the error happend to process the second chunk - JMC detected it has invalid magic.

JMC would read the chunk while the index is lower than chunk size as following. On the other hand, jfr command does not rely on chunk size in `ChunkHeader::refresh()`. This is the big difference between JMC and jfr, and it is cause of infinite loop.

https://github.com/openjdk/jmc/blob/8.2.0-ga/core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/parser/v1/ChunkLoaderV1.java#L82-L95

```java
// Read events
long index = header.getBodyStartOffset();
while (index < header.getChunkSize()) {
	input.seek(index);
	int size = input.readInt();
	long type = input.readLong();
	if (size == 0) {
		throw new CouldNotLoadRecordingException("Found event with invalid size (0)"); //$NON-NLS-1$
	}
	if (type != CONSTANT_POOL_EVENT_TYPE && type != ChunkMetadata.METADATA_EVENT_TYPE) {
		manager.readEvent(type, input, size);
	}
	index += size;
}
```

I think it is better to refactor jfr code like JMC, but it will big change. So I think this PR is a reasonable to fix the problem.

**Comment by egahlin** [comment]
> Did you say JVM would write recording file with random access? 

Yes, it writes the chunk header using random access. 

>Even if that is the case, it means recording file might be "unreliable" when it conflicts reading / writing, isn't it?

Not if the parser follows a protocol where the file state is checked in the header. With JDK 14, JFR file format is streaming, but backward compatible for non-streaming parsers that only reads finished files.

The JDK parser can read a recording while it is being written. The JMC parser doesn't support streaming, so it would be incorrect to use that logic.

**Comment by YaSuenag** [comment]
Even if JDK parser should support streaming, we should avoid infinite loop in it because the recording file may be broken.

Can we add timeout or loop limit in this area?

**Comment by egahlin** [comment]
There is a limit of 1000 iterations, unless the recordings is opened using the EventStream or RecordingStream API, which is not the case with the 'jfr' command.

https://github.com/openjdk/jdk/blob/0599a05f8c7e26d4acae0b2cc805a65bdd6c6f67/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/RecordingInput.java#L451

**Comment by YaSuenag** [comment]
@egahlin I pushed new commit to this PR. How about this? It adds loop limit like `RecordingInput::pollWait`.

I confirmed the recording file from Native Image has `0` in `flagByte` (it is called as `feature` in HotSpot) - so root cause of the hang is `metadataPosition` is zero (we can see it in UL). This change can avoid infinite loop in that case.

**Comment by egahlin** [comment]
> @egahlin I pushed new commit to this PR. How about this? It adds loop limit like `RecordingInput::pollWait`.
> 
> I confirmed the recording file from Native Image has `0` in `flagByte` (it is called as `feature` in HotSpot) - so root cause of the hang is `metadataPosition` is zero (we can see it in UL). This change can avoid infinite loop in that case.

This will break event streaming where we might need to spin indefinitely, or at least much longer than a few seconds. If the metadata offset has not been written by the JVM, we need to wait for it. Every recording chunk must have a metadata section for it to be parsable.

In the bug you write "I passed invalid file which are in JFR repository of GraalVM Native Image". 

Did you do this on a live process, or did you copy the recording file out? 

If it is live, the metadata position should be written eventually, or there is a bug when it is written, and should be fixed there.

If you copied the recording file out yourself, while it is being written, and passed it to 'jfr print', that is not supported.  When you copy using the OS, your are not following the protocol where you need to inspect the FILE_STATE.

**Comment by YaSuenag** [comment]
`ChunkHeader::refresh` need to satisfy to exit loop following conditions:

* File state is "stable" (get same state twice (L123 and L131))
* `metadataPosition` is not (greater than) 0

`fileState1` comes from `readFileState()` which uses `pollWait()` as you mentioned, so we can deem the recording data is "stable" if L134 is true.

```java
123             byte fileState1 = readFileState();
 :
131             byte fileState2 =  input.readPhysicalByte();
132             input.positionPhysical(absoluteChunkStart + FLAG_BYTE_POSITION);
133             int flagByte = input.readPhysicalByte();
134             if (fileState1 == fileState2) { // valid header
135                 finished = fileState1 == 0;
136                 if (metadataPosition != 0) {
 :
164                     return;
165                 }
```

In addition, we can deem that recording data would not be updated if `finished` is set to `true` in L135. Thus I think we can fix this problem with following patch. How about this?

```diff
diff --git a/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java b/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
index 8c8ec55f0da..8648c030f06 100644
--- a/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
+++ b/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
@@ -162,6 +162,8 @@ public final class ChunkHeader {
                     Logger.log(LogTag.JFR_SYSTEM_PARSER, LogLevel.INFO, "Chunk: finalChunk=" + finalChunk);
                     absoluteChunkEnd = absoluteChunkStart + chunkSize;
                     return;
+                } else if (finished) {
+                    throw new IOException("metadataPosition is 0 but chunk header is valid.");
                 }
             }
         }
```

I understand that producer (Native Image in this case) should be fixed not to out invalid recording file. However we need to notify errors when the user passes invalid file to jfr command. So I've proposed this to jdk project.

**Comment by egahlin** [comment]
> diff --git a/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java b/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
> index 8c8ec55f0da..8648c030f06 100644
> --- a/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
> +++ b/src/jdk.jfr/share/classes/jdk/jfr/internal/consumer/ChunkHeader.java
> @@ -162,6 +162,8 @@ public final class ChunkHeader {
>                      Logger.log(LogTag.JFR_SYSTEM_PARSER, LogLevel.INFO, "Chunk: finalChunk=" + finalChunk);
>                      absoluteChunkEnd = absoluteChunkStart + chunkSize;
>                      return;
> +                } else if (finished) {
> +                    throw new IOException("metadataPosition is 0 but chunk header is valid.");
>                  }
>              }
>          }
> ```
> 

This may work, values are read reliably and when a chunk is finished, it should always have metadata section, or something is wrong with the file. 

That said, when the file format was designed the metadata pointer in the header was meant as a hint (not a mandatory thing) to prevent a parser for reading the file twice. Neither JMC or JDK parser supports reading recordings without the metadata pointer hint AFAIK, so that ship may have sailed. If the use case should arrive, the ChunkHeader class must be modified anyway (and the above check replaced with an iteration over all the events to find the offset). 

Have you looked at the HotSpot implementation to make sure fileState is never 0, unless the metadata pointer hint has been written? If I remember correctly, the initial value is 1, but I haven't checked. I looked at the RemoteRecordingStream class and it looks like it can't happen there, if the output from the JVM is OK.

I think the message could be "No metadata event found in finished chunk".

**Comment by egahlin** [comment]
> In JfrChunkWriter.cpp, the file state is always set to `0` when a chunk is finalized.
> 
> ```c++
> 101   void write_generation(bool finalize) {
> 102     _writer->be_write(finalize ? COMPLETE : _chunk->generation());
> 103     _writer->be_write(PAD);
> 104   }
> 105
> 106   void write_next_generation(bool finalize) {
> 107     _writer->be_write(finalize ? COMPLETE : _chunk->next_generation());
> 108     _writer->be_write(PAD);
> 109   }
> ```

And the initial value is 1. 
https://github.com/openjdk/jdk/blob/0ca74f538e1a8a351cc0631c5fe397a74653ce6f/src/hotspot/share/jfr/recorder/repository/jfrChunk.cpp#L69

**Review by egahlin — APPROVED** [review]

**Comment by YaSuenag** [comment]
Can I get second reviewer?

**Comment by egahlin** [comment]
> Can I get second reviewer?

The change is trivial, even though interaction with other parts of JFR is not. I have run your code with all the JFR tests 200 times without failure. I would push it. You are unlikely to get additional input on this.

**Pull request closed without merging**
