### PR TITLE
8305461: [vectorapi] Add VectorMask::xor

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

This patch adds `VectorMask.xor` to the public interface of `VectorMask`. This method has already been existed in each concrete mask classes.

Please kindly review.
Thanks a lot.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8305494](https://bugs.openjdk.org/browse/JDK-8305494) to be approved

### Issues
 * [JDK-8305461](https://bugs.openjdk.org/browse/JDK-8305461): [vectorapi] Add VectorMask::xor
 * [JDK-8305494](https://bugs.openjdk.org/browse/JDK-8305494): [vectorapi] Add VectorMask::xor (**CSR**)

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13277/head:pull/13277` \
`$ git checkout pull/13277`

Update a local copy of the PR: \
`$ git checkout pull/13277` \
`$ git pull https://git.openjdk.org/jdk.git pull/13277/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13277`

View PR using the GUI difftool: \
`$ git pr show -t 13277`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13277.diff">https://git.openjdk.org/jdk/pull/13277.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13277#issuecomment-1494781759)

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
Thank you for doing this. I am guessing it was always intended to be public but was not spotted in previous reviews.

**Comment by merykitty** [comment]
@PaulSandoz Thanks for your timely review, do I need a second review for this patch?

**Comment by PaulSandoz** [comment]
> @PaulSandoz Thanks for your timely review, do I need a second review for this patch?

No need for another reviewer.

**Comment by eirbjo** [comment]
Hello @merykitty,

I'm observing GHA test failure in `jdk/incubator/vector/ShortMaxVectorTests` on `linux-x86` (jdk master):

```
test ShortMaxVectorTests.sliceShortMaxVectorTestsMasked(short[-i * 5], short[i + 1], mask[true]): failure
java.lang.AssertionError: arrays differ firstly at element [16]; expected value is <12> but was <1>. (ref: [-135, -140, -145, -150, -155, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], res: [-135, -140, -145, -150, -155, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), at index #0, at origin #27
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.assertEquals(Assert.java:275)
	at ShortMaxVectorTests.assertArraysEquals(ShortMaxVectorTests.java:854)
	at ShortMaxVectorTests.sliceShortMaxVectorTestsMasked(ShortMaxVectorTests.java:4812)
```

Could this be caused by changes in this PR?

See https://github.com/eirbjo/jdk/actions/runs/4707493730#user-content-jdk_incubator_vector_shortmaxvectortests

**Pull request closed without merging**
