### PR TITLE
8329749: Obsolete the unused UseNeon flag

### PR DESCRIPTION
**Pull request by TobiHartmann**
After [JDK-8328264](https://bugs.openjdk.org/browse/JDK-8328264), the UseNeon flag is only used by JVMCI code and @dougxc confirmed that it can be removed.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8329753](https://bugs.openjdk.org/browse/JDK-8329753) to be approved

### Issues
 * [JDK-8329749](https://bugs.openjdk.org/browse/JDK-8329749): Obsolete the unused UseNeon flag (**Enhancement** - P4)
 * [JDK-8329753](https://bugs.openjdk.org/browse/JDK-8329753): Obsolete UseNeon (**CSR**)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [5d8119ab](https://git.openjdk.org/jdk/pull/18648/files/5d8119abefcc0958cce949247e8232c5319aa304)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [5d8119ab](https://git.openjdk.org/jdk/pull/18648/files/5d8119abefcc0958cce949247e8232c5319aa304)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18648/head:pull/18648` \
`$ git checkout pull/18648`

Update a local copy of the PR: \
`$ git checkout pull/18648` \
`$ git pull https://git.openjdk.org/jdk.git pull/18648/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18648`

View PR using the GUI difftool: \
`$ git pr show -t 18648`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18648.diff">https://git.openjdk.org/jdk/pull/18648.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18648#issuecomment-2039219313)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks, Christian!

**Review by chhagedorn — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Good

**Comment by altrisi** [comment]
Should the `UseNeon` enum constant this code referenced be removed too?

https://github.com/openjdk/jdk/blob/5d8119abefcc0958cce949247e8232c5319aa304/src/jdk.internal.vm.ci/share/classes/jdk/vm/ci/aarch64/AArch64.java#L191-L193

**Comment by TobiHartmann** [comment]
> Should the `UseNeon` enum constant this code referenced be removed too?

Good catch. Removed as well.

**Comment by TobiHartmann** [comment]
Thanks for the reviews, @vnkozlov, @altrisi!

**Review by theRealAph — APPROVED** [review]

**Comment by TobiHartmann** [comment]
Thanks for the review, Andrew.

**Pull request closed without merging**
