### PR TITLE
8296263: Uniform APIs for using archived heap regions

### PR DESCRIPTION
**Pull request by ashu-mehra**
This is an attempt to unify the two different approaches for using archived heap regions. Main goal is to restructure and modify the code to have a single set of GC APIs that can be called for using archived heap regions.

In current state, the VM either tries to "map" (for G1) or "load" (for non-G1 GC policies) the archived heap regions into the java heap.
When mapping, the VM determines the address range in the java heap where the archived regions should be mapped. It tries to map the regions towards the end of the heap. The APIs used for this purpose are G1 specific.
When loading, the VM asks the GC to provide a chunk of memory from the heap, into which it reads the contents of the archived heap regions. The APIs used are GC policy agnostic but challenging to use for region based collectors.

This PR attempts to add new set of GC APIs that can be used by the VM to reserve space in the heap for mapping the archived heap regions. It combines the good parts of the two existing approaches. Similar to the "loading" API, in this new approach VM is not responsible for determining the mapping address. That responsibility always resides with the GC policy. This also allows the flexibility for the GC implementation to decide where and how to reserve the space for the archived regions. For instance, G1 implementation can continue to attempt to allocate the space towards the end of the heap.
This PR also provides the implementation of the new APIs for all the existing GC policies that currently support archived heap regions viz G1, serial, parallel and epsilon.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296263](https://bugs.openjdk.org/browse/JDK-8296263): Uniform APIs for using archived heap regions

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10970/head:pull/10970` \
`$ git checkout pull/10970`

Update a local copy of the PR: \
`$ git checkout pull/10970` \
`$ git pull https://git.openjdk.org/jdk pull/10970/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10970`

View PR using the GUI difftool: \
`$ git pr show -t 10970`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10970.diff">https://git.openjdk.org/jdk/pull/10970.diff</a>

</details>

### CODE REVIEW

**Comment by ashu-mehra** [comment]
I understand reviewing all the changes together can be challenging. So I have tried to segregate the changes into different commits. I guess reviewing individual commits in the commit order should make it a bit easier.

**Comment by iklam** [comment]
Hi Ashutosh, I've been trying out your patch and reading the code. So far, I found a few problems:

- With debug VM, `java -Xlog:cds -XX:+UseSerialGC --version` spends a long time at VM exit to verify the heap
- I cannot run the jtreg tests with a fastdebug or slowdebug VM in agentvm mode. I.e., `jtreg .... -agentvm HelloTest.java`. Product VM works fine in agentvm mode.
- These two test cases crash with a product VM:
  - runtime/cds/appcds/javaldr/GCSharedStringsDuringDump.java
  - runtime/cds/appcds/sharedStrings/SharedStringsStress.java

**Comment by ashu-mehra** [comment]
@iklam thanks for taking a look at the patches and trying them out.

> With debug VM, java -Xlog:cds -XX:+UseSerialGC --version spends a long time at VM exit to verify the heap

ah right! I too observed this locally but somehow missed my radar. I need to check what's going on there.

> These two test cases crash with a product VM:
> - runtime/cds/appcds/javaldr/GCSharedStringsDuringDump.java
> - runtime/cds/appcds/sharedStrings/SharedStringsStress.java

I can recreate these failures locally with fastdebug build as well. Looking at them right now.

**Comment by iklam** [comment]
By the way, one enhancement that I've been considering (which will be independent of this PR) is to remove the dependency on G1 for writing the archived heap. I've created https://bugs.openjdk.org/browse/JDK-8296344

**Comment by ashu-mehra** [comment]
I think I figured out the reason for crashes with `SharedStringsStress.java` and `GCSharedStringsDuringDump.java` tests.
In the implementation for G1 the regions are allocated one after the other, without taking into account the gap that may have existed between the regions at the dump time. This can result in an object spanning across two G1 regions.

For instance, if there are two regions at dump time (denoted by `X` and `Y`) and the first region occupies one G1 region R1 and  the second region occupies two G1 regions - R2 and R3, then they would be represented at dump time as:
```
    R1         R2         R3         R4
     |XXXXXX    |YYYYYYYYYY|YYYYYYYYYY|
```
The blank space towards the end of R1 denotes the region is not fully occupied.

At run time these would be mapped as follows:

```
    R1         R2         R3         R4
     |XXXXXXYYYY|YYYYYYYYYY|YYYYYY    |
```

At dump time the objects are all within a region. But at run time, it is possible for an object near the region boundary to overflow into next region. If that happens we would the assertion `assert(next_addr == top())` in `HeapRegion::update_bot()`.

**Comment by ashu-mehra** [comment]
I am thinking this situation of object overflowing to next region can happen in earlier G1 implementation as well if the G1 region size is different at run time than at dump time.
Taking the above example, if the G1 region size at run time is 1.5x the region size at dump time, then we would end up with some thing like this:

```
    R1               R2              R3
     |XXXXXX     YYYYY|YYYYYYYYYYYYYYY|
```

So there is a chance that the object towards the end of R1 may overflow into R2.
Unless I missed something, it looks like this is a potential issue in earlier implementation as well.

**Comment by iklam** [comment]
I am not sure if the existing implementation is 100% correct, but for these test cases, I think we are probably saved by this code: 

```
  if (!is_aligned(relocated_closed_heap_region_bottom, HeapRegion::GrainBytes)) {
    // Align the bottom of the closed archive heap regions at G1 region boundary.
    // This will avoid the situation where the highest open region and the lowest
    // closed region sharing the same G1 region. Otherwise we will fail to map the
    // open regions.
    size_t align = size_t(relocated_closed_heap_region_bottom) % HeapRegion::GrainBytes;
    delta -= align;
    log_info(cds)("CDS heap data needs to be relocated lower by a further " SIZE_FORMAT
                  " bytes to " INTX_FORMAT " to be aligned with HeapRegion::GrainBytes",
                  align, delta);
    set_shared_heap_runtime_delta(delta);
    relocated_closed_heap_region_bottom = heap_region_runtime_start_address(si);
    _heap_pointers_need_patching = true;
  }
```

G1 regions are at least 1MB, and are always a power of 2.

By patching SharedStringsStress.java with this, I can get the CA1 and OA0 regions to be not aligned by GrainBytes, but that doesn't seem to cause the test to fail.

```
-                TestCommon.concat(vmOptionsPrefix, "HelloString"));
+                TestCommon.concat(vmOptionsPrefix, "-Xlog:cds=debug", "-Xmx6g", "HelloString"));
```

In any case, I think we can consider first changing the way the regions are written ([JDK-8296344](https://bugs.openjdk.org/browse/JDK-8296344)) so that they can be more easily mapped by various collectors.

(Also, tactically, we should probably first change G1 to use the new "Uniform API" you are thinking about, but leave the other collectors unchanged. This way, we can gradually test things out and fix the other collectors in subsequent RFEs).

Currently, when writing the archived heap, we allocate a G1 region and write objects into it, from bottom to top. When it fills up, we allocate another G1 region that's immediately below, and start filing it from bottom to top. At the end, we merge all the fully-filled regions into the CA0 region, and make the last, half-filled region CA1.

(Same for the OA0, OA1 regions, but usually the OA0 region never has more than 1MB objects, so we'd never have the OA1 region).

This is kind of kludgy. We should be able to first determine all objects to be archived, and then write them out a single contiguous "closed" region, and a single contiguous "open" region. When filling out these regions, we can pack the objects so that they will never cross a 1MB boundary.

Also, I think it may not even be worthwhile to have the "closed" region and treat it specially at runtime. We can have just a single contiguous block of archived objects like this, where S are the String objects and their char arrays, and O are the other types of objects

```
OOOOOOOOOOOSSSSSSSSSSS
```

At runtime, we allocate enough G1 regions from the top of the heap to accommodate the archived objects, and put a dummy object at the bottom to fix the bottom-most region.

(The reason we align the archived regions to the top of the G1 heap is the top of the heap usually have the same narrowOop for various heap sizes, so we can usually avoid patching the embedded oop pointers.

This is a trade off with other collectors, which may not allow you to start allocating memory from the top. We may want to reconsider this.)

All the Strings are always in the interned table so they will never be collected. Also, we already computed their hashcode, so they are never written into (unless you `synchronize` on them at runtime). So for the region(s) that contain only the S objects, 
we can effectively share the memory across multiple processes, and the GC will never collect them.

Anyway, we usually just have a few MBs of archived objects, so it may not matter whether we keep them immutable or not.
*******

I want to thank you for starting working in this area. Going forward, I think we need more discussion and design before we can decide exactly what to do.

**Comment by ashu-mehra** [comment]
@iklam thanks for sharing the information and details on the future work in this space.

> By patching SharedStringsStress.java with this, I can get the CA1 and OA0 regions to be not aligned by GrainBytes, but that doesn't seem to cause the test to fail.

I was actually referring to CA0 and CA1 in my figures (which I realized was not clear in my explanation earlier). 
Anyway, I now understand the existing mechanism works fine because the following conditions are maintained (which you have already mentioned in your comment):
1. G1 regions are at least 1MB, and are always a power of 2.
2. At dump time the objects are placed such that they do not cross `HeapRegion::min_region_size_in_words()` which I believe is 1M.

Because of these two constraints, change in G1 region size at run time cannot result in objects crossing the region boundary.
So if I update the G1 code such that at run time the regions are mapped at 1M boundary then I can get rid of the problem of objects crossing region boundary and the two tests also pass.

> In any case, I think we can consider first changing the way the regions are written ([JDK-8296344](https://bugs.openjdk.org/browse/JDK-8296344)) so that they can be more easily mapped by various collectors.

I agree ([JDK-8296344](https://bugs.openjdk.org/browse/JDK-8296344)) would make it easier to map them at run time and would be happy to contribute to it anyway possible. But again, that's a GC policy specific implementation detail. 
I guess you would agree we need to de-couple the CDS code from the GC policy details. While JDK-8296344 aims at decoupling the code at dump time, my aim with this PR is to achieve the same at run time by having GC-agnostic APIs. 
Moreover, the dump time mechanism should not affect the APIs used for mapping regions at run time (though the implementation may need to be adjusted).
So, with this in mind do you think we can continue working on this PR, or do you believe the GC APIs this PR proposes to add would not be sufficient once JDK-8296344 is implemented?

> (Also, tactically, we should probably first change G1 to use the new "Uniform API" you are thinking about, but leave the other collectors unchanged. This way, we can gradually test things out and fix the other collectors in subsequent RFEs).

That makes sense. Ideally I should have done the implementation for other collectors in a separate RFEs. But I was worried if I the new APIs are flexible enough to support other non-G1 policies, and in an attempt to verify that I added the support for those policies as well. If it helps I can remove those commits and deliver them later in subsequent RFEs.

**Comment by iklam** [comment]
> While JDK-8296344 aims at decoupling the code at dump time, my aim with this PR is to achieve the same at run time by having GC-agnostic APIs. Moreover, the dump time mechanism should not affect the APIs used for mapping regions at run time (though the implementation may need to be adjusted).

I think it depends on how we want to change the dump time operations. If we decide to go with a single contiguous block, then the API for mapping this block into the runtime heap will look very different than what you have today:

```
bool ArchiveHeapLoader::get_heap_range_for_archive_regions(ArchiveHeapRegions* heap_regions, bool is_open) {
  if (Universe::heap()->alloc_archive_regions(heap_regions->dumptime_regions(),
                                           heap_regions->num_regions(),
                                           heap_regions->runtime_regions(),
                                           is_open)) {
```

Also, we should probably record the region boundary information in the archived objects. Something like "objects never span across 1MB boundaries". This may need to be passed to the runtime mapping API, so incompatible collectors (i.e., one uses 512KB regions) can reject the archived objects.

One of my goal for JDK-8296344 is to optimize the archived objects for the collector chosen at dump time. For example, if you dump with SerialGC, the archived objects can be mapped efficiently without relocation when SerialGC is also chosen at run time, but may require relocation if G1 is chosen at run time. I am not sure if how this would affect the runtime mapping API. Maybe some sort of preference would need to be indicated.

I think it would be best for us to think about the whole picture before committing to a design. Timing wise, I think we missed the JDK 20 release anyway, so we should have plenty time to come up with a good design for JDK 21.

I also would like to hear from folks in our GC team. @tschatzl @stefank

**Comment by tschatzl** [comment]
Some additional initial notes about the code:

* please document the new APIs in `CollectedHeap` (something like "// Support for mapping archive regions into the heap" for 6 methods is not sufficient) - it would also help reviewing.
Particularly something like `heap_region_dealloc_supported()` needs some kind of exact specification.
Also return values that are not obvious should be documented.
* also we should be careful with the naming as the term "region" is overloaded enough already; e.g.  `heap_region_dealloc_supported` seems to miss an `archive`.
* while we are at changing the API, please use proper types, i.e. unsigned ints/size_t for sizes.
* actually I would suggest to use the term "ranges" instead of regions for the areas/MemRegions from the archive. This would help a lot with code clarity in collectors that already use the term regions.
* similar to @iklam I strongly suggest splitting this change by collector anyway. There will likely be considerable changes on top of your current stack of changes which may require working/reviewing on the tip.

**Review by tschatzl — CHANGES_REQUESTED** [review]
Some additional initial notes about the code:

* please document the new APIs in `CollectedHeap` (something like "// Support for mapping archive regions into the heap" for 6 methods with tons of parameters is not sufficient) - it would also help reviewing.
* also we should be careful with the naming as the term "region" is overloaded enough already; e.g.  `heap_region_dealloc_supported` seems to miss an `archive`.
* while we are at changing the API, the change should use appropriate types, i.e. unsigned ints/size_t for sizes.
* there is quite a bit inconsistency in the naming: sometimes the MemRegions are called "something_regions", sometimes "something_ranges", there is also "something_spaces"; the same with the associated counts that are sometimes called "count", and sometimes "num_regions".

Summarizing all this, I would strongly suggest to use the term "ranges" instead of regions for the areas/MemRegions from the archive. This would help a lot with code clarity in collectors that already use the term regions.

Similar to @iklam I strongly suggest splitting this change by collector (or at least basic+g1 and epsilon/serial/parallel) anyway. There will likely be considerable changes on top of your current stack of changes which may require working/reviewing on the tip.

There are additional initial comments in the PR. I understand that some of them may become obsolete as we change the API.

I did not really look at dumptime considerations which seem to be under discussion right now; I do not have the overview about the exact requirements/problems in that area, particularly with regards to JDK-8296344.
The chosen API (and the intended execution flow during dump/runtime) is underdocumented at the moment to give good comments. It would be nice to summarize that to start a discussion; maybe even discuss this on some mailing list instead in the PR of a 2k LOC change.

However, from the existing commetns here, I do think it is a good idea to write out all chosen assumptions when dumping (e.g. the alignment boundary of 1MB), even if currently that is the minimum for all collectors.

**Comment by ashu-mehra** [comment]
@tschatzl thanks for reviewing the PR. Given that JDK-8296344 is likely to affect this PR and there are still details to be figured out and finalized for the dumping, I guess its best to put this on hold for now. Once we have the details sorted out, I can resurrect this patch if required.

**Comment by ashu-mehra** [comment]
@iklam you mentioned [here](https://github.com/openjdk/jdk/pull/10970#issuecomment-1302600242) that you were not able to run the tests with -agentvm option using fastdebug build. Its a long shot but I am wondering if you still remember what error you were getting and which tests you were running.

I recently tried running in agentvm mode with this PR and tests ran fine. The command I used was:

`java -jar <path to jtreg.jar> -agentvm -verbose:all -jdk:<path to jdk to test> test/hotspot/jtreg:hotspot_cds`

Some tests (like `runtime/cds/appcds/jvmti/ClassFileLoadHookTest.java`) had this error `Use -nativepath to specify the location of native code` but I see the error without this patch as well.

**Comment by iklam** [comment]
> @iklam you mentioned [here](https://github.com/openjdk/jdk/pull/10970#issuecomment-1302600242) that you were not able to run the tests with -agentvm option using fastdebug build. Its a long shot but I am wondering if you still remember what error you were getting and which tests you were running.

I lots my old build so I rebuilt from version [565e6ff](https://github.com/openjdk/jdk/pull/10970/commits/565e6ffd68d67a94a3ffff76734005492b98dd9d) and I couldn't reproduce the problem anymore. Maybe I had a glitch in my build. Sorry for the noise.

**Comment by ashu-mehra** [comment]
> I lots my old build so I rebuilt from version [565e6ff](https://github.com/openjdk/jdk/pull/10970/commits/565e6ffd68d67a94a3ffff76734005492b98dd9d) and I couldn't reproduce the problem anymore. Maybe I had a glitch in my build. Sorry for the noise.

@iklam no worries, thanks for checking again and clarifying it up.

**Pull request closed without merging**
