### PR TITLE
8342376: More reliable OOM handling in ExceptionDuringDumpAtObjectsInitPhase test

### PR DESCRIPTION
**Pull request by shipilev**
Found a test bug while testing [JDK-8341913](https://bugs.openjdk.org/browse/JDK-8341913) with Shenandoah. For OOM testing, the test fills out the heap with large arrays and then attempts to allocate a smaller array.

That allocation almost always succeeds with Shenandoah. Actually, it succeeds with other GCs as well, it just so happens that other GCs throw OOM with "GC overhead limit exceeded".

Plus, some allocations should be sinked to avoid dead-code elimination.

Additional testing:
 - [x] Linux x86_64 server fastdebug, test now passes reliably with JDK-8341913 and Shenandoah
 - [x] Linux x86_64 server fastdebug, test with {Serial, Parallel, G1, Shenandoah}, 50 times

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342376](https://bugs.openjdk.org/browse/JDK-8342376): More reliable OOM handling in ExceptionDuringDumpAtObjectsInitPhase test (**Bug** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21536/head:pull/21536` \
`$ git checkout pull/21536`

Update a local copy of the PR: \
`$ git checkout pull/21536` \
`$ git pull https://git.openjdk.org/jdk.git pull/21536/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21536`

View PR using the GUI difftool: \
`$ git pr show -t 21536`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21536.diff">https://git.openjdk.org/jdk/pull/21536.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21536#issuecomment-2416754903)

### CODE REVIEW

**Comment by shipilev** [comment]
@iklam, I think the original test is yours, take a look?

**Comment by iklam** [comment]
Can you describe which test failed with Shenandoah and how the fail? Is it this part of ExceptionDuringDumpAtObjectsInitPhase.java?

```
        System.out.println("2. OOM during dump");
        TestCommon.dump(appJar,
                        TestCommon.list(Hello.class.getName()),
                        "-XX:+UnlockDiagnosticVMOptions",
                        "-XX:+AllowArchivingWithJavaAgent",
                        "-javaagent:" + agentJar,
                        "-Dtest.with.oom=true",
                        "-Xlog:cds,class+load",
                        "-Xmx12M",
                        gcLog).shouldNotHaveExitValue(0)
                              .shouldContain("Out of memory. Please run with a larger Java heap, current MaxHeapSize");
```

> For OOM testing, the test fills out the heap with large arrays and then attempts to allocate a smaller array.

The test keeps allocating with no catch for OOM. Shouldn't this always fail?

```
            if (TEST_WITH_OOM) {
                // fill until OOM
                System.out.println("Fill objects until OOM");
                for (;;) {
                    waste.add(new byte[64*1024]);
                }
            }
```

The test does not expect an OOM from the following block. The purpose of this is just to make so allocation. When done enough times (hundreds of classes are loaded during dump time), we will have executed some GCs. The purpose is to make sure that the CDS code uses Handles correctly to avoid holding onto dead oops.

```
            try {
                makeGarbage();
            } catch (Throwable t) {
```

**Comment by shipilev** [comment]
> Can you describe which test failed with Shenandoah and how the fail?

Looking deeper at this, I think the test is flaky through a different mechanism. The OOM that test wants to catch here:
https://github.com/openjdk/jdk/blob/d4f0ba73f653a3886b17f283b9b6a92db1af52aa/src/hotspot/share/cds/metaspaceShared.cpp#L664-L667

...comes from some other place, since we eat all exceptions from `ClassTransformer.transform` here:
https://github.com/openjdk/jdk/blob/d4f0ba73f653a3886b17f283b9b6a92db1af52aa/src/java.instrument/share/classes/sun/instrument/TransformerManager.java#L195-L198

I suspect there is some other allocation outside the transformer code gets the second "GC limit exceeded" OOM while allocating. Shenandoah does not handle GC limits, so it just happily allocates. Now, if we allocate 64K arrays in `Fill objects until OOM` block, OOM there, this means we still have 64KB of runway to work with. I believe this is enough for Shenandoah to complete the test without OOM. If I do just this:

```
-                    waste.add(new byte[64*1024]);
+                    waste.add(new byte[32*1024]);
```

Tests starts to pass with Shenandoah, which means 32KB free space was not enough to fly through the rest of the code.

I'll look again tomorrow.

**Review by iklam — APPROVED** [review]
LGTM

**Comment by shipilev** [comment]
Thank you! I think I need another Reviewer for this one.

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
