### PR TITLE
8318608: Enable parallelism in vmTestbase/nsk/stress/threads tests

### PR DESCRIPTION
**Pull request by elifaslan1**
The commit includes changes to unblock parallelism for more `hotspot:tier4` tests. in `test/hotspot/jtreg/vmTestbase/nsk/stress/thread `tests.

Below are the before and after test run comparisons:

Before:
 time,count
   15,    1
   33,    1
   48,    1
   66,    1
   72,    1
   77,    1

Mean                51.83s
Standard deviation  22.24s
Total elapsed time 1m 17s

After:
 time,count
   19,    1
   23,    1
   29,    1
   34,    1
   48,    1
   53,    1

Mean                34.33s
Standard deviation  12.43s
Total elapsed time 0m 53s

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318608](https://bugs.openjdk.org/browse/JDK-8318608): Enable parallelism in vmTestbase/nsk/stress/threads tests (**Enhancement** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16327/head:pull/16327` \
`$ git checkout pull/16327`

Update a local copy of the PR: \
`$ git checkout pull/16327` \
`$ git pull https://git.openjdk.org/jdk.git pull/16327/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16327`

View PR using the GUI difftool: \
`$ git pr show -t 16327`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16327.diff">https://git.openjdk.org/jdk/pull/16327.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16327#issuecomment-1776135667)

### CODE REVIEW

**Comment by elifaslan1** [comment]
@lmesnik could you please test this to your system and report the results? TIA

**Review by lmesnik — APPROVED** [review]
Looks good. Testing passed.

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
