### PR TITLE
8280949: Correct the references for the Java Security Standard Algorithm Names specification

### PR DESCRIPTION
**Pull request by XueleiFan**
In the JSSE specification, the reference to "Java Security Standard Algorithm Names" specification is documented as "Java Cryptography Architecture Standard Algorithm Name Documentation".  As should be corrected.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280949](https://bugs.openjdk.java.net/browse/JDK-8280949): Correct the references for the Java Security Standard Algorithm Names specification

### Reviewers
 * [Sean Mullan](https://openjdk.java.net/census#mullan) (@seanjmullan - **Reviewer**) ⚠️ Review applies to 9f75163bdb9605ef86d5c0a6db1567fa02f09ad4

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7290/head:pull/7290` \
`$ git checkout pull/7290`

Update a local copy of the PR: \
`$ git checkout pull/7290` \
`$ git pull https://git.openjdk.java.net/jdk pull/7290/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7290`

View PR using the GUI difftool: \
`$ git pr show -t 7290`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7290.diff">https://git.openjdk.java.net/jdk/pull/7290.diff</a>

</details>

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]
Please capitalize "specification"  (i.e. "Specification")  to be consistent with other references in the javadoc. Looks good otherwise.

**Comment by XueleiFan** [comment]
> Please capitalize "specification" (i.e. "Specification") to be consistent with other references in the javadoc. Looks good otherwise.
OK.  Just curious, why we want to use capitalized "specification"?  This word "specification" is not a part of the document title.

**Comment by seanjmullan** [comment]
> > Please capitalize "specification" (i.e. "Specification") to be consistent with other references in the javadoc. Looks good otherwise.
> 
> OK. Just curious, why we want to use capitalized "specification"? This word "specification" is not a part of the document title.

True (although in hindsight we could have added it to the title). However, I think capitalizing when referencing it signifies that it is an important and normative document, similar to when you refer to standard documents even if it is not in title (ex: "The AES Standard"). If we referred to it again in subsequent text, then it is not as necessary, i.e. you could say "This specification includes list of names that are defined as standard ...

**Comment by XueleiFan** [comment]
> > > Please capitalize "specification" (i.e. "Specification") to be consistent with other references in the javadoc. Looks good otherwise.
> > 
> > 
> > OK. Just curious, why we want to use capitalized "specification"? This word "specification" is not a part of the document title.
> 
> True (although in hindsight we could have added it to the title). However, I think capitalizing when referencing it signifies that it is an important and normative document, similar to when you refer to standard documents even if it is not in title (ex: "The AES Standard"). If we referred to it again in subsequent text, then it is not as necessary, i.e. you could say "This specification includes list of names that are defined as standard ...

Good point!  Thank you!

**Pull request closed without merging**
