### PR TITLE
8260923: Add more tests for SSLSocket input/output shutdown

### PR DESCRIPTION
**Pull request by akolarkunnu**
There is a lack of tests in the area of  java.net.Socket.shutdownInput() and java.net.Socket.shutdownOutput() , so added more tests in this area of with different TLS versions. Please review.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260923](https://bugs.openjdk.java.net/browse/JDK-8260923): Add more tests for SSLSocket input/output shutdown

### Reviewers
 * [Sean Coffey](https://openjdk.java.net/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2745/head:pull/2745` \
`$ git checkout pull/2745`

Update a local copy of the PR: \
`$ git checkout pull/2745` \
`$ git pull https://git.openjdk.java.net/jdk pull/2745/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2745`

View PR using the GUI difftool: \
`$ git pr show -t 2745`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2745.diff">https://git.openjdk.java.net/jdk/pull/2745.diff</a>

</details>

### CODE REVIEW

**Comment by akolarkunnu** [comment]
@coffeys

**Comment by coffeys** [comment]
Thanks for increasing code coverage here. Looks fine to me.

**Review by coffeys — APPROVED** [review]

**Pull request closed without merging**
