### PR TITLE
8340308: PassFailJFrame: Make rows default to number of lines in instructions

### PR DESCRIPTION
**Pull request by aivanov-jdk**
It has become quite common to use the following code

```java
.rows((int) INSTRUCTIONS.lines().count() + 1)
```

to set the number of rows for `PassFailJFrame`.

Make this the default value. Newer tests could drop `.rows` from builder configuration if the new default works well.

If a test needs customising the new default value, the newly added method `rowsAdd` could be used to increase the number of rows.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340308](https://bugs.openjdk.org/browse/JDK-8340308): PassFailJFrame: Make rows default to number of lines in instructions (**Enhancement** - P4)

### Reviewers
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - **Reviewer**)
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21039/head:pull/21039` \
`$ git checkout pull/21039`

Update a local copy of the PR: \
`$ git checkout pull/21039` \
`$ git pull https://git.openjdk.org/jdk.git pull/21039/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21039`

View PR using the GUI difftool: \
`$ git pr show -t 21039`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21039.diff">https://git.openjdk.org/jdk/pull/21039.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21039#issuecomment-2355878215)

### CODE REVIEW

**Comment by aivanov-jdk** [comment]
There are currently 29 tests which use `.rows((int) INSTRUCTIONS.lines().count() + 1)` to set the number of rows.

Another set of tests uses `+ 2` instead, the number of such tests is 24.

You can get the list of files using these commands:

```bash
grep --recursive --files-with-matches --perl-regexp '\.rows\(\(int\).*\.lines\(\)\.count\(\).*\+.*1.*\)' test/jdk
grep --recursive --files-with-matches --perl-regexp '\.rows\(\(int\).*\.lines\(\)\.count\(\).*\+.*2.*\)' test/jdk
```

Two tests added in #20996 use `+ 5`.

**Review by honkar-jdk — APPROVED** [review]
LGTM, eliminates the need to specify `.rows((int) INSTRUCTIONS.lines().count() + 1)` if the default no. of rows works for the test.

**Review by azvegint — APPROVED** [review]
As another improvement, we can also consider calculating the default number of columns (based on the widest string?) in a separate issue.

**Comment by aivanov-jdk** [comment]
> As another improvement, we can also consider calculating the default number of columns (based on the widest string?) in a separate issue.

Yes!

I added a comment in JBS:

> This is part of a larger effort for providing better defaults for sizing the instructions which is tracked by [JDK-8328163](https://bugs.openjdk.org/browse/JDK-8328163): *Implement automatic instruction sizing for `PassFailJFrame`*.

I quickly prototyped it in my [8328163-autoSize-passFail](https://github.com/aivanov-jdk/jdk/tree/8328163-autoSize-passFail) branch ([diff to master](https://github.com/openjdk/jdk/compare/master...aivanov-jdk:jdk:8328163-autoSize-passFail)) in March 2024, yet it proved to be not as simple.

I guess if we disable word-wrapping on `JTextArea`, it becomes simpler; yet some tests already depend on word-wrapping. I or anyone else have to come up with a clever heuristics which works good in most cases.

I thought about using something like this: disable word-wrapping and get text dimensions; if the width is too large (how large?), then enable word-wrapping and reduce the width of the text area, recalculate the preferred size again. If the height is too large (how large?), limit it to a value, the instructions are already in `JScrollPane`, yet it's best to avoid scroll bars — seeing all the instruction text is always better compared to having to scroll.

**Pull request closed without merging**
