### PR TITLE
JDK-8272065: jcmd cannot rely on the old core reflection implementation which will be changed after JEP 416

### PR DESCRIPTION
**Pull request by tstuefe**
`VM.metaspace`, `VM.classloaders` and `VM.class_hierarchy` all print out reflection invocation targets for delegating reflection class loaders. Post JEP 416 we don't use DelegatingClassLoaders anymore.

This patch removes the display of reflection targets from these commands as well as associated helper code and tests.

I don't have enough time atm to reimplement this feature using method handles. But at least we can remove the old code, and prepare the way for more code removal.

The patch does not touch vmClasses, `reflect_ConstructorAccessor` and `reflect_MethodAccessor` are both still there.

Tests: GHAs, manually testing the commands.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272065](https://bugs.openjdk.java.net/browse/JDK-8272065): jcmd cannot rely on the old core reflection implementation which will be changed after JEP 416

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6257/head:pull/6257` \
`$ git checkout pull/6257`

Update a local copy of the PR: \
`$ git checkout pull/6257` \
`$ git pull https://git.openjdk.java.net/jdk pull/6257/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6257`

View PR using the GUI difftool: \
`$ git pr show -t 6257`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6257.diff">https://git.openjdk.java.net/jdk/pull/6257.diff</a>

</details>

### CODE REVIEW

**Review by mlchung — APPROVED** [review]
Looks good to me.   Thanks for following this up.    The new implementation does not spin any new class loader and so I don't think jcmd needs to extend its support for the new implementation using method handles.

**Comment by tstuefe** [comment]
> Looks good to me. Thanks for following this up. The new implementation does not spin any new class loader and so I don't think jcmd needs to extend its support for the new implementation using method handles.

Thank you Mandy!

**Review by coleenp — APPROVED** [review]
Yes, looks good to me also.

**Review by dholmes-ora — APPROVED** [review]
I never realized we needed special handling for these classloaders so I'm glad to see this gone too.

Thanks,
David

**Comment by tstuefe** [comment]
Thanks @mlchung, @coleenp and @dholmes-ora.

/integrate

**Pull request closed without merging**
