### PR TITLE
8278885: Remove Windows ARM64 int8_t workaround in G1

### PR DESCRIPTION
**Pull request by aamarsh**
Please review this small change to revert a previous workaround that avoided an MSVC issue. 

This issue has now been fixed in VS 16.8 and higher. 

I also updated some documentation to reflect this change.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278885](https://bugs.openjdk.java.net/browse/JDK-8278885): Remove Windows ARM64 int8_t workaround in G1

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6872/head:pull/6872` \
`$ git checkout pull/6872`

Update a local copy of the PR: \
`$ git checkout pull/6872` \
`$ git pull https://git.openjdk.java.net/jdk pull/6872/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6872`

View PR using the GUI difftool: \
`$ git pr show -t 6872`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6872.diff">https://git.openjdk.java.net/jdk/pull/6872.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
GC changes look good.

**Comment by karianna** [comment]
> /sponser

I think it's _sponsor_

**Pull request closed without merging**
