### PR TITLE
8256417: Exclude TestJFRWithJMX test from running with PodMan

### PR DESCRIPTION
**Pull request by mseledts**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256417](https://bugs.openjdk.java.net/browse/JDK-8256417): Exclude TestJFRWithJMX test from running with PodMan

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2726/head:pull/2726`
`$ git checkout pull/2726`

### CODE REVIEW

**Comment by mseledts** [comment]
Please review this small change that excludes the TestJFRWithJMX test from execution on Podman.
In summary, this test requires capabilities that are not available under "rootless" podman.
What was done:
  - added an at-requires method to return the name of the container engine
  - using the above named at requires to exclude this test as described above

**Comment by mseledts** [comment]
@hseigel  @iignatev Could you please take a look?

**Comment by iignatev** [comment]
Hi Misha,

so this test can't be run w/ `podman` only if the test-user doesn't have root-level privileges? if so, I think it's better to check if we really don't have such priviliges and throw `SkippedException` (e.g. the same way we do in `SATestUtils` via `Platform.isRoot`). that way, the test will still be runnable in some configurations.

-- Igor

**Comment by mseledts** [comment]
Igor, thanks for the suggestion. I will update the code to use SkippedException and Platform.isRoot

**Comment by mseledts** [comment]
Igor, while following your suggestion of using jtreg.SkippedException, I am thinking about keeping the new VMProps.containerEngine() in the VMProps.java. It can come in handy in the future. I hope you do not mind that.

**Comment by mseledts** [comment]
I have updated the changes. @iignatev please review.

**Comment by iignatev** [comment]
> Igor, while following your suggestion of using jtreg.SkippedException, I am thinking about keeping the new VMProps.containerEngine() in the VMProps.java. It can come in handy in the future. I hope you do not mind that.

generally speaking, I am no fan of adding things we don't use. instead, I'd suggest you creating Platform::containerEngine (or better Container::engine) and it in the test. and if/when the needs for `@requiers container.engine` appears, we can add one w/ almost zero effort.

PS you need to update copyright year in all the updated files.

-- Igor

**Comment by mseledts** [comment]
OK, I will just remove the code from VMProps.

**Review by iignatev — APPROVED** [review]

**Comment by mseledts** [comment]
Thank you Igor.
/integrate

**Pull request closed without merging**
