### PR TITLE
8277342: vmTestbase/nsk/stress/strace/strace004.java fails with SIGSEGV  in InstanceKlass::jni_id_for

### PR DESCRIPTION
**Pull request by coleenp**
Use the version jni_id_for_impl() as jni_id_for() that takes out the JFieldIdCreation_lock before reading jni_ids in InstanceKlass.
Tested with mach5 tier1-3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277342](https://bugs.openjdk.java.net/browse/JDK-8277342): vmTestbase/nsk/stress/strace/strace004.java fails with SIGSEGV in InstanceKlass::jni_id_for

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 47cb164bdcc5d51a1b23f34d38766f2a9831562b
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6466/head:pull/6466` \
`$ git checkout pull/6466`

Update a local copy of the PR: \
`$ git checkout pull/6466` \
`$ git pull https://git.openjdk.java.net/jdk pull/6466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6466`

View PR using the GUI difftool: \
`$ git pr show -t 6466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6466.diff">https://git.openjdk.java.net/jdk/pull/6466.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
@coleenp - The original failure happened in Tier5...

**Comment by coleenp** [comment]
@dcubed-ojdk thanks Dan.  I'll rerun tier5 on our default platforms.

**Review by dholmes-ora — APPROVED** [review]
Hi Coleen,

The changes in themselves seem fine. My only concern is whether always locking will introduce contention and impact performance. The code was attempting the classic pattern of doing a lock-free query first, but as you note it lacks the necessary memory ordering operations. So if needed we could make the lock-free path work correctly.

Thanks,
David

**Comment by coleenp** [comment]
Thanks for reviewing.  I fixed the comments.  I will see if I can find some jni performance tests tomorrow.

**Review by hseigel — APPROVED** [review]
LGTM! Thanks for doing this.
Harold

**Comment by coleenp** [comment]
Thanks Harold and David.  I did run some startup and performance tests that might notice JNI (added link to bug for you) and there is no difference in performance.
/integrate

**Comment by coleenp** [comment]
I should have pointed out that tier5 also completed with no failures.

**Pull request closed without merging**
