### PR TITLE
8297385: Remove duplicated null typos in javadoc

### PR DESCRIPTION
**Pull request by dongxuwang**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8297385](https://bugs.openjdk.org/browse/JDK-8297385)

### Issue
 * [JDK-8297385](https://bugs.openjdk.org/browse/JDK-8297385): Remove duplicated null typo in javadoc ⚠️ Title mismatch between PR and JBS.

### Reviewers
 * [Yi Yang](https://openjdk.org/census#yyang) (@kelthuzadx - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11169/head:pull/11169` \
`$ git checkout pull/11169`

Update a local copy of the PR: \
`$ git checkout pull/11169` \
`$ git pull https://git.openjdk.org/jdk pull/11169/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11169`

View PR using the GUI difftool: \
`$ git pr show -t 11169`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11169.diff">https://git.openjdk.org/jdk/pull/11169.diff</a>

</details>

### CODE REVIEW

**Comment by kelthuzadx** [comment]
good catch, do you need a JBS issue for this?

**Comment by dongxuwang** [comment]
> good catch, do you need a JBS issue for this?

Thank you if you can help with that.

**Comment by kelthuzadx** [comment]
> > good catch, do you need a JBS issue for this?
> 
> Thank you if you can help with that.

I filed https://bugs.openjdk.org/browse/JDK-8297385 for this, you can change your title to [8297385: Remove duplicated null typo in javadoc](https://bugs.openjdk.org/browse/JDK-8297385), openjdk robot will guide you remaining processes.

**Comment by dongxuwang** [comment]
> > > good catch, do you need a JBS issue for this?
> > 
> > 
> > Thank you if you can help with that.
> 
> I filed https://bugs.openjdk.org/browse/JDK-8297385 for this, you can change your PR title and commit message to [8297385: Remove duplicated null typo in javadoc](https://bugs.openjdk.org/browse/JDK-8297385), OpenJDK robot will guide you remaining processes.

Thank you, can you also help review

**Review by kelthuzadx — APPROVED** [review]
This looks good, but I'm not a Reviewer, you still need an approval from Reviewer.

**Comment by dongxuwang** [comment]
> This looks good, but I'm not a Reviewer, you still need an approval from Reviewer.

Thanks

**Comment by dongxuwang** [comment]
Use #11311 instead, close this pr.

**Pull request closed without merging**
