### PR TITLE
JDK-8301462: Convert Permission files to use lambda after JDK-8076596

### PR DESCRIPTION
**Pull request by mlchung**
A trivial fix.   Convert the use of anonymous inner classes in a few Permission classes to lambdas to work around JDK-8076596, which has been resolved.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301462](https://bugs.openjdk.org/browse/JDK-8301462): Convert Permission files to use lambda after JDK-8076596

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [627da759](https://git.openjdk.org/jdk/pull/12463/files/627da75963d6e02d498d58742b38b06187eb33f0)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to [627da759](https://git.openjdk.org/jdk/pull/12463/files/627da75963d6e02d498d58742b38b06187eb33f0)
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12463/head:pull/12463` \
`$ git checkout pull/12463`

Update a local copy of the PR: \
`$ git checkout pull/12463` \
`$ git pull https://git.openjdk.org/jdk pull/12463/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12463`

View PR using the GUI difftool: \
`$ git pr show -t 12463`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12463.diff">https://git.openjdk.org/jdk/pull/12463.diff</a>

</details>

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Mandy, the changes look fine to me.

Each of these files will need a copyright year update before integrating.

**Comment by mlchung** [comment]
Thanks for the review @jaikiran

**Review by jaikiran — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
LGTM. I can't help noticing that the code for SocketPermission, PropertyPermission, and ServicePermission is almost identical. But there's not much we could do factorize that easily since the lambda requires access to private static method accessors: trying to factorize would probably add to the complexity instead of reducing it and impair readability.

**Comment by seanjmullan** [comment]
There's also one in `FilePermission.add()` that can be changed to use a lambda.

**Comment by mlchung** [comment]
Updated `FilePermissionCollection::add` to use lambda.

**Review by seanjmullan — APPROVED** [review]

**Pull request closed without merging**
