### PR TITLE
8344951: Stabilize write barrier micro-benchmarks

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset makes the `testArrayWriteBarrierFastPath*` micro-benchmarks in `WriteBarrier.java` more robust w.r.t. a few external factors, so that different GC barrier models can be compared more reliably. More specifically, it ensures that:

  - the main loop is never unrolled regardless of the selected GC algorithm,
  - no spilling occurs within the main loop for the final C2 compilation, and
  - the majority of the execution time is spent in the write operation and its associated barrier.

The changes preserve the original G1 barrier test profile, i.e. practically no write crosses heap regions under the default G1 configuration. More sophisticated benchmarks may be added in the future that exercise different G1 barrier levels.

Thanks to Thomas Schatzl for reporting and discussing issues in the micro-benchmarks.

**Testing:** build and run the micro-benchmarks (linux-x64, linux-aarch64, windows-x64, macosx-x64, macosx-aarch64).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344951](https://bugs.openjdk.org/browse/JDK-8344951): Stabilize write barrier micro-benchmarks (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22763/head:pull/22763` \
`$ git checkout pull/22763`

Update a local copy of the PR: \
`$ git checkout pull/22763` \
`$ git pull https://git.openjdk.org/jdk.git pull/22763/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22763`

View PR using the GUI difftool: \
`$ git pr show -t 22763`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22763.diff">https://git.openjdk.org/jdk/pull/22763.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22763#issuecomment-2545554504)
</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Is it possible to have 2 runs: one with default `LoopUnrollLimit` and an other as you set.

**Comment by robcasloz** [comment]
> Is it possible to have 2 runs: one with default `LoopUnrollLimit` and an other as you set.

Done (commit 25a24bcc).

**Comment by robcasloz** [comment]
Turns out that spilling did occur in the main loop of the `testArrayWriteBarrierFastPath*` micros for G1 on x64, but only when LinuxPerfAsmProfiler is disabled (!). The latest commit (20817324) ensures no spilling happens within the main loop (for G1, Serial, Parallel, and Z on x64), regardless of whether profiling is enabled, by disabling inlining the benchmarks into their caller JMH-generated harness. Thanks to Thomas Schatzl for pointing out the issue and helping reproduce it.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks for reviewing, Vladimir!

**Review by tschatzl — APPROVED** [review]

**Comment by robcasloz** [comment]
Thanks for reviewing, Thomas!

**Pull request closed without merging**
