### PR TITLE
8258383: vmTestbase/gc/g1/unloading/tests/unloading_compilation_level[1,2,3] time out without TieredCompilation

### PR DESCRIPTION
**Pull request by TobiHartmann**
The test gets stuck while waiting for a compilation to succeed, because the corresponding compilation level is not available since Tiered Compilation is disabled (or `TieredStopAtLevel` is set). The tests should not be executed without Tiered Compilation (or if the requested compilation level is not available) and also check the output of `enqueueMethodForCompilation` for sanity.

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258383](https://bugs.openjdk.java.net/browse/JDK-8258383): vmTestbase/gc/g1/unloading/tests/unloading_compilation_level[1,2,3] time out without TieredCompilation

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2125/head:pull/2125`
`$ git checkout pull/2125`

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I see such `requires` patter in other tests too. 
But what will happen if server VM is built without C1 - no tiered?
Such tests may need additions requires `vm.compiler1.enabled`

Also when requested level 4 compilation (*_compilation_level4_* tests) you don't need to force -XX:+TieredCompilation.

**Comment by TobiHartmann** [comment]
Thanks for the review Vladimir.

> I see such requires patter in other tests too.
> But what will happen if server VM is built without C1 - no tiered?
> Such tests may need additions requires vm.compiler1.enabled

Yes, I've took that pattern from other tests. The problem with `requires vm.compiler1.enabled` is that the test will be skipped if `-XX:-TieredCompilation` is set (because then C1 is not available). Since this is a general problem that affects other tests as well, I think it should be addressed separately if necessary. What do you think?

> Also when requested level 4 compilation (compilation_level4 tests) you don't need to force -XX:+TieredCompilation.

Right, I've updated the corresponding tests.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by vnkozlov** [comment]
> Thanks for the review Vladimir.
> 
> > I see such requires patter in other tests too.
> > But what will happen if server VM is built without C1 - no tiered?
> > Such tests may need additions requires vm.compiler1.enabled
> 
> Yes, I've took that pattern from other tests. The problem with `requires vm.compiler1.enabled` is that the test will be skipped if `-XX:-TieredCompilation` is set (because then C1 is not available). Since this is a general problem that affects other tests as well, I think it should be addressed separately if necessary. What do you think?

Yes, you are right about switching off C1 with TieredCompilation flag. Current changes are fine.
I agree with addressing C1 absence from VM build in separate changes. I think we need additional `requires` feature to check if C1/C2 are included in VM build. `vm.server` is not enough.

**Comment by TobiHartmann** [comment]
Thanks for the review, Vladimir!

**Pull request closed without merging**
