### PR TITLE
8325083: jdk/incubator/vector/Double512VectorTests.java crashes in Assembler::vex_prefix_and_encode

### PR DESCRIPTION
**Pull request by jatin-bhateja**
This bugfix patch limits the register class for operands of byte to double cast pattern to prevent reported assertion failure on Knights family CPUs.

Kindly review and share your feedback.

Best Regards,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8325083: jdk/incubator/vector/Double512VectorTests.java crashes in Assembler::vex_prefix_and_encode`

### Issue
 * [JDK-8325083](https://bugs.openjdk.org/browse/JDK-8325083): jdk/incubator/vector/Double512VectorTests.java crashes in Assembler::vex_prefix_and_encode (**Bug** - P3)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19407/head:pull/19407` \
`$ git checkout pull/19407`

Update a local copy of the PR: \
`$ git checkout pull/19407` \
`$ git pull https://git.openjdk.org/jdk.git pull/19407/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19407`

View PR using the GUI difftool: \
`$ git pr show -t 19407`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19407.diff">https://git.openjdk.org/jdk/pull/19407.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19407#issuecomment-2132713413)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
@jatin-bhateja can you explain in more details what KNL is missing to trigger the assert? Can we predicate on missing feature here instead of KNL && DBL checks?
My concern is KNL check could be not enough if such feature is disabled in some container environment which does not match KNL settings.

Why we have `assert(UseAVX > 0` here? `Assembler::vpmov*()` instructions have corresponding asserts already. No need to fix it here but I think we need to cleanup `*.ad` files from such duplicated asserts as separate RFE.

**Comment by jatin-bhateja** [comment]
> @jatin-bhateja can you explain in more details what KNL is missing to trigger the assert? Can we predicate on missing feature here instead of KNL && DBL checks? My concern is KNL check could be not enough if such feature is disabled in some container environment which does not match KNL settings.
> 
> Why we have `assert(UseAVX > 0` here? `Assembler::vpmov*()` instructions have corresponding asserts already. No need to fix it here but I think we need to cleanup `*.ad` files from such duplicated asserts as separate RFE.

Hi @vnkozlov ,  Problem occurs while emitting VMOVSXBD, please refer to following LOC
https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp#L2936

This is a case for byte to double conversion and we break it into two instructions, first for byte to doubleword casting followed by doubleword to double precision casting, while we could have used a combination of VMOVSXBQ + VCVTQQ2PD but it would further constrain this since quadword to double precision casting needs AVX512DQ feature, thus current scheme works well and by limiting operand allocations to legacy register set we can safely issue 256 bit VMOVSXBD instruction on KNL target which lacks AVX512VL feature.

**Comment by vnkozlov** [comment]
@jatin-bhateja Thank you for explaining the issue.  I am fine with splitting instruction to use legacy registers.
My only concern is use of `!VM_Version::is_knights_family()` check. Can we use `VM_Version::supports_avx512vl()` instead?

**Comment by jatin-bhateja** [comment]
> @jatin-bhateja Thank you for explaining the issue. I am fine with splitting instruction to use legacy registers. My only concern is use of `!VM_Version::is_knights_family()` check. Can we use `VM_Version::supports_avx512vl()` instead?

DONE

**Comment by vnkozlov** [comment]
Something went wrong with you latest push - unrelated changes were included.

**Comment by jatin-bhateja** [comment]
> Something went wrong with your latest push - unrelated changes were included.

My bad, was creating a separate PR for it, somehow it got pushed with this one.

**Comment by vnkozlov** [comment]
Looks good. I will run our testing.
Please verify that it still pass reproducer case.

**Review by vnkozlov — APPROVED** [review]
My testing passed without new failures.

**Review by sviswa7 — APPROVED** [review]
Looks good to me as well.

**Pull request closed without merging**
