### PR TITLE
8323503: x86: Shorter movptr(reg, imm) for 32-bit unsigned immediates

### PR DESCRIPTION
**Pull request by shipilev**
We noticed in [JDK-8323497](https://bugs.openjdk.org/browse/JDK-8323497) that `movptr` optimization done in [JDK-8319406](https://bugs.openjdk.org/browse/JDK-8319406) is not covering the case of immediates that fit in 32-bit unsigned, but do not fit in 32-bit signed. In that case, we can maybe do `mov r32, imm32` and rely on x86 zero-extending 32->64 bit for us. Since `movl` encoding is smaller than sign-extending `movq`, we also save more code on most paths that [JDK-8319406](https://bugs.openjdk.org/browse/JDK-8319406) improved.

There are a few interesting conversions along the way:
  1. `intptr_t` -> `uint32_t` (this method)
  2. `uint32_t` -> `int32_t` (argument conversion for `movl`)
  3. `int32_t` -> `uint32_t` (in `emit_int32`)
 
I believe these are safe after `is_uimm32` check, but please check (sic) me on this.

Note that x86_64 matcher already does similar thing for immediates:

```
// Long Immediate 32-bit unsigned
operand immUL32()
%{
  predicate(n->get_long() == (unsigned int) (n->get_long()));
  match(ConL);
  ...
%}

instruct loadConUL32(rRegL dst, immUL32 src)
%{
  ...
  format %{ "movl    $dst, $src\t# long (unsigned 32-bit)" %}
  ins_encode %{
    __ movl($dst$$Register, $src$$constant);
  %}
%}
```

Additional testing:
 - [x] Linux x86_64 server fastdebug, `tier{1,2,3,4}`

Code sizes for `Hello World`, `-Xcomp`:

```
# Before
  tier1 nmethod code size         :   426208 bytes
  tier2 nmethod code size         :   462880 bytes
  tier3 nmethod code size         :   889992 bytes
  tier4 nmethod code size         :  1244448 bytes

# After
  tier1 nmethod code size         :   425768 bytes (-0.1%)
  tier2 nmethod code size         :   462400 bytes (-0.1%)
  tier3 nmethod code size         :   882072 bytes (-0.8%)
  tier4 nmethod code size         :  1236448 bytes (-0.6%)
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323503](https://bugs.openjdk.org/browse/JDK-8323503): x86: Shorter movptr(reg, imm) for 32-bit unsigned immediates (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Evgeny Astigeevich](https://openjdk.org/census#eastigeevich) (@eastig - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17343/head:pull/17343` \
`$ git checkout pull/17343`

Update a local copy of the PR: \
`$ git checkout pull/17343` \
`$ git pull https://git.openjdk.org/jdk.git pull/17343/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17343`

View PR using the GUI difftool: \
`$ git pr show -t 17343`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17343.diff">https://git.openjdk.org/jdk/pull/17343.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17343#issuecomment-1885442639)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Looks good.

**Review by vnkozlov — COMMENTED** [review]
What about next?:
```
// src should NEVER be a real pointer. Use AddressLiteral for true pointers
void MacroAssembler::movptr(Address dst, intptr_t src, Register rscratch) {
  if (is_simm32(src)) {
    movptr(dst, checked_cast<int32_t>(src));
```

**Comment by shipilev** [comment]
> What about next?:
> 
> ```
> // src should NEVER be a real pointer. Use AddressLiteral for true pointers
> void MacroAssembler::movptr(Address dst, intptr_t src, Register rscratch) {
>   if (is_simm32(src)) {
>     movptr(dst, checked_cast<int32_t>(src));
> ```

Ah, hm! That is the version with `Address dst`. I don't think this zero-extending trick with `movl` and 64-bit destination register works here, because there is no register. We need the affect the full 64-bit of memory, which is what `movptr(Address, int32_t)` -> `movslq` would already give. I don't see any other missing shortcuts here.

**Comment by vnkozlov** [comment]
Okay.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
I think this implicitly relies on 2-complement representation for signed types, so that signed->unsigned conversion is sane. I modeled these casts in godbolt, and it made sense, and UBSan did not complain. Let's see if this rubs anyone else the wrong way. (Trying to snipe @theRealAph or @kimbarrett here.)

**Review by eastig — APPROVED** [review]
lgtm

**Comment by shipilev** [comment]
All right; I also run a few stressy things here, and I think we are fine. Let's see if it breaks anything else.

/integrate

**Pull request closed without merging**
