### PR TITLE
JDK-8305223: IGV: mark osr compiled graphs with [OSR] in the name

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Graphs in IGV that were osr compiled have an "osr" property. To make it easier to distinguish them from non-osr, append `[OSR]` to the name of the group in the outline

osr

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305223](https://bugs.openjdk.org/browse/JDK-8305223): IGV: mark osr compiled graphs with [OSR] in the name

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [bfe14342](https://git.openjdk.org/jdk/pull/13241/files/bfe143422883744e58795498140af58079f95304)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Eric Liu](https://openjdk.org/census#eliu) (@theRealELiu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13241/head:pull/13241` \
`$ git checkout pull/13241`

Update a local copy of the PR: \
`$ git checkout pull/13241` \
`$ git pull https://git.openjdk.org/jdk.git pull/13241/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13241`

View PR using the GUI difftool: \
`$ git pr show -t 13241`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13241.diff">https://git.openjdk.org/jdk/pull/13241.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by robcasloz — APPROVED** [review]
Looks good. Could you update the copyright year?

**Comment by tobiasholenstein** [comment]
> Looks good. Could you update the copyright year?
 
done

**Review by robcasloz — APPROVED** [review]

**Comment by tobiasholenstein** [comment]
thanks @TobiHartmann , @robcasloz and @theRealELiu for the reviews!

/integrate

**Pull request closed without merging**
