### PR TITLE
8276976: Rename LIR_OprDesc to LIR_Opr

### PR DESCRIPTION
**Pull request by caoman**
Hi all,

Can I have reviews for this mechanical renaming change as a follow up to https://bugs.openjdk.java.net/browse/JDK-8276453?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276976](https://bugs.openjdk.java.net/browse/JDK-8276976): Rename LIR_OprDesc to LIR_Opr

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)

### Contributors
 * Chuck Rasbold `<rasbold@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6377/head:pull/6377` \
`$ git checkout pull/6377`

Update a local copy of the PR: \
`$ git checkout pull/6377` \
`$ git pull https://git.openjdk.java.net/jdk pull/6377/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6377`

View PR using the GUI difftool: \
`$ git pr show -t 6377`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6377.diff">https://git.openjdk.java.net/jdk/pull/6377.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by veresov — APPROVED** [review]
Looks good.

**Comment by caoman** [comment]
Thank you for the reviews

**Pull request closed without merging**
