### PR TITLE
8321151: JDK-8294427 breaks Windows L&F on all older Windows versions

### PR DESCRIPTION
**Pull request by rajamah**
**Issue:**
https://bugs.openjdk.org/browse/JDK-8294427 starts to use this API
https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-openthemedatafordpi

which was introduced only in Windows 10 1703.
So the theming engine won't load on anything earlier like the original windows 10 or windows 8.1 etc.

So as an undocumented side-effect it completely breaks the theming of Windows L&F on anything earlier
and it falls back to hard-coded rendering like Windows NT/Windows 2000

Whilst those older versions are technically out of at least "mainstream" support, this is not the way
to make that breaking change and I see this fix has been backported to older releases which expect stability

it seems to me that this code should NOT fail if the new API is missing and instead fall back to the old code.
No one will care about a pixel being off on hi-dpi if the entire UI is wrong.

**Fix:**
Added fallback path to support older versions of Windows that do not support OpenThemeDataForDpi().

**Testing:**
Tested on my Windows 10 machine with and without the fallback path and it works as expected.
Alexey tested on Windows 7 and on Windows 10 v1607 — it works correctly (jdk 21.0.2 can't render themes as reported).
He also tested on Windows 11 .

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8321151](https://bugs.openjdk.org/browse/JDK-8321151): JDK-8294427 breaks Windows L&amp;F on all older Windows versions (**Bug** - P4)

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Alisen Chung](https://openjdk.org/census#achung) (@alisenchung - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17173/head:pull/17173` \
`$ git checkout pull/17173`

Update a local copy of the PR: \
`$ git checkout pull/17173` \
`$ git pull https://git.openjdk.org/jdk.git pull/17173/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17173`

View PR using the GUI difftool: \
`$ git pr show -t 17173`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17173.diff">https://git.openjdk.org/jdk/pull/17173.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17173#issuecomment-1865348543)

### CODE REVIEW

**Review by aivanov-jdk — APPROVED** [review]
Looks good to me.

I tested it on Windows 7, Windows 10 v1607 as well as current versions of Windows 10 and 11. I ran SwingSet2 side-by-side and I didn't spot any differences.

**Review by alisenchung — APPROVED** [review]
Looks fine

**Pull request closed without merging**
