### PR TITLE
8318605: Enable parallelism in vmTestbase/nsk/stress/stack tests

### PR DESCRIPTION
**Pull request by elifaslan1**
The commit includes changes to unblock parallelism vmTestbase/nsk/stress/stack tests.
GHA tested.
Command below succeeded 
`make test TEST=vmTestbase/nsk/stress/stack JTREG=REPEAT_COUNT=100`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8318605](https://bugs.openjdk.org/browse/JDK-8318605): Enable parallelism in vmTestbase/nsk/stress/stack tests (**Enhancement** - P4)

### Reviewers
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18037/head:pull/18037` \
`$ git checkout pull/18037`

Update a local copy of the PR: \
`$ git checkout pull/18037` \
`$ git pull https://git.openjdk.org/jdk.git pull/18037/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18037`

View PR using the GUI difftool: \
`$ git pr show -t 18037`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18037.diff">https://git.openjdk.org/jdk/pull/18037.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18037#issuecomment-1968042511)

### CODE REVIEW

**Review by lgxbslgx — APPROVED** [review]
LGTM.

**Review by shipilev — APPROVED** [review]
Looks good, but we need @lmesnik to bless this integration.

/reviewers 2

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
