### PR TITLE
8305490: CommandProcessor command "dumpclass" produces classes with invalid field descriptors

### PR DESCRIPTION
**Pull request by asotona**
CommandProcessor command "dumpclass" produces classes with invalid field descriptors. 

Proposed patch fixes `sun.jvm.hotspot.oops.InstanceKlass::getFieldSignatureIndex` to return correct `getSignatureIndex` instead of invalid `getGenericSignatureIndex`.

Added condition to  `ClhsdbDumpclass` test assures no errors are reported by `javap` in the dumped classes.

Please review.

Thank you,
Adam

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8305490](https://bugs.openjdk.org/browse/JDK-8305490): CommandProcessor command "dumpclass" produces classes with invalid field descriptors

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [ff0b4c99](https://git.openjdk.org/jdk/pull/13321/files/ff0b4c9939c7861baa3aa8c6108355ded4494f14)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - **Reviewer**) ⚠️ Review applies to [ff0b4c99](https://git.openjdk.org/jdk/pull/13321/files/ff0b4c9939c7861baa3aa8c6108355ded4494f14)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13321/head:pull/13321` \
`$ git checkout pull/13321`

Update a local copy of the PR: \
`$ git checkout pull/13321` \
`$ git pull https://git.openjdk.org/jdk.git pull/13321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13321`

View PR using the GUI difftool: \
`$ git pr show -t 13321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13321.diff">https://git.openjdk.org/jdk/pull/13321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13321#issuecomment-1495510056)

### CODE REVIEW

**Review by plummercj — APPROVED** [review]
The test needs a copyright update. Otherwise the changes look good.

I assume the reason you caught this failure is because the [JDK-8294969](https://bugs.openjdk.org/browse/JDK-8294969) changes include making javap return a non-zero exit code if there are any error. If that's the case, I guess technically the test change is not needed, but probably good to have in place anyway.

**Review by fparain — APPROVED** [review]
Looks good to me.
Thank you for fixing this.

Fred

**Comment by asotona** [comment]
Thank you, I've updated test copyright header.

Yes, it was identified when working on [JDK-8294969](https://bugs.openjdk.org/browse/JDK-8294969), however it is still work in progress.

**Pull request closed without merging**
