### PR TITLE
8259628: jdk/net/ExtendedSocketOption/AsynchronousSocketChannelNAPITest.java fails intermittently

### PR DESCRIPTION
**Pull request by pconcannon**
Hi,

Could someone please review my fix for JDK-8259628: '`jdk/net/ExtendedSocketOption/AsynchronousSocketChannelNAPITest.java` fails intermittently' ?

`AsynchronousSocketChannelNAPITest` is failing intermittently on Linux due to a race condition caused by not correctly waiting for the result of an asynchronous operation. This fix rectifies this issue and adds additional checks to ensure correct result is received.

Kind regards,
Patrick

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259628](https://bugs.openjdk.java.net/browse/JDK-8259628): jdk/net/ExtendedSocketOption/AsynchronousSocketChannelNAPITest.java fails intermittently

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 507eeddeb75d7b51747164157a05c19ce9a18c5c

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2162/head:pull/2162`
`$ git checkout pull/2162`

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM. Thanks Patrick for taking this on!

**Comment by dfuch** [comment]
Hi Mark,

> The test has been modified to assert some conditions on the read and write buffer. These asserts, in theory, can not be assumed to hold true. Consider that the write returns a Future and will inform the writer how many bytes have been written. So writes are not atomic.
> Additionally, as such, a read may not actually read the number of bytes written by the writer,
> due to the underlying semantics of the supporting protocol (TCP/IP). If it was UDP as the underlying protocol then the read/write assertions would hold.

My understanding is that read will read a full datagram (or nothing) and write will write a full datagram (or nothing). Indeed a datagram is the smallest unit that can be read or write on an UDP channel. Two calls to write() will produce two datagrams. Two calls to read() will attempt to read two datagrams.

best regards,

-- daniel

**Comment by dfuch** [comment]
> My understanding is that read will read a full datagram (or nothing) and write will write a full datagram (or nothing). Indeed a datagram is the smallest unit that can be read or written on a UDP channel. Two calls to write() will produce two datagrams. Two calls to read() will attempt to read two datagrams.

... but we don't have a datagram channel here: it's a regular socket channel ... sorry for the confusion. 
Yes - objections accepted...

**Review by dfuch — CHANGES_REQUESTED** [review]
You could still do some checking if you wanted.
If you know that you have written `nsent` bytes, and that you later read `nread` bytes, then you could assert the following:
1. nread <= nsent
2. writeBuffer.mismatch(readBuffer) == (nread == nsent ? -1 : nread)

**Comment by msheppar** [comment]
Hi Daniel,
   by adding a read/send bytes checks, are we not obscuring the purpose of the test and that's the NAPI check ?
Consider that, as the communication channel between the writer and sender is a stream, there are no (atomic) message boundaries, and in theory a read could be less than an individual write in one iteration,  and then greater than the individual write in another iteration. Thus, adding an assert could give rise to unnecessary failures - it is unlikely in this test - in fact because of colocation you could place a strong bet that it won't happen. 
Nonetheless, the following is possible
iteration N      write n bytes, reads m where  m < n (The underlying TCP protocol machine has sent m bytes and not the full n)
iteration N +1  write n bytes, read n + (n-m)  i.e. the current write + the residue from the write in iteration N

and then an  assert nread <= nsent will fail  ?

In any case, the main thing is that the test is happy with its NAPI across the various reads

best regards
Mark

**Comment by dfuch** [comment]
> iteration N write n bytes, reads m where m < n (The underlying TCP protocol machine has sent m bytes and not the full n)
> iteration N +1 write n bytes, read n + (n-m) i.e. the current write + the residue from the write in iteration N
> 
> and then an assert nread <= nsent will fail ?

Good point. You'd have to aggregate the results across multiple read writes and that would clutter the test.
OK - I withdraw my suggestion. What you have now is good enough Patrick.
Approved.

**Review by dfuch — APPROVED** [review]

**Pull request closed without merging**
