### PR TITLE
8264048: Fix caching in Jar URL connections when an entry is missing

### PR DESCRIPTION
**Pull request by AlekseiEfimov**
Current fix tries to tackle an issue with URL connection referencing non-existing Jar file entries:
If an entry that doesn't exist is specified in an URL connection the underlying Jar file is still cached even if an exception is thrown after that. Such behavior prevents the caller, for instance, a `URLClassLoader`, from closing a Jar file.

The proposed fix checks if entry exists before caching a Jar file (only for cases with enabled caching):
- If entry exists - jar file is cached if it wasn't cached before
- If entry doesn't exist and jar file wasn't cached before - jar file is closed and exception is thrown
- If entry doesn't exist and jar file was cached before - jar file is kept cached and exception is thrown

The following tests have been used to verify the fix:
- New regression tests
- ``:jdk_core:`` tests
- `api/java_util`,`api/java_net` JCK tests

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264048](https://bugs.openjdk.java.net/browse/JDK-8264048): Fix caching in Jar URL connections when an entry is missing

### Reviewers
 * [Brent Christian](https://openjdk.java.net/census#bchristi) (@bchristi-git - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Contributors
 * Daniel Fuchs `<dfuchs@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3263/head:pull/3263` \
`$ git checkout pull/3263`

Update a local copy of the PR: \
`$ git checkout pull/3263` \
`$ git pull https://git.openjdk.java.net/jdk pull/3263/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3263`

View PR using the GUI difftool: \
`$ git pr show -t 3263`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3263.diff">https://git.openjdk.java.net/jdk/pull/3263.diff</a>

</details>

### CODE REVIEW

**Comment by dfuch** [comment]
Hi Aleksei, thanks for putting this together.

`test/jdk/sun/misc/URLClassPath/RemoveJar.java` seems to be an older version of `test/jdk/java/net/URLClassLoader/RemoveJar.java`. The two tests are almost identical - so `test/jdk/sun/misc/URLClassPath/RemoveJar.java` can probably be removed from the PR.

Otherwise the proposed changes look good to me.

**Comment by AlekseiEfimov** [comment]
Thanks for the review, Daniel. It is correct that `test/jdk/sun/misc/URLClassPath/RemoveJar.java` is an old version. It is removed now.

**Review by bchristi-git — APPROVED** [review]
Hi, Aleksei.  The change looks good.

**Review by dfuch — APPROVED** [review]

**Pull request closed without merging**
