### PR TITLE
8321299: runtime/logging/ClassLoadUnloadTest.java doesn't reliably trigger class unloading

### PR DESCRIPTION
**Pull request by matias9927**
ClassLoadUnloadTest.java passes by accident because an unrelated LambdaForm is being unloaded. The test class, `test.Empty` should be loaded by a custom class loader and then subsequently unloaded, however this is not actually occurring due to the sub-process not receiving the class path. This patch modifies `ClassUnloadCommon`, so it may accept a string containing the classlist, and `ClassLoadUnloadTest.java` so it checks specifically for `test.Empty` to be unloaded. Verified with tier1-5 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321299](https://bugs.openjdk.org/browse/JDK-8321299): runtime/logging/ClassLoadUnloadTest.java doesn't reliably trigger class unloading (**Bug** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [efa6b5e2](https://git.openjdk.org/jdk/pull/18207/files/efa6b5e2645abef70194e0e36278fad73e050938)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18207/head:pull/18207` \
`$ git checkout pull/18207`

Update a local copy of the PR: \
`$ git checkout pull/18207` \
`$ git pull https://git.openjdk.org/jdk.git pull/18207/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18207`

View PR using the GUI difftool: \
`$ git pr show -t 18207`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18207.diff">https://git.openjdk.org/jdk/pull/18207.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18207#issuecomment-1989474075)

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Well that's unexpected that the subprocess doesn't get the class path.  This looks good!  Please update the copyright headers.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Seems to me that the real problem here is the use of `ProcessTools.createLimitedTestJavaProcessBuilder` as that prevents the launched VM from getting the properties that jtreg sets, and thus in turn the `newClassLoader()` code couldn't create the right classpath. If we explicitly set the `test.class.path` property for the exec'd VM then that should fix it.

**Comment by dholmes-ora** [comment]
Also seems to me that `./runtime/logging/LoaderConstraintsTest.java` has the same kind of problem even though it is not failing - which suggests the test is flawed in some other way.

**Review by dholmes-ora — APPROVED** [review]
Thanks for the update! Much simpler/cleaner.

Did you get a chance to investigate the other test?

**Comment by matias9927** [comment]
> Did you get a chance to investigate the other test?

I've been looking into it but I noticed that there is no new output if I introduce a similar change to what I did here. I think `LoaderConstraintsTest.java` is actually working as intended since it doesn't matter which class loader loads the test class.

**Comment by matias9927** [comment]
Thanks for the feedback and reviews @coleenp and @dholmes-ora!
/integrate

**Pull request closed without merging**
