### PR TITLE
8322985: [BACKOUT] 8318562: Computational test more than 2x slower when AVX instructions are used

### PR DESCRIPTION
**Pull request by TobiHartmann**
[JDK-8318562](https://bugs.openjdk.org/browse/JDK-8318562) broke implicit null checking for cvt instructions. See JBS for details. Let's back it out for now because this is a potential showstopper for JDK 17.0.11, 21.0.2 and 22 and needs to be backported asap.

The backout applies cleanly.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322985](https://bugs.openjdk.org/browse/JDK-8322985): [BACKOUT] 8318562: Computational test more than 2x slower when AVX instructions are used (**Bug** - P1)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17279/head:pull/17279` \
`$ git checkout pull/17279`

Update a local copy of the PR: \
`$ git checkout pull/17279` \
`$ git pull https://git.openjdk.org/jdk.git pull/17279/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17279`

View PR using the GUI difftool: \
`$ git pr show -t 17279`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17279.diff">https://git.openjdk.org/jdk/pull/17279.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17279#issuecomment-1878688117)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Sounds reasonable, backout looks good.

**Comment by TobiHartmann** [comment]
Thanks, Christian!

**Review by shipilev — APPROVED** [review]
All right, dang. 

I would handle 17.0.11 (April 2024) backout. For 21.0.2, we need to coordinate with Rob.

**Comment by TobiHartmann** [comment]
Thanks Aleksey, I'll reach out to Rob by email.

**Comment by TobiHartmann** [comment]
Testing is clean. I'm integrating this so that we can prepare the backports asap.

**Pull request closed without merging**
