### PR TITLE
8344611: Add missing classpath exception

### PR DESCRIPTION
**Pull request by Sorna-Sarathi**
This PR adds missing Classpath exception in several files.

JBS Issue: [JDK-8334611](https://bugs.openjdk.org/browse/JDK-8344611)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344611](https://bugs.openjdk.org/browse/JDK-8344611): Add missing classpath exception (**Bug** - P2)

### Reviewers
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Committer)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22272/head:pull/22272` \
`$ git checkout pull/22272`

Update a local copy of the PR: \
`$ git checkout pull/22272` \
`$ git pull https://git.openjdk.org/jdk.git pull/22272/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22272`

View PR using the GUI difftool: \
`$ git pr show -t 22272`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22272.diff">https://git.openjdk.org/jdk/pull/22272.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22272#issuecomment-2488809348)
</details>

### CODE REVIEW

**Review by offamitkumar — CHANGES_REQUESTED** [review]
Do similar change for: 
```
src/java.base/share/native/libjava/ub.h
src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/JimageDiffGenerator.java
src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/ResourcePoolReader.java
```

**Comment by Sorna-Sarathi** [comment]
> Do similar change for:
> 
> ```
> src/java.base/share/native/libjava/ub.h
> src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/JimageDiffGenerator.java
> src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/ResourcePoolReader.java
> ```

Added the changes for the above files.

**Review by offamitkumar — APPROVED** [review]

**Comment by Sorna-Sarathi** [comment]
### Summary
This PR fixes [JDK-8334611](https://bugs.openjdk.org/browse/JDK-8344611) and adds missing classpath exception in several files. It's now ready for review

Could someone from the community please review this PR and provide feedback? 
Thank you!

**Comment by offamitkumar** [comment]
@jerboaa can we get one more approval ?

**Comment by jerboaa** [comment]
```
src/java.base/share/native/libjava/ub.h
src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/JimageDiffGenerator.java
src/jdk.jlink/share/classes/jdk/tools/jlink/internal/runtimelink/ResourcePoolReader.java
```

Look OK. I'm not sure about the libsleef part. A reviewer of that PR, perhaps @theRealAph, might be able to help?

**Comment by offamitkumar** [comment]
This only adds information about the classpath exception copyright. So can't we consider it trivial ? As there is not functionality change.

**Comment by dholmes-ora** [comment]
It may be "trivial" in that sense but if "Oracle is designating ..." then it probably needs someone from Oracle to confirm it is an okay change to make. Like @jerboaa I am unclear about the libsleef files. @irisclark can you give the okay here?

**Comment by AlanBateman** [comment]
If you want, you could separate the two areas so that you at least get the jlink source updated.

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
