### PR TITLE
JDK-8258187 IllegalMonitorStateException in ArrayBlockingQueue

### PR DESCRIPTION
**Pull request by Martin-Buchholz**
/cc core-libs

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258187](https://bugs.openjdk.java.net/browse/JDK-8258187): IllegalMonitorStateException in ArrayBlockingQueue

### Reviewers
 * [Doug Lea](https://openjdk.java.net/census#dl) (@DougLea - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2015/head:pull/2015`
`$ git checkout pull/2015`

### CODE REVIEW

**Review by DougLea — APPROVED** [review]

**Comment by Martin-Buchholz** [comment]
The code is good, but this is actually a fix for 
JDK-8258187 IllegalMonitorStateException in ArrayBlockingQueue
I will fiddle with the PR and JBS metadata.

**Pull request closed without merging**
