### PR TITLE
8308537: Remove BreakAtNode

### PR DESCRIPTION
**Pull request by enothum**
The BreakAtNode flag was unused as its utility is now insignificant with the use of "rr" in practice. See the following discussion: https://github.com/openjdk/jdk/pull/13767#issuecomment-1541805032. I removed the BreakAtNode flag and the related parts in the code.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308537](https://bugs.openjdk.org/browse/JDK-8308537): Remove BreakAtNode

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14311/head:pull/14311` \
`$ git checkout pull/14311`

Update a local copy of the PR: \
`$ git checkout pull/14311` \
`$ git pull https://git.openjdk.org/jdk.git pull/14311/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14311`

View PR using the GUI difftool: \
`$ git pr show -t 14311`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14311.diff">https://git.openjdk.org/jdk/pull/14311.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14311#issuecomment-1578188365)

### CODE REVIEW

**Comment by rwestrel** [comment]
I actually use it (albeit rarely). rr is linux x86 only AFAIK.

**Comment by enothum** [comment]
Okay sure, in that case I am withdrawing this PR, and keep the BreakAtNode flag.

**Comment by simonis** [comment]
I agree with @rwestrel. It's one of the features that's rarely used, but it doesn't hurt and for some situations it's good that it's there.

**Comment by navyxliu** [comment]
I am using BreakAtNode in particular with debug_idx a lot. It helps me to locate when and where the node-in-question is constructed. If you plan to remove it, is there any alternative?

**Comment by TobiHartmann** [comment]
> If you plan to remove it, is there any alternative?

Many of us use http://rr-project.org/ for debugging. Being able to reverse execute is much more powerful because you can simply set watchpoints on the node or it's inputs to trace back creation of entire subgraphs in the IR.

**Pull request closed without merging**
