### PR TITLE
8268165: AsyncLogging will crash if rotate() fails

### PR DESCRIPTION
**Pull request by navyxliu**
LogFileOutput::rotate() may leave _stream NULL because os::fopen() may return NULL due to space or inode limitations. AsyncLogWriter::write() calls LogFileOutput::write_blocking() without null check. Null check is added to prevent from crashing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268165](https://bugs.openjdk.java.net/browse/JDK-8268165): AsyncLogging will crash if rotate() fails

### Reviewers
 * [Yasumasa Suenaga](https://openjdk.java.net/census#ysuenaga) (@YaSuenag - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4332/head:pull/4332` \
`$ git checkout pull/4332`

Update a local copy of the PR: \
`$ git checkout pull/4332` \
`$ git pull https://git.openjdk.java.net/jdk pull/4332/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4332`

View PR using the GUI difftool: \
`$ git pr show -t 4332`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4332.diff">https://git.openjdk.java.net/jdk/pull/4332.diff</a>

</details>

### CODE REVIEW

**Comment by navyxliu** [comment]
/summary LogFileOutput::rotate() may leave _stream NULL because os::fopen() may return NULL due to space or inode limitations.  AsyncLogWriter::write() calls LogFileOutput::write_blocking() without null check.  Null check is added to prevent from crashing.

**Comment by navyxliu** [comment]
hi, @YaSuenag, 
Could you take a look at this? It's an error-handling patch. 

thanks,
--lx

**Review by YaSuenag — APPROVED** [review]
Looks good.

I wonder why we use semaphore instead of mutex for `_rotation_semaphore`, but it's not yours.

**Comment by navyxliu** [comment]
> Looks good.
> 
> I wonder why we use semaphore instead of mutex for `_rotation_semaphore`, but it's not yours.

Thanks for reviewing it. 

I can try to answer this.  Synchronous logging writing may happen anywhere and anytime. 
hotspot's mutex requires Thread::current().  We can't assume that in very early stage or very late stage, or it will fail this assertion. 
```
  assert(current != NULL, "Thread::current() called on detached thread");
```

eg. this logsite is invoked after `delete thread;`.  
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/threadSMR.cpp#L1027

Semaphore doesn't have this constraint.

**Comment by YaSuenag** [comment]
> I can try to answer this. Synchronous logging writing may happen anywhere and anytime.
> hotspot's mutex requires Thread::current(). We can't assume that in very early stage or very late stage, or it will fail this assertion.
> 
> ```
>   assert(current != NULL, "Thread::current() called on detached thread");
> ```
> 
> eg. this logsite is invoked after `delete thread;`.
> https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/threadSMR.cpp#L1027
> 
> Semaphore doesn't have this constraint.

Ah, I see. Thanks!

**Comment by YaSuenag** [comment]
Sorry, I will be careful.

**Pull request closed without merging**
