### PR TITLE
JDK-8324341 : Remove redundant preprocessor #if's checks

### PR DESCRIPTION
**Pull request by JohnTortugo**
Can I please get some reviews for this change to remove some redundant #if / #ifdefs ?

My search was just a simple grep + some bash script, though. I tested using JTREG on MacOS, Linux Mariner & Alpine from tier1 to 3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324341](https://bugs.openjdk.org/browse/JDK-8324341): Remove redundant preprocessor #if's checks (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19378/head:pull/19378` \
`$ git checkout pull/19378`

Update a local copy of the PR: \
`$ git checkout pull/19378` \
`$ git pull https://git.openjdk.org/jdk.git pull/19378/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19378`

View PR using the GUI difftool: \
`$ git pr show -t 19378`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19378.diff">https://git.openjdk.org/jdk/pull/19378.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19378#issuecomment-2128354459)

### CODE REVIEW

**Comment by albertnetymk** [comment]
Can you merge master to re-trigger GHA?

**Comment by JohnTortugo** [comment]
@albertnetymk - I updated the branch, and all GHA are passing. Thanks!

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by albertnetymk — APPROVED** [review]

**Pull request closed without merging**
