### PR TITLE
8255720: Optimize bci_to_dp/-data by enabling iteration over raw DataLayouts

### PR DESCRIPTION
**Pull request by cl4es**
MethodData::bci_to_dp and ciMethodData::bci_to_data show up in startup/warmup profiles - much of the overhead allocating resource objects when iterating over ProfileData objects (next_data)

Providing a means to iterate over the raw DataLayout objects allow us to avoid explicitly allocating resource objects for purposes of calculating the next DataLayout address for the most common types. 

This patch reduces overhead of MethodData::bci_to_dp and ciMethodData::bci_to_data by 80% or more in profiles and has a measurable impact on simple startup tests, e.g. ~250k instruction (~0.2% of total) reduction on Hello World.

Testing: tier1-3 passed

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255720](https://bugs.openjdk.java.net/browse/JDK-8255720): Optimize bci_to_dp/-data by enabling iteration over raw DataLayouts

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 0d8e8f048289ae3387298d4d05ac11ba26eed217
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/988/head:pull/988`
`$ git checkout pull/988`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Nice!

**Review by TobiHartmann — APPROVED** [review]
Looks good to! Some of the code formatting could be improved though (missing new lines between method definitions).

**Review by TobiHartmann — APPROVED** [review]
Looks good, thanks for making these changes.

**Comment by cl4es** [comment]
@vnkozlov @TobiHartmann - thank you for reviewing!

/integrate

**Pull request closed without merging**
