### PR TITLE
8328081: Remove unnecessary return statement in method `markWord::displaced_mark_helper`

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

This trivial patch removes unnecessary return statement in method `markWord::displaced_mark_helper`.

Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328081](https://bugs.openjdk.org/browse/JDK-8328081): Remove unnecessary return statement in method `markWord::displaced_mark_helper` (**Enhancement** - P5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18272/head:pull/18272` \
`$ git checkout pull/18272`

Update a local copy of the PR: \
`$ git checkout pull/18272` \
`$ git pull https://git.openjdk.org/jdk.git pull/18272/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18272`

View PR using the GUI difftool: \
`$ git pr show -t 18272`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18272.diff">https://git.openjdk.org/jdk/pull/18272.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18272#issuecomment-1994338490)

### CODE REVIEW

**Comment by shipilev** [comment]
I think we do this as the matter of course, in case `fatal` is not handled as non-returning by compilers. Does this fix any existing compiler warning/failure?

**Comment by lgxbslgx** [comment]
> I think we do this as the matter of course, in case `fatal` is not handled as non-returning by compilers.

The method `markWord::set_displaced_mark_helper` has no return statement at the end. So I want the `markWord::displaced_mark_helper` to be consistent with `markWord::set_displaced_mark_helper`.

> Does this fix any existing compiler warning/failure?

I didn't notice the compiler warning, but the IDE `CLion` warns that the return statement is `unreachable code`.

**Comment by dholmes-ora** [comment]
You would need to verify that this does not cause a build warning with all supported compilers on all platforms. As stated above these "fake" returns exist precisely because compilers (in the past at least) did not recognize that `fatal` is non-returning.

**Comment by lgxbslgx** [comment]
> You would need to verify that this does not cause a build warning with all supported compilers on all platforms.

Sorry, I don't have all the environments locally to verify. May need some help. Thanks.

**Comment by dholmes-ora** [comment]
> Sorry, I don't have all the environments locally to verify. May need some help. Thanks.

My point was a bit too subtle. Given that you can't verify all the compilers as needed, the change should not be made in my opinion.

**Comment by lgxbslgx** [comment]
> My point was a bit too subtle. Given that you can't verify all the compilers as needed, the change should not be made in my opinion.

Got it. Thanks for your kindly discussion and suggestion.

> The method `markWord::set_displaced_mark_helper` has no return statement at the end. So I want the `markWord::displaced_mark_helper` to be consistent with `markWord::set_displaced_mark_helper`.

I notice the return value of the method `markWord::set_displaced_mark_helper` is `void`, but the method `markWord::displaced_mark_helper` has a not empty return value. It is the point I missed so that I submitted this wrong PR.

It is my negligence. Apologize for wasting your time.

**Pull request closed without merging**
