### PR TITLE
8311877: [macos] Add CLI options to provide signing identity directly to codesign and productbuild

### PR DESCRIPTION
**Pull request by sashamatveev**
- Added `--mac-app-image-sign-identity` and `--mac-installer-sign-identity` CLI options to jpackage to provide signing identity directly to `codesign` and `productbuild` tools as per CSR [JDK-8316631](https://bugs.openjdk.org/browse/JDK-8316631).
- If `codesign` or `productbuild` fails, then output of these tools will be printed to stdout to help user diagnose issues with signing using new options. Examples with sign identity set to "test" which does not exist on system:
> Error: "codesign" failed with following output:
> test: no identity found

> Error: "productbuild" failed with following output:
> productbuild: error: Cannot write product to "/Users/SOMEDIR/Test-1.0.pkg". (Could not find appropriate signing identity for “test”.)
- Added error handling not to allow invalid combinations of signing options.
- Updated signing tests to test new changes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8316631](https://bugs.openjdk.org/browse/JDK-8316631) to be approved

### Issues
 * [JDK-8311877](https://bugs.openjdk.org/browse/JDK-8311877): [macos] Add CLI options to provide signing identity directly to codesign and productbuild (**Bug** - P3)
 * [JDK-8316631](https://bugs.openjdk.org/browse/JDK-8316631): [macos] Add CLI options to provide signing identity directly to codesign and productbuild (**CSR**)

### Reviewers
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16085/head:pull/16085` \
`$ git checkout pull/16085`

Update a local copy of the PR: \
`$ git checkout pull/16085` \
`$ git pull https://git.openjdk.org/jdk.git pull/16085/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16085`

View PR using the GUI difftool: \
`$ git pr show -t 16085`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16085.diff">https://git.openjdk.org/jdk/pull/16085.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16085#issuecomment-1751499741)

### CODE REVIEW

**Comment by victordyakov** [comment]
@alexeysemenyukoracle please review

**Comment by alexeysemenyukoracle** [comment]
If I get it right from the code, if `--mac-app-image-sign-identity` or `--mac-installer-sign-identity` option is specified and `--mac-sign` is NOT, it is an error. What is the point in `--mac-sign` then? It looks redundant.

If we still want `--mac-sign` to have any meaning when `--mac-app-image-sign-identity` and `--mac-installer-sign-identity` are used let's make jpackage silently ignore any signing options if `--mac-sign` is not specified.

E.g.:
`jpackage --mac-app-image-sign-identity foo` - no error and no signing

`jpackage --mac-app-image-sign-identity foo --mac-sign` - no error, run signing

**Comment by sashamatveev** [comment]
Yes, you got it right. I agree it does not make sense to consider error if `--mac-sign` is not specified. I fixed it as you suggested. `--mac-app-image-sign-identity` will be ignored and no signing is done if `--mac-sign` is not specified.

Also, updated `SigningPackageTest.java` to include tests for cases when only app-image is being signed or when only pkg is being signed using sign identity options.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Comment by sashamatveev** [comment]
Michael filed https://bugs.openjdk.org/browse/JDK-8318063 for codesign verification, so I would prefer to move discussion under this JBS issue on this topic.

For now I do not know if we need to add it. From my experience I never found case when codesign did not fail during signing, but signature verification failed. So, for now I think it is redundant and we will never get to signature verification step if something wrong since codesign will fail during signing. Only case I see is when we did not run codesign at all, but it means our entire signing is broken.

Michael, do you have any examples when you was able to sign application bundle via jpackage or manually, but codesign verification gave error?

**Pull request closed without merging**
