### PR TITLE
8279317: compiler/jvmci/compilerToVM/DisassembleCodeBlobTest.java assumes immutable code

### PR DESCRIPTION
**Pull request by dean-long**
This test was failing in loom because of nmethod entry barriers, but there are other reasons why it shouldn't assume immutable code, such as embedded oops and NativeJump::patch_verified_entry().

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279317](https://bugs.openjdk.java.net/browse/JDK-8279317): compiler/jvmci/compilerToVM/DisassembleCodeBlobTest.java assumes immutable code

### Reviewers
 * [Doug Simon](https://openjdk.java.net/census#dnsimon) (@dougxc - Committer) ⚠️ Review applies to b62af58b6e0c53108f9a357cf06a644cb420a95d
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7781/head:pull/7781` \
`$ git checkout pull/7781`

Update a local copy of the PR: \
`$ git checkout pull/7781` \
`$ git pull https://git.openjdk.java.net/jdk pull/7781/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7781`

View PR using the GUI difftool: \
`$ git pr show -t 7781`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7781.diff">https://git.openjdk.java.net/jdk/pull/7781.diff</a>

</details>

### CODE REVIEW

**Comment by dean-long** [comment]
Got some test failures, putting back into Draft mode.

**Comment by dougxc** [comment]
I see now that it's probably unrealistic to expect compiled code to be immutable, even if said code is never executed.

**Review by dougxc — APPROVED** [review]

**Comment by dean-long** [comment]
Test updated.  Rerunning tests.

**Comment by dean-long** [comment]
Thanks Doug.

**Review by veresov — APPROVED** [review]

**Comment by dean-long** [comment]
Thanks Igor.

**Pull request closed without merging**
