### PR TITLE
8258912: Remove JVM options CountJNICalls and CountJVMCalls

### PR DESCRIPTION
**Pull request by hseigel**
Please review this change to remove the old non-product JVM -XX flags CountRuntimeCalls, CountJNICalls, CountJVMCalls, and CountRemovableExceptions.  Additionally, this change removes non-product flag WarnOnStalledSpinLock because, as a result of this change, it is no longer used.

The change was tested with Mach5 tiers 1-2 on Linux, Mac OS, and Windows, and tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258912](https://bugs.openjdk.java.net/browse/JDK-8258912): Remove JVM options CountJNICalls and CountJVMCalls

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2050/head:pull/2050`
`$ git checkout pull/2050`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
LGTM!

**Review by lfoltan — APPROVED** [review]
LGTM.
Lois

**Review by dholmes-ora — COMMENTED** [review]
Hi Harold,

The call counters seem like useful statistics to me, though ones that may only be checked during specific types of development work. I think some consultation may be in order here rather than "take it away and see if anyone complains".

At a minimum I'd like to know whether our benchmarking/optimisation experts ever utilise these when figuring out code changes - paging @cl4es and @shipilev  :)

Thanks,
David

**Review by shipilev — APPROVED** [review]
I never used these flags, and I don't think they are very useful. I think most of that data is supposed to be delivered by JFR these days, instead of ad-hoc profiling facilities. If there are no relevant JFR events, they could be added later.

**Comment by hseigel** [comment]
Thanks Coleen, Lois, and Aleksey for reviewing this change and David for his comments!

/integrate

**Pull request closed without merging**
