### PR TITLE
8312585: Rename DisableTHPStackMitigation flag to THPStackMitigation

### PR DESCRIPTION
**Pull request by shipilev**
The flag newly added by [JDK-8312182](https://bugs.openjdk.org/browse/JDK-8312182) is prompting the use of `-XX:+DisableTHPStackMitigation` to disable the THP stack mitigation, thus allowing THP in thread stacks. This double negation does not read well, and not in line with other mitigation flags like `IntelJccErratumMitigation`.

It would be better to rename the flag to avoid double-negation, before it proliferates to other JDK releases.

(I would have the same comment during the original review, but missed it :P)

Additional testing: 
 - [x] GHA
 - [x] Linux x86_64 fastdebug, affected test

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312585](https://bugs.openjdk.org/browse/JDK-8312585): Rename DisableTHPStackMitigation flag to THPStackMitigation (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14992/head:pull/14992` \
`$ git checkout pull/14992`

Update a local copy of the PR: \
`$ git checkout pull/14992` \
`$ git pull https://git.openjdk.org/jdk.git pull/14992/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14992`

View PR using the GUI difftool: \
`$ git pr show -t 14992`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14992.diff">https://git.openjdk.org/jdk/pull/14992.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14992#issuecomment-1647519536)

### CODE REVIEW

**Comment by shipilev** [comment]
FYI @tstuefe.

**Comment by dholmes-ora** [comment]
I disagree. This name is exactly what is intended - we disable a mitigation/workaround. It's name is consistent with previous flags of this kind DisableXXXWorkAround IIRC.

**Comment by dholmes-ora** [comment]
I also don't see a "double negation" here - naming a flag DisableX is not in itself double-negation.

**Comment by tstuefe** [comment]
I also like the flag as it is. If "mitigation" bothers you, you could name it "DisableTHPStackFix" or similar".

**Comment by shipilev** [comment]
It was confusing at least for me, because I had to pause and think what exactly `-XX:-DisableTHPStackMitigation` would mean. It is disabling (`-`) the disablement (`Disable`) of the mitigation, so it actually enables it? And yes, I do dislike `Use*`, `Disable*` and `Enable*` prefixes for something that is already covered by binary `(+|-)` because of collisions like these.

In my opinion, `(+|-)IntelJccErratumMitigation` did it right, and we should follow that one.

**Comment by tstuefe** [comment]
Okay, sounds reasonable too. If you can convince David, I'm fine with either outcome. 

I know, not very helpful :-)

**Comment by dholmes-ora** [comment]
I understand how you see it this way but that is, I presume, because you read the +/- as enable/disable. But `+Foo` simply means "set Foo to true". `-Foo` means "set Foo to false". If you read it that way there is no confusion: `-DisableTHPStackMitigation` means `DisableTHPStackMitigation==false` ie we are not disabling the mitigation, hence it is enabled.

To me the use of Enable/Disable can convey additional information about the nature of the flag - if the flag is DisableX then I would expect X to normally be enabled but in some rare cases we may need to disable it, hence the flag conveys that. And yes you can abuse that by having the flag and the default value of the flag the wrong way around - such is life. To me if the flag is just X then it suggests, albeit there must be a default for X, that there is some ambivalence about whether X should be enabled or not - "hey X is enabled by default, but if you want to turn it off that's fine, your call."

I fully understand both points of view here, but there is plenty of precedence for using Use/Enable/Disable prefixes on flags. And Use in particular is far too entrenched to be displaced.

**Comment by stefank** [comment]
FWIW, I agree with Aleksey and I don't think we should be adding flags prefixed with Disable.

**Comment by tstuefe** [comment]
Note that the original name was already discussed a lot and went through several changes.

I am fine with whatever variant we come up (all alternatives sound sensible to me), but it would be good if we resolved that soon before starting to backport [JDK-8312182](https://github.com/openjdk/jdk/pull/14919).

**Comment by shipilev** [comment]
The current positions seem to be: strong "rename, dropping Disable" from me; "rename from Disable" from Stefan; "keep it" from David; "abstain" from Thomas. So while this _technically_ leans toward renaming, I don't think this overrides David's objection to the change. So unless somebody else puts in a strong position "for" or "against", or current folks change their positions, we are in a bind.

**Comment by dholmes-ora** [comment]
We've had some internal discussion and the general position is "no negative naming" and a preference I believe for "Use" as a prefix if a prefix is needed/desired. There will probably be a style-guide update proposed for the general case. So my objection is overridden and so withdrawn. :)

**Review by dholmes-ora — APPROVED** [review]

**Comment by shipilev** [comment]
> We've had some internal discussion and the general position is "no negative naming" and a preference I believe for "Use" as a prefix if a prefix is needed/desired. There will probably be a style-guide update proposed for the general case. So my objection is overridden and so withdrawn. :)

Thank you for initiating the discussion, and triggering the future style guide change. It was a long time coming :)

I am going to re-test this thing, while waiting for more approvals.

**Comment by dholmes-ora** [comment]
> Thank you for initiating the discussion, and triggering the future style guide change. It was a long time coming :)

Can't take the credit, that was @stefank .

**Review by tstuefe — APPROVED** [review]
Good.

Thanks to @dholmes-ora for resolving the discussions, I'm happy we agree.

**Comment by shipilev** [comment]
RISC-V GHA failure is the infrastructural one, to be fixed with another PR.
I think we are good with integrating this one.

/integrate

**Pull request closed without merging**
