### PR TITLE
8339162: [REDO] JDK-8338440 Parallel: Improve fragmentation mitigation in Full GC

### PR DESCRIPTION
**Pull request by albertnetymk**
This PR consists of two commits, the original and bug-fix.

The original patch calculates the dest-count for the preceding live words incorrectly -- `preceding_destination` can be on region-boundary.

Test: TEST=gc/TestSoftReferencesBehaviorOnOOME.java fails ~4/100 without the fix but passes with the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339162](https://bugs.openjdk.org/browse/JDK-8339162): [REDO] JDK-8338440 Parallel: Improve fragmentation mitigation in Full GC (**Enhancement** - P4)

### Reviewers
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**) Review applies to [fbba74ae](https://git.openjdk.org/jdk/pull/21872/files/fbba74aecfb4b40de2c89dca91cc6913186ab637)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - **Reviewer**) Review applies to [fbba74ae](https://git.openjdk.org/jdk/pull/21872/files/fbba74aecfb4b40de2c89dca91cc6913186ab637)
 * [Zhengyu Gu](https://openjdk.org/census#zgu) (@zhengyu123 - **Reviewer**)

### Contributors
 * Guoxiong Li `<gli@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21872/head:pull/21872` \
`$ git checkout pull/21872`

Update a local copy of the PR: \
`$ git checkout pull/21872` \
`$ git pull https://git.openjdk.org/jdk.git pull/21872/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21872`

View PR using the GUI difftool: \
`$ git pr show -t 21872`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21872.diff">https://git.openjdk.org/jdk/pull/21872.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21872#issuecomment-2454413108)
</details>

### CODE REVIEW

**Comment by albertnetymk** [comment]
@lgxbslgx @zhengyu123 @walulyai Could you take a look?

**Review by lgxbslgx — APPROVED** [review]
Looks good. Nice found. The `region_align_up`  is not the `next_region_start_address`.

**Comment by lgxbslgx** [comment]
> The `region_align_up` is not the `next_region_start_address`.

Even an experienced developer would misuse the function `region_align_up`, it may be good to add comment (in another PR?) to `region_align_up` to clarify its usage.

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
