### PR TITLE
8233557: [TESTBUG] DoubleClickTitleBarTest.java fails on macOs

### PR DESCRIPTION
**Pull request by alisenchung**
test passed, removing from ProblemList.txt

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8233557](https://bugs.openjdk.java.net/browse/JDK-8233557): [TESTBUG] DoubleClickTitleBarTest.java fails on macOs

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to 61c7e366bc6ca266c91af25f3c9eb2fa90385821

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6112/head:pull/6112` \
`$ git checkout pull/6112`

Update a local copy of the PR: \
`$ git checkout pull/6112` \
`$ git pull https://git.openjdk.java.net/jdk pull/6112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6112`

View PR using the GUI difftool: \
`$ git pr show -t 6112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6112.diff">https://git.openjdk.java.net/jdk/pull/6112.diff</a>

</details>

### CODE REVIEW

**Comment by prrace** [comment]
Was this verified in mach 5 ? How many times in a row did these tests pass ?

**Comment by prrace** [comment]
Was this verified in mach 5 ? How many times in a row did it pass ?

**Comment by alisenchung** [comment]
> Was this verified in mach 5 ? How many times in a row did it pass ?

The test passes

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
