### PR TITLE
JDK-8269571: NMT should print total malloc bytes and invocation count

### PR DESCRIPTION
**Pull request by tstuefe**
At the moment NMT prints a total of reserved and committed bytes. If one wants to know how much C-Heap the VM uses, one needs to add all numbers from the sub categories.

It would be helpful would NMT print the total number of malloced memory and additionally the malloc invocation count.

----

This patch modifes the printout to print, in addition to totals, the number of malloced bytes, malloc invocation counts, and number of mmap reserved/committed bytes. This mirrors the way we print individual sub categories and allocation sites.

Before:
```
Native Memory Tracking:

Total: reserved=18489703KB, committed=1183967KB
```

After:

```
Native Memory Tracking:

Total: reserved=18491726KB, committed=1183178KB
       malloc: 40590KB #13669
       mmap:   reserved=18451136KB, committed=1142588KB
```

Tests: Ran hotspot/runtime/NMT jtreg tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269571](https://bugs.openjdk.java.net/browse/JDK-8269571): NMT should print total malloc bytes and invocation count

### Reviewers
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)
 * [Xin Liu](https://openjdk.java.net/census#xliu) (@navyxliu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4622/head:pull/4622` \
`$ git checkout pull/4622`

Update a local copy of the PR: \
`$ git checkout pull/4622` \
`$ git pull https://git.openjdk.java.net/jdk pull/4622/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4622`

View PR using the GUI difftool: \
`$ git pr show -t 4622`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4622.diff">https://git.openjdk.java.net/jdk/pull/4622.diff</a>

</details>

### CODE REVIEW

**Review by zhengyu123 — APPROVED** [review]
Good to me.

**Comment by tstuefe** [comment]
Thank you @zhengyu123

**Comment by navyxliu** [comment]
your change looks good to me. 

>        malloc: 40590KB #13669
I think 13669 is the invocation count of malloc(). Out of curiosity, may I know how to use it?  Do you intend to use this to pinpoint memleak from malloc()?  A straight malloc() icount may not help much. Is it possible we can have the number of  unbalanced malloc()?  That is icount of malloc() minus icount of free(). of course, it is not directly related to this PR.

**Review by navyxliu — APPROVED** [review]

**Comment by tstuefe** [comment]
> your change looks good to me.
> 

Thanks!

> > ```
> >    malloc: 40590KB #13669
> > ```
> 
> I think 13669 is the invocation count of malloc(). Out of curiosity, may I know how to use it? Do you intend to use this to pinpoint memleak from malloc()? A straight malloc() icount may not help much. Is it possible we can have the number of unbalanced malloc()? That is icount of malloc() minus icount of free(). of course, it is not directly related to this PR.

That count is not the invocation counter (which can be useful too under certain conditions) but the number of outstanding allocations.

**Comment by navyxliu** [comment]
> > your change looks good to me.
> 
> Thanks!
> 
> > > ```
> > >    malloc: 40590KB #13669
> > > ```
> > 
> > 
> > I think 13669 is the invocation count of malloc(). Out of curiosity, may I know how to use it? Do you intend to use this to pinpoint memleak from malloc()? A straight malloc() icount may not help much. Is it possible we can have the number of unbalanced malloc()? That is icount of malloc() minus icount of free(). of course, it is not directly related to this PR.
> 
> That count is not the invocation counter (which can be useful too under certain conditions) but the number of outstanding allocations.
I see.  I take a look at mallocTracker.hpp. It's unbalanced count.

**Pull request closed without merging**
