### PR TITLE
8256497: Zero: enable G1 and Shenandoah GCs

### PR DESCRIPTION
**Pull request by shipilev**
Following the [JDK-8255796](https://bugs.openjdk.java.net/browse/JDK-8255796) improvement that ditched the inline contiguous alloc use from Zero, we can now rely on GC interface to hook the GCs properly. G1 and Shenandoah are a bit special here, because they require special `Reference.get` handling.

Note that it does not change the default GC for Zero, because Zero is implicitly `NeverActAsServerMachine`, which still selects Serial GC by default. After this change, Zero users can opt-in to G1 or Shenandoah.

Additional testing:
 - [x] Linux x86_64 Zero fastdebug `hotspot_gc_shenandoah` (some lingering failures about non-enabled compressed oops)
 - [x] Linux x86_64 Zero fastdebug `tier1` with `-XX:+UseG1GC`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8256497](https://bugs.openjdk.java.net/browse/JDK-8256497): Zero: enable G1 and Shenandoah GCs

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to c31db83cac0de8b44ece1d6c5173f7ea7f0e8566
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to debdd42c3710d6af10b50ddc6693143ad373e975
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1268/head:pull/1268`
`$ git checkout pull/1268`

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good to me! Thanks!

**Review by erikj79 — APPROVED** [review]
Build change looks ok.

**Review by magicus — APPROVED** [review]
Build changes look good.

**Comment by shipilev** [comment]
Thanks! By now I completed more thorough tests with Shenandoah, and those look fine.

/integrate

**Pull request closed without merging**
