### PR TITLE
8320280: RISC-V: Avoid passing t0 as temp register to MacroAssembler::lightweight_lock/unlock

### PR DESCRIPTION
**Pull request by zifeihan**
This is inspired by https://bugs.openjdk.org/browse/JDK-8316880.
MacroAssembler::lightweight_lock/unlock is non-trivial on linux-riscv64 platform. Passing t0(aka x5) as temporary register to these two assember functions can also be error prone. As a reserved scratch register, t0 is implicitly clobberred by various assembler functions. This fixes the issue by finding and passing a different register, which is similar with https://bugs.openjdk.org/browse/JDK-8316880.

### Testing:
- [x]  Run tier1-3 tests with qemu 8.1.50 (default locking mode) (release)
- [x]  Run non-trivial benchmark workloads (specjbb2005, dacapo, renaissance) with -XX:LockingMode=2 (fastdebug & release)
- [x] hotspot:tier4 on hifive unmatched (release)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320280](https://bugs.openjdk.org/browse/JDK-8320280): RISC-V: Avoid passing t0 as temp register to MacroAssembler::lightweight_lock/unlock (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [eccb82c9](https://git.openjdk.org/jdk/pull/16703/files/eccb82c9713fd6322abbcf1c8bb3168a1edaa8f2)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16703/head:pull/16703` \
`$ git checkout pull/16703`

Update a local copy of the PR: \
`$ git checkout pull/16703` \
`$ git pull https://git.openjdk.org/jdk.git pull/16703/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16703`

View PR using the GUI difftool: \
`$ git pr show -t 16703`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16703.diff">https://git.openjdk.org/jdk/pull/16703.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16703#issuecomment-1815659501)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good. Thanks for fixing this.

**Review by robehn — COMMENTED** [review]
Hi, thanks, looks good, but if 'temp'/'scratch' is not suppose to be t0, why not assert this in the 'callees' ?

E.g. in C2_MacroAssembler::fast_lock this assert:
assert_different_registers(oop, box, tmp, disp_hdr, t0); needs to updated with tmp3Reg.
Other 'callee' have no asserts.

**Comment by zifeihan** [comment]
> Hi, thanks, looks good, but if 'temp'/'scratch' is not suppose to be t0, why not assert this in the 'callees' ?
> 
> E.g. in C2_MacroAssembler::fast_lock this assert: assert_different_registers(oop, box, tmp, disp_hdr, t0); needs to updated with tmp3Reg. Other 'callee' have no asserts.

@robehn Thanks for your review, I have updated several assertions for calls to MacroAssembler::lightweight_lock/unlock.

**Comment by robehn** [comment]
Hi, thanks!

Sorry with calle I meant all methods that have cmpxchg in them, such
macroAssembler_riscv.cpp: MacroAssembler::lightweight_(un)lock
Where this assert is also assert_different_registers(obj, hdr, tmp1, tmp2);
So there are a couple of more, sorry.

There also a special cmpxchg_obj_header which still uses t0.
You want to fix that in this same PR?

**Comment by zifeihan** [comment]
> Hi, thanks!
> 
> Sorry with callee I meant all methods that have cmpxchg in them, such macroAssembler_riscv.cpp: MacroAssembler::lightweight_(un)lock Where this assert is also assert_different_registers(obj, hdr, tmp1, tmp2); So there are a couple of more, sorry.
> 
> There also a special cmpxchg_obj_header which still uses t0. You want to fix that in this same PR?

Hi @robehn, I am not sure if understand it correctly. Do you want me to revert my last comment and add `t0` in the list of `assert_different_registers` in MacroAssembler::lightweight_(un)lock? I think it might be better to handle the special case for cmpxchg_obj_header in another PR, is that OK for you?

**Comment by robehn** [comment]
> > Hi, thanks!
> > Sorry with callee I meant all methods that have cmpxchg in them, such macroAssembler_riscv.cpp: MacroAssembler::lightweight_(un)lock Where this assert is also assert_different_registers(obj, hdr, tmp1, tmp2); So there are a couple of more, sorry.
> > There also a special cmpxchg_obj_header which still uses t0. You want to fix that in this same PR?
> 
> Hi @robehn, I am not sure if understand it correctly. Do you want me to revert my last comment and add `t0` in the list of `assert_different_registers` in MacroAssembler::lightweight_(un)lock? I think it might be better to handle the special case for cmpxchg_obj_header in another PR, is that OK for you?

If you don't mind, just add t0 in those asserts. The other asserts are also useful for the reader to what is expected without needing to trace down the entire call chain, so no need to revert anything.

**Review by robehn — APPROVED** [review]
Looks good, thanks!

**Comment by zifeihan** [comment]
@RealFYang @robehn Thanks all for the review. 
/integrate

**Pull request closed without merging**
