### PR TITLE
8287726: Fix JVMTI tests with "requires vm.continuations" after JDK-8287496

### PR DESCRIPTION
**Pull request by shipilev**
[JDK-8287496](https://bugs.openjdk.java.net/browse/JDK-8287496) brought the alternative Loom implementation that can be used by ports as the fallback. That fallback does not support JVMTI entirely, so lots of tests fail. Some JVMTI is still supported, so cutting off at `@requires vm.jvmti` seems too broad. They should be predicated with `@requires vm.continuations` to be skipped when fallback is used.

This also allows reverting relevant x86_32 problemlist exclusions.

Additional testing:
 - [x] Linux x86_32 fastdebug, `serviceability/jvmti` works, many tests skipped
 - [x] Linux x86_64 fastdebug, `serviceability/jvmti` still works, with all current tests executing

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287726](https://bugs.openjdk.java.net/browse/JDK-8287726): Fix JVMTI tests with "requires vm.continuations" after JDK-8287496

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Robbin Ehn](https://openjdk.java.net/census#rehn) (@robehn - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8990/head:pull/8990` \
`$ git checkout pull/8990`

Update a local copy of the PR: \
`$ git checkout pull/8990` \
`$ git pull https://git.openjdk.java.net/jdk pull/8990/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8990`

View PR using the GUI difftool: \
`$ git pr show -t 8990`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8990.diff">https://git.openjdk.java.net/jdk/pull/8990.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
I expect you can unexclude the runtime/* tests from this section too.  Also the same section in test/jdk/ProblemList.txt that excludes the tests on x86_32 can be cleaned up too, maybe a separate PR.

**Comment by shipilev** [comment]
> I expect you can unexclude the runtime/* tests from this section too. Also the same section in test/jdk/ProblemList.txt that excludes the tests on x86_32 can be cleaned up too, maybe a separate PR.

Yes, in separate PR. In this PR, I want to deal with JVMTI tests specifically. We can take JVMTI tests off the problemlist exactly because of `@requires vm.continuations` added in this PR.

**Review by robehn — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]

**Comment by shipilev** [comment]
Trivial, or? I would like to have this integrated sooner to clean up our testing.

**Comment by robehn** [comment]
> Trivial, or? I would like to have this integrated sooner to clean up our testing.

Ship it under trivial, thanks.

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
