### PR TITLE
JDK-8302810: NMT gtests don't correctly check for marked ranges

### PR DESCRIPTION
**Pull request by tstuefe**
We have the helper functions `GtestUtils::mark_range` and `GtestUtils::check_range`. One fills a range with a byte pattern, and the other checks that range.

The latter does not assert - it just returns a boolean value. But its name implies it does, in fact, assert (as similar check_... functions in hotspot).

It is used without ASSERT_TRUE or EXPECT_TRUE in several places, which makes these tests ignore errors. This caused https://bugs.openjdk.org/browse/JDK-8302811 to be hidden.

----

Patch adds the necessary assertions (EXPECT_, in this case, since its used in a non-void subfunction).

It also renames `GtestUtils::check_range` to `GtestUtils::is_range_checked`, which more clearly indicates that it returns a boolean value and won't assert on itself.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302810](https://bugs.openjdk.org/browse/JDK-8302810): NMT gtests don't correctly check for marked ranges

### Reviewers
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - Committer) ⚠️ Review applies to [5a69a5fe](https://git.openjdk.org/jdk/pull/12629/files/5a69a5fe19aa21382b3af78dbdbcfe8b4630997b)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12629/head:pull/12629` \
`$ git checkout pull/12629`

Update a local copy of the PR: \
`$ git checkout pull/12629` \
`$ git pull https://git.openjdk.org/jdk pull/12629/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12629`

View PR using the GUI difftool: \
`$ git pr show -t 12629`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12629.diff">https://git.openjdk.org/jdk/pull/12629.diff</a>

</details>

### CODE REVIEW

**Review by gerard-ziemski — APPROVED** [review]
LGTM, thank you for fixing this.

**Review by dholmes-ora — APPROVED** [review]
Seems fine. Thanks

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Just noticed the test are failing with this change.

**Comment by tstuefe** [comment]
> Just noticed the test are failing with this change.

Should be fixed with 8302811, I'll re-run the tests.

**Comment by tstuefe** [comment]
> LGTM, thank you for fixing this.

Thanks, Gerard!

**Review by dholmes-ora — APPROVED** [review]
Seems fine now. Thanks.

**Pull request closed without merging**
