### PR TITLE
8293041: --disable-@files option doesn't work and cause an error

### PR DESCRIPTION
**Pull request by asotona**
Option --disable-@files is passed to VM option causing it to fail.
Proposed patch skips --disable-@files option in src/java.base/share/native/libjli/java.c ParseArguments processing, so it is not passed to the VM.
The patch also adds relevant test to ArgsFileTest.

Please review.

Thank you,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293041](https://bugs.openjdk.org/browse/JDK-8293041): --disable-@files option doesn't work and cause an error

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11183/head:pull/11183` \
`$ git checkout pull/11183`

Update a local copy of the PR: \
`$ git checkout pull/11183` \
`$ git pull https://git.openjdk.org/jdk pull/11183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11183`

View PR using the GUI difftool: \
`$ git pr show -t 11183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11183.diff">https://git.openjdk.org/jdk/pull/11183.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
Are you sure this is right place to do this? There are other "launcher options" that aren't passed through to CreateJavaVM and I'm surprised this one is.

**Comment by AlanBateman** [comment]
> Alternate suggestions are welcome, or link to relevant documentation, or an example of another filtered option.

I think I would start in ParseArguments (libjli/java.c) to see the options that are handled, translated, or passed through. I can't be 100% sure how this one should be handled without studying it more closely.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
As far as I can see @-file processing is a launcher feature, including the expansion of JDK_JAVA_OPTIONS, so it should never be getting passed through to the VM in the first place.

What I can't figure out is how the test tools/launcher/ArgsFileTest.java is working when the JVM won't start with that flag on the command-line ??

**Comment by dholmes-ora** [comment]
BTW for future reference for the test case we are no longer creating tests using the bug id as a directory, instead tests should be groups into functional areas. Thanks.

I was also surprised to see the i8N changes here as I thought that was normally handled seperately.

**Comment by asotona** [comment]
@dholmes-ora and @AlanBateman thanks for pointing me to the right place for the fix.

tools/launcher/ArgsFileTest.java was working because it didn't contain any test with --disable-@files option verifying VM really starts

**Review by AlanBateman — APPROVED** [review]
Good to see that this turned out to a simple change.

**Comment by dholmes-ora** [comment]
> tools/launcher/ArgsFileTest.java was working because it didn't contain any test with --disable-@files option verifying VM really starts

What about the  killswitch test ??

**Comment by asotona** [comment]
> > tools/launcher/ArgsFileTest.java was working because it didn't contain any test with --disable-@files option verifying VM really starts
> 
> What about the killswitch test ??

KillSwitch test did not construct valid command line, it didn't expect VM to start correctly and so it didn't test the VM exit value. KillSwitch test just checked expanded options presence in the debug log (before passing to ParseArguments). 
I've added one simple test composing valid cmd line 'java --disable-@files --version' and verifying successful VM execution.

**Pull request closed without merging**
