### PR TITLE
8269962: SA has unused Hashtable, Dictionary classes

### PR DESCRIPTION
**Pull request by coleenp**
See bug for more details. This code is unused and is soon going to be not in hotspot.
I left in logBytesPerWord() from my previous change because it might be useful in the SA.  I could remove it if opinion warrants.
Ran tier1-3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269962](https://bugs.openjdk.java.net/browse/JDK-8269962): SA has unused Hashtable, Dictionary classes

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4708/head:pull/4708` \
`$ git checkout pull/4708`

Update a local copy of the PR: \
`$ git checkout pull/4708` \
`$ git pull https://git.openjdk.java.net/jdk pull/4708/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4708`

View PR using the GUI difftool: \
`$ git pr show -t 4708`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4708.diff">https://git.openjdk.java.net/jdk/pull/4708.diff</a>

</details>

### CODE REVIEW

**Comment by coleenp** [comment]
I also removed BinaryTreeDictionary left over from Metaspace and CMS.

**Review by plummercj — APPROVED** [review]
Nice cleanup!

**Comment by coleenp** [comment]
Thank you so much Chris.  I was going to send you a note so you'd see this!

**Review by iklam — APPROVED** [review]
LGTM. Thanks for the cleanup.

**Review by dholmes-ora — APPROVED** [review]
LGTM too.

Thanks,
David

**Comment by coleenp** [comment]
Thanks Ioi and David.
/integrate

**Pull request closed without merging**
