### PR TITLE
8310105: LoongArch64 builds are broken after JDK-8304913

### PR DESCRIPTION
**Pull request by theaoqi**
LoongArch64 Zero builds are broken after [JDK-8304913](https://bugs.openjdk.org/browse/JDK-8304913):
```
jdk.tools.jlink.plugin.PluginException: ModuleTarget is malformed: No enum constant jdk.internal.util.Architecture.LOONGARCH64
at jdk.jlink/jdk.tools.jlink.builder.DefaultImageBuilder.storeFiles(DefaultImageBuilder.java:181)
at jdk.jlink/jdk.tools.jlink.internal.ImagePluginStack.storeFiles(ImagePluginStack.java:486)
at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.writeImage(ImageFileCreator.java:168)
at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.create(ImageFileCreator.java:100)
at jdk.jlink/jdk.tools.jlink.internal.JlinkTask$ImageHelper.retrieve(JlinkTask.java:860)
at jdk.jlink/jdk.tools.jlink.internal.ImagePluginStack.operate(ImagePluginStack.java:194)
at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:423)
at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:286)
at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)
Error: jdk.tools.jlink.plugin.PluginException: ModuleTarget is malformed: No enum constant jdk.internal.util.Architecture.LOONGARCH64
```

Builds tested: LoongArch64 Zero, both release and fastdebug.

If this patch conflicts with #14471, I will rebase after #14471 is integrated.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310105](https://bugs.openjdk.org/browse/JDK-8310105): LoongArch64 builds are broken after JDK-8304913 (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14482/head:pull/14482` \
`$ git checkout pull/14482`

Update a local copy of the PR: \
`$ git checkout pull/14482` \
`$ git pull https://git.openjdk.org/jdk.git pull/14482/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14482`

View PR using the GUI difftool: \
`$ git pr show -t 14482`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14482.diff">https://git.openjdk.org/jdk/pull/14482.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14482#issuecomment-1592350510)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks okay, thanks!

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Pull request closed without merging**
