### PR TITLE
JDK-8225013: sanity/client/SwingSet/src/ScrollPaneDemoTest.java fails on Linux

### PR DESCRIPTION
**Pull request by shurymury**
Before the fix the test was failing around 1 time in fifty runs. After the fix the test did not fail in ~ 1k runs.
Additional instrumentation is added to save useful information on the UI state, should the failure happen again.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8225013](https://bugs.openjdk.java.net/browse/JDK-8225013): sanity/client/SwingSet/src/ScrollPaneDemoTest.java fails on Linux

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8848/head:pull/8848` \
`$ git checkout pull/8848`

Update a local copy of the PR: \
`$ git checkout pull/8848` \
`$ git pull https://git.openjdk.java.net/jdk pull/8848/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8848`

View PR using the GUI difftool: \
`$ git pr show -t 8848`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8848.diff">https://git.openjdk.java.net/jdk/pull/8848.diff</a>

</details>

### CODE REVIEW

**Comment by shurymury** [comment]
@prrace @lawrence-andrew , can you take a look?

**Comment by prrace** [comment]
I don't know anything about Jemmy, so I have no idea what these changes do.
Importantly I can't tell what you've done which makes the test stable and why.
Can you explain both the problem and the solution ?

**Comment by shurymury** [comment]
> Can you explain both the problem and the solution ?

From what I have observed, the test starts before the window is painted. The window is basically gray. My hypothesis is then that it takes time to load the background image and the test starts before that.

So the fix is to wait for the image to be loaded. To do that I find the label (by description of the icon) and wait for getImageLoadStatus() == MediaTracker.COMPLETE of that icon.

Additionally, after the image is loaded, I capture an image of the screen and also save UI state in an xml file. Should the test fail again, there will hopefully be more information available.

**Comment by lawrence-andrew** [comment]
LGTM

**Review by prrace — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
