### PR TITLE
8324755: Enable parallelism in vmTestbase/gc/gctests/LargeObjects tests

### PR DESCRIPTION
**Pull request by roy-soumadipta**
The commit includes changes to unblock parallelism in vmTestbase/gc/gctests/LargeObjects tests.

Below are the before and after run comparisons on AL2:
```
# Fastdebug
before: 7985.84s user 417.77s system 498% cpu 28:06.25 total
after: 2503.22s user 48.65s system 606% cpu 7:00.69 total

# Release
before: 1063.25s user 45.87s system 125% cpu 14:42.10 total
after: 1077.70s user 45.71s system 481% cpu 3:53.28 total
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8324755](https://bugs.openjdk.org/browse/JDK-8324755): Enable parallelism in vmTestbase/gc/gctests/LargeObjects tests (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18798/head:pull/18798` \
`$ git checkout pull/18798`

Update a local copy of the PR: \
`$ git checkout pull/18798` \
`$ git pull https://git.openjdk.org/jdk.git pull/18798/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18798`

View PR using the GUI difftool: \
`$ git pr show -t 18798`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18798.diff">https://git.openjdk.org/jdk/pull/18798.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18798#issuecomment-2058950002)

### CODE REVIEW

**Comment by roy-soumadipta** [comment]
https://github.com/roy-soumadipta/jdk-jtreg-optimizations/actions/runs/8705334719 is running not sure why hasn't it auto reflected here yet.

**Review by shipilev — APPROVED** [review]
Looks fine to me. @lmesnik should also approve.

/reviewers 2

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
