### PR TITLE
8330625: Compilation memory statistic: prevent tearing of the final report

### PR DESCRIPTION
**Pull request by tstuefe**
Somewhat trivial change to reduce the chance of tearing the final compilation cost history report. See JBS for details.

---

The patch:
- upon end of a compilation, we print the the offending log line and account the cost in the compilation cost history table. For the latter we lock over NMTCompilationCostHistory_lock. The patch swaps these two actions such that we print after pulling the lock. That greatly reduces, albeit not completely removes, the chance of printing log lines into the final report. (I did not want to widen the scope of that lock to include the printout)
- also moves the locking of NMTCompilationCostHistory_lock  up to the start of the reporting function to include printing the report header into the locking

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330625](https://bugs.openjdk.org/browse/JDK-8330625): Compilation memory statistic: prevent tearing of the final report (**Bug** - P5)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [92049dda](https://git.openjdk.org/jdk/pull/18866/files/92049dda729807021de785675f31cdc05dc08867)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18866/head:pull/18866` \
`$ git checkout pull/18866`

Update a local copy of the PR: \
`$ git checkout pull/18866` \
`$ git pull https://git.openjdk.org/jdk.git pull/18866/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18866`

View PR using the GUI difftool: \
`$ git pr show -t 18866`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18866.diff">https://git.openjdk.org/jdk/pull/18866.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18866#issuecomment-2069092137)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

What kind of testing you do for changes in this code?

**Comment by tstuefe** [comment]
> Good.
>

Thank you, Vladimir 

> What kind of testing you do for changes in this code?

Beside the GHAs, I added report printing at random intervals (so, not at shutdown) and saw with my patch a much reduced rate of tearing. The remaining tears come from the fact that the log line https://github.com/openjdk/jdk/blob/58bf813f3d60fe7bde734df68c64dbf12be01250/src/hotspot/share/compiler/compilationMemoryStatistic.cpp#L434 is printed outside the log scope still, so if report printing commences exactly at this point ( https://github.com/openjdk/jdk/blob/58bf813f3d60fe7bde734df68c64dbf12be01250/src/hotspot/share/compiler/compilationMemoryStatistic.cpp#L430), we still see the log line in middle of the report. I don't want to move the compiler log line into lock scope however since I don't want compiler threads to wait for each other after compilation. I also did not want to overcomplicate the patch.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by tstuefe** [comment]
Thanks @vnkozlov and @TobiHartmann !

/integrate

**Pull request closed without merging**
