### PR TITLE
8255367: C2: Deoptimization during vector box construction is broken

### PR DESCRIPTION
**Pull request by iwanowww**
Vector box allocation is a multi-step process: it involves 2 allocations (typed vector instance + primitive array) and 2 initializing stores (vector value store into primitive array and field initialization in typed vector instance). If deoptimization happens at any of the aforementioned allocation points the result is broken: either wrong instance is put on stack (primitive array instead of typed vector) or vector initializing store is missing.

There are 2 ways to fix the problem: 
- piggy-back on rematerialization;
- reexecute the bytecode which allocates the instance.

I chose the latter option because it's simpler to implement. (Rematerialization requires some adjustment of JVM state associated with each allocation to record vector type and value.) 

The downside is there shouldn't be any side effects present. It's not a problem right now, because boxing happens only at vector intrinsics use sites and the only intrinsic which has any side effects is vector store operation (it doesn't produce vectors, hence, no boxing needed).

The actual fix is small: adding `PreserveReexecuteState` in `LibraryCallKit::box_vector` is enough for the problem to go away. The rest is cleanups/refactorings.

Testing:
- [x] jdk/incubator/vector tests w/ -XX:+DeoptimizeALot & -XX:UseAVX={3,2,1,0}
- [ ] hs-precheckin-comp, hs-tier1, hs-tier2

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255367](https://bugs.openjdk.java.net/browse/JDK-8255367): C2: Deoptimization during vector box construction is broken

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to f13f72850916111822d56eca0c1701841e9dddaa
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1126/head:pull/1126`
`$ git checkout pull/1126`

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by iwanowww** [comment]
Thanks for the review, Tobias.

**Review by vnkozlov — APPROVED** [review]
Good.

The only concern with such approach is that array could be allocated twice if deoptimization happens during Vector object allocation (after compiled code allocated array). We saw some JVMTI issues with Graal which too does reallocation in some cases during deoptimization.

**Pull request closed without merging**
