### PR TITLE
8319522: Consolidate heap dump writer and other utilities

### PR DESCRIPTION
**Pull request by y1yang0**
Move heap dump writer to heapdumpcompression.hpp and rename it to heapdumpwriter.hpp so that all heapdump utilities appears in the same file. A further refactor is remove AbstractDumpWriter and use DumpWriter directly.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with updated jcheck configuration in pull request)

### Issue
 * [JDK-8319522](https://bugs.openjdk.org/browse/JDK-8319522): Consolidate heap dump writer and other utilities (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16520/head:pull/16520` \
`$ git checkout pull/16520`

Update a local copy of the PR: \
`$ git checkout pull/16520` \
`$ git pull https://git.openjdk.org/jdk.git pull/16520/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16520`

View PR using the GUI difftool: \
`$ git pr show -t 16520`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16520.diff">https://git.openjdk.org/jdk/pull/16520.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16520#issuecomment-1794586518)

### CODE REVIEW

**Comment by shipilev** [comment]
Let me ask/suggest we do not this until most of the in-flight heap dump improvements are delivered. (For example, #16545). This would simplify the backports to previous JDK releases. Let's do this refactoring in early JDK 23?

**Comment by y1yang0** [comment]
> Let me ask/suggest we do not this until most of the in-flight heap dump improvements are delivered. (For example, #16545). This would simplify the backports to previous JDK releases. Let's do this refactoring in early JDK 23?

Okay

**Comment by y1yang0** [comment]
Can I have a review for this?

**Pull request closed without merging**
