### PR TITLE
8279068: IGV: Update to work with JDK 16 and 17

### PR DESCRIPTION
**Pull request by robcasloz**
This change upgrades the NetBeans Platform on which IGV is based to its latest version ([12.6](https://netbeans.apache.org/download/nb126/index.html)). The upgrade introduces support for JDK versions 16 and 17, and drops support for versions earlier than 11. The change adds a check to enforce that a supported JDK version is used when building IGV, emitting an informative error message otherwise.

#### Testing

Tested the following use cases manually on all combinations of (Linux, Windows, macOS) and (JDK 11, JDK 16, JDK 17):

- build
- open graph file (small.xml in [test-input.zip](https://bugs.openjdk.java.net/secure/attachment/93988/test-input.zip))
- import graphs via network (localhost)
- expand groups in outline
- open a graph
- open a clone
- zoom in and out
- search a node
- apply filters
- extract a node
- show all nodes
- select nodes corresponding to a bytecode
- view control flow
- select nodes corresponding to a basic block
- cluster nodes
- show satellite view
- compute the difference of two graphs
- change node text
- export graph as PDF
- remove a group
- save groups into a file
- open a large graph file (large.xml in [test-input.zip](https://bugs.openjdk.java.net/secure/attachment/93988/test-input.zip))
- open a large graph ("After Escape Analysis" in large.xml)

Also tested that building IGV on JDK 8 and 18 (EA) fails with the error message "IGV requires a JDK version between 11 and 17".

Thanks to Jesper Wilhelmsson for helping with testing on macOS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279068](https://bugs.openjdk.java.net/browse/JDK-8279068): IGV: Update to work with JDK 16 and 17

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7347/head:pull/7347` \
`$ git checkout pull/7347`

Update a local copy of the PR: \
`$ git checkout pull/7347` \
`$ git pull https://git.openjdk.java.net/jdk pull/7347/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7347`

View PR using the GUI difftool: \
`$ git pr show -t 7347`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7347.diff">https://git.openjdk.java.net/jdk/pull/7347.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by robcasloz** [comment]
Thanks for reviewing, Vladimir and Nils!

**Review by chhagedorn — APPROVED** [review]
Nice update!

**Pull request closed without merging**
