### PR TITLE
8334287: Man page update for jstatd deprecation

### PR DESCRIPTION
**Pull request by kevinjwalls**
Man page update for JDK-8327793 which marked jstatd as deprecated for removal in JDK 24.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334287](https://bugs.openjdk.org/browse/JDK-8334287): Man page update for jstatd deprecation (**Enhancement** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19829/head:pull/19829` \
`$ git checkout pull/19829`

Update a local copy of the PR: \
`$ git checkout pull/19829` \
`$ git pull https://git.openjdk.org/jdk.git pull/19829/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19829`

View PR using the GUI difftool: \
`$ git pr show -t 19829`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19829.diff">https://git.openjdk.org/jdk/pull/19829.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19829#issuecomment-2182835351)

### CODE REVIEW

**Comment by kevinjwalls** [comment]
The updated man page looks like:

```
JSTATD(1)                                                             JDK Commands                                                            JSTATD(1)

NAME
       jstatd - monitor the creation and termination of instrumented Java HotSpot VMs

SYNOPSIS
       WARNING: This command is deprecated and will be removed in a future release.

       Note: This command is experimental and unsupported.

       jstatd [options]
...etc...	   
```

**Comment by AlanBateman** [comment]
I assume we should hold off reviewing until the warning and the experiment note are combined.

**Review by dholmes-ora — COMMENTED** [review]
Sorry this got left "pending" yesterday

**Comment by kevinjwalls** [comment]
Thanks Alan and David, moving to a single line:

```
JSTATD(1)                                                             JDK Commands                                                            JSTATD(1)

NAME
       jstatd - monitor the creation and termination of instrumented Java HotSpot VMs

SYNOPSIS
       WARNING: This command is experimental, unsupported, and deprecated.  It will be removed in a future release.

       jstatd [options]
```

**Review by AlanBateman — APPROVED** [review]

**Comment by kevinjwalls** [comment]
Thanks Alan and David for the comments.

**Pull request closed without merging**
