### PR TITLE
8262001: java/lang/management/ThreadMXBean/ResetPeakThreadCount.java failed with "RuntimeException: Current Peak = 14 Expected to be == previous peak = 7 + 8"

### PR DESCRIPTION
**Pull request by alexmenkov**
The fix updates ResetPeakThreadCount.java test - increases number of threads, but relaxes conditions so start/termination of system threads don't cause failures.
Additional changes:
- store threads in a list instead of array (we need only to start/terminate some number of threads, so linked list works better);
- flags for thread termination are moved to thread class;
- store values from ThreadMXBean.getPeakThreadCount() and getThreadCount() in int instead of long (the methods return int values)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262001](https://bugs.openjdk.java.net/browse/JDK-8262001): java/lang/management/ThreadMXBean/ResetPeakThreadCount.java failed with "RuntimeException: Current Peak = 14 Expected to be == previous peak = 7 + 8"

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 8252f4bc8bb553d96047bf8ef4ddfe08f1497069
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to 8252f4bc8bb553d96047bf8ef4ddfe08f1497069

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/2885/head:pull/2885`
`$ git checkout pull/2885`

To update a local copy of the PR:
`$ git checkout pull/2885`
`$ git pull https://git.openjdk.java.net/jdk pull/2885/head`

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
This looks like a good cleanup to me. Please wait for a review from someone from serviceability-dev before pushing.

**Review by sspitsyn — APPROVED** [review]
Alex,
This looks good to me.
Nit:
The line needs a dot (was missed in the original code):
`+    // The MyThread thread lives as long as correspondent its live value is true`

Thanks,
Serguei

**Pull request closed without merging**
