### PR TITLE
8159979: During initial mark, preparing all regions for marking may take a significant amount of time

### PR DESCRIPTION
**Pull request by walulyai**
Hi all,

Please review this change to move the work done during preparation for a concurrent mark start (pre_concurrent_start) into a G1BatchedGangTask.

Testing: Tier 1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8159979](https://bugs.openjdk.java.net/browse/JDK-8159979): During initial mark, preparing all regions for marking may take a significant amount of time

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5302/head:pull/5302` \
`$ git checkout pull/5302`

Update a local copy of the PR: \
`$ git checkout pull/5302` \
`$ git pull https://git.openjdk.java.net/jdk pull/5302/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5302`

View PR using the GUI difftool: \
`$ git pr show -t 5302`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5302.diff">https://git.openjdk.java.net/jdk/pull/5302.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — CHANGES_REQUESTED** [review]
The new log messages should be added to TestGCLogMessages.java.

**Review by tschatzl — APPROVED** [review]
Since I'm messing around with the TestGCLogMessages.java test anyway currently, I'll add the two messages in https://github.com/openjdk/jdk/pull/5306.

**Review by albertnetymk — APPROVED** [review]

**Comment by walulyai** [comment]
Thanks for the reviews!

/integrate

**Comment by DamonFool** [comment]
One test fails after this integration: https://github.com/openjdk/jdk/pull/5322

**Pull request closed without merging**
