### PR TITLE
8299226: compiler/profiling/TestTypeProfiling.java: make it not throw if C2 is not enabled.

### PR DESCRIPTION
**Pull request by ikorennoy**
Changing RuntimeException to SkippedException when TieredStopAtLevel < 4.

The main part of this problem was done in [JDK-8226795](https://bugs.openjdk.org/browse/JDK-8226795) but for some reason, the exception was not changed.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299226](https://bugs.openjdk.org/browse/JDK-8299226): compiler/profiling/TestTypeProfiling.java: make it not throw if C2 is not enabled.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12981/head:pull/12981` \
`$ git checkout pull/12981`

Update a local copy of the PR: \
`$ git checkout pull/12981` \
`$ git pull https://git.openjdk.org/jdk.git pull/12981/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12981`

View PR using the GUI difftool: \
`$ git pr show -t 12981`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12981.diff">https://git.openjdk.org/jdk/pull/12981.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12981#issuecomment-1464356874)

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Did you tried to reproduce the issue described in the bug?

JDK-8226795 fix added jtreg's commands `@requires` which will not allow to run without C2. I tried:
```
Test results: no tests selected
```
Also `Platform` and `TIERED_*` checks in `main()` methods are useless and can be removed after JDK-8226795 changes.

**Comment by ikorennoy** [comment]
Yes, I tried to reproduce the issue, it didn't reproduce for me either.

Initially, I thought about removing these checks, but then I decided that there would be less diff and the code would be the same as in other tests that use similar checks.

I am not familiar with OpenJDK development processes, but if it's possible within this PR, I can remove the checks code from this test and from other similar tests: Level2RecompilationTest.java OSRFailureLevel4Test.java.

**Comment by ikorennoy** [comment]
I looked again at the Level2RecompilationTest and OSRFailureLevel4Test and it seems that I was wrong in these tests the checks in `main()` are different.

So, it only needs to remove the checks from TestTypeProfiling.

**Comment by vnkozlov** [comment]
@ikorennoy, I added comment with question to Evgeny about how he hit the issue so we can reproduce it.
These tests can't be run without JTREG which filter them. Based on his answer we either close bug as not issue or try to find why filtering does not work in his configuration.

If you want to look to do clean to remove unneeded checks and simplify `@requires` I would suggest to file a separate RFE.

**Comment by ikorennoy** [comment]
@vnkozlov seems like there are no updates in Jira. What can we do now?

**Comment by vnkozlov** [comment]
@ikorennoy I added new comment in Jira. I am suggesting to close this issue if we don't get answer in few days.

**Comment by vnkozlov** [comment]
@ikorennoy  Evgeny closed bug so you can withdraw this PR.

**Comment by ikorennoy** [comment]
@vnkozlov thank you for your help!

**Pull request closed without merging**
