### PR TITLE
8282240: Add _name field to Method for NOT_PRODUCT only

### PR DESCRIPTION
**Pull request by coleenp**
Whenever I'm debugging I really wish I knew the name of the method that I'm looking at, so I added this field in not-product.
Tested with tier1 on Oracle platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282240](https://bugs.openjdk.java.net/browse/JDK-8282240): Add _name field to Method for NOT_PRODUCT only

### Reviewers
 * [Patricio Chilano Mateo](https://openjdk.java.net/census#pchilanomate) (@pchilano - **Reviewer**)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7608/head:pull/7608` \
`$ git checkout pull/7608`

Update a local copy of the PR: \
`$ git checkout pull/7608` \
`$ git pull https://git.openjdk.java.net/jdk pull/7608/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7608`

View PR using the GUI difftool: \
`$ git pr show -t 7608`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7608.diff">https://git.openjdk.java.net/jdk/pull/7608.diff</a>

</details>

### CODE REVIEW

**Review by pchilano — APPROVED** [review]
Hi Coleen,

Looks good to me. I see we also call set_constants() and set_name_index() from VM_RedefineClasses::set_new_constant_pool(), do we need to set the name in there too or it's not needed?

Thanks,
Patricio

**Review by hseigel — APPROVED** [review]
Changes look good!
Thanks, Harold

**Comment by coleenp** [comment]
Hi Patricio,  In the RedefineClasses case, the methods already have the _name field set.  But your comment pointed out the fragility of this change, so I changed it.  Hope this one is better.   Please re-review.
Harold, can you re-review also?

**Review by hseigel — APPROVED** [review]
Still looks good!
Harold

**Review by pchilano — APPROVED** [review]
Still good!

Thanks,
Patricio

**Comment by coleenp** [comment]
Thanks Patricio and Harold.  With this fix (needed to walk new field for CDS), the new test passes on all platforms.

**Review by pchilano — APPROVED** [review]
Adding that test case was a good idea :) 
Looks good!

Thanks,
Patricio

**Review by hseigel — APPROVED** [review]
Looks good!  Harold

**Comment by coleenp** [comment]
Thanks Harold and Patricio!
/integrate

**Pull request closed without merging**
