### PR TITLE
JDK-8151531: Add notes to BaseStream.spliterator/iterator docs regarding them being escape hatches

### PR DESCRIPTION
**Pull request by viktorklang-ora**
Still relevant to address? /cc @PaulSandoz

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8151531](https://bugs.openjdk.org/browse/JDK-8151531): Add notes to BaseStream.spliterator/iterator docs regarding them being escape hatches

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13890/head:pull/13890` \
`$ git checkout pull/13890`

Update a local copy of the PR: \
`$ git checkout pull/13890` \
`$ git pull https://git.openjdk.org/jdk.git pull/13890/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13890`

View PR using the GUI difftool: \
`$ git pr show -t 13890`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13890.diff">https://git.openjdk.org/jdk/pull/13890.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13890#issuecomment-1540468779)

### CODE REVIEW

**Comment by viktorklang-ora** [comment]
@PaulSandoz Makes a lot of sense. Done.

**Review by PaulSandoz — APPROVED** [review]

**Pull request closed without merging**
