### PR TITLE
8321003: RISC-V: C2 MulReductionVI

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this patch to implement MulReductionVI/MulReductionVL/MulReductionVF/MulReductionVD?
On riscv, there is no straightforward instructions to do it, but we can do it with a reduction tree, which could reduce the time complexity to lg(N).
Thanks

## Performance
TBD

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8321003](https://bugs.openjdk.org/browse/JDK-8321003): RISC-V: C2 MulReductionVI (**Sub-task** - P4)
 * [JDK-8321004](https://bugs.openjdk.org/browse/JDK-8321004): RISC-V: C2 MulReductionVL (**Sub-task** - P4)
 * [JDK-8321005](https://bugs.openjdk.org/browse/JDK-8321005): RISC-V: C2 MulReductionVF (**Sub-task** - P4)
 * [JDK-8321006](https://bugs.openjdk.org/browse/JDK-8321006): RISC-V: C2 MulReductionVD (**Sub-task** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19015/head:pull/19015` \
`$ git checkout pull/19015`

Update a local copy of the PR: \
`$ git checkout pull/19015` \
`$ git pull https://git.openjdk.org/jdk.git pull/19015/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19015`

View PR using the GUI difftool: \
`$ git pr show -t 19015`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19015.diff">https://git.openjdk.org/jdk/pull/19015.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19015#issuecomment-2084868034)

### CODE REVIEW

**Comment by Hamlin-Li** [comment]
in progress...

**Comment by robehn** [comment]
Can you convert to draft please?

**Comment by Hamlin-Li** [comment]
> Can you convert to draft please?

Thanks for the tip.

**Pull request closed without merging**
