### PR TITLE
JDK-8296403: [TESTBUG] IR test runner methods in TestLongRangeChecks.java invoke wrong test methods

### PR DESCRIPTION
**Pull request by dafedafe**
The `testStrideNegScalePosInIntLoop2` and `testStridePosScaleNegInIntLoop2` tests of the IR test _TestLongRangeChecks.java_ invoke the wrong test methods.

Changing the test method calls to invoke the right ones.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296403](https://bugs.openjdk.org/browse/JDK-8296403): [TESTBUG] IR test runner methods in TestLongRangeChecks.java invoke wrong test methods

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [da08bbc0](https://git.openjdk.org/jdk/pull/12088/files/da08bbc0c8fea74fb76a65caddfcecc14ab4918e)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [da08bbc0](https://git.openjdk.org/jdk/pull/12088/files/da08bbc0c8fea74fb76a65caddfcecc14ab4918e)
 * [Jie Fu](https://openjdk.org/census#jiefu) (@DamonFool - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12088/head:pull/12088` \
`$ git checkout pull/12088`

Update a local copy of the PR: \
`$ git checkout pull/12088` \
`$ git pull https://git.openjdk.org/jdk pull/12088/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12088`

View PR using the GUI difftool: \
`$ git pr show -t 12088`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12088.diff">https://git.openjdk.org/jdk/pull/12088.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good and trivial.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by DamonFool** [comment]
It would be better to update the copyright year.

**Comment by dafedafe** [comment]
@DamonFool thanks for the hint: I added the Oracle copyright line.

**Review by DamonFool — APPROVED** [review]
Thanks for the update.
Looks good to me too.

**Comment by dafedafe** [comment]
@TobiHartmann @chhagedorn @DamonFool thanks for your reviews!

**Pull request closed without merging**
