### PR TITLE
8262503: Support records in Dynalink

### PR DESCRIPTION
**Pull request by szegedi**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262503](https://bugs.openjdk.java.net/browse/JDK-8262503): Support records in Dynalink

### Reviewers
 * [Athijegannathan Sundararajan](https://openjdk.java.net/census#sundar) (@sundararajana - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2767/head:pull/2767` \
`$ git checkout pull/2767`

Update a local copy of the PR: \
`$ git checkout pull/2767` \
`$ git pull https://git.openjdk.java.net/jdk pull/2767/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2767`

View PR using the GUI difftool: \
`$ git pr show -t 2767`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2767.diff">https://git.openjdk.java.net/jdk/pull/2767.diff</a>

</details>

### CODE REVIEW

**Review by sundararajana — APPROVED** [review]
Looks good

**Comment by szegedi** [comment]
Thank you for the review, @sundararajana!

**Pull request closed without merging**
