### PR TITLE
Intrinsifications of String.hashCode

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

This patch implements intrinsifications for `StringLatin1.hashCode` and `StringUTF16.hashCode` by using vector operations on supporting hardware. The patch uses existing vector nodes to generate desired machine instructions.
The benchmark results below are from a modified version of the existing `org/openjdk/bench/java/lang/StringHashCode.java` that covers hash code computation measurements.

Thank you very much.

    Before:
    Benchmark                      (length)  Mode  Cnt    Score   Error  Units
    StringHashCode.uncachedLatin1         1  avgt   25    3.248 ± 0.042  ns/op
    StringHashCode.uncachedLatin1         3  avgt   25    4.580 ± 0.007  ns/op
    StringHashCode.uncachedLatin1        10  avgt   25    8.548 ± 0.019  ns/op
    StringHashCode.uncachedLatin1        30  avgt   25   20.579 ± 0.075  ns/op
    StringHashCode.uncachedLatin1       100  avgt   25   77.900 ± 0.782  ns/op
    StringHashCode.uncachedLatin1       300  avgt   25  241.005 ± 1.683  ns/op
    StringHashCode.uncachedLatin1      1000  avgt   25  805.875 ± 2.824  ns/op
    StringHashCode.uncachedUTF16          1  avgt   25    2.961 ± 0.007  ns/op
    StringHashCode.uncachedUTF16          3  avgt   25    4.778 ± 0.007  ns/op
    StringHashCode.uncachedUTF16         10  avgt   25    7.140 ± 0.203  ns/op
    StringHashCode.uncachedUTF16         30  avgt   25   20.082 ± 0.031  ns/op
    StringHashCode.uncachedUTF16        100  avgt   25   76.506 ± 0.713  ns/op
    StringHashCode.uncachedUTF16        300  avgt   25  239.419 ± 0.731  ns/op
    StringHashCode.uncachedUTF16       1000  avgt   25  806.551 ± 2.725  ns/op

    After:
    Benchmark                      (length)  Mode  Cnt    Score   Error  Units     Gain
    StringHashCode.uncachedLatin1         1  avgt   25    2.426 ± 0.016  ns/op   33.88%
    StringHashCode.uncachedLatin1         3  avgt   25    4.308 ± 0.013  ns/op    6.31%
    StringHashCode.uncachedLatin1        10  avgt   25    5.595 ± 0.289  ns/op   52.78%
    StringHashCode.uncachedLatin1        30  avgt   25   12.636 ± 0.064  ns/op   62.86%
    StringHashCode.uncachedLatin1       100  avgt   25   17.121 ± 0.076  ns/op  355.00%
    StringHashCode.uncachedLatin1       300  avgt   25   37.251 ± 0.670  ns/op  546.98%
    StringHashCode.uncachedLatin1      1000  avgt   25  106.531 ± 0.075  ns/op  656.47%
    StringHashCode.uncachedUTF16          1  avgt   25    2.967 ± 0.027  ns/op   -0.20%
    StringHashCode.uncachedUTF16          3  avgt   25    4.843 ± 0.005  ns/op   -1.34%
    StringHashCode.uncachedUTF16         10  avgt   25    5.656 ± 0.285  ns/op   26.24%
    StringHashCode.uncachedUTF16         30  avgt   25   12.724 ± 0.158  ns/op   57.83%
    StringHashCode.uncachedUTF16        100  avgt   25   17.508 ± 0.072  ns/op  336.98%
    StringHashCode.uncachedUTF16        300  avgt   25   37.219 ± 1.174  ns/op  543.27%
    StringHashCode.uncachedUTF16       1000  avgt   25  107.698 ± 0.439  ns/op  648.90%

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6658/head:pull/6658` \
`$ git checkout pull/6658`

Update a local copy of the PR: \
`$ git checkout pull/6658` \
`$ git pull https://git.openjdk.java.net/jdk pull/6658/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6658`

View PR using the GUI difftool: \
`$ git pr show -t 6658`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6658.diff">https://git.openjdk.java.net/jdk/pull/6658.diff</a>

</details>

### CODE REVIEW

**Comment by altrisi** [comment]
I believe you (or someone) have to create an issue and reference the number in the PR title in order for it to get the RFR label and get reviewed.

**Comment by merykitty** [comment]
@altrisi Oh yes thank you very much for the reminder. I should have changed this to a draft earlier.

**Comment by tarsa** [comment]
Hi @merykitty . Could you try to add safepoint polls to the generated code? They would be needed to keep time-to-safepoint very low, helping the very low latency GCs like ZGC and Shenandoah. See this comment https://github.com/openjdk/jdk/pull/10847#issuecomment-1312807022 and the linked issue raised by original ZGC author: https://bugs.openjdk.org/browse/JDK-8233300 . Thanks.

**Pull request closed without merging**
