### PR TITLE
8299614: Shenandoah: STW mark should keep nmethod/oops referenced from stack chunk alive

### PR DESCRIPTION
**Pull request by shipilev**
See the investigation in the bug. Basically, with Loom we have to enable nmethod barriers to get the proper marking of nmethods/oops from stack chunks. See `ShenandoahMarkRefsSuperClosure::do_nmethod` callers and callees for more details. This IMO makes `ShenandoahNMethodBarrier` flag non-optional, as we have to enable nmethod barriers when Loom is enabled. The major part of PR deals with that.

Additional testing:
 - [x] Original reproducer does not fail anymore
 - [x] MacOS AArch64 fastdebug, `hotspot_gc_shenandoah`
 - [x] Linux AArch64 fastdebug, `hotspot_gc_shenandoah`
 - [x] Linux x86_64 fastdebug, `hotspot_gc_shenandoah`
 - [x] Linux AArch64 fastdebug, `tier1 tier2 tier3` with `-XX:+UseShenandoahGC`
 - [x] Linux x86_64 fastdebug, `tier1 tier2 tier3` with `-XX:+UseShenandoahGC`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299614](https://bugs.openjdk.org/browse/JDK-8299614): Shenandoah: STW mark should keep nmethod/oops referenced from stack chunk alive (**Bug** - P3)

### Reviewers
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.org/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15669/head:pull/15669` \
`$ git checkout pull/15669`

Update a local copy of the PR: \
`$ git checkout pull/15669` \
`$ git pull https://git.openjdk.org/jdk.git pull/15669/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15669`

View PR using the GUI difftool: \
`$ git pr show -t 15669`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15669.diff">https://git.openjdk.org/jdk/pull/15669.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15669#issuecomment-1714380097)

### CODE REVIEW

**Comment by earthling-amzn** [comment]
I'm not suggesting we keep `ShenandoahNMethodBarrier` flag, but for the sake of my own understanding: the passive mode does not need the nmethod barriers, correct?

**Comment by shipilev** [comment]
> I'm not suggesting we keep `ShenandoahNMethodBarrier` flag, but for the sake of my own understanding: the passive mode does not need the nmethod barriers, correct?

Passive needs nmethod barriers, because STW mark in passive mode needs to visit stackChunks, which in current code requires nmethod barriers to be armed to get them to visit the stackChunk's nmethods. Read through `ShenandoahMarkRefsSuperClosure::do_nmethod`. The reproducer (see bug) fails with passive too.

It is an unfortunate dependency, which we can untie by making `ShenandoahMarkRefsSuperClosure::do_nmethod` scan the nmethods directly when nmethod barriers are disabled, like this:

```
diff --git a/src/hotspot/share/gc/shenandoah/shenandoahClosures.inline.hpp b/src/hotspot/share/gc/shenandoah/shenandoahClosures.inline.hpp
index 1c8daba3d24..fe00fe72220 100644
--- a/src/hotspot/share/gc/shenandoah/shenandoahClosures.inline.hpp
+++ b/src/hotspot/share/gc/shenandoah/shenandoahClosures.inline.hpp
@@ -71,6 +71,7 @@ BoolObjectClosure* ShenandoahIsAliveSelector::is_alive_closure() {
 
 void ShenandoahOopClosureBase::do_nmethod(nmethod* nm) {
   nm->run_nmethod_entry_barrier();
+  nm->follow_nmethod(this);
 }
 
 ShenandoahKeepAliveClosure::ShenandoahKeepAliveClosure() :
diff --git a/src/hotspot/share/gc/shenandoah/shenandoahOopClosures.hpp b/src/hotspot/share/gc/shenandoah/shenandoahOopClosures.hpp
index 11c70f2726a..44f06a26684 100644
--- a/src/hotspot/share/gc/shenandoah/shenandoahOopClosures.hpp
+++ b/src/hotspot/share/gc/shenandoah/shenandoahOopClosures.hpp
@@ -63,6 +63,7 @@ class ShenandoahMarkRefsSuperClosure : public MetadataVisitingOopIterateClosure
   virtual void do_nmethod(nmethod* nm) {
     assert(!is_weak(), "Can't handle weak marking of nmethods");
     nm->run_nmethod_entry_barrier();
+    nm->follow_nmethod(this);
   }
 };
```

But IMO that is riskier than just delegating to nmethod barriers, like concurrent GC does. ...and it would probably do double work when nmethod barriers are used. 

Further, `ShenandoahNMethodBarrier` is kinda misnomer, because most of the `Shenandoah*Barrier` flags are dealing with emitting the mutator-side barriers. But `ShenandoahNMethodBarrier`, as evident from this PR, only guards arming the barriers in some conditions. The nmethod barriers are still emitted in the generated code by interpreter and compilers even with `-ShenandoahNMethodBarrier`. So, this PR resolves this oddity as well.

**Review by rkennke — APPROVED** [review]
Looks good to me. Thank you!

**Review by zhengyu123 — APPROVED** [review]
Make senses. LGTM

**Comment by shipilev** [comment]
Thanks all!

/integrate

**Pull request closed without merging**
