### PR TITLE
8295099: vmTestbase/nsk/stress/strace/strace013.java failed with "TestFailure: wrong lengths of stack traces: strace013Thread0: NNN strace013Thread83: MMM"

### PR DESCRIPTION
**Pull request by dholmes-ora**
The test is incorrectly synchronized and may take the stack trace of a thread before it has entered the wait() and thus be three frames short of the correct stack. So I cleaned that up to ensure things are correctly synchronized.

A number of comments in the test description etc were wrong so I also fixed those.

These tests are stylistically awful but I refrained from embarking on a major cleanup and adopted the prevailing styles.

Testing: local plus 50x on each platform (in progress)

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295099](https://bugs.openjdk.org/browse/JDK-8295099): vmTestbase/nsk/stress/strace/strace013.java failed with "TestFailure: wrong lengths of stack traces:  strace013Thread0: NNN strace013Thread83: MMM"

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11011/head:pull/11011` \
`$ git checkout pull/11011`

Update a local copy of the PR: \
`$ git checkout pull/11011` \
`$ git pull https://git.openjdk.org/jdk pull/11011/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11011`

View PR using the GUI difftool: \
`$ git pr show -t 11011`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11011.diff">https://git.openjdk.org/jdk/pull/11011.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
This looks fine. 

About that check at Line 171ff, where the test first compares stack lengths, I wonder whether the "k>2" was wiggle room for the problem you now solve? Could not explain it otherwise. If yes, you could probable require the length to be just equal now.

A CountDownLatch may make the coding a bit clearer maybe.

**Comment by dholmes-ora** [comment]
Thanks @tstuefe !

> I wonder whether the "k>2" was wiggle room for the problem you now solve? Could not explain it otherwise. If yes, you could probable require the length to be just equal now.

Yes I think you are right. I'll try making that change - though I'm loathe to spend too much time trying to clean this up as the more you look the more you find.

> A CountDownLatch may make the coding a bit clearer maybe.

Possibly it could avoid the sleep loop, but we still need a sync-block to guarantee the last thread is in the wait(). I'll stick with the current crude mechanism.

**Comment by dholmes-ora** [comment]
I changed things to remove the "k-2" slack, but also note that if a spurious wakeup were ever to occur then the test could again fail. I think the slack was misguided and should have been 3 - but in that case I fail to see the point of this test. If we get rare failures in the future I would advocate for the removal of this test.

**Comment by tstuefe** [comment]
> I changed things to remove the "k-2" slack, but also note that if a spurious wakeup were ever to occur then the test could again fail. I think the slack was misguided and should have been 3 - but in that case I fail to see the point of this test. If we get rare failures in the future I would advocate for the removal of this test.

Seems reasonable. Lets see how your fix works.

**Comment by dholmes-ora** [comment]
Thanks @tstuefe !

Can I get a second review please.

**Comment by lmesnik** [comment]
The fix looks good. However, there is the same problem in other strace tests. They should be fixed also, new bug filed to fix them.

**Comment by dholmes-ora** [comment]
Thanks @lmesnik . Can you click the "approve" button please. :)

**Comment by dholmes-ora** [comment]
Actually ... looking at some of those other tests it seems the real bug here was that "k-2" should have been "k-3". All the tests seem to use racey logic such that once a thread bumps the "achived" count, the test then expects a range of different possible stacks depending on the code that follows. By doing so it can be adversely affected if the implementations of any of those methods changes such that the possible stack views also change. I expect that virtual threads may have had some impact on this due to changes in Thread and ThreadGroup.

**Review by lmesnik — APPROVED** [review]

**Comment by dholmes-ora** [comment]
@tstuefe  and @lmesnik  I have completely redone the fix and just corrected the slack value from 2 to 3. I also kept some comment fixes and added extra commentary.

If we want to fix these tests they should probably all be done together, though I doubt the others can be made more accurate.

Thanks

Thanks.

**Comment by dholmes-ora** [comment]
The "request re-review" functionality seems to be broken :(

**Review by tstuefe — APPROVED** [review]
Okay, this is fine too.

**Comment by tstuefe** [comment]
> The "request re-review" functionality seems to be broken :(

No, I got a GH notification.

**Review by lmesnik — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thank you both.

/intergate

**Pull request closed without merging**
