### PR TITLE
8264109: Add vectorized implementation for VectorMask.andNot()

### PR DESCRIPTION
**Pull request by XiaohongGong**
Currently "VectorMask.andNot()" is not vectorized:
```
    public VectorMask<E> andNot(VectorMask<E> m) {
        // FIXME: Generate good code here.
        return bOp(m, (i, a, b) -> a && !b);
    }
```
This can be implemented with` "and(m.not())" `directly. Since `"VectorMask.and()/not()" `have been vectorized in hotspot, `"andNot"`
can be vectorized as well by calling them.

The performance gain is >100% for such a simple JMH:
```
  @Benchmark
  public Object andNot(Blackhole bh) {
    boolean[] mask = fm.apply(SPECIES.length());
    boolean[] r = fmt.apply(SPECIES.length());
    VectorMask<Byte> rm = VectorMask.fromArray(SPECIES, r, 0);

    for (int ic = 0; ic < INVOC_COUNT; ic++) {
      for (int i = 0; i < mask.length; i += SPECIES.length()) {
        VectorMask<Byte> vmask = VectorMask.fromArray(SPECIES, mask, i);
          rm = rm.andNot(vmask);
        }
    }
    return rm;
  }
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264109](https://bugs.openjdk.java.net/browse/JDK-8264109): Add vectorized implementation for VectorMask.andNot()

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3211/head:pull/3211` \
`$ git checkout pull/3211`

Update a local copy of the PR: \
`$ git checkout pull/3211` \
`$ git pull https://git.openjdk.java.net/jdk pull/3211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3211`

View PR using the GUI difftool: \
`$ git pr show -t 3211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3211.diff">https://git.openjdk.java.net/jdk/pull/3211.diff</a>

</details>

### CODE REVIEW

**Comment by XiaohongGong** [comment]
Hi there, could anyone please take a look at this PR? Thanks so much!

**Review by PaulSandoz — COMMENTED** [review]
Would you mind updating the existing `AbstractMask.andNot` implementation? rather than changing `VectorMask.andNot`. That fits in with the current implementation pattern.

**Comment by XiaohongGong** [comment]
> Would you mind updating the existing `AbstractMask.andNot` implementation? rather than changing `VectorMask.andNot`. That fits in with the current implementation pattern.

Hi @PaulSandoz , thanks for looking at this PR. I'v updated the patch according to your comments. Would you mind having look at it again? Thanks so much!

**Review by PaulSandoz — APPROVED** [review]
Looks good.

**Comment by XiaohongGong** [comment]
Thanks for your review @PaulSandoz !

**Review by nsjian — APPROVED** [review]
LGTM

**Comment by XiaohongGong** [comment]
Thanks for the review @nsjian !

**Pull request closed without merging**
