### PR TITLE
8255989: Remove explicitly unascribed authorship from Java source files

### PR DESCRIPTION
**Pull request by pavelrappo**
This PR proposes to remove
1. JavaDoc `@author` tags with unclear semantics: `@author unascribed|unattributed|unknown`
2. A couple of astray Form Feed (a.k.a. FF, `\f`,  `0xC`, or `^L`) characters

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255989](https://bugs.openjdk.java.net/browse/JDK-8255989): Remove explicitly unascribed authorship from Java source files

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to 9f9b0a85e4e0419ee83f8d3c675fb6897b78eb34
 * [Mark Reinhold](https://openjdk.java.net/census#mr) (@mbreinhold - **Reviewer**) ⚠️ Review applies to 9f9b0a85e4e0419ee83f8d3c675fb6897b78eb34
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to 9f9b0a85e4e0419ee83f8d3c675fb6897b78eb34
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to 9f9b0a85e4e0419ee83f8d3c675fb6897b78eb34
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to 9f9b0a85e4e0419ee83f8d3c675fb6897b78eb34

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1100/head:pull/1100`
`$ git checkout pull/1100`

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
A removed @author tag is a good @author tag

**Review by mbreinhold — APPROVED** [review]

**Review by mlchung — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Comment by pavelrappo** [comment]
Thanks to all the reviewers, this may be now integrated.

For extra confidence, I went to https://openjdk.java.net/census and checked that there are no authors whose name is one of "unascribed", "unattributed", or "unknown". I did this because some words might not be what they seem: for example, see https://stackoverflow.com/questions/4456438/how-to-pass-null-a-real-surname-to-a-soap-web-service-in-actionscript-3

**Pull request closed without merging**
