### PR TITLE
8332105: Exploded JDK does not include CDS

### PR DESCRIPTION
**Pull request by tstuefe**
An exploded JDK cannot be used with either -Xshare:on or -Xshare:auto. That causes tests like runtime/CompressedOops/CompressedCPUSpecificClassSpaceReservation.java to fail when running on an exploded JDK.

Since an exploded JDK cannot use CDS, we should - for tests - treat it as if CDS had not been included.

/label hotspot

----

Note that I was torn between two ways to fix this:

- either this fix, which is rather simple and automatically updates the "vm.cds" `@requires` property
- or to expose "exploded-ness" as a boolean property via `WhiteBox` and `VMProps`(`jdk.exploded`). See this draft PR: https://github.com/openjdk/jdk/pull/19178 . 

The latter is cleaner and clearer, conveying the message of exploded-ness without muddling it with the CDS aspect. But OTOH the complexity may not be required. 

I can go either way, though I have a slight preference for this PR, which is why I posted it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332105](https://bugs.openjdk.org/browse/JDK-8332105): Exploded JDK does not include CDS (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19188/head:pull/19188` \
`$ git checkout pull/19188`

Update a local copy of the PR: \
`$ git checkout pull/19188` \
`$ git pull https://git.openjdk.org/jdk.git pull/19188/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19188`

View PR using the GUI difftool: \
`$ git pr show -t 19188`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19188.diff">https://git.openjdk.org/jdk/pull/19188.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19188#issuecomment-2105660745)

### CODE REVIEW

**Comment by tstuefe** [comment]
Any takers?

**Review by dholmes-ora — APPROVED** [review]
Seems okay. This test should have had  `requires vm.cds` anyway.

Just out of curiosity why is CDS not compatible with an exploded build?

**Comment by tstuefe** [comment]
> > Seems okay. This test should have had `requires vm.cds` anyway.
> > Just out of curiosity why is CDS not compatible with an exploded build?

@dholmes-ora Thanks for the review. Honestly, I don't know. Maybe @iklam knows.

> 
> Isn't the exploded build supposed to be as fast as possible? I think that's why people use it, and it'd be a shame to allow anything, such as building a CDS arcive, to slow that process down.

Sure, but not generating a CDS archive at build time and being unable to dump or use an archive at all are two different things.

**Comment by iklam** [comment]
> > > Seems okay. This test should have had `requires vm.cds` anyway.
> > > Just out of curiosity why is CDS not compatible with an exploded build?
> 
> @dholmes-ora Thanks for the review. Honestly, I don't know. Maybe @iklam knows.
> 
> > Isn't the exploded build supposed to be as fast as possible? I think that's why people use it, and it'd be a shame to allow anything, such as building a CDS arcive, to slow that process down.
> 
> Sure, but not generating a CDS archive at build time and being unable to dump or use an archive at all are two different things.

The exploded build has tens of thousands of class files. If any of them are modified, the CDS archive may no longer be valid. There's no quick way of checking that. That's why CDS doesn't support the exploded build (or any apps that load class files from a directory).

**Comment by tstuefe** [comment]
Holding this off until post RDP1 23, not that important

**Comment by offamitkumar** [comment]
I still see some failures which are only failing in exploded-jvm; 

```
java/foreign/TestLinker.java 
java/lang/SecurityManager/CheckSecurityProvider.java 
java/lang/StackWalker/VerifyStackTrace.java 
java/lang/System/LoggerFinder/internal/BaseDefaultLoggerFinderTest/BaseDefaultLoggerFinderTest.java 
java/lang/System/LoggerFinder/internal/BootstrapLogger/BootstrapLoggerTest.java 
java/lang/System/LoggerFinder/internal/LoggerFinderLoaderTest/LoggerFinderLoaderTest.java 
java/lang/invoke/RevealDirectTest.java 
java/lang/invoke/lambda/LogGeneratedClassesTest.java 
java/lang/reflect/records/IsRecordTest.java 
java/lang/reflect/records/RecordPermissionsTest.java 
java/lang/reflect/records/RecordReflectionTest.java 
java/lang/runtime/ObjectMethodsTest.java 
java/util/Currency/PropertiesTestRun.java 
java/util/ResourceBundle/Bug6359330.java 
java/util/TimeZone/TimeZoneDatePermissionCheckRun.java 
java/util/logging/LogManager/Configuration/rootLoggerHandlers/BadRootLoggerHandlers.java 
java/util/logging/LogManager/Configuration/rootLoggerHandlers/RootLoggerHandlers.java 
java/util/logging/LogManager/Configuration/updateConfiguration/SimpleUpdateConfigWithInputStreamTest.java 
java/util/logging/LogManager/Configuration/updateConfiguration/UpdateConfigurationTest.java 
java/util/logging/Logger/getGlobal/TestGetGlobal.java 
java/util/logging/Logger/getGlobal/TestGetGlobalByName.java 
java/util/logging/Logger/getGlobal/TestGetGlobalConcurrent.java 
java/util/logging/Logger/setResourceBundle/TestSetResourceBundle.java 
java/util/logging/TestMainAppContext.java 
jdk/internal/jimage/JImageReadTest.java 
jdk/modules/etc/JmodExcludedFiles.java 
sun/reflect/ReflectionFactory/ReflectionFactoryTest.java 
sun/util/locale/provider/Bug8152817.java
```

Did you also notice them in tier1 with exploded-build ? 

I only looked at `TestLinker.java` failure, It doesn't "seem" to be related to CDS: 
```
TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.ServiceConfigurationError: Locale provider adapter "CLDR"cannot be instantiated.
```

**Review by iklam — APPROVED** [review]
LGTM

**Comment by tstuefe** [comment]
@offamitkumar thanks for testing. If these tests are dependent on CDS, they should have the requirement specified.

@iklam thanks!

/integrate

**Pull request closed without merging**
