### PR TITLE
8280437: Move G1BufferNodeList to gc/shared

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this simple (trivial?) change, renaming G1BufferNodeList to
BufferNodeList and moving its files from gc/g1 to gc/shared.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280437](https://bugs.openjdk.java.net/browse/JDK-8280437): Move G1BufferNodeList to gc/shared

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to 3761c3e4b9d8ae9c3ce69754108cacfc7cf0f90a
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to 3761c3e4b9d8ae9c3ce69754108cacfc7cf0f90a
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**) ⚠️ Review applies to 3761c3e4b9d8ae9c3ce69754108cacfc7cf0f90a

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7183/head:pull/7183` \
`$ git checkout pull/7183`

Update a local copy of the PR: \
`$ git checkout pull/7183` \
`$ git pull https://git.openjdk.java.net/jdk pull/7183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7183`

View PR using the GUI difftool: \
`$ git pr show -t 7183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7183.diff">https://git.openjdk.java.net/jdk/pull/7183.diff</a>

</details>

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Review by Hamlin-Li — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks @walulyai , @Hamlin-Li , and @kstefanj for reviews.

**Pull request closed without merging**
