### PR TITLE
8253644: C2: assert(skeleton_predicate_has_opaque(iff)) failed: unexpected

### PR DESCRIPTION
**Pull request by chhagedorn**
`test1()` fails while creating pre/main/post loops when copying skeleton predicates to the main loop. The problem is that we find phi nodes when following a skeleton `Opaque4` bool node, when trying to find the `OpaqueLoopInit` and `OpaqueLoopStride` nodes. This is unexpected and lets the assertion fail. This happens due to the following reason:

An inner loop of a nested loop is first unswitched and the skeleton predicates are copied to the slow and fast loop by just creating a new `If` node that share the same `Opaque4` node:
https://github.com/openjdk/jdk/blob/973255c469d794afe8ee74b24ddb5048bfcaadf7/src/hotspot/share/opto/loopPredicate.cpp#L268-L273

The loop tree building algorithm recognizes both loops as children of the parent loop:
```
Loop: N0/N0  has_sfpt
  Loop: N338/N314  limit_check profile_predicated predicated counted [0,100),+1 (2 iters)  has_sfpt
     Loop: N459/N458  profile_predicated predicated counted [0,10000),+1 (5271 iters)  has_sfpt (slow loop)
     Loop: N343/N267  profile_predicated predicated counted [0,10000),+1 (5271 iters)  has_sfpt (fast loop)
```

Some additional optimizations are then applied such that the fast loop no longer has any backedge/path to the parent loop while the slow loop still has. As a result, the loop tree building algorithm only recognizes the slow loop as child while the fast loop is not. The fast loop is treated as a separate loop on the same level as the parent loop:
```
Loop: N0/N0  has_sfpt
  Loop: N338/N314  limit_check profile_predicated predicated counted [0,100),+1 (2 iters)  has_sfpt
    [N459, but the loop could actually be removed in the meantime but the skeleton predicates are still there]
  Loop: N343/N267  profile_predicated predicated counted [0,10000),+1 (5274 iters)  has_sfpt
```

Now the original parent loop (N338) gets peeled. The fast and the slow loop still both share skeleton `Opaque4` bool nodes with all their inputs nodes up to and including the `OpaqueLoopInit/Stride` nodes. Let's look at one of the skeleton `If` nodes for the fast loop that uses such a `Opaque4` node. The skeleton `If` is no longer part of the original parent loop and is therefore not peeled. But now we need some phi nodes to select the correct nodes either from the peeled iteration or from N338 for this skeleton `If` of the fast loop. This is done in `PhaseIdealLoop::clone_iff()` which creates a new `Opaque4` node together with new `Bool` and `Cmp` nodes and then inserts some phi nodes to do the selection. 

When afterwards creating pre/main/post loops for the fast loop (N343) that is no child anymore, we find these phi nodes on the path to the `OpaqueLoopInit/Stride` nodes which lets the assertion fail. A more detailed explanation why this happens can be find at `test1()` in [TestUnswitchCloneSkeletonPredicates](https://github.com/chhagedorn/jdk/blob/cfc7c941ddefd716c9f07bf7e8f4824f00bb7e9b/test/hotspot/jtreg/compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java#L51).

I propose to copy the skeleton predicates to the unswitched loops in the same way as we copy the skeleton predicates to the main loop by cloning all the nodes on the path to the` OpaqueLoopInit/Stride` nodes with a small adaptation: We should also copy the `OpaqueLoopInit/Stride` nodes and we should keep the uncommon traps because we only want to replace them by `Halt` nodes once we create pre/main/post loops.

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253644](https://bugs.openjdk.java.net/browse/JDK-8253644): C2: assert(skeleton_predicate_has_opaque(iff)) failed: unexpected

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to c831c12178d2902c3570bfffa0943151d465f7e1
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1448/head:pull/1448`
`$ git checkout pull/1448`

### CODE REVIEW

**Comment by rwestrel** [comment]
> Some additional optimizations are then applied such that the fast loop no longer has any backedge/path to the parent loop while the slow loop still has.

Does one round of loop opts stop here...
and another starts below?

>  As a result, the loop tree building algorithm only recognizes the slow loop as child while the fast loop is not. The fast loop is treated as a separate loop on the same level as the parent loop:

>     [N459, but the loop could actually be removed in the meantime but the skeleton predicates are still there]

I don't understand that part. Is N459 no longer a loop?

**Comment by chhagedorn** [comment]
> > Some additional optimizations are then applied such that the fast loop no longer has any backedge/path to the parent loop while the slow loop still has.
> 
> Does one round of loop opts stop here...
> and another starts below?
> 
> > As a result, the loop tree building algorithm only recognizes the slow loop as child while the fast loop is not. The fast loop is treated as a separate loop on the same level as the parent loop:
> 
> > ```
> > [N459, but the loop could actually be removed in the meantime but the skeleton predicates are still there]
> > ```
> 
> I don't understand that part. Is N459 no longer a loop?

Yes, exactly. So, we unswitch in one round A. Then we have the first loop tree shown with the slow and fast loop at the start of the next round B. In this round B, we apply Split If that is then able to remove the [`IfNode` (2)](https://github.com/chhagedorn/jdk/blob/cfc7c941ddefd716c9f07bf7e8f4824f00bb7e9b/test/hotspot/jtreg/compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java#L101). We always take the true projection ( `x == 100` is true) which means that we immediately exit the fast loop N459 on the first iteration. The `CountedLoopNode` is therefore removed. The second loop tree shown is at the start of the next round C where we then finally apply the peeling and pre/main/post steps which lets the assertion fail. This description of N459 is indeed a bit misleading. When afterwards talking about the fast loop I just mean where the fast loop was before to keep things simpler.

**Comment by rwestrel** [comment]
> Yes, exactly. So, we unswitch in one round A. Then we have the first loop tree shown with the slow and fast loop at the start of the next round B. In this round B, we apply Split If that is then able to remove the [`IfNode` (2)](https://github.com/chhagedorn/jdk/blob/cfc7c941ddefd716c9f07bf7e8f4824f00bb7e9b/test/hotspot/jtreg/compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java#L101). We always take the true projection ( `x == 100` is true) which means that we immediately exit the fast loop N459 on the first iteration. The `CountedLoopNode` is therefore removed. The second loop tree shown is at the start of the next round C where we then finally apply the peeling and pre/main/post steps which lets the assertion fail. This description of N459 is indeed a bit misleading. When afterwards talking about the fast loop I just mean where the fast loop was before to keep things simpler.

Thanks for the clarification.
On round C, N459 is not part of the loop tree anymore then?
If that's case shouldn't we remove useless skeleton predicates because then don't guard a loop anymore (PhaseIdealLoop::eliminate_useless_predicates())?

**Comment by chhagedorn** [comment]
> > Yes, exactly. So, we unswitch in one round A. Then we have the first loop tree shown with the slow and fast loop at the start of the next round B. In this round B, we apply Split If that is then able to remove the [`IfNode` (2)](https://github.com/chhagedorn/jdk/blob/cfc7c941ddefd716c9f07bf7e8f4824f00bb7e9b/test/hotspot/jtreg/compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java#L101). We always take the true projection ( `x == 100` is true) which means that we immediately exit the fast loop N459 on the first iteration. The `CountedLoopNode` is therefore removed. The second loop tree shown is at the start of the next round C where we then finally apply the peeling and pre/main/post steps which lets the assertion fail. This description of N459 is indeed a bit misleading. When afterwards talking about the fast loop I just mean where the fast loop was before to keep things simpler.
> 
> Thanks for the clarification.
> On round C, N459 is not part of the loop tree anymore then?
> If that's case shouldn't we remove useless skeleton predicates because then don't guard a loop anymore (PhaseIdealLoop::eliminate_useless_predicates())?

I had a look at that method. Apparently, we are only removing `Opaque1` predicates but no `Opaque4` skeleton predicates:
https://github.com/openjdk/jdk/blob/973255c469d794afe8ee74b24ddb5048bfcaadf7/src/hotspot/share/opto/loopnode.cpp#L3573-L3579
Could that be improved? But as of the current implementation, the `Opaque4` node with its inputs is shared between a fast and a slow loop. So we could not remove the `Opaque4` node when either the fast or slow loop does not need it anymore while the other one does.

**Review by rwestrel — APPROVED** [review]

**Comment by rwestrel** [comment]
> Could that be improved? But as of the current implementation, the `Opaque4` node with its inputs is shared between a fast and a slow loop. So we could not remove the `Opaque4` node when either the fast or slow loop does not need it anymore while the other one does.

Right. Yes, I think it would make sense to remove the skeleton predicates that become useless. Anyway, your fix looks good to me.

**Review by vnkozlov — APPROVED** [review]
Good.

I suggest to merge latest source and re-test again. I am concern that some Git testing failed.

**Comment by chhagedorn** [comment]
> > Could that be improved? But as of the current implementation, the `Opaque4` node with its inputs is shared between a fast and a slow loop. So we could not remove the `Opaque4` node when either the fast or slow loop does not need it anymore while the other one does.
> 
> Right. Yes, I think it would make sense to remove the skeleton predicates that become useless. Anyway, your fix looks good to me.

Thanks for your careful review! I filed [JDK-8257498](https://bugs.openjdk.java.net/browse/JDK-8257498) to also eliminate useless skeleton predicates.

**Comment by chhagedorn** [comment]
> Good.
> 
> I suggest to merge latest source and re-test again. I am concern that some Git testing failed.

Thanks for your review! Good idea, I will do that and start some more testing.

**Comment by chhagedorn** [comment]
Extended testing with tier1-7 and hs-precheckin-comp looked good.

**Review by vnkozlov — APPROVED** [review]

**Comment by chhagedorn** [comment]
@vnkozlov @rwestrel Thanks for your reviews!

**Pull request closed without merging**
