### PR TITLE
8277602: Deopt code does not extend the stack enough if the caller is an optimize entry blob

### PR DESCRIPTION
**Pull request by JornVernee**
Deoptimization code does not recreate c2i adapter 'frames'. For compiled callers this means that the stack needs to be adjusted manually to make room for the parameters when the callee is converted to an interpreter frame (essentially emulating what a c2i adapter would do).

To check if the caller does a compiled call, the current code uses `frame::is_compiled_frame()`, which is true if the codeblob of the caller frame is an instance of `CompiledMethod`.

However, optimized entry blobs also do compiled calls, are not detected by this test, and therefore don't get their stack adjusted correctly.

To address this, I've added a new `frame::is_compiled_caller` function to determine if the caller is doing a compiled call, and I use that in the deopt code instead of `is_compiled_frame`.

This patch also removes an old workaround that tried to fix the issue by allocating some spill space in the optimized entry blob frame, but this only accounts for the first argument. If there are more arguments we still have a problem. The suggested patch fixes this the right way I think.

Thanks,
Jorn

Testing: run-test-jdk_foreign on Windows x64 and Linux x64 (afaik these are the only tests that use optimized entry blobs)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277602](https://bugs.openjdk.java.net/browse/JDK-8277602): Deopt code does not extend the stack enough if the caller is an optimize entry blob

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to 443b93e3131dbcf4e6a9949e7aee4650faaa4e2b
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6522/head:pull/6522` \
`$ git checkout pull/6522`

Update a local copy of the PR: \
`$ git checkout pull/6522` \
`$ git pull https://git.openjdk.java.net/jdk pull/6522/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6522`

View PR using the GUI difftool: \
`$ git pr show -t 6522`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6522.diff">https://git.openjdk.java.net/jdk/pull/6522.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
I've CC'd hotspot-compiler on this since compiler folks are probably the most familiar with deoptimization code.

**Comment by dean-long** [comment]
This seems safe enough, since it should only affect optimized entry blob frames.

**Review by dean-long — APPROVED** [review]

**Comment by JornVernee** [comment]
Thanks for the review.

FWIW, we have a test case which is a tomcat benchmark that uses a custom panama-foreign based SSL library. A memory corruption crash occurs in that benchmark, gets more frequent with -XX:+DeoptimizeALot, and goes away with this fix.

There's a test that used to also test this deopt code path in the jdk_foreign test suite as well, but the conditions for the failure are quite specific (optimized entry blob needs to be the deoptee's caller), and due to some code changing elsewhere the test seems to no longer hit the offending code path.

This doesn't need to be integrated right away (though I would like to get it into 18). In the mean time I'll also see if I can improve the existing test to catch this case again.

**Review by TobiHartmann — APPROVED** [review]
Looks good but a targeted regression test (or a noreg-* label) is required.

**Comment by JornVernee** [comment]
I've added a test and a couple of asserts that catch the case I'm trying to fix. If I revert the fix in deoptimization.cpp the latter assert fires (that's the case I found during debugging as well), and when I re-add the fix tests pass again.

I ran this through tier1-3 as well.

The asserts I've added only check for 'overflow' in the case of compiled callers. I played around with adding a similar check for interpreted callers as well, but I wasn't able to provoke an assertion failure with that, and I'm not 100% what the right check should be. I suspect interpreted callers are rare when we deopt due to an uncommon trap. For these reasons, I've left the asserts to check for overflow in the case of compiled callers only, for now.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me but please run this through tier4-5 as well.

**Comment by JornVernee** [comment]
Tier4-5 came back clean, except for some failures due to known issues.

Will go ahead an integrate this.

**Pull request closed without merging**
