### PR TITLE
8281539: IGV: schedule approximation computes immediate dominators wrongly

### PR DESCRIPTION
**Pull request by robcasloz**
The `ServerCompiler` module in IGV computes an approximation of C2's schedule for unscheduled graphs, for clustering and showing control flow information in the "Control Flow" window. This approximation uses domination information to guide the scheduling of nodes into basic blocks. Currently, this information is computed with a custom algorithm implementation that gives wrong results for some graphs, as shown in [the issue report](https://bugs.openjdk.java.net/browse/JDK-8281539).

This change simply replaces the custom implementation with one from the [T. J. Watson Libraries for Analysis (WALA)](https://github.com/wala/WALA), a popular set of static analysis libraries licensed under the [OSI](http://www.opensource.org/)-approved [Eclipse Public License](http://www.eclipse.org/legal/epl-v10.html). The replacement gives correct domination information for the reported graphs and reduces significantly the complexity of the `ServerCompiler` module.

#### Testing

- Tested manually that the dominator tree computed for a few selected graphs (included the reported one) is correct.
- Tested manually, for large graphs, that the dominator tree computation takes a negligible fraction (around 1%) of the entire graph scheduling time.
- Tested automatically that scheduling tens of thousands of graphs does not trigger any assertion failure (by instrumenting IGV to schedule parsed graphs eagerly and running `java -Xcomp -XX:-TieredCompilation -XX:PrintIdealGraphLevel=4`).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281539](https://bugs.openjdk.java.net/browse/JDK-8281539): IGV: schedule approximation computes immediate dominators wrongly

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7405/head:pull/7405` \
`$ git checkout pull/7405`

Update a local copy of the PR: \
`$ git checkout pull/7405` \
`$ git pull https://git.openjdk.java.net/jdk pull/7405/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7405`

View PR using the GUI difftool: \
`$ git pr show -t 7405`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7405.diff">https://git.openjdk.java.net/jdk/pull/7405.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by neliasso — APPROVED** [review]
I can still find some peculiarities - but gosh - it's fast! Let's push this!

**Comment by robcasloz** [comment]
Thanks Christian and Nils for reviewing!

@neliasso: yes, there are multiple sources of inaccuracy in IGV's schedule approximation, and this change addresses just one of them. [JDK-8280568](https://bugs.openjdk.java.net/browse/JDK-8280568) addresses another one (work in progress), and I am still collecting and documenting others.

**Comment by robcasloz** [comment]
/summary
Replace custom dominator computation with one from the WALA libraries.

**Pull request closed without merging**
