### PR TITLE
8283930: IGV: add toggle button to show/hide empty blocks in CFG view

### PR DESCRIPTION
**Pull request by robcasloz**
This change introduces a toggle button to show or hide empty blocks in the control-flow graph view. Showing empty blocks can be useful to provide context, for example when extracting a small set of nodes. On the other hand, for large graphs it can be preferable to hide empty blocks so that the extracted nodes can be localized more easily. Since both modes have advantages or disadvantages, this change gives the user the option to quickly switch between them. The toggle button is only active in the control-flow graph view: empty blocks in the clustered sea-of-nodes view are never shown because they would be disconnected and hence would not provide any additional context.

#### Testing

- Tested manually on a small selection of graphs.

- Tested automatically viewing thousands of graphs with random node subsets extracted, in all four combinations of showing/hiding empty blocks and showing/hiding neighbors of extracted nodes. The automatic test is performed by instrumenting IGV to view graphs and extract nodes randomly as the graphs are loaded, and running `java -Xcomp -XX:-TieredCompilation -XX:PrintIdealGraphLevel=4`.

#### Screenshots

- New toggle button:

toolbar

- Example control-flow graph with extracted node (85) and shown empty blocks:

<p align="center">

</p

- Example control-flow graph with the same extracted node and hidden empty blocks:

<p align="center">

</p

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283930](https://bugs.openjdk.java.net/browse/JDK-8283930): IGV: add toggle button to show/hide empty blocks in CFG view

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 13f5b4a7cad28000f5d6576e09f90a22f769424f
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8128/head:pull/8128` \
`$ git checkout pull/8128`

Update a local copy of the PR: \
`$ git checkout pull/8128` \
`$ git pull https://git.openjdk.java.net/jdk pull/8128/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8128`

View PR using the GUI difftool: \
`$ git pr show -t 8128`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8128.diff">https://git.openjdk.java.net/jdk/pull/8128.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good feature

**Comment by robcasloz** [comment]
> Good feature

Thanks for reviewing, Vladimir!

**Review by chhagedorn — APPROVED** [review]
That looks nice! Thanks for following up with this RFE which I think is especially valuable for large graphs.

**Comment by robcasloz** [comment]
Thanks for reviewing, Christian! I just applied your suggested refactorings.

**Review by chhagedorn — APPROVED** [review]
Thanks, looks good!

**Pull request closed without merging**
