### PR TITLE
8345503: Test EnableNativeAccessCDS.java fails with TEST_THREAD_FACTORY=Virtual

### PR DESCRIPTION
**Pull request by matias9927**
The JTREG option `TEST_THREAD_FACTORY=Virtual` injects command line arguments into the test and may separate an option from its arguments. In this case, the option was being placed between `--enable-native-access` and it's argument `java.base`. This patch adds `--enable-native-access` to the list of options that takes additional arguments.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345503](https://bugs.openjdk.org/browse/JDK-8345503): Test EnableNativeAccessCDS.java fails with TEST_THREAD_FACTORY=Virtual (**Bug** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [SendaoYan](https://openjdk.org/census#syan) (@sendaoYan - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22555/head:pull/22555` \
`$ git checkout pull/22555`

Update a local copy of the PR: \
`$ git checkout pull/22555` \
`$ git pull https://git.openjdk.org/jdk.git pull/22555/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22555`

View PR using the GUI difftool: \
`$ git pr show -t 22555`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22555.diff">https://git.openjdk.org/jdk/pull/22555.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22555#issuecomment-2518268060)
</details>

### CODE REVIEW

**Review by lmesnik — CHANGES_REQUESTED** [review]
You need to add this option to list here:https://github.com/openjdk/jdk/blob/master/test/lib/jdk/test/lib/process/ProcessTools.java#L394

So ProcessTools knows that next toke is the 2nd parameter of the option.

**Comment by lmesnik** [comment]
Also, the  TEST_THREAD_FACTORY=Virtual
is useless when java doesn't run any classes.  I expect it should silently pass.

So test might be excluded.

**Review by lmesnik — APPROVED** [review]

**Review by iklam — APPROVED** [review]

**Review by sendaoYan — APPROVED** [review]
After apply the patch of this PR, the test run passed.

**Comment by matias9927** [comment]
Thanks for the reviews @lmesnik @iklam and @sendaoYan! 
/integrate

**Pull request closed without merging**
