### PR TITLE
8324718: Add a static function to java.util.Objects to simplify object equality checks

### PR DESCRIPTION
**Pull request by davidalayachew**
Adding a function to Objects in order to facilitate equality checking and enhance readability. You simply specify the 2 objects that you want to check for equality, and then provide the functions which will be used to provide the values that we will check for equality.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 23 to be approved (needs to be created)

### Issue
 * [JDK-8324718](https://bugs.openjdk.org/browse/JDK-8324718): Add a static function to java.util.Objects to simplify object equality checks (**Enhancement** - P5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17603/head:pull/17603` \
`$ git checkout pull/17603`

Update a local copy of the PR: \
`$ git checkout pull/17603` \
`$ git pull https://git.openjdk.org/jdk.git pull/17603/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17603`

View PR using the GUI difftool: \
`$ git pr show -t 17603`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17603.diff">https://git.openjdk.org/jdk/pull/17603.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17603#issuecomment-1912972965)

### CODE REVIEW

**Comment by davidalayachew** [comment]
@AlanBateman ty vm for helping!

I took a look at the CSR FAQ, and found this.

> Q: How do I create a CSR ?
> A: Do not directly create a CSR from the Create Menu. JIRA will let you do this right up until the moment you try to save it and find your typing was in vain.
Instead you should go to the target bug, select "More", and from the drop down menu select "Create CSR". This is required to properly associate the CSR with the main bug, just as is done for backports.

I don't see this on my bug page. Am I looking in the wrong place? Or do I lack the permissions? -- https://bugs.openjdk.org/browse/JDK-8324718

**Comment by davidalayachew** [comment]
Adding a screenshot to demonstrate what I see.
image

Clicking NEW on the top left says that I don't have permissions.

**Comment by liach** [comment]
I fail to see the point of this new API. Existing `ObjectMethods::bootstrap` already achieves the same functionality in a better way (though the user code looks a bit more conplex), as its produced MethodHandle can be stored in a static final field and constant-fold by the JIT, while this method's argument array can't as Java arrays are not constants, and this method is polymorphic.

**Comment by davidalayachew** [comment]
Hello @liach,

Thank you for your response!

> I fail to see the point of this new API. Existing `ObjectMethods::bootstrap` already achieves the same functionality in a better way (though the user code looks a bit more conplex), as its produced MethodHandle can be stored in a static final field and constant-fold by the JIT, while this method's argument array can't as Java arrays are not constants, and this method is polymorphic.

`ObjectMethods::bootstrap` is a better fit for records, but I don't see how it could apply to general classes. Maybe you are saying a new method should instead be made on `ObjectMethods` that does something similar to the `bootstrap` method, but for classes?

Regardless, the goal of this API was to provide functionality very similar to `java.util.Comparator`, where you can provide an ad-hoc set of functions to define your comparison logic. This method is the same thing, but for equality instead.

**Comment by liach** [comment]
It can be used for general classes. See an example:
```java
public class Stuff {
  public int a, b;
  private static final MethodHandle EQUALS;

  static {
    var lookup = MethodHandles.lookup();
    try {
      EQUALS = ObjectMethods.bootstrap(lookup, "equals", MethodHandle.class, "",
          lookup.findGetter(Stuff.class, "a", int.class),
          lookup.findGetter(Stuff.class, "b", int.class));
    } catch (ReflectiveOperationException ex) {
      throw new ExceptionInInitializerError(ex);
    }
  }

  public boolean equals(Object o) {
    return EQUALS.invokeExact(this, o);
  }
}
```

**Comment by davidalayachew** [comment]
> It can be used for general classes. See an example:
> 
> ```java
> public class Stuff {
>   public int a, b;
>   private static final MethodHandle EQUALS;
> 
>   static {
>     var lookup = MethodHandles.lookup();
>     try {
>       EQUALS = ObjectMethods.bootstrap(lookup, "equals", MethodHandle.class, "",
>           lookup.findGetter(Stuff.class, "a", int.class),
>           lookup.findGetter(Stuff.class, "b", int.class));
>     } catch (ReflectiveOperationException ex) {
>       throw new ExceptionInInitializerError(ex);
>     }
>   }
> 
>   public boolean equals(Object o) {
>     return EQUALS.invokeExact(this, o);
>   }
> }
> ```

@liach, Ok, I concede that point.

Regardless, my original intention was to have something that could be used ad-hoc, along the lines of `Comparator`. In your example, it would be quite difficult to provide the necessary parameters ad hoc.

**Comment by davidalayachew** [comment]
I also want to know, would your example not be classified as "brittle" for ad-hoc equality checks? If I refactor `Stuff` to change the field names or fields types, doesn't that mean that the example you have provided would NOT get a compilation error, but would fail at run time?

**Comment by liach** [comment]
Your API is risky as well: it won't get a compile error if you add a new field but forgot to add that field to equality checks too. And since initialization happens in `<clinit>`, your said error is quite easy to detect if this class is ever loaded.

If you want this example to be "not brittle" you can resort to annotation processors (essentially compiler plugins) that automatically generate invokedynamic (which is better than this explicit field approach, as this field is initialized eagerly while indy is lazy)

**Comment by liach** [comment]
If you want a simpler, straightforward approach in case your getters change as often as the objects you compare, you can do:
```java
getters.stream().allMatch(g -> Objects.equals(g.apply(a), g.apply(b)));
```

**Comment by davidalayachew** [comment]
> Your API is risky as well: it won't get a compile error if you add a new field but forgot to add that field to equality checks too. And since initialization happens in `<clinit>`, your said error is quite easy to detect if this class is ever loaded.
> 
> If you want this example to be "not brittle" you can resort to annotation processors (essentially compiler plugins) that automatically generate invokedynamic (which is better than this explicit field approach, as this field is initialized eagerly while indy is lazy)

As far as I can tell, the risk of my API is fully subsetted by yours.

And while I can appreciate the suggestion to use annotations, I really question the wisdom of using an annotation for something that can be done with a simple library method. I understand that my version may not have the constant folding benefits of yours, but I am taking code that developers were already going to write and refactoring it to be slightly less error-prone and slightly more streamlined. Then, I package it into this `Objects` class and make it easy for them to understand and use. Not to mention, it's an import they probably have in hand already.

And either way, the annotation would be somewhat unclear on where/how to use it. Remember, this method isn't just to implement `equals` for a class -- it is meant to be used anywhere that we need ad-hoc equality checks.

**Comment by davidalayachew** [comment]
> If you want a simpler, straightforward approach in case your getters change as often as the objects you compare, you can do:
> 
> ```java
> getters.stream().allMatch(g -> Objects.equals(g.apply(a), g.apply(b)));
> ```

Oh, I did not see this when I clicked post.

So, this solution is great if I want all the fields. But again, ad-hoc. I don't always want all the fields. I want the user to be able to choose, at use-site, which methods to use to perform equality checking on.

Furthermore, not every method will be present in the class. What if I want to compare 2 objects for the length of their `String` field? I don't want to compare if the 2 are equal, but if the lengths of them are equal.

**Comment by liach** [comment]
I strongly disrecommend adding a library method that will become a performance burden. This method is not helpful as it is hard to optimize; I would recommend creating an alternative with this signature:
```java
public static <T> BiPredicate<T, T> equalsBy(List<Function<T, ?>> getters)
```

If this getters list is constant (like from `List.of`), JIT can actually constant-fold the resulting predicate, making it much faster than your API once inlined.

Your current notation doesn't offer any opportunity for JIT compiler to treat the getters as a constant to perform optimizations.

**Comment by davidalayachew** [comment]
> I strongly disrecommend adding a library method that will become a performance burden. This method is not helpful as it is hard to optimize; I would recommend creating an alternative with this signature:
> 
> ```java
> public static <T> BiPredicate<T, T> equalsBy(List<Function<T, ?>> getters)
> ```
> 
> If this getters list is constant (like from `List.of`), JIT can actually constant-fold the resulting predicate, making it much faster than your API once inlined.
> 
> Your current notation doesn't offer any opportunity for JIT compiler to treat the getters as a constant to perform optimizations.

Deal. Let me make the changes.

**Comment by prrace** [comment]
> I don't see this on my bug page. Am I looking in the wrong place? Or do I lack the permissions? -- https://bugs.openjdk.org/browse/JDK-8324718

The screenshot shows you are not logged in. You can't do anything in JBS until you login.
But if you are a first time contributor without a JBS login, you can't do that, so you will have to find
someone with the time and motivation and expertise in this area to sponsor you through the process.
They'll likely end up spending more time on it than you will ..

**Comment by davidalayachew** [comment]
> > I don't see this on my bug page. Am I looking in the wrong place? Or do I lack the permissions? -- https://bugs.openjdk.org/browse/JDK-8324718
> 
> The screenshot shows you are not logged in. You can't do anything in JBS until you login. But if you are a first time contributor without a JBS login, you can't do that, so you will have to find someone with the time and motivation and expertise in this area to sponsor you through the process. They'll likely end up spending more time on it than you will ..

@prrace That is very helpful, ty vm.

I am a first time contributor, so that is good to know. Would you be able to point me towards a template, or an idea of what questions I will have to fill out? I want to fill out as much as I can so that I can take as much time and effort off the plates of whoever sponsors me.

**Comment by davidalayachew** [comment]
Apologies for taking so long -- juggling emergencies at work.

I have sent the email @liach @prrace @AlanBateman !

Here is a link -- https://mail.openjdk.org/pipermail/core-libs-dev/2024-February/119140.html

Though, I cc'd you 3 on the email too, since piper mail always bungles up the email format, making them barely readable. Please let me know your thoughts, as well as anything I might be missing!

Thank you all again for your help!

**Comment by davidalayachew** [comment]
After "socializing" the idea, I have decided to abandon it for the potential of misuse. Here is a link. https://mail.openjdk.org/pipermail/core-libs-dev/2024-February/119140.html

I will close this pull request in response. Thank you all for your help!

**Pull request closed without merging**
