### PR TITLE
8322256: Define and document GZIPInputStream concatenated stream semantics

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR with picks up on the excellent work done by @archiecobbs in #18385

The proposed changes aim to solve two issues with the current `java.util.zip.GZIPInputStream`:

*  The class parses multiple concatenated GZIP files as a single stream. This behavior is not documented in the API  specification.
*  Any additional bytes following a trailer which do not form a valid header are discarded and the stream behaves as if the end of stream has been reached. This behavior is not documented in the API  specification.

Testing:

* A new test `GZIPInputStreamConcat` verifies the behaviors being specified in this PR 
* A new test `GZIPInputStreamGzipCommand` verifies decompression of various GZIP files created using the `gzip` command.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires CSR request [JDK-8330195](https://bugs.openjdk.org/browse/JDK-8330195) to be approved

### Issues
 * [JDK-8322256](https://bugs.openjdk.org/browse/JDK-8322256): Define and document GZIPInputStream concatenated stream semantics (**Bug** - P4)
 * [JDK-8330195](https://bugs.openjdk.org/browse/JDK-8330195): Define and document GZIPInputStream concatenated stream semantics (**CSR**)

### Contributors
 * Archie Cobbs `<acobbs@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20787/head:pull/20787` \
`$ git checkout pull/20787`

Update a local copy of the PR: \
`$ git checkout pull/20787` \
`$ git pull https://git.openjdk.org/jdk.git pull/20787/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20787`

View PR using the GUI difftool: \
`$ git pr show -t 20787`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20787.diff">https://git.openjdk.org/jdk/pull/20787.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20787#issuecomment-2320785205)
</details>

### CODE REVIEW

**Comment by eirbjo** [comment]
@LanceAndersen @jaikiran 

I have updated the API documentation in this PR inspired by the following comment from @jaikiran in Archie's PR:

https://github.com/openjdk/jdk/pull/18385#issuecomment-2265378324

I aimed to keep this at a high level, avoiding any details of the GZIP file format and the parsing logic involved in the implementation:

```
 * <p>
 * The InputStream passed to the constructor of this class may represent a
 * single GZIP file or multiple consecutive GZIP files. When the end of a
 * GZIP file is immediately followed by a new GZIP file, this class continues
 * to decode compressed data into a single, concatenated stream of uncompressed
 * data. Otherwise, any additional trailing bytes following a GZIP file are
 * discarded as if the end of stream is reached.
```

What do you think?

**Comment by AlanBateman** [comment]
I wonder if we can dig up the discussion on JDK-4691425. I can't find the CSR (or "CCC" at the time) that would have captured the reasoning for supporting this.

**Comment by LanceAndersen** [comment]
> I wonder if we can dig up the discussion on JDK-4691425. I can't find the CSR (or "CCC" at the time) that would have captured the reasoning for supporting this.

The gnu.org docs cover this(concatenating gzip files)  as part of its [advanced usage of gzip](https://github.com/openjdk/jdk/pull/20787#issuecomment-2320873616), so I don'r think we need to do any more archeology

**Comment by LanceAndersen** [comment]
> @LanceAndersen @jaikiran
> 
> I have updated the API documentation in this PR inspired by the following comment from @jaikiran in Archie's PR:
> 
> [#18385 (comment)](https://github.com/openjdk/jdk/pull/18385#issuecomment-2265378324)
> 
> I aimed to keep this at a high level, avoiding any details of the GZIP file format and the parsing logic involved in the implementation:
> 
> ```
>  * <p>
>  * The {@code InputStream} passed to the constructor of this class may represent
>  * a single GZIP file or multiple consecutive GZIP files. When the end of a
>  * GZIP file is immediately followed by a new GZIP file, this class continues
>  * to decode compressed data into a single, concatenated stream of uncompressed
>  * data. Otherwise, any additional trailing bytes following a GZIP file are
>  * discarded as if the end of stream is reached
> ```
> 
> I also made a pass over the tests with my suggested improvement from the previous PR.
> 
> What do you think?

I think we are closer and this reads much better.,  I still think we can add a mention the GZIP header/trailer similar to  what we did for ZipInputStream:

> The [getNextEntry()](https://download.java.net/java/early_access/jdk23/docs/api/java.base/java/util/zip/ZipInputStream.html#getNextEntry()) method is used to read the next ZIP file entry (Local file (LOC) header record in the ZIP format)

Thank you for picking this up.  Will look at the test a bit later this morning my time after some coffee :-)

**Comment by AlanBateman** [comment]
> The gnu.org docs cover this(concatenating gzip files) as part of its [advanced usage of gzip](https://github.com/openjdk/jdk/pull/20787#issuecomment-2320873616), so I don'r think we need to do any more archeology

Okay, but just very surprising that support was added in JDK 7 without changes to the API docs or other documentation (from a quick search).

If we are retrofitting the APIs docs then I think treat "GZIP" as a file format. It may require adding overrides so there is a place to document the behavior when reading an entry roll over into the next stream.

**Comment by LanceAndersen** [comment]
> > The gnu.org docs cover this(concatenating gzip files) as part of its [advanced usage of gzip](https://github.com/openjdk/jdk/pull/20787#issuecomment-2320873616), so I don'r think we need to do any more archeology
> 
> Okay, but just very surprising that support was added in JDK 7 without changes to the API docs or other documentation (from a quick search).
> 

I am not sure either but the implementation is pretty much in line with gzip/gunzip

> If we are retrofitting the APIs docs then I think treat "GZIP" as a file format. It may require adding overrides so there is a place to document the behavior when reading an entry roll over into the next stream.

Perhaps, an  additional blurb(or APINote) in the existing GZIPInputStream::read, but I think the verbiage that is being proposed with a couple tweaks covers the behavior.

BTW, this is what gzip/gunzip does:

```
bats % ls
Bruce.txt       Robin.txt       batman.txt      hello.txt    

bats % gzip -c batman.txt  > iambatman.gz
bats % gzip -c Bruce.txt  >> iambatman.gz
bats % gzip -c hello.txt  >> iambatman.gz
bats % gzip -c Robin.txt >> iambatman.gz   
bats % gunzip -c iambatman.gz 
I am batman
Bruce Wayne here
hello
Robin here

bats % gzip -c batman.txt  > iambrokenbat.gz
bats % gzip -c Bruce.txt >> iambrokenbat.gz 
bats % cat hello.txt >> iambrokenbat.gz 
bats % gzip -c Robin.txt >> iambrokenbat.gz

bats % gunzip -c iambrokenbat
I am batman
Bruce Wayne here
gunzip: iambrokenbat.gz: trailing garbage ignored


bats % gunzip iambatman    

bats % ls
Bruce.txt       Robin.txt       batman.txt      batman.txt.orig hello.txt       iambatman       iambrokenbat.gz
bats % cat iambatman 
I am batman
Bruce Wayne here
hello
Robin here

bats % gunzip iambrokenbat    
gunzip: iambrokenbat.gz: trailing garbage ignored
bats % ls
Bruce.txt       Robin.txt       batman.txt      batman.txt.orig hello.txt       iambatman       iambrokenbat
bats % cat iambrokenbat 
I am batman
Bruce Wayne here

bats %  gunzip -l iambatman.gz 
  compressed uncompressed  ratio uncompressed_name
         167           11 -99.9% iambatman

```

**Comment by eirbjo** [comment]
Not quite sure how to proceed here. Did this  

> > If we are retrofitting the APIs docs then I think treat "GZIP" as a file format. It may require adding overrides so there is a place to document the behavior when reading an entry roll over into the next stream.
> 
> Perhaps, an additional blurb(or APINote) in the existing GZIPInputStream::read, but I think the verbiage that is being proposed with a couple tweaks covers the behavior.

Not entirely sure how to proceed here.. Did we reach consensus on the concern raised by @AlanBateman about "treating GZIP as a file format"? 

Alan, are you ok with supporting concatenated GZIP stream into a single stream, or were you suggesting that we add APIs to parse the individual compressed streams? I'm not convinced there is any demand for this, also nothing in this proposed change prevents us from adding something like that in the future.

**Pull request closed without merging**
