### PR TITLE
8255964: Add all details to jstack log in jtreg timeout handler

### PR DESCRIPTION
**Pull request by neliasso**
This patch adds jcmd Thread.print to the jtreg timeout handler.

Please review.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255964](https://bugs.openjdk.java.net/browse/JDK-8255964): Add all details to jstack log in jtreg timeout handler

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1080/head:pull/1080`
`$ git checkout pull/1080`

### CODE REVIEW

**Comment by iignatev** [comment]
Hi Nils,

It looks alright, but could you please elaborate on why we need it when there is already `jstack` action?

— Igor

**Comment by neliasso** [comment]
They have the same output - I didn't realize that. But it would be nice to add the extended output - so I am updating the PR.

**Review by iignatev — APPROVED** [review]

**Pull request closed without merging**
