### PR TITLE
8255526: Enable jcheck whitespace checking of build system files

### PR DESCRIPTION
**Pull request by magicus**
With the new Skara tooling, we can finally enable whitespace testing for build system files (makefiles and autoconf files).

/cc build

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255526](https://bugs.openjdk.java.net/browse/JDK-8255526): Enable jcheck whitespace checking of build system files

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to 236d8360391e1c93af33f20b012b414bab3b02bc

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/898/head:pull/898`
`$ git checkout pull/898`

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks fine to me.

**Review by erikj79 — APPROVED** [review]
Awesome, finally!

**Comment by magicus** [comment]
I need to put this on hold for a while. It turned out that the Skara jcheck disallows initial tabs, which makes sense for sane source code formats (java, c++) but is unfortunately an incorrect assumption for makefiles.

(I tested that the modification to jcheck detected trailing whitespaces, but it never occurred to me that I needed to modify a line starting with tab to show that this fix would not work...)

**Comment by magicus** [comment]
Fix for Skara in PR https://github.com/openjdk/skara/pull/929.

**Comment by magicus** [comment]
Now the Skara fix is deployed, and I've added instructions to the jcheck configure file to allow tabs in Makefiles, so this is finally ready to be integrated.

**Review by shipilev — APPROVED** [review]
Still good!

**Pull request closed without merging**
