### PR TITLE
8264062: Use the blessed modifier order in jdk.jfr

### PR DESCRIPTION
**Pull request by alblue**
This replaces patterns such as "final public" with "public final" to bring the modifiers in the standard order for the jdk.jfr module.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264062](https://bugs.openjdk.java.net/browse/JDK-8264062): Use the blessed modifier order in jdk.jfr

### Reviewers
 * [Markus Grönlund](https://openjdk.java.net/census#mgronlun) (@mgronlun - **Reviewer**) ⚠️ Review applies to ec31fbd390671c8903b8dd502895634a26f95614

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3161/head:pull/3161`
`$ git checkout pull/3161`

To update a local copy of the PR:
`$ git checkout pull/3161`
`$ git pull https://git.openjdk.java.net/jdk pull/3161/head`

### CODE REVIEW

**Comment by alblue** [comment]
Would someone mind reviewing this? @mgronlun perhaps?

**Review by mgronlun — APPROVED** [review]
Hi Alex, looks good. Thank you.

**Pull request closed without merging**
