### PR TITLE
8294978: Convert 5 test/jdk/jdk/jfr tests from ASM library to Classfile API

### PR DESCRIPTION
**Pull request by liach**
Converted these tests to Classfile API and some of the constants to Constant API. InstrumentationCallback.callback wasn't changed to a record since I cannot figure out how to ship a nested record class with InstrumentationCallback in a jar.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294978](https://bugs.openjdk.org/browse/JDK-8294978): Convert 5 test/jdk/jdk/jfr tests from ASM library to Classfile API (**Sub-task** - P5)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - **Reviewer**) ⚠️ Review applies to [42d23c17](https://git.openjdk.org/jdk/pull/13072/files/42d23c17b9d2c264a97f6c8558303305054576b2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13072/head:pull/13072` \
`$ git checkout pull/13072`

Update a local copy of the PR: \
`$ git checkout pull/13072` \
`$ git pull https://git.openjdk.org/jdk.git pull/13072/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13072`

View PR using the GUI difftool: \
`$ git pr show -t 13072`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13072.diff">https://git.openjdk.org/jdk/pull/13072.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13072#issuecomment-1473391021)

### CODE REVIEW

**Comment by liach** [comment]
keep alive. @asotona will we work on this only after the promotion of classfile api to preview, i.e. package moved to java.*?

**Comment by asotona** [comment]
> keep alive. @asotona will we work on this only after the promotion of classfile api to preview, i.e. package moved to java.*?

It is questionable. Postponing tests conversions after classfile api is open saves work with complex re-packaging, however the tests are great source of use cases and it may help to better shape the api before opening it.

**Review by asotona — APPROVED** [review]
It look good, thanks for the contribution.

**Comment by liach** [comment]
@egahlin I am requesting a review for this patch which migrates ASM occurrences in JFR tests to the Class-File API, after JFR's own code's migration in #16195.

**Comment by liach** [comment]
Keep alive. Should I integrate this only after the CodeBuilder API update?

**Comment by asotona** [comment]
> Keep alive. Should I integrate this only after the CodeBuilder API update?

It would simplify the API update merge, however it is up to your decision.

**Comment by liach** [comment]
I will wait for your CodeBuilder API update first then.

**Comment by liach** [comment]
Still waiting on #17282...

**Comment by liach** [comment]
#17282 is integrated, and all `test/jdk/jdk/jfr` tests pass. Asking for a sponsor.

/integrate

**Comment by liach** [comment]
/integrate

Hope this weirdness of skara doesn't persist.

**Pull request closed without merging**
