### PR TITLE
JDK-8290839: jdk/jfr/event/compiler/TestJitRestart.java failed with "RuntimeException: No JIT restart event found: expected true, was false"

### PR DESCRIPTION
**Pull request by MBaesken**
In seldom cases the TestJitRestart.java JFR test failed because no Jitrestart event was seen in the test.
Dean Long suggested to change the test a bit "How about changing the test to look at CodeCacheFull, compilation, and JitRestart events. It can test that no compilation events happen after CodeCacheFull unless a JitRestart comes first. So it would be testing the order of events and not absolute counts."

So I adjusted the test (still succeeds after a JitRestart is seen, but in case it is not seen only fails in case of Compilation events after CodeCacheFull).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290839](https://bugs.openjdk.org/browse/JDK-8290839): jdk/jfr/event/compiler/TestJitRestart.java failed with "RuntimeException: No JIT restart event found: expected true, was false"

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9612/head:pull/9612` \
`$ git checkout pull/9612`

Update a local copy of the PR: \
`$ git checkout pull/9612` \
`$ git pull https://git.openjdk.org/jdk pull/9612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9612`

View PR using the GUI difftool: \
`$ git pr show -t 9612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9612.diff">https://git.openjdk.org/jdk/pull/9612.diff</a>

</details>

### CODE REVIEW

**Comment by egahlin** [comment]
There is no guarantee that events will arrive in the recording file in the same order they were committed. If the test depends on there order(?), the events should be sorted, i.e. events.sort(Comparator.comparing(RecordedEvent::getEndTime)).

**Comment by MBaesken** [comment]
> There is no guarantee that events will arrive in the recording file in the same order they were committed. If the test depends on there order(?), the events should be sorted, i.e. events.sort(Comparator.comparing(RecordedEvent::getEndTime)).

Yes the order is important.  However sorting using getEndTime leads to alot of errors, 50% of test runs fail this way (makes things worse)  because we seem to have  compilation events with end time later than the jdk.CodeCacheFull  event.
However sorting using getStartTime seems to work well.

**Review by egahlin — APPROVED** [review]
I don't know enough about the compiler events and their order, but looks reasonable.

**Review by RealLucy — APPROVED** [review]
Changes look good to me.

**Comment by MBaesken** [comment]
Hi Erik and Lutz, thanks for the reviews !

**Pull request closed without merging**
