### PR TITLE
8328592: hprof tests fail with -XX:-CompactStrings

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for symptoms. The tests are failing because hprof test library is confused about non-compact strings.

Additional testing:
 - [x] `serviceability/HeapDump lib-test:all` with `-XX:-CompactStrings` now pass
 - [x]  `serviceability/HeapDump lib-test:all` with `-XX:+CompactStrings` still pass

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328592](https://bugs.openjdk.org/browse/JDK-8328592): hprof tests fail with -XX:-CompactStrings (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [f783418d](https://git.openjdk.org/jdk/pull/18394/files/f783418dc7a228c36ecc0d14dba1b62c2aedd80d)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to [5ba1f4b8](https://git.openjdk.org/jdk/pull/18394/files/5ba1f4b8205b96865a1ee869dcb4ce82456ae84d)
 * [Alex Menkov](https://openjdk.org/census#amenkov) (@alexmenkov - **Reviewer**) ⚠️ Review applies to [f783418d](https://git.openjdk.org/jdk/pull/18394/files/f783418dc7a228c36ecc0d14dba1b62c2aedd80d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18394/head:pull/18394` \
`$ git checkout pull/18394`

Update a local copy of the PR: \
`$ git checkout pull/18394` \
`$ git pull https://git.openjdk.org/jdk.git pull/18394/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18394`

View PR using the GUI difftool: \
`$ git pr show -t 18394`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18394.diff">https://git.openjdk.org/jdk/pull/18394.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18394#issuecomment-2009168826)

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Are we guaranteed that non-compact string char component bytes are stored in little-endian order?

**Comment by shipilev** [comment]
> Are we guaranteed that non-compact string char component bytes are stored in little-endian order?

No, I don't think we are guaranteed any particular endianness, argh. The new patch follows what `StringUTF16` does: https://github.com/openjdk/jdk/blob/4e83f4cfc779e39cca0070b5729a508aeaa74654/src/java.base/share/classes/java/lang/StringUTF16.java#L1663-L1673

**Review by alexmenkov — APPROVED** [review]
Looks good. Please update copyright years before push

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
GHA failures look environmental. I am integrating this.

/integrate

**Pull request closed without merging**
