### PR TITLE
8250659: Clarify in ParameterizedType.getRawType() doc that only Class is returned

### PR DESCRIPTION
**Pull request by liach**
Clarify that only `Class` is returned for core reflection implementation, and the return type is `Type` to support other implementations, such as ones modeling unloaded or remote types.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8250659](https://bugs.openjdk.org/browse/JDK-8250659): Clarify in ParameterizedType.getRawType() doc that only Class is returned (**Enhancement** - P4)
 * [JDK-8335473](https://bugs.openjdk.org/browse/JDK-8335473): Clarify in ParameterizedType.getRawType() doc that only Class is returned (**CSR**) (Withdrawn)

### Reviewers
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19978/head:pull/19978` \
`$ git checkout pull/19978`

Update a local copy of the PR: \
`$ git checkout pull/19978` \
`$ git pull https://git.openjdk.org/jdk.git pull/19978/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19978`

View PR using the GUI difftool: \
`$ git pr show -t 19978`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19978.diff">https://git.openjdk.org/jdk/pull/19978.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19978#issuecomment-2200867940)

### CODE REVIEW

**Comment by liach** [comment]
Keep-alive.

**Review by jddarcy — APPROVED** [review]
Looks fine.

**Pull request closed without merging**
