### PR TITLE
8343877: Test AsyncClose.java intermittent fails - Socket.getInputStream().read() wasn't preempted

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this test-only fix which addresses the intermittent failure in AsyncClose test as noted in https://bugs.openjdk.org/browse/JDK-8343877?

The `FileDescriptor` of the `Socket` instance that gets returned from a call to `ServerSocket.accept()` gets enrolled with the `java.lang.ref.Cleaner` so that the underlying file descriptor of the newly accepted socket gets closed.

The `Socket_getInputStream_read` and even the `Socket_getOutputStream_write` tests don't hold on to the `Socket` instance returned by the `accept()` call until the concurrent `Thread` that reads (or writes) on the client side of the socket. This is an oversight in the test and this can lead to a case where the GC upon noticing that the returned `Socket` instance isn't referenced may garbage collect that instance and thus the `Cleaner` may end up closing the underlying file descriptor. When that happens, the expectations of the test don't hold and thus the test fails as noted in the linked issue.

The commit in this PR updates these 2 tests to use a try-with-resources for the returned `Socket` instance and that way enforce reachability of the `Socket` instance until the end of the try block. This should prevent the GC from garbage collecting the instance and at the same time `close()` the returned `Socket` in a deterministic manner.

No explicit `java.lang.ref.Reference.reachabilityFence()` should be required here given what the JLS specifies about try-with-resources and reachability in section 14.20.3 https://docs.oracle.com/javase/specs/jls/se23/html/jls-14.html#jls-14.20.3.

These tests continue to pass after this change with a test repeat of 50. tier2 too passes without any failures.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343877](https://bugs.openjdk.org/browse/JDK-8343877): Test AsyncClose.java intermittent fails - Socket.getInputStream().read() wasn't preempted (**Bug** - P3)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [SendaoYan](https://openjdk.org/census#syan) (@sendaoYan - Committer) Review applies to [186fd9ad](https://git.openjdk.org/jdk/pull/22093/files/186fd9add66ce477678645ea787e2a27f9e07176)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) Review applies to [186fd9ad](https://git.openjdk.org/jdk/pull/22093/files/186fd9add66ce477678645ea787e2a27f9e07176)
 * [Mark Sheppard](https://openjdk.org/census#msheppar) (@msheppar - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22093/head:pull/22093` \
`$ git checkout pull/22093`

Update a local copy of the PR: \
`$ git checkout pull/22093` \
`$ git pull https://git.openjdk.org/jdk.git pull/22093/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22093`

View PR using the GUI difftool: \
`$ git pr show -t 22093`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22093.diff">https://git.openjdk.org/jdk/pull/22093.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22093#issuecomment-2475421767)
</details>

### CODE REVIEW

**Comment by sendaoYan** [comment]
After git apply the patch from https://github.com/openjdk/jdk/pull/22093 and run the test 10k times, all test passed.

**Review by dfuch — APPROVED** [review]
Good sleuthing! Changes look good to me.

**Review by sendaoYan — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]
Yes, good sleuthing. I think this is a JDK 1.4 era test so this test bug may have existed since then. In passing I wonder if we can replace the sleeps with code that we use in other tests to poll the thread's stack until it is observed in the expected method. Not for this PR of course.

**Comment by msheppar** [comment]
is it the case that a try-with-resource, and the implicit final declaration of s2, will maintain a strongly reachable reference ? Rather than having to declare s2 as a final member variable of Socket_getInputStream_read, as done with the reader socket s, or using a ReachabilityFence to maintain an extant reference. 
I don't see 

I terms of "cleanliness" the listener ServerSocket is implicitly released, rather than having an explicit close  in a finally block for the outer try block, or being initialised in an outer try-with-resources

**Comment by jaikiran** [comment]
Hello Mark,

> is it the case that a try-with-resource, and the implicit final declaration of s2, will maintain a strongly reachable reference ?
> Rather than having to declare s2 as a final member variable of Socket_getInputStream_read, as done with the reader socket s, or using a ReachabilityFence to maintain an extant reference.

The use (or non-use) of `final` doesn't play a role here. The use of try-with-resources for the `s2` `Socket` instance (the one which was being cleaned up by the `Cleaner`) is what enforces the strong reachability. The JLS (linked in the PR description) explains how the try-with-resources is implemented - specifically, the compiler introduces bytecode to have an explicit call to `s2.close()` at the end of that try-with-resources block (this can be checked by running `javap` against these updated classes). The presence of that `s2.close()` call is what enforces the reachability of `s2`. 

> I terms of "cleanliness" the listener ServerSocket is implicitly released

I have now updated the PR to use a try-with-resources for the `ServerSocket` too. The tests continue to pass with these changes.

**Comment by jaikiran** [comment]
> In passing I wonder if we can replace the sleeps with code that we use in other tests to poll the thread's stack until it is observed in the expected method. Not for this PR of course.

The `AsyncClose` test launches several other tests and like you note, each of these appear to have `Thread.sleep(...)` for the other Thread to arrive for specific operations.

As suggested, I'll file a JBS issue to update them to use the Thread stack evaluation technique that we use in some other tests.

**Review by dfuch — APPROVED** [review]
Good suggestion Mark! Still looks good.

**Comment by jaikiran** [comment]
Thank you all for the reviews and thanks to Daniel, Mark and @sendaoYan for the help during the investigation of this failure. I'll go ahead and integrate this shortly.

**Comment by msheppar** [comment]
> Hello Mark,
> 
> > is it the case that a try-with-resource, and the implicit final declaration of s2, will maintain a strongly reachable reference ?
> > Rather than having to declare s2 as a final member variable of Socket_getInputStream_read, as done with the reader socket s, or using a ReachabilityFence to maintain an extant reference.
> 
> The use (or non-use) of `final` doesn't play a role here. The use of try-with-resources for the `s2` `Socket` instance (the one which was being cleaned up by the `Cleaner`) is what enforces the strong reachability. The JLS (linked in the PR description) explains how the try-with-resources is implemented - specifically, the compiler introduces bytecode to have an explicit call to `s2.close()` at the end of that try-with-resources block (this can be checked by running `javap` against these updated classes). The presence of that `s2.close()` call is what enforces the reachability of `s2`.
> 
> > I terms of "cleanliness" the listener ServerSocket is implicitly released
> 
> I have now updated the PR to use a try-with-resources for the `ServerSocket` too. The tests continue to pass with these changes.

Cheers JP, thanks for that feedback and for ServerSocket suggestion
yes, I appreciate and understand the implicit additions which come with try-with-resource and the autoclose. As such, I was just confirming that as s2 is a local variable, this is is sufficient to extend scope of a strongly reachable reference.

in any case ... it's all good

"big shout out" to @djelinski for some insightful observation during this issue investigation

**Review by msheppar — APPROVED** [review]
an LGTM

**Pull request closed without merging**
