### PR TITLE
8316186: RISC-V: Remove PlatformCmpxchg<4>

### PR DESCRIPTION
**Pull request by robehn**
Hi, please consider.

I don't know the history behind the Cmpxhg<4>, but it is not needed anymore.
Using compiler as in 8 byte case is just fine.

Passes hotspot-tier (qemu, vf2 still running), some manual extra testing via gtest, looked at compiler: output, e.g. https://godbolt.org/z/a31Gdqn8q

If you know the history please share, and if you have a reason why we should keep it please speak up!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316186](https://bugs.openjdk.org/browse/JDK-8316186): RISC-V: Remove PlatformCmpxchg&lt;4&gt; (**Enhancement** - P5)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15715/head:pull/15715` \
`$ git checkout pull/15715`

Update a local copy of the PR: \
`$ git checkout pull/15715` \
`$ git pull https://git.openjdk.org/jdk.git pull/15715/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15715`

View PR using the GUI difftool: \
`$ git pr show -t 15715`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15715.diff">https://git.openjdk.org/jdk/pull/15715.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15715#issuecomment-1717540079)

### CODE REVIEW

**Comment by RealFYang** [comment]
The first instruction of the inline asm will make a difference here. 
It sign-extend the 32-bit input compare_value into 64-bit because the `bne` instruction compares 64-bit values. 
Please note that we don't have 32-bit compare-and-branch instructions for RISC-V 64. 
As I remembered, we once witnessed test failures if we use the compiler version. 

``` 
 __asm__ __volatile__ (
    "1:  sext.w    %1, %3      \n\t" // sign-extend compare_value
    "    lr.w      %0, %2      \n\t"
    "    bne       %0, %1, 2f  \n\t"
```

**Comment by robehn** [comment]
So we basically have some rubbish in top 32 bits, we clear them, right.
And lr.w automatically sign extends, so old_value is fine.

Checking for when/where the debug was/is in tool-chain.

**Comment by robehn** [comment]
I asked around, there is no known bug.
And if there was a bug it can't be the " __atomic_compare_exchange" it self I was told.
"As per ABI, 32-bit quantities in 64-bit container have to be sign-extended"

The compare value is passed as pointer, the normal generate code is:
"lw      a3,0(a5)"
"LW instruction loads a 32-bit value from memory and sign-extends this to 64 bits"

gcc 8.2 seems to generate the same code as gcc 13/tip.

**Comment by RealFYang** [comment]
Try this test: `make test TEST="test/hotspot/jtreg/gc/shenandoah/compiler/TestReferenceCAS.java"`
It fails with this change:
```
java.lang.RuntimeException: a (foo) != b (bar): success compareAndSet Object value
        at TestReferenceCAS.assertEquals(TestReferenceCAS.java:93)
        at TestReferenceCAS.testAccess(TestReferenceCAS.java:115)
        at TestReferenceCAS.main(TestReferenceCAS.java:100)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by robehn** [comment]
> Try this test: `make test TEST="test/hotspot/jtreg/gc/shenandoah/compiler/TestReferenceCAS.java"` It fails with this change:
> 
> ```
> java.lang.RuntimeException: a (foo) != b (bar): success compareAndSet Object value
>         at TestReferenceCAS.assertEquals(TestReferenceCAS.java:93)
>         at TestReferenceCAS.testAccess(TestReferenceCAS.java:115)
>         at TestReferenceCAS.main(TestReferenceCAS.java:100)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
>         at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
>         at java.base/java.lang.Thread.run(Thread.java:1570)
> ```

But that test should be using MacroAssembler::cmpxchg_narrow_value ?

**Comment by robehn** [comment]
GC barrier may use that Atomic::cmpxchg, depending on compiled or not, etc, so that test uses this cmpxchg

The case we are talking seems to be the narrow oop.

According to RV calling convention specs:
`In RV64, 32-bit types, such as int, are stored in integer registers as proper sign extensions of their
32-bit values; that is, bits 63..31 are all equal. This restriction holds even for unsigned 32-bit types`

This means any 4-bytes passed in integer register must be sign extended by caller.
Now this method will be inline, but above must still be true.

I added this 'assert':
`+  if (byte_size == 4) {
+    T tmp;
+    __asm__ __volatile__ (
+    "    sext.w    %0, %1      \n\t" // sign-extend
+    "    beq       %0, %1, 1f  \n\t"
+    "    ld        x0,(x0)     \n\t"
+    "    1:                    \n\t"
+    "                          \n\t"
+    : /*%0*/"=&r" (tmp)
+    : /*%1*/"r" (compare_value)
+    : "memory" );
+  }
`

And tested gcc 12 and 13, in qemu and on VF2 (gcc 12) it do not fire, hence I cannot reproduce.
If there is a bug it is not with  __atomic_compare_exchange, since the value must already be sign extended.

AFAICT this extra sign extension is actually hiding a deeper bug!

Are you building normal upstream gcc (12/13)?

This made be realize that the call_VM with Register must always be manually check for proper sign extension.

**Comment by RealFYang** [comment]
I agree with your understanding about C/C++ ABI calling conversion. I am suspecting that this might be related how narrow oop are loaded for template interpreter, C1 and C2. Normally we do `lwu` to do that which does zero-extension instead of sign-extension. An example for C2 is [1]. Sign-extension for 32-bit narrow oop doesn't make much sense to me at first glance. But that's just a guess.

BTW: I am using GCC-11.4.0 shipped with Ubuntu 22.04.3 LTS. I can try GCC-12 later. 

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/riscv.ad#L4684

**Comment by RealFYang** [comment]
PS: I can reproduce the test failure with GCC version 10 and 11. But it does not trigger with GCC 12.
Note that I am using openjdk release build. It won't trigger if I use slowdebug build from GCC 11.

**Comment by RealFYang** [comment]
> I can't reproduce with gcc 11.4.0-1ubuntu1~23.04 (testing with fastdebug). Trying with another gcc....

You might want to try openjdk release build from GCC 10 or 11. 

> Can you add 'assert' code above and check hs_err which case this is?

Yeah, I have added code change from this pull request and your 'assert' code and doing a native release build with GCC 11.

**Comment by RealFYang** [comment]
> > Can you add 'assert' code above and check hs_err which case this is?
> 
> Yeah, I have added code change from this pull request and your 'assert' code and doing a native release build with GCC 11.

Turns out that the issue won't reproduce if adding your 'assert' code.
That is to say, it only triggers with openjdk release build built with this PR and GCC version 10 or 11 on my side.

**Comment by robehn** [comment]
> > > Can you add 'assert' code above and check hs_err which case this is?
> > 
> > 
> > Yeah, I have added code change from this pull request and your 'assert' code and doing a native release build with GCC 11.
> 
> Turns out that the issue won't reproduce if adding your 'assert' code. That is to say, it only triggers with openjdk release build built with this PR and GCC version 10 or 11 on my side.

I can now reproduce using gcc 11.3 + this branch with no changes.

**Comment by robehn** [comment]
Fix for the bug here:
https://github.com/openjdk/jdk/pull/15917

**Comment by robehn** [comment]
Merge with master, retested the problematic tests, we are all green now.
Please consider :)

**Review by RealFYang — APPROVED** [review]
Looks good. So far my local regression tests with release build from GCC-11 are fine.

**Comment by robehn** [comment]
> Looks good. So far my local regression tests with release build from GCC-11 are fine.

Thanks you, and extra thanks for testing!

**Review by Hamlin-Li — APPROVED** [review]

**Comment by robehn** [comment]
@Hamlin-Li thanks!

/integrate

**Pull request closed without merging**
