### PR TITLE
8297437: javadoc cannot link to old docs (with old style anchors)

### PR DESCRIPTION
**Pull request by wkia**
As it discussed on the mail list, checking presence of "element-list" or "package-list" is good enough approach to determine which type of anchors is used in external docs. The fix is for docs generated by 'supported' platforms only, i.e. 8, 11, ...

This fix extends `Extern.Item` with `useOldFormId` boolean flag to indicate a type of anchor. The boolean flag is set accordingly when reading a list of elements from either "element-list" or "package-list". 

Name transformation is performed in `Extern.getExternalLink()` by `getOldFormHtmlName()` call when creating `DocLink` instance.

Type of anchors used by platform docs are hard-coded in `isOldFormPlatformDocs()` (similar to `getPlatformElementList()`), since it's not supposed to rebuild platform docs on docs.oracle.com.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297437](https://bugs.openjdk.org/browse/JDK-8297437): javadoc cannot link to old docs (with old style anchors)

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.org/census#hannesw) (@hns - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12066/head:pull/12066` \
`$ git checkout pull/12066`

Update a local copy of the PR: \
`$ git checkout pull/12066` \
`$ git pull https://git.openjdk.org/jdk pull/12066/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12066`

View PR using the GUI difftool: \
`$ git pr show -t 12066`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12066.diff">https://git.openjdk.org/jdk/pull/12066.diff</a>

</details>

### CODE REVIEW

**Review by hns — CHANGES_REQUESTED** [review]
This looks good to me. A few minor issues:

 - The year in the copyright headers of modified files should be updated to 2023
 - The bug id should be added to the @bug field of tests that have been significantly changed (I think only TestLinkPlatform.java in this case)
 - I wonder if for those tests that are hard-coded to release 8 we should add tests for release >= 10?

**Comment by wkia** [comment]
> * I wonder if for those tests that are hard-coded to release 8 we should add tests for release >= 10?

I'm not sure about it.  
TestLinkPlatform seems OK now, it covers both cases, but doesn't check 'element-list' file existance. Other changed tests are affected because of they use 'package-list' file in the folder specified by '-linkoffline' option, not because of 'source 8'. There are some javadoc tests which use 'element-list' file currently, but they don't check anchor names. To make sure we check both cases, in a part of the affected tests we could use 'element-list' file instead, so we could cover both cases.

**Review by hns — APPROVED** [review]
Thanks for the update, looks good!

**Comment by hns** [comment]
I can sponsor this PR.

**Pull request closed without merging**
