### PR TITLE
8271202: C1: assert(false) failed: live_in set of first block must be empty

### PR DESCRIPTION
**Pull request by kelthuzadx**
Hi, I'm trying to fix [JDK-8271202](https://bugs.openjdk.java.net/browse/JDK-8271202). A local variable(smallinvoc) is defined in B3 and only used in B14, so it oughts to have a short lifetime. But its lifetime has been unconditionally extended since -XX:+DeoptimizeALot(**Just removing this may be also a simpler and safer fix? Not sure if it's acceptable**), making it propagate to almost the whole remaing IR.

https://github.com/openjdk/jdk/blob/ecd445562f8355704a041f9eca0e87dc85a7f44c/src/hotspot/share/ci/ciMethod.cpp#L373-L379

image

A virtual register(v603) that represents this variable is located in B13 live_in set, which propagated to B1 live_out set.

When B1 merges state with B16 and B19, it found that this variable in new_state(B16) was empty, so B1 invalidates the corresponding local slot.

https://github.com/openjdk/jdk/blob/ecd445562f8355704a041f9eca0e87dc85a7f44c/src/hotspot/share/c1/c1_Instruction.cpp#L826-L838

I think we should invalidate this slot only when their types are mismatched. Otherwise, Phi will not be generated, B19 live_gen set will not contain this variable, because of which this variable is alive in B1 live_in. B1 live_in will eventually backward propagate to B20 live_in set, it avoids being killed by B19 live_gen, which causes the crash.

```
Block 1
live_in:
603 616 617 618 619 620 621 622 
live_out:
603 616 617 618 619 620 621 622 
live_gen:
620 
live_kill:
648 649 650

Block 16
live_in:
603 616 617 618 619 620 621 622 
live_out:
603 616 617 618 619 620 621 622 
live_gen:
616 617 618 619 620 621 622 
live_kill:
620 654 655 656 657 

Block 19
live_in:
603 
live_out:
603 616 617 618 619 620 621 622 
live_gen:

live_kill:
0 1 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 


Block 20
live_in:
603 
live_out:
603 
live_gen:

live_kill:
577 578
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271202](https://bugs.openjdk.java.net/browse/JDK-8271202): C1: assert(false) failed: live_in set of first block must be empty

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4916/head:pull/4916` \
`$ git checkout pull/4916`

Update a local copy of the PR: \
`$ git checkout pull/4916` \
`$ git pull https://git.openjdk.java.net/jdk pull/4916/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4916`

View PR using the GUI difftool: \
`$ git pr show -t 4916`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4916.diff">https://git.openjdk.java.net/jdk/pull/4916.diff</a>

</details>

### CODE REVIEW

**Comment by kelthuzadx** [comment]
Can I have a review for this fix? Thanks.

**Review by vnkozlov — APPROVED** [review]
I am not expert but your explanation of issue and suggested fix seems reasonable.

**Review by neliasso — APPROVED** [review]
Thanks for a thorough explanation of the problem. It seems to be a very rare case of a rare case - nice find!

The fix seems reasonable. Approved.

**Comment by TheRealMDoerr** [comment]
> A local variable(smallinvoc) is defined in B3 and only used in B14

This sounds like a bug. B3 doesn't dominate B14, so B14 can't use the variable. Shouldn't the local slot have been invalidated on the path between the two blocks?
Invalidation of local slots usually occurs when the control flow predecessors have different types or a dead value (indicated by `new_value == NULL` in `BlockBegin::try_merge`). 
Maybe it's a case which C1 can't handle. If so, bailing out would be the right choice IMHO.

**Comment by kelthuzadx** [comment]
Thank you all for reviewing this PR,  I will investigate more based on review feedback, will get back to you on this.

**Comment by TheRealMDoerr** [comment]
Thanks a lot for analyzing it further. Christian has added a comment to the bug how it can be reproduced, but I haven't found time for it, yet. My first guess is that the problem could be that we don't invalidate phi functions recursively. The phi we're currently invalidating may feed into another phi in another block which would also require invalidation. If that's the case, we could either implement recursive invalidation or detect it and bail out.

**Pull request closed without merging**
