### PR TITLE
8319757: java/nio/channels/DatagramChannel/InterruptibleOrNot.java failed: wrong exception thrown

### PR DESCRIPTION
**Pull request by AlanBateman**
InterruptibleOrNot.testInterruptBeforeInterruptibleReceive has failed a few times. It calls DatagramChannel.receive with the interrupt status set and expects ClosedByInterruptException to be thrown. The shared part of the test is also used for the non-interruptible scenario which needs a delayed close to ensure the thread calling receive wakes up. The 2s delay is not sufficient and thus it's possible for the async close to beat the detection of the interrupt status. This leads to AsynchronousCloseException instead of the expected ClosedByInterruptException.

The test is re-worked to split the interruptible and non-interruptible tests. The test is also changed to drop the delayed interrupt/close and instead use a thread to poll under the target thread is in DatagramChannel.receive. The overall test is simpler. I changed it to be a JUnit test, that part is only a few lines of changes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319757](https://bugs.openjdk.org/browse/JDK-8319757): java/nio/channels/DatagramChannel/InterruptibleOrNot.java failed: wrong exception thrown (**Bug** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17251/head:pull/17251` \
`$ git checkout pull/17251`

Update a local copy of the PR: \
`$ git checkout pull/17251` \
`$ git pull https://git.openjdk.org/jdk.git pull/17251/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17251`

View PR using the GUI difftool: \
`$ git pr show -t 17251`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17251.diff">https://git.openjdk.org/jdk/pull/17251.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17251#issuecomment-1877025663)

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
The test changes look OK to me.

Given that these are unconnected DatagramChannels, do you think this test is susceptible to receiving unexpected packets (in CI environments) and can run into intermittent failures (receive completing successfully before being interuppted)? Would making them connected (to a test specific address that never sends anything) improve the situation or would that then take a different code path than what this test intends to test?

**Review by bplb — APPROVED** [review]
Looks good insofar as I know this area.

**Comment by AlanBateman** [comment]
> Given that these are unconnected DatagramChannels, do you think this test is susceptible to receiving unexpected packets (in CI environments) and can run into intermittent failures (receive completing successfully before being interrupted)? Would making them connected (to a test specific address that never sends anything) improve the situation or would that then take a different code path than what this test intends to test?

I view the issue interference (stray datagrams) from other tests/programs as a separate topic. It would be useful to audit the DatagramChannel, DatagramSocket, and other tests that send unicast datagrams to identity the tests that send to target addresses/ports that the test doesn't control. Tests for PortUnreachableException or tests that need to use specific protocol families (IPv4 or IPv6) are examples. It sometimes feels like these need to be isolated, I don't think jtreg exclusivedirs provides enough as it's a lock file for a specific tree rather than all agent VMs. In addition, it would be a bit unusual to use send/receive on a connected DatagramChannel. It's allowed of course but usually it's read/write when connected. So I agree your suggestion is something we should consider doing, I view is as part of broader issue to reduce and eliminate interference from other programs or tests. This PR is more focused on fixing the timing issue in the test where a channel can be closed and the thread blocked on the channel interrupted at around the same time.

**Comment by AlanBateman** [comment]
Thanks for the reviews.

**Pull request closed without merging**
