### PR TITLE
8259398: Super word not applied to a loop with byteArrayViewVarHandle

### PR DESCRIPTION
**Pull request by vnkozlov**
Address expressing in this case has CastII which is not range check related.
I think it is safe to skip any CastII nodes (similar to ConvI2L nodes) when parsing address for vectors - vectors will be constructed only if the same loop's variable and invariant are used for all memory operations regardless casts. Also vectors address depends on loop's variable so they will not be moved outside loop.
In 32-bit VM there is no ConvI2L nodes so I moved CastII checks from under ConvI2L check.

New regression case added to TestBufferVectorization.java test.

Testing hs-tier1-7, RenaissanceStressTest. Run all vectorizing tests locally to make sure no regression.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259398](https://bugs.openjdk.java.net/browse/JDK-8259398): Super word not applied to a loop with byteArrayViewVarHandle

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2317/head:pull/2317`
`$ git checkout pull/2317`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
Thank you @iwanowww

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by vnkozlov** [comment]
Thank you all

**Comment by vnkozlov** [comment]
Thank you all for reviews.

**Pull request closed without merging**
