### PR TITLE
8315383: jlink SystemModulesPlugin incorrectly parses the options

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://bugs.openjdk.org/browse/JDK-8315383

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315383](https://bugs.openjdk.org/browse/JDK-8315383): jlink SystemModulesPlugin incorrectly parses the options (**Bug** - P3)

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to [8fd76f62](https://git.openjdk.org/jdk/pull/15495/files/8fd76f62e161845977069418405e821be728c079)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15495/head:pull/15495` \
`$ git checkout pull/15495`

Update a local copy of the PR: \
`$ git checkout pull/15495` \
`$ git pull https://git.openjdk.org/jdk.git pull/15495/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15495`

View PR using the GUI difftool: \
`$ git pr show -t 15495`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15495.diff">https://git.openjdk.org/jdk/pull/15495.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15495#issuecomment-1699705295)

### CODE REVIEW

**Review by mlchung — APPROVED** [review]
Looks good.   Thanks for catching this.

There are a few unused imports in JLinkDedupTestBatchSizeOne.java.  Can you remove them as you are in that file?

**Comment by Siedlerchr** [comment]
@mlchung Could you please do the backport for us? We don't have the rights. Thanks in advance!

**Comment by mlchung** [comment]
sure, I can help.

**Pull request closed without merging**
