### PR TITLE
Add self-signed ISRG Root X2 to keystore

### PR DESCRIPTION
**Pull request by pgporada**
Hi, I'd like to get the [self-signed ISRG Root X2 CA cert](https://letsencrypt.org/certificates/) included in the OpenJDK root store.
```
$ openssl x509 -in isrg-root-x2.pem -noout -subject -issuer -serial -startdate -enddate
subject=C = US, O = Internet Security Research Group, CN = ISRG Root X2
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X2
serial=41D29DD172EAEEA780C12C6CE92F8752
notBefore=Sep  4 00:00:00 2020 GMT
notAfter=Sep 17 16:00:00 2040 GMT
```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12445/head:pull/12445` \
`$ git checkout pull/12445`

Update a local copy of the PR: \
`$ git checkout pull/12445` \
`$ git pull https://git.openjdk.org/jdk.git pull/12445/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12445`

View PR using the GUI difftool: \
`$ git pr show -t 12445`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12445.diff">https://git.openjdk.org/jdk/pull/12445.diff</a>

</details>

### CODE REVIEW

**Comment by pgporada** [comment]
I do not have access to create an account at bugs.openjdk.org to create an issue.

**Comment by pgporada** [comment]
It's waiting on openjdk to do something with it.

**Comment by pgporada** [comment]
@RogerRiggs Would you be able to help me out with this, please? I saw you were a reviewer on several other PRs. https://github.com/openjdk/jdk/pull/12445#issuecomment-1419638534

**Comment by pgporada** [comment]
@RogerRiggs Would you be able to help me out with this, please? I saw you were a reviewer on several other PRs. https://github.com/openjdk/jdk/pull/12445#issuecomment-1419638534

**Comment by RogerRiggs** [comment]
Can you familiarize yourself with the process for [Including Certificate Authority Root Certificates in Java](https://www.oracle.com/java/technologies/javase/carootcertsprogram.html).
Are there particular servers or services that need this new root.
The certificate authority itself may need to make the request.

**Comment by RogerRiggs** [comment]
I found out the request is in process so stay tuned; as the process indicates, it can take a while.
This PR can be closed.

**Comment by pgporada** [comment]
Cool, thanks!

**Pull request closed without merging**
