### PR TITLE
8306927: Collator treats "v" and "w" as the same letter for Swedish language locale.

### PR DESCRIPTION
**Pull request by naotoj**
Updating the collation rules for Swedish to the modern one, which is aligned with the CLDR's default collation rules. Since it is changing the existing behavior, a release note has also been drafted: https://bugs.openjdk.org/browse/JDK-8306948

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306927](https://bugs.openjdk.org/browse/JDK-8306927): Collator treats "v" and "w" as the same letter for Swedish language locale.

### Reviewers
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13677/head:pull/13677` \
`$ git checkout pull/13677`

Update a local copy of the PR: \
`$ git checkout pull/13677` \
`$ git pull https://git.openjdk.org/jdk.git pull/13677/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13677`

View PR using the GUI difftool: \
`$ git pr show -t 13677`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13677.diff">https://git.openjdk.org/jdk/pull/13677.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13677#issuecomment-1524034225)

### CODE REVIEW

**Review by justin-curtis-lu — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Release note also looks good.

**Comment by JoeWang-Java** [comment]
The rule was changed in 2006, the year Jave SE 6 was released. Though it looks like very much a corner case, it goes all the way back. I wonder if a CSR is needed?

**Comment by naotoj** [comment]
> The rule was changed in 2006, the year Jave SE 6 was released. Though it looks like very much a corner case, it goes all the way back. I wonder if a CSR is needed?

We don't file a CSR for such a locale data change. These sorts of changes happen in the CLDR upgrade all the time, as well as other i18n-related data changes (currency, timezone, etc.)

**Review by JoeWang-Java — APPROVED** [review]
I see. Thanks.

**Comment by AlanBateman** [comment]
@naotoj I know we don't usually create CSRs for changes to locale data but changing the sorting order looks significant, it might need further discussion.

**Comment by naotoj** [comment]
I created an enhancement for Collator to support multiple tables: [JDK-8307547](https://bugs.openjdk.org/browse/JDK-8307547) that would require a CSR where we can discuss the default

**Pull request closed without merging**
