### PR TITLE
8278028: [test-library] Warnings cleanup of the test library

### PR DESCRIPTION
**Pull request by RogerRiggs**
Compilation warnings of the test library introduce noise in test output and should be addressed or suppressed. 
Changes include:
 - SuppressWarnings("deprecation") and SuppressWarnings("removal")
 - Adding type parameters to Raw types
 - Adding a hashCode method where equals was already present

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278028](https://bugs.openjdk.java.net/browse/JDK-8278028): [test-library] Warnings cleanup of the test library

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 0f445b4ac69fa72ee9f9324c6e98408b51d96f48
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to 0f445b4ac69fa72ee9f9324c6e98408b51d96f48
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to 0f445b4ac69fa72ee9f9324c6e98408b51d96f48
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to 0f445b4ac69fa72ee9f9324c6e98408b51d96f48
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6638/head:pull/6638` \
`$ git checkout pull/6638`

Update a local copy of the PR: \
`$ git checkout pull/6638` \
`$ git pull https://git.openjdk.java.net/jdk pull/6638/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6638`

View PR using the GUI difftool: \
`$ git pr show -t 6638`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6638.diff">https://git.openjdk.java.net/jdk/pull/6638.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
Changes look reasonable to me but since I am not familiar with all those files it might be best to get at least one additional reviewer.

**Comment by RogerRiggs** [comment]
Can another reviewer take a look at this?  Thanks

**Review by mlchung — APPROVED** [review]
Looks okay to me.

**Review by naotoj — APPROVED** [review]
LGTM. Nit: Some of the files need copyright year updates.

**Review by LanceAndersen — APPROVED** [review]

**Review by lmesnik — COMMENTED** [review]
Is test/micro/org/openjdk/bench/java/io/SerialFilterOverhead.java  added accidentally or by purpose?

**Comment by RogerRiggs** [comment]
> Is test/micro/org/openjdk/bench/java/io/SerialFilterOverhead.java added accidentally or by purpose?

By mistake, thanks for noticing.

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
