### PR TITLE
Remove duplicated code in the poll() method of LinkedList

### PR DESCRIPTION
**Pull request by tanisperez**
The poll() and the pollFirst() code is the same in the LinkedList class. We should call directly to pollFirst() from the poll() method.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/115/head:pull/115`
`$ git checkout pull/115`

### CODE REVIEW

**Review by tweimer — CHANGES_REQUESTED** [review]
Same for `peek()` and `peekFirst()` please

**Comment by tanisperez** [comment]
I need to create an issue for this Pull Request, but I cannot create an account on the issue tracker. I tried the Forgot Password form, but I don't receive the email with the reset link.

**Comment by tanisperez** [comment]
It is insane how difficult it is to open a Pull Request for this project. I think it is bad for the Java platform, you need to attract more contributors for the project to keep it alive...

I am stuck with the process to open a new issue, the reset link to create a new account does not work. https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1

**Comment by stuart-marks** [comment]
Sorry about the difficulties with contributing, and thanks for putting in the effort! Unfortunately this is quite poorly documented at the moment, but one needs to have an official project role in order to get an account with the bug database, and in order to get a project role you need to have contributed some fixes. Effectively this means that new contributors need to find someone to sponsor their fixes.

Probably the best thing to do for future contributions is to join a mailing list and discuss the changes there. See http://mail.openjdk.java.net/mailman/listinfo . Library changes are discussed in core-libs-dev. Other good mailing lists are announce, jdk-dev (for general development issues), and discuss.

I'll address the particulars of this PR in a separate comment.

**Comment by stuart-marks** [comment]
The proposed change removes a tiny amount of duplicated code (a null check around a call to an internal method) and replaces it with a call to a public method. Since public methods are overridable, this means that this change would be visible to subclasses. This is a behavior change, and it might cause subtle bugs to occur in applications. While the risk of this is probably low, it's nonzero, and it doesn't seem justified by the very small benefit of removing a little bit of duplicate code. Therefore I'm inclined to close out this PR.

**Pull request closed without merging**
