### PR TITLE
8334629: [BACKOUT] PhaseIdealLoop::conditional_move is too conservative

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

I cannot explain the regression, comparing the current mainline to JDK-21 reveals a decrease in performance, yet it is only for some combinations of OS-GC and perfasm shows that the hot regions (>99% of execution time) do not contain differences that can explain the results.

Consequently, with the advice of @TobiHartmann , I propose to effectively revert JDK-8319451 for the generation of `CMove`s inside loops. For those outside, the before-JDK-8319451 probability threshold is 0.001 and the current value is 0.01. I think the current value is more reasonable as evidenced by the benchmark added in JDK-8319451.

Please kindly review, thank you very much.
Quan Anh

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334629](https://bugs.openjdk.org/browse/JDK-8334629): [BACKOUT] PhaseIdealLoop::conditional_move is too conservative (**Sub-task** - P3)

### Reviewers
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**) ⚠️ Review applies to [caaee62b](https://git.openjdk.org/jdk/pull/19650/files/caaee62bc50590c57430e0eac3476c2f0e60a5b8)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Jasmine Karthikeyan](https://openjdk.org/census#jkarthikeyan) (@jaskarth - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19650/head:pull/19650` \
`$ git checkout pull/19650`

Update a local copy of the PR: \
`$ git checkout pull/19650` \
`$ git pull https://git.openjdk.org/jdk.git pull/19650/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19650`

View PR using the GUI difftool: \
`$ git pr show -t 19650`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19650.diff">https://git.openjdk.org/jdk/pull/19650.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19650#issuecomment-2160478164)

### CODE REVIEW

**Comment by TobiHartmann** [comment]
Thanks, Quan Anh. On second thought, I think it's best to cleanly backout [JDK-8319451](https://bugs.openjdk.org/browse/JDK-8319451) for now and file a REDO to get rid of the dependency on `BlockLayoutMinDiamondPercentage`. I think this would actually require a CSR though because `BlockLayoutMinDiamondPercentage` is a product flag and we chang it's behavior.

**Comment by merykitty** [comment]
@TobiHartmann Thanks for your suggestion, I have changed this to a backout, I need to also rename the issue, right?

**Comment by eme64** [comment]
@TobiHartmann @merykitty
Usually, you file a `[REDO]`, and make the `[BACKOUT]` a subtask. Example:
https://bugs.openjdk.org/browse/JDK-8323727

**Comment by merykitty** [comment]
@eme64 Thanks for the info, what if we only want to backout the change without the intention of a REDO?

**Comment by TobiHartmann** [comment]
The OpenJDK Guide has all the details, see "Alternative 3":
https://openjdk.org/guide/#backing-out-a-change

I think creating a REDO is fine though, since we definitely want to get rid of the dependency on `BlockLayoutMinDiamondPercentage` at some point. Feel free to leave it unassigned though.

**Comment by merykitty** [comment]
@TobiHartmann Thanks for your suggestion, I have made relevant issues and changed the title of this PR, can you please review it?

**Review by eme64 — APPROVED** [review]
Looks good, it is the exact backout of https://github.com/openjdk/jdk/pull/16524/files.

I guess it is a shame that you are also backing out the microbenchmark, but you can easily push that separately or in your REDO.

**Comment by eme64** [comment]
Aha, I just saw that there are apparently failures on GitHub actions:

```
Failed IR Rules (2) of Methods (2)
----------------------------------
1) Method "public java.lang.Object[] compiler.c2.irTests.TestIfMinMax.testMaxIntReduction(int[],int[])" - [Failed IR rules: 1]:
   * @IR rule 1: "@compiler.lib.ir_framework.IR(phase={DEFAULT}, applyIfPlatformAnd={}, applyIfCPUFeatureOr={"sse4.1", "true", "asimd", "true"}, counts={"_#MAX_REDUCTION_V#_", "> 0"}, failOn={}, applyIfPlatform={}, applyIfPlatformOr={}, applyIfOr={}, applyIfCPUFeatureAnd={}, applyIf={"SuperWordReductions", "true"}, applyIfCPUFeature={}, applyIfAnd={}, applyIfNot={})"
     > Phase "PrintIdeal":
       - counts: Graph contains wrong number of nodes:
         * Constraint 1: "(\d+(\s){2}(MaxReductionV.*)+(\s){2}===.*)"
           - Failed comparison: [found] 0 > 0 [given]
           - No nodes matched!

2) Method "public java.lang.Object[] compiler.c2.irTests.TestIfMinMax.testMinIntReduction(int[],int[])" - [Failed IR rules: 1]:
   * @IR rule 1: "@compiler.lib.ir_framework.IR(phase={DEFAULT}, applyIfPlatformAnd={}, applyIfCPUFeatureOr={"sse4.1", "true", "asimd", "true"}, counts={"_#MIN_REDUCTION_V#_", "> 0"}, failOn={}, applyIfPlatform={}, applyIfPlatformOr={}, applyIfOr={}, applyIfCPUFeatureAnd={}, applyIf={"SuperWordReductions", "true"}, applyIfCPUFeature={}, applyIfAnd={}, applyIfNot={})"
     > Phase "PrintIdeal":
       - counts: Graph contains wrong number of nodes:
         * Constraint 1: "(\d+(\s){2}(MinReductionV.*)+(\s){2}===.*)"
           - Failed comparison: [found] 0 > 0 [given]
           - No nodes matched!
```

Could these be related?

**Comment by eme64** [comment]
It is possible that the test that @jaskarth added in the meantime relied on your change:
https://github.com/openjdk/jdk/commit/9f920b9bbf8a64e2c2db085cf3da30db37c0d1bc

**Comment by eme64** [comment]
I'll run testing from our side, please ask for the results before you integrate.

**Comment by jaskarth** [comment]
Ah yep, looking at the log the main IfNode has `P=0.891189`, so it doesn't succeed the new check `prob > 0.18 && prob < 0.82`. I think this is fundementally the same problem as https://github.com/openjdk/jdk/pull/18734, and increasing the number of predetermined elements ([here](https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/compiler/c2/irTests/TestIfMinMax.java#L184-L194)) should fix this. If it's important to get this patch in quickly though feel free to problemlist the test or disable the IR verification, I can take a look at it soon.

**Comment by merykitty** [comment]
@jaskarth Thanks for your analysis, I added the test to the problem list and created a relevant issue for it.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Review by jaskarth — APPROVED** [review]
Thanks for creating the issue! I've assigned myself to it. The patch looks good to me as well.

**Comment by eme64** [comment]
@merykitty testing looks good (only failed for `compiler/c2/irTests/TestIfMinMax.java` but you now problem-listed it).

**Comment by merykitty** [comment]
@eme64 @TobiHartmann @jaskarth Thanks a lot for your reviews.
/integrate

**Pull request closed without merging**
