### PR TITLE
8291633: Build failures with GCC 11, Alpine 3 due to incompatible casts from nullptr

### PR DESCRIPTION
**Pull request by shipilev**
Looks like GCC and musl that ship in new Alpine 3.15 highlight that some casts from `NULL` and `nullptr` are risky/illegal. 

They fall into three categories:
  - explicitly casting `NULL` to integral type; we can and should use `NULL_WORD` in these cases, like the rest of Hotspot does;
  - using `NULL` in ternary expression when another side is integral type, thus implicitly casting it;
  - `reinterpret_cast`-ing `NULL` to pointer type -- this is dangerous and rightfully breaks; we can use `static_cast` instead.

Additional testing:
 - [x] Linux x86_64 {release, fastdebug, slowdebug} build with Alpine 3.15, GCC 11.2.1
 - [x] Linux x86_64 fastdebug tier1 with GCC 9.3.0

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291633](https://bugs.openjdk.org/browse/JDK-8291633): Build failures with GCC 11, Alpine 3 due to incompatible casts from nullptr

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [59f92b41](https://git.openjdk.org/jdk/pull/9705/files/59f92b414b113bb53c7dca10ec6de0467d8fabef)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [59f92b41](https://git.openjdk.org/jdk/pull/9705/files/59f92b414b113bb53c7dca10ec6de0467d8fabef)
 * [Jie Fu](https://openjdk.org/census#jiefu) (@DamonFool - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9705/head:pull/9705` \
`$ git checkout pull/9705`

Update a local copy of the PR: \
`$ git checkout pull/9705` \
`$ git pull https://git.openjdk.org/jdk pull/9705/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9705`

View PR using the GUI difftool: \
`$ git pr show -t 9705`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9705.diff">https://git.openjdk.org/jdk/pull/9705.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
LGTM

**Review by MBaesken — APPROVED** [review]
Looks good to me, thanks for looking into it.

**Comment by shipilev** [comment]
Thank you! If there are no other reviews, I'll be integrating this soon.

**Comment by DamonFool** [comment]
> Thank you! If there are no other reviews, I'll be integrating this soon.

Maybe, we'd better update the copyright year of src/hotspot/cpu/x86/interpreterRT_x86_64.cpp before integration.
Thanks.

**Comment by shipilev** [comment]
> Maybe, we'd better update the copyright year of src/hotspot/cpu/x86/interpreterRT_x86_64.cpp before integration. Thanks.

Did so in new commit.

**Review by DamonFool — APPROVED** [review]
Thanks for the update.
LGTM

**Pull request closed without merging**
