### PR TITLE
8292158: AES-CTR cipher state corruption with AVX-512

### PR DESCRIPTION
**Pull request by AJ-Ferguson**
Fix cipher state corruption when encrypting/decrypting less than 16 bytes at a time.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292158](https://bugs.openjdk.org/browse/JDK-8292158): AES-CTR cipher state corruption with AVX-512

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Smita Kamath](https://openjdk.org/census#svkamath) (@smita-kamath - Author) ⚠️ Review applies to [360304cf](https://git.openjdk.org/jdk/pull/9635/files/360304cf5cdfaf8dfe68adb0a10459fdb6e3cae0)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9635/head:pull/9635` \
`$ git checkout pull/9635`

Update a local copy of the PR: \
`$ git checkout pull/9635` \
`$ git pull https://git.openjdk.org/jdk pull/9635/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9635`

View PR using the GUI difftool: \
`$ git pr show -t 9635`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9635.diff">https://git.openjdk.org/jdk/pull/9635.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Please, add regression test.

**Comment by robcasloz** [comment]
Hi @AJ-Ferguson, please note that the [JBS issue](https://bugs.openjdk.org/browse/JDK-8292158) is assigned to @smita-kamath, who wrote the original implementation. Please check with Smita or other regular Intel contributors (e.g. @jatin-bhateja, @sviswa7) before moving forward with this changeset.

**Comment by smita-kamath** [comment]
@AJ-Ferguson, will take a look at the PR. Thank you.

**Comment by smita-kamath** [comment]
Hi AJ-Ferguson, I have modified the changes you recommended and added a suggestion. Please have a look at the diff file and let me know what you think. Thanks.
[diff.txt](https://github.com/openjdk/jdk/files/9604614/diff.txt)

**Comment by AJ-Ferguson** [comment]
Hello @smita-kamath, thank you for taking the time to look at this PR. The changes you posted look good to me. I have added your improvements and updated the branch.

**Review by smita-kamath — APPROVED** [review]

**Comment by sviswa7** [comment]
@AJ-Ferguson Please do add a test for this case.

**Comment by AJ-Ferguson** [comment]
@sviswa7 @vnkozlov I have added the test. Please let me know if there are any issues.

**Review by vnkozlov — COMMENTED** [review]
Good. I submitted testing.

**Review by vnkozlov — APPROVED** [review]
Testing passed.

**Review by sviswa7 — APPROVED** [review]
Looks good to me as well.

**Comment by AJ-Ferguson** [comment]
Thank you for the reviews.

/integrate

**Pull request closed without merging**
