### PR TITLE
8279358: vmTestbase/nsk/jvmti/scenarios/jni_interception/JI03/ji03t003/TestDescription.java fails with usage tracker 

### PR DESCRIPTION
**Pull request by alexmenkov**
The test counts calls of intercepted JNI functions, but doesn't completely filter out calls from other threads.
Function isThreadExpected is used only for ExceptionOccurred function and the function checks only some known JFR/Graal threads.

The change:
 - updates the test to count only the calls on the test thread;
 - adds verbose output.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8279358](https://bugs.openjdk.java.net/browse/JDK-8279358): vmTestbase/nsk/jvmti/scenarios/jni_interception/JI03/ji03t003/TestDescription.java fails with usage tracker

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [eb4626bb](https://git.openjdk.java.net/jdk/pull/8475/files/eb4626bbc46a57c6ee5460baffe799797ddf1735)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8475/head:pull/8475` \
`$ git checkout pull/8475`

Update a local copy of the PR: \
`$ git checkout pull/8475` \
`$ git pull https://git.openjdk.java.net/jdk pull/8475/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8475`

View PR using the GUI difftool: \
`$ git pr show -t 8475`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8475.diff">https://git.openjdk.java.net/jdk/pull/8475.diff</a>

</details>

### CODE REVIEW

**Comment by plummercj** [comment]
What about ji01t001? Seems it can suffer from the same issues. I know I see the WARNING message in its output for unexpected intercept calls.

**Comment by plummercj** [comment]
Also there is [JDK-8284027](https://bugs.openjdk.java.net/browse/JDK-8284027), which also is a failure related to unexpected threads and fails because isThreadExpected() is not filtering all the proper threads (loom makes this issue worse). It looks like you are trying to make the individual tests smarter rather than fixing isThreadExpected(). I'm not saying this is the wrong approach, but we should apply the approach to all tests that use isThreadExpected() .

**Comment by alexmenkov** [comment]
@plummercj ji01t001 checks that the number of the calls >= of the expected.
I thought about make the same condition here, but decided that it would be better to verify for equality, but ensure we count the calls from the test thread only

**Review by sspitsyn — APPROVED** [review]
It looks good.
It needs to be coordinated with Chris who is in process of fixing similar issue in Loom but for different nsk.jvmti test: ji01t001. As I see you already have some comment exchange.

**Comment by alexmenkov** [comment]
I did something wrong with the PR, going to recreate it

**Pull request closed without merging**
