### PR TITLE
8343467: Remove unnecessary @SuppressWarnings annotations (security)

### PR DESCRIPTION
**Pull request by archiecobbs**
Please review this patch which removes unnecessary `@SuppressWarnings` annotations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343467](https://bugs.openjdk.org/browse/JDK-8343467): Remove unnecessary @SuppressWarnings annotations (security) (**Sub-task** - P5)

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21844/head:pull/21844` \
`$ git checkout pull/21844`

Update a local copy of the PR: \
`$ git checkout pull/21844` \
`$ git pull https://git.openjdk.org/jdk.git pull/21844/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21844`

View PR using the GUI difftool: \
`$ git pr show -t 21844`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21844.diff">https://git.openjdk.org/jdk/pull/21844.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21844#issuecomment-2452692252)
</details>

### CODE REVIEW

**Comment by seanjmullan** [comment]
The files under `src/java.xml.crypto/share/classes/com/sun/org/apache/xml/internal/security/` and `src/java.xml.crypto/share/classes/org/jcp/xml/dsig/internal/dom` come from 3rd party source code where these warnings are still emitted. Please do not incorporate these changes since it would cause the JDK code to diverge.

**Comment by archiecobbs** [comment]
> The files under `src/java.xml.crypto/share/classes/com/sun/org/apache/xml/internal/security/` and `src/java.xml.crypto/share/classes/org/jcp/xml/dsig/internal/dom` come from 3rd party source code where these warnings are still emitted. Please do not incorporate these changes since it would cause the JDK code to diverge.

@seanjmullan - thanks for the heads-up. Those files should be reverted in dc5340d9f05.

**Comment by seanjmullan** [comment]
Thanks. Can you also explain why the unchecked and serial warning suppressions are no longer needed?

**Comment by archiecobbs** [comment]
> Can you also explain why the unchecked and serial warning suppressions are no longer needed?

Yes and no...

The annoying answer would be: because they no longer suppress any warnings :)

But I think what you're really asking is: how & why they were put there in the first place? And how over time did they somehow became no longer necessary?

That's a great question, but I don't have any answers because these changes were generated from an automated analysis.

**Comment by seanjmullan** [comment]
> But I think what you're really asking is: how & why they were put there in the first place? And how over time did they somehow became no longer necessary?

Yes.

> That's a great question, but I don't have any answers because these changes were generated from an automated analysis.

Can we find this out? It would be really useful to explain why the warnings are no longer an issue.

**Comment by archiecobbs** [comment]
> Can we find this out? It would be really useful to explain why the warnings are no longer an issue.

I haven't checked exhaustively, but all of the ones I've checked appear to be due to either (a) the warning was never needed, or (b) a subsequent refinement of the warning itself which made the code no longer qualify as "warnable".

For an example of (a) see commit 8fb70c710afa which added `@SuppressWarnings("unchecked")` for a cast to type `Key`, even though `Key` is not a generic type and so the cast was never unchecked in the first place.

For an example of (b), see commit b431c6929d12 which added `@SuppressWarnings("serial")` because an anonymous class did not declare `serialVersionUID`, but then later the warning was was changed to no longer trigger in that situation by [JDK-7152104](https://bugs.openjdk.org/browse/JDK-7152104), but the annotation was not removed as part of that commit.

I guess the only other possibility is that the warning stopped working at some point due to a bug, but I haven't seen any examples of that.

**Review by seanjmullan — APPROVED** [review]
The bug needs an appropriate `noreg` label (I suggest `noreg-cleanup`). Otherwise, looks good to me.

**Pull request closed without merging**
