### PR TITLE
8271396: Spelling errors

### PR DESCRIPTION
**Pull request by ebourg**
This PR fixes the following spelling errors:

 choosen  -> chosen
 commad   -> command
 hiearchy -> hierarchy
 leagacy  -> legacy
 minium   -> minimum
 subsytem -> subsystem
 unamed   -> unnamed

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271396](https://bugs.openjdk.java.net/browse/JDK-8271396): Spelling errors

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to a0937d2619186488ebf50db2da50b78c73d41033
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to a0937d2619186488ebf50db2da50b78c73d41033
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Prasanta Sadhukhan](https://openjdk.java.net/census#psadhukhan) (@prsadhuk - **Reviewer**) ⚠️ Review applies to 31cfcba7eef6c5557f928f7285b4f9b5fdeff5ba
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to 31cfcba7eef6c5557f928f7285b4f9b5fdeff5ba

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2385/head:pull/2385` \
`$ git checkout pull/2385`

Update a local copy of the PR: \
`$ git checkout pull/2385` \
`$ git pull https://git.openjdk.java.net/jdk pull/2385/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2385`

View PR using the GUI difftool: \
`$ git pr show -t 2385`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2385.diff">https://git.openjdk.java.net/jdk/pull/2385.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by ChrisHegarty — APPROVED** [review]
Trivially, looks ok to me.

**Comment by ebourg** [comment]
.

**Comment by ebourg** [comment]
.

**Comment by kelthuzadx** [comment]
Hi, I've filed https://bugs.openjdk.java.net/browse/JDK-8271396 for this PR, you can change the title to "8271396: Spelling errors", openjdk bot will link this PR to the corresponding issue. Also you should resolve conflicts and pass jcheck before integrating it.

**Comment by ebourg** [comment]
Thank you!

**Comment by ebourg** [comment]
The PR has been updated

**Review by irisclark — APPROVED** [review]

**Review by prsadhuk — APPROVED** [review]
Thanks for awt/swing correction.

**Review by plummercj — APPROVED** [review]
jdi, jvmti, and dcmd related changes look good.

**Comment by FrauBoes** [comment]
I'm happy to sponsor this change, but could you please update the copyright year where necessary, e.g. in 
src/java.desktop/unix/classes/sun/awt/X11/XMSelection.java: 
`Copyright (c) 2003, 2018, Oracle...` -> `Copyright (c) 2003, 2021, Oracle...`

**Comment by ebourg** [comment]
@FrauBoes thank you, the PR has been updated to modify the copyright year

**Comment by kevinrushforth** [comment]
@ebourg for future PRs please do not force push after the PR is out for review. Just push incremental comments normally. The Skara tooling will squash them all into a single commit.

**Review by irisclark — APPROVED** [review]

**Comment by ebourg** [comment]
@kevinrushforth I'll do that, thank you for the hint

**Comment by FrauBoes** [comment]
@ebourg Thanks for updating the copyright. If you integrate again, I can sponsor sponsor.

**Comment by ebourg** [comment]
Thank you, glad to land my first commit to OpenJDK

**Pull request closed without merging**
