### PR TITLE
8343793: Test java/foreign/TestMemorySession.java is timing out

### PR DESCRIPTION
**Pull request by merykitty**
Hi,

This patch fixes the deadlock in `TestMemorySession#testAcquireCloseRace`. The lock-step spin lock is implemented as with `lock` being an `AtomicInteger`:

    // Keep the 2 threads operating on the same scope
    int k = lock.getAndAdd(1) + 1;
    while (k != i * 2) {
        Thread.onSpinWait();
        k = lock.get();
    }

Given the initial condition:

    Thread 1: i = 0
    Thread 2: i = 0
    lock: -2

The `lock` then undergoes the following operations:

        Thread 1          Thread 2         lock value
      getAndAdd(1)                            -1
                        getAndAdd(1)           0 -> Thread 2 then continues its next iteration, its i value is now 1
                        getAndAdd(1)           1 -> Thread 2 reaches the next iteration before thread 1 has a chance to read the value 0
          get()                                1 -> Thread 1 now cannot proceed because it missed the value 0
                           get()               1 -> Thread 2 now cannot proceed because lock can never reach 2

The solution is to not rely on the exact value of the lock but instead whether the lock has passed the expected value.

Testing: I have run this test several hundreds times and got no failure while without this patch I encountered a timeout every approximately 30 times.

Please take a look, thanks a lot.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343793](https://bugs.openjdk.org/browse/JDK-8343793): Test java/foreign/TestMemorySession.java is timing out (**Bug** - P3)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21976/head:pull/21976` \
`$ git checkout pull/21976`

Update a local copy of the PR: \
`$ git checkout pull/21976` \
`$ git pull https://git.openjdk.org/jdk.git pull/21976/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21976`

View PR using the GUI difftool: \
`$ git pr show -t 21976`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21976.diff">https://git.openjdk.org/jdk/pull/21976.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21976#issuecomment-2464576568)
</details>

### CODE REVIEW

**Comment by mcimadamore** [comment]
I'm playing with something like this:

```
@Test
    public void testAcquireCloseRace() throws InterruptedException {
        int MAX_ITERATIONS = 1000;
        AtomicInteger iteration = new AtomicInteger();
        boolean[] result = new boolean[1];
        MemorySessionImpl[] scopes = new MemorySessionImpl[MAX_ITERATIONS];
        for (int i = 0; i < MAX_ITERATIONS; i++) {
            scopes[i] = MemorySessionImpl.toMemorySession(Arena.ofShared());
        }

        // This thread tries to close the scopes
        Thread t1 = new Thread(() -> {
            int it = iteration.get();
            while (it < MAX_ITERATIONS) {
                while (true) {
                    try {
                        scopes[it].close();
                        // if we close successfully, the iteration is now completed
                        break;
                    } catch (IllegalStateException e) {
                        // scope is acquired, wait and try again
                        Thread.onSpinWait();
                    }
                }
                // wait for other thread to complete its iteration
                int prev = it;
                while (prev == it) {
                    Thread.onSpinWait();
                    it = iteration.get();
                }
            }
        });

        // This thread tries to acquire the scopes, then check if it is alive after an acquire failure
        Thread t2 = new Thread(() -> {
            int it = iteration.get();
            while (it < MAX_ITERATIONS) {
                while (true) {
                    try {
                        scopes[it].acquire0();
                    } catch (IllegalStateException e) {
                        // we failed to acquire, meaning the other thread has closed this scope
                        if (scopes[it].isAlive()) {
                            result[0] = true;
                        }
                        // this iteration is now completed
                        break;
                    }
                    // if we get here, acquire was successful, so we need to release...
                    scopes[it].release0();
                    // ... and then try again
                }
                // advance to next iteration
                it = iteration.addAndGet(1);
            }
        });

        t1.start();
        t2.start();
        t1.join();
        t2.join();
        assertFalse(result[0]);
    }
```

I think I find this logic a bit more direct:

* both thread agree on an iteration count (the atomic integer)
* thread A keeps trying closing a scope -- if it succeds, its iteration is done, and it waits for the next thread to be done
* thread B keeps acquiring and releasing a scope -- if it fails to acquire, that means that the scope is closed by the other thread, so this iteration is done, and we can update the shared iteration counter

What do you think?

**Comment by merykitty** [comment]
@mcimadamore I think your approach is more or less similar. Although it is a little bit clearer in terms of what index we are operating on, it is a bit less clear in terms of the synchronization mechanism, as it is spread out to a wider scope.

**Comment by mcimadamore** [comment]
> @mcimadamore I think your approach is more or less similar. Although it is a little bit clearer in terms of what index we are operating on, it is a bit less clear in terms of the synchronization mechanism, as it is spread out to a wider scope.

IMHO both synchronization mechanisms are spread out in scope, as no matter what you'll have an action at a distance. FWIW, I find the logic with index updating particularly hard to read -- and a very indirect way to coordinate the two threads, which is why I tried to reach for something a little more explicit.

**Comment by JornVernee** [comment]
I think I also prefer Maurizio's version.

**Comment by merykitty** [comment]
Sure, I have refactored the test, no failure after 200 runs.

**Comment by merykitty** [comment]
Thanks for your reviews and suggestions. I have run the test a couple hundred times more, and there is no failure. GHA failures are in Installing dependencies steps, I have rerun it some times and there is no other failure there.
/integrate

**Pull request closed without merging**
