### PR TITLE
8252001: remove usage of PropertyResolvingWrapper in vmTestbase/nsk/jdi

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review the patch which removes `PropertyResolvingWrapper` from `vmTestbase/nsk/jdi`? other than the removal of `PropertyResolvingWrapper` from jtreg actions, the patch also 
 - `s/"-debugee.vmkeys=/-debugee.vmkeys="/`
 - removed `ExecDriver` there it's not needed anymore
 - as jtreg doesn't support static nested classes as main test classes, all `EventTestTemplates`s inner classes were moved up and the tests were updated accordingly
 - appended ${java.class.path} to `-cp` in the tests which specify classpath, otherwise, these tests fail due to CNFE of jtreg tests
 - escaped `"` on windows in `nsk.share.jdi.Binder`
 - replaced default quote (`"`) w/ `\0` in `n.s.j.Binder` so there will be no clashes w/ `"` from actions

testing: ✅ `vmTestbase/nsk/jdi` tests on `{linux,windows,macos}-x64`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252001](https://bugs.openjdk.java.net/browse/JDK-8252001): remove usage of PropertyResolvingWrapper in vmTestbase/nsk/jdi

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/379/head:pull/379`
`$ git checkout pull/379`

### CODE REVIEW

**Review by plummercj — APPROVED** [review]
Looks good. In the future I would like to see something like this broken up so as to not mix the smaller changes in with the massive repetitive changes.

**Comment by iignatev** [comment]
> Looks good. In the future I would like to see something like this broken up so as to not mix the smaller changes in with the massive repetitive changes.

thanks, Chris. unfortunately, most of the changes here weren't self-sufficient or meaningful on their own, so they couldn't be (easily?) broken up. you could have though reviewed the patch as if it were broken up by reviewing each particular commit separately.

**Comment by sspitsyn** [comment]
Igor,
Not sure, I understand some of the fixes.
For example:

```
diff --git a/test/hotspot/jtreg/vmTestbase/nsk/jdi/MonitorContendedEnteredRequest/addThreadFilter/TestDescription.java b/test/hotspot/jtreg/vmTestbase/nsk/jdi/MonitorContendedEnteredRequest/addThreadFilter/TestDescription.java
index 9b4967020b1..b75a9749208 100644
--- a/test/hotspot/jtreg/vmTestbase/nsk/jdi/MonitorContendedEnteredRequest/addThreadFilter/TestDescription.java
+++ b/test/hotspot/jtreg/vmTestbase/nsk/jdi/MonitorContendedEnteredRequest/addThreadFilter/TestDescription.java
@@ -39,7 +39,7 @@
  *                 - add to request filter for single thread
  *                 - add to request filter for the same thread 2 times, expect behavior such as in previous case
  *                 - add to request filter for 2 different threads, so events shouldn't be received
- *         Test executes class nsk.share.jdi.EventTestTemplates$ClassExclusionFilterTest which uses JDI events testing
+ *         Test executes class nsk.share.jdi.ClassExclusionFilterTest which uses JDI events testing
  *         framework based on classes from package nsk.share.jdi.*.
  *         This framework uses following scenario:
  *                 - debugger VM forces debugge VM to create number of objects which should generate events during test
@@ -57,17 +57,17 @@
  *
  * @library /vmTestbase
  *          /test/lib
- * @build nsk.share.jdi.EventTestTemplates
+ * @build nsk.share.jdi.ThreadFilterTest
  *        nsk.share.jdi.JDIEventsDebuggee
  *        nsk.share.jdi.MonitorEventsDebuggee
- * @run main/othervm/native PropertyResolvingWrapper
- *      nsk.share.jdi.EventTestTemplates$ThreadFilterTest
+ * @run main/othervm/native
+ *      nsk.share.jdi.ThreadFilterTest
```
The EventTestTemplates$StressTestTemplate is replaced with StressTestTemplate in the comment.
However, the @build and @run commands replaces the EventTestTemplates or EventTestTemplates$ThreadFilterTest with the ThreadFilterTest. Is this intentional?
There are several files with such mismatches.

**Comment by iignatev** [comment]
@sspitsyn , I just `s/nsk.share.jdi.EventTestTemplates$/nsk.share.jdi` and then replaced `nsk.share.jdi.EventTestTemplates` in `@build` w/ appropriate form inner class of `n.s.j.EventTestTemplates`, e.g.  `ThreadFilterTest`. and the end, the tests execute the (simantically) same classes as before.

The discrepancy b/w comments and `@run` directives are pre-existing, I'll file a separate issue to clean them up.

**Review by sspitsyn — APPROVED** [review]
@iignatev
Thank you for explanation and filing a new bug.
I'm okay with this update.

**Comment by iignatev** [comment]
for the record, the RFE to clean up the comments -- [8253864](https://bugs.openjdk.java.net/browse/JDK-8253864)

**Pull request closed without merging**
