### PR TITLE
8320175: [BACKOUT] 8316533: C2 compilation fails with assert(verify(phase)) failed: missing Value() optimization

### PR DESCRIPTION
**Pull request by eme64**
This reverts commit b5c863b772603b3fbf159d2bd3f6d1caffaff16a. [JDK-8316533](https://bugs.openjdk.org/browse/JDK-8316533).

The patch fixed a bug in verification, but created a regression which will take more time to investigate and fix. Hence the backout for now.

Testing: passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320175](https://bugs.openjdk.org/browse/JDK-8320175): [BACKOUT] 8316533: C2 compilation fails with assert(verify(phase)) failed: missing Value() optimization (**Sub-task** - P3)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17425/head:pull/17425` \
`$ git checkout pull/17425`

Update a local copy of the PR: \
`$ git checkout pull/17425` \
`$ git pull https://git.openjdk.org/jdk.git pull/17425/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17425`

View PR using the GUI difftool: \
`$ git pr show -t 17425`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17425.diff">https://git.openjdk.org/jdk/pull/17425.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17425#issuecomment-1892210014)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good and trivial.

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too.

**Comment by eme64** [comment]
Thanks for the reviews @chhagedorn @TobiHartmann 
/integrate

**Pull request closed without merging**
