### PR TITLE
JDK-8303154: Investigate and improve instruction cache flushing during compilation

### PR DESCRIPTION
**Pull request by dafedafe**
It was noticed that we flush the instruction cache too much for a single C1 compilation. The same is true for the C2 compilation.
There are several places in the code where the instruction cache is called and many of them are very intertwined (see [bug report](https://bugs.openjdk.org/browse/JDK-8303154)).

This PR is meant to be a "minimum" set of changes that improve the situation without introducing excessive extra information to keep track of the origin of the call through call stacks. This is done by avoiding calls to flush the ICache:
* at `Compilation::emit_code_epilog`
* when calling `CodeCache::commit` as flushing is done anyway when copying from the temporary buffer into the code cache in `CodeBuffer::copy_code_to`. This results in flushing the ICache only once instead of 3 times for a C1 compilation and twice for a C2 compilation. Additionally this halves the number of flushes during adapters generation (lots of calls).
* at `SharedRuntime::generate_i2c2i_adapters` as this is called with a temporary buffer and an ICache flush is not needed

This change decreases the number of calls to flush the ICache for a simple _Hello world_ program on Mac OSX aarch64 from 3569 to 2028 on C1 (43.2% improvement) and from  3572 to 1952 on C2 (45.4% improvement).

This fix includes changes for x86_32/64 and aarch64, which I could test thoroughly but also for **arm** and **riscv**, for which I would need some help with testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303154](https://bugs.openjdk.org/browse/JDK-8303154): Investigate and improve instruction cache flushing during compilation

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [2e119cb1](https://git.openjdk.org/jdk/pull/12877/files/2e119cb1d92930a33d04c65b263c670f91b521d3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12877/head:pull/12877` \
`$ git checkout pull/12877`

Update a local copy of the PR: \
`$ git checkout pull/12877` \
`$ git pull https://git.openjdk.org/jdk pull/12877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12877`

View PR using the GUI difftool: \
`$ git pr show -t 12877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12877.diff">https://git.openjdk.org/jdk/pull/12877.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Did you look on how many times we flush ICache during adapters generation?
It has most numerous cases when I looked on it:
"CodeCache::commit() is also used for adapters. But adapters uses RuntimeBlob which calls CodeBuffer::copy_code_to()."

I thought we would remove flush from CodeCache::commit() and not from copy_code_to().

**Comment by dafedafe** [comment]
> Did you look on how many times we flush ICache during adapters generation? It has most numerous cases when I looked on it: "CodeCache::commit() is also used for adapters. But adapters uses RuntimeBlob which calls CodeBuffer::copy_code_to()."

@vnkozlov the ICache flushing was called 1596 times during adapters generation with C1. You're right, these are by far the most calls and the flush calls are also performed twice in these cases, once in `CodeBuffer::copy_code_to()` and  once in `CodeCache::commit()` (I've missed it).
 
> I thought we would remove flush from CodeCache::commit() and not from copy_code_to().

I thought it would make more sense to keep the flush in `CodeCache::commit()` since it was generally the last call made but, in light of what you're pointing out, it would definitely make more sense to remove it from `CodeCache::commit()` and only leave it in `copy_code_to`. This also halves the number of flushing coming from adapters.

**Comment by dafedafe** [comment]
@vnkozlov @TobiHartmann I pushed the changes if you want to have a look at them again. Thanks a lot!

**Review by vnkozlov — APPROVED** [review]
Good. What are new numbers of of calls to flush the ICache?

**Comment by vnkozlov** [comment]
@dafedafe I look on stack traces you collected. Please look on this:
```
 732  Stack: 
    ICache::invalidate_range(unsigned char *, int) icache_bsd_aarch64.hpp:41
    AbstractAssembler::flush() assembler.cpp:110
    SharedRuntime::generate_i2c2i_adapters(MacroAssembler *, int, int, const BasicType *, const VMRegPair *, AdapterFingerPrint *) sharedRuntime_aarch64.cpp:794
    AdapterHandlerLibrary::create_adapter(AdapterBlob *&, int, BasicType *, bool) sharedRuntime.cpp:2970 
```
`generate_i2c2i_adapters` is called for temporary buffer so we don't need to flush it:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/sharedRuntime.cpp#L2870

**Comment by dafedafe** [comment]
> Good. What are new numbers of of calls to flush the ICache?

The total number of flushes for the _HelloWorld_ on Mac OSX aarch64 go from 3569 to 2756 on C1 (22.8% improvement) and from 3572 to 2685 on C2 (24.1% improvement).

**Comment by dafedafe** [comment]
> @dafedafe I look on stack traces you collected. Please look on this:
> 
> ```
>  732  Stack: 
>     ICache::invalidate_range(unsigned char *, int) icache_bsd_aarch64.hpp:41
>     AbstractAssembler::flush() assembler.cpp:110
>     SharedRuntime::generate_i2c2i_adapters(MacroAssembler *, int, int, const BasicType *, const VMRegPair *, AdapterFingerPrint *) sharedRuntime_aarch64.cpp:794
>     AdapterHandlerLibrary::create_adapter(AdapterBlob *&, int, BasicType *, bool) sharedRuntime.cpp:2970 
> ```
> generate_i2c2i_adapters is called for temporary buffer so we don't need to flush it:


Yes, thanks a lot @vnkozlov! I've removed the flushing there too.
Now the number of flushes for _HelloWorld_ is down to 2028 with C1 (43% improvement).

**Comment by vnkozlov** [comment]
Nice! Good work. Now please thoroughly test it.

**Review by TobiHartmann — APPROVED** [review]
Good catch, Vladimir. New version looks good to me too.

**Comment by dafedafe** [comment]
This fix includes some changes to `sharedRuntime` for multiple platforms. I could thoroughly test a x86_32/64 and aarch64 but I'd need some help testing on **ARM** and **RISCV**.
@RealFYang could you or someone you know please run some testing for **RISCV** to make sure my change doesn't break anything? @bulasevich @shqking could I ask you the same for **ARM**?
Thank you very much in advance for your help!

**Comment by vnkozlov** [comment]
@dafedafe  as followup RFE (I don't want to add more changes to this PR) look on all uses of `masm::flush()` for **temporary** buffers. I see such uses in some other `SharedRuntime` methods: [SharedRuntime::generate_resolve_blob](https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/sharedRuntime_x86_64.cpp#L3299)
There are may be only few but since we start fixing such cases we should finish.

**Comment by TobiHartmann** [comment]
FTR, the follow-up RFE is [JDK-8303971](https://bugs.openjdk.org/browse/JDK-8303971).

**Comment by dafedafe** [comment]
> @dafedafe as followup RFE (I don't want to add more changes to this PR) look on all uses of `masm::flush()` for **temporary** buffers. I see such uses in some other `SharedRuntime` methods: [SharedRuntime::generate_resolve_blob](https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/sharedRuntime_x86_64.cpp#L3299)
> There are may be only few but since we start fixing such cases we should finish.

Sure! Thanks for the hint @vnkozlov.

**Comment by RealFYang** [comment]
Hi, I performed tier1-3 tests on linux-riscv64 boards, result looks good.

**Comment by dafedafe** [comment]
@RealFYang thank you very much for running the tests!

**Comment by bulasevich** [comment]
HI, tier1-2 tests on ARM32 are OK!

**Comment by dafedafe** [comment]
@TobiHartmann @vnkozlov thanks a lot for your reviews!

**Pull request closed without merging**
