### PR TITLE
8272725: G1: add documentation on needs_remset_update_t vs bool

### PR DESCRIPTION
**Pull request by albertnetymk**
Simple type change in `struct G1HeapRegionAttr`.

Test: hotspot_gc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272725](https://bugs.openjdk.java.net/browse/JDK-8272725): G1: add documentation on needs_remset_update_t vs bool

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5188/head:pull/5188` \
`$ git checkout pull/5188`

Update a local copy of the PR: \
`$ git checkout pull/5188` \
`$ git pull https://git.openjdk.java.net/jdk pull/5188/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5188`

View PR using the GUI difftool: \
`$ git pr show -t 5188`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5188.diff">https://git.openjdk.java.net/jdk/pull/5188.diff</a>

</details>

### CODE REVIEW

**Comment by tschatzl** [comment]
The use of `uint8_t` in this case is intentional to have control of the size of the table, keeping it small and access time fairly small to minimize cache pollution. The size of `bool` is not defined in C++ after all. This could "waste" a lot of (cache) space.

When `G1HeapRegionAttr` has been introduced there has been a related performance issue with SPARC where this mattered which is gone now - I do not remember x64/x86 being particularly affected, but idk impact on the "new" ARM64 platform.

Anyway, it seems better to me to make sure that in this case we keep the size of the heap region attr controlled. It's being accessed for literally every reference multiple times.

**Comment by kimbarrett** [comment]
A comment describing the rationale for the specific types might have been nice.  I think there might have been something there in the past, but maybe removed with SPARC support.  But I agree that this is a place where we really do care about low-level control.

**Comment by albertnetymk** [comment]
I see; thank you for the explanation. How about I pivot this ticket/PR to adding some comment on the use of `uint8_t`?

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
