### PR TITLE
8277881 Missing SessionID in TLS1.3 resumption in compatibility mode

### PR DESCRIPTION
**Pull request by djelinski**
All TLS 1.3 handshakes in compatibility mode must send a non-empty SessionID field. Currently TLS1.3 session resumptions are sending empty session ID. This patch fixes that problem.

All jdk_core tests passed. The newly added check passes with the patch, fails without it.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277881](https://bugs.openjdk.java.net/browse/JDK-8277881): Missing SessionID in TLS1.3 resumption in compatibility mode

### Reviewers
 * [Anthony Scarpino](https://openjdk.java.net/census#ascarpino) (@ascarpino - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6583/head:pull/6583` \
`$ git checkout pull/6583`

Update a local copy of the PR: \
`$ git checkout pull/6583` \
`$ git pull https://git.openjdk.java.net/jdk pull/6583/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6583`

View PR using the GUI difftool: \
`$ git pr show -t 6583`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6583.diff">https://git.openjdk.java.net/jdk/pull/6583.diff</a>

</details>

### CODE REVIEW

**Review by ascarpino — CHANGES_REQUESTED** [review]
Please add " 2021," to the copyright of ResumeTLS13withSNI.java.
I have run all the tests and they pass.

Have you run this fix on your customer's setup or similar setup to confirm this fixed their problem?

**Comment by djelinski** [comment]
Thanks @ascarpino for reviewing. Copyright year updated.

Yes I confirmed that the updated version fixes the problem.

Interestingly, aside from the empty SessionID there were no other differences between the initial and resumption ClientHello messages, i.e. pre_shared_key extension was absent in both. I suppose the server didn't send any NewSessionTicket, but didn't investigate it further.

**Review by ascarpino — APPROVED** [review]
Approved

**Pull request closed without merging**
