### PR TITLE
8291472: [macos] jawt 1.4 lock/unlock not supported

### PR DESCRIPTION
**Pull request by alisenchung**
Removing if check for unsupported jawt versions

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291472](https://bugs.openjdk.org/browse/JDK-8291472): [macos] jawt 1.4 lock/unlock not supported (**Bug** - P4)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19639/head:pull/19639` \
`$ git checkout pull/19639`

Update a local copy of the PR: \
`$ git checkout pull/19639` \
`$ git pull https://git.openjdk.org/jdk.git pull/19639/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19639`

View PR using the GUI difftool: \
`$ git pr show -t 19639`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19639.diff">https://git.openjdk.org/jdk/pull/19639.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19639#issuecomment-2159295427)

### CODE REVIEW

**Comment by mrserb** [comment]
Is it possible to cover this fix by the test?

**Comment by alisenchung** [comment]
> Is it possible to cover this fix by the test?

How would I go about writing a test?

**Comment by prrace** [comment]
@mrserb can you look at this one.

**Comment by mrserb** [comment]
> @mrserb can you look at this one.

The change looks fine. I remember we had a task to test jawt functionality, but seems we still do not create any tests for this area.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
