### PR TITLE
8276173: Clean up and remove unneeded casts in HeapDumper

### PR DESCRIPTION
**Pull request by lkorinth**
HeapDumper does a lot of unneeded casts. Some arguments should be const. Headers are not correctly sorted. Comment about identifier size on Windows and Solaris is not true.

First I cleaned up casting in the "union casting", but then I decided it was better to create a temporary bit_cast that we can use until we get the proper one in c++20.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276173](https://bugs.openjdk.java.net/browse/JDK-8276173): Clean up and remove unneeded casts in HeapDumper

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6211/head:pull/6211` \
`$ git checkout pull/6211`

Update a local copy of the PR: \
`$ git checkout pull/6211` \
`$ git pull https://git.openjdk.java.net/jdk pull/6211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6211`

View PR using the GUI difftool: \
`$ git pr show -t 6211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6211.diff">https://git.openjdk.java.net/jdk/pull/6211.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
This looks good.

**Review by hseigel — APPROVED** [review]
Looks good!
Thanks, Harold

**Comment by lkorinth** [comment]
Thanks Coleen and Harold!
/integrate

**Pull request closed without merging**
