### PR TITLE
8268664: The documentation of the Scanner.hasNextLine is incorrect

### PR DESCRIPTION
**Pull request by igraves**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268664](https://bugs.openjdk.java.net/browse/JDK-8268664): The documentation of the Scanner.hasNextLine is incorrect

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4547/head:pull/4547` \
`$ git checkout pull/4547`

Update a local copy of the PR: \
`$ git checkout pull/4547` \
`$ git pull https://git.openjdk.java.net/jdk pull/4547/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4547`

View PR using the GUI difftool: \
`$ git pr show -t 4547`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4547.diff">https://git.openjdk.java.net/jdk/pull/4547.diff</a>

</details>

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Review by bplb — APPROVED** [review]
+1

**Review by irisclark — APPROVED** [review]
Associated CSR also Reviewed.

**Pull request closed without merging**
