### PR TITLE
8303276: Secondary assertion failure in AdapterHandlerLibrary::contains during crash reporting

### PR DESCRIPTION
**Pull request by coleenp**
Don't check lock ownership if an error has been reported.
Ran tier1-4 tests which include some intentionally crashing tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303276](https://bugs.openjdk.org/browse/JDK-8303276): Secondary assertion failure in AdapterHandlerLibrary::contains during crash reporting

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to [e9810ef3](https://git.openjdk.org/jdk/pull/13500/files/e9810ef31d8127c49281e5c18f0643f63c456700)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [e9810ef3](https://git.openjdk.org/jdk/pull/13500/files/e9810ef31d8127c49281e5c18f0643f63c456700)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13500/head:pull/13500` \
`$ git checkout pull/13500`

Update a local copy of the PR: \
`$ git checkout pull/13500` \
`$ git pull https://git.openjdk.org/jdk.git pull/13500/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13500`

View PR using the GUI difftool: \
`$ git pr show -t 13500`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13500.diff">https://git.openjdk.org/jdk/pull/13500.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13500#issuecomment-1511938305)

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Not sure I agree with this. If there is code that gets called on the error-handler path and it can't be called due to issues like this then we need to know about that and try to fix the code. Ignoring the need for locking or safepoints could just lead to different secondary crashes.

**Comment by dholmes-ora** [comment]
More specifically I think we need to evaluate on a case by case basis - so the check for `is_error_reported()` would be in the function with the `assert_locked_or_safepoint`. This is a bit messy syntactically.
```
\#ifdef ASSERT
if (!VM_Error::is_error_reported()) assert_locked_or_safepoint(...);
\#endif
```

**Comment by dholmes-ora** [comment]
> we trade a guaranteed secondary error against a very unlikely one

I would say we trade a very obvious secondary error for a potentially very obscure one. If you don't hold the lock, nor are at a safepoint, then the access is inherently unsafe. You may not crash you may just get bad or misleading data which could then send you off on a wild goose chase.

Time will tell ...

**Review by iklam — APPROVED** [review]
LGTM

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by coleenp** [comment]
Thanks Thomas and Ioi.  I remerged mainline and the aarch64 failures in GHA went away.
/integrate

**Pull request closed without merging**
