### PR TITLE
8250635: MethodArityHistogram should use Compile_lock in favour of fancy checks

### PR DESCRIPTION
**Pull request by RealLucy**
This change was already fully reviewed before the Mercurial to Git transition. 
Reviewed-by: thartmann (TobiHartmann), mdoerr (TheRealMDoerr).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8250635](https://bugs.openjdk.java.net/browse/JDK-8250635): MethodArityHistogram should use Compile_lock in favour of fancy checks

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/321/head:pull/321`
`$ git checkout pull/321`

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
I had already reviewed it on the mailing list.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by RealLucy** [comment]
Thank you, Tobias and Martin,
for reacting so promptly.

/integrate requested.

Regards,
Lutz

**Pull request closed without merging**
