### PR TITLE
8252773: [TESTBUG] serviceability/jvmti/GetObjectSizeOverflow fails due to OOM conditions

### PR DESCRIPTION
**Pull request by mychris**
The test case already handles out of memory conditions, but not if the whole JVM crashes because of it.

This PR has already been discussed on the mailing list: https://mail.openjdk.java.net/pipermail/serviceability-dev/2020-September/032884.html

@plummercj please review this PR again. I also need a sponsor for this change.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252773](https://bugs.openjdk.java.net/browse/JDK-8252773): [TESTBUG] serviceability/jvmti/GetObjectSizeOverflow fails due to OOM conditions

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/38/head:pull/38`
`$ git checkout pull/38`

### CODE REVIEW

**Comment by plummercj** [comment]
The changes look good. I pulled your branch and submitted testing of the moved test on various hosts and with various GCs and they all have passed. It also passes tier1 testing.

I can't sponsor this commit at the moment since I am still trying to get up to speed with GIT. Maybe later this week. You can also try to find another sponsor.

/reviewer add plummercj

**Review by plummercj — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]

**Comment by mychris** [comment]
Thanks for the review and the testing. Sponsoring is as simple as putting the /sponsor command after I executed the /integrate command. But it shouldn't be a big deal if this one is delayed a bit.

**Pull request closed without merging**
