### PR TITLE
8283008: KRegister documentation out of date

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  can I have reviews for this cleanup of `KRegister(Impl)` documentation, currently being a mix of copy&paste from `XMMRegister` and obsolete MMX support.

Testing: local compilation

Thanks,
  Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283008](https://bugs.openjdk.java.net/browse/JDK-8283008): KRegister documentation out of date

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to 4ea657d27420b204963daa2acee0415cf830a46a
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**)
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Jatin Bhateja](https://openjdk.java.net/census#jbhateja) (@jatin-bhateja - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7784/head:pull/7784` \
`$ git checkout pull/7784`

Update a local copy of the PR: \
`$ git checkout pull/7784` \
`$ git pull https://git.openjdk.java.net/jdk pull/7784/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7784`

View PR using the GUI difftool: \
`$ git pr show -t 7784`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7784.diff">https://git.openjdk.java.net/jdk/pull/7784.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]
Looks good, and trivial.  Thanks for fixing this.

**Comment by DamonFool** [comment]
Please also update the copyright year.

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Review by DamonFool — APPROVED** [review]

**Review by jatin-bhateja — APPROVED** [review]

**Comment by tschatzl** [comment]
Thanks everyone for your reviews

/integrate

**Pull request closed without merging**
