### PR TITLE
8255429: Remove C2-based profiling

### PR DESCRIPTION
**Pull request by veresov**
If there are no objections I'd like to remove some obsolete code that was an experiment to implement profiling in C2. It was added during the first tiered compilation experiments and is not unused.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255429](https://bugs.openjdk.java.net/browse/JDK-8255429): Remove C2-based profiling

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/888/head:pull/888`
`$ git checkout pull/888`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by erik1iu** [comment]
Do you mean that those profiling data never used before ? I noticed that those data was collected during abstract interpretation, is that `the first tiered compilation` you mean ?

**Review by neliasso — APPROVED** [review]
Nice clean up!

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by veresov** [comment]
> Do you mean that those profiling data never used before ? I noticed that those data was collected during abstract interpretation, is that `the first tiered compilation` you mean ?

No, it is code from >10 years ago that aimed to implement tiered compilation using c2 only. It generates code semantically equivalent to level 2 and 3. It is currently done by c1, so we don't need the c2 version.

**Comment by erik1iu** [comment]
@veresov  Thanks, this makes more sense to me now. I also wonder the profiling in interpreter, will it be deprecated ?

**Comment by veresov** [comment]
> @veresov Thanks, this makes more sense to me now. I also wonder the profiling in interpreter, will it be deprecated ?

No, definitely not.

**Pull request closed without merging**
