### PR TITLE
8323089: networkaddress.cache.ttl is not a system property

### PR DESCRIPTION
**Pull request by djelinski**
Please review this documentation change that:
- removes networkcache.cache.*.ttl properties from the [System properties page](https://docs.oracle.com/en/java/javase/21/docs/api/system-properties.html)
- Adds a link to the Security class where security properties are mentioned

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323089](https://bugs.openjdk.org/browse/JDK-8323089): networkaddress.cache.ttl is not a system property (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Aleksei Efimov](https://openjdk.org/census#aefimov) (@AlekseiEfimov - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17671/head:pull/17671` \
`$ git checkout pull/17671`

Update a local copy of the PR: \
`$ git checkout pull/17671` \
`$ git pull https://git.openjdk.org/jdk.git pull/17671/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17671`

View PR using the GUI difftool: \
`$ git pr show -t 17671`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17671.diff">https://git.openjdk.org/jdk/pull/17671.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17671#issuecomment-1922070882)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]
Hello Daniel, these changes look good to me.

**Review by AlekseiEfimov — APPROVED** [review]
Hi Daniel,
The changes looks good to me.

**Review by dfuch — APPROVED** [review]
LGTM

**Comment by djelinski** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
