### PR TITLE
8276265: jcmd man page is outdated

### PR DESCRIPTION
**Pull request by dholmes-ora**
It was noticed that a number of updates to the jcmd subcommands (some new, some modified) had not been added to the manpage. The text was supplied by @tstuefe - thanks Thomas. I applied the changes to the closed markdown sources and regenerated the nroff file. For easier review I have generated a html version that can be viewed here:

https://htmlpreview.github.io/https://github.com/dholmes-ora/jdk/blob/57c00815460ffef201239eafac322b4dd246da1b/jcmd.html

Summary of changes:

New Commands:
- Compiler.perfmap
- System.trim_native_heap
- VM.cds
- VM.classloaders
- VM.events
- VM.metaspace

Missing flags:
- GC.class_histogram -parallel
- GC.heap_dump - gz and overwrite options
- Thread.print -e

There are further improvements that could be made, some mentioned in the bug report. I also noticed a general confusion between arguments and options with some subcommands, but I did not try to address that.

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276265](https://bugs.openjdk.java.net/browse/JDK-8276265): jcmd man page is outdated

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6271/head:pull/6271` \
`$ git checkout pull/6271`

Update a local copy of the PR: \
`$ git checkout pull/6271` \
`$ git pull https://git.openjdk.java.net/jdk pull/6271/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6271`

View PR using the GUI difftool: \
`$ git pr show -t 6271`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6271.diff">https://git.openjdk.java.net/jdk/pull/6271.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
> It was noticed that a number of updates to the jcmd subcommands (some new, some modified) had not been added to the manpage. The text was supplied by @tstuefe - thanks Thomas. I applied the changes to the closed markdown sources and regenerated the nroff file. For easier review I have generated a html version that can be viewed here:

Your link did not work, I generated them and put them here for reviewer convenience: https://gist.github.com/tstuefe/8bd16a64061537d23e9ee556c7bd2965

Looks good. Most of the commands are ours (SAPs), but I had no idea that man pages existed.

> 
> There are further improvements that could be made, some mentioned in the bug report. I also noticed a general confusion between arguments and options with some subcommands, but I did not try to address that.
> 

jcmd commands in general feel a bit anarchic. Different styles etc. But I fear that cannot be changed because of backward compatibility.

Thanks, Thomas

**Comment by dholmes-ora** [comment]
@plummercj seems to me that the help text is where the error was introduced. If you say "If x then .... Otherwise ..." the "otherwise" is equivalent to "not x" because X was the subject of the previous sentence. So the help text should not be using otherwise the way that it does as the subject is wrong - it wants the subject to the use of the -s option. What the help text should say is something like:

-s:  [optional]  If a classname is specified print its subclasses. Without this option only the superclasses would be printed.

**Comment by plummercj** [comment]
> -s: [optional] If a classname is specified print its subclasses. Without this option only the superclasses would be printed.

Yes, wording like that would be clearer. How do you want to handle this? A new CR for both the help text and the man page, or do you think you can make both changes with this PR?

**Comment by dholmes-ora** [comment]
A new CR please. And a review of this PR :) Thanks

**Review by plummercj — APPROVED** [review]

**Comment by plummercj** [comment]
> A new CR please. And a review of this PR :) Thanks

https://bugs.openjdk.java.net/browse/JDK-8276982

**Comment by dholmes-ora** [comment]
Thanks for the reviews @tstuefe  and @plummercj !

**Pull request closed without merging**
