### PR TITLE
8305480: test/hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java failing on 32 bit arm

### PR DESCRIPTION
**Pull request by vpa1977**
os::current_frame() is stubbed out on the Linux Arm Thumb platform [1].

This affects 'MemDetailReporter::report_virtual_memory_region()'[2] causing the trace to miss 'from  <location>' part which breaks 'test/hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java'.

```
result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: '\[0x[0]*7947e000 - 0x[0]*794de000\] committed 384KB from.*' missing from stdout/stderr
```
This PR relaxes the test assertion, as 'MemDetailReporter::report_virtual_memory_region()' as 'from' statement is only available if the current frame can be unwinded [2].

[1] https://github.com/openjdk/jdk/blob/0deb648985b018653ccdaf193dc13b3cf21c088a/src/hotspot/os_cpu/linux_arm/os_linux_arm.cpp#L219
[2] https://github.com/openjdk/jdk/blob/aa762102e9328ca76663b56b3be6f6141b044744/src/hotspot/share/services/memReporter.cpp#L397

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305480](https://bugs.openjdk.org/browse/JDK-8305480): test/hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java failing on 32 bit arm

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [52b1473c](https://git.openjdk.org/jdk/pull/13291/files/52b1473cec0624ce19310e99f54c4342f5685068)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [52b1473c](https://git.openjdk.org/jdk/pull/13291/files/52b1473cec0624ce19310e99f54c4342f5685068)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13291/head:pull/13291` \
`$ git checkout pull/13291`

Update a local copy of the PR: \
`$ git checkout pull/13291` \
`$ git pull https://git.openjdk.org/jdk.git pull/13291/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13291`

View PR using the GUI difftool: \
`$ git pr show -t 13291`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13291.diff">https://git.openjdk.org/jdk/pull/13291.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13291#issuecomment-1494938223)

### CODE REVIEW

**Comment by jerboaa** [comment]
I've created this bug for it: https://bugs.openjdk.org/browse/JDK-8305480 Please use `/issue add` to get it properly recorded in this pr.

**Comment by vpa1977** [comment]
The pipeline fails on ' runtime/ErrorHandling/TestDwarf.java' which seems to be unrelated to the PR

**Comment by tstuefe** [comment]
There is no reason to losen this test for all platforms, no?

**Comment by vpa1977** [comment]
> There is no reason to losen this test for all platforms, no?
Fully agree, though not sure how to translate the presence of the ` __thumb__ ` define into test without introducing much complexity. I could only think of a heavy-handed approach of adding a `isCurrentFrameSupported()` to the WhiteBox, but that's probably wrong.

**Comment by tstuefe** [comment]
> > There is no reason to losen this test for all platforms, no?
> 
> Fully agree, though not sure how to translate the presence of the `__thumb__` define into test without introducing much complexity. I could only think of a heavy-handed approach of adding a `isCurrentFrameSupported()` to the WhiteBox, but that's probably wrong.

Just limit it to arm32. `if (Platform.isARM())`

Cheers, Thomas

**Review by tstuefe — APPROVED** [review]
Good! Needs a second review though, even though the patch is trivial, hotspot rules.

@jdksjolen ?

**Comment by tstuefe** [comment]
Just noticed, please update the copyright year for Oracle 2022->2023 (leave the rest as it is).

**Review by dholmes-ora — APPROVED** [review]
Okay.

**Comment by vpa1977** [comment]
@tstuefe Thank you very much!!!! I know that it is a bit of a nuisance, but if you have some time, would it be possible to look at another one-liner here: https://github.com/openjdk/jdk/pull/13292

**Pull request closed without merging**
