### PR TITLE
8309210: Extend VM Operations hs_err logging

### PR DESCRIPTION
**Pull request by stefank**
We have a section in the hs_err file, which prints the most recently run VM operations. Sometimes a VM operation type is used from multiple places in our code and it's not obvious why the VM operation was run. For example, HandshakeAllThreads doesn't tell us why we are running the handshake. I propose that we add an option for the VM operations to tell more about why they are used.

The proposed patch enhances the Handshake VM operation and the ZGC pause VM Operations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309210](https://bugs.openjdk.org/browse/JDK-8309210): Extend VM Operations hs_err logging

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)
 * [Stefan Johansson](https://openjdk.org/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14248/head:pull/14248` \
`$ git checkout pull/14248`

Update a local copy of the PR: \
`$ git checkout pull/14248` \
`$ git pull https://git.openjdk.org/jdk.git pull/14248/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14248`

View PR using the GUI difftool: \
`$ git pr show -t 14248`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14248.diff">https://git.openjdk.org/jdk/pull/14248.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14248#issuecomment-1570371763)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems quite reasonable.

Thanks.

**Review by tstuefe — APPROVED** [review]
Looks good.

**Review by fisk — APPROVED** [review]
This will make debugging much easier. Thank you. Looks good.

**Review by kstefanj — APPROVED** [review]
Looks good! File file an enhancement to add this for all `VM_GC_Operations`

**Comment by stefank** [comment]
Thanks for the reviews!
/integrate

**Pull request closed without merging**
