### PR TITLE
8312136: Modify runtime/ErrorHandling/TestDwarf.java to split dwarf and decoder testing

### PR DESCRIPTION
**Pull request by dholmes-ora**
This change updates the test so that there are two variants: one expects to get good decoder parsing of the log lines, and one which doesn't. The decoder expecting variant is then ProblemListed.

The exception message in the failing decoder test case is modified to report the actual problem - see example output in JBS issue.

Tested locally and in GHA to get the failing linux-x86 case.

Tier1 sanity tests

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312136](https://bugs.openjdk.org/browse/JDK-8312136): Modify runtime/ErrorHandling/TestDwarf.java to split dwarf and decoder testing (**Enhancement** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15895/head:pull/15895` \
`$ git checkout pull/15895`

Update a local copy of the PR: \
`$ git checkout pull/15895` \
`$ git pull https://git.openjdk.org/jdk.git pull/15895/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15895`

View PR using the GUI difftool: \
`$ git pr show -t 15895`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15895.diff">https://git.openjdk.org/jdk/pull/15895.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15895#issuecomment-1732884156)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Thanks for splitting this test and reviving the DWARF related parts. Looks good!

**Comment by dholmes-ora** [comment]
Thanks for the review @chhagedorn

**Review by pchilano — APPROVED** [review]
Looks good.

**Comment by dholmes-ora** [comment]
Thanks for the review @pchilano !

**Pull request closed without merging**
