### PR TITLE
8297830: aarch64: Make Address a discriminated union internally 

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the aarch64 Address class.  It now uses an
internal union, separating the literal and nonliteral cases.

This avoids leaving some fields uninitialized or initializing them to dummy
values.  It also reduces the size of the Address class somewhat, though it's
unclear whether that makes any noticeable difference.

Testing:
mach5 tier1 for linux-aarch64 and macosx-aarch64
mach5 tier2-5 for linux-aarch64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297830](https://bugs.openjdk.org/browse/JDK-8297830): aarch64: Make Address a discriminated union internally

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to [eb4f70b8](https://git.openjdk.org/jdk/pull/11429/files/eb4f70b852d3de53b0e477295da44fbac9fd95ef)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to [eb4f70b8](https://git.openjdk.org/jdk/pull/11429/files/eb4f70b852d3de53b0e477295da44fbac9fd95ef)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11429/head:pull/11429` \
`$ git checkout pull/11429`

Update a local copy of the PR: \
`$ git checkout pull/11429` \
`$ git pull https://git.openjdk.org/jdk pull/11429/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11429`

View PR using the GUI difftool: \
`$ git pr show -t 11429`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11429.diff">https://git.openjdk.org/jdk/pull/11429.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]
OK, thanks. It does seem to me a bit like moving the furniture around, but I have to admit it's an improvement. :-)

**Comment by dcubed-ojdk** [comment]
s/descriminated/discriminated/

Use "/issue JDK-8297830" to update the PR title... or just do the single char fix.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. A lot of small touches all over assembler_aarch64.hpp
but the result is definitely cleaner...

**Comment by theRealAph** [comment]
> The driver for all these cleanups around aarch64 Address is that when I tried to fix JDK-8160404 I got (valid) compiler warnings here about UB.

Aha! Thanks. It's good to have that here, in the discussion.

**Comment by kimbarrett** [comment]
Thanks for reviews @theRealAph and @dcubed-ojdk .

**Pull request closed without merging**
