### PR TITLE
8345799: Update copyright year to 2024 for core-libs in files where it was missed

### PR DESCRIPTION
**Pull request by magicus**
Some files have been modified in 2024, but the copyright year has not been properly updated. This should be fixed. 

I have located these modified files using:
```
git log --since="Jan 1" --name-only --pretty=format: | sort -u > file.list
```
and then run a script to update the copyright year to 2024 on these files.

I have made a manual sampling of files in the list to verify that they have indeed been modified in 2024.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345799](https://bugs.openjdk.org/browse/JDK-8345799): Update copyright year to 2024 for core-libs in files where it was missed (**Bug** - P4)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**) Review applies to [8e040c3a](https://git.openjdk.org/jdk/pull/22640/files/8e040c3adb97636451f2fb3fa07be5d102662dd0)
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**)
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22640/head:pull/22640` \
`$ git checkout pull/22640`

Update a local copy of the PR: \
`$ git checkout pull/22640` \
`$ git pull https://git.openjdk.org/jdk.git pull/22640/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22640`

View PR using the GUI difftool: \
`$ git pr show -t 22640`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22640.diff">https://git.openjdk.org/jdk/pull/22640.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22640#issuecomment-2527807133)
</details>

### CODE REVIEW

**Comment by dfuch** [comment]
changes to sun.net and java.naming/jdk.naming.* look ok

**Review by kevinjwalls — APPROVED** [review]
Looks good.
They all seem to follow the pattern, I looked at some and yes they have changes in 2024 but no year update.  One of them was mine I noticed!

**Comment by RogerRiggs** [comment]
That git query isn't correct for all the files in the repo. In particular, the copyrights on third party files are NOT updated uniformly when new versions are applied. In particular, XML files are NOT updated.

**Review by RogerRiggs — CHANGES_REQUESTED** [review]
Copyright dates in third party files are not updated uniformly. See the previous comment.

**Comment by magicus** [comment]
> I also meant to note that there are updates to binaries, src/java.base/share/classes/jdk/internal/icu/impl/data/icudt76b/... which maybe isn't intentional, or I just don't understand?

That was certainly not intentional! I'm not sure how that happened, I need to look at my copyright update script again...

**Comment by magicus** [comment]
> That git query isn't correct for all the files in the repo. In particular, the copyrights on third party files are NOT updated uniformly when new versions are applied. In particular, XML files are NOT updated.

I'm not sure I understand what you mean. Are you saying that I did not update files that should have been updated, or that I updated files that should not have been updated?

The only 3rd party XML files I know about are the ones in `make/data/cldr`. They have certainly been updated in 2024 from upstream, but they do not carry an Oracle copyright header, so there is nothing there to update.

**Comment by JoeWang-Java** [comment]
The git query found all those java.xml properties files likely due to the jcheck change (JDK-8325558) you made. That patch correctly kept the copyright years as they were since we generally don't change copyright year unless the change is significant.

**Review by JoeWang-Java — APPROVED** [review]

**Comment by RogerRiggs** [comment]
@magicus My question was about third party (xml) code used from Apache.
Joe's review and approval resolved that question.

**Review by justin-curtis-lu — APPROVED** [review]
Looked at the i18n changes (src, test, and 3rd party icu files w/ Oracle header) and they look correct to me.

**Comment by prsadhuk** [comment]
not sure why client label is added, no java.desktop/accessibility files are in there

**Comment by prrace** [comment]
> not sure why client label is added, no java.desktop/accessibility files are in there

I was puzzling over that too.

**Review by Hamlin-Li — APPROVED** [review]
Nice batch cleanup.

**Review by LanceAndersen — APPROVED** [review]

**Comment by magicus** [comment]
@prsadhuk @prrace `src/java.base/share/classes/jdk/internal/access/JavaAWTFontAccess.java` matches the pattern `"src/java.base/share/classes/jdk/internal/access/\\w+AWT"` which is setup for `client` in the Skara `jdk.json` label configuration.

**Pull request closed without merging**
