### PR TITLE
8282857: Create a regression test for JDK-4702690

### PR DESCRIPTION
**Pull request by srmandal**
Create a regression test for [JDK-4702690](https://bugs.openjdk.java.net/browse/JDK-4702690)

In many cases in Swing it is possible to easily programatically determine that a JScrollBar (or two) is scrolling some JPanel (the cannonical case is a JScrollPane).
In these cases, when accessibility support is instantiated (e.g. the AccessibleJScrollBar is created), a Controller_For and Controled_By relation should be instantiated between the AccessibleJScrollBar and the AccessibleJPanel that the JScrollBar and JPanel are associated with.

This allows various assistive technologies, especially voice-recognition technologies, to better interact with scrolling items.

The test put up validates that the target object for these properties(CONTROLLED_BY, CONTROLLED_FOR) are set appropriately for JScrollPane and JScrollBar.
This review is for migrating tests from a closed test suite to open.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8282857](https://bugs.openjdk.java.net/browse/JDK-8282857): Create a regression test for JDK-4702690

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**) ⚠️ Review applies to [01f8c430](https://git.openjdk.java.net/jdk/pull/7753/files/01f8c430dc537f373e833d2ecbdeae148b4f1506)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7753/head:pull/7753` \
`$ git checkout pull/7753`

Update a local copy of the PR: \
`$ git checkout pull/7753` \
`$ git pull https://git.openjdk.java.net/jdk pull/7753/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7753`

View PR using the GUI difftool: \
`$ git pr show -t 7753`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7753.diff">https://git.openjdk.java.net/jdk/pull/7753.diff</a>

</details>

### CODE REVIEW

**Comment by srmandal** [comment]
@mrserb  can you please review the changes after incorporating the earlier feedback ?

**Comment by srmandal** [comment]
The test ran successfully on Mach5 with multiple runs (30) on windows-x64, linux-x64 and macos-x64.

**Review by prrace — CHANGES_REQUESTED** [review]
and again .. just go through all your PRs and get rid of bugid directories where there's just one file in it !

**Review by azuev-java — APPROVED** [review]

**Comment by srmandal** [comment]
As suggested, bug id folder structure is removed and test is under pre-existing accessibility directory.
Test code has not changed but it has been run mach5 after the change.(Link provided in the JBS Issue)  

Can someone take a look and this be marked as approved/sponsored after the above changes?

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
