### PR TITLE
8275670: ciReplay: java.lang.NoClassDefFoundError when trying to load java/lang/invoke/LambdaForm$MH

### PR DESCRIPTION
**Pull request by dean-long**
The invokedynamic support added by 8271911 was incomplete.  In particular, it failed to search through argL fields.  This change fixes that, adds a test, and also cleans up the code a bit.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275670](https://bugs.openjdk.java.net/browse/JDK-8275670): ciReplay: java.lang.NoClassDefFoundError when trying to load java/lang/invoke/LambdaForm$MH

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6243/head:pull/6243` \
`$ git checkout pull/6243`

Update a local copy of the PR: \
`$ git checkout pull/6243` \
`$ git pull https://git.openjdk.java.net/jdk pull/6243/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6243`

View PR using the GUI difftool: \
`$ git pr show -t 6243`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6243.diff">https://git.openjdk.java.net/jdk/pull/6243.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by dean-long** [comment]
Thanks Vladimir.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by dean-long** [comment]
Thanks Christian.

**Pull request closed without merging**
