### PR TITLE
JDK-8297660: x86: Redundant test+jump in C1 allocateArray

### PR DESCRIPTION
**Pull request by tstuefe**
In `C1_MacroAssembler::initialize_body()` we test the input array length for 0. We do this again in `MacroAssembler::zero_memory()`. This results in a redundant test+jump instruction:

```
 13442   0x00007f58a8ca2f02:   sub    $0x10,%rsi                 
 13443   0x00007f58a8ca2f06:   je     0x00007f58a8ca2f26   <<
 13444   0x00007f58a8ca2f0c:   test   %rsi,%rsi                     
 13445   0x00007f58a8ca2f0f:   je     0x00007f58a8ca2f26    <<
 13446   0x00007f58a8ca2f15:   xor    %rbx,%rbx
 13447   0x00007f58a8ca2f18:   shr    $0x3,%rsi
 13448   0x00007f58a8ca2f1c:   mov    %rbx,0x8(%rax,%rsi,8)
 13449   0x00007f58a8ca2f21:   dec    %rsi
 13450   0x00007f58a8ca2f24:   jne    0x00007f58a8ca2f1c           ;*anewarray {reexecute=0 rethrow=0 return_oop=0}
 13451                                                             ; - java.lang.invoke.MethodHandles::<clinit>@24 (line 5109)
```

Since `MacroAssembler::zero_memory()` is only ever called from `C1_MacroAssembler::initialize_body()`, it does not need to test for len=0, since its caller already does.

---

Patch removes one test+jump and adds an assertion for len>0 to zero_memory.

Patch ran through SAP nightlies and GHAs.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297660](https://bugs.openjdk.org/browse/JDK-8297660): x86: Redundant test+jump in C1 allocateArray

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to [3372e965](https://git.openjdk.org/jdk/pull/11372/files/3372e965626390d8bef75466b5ab4c001256b8f3)
 * [Yi Yang](https://openjdk.org/census#yyang) (@y1yang0 - Committer) ⚠️ Review applies to [3372e965](https://git.openjdk.org/jdk/pull/11372/files/3372e965626390d8bef75466b5ab4c001256b8f3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11372/head:pull/11372` \
`$ git checkout pull/11372`

Update a local copy of the PR: \
`$ git checkout pull/11372` \
`$ git pull https://git.openjdk.org/jdk pull/11372/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11372`

View PR using the GUI difftool: \
`$ git pr show -t 11372`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11372.diff">https://git.openjdk.org/jdk/pull/11372.diff</a>

</details>

### CODE REVIEW

**Comment by y1yang0** [comment]
Is it reasonable to remove such checking from the caller? Macro assembler is shared across all assemblers, zero_memory may be used in other place in the future due to its non-ad-hoc implementation.

**Comment by tstuefe** [comment]
> Is it reasonable to remove such checking from the caller? Macro assembler is shared across all assemblers, zero_memory may be used in other place in the future due to its non-ad-hoc implementation.

That is why I added the assertion. Hopefully, such a hypothetical use would surface in tests.

**Comment by theRealAph** [comment]
Surely a macro assembler function that takes a length should not misbehave of that length is zero. It's a fairly basic correctness criterion that it most not, because zero is a valid number. We shouldn't be building fragility into the system.
I agree that it makes sense to remove one of the checks, but it should be the one in the caller.

**Comment by tstuefe** [comment]
> Surely a macro assembler function that takes a length should not misbehave of that length is zero. It's a fairly basic correctness criterion that it most not, because zero is a valid number. We shouldn't be building fragility into the system. I agree that it makes sense to remove one of the checks, but it should be the one in the caller.

Okay, did that.

I did it the other way around originally since the outer test cannot be removed, it's the sub of the header size. So the test in zero_memory is still redundant, but the outer jz has been removed at least:

```
  0x00007f8080ca2f02:   sub    $0x10,%rsi  << initialize_body
  0x00007f8080ca2f06:   test   %rsi,%rsi      << zero_memory
  0x00007f8080ca2f09:   je     0x00007f8080ca2f20 << zero_memory
```

**Review by theRealAph — APPROVED** [review]

**Review by y1yang0 — APPROVED** [review]

**Comment by y1yang0** [comment]
I mean, remove the checking from caller instead of callee. zero_memory can be used in other places given that it is part of general macro assembler.

**Comment by tstuefe** [comment]
> I mean, remove the checking from caller instead of callee. zero_memory can be used in other places given that it is part of general macro assembler.

Did I not just do that? Could you check the latest version please?

**Pull request closed without merging**
