### PR TITLE
8343026: JFR: Index into fields in the topFrame

### PR DESCRIPTION
**Pull request by egahlin**
Could I have a review of a change that allows 'jfr view' queries to reference nested fields for a top frame.

Testing: jdk/jdk/jfr and diff of 'jfr view all-views' before and after the change.

This change will not impact the output of the exiting views, but it helps OpenJDK developers diagnose issues, for example, print 'lineNumber', (frame) 'type' and 'bytecodeIndex' of the top frame.

Thanks
Erik

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343026](https://bugs.openjdk.org/browse/JDK-8343026): JFR: Index into fields in the topFrame (**Enhancement** - P4)

### Reviewers
 * [Markus Grönlund](https://openjdk.org/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21705/head:pull/21705` \
`$ git checkout pull/21705`

Update a local copy of the PR: \
`$ git checkout pull/21705` \
`$ git pull https://git.openjdk.org/jdk.git pull/21705/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21705`

View PR using the GUI difftool: \
`$ git pr show -t 21705`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21705.diff">https://git.openjdk.org/jdk/pull/21705.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21705#issuecomment-2437105259)

### CODE REVIEW

**Review by mgronlun — APPROVED** [review]
Looks good!

**Comment by egahlin** [comment]
Thanks for the reviews.

/integrate

**Review by mgronlun — APPROVED** [review]

**Comment by egahlin** [comment]
Thanks for the review of the whitespace removal.

**Pull request closed without merging**
