### PR TITLE
8244202: Implementation of JEP 418: Internet-Address Resolution SPI

### PR DESCRIPTION
**Pull request by AlekseiEfimov**
This change implements a new service provider interface for host name and address resolution, so that java.net.InetAddress API can make use of resolvers other than the platform's built-in resolver.

The following API classes are added to `java.net.spi` package to facilitate this:
- `InetAddressResolverProvider` -  abstract class defining a service, and is, essentially, a factory for `InetAddressResolver` resolvers.
- `InetAddressResolverProvider.Configuration ` - an interface describing the platform's built-in configuration for resolution operations that could be used to bootstrap a resolver construction, or to implement partial delegation of lookup operations.
- `InetAddressResolver` - an interface that defines methods for the fundamental forward and reverse lookup operations.
- `InetAddressResolver.LookupPolicy` - a class whose instances describe the characteristics of one forward lookup operation.  

More details in [JEP-418](https://openjdk.java.net/jeps/418).

Testing: new and existing `tier1:tier3` tests

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8244202](https://bugs.openjdk.java.net/browse/JDK-8244202): Implementation of JEP 418: Internet-Address Resolution SPI

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to f660cc6ecc7a31c83de220160b9fd8d0fbacd1be
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 1378686becfcbf18793556de8381b5ebcd79698d
 * [Michael McMahon](https://openjdk.java.net/census#michaelm) (@Michael-Mc-Mahon - **Reviewer**) ⚠️ Review applies to f660cc6ecc7a31c83de220160b9fd8d0fbacd1be
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to 0542df514e705b3f5c817aa37ea985126dac74af

### Contributors
 * Chris Hegarty `<chegar@openjdk.org>`
 * Daniel Fuchs `<dfuchs@openjdk.org>`
 * Alan Bateman `<alanb@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5822/head:pull/5822` \
`$ git checkout pull/5822`

Update a local copy of the PR: \
`$ git checkout pull/5822` \
`$ git pull https://git.openjdk.java.net/jdk pull/5822/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5822`

View PR using the GUI difftool: \
`$ git pr show -t 5822`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5822.diff">https://git.openjdk.java.net/jdk/pull/5822.diff</a>

</details>

### CODE REVIEW

**Comment by msheppar** [comment]
What’s in a name?
I find the method names of the InetAddressResolver interface a bit ambiguous. Typically in this DNS problem space
one speaks of lookup to resolve a hostname to its associated addresses and reverse lookup
to resolve an IP address to a hostname (or names) associated with it.

For the method names lookupHostname, and lookupAddresses,
and the semantics conveyed in those names, 
I would expect lookupHostname to resolve a hostname, that is, take a hostname as parameter and
the return value the addresses, while lookupAddresses I would expect to resolve an address to its hostname,
that is, take an address and return a hostname.
However, the current pair of methods names convey the opposite, lookupHostname resolves an address and
lookupAddresses resolves a hostname.

I would proffer a method name change to use lookup and reverseLookup
OR to use resolvesHostname and resolveAddress, to resolve a hostname and address
respectively.

Thus, lookupHostname should be renamed to reverseLookup and
lookupAddresses to lookup OR
lookupHostname renamed to resolveAddress and lookupAddresses renamed to resolveHostname.

**Comment by msheppar** [comment]
Refactor remove Configuration and simplify interface:

In the InetAddressResolver a Configuration abstraction is defined, and this is supplied to
a get method of the InetAddressResolverProvider.

The objective is to “inject” some platform configuration into an InetAddressResolver. This
consistents of two pieces of platform configuration detail, a builtin resolver reference and the hostname.
Why not provide them as parameters to the provider get method and dispense with the Configuration
abstraction? Thus simplifying the interface. The hostname is being supplied by the getLocalHostName
of an InetAddressImpl. This is essentially a wrapper to the library call gethostname. This
could be provided as a static method in InetAddressImpl, called once during loadResolver to 
provide the hostname parameter String. The hostname is a static piece of system configuration, which
requires a system restart if it were to be changed - so need to provide a lambda.

So Suggestion is refector remove Configuration to simplify the interface and provide the
BULITIN_RESOLVER and hostname as parameters to the InetAddressResolverProvider::get method

**Comment by AlanBateman** [comment]
> * `InetAddressResolverProvider.Configuration` interface API might evolve, e.g. there might be a need to pass additional configuration items.
> * local hostname is a dynamic information, therefore it cannot be passed as string parameter to `InetAddressResolverProvider::get`.

Right, I think we've ended up with a good model here that supports the common case, stacking, and can be extended in the future to add new configuration if required. Also if good use-cases come up when Configuration can be changed to be non-sealed.

**Review by Michael-Mc-Mahon — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]
LGTM.

**Pull request closed without merging**
