### PR TITLE
8325878: Require minimum Clang version 13

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that updates the minimum supported version of Clang
to be used for building OpenJDK from 3.5 to 13.

This permits enabling C++17 (JDK-8314488), though Clang 5 might suffice for
that. A minimum of Clang 13 also obtains a critical bug fix for the [[noreturn]]
attribute (see JDK-8303805).

Testing: mach5 tier1, which includes building with a recent version of Xcode/clang.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325878](https://bugs.openjdk.org/browse/JDK-8325878): Require minimum Clang version 13 (**Enhancement** - P4)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer) ⚠️ Review applies to [9796d4a9](https://git.openjdk.org/jdk/pull/17862/files/9796d4a96767f7a15fa8166ddd6484edf2598c75)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [9796d4a9](https://git.openjdk.org/jdk/pull/17862/files/9796d4a96767f7a15fa8166ddd6484edf2598c75)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17862/head:pull/17862` \
`$ git checkout pull/17862`

Update a local copy of the PR: \
`$ git checkout pull/17862` \
`$ git pull https://git.openjdk.org/jdk.git pull/17862/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17862`

View PR using the GUI difftool: \
`$ git pr show -t 17862`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17862.diff">https://git.openjdk.org/jdk/pull/17862.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17862#issuecomment-1945393500)

### CODE REVIEW

**Review by TheShermanTanker — APPROVED** [review]

**Review by magicus — APPROVED** [review]
Change looks fine from a build perspective.

**Comment by tstuefe** [comment]
Unfortunately this will break my workflow on Linux - I use clang to build on Ubuntu 20.04, which is not that old, but it ships with clang 12. This is not a deal breaker, just annoying.

**Comment by kimbarrett** [comment]
> Unfortunately this will break my workflow on Linux - I use clang to build on Ubuntu 20.04, which is not that old, but it ships with clang 12. This is not a deal breaker, just annoying.

That's unfortunate, but I think the [[noreturn]] issue is very important.  Until we have that fix, we can't rely on that
attribute to silence certain warnings.  This requires us to continue to insert dead returns or apply other workarounds.
And forgetting to do so (because someone makes a change that works fine with later versions or on other platforms)
will lead to build-breakage JBS issues/PRs just to continue to support older versions of clang.  We've already had
several of those.

**Comment by tstuefe** [comment]
> > Unfortunately this will break my workflow on Linux - I use clang to build on Ubuntu 20.04, which is not that old, but it ships with clang 12. This is not a deal breaker, just annoying.
> 
> That's unfortunate, but I think the [[noreturn]] issue is very important. Until we have that fix, we can't rely on that attribute to silence certain warnings. This requires us to continue to insert dead returns or apply other workarounds. And forgetting to do so (because someone makes a change that works fine with later versions or on other platforms) will lead to build-breakage JBS issues/PRs just to continue to support older versions of clang. We've already had several of those.

Thank you for explaining the motivation. @forax also mentioned that our workaround produces false warnings in IDEs (just checked in CDT). I'm fine with it - I will find another solution for my Linux box.

**Comment by kimbarrett** [comment]
There was some discussion of clang versions over in the PR proposing to enable
C++17 (https://github.com/openjdk/jdk/pull/14988).  The minimum version
proposed here (13) seemed acceptable from that discussion.  Good to go here?

**Comment by kimbarrett** [comment]
Thanks for reviews/responses. I'll go ahead with integration. We won't be
reliant on the new version immediately, so we can still reconsider if it
causes someone problems and they bring it up soon-ish.

**Comment by magicus** [comment]
> I don't want to integrate this until the minimum aix-ppc toolchain has been updated

@kimbarrett Is anyone working on that problem?

**Pull request closed without merging**
