### PR TITLE
8328507: Move StackWatermark code from safepoint cleanup

### PR DESCRIPTION
**Pull request by fisk**
There is some stack watermark code in safepoint cleanup that flushes out concurrent stack processing, as a defensive measure to guard safepoint operations that assume the stacks have been fixed up. However, we wish to get rid of safepoint cleanup so this operation should move out from the safepoint. This proposal moves it into CollectedHeap::safepoint_synchronize_begin instead which runs before we start shutting down Java threads. This moves the code into more obvious GC places and reduces time spent inside of non-GC safepoints.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328507](https://bugs.openjdk.org/browse/JDK-8328507): Move StackWatermark code from safepoint cleanup (**Enhancement** - P4)

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**) ⚠️ Review applies to [f18381c8](https://git.openjdk.org/jdk/pull/18378/files/f18381c8117ba100e72d02e5911a47c884aab5e3)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18378/head:pull/18378` \
`$ git checkout pull/18378`

Update a local copy of the PR: \
`$ git checkout pull/18378` \
`$ git pull https://git.openjdk.org/jdk.git pull/18378/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18378`

View PR using the GUI difftool: \
`$ git pr show -t 18378`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18378.diff">https://git.openjdk.org/jdk/pull/18378.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18378#issuecomment-2007219374)

### CODE REVIEW

**Review by xmas92 — APPROVED** [review]
lgtm.

**Review by coleenp — APPROVED** [review]
This makes sense.

**Comment by fisk** [comment]
Thanks for the review, @coleenp and @xmas92!

**Pull request closed without merging**
