### PR TITLE
8337563: NMT: rename MEMFLAGS to MemFlag

### PR DESCRIPTION
**Pull request by gerard-ziemski**
Please review this cleanup, where we rename `MEMFLAGS` to `MemType`.

`MEMFLAGS` implies that we can use more than one at the same time, but those are exclusive values, so `MemType` is much more suitable name.

There is a bunch of other related cleanup that we can do, but I will leave for follow up issues such as [NMT: rename NMTUtil::flag to NMTUtil::type](https://bugs.openjdk.org/browse/JDK-8337836)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Error
&nbsp;⚠️ This PR only contains changes already present in the target

### Integration blocker
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8337563](https://bugs.openjdk.org/browse/JDK-8337563)

### Issue
 * [JDK-8337563](https://bugs.openjdk.org/browse/JDK-8337563): NMT: rename MEMFLAGS to MemTag (**Enhancement** - P4) ⚠️ Title mismatch between PR and JBS.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20497/head:pull/20497` \
`$ git checkout pull/20497`

Update a local copy of the PR: \
`$ git checkout pull/20497` \
`$ git pull https://git.openjdk.org/jdk.git pull/20497/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20497`

View PR using the GUI difftool: \
`$ git pr show -t 20497`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20497.diff">https://git.openjdk.org/jdk/pull/20497.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20497#issuecomment-2274005402)

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
If you called it `MemTypeFlag` - which to me still suggests mutually-exclusive values - then you would not need to rename all the variables with "flag" in their name later.

**Comment by gerard-ziemski** [comment]
> If you called it `MemTypeFlag` - which to me still suggests mutually-exclusive values - then you would not need to rename all the variables with "flag" in their name later.

Hmm, not a bad idea. Are there any other opinions?

**Comment by gerard-ziemski** [comment]
We could do:

`#define MEMFLAGS MemType`

to help out with backports, and leave it up to the runtime/compiler/gc teams when to pull the trigger to switch over when they are ready, if that helps? Any backport would have to deal with this change to a degree though unfortunately.

I would want this change in runtime/nmt at the minimum, though personally I would prefer if we adopted it everywhere as in my proposed fix.

**Comment by gerard-ziemski** [comment]
The current proposed fix renames from MEMFLAGS to MemType, other proposed names are:

- MemTypeFlag
- NMTCategory
- NMTCat

I also like:

- NMTMemType

Any other suggestions?

I don't think I will be following up with argument renaming after this, though, whatever the final name we agree on...

**Comment by gerard-ziemski** [comment]
@dholmes-ora @tstuefe @jdksjolen 

Where are we here? I have renamed MEMFLAGS to MemType.

Is this fine, or do you wish to see a different way to handle this?

**Comment by dholmes-ora** [comment]
MemType still makes all the "flag" variable names look weird IMO.

**Comment by stefank** [comment]
> Is everyone OK with MemTypeFlag?

It's quite unfortunate to have a three-word type for something this prolific in our code base. Why not go with `MemType` and change variable names from `flag` to `mt`?

```
  static char* map_memory_to_file(size_t size, int fd, MEMFLAGS flag = mtNone);
```
would then become:
```
  static char* map_memory_to_file(size_t size, int fd, MemType mt = mtNone);
```

**Comment by gerard-ziemski** [comment]
> > Is everyone OK with MemTypeFlag?
> 
> It's quite unfortunate to have a three-word type for something this prolific in our code base. Why not go with `MemType` and change variable names from `flag` to `mt`?
> 
> ```
>   static char* map_memory_to_file(size_t size, int fd, MEMFLAGS flag = mtNone);
> ```
> 
> would then become:
> 
> ```
>   static char* map_memory_to_file(size_t size, int fd, MemType mt = mtNone);
> ```

My initial choice was exactly that, but then I backed-off from renaming the arguments, because how big and intrusive the change it seemed.

David seems to prefer `MemTypeFlag`, so that we don't have to rename all the arguments and I see a point in that, but it wouldn't be my first choice.

Thomas seems to prefer `NMTCat` that I just don't like much, despite that it has NMT prefix in it, for some reason.

If we could find a compromise that we all can live with, despite it not being exactly what every single person wants, then that would be great. We could this in separate steps:

Initial effort (this fix): we rename `MEMFLAGS` to `MemType`

Follow up effort(s): we either rename all arguments in one big push (intrusive) or we do it a file, or related files (like NMT) together at a time in a followup(s).

Is this a reasonable compromise to everyone?

**Comment by dholmes-ora** [comment]
> I really dislike MemType for its very genericness. MEMFLAGS is a handle into the NMT subsystem. It has no meaning beyond NMT. Yet, it is spread all over the code base. Therefore I really would like an NMT prefix, whatever the name then is.

I agree with @tstuefe here. `MemFlag` and `MemType` sound far too general when this is NMT specific.

My preference to keep the "flags" part of the type was to avoid needing to rename many parameters. The usage of `MEMFLAGS flags` is quite extensive. I would not want to see a partial approach here where we end up with a non-flag type name but a flag variable name.

`NMTTypeFlag` would I hope satisfy Thomas's requirement and avoid the need to do variable renames.

**Comment by stefank** [comment]
> I agree with @tstuefe here. MemFlag and MemType sound far too general when this is NMT specific.

Yes, it is not very specific, but it also not hard to learn and then know what this type is all about.

> My preference to keep the "flags" part of the type was to avoid needing to rename many parameters. The usage of MEMFLAGS flags is quite extensive. I would not want to see a partial approach here where we end up with a non-flag type name but a flag variable name.

I think we should rename all the 'flags' variables in the same change.

> NMTTypeFlag would I hope satisfy Thomas's requirement and avoid the need to do variable renames.

* To me, that's really not an appealing name for a type that is going to be used by all parts of the HotSpot code base. I much more prefer a shorter name that is easy on the eyes, then a longer and more specific name that is an eyesore.

* And even as a longer name, it doesn't tell what it is going to be used for. What is a Native Memory Tracker Type Flag?

* I don't want us to select a bad name so that we don't have to change the variable names.

* Whatever we choose we also need to consider the mt prefix of things like mtGC, mtClass, etc.

With all that said, I hope it is clear that we various reviewers have different opinions around this and that we don't integrate this before we have some kind of consensus about the way forward with this.

**Comment by dholmes-ora** [comment]
> What is a Native Memory Tracker Type Flag?

It is a flag telling us the type of native memory being tracked.

> Whatever we choose we also need to consider the mt prefix of things like mtGC, mtClass, etc.

And what does that stand for: memory type? memory tracker? Arguably they should have been nmtGC etc.

> I think we should rename all the 'flags' variables in the same change.

Okay. That's a big change but I'd prefer it to any half-way measures.

**Comment by kimbarrett** [comment]
> > I agree with @tstuefe here. MemFlag and MemType sound far too general when this is NMT specific.
> 
> Yes, it is not very specific, but it also not hard to learn and then know what this type is all about.
> 
> > My preference to keep the "flags" part of the type was to avoid needing to rename many parameters. The usage of MEMFLAGS flags is quite extensive. I would not want to see a partial approach here where we end up with a non-flag type name but a flag variable name.
> 
> I think we should rename all the 'flags' variables in the same change.
> 
> > NMTTypeFlag would I hope satisfy Thomas's requirement and avoid the need to do variable renames.
> 
>     * To me, that's really not an appealing name for a type that is going to be used by all parts of the HotSpot code base. I much more prefer a shorter name that is easy on the eyes, then a longer and more specific name that is an eyesore.
> 
>     * And even as a longer name, it doesn't tell what it is going to be used for. What is a Native Memory Tracker Type Flag?
> 
>     * I don't want us to select a bad name so that we don't have to change the variable names.
> 
>     * Whatever we choose we also need to consider the mt prefix of things like mtGC, mtClass, etc.
> 
> 
> With all that said, I hope it is clear that we various reviewers have different opinions around this and that we don't integrate this before we have some kind of consensus about the way forward with this.

I strongly agree with everything @stefank said above.  I also think some of the suggestions that have been offered
are not improvements from the status quo, or not enough to be worth the code churn.

The only thing I have against MemType is that "type" is pretty overloaded.  I spent some time with a thesaurus, but
the only alternative I came up with that I liked was MemGroup, but it fails the "mt" prefix consideration.

**Comment by stefank** [comment]
> > Whatever we choose we also need to consider the mt prefix of things like mtGC, mtClass, etc.
> 
> And what does that stand for: memory type? memory tracker? Arguably they should have been nmtGC etc.

The memflags.hpp file says that it's a memory type:
```
+#define MEMORY_TYPES_DO(f)                                                           \
+  /* Memory type by sub systems. It occupies lower byte. */                          \
+  f(mtJavaHeap,       "Java Heap")   /* Java heap                                 */ \
```
My guess is that at some point there was an incomplete rename from "memory type".

**Comment by kimbarrett** [comment]
> > > Whatever we choose we also need to consider the mt prefix of things like mtGC, mtClass, etc.
> > 
> > 
> > And what does that stand for: memory type? memory tracker? Arguably they should have been nmtGC etc.
> 
> The memflags.hpp file says that it's a memory type:
> 
> ```
> +#define MEMORY_TYPES_DO(f)                                                           \
> +  /* Memory type by sub systems. It occupies lower byte. */                          \
> +  f(mtJavaHeap,       "Java Heap")   /* Java heap                                 */ \
> ```
> 
> My guess is that at some point there was an incomplete rename from "memory type".

Note that we used to have `typedef MemType MEMFLAGS;`

**Comment by kimbarrett** [comment]
The suggestion of "nmtGC" from @daholmes initially looked somewhat appealing
to me. But that then suggests "NMTType" or (better?) "NMTGroup" or something
like that. But I don't much like the look of or typing those acronyms. (Note
that NMTGroup is HotSpot style, not NmtGroup.)

So I'm still preferring "MemType".

**Comment by gerard-ziemski** [comment]
We already have `NMT_TrackingLevel` in `nmtCommon.hpp`, so we could do `NMT_MemType` ?

We could also add NMT class and then have `NMT::MemType`?

Note that as Stefan pointed out, we refer to it as memory type in memflags.hpp Moreover, we use 'mt' in the actual enumerated names as in `mtNone` for example.

**Comment by gerard-ziemski** [comment]
@dholmes-ora @tstuefe @stefank @kimbarrett @afshin-zafari @jdksjolen 

hi all,

I would like to see if we can give this another go, now that we got some time to sleep on it.

How about this - I created a table with some name candidates, so everyone can see where everyone else is. We all can choose 3 candidates that we can rank 1, 2 and 3. At the end we tabulate the answer and the one with highest score wins?

| developer | MemType | MemTypeFlag | NMTCat | NMTGroup | NMT_MemType | NMT::MemType |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| gerard | 1 | 0 | 0 | 0 | 2 | 3 |
| David  | ? | ? | ? | ? | ? | ? |
| Thomas | ? | ? | ? | ? | ? | ? |
| Johan  | ? | ? | ? | ? | ? | ? |
| Afshin | ? | ? | ? | ? | ? | ? |
| Stefan | ? | ? | ? | ? | ? | ? |
| Kim    | ? | ? | ? | ? | ? | ? |

**Comment by dholmes-ora** [comment]
Hmmmm .... I like the structure of `NMT::MemType` but also prefer to keep "flag" in the name to avoid renaming parameters (or having oddly named parameters). Can I vote for `NMT::MemTypeFlag`? :) Otherwise:
- `MemTypeFlag` - 3 points
- `NMT::MemType` - 2 points
- `NMT_MemType` - 1 point (but maybe `NMTMemType`?)

**Comment by tstuefe** [comment]
NMTCat,  NMTGroup 3 points

**Comment by afshin-zafari** [comment]
- `MemTypeFlag` : 3
- `NMT::MemType` : 2
IMHO, `MemType` without NMT is a global name and possibly will be source of confusion in the code or by the developers.

**Comment by coleenp** [comment]
I like NMT::MemType 3 points.

**Comment by dcubed-ojdk** [comment]
I think it must have `NMT` somewhere in the name. `NMTGroup` sounds like
there could more than one value set at one time, but that might be just me.
`NMTCat` (and `NMTGroup`) lose the idea that `Type` should be in there somewhere.

For ease of typing, I'm not fond of `NMT::MemType` but it has the appeal of being
in a namespace...

So I'm going with:
NMT::MemType - 3 points
NMT_MemType/NMTMemType(prefer for ease of typing) - 2 points

and I'm skipping a 1 point assignment.

**Comment by gerard-ziemski** [comment]
Taking Dan's feedback into account we have:

**Comment by gerard-ziemski** [comment]
Taking Dan's feedback into account we have:

|        | MemType | MemTypeFlag | NMTCat         | NMTGroup | NMT_MemType   | NMT::MemType |
| :---:  | :---:   | :---:       | :---:          | :---:    | :---:         | :---:        |
| gerard | 1       | 0           | 0              | 0        | 2             | 3            |
| David  | 0       | 3           | 0              | 0        | 1(NMTMemType) | 2            |
| Thomas | 0       | 0           | 2              | 3        | 0             | 0            |
| Johan  | 0       | 0           | 2(NMTCategory) | 3        | 0             | 0            |
| Afshin | 0       | 3           | 0              | 0        | 0             | 2            |
| Coleen | 0       | 0           | 0              | 0        | 0             | 3            |
| Dan    | 0       | 0           | 0              | 0        | 2(NMTMemType) | 3            |
|        | 1       | 6           | 4              | 6        | 5             | 13           |

`NMT::MemType` it is.

Sorry, if your choice hasn't made it. I am surprised how wide the spectrum of choices are, this took a while to find a consensus.

Thank you everyone, who participated!

**Comment by stefank** [comment]
I much prefer to see MemType, but I'm warming up to NMTCategory.

MemType: Succinct - matches part of the code (E.g. the mt in mtGC)
MemTypeFlag: Too many words for my preference.
NMTCat: Meuw. :)
NMTCategory: Parts of the code call these categories, so I'm not entirely against this.
NMTGroup: "Group" is a new name for this that currently isn't reflected at all in the code.
NMT_MemType: I think we should try get rid of names using this style.
NMT::MemType: The `::` makes all function declarations noisier for very little benefit, IMO.

**Comment by kimbarrett** [comment]
I continue to mostly agree with @stefank.

I think this name shouldn't be considered in isolation. There are already a
bunch of "NMT_" prefixed names. That's the common idiom for things like this
(often (maybe even usually?) without the "_"). Why are we proposing to adopt a
new style. (For just this? That would be weird. Or more broadly? That
certainly needs more discussion.)

Implementation question: Where does the NMT "namespace" come from? Presumably
the enum definition is going to be wrapped up in an AllStatic class?

A similar effect can be achieved using a `namespace`, but HotSpot avoids using
those except in some specific cases that don't apply to this type in
isolation. But if we're going to consider the broader scope (as we should),
then a namespace might well be appropriate. I'd prefer namespaces (if we were
to start using them) use snake_case style naming myself, so "nmt::MemType".

**Comment by gerard-ziemski** [comment]
After some more internal discussion `MemTag`  and `NMT::MemTag` were suggested.

**Comment by gerard-ziemski** [comment]
> I continue to mostly agree with @stefank.
> 
> I think this name shouldn't be considered in isolation. There are already a bunch of "NMT_" prefixed names. That's the common idiom for things like this (often (maybe even usually?) without the "_"). Why are we proposing to adopt a new style. (For just this? That would be weird. Or more broadly? That certainly needs more discussion.)

It is precisely because we already are using `NMT_TrackingStackDepth` and `NMT_TrackingLevel` (and the fact that MemType by itself was too general) that I suggested we adopt `NMT::` Yes, it would be all static class.

Why not all lower letter `nmt::`? Again, because we already use `NMT_` elsewhere.

My plan was later to switch from `NMT_` to `NMT::` for all of them. We can do `nmt::` too.

So how about `MemTag`, `nmt::MemTag` or `NMT::MemTag`?

**Comment by tstuefe** [comment]
I am not against moving NMT into a namespace, but we should be sure that is what we want. Introducing a new namespace is a larger scope than just renaming a single type.

For example: should the whole of NMT, including its outside-facing interface, including the enum values itself, go into the new NMT namespace? So, do we do this now:

```
NMT::MemFlag flag = NMT::mtGC;
NMT::MemTracker::record_malloc(p, l, flag);
NMT::MemTracker::report();
```
? If yes, that affects more than just the type name. 

Do we omit the namespace qualifier when inside NMT? 
When outside NMT, do we sprinkle `using NMT` around to avoid getting RSI from typing "NMT::"? That is possible, but now we get:

```
MemFlag flag = mtGC;
MemTracker::record_malloc(p, l, flag);
```

so the "NMT" prefix is gone. And we have both NMT::MemFlag and MemFlag, so people grepping for stuff need to look for both variants.

Or do you plan to just put this single enum into the namespace? As in 

```
namespace NMT { enum MEMFLAGS ... };
```
?

But having a namespace and keeping 99% of associated code outside of that namespace would be a very weird choice. And the enum values would have to be in that namespace in any case, so we wont get around having to qualify all "mtXXX" flags NMT::mtXXX.

---

Note that I am not against namespaces. I used them for Metaspace back when doing Elastic Metaspace, and I have argued for their selective use in the past. But changes like these tend to fan out a bit more than one initially thinks.

I also really prefer namespaces to be lowercase, since that is the usual way they are written ("std", "boost" etc)

**Comment by kimbarrett** [comment]
> [...] And the enum values would have to be in that namespace in any case, so we wont get around having to qualify all "mtXXX" flags NMT::mtXXX.

We already have to solve essentially that problem because its now a scoped enum.  We currently define synonym
constants at global scope.  (C++20 provides `using MEMFLAGS;`.) Otherwise, we'd currently be needing
MEMFLAGS::mtXXX.

**Comment by kimbarrett** [comment]
> > I continue to mostly agree with @stefank.
> > I think this name shouldn't be considered in isolation. There are already a bunch of "NMT_" prefixed names. That's the common idiom for things like this (often (maybe even usually?) without the "_"). Why are we proposing to adopt a new style. (For just this? That would be weird. Or more broadly? That certainly needs more discussion.)
> 
> It is precisely because we already are using `NMT_TrackingStackDepth` and `NMT_TrackingLevel` (and the fact that MemType by itself was too general) that I suggested we adopt `NMT::` Yes, it would be all static class.
> 
> Why not all lower letter `nmt::`? Again, because we already use `NMT_` elsewhere.
> 
> My plan was later to switch from `NMT_` to `NMT::` for all of them. We can do `nmt::` too.

An `NMT_` => `NMT::` change requires using a namespace.  An allstatic class is closed for extension, and some of these
definitions are in different files.  The only way to use an allstatic class instead of a namespace is to go the same route as
currently used by the "os" class (over my dead body, and probably @tstuefe too).

That previously unstated plan also supports my claim that we shouldn't be considering this one type's name in isolation.

**Comment by gerard-ziemski** [comment]
Assuming for a second that we agree on the name of new type ( for now `MemTag`). Are we sure we want to combine that rename `MEMFLAGS` --> `MemTag` with changing the names of parameters and variables around this change at the same time?

This is exactly what I initially did, but after I took a 2nd look I got worried about how big it looked. Just for a reference these are my changes I am talking about, which I abandoned: https://openjdk.github.io/cr/?repo=jdk&pr=20472&range=00

**Comment by coleenp** [comment]
Yes, I think people want the name of the new type, and variables that are declared with this type changed in one PR.  Just looking through a bit of this webrev, this looks fine.  This isn't very hard to review.

**Comment by dholmes-ora** [comment]
FWIW as I recall the suggestion to include NMT in the name in some form was to make it clear that these kinds of parameter, which appear all over the place, are needed because of NMT and are not inherently part of whatever API they appear in. Whether that happens via a namespace, a nested enum, or a simple prefix, I don't really care except to say that anything that can then result in dropping the NMT in the source code (e.g. via a using directive) completely defeats the purpose of having it in the first place. So if there is no good answer here than I guess we just drop NMT from the name.

**Comment by tstuefe** [comment]
> FWIW as I recall the suggestion to include NMT in the name in some form was to make it clear that these kinds of parameter, which appear all over the place, are needed because of NMT and are not inherently part of whatever API they appear in. Whether that happens via a namespace, a nested enum, or a simple prefix, I don't really care except to say that anything that can then result in dropping the NMT in the source code (e.g. via a using directive) completely defeats the purpose of having it in the first place. So if there is no good answer here than I guess we just drop NMT from the name.

The funny part is that the result is now "MemType", which has the lowest results in the vote.

**Comment by gerard-ziemski** [comment]
> FWIW as I recall the suggestion to include NMT in the name in some form was to make it clear that these kinds of parameter, which appear all over the place, are needed because of NMT and are not inherently part of whatever API they appear in. Whether that happens via a namespace, a nested enum, or a simple prefix, I don't really care except to say that anything that can then result in dropping the NMT in the source code (e.g. via a using directive) completely defeats the purpose of having it in the first place. So if there is no good answer here than I guess we just drop NMT from the name.

Kim and Stefan said that any consideration of using namespace would require additional discussion. And almost everyone dislikes adding the `NMT_` prefix.

I feel like we achieved (imperfect) agreement that allows us to proceed with a cleanup using `MemTag` as the new type name to replace MEMFLAGS, which I hope everyone agrees is an improvement.

I am almost done with that name change and I see it as a significant improvement worthwhile of this effort, with anything else that can be handled in followups, however, if you feel strongly that we should discuss the full topic right now, before proceeding, please let it be known here.

Personally I just wanted to cleanup MEMFLAGS and related flag(s) names that we used in very inconsistent matter.

**Comment by coleenp** [comment]
Yes, I think this PR is not right.

**Comment by gerard-ziemski** [comment]
Closing this PR and will move to a new one shortly.

**Comment by gerard-ziemski** [comment]
The PR has been moved to https://github.com/openjdk/jdk/pull/20872

**Comment by tstuefe** [comment]
I am not excited about the final result, and I pity the poor backport maintainers, but it is also not a hill I'd die on.

**Comment by gerard-ziemski** [comment]
I'm not as excited about it as I was when started working on it.

Will get https://github.com/openjdk/jdk/pull/20872 ready, then will give it final thought.

**Pull request closed without merging**
