### PR TITLE
8245107: Use Unified Logging in trace_method_handle_stub()

### PR DESCRIPTION
**Pull request by chhagedorn**
This changes the logging of method handles from specifying Verbose to using unified logging with level Trace.

I only tested it on x86. Could anybody verify that it also works on ARM, S390 and PPC?

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8245107](https://bugs.openjdk.java.net/browse/JDK-8245107): Use Unified Logging in trace_method_handle_stub()

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1665/head:pull/1665`
`$ git checkout pull/1665`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Thank you for doing this.  I probably should have with my fix but it's better that someone who might read this information to do it.

**Review by TheRealMDoerr — APPROVED** [review]
Looks correct. Works on PPC64 and s390.

**Comment by chhagedorn** [comment]
Thanks Martin for your review and the verification on PPC64 and s390!

**Comment by chhagedorn** [comment]
Could anybody also quickly verify that the changes in `methodHandles_arm.cpp` build and are correct?

**Comment by chhagedorn** [comment]
Nevermind, I could verify that it builds correctly.

**Pull request closed without merging**
