### PR TITLE
8262093: java/util/concurrent/tck/JSR166TestCase.java failed "assert(false) failed: unexpected node"

### PR DESCRIPTION
**Pull request by vnkozlov**
LoadStore node misses Value() method which checks for Top inputs. As result dead data IR subgraph was not removed. Control subgraph is not eliminated because of complicated loop. 

The fix is to add missing Value() method.
Small refactoring in StoreCMNode::Value() because StoreNode::Value() already has checks for TOP edges.
Added check to SCMemProjNode::Value() which led to changes in GraphKit::compress_string() where call to transform() was missing.
Dumping additional info for asserts and code style fixes in macro.cpp.

Tested tier1-4 and xcomp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262093](https://bugs.openjdk.java.net/browse/JDK-8262093): java/util/concurrent/tck/JSR166TestCase.java failed "assert(false) failed: unexpected node"

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3226/head:pull/3226` \
`$ git checkout pull/3226`

Update a local copy of the PR: \
`$ git checkout pull/3226` \
`$ git pull https://git.openjdk.java.net/jdk pull/3226/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3226`

View PR using the GUI difftool: \
`$ git pr show -t 3226`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3226.diff">https://git.openjdk.java.net/jdk/pull/3226.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me but could you please update the code style of the lines you've touched? For example:
`const Type *t = phase->type( in(MemNode::Memory) );` -> `const Type* t = phase->type(in(MemNode::Memory));`

**Comment by vnkozlov** [comment]
> Looks good to me but could you please update the code style of the lines you've touched? For example:
> `const Type *t = phase->type( in(MemNode::Memory) );` -> `const Type* t = phase->type(in(MemNode::Memory));`

Done.

**Review by TobiHartmann — APPROVED** [review]
Thanks for updating! Looks good.

**Pull request closed without merging**
