### PR TITLE
8254244: Some code emitted by TemplateTable::branch is unused when running TieredCompilation

### PR DESCRIPTION
**Pull request by cl4es**
On x86, arm, aarch64 and s390, TemplateTable::branch emits code to allocate a MethodData which is never called if running TieredCompilation. Skipping it slightly reduces interpreter code size and results in a minor startup improvement (~100k instructions less).

The PPC implementation differs significantly, and is left untouched.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8254244](https://bugs.openjdk.java.net/browse/JDK-8254244): Some code emitted by TemplateTable::branch is unused when running TieredCompilation

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/564/head:pull/564`
`$ git checkout pull/564`

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Hi Claes, looks good. Seems like PPC was implemented like SPARC which was a bit different and is not affected by this issue.

**Comment by cl4es** [comment]
> Hi Claes, looks good. Seems like PPC was implemented like SPARC which was a bit different and is not affected by this issue.

Martin, thanks for reviewing and checking PPC.

**Review by coleenp — APPROVED** [review]
LGTM!

**Review by veresov — APPROVED** [review]

**Comment by cl4es** [comment]
Thanks for reviewing!

/integrate

**Pull request closed without merging**
