### PR TITLE
8255412: "Linux x32" should be "Linux x86" in submit workflow

### PR DESCRIPTION
**Pull request by shipilev**
John Paul Adrian Glaubitz mentions "x32" is actually the designation for "x86_64 with 32-bit pointers". Let's rename "Linux x32" to "Linux x86". I also realized that JDK-8254282 missed "Linux x32" for the platform selection. While you can guess it is accepted from reading the workflow, it would be more convenient to have it in the default argument list.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (1/1 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255412](https://bugs.openjdk.java.net/browse/JDK-8255412): "Linux x32" should be "Linux x86" in submit workflow

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/869/head:pull/869`
`$ git checkout pull/869`

### CODE REVIEW

**Comment by glaubitz** [comment]
Note that "Linux x32" is ambigious as this is the name for the x32 ABI (x86_64 with 32-bit pointers).

**Comment by magicus** [comment]
I agree with @glaubitz; "x32" is an odd choice of name for what we've been calling "x86" in the JDK build all the time.

I realize this unfortunate naming arrived with JDK-8254282, which I unfortunately was too late to review. However, I'd very much want to request the "x32" naming changed to "x86" consistently in submit.yml. This relates to JDK-8255305 as well. And frankly, I don't understand why this is a separate bug, instead of a part of JDK-8255305. Can you please explain the rationale for that? If you just want to make additional changes to JDK-8255305, there is really no need to open a new JBS issue and PR -- just push additional commits to JDK-8255305!

**Comment by shipilev** [comment]
> And frankly, I don't understand why this is a separate bug, instead of a part of JDK-8255305. Can you please explain the rationale for that? If you just want to make additional changes to JDK-8255305, there is really no need to open a new JBS issue and PR -- just push additional commits to JDK-8255305!

My rationale is simple: I am playing the whack-a-mole against the ongoing x86_32 regressions here -- every day that x86_32 is not tested adds up to my own churn to fix new x86_32 issues. If I add more commits to other PRs, they would need to get retested -- and that takes away precious time. Please let me push the chunks of the work as soon as they are logically complete and can be integrated.

I would file and bulk follow-up RFE to change "Linux x32" to "Linux x86" or whatever, as soon as the workflow pipeline is actually deployed.

**Comment by glaubitz** [comment]
> My rationale is simple: I am playing the whack-a-mole against the ongoing x86_32 regressions here

Would it be possible that we add a Travis hook so that commits get tested once before they are merged?

Travis supports all of the important architectures of OpenJDK on Linux these days: https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by shipilev** [comment]
> > My rationale is simple: I am playing the whack-a-mole against the ongoing x86_32 regressions here
> 
> Would it be possible that we add a Travis hook so that commits get tested once before they are merged?

Maybe, but that would be beyond the scope of this PR. These GH actions workflows go the long way already to make pre-integration tests, and they already run and used by OpenJDK contributors. I see immediate value in improving GH workflows, and see no clear estimate how much work would be involved in hooking up Travis, and what the project-wide consequences would be. If you want, open a new bug, prototype the change, discuss it there, and see if that is an acceptable thing to do.

**Comment by shipilev** [comment]
Let me coop this PR to rename x32 -> x86, among other cosmetic changes. Once #830 lands, I'll update x32 -> x86 in those new blocks as well. This way, we can have best of both worlds: x86_32 would start testing, and we would do the follow-ups here.

**Comment by magicus** [comment]
@shipilev I realize you are eager to have Github run automatic testing on platforms that you care about, but it's not like it's a regression that needs to be taken care of immediately. I strongly prefer to have a correct solution implemented once, before committing, than this piece-meal splitting of what's actually a single issue into three different PRs.

Now, the first one has already gone in, so not much to do about that, but I strongly believe that this and JDK-8255305 should be folded together in a single issue.

**Comment by shipilev** [comment]
> @shipilev I realize you are eager to have Github run automatic testing on platforms that you care about, but it's not like it's a regression that needs to be taken care of immediately. I strongly prefer to have a correct solution implemented once, before committing, than this piece-meal splitting of what's actually a single issue into three different PRs.

I very much care that the in-flight PRs (notably #505 and #548) would get their x86_32 testing early, hopefully before their integration. Because, having the same argument here, I strongly prefer to have a correct solution implemented once for the *actual product code*. I believe the choice between "making the test code sparkling clean in one go" and "making the product code sparking clean in one go" is obvious.

> Now, the first one has already gone in, so not much to do about that, but I strongly believe that this and JDK-8255305 should be folded together in a single issue.

I disagree. These changes are logically independent. #830 adds testing step, it is self-sufficient, already tested, and already in review. This one cleans up cosmetics, is relatively new, has a potential to accumulate other followups, and thus risks to drag on. Let's do the MVP in #830, and then do everything else.

**Comment by magicus** [comment]
Do you mean that you consider #505 and #548 dependent on this bug? If so, I think you misunderstand the purpose of the Github submit testing hook. You can -- and should! -- still do proper testing just as you did before the migration to Github. The Github action hook is a convenience.

Unless there is a breakage or a regression, I don't think we should rush patches in. It's better to get things right. You say "then do everything else". Are there more functionality regarding x86 that you would like to see integrated in the Github submit hook? If so, I think it's better that you present it now, than just a piece at a time.

> I believe the choice between "making the test code sparkling clean in one go" and "making the product code sparking clean in one go" is obvious.

I don't even understand what you mean by this.

> These changes are logically independent.

No, they are not. For one thing, this patch would explicitly introduce the "x32" naming, something JDK-8255305 is set. to remove. And this is just a trivial indication that both issues revolves around giving proper support for x86 in the submit flow.

Just to be clear: I do not object to making x86 a first-class citizen in the submit hook! What I *do* object to is this piece-meal integration of two, or worse,  three, PRs for what should have been one comprehensive PR.

**Comment by shipilev** [comment]
> Do you mean that you consider #505 and #548 dependent on this bug? If so, I think you misunderstand the purpose of the Github submit testing hook. You can -- and should! -- still do proper testing just as you did before the migration to Github. The Github action hook is a convenience.

Oh yes, I must be misunderstanding this. Because I thought pre-submit tests were the replacement for jdk-submit functionality, which was the Oracle's requirement for push to shared code. Good to know it had been demoted to mere suggestion.

> Unless there is a breakage or a regression, I don't think we should rush patches in. It's better to get things right. You say "then do everything else". Are there more functionality regarding x86 that you would like to see integrated in the Github submit hook? If so, I think it's better that you present it now, than just a piece at a time.

No, I mean to stop at `tier1` for x86_32. "Do everything else" means doing the cosmetics like in this PR that does not affect the actual testing.

> > I believe the choice between "making the test code sparkling clean in one go" and "making the product code sparking clean in one go" is obvious.
> 
> I don't even understand what you mean by this.

I mean that bikeshedding the testing code means holding off the testing of the product code. Making sure that product code is correct on x86_32 is more important than making sure the testing code is cosmetically clean.

> > These changes are logically independent.
> 
> No, they are not. For one thing, this patch would explicitly introduce the "x32" naming, something JDK-8255305 is set. to remove. And this is just a trivial indication that both issues revolves around giving proper support for x86 in the submit flow.

JDK-8255305 (#830) is set to add another instance of "x32", to already existing "x32" in the build steps. That means #830 yields a logically consistent `submit.yml`: it builds as "x32", it tests as "x32". This patch is set to rename "x32" -> "x86" (*if*, *IF* we agree that rename even makes sense!), yielding another logically consistent `submit.yml`. In this sense, they are logically independent.

> Just to be clear: I do not object to making x86 a first-class citizen in the submit hook! What I _do_ object to is this piece-meal integration of two, or worse, three, PRs for what should have been one comprehensive PR.

There are "Request Changes" in #830 that you can use as Reviewer. I would then oblige, but also reference this discussion. Because the next thing I expect is someone else to come along and ask why "x32" -> "x86" rename is not done separately from the addition of the actual testing. I would make that comment myself for someone else's PR, because I prefer changes to do one thing at a time.

**Comment by magicus** [comment]
> > Do you mean that you consider #505 and #548 dependent on this bug? If so, I think you misunderstand the purpose of the Github submit testing hook. You can -- and should! -- still do proper testing just as you did before the migration to Github. The Github action hook is a convenience.

> Oh yes, I must be misunderstanding this. Because I thought pre-submit tests were the replacement for jdk-submit functionality, which was the Oracle's requirement for push to shared code. Good to know it had been demoted to mere suggestion.

I did not say it was a "suggestion". I said it was a "convenience". Those two are not the same. As a Committer, it is your responsibility, now and as it always has been, to make sure the code is tested to the best of your abilities.  As a Reviewer, it is your responsibility to make make sure that no significant testing has been left out by the Committer.

> Making sure that product code is correct on x86_32 is more important than making sure the testing code is cosmetically clean.

Thankfully, those two are not orthogonal! The testing for x86 on product changes can proceed just as before the move to Github, and we can make sure to keep the testing code up to the same quality as one should expect.

**Comment by magicus** [comment]
@shipilev My suggestion is that you take the commits from this PR and fold them into #830, and update the code added in #830 to match the naming. If you do that, I'll accept your patch.

**Comment by shipilev** [comment]
> @shipilev My suggestion is that you take the commits from this PR and fold them into #830, and update the code added in #830 to match the naming. If you do that, I'll accept your patch.

Thanks. Again: please record this suggestion as formal "request changes" in #830, so that #830 PR history is consistent and clear to outside observer without reading the whole thread.

**Pull request closed without merging**
