### PR TITLE
8297258: Typo in `java -help` referencing -disable-@files instead of --disable-@files

### PR DESCRIPTION
**Pull request by asotona**
There is a typo in `java -help` referencing -disable-@files instead of --disable-@files option.

Please review.

Thanks,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297258](https://bugs.openjdk.org/browse/JDK-8297258): Typo in `java -help` referencing -disable-@files instead of --disable-@files

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11236/head:pull/11236` \
`$ git checkout pull/11236`

Update a local copy of the PR: \
`$ git checkout pull/11236` \
`$ git pull https://git.openjdk.org/jdk pull/11236/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11236`

View PR using the GUI difftool: \
`$ git pr show -t 11236`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11236.diff">https://git.openjdk.org/jdk/pull/11236.diff</a>

</details>

### CODE REVIEW

**Comment by naotoj** [comment]
Changes in English resource bundles are automatically detected by the translation process, and each JDK release (incl. 20) will have an l10n cycle that should correctly reflect the changes in those l10n files. However that only applies to Oracle supported locales (de/ja/zh-CN), so changes in those other l10n files in this PR will stay.

**Review by mlchung — APPROVED** [review]
I believe there is no need to update the localized versions as they will be updated in bulk toward the end of the release.   This change is trivial and it's fine.

**Comment by AlanBateman** [comment]
> I believe there is no need to update the localized versions as they will be updated in bulk toward the end of the release. 

@asotona - I see you integrated the change with the localized properties? Did you mean to do that? I support the next l10n update will just refresh the languages that they support but in general, we don't directly edit them.

**Pull request closed without merging**
