### PR TITLE
8257424: RecordingStream does not specify the recording name

### PR DESCRIPTION
**Pull request by YaSuenag**
`RecordingStream` will start new flight recording to gather events. It has some of methods which are equivalent to `Recording`, but we cannot set recording name.

If we can specify the name for `RecordingStream`, it is useful to distinguish recordings by JFR.check dcmd.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257424](https://bugs.openjdk.java.net/browse/JDK-8257424): RecordingStream does not specify the recording name

### Reviewers
 * [Erik Gahlin](https://openjdk.java.net/census#egahlin) (@egahlin - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1520/head:pull/1520`
`$ git checkout pull/1520`

### CODE REVIEW

**Comment by egahlin** [comment]
The underlying recording is an implementation detail, not sure it should show up in jcmd at all. Also, RemoteRecordingStream and RecordingStream should be interchangeable and setting the name on RemoteRecordingStream will not work with the current implementation. 

We have deliberately not added methods in Recording to RecordingStream and kept the API to the bare minimum Many of the methods are trivial to implement, but we don't want to commit on them yet. Instead we like to get the overall architecture correct and there still things we need to figure out.

**Comment by YaSuenag** [comment]
`RemoteRecordingStream` would set the specified recording name.
https://github.com/openjdk/jdk/blob/master/src/jdk.management.jfr/share/classes/jdk/management/jfr/RemoteRecordingStream.java#L278

> The underlying recording is an implementation detail, not sure it should show up in jcmd at all. 

If so, why `RemoteRecordingStream` will set the name?

> Also, RemoteRecordingStream and RecordingStream should be interchangeable and setting the name on RemoteRecordingStream will not work with the current implementation.

I think we can add `setName()` to both `RecordingStream` and `RemoteRecordingStream`, and also it is nature because `RemoteRecordingStream` will set specified name in current behavior.

**Comment by egahlin** [comment]
> If so, why `RemoteRecordingStream` will set the name?

There is no API to set the name.

**Comment by egahlin** [comment]
> `RemoteRecordingStream` would set the specified recording name.
> https://github.com/openjdk/jdk/blob/master/src/jdk.management.jfr/share/classes/jdk/management/jfr/RemoteRecordingStream.java#L278
> 
> > The underlying recording is an implementation detail, not sure it should show up in jcmd at all.
> 
> If so, why `RemoteRecordingStream` will set the name?
> 
> > Also, RemoteRecordingStream and RecordingStream should be interchangeable and setting the name on RemoteRecordingStream will not work with the current implementation.
> 
> I think we can add `setName()` to both `RecordingStream` and `RemoteRecordingStream`, and also it is nature because `RemoteRecordingStream` will set specified name in current behavior.

The name is used to identify it is a streaming recording, so it is closed properly. See OngoingStream. This is no ideal solution, but it works for now.

**Comment by egahlin** [comment]
If you want to make the name of a RecordingStream "Recording Stream" + creationTime.toString(), for consistency and debuggability, I'm fine with that, but I rather not add an API method, at least not now.

**Comment by YaSuenag** [comment]
> If you want to make the name of a RecordingStream "Recording Stream" + creationTime.toString(), for consistency and debuggability, I'm fine with that, but I rather not add an API method, at least not now.

Agree, should I change issue title? or should I file to JBS with new title?

**Comment by YaSuenag** [comment]
I updated PR. I will update both subject and description if you are ok.

**Comment by egahlin** [comment]
No problem, update PR subject and bug description. Have you run the tests in jdk/jdk/jfr?

**Comment by YaSuenag** [comment]
@egahlin I updated subject and description on this PR and on JBS.

I tested jdk/jdk/jfr on my Linux x64 with this change, Only jdk/jfr/api/recording/event/TestReEnableName.java was failed, but it does not seem to cause by this change.

```
test result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Too few events found: expected 0 >= 5
```

**Review by egahlin — APPROVED** [review]

**Pull request closed without merging**
