### PR TITLE
8309468: Remove jvmti Allocate locker test case

### PR DESCRIPTION
**Pull request by lkorinth**
There is a bunch of tests that are used to test critical section/gc locker. One of the test is named jvmti locker. In that test, JNI code is doing a loop of ` jvmti->Allocate()` followed `sleep()` followed by a `jvmti->Deallocate()`. There is no JVM lock implementation to be tested on jvmti Allocate/Deallocate, they are implemented using malloc/free. Let us save test time, code complexity and confusion by removing this test. 

This removal is very similar to https://bugs.openjdk.org/browse/JDK-8309048

(Oracle) hs-tier5 testing passed on x86-64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309468](https://bugs.openjdk.org/browse/JDK-8309468): Remove jvmti Allocate locker test case (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14421/head:pull/14421` \
`$ git checkout pull/14421`

Update a local copy of the PR: \
`$ git checkout pull/14421` \
`$ git pull https://git.openjdk.org/jdk.git pull/14421/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14421`

View PR using the GUI difftool: \
`$ git pr show -t 14421`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14421.diff">https://git.openjdk.org/jdk/pull/14421.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14421#issuecomment-1587696411)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Serviceability folk should probably look at this and @lmesnik.

I can't see what this is actually trying to test either, so removing it seems fine to me too.

Thanks.

**Review by lmesnik — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]
I also do not see any value in this test, so it looks good to get rid of it.
Thanks,
Serguei

**Comment by lkorinth** [comment]
Thanks David, Leonid and Serguei!
/integrate

**Pull request closed without merging**
