### PR TITLE
Update field access methods in ZipUtils to use the VarHandle API

### PR DESCRIPTION
**Pull request by eirbjo**
This PR suggests to update the field access methods in ZipUtils to use the VarHandle API when reading multibyte values from byte arrays.

To facilitate this change,  we first remove duplication in existing methods such that:

- CH aliases to the new method get8
- SH aliases to get16
- LG aliases to get32
- LL aliases to get64
- get16 uses get8
- get32 uses get32S

(Note that CH, SH, LG, LL could now be removed in in favour of their targets. I consider this out of scope for this PR.)

To simplify review, the refactoring is done in  a separate commit 0e924a2 

Then, in commit 25ac0a6, the methods get16, get64 and get32S are updated to read values using the VarHandle API.

Performance:

I had problems getting stable results from the existing ZipFileOpen test, but when reading an existing xalan.jar (1565 entries), I'm seeing a ~3% speedup:

Baseline:

```
Benchmark                     Mode  Cnt       Score     Error  Units
ZipFileOpen.openCloseZipFile  avgt   25  136537.112 ± 340.233  ns/op
```

VarHandle:

```
Benchmark                     Mode  Cnt       Score     Error  Units
ZipFileOpen.openCloseZipFile  avgt   25  132600.030 ± 422.163  ns/op
```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12273/head:pull/12273` \
`$ git checkout pull/12273`

Update a local copy of the PR: \
`$ git checkout pull/12273` \
`$ git pull https://git.openjdk.org/jdk pull/12273/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12273`

View PR using the GUI difftool: \
`$ git pr show -t 12273`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12273.diff">https://git.openjdk.org/jdk/pull/12273.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
3% seem like a rather small win, no? This will probably add a few VHs on the bootstrap path for quite a few applications, too, so we need to see that startup/warmup numbers aren't too much worse off and that doing this is the right trade-off

**Comment by eirbjo** [comment]
> 3% seem like a rather small win, no? This will probably add a few VHs on the bootstrap path for quite a few applications, too, so we need to see that startup/warmup numbers aren't too much worse off and that doing this is the right trade-off

Thanks, did not consider that! Do you have suggestions on how to assess the impact on startup/warmup?

**Comment by cl4es** [comment]
Wall clock measures of applications that load any number of jar files. Impact of bootstrapping and warming up som VHs, if any, would be more prominent on smaller and medium size applications.

**Comment by eirbjo** [comment]
> Wall clock measures of applications that load any number of jar files. 

Can we make a brave assumption that the worst-case scenario would be to load a single class from a single JAR on the classpath? This would force the VarHandles to be loaded via ZipFile, but do very little actual IO to amortize the cost.

So I made the following Java class which outputs the uptime of the JVM:

```
public static void main(String[] args) {
    System.out.println(java.lang.management.ManagementFactory.getRuntimeMXBean().getUptime());
}
```

Then I performed 1000 startups on each of master and the PR branch, then calculated P50, P75, P95, P99 and STDEV:

```
Percentile.  Master	 VarHandles
50 %             62      62
75 %             63      63
90 %             66      67
95 %             66      67
99 %             68      68.01
STDEV           1.9      2.14
```

No measurable diffence outside rounding errors, but I'm not sure how reliable the getUptime method is. Unfortunately, it returns the time in millis.

**Comment by cl4es** [comment]
JMX is pretty heavy to initialize itself, and this takes the time from some point from some "VM initialization done" time to the sampling, which might hide/miss what you're trying to measure. I'd prefer some external time measurement on the minimal application that triggers the code in question. Taking out the diff, if any, on what classes are loaded can also be enlightening (`-Xlog:class+load`)

**Comment by eirbjo** [comment]
To measure the impact on warmup, I made a class which opens all 109 JARs which are dependencies of spring-petclinic:

```
List<Path> jars = Files.list(Path.of(args[0])).collect(Collectors.toList());
for (Path file : jars) {
    new ZipFile(file.toFile());
}
System.out.println(ManagementFactory.getRuntimeMXBean().getUptime()); 
```

This is also run 1000 times for each branch.

Results show a regression for VarHandles:

```
Px   Master VarHandle
P50   88   96
P75   89   97
P90   90   99
P95   91   105
P99   98   106
STDEV 2,44 3,39
```

I'll look into measuring without JMX overhead, but it does look like the warmup cost makes this PR not worth considering.

**Comment by cl4es** [comment]
Right, if we subtract the overhead in the first test then the difference should mostly be from that `new ZipFile` loop, suggesting on average a cost increase from 26 to 34ms, or roughly 30% overhead in this warmup test. While VHs (and MHs) are great, they still have this unfortunate tradeoff that they take some time to bootstrap, then run a bit slower through interpreter and profiling phases before they end up being optimized to more optimal code than the baseline - hopefully. Had it been a larger peak performance win it'd be easier to accept the trade-off. Now it looks more dubious.

**Comment by eirbjo** [comment]
I agree it looks dubious. BTF, here's updated results measuring time using System.nanoTime, removing JMX overhead:

```
Percentile	Master		VarHandles
50 %		47		54
75 %		48		54
90 %		50		56
95 %		52		58
99 %		54		59
STDEV		1,92		1,82
```

**Comment by RogerRiggs** [comment]
PR https://github.com/openjdk/jdk/pull/12076 just introduced a JDK internal class (`jdk.internal.util.ByteArray`) to speed up get/set of primitive types in byte arrays.
Using it instead of task specific VarHandles may not help with interpreter/startup but its better than creating multiple VarHandles that do the same thing.

**Comment by eirbjo** [comment]
Roger,

Bytes in ZIPs files are in little-endian order, so I don't think the methods  in ByteArray are useful here.

I agree that it would probably not help much on the interpreter/startup time.

**Comment by RogerRiggs** [comment]
fyi, The little-endian version ByteArrayLittleEndian is in PR https://github.com/openjdk/jdk/pull/12204. (Not yet integrated)

**Pull request closed without merging**
