### PR TITLE
8275745: Reproducible copyright headers

### PR DESCRIPTION
**Pull request by ebourg**
The copyright headers are generated at build time, and the year inserted in the template depends on the current date. This means the headers are not reproducible if the project is built a year later. The year in the headers could be derived from the SOURCE_DATE_EPOCH environment variable to make the build reproducible (this variable is already used in other parts of the build).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275745](https://bugs.openjdk.java.net/browse/JDK-8275745): Reproducible copyright headers

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to 9c4efbda20bbf8afbc6027356385c5aa4e5e7c80
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/1498/head:pull/1498` \
`$ git checkout pull/1498`

Update a local copy of the PR: \
`$ git checkout pull/1498` \
`$ git pull https://git.openjdk.java.net/jdk pull/1498/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1498`

View PR using the GUI difftool: \
`$ git pr show -t 1498`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/1498.diff">https://git.openjdk.java.net/jdk/pull/1498.diff</a>

</details>

### CODE REVIEW

**Comment by ebourg** [comment]
Dummy comment to keep this issue alive (auto closing after 8 weeks of inactivity is a bad idea)

**Comment by ebourg** [comment]
.

**Comment by ebourg** [comment]
.

**Comment by kelthuzadx** [comment]
You should link an issue to this patch so that a Request-For-Review email will be sent to the corresponding mailing list. Or they may not notice your patch.

**Comment by ebourg** [comment]
Unfortunately I don't have a JBS account, so I'm stuck here bumping this PR every 4 weeks until someone notices it.

**Comment by ebourg** [comment]
.

**Comment by kelthuzadx** [comment]
Hi Emmanuel Bourg,

I'm not quite sure whether this PR is useful since I'm not familiar with the make system. I think you can just send an email to build-dev@openjdk.java.net(You may need to subscribe [it](https://mail.openjdk.java.net/mailman/listinfo/build-dev) before), the related folks/experts would review your change or give some meaningful feedbacks if they think it's worth doing it. Good Luck!

Thanks,
Yang

**Comment by ebourg** [comment]
Yes, 5 months later I now understand that the GitHub issue tracker isn't the right entry point to contribute to OpenJDK, sadly.

**Comment by ebourg** [comment]
.

**Comment by magicus** [comment]
@ebourg I have now modified this patch so it uses COPYRIGHT_YEAR, and sets COPYRIGHT_YEAR based on SOURCE_DATE_EPOCH, if it exists. The patch is in a branch in my personal fork, https://github.com/magicus/jdk/tree/reproducible-copyright-year.

If you think it looks good, we have two possible ways forward. Either you close this PR, and I open a new targeting the same JBS issue, and credit you as co-author. Or you integrate my branch into this PR, and credit me as co-author. Any of them is OK for me, but I think the former is simpler.

**Comment by ebourg** [comment]
@magicus Thank you! I've integrated your branch

**Review by magicus — APPROVED** [review]
LGTM but then again I wrote most of it. :) Please await further reviewers before integrating.

**Comment by ebourg** [comment]
I can rebase the branch with your changes only, my commit just adds noise.

**Comment by magicus** [comment]
In the future, please refrain from force pushing to a PR. It makes history hard to follow for reviewers, and is generally strongly discouraged. OpenJDK uses the Skara tools which will automatically squash and rebase the commits in the PR.

**Comment by ebourg** [comment]
Thank you for the advice, I'm not familiar with the Skara workflow yet.

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
@ebourg To finish integrating this PR, you need to type `/integrate` as a PR comment. This will allow the Skara bots to move the bug on to the state where I can sponsor it.

**Comment by ebourg** [comment]
@magicus Thank you for the hint!

**Comment by magicus** [comment]
@ebourg Thank you for your contribution! It's been a long and bumpy ride for something that seemed like a simple patch. I hope you have not been scared away from contributing to the JDK in the future. :-)

**Comment by ebourg** [comment]
Thanks again for walking me through the process, I'll try to submit more reproducibility fixes, there are a few more patches pending in Debian:
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-build-jmod.diff
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-build-user.diff
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-character-data.diff
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-javadoc-timestamp.diff
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-module-info.diff
https://salsa.debian.org/openjdk-team/openjdk/-/blob/openjdk-17/debian/patches/reproducible-properties-timestamp.diff

**Comment by magicus** [comment]
@ebourg  You might be interested in watching what @andrew-m-leonard is doing in the area, for example in https://github.com/openjdk/jdk/pull/6395.

**Pull request closed without merging**
