### PR TITLE
8321314: Reinstate disabling the compiler's default active annotation processing

### PR DESCRIPTION
**Pull request by jddarcy**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8321319](https://bugs.openjdk.org/browse/JDK-8321319) to be approved

### Issues
 * [JDK-8321314](https://bugs.openjdk.org/browse/JDK-8321314): Reinstate disabling the compiler's default active annotation processing (**Enhancement** - P3)
 * [JDK-8321319](https://bugs.openjdk.org/browse/JDK-8321319): Reinstate disabling the compiler's default active annotation processing (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19331/head:pull/19331` \
`$ git checkout pull/19331`

Update a local copy of the PR: \
`$ git checkout pull/19331` \
`$ git pull https://git.openjdk.org/jdk.git pull/19331/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19331`

View PR using the GUI difftool: \
`$ git pr show -t 19331`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19331.diff">https://git.openjdk.org/jdk/pull/19331.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19331#issuecomment-2127898339)

### CODE REVIEW

**Comment by jddarcy** [comment]
See broader policy discussion in

    https://mail.openjdk.org/pipermail/jdk-dev/2024-May/009028.html

**Comment by SentryMan** [comment]
> Since [JDK-8306819](https://bugs.openjdk.org/browse/JDK-8306819), support for '-proc:full' has been backported to earlier update release trains. This should ease the impact of the behavioral change.

I'm not sure I follow. Since the warning saying "implicit annotation processing will be disabled" was not also backported, how would people on earlier Java versions even know to use this new parameter? 

As it stands, the behavior change will still break a large number of builds that rely on implicit annotation processing, so I don't understand how the impact was reduced. Perhaps I'm looking at it from the wrong angle?

**Comment by jddarcy** [comment]
> > Since [JDK-8306819](https://bugs.openjdk.org/browse/JDK-8306819), support for '-proc:full' has been backported to earlier update release trains. This should ease the impact of the behavioral change.
> 
> I'm not sure I follow. Since the warning saying "implicit annotation processing will be disabled" was not also backported, how would people on earlier Java versions even know to use this new parameter?
> 
> As it stands, the behavior change will still break a large number of builds that rely on implicit annotation processing, so I don't understand how the impact was reduced. Perhaps I'm looking at it from the wrong angle?

With `-proc:full` backed to 17u and 11u (already in JDK 21) ,together with current version of the Maven compiler plugin supporting `-proc:full`, the ability to specific `-proc:full` in a build is decoupled from upgrading to JDK 21 or later.

In other words, developers today[*] can change their build configurations to work seamlessly with a future upgrade to JDK 23, or later, with the different annotation processing default.

Of course, if a build is not using annotation processing, it will work fine after the change too. Various other explicit build configurations to support annotation processing, such as setting the processor path, are possible as well.

[*] Using the current Maven compiler plugin and current version of a JDK update release.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Pull request closed without merging**
