### PR TITLE
8324736: Invalid end positions for EMPTY_STATEMENT

### PR DESCRIPTION
**Pull request by archiecobbs**
In the fix for [JDK-8305671](https://bugs.openjdk.org/browse/JDK-8305671), an `EMPTY_STATEMENT` representing a lone semicolon was being created with the wrong source code position. The bug was that the starting position needed to be captured prior to advancing to the next token, not after.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324736](https://bugs.openjdk.org/browse/JDK-8324736): Invalid end positions for EMPTY_STATEMENT (**Bug** - P4)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17595/head:pull/17595` \
`$ git checkout pull/17595`

Update a local copy of the PR: \
`$ git checkout pull/17595` \
`$ git pull https://git.openjdk.org/jdk.git pull/17595/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17595`

View PR using the GUI difftool: \
`$ git pr show -t 17595`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17595.diff">https://git.openjdk.org/jdk/pull/17595.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17595#issuecomment-1912515759)

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Comment by archiecobbs** [comment]
@vicente-romero-oracle any interest in sponsoring this so we can wrap it up? Thanks.

**Pull request closed without merging**
