### PR TITLE
JDK-8305320: DbgStrings and AsmRemarks are leaking

### PR DESCRIPTION
**Pull request by jcking**
Fix two leaks related to `DbgStrings` and `AsmRemarks` in debug builds.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305320](https://bugs.openjdk.org/browse/JDK-8305320): DbgStrings and AsmRemarks are leaking

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13249/head:pull/13249` \
`$ git checkout pull/13249`

Update a local copy of the PR: \
`$ git checkout pull/13249` \
`$ git pull https://git.openjdk.org/jdk.git pull/13249/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13249`

View PR using the GUI difftool: \
`$ git pr show -t 13249`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13249.diff">https://git.openjdk.org/jdk/pull/13249.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13249#issuecomment-1490775234)

### CODE REVIEW

**Comment by jcking** [comment]
Friendly poke.

**Review by coleenp — APPROVED** [review]
This looks like a good change.  Thank you for finding this.

**Review by fparain — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
