### PR TITLE
8035271: Incorrect indentation of LineNumberTable/LocalVariableTable/Exception table/LocalVariableTypeTable/StackMapTable/RuntimeVisibleTypeAnnotations in verbose mode

### PR DESCRIPTION
**Pull request by jonath4ndev**
Very similar and related to: https://bugs.openjdk.org/browse/JDK-8034066

This PR includes changes to ensure the indentation of `LineNumberTable` and `LocalVariableTable` behave in the same way both for the `javap -verbose` and `javap -l -c` case. Prior to this PR, for the `javap -l -c` case the `LineNumberTable` and `LocalVariableTable` attributes are not indented with regard to the `Code: ` header.

The only case, where no extra indentation is added is for `javap -l` without `-c` -- As it does not make sense to indent if there is no `Code:` header to indent relative to. I am not sure if there is a use case for `-l` without `-c`, but would leave this functionality as is.

### Case: `javap -l -c EmptyLoop.class`

```
...
  public void emptyLoop();
    Code:
       0: iconst_0
       ...
      14: return
    LineNumberTable:
      line 3: 0
      line 5: 14
...
```

### Case: `javap -verbose EmptyLoop.class`

```
...
  public void emptyLoop();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=1
         0: iconst_0
         ...
        14: return
      LineNumberTable:
        line 3: 0
        line 5: 14
...
```

### Case: `javap -l -c EmptyLoop.class`
```
...
  public void emptyLoop();
    Code:
         0: iconst_0
         ...
        14: return
      LineNumberTable:
        line 3: 0
        line 5: 14
...
```

### Add code header for only `-l` case?
Currently for `-l` without `-c` things look as follows:

```
...
  public void emptyLoop();
    LineNumberTable:
      line 3: 0
      line 5: 14
...
```

One could also imagine making the output:
```
...
  public void emptyLoop();
    Code:
      LineNumberTable:
        line 3: 0
        line 5: 14
...
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8035271](https://bugs.openjdk.org/browse/JDK-8035271): Incorrect indentation of LineNumberTable/LocalVariableTable/Exception table/LocalVariableTypeTable/StackMapTable/RuntimeVisibleTypeAnnotations in verbose mode (**Bug** - P5)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22359/head:pull/22359` \
`$ git checkout pull/22359`

Update a local copy of the PR: \
`$ git checkout pull/22359` \
`$ git pull https://git.openjdk.org/jdk.git pull/22359/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22359`

View PR using the GUI difftool: \
`$ git pr show -t 22359`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22359.diff">https://git.openjdk.org/jdk/pull/22359.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22359#issuecomment-2497965205)
</details>

### CODE REVIEW

**Comment by mcimadamore** [comment]
> > Add code header for only -l case?

I also like this option, because it maintains the "nesting" of attributes - e.g. the main thing here is that LNT and LVT are attributes of Code, so they should be nested in there. One option could be to report the general number of opcodes in the Code attribute, if no `-c` is provided (so that at least that can be used as a guidance for interpreting the other attributes.

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
The current output looks fine; adding a `Code` header is more accurate that these attributes are on the Code instead of the method.

/reviewers 2 reviewer

**Comment by jonath4ndev** [comment]
> > > Add code header for only -l case?
> 
> I also like this option, because it maintains the "nesting" of attributes - e.g. the main thing here is that LNT and LVT are attributes of Code, so they should be nested in there. One option could be to report the general number of opcodes in the Code attribute, if no `-c` is provided (so that at least that can be used as a guidance for interpreting the other attributes).


Do you mean comething as simple as this just counting the number of instructions?

### `javap -l EmptyLoop`
```
Compiled from "EmptyLoop.java"
public class EmptyLoop {
  public EmptyLoop();
    Code:
      Opcode count: 3
      LineNumberTable:
        line 1: 0

  public void emptyLoop();
    Code:
      Opcode count: 8
      LineNumberTable:
        line 3: 0
        line 5: 14
}
```

<details>
<summary>With code for context: `javap -l -c EmptyLoop`</summary>

```
Compiled from "EmptyLoop.java"
public class EmptyLoop {
  public EmptyLoop();
    Code:
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 1: 0

  public void emptyLoop();
    Code:
         0: iconst_0
         1: istore_1
         2: iload_1
         3: bipush        10
         5: if_icmpge     14
         8: iinc          1, 1
        11: goto          2
        14: return
      LineNumberTable:
        line 3: 0
        line 5: 14
}
```

</details>

**Comment by jonath4ndev** [comment]
> > Add code header for only -l case?
> 
> I think that is the right move. `LineNumberTable`, and others listed here: https://docs.oracle.com/javase/specs/jvms/se23/html/jvms-4.html#jvms-4.7-320 are/can be sub-attributes of the code attribute. So I think it makes sense to render them under `Code:`.

I have added this.

Notably I opted to split `writeInternal` into `writeMinimal` and `writeVerbose` as the logic was getting a little unreadable. (things like `if (!minimal || options.showLineAndLocalVariableTables)`). Although some added duplication, I think this is more readable.

**Review by JornVernee — APPROVED** [review]

**Review by liach — APPROVED** [review]
Good cleanup to writeInternal.

**Comment by mcimadamore** [comment]
> Do you mean comething as simple as this just counting the number of instructions?

Something like this, yeah, if this is deemed useful

**Comment by mcimadamore** [comment]
> Something like this, yeah, if this is deemed useful

Or, if code is skipped, should we also skip code attributes?

**Comment by jonath4ndev** [comment]
> Something like this, yeah, if this is deemed useful

I did implement this locally, but I am not sure of its utility. The values in `LineNumberTable` refer to PC locations, for which the number of opcodes does not really provide much context. What do you think?

> Or, if code is skipped, should we also skip code attributes?

I tend to like this approach, especially if I were starting from scratch. But considering the current functionality may be depended on, I think the current solution is a decent trade off of increasing readability/uniformity, without removing this existing functionality.

> For the records, I'm fine for these issues to be tackled also in separate PRs.

In that case I would suggest integrating as is. I would personally tend towards no further changes thereafter, but would be interested any other opinions/suggestions to the contrary.

**Comment by jonath4ndev** [comment]
I have created a new Enhancement Issue on JBS: https://bugs.openjdk.org/browse/JDK-8345123 which we can further look into and will go forward with integrating this PR.

**Comment by mcimadamore** [comment]
> I tend to like this approach, especially if I were starting from scratch. But considering the current functionality may be depended on, I think the current solution is a decent trade off of increasing readability/uniformity, without removing this existing functionality.

I'm not too concerned by this TBH. The set of options seem to be contradictory (e.g. I want to omit code attribute, but retain all the attributes nested inside Code, which are often expressed in terms of offset onto the -- omitted -- opcode array). I think it's ok if we decided that `-c` means "really, shut up about Code" :-)

**Comment by jonath4ndev** [comment]
I have additionally created https://bugs.openjdk.org/browse/JDK-8345145 to further pursue the `-l` without `-c` case, with the idea of not outputting any code attributes when neither `-c` nor `-v` is specified.

**Pull request closed without merging**
