### PR TITLE
8283379: Memory leak in FileHeaderHelper

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this small patch to fix memory leak in `FileHeaderHelper`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283379](https://bugs.openjdk.java.net/browse/JDK-8283379): Memory leak in FileHeaderHelper

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7872/head:pull/7872` \
`$ git checkout pull/7872`

Update a local copy of the PR: \
`$ git checkout pull/7872` \
`$ git pull https://git.openjdk.java.net/jdk pull/7872/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7872`

View PR using the GUI difftool: \
`$ git pr show -t 7872`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7872.diff">https://git.openjdk.java.net/jdk/pull/7872.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,
David

**Review by iklam — APPROVED** [review]
Looks good to me.

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by zhengyu123** [comment]
Thanks, @dholmes-ora @iklam @tstuefe

**Pull request closed without merging**
