### PR TITLE
8335946: DTrace code snippets should be generated when DTrace flags are enabled

### PR DESCRIPTION
**Pull request by kuaiwei**
Some DTrace code snippets are generated no matter dtrace is enabled or not. It looks dtrace flags could be dynamic changed in previous jdk releases. Since they are not changeable, the code snippets can be generated based on flags. The code snippets are:
1. method entry of native wrapper
2. method entry/exit of interpreter
3. allocation of interpreter

For example, run this command and check output with x86_64 build:
./java -XX:+UnlockDiagnosticVMOptions -XX:+PrintNativeNMethods -version

```asm
  0x00007f541436418f: cmpb $0x0,0x163c8b17(%rip) # 0x00007f542a72ccad
                                                            ; {external_word}
  0x00007f5414364196: je 0x00007f54143641d0
  0x00007f541436419c: push %rsi
  0x00007f541436419d: push %rdx
  0x00007f541436419e: push %rcx
  0x00007f541436419f: movabs $0x7f5386436860,%rsi ; {metadata({method} {0x00007f5386436860} 'getReferenceVolatile' '(Ljava/lang/Object;J)Ljava/lang/Object;' in 'jdk/internal/misc/Unsafe')}
  0x00007f54143641a9: mov %r15,%rdi
  0x00007f54143641ac: test $0xf,%spl
  0x00007f54143641b0: je 0x00007f54143641c8
  0x00007f54143641b6: sub $0x8,%rsp
  0x00007f54143641ba: callq 0x00007f5429ffe180 ; {runtime_call SharedRuntime::dtrace_method_entry(JavaThread*, Method*)}
  0x00007f54143641bf: add $0x8,%rsp
  0x00007f54143641c3: jmpq 0x00007f54143641cd
  0x00007f54143641c8: callq 0x00007f5429ffe180 ; {runtime_call SharedRuntime::dtrace_method_entry(JavaThread*, Method*)}
  0x00007f54143641cd: pop %rcx
  0x00007f54143641ce: pop %rdx
  0x00007f54143641cf: pop %rsi
```

Apply this patch, dtrace_method invocation will be emitted only when DTraceMethodProbes is enabled.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335946](https://bugs.openjdk.org/browse/JDK-8335946): DTrace code snippets should be generated when DTrace flags are enabled (**Enhancement** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20090/head:pull/20090` \
`$ git checkout pull/20090`

Update a local copy of the PR: \
`$ git checkout pull/20090` \
`$ git pull https://git.openjdk.org/jdk.git pull/20090/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20090`

View PR using the GUI difftool: \
`$ git pr show -t 20090`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20090.diff">https://git.openjdk.org/jdk/pull/20090.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20090#issuecomment-2216583461)

### CODE REVIEW

**Comment by TobiHartmann** [comment]
/label remove hotspot-compiler
/label add hotspot-runtime

I think this should go to hotspot-runtime.

**Review by coleenp — APPROVED** [review]
This looks good.  Does anyone use DTRACE?

**Comment by kuaiwei** [comment]
Thanks for review.

**Comment by kuaiwei** [comment]
@dholmes-ora Thanks for your help.

**Pull request closed without merging**
