### PR TITLE
8264019: Use the blessed modifier order in java.xml

### PR DESCRIPTION
**Pull request by alblue**
As a subtask of JDK-8263854 this cleans up the `java.xml` module to used the blessed modifier order.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8264019](https://bugs.openjdk.java.net/browse/JDK-8264019): Use the blessed modifier order in java.xml

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3091/head:pull/3091`
`$ git checkout pull/3091`

To update a local copy of the PR:
`$ git checkout pull/3091`
`$ git pull https://git.openjdk.java.net/jdk pull/3091/head`

### CODE REVIEW

**Comment by alblue** [comment]
Would someone mind creating a bug for me under the parent bug JDK-8263854?

**Comment by alblue** [comment]
@shipilev would you mind creating a bug for me please?

**Comment by shipilev** [comment]
Sure, here it is: https://bugs.openjdk.java.net/browse/JDK-8264019

**Comment by AlanBateman** [comment]
The JDK's copy of the xalan and xerces code has diverged significantly from upstream so maybe this change is okay, Joe Wang can say.

**Comment by JoeWang-Java** [comment]
Hi Alex,  thanks for looking into this. As Alan mentioned, these code came from Apache, while we've made changes, we refrained from making minor ones (code style, format and etc.) as it would add unnecessary burden for future merges. I'd prefer not taking the changes to the source files that came from Apache. Thanks.

**Comment by alblue** [comment]
OK, will abandon it. If someone could close the associated bug that would be appreciated.

**Pull request closed without merging**
