### PR TITLE
8259846: [BACKOUT] JDK-8259278 Optimize Vector API slice and unslice operations

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit a6b2162f5400b4596afa5b88219c9cb55dcdb729.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * ⚠️ Temporary failure when trying to retrieve information on issue `8259846`.

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2103/head:pull/2103`
`$ git checkout pull/2103`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by dcubed-ojdk** [comment]
@iwanowww - Thanks for the very fast review. I have a Tier1 running right now.

**Review by PaulSandoz — APPROVED** [review]
Java changes look good.

**Comment by dcubed-ojdk** [comment]
@PaulSandoz - thanks for the review.

**Comment by PaulSandoz** [comment]
@sviswa7 unfortunately the integration of https://github.com/openjdk/jdk/pull/1950 needed to be reverted due to failures in conversion tests. Some were timing out and some were crashing (on some older Mac hardware).

**Pull request closed without merging**
