### PR TITLE
8304547: Remove checking of -Djava.compiler in src/jdk.jdi/share/classes/com/sun/tools/jdi/SunCommandLineLauncher.java

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which removes the following outdated guard/check from SunCommandLineLauncher:

```
if ((options.indexOf("-Djava.compiler=") != -1) &&
    (options.toLowerCase().indexOf("-djava.compiler=none") == -1)) {
    throw new IllegalConnectorArgumentsException("Cannot debug with a JIT compiler",
                                                 ARG_OPTIONS);
}

```

Efforts are underway to remove the `java.compiler` system property entirely, besides that this test no longer makes sense since debugging with a JIT has been supported for a while.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304547](https://bugs.openjdk.org/browse/JDK-8304547): Remove checking of -Djava.compiler in src/jdk.jdi/share/classes/com/sun/tools/jdi/SunCommandLineLauncher.java

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13109/head:pull/13109` \
`$ git checkout pull/13109`

Update a local copy of the PR: \
`$ git checkout pull/13109` \
`$ git pull https://git.openjdk.org/jdk.git pull/13109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13109`

View PR using the GUI difftool: \
`$ git pr show -t 13109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13109.diff">https://git.openjdk.org/jdk/pull/13109.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good.

This was actually found years ago but the issue closed: [JDK-6374661](https://bugs.openjdk.org/browse/JDK-6374661)

**Review by plummercj — APPROVED** [review]

**Comment by plummercj** [comment]
Please make sure you run the jdk/com/sun/jdi tests and the jdb, jdwp, and jdi test under hotspot/jtreg/vmTestbase/nsk

**Comment by eirbjo** [comment]
> Please make sure you run the jdk/com/sun/jdi tests and the jdb, jdwp, and jdi test under hotspot/jtreg/vmTestbase/nsk

Tests passed:

```

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/com/sun/jdi                          177   177     0     0   
   jtreg:test/hotspot/jtreg/vmTestbase/nsk/jdi        1142  1142     0     0   
   jtreg:test/hotspot/jtreg/vmTestbase/nsk/jdb          67    67     0     0   
   jtreg:test/hotspot/jtreg/vmTestbase/nsk/jdwp        113   113     0     0   
==============================

```

**Pull request closed without merging**
