### PR TITLE
8283352: [CDS] SharedBaseAddress.java fails on x86_32

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all, 

Three cds tests fail on x86_32 due to incorrect VM testing parameters.
```
runtime/cds/appcds/SharedBaseAddress.java
runtime/cds/SharedBaseAddress.java#id1
runtime/cds/SharedBaseAddress.java#id0
```

Here is part of the failing log.
```
[STDERR]
Improperly specified VM option 'SharedBaseAddress=8g'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


[STDERR]
Improperly specified VM option 'SharedBaseAddress=0x800001000'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The fix just excludes them for 32-bit VMs.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283352](https://bugs.openjdk.java.net/browse/JDK-8283352): [CDS] SharedBaseAddress.java fails on x86_32

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to f4c74e8170c6dbba0439f199710dc723fd31c568
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7863/head:pull/7863` \
`$ git checkout pull/7863`

Update a local copy of the PR: \
`$ git checkout pull/7863` \
`$ git pull https://git.openjdk.java.net/jdk pull/7863/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7863`

View PR using the GUI difftool: \
`$ git pr show -t 7863`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7863.diff">https://git.openjdk.java.net/jdk/pull/7863.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable.

Thanks,
David

**Comment by iklam** [comment]
I think it's better to keep testing the 32-bit VM with values that are valid in 32-bit. How about splitting `testTable` into two parts: one for all builds, one for 64-bit platforms only?

**Comment by tstuefe** [comment]
> I think it's better to keep testing the 32-bit VM with values that are valid in 32-bit. How about splitting `testTable` into two parts: one for all builds, one for 64-bit platforms only?

Or, just ignore table entries < 4G.

**Comment by DamonFool** [comment]
> > I think it's better to keep testing the 32-bit VM with values that are valid in 32-bit. How about splitting `testTable` into two parts: one for all builds, one for 64-bit platforms only?
> 
> Or, just ignore table entries < (4G - whatever reasonable size we assume for the CDS archive, let's say 256M).
> 
> Update: on second thought, I like Iois idea more, of a table specially curated toward 32bit.

Thank you all for your review and comments.
Updated.
Thanks.

**Comment by iklam** [comment]
I think it would be better to do this. The code is easier to read and you can minimize the commit delta.

```
main() {
    test(testTable_32bit);
    if (is 64 bit vm) {
       test(testTable_64bit);
    }
}

static void test(String[] testTable) {
  // original code in main()....
}
```

**Comment by DamonFool** [comment]
> I think it would be better to do this. The code is easier to read and you can minimize the commit delta.
> 
> ```
> main() {
>     test(testTable_32bit);
>     if (is 64 bit vm) {
>        test(testTable_64bit);
>     }
> }
> 
> static void test(String[] testTable) {
>   // original code in main()....
> }
> ```

Good suggestion!
Updated.
Thanks.

**Review by iklam — APPROVED** [review]
Looks good. Thanks for making the changes.

**Review by tstuefe — APPROVED** [review]
Looks good!

**Comment by DamonFool** [comment]
Thank you all for the review and comments.
/integrate

**Pull request closed without merging**
