### PR TITLE
8303451: Synchronization entry in C2 debug info is misleading

### PR DESCRIPTION
**Pull request by quadhier**
This should fix [JDK-8303451](https://bugs.openjdk.org/browse/JDK-8303451).

It tries to correct some misleading code comments printed by `-XX:+PrintAssembly`.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303451](https://bugs.openjdk.org/browse/JDK-8303451): Synchronization entry in C2 debug info is misleading (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14192/head:pull/14192` \
`$ git checkout pull/14192`

Update a local copy of the PR: \
`$ git checkout pull/14192` \
`$ git pull https://git.openjdk.org/jdk.git pull/14192/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14192`

View PR using the GUI difftool: \
`$ git pr show -t 14192`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14192.diff">https://git.openjdk.org/jdk/pull/14192.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14192#issuecomment-1565557234)

### CODE REVIEW

**Comment by quadhier** [comment]
Hi @TobiHartmann , could you please review this change? Thanks in advance!

**Review by TobiHartmann — COMMENTED** [review]
Couldn't we detect if the method is synchronized and adjust the comment accordingly?

**Comment by TobiHartmann** [comment]
@dean-long also had some suggestions in [JDK-8201516](https://bugs.openjdk.org/browse/JDK-8201516) and might want to have a look.

**Comment by quadhier** [comment]
Hi, @TobiHartmann thanks for your advice. It seems that this PR should do more than a simple change of code comment. I will investigate it further.

**Pull request closed without merging**
