### PR TITLE
8274243: Implement fast-path for ASCII-compatible CharsetEncoders on aarch64

### PR DESCRIPTION
**Pull request by phedlin**
Implementation of ISO/ASCII char set encoding, extending current implementation with ASCII encoding support.

Implementation focusing on balance between small footprint and efficiency, trying to utilise a dual SIMD path (e.g. Neoverse N1) for the additional Ascii-check.

Testing: tier1-6

Benchmarks, 18-b26 vs. update (ran on Aurora/Ampere Altra):
```
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16384-type:ASCII..........72.23%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16384-type:BIG5...........70.38%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16384-type:ISO_8859_15....67.81%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16384-type:UTF_16......... 3.72%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16384-type:UTF_8..........68.50%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:2048-type:ASCII...........65.59%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:2048-type:BIG5............60.59%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:2048-type:ISO_8859_15.....63.79%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:2048-type:UTF_16.......... 1.04%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:2048-type:UTF_8...........63.33%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:512-type:ASCII............57.25%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:512-type:BIG5.............49.33%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:512-type:ISO_8859_15......61.37%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:512-type:UTF_16........... 0.02%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:512-type:UTF_8............54.75%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:255-type:ASCII............54.52%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:255-type:BIG5.............40.41%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:255-type:ISO_8859_15......58.46%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:255-type:UTF_16...........-0.55%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:255-type:UTF_8............55.98%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:127-type:ASCII............47.37%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:127-type:BIG5.............36.41%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:127-type:ISO_8859_15......50.83%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:127-type:UTF_16........... 8.63%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:127-type:UTF_8............48.95%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:31-type:ASCII.............17.55%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:31-type:BIG5..............18.58%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:31-type:ISO_8859_15.......20.82%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:31-type:UTF_16............ 4.16%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:31-type:UTF_8.............18.44%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16-type:ASCII.............21.96%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16-type:BIG5..............22.42%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16-type:ISO_8859_15.......30.27%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16-type:UTF_16............-1.17%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:16-type:UTF_8.............35.99%

openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:15-type:ASCII............. 6.19%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:15-type:BIG5.............. 7.34%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:15-type:ISO_8859_15....... 8.34%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:15-type:UTF_16............-0.46%
openjdk.bench.java.nio.CharsetEncodeDecode.encode-size:15-type:UTF_8............. 6.80%
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8274243](https://bugs.openjdk.java.net/browse/JDK-8274243): Implement fast-path for ASCII-compatible CharsetEncoders on aarch64

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6723/head:pull/6723` \
`$ git checkout pull/6723`

Update a local copy of the PR: \
`$ git checkout pull/6723` \
`$ git pull https://git.openjdk.java.net/jdk pull/6723/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6723`

View PR using the GUI difftool: \
`$ git pr show -t 6723`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6723.diff">https://git.openjdk.java.net/jdk/pull/6723.diff</a>

</details>

### CODE REVIEW

**Comment by phedlin** [comment]
```
Benchmark                                                      (charsetName)                          (message)  (timesToAppend)  Mode  Cnt    Score     Error  Units
EncoderBenchmarks.charsetEncoder                                       UTF-8     This is a simple ASCII message                3  avgt    4  144.807 ±   9.557  ns/op
EncoderBenchmarks.charsetEncoder                                       UTF-8  This is a message with unicode 😊                3  avgt    4  378.458 ± 206.193  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8     This is a simple ASCII message                3  avgt    4  200.844 ±  14.998  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8  This is a message with unicode 😊                3  avgt    4  356.589 ±   8.588  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8     This is a simple ASCII message                3  avgt    4  698.518 ±  17.269  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8  This is a message with unicode 😊                3  avgt    4  862.678 ±  30.872  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8     This is a simple ASCII message                3  avgt    4  109.413 ±   2.780  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8  This is a message with unicode 😊                3  avgt    4  522.050 ±  34.763  ns/op
```
**-XX:SoftwarePrefetchHintDistance=128**
```
Benchmark                                                      (charsetName)                          (message)  (timesToAppend)  Mode  Cnt    Score    Error  Units
EncoderBenchmarks.charsetEncoder                                       UTF-8     This is a simple ASCII message                3  avgt    4  144.519 ± 12.731  ns/op
EncoderBenchmarks.charsetEncoder                                       UTF-8  This is a message with unicode 😊                3  avgt    4  302.409 ± 51.020  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8     This is a simple ASCII message                3  avgt    4  201.144 ± 14.624  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8  This is a message with unicode 😊                3  avgt    4  469.724 ±  4.871  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8     This is a simple ASCII message                3  avgt    4  695.666 ± 22.061  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8  This is a message with unicode 😊                3  avgt    4  858.812 ± 22.913  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8     This is a simple ASCII message                3  avgt    4  109.598 ±  1.921  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8  This is a message with unicode 😊                3  avgt    4  511.589 ± 34.407  ns/op
```

**Comment by phedlin** [comment]
New implementation (disregards prefetch option).
```
Benchmark                                                      (charsetName)                          (message)  (timesToAppend)  Mode  Cnt    Score    Error  Units
EncoderBenchmarks.charsetEncoder                                       UTF-8     This is a simple ASCII message                3  avgt    4  116.916 ± 14.340  ns/op
EncoderBenchmarks.charsetEncoder                                       UTF-8  This is a message with unicode 😊                3  avgt    4  292.334 ± 10.038  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8     This is a simple ASCII message                3  avgt    4  178.490 ± 11.258  ns/op
EncoderBenchmarks.charsetEncoderWithAllocation                         UTF-8  This is a message with unicode 😊                3  avgt    4  363.741 ± 13.080  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8     This is a simple ASCII message                3  avgt    4  695.520 ± 20.217  ns/op
EncoderBenchmarks.charsetEncoderWithAllocationWrappingBuilder          UTF-8  This is a message with unicode 😊                3  avgt    4  862.785 ± 13.673  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8     This is a simple ASCII message                3  avgt    4  108.263 ±  6.123  ns/op
EncoderBenchmarks.toStringGetBytes                                     UTF-8  This is a message with unicode 😊                3  avgt    4  516.571 ± 22.347  ns/op
```

**Comment by cl4es** [comment]
Great to see this come along, thanks!

I can't review the code, but I think it'd be good to collect benchmark scores for `ISO-8859-1` before and after, along with absolute numbers so we see how things stack up against the existing ISO-8859-1-only intrinsic.

**Comment by phedlin** [comment]
The revised (bloated) version compares like this (master vs. update).
```
Benchmark                   (size)       (type)  Mode  Cnt    Score   Error  Units
CharsetEncodeDecode.encode   16384        UTF-8  avgt   30   17.920 ± 0.229  us/op
CharsetEncodeDecode.encode   16384         BIG5  avgt   30   18.867 ± 0.356  us/op
CharsetEncodeDecode.encode   16384  ISO-8859-15  avgt   30   17.419 ± 0.220  us/op
CharsetEncodeDecode.encode   16384   ISO-8859-1  avgt   30    6.200 ± 0.134  us/op
CharsetEncodeDecode.encode   16384        ASCII  avgt   30   17.149 ± 0.219  us/op
CharsetEncodeDecode.encode   16384       UTF-16  avgt   30  135.115 ± 1.440  us/op
```
```
Benchmark                   (size)       (type)  Mode  Cnt    Score   Error  Units
CharsetEncodeDecode.encode   16384        UTF-8  avgt   30    9.018 ± 0.179  us/op
CharsetEncodeDecode.encode   16384         BIG5  avgt   30   10.550 ± 0.470  us/op
CharsetEncodeDecode.encode   16384  ISO-8859-15  avgt   30    8.843 ± 0.187  us/op
CharsetEncodeDecode.encode   16384   ISO-8859-1  avgt   30    6.406 ± 0.155  us/op
CharsetEncodeDecode.encode   16384        ASCII  avgt   30    8.822 ± 0.173  us/op
CharsetEncodeDecode.encode   16384       UTF-16  avgt   30  135.195 ± 1.432  us/op
```

**Comment by phedlin** [comment]
New PR on JDK-18 repo.

https://github.com/openjdk/jdk18/pull/20

**Pull request closed without merging**
