### PR TITLE
JDK-8313790: [arm32] Specify -marm when building without an ABI profile

### PR DESCRIPTION
**Pull request by tstuefe**
See [JDK-8288719](https://bugs.openjdk.org/browse/JDK-8288719) and subsequent [discussion](https://mail.openjdk.org/pipermail/build-dev/2022-May/034635.html) back in 2022.

On Arm, we can generate either arm- or thumb-code (`-marm` or `-mthumb`). 

At the moment, if we don't specify an ABI profile (`--with_abi_profile`) when configuring the build, we call gcc without `-marm` or `-mthumb`. Then we use whatever the toolchain defaults too, which is pretty much random (it depends on how the toolchain itself had been built). That can cause really rare but tricky problems when combining static assembly and C++ code (See e.g. JDK-8288719).

I propose to always specify `-marm` as default, unless an ABI profile is given, to prevent such errors.

Thanks to @marchof for testing this.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313790](https://bugs.openjdk.org/browse/JDK-8313790): [arm32] Specify -marm when building without an ABI profile (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15162/head:pull/15162` \
`$ git checkout pull/15162`

Update a local copy of the PR: \
`$ git checkout pull/15162` \
`$ git pull https://git.openjdk.org/jdk.git pull/15162/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15162`

View PR using the GUI difftool: \
`$ git pr show -t 15162`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15162.diff">https://git.openjdk.org/jdk/pull/15162.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15162#issuecomment-1785646685)

### CODE REVIEW

**Comment by tstuefe** [comment]
os::attempt_reserve_memory_at() is used to map memory at a specific address that we fancy. It is not used to replace an existing mapping (hence we omit MAP_FIXED). 

But if there is an existing mapping, the kernel maps someplace else (and on Linux, this location is random). This is not what we want, therefore we unmap that address again. 

MAP_FIXED_NOREPLACE exists since Linux 4.17 and prevents an unnecessary cycle of mmap->munmap. Details see comment.

**Comment by tstuefe** [comment]
Thanks to @marchof for testing!

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
I thought `--with-abi-profile` was required when building on arm32. Would that not be a better fix to do?

**Comment by magicus** [comment]
(And even if we don't go that route, I think it would be better to have an "else" clause that sets the fallback value you propose here, rather than to set it once at the start and then overwrite it for almost all cases.)

**Pull request closed without merging**
