### PR TITLE
8307652: sealed class hierarchy graph doesn't distinguish non-sealed classes

### PR DESCRIPTION
**Pull request by liach**
`@sealedGraph` had a mechanism to render non-sealed classes differently, but it's useless because the graph nodes are not bordered. This patch converts the non-sealed classes to be rendered in italics instead.

An example of `ConstantDesc`, which has a sealed hierarchy except `DynamicConstantDesc`:
JDK 20:
image

This patch:
image

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307652](https://bugs.openjdk.org/browse/JDK-8307652): sealed class hierarchy graph doesn't distinguish non-sealed classes

### Reviewers
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - Committer)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13877/head:pull/13877` \
`$ git checkout pull/13877`

Update a local copy of the PR: \
`$ git checkout pull/13877` \
`$ git pull https://git.openjdk.org/jdk.git pull/13877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13877`

View PR using the GUI difftool: \
`$ git pr show -t 13877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13877.diff">https://git.openjdk.org/jdk/pull/13877.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13877#issuecomment-1539372530)

### CODE REVIEW

**Comment by jonathan-gibbons** [comment]
@minborg You should comment on this one.   

I'm not sure that italics by itself is a good idea.

**Comment by minborg** [comment]
Thanks for this improvement suggestion. Indicating "openness" is certainly important. I was playing around with various ways of expressing it and came up with this:

image

What is your opinion on it? It might be slightly more intuitive? We could even do this:

image



Here is the code:


```
digraph G {

 shape="none"
 rankdir = "BT"
 
 ClassDesc -> ConstantDesc
 MethodHandleDesc -> ConstantDesc
 DirectMethodHandleDesc -> MethodHandleDesc
 DynamicConstantDesc -> ConstantDesc
 Float -> ConstantDesc
 Hidden1 -> DynamicConstantDesc [style="dashed"]
 
 Hidden1 [label="<any>"]
 
  ClassDesc [shape=none];
  ConstantDesc [shape=none];
  MethodHandleDesc [shape=none];
  DynamicConstantDesc [shape=none];
  DirectMethodHandleDesc [shape=none];
  Float [shape=none];
  Hidden1 [shape=none];
}

```

**Review by minborg — APPROVED** [review]
These changes look very good. A significant improvement to the graph rendering.

**Comment by liach** [comment]
@jonathan-gibbons Can you take a look again at the revised version?

**Comment by jonathan-gibbons** [comment]
Given this is in a build-time taglet For JDK documentation, the use of `<any>` is acceptable and a reasonably good solution.

If this were to ever become a standard javadoc feature, we would maybe have to figure out how to localize the string, but that is not necessary here.

**Review by jonathan-gibbons — APPROVED** [review]
Generally, a good feature and a nice solution.

I endorse @minborg's approval.

**Pull request closed without merging**
