### PR TITLE
JDK-8318175 : AIX PPC64: Handle alignment of double in structs

### PR DESCRIPTION
**Pull request by suchismith1993**
1. use pragma directive to handle alignment.

JBS Issue: [JDK-8318175](https://bugs.openjdk.org/browse/JDK-8318175)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318175](https://bugs.openjdk.org/browse/JDK-8318175): AIX PPC64: Handle alignment of double in structs (**Sub-task** - P3)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16579/head:pull/16579` \
`$ git checkout pull/16579`

Update a local copy of the PR: \
`$ git checkout pull/16579` \
`$ git pull https://git.openjdk.org/jdk.git pull/16579/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16579`

View PR using the GUI difftool: \
`$ git pr show -t 16579`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16579.diff">https://git.openjdk.org/jdk/pull/16579.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16579#issuecomment-1810503510)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Looks good. I had proposed this solution here: https://github.com/openjdk/jdk/pull/16179#discussion_r1360709308

**Review by offamitkumar — APPROVED** [review]
LGTM

**Pull request closed without merging**
