### PR TITLE
8263549:  8263412 can cause jtreg testlibrary split

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review this dull patch that replaces `ClassFileInstaller` w/ `jdk.test.lib.helpers.ClassFileInstaller` in all jtreg test descriptions to ensure we won't get split testlibrary, and removes `jdk/test/lib/ClassFileInstaller.java` (so it won't be accidentally used).

from JBS:
> after JDK-8263412, we might (again) encounter NCDFE b/c parts of testlibraries aren't on the classpath. this happens when jtreg builds `jdk.test.lib.helpers.ClassFileInstaller` as a part of test-specific code, but `ClassFileInstaller` as part of shared testibrary directory in one test, when in the following test, jtreg sees `ClassFileInstaller` in the shared directory, hence javac won't recompile it/its dependencies, but in runtime `jdk.test.lib.helpers.ClassFileInstaller` is nowhere to be found, hence we get NCDFE. 

testing:
- [x]  `grep ' ClassFileInstaller[^.]`
- [ ] tier1-3

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263549](https://bugs.openjdk.java.net/browse/JDK-8263549):  8263412 can cause jtreg testlibrary split

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to 6e53ad97ff3c76ff1a7bf3a3772aaa264aa54e4b
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2985/head:pull/2985`
`$ git checkout pull/2985`

### CODE REVIEW

**Comment by iignatev** [comment]
note for reviewers: the big part of the patch is just `sed -i  's/ ClassFileInstaller / jdk.test.lib.helpers.ClassFileInstaller /g'`

**Review by iklam — APPROVED** [review]
I did this and scanned the differences (with the diff file from the webrev) and it looks reasonable to me.

```
grep '^[+-]' diff.txt | grep -v Copyright | grep -v '^.[+-]' | less
```

It looks like most of the changes are mechanical. There were only a few cases where manual changes were made. I trusted that you have tested those cases individually.

But I don't understand why this error can happen. It seems like jtreg would allow two test cases to interfere with each other.

**Comment by iignatev** [comment]
Hi Ioi,

thanks for review this, I ran the whole tier1-3 jobs which should provide enough coverage. as oracle builds don't have AOT feature enabled, I missed a compilation error in `IncorrectAOTLibraryTest` test. the test failed in GitHub action and should be fixed by [3a3b7a8](https://github.com/openjdk/jdk/pull/2985/commits/3a3b7a846289181b466b3c1eb478a0a571d9468b),

-- Igor

**Comment by iklam** [comment]
> But I don't understand why this error can happen. It seems like jtreg would allow two test cases to interfere with each other.

The root cause seems to be https://bugs.openjdk.java.net/browse/CODETOOLS-7902847

**Review by dcubed-ojdk — APPROVED** [review]
I downloaded the patch and used Ioi's cmd pattern to scroll through
the changes. I can't honestly say that I looked at every line since 867
changed files would overwhelm anyone's brain...

I did notice a couple of `@run main` instead of `@run driver` calls
to the ClassFileInstaller, but those are pre-existing.

Thumbs up.

**Comment by iignatev** [comment]
Hi Dan,

Thanks for your review!

> I did notice a couple of @run main instead of @run driver calls to the ClassFileInstaller, but those are pre-existing.
I noticed this too, planning to fix that with a separate RFE.

-- Igor

**Pull request closed without merging**
