### PR TITLE
8304687: Move add_to_hierarchy

### PR DESCRIPTION
**Pull request by coleenp**
Moved SystemDictionary::add_to_hierarchy to InstanceKlass::add_to_hierarchy where it more logically belongs and next to other functions that also care about dependencies.
Tested with tier1-4, and tier1 on linux,windows,macos to check header file changes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304687](https://bugs.openjdk.org/browse/JDK-8304687): Move add_to_hierarchy

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13129/head:pull/13129` \
`$ git checkout pull/13129`

Update a local copy of the PR: \
`$ git checkout pull/13129` \
`$ git pull https://git.openjdk.org/jdk.git pull/13129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13129`

View PR using the GUI difftool: \
`$ git pr show -t 13129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13129.diff">https://git.openjdk.org/jdk/pull/13129.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Refactoring looks fine.

Thanks.

**Review by dholmes-ora — APPROVED** [review]
Still good.

**Review by fparain — APPROVED** [review]
LGTM

**Comment by coleenp** [comment]
Thanks David and Fred.
/integrate

**Pull request closed without merging**
