### PR TITLE
8242559: Clean the "libawt_xawt" library from code for headless mode

### PR DESCRIPTION
**Pull request by mrserb**
This bug extracted from JDK-8240290[1]

The libawt_xawt.so library is used by the headful toolkit, but it still
has some code related to the headless mode, which could be deleted.

In the fix, the HEADLESS related code was removed, to prove that we did
not build this library in HEADLESS mode, I added "#error This " to all
library files(but some of them already has it)

[1] https://bugs.openjdk.java.net/browse/JDK-8240290

The old review request:
https://mail.openjdk.java.net/pipermail/awt-dev/2020-April/015881.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (hs/tier1 compiler)](https://github.com/mrserb/jdk/runs/1290401911)

### Issue
 * [JDK-8242559](https://bugs.openjdk.java.net/browse/JDK-8242559): Clean the "libawt_xawt" library from code for headless mode

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**) ⚠️ Review applies to 10c83cdcba1c297791e59c5653cb9504cb2da7be

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/101/head:pull/101`
`$ git checkout pull/101`

### CODE REVIEW

**Review by prrace — COMMENTED** [review]
Clearly these are there to prevent mistakes. So they add value at a tiny build time cost.
I don't see the point of removing them.

**Comment by mrserb** [comment]
> Clearly these are there to prevent mistakes. So they add value at a tiny build time cost.
> I don't see the point of removing them.

That's the point of the fix, instead of implementing two versions of each method in these files just prevent compilation of the file in the headless mode. As far as understand both solutions are equivalent, but an assertion at the start of the file a much cleaner.

**Comment by magicus** [comment]
I agree with Sergey. This is much cleaner. All steps towards cleaning up the spaghetti code regarding headless/not headless are important, even if they are small. It's like solving the thousand paper cuts issue; you have to address every individual cut, not matter how miniscule.

**Review by azuev-java — APPROVED** [review]

**Pull request closed without merging**
