### PR TITLE
JDK-8321599 Data loss in AVX3 Base64 decoding

### PR DESCRIPTION
**Pull request by asgibbons**
Fix for looking for padding characters within the encoded string.  Was not adding start offset to length, so was looking at potentially freed or uninitialized memory.

Tested teir1 and with testcase supplied with JBS issue.

The problem will only occur when all of the following are true:
1. The source offset of the string to be decoded is != 0.
2. The characters at the beginning of the string (minus the offset) plus the string length mod 64 are either "=" or "==".
3. The string is >= 32 characters.
4. The string is not MIME encoded.

If any of these conditions are not met, the decode works as expected. This was due to omitting the source offset of the string when checking for padding characters.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321599](https://bugs.openjdk.org/browse/JDK-8321599): Data loss in AVX3 Base64 decoding (**Bug** - P2)

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to [ba60ac59](https://git.openjdk.org/jdk/pull/17039/files/ba60ac59b27ad13b5c13ac5fc99ef003b4832f45)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [ba60ac59](https://git.openjdk.org/jdk/pull/17039/files/ba60ac59b27ad13b5c13ac5fc99ef003b4832f45)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17039/head:pull/17039` \
`$ git checkout pull/17039`

Update a local copy of the PR: \
`$ git checkout pull/17039` \
`$ git pull https://git.openjdk.org/jdk.git pull/17039/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17039`

View PR using the GUI difftool: \
`$ git pr show -t 17039`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17039.diff">https://git.openjdk.org/jdk/pull/17039.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17039#issuecomment-1847839362)

### CODE REVIEW

**Comment by eastig** [comment]
@asgibbons, am I correct the problem is that padding '=' characters were not found and not processed. This happens because a source offset is not taken into account.
A test is:
```
A, B: String
Buf: ByteBuffer
C := base64_encode(A) + base64_encode(B) # encode(B) should have '=' or '=='
put C in Buf
A' := base64_decode(Buf)
B' := base64_decode(Buf)
assert(A.equals(A'))
assert(B.equals(B'))
```

**Comment by asgibbons** [comment]
> @asgibbons, am I correct the problem is that padding '=' characters were not found and not processed. This happens because a source offset is not taken into account. A test is:
> 
> ```
> A, B: String
> Buf: ByteBuffer
> C := base64_encode(A) + base64_encode(B) # encode(B) should have '=' or '=='
> put C in Buf
> A' := base64_decode(Buf)
> B' := base64_decode(Buf)
> assert(A.equals(A'))
> assert(B.equals(B'))
> ```

No.  The padding '=' character was found and terminated the decoding, which is expected.  The issue is that the input string (encoded) is quite long in this case and the test is decoding a substring of the full string.  The parameters passed to Decode are a pointer to the start of the (long) string and a (large) offset.  I was looking for padding characters relative to the start of the long string instead of the substring (start plus the starting offset).  Example:

```
Encoded string:
. . . = = . . . a a a a a a a ... a a a a
^               ^
|               |
start          start + offset
```
I was asked to decode the bytes at ```(start + offset)```.  When the algorithm gets to the last 31 bytes of ```a a a a ... a a a a```, it looks for padding at ```(start + remaining_length - 1)``` instead of ```(start + start_offset + remaining_length - 1)```.  It actually found a padding byte at ```(start + remaining_length - 1)``` and decided that the output length should be reduced by one character (or 2 if there were 2 padding bytes found).  A very specific edge case (so good catch by testers).

**Comment by pettyjamesm** [comment]
I was one of the engineers investigating the issue and wrote the original form of reproducer submitted on the ticket. The use case that was failing that I tried to mimic in the reproducer was decoding base64 data in a column oriented analytics engine- so the fact that the backing buffer is (much) larger than the subset being decoded on any invocation, has non zero starting offsets, and contains padded base64 strings earlier in the source buffer isn’t an exceptional use case. Thanks again for the quick fix!

**Comment by vnkozlov** [comment]
@pettyjamesm did you verified this fix with your case?

**Comment by pettyjamesm** [comment]
> @pettyjamesm did you verified this fix with your case?

Unfortunately not, we don’t currently have any workflow that builds a test artifact from JDK source- so it would be a big lift to get to that point for us.

**Comment by vnkozlov** [comment]
> @asgibbons, thank you for the quick fix.
> I think it's worth to add the reproducer for the JBS issue as a test.

Yes, we need regression test with this changes.

**Comment by asgibbons** [comment]
Closing this PR by @TobiHartmann request.

**Comment by asgibbons** [comment]
Security issue has been resolved.  Re-opening.

**Comment by sviswa7** [comment]
The fix looks good to me. Could you please update the copyright year in TestBase64.java?

**Review by sviswa7 — APPROVED** [review]

**Comment by sviswa7** [comment]
@vnkozlov Please advice if we can go ahead and integrate this fix.

**Review by vnkozlov — APPROVED** [review]
Looks reasonable. Please, update copyright year to 2024 in source file and test.

**Comment by vnkozlov** [comment]
Good.

**Comment by sviswa7** [comment]
Thanks a lot @vnkozlov.

**Pull request closed without merging**
