### PR TITLE
8332533: RISC-V: Enable vector variable shift instructions for machines with RVV

### PR DESCRIPTION
**Pull request by zifeihan**
Hi, I noticed the following warning in the Opto JIT Code for the Vector API in the `test/jdk/jdk/incubator/vector/Byte256VectorTests.java: ASHRByte256VectorTests` test:
```
--------------------------------------------------------------------------------
  ** Rejected vector op (RShiftVB,byte,32) because architecture does not support variable vector shifts
  ** not supported: arity=2 opc=405 vlen=32 etype=byte ismask=0 is_masked_op=0
``` 
the reason is because Matcher::supports_vector_ variable_shifts returns false. the port of RISC-V Vector API now supports the vector shifts, so this should return with UseRVV.  By the Way, the Matcher::supports_vector_variable_shifts function was introduced by Vector API, and I think forgot to modify the Matcher::supports_vector_variable_shifts function when implementing vector shift.
After the fix, the test passes normally and generates the Opto JIT Code such as:
```
1c2     loadV V1, [R7]  # vector (rvv)
1ca     lwu  R28, [R28, #12]    # loadN, compressed ptr, #@loadN ! Field: jdk/internal/vm/vector/VectorSupport$VectorPayload.payload (constant)
1ce     decode_heap_oop  R7, R28    #@decodeHeapOop
1d2     addi  R7, R7, #16   # ptr, #@addP_reg_imm
1d4     loadV V2, [R7]  # vector (rvv)
1dc     vand_immI V1, V1, #7
1e4     spill [sp, #48] -&gt; R7    # spill size = 32
1e6     # castII of R7, #@castII
1e6     vasrB V3, V2, V1
1fa     spill [sp, #96] -&gt; R29   # spill size = 32
1fc     bgeu  R7, R29, B101 #@cmpU_branch  P=0.000001 C=-1.000000
```

### Testing:
qemu 8.1.50 with UseRVV:
- [x] Run tier1-3 tests (release)
- [x] Run test/jdk/jdk/incubator/vector (fastdebug)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332533](https://bugs.openjdk.org/browse/JDK-8332533): RISC-V: Enable vector variable shift instructions for machines with RVV (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [546c255a](https://git.openjdk.org/jdk/pull/19313/files/546c255abdcab50e281efe2d5f466f077e17cf99)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19313/head:pull/19313` \
`$ git checkout pull/19313`

Update a local copy of the PR: \
`$ git checkout pull/19313` \
`$ git pull https://git.openjdk.org/jdk.git pull/19313/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19313`

View PR using the GUI difftool: \
`$ git pr show -t 19313`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19313.diff">https://git.openjdk.org/jdk/pull/19313.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19313#issuecomment-2121569073)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good. Thanks.

**Comment by Hamlin-Li** [comment]
Is `UseRVV ` a const? Seems you need to remove `constexpr`.
Or you can just return true (so, keep constexpr), as `supports_vector_variable_shifts` is not a independent check, and it's protected by `Matcher::match_rule_supported_vector` in both vector api and auto-vectorization.

**Comment by zifeihan** [comment]
> Is `UseRVV ` a const? Seems you need to remove `constexpr`. Or you can just return true (so, keep constexpr), as `supports_vector_variable_shifts` is not a independent check, and it's protected by `Matcher::match_rule_supported_vector` in both vector api and auto-vectorization.

Thanks for your review. I've removed `constexpr`.

**Comment by zifeihan** [comment]
@RealFYang @Hamlin-Li : Thanks for the review.
/integrate

**Pull request closed without merging**
