### PR TITLE
8283684: IGV: speed up filter application

### PR DESCRIPTION
**Pull request by robcasloz**
This change improves view creation time by creating a single JavaScript engine shared among all filters, rather than creating an engine every time a filter is applied. Since creating a JavaScript engine is a costly operation, this change speeds up view creation substantially for small and medium-sized graphs as soon as any filter is applied. This includes the default IGV configuration, where the "Color by category" filter is enabled.

##### Functionality

- Tested manually applying different filter subsets and differing on a small selection of graphs, for JDK 11 and 17 (which use different versions and ways of packaging the JavaScript engine).

- Tested automatically viewing thousands of graphs with different subsets of filters enabled (by instrumenting IGV to view graphs as they are loaded and running `java -Xcomp -XX:-TieredCompilation -XX:PrintIdealGraphLevel=4`).

##### Performance

Measured the view creation time for the default sea-of-nodes view on a selection of 94 medium-sized graphs (200-493 nodes) for different subsets of filters. Before the change, the view creating time increases roughly linearly with the number of applied filters (since an engine is created for each filter application). After the change, the view creating time remains roughly constant (even slightly decreasing) as the number of applied filters increases, yielding an average speedup of 2.4x for the default IGV configuration, and up to 8.2x when five filters are applied. The speedup is expected to diminish for larger graphs where engine creation does not dominate view creation time. The complete results are [attached](https://github.com/openjdk/jdk/files/8396784/performance-evaluation.ods) (note that each measurement in the sheet corresponds to the median of ten runs).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283684](https://bugs.openjdk.java.net/browse/JDK-8283684): IGV: speed up filter application

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8073/head:pull/8073` \
`$ git checkout pull/8073`

Update a local copy of the PR: \
`$ git checkout pull/8073` \
`$ git pull https://git.openjdk.java.net/jdk pull/8073/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8073`

View PR using the GUI difftool: \
`$ git pr show -t 8073`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8073.diff">https://git.openjdk.java.net/jdk/pull/8073.diff</a>

</details>

### CODE REVIEW

**Comment by robcasloz** [comment]
Anyone willing to review this?

**Comment by robcasloz** [comment]
> Looks good.

Thanks, Tobias!

**Review by vnkozlov — APPROVED** [review]
good

**Comment by robcasloz** [comment]
> good

Thanks for reviewing, Vladimir!

**Pull request closed without merging**
