### PR TITLE
8343123: Nimbus: javax/swing/JInternalFrame/bug6726866.java does not have green undecorated window

### PR DESCRIPTION
**Pull request by prsadhuk**
Test fails in NimbusL&F as DesktopPane does not have green background as set by the user, which is because, the auto-generated [DesktopPanePainter class](https://github.com/openjdk/jdk/blob/eb40a88f4076360708402454a494907e8c0c845d/src/java.desktop/share/classes/javax/swing/plaf/nimbus/SynthPainterImpl.java#L100-L102) which has pre-coded color values does not honour user-defined color.

Fix is to make sure user-defined DesktopPane background color is honoured and is painted and only auto-generated class for L&F derived colors.
CI is ok..

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343123](https://bugs.openjdk.org/browse/JDK-8343123): Nimbus: javax/swing/JInternalFrame/bug6726866.java does not have green undecorated window (**Bug** - P4)

### Reviewers
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - **Reviewer**)
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22057/head:pull/22057` \
`$ git checkout pull/22057`

Update a local copy of the PR: \
`$ git checkout pull/22057` \
`$ git pull https://git.openjdk.org/jdk.git pull/22057/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22057`

View PR using the GUI difftool: \
`$ git pr show -t 22057`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22057.diff">https://git.openjdk.org/jdk/pull/22057.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22057#issuecomment-2472252777)
</details>

### CODE REVIEW

**Review by TejeshR13 — COMMENTED** [review]
Please update `SynthPainterImpl` file copywrite year.

**Review by TejeshR13 — APPROVED** [review]
I have tested the fix and is working as expected. LGTM.

**Review by DamonGuy — APPROVED** [review]
Tested this myself as well. It makes me wonder why the original implementation of this didn't work as expected and why checking for an instance of a UIResource is now needed. Works as expected now.

**Comment by prsadhuk** [comment]
If it's L&F set color, which is the case in auto-generated DesktopPainter class, then it will be an instance of UIResource so the fix delegates the painting to that auto-generated class but if background is set by user (as is the case in this testcase) then it will be an instance of Color and not UIResource so we are not delegating to the auto-generated class and do the painting in SynthDesktopPaneUI#update which is called after DesktopPainter class call..

**Pull request closed without merging**
