### PR TITLE
8324334: Shenandoah: Improve end of process report

### PR DESCRIPTION
**Pull request by earthling-amzn**
Shenandoah emits a summary of collector statistics when the JVM process exits normally. These statistics do not include the number of cycles which did not require evacuation (we call these abbreviated or short-cut cycles).

The end-of-process report should include these shortcut cycles and also show the outcomes of various cycles as a percentage of the total number of cycles. This change also removes some unused variables/methods and has the heuristic lean on the collector policy for tracking consecutive degenerated cycles (rather than having both the heuristic and the collector policy tracking this).

Here is an example of the improved report:
```
    20 Completed GCs
     5 Successful Concurrent GCs (25.00%)
       2 invoked explicitly (40.00%)
       0 invoked implicitly (0.00%)
       1 abbreviated (20.00%)
    13 Degenerated GCs (65.00%)
       3 upgraded to Full GC (23.08%)
      13 caused by allocation failure (100.00%)
       0 abbreviated (0.00%)
        10 happened at Mark
         3 happened at Update References
     5 Full GCs (25.00%)
       0 invoked explicitly (0.00%)
       0 invoked implicitly (0.00%)
       2 caused by allocation failure (40.00%)
       3 upgraded from Degenerated GC (60.00%)
```

In addition to GHA testing, these changes have been tested on Dacapo, Extremem, SpecJBB2015, SpecJVM2008, Heapothesys and Diluvian.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324334](https://bugs.openjdk.org/browse/JDK-8324334): Shenandoah: Improve end of process report (**Task** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - no project role) ⚠️ Review applies to [66bca0f3](https://git.openjdk.org/jdk/pull/17521/files/66bca0f32a1addb28f04b1acb21ddebfcc1cf86e)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**) ⚠️ Review applies to [66bca0f3](https://git.openjdk.org/jdk/pull/17521/files/66bca0f32a1addb28f04b1acb21ddebfcc1cf86e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17521/head:pull/17521` \
`$ git checkout pull/17521`

Update a local copy of the PR: \
`$ git checkout pull/17521` \
`$ git pull https://git.openjdk.org/jdk.git pull/17521/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17521`

View PR using the GUI difftool: \
`$ git pr show -t 17521`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17521.diff">https://git.openjdk.org/jdk/pull/17521.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17521#issuecomment-1904781501)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Thanks for preparing this.

**Comment by earthling-amzn** [comment]
The copyright update anticipates the changes to this file on the generational mode branch. I will revert it here. I will also add comments to the methods of the collector policy.

**Pull request closed without merging**
