### PR TITLE
8313760: [REDO] Enhance AES performance

### PR DESCRIPTION
**Pull request by chhagedorn**
This reapplies JDK-8308682 (i.e. reverse the backout done with [JDK-8313756](https://bugs.openjdk.org/browse/JDK-8313756)) but attributes it correctly to @theRealAph together with @adinn and @sviswa7 as additional reviewers.

The redo applied cleanly.

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313760](https://bugs.openjdk.org/browse/JDK-8313760): [REDO] Enhance AES performance (**Bug** - P2)

### Reviewers
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) - **Reviewer** ⚠️ Added manually
 * [Dean Long](https://openjdk.org/census#dlong) - **Reviewer** ⚠️ Added manually

### Contributors
 * Andrew Haley `<aph@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15267/head:pull/15267` \
`$ git checkout pull/15267`

Update a local copy of the PR: \
`$ git checkout pull/15267` \
`$ git pull https://git.openjdk.org/jdk.git pull/15267/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15267`

View PR using the GUI difftool: \
`$ git pr show -t 15267`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15267.diff">https://git.openjdk.org/jdk/pull/15267.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15267#issuecomment-1677264011)

### CODE REVIEW

**Review by adinn — COMMENTED** [review]
These changes look fine, thanks!

**Comment by chhagedorn** [comment]
Thanks @adinn! I think you additionally need to approve it since the bot does not accept only manually added reviewers.

**Review by theRealAph — APPROVED** [review]
Thank you.

**Comment by chhagedorn** [comment]
Thanks @theRealAph for your review!

For some reason, @adinn was removed again as reviewer by the bot. I'll add him again.

**Comment by chhagedorn** [comment]
> @chhagedorn Reviewer `adinn` has already made an authenticated review of this PR, and does not need to be credited manually.

@adinn I'm not sure why it says that but does not list you above. Maybe you need to explicitly approve the PR again to appear in the reviewer list again.

**Comment by kevinrushforth** [comment]
>> Reviewer adinn has already made an authenticated review of this PR, and does not need to be credited manually.
>
> @adinn I'm not sure why it says that but does not list you above. Maybe you need to explicitly approve the PR again to appear in the reviewer list again.

Yes, GitHub now sees @adinn as having reviewed, but without approving it, so Skara will not allow him to be added manually. If he reviews / approves, he will then be listed.

**Comment by chhagedorn** [comment]
Thanks @kevinrushforth for the explanation!

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Review by rhalade — APPROVED** [review]

**Review by adinn — APPROVED** [review]

**Comment by theRealAph** [comment]
It's come through as co-authored-by instead of authored-by, which is wrong because I wrote every single byte, but never mind.

**Pull request closed without merging**
