### PR TITLE
8276825: hotspot/runtime/SelectionResolution test errors

### PR DESCRIPTION
**Pull request by hseigel**
Please review this trivial fix to a few of the hotspot/runtime/SelectionResolution test class files.  The fix was tested by running the tests locally and Mach5 tiers 1-3 on Linux, MacOS, and Windows.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276825](https://bugs.openjdk.java.net/browse/JDK-8276825): hotspot/runtime/SelectionResolution test errors

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to f3ab41028ce2c999b1a92bab43d7c014877f787f

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6300/head:pull/6300` \
`$ git checkout pull/6300`

Update a local copy of the PR: \
`$ git checkout pull/6300` \
`$ git pull https://git.openjdk.java.net/jdk pull/6300/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6300`

View PR using the GUI difftool: \
`$ git pr show -t 6300`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6300.diff">https://git.openjdk.java.net/jdk/pull/6300.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Harold,

The fix looks good but I'm unclear about the exact circumstances here. Were these tests failing? If so were they excluded somehow? Or were these still passing by accident - which indicates a bigger problem with the test?

Thanks,
David

**Review by shipilev — APPROVED** [review]
Looks fine to me.

**Comment by hseigel** [comment]
Thanks David and Aleksey for the reviews.

The tests passed by accident.  The calls to the Clazz constructor happen to succeed because the constructor adds ACC_SUPER to the incoming access.  When the access is -1, this results in access being set to 31 because ACC_SUPER equals 32.

I changed the Clazz cosntructor java to 'or' the incoming access with ACC_SUPER instead of adding it.  This will prevent the test from succeeding in the future if an index of -1 is passsed as the access.

Does this latest change look okay?

**Comment by dholmes-ora** [comment]
So does that mean we check access by AND'ing with a mask ie 

```bool is_public = access_bits & ACC_PUBLIC != 0```

So access bits of 31 are the same as 1 from an access check perspective?

**Review by dholmes-ora — APPROVED** [review]
Changes seem fine.

Thanks,
David

**Comment by hseigel** [comment]
Thanks David!

/integrate

**Comment by hseigel** [comment]
Hi David,

The access checks are done by AND'ing.  Here's an example from 
classFileParser.cpp:

    void ClassFileParser::verify_legal_field_modifiers(jint flags, bool
    is_interface, TRAPS) const {
                             ...
       const bool is_public    = (flags & JVM_ACC_PUBLIC)    != 0;
       const bool is_protected = (flags & JVM_ACC_PROTECTED) != 0;

So, for example, access bits of both 31 and 1 indicate that 
JVM_ACC_PUBLIC is set.

Harold

**Pull request closed without merging**
