### PR TITLE
JDK-8154011: Make TraceDeoptimization a diagnostic flag

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Make TraceDeoptimization available in a product build.

I checked that performance is not affected on Aurora.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8154011](https://bugs.openjdk.java.net/browse/JDK-8154011): Make TraceDeoptimization a diagnostic flag

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6703/head:pull/6703` \
`$ git checkout pull/6703`

Update a local copy of the PR: \
`$ git checkout pull/6703` \
`$ git pull https://git.openjdk.java.net/jdk pull/6703/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6703`

View PR using the GUI difftool: \
`$ git pr show -t 6703`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6703.diff">https://git.openjdk.java.net/jdk/pull/6703.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by dholmes-ora — APPROVED** [review]
Change looks fine, though as I mention in JBS maybe this could be converted to unified logging?

Cheers,
David

**Review by TobiHartmann — APPROVED** [review]
Looks good to me and as discussed in JIRA, this can't be easily converted to UL.

**Comment by dougxc** [comment]
Sorry for only bringing it up now, but @tkrodriguez just observed that several of the places that test `TraceDeoptimization` aren't included in a `PRODUCT` build. In particular, [here](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/vframeArray.cpp#L443), [here](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/deoptimization.cpp#L265), and [here](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/deoptimization.cpp#L731).

**Comment by vnkozlov** [comment]
@tobiasholenstein please file follow up bug and fix places pointed by Doug.
Also make sure run testing to find and fix affected tests.

**Comment by tkrodriguez** [comment]
Some of those might be benign, thought they are inconsistent.  The DEOPT PACKING messages are controlled by PrintDeoptimizationDetails, but DEOPT UNPACKING is controlled by TraceDeoptimization.  The REALLOC messages could likely be under PrintDeoptimizationDetails.  Maybe it would make sense to rationalize them a bit and make PrintDeoptimizationDetails diagnostic as well.

**Comment by tobiasholenstein** [comment]
Thanks for catching that! I filed a Bug on JIRA (JDK-8278329)

**Pull request closed without merging**
