### PR TITLE
8322962: Upcall stub might go undetected when freezing frames

### PR DESCRIPTION
**Pull request by pchilano**
Please review this simple fix. There is a missing push_cont_fastpath()/pop_cont_fastpath() around the call to Java in the upcall stub. Because of this, if from that upcall a virtual thread tries to yield, and all the other methods in the stack are compiled, we will incorrectly take the freeze fast path and freeze everything in the stack including the native frames. By forcing the slow path instead we will identify the upcall stub and pin the vthread.

The issue can be easily reproduced by running the modified version of test GetStackTraceALotWhenPinned.java included in this patch. I also tested the fix by running tiers1-3 in mach5. 

Thanks,
Patricio

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322962](https://bugs.openjdk.org/browse/JDK-8322962): Upcall stub might go undetected when freezing frames (**Bug** - P4)

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**) ⚠️ Review applies to [5404cf02](https://git.openjdk.org/jdk/pull/17964/files/5404cf0283ce00293159478510036326f0130102)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [5404cf02](https://git.openjdk.org/jdk/pull/17964/files/5404cf0283ce00293159478510036326f0130102)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to [5404cf02](https://git.openjdk.org/jdk/pull/17964/files/5404cf0283ce00293159478510036326f0130102)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [5404cf02](https://git.openjdk.org/jdk/pull/17964/files/5404cf0283ce00293159478510036326f0130102)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17964/head:pull/17964` \
`$ git checkout pull/17964`

Update a local copy of the PR: \
`$ git checkout pull/17964` \
`$ git pull https://git.openjdk.org/jdk.git pull/17964/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17964`

View PR using the GUI difftool: \
`$ git pr show -t 17964`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17964.diff">https://git.openjdk.org/jdk/pull/17964.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17964#issuecomment-1959600585)

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
x64 and aarch64 code look good to me. push/pop_cont_fastpath don't modify the register state or the stack ptr. (it looks like 32-bit x86 will use the fallback linker for now, so I'm not worried about that).

**Review by AlanBateman — APPROVED** [review]
x64 and aarch64 changes looks right to me.

**Comment by pchilano** [comment]
Could I get a review from @TheRealMDoerr and @RealFYang for the ppc and risc-v changes?

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Test is passing on linux PPC64le.

**Review by RealFYang — APPROVED** [review]
LGTM. Test passed with or without -Xcomp flag on linux-riscv64 platform.

**Comment by dean-long** [comment]
Is there a way to automatically detect missing calls to push_cont_fastpath?

**Comment by pchilano** [comment]
Thanks for the reviews @TheRealMDoerr and @RealFYang.

**Comment by pchilano** [comment]
> Is there a way to automatically detect missing calls to push_cont_fastpath?
>
There is a check at the beginning of freeze that we don't have interpreter or native frames if we take the fast path. This missed that we can also go from native->Java using the Panama API rather than JNI. But I changed that check now to explicitly verify that all frames in the stack are compiled. Please take a look.

**Review by dean-long — APPROVED** [review]
Looks good!

**Comment by pchilano** [comment]
> Looks good!
>
Thanks for the review Dean!

**Pull request closed without merging**
