### PR TITLE
JDK-8283416: Update java.lang.invoke.MethodHandle to use sealed classes

### PR DESCRIPTION
**Pull request by jddarcy**
Small refactoring to use sealed classes in the MethodHandle implementation hierarchy.

DelegatingMethodHandle is non-sealed rather than sealed since it has two subclasses, one defined as a nested class and only a separate type in the same package. The permits clause does not allow listed those two kinds of subclasses.

Please also review the corresponding CSR https://bugs.openjdk.java.net/browse/JDK-8283434

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8283416](https://bugs.openjdk.java.net/browse/JDK-8283416): Update java.lang.invoke.MethodHandle to use sealed classes
 * [JDK-8283434](https://bugs.openjdk.java.net/browse/JDK-8283434): Update java.lang.invoke.MethodHandle to use sealed classes (**CSR**)

### Reviewers
 * [Athijegannathan Sundararajan](https://openjdk.java.net/census#sundar) (@sundararajana - **Reviewer**) ⚠️ Review applies to f4f794116c9c393228954b65bd2290a0bd916d06
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7881/head:pull/7881` \
`$ git checkout pull/7881`

Update a local copy of the PR: \
`$ git checkout pull/7881` \
`$ git pull https://git.openjdk.java.net/jdk pull/7881/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7881`

View PR using the GUI difftool: \
`$ git pr show -t 7881`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7881.diff">https://git.openjdk.java.net/jdk/pull/7881.diff</a>

</details>

### CODE REVIEW

**Comment by sundararajana** [comment]
"DelegatingMethodHandle is non-sealed rather than sealed since it has two subclasses, one defined as a nested class and only a separate type in the same package. The permits clause does not allow listed those two kinds of subclasses."

We can have a permits clause that lists fully qualified class name for the nested class and simple name for that separate type in the same package, right?

Also

$ cd $jdk_src/src/java.base/share/classes/java/lang/invoke
$ grep "extends DelegatingMethodHandle" *
MethodHandleImpl.java:    private static final class AsVarargsCollector extends DelegatingMethodHandle {
MethodHandleImpl.java:    static class CountingWrapper extends DelegatingMethodHandle {
MethodHandleImpl.java:    private static final class WrappedMember extends DelegatingMethodHandle {
MethodHandleImpl.java:    static final class IntrinsicMethodHandle extends DelegatingMethodHandle 

All 4 are nested classes. Two of those subclasses are nested "private" in another class and hence cannot be referred from DelegatingMethodHandle's permits clause, right?

**Comment by jddarcy** [comment]
> "DelegatingMethodHandle is non-sealed rather than sealed since it has two subclasses, one defined as a nested class and only a separate type in the same package. The permits clause does not allow listed those two kinds of subclasses."
> 
> We can have a permits clause that lists fully qualified class name for the nested class and simple name for that separate type in the same package, right?
> 
> Also
> 
> $ cd $jdk_src/src/java.base/share/classes/java/lang/invoke $ grep "extends DelegatingMethodHandle" * MethodHandleImpl.java: private static final class AsVarargsCollector extends DelegatingMethodHandle { MethodHandleImpl.java: static class CountingWrapper extends DelegatingMethodHandle { MethodHandleImpl.java: private static final class WrappedMember extends DelegatingMethodHandle { MethodHandleImpl.java: static final class IntrinsicMethodHandle extends DelegatingMethodHandle
> 
> All 4 are nested classes. Two of those subclasses are nested "private" in another class and hence cannot be referred from DelegatingMethodHandle's permits clause, right?

I did try to name the nested type in the permits clause, and it was not accepted by javac. (If all the subclasses are in the same compilation unit, either as auxiliary classes or nested classes, an explicit permits clause can be skipped as the compiler will infer it.)

Per your other point about the nested classes in MethodHandleImpl, JLS 8.1.6 states:

"Every TypeName [in the permits clause] must name an accessible class ([§6.6]), or a compile-time error occurs."

so the private classes of another class would not be accessible either.

**Comment by sundararajana** [comment]
Hmm.. I tried the following example:

$ cat com/acme/X.java
package com.acme;

// We can omit permits clause if all the subclasses are in the same compilation unit.
// But that's applicable here as two subclasses "Z", "P.Q" are outside the compilation unit.
// So we use explicit permits clause that lists all the subclasses.

public sealed class X 
   permits X.Y, W, Z, P.Q {
   final class Y extends X {}
}

final class W extends X {}

$ cat com/acme/Z.java
package com.acme;

final class Z extends X {
}

$ cat com/acme/P.java 
package com.acme;

class P {
   final class Q extends X {}
}

$ javac com/acme/*.java

is fine. Am I missing something?

**Review by sundararajana — APPROVED** [review]
LGTM

**Comment by mlchung** [comment]
> $ javac com/acme/*.java
>
> is fine. Am I missing something?

If you make P.Q private, it will fail the compilation.

To make `DelegatingMethodHandle` a sealed class, we could make `AsVarargsCollector` and `WrappedMember` package-private classes.

**Comment by sundararajana** [comment]
> > $ javac com/acme/*.java
> > is fine. Am I missing something?
> 
> If you make P.Q private, it will fail the compilation.
> 

Yes, I got that part. I did make a comment earlier ("Two of those subclasses are nested "private" in another class and hence cannot be referred from DelegatingMethodHandle's permits clause, right?"). My example was in response to "I did try to name the nested type in the permits clause, and it was not accepted by javac." comment by @jddarcy. I wondered if there is any other issue with permits beyond private access of those 2 nested classes. 

> To make `DelegatingMethodHandle` a sealed class, we could make `AsVarargsCollector` and `WrappedMember` package-private classes.

right.

**Comment by ExE-Boss** [comment]
**javac** should be changed to allow fully qualified access to private inner classes in the `permits` clause of an enclosing class.

**Comment by forax** [comment]
> javac should be changed to allow fully qualified access to private inner classes in the permits clause of an enclosing class.

This is not how private works, private means accessible between the '{' and the '}' of the class.
The permits clause is declared outside of the '{' and the '}' of the class, thus a private member class is not visible from the permits clause.

**Comment by ExE-Boss** [comment]
But the private inner classes are visible to the compiled `PermittedSubclasses` class attribute (otherwise it wouldn’t be possible for private inner classes to extend a sealed outer class with an implicit `permits` clause).

---

Technically, `private` means accessible only within the current nest.

**Review by mlchung — APPROVED** [review]
Looks good.

**Pull request closed without merging**
