### PR TITLE
8299713: Test javax/swing/JTableHeader/6889007/bug6889007.java failed: Wrong type of cursor

### PR DESCRIPTION
**Pull request by prsadhuk**
Issue seems to be very old, very intermittent bug which is not reproducible in repeated test run,
so added some stability fixes like accessing swing components in EDT, delay, frame dispose and take a screenshot during fail.
Multiple runs on CI platforms is ok.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299713](https://bugs.openjdk.org/browse/JDK-8299713): Test javax/swing/JTableHeader/6889007/bug6889007.java failed: Wrong type of cursor

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12181/head:pull/12181` \
`$ git checkout pull/12181`

Update a local copy of the PR: \
`$ git checkout pull/12181` \
`$ git pull https://git.openjdk.org/jdk.git pull/12181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12181`

View PR using the GUI difftool: \
`$ git pr show -t 12181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12181.diff">https://git.openjdk.org/jdk/pull/12181.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12181#issuecomment-1403272052)

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Comment by kumarabhi006** [comment]
@prsadhuk Trying to run the test in **ubuntu** system, it ended with time out error. Test passed in **windows** system.

**Review by TejeshR13 — APPROVED** [review]

**Comment by TejeshR13** [comment]
> @prsadhuk Trying to run the test in **ubuntu** system, it ended with time out error. Test passed in **windows** system.

@kumarabhi006 I'm not getting any such error in _ubuntu_. Fix is working for me in windows and ubuntu.

**Comment by prsadhuk** [comment]
time

**Pull request closed without merging**
