### PR TITLE
8322064: Remove expired flags in JDK 24

### PR DESCRIPTION
**Pull request by dholmes-ora**
All the VM flags that expire in JDK 24 are removed from the flag table. (Note obsoletion of flags in 24 is handled by separate PR's for each flag.)

The Java manpage is updated to move any documented obsolete flags to the removed flags section, and last releases removed flags are removed. A link to the JDK 23 removed flags is added.

No test were found that still referenced the removed flags (any such usage should have been removed when the flag was made obsolete).

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322064](https://bugs.openjdk.org/browse/JDK-8322064): Remove expired flags in JDK 24 (**Enhancement** - P3)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19642/head:pull/19642` \
`$ git checkout pull/19642`

Update a local copy of the PR: \
`$ git checkout pull/19642` \
`$ git pull https://git.openjdk.org/jdk.git pull/19642/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19642`

View PR using the GUI difftool: \
`$ git pr show -t 19642`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19642.diff">https://git.openjdk.org/jdk/pull/19642.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19642#issuecomment-2159611986)

### CODE REVIEW

**Comment by vnkozlov** [comment]
@dholmes-ora, I pushed  "Obsolete RTM flags" changes. You need to update man page.

**Comment by dholmes-ora** [comment]
Thanks @vnkozlov . Not sure what happened there as I had already pulled your changes. Seems to be fixed now.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by tstuefe — APPROVED** [review]
+1

**Comment by dholmes-ora** [comment]
Thanks for the reviews @vnkozlov  and @tstuefe !

/integrate

**Pull request closed without merging**
