### PR TITLE
8287180: Update IANA Language Subtag Registry to Version 2022-08-08

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
Problem: IANA Language subtag registry is outdated
Fix: Updated from version 2022-03-02 to 2022-08-08 -> [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287180](https://bugs.openjdk.org/browse/JDK-8287180): Update IANA Language Subtag Registry to Version 2022-08-08

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10546/head:pull/10546` \
`$ git checkout pull/10546`

Update a local copy of the PR: \
`$ git checkout pull/10546` \
`$ git pull https://git.openjdk.org/jdk pull/10546/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10546`

View PR using the GUI difftool: \
`$ git pr show -t 10546`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10546.diff">https://git.openjdk.org/jdk/pull/10546.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — CHANGES_REQUESTED** [review]
Although there aren't actual code changes, I believe the test `test/jdk/java/util/Locale/LanguageSubtagRegistryTest.java` should be modified as well.

**Review by naotoj — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
