### PR TITLE
8298376: ZGC: thaws stackChunk with stale oops

### PR DESCRIPTION
**Pull request by stefank**
During the recent ZGC + Loom rewrites JDK-8296875 a bug was introduced, which causes Loom to thaw stackChunks with stale oops.

Before that change we made sure that only the GC performed load barriers on the cont oop in stackChunk, so that we could use the oop state as an indication of the age of the stackChunk. That information was then used in ZCollectedHeap::requires_barriers.

In Generational ZGC we changed the implementation of requires_barriers, so that the rest of the JVM didn't need to have special-handling of the cont oop. However, when upstreaming the changes in JDK-8296875 we purposefully didn't update requires_barriers, but we incorrectly brought over the removal of the special-handling of the cont oop.

To limit the fix for this bug, I propose that we restore the special-handling of the cont oop.

I've tested this with a reproducer running Fuzz.java + ZGC.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298376](https://bugs.openjdk.org/browse/JDK-8298376): ZGC: thaws stackChunk with stale oops

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to [bb7183bf](https://git.openjdk.org/jdk/pull/11585/files/bb7183bf7be94364f13fddc7b5821958ee02a214)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**) ⚠️ Review applies to [bb7183bf](https://git.openjdk.org/jdk/pull/11585/files/bb7183bf7be94364f13fddc7b5821958ee02a214)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11585/head:pull/11585` \
`$ git checkout pull/11585`

Update a local copy of the PR: \
`$ git checkout pull/11585` \
`$ git pull https://git.openjdk.org/jdk pull/11585/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11585`

View PR using the GUI difftool: \
`$ git pr show -t 11585`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11585.diff">https://git.openjdk.org/jdk/pull/11585.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good.

**Review by pchilano — APPROVED** [review]
Looks good, thanks for adding the comment.

**Comment by coleenp** [comment]
Should this be fixed for JDK 20?

**Comment by stefank** [comment]
> Should this be fixed for JDK 20?

Yes. I'll backport this after pushing to 21.

**Pull request closed without merging**
