### PR TITLE
8328649: Disallow enclosing instances for local classes in constructor prologues

### PR DESCRIPTION
**Pull request by archiecobbs**
A local class declared in a static context is not supposed to have an immediately enclosing instance (§15.9.2). That includes local classes declared in constructors prior to `super()` (during the "constructor prologue" in the new lingo).

However, the compiler is allowing code like this to successfully compile:
```java
import java.util.concurrent.atomic.*;
public class Test extends AtomicReference<Object> {
  
    public Test() {
        super(switch (0) {
          default -> {
              class Local { { Test.this.hashCode(); } }   // this should fail
              yield null;
            }
        });
    }
}
```
This patch fixes the "leak".

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8328706](https://bugs.openjdk.org/browse/JDK-8328706) to be approved

### Issues
 * [JDK-8328649](https://bugs.openjdk.org/browse/JDK-8328649): Disallow enclosing instances for local classes in constructor prologues (**Bug** - P4)
 * [JDK-8328706](https://bugs.openjdk.org/browse/JDK-8328706): Disallow enclosing instances for local classes in constructor prologues (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18416/head:pull/18416` \
`$ git checkout pull/18416`

Update a local copy of the PR: \
`$ git checkout pull/18416` \
`$ git pull https://git.openjdk.org/jdk.git pull/18416/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18416`

View PR using the GUI difftool: \
`$ git pr show -t 18416`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18416.diff">https://git.openjdk.org/jdk/pull/18416.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18416#issuecomment-2011066104)

### CODE REVIEW

**Comment by liach** [comment]
Thanks for this change! This unification of outer instance handling of inner and anonymous class declaration paves the way for Valhalla's value classes and makes things more straightforward.

According to https://github.com/openjdk/jdk/pull/13656#issuecomment-1732340240 this change will affect the class file generated, such as for your given example. Should this patch get a CSR then?

**Comment by archiecobbs** [comment]
> According to https://github.com/openjdk/jdk/pull/13656#issuecomment-1732340240 this change will affect the class file generated, such as for your given example. Should this patch get a CSR then?

Well, this change only affects generated classfiles in the sense that it will be no longer possible to generate certain classfiles because compilation will fail instead :)

But regardless I think a CSR is probably warranted so I'll add one. Thanks.

**Review by vicente-romero-oracle — APPROVED** [review]
looks good to me

**Comment by vicente-romero-oracle** [comment]
> @vicente-romero-oracle, would you (or anyone) mind reviewing the [associated CSR](https://bugs.openjdk.org/browse/JDK-8328706) per @jddarcy's request?
> 
> Thanks.

looks good

**Comment by archiecobbs** [comment]
Hi @vicente-romero-oracle , thanks for reviewing & sponsoring. Please sponsor one more time as the bot got confused somehow. Thanks.

**Pull request closed without merging**
