### PR TITLE
8281243: Test java/lang/instrument/RetransformWithMethodParametersTest.java is failing

### PR DESCRIPTION
**Pull request by alexmenkov**
The test expects ClassFileReconstituter restores exactly the same bytes as original classbytes.
This can be wrong if the class has more than 1 method (due to method sorting in the VM).
MethodParametersTarget class had only 1 method (method1), but didn't have constructors. This caused declaration of implicit default constructor, so the class actually had 2 methods.
The fix converts the method to constructor to avoid default constructor declaration.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281243](https://bugs.openjdk.java.net/browse/JDK-8281243): Test java/lang/instrument/RetransformWithMethodParametersTest.java is failing

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7345/head:pull/7345` \
`$ git checkout pull/7345`

Update a local copy of the PR: \
`$ git checkout pull/7345` \
`$ git pull https://git.openjdk.java.net/jdk pull/7345/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7345`

View PR using the GUI difftool: \
`$ git pr show -t 7345`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7345.diff">https://git.openjdk.java.net/jdk/pull/7345.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Looks good to me.
Thanks,
Serguei

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up on the changes.

However, there's no details on how this fix was tested. Please clarify.
So far this test failure has been seen intermittently in Tier3.

**Review by lmesnik — APPROVED** [review]

**Comment by alexmenkov** [comment]
> Thumbs up on the changes.
> 
> However, there's no details on how this fix was tested. Please clarify. So far this test failure has been seen intermittently in Tier3.

Failure reports clearly show that the root cause is method sorting (ctor and method1 are in different order in original and reconstructed bytes), so I manually verified that now target class has the only method.
Also I run the test with --test-repeat 100 on supported platforms.

**Pull request closed without merging**
