### PR TITLE
8267079: Support async handshakes that can be executed by a remote thread

### PR DESCRIPTION
**Pull request by caoman**
Hi all,

Can I have reviews for this small refactoring change? It resolves a pending concern from [JDK-8238761](https://bugs.openjdk.java.net/browse/JDK-8238761), clarifies the code and allows more use case of async handshakes. See [JDK-8267079](https://bugs.openjdk.java.net/browse/JDK-8267079) for detailed description.

-Man

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8267079](https://bugs.openjdk.java.net/browse/JDK-8267079): Support async handshakes that can be executed by a remote thread

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4005/head:pull/4005` \
`$ git checkout pull/4005`

Update a local copy of the PR: \
`$ git checkout pull/4005` \
`$ git pull https://git.openjdk.java.net/jdk pull/4005/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4005`

View PR using the GUI difftool: \
`$ git pr show -t 4005`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4005.diff">https://git.openjdk.java.net/jdk/pull/4005.diff</a>

</details>

### CODE REVIEW

**Comment by caoman** [comment]
Hi David,

By "remote" I mean any thread that is not the current running thread itself. Basically "remote" = "non-self". In the handhshake model's terminology, remote executable means "executing thread" != "target thread". Remote is commonly used as a synonym for "non-local" in literature about CPU and NUMA, e.g. "remote cache", "remote memory".

Do you prefer the old term "non_self_executable" over "remote_executable"?

**Comment by robehn** [comment]
Hi, a couple of questions.

- The AsyncHandshakeClosure must still be on heap but when executed by a remote thread it looks like it's never deleted?
- In a normal work load there are very few handshakes, meaning there are almost never a "remote" thread.
  So if the requester uses the new AsyncHandshakeClosure, they will be almost always self/local executed.
  And there is no guarantee there will be any more handshakes, so the AsyncHandshakeClosure cannot be guaranteed to 
  finished. Since if the thread is in blocked state and there are not more handshakes it will not be executed.
  Which is the reason I did not separate them from the begging, to me it looks like very little adavantage to use 
  AsyncHandshakeClosure vs SelfExecutedHandshakeClosure.
  If you need guarantee that the handshake is executed, you cannot use AsyncHandshakeClosure and since there is almost never a remote thread the performance difference should be very slim?

To me it sounds like you want to customize the yield method or manually loop the processing of 'normal' handshakes?

E.g. either customized yield as template or closure:
Handshake::execute(handshake, ON_YIELD); // synchronous call
Or
Handshake::enqueue(handshake);
while (!Handshake::process_handshakes(handshake)) { // Do one iteration
   // Do other stuff
}

So the processing is asynchronous but we use normal handshakes?

**Comment by caoman** [comment]
I addressed the comments in the second commit.

For Robbin's question:
> The AsyncHandshakeClosure must still be on heap but when executed by a remote thread it looks like it's never deleted?

Great catch! Added delete in HandshakeState::try_process() similarly to HandshakeState::process_self_inner().

> If you need guarantee that the handshake is executed, you cannot use AsyncHandshakeClosure and since there is almost never a remote thread and the performance difference should be very slim?

I hope the reply to David could also answer this. I don't need a guarantee that the handshake is executed. I mainly need a safe approach to skip target threads that are blocked. Reusing the four if checks in HandshakeState::try_process() is a possible approach, and it would need async non-self executable handshake for HandshakeState::claim_handshake() to return true.

> To me it sounds like you want to customize the yield method or manually loop the processing of 'normal' handshakes?

Yes, that could work as well. I did find the "async" name confusing. If we support `Handshake::enqueue(handshake)` for 'normal' handshakes, it is basically an async submission of the 'normal' handshake. It also has the problem of how to deallocate the `HandshakeOperation` object, which is currently handled by `AsyncHandshakeOperation`.

**Comment by robehn** [comment]
> I addressed the comments in the second commit.
> 
> For Robbin's question:
> 
> > The AsyncHandshakeClosure must still be on heap but when executed by a remote thread it looks like it's never deleted?
> 
> Great catch! Added delete in HandshakeState::try_process() similarly to HandshakeState::process_self_inner().
> 
> > If you need guarantee that the handshake is executed, you cannot use AsyncHandshakeClosure and since there is almost never a remote thread and the performance difference should be very slim?
> 
> I hope the reply to David could also answer this. I don't need a guarantee that the handshake is executed. I mainly need a safe approach to skip target threads that are blocked. Reusing the four if checks in HandshakeState::try_process() is a possible approach, and it would need async non-self executable handshake for HandshakeState::claim_handshake() to return true.
> 
> > To me it sounds like you want to customize the yield method or manually loop the processing of 'normal' handshakes?
> 
> Yes, that could work as well. I did find the "async" name confusing. If we support `Handshake::enqueue(handshake)` for 'normal' handshakes, it is basically an async submission of the 'normal' handshake. It also has the problem of how to deallocate the `HandshakeOperation` object, which is currently handled by `AsyncHandshakeOperation`.

Ok, I think I got what you are trying todo.
But if you don't need it to be execute and you are fine with it being never execute, you also must not enqueue more.
Since it's never executed it will never be freed, thus we are leaking memory every time one is enqueued.
Which means the issuer of the handshakes must keep track of what threads that have not completed it's previous async handshake and avoid enqueue more.

Since we don't want to do this, I'm guessing, you could processes them with VM thread during the the safepoint synchronization (in this time slot where we often end up yielding the VM thread).
As long as you promise to safepoint and processes them there, if needed, we are not leaking.

**Comment by caoman** [comment]
Re David's comment:

> Though if there is a self-only async op in the queue ahead of that, then you won't be able to proceed anyway.

I don't quite understand this part. After this change, in `HandshakeState::try_process()`, the do...while loop calls `HandshakeState::pop()` inside, which will skip those self-only async ops, right?  Then it can still process those non-self executable async ops.

> Not really getting this part. Why do you want to skip blocked threads?
> ...
> if a thread is blocked then it is handshake-safe and so the handshake should be fast.
> Or are you concerned that your handshake won't be able to proceed
> because of what else may be in a target thread's op queue, and you want
> to skip that target in that case?

Perhaps "skipping" is a bad choice of word. In the latest implementation for epoch sync protocol, the requesting thread still issues the async handshake to blocked threads. The requesting thread then checks whether the target thread is blocked, if so, it updates the target thread's epoch counter on behalf of the target thread, then the epoch sync is done for this target thread. If the target thread is not blocked, the requesting thread can only wait, and possibly time out and give up. This is the same as the way that  `Handshake::execute()` executes a synchronous handshake op on behalf of a blocked target thread.

Currently just running `Handshake::execute()` for a target thread could run into a safepoint, and it does not support timeout or giving up. These behaviors do not work for G1's refinement. This is the reason I'm using enqueue-only async submission, and also need a way to check for threads that are blocked, in order to quickly finish the epoch sync with blocked threads.

With the arm-the-poll-only approach Robbin suggested, I think it still needs a way to check for blocked threads, and update the blocked thread's epoch counter on behalf of the blocked thread. I could do that in the change for JDK-8236485, or split it up in another RFE.

**Comment by caoman** [comment]
> I thought we had to preserve the order of handshake operations? (In the
> same way the safepoint operations were previously well ordered.) If that
> is not the case ... there might be some subtle interactions there that
> might lead to very hard to diagnose bugs.

I'm not sure about this. Currently without this change, if there are both async self-executed ops and synchronous non-self executable ops on the queue, it would not preserve the execution order.
I think non-self executable ops and self-executed ops shouldn't depend on each other. It would be a misuse of handshakes if that happens.

> As I don't know anything about the epoch sync protocol I don't really
> understand the requirements here. If you are prepared to have some
> threads defer execution of the async handshake indefinitely (because
> they aren't blocked) then why do you need to ensure you update the
> counter for other threads, rather than have them do it themselves when
> they are able to execute the async handshake op?

The epoch sync protocol only needs the target thread to execute a memory fence, or become blocked. The purpose is to flush out all potential stores to Java heap, or establish a release-acquire edge from the target thread to requesting thread. It is essentially an asymmetric Dekker synchronization (see [this article](https://blogs.oracle.com/dave/qpi-quiescence)). The role of handshake is like a "membarrier" Linux syscall on the target thread. This is why the actual handshake op is a no-op, and the arm-the-poll-only approach as Robbin suggested is superior.

For this question, it is because:
- We want to minimize the number of deferred ops, because deferring means more work during the later GC pause. In fact, with a timeout of 2-3 milliseconds, it is extremely rare to have deferred ops already.
- A blocked thread may not come back to in_Java for a long time, so it will not execute any self-executed async op. If we don't handle them, most ops will become deferred if there's a blocked thread. In a realistic large server, it is common to have hundreds or thousands of Java threads, and a large portion of them are blocked on Object.wait() and rarely become running.

**Comment by robehn** [comment]
"The goal is to support asynchronous handshake with all threads for JDK-8236485, and skipping threads that are blocked, without entering a safepoint in the requesting thread."

This line is just confusing, the requesting thread only enters a safepoint if it's a JavaThread.

- You don't need to skip blocked/native thread, those handshakes are finished really quickly on first iteration.
- If VM thread is busy doing starting safepoint, you can skip your epoch, since you just got it free via the safepoint.
  - Save the current safepoint counter and store it in the VM op.
  - Check that safepoint counter vs current counter in the VM ops doit_prologue()
  - If they do not match all threads have emitted the barrier. 

- All JavaThreads will safepoint before they perform any handshakes.
- If there is a safepoint, we should perform it was quick as possible, otherwise it will take longer for them to perform handshakes. 
- G1 concurrent threads are stopped before the safepoint: 
```
void G1CollectedHeap::safepoint_synchronize_begin() {
  SuspendibleThreadSet::synchronize();
}  

```

Not sure if this epoch sync is run by a thread part of SuspendibleThreadSet or not, but:
If it is; it is just prolonging the time to safepoint, which is a free epoch, thus finishing the epoch just wastes CPU.
If it is not; it is just hurting it's own performance, since handshakes are performed _after_ the safepoint.

So I do not see any reason why you can't use a synchronous handshakes.

If a Java thread does not do it's handshake in timely manner, there are generally be two issues:
- You don't have enough CPU, so the thread is not running. Using more CPU will just hurt in this case, so yielding is the correct thing todo.
- We are allocating and zeroing a large array, which is a GC issue. (fixed in ZGC)

If you have seem another case where you think a synchronous handshake takes to long, please let me know.

**Comment by caoman** [comment]
Re David's comment:

> Still not clear why this is necessary. The target thread is just as
> blocked or in native during a GC pause safepoint, as it is during a
> handshake. So if the GC can process them in one case surely it can do
> both. ??

There is no association between a dirty card and Java thread(s). Even if we have such association, i.e. we track which thread produced the dirty card, it is still insufficient to coordinate with only the dirtying thread. This is because other threads could have observed the card being dirty and performed a store to Java heap, without doing any fence or synchronization. Later, the refinement thread (the requesting thread) needs to load from the Java heap range mapped to the dirty card's address for the refinement work.
Thus, it is only safe to load from the Java heap range under one of the two conditions:
- The requesting thread have finished epoch synchronization with **all** Java threads. 
- It is at a safepoint where **all** Java threads have been synchronized and stopped.
Either condition guarantees that previous stores to the Java heap range mapped to the card's address are visible to the loading thread.

**Comment by caoman** [comment]
Re Robin's comment:

> This line is just confusing, the requesting thread only enters a safepoint if it's a JavaThread.
> ...
> Not sure if this epoch sync is run by a thread part of SuspendibleThreadSet or not, but:

Yes it is confusing. Let me clarify the problem.

The epoch sync is requested by either a G1 refinement thread, which is a part of SuspendibleThreadSet; or a Java thread from its post-write barrier's slow path, which is a JRT_LEAF function that forbids any operation that can safepoint. G1 by design supports concurrent refinement from a Java thread's post-write barrier, if there's too many cards to refine, see G1DirtyCardQueueSet::handle_completed_buffer().

I could get the epoch sync working using synchronous handshake when requesting thread == G1 refinement thread, by leaving SuspendibleThreadSet and redirtying some pending cards before calling Handshake::execute(). However, it does not work for the requesting thread == Java thread case, due to the JRT_LEAF constraint. This is the reason for proposing to use Handshake::enqueue() and support executing them from non-self threads.

> If it is; it is just prolonging the time to safepoint, which is a free epoch, thus finishing the epoch just wastes CPU.

Good point. I'll make sure any waiting in the epoch sync protocol also checks for pending safepoint and yields.

Anyway, I think the arm-the-poll-only approach is superior and it does not need to issue any handshake. I will look into that instead.

**Comment by caoman** [comment]
> If it is an all or none proposition then I don't see what skipping
> blocked threads has to do with this ??? Sorry I think I'm losing track
> of issues.

There's a per-thread epoch counter that determines each thread's progress for an epoch sync request.
A blocked thread cannot update its epoch counter by itself, so the requesting thread needs to "skip" the blocked thread by first checking if the target thread is blocked, then doing either:
- treats the target thread's epoch counter as >= the requested counter value;
- updates the target thread's counter on behalf of the target thread.

Either approach ensures forward progress when encountering a blocked thread. Otherwise, any blocked thread would prevent the epoch sync from finishing, leading to deferred cards.

Perhaps the description of https://bugs.openjdk.java.net/browse/JDK-8236485 can help understand it?

Anyway, this is beyond this PR. What do we want to do with this PR? The epoch sync protocol will not depend on it if it uses the arm-the-poll-only approach.

**Comment by robehn** [comment]
> Re Robin's comment:
> 
> > This line is just confusing, the requesting thread only enters a safepoint if it's a JavaThread.
> > ...
> > Not sure if this epoch sync is run by a thread part of SuspendibleThreadSet or not, but:
> 
> Yes it is confusing. Let me clarify the problem.
> 
> The epoch sync is requested by either a G1 refinement thread, which is a part of SuspendibleThreadSet; or a Java thread from its post-write barrier's slow path, which is a JRT_LEAF function that forbids any operation that can safepoint. G1 by design supports concurrent refinement from a Java thread's post-write barrier, if there's too many cards to refine, see G1DirtyCardQueueSet::handle_completed_buffer().
> 
> I could get the epoch sync working using synchronous handshake when requesting thread == G1 refinement thread, by leaving SuspendibleThreadSet and redirtying some pending cards before calling Handshake::execute(). However, it does not work for the requesting thread == Java thread case, due to the JRT_LEAF constraint. This is the reason for proposing to use Handshake::enqueue() and support executing them from non-self threads.
> 
> > If it is; it is just prolonging the time to safepoint, which is a free epoch, thus finishing the epoch just wastes CPU.
> 
> Good point. I'll make sure any waiting in the epoch sync protocol also checks for pending safepoint and yields.
> 
> Anyway, I think the arm-the-poll-only approach is superior and it does not need to issue any handshake. I will look into that instead.

If someone keeps suspending ad resuming a thread the thread might always have the poll armed and always have a handshake.
Just looking if queue is empty or not, or poll is armed or not can have pathological cases.
If you add an epoch counter into Thread::gc_data_offset you could update it by putting a line next cross-mod-fence:
`
void SafepointMechanism::process_if_requested_slow(JavaThread *thread) {
...
  OrderAccess::cross_modify_fence();
  Universe::heap()->barrier_complete(thread); // store global epoch to GCThreadLocalData
}
`
But as David said, you basically trying to handshake without a handshake :)
(should try to put the counter inside the handshake instead)

**Comment by caoman** [comment]
Thanks. Let me first do more experiment to validate first. I'll close this PR once confirming the other approach also works.

> If someone keeps suspending ad resuming a thread the thread might always have the poll armed and always have a handshake.
> Just looking if queue is empty or not, or poll is armed or not can have pathological cases.

If I understand the context correctly, the approach of updating the epoch counter in `process_if_requested_slow()` will prevent the pathological cases above? And yes, the current implementation already updates the epoch counter in `SafepointMechanism::update_poll_values()` similarly.

> If you add an epoch counter into Thread::gc_data_offset you could update it by putting a line next cross-mod-fence:
> `void SafepointMechanism::process_if_requested_slow(JavaThread *thread) { ... OrderAccess::cross_modify_fence(); Universe::heap()->barrier_complete(thread); // store global epoch to GCThreadLocalData }`

Thanks, adding a new virtual method in CollectedHeap is much cleaner than my current `if (UseG1GC) update_epoch_self();` approach.

> But as David said, you basically trying to handshake without a handshake :)
> (should try to put the counter inside the handshake instead)

One note is that a thread could also update its epoch counter in places that are irrelevant to polling or handshake. This could make epoch sync more responsive than handshakes. Currently I only added such update in `ThreadInVMfromJava`, since it is executed frequently. I'll evaluate whether this update still makes much difference in responsiveness.

**Comment by robehn** [comment]
> If I understand the context correctly, the approach of updating the epoch counter in `process_if_requested_slow()` will prevent the pathological cases above? 

Yes, it will avoid that!

Thanks, Robbin

**Comment by caoman** [comment]
Closing this PR as the "arm-the-poll-only approach" seems to work, although there are some performance problems to resolve.

**Pull request closed without merging**
