### PR TITLE
8268285: vmTestbase/nsk/jvmti/GetThreadState/thrstat002 failed with "Wrong thread "thr1" (...) state after SuspendThread"

### PR DESCRIPTION
**Pull request by sspitsyn**
The test is intermittently failing because the tested thread thrstat002a is blocked on a monitor in the PrintStream.println(String) when it is expected to be in the RUNNABLE state:
  thrstat002.runningBarrier.unlock(); <= now the thrstat002 state can be checked and suspend issued
  System.out.println("thrstat002a.run after runningBarrier unlock"); <= blocked on the monitor in here

The fix is to move println line to the point before thrstat002.runningBarrier.unlock();
Also, a fflush(0) statement is added to the agent *_checkStatus() function to get output better sync'ed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268285](https://bugs.openjdk.java.net/browse/JDK-8268285): vmTestbase/nsk/jvmti/GetThreadState/thrstat002 failed with "Wrong thread "thr1" (...) state after SuspendThread"

### Reviewers
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - Committer) ⚠️ Review applies to 9d7ed6e515f1951c2a5e13cbf259e300f9999090
 * [Alex Menkov](https://openjdk.java.net/census#amenkov) (@alexmenkov - **Reviewer**) ⚠️ Review applies to 9d7ed6e515f1951c2a5e13cbf259e300f9999090
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 07bdb421e56525b5beb5ed07416877c0d00fad59

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4447/head:pull/4447` \
`$ git checkout pull/4447`

Update a local copy of the PR: \
`$ git checkout pull/4447` \
`$ git pull https://git.openjdk.java.net/jdk pull/4447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4447`

View PR using the GUI difftool: \
`$ git pr show -t 4447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4447.diff">https://git.openjdk.java.net/jdk/pull/4447.diff</a>

</details>

### CODE REVIEW

**Review by lmesnik — APPROVED** [review]

**Review by alexmenkov — APPROVED** [review]

**Comment by sspitsyn** [comment]
Leonid and Alex, thank you for quick review!

**Review by dholmes-ora — APPROVED** [review]
LGTM2 :)

The two adjacent printlns are somewhat redundant (sorry I overlooked that) but harmless.

Thanks,
David

**Comment by sspitsyn** [comment]
Thanks, David. Yes, I looked at these two lines and decided it is harmless to keep both.

**Pull request closed without merging**
