### PR TITLE
8263017: Read barriers are missing in nmethod printing code 

### PR DESCRIPTION
**Pull request by iwanowww**
OOP accesses from nmethod printing code miss read barriers. 
It causes sporadic crashes when the code stumbles upon a stale OOP.

When `nmethod::print_nmethod` is invoked, the corresponding nmethod is already installed in the code cache and there was a safepoint check in between (see `ThreadToNativeFromVM` usage in `CompileBroker::invoke_compiler_on_method`).
 
The fix adds missing read barriers in `oop_Relocation::oop_value()` and introduces `oop_Relocation::raw_oop_value()` for cases when read barriers aren't needed.

Along the way, there are some cleanups applied (e.g, `nmethod::print_[oops|metadata]` is superseded by `nmethod::print_recorded_[oops|metadata]`).

Testing:
- [x] failing test w/ `-XX:+UseZGC` `-XX:ZCollectionInterval=0.01` `-XX:ZFragmentationLimit=0`
- [x] hs-tier1 - hs-tier4

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263017](https://bugs.openjdk.java.net/browse/JDK-8263017): Read barriers are missing in nmethod printing code 

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2919/head:pull/2919`
`$ git checkout pull/2919`

### CODE REVIEW

**Review by fisk — CHANGES_REQUESTED** [review]
The load barrier on misaligned oop relocations will cause intermittent crashes. This is not safe. I can give you a fix tomorrow hopefully.

**Review by vnkozlov — APPROVED** [review]
Nice noticing that `print_recorded_oops()` and `print_recorded_metadata()` produces the same output as `print_oops()` and `print_metadata()`. I looked on output recently and was wondering why it printed twice.

**Comment by iwanowww** [comment]
> The load barrier on misaligned oop relocations will cause intermittent crashes. This is not safe. I can give you a fix tomorrow hopefully.

Thanks, Erik. 

As an alternative, I could add `BarrierSetNMethod::nmethod_entry_barrier()` into `nmethod::print_nmethod()` to ensure that all the oops are healed. Let me know what you prefer.

**Comment by fisk** [comment]
> > The load barrier on misaligned oop relocations will cause intermittent crashes. This is not safe. I can give you a fix tomorrow hopefully.
> 
> 
> 
> Thanks, Erik. 
> 
> 
> 
> As an alternative, I could add `BarrierSetNMethod::nmethod_entry_barrier()` into `nmethod::print_nmethod()` to ensure that all the oops are healed. Let me know what you prefer.

You can run nmethod::run_nmethod_entry_barriers() for now to fix the immediate bug. Then I can add the better load barrier for this situation. If you decide to do that, consider this reviewed.

**Comment by iwanowww** [comment]
> You can run nmethod::run_nmethod_entry_barriers() for now to fix the immediate bug. Then I can add the better load barrier for this situation.

Sounds good. Switched to `run_nmethod_entry_barriers()` for now.

Also, reverted the cleanups/refactorings. Will push them separately.

**Review by fisk — APPROVED** [review]
Looks good.

**Review by vnkozlov — APPROVED** [review]
Wow. Now it is really pinpoint fix!

**Comment by iwanowww** [comment]
Thanks for the reviews, Erik and Vladimir.

**Pull request closed without merging**
