### PR TITLE
JDK-8263467: Incorrect double-checked locking in sun.java2d.CRenderer

### PR DESCRIPTION
**Pull request by shipilev**
SonarCloud reports multiple incorrect double-checked locking cases in `sun.java2d.CRenderer`. For example:

```
  Arc2D arcToShape;

  ...
            if (arcToShape == null) {
                synchronized (this) {
                    if (arcToShape == null) {
                        arcToShape = new Arc2D.Float();
                    }
                }
            }
```

`Arc2D` contains fields that are not `final`. `arcToShape` is not `volatile`. This makes it an incorrect DCL.
This code is used by Mac OS, do it would probably blow up some time later on M1.

This is the candidate fix that preserves the semantics. I am doing this fix blindly so far, without testing on real Mac OS. But maybe there is no need to do any of this, because the setter methods overwrite the contents of all these objects under their own sync. So, maybe we can just allocate those objects without DCL-backed caching and pass them in?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263467](https://bugs.openjdk.java.net/browse/JDK-8263467): Incorrect double-checked locking in sun.java2d.CRenderer

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Alexander Zvegintsev](https://openjdk.java.net/census#azvegint) (@azvegint - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/2948/head:pull/2948` \
`$ git checkout pull/2948`

Update a local copy of the PR: \
`$ git checkout pull/2948` \
`$ git pull https://git.openjdk.java.net/jdk pull/2948/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2948`

View PR using the GUI difftool: \
`$ git pr show -t 2948`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/2948.diff">https://git.openjdk.java.net/jdk/pull/2948.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
I guess "Incorrect double-checked" is a too strict description of this code, it just tried to eliminate the creation of one object and do not care about the content of that object, since it is immediately overridden. 

I think It will be more clear to just eliminate this DCL since overhead and code complexity seems too much to just cache five objects.

Probably it was important in past(jdk6 and below) when this renderer was used for onscreen rendering. Currently, it is used for printing(if actually used at all).

**Comment by shipilev** [comment]
Ok, I removed the "DCL" from that code and used the objects directly. AFAICS, synchronization is redundant on those local objects. What would be a good test for this change?

**Comment by mrserb** [comment]
> Ok, I removed the "DCL" from that code and used the objects directly. AFAICS, synchronization is redundant on those local objects. What would be a good test for this change?

I guess that synchronization became redundant because the field was moved to the local var. But before that, it guarded the method in question for multithreaded access and that was not part of the DCL. So it will be better to return those fields back.

As the test I have run all automated tests and some manual tests, none of them triggered this code.

**Comment by shipilev** [comment]
Not now, bot.

**Review by prrace — APPROVED** [review]
LGTM

**Review by azvegint — APPROVED** [review]

**Comment by mrserb** [comment]
> I guess that synchronization became redundant because the field was moved to the local var. But before that, it guarded the method in question for multithreaded access and that was not part of the DCL. So it will be better to return those fields back.

Is not approved yet, see above.

**Comment by turbanoff** [comment]
Seems this PR was lost for some reason.
@shipilev can you please reopen it?

**Pull request closed without merging**
