### PR TITLE
8345438: Invalid error for return in early construction context lambda

### PR DESCRIPTION
**Pull request by archiecobbs**
The "Flexible Constructors" JEP feature allows statements to appear before a `super()` invocation, but some restrictions, one of which is that `return` is not allowed. The compiler check for this was being too strict in that it was incorrectly disallowing a `return` statement that was nested inside a lambda, which is OK.

Please review this patch to the `SuperThisChecker` which fixes this.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345438](https://bugs.openjdk.org/browse/JDK-8345438): Invalid error for return in early construction context lambda (**Bug** - P4)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**) Review applies to [470684f8](https://git.openjdk.org/jdk/pull/22531/files/470684f87ca2619b1a3ffbb341e71d0fc301e84c)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22531/head:pull/22531` \
`$ git checkout pull/22531`

Update a local copy of the PR: \
`$ git checkout pull/22531` \
`$ git pull https://git.openjdk.org/jdk.git pull/22531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22531`

View PR using the GUI difftool: \
`$ git pr show -t 22531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22531.diff">https://git.openjdk.org/jdk/pull/22531.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22531#issuecomment-2516027010)
</details>

### CODE REVIEW

**Comment by liach** [comment]
Since those checks were not initialized correct for lambda nesting at all, is there any other implied effects of missing these state initializations? Is there any scenario that is erroneously allowed in a lambda, or any other scenario that is erroneously rejected in a lambda? Would be nice to include them in the test if there is any.

**Review by mcimadamore — APPROVED** [review]
Looks good. I was a bit worried re. setting `scanDepth = 0`, but I see that the `costructor` check dominates everything else.

**Comment by archiecobbs** [comment]
> Since those checks were not initialized correct for lambda nesting at all, is there any other implied effects of missing these state initializations? Is there any scenario that is erroneously allowed in a lambda, or any other scenario that is erroneously rejected in a lambda? Would be nice to include them in the test if there is any.

I did think about that as well and couldn't come up with any. However, I've sprinkled in some more tests in 0dce8b32b83.

For the purposes of this analysis, the handling of a lambda should be the same as the handling of a non-constructor method, which is the effect that this patch has.

**Comment by archiecobbs** [comment]
@mcimadamore, requesting a re-review after new unit tests added. Thanks.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Comment by archiecobbs** [comment]
Thanks for the reviews.

**Pull request closed without merging**
