### PR TITLE
8254023: A module declaration is not allowed to be a target of an annotation that lacks an @Target meta-annotation

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

The Java Language Specifications(JLS), from 8 to 13 included, state it as below:

> If an annotation of type java.lang.annotation.Target is not present on the
declaration of an annotation type T , then T is applicable in all declaration contexts
except type parameter declarations, and in no type contexts.
These contexts are the syntactic locations where annotations were allowed in Java SE 7.

The JLS 14 and 15 state it as below:

>If an annotation of type java.lang.annotation.Target is not present on the
declaration of an annotation type T , then T is applicable in all nine declaration
contexts and in all 16 type contexts.

This patch adds `names.MODULE, names.TYPE_PARAMETER, names.TYPE_USE` to `com.sun.tools.javac.comp.Check.dfltTargetMeta` to fix this issue.
Thank you for taking the time to review.

Best Regards.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8254023](https://bugs.openjdk.java.net/browse/JDK-8254023): A module declaration is not allowed to be a target of an annotation that lacks an @Target meta-annotation

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/622/head:pull/622`
`$ git checkout pull/622`

### CODE REVIEW

**Comment by jbf** [comment]
Hello,

Thank you for the contribution.

As you can see from the \@Target javadoc ( https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/annotation/Target.html ) there is some ambiguity here. I have rased a separate discussion on compiler-dev, depending on the outcome of that discussion this patch will need to be revised.

**Comment by lgxbslgx** [comment]
Thanks for focusing on this patch. I will continue to follow the discussion and revise my patch based on the outcome of the discussion.

**Comment by lgxbslgx** [comment]
> Short term (Java 16) it makes sense to fix https://bugs.openjdk.java.net/browse/JDK-8254023 given that both competing specs agree for this case, it is a small fix, and externally found.
>
>For Java 17 we should align both specs and the reference implementation one way or another.

@jbf According to your comments, I revise my code to only fix JDK-8254023.
The rest of the work, ambiguity of the specifications, will be clarified and fixed in Java 17.
Thank you for taking the time to review.

**Comment by vicente-romero-oracle** [comment]
the change looks good but I'm surprised that no other tests are failing and need changes, in particular tests like:  `test/langtools/tools/javac/annotations/repeatingAnnotations/combo/TargetAnnoCombo.java`

**Comment by lgxbslgx** [comment]
@vicente-romero-oracle It is difficult to identify which test should be changed, because all the tests passed. As you said, the `TargetAnnoCombo.java` maybe need to be changed. I want to revise it now. Should I do it?

**Comment by vicente-romero-oracle** [comment]
> @vicente-romero-oracle It is difficult to identify which test should be changed, because all the tests passed. As you said, the `TargetAnnoCombo.java` maybe need to be changed. I want to revise it now. Should I do it?

sure please, I think that you should not only check that that test passes but also modify it, explicitly adding cases for the MODULE target. As a general comment this change is simple but the implications are not. I think the patch needs to add more tests. We also need to test that annotation processors can `see` the annotation applied to modules, etc.

**Comment by jbf** [comment]
Hi,

I don't think TargetAnnoCombo should be updated, at least not for this fix. It is an old hard to understand test that predates modules.

It would be good to do further testing as Vicente writes. I suggest:

1) A test that the module info compiles, you already have this.
2) A test that the class file contains the bytes for the annotation might make sense. As Jon has pointed out in different review threads there is the toolbox, perhaps that could be of use? There are some examples of toolbox tests in  `jdk/test/langtools/tools/javac/modules` though I don't have a good example of one that verifies the contents of the class file. Perhaps @vicente-romero-oracle can point to an example? 
3) There should already be tests that annotation processing can pick up annotations on module declarations, it looks like `jdk/test/langtools/tools/javac/modules/AnnotationProcessing.java` contains some of this. See if you can add a case with an annotation without \@Target.

**Comment by vicente-romero-oracle** [comment]
> Hi,
> 
> I don't think TargetAnnoCombo should be updated, at least not for this fix. It is an old hard to understand test that predates modules.
> 
> It would be good to do further testing as Vicente writes. I suggest:
> 
>     1. A test that the module info compiles, you already have this.
> 
>     2. A test that the class file contains the bytes for the annotation might make sense. As Jon has pointed out in different review threads there is the toolbox, perhaps that could be of use? There are some examples of toolbox tests in  `jdk/test/langtools/tools/javac/modules` though I don't have a good example of one that verifies the contents of the class file. Perhaps @vicente-romero-oracle can point to an example?

it is probably an overkill but method: `testAnnos` in test: `test/langtools/tools/javac/records/RecordCompilationTests.java` is an example applied to records that could be adapted to what we want here

**Comment by lgxbslgx** [comment]
I added two test cases. Thank you for taking the time to review.

**Comment by jbf** [comment]
Hi @lgxbslgx 

This looks good to me. Since this is targeted to Java 16 we need to close this PR and open a new PR towards the JDK16 project and finish the review there, add a link back to this PR would also be neat. Can you do that?

cheers
/Joel

**Comment by lgxbslgx** [comment]
@jbf I open a new PR in JDK 16. Please see https://github.com/openjdk/jdk16/pull/34

**Comment by lgxbslgx** [comment]
The later work will be completed in JDK 16.

**Pull request closed without merging**
