### PR TITLE
8270086: ARM32-softfp: Do not load CONSTANT_double using the condy helper methods in the interpreter

### PR DESCRIPTION
**Pull request by mychris**
Hi,

please review this fix for the template interpreter for ARM32-softfp.

With the introduction of condy, the interpreter started to load double constants using the condy_helper, which is unnecessary. Also, the [resolve_ldc](https://github.com/openjdk/jdk/blob/8973867fb9568a3a527b763c9ce10cebdfb306d0/src/hotspot/share/interpreter/interpreterRuntime.cpp#L148) implementation of the interpreter runtime might not be designed to load constant values. It should only load strings and condy.

https://github.com/openjdk/jdk/blob/2ee56fd1cf4acd634e19cc77b7c9a6858e1c315a/src/hotspot/cpu/arm/templateTable_arm.cpp#L515-L560

I refactored the ldc2_w bytecode imlpementation. Now, the ifdef between soft and hard float covers both types, CONSTANT_Long and CONSTANT_Double. I did this, because for the softfp, we can use a conditional cmp, since double and long are both placed on the stack in the same way. The same is also done for CONSTANT_Integer and CONSTANT_Float in the ldc bytecode implementation. Also, I think it is easier to follow the code this way.

Old ldc2_w implementation (before condy was implemented for ARM32):

https://github.com/openjdk/jdk/blob/7101b28dc3903be27cb46a00781f4d74f81f1114/src/hotspot/cpu/arm/templateTable_arm.cpp#L497-L537

Testing: ARMv7-A (hardfp) hotspot tier1, ARMv5TE (softfp) hotspot tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270086](https://bugs.openjdk.java.net/browse/JDK-8270086): ARM32-softfp: Do not load CONSTANT_double using the condy helper methods in the interpreter

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4767/head:pull/4767` \
`$ git checkout pull/4767`

Update a local copy of the PR: \
`$ git checkout pull/4767` \
`$ git pull https://git.openjdk.java.net/jdk pull/4767/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4767`

View PR using the GUI difftool: \
`$ git pr show -t 4767`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4767.diff">https://git.openjdk.java.net/jdk/pull/4767.diff</a>

</details>

### CODE REVIEW

**Comment by mychris** [comment]
@dholmes-ora or @coleenp, could you maybe have a look at this, since you already looked into #4582?

**Comment by dholmes-ora** [comment]
Sorry @mychris I never noticed this PR mail. I have taken a look and the logic seems sounds to me but I'm no expert at writing ARM code so I can't really approve it in detail.

David

**Review by shipilev — COMMENTED** [review]
I see that this patch does, and I think it goes in the right direction. Let's follow the form of other arches `TemplateTable::ldc2_w` does, and what other places in ARM32 template interpreter do?

These are my suggestions: 
 - Rename label `Condy` to `NotLong`
 - Rename label `exit` to `Done`
 - Handle only double path under !_ABI_HARD_PATH

Something like (drafting it blindly):

```
  Label NotLong, Done;

  Label NotDouble;
  __ cmp(Rtemp, JVM_CONSTANT_Double);
  __ b(NotDouble, ne);
#ifdef __ABI_HARD__
  __ ldr_double(D0_tos, Address(Rbase, base_offset));
#else
  __ ldr(R0_tos_lo, Address(Rbase, base_offset + 0 * wordSize));
  __ ldr(R1_tos_hi, Address(Rbase, base_offset + 1 * wordSize));
#endif
  __ push(dtos);
  __ b(Done);

  __ bind(NotDouble);
  __ cmp(Rtemp, JVM_CONSTANT_Long);
  __ b(NotLong, ne);
  __ ldr(R0_tos_lo, Address(Rbase, base_offset + 0 * wordSize));
  __ ldr(R1_tos_hi, Address(Rbase, base_offset + 1 * wordSize));
  __ push(ltos);
  __ b(Done);
#endif // __ABI_HARD__

  __ bind(NotLong);
  condy_helper(Done);
  __ bind(Done);
```

**Comment by shipilev** [comment]
TBH, I am not even sure that we need to check `__ABI_HARD__` here instead of `__SOFTFP__` here. Looking at `TemplateTable::dload` and `load_category2_local`, I would have expected `__SOFTFP__`...

**Comment by mychris** [comment]
Thanks for looking into this, Aleksey.

I will look into your suggestions. The reason I did a bigger #ifdef block was, because I think the problem was introduced because the softfp path was mixed into the hardfp one. For me, this makes the softfp path harder to understand, in contrast to my suggested solution. I know that having bigger #ifdef brings other problems with it. Do you think it is better to keep the #ifdef as small as possible and mix the softfp path into the hardfp?

> TBH, I am not even sure that we need to check __ABI_HARD__ here instead of __SOFTFP__ here. Looking at TemplateTable::dload and load_category2_local, I would have expected __SOFTFP__...

I don't quite understand what you mean here. Both, ABI_HARD and SOFTFP should be macros which specify which ABI should be used, so for me, if `__SOFTFP__` is `1`, `__ABI_HARD__` is `0`, or the other way around, or am I missing something? Could you elaborate why you think this should be changed?

**Comment by shipilev** [comment]
AFAICS, the real problem is that "double" path is not implemented for "!__ABI_HARD__" path, right? Which calls for fixing that part, and that part only. This also avoids touching the "long" path and relying on the "ltos" being fine for doubles. Other parts of template interpreter deal with this already, see `TemplateTable::dload`.

AFAIU, `ABI_HARD` and `SOFTFP` are defining different things. `SOFTFP` defines whether to use hardware or software instructions to deal with FP. Whereas `ABI_HARD` covers the _ABI_ parts, i.e. which registers to use to pass FP values between calls. Here we don't call anything, but only do loads. This reasoning seems to be consistent with what `TemplateTable::dload` does...

**Comment by mychris** [comment]
> AFAIU, ABI_HARD and SOFTFP are defining different things. SOFTFP defines whether to use hardware instructions or software emulation to deal with FP. Whereas ABI_HARD covers the ABI parts, i.e. which registers to use to pass FP values between calls. Here we don't call anything, but only do loads. This reasoning seems to be consistent with what TemplateTable::dload does. Seeing how -mfloat-abi takes three values, I can see ABI_HARD and SOFTFP might be not mutually exclusive?

That makes sense.
I checked with my GCC:

* `-mfloat-abi=soft` defines `__SOFTFP__`
* `-mfloat-abi=softfp` defines neither `__ARM_PCS_VFP`, nor `__SOFTFP__` (`__ARM_PCS_VFP` is used to define `__ABI_HARD__` in `globalDefinitions_arm.hpp`)
* `-mfloat-abi=hard` defines `__ARM_PCS_VFP`

My assumption was that `__SOFTFP__` is defined for both, `-mfloat-abi=soft` and `-mfloat-abi=softfp`, which is not the case. Thanks for pointing that out.

This suggests that we need to be consistent within the template interpreter and always use `__SOFTFP__` if we want to know which registers to use to pass floating point values inside the interpreter. `__ABI_HARD__` has to be used if it is required to follow the native ABI.

**Comment by mychris** [comment]
I changed the code as suggested.

Now __SOFTFP__ is used instead of ABI_HARD and the `#ifdef` is inside the `JVM_CONSTANT_Double` case only, loading double constants as needed.
Other changes are only renaming labels.

**Review by shipilev — APPROVED** [review]
This looks fine to me, thanks! Assuming it passes `tier1` on soft/hard-float targets, we are good to go.

**Comment by mychris** [comment]
Yes, hotspot tier1 on ARMv7-A (hard fload) and ARMv5TE (soft float) are passing.
Windows build failure is unrelated.

**Comment by shipilev** [comment]
> Yes, hotspot tier1 on ARMv7-A (hard fload) and ARMv5TE (soft float) are passing.
> Windows build failure is unrelated.

OK, good. I'll be happy to sponsor this.

**Comment by mychris** [comment]
Thanks, but don't we need a second reviewer, or is this change trivial enough?

**Comment by shipilev** [comment]
> Thanks, but don't we need a second reviewer, or is this change trivial enough?

For ARM-specific code, I don't think you would get more Oracle reviewers. Maybe @bulasevich wants to take a look.

**Comment by BorisUlasevich** [comment]
(I am not a formal reviewer)

I like the change.

Though I do catch what was the original motivation, was it an incorrect behavior? Is there any test for that?

And, frankly, I do not quite understand (NotLong && NotDouble) case for ldc2_w bytecode template which is designed to get long or double. Is condy_helper ever called here?

**Comment by mychris** [comment]
Thanks for looking into this.

The motivation is an incorrect behavior. The `ldc2_w` bytecode is used to load 3 different types of constants, `CONSTANT_Long`, `CONSTANT_Double`, and `CONSTANT_Dynamic`. The `condy_helper` should only be used to load constants of type `CONSTANT_Dynamic`. Currently it also loads `CONSTANT_Double` constants on soft-float targets, which is wrong and should not be done.

For this specific faulty behavior, there is no test case and I don't think there can be one, as loading is done using the wrong path, but still succeeds.

I don't think there are any test cases for loading primitive constants (as this is done while loading the runtime and therefor tested alot without a specific test case). There are some tests for constant dynamics in `test/hotspot/jtreg/runtime/condy`.

**Comment by BorisUlasevich** [comment]
Ok, thanks. 
The change is good for me.

**Comment by mychris** [comment]
Thank you.
/integrate

**Pull request closed without merging**
