### PR TITLE
8329559: Test javax/swing/JFrame/bug4419914.java failed because The End and Start buttons are not placed correctly and Tab focus does not move as expected

### PR DESCRIPTION
**Pull request by prsadhuk**
Test issue shows the End and Start buttons are not placed as per instructions due to ComponentOrientation RTL was not honoured, as with `getContentPane()` being removed from `add` call of JFrame, it was also additionally removed from other JFrame calls which resulted in the RTL not being propagated to its child. Fix is to add `getContentPane()` to the non-add methods of JFrame as was done in the applet version of the test..

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329559](https://bugs.openjdk.org/browse/JDK-8329559): Test javax/swing/JFrame/bug4419914.java failed because The End and Start buttons are not placed correctly and Tab focus does not move as expected (**Bug** - P4)

### Reviewers
 * [Abhishek Kumar](https://openjdk.org/census#abhiscxk) (@kumarabhi006 - Committer)
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - **Reviewer**)
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18612/head:pull/18612` \
`$ git checkout pull/18612`

Update a local copy of the PR: \
`$ git checkout pull/18612` \
`$ git pull https://git.openjdk.org/jdk.git pull/18612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18612`

View PR using the GUI difftool: \
`$ git pr show -t 18612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18612.diff">https://git.openjdk.org/jdk/pull/18612.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18612#issuecomment-2036234175)

### CODE REVIEW

**Review by kumarabhi006 — APPROVED** [review]
Just a minor suggestion, can increase the row count to avoid the scrollbar else looks good to me.

**Review by kumarabhi006 — APPROVED** [review]

**Review by honkar-jdk — APPROVED** [review]
LGTM

**Review by DamonGuy — APPROVED** [review]
Changes LGTM. Behaving as expected.

**Pull request closed without merging**
