### PR TITLE
8280770: serviceability/sa/ClhsdbThreadContext.java sometimes fails with 'Thread "SteadyStateThread"' missing from stdout/stderr

### PR DESCRIPTION
**Pull request by plummercj**
The test does a "threadcontext -v -a", and from the following output determines the threadID of the SteadyStateThread:

  `Thread "SteadyStateThread" id=23 Address=0x000001dc51749420`

It then tries threadcontext on this id, but it fails:

```
 + threadcontext -v 23
Couldn't find thread 23 
```

This only happens on Windows. It turns out that each time you attach on Window, the threadID for a thread can change. Some added diagnostic output showed that for the SteadyStateThread, it changed from 23 to 20, and there is no thread with an ID of 23.

The only way to make this this part of the test work Windows as expected is to parse the output of "threadcontext -v -a" without first doing a detach, and then doing the "threadcontext -v 23" without having to attach again. Unfortunately the test infrastructure for Clhsdb tests (and specifically ClhsdbLauncher) don't make this easy to do this. You can't easily see the output without first detaching, and then attach again on the next command. For this reason I've chosen to not verify the output of the "threadcontext -v <id>" part of the test when running on Windows. ClhsdbLauncher will still do the normal checks to make sure no exceptions or errors are present in the output.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280770](https://bugs.openjdk.java.net/browse/JDK-8280770): serviceability/sa/ClhsdbThreadContext.java  sometimes fails with 'Thread "SteadyStateThread"' missing from stdout/stderr

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7259/head:pull/7259` \
`$ git checkout pull/7259`

Update a local copy of the PR: \
`$ git checkout pull/7259` \
`$ git pull https://git.openjdk.java.net/jdk pull/7259/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7259`

View PR using the GUI difftool: \
`$ git pr show -t 7259`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7259.diff">https://git.openjdk.java.net/jdk/pull/7259.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
How are the thread id's determined such that they can change on each attach?

**Comment by plummercj** [comment]
> How are the thread id's determined such that they can change on each attach?

This is all I could find:

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/controlling-threads-and-processes

I speculated about it a bit in the following bug comment:

https://bugs.openjdk.java.net/browse/JDK-8280770?focusedCommentId=14472814&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14472814

I assume on each attach it iterates over all the threads in the order created and assigns IDs starting at 0. So if some in the middle are deleted, then those that come after get a new ID. I noticed the following before and after orders when the thest fails:

4 11 12 13 14 15 16 17 18 19 20 22 23
1 8 9 10 11 12 13 14 15 16 17 19 20 

In the the 1st list "main" is 4. In the second it is 1.  The order of the threads remains the same. Only the threadIDs have changed. So I'm guessing whichever threads were 1, 2, and 3 in the first list have exited. These would all be non-java threads so they don't show up in the SA list of threads. However I have no idea what those 3 exiting threads would be, assuming they are all ones created before "main".

**Comment by dholmes-ora** [comment]
That seems bizarre. If this is a dump from our Java launcher then there should be no other threads created before the one that loads the JVM.
That said I'm a little surprised we are doing "kernel debugging" here and so the "engine id" comes into play. But that said shouldn't we be using the stable "system id" for the threads not this "engine id" ?

**Comment by plummercj** [comment]
> That seems bizarre. If this is a dump from our Java launcher then there should be no other threads created before the one that loads the JVM.

Maybe they are invisible threads that Windows creates on thread launch that are deleted soon after startup. Or maybe it has little to do with thread creation/deletion, and the numbering given to threads depends on other factors.

> That said I'm a little surprised we are doing "kernel debugging" here and so the "engine id" comes into play. But that said shouldn't we be using the stable "system id" for the threads not this "engine id" ?

I'm not sure. This appears to be unique to Windows. For Linux the `javathread.printThreadIDOn()` call boils down to the following in LinuxThread.java:
```
    public String toString() {
        return Integer.toString(lwp_id);
    }
```

For BSD:

```
    public String toString() {
        return Integer.toString(thread_id);
    }
```

For Windows:

```
  public String toString() {
    return Long.toString(getThreadID());
  }

  /** Retrieves the thread ID of this thread by examining the Thread
      Information Block. */
  private long getThreadID() {
    if (!gotID) {
       id = debugger.getThreadIdFromSysId(sysId);
       gotID = true;
    }

    return id;
  }
```

I'm not sure why it is done this way. Note I introduced nothing new with how clhsdb deals with Thread IDs when I added the threadcontext comment. The following commands can all run into this issue:

- dumpreplaydata
- dumpideal
- dumpcfg
- dumpilt
- where
- thread
- threads (which prints the thread id so you can pass it to other commands)

So this is an old issue. If you want I can file a separate CR for it. I don't think it makes any sense to address it as part of this bug fix.

**Comment by dholmes-ora** [comment]
It may be an old issue but if we're using the wrong/inappropriate thread id and that is what causes the current bug then it does seem very pertinent to this PR. For a single "session" it doesn't matter which is used but if you want an id that is valid across sessions then seems we should be using the system id.

**Comment by plummercj** [comment]
> It may be an old issue but if we're using the wrong/inappropriate thread id and that is what causes the current bug then it does seem very pertinent to this PR. For a single "session" it doesn't matter which is used but if you want an id that is valid across sessions then seems we should be using the system id.

Let me put it a different way. The thread ID issue an old bug that we are not going to address now (and likely not ever). This is a new test for a new command that is exposing the bug (there are other clhsdb commands that could have, but they are not testing in a sufficient manner to expose the bug). Therefore what makes sense now is to have the test work around the issue rather than fail.

**Comment by plummercj** [comment]
I filed [JDK-8280971](https://bugs.openjdk.java.net/browse/JDK-8280971) to address the issue of the changing thread IDs on Windows. I'd like to move forward with the workaround in this test. Otherwise it will be problem listed since it is causing too much noise.

**Review by sspitsyn — APPROVED** [review]
Looks okay to me.
Thanks,
Serguei

**Review by dholmes-ora — APPROVED** [review]
Ok.

**Comment by plummercj** [comment]
Thanks for the reviews David and Serguei!

**Pull request closed without merging**
