### PR TITLE
8344014: Simplify TracePhase constructor

### PR DESCRIPTION
**Pull request by tstuefe**
As a prerequisite for [JDK-8344009](https://bugs.openjdk.org/browse/JDK-8344009), `TracePhase` constructor needs to know the PhaseTraceId. And while we are at it, it can be simplified: trace strings can be kept in via x-macro with the IDs, and it is sufficient to pass in the IDs, no need to pass the pointer to the counters since we use the same counters anyway.

Since this is a somewhat invasive but purely mechanical change, I separate this work from [JDK-8344009](https://bugs.openjdk.org/browse/JDK-8344009).

There are no functional changes. Trace texts have been faithfully taken over, even in the case where the original TracePhase constructor invocation got fed an empty string (`_t_vector` and `_t_renumberLive`) - whether this was intentional or not, this patch does not change it.

The patch preserves the possibility to override the phase name with an explicit argument to the constructor. This is used in one existing case ("computeLive (sbplr)"), again, to faithfully preserve the log format.

Test: I checked manually with +CITimeVerbose with and without patch and compared the output; output format is preserved.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8344014](https://bugs.openjdk.org/browse/JDK-8344014): Simplify TracePhase constructor (**Enhancement** - P4)

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22029/head:pull/22029` \
`$ git checkout pull/22029`

Update a local copy of the PR: \
`$ git checkout pull/22029` \
`$ git pull https://git.openjdk.org/jdk.git pull/22029/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22029`

View PR using the GUI difftool: \
`$ git pr show -t 22029`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22029.diff">https://git.openjdk.org/jdk/pull/22029.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22029#issuecomment-2470582263)
</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Mac OS error unrelated.

**Comment by dean-long** [comment]
This looks OK, but doesn't seem strictly necessary for JDK-8344009.  We could get the PhaseTraceId from `accumulator - &Phase::timers[0]`.

**Review by dean-long — APPROVED** [review]

**Comment by tstuefe** [comment]
> This looks OK, but doesn't seem strictly necessary for JDK-8344009. We could get the PhaseTraceId from `accumulator - &Phase::timers[0]`.

I thought so too, but it seemed a bit ugly and brittle, and the simplification seemed worth it anyhow.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by tstuefe** [comment]
Thank you @dean-long and @rwestrel !

**Pull request closed without merging**
