### PR TITLE
8270869: G1ServiceThread may not terminate

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this fix of a rare race in G1ServiceThread termination that
can lead to the thread not terminating in a timely manner.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270869](https://bugs.openjdk.java.net/browse/JDK-8270869): G1ServiceThread may not terminate

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer) ⚠️ Review applies to e065a5150968e46659e76ec0583253eae3b74b00
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to e065a5150968e46659e76ec0583253eae3b74b00

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4819/head:pull/4819` \
`$ git checkout pull/4819`

Update a local copy of the PR: \
`$ git checkout pull/4819` \
`$ git pull https://git.openjdk.java.net/jdk pull/4819/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4819`

View PR using the GUI difftool: \
`$ git pr show -t 4819`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4819.diff">https://git.openjdk.java.net/jdk/pull/4819.diff</a>

</details>

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]
Only a minor comment on the style; I think not using `else-if` is clearer: the early-return handles the exiting condition, and the other two cases depend on the task queue state.

**Review by tschatzl — APPROVED** [review]
Looks good, same comment about the use of the `else if`, but I'm good either way.

**Comment by kimbarrett** [comment]
> Looks good, same comment about the use of the `else if`, but I'm good either way.

I think that looks weird; the if-ladder covers all cases, and splitting it up makes that seem less obvious to me.  Also, if I were to split it up I would probably write the exiting case as
`if (should_terminate()) return;`
which I know Thomas has a preference against.

**Pull request closed without merging**
