### PR TITLE
8264881: Remove the old development option MemProfiling

### PR DESCRIPTION
**Pull request by kelthuzadx**
MemProfiler is a very old development option added at:

^As 00018/00000/00000
^Ad D 1.1 98/04/14 13:18:32 renes 1 0
^Ac date and time created 98/04/14 13:18:32 by renes
^Ae

Today it doesn't work because it is untested and there is no reason/scenario to prove it is useful.

After a short discussion in https://github.com/openjdk/jdk/pull/3340, I'd like to propose removing the memprofiler if there are no strong objections.

Thanks!
Yang

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264881](https://bugs.openjdk.java.net/browse/JDK-8264881): Remove the old development option MemProfiling

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3393/head:pull/3393` \
`$ git checkout pull/3393`

Update a local copy of the PR: \
`$ git checkout pull/3393` \
`$ git pull https://git.openjdk.java.net/jdk pull/3393/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3393`

View PR using the GUI difftool: \
`$ git pr show -t 3393`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3393.diff">https://git.openjdk.java.net/jdk/pull/3393.diff</a>

</details>

### CODE REVIEW

**Comment by kelthuzadx** [comment]
Gentle query: I do find another three product options(UseNewCode\d) that do nothing, they have been added in JDK6 as initial load commit(Maybe early). Does anyone know what's the intention of adding these options? Is it reasonable to remove them now?

**Review by dholmes-ora — APPROVED** [review]
Hi Yi,

Actual code removal looks good. 

Thanks,
David

**Comment by kelthuzadx** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@openjdk.java.net):_
> 
> On 8/04/2021 1:51 pm, Yi Yang wrote:
> 
> > On Thu, 8 Apr 2021 03:19:21 GMT, Yi Yang <yyang at openjdk.org> wrote:
> > > MemProfiler is a very old development option added at:
> > > ^As 00018/00000/00000
> > > ^Ad D 1.1 98/04/14 13:18:32 renes 1 0
> > > ^Ac date and time created 98/04/14 13:18:32 by renes
> > > ^Ae
> > > Today it doesn't work because it is untested and there is no reason/scenario to prove it is useful.
> > > After a short discussion in https://github.com/[/pull/3340](https://github.com/openjdk/jdk/pull/3340), I'd like to propose removing the memprofiler if there are no strong objections.
> > > Thanks!
> > > Yang
> > 
> > 
> > Gentle query: I do find another three product options(UseNewCode\d) that do nothing, they have been added in JDK6 as initial load commit(Maybe early). Does anyone know what's the intention of adding these options? Is it reasonable to remove them now?
> 
> The UseNewCode flags are there as a development aid so that you can
> conditionally enable changed logic during development without needing to
> add a new runtime flag just for that. It can be very useful for gating
> changes when doing performance runs. No code ever gets committed that
> actually uses them though.
> 
> So no, please do not delete them. :)
> 
> Thanks,
> David

Got it. Thank you David, you are the OpenJDK encyclopedia. :)

**Review by coleenp — APPROVED** [review]
Thank you for finding and removing this code.

**Comment by kelthuzadx** [comment]
Hi @dholmes-ora , how about my latest update? If you think it's okay, I would like to integrate it.

**Comment by kelthuzadx** [comment]
Thanks @dholmes-ora @coleenp for the review.

/integrate

**Review by shipilev — APPROVED** [review]
Looks fine to me as well.

**Pull request closed without merging**
