### PR TITLE
8311162: Simplify and modernize equals and hashCode for java.net

### PR DESCRIPTION
**Pull request by pavelrappo**
Please review this PR to use modern APIs and language features to simplify `equals` and `hashCode` for the java.net package.

Note, in NetworkInterface we could do even more and change this:

        for (InetAddress thisAddr : this.addrs) {
            boolean found = false;
            for (InetAddress thatAddr : that.addrs) {
                if (thisAddr.equals(thatAddr)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                return false;
            }
        }
        return true;

to this:

        return Set.of(that.addrs).containsAll(Set.of(this.addrs));

But arguably, the first option is already better enough than what was there before.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311162](https://bugs.openjdk.org/browse/JDK-8311162): Simplify and modernize equals and hashCode for java.net (**Bug** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Michael McMahon](https://openjdk.org/census#michaelm) (@Michael-Mc-Mahon - **Reviewer**)
 * [Mark Sheppard](https://openjdk.org/census#msheppar) (@msheppar - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14726/head:pull/14726` \
`$ git checkout pull/14726`

Update a local copy of the PR: \
`$ git checkout pull/14726` \
`$ git pull https://git.openjdk.org/jdk.git pull/14726/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14726`

View PR using the GUI difftool: \
`$ git pr show -t 14726`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14726.diff">https://git.openjdk.org/jdk/pull/14726.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14726#issuecomment-1614394168)

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM - please run either `tier2` or `:jdk_net` before integrating.

**Comment by dfuch** [comment]
> ```return Set.of(that.addrs).containsAll(Set.of(this.addrs));```

Since it's been checked before that the arrays have the same length it could even be:
```
    return Set.of(that.addrs).equals(Set.of(this.addrs));
```

but your proposed changes are already good enough.

**Review by Michael-Mc-Mahon — APPROVED** [review]
The change looks good to me, per the webrev

**Comment by msheppar** [comment]
For NetworkInterface the non Set version is more straight forward and clearer, Set intersection is a little arcane
Not sure it is possible to assign the same IP address multiple times to an interface, maybe an IPv6 with different scope ids? but I think not.

**Comment by pavelrappo** [comment]
> For NetworkInterface the non Set version is more straight forward and clearer, Set intersection is a little arcane
> Not sure it is possible to assign the same IP address multiple times to an interface, maybe an IPv6 with different scope ids? but I think not.

After eliminating indexes from the loops, they certainly look cleaner: prior to this change, the loops might have given an impression that there was some sort of element matching (correlating by index), which there wasn't. My personal rule of thumb is this: avoid indexing if it's only used to access the *next* element in the iteration.

That said, I'm a bit surprised that you find set equality (not a subset test, but an equality test, as we discussed with @dfuch in this PR) to be more arcane than nested loops.

Anyway, the testing has shown no issues, so unless there is anything else, I'll integrate it shortly.

**Comment by msheppar** [comment]
right so, well that aside, one could consider the overhead in instantiating the Sets !!
What also stands out wrt NetworkInterface::equals is a perceived anomaly that when available the MAC address is not considered part of the "equation"

**Review by msheppar — APPROVED** [review]
good job!

**Pull request closed without merging**
