### PR TITLE
8259048: (tz) Upgrade time-zone data to tzdata2020f

### PR DESCRIPTION
**Pull request by kiranoracle**
Hi Guys,

Updating the summary as tzdata2020f is available and includes tzdata2020e changes also.

Please review the integration of tzdata2020f to JDK.

Details regarding the change can be viewed at - https://mm.icann.org/pipermail/tz-announce/2020-December/000064.html
Bug: https://bugs.openjdk.java.net/browse/JDK-8259048

tzdata2020e - Most of the changes are about correcting past timestamps and Australia/Currie timezone is removed.
tzdata2020f - No changes to the data since 2020e.

Regression Tests pass along with JCK.

Please let me know if the changes are good to push.

Thanks,
Kiran

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259048](https://bugs.openjdk.java.net/browse/JDK-8259048): (tz) Upgrade time-zone data to tzdata2020f

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to a89ac891a8fea8a4907b9736b8937a3ceb3bf535

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1937/head:pull/1937`
`$ git checkout pull/1937`

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
Looks good.
IIUC, 2020f is already out, and the 2020e-2020f diff does not seem to include any data change. Would you change this PR to incorporate 2020f?

**Review by erikj79 — APPROVED** [review]

**Comment by kiranoracle** [comment]
> Looks good.
> IIUC, 2020f is already out, and the 2020e-2020f diff does not seem to include any data change. Would you change this PR to incorporate 2020f?

Hi @naotoj ,

I have updated the VERSION and PR title to incorporate tzdata2020f, please let me know if the changes are good to push.

**Review by naotoj — APPROVED** [review]

**Pull request closed without merging**
