### PR TITLE
8255546: Missing coverage for javax.smartcardio.CardPermission and ResponseAPDU

### PR DESCRIPTION
**Pull request by fguallini**
This patch is to add code coverage to the following methods
- javax.smartcardio.CardPermission::**implies** (1)
- javax.smartcardio.ResponseAPDU::**toString** (2)

Tests are added following the expected implementation given in the methods specifications

(1) https://github.com/openjdk/jdk/blob/5dfb42fc68099278cbc98e25fb8a91fd957c12e2/src/java.smartcardio/share/classes/javax/smartcardio/CardPermission.java#L214-L229

(2) https://github.com/openjdk/jdk/blob/5dfb42fc68099278cbc98e25fb8a91fd957c12e2/src/java.smartcardio/share/classes/javax/smartcardio/ResponseAPDU.java#L141-L149

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255546](https://bugs.openjdk.java.net/browse/JDK-8255546): Missing coverage for javax.smartcardio.CardPermission and ResponseAPDU

### Reviewers
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1092/head:pull/1092`
`$ git checkout pull/1092`

### CODE REVIEW

**Comment by fguallini** [comment]
> _Mailing list message from [sibabrata.sahoo at oracle.com](mailto:sibabrata.sahoo@oracle.com) on [security-dev](mailto:security-dev@openjdk.java.net):_
> 
> So you have converted the Test to use JUnit other than adding few new Test cases.
> 
> It looks fine to me.
> 
> Thanks,
> Siba

Hi Siba,
Tests were converted to Testng and coverage for CardPermission::implies and ResponseAPDU::toString was added. Thank you for reviewing

**Review by XueleiFan — APPROVED** [review]

**Pull request closed without merging**
