### PR TITLE
8318051: Duration.between uses exceptions for control flow

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
The existing logic uses nanosecond arithmetic to compute Duration.between. Since that can overflow for durations greater than 292 years, it has a try/catch that falls back to computing the seconds part and adjusting that for nanoseconds. However, exception handling is typically very expensive, so in cases like the one in the linked bug this method was a performance trap.

The new logic is essentially the old catch block. It needs a special case for when the number of seconds is 0, so it is slightly slower in that case. But in other cases it is probably somewhat faster, because it avoids a [division](https://github.com/openjdk/jdk/blob/8d9a4b43f4fff30fd217dab2c224e641cb913c18/src/java.base/share/classes/java/time/Duration.java#L283) and associated mod.

The test coverage in [`TCKDuration`](https://github.com/openjdk/jdk/blob/8d9a4b43f4fff30fd217dab2c224e641cb913c18/test/jdk/java/time/tck/java/time/TCKDuration.java#L780) is already very thorough so no new tests are needed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318051](https://bugs.openjdk.org/browse/JDK-8318051): Duration.between uses exceptions for control flow (**Bug** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16318/head:pull/16318` \
`$ git checkout pull/16318`

Update a local copy of the PR: \
`$ git checkout pull/16318` \
`$ git pull https://git.openjdk.org/jdk.git pull/16318/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16318`

View PR using the GUI difftool: \
`$ git pr show -t 16318`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16318.diff">https://git.openjdk.org/jdk/pull/16318.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16318#issuecomment-1775696058)

### CODE REVIEW

**Comment by RogerRiggs** [comment]
Did you identify an existing test that reproduces your initial issue case?
`Duration.between(instant, Instant.MAX).compareTo(duration) < 0`

Otherwise, looks good

**Comment by eamonnmcmanus** [comment]
Yes, what I tried was just removing the catch-block from the existing code and verifying that `TCKDuration` fails with `ArithmeticException`. It calls `between` on `Instant` values that are 500 years apart, which is enough to trigger nanosecond overflow. So both the original `try` and the original `catch` are tested.

**Review by RogerRiggs — APPROVED** [review]
Thanks for the fix and confirming the test.

**Pull request closed without merging**
