### PR TITLE
8304696: Duplicate class names in dynamicArchive tests can lead to test failure

### PR DESCRIPTION
**Pull request by calvinccheung**
To avoid duplicate class name `MyShutdown`, the fix is to change the `MyShutdown` class name for the LambdaProxyDuringShutdown.java test to `ShutdownHelper`.

Tested manually by running the LInkClassTest.java and LambdaProxyDuringShutdown.java tests serially on linux-x64.
Also ran tiers 1 and 3 testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304696](https://bugs.openjdk.org/browse/JDK-8304696): Duplicate class names in dynamicArchive tests can lead to test failure

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13542/head:pull/13542` \
`$ git checkout pull/13542`

Update a local copy of the PR: \
`$ git checkout pull/13542` \
`$ git pull https://git.openjdk.org/jdk.git pull/13542/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13542`

View PR using the GUI difftool: \
`$ git pr show -t 13542`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13542.diff">https://git.openjdk.org/jdk/pull/13542.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13542#issuecomment-1515092346)

### CODE REVIEW

**Comment by iklam** [comment]
I think it's better to restructure the test classes to avoid having the same problem in the future -- classes with generic names that appear in multiple, unrelated test cases.

In this particular case, we have both LinkClassApp.java and LambdaProxyDuringShutdownApp.java that contain two different implementation of a class with the same name, MyShutdown.

I would suggest putting the small, generic classes as static inner classes. E.g.,

```
public class LinkClassApp.java {
    static class MyShutdown { ... }
    static class Outer { ...}
}
```

Then, the test cases can refer to this class using a unique name, like

```
@run driver jdk.test.lib.helpers.ClassFileInstaller -jar lambda_proxy_shutdown.jar ....
             LambdaProxyDuringShutdownApp$MyShutdown ....
```

LinkClassApp.java (and perhaps some more test classes) should also be restructured similarly.

Thanks

**Comment by calvinccheung** [comment]
I've made changes to the LinkClassTest.java and LinkClassApp.java as you suggested.
However, I can't make similar changes to the LambdaProxyDuringShutdownApp.java because it will not work with the original intention of the test. In particular:
```
                // Only the nest host (Outer) and the Inner class are loaded
                // from the dynamic archive.
                // The lambda proxy is not loaded from the dynamic archive.
```
So I reverted the changes to my original webrev.

**Review by iklam — APPROVED** [review]
Looks good to me.

**Comment by calvinccheung** [comment]
Thanks @iklam for the review.
/integrate

**Pull request closed without merging**
