### PR TITLE
8286093: java/awt/geom/Path2D/UnitTest.java failed with "RuntimeException: 2D bounds too small"

### PR DESCRIPTION
**Pull request by mickleness**
This resolves an occasional unit test failure in Path2D.UnitTest.

The previous Path2D#getBounds2D(PathIterator) implementation assumed that after a SEG_CLOSE the next segment would always be a SEG_MOVETO to start a new clearly defined segment. But the Path2D.UnitTest created random paths that didn't follow this expectation.

This commit updates #getBounds2D(PathIterator) so it will move the cursor back to the (moveX, moveY) point for the sake of calculating future segments. This appears to resolve the unit test failures.

This commit also modifies the unit test so it logs random seeds. This may help developers isolate/reproduce specific failures with more certainty.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286093](https://bugs.openjdk.java.net/browse/JDK-8286093): java/awt/geom/Path2D/UnitTest.java failed with "RuntimeException: 2D bounds too small"

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to [88346f4d](https://git.openjdk.java.net/jdk/pull/8828/files/88346f4df39e06b51f14c25b59e565b13ea4062a)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8828/head:pull/8828` \
`$ git checkout pull/8828`

Update a local copy of the PR: \
`$ git checkout pull/8828` \
`$ git pull https://git.openjdk.java.net/jdk pull/8828/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8828`

View PR using the GUI difftool: \
`$ git pr show -t 8828`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8828.diff">https://git.openjdk.java.net/jdk/pull/8828.diff</a>

</details>

### CODE REVIEW

**Comment by bourgesl** [comment]
A general comment from an openjdk comitter, not reviewer:
It looks overall good, I would have named moveX/Y as startX/Y, as usual.

Should we test closed paths and non-closed paths to ensure bounds2d is correct in both case ? Maybe it is already the case.

Congratulations,
Laurent

**Review by prrace — APPROVED** [review]
I ran our full battery of automated tests and results look good.

**Comment by mickleness** [comment]
I just realized there's an explicit openJDK ticket for these failures ( https://bugs.openjdk.java.net/browse/JDK-8286093 ). Should I... close this PR and open a new one? Simply rename this one? (Or my favorite: do nothing?)

**Comment by prrace** [comment]
Oh, I hadn't noticed. yes you will need to fix this, the tooling won't let you re-use the same id (I hope!)
there's a /issue command which should work for this.

**Comment by prrace** [comment]
Seems I can't change this for you - maybe because you didn't check the option to allow other committers to edit the PR ?
So you will need to fix it yourself.

**Pull request closed without merging**
