### PR TITLE
8317257: RISC-V: llvm build broken

### PR DESCRIPTION
**Pull request by VladimirKempik**
Please review this small fix to make hotspot compilable with clang on risc-v.
It supposed to fix next error:
```
/home/user/openjdk/jdk/src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp:1518:10: error: call to member function 'null_check' is ambiguous
      __ null_check(obj);
      ~~~^~~~~~~~~~
/home/user/openjdk/jdk/src/hotspot/cpu/riscv/macroAssembler_riscv.hpp:238:16: note: candidate function
  virtual void null_check(Register reg, int offset = -1);
               ^
/home/user/openjdk/jdk/src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.hpp:109:8: note: candidate function
  void null_check(Register r, Label *Lnull = nullptr) { MacroAssembler::null_check(r); }
       ^
1 error generated.
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317257](https://bugs.openjdk.org/browse/JDK-8317257): RISC-V: llvm build broken (**Bug** - P3)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15965/head:pull/15965` \
`$ git checkout pull/15965`

Update a local copy of the PR: \
`$ git checkout pull/15965` \
`$ git pull https://git.openjdk.org/jdk.git pull/15965/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15965`

View PR using the GUI difftool: \
`$ git pr show -t 15965`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15965.diff">https://git.openjdk.org/jdk/pull/15965.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15965#issuecomment-1739597628)

### CODE REVIEW

**Comment by RealFYang** [comment]
I see this was once introduced by https://bugs.openjdk.org/browse/JDK-8278479. Maybe align with aarch64 by using: `__ null_check(obj, -1);` ?

**Comment by VladimirKempik** [comment]
Thanks for taking a look, also fixed some static_assert being without message, it's c++17 only feature according to clang error

**Review by RealFYang — APPROVED** [review]
Updated change LGTM. Thanks.

**Pull request closed without merging**
