### PR TITLE
8334653: ISO 4217 Amendment 177 Update

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
Please review this PR, which is a backport of commit [86b0cf25](https://github.com/openjdk/jdk/commit/86b0cf259fb3cbe3a1973151148e5d36c6a99d91) from the [openjdk/jdk](https://git.openjdk.org/jdk) mainline branch.

This change incorporates the ISO 4217 Amendment 177 Update.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334653](https://bugs.openjdk.org/browse/JDK-8334653): ISO 4217 Amendment 177 Update (**Bug** - P3)

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20126/head:pull/20126` \
`$ git checkout pull/20126`

Update a local copy of the PR: \
`$ git checkout pull/20126` \
`$ git pull https://git.openjdk.org/jdk.git pull/20126/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20126`

View PR using the GUI difftool: \
`$ git pr show -t 20126`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20126.diff">https://git.openjdk.org/jdk/pull/20126.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20126#issuecomment-2221620145)

### CODE REVIEW

**Review by naotoj — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by Kboxoxx** [comment]
> @justin-curtis-lu This change now passes all _automated_ pre-integration checks.
> 
> ℹ️ This project also has non-automated pre-integration requirements. Please see the file [CONTRIBUTING.md](https://github.com/openjdk/jdk/blob/jdk23/CONTRIBUTING.md) for details.
> 
> After integration, the commit message for the final commit will be:
> 
> ```
> 8334653: ISO 4217 Amendment 177 Update
> 
> Reviewed-by: naoto, iris
> ```
> 
> You can use [pull request commands](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands) such as [/summary](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/summary), [/contributor](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/contributor) and [/issue](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/issue) to adjust it as needed.
> 
> At the time when this comment was updated there had been 4 new commits pushed to the `jdk23` branch:
> 
> * [9620b91](https://github.com/openjdk/jdk/commit/9620b912dd4be0b5c7440d0f9a0d8456e2ad1cd7): 8333884: MemorySegment::reinterpret removes read-only property
> * [e991c0f](https://github.com/openjdk/jdk/commit/e991c0f921768debdb8cb849acd5006ce81c989a): 8335766: Switch case with pattern matching and guard clause compiles inconsistently
> * [6720685](https://github.com/openjdk/jdk/commit/6720685abdc1c91f5083255782810cdb2d7d72f4): 8335966: Remove incorrect problem listing of java/lang/instrument/NativeMethodPrefixAgent.java in ProblemList-Virtual.txt
> * [4aab58b](https://github.com/openjdk/jdk/commit/4aab58be4aa1bbe848084189b467d0c586a4ffbb): 8335637: Add explicit non-null return value expectations to Object.toString()
> 
> Please see [this link](https://git.openjdk.org/jdk/compare/5b9ecb178667e373a834b241b8f8c8a13cef3b4d...jdk23) for an up-to-date comparison between the source branch of this pull request and the `jdk23` branch. As there are no conflicts, your changes will automatically be rebased on top of these commits when integrating. If you prefer to avoid this automatic rebasing, please check the documentation for the [/integrate](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/integrate) command for further details.
> 
> ➡️ To integrate this PR with the above commit message to the `jdk23` branch, type [/integrate](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/integrate) in a new comment.

**Comment by turbanoff** [comment]
>Please review this PR, which is a backport of commit [86b0cf25](https://github.com/openjdk/jdk/commit/86b0cf259fb3cbe3a1973151148e5d36c6a99d91) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

This message is kind of confusing. It's is `openjdk/jdk` repository too.

**Comment by justin-curtis-lu** [comment]
@turbanoff true, I adjusted the message to indicate the original commit is from mainline.

**Pull request closed without merging**
