### PR TITLE
8299380: conflict assert definitions

### PR DESCRIPTION
**Pull request by XueleiFan**
May I have this code cleanup reviewed?

The following failure occurs while building on MacOS M1:

```
In file included from /Users/xueleifan/workspace/jdk-dev/test/hotspot/gtest/jfr/test_networkUtilization.cpp:222:
/Users/xueleifan/workspace/jdk-dev/src/hotspot/share/jfr/periodic/jfrNetworkUtilization.cpp:59:25: error: too many arguments provided to function-like macro invocation
  assert(iface != NULL, "invariant");
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/assert.h:98:9: note: macro 'assert' defined here
#define assert(e) \
        ^
```
The assert() function used in jfrNetworkUtilization.cpp is conflicted with the assert definition in Xcode.  Alternatively, vmassert() could be used instead per the assert() definition in [hotspot](src/hotspot/share/utilities/debug.hpp).
```
// Note: message says "assert" rather than "vmassert" for backward
// compatibility with tools that parse/match the message text.
```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299380](https://bugs.openjdk.org/browse/JDK-8299380): conflict assert definitions

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11792/head:pull/11792` \
`$ git checkout pull/11792`

Update a local copy of the PR: \
`$ git checkout pull/11792` \
`$ git pull https://git.openjdk.org/jdk pull/11792/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11792`

View PR using the GUI difftool: \
`$ git pr show -t 11792`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11792.diff">https://git.openjdk.org/jdk/pull/11792.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
My building on Mac M1 works fine.

So may I ask how to reproduce this bug?
Thanks.

**Comment by XueleiFan** [comment]
> My building on Mac M1 works fine.
> 
> So may I ask how to reproduce this bug? Thanks.

Did you enable googletest?  I run into the problem when googletest is enabled.

**Comment by DamonFool** [comment]
> > My building on Mac M1 works fine.
> > So may I ask how to reproduce this bug? Thanks.
> 
> Did you enable googletest? I run into the problem when googletest is enabled.

Yes, the `gtest:all` passed on my m1.
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   gtest:all/server                                    952   952     0     0   
==============================
TEST SUCCESS
```

**Comment by XueleiFan** [comment]
> > > My building on Mac M1 works fine.
> > > So may I ask how to reproduce this bug? Thanks.
> > 
> > 
> > Did you enable googletest? I run into the problem when googletest is enabled.
> 
> Yes, the `gtest:all` passed on my m1.
> 
> ```
> ==============================
> Test summary
> ==============================
>    TEST                                              TOTAL  PASS  FAIL ERROR   
>    gtest:all/server                                    952   952     0     0   
> ==============================
> TEST SUCCESS
> ```
Did you use "--disable-warnings-as-errors" options while configuation?  Here is my configuration for the build (googletest is version 1.8.1):

$ bash configure --with-jtreg=.../jtreg --with-gtest=.../googletest

**Comment by DamonFool** [comment]
> The XCode version may be also related, I'm not very sure.

Okay.
My XCode is MacOSX12.0.sdk.

This kind of `assert(condition, msg)` is widely used in `test/hotspot/gtest`.

Why the errors only occur in `test/hotspot/gtest/jfr/test_networkUtilization.cpp`?

**Comment by XueleiFan** [comment]
> Why the errors only occur in `test/hotspot/gtest/jfr/test_networkUtilization.cpp`?

I think it is related to the C including files parsing sequences, but I'm not sure which file make it wrong.

**Comment by DamonFool** [comment]
> > Why the errors only occur in `test/hotspot/gtest/jfr/test_networkUtilization.cpp`?
> 
> I think it is related to the C including files parsing sequences, but I'm not sure which file makes it wrong.

So this seems to be a compiler toolchain bug?

**Comment by XueleiFan** [comment]
> So this seems to be a compiler toolchain bug?

The including file parsing sequences could be complicated, I think. 

For historic reason, there are a lot of use of the assert macro with 2+ parameters.  Basically, assert is a name defined and used in ANSI C.  The name should not be re-defined for other forms and purpose.  As suggested in the definition of the 2+ parameters, vmassert() should be used.

**Comment by dholmes-ora** [comment]
Please see [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254)

**Comment by XueleiFan** [comment]
> Please see [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254)

Thank you for the reference.  I think JDK-8299254 will address the issue, and I would like to close this PR and bug out.

**Pull request closed without merging**
