### PR TITLE
8284093: Memory leak: X11SD_DisposeXImage should also free obdata

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this small patch to fix leaking `XShmSegmentInfo` that is attached to `XImage`. 

Test:

- [x] jdk_2d

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284093](https://bugs.openjdk.java.net/browse/JDK-8284093): Memory leak: X11SD_DisposeXImage should also free obdata

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8060/head:pull/8060` \
`$ git checkout pull/8060`

Update a local copy of the PR: \
`$ git checkout pull/8060` \
`$ git pull https://git.openjdk.java.net/jdk pull/8060/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8060`

View PR using the GUI difftool: \
`$ git pr show -t 8060`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8060.diff">https://git.openjdk.java.net/jdk/pull/8060.diff</a>

</details>

### CODE REVIEW

**Comment by zhengyu123** [comment]
> Looks like X11SD_DropSharedSegment doesn't free this .. so this seems needed. But be sure to run X11 testing that will exercise the code path to verify no surprises before this is pushed

Thanks for the review, @prrace

I ran jdk_2d tests on Linux. Could you suggest any other tests I should run before push?

**Comment by zhengyu123** [comment]
Friendly ping!

May I have a second review?

Thanks

**Comment by neugens** [comment]
I'm not officially a reviewer but afaik there isn't any other place where the obdata is freed, and X11SD_DropSharedSegment doesn't do it, so we probably need to do it there. Since obdata is malloced in X11SD_CreateSharedImage, it seems correct to free it in X11SD_DisposeXImage (instead of directly within X11SD_DropSharedSegment), so the patch looks good to me.

**Review by gnu-andrew — APPROVED** [review]
This looks correct to me.

There is another similar block:
```
        if (xsdo->shmPMData.shmSegInfo != NULL) {
            X11SD_DropSharedSegment(xsdo->shmPMData.shmSegInfo);
            xsdo->shmPMData.shmSegInfo = NULL;
        }
```
But `xsdo->shmPMData.shmSegInfo` is assigned `img->obdata` in `X11SD_CreateSharedPixmap`, so looks like this is the one and only place to free this.

**Comment by zhengyu123** [comment]
Thanks, @neugens @gnu-andrew

**Pull request closed without merging**
