### PR TITLE
8273482: Remove "foreground work" concept from WorkGang

### PR DESCRIPTION
**Pull request by pliden**
JDK-8237354 introduced the concept of "foreground work" in WorkGang, as a special case for use by the HeapDumper. I propose that we remove this code, since this special use case can be solved without the need for the concept of "foreground work" in WorkGang.

As far as I can tell, there's no reason why it must be the VM thread that takes on the task of writing the header, iterating over roots, etc. So, in VM_HeapDumper::work(), instead of checking if the current thread is the VM thread we can just check if the worker_id is non-zero. That way, a single worker thread will take on the task of writing the header, iterating over roots, etc, and all other worker threads will continue to call worker_loop().

Testing:
 - Passed Tier1-3
 - Passed multiple runs of test/hotspot/jtreg/serviceability/dcmd/gc/
 - Manually ran jcmd GC.heap_dump with various GCs enabled

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273482](https://bugs.openjdk.java.net/browse/JDK-8273482): Remove "foreground work" concept from WorkGang

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 74ab4a073a81f008e54c74c6dd735f5b075c6be4
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 74ab4a073a81f008e54c74c6dd735f5b075c6be4

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5410/head:pull/5410` \
`$ git checkout pull/5410`

Update a local copy of the PR: \
`$ git checkout pull/5410` \
`$ git pull https://git.openjdk.java.net/jdk pull/5410/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5410`

View PR using the GUI difftool: \
`$ git pr show -t 5410`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5410.diff">https://git.openjdk.java.net/jdk/pull/5410.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm. Thanks a lot for looking into this.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by pliden** [comment]
Patch updated include the removal of a few asserts, as discussed here: http://mail.openjdk.java.net/pipermail/hotspot-gc-dev/2021-September/036807.html

**Comment by schmelter-sap** [comment]
The reason I've added this was, that for the shenandoah GC the heap iteration would run into assertions if not called from the VM thread. Maybe this has changed in the meantime.

**Comment by pliden** [comment]
> The reason I've added this was, that for the shenandoah GC the heap iteration would run into assertions if not called from the VM thread. Maybe this has changed in the meantime.

As mentioned in my previous comment. This PR removes those asserts since they were overly strict.

**Comment by pliden** [comment]
Thanks all for reviewing!

/integrate

**Pull request closed without merging**
