### PR TITLE
8265245: depChecker_<cpu> don't have any functionalities

### PR DESCRIPTION
**Pull request by kelthuzadx**
Yet another OpenJDK6 old guy.

src/hotspot/cpu/<cpu>/depChecker_<cpu>.hpp/cpp are included by src/hotspot/share/compiler/disassembler.cpp, they don't provide any functionality.

In the absence of strong demand either in existing ARCHs or future ARCHs, I think we can remove it.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265245](https://bugs.openjdk.java.net/browse/JDK-8265245): depChecker_<cpu> don't have any functionalities

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3531/head:pull/3531` \
`$ git checkout pull/3531`

Update a local copy of the PR: \
`$ git checkout pull/3531` \
`$ git pull https://git.openjdk.java.net/jdk pull/3531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3531`

View PR using the GUI difftool: \
`$ git pr show -t 3531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3531.diff">https://git.openjdk.java.net/jdk/pull/3531.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by neliasso — APPROVED** [review]
Nice cleanup. 

Approved.

**Comment by kelthuzadx** [comment]
Thanks @TobiHartmann and @neliasso for the reviews.

/integrate

**Pull request closed without merging**
