### PR TITLE
8256056: Deoptimization stub doesn't save vector registers on x86

### PR DESCRIPTION
**Pull request by iwanowww**
Deoptimization stub doesn't save vector registers on x86 and it may break vector rematerialization when a vector value (produced through Vector API) ends up in a register (and not spilled on stack).

The fix unconditionally saves all wide vector registers when going through deopt stub. If there are any performance concerns with that, it's possible to introduce a dedicated variant and choose between 2 versions when patching nmethods (like what happens with safepoint stubs). But deoptimization is already quite expensive to save much on that, so I decided to keep things as is.   

As a cleanup, I made `save_vectors` parameter explicit to make the intentions clearer.

Testing (with some other relevant patches):
- [x] jdk/incubator/vector w/ -XX:+DeoptimizeALot and -XX:UseAVX=3 on AVX512-capable hardware
- [x] hs-precheckin-comp, hs-tier1, hs-tier2

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (8/8 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8256056](https://bugs.openjdk.java.net/browse/JDK-8256056): Deoptimization stub doesn't save vector registers on x86

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1134/head:pull/1134`
`$ git checkout pull/1134`

### CODE REVIEW

**Comment by sviswa7** [comment]
If possible, it will be good to do this optionally.
Doing it unconditionally, the concern is the frequency drop with larger vector width.

**Comment by iwanowww** [comment]
> If possible, it will be good to do this optionally.
As I mentioned earlier, it's possible, but requires 2 variants of deopt stub and dispatching logic to choose proper one depeding on the location it is patched with. 

Deoptimization process is already expensive and execution ends up in interpreter anyway. 

Is the frequency drop such a problem in case of deopt stub to justify the increase in complexity?
Also, I'd like to point out that on older CPUs with AVX512 supported (like Skylake) AVX=3 is turned off by default to avoid generating EVEX-encoded instructions on CPUs which have frequency scaling issues. So, if AVX=3 is specified, there are already many places (which are more performance sensitive IMO) with EVEX-encoded instructions.

**Comment by sviswa7** [comment]
May be not. Let us go with your solution and we can revisit if the performance runs show otherwise.

**Review by cl4es — APPROVED** [review]
Looks OK - on my AVX=2-enabled test system the added overhead of the extra work during bootstrap is negligible (~16k instructions).

**Review by vnkozlov — COMMENTED** [review]
We did record that compiled code has wide vectors.
May be we need specialized depot stub for 512 bits vectors

**Comment by iwanowww** [comment]
> We did record that compiled code has wide vectors.
> May be we need specialized depot stub for 512 bits vectors

As we discussed with Sandhya, it is doable, but will introduce additional complexity. And benefits are not clear: deoptimization is far from performace critical.

I made an artificial experiment and composed a micro-benchmark which performs 100k deoptimizations in a row without triggering any recompilations. The results (on a Skylake server) are:
```
-XX:AVX              =3       =2      =0
save_vectors=OFF     4,6s     4,4s    4,4s
save_vectors=ON      5,5s     4,4s    4,4s
```
Saving full ZMM0-31 register state adds ~20% of execution time when continuously deoptimizing trivial method (just a single call), but when lazy deoptimization behaves normally (deoptimized code is thrown away along the way), there's basically no difference in scores because the time is spent in interpreter waiting for recompiled code to arrive.

**Review by vnkozlov — APPROVED** [review]
Okay.

**Comment by iwanowww** [comment]
Thanks for the reviews, Claes and Vladimir.

**Pull request closed without merging**
