### PR TITLE
8340540: Problemlist DcmdMBeanPermissionsTest.java and SystemDumpMapTest.java

### PR DESCRIPTION
**Pull request by tstuefe**
Quick problemlisting. Thank you.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340540](https://bugs.openjdk.org/browse/JDK-8340540): Problemlist DcmdMBeanPermissionsTest.java and SystemDumpMapTest.java (**Sub-task** - P4)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21109/head:pull/21109` \
`$ git checkout pull/21109`

Update a local copy of the PR: \
`$ git checkout pull/21109` \
`$ git pull https://git.openjdk.org/jdk.git pull/21109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21109`

View PR using the GUI difftool: \
`$ git pr show -t 21109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21109.diff">https://git.openjdk.org/jdk/pull/21109.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Ping @kevinjwalls

**Comment by kevinjwalls** [comment]
Thanks.  Are you OK to create a subtask of 8340401 for this problemlisting, so we keep 8340401 for the real follow on fix.
8340401 appears in the problem list entry, that's good.

**Comment by tstuefe** [comment]
> Thanks. Are you OK to create a subtask of 8340401 for this problemlisting, so we keep 8340401 for the real follow on fix. 8340401 appears in the problem list entry, that's good.

Good catch. I thought that's what I did, but got confused mid flight. This should be right.

**Review by kevinjwalls — APPROVED** [review]
Thanks, all good for a trivial problemlisting.
We'll be back here again soon probably!

**Comment by tstuefe** [comment]
Thanks @kevinjwalls !

/integrate

**Pull request closed without merging**
