### PR TITLE
JDK-8295710 : remove os::dll_file_extension

### PR DESCRIPTION
**Pull request by MBaesken**
The os::dll_file_extension() function could be unified for the different OS platforms.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295710](https://bugs.openjdk.org/browse/JDK-8295710): remove os::dll_file_extension

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10782/head:pull/10782` \
`$ git checkout pull/10782`

Update a local copy of the PR: \
`$ git checkout pull/10782` \
`$ git pull https://git.openjdk.org/jdk pull/10782/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10782`

View PR using the GUI difftool: \
`$ git pr show -t 10782`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10782.diff">https://git.openjdk.org/jdk/pull/10782.diff</a>

</details>

### CODE REVIEW

**Comment by MBaesken** [comment]
Hi David, yes we can remove  os::dll_file_extension ; I adjusted the change.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
You need to remove it from ./share/runtime/os.hpp too. Thanks.

**Comment by MBaesken** [comment]
Hi David, I removed dll_file_extension() from os.hpp .

**Review by dholmes-ora — APPROVED** [review]
Looks good.

But could you update the JBS issue/title to indicate it is now removed not unified.

Thanks.

**Review by TheRealMDoerr — APPROVED** [review]
Nice cleanup! LGTM. Yeah, describing that you remove it in the JBS issue makes sense.

**Review by RealLucy — APPROVED** [review]
LGTM.
Thank you for unifying. I like the fact that knowledge about the dynamic library extension is now stored at exactly one place.

**Comment by MBaesken** [comment]
Hi David, Lutz and Martin, thanks for the reviews !

**Pull request closed without merging**
