### PR TITLE
8294403: [REDO] make test should report only on executed tests

### PR DESCRIPTION
**Pull request by shipilev**
This should help to speed up tests significantly. Currently, if we run "make test" with a subset of tests, JTReg would still read the entirety of test root to report on tests that were not run. Even with current suite of tests it gets expensive. If you add more tests to suite -- for example, mounting a large test archive like pre-generated fuzzer tests -- it starts to take a lot of time.

The reasonable default for older jtreg is `-report:executed`. My own CI -- that has millions of tests mounted in `test/` -- was running with `JTREG="OPTIONS=-report:executed"` for years now. [CODETOOLS-7903323](https://bugs.openjdk.org/browse/CODETOOLS-7903323) provides a new reporting option, `-report:files`, which makes this whole business easier. This requires new jtreg.

Motivational improvements:

```
$ time CONF=linux-x86_64-server-release make run-test TEST=gc/epsilon/TestHelloWorld.java

# Default JDK tree

# Baseline
real	0m9.086s
user	0m22.857s
sys	0m4.202s

# Patched
real	0m6.406s   ; +40% faster
user	0m17.156s
sys	0m3.193s

# +100K fuzzer tests in tree

# Baseline
real	3m1.997s
user	3m16.643s
sys	0m10.490s

# Patched
real	0m8.919s   ; 20x faster
user	0m17.904s
sys	0m4.860s
```

Additional testing:
 - [x] Ad-hoc timing tests (see above)
 - [x] Reproducer from [CODETOOLS-7903331](https://bugs.openjdk.org/browse/CODETOOLS-7903331)
 - [x] Eyeballing the test results on passing tests with REPEAT_COUNT > 1
 - [x] Eyeballing the test results on intermittently failing tests with RETRY_COUNT > 1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294403](https://bugs.openjdk.org/browse/JDK-8294403): [REDO] make test should report only on executed tests

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [a803958f](https://git.openjdk.org/jdk/pull/11824/files/a803958f1af3551ac71f9fb3e8c28f31335eb146)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [a803958f](https://git.openjdk.org/jdk/pull/11824/files/a803958f1af3551ac71f9fb3e8c28f31335eb146)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11824/head:pull/11824` \
`$ git checkout pull/11824`

Update a local copy of the PR: \
`$ git checkout pull/11824` \
`$ git pull https://git.openjdk.org/jdk pull/11824/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11824`

View PR using the GUI difftool: \
`$ git pr show -t 11824`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11824.diff">https://git.openjdk.org/jdk/pull/11824.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
This might need more exposure.

/label add hotspot
/label add core-libs

**Review by erikj79 — APPROVED** [review]
Looks good from a build point of view.

**Review by dholmes-ora — APPROVED** [review]
This seems fine to me. Thanks.

I personally always run with `-noreport`. :)

**Comment by shipilev** [comment]
> Please update the copyright years on the files before integrating.

Updated.

> I see that in the additional testing section you note, running tests with RETRY_COUNT. Is that intentional? Does retry count play a role in the report generation?

The logic for REPEAT/RETRY_COUNT merges the jtreg reports from "different" repeated runs. We have to check new reporting mode still produces sane results in that mode.

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
> > I see that in the additional testing section you note, running tests with RETRY_COUNT. Is that intentional? Does retry count play a role in the report generation?
> 
> The logic for REPEAT/RETRY_COUNT merges the jtreg reports from "different" repeated runs. We have to check new reporting mode still produces sane results in that mode.

Thank you for that detail, I wasn't aware of that.

**Review by djelinski — APPROVED** [review]
I like this!
```
$ time make run-test TEST=jdk/java/net/BindException/Test.java:

# baseline:
real    0m43.176s
user    0m12.453s
sys     1m13.797s
# patched:
real    0m22.558s
user    0m10.797s
sys     1m1.734s
```

**Comment by shipilev** [comment]
My longer testing passes well. I would like to integrate it soon, if there are no objections.

**Pull request closed without merging**
