### PR TITLE
8280915: Better parallelization for AbstractSpliterator and IteratorSpliterator when size is unknown

### PR DESCRIPTION
**Pull request by amaembo**
See the bug description for details.

I propose a simple solution. Let's allow ArraySpliterator to be non-SIZED and report artificial estimatedSize(), much bigger than the real one. This will allow AbstractSpliterator and IteratorSpliterator to produce prefix whose size is comparable to Long.MAX_VALUE (say, starting with Long.MAX_VALUE/2), and this will enable further splitting of the prefix. This change will drastically improve parallel streaming for affected streams of size <= 1024 and significantly improve for streams of size 1025..20000. The cost is higher-grained splitting for huge streams of unknown size. This might add a minor overhead for such scenarios which, I believe, is completely tolerable.

No public API changes are necessary, sequential processing should not be affected, except an extra field in ArraySpliterator which increases a footprint by 8 bytes.

I added a simple test using an artificial collector to ensure that at least two non-empty parts are created when parallelizing Stream.iterate source. More testing ideas are welcome.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280915](https://bugs.openjdk.java.net/browse/JDK-8280915): Better parallelization for AbstractSpliterator and IteratorSpliterator when size is unknown

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7279/head:pull/7279` \
`$ git checkout pull/7279`

Update a local copy of the PR: \
`$ git checkout pull/7279` \
`$ git pull https://git.openjdk.java.net/jdk pull/7279/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7279`

View PR using the GUI difftool: \
`$ git pr show -t 7279`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7279.diff">https://git.openjdk.java.net/jdk/pull/7279.diff</a>

</details>

### CODE REVIEW

**Comment by amaembo** [comment]
I added a microbenchmark to demonstrate the speed improvement achievable by this patch. For demonstration, I used `Pattern.splitAsStream` source (though as listed in JDK-8280915, many other standard sources are also affected). For downstream operation I selected `BigInteger.pow(1000)` which is moderately CPU-intensive (takes ~10us on my machine for input numbers within 1000..2000). The benchmarking results are as follows (my machine has 8 cores). Here's non-patched version:

```
Benchmark                  (size)  Mode  Cnt      Score      Error  Units
sumOf1000thPowers              10  avgt   30    100.367 ±    0.793  us/op
sumOf1000thPowers             100  avgt   30    963.857 ±    6.252  us/op
sumOf1000thPowers            1000  avgt   30  10012.923 ±   81.091  us/op
sumOf1000thPowers           10000  avgt   30  99546.370 ±  625.105  us/op
sumOf1000thPowersParallel      10  avgt   30    104.561 ±    1.118  us/op
sumOf1000thPowersParallel     100  avgt   30    995.400 ±   26.116  us/op
sumOf1000thPowersParallel    1000  avgt   30   9969.296 ±   85.166  us/op
sumOf1000thPowersParallel   10000  avgt   30  55856.516 ± 2315.530  us/op
```

We observe that the results depend on the input size linearly for sequential run, which is quite expected. Parallel doesn't help at all for size = 10, 100, and 1000, which validates my claim that these spliterators cannot split at all for sizes <= 1024. For size = 10000, parallel version starts performing somewhat better (1.78x), though it's not nearly close to the available machine parallelism.

Here's patched version:

```
Benchmark                  (size)  Mode  Cnt      Score      Error  Units
sumOf1000thPowers              10  avgt   30    101.380 ±    0.961  us/op
sumOf1000thPowers             100  avgt   30    970.843 ±    8.360  us/op
sumOf1000thPowers            1000  avgt   30   9837.397 ±   93.656  us/op
sumOf1000thPowers           10000  avgt   30  97741.823 ± 1276.116  us/op
sumOf1000thPowersParallel      10  avgt   30     41.597 ±    0.910  us/op
sumOf1000thPowersParallel     100  avgt   30    189.735 ±    1.911  us/op
sumOf1000thPowersParallel    1000  avgt   30   1776.337 ±   31.034  us/op
sumOf1000thPowersParallel   10000  avgt   30  17685.723 ±  127.846  us/op
```

We observe no regression for sequential run and drastic improvement for parallel. Even for size = 10, we see 2.46x speedup and 41 us total time. For bigger sizes, we see 5.11x..5.54x speedup.

Please review my patch. I'll be happy to discuss any concerns about this optimization you may have. Thanks in advance!

**Comment by PaulSandoz** [comment]
@amaembo It's on my queue to review, i may get to it tomorrow, otherwise next week.

**Comment by PaulSandoz** [comment]
> @amaembo It's on my queue to review, i may get to it tomorrow, otherwise next week.

I took last week off at short notice, since it was the school holidays. Looking today.

**Comment by PaulSandoz** [comment]
For unknown-sized iterators we have to bias towards some strategy (recognizing that the source is a poor choice for parallelism).

Currently the "peeled" split containing an array of elements (copied from the iterator) is never split, since the array length will never in practice be greater than the size threshold. The parallelism is derived from the splits of the iterator, and this is biased towards a large number of elements.

In your approach each  "peeled" split effectively gets to use half of the total parallelism. Over subsequent splits of the source that's gonna over provision tasks, specifically after two splits (or 2 * 2^10 + 2^10 elements), and this is biased towards a smaller number of elements.

In the issue you point out a number of relevant stream sources. In practice they are unlikely to have millions of elements, and probably more likely fitting into the first few steps of the arithmetic splitting sequence. If the cost-per-element is reasonably high that would overcome any over provisioning.

Overall it looks reasonable. I ran it through tier 1/2 testing and there were no failures. If you don't mind I would like to let this percolate a little in my mind (i.e. sleep on it for a day or two).

**Comment by amaembo** [comment]
A gentle ping :-)

**Review by PaulSandoz — APPROVED** [review]
Getting back to this after much delay! Approving. But, i would like to try and document this design decision in comments, and maybe in implementation notes. We can do that as a follow on PR.

**Pull request closed without merging**
