### PR TITLE
8287205: generate_cont_thaw generates dead code after jump to exception handler

### PR DESCRIPTION
**Pull request by reinrich**
This fix avoids generating unreachable instructions after the jump to the exception handler in `generate_cont_thaw()`

Testing:

jtreg:test/hotspot/jtreg:hotspot_loom
jtreg:test/jdk:jdk_loom

On linux x86_64 and aarch64.

On aarch64 the test `jdk/java/lang/management/ThreadMXBean/VirtualThreadDeadlocks.java` had a timeout. The aaarch64 machine I used is very slow. This might have caused the timeout.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287205](https://bugs.openjdk.java.net/browse/JDK-8287205): generate_cont_thaw generates dead code after jump to exception handler

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [9489400f](https://git.openjdk.java.net/jdk/pull/8863/files/9489400f98fd2584bb18d9d5f8e727bd0934e2c1)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8863/head:pull/8863` \
`$ git checkout pull/8863`

Update a local copy of the PR: \
`$ git checkout pull/8863` \
`$ git pull https://git.openjdk.java.net/jdk pull/8863/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8863`

View PR using the GUI difftool: \
`$ git pr show -t 8863`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8863.diff">https://git.openjdk.java.net/jdk/pull/8863.diff</a>

</details>

### CODE REVIEW

**Comment by reinrich** [comment]
> I think this is still `hotspot-compiler`

Ok. I will revert to `hotspot-compiler`

> I also suggest to pull from master and run `make test TEST="hotspot_loom jdk_loom"`.

Will do. I'll await our nightly tests before marking this pr as ready for review.

**Review by shipilev — APPROVED** [review]
Looks fine to me. I missed this while refactoring x86_64 generate_cont_thaw :)

**Comment by AlanBateman** [comment]
> On aarch64 the test `jdk/java/lang/management/ThreadMXBean/VirtualThreadDeadlocks.java` had a timeout. The aaarch64 machine I used is very slow. This might have caused the timeout.

There's an issue with that test, it's tracked by JDK-8287200. Leonid has a PR open to fix it.

**Comment by reinrich** [comment]
> Good.

Thank's for the reviews Aleksey and Vladimir.
I've got 2 weeks off now. Will integrate when back.

Richard.

**Comment by shipilev** [comment]
> Thank's for the reviews Aleksey and Vladimir. I've got 2 weeks off now. Will integrate when back.

In two weeks, we are going to be in RDP1, so this issue might not be integratable then. I think this issue is simple enough to push now, and the risk for it is small.

**Comment by reinrich** [comment]
> > Thank's for the reviews Aleksey and Vladimir. I've got 2 weeks off now. Will integrate when back.
> 
> 
> 
> In two weeks, we are going to be in RDP1, so this issue might not be integratable then. I think this issue is simple enough to push now, and the risk for it is small.

I agree, the risk is small (as the gain is). But maybe it blocks your changes? Do you want me to push now? You could also include this small enhancement in your work and I'd close this PR.

**Comment by shipilev** [comment]
> > > Thank's for the reviews Aleksey and Vladimir. I've got 2 weeks off now. Will integrate when back.
> > 
> > 
> > In two weeks, we are going to be in RDP1, so this issue might not be integratable then. I think this issue is simple enough to push now, and the risk for it is small.
> 
> I agree, the risk is small (as the gain is). But maybe it blocks your changes? Do you want me to push now? You could also include this small enhancement in your work and I'd close this PR.

Just push it now. I will handle the fallout, if any, while you are away. Other arches are likely to use x86_64 code as the template, so minor differences would accumulate if we delay this PR.

**Comment by reinrich** [comment]
Sure. Thanks!
/integrate

**Pull request closed without merging**
