### PR TITLE
8216984: Deprecate for removal Socket constructors to create UDP sockets

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which marks 2 constructors on `java.net.Socket` as deprecated for removal?

As noted in https://bugs.openjdk.org/browse/JDK-8216984 these 2 `Socket` constructors, which allow for `stream=false` to construct a UDP socket, have been deprecated since several releases (starting Java 1.1). `java.net.DatagramSocket` has been a standard API for dealing with UDP sockets as noted in the already existing deprecation note on these constructors.

The commit in this PR marks these constructs as deprecated for removal to allow for their removal in some future release.

No new tests have been added for this change. tier1, tier2 and tier3 testing is currently in progress.

A CSR for this change is available at https://bugs.openjdk.org/browse/JDK-8333092

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8333092](https://bugs.openjdk.org/browse/JDK-8333092) to be approved

### Issues
 * [JDK-8216984](https://bugs.openjdk.org/browse/JDK-8216984): Deprecate for removal Socket constructors to create UDP sockets (**Enhancement** - P3)
 * [JDK-8333092](https://bugs.openjdk.org/browse/JDK-8333092): Deprecate for removal Socket constructors to create UDP sockets (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19441/head:pull/19441` \
`$ git checkout pull/19441`

Update a local copy of the PR: \
`$ git checkout pull/19441` \
`$ git pull https://git.openjdk.org/jdk.git pull/19441/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19441`

View PR using the GUI difftool: \
`$ git pr show -t 19441`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19441.diff">https://git.openjdk.org/jdk/pull/19441.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19441#issuecomment-2136336680)

### CODE REVIEW

**Comment by AlanBateman** [comment]
I'm wondering about SocketImpl.create(boolean). We can't deprecate this method but maybe we should add a note to its API docs to say that Socket constructors to create a datagram socket is deprecated. If we do remove the constructors then I think SocketImpl.create(boolean) will be changed to throw UOE if the value of the parameter is false.

**Comment by jaikiran** [comment]
Hello Alan, I've updated the PR to include a note on `SocketImpl.create(...)`. Does the wording look correct? I'll update the CSR too once we finalize on the text.

**Comment by AlanBateman** [comment]
> Hello Alan, I've updated the PR to include a note on `SocketImpl.create(...)`. Does the wording look correct? I'll update the CSR too once we finalize on the text.

SocketImpl is for implementors (it's not a user facing API) so something like the following might be a better fit:

"The Socket constructors to create a datagram socket are deprecated for removal. This method will be re-specified in a future release to not support creating datagram sockets."

**Comment by jaikiran** [comment]
Done, I've updated the PR with the suggested text.

**Review by AlanBateman — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
LGTM

**Comment by jaikiran** [comment]
Thank you Alan and Daniel for the reviews.

**Pull request closed without merging**
