### PR TITLE
8306858: Remove some remnants of CMS from SA agent

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that removes some remaining CMS related stuff.

Testing: tier1-3, gha

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306858](https://bugs.openjdk.org/browse/JDK-8306858): Remove some remnants of CMS from SA agent

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [42d4cafa](https://git.openjdk.org/jdk/pull/13646/files/42d4cafa6e424ed8881cfb0c634e99035e0c1356)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [42d4cafa](https://git.openjdk.org/jdk/pull/13646/files/42d4cafa6e424ed8881cfb0c634e99035e0c1356)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13646/head:pull/13646` \
`$ git checkout pull/13646`

Update a local copy of the PR: \
`$ git checkout pull/13646` \
`$ git pull https://git.openjdk.org/jdk.git pull/13646/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13646`

View PR using the GUI difftool: \
`$ git pr show -t 13646`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13646.diff">https://git.openjdk.org/jdk/pull/13646.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13646#issuecomment-1522092364)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks fine to me.

But the synopsis has a typo, "remnants".

**Review by plummercj — APPROVED** [review]

**Review by plummercj — CHANGES_REQUESTED** [review]
Copyrights need updating

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by plummercj — APPROVED** [review]
Looks good.

**Review by ysramakrishna — APPROVED** [review]

**Comment by tschatzl** [comment]
Thanks @shipilev @kimbarrett @plummercj @ysr for you reviews.
/integrate

**Pull request closed without merging**
