### PR TITLE
8081507: Open or Save button in JFileChooser has OK title in GTK LaF

### PR DESCRIPTION
**Pull request by kumarabhi006**
Open or Save button in JFileChooser has OK title in GTK LAF. The open/save button text modified as per the native FileChooser. Manual test case is added.

`open/test/jdk/sanity/client/SwingSet/src/FileChooserDemoTest.java` failed with the current fix with an exception `**Wait AbstractButton with text "OK" loaded.**` Updated the test for GTK LAF and tested in CI which is OK now.

CI link is added in JBS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8081507](https://bugs.openjdk.org/browse/JDK-8081507): Open or Save button in JFileChooser has OK title in GTK LaF

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11790/head:pull/11790` \
`$ git checkout pull/11790`

Update a local copy of the PR: \
`$ git checkout pull/11790` \
`$ git pull https://git.openjdk.org/jdk pull/11790/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11790`

View PR using the GUI difftool: \
`$ git pr show -t 11790`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11790.diff">https://git.openjdk.org/jdk/pull/11790.diff</a>

</details>

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Comment by kumarabhi006** [comment]
@mrserb Can you please sponsor this PR?

**Review by TejeshR13 — APPROVED** [review]
Fix is tested and working fine.

**Pull request closed without merging**
