### PR TITLE
JDK-8291805: IGV: Improve Zooming

### PR DESCRIPTION
**Pull request by tobiasholenstein**
# Overview

The zooming is improved in the following ways:

1) Added a minimum (10%) and maximum (400%) zoom level. If you have a sensitive mouse wheel, it can be annoying to zoom in or out too much (until the graph is invisibly small or the nodes are larger than the window) 

2) Zooming with a trackpad was not very smooth because IGV did panning and zooming at the same time - Now panning is disabled when CMD/Ctrl key is pressed for zooming 

3) When only a few nodes were selected, zooming was no longer mouse centred. Instead, the center of the zooming was in the upper left corner. Now the zooming is centred to the middle of the scene when all selected nodes fit in the screen.  

4) Added a shortcut (Ctrl - 0) to reset the zoom level to 100%. 

5) Updated the Zoom icons to be vector graphics (.svg)

6) Replaced the zooming buttons with a new drop-down menu to select the zooming level (100%, 125%, ...)

# Implementation

1) New functions `getZoomMinFactor()` and `getZoomMinFactor()` assure that we do not zoom in or out our infinitely.  `getZoomMinFactor()` assures that we do not zoom out further if zoom level is <100% and all visible nodes already fit on the screen. 

2) We introduced a new `MouseCenteredZoomAction.java` for zooming with the mouse/trackpad. `MouseCenteredZoomAction` performs panning when the modifier key is pressed (Ctrl/CMD) and zooming otherwise. 

3) The `JScrollPane` now has a `JPanel centeringPanel` with `GridBagLayout()` that contains the `viewComponent`. This assures that the `viewComponent` is always centred when no scrollbars are visible. This makes the `Widget topLeft, bottomRight` obsolete as we can now add a white border of `BORDER_SIZE` to the `DiagramScene` instead. 

4) `ZoomResetAction.java` resets the zoom level to 100%. The shortcut is `Ctrl - 0` and the action is available in the menu: `View` -> `Reset Zoom`. It was not added to the icon menu bar in the `EditorTopComponent` because of space issue. 

5) new self created icons with vector graphics: `zoomIn.svg`,  `zoomOut.svg` and  `zoomReset.svg`

6) A new drop down menu that replaces the zoom-in and zoom-out buttons. The user can also manually enter a value. 
zoom-drop-down

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291805](https://bugs.openjdk.org/browse/JDK-8291805): IGV: Improve Zooming

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**) ⚠️ Review applies to [785c9ec0](https://git.openjdk.org/jdk/pull/10026/files/785c9ec0a9c55180afd815a9466b7097e515a155)
 * [Ludvig Janiuk](https://openjdk.org/census#lujaniuk) (@LudwikJaniuk - Author) ⚠️ Review applies to [6e2209df](https://git.openjdk.org/jdk/pull/10026/files/6e2209df3a0b3f1c135afc4eb40f801012cd094d)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [96911601](https://git.openjdk.org/jdk/pull/10026/files/969116019f48419e1339cef28c7554d70f7c13fe)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10026/head:pull/10026` \
`$ git checkout pull/10026`

Update a local copy of the PR: \
`$ git checkout pull/10026` \
`$ git pull https://git.openjdk.org/jdk pull/10026/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10026`

View PR using the GUI difftool: \
`$ git pr show -t 10026`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10026.diff">https://git.openjdk.org/jdk/pull/10026.diff</a>

</details>

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
Hi uh, I'm not a regular in this codebase, so anything I say should be taken with the caveat that I might not know what I'm doing. With that said, I tested your PR, and zooming still seems pretty broken to me. For one, I don't notice much of a difference except for the animation. Secondly, I think a big part of what makes the zooming feel erratic is there's this "frame" around the scene that forces the zooming to take strange turns. If you'd like, maybe we can talk over zoom ( ;) ) about the zooming behavior?

**Comment by tobiasholenstein** [comment]
After some discussions with @LudwikJaniuk and @robcasloz I removed the animated zooming again. Even if zooming is still not perfect, this PR should at least be an improvement on the various aspects that make zooming annoying. I am looking forward to your feedback!

**Review by robcasloz — APPROVED** [review]
Thanks Tobias for improving zooming, works like a charm! I only have a minor comment.

**Comment by LudwikJaniuk** [comment]
@tobiasholenstein Wanna try it soon :)

**Comment by LudwikJaniuk** [comment]
The latest version feels robust and seems to react to the mouse pointer's location consistently. I still think the "borders" of the map should be widened, but that's outside the scope of this PR.

**Review by LudwikJaniuk — APPROVED** [review]

**Comment by tobiasholenstein** [comment]
> The latest version feels robust and seems to react to the mouse pointer's location consistently. I still think the "borders" of the map should be widened, but that's outside the scope of this PR.

Thanks for testing! I now increased the border size (`BORDER_SIZE`) from 20px to 100px. And you are right, more complex changes to the size of the plane / layout could be done in another PR :)

**Comment by tobiasholenstein** [comment]
Update: I also removed the zoom level "300%" from the drop down menu - this avoids scrolling in the drop down. And I allowed the min. zoom level in the drop down menu (25%) to always be used

**Review by robcasloz — APPROVED** [review]

**Review by chhagedorn — APPROVED** [review]
Looks good! I've tested your changes and the zooming works great.

**Comment by tobiasholenstein** [comment]
Thanks @robcasloz , @LudwikJaniuk  and @chhagedorn for the reviews and helpful feedback!

/integrate

**Pull request closed without merging**
