### PR TITLE
8253311: Cleanup relocInfo constructors

### PR DESCRIPTION
**Pull request by kimbarrett**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253311](https://bugs.openjdk.java.net/browse/JDK-8253311): Cleanup relocInfo constructors

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/265/head:pull/265`
`$ git checkout pull/265`

### CODE REVIEW

**Comment by kimbarrett** [comment]
Please review this cleanup of the relocInfo constructors.

We use constructor delegation to avoid code duplication.  The old code seems
to have been attempting to fake constructor delegation for similar reasons.

Also fixed some comments about a nonexistent BoundRelocation class.

Testing: mach5 tier1-3

**Review by vnkozlov — APPROVED** [review]

**Comment by vnkozlov** [comment]
Looks good.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Pull request closed without merging**
