### PR TITLE
8275604: Zero: Reformat opclabels_data

### PR DESCRIPTION
**Pull request by shipilev**
This is a formatting-only patch that formats opclabels_data array to be more readable.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275604](https://bugs.openjdk.java.net/browse/JDK-8275604): Zero: Reformat opclabels_data

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6031/head:pull/6031` \
`$ git checkout pull/6031`

Update a local copy of the PR: \
`$ git checkout pull/6031` \
`$ git pull https://git.openjdk.java.net/jdk pull/6031/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6031`

View PR using the GUI difftool: \
`$ git pr show -t 6031`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6031.diff">https://git.openjdk.java.net/jdk/pull/6031.diff</a>

</details>

### CODE REVIEW

**Review by adinn — APPROVED** [review]
Looks fineto me.

**Comment by shipilev** [comment]
Thank you! Trivial, right?

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Comment by adinn** [comment]
> Thank you! Trivial, right?

Indeed.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
