### PR TITLE
8257074 Update the ByteBuffers micro benchmark

### PR DESCRIPTION
**Pull request by ChrisHegarty**
The ByteBuffers micro benchmark seems to be a little dated. 

It should be a useful resource to leverage when analysing the performance impact of any potential implementation changes in the byte buffer classes. More specifically, the impact of such changes on the performance of sharp memory access operations. 

This issue proposes to update the benchmark in the following ways to meet the aforementioned use-case: 

1. Remove allocation from the individual benchmarks - it just creates noise. 
2. Consolidate per-thread shared heap and direct buffers. 
3. All scenarios now use absolute memory access operations - so no state of the shared buffers is considered. 
4. Provide more reasonable default fork, warmup, etc, out-of-the-box. 
5. There seems to have been an existing bug in the test where the size parameter was not always considered - this is now fixed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257074](https://bugs.openjdk.java.net/browse/JDK-8257074): Update the ByteBuffers micro benchmark

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to 5e91e63efadacf1cd0c34e7da4837117876501d4
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 5e91e63efadacf1cd0c34e7da4837117876501d4
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - Committer) ⚠️ Review applies to 5e91e63efadacf1cd0c34e7da4837117876501d4
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**) ⚠️ Review applies to 5ee5d8bfbe1ad61d7c14e287c863b611dac819a5

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1430/head:pull/1430`
`$ git checkout pull/1430`

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
Overall a reasonable clean-up.

I do wonder if there's some value to at least some of these noisy, allocating variants, though. Could be interesting to zoom in on code where we allocate transient, small buffers, e.g. when encoding/decoding strings. But perhaps that needs to be designed differently and focus on a specific use case.

**Review by dfuch — APPROVED** [review]
I am not an expert in JMH microbenchmarks but the proposed changes look reasonable to me.

**Review by JornVernee — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
> I do wonder if there's some value to at least some of these noisy, allocating variants, though. Could be interesting to zoom in on code where we allocate transient, small buffers, e.g. when encoding/decoding strings. But perhaps that needs to be designed differently and focus on a specific use case.

Yes, that is an interest case, but largely orthogonal to the primary use-case for this particular micro benchmark (or maybe; the primary use-case that I want to use this benchmark for ;-) ). It appears to me that the primary purpose is to evaluate the memory access operations, so I want to keep buffer allocation out of the picture.  Of course, we could decide to just create a new benchmark, but then I'm not sure what we'd use the old one for.

**Review by mcimadamore — APPROVED** [review]
Looks like a good cleanup. I agree that mixing access and instantiation is not good from a benchmark perspective - although, given that direct buffers have a rather convoluted allocation process, I guess it would be useful, in the long term, to track performances of that too (this can be done by coupling direct buffer allocation with calls to Unsafe::invokeCleaner, so that the benchmark is not affected by the GC activity).

Also, given a carrier e.g. `float` there are at least two ways to get a float from a byte array:

* ByteBuffer::getFloat (both direct/heap)
* FloatBuffer::get() (both direct/heap)

The benchmark here focuses on the first bullet, but I think at some point we should also cover the remaining axis, so that, for each carrier, we really do at least 4 tests. Of course if you take into account swappiness for non-byte carriers, you get an extra variant for direct buffers as well, as you wanna test native endian vs. non-native endian.

So many possibilities :-)

**Comment by ChrisHegarty** [comment]
> Looks like a good cleanup. I agree that mixing access and instantiation is not good from a benchmark perspective - although, given that direct buffers have a rather convoluted allocation process, I guess it would be useful, in the long term, to track performances of that too (this can be done by coupling direct buffer allocation with calls to Unsafe::invokeCleaner, so that the benchmark is not affected by the GC activity).

I'll see if I can write a test for this.

> Also, given a carrier e.g. `float` there are at least two ways to get a float from a byte array:
> 
> * ByteBuffer::getFloat (both direct/heap)
> * FloatBuffer::get() (both direct/heap)
> 
> The benchmark here focuses on the first bullet, but I think at some point we should also cover the remaining axis, so that, for each carrier, we really do at least 4 tests. Of course if you take into account swappiness for non-byte carriers, you get an extra variant for direct buffers as well, as you wanna test native endian vs. non-native endian.

Yes, good observation - I had similar thoughts. Let me check if we could easily integrate some of these variants. What I'm trying to end up with is a comprehensive(ish) set of test scenarios that can be used to analyse performance ( of which views and endianness are important).

It may be reasonable for this particular benchmark to include views, etc, with appropriately named benchmark methods, so that one can easily run a subset, e.g. "org.openjdk.bench.java.nio.ByteBuffers.test(Direct)?(BulkPut|SinglePutByte)", when trying to "zoom in" on a specific code path.

**Review by mcimadamore — COMMENTED** [review]
Looks a great improvements. Two comments:

* the names always mention the "Single" word, when in fact all benchmark involve some kind of a loop. I'd suggest making that more  explicit, both in the benchmark method and in the helpers.

* I see that you added  support for views - but note that, for heap buffers there are two different kind of views (!!). E.g. I believe that:

```
ByteBuffer.allocate(size * 4).asFloatBuffer()
```
returns a buffer of a different class than:

```
FloatBuffer.allocate(size);
```
I think you are only testing the former?

**Review by bplb — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
While the updated set of scenarios covered by this benchmark is
reasonably (and vastly improves coverage), I find myself reluctant to
add the last remaining buffer property - read-only views. It's time to
template the generation of this code!

**Comment by JornVernee** [comment]
If the cases get to be too many, you might also want to consider splitting the benchmark class into several classes that cover different cases (we did this for the memory access benchmarks as well). That would also make it easier to run a subset of cases in isolation.

**Comment by ChrisHegarty** [comment]
All comments to date have been addressed. Unless there are any further comments, I would like to integrate this change.

**Pull request closed without merging**
