### PR TITLE
8279066: entries.remove(entry) is useless in PKCS12KeyStore

### PR DESCRIPTION
**Pull request by wangweij**
Before password-less PKCS12 keystores are supported, certificates in a PKCS12 file are always encrypted. Therefore if one loads the keystore with a null pass, it contains `PrivateKeyEntry`s without certificates. This has always been awkward (and most likely useless) so when JDK-8076190 introduced the password-less feature I also added a line to remove such an entry. 

https://github.com/openjdk/jdk/blob/a729a70c0119ed071ff490b0dfd4e3e2cb1a5ae4/src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#L2272 

Unfortunately, the line is not coded correctly, it should have been `remove(key)` but here it's `remove(value)`.

This code change correctly removes the entry.

That said, this behavior, although weird, has been there from the beginning since PKCS12 keystore was introduced. If you can find out a usage of a private key entry without any certificate and think it's worth kept that way, I can simply remove the `remove` call and leave the entry there.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279066](https://bugs.openjdk.java.net/browse/JDK-8279066): entries.remove(entry) is useless in PKCS12KeyStore

### Reviewers
 * [Sean Mullan](https://openjdk.java.net/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6910/head:pull/6910` \
`$ git checkout pull/6910`

Update a local copy of the PR: \
`$ git checkout pull/6910` \
`$ git pull https://git.openjdk.java.net/jdk pull/6910/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6910`

View PR using the GUI difftool: \
`$ git pr show -t 6910`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6910.diff">https://git.openjdk.java.net/jdk/pull/6910.diff</a>

</details>

### CODE REVIEW

**Comment by gerry1888** [comment]
Storage  to clouds+4

**Comment by seanjmullan** [comment]
I still think it's useful even if I can't see the certificate chain. I'd rather see the entry if it actually exists in the keystore and I think removing it is odd because it still exists in the keystore. Also, sometimes I use keytool without a storepass just to see what is in it, and then if I see the certificates are not showing up, I can try again with the password.

**Comment by wangweij** [comment]
OK, I've updated the change to simply removing that `remove` all.

**Review by seanjmullan — APPROVED** [review]

**Pull request closed without merging**
