### PR TITLE
JDK-8303071: Memory leaks in libjdwp

### PR DESCRIPTION
**Pull request by jcking**
Fix minor memory leaks in libjdwp.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303071](https://bugs.openjdk.org/browse/JDK-8303071): Memory leaks in libjdwp

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12716/head:pull/12716` \
`$ git checkout pull/12716`

Update a local copy of the PR: \
`$ git checkout pull/12716` \
`$ git pull https://git.openjdk.org/jdk pull/12716/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12716`

View PR using the GUI difftool: \
`$ git pr show -t 12716`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12716.diff">https://git.openjdk.org/jdk/pull/12716.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
It looks good.
Thank you for taking care about it.
Thanks,
Serguei

**Comment by dholmes-ora** [comment]
Just a sanity check here. That memory was allocated using `*callback->alloc` not `jvmtiAllocate` - is it correct to release with `jvmtiDeallocate`?

**Comment by jcking** [comment]
callback->alloc is jvmtiAllocate and callback->free is jvmtiDeallocate. It is setup in transport.c, which is also the one which frees. So it is fine in this case.

**Comment by dholmes-ora** [comment]
Thanks! Now I can join the dots there.

**Review by plummercj — COMMENTED** [review]
Approved.

@jcking In the future please wait for a second review before pushing any hotspot related changes unless the reviewer agrees that the changes are trivial. thanks.

**Pull request closed without merging**
