### PR TITLE
8305618: Move gcold out of tier1

### PR DESCRIPTION
**Pull request by lkorinth**
8305618: Move gcold out of tier1

Remove gcold out from tier1. Related to [JDK-8298981](https://bugs.openjdk.org/browse/JDK-8298981). Moving gcbasher out of tier1 was more controversial, and will be done later --- if at all.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305618](https://bugs.openjdk.org/browse/JDK-8305618): Move gcold out of tier1

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13340/head:pull/13340` \
`$ git checkout pull/13340`

Update a local copy of the PR: \
`$ git checkout pull/13340` \
`$ git pull https://git.openjdk.org/jdk.git pull/13340/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13340`

View PR using the GUI difftool: \
`$ git pr show -t 13340`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13340.diff">https://git.openjdk.org/jdk/pull/13340.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13340#issuecomment-1496590198)

### CODE REVIEW

**Review by lmesnik — APPROVED** [review]

**Review by dholmes-ora — COMMENTED** [review]
You've removed tier1_gc_gcold from tier1_gc as stated, but shouldn't that group now be renamed as it is no longer part of tier1? And does it need to be added into another tier?

**Comment by shipilev** [comment]
> You've removed tier1_gc_gcold from tier1_gc as stated, but shouldn't that group now be renamed as it is no longer part of tier1? And does it need to be added into another tier?

+1. 

Shenandoah runs both gcold and gcbasher in tier3, should we run these in tier3 as well? Otherwise they would get caught by tier4, which is too long for many to run.

**Comment by lkorinth** [comment]
I can add tier1_gc_gcold to tier2 or tier3 (and rename it to correct tier number), or I could just remove it and it will run in tier4. What do you prefer?

**Comment by lmesnik** [comment]
> You've removed tier1_gc_gcold from tier1_gc as stated, but shouldn't that group now be renamed as it is no longer part of tier1? And does it need to be added into another tier?

There is some misunderstanding in the gc tiers/groups naming and usage. 
We use only tier1_gc and hotspot_gc groups in our testing and don't use hotspot tier2/tier3 test groups directly.

Thus, the gc_old tests would be executed with all other tests from hotspot_gc. And we just not going to use this test group. I am fine with renaming it and adding to the tier3 if is more convenient for openjdk users.

**Comment by shipilev** [comment]
> I can add tier1_gc_gcold to tier2 or tier3 (and rename it to correct tier number), or I could just remove it and it will run in tier4. What do you prefer?

I prefer tier3. GC stress tests belong there, I think.

**Review by shipilev — APPROVED** [review]
I like this. Have you confirmed these actually run in `tier3`?

**Comment by lkorinth** [comment]
Yes, it passes and it runs gcold.

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
