### PR TITLE
8345273: Fix -Wzero-as-null-pointer-constant warnings in s390 code

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to remove -Wzero-as-null-pointer-constant warnings
in s390 code.

Most places involve just changing literal 0 to nullptr.

Removed a dead return after ShouldNotReachHere() that is no longer needed.

Testing:
GHA sanity test build, with and without -Wzero-as-null-pointer-constant enabled.
I don't have the capability to run tests for this platform, so hoping someone
from the aix-ppc maintainers can do more testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345273](https://bugs.openjdk.org/browse/JDK-8345273): Fix -Wzero-as-null-pointer-constant warnings in s390 code (**Enhancement** - P4)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22469/head:pull/22469` \
`$ git checkout pull/22469`

Update a local copy of the PR: \
`$ git checkout pull/22469` \
`$ git pull https://git.openjdk.org/jdk.git pull/22469/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22469`

View PR using the GUI difftool: \
`$ git pr show -t 22469`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22469.diff">https://git.openjdk.org/jdk/pull/22469.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22469#issuecomment-2509949824)
</details>

### CODE REVIEW

**Comment by offamitkumar** [comment]
hi @kimbarrett, 

I tried to build it on s390x with these changes: 
```diff
diff --git a/make/autoconf/flags-cflags.m4 b/make/autoconf/flags-cflags.m4
index 57654514eb6..ce3077e7d38 100644
--- a/make/autoconf/flags-cflags.m4
+++ b/make/autoconf/flags-cflags.m4
@@ -448,7 +448,7 @@ AC_DEFUN([FLAGS_SETUP_CFLAGS],
   CC="$CC_OLD"
   CXX="$CXX_OLD"
   CFLAGS="$CFLAGS_OLD"
-  CXXFLAGS="$CXXFLAGS_OLD"
+  CXXFLAGS="$CXXFLAGS_OLD  -Wzero-as-null-pointer-constant"
 ])
```

is that correct way to test it ? 

I got couple of build warnings, good thing is that none of them are in s390x code. I am attaching build.log file. 

[build.log](https://github.com/user-attachments/files/17972560/build.log)

**Comment by kimbarrett** [comment]
> hi @kimbarrett,
> 
> I tried to build it on s390x with these changes:
> 
> ```diff
> diff --git a/make/autoconf/flags-cflags.m4 b/make/autoconf/flags-cflags.m4
> index 57654514eb6..ce3077e7d38 100644
> --- a/make/autoconf/flags-cflags.m4
> +++ b/make/autoconf/flags-cflags.m4
> ```
[snip]
> is that correct way to test it ?

That's too general, affecting the entire JDK. The rule we're trying to enforce
(don't use literal 0 as a null pointer constant) is specific to HotSpot.

For testing, I've been adding the warning to the list here:

https://github.com/openjdk/jdk/blob/e13206d3a16a67a604076faecded88cbed85db1a/make/autoconf/flags-cflags.m4#L785

I've not verified with the build team that this is the right place ultimately.
And I suspect it's not, since your log listed warnings in adlc. I'm not seeing
any warnings there, even though (looking at the code) there clearly should be.

**Review by TheShermanTanker — APPROVED** [review]
Looks good

**Comment by TheShermanTanker** [comment]
> > hi @kimbarrett,
> > I tried to build it on s390x with these changes:
> > ```diff
> > diff --git a/make/autoconf/flags-cflags.m4 b/make/autoconf/flags-cflags.m4
> > index 57654514eb6..ce3077e7d38 100644
> > --- a/make/autoconf/flags-cflags.m4
> > +++ b/make/autoconf/flags-cflags.m4
> > ```
> 
> [snip]
> 
> > is that correct way to test it ?
> 
> That's too general, affecting the entire JDK. The rule we're trying to enforce (don't use literal 0 as a null pointer constant) is specific to HotSpot.
> 
> For testing, I've been adding the warning to the list here:
> 
> https://github.com/openjdk/jdk/blob/e13206d3a16a67a604076faecded88cbed85db1a/make/autoconf/flags-cflags.m4#L785
> 
> I've not verified with the build team that this is the right place ultimately. And I suspect it's not, since your log listed warnings in adlc. I'm not seeing any warnings there, even though (looking at the code) there clearly should be.

Do we also want ADLC to have nulls cleaned up? I thought it was just HotSpot that the cleanups were aimed at, not including the tools used while building it

**Review by theRealAph — APPROVED** [review]

**Comment by kimbarrett** [comment]
I'd like a review from an s390 porter.  But it's a simple enough change that I'm not going to wait indefinitely.
I'll give it another day.

**Review by offamitkumar — APPROVED** [review]
Sorry for kept you waiting. LGTM

**Comment by kimbarrett** [comment]
Thanks for reviews @theRealAph , @TheShermanTanker , and @offamitkumar

**Pull request closed without merging**
