### PR TITLE
8263565: NPE was thrown when sun.jvm.hotspot.rmi.serverNamePrefix was set

### PR DESCRIPTION
**Pull request by YaSuenag**
NPE was thrown when I set server name prefix for debugd as following:

```
$ jhsdb -J-Dsun.jvm.hotspot.rmi.serverNamePrefix=test debugd --pid 781
Attaching to process ID 781 and starting RMI services, please wait...
Error attaching to process or starting server: sun.jvm.hotspot.debugger.DebuggerException: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
        at jdk.hotspot.agent/sun.jvm.hotspot.RMIHelper.rebind(RMIHelper.java:78)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:379)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:329)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.startServer(HotSpotAgent.java:215)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runDEBUGD(SALauncher.java:431)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:493)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
        at java.base/java.net.URI$Parser.parse(URI.java:3166)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.rmi/java.rmi.Naming.intParseURL(Naming.java:273)
        at java.rmi/java.rmi.Naming.parseURL(Naming.java:237)
        at java.rmi/java.rmi.Naming.rebind(Naming.java:171)
        at jdk.hotspot.agent/sun.jvm.hotspot.RMIHelper.rebind(RMIHelper.java:64)
        ... 5 more
```

`serverNamePrefix` would not affect due to trivial bug.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263565](https://bugs.openjdk.java.net/browse/JDK-8263565): NPE was thrown when sun.jvm.hotspot.rmi.serverNamePrefix was set

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Alex Menkov](https://openjdk.java.net/census#amenkov) (@alexmenkov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3000/head:pull/3000` \
`$ git checkout pull/3000`

Update a local copy of the PR: \
`$ git checkout pull/3000` \
`$ git pull https://git.openjdk.java.net/jdk pull/3000/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3000`

View PR using the GUI difftool: \
`$ git pr show -t 3000`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3000.diff">https://git.openjdk.java.net/jdk/pull/3000.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — APPROVED** [review]
The fix looks fine. It would be nice if this was documented somewhere (and even tested). Also, while looking into this I noticed the following comment:

        // debugServerID follows the pattern [unique_id@]host[:port]
        // we have to transform this as //host[:port]/<serverNamePrefix>['_'<unique_id>]

The `[:port]` part is also not document, not even in the command line syntax for `sadebugd`

**Comment by YaSuenag** [comment]
Thanks @plummercj for your review!

> The fix looks fine. It would be nice if this was documented somewhere (and even tested). Also, while looking into this I noticed the following comment:
> 
> ```
>     // debugServerID follows the pattern [unique_id@]host[:port]
>     // we have to transform this as //host[:port]/<serverNamePrefix>['_'<unique_id>]
> ```
> 
> The `[:port]` part is also not document, not even in the command line syntax for `sadebugd`

In addition `sun.jvm.hotspot.rmi.startRegistry` is also undocumented even though it works well.
Both `serverNamePrefix` and `startRegistry` are not exposed as command line options of jhsdb, I think documentation. implementing testcases, and exposing as command line options should be done simultaneously. We need to change both command line help and manpage in that work (CSR is needed of course.)

For example, I think we can expose them as following:

```
$ jhsdb debugd --help
    :
    --disableregistry             Do not start RMI registry (to use RMI registry that exists)
    --servernameprefix         Specify RMI server name prefix
```

```
$ jhsdb jinfo --help
    :
    --connect [<id>@]<host>[:registryport][/servernameprefix] To connect to a remote debug server (debugd).
    :
    Examples: jhsdb jinfo --pid 1234
          or  jhsdb jinfo --core ./core.1234 --exe ./myexe
          or  jhsdb jinfo --connect debugserver
          or  jhsdb jinfo --connect id@debugserver:1234/prefix
```

I will work for it if you are ok.

**Comment by plummercj** [comment]
That looks fine, although I'm a little unclear about the need for `--disableregistry`, and how that applies to existing code. 

Also, I think a bit of explanation of `[:registryport]` is needed since it is not also specified by the `jhsdb debugd` command. That's just the port that it chooses to communicate over, and can be any available port, right? If one is not specified, what port is chosen, and what would be a reason that you would want to specify a port?

**Comment by YaSuenag** [comment]
> That looks fine, although I'm a little unclear about the need for `--disableregistry`, and how that applies to existing code.

We can use it when we want to register SA endpoint to RMI registry that exists (e.g. rmid). I think it is simple to proxy to `sun.jvm.hotspot.rmi.startRegistry` like `--registryport` option in jhsdb.

https://github.com/openjdk/jdk/blob/master/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/SALauncher.java#L392-L400

> Also, I think a bit of explanation of `[:registryport]` is needed since it is not also specified by the `jhsdb debugd` command. That's just the port that it chooses to communicate over, and can be any available port, right? If one is not specified, what port is chosen, and what would be a reason that you would want to specify a port?

We can specify any available port as you said.
For example, if we run multiple debugd instances on same OS, we need to use different port. We can use `--registryport` and `[:registryport]` in that case.
However we will not have many opportunities to use this.

**Comment by plummercj** [comment]
I think the default rmi registry port is 1099. However, do we need to also support something like [JDK-8196729](https://bugs.openjdk.java.net/browse/JDK-8196729) for the rmi communications port?

**Comment by YaSuenag** [comment]
> I think the default rmi registry port is 1099. However, do we need to also support something like [JDK-8196729](https://bugs.openjdk.java.net/browse/JDK-8196729) for the rmi communications port?

We can specify RMI communication port with `--rmiport` in `jhsdb debugd`. It has been introduced in [JDK-8196751](https://bugs.openjdk.java.net/browse/JDK-8196751).

**Comment by YaSuenag** [comment]
For example, if we want to fix RMI registry and communication port, we can start debugd instance as following:

```
$ jhsdb debugd --pid 1234 --registryport 2000 --rmiport 3000
```

Then, we can connect to it as following:

```
$ jhsdb jinfo --connect localhost:2000
```

**Comment by plummercj** [comment]
Sorry. I was running an old jhsdb. So we already have --registryport 2000 --rmiport, and you can already specify [:<registryport>] as part of the debugserver. So what needs to be added is just --servernameprefix, and better help for explaining all the parts of the debugserver that are specified with --connect. You also want to add --disableregistry, but I think that's kind of separate from the above and probably needs its own CR and CSR.

**Comment by YaSuenag** [comment]
> So what needs to be added is just --servernameprefix, and better help for explaining all the parts of the debugserver that are specified with --connect. You also want to add --disableregistry, but I think that's kind of separate from the above and probably needs its own CR and CSR.

I filed them to JBS. I will work for them later.

* --servernameprefix: https://bugs.openjdk.java.net/browse/JDK-8263635
* --disableregistry: https://bugs.openjdk.java.net/browse/JDK-8263636

**Comment by YaSuenag** [comment]
Ping: could you review it? I need one more reviewer to push.

**Review by alexmenkov — APPROVED** [review]

**Pull request closed without merging**
