### PR TITLE
8257212: (bf spec) Clarify byte order of the buffer returned by CharBuffer.subsequence(int,int)

### PR DESCRIPTION
**Pull request by c-cleary**
Specification for CharBuffer::subSequence was missing clarification on the byte order of the returned CharBuffer. The returned order will always be the same as that of the original buffer. For example, subSequence() called on a CharBuffer with Little-Endian Byte Order will return a CharBuffer of Little-Endian Order. The specification has been changed to reflect this.

In addition to this, some additional testing was added to improve test coverage of this behavior. Testing for the Byte Order of different types of Buffer is generated via the template Order-X.java.template which serves to verify the original Byte Order of a Buffer and subsequently verify that the same Byte Order is present after operations such as CharBuffer::subSequence

CSR: https://bugs.openjdk.java.net/browse/JDK-8259638

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257212](https://bugs.openjdk.java.net/browse/JDK-8257212): (bf spec) Clarify byte order of the buffer returned by CharBuffer.subsequence(int,int)

### Reviewers
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2049/head:pull/2049`
`$ git checkout pull/2049`

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]

**Comment by c-cleary** [comment]
CDR is filed: [https://bugs.openjdk.java.net/browse/JDK-8259638](https://bugs.openjdk.java.net/browse/JDK-8259638)

**Comment by bplb** [comment]
In X-Buffer.java.template, s/2020/2021/ in the copyright year; in Order-X.java.template add 2021 as second copyright year.

**Comment by c-cleary** [comment]
> In X-Buffer.java.template, s/2020/2021/ in the copyright year; in Order-X.java.template add 2021 as second copyright year.

2021 is now added to all copyright notices... classic start of the year mistake!

**Review by ChrisHegarty — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
