### PR TITLE
8293329: x86: Improve handling of constants in AES/GHASH stubs

### PR DESCRIPTION
**Pull request by iwanowww**
Pre-generating constants saves on startup and static/dynamic footprint a bit, plus simplifies bootstrapping logic. 

As a downside, constants aren't guaranteed to be always reachable anymore, but since they are used from stubs, finding a scratch register when needed is not a problem.

Testing: 
- [x] hs-tier1 - hs-tier4 w/ `-XX:+ForceUnreachable` 
- [x] x86_32 build

/cc hotspot

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293329](https://bugs.openjdk.org/browse/JDK-8293329): x86: Improve handling of constants in AES/GHASH stubs

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10152/head:pull/10152` \
`$ git checkout pull/10152`

Update a local copy of the PR: \
`$ git checkout pull/10152` \
`$ git pull https://git.openjdk.org/jdk pull/10152/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10152`

View PR using the GUI difftool: \
`$ git pr show -t 10152`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10152.diff">https://git.openjdk.org/jdk/pull/10152.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I would like to see the effect on performance. In worst case constants will not be reachable always. Changes are fine if the effect is negligible.

**Comment by iwanowww** [comment]
> I would like to see the effect on performance. In worst case constants will not be reachable always. Changes are fine if the effect is negligible.

I ran AES microbenchmarks and didn't notice any noticeable difference between baseline and the patched version w/ `-XX:+ForceUnreachable` in throughput.

**Comment by vnkozlov** [comment]
> > I would like to see the effect on performance. In worst case constants will not be reachable always. Changes are fine if the effect is negligible.
> 
> I ran AES microbenchmarks and didn't notice any noticeable difference between baseline and the patched version w/ `-XX:+ForceUnreachable` in throughput.

Good.

**Review by vnkozlov — APPROVED** [review]

**Comment by iwanowww** [comment]
Thanks for the review, Vladimir.

/integrate

**Pull request closed without merging**
