### PR TITLE
8325451: Missed elimination of assertion predicates

### PR DESCRIPTION
**Pull request by caojoshua**
For this example:

```
public void blackhole(int[] arr) {
  for (int i = 0; i < arr.length; ++i) {
    blackhole(arr[i]);
  }
}
```

We generate predicates for the lower/upper bound. The lower bound predicate gets optimized away, but the associated assertion predicate remains in the code.

The issue is that we iterate over list `C->template_assertion_predicate_opaq_node`, and we delete items from it in `_igvn.replace_node(n, n->in(2))`. I was surprised that this actually removes an item from the predicates list. Here is the trace:

```
#0  Compile::remove_template_assertion_predicate_opaq (this=0x7fffb5d5a7e0, n=0x7fff84097eb0) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/compile.hpp:776
#1  0x00007ffff5313c53 in Compile::remove_useless_node (this=0x7fffb5d5a7e0, dead=0x7fff84097eb0) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/compile.cpp:395
#2  0x00007ffff5cebb95 in PhaseIterGVN::remove_globally_dead_node (this=0x7fffb5d584e0, dead=0x7fff84097eb0) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/phaseX.cpp:1380
#3  0x00007ffff52241ce in PhaseIterGVN::remove_dead_node (this=0x7fffb5d584e0, dead=0x7fff84097eb0) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/phaseX.hpp:527
#4  0x00007ffff5cebfc7 in PhaseIterGVN::subsume_node (this=0x7fffb5d584e0, old=0x7fff84097eb0, nn=0x7fff8408fb80) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/phaseX.cpp:1429
#5  0x00007ffff50045bf in PhaseIterGVN::replace_node (this=0x7fffb5d584e0, old=0x7fff84097eb0, nn=0x7fff8408fb80) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/phaseX.hpp:539
#6  0x00007ffff5aec060 in PhaseIdealLoop::eliminate_useless_template_assertion_predicates (this=0x7fffb5d58120, useful_predicates=...) at /local/home/joshcao/pea/jdk/src/hotspot/share/opto/loopnode.cpp:4366
```

We can fix this by iterating in reverse over the linked list.

Caveat: this patch only affects the first test `TestPredicateBasic::basic()`. Adding the other tests for completeness and can potentially be improved in other work.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325451](https://bugs.openjdk.org/browse/JDK-8325451): Missed elimination of assertion predicates (**Enhancement** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [ac2b3291](https://git.openjdk.org/jdk/pull/17767/files/ac2b3291eceea887d31bf5835ed0656bec3bda4e)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17767/head:pull/17767` \
`$ git checkout pull/17767`

Update a local copy of the PR: \
`$ git checkout pull/17767` \
`$ git pull https://git.openjdk.org/jdk.git pull/17767/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17767`

View PR using the GUI difftool: \
`$ git pr show -t 17767`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17767.diff">https://git.openjdk.org/jdk/pull/17767.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17767#issuecomment-1933449019)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Good catch! The complete fix for Assertion Predicates [JDK-8288981](https://bugs.openjdk.org/browse/JDK-8288981) will remove this code here and do the cleanup differently. But for now, I think it's good to fix it.

**Comment by caojoshua** [comment]
@chhagedorn could you sponsor this?

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
