### PR TITLE
8295814: jdk/jshell/CommandCompletionTest.java fails with "lists don't have the same size expected [2] but found [1]"

### PR DESCRIPTION
**Pull request by asotona**
File completion in CommandCompletionTest::testSet intermittently fails.
Also message provided by org.testng.Assert::assertEquals is also not very verbose when comparing collections:
"lists don't have the same size expected [2] but found [1]".

Cause of the failure is in the expected side of the assertion (CommandCompletionTest::getRootDirectories), which may conatain duplicates. While the actual side of the assertion is distinct (CommandCompletionTest::computeCompletions).

Proposed patch de-duplicates CommandCompletionTest::getRootDirectories and adds full description of the expected result to the error message for future debugging.

Please review.

Thanks,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295814](https://bugs.openjdk.org/browse/JDK-8295814): jdk/jshell/CommandCompletionTest.java fails with "lists don't have the same size expected [2] but found [1]"

### Reviewers
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10870/head:pull/10870` \
`$ git checkout pull/10870`

Update a local copy of the PR: \
`$ git checkout pull/10870` \
`$ git pull https://git.openjdk.org/jdk pull/10870/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10870`

View PR using the GUI difftool: \
`$ git pr show -t 10870`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10870.diff">https://git.openjdk.org/jdk/pull/10870.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
@asotona - please see this comment that I added to the bug:

https://bugs.openjdk.org/browse/JDK-8295814?focusedCommentId=14532614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14532614

**Comment by asotona** [comment]
Please review proposed patch to test minimal size of the expected completion response for problematic test cases, instead of verification of the exact content.

**Review by lahodaj — APPROVED** [review]
Looks OK.

**Pull request closed without merging**
