### PR TITLE
8280106: G1: Make reclaiming memory functionality more general in G1SegmentedArrayFreePool and G1SegmentedArrayFreeMemoryTask

### PR DESCRIPTION
**Pull request by Hamlin-Li**
We have planned to make memory reclaimation more general, and reuse it in evacuation failure processing after JDK-8254739.
Some of the work has already been done in JDK-8276670 and JDK-8277542.
But after JDK-8278917, there is no need to return the memory used by G1SegmentedArray in evacuation failure processing, as it uses another way to do it.
Currently, G1SegmentedArrayFreePool and G1SegmentedArrayFreeMemoryTask is half-bound to card set, and half-general, it should be made more general for the readability of the code and future possible reuse of this functionality returning memory (used by G1SegmentedArray) to OS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8280106](https://bugs.openjdk.java.net/browse/JDK-8280106): G1: Make reclaiming memory functionality more general in G1SegmentedArrayFreePool and G1SegmentedArrayFreeMemoryTask

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7121/head:pull/7121` \
`$ git checkout pull/7121`

Update a local copy of the PR: \
`$ git checkout pull/7121` \
`$ git pull https://git.openjdk.java.net/jdk pull/7121/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7121`

View PR using the GUI difftool: \
`$ git pr show -t 7121`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7121.diff">https://git.openjdk.java.net/jdk/pull/7121.diff</a>

</details>

### CODE REVIEW

**Review by walulyai — COMMENTED** [review]
Is there a plan to use the Configuration parameter beyond getting the number of object types as in `static constexpr uint NUM = Configuration::num_mem_object_types();`?

**Comment by Hamlin-Li** [comment]
Hi Ivan,

Thanks for having a look at this patch. I'm on vacation this week, how about I get back to you next week?

Thanks
-Hamlin

**Comment by Hamlin-Li** [comment]
Currently, Configuration is only used to get the number of object types.
Do you suggest to use a const template parameter (e.g. template<MEMFLAGS flag, int NUM> class G1SegmentedArrayFreeMemoryTask) to replace the Configuration parameter? I don't object, but seems a Configuration parameter make it more clear to differentiate between 2 G1SegmentedArrayFreeMemoryTask even if they has the same number of object types.
Please kindly let me know you suggestion.

**Comment by walulyai** [comment]
> Currently, Configuration is only used to get the number of object types. Do you suggest to use a const template parameter (e.g. template<MEMFLAGS flag, int NUM> class G1SegmentedArrayFreeMemoryTask) to replace the Configuration parameter? I don't object, but seems a Configuration parameter make it more clear to differentiate between 2 G1SegmentedArrayFreeMemoryTask even if they has the same number of object types. Please kindly let me know you suggestion.

Just seemed like overkill to use a template parameter, const template parameter does not solve that. If there is not work around that doesn't involve a new template parameter, then the Configuration is better because we might use it for more in the future. I was just wondering if we can pass the number of object types in constructor rather than template parameter.

**Comment by Hamlin-Li** [comment]
> > Currently, Configuration is only used to get the number of object types. Do you suggest to use a const template parameter (e.g. template<MEMFLAGS flag, int NUM> class G1SegmentedArrayFreeMemoryTask) to replace the Configuration parameter? I don't object, but seems a Configuration parameter make it more clear to differentiate between 2 G1SegmentedArrayFreeMemoryTask even if they has the same number of object types. Please kindly let me know you suggestion.
> 
> Just seemed like overkill to use a template parameter, const template parameter does not solve that. If there is not work around that doesn't involve a new template parameter, then the Configuration is better because we might use it for more in the future. I was just wondering if we can pass the number of object types in constructor rather than template parameter.

So, do you agree to go with a Configuration as the template parameter?
( Sorry, I missed another use of Configuration which is Configuration::mem_object_type_name_str(i). )

**Comment by walulyai** [comment]
> > > Currently, Configuration is only used to get the number of object types. Do you suggest to use a const template parameter (e.g. template<MEMFLAGS flag, int NUM> class G1SegmentedArrayFreeMemoryTask) to replace the Configuration parameter? I don't object, but seems a Configuration parameter make it more clear to differentiate between 2 G1SegmentedArrayFreeMemoryTask even if they has the same number of object types. Please kindly let me know you suggestion.
> > 
> > 
> > Just seemed like overkill to use a template parameter, const template parameter does not solve that. If there is not work around that doesn't involve a new template parameter, then the Configuration is better because we might use it for more in the future. I was just wondering if we can pass the number of object types in constructor rather than template parameter.
> 
> So, do you agree to go with a Configuration as the template parameter? ( Sorry, I missed another use of Configuration which is Configuration::mem_object_type_name_str(i). )

Yes

**Pull request closed without merging**
