### PR TITLE
8286269: [java.desktop] Use newer instanceof language feature wherever possible

### PR DESCRIPTION
**Pull request by SWinxy**
The old java.desktop package needs dusting off. It hasn't been kept up to pace with the Java language, but it should. The purpose of this PR is to replace most or all `instanceof` checks with the new `instanceof` with a variable. Some methods that used `instanceof` were also reworked alongside the change (such as `.equals()`) if they were small and they could be clearer.
There should be no actual change in outcomes from this PR. I have triple checked my work. Some cases are kinda 'wut?'.
This is also a large change. When pattern matching for switch arrives, many methods can be reworked to take advantage of it (when it comes.. eventually ;w;).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286269](https://bugs.openjdk.java.net/browse/JDK-8286269): [java.desktop] Use newer instanceof language feature wherever possible

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7000/head:pull/7000` \
`$ git checkout pull/7000`

Update a local copy of the PR: \
`$ git checkout pull/7000` \
`$ git pull https://git.openjdk.java.net/jdk pull/7000/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7000`

View PR using the GUI difftool: \
`$ git pr show -t 7000`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7000.diff">https://git.openjdk.java.net/jdk/pull/7000.diff</a>

</details>

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Try to merge instead of rebasing and force-pushing, it helps with later reviews. I can try to help you get a JBS issue for this too, since you need one for the PR to be accepted (No guarantees though)

**Comment by SWinxy** [comment]
> Try to merge instead of rebasing and force-pushing, it helps with later reviews.

Good to know. I'm not a git master, and the purpose of the force push was to consolidate some missed changes into a single commit, but I know it can mess up PRs.

> I can try to help you get a JBS issue for this too

Thanks. I've been having some frustrations with the OCA process, and I don't want my commits to languish.

**Comment by TheShermanTanker** [comment]
> > Try to merge instead of rebasing and force-pushing, it helps with later reviews.
> 
> Good to know. I'm not a git master, and the purpose of the force push was to consolidate some missed changes into a single commit, but I know it can mess up PRs.
> 
> > I can try to help you get a JBS issue for this too
> 
> Thanks. I've been having some frustrations with the OCA process, and I don't want my commits to languish.

@SWinxy I haven't been able to contact anyone to create an issue yet, but I'm now able to create them directly myself, that said, it's probably best if i wait for your contributor agreement to be approved before I do so. Would you like me to create entries corresponding to your PRs now anyway or hold off for now? (Do remind me to do so once the agreement gets approved if you want me to wait first)

**Comment by SWinxy** [comment]
The OCA process is back in my court, and I've been overwhelmed these past few weeks to get it over with. Thank you, genuinely, for offering. If you have time to create those issues on the JBS, I would greatly appreciate it.

**Comment by TheShermanTanker** [comment]
> The OCA process is back in my court, and I've been overwhelmed these past few weeks to get it over with. Thank you, genuinely, for offering. If you have time to create those issues on the JBS, I would greatly appreciate it.

The OCA can be an absolute pain, I feel you since my process took almost 2 months to be approved. I can't create the issues until you're approved though, unfortunately :(

Don't worry though, I'll be watching your PRs and waiting for you to get approved, and I'll create the issues the moment that happens ;)

Have a great day!

**Comment by SWinxy** [comment]
Keeping open.

**Comment by TheShermanTanker** [comment]
@SWinxy Gratz on getting the contributor status! I've created an issue on the tracker for you, please rename the title of this PR to just 8286269 and the automated system should take care of the rest and send your PR for review!

**Comment by SWinxy** [comment]
@TheShermanTanker You are a legend! Thank you for all this. I've added it to #7096 and #7097, too, though I wanna double check that my changes in #7098 are right before doing it to that one. I have time tomorrow to merge the conflicts for this PR. Can't thank you enough, btw. You have been super helpful, being there when it feels like I'm screaming into the void.

**Comment by TheShermanTanker** [comment]
> @TheShermanTanker You are a legend! Thank you for all this. I've added it to #7096 and #7097, too, though I wanna double check that my changes in #7098 are right before doing it to that one. I have time tomorrow to merge the conflicts for this PR. Can't thank you enough, btw. You have been super helpful, being there when it feels like I'm screaming into the void.

No problems mate, this was what I faced too when joining as a contributor, so I know how it feels ;)

**Comment by SWinxy** [comment]
> No problems mate, this was what I faced too when joining as a contributor, so I know how it feels ;)
Then I should pass the wisdom on. (I also fixed the conflict from the web view rather than having to go into my IDE, which must be new. Super quick!)

**Comment by TheShermanTanker** [comment]
You do need to become a registered Author to properly help new contributors though, but the requirement is only that you have 2 accepted PRs in the codebase. With the 4 PRs you already have, you should be able to get to Author in no time if all 4 get through :)

**Comment by SWinxy** [comment]
:)

**Review by prrace — CHANGES_REQUESTED** [review]
Please do NOT just show up with a changeset. It is a waste of your time and ours.
Send email to the client mailing list to discuss first.
The amount of attention needed to review these changes and test them is out of all proportion to the absolutely zero benefit to users. 
As client lead, I suggest you find changes that actually make the product better, not these where the only possible change anyone can detect is a regression.
Withdraw and close as will not fix.

**Comment by kevinrushforth** [comment]
For future contributions, I invite you to familiarize yourself with the [OpenJDK Contributing Guide](https://openjdk.java.net/guide/), and particularly the ["Socialize your change"](https://openjdk.java.net/guide/#socialize-your-change) section, which highlights the importance of discussing non-trivial changes ahead of time on the appropriate mailing list (client-libs-dev "at" openjdk.java.net, in this case), rather than just showing up with a pull request.

**Pull request closed without merging**
