### PR TITLE
8277878: Fix compiler tests after JDK-8275908

### PR DESCRIPTION
**Pull request by simonis**
This is a quick fix for the two compiler tests introduced by JDK-8275908. The test explicitly added SerialGC in the parameter list which leads to a garbage collector conflict, if the tests are run with some other Garbage collector.

It was suggested to fix this by adding a `@requires vm.gc.Serial` tag but this is not necessary because the tests are actually GC-agnostic so I've removed the `-XX:+UseSerialGC` parameter from the test command line instead.

After the fix it was necessary to refine the check for whether the test JVM has JVMCI support built-in. Before the fix, I used  `WhiteBox.getWhiteBox().isJVMCISupportedByGC()` which worked fine if only running with SerialGC. Now that we can run with GCs which don't support JVMCI we have to use the more specific `(WB.getBooleanVMFlag("EnableJVMCI") != null)`.

Please let me know if you want me to push this instantly after it has been reviewed or if you first want to re-run your internal Tier3 tests before pushing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277878](https://bugs.openjdk.java.net/browse/JDK-8277878): Fix compiler tests after JDK-8275908

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6581/head:pull/6581` \
`$ git checkout pull/6581`

Update a local copy of the PR: \
`$ git checkout pull/6581` \
`$ git pull https://git.openjdk.java.net/jdk pull/6581/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6581`

View PR using the GUI difftool: \
`$ git pr show -t 6581`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6581.diff">https://git.openjdk.java.net/jdk/pull/6581.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
That looks good and trivial to me.

**Review by chhagedorn — APPROVED** [review]
Looks good! I guess it does not hurt to quickly verify it. Tier3 testing is submitted, will get back to you with the results.

**Comment by simonis** [comment]
Thanks @chhagedorn, @TobiHartmann!

I'll wait with submitting until @chhagedorn reports back the Tier3 results.

**Comment by dholmes-ora** [comment]
@simonis  the submitted tests have passed. Thanks.

**Comment by simonis** [comment]
Thanks @dholmes-ora.

**Pull request closed without merging**
