### PR TITLE
8253659: ProblemList sun/security/ec/TestEC.java on linux-aarch64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Reduce noise in CI Tier2 by ProblemListing this test.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253659](https://bugs.openjdk.java.net/browse/JDK-8253659): ProblemList sun/security/ec/TestEC.java on linux-aarch64

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/362/head:pull/362`
`$ git checkout pull/362`

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
My Tier2 test job ran sun/security/ec/TestEC.java on all regular Oracle
platforms except for linux-aarch64. I also updated the generic-ARCH
header comment to include 'aarch64' in the list so folks don't have to
wonder whether to use 'aarch64' or 'arm' or 'arm64'.

**Review by iklam — APPROVED** [review]

**Comment by iklam** [comment]
Looks like a trivial change to me.

**Comment by dcubed-ojdk** [comment]
@iklam - thanks for the fast review.
/integrate

**Comment by dcubed-ojdk** [comment]
Tony - sorry about that. The last time I checked your bug (about 2 hours ago)
it wasn't "in progress". Please update your fix to remove the test from the
ProblemList.

**Pull request closed without merging**
