### PR TITLE
8329764: G1: Handle null references during verification first

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that suggests to move the null reference check in object iteration during heap verification first.

The reason is as stated, since null references are fairly common (not only in that test mentioned in https://bugs.openjdk.org/browse/JDK-8329314), it may make sense to put it first. Also, null references never fail anyway (and verification failure is supposed to be uncommon).

Improves total runtime of that test case from 3s (~3.9s cpu time) to 2.2s (~3.1s cpu time).

If you think it makes the code too ugly, I will retract it.

Testing: gha, local testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329764](https://bugs.openjdk.org/browse/JDK-8329764): G1: Handle null references during verification first (**Enhancement** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18650/head:pull/18650` \
`$ git checkout pull/18650`

Update a local copy of the PR: \
`$ git checkout pull/18650` \
`$ git pull https://git.openjdk.org/jdk.git pull/18650/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18650`

View PR using the GUI difftool: \
`$ git pr show -t 18650`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18650.diff">https://git.openjdk.org/jdk/pull/18650.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18650#issuecomment-2039535270)

### CODE REVIEW

**Comment by tschatzl** [comment]
Fwiw, removing the `assert(_containing_obj != nullptr` but keeping other code as is gives the following results: runtime 2.65s (cpu time 3.2s), so it may still be worth changing the code as suggested.

**Comment by stefank** [comment]
I integrated the simplest version of #18595 now. I still think it would be nice to clean away the assert(_containing_obj...) with my proposed changes. Should I do that? Or do you have some other plan for it?

**Comment by tschatzl** [comment]
> I integrated the simplest version of https://github.com/openjdk/jdk/pull/18595 now. I still think it would be nice to clean away the assert(_containing_obj...) with my proposed changes. Should I do that? Or do you have some other plan for it?

I am good with moving the `assert` too (not sure if it is worth an extra change or adding it here); however this change, i.e. moving the condition, would improve performance beyond moving the assert as shown above.

The other changes from you about extracting the failure counter could be done as well - when refactoring this verification code the last time the extra 30 LOC or so did not seem worth to me, but the code is already fairly large.

There are no further plans from me to improve verification performance further, apart from maybe filing a CR to parallelize verification of large object arrays.

Does that answer your questions?

**Comment by stefank** [comment]
> > I integrated the simplest version of #18595 now. I still think it would be nice to clean away the assert(_containing_obj...) with my proposed changes. Should I do that? Or do you have some other plan for it?
> 
> I am good with moving the `assert` too (not sure if it is worth an extra change or adding it here); however this change, i.e. moving the condition, would improve performance beyond moving the assert as shown above.
> 
> The other changes from you about extracting the failure counter could be done as well - when refactoring this verification code the last time the extra 30 LOC or so did not seem worth to me, but the code is already fairly large.
> 
> There are no further plans from me to improve verification performance further, apart from maybe filing a CR to parallelize verification of large object arrays.
> 
> Does that answer your questions?

I had hoped for a more clear yes or no. :)

**Comment by tschatzl** [comment]
> > > I integrated the simplest version of #18595 now. I still think it would be nice to clean away the assert(_containing_obj...) with my proposed changes. Should I do that? Or do you have some other plan for it?
> > 
> > 
> > I am good with moving the `assert` too (not sure if it is worth an extra change or adding it here); however this change, i.e. moving the condition, would improve performance beyond moving the assert as shown above.
> > The other changes from you about extracting the failure counter could be done as well - when refactoring this verification code the last time the extra 30 LOC or so did not seem worth to me, but the code is already fairly large.
> > There are no further plans from me to improve verification performance further, apart from maybe filing a CR to parallelize verification of large object arrays.
> > Does that answer your questions?
> 
> I had hoped for a more clear yes or no. :)

If unsure: Please move the assert and add the failure counter changes :) Would be good to have.

Thomas

**Comment by stefank** [comment]
I've opened #18677 for the null-check and failure counting.

**Comment by tschatzl** [comment]
Still saving ~200ms (release build) verifying that large array.

**Comment by tschatzl** [comment]
500ms on a fastdebug build.

**Comment by albertnetymk** [comment]
> I was think of something similar, also makes the iteration actually stop at G1MaxVerifyFailures instead of at some related but arbitrary larger number.

From https://github.com/openjdk/jdk/pull/18595

Stopping field-iteration at the specified limit sounds much nicer; can that be done instead of (or in addition to) this reordering?

**Review by stefank — APPROVED** [review]
Looks good to me.

**Comment by albertnetymk** [comment]
> this change speeds up the common case (no error, null references),

That's true, but the new logic is kind of surprising -- the threshold is checked after we de-ref the field; I would have expected the threshold controls the field-iteration/de-ref.

> making the VM exit faster after an error would require some way to abort iteration

I've noticed that the current iteration API lacks support for early returns...

In the optimal scenario:

```
for (field in obj) {
  oop = *field;

  if (oop == null)
    continue;

  if (!is_correct(oop)) {
    ++failure;
    if (failure >= threshold) {
      break;
    }
  }
}
```

Since threshold is only accessed during failure cases, the impact on performance should be minimal.

(This implementation relies on a new iteration API, and there may be overlooked details necessary for its proper functionality. Feel free to merge the current PR.)

**Comment by tschatzl** [comment]
> > this change speeds up the common case (no error, null references),
> 
> That's true, but the new logic is kind of surprising -- the threshold is checked after we de-ref the field; I would have expected the threshold controls the field-iteration/de-ref.

That is why I consider this change "ugly" as well.

Looking at perf counters, my hunch is that the two loads for the current failure counter and the bound (and comparison) are just much more expensive (in terms of cpu resources even if both branches are easily predicted) than the single pointer deref and check against `null`.

**Comment by tschatzl** [comment]
thanks @stef

**Pull request closed without merging**
