### PR TITLE
JDK-8300266: Detect Virtualization on Linux aarch64

### PR DESCRIPTION
**Pull request by MBaesken**
Currently we detect virtualization on Linux x86_64 (cpuid call) and Linux ppc64le ; the result is afterwards used e.g. in hs_err and JFR output.

On Linux aarch64 the detection is missing, this should be added.
One option would be to look at /sys/devices/virtual/dmi/id/product_name and related files , at least KVM and VMWare can be detected using these files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300266](https://bugs.openjdk.org/browse/JDK-8300266): Detect Virtualization on Linux aarch64

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12071/head:pull/12071` \
`$ git checkout pull/12071`

Update a local copy of the PR: \
`$ git checkout pull/12071` \
`$ git pull https://git.openjdk.org/jdk pull/12071/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12071`

View PR using the GUI difftool: \
`$ git pr show -t 12071`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12071.diff">https://git.openjdk.org/jdk/pull/12071.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — COMMENTED** [review]
Hi Matthias,

- can you give an example of such a line? I assume it won't overflow the 500 bytes, right?
- Does it have to live inside CPU/aarch? Would be better in the linux_aarch branch
- People start using `nullptr` instead of `NULL` now in earnest, might be better to use that instead.

Cheers, Thomas

**Comment by MBaesken** [comment]
Hi Thomas, thanks for the comments. I switched to nullptr.
The lines look like this 
/sys/devices/virtual/dmi/id/product_name
KVM Virtual Machine
and
VMware Virtual Platform
(sometimes they are slightly different, depending on the vendor)
From what I saw, they are rather short, not over 500 chars.
Regarding "Does it have to live inside CPU/aarch" - I just followed what we have on ppc64le and x86_64 where it is at the same place , so maybe easier to find if it's the same location across platforms.

**Review by tstuefe — APPROVED** [review]
LGTM

**Review by RealLucy — APPROVED** [review]
Looks good to me.

**Comment by dholmes-ora** [comment]
Looks to me like these should all be moved to vm_version_<os_arch>.cpp.  New RFE?

**Comment by MBaesken** [comment]
> Looks to me like these should all be moved to vm_version_<os_arch>.cpp. New RFE?

Hi David, this could indeed be a follow-up cleanup change.

Lutz/Thomas, thanks for the reviews.

/integrate

**Pull request closed without merging**
