### PR TITLE
8286647: JFR: Build failure when C1 or C2 is disabled after JDK-8282420

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

JDK fails to build when c1 or c2 is disabled after JDK-8282420.
The reason is that c1/c2 code is used without `#ifdef` guards.
The fix just adds some `#ifdef`.

Testing:
 - build   on Linux/x64
 - jdk/jfr on Linux/x64

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286647](https://bugs.openjdk.java.net/browse/JDK-8286647): JFR: Build failure when C1 or C2 is disabled after JDK-8282420

### Reviewers
 * [Markus Grönlund](https://openjdk.java.net/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8680/head:pull/8680` \
`$ git checkout pull/8680`

Update a local copy of the PR: \
`$ git checkout pull/8680` \
`$ git pull https://git.openjdk.java.net/jdk pull/8680/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8680`

View PR using the GUI difftool: \
`$ git pr show -t 8680`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8680.diff">https://git.openjdk.java.net/jdk/pull/8680.diff</a>

</details>

### CODE REVIEW

**Comment by mgronlun** [comment]
Is it possible to use the #ifdef's for only the #include <header> declarations in JfrResolution.cpp to help reduce the amount of conditionalisation? Thanks.

**Comment by DamonFool** [comment]
> Ok, the function definitions in the .cpp will also have to be conditionalised. Is the rest necessary? Forward declarations are just symbolic pointers until they reach their definition.

At the beginning, I didn't guard the forward declarations and the build still passed on my Linux/x64.
```
#ifdef COMPILER1
class GraphBuilder;
#endif

#ifdef COMPILER2
class Parse;
#endif
```

However, I'm not sure if all the compilers would pass without the  two `#ifdef` above.
So to make it to be safe enough, I just added them.

Are you sure it's safe to remove them? 
Thanks.

**Comment by mgronlun** [comment]
In general, we would like to reduce the amount of conditionalization because it makes the code harder to read and follow. Compilers should not require a definition until a definition is actually needed. Perhaps there are compilers out there that don't do this, but I can't think of any right now. If that is the case, we can revisit to add in the conditionals for them.

Please try to only conditionalize in jfrResolution.cpp if you can, thank you.

**Comment by DamonFool** [comment]
> In general, we would like to reduce the amount of conditionalization because it makes the code harder to read and follow. Compilers should not require a definition until a definition is actually needed. Perhaps there are compilers out there that don't do this, but I can't think of any right now. If that is the case, we can revisit to add in the conditionals for them.
> 
> Please try to only conditionalize in jfrResolution.cpp if you can, thank you.

OK.

I revert changes in the `jfr.hpp`.
Not sure if it's fine for all the compilers.
But as you mentioned that we can add them back if it's really a problem.

The remaining change is necessary on Linux/x64.
Thanks.

**Comment by mgronlun** [comment]
Is the ifdef in jfr.cpp needed? There is no type-use, only the forwarding of pointers.

**Comment by DamonFool** [comment]
> Is the ifdef in jfr.cpp needed? There is no type-use, only the forwarding of pointers.

Yes.
It uses `Parse` and `GraphBuilder`. 
You can just experiment it on Linux/x64.
Thanks.

**Review by mgronlun — APPROVED** [review]

**Comment by DamonFool** [comment]
Thanks @mgronlun for the review.
/integrate

**Pull request closed without merging**
