### PR TITLE
8186085: (opt) add filter(), flatMap(), and map() methods to OptionalDouble/Int/Long

### PR DESCRIPTION
**Pull request by amCap1712**
Hi all,
This PR intends to add filter, map and flatMap methods to the Optional classes for primitives. The rationale is consistency with the Optional class for objects and user convenience.
Thanks.
Regards,
Kartik

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8186085](https://bugs.openjdk.java.net/browse/JDK-8186085): (opt) add filter(), flatMap(), and map() methods to OptionalDouble/Int/Long

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/857/head:pull/857`
`$ git checkout pull/857`

### CODE REVIEW

**Comment by amCap1712** [comment]
Kindly review the patch. Thanks in advance!

**Comment by forax** [comment]
Hi !
thanks for taking the time to craft that pull request but this is typically the kind of patch that should be discussed on the mailing list first before creating a pull request.

There are several issues, one is that we want to retrofit OptionalInt, OptionalLong, etc to be Optional<int>, Optional<long> as part of project Valhalla so we don't want to add more methods in the primitive variants of Optional and Stream to avoid to be blocked later while trying retrofitting those classes due to these methods.
So we know that some methods are missing but we want to know first how the specialization of generics over primitive types works before adding those methods.

The second issue is that when you want to change the public API of the JDK, you have to create a CSR to ask to the CSR guys/girls leaded by Joe Darcy if the signature and the semantics of the methods you want to add are coherent with the rest of the API.

I recommend you to start by fixing bugs because those can be fixed by a simple pull request.

regards,
Rémi

**Comment by amCap1712** [comment]
Thank you for the suggestions. I'll try fixing some bugs first. Should I close this PR as well or leave it open ?

**Comment by forax** [comment]
If it doesn't break your hart too much, yes please.

**Comment by amCap1712** [comment]
Sure, no worries. I am new to the project and understand that it'll take some time to understand how the project works and make some valuable contributions. In the future, I'll take care of first discussing on the appropriate mailing list before proposing patches. Thanks again.

**Pull request closed without merging**
