### PR TITLE
8346667: Doccheck: warning about missing </span> before <h2>

### PR DESCRIPTION
**Pull request by nizarbenalla**
Please review this doc-only patch to avoid some unwanted failures in our HTML checks. 

Javadoc wraps everything under `@param` in a `<span>`, so having an `h2` tag there trips some of our tests that use html validators (html-tidy and some other tests). I believe you shouldn't have an `<h2>` inside of a span.

This patch moves the text about "Value-based classes and identity operations" above the `@param` tag, it will now be rendered at the bottom of the class documentation.

This will need to be backported to JDK 24.

TIA.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8346667](https://bugs.openjdk.org/browse/JDK-8346667): Doccheck: warning about missing &lt;/span&gt; before &lt;h2&gt; (**Bug** - P4)

### Reviewers
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22833/head:pull/22833` \
`$ git checkout pull/22833`

Update a local copy of the PR: \
`$ git checkout pull/22833` \
`$ git pull https://git.openjdk.org/jdk.git pull/22833/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22833`

View PR using the GUI difftool: \
`$ git pr show -t 22833`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22833.diff">https://git.openjdk.org/jdk/pull/22833.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22833#issuecomment-2555183726)
</details>

### CODE REVIEW

**Comment by PaulSandoz** [comment]
I suggest you try and move this section immediately above the `@param` declaration and see if that resolves things. This section was intended to be part of the class documentation.

**Comment by nizarbenalla** [comment]
Done, thanks for the suggestion. The problem seems to have gone away.

**Pull request closed without merging**
