### PR TITLE
8319548: Unexpected internal name for Filler array klass causes error in VisualVM

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that changes the filler array class name (again) after user feedback.

In particular, the previous name `Ljdk/internal/vm/FillerArray;` confuses some tools (https://github.com/oracle/visualvm/issues/523). I.e. it's not an array, but still variable sized.
This change adds the `[` array bracket, and renames the element name to not have `Array` inside to not try to pretend that the element is some other kind of array.

Testing: tier1-6

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319548](https://bugs.openjdk.org/browse/JDK-8319548): Unexpected internal name for Filler array klass causes error in VisualVM (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Contributors
 * Tomáš Hůrka `<tomas.hurka@oracle.com>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17155/head:pull/17155` \
`$ git checkout pull/17155`

Update a local copy of the PR: \
`$ git checkout pull/17155` \
`$ git pull https://git.openjdk.org/jdk.git pull/17155/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17155`

View PR using the GUI difftool: \
`$ git pr show -t 17155`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17155.diff">https://git.openjdk.org/jdk/pull/17155.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17155#issuecomment-1862484503)

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]

**Comment by dholmes-ora** [comment]
I'm still struggling with what we are doing with this filler array stuff. IIUC the underlying type is actually `int[]` but we pretend it is `FillerElement[]`. Won't exposing this fake type just lead to further problems if tools try to inspect one of these arrays as-if it were an `Object[]` ??

**Comment by tschatzl** [comment]
> I'm still struggling with what we are doing with this filler array stuff. IIUC the underlying type is actually `int[]` but we pretend it is `FillerElement[]`. 

The reason for having dedicated filler array klasses is detecting internally in the GC that we are currently looking at a dead object. That the VM can distinguish dead objects from live objects is required for some functionality (like heap dumping only live classes, but also verification) without undue performance (basically need to redo marking every time this is needed) or memory usage hit (1.5% of maximum Java heap size) when invoking some APIs.

E.g. any reference from a live object to a dead object will immediately assert.

There is also improved debugability due to that - i.e. if you see a reference to any such klass in a hs_err file, it is 99% an error with a reference where the barrier has been forgotten.

The reason for having a custom array type and not having a klass referencing `int` elements is because Hotspot does not support that.

> Won't exposing this fake type just lead to further problems if tools try to inspect one of these arrays as-if it were an `Object[]` ??

We do not expose these arrays to regular APIs (e.g. we filter them out when iterating available klasses), and they are never referenced by other live objects by definition. So it is impossible for a Java application to get a reference to such objects or these klasses.

The only way they are exposed is in a heap dump also containing dead objects (and related functionality like the `jcmd` class histogram). Somebody at some time thought that this would be an interesting feature so we need to support it.

Previously one would get the same dead objects in that output just intermingled with other `int[]` arrays. Imo this discrimination is preferable and much more useful for heap analysis.

**Comment by tschatzl** [comment]
Fwiw, the original issue introducing details this too https://bugs.openjdk.org/browse/JDK-8284435; it does not particularly point out how much memory this saves, but it mentions that it removes the need for keeping around an extra mark bitmap covering the whole Java heap (that 1.5%).

**Comment by dholmes-ora** [comment]
Thanks for clarifying @tschatzl that these pretend arrays are only exposed in this one case.

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks

**Comment by tschatzl** [comment]
Thanks @albertnetymk @dholmes-ora for your reviews
/integrate

**Comment by jjscl8888** [comment]
I observed a phenomenon on our application. When there is no traffic on a certain instance, the number of old generation objects suddenly increases at a certain moment. After dumping the object instances, I found a large number of jdk.internal.vm.FillerArray objects, occupying more than 10G of memory. Have you ever encountered this?
image

**Comment by tschatzl** [comment]
> I observed a phenomenon on our application. When there is no traffic on a certain instance, the number of old generation objects suddenly increases at a certain moment. After dumping the object instances, I found a large number of jdk.internal.vm.FillerArray objects, occupying more than 10G of memory. Have you ever encountered this?

You probably did the heap dump right after G1 managed to free lots of memory - these `FillerArray` elements represent unused memory within regions.

Previously one would have seen a huge amount of int-arrays (`[I`) staying around.

Normally G1 would then incrementally reduce these `FillerArray`s in subsequent mixed collections (after marking etc) by evacuating the live objects between these filler objects, making these regions completely empty.

From the given output of `jmap` and not knowing what else is going on with the GC this behavior seems normal.

**Comment by jjscl8888** [comment]
> > I observed a phenomenon on our application. When there is no traffic on a certain instance, the number of old generation objects suddenly increases at a certain moment. After dumping the object instances, I found a large number of jdk.internal.vm.FillerArray objects, occupying more than 10G of memory. Have you ever encountered this?
> 
> You probably did the heap dump right after G1 managed to free lots of memory - these `FillerArray` elements represent unused memory within regions.
> 
> Previously one would have seen a huge amount of int-arrays (`[I`) staying around.
> 
> Normally G1 would then incrementally reduce these `FillerArray`s in subsequent mixed collections (after marking etc) by evacuating the live objects between these filler objects, making these regions completely empty.
> 
> From the given output of `jmap` and not knowing what else is going on with the GC this behavior seems normal.

image
Thank you for your clarification. if the instance in question had no traffic but you observed a sudden increase in the old generation size at 2:35 in the graph, and subsequent garbage collections (GCs) did not reduce the size of the old generation back to its original value

**Comment by tschatzl** [comment]
(because the bot does not seem to forward the answer from the mailing list within a few hours; fwiw, it has been pure luck that I stumbled across that question within github):

On 30.04.24 03:38, jjscl8888 wrote:
>  Thank you for your clarification. if the instance in question had no
> traffic but you observed a sudden increase in the old generation size
> at 2:35 in the graph, and subsequent garbage collections (GCs) did not
> reduce the size of the old generation back to its original value

Collectors are fairly reluctant to give back memory to the OS.

For G1 in particular, there are the options `MinHeapFreeRatio` and `MaxHeapFreeRatio` which to some degree steer commit and uncommit.

* `MinHeapFreeRatio` is "The minimum percentage of heap free after GC to avoid expansion", i.e. minimum amount of memory should be kept free. Default is 40%, i.e. expands if less than that amount of memory is free.

* `MaxHeapFreeRatio` is "The maximum percentage of heap free after GC to avoid shrinking", i.e. maximum amount of memory that should be kept free. Default is 70%; i.e. only shrinks the heap if more than 70% of memory is free.

Not sure the latter condition is met here to shrink, and without logs (`-Xlog:gc+ergo+heap=debug`) this is just a guess. Also, this kind of heap resizing (including shrinking) only occurs in the Remark pause.

So to decrease the heap more aggressively, it might work to decrease `MaxHeapFreeRatio` (and probably `MinHeapFreeRatio` too because for such large heaps the default values are maybe not optimal).

Hth,
  Thomas

**Comment by jjscl8888** [comment]
> (because the bot does not seem to forward the answer from the mailing list within a few hours; fwiw, it has been pure luck that I stumbled across that question within github):
> 
> On 30.04.24 03:38, jjscl8888 wrote:
> 
> > Thank you for your clarification. if the instance in question had no
> > traffic but you observed a sudden increase in the old generation size
> > at 2:35 in the graph, and subsequent garbage collections (GCs) did not
> > reduce the size of the old generation back to its original value
> 
> Collectors are fairly reluctant to give back memory to the OS.
> 
> For G1 in particular, there are the options `MinHeapFreeRatio` and `MaxHeapFreeRatio` which to some degree steer commit and uncommit.
> 
> * `MinHeapFreeRatio` is "The minimum percentage of heap free after GC to avoid expansion", i.e. minimum amount of memory should be kept free. Default is 40%, i.e. expands if less than that amount of memory is free.
> * `MaxHeapFreeRatio` is "The maximum percentage of heap free after GC to avoid shrinking", i.e. maximum amount of memory that should be kept free. Default is 70%; i.e. only shrinks the heap if more than 70% of memory is free.
> 
> Not sure the latter condition is met here to shrink, and without logs (`-Xlog:gc+ergo+heap=debug`) this is just a guess. Also, this kind of heap resizing (including shrinking) only occurs in the Remark pause.
> 
> So to decrease the heap more aggressively, it might work to decrease `MaxHeapFreeRatio` (and probably `MinHeapFreeRatio` too because for such large heaps the default values are maybe not optimal).
> 
> Hth, Thomas

Thank you for your previous question. I have another inquiry regarding compiling the JDK source code. I've noticed that when I compile the JDK without selecting specific configure parameters, the resulting JDK size differs from the official version available on the website. I'm curious to know which configuration parameters were used for the official LTS (Long-Term Support) version of the JDK.

**Pull request closed without merging**
