### PR TITLE
8271569: Change cdsoffsets.cpp to cdsConstants.cpp

### PR DESCRIPTION
**Pull request by yminqi**
Changed cdsOffsets.cpp to cdsConstants.cpp, now the offsets and constants are initialized static and searched separately.
The offsets array could not use 'constexpr' since g++ on MacOs and VSC++ on Windows complained reinterpret_cast in 'offset_of' should not be used in constexpr initialization. Changed some field access for forming global list first.

Tests: ter1-4

Thanks
Yumin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8271569](https://bugs.openjdk.java.net/browse/JDK-8271569): Change cdsoffsets.cpp to cdsConstants.cpp

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5423/head:pull/5423` \
`$ git checkout pull/5423`

Update a local copy of the PR: \
`$ git checkout pull/5423` \
`$ git pull https://git.openjdk.java.net/jdk pull/5423/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5423`

View PR using the GUI difftool: \
`$ git pr show -t 5423`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5423.diff">https://git.openjdk.java.net/jdk/pull/5423.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi Yumin,

> Changed cdsOffsets.cpp to cdsConstants.cpp

This is not showing up in the PR as a rename but as a new file. So there is no way to know what changes you may have made inside cdsConstants.cpp. The header file change shows as a rename. 

David

**Comment by yminqi** [comment]
> Hi Yumin,
> 
> > Changed cdsOffsets.cpp to cdsConstants.cpp
> 
> This is not showing up in the PR as a rename but as a new file. So there is no way to know what changes you may have made inside cdsConstants.cpp. The header file change shows as a rename.
> 
> David

Hi, David
  git did not rename the 'old' to 'new' so the patch showed cdsConstants.cpp as a 'new' file. So I will change description as you indicated. Thanks

Yumin

**Comment by yminqi** [comment]
@dholmes-ora I see your point here --- let me redo the patch using rename.

**Pull request closed without merging**
