### PR TITLE
8324242: Avoid null check for OopHandle::ptr_raw()

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to use OopHandle::is_empty() rather than comparing
the result of OopHandle::ptr_raw() with nullptr.  While equivalent, the former
is the intended API for such checks.  ptr_raw should only be used directly
where it is actually needed.

Testing: mach5 tier1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324242](https://bugs.openjdk.org/browse/JDK-8324242): Avoid null check for OopHandle::ptr_raw() (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**) ⚠️ Review applies to [f387b8f3](https://git.openjdk.org/jdk/pull/17510/files/f387b8f3e1bb6f2c129f15ee1bf57a71cc09e3be)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [f387b8f3](https://git.openjdk.org/jdk/pull/17510/files/f387b8f3e1bb6f2c129f15ee1bf57a71cc09e3be)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17510/head:pull/17510` \
`$ git checkout pull/17510`

Update a local copy of the PR: \
`$ git checkout pull/17510` \
`$ git pull https://git.openjdk.org/jdk.git pull/17510/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17510`

View PR using the GUI difftool: \
`$ git pr show -t 17510`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17510.diff">https://git.openjdk.org/jdk/pull/17510.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17510#issuecomment-1902542413)

### CODE REVIEW

**Comment by jdksjolen** [comment]
LGTM and trivial.

**Review by shipilev — APPROVED** [review]
Looks reasonable. 

I guess the use in `ClassLoaderData::remove_handle` is fine, because we want to assert it?

Related, pre-existing: the use in `ClassLoaderData::print_on` is also odd. This reports the address of oophandle slot, not the classloader oop itself? Should probably be `.peek()`?

```
  out->print_cr(" - class loader        " INTPTR_FORMAT, p2i(_class_loader.ptr_raw()));
```

**Review by jdksjolen — APPROVED** [review]
Oh, I didn't approve it in my last comment.

**Review by coleenp — COMMENTED** [review]
Can ptr_raw be made private with this change?

**Review by coleenp — APPROVED** [review]
Answer to my previous question.  I guess not.

**Comment by kimbarrett** [comment]
> Can ptr_raw be made private with this change?

Not yet.  That's the general direction I was trying for, but I'm not sure it's achievable.  At least not without some
serious reworking of some OopHandle uses.  But I found some little cleanups like this while I was exploring.

**Comment by kimbarrett** [comment]
> Looks reasonable.
> 
> I guess the use in `ClassLoaderData::remove_handle` is fine, because we want to assert it?

I forgot about this one.  I initially skipped it because I didn't understand what was happening here.  I'd forgotten that
the CLD uses OopHandle to wrap a pointer to the CLD handle area rather than an OopStorage entry. I'll push a fix
after I've run tests.

> Related, pre-existing: the use in `ClassLoaderData::print_on` is also odd. This reports the address of oophandle slot, not the classloader oop itself? Should probably be `.peek()`?
> 
> ```
>   out->print_cr(" - class loader        " INTPTR_FORMAT, p2i(_class_loader.ptr_raw()));
> ```

I think you are probably correct, but felt that was a little out of scope for
what I was doing in this PR.

It looks like it was changed from printing the (void* cast) loader oop to
printing the (newly introduced) handle address by 8201556: "Disallow reading
oops in ClassLoaderData if unloading". I don't know whether that was
intentional, but guessing not.

**Comment by kimbarrett** [comment]
> > Related, pre-existing: the use in `ClassLoaderData::print_on` is also odd. This reports the address of oophandle slot, not the classloader oop itself? Should probably be `.peek()`?
> > ```
> >   out->print_cr(" - class loader        " INTPTR_FORMAT, p2i(_class_loader.ptr_raw()));
> > ```
> 
> I think you are probably correct, but felt that was a little out of scope for what I was doing in this PR.
> 
> It looks like it was changed from printing the (void* cast) loader oop to printing the (newly introduced) handle address by 8201556: "Disallow reading oops in ClassLoaderData if unloading". I don't know whether that was intentional, but guessing not.

https://bugs.openjdk.org/browse/JDK-8324514
ClassLoaderData::print_on should print address of class loader

**Comment by shipilev** [comment]
> https://bugs.openjdk.org/browse/JDK-8324514 ClassLoaderData::print_on should print address of class loader

Thanks. I'll handle that one, so you don't need to go too far into this rabbit hole :)

**Comment by kimbarrett** [comment]
> > Looks reasonable.
> > I guess the use in `ClassLoaderData::remove_handle` is fine, because we want to assert it?
> 
> I forgot about this one. I initially skipped it because I didn't understand what was happening here. I'd forgotten that the CLD uses OopHandle to wrap a pointer to the CLD handle area rather than an OopStorage entry. I'll push a fix after I've run tests.

Non-assert code now just uses is_empty.  However, the assert has to use ptr_raw, unfortunately.

**Review by shipilev — APPROVED** [review]
Looks okay. Pity we were not able to eliminate the `ptr_raw` use completely.

**Comment by kimbarrett** [comment]
> Looks okay. Pity we were not able to eliminate the `ptr_raw` use completely.

Some of the remaining would require a lot more preparatory work, if possible at all.

Thanks for reviews, @jdksjolen , @shipilev , and @coleenp .

**Pull request closed without merging**
