### PR TITLE
8279437: [JVMCI] exception in HotSpotJVMCIRuntime.translate can exit the VM

### PR DESCRIPTION
**Pull request by dougxc**
This PR addresses the problem reported in JDK-8279437 by adding support for transferring exceptions from HotSpot into libgraal (the other way around was already supported).
It also improves the translation of exceptions by:
* using a native (resource) buffer more directly for serializing an exception
* changing the serialization format to be a gzipped binary representation as it is much smaller than the string representation currently used and avoids having to worry about special characters (e.g. a `|` in an exception's message string).

It also adds the `jvmci.ForceTranslateFailure` option to allow testing handling of failures in `HotSpotJVMCIRuntime.translate`. See https://github.com/oracle/graal/commit/b3a6ce471e0d116196d6fde1c62377191f5db4ec for such a test.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279437](https://bugs.openjdk.java.net/browse/JDK-8279437): [JVMCI] exception in HotSpotJVMCIRuntime.translate can exit the VM

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 38a2f3f67e1182142be84a35b478cc6dd56ea5e9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6951/head:pull/6951` \
`$ git checkout pull/6951`

Update a local copy of the PR: \
`$ git checkout pull/6951` \
`$ git pull https://git.openjdk.java.net/jdk pull/6951/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6951`

View PR using the GUI difftool: \
`$ git pr show -t 6951`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6951.diff">https://git.openjdk.java.net/jdk/pull/6951.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good. Thank you for testing it.

**Comment by vnkozlov** [comment]
Please, update copyright year to 2022 in changed files.

**Comment by dougxc** [comment]
> Please, update copyright year to 2022 in changed files.

I've done it but this should really be automated some how. I thought there is (was?) a script that runs over all JDK sources once a year to fix copyright dates?

**Pull request closed without merging**
