### PR TITLE
8278471: Remove unreached rules in AddNode::IdealIL

### PR DESCRIPTION
**Pull request by CptGit**
Reorder optimizations in addnode so special cases appear before general cases; otherwise the special cases would be never covered.

`(a - b) + (c - d)` subsumes both `(a - b) + (b - c)` and `(a - b) + (c - a)`. Therefore `(a - b) + (b - c)` and `(a - b) + (c - a)` have to be placed before `(a - b) + (c - d)` so that they can work.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278471](https://bugs.openjdk.java.net/browse/JDK-8278471): Remove unreached rules in AddNode::IdealIL

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6752/head:pull/6752` \
`$ git checkout pull/6752`

Update a local copy of the PR: \
`$ git checkout pull/6752` \
`$ git pull https://git.openjdk.java.net/jdk pull/6752/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6752`

View PR using the GUI difftool: \
`$ git pr show -t 6752`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6752.diff">https://git.openjdk.java.net/jdk/pull/6752.diff</a>

</details>

### CODE REVIEW

**Comment by fmatte1** [comment]
related JBS issue - https://bugs.openjdk.java.net/browse/JDK-8278471

**Comment by merykitty** [comment]
We actually don't need those since `(x - c) + (c - y)` would be transformed into `(x + c) - (c + y)` which will be transformed into `x - y` anyway. So you can safely remove them completely.

https://github.com/openjdk/jdk/blob/10a51fdb05abe7f7be76a9c442bd4564b24010de/src/hotspot/share/opto/subnode.cpp#L256

**Comment by CptGit** [comment]
> We actually don't need those since `(x - c) + (c - y)` would be transformed into `(x + c) - (c + y)` which will be transformed into `x - y` anyway. So you can safely remove them completely.
> 
> https://github.com/openjdk/jdk/blob/10a51fdb05abe7f7be76a9c442bd4564b24010de/src/hotspot/share/opto/subnode.cpp#L256

Thank you for pointing this out! I have two questions:

1. Should I just go ahead and delete these two, (a - b) + (b - c) and (a - b) + (c - a), in this pr?

2. I do see you are familiar with the concatenation of different optimizations. I was wondering where I am able to find more information about the order the functions are called, for example Ideal(), Value(), Identity(), or even better the entire workflow of optimization.

Thank you very much!

**Comment by merykitty** [comment]
Hi, I think just deleting those 2 should be okay.

Regarding idealisation, if you look into `PhaseGVN::transform`, it is clear that `Node::Ideal` is called repeatedly until there is nothing change anymore. Then `Node::Value` is called to do constant propagation before `Node::Identity` is called to get rid of redundant operations. Finally, value numbering is the transformation which deduplicates all equivalent `Node`s into a single one.

https://github.com/openjdk/jdk/blob/ccdb9f1b160a0f49ee86c7a2714d2381d68419cc/src/hotspot/share/opto/phaseX.cpp#L828

**Comment by CptGit** [comment]
> Hi, I think just deleting those 2 should be okay.
> 
> Regarding idealisation, if you look into `PhaseGVN::transform`, it is clear that `Node::Ideal` is called repeatedly until there is nothing change anymore. Then `Node::Value` is called to do constant propagation before `Node::Identity` is called to get rid of redundant operations. Finally, value numbering is the transformation which deduplicates all equivalent `Node`s into a single one.
> 
> https://github.com/openjdk/jdk/blob/ccdb9f1b160a0f49ee86c7a2714d2381d68419cc/src/hotspot/share/opto/phaseX.cpp#L828

Thank you so much for answering both my questions!

**Review by DamonFool — APPROVED** [review]
LGTM

The removed rules actually never be reached before.
So removing them won't make performance any worse.

And the removed opts are already done by (AddNode::IdealIL + SubINode::Ideal).

However, it would be better to change the JBS title as something like 'Remove unreached rules in AddNode::IdealIL'
Thanks.

**Comment by CptGit** [comment]
> 

Thank you for your review. @DamonFool Would you mind making the change to JBS for me? I don't have an account there, so I am not able to edit. Thanks.

**Comment by DamonFool** [comment]
> > 
> 
> Thank you for your review. @DamonFool Would you mind making the change to JBS for me? I don't have an account there, so I am not able to edit. Thanks.

The JBS title had been updated.
Thanks.

**Comment by DamonFool** [comment]
> /integrate

Hi @CptGit , you need at least two reviews for hotspot changes.
So one more review is required.

**Comment by CptGit** [comment]
> > /integrate
> 
> Hi @CptGit , you need at least two reviews for hotspot changes. So one more review is required.

It thought it can be integrated since the bot told me.Thanks for letting me know the requirement.

**Comment by lgxbslgx** [comment]
@DamonFool Now we have the command **reviewers** to change the number of the required reviewers. Hope more developers know this.

**Comment by DamonFool** [comment]
> @DamonFool Now we have the command **reviewers** to change the number of the required reviewers. Hope more developers know this.

Nice!
Got it and thanks @lgxbslgx  .

/reviewers 2 reviewer

**Comment by lgxbslgx** [comment]
> @DamonFool Usage: /reviewers <n> [<role>] where <n> is the number of required reviewers. If role is set, the reviewers need to have that project role. If omitted, role defaults to authors.
> Number of required reviewers of role reviewers cannot be decreased below 3

@DamonFool Unfortunately, it seems that you meet a bug. I filed [SKARA-1288](https://bugs.openjdk.java.net/browse/SKARA-1288) to follow up.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Before you integrate this, please, IR framework test which checks that conversions are really happened. Especially ones you removed.

**Comment by CptGit** [comment]
> Before you integrate this, please, add IR framework test which checks that conversions are really happened. Especially ones you removed.

Thanks a lot @vnkozlov for the suggestion of IR test. I added a test and found long type not working. Then I realized "long" does not have two conversions from "int" so I added them. These IR tests helped! Thank you!

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by DamonFool — APPROVED** [review]

**Pull request closed without merging**
