### PR TITLE
8309218: java/util/concurrent/locks/Lock/OOMEInAQS.java still times out with ZGC, Generational ZGC, and SerialGC

### PR DESCRIPTION
**Pull request by viktorklang-ora**
As per conversation in the issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309218](https://bugs.openjdk.org/browse/JDK-8309218): java/util/concurrent/locks/Lock/OOMEInAQS.java still times out with ZGC, Generational ZGC, and SerialGC (**Bug** - P3)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17313/head:pull/17313` \
`$ git checkout pull/17313`

Update a local copy of the PR: \
`$ git checkout pull/17313` \
`$ git pull https://git.openjdk.org/jdk.git pull/17313/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17313`

View PR using the GUI difftool: \
`$ git pr show -t 17313`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17313.diff">https://git.openjdk.org/jdk/pull/17313.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17313#issuecomment-1881837445)

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Viktor, the skara bot very helpfully has noted that this test has been problemlisted in a couple of files:

> 8309218 is used in problem lists: [test/jdk/ProblemList-zgc.txt, test/jdk/ProblemList-generational-zgc.txt]

so this current PR which is proposing to fix that test would have to remove it from those two problem lists.

**Comment by viktorklang-ora** [comment]
@jaikiran Gah, you're obviously right, I've amended the problem lists and updated the copyright years there as well.

**Review by jaikiran — APPROVED** [review]
Hello Viktor, the changes look OK to me.

This test resides in `tier1`, so if not already done, then I would suggest running tier1 once to be sure there are no unexpected issues and given that this is a GC reliant test then additionally running only this test in the CI, with a --test-repeat of something like 50, might also be a good way to see if there any intermittent failures.

**Review by dholmes-ora — APPROVED** [review]
Looks good. Restricting to only using G1, which has not been failing, seems the best thing to do here.

Thanks.

**Review by AlanBateman — APPROVED** [review]
The effect of `@requires vm.gc.G1` is that the test won't be selected when there is a test run that uses a different GC. Make sense and I agree restricting this test to one GC make sense.

**Comment by viktorklang-ora** [comment]
@jaikiran I've had it run tier1 (though not in a repeat loop), since the changes proposed here only affects the execution of the test and not changing the test itself, I thought it just made sense to have it run on tier1 once (after running the specific test itself on M5 100 times).

**Comment by jaikiran** [comment]
@viktorklang-ora  that sounds good to me.

**Pull request closed without merging**
