### PR TITLE
8258653: CallJavaNode::_bci is not in use

### PR DESCRIPTION
**Pull request by navyxliu**
The member variable CallJavaNode::_bci is completely dead in release build. 
In debug builds, CallJavaNode::validate_symbolic_info does refer to it, but 
the information can obtain from jvms()->bci(). CallJavaNode also copies _bci 
to MachCallJavaNode, but CodeGen doesn't use it as well.

/cc hotspot-compiler

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258653](https://bugs.openjdk.java.net/browse/JDK-8258653): CallJavaNode::_bci is not in use

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1834/head:pull/1834`
`$ git checkout pull/1834`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by iwanowww — APPROVED** [review]
Nice catch! Looks good.

**Comment by navyxliu** [comment]
May I call a sponsor to merge this? 

The failure  in pre-submit tests set is "java/util/HexFormat/HexFormatTest.java" in x86. 
```
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by navyxliu** [comment]
the HexFormatTest is tracking here:  https://bugs.openjdk.java.net/browse/JDK-8258584

**Comment by iwanowww** [comment]
I submitted the patch for additional testing. 
Will integrate it once the testing is over.

**Comment by navyxliu** [comment]
Thanks! @ iwanowww and @vnkozlov.

**Pull request closed without merging**
