### PR TITLE
8318837: javac generates wrong ldc instruction for dynamic constant loads

### PR DESCRIPTION
**Pull request by mcimadamore**
This PR fixes how javac loads dynamic variable symbols in `Gen` - currently, either a `ldc` or `ldc_w` is emitted. This is problematic, as, depending on the type of the dynamic constant, in some cases `ldc2_w` might be required (e.g. if the type of the constant is either `long` or `double`).

I've updated the existing compiler condy test to check which `ldc` opcode is emitted for the various constants. I've also verified that the updated test fails w/o the changes in this patch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318837](https://bugs.openjdk.org/browse/JDK-8318837): javac generates wrong ldc instruction for dynamic constant loads (**Bug** - P4)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [23d4ef69](https://git.openjdk.org/jdk/pull/16367/files/23d4ef69d8f7a940731cbdcb3bda79252f7551a8)
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**) ⚠️ Review applies to [59c0bfe4](https://git.openjdk.org/jdk/pull/16367/files/59c0bfe44cef06c88c85887d635512262b72d21f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16367/head:pull/16367` \
`$ git checkout pull/16367`

Update a local copy of the PR: \
`$ git checkout pull/16367` \
`$ git pull https://git.openjdk.org/jdk.git pull/16367/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16367`

View PR using the GUI difftool: \
`$ git pr show -t 16367`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16367.diff">https://git.openjdk.org/jdk/pull/16367.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16367#issuecomment-1779763398)

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Comment by vicente-romero-oracle** [comment]
side: given that you are in the neighborhood :) does it makes sense to fold the cases for: `ldc2w` and `ldc2` at: `Code::emitop2`?

**Comment by mcimadamore** [comment]
> side: given that you are in the neighborhood :) does it make sense to fold the cases for: `ldc2w` and `ldc2` at: `Code::emitop2`?

I can - but, I realized when I wrote the patch that the naming of the constants is wrong. The JVMS only knows about these instructions:

* [ldc](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc)
* [ldc_w](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc_w)
* [ldc2_w](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc2_w)

While javac has `ldc`, `ldc2` and `ldc2_w`. So, I suspect javac's `ldc2` is really `ldc_w`. Should this be renamed too?

**Comment by vicente-romero-oracle** [comment]
> > side: given that you are in the neighborhood :) does it make sense to fold the cases for: `ldc2w` and `ldc2` at: `Code::emitop2`?
> 
> I can - but, I realized when I wrote the patch that the naming of the constants is wrong. The JVMS only knows about these instructions:
> 
>     * [ldc](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc)
> 
>     * [ldc_w](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc_w)
> 
>     * [ldc2_w](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.ldc2_w)
> 
> 
> While javac has `ldc`, `ldc2` and `ldc2_w`. So, I suspect javac's `ldc2` is really `ldc_w`. Should this be renamed too?

as you please but then you should also rename `ldc1` to plain `ldc`

**Comment by mcimadamore** [comment]
> > > side: given that you are in the neighborhood :) does it make sense to fold the cases for: `ldc2w` and `ldc2` at: `Code::emitop2`?

This turned out to be a very good suggestion, thanks! While doing it, I realized that we already had a method (`Types::constantType`) to get the `Type` of a constant, so the new method I added to `LoadableConstant` is not really required (and I have now removed it).

In the end I left the names as they are, beacuse, while confusing, when looking at `emitOp` they kind of make sense - e.g. 1/2 is used to denote the number of operand bytes. So at least it's self-consistent :-)

**Review by lahodaj — APPROVED** [review]
Looks good to me.

I wonder if we should also simplify `Items.ImmediateItem.ldc`, since now `Code.emitLdc` handles the long/double on its own?

**Comment by vicente-romero-oracle** [comment]
> > > > side: given that you are in the neighborhood :) does it make sense to fold the cases for: `ldc2w` and `ldc2` at: `Code::emitop2`?
> 
> This turned out to be a very good suggestion, thanks! While doing it, I realized that we already had a method (`Types::constantType`) to get the `Type` of a constant, so the new method I added to `LoadableConstant` is not really required (and I have now removed it).
> 
> In the end I left the names as they are, beacuse, while confusing, when looking at `emitOp` they kind of make sense - e.g. 1/2 is used to denote the number of operand bytes. So at least it's self-consistent :-)

last version looks good to me, thanks!

**Comment by mcimadamore** [comment]
> Looks good to me.
> 
> I wonder if we should also simplify `Items.ImmediateItem.ldc`, since now `Code.emitLdc` handles the long/double on its own?

Good catch - done

**Pull request closed without merging**
