### PR TITLE
8264196: Change link_and_cleanup_shared_classes(CATCH) to CHECK

### PR DESCRIPTION
**Pull request by calvinccheung**
Please review this simple fix for passing in CHECK instead of CATCH when calling `link_and_cleanup_shared_classes()` since it could throw an exception.

Testing: tiers 1 and 2 on mach5.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264196](https://bugs.openjdk.java.net/browse/JDK-8264196): Change link_and_cleanup_shared_classes(CATCH) to CHECK

### Reviewers
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3640/head:pull/3640` \
`$ git checkout pull/3640`

Update a local copy of the PR: \
`$ git checkout pull/3640` \
`$ git pull https://git.openjdk.java.net/jdk pull/3640/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3640`

View PR using the GUI difftool: \
`$ git pr show -t 3640`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3640.diff">https://git.openjdk.java.net/jdk/pull/3640.diff</a>

</details>

### CODE REVIEW

**Review by yminqi — APPROVED** [review]
LGTM

**Review by iklam — APPROVED** [review]
Looks good and trivial.

**Comment by calvinccheung** [comment]
@yminqi, @iklam, thanks for your quick review.

**Pull request closed without merging**
