### PR TITLE
8279315: Add Git support to update_copyright_year.sh script

### PR DESCRIPTION
**Pull request by ProjectD8**
Modified the `make/scripts/update_copyright_year.sh` script to support Git as well as Mercurial, as per [JDK-8279315](https://bugs.openjdk.java.net/browse/JDK-8279315). Also added the ability to specify company name as a command line argument instead of being hard-coded into the script.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279315](https://bugs.openjdk.java.net/browse/JDK-8279315): Add Git support to update_copyright_year.sh script

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7027/head:pull/7027` \
`$ git checkout pull/7027`

Update a local copy of the PR: \
`$ git checkout pull/7027` \
`$ git pull https://git.openjdk.java.net/jdk pull/7027/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7027`

View PR using the GUI difftool: \
`$ git pr show -t 7027`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7027.diff">https://git.openjdk.java.net/jdk/pull/7027.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]
Looks good. 

Did you consider automatically inferring the VCS by looking for `${this_script_dir}/../../{.git,.hg}`? To resolve `this_script_dir`, you can use the same snippet we have in e.g. top level configure:

```
# Get an absolute path to this script, since that determines the top-level directory.
this_script_dir=`dirname $0`
this_script_dir=`cd $this_script_dir > /dev/null && pwd`
```

**Comment by ProjectD8** [comment]
> Looks good.
> 
> Did you consider automatically inferring the VCS by looking for `${this_script_dir}/../../{.git,.hg}`? To resolve `this_script_dir`, you can use the same snippet we have in e.g. top level configure:
> 
> ```
> # Get an absolute path to this script, since that determines the top-level directory.
> this_script_dir=`dirname $0`
> this_script_dir=`cd $this_script_dir > /dev/null && pwd`
> ```

Thank you for the review, and for the suggestion! I've implemented the VCS auto-detection logic now, could you please take another look?

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
If you need help sponsoring the change, I can do that. You just need to follow the bots instructions and issue the integrate command first.

**Comment by ProjectD8** [comment]
@erikj79 I guess the bot says it's ready now, could you please sponsor the change?

**Comment by erikj79** [comment]
Sorry, I don't get any notification that it's ready to be sponsored.
/sponsor

**Pull request closed without merging**
