### PR TITLE
8268855: Cleanup name handling in the Thread class and subclasses 

### PR DESCRIPTION
**Pull request by dholmes-ora**
Please review this small cleanup item.

We can simplify and cleanup up name() management:

- make name() return "const char *" and only cast away constness at API boundaries when essential
- add type_name() so that we can avoid code like "if (t->is_VM_Thread()) print("VMThread");
- Rename JavaThread::get_thread_name() to name() (no need for the extra indirection)

There are a couple of minor changes to the appearance of some internal threads in the hs_err log e.g.

  0x000055af03e5b1b0 WatcherThread [stack: 0x00007f685df00000,0x00007f685e000000] [id=15952]

is now:

  0x000055af03e5b1b0 WatcherThread "VM Periodic Task Thread" [stack: 0x00007f685df00000,0x00007f685e000000] [id=15952]

but this shouldn't affect anything and makes things more consistent.

Notes: 

1. While "override" is the ideal style when declaring overriding methods it has to be applied to all virtual methods in a class. So unless "override" is already used in a class, I did not start using it. I have filed a separate RFE to convert the Thread classes to use "override" consistently.
2.  While there is no need to redeclare a virtual method as "virtual" I kept to the existing style in those classes where changes were made.
3. I did not override type_name() for all the JavaThread subclasses as it seemed unnecessary, but happy to hear other views on this.

Testing (in progress):
 - All builds in tiers 1-5
 - GHA
 - tiers 1-3 as a sanity test

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268855](https://bugs.openjdk.java.net/browse/JDK-8268855): Cleanup name handling in the Thread class and subclasses

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4569/head:pull/4569` \
`$ git checkout pull/4569`

Update a local copy of the PR: \
`$ git checkout pull/4569` \
`$ git pull https://git.openjdk.java.net/jdk pull/4569/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4569`

View PR using the GUI difftool: \
`$ git pr show -t 4569`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4569.diff">https://git.openjdk.java.net/jdk/pull/4569.diff</a>

</details>

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
Looks good!
Lois

**Comment by navyxliu** [comment]
LGTM.

**Review by coleenp — APPROVED** [review]
This looks good.

**Comment by dholmes-ora** [comment]
Thanks for the reviews.

/integrate

**Pull request closed without merging**
