### PR TITLE
8294979: test/jdk/tools/jlink 3 test classes use ASM library

### PR DESCRIPTION
**Pull request by xqoasis**
Modified 3 of 3 test/jdk/tools/jlink test classes to replace com.sun.tools.classfile library.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294979](https://bugs.openjdk.org/browse/JDK-8294979): test/jdk/tools/jlink 3 test classes use ASM library (**Sub-task** - P5)

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Koichi Sakata](https://openjdk.org/census#ksakata) (@jyukutyo - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14877/head:pull/14877` \
`$ git checkout pull/14877`

Update a local copy of the PR: \
`$ git checkout pull/14877` \
`$ git pull https://git.openjdk.org/jdk.git pull/14877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14877`

View PR using the GUI difftool: \
`$ git pr show -t 14877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14877.diff">https://git.openjdk.org/jdk/pull/14877.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14877#issuecomment-1654076109)

### CODE REVIEW

**Comment by asotona** [comment]
I would suggest to minimise footprint of the patch and do not change unrelated code.
Any unnecessary reformat can cause conflicts when merging into or from another project or when backporting.

**Comment by liach** [comment]
I think these exports can probably be removed completely; no test code uses ASM, meaning the export was likely redundant from the very beginning.

**Comment by asotona** [comment]
> I think these exports can probably be removed completely; no test code uses ASM, meaning the export was likely redundant from the very beginning.

I can confirm, the tests are passing even without the exports.

**Review by mlchung — APPROVED** [review]
Looks good.

**Review by jyukutyo — APPROVED** [review]

**Comment by jyukutyo** [comment]
I'll sponsor you. I've checked those tests passed.

**Pull request closed without merging**
