### PR TITLE
8331934: [s390x] Add support for primitive array C1 clone intrinsic

### PR DESCRIPTION
**Pull request by offamitkumar**
Adds JDK-8302850 Port for s390x. 

Testing: 
```
make test TEST="hotspot_compiler" JTREG="JAVA_OPTIONS=-XX:TieredStopAtLevel=1"

==============================                                                                                                          
Test summary                                                                                                                            
==============================                                                                                                          
   TEST                                              TOTAL  PASS  FAIL ERROR                                                            
   jtreg:test/hotspot/jtreg:hotspot_compiler          1166  1166     0     0                                                            
==============================                                                                                                          
TEST SUCCESS

* Tier1 Test with Fast debug build. 
```
BenchMarking:

```
Without Patch: 

Benchmark                 (size)  Mode  Cnt     Score    Error  Units
ArrayClone.byteArraycopy       0  avgt   15    10.838 ±  0.461  ns/op
ArrayClone.byteArraycopy      10  avgt   15    28.919 ±  1.695  ns/op
ArrayClone.byteArraycopy     100  avgt   15    48.815 ±  0.901  ns/op
ArrayClone.byteArraycopy    1000  avgt   15   256.357 ±  7.901  ns/op
ArrayClone.byteClone           0  avgt   15    90.398 ±  3.119  ns/op
ArrayClone.byteClone          10  avgt   15   103.774 ±  4.468  ns/op
ArrayClone.byteClone         100  avgt   15   126.628 ±  6.952  ns/op
ArrayClone.byteClone        1000  avgt   15   326.409 ± 31.635  ns/op
ArrayClone.intArraycopy        0  avgt   15    10.450 ±  0.509  ns/op
ArrayClone.intArraycopy       10  avgt   15    36.903 ±  0.753  ns/op
ArrayClone.intArraycopy      100  avgt   15    85.964 ±  1.806  ns/op
ArrayClone.intArraycopy     1000  avgt   15   841.512 ± 40.335  ns/op
ArrayClone.intClone            0  avgt   15    89.332 ±  3.695  ns/op
ArrayClone.intClone           10  avgt   15   110.639 ±  2.476  ns/op
ArrayClone.intClone          100  avgt   15   195.781 ±  8.622  ns/op
ArrayClone.intClone         1000  avgt   15  1058.479 ± 92.468  ns/op
Finished running test 'micro:java.lang.ArrayClone'


with patch:

Benchmark                 (size)  Mode  Cnt    Score    Error  Units
ArrayClone.byteArraycopy       0  avgt   15   10.526 ±  0.289  ns/op
ArrayClone.byteArraycopy      10  avgt   15   27.110 ±  0.656  ns/op
ArrayClone.byteArraycopy     100  avgt   15   49.872 ±  1.562  ns/op
ArrayClone.byteArraycopy    1000  avgt   15  269.518 ±  4.567  ns/op
ArrayClone.byteClone           0  avgt   15   10.766 ±  0.899  ns/op
ArrayClone.byteClone          10  avgt   15   18.341 ±  0.394  ns/op
ArrayClone.byteClone         100  avgt   15   40.986 ±  0.674  ns/op
ArrayClone.byteClone        1000  avgt   15  227.512 ±  7.643  ns/op
ArrayClone.intArraycopy        0  avgt   15   10.320 ±  0.294  ns/op
ArrayClone.intArraycopy       10  avgt   15   36.557 ±  0.860  ns/op
ArrayClone.intArraycopy      100  avgt   15   89.837 ±  2.364  ns/op
ArrayClone.intArraycopy     1000  avgt   15  836.678 ± 27.920  ns/op
ArrayClone.intClone            0  avgt   15   10.043 ±  0.216  ns/op
ArrayClone.intClone           10  avgt   15   29.149 ±  0.723  ns/op
ArrayClone.intClone          100  avgt   15   88.046 ±  2.211  ns/op
ArrayClone.intClone         1000  avgt   15  840.163 ± 58.748  ns/op
Finished running test 'micro:java.lang.ArrayClone'
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331934](https://bugs.openjdk.org/browse/JDK-8331934): [s390x] Add support for primitive array C1 clone intrinsic (**Enhancement** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Sidraya Jayagond](https://openjdk.org/census#sjayagond) (@sid8606 - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19220/head:pull/19220` \
`$ git checkout pull/19220`

Update a local copy of the PR: \
`$ git checkout pull/19220` \
`$ git pull https://git.openjdk.org/jdk.git pull/19220/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19220`

View PR using the GUI difftool: \
`$ git pr show -t 19220`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19220.diff">https://git.openjdk.org/jdk/pull/19220.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19220#issuecomment-2109591738)

### CODE REVIEW

**Comment by offamitkumar** [comment]
@RealLucy @TheRealMDoerr Would you please review this one. :-) 

Testing seems clear on s390x. I have posted Benchmark result as well. 

Please let me know if any further testing is required.

**Comment by offamitkumar** [comment]
Result from the LPAR: 

```
without patch:
Benchmark                 (size)  Mode  Cnt    Score   Error  Units
ArrayClone.byteArraycopy       0  avgt   15    4.021 ± 0.032  ns/op
ArrayClone.byteArraycopy      10  avgt   15   15.931 ± 0.171  ns/op
ArrayClone.byteArraycopy     100  avgt   15   16.201 ± 0.076  ns/op
ArrayClone.byteArraycopy    1000  avgt   15   45.268 ± 0.213  ns/op
ArrayClone.byteClone           0  avgt   15   70.300 ± 0.244  ns/op
ArrayClone.byteClone          10  avgt   15   77.112 ± 0.558  ns/op
ArrayClone.byteClone         100  avgt   15   79.860 ± 0.606  ns/op
ArrayClone.byteClone        1000  avgt   15  112.834 ± 0.526  ns/op
ArrayClone.intArraycopy        0  avgt   15    4.007 ± 0.012  ns/op
ArrayClone.intArraycopy       10  avgt   15   15.378 ± 0.055  ns/op
ArrayClone.intArraycopy      100  avgt   15   25.387 ± 0.102  ns/op
ArrayClone.intArraycopy     1000  avgt   15  161.278 ± 0.719  ns/op
ArrayClone.intClone            0  avgt   15   70.341 ± 0.265  ns/op
ArrayClone.intClone           10  avgt   15   78.209 ± 0.514  ns/op
ArrayClone.intClone          100  avgt   15   89.845 ± 0.571  ns/op
ArrayClone.intClone         1000  avgt   15  257.037 ± 2.809  ns/op
Finished running test 'micro:java.lang.ArrayClone'
```


```
with patch: 
Benchmark                 (size)  Mode  Cnt    Score   Error  Units
ArrayClone.byteArraycopy       0  avgt   15    4.021 ± 0.027  ns/op
ArrayClone.byteArraycopy      10  avgt   15   16.106 ± 0.859  ns/op
ArrayClone.byteArraycopy     100  avgt   15   16.212 ± 0.045  ns/op
ArrayClone.byteArraycopy    1000  avgt   15   45.147 ± 0.137  ns/op
ArrayClone.byteClone           0  avgt   15    3.570 ± 0.010  ns/op
ArrayClone.byteClone          10  avgt   15    6.033 ± 0.018  ns/op
ArrayClone.byteClone         100  avgt   15    6.868 ± 0.020  ns/op
ArrayClone.byteClone        1000  avgt   15   33.437 ± 0.114  ns/op
ArrayClone.intArraycopy        0  avgt   15    4.008 ± 0.010  ns/op
ArrayClone.intArraycopy       10  avgt   15   15.373 ± 0.044  ns/op
ArrayClone.intArraycopy      100  avgt   15   29.543 ± 3.687  ns/op
ArrayClone.intArraycopy     1000  avgt   15  161.554 ± 0.414  ns/op
ArrayClone.intClone            0  avgt   15    3.571 ± 0.010  ns/op
ArrayClone.intClone           10  avgt   15    6.184 ± 0.016  ns/op
ArrayClone.intClone          100  avgt   15   13.304 ± 0.043  ns/op
ArrayClone.intClone         1000  avgt   15  133.755 ± 0.362  ns/op
Finished running test 'micro:java.lang.ArrayClone'
```

**Comment by offamitkumar** [comment]
> @RealLucy @TheRealMDoerr Would you please review this one. :-)

pinging you again, if you got bandwidth then please review it.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by offamitkumar** [comment]
@galderz if possible can you review this ?

Maybe this could ease you a bit while review: Testing for `{tier1} X {fastdebug, slowdebug, release}` and `{tier1 -XX:TieredStopAtLevel=1} X {fastdebug, slowdebug, release}` was clean. Benchmarking also shows that we are good on this. You can check the result [here](https://github.com/openjdk/jdk/pull/19220#issuecomment-2115237059) :-)

**Comment by galderz** [comment]
@offamitkumar I'm no s390 expert, so I can only do a light review on the code. The changes look good to me and the benchmark results show improvements. One thing I would suggest is maybe expanding the testing a bit, e.g. hotspot_compiler, hotspot_gc, hotspot_serviceability, hotspot_runtime, and tier1-3 see https://github.com/openjdk/jdk/pull/17667#issuecomment-2071741244 for further details.

**Review by sid8606 — APPROVED** [review]
LGTM

**Comment by offamitkumar** [comment]
Ran this command: `make test TEST="hotspot_compiler hotspot_gc hotspot_serviceability hotspot_runtime tier1 tier2 tier3" JTREG="JAVA_OPTIONS=-XX:TieredStopAtLevel=1 -Xcomp"` and didn't see any new failure appearing due to my changes.

**Pull request closed without merging**
