### PR TITLE
JDK-8276202: LogFileOutput.invalid_file_vm asserts when being executed from a read only working directory

### PR DESCRIPTION
**Pull request by jdksjolen**
This PR replaces some of the VM `assert` with gtest `ASSERT` where applicable and fixes a bug in a UL test.
The test used to create a temporary directory in cwd, failing if cwd is read-only. Now it creates the directory in /tmp/.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276202](https://bugs.openjdk.java.net/browse/JDK-8276202): LogFileOutput.invalid_file_vm asserts when being executed from a read only working directory

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8238/head:pull/8238` \
`$ git checkout pull/8238`

Update a local copy of the PR: \
`$ git checkout pull/8238` \
`$ git pull https://git.openjdk.java.net/jdk pull/8238/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8238`

View PR using the GUI difftool: \
`$ git pr show -t 8238`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8238.diff">https://git.openjdk.java.net/jdk/pull/8238.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Hi Johan,

These changes all look fine but you are fixing two distinct problems here and really they should be split into two different JBS issues. You can still use one PR if you want but with distinct commits for each issue.

Thanks,
David

**Review by dholmes-ora — APPROVED** [review]

**Comment by jdksjolen** [comment]
Thank you for the review, David!

**Comment by dcubed-ojdk** [comment]
Typically the reason for putting temporary files in the current directory
is so that they are created in a JTREG managed directory and cleaned
up as needed. By putting the files in /tmp you will be putting them in
a place where JTREG won't deal with them. Also, in the event of a test
failure, will the file in /tmp be left behind?

**Comment by tstuefe** [comment]
> Typically the reason for putting temporary files in the current directory is so that they are created in a JTREG managed directory and cleaned up as needed. By putting the files in /tmp you will be putting them in a place where JTREG won't deal with them. Also, in the event of a test failure, will the file in /tmp be left behind?

Oh, Dan is right :-( With jtreg, I can use -retain to keep the temp files, otherwise jtreg cleans them up.That only works oc with cwd.

I see now how weirdly difficult this problem is. In my opinion, the file handling parts of the UL tests would have been better left as jtreg tests, not as gtests.

For the record, I would be perfectly content with just the assert->ASSERT part of this fix.

**Review by tstuefe — APPROVED** [review]
I'm fine with this change. Thanks for fixing.

**Comment by jdksjolen** [comment]
@dholmes-ora , @tstuefe , would either of you be OK with sponsoring this PR :-)? Thank you!

**Comment by tstuefe** [comment]
Sure

/sponsor

**Pull request closed without merging**
