### PR TITLE
8291643: Consider omitting type annotations from type error diagnostics

### PR DESCRIPTION
**Pull request by cushon**
Hi,

Please consider this fix for [JDK-8291643](https://bugs.openjdk.org/browse/JDK-8291643), which causes javac to remove type-use annotations when formatting types in diagnostics.

For the example like the one in the bug, this change causes javac to emit the diagnostic like `incompatible types: List<String> cannot be converted to List<Number>` rather than `incompatible types: List<String> cannot be converted to List<@Nullable Number>`. Including the type annotations can be confusing, because they do not impact the type checking done by the compiler.

An alternative I considered was to remove type annotations from types for specific diagnostics, instead of doing it unconditionally in diagnostic formatting. I can revisit that if the current approach seems too broad.

The test update to `test/langtools/tools/javac/lambda/LambdaConv25.out` is because a `ForAll` is being formatted, and `stripMetadata()` uses a `StructuralTypeMapping` which rewrites away the `ForAll`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291643](https://bugs.openjdk.org/browse/JDK-8291643): Consider omitting type annotations from type error diagnostics (**Enhancement** - P4)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16578/head:pull/16578` \
`$ git checkout pull/16578`

Update a local copy of the PR: \
`$ git checkout pull/16578` \
`$ git pull https://git.openjdk.org/jdk.git pull/16578/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16578`

View PR using the GUI difftool: \
`$ git pr show -t 16578`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16578.diff">https://git.openjdk.org/jdk/pull/16578.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16578#issuecomment-1803013464)

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks good to me

**Comment by vicente-romero-oracle** [comment]
I guess your patch have uncovered a bug in stripMetadata

**Comment by cushon** [comment]
I have been looking at some other issues related to diagnostics and type annotations (e.g. [JDK-8043226](https://bugs.openjdk.org/browse/JDK-8043226)), and I am now wondering if it would make sense to preserve type annotations on times some of the time. I think stripping them is a good default (the majority of diagnostics about types are not related to type annotations), but do you have thoughts on letting diagnostics opt-in to preserving the annotations?

One possibility would be to have a trivial wrapper around the types used in diagnostic arguments, and then have the diagnostic formatter unwrap them and leave the annotations on:

https://github.com/openjdk/jdk/blob/a95062b39a431b4937ab6e9e73de4d2b8ea1ac49/src/jdk.compiler/share/classes/com/sun/tools/javac/util/AbstractDiagnosticFormatter.java#L202-L203

I am now also wondering if `AbstractDiagnosticFormatter` would be a better place to call `stripMetdata()` than where it currently is in `JCDIagnostic`.

What do you think? (And sorry for no thinking of these issues until after opening the PR.)

---

> > The test update to `test/langtools/tools/javac/lambda/LambdaConv25.out` is because a `ForAll` is being formatted, and `stripMetadata()` uses a `StructuralTypeMapping` which rewrites away the `ForAll`.
>
> I guess your patch have uncovered a bug in stripMetadata

I wasn't sure if would be considered a bug or not, but it was unexpected. I'm not sure preserving the `ForAll` makes the diagnostic clearer, but it's also possible to update `stripMetadata()` to preserve it.

The following would preserve the original diagnostics for `LambdaConv25`, do you have a preference?

```diff
diff --git a/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Type.java b/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Type.java
index e295096bb6d..b914d5e4a43 100644
--- a/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Type.java
+++ b/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Type.java
@@ -446,7 +446,12 @@ public Type visitTypeVar(TypeVar t, Void aVoid) {
             public Type visitWildcardType(WildcardType wt, Void aVoid) {
                 return super.visitWildcardType((WildcardType)wt.typeNoMetadata(), aVoid);
             }
-        };
+
+            @Override
+            public Type visitForAll(ForAll t, Void aVoid) {
+                return new ForAll(t.tvars, t.qtype.accept(this, aVoid));
+            }
+    };

     public Type preannotatedType() {
         return addMetadata(new Annotations());
```

**Comment by jddarcy** [comment]
> I guess your patch have uncovered a bug in stripMetadata

FYI, in case it is relevant here, I ran into some (still unresolved AFAIK) issues in stripMeta data during work on JDK-8042981: "Strip type annotations in Types' utility methods", including type annotations not being stripped for primitive types.

**Comment by cushon** [comment]
> > I guess your patch have uncovered a bug in stripMetadata
> 
> FYI, in case it is relevant here, I ran into some (still unresolved AFAIK) issues in stripMeta data during work on JDK-8042981: "Strip type annotations in Types' utility methods", including type annotations not being stripped for primitive types.

Thanks! I had another look at that and left a comment in the PR: https://github.com/openjdk/jdk/pull/8984#issuecomment-1806211798

**Comment by cushon** [comment]
I pushed a demo of some of the changes mentioned earlier, including an implementation of a `stripAnnotations` method that uses the approach I mentioned in https://github.com/openjdk/jdk/pull/8984#issuecomment-1806211798

> One possibility would be to have a trivial wrapper around the types used in diagnostic arguments, and then have the diagnostic formatter unwrap them and leave the annotations on

`AbstractDiagnosticFormatter` now removes type annotations from printed types by default, and there's a `JCDiagnostic.AnnotatedType` wrapper for diagnostics that want to opt-in to printing types with annotations. This isn't currently used in the PR, but https://github.com/openjdk/jdk/pull/16592 is an example of a diagnostic that wants to include type annotations.

**Comment by cushon** [comment]
Please keep this open for now

**Comment by cushon** [comment]
I updated this to use the `Type#stripMetadata` method added in https://bugs.openjdk.org/browse/JDK-8042981 to remove the type annotations, now that change has landed.

**Comment by cpovirk** [comment]
As an interested party, one thing that I'd highlight is that the tests and examples shown here are by nature simpler than what we see in real-world errors, such as this one:

```
com/google/common/collect/MutableClassToInstanceMap.java:169: error: incompatible types: Map<Class<? extends @org.checkerframework.checker.nullness.qual.NonNull B>,B> cannot be converted to Map<? extends Class<B>,? extends B>
  where @org.checkerframework.checker.nullness.qual.NonNull B is a type-variable:
    @org.checkerframework.checker.nullness.qual.NonNull B extends @org.checkerframework.checker.nullness.qual.Nullable Object declared in class MutableClassToInstanceMap
```

That could be reduced to merely:

```
com/google/common/collect/MutableClassToInstanceMap.java:169: error: incompatible types: Map<Class<? extends B>,B> cannot be converted to Map<? extends Class<B>,? extends B>
  where B is a type-variable:
    B extends Object declared in class MutableClassToInstanceMap
```

Note also that the first line of the current message, by including `@org.checkerframework.checker.nullness.qual.NonNull` in the one type but not the other, may suggest to some readers that the nullness annotations are part of the reason for the error, when in fact the error has nothing to do with nullness.

**Comment by cushon** [comment]
The example my colleage @cpovirk shared in https://github.com/openjdk/jdk/pull/16578#issuecomment-2088992273 was

> As an interested party, one thing that I'd highlight is that the tests and examples shown here are by nature simpler than what we see in real-world errors, such as this one:
>
> ```
> com/google/common/collect/MutableClassToInstanceMap.java:169: error: incompatible types: Map<Class<? extends @org.checkerframework.checker.nullness.qual.NonNull B>,B> cannot be converted to Map<? extends Class<B>,? extends B>
>   where @org.checkerframework.checker.nullness.qual.NonNull B is a type-variable:
>     @org.checkerframework.checker.nullness.qual.NonNull B extends @org.checkerframework.checker.nullness.qual.Nullable Object declared in class MutableClassToInstanceMap
> ```
> That could be reduced to merely:
>
> ```
> com/google/common/collect/MutableClassToInstanceMap.java:169: error: incompatible types: Map<Class<? extends B>,B> cannot be converted to Map<? extends Class<B>,? extends B>
>   where B is a type-variable:
>     B extends Object declared in class MutableClassToInstanceMap
> ```
> Note also that the first line of the current message, by including `@org.checkerframework.checker.nullness.qual.NonNull` in the one type but not the other, may suggest to some readers that the nullness annotations are part of the reason for the error, when in fact the error has nothing to do with nullness.

**Comment by cushon** [comment]
> `AbstractDiagnosticFormatter` now removes type annotations from printed types by default, and there's a `JCDiagnostic.AnnotatedType` wrapper for diagnostics that want to opt-in to printing types with annotations. This isn't currently used in the PR, but #16592 is an example of a diagnostic that wants to include type annotations.

I updated this after the merge of [JDK-8043226: Better diagnostics for non-applicable type annotations](https://bugs.openjdk.org/browse/JDK-8043226), which introduces some diagnostics that include types where the annotations should be preserved, to use the `JCDiagnostic.AnnotatedType` to preserve those annotations.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Pull request closed without merging**
