### PR TITLE
8327738: Remove unused internal method sun.n.w.p.h.HttpURLConnection.setDefaultAuthenticator

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this cleanup PR which removes the internal, unused method `sun.n.w.p.h.HttpURLConnection.setDefaultAuthenticator` with associated code.

This was discovered while investigating methods annotated with `@Deprecated`, but missing `@deprecated` javadoc tags.

The method sets a private static field which is read in various places. This field and its uses is also removed. After these changes, the associated interface `HttpAuthenticator` falls out of use and is removed as well.

Testing: No tests changes in this PR, this is purely a cleanup removal of unused code. A grep for `setDefaultAuthentication` across the JDK repo after this PR returns no matches.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327738](https://bugs.openjdk.org/browse/JDK-8327738): Remove unused internal method sun.n.w.p.h.HttpURLConnection.setDefaultAuthenticator (**Enhancement** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18178/head:pull/18178` \
`$ git checkout pull/18178`

Update a local copy of the PR: \
`$ git checkout pull/18178` \
`$ git pull https://git.openjdk.org/jdk.git pull/18178/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18178`

View PR using the GUI difftool: \
`$ git pr show -t 18178`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18178.diff">https://git.openjdk.org/jdk/pull/18178.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18178#issuecomment-1987851911)

### CODE REVIEW

**Review by djelinski — APPROVED** [review]
LGTM. Thanks!

**Comment by eirbjo** [comment]
As noted by @cl4es [1], the changes in this PR make the associated interface `HttpAuthenticator` fall out of use. This PR now deletes this interface.

**Review by djelinski — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
LGTM. I ran tier2 and saw no error.

**Comment by eirbjo** [comment]
Thanks to the Daniels for your reviews and testing help!

/integrate

**Pull request closed without merging**
