### PR TITLE
8276266: Clean up incorrect client-libs ProblemList.txt entries

### PR DESCRIPTION
**Pull request by prrace**
We have a few stale entries in the Problem list.
We need to remap some tests to still open bugs
7100044 -> 6849371
8203047 -> 8072110
8233703 -> 8238436
8273618 -> 8273617

We need to remove these FIXED bugs
java/awt/Choice/ChoiceKeyEventReaction/ChoiceKeyEventReaction.java 7185258 macosx-all

java/awt/GridLayout/LayoutExtraGaps/LayoutExtraGaps.java 8000171 windows-all
(actually closed as a dup of 8196100 which is fixed)

And this RESOLVED / not reproducible.
 java/awt/SplashScreen/MultiResolutionSplash/MultiResolutionSplashTest.java 8061235 macosx-all

I've verified that the removed ones do pass in the CI test system so we should be OK unless they are very intermittent or environment specific

---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8276266](https://bugs.openjdk.java.net/browse/JDK-8276266): Clean up incorrect client-libs ProblemList.txt entries

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6203/head:pull/6203` \
`$ git checkout pull/6203`

Update a local copy of the PR: \
`$ git checkout pull/6203` \
`$ git pull https://git.openjdk.java.net/jdk pull/6203/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6203`

View PR using the GUI difftool: \
`$ git pr show -t 6203`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6203.diff">https://git.openjdk.java.net/jdk/pull/6203.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
I am not sure why the macOS-specific JDK-8203047 was closed as a duplicate of x11 specific JDK-8072110?
The HandleExceptionOnEDT from the JDK-8203047 is not even mentioned in the JDK-8072110.

**Comment by mrserb** [comment]
Any updates on that @prrace @prsadhuk?

**Comment by prrace** [comment]
@prsadhuk - still looking for a response from you.

**Comment by prsadhuk** [comment]
> > I am not sure why the macOS-specific JDK-8203047 was closed as a duplicate of x11 specific JDK-8072110?
> > The HandleExceptionOnEDT from the JDK-8203047 is not even mentioned in the JDK-8072110.
> 
> I don't know. This was done by @prsadhuk - Prasanta can you explain that ?

I am not sure on this now...Seems like it might have been a mistake seeing it now..probably I was trying to close as dup with some other JBS but inadvertently mentioned the wrong one..

**Review by azuev-java — APPROVED** [review]
Looks good.

**Pull request closed without merging**
