### PR TITLE
8320786: Remove ThreadGroup.stop

### PR DESCRIPTION
**Pull request by AlanBateman**
ThreadGroup.stop was deprecated since JDK 1.2, deprecated for removal in Java 18, and re-specified/degraded to throw UnsupportedOperationException unconditionally in Java 20. Early in Java 23 seems a fine time to finally remove this method. Corpus analysis of 176 million classes in 485k artifacts found residual usages in 14 artifacts, so not many.

It would be nice if we could remove Thread.stop at the same time. Sadly there are still quite a few artifacts containing code (and in some cases tests) that reference this method. We will have to come back to this in some future release.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8320891](https://bugs.openjdk.org/browse/JDK-8320891) to be approved

### Issues
 * [JDK-8320786](https://bugs.openjdk.org/browse/JDK-8320786): Remove ThreadGroup.stop (**Enhancement** - P4)
 * [JDK-8320891](https://bugs.openjdk.org/browse/JDK-8320891): Remove ThreadGroup.stop (**CSR**)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**) ⚠️ Review applies to [d243df5c](https://git.openjdk.org/jdk/pull/16828/files/d243df5c19b96706827bf96237122dd33aa1ba66)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [d243df5c](https://git.openjdk.org/jdk/pull/16828/files/d243df5c19b96706827bf96237122dd33aa1ba66)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [d243df5c](https://git.openjdk.org/jdk/pull/16828/files/d243df5c19b96706827bf96237122dd33aa1ba66)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16828/head:pull/16828` \
`$ git checkout pull/16828`

Update a local copy of the PR: \
`$ git checkout pull/16828` \
`$ git pull https://git.openjdk.org/jdk.git pull/16828/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16828`

View PR using the GUI difftool: \
`$ git pr show -t 16828`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16828.diff">https://git.openjdk.org/jdk/pull/16828.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16828#issuecomment-1829897894)

### CODE REVIEW

**Comment by magicus** [comment]
> It would be nice if we could remove Thread.stop at the same time. Sadly there are still quite a few artifacts containing code (and in some cases tests) that reference this method. We will have to come back to this in some future release.

But we've started eating the elephant. I vote for free champagne to all JDK developers every time we can actually remove stuff that have been deprecated for removal!

**Review by RogerRiggs — APPROVED** [review]
Finally!

**Review by dholmes-ora — APPROVED** [review]
Looks good!

Thanks

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
