### PR TITLE
JDK-8300584: Accelerate AVX-512 CRC32C for small buffers

### PR DESCRIPTION
**Pull request by asgibbons**
Use AVX2 code for CRC32C for small buffers in the AVX-512 path.  Breakeven buffer size between the two algorithms is on the order of 384 bytes.

**Performance numbers for previous:**
```
Benchmark                    (count)   Mode  Cnt      Score     Error   Units
TestCRC32C.testCRC32CUpdate       64  thrpt    4  66974.957 ±   8.872  ops/ms
TestCRC32C.testCRC32CUpdate      128  thrpt    4  44224.810 ±  11.801  ops/ms
TestCRC32C.testCRC32CUpdate      256  thrpt    4  63997.611 ± 173.577  ops/ms
TestCRC32C.testCRC32CUpdate      512  thrpt    4  56068.683 ± 269.582  ops/ms
TestCRC32C.testCRC32CUpdate     2048  thrpt    4  27048.098 ±  87.350  ops/ms
TestCRC32C.testCRC32CUpdate    16384  thrpt    4   4066.736 ±  10.318  ops/ms
TestCRC32C.testCRC32CUpdate    65536  thrpt    4   1040.754 ±   6.419  ops/ms
```

**Performance numbers for this version:**
```
Benchmark                    (count)   Mode  Cnt       Score     Error   Units
TestCRC32C.testCRC32CUpdate       64  thrpt    3  161659.326 ±  74.974  ops/ms
TestCRC32C.testCRC32CUpdate      128  thrpt    3   88456.935 ±  11.940  ops/ms
TestCRC32C.testCRC32CUpdate      256  thrpt    3   73254.993 ±   5.004  ops/ms
TestCRC32C.testCRC32CUpdate      512  thrpt    3   56508.541 ± 298.229  ops/ms
TestCRC32C.testCRC32CUpdate     2048  thrpt    3   26701.995 ±  31.369  ops/ms
TestCRC32C.testCRC32CUpdate    16384  thrpt    3    4110.819 ±   4.618  ops/ms
TestCRC32C.testCRC32CUpdate    65536  thrpt    3    1045.821 ±   2.037  ops/ms

```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300584](https://bugs.openjdk.org/browse/JDK-8300584): Accelerate AVX-512 CRC32C for small buffers

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12079/head:pull/12079` \
`$ git checkout pull/12079`

Update a local copy of the PR: \
`$ git checkout pull/12079` \
`$ git pull https://git.openjdk.org/jdk pull/12079/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12079`

View PR using the GUI difftool: \
`$ git pr show -t 12079`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12079.diff">https://git.openjdk.org/jdk/pull/12079.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
We should avoid duplicating code. Since `crc32c_ipl_alg2_alt2` is used in both cases we can reshape code like next (pseudo code):

```
  if (supports_avx512()) {
    if (len > 384) {
       kernel_crc32_avx512();
       jmp Exit;
     }
  }
  crc32c_ipl_alg2_alt2();
Exit:
...
```

**Comment by asgibbons** [comment]
@vnkozlov - There is really no code duplication here.  This is generating code, so the `if(supports_avx512())` construct is directing which code is generated for the intrinsic.  That is, it either generates the AVX-512 kernel -OR- it generates the AVX2 routine.  I need *both* generated for this fix.  In the original code, there is no fall-through, so the `crc32c_ipl_alg2_alt2()` block can't be jumped to (because it's never generated).  Does this make sense?

**Comment by vnkozlov** [comment]
I mean this (`else` is removed so that `AVX2` code is always generated):
```
   __ enter(); // required for proper stackwalking of RuntimeStub frame
+
+  Label L_small, L_continue;
+
   if (VM_Version::supports_sse4_1() && VM_Version::supports_avx512_vpclmulqdq() &&
       VM_Version::supports_avx512bw() &&
       VM_Version::supports_avx512vl()) {
+    __ cmpl(len, 384);
+    __ jcc(Assembler::belowEqual, L_small);
+
     __ lea(j, ExternalAddress(StubRoutines::x86::crc32c_table_avx512_addr()));
     __ kernel_crc32_avx512(crc, buf, len, j, l, k);
-  } else {
+    __ jmp(L_continue);
+
+    __ bind(L_small);
+  }
 #ifdef _WIN64
-    __ push(y);
-    __ push(z);
+  __ push(y);
+  __ push(z);
 #endif
-    __ crc32c_ipl_alg2_alt2(crc, buf, len,
-                            a, j, k,
-                            l, y, z,
-                            c_farg0, c_farg1, c_farg2,
-                            is_pclmulqdq_supported);
+  __ crc32c_ipl_alg2_alt2(crc, buf, len,
+                          a, j, k,
+                          l, y, z,
+                          c_farg0, c_farg1, c_farg2,
+                          is_pclmulqdq_supported);
 #ifdef _WIN64
-    __ pop(z);
-    __ pop(y);
+  __ pop(z);
+  __ pop(y);
 #endif
-  }
+  __ bind(L_continue);
   __ movl(rax, crc);
   __ vzeroupper();
   __ leave(); // required for proper stackwalking of RuntimeStub frame
```

**Comment by asgibbons** [comment]
@vnkozlov Thanks for clarifying.  I've pushed changed code - let me know if this is what you were thinking.

**Review by vnkozlov — COMMENTED** [review]
Please, rerun performance tests. I will run our regular testing.

**Comment by asgibbons** [comment]
Here are the new results.  They seem to be in-line with what was reported in the initial description:

```
Benchmark                    (count)   Mode  Cnt       Score    Error   Units
TestCRC32C.testCRC32CUpdate       64  thrpt    4  161653.588 ± 90.568  ops/ms
TestCRC32C.testCRC32CUpdate      128  thrpt    4   88458.045 ±  1.664  ops/ms
TestCRC32C.testCRC32CUpdate      256  thrpt    4   73253.929 ±  2.757  ops/ms
TestCRC32C.testCRC32CUpdate      512  thrpt    4   56095.367 ± 33.203  ops/ms
TestCRC32C.testCRC32CUpdate     2048  thrpt    4   27714.763 ±  7.075  ops/ms
TestCRC32C.testCRC32CUpdate    16384  thrpt    4    4120.630 ± 13.723  ops/ms
TestCRC32C.testCRC32CUpdate    65536  thrpt    4    1046.727 ±  0.227  ops/ms
```

**Comment by vnkozlov** [comment]
Good. You need second review.

**Review by vnkozlov — APPROVED** [review]
My testing passed.

**Review by sviswa7 — APPROVED** [review]
Looks good to me as well.

**Pull request closed without merging**
