### PR TITLE
8308875: java/awt/Toolkit/GetScreenInsetsCustomGC/GetScreenInsetsCustomGC.java failed with 'Cannot invoke "sun.awt.X11GraphicsDevice.getInsets()" because "device" is null'

### PR DESCRIPTION
**Pull request by mkartashev**
8308875 is a regression after the recent [fix for 8305578](https://github.com/openjdk/jdk/commit/d7245f70) that effectively undid a part of [another, older, change](https://github.com/openjdk/jdk/commit/40f6d697d25293282e3d3ee695ef8cd9a5494799), the one made to fix [8233573](https://bugs.openjdk.org/browse/JDK-8233573).

This commits brings that part back and passes the test `java/awt/Toolkit/GetScreenInsetsCustomGC/GetScreenInsetsCustomGC.java` on Linux, so the test is also removed from the ProblemList file.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308875](https://bugs.openjdk.org/browse/JDK-8308875): java/awt/Toolkit/GetScreenInsetsCustomGC/GetScreenInsetsCustomGC.java failed with 'Cannot invoke "sun.awt.X11GraphicsDevice.getInsets()" because "device" is null'

### Reviewers
 * [Alexey Ushakov](https://openjdk.org/census#avu) (@avu - Committer)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14170/head:pull/14170` \
`$ git checkout pull/14170`

Update a local copy of the PR: \
`$ git checkout pull/14170` \
`$ git pull https://git.openjdk.org/jdk.git pull/14170/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14170`

View PR using the GUI difftool: \
`$ git pr show -t 14170`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14170.diff">https://git.openjdk.org/jdk/pull/14170.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14170#issuecomment-1564006309)

### CODE REVIEW

**Comment by mkartashev** [comment]
@mrserb Could you take a look at this one, please? I believe it reinstates the fix ([8233573](https://bugs.openjdk.org/browse/JDK-8233573)) that you originally made.

**Review by avu — APPROVED** [review]
Looks good for me

**Review by prrace — APPROVED** [review]
I note that the previous fix "undid" similar code on windows and mac as well.
Any explanation why it only causes a problem for Linux ?

**Comment by mkartashev** [comment]
> I note that the previous fix "undid" similar code on windows and mac as well.
> Any explanation why it only causes a problem for Linux ?

I will only be able to research that in about 2 weeks from now, sorry.

**Comment by mrserb** [comment]
Not a critical comment but it would be good in such cases to add a new bugid to the test which found the bug.

**Comment by mkartashev** [comment]
@prrace 
> I note that the previous fix "undid" similar code on windows and mac as well.
> Any explanation why it only causes a problem for Linux ?

Now that I've looked at the code, I don't understand the statement "the previous fix "undid" similar code on windows and mac as well". If by "the previous fix" you mean the fix for 8305578, then it did *not* introduce the same problem on MacOS/Windows as it did for Linux. Compare the relevant parts of `getScreenInsets()` before this one has been integrated:
```
Linux:
        final X11GraphicsDevice device = (X11GraphicsDevice) gc.getDevice();
        Insets insets = device.getInsets();

MacOS:
        if (!(gd instanceof CGraphicsDevice)) {
            return super.getScreenInsets(gc);
        }

Windows:
        if (!(gd instanceof Win32GraphicsDevice)) {
            return super.getScreenInsets(gc);
        }
```

Only Linux will fail in case of a "custom" `GraphicsConfiguration`.

**Pull request closed without merging**
