### PR TITLE
8304180: Constant Descriptors for MethodHandles::classData and classDataAt

### PR DESCRIPTION
**Pull request by liach**
Add Constant Descriptors for DirectMethodHandleDesc of MethodHandles::classData and classDataAt in ConstantDescs. This facilitates easier access of class data via condy in Classfile API-generated bytecode. Most other constant bootstrap methods provided in the JDK, notably from `ConstantBootstraps`, already have constant descriptors in ConstantDescs.

Context: https://mail.openjdk.org/pipermail/classfile-api-dev/2023-March/000235.html

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8304181](https://bugs.openjdk.org/browse/JDK-8304181) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8304180](https://bugs.openjdk.org/browse/JDK-8304180): Constant Descriptors for MethodHandles::classData and classDataAt
 * [JDK-8304181](https://bugs.openjdk.org/browse/JDK-8304181): Constant Descriptors for MethodHandles::classData and classDataAt (**CSR**)

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13033/head:pull/13033` \
`$ git checkout pull/13033`

Update a local copy of the PR: \
`$ git checkout pull/13033` \
`$ git pull https://git.openjdk.org/jdk.git pull/13033/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13033`

View PR using the GUI difftool: \
`$ git pr show -t 13033`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13033.diff">https://git.openjdk.org/jdk/pull/13033.diff</a>

</details>

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
Looks good. I've added myself as a reviewer on the CSR as well.

**Comment by JornVernee** [comment]
P.S. we don't seem to have a test for this class at the moment (except indirectly), but it might be nice to add a test that iterates over all the fields in this class, and tries to resolve them, to make sure that that works.

**Review by mlchung — APPROVED** [review]
This looks good.

**Pull request closed without merging**
