### PR TITLE
8290169: adlc: Improve child constraints for vector unary operations

### PR DESCRIPTION
**Pull request by shqking**
As demonstrated in [1], the child constrait generated for *predicated
vector unary operation* is the super set of that generated for the
*unpredicated* version. As a result, there exists a risk for predicated
vector unary operaions to match the unpredicated rules by accident.

In this patch, we resolve this issue by generating one extra check
"rChild == NULL" ONLY for vector unary operations. In this way, the
child constraints for predicated/unpredicated vector unary operations
are exclusive now.

Following the example in [1], the dfa state generated for AbsVI is shown
below.

```
void  State::_sub_Op_AbsVI(const Node *n){
  if( STATE__VALID_CHILD(_kids[0], VREG) && STATE__VALID_CHILD(_kids[1], PREGGOV) &&
      ( UseSVE > 0 ) )
  {
    unsigned int c = _kids[0]->_cost[VREG]+_kids[1]->_cost[PREGGOV] + SVE_COST;
      DFA_PRODUCTION(VREG, vabsI_masked_rule, c)
  }
  if( STATE__VALID_CHILD(_kids[0], VREG) && _kids[1] == NULL &&  <---- 1
      ( UseSVE > 0) )
  {
    unsigned int c = _kids[0]->_cost[VREG] + SVE_COST;
    if (STATE__NOT_YET_VALID(VREG) || _cost[VREG] > c) {
      DFA_PRODUCTION(VREG, vabsI_rule, c)
    }
  }
  ...
```

We can see that the constraint at line 1 cannot be matched for
predicated AbsVI node now.

The main updates are made in adlc/dfa part. Ideally, we should only
add the extra check for affected platforms, i.e. AVX-512 and SVE. But we
didn't do that because it would be better not to introduce any
architecture dependent implementation here.

Besides, workarounds in both ~aarch64_sve.ad~aarch64_vector.ad and x86.ad are removed. 1)
Many "is_predicated_vector()" checks can be removed in ~aarch64_sve.ad~aarch64_vector.ad
file. 2) Default instruction cost is used for involving rules in x86.ad
file.

~[1]. https://github.com/shqking/jdk/commit/50ec9b19~
[1]. https://github.com/shqking/jdk/commit/f7d9621e2

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290169](https://bugs.openjdk.org/browse/JDK-8290169): adlc: Improve child constraints for vector unary operations

### Reviewers
 * [Eric Liu](https://openjdk.org/census#eliu) (@theRealELiu - Author) ⚠️ Review applies to [4be4fa37](https://git.openjdk.org/jdk/pull/9534/files/4be4fa3796b0620a8300721b638259c25754a876)
 * [Xiaohong Gong](https://openjdk.org/census#xgong) (@XiaohongGong - Committer) ⚠️ Review applies to [f8bfb7be](https://git.openjdk.org/jdk/pull/9534/files/f8bfb7be24acb5b8d0452ff4accd9e29f65ea957)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to [f8bfb7be](https://git.openjdk.org/jdk/pull/9534/files/f8bfb7be24acb5b8d0452ff4accd9e29f65ea957)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9534/head:pull/9534` \
`$ git checkout pull/9534`

Update a local copy of the PR: \
`$ git checkout pull/9534` \
`$ git pull https://git.openjdk.org/jdk pull/9534/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9534`

View PR using the GUI difftool: \
`$ git pr show -t 9534`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9534.diff">https://git.openjdk.org/jdk/pull/9534.diff</a>

</details>

### CODE REVIEW

**Comment by theRealELiu** [comment]
LGTM.

**Review by theRealELiu — APPROVED** [review]

**Comment by shqking** [comment]
Can anyone help to take a look at this PR? Thanks in advance.

**Review by XiaohongGong — APPROVED** [review]
AArch64 part looks good to me. Thanks!

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Comment by shqking** [comment]
@TobiHartmann Thanks for your comment.

As some shared code, i.e. `share/adlc`, gets changed in this patch, I think it would be better for this patch to pass the Oracle CI tests. I wonder if you could help to launch the test? Thanks.

**Comment by TobiHartmann** [comment]
Sure, I did already run testing. All passed.

**Comment by shqking** [comment]
@TobiHartmann Thanks for your testing.

/integrate

**Pull request closed without merging**
