### PR TITLE
8328561: test java/awt/Robot/ManualInstructions/ManualInstructions.java isn't used

### PR DESCRIPTION
**Pull request by prrace**
I don't know why this file is checked in. It has no @test tag and doesn't do anything. I am deleting it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328561](https://bugs.openjdk.org/browse/JDK-8328561): test java/awt/Robot/ManualInstructions/ManualInstructions.java isn't used (**Bug** - P4)

### Reviewers
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer)
 * [Prasanta Sadhukhan](https://openjdk.org/census#psadhukhan) (@prsadhuk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18440/head:pull/18440` \
`$ git checkout pull/18440`

Update a local copy of the PR: \
`$ git checkout pull/18440` \
`$ git pull https://git.openjdk.org/jdk.git pull/18440/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18440`

View PR using the GUI difftool: \
`$ git pr show -t 18440`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18440.diff">https://git.openjdk.org/jdk/pull/18440.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18440#issuecomment-2013604578)

### CODE REVIEW

**Comment by prsadhuk** [comment]
Should we also remove test/jdk/java/awt/Mouse/MouseModifiersUnitTest/ModifierPermutation.java which also does not have @test tag and added for same product fix JDK-6315717?

**Review by DamonGuy — APPROVED** [review]

**Comment by prrace** [comment]
> Should we also remove test/jdk/java/awt/Mouse/MouseModifiersUnitTest/ModifierPermutation.java which also does not have @test tag and added for same product fix JDK-6315717?

Whilst the test in that file clearly needs some work, it (1) isn't related to Applets and (2) does appear to be actually related to the product fix. So I think deciding what to do with that is a separate question. We might want to fix it up and get it running in CI testing.

**Review by prsadhuk — APPROVED** [review]
ok

**Pull request closed without merging**
