### PR TITLE
7001973: java/awt/Graphics2D/CopyAreaOOB.java fails

### PR DESCRIPTION
**Pull request by masyano**
Could you please review the 7001973 fixes?

On Windows, CopyAreaOOB.java fails with a blank window. The cause of this problem is that paint() works one time only. Painting area is not guaranteed when showing a window.

I think this behavior should be removed for purpose of this test (`@summary: Verifies that copyArea() works properly`). Also, this program uses a Robot, but implements waiting logic by itself. This logic should be replaced to Robot API.

This fix works fine in Windows, so this test can be removed from ProblemList.txt. I don't have a Mac environment, so can someone please confirm that this fix will work on Mac?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-7001973](https://bugs.openjdk.java.net/browse/JDK-7001973): java/awt/Graphics2D/CopyAreaOOB.java fails

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5491/head:pull/5491` \
`$ git checkout pull/5491`

Update a local copy of the PR: \
`$ git checkout pull/5491` \
`$ git pull https://git.openjdk.java.net/jdk pull/5491/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5491`

View PR using the GUI difftool: \
`$ git pr show -t 5491`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5491.diff">https://git.openjdk.java.net/jdk/pull/5491.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
This test is quite strict and its purpose exactly check that the first paint() will properly render the windows content.
So if the window will paint some garbage and then repaint correct content this test wil catch that.

**Comment by masyano** [comment]
I read JDK-6430601 and JDK-8198613, described at `@bug`. JDK-6430601 is a background rendering problem in JInternalFrame with OpenGL pipeline. JDK-8198613 is a timeout problem with OpenGL pipeline, as a result, OpenGL pipeline test is removed.
So now, the purpose of this test is to confirm the usual drawing result on default settings, then I think there is no need to strict paint() at once.

**Comment by masyano** [comment]
The test checks only one time for painting "result".

I think the painting sequence depends on rendering pipeline. I collected a log the Java2D and the ComponentPeer, then multiple PaintEvent is recorded with default D3D pipeline (see below).  So, paint() should not be restrict one time.

```
$ /Downloads/jdk-17/bin/java -Dsun.java2d.trace=log,timestamp -Djava.util.logging.config.file=logging.properties CopyAreaOOB
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 0, height = 0
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 0, height = 0
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
1631860257699: D3DFillRect
1631860257732: D3DFillRect
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
1631860257741: D3DFillRect
1631860257743: D3DFillRect
1631860257750: D3DFillRect
1631860257751: D3DFillRect
1631860257755: D3DFillRect
1631860257757: D3DCopyArea
Sep 17, 2021 3:30:57 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
1631860257759: D3DFillRect
1631860257762: D3DFillRect
1631860257763: D3DFillRect
1631860257763: D3DFillRect
1631860257764: D3DFillRect
1631860257764: D3DCopyArea

$ /Downloads/jdk-17/bin/java -Dsun.java2d.trace=log,timestamp -Djava.util.logging.config.file=logging.properties -Duser.language=en -Dsun.java2d.noddraw CopyAreaOOB
Sep 17, 2021 3:32:10 PM sun.awt.windows.WComponentPeer coalescePaintEvent
FINEST: coalescePaintEvent: PAINT: add: x = 0, y = 0, width = 400, height = 400
1631860330225: GDIFillRect
1631860330249: GDIFillRect
1631860330254: GDIFillRect
1631860330254: GDIFillRect
1631860330255: GDICopyArea
```

**Comment by mrserb** [comment]
Let's check the sequence in the test:
1. Frame created
2. Undecorated property is set
3. peer is created, and native configuration completed
4. frame is moved to the center of the screen
5. frame became visible

It is fine to have a few paint events posted for the code above, my question was why the first CopyArea is ignored? If the awt/java2d is not ready yet to draw/repaint the window that events should not be posted, if it is ready then CopyArea should work, no?

**Comment by masyano** [comment]
> my question was why the first CopyArea is ignored? 

This is a RepaintArea's behavior. clearRect() is called before paint() because shouldClearRectBeforePaint is true for Canvas. Then, if 2nd paint() is called and paint() does nothing, blank window will be drawn.
https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/awt/RepaintArea.java#L235

**Comment by mrserb** [comment]
> This is a RepaintArea's behavior. clearRect() is called before paint() because shouldClearRectBeforePaint is true for Canvas. Then, if 2nd paint() is called and paint() does nothing, blank window will be drawn.

So the "sun.awt.noerasebackground" property may fix the problem? Or simple freeze the EDT after g2d.copyArea?

**Comment by masyano** [comment]
> So the "sun.awt.noerasebackground" property may fix the problem? 

Yes. With `-Dsun.awt.noerasebackground=true`, original CopyAreaOOB.java is Passed. But it is just a workaround.

paint() is called twice with default settings on Windows, so my suggested fix is more realistic and reasonable than original code with `-Dsun.awt.noerasebackground=true`.

**Comment by mrserb** [comment]
> Yes. With `-Dsun.awt.noerasebackground=true`, original CopyAreaOOB.java is Passed. But it is just a workaround.

Yes, it is just a workaround that most probably will not work on other platforms. But EDT freeze for some time after copyarea will work.

> paint() is called twice with default settings on Windows, so my suggested fix is more realistic and reasonable than original code with `-Dsun.awt.noerasebackground=true`.

Do you know why we post it twice? It does not seem right, since we repaint all content in the apps like Netbeans/Idea and it is quite a heavyweight operation.

**Comment by masyano** [comment]
> Do you know why we post it twice? It does not seem right, since we repaint all content in the apps like Netbeans/Idea and it is quite a heavyweight operation.

Because SurfaceData is judged to be lost when 1st getGraphics() is called on 1st PaintEvent processing.

https://github.com/openjdk/jdk/blob/master/src/java.desktop/windows/classes/sun/java2d/d3d/D3DScreenUpdateManager.java#L478

I traced PaintEvent, then I got following stacktrace.

```
breakpoint hit: "Thread=AWT-EventQueue-0", java.awt.event.PaintEvent.<init>()、line=106 bci=0

  [1] java.awt.event.PaintEvent.<init> (PaintEvent.java:106)
  [2] sun.awt.PaintEventDispatcher.createPaintEvent (PaintEventDispatcher.java:80)
  [3] sun.awt.windows.WComponentPeer.postPaintIfNecessary (WComponentPeer.java:892)
  [4] sun.awt.windows.WComponentPeer.handlePaint (WComponentPeer.java:886)
  [5] sun.java2d.d3d.D3DScreenUpdateManager.repaintPeerTarget (D3DScreenUpdateManager.java:283)
  [6] sun.java2d.d3d.D3DScreenUpdateManager.validate (D3DScreenUpdateManager.java:492)
  [7] sun.java2d.d3d.D3DScreenUpdateManager.createGraphics (D3DScreenUpdateManager.java:260)
  [8] sun.awt.windows.WComponentPeer.getGraphics (WComponentPeer.java:646)
  [9] java.awt.Component.getGraphics (Component.java:3,128)
  [10] sun.awt.RepaintArea.paint (RepaintArea.java:227)
  [11] sun.awt.windows.WComponentPeer.handleEvent (WComponentPeer.java:371)
  [12] java.awt.Component.dispatchEventImpl (Component.java:5,056)
  [13] java.awt.Container.dispatchEventImpl (Container.java:2,325)
  [14] java.awt.Window.dispatchEventImpl (Window.java:2,775)
  [15] java.awt.Component.dispatchEvent (Component.java:4,827)
  [16] java.awt.EventQueue.dispatchEventImpl (EventQueue.java:772)
  [17] java.awt.EventQueue$4.run (EventQueue.java:721)
  [18] java.awt.EventQueue$4.run (EventQueue.java:715)
  [19] java.security.AccessController.executePrivileged (AccessController.java:753)
  [20] java.security.AccessController.doPrivileged (AccessController.java:391)
  [21] java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege (ProtectionDomain.java:85)
  [22] java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege (ProtectionDomain.java:95)
  [23] java.awt.EventQueue$5.run (EventQueue.java:745)
  [24] java.awt.EventQueue$5.run (EventQueue.java:743)
  [25] java.security.AccessController.executePrivileged (AccessController.java:753)
  [26] java.security.AccessController.doPrivileged (AccessController.java:391)
  [27] java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege (ProtectionDomain.java:85)
  [28] java.awt.EventQueue.dispatchEvent (EventQueue.java:742)
  [29] java.awt.EventDispatchThread.pumpOneEventForFilters (EventDispatchThread.java:203)
  [30] java.awt.EventDispatchThread.pumpEventsForFilter (EventDispatchThread.java:124)
  [31] java.awt.EventDispatchThread.pumpEventsForHierarchy (EventDispatchThread.java:113)
  [32] java.awt.EventDispatchThread.pumpEvents (EventDispatchThread.java:109)
  [33] java.awt.EventDispatchThread.pumpEvents (EventDispatchThread.java:101)
  [34] java.awt.EventDispatchThread.run (EventDispatchThread.java:90)
AWT-EventQueue-0[1] > >
```

At 1st PaintEvent is processing, RepaintArea calls getGraphics(), then D3DScreenUpdateManager finally calls new PaintEvent().
So, 2nd PaintEvent is posted and invoked later on EDT.

**Comment by mrserb** [comment]
> At 1st PaintEvent is processing, RepaintArea calls getGraphics(), then D3DScreenUpdateManager finally calls new PaintEvent().
> So, 2nd PaintEvent is posted and invoked later on EDT.

It does not look right, isn't it? Every time we show a frame we render its content twice, and the first rendering is always discarded. Probably we should validate the surface before we posting the first paint event and before we show the window.

**Comment by masyano** [comment]
I think we should fix D3DScreenUpdateManager. I would like to create a new issue for it.

But I think this test should be fixed, because the purpose of this test is to confirm the usual drawing result on default settings, then there is no need to restrict paint() one time.

If the test that verifies paint() isn't called twice is needed, we should create a new test in the new bug id.

**Comment by mrserb** [comment]
You will not be able to write the test which will check that only one paint event is posted, it is not guaranteed.
You can only check that each rendering caused by the paint event will work fine. This test case check that the first event works fine, it can be improved to check all paint events.

So for the test update, you can add a big delay after the rendering, and wait for what will occur on the screen, any ideas why it may not work? You also can create a separate bug to investigate how we can validate the surface before showing the window so we did not post more events than necessary.

**Comment by masyano** [comment]
I understood what you wanted to test.

I think all paint events can be examined by only checking at the end of paint(). So I moved checkRegion into paint() part. It also works fine in case of multi paint events happen when restoring Frame from the iconified status to normal status.

**Comment by masyano** [comment]
@mrserb Thank you for helping me with the test. How many more days does the test run?

**Comment by masyano** [comment]
@mrserb Could you please reply to the above comment?

**Comment by masyano** [comment]
@mrserb How is the test running? Could you give me a reply?

**Comment by masyano** [comment]
@mrserb Could you tell me how long it will take to run the test?

**Comment by masyano** [comment]
@mrserb Could you please reply to the above comment?

**Comment by masyano** [comment]
@mrserb I have tested on MacOS. The drawing result has no problem, and passed with no Exception. Please review this PR again.

**Comment by masyano** [comment]
@mrserb Could you please review the above comments?

**Review by mrserb — APPROVED** [review]

**Comment by masyano** [comment]
@mrserb Could you please commit this fix as a sponsor?

**Pull request closed without merging**
