### PR TITLE
8321815: Shenandoah: gc state should be synchronized to java threads only once per safepoint

### PR DESCRIPTION
**Pull request by earthling-amzn**
Presently, every change to the gc change is distributed to all java threads. The gc state is only changed on safepoints. For applications with a very large number of java threads this may increase time on the safepoint. It would be better to synchronize the gc state only once per safepoint.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321815](https://bugs.openjdk.org/browse/JDK-8321815): Shenandoah: gc state should be synchronized to java threads only once per safepoint (**Enhancement** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - no project role) ⚠️ Review applies to [91a5cee4](https://git.openjdk.org/jdk/pull/17112/files/91a5cee4beaaf4fa23a3fe8cec6b2fd5fa0155b7)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**) ⚠️ Review applies to [93d0f4e3](https://git.openjdk.org/jdk/pull/17112/files/93d0f4e36b21bfb1ad0deebc6eefb3eed04e31e4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17112/head:pull/17112` \
`$ git checkout pull/17112`

Update a local copy of the PR: \
`$ git checkout pull/17112` \
`$ git pull https://git.openjdk.org/jdk.git pull/17112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17112`

View PR using the GUI difftool: \
`$ git pr show -t 17112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17112.diff">https://git.openjdk.org/jdk/pull/17112.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17112#issuecomment-1856450710)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Am wondering if we measure any improvement in time-at-safepoints for workloads with large number of threads?

**Review by ysramakrishna — COMMENTED** [review]
This seems reasonable. How many unnecessary state change distributions to threads do we save from this, so as to quantify the savings?

It would seem as if, as a verification mechanism that no state changes were dropped from distribution, it might be a good idea to assert in both prologue and epilogue of ShenandoahHeap stop-world ops that the `_gc_state_changed` flag is false, indicating that the last state change was "consumed and distributed" by any stop-world op?

**Comment by earthling-amzn** [comment]
This instrumentation isn't included in this PR, but it shows how often GC state changes in a typical cycle:
```
[40.118s][31676][info ][gc,start    ] GC(1) Pause Init Mark (unload classes)
[40.118s][31676][info ][gc          ] GC(1) GC state = 22
[40.118s][31676][info ][gc          ] GC(1) Pause Init Mark (unload classes) 0.119ms
[41.646s][31676][info ][gc,start    ] GC(1) Pause Final Mark (unload classes)
[41.646s][31676][info ][gc          ] GC(1) GC state = 0
[41.646s][31676][info ][gc          ] GC(1) GC state = 10
[41.648s][31676][info ][gc          ] GC(1) GC state = 14
[41.648s][31676][info ][gc          ] GC(1) GC state = 15
[41.648s][31676][info ][gc          ] GC(1) Pause Final Mark (unload classes) 2.324ms
[42.774s][31676][info ][gc,start    ] GC(1) Pause Init Update Refs
[42.774s][31676][info ][gc          ] GC(1) GC state = 11
[42.774s][31676][info ][gc          ] GC(1) GC state = 1
[42.774s][31676][info ][gc          ] GC(1) GC state = 9
[42.774s][31676][info ][gc          ] GC(1) Pause Init Update Refs 0.108ms
[43.040s][31676][info ][gc,start    ] GC(1) Pause Final Update Refs
[43.040s][31676][info ][gc          ] GC(1) GC state = 1
[43.040s][31676][info ][gc          ] GC(1) GC state = 0
[43.040s][31676][info ][gc          ] GC(1) Pause Final Update Refs 0.162ms
```
And for some degenerated cycles, many of these changes may happen on the same safepoint:
```
[60.839s][31676][info ][gc,start       ] GC(17) Pause Degenerated GC (Mark)
[61.417s][31676][info ][gc             ] GC(17) GC state = 0
[62.291s][31676][info ][gc             ] GC(17) GC state = 4
[62.291s][31676][info ][gc             ] GC(17) GC state = 5
[62.309s][31676][info ][gc             ] GC(17) GC state = 1
[62.309s][31676][info ][gc             ] GC(17) GC state = 1
[62.309s][31676][info ][gc             ] GC(17) GC state = 9
[63.372s][31676][info ][gc             ] GC(17) GC state = 1
[63.372s][31676][info ][gc             ] GC(17) GC state = 0
[63.373s][31676][info ][gc             ] GC(17) Pause Degenerated GC (Mark) 31103M->24719M(32768M) 2534.356ms
```
I can add the assertions you described in the prologue and epilogue methods. For what it's worth, changes to the gc state already assert the changes occur on a safepoint.

**Review by ysramakrishna — APPROVED** [review]
Looks good; thanks for the data and for the extra verification checks.
🚢

**Review by shipilev — COMMENTED** [review]
(Late for the party here!)

The idea looks good, but there are two minor problems with it:

 1. Thread-local gc-state is supposed to be used from the barriers. This is why we can coalesce the thread-local gc-state within a safepoint, as long as we have the proper setup after the safepoint. However, I think it is a happy accident that we don't poll thread-local gc-state from current native barrier code, and thread-local gc-state is only used by java threads. If we ever did access from non-java (gc) threads, this would subtly break GC within e.g. final-mark vmop.
 2. It is fairly weird that now `ShenandoahHeap::set_gc_state_all_threads` does the actual modification, while `ShenandoahHeap::set_gc_state_mask` does not! The names of the methods do not highlight the difference in semantics.

I guess we can hit two birds with one stone if we rename the methods to mention java threads and record/set split, and assert that non-java threads do not touch the `ShenandoahThreadLocalData::_gc_state`. Something like `SH::set_gc_state` (changes the global, sets the propagation flag) and `SH::propagate_gc_state_java_threads` (propagates global to thread-local java threads)?

**Comment by earthling-amzn** [comment]
I'll open a new PR to rename these methods and add an assert that non-java threads never touch the thread local copy of gc state.

**Pull request closed without merging**
