### PR TITLE
8317538: Potential bottleneck in Provider::getService: specjvm2008::crypto.rsa have scalability issue for high vCPU numbers

### PR DESCRIPTION
**Pull request by IvaVladimir**
This patch remove access to the shared variable to fix scalability issue in the multithread environment.  According to testing by the specjvm2008::crypto.rsa the one thread performance reduced for less than 1% while the score for the multithread run increased in ~2x. For the 2 socket system with Xeon 8480+ numbers looks as: 
- 1 thread: 643.15 for original version vs 642.54 for patched one;
- 224 threads: 22446.19 for original vs 46147.41 for patched.

The RSABench microbenchmark reports no score changes for the 1 thread (average for all testcases) and 2.4% improvement for the 224 threads.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8317538](https://bugs.openjdk.org/browse/JDK-8317538): Potential bottleneck in Provider::getService: specjvm2008::crypto.rsa have scalability issue for high vCPU numbers (**Bug** - P3)

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21622/head:pull/21622` \
`$ git checkout pull/21622`

Update a local copy of the PR: \
`$ git checkout pull/21622` \
`$ git pull https://git.openjdk.org/jdk.git pull/21622/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21622`

View PR using the GUI difftool: \
`$ git pr show -t 21622`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21622.diff">https://git.openjdk.org/jdk/pull/21622.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21622#issuecomment-2427421887)

### CODE REVIEW

**Comment by cl4es** [comment]
Is `Provider::getService` a bottleneck in real apps or is this mostly something which manifests in specjvm2008 and such benchmarks (which likely does what could be considered setup logic in the hot path)? 

I agree with the changes though: caching transient lookup keys seem a dubious optimization at best on modern HW/JVMs, and doing so in a way that might cause cache-line ping-pong on large systems looks pretty bad.

**Comment by IvaVladimir** [comment]
I was failed to find any real application that was affected. For now only specjvm2008 reports different scores. 
Seems, this optimization was designed for the one thread performance long time ago but now even for one thread it gives less than run-to-run variation.

**Review by cl4es — CHANGES_REQUESTED** [review]
The bug description needs to be updated to reflect that this is a potential bottleneck in `Provider::getService` and not isolated to RSA. 

Other than that I think this is a reasonable patch. Removing a bottleneck from specjvm2008.rsa will - if not else - ensure such benchmarks focus better on the stuff that matters.

**Comment by seanjmullan** [comment]
Please hold off on integrating until someone from the Security group reviews this.

**Comment by ascarpino** [comment]
Did you see the same performance improvement with specjvm2008::crypto.aes?  I believe that should be running through this code as well unless there is something particular with RSA or any other asymmetric key.

**Comment by ascarpino** [comment]
Is `volatile` a known performance decelerator?
I don't see any source control history for that part of the code, so I can only speculate at `previousKey` was to improve benchmarking.  Did you try just removing `volatile` and leaving the rest of the code?

**Review by cl4es — APPROVED** [review]

**Comment by valeriepeng** [comment]
Note the bot warning on the branch name being master. Will you change this following the bot's instruction? Also the minor issue with the convention of starting the synopsis with Upper case, i.e. "potential" -> "Potential".

**Comment by IvaVladimir** [comment]
The specjvm::crypto.aes workload not affected by this issue.
It implemented as mix of DES and AES encryptions but AES much better optimized vs DES. The top 3 methods for this workload for the 112T run are:
85.6% com::sun::crypto::provider::DESCrypt::cipherBlock
6.5%   com::sun::crypto::provider::DESCrypt::perm
4.4%   com::sun::crypto::provider::CipherCore::update
i.e. this workload have no problem with the getService method.

**Comment by IvaVladimir** [comment]
Without the 'volatile' the performance improved for ~6% (22293 -> 23638) for the 224 threads run. 
Without the 'static volatile' performance improved ~1.9x (22293 -> 42045). It may be 'transient' instance field.
Scores for the 1 thread runs similar for all 3 modification and fit to run-to-run variation.

**Comment by cl4es** [comment]
> Note the bot warning on the branch name being master. Will you change this following the bot's instruction? Also the minor issue with the convention of starting the synopsis with Upper case, i.e. "potential" -> "Potential".

I had missed this bot comment. @IvaVladimir you probably ought to take the bots advice and close this PR, move the changes over to a new branch and create a new PR from that branch -- otherwise your repository will get into a real wonky state after integration.

**Pull request closed without merging**
