### PR TITLE
8292592: JFR test TestNative is not reliable due to low rate of sampling.

### PR DESCRIPTION
**Pull request by robehn**
Split TestNative into two different test, so native sampling can have a high frequency.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292592](https://bugs.openjdk.org/browse/JDK-8292592): JFR test TestNative is not reliable due to low rate of sampling.

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**) ⚠️ Review applies to [4b19fef9](https://git.openjdk.org/jdk/pull/9915/files/4b19fef9ad4190a454fa3d1a25a64e8ab3ff1601)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [4b19fef9](https://git.openjdk.org/jdk/pull/9915/files/4b19fef9ad4190a454fa3d1a25a64e8ab3ff1601)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9915/head:pull/9915` \
`$ git checkout pull/9915`

Update a local copy of the PR: \
`$ git checkout pull/9915` \
`$ git pull https://git.openjdk.org/jdk pull/9915/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9915`

View PR using the GUI difftool: \
`$ git pr show -t 9915`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9915.diff">https://git.openjdk.org/jdk/pull/9915.diff</a>

</details>

### CODE REVIEW

**Comment by egahlin** [comment]
The new test uses jdk.ExecutionSample, not jdk.NativeMethodSample. This might be by design, but I though I should mention it.

**Review by egahlin — APPROVED** [review]

**Comment by robehn** [comment]
Thank you @egahlin !

**Review by shipilev — APPROVED** [review]
Nit: not sure if all imports are needed, like `AtomicInteger`?

**Comment by robehn** [comment]
@shipilev thank you! I'll fix that before push!

**Pull request closed without merging**
