### PR TITLE
8318569: Add getter methods for Locale and Patterns in ListFormat

### PR DESCRIPTION
**Pull request by naotoj**
Proposing adding getter methods for `locale` and `patterns` fields in the `ListFormat` instances. Those fields are used for `equals()`, but without the public getter methods, users cannot tell the reasoning of the equality of two instances. A corresponding CSR has also been drafted.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8318571](https://bugs.openjdk.org/browse/JDK-8318571) to be approved

### Issues
 * [JDK-8318569](https://bugs.openjdk.org/browse/JDK-8318569): Add getter methods for Locale and Patterns in ListFormat (**Enhancement** - P4)
 * [JDK-8318571](https://bugs.openjdk.org/browse/JDK-8318571): Add getter methods for Locale and Patterns in ListFormat (**CSR**)

### Reviewers
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16293/head:pull/16293` \
`$ git checkout pull/16293`

Update a local copy of the PR: \
`$ git checkout pull/16293` \
`$ git pull https://git.openjdk.org/jdk.git pull/16293/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16293`

View PR using the GUI difftool: \
`$ git pr show -t 16293`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16293.diff">https://git.openjdk.org/jdk/pull/16293.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16293#issuecomment-1773173732)

### CODE REVIEW

**Review by JoeWang-Java — APPROVED** [review]
Looks good to me.

**Review by RogerRiggs — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Corresponding CSR also Reviewed.

**Review by Hamlin-Li — APPROVED** [review]
LGTM

**Pull request closed without merging**
