### PR TITLE
8319450: Add missing @since tags for new ofLiteral() methods

### PR DESCRIPTION
**Pull request by marchof**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8319450](https://bugs.openjdk.org/browse/JDK-8319450)

### Issue
 * [JDK-8319450](https://bugs.openjdk.org/browse/JDK-8319450): New methods java.net.InetXAddress.ofLiteral() miss @since tag (**Bug** - P4) ⚠️ Title mismatch between PR and JBS.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16510/head:pull/16510` \
`$ git checkout pull/16510`

Update a local copy of the PR: \
`$ git checkout pull/16510` \
`$ git pull https://git.openjdk.org/jdk.git pull/16510/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16510`

View PR using the GUI difftool: \
`$ git pr show -t 16510`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16510.diff">https://git.openjdk.org/jdk/pull/16510.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16510#issuecomment-1793814087)

### CODE REVIEW

**Comment by marchof** [comment]
No idea why I closed this. Looks like I can't re-open. Will give another try. Sry.

**Comment by djelinski** [comment]
For future reference, bot command `/open` would probably help.

**Comment by erikj79** [comment]
It looks like you pushed something weird. Github is unable to show the diff, and shows over 5000 changed files. The bot can't find a merge-base between the source and target.

**Comment by marchof** [comment]
@djelinski  @erikj79 Thanks for your help! As always the problem is in front of the screen :)

**Pull request closed without merging**
