### PR TITLE
8325881: Require minimum gcc version 10

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that updates the minimum supported version of gcc
to be used for building OpenJDK from 6.0 to 10.0.

This permits enabling C++17 (JDK-8314488), though gcc 9.0 might suffice for
that. A minimum of gcc 10 also obtains the primitives needed to support a
work-alick for std::is_constant_evaluated (added in C++20). There are a bunch
of improvements that would be enabled by that. Having it would also allow the
elimination of a bit of a mess in the HotSpot assert macros that was needed to
work around the lack of that feature (JDK-8303805). Either current or proposed
minimum versions of other supported compilers also provide the needed
primitives.

Testing: mach5 tier1 (uses gcc13.2 on gcc-based platforms)
Locally (linux-x64) built and ran tier1 with gcc10.3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325881](https://bugs.openjdk.org/browse/JDK-8325881): Require minimum gcc version 10 (**Enhancement** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17899/head:pull/17899` \
`$ git checkout pull/17899`

Update a local copy of the PR: \
`$ git checkout pull/17899` \
`$ git pull https://git.openjdk.org/jdk.git pull/17899/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17899`

View PR using the GUI difftool: \
`$ git pr show -t 17899`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17899.diff">https://git.openjdk.org/jdk/pull/17899.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17899#issuecomment-1949900078)

### CODE REVIEW

**Comment by kimbarrett** [comment]
There was some discussion of gcc versions over in the PR proposing to enable C++17:
https://github.com/openjdk/jdk/pull/14988#issuecomment-1895511862
https://github.com/openjdk/jdk/pull/14988#issuecomment-1895729165
Has that been sufficiently answered?  Good to go here?
@shipilev @theRealAph @TheRealMDoerr

**Comment by TheRealMDoerr** [comment]
I have no objections. We already build with gcc 11. Some machines may need to get a newer gcc, but I think that's acceptable.

**Review by shipilev — COMMENTED** [review]
I have no objections either. Let me check with our team if this breaks anything hard for our builds.

**Review by shipilev — APPROVED** [review]
No problem from our side, thanks!

**Comment by kimbarrett** [comment]
Thanks for reviews/responses. I'll go ahead with integration. We won't be
reliant on the newer version immediately, so we can still reconsider if it causes
someone problems and they bring it up soon-ish.

**Pull request closed without merging**
