### PR TITLE
8278275: Initial nroff manpage generation for JDK 19

### PR DESCRIPTION
**Pull request by dholmes-ora**
Trivial update to change the version to 19-ea, and update the single reference to the "current release".

Content changes for 19 will follow.

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278275](https://bugs.openjdk.java.net/browse/JDK-8278275): Initial nroff manpage generation for JDK 19

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Jonathan Gibbons](https://openjdk.java.net/census#jjg) (@jonathan-gibbons - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6811/head:pull/6811` \
`$ git checkout pull/6811`

Update a local copy of the PR: \
`$ git checkout pull/6811` \
`$ git pull https://git.openjdk.java.net/jdk pull/6811/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6811`

View PR using the GUI difftool: \
`$ git pr show -t 6811`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6811.diff">https://git.openjdk.java.net/jdk/pull/6811.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
This "mechanical" update is just being sent to the build mailing list for review.

Paging @jonathan-gibbons too :)

**Review by erikj79 — APPROVED** [review]
Looks good to me.

**Review by jonathan-gibbons — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the reviews Erik, Jon and Iris!

/integrate

**Pull request closed without merging**
