### PR TITLE
8290824: Use InputStream.readAllBytes() instead of explicit loops

### PR DESCRIPTION
**Pull request by stsypanov**
We can use `InputStream.readAllBytes()` in `ModuleHashes` and `X509CertPath`.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290824](https://bugs.openjdk.org/browse/JDK-8290824): Use InputStream.readAllBytes() instead of explicit loops

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9596/head:pull/9596` \
`$ git checkout pull/9596`

Update a local copy of the PR: \
`$ git checkout pull/9596` \
`$ git pull https://git.openjdk.org/jdk pull/9596/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9596`

View PR using the GUI difftool: \
`$ git pr show -t 9596`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9596.diff">https://git.openjdk.org/jdk/pull/9596.diff</a>

</details>

### CODE REVIEW

**Comment by mbreinhold** [comment]
Why do you say “instead of surrogate code”? I don’t see any Unicode surrogate processing here, but maybe you mean something else. Would “instead of explicit loops” be a better summary?

**Comment by stsypanov** [comment]
By "surrogate code" I mean hand-written snippets reading all the bytes from an InputStream.

> It means the whole content from the input stream is read into a single array and this could lead to a sudden peak memory usage if the size is big.

`InputStream.readAllBytes()` reads data from the InputStream in chunks of 8192 bytes, then combines them into one resulting array which is returned. In theory this could lead even to OOME in case the size the resulting array exceeds `Integer.MAX_VALUE`, I doubt however this would ever happen.

I've looked into the history of `ModulerHashes`: prior to `byte[]` it used `ByteBuffer` of the same size (32 kB) as intermediate storage. I think digesting all the data at once might be faster than doing it chunk by chunk, on the other hand I understand memory concern.

**Comment by mbreinhold** [comment]
If by “surrogates” you mean “substitutes”, then this wording is confusing. At the time these explicit loops were written they weren’t surrogates for anything, since `InputStream::readAllBytes` didn’t yet exist. Please revise the summary to say “... instead of explicit loops”.

I share @wangweij’s concern about the change to the `ModuleHashes` class. The original code does not read the entirety of each stream into a single byte array because it doesn’t need to in order to update the digest. Furthermore, it re-uses the same byte array for all of the (potentially many) input streams. Your change would allocate a new byte array for each input stream, which seems likely to be slower. Please measure this (using, e.g., [JMH]) before making such a change.

[JMH]: https://github.com/openjdk/jmh

**Comment by stsypanov** [comment]
> Please revise the summary to say “... instead of explicit loops”.

Done.

> Please measure this (using, e.g., [JMH](https://github.com/openjdk/jmh)) before making such a change.

I'm aware of JMH, I was asking mostly about public API I should call in a benchmark to execute the changed code.

**Comment by stsypanov** [comment]
Could one advise how to execute smth like `jmod hash --module-path ~/openjdk-18.0.2/Contents/Home/jmods --hash-modules .*`? This command doesn't work for me.

**Comment by turbanoff** [comment]
Ow. I've created similar PR for `X509CertPath` recently #9263

**Comment by stsypanov** [comment]
@turbanoff I'll then remove the mentioned piece from this PR

**Comment by stsypanov** [comment]
I've measured this with benchmark
```java
@State(Scope.Thread)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@Fork(jvmArgsAppend = {"-Xms1g", "-Xmx1g"})
public class HashBenchmark {

  private final Path path = Path.of("/Users/stsypanov/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home/jmods");
  private final ModuleFinder finder = ModulePath.of(Runtime.version(), true, path);

  @Benchmark
  public byte[] hash() throws Exception {
    return hash(finder, "java.base");
  }

  private byte[] hash(ModuleFinder finder, String name) throws Exception {
    ModuleReference mref = finder.find(name).orElseThrow(RuntimeException::new);
    try (ModuleReader reader = mref.open()) {
      return ModuleHashes.computeHash(reader, "SHA-256");
    }
  }
}
```
and indeed the change makes things slower:
```
baseline
Benchmark                                            Mode  Cnt         Score         Error   Units
HashBenchmark.hash                                   avgt   50       174,632 ±       5,581   ms/op
HashBenchmark.hash:·gc.alloc.rate                    avgt   50       165,848 ±       4,574  MB/sec
HashBenchmark.hash:·gc.alloc.rate.norm               avgt   50  31773902,052 ±   24870,662    B/op
HashBenchmark.hash:·gc.churn.G1_Eden_Space           avgt   50       166,357 ±       9,399  MB/sec
HashBenchmark.hash:·gc.churn.G1_Eden_Space.norm      avgt   50  31891221,589 ± 1725370,956    B/op
HashBenchmark.hash:·gc.churn.G1_Old_Gen              avgt   50         5,553 ±       0,327  MB/sec
HashBenchmark.hash:·gc.churn.G1_Old_Gen.norm         avgt   50   1064354,875 ±   60435,285    B/op
HashBenchmark.hash:·gc.churn.G1_Survivor_Space       avgt   50         0,034 ±       0,032  MB/sec
HashBenchmark.hash:·gc.churn.G1_Survivor_Space.norm  avgt   50      6754,365 ±    6398,008    B/op
HashBenchmark.hash:·gc.count                         avgt   50       144,000                counts
HashBenchmark.hash:·gc.time                          avgt   50       249,000                    ms

patched

Benchmark                                            Mode  Cnt          Score         Error   Units
HashBenchmark.hash                                   avgt   50        192,068 ±       8,236   ms/op
HashBenchmark.hash:·gc.alloc.rate                    avgt   50        568,790 ±      22,912  MB/sec
HashBenchmark.hash:·gc.alloc.rate.norm               avgt   50  119441637,758 ±   28476,724    B/op
HashBenchmark.hash:·gc.churn.G1_Eden_Space           avgt   50        568,892 ±      26,936  MB/sec
HashBenchmark.hash:·gc.churn.G1_Eden_Space.norm      avgt   50  119444622,067 ± 2746230,425    B/op
HashBenchmark.hash:·gc.churn.G1_Old_Gen              avgt   50          4,964 ±       0,238  MB/sec
HashBenchmark.hash:·gc.churn.G1_Old_Gen.norm         avgt   50    1042019,563 ±   23557,187    B/op
HashBenchmark.hash:·gc.churn.G1_Survivor_Space       avgt   50          0,043 ±       0,033  MB/sec
HashBenchmark.hash:·gc.churn.G1_Survivor_Space.norm  avgt   50       9130,656 ±    7040,858    B/op
HashBenchmark.hash:·gc.count                         avgt   50        492,000                counts
HashBenchmark.hash:·gc.time                          avgt   50        738,000                    ms
```
I'll close this PR then.

**Pull request closed without merging**
