### PR TITLE
8286271: [java.desktop] Replace ternary operators with java.lang.Math min/max

### PR DESCRIPTION
**Pull request by SWinxy**
Delete `sun.java2d.marlin.FloatMath` class in favor of methods in `java.lang.Math`. The methods in `Math.java` are intrinsics and can gain from significant speedups. Hand-written min/max operations are also replaced with calls. 5 uses of `ceil` and 2 uses of `floor` were replaced.
This should not cause any rendering differences from the different algorithms being used, as they theoretically will end up at the same outcomes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286271](https://bugs.openjdk.java.net/browse/JDK-8286271): [java.desktop] Replace ternary operators with java.lang.Math min/max

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7097/head:pull/7097` \
`$ git checkout pull/7097`

Update a local copy of the PR: \
`$ git checkout pull/7097` \
`$ git pull https://git.openjdk.java.net/jdk pull/7097/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7097`

View PR using the GUI difftool: \
`$ git pr show -t 7097`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7097.diff">https://git.openjdk.java.net/jdk/pull/7097.diff</a>

</details>

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Comment to keep PR active

**Comment by SWinxy** [comment]
Keeping open.

**Comment by TheShermanTanker** [comment]
@SWinxy Issue ID is 8286271

**Comment by bourgesl** [comment]
Hi,
Concerning the Marlin renderer, I made FloatMath for performance reasons, highly tuned impl. 
I doubt calling Math.ceil/floor or Math.min/max is really faster.
 I should test performance with your changes or write a jmh benchmark...

**Comment by SWinxy** [comment]
I see... It's something similar to JOML's [FASTMATH](https://joml-ci.github.io/JOML/apidocs/org/joml/Options.html#FASTMATH) option.
Even if calling Math.min/max wouldn't be faster (I would hope so, being tagged with @IntrinsicCandidate), it would still be unnecessary code duplication. The Java code is identical, save for the `final` modifier in the parameter list.
`ceil_f`, `floor_f`, and `floor_int(float)` are not used.
`ceil_int(float)` is only used once, in `MarlinProperties.align`. `align` is used only three times, with the callers being constants in `MarlinConst`. This is to say the performance benefit would be pointless assuming the three callers to `align` aren't called in other peoples' code (I doubt, but who knows).
For `ceil_int(double)` and `floor_int(double)`, that is where performance would matter. What I can end up doing is adding back `FloatMath` with those two methods, and rename it to `FastMath` or something.

**Comment by bourgesl** [comment]
Thanks for your detailed analysis, it matches my variant, so I prefer keeping FloatMath with fewer methods.
I agree min/max can use jdk math as I manually inlined important calls inside very hot loops in Renderer.

Here is my latest version of FloatMath (jdk branch):
https://github.com/bourgesl/marlin-renderer/blob/jdk/src/main/java/sun/java2d/marlin/FloatMath.java

Marlin renderer 0.9.4.5 has few more patches that I have to propose to openjdk/jdk as I did for openjfx:
https://github.com/openjdk/jfx/pull/674

Thanks

**Comment by SWinxy** [comment]
Sick. Should I implement these changes in this PR or do you want to do them?

**Comment by bourgesl** [comment]
Please keep FloatMath alive to have floor/ceil (double) and I will anyway merge in my repo.
Go on

**Comment by prrace** [comment]
I would like to  caution that in a previous bug fix where this form was replaced it was determined not to be 100% compatible

https://mail.openjdk.java.net/pipermail/client-libs-dev/2021-December/001694.html

In short, this is pointless churn and I reject this PR.

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
I agree with Phil. Whatever small benefit there might be in doing this isn't justified by the cost of reviewing and testing it, especially given the very real risk of introducing regressions.

This PR should be withdrawn and the JBS bug closed as "Won't fix"

**Comment by SWinxy** [comment]
Say the `Double.compare` change is dropped (makes sense; the method is not the same as the replaced code), the changes to RowFilter are undone (i.e. `abs()`), and the performance-critical code @bourgesl wants is kept. This leaves the ternary operators and FloatMath as changed. Does the risk of regression make readability improvements unworthy? Take this line for instance:
```java
int y = (itemBounds.y + itemBounds.height > screenBounds.y) ? itemBounds.y + itemBounds.height : screenBounds.y; // from
int y = Math.max(itemBounds.y + itemBounds.height, screenBounds.y); // to
```
I get that you're cautious, but this is more understandable to maintain. It takes much effort to really understand what the ternary operators are doing, and I believe that it is worth changing.

**Review by prrace — CHANGES_REQUESTED** [review]
As per my request, please withdraw this PR and close the bug as will not fix.

**Pull request closed without merging**
