### PR TITLE
8263821: Remove unused MethodTypeForm canonicalization codes

### PR DESCRIPTION
**Pull request by cl4es**
MethodTypeForm.INTS, LONGS and RAW_RETURN are effectively unused. This removes these canonicalization codes and cleans up related code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263821](https://bugs.openjdk.java.net/browse/JDK-8263821): Remove unused MethodTypeForm canonicalization codes

### Reviewers
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3075/head:pull/3075`
`$ git checkout pull/3075`

To update a local copy of the PR:
`$ git checkout pull/3075`
`$ git pull https://git.openjdk.java.net/jdk pull/3075/head`

### CODE REVIEW

**Review by mlchung — APPROVED** [review]
I don't object this dead code elimination.  I don't know the design/thought when these unused canonicalization codes were defined.

**Comment by cl4es** [comment]
This code appear to have been initially introduced with the JDK 7 implementation of JSR 292, which implemented different ways of adapting to and from generic types than the current code: https://bugs.openjdk.java.net/browse/JDK-6839872

Many uses (possibly all) were removed in https://bugs.openjdk.java.net/browse/JDK-6983728 (8-b01) where adapters were reworked. This was backported to 7, so the code I'm removing here is probably dead in all active releases.

**Comment by mlchung** [comment]
Thanks for the history.

**Pull request closed without merging**
