### PR TITLE
8138732: Rename @HotSpotIntrinsicCandidate to @IntrinsicCandidate and move it to the jdk.internal.vm.annotation package

### PR DESCRIPTION
**Pull request by marschall**
Hello, newbie here

I picked JDK-8138732 to work on because it has a "starter" label and I believe I understand what to do.

- I tried to update the copyright year to 2020 in every file.
- I decided to change `@since` from 9 to 16 since it is a new annotation name in a new package.
- I tried to keep code changes to a minimum, eg not change to imports if fully qualified class names are used instead of imports. In some cases I did minor reordering of imports to keep them sorted alphabetically.
- All tier1 tests pass.
- One jpackage/jlink tier2 test fails but I don't believe it is related.
- Some tier3 Swing tests fail but I don't think they are related.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8138732](https://bugs.openjdk.java.net/browse/JDK-8138732): Rename @HotSpotIntrinsicCandidate to @IntrinsicCandidate and move it to the jdk.internal.vm.annotation package

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 47328f4bed07c116dc4dafe6642c062e70a4e66c
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 1c9dd9da6dea509cc50e46dc0c1b630d429be7b0
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**) ⚠️ Review applies to 1c9dd9da6dea509cc50e46dc0c1b630d429be7b0
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 25d947266f32f30a1a9c9cd5458a13821246b66d
 * [Erik Gahlin](https://openjdk.java.net/census#egahlin) (@egahlin - **Reviewer**) ⚠️ Review applies to 25d947266f32f30a1a9c9cd5458a13821246b66d

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/45/head:pull/45`
`$ git checkout pull/45`

### CODE REVIEW

**Comment by AlanBateman** [comment]
This one probably needs discussion on hotspot-dev to get agreement on the rename/move. It might need coordination with Graal. If the change does go ahead then please check if java.base's module-info.java still needs to export jdk.internal to jdk.jfr, I suspect that qualified export can be removed.

**Review by dholmes-ora — APPROVED** [review]
The changes all look good to me.

**Review by AlanBateman — APPROVED** [review]

**Review by PaulSandoz — APPROVED** [review]

**Comment by vnkozlov** [comment]
You should consider upstreaming Graal changes (jdk.internal.vm.compiler) into https://github.com/oracle/graal
Otherwise next time we do "Update Graal" in JDK they will be overwritten.

**Comment by vnkozlov** [comment]
Changes look good. I ran hs-tier1 and hs-tier3 test jobs which run Graal tests and they passed.

**Review by vnkozlov — APPROVED** [review]

**Comment by egahlin** [comment]
Have you run the JFR tests in test/jdk/jdk/jfr?

**Comment by dholmes-ora** [comment]
@marschall Please do not force-push anything as it breaks the commit history in the PR and renders previous reviews/comments obsolete. There is no way for the reviewers to see what changed between the commit they reviewed and the commit now in the PR.

To update to latest changes you should have just merged your branch with your (up-to-date) local master, committed that merge in your local branch and then pushed that commit to your Personal Fork. The skara tooling will flatten the series of commits in a PR into one single well-formed commit that is pushed to the master branch of the repo.

**Review by vnkozlov — APPROVED** [review]
Update seems fine. Thanks for JFR testing and fixing.

**Review by egahlin — APPROVED** [review]

**Comment by vnkozlov** [comment]
@marschall  I will sponsor it after you integrate the latest update.

**Comment by marschall** [comment]
@vnkozlov done, I hope I now made it correctly with a merge commit for the latest merge conflict

**Comment by vnkozlov** [comment]
hs-tier1, hs-tier3-graal testing passed

**Pull request closed without merging**
