### PR TITLE
8298809: Clean up vm/compiler/InterfaceCalls JMH

### PR DESCRIPTION
**Pull request by ericcaspole**
I removed some confusing less effective cases and modified and renamed some to cover what seem like the most useful cases with 1+ types and 1+ interfaces implemented in those types. Here is an example run:

Benchmark                        Mode  Cnt  Score   Error  Units
InterfaceCalls.test1stInt2Types  avgt   12  2.196 ± 0.022  ns/op
InterfaceCalls.test1stInt3Types  avgt   12  8.259 ± 0.045  ns/op
InterfaceCalls.test1stInt5Types  avgt   12  8.279 ± 0.024  ns/op
InterfaceCalls.test2ndInt2Types  avgt   12  2.467 ± 0.023  ns/op
InterfaceCalls.test2ndInt3Types  avgt   12  9.287 ± 0.032  ns/op
InterfaceCalls.test2ndInt5Types  avgt   12  9.343 ± 0.027  ns/op
InterfaceCalls.testMonomorphic   avgt   12  1.440 ± 0.031  ns/op

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298809](https://bugs.openjdk.org/browse/JDK-8298809): Clean up vm/compiler/InterfaceCalls JMH

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11696/head:pull/11696` \
`$ git checkout pull/11696`

Update a local copy of the PR: \
`$ git checkout pull/11696` \
`$ git pull https://git.openjdk.org/jdk pull/11696/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11696`

View PR using the GUI difftool: \
`$ git pr show -t 11696`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11696.diff">https://git.openjdk.org/jdk/pull/11696.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
To be consistent I think we should rename interfaces and their methods:

```
    interface FirstInterface {
        public int getIntFirst();
     }

     interface SecondInterface {
         public int getIntSecond();
     }
```

**Comment by ericcaspole** [comment]
Thanks Vladimir, good suggestion!

**Review by vnkozlov — APPROVED** [review]
Good.

**Pull request closed without merging**
