### PR TITLE
JDK-8320941: Discuss receiver type handling 

### PR DESCRIPTION
**Pull request by jddarcy**
Please review this note to discuss when ExecutableElement returns a non-sentinel object for the receiver type.

(The PR was accidentally created from the wrong branch; the change to java.lang.Double can be ignored.)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8321061](https://bugs.openjdk.org/browse/JDK-8321061) to be approved

### Issues
 * [JDK-8320941](https://bugs.openjdk.org/browse/JDK-8320941): Discuss receiver type handling (**Enhancement** - P4)
 * [JDK-8321061](https://bugs.openjdk.org/browse/JDK-8321061): Discuss receiver type handling (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16874/head:pull/16874` \
`$ git checkout pull/16874`

Update a local copy of the PR: \
`$ git checkout pull/16874` \
`$ git pull https://git.openjdk.org/jdk.git pull/16874/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16874`

View PR using the GUI difftool: \
`$ git pr show -t 16874`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16874.diff">https://git.openjdk.org/jdk/pull/16874.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16874#issuecomment-1831146824)

### CODE REVIEW

**Comment by jddarcy** [comment]
In retrospect, it may have been better to define

    TypeMirror ExecutableType.getReceiverType()
    
to instead be

    VariableElement ExecutableType.getReceiverParameter()
    
However, it is far too late to make that change.

@cushon , does this spec update properly capture the intended semantics of your recent change for JDK-8319196?

**Comment by jddarcy** [comment]
Once the wording of the spec update is worked out, I'll file the CSR in due course.

**Comment by cushon** [comment]
> @cushon , does this spec update properly capture the intended semantics of your recent change for JDK-8319196?

Yes, thanks, I think this captures the intended semantics from JDK-8319196.

**Comment by jddarcy** [comment]
> > @cushon , does this spec update properly capture the intended semantics of your recent change for JDK-8319196?
> 
> Yes, thanks, I think this captures the intended semantics from JDK-8319196.

Thanks @cushon ; CSR now ready for review: https://bugs.openjdk.org/browse/JDK-8321061.

**Review by vicente-romero-oracle — APPROVED** [review]
looks good to me

**Pull request closed without merging**
