### PR TITLE
8340717: Remove unused function declarations from java.c/java.h of the launcher

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this cleanup to the launcher code to remove declarations of unused functions?

The `ValidateModules` function appears to be a left-over from https://bugs.openjdk.org/browse/JDK-8194937.

The `SetApplicationClassPath` and `PrintMachineDependentOptions` appear to have been unused for a long time (ever since the first commit in the current JDK repo).

The data model related macros, being removed in this PR, are unused and no longer relevant.

No new tests have been added and existing tier1, tier2 and tier3 tests continue to pass with this change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340717](https://bugs.openjdk.org/browse/JDK-8340717): Remove unused function declarations from java.c/java.h of the launcher (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21149/head:pull/21149` \
`$ git checkout pull/21149`

Update a local copy of the PR: \
`$ git checkout pull/21149` \
`$ git pull https://git.openjdk.org/jdk.git pull/21149/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21149`

View PR using the GUI difftool: \
`$ git pr show -t 21149`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21149.diff">https://git.openjdk.org/jdk/pull/21149.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21149#issuecomment-2370136200)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
LGTM!

Thanks

**Review by shipilev — APPROVED** [review]

**Review by TheShermanTanker — APPROVED** [review]
Looks trivial and good

**Comment by jaikiran** [comment]
Thank you all for the reviews.

**Pull request closed without merging**
