### PR TITLE
8292159: TYPE_USE annotations on generic type arguments of record components discarded

### PR DESCRIPTION
**Pull request by sadayapalam**
Handle carryover of type annotations to record components in a place which will be
    reached regardless of whether there are any annotations in a SE5 annotation location.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8292159](https://bugs.openjdk.org/browse/JDK-8292159): TYPE_USE annotations on generic type arguments of record components discarded
 * [JDK-8295705](https://bugs.openjdk.org/browse/JDK-8295705): TYPE_USE annotations on generic type arguments of record components discarded (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [1f9085e6](https://git.openjdk.org/jdk/pull/10741/files/1f9085e6b73d7b2b60984fd7a936d1a337b7aa7f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10741/head:pull/10741` \
`$ git checkout pull/10741`

Update a local copy of the PR: \
`$ git checkout pull/10741` \
`$ git pull https://git.openjdk.org/jdk pull/10741/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10741`

View PR using the GUI difftool: \
`$ git pr show -t 10741`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10741.diff">https://git.openjdk.org/jdk/pull/10741.diff</a>

</details>

### CODE REVIEW

**Comment by jddarcy** [comment]
> /csr needed

I agree it is reasonable to have a CSR to note the behavioral change; thanks,

**Comment by sadayapalam** [comment]
For the record(sic!) , javac's implementation seems to use terminology that differs from JLS (but still may be producing fully equivalent implementation)

See that JLS 8.10.1 says:

The record components of a record class, if any, are specified in the header of a
record declaration. Each record component consists of a type (optionally preceded
by one or more annotations) and an identifier that specifies the name of the
record component. A record component corresponds to two members of the record
class: a private field declared implicitly, and a public accessor method declared
explicitly or implicitly (§8.10.3).

Javac implementation treats the declaration in the record header as a component field
and generates record component from that.

In doing so, it is aligning with terminology used by JDK, which treats the components of
the record attribute as Record components. 

The following is from Class.java

```
/*
     * Returns an array containing the components of the Record attribute,
     * or null if the attribute is not present.
     *
     * Note that this method returns non-null array on a class with
     * the Record attribute even if this class is not a record.
     */
    private native RecordComponent[] getRecordComponents0();
```

This may be just splitting hairs - but at least initially it is a bit confusing that we go from components fields to record components in javac implementation rather than vice versa.

As called out before, the net effect may be that a totally equivalent implementation results.

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Pull request closed without merging**
