### PR TITLE
JDK-8264838: IGV: enhance graph export functionality 

### PR DESCRIPTION
**Pull request by neliasso**
Hi,

This patch adds SVG and searchable PDF export functionality to IGV. 

It's originally contributed by rcastanedalo@openjdk.java.net.
I have updated the patch with new library versions, rebased and tested it.

Please review,
Nils Eliasson

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264838](https://bugs.openjdk.java.net/browse/JDK-8264838): IGV: enhance graph export functionality

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Contributors
 * Roberto Castañeda Lozano `<rcastanedalo@openjdk.org>`
 * Nils Eliasson `<neliasso@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6564/head:pull/6564` \
`$ git checkout pull/6564`

Update a local copy of the PR: \
`$ git checkout pull/6564` \
`$ git pull https://git.openjdk.java.net/jdk pull/6564/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6564`

View PR using the GUI difftool: \
`$ git pr show -t 6564`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6564.diff">https://git.openjdk.java.net/jdk/pull/6564.diff</a>

</details>

### CODE REVIEW

**Comment by neliasso** [comment]
I updated this PR with a change based on feedback by @chhagedorn from the previous (withdrawn) PR.

**Review by chhagedorn — APPROVED** [review]
Looks good to me! I've applied the changes and could successfully export a graph to PDF and SVG.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by neliasso** [comment]
Thanks for the review @TobiHartmann and @chhagedorn !

**Pull request closed without merging**
