### PR TITLE
8260286: Manual Test "ws/open/test/jdk/sun/security/tools/jarsigner/compatibility/Compatibility.java" fails

### PR DESCRIPTION
**Pull request by fguallini**
Fixing manual Test "ws/open/test/jdk/sun/security/tools/jarsigner/compatibility/Compatibility.java". It was not handling "weak algorithm" warning during jarsigner output verification

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260286](https://bugs.openjdk.java.net/browse/JDK-8260286): Manual Test "ws/open/test/jdk/sun/security/tools/jarsigner/compatibility/Compatibility.java" fails

### Reviewers
 * [Rajan Halade](https://openjdk.java.net/census#rhalade) (@rhalade - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2224/head:pull/2224`
`$ git checkout pull/2224`

### CODE REVIEW

**Review by rhalade — APPROVED** [review]

**Comment by haimaychao** [comment]
Looks good.

**Comment by haimaychao** [comment]
One comment: Add bug id to the changed test. Thanks.

**Review by haimaychao — COMMENTED** [review]
Change copyright year to 2021

**Comment by fguallini** [comment]
Thanks for the review

**Review by rhalade — APPROVED** [review]

**Pull request closed without merging**
