### PR TITLE
JDK-8278014: [vectorapi] Remove test run script

### PR DESCRIPTION
**Pull request by PaulSandoz**
Remove Vector API scripts for building and running tests. `jtreg` should be used instead.

Also updated the test generation script to remove options that assume mercurial as the code repository.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278014](https://bugs.openjdk.java.net/browse/JDK-8278014): [vectorapi] Remove test run script

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to 65fa1fbe02dfbfb193508febb3d6587aaac8f811
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6621/head:pull/6621` \
`$ git checkout pull/6621`

Update a local copy of the PR: \
`$ git checkout pull/6621` \
`$ git pull https://git.openjdk.java.net/jdk pull/6621/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6621`

View PR using the GUI difftool: \
`$ git pr show -t 6621`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6621.diff">https://git.openjdk.java.net/jdk/pull/6621.diff</a>

</details>

### CODE REVIEW

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Comment by DamonFool** [comment]
Shall we also update the copyright year?

**Comment by PaulSandoz** [comment]
> Shall we also update the copyright year?

Doh! of course, updated.

**Review by DamonFool — APPROVED** [review]
Thanks for your update.
LGTM

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
