### PR TITLE
8343777: Add since checker tests to Internationalisation modules

### PR DESCRIPTION
**Pull request by nizarbenalla**
Can I please get a review for this PR that add tests to verify the value of `@since` tags to the Internationalisation area modules. The test is described in this [email](https://mail.openjdk.org/pipermail/jdk-dev/2024-October/009474.html). This issue is similar to JDK-8341399, JDK-8331051 and JDK-8343442.

The benefit from this is helping API authors and reviewer validate the accuracy of `@since` in their source code (and subsequently, in the generated documentation). And lessen the burden on Reviewers.

The test has been added for `java.base` and a few other modules and has helped catch some bugs before they make it to the JDK.

TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343777](https://bugs.openjdk.org/browse/JDK-8343777): Add since checker tests to Internationalisation modules (**Sub-task** - P4)

### Reviewers
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21985/head:pull/21985` \
`$ git checkout pull/21985`

Update a local copy of the PR: \
`$ git checkout pull/21985` \
`$ git pull https://git.openjdk.org/jdk.git pull/21985/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21985`

View PR using the GUI difftool: \
`$ git pr show -t 21985`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21985.diff">https://git.openjdk.org/jdk/pull/21985.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21985#issuecomment-2465055602)
</details>

### CODE REVIEW

**Comment by naotoj** [comment]
Hi Nizar,
Both modules are intended to provide implementations for charsets/localedata, and no public APIs are/will be provided. Do we need since check for these modules?

**Comment by naotoj** [comment]
OK, fine from the coverage perspective. I would appreciate some explanations in the test description though, as someone might think if public APIs may be added in these modules.

**Review by justin-curtis-lu — APPROVED** [review]
LGTM w/ the summary clarification

**Review by naotoj — APPROVED** [review]
LGTM. Thank you for making the comments.

**Comment by nizarbenalla** [comment]
Thank you for the reviews, I hope those comments are helpful to people.

/integrate

**Pull request closed without merging**
