### PR TITLE
8296349: [aarch64] Avoid slicing Address::extend

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change around `Address::extend`.  The 4 derived classes are
replaced by static functions of the same name as the former class.  These
functions return an `extend` object initialized with the same values as were
used by the corresponding derived class constructor.

Testing: mach5 tier1-3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296349](https://bugs.openjdk.org/browse/JDK-8296349): [aarch64] Avoid slicing Address::extend

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to [a351cd6a](https://git.openjdk.org/jdk/pull/10976/files/a351cd6a2a82a431a6a2856b36deb93041259306)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [a351cd6a](https://git.openjdk.org/jdk/pull/10976/files/a351cd6a2a82a431a6a2856b36deb93041259306)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10976/head:pull/10976` \
`$ git checkout pull/10976`

Update a local copy of the PR: \
`$ git checkout pull/10976` \
`$ git pull https://git.openjdk.org/jdk pull/10976/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10976`

View PR using the GUI difftool: \
`$ git pr show -t 10976`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10976.diff">https://git.openjdk.org/jdk/pull/10976.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]
Yep. That's a nice simplification, thanks.

**Comment by kimbarrett** [comment]
Anyone else?

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by kimbarrett** [comment]
Thanks @theRealAph and @TobiHartmann for reviews.

**Pull request closed without merging**
