### PR TITLE
8268768: idea.sh has been updated in surprising and incompatible ways

### PR DESCRIPTION
**Pull request by mcimadamore**
As the title says (please also refer to the JBS issue which describes all the issues in more details), the IDE support for IntelliJ has been updated with many enhancements as part of a seemingly innocuous "path handling" fix. The IDE doesn't appear to be usable in the same way it was in the past and many functionalities have been broken as a result (including support for jtreg test execution using the plugin).

For the above reasons, I'm reverting the plugin and idea.sh code to last known working version. Any _targeted_ fix can be re-applied after the revert. Larger enhancements need to be discussed in the proper venue:

https://openjdk.java.net/groups/ide-support/

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268768](https://bugs.openjdk.java.net/browse/JDK-8268768): idea.sh has been updated in surprising and incompatible ways

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4492/head:pull/4492` \
`$ git checkout pull/4492`

Update a local copy of the PR: \
`$ git checkout pull/4492` \
`$ git pull https://git.openjdk.java.net/jdk pull/4492/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4492`

View PR using the GUI difftool: \
`$ git pr show -t 4492`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4492.diff">https://git.openjdk.java.net/jdk/pull/4492.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
Agreed, let's back up and reevaluate.

**Comment by jonathan-gibbons** [comment]
Does this need back ported in 17 (or pushed to 17 and "back"ported into 18?

**Comment by mcimadamore** [comment]
I can push to 17 if desired, but I'll need a new PR for that

**Comment by jonathan-gibbons** [comment]
> I can push to 17 if desired, but I'll need a new PR for that

pushing to 17 would be nice; the script is equally broken and unusable there.

**Comment by mcimadamore** [comment]
closing - and recreating against 17

**Pull request closed without merging**
