### PR TITLE
8284888 : [macos] javax/swing/JInternalFrame/8146321/JInternalFrameIconTest.java failed with "NimbusLookAndFeel] : ERROR: icon and imageIcon not same."

### PR DESCRIPTION
**Pull request by prsadhuk**
Test used to fail in specific CI macos M1 system owing to miniscule color difference 

```
x 0 y 0 red1 171 red2 171 green1 174 green2 175 blue1 184 blue2 184
x 0 y 1 red1 172 red2 173 green1 177 green2 177 blue1 185 blue2 185
x 0 y 2 red1 173 red2 174 green1 177 green2 178 blue1 187 blue2 187
x 0 y 6 red1 0 red2 0 green1 1 green2 0 blue1 0 blue2 0
x 0 y 15 red1 1 red2 0 green1 0 green2 0 blue1 0 blue2 0
```

SInce we already have color-tolerance check present, there is no need of exact color value check.
Also, made the frame undecorated and remove unneeded library being built. 
Several iterations of the test passed in the same system (where it used to fail 4/10) along with other platforms (link in JBS)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8284888](https://bugs.openjdk.java.net/browse/JDK-8284888): [macos] javax/swing/JInternalFrame/8146321/JInternalFrameIconTest.java failed with "NimbusLookAndFeel] : ERROR: icon and imageIcon not same."

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8380/head:pull/8380` \
`$ git checkout pull/8380`

Update a local copy of the PR: \
`$ git checkout pull/8380` \
`$ git pull https://git.openjdk.java.net/jdk pull/8380/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8380`

View PR using the GUI difftool: \
`$ git pr show -t 8380`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8380.diff">https://git.openjdk.java.net/jdk/pull/8380.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
The JDK-8284888 bug is not public, cannot see a bug description.

**Comment by mrserb** [comment]
BTW did you have a chance to check why to images are not the same? Is it a problem in the robot or in the rendering? Can it be related to upscaling/downscaling?

**Comment by prsadhuk** [comment]
The bug is made public.
The images looks alike visually. I could not find anything wrong with rendering or robot which otherwise could have caused issue in other systems and platforms but it's only failing in this CI system (but color profile setting is ok). As per [JDK-8266247](https://bugs.openjdk.java.net/browse/JDK-8266247) which also happens in same mc, some faulty video memory is doubted.
Also, it's not happening everytime but intermittently so seeing all this, I have just relaxed color check a bit

**Comment by mrserb** [comment]
> The bug is made public. The images looks alike visually. I could not find anything wrong with rendering or robot which otherwise could have caused issue in other systems and platforms but it's only failing in this CI system (but color profile setting is ok). As per [JDK-8266247](https://bugs.openjdk.java.net/browse/JDK-8266247) which also happens in same mc, some faulty video memory is doubted. Also, it's not happening everytime but intermittently so seeing all this, I have just relaxed color check a bit

I am not sure that the color profile or something like that can be the root cause, because the test does not check an exact RGB of the color, instead, it renders the image twice and then compares, so it is strange that the results are different.

**Comment by mrserb** [comment]
> Not sure I understand. It does not render same image twice but it renders an `ImageIcon `and an `Icon `and compare the bufferedimage of those 2 so I guess it alright to not have exact color check ` if (red1 != red2 || green1 != green2 || blue1 != blue2) {` and rely on color tolerance which we have in many tests involving bufferedimages..

Sure these are not the same images, but still, we render images and get different results, on one specific system? If the robot is not a root cause then looks like the difference occurrs somewhere in the rendering pipeline?

**Comment by prrace** [comment]
This is occuring only on the M1 imac where despite having the right profile we see "off by 1/255" errors sometimes.

**Comment by prsadhuk** [comment]
> This is occurring only on the M1 imac where despite having the right profile we see "off by 1/255" errors sometimes. So why do we need a color tolerance of 25 ? Why isn't it 1 ?

It was there from start so did not tinker although I tested with tolerance of 10 which passed. Anyway, I have changed it to 1 which also passed in the intended system and all other platforms (CI job link in JBS)

**Comment by dcubed-ojdk** [comment]
@prsadhuk and @prrace,
We have 8 sightings of this failure mode on macosx-aarch64 in the jdk/jdk and
loom CIs. I'm about to start my noise suppression phase in preparation for the
potential Loom VT integration this weekend.

Will this (potential) fix be integrated soon or should I go ahead and ProblemList
this test on macosx-aarch64?

**Comment by dcubed-ojdk** [comment]
I will be integrating a ProblemListing for javax/swing/JInternalFrame/8146321/JInternalFrameIconTest.java
on macosx-aarch64 shortly. Please update this PR to include that ProblemListing changeset and then
UnProblemList the test in the PR so that the test runs in your pre-integration testing.

**Comment by prrace** [comment]
I believe this fix should be integrated before the weekend so there is no need to PL.
We can do that if it is needed.

**Comment by prrace** [comment]
> > This is occurring only on the M1 imac where despite having the right profile we see "off by 1/255" errors sometimes. So why do we need a color tolerance of 25 ? Why isn't it 1 ?
> 
> It was there from start so did not tinker although I tested with tolerance of 10 (which is the default tolerance used in other tests) which passed. Anyway, I have changed it to 1 which also passed in the intended system and all other platforms (CI job link in JBS)

Yes .. I went back and looked at the thread started here : https://mail.openjdk.java.net/pipermail/swing-dev/2016-January/005286.html
and it was in the first webrev and no one ever questioned why it was needed ..

perhaps some shadow effects were touching on the icon which is near the edge of the top-level window
but that could be cured easily in this test which is for JInternalFrame .. if it were actually an issue ..

**Comment by prrace** [comment]
OK so .. there's a difficulty facing this test. It has NO idea where the icon is. 
It randomly captures a chunk of the title bar and for Aqua it doesn't even come close to grabbing a single pixel
of the icon  - it is 100 pixels or more off.

So we are not comparing what we want to be comparing. It is pointless.

I think you need to come up with a way to make sure you are grabbing the right place which is L&F dependent ...

If you can't then you might as well scrap this useless test which is really just comparing pixels from the title bar.

**Comment by prsadhuk** [comment]
Yes, it looks for Aqua the icon is "after" the disabled close, maximize, resizable buttons 
whereas for other L&F those buttons are not there so for other L&F the icon is at extreme left 
but it is strange that the images captured during the failure "imageicon-fail.png" and "iconimage-fail.png" (attached in JBS) shows the image which resembles the icon image (a black square)
I tried to create JInternalFrame(String title, boolean resizable, boolean closable, boolean maximizable, boolean iconifiable) with false for all but it still shows those buttons for Aqua..

I am not sure if there is an y deterministic way to find out the location of the icon

**Comment by prsadhuk** [comment]
> I am not sure if there is an y deterministic way to find out the location of the icon

Modified to use the capture area as used in the original webrev for Aqua which will capture the title bar with icon
iconImage-fail

Testing in iMacs and other mac systems and other platforms are green.

**Comment by prsadhuk** [comment]
> > I am not sure if there is an y deterministic way to find out the location of the icon
> 
> Modified to use the capture area as used in the original webrev for Aqua which will capture the title bar with icon iconImage-fail
> 
> Capture area is modified slightly to omit the top inset too to remove the blue background from captured image.
> 
> Testing in iMacs and other mac systems and other platforms are green.

The original issue is apart from ImageIcon all other`icon is displayed lower than it should be and to the right of where it should be, covering part of the title text.`
Screenshot 2022-05-06 at 9 40 41 AM

whereas for ImageIcon
Screenshot 2022-05-06 at 10 47 47 AM

so I think it should be ok testing the titlebar the bufferedimage with ImageIcon and Icon will be different thus testing the fix as well keeping all platforms happy

**Pull request closed without merging**
