### PR TITLE
8329968: os::random should be random

### PR DESCRIPTION
**Pull request by tstuefe**
Hi,

This change ensures that the random seed of os::random is initialized randomly. Before this patch, every sequence of os::random calls gave the same results. With this patch, a quasi-random seed based on javaTimeNanos is used.

Where this matters the most:

- Random distribution of ihashes. Atm, ihashes are always the same for the same sequence of System.identityHashCode.

- We use os::random to fuzzing gtests. This is the part most important to me. I want gtest tests that use os::random for stress testing data structures to be as efficient as possible in tickling out pathological behavior.

Note that this issue turned out to be much more controversial than I expected. Please see pro- and con-arguments in JBS comment section. I would like a consensus on this issue before pushing the fix (pinging @dholmes). If we cannot agree that this needs fixing, I'd be content with at least the gtests being random. So, a smaller version of this change would be to use a separate random seed for gtests.

---

Tests:
- tested that the regression test fails with Stock JVM, passes with patched JVM
- GHAs
(will do more tests to see if the new randomness shakes lose bugs. However, before investing the work I'd like consensus that this PR can go forward)

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329968](https://bugs.openjdk.org/browse/JDK-8329968): os::random should be random (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18702/head:pull/18702` \
`$ git checkout pull/18702`

Update a local copy of the PR: \
`$ git checkout pull/18702` \
`$ git pull https://git.openjdk.org/jdk.git pull/18702/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18702`

View PR using the GUI difftool: \
`$ git pr show -t 18702`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18702.diff">https://git.openjdk.org/jdk/pull/18702.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18702#issuecomment-2133020149)

### CODE REVIEW

**Comment by tstuefe** [comment]
CDS errors will be addressed separately by https://github.com/openjdk/jdk/pull/18735

**Comment by tstuefe** [comment]
Linux build error unrelated.

**Comment by dholmes-ora** [comment]
> Random distribution of ihashes. Atm, ihashes are always the same for the same sequence of System.identityHashCode.

And this is a problem because??? Conversely if you change the ihashes every time an application runs what affect does this have on the general performance of hashmaps? Does  this not introduce some instability? Could some seeds lead to pathological hashmap behaviour?

> We use os::random to fuzzing gtests

Can you not use FastRandom for that? Or employ the same technique that FastRandom does?

**Comment by tstuefe** [comment]
> > Random distribution of ihashes. Atm, ihashes are always the same for the same sequence of System.identityHashCode.
> 
> And this is a problem because???

A feeling of unease. I cannot conjure an attack scenario up that relies on predictable ihashes, but that does not mean there is none. And, inversely, you probably cannot prove that there is none either. Therefore, In the end, it comes down to a risk assessment. 

> Conversely if you change the ihashes every time an application runs what affect does this have on the general performance of hashmaps? Does this not introduce some instability? Could some seeds lead to pathological hashmap behaviour?

That is possible, albeit unlikely. I tested the RNG yesterday (after falsely thinking the RNG had a bad distribution) with a large number of different seeds, and the distribution seemed to be fine for all testd seeds. (There was an oddity if the seed was 0, but I did not dive into that).

Considering that today's ihash generation start being more random if multiple threads come into play, I would guess different seeds should not be a problem.

> 
> > We use os::random to fuzzing gtests
> 
> Can you not use FastRandom for that? Or employ the same technique that FastRandom does?

Certainly. That is my fallback plan if we don't fix os::random.

**Comment by jdksjolen** [comment]
Hi,

If we can't guarantee reproducibility because of the non-determinism introduced by mutliple threads, then what point is there in keeping the seed the same for each run? It makes sense to me that the function should be the one which is least surprising, and that's coming from someone that generally jumps-to-definition a lot (and deeply) to find out what happens in the code. It's certainly surprising to me that we don't seed the RNG with some form of non-constant entropy (even if it's a poor one).

Today we have very strong tools, such as `rr` (deterministic+time travelling debugging), which we can use for reproducing runs. Partial reproducibility based on having the same initial seed seems fragile compared to that.

Finally, if you're trying to reproduce an issue on a JDK and you want to make as much state reproducible as possible, then wouldn't you have to go around in all of our RNG:s and figure out what their initial seeds were? Just fixing `os::random` doesn't seem as likely.

If `os::random` was added today, never having existed before, then I would think it would be added with some form of non-constant seeding, no?

All the best,
Johan

**Comment by dholmes-ora** [comment]
> I would think it would be added with some form of non-constant seeding, no?

Well if you or Thomas were adding it then apparently yes. :) But such questions are somewhat pointless. Things would be done today based on the education and experience of the person doing it. The whole JDK would be different. :)

**Pull request closed without merging**
