### PR TITLE
8279294: NonblockingQueue::try_pop may improperly indicate queue is empty

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this improvement to NonblockingQueue::try_pop.  The old code
returned an indication that the queue was empty in some cases where that
wasn't true.  In particular, contending try_pop operations could result in
some incorrectly indicating empty.  The change fixes that and improves the
interaction between contending try_pops.

Testing:
mach5 tier1-3

Lots of testing of this change in conjunction with others as part of
investigating and fixing JDK-8273383.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279294](https://bugs.openjdk.java.net/browse/JDK-8279294): NonblockingQueue::try_pop may improperly indicate queue is empty

### Reviewers
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to 562729a14e25f7eb97e2b9464748e250bae36dbf
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 562729a14e25f7eb97e2b9464748e250bae36dbf

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7149/head:pull/7149` \
`$ git checkout pull/7149`

Update a local copy of the PR: \
`$ git checkout pull/7149` \
`$ git pull https://git.openjdk.java.net/jdk pull/7149/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7149`

View PR using the GUI difftool: \
`$ git pr show -t 7149`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7149.diff">https://git.openjdk.java.net/jdk/pull/7149.diff</a>

</details>

### CODE REVIEW

**Review by walulyai — APPROVED** [review]
Lgtm!

Suggestion:
With the comments growing after each change, maybe we rename `result` to `old_head`

**Comment by kimbarrett** [comment]
> Suggestion: With the comments growing after each change, maybe we rename `result` to `old_head`

I've been thinking that `result` might have been a poor naming choice here.  I think I'd like to do such a variable renaming separately though.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by kimbarrett** [comment]
Thanks @walulyai and @tschatzl for reviews.

**Pull request closed without merging**
