### PR TITLE
JDK-8305815: Update Libpng to 1.6.39

### PR DESCRIPTION
**Pull request by honkar-jdk**
Updated libpng from 1.6.38 to 1.6.39.

- libpng.md file updated accordingly
- src code files updated from upstream

CIient (CI Testing) and SplashScreen related tests work as expected with the changes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305815](https://bugs.openjdk.org/browse/JDK-8305815): Update Libpng to 1.6.39

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13755/head:pull/13755` \
`$ git checkout pull/13755`

Update a local copy of the PR: \
`$ git checkout pull/13755` \
`$ git pull https://git.openjdk.org/jdk.git pull/13755/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13755`

View PR using the GUI difftool: \
`$ git pr show -t 13755`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13755.diff">https://git.openjdk.org/jdk/pull/13755.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13755#issuecomment-1531897231)

### CODE REVIEW

**Comment by honkar-jdk** [comment]
@prrace Please review

**Comment by mrserb** [comment]
Please add a note about what testing was done for this patch.

**Comment by honkar-jdk** [comment]
> Please add a note about what testing was done for this patch.

Updated the PR description with testing info.

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
