### PR TITLE
8253970: Build error: address argument to atomic builtin must be a pointer to integer or pointer ('volatile narrowOop *' invalid)

### PR DESCRIPTION
**Pull request by DamonFool**
__sync_val_compare_and_swap shouldn't call with narrowOop* for clang after JDK-8247912.
Before passing type T to __sync_val_compare_and_swap, the fix converts T to uint32_t* if sizeof(T) == 4.

Testing:
 - Zero VM build on Linux and MacOS with clang
 - Zero VM build on Linux with gcc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8253970](https://bugs.openjdk.java.net/browse/JDK-8253970): Build error: address argument to atomic builtin must be a pointer to integer or pointer ('volatile narrowOop *' invalid)

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/496/head:pull/496`
`$ git checkout pull/496`

### CODE REVIEW

**Comment by kimbarrett** [comment]
No, don't make this change.  Something else is going wrong here.  The Platform layer shouldn't be called with enum types; the higher level platform-independent layer should have canonicalized such to the associated underlying integral types.

**Comment by kimbarrett** [comment]
Apparently I misremembered.  The platform-independent layer isn't doing that canonicalization of enum types to associated integral types.  But I think it should be in some places.

**Comment by DamonFool** [comment]
Thanks @kimbarrett for your review.
I'll think it more after my holiday.

**Comment by kimbarrett** [comment]
What version of clang?

gcc (at least recent versions) allows enum types (both scoped and unscoped) for both the __sync_xxx functions and for the __atomic_xxx functions. (The documentation for both say the type can be an integral scalar or pointer type. Enums are not integral types.)

So this seems to be a clang incompatibility with gcc, which may be a clang bug.

The __sync_xxx functions have been legacy since gcc4.7, having been superseded by the __atomic_xxx functions. Could zero be updated here?  Would that help? If clang is incompatible with gcc for the __sync_xxx functions, it might also be incompatible for the __atomic_xxx functions.

BTW, the memory ordering by the zero implementation of Atomic::xchg in terms of __sync_lock_test_and_set looks wrong to me.  I think the fence() is on the wrong side of the __sync_xxx operation.

**Comment by DamonFool** [comment]
The following two versions of clang can reproduce the bug.

$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.0.0
Thread model: posix

# clang -v
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by DamonFool** [comment]
Hi @kimbarrett ,

I replace __sync_val_compare_and_swap whith __atomic_compare_exchange and it really woks.
Thanks for your help.

I also fix the following bug when building zero VM on MacOS.
--------------------------------------------------------------
   * For target hotspot_variant-zero_libjvm_objs_os_bsd_zero.o:
   ./src/hotspot/os_cpu/bsd_zero/os_bsd_zero.cpp:176:21: error: no member named 'in_stack_yellow_reserved_zone' in 'JavaThread'
           if (thread->in_stack_yellow_reserved_zone(addr)) {
               ~~~~~~  ^
   ./src/hotspot/os_cpu/bsd_zero/os_bsd_zero.cpp:177:19: error: no member named 'disable_stack_yellow_reserved_zone' in 'JavaThread'
             thread->disable_stack_yellow_reserved_zone();
             ~~~~~~  ^
   ./src/hotspot/os_cpu/bsd_zero/os_bsd_zero.cpp:180:26: error: no member named 'in_stack_red_zone' in 'JavaThread'
           else if (thread->in_stack_red_zone(addr)) {
                    ~~~~~~  ^
   ./src/hotspot/os_cpu/bsd_zero/os_bsd_zero.cpp:181:19: error: no member named 'disable_stack_red_zone' in 'JavaThread'
             thread->disable_stack_red_zone();
             ~~~~~~  ^
--------------------------------------------------------------

Testing:
  - Zero VM builds on Linux/x64 with both clang and gcc
  - Zero VM build on MacOS

As for the memory ordering of the zero implementation, it might be better to file another bug to fix it.
What do you think?

Thanks.
Best regards,
Jie

**Comment by DamonFool** [comment]
Thanks @kimbarrett for your review.
I will spend some time to digest your comments on the memory model semantics.

**Comment by DamonFool** [comment]
Hi @kimbarrett ,

I agree with you.
All of the atomic operations that imply a read-modify-write action guarantee a two-way memory barrier across that operation.
So FULL_MEM_BARRIERs (before and after the atomic operation) should be added.

The patch has been updated.
Please review it.
Thanks.

Best regards,
Jie

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by DamonFool** [comment]
Thanks @kimbarrett for your review.
Will push it tomorrow if there is no objection.

**Comment by DamonFool** [comment]
OK.

May I get a second review for this change?
Thanks.

**Comment by DamonFool** [comment]
Hi all,

May I get a second review to finish this issue?
Some of our testing pipelines become red due to this bug.

Thanks.
Best regards,
Jie

**Review by dholmes-ora — APPROVED** [review]
Seems consistent with the aarch64 code.

Thanks,
David

**Comment by DamonFool** [comment]
Thanks @dholmes-ora for your review.
/integrate

**Pull request closed without merging**
