### PR TITLE
JDK-8295406: C1 crash with -XX:TypeProfileArgsLimit=0 -XX:TypeProfileLevel=222

### PR DESCRIPTION
**Pull request by dafedafe**
`-XX:TypeProfileArgsLimit=0 -XX:TypeProfileLevel=222` cause an assert to fail in `LIRGenerator::profile_arguments`.

`LIRGenerator::profile_arguments` actually checks if arguments need to be profiled but the `MethodData::profile_arguments` method doesn't take `TypeProfileArgsLimit=0` into account.

Adding a check for _TypeProfileArgsLimit>0_ to determine if arguments have to be profiled.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295406](https://bugs.openjdk.org/browse/JDK-8295406): C1 crash with -XX:TypeProfileArgsLimit=0 -XX:TypeProfileLevel=222

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11843/head:pull/11843` \
`$ git checkout pull/11843`

Update a local copy of the PR: \
`$ git checkout pull/11843` \
`$ git pull https://git.openjdk.org/jdk pull/11843/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11843`

View PR using the GUI difftool: \
`$ git pr show -t 11843`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11843.diff">https://git.openjdk.org/jdk/pull/11843.diff</a>

</details>

### CODE REVIEW

**Comment by dafedafe** [comment]
@rwestrel thanks a lot for your hint!

**Comment by dafedafe** [comment]
Added `TestTypeProfileArgsLimit` regression test that checks for `TypeProfileArgsLimit=0` and `TypeProfileLevel=222` plus a few other combinations of `TypeProfileArgsLimit`, `TypeProfileLevel` and `TypeProfileParmsLimit`.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me!

**Comment by dafedafe** [comment]
@TobiHartmann thanks a lot for reviewing it.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by dafedafe** [comment]
@TobiHartmann @vnkozlov thanks a lot for your reviews!

**Pull request closed without merging**
