### PR TITLE
8342602: Remove JButton/PressedButtonRightClickTest test

### PR DESCRIPTION
**Pull request by aivanov-jdk**
The `javax/swing/JButton/PressedButtonRightClickTest.java` test that was added by [JDK-8049069](https://bugs.openjdk.org/browse/JDK-8049069) fully duplicates an existing test `javax/swing/JButton/bug4490179.java`.

To save time running tests, I'm removing `PressedButtonRightClickTest.java`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342602](https://bugs.openjdk.org/browse/JDK-8342602): Remove JButton/PressedButtonRightClickTest test (**Bug** - P4)

### Reviewers
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21587/head:pull/21587` \
`$ git checkout pull/21587`

Update a local copy of the PR: \
`$ git checkout pull/21587` \
`$ git pull https://git.openjdk.org/jdk.git pull/21587/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21587`

View PR using the GUI difftool: \
`$ git pr show -t 21587`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21587.diff">https://git.openjdk.org/jdk/pull/21587.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21587#issuecomment-2422868986)
</details>

### CODE REVIEW

**Comment by mrserb** [comment]
The `bug4490179` verifies the code using the listener added to the button while the `PressedButtonRightClickTest` verifies the code using `getModel().isPressed()` which is not necessary the same.

btw it is unclear why the bug4490179 test is not mention in the https://bugs.openjdk.org/browse/JDK-8049069

**Comment by aivanov-jdk** [comment]
> The `bug4490179` verifies the code using the listener added to the button while the `PressedButtonRightClickTest` verifies the code using `getModel().isPressed()` which is not necessary the same.

The description of [JDK-8049069](https://bugs.openjdk.org/browse/JDK-8049069):

> 1. Press JButton with left mouse button and don't release it.
> 2. While holding left button, press and release right button
> Expected behaviour: JButton is still pressed
> Actual behaviour: JButton is released.

This matches the description of [JDK-4490179](https://bugs.openjdk.org/browse/JDK-4490179):

> On a JButton, press the left mouse button and, without releasing it, click the right button. This (incorrectly) fires an ActionEvent and disarms the button.

Indeed, if I add `ActionListener` to `JButton` to the test case `JButtonReleaseBug.java` attached to JDK-8049069, the action event is triggered as soon as I release the right mouse button because the model goes from pressed state to released state.

Even though the tests verify slightly different conditions, the effect is the same. The button must remain pressed when right mouse button is pressed and released.

> btw it is unclear why the bug4490179 test is not mention in the https://bugs.openjdk.org/browse/JDK-8049069

I do not know. I assume the reporter of JDK-8049069 didn't know a test had already existed.

According the first comment, “Detected by test: Swing_JButton/Automated/RButtonEventOP.” It looks the bug was found by SQE and a test in the SQE test suite.

**Comment by mrserb** [comment]
> Even though the tests verify slightly different conditions, the effect is the same. The button must remain pressed when right mouse button is pressed and released.

But it's still a different condition, and removing the test will reduce coverage.

**Comment by aivanov-jdk** [comment]
> > Even though the tests verify slightly different conditions, the effect is the same. The button must remain pressed when right mouse button is pressed and released.
> 
> But it's still a different condition, and removing the test will reduce coverage.

No, it will not reduce the coverage. If `model.isPressed()` returns `true`, it means the action event isn't triggered; if `model.isPressed()` becomes `false`, the action event is triggered.

Both tests verify *the same end result*: no action event is triggered if mouse button 3 is pressed and released while mouse button 1 is pressed. `bug4490179.java` does it explicitly whereas `PressedButtonRightClickTest.java` does it implicitly by checking the state of the button model.

**Comment by DamonGuy** [comment]
> > > Even though the tests verify slightly different conditions, the effect is the same. The button must remain pressed when right mouse button is pressed and released.
> > 
> > 
> > But it's still a different condition, and removing the test will reduce coverage.
> 
> No, it will not reduce the coverage. If `model.isPressed()` returns `true`, it means the action event isn't triggered; if `model.isPressed()` becomes `false`, the action event is triggered.
> 
> Both tests verify _the same end result_: no action event is triggered if mouse button 3 is pressed and released while mouse button 1 is pressed. `bug4490179.java` does it explicitly whereas `PressedButtonRightClickTest.java` does it implicitly by checking the state of the button model.

Looking at both of these tests, it does look like the coverage will remain the same. Looks like there's just two ways to test the same functionality, and the original issue reported for each bug is virtually identical. 

If removing one test is actually problematic, you could edit the remaining test to check for both `isPressed()` and for the action event trigger, but that seems unnecessary. And I think checking for the action event rather than the state of the button just makes more sense.

Removing the suggested test seems right to me. The additional test was probably just created due to not knowing the older test existed as mentioned.

**Review by DamonGuy — APPROVED** [review]

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
