### PR TITLE
8290466: Default to --with-source-date=current to avoid unmodified Hotspot recompilation

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for symptoms and rationale.

In short, after [JDK-8288396](https://bugs.openjdk.org/browse/JDK-8288396) moved the timestamp to `CFLAGS_VM_VERSION` macro, which changes with every build, we get Hotspot recompilation every time, even when Hotspot is not modified.

I believe current behavior is correct for `--with-source-date=updated` (current default): you do Hotspot build, you get updated build timestamp, which forces recompilation of affected compilation units, relinkage, re-creation of jmods/jimage. The way out is to switch to `--with-source-date=current`, which would only get the build timestamp at configure time.

CIs and build farms are likely reconfiguring before every build anyway, so their behavior is unlikely to be affected. But this switch definitely improves the day-to-day OpenJDK development work: it saves >50 seconds on every `make` for my machine, see below.

Back-to-back unmodified build before:

```
$ CONF=linux-x86_64-server-release time make hotspot
Building target 'hotspot' in configuration 'linux-x86_64-server-release'
Finished building target 'hotspot' in configuration 'linux-x86_64-server-release'

39.03user 10.97system 0:56.89elapsed 87%CPU (0avgtext+0avgdata 2048944maxresident)k
363616inputs+4108072outputs (484major+1100154minor)pagefaults 0swaps

$ CONF=linux-x86_64-server-release time make hotspot
Building target 'hotspot' in configuration 'linux-x86_64-server-release'
Finished building target 'hotspot' in configuration 'linux-x86_64-server-release'

38.18user 9.02system 0:49.18elapsed 95%CPU (0avgtext+0avgdata 2048788maxresident)k
40inputs+4101112outputs (0major+1100077minor)pagefaults 0swaps
```

Back-to-back unmodified build after:

```
$ CONF=linux-x86_64-server-release time make hotspot
Building target 'hotspot' in configuration 'linux-x86_64-server-release'
Finished building target 'hotspot' in configuration 'linux-x86_64-server-release'

2.15user 0.22system 0:02.59elapsed 91%CPU (0avgtext+0avgdata 49480maxresident)k
0inputs+176outputs (0major+55506minor)pagefaults 0swaps

$ CONF=linux-x86_64-server-release time make hotspot
Building target 'hotspot' in configuration 'linux-x86_64-server-release'
Finished building target 'hotspot' in configuration 'linux-x86_64-server-release'

2.18user 0.14system 0:02.46elapsed 94%CPU (0avgtext+0avgdata 49332maxresident)k
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290466](https://bugs.openjdk.org/browse/JDK-8290466): Default to --with-source-date=current to avoid unmodified Hotspot recompilation

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [0f0163f5](https://git.openjdk.org/jdk/pull/9638/files/0f0163f582c29e11e5d8fc70321523d712106a3d)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [0f0163f5](https://git.openjdk.org/jdk/pull/9638/files/0f0163f582c29e11e5d8fc70321523d712106a3d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9638/head:pull/9638` \
`$ git checkout pull/9638`

Update a local copy of the PR: \
`$ git checkout pull/9638` \
`$ git pull https://git.openjdk.org/jdk pull/9638/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9638`

View PR using the GUI difftool: \
`$ git pr show -t 9638`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9638.diff">https://git.openjdk.org/jdk/pull/9638.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by shipilev** [comment]
Any other opinions?

**Comment by shipilev** [comment]
@magicus -- you are good with this, or?

**Comment by magicus** [comment]
Sorry for the slow response, I'm on vacation. 😎 

This looks good to me. Just update the default value in the help text as well:
```
      [how to set SOURCE_DATE_EPOCH ('updated', 'current', 'version' a timestamp or an ISO-8601 date) @<:@current/value of SOURCE_DATE_EPOCH@:>@])],
```

(github does not allow me to comment on it since it's too far away from any changed lines in the PR)

**Review by magicus — APPROVED** [review]

**Comment by shipilev** [comment]
> Sorry for the slow response, I'm on vacation. 

Ah. I seen a few replies from you assumed you are back.

> ```
>       [how to set SOURCE_DATE_EPOCH ('updated', 'current', 'version' a timestamp or an ISO-8601 date) @<:@current/value of SOURCE_DATE_EPOCH@:>@])],
> ```

Good spot, fixed in new commit.

**Comment by shipilev** [comment]
Entering the week with faster builds.

/integrate

**Pull request closed without merging**
