### PR TITLE
8303508: Vector.lane() gets wrong value on x86

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Incorrectness happens because compiler absorbs casting IR chain during idealizations.
Sign extending the result of sub-word extraction operation.

Please refer to detailed discussion on https://github.com/openjdk/jdk/pull/13070#issuecomment-1479779537 

Best Regards,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303508](https://bugs.openjdk.org/browse/JDK-8303508): Vector.lane() gets wrong value on x86

### Reviewers
 * [Eric Liu](https://openjdk.org/census#eliu) (@theRealELiu - Committer)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13152/head:pull/13152` \
`$ git checkout pull/13152`

Update a local copy of the PR: \
`$ git checkout pull/13152` \
`$ git pull https://git.openjdk.org/jdk.git pull/13152/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13152`

View PR using the GUI difftool: \
`$ git pr show -t 13152`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13152.diff">https://git.openjdk.org/jdk/pull/13152.diff</a>

</details>

### CODE REVIEW

**Review by theRealELiu — APPROVED** [review]
Looks good to me. Thanks for your fix.

**Review by TobiHartmann — APPROVED** [review]
Looks good. I submitted some testing and will report back once it finished.

**Comment by TobiHartmann** [comment]
All tests passed.

**Pull request closed without merging**
