### PR TITLE
8213719: Both sect163r2 and sect163k1 are default curves for field size 163

### PR DESCRIPTION
**Pull request by wangweij**
There should only be one curve having type BD or PD in CurveDB.java for any given length. Here we keep the last one (sect163r2) so there's no behavior change.

I tried to search on the net to see if there is a consensus on which curve is meant to be the default one for a size, but cannot find one for 163. If anyone can find it I'll be happy to take a look.

Noreg-cleanup.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8213719](https://bugs.openjdk.java.net/browse/JDK-8213719): Both sect163r2 and sect163k1 are default curves for field size 163

### Reviewers
 * [Valerie Peng](https://openjdk.java.net/census#valeriep) (@valeriepeng - **Reviewer**)
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1485/head:pull/1485`
`$ git checkout pull/1485`

### CODE REVIEW

**Comment by valeriepeng** [comment]
> There should only be one curve having type BD or PD in CurveDB.java for any given length. Here we keep the last one (sect163r2) so there's no behavior change.
> 
> I tried to search on the net to see if there is a consensus on which curve is meant to be the default one for a size, but cannot find one for 163. If anyone can find it I'll be happy to take a look.
> 
Based on CurveDB line 141, it seems we uses the first one and discards the rest? Are you sure we keep the last one?
Don't have answers for your questions though.

**Comment by wangweij** [comment]
> Based on CurveDB line 141, it seems we uses the first one and discards the rest? Are you sure we keep the last one?
> Don't have answers for your questions though.

Before this change both sect163k1 and sect163r2 have "BD" so both will be added to lengthMap and the 2nd one wins out.

**Comment by valeriepeng** [comment]
> 
> 
> > Based on CurveDB line 141, it seems we uses the first one and discards the rest? Are you sure we keep the last one?
> > Don't have answers for your questions though.
> 
> Before this change both sect163k1 and sect163r2 have "BD" so both will be added to lengthMap and the 2nd one wins out.

Hmm, ok, I re-read the code and it's true that both are added to the lengthMap. Actually, non-PD/non-BD entries are added to the length map too if no entries for such length in length map is present at time of the add() call, right?

**Comment by wangweij** [comment]
> > > Based on CurveDB line 141, it seems we uses the first one and discards the rest? Are you sure we keep the last one?
> > > Don't have answers for your questions though.
> > 
> > 
> > Before this change both sect163k1 and sect163r2 have "BD" so both will be added to lengthMap and the 2nd one wins out.
> 
> Hmm, ok, I re-read the code and it's true that both are added to the lengthMap. Actually, non-PD/non-BD entries are added to the length map too if no entries for such length in length map is present at time of the add() call, right?

Yes, I think that's what "if there are multiple matches for the given size, an arbitrary one is returns" in the comment of `lookup(int)` means. If there is a PD/BD with the same length, the previously added will be substituted anyway.

**Comment by valeriepeng** [comment]
Alright, I have no more comments/questions. Thanks.

**Review by valeriepeng — APPROVED** [review]

**Review by XueleiFan — APPROVED** [review]

**Pull request closed without merging**
