### PR TITLE
8252593: [TESTBUG] serviceability/jvmti/GetLocalVariable/GetLocalWithoutSuspendTest.java failed with JVMTI_ERROR_INVALID_SLOT

### PR DESCRIPTION
**Pull request by reinrich**
Continuing review [1] after transition to Git/Github.

I still cannot reproduce the issue.

RFC on alternatives:

1. Integrate this change and ignore future JVMTI_ERROR_INVALID_SLOT
2. Don't ignore JVMTI_ERROR_INVALID_SLOT but integrate the rest of this patch. If the test still fails with JVMTI_ERROR_INVALID_SLOT we will at least know the depth of the frame.
3. Add trace code to VM_GetOrSetLocal in !PRODUCT or ASSERT configurations depending on an option or property.

Any other ideas?

I'm in favour of 1.

[1] http://mail.openjdk.java.net/pipermail/serviceability-dev/2020-September/032876.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252593](https://bugs.openjdk.java.net/browse/JDK-8252593): [TESTBUG] serviceability/jvmti/GetLocalVariable/GetLocalWithoutSuspendTest.java failed with JVMTI_ERROR_INVALID_SLOT

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/142/head:pull/142`
`$ git checkout pull/142`

### CODE REVIEW

**Comment by reinrich** [comment]
Thanks @iignatev for providing the hint that helped finding the cause for the JVMTI_ERROR_INVALID_SLOT

https://bugs.openjdk.java.net/browse/JDK-8252593?focusedCommentId=14368599&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14368599

I would like to take a different approach now for fixing this by making sure the JVMTI GetLocalObject() call refers to one of the recursiveMethod frames on stack.

How to do that? Can I close this PR and create a new branch JDK-8252593-2 and then a new PR?

**Comment by dcubed-ojdk** [comment]
You can also change the PR back to draft, revamp the changes and then
change the PR back to "ready for review" or whatever it's called.

**Comment by reinrich** [comment]
Thanks @dcubed-ojdk ! I didn't know the PR can be converted back to draft. I will try that.

**Comment by reinrich** [comment]
> I would like to take a different approach now for fixing this by making sure the JVMTI GetLocalObject() call refers to one of the recursiveMethod frames on stack.

After a closer look I don't think this is possible. The GetLocalObject() call should target a frame deep in the stack to prolongue the stackwalk. So the depth D will be large. This means the target thread has to wait in a frame that has more than D caller frames to make sure at D is a frame of recursiveMethod. This will make the test less sensitive as a regression test because if there is an unsafe stackwalk to find the target frame for the GetLocalObject() at depth D it will likely still succeed, because the target thread does not return from all the recursive activations of recursiveMethod.

So I'm still proposing the original fix which silently accepts JVMTI_ERROR_INVALID_SLOT.

**Review by sspitsyn — APPROVED** [review]

**Review by plummercj — APPROVED** [review]

**Comment by reinrich** [comment]
Thanks Serguei and Chris. I'll integrate this tomorrow.

**Pull request closed without merging**
