### PR TITLE
8292848: AWT_Mixing and TrayIcon tests fail on el8 with hard-coded isOel7

### PR DESCRIPTION
**Pull request by tkiriyama**
Could you please review the JDK-8292848 bug fixes?
The purpose of the isOel7 method is to detect differences in GNOME version changes, and the isOel7 
result should be true after version 8.
I modified the isOel7 method to use regular expressions instead of hard-coded versions to be able to 
detect the new os version.
I also changed the method name to match the new conditions.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292848](https://bugs.openjdk.org/browse/JDK-8292848): AWT_Mixing and TrayIcon tests fail on el8 with hard-coded isOel7

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9995/head:pull/9995` \
`$ git checkout pull/9995`

Update a local copy of the PR: \
`$ git checkout pull/9995` \
`$ git pull https://git.openjdk.org/jdk pull/9995/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9995`

View PR using the GUI difftool: \
`$ git pr show -t 9995`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9995.diff">https://git.openjdk.org/jdk/pull/9995.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]
I guess this will do what was previously being done on OL7 .. but the way it is done it is fragile
and surely it can't be specific to OL .. and there's some pretty hokey adjustments going on in some of these tests.
I think some day these tests will need to be re-examined.

**Comment by tkiriyama** [comment]
@prrace 
Thank you for your review. I agree with another consideration .

I think two reviews are required thisfix to be integrated. Could anyone please review this fix?

**Review by mrserb — APPROVED** [review]

**Comment by tkiriyama** [comment]
@prrace 
Could you sponsor  this pull request, please?

**Comment by tkiriyama** [comment]
Thank you for your support.

@mrserb 
If @prrace cannot be sponsor, could you sponsor this pull request, please?

**Comment by tkiriyama** [comment]
@prrace 
I’m sorry to bother you again. Could you sponsor this pull request, please?

**Comment by jayathirthrao** [comment]
Since it is already approved by Phil and Sergey, i have sponsored it.

**Pull request closed without merging**
