### PR TITLE
JDK-8288121: [JVMCI] Re-export the TerminatingThreadLocal functionality to the graal compiler.

### PR DESCRIPTION
**Pull request by tzezula**
JVMCI compilers need to release resources tied to a thread-local variable when the associated thread is exiting. The JDK internally uses the jdk.internal.misc.TerminatingThreadLocal class for this purpose. This pull request re-exports the TerminatingThreadLocal functionality to JVMCI compilers.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288121](https://bugs.openjdk.org/browse/JDK-8288121): [JVMCI] Re-export the TerminatingThreadLocal functionality to the graal compiler.

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - Committer) ⚠️ Review applies to [9156847a](https://git.openjdk.org/jdk/pull/9107/files/9156847aa1a59d1ba8ac15edb2cdd2b37793cdd1)
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**) ⚠️ Review applies to [9156847a](https://git.openjdk.org/jdk/pull/9107/files/9156847aa1a59d1ba8ac15edb2cdd2b37793cdd1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9107/head:pull/9107` \
`$ git checkout pull/9107`

Update a local copy of the PR: \
`$ git checkout pull/9107` \
`$ git pull https://git.openjdk.org/jdk pull/9107/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9107`

View PR using the GUI difftool: \
`$ git pr show -t 9107`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9107.diff">https://git.openjdk.org/jdk/pull/9107.diff</a>

</details>

### CODE REVIEW

**Comment by vnkozlov** [comment]
@dougxc, can you review this? It is out of my expertise.

**Review by dougxc — APPROVED** [review]

**Comment by dougxc** [comment]
@plevart any chance you could look at this PR since you introduced `TerminatingThreadLocal`.

**Comment by dougxc** [comment]
Note that we also considered an alternate solution which would be to export `java.base/jdk.internal.misc` to `jdk.internal.vm.compiler`. However, this is not possible without making `jdk.internal.vm.compiler` a non-upgradeable module.

**Review by tkrodriguez — APPROVED** [review]
I don't see any better solution at the moment.

**Pull request closed without merging**
