### PR TITLE
8255579: x86: Use cmpq(Register,Address) in safepoint_poll

### PR DESCRIPTION
**Pull request by shipilev**
JDK-8253180 added a new block in `safepoint_poll` that uses broken `cmpq` (JDK-8255550): it effectively does the comparison with operands swapped. It makes sense to use the non-broken `cmpq`, as to avoid changing the condition code and thus making the code less understandable. See the discussion in #910. 

Testing:
  - [x] `tier1` with Z (some SA tests fail, and some other fail with OOME -- seem to be expected/problem-listed)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255579](https://bugs.openjdk.java.net/browse/JDK-8255579): x86: Use cmpq(Register,Address) in safepoint_poll

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/924/head:pull/924`
`$ git checkout pull/924`

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good. I also got confused about this. When this instruction didn't work the way I thought it would, I thought it must be a weird style thing, that everything is right to left in the assembler, for consistency, so it would read from right to left. Then I convinced myself it made sense. But the instruction being incorrectly encoded also checks out. Sigh. Anyway, I ran some local testing that would just fall over immediately if this didn't work. And it seems to work.

**Comment by shipilev** [comment]
Thanks @fisk! Would you like someone else to look at this, or your review is enough?

**Comment by fisk** [comment]
Since the encodings of the two instructions are literally identical, I think this classifies as a trivial change. So I'm okay with one review.

**Review by fisk — APPROVED** [review]

**Review by zhengyu123 — APPROVED** [review]
Tested with Shenandoah + concurrent stack processing on my personal branch, works fine.

**Comment by shipilev** [comment]
Tests look clean. Pushing, thanks @fisk, @zhengyu123.

/integrate

**Pull request closed without merging**
