### PR TITLE
JDK-8289741 :  Remove unused imports from DTDBuilder.java

### PR DESCRIPTION
**Pull request by scientificware**
This is tracked in JBS as

[JDK-8289741](https://bugs.openjdk.org/browse/JDK-8289741) and duplicated by [JDK-8290070](https://bugs.openjdk.org/browse/JDK-8290070)

Unused imports in DTDBuider.java.

> **Remove unused imports from DTDBuilder.java**

Some imports are no more used.

- java.io.FileNotFoundException;
- java.io.BufferedInputStream;
- java.io.OutputStream;
- java.util.BitSet;
- java.util.StringTokenizer;
- java.util.Properties;
- java.util.zip.DeflaterOutputStream;
- java.util.zip.Deflater;
- java.net.URL;

https://github.com/scientificware/jdk/issues/4

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289741](https://bugs.openjdk.org/browse/JDK-8289741): Remove unused imports from DTDBuilder.java

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9360/head:pull/9360` \
`$ git checkout pull/9360`

Update a local copy of the PR: \
`$ git checkout pull/9360` \
`$ git pull https://git.openjdk.org/jdk pull/9360/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9360`

View PR using the GUI difftool: \
`$ git pr show -t 9360`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9360.diff">https://git.openjdk.org/jdk/pull/9360.diff</a>

</details>

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
@scientificware Do you need an entry in the JBS for this PR?

**Comment by scientificware** [comment]
Hi @TheShermanTanker,
Yes I need it.
I'm waiting the Issue Id.
Regards

**Comment by TheShermanTanker** [comment]
Alright, was asking since I can help create one for you, but it seems that others already have it covered

**Comment by scientificware** [comment]
@TheShermanTanker , thank you for asking and helping.

>  it seems that others already have it covered

In fact, I dont known.
Yesterday, I posted 3 reports in the Java Bug Database and I haven't no feedback at this moment.

**Comment by TheShermanTanker** [comment]
> @TheShermanTanker , thank you for asking and helping.
> 
> > it seems that others already have it covered
> 
> In fact, I dont known. Yesterday, I posted 3 reports in the Java Bug Database and I have no feedback at this moment.

Well, in that case, wait no longer!
Your issue ID is [8289741](https://bugs.openjdk.org/browse/JDK-8289741), just change your title to "8289741" and the automated tooling should take care of the rest and send this PR to the appropriate teams for review.

All the best!

**Comment by scientificware** [comment]
@TheShermanTanker Thanks.

**Comment by scientificware** [comment]
Just waiting to be reviewed.

**Comment by jaikiran** [comment]
Hello @scientificware, what you propose here, I think looks fine. Additionally can you also update the copyright years on this file from `Copyright (c) 1998, 2020,` to `Copyright (c) 1998, 2022,`?

I see that the changed file resides at `make/jdk/src/classes/build/tools/dtdbuilder/DTDBuilder.java` and I think this needs to be reviewed by the build team. @magicus, is it OK if I re-add the `build` label for this PR?

**Comment by scientificware** [comment]
@jaikiran The copyright years were updated by a previous commit.

**Comment by jaikiran** [comment]
You are right, the copyright year on the file is fine - I was looking at an older version of this file.

**Comment by magicus** [comment]
@jaikiran The build tools are not really part of the build system as such. I used to push for a solution to move them to their corresponding modules, but this met with resistance and did not really go anywhere.

In general, though, the build tools needs to be reviewed by the group "owning" them. In some cases, the change affects how the build tool interacts with the rest of the build system. If that is the case, the build label is relevant.

Unfortunately, the Skara label rules are a bit too coarse to capture this reality.

**Comment by jaikiran** [comment]
Thank you Magnus.

Given the nature of this change, adding myself as the reviewer and approving this change.

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
@scientificware, please issue the integrate command when you are ready and I can sponsor this for you. In the meantime, I'll run some tests to be sure that this change is fine.

**Comment by scientificware** [comment]
@jaikiran, Done and thanks for your sponsoring and reviewing.

**Comment by jaikiran** [comment]
The tests came back fine without any issue.

**Pull request closed without merging**
