### PR TITLE
8326446: The User and System of jdk.CPULoad on Apple M1 are inaccurate

### PR DESCRIPTION
**Pull request by yanglong1010**
hi

I would like to fix this.

As the description in [JDK-8326446](https://bugs.openjdk.org/browse/JDK-8326446).
JFR uses task_info() with flavor TASK_ABSOLUTETIME_INFO to read User and System time. it is not reliable on Apple m1.

Libc provides the [times](https://man7.org/linux/man-pages/man2/times.2.html) function, which uses TASK_BASIC_INFO_COUNT and TASK_THREAD_TIMES_INFO_COUNT. It will also return the real time of the process, and the time unit is the same, which is suitable for solving this problem.

I ran test/jdk/jdk/jfr/event/os/TestCPULoad.java and passed.

I would appreciate it if you could review this.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326446](https://bugs.openjdk.org/browse/JDK-8326446): The User and System of jdk.CPULoad on Apple M1 are inaccurate (**Bug** - P3)

### Reviewers
 * [Markus Grönlund](https://openjdk.org/census#mgronlun) (@mgronlun - **Reviewer**)
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17976/head:pull/17976` \
`$ git checkout pull/17976`

Update a local copy of the PR: \
`$ git checkout pull/17976` \
`$ git pull https://git.openjdk.org/jdk.git pull/17976/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17976`

View PR using the GUI difftool: \
`$ git pr show -t 17976`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17976.diff">https://git.openjdk.org/jdk/pull/17976.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17976#issuecomment-1960873600)

### CODE REVIEW

**Comment by mgronlun** [comment]
Seems reasonable.

Is there a risk of introducing a regression for existing platforms? Did the result on x64 turn out equivalent to pre-change?

**Comment by mgronlun** [comment]
The units are changed from nanos to ticks, but this is opaque because doubles are used to represent only the ratios?

**Comment by yanglong1010** [comment]
> The units are changed from nanos to ticks, but this is opaque because doubles are used to represent only the ratios?

Yes

**Comment by yanglong1010** [comment]
> Seems reasonable.
> 
> Is there a risk of introducing a regression for existing platforms? Did the result on x64 turn out equivalent to pre-change?

I ran the pre- and post-change versions on MacOS X64, and I can see that the results are consistent.
```
OS Information

Time     OS Version
-------- --------------------------------------------------------------------------------------------------------------
22:28:13 uname: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5...

CPU Information

Time     Type                                    Description                             Sockets Cores Hardware Threads
-------- --------------------------------------- --------------------------------------- ------- ----- ----------------
22:28:13 Intel Haswell (HT) SSE SSE2 SSE3 SSS... Brand: Intel(R) Core(TM) i7-4770HQ C...       1     4                8

                                     CPU Load (pre fix, I ran the changed version first, so the time is newer)

Time                         JVM User           JVM System           Machine Total
------------------ ------------------ -------------------- -----------------------
22:28:15                       10.41%               39.19%                  76.21%
22:28:16                       10.31%               39.46%                  70.88%
22:28:17                       10.30%               39.46%                  68.58%
22:28:18                       10.30%               39.47%                  67.96%

                                     CPU Load (post fix)

Time                         JVM User           JVM System           Machine Total
------------------ ------------------ -------------------- -----------------------
22:25:58                       10.40%               38.99%                  82.34%
22:25:59                       10.37%               39.50%                  82.15%
22:26:00                       10.27%               39.23%                  68.65%
22:26:01                       10.37%               39.63%                  68.25%
```

**Comment by yanglong1010** [comment]
@mgronlun Thanks for your review. Does this patch need a second review ?

**Comment by mgronlun** [comment]
I think it needs a second review. Also, I am not very versed in Mac internals.

**Comment by yanglong1010** [comment]
> I think it needs a second review. Also, I am not very versed in Mac internals.

Thanks. Would you help me to invite the second reviewer?

**Comment by yanglong1010** [comment]
@egahlin Could I have a second review of this backport.

**Comment by egahlin** [comment]
> @egahlin Could I have a second review of this patch.

Looks reasonable, but why was this removed:

`if(!now_in_nanos(&total_cpu_nanos)) {
    return OS_ERR;
  }`

**Comment by yanglong1010** [comment]
Because the [times](https://man7.org/linux/man-pages/man2/times.2.html) libc api returns the real time of the process. So we don't need to calculate the `total_cpu_nanos`, just use the return value of `times`.

```
struct tms buf;
clock_t jvm_real = times(&buf);
if (jvm_real == (clock_t) (-1)) {
  return OS_ERR;
}

...

uint64_t delta = active_processor_count * (jvm_real - _jvm_real);
```

**Comment by egahlin** [comment]
> Because the [times](https://man7.org/linux/man-pages/man2/times.2.html) libc api returns the real time of the process.

OK, I had a vague memory about some other issue, but I don't remember and it probably doesn't apply.

**Review by egahlin — APPROVED** [review]

**Pull request closed without merging**
