### PR TITLE
8024624: [TEST_BUG] [macosx] CTRL+RIGHT(LEFT) doesn't move selection on next cell in JTable on Aqua L&F

### PR DESCRIPTION
**Pull request by DamonGuy**
Aqua L&F tables lacked support for `CTRL+ARROW`, `CTRL+PG_UP/DOWN`, and `CTRL+SHIFT+PG_UP/DOWN` key bindings. This allows for navigation and selection of table cells without the need of a mouse and without deselecting the current selected cell group. 

Those key bindings are added to Aqua's key bindings for tables. The `SPACE` key binding was also added because it allows for the selection of cells after navigating using the `CTRL+ARROW` bindings, and some of the new bindings are only useful with the `SPACE` binding added. The closed test that this bug originates from tests for both left-to-right and right-to-left functionality, so the new directional bindings are also added to the right-to-left key bindings table where needed.

This requires mission control shortcuts in macOS to be disabled as `CTRL+ARROW` keys are normally used for virtual desktop navigation.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8024624](https://bugs.openjdk.java.net/browse/JDK-8024624): [TEST_BUG] [macosx] CTRL+RIGHT(LEFT) doesn't move selection on next cell in JTable on Aqua L&F

### Reviewers
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**) ⚠️ Review applies to e5ce124e6bb5843f1ba818907c441a00014870fa
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7792/head:pull/7792` \
`$ git checkout pull/7792`

Update a local copy of the PR: \
`$ git checkout pull/7792` \
`$ git pull https://git.openjdk.java.net/jdk pull/7792/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7792`

View PR using the GUI difftool: \
`$ git pr show -t 7792`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7792.diff">https://git.openjdk.java.net/jdk/pull/7792.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
What shortcuts are used by the native macOS applications for such navigation? Aqua should align bihaviour to the native app and not other cross platform L&F or windows/linux.

**Comment by DamonGuy** [comment]
> What shortcuts are used by the native macOS applications for such navigation? Aqua should align bihaviour to the native app and not other cross platform L&F or windows/linux.

The only shortcuts that allow for non-adjacent cell selection on tables is `COMMAND+LEFT_CLICK`. This requires the use of a mouse on top of keyboard inputs.

Apple Pages has no support at all for these table navigation functions other than `COMMAND+LEFT_CLICK`. Excel has a selection mode that can be toggled on/off using SHIFT+F8. I also tested in macOS's `System Preferences > Keyboard > Text` and `CMD+CLICK` is the only supported way to select non-adjacent cells as well.

The two paths to fixing this issue was either adding the shortcuts and functionality to Aqua L&F tables or to make the test exclude macOS. The benefit of adding the shortcuts to Aqua allows for users to navigate without the need for a mouse or touchpad. The Oracle doc for tables [here](https://docs.oracle.com/javase/tutorial/uiswing/components/table.html) shows that `CTRL+ARROW` is a supported keyboard action as an alternative for `CTRL+CLICK`, and has no mention of excluding macOS or Aqua L&F. 

So, I thought it is appropriate to add the shortcuts to Aqua, but I can make changes if needed.

**Review by azuev-java — APPROVED** [review]

**Comment by DamonGuy** [comment]
> _Mailing list message from [Miguel Munoz](mailto:swingguy1024@yahoo.com) on [client-libs-dev](mailto:client-libs-dev@mail.openjdk.java.net):_
> 
> On the MacOS, it's the OPTION-CLICK event, not the COMMAND-CLICK event that does the same thing as CONTROL-CLICK on Windows and other platforms. Every platform has modifier key used to advance the cursor by words instead of characters, but the modifiers are different on the Mac.
> 
> To see this working correctly, try an app running under JDK 8, which was the last one they worked under. (Actually, I haven't tried 9 or 10) Or you can try any non-java application. This is a standard user interface convention, and Java should continue to support it like it did through Java -8.
> 
> ? Miguel Mu?oz On Tuesday, March 15, 2022, 06:53:19 PM PDT, Sergey Bylokhov <serb at openjdk.java.net> wrote:
> 
> On Sat, 12 Mar 2022 01:27:34 GMT, DamonGuy <duke at openjdk.java.net> wrote:
> 
> > Apple Pages has no support at all for these table navigation functions other than `COMMAND+LEFT_CLICK`. Excel has a selection mode that can be toggled on/off using SHIFT+F8. I also tested in macOS's `System Preferences > Keyboard > Text` and `CMD+CLICK` is the only supported way to select non-adjacent cells as well.
> 
> Since for any reason the macOS does not supported such navigation in the tables and use it by mission control it seems correct to do the same in the native look and feel, and ignore the test.
> 
> -------------
> 
> PR: https://git.openjdk.java.net/jdk/pull/7792

I tested again on native macOS tables, and CMD+CLICK seems to be the functioning modifier+key combination for selecting multiple non-adjacent cells. I also found [this](https://support.apple.com/guide/pages/select-tables-cells-rows-and-columns-tan661e2f40a/mac) information under `cells` and `rows and columns` that shows the same key bindings. I could change the bindings, but that would change Aqua L&F to be further from native macOS behavior.

**Comment by mrserb** [comment]
> I see your point. I will update the closed repo changes to exclude macOS from testing to avoid any issues it may cause. Should a separate issue be raised to update [this](https://docs.oracle.com/javase/tutorial/uiswing/components/table.html) doc to mention that macOS isn't included for these key bindings?

As far as I know that doc cannot be updated, see the header of that page.

**Comment by DamonGuy** [comment]
I have removed the additional key bindings. Instead, I excluded macOS from the test. I also converted the closed test to be appropriate for open repo use. I removed the reliance on deprecated and closed-exclusive libraries, like JRobot and SwingTestHelper. I also re-organized the test methods since SwingTestHelper's method naming convention does not need to be adhered to.

**Review by prrace — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Comment by mrserb** [comment]
BTW why this PR is in the draft state?

**Comment by DamonGuy** [comment]
> BTW why this PR is in the draft state?

This PR was in draft while I was learning about the correct process to convert a test. I just made the branch ready for review again, thanks!

**Pull request closed without merging**
