### PR TITLE
8336844: ZipConstants64 defines duplicate constants EXTID_ZIP64 and ZIP64_EXTID

### PR DESCRIPTION
**Pull request by cushon**
This change deduplicates constants in ZipConstants64 for the Zip64 Extended Information Extra Field Header ID (see APPNOTE.TXT 4.5.3).

I think there are arguments for consolidating on either `EXTID_ZIP64` or `ZIP64_EXTID`. The PR currently consolidates on `EXTID_ZIP64`, `ZIP64_EXTID` is also an option if there's a preference for that.

I noticed this while working on a zip64 bug in [JDK-8328995](https://bugs.openjdk.org/browse/JDK-8328995), I was reviewing places that handled zip64 extra fields and initially missed some because I was only looking at one of the constants.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336844](https://bugs.openjdk.org/browse/JDK-8336844): ZipConstants64 defines duplicate constants EXTID_ZIP64 and ZIP64_EXTID (**Enhancement** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Vyom Tewari](https://openjdk.org/census#vtewari) (@vyommani - Committer)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20264/head:pull/20264` \
`$ git checkout pull/20264`

Update a local copy of the PR: \
`$ git checkout pull/20264` \
`$ git pull https://git.openjdk.org/jdk.git pull/20264/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20264`

View PR using the GUI difftool: \
`$ git pr show -t 20264`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20264.diff">https://git.openjdk.org/jdk/pull/20264.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20264#issuecomment-2240004687)

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Liam, the changes look fine to me. Choosing `EXTID_ZIP64` constant in preference of the other seems OK too, since that constant is more closer in code location with the other extra field header ids.

Some of these files require a copyright year update. Please update those before integrating.

**Comment by cushon** [comment]
I updated the copyright dates. Thanks for the review!

**Review by jaikiran — APPROVED** [review]
The changes look good to me. Although a trivial change, it would be good to wait for Lance to review this before integrating.

**Review by vyommani — APPROVED** [review]
Looks OK to me.

**Review by LanceAndersen — APPROVED** [review]
The change looks fine.

**Pull request closed without merging**
