### PR TITLE
8280932: G1: Rename HeapRegionRemSet::_code_roots accessors

### PR DESCRIPTION
**Pull request by albertnetymk**
Mostly mechanical changes of renaming some methods/comments.

Test: build

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280932](https://bugs.openjdk.java.net/browse/JDK-8280932): G1: Rename HeapRegionRemSet::_code_roots accessors

### Reviewers
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to 6a226cdaf9588c17380eac907a25bdf523a7f345

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7285/head:pull/7285` \
`$ git checkout pull/7285`

Update a local copy of the PR: \
`$ git checkout pull/7285` \
`$ git pull https://git.openjdk.java.net/jdk pull/7285/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7285`

View PR using the GUI difftool: \
`$ git pr show -t 7285`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7285.diff">https://git.openjdk.java.net/jdk/pull/7285.diff</a>

</details>

### CODE REVIEW

**Comment by tschatzl** [comment]
Some more candidates for renaming:

```
void G1CollectedHeap::rebuild_strong_code_roots() {
  RebuildStrongCodeRootClosure blob_cl(this);
  CodeCache::blobs_do(&blob_cl);
}
```

Please also look after "strong code root" in comments (mostly related to this method). Also e.g. in g1RemSetSummary.cpp:236/303 though.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Review by tschatzl — CHANGES_REQUESTED** [review]
See the earlier comment from me.

**Review by tschatzl — COMMENTED** [review]
Lgtm. Thanks.

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
