### PR TITLE
8277946: NMT: Deprecate and remove VM.native_memory shutdown jcmd command option

### PR DESCRIPTION
**Pull request by zhengyu123**
NMT shutdown functionality is a remnant of its first implementation, which could consume excessive amount of memory, therefore, it needed capability to shut it self down to ensure health of JVM. This is no longer a case for new implementation.

NMT shutdown can be requested via Jcmd. However, it is rare used.

We should deprecate for shutdown Jcmd command for removing NMT shutdown functionality.

Corresponding [CSR](https://bugs.openjdk.java.net/browse/JDK-8277947) has been approved.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8277946](https://bugs.openjdk.java.net/browse/JDK-8277946): NMT: Deprecate and remove VM.native_memory shutdown jcmd command option
 * [JDK-8277947](https://bugs.openjdk.java.net/browse/JDK-8277947): NMT: Deprecate and remove VM.native_memory shutdown jcmd command option (**CSR**) ⚠️ Issue is not open.

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6618/head:pull/6618` \
`$ git checkout pull/6618`

Update a local copy of the PR: \
`$ git checkout pull/6618` \
`$ git pull https://git.openjdk.java.net/jdk pull/6618/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6618`

View PR using the GUI difftool: \
`$ git pr show -t 6618`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6618.diff">https://git.openjdk.java.net/jdk/pull/6618.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Nice. Looks good. But that just removes the jcmd; I assume you remove the shutdown-on-OOM functionality, together with shutdown mechanics itself, in a separate RFE?

**Comment by zhengyu123** [comment]
> Nice. Looks good. But that just removes the jcmd; I assume you remove the shutdown-on-OOM functionality, together with shutdown mechanics itself, in a separate RFE?

Thanks for the review, @tstuefe 

Yes, I filed JDK-8277990 to remove the rest.

**Review by shipilev — APPROVED** [review]
Looks fine. I wonder: was `NMT_minimal` the state after "shutdown"? If so, should it be removed too? (in separate PR, probably)

**Comment by zhengyu123** [comment]
> Looks fine. I wonder: was `NMT_minimal` the state after "shutdown"? If so, should it be removed too? (in separate PR, probably)

hn

> Looks fine. I wonder: was `NMT_minimal` the state after "shutdown"? If so, should it be removed too? (in separate PR, probably)

Thanks for the review, @shipilev 

Yes, NMT_minimal will be removed in followup CR 8277990.

**Review by dholmes-ora — APPROVED** [review]
Hi Zhengyu,

I am fine with removal of the shutdown option of the jcmd as presented, but as per the CSR request I think "Deprecate" has to be removed from this as nothing has been deprecated.

I'm not at all clear why the actual shutdown mechanics removal has been deferred to another issue - that would make sense if this PR actually just deprecated something, but as it is I would have expected everything to go. With RDP1 upon us I assume the actual removal will now be in 19.

Thanks,
David

**Comment by zhengyu123** [comment]
> Hi Zhengyu,
> 
> I am fine with removal of the shutdown option of the jcmd as presented, but as per the CSR request I think "Deprecate" has to be removed from this as nothing has been deprecated.
> 
> I'm not at all clear why the actual shutdown mechanics removal has been deferred to another issue - that would make sense if this PR actually just deprecated something, but as it is I would have expected everything to go. With RDP1 upon us I assume the actual removal will now be in 19.
> 
> Thanks, David

Hi David,

Thanks for the review. I were not sure I should remove shutdown mechanics with this CR, as it only mentions jcmd part and there is auto-shutdown part also. 

I already have the second change ready, will PR tomorrow, it is quite large through.

-Zhengyu

**Pull request closed without merging**
