### PR TITLE
8338583: NMT: Malloc overhead is calculated incorrectly

### PR DESCRIPTION
**Pull request by kirleo2**
Malloc overhead because of using NMT equals 18 bytes (size of MallocHeader (16 bytes) + footer canary (2 bytes)). Current approach of total malloc overhead calculation takes into account only header size, but not footer canary, as a result leading to incorrect value of reported tracking overhead.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338583](https://bugs.openjdk.org/browse/JDK-8338583): NMT: Malloc overhead is calculated incorrectly (**Bug** - P3)

### Reviewers
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - Committer) Review applies to [0c1466f7](https://git.openjdk.org/jdk/pull/20625/files/0c1466f7f17217384bd0492bf72cd4b4d9396977)
 * [Afshin Zafari](https://openjdk.org/census#azafari) (@afshin-zafari - Committer)
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20625/head:pull/20625` \
`$ git checkout pull/20625`

Update a local copy of the PR: \
`$ git checkout pull/20625` \
`$ git pull https://git.openjdk.org/jdk.git pull/20625/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20625`

View PR using the GUI difftool: \
`$ git pr show -t 20625`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20625.diff">https://git.openjdk.org/jdk/pull/20625.diff</a>

</details>

### CODE REVIEW

**Comment by kirleo2** [comment]
Hello, Team! Regarding the OCA, I am Azul employee

**Comment by robilad** [comment]
Hi, Please send me an e-mail at dalibor.topic@oracle.com so that I can take the next steps to mark your account as verified in Skara.

**Review by gerard-ziemski — APPROVED** [review]
Looks good to me, thank you for fixing this.

Can't believe we missed it.

**Comment by afshin-zafari** [comment]
Thank you for the fix.
Please update the copyright year for `nmtMemTracker.hpp`, thanks.

**Comment by kirleo2** [comment]
@afshin-zafari This is already done in another patch.

**Comment by afshin-zafari** [comment]
> @afshin-zafari This is already done in another patch.

Yes, saw it now.
Good, thanks.

**Review by afshin-zafari — APPROVED** [review]
LGTM. Thanks.

**Review by yan-too — APPROVED** [review]

**Pull request closed without merging**
