### PR TITLE
8297951: C2: Create skeleton predicates for all If nodes in loop predication

### PR DESCRIPTION
**Pull request by chhagedorn**
We currently only create skeleton predicates for `RangeCheck` nodes and not for normal `If` nodes:
https://github.com/openjdk/jdk/blob/2cb64a75578ccc15a1dfc8c2843aa11d05ca8aa7/src/hotspot/share/opto/loopPredicate.cpp#L1344-L1346

But it is also possible to create range check predicates in loop predication for `If` nodes if they have the right pattern checked in `PhaseIdealLoop::loop_predication_impl()` and `IdealLoopTree::is_range_check_if()`. This, however, is much more rare.

Without skeleton predicates for these `If` nodes, we could run into the same problems already fixed for `RangeCheck` nodes (see [JDK-8193130](https://bugs.openjdk.org/browse/JDK-8193130) and related bugs). This is almost impossible to trigger in practice as it needs a very specific setup and the right optimizations to be applied. But the test case shows such a case where we hit an assert due to a broken memory graph because we are missing skeleton predicates.

I therefore propose to always create skeleton predicates for hoisted range checks in loop predication.

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297951](https://bugs.openjdk.org/browse/JDK-8297951): C2: Create skeleton predicates for all If nodes in loop predication

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11454/head:pull/11454` \
`$ git checkout pull/11454`

Update a local copy of the PR: \
`$ git checkout pull/11454` \
`$ git pull https://git.openjdk.org/jdk pull/11454/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11454`

View PR using the GUI difftool: \
`$ git pr show -t 11454`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11454.diff">https://git.openjdk.org/jdk/pull/11454.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me. Great that you were able to find a test!

**Comment by chhagedorn** [comment]
Thanks Tobias for your review!

**Review by vnkozlov — APPROVED** [review]
Make sense.

**Comment by chhagedorn** [comment]
Thank you Vladimir for your review!

**Pull request closed without merging**
