### PR TITLE
8282507: Add a separate license file for hsdis

### PR DESCRIPTION
**Pull request by caoman**
Hi all,

Could anyone help review the addition of LICENSE file to hsdis directory?

-Man

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282507](https://bugs.openjdk.java.net/browse/JDK-8282507): Add a separate license file for hsdis

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7649/head:pull/7649` \
`$ git checkout pull/7649`

Update a local copy of the PR: \
`$ git checkout pull/7649` \
`$ git pull https://git.openjdk.java.net/jdk pull/7649/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7649`

View PR using the GUI difftool: \
`$ git pr show -t 7649`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7649.diff">https://git.openjdk.java.net/jdk/pull/7649.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
I'm not sure what the legal implications are of adding a separate general file like this, instead of marking each individual file. I'd need to get some confirmation that this is acceptable.

**Comment by caoman** [comment]
Thank you for reaching out for confirmation. This doc might help: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository . A separate LICENSE file is also more consistent with other code in OpenJDK.

**Comment by caoman** [comment]
Any updates on whether this is acceptable?

**Comment by theRealAph** [comment]
> Any updates on whether this is acceptable?

What is the point of this change? It'd require legal inspection, and as far as I can tell there is no point.

**Comment by magicus** [comment]
@caoman No, I have not gotten any replies. I also fully agree with @theRealAph, that this change seem like a huge waste of time chasing legal approval, for what gain? The license for these few special files are already clearly specified in them.

**Comment by caoman** [comment]
The context is that Google have an automated check for license compliance for all imported open-source software. We (Java platform team) have to maintain a script that finds and copies all licenses within OpenJDK codebase, in order to pass the license compliance check. All other licenses within the OpenJDK codebase are already in their own files that contain only the license information. We have two options:
- Add special-handling code to the script we maintain, so it can extract the license information from hsdis's README.md file and copy it.
- Provide a separate file for hsdis that contains only the license in OpenJDK.

The second approach is more appealing to us, as it reduces our script's complexity and maintenance burden, and makes hsdis's license structure consistent with other licenses in OpenJDK.

If getting the legal approval requires too much overhead, we could use the first approach to implement the logic in our script instead.

**Comment by magicus** [comment]
When you say your change "makes hsdis's license structure consistent with other licenses in OpenJDK", what do you mean by that? 

If we had random LICENSE files lying around I'd agree that we should do the same here, but that is clearly not the case. There's a top-level LICENSE file. And there are markdown files in share/legal for licenses of included 3rd party code. Can you clarify how this change would improve consistency?

From my PoV, this is just another case of how parts of the code use GPL, and parts use GPL+classpath exception. There are no "LICENSE" file specific to Hotspot saying it has a different license in general to e.g. java.base.

**Comment by caoman** [comment]
The consistency is to have the license information in its own file, like other 3rd party code in OpenJDK. There two ways:
- Add a LICENSE file or a similar text file. There is src/java.desktop/share/native/libsplashscreen/libpng/LICENSE and make/data/cldr/unicode-license.txt.
- Add markdown files in share/legal subdirectory. Many examples exist such as src/java.xml/share/legal/. This approach seems mainly used for source code in Java.

Do you think it is better to follow the "share/legal" approach such as adding a file src/utils/hsdis/share/legal/hsdis.md ?

**Comment by magicus** [comment]
But those are licenses for 3rd party code which we have incorporated.

hsdis is written by us. We have just chosen a different license to distribute it under. That makes comparisons with libpng and cldr irrelevant.

src/java.desktop/share/native/libsplashscreen/libpng/LICENSE seems like a mistake. There should be a libpng.md file in java.desktop/share/legal instead.

I think the comparison you need to do is how e.g. src/java.base and src/hotspot are licensed differently.

**Comment by caoman** [comment]
Thank you for pointing out the difference between hsdis and other 3rd party code.

> src/java.desktop/share/native/libsplashscreen/libpng/LICENSE seems like a mistake. There should be a libpng.md file in java.desktop/share/legal instead.

Yes, src/java.desktop/share/legal/libpng.md already exists and contains the same content.

Is hsdis the only part of code in OpenJDK that is written by the OpenJDK community, but not licensed under GPLv2+Classpath Exception? If so, we cannot say which way is consistent.

I do think a separate license file for hsdis is better, as the top-level LICENSE file does not mention the UPLv1 license, and it doesn't apply to hsdis. Having a separate license file is also a common approach for open source software.

What do you think? Again if it takes a lot of your time to get legal approval for this, then it is probably not worth it. Or could we rename the file to something like hsdis-license.txt so it doesn't need legal review?

**Comment by magicus** [comment]
As an engineer and not a lawyer, these are definitely muddy waters to me. I'm trying to get an understanding of the process, but I'm not used to navigating those parts of the organization. But from what I've found out so far, it do seem that if you insist on going through with this, we'd need to get legal approval. Which would be a ton of hassle for me. :( So I implore you to reconsider this PR.

And no, hsdis is not the only part of OpenJDK with another license than GPL+CE. The entire hotspot code base, and all tests, are licensed under GPL. But afaic the GPL, GPL+CE and UPL covers all code that is created by the OpenJDK project. This is not a legal guarantee, though, it's just my current understanding of the situation.

And thank you for pointing out src/java.desktop/share/native/libsplashscreen/libpng/LICENSE. I'll bring it up with our resident 3rd party license expert. :-)

**Comment by magicus** [comment]
With all that said, if you were to rename the file hsdis-license.txt, I would not have any objection. My sole concern here is that the name "LICENSE" sounds so broad that a lawyer, in the way that lawyers sometime do :), might be able to misinterpret this as applying to anything else than hsdis. With a clearer name, that worry disappears. So if you can accept that name instead, I don't have any more objections. The factual licensing of hsdis under UPL is not in dispute.

**Comment by caoman** [comment]
Thank you for helping navigate through this situation! I surely do not want to drag you into the complex legal approval process. Also same here, as an engineer and not a lawyer, my comments are only based on my observations and understandings, and have no legal guarantee.

Renaming to "hsdis-license.txt" works perfectly fine for our script and tool. I renamed the file and updated RFE and PR. Let me know if we can submit this. If you still need to go through legal approval, then I'll abandon this PR.

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
