### PR TITLE
8256664: Shenandoah: Cleanup after JDK-8212879

### PR DESCRIPTION
**Pull request by zhengyu123**
JDK-8212879 removed last serial weak roots, that means:

1) Concurrent GC no longer needs to cleanup any weak roots at pause
2) Root verifier no longer needs to distinguish concurrent/serial weak roots.

Test:
- [x] hotspot_gc_shenandoah

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ❌ (1/9 failed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test task**
- [Linux x64 (hs/tier1 runtime)](https://github.com/zhengyu123/jdk/runs/1428124297)

### Issue
 * [JDK-8256664](https://bugs.openjdk.java.net/browse/JDK-8256664): Shenandoah: Cleanup after JDK-8212879

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1336/head:pull/1336`
`$ git checkout pull/1336`

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good to me! Thank you!

**Comment by rkennke** [comment]
There is one failure in tier1/linux/x86_64, make sure this is not caused by this change!

**Comment by shipilev** [comment]
> There is one failure in tier1/linux/x86_64, make sure this is not caused by this change!

It seems to be https://bugs.openjdk.java.net/browse/JDK-8256641, and it manifests across many runs today.

**Comment by zhengyu123** [comment]
> Looks good to me! Thank you!

Thanks.

**Comment by zhengyu123** [comment]
> > There is one failure in tier1/linux/x86_64, make sure this is not caused by this change!
> 
> It seems to be https://bugs.openjdk.java.net/browse/JDK-8256641, and it manifests across many runs today.

Yes, it is not related to this change.

**Pull request closed without merging**
