### PR TITLE
8345039: IGV: save user-defined node colors to XML

### PR DESCRIPTION
**Pull request by tobiasholenstein**
This PR depends on https://github.com/openjdk/jdk/pull/22402 

[JDK-8343535](https://bugs.openjdk.org/browse/JDK-8343535) introduced the possibility to give user-defined colors to a node.
The colors are lost when the user goes to the next graph or when IGV is closed. Save the colors as a property of the graph to the XML to make it more permanent. This requires that the user can also remove the colors again.

color

### Whats new
- Now colors are saved with the XML as well
- Colors are kept when changing to a different graph
- The user can remove the color again: This uses the color from the filter or WHITE otherwise

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345039](https://bugs.openjdk.org/browse/JDK-8345039): IGV: save user-defined node colors to XML (**Enhancement** - P4)

### Reviewers
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**) Review applies to [f0de94b7](https://git.openjdk.org/jdk/pull/22440/files/f0de94b71e773284b31da174fa6952a8e564c80b)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**) Review applies to [e58c6171](https://git.openjdk.org/jdk/pull/22440/files/e58c617152ad931cb75d6bc8ab257f98118214ea)

### Contributors
 * Roberto Castañeda Lozano `<rcastanedalo@openjdk.org>`
 * Christian Hagedorn `<chagedorn@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22440/head:pull/22440` \
`$ git checkout pull/22440`

Update a local copy of the PR: \
`$ git checkout pull/22440` \
`$ git pull https://git.openjdk.org/jdk.git pull/22440/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22440`

View PR using the GUI difftool: \
`$ git pr show -t 22440`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22440.diff">https://git.openjdk.org/jdk/pull/22440.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22440#issuecomment-2506352748)
</details>

### CODE REVIEW

**Comment by chhagedorn** [comment]
Nice! I quickly tried it out on Linux and found two things:

- The color is not kept when going to another graph.
- The "No Color" button looks like this (but it's working when clicking on "No...":
image

**Comment by robcasloz** [comment]
> * The color is not kept when going to another graph.

Hi Christian, can you try [this change](https://github.com/openjdk/jdk/commit/62cc2351ef0cdeaf48bbc0ef5c82501219b9c7c9) and see if it works for you?

**Comment by robcasloz** [comment]
> So, the only minor problem left is the "No..." that does not look like a button and therefore is not suggesting to click it. Maybe you find a fix for that. If not, I guess it's okay to move forward with this patch and come back to it later again.

This small adjustment should address that part: https://github.com/openjdk/jdk/commit/a5f6562f86481316ae36fc629bb9d5efae7f3e2f. Could you please try it out?

**Comment by robcasloz** [comment]
> > So, the only minor problem left is the "No..." that does not look like a button and therefore is not suggesting to click it. Maybe you find a fix for that. If not, I guess it's okay to move forward with this patch and come back to it later again.
> 
> This small adjustment should address that part: [a5f6562](https://github.com/openjdk/jdk/commit/a5f6562f86481316ae36fc629bb9d5efae7f3e2f). Could you please try it out?

Here's a revised version of the adjustment that also makes the button look clickable (thanks to @chhagedorn  for trying out and adjusting the button settings to prevent label truncation and ugly button focus shape): https://github.com/openjdk/jdk/commit/aba8d3e253cc2fd7c33d0d00ea9f014fdaa37e3d. @tobiasholenstein feel free to incorporate and edit to your liking.

**Review by chhagedorn — APPROVED** [review]
Thanks for the update, it works now as expected! :-)

**Review by robcasloz — APPROVED** [review]
Looks good, making custom colors persistent really improves the usability of this feature!

**Review by robcasloz — APPROVED** [review]
I re-tested this change after merging the latest changes from https://github.com/openjdk/jdk/pull/22402 and did not find any issue.

**Review by chhagedorn — APPROVED** [review]
This is a nice enhancement! As discussed offline, we could follow up with RFEs (if wanted) to handle:
- Save colors added in the diff view when having graph "X vs. X + 4" opened and going to the next graph, e.g. "X vs X + 3". It currently drops the color.
- When cloning a graph, making the coloring local and not globally per XML. Now when you color a node in one of the graphs, it will be applied to the original and the cloned graph.

**Comment by tobiasholenstein** [comment]
thanks @chhagedorn , @robcasloz and @eme64 for the reviews!

**Pull request closed without merging**
