### PR TITLE
8276672: Cannot build hsdis on WSL

### PR DESCRIPTION
**Pull request by YaSuenag**
JDK-8275128 introduced new Makefile for hsdis to integrate it to normal build system, however it does not work on WSL 1 Ubuntu 20.04 and MinGW from Ubuntu.

Hsdis.gmk has two problems:

1. MinGW version is fixed to "9.2.0"
2. Assumes sysroot for MinGW is located at /usr/$MINGW_BASE/sys-root

I tested this change on WSL only, so it is appreciate to review on Cygwin.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276672](https://bugs.openjdk.java.net/browse/JDK-8276672): Cannot build hsdis on WSL

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Contributors
 * Magnus Ihse Bursie `<ihse@openjdk.org>`
 * Yasumasa Suenaga `<ysuenaga@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6269/head:pull/6269` \
`$ git checkout pull/6269`

Update a local copy of the PR: \
`$ git checkout pull/6269` \
`$ git pull https://git.openjdk.java.net/jdk pull/6269/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6269`

View PR using the GUI difftool: \
`$ git pr show -t 6269`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6269.diff">https://git.openjdk.java.net/jdk/pull/6269.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Hi @YaSuenag,

Thank you for your contribution. I'll have a closer look and try this out on Cygwin after the weekend.

**Comment by magicus** [comment]
Hi @YaSuenag,

Unfortunately this patch does not work out-of-the box on Cygwin, at least not on my machine. :-(

I found two issues:

1) The libraries are in $(MINGW_SYSROOT)/mingw/lib, not $(MINGW_SYSROOT)/lib. For `-L`, we can of course include both paths just to be safe rather than sorry, but that will not work for dllcrt2.o, so we need to verify which path works.

2) On the machine I'm testing, mingw 11.0.4 is installed, but MINGW_VERSION should need to be just 11. (It's worth noting that my original implementation would not have worked either, in this case.)

So here too I think we need to check both possibilities and verify them.

**Comment by magicus** [comment]
Also, there's no need to use eval to assign to variables. You can just use normal assignment :=.

I'll try to make this work for cygwin in a branch in my personal fork. I'll let you know when I'm done and then you can test if it works for you.

**Comment by magicus** [comment]
Please check out if https://github.com/magicus/jdk/tree/hsdis-on-wsl works OK in your environment. It does work for me on Cygwin.

**Comment by YaSuenag** [comment]
@magicus Thanks ! Your change works fine on my WSL, so I merged it to this PR (and also I added you as a contributor).

**Comment by YaSuenag** [comment]
I removed `SYSROOT_FLAGS` because it is no longer used.

**Review by magicus — APPROVED** [review]
Great! I missed the redundant `SYSROOT_FLAGS`, thanks for taking care of that.

**Review by erikj79 — APPROVED** [review]

**Pull request closed without merging**
