### PR TITLE
8316967: Correct the scope of vmtimer in UnregisteredClasses::load_class

### PR DESCRIPTION
**Pull request by calvinccheung**
Simple fix for removing the vmtimer from `UnregisteredClasses::load_class` and the corresponding `PerfClassTraceTime` constructor.

Passed tier1 testing.
--------------------
Update: correct the scope of the vmtimer instead of removing it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316967](https://bugs.openjdk.org/browse/JDK-8316967): Correct the scope of vmtimer in UnregisteredClasses::load_class (**Enhancement** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Jiangli Zhou](https://openjdk.org/census#jiangli) (@jianglizhou - **Reviewer**) ⚠️ Review applies to [321bde57](https://git.openjdk.org/jdk/pull/16046/files/321bde57b76074d6f3d4602e81c9158e85dd94ee)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16046/head:pull/16046` \
`$ git checkout pull/16046`

Update a local copy of the PR: \
`$ git checkout pull/16046` \
`$ git pull https://git.openjdk.org/jdk.git pull/16046/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16046`

View PR using the GUI difftool: \
`$ git pr show -t 16046`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16046.diff">https://git.openjdk.org/jdk/pull/16046.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16046#issuecomment-1747792601)

### CODE REVIEW

**Comment by dholmes-ora** [comment]
As it stands this timer doesn't measure anything, but presumably the intent was to measure the execution time of this method? So why not just fix the scope of the timer rather than removing it?

**Comment by calvinccheung** [comment]
> As it stands this timer doesn't measure anything, but presumably the intent was to measure the execution time of this method? So why not just fix the scope of the timer rather than removing it?

Based on the file history, the `unregisterClasses.cpp` was created for 826194 (Use ClassLoader for unregistered classes during -Xshare:dump). The `UnregisteredClasses::load_class` function was originally in `ClassLoaderExt::load_class` where it used the vmtimer to measure the following:
```
  {
    PerfClassTraceTime vmtimer(perf_sys_class_lookup_time(),
                               THREAD->get_thread_stat()->perf_timers_addr(),
                               PerfClassTraceTime::CLASS_LOAD);
    stream = e->open_stream(THREAD, file_name);
  }
```
After the fix for 8261914, the open_stream call is not needed and thus we left with the code in the current state.
I think it's reasonable to have the vmtimer to measure the entire `UnregisteredClasses::load_class`. This means the fix would just remove the braces around the constructor call.

**Review by dholmes-ora — COMMENTED** [review]
I have to wonder why the original code only timed the `open_stream` call? Is it because that is what `perf_sys_class_lookup_time` does versus `perf_sys_classload_time`? If so then removal may be better after all. Perhaps @iklam or @jianglizhou can recall this early AppCDS v2 code?

**Comment by jianglizhou** [comment]
> I have to wonder why the original code only timed the `open_stream` call? Is it because that is what `perf_sys_class_lookup_time` does versus `perf_sys_classload_time`? If so then removal may be better after all. Perhaps @iklam or @jianglizhou can recall this early AppCDS v2 code?

I paged in some of my memory on this. @iklam added the `ClassLoaderExt::load_class` specifically related change, so he probably can add additional background. I think the `perf_sys_class_lookup_time` part was simply based on how it was used in [ClassLoader::load_classfile](https://github.com/openjdk/jdk8u-dev/blob/27608e1e36154fcbedc627bc2afa965b1a06ebfb/hotspot/src/share/vm/classfile/classLoader.cpp#L1157C21-L1157C21).

**Comment by iklam** [comment]
In the non-CDS code, the `PerfClassTraceTime::CLASS_LOAD` event covers the call to `java.lang.ClassLoader::loadClass()`, so I think we should do that in `UnregisteredClasses::load_class()` as well.

https://github.com/openjdk/jdk/blob/33591a30d2e495b46877b76084aa2f52e5389246/src/hotspot/share/classfile/systemDictionary.cpp#L1294-L1319

I am trying to understand why I originally covered only the stream reading time but not the class parsing time. It was probably a bug :-)

https://github.com/openjdk/jdk/blob/4fd2a149977b05eb6e4b28d147ab9c043a7934ec/src/hotspot/share/classfile/classLoaderExt.cpp#L274-L295

**Review by iklam — APPROVED** [review]
LGTM

**Comment by jianglizhou** [comment]
> In the non-CDS code, the `PerfClassTraceTime::CLASS_LOAD` event covers the call to `java.lang.ClassLoader::loadClass()`, so I think we should do that in `UnregisteredClasses::load_class()` as well.
> 
> https://github.com/openjdk/jdk/blob/33591a30d2e495b46877b76084aa2f52e5389246/src/hotspot/share/classfile/systemDictionary.cpp#L1294-L1319
> 
> I am trying to understand why I originally covered only the stream reading time but not the class parsing time. It was probably a bug :-)
> 
> https://github.com/openjdk/jdk/blob/4fd2a149977b05eb6e4b28d147ab9c043a7934ec/src/hotspot/share/classfile/classLoaderExt.cpp#L274-L295

Changing the scope seems reasonable to me as well. Taking a close look of the current change after reading @iklam's comment above,  I think it might be reasonable to change the `ClassLoader::perf_sys_class_lookup_time` name. Unregistered class loader is for user defined classloader support (continue paging back my memory for this specifically :)). Using `sys` could be confusing.

**Review by jianglizhou — APPROVED** [review]

**Comment by calvinccheung** [comment]
> Changing the scope seems reasonable to me as well. Taking a close look of the current change after reading @iklam's comment above, I think it might be reasonable to change the `ClassLoader::perf_sys_class_lookup_time` name. Unregistered class loader is for user defined classloader support (continue paging back my memory for this specifically :)). Using `sys` could be confusing.

Thanks for the review and sorry for the delay in replying as I took a few days off.
How about changing `ClassLoader::perf_sys_class_lookup_time()` to `ClassLoader::perf_app_class_lookup_time()`?
Or simply using the existing `ClassLoader::perf_app_classload_time()`? (Which is being used in https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/systemDictionary.cpp#L1289-#L1299)

**Comment by jianglizhou** [comment]
> Thanks for the review and sorry for the delay in replying as I took a few days off.
> How about changing `ClassLoader::perf_sys_class_lookup_time()` to `ClassLoader::perf_app_class_lookup_time()`?
> Or simply using the existing `ClassLoader::perf_app_classload_time()`? (Which is being used in https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/systemDictionary.cpp#L1289-#L1299)

`ClassLoader::perf_app_classload_time` seems ok. If there is any interest in differentiating the class loading time for user defined classloader and archived cases, `perf_shared_unregistered_classload_time` might be more specific.

**Comment by iklam** [comment]
> > Thanks for the review and sorry for the delay in replying as I took a few days off.
> > How about changing `ClassLoader::perf_sys_class_lookup_time()` to `ClassLoader::perf_app_class_lookup_time()`?
> > Or simply using the existing `ClassLoader::perf_app_classload_time()`? (Which is being used in https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/systemDictionary.cpp#L1289-#L1299)
> 
> `ClassLoader::perf_app_classload_time` seems ok. If there is any interest in differentiating the class loading time for user defined classloader and archived cases, `perf_shared_unregistered_classload_time` might be more specific.

I think for simplicity, we can just use the existing `ClassLoader::perf_app_classload_time()`, which counts the time spent in loading classes that are not loaded by the boot loader.

`UnregisteredClasses::load_class()` is used only during `-Xshare:dump`, so I think this timer usually won't be looked at.

**Comment by calvinccheung** [comment]
@jianglizhou, @iklam I've pushed another commit for replacing the `perf_sys_class_lookup_time()` with the `perf_app_classload_time()`. Also removed the `perf_sys_class_lookup_time()` since it's no longer used. Please re-review.
Thanks!

**Comment by iklam** [comment]
Should these be removed as well?

```
./share/classfile/classLoader.cpp:PerfCounter*    ClassLoader::_perf_sys_class_lookup_time = nullptr;
./share/classfile/classLoader.cpp:    NEWPERFTICKCOUNTER(_perf_sys_class_lookup_time, SUN_CLS, "lookupSysClassTime");
./share/classfile/classLoader.hpp:  static PerfCounter* _perf_sys_class_lookup_time;
```

**Comment by calvinccheung** [comment]
> Should these be removed as well?
> 
> ```
> ./share/classfile/classLoader.cpp:PerfCounter*    ClassLoader::_perf_sys_class_lookup_time = nullptr;
> ./share/classfile/classLoader.cpp:    NEWPERFTICKCOUNTER(_perf_sys_class_lookup_time, SUN_CLS, "lookupSysClassTime");
> ./share/classfile/classLoader.hpp:  static PerfCounter* _perf_sys_class_lookup_time;
> ```

I've pushed another commit to remove those.
Re-running tier1 tests.

**Comment by calvinccheung** [comment]
@jianglizhou, @iklam Please re-review the latest version. Thanks!

**Review by iklam — APPROVED** [review]
The latest version looks good.

**Comment by jianglizhou** [comment]
LGTM, thank.

**Comment by calvinccheung** [comment]
Thanks @jianglizhou @iklam @dholmes-ora for the reviews.

/integrate

**Pull request closed without merging**
