### PR TITLE
8317048: VerifyError with unnamed pattern variable and more than one components

### PR DESCRIPTION
**Pull request by biboudis**
There were situations when javac optimizes switch structures (by merging the head of cases recursively) when two neighboring cases have a mix of named and unnamed patterns. This resulted translation is like the following:

From this:

```
  static <T1 extends Comparable, T2 extends Comparable> int compareTo(Tuple<R<T1>, R<T2>> o) {
        return switch (o) {
            case Tuple<R<T1>, R<T2>>(R1<T1> _, R1<T2> _) -> -1;
            case Tuple<R<T1>, R<T2>>(R1<T1> _, R2<T2> _) -> -1;
            case Tuple<R<T1>, R<T2>>(R2<T1> _, R1<T2> _) -> -1;
            case Tuple<R<T1>, R<T2>>(R2<T1> fst, R2<T2> snd) -> fst.value().compareTo(snd.value());
        };
    }
```

to code like this from the deeper nested switch (sample taken from `translateTopLevelClass`):

```
...
case 1:
   if (!(let snd = (T8317048.R2)selector10$temp; in true)) {
       index$11 = 2;
       continue;
   }
   yield .value().compareTo(snd.value()); // boom, fst is missing
   break;
...
```

The reason is that in the `resolveAccumulator` we peek the first of the two to replace both, in this case the `R2<T1> _`. 

```
JCPatternCaseLabel leadingTest = 
        (JCPatternCaseLabel) accummulator.first().labels.head;
```

One way to solve this is to not merge two successive type patterns that have different namings (either both named or both unnamed).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317048](https://bugs.openjdk.org/browse/JDK-8317048): VerifyError with unnamed pattern variable and more than one components (**Bug** - P4)

### Reviewers
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15983/head:pull/15983` \
`$ git checkout pull/15983`

Update a local copy of the PR: \
`$ git checkout pull/15983` \
`$ git pull https://git.openjdk.org/jdk.git pull/15983/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15983`

View PR using the GUI difftool: \
`$ git pr show -t 15983`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15983.diff">https://git.openjdk.org/jdk/pull/15983.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15983#issuecomment-1740665133)

### CODE REVIEW

**Comment by biboudis** [comment]
Keep open 🚀

**Review by lahodaj — APPROVED** [review]
Looks OK.

**Pull request closed without merging**
