### PR TITLE
8342701: [PPC64] TestOSRLotsOfLocals.java crashes

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Fix for "assert(nbits == 32 || (-(1 << (nbits-1)) <= x && x < (1 << (nbits-1)))) failed: value out of range" in new test "TestOSRLotsOfLocals" (see JBS).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342701](https://bugs.openjdk.org/browse/JDK-8342701): [PPC64] TestOSRLotsOfLocals.java crashes (**Bug** - P3)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21613/head:pull/21613` \
`$ git checkout pull/21613`

Update a local copy of the PR: \
`$ git checkout pull/21613` \
`$ git pull https://git.openjdk.org/jdk.git pull/21613/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21613`

View PR using the GUI difftool: \
`$ git pr show -t 21613`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21613.diff">https://git.openjdk.org/jdk/pull/21613.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21613#issuecomment-2426817493)

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Looks good to me.

**Review by reinrich — APPROVED** [review]
Looks good.

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews!

**Pull request closed without merging**
