### PR TITLE
8271276: C2: Wrong JVM state used for receiver null check

### PR DESCRIPTION
**Pull request by iwanowww**
JDK-8257211 enabled call devirtualization during post-parse phase. When a virtual call is replaced, there is a receiver null check inserted, but wrong JVM state is picked up (arguments vs locals). (`GraphKit::null_check_receiver_before_call()` should have been used instead).

Instead of fixing the problematic null check, I decided to completely remove it because it is redundant: all relevant `CallGenerator`s already issue a receiver null check when one is required.   

Testing: hs-tier1 - hs-tier6

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271276](https://bugs.openjdk.java.net/browse/JDK-8271276): C2: Wrong JVM state used for receiver null check

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5150/head:pull/5150` \
`$ git checkout pull/5150`

Update a local copy of the PR: \
`$ git checkout pull/5150` \
`$ git pull https://git.openjdk.java.net/jdk pull/5150/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5150`

View PR using the GUI difftool: \
`$ git pr show -t 5150`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5150.diff">https://git.openjdk.java.net/jdk/pull/5150.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

I assume you are talking about this existing null check code for virtual call receiver:
[callGenerator.cpp#L242](
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/callGenerator.cpp#L242)

**Comment by vnkozlov** [comment]
I don't see link to testing in bug report.

**Comment by iwanowww** [comment]
> I assume you are talking about this existing null check code for virtual call receiver:
callGenerator.cpp#L242

No, the relevant places are [callGenerator.cpp#L166](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/callGenerator.cpp#L166), [callGenerator.cpp#L924](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/callGenerator.cpp#L924), [callGenerator.cpp#L1291](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/callGenerator.cpp#L1291), and [parse1.cpp#L1130](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/parse1.cpp#L1130). 

My observation is if there's a fresh `CallGenerator` constructed in `LateInlineVirtualCallGenerator::do_late_inline_check()`, it always handles receiver null check itself.

**Comment by vnkozlov** [comment]
I thought `VirtualCallGenerator::generate()` will be call by following `inline_cg()->generate(jvms)` at line #740 (for virtual calls) and it will generate null check I pointed.

The lines you pointed are for other types of calls.

Anyway, changes are fine since all `*CallGenerator::generate()` methods do null check as we see.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Tobias.

/integrate

**Pull request closed without merging**
