### PR TITLE
8300273: [IR framework] Handle <!-- safepoint while printing --> message instead of bailing out

### PR DESCRIPTION
**Pull request by chhagedorn**
This is yet another attempt to fix the IR framework in cases where the `tty` lock is broken for a safepoint. This time, however, I've decided to not add another bailout but to just rewrite the `hotspot_pid*` parsing code to completely parse everything. This means that `<!-- safepoint while printing -->` messages are now skipped and then parsing continues for the reminder of a `PrintIdeal` output block.

#### When are `tty` locks broken?
This can only happen when dumping `PrintIdeal` for various compile phases. For `PrintOptoAssembly`, we have a `NoSafePointVerifier` object that ensures that we are not safepointing during the dump:
https://github.com/openjdk/jdk/blob/f7da09c34918eea434c82af22b1da1f2a5b35f35/src/hotspot/share/opto/output.cpp#L1814-L1822
The last interesting message printed by `LogCompilation` that needs to be parsed is the compilation queued message. This message is emitted in `CompileTask::log_task_queued()` where we also take the `tty` lock. Since we do not seem to safepoint during this method, I've added a `NoSafepointVerifier` object - just to be sure.

#### Implementation details
The idea is that we keep track of writer thread ids and currently parsed `PrintIdeal` blocks when parsing the `hotspot_pid*` file. If a new writer thread starts writing, it emits a `<writer thread='1683670'/>` message with the id. If that happens while we are still parsing a `PrintIdeal` block (i.e. not found the `</ideal>` end tag for the `<ideal ... />` opening tag), we store the currently parsed method (i.e. a `LoggedMethod` object) with its `WriterThread` in `WriterThread::saveLoggedMethod()`. When later parsing the same writer id again, we restore the method with `WriterThread::restoreLoggedMethod()` and continue parsing.

Each line of a `PrintIdeal` output block is stored within a `CompilePhaseBlock` object. This class makes sure to remove any `<!-- safepoint while printing -->` message (always at the end of a line with a line break) and to merge such a split line again.

I've removed all previously added bailout fixes as they are not needed anymore with this fix.

I've added some more classes and did some renamings to better structure the parsing steps. 

#### Testing
On top of normal tier testing, I've added a separate test that parses a manually written `hotspot_pid*` file that simulates various cases of breaking the tty log and emitting the `<!-- safepoint while printing -->` message with a line break.

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300273](https://bugs.openjdk.org/browse/JDK-8300273): [IR framework] Handle &lt;!-- safepoint while printing --&gt; message instead of bailing out

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12246/head:pull/12246` \
`$ git checkout pull/12246`

Update a local copy of the PR: \
`$ git checkout pull/12246` \
`$ git pull https://git.openjdk.org/jdk pull/12246/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12246`

View PR using the GUI difftool: \
`$ git pr show -t 12246`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12246.diff">https://git.openjdk.org/jdk/pull/12246.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
This is hard to review but the solution makes sense and the code looks good to me. Some of the files still have copyright year 2022.

**Comment by chhagedorn** [comment]
Thank you Tobias for your review! I've updated the copyright years.

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review :-)

I gave this another spin in the Valhalla repository and noticed that I accidentally dropped the XML escaping. I've re-added it. Will re-run some testing again.

**Review by TobiHartmann — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Update is good.

**Comment by chhagedorn** [comment]
Thanks Tobias and Vladimir for your reviews! Valhalla testing looked good with the update.

/integrate

**Pull request closed without merging**
