### PR TITLE
8261940: Fix references to IOException in BigDecimal javadoc 

### PR DESCRIPTION
**Pull request by jddarcy**
Noticed by some of  Jon Gibbons's doc linting & checking tooling, this changeset fixes two javadoc issues for BigDecimal's serialization-related methods, improving the serial form page.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261940](https://bugs.openjdk.java.net/browse/JDK-8261940): Fix references to IOException in BigDecimal javadoc

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 27ff1d780d6b1992c4cbe7bf4253069b70fbaa7d
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to 27ff1d780d6b1992c4cbe7bf4253069b70fbaa7d
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to 27ff1d780d6b1992c4cbe7bf4253069b70fbaa7d
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**) ⚠️ Review applies to 27ff1d780d6b1992c4cbe7bf4253069b70fbaa7d

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2623/head:pull/2623`
`$ git checkout pull/2623`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Looks okay but it might be simpler to just import java.io.IOException and avoid having two usages of the fully qualified name in the source file.

**Review by ChrisHegarty — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by bplb — APPROVED** [review]
I concur with @AlanBateman about importing `IOException`.

**Comment by jddarcy** [comment]
Will integrate using the suggested import of java.io.IOException; thanks.

**Pull request closed without merging**
