### PR TITLE
6278172: TextComponent.getSelectedText() throws StringIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by mrserb**
The text components are implements as wrappers over the "native" peers. Most of the functionality is provided by the peers not wrappers like TextArea/TextField. The current bug occurs in the TextArea/TextField when the native peer was created yet.

The steps to reproduce:
 1. Sets the long text to the component
 2. Select all text in the component
 3. Sets the short text to the component
 4. Request the selected text -> BOOM

The bug on step 4 occurred because we request a long substring of the short text. To eliminate an exception we have two choices:
 1. Preserve the selection in the setText(), but limit it by the length of the current text.
 2. Resets the selection.

I tried both solutions, the second caused some TCK tests to fail, so I selected the first one.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-6278172](https://bugs.openjdk.java.net/browse/JDK-6278172): TextComponent.getSelectedText() throws StringIndexOutOfBoundsException

### Reviewers
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1104/head:pull/1104`
`$ git checkout pull/1104`

### CODE REVIEW

**Comment by mrserb** [comment]
Any volunteers for a review?

**Comment by mrserb** [comment]
Any volunteers for a review?

**Review by aivanov-jdk — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
I wonder how native text components behave: is the selection preserved when text is replaced?

**Comment by mrserb** [comment]
> I wonder how native text components behave: is the selection preserved when text is replaced?

On windows, the selection resets, on macOS and Linux it is preserved. But it works that way because we implemented it in a such way, actually did not pay attention to such use-case.

> Do I get it right that if the new text is longer than the initial one, then only the portion will be left selected.

For the case:
 1. the user sets the short text
 2. then selects the longer distance
 3. then sets the longer text
nothing is changed. The select() method at step 2 will trim passed parameters based on the short text at step 1. So only the portion of the text will be selected.

> Won't it cause the issue if the scenario where the selectionStart is past the length of the new text. I mean the only "field" portion of "text field" is selected, and then the text in component is replaced with "text", thus the selectionStart points 1 character past the end of the new text.

The new call to select() method should take care of that since the user as well can call it passing wrong parameters.

**Comment by aivanov-jdk** [comment]
> The new call to select() method should take care of that since the user as well can call it passing wrong parameters.

Thank you for clarification.

Looks good.

**Pull request closed without merging**
