### PR TITLE
8280916: Simplify HotSpot Style Guide editorial changes

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the HotSpot Style Guide change process.

The current process involves gathering consensus among the HotSpot Group
Members.  That's fine for changes of substance.  But it seems overly weighty
for editorial changes that don't affect the substance of the guide, but only
it's clarity or accuracy.

The proposed change would permit the normal PR process to be used for such
changes, but require the requisite reviewers to additionally be HotSpot Group
Members.

Note that there have already been a couple of changes that effectively
followed the proposed new process.
https://bugs.openjdk.java.net/browse/JDK-8274169
https://bugs.openjdk.java.net/browse/JDK-8280182

This is a modification of the Style Guide, so rough consensus among the
HotSpot Group members is required to make this change. Only Group members
should vote for approval (via the github PR), though reasoned objections or
comments from anyone will be considered. A decision on this proposal will not
be made before Monday 14-Feb-2022 at 12h00 UTC.

Since we're piggybacking on github PRs here, please use the PR review process
to approve (click on Review Changes > Approve), rather than sending a "vote:
yes" email reply that would be normal for a CFV.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280916](https://bugs.openjdk.java.net/browse/JDK-8280916): Simplify HotSpot Style Guide editorial changes

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Stefan Karlsson](https://openjdk.java.net/census#stefank) (@stefank - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7281/head:pull/7281` \
`$ git checkout pull/7281`

Update a local copy of the PR: \
`$ git checkout pull/7281` \
`$ git pull https://git.openjdk.java.net/jdk pull/7281/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7281`

View PR using the GUI difftool: \
`$ git pr show -t 7281`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7281.diff">https://git.openjdk.java.net/jdk/pull/7281.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by dholmes-ora — APPROVED** [review]

**Review by tstuefe — APPROVED** [review]
This makes sense.

About substantive changes: since those affect a lot of people, would it make sense to include a clause for a minimum time to collect answers on a proposed style change? Like the 24hrs clause for code reviews?

Thanks, Thomas

**Review by stefank — APPROVED** [review]

**Comment by kimbarrett** [comment]
> About substantive changes: since those affect a lot of people, would it make sense to include a clause for a minimum time to collect answers on a proposed style change? Like the 24hrs clause for code reviews?

Since ultimately a substantive change requires the Group Lead to decide that consensus has been reached, I don't think more detail is really necessary in this area.

**Review by vnkozlov — APPROVED** [review]
Approved.

**Review by tschatzl — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks @vnkozlov and all the other reviewers.

**Pull request closed without merging**
