### PR TITLE
8293069: Make -XX:+Verbose less verbose

### PR DESCRIPTION
**Pull request by enothum**
1) Added PrintOpto guard to noisy Verbose prints in Compile::process_for_unstable_if_traps and Parse::catch_call_exceptions.

2) Removed noisy Verbose in ciEnv::record_best_dyno_loc, which looked like a leftover from implementation of [JDK-8271911](https://bugs.openjdk.org/browse/JDK-8271911).
I also rearranged the if statement around Verbose and removed the TODO comment.
@dean-long is the TODO still relevant? In case it is still relevant, I think we should create a separate enhancement for further investigation rather than keeping it in the comments.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293069](https://bugs.openjdk.org/browse/JDK-8293069): Make -XX:+Verbose less verbose (**Enhancement** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14420/head:pull/14420` \
`$ git checkout pull/14420`

Update a local copy of the PR: \
`$ git checkout pull/14420` \
`$ git pull https://git.openjdk.org/jdk.git pull/14420/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14420`

View PR using the GUI difftool: \
`$ git pr show -t 14420`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14420.diff">https://git.openjdk.org/jdk/pull/14420.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14420#issuecomment-1589455567)

### CODE REVIEW

**Comment by dean-long** [comment]
The TODO is still relevant (we could chose a winner based on shorting string length, for example), but I don't think it's important enough for an RFE.  Removing the TODO is fine.

**Comment by enothum** [comment]
Thanks for your feedback! In that case I won't create an RFE and proceed with the change.

**Pull request closed without merging**
