### PR TITLE
8274980: Improve adhoc build version strings

### PR DESCRIPTION
**Pull request by magicus**
Current adhoc version build strings are not ideal. Some of the problems:
 * A build number of "0" is inserted, which make the version string look like it's an official build, at least when not reading carefully
 * The version string gives little indication on what source code the build was based

Also, an error was discovered in how the build system generates version strings without a build number (since this basically never happened before). A version without a build number,  and without a PRE value, but with an OPT value, should have a "+-" separator, according to JEP 223. While this was correctly handled, the "+-" separator was also applied to versions without a build, but with both PRE and OPT. In this case, the "+" should be omitted, according to JEP 223. This bug is fixed by this commit.

Ideally, the adhoc version string should include something along the lines of the output of `git describe`. However, since the version string is set at configure time, not build time, this will almost immediately become misleading. :-( A substitute is proposed in this patch, where the branch name is included in the OPT string (if it's not `master`).

Finally, this patch fixes hotspot so it can properly build without a build number. This was the last blocker for why the build system always required the "0" as build number before. To facilitate interoperability with external tools (like jib) that still sets build number to "0" to really signal "no build number", a build number exactly matching "0" will be interpreted as having no build number.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274980](https://bugs.openjdk.java.net/browse/JDK-8274980): Improve adhoc build version strings

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6152/head:pull/6152` \
`$ git checkout pull/6152`

Update a local copy of the PR: \
`$ git checkout pull/6152` \
`$ git pull https://git.openjdk.java.net/jdk pull/6152/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6152`

View PR using the GUI difftool: \
`$ git pr show -t 6152`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6152.diff">https://git.openjdk.java.net/jdk/pull/6152.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Give me a bit more time, bot...

**Comment by TheShermanTanker** [comment]
Is the version string for the following `build 17+35-LTS-2724`?
```
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```
(I can't remember what they were like since I built the jdk a while ago) 

If that's the case, I'm wondering if instead of changing `18-internal+0-adhoc.shade.jdk (18-internal)` to something like `18-internal-jdk-18+17-80-gcdf89304eaf.shade (18-internal)`, `build 18<+build number, not required>-internal-<branch name + commit id>` would be more understandable and slightly easier on one's eyes, while conveying the same information the usual (verbose) version string otherwise tries to display

I can help with resolving the test failures, if needed?

**Comment by shipilev** [comment]
> If that's the case, I'm wondering if instead of changing `18-internal+0-adhoc.shade.jdk (18-internal)` to something like `18-internal-jdk-18+17-80-gcdf89304eaf.shade (18-internal)`, `build 18<+build number, not required>-internal-<branch name + commit id>` would be more understandable and slightly easier on one's eyes, while conveying the same information the usual (verbose) version string otherwise tries to display

We have been discussing this (see the bug comments in JIRA). The showstopper is that versions are captured during `configure`, which means you can configure on one branch, switch to another, and your build would still be recorded as produced by old branch.

**Comment by TheShermanTanker** [comment]
> > If that's the case, I'm wondering if instead of changing `18-internal+0-adhoc.shade.jdk (18-internal)` to something like `18-internal-jdk-18+17-80-gcdf89304eaf.shade (18-internal)`, `build 18<+build number, not required>-internal-<branch name + commit id>` would be more understandable and slightly easier on one's eyes, while conveying the same information the usual (verbose) version string otherwise tries to display
> 
> We have been discussing this (see the bug comments in JIRA). The showstopper is that versions are captured during `configure`, which means you can configure on one branch, switch to another, and your build would still be recorded as produced by old branch.

I must've missed that, my bad. I was referring to the original issue though, where the final generated version string is ultimately something along the lines of `18-internal-jdk-18+17-80.shade (18-internal)`, which could potentially be shortened to something like `build 18<+build number>-internal`, which is much less verbose and somewhat easier to understand.

All that aside though, would it be possible to detect the branch and commit at compile time?

**Comment by TheShermanTanker** [comment]
I'm not sure if there's a neater way to do this, but I did come up with a fix for `[IS_EMPTY define did not work on msvc](https://github.com/openjdk/jdk/pull/6152/commits/3c93c740e6d0d8624be6f87b5495d61b408167bd)`: https://github.com/magicus/jdk/commit/085ae29f2f01df1f06433713f5a554e7f3b375aa which seems to work properly for MSVC when building on Windows when handling empty version build numbers. I'm not too versed with the build system though, so I'm not entirely sure that it working with MSVC is a direct result of the change or just a coincidence (Potentially caused by the change made to make/autoconf/spec.gmk.in in this PR)

**Comment by magicus** [comment]
This was more problematic than expected. Two tests made unfounded assumptions about version string format; one was simple to fix but the other tricky to track down, since I initially could not reproduce it locally but only in our CI testing. (It turned out that this was since the CI testing made a specially formatted version string.) 

The GHA actions all made use of "--with-version-build=0", and thus all of them failed when trying to upload builds. It took me a while to realize that this was due to file names with version strings in them, and not general shakiness of the GHA builds.

I think this is finally ready for review now. :-)

**Review by shipilev — APPROVED** [review]
I like this. Built the adhoc binary with this patch, and version string is nice:

```
$ build/linux-x86_64-server-fastdebug/images/jdk/bin/java -version
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (fastdebug build 19-internal-adhoc.shade.jdk)
OpenJDK 64-Bit Server VM (fastdebug build 19-internal-adhoc.shade.jdk, mixed mode, sharing)
```

**Pull request closed without merging**
