### PR TITLE
8253379: [windows] Several jpackage tests failed with error code 1638

### PR DESCRIPTION
**Pull request by andyherrick**
8253379: [windows] Several jpackage tests failed with error code 1638
two windows specific test fixes in WindowsHelper:
1.) do not test that the parent directory of a windows menu shortcut is empty after shortcut is uninstalled (there may be other shortcuts using that directory)
2.) do not programmatically install windows exe installers (since we have no way of programmatically uninstalling them)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253379](https://bugs.openjdk.java.net/browse/JDK-8253379): [windows] Several jpackage tests failed with error code 1638

### Reviewers
 * [Alexey Semenyuk](https://openjdk.java.net/census#asemenyuk) (@alexeysemenyukoracle - Committer) ⚠️ Review applies to 1e20f1c7b11f13542325b413334011617d6b41ce
 * [Alexander Matveev](https://openjdk.java.net/census#almatvee) (@sashamatveev - Committer)
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/337/head:pull/337`
`$ git checkout pull/337`

### CODE REVIEW

**Comment by sashamatveev** [comment]
According to msiexec help, msiexec supports ProductCode for uninstall "/x | Package\|ProductCode". Do you know if it would be possible to use such options?

**Comment by alexeysemenyukoracle** [comment]
Currently msi wrapper unconditionally adds "/i" on msiexec command line. So passing "/x" option to exe installer would not work. 
I think we need to rework msi wrapper to only support one command line option - "--uninstall" instead of passing all command line parameters to nested msiexec invocation.

**Comment by andyherrick** [comment]
> 
> 
> Currently msi wrapper unconditionally adds "/i" on msiexec command line. So passing "/x" option to exe installer would not work.
> I think we need to rework msi wrapper to only support one command line option - "--uninstall" instead of passing all command line parameters to nested msiexec invocation.

yes - but until we have that implemented in the wrapper, shouldn't we disable in the tests installing what we can't unintall ?

**Review by alexeysemenyukoracle — APPROVED** [review]

**Review by sashamatveev — APPROVED** [review]

**Review by azuev-java — APPROVED** [review]

**Pull request closed without merging**
