### PR TITLE
8236136: tests which use CompilationMode shouldn't be run w/ TieredStopAtLevel

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Prevents the tests from JDK-8236136 from running when the required `TieredStopAtLevel` is not met, with the exception of `compiler/jvmci/events/JvmciNotifyBootstrapFinishedEventTest` as it seems to already have the requirement set, and I'm not sure what (or whether) to update it's required `TieredStopAtLevel` to should the existing one be outdated (Would appreciate any feedback on this part)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8236136](https://bugs.openjdk.java.net/browse/JDK-8236136): tests which use CompilationMode shouldn't be run w/ TieredStopAtLevel

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7451/head:pull/7451` \
`$ git checkout pull/7451`

Update a local copy of the PR: \
`$ git checkout pull/7451` \
`$ git pull https://git.openjdk.java.net/jdk pull/7451/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7451`

View PR using the GUI difftool: \
`$ git pr show -t 7451`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7451.diff">https://git.openjdk.java.net/jdk/pull/7451.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by TheShermanTanker** [comment]
Thanks! Gonna integrate shortly

**Comment by TheShermanTanker** [comment]
@neliasso I almost forgot, does `compiler/jvmci/events/JvmciNotifyBootstrapFinishedEventTest` need any updating for it's TieredStopAtLevel requirements or is it good to remain as is?

**Comment by neliasso** [comment]
> @neliasso I almost forgot, does `compiler/jvmci/events/JvmciNotifyBootstrapFinishedEventTest` need any updating for it's TieredStopAtLevel requirements or is it good to remain as is?

It should be good as it is. It already requires that TieredStopAtLevel is not set. When used, Jvmci is level 4, so there is no reason to run with that flag.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Pull request closed without merging**
