### PR TITLE
8290300: Use standard String-joining tools where applicable

### PR DESCRIPTION
**Pull request by stsypanov**
Simplify code with `String.join()`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290300](https://bugs.openjdk.org/browse/JDK-8290300): Use standard String-joining tools where applicable

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9513/head:pull/9513` \
`$ git checkout pull/9513`

Update a local copy of the PR: \
`$ git checkout pull/9513` \
`$ git pull https://git.openjdk.org/jdk pull/9513/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9513`

View PR using the GUI difftool: \
`$ git pr show -t 9513`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9513.diff">https://git.openjdk.org/jdk/pull/9513.diff</a>

</details>

### CODE REVIEW

**Comment by stsypanov** [comment]
Reverted jops

**Comment by stsypanov** [comment]
@JimLaskey I'll double check and add tests if necessary

**Comment by stsypanov** [comment]
@JimLaskey changes in `WindowsPath` are covered by `PathOps`, apart from this there are 10 tests calling this method.

With `ProcessBuilder` and `Locale` it looks like the code I've changed is never executed at all for `ProcessStartEvent.isEnabled()` always return false and `ProcessStartEvent` itself is not used anywhere else.

For `Locale` all the call sites of `formatList()` never pass null, so the code in `if` block is never executed. I think we can delete this unused parts of the code in `Locale`, but I'm not sure about `ProcessBuilder`.

**Comment by naotoj** [comment]
> For `Locale` all the call sites of `formatList()` never pass null, so the code in `if` block is never executed. I think we can delete this unused parts of the code in `Locale`,

Are you sure about this? `pattern` is derived from `LocaleResources.getLocaleName()` which could return `null`.

**Comment by stsypanov** [comment]
Right, my bad. I've confused arguments. The changes reverted.

**Review by naotoj — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
Changes to HttpURLConnection look good to me

**Comment by stsypanov** [comment]
Anyone to sponsor?

**Comment by stsypanov** [comment]
Thanks!

**Pull request closed without merging**
