### PR TITLE
8330686: Fix typos in the DatabaseMetaData javadoc

### PR DESCRIPTION
**Pull request by onacit**
Fix typos within the `DatabaseMetaData.java`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330686](https://bugs.openjdk.org/browse/JDK-8330686): Fix typos in the DatabaseMetaData javadoc (**Enhancement** - P5)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18860/head:pull/18860` \
`$ git checkout pull/18860`

Update a local copy of the PR: \
`$ git checkout pull/18860` \
`$ git pull https://git.openjdk.org/jdk.git pull/18860/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18860`

View PR using the GUI difftool: \
`$ git pr show -t 18860`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18860.diff">https://git.openjdk.org/jdk/pull/18860.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18860#issuecomment-2067619248)

### CODE REVIEW

**Comment by onacit** [comment]
@openjdk with issue from where?

**Comment by jaikiran** [comment]
Hello @onacit, it appears a JBS issue has been filed for this https://bugs.openjdk.org/browse/JDK-8330686. Please change the title of this PR to `8330686: Fix typos in the DatabaseMetaData javadoc` so that it triggers the official review process.

**Review by jaikiran — COMMENTED** [review]
These typo fixes look fine to me. Please update the copyright year on the file from `1996, 2022,` to `1996, 2024,`

**Comment by onacit** [comment]
@jaikiran Done. Thank you.

**Review by jaikiran — APPROVED** [review]
Thank you for the update. The changes look fine to me.

**Review by LanceAndersen — APPROVED** [review]

**Comment by jaikiran** [comment]
Hello Jin, once a PR is approved, unless there are additional review comments to address, it's a good idea not to update/change the PR.

In this case, it appears that you only updated the commit message to include the `Reviewed-By` line. Contributions to the JDK repo these days use bots which automatically add the `Reviewed-By` line when the PR is actually being integrated. We used to previously (before migrating to GitHub pull requests) expect the contributors to add that line themselves, but that's no longer the case.

I have reviewed this PR afresh and the change still looks good to me. I'll go ahead and sponsor this now.

**Review by jaikiran — APPROVED** [review]

**Comment by onacit** [comment]
@jaikiran Is everything O.K. with this PR? Is it merged? Please help me. Thank you anyway.

**Comment by jaikiran** [comment]
Yes, the PR has been merged and the changes are now part of the JDK.

**Comment by onacit** [comment]
@jaikiran I do love you. Thank you.

**Pull request closed without merging**
