### PR TITLE
8263508: Remove dead code in MethodHandleImpl

### PR DESCRIPTION
**Pull request by cl4es**
Remove unused methods.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263508](https://bugs.openjdk.java.net/browse/JDK-8263508): Remove dead code in MethodHandleImpl

### Reviewers
 * [Johannes Kuhn](https://openjdk.java.net/census#jkuhn) (@DasBrain - Author)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2969/head:pull/2969`
`$ git checkout pull/2969`

### CODE REVIEW

**Review by DasBrain — APPROVED** [review]
LGTM

**Review by mlchung — APPROVED** [review]

**Comment by cl4es** [comment]
Thanks for reviewing, @DasBrain and @mlchung.

**Pull request closed without merging**
