### PR TITLE
8322142: JFR: Periodic tasks aren't orphaned between recordings

### PR DESCRIPTION
**Pull request by carterkozak**
This issue is described on the jfr-dev mailing list here:
https://mail.openjdk.org/pipermail/hotspot-jfr-dev/2023-December/005697.html
With a minimal reproducer here:
https://github.com/carterkozak/periodic-event-repro

Currently a draft because I don't have a ticket for this issue, and I haven't had a chance to add a test for this. I have verified that a build with this change resolves the bug I encountered.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322142](https://bugs.openjdk.org/browse/JDK-8322142): JFR: Periodic tasks aren't orphaned between recordings (**Bug** - P2)

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17114/head:pull/17114` \
`$ git checkout pull/17114`

Update a local copy of the PR: \
`$ git checkout pull/17114` \
`$ git pull https://git.openjdk.org/jdk.git pull/17114/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17114`

View PR using the GUI difftool: \
`$ git pr show -t 17114`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17114.diff">https://git.openjdk.org/jdk/pull/17114.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17114#issuecomment-1874531236)

### CODE REVIEW

**Comment by egahlin** [comment]
I need to look more into this, and check this out manually, but what if BatchManager holds a SequencedSet of batches instead (LinkedHashSet).

When active sorted task are iterated and getTask() doesn't return null, the batch is added to batches field. If it already exists, nothing happens, otherwise it is inserted. 

I guess we could end up with two batches with same period, but maybe the period could be the key. A TreeMap or LinkedHahMap.

**Comment by carterkozak** [comment]
I'm not certain what cases the BatchManager is optimized for, but I think the path forward depends quite a bit on that. array/ArrayList is difficult to outperform when inputs are small. TreeMap and LinkedHashSet both involve traversing many more pointers. I'm not sure how we want to weigh the benefit of reusing Batch objects between event disablement and reenablement against the higher traversal cost.

If we did move from ArrayList to a SequencedSet, instead of adding the orphaned flag or re-adding the task, we could update the existing null check along these lines:
```diff
-                if (batch == null) {
+                if (batch == null || !batches.contains(batch)) {
                    batch = findBatch(task.getPeriod());
```

**Comment by egahlin** [comment]
> I'm not certain what cases the BatchManager is optimized for, but I think the path forward depends quite a bit on that. array/ArrayList is difficult to outperform when inputs are small. TreeMap and LinkedHashSet both involve traversing many more pointers. I'm not sure how we want to weigh the benefit of reusing Batch objects between event disablement and reenablement against the higher traversal cost.
> 
> If we did move from ArrayList to a SequencedSet, instead of adding the orphaned flag or re-adding the task, we could update the existing null check along these lines:
> 
> ```diff
> -                if (batch == null) {
> +                if (batch == null || !batches.contains(batch)) {
>                     batch = findBatch(task.getPeriod());
> ```

It would be the same, but we would introduce O(n^2). 

The purpose of the reuse is not reduce allocation, but to make the period stable. Flipping back and forth should not reset things. I need to run with logging to see it looks OK.

**Comment by egahlin** [comment]
I don't think we have a complexity issue anymore.  I was thinkings tasks/events, but batches should at most be 25.

How would this work? If a batch with the same period exists, we reuse it, otherwise we insert it.

```
                     batch = findBatch(task.getPeriod());
+                } else {
+                    insertBatch(batch);
                 }
                 batch.add(task);
             }
```

 
```
+    private void insertBatch(Batch batch) {
+        for (Batch b : batches) {
+            if (b.getPeriod() == batch.getPeriod()) {
+                return; // Batch already exists
+            }
+        }
+        batches.add(batch);
+    }
+
```
```

**Comment by carterkozak** [comment]
> batches should at most be 25

That makes sense, I'd thought you had meant 10,000 events with unique periods :-)

> ```diff
> +    private void insertBatch(Batch batch) {
> +        for (Batch b : batches) {
> +            if (b.getPeriod() == batch.getPeriod()) {
> +                return; // Batch already exists
> +            }
> +        }
> +        batches.add(batch);
> +    }
> ```
I don't think it's correct to assume `b.getPeriod() == batch.getPeriod()` `b` is the same instance as `batch`, though. Consider the following scenario:

1. Event A is enabled at a 10 second interval
1. Event A is disabled (the batch is removed from the BatchManager)
1. Event B is enabled at a 10 second interval (this inserts a new Batch with the same 10 second period)
1. Event A is enabled again (still using the 10 second period).

In this scenario, Event A will have a Batch reference with the same period as the batch used by Event B, so `insertBatches` will return without changing the state of the BatchManager. In cases where the period duplicates an existing batch, I think we need register events to the existing batch.

Perhaps we should update `Batch findBatch(long period)` to `Batch findOrInsertBatch(long period, @Nullable Batch maybeCachedBatch)` where an existing registered batch is returned if one exists, otherwise `maybeCachedBatch` is inserted and returned if non-null, falling back to instantiating a new batch (the current behavior when an existing batch cannot be found). What do you think?

Sorry for slow responses today, I've been away from the computer -- I should have time to update this tomorrow.

**Comment by egahlin** [comment]
Looks reasonable, but maybe this method signature would be easier to understand for someone that doesn't know the history?

    private Batch findBatch(long period, Batch oldBatch) {
      ...
    }

**Comment by carterkozak** [comment]
Sounds good to me, I've applied your suggestion.

I'd appreciate if you could give me some guidance on adding a test for this fix. I may be able fit my reproducer (updated with a 1ms period) into the format of the tests in `jdk.jfr.api.flightrecorder`, but being a periodic test it will require some form of sleep/wait, and be fairly specific to this issue. Please let me know what you think the best path forward is, and I'll put something together :-)

Thanks for your help!

**Comment by egahlin** [comment]
> I'd appreciate if you could give me some guidance on adding a test for this fix.

It's hard to test in a reliable way. I would not add a test. Time is better spent fixing other issues than hunting down false positives.

**Comment by carterkozak** [comment]
That works for me, thank you!

**Review by egahlin — APPROVED** [review]
Could you update the title of PR so it matches the bug? I think a ':' is missing after "JFR".

I can sponsor the change.

After it has been integrated into main, it can be backported to JDK 21 and 22.

**Comment by egahlin** [comment]
> Thanks again @egahlin!
> 
> > After it has been integrated into main, it can be backported to JDK 21 and 22.
> 
> Would you like me to issue the backport commands? I'm not terribly familiar with the process, but I suspect `jdk21u-dev` and `jdk22` are the correct targets?

Let's wait for the change to run through testing before backporting to JDK 22.

If everything looks fine in a couple of weeks, we can also backport to JDK 21. Not sure about the targets, I will have to look it up.

**Pull request closed without merging**
