### PR TITLE
8322513: Build failure with minimal

### PR DESCRIPTION
**Pull request by xpbob**
Build failure with minimal
```
sh configure --with-jvm-variants=minimal 
```
```
=== Output from failing command(s) repeated here ===
* For target hotspot_variant-minimal_libjvm_objs_handshake.o:
/src/hotspot/share/runtime/handshake.cpp: In member function 'HandshakeOperation* HandshakeState::get_op_for_self(bool, bool)':
src/hotspot/share/runtime/handshake.cpp:490:37: error: 'class JavaThread' has no member named 'is_disable_suspend'; did you mean 'is_trace_suspend'?
   if (allow_suspend && _handshakee->is_disable_suspend()) {
                                     ^~~~~~~~~~~~~~~~~~
                                     is_trace_suspend
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322513](https://bugs.openjdk.org/browse/JDK-8322513): Build failure with minimal (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17164/head:pull/17164` \
`$ git checkout pull/17164`

Update a local copy of the PR: \
`$ git checkout pull/17164` \
`$ git pull https://git.openjdk.org/jdk.git pull/17164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17164`

View PR using the GUI difftool: \
`$ git pr show -t 17164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17164.diff">https://git.openjdk.org/jdk/pull/17164.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17164#issuecomment-1863780454)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks fine and trivial.

Thanks

**Comment by dholmes-ora** [comment]
But I think you will then run into further problems due to JDK-8311218 - there is a "fatal" in jvm.cpp that will be called when JVM TI is not available.

**Review by robehn — APPROVED** [review]
Thanks, yes please ship now under trivial.

I have the same fix locally it working fine.

**Comment by xpbob** [comment]
@dholmes-ora @robehn 
Thanks for the review

**Comment by robehn** [comment]
@dholmes-ora, minimal is used when you cross-compile, you need to build a minimal native buildjdk.
This do not yet use "Loom", but if/when folks start using virtual thread in core libs, we can get into problems it seems like.

**Comment by dholmes-ora** [comment]
@robehn I didn't realize Loom support was conditional. In any case the fatal is still wrong.

**Comment by robehn** [comment]
> @robehn I didn't realize Loom support was conditional. In any case the fatal is still wrong.

Sorry, I just mean the bug you found in 8311218 would probably gone unnoticed for very long (at least for us).

**Pull request closed without merging**
