### PR TITLE
8283607: Rename KlassID to KlassKind

### PR DESCRIPTION
**Pull request by stefank**
During the review of JDK-8283574 / #7922 , it was brought up that the term ID to describe the "kind" of *Klass is misleading. Rename KlassID to KlassKind, and update names of variables of KlassID.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283607](https://bugs.openjdk.java.net/browse/JDK-8283607): Rename KlassID to KlassKind

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7936/head:pull/7936` \
`$ git checkout pull/7936`

Update a local copy of the PR: \
`$ git checkout pull/7936` \
`$ git pull https://git.openjdk.java.net/jdk pull/7936/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7936`

View PR using the GUI difftool: \
`$ git pr show -t 7936`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7936.diff">https://git.openjdk.java.net/jdk/pull/7936.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems fine.

Thanks,
David

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by tschatzl — APPROVED** [review]
Still good.

**Review by dholmes-ora — APPROVED** [review]

**Comment by stefank** [comment]
Thanks for reviewing.
/integrate

**Pull request closed without merging**
