### PR TITLE
8328957: Update PKCS11Test.java to not use hardcoded path

### PR DESCRIPTION
**Pull request by mpdonova**
When resolving the location of the NSS library, the code appended a hard-coded path: `/nss/lib`. This makes it difficult for a person to specify the library when it is installed in a location such as `/usr/lib64`. 

In this PR, I removed the hard-coded path and updated the code to search the specified path for the nss library file, softokn3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328957](https://bugs.openjdk.org/browse/JDK-8328957): Update PKCS11Test.java to not use hardcoded path (**Bug** - P4)

### Reviewers
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - Committer)
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18488/head:pull/18488` \
`$ git checkout pull/18488`

Update a local copy of the PR: \
`$ git checkout pull/18488` \
`$ git pull https://git.openjdk.org/jdk.git pull/18488/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18488`

View PR using the GUI difftool: \
`$ git pr show -t 18488`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18488.diff">https://git.openjdk.org/jdk/pull/18488.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18488#issuecomment-2020527672)

### CODE REVIEW

**Review by martinuy — COMMENTED** [review]
Hi @mpdonova ,

Thanks for contributing this fix. I've seen in java.nio.file.Files::find doc an implementation note saying that it should be used in a try-with-resource fashion to close the stream and any open directories. Should we consider this?

One more question. The ".orElse(path).getParent()" code path, what case is it intended for? I wonder in which cases this is expected to succeed.

Martin.-

**Comment by mpdonova** [comment]
> Hi @mpdonova ,
> 
> Thanks for contributing this fix. I've seen in java.nio.file.Files::find doc an implementation note saying that it should be used in a try-with-resource fashion to close the stream and any open directories. Should we consider this?
> 
> One more question. The ".orElse(path).getParent()" code path, what case is it intended for? I wonder in which cases this is expected to succeed.
> 
> Martin.-

I think adding the try-with-resources is a good idea. Always better to close things that potentially leave them open.

The `orElse(path).getParent()` was to return a default path that was then used higher-up on the call stack to check for the existence of the library. Looking at it again, that seemed redundant, since this change also looks for the existence of the library, so I refactored the code a little bit for the new `findNssLibrary()` method to return the path to the library or throw a SkippedException.

I think this is a cleaner way to do it.

**Review by martinuy — APPROVED** [review]
Looks good to me. I verified that it fixes the problem when running PKCS11 tests with system libraries (e.g. /usr/lib64).

**Review by rhalade — APPROVED** [review]

**Pull request closed without merging**
