### PR TITLE
8267364: Remove mask.incr which is introduced by JDK-8256973

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

Please review the trivial change which removes the useless mask.incr.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267364](https://bugs.openjdk.java.net/browse/JDK-8267364): Remove mask.incr which is introduced by JDK-8256973

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4107/head:pull/4107` \
`$ git checkout pull/4107`

Update a local copy of the PR: \
`$ git checkout pull/4107` \
`$ git pull https://git.openjdk.java.net/jdk pull/4107/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4107`

View PR using the GUI difftool: \
`$ git pr show -t 4107`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4107.diff">https://git.openjdk.java.net/jdk/pull/4107.diff</a>

</details>

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good and trivial.

**Comment by DamonFool** [comment]
> Looks good and trivial.

Thanks @iwanowww .
/integrate

**Comment by DamonFool** [comment]
> Looks good and trivial.

Thanks @TobiHartmann .

**Comment by jatin-bhateja** [comment]
Thanks Jie.

**Pull request closed without merging**
