### PR TITLE
8301377: adjust timeout for JLI GetObjectSizeIntrinsicsTest.java subtest again

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial fixes to increase timeouts for tests that timeout under heavy stress:
[JDK-8301377](https://bugs.openjdk.org/browse/JDK-8301377) adjust timeout for JLI GetObjectSizeIntrinsicsTest.java subtest again
[JDK-8305502](https://bugs.openjdk.org/browse/JDK-8305502) adjust timeouts in three more M&M tests
[JDK-8302607](https://bugs.openjdk.org/browse/JDK-8302607) increase timeout for ContinuousCallSiteTargetChange.java

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8301377](https://bugs.openjdk.org/browse/JDK-8301377): adjust timeout for JLI GetObjectSizeIntrinsicsTest.java subtest again
 * [JDK-8302607](https://bugs.openjdk.org/browse/JDK-8302607): increase timeout for ContinuousCallSiteTargetChange.java
 * [JDK-8305502](https://bugs.openjdk.org/browse/JDK-8305502): adjust timeouts in three more M&amp;M tests

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13593/head:pull/13593` \
`$ git checkout pull/13593`

Update a local copy of the PR: \
`$ git checkout pull/13593` \
`$ git pull https://git.openjdk.org/jdk.git pull/13593/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13593`

View PR using the GUI difftool: \
`$ git pr show -t 13593`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13593.diff">https://git.openjdk.org/jdk/pull/13593.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13593#issuecomment-1518367749)

### CODE REVIEW

**Review by naotoj — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
I forgot to include testing info:

- 8301377 has been tested in jdk-20+34 and jdk-21+{9,1[013-9]} stress testing.
- 8302607 has been reworked into increasing the timeout and has been tested in jdk-21+1[89] stress testing.
- 8305502 has been tested in jdk-21+1[7-9] stress testing.

The jdk-21+19 stress run will complete late on Sunday, 2023.04.23.

**Comment by dcubed-ojdk** [comment]
@naotoj and @lmesnik - Thanks for the reviews!
This PR will likely integrate on Monday (2023.04.24).

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by dcubed-ojdk** [comment]
@TobiHartmann - Thanks for the review!

My jdk-21+19 stress testing round had no issues with these fixes.

/integrate

**Pull request closed without merging**
