### PR TITLE
8337269: G1ConfidencePercent interpreted inconsistently

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that removes the inconsistency in interpretation of G1ConfidencePercent; higher confidence means that G1 should use less safety margin (i.e. part of the variance).

Other than that it does not change the uses for it.

Testing: gha

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337269](https://bugs.openjdk.org/browse/JDK-8337269): G1ConfidencePercent interpreted inconsistently (**Bug** - P4)

### Reviewers
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**) Review applies to [9ffbbdc9](https://git.openjdk.org/jdk/pull/21448/files/9ffbbdc9401b75f13c282988fb27ff3ba69ed844)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21448/head:pull/21448` \
`$ git checkout pull/21448`

Update a local copy of the PR: \
`$ git checkout pull/21448` \
`$ git pull https://git.openjdk.org/jdk.git pull/21448/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21448`

View PR using the GUI difftool: \
`$ git pr show -t 21448`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21448.diff">https://git.openjdk.org/jdk/pull/21448.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21448#issuecomment-2404648025)

### CODE REVIEW

**Review by walulyai — APPROVED** [review]

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by kimbarrett — CHANGES_REQUESTED** [review]
Retracting my prior approval.

I think the proposed change does address the described inconsistency.  But I
think it doesn't go far enough.

The G1Predictions constructor takes a "sigma" argument.  It range checks it,
and the failure message describes it as "confidence".  The accessor for that
value is described as "Confidence factor".  That seems inconsistent with the
usage (a small value suggests higher confidence in the average value), and
with the new calculation of the argument.

**Comment by tschatzl** [comment]
> Retracting my prior approval.
> 
> I think the proposed change does address the described inconsistency. But I think it doesn't go far enough.
> 
> The G1Predictions constructor takes a "sigma" argument. It range checks it, and the failure message describes it as "confidence". The accessor for that value is described as "Confidence factor". That seems inconsistent with the usage (a small value suggests higher confidence in the average value), and with the new calculation of the argument.

I renamed the member as it had a wrong name anyway; sigma is the actual value of the stddev, not some factor. I hope this is good enough to address your concerns.

**Review by kimbarrett — CHANGES_REQUESTED** [review]

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by tschatzl** [comment]
Thanks @walulyai @kimbarrett for your reviews
/integrate

**Pull request closed without merging**
