### PR TITLE
8307399: get rid of compatibility ThreadStart/ThreadEnd events for virtual threads

### PR DESCRIPTION
**Pull request by sspitsyn**
The compatible lifecycle `ThreadStart/ThreadEnd` events were added in JDK 19 to support legacy virtual thread unaware JVMTI agents which do not enable the can_support_virtual_threads capability. When this capability is enabled then the `VirtualThreadStart/VirtualThreadEnd` instead of the `ThreadStart/ThreadEnd` events are generated for virtual threads and can be managed (enabled/disabled) separately. If the the `can_support_virtual_threads` capability is disabled then the `ThreadStart/ThreadEnd` events are generated for virtual threads.
This enhancement is to get rid of the compatible lifecycle `ThreadStart/ThreadEnd` events.
Motivation: Performance overhead from compatible lifecycle events can be significant when a lot of virtual threads are created.

Also, there is an experimental VM flag `PostVirtualThreadCompatibleLifecycleEvents` (enabled by default).
If it is turned on then the default compatible lifecycle `ThreadStart/ThreadEnd` events for virtual threads are generated. This VM flag has to be removed now.

Testing:
The mach5 tiers 1-6 were submitted and passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8307401](https://bugs.openjdk.org/browse/JDK-8307401) to be approved

### Issues
 * [JDK-8307399](https://bugs.openjdk.org/browse/JDK-8307399): get rid of compatibility ThreadStart/ThreadEnd events for virtual threads
 * [JDK-8307401](https://bugs.openjdk.org/browse/JDK-8307401): get rid of compatibility ThreadStart/ThreadEnd events for virtual threads (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13874/head:pull/13874` \
`$ git checkout pull/13874`

Update a local copy of the PR: \
`$ git checkout pull/13874` \
`$ git pull https://git.openjdk.org/jdk.git pull/13874/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13874`

View PR using the GUI difftool: \
`$ git pr show -t 13874`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13874.diff">https://git.openjdk.org/jdk/pull/13874.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13874#issuecomment-1539266948)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
The spec + implementation changes looks okay, it's a good simplification.

**Review by pchilano — APPROVED** [review]
Looks good to me.

Thanks,
Patricio

**Review by plummercj — APPROVED** [review]

**Comment by sspitsyn** [comment]
Thank you for review, Chris!

**Pull request closed without merging**
