### PR TITLE
8252526: Remove excessive inclusion of jvmti.h and jvmtiExport.hpp

### PR DESCRIPTION
**Pull request by iklam**
jvmti.h is included 905 times and jvmtiExport.hpp is included 776 times (out of 971 hotspot .o files). Most of these are unnecessarily included by the following 3 popular header files:

* javaClasses.hpp: `java_lang_Class::ThreadStatus` (which depends on jvmti.h) this type is rarely used. Move this type to a separate header file. The enum is also changed to an enum class for better type safety.
* os.hpp: No need to include jvmti.h. Use forward declaration for `struct jvmtiTimerInfo;` instead.
* thread.hpp: No need to include jvmExport.hpp. Use forward declaration for `JvmtiSampledObjectAllocEventCollector` and `JvmtiVMObjectAllocEventCollector` instead.

Tested with mach5 tier1-2 and build tiers 3-5.

Note: Many files are changed, but most of the changes are adding a missing jvmtiExports.hpp.

Original review thread: https://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2020-August/041509.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252526](https://bugs.openjdk.java.net/browse/JDK-8252526): Remove excessive inclusion of jvmti.h and jvmtiExport.hpp

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to becd1f67aa66180be1eb7cf2ab04ce7cf56c679b
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to becd1f67aa66180be1eb7cf2ab04ce7cf56c679b

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1152/head:pull/1152`
`$ git checkout pull/1152`

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Thank you for your continued effort to simplify building of hotspot. All efforts to clean up the include mess edges us slowly towards a more efficient hotspot build (which will improve build times overall, since most of the product depends on hotspot).

**Review by kimbarrett — APPROVED** [review]
Nice!

**Comment by iklam** [comment]
Thanks @magicus @kimbarrett for the review
/integrate

**Pull request closed without merging**
