### PR TITLE
8339359: RISC-V: Use auipc explicitly in far_jump and far_call macro assembler routines

### PR DESCRIPTION
**Pull request by RealFYang**
Previous discussion: https://github.com/openjdk/jdk/pull/18942#issuecomment-2109162337

For MacroAssembler::far_call and MacroAssembler::far_jump, I would suggest we use explicit
auipc instead of MacroAssembler::la for them as the destination is ensured to be in code cache.
This will help save unnecessary check in MacroAssembler::la and make the code more consistent.
Also this will help distinguish these two macro assembler routines from MacroAssembler::rt_call

Testing:
- [x] release & fastdebug builds
- [x] Tiered 1-3 tests

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339359](https://bugs.openjdk.org/browse/JDK-8339359): RISC-V: Use auipc explicitly in far_jump and far_call macro assembler routines (**Enhancement** - P4)

### Reviewers
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer) Review applies to [95b69ff0](https://git.openjdk.org/jdk/pull/20805/files/95b69ff08af0efe5ad736b59b28f6c20b1217eae)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20805/head:pull/20805` \
`$ git checkout pull/20805`

Update a local copy of the PR: \
`$ git checkout pull/20805` \
`$ git pull https://git.openjdk.org/jdk.git pull/20805/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20805`

View PR using the GUI difftool: \
`$ git pr show -t 20805`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20805.diff">https://git.openjdk.org/jdk/pull/20805.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20805#issuecomment-2323885341)

### CODE REVIEW

**Comment by robehn** [comment]
Looks good, thanks!

A personal opionion is that I really like my assembler to be as WYSIWYG as possible.

**Review by luhenry — APPROVED** [review]
LGTM

**Comment by RealFYang** [comment]
Thanks for having a look. I just added one commit correcting the assertion message of far_jump.
My local tier1-3 tests are good. @robehn : Can you take another look and approve this?

**Review by robehn — APPROVED** [review]
Thanks, yes!

**Comment by RealFYang** [comment]
Thanks all for the review.
/integrate

**Pull request closed without merging**
