### PR TITLE
JDK-8322782: Clean up usages of unnecessary fully qualified class name "java.util.Arrays"

### PR DESCRIPTION
**Pull request by MBaesken**
In [JDK-8322772](https://bugs.openjdk.org/browse/JDK-8322772) one similar cleanup has been proposed before (and was done in the change). But there are a number of other places in the codebase where the import is done and still the unneeded fully qualified class name "java.util.Arrays" is used so more cleanups can be done.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322782](https://bugs.openjdk.org/browse/JDK-8322782): Clean up usages of unnecessary fully qualified class name "java.util.Arrays" (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [af1c0375](https://git.openjdk.org/jdk/pull/17241/files/af1c0375dcda858122df8d6cf267df823f00027b)
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17241/head:pull/17241` \
`$ git checkout pull/17241`

Update a local copy of the PR: \
`$ git checkout pull/17241` \
`$ git pull https://git.openjdk.org/jdk.git pull/17241/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17241`

View PR using the GUI difftool: \
`$ git pr show -t 17241`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17241.diff">https://git.openjdk.org/jdk/pull/17241.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17241#issuecomment-1875248610)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Looks fine, surprised to see so many. I assume you'll bump the copyright date on all the files before integrating.

**Comment by MBaesken** [comment]
Hi Alan, thanks for the review !
I adjust the copyright year info and also some more places in Invokers.java .

**Review by aivanov-jdk — APPROVED** [review]
Looks good to me.

**Comment by MBaesken** [comment]
Hi Alexey, thanks for the review !

/integrate

**Pull request closed without merging**
