### PR TITLE
8317538: RSA have scalability issue for high vCPU numbers

### PR DESCRIPTION
**Pull request by blperez01**
Modified `getService` method to prevent caching of `ServiceKey`, which was negatively impacting multithreaded performance

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317538](https://bugs.openjdk.org/browse/JDK-8317538): RSA have scalability issue for high vCPU numbers (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16403/head:pull/16403` \
`$ git checkout pull/16403`

Update a local copy of the PR: \
`$ git checkout pull/16403` \
`$ git pull https://git.openjdk.org/jdk.git pull/16403/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16403`

View PR using the GUI difftool: \
`$ git pr show -t 16403`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16403.diff">https://git.openjdk.org/jdk/pull/16403.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16403#issuecomment-1783051305)

### CODE REVIEW

**Comment by blperez01** [comment]
> I have a few questions:
> 
> * The change listed in the bug is not the same as this PR.  The bug removes the section and leaves only the new ServiceKey().  The condition statement left will always be false.
> * This seems like a large performance difference for just removing a condition for the existing key.  Is the problem that is volatile?  Might removing volatile help?
> * This change is done for vCPU machines.  What is the impact on non vCPU?  The reason for the caches was most likely to help single threaded performance.  How have those been situations been effected?

Just fixed the first bullet. I'll investigate the latter two points and see if just removing volatile is sufficient and what the impact is on non vCPUs

**Comment by shipilev** [comment]
The problem with not caching the `ServiceKey`, AFAICS, is that we are going to do `toUpperCase` and `intern` in `ServiceKey` constructor. 

The problem *with* caching the key comes from the contention on a single variable, if we ping-pong different `ServiceKey`-s through that single-slot cache. Dropping `volatile` should not help much, because the first-order effect is contention, not additional synchronization. The easy mitigation would be updating `previousKey` conditionally. For example, when the cache is `null` and have not been initialized.

Single-slot caches are problematic like that. Something like `ConcurrentMap<Pair<String,String>, WeakReference<ServiceKey>>` would mitigate update-side problems with single-slot cache. But it remains to be seen if it is better than accepting `toUpperCase` and `intern`.

**Comment by ferakocz** [comment]
I think the best way to fix this would be what is suggested in the bug: add a new property threadId to the ServiceKey class, save the thread id (currentThread.getId())  in it in the constructor and add checking it (along with the key.matches() check) in the getService() method.

**Pull request closed without merging**
