### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by onacit**
Fixes a typo on `DatabaseMetaData`.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17696/head:pull/17696` \
`$ git checkout pull/17696`

Update a local copy of the PR: \
`$ git checkout pull/17696` \
`$ git pull https://git.openjdk.org/jdk.git pull/17696/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17696`

View PR using the GUI difftool: \
`$ git pr show -t 17696`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17696.diff">https://git.openjdk.org/jdk/pull/17696.diff</a>

</details>

### CODE REVIEW

**Review by Hamlin-Li — COMMENTED** [review]
I see there is more cases could be fixed, e.g.
```
diff --git a/src/java.sql/share/classes/java/sql/DatabaseMetaData.java b/src/java.sql/share/classes/java/sql/DatabaseMetaData.java
index 6f63c2989b8..8722862c5d8 100644
--- a/src/java.sql/share/classes/java/sql/DatabaseMetaData.java
+++ b/src/java.sql/share/classes/java/sql/DatabaseMetaData.java
@@ -3289,7 +3289,7 @@ ResultSet getClientInfoProperties()
      * function name criteria are returned.  They are ordered by
      * {@code FUNCTION_CAT}, {@code FUNCTION_SCHEM},
      * {@code FUNCTION_NAME} and
-     * {@code SPECIFIC_ NAME}.
+     * {@code SPECIFIC_NAME}.
      *
      * <P>Each function description has the following columns:
      *  <OL>
@@ -3339,7 +3339,7 @@ ResultSet getFunctions(String catalog, String schemaPattern,
      * parameter name criteria are returned. They are ordered by
      * {@code FUNCTION_CAT}, {@code FUNCTION_SCHEM},
      * {@code FUNCTION_NAME} and
-     * {@code SPECIFIC_ NAME}. Within this, the return value,
+     * {@code SPECIFIC_NAME}. Within this, the return value,
      * if any, is first. Next are the parameter descriptions in call
      * order. The column descriptions follow in column number order.
      *
```
Can you fix them together?

**Comment by onacit** [comment]
@Hamlin-Li As you wish.

**Comment by onacit** [comment]
@Hamlin-Li Oracle may not allow me. Can you fix this for me?

**Comment by Hamlin-Li** [comment]
Hi, I don't think your pr is in right status, please check the files changed: https://github.com/openjdk/jdk/pull/17696/files

**Comment by onacit** [comment]
`/signed`

**Pull request closed without merging**
