### PR TITLE
8313402: C1: Incorrect LoadIndexed value numbering

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for more investigation. 

This manifests in current tests, if you run them with C1. The root cause for the failure is that we fold two `LoadIndexed` nodes, when one of them reads `char` from `byte[]` via `_getCharStringU` intrinsic, and another one reads `byte` normally. So we can fold the "char"-reading load with "byte" reading load, effectively reading the wrong thing. New regression test shows it: it would read "42" instead of full char.

```
$ build/macosx-aarch64-server-fastdebug/images/jdk/bin/java -XX:TieredStopAtLevel=1 -XX:CICompilerCount=1 -XX:+PrintCompilation -XX:+PrintIR0 -XX:+PrintValueNumbering Test8313402.java

. 8 0 i152 a141[i110](i144) (B) [rc]
...
. 7 0 i180 a162[i110] (C)
...
Value Numbering: LoadIndexed i180 equal to i152 (size 47, entries 27, nesting-diff 0)
``` 

GVN hash discriminates on `type()->tag()`, but that `ValueType` maps to the same `T_INT` for both `char` and `byte`! Instead of hashing on that, let's hash on the original element type instead.

Testing:
 - [x] New regression test fails without the fix, passes after the fix
 - [x] Linux AArch64 fastdebug, `tier1 tier2 tier3`
 - [x] Linux x86_64 fastdebug, `tier1 tier2 tier3`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313402](https://bugs.openjdk.org/browse/JDK-8313402): C1: Incorrect LoadIndexed value numbering (**Bug** - P2)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15091/head:pull/15091` \
`$ git checkout pull/15091`

Update a local copy of the PR: \
`$ git checkout pull/15091` \
`$ git pull https://git.openjdk.org/jdk.git pull/15091/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15091`

View PR using the GUI difftool: \
`$ git pr show -t 15091`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15091.diff">https://git.openjdk.org/jdk/pull/15091.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15091#issuecomment-1658770791)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Nice analysis, the fix looks good to me!

**Comment by shipilev** [comment]
> Nice analysis, the fix looks good to me!

Thanks Tobias! I wonder if it makes sense to wait for more reviewers, or the fix is simple enough to go in now?
Not sure if other compiler folks are on vacations or not :)

**Comment by TobiHartmann** [comment]
I think this is good to go but I'll run some quick sanity testing and report back.

**Comment by TobiHartmann** [comment]
Testing looks good. Ship it!

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
