### PR TITLE
8265473: Move os::Linux to its own header file

### PR DESCRIPTION
**Pull request by iklam**
Closed. New PR with a better design is at #9600.

Another step of moving unnecessary stuff outside of os.hpp

The `os::Linux` class is used only by the Linux-specific code in HotSpot. Therefore, it should be moved outside of os.hpp, which is used by platform-independent code.

I don't have a good name for the new header. `os_linux.hpp` would have been a good name, but that's already taken, so I am settling on os_linux.impl.hpp. Suggestions are welcome.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8265473](https://bugs.openjdk.org/browse/JDK-8265473): Move os::Linux to its own header file

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [5c540f8c](https://git.openjdk.org/jdk/pull/9423/files/5c540f8c07e68b4ceb2450252e66bdd9fe964953)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9423/head:pull/9423` \
`$ git checkout pull/9423`

Update a local copy of the PR: \
`$ git checkout pull/9423` \
`$ git pull https://git.openjdk.org/jdk pull/9423/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9423`

View PR using the GUI difftool: \
`$ git pr show -t 9423`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9423.diff">https://git.openjdk.org/jdk/pull/9423.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Another place that the os::Linux file could be moved to is [os_share_linux.hpp](https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_share_linux.hpp). Today it contains some outdated declarations that are not used by anyone. 

If we interpret the name of this header to be "shared interfaces used by the os/*.cpp files", then os::Linux would belong here.

**Review by coleenp — APPROVED** [review]
This seems fine.  The name could be os_linux_impl.hpp, since impl looks a lot like inline surrounded by dots.
os_share_linux.hpp should be deleted if it's not used.  I wouldn't think of looking there for anything.

**Comment by iklam** [comment]
> This seems fine. The name could be os_linux_impl.hpp, since impl looks a lot like inline surrounded by dots. os_share_linux.hpp should be deleted if it's not used. I wouldn't think of looking there for anything.

I renamed the file to os_linux_impl.hpp. I'll remove os_share_linux.hpp in a separate PR.

**Comment by tstuefe** [comment]
I'm surprised that this works. That you are able to declare a nested class outside its enclosing class.

Apart from that, seeing that this has nothing really to do anymore with os::, why not just drop the "os::" prefix? Just call it "Linux" or "LinuxImpl" or "LinuxHelpers" or "LinuxOsHelpers" ...

**Comment by dholmes-ora** [comment]
I share Thomas's surprise that this works. It also doesn't really make sense to me. You've rendered os_linux.hpp essentially an empty file and lament that there is not a good name for the new file because os_linux.hpp is taken - but that's because os_linux.hpp is actually where os::linux should be declared! 

You want to make os.hpp smaller so perhaps the thing to tackle is why os_<os>.hpp gets included in os.hpp in the first place. Unless it adds to the shared os API (which seems it can't as then it could just be in os.hpp) then there should not be anything in os_<os>.hpp that is needed for the shared os interface. So perhaps a different refactoring across all the os files is what is needed here.

**Comment by iklam** [comment]
David and Thomas,

I think you're right. The current structure of the `os.hpp` header file doesn't make sense. Files like `os_linux.hpp` and `os_linux_x86.hpp` declare additional member functions of the `os` class. However, these functions are never (or should never be) used by cross platform code. For example,  `workaround_expand_exec_shield_cs_limit()` declared in `os_linux_x86.hpp` is used only under the src/hotspot/os/linux diretory.

My proposal is to remove all os- and platform- specific includes from `os.hpp`. The `os` class should include only functions that are usable from shared code.

Then, we can keep the `os_linux.hpp` file, which in turn would include other `os_linux_<arch>.hpp` files. These files should declare functions that are used by Linux-specific source files.

For naming, I would prefer to leave it as `os::Linux` for now, so as to avoid making a huge number of changes. We can change it to something else (like the ones suggested by Thomas) in a separate RFE.

Yes, it's legal to declare `os::Linux` outside of the declaration of the `os` class. See https://en.cppreference.com/w/cpp/language/nested_types

With my new proposal, the function `workaround_expand_exec_shield_cs_limit()` declared in `os_linux_x86.hpp` will move from `os::workaround_expand_exec_shield_cs_limit()` to `os::Linux::workaround_expand_exec_shield_cs_limit()`.

**Comment by tstuefe** [comment]
Interesting about forward-declaring nested classes, did not know that is possible.

I think what you are trying to do - disentangling the interface and removing platform-dependent stuff - is really useful. I even think a lot of the platform-dependent stuff does not even need to appear in any header, local static functions in os_xxx.cpp would have been fine.

I propose a slightly alternative way for this though. How about making `os` a real namespace? That's what AllStatic tries to be anyway. It's only a class because namespaces did not exist when it was introduced.

In contrast to a class you can extend namespaces. Whereas a class must be always complete.

You could have:

os.hpp
```
namespace os {
  ..
  // Return the default page size.
  static int    vm_page_size();
  .. // many more
}
```

os_linux.hpp
```
namespace os {
  namespace Linux {
    ...
     void print_process_memory_info(outputStream* st);
     void print_system_memory_info(outputStream* st);
   ...
  }
}
```

Compilation units just needing the generic part can include `os.hpp` and be done with it. os_linux.cpp would include both os.hpp and os_linux.hpp. 

As a bonus, we can remove those awkward injections of class definitions into the middle of class os. The os_xxx.hpp headers then would become standard headers, includable on their own.

We would loose the ability to make os:: functions private in the interface. But that can be solved by moving them into their own header. Or really taking a good look - why would private members have to appear in a public interface?

I realize that this would be a bigger change than what you have planned, but I think that this way would be the standard way to organize an interface like this, easier to understand and to maintain. What do you think?

**Comment by iklam** [comment]
I like the idea of using namespaces. I think the private methods in os.hpp can be moved to share/runtime/osImpl.hpp, which should be included only by the os*.cpp files. Let me try to do a prototype of this.

**Comment by dholmes-ora** [comment]
@iklam I thought we very recently rejected use of namespaces due to the visibility issue? 

Call me old fashioned by I much prefer classes for defining interfaces.

**Comment by tstuefe** [comment]
> 



> @iklam I thought we very recently rejected use of namespaces due to the visibility issue?
> 
> Call me old fashioned by I much prefer classes for defining interfaces.

We really should rethink this rule. I find it baffling that we include a many modern C++ features (e.g. template metaprogramming, which is often a mixed blessing) but still are avoiding simple namespace.

Had a read over the hotspot style guide. It cites advantages of AllStatic vs namespace:

```
1 Provides access control for members, which is unavailable with
namespaces.

2 Avoids [Argument Dependent Lookup][ADL] (ADL).

3 Closed for additional members.  Namespaces allow names to be added in
multiple contexts, making it harder to see the complete API.
```

I cannot comment off-hand about the ADL issue (2), but the other two points are actually advantages of namespaces, not disadvantages. At least when it comes to things like "os":

- I don't _want_ access control for members in a public interface. A public interface should be clean and minimal. Allowing private members in an interface tempts devs into adding private implementation details, which have no place in a public header. That leads to a lot of unnecessary include dependencies. Using namespace OTOH would be inductive for clean interface design.

- (3) is actually the biggest advantage. I can extend the os namespace without having to change the central header. Which, as I have argued before, leads to a much cleaner include file structure.

**Comment by dholmes-ora** [comment]
> - I don't _want_ access control for members in a public interface. A public interface should be clean and minimal. Allowing private members in an interface tempts devs into adding private implementation details, which have no place in a public header.

You are basically arguing against C++ class-based design there. C++ classes define both the public and non-public interfaces of a class. Header files include the full class definition. Ergo public header files have private implementation details.

**Comment by tstuefe** [comment]
> > * I don't _want_ access control for members in a public interface. A public interface should be clean and minimal. Allowing private members in an interface tempts devs into adding private implementation details, which have no place in a public header.
> 
> You are basically arguing against C++ class-based design there. C++ classes define both the public and non-public interfaces of a class. Header files include the full class definition. Ergo public header files have private implementation details.

No, I'm fine with C++ class based design. But AllStatic is just a way to group a bunch of global functions together. That has nothing to do with class-based design, these classes are never instantiated. That is just name scoping. Could have done the same with a common prefix.

**Comment by iklam** [comment]
> 1. Provides access control for members, which is unavailable with namespaces.
> 2. Avoids [Argument Dependent Lookup][ADL] (ADL).
> 3. Closed for additional members.  Namespaces allow names to be added in multiple contexts, making it harder to see the complete API.

I agree with Thomas that for the `os` interface, `#3` is actually the biggest disadvantage of using a class. `os` is a hodge-podge of porting interfaces. Usually no one cares what the "complete API" is (the only bad thing I can think of is that namespace allows declaration of new overloaded functions, which may make the code very hard to read; also see point `#2` below).

However, I agree `#1` and `#2` are advantages of using class.

For `#1`, even if we declare 'private' members in separate header files,  they can be easily be leaked when we have inline functions like:

```
/* public */ inline int os::getFoo() {
    return os::_private_foo;
}
```

Any file that includes `os_inline.hpp` will inadvertently see the private members. We can use naming convention to mark the members that shouldn't be accessed by outside code, but we can't use the C++ compiler to check for violations.

For `#2` (https://en.wikipedia.org/wiki/Argument-dependent_name_lookup), we can partially address it by forbidding the use of `using namespace os`. Again, this is not enforceable by the C++ compiler.

---

So without a clear consensus, I don't want to pursue the namespace solution.

But I do want to move `os::Linux` outside of os.hpp. Can we still entertain my os_linux_impl.hpp proposal for now?

Separately, we should split up the `os` class, like moving the string operations to a different header.

**Comment by dholmes-ora** [comment]
> Can we still entertain my os_linux_impl.hpp proposal for now?

The namespace discussion was just a sidebar and we're not going to go with namespaces. So that just brings things back to what you proposed above.

> My proposal is to remove all os- and platform- specific includes from os.hpp. The os class should include only functions that are usable from shared code.

 I don't like the original proposal and don't want to see it as an interim step until "something better" comes along. This is not a critical problem that must be solved today.

**Comment by iklam** [comment]
I've had some off-line discussion with David. He asked me an enlightening question --

> Why is os_linux.hpp almost empty after you proposal

This is when I realized -- `os_linux.hpp` should contain nothing except for the class `os::Linux`!

If I understood correctly, the design for the `os` class should be like this -- and most of the code already falls under this pattern:

- The `os` class should contain a platform-independent API.
- OS-specific implementation should be in either `os_<os>.cpp` or `os_<os>.inline.hpp`
- For example, `uses_stack_guard_pages()` is declared in `os.hpp`, and implemented on `os_linux.inline.hpp`.
- However, we a handful of deviations from this pattern. For example, `zero_page_read_protected()` is declared and implemented in `os_<os>.hpp`, but it's fairly to move it to conform to the above pattern.

The `os_<os>_<cpu>` files should follow similar rules. For example, there's no reason to declare `setup_fpu()` everywhere (13 times) when it can be declared once in `os.hpp`.

Over the years, I think the various os_xxx files were modified by authors who didn't understand the design, and we have lots of weird stuff

- `atomic_copy64()` should not be part of the `os` class, but rather a static function in files like `os_linux_zero.cpp`
- `workaround_expand_exec_shield_cs_limit()` should be a static function in `os_linux.cpp`

So my revised proposal is:

- Get rid of the "include a header file in the middle of the declaration of the os class" travesty
- `os.hpp` declares a platform-independent API
- `os_<os>.hpp` declares utility functions that are used by the OS-specific implementation of the `os` class. This header file should be included by only the files under `src/hotspot/<os>` or `src/hotspot/<os>_<cpu>`
- Platform-specific implementations should usually be in the `os_<os>.cpp` or `os_<os>_<cpu>.cpp`.
- When inlining is necessary for performance reasons, generic code should include `os.inline.hpp`, which in turn includes `os_<os>.hpp`, which includes `os_<os>_<cpu>.hpp`.

This way, `os::Linux` can happily live inside `os_linux.hpp`, and won't be included transitively by `os.hpp`

I have done a prototype here. Only Linux/x64 is working. I'll probably discover some problems when doing other os/cpus

https://github.com/openjdk/jdk/compare/master...iklam:jdk:xxtemp-normalize-os-hpp-inclusion

If people think this is worth pursuing, I will probably close this PR and open a new one, because the changes are much larger than I originally anticipated.

**Comment by tstuefe** [comment]
> So my revised proposal is:
> 
> * Get rid of the "include a header file in the middle of the declaration of the os class" travesty
> * `os.hpp` declares a platform-independent API
> * `os_<os>.hpp` declares utility functions that are used by the OS-specific implementation of the `os` class. This header file should be included by only the files under `src/hotspot/<os>` or `src/hotspot/<os>_<cpu>`
> * Platform-specific implementations should usually be in the `os_<os>.cpp` or `os_<os>_<cpu>.cpp`.
> * When inlining is necessary for performance reasons, generic code should include `os.inline.hpp`, which in turn includes `os_<os>.hpp`, which includes `os_<os>_<cpu>.hpp`.
> 
> This way, `os::Linux` can happily live inside `os_linux.hpp`, and won't be included transitively by `os.hpp`
> 
> I have done a prototype here. Only Linux/x64 is working. I'll probably discover some problems when doing other os/cpus
> 
> [master...iklam:jdk:xxtemp-normalize-os-hpp-inclusion](https://github.com/openjdk/jdk/compare/master...iklam:jdk:xxtemp-normalize-os-hpp-inclusion)
> 
> If people think this is worth pursuing, I will probably close this PR and open a new one, because the changes are much larger than I originally anticipated.

I like everything about this proposal :-)

os.hpp and friends have a long history, a lot of ports started by copy-pasting parts around, and its common property without a clear maintainer. That could explain its current state.

One small addition, functions that are clearly both declared and used within os_xxx.cpp and nowhere else I would like to have removed from headers completely and converted to local statics.

Cheers, Thomas

**Pull request closed without merging**
