### PR TITLE
8261728: SimpleDateFormat should link to DateTimeFormatter

### PR DESCRIPTION
**Pull request by naotoj**
Please review this simple doc fix. A CSR will be filed accordingly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261728](https://bugs.openjdk.java.net/browse/JDK-8261728): SimpleDateFormat should link to DateTimeFormatter

### Reviewers
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2616/head:pull/2616`
`$ git checkout pull/2616`

### CODE REVIEW

**Review by bplb — APPROVED** [review]
LGTM

**Review by RogerRiggs — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]
Hi Naoto,

Looks good.  

Any thoughts to making the new wording stick out more perhaps via a something like  "Note: Consider...." and bolding "Note:" 


Not sure if it is @apiNote worthy but I guess that is an option also?

**Comment by naotoj** [comment]
> Not sure if it is @APinote worthy but I guess that is an option also?

Good point. Modified.

**Review by bplb — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
