### PR TITLE
8253757: Add LLVM-based backend for hsdis

### PR DESCRIPTION
**Pull request by magicus**
This patch expands the newly added system for hsdis backends to include LLVM.

The actual code in hsdis-llvm.cpp is based heavily on the work by @luhenry, as published in the never integrated PR https://github.com/openjdk/jdk/pull/392. (I have basically just ripped out the binutils-based part of it.)

Unfortunately I have not been able to make this work properly on Windows. With some additional flags I made it compile without complaints, but it caused hotspot to segfault in `LoadLibrary` (!) in `os::dll_load` when I tried to load the library. This is somewhat ironic, since the initial implementation was created by Ludovic for the very purpose of using it on Windows.

The lack of Windows support in this patch does not mean it is impossible to get it to work, just that I need to co-operate with someone who has more experience of compiling LLVM on Windows, and/or are more eager to get this combination to work.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253757](https://bugs.openjdk.java.net/browse/JDK-8253757): Add LLVM-based backend for hsdis

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to effac9b87ecb3cdc8d3d149b9dcd72ee1ea88fec
 * [Ludovic Henry](https://openjdk.java.net/census#luhenry) (@luhenry - Author) ⚠️ Review applies to effac9b87ecb3cdc8d3d149b9dcd72ee1ea88fec

### Contributors
 * Magnus Ihse Bursie `<ihse@openjdk.org>`
 * Ludovic Henry `<luhenry@openjdk.org>`
 * Nick Gasson `<ngasson@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5920/head:pull/5920` \
`$ git checkout pull/5920`

Update a local copy of the PR: \
`$ git checkout pull/5920` \
`$ git pull https://git.openjdk.java.net/jdk pull/5920/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5920`

View PR using the GUI difftool: \
`$ git pr show -t 5920`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5920.diff">https://git.openjdk.java.net/jdk/pull/5920.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
In my experience the output of llvm-config is also not usable. I think the output also depends on the toolchain you use to build llvm FWIW. The output of my locally built llvm-config does contain the MSVC flags, but the paths it points to are incorrect (all pointing to the build directory, instead of the package install location).

I have a patch here that gets me a working hsdis based on the llvm package I built manually using MSVC (the official package doesn't seem to contain the needed header files): https://github.com/openjdk/jdk/compare/pr/5920...JornVernee:hsdis_llvm_windows

(The only issue currently is that the code I used to filter out the incorrect `-I` flags from what llvm-config gives me doesn't seem to work, though the build still passes).

I built llvm using something like this (according to my notes):

```
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
mkdir build_llvm
cd build_llvm
cmake ../llvm -D"LLVM_TARGETS_TO_BUILD:STRING=X86" -D"CMAKE_BUILD_TYPE:STRING=Release" -D"CMAKE_INSTALL_PREFIX=install_local" -A x64 -T host=x64
cmake --build . --config Release --target install
```

This then uses MSVC to build me an llvm 'package' in `build_llvm/install_local`, which I then point to using `--with-lllvm`.

The only other issue I had is that `install-hsdis` only copies the library to the exploded JDK, so I manually copy it to `images/jdk/bin/server` afterwards.

HTH

**Comment by theRealAph** [comment]
So I figured out how to build it with `make build-hsdis`. The instructions need to be fixed.

Two problems: firstly, the library seems to be built with the wrong name, so the runtime doesn't find it. I had to use
`ln -sf ~/lib/libhsdis.dylib ~/lib/hsdis-aarch64.dylib`
to get it to work.

More severely, the disassembly is truncated, so lots of stuff doesn't work. The binutils-based hsdis prints
```

 0x00000001105665b4:   stp     wzr, wzr, [x20, #60]        ;*putfield preCounterBlock {reexecute=0 rethrow=0 return_oop=0}
                                                            ; - com.sun.crypto.provider.GaloisCounterMode$GCMEngine::<init>@80 (line 673)
                                                            ; - com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt::<init>@8 (line 1346)
                                                            ; - com.sun.crypto.provider.GaloisCounterMode::checkInit@60 (line 329)
 ;; B6: #       out( B242 B7 ) <- in( B192 B5 )  Freq: 0.999999
  0x00000001105665b8:   cbnz    x21, 0x00000001105665c8
 ;; null oop passed to encode_heap_oop_not_null2
  0x00000001105665bc:   dcps1   #0xdeae
  0x00000001105665c0:   .inst   0x082adca6 ; undefined
  0x00000001105665c4:   udf     #1
  0x00000001105665c8:   lsr     x10, x21, #3                ;*invokevirtual getLongUnaligned {reexecute=0 rethrow=0 return_oop=0}
                                                            ; - java.lang.invoke.VarHandleByteArrayAsLongs$ArrayHandle::get@32 (line 115)
   ... lots more
```

but the llvm-based one stops here:

```
  0x000000010ed79034:           stp     wzr, wzr, [x20, #0x3c];*putfield preCounterBlock {reexecute=0 rethrow=0 return_oop=0}
                                                            ; - com.sun.crypto.provider.GaloisCounterMode$GCMEngine::<init>@80 (line 673)
                                                            ; - com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt::<init>@8 (line 1346)
                                                            ; - com.sun.crypto.provider.GaloisCounterMode::checkInit@60 (line 329)
 ;; B6: #       out( B242 B7 ) <- in( B192 B5 )  Freq: 0.999999
  0x000000010ed79038:           cbnz    x21, #0x10
 ;; null oop passed to encode_heap_oop_not_null2
  0x000000010ed7903c:           dcps1   #0xdeae
  0x000000010ed79040:   --------------------------------------------------------------------------------
[/Disassembly]

```

I think it's giving up as soon as it sees something it doesn't recognize, so it's pretty much useless.

In addition, even when it does work the LLVM disassembly is pretty poor. For example, the unverified entry point looks like

```
  0x000000010ed78f80:           ldr     w8, [x1, #0x8]
  0x000000010ed78f84:           cmp     w9, w8
  0x000000010ed78f88:           b.eq    #0x10
  0x000000010ed78f8c:           adrp    x8, #-128524288     ;   {runtime_call ic_miss_stub}
  0x000000010ed78f90:           add     x8, x8, #0x1c0
  0x000000010ed78f94:           br      x8

```
instead of

```
  0x0000000110566500:   ldr     w8, [x1, #8]
  0x0000000110566504:   cmp     w9, w8
  0x0000000110566508:   b.eq    0x0000000110566518  // b.none
  0x000000011056650c:   adrp    x8, 0x0000000108ae6000      ;   {runtime_call ic_miss_stub}
  0x0000000110566510:   add     x8, x8, #0x1c0
  0x0000000110566514:   br      x8

```
Sure, it's good to have a choice, but the LLVM-based hsdis doesn't look to me like a serious alternative for professional work.

**Comment by nick-arm** [comment]
The problem is `LLVMDisasmInstruction()` returns zero size as soon as it hits an instruction it doesn't understand. Something kludgy like this works:

```diff
diff --git a/src/utils/hsdis/llvm/hsdis-llvm.cpp b/src/utils/hsdis/llvm/hsdis-llvm.cpp
index a491082f14fa..3c50ee8e3b40 100644
--- a/src/utils/hsdis/llvm/hsdis-llvm.cpp
+++ b/src/utils/hsdis/llvm/hsdis-llvm.cpp
@@ -307,6 +307,10 @@ class hsdis_backend : public hsdis_backend_base {
   virtual size_t decode_instruction(uintptr_t p, uintptr_t start, uintptr_t end) {
     char buf[128];
     size_t size = LLVMDisasmInstruction(_dcontext, (uint8_t*)p, (uint64_t)(end - start), (uint64_t)p, buf, sizeof(buf));
+    if (size == 0 && end - start >= 4) {
+      snprintf(buf, sizeof(buf), "\t.word\t#0x%08x", *(uint32_t*)p);
+      size = 4;
+    }
     if (size > 0) {
       (*_printf_callback)(_printf_stream, "%s", buf);
     }
```

```
  0x0000ffff94685454:           br      x8
  0x0000ffff94685458:           .word   #0x93e3f4c0
  0x0000ffff9468545c:           udf     #0xffff
[Exception Handler]
  0x0000ffff94685460:           adrp    x8, #-0x795000      ;   {runtime_call handle_exception_from_callee Runtime1 stub}
```

**Comment by magicus** [comment]
@nick-arm That'd introduce a new dependency to Capstone. ;-)

But you're suggestion is excellent -- in fact, I have a branch in my personal fork that builds hsdis with Capstone as backend. I just scheduled for myself to submit this PR first. (Which maybe was a mistake; it was obviously more tricky to get right than I anticipated.) I might reconsider that choice and let this PR wait until I've pushed the Capstone backend first, instead.

**Comment by magicus** [comment]
Yeah bot, I'm still working on it.

**Comment by swesonga** [comment]
@magicus @JornVernee Thank you for starting this PR and for the notes on the Windows changes. I'm trying them out on macOS and Windows.

@theRealAph I'm not as familiar with the mac platform. Did you need to do anything special to address these errors? I was adding -L/opt/homebrew/opt/llvm/lib to the HSDIS_LDFLAGS.

```Undefined symbols for architecture arm64:
  "_LLVMCreateDisasm", referenced from:
      hsdis_backend::hsdis_backend(unsigned long, unsigned long, unsigned char*, unsigned long, void* (*)(void*, char const*, void*), void*, int (*)(void*, char const*, ...), void*, char const*, int) in hsdis-llvm.o
  "_LLVMDisasmDispose", referenced from:
      hsdis_backend::~hsdis_backend() in hsdis-llvm.o
...
ld: symbol(s) not found for architecture arm64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by swesonga** [comment]
> @magicus @JornVernee Thank you for starting this PR and for the notes on the Windows changes. I'm trying them out on macOS and Windows.
> 
> @theRealAph I'm not as familiar with the mac platform. Did you need to do anything special to address these errors? I was adding -L/opt/homebrew/opt/llvm/lib to the HSDIS_LDFLAGS.
> 
> ```
>   "_LLVMCreateDisasm", referenced from:
>       hsdis_backend::hsdis_backend(unsigned long, unsigned long, unsigned char*, unsigned long, void* (*)(void*, char const*, void*), void*, int (*)(void*, char const*, ...), void*, char const*, int) in hsdis-llvm.o
>   "_LLVMDisasmDispose", referenced from:
>       hsdis_backend::~hsdis_backend() in hsdis-llvm.o
> ...
> ld: symbol(s) not found for architecture arm64
> clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Turns out I just needed to add /opt/homebrew/opt/llvm/bin to my PATH. I can now use --with-hsdis=llvm.

**Comment by magicus** [comment]
Yes bot, thank you for the reminder.

**Comment by magicus** [comment]
This PR has just gotten too messy. :-( I'll close this one for now, focus on getting the (much simpler) Capstone backend integrated, and then I can come back and revisit this functionality, but in a fresh new PR.

**Pull request closed without merging**
