### PR TITLE
8264359: Compiler directives should enable DebugNonSafepoints when PrintAssembly is requested

### PR DESCRIPTION
**Pull request by neliasso**
DebugNonSafepoints should be set when PrintAssembly is requested. This only happened for compile commands but not for compiler directives. This PR moves the check to compiler directives - that code path is used for both directives and commands. I am leaving the check and update in arguments.cpp - there might be some need for using flag PrintAssembly for stubs or wrappers, in a code path that doesn't use commands or directives.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264359](https://bugs.openjdk.java.net/browse/JDK-8264359): Compiler directives should enable DebugNonSafepoints when PrintAssembly is requested

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3316/head:pull/3316` \
`$ git checkout pull/3316`

Update a local copy of the PR: \
`$ git checkout pull/3316` \
`$ git pull https://git.openjdk.java.net/jdk pull/3316/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3316`

View PR using the GUI difftool: \
`$ git pr show -t 3316`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3316.diff">https://git.openjdk.java.net/jdk/pull/3316.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by neliasso** [comment]
Thanks for the reviews Vladimir and Tobias!

**Pull request closed without merging**
