### PR TITLE
8284075: Optimize paired floorDiv and floorMod calculations in java.time

### PR DESCRIPTION
**Pull request by cl4es**
A common arithmetic pattern in java.time is to calculate both `Math.floorDiv` and `floorMod` for the same arguments. In such cases `floorMod` can be calculated more efficiently using the result of `floorDiv`.

From the javadoc for `floorMod`, the relationship is such that:

```java
floorDiv(x, y) * y + floorMod(x, y) == x
```
or:
```java
floorMod(x, y) == x - floorDiv(x, y) * y;
```

Simplifying like so bring a 15% or so speed-up on `GetYearBench`, which benefits from the changes `Instant::ofEpochMilli` and `LocalDateTime::ofEpochSecond`:

```
Benchmark                                                   Mode  Cnt       Score       Error   Units
GetYearBench.getYearFromMillisZoneOffset                   thrpt    5      34.522 ±     0.054  ops/ms
GetYearBench.getYearFromMillisZoneRegion                   thrpt    5       9.984 ±     0.151  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized         thrpt    5      34.844 ±     0.281  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC                thrpt    5      34.517 ±     0.007  ops/ms
```

```
Benchmark                                                   Mode  Cnt       Score       Error   Units
GetYearBench.getYearFromMillisZoneOffset                   thrpt    5      39.709 ±     0.048  ops/ms
GetYearBench.getYearFromMillisZoneRegion                   thrpt    5      11.703 ±     0.510  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized         thrpt    5      39.612 ±     0.023  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC                thrpt    5      39.511 ±     0.050  ops/ms
```

Testing: java.time tests locally, tier1+2 ongoing

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8284075](https://bugs.openjdk.java.net/browse/JDK-8284075): Optimize paired floorDiv and floorMod calculations in java.time

### Reviewers
 * [Stephen Colebourne](https://openjdk.java.net/census#scolebourne) (@jodastephen - Author) ⚠️ Review applies to 37b33695e529b080faa75c2a0b87dd1829f8e5d8

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8056/head:pull/8056` \
`$ git checkout pull/8056`

Update a local copy of the PR: \
`$ git checkout pull/8056` \
`$ git pull https://git.openjdk.java.net/jdk pull/8056/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8056`

View PR using the GUI difftool: \
`$ git pr show -t 8056`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8056.diff">https://git.openjdk.java.net/jdk/pull/8056.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
Hi @merykitty - thanks for taking a look. I tried your suggested ideas but haven't been able to make operation pair any faster. I suspect we would need a bit more JIT magic than making them look similar.

**Review by jodastephen — APPROVED** [review]
Seems reasonable to me

**Comment by merykitty** [comment]
@cl4es  I think I know why, in these cases, the divisors are constants so `a % b` is transformed into `a - b * (a / b)` anyway (and the division is transformed further). So my proposal is more or less the same thing as the operations today already. Thanks.

**Comment by theRealAph** [comment]
I'm not seeing a big difference, at least on AArch64. There is no divide instruction anywhere in the loop of `GetYearBench_getYearFromMillisZoneXXX_jmhTest`. To perform the division and the mod, we do a `mul` and a `mulh`, and a couple of shifts. The multiplication needed by the `%` and the `/` is only done once.

Before

```
Benchmark                                            Mode  Cnt   Score   Error   Units
GetYearBench.getYearFromMillisZoneOffset            thrpt    5  82.795 ± 0.038  ops/ms
GetYearBench.getYearFromMillisZoneRegion            thrpt    5  23.354 ± 0.030  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized  thrpt    5  82.946 ± 0.043  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC         thrpt    5  82.263 ± 0.029  ops/ms
```
After

```
Benchmark                                            Mode  Cnt   Score   Error   Units
GetYearBench.getYearFromMillisZoneOffset            thrpt    5  84.649 ± 0.028  ops/ms
GetYearBench.getYearFromMillisZoneRegion            thrpt    5  24.183 ± 0.031  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized  thrpt    5  84.220 ± 0.044  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC         thrpt    5  83.794 ± 0.975  ops/ms
```

I think this is almost in the noise, really

**Comment by cl4es** [comment]
@theRealAph the numbers I got was from AArch64 so I went back and double-checked. I think you're right and that I had merged in #8039 in my experiment branch but not my baseline. D'oh!

Baseline:
```
Benchmark                                            Mode  Cnt   Score   Error   Units
GetYearBench.getYearFromMillisZoneOffset            thrpt    5  39.719 ? 0.008  ops/ms
GetYearBench.getYearFromMillisZoneRegion            thrpt    5  11.658 ? 0.075  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized  thrpt    5  39.616 ? 0.026  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC         thrpt    5  39.505 ? 0.142  ops/ms
```
Experiment:
```
Benchmark                                            Mode  Cnt   Score   Error   Units
GetYearBench.getYearFromMillisZoneOffset            thrpt    5  39.725 ? 0.050  ops/ms
GetYearBench.getYearFromMillisZoneRegion            thrpt    5  11.806 ? 0.017  ops/ms
GetYearBench.getYearFromMillisZoneRegionNormalized  thrpt    5  39.692 ? 0.265  ops/ms
GetYearBench.getYearFromMillisZoneRegionUTC         thrpt    5  39.661 ? 0.093  ops/ms
```

I'll withdraw this PR.

**Pull request closed without merging**
