### PR TITLE
8343070: Enable is_trace_align_vector when TraceSuperWord is set

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this simple patch?
Currently, in SuperWord::filter_packs_for_alignment(), there is some log not turned on when TraceSuperWord is set, but I think it should, as it's more convenient for users to debug.
Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8343070](https://bugs.openjdk.org/browse/JDK-8343070): Enable is_trace_align_vector when TraceSuperWord is set (**Enhancement** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21715/head:pull/21715` \
`$ git checkout pull/21715`

Update a local copy of the PR: \
`$ git checkout pull/21715` \
`$ git pull https://git.openjdk.org/jdk.git pull/21715/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21715`

View PR using the GUI difftool: \
`$ git pr show -t 21715`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21715.diff">https://git.openjdk.org/jdk/pull/21715.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21715#issuecomment-2438028619)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me but @eme64 should have a look at this as well.

/reviewers 2

**Comment by eme64** [comment]
@Hamlin-Li There is a lot of tracing in SuperWord. You have very fine-grained control with `TraceAutoVectorization`, and in my opinion `TraceSuperWord` should just be a "summary", and quickly readable to get a hint. You can use `-XX:CompileCommand=TraceAutoVectorization,*::*,ALIGN_VECTOR`.

If you do think we should add the align vector tracing into `TraceSuperWord`, then I would like to hear from you what other tracing you would add, and what not. What do you think?

**Comment by eme64** [comment]
BTW I'm not saying that tracing is handled optimally. I currently just have it working. And maybe eventually we can remove `TraceSuperWord` and only use `TraceAutoVectorization`. The grouping of tracing flags/tags can surely be adjusted.

**Comment by eme64** [comment]
Ah, one more thing. I try to keep `SW_INFO` and `TraceSuperWord` in sync. So if we do decide to add `ALIGN_VECTOR` to `TraceSuperWord`, we should also add it to `SW_INFO`.

**Comment by Hamlin-Li** [comment]
> Looks reasonable to me but @eme64 should have a look at this as well.
> 
> /reviewers 2

Thanks @TobiHartmann !

**Comment by Hamlin-Li** [comment]
Thanks @eme64 for discussion! :)
I'm on vacation, will get back to you when I'm back later.

**Comment by Hamlin-Li** [comment]
@eme64 Thanks for the information.
At first my thought was to make it easier to debug SLP process, as I observed some tests failure on riscv, but it won't print out the detailed failure reason. This pr made it easy to do so, but at the same time also introduce some verbose information unconditionally, which is not useful when there is no failure/rejection or when user don't care about it.
I don't find another more reasonable way to modify current log in SLP, I'll use `-XX:CompileCommand=TraceAutoVectorization,*::*,ALIGN_VECTOR` instead, and close this pr.

**Pull request closed without merging**
