### PR TITLE
8277346: ProblemList 7 serviceability/sa tests on macosx-x64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
A trivial fix to ProblemList 7 serviceability/sa tests on macosx-x64.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8277346](https://bugs.openjdk.java.net/browse/JDK-8277346): ProblemList 7 serviceability/sa tests on macosx-x64
 * [JDK-8277351](https://bugs.openjdk.java.net/browse/JDK-8277351): ProblemList runtime/jni/checked/TestPrimitiveArrayCriticalWithBadParam.java on macosx-x64

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6438/head:pull/6438` \
`$ git checkout pull/6438`

Update a local copy of the PR: \
`$ git checkout pull/6438` \
`$ git pull https://git.openjdk.java.net/jdk pull/6438/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6438`

View PR using the GUI difftool: \
`$ git pr show -t 6438`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6438.diff">https://git.openjdk.java.net/jdk/pull/6438.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm and trivial

**Review by bplb — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@tschatzl and @bplb - Thanks for the fast review!

/integrate

**Pull request closed without merging**
