### PR TITLE
8269428: java/util/concurrent/ConcurrentHashMap/ToArray.java timed out

### PR DESCRIPTION
**Pull request by viktorklang-ora**
As an intermediate fix to the test, switching to explicit usage of an ExecutorService seems to do the trick to make this test reliably pass.

With that said, this test (CHM::ToArray.java) seems to trigger an issue in ForkJoinPool, so that would need to be fixed separately.

Tagging @DougLea as an FYI. :)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8269428](https://bugs.openjdk.org/browse/JDK-8269428): java/util/concurrent/ConcurrentHashMap/ToArray.java timed out (**Bug** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18023/head:pull/18023` \
`$ git checkout pull/18023`

Update a local copy of the PR: \
`$ git checkout pull/18023` \
`$ git pull https://git.openjdk.org/jdk.git pull/18023/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18023`

View PR using the GUI difftool: \
`$ git pr show -t 18023`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18023.diff">https://git.openjdk.org/jdk/pull/18023.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18023#issuecomment-1966256843)

### CODE REVIEW

**Comment by DougLea** [comment]
This change seems OK in  terms of avoiding failures due to unrelated FJP and/or GC issues (for which it may be better to develop a separate test).

**Review by jaikiran — APPROVED** [review]
The intention of this `ToArray` as noted in the summary of this test is to verify the thread safety of the `toArray()` methods of collection views. As noted in the JBS issue, the reason why this test keeps timing out intermittently appears to be an issue in the `ForkJoinPool` and thus those timeouts aren't exposing any issues within `toArray()` implementations itself. So it seems fine that we are switching over to using a thread pool that doesn't exhibit those issues.

This proposed change looks good to me. Since Doug has already approved this too, I will go ahead and officially mark this as reviewed.

Before integrating, please update the copyright year on this file.

**Comment by jaikiran** [comment]
Hello Viktor, Doug,

> failures due to unrelated FJP and/or GC issues (for which it may be better to develop a separate test).

Since the test has (unintentionally) exposed an issue within the ForkJoinPool, should we open a separate issue to track that (or do we already have one)?

**Comment by viktorklang-ora** [comment]
Thanks @jaikiran, I have issued another commit: updating the copyright year

**Review by jaikiran — APPROVED** [review]

**Comment by viktorklang-ora** [comment]
@jaikiran I suspect that we might already have a JBS issue which relates to the FJP bug itself, but I'll have to go find it first. I'll sync with Doug next week.

**Comment by jaikiran** [comment]
> @jaikiran I suspect that we might already have a JBS issue which relates to the FJP bug itself, but I'll have to go find it first. I'll sync with Doug next week.

Thank you - that sounds fine to me.

**Pull request closed without merging**
