### PR TITLE
8322880: Eliminate -Wparentheses warnings in arm32 code

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to eliminate some -Wparentheses warnings. In most
cases, this involved simply adding a few parentheses to make some implicit
operator precedence explicit. Exceptions are:

In the clear_array instruct, removed extraneous parens in a declaration:
`Label(loop);` => `Label loop;`

In NativeMovConstReg::set_data, changed `&` => `&&`.  This is conceptually a
bug fix, but the old code "accidentally" worked.

Testing: Local (linux-x64) cross-build for linux-arm32.  Also ran GHA with
-Wparentheses enabled along with this and other changes needed to make that
work.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322880](https://bugs.openjdk.org/browse/JDK-8322880): Eliminate -Wparentheses warnings in arm32 code (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17300/head:pull/17300` \
`$ git checkout pull/17300`

Update a local copy of the PR: \
`$ git checkout pull/17300` \
`$ git pull https://git.openjdk.org/jdk.git pull/17300/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17300`

View PR using the GUI difftool: \
`$ git pr show -t 17300`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17300.diff">https://git.openjdk.org/jdk/pull/17300.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17300#issuecomment-1880651363)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks reasonable.

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks

**Comment by kimbarrett** [comment]
Thanks for reviews, @dholmes-ora and @shipilev .

**Pull request closed without merging**
