### PR TITLE
8316273: JDK-8315818 broke JVMCIPrintProperties on libgraal

### PR DESCRIPTION
**Pull request by dougxc**
This PR prevents the possibility for `JVMCIPrintProperties` to emit output more than once. That possibility was introduced by [JDK-8315818](https://bugs.openjdk.org/browse/JDK-8315818) by allowing JVMCI initialization to happen earlier on a compiler thread that races with the main thread in terms of JVMCI initialization.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316273](https://bugs.openjdk.org/browse/JDK-8316273): JDK-8315818 broke JVMCIPrintProperties on libgraal (**Bug** - P5)

### Reviewers
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15739/head:pull/15739` \
`$ git checkout pull/15739`

Update a local copy of the PR: \
`$ git checkout pull/15739` \
`$ git pull https://git.openjdk.org/jdk.git pull/15739/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15739`

View PR using the GUI difftool: \
`$ git pr show -t 15739`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15739.diff">https://git.openjdk.org/jdk/pull/15739.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15739#issuecomment-1719317254)

### CODE REVIEW

**Review by tkrodriguez — APPROVED** [review]
Maybe there's no need to separate init phases any more?

**Comment by dougxc** [comment]
> Maybe there's no need to separate init phases any more?

I think you're right. It was only split up for Graal in the first place: https://bugs.openjdk.org/browse/JDK-8200230

**Review by vnkozlov — APPROVED** [review]
Looks good to me.

**Review by tkrodriguez — APPROVED** [review]
New version looks good.

**Comment by dougxc** [comment]
Thanks for the reviews!

/integrate

**Pull request closed without merging**
