### PR TITLE
8284404: Too aggressive sweeping with Loom

### PR DESCRIPTION
**Pull request by fisk**
The normal sweeping heuristics trigger sweeping whenever 0.5% of the reserved code cache could have died. Normally that is fine, but with loom such sweeping requires a full GC cycle, as stacks can now be in the Java heap as well. In that context, 0.5% does seem to be a bit too trigger happy. So this patch adjusts that default when using loom to 10x higher.
If you run something like jython which spins up a lot of code, it unsurprisingly triggers a lot less GCs due to code cache pressure.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8284404](https://bugs.openjdk.org/browse/JDK-8284404): Too aggressive sweeping with Loom

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [461f8a30](https://git.openjdk.org/jdk/pull/8673/files/461f8a3002ce2718698a43d5bca13fdfbd9d9879)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/8673/head:pull/8673` \
`$ git checkout pull/8673`

Update a local copy of the PR: \
`$ git checkout pull/8673` \
`$ git pull https://git.openjdk.org/jdk pull/8673/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8673`

View PR using the GUI difftool: \
`$ git pr show -t 8673`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/8673.diff">https://git.openjdk.org/jdk/pull/8673.diff</a>

</details>

### CODE REVIEW

**Comment by vnkozlov** [comment]
Did you run our regular performance testing with loom to see how this change affect performance?
Why 10x and not other number?

**Comment by fisk** [comment]
> Did you run our regular performance testing with loom to see how this change affect performance?
> 
> Why 10x and not other number?

I tried to find a problematic workload where tis is a real issue and and manually found that jython compiles a lot of methods yielding a lot of sweeper triggered GCs. This new threshold remedied the problem so that only a few were triggered.
I have however not run the wider perf suite. I can do that though.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Thank you for explaining where the number came from.

I think `SweeperThreshold` should still be limited to some reasonable number. Otherwise this code may set it to `1000.0` (flag's max allowed value is 100.).

**Comment by fisk** [comment]
@vnkozlov Is your concern that a user explicitly overrides the default to a value that ends up not being good? If so, I'm not sure why we would be in the business of preventing the user from shooting itself in the foot and guessing what the user really wanted here. Maybe I missed something.

**Comment by fisk** [comment]
> > @vnkozlov Is your concern that a user explicitly overrides the default to a value that ends up not being good? If so, I'm not sure why we would be in the business of preventing the user from shooting itself in the foot and guessing what the user really wanted here. Maybe I missed something.
> 
> 
> 
> Yes, it was my concern which was unjustifiable because I missed that this code is guarded by `FLAG_IS_DEFAULT(SweeperThreshold)`. So you simply set `SweeperThreshold` to 5% (default is 0.5) which is fine.

Okay great - thanks for the review!

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. A comment explaining the justification wouldn't hurt.

**Comment by TobiHartmann** [comment]
@fisk This PR needs to be re-submitted for the JDK 19 repository.

**Review by TobiHartmann — APPROVED** [review]

**Pull request closed without merging**
