### PR TITLE
8291569: Consider removing JNI checks for signals SIGPIPE and SIGXFSZ

### PR DESCRIPTION
**Pull request by dholmes-ora**
Simple enhancement to skip checking of the handlers for SIGPIPE and SIGXFSZ as we really don't care if they change, and we expect that they can.

The signal checking code might seem to have a redundancy as we skip these signals in two places, but the primary use of the `do_check_signal_periodically` array is to allow for only issuing one warning per signal. I could have skipped them in either place and get the same effect but it seemed inappropriate to set the array entry and not do the check; and vice-versa.

Testing: just basic sanity test tiers 1-3. This doesn't affect any application behaviour.

There are no regression tests in this specific area and it did not seem worth the effort creating one just for this.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291569](https://bugs.openjdk.org/browse/JDK-8291569): Consider removing JNI checks for signals SIGPIPE and SIGXFSZ

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12062/head:pull/12062` \
`$ git checkout pull/12062`

Update a local copy of the PR: \
`$ git checkout pull/12062` \
`$ git pull https://git.openjdk.org/jdk pull/12062/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12062`

View PR using the GUI difftool: \
`$ git pr show -t 12062`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12062.diff">https://git.openjdk.org/jdk/pull/12062.diff</a>

</details>

### CODE REVIEW

**Comment by robehn** [comment]
Hi David, I'm a bit confused here.

Why do we bother with setting up a single handler for i.e. SIGPIPE at all then?
`set_signal_handler(SIGPIPE);`

If the user sets a no-op signal handler for SIGPIPE, without UseSignalChaining, before start of VM we seem to fatal out ?
But if the user sets a no-op signal handler for SIGPIPE after start of VM we do not care?

Isn't this a bit inconsistent?

Shouldn't we just remove SIGPIPE/SIGXFSZ completely if we actually don't care?

**Comment by dholmes-ora** [comment]
The reason the VM handles (and ignores) SIGPIPE is because it can be raised by the OS when a socket connection is terminated. This would crash the VM unless we handle the signal - ref https://bugs.openjdk.org/browse/JDK-4630104

**Comment by robehn** [comment]
Correct me if I'm wrong, if we:
1: Start VM
2: Install our signal handler (which 'ignores')
3: A user installs their handler (we do not do periodic check of SIGPIPE)
4: A user removes theirs handler
5: We get SIGPIPE and crash ??

If we need to either sig ignore or our ignore handler shouldn't we do periodic check?

**Review by tstuefe — APPROVED** [review]
Seems reasonable.

**Comment by robehn** [comment]
I'm wondering if the user have communicated this to the VM by using the proper option, but are starting without the signal handlers yet installed.
E.g.
The user starts the VM and at later stage while doing additional class loading a dynamic library is loaded which installs SIGPIPE handler. (it can also be JVM TI agent or so which is later unloaded)
When this code no longer is relevant the user calls down to that library to shutdown, it thus removes it's signal handlers.

I have not seen that you must install your handler before CreateVM, but maybe you must?
Again a bit confused by this, maybe I understand it wrong.

**Comment by tstuefe** [comment]
> I'm wondering if the user have communicated this to the VM by using the proper option, but are starting without the signal handlers yet installed. E.g. The user starts the VM and at later stage while doing additional class loading a dynamic library is loaded which installs SIGPIPE handler. (it can also be JVM TI agent or so which is later unloaded) When this code no longer is relevant the user calls down to that library to shutdown, it thus removes it's signal handlers.
> 
> I have not seen that you must install your handler before CreateVM, but maybe you must? Again a bit confused by this, maybe I understand it wrong.

To my understanding, this scenario should work if signal handling is set up correctly and completely (including pre-loading libjsig).

There are two phases:
- user handler installed before hotspot signal init: we store the user handler in hotspot for chaining.
- user handler installed after hotspot signal init: if the user uses libjsig correctly (https://docs.oracle.com/javase/8/docs/technotes/guides/vm/signal-chaining.html) it will have been preloaded and we will intercept the sigaction() call. We then leave our own signal handler installed but store the user handler in the libjsig.

When we process a signal and signal chaining is on, we call the chained handler, with the one from the libjsig having precedence - https://github.com/openjdk/jdk/blob/1a6ac606cd430d86acede05e9caeaddec57c50d0/src/hotspot/os/posix/signals_posix.cpp#L381-L394

**Comment by robehn** [comment]
Now pieces fall into place. I totally forgot about libjsig.

Thank you for your patience :) !

Seems reasonable to me also!

**Review by robehn — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the discussion and reviews @robehn  and @tstuefe 

> But setting a SIGPIPE handler - or temporarily disabling it - without signal chaining seems to be such a common pattern that we now remove the warning instead. We basically throw the hands in the air and give up.

Given changing the handler is somewhat expected/normal then issuing an alarming warning only annoys people who expect to be able to run JNI-warning free.

**Comment by dholmes-ora** [comment]
And just to be clear @robehn the scenario we are dealing with is the case where libjsig is not actually used - as we would not install the user's handler in that case we would chain to it. See:

https://bugs.openjdk.org/browse/JDK-8292054

for the kind of scenario (though for different signals). So we do rely on the third-party code doing the right thing by taking over the handler temporarily and then restoring it - if they don't then yes we can crash.

So that said I'm now second-guessing the approach here:
- pro: doesn't issue a warning for a well-behaved third-party library that messes with the handler
- con:  doesn't issue a warning for a badly-behaved third-party library that messes with the handler and triggers a crash

**Comment by tstuefe** [comment]
> And just to be clear @robehn the scenario we are dealing with is the case where libjsig is not actually used - as we would not install the user's handler in that case we would chain to it. See:
> 
> https://bugs.openjdk.org/browse/JDK-8292054
> 
> for the kind of scenario (though for different signals). So we do rely on the third-party code doing the right thing by taking over the handler temporarily and then restoring it - if they don't then yes we can crash.
> 
> So that said I'm now second-guessing the approach here:
> 
>     * pro: doesn't issue a warning for a well-behaved third-party library that messes with the handler
> 
>     * con:  doesn't issue a warning for a badly-behaved third-party library that messes with the handler and triggers a crash

I'm fine with both approaches.

**Comment by robehn** [comment]
Since [Oracles troubleshooting guide](https://docs.oracle.com/en/java/javase/19/troubleshoot/handle-signals-and-exceptions.html) guides howto get libjsig working and it's included in our builds, I would consider it a standard tool to be used in these situations.

I'm fine with both also.

**Comment by dholmes-ora** [comment]
Okay I will proceed as-is then. Thanks.

/integrate

**Pull request closed without merging**
