### PR TITLE
8271579: G1: Move copy before CAS in do_copy_to_survivor_space

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Propose to move copy before CAS in do_copy_to_survivor_space, as we found this will improve G1 performance. Specjbb shows 3.7% in critical on aarch64, no change in max.

After this change copy_to_survivor in G1 is also aligned with PS's copy_to_survivor.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8271579](https://bugs.openjdk.java.net/browse/JDK-8271579): G1: Move copy before CAS in do_copy_to_survivor_space
 * [JDK-8272070](https://bugs.openjdk.java.net/browse/JDK-8272070): G1: Simplify age calculation after JDK-8271579

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 997fdc190d996b14a0b0714dc69e817a9a6944db
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer) ⚠️ Review applies to 997fdc190d996b14a0b0714dc69e817a9a6944db

### Contributors
 * shoubing ma `<mashoubing1@huawei.com>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4983/head:pull/4983` \
`$ git checkout pull/4983`

Update a local copy of the PR: \
`$ git checkout pull/4983` \
`$ git pull https://git.openjdk.java.net/jdk pull/4983/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4983`

View PR using the GUI difftool: \
`$ git pr show -t 4983`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4983.diff">https://git.openjdk.java.net/jdk/pull/4983.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
Amazing.
So what do you think is the reason for the performance gain?
Thanks.

**Comment by TheRealMDoerr** [comment]
Sounds like a good idea. Only doing prefetch immediately before copy looks odd, but this may be a different topic.

**Review by kimbarrett — COMMENTED** [review]
Any explanation for why this has a significant impact?

**Comment by Hamlin-Li** [comment]
Not quite sure, it could be related to the pipeline scheduling at CPU level.
BTW, I just uploaded the test result for x86, no regression for x86.

**Comment by tschatzl** [comment]
We are currently trying to reproduce these improvements on aarch64 and x64.

Also, please revert the change to the age calculation and file this separately. I think I remember the reason for incrementing the age the way it is done is/was that it is supposed to avoid some forced reloads of the mark word which may or may not be important. Either way it is completely unrelated to this change.

**Comment by Hamlin-Li** [comment]
I see, just reverted the code related to age.

**Comment by nick-arm** [comment]
What type of machine are you using to get that result? We tested SPECjbb on AWS M6g but couldn't see any significant difference in critical jops.

**Comment by Hamlin-Li** [comment]
Thanks for the testing, and feedback.

setting in run_multi.sh of specjbb2015:

GROUP_COUNT=4
TI_JVM_COUNT=1
JAVA_OPTS_BE="-server  -XX:+UseG1GC -Xmx50g -Xms50g -XX:ParallelGCThreads=25"

my test env is as below:

$ uname -a
Linux jvm-97 4.19.36-vhulk1907.1.0.h702.eulerosv2r8.aarch64 #1 SMP Mon Mar 16 00:02:15 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        4
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            65536K
NUMA node0 CPU(s):   0-31
NUMA node1 CPU(s):   32-63
NUMA node2 CPU(s):   64-95
NUMA node3 CPU(s):   96-127

**Comment by Hamlin-Li** [comment]
@tschatzl Hi Thomas, may I ask how's test result on aarch64 and x64?

**Comment by tschatzl** [comment]
Sorry for the wait, but actually my testing just finished today - I initially had a few issues (needing to redo a few times, and due to the results re-testing to get better results), but I could not see any statistically significant difference in either maxjops or criticaljops (or any other benchmark I have tested) with Oracle cloud instances with Ampere Altra CPUs at this time.

There is no discernible difference on x64 either.

I will discuss this with others how to proceed today; personally it may be worth aligning the code with Parallel GC anyway.

**Comment by Hamlin-Li** [comment]
Thanks for the feedback. Please kindly let me know your discussion result.

**Comment by tschatzl** [comment]
So we talked about this internally, and standalone it does not seem to be worth adding given that the gain you report is not reproducable on multiple (current) systems, and together we were not able to come up with an explanation why this suggested order of copy/cas would be better.

However it also enables further code improvements by simplifying (mark word) code. So we think that if this change and the mark word change suggested earlier together are at least performance-neutral (which is likely imo), we are going to take in both changes.

I'll start some perf runs with both changes applied (I'll just manually re-apply the mark word change you suggested earlier).

Hth,
  Thomas

**Comment by tschatzl** [comment]
This is the code I'm using: https://github.com/openjdk/jdk/compare/master...tschatzl:mark-word-cleanup-copy-cas?expand=1

**Comment by Hamlin-Li** [comment]
Thanks Thomas, then I'll wait for your perf result.

**Review by tschatzl — APPROVED** [review]
Lgtm; perf results with the mark word change (see earlier) look good, i.e. no particular perf changes. Please wait for a second review.

**Review by albertnetymk — APPROVED** [review]

**Comment by Hamlin-Li** [comment]
Kindly reminder, I think I still need another reviewer?

**Comment by tschatzl** [comment]
There are two reviews (from me and @albertnetymk), and Kim's question about the reasons do not seem relevant any more, so this is good to go imho.

**Comment by Hamlin-Li** [comment]
Thanks Thomas, I just saw Albert has been a reviewer too. 
Congratulation @albertnetymk

**Comment by tschatzl** [comment]
Just for clarification: the default requirements for a change in the gc-team to integrate is to have at least two "r"eviewers (note the lowercase r - those are people that approved it regardless of role), at least one of which must be a "R"eviewer, i.e. has the openjdk reviewer role (and there are no other open questions/comments).

So that formal requirement had already been fulfilled by me and Albert without Albert being a "R"eviewer.

**Pull request closed without merging**
