### PR TITLE
8255883: Avoid duplicated GeneratedMethodAccessor when reflect method invoked from different threads

### PR DESCRIPTION
**Pull request by huishi-hs**
…ructorAccessorImpl object

duplicate with https://github.com/openjdk/jdk/pull/1070, try trigger test with new PR

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255883](https://bugs.openjdk.java.net/browse/JDK-8255883): Avoid duplicated GeneratedMethodAccessor when reflect method invoked from different threads

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1213/head:pull/1213`
`$ git checkout pull/1213`

### CODE REVIEW

**Comment by huishi-hs** [comment]
@JornVernee 
Could you please help approve and start  tier1 test?
This is same PR with https://github.com/openjdk/jdk/pull/1070

**Comment by JornVernee** [comment]
@huishi-hs Testing should start automatically, will appear here when you push to any branch in your fork that is not `master`: https://github.com/huishi-hs/jdk/actions (unless you disabled this in the repo settings).

As I said, the `/test` command does not work at this time.

**Comment by huishi-hs** [comment]
@JornVernee  Thanks!  I didn't enable https://github.com/huishi-hs/jdk/actions. Now it works.

**Comment by huishi-hs** [comment]
Close this. PR is only for presubmit testing.

**Pull request closed without merging**
