### PR TITLE
8306323: Update license files in CLDR v43

### PR DESCRIPTION
**Pull request by naotoj**
The upgrade to CLDR v43 was missing the license-related file updates. Here are the supplemental updates.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306323](https://bugs.openjdk.org/browse/JDK-8306323): Update license files in CLDR v43

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Steven Loomis](https://openjdk.org/census#srl) (@srl295 - Committer)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13517/head:pull/13517` \
`$ git checkout pull/13517`

Update a local copy of the PR: \
`$ git checkout pull/13517` \
`$ git pull https://git.openjdk.org/jdk.git pull/13517/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13517`

View PR using the GUI difftool: \
`$ git pr show -t 13517`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13517.diff">https://git.openjdk.org/jdk/pull/13517.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13517#issuecomment-1513640712)

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

**Review by srl295 — CHANGES_REQUESTED** [review]
[testing]

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
- [Steven Loomis](https://openjdk.org/census#srl) (@srl295 - Committer) 🎉

**Pull request closed without merging**
