### PR TITLE
8332101: Add an `@since` to `StandardOperation:REMOVE` in `jdk.dynalink`

### PR DESCRIPTION
**Pull request by nizarbenalla**
Code cleanup, please review this simple change. I split my changes into 1 PR per module to make reviewing simpler.
To help with the review, this was added back in https://bugs.openjdk.org/browse/JDK-8191905
TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332101](https://bugs.openjdk.org/browse/JDK-8332101): Add an `@<!---->since` to `StandardOperation:REMOVE` in `jdk.dynalink` (**Sub-task** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19189/head:pull/19189` \
`$ git checkout pull/19189`

Update a local copy of the PR: \
`$ git checkout pull/19189` \
`$ git pull https://git.openjdk.org/jdk.git pull/19189/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19189`

View PR using the GUI difftool: \
`$ git pr show -t 19189`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19189.diff">https://git.openjdk.org/jdk/pull/19189.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19189#issuecomment-2106344437)

### CODE REVIEW

**Comment by nizarbenalla** [comment]
I believe `jdk.nashorn` is under core-libs

/label core-libs

**Review by jaikiran — APPROVED** [review]
The change looks good to me. `StandardOperation.REMOVE` was introduced through https://bugs.openjdk.org/browse/JDK-8191905 which was a JDK 10 change, so matches with the proposed change in this PR.

**Pull request closed without merging**
