### PR TITLE
8324659: GHA: Generic jtreg errors are not reported

### PR DESCRIPTION
**Pull request by shipilev**
When looking at [JDK-8324647](https://bugs.openjdk.org/browse/JDK-8324647), I was surprised to see that GHA has this output:

```
Running test 'jtreg:test/lib-test:tier1'
/home/runner/work/jdk/jdk/test/lib-test/TEST.groups: group all: group includes itself
Error: One or more groups are invalid
Finished running test 'jtreg:test/lib-test:tier1'
Test report is stored in build/run-test-prebuilt/test-results/jtreg_test_lib_test_tier1

==============================
Test summary
==============================
   TEST TOTAL PASS FAIL ERROR
>> jtreg:test/lib-test:tier1 1 0 0 1 <<
==============================
TEST FAILURE
```

...and yet, the tests are recorded as "green"! I think this is because our error reporting code is tad buggy. AFAICS, `make test-prebuilt` does not report a non-zero exit code on failure, and the external script looks for `build/run-test-prebuilt/make-support/exit-with-error` to check for error. But it does not _set_ the exit code on its own when the failure is discovered, neither it sets `failure=true` on generic failure.

I think at very minimum we should report `failure=true` on generic failure. I thought about reporting non-zero exit code from the parsing script, but it does not feel clean to return non-zero exit code from the _parsing script_. Non-zero exit code from that script should signify the error in the script itself.

Additional testing:
 - [x] Current GHA with lib-test failure (now red)
 - [x] Current GHA with lib-test fix (now green)
 - [x] GHA with artificial errors: https://github.com/shipilev/jdk/actions/runs/7652797646/job/20854472816

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324659](https://bugs.openjdk.org/browse/JDK-8324659): GHA: Generic jtreg errors are not reported (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17568/head:pull/17568` \
`$ git checkout pull/17568`

Update a local copy of the PR: \
`$ git checkout pull/17568` \
`$ git pull https://git.openjdk.org/jdk.git pull/17568/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17568`

View PR using the GUI difftool: \
`$ git pr show -t 17568`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17568.diff">https://git.openjdk.org/jdk/pull/17568.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17568#issuecomment-1910349449)

### CODE REVIEW

**Comment by shipilev** [comment]
Ah, I see a GHA failure similar to https://bugs.openjdk.org/browse/JDK-8318536 -- which is a nice example that current PR still works when there are failures :)

**Review by erikj79 — APPROVED** [review]

**Review by TheShermanTanker — APPROVED** [review]
LGTM

**Review by tstuefe — APPROVED** [review]
Ouch. Wow. +1. 

Is this problem also in older releases?

**Comment by shipilev** [comment]
> Is this problem also in older releases?

Yes, I think so. I'll backport it everywhere I can reach.

**Pull request closed without merging**
