### PR TITLE
8303022: "assert(allocates2(pc)) failed: not in CodeBuffer memory" When linking downcall handle

### PR DESCRIPTION
**Pull request by JornVernee**
The issue is that the size of the code buffer is not large enough to hold the whole stub.

Proposed solution is to scale the size of the stub with the number of arguments. I've adjusted sizes for both downcall and upcall stubs. I've also dropped the number of relocations, since we're not really using any for downcalls, and for upcalls we only have 1 AFAICS. (the size of the relocations can not be zero however, as that leads to the relocation section [not being initialized][1], and triggering [an assert][2] later when the code blob is copied).

The way I've determined the new base size and per-argument size for stubs, is by first linking a stub without any arguments to get the required base size, and by then adding 20 `double` arguments to get a rough per-argument size. Both values have wiggle room as well. The sizes can be printed using e.g. `-XX:+LogCompilation`, and then looking for `nep_invoker_blob` and `upcall_stub*` in the log file. This experiment was done on a fastdebug build to account for additional debug code being generated. The included test is designed to try and maximize the size of the generated stub.

I've also updated `CodeBuffer::log_section_sizes` to print the in-use size, rather than just the capacity and free space.

[1]: https://github.com/openjdk/jdk/blob/56512cfe1f0682c98ba3488af3d03ccef632c016/src/hotspot/share/asm/codeBuffer.cpp#L119-L121
[2]: https://github.com/openjdk/jdk/blob/56512cfe1f0682c98ba3488af3d03ccef632c016/src/hotspot/share/asm/codeBuffer.cpp#L675

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303022](https://bugs.openjdk.org/browse/JDK-8303022): "assert(allocates2(pc)) failed: not in CodeBuffer memory" When linking downcall handle

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12908/head:pull/12908` \
`$ git checkout pull/12908`

Update a local copy of the PR: \
`$ git checkout pull/12908` \
`$ git pull https://git.openjdk.org/jdk pull/12908/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12908`

View PR using the GUI difftool: \
`$ git pr show -t 12908`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12908.diff">https://git.openjdk.org/jdk/pull/12908.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
I think you need to add these changes to other ports too and ask for testing on them.

**Comment by JornVernee** [comment]
@vnkozlov Yes, this is true. The only other existing port of this code is RISCV. However, to fix that port properly, someone needs to repeat the experiment on RISCV in order to figure out what the base size and the size per argument should be.

I don't have access to a RISCV machine, so I figured I would file a followup issue for the RISCV maintainers to fix separately.

@feilongjiang Could you comment on this? If you could figure out the needed sizes for RISCV I could add the needed changes to this patch. Otherwise I could file a followup issue if that seems more convenient.

**Comment by feilongjiang** [comment]
> @feilongjiang Could you comment on this? If you could figure out the needed sizes for RISCV I could add the needed changes to this patch. Otherwise I could file a followup issue if that seems more convenient. TIA

Yes, I will take a look to find out the needed size for RISCV.

**Comment by JornVernee** [comment]
@feilongjiang Thanks! I've added the riscv changes.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by JornVernee** [comment]
Not sure if this needs another reviewer?

**Comment by vnkozlov** [comment]
> @vnkozlov Does this need another reviewer?

Yes, it is not trivial

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by JornVernee** [comment]
Thanks for the reviews. I'm running one more round of tests before integrating.

**Pull request closed without merging**
