### PR TITLE
8305995: Footprint regression from JDK-8224957

### PR DESCRIPTION
**Pull request by catap**
This is a fix for the regression introduced by da43cb5e463069cf4dafb262664f0d3d7c2e0eac in fix 8224957.

This regression was found while attempting to migrate an application from JDK 1.8 to JDK 17, by running internal benchmarks, and while investigating abnormal memory usage for about 4 times more from one of them.

The regression appears in the JMH benchmark, which builds a huge tree which contains boxed integers from 0 to a few thousand. A tree has very complex structure and the same objects are reused a lot.

When an `integer` is found it's collected as `Integer` and unboxed inside the collector callback.

This benchmark was run with `ParallelGC` on different JVMs: `JDK 1.8.0_362`, `JDK 11.0.18`, `JDK 13.0.13`, `JDK 15.0.9`, `JDK 17.0.6`, `JDK 19.0.2` and `JDK 20`. This allows to see that something has changed between 13 and 15, and that the memory footprint for this code has increased from `3152` to `11828` bytes per operation.

After that I've done a `git bisect` which allows me to locate the introducer.

So the current fix reduces the memory footprint on the local root 425ef0685c584abec80454fbcccdcc6db6558f93 to `2960` bytes per operation.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305995](https://bugs.openjdk.org/browse/JDK-8305995): Footprint regression from JDK-8224957

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13453/head:pull/13453` \
`$ git checkout pull/13453`

Update a local copy of the PR: \
`$ git checkout pull/13453` \
`$ git pull https://git.openjdk.org/jdk.git pull/13453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13453`

View PR using the GUI difftool: \
`$ git pr show -t 13453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13453.diff">https://git.openjdk.org/jdk/pull/13453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13453#issuecomment-1508234249)

### CODE REVIEW

**Comment by catap** [comment]
I've minimized my code to a trivial benchmark https://gist.github.com/catap/3ac65ba878048cca0132e6cba17d86ba which shown that effect of this patch is reducing memory footprint 20 times.

**Comment by TobiHartmann** [comment]
Thanks for reporting this, Kirill. I filed [JDK-8305995](https://bugs.openjdk.org/browse/JDK-8305995) for tracking. It would be great if you could add your benchmark (to `test/micro/org/openjdk/bench/`). I'll have a look at your proposed fix next week.

**Comment by vnkozlov** [comment]
First, please update PR's title should match JBS's title.
Second, @catap you referenced JMH benchmark. Is it already in `test/micro/org/openjdk/bench/` or it is new? Please add it if it is not.
 
So before 8224957 code looks through in(1) for req() > 3 (and == 2). After 8224957 we bailout for >3 inputs.
This fix removed this restriction and we now go through all inputs for case > 3 inputs.
It may increase compilation time for such cases significantly but on other hand it may allow reduce IR.

I assume, based on description, x4 increase is in Java heap due to not unboxing some Java objects. Or is it memory consumed by C2 Jit compiler during benchmark execution?

**Comment by catap** [comment]
@vnkozlov after spending some time to simplify my benchmark and to include it into PR as the next commit, I'd like to conclude that boxing / unboxing aren't doing anything with it.

I just made a force push which contains the benchmark. JMH reports that it almost hasn't got memory footprint in runtime `≈ 10⁻³` on JDK up to  13 includes, but on JDK 15 and after that it consumes `≈ 7536`.

So, in fact it isn't x4, I was wrong on the first assumption. It is much bigger.

P.S. I've also rewrite the commit message and include issue ID into it.

**Comment by vnkozlov** [comment]
Thank you for adding benchmark. Please use meaningful name for benchmark and add copyright header to it. See other benchmarks there as example.

**Comment by vnkozlov** [comment]
And add benchmark's output as comment and what machine you used to run it.

**Comment by catap** [comment]
Renamed. I've run it as `make test TEST="micro:RBTreeSearch" MICRO_OPTIONS="-prof gc"` and have an output on my branch:
```
Benchmark                                 Mode  Cnt   Score    Error   Units
RBTreeSearch.search                      thrpt   12   0.079 ±  0.013  ops/us
RBTreeSearch.search:·gc.alloc.rate       thrpt   12  ≈ 10⁻⁴           MB/sec
RBTreeSearch.search:·gc.alloc.rate.norm  thrpt   12   0.003 ±  0.001    B/op
RBTreeSearch.search:·gc.count            thrpt   12     ≈ 0           counts
```
if I revert my changes by `git diff ..origin/master -- src/hotspot/share/opto/node.cpp | patch -p1` for example and re-run test I do have an output:
```
Benchmark                                 Mode  Cnt     Score    Error   Units
RBTreeSearch.search                      thrpt   12     0.044 ±  0.009  ops/us
RBTreeSearch.search:·gc.alloc.rate       thrpt   12   209.072 ± 42.450  MB/sec
RBTreeSearch.search:·gc.alloc.rate.norm  thrpt   12  5024.005 ±  0.001    B/op
RBTreeSearch.search:·gc.count            thrpt   12    17.000           counts
RBTreeSearch.search:·gc.time             thrpt   12    17.000               ms
```

As you may see memory footprint quite different.

As test machine I use right now macOS 12.6.3. I may find some linux, but I doubt that this logic is os specific.

**Comment by vnkozlov** [comment]
New test's name is fine. Please, update copyright year (first line) to 2023.

Thank you for data. It shows that C2 did not eliminate Integer boxing allocations without your fix. As result they consume Java heap.  With your fix C2's Escape Analysis eliminated these allocations.

Good!

I will submit internal  testing for your changes.

**Review by vnkozlov — APPROVED** [review]
My testing passed.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too. Thanks for fixing this!

**Comment by TobiHartmann** [comment]
We (Oracle) will backport it to Oracle JDK 17u after some bake time in mainline. It's then up to the OpenJDK community to backport it to OpenJDK 17u as well but I think it's likely that they will do so.

**Comment by catap** [comment]
@TobiHartmann thanks, it's clear. But can I expect that this fix will be the next release of JDK17?

**Comment by TobiHartmann** [comment]
This will most likely go into JDK 17.0.8 but it depends on if and when the fix is backported.

**Pull request closed without merging**
