### PR TITLE
8325028: (ch) Pipe channels should lazily set socket to non-blocking mode on first use by virtual thread

### PR DESCRIPTION
**Pull request by AlanBateman**
The Unix implementation of the Pipe source/sink channels eagerly configures the underlying socket to be non-blocking in case the pipe is used by a virtual thread. It can be done lazily, as done with the network channels. No changes to the semantics of the APIs, and well tested by the existing tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325028](https://bugs.openjdk.org/browse/JDK-8325028): (ch) Pipe channels should lazily set socket to non-blocking mode on first use by virtual thread (**Enhancement** - P4)

### Reviewers
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17648/head:pull/17648` \
`$ git checkout pull/17648`

Update a local copy of the PR: \
`$ git checkout pull/17648` \
`$ git pull https://git.openjdk.org/jdk.git pull/17648/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17648`

View PR using the GUI difftool: \
`$ git pr show -t 17648`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17648.diff">https://git.openjdk.org/jdk/pull/17648.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17648#issuecomment-1931871193)

### CODE REVIEW

**Review by bplb — APPROVED** [review]
Looks okay.

**Comment by jaikiran** [comment]
Hello Alan, is the use of the word "socket" in the comments and the method names (and the PR title) intentional? As far as I can see the sink/source channels' underlying resources are file descriptors created out of a `pipe()` call. Do we use the term "socket" for such cases too?

**Comment by AlanBateman** [comment]
> Hello Alan, is the use of the word "socket" in the comments and the method names (and the PR title) intentional? 

These channels can work with pipes or an unnamed pair of connected sockets. In the Windows implementation they use a Unix domain socket or a TCP socket, depending not on which Windows release. So I kept the comment using "socket" but you are right that it might be a bit clearer to say pipe in the Unix implementation. We can adjust this comment when next touching this area (as the changes here are already integrated).

**Comment by jaikiran** [comment]
> We can adjust this comment when next touching this area (as the changes here are already integrated).

That is fine with me.

**Pull request closed without merging**
