### PR TITLE
8274939: Incorrect size of the pixel storage is used by the robot on macOS

### PR DESCRIPTION
**Pull request by mrserb**
In JDK 9 the native code for the robot class was reworked to get an access to the HiDPI quality screenshots. So we allocate the data storage for the HiDPI quality and then request the best quality from the macOS.

It works fine if the user request the screenshot of some area, since we properly scale this area. Unfortunately it does not work well if the user request only one pixel, in this case we allocate the array of one element and does not multiply the size by the scale, so if the system scale is 2 then the macOS returns the 2x2 pixels, which does not fit properly to the array of one element. This can be checked by the Xcheck:jni option which produce fatal error in this case.

Solution is to allocate the storage of the proper size 1 * scale * 1 * scale

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274939](https://bugs.openjdk.java.net/browse/JDK-8274939): Incorrect size of the pixel storage is used by the robot on macOS

### Reviewers
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5864/head:pull/5864` \
`$ git checkout pull/5864`

Update a local copy of the PR: \
`$ git checkout pull/5864` \
`$ git pull https://git.openjdk.java.net/jdk pull/5864/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5864`

View PR using the GUI difftool: \
`$ git pr show -t 5864`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5864.diff">https://git.openjdk.java.net/jdk/pull/5864.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Any volunteers?

**Comment by prsadhuk** [comment]
It seems CheckCommonColors still fails intermittently even with this fix in macos aarch64 along with others
open/test/jdk/java/awt/Robot/HiDPIScreenCapture/ScreenCaptureTest.java, 
open/test/jdk/java/awt/ColorClass/AlphaColorTest.java, 
open/test/jdk/java/awt/AlphaComposite/WindowAlphaCompositeTest.java

CheckCommonColors fails with this log
---------System.out:(3/175)----------
color = java.awt.Color[r=255,g=255,b=255], useRect = true
color = java.awt.Color[r=255,g=255,b=255], useRect = false
color = java.awt.Color[r=192,g=192,b=192], useRect = true
----------System.err:(17/897)----------
Expected: java.awt.Color[r=192,g=192,b=192]
Actual: java.awt.Color[r=199,g=199,b=199]
Point: java.awt.Point[x=960,y=600]
Dump screen to: ScreenCapture.png

**Comment by mrserb** [comment]
> It seems CheckCommonColors still fails intermittently even with this fix in macos aarch64 along with others open/test/jdk/java/awt/Robot/HiDPIScreenCapture/ScreenCaptureTest.java, open/test/jdk/java/awt/ColorClass/AlphaColorTest.java, open/test/jdk/java/awt/AlphaComposite/WindowAlphaCompositeTest.java

They could fail because of cursor location, or some other bug in our code or in the macOS. It will be good to debug it on that system where it fail.

**Comment by mrserb** [comment]
Any volunteers?

**Comment by mrserb** [comment]
Any volunteers to look at this buffer overrun?

**Review by aivanov-jdk — APPROVED** [review]
I think increasing the buffer according to the scale is correct as the `scale` × `scale` image where `scale != 1` can't fit into the buffer of size 1.

It may not fix other bugs or test failures; buffer overrun is not a good thing and it's fixed.

**Comment by aivanov-jdk** [comment]
I wonder if a similar problem exist on Windows and Linux. The `pixelArray` is allocated as `new int[bounds.width*bounds.height]` in both. And for macOS too: `CRobot.getRGBPixels` allocates the array of size `bounds.width*bounds.height`, shouldn't it be twice as large if uiScale=2.0 is in effect?

**Comment by prrace** [comment]
I noted I was intending tests with this patch applied .. I think I did that but of course I've lost them now. I'll try again.

**Comment by prrace** [comment]
Why doesn't this need updating too ?  Seems like it must be OK else we'd have massive over-runs .. 

  @Override
    public int [] getRGBPixels(final Rectangle bounds) {
        int[] c = new int[bounds.width * bounds.height];
        getScreenPixels(bounds, c);
        return c;
    }

**Comment by prrace** [comment]
Looking at what happens in native it seems like it should be possible to add a check that the
Java array has enough capacity to satisfy what the call to retrieve pixels expects. 
I think it would be reasonable to throw InternalError if it does not !

**Comment by prrace** [comment]
My testing looks good - but waiting on answers to the other questions

**Comment by mrserb** [comment]
> I wonder if a similar problem exist on Windows and Linux. The pixelArray is allocated as new int[bounds.width*bounds.height] in both. And for macOS too: CRobot.getRGBPixels allocates the array of size bounds.width*bounds.height, shouldn't it be twice as large if uiScale=2.0 is in effect?

On Linux and Windows we pass the size of the area to the system in the device space, so we store an image of the size we just allocated. The macOS is different we pass the coordinates in the users space -> when we pass 1x1 we may get 4x4 on the HiDPI screen, this is what the current fix changed.

>Why doesn't this need updating too ? Seems like it must be OK else we'd have massive over-runs ..

We do not need to change other getRGBPixels() method because its coordinates already converted to the pixels(device space), we do this in the shared code. Note that the method which changed by this fix however use the "1" as a width and height in the users space - this is a bug.

>Looking at what happens in native it seems like it should be possible to add a check that the
Java array has enough capacity to satisfy what the call to retrieve pixels expects.
I think it would be reasonable to throw InternalError if it does not !

The logic we use is this:
 1 We prepared the pixel storage using device space coordinates
 2 We capture the 1x1 unit in the users space, usually this is 1x1 pixel on lowdpi and 4x4 on hidpi screen, actually macOS may return any size
 3 If the macOS return some other size we down/up [scale](https://github.com/openjdk/jdk/blob/cab590517bf705418c7376edd5d7066b13b6dde8/src/java.desktop/macosx/native/libawt_lwawt/awt/CRobot.m#L352) it to the size we calculated at step 1

**Comment by prrace** [comment]
I get that getPixelColor() / getRGBPixel() takes only a coordinate but when looking at CRobotPeer it is far from obvious why there is this inconsistency.  If we can't make the shared code consistent - maybe add a scale parameter ? Then at least we should have some comments.
But why are X11 and Windows fine with no scale ?

X11:
    @Override
    public int getRGBPixel(int x, int y) {
        int[] pixelArray = new int[1];
        getRGBPixelsImpl(xgc, x, y, 1, 1, pixelArray, useGtk);
        return pixelArray[0];
    }

Windows :
    @Override
    public int getRGBPixel(int x, int y) {
         // See 7002846: that's ineffective, but works correctly with non-opaque windows
        return getRGBPixels(new Rectangle(x, y, 1, 1))[0];
    }

And in native what I was suggesting was a safeguard that would have detected this problem - which I still think would be a good idea.

BTW "usually this is 1x1 pixel on lowdpi and 4x4 on hidpi screen, actually macOS may return any size"

When might it return "any size" ?
My experiments show scale==2 no matter what scale I use in the macos Display settings for the built-in retina

**Comment by mrserb** [comment]
> But why are X11 and Windows fine with no scale ?

Since the coordinates are in the device space, and we pass this coordinates to the OS as is, and the OS returns the images of the requested size we do not need to use a scale there. Unlike macOS where we should have coordinates in the user space and device space at the same time. So instead of the second coordinates we pass the scale and calculate others coordinate.

> BTW "usually this is 1x1 pixel on lowdpi and 4x4 on hidpi screen, actually macOS may return any size"
> 
> When might it return "any size" ? My experiments show scale==2 no matter what scale I use in the macos Display settings for the built-in retina

Per the specification of the method we use: [kCGWindowImageBestResolution](https://developer.apple.com/documentation/coregraphics/cgwindowimageoption/kcgwindowimagebestresolution). So when we request the area in the user space, that method may return low/hi/something in between/ image, then we convert/scale that image to fit the array we allocated.

**Comment by prrace** [comment]
- So this is crying out for comments in the source code 
- I still see a need for a safety check in native code

**Comment by mrserb** [comment]
>     * I still see a need for a safety check in native code

I can add some check but which one? In the native we should use the bounds we passed from java side, the problem is that we pass "1 * scale" = 'scale", but allocate the array as "new int[1]" so this is an issue on that java side in the changed method.

**Comment by prrace** [comment]
> > ```
> > * I still see a need for a safety check in native code
> > ```
> 
> 
> I can add some check but which one? In the native we should use the bounds we passed from java side, the problem is that we pass "1 * scale" = 'scale", but allocate the array as "new int[1]" so this is an issue on that java side in the changed method.
Isn't the over-run supposed to be here :

JNIEXPORT void JNICALL
Java_sun_lwawt_macosx_CRobot_nativeGetScreenPixels
(JNIEnv *env, jobject peer,
 jint x, jint y, jint width, jint height, jdouble scale, jintArray pixels)



 void *jPixelData = (*env)->GetPrimitiveArrayCritical(env, pixels, 0);

  CGContextRef jPicContextRef = CGBitmapContextCreate(
                                            jPixelData,
                                            picWidth, picHeight,
                                            8, picWidth * sizeof(jint),
                                            picColorSpace,
                                            kCGBitmapByteOrder32Host |
                                            kCGImageAlphaPremultipliedFirst)

And then the apple docs at https://developer.apple.com/documentation/coregraphics/1455939-cgbitmapcontextcreate/ say
about the 1st parameter :
Data

    A pointer to the destination in memory where the drawing is to be rendered. The size of this memory block should be at least (bytesPerRow*height) bytes.
and picWidth * sizeof(jint), is bytes per row.
    So if it the Java array pixels  is just one int (4 bytes) and we have a scale of 2 when it needs to be 4 ints (16 bytes) we'd have the over-run ? 
Then why can't we just  make sure (*env)->GetArrayLength(env, pixels) >= picWidth * picHeight ??

**Comment by mrserb** [comment]
>A pointer to the destination in memory where the drawing is to be rendered. The size of this memory block should be at least (bytesPerRow*height) bytes. and picWidth * sizeof(jint), is bytes per row.
So if it the Java array pixels is just one int (4 bytes) and we have a scale of 2 when it needs to be 4 ints (16 bytes) we'd have the over-run ? 

If the scale is 2 then we will need 4 ints overall, but only 2 ints per row, since we will have 2 rows.

>Then why can't we just make sure (*env)->GetArrayLength(env, pixels) >= picWidth * picHeight ??

We can for sure, I can update the fix.

**Comment by mkartashev** [comment]
FWIW there's a related problem on Linux where the size of the captured area is [scaled down in the native code](https://github.com/openjdk/jdk/blob/973dda5ce0747a8ea67ec3a34c2ef2a0b2b6b140/src/java.desktop/unix/native/libawt_xawt/awt/gtk3_interface.c#L2874), which in case of capturing just one pixel might end up being 0 for scales 300%+. I just filed [JDK-8280861](https://bugs.openjdk.java.net/browse/JDK-8280861) for that and the issue with coordinates scaling on Linux.

**Comment by mrserb** [comment]
> I just filed [JDK-8280861](https://bugs.openjdk.java.net/browse/JDK-8280861) for that and the issue with coordinates scaling on Linux.

It looks similar to what is done on macOS when two types of coordinates are be needed: the user's space to pass to the GTK and the device space to create storage for the pixels. Be careful to not desync them as we did on macOS here.

**Comment by mrserb** [comment]
You are absolutely right! in case of linux we have the same bug when gtk is used. =(

**Comment by mrserb** [comment]
I have added an additional check for the parameters of the native method.

**Review by prrace — APPROVED** [review]
Sorry, missed this update.

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
