### PR TITLE
8251944: Add Shenandoah test config to compiler/gcbarriers/UnsafeIntrinsicsTest.java

### PR DESCRIPTION
**Pull request by shipilev**
There used to be failures in Shenandoah CAS handling code like that were caught by this test. Those were fixed in JDK-8255401. This change turns the test into regression test for it.

Additional testing:
 - [x] Affected test on `x86_64` fastdebug, release
 - [x] Affected test on `x86_32` fastdebug
 - [x] Affected test on `aarch64` fastdebug

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251944](https://bugs.openjdk.java.net/browse/JDK-8251944): Add Shenandoah test config to compiler/gcbarriers/UnsafeIntrinsicsTest.java

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to 8ca126867a30a4e399c255a756bbad5b62d51c97
 * [Aditya Mandaleeka](https://openjdk.java.net/census#adityam) (@adityamandaleeka - Author) ⚠️ Review applies to 8ca126867a30a4e399c255a756bbad5b62d51c97

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1693/head:pull/1693`
`$ git checkout pull/1693`

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Looks good to me! Thanks!

**Review by adityamandaleeka — APPROVED** [review]
LGTM

**Pull request closed without merging**
