### PR TITLE
8250269: Replace ATTRIBUTE_ALIGNED with alignas

### PR DESCRIPTION
**Pull request by TheShermanTanker**
C++11 added the alignas attribute, for the purpose of specifying alignment on types, much like compiler specific syntax such as gcc's \_\_attribute\_\_((aligned(x))) or Visual C++'s \_\_declspec(align(x)).

We can phase out the use of the macro in favor of the standard attribute. In the meantime, we can replace the compiler specific definitions of ATTRIBUTE_ALIGNED with a portable definition. We might deprecate the use of the macro but changing its implementation quickly and cleanly applies the feature where the macro is being used.

Note: With certain parts of HotSpot using ATTRIBUTE_ALIGNED so indiscriminately, this commit will likely take some time to get right

This will require adding the alignas attribute to the list of language features approved for use in HotSpot code. (Completed with [8297912](https://github.com/openjdk/jdk/pull/11446))

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8250269](https://bugs.openjdk.org/browse/JDK-8250269): Replace ATTRIBUTE_ALIGNED with alignas (**Enhancement** - P4)

### Reviewers
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/11431/head:pull/11431` \
`$ git checkout pull/11431`

Update a local copy of the PR: \
`$ git checkout pull/11431` \
`$ git pull https://git.openjdk.org/jdk.git pull/11431/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11431`

View PR using the GUI difftool: \
`$ git pr show -t 11431`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11431.diff">https://git.openjdk.org/jdk/pull/11431.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/11431#issuecomment-1332092458)

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Pinging mailing list for further guidance on what to do with the commit, I think it may have been buried by more recent Pulls

**Comment by TheShermanTanker** [comment]
:(

**Comment by TheShermanTanker** [comment]
:(

**Comment by plummercj** [comment]
This PR should be closed since the changes have been merged into #13258.

**Comment by kimbarrett** [comment]
I've been meaning to review this but have been swamped.  Sorry.

I don't think this change to HotSpot should be combined with JDK-8305341 / PR#13258.

I'm concerned there might be uses of ATTRIBUTE_ALIGNED in other places than at
the front of the declaration (like the fixed offset_of macro in the proposed changes).
Obviously there aren't any that break compilation.  But is alignas in other
places valid but with a different meaning?  For a discussion of the kind of
thing I'm concerned about, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108796

**Comment by TheShermanTanker** [comment]
Ah, sorry about that, I'll remove the issue from the other PR

**Comment by TheShermanTanker** [comment]
> I've been meaning to review this but have been swamped. Sorry.
> 
> I don't think this change to HotSpot should be combined with JDK-8305341 / PR#13258.
> 
> I'm concerned there might be uses of ATTRIBUTE_ALIGNED in other places than at the front of the declaration (like the fixed offset_of macro in the proposed changes). Obviously there aren't any that break compilation. But is alignas in other places valid but with a different meaning? For a discussion of the kind of thing I'm concerned about, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108796

I get what you mean, I'll search HotSpot's codebase to see whether this issue pops up in any of our existing code. It's a little tempting to just replace every instance of this macro with alignas, but I guess I'll avoid doing that to keep the changes minimal

**Comment by TheShermanTanker** [comment]
@kimbarrett I've written down all the usage sites excluding the globalDefinitions_gcc.hpp case as such (included the code affected for easy grepping as well):

macroAssembler_aarch64_log.cpp:
`ATTRIBUTE_ALIGNED(64) juint _L_tbl[] =`

stubRoutines_aarch64.cpp:
```
ATTRIBUTE_ALIGNED(4096) juint StubRoutines::aarch64::_crc_table[] =
ATTRIBUTE_ALIGNED(64) jubyte StubRoutines::aarch64::_adler_table[] = {
ATTRIBUTE_ALIGNED(64) juint StubRoutines::aarch64::_npio2_hw[] = {
ATTRIBUTE_ALIGNED(64) jdouble StubRoutines::aarch64::_dsin_coef[] = {
ATTRIBUTE_ALIGNED(64) jdouble StubRoutines::aarch64::_dcos_coef[] = {
ATTRIBUTE_ALIGNED(64) jdouble StubRoutines::aarch64::_two_over_pi[] = {
ATTRIBUTE_ALIGNED(64) jdouble StubRoutines::aarch64::_pio2[] = {
```

macroAssembler_x86_32_constants.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _ONES[] = {
ATTRIBUTE_ALIGNED(16) static const juint _PI4_INV[] = {
ATTRIBUTE_ALIGNED(16) static const juint _PI4X3[] = {
ATTRIBUTE_ALIGNED(16) static const juint _PI4X4[] = {
ATTRIBUTE_ALIGNED(16) static const juint _L_2IL0FLOATPACKET_0[] = {
```

macroAssembler_x86_32_cos.cpp:
`ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_cos[] =`

macroAssembler_x86_32_exp.cpp:
`ATTRIBUTE_ALIGNED(16) static const juint _static_const_table[] =`

macroAssembler_x86_32_log.cpp:
`ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_log[] =`

macroAssembler_x86_32_log10.cpp:
`ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_log10[] =`

macroAssembler_x86_32_pow.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_pow[] =
ATTRIBUTE_ALIGNED(8) static const double _DOUBLE2 = 2.0;
ATTRIBUTE_ALIGNED(8) static const double _DOUBLE0 = 0.0;
ATTRIBUTE_ALIGNED(8) static const double _DOUBLE0DOT5 = 0.5;
```

macroAssembler_x86_32_sin.cpp:
```
ATTRIBUTE_ALIGNED(8) static const juint _zero_none[] =
ATTRIBUTE_ALIGNED(4) static const juint __4onpi_d[] =
ATTRIBUTE_ALIGNED(4) static const juint _TWO_32H[] =
ATTRIBUTE_ALIGNED(4) static const juint _pi04_3d[] =
ATTRIBUTE_ALIGNED(4) static const juint _pi04_5d[] =
ATTRIBUTE_ALIGNED(4) static const juint _SCALE[] =
ATTRIBUTE_ALIGNED(4) static const juint _zeros[] =
ATTRIBUTE_ALIGNED(4) static const juint _pi04_2d[] =
ATTRIBUTE_ALIGNED(4) static const juint _TWO_12H[] =
ATTRIBUTE_ALIGNED(2) static const jushort __4onpi_31l[] =
ATTRIBUTE_ALIGNED(16) static const jushort _SP[] =
ATTRIBUTE_ALIGNED(16) static const jushort _CP[] =
ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_sin[] =
```

macroAssembler_x86_32_tan.cpp:
```
ATTRIBUTE_ALIGNED(16) static const jushort _TP[] =
ATTRIBUTE_ALIGNED(16) static const jushort _TQ[] =
ATTRIBUTE_ALIGNED(16) static const jushort _GP[] =
ATTRIBUTE_ALIGNED(16) static const juint _static_const_table_tan[] =
```

stubGenerator_x86_32.cpp:
```
ATTRIBUTE_ALIGNED(16) static const uint32_t KEY_SHUFFLE_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint32_t COUNTER_SHUFFLE_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint32_t GHASH_BYTE_SWAP_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint32_t GHASH_LONG_SWAP_MASK[] = {
```

stubGenerator_x86_64_adler.cpp:
```
ATTRIBUTE_ALIGNED(64) static const juint ADLER32_ASCALE_TABLE[] = {
ATTRIBUTE_ALIGNED(32) static const juint ADLER32_SHUF0_TABLE[] = {
ATTRIBUTE_ALIGNED(32) static const juint ADLER32_SHUF1_TABLE[] = {
```

stubGenerator_x86_64_aes.cpp:
```
ATTRIBUTE_ALIGNED(16) static const uint64_t KEY_SHUFFLE_MASK[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_SHUFFLE_MASK[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_MASK_LINC0[] = {
ATTRIBUTE_ALIGNED(16) static const uint64_t COUNTER_MASK_LINC1[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_MASK_LINC4[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_MASK_LINC8[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_MASK_LINC16[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t COUNTER_MASK_LINC32[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t GHASH_POLYNOMIAL_REDUCTION[] = {
ATTRIBUTE_ALIGNED(16) static const uint64_t GHASH_POLYNOMIAL_TWO_ONE[] = {
```

stubGenerator_x86_64_chacha.cpp:
```
ATTRIBUTE_ALIGNED(64) static const uint64_t CC20_COUNTER_ADD_AVX[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t CC20_COUNTER_ADD_AVX512[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t CC20_LROT_CONSTS[] = {
```

stubGenerator_x86_64_constants.cpp:
```
ATTRIBUTE_ALIGNED(8) static const juint _ONE[] = {
ATTRIBUTE_ALIGNED(16) static const juint _ONEHALF[] = {
ATTRIBUTE_ALIGNED(8) static const juint _SIGN_MASK[] = {
ATTRIBUTE_ALIGNED(8) static const juint _TWO_POW_55[] = {
ATTRIBUTE_ALIGNED(8) static const juint _TWO_POW_M55[] = {
ATTRIBUTE_ALIGNED(16) static const juint _SHIFTER[] = {
ATTRIBUTE_ALIGNED(4) static const juint _ZERO[] = {
ATTRIBUTE_ALIGNED(16) static const juint _SC_1[] = {
ATTRIBUTE_ALIGNED(16) static const juint _SC_2[] = {
ATTRIBUTE_ALIGNED(16) static const juint _SC_3[] = {
ATTRIBUTE_ALIGNED(16) static const juint _SC_4[] = {
ATTRIBUTE_ALIGNED(8) static const juint _PI_4[] = {
ATTRIBUTE_ALIGNED(8) static const juint _PI32INV[] = {
ATTRIBUTE_ALIGNED(8) static const juint _NEG_ZERO[] = {
ATTRIBUTE_ALIGNED(8) static const juint _P_1[] = {
ATTRIBUTE_ALIGNED(16) static const juint _P_2[] = {
ATTRIBUTE_ALIGNED(8) static const juint _P_3[] = {
ATTRIBUTE_ALIGNED(16) static const juint _PI_INV_TABLE[] = {
ATTRIBUTE_ALIGNED(16) static const juint _Ctable[] = {
```

stubGenerator_x86_64_exp.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _cv[] =
ATTRIBUTE_ALIGNED(16) static const juint _mmask[] =
ATTRIBUTE_ALIGNED(16) static const juint _bias[] =
ATTRIBUTE_ALIGNED(16) static const juint _Tbl_addr[] =
ATTRIBUTE_ALIGNED(16) static const juint _ALLONES[] =
ATTRIBUTE_ALIGNED(16) static const juint _ebias[] =
ATTRIBUTE_ALIGNED(4) static const juint _XMAX[] =
ATTRIBUTE_ALIGNED(4) static const juint _XMIN[] =
ATTRIBUTE_ALIGNED(4) static const juint _INF[] =
```

stubGenerator_x86_64_ghash.cpp:
```
ATTRIBUTE_ALIGNED(16) static const uint64_t GHASH_SHUFFLE_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint64_t GHASH_LONG_SWAP_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint64_t GHASH_BYTE_SWAP_MASK[] = {
ATTRIBUTE_ALIGNED(16) static const uint64_t GHASH_POLYNOMIAL[] = {
```

stubGenerator_x86_64_log.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _L_tbl[] =
ATTRIBUTE_ALIGNED(16) static const juint _log2[] =
ATTRIBUTE_ALIGNED(16) static const juint _coeff[] =
ATTRIBUTE_ALIGNED(16) static const juint _HIGHSIGMASK_log10[] = {
ATTRIBUTE_ALIGNED(16) static const juint _LOG10_E[] = {
ATTRIBUTE_ALIGNED(16) static const juint _L_tbl_log10[] = {
ATTRIBUTE_ALIGNED(16) static const juint _log2_log10[] =
ATTRIBUTE_ALIGNED(16) static const juint _coeff_log10[] =
```

stubGenerator_x86_64_poly.cpp:
```
ATTRIBUTE_ALIGNED(64) static const uint64_t POLY1305_PAD_MSG[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t POLY1305_MASK42[] = {
ATTRIBUTE_ALIGNED(64) static const uint64_t POLY1305_MASK44[] = {
```

stubGenerator_x86_64_pow.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _HIGHSIGMASK[] = {
ATTRIBUTE_ALIGNED(16) static const juint _LOG2_E[] = {
ATTRIBUTE_ALIGNED(16) static const juint _HIGHMASK_Y[] = {
ATTRIBUTE_ALIGNED(16) static const juint _T_exp[] = {
ATTRIBUTE_ALIGNED(16) static const juint _e_coeff[] = {
ATTRIBUTE_ALIGNED(16) static const juint _coeff_h[] = {
ATTRIBUTE_ALIGNED(16) static const juint _HIGHMASK_LOG_X[] = {
ATTRIBUTE_ALIGNED(8) static const juint _HALFMASK[] = {
ATTRIBUTE_ALIGNED(16) static const juint _coeff_pow[] = {
ATTRIBUTE_ALIGNED(16) static const juint _L_tbl_pow[] = {
ATTRIBUTE_ALIGNED(8) static const juint _log2_pow[] = {
ATTRIBUTE_ALIGNED(8) static const juint _DOUBLE2[] = {
ATTRIBUTE_ALIGNED(8) static const juint _DOUBLE0[] = {
ATTRIBUTE_ALIGNED(8) static const juint _DOUBLE0DOT5[] = {
```

stubGenerator_x86_64_sin.cpp:
`ATTRIBUTE_ALIGNED(8) static const juint _ALL_ONES[] =`

stubGenerator_x86_64_tan.cpp:
```
ATTRIBUTE_ALIGNED(16) static const juint _MUL16[] =
ATTRIBUTE_ALIGNED(16) static const juint _sign_mask_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _PI32INV_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _P_1_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _P_2_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _P_3_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Ctable_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _MASK_35_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Q_11_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Q_9_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Q_7_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Q_5_tan[] =
ATTRIBUTE_ALIGNED(16) static const juint _Q_3_tan[] =
ATTRIBUTE_ALIGNED(8) static const juint _PI_4_tan[] =
ATTRIBUTE_ALIGNED(8) static const juint _QQ_2_tan[] =
```

stubRoutines_x86.cpp:
```
ATTRIBUTE_ALIGNED(64) const juint StubRoutines::x86::_k256[] =
ATTRIBUTE_ALIGNED(64) juint StubRoutines::x86::_k256_W[2*sizeof(StubRoutines::x86::_k256)];
ATTRIBUTE_ALIGNED(64) const julong StubRoutines::x86::_k512_W[] =
```

For gc code that uses ATTRIBUTE_ALIGNED, since they define their own macros that use it:

xGlobals.hpp:
`#define           XCACHE_ALIGNED                ATTRIBUTE_ALIGNED(XCacheLineSize)`

zGlobals.hpp:
`#define           ZCACHE_ALIGNED                ATTRIBUTE_ALIGNED(ZCacheLineSize)`

xMarkStack.hpp:
```
XCACHE_ALIGNED XMarkStackList _published;
XCACHE_ALIGNED XMarkStackList _overflowed;
```

xMarkStackAllocator.hpp:
```
XCACHE_ALIGNED XMarkStackMagazineList _freelist;
XCACHE_ALIGNED XMarkStackSpace        _space;
```

xMarkTerminate.hpp
`XCACHE_ALIGNED volatile uint _nworking_stage0;`

xNMethodTableIteration.hpp:
`XCACHE_ALIGNED volatile size_t _claimed;`

zMarkStack.hpp:
```
ZCACHE_ALIGNED ZMarkStackList _published;
ZCACHE_ALIGNED ZMarkStackList _overflowed;
```

zMarkStackAllocator.hpp:
```
ZCACHE_ALIGNED ZMarkStackSpace        _space;
ZCACHE_ALIGNED ZMarkStackMagazineList _freelist;
ZCACHE_ALIGNED volatile bool          _expanded_recently;
```

zNMethodTableIteration.hpp:
`ZCACHE_ALIGNED volatile size_t _claimed;`

Fortunately, it seems like that mismatched macro in the globalDefinitions file really is the only code in HotSpot where the alignas specifier is in an area that is semantically different in the C++ Language

**Comment by TheShermanTanker** [comment]
Bumping

**Comment by TheShermanTanker** [comment]
Anyone? There's confirmation that no other cases of the macro is in a position that causes issues without compiler errors...

**Comment by kimbarrett** [comment]
> Anyone? There's confirmation that no other cases of the macro is in a position that causes issues without compiler errors...

I plan to look at this again soon-ish, but swamped right now.

**Comment by TheShermanTanker** [comment]
Alright, thanks Kim :)

**Comment by TheShermanTanker** [comment]
Don't do that...

**Comment by TheShermanTanker** [comment]
Bumping

**Review by rkennke — APPROVED** [review]
This looks reasonable to me. Would be good to phase out the actual macro uses as well, in the future.
Also, would be great to be able to use offsetof() instead of offset_of() whereever this is possible.

**Comment by TheShermanTanker** [comment]
Thanks Roman, though I think there is discussion around offsetof and offset_of and the consensus was that it can't be replaced without causing issues, at least for now

**Comment by rkennke** [comment]
> Thanks Roman, though I think there is discussion around offsetof and offset_of and the consensus was that it can't be replaced without causing issues, at least for now

offsetof() can certainly not be replaced wholesale, because offset_of() is only specified to work for standard layout types. But I believe it could be used in places where we know that we are dealing with types that fit the spec. But I'm not deeply familiar with the constraints there.

**Review by kimbarrett — APPROVED** [review]
I think some of the uses of ZCACHE_ALIGNED might be wrong, but I don't think they are
made any worse by this change.  So looks good.

**Comment by TheShermanTanker** [comment]
Thanks Kim!

**Pull request closed without merging**
