### PR TITLE
8318607: Enable parallelism in vmTestbase/nsk/stress/jni tests

### PR DESCRIPTION
**Pull request by elifaslan1**
The commit includes changes to unblock parallelism for more `hotspot:tier4 `tests. in `test/hotspot/jtreg/vmTestbase/nsk/stress/jni `tests.

Below are the before and after test run comparisons:

Before:
 time,count
   32,    1
   63,    1
   64,    1
   94,    1
  124,    1
  155,    1
  185,    1
  216,    1

Mean               116.63s
Standard deviation  60.62s
Total elapsed time 3m 36s

After:
 time,count
    4,    1
   33,    1
   34,    2
   36,    3
   41,    1

Mean                31.75s
Standard deviation  10.73s
Total elapsed time 0m 41s

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318607](https://bugs.openjdk.org/browse/JDK-8318607): Enable parallelism in vmTestbase/nsk/stress/jni tests (**Enhancement** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16326/head:pull/16326` \
`$ git checkout pull/16326`

Update a local copy of the PR: \
`$ git checkout pull/16326` \
`$ git pull https://git.openjdk.org/jdk.git pull/16326/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16326`

View PR using the GUI difftool: \
`$ git pr show -t 16326`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16326.diff">https://git.openjdk.org/jdk/pull/16326.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16326#issuecomment-1776116186)

### CODE REVIEW

**Comment by elifaslan1** [comment]
@lmesnik could you please test this to your system and report the results? TIA

**Review by lmesnik — APPROVED** [review]
Looks good. Testing passed.

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
