### PR TITLE
8330539: Use #include <alloca.h> instead of -Dalloca'(size)'=__builtin_alloca'(size)' for AIX

### PR DESCRIPTION
**Pull request by JoKern65**
We need to find a better way to handle alloca on AIX.

See the discussion in the PR for https://bugs.openjdk.org/browse/JDK-8329257, e.g. https://github.com/openjdk/jdk/pull/18536#discussion_r1568650313 in which three alternatives are suggested. Quoting:

Let me summarize the choices we have and ask for your vote.
Magnus dislikes the -Dalloca'(size)'=__builtin_alloca'(size)' in flags-cflags.m4 I introduced to get rid of

#if defined(_AIX)
#include <alloca.h>
#endif

in globalDefinitions_gcc.hpp.

We have four possible solutions

1. Reintroduce

#if defined(_AIX)
#include <alloca.h>
#endif

in globalDefinitions_gcc.hpp.

2. Unconditionally introduce only #include <alloca.h> in globalDefinitions_gcc.hpp. This should work for all platforms using this header including the unofficial Windows/gcc Port, although only AIX needs it.

3. Add

#if defined(_AIX)
#include <alloca.h>
#endif

to the sources using alloca(). These are
/hotspot/share/runtime/os.cpp
/hotspot/share/runtime/javaThread.cpp
/hotspot/share/utilities/vmError.cpp
Here we need the AIX condition, because otherwise the classic Windows Build (NTAMD64) fails.

4. Replace -Dalloca'(size)'=__builtin_alloca'(size)' in flags-cflags.m4 by -U__STRICT_ANSI__ at the same place. Explanation can also found in https://github.com/openjdk/jdk/pull/18536#discussion_r1583360569 and following.

I will implement the solution with the most likes and having no dislike.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330539](https://bugs.openjdk.org/browse/JDK-8330539): Use #include &lt;alloca.h&gt; instead of -Dalloca'(size)'=__builtin_alloca'(size)' for AIX (**Bug** - P3)

### Reviewers
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19053/head:pull/19053` \
`$ git checkout pull/19053`

Update a local copy of the PR: \
`$ git checkout pull/19053` \
`$ git pull https://git.openjdk.org/jdk.git pull/19053/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19053`

View PR using the GUI difftool: \
`$ git pr show -t 19053`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19053.diff">https://git.openjdk.org/jdk/pull/19053.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19053#issuecomment-2090069229)

### CODE REVIEW

**Review by TheShermanTanker — APPROVED** [review]
I'd put alloca.h down below the Standard Headers, next to stuff like pthread.h and dlfcn.h, and have the AIX ifdef check so it's clearer that only AIX needs it, but otherwise no objections

**Comment by TheShermanTanker** [comment]
Compilation Failures are all unrelated to the actual change itself

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. This is my preferred solution. GHA failures are there because this PR is based on the code before https://github.com/openjdk/jdk/commit/286cbf831c2eb76e31bd69b4a93cd5ae9a821493 .

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
Looks good to me too.

**Comment by TheShermanTanker** [comment]
I stand corrected, it seems that MinGW distributions don't have alloca.h in their headers. No worries, the Windows/gcc Port will handle this downstream

**Pull request closed without merging**
