### PR TITLE
8272385: Enforce ECPrivateKey d value to be in the range [1, n-1] for SunEC provider

### PR DESCRIPTION
**Pull request by jnimeh**
This fix adds an EC private key range check for the scalar value to be within the range [1, n-1] (n being the order of the generator) for the SunEC ECDSA Signature algorithms and ECDH KeyAgreement algorithms.  While the SunEC KeyGenerator for EC keys will not generate private keys that sit outside the accepted range, it is possible to create and attempt to use ECPrivateKey objects that violate this range through a KeyFactory.

JBS: https://bugs.openjdk.java.net/browse/JDK-8272385

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272385](https://bugs.openjdk.java.net/browse/JDK-8272385): Enforce ECPrivateKey d value to be in the range [1, n-1] for SunEC provider

### Reviewers
 * [Anthony Scarpino](https://openjdk.java.net/census#ascarpino) (@ascarpino - **Reviewer**) ⚠️ Review applies to 864b9aaf746ee5443ddd1cd4a30e1cafe3972f64
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**) ⚠️ Review applies to 864b9aaf746ee5443ddd1cd4a30e1cafe3972f64

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5324/head:pull/5324` \
`$ git checkout pull/5324`

Update a local copy of the PR: \
`$ git checkout pull/5324` \
`$ git pull https://git.openjdk.java.net/jdk pull/5324/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5324`

View PR using the GUI difftool: \
`$ git pr show -t 5324`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5324.diff">https://git.openjdk.java.net/jdk/pull/5324.diff</a>

</details>

### CODE REVIEW

**Comment by wangweij** [comment]
So the key is only validated before it's used? Why not when creating it?

Do we need to validate public key as well? It might not be a problem since modular calculation should scale it back to normal. Our old native impl does have one at https://github.com/openjdk/jdk11u-dev/blob/master/src/jdk.crypto.ec/share/native/libsunec/impl/ec.c#L481.

One more thing: I would prefer `[1, n)` in the bug title. :-)

**Comment by jnimeh** [comment]
> So the key is only validated before it's used? Why not when creating it?
> 
> Do we need to validate public key as well? It might not be a problem since modular calculation should scale it back to normal. Our old native impl does have one at https://github.com/openjdk/jdk11u-dev/blob/master/src/jdk.crypto.ec/share/native/libsunec/impl/ec.c#L481.
> 
> One more thing: I would prefer `[1, n)` or `(0, n)` in the bug title, and, it's probably more efficient to call `sVal.compareTo(BigInteger.ZERO) <= 0` than `sVal.compareTo(BigInteger.ONE) < 0`.

Good questions.
WRT the KeyFactory, I looked not only at ours but also BC's and neither seems to put restrictions on ranges for an ECPrivateKey.  Given that behavior I thought for this change I'd leave KeyFactory alone.

Validating the public key might not be a bad idea.  I could come up with a Java-based version of what's in libsunec and update the test to cover that as well.

With respect to the synopsis, I'd prefer to leave it [1, n-1] because that's the notation used by FIPS 186-4, X9.62 and SEC 1.  But the BigInteger.compareTo I will change as you suggested.

**Review by ascarpino — APPROVED** [review]
Looks good to me

**Pull request closed without merging**
