### PR TITLE
8274349: ForkJoinPool.commonPool() does not work with 1 CPU

### PR DESCRIPTION
**Pull request by dholmes-ora**
A regression introduced in Java 17 will give the default FJ pool a parallelism of zero in a uniprocessor environment. The fix restores this to a value of 1. See bug report for details.

Testing:
 - new regression test
 - tiers 1-3

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274349](https://bugs.openjdk.java.net/browse/JDK-8274349): ForkJoinPool.commonPool() does not work with 1 CPU

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 666f36f43828e44e391bd6e6141253164f1b7747
 * [Martin Buchholz](https://openjdk.java.net/census#martin) (@Martin-Buchholz - **Reviewer**) ⚠️ Review applies to 666f36f43828e44e391bd6e6141253164f1b7747

### Contributors
 * Doug Lea `<dl@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5784/head:pull/5784` \
`$ git checkout pull/5784`

Update a local copy of the PR: \
`$ git checkout pull/5784` \
`$ git pull https://git.openjdk.java.net/jdk pull/5784/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5784`

View PR using the GUI difftool: \
`$ git pr show -t 5784`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5784.diff">https://git.openjdk.java.net/jdk/pull/5784.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Oh wow. Looks good!

**Comment by Martin-Buchholz** [comment]
I always try to avoid Thread.sleep or polling in tests, so I would write the test like this:

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ForkJoinPool;

public class ForkJoinUniProcessor {
    public static void main(String[] args) throws InterruptedException {
        // If the default parallelism were zero then this task would not
        // complete and the test will timeout.
        CountDownLatch ran = new CountDownLatch(1);
        ForkJoinPool.commonPool().submit(() -> ran.countDown());
        ran.await();
    }
}

**Review by Martin-Buchholz — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the reviews @shipilev  and @Martin-Buchholz !

Test updated per Martin's suggestion.

/integrate

**Pull request closed without merging**
