### PR TITLE
JDK-8299482: Remove metaprogramming/isIntegral.hpp

### PR DESCRIPTION
**Pull request by jcking**
Code cleanup of pre-C++11 <type_traits> implementations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299482](https://bugs.openjdk.org/browse/JDK-8299482): Remove metaprogramming/isIntegral.hpp

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [a22853dc](https://git.openjdk.org/jdk/pull/11818/files/a22853dc7cd163cce74ba4ed2e9fb43463839850)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [a22853dc](https://git.openjdk.org/jdk/pull/11818/files/a22853dc7cd163cce74ba4ed2e9fb43463839850)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11818/head:pull/11818` \
`$ git checkout pull/11818`

Update a local copy of the PR: \
`$ git checkout pull/11818` \
`$ git pull https://git.openjdk.org/jdk pull/11818/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11818`

View PR using the GUI difftool: \
`$ git pr show -t 11818`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11818.diff">https://git.openjdk.org/jdk/pull/11818.diff</a>

</details>

### CODE REVIEW

**Comment by jcking** [comment]
@kimbarrett Another one.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by tschatzl — APPROVED** [review]

**Comment by jcking** [comment]
Forgot to remove the actual header apparently, updated.

**Pull request closed without merging**
