### PR TITLE
JDK-8309032: jpackage does not work for module projects unless --module-path is specified

### PR DESCRIPTION
**Pull request by airsquared**
[JDK-8309032](https://bugs.openjdk.org/browse/JDK-8309032), [JDK-8306488](https://bugs.openjdk.org/browse/JDK-8306488)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309032](https://bugs.openjdk.org/browse/JDK-8309032): jpackage does not work for module projects unless --module-path is specified (**Bug** - P4)

### Reviewers
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)
 * [Alexander Matveev](https://openjdk.org/census#almatvee) (@sashamatveev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14840/head:pull/14840` \
`$ git checkout pull/14840`

Update a local copy of the PR: \
`$ git checkout pull/14840` \
`$ git pull https://git.openjdk.org/jdk.git pull/14840/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14840`

View PR using the GUI difftool: \
`$ git pr show -t 14840`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14840.diff">https://git.openjdk.org/jdk/pull/14840.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14840#issuecomment-1638787366)

### CODE REVIEW

**Comment by airsquared** [comment]
@alexeysemenyukoracle would you be able to sponsor this change? Thanks!

**Comment by alexeysemenyukoracle** [comment]
@sashamatveev would you like to review the change before I sponsor it?

**Review by sashamatveev — APPROVED** [review]

**Comment by sashamatveev** [comment]
@alexeysemenyukoracle Looks good.

**Comment by airsquared** [comment]
This also resolved [JDK-8306488](https://bugs.openjdk.org/browse/JDK-8306488), if someone can mark it as such.

**Pull request closed without merging**
