### PR TITLE
8337674: ZGC: Consistent style for naming private static constants

### PR DESCRIPTION
**Pull request by jsikstro**
There are various styles for naming private static constants in ZGC. Some have a leading underscore, some begin with a lowercase letter and some start with an uppercase letter. The convention we feel is most appropriate, which also aligns with the hotspot style guide, is to have mixed-case with the first letter of each word capitalized when naming private static constants. There are also some occurrences of writing `const static` instead of the more commonly used `static const`, which should be made consistent to have the static keyword appear first.

The lines changed have been identified by running:
`rg "static const .* [[:lower:]].* =" src/hotspot/share/gc/z src/hotspot/*/*/gc/z`
`rg "static const .* _.* =" src/hotspot/share/gc/z src/hotspot/*/*/gc/z`
`rg "const static" src/hotspot/share/gc/z src/hotspot/*/*/gc/z`

The occurrences of `const static valid_max_address_offset_bits` have been converted to `static const` from `const static` but have not been renamed to mixed-case as the occurrences are not exposed outside their function(s).

Tested with tiers 1-3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337674](https://bugs.openjdk.org/browse/JDK-8337674): ZGC: Consistent style for naming private static constants (**Enhancement** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20968/head:pull/20968` \
`$ git checkout pull/20968`

Update a local copy of the PR: \
`$ git checkout pull/20968` \
`$ git pull https://git.openjdk.org/jdk.git pull/20968/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20968`

View PR using the GUI difftool: \
`$ git pr show -t 20968`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20968.diff">https://git.openjdk.org/jdk/pull/20968.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20968#issuecomment-2346382409)

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Review by Hamlin-Li — APPROVED** [review]

**Comment by jsikstro** [comment]
Thank you for the reviews! @stefank @xmas92 @Hamlin-Li 
/integrate

**Pull request closed without merging**
