### PR TITLE
JDK-8259681 : Remove the Marlin rendering engine (single-precision)

### PR DESCRIPTION
**Pull request by bourgesl**
- Removed MarlinRenderingEngine and related classes
- Fixed jtreg tests to remove explicit test runs on MarlinRenderingEngine
- Marlin Version set to 0.9.1.4

Jtreg tests [test/jdk/sun/java2d/marlin/] : OK

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259681](https://bugs.openjdk.java.net/browse/JDK-8259681): Remove the Marlin rendering engine (single-precision)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2076/head:pull/2076`
`$ git checkout pull/2076`

### CODE REVIEW

**Comment by bourgesl** [comment]
Apparently windows x64 build failed: no C compiler found !

**Comment by prrace** [comment]
> Apparently windows x64 build failed: no C compiler found !

Other PRs have the same issue. I suppose problem with github actions. Maybe the github default compiler change.

**Comment by mrserb** [comment]
I'll start internal testing.

**Comment by mrserb** [comment]
please update the copyright dates

**Review by mrserb — APPROVED** [review]

**Comment by bourgesl** [comment]
Sergey, I slightly modified the reviewed change:
see incremental changes: https://openjdk.github.io/cr/?repo=jdk&pr=2076&range=01-02

**Comment by bourgesl** [comment]
One more idea: 
should I rename all Dxxx classes to xxx to make code more obvious, readable ?

However, renaming DMarlinRenderingEngine to MarlinRenderingEngine may lead confusion with previous versions and may be a compatibility issue ? so I would prefer keeping DMarlinRenderingEngine now.

What do you think ?

**Comment by mrserb** [comment]
> However, renaming DMarlinRenderingEngine to MarlinRenderingEngine may lead confusion with previous versions and may be a compatibility issue ? so I would prefer keeping DMarlinRenderingEngine now.

I agree with you.

**Comment by kevinrushforth** [comment]
I also agree with this. Similarly, when you go to remove the single-precision `MarlinRasterizer` from JavaFX, via [JDK-8259718](https://bugs.openjdk.java.net/browse/JDK-8259718), I would expect to see `DMarlinRasterizer` and similar names to remain.

**Review by mrserb — APPROVED** [review]

**Comment by bourgesl** [comment]
Sergey, I made the class refactoring, more clear in incremental webrev:
https://openjdk.github.io/cr/?repo=jdk&pr=2076&range=02-03
Still Approved ?

**Comment by bourgesl** [comment]
Forgot to fix copyright year on renamed classes, sorry

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
