### PR TITLE
8272094: compiler/codecache/TestStressCodeBuffers.java crashes with "failed to allocate space for trampoline"

### PR DESCRIPTION
**Pull request by theRealAph**
This problem is, I believe, caused by an assertion left in the source code after development.
The fix is simply to remove the assertion.

It's not at all easy to reproduce this bug, being a very intermittent failure, but in the end I reproduced it by making `-XX:+StressCodeBuffers` much more stressful, like so:
```

diff --git a/src/hotspot/share/asm/codeBuffer.cpp b/src/hotspot/share/asm/codeBuffer.cpp
index ddd946d7542..c74ba21cf63 100644
--- a/src/hotspot/share/asm/codeBuffer.cpp
+++ b/src/hotspot/share/asm/codeBuffer.cpp
@@ -837,7 +837,8 @@ void CodeBuffer::expand(CodeSection* which_cs, csize_t amount) {
   if (StressCodeBuffers && blob() != NULL) {
     static int expand_count = 0;
     if (expand_count >= 0)  expand_count += 1;
-    if (expand_count > 100 && is_power_of_2(expand_count)) {
+    if (expand_count > 100 && // is_power_of_2(expand_count)
+        expand_count % 40 == 0) {
       tty->print_cr("StressCodeBuffers: have expanded %d times", expand_count);
       // simulate an occasional allocation failure:
       free_blob();

```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8272094](https://bugs.openjdk.java.net/browse/JDK-8272094): compiler/codecache/TestStressCodeBuffers.java crashes with "failed to allocate space for trampoline"

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [c06acfac](https://git.openjdk.java.net/jdk/pull/8730/files/c06acfaced3272ef9f5c240d79948f3bca3d2877)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8730/head:pull/8730` \
`$ git checkout pull/8730`

Update a local copy of the PR: \
`$ git checkout pull/8730` \
`$ git pull https://git.openjdk.java.net/jdk pull/8730/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8730`

View PR using the GUI difftool: \
`$ git pr show -t 8730`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8730.diff">https://git.openjdk.java.net/jdk/pull/8730.diff</a>

</details>

### CODE REVIEW

**Comment by theRealAph** [comment]
> Okay, so what is supposed to happen on failure? I see `aarch64.ad` has two rules that use `__ zero_words`.
> 
> `clearArray_reg_reg` does:
> 
> ```
>     address tpc = __ zero_words($base$$Register, $cnt$$Register);
>     if (tpc == NULL) {
>       ciEnv::current()->record_failure("CodeCache is full");
>       return;
>     }
> ```
> 
> ...while `clearArray_imm_reg` calls through to `MacroAssembler::zero_words(Register base, uint64_t cnt)`, which still enters this method without checking the result? Maybe the predicate saves us here, IDK.

Good catch. Yes, it is saved by the predicate, which is `cnt < (BlockZeroingLowLimit >> LogBytesPerWord)`. The macro checks for `cnt <= (uint64_t)BlockZeroingLowLimit / BytesPerWord`, and in that case generates a short inline sequence. It's pretty evil code, though. (Can we say "pathological coupling"?. I think I'll add a check, although it will be unreachable in the current source because of the predicate.

**Review by shipilev — APPROVED** [review]
I would just do `return pc()` and `return zero_words(...)`. Or at least initialize `address result = nullptr;`?

**Comment by theRealAph** [comment]
> I would just do `return pc()` and `return zero_words(...)`. Or at least initialize `address result = nullptr;`?

I'd rather the branches in an if/else likr this come together at the end than jump out in the middle. But yes, i take your point about the initialization.

**Review by vnkozlov — APPROVED** [review]
Good.

**Pull request closed without merging**
