### PR TITLE
8285394: Compiler blackholes can be eliminated due to stale ciMethod::intrinsic_id()

### PR DESCRIPTION
**Pull request by shipilev**
This is seen in some tests: if blackhole method is deemed hot for inlining, then at least C2 would inline it without looking back at its intrinsic status. Which silently breaks blackholes.

The cause is that there are *two* places where intrinsic ID is recorded. Current blackhole code only writes down blackhole intrinsic ID in `Method::intrinsic_id()`, but we should also set it in `ciMethod::intrinsic_id()`, which is used from C2 inlining code. `ciMethod` is normally populated from `Method::intrinsic_id()`, but it happens too early, before setting up blackhole intrinsic. 

Additional testing:
 - [x] Linux x86_64 {fastdebug,release}, wew test fails before the patch, passes with it
 - [x] Linux x86_64 {fastdebug,release} `compiler/blackhole`
 - [x] Linux x86_64 fastdebug, sanity microbenchmark corpus run with the patch

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285394](https://bugs.openjdk.java.net/browse/JDK-8285394): Compiler blackholes can be eliminated due to stale ciMethod::intrinsic_id()

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8344/head:pull/8344` \
`$ git checkout pull/8344`

Update a local copy of the PR: \
`$ git checkout pull/8344` \
`$ git pull https://git.openjdk.java.net/jdk pull/8344/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8344`

View PR using the GUI difftool: \
`$ git pr show -t 8344`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8344.diff">https://git.openjdk.java.net/jdk/pull/8344.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Good. Need to test it.

**Review by vnkozlov — APPROVED** [review]
Testing passed.

**Review by dean-long — CHANGES_REQUESTED** [review]
Wouldn't it be better to call tag_blackhole_if_possible() in Method::init_intrinsic_id()?  Or is it considered an expensive operation and only the compilers (and never, say, the interpreter) would ever care about this?  If it is an expensive operation, and we call it for every ciMethod, then maybe tag_blackhole_if_possible() should check for "already set" first thing.

**Comment by shipilev** [comment]
> Wouldn't it be better to call tag_blackhole_if_possible() in Method::init_intrinsic_id()? Or is it considered an expensive operation and only the compilers (and never, say, the interpreter) would ever care about this? 

Looking up `CompilerOracle` commands can be surprisingly expensive, especially with large compiler command lists. Nils optimized the lookups quite well (after all, we do a similar lookup for inline/dontinline at compilation time), but it is still not completely free. But the reason we settled to do the tagging here is that only compilers care about this intrinsic, and putting the calls to `CompilerOracle` in otherwise compiler-agnostic runtime code (`Method`) introduced the unfortunate level of cohesion.

> If it is an expensive operation, and we call it for every ciMethod, then maybe tag_blackhole_if_possible() should check for "already set" first thing.

Maybe. That looks like a minor performance optimization, which I would like to keep out of this bugfixing PR, OK? Out of curiosity, I instrumented `tag_blackhole_if_possible`, and on Spring startup we do about 70K lookups and "already set" filter can filter about 9K of them.

**Review by dean-long — APPROVED** [review]
OK.

**Comment by shipilev** [comment]
Thanks for reviews!

/integrate

**Pull request closed without merging**
