### PR TITLE
8295110: RISC-V: Mark out relocations as incompressible

### PR DESCRIPTION
**Pull request by zhengxiaolinX**
This patch marks all relocations incompressible as pre-discussions at [1] and converts instructions to their 2-byte compressible counterparts as much as possible when UseRVC is enabled.

Chaining PR #10421.

1. Code size reduction rate: about ~17% now after this patch under RVC, meaning if there's a piece of code of 1000 bytes, it may shrink to 830 bytes when RVC is enabled. [2]
2. Performance: conservatively no regressions observed. [3]

The overloaded `relocate()` methods hide `IncompressibleRegion`s inside, to exclude instructions used at relocations from being compressed.

Having tested several times hotspot tier1~tier4; Testing another turn on board.

[1] https://mail.openjdk.org/pipermail/riscv-port-dev/2022-September/000615.html
[2] https://mail.openjdk.org/pipermail/riscv-port-dev/2022-September/000633.html
[3] https://mail.openjdk.org/pipermail/riscv-port-dev/2022-October/000656.html

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295110](https://bugs.openjdk.org/browse/JDK-8295110): RISC-V: Mark out relocations as incompressible

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Yadong Wang](https://openjdk.org/census#yadongwang) (@yadongw - Author) ⚠️ Review applies to [83f3598a](https://git.openjdk.org/jdk/pull/10643/files/83f3598a9fb3cdb3939a4dec9a6a5902561dae39)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10643/head:pull/10643` \
`$ git checkout pull/10643`

Update a local copy of the PR: \
`$ git checkout pull/10643` \
`$ git pull https://git.openjdk.org/jdk pull/10643/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10643`

View PR using the GUI difftool: \
`$ git pr show -t 10643`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10643.diff">https://git.openjdk.org/jdk/pull/10643.diff</a>

</details>

### CODE REVIEW

**Comment by RealFYang** [comment]
Personally, I prefer the following style:
```
  __ relocate(spec, [&] {
      int32_t off = 0;
      la_patchable(t0, RuntimeAddress(entry), off);
      jalr(x1, t0, off);
  });
```
Then the code looks more unified to me.

**Comment by zhengxiaolinX** [comment]
> Personally, I prefer the following style:
> 
> ```
>   __ relocate(spec, [&] {
>       int32_t off = 0;
>       la_patchable(t0, RuntimeAddress(entry), off);
>       jalr(x1, t0, off);
>   });
> ```
> 
> Then the code looks more unified to me. And we don't need to extend a new la_patchable interface.

Done - code expands a little for the `relocate()` inside `la_patchable()` is extracted to their outer callers explicitly.

**Review by RealFYang — APPROVED** [review]
Updated change looks good. Thanks.

**Review by yadongw — APPROVED** [review]
lgtm

**Comment by zhengxiaolinX** [comment]
Thanks for reviewing! @RealFYang @yadongw 

Will wait for #10697 to be merged first for it seems needs a redo if mine goes first.

**Review by RealFYang — APPROVED** [review]
Thanks for rebasing this. Still looks good.

**Comment by zhengxiaolinX** [comment]
Test results (new code in this patch) on QEMU & my board in the several days look okay.

/integrate

**Pull request closed without merging**
