### PR TITLE
8301005: Clean up Copy::conjoint_*_atomic on windows

### PR DESCRIPTION
**Pull request by fisk**
The atomic copying code on windows has some logic that has been copy pasted for a bunch of types with the only difference being the type. Unfortunately, the jlong copying is using oop copying (even though the values are not at all oops), which isn't super nice. Moreover, this copy pasted sequence isn't actually using Atomic, even though it's for atomic copying, which also isn't super nice. This needs a cleanup, and this patch aims to fix that.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301005](https://bugs.openjdk.org/browse/JDK-8301005): Clean up Copy::conjoint_*_atomic on windows

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12197/head:pull/12197` \
`$ git checkout pull/12197`

Update a local copy of the PR: \
`$ git checkout pull/12197` \
`$ git pull https://git.openjdk.org/jdk pull/12197/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12197`

View PR using the GUI difftool: \
`$ git pr show -t 12197`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12197.diff">https://git.openjdk.org/jdk/pull/12197.diff</a>

</details>

### CODE REVIEW

**Review by xmas92 — APPROVED** [review]
lgtm.

**Comment by fisk** [comment]
Thanks for the review, @xmas92!

**Review by stefank — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Comment by fisk** [comment]
Thank you for the reviews, @tschatzl and @stefank!

**Pull request closed without merging**
