### PR TITLE
JDK-8297164: Update troff man pages and CheckManPageOptions.java

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review an update for the troff man pages, following the recent update to upgrade to use pandoc 2.19.2
(See https://bugs.openjdk.org/browse/JDK-8297165)

In conjunction with this, one javadoc test also needs to be updated, to work with the new form of output generated by the new version of pandoc.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297164](https://bugs.openjdk.org/browse/JDK-8297164): Update troff man pages and CheckManPageOptions.java

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [1413ee26](https://git.openjdk.org/jdk/pull/11223/files/1413ee26d9e34f4345c2667140da0e71e03d0e53)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11223/head:pull/11223` \
`$ git checkout pull/11223`

Update a local copy of the PR: \
`$ git checkout pull/11223` \
`$ git pull https://git.openjdk.org/jdk pull/11223/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11223`

View PR using the GUI difftool: \
`$ git pr show -t 11223`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11223.diff">https://git.openjdk.org/jdk/pull/11223.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi @jonathan-gibbons ,

I notice that in the new version dash characters are no longer escaped as `\-`, do these still display correctly?

**Comment by jonathan-gibbons** [comment]
> Hi @jonathan-gibbons ,
> 
> I notice that in the new version dash characters are no longer escaped as `\-`, do these still display correctly?

Yes, at least in all the files I verified and I have no reason to believe it might be different in any other files.

**Review by dholmes-ora — APPROVED** [review]
Looks okay.

Thanks for doing this before the end-of-release updates!

**Comment by dfuch** [comment]
The diffs are a bit difficult to read but I didn't spot anything obviously wrong with jwebserver. I could see that the new compress option was there in jmod man page too. +1.

**Pull request closed without merging**
