### PR TITLE
8265794: Remove ProblemList-non-cds-mode

### PR DESCRIPTION
**Pull request by mseledts**
Please review this trivial change.

This list has been empty for a long time, and no changes in history since Oct 2018. If we see any issues in non-CDS mode (-Xshare:off) testing in the future (which is very unlikely), we should simply use generic ProblemList to exclude such failing tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265794](https://bugs.openjdk.java.net/browse/JDK-8265794): Remove ProblemList-non-cds-mode

### Reviewers
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3643/head:pull/3643` \
`$ git checkout pull/3643`

Update a local copy of the PR: \
`$ git checkout pull/3643` \
`$ git pull https://git.openjdk.java.net/jdk pull/3643/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3643`

View PR using the GUI difftool: \
`$ git pr show -t 3643`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3643.diff">https://git.openjdk.java.net/jdk/pull/3643.diff</a>

</details>

### CODE REVIEW

**Comment by mseledts** [comment]
@calvinccheung @iklam could you please review when you have a chance ?

**Comment by iignatev** [comment]
not that keeping this file costs us a lot, but I'm fine with the change, and I agree that it's a trivial one.

-- Igor

**Review by calvinccheung — COMMENTED** [review]
I think some task definitions refer to this ProblemList and those need to be updated too.

**Review by iklam — APPROVED** [review]
Look good to me.

**Review by calvinccheung — APPROVED** [review]
Looks good. (I saw the changes to the task definitions in another PR.)

**Review by iignatev — APPROVED** [review]

**Comment by mseledts** [comment]
Calvin, Ioi, Igor, thank you for review.
/integrate

**Pull request closed without merging**
