### PR TITLE
8343426: ConcurrentSkipListMap.spliterator() can no longer split the stream

### PR DESCRIPTION
**Pull request by kabutz**
Since Java 10, spliterators for the ConcurrentSkipListMap were pointing to the head, which has item == null, rather than to the first element. The trySplit() method no longer worked, and always returned null. Therefore, parallel streams have not worked for ConcurrentSkipListMap and ConcurrentSkipListSet since Java 10. It worked correctly in Java 8 and 9.

The problem lies in the constructor calls for the various spliterators. In Java 9, we pass in head.node.next as "origin" into the  constructor. In Java 10, this was changed to just head.node as "origin". Since the "item" field is always null on head.node, we never enter the first if() statement in the trySplit() method and thus it always returns null.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343426](https://bugs.openjdk.org/browse/JDK-8343426): ConcurrentSkipListMap.spliterator() can no longer split the stream (**Bug** - P3)

### Reviewers
 * [Viktor Klang](https://openjdk.org/census#vklang) (@viktorklang-ora - **Reviewer**)

### Contributors
 * Doug Lea `<dl@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21820/head:pull/21820` \
`$ git checkout pull/21820`

Update a local copy of the PR: \
`$ git checkout pull/21820` \
`$ git pull https://git.openjdk.org/jdk.git pull/21820/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21820`

View PR using the GUI difftool: \
`$ git pr show -t 21820`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21820.diff">https://git.openjdk.org/jdk/pull/21820.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21820#issuecomment-2451644383)
</details>

### CODE REVIEW

**Comment by viktorklang-ora** [comment]
Hi @kabutz,
Interesting catch!
A regression test (splitability) and a test which verifies correct operation under parallel evaluation would be appropriate here.

**Comment by kabutz** [comment]
Sure, where should I add that test?

**Comment by viktorklang-ora** [comment]
@kabutz I'd say either under its own directory `test/jdk/java/util/concurrent/ConcurrentSkipListMap/` or possibly in `test/jdk/java/util/concurrent/tck/ConcurrentSkipListMapTest.java`.

**Comment by viktorklang-ora** [comment]
@kabutz I think @DougLea identified some potential edge-cases with the proposed solution, so I added his suggested diff to the JBS Issue for reference.

**Comment by viktorklang-ora** [comment]
@kabutz Let me know how you want to proceed. 👍

**Comment by kabutz** [comment]
> @kabutz Let me know how you want to proceed. 👍

've made the changes and sent another PR to the branch holding the changes. Hope that's the right way of doing it...

**Comment by viktorklang-ora** [comment]
@kabutz Ah, so then you can close this PR? I'll have a look at the other PR.

**Comment by viktorklang-ora** [comment]
@kabutz Might actually be easier to drop the other PR and add the commits to your branch [8343426-cslm-spliterator-bug](https://github.com/kabutz/jdk/tree/8343426-cslm-spliterator-bug) so this PR is updated.

**Comment by viktorklang-ora** [comment]
@kabutz The update for CSLM is based on @DougLea's proposal on the JBS issue, right? (Assuming that's the case I will add him as a co-contributor)

**Comment by kabutz** [comment]
> JBS

Yes, correct.

**Comment by viktorklang-ora** [comment]
@kabutz The OpenJDK bot doesn't trust me :-) would you mind adding Doug as a contributor? :)

**Comment by viktorklang-ora** [comment]
Thanks @kabutz & @DougLea!

**Pull request closed without merging**
