### PR TITLE
8291972: Fix double copy of arguments when thawing two interpreted frames

### PR DESCRIPTION
**Pull request by pchilano**
When thawing two consecutive interpreted frames the current code makes room in the stack and copies the callee arguments twice, once in the caller and once in the callee. This duplication could use more stack space than the calculation made in prepare_thaw() for the maximum stack space that will be needed during thaw. If that's the case then we will hit an assert that we are writing pass the allowed limit.
Today we don't see this issue though because the only case where we could thaw two interpreter frames is the first time after a freeze. The thawed frames are always Continuation.yield and Continuation.yield0 and the extra used space is only 3 words(yield0's three arguments) which will never exceed the calculation made in prepare_thaw(). 
The issue can be made visible when changing the number of frames we thaw when hitting a return barrier from 1 to 2 and running test Continuation/Basic.java.

This patch fixes this by adjusting the calculated size of the callee frame in new_stack_frame() so that we use the space for the arguments already allocated by the caller. 

Tested the patch by changing the number of thaw frames from 1 to 2 and running all tests in jdk/internal/vm/Continuation/ and jdk/java/lang/Thread/virtual. Also run tiers1-3 in mach5 and loom-tiers1-4.

Thanks,
Patricio

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291972](https://bugs.openjdk.org/browse/JDK-8291972): Fix double copy of arguments when thawing two interpreted frames

### Reviewers
 * [Ron Pressler](https://openjdk.org/census#rpressler) (@pron - Committer) ⚠️ Review applies to [47cf7dce](https://git.openjdk.org/jdk/pull/9774/files/47cf7dce3a34e31fb872e8ef111f4572fe3ab372)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**) ⚠️ Review applies to [47cf7dce](https://git.openjdk.org/jdk/pull/9774/files/47cf7dce3a34e31fb872e8ef111f4572fe3ab372)
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**) ⚠️ Review applies to [47cf7dce](https://git.openjdk.org/jdk/pull/9774/files/47cf7dce3a34e31fb872e8ef111f4572fe3ab372)

### Contributors
 * Richard Reingruber `<rrich@openjdk.org>`
 * Patricio Chilano Mateo `<pchilanomate@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9774/head:pull/9774` \
`$ git checkout pull/9774`

Update a local copy of the PR: \
`$ git checkout pull/9774` \
`$ git pull https://git.openjdk.org/jdk pull/9774/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9774`

View PR using the GUI difftool: \
`$ git pr show -t 9774`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9774.diff">https://git.openjdk.org/jdk/pull/9774.diff</a>

</details>

### CODE REVIEW

**Review by pron — APPROVED** [review]
Looks fine to me.

**Review by robehn — APPROVED** [review]
Thank you!

**Review by reinrich — APPROVED** [review]
This looks good!

https://github.com/openjdk/jdk/pull/9850 duplicates this. It contains a reproducer test that asserts on aarch64. The test does not fail on x86_64 because padding for interpreter frames is added that is not needed on x86_64. Without that the test also asserts on x86_64 (see JDK-8292278).

Thanks, Richard.

**Comment by pchilano** [comment]
Thanks @pron, @robehn and @reinrich for the reviews!

**Comment by pchilano** [comment]
@reinrich If you want to add that test I can add it here and list you as contributor or you can still push it in your PR once you are back. Let me know otherwise I will just integrate the fix.

**Comment by reinrich** [comment]
> @reinrich If you want to add that test I can add it here and list you as contributor or you can still push it in your PR once you are back. Let me know otherwise I will just integrate the fix.

Please add the test here if you think it is good. I'll close #9850 then.

**Comment by pchilano** [comment]
Added Richard's test and run on both x64 and aarch64. Verified it fails on aarch64 without this fix and passes with it.

**Pull request closed without merging**
