### PR TITLE
7033677: potential cast error in MemberEnter

### PR DESCRIPTION
**Pull request by archiecobbs**
In an `import` statement, the thing imported is always a `JCFieldAccess` (it's not legal in Java to import a simple name).

Therefore the type of `JCFieldAccess.qualid`, which is currently `JCTree`, is unnecessarily wide and can be narrowed to `JCFieldAccess`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-7033677](https://bugs.openjdk.org/browse/JDK-7033677): potential cast error in MemberEnter

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [6fdc874d](https://git.openjdk.org/jdk/pull/12606/files/6fdc874dc35c476008f20eb13892a85c2e242937)
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12606/head:pull/12606` \
`$ git checkout pull/12606`

Update a local copy of the PR: \
`$ git checkout pull/12606` \
`$ git pull https://git.openjdk.org/jdk pull/12606/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12606`

View PR using the GUI difftool: \
`$ git pr show -t 12606`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12606.diff">https://git.openjdk.org/jdk/pull/12606.diff</a>

</details>

### CODE REVIEW

**Comment by vicente-romero-oracle** [comment]
not sure as the JLS, section: `7.5.1 Single-Type-Import Declarations` has this rule:

```
SingleTypeImportDeclaration:
    import TypeName ;
```

**Comment by archiecobbs** [comment]
> not sure as the JLS, section: `7.5.1 Single-Type-Import Declarations` has this rule:
> 
> ```
> SingleTypeImportDeclaration:
>     import TypeName ;
> ```

Yes - but it then says:

> The class or interface must be either a member of a named package, or a member of a class or interface whose outermost lexically enclosing class or interface declaration ([§8.1.3](https://docs.oracle.com/javase/specs/jls/se19/html/jls-8.html#jls-8.1.3)) is a member of a named package, or a compile-time error occurs.

Also, the parser won't accept a single identifier.

**Comment by lahodaj** [comment]
Looks reasonable to me, but please note that `test/langtools/jdk/javadoc/tool/sampleapi/lib/sampleapi/generator/PackageGenerator.java` needs to be fixed as well - on line 280. (Please see the results from GitHub Actions.)

**Comment by archiecobbs** [comment]
> Looks reasonable to me, but please note that `test/langtools/jdk/javadoc/tool/sampleapi/lib/sampleapi/generator/PackageGenerator.java` needs to be fixed as well

Oops - thanks. Should be fixed now.

**Pull request closed without merging**
