### PR TITLE
8264958: C2 compilation fails with assert "n is later than its clone"

### PR DESCRIPTION
**Pull request by rwestrel**
JDK-8229483 added logic to hoist a load that would wrongly end up in
an outer strip mined loop. That logic checks that it's legal to do so
with:

is_dominator(n_ctrl, x_head)

but that test passes for n_ctrl == x_head when it's not legal to hoist
the load i.e. the test we want is for strict domination. The fix I
propose is to add an explicit check for that case.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264958](https://bugs.openjdk.java.net/browse/JDK-8264958): C2 compilation fails with assert "n is later than its clone"

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3539/head:pull/3539` \
`$ git checkout pull/3539`

Update a local copy of the PR: \
`$ git checkout pull/3539` \
`$ git pull https://git.openjdk.java.net/jdk pull/3539/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3539`

View PR using the GUI difftool: \
`$ git pr show -t 3539`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3539.diff">https://git.openjdk.java.net/jdk/pull/3539.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good!

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by rwestrel** [comment]
@neliasso @TobiHartmann thanks for the review

**Pull request closed without merging**
