### PR TITLE
8345405: Add JMH showing the regression in 8341649

### PR DESCRIPTION
**Pull request by ericcaspole**
This JMH using MethodHandles shows the regression in 8341649, for example comparing 24-b25, which included the regression to today's head. It was an interaction between the runtime and C2 rather than a change in MethodHandles.

Here are example results from an Ampere platform:
jdk-24-b25 before the fix:
Benchmark                (classes)  (instances)   Mode  Cnt   Score   Error   Units
MethodHandleStress.work       1000          100  thrpt   20  33.423 ± 7.678  ops/ms

Today's head with the fix:
Benchmark                (classes)  (instances)   Mode  Cnt    Score    Error   Units
MethodHandleStress.work       1000          100  thrpt   20  709.249 ± 50.575  ops/ms

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345405](https://bugs.openjdk.org/browse/JDK-8345405): Add JMH showing the regression in 8341649 (**Enhancement** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) Review applies to [4c7ee932](https://git.openjdk.org/jdk/pull/22556/files/4c7ee93271376a5085562207f7eff60ff6afbf2f)
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22556/head:pull/22556` \
`$ git checkout pull/22556`

Update a local copy of the PR: \
`$ git checkout pull/22556` \
`$ git pull https://git.openjdk.org/jdk.git pull/22556/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22556`

View PR using the GUI difftool: \
`$ git pr show -t 22556`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22556.diff">https://git.openjdk.org/jdk/pull/22556.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22556#issuecomment-2518348383)
</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Thank you for adding this test. Looks good to me.

**Review by cl4es — APPROVED** [review]

**Pull request closed without merging**
