### PR TITLE
JDK-8302455: VM.classloader_stats memory size values are wrong

### PR DESCRIPTION
**Pull request by tstuefe**
VM.classloader_stats shows metaspace consumption in words, but should show bytes. 

Patch fixes that, and adjusts the associated jtreg test to catch regressions like this.

I manually tested the test with the unpatched hotspot to see if the regression shows up, it does.

Tested the patch on x64 (fastdebug, release) and x86.

Note: "calculate_jfr_stats" is misnamed, actually only ever used by this dcmd, not by jfr. I will clear this up in a separate RFE.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302455](https://bugs.openjdk.org/browse/JDK-8302455): VM.classloader_stats memory size values are wrong

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [2be3a810](https://git.openjdk.org/jdk/pull/12556/files/2be3a810493f91a1c5b9a4c85229bdd9a70d2304)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12556/head:pull/12556` \
`$ git checkout pull/12556`

Update a local copy of the PR: \
`$ git checkout pull/12556` \
`$ git pull https://git.openjdk.org/jdk pull/12556/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12556`

View PR using the GUI difftool: \
`$ git pr show -t 12556`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12556.diff">https://git.openjdk.org/jdk/pull/12556.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good.

**Comment by dholmes-ora** [comment]
So in addition to the poor name, the declaration is wrong:
```
 void calculate_jfr_stats(size_t* p_used_bytes, size_t* p_capacity_bytes) const;
```
as it refers to bytes not words. Perhaps better to clean this up completely in this issue rather than a separate RFE?

**Comment by dholmes-ora** [comment]
That said, given:
```
// This only exists for JFR and jcmd VM.classloader_stats. We may want to
//  change this. Capacity as a stat is of questionable use since it may
//  contain committed and uncommitted areas. For now we do this to maintain
//  backward compatibility with JFR.
```
and the fact this is not used by JFR then maybe it should all just be removed?

**Comment by tstuefe** [comment]
> That said, given:
> 
> ```
> // This only exists for JFR and jcmd VM.classloader_stats. We may want to
> //  change this. Capacity as a stat is of questionable use since it may
> //  contain committed and uncommitted areas. For now we do this to maintain
> //  backward compatibility with JFR.
> ```
> 
> and the fact this is not used by JFR then maybe it should all just be removed?

That's my plan, but I'd like to do this in a follow-up RFE. The patch I'd like to keep minimal for easy downport. I'd like to keep cleanups separate.

**Comment by dholmes-ora** [comment]
Given the reason this bug likely arose is the fact the parameters to `calculate_jfr_stats` say they are "bytes" then fixing that is not a mere cleanup IMO. Can we at least fix that in this PR?

**Comment by tstuefe** [comment]
> Given the reason this bug likely arose is the fact the parameters to `calculate_jfr_stats` say they are "bytes" then fixing that is not a mere cleanup IMO. Can we at least fix that in this PR?

Hi David, I reformed the ill-named function and renamed it to "usage_numbers", because that name and prototype is used in other places in Metaspace as well (e.g. MetaspaceArena), so its a uniform scheme.

**Review by dholmes-ora — APPROVED** [review]
Looks good. The `usage_numbers` changes were a bit more involved then I had expected but they seem fine.

Thanks.

**Comment by tstuefe** [comment]
Thanks David!

/integrate

**Pull request closed without merging**
