### PR TITLE
8268241: deprecate JVM TI Heap functions 1.0

### PR DESCRIPTION
**Pull request by sspitsyn**
The JVM TI Heap functions 1.0 were superseded by newer functions in JVM TI 1.2 (Java 6) and should be deprecated so they can be removed in a future release.

We need to replace this sentence:
"These functions and data types were introduced in the original JVM TI
version 1.0 and have been superseded by more powerful and flexible
versions which:"
with:
"These functions and data types were introduced in the original JVM TI
version 1.0. They are deprecated and will be changed to return an error
in a future release. They were superseded in JVM TI version 1.2 (Java 6) by more powerful and flexible versions which:" 

The CSR has been approved:
  https://bugs.openjdk.java.net/browse/JDK-8268242

The JVM TI Heap functions reflect the requirements of tool vendors during JSR-163. They pre-date concurrent collectors, the built-in heap dump support, and JFR. They are a maintenance burden and there is little evidence that they are used by modern tools (they involve stop-the-world operations and so are not suitable for production systems).

The JVM TI functions to deprecate are:
    IterateOverObjectsReachableFromObject
    IterateOverReachableObjects
    IterateOverHeap
    IterateOverInstancesOfClass

The "Heap 1.0" section of the JVM TI spec has existing wording in bold to say that the functions have been superseded. The proposal is to change this to say that the functions are deprecated and will be degraded in a future release.
A release note is planned. The release note will detail how to use -Xlog:jvmti=trace and -XX:TraceJVMTI= to identify any residual usages of these functions.

A future CSR will likely degrade these functions so that they return an error to indicate that they are no longer implemented/supported. We also plan to re-examine the newer Heap functions with a view to deprecate them in the future too (this requires a bit more work to understand if there is any real usage, also some adjustments to the JDWP and JDI specs).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268241](https://bugs.openjdk.java.net/browse/JDK-8268241): deprecate JVM TI Heap functions 1.0

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 2cd78dfdd94e0a409a197a07e7154003b07f0b38
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to 2cd78dfdd94e0a409a197a07e7154003b07f0b38
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4406/head:pull/4406` \
`$ git checkout pull/4406`

Update a local copy of the PR: \
`$ git checkout pull/4406` \
`$ git pull https://git.openjdk.java.net/jdk pull/4406/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4406`

View PR using the GUI difftool: \
`$ git pr show -t 4406`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4406.diff">https://git.openjdk.java.net/jdk/pull/4406.diff</a>

</details>

### CODE REVIEW

**Comment by linzang** [comment]
Hi Serguei, 
I am not a reviewer:-), but have 1 minor suggestion:  the year info of copyright in header need to update to 2021.  Thanks.

**Comment by sspitsyn** [comment]
Thank you for the comment, Lin! I'll update the copyright year before the push.

**Review by AlanBateman — APPROVED** [review]

**Comment by dholmes-ora** [comment]
So ... we're logically deprecating these functions by documenting that they are deprecated, but there is no actual deprecation mechanism for JVM TI - correct? JVM TI versioning cannot be used to remove anything, it can only add new functionality.

Thanks,
David

**Comment by AlanBateman** [comment]
> So ... we're logically deprecating these functions by documenting that they are deprecated, but there is no actual deprecation mechanism for JVM TI - correct? JVM TI versioning cannot be used to remove anything, it can only add new functionality.

I don't think it will be possible to remove the functions but they would return an error such as JVMTI_ERROR_UNSUPPORTED in the some future release. An intermediate step might be to emit a warning when the can_tag_objects capability is enabled.

**Review by irisclark — APPROVED** [review]

**Comment by sspitsyn** [comment]
Thanks, Alan and Iris for review and approval!

**Review by kevinjwalls — APPROVED** [review]

**Comment by sspitsyn** [comment]
Thanks, Kevin, for review, suggestion and approval!

**Pull request closed without merging**
