### PR TITLE
8261071: AArch64: Refactor interpreter native wrappers

### PR DESCRIPTION
**Pull request by AntonKozlov**
Please review refactoring of interpreter signature handlers on aarch64. The main objective is to prepare for the new calling convention of macOS/AArch64, although this patch brings nothing from the new convention.

Tested with signature stress tests and tier1 on Linux/AArch64.

I have stared with a single function implementing SlowSignatureHandler (https://github.com/openjdk/jdk/commit/5ef1bd15c3bb174f4aed5e358d1ce2fff2846858#diff-1ff58ce70aeea7e9842d34e8d8fd9c94dd91182999d455618b2a171efd8f742cR164). The single function was compact but obscure. I was shuffling it until I eventually came to something similar of the initial approach with few pieces abstracted away.

The most notable changes in the final version should be
* we count only parameters passed in registers
* ldrw/strw are used to pass via stack in SignatureHandlerGenerator::pass_int

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261071](https://bugs.openjdk.java.net/browse/JDK-8261071): AArch64: Refactor interpreter native wrappers

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2413/head:pull/2413`
`$ git checkout pull/2413`

### CODE REVIEW

**Review by theRealAph — COMMENTED** [review]
Thanks, that looks way better. Are all platform differences handled by Interpreter::local_offset_in_bytes() ?

**Comment by AntonKozlov** [comment]
> Are all platform differences handled by Interpreter::local_offset_in_bytes() ?

Java local structure is very similar between CPUs. The function is a simple one:
```
  // Local values relative to locals[n]
  static int  local_offset_in_bytes(int n) {
    return ((frame::interpreter_frame_expression_stack_direction() * n) * stackElementSize);
  } 
```

**Review by theRealAph — APPROVED** [review]

**Pull request closed without merging**
