### PR TITLE
8332744: [REDO] 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version

### PR DESCRIPTION
**Pull request by cushon**
This change fixes a bug preventing javac from emitting 'compiler.warn.sun.proprietary' diagnostics if `--system` is set to a non-default value. The diagnostics are currently emitted for values of `--release`, and for the default value of `--system`.

The is a redo of [JDK-8331081](https://bugs.openjdk.org/browse/JDK-8331081), which was backed out in [JDK-8332740](https://bugs.openjdk.org/browse/JDK-8332740) due to a build failure in the microbenchmarks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332744](https://bugs.openjdk.org/browse/JDK-8332744): [REDO] 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version (**Bug** - P4)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19397/head:pull/19397` \
`$ git checkout pull/19397`

Update a local copy of the PR: \
`$ git checkout pull/19397` \
`$ git pull https://git.openjdk.org/jdk.git pull/19397/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19397`

View PR using the GUI difftool: \
`$ git pr show -t 19397`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19397.diff">https://git.openjdk.org/jdk/pull/19397.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19397#issuecomment-2148078720)
</details>

### CODE REVIEW

**Comment by cushon** [comment]
bridgekeeper please keep this open for now

**Comment by cushon** [comment]
I still think it'd be slightly worthwhile to fix the built-in sunapi implementation to handle this case, but if the feeling is that it isn't worth spending time on and the possible disruption to `-Werror`, that's also OK.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Comment by cushon** [comment]
@vicente-romero-oracle could you please take another look?

I was preparing to integrate this, and the latest merge includes one new benchmark that requires another update: https://github.com/openjdk/jdk/pull/19397/commits/a56bc3a5d461f2f27ee77e169d7bc6b9e80247cb

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Comment by vicente-romero-oracle** [comment]
@cushon done, thanks

**Pull request closed without merging**
