### PR TITLE
8184444: The compiler error "variable not initialized in the default constructor" is not apt in case of static final variables

### PR DESCRIPTION
**Pull request by archiecobbs**
This bug causes this class:
```java
class StaticFinalInit {
    static final int foo;
}
```
to fail to compile as it should but with a confusing error message:
```
StaticFinalInit.java:2: error: variable foo not initialized in the default constructor
    static final int foo;
                     ^
```
In another variant, if there is a non-default constructor:
```java
class StaticFinalInit {
    static final int foo;
    StaticFinalInit() { }
}
```
the compiler gives the right error message but shows the wrong source code location:
```
StaticFinalInit.java:3: error: variable foo might not have been initialized
    StaticFinalInit() { }
                        ^
```
This behavior is a side-effect of the roundabout way we currently check for definite assignment of static final fields.

When recursing into a class definition in `Flow.AssignAnalyzer`, we first initialize DA/DU analysis for static fields, and then recurse on the static initializers to pick up static field assignments. However, we don't then check for definite assignment of static final fields. Instead, we proceed with the analysis, and then later, whenever we visit an initial constructor (i.e., one that invokes `super()` instead of `this()`), we check for definite assignment of both static final and instance final fields.

This works because every class has at least one initial constructor, so static fields will always get checked at least once. Of course, it also results in doing some redundant work (if there are multiple initial constructors) and it generates the wrong error message and/or source code position.

This patch adds a check for definite assignment of static final fields (with the appropriate error message) after we recurse on the static initializers, and it filters out static fields from the checks being done in initial constructors. It also updates a couple of existing unit tests that were expecting the wrong source code position.

The two examples above now both generate this error message:
```
StaticFinalInit.java:2: error: variable foo might not have been initialized
    static final int foo;
                     ^
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8184444](https://bugs.openjdk.org/browse/JDK-8184444): The compiler error "variable  not initialized in the default constructor" is not apt in case of static final variables

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**) ⚠️ Review applies to [d9ef373f](https://git.openjdk.org/jdk/pull/10896/files/d9ef373ff85d46ca2996b7b0a140bc99e10fda55)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/10896/head:pull/10896` \
`$ git checkout pull/10896`

Update a local copy of the PR: \
`$ git checkout pull/10896` \
`$ git pull https://git.openjdk.org/jdk.git pull/10896/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10896`

View PR using the GUI difftool: \
`$ git pr show -t 10896`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10896.diff">https://git.openjdk.org/jdk/pull/10896.diff</a>

</details>

### CODE REVIEW

**Comment by archiecobbs** [comment]
keepalive

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Pull request closed without merging**
