### PR TITLE
8300669: AArch64: Table based tails processing and wider stores for Arrays.fill() intrinsic

### PR DESCRIPTION
**Pull request by dchuyko**
This is a new AArch64 implementation of existing (1-4-byte element) stubs that are called in C2-compiled code for array fill patterns and Arrays.fill().

Main variant of existing algorithm:

```
[Short arrays (< 8 bytes): fill by element and exit];
// ...
[align base to 8 bytes];
// ...
// fill_words
head_len = (cnt & 14) / 2;
switch (head_len) {
    do {
      cnt -= 16;
        stp;
       case 7:
        stp;
       case 6:
        stp;
        // ...
      case 1:
         stp;
       case 0:
         base += 8*16;
     } while (cnt);
   }
[(over)write a tail < 8 bytes];
```

Even in good case, only 16-byte GPR (STP) stores are used, and there is a jump for every 8 stores. There is always extra work to be done for misaligned targets, which especially affects small to medium lengths.

The new implementation generates fill implementation for every length up to a certain threshold (160-byte length). These implementations form a table where you jump when the remaining target length is suitable.

For each table entry (target length), we can have no branches and use the most number of widest possible stores that best fit the detected CPU model. Currently it is SIMD STPQ for Neoverse N2 and GPR STP for the rest. The choice is made after benchmarking and is controlled by the new UseSIMDForArrayFill flag in AArch64.

Main variant of the new algorithm (see mode detailed description in comments):

```
[align data at 16 bytes];
while(cnt_bytes > 128) {
   [store 128 bytes];
   cnt_bytes -= 128;
}
[store tail of 0..127 bytes];

```

Both existing and proposed implementations specifically handle zero fill case (see comments about ZVA). New implementation contains a path for very small arrays that can be cut to further improve more generic case (added to avoid regressions).

The check added in https://bugs.openjdk.org/browse/JDK-8298720 in StubGenerator is removed as it is a stub code being generated. For the selected threshold, the increase in code size is within 8 KB.

New test TestArraysFill is added to intrinsics jtreg tests. It calls optimized versions of 2-arg and 4-arg Arrays.fill() for different data types, lengths and patterns. The target data is checked to be filled with the required value, the surrounding data is checked to be intact.

Existing test/micro/org/openjdk/bench/java/util/ArraysFill.java benchmark was used only initially. There are many cases and data lengths to cover. A modified version of the benchmark is attached [1] to the RFE, but not included in the change as it takes too long to complete all valuable variants.

Resulting performance data are listed in the spreadsheet [2] attache to the RFE. Target processors were Graviton 3, Graviton 2, TaiShan, A72 and A53. Latest data from Altra is not included but the picture there was similar to Graviton 2 in all experiments. There is a range of target lengths with various enhancement numbers. Interesting lengths are within table implementation threshold and close to them (stepped), small lengths (all) and long lengths (1 point, they look similar). Over this voluntary selection:

- No major regressions were found.
- Geomean improvement: 11-33%
- Median improvement: 10-48%

Testing: tier1, tier2 and the new test on fastdebug aarch64 and x86.

[1] https://bugs.openjdk.org/secure/attachment/102426/ArraysFill.java
[2] https://bugs.openjdk.org/secure/attachment/102427/arrays-fill.ods

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300669](https://bugs.openjdk.org/browse/JDK-8300669): AArch64: Table based tails processing and wider stores for Arrays.fill() intrinsic

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12222/head:pull/12222` \
`$ git checkout pull/12222`

Update a local copy of the PR: \
`$ git checkout pull/12222` \
`$ git pull https://git.openjdk.org/jdk.git pull/12222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12222`

View PR using the GUI difftool: \
`$ git pr show -t 12222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12222.diff">https://git.openjdk.org/jdk/pull/12222.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12222#issuecomment-1405194866)

### CODE REVIEW

**Comment by adinn** [comment]
> The worst part of it is that, with separate code for each length of copy, we have something that looks good in benchmarks, but it occupies more instruction cache that could be used for other things. I would not be surprised if, when integrated into an application with high icache pressure, it didn't make things worse.

Those are definitely important points. This is a lot more instruction cache than with the status quo dedicated to a stub that addresses one specific need.

Also, as you say, this has the potential to noticeably increase cache pressure. A counter-argument to that might be that an application doing a lot of array fills may well be filling arrays of the same size or from a limited range of sizes (even if those sizes varied from app to app). But that's not always going to be true.

Stepping back a bit from that critique I'm prompted to ask what is motivating this change. What evidence is there that we need this solution, or any, in preference to the one we already have?

> Also, it's a lot of complicated code, with only a small gain even on a specially-designed benchmark.

That's another important point that underlines the need for a compelling answer to the question of motivation, preferably an answer which also offers reason to believe the benchmark results will translate to similar gains in a real app.

**Comment by dchuyko** [comment]
Thу functionality in question applies to Arrays.fill() and to fill loops as well. First one is easier to study: get (start, fill length, array length), and get the call weight in profiles.

**Comment by dchuyko** [comment]
As an example consider parameters distribution in OpenJDK jtreg tests.
02-jtreg-lengths
Here most fills start with 0 and fill length is below 512 elements.

**Comment by dchuyko** [comment]
In micro-benchmarks we can compare proposed implementation ("patch"), existing one ("clean") and also a variant when stubs are not called ("off"). For instance here is a plot for aligned int fills on Graviton 3.
03-fill-512-3
Existing stub is slower than no-stub variant on many lengths and shows leaping results for neighbor lengths. Patched version is the same 30% to current version as that is to no-stub version for <90 elements. Patched version is same or better than no-stub version for longer lengths and it "leaps" much less.

**Comment by dchuyko** [comment]
In non-dedicated benchmarks there is some improvement in message digest operations for small lengths where cleaning operation has noticeable weight. E.g. SHA-224 for size 16 is 4.7% faster (MD5, SHA-256, SHA3-256 show 1-4%). SpecJVM serial is 0.14% faster (fill() weight there is ~0.28%).

**Comment by dchuyko** [comment]
It is not so easy to see icache pressure in benchmarks but all branching penalties show up quickly. Current patch allows tuning of the table size. It actually can be a mask to allow certain lengths. So for any known application where icache pressure is significant it is possible to try different table volumes.

**Comment by theRealAph** [comment]
> As an example consider parameters distribution in OpenJDK jtreg tests. 02-jtreg-lengths Here most fills start with 0 and fill length is below 512 elements.

Can you please explain what this means? Are these all non-zero fills?

**Pull request closed without merging**
