### PR TITLE
8264788:  Make SequentialSubTasksDone use-once

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  can I have reviews for this change that simplifies code ahead?

SequentialSubTasksDone has some machinery to reset itself automatically after all tasks were claimed.

This is not used at all and can/should be removed. 

Test: tier1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264788](https://bugs.openjdk.java.net/browse/JDK-8264788): Make SequentialSubTasksDone use-once

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer) ⚠️ Review applies to 5393097086e354134393523b411c9db02a31c461
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3372/head:pull/3372` \
`$ git checkout pull/3372`

Update a local copy of the PR: \
`$ git checkout pull/3372` \
`$ git pull https://git.openjdk.java.net/jdk pull/3372/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3372`

View PR using the GUI difftool: \
`$ git pr show -t 3372`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3372.diff">https://git.openjdk.java.net/jdk/pull/3372.diff</a>

</details>

### CODE REVIEW

**Comment by tschatzl** [comment]
Note that it is possible to remove the CAS loop in `SequentialSubTasksDone` with an atomic add. I wasn't sure to do this, but if somebody thinks it is a good idea (and probably faster anyway) similar to the following:

    bool SequentialSubTasksDone::try_claim_task(uint& t) {
      if (t < _num_tasks) {
        t = Atomic::add(&_num_claimed, 1) - 1;
      }
      return t < _num_tasks;
    }

(And slightly fixing that assert in the destructor)

**Review by albertnetymk — APPROVED** [review]
Looking at how `SequentialSubTasksDone` is used, I don't really see the benefit of having `assert(_num_claimed == _num_tasks)` in the destructor. If we drop that assertion, `Atomic::add` is more readable.

I prefer `Atomic::add` with the assertion removed, but this version is fine as well.

**Comment by tschatzl** [comment]
I changed to the `Atomic::add` but kept the assert (modified).

**Review by kstefanj — APPROVED** [review]
Looks good.

**Comment by tschatzl** [comment]
Thanks @albertnetymk @kstefanj for your reviews.

**Pull request closed without merging**
