### PR TITLE
8307532: Implement LM_LIGHTWEIGHT for Zero

### PR DESCRIPTION
**Pull request by rkennke**
This implements the remaining parts of LW locking in Zero. Much of the work has already been done by Axel, this basically only implements the missing part that handles synchronized JNI entries. I basically preserved the LM_LEGACY case, except that I shuffled the code a little to match what we do in monitorexit case in bytecodeInterpreter.cpp (but should be functionally equivalent). The LM_LIGHTWEIGHT and LM_MONITOR case (the latter of which has been broken, before) simply call into the runtime.

With this change, we can now remove the block in arguments.cpp that deals with missing LM_LIGHTWEIGHT support.

Testing:
 - [x] bootcycle-images
 - [x] java -jar jcstress-latest.jar -tb 1h

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307532](https://bugs.openjdk.org/browse/JDK-8307532): Implement LM_LIGHTWEIGHT for Zero (**Enhancement** - P4)

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21220/head:pull/21220` \
`$ git checkout pull/21220`

Update a local copy of the PR: \
`$ git checkout pull/21220` \
`$ git pull https://git.openjdk.org/jdk.git pull/21220/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21220`

View PR using the GUI difftool: \
`$ git pr show -t 21220`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21220.diff">https://git.openjdk.org/jdk/pull/21220.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21220#issuecomment-2379533549)

### CODE REVIEW

**Review by xmas92 — COMMENTED** [review]
The `LM_LIGHTWEIGHT` changes looks good to me.

This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build. 

`ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()`  as well.

**Comment by rkennke** [comment]
> The `LM_LIGHTWEIGHT` changes looks good to me.
> 
> This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build.
> 
> `ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()` as well.

Thanks, Axel!

I made the change in basictLock.inline.hpp.

I've also run 'make bootcycle-images' to give it some testing.

Roman

**Comment by TheShermanTanker** [comment]
> The `LM_LIGHTWEIGHT` changes looks good to me.
> 
> This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build.
> 
> `ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()` as well.

I might be missing something, but Zero cannot be combined with another VM variant in the configure step, so the risk of a CPU arch being defined at the same time as Zero cannot happen (The build system treats Zero a little strangely)

**Comment by xmas92** [comment]
> > The `LM_LIGHTWEIGHT` changes looks good to me.
> > This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build.
> > `ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()` as well.
> 
> I might be missing something, but Zero cannot be combined with another VM variant in the configure step, so the risk of a CPU arch being defined at the same time as Zero cannot happen (The build system treats Zero a little strangely)

Good to know. Then it should not be an issue.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Comment by rkennke** [comment]
> > The `LM_LIGHTWEIGHT` changes looks good to me.
> 
> > 
> 
> > This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build.
> 
> > 
> 
> > `ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()` as well.
> 
> 
> 
> I might be missing something, but Zero cannot be combined with another VM variant in the configure step, so the risk of a CPU arch being defined at the same time as Zero cannot happen (The build system treats Zero a little strangely)

No, this doesn't seem to be the case. I placed a STATIC_ASSERT in the #if defined ... block and it fired with ZERO. This means that yes, we *do* get both ZERO and (e.g.) X86 defined at the same time. And it makes sense, too. ZERO is a JVM variant and X86, AARCH64, etc are CPU arches. It is entirely possible and reasonable to build zero JVM on x86 or aarch64.

**Comment by TheShermanTanker** [comment]
> > > The `LM_LIGHTWEIGHT` changes looks good to me.
> > 
> > 
> > > 
> > 
> > 
> > > This also enables `UseObjectMonitorTable`. I believe `BasicLock::object_monitor_cache()` must be modified as well. Assuming that both `ZERO` and a supported platform (e.g. `X86`) can and will be defined in the same build.
> > 
> > 
> > > 
> > 
> > 
> > > `ZERO` should return `nullptr` in `BasicLock::object_monitor_cache()` as well.
> > 
> > 
> > I might be missing something, but Zero cannot be combined with another VM variant in the configure step, so the risk of a CPU arch being defined at the same time as Zero cannot happen (The build system treats Zero a little strangely)
> 
> No, this doesn't seem to be the case. I placed a STATIC_ASSERT in the #if defined ... block and it fired with ZERO. This means that yes, we _do_ get both ZERO and (e.g.) X86 defined at the same time. And it makes sense, too. ZERO is a JVM variant and X86, AARCH64, etc are CPU arches. It is entirely possible and reasonable to build zero JVM on x86 or aarch64.

That is very strange, the build system treats (Or is at least supposed to treat) Zero as a CPU arch. Might be time for me to revisit that code, either I made a mistake, or something is wrong. Thanks for the heads up

**Pull request closed without merging**
