### PR TITLE
8324571: JDK 23 L10n resource files update

### PR DESCRIPTION
**Pull request by alisenchung**
l10n update for jdk23

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8324571](https://bugs.openjdk.org/browse/JDK-8324571): JDK 23 L10n resource files update (**Bug** - P3)

### Reviewers
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17542/head:pull/17542` \
`$ git checkout pull/17542`

Update a local copy of the PR: \
`$ git checkout pull/17542` \
`$ git pull https://git.openjdk.org/jdk.git pull/17542/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17542`

View PR using the GUI difftool: \
`$ git pr show -t 17542`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17542.diff">https://git.openjdk.org/jdk/pull/17542.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17542#issuecomment-1907053296)

### CODE REVIEW

**Review by naotoj — APPROVED** [review]

**Review by justin-curtis-lu — APPROVED** [review]
LGTM, changes consistent with the original properties files

**Comment by hns** [comment]
Please note that this PR contains messages that are not part of JDK 22. Specifically the messages related to the table of contents feature are not part of JDK 22. So this should **not** be backported to 22 as the title and description suggest it would.

**Comment by hns** [comment]
I set reviewers to 2 with the intent to have somebody take a second look, then I realized that this PR already has 2 reviewers. In any case please make sure these changes are correct before integrating as they should not go into JDK 22 (see my comment above).

**Review by naotoj — CHANGES_REQUESTED** [review]
Good catch @hns This PR should not have been created against the mainline, but JDK22 stabilization repository (w/o mainline changes). Retracting the approval.

**Comment by alisenchung** [comment]
> I set reviewers to 2 with the intent to have somebody take a second look, then I realized that this PR already has 2 reviewers. In any case please make sure these changes are correct before integrating as they should not go into JDK 22 (see my comment above).

There was some confusion as to which repo should be updated for rdp2. Since we have the translations complete already, could you review the changes for doclets? These changes will not be backported to jdk22

**Comment by alisenchung** [comment]
@jonathan-gibbons could you please review the javadocs l10n changes?

**Review by jonathan-gibbons — APPROVED** [review]
As always, I am unable to comment on specific translations.

That being said, these changes look OK for JDK 23.  They should *not* be back ported to JDK 22.

**Comment by hns** [comment]
I should mention that it was @jonathan-gibbons who caught this and made me aware of it. Thanks Jon!

**Comment by alisenchung** [comment]
@hns can you take a look for these changes for jdk23 only?

**Pull request closed without merging**
