### PR TITLE
JDK-8299554: Remove EnableIf from metaprogramming/enableIf.hpp

### PR DESCRIPTION
**Pull request by jcking**
As the title says, remove `EnableIf` type alias from `metaprogramming/enableIf.hpp` leaving only `ENABLE_IF` and `ENABLE_IF_SDEFN`.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299554](https://bugs.openjdk.org/browse/JDK-8299554): Remove EnableIf from metaprogramming/enableIf.hpp

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11835/head:pull/11835` \
`$ git checkout pull/11835`

Update a local copy of the PR: \
`$ git checkout pull/11835` \
`$ git pull https://git.openjdk.org/jdk pull/11835/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11835`

View PR using the GUI difftool: \
`$ git pr show -t 11835`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11835.diff">https://git.openjdk.org/jdk/pull/11835.diff</a>

</details>

### CODE REVIEW

**Comment by jcking** [comment]
@kimbarrett Cleanup EnableIf, but leave ENABLE_IF and ENABLE_IF_SDEFN as discussed. Also switched to `std::enable_if_t`.

**Comment by kimbarrett** [comment]
> @kimbarrett Cleanup EnableIf, but leave ENABLE_IF and ENABLE_IF_SDEFN as discussed. Also switched to `std::enable_if_t`.

My suggestion here: https://github.com/openjdk/jdk/pull/11794#pullrequestreview-1231289245
was to leave this one alone.  I think (pretty nearly) all current uses of EnableIf would be better handled by refactoring
to take advantage of C++17 if-constexpr.  I think there's little point to this intermediate change if C++17 support is
coming (which I'm hopeful that it is).

**Comment by jcking** [comment]
> > @kimbarrett Cleanup EnableIf, but leave ENABLE_IF and ENABLE_IF_SDEFN as discussed. Also switched to `std::enable_if_t`.
> 
> My suggestion here: [#11794 (review)](https://github.com/openjdk/jdk/pull/11794#pullrequestreview-1231289245) was to leave this one alone. I think (pretty nearly) all current uses of EnableIf would be better handled by refactoring to take advantage of C++17 if-constexpr. I think there's little point to this intermediate change if C++17 support is coming (which I'm hopeful that it is).

Rewriting to use `if constexpr` is more involved than a simple replace. This is meant to just stop the bleeding and remove the alias.

**Comment by jcking** [comment]
Withdrawing.

**Pull request closed without merging**
