### PR TITLE
JDK-8269774: doclint reports missing javadoc comments for JavaFX properties if the docs are on the property method

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a simple change to the code for generating docs for JavaFX properties, in order to suppress an inappropriate
"missing comment" warning.

The change is to use `hasDocCommentTree` instead of `getDocCommentTree`.

A new test is added, that runs javadoc on similar classes, with and without a comment on the field for a property. In both cases, no warnings about missing comments should be generated, and when the comment is available, it is used as expected.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269774](https://bugs.openjdk.java.net/browse/JDK-8269774): doclint reports missing javadoc comments for JavaFX properties if the docs are on the property method

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - Author)
 * [Hannes Wallnöfer](https://openjdk.java.net/census#hannesw) (@hns - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4747/head:pull/4747` \
`$ git checkout pull/4747`

Update a local copy of the PR: \
`$ git checkout pull/4747` \
`$ git pull https://git.openjdk.java.net/jdk pull/4747/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4747`

View PR using the GUI difftool: \
`$ git pr show -t 4747`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4747.diff">https://git.openjdk.java.net/jdk/pull/4747.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
It looks like the fix works. We still have quite a few warnings about missing comments, but almost all of them are actual problems with missing comments in various JavaFX methods. In at least two cases, they revealed methods that should not have been public in the first place or were misnamed (a property method name that was spelled incorrectly). This is good.

I did spot one odd warning. The following warning is on a private field that is not a property type, but is simply a `boolean`:

```
...\rt\modules\javafx.swing\src\main\java\javafx\embed\swing\JFXPanel.java:179: warning: no comment
    private boolean isCapturingMouse = false;
                    ^
```

This might be a different problem entirely. I'll go through the rest and see if I spot anything else.

**Comment by kevinrushforth** [comment]
There must be something about the `JFXPanel` class that is confusing javadoc. There are 13 warnings about missing comments, all of which are on private fields that are simple types (not properties).

**Comment by kevinrushforth** [comment]
I see this on a few other classes, too. Very odd.

**Comment by kevinrushforth** [comment]
Update: It looks like the above warnings on private fields are due to problems in those JavaFX files relating to serialization. In any case it completely unrelated to this PR, which fixes the problems reported in the bug.

**Review by kevinrushforth — APPROVED** [review]
The fix looks good. You'll just need to fix the whitespace problems in the test that `jcheck` reported.

**Review by kevinrushforth — APPROVED** [review]

**Review by hns — APPROVED** [review]
Looks good!

**Pull request closed without merging**
