### PR TITLE
8253409: Double-rounding possibility in float fma

### PR DESCRIPTION
**Pull request by jddarcy**
In floating-point, usually doing an operation to double precision and then rounding to float gives the right result in float precision. One exception to this is fused multiply add (fma) where "a * b + c" is computed with a single rounding. This requires the equivalent of extra intermediate precision inside the operation. If a float fma is implemented using a double fma rounded to float, for some well-chosen arguments where the final result is near a half-way result in *float*, an incorrect answer will be computed due to double rounding. In more detail, the double result will round up and then the cast to float will round up again whereas a single rounding of the exact answer to float would only round-up once.

The new float fma implementation does the exact arithmetic using BigDecimal where possible, with guard to handle the non-finite and signed zero IEEE 754 details.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253409](https://bugs.openjdk.java.net/browse/JDK-8253409):  Double-rounding possibility in float fma

### Reviewers
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2684/head:pull/2684`
`$ git checkout pull/2684`

### CODE REVIEW

**Review by bplb — APPROVED** [review]
Looks fine. Presumably the updated test fails without the source change.

**Comment by jddarcy** [comment]
> 
> 
> Looks fine. Presumably the updated test fails without the source change.

Right; the added test case is the failing one from the bug report. It will fail if the old non-intrinsic implementation, that is the Java implementation is used.

**Pull request closed without merging**
