### PR TITLE
JDK-8284874: Add comment to ProcessHandle/OnExitTest to describe zombie problem

### PR DESCRIPTION
**Pull request by tstuefe**
ProcessHandle/OnExitTest is vulnerable to misconfigured systems that do not reap zombies in a timely fashion. [JDK-8284282](https://bugs.openjdk.java.net/browse/JDK-8284282) describes this problem in detail.

Until we figure out a way to fix that (if at all - see comments in JBS), let us have a clarifying comment in the test itself.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284874](https://bugs.openjdk.java.net/browse/JDK-8284874): Add comment to ProcessHandle/OnExitTest to describe zombie problem

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8240/head:pull/8240` \
`$ git checkout pull/8240`

Update a local copy of the PR: \
`$ git checkout pull/8240` \
`$ git pull https://git.openjdk.java.net/jdk pull/8240/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8240`

View PR using the GUI difftool: \
`$ git pr show -t 8240`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8240.diff">https://git.openjdk.java.net/jdk/pull/8240.diff</a>

</details>

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
Please update the copyright date.
Thanks for including the explanation in the test.

**Comment by tstuefe** [comment]
> Please update the copyright date. Thanks for including the explanation in the test.

Thank you @RogerRiggs! Would I need a second Reviewer?

**Comment by RogerRiggs** [comment]
Core-libs issues only require 1 reviewer; though some more complex issues deserve more than 1.
Thanks

**Review by RogerRiggs — APPROVED** [review]

**Comment by tstuefe** [comment]
Thanks Roger!

/integrate

**Pull request closed without merging**
