### PR TITLE
8332032: C2: Remove ExpandSubTypeCheckAtParseTime flag

### PR DESCRIPTION
**Pull request by xiaotaonan**
C2: Remove ExpandSubTypeCheckAtParseTime flag

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332032](https://bugs.openjdk.org/browse/JDK-8332032): C2: Remove ExpandSubTypeCheckAtParseTime flag (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19205/head:pull/19205` \
`$ git checkout pull/19205`

Update a local copy of the PR: \
`$ git checkout pull/19205` \
`$ git pull https://git.openjdk.org/jdk.git pull/19205/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19205`

View PR using the GUI difftool: \
`$ git pr show -t 19205`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19205.diff">https://git.openjdk.org/jdk/pull/19205.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19205#issuecomment-2106101027)

### CODE REVIEW

**Comment by xiaotaonan** [comment]
@lgxbslgx

**Comment by chhagedorn** [comment]
Hi @xiaotaonan, please first ask in JBS if you can take over RFEs/bugs that are already assigned like this one, especially if it has just been filed. This PR misses the entire context why this flag should be removed and what the pros/cons and trade-offs are. I planned to do some more offline discussions first before removing this flag since it is now related to an otherwise hard-to-fix bug in Valhalla.

**Comment by xiaotaonan** [comment]
> please first ask in JBS if you can take over RFEs/bugs that are already assigned like this one, especially if it has just been filed. This PR misses the entire context why this flag should be removed and what the pros/cons and trade-offs are. I planned to do some more offline discussions first before proposing the actual PR to remove this flag since it is now related to an otherwise hard-to-fix bug in Valhalla.

OK.

**Comment by lgxbslgx** [comment]
> @lgxbslgx

The reviewers (maybe me) of the corresponding area will review your patch. So I don't think you need to CC me especially.

**Comment by chhagedorn** [comment]
> > please first ask in JBS if you can take over RFEs/bugs that are already assigned like this one, especially if it has just been filed. This PR misses the entire context why this flag should be removed and what the pros/cons and trade-offs are. I planned to do some more offline discussions first before proposing the actual PR to remove this flag since it is now related to an otherwise hard-to-fix bug in Valhalla.
> 
> OK.

Thanks for your understanding and letting me taking this PR over - I will propose this change again later this week (we first also need to update some internal stress jobs that use this flag).

**Pull request closed without merging**
