### PR TITLE
8338747: hasIncubatorModules needs to be generated when module resolution required at startup

### PR DESCRIPTION
**Pull request by AlanBateman**
This PR proposes changes to the ModuleBootstrap code that is used with CDS (Ahead-of-Time Class Loading & Linking in the future). At things stand, the module graph and boot layer can be archived at dump time (-Xshare:dump) when the initial module is the class path or the initial module is in the run-time image. Future work will extend this to deployments with an application module path or where additional root modules are specified with --add-modules. To get there we need the code that determines whether to archive is in one place, and it needs to know if the module graph contains incubator modules or split packages. 

Testing: tier1-tier6. There are no new tests, the changes don't expand or change what can be archived. Calvin has done some some testing with the change as it is needed for [JDK-8328313](https://bugs.openjdk.org/browse/JDK-8328313).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338747](https://bugs.openjdk.org/browse/JDK-8338747): hasIncubatorModules needs to be generated when module resolution required at startup (**Bug** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20818/head:pull/20818` \
`$ git checkout pull/20818`

Update a local copy of the PR: \
`$ git checkout pull/20818` \
`$ git pull https://git.openjdk.org/jdk.git pull/20818/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20818`

View PR using the GUI difftool: \
`$ git pr show -t 20818`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20818.diff">https://git.openjdk.org/jdk/pull/20818.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20818#issuecomment-2341598083)

### CODE REVIEW

**Comment by iklam** [comment]
I can confirm that the problem reported in the bug has been fixed. I added the following prints:

```
        // Step 8: CDS dump phase

+       if (CDS.isDumpingStaticArchive()) {
+           boolean hasSplitPackages = containsSplitPackages(cf);
+           boolean hasIncubatorModules = containsIncubatorModule(cf);
+           System.out.println("hasSplitPackages    = " + hasSplitPackages);
+           System.out.println("hasIncubatorModules = " + hasIncubatorModules);
+       }

        if (CDS.isDumpingStaticArchive() && !haveModulePath && addModules.isEmpty()) {
            assert !isPatched;
=====
$ ls -l d
-rw-rw-r-- 1 iklam iklam 1349 Jul 26 15:31 com.greetings.jar
-rw-rw-r-- 1 iklam iklam 1136 Jul 26 15:31 org.astro.jar
$ java -p d -m com.greetings
Greetings world!
$ java -Xshare:dump -XX:SharedArchiveFile=hw.jsa --module-path=d
hasSplitPackages    = false
hasIncubatorModules = false
```

`hasIncubatorModules` was `true` in the bug report, but with the patch, both of these two values are `false`. This fix will unblock the following code when Calvin adds support for `--module-path` for the archived FMG.

```
        if (!hasSplitPackages && !hasIncubatorModules) {
            ArchivedBootLayer.archive(bootLayer);
        }
```

**Review by iklam — APPROVED** [review]
The logic seems to be correct (or at least err on the side of safety and recompute hasSplitPackages/hasIncubatorModules when we aren't 100% sure).

Small nit on the bug title: should it be changed to ".... when module resolution is required at startup"?

**Review by calvinccheung — APPROVED** [review]
Thanks for the fix. I tried the patch together with my prototype for JDK-8328313 and sanity testing looks good.

**Comment by AlanBateman** [comment]
> The logic seems to be correct (or at least err on the side of safety and recompute hasSplitPackages/hasIncubatorModules when we aren't 100% sure).

Just to say a bit more about this. When you specify an application module path to the java launcher then you don't know in advance which modules on the module path will be resolved and whether an incubator module will be resolved. So if startup generates a new Configuration then it has to be checked for incubator modules so that a warning can be printed. The issue we have isn't really a bug, it's that the prototype CDS changes piggyback on the flag used to say if we need to check for incubator modules. With the changes, the flag is renamed to mayContainIncubatorModules to avoid any confusion. As part of dumping, the generated Configuration is checked for incubating modules so that archiving of the boot layer (or "FMG" as CDS refers to it) can be skipped.

**Pull request closed without merging**
