### PR TITLE
8267452: Delegate forEachRemaining in Spliterators.iterator()

### PR DESCRIPTION
**Pull request by amaembo**
Sometimes, `Spliterator::forEachRemaining` has much more optimized implementation, compared to `Spliterator::tryAdvance`. For example, if a `Stream::spliterator` called for a stream that has intermediate operations, `tryAdvance()` may buffer intermediate elements while `forEachRemaining()` just delegates to the `wrapAndCopyInto` (see `StreamSpliterators.AbstractWrappingSpliterator` and its inheritors).

`Spliterators::iterator` methods (used in particular by `Stream::iterator`) provide adapter iterators that delegate to the supplied spliterator. Unfortunately, they don't have a specialized implementation for `Iterator::forEachRemaining`. As a result, a default implementation is used that delegates to `hasNext`/`next`, which in turn causes the delegation to `tryAdvance`. It's quite simple to implement `Iterator::forEachRemaining` here, taking advantage of possible spliterator optimizations if the iterator client decides to use `forEachRemaining`.

This patch implements Iterator::forEachRemaining in Spliterators::iterator methods. Also, I nullize the `nextElement` in `Iterator::next` to avoid accidental prolongation of the user's object lifetime when iteration is finished. Finally, a small cleanup: I added the `final` modifier where possible to private fields in `Spliterators`.

Test-wise, some scenarios are already covered by SpliteratorTraversingAndSplittingTest. However, the resulting iterator is always wrapped into `Spliterators::spliterator`, so usage scenarios are somewhat limited. In particular, calling `hasNext` (without `next`) before `forEachRemaining` was not covered there. I added more tests in `IteratorFromSpliteratorTest` to cover these scenarios. I checked that removing `valueReady = false;` or `action.accept(t);` lines from newly implemented `forEachRemaining` method causes new tests to fail (but old tests don't fail due to this).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267452](https://bugs.openjdk.java.net/browse/JDK-8267452): Delegate forEachRemaining in Spliterators.iterator()

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**) ⚠️ Review applies to 9a5e0dd2192d0aef68b86656fcc44803c4fe75e9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4124/head:pull/4124` \
`$ git checkout pull/4124`

Update a local copy of the PR: \
`$ git checkout pull/4124` \
`$ git pull https://git.openjdk.java.net/jdk pull/4124/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4124`

View PR using the GUI difftool: \
`$ git pr show -t 4124`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4124.diff">https://git.openjdk.java.net/jdk/pull/4124.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — COMMENTED** [review]
Changes look good.

Testing wise we have the combo test `SpliteratorTraversingAndSplittingTest` that includes a case that tests a Spliterator produced via Spliterator -> Iterator -> Spliterator, under various operations. GIven that case do you still think we require explicit tests?

**Comment by amaembo** [comment]
@PaulSandoz thanks for review!

As for `SpliteratorTraversingAndSplittingTest`, I commented in the issue description above:

> Test-wise, some scenarios are already covered by SpliteratorTraversingAndSplittingTest. However, the resulting iterator is always wrapped into `Spliterators::spliterator`, so usage scenarios are somewhat limited. In particular, calling `hasNext` (without `next`) before `forEachRemaining` was not covered there. I added more tests in `IteratorFromSpliteratorTest` to cover these scenarios. I checked that removing `valueReady = false;` or `action.accept(t);` lines from newly implemented `forEachRemaining` method causes new tests to fail (but old tests don't fail due to this).

In short, it doesn't pass manual mutation testing. New tests are capable to catch more possible regressions.

**Review by PaulSandoz — APPROVED** [review]
Oops i missed the bit about testing in the description. That's subtle, the `hasNext` occurs in the assert before the `forEachRemaining`. Could you add a comment that this is the primary purpose of the test since `SpliteratorTraversingAndSplittingTest` cannot do that for a spliterator wrapping an iterator?

**Comment by amaembo** [comment]
@PaulSandoz added a comment, thanks!

**Pull request closed without merging**
