### PR TITLE
8321274: Rename ZipEntry.extraAttributes to ZipEntry.externalFileAttributes

### PR DESCRIPTION
**Pull request by eirbjo**
Please consider this PR which suggests we rename `ZipEntry.extraAttributes` to `ZipEntry.externalFileAttributes`.

This field was introduced in [JDK-8218021](https://bugs.openjdk.org/browse/JDK-8218021), originally under the name `ZipEntry.posixPerms`. [JDK-8250968](https://bugs.openjdk.org/browse/JDK-8250968) later renamed the field to `ZipEntry.extraAttributes` and extended its semantics to hold the full two-byte value of the `external file attributes` field, as defined by `APPNOTE.TXT`

The name `extraAttributes` is misleading. It has nothing to do with the `extra field` (an unrelated structure defined in `APPNOTE.TXT`), although the name indicates it does.

To prevent confusion and make life easier for future maintainers, I suggest we rename this field to `ZipEntry.externalFileAttributes` and update related methods, parameters and comments accordingly.

While this change is a straightforward renaming, reviewers should consider whether it carries its weight, especially considering it might complicate future backports. 

As a note to reviewers, this PR includes the following intended updates:

- Rename `ZipEntry.extraAttributes` and any references to this field to `ZipEntry.externalFileAttributes`
- Update `JavaUtilZipFileAccess` to similarly rename methods to `setExternalFileAttributes` and `getExternalFileAttributes` 
- Rename the field `JarSigner.extraAttrsDetected` to `JarSigner.externalFileAttrsDetected`
- Rename a local variable in `JarSigner.writeEntry` to `externalFileAttributes`
- Rename `s.s.t.jarsigner.Main.extraAttrsDetected` to `externalFileAttributesDetected`
- Rename resource string key names in `s.s.t.jarsigner.Resources` from `extra.attributes.detected` to `external.file.attributes.detected`
- Rename method `SymlinkTest.verifyExtraAttrs` to `verifyExternalFileAttributes`, also updated two references to 'extra attributes' in this method
- Updated copyright in all affected files

If the resource file changes should be dropped and instead handled via `msgdop` updates, let me know and I can revert the non-default files.

I did a search across the code base to find 'extraAttrs', 'extra.attr' after these updates, and found nothing related to zip/jar. The `zip` and `jar` tests run clean:

```
make test TEST="test/jdk/java/util/jar"
make test TEST="test/jdk/java/util/zip"
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321274](https://bugs.openjdk.org/browse/JDK-8321274): Rename ZipEntry.extraAttributes to ZipEntry.externalFileAttributes (**Enhancement** - P4)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16952/head:pull/16952` \
`$ git checkout pull/16952`

Update a local copy of the PR: \
`$ git checkout pull/16952` \
`$ git pull https://git.openjdk.org/jdk.git pull/16952/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16952`

View PR using the GUI difftool: \
`$ git pr show -t 16952`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16952.diff">https://git.openjdk.org/jdk/pull/16952.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16952#issuecomment-1839044344)

### CODE REVIEW

**Comment by LanceAndersen** [comment]
Thank you for the contribution Eirik.  I will take a peek at this once we are able to push changes for JDK 23

**Comment by jaikiran** [comment]
Hello Eirik, I think this is a reasonable change. I haven't had a chance to review some of these PRs due to some other priority tasks. I have these PRs on my TODO list. So if you want to pursue this further, please go ahead and reopen this and I'll review this in the coming days.

**Review by LanceAndersen — APPROVED** [review]
I think the change is OK, any reason to not make it `externalFileAttributes`?

**Comment by eirbjo** [comment]
> I think the change is OK, any reason to not make it `externalFileAttributes`?

None other than length / verbosity.  But since this refers to the _attributes of the external file_, dropping any name element also loses some semantics, introducing a potential for confusion. Perhaps verbosity is the sensible choice here.

If you agree to the above, I can update the PR to rename to the following names instead:

- `ZipFile.externalFileAttributes`
- `JavaUtilZipFileAccess.java.[set|get]ExternalFileAttributes`
- `JarSigner.externalFileAttributesDetected`
- `jarsigner/Main.externalFileAttributesDetected`
- `external.file.attributes.detected` in `Resources.java`

WDYT?

**Comment by LanceAndersen** [comment]
> > I think the change is OK, any reason to not make it `externalFileAttributes`?
> 
> None other than length / verbosity. But since this refers to the _attributes of the external file_, dropping any name element also loses some semantics, introducing a potential for confusion. Perhaps verbosity is the sensible choice here.
> 
> If you agree to the above, I can update the PR to rename to the following names instead:
> 
> * `ZipFile.externalFileAttributes`
> * `JavaUtilZipFileAccess.java.[set|get]ExternalFileAttributes`
> * `JarSigner.externalFileAttributesDetected`
> * `jarsigner/Main.externalFileAttributesDetected`
> * `external.file.attributes.detected` in `Resources.java`
> 
> WDYT?

I think the proposed change above makes things clearer.  Perhaps also make the same change in zipfs as well while you are at it?

**Comment by eirbjo** [comment]
> I think the proposed change above makes things clearer. Perhaps also make the same change in zipfs as well while you are at it?

I have pushed the rename to "ZipEntry.externalFileAttributes". Also renamed `ZipFileSystem.Entry.posixPerms` to `ZipFileSystem.Entry.externalFileAttributes`. Hopefully this makes things clearer.

A side note: The Posix support in `ZipFileSystem` is somewhat odd in that it supports the notion of a `null` permission set. So setting the permissions attribute to `null` clears all the attributes, not just the permisson ones.  But even so, I think using the full name here is also an improvement, since it signals that the field may also carry preexisting file type, setuid, setgid, sticky bits.

**Review by LanceAndersen — APPROVED** [review]

**Comment by eirbjo** [comment]
This PR was approved by Lance in March, but it seems I forgot to integrate.

I plan to integrate this in the next few days unless I hear objections.

**Comment by jaikiran** [comment]
Hello Eirik, it will be better to merge with the latest master branch and run the tier tests before integrating.

**Comment by liach** [comment]
I believe this field only captures the 2 bytes at higher indices of External File Attribute; it's not the complete 4-byte external file attributes and this value is not captured unless "Version made by" field's larger index byte (byte 5) is 3. So this name may still be imperfect.

**Comment by eirbjo** [comment]
> I believe this field only captures the 2 bytes at higher indices of External File Attribute; it's not the complete 4-byte external file attributes and this value is not captured unless "Version made by" field's larger index byte (byte 5) is 3. So this name may still be imperfect.

The purpose of this PR was mainly to reduce the risk of confusion with the "extra field", which is an entirely unrelated concept.

While I agree that the name `externalFileAttributes` might not express the full semantics of the field perfectly, I'm honestly not sure which name would, given that `APPNOTE.TXT` is pretty opaque in describing what these two bytes express, and as you point out, the field only carries data when "Version Made By" indicates Unix.

Instead of trying to find name which covers the full semantics, I suggest that we keep `externalFileAttributes` and instead seek to improve the comments relevant to this field:

* The field comment currently says `// File type, setuid, setgid, sticky, POSIX permissions`, we could prepend something clarifying that the field only carries data for Unix entries.
* Line 699 says `// read all bits in this field, including sym link attributes`, this could be improved to clarify that only the higher two "unix-bytes" are read ("all bits in this field" is a bit unclear now)
* Line 700 masks off the Unix bytes with `0xFFFF`, this isn't strictly necessary since `CENATX_PERMS` already only reads the two bytes we want. Perhaps clearer just to drop this masking.
* `ZipUtils.CENATX_PERMS` reads the full 16 bits of the Unix external file attributes, not just the permissions. The current name is confusing.

Since I don't want to delay the integration of the this PR any further, I suggest we tackle the above clarifications in a follow-up PR. Would that be ok with you, @liach ?

**Comment by eirbjo** [comment]
> Hello Eirik, it will be better to merge with the latest master branch and run the tier tests before integrating.

Life happened, but I have now merged with the latest master and GHA runs green.

Did you want to run additional testing before integration @jaikiran ?

**Comment by jaikiran** [comment]
Hello Eirik, I'll run some tests and review this PR this coming week.

**Comment by jaikiran** [comment]
Hello Eirik, the latest changes in this PR (`292d6801`) look good to me. However, these changes cause some (expected) compilation failures in some of the internal classes within some Oracle specific JDK classes. Those tests aren't accessible for external contributors. I will be updating that code to address those failures. That would mean that the integration of this PR will have to be co-ordinated. 

Can you issue a `/integrate delegate` command on this PR so that it then allows me to do the actual integration along with the Oracle side of changes?

**Review by jaikiran — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Comment by eirbjo** [comment]
> Can you issue a `/integrate delegate` command on this PR so that it then allows me to do the actual integration along with the Oracle side of changes?

Done. And big thanks for your help getting this long-lasting change across the finish line!

**Pull request closed without merging**
