### PR TITLE
8323950: Null CLD while loading shared lambda proxy class with javaagent active

### PR DESCRIPTION
**Pull request by calvinccheung**
A simple fix for an assert failure when an archived interface of an archived lambda proxy class is being transformed using
a java agent during runtime. Please refer to the bug report for details.

Testing: passed tiers 1 - 4 (including the new test).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323950](https://bugs.openjdk.org/browse/JDK-8323950): Null CLD while loading shared lambda proxy class with javaagent active (**Bug** - P2)

### Reviewers
 * [Matias Saavedra Silva](https://openjdk.org/census#matsaave) (@matias9927 - Committer)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17602/head:pull/17602` \
`$ git checkout pull/17602`

Update a local copy of the PR: \
`$ git checkout pull/17602` \
`$ git pull https://git.openjdk.org/jdk.git pull/17602/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17602`

View PR using the GUI difftool: \
`$ git pr show -t 17602`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17602.diff">https://git.openjdk.org/jdk/pull/17602.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17602#issuecomment-1912898411)

### CODE REVIEW

**Review by matias9927 — APPROVED** [review]
LGTM!

**Comment by fisk** [comment]
These nulled out CLD fields in class loaders are troubling to me. The GCs are not built to cope with them. The code for marking through the heap assumes that surely a ClassLoader has a corresponding CLD, and crashes if it does not.

While we can try to chase after every closure where this is a problem and add a null check, I have to wonder if it is the right solution.

I wonder, if the CLD could be archived as well, or something like that.

**Review by iklam — APPROVED** [review]

**Pull request closed without merging**
