### PR TITLE
8224775: test/jdk/com/sun/jdi/JdwpListenTest.java failed to attach

### PR DESCRIPTION
**Pull request by alexmenkov**
The fix also partially fixes JdwpAttachTest failures (JDK-8253940).
The failures are caused by network configuration changes during test execution ("global" IPv6 addresses disappears from interface).
To minimize chances of intermittent failures like this java.net tests use only link-local addresses whenever possible.
The fix does the same for JDI tests (Utils.getAddressesWithSymbolicAndNumericScopes  is used by JdwpListenTest and JdwpAttachTest)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8224775](https://bugs.openjdk.java.net/browse/JDK-8224775): test/jdk/com/sun/jdi/JdwpListenTest.java failed to attach

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to 96176a61db680379552f3e6a06f3a8a5b428f0ee
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2633/head:pull/2633`
`$ git checkout pull/2633`

### CODE REVIEW

**Comment by alexmenkov** [comment]
Added serviceability and net as this is JDI tests, but the issue is networking-related

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thanks,
Serguei

**Review by dfuch — COMMENTED** [review]
I don't see any specific issue with the proposed change but I don't know the JDWP tests enough to provide more feedback than that. Do you have special test cases for the IPv6 loopback? AFAIU this code here will filter it out?

**Comment by alexmenkov** [comment]
> 
> 
> I don't see any specific issue with the proposed change but I don't know the JDWP tests enough to provide more feedback than that. Do you have special test cases for the IPv6 loopback? AFAIU this code here will filter it out?

Good catch. IPv6 loopback addresses shouldn't be filtered out.
I'll update PR after re-testing

**Review by dfuch — APPROVED** [review]
The last changes look good to me.

**Pull request closed without merging**
