### PR TITLE
8306282: Build failure linux-arm32-open-cmp-baseline after JDK-8257967

### PR DESCRIPTION
**Pull request by mgronlun**
Greetings,

With [JDK-8257967](https://bugs.openjdk.org/browse/JDK-8257967), much refactoring was done to the JVMTI code concerning agents. However, some platforms do not have JVMTI support, and tier5 of testing builds an embedded build,  linux-arm32-open-cmp-baseline, which failed because the refactoring did not properly handle conditional compilations for JVMTI.

JDK-8257967 did run tier5, but it used an existing build, so it did not cause recompilations of the embedded target :-(

This changeset adds the conditional constructs to let linux-arm32-open-cmp-baseline build successfully.

It does not look good, but there you go...

Testing:

Building: linux-arm32-open-cmp-baseline
Building: regular platforms

Thanks
Markus

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306282](https://bugs.openjdk.org/browse/JDK-8306282): Build failure linux-arm32-open-cmp-baseline after JDK-8257967

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**) ⚠️ Review applies to [70bc2625](https://git.openjdk.org/jdk/pull/13512/files/70bc262588a2cfbdbf7e1738268f89265d265501)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13512/head:pull/13512` \
`$ git checkout pull/13512`

Update a local copy of the PR: \
`$ git checkout pull/13512` \
`$ git pull https://git.openjdk.org/jdk.git pull/13512/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13512`

View PR using the GUI difftool: \
`$ git pr show -t 13512`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13512.diff">https://git.openjdk.org/jdk/pull/13512.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13512#issuecomment-1513260707)

### CODE REVIEW

**Review by egahlin — APPROVED** [review]

**Comment by dholmes-ora** [comment]
@mgronlun I agree this does not look good. I'm not sure this was the right way to conditionalize the new code, rather than ensuring the callsites were conditionalized on INCLUDE_JVMTI.

**Comment by mgronlun** [comment]
> @mgronlun I agree this does not look good. I'm not sure this was the right way to conditionalize the new code, rather than ensuring the callsites were conditionalized on INCLUDE_JVMTI.

It follows the same pattern as for other jvmti*.cpp files also excluded via make/hotspot/lib/jvmFeatures.gmk. For example, jvmtiExport.cpp. Might be better to improve with conditionalized callsites, agree.

**Comment by dholmes-ora** [comment]
> It follows the same pattern as for other jvmti*.cpp files also excluded via make/hotspot/lib/jvmFeatures.gmk. For example, jvmtiExport.cpp.

Okay , yes I see that now - I was thrown by the fact that the original versions of these functions in arguments.hpp/cpp did not need this but they were in fact not conditional despite being JVMTI specific. Seems to me there should be a bunch of code in arguments.cpp that is conditionalized on INCLUDE_JVMTI.

**Pull request closed without merging**
