### PR TITLE
8285437: riscv: Fix MachNode size mismatch for MacroAssembler::verify_oops*

### PR DESCRIPTION
**Pull request by zhengxiaolinX**
Trivial and same as [JDK-8283737](https://bugs.openjdk.java.net/browse/JDK-8283737): in fastdebug build, MacroAssembler::verify_oop is used in match rules encodeHeapOop and decodeHeapOop, which also requires a fixed length.

Logs are inside the JBS issue, and this issue could be reproduced by using `-XX:+VerifyOops`.

Tested using `-XX:+VerifyOops` and a hotspot tier1 on qemu.

Thanks,
Xiaolin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285437](https://bugs.openjdk.java.net/browse/JDK-8285437): riscv: Fix MachNode size mismatch for MacroAssembler::verify_oops*

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to f52442b67de1457dee6c25d82c0d984788d85b08
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8356/head:pull/8356` \
`$ git checkout pull/8356`

Update a local copy of the PR: \
`$ git checkout pull/8356` \
`$ git pull https://git.openjdk.java.net/jdk pull/8356/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8356`

View PR using the GUI difftool: \
`$ git pr show -t 8356`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8356.diff">https://git.openjdk.java.net/jdk/pull/8356.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks fine.

**Review by RealFYang — APPROVED** [review]
Looks good.

**Comment by zhengxiaolinX** [comment]
Thank you for the quick reviews! Then move on.

/integrate

**Comment by RealFYang** [comment]
PS: Could you please add some code comment like fix for [JDK-8283737](https://bugs.openjdk.java.net/browse/JDK-8283737) ?
I can sponsor after that.

**Comment by zhengxiaolinX** [comment]
> PS: Could you please add some code comment like fix for [JDK-8283737](https://bugs.openjdk.java.net/browse/JDK-8283737) ? I can sponsor after that.

Thank you, Felix. This is very reasonable. Added and hope they look good.

**Review by RealFYang — APPROVED** [review]
Code comment looks good. Thanks.

**Pull request closed without merging**
