### PR TITLE
8338407: Support grouping several of existing regs into a new one

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this patch to add `group` support to operand?

### Some background about this pr

In some platforms, there is some concept like a group of registers, for example on riscv there is vector group, which is a group of other single vectors. For example, m2 could be v2+v3, or v4+v5, m4 could be v4+v5+v6+v7, or v8+v9+v10+v11.
And, it's helpful to represent these vector group explicitly, otherwise it's tedious and error-prone. For example, in existing code, there's some like below:
```
instruct vstring_compareUL(iRegP_R11 str1, iRegI_R12 cnt1, iRegP_R13 str2, iRegI_R14 cnt2,
                           iRegI_R10 result, vReg_V4 v4, vReg_V5 v5, vReg_V6 v6, vReg_V7 v7,
                           vReg_V8 v8, vReg_V9 v9, vReg_V10 v10, vReg_V11 v11,
                           iRegP_R28 tmp1, iRegL_R29 tmp2)
// ...
  effect(KILL tmp1, KILL tmp2, USE_KILL str1, USE_KILL str2, USE_KILL cnt1, USE_KILL cnt2,
         TEMP v4, TEMP v5, TEMP v6, TEMP v7, TEMP v8, TEMP v9, TEMP v10, TEMP v11);
// ...
    __ string_compare_v($str1$$Register, $str2$$Register,
                        $cnt1$$Register, $cnt2$$Register, $result$$Register,
                        $tmp1$$Register, $tmp2$$Register,
                        StrIntrinsicNode::UL);
```
The potential problems of the above code are that we need to
1. write v4~v11 explicitly in its `instruct` and its `effect`, it's tedious;
2. vector group are represented implicitly, which is not clear and error-prone;
3. in its encoding `string_compare_v`, we need to specify m4, and v4/v8 explicitly.
4. if some day we need to adjust from m4 to m2 or m8, it's really tedious and error-prone to make that change in both ad file and macro assembler files.

### This PR

The proposed solution is to represent a group of vector registers with a real vector group, e.g. `vReg_V4 v4, vReg_V5 v5, vReg_V6 v6, vReg_V7 v7` with `vReg_V4M4 v4m4`, `TEMP v4, TEMP v5, TEMP v6, TEMP v7` with `TEMP v4m4` and in `string_compare_v` implementation, we could query the length of of vector group (i.e. m4 in this case) and set its vtype automatically.
This solution solve the above listed issues, especially the last issue, that means in the future if we need to adjust m4 to m2 or m8, we only need to change the code in ad file and the change is simpler, and no change in string_compare_v is needed.

### What it looks like

For more usage details, please please check [here](https://github.com/openjdk/jdk/compare/master...Hamlin-Li:jdk:explicit-v-reg-group-v3), the riscv part.

Basically it looks like below:
```
operand reg_x()
%{
  group(reg_y, reg_z)
%}
```
And this reg_x can be used in an instruct as its input operand, a TEMP in effect list, in ins_encode as parameters. Underlying, a group operand will be ungrouped automatically as separate operands.

### Alternative

I tried several solutions.
1. One of them is to just add some new reg class and operand, it kindly worked, but can only prevent other regs in an instruct using the one of the vector regs in a vector group.
2. Another is to make modification in chaitin of C2 to support vector group, seems to me it finally turned out not practical, too much basic code change in chaitin and the impact is too big to be acceptable.

Current solution is to change the adlc parser, basically it works like a macro expansion, replacing vector groups with vectors, so in this way chaitin implementation does not need any changes, also means it's simpler to implement and more acceptable for the community (I hope so).

### Test

Besides of riscv, I've also triggered tier1/2/3 tests on x86 and aarch64, running in progress.

Thanks!

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warnings
&nbsp;⚠️ Patch contains a binary file (src/java.base/share/classes/jdk/internal/icu/impl/data/icudt74b/nfc.nrm)
&nbsp;⚠️ Patch contains a binary file (src/java.base/share/classes/jdk/internal/icu/impl/data/icudt74b/nfkc.nrm)
&nbsp;⚠️ Patch contains a binary file (src/java.base/share/classes/jdk/internal/icu/impl/data/icudt74b/ubidi.icu)
&nbsp;⚠️ Patch contains a binary file (src/java.base/share/classes/jdk/internal/icu/impl/data/icudt74b/uprops.icu)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/javax/swing/text/doc-files/Document-insert.gif)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-bw16.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-bw24.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-bw32.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-bw48.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-interim16.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-interim24.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-interim32.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-interim48.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-yellow16.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-yellow24.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-yellow32.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/share/classes/sun/awt/resources/security-icon-yellow48.png)
&nbsp;⚠️ Patch contains a binary file (src/java.desktop/windows/native/libawt/windows/security_warning.ico)
&nbsp;⚠️ Patch contains a binary file (src/utils/IdealGraphVisualizer/View/src/main/resources/com/sun/hotspot/igv/view/images/hideDuplicates.png)
&nbsp;⚠️ Patch contains a binary file (test/jdk/java/security/ProtectionDomain/AllPerm.jar)
&nbsp;⚠️ Patch contains a binary file (test/jdk/sun/security/provider/PolicyFile/TokenStore.keystore)
&nbsp;⚠️ Patch contains a binary file (test/jdk/sun/security/provider/PolicyFile/TrustedCert.keystore)
&nbsp;⚠️ Patch contains a binary file (test/jdk/sun/security/provider/PolicyFile/TrustedCert.keystore1)
&nbsp;⚠️ Patch contains a binary file (test/jdk/sun/security/provider/PolicyParser/ExtDirsA/a.jar)
&nbsp;⚠️ Patch contains a binary file (test/jdk/sun/security/provider/PolicyParser/ExtDirsB/b.jar)

### Issue
 * [JDK-8338407](https://bugs.openjdk.org/browse/JDK-8338407): Support grouping several of existing regs into a new one (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20775/head:pull/20775` \
`$ git checkout pull/20775`

Update a local copy of the PR: \
`$ git checkout pull/20775` \
`$ git pull https://git.openjdk.org/jdk.git pull/20775/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20775`

View PR using the GUI difftool: \
`$ git pr show -t 20775`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20775.diff">https://git.openjdk.org/jdk/pull/20775.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20775#issuecomment-2318063129)
</details>

### CODE REVIEW

**Comment by dean-long** [comment]
Are you trying to support arbitrary groups of vectors, or only aligned and sequential groups, like on riscv?

> 1. One of them is to just add some new reg class and operand, it kindly worked, but can only prevent other regs in an instruct using the one of the vector regs in a vector group.

I don't see why this wouldn't work.  As long as the register mask is correct, it should prevent/exclude all the vector regs in a vector group.
I believe this is how arm32 implements vecD on the dflt_low_reg registers.  64-bit "D" vectors are composed of two adjacent 32-bit "S" registers.

**Comment by Hamlin-Li** [comment]
Thanks for taking a look and suggestions!

> Are you trying to support arbitrary groups of vectors, or only aligned and sequential groups, like on riscv?

I'm trying supporting the latter.
Some more backgroud: On riscv, its vector only support scale one (that means it's vectorA in hotspot, length of one single vector register is dynamic, it could be 128/256/512... bits). The start vector reg in a vector group must be aligned to the length of vector group, e.g. if a vector group length is 8, then it can only be one of (v0-v7), (v8-v15), (v16-v23), (v24-v31).

> 
> > 1. One of them is to just add some new reg class and operand, it kindly worked, but can only prevent other regs in an instruct using the one of the vector regs in a vector group.
> 
> I don't see why this wouldn't work. As long as the register mask is correct, it should prevent/exclude all the vector regs in a vector group. I believe this is how arm32 implements vecD on the dflt_low_reg registers. 64-bit "D" vectors are composed of two adjacent 32-bit "S" registers.

(I could be wrong about VecD on arm below.)

[Here](https://github.com/openjdk/jdk/compare/master...Hamlin-Li:jdk:explicit-v-reg-group-v1) is the alternative implementation of "`just add some new reg class and operand`" mentioned above, please check changes in src/hotspot/cpu/riscv/riscv.ad and other related changes.
I think the reasons why this change (or the way you suggested above) does not work as expected are:
* vecD and vecA are different way to control vector register allocation in hotspot, vecD is fixed size, vecA is dynamic, so that vecD works does not directly mean vecA could work as well in the same way. (riscv only support vecA.) 
* with new reg_class and operand introduced (take v2m2_reg, vReg_V2_m2 as example), current code base only ensure vReg_V2_m2 will take one vector register from between v2 and v3, but will not ensure both v2 and v3 are allocated at the same time for it. So if an instruct in ad file has (..., vReg_V2_m2 v2m2, vReg vx, ...) as its inputs (and suppose both are `TEMP`), then there is a chance vx will finally be allocated at v2 or v3, which is unexpected. But on the other hand, if an instruct in ad file has (..., vReg vx, vReg vy, ...) as its inputs  (and suppose both are `TEMP`), then there is no chance vx will be same as vy.

Hope the above could answer your question, but it could also be that I'm doing some wrong things in [that implementation](https://github.com/openjdk/jdk/compare/master...Hamlin-Li:jdk:explicit-v-reg-group-v1).

**Comment by dean-long** [comment]
OK, I think I see the problem that approach.  I believe the reason vecD on arm32 works is because there is a VecD ideal type that has the correct size.  Using `match(VecA)` will give the wrong size for groups like vReg_V2_m2.  We would need maybe a new syntax, like `match(VecA[2])` or `match(VecA[4])`.

**Comment by Hamlin-Li** [comment]
> OK, I think I see the problem that approach. I believe the reason vecD on arm32 works is because there is a VecD ideal type that has the correct size. Using `match(VecA)` will give the wrong size for groups like vReg_V2_m2.

Yes.

> We would need maybe a new syntax, like `match(VecA[2])` or `match(VecA[4])`.

We could have something like `match(VecA[2])`.

In this pr, I'm implementing a similar one, it will looks like below
```
operand vReg_V2M2()
%{
  group(vReg_V2, vReg_V3)
%}
```
and
```
operand vReg_V8M4()
%{
  group(vReg_V8, vReg_V9, vReg_V10, vReg_V11)
%}
```
For a more detailed demo of its usage, please have a look at this [merged pr](https://github.com/openjdk/jdk/compare/master...Hamlin-Li:jdk:explicit-v-reg-group-v3) (merge of this pr and riscv demo usage, I say `demo` because if this pr is accepted, there're more code in riscv to be changed(i.e. simplied))

The good part of this `group operand` implementation is that it does not change anything inside chaitin reg allocation, it does not change anything for any existing `operand`. A `group operand` is just a "grouping" of other operands, a `group operand` itself does not mean anything to the underlying (or to say the underlying has no knowledge of this `group operand`, especially the chaitin), an `group operand` is just "ungrouped" when parsing the `instruct`.

**Comment by luhenry** [comment]
@RealFYang I would love to have your input on this. I expect it would really help in expressing some of the vector register groups constraints we have in the runtime in places, and allow us to clean it up and make the code's assumptions clearer.

**Pull request closed without merging**
