### PR TITLE
8328166: Epsilon: 'EpsilonHeap::allocate_work' misuses the parameter 'size' as size in bytes

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

The method `EpsilonHeap::allocate_work` misuses the parameter `size` as size in bytes. Actually, the parameter `size` is size in words. This patch fixes it.
 
The test command `make test TEST=test/hotspot/jtreg/gc/epsilon` passed locally.

Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328166](https://bugs.openjdk.org/browse/JDK-8328166): Epsilon: 'EpsilonHeap::allocate_work' misuses the parameter 'size' as size in bytes (**Bug** - P2)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18303/head:pull/18303` \
`$ git checkout pull/18303`

Update a local copy of the PR: \
`$ git checkout pull/18303` \
`$ git pull https://git.openjdk.org/jdk.git pull/18303/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18303`

View PR using the GUI difftool: \
`$ git pr show -t 18303`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18303.diff">https://git.openjdk.org/jdk/pull/18303.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18303#issuecomment-1997502851)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Right, good catch! This looks like a day 1 Epsilon issue, and we never noticed, because it really matters only for large objects near heap exhaustion.

**Comment by lgxbslgx** [comment]
Thanks @shipilev for your review. Waiting for another review.

**Comment by lgxbslgx** [comment]
The test `test/jdk/java/util/HashMap/WhiteBoxResizeTest.java` failed in Pre-submit tests. But it passed at https://github.com/openjdk/jdk/pull/18304.

**Review by tschatzl — APPROVED** [review]

**Comment by lgxbslgx** [comment]
@shipilev @tschatzl Thanks for your reviews.

/integrate

**Pull request closed without merging**
