### PR TITLE
8258407: Split up CompileJavaModules.gmk into make/modules/$M/Java.gmk

### PR DESCRIPTION
**Pull request by magicus**
Right now `CompileJavaModules.gmk` contains two different part: one part with the functionality needed to compile a java module, and one part were all special requirements for all modules are listed.

The second part should be removed from `CompileJavaModules.gmk`, and instead listed directly for each individual module in `make/modules/$M/Java.gmk`.

I used a special-written shell script to automatically extract the module-specific part from CompileJavaModules.gmk into the respective Java.gmk files, to avoid risking any hard-to-detect copy/paste errors. After this I did a `sed -i` to remove the module-specific prefix. All this makes me confident that I have correctly moved the variables (I realize this is hard to verify from the patch).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258407](https://bugs.openjdk.java.net/browse/JDK-8258407): Split up CompileJavaModules.gmk into make/modules/$M/Java.gmk

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to a869f4b0e78b860efd17882ddd8e75f5b241fca5

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1779/head:pull/1779`
`$ git checkout pull/1779`

### CODE REVIEW

**Comment by erikj79** [comment]
Looks good to me. I assume you have run compare builds on all platforms.

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
@erikj79 Actually, I had not done that. But it was a great idea. Now I have, and it looks good. :-)

**Pull request closed without merging**
