### PR TITLE
8269373: some tests in jdk/tools/launcher/ fails on localized Windows platform

### PR DESCRIPTION
**Pull request by masyano**
Hi all,

Could you please review the 8269373 bug fixes?

These tests call java.lang.ProcessBuilder in direct, so not used jtreg command option. To run non-localized tests, -Duser.language=en and -Duser.country=US options should be added in ProcessBuilder.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269373](https://bugs.openjdk.java.net/browse/JDK-8269373): some tests in jdk/tools/launcher/ fails on localized Windows platform

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4594/head:pull/4594` \
`$ git checkout pull/4594`

Update a local copy of the PR: \
`$ git checkout pull/4594` \
`$ git pull https://git.openjdk.java.net/jdk pull/4594/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4594`

View PR using the GUI difftool: \
`$ git pr show -t 4594`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4594.diff">https://git.openjdk.java.net/jdk/pull/4594.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — COMMENTED** [review]
From a peek at the bug report, I could not find out the exact cause why they are failing. Have you figured it out?

As to the fix itself, I would rather avoid hardcoding `en-US` in the argument. Would that be replaced with the launching process' locale?

**Comment by masyano** [comment]
Sorry for late reply.

These tests compare the output of running the jar, and the correct answers to the output results are written in English. When these are run on localized Windows platform, the output will be in the local language and the comparison result will be false. So, these need to add -Duser.language=en and -Duser.country=US to the execution option of the jar.

And I fixed avoided hardcoding by using "test.vm.opts". If we want to run these tests on localized Windows platform, we need to add -Duser.language=en and -Duser.country=US as jtreg command options.

**Comment by naotoj** [comment]
Then I would think the better fix would be to run the test if the default locale is `Locale.US`, otherwise the test should exit gracefully.

**Comment by masyano** [comment]
It is true that some other tests say Passed if the locale is not US, but I rather think that is not a good way. I think we should run tests as much as possible to ensure quality even in non-US environments.

**Comment by naotoj** [comment]
IMHO, this kind of test that sets the locale forcefully sometimes gives us false positives. I'd rather eliminate that possibility than run tests in different locales

**Comment by masyano** [comment]
I fixed it to exit silently in case the locale is not US. Thank you.

**Review by naotoj — APPROVED** [review]
Thanks. Looks good to me.

**Pull request closed without merging**
