### PR TITLE
8316181: Move the fast locking implementation out of the .ad files

### PR DESCRIPTION
**Pull request by stefank**
Some platforms put the fast locking implementation in the `C2_MacroAssembler` class, while others have it in the .ad files. I'd like to propose that we unify this a bit and move the code out of the .ad files.

The benefit is consistency between the platforms but also that it is easier to work with the C++ code when it is in plain C++ files and not in the .ad files.

The implementation is a pure copy of the code except that the section:
```
    C2_MacroAssembler _masm(&cbuf);
    Register oop = as_Register($object$$reg);
    Register box = as_Register($box$$reg);
    Register disp_hdr = as_Register($tmp$$reg);
    Register tmp = as_Register($tmp2$$reg);
```

has been replaced with:
```
  Register oop = objectReg;
  Register box = boxReg;
  Register disp_hdr = tmpReg;
  Register tmp = tmp2Reg;
```

and the references to `__ ` have been removed.

This change affects AArch64 and RISC-V

Tested with tier1-3 on AArch64

This PR depends on #15709

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316181](https://bugs.openjdk.org/browse/JDK-8316181): Move the fast locking implementation out of the .ad files (**Enhancement** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [0efabfe1](https://git.openjdk.org/jdk/pull/15712/files/0efabfe16343be4a076c83bd1ad75b5e729e5b1e)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15712/head:pull/15712` \
`$ git checkout pull/15712`

Update a local copy of the PR: \
`$ git checkout pull/15712` \
`$ git pull https://git.openjdk.org/jdk.git pull/15712/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15712`

View PR using the GUI difftool: \
`$ git pr show -t 15712`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15712.diff">https://git.openjdk.org/jdk/pull/15712.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15712#issuecomment-1717470856)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by rkennke — APPROVED** [review]
Looks good, thank you!

**Review by RealFYang — APPROVED** [review]
LGTM. I have tested both https://github.com/openjdk/jdk/pull/15709 and this one on linux-riscv64 platform. Results looks good.

**Comment by stefank** [comment]
Thanks @rkennke and @RealFYang for the reviews!
/integrate

**Pull request closed without merging**
