### PR TITLE
8253014: OopStorage bulk release logs entries multiple times

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this trivial change that removes some incorrect / duplicate
logging from OopStorage's bulk release operation.  The correct logging is
done about 10 lines later.

Testing: mach5 tier1.

/label hotspot-gc
/summary Remove excess logging.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253014](https://bugs.openjdk.java.net/browse/JDK-8253014): OopStorage bulk release logs entries multiple times

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to b75300000b1c26a4032a5a0f2c8f285f7909f948

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/319/head:pull/319`
`$ git checkout pull/319`

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks trivial, after reading the code for a minute. BTW, maybe the message should be "releasing", not "released", as the actual release had not happened yet at the time of logging.

**Comment by shipilev** [comment]
Note the commit message that bot suggested is wrong, includes PR metadata.

**Review by tschatzl — APPROVED** [review]
Lgtm and confirming triviality

**Comment by kimbarrett** [comment]
I changed the log messages to say "releasing" rather than "released" as suggested.  Also fixed the summary, which hit a Skara bug that I thought had been fixed, but apparently hadn't quite been rolled out at the time.

**Review by shipilev — APPROVED** [review]
Still good.

**Pull request closed without merging**
