### PR TITLE
8314653: Metaspace: remove allocation guard feature

### PR DESCRIPTION
**Pull request by tstuefe**
In Metaspace in debug builds, one can guard allocations. This has been a useful feature in during implementation of JEP 387 to find bugs, but has not found much use thereafter, and remains an obscure and underused feature.

But these guards cause quite a bit of complexity, mainly since they make testing difficult: with guards on, predicting arena growth gets quite complex.

I propose to remove this feature to reduce Metaspace complexity.

Tests: local (mac m1, Linux x64) Metaspace tests. GHAs.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314653](https://bugs.openjdk.org/browse/JDK-8314653): Metaspace: remove allocation guard feature (**Enhancement** - P4)

### Reviewers
 * [Afshin Zafari](https://openjdk.org/census#azafari) (@afshin-zafari - Committer)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19611/head:pull/19611` \
`$ git checkout pull/19611`

Update a local copy of the PR: \
`$ git checkout pull/19611` \
`$ git pull https://git.openjdk.org/jdk.git pull/19611/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19611`

View PR using the GUI difftool: \
`$ git pr show -t 19611`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19611.diff">https://git.openjdk.org/jdk/pull/19611.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19611#issuecomment-2156339570)

### CODE REVIEW

**Comment by tstuefe** [comment]
Friendly ping

**Review by afshin-zafari — APPROVED** [review]
Thank you @tstuefe. 
Please update the Copyright years before integrating.

**Review by dholmes-ora — APPROVED** [review]
I can't verify this is complete but the code removal seems fine, and I will defer to your assessment that this code is not useful.

Thanks

**Comment by tstuefe** [comment]
Many thanks, @afshin-zafari and @dholmes-ora . I updated the copyrights, merged, and will wait for GHAs to be green before finally pushing.

**Review by dholmes-ora — APPROVED** [review]
Re-approving as required under the new rules.

**Comment by tstuefe** [comment]
> Re-approving as required under the new rules.

Thank you!

**Review by afshin-zafari — APPROVED** [review]
Thanks again.

**Pull request closed without merging**
