### PR TITLE
8337318: Deoptimization::relock_objects fails assert(monitor->owner() == Thread::current()) failed: must be

### PR DESCRIPTION
**Pull request by coleenp**
The assert is wrong.  During deoptimization, the locking_thread is not the current thread, and that's the thread we should assert is the owner.
Reproduced in tier8 with com/sun/jdi/EATests.java, with LockStack CAPACITY=1 and not reproduced with the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337318](https://bugs.openjdk.org/browse/JDK-8337318): Deoptimization::relock_objects fails assert(monitor-&gt;owner() == Thread::current()) failed: must be (**Bug** - P3)

### Reviewers
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**) 🔄 Re-review required (review applies to [8a73754e](https://git.openjdk.org/jdk/pull/20553/files/8a73754e19d98f2fd598213807ef986be2cde6d3))
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Contributors
 * Richard Reingruber `<rrich@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20553/head:pull/20553` \
`$ git checkout pull/20553`

Update a local copy of the PR: \
`$ git checkout pull/20553` \
`$ git pull https://git.openjdk.org/jdk.git pull/20553/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20553`

View PR using the GUI difftool: \
`$ git pr show -t 20553`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20553.diff">https://git.openjdk.org/jdk/pull/20553.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20553#issuecomment-2284395658)

### CODE REVIEW

**Review by pchilano — APPROVED** [review]
Looks good to me.

**Review by reinrich — APPROVED** [review]
Looks good to me. The reproducer succeeds with the fix.

**Review by pchilano — APPROVED** [review]

**Comment by coleenp** [comment]
Thanks again for the review Patricio and review and test Richard.

**Comment by reinrich** [comment]
Thanks for adding the reproducer Coleen. I forgot to update the copyright year. Could you please take care of that?

**Comment by coleenp** [comment]
Ok, I updated the SAP copyright.  It seems to be that we add the date without the trailing comma (unlike the Oracle one).

**Comment by reinrich** [comment]
> Ok, I updated the SAP copyright. It seems to be that we add the date without the trailing comma (unlike the Oracle one).

Yes, that's correct. Thanks!

**Review by reinrich — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Looks good. Somewhat surprising we didn't hit this sooner, but now we at least have test coverage.

Thanks.

**Review by shipilev — APPROVED** [review]

**Comment by coleenp** [comment]
Thanks for reviewing Aleksey and David.
/integrate

**Pull request closed without merging**
