### PR TITLE
8263591: Two C2 compiler phases with the name "after matching"

### PR DESCRIPTION
**Pull request by TobiHartmann**
[JDK-8223347](https://bugs.openjdk.java.net/browse/JDK-8223347) added a `PHASE_AFTER_MATCHING` which is equivalent to  `PHASE_MATCHING` but only printed at level 3 and before node verification: 
https://github.com/openjdk/jdk/blob/20297a1bebfe03c45344a713ec561c97888c4750/src/hotspot/share/opto/compile.cpp#L2757-L2769

I don't think there is any benefit in having both and therefore removed it together with some other dead code (`idx` is always `0`).

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263591](https://bugs.openjdk.java.net/browse/JDK-8263591): Two C2 compiler phases with the name "after matching"

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 1b887fb557858ccc2ac1012b954f9749ca4bf418
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/3026/head:pull/3026`
`$ git checkout pull/3026`

### CODE REVIEW

**Review by neliasso — COMMENTED** [review]
idx is always 0 from the current source, but I use it a lot when developing. I usually add a print_method for every transformation of something, and adding the idx so it is quick to pinpoint in IGV.

**Comment by TobiHartmann** [comment]
Thanks for the review, Nils. Makes sense, I've updated the PR accordingly.

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks again, Nils!

**Review by chhagedorn — APPROVED** [review]
Looks good.

**Comment by TobiHartmann** [comment]
I forgot to remove `PHASE_AFTER_MATCHING` from the enum as well. Updated the PR.

Thanks for the review, Christian!

**Review by chhagedorn — APPROVED** [review]

**Pull request closed without merging**
