### PR TITLE
8297201: Obsolete AliasLevel flag

### PR DESCRIPTION
**Pull request by TobiHartmann**
The AliasLevel flag was deprecated in JDK 19 by [JDK-8075816](https://bugs.openjdk.org/browse/JDK-8075816) and should now be obsoleted. Patch is slightly adjusted https://github.com/openjdk/jdk/pull/8140/commits/6a1bed2d7ed5494b051fae09d28787fd01de9635, originally from @tobiasholenstein.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297201](https://bugs.openjdk.org/browse/JDK-8297201): Obsolete AliasLevel flag

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Tobias Holenstein](https://openjdk.org/census#tholenstein) (@tobiasholenstein - Committer)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Contributors
 * Tobias Holenstein `<tholenstein@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11207/head:pull/11207` \
`$ git checkout pull/11207`

Update a local copy of the PR: \
`$ git checkout pull/11207` \
`$ git pull https://git.openjdk.org/jdk pull/11207/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11207`

View PR using the GUI difftool: \
`$ git pr show -t 11207`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11207.diff">https://git.openjdk.org/jdk/pull/11207.diff</a>

</details>

### CODE REVIEW

**Comment by tobiasholenstein** [comment]
I think `do_aliasing()` is always true in `*Compile::flatten_alias_type( const TypePtr *tj )` because `flatten_alias_type` is only called in the `Compile::find_alias_type(..)` function after we checked that `do_aliasing()` is true.

**Comment by TobiHartmann** [comment]
Good catch! I updated the fix accordingly.

**Review by chhagedorn — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
This removal looks accurate: AliasLevel == 0 -> do_aliasing == false; else do_aliasing == true

Thanks for fixing.

**Comment by tobiasholenstein** [comment]
Looks good to me

**Comment by TobiHartmann** [comment]
Christian, David, Toby, thanks for the reviews. I'll push this right away after some sanity testing to address the `gtest/GTestWrapper.java` failures.

**Review by tobiasholenstein — APPROVED** [review]

**Review by robcasloz — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks, Roberto!

**Pull request closed without merging**
