### PR TITLE
8302289: RISC-V: Use bgez instruction in arraycopy_simple_check when possible

### PR DESCRIPTION
**Pull request by zifeihan**
HI,

Refer to src/hotspot/cpu/s390/c1_LIRAssembler_s390.cpp, because Klass::_lh_neutral_value is always 0, we can use bgez here instead of the combination of mv and bge.

Please take a look and have some reviews. Thanks a lot.
## Testing:
- all tier1 on unmatched board without new failures

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302289](https://bugs.openjdk.org/browse/JDK-8302289): RISC-V: Use bgez instruction in arraycopy_simple_check when possible

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Dingli Zhang](https://openjdk.org/census#dzhang) (@DingliZhang - Author)
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12525/head:pull/12525` \
`$ git checkout pull/12525`

Update a local copy of the PR: \
`$ git checkout pull/12525` \
`$ git pull https://git.openjdk.org/jdk pull/12525/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12525`

View PR using the GUI difftool: \
`$ git pr show -t 12525`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12525.diff">https://git.openjdk.org/jdk/pull/12525.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good.

**Comment by DingliZhang** [comment]
LGTM, thanks! (not a reviewer)

**Review by DingliZhang — APPROVED** [review]

**Comment by zifeihan** [comment]
Thanks all for the review.
/integrate

**Review by luhenry — APPROVED** [review]

**Pull request closed without merging**
