### PR TITLE
8338858: Replace undocumented APIs with documented APIs in the OpenJDK

### PR DESCRIPTION
**Pull request by dhanalla**
The `wepoll` code has been ported from opensource repo [`wepoll`](https://github.com/piscisaureus/wepoll) to OpenJDK in PR [pull/3816](https://github.com/openjdk/jdk/pull/3816), which incorporated undocumented Windows APIs (NtCreateKeyedEvent, NtReleaseKeyedEvent, NtWaitForKeyedEvent). 

This PR aims to replace these undocumented APIs with documented synchronization APIs. 

Test Performed:
1. All 12 tests in wepoll repo passed 
           test-auto-drop-on-close PASS
           test-connect-fail-events PASS
           test-connect-success-events PASS
           test-ctl-fuzz PASS
           test-error PASS
           test-leak-1 PASS
           test-mixed-socket-types PASS
           test-multi-poll PASS
           test-oneshot-and-hangup PASS
           test-reflock PASS
           test-tree PASS
           test-udp-pings PASS
        DONE - 12 PASSED, 0 FAILED

2. No new failure in JTreg test
3. Micro bench results: similar performance score before and after the changes

without change in this PR:

image

With the change in this PR:

image

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338858](https://bugs.openjdk.org/browse/JDK-8338858): Replace undocumented APIs with documented APIs in the OpenJDK (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20682/head:pull/20682` \
`$ git checkout pull/20682`

Update a local copy of the PR: \
`$ git checkout pull/20682` \
`$ git pull https://git.openjdk.org/jdk.git pull/20682/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20682`

View PR using the GUI difftool: \
`$ git pr show -t 20682`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20682.diff">https://git.openjdk.org/jdk/pull/20682.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20682#issuecomment-2305387360)

### CODE REVIEW

**Comment by AlanBateman** [comment]
Is there is a PR open in piscisaureus/wepoll to propose these changes upstream?

**Comment by dhanalla** [comment]
> Is there is a PR open in piscisaureus/wepoll to propose these changes upstream?

Thanks @AlanBateman for reviewing this PR.
here is the wepoll PR https://github.com/piscisaureus/wepoll/pull/37

**Comment by AlanBateman** [comment]
Can you confirm that you've run jdk tier2 with these changes?

**Comment by AlanBateman** [comment]
@djelinski Would you have cycles to look at this? Ideally the changes would go upstream and/or Microsoft would contribute resources to that project. From a quick scan, the changes aren't too bad although there are some needless fixes to comment typos.

**Review by djelinski — COMMENTED** [review]
I understand that this is a like-for-like replacement, where `reflock__signal_event` waits for another thread to call `reflock__await_event`, because that's what `NtReleaseKeyedEvent` did, even if that is not necessary from the perspective of the calling code. It looks OK, but it doesn't make the code easier to follow.

I think if we're going to touch this code, we should make it more readable than the original. We could replace the whole reflock structure with SRW locks; `reflock_ref` is semantically equivalent to `AcquireSRWLockShared`, `reflock_unref` is equivalent to `ReleaseSRWLockShared`, and `reflock_unref_and_destroy` is equivalent to `ReleaseSRWLockShared` followed by `AcquireSRWLockExclusive`.

Also, I'd very much like to avoid forking wepoll here. We keep our own copy to simplify the build system, but we don't want to maintain our own fork. @dhanalla if the https://github.com/piscisaureus/wepoll/pull/37 request is not accepted, do you plan to maintain a fork of wepoll? Or is wepoll officially dead?

Finally, this PR claims to replace the undocumented APIs, but does nothing about the usage of AFD. Is there a plan to remove the AFD too?

**Comment by dhanalla** [comment]
> Can you confirm that you've run jdk tier2 with these changes?

@AlanBateman, I have run both Tier 1 and Tier 2 tests and can confirm that there are no new failures related to this change.

**Comment by dhanalla** [comment]
> I understand that this is a like-for-like replacement, where `reflock__signal_event` waits for another thread to call `reflock__await_event`, because that's what `NtReleaseKeyedEvent` did, even if that is not necessary from the perspective of the calling code. It looks OK, but it doesn't make the code easier to follow.
> 
> I think if we're going to touch this code, we should make it more readable than the original. We could replace the whole reflock structure with SRW locks; `reflock_ref` is semantically equivalent to `AcquireSRWLockShared`, `reflock_unref` is equivalent to `ReleaseSRWLockShared`, and `reflock_unref_and_destroy` is equivalent to `ReleaseSRWLockShared` followed by `AcquireSRWLockExclusive`.
> 
> Also, I'd very much like to avoid forking wepoll here. We keep our own copy to simplify the build system, but we don't want to maintain our own fork. @dhanalla if the [piscisaureus/wepoll#37](https://github.com/piscisaureus/wepoll/pull/37) request is not accepted, do you plan to maintain a fork of wepoll? Or is wepoll officially dead?
> 
> Finally, this PR claims to replace the undocumented APIs, but does nothing about the usage of AFD. Is there a plan to remove the AFD too?

Thank you @djelinski, At this time, we don’t have the bandwidth to fork and maintain wepoll. If this presents a challenge for the PR, we completely understand and will proceed by closing it. We will make the necessary changes directly in our downstream distribution.

**Pull request closed without merging**
