### PR TITLE
8327426: RISC-V: Move alignment shim into initialize_header() in C1_MacroAssembler::allocate_array

### PR DESCRIPTION
**Pull request by zifeihan**
Hi, I noticed that RISC-V missed this change from #11044 [1]: 

`I know @albertnetymk already touched on this but some thoughts on the unclear boundaries between the header and the data. My feeling is that the most pragmatic solution would be to have the header initialization always initialize up to the word aligned (up) header_size_in_bytes. (Similarly to how it is done for the instanceOop where the klass gap gets initialized with the header, even if it may be data.) And have the body initialization do the rest (word aligned to word aligned clear).`

`This seems preferable than adding these extra alignment shims in-between the header and body/payload/data initialization. (I also tried moving the alignment fix into the body initialization, but it seems a little bit messier in the implementation.)`

After this patch, it will be more consistent with other CPU platforms like X86 and ARM64.

[1] https://github.com/openjdk/jdk/pull/11044#pullrequestreview-1894323275

### Tests

- [x]  Run tier1-3 tests on SiFive unmatched (release)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327426](https://bugs.openjdk.org/browse/JDK-8327426): RISC-V: Move alignment shim into initialize_header() in C1_MacroAssembler::allocate_array (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18131/head:pull/18131` \
`$ git checkout pull/18131`

Update a local copy of the PR: \
`$ git checkout pull/18131` \
`$ git pull https://git.openjdk.org/jdk.git pull/18131/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18131`

View PR using the GUI difftool: \
`$ git pr show -t 18131`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18131.diff">https://git.openjdk.org/jdk/pull/18131.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18131#issuecomment-1980102730)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Thanks.

**Comment by zifeihan** [comment]
linux-riscv64 builds fine locally. GHA failure is infrastructural: https://bugs.openjdk.org/browse/JDK-8326960

**Comment by zifeihan** [comment]
@RealFYang Thanks for your review.
/integrate

**Pull request closed without merging**
