### PR TITLE
8328744: Parallel: Parallel GC throws OOM before heap is fully expanded

### PR DESCRIPTION
**Pull request by zhengyu123**
Parallel Scavenge may give up if it determines that current old gen does not have enough free space to accommodate estimated promotion size, and fall back to compact GC.

If compact GC can not reclaim enough space, this vicious cycle continues until OOM, without any intentions to expand old gen. We saw our production instances running hundreds compact GCs, while heaps were not fully utilized.

I believe when Scavenge determines if there is enough old space for the promotion, it should also consider the free space may be created by expanding the old gen.

Tests:
   hotspot_gc, tier1 and tier2 with Parallel GC (fastdebug and release) on x86_64 and MacOSX

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328744](https://bugs.openjdk.org/browse/JDK-8328744): Parallel: Parallel GC throws OOM before heap is fully expanded (**Bug** - P2)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18463/head:pull/18463` \
`$ git checkout pull/18463`

Update a local copy of the PR: \
`$ git checkout pull/18463` \
`$ git pull https://git.openjdk.org/jdk.git pull/18463/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18463`

View PR using the GUI difftool: \
`$ git pr show -t 18463`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18463.diff">https://git.openjdk.org/jdk/pull/18463.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18463#issuecomment-2016507527)

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Comment by zhengyu123** [comment]
Thanks for the reviews, @albertnetymk @tschatzl

**Pull request closed without merging**
