### PR TITLE
8289275: Remove incorrect __declspec(dllimport) attributes from pointers in jdk.crypto.cryptoki

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Several instances of function pointers in jdk.crypto.cryptoki are marked with the dllimport attribute, which should only be applied to symbol declarations, of which a typedef'd function pointer is not. This would only be useful if a function pointer defined in the linked dll is desired to be imported, not if the pointer itself is created locally and used to store a function address. In addition to being incorrect, at least on the versions of Visual C++ the JDK supports today, it is also redundant; Typically they are used to avoid an indirect stub that jumps to the proper entry in the import address table, but usage of these typedefs involves loading the address of a function and directly (Usually through GetProcAddress, even in other cases it would simply be set to the address of a function anyway) assigning it to the pointer before immediately dispatching when called, which bypasses this procedure entirely and makes the attribute pointless.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289275](https://bugs.openjdk.org/browse/JDK-8289275): Remove incorrect __declspec(dllimport) attributes from pointers in jdk.crypto.cryptoki

### Reviewers
 * [Valerie Peng](https://openjdk.org/census#valeriep) (@valeriepeng - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9353/head:pull/9353` \
`$ git checkout pull/9353`

Update a local copy of the PR: \
`$ git checkout pull/9353` \
`$ git pull https://git.openjdk.org/jdk pull/9353/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9353`

View PR using the GUI difftool: \
`$ git pr show -t 9353`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9353.diff">https://git.openjdk.org/jdk/pull/9353.diff</a>

</details>

### CODE REVIEW

**Comment by valeriepeng** [comment]
pkcs11.h is a standard header file from OASIS. Best to leave it alone. Just my .02.

**Comment by TheShermanTanker** [comment]
> pkcs11.h is a standard header file from OASIS. Best to leave it alone. Just my .02.

The only change to pkcs11.h is in a comment though, the other changes are outside the ANSI C headers from the standard. Should I just revert the comment in that case?

**Comment by TheShermanTanker** [comment]
Tested with `Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104` using `FPTR_VersionCheck`, no differences in the generated assembly snippets:

Without __declspec(dllimport):
```
   0:	48 83 ec 38          	sub    $0x38,%rsp
   4:	48 8d 0d 00 00 00 00 	lea    0x0(%rip),%rcx        # b <main+0xb>
   b:	ff 54 24 20          	call   *0x20(%rsp)
   f:	33 c0                	xor    %eax,%eax
  11:	48 83 c4 38          	add    $0x38,%rsp
  15:	c3                   	ret   
``` 

With __declspec(dllimport):
```
   0:	48 83 ec 38          	sub    $0x38,%rsp
   4:	48 8d 0d 00 00 00 00 	lea    0x0(%rip),%rcx        # b <main+0xb>
   b:	ff 54 24 20          	call   *0x20(%rsp)
   f:	33 c0                	xor    %eax,%eax
  11:	48 83 c4 38          	add    $0x38,%rsp
  15:	c3                   	ret    
```

**Comment by valeriepeng** [comment]
> > pkcs11.h is a standard header file from OASIS. Best to leave it alone. Just my .02.
> 
> The only change to pkcs11.h is in a comment though, the other changes are outside the ANSI C headers from the standard. Should I just revert the comment in that case?

Sounds good to me.
Will take a look at the rest of changes in a day or two.
Thanks!

**Comment by TheShermanTanker** [comment]
> > > pkcs11.h is a standard header file from OASIS. Best to leave it alone. Just my .02.
> > 
> > 
> > The only change to pkcs11.h is in a comment though, the other changes are outside the ANSI C headers from the standard. Should I just revert the comment in that case?
> 
> Sounds good to me. Will take a look at the rest of changes in a day or two. Thanks!

Alright, will do. I also do want to look at p11_md.h to see if my changes are appropriate in the meantime, as I have a feeling it can be accomplished somewhat more elegantly

Thanks for the review!

**Review by valeriepeng — APPROVED** [review]

**Comment by TheShermanTanker** [comment]
@valeriepeng Might need you to sponsor this, thanks for the review!

**Pull request closed without merging**
