### PR TITLE
8310027: Fix -Wconversion warnings in nmethod and compiledMethod related code

### PR DESCRIPTION
**Pull request by coleenp**
This change adds casts to nmethod and compiled method offset and size functions that return int, and checked_casts where it's not obvious or already checked that the cast is correct.
Tested with tier1 on Oracle platforms, and tier1-4 linux and windows.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310027](https://bugs.openjdk.org/browse/JDK-8310027): Fix -Wconversion warnings in nmethod and compiledMethod related code (**Bug** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14505/head:pull/14505` \
`$ git checkout pull/14505`

Update a local copy of the PR: \
`$ git checkout pull/14505` \
`$ git pull https://git.openjdk.org/jdk.git pull/14505/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14505`

View PR using the GUI difftool: \
`$ git pr show -t 14505`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14505.diff">https://git.openjdk.org/jdk/pull/14505.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14505#issuecomment-1594615653)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thanks Vladimir.

**Review by fparain — APPROVED** [review]
Looks good to me

**Pull request closed without merging**
