### PR TITLE
8291000: C2: Purge LoadPLocked and Store*Conditional nodes

### PR DESCRIPTION
**Pull request by shipilev**
The last uses for these nodes was the inline contiguous allocations. With [JDK-8290706](https://bugs.openjdk.org/browse/JDK-8290706), these nodes are not used anymore and can be cleaned up.

Testing:
 - [x] Linux x86_64 fastdebug tier1
 - [x] Linux x86_32 fastdebug tier1
 - [x] Linux AArch64 fastdebug tier1
 - [x] Linux x86_64 Zero build
 - [x] Linux AArch64 cross-build
 - [x] Linux ARM cross-build
 - [x] Linux S390X cross-build
 - [x] Linux PPC64 cross-build
 - [x] Linux RISC-V cross-build

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291000](https://bugs.openjdk.org/browse/JDK-8291000): C2: Purge LoadPLocked and Store*Conditional nodes

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9636/head:pull/9636` \
`$ git checkout pull/9636`

Update a local copy of the PR: \
`$ git checkout pull/9636` \
`$ git pull https://git.openjdk.org/jdk pull/9636/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9636`

View PR using the GUI difftool: \
`$ git pr show -t 9636`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9636.diff">https://git.openjdk.org/jdk/pull/9636.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Nice change. Looks good.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
Thank you, I'll be integrating soon, if there are no objections.

**Pull request closed without merging**
