### PR TITLE
8307588: [JVMCI] HotSpotConstantPool#lookupBootstrapMethodInvocation broken by JDK-8301995

### PR DESCRIPTION
**Pull request by zapster**
As a result of the changes for [JDK-8301995](https://bugs.openjdk.org/browse/JDK-8301995), `HotSpotConstantPool#lookupBootstrapMethodIntrospection` is broken as it no longer decodes the correct constant pool index for looking up the bootstrap method invocation for invokedynamic.

This fixes the problem and modifies `TestDynamicConstant` to exercise the code in question.

I've manually verified that this solved the native image issues that uncovered the problem.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307588](https://bugs.openjdk.org/browse/JDK-8307588): [JVMCI] HotSpotConstantPool#lookupBootstrapMethodInvocation broken by JDK-8301995

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - Committer) ⚠️ Review applies to [b271e842](https://git.openjdk.org/jdk/pull/13858/files/b271e8429aedcef13db0211c7114c562d97ee3e2)
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**) ⚠️ Review applies to [b271e842](https://git.openjdk.org/jdk/pull/13858/files/b271e8429aedcef13db0211c7114c562d97ee3e2)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13858/head:pull/13858` \
`$ git checkout pull/13858`

Update a local copy of the PR: \
`$ git checkout pull/13858` \
`$ git pull https://git.openjdk.org/jdk.git pull/13858/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13858`

View PR using the GUI difftool: \
`$ git pr show -t 13858`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13858.diff">https://git.openjdk.org/jdk/pull/13858.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13858#issuecomment-1537979898)

### CODE REVIEW

**Review by dougxc — APPROVED** [review]

**Review by tkrodriguez — APPROVED** [review]

**Comment by zapster** [comment]
Thanks for the reviews!

**Review by vnkozlov — COMMENTED** [review]
Please, update Copyright year in test file.  No need for re-testing.

**Comment by zapster** [comment]
Thanks @vnkozlov, done.

**Comment by vnkozlov** [comment]
And, please activate GH Actions testing in you repo.

**Review by vnkozlov — APPROVED** [review]
Good.
Please, wait GHA finish before integration.

**Pull request closed without merging**
