### PR TITLE
8336098: G1: Refactor G1RebuildRSAndScrubTask

### PR DESCRIPTION
**Pull request by albertnetymk**
Small refactoring to consolidate the early-return logic during scan-and-rebuild.

Test: tie1-3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336098](https://bugs.openjdk.org/browse/JDK-8336098): G1: Refactor G1RebuildRSAndScrubTask (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20114/head:pull/20114` \
`$ git checkout pull/20114`

Update a local copy of the PR: \
`$ git checkout pull/20114` \
`$ git pull https://git.openjdk.org/jdk.git pull/20114/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20114`

View PR using the GUI difftool: \
`$ git pr show -t 20114`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20114.diff">https://git.openjdk.org/jdk/pull/20114.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20114#issuecomment-2221385500)

### CODE REVIEW

**Review by tschatzl — COMMENTED** [review]
Did you do cursory performance measurements as this change uses the chunked version of scanning for every object now? We intentionally do not do that in pauses (i.e. use the `oop_oop_iterate(, MemRegion)` code), and the reason for this split here is the same.

I.e. this has been done intentionally, not just to complicate code. Scrubbing/rebuild performance is on the critical path to reclaim memory.

I also do not really like the inlining in `scan_and_scrub_region` - the compiler will do it for us and it makes the method a lot larger which is something you noticed given the additional comments and the extra scopes. I would (slightly) prefer if that were reverted, but I do not mind that.

**Comment by albertnetymk** [comment]
I have reverted the `oop_oop_iterate` part, which sometime is perf-neutral or -8% regression from run to run...

Also modified `scan_and_scrub_region` a bit to make the enclosing two steps more symmetric and the whole method smaller.

**Review by lgxbslgx — CHANGES_REQUESTED** [review]
Please note several logs are removed in this patch. I am OK with such removal, considering that the logs are at trace level.

One nit below.

**Review by lgxbslgx — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
