### PR TITLE
8278276: G1: Refine naming of G1GCParPhaseTimesTracker::_must_record

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is a trivial improvement to refine the naming of G1GCParPhaseTimesTracker::_must_record to _initial_record.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278276](https://bugs.openjdk.java.net/browse/JDK-8278276): G1: Refine naming of G1GCParPhaseTimesTracker::_must_record

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to fee8048903a6836117775bcf5b9eb5f824b2c7e5
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to fee8048903a6836117775bcf5b9eb5f824b2c7e5

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6714/head:pull/6714` \
`$ git checkout pull/6714`

Update a local copy of the PR: \
`$ git checkout pull/6714` \
`$ git pull https://git.openjdk.java.net/jdk pull/6714/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6714`

View PR using the GUI difftool: \
`$ git pr show -t 6714`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6714.diff">https://git.openjdk.java.net/jdk/pull/6714.diff</a>

</details>

### CODE REVIEW

**Comment by kstefanj** [comment]
I wonder if we could find an even better name than `initial_record`. The member is there to tell whether or not we can have multiple instances using the same phase. So something like `single_record` would be more accurate imho. 

An alternative would be to switch the `bool` to be `false` by default and call it something like `allow_multiple_record`, not sure this is better. Let's here what other thinks.

**Comment by Hamlin-Li** [comment]
Thanks Stefan, I think your suggestion is better, I prefer `allow_multiple_record`, let's see others' opinion.

**Comment by tschatzl** [comment]
I prefer `allow_multiple_record` too.

**Comment by Hamlin-Li** [comment]
Thanks Thomas for confirmation.

**Review by kstefanj — APPROVED** [review]
Looks good!

**Comment by Hamlin-Li** [comment]
Can I get another approval, or this is trivial? :)

**Review by tschatzl — APPROVED** [review]
Lgtm. Please fix the issue with the copyright date before pushing.

**Comment by Hamlin-Li** [comment]
Thanks @tschatzl @kstefanj for your reviews.

/integrate

**Pull request closed without merging**
