### PR TITLE
8258742: Move PtrQueue reset to PtrQueueSet subclasses

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the PtrQueue hierarchy, changing queue reset
from an intrinsic operation of the queue to an operation the qset performs
on a queue.  This is another piece of the refactoring being done under
JDK-8258251, separated out for easier review.

After the refactoring of queue reset, PtrQueue::is_empty and PtrQueue::size
are no longer used, so are removed.  Further, PtrQueue::{set_}index_in_bytes
are removed, directly using _index instead.

A less obvious part of the change is in the G1 remark task and Shenandoah
final marking task.  The threads walk performed by these no longer directly
processes the partial per-thread SATB buffers.  Instead they just flush the
queues for later completed buffer processing.

Testing:
mach5 tier1
local (linux-x64) hotspot:tier1 with -XX:+UseShenandoahGC

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258742](https://bugs.openjdk.java.net/browse/JDK-8258742): Move PtrQueue reset to PtrQueueSet subclasses

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 593b40b7f2068d70c90390935bdce042d4818781
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to 593b40b7f2068d70c90390935bdce042d4818781

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2115/head:pull/2115`
`$ git checkout pull/2115`

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]
Looks good!

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @walulyai for reviews.

**Pull request closed without merging**
