### PR TITLE
8319673: Few security tests ignore VM flags

### PR DESCRIPTION
**Pull request by mpdonova**
In this PR I updated the tests to use the newer ProcessTools.createTestJavaProcessBuilder() methods to launch child processes. This method ensures that VM options are passed to subprocesses.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319673](https://bugs.openjdk.org/browse/JDK-8319673): Few security tests ignore VM flags (**Sub-task** - P4)

### Reviewers
 * [Weijun Wang](https://openjdk.org/census#weijun) (@wangweij - **Reviewer**)
 * [Hai-May Chao](https://openjdk.org/census#hchao) (@haimaychao - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17877/head:pull/17877` \
`$ git checkout pull/17877`

Update a local copy of the PR: \
`$ git checkout pull/17877` \
`$ git pull https://git.openjdk.org/jdk.git pull/17877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17877`

View PR using the GUI difftool: \
`$ git pr show -t 17877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17877.diff">https://git.openjdk.org/jdk/pull/17877.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17877#issuecomment-1946623405)

### CODE REVIEW

**Comment by haimaychao** [comment]
Test sun/security/tools/jarsigner/compatibility/SignTwice.java is listed as test needs to be updated in the bug, but not in the webrev?

**Comment by mpdonova** [comment]
> Test sun/security/tools/jarsigner/compatibility/SignTwice.java is listed as test needs to be updated in the bug, but not in the webrev?

SignTwice.java just invokes `Compatibility.main()`. I updated Compatibility.java to pass VM options to subprocesses.

**Comment by mpdonova** [comment]
> The tests that used to call `createLimitedTestJavaProcessBuilder` intentionally avoid copying all the VM options so they can provide their own. Are you sure they should be modified?

I reverted two tests that used `createLimitedTestJavaProcessBuilder`, the third, DKSTest.java, is ok using the other method.

**Review by haimaychao — APPROVED** [review]
Nit: Copyright year of IterationCount.java would need to be changed.

**Comment by haimaychao** [comment]
Looks good. Thanks.

**Comment by rhalade** [comment]
> > Nit: Copyright year of IterationCount.java would need to be changed.
> 
> That is a Red Hat copyright; should I add an Oracle copyright? The file isn't significantly changed.

AFAIK, no need to update with Oracle copyright for this update.

**Pull request closed without merging**
