### PR TITLE
8276025: Hotspot's libsvml.so may conflict with user dependency

### PR DESCRIPTION
**Pull request by sviswa7**
This patch removes conflicts with libsvml.so distributed with Intel's MKL library:
  Renames exported symbols from __svml to __jsvml.
  Renames library from libsvml.so to libjsvml.so.
  Updates the stubGenerator_x86_64.cpp  accordingly to load libjsvml.so and the renamed symbols.
  Updates tests to look for the new library.

Please review.

Best Regards,
Sandhya

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276025](https://bugs.openjdk.java.net/browse/JDK-8276025): Hotspot's libsvml.so may conflict with user dependency

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6265/head:pull/6265` \
`$ git checkout pull/6265`

Update a local copy of the PR: \
`$ git checkout pull/6265` \
`$ git pull https://git.openjdk.java.net/jdk pull/6265/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6265`

View PR using the GUI difftool: \
`$ git pr show -t 6265`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6265.diff">https://git.openjdk.java.net/jdk/pull/6265.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good. I will run tests.

**Comment by vnkozlov** [comment]
For completeness may be rename files too: jsvml_*.S

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by erikj79 — APPROVED** [review]
Build changes look good.

**Comment by vnkozlov** [comment]
There is also need to update one closed test we have before integration.

**Review by PaulSandoz — APPROVED** [review]
I did a case insensitive regex search `[^j]svml` over the checked out PR and did not find anything relevant that was missed.

**Review by magicus — APPROVED** [review]

**Comment by vnkozlov** [comment]
@sviswa7 testing passed you can integrate.

**Comment by sviswa7** [comment]
Thanks a lot @vnkozlov for testing and review.
Thanks @erikj79 @PaulSandoz @magicus for the review.

**Pull request closed without merging**
