### PR TITLE
8346039: [BACKOUT] - [C1] LIR Operations with one input should be implemented as LIR_Op1

### PR DESCRIPTION
**Pull request by dholmes-ora**
Revert "8345609: [C1] LIR Operations with one input should be implemented as LIR_Op1"

This reverts commit a21d21f4d7b74e21f68b6bf9c5dc9ba7d3f9963c.

Testing tiers 1-3 in progress

Thanks

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8346039](https://bugs.openjdk.org/browse/JDK-8346039): [BACKOUT] - [C1] LIR Operations with one input should be implemented as LIR_Op1 (**Sub-task** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22690/head:pull/22690` \
`$ git checkout pull/22690`

Update a local copy of the PR: \
`$ git checkout pull/22690` \
`$ git pull https://git.openjdk.org/jdk.git pull/22690/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22690`

View PR using the GUI difftool: \
`$ git pr show -t 22690`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22690.diff">https://git.openjdk.org/jdk/pull/22690.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22690#issuecomment-2537125881)
</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by dholmes-ora** [comment]
Thanks for the review @vnkozlov !

Just awaiting testing to complete.

**Review by TheRealMDoerr — APPROVED** [review]
Backout looks correct. I wonder on what kind of machine the issue showed up. Was it 32 bit? Tier 2 has passed on our machines.

**Comment by dholmes-ora** [comment]
@TheRealMDoerr  Windows -x64 and Linux-x64. It is intermittent (I guess random register content might cause that).

Thanks for the review.

**Comment by dholmes-ora** [comment]
@TheRealMDoerr  I've added some failing test info to [JDK-8346038](https://bugs.openjdk.org/browse/JDK-8346038)

**Comment by TheRealMDoerr** [comment]
It must be machine dependent. I guess `UseAVX > 2 && !VM_Version::supports_avx512vl()` is the case which is not hit by our machines. Could you confirm that?

**Comment by dholmes-ora** [comment]
Yes the failing runs have `-XX:UseAVX=3 -XX:+UnlockDiagnosticVMOptions -XX:+UseKNLSetting`

**Comment by TheRealMDoerr** [comment]
Thanks for confirming!
@vnkozlov: Regarding the redo: Do you think we can remove the separate case https://github.com/openjdk/jdk/blob/64fad1c7d374bbc635bad3b1fa7941379f39565f/src/hotspot/cpu/x86/c1_LIRAssembler_x86.cpp#L3802 and fall back to `xorps` in C1? That would simplify the code a lot and avoid an extra temp register and the preloading with `LIR_OprFact::floatConst(-0.0)`?

**Comment by vnkozlov** [comment]
@TheRealMDoerr  I don't know simple answer for your question.

These checks were added after failures during testing changes for [JDK-821076](https://bugs.openjdk.org/browse/JDK-8210764) [diffs](https://github.com/openjdk/jdk/commit/092fe55fb10a979534cfd69eaa35546f3af11677#diff-144639248eb0a12e15e1e8d36dae1fdd5d6ad6948610f283c7c26a807b431a6eL3768)

Here is review of these changes: https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2018-September/030629.html

The issue could be that we should avoid mixing encoding modes for AVX instructions (when C1 and C2 compiled methods call each other).

May be we should wait when @sviswa7 is back from vacation and get her answer to your question.

If it is not about mixing mode we can accept small performance issues since C1 generated code will be replaced with C2 generated.

**Comment by merykitty** [comment]
@TheRealMDoerr I have not looked too closely at your change, but from the error messages I guess the failure may be due to the fact that input operands are not required to live during the node, while temp operands live only during the node. As a result, they may be assigned the same register by the allocator, which is not correct for some of the nodes here.

**Comment by TheRealMDoerr** [comment]
Thanks everyone for looking into the issue and the assistance. I have understood the problem. C1 allows using the same register for a temp and an input operand. Another problem is that the `UseKNLSetting` code needs the `floatConst(-0.0)` for `lir_abs` and `lir_neg`.
Only the code for `UseAVX > 2 && !VM_Version::supports_avx512vl()` is affected. The rest looks correct and all tests had passed without this mode.
I'll check with @sviswa7 if we can remove this extra code from C1.

**Comment by TheRealMDoerr** [comment]
I've created a draft PR with the removal: https://github.com/openjdk/jdk/pull/22709
The new code actually looks better to me, but I'll wait for the feedback from Intel.

**Pull request closed without merging**
