### PR TITLE
8344222: Remove calls to SecurityManager and doPrivileged  in java.net.HttpURLConnection, java.net.HttpConnectSocketImpl,  and javax.net.HttpsURLConnection after JEP 486 integration

### PR DESCRIPTION
**Pull request by vy**
Addresses [8344222](https://bugs.openjdk.org/browse/JDK-8344222) and removes `SecurityManager` and `doPrivileged()` usages from `Http(s)URLConnection` and `HttpConnectSocketImpl`. `tier2` and `tier3` results are on their way.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344222](https://bugs.openjdk.org/browse/JDK-8344222): Remove calls to SecurityManager and doPrivileged  in java.net.HttpURLConnection, java.net.HttpConnectSocketImpl,  and javax.net.HttpsURLConnection after JEP 486 integration (**Sub-task** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22326/head:pull/22326` \
`$ git checkout pull/22326`

Update a local copy of the PR: \
`$ git checkout pull/22326` \
`$ git pull https://git.openjdk.org/jdk.git pull/22326/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22326`

View PR using the GUI difftool: \
`$ git pr show -t 22326`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22326.diff">https://git.openjdk.org/jdk/pull/22326.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22326#issuecomment-2493905842)
</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]
LGTM

**Review by jaikiran — APPROVED** [review]
These changes look good to me.

**Pull request closed without merging**
