### PR TITLE
8273216: JCMD does not work across container boundaries with Podman

### PR DESCRIPTION
**Pull request by jerboaa**
Please review this test fix so as to make it work with podman too. I've tested this with podman 3.3.1 when running as regular user and when running as root. Also tested it with docker on cgroups v1 with root. I don't know how to do rootless docker testing.

Thoughts?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273216](https://bugs.openjdk.java.net/browse/JDK-8273216): JCMD does not work across container boundaries with Podman

### Reviewers
 * [Mikhailo Seledtsov](https://openjdk.java.net/census#mseledtsov) (@mseledts - Committer)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5740/head:pull/5740` \
`$ git checkout pull/5740`

Update a local copy of the PR: \
`$ git checkout pull/5740` \
`$ git pull https://git.openjdk.java.net/jdk pull/5740/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5740`

View PR using the GUI difftool: \
`$ git pr show -t 5740`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5740.diff">https://git.openjdk.java.net/jdk/pull/5740.diff</a>

</details>

### CODE REVIEW

**Comment by mseledts** [comment]
Severin, thank you for addressing this issue. Overall the change looks good.

I ran your change through Oracle's test system, and the Docker case passes. However, a Podman case fails when running 'jcmd -l' attempting to find the target test child process - could not find it. Please note that we run both Docker and Podman tests in non-root mode (a regular "test user"). Perhaps the test should have conditional guards for it, and throw a jtreg.SkippedException for Podman non-root user with a short message?

---------System.err:(13/757)----------
java.lang.RuntimeException: Could not find specified process
	at TestJcmd.testJcmdGetPid(TestJcmd.java:103)
	at TestJcmd.main(TestJcmd.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:833)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test

result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Could not find specified process

**Comment by mseledts** [comment]
Also, I checked a Podman version on our test systems: it is earlier/below 3.3.1. Perhaps the conditional guard in the test should check for that as well, and if version is below 3.3.1, we should check if user is root, and throw SkippedException if not?

**Comment by jerboaa** [comment]
@mseledts Thanks for the review and tests. I've now added a version check for podman. I've run this with 3.3.1 and it works fine in rootless mode. It should start to work for you once you upgrade. Thoughts?

**Review by mseledts — APPROVED** [review]
Changes look good to me. This version now passes Oracle container testing, thank you.

**Comment by jerboaa** [comment]
Thanks for the review, @mseledts. Any (R)eviewers please?

**Review by hseigel — APPROVED** [review]
Changes look good.  Thanks for fixing this.
Harold

**Comment by jerboaa** [comment]
Thank you, Harold!

/integrate

**Pull request closed without merging**
