### PR TITLE
8284294: Create an automated regression test for RFE 4138746

### PR DESCRIPTION
**Pull request by manukumarvs**
Create an automated regression test for [JDK-4138746](https://bugs.openjdk.java.net/browse/JDK-4138746)

Issue:
In the following example (and similarly with other components) you cannot specify the correct character to underline:

JLabel label = new JLabel ("Save As...");
label.setDisplayedMnemonic ('A');

The 'A' in 'As' should be underlined (that's the intention at least), but the 'a' in 'Save' is what gets underlined.

The problem (aside from the lack of an API to specify exactly what should be underlined) is in the javax.swing.plaf.basic.BasicGraphicUtils drawString method which underlines the first character (upper OR lowercase) that matches the mnemonic character.

Fix:
A new property "displayedMnemonicIndex" is introduced
in classes AbstractButton and JLabel. It tells which
character to underline. So for example to underline
the capital 'A' in 'Save As', one should call:
    setMnemonic('A');
    setDisplayedMnemonicIndex(5);

Testing:
Tested in Mach5 10 times per platform and got all Pass.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284294](https://bugs.openjdk.java.net/browse/JDK-8284294): Create an automated regression test for RFE 4138746

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to 9c951603ecf299c06d80adcff8b7ff947df06d8d

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8093/head:pull/8093` \
`$ git checkout pull/8093`

Update a local copy of the PR: \
`$ git checkout pull/8093` \
`$ git pull https://git.openjdk.java.net/jdk pull/8093/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8093`

View PR using the GUI difftool: \
`$ git pr show -t 8093`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8093.diff">https://git.openjdk.java.net/jdk/pull/8093.diff</a>

</details>

### CODE REVIEW

**Comment by manukumarvs** [comment]
@aivanov-jdk Can you please review this.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
