### PR TITLE
8253768: Deleting unused pipe_class definitions in adl-file (x86_64.ad).

### PR DESCRIPTION
**Pull request by phedlin**
/issue create hotspot/compiler

This is just removing some dead/unused code. More importantly, this is a test of the new "issue create" support in Skara.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253768](https://bugs.openjdk.java.net/browse/JDK-8253768): Deleting unused pipe_class definitions in adl-file (x86_64.ad).

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/74/head:pull/74`
`$ git checkout pull/74`

### CODE REVIEW

**Comment by phedlin** [comment]
Deleting unused pipe_class definitions in adl-file (x86_64.ad).
/issue create hotspot/compiler

**Review by neliasso — APPROVED** [review]
Looks good.

**Comment by phedlin** [comment]
Thanks for reviewing Nils.

**Pull request closed without merging**
