### PR TITLE
8252684: Move the AArch64 assember test under test/hotspot/gtest

### PR DESCRIPTION
**Pull request by nick-arm**
There was a question on the SVE review thread on build-dev [1] a few
months ago about why there is a Python script and test code under
src/hotspot/cpu/aarch64. The script generates code to check the
Assembler instruction encodings against those of the system assembler.
The test runs every time the debug VM is started.

AFAIK there's no precedent in the rest of Hotspot for having functional
tests that run on startup, and we have the existing gtest framework for
testing internal C++ modules. This patch (perhaps more of an RFC) moves
the assembler test under test/hotspot/gtest/aarch64.

The test will now run in tier1, including for release builds. The
downside is that debug builds won't catch assembler encoding errors
immediately on startup.

Tested by injecting an error in one of the instruction encodings and
verifying `make test TEST="gtest"` fails.

[1] https://mail.openjdk.java.net/pipermail/build-dev/2020-August/028048.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (8/8 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (1/9 failed) |    |  ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x86 (hs/tier1 compiler)](https://github.com/nick-arm/jdk/runs/1467231153)
- [Windows x64 (build debug)](https://github.com/nick-arm/jdk/runs/1467146856)
- [Windows x64 (build release)](https://github.com/nick-arm/jdk/runs/1467146848)

### Issue
 * [JDK-8252684](https://bugs.openjdk.java.net/browse/JDK-8252684): Move the AArch64 assember test under test/hotspot/gtest

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1476/head:pull/1476`
`$ git checkout pull/1476`

### CODE REVIEW

**Comment by luhenry** [comment]
From having worked on the Windows and macOS port to AArch64, I concur that moving the test to the already dedicated gtest test suite makes more sense.

**Comment by nick-arm** [comment]
> 
> I now wonder if we could even get a step further and have the Python script generate the entirety of `test/hotspot/gtest/aarch64/test_assembler_aarch64.cpp`. It would be about adding just the copyright, the headesr `#include`, and some glue code. That would make it easier to regenerate the file instead of depending on a copy-paste.

I suppose it doesn't need to generate the whole file: the Python script can just write its output to a file that gets `#include`d into `test_assembler_aarch64.cpp`.

**Comment by theRealAph** [comment]
> I suppose it doesn't need to generate the whole file: the Python script can just write its output to a file that gets `#include`d into `test_assembler_aarch64.cpp`.

Indeed. I did wonder about regenerating everything by running the Python script at test time, but reasoned that doing so would introduce a dependency on build tools ("as", for example) that I didn't want to have. But moving the output of aarch64_asmtest.py into a separate file is a good idea, if you like.

I'm minded to just approve this patch as it is now.

**Comment by nick-arm** [comment]
> 
> Indeed. I did wonder about regenerating everything by running the Python script at test time, but reasoned that doing so would introduce a dependency on build tools ("as", for example) that I didn't want to have. But moving the output of aarch64_asmtest.py into a separate file is a good idea, if you like.
> 

I moved the output to a separate file `asmtest.out.h` with note on how to generate it.

**Review by theRealAph — APPROVED** [review]

**Comment by dholmes-ora** [comment]
This has broken all the regular x86 Windows builds! Please fix or backout immediately!

**Comment by dholmes-ora** [comment]
IIUC given:
```
#ifdef AARCH64
#include "precompiled.hpp"
```
VS will ignore the ifdef as it appears before the precompiled header include.

**Comment by nick-arm** [comment]
> This has broken all the regular x86 Windows builds! Please fix or backout immediately!

@dholmes-ora sorry I don't have access to a computer at the moment, would you mind reverting it for me? The added file is wrapped in #ifdef AARCH64 so I don't know why that affects windows x86.

**Comment by dholmes-ora** [comment]
The ifdef needs to come after the include of the precompiled header. I'm filing a bug. But it is Sunday for me too and I have very limited time.

**Pull request closed without merging**
