### PR TITLE
8295457: Make the signatures of write barrier methods consistent

### PR DESCRIPTION
**Pull request by caizixian**
Currently, the signatures for various write barrier related methods are inconsistent and can be a bit confusing. Let's take x86 as an example.

The `store_at` of `BarrierSetAssembler` uses `dst` and `val`, and similarly for `oop_store_at` of `CardTableBarrierSetAssembler`.

https://github.com/openjdk/jdk/blob/358ac07255cc640cbcb9b0df5302d97891a34087/src/hotspot/cpu/x86/gc/shared/barrierSetAssembler_x86.hpp#L50

https://github.com/openjdk/jdk/blob/358ac07255cc640cbcb9b0df5302d97891a34087/src/hotspot/cpu/x86/gc/shared/cardTableBarrierSetAssembler_x86.hpp#L38

However, `access_store_at` and `store_heap_oop` of `MacroAssembler` use `dst` and `src`, presumably copied from `access_load_at` and `load_heap_oop` respectively.

https://github.com/openjdk/jdk/blob/358ac07255cc640cbcb9b0df5302d97891a34087/src/hotspot/cpu/x86/macroAssembler_x86.hpp#L355

https://github.com/openjdk/jdk/blob/358ac07255cc640cbcb9b0df5302d97891a34087/src/hotspot/cpu/x86/macroAssembler_x86.hpp#L362

This PR cleans up the signature of write barrier methods across affected architectures, hopefully making them less confusing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295457](https://bugs.openjdk.org/browse/JDK-8295457): Make the signatures of write barrier methods consistent

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [040c6bcf](https://git.openjdk.org/jdk/pull/10739/files/040c6bcf1c6dfb1a18ea8002e57ebf42e9f87b3d)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [040c6bcf](https://git.openjdk.org/jdk/pull/10739/files/040c6bcf1c6dfb1a18ea8002e57ebf42e9f87b3d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10739/head:pull/10739` \
`$ git checkout pull/10739`

Update a local copy of the PR: \
`$ git checkout pull/10739` \
`$ git pull https://git.openjdk.org/jdk pull/10739/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10739`

View PR using the GUI difftool: \
`$ git pr show -t 10739`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10739.diff">https://git.openjdk.org/jdk/pull/10739.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Submitted https://bugs.openjdk.org/browse/JDK-8295457 for this PR, please rename it to: "8295457: Make the signatures of write barrier methods consistent" to let bots hook it up.

**Comment by caizixian** [comment]
@shipilev Thanks, I've just fixed the title. Tests have all passed.

**Review by tschatzl — APPROVED** [review]

**Review by shipilev — COMMENTED** [review]
Do you want to check `macroAssembler_ppc.*`, `macroAssembler_arm.*` too?

**Review by shipilev — APPROVED** [review]
All right then!

**Comment by caizixian** [comment]
Not sure why the bot was complaining about rebasing. I merged the latest commits from master.

**Pull request closed without merging**
