### PR TITLE
8254104: MethodCounters must exist before nmethod is installed

### PR DESCRIPTION
**Pull request by veresov**
Ensure that MethodCounters for a particular method exist during the nmethod install (for methods that were never run before). Tiered compilation policy depends on the state stored in the counters to function properly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (3/3 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ❌ (1/9 failed) | ✔️ (9/9 passed) |

**Failed test task**
- [Windows x64 (langtools/tier1)](https://github.com/veresov/jdk/runs/1221831410)

### Issue
 * [JDK-8254104](https://bugs.openjdk.java.net/browse/JDK-8254104): MethodCounters must exist before nmethod is installed

### Reviewers
 * [Doug Simon](https://openjdk.java.net/census#dnsimon) (@dougxc - Committer) ⚠️ Review applies to b626ad9c987d702e1232a6fe81d3de8b0f8862b9
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/543/head:pull/543`
`$ git checkout pull/543`

### CODE REVIEW

**Review by dougxc — APPROVED** [review]

**Comment by vnkozlov** [comment]
Would be great if you explain in what cases you don't have MethodCounters  *AFTER* compilation?
Should you do that at the beginning of compilation?
We do check for presence of MDO during start of compilation (C2 example):
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/compile.cpp#L599

**Comment by veresov** [comment]
The need for MethodCounters to be present is driven by the tiered compilation policy. It's not needed by a compiler per se. Moreover you don't need then if you don't install the code. For example when compilation happens for native image it's not needed. Anyways, seemed like an appropriate place to do it.

**Comment by veresov** [comment]
Oh, and to answer your question about when it happens. In most Graal unit tests it compiles and installs methods that have been never executed in the interpreter, which normally lazily allocates the counters.

**Comment by vnkozlov** [comment]
Okay. MethodCounters are created in Interpreter in all cases regardless TieredCompilation setting:
https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/templateInterpreterGenerator_x86.cpp#L386

So check for TieredCompilation is strange.

I understand that MethodCounters are not created in AOT case. And now I get that it includes Graal unit testing as you pointed (which similar to AOT) which request compilation through Java and not usual Compilation Broker. In which case you fix is reasonable.

**Review by vnkozlov — APPROVED** [review]
OK

**Pull request closed without merging**
