### PR TITLE
8281100: Spurious "variable might not have been initialized" with sealed class switch

### PR DESCRIPTION
**Pull request by lahodaj**
Consider:
```
interface I permits A, B {}

String data;
I i = ...;
switch (i) {
    case A a -> data = 0;
    case B b -> data = 0;
}
System.err.println(data); //incorrect error here
```

The specification says that `data` is definitely assigned as the `System.err.println`, as the switch covers `I`, but javac will report an error that the variable may not be assigned.

This patch fixes that - the only tricky part is that if there's an error in the switch (like when the switch is expected to be exhaustive, but is not), the current patch will try to suppress the follow-up "variable may not be assigned" errors. As an example:
```
interface I permits A, B {}

String data;
I i = ...;
switch (i) { //error here, not exhaustive
    case A a -> data = 0;
}
System.err.println(data); //no error here, due to the preceding exhaustiveness error
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281100](https://bugs.openjdk.java.net/browse/JDK-8281100): Spurious "variable might not have been initialized" with sealed class switch

### Reviewers
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7402/head:pull/7402` \
`$ git checkout pull/7402`

Update a local copy of the PR: \
`$ git checkout pull/7402` \
`$ git pull https://git.openjdk.java.net/jdk pull/7402/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7402`

View PR using the GUI difftool: \
`$ git pr show -t 7402`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7402.diff">https://git.openjdk.java.net/jdk/pull/7402.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks sensible

**Review by vicente-romero-oracle — COMMENTED** [review]
this test case is failing for me, I was expecting it to compile:

```
sealed interface I permits A, B {}

final class A implements I {}

final class B implements I {}

class Test {
    void m(I i) {
        int data;
        switch (i) {
            case A a -> data = 0;
            case B b -> data = 0;
        };
        System.err.println(data);
    }
}
```

**Comment by lahodaj** [comment]
> this test case is failing for me, I was expecting it to compile:
> 
> ```
> sealed interface I permits A, B {}
> 
> final class A implements I {}
> 
> final class B implements I {}
> 
> class Test {
>     void m(I i) {
>         int data;
>         switch (i) {
>             case A a -> data = 0;
>             case B b -> data = 0;
>         };
>         System.err.println(data);
>     }
> }
> ```

Hm, seems to work for me with this patch?
```
~/src/jdk/jdk (JDK-8281100) $ cat /tmp/Test.java 
sealed interface I permits A, B {}

final class A implements I {}

final class B implements I {}

class Test {
    void m(I i) {
        int data;
        switch (i) {
            case A a -> data = 0;
            case B b -> data = 0;
        };
        System.err.println(data);
    }
}
~/src/jdk/jdk (JDK-8281100) $ ./build/linux-x86_64-server-release/jdk/bin/javac --enable-preview -source 19 /tmp/Test.java 
Note: /tmp/Test.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.
~/src/jdk/jdk (JDK-8281100) $ git push origin JDK-8281100
Everything up-to-date
```

**Comment by vicente-romero-oracle** [comment]
yep I also can't reproduce the issue, redid everything, I did yesterday, probably some build issue, not sure because I cleaned and rebuilt several times yesterday to be sure, anyway, yes it is working fine for me too now, sorry for the noise,


> > this test case is failing for me, I was expecting it to compile:
> > ```
> > sealed interface I permits A, B {}
> > 
> > final class A implements I {}
> > 
> > final class B implements I {}
> > 
> > class Test {
> >     void m(I i) {
> >         int data;
> >         switch (i) {
> >             case A a -> data = 0;
> >             case B b -> data = 0;
> >         };
> >         System.err.println(data);
> >     }
> > }
> > ```
> 
> Hm, seems to work for me with this patch?
> 
> ```
> ~/src/jdk/jdk (JDK-8281100) $ cat /tmp/Test.java 
> sealed interface I permits A, B {}
> 
> final class A implements I {}
> 
> final class B implements I {}
> 
> class Test {
>     void m(I i) {
>         int data;
>         switch (i) {
>             case A a -> data = 0;
>             case B b -> data = 0;
>         };
>         System.err.println(data);
>     }
> }
> ~/src/jdk/jdk (JDK-8281100) $ ./build/linux-x86_64-server-release/jdk/bin/javac --enable-preview -source 19 /tmp/Test.java 
> Note: /tmp/Test.java uses preview features of Java SE 19.
> Note: Recompile with -Xlint:preview for details.
> ~/src/jdk/jdk (JDK-8281100) $ git push origin JDK-8281100
> Everything up-to-date
> ```

**Pull request closed without merging**
