### PR TITLE
8266610: Method RandomAccessFile#length() returns 0 for block devices on linux.

### PR DESCRIPTION
**Pull request by vyommani**
RandomAccessFile.length() method for block device return always 0

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266610](https://bugs.openjdk.java.net/browse/JDK-8266610): Method RandomAccessFile#length() returns 0 for block devices on linux.

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3914/head:pull/3914` \
`$ git checkout pull/3914`

Update a local copy of the PR: \
`$ git checkout pull/3914` \
`$ git pull https://git.openjdk.java.net/jdk pull/3914/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3914`

View PR using the GUI difftool: \
`$ git pr show -t 3914`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3914.diff">https://git.openjdk.java.net/jdk/pull/3914.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
I think this look okay, and consistent with the file dispatcher implementation.

**Comment by huishi-hs** [comment]
Could required os = linux added for test/jdk/java/nio/channels/FileChannel/BlockDeviceSize.java? As it is decribed only run as linux.

**Comment by vyommani** [comment]
> Could required os = linux added for test/jdk/java/nio/channels/FileChannel/BlockDeviceSize.java? As it is decribed only run as linux.

Sure, this is separate issue(https://bugs.openjdk.java.net/browse/JDK-8150539). We will fix it separately.

**Comment by AlanBateman** [comment]
> Could required os = linux added for test/jdk/java/nio/channels/FileChannel/BlockDeviceSize.java? As it is decribed only run as linux.

Yes, good idea. Also maybe we can see about changing it to avoid the dependency on /dev/sda1.

**Comment by vyommani** [comment]
> Could required os = linux added for test/jdk/java/nio/channels/FileChannel/BlockDeviceSize.java? As it is decribed only run as linux.

Sure, this is separate issue(https://bugs.openjdk.java.net/browse/JDK-8150539). We will fix it separately.

**Comment by dholmes-ora** [comment]
@vyommani this has broken the build on macos as you are including a linux specific header file in non-linux code! Please backout or fix ASAP. Thanks.

**Pull request closed without merging**
