### PR TITLE
8338539: New Object to ObjectMonitor mapping: riscv64 implementation

### PR DESCRIPTION
**Pull request by zifeihan**
The riscv64 implementation of JDK-8315884 New Object to ObjectMonitor mapping

### Testing:
- [x] tier1-3 & hotspot:tier4 tests (release)
- [x] test/hotspot/jtreg/runtime/Monitor/UseObjectMonitorTableTest.java (release & fastdebug)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338539](https://bugs.openjdk.org/browse/JDK-8338539): New Object to ObjectMonitor mapping: riscv64 implementation (**Sub-task** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20621/head:pull/20621` \
`$ git checkout pull/20621`

Update a local copy of the PR: \
`$ git checkout pull/20621` \
`$ git pull https://git.openjdk.org/jdk.git pull/20621/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20621`

View PR using the GUI difftool: \
`$ git pr show -t 20621`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20621.diff">https://git.openjdk.org/jdk/pull/20621.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20621#issuecomment-2295271525)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good to me. Thanks!

**Comment by robehn** [comment]
Hey, not funcational review yet.

But this code have been patched to many times "let me just add this".
We shadow tmp1 register with tmp1_mark, then we shadow tmp1_mark with tmp1_tagged_monitor.

If we create two methods, one for "{ // Lightweight locking" and one for "{ // Handle inflated monitor." this code will be so much better.

If you are not up for the task I can do it.

**Comment by zifeihan** [comment]
> Hey, not functional review yet.
> 
> But this code have been patched to many times "let me just add this". We shadow tmp1 register with tmp1_mark, then we shadow tmp1 with tmp1_monitor. And similar for other tmp registers.
> 
> If we create two methods, one for "{ // Lightweight locking" and one for "{ // Handle inflated monitor." this code will be so much better.
> 
> If you are not up for the task I can do it.
> 
> (your patch actually slightly improves this, so I'm not saying it's your doing)

Hi, Thanks for having a look! Your suggestion makes sense to me. But I feel that it's better to go with another PR. Will leave it for you :-)

**Comment by robehn** [comment]
> Hi, Thanks for having a look! Your suggestion makes sense to me. But I feel that it's better to go with another PR. Will leave it for you :-)

Yes, thanks! Looks good!

**Review by Hamlin-Li — APPROVED** [review]

**Comment by zifeihan** [comment]
Thanks all for the review.
/integrate

**Comment by RealFYang** [comment]
> > Hey, not functional review yet.
> > But this code have been patched to many times "let me just add this". We shadow tmp1 register with tmp1_mark, then we shadow tmp1 with tmp1_monitor. And similar for other tmp registers.
> > If we create two methods, one for "{ // Lightweight locking" and one for "{ // Handle inflated monitor." this code will be so much better.
> > If you are not up for the task I can do it.
> > (your patch actually slightly improves this, so I'm not saying it's your doing)
> 
> Hi, Thanks for having a look! Your suggestion makes sense to me. But I feel that it's better to go with another PR. Will leave it for you :-)

Hi, Please keep the current shape for a while as I am trying to sync regularly with loom fiber changes which touches this part.

**Comment by robehn** [comment]
> Hi, Please keep the current shape for a while as I am trying to sync regularly with latest loom fiber changes which touches this part.

Okey, I have a big patch :) It turns out we can reuse same code in C1 and C2 with some minor changes.
I'll hold off.

**Pull request closed without merging**
