### PR TITLE
8340269: [s390x] TestLargeStub.java failure after 8338123

### PR DESCRIPTION
**Pull request by offamitkumar**
Fixes the test case; Ran tier1 with fastdebug-vm, didn't see any regression.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340269](https://bugs.openjdk.org/browse/JDK-8340269): [s390x] TestLargeStub.java failure after 8338123 (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21033/head:pull/21033` \
`$ git checkout pull/21033`

Update a local copy of the PR: \
`$ git checkout pull/21033` \
`$ git pull https://git.openjdk.org/jdk.git pull/21033/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21033`

View PR using the GUI difftool: \
`$ git pr show -t 21033`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21033.diff">https://git.openjdk.org/jdk/pull/21033.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21033#issuecomment-2354914181)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
`pd_store_reg` and `pd_load_reg` use `reg2mem_opt` etc. I don't know how large they can get. It's correct if they fit into 16 Bytes. Did you measure the size of a trivial downcall stub? Do you still have some space left?

**Review by RealLucy — APPROVED** [review]
Looks good.

**Comment by offamitkumar** [comment]
@TheRealMDoerr I have updated the code size & args size required as per your suggestion. Please have a look again;

Thank you.

**Comment by offamitkumar** [comment]
Also I did run the test again and I am not seeing any issues.

**Review by RealLucy — APPROVED** [review]
Looks good. 
Should such a sizing issue reoccur, then please increment the values to 512 and 16.

And please wait for the tests to complete successfully!

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by offamitkumar** [comment]
>Should such a sizing issue reoccur, then please increment the values to 512 and 16.

Sure Lutz. Thank you both for the review & suggestions; 

/integrate

**Pull request closed without merging**
