### PR TITLE
8258447: Move make/hotspot/hotspot.script to make/scripts

### PR DESCRIPTION
**Pull request by magicus**
The hotspot launcher script is misplaced among the hotspot make files. It should move to make/scripts (and get a proper extension).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258447](https://bugs.openjdk.java.net/browse/JDK-8258447): Move make/hotspot/hotspot.script to make/scripts

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1791/head:pull/1791`
`$ git checkout pull/1791`

### CODE REVIEW

**Comment by magicus** [comment]
Can someone from hotspot please confirm if this script is still needed/used?

**Review by dcubed-ojdk — APPROVED** [review]
The rename and makefile changes look good.
I've used the script on occasion, but not recently (not in the last 6 months).

**Pull request closed without merging**
