### PR TITLE
8319690: [AArch64] C2 compilation hits offset_ok_for_immed: assert "c2 compiler bug"

### PR DESCRIPTION
**Pull request by eme64**
Taking this over from @fg1417, she seems to be "on leave" according to her GitHub account.

I'm taking her regression test (she improved the reproducer that I had originally reported the bug with).

It is ok to just remove the assert, because the address is "sanitized" after the assert, i.e. we use a `lea` instruction to compute the address.

But I'm simply removing the assert, as suggested in the comments of the previous [PR](https://github.com/openjdk/jdk/pull/16991#issuecomment-1962307596).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319690](https://bugs.openjdk.org/browse/JDK-8319690): [AArch64] C2 compilation hits offset_ok_for_immed: assert "c2 compiler bug" (**Bug** - P4)

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)

### Contributors
 * Fei Gao `<fgao@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18103/head:pull/18103` \
`$ git checkout pull/18103`

Update a local copy of the PR: \
`$ git checkout pull/18103` \
`$ git pull https://git.openjdk.org/jdk.git pull/18103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18103`

View PR using the GUI difftool: \
`$ git pr show -t 18103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18103.diff">https://git.openjdk.org/jdk/pull/18103.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18103#issuecomment-1976410665)

### CODE REVIEW

**Comment by eme64** [comment]
/contributor add fg1417

@fg1417 wrote a first PR, but gave it up. I'm taking over the test, but not her fix.
(I had found the original reproducer, but she improved the test further, so I want to give her credit for that)

**Review by theRealAph — APPROVED** [review]
Yes, that's right. I wrote that assertion for my own information, this isn't really a bug. I might rework this whole area of the compiler in the future, but there's no urgency. Thanks.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by lgxbslgx — APPROVED** [review]
Looks good.

**Comment by eme64** [comment]
Thanks @vnkozlov @theRealAph @lgxbslgx for the reviews!
Thanks @fg1417 for the original PR and patching up the test.

/integrate

**Pull request closed without merging**
