### PR TITLE
8325042: remove unused JVMDITools test files

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this trivial change to remove some unused files.

Testing: mach5 tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325042](https://bugs.openjdk.org/browse/JDK-8325042): Remove unused JVMDITools test files (**Sub-task** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17650/head:pull/17650` \
`$ git checkout pull/17650`

Update a local copy of the PR: \
`$ git checkout pull/17650` \
`$ git pull https://git.openjdk.org/jdk.git pull/17650/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17650`

View PR using the GUI difftool: \
`$ git pr show -t 17650`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17650.diff">https://git.openjdk.org/jdk/pull/17650.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17650#issuecomment-1919521324)

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Thank you for removing these.  This is a trivial change.

**Comment by kimbarrett** [comment]
Thanks for review, @coleenp

**Pull request closed without merging**
