### PR TITLE
8314753: Remove support for @beaninfo, @ToDo, @since.unbundled, and @Note

### PR DESCRIPTION
**Pull request by pavelrappo**
Please review this trivial PR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8314753](https://bugs.openjdk.org/browse/JDK-8314753): Remove support for @beaninfo, @ToDo, @since.unbundled, and @Note (**Bug** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15385/head:pull/15385` \
`$ git checkout pull/15385`

Update a local copy of the PR: \
`$ git checkout pull/15385` \
`$ git pull https://git.openjdk.org/jdk.git pull/15385/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15385`

View PR using the GUI difftool: \
`$ git pr show -t 15385`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15385.diff">https://git.openjdk.org/jdk/pull/15385.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15385#issuecomment-1687989899)

### CODE REVIEW

**Comment by pavelrappo** [comment]
/cc client, jmx

CC'ing client-libs-dev because `@beaninfo` and `@Note` and jmx-dev because of `@since.unbundled`, which might've been used for JMX before 2007.

**Comment by pavelrappo** [comment]
/cc core-libs

CC'ing core-libs-dev whose members might also have some recollection on tags in question.

**Comment by pavelrappo** [comment]
/cc client, jmx

CC'ing client-libs-dev because @beaninfo and @Note and jmx-dev because of @since.unbundled, which might've been used for JMX before 2007.

**Review by RogerRiggs — APPROVED** [review]
Looks trivial only after reviewing the issue and knowing the background.
The PR description could be a bit more complete and save a bunch of clicking around.

**Pull request closed without merging**
