### PR TITLE
JDK-8302846: IGV: Zoom stuck when zooming out on large graphs

### PR DESCRIPTION
**Pull request by tobiasholenstein**
# Problem 
In the IdealGraphVisualizer (IGV) the user can zoom in and out using either the mouse-wheel or by entering/selecting a value in the zoom combo-box. The zoom combo-box is implemented in `ZoomLevelAction.java`: 
- `ZoomLevelAction` has a listener on `scene.getZoomChangedEvent()` which calls `changed(..)` each time the zoom level of the `diagramScene` changes, e.g. when the user zooms in/out with the mouse-wheel. 
- `actionPerformed(..)` is called when the user enters/selects a zoom level in the combo-box, in which case it calls `setZoomLevel(..)` -> `diagramScene.setZoomPercentage(zoomLevel)` to update the zooming of the scene. 
- `changed(..)` calls `setSelectedItem(..)` which updates the content of the combo-box and triggers a also a call to `actionPerformed(..)`. Unfortunately, in this case we should not call `diagramScene.setZoomPercentage(zoomLevel)` because the `diagramScene` is updating the `ZoomLevelAction` and not vice versa. The problem only reveals for small zooming level because `ZoomLevelAction` uses an integer for the zooming level (1-100%) while the `diagramScene` uses a float (1.0f is 100%). In the example where the bug occurs, mouse wheel zooming changed zoom level in `diagramScene` from 0.01 to 0.012 -  then `diagramScene` updates the `ZoomLevelAction` which rounds 1.2% to 1% :  and now the BUG: `ZoomLevelAction ` sets `diagramScene` zooming again to 0.01. The zooming is stuck at 0.01

# Solution
When `diagramScene` updates the `ZoomLevelAction`, `actionPerformed(..)` should not call `diagramScene.setZoomPercentage(zoomLevel)`. So we introduce a ` boolean updateZoomInScene` that is set to `false` when a change of zoom in `diagramScene ` triggered the  `actionPerformed(..)`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302846](https://bugs.openjdk.org/browse/JDK-8302846): IGV: Zoom stuck when zooming out on large graphs

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**) ⚠️ Review applies to [9f97bf39](https://git.openjdk.org/jdk/pull/12652/files/9f97bf39462a5b7cb2cfea89f1dd9b7475cde973)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [9f97bf39](https://git.openjdk.org/jdk/pull/12652/files/9f97bf39462a5b7cb2cfea89f1dd9b7475cde973)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12652/head:pull/12652` \
`$ git checkout pull/12652`

Update a local copy of the PR: \
`$ git checkout pull/12652` \
`$ git pull https://git.openjdk.org/jdk pull/12652/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12652`

View PR using the GUI difftool: \
`$ git pr show -t 12652`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12652.diff">https://git.openjdk.org/jdk/pull/12652.diff</a>

</details>

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Thanks for fixing this, Toby! Please update the copyright header.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by tobiasholenstein** [comment]
thanks @robcasloz and 

> Thanks for fixing this, Toby! Please update the copyright header.

done

**Comment by tobiasholenstein** [comment]
Thanks @robcasloz and @TobiHartmann for the reviews!

/integrate

**Pull request closed without merging**
