### PR TITLE
8319955: Improve dependencies removal during class unloading

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this performance improvement to dependency removal during class unloading: instead of moving the dependencies item by item via a `cmpxchg`, batch this operation.

This makes that part of class unloading ~7x faster in my measurements (class unloading stress test, loading/unloading 6k classes).

Testing: tier1-7

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319955](https://bugs.openjdk.org/browse/JDK-8319955): Improve dependencies removal during class unloading (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16639/head:pull/16639` \
`$ git checkout pull/16639`

Update a local copy of the PR: \
`$ git checkout pull/16639` \
`$ git pull https://git.openjdk.org/jdk.git pull/16639/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16639`

View PR using the GUI difftool: \
`$ git pr show -t 16639`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16639.diff">https://git.openjdk.org/jdk/pull/16639.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16639#issuecomment-1809689540)

### CODE REVIEW

**Comment by dholmes-ora** [comment]
So this batches the operation by moving the batch to the purge list, but it doesn't actually release anything. Who/what will process the purge list and when? The implications of this change in terms of concurrent activities is far from clear.

**Comment by tschatzl** [comment]
> So this batches the operation by moving the batch to the purge list, but it doesn't actually release anything. Who/what will process the purge list and when? The implications of this change in terms of concurrent activities is far from clear.

There is no observable difference (apart from being faster) here - the move of the dependencies from the (single) Klass to the purge list is and has been under the `ClassLoaderData_lock` anyway, locking out "everything" already.

The current basic structure is like:

```
(indentation means call level)
lock ClassLoaderDataGraph_lock
CLGD::do_unloading()
  CLD::unload
  foreach (Klass in CLD) {
    remove_all_dependents()
  }
unlock ClassLoaderDataGraph_lock
```

The only thing that change is the performance of `remove_all_dependents`, from

```
void DependencyContext::remove_all_dependents() {
  for (all dependents x) {
    loadload barrier
    cmpxchg x into purge list
  }
}
```

to

```
void DependencyContext::remove_all_dependents() {
  find last pointer of dependents list of the dead(!) Klass, i.e. verified unreachable by the mutator
  cmpxchg first/last into purge list
}
```

Literally no change in locking or the scope of the `ClassLoaderDataGraph_lock`. Everything else is already locked out (for a really long time in that stress test).

The only change is the amount of atomic operations.

Actually, the time to hold the `CLDG_lock` is *much shorter* now as indicated by the numbers in the CR.

The purge list is processed as before at some point afterwards. No change here.

Unfortunately the code still needs to traverse the linked list (and there are really many linked lists here and in nmethod management :( ) which are not very amenable to performance improvements (e.g. parallelization).

It is a non-goal for this CR to change data structures.

**Comment by tschatzl** [comment]
Sorry forgot to answer this:

> Who/what will process the purge list and when?

There is a call to `ClassLoaderDataGraph::purge` which does that, executed later dependent on garbage collector. This change does not change the amount of elements (apart from the order of the elements) too, so no difference here.

(During class unloading `DependencyContext::delete_on_release()` is and has always been false, and the existing code always moves entries to the purge list - there is an appropriate assert in the new code).

**Comment by tschatzl** [comment]
Concurrent additions to the purge list (during (concurrent) class unloading) should be fine due to the `cmpxchg` used, i.e. callers of `DependencyContext::release()` while the first part of class unloading (i.e. CLD unlinking) is in progress (i.e. `!delete_on_release()`).

**Comment by dholmes-ora** [comment]
> (During class unloading DependencyContext::delete_on_release() is and has always been false, and the existing code always moves entries to the purge list - there is an appropriate assert in the new code).

Thanks I can see that now. So all this does is move a chunk of elements to the purge-list instead of doing it one at a time. Makes me wonder why this wasn't noticed sooner. :)

**Review by dholmes-ora — APPROVED** [review]
Changes look good. Thanks

**Comment by tschatzl** [comment]
Thanks @dholmes-ora @fisk for your reviews
/integrate

**Pull request closed without merging**
