### PR TITLE
8234315: GTK LAF does not gray out disabled JMenu

### PR DESCRIPTION
**Pull request by kumarabhi006**
Disabled JMenu foreground color was not grayed out in GTK LAF for version 3. The issue didn't occur in GTK-2. 
After analysis it has been found that the JMenu widget type was changed to JMenuBar and the color value returned for the foreground color in disabled state was close to black color (RGB 0,0,0) for menubar which is not differentiable from enabled state foreground color.

As a fix for this problem, if the menubar is in disabled state then the widget is changed to JMenu and color value returned for disabled menu is gray color.

An automated test case has been added and checked in CI, link is added in JBS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8234315](https://bugs.openjdk.org/browse/JDK-8234315): GTK LAF does not gray out disabled JMenu

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)
 * [Prasanta Sadhukhan](https://openjdk.org/census#psadhukhan) (@prsadhuk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10176/head:pull/10176` \
`$ git checkout pull/10176`

Update a local copy of the PR: \
`$ git checkout pull/10176` \
`$ git pull https://git.openjdk.org/jdk pull/10176/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10176`

View PR using the GUI difftool: \
`$ git pr show -t 10176`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10176.diff">https://git.openjdk.org/jdk/pull/10176.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Does the new color looks the same as in the native applications?

**Comment by kumarabhi006** [comment]
> Does the new color looks the same as in the native applications?

I think it is same as in native application. Attached a screenshot of test application and text editor (gedit) in ubuntu. 
DisableMenuColor

**Review by mrserb — APPROVED** [review]
Looks fine, please double how it will work if the dark theme is set.

**Comment by kumarabhi006** [comment]
> Looks fine, please double how it will work if the dark theme is set.

In case of dark theme set, foreground color is grayed out. 
Enabled_Menu_Dark_Theme

Disabled_Menu_Dark_Theme

**Review by prsadhuk — APPROVED** [review]

**Pull request closed without merging**
