### PR TITLE
JDK-8266795: Remove dead code LowMemoryDetectorDisabler

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is trivial change to remove dead code in low memory detector.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266795](https://bugs.openjdk.java.net/browse/JDK-8266795): Remove dead code LowMemoryDetectorDisabler

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3964/head:pull/3964` \
`$ git checkout pull/3964`

Update a local copy of the PR: \
`$ git checkout pull/3964` \
`$ git pull https://git.openjdk.java.net/jdk pull/3964/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3964`

View PR using the GUI difftool: \
`$ git pr show -t 3964`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3964.diff">https://git.openjdk.java.net/jdk/pull/3964.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Hi Hamlin,

What you have seems fine, but unless I missed something it seems the whole notion of being enabled/disabled is unused:

 // > 0 if temporary disabed
  static volatile jint _disabled_count;
  static bool temporary_disabled() { return _disabled_count > 0; }
  static void disable() { Atomic::inc(&_disabled_count); }
  static void enable() { Atomic::dec(&_disabled_count); }

Thanks,
David

**Comment by Hamlin-Li** [comment]
Seems the build failure is not related to this change.
'''
2021-05-11T13:21:17.0861973Z Err:27 https://packages.microsoft.com/repos/azure-cli focal Release
2021-05-11T13:21:17.0863392Z   Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.82.67.141 443]
2021-05-11T13:21:50.1858001Z Err:28 https://packages.microsoft.com/ubuntu/20.04/prod focal Release
2021-05-11T13:21:50.1859811Z   Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.82.67.141 443]
2021-05-11T13:21:56.7524970Z Reading package lists...
2021-05-11T13:21:56.7679502Z E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' no longer has a Release file.
2021-05-11T13:21:56.7681552Z E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' no longer has a Release file.
2021-05-11T13:21:56.7697849Z ##[error]Process completed with exit code 100.
'''

**Review by dholmes-ora — APPROVED** [review]
Looks good!

Thanks,
David

**Comment by Hamlin-Li** [comment]
Thanks David for your detailed review!

/integrate

**Pull request closed without merging**
