### PR TITLE
8281400: Remove unused wcslen() function

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small change to remove the unused wcslen() function.  This change was tested by running Mach5 tiers 1-2 on Linux, Mac OS, and Windows.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281400](https://bugs.openjdk.java.net/browse/JDK-8281400): Remove unused wcslen() function

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 820152687853e8179f6f22b2690abb5db318cd43
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7374/head:pull/7374` \
`$ git checkout pull/7374`

Update a local copy of the PR: \
`$ git checkout pull/7374` \
`$ git pull https://git.openjdk.java.net/jdk pull/7374/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7374`

View PR using the GUI difftool: \
`$ git pr show -t 7374`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7374.diff">https://git.openjdk.java.net/jdk/pull/7374.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
"grep" concurs that this function is only used in os_windows.cpp.
Thumbs up. This is a trivial fix.

Not your problem, but the XLC header has the same issue:
src/hotspot/share/utilities/globalDefinitions_xlc.hpp:inline int wcslen(const jchar* x) { return wcslen((const wchar_t*)x); }

**Comment by dholmes-ora** [comment]
Please fix both files and update the JBS issue title etc.

Thanks.

**Review by coleenp — APPROVED** [review]
Looks good + trivial.

**Review by lfoltan — APPROVED** [review]
Looks good.
Lois

**Comment by hseigel** [comment]
Thanks Dan, Coleen, and Lois for the reviews.

/integrate

**Pull request closed without merging**
