### PR TITLE
8301153: RISC-V: pipeline class for several instructions is not set correctly

### PR DESCRIPTION
**Pull request by feilongjiang**
Witness that some c2 instructions use the inappropriate ins_pipe, e.g.:

```
instruct MoveI2F_stack_reg(fRegF dst, stackSlotI src) %{

  match(Set dst (MoveI2F src));

  effect(DEF dst, USE src);

  ins_cost(LOAD_COST);

  format %{ "flw $dst, $src\t#@MoveI2F_stack_reg" %}

  ins_encode %{
    __ flw(as_FloatRegister($dst$$reg), Address(sp, $src$$disp));
  %}

  ins_pipe(pipe_class_memory);

%}
```

We can use the more accurate pipe_class `fp_load_mem_s` instead.

This PR also fixes the side effect of the flags register for two instructions, we should use/kill a flags register.

Testing:

- [x] Tier1~3 on Unmatched board with release build

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301153](https://bugs.openjdk.org/browse/JDK-8301153): RISC-V: pipeline class for several instructions is not set correctly

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Yadong Wang](https://openjdk.org/census#yadongwang) (@yadongw - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12219/head:pull/12219` \
`$ git checkout pull/12219`

Update a local copy of the PR: \
`$ git checkout pull/12219` \
`$ git pull https://git.openjdk.org/jdk pull/12219/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12219`

View PR using the GUI difftool: \
`$ git pr show -t 12219`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12219.diff">https://git.openjdk.org/jdk/pull/12219.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
LGTM.

**Review by yadongw — APPROVED** [review]
lgtm

**Comment by feilongjiang** [comment]
@RealFYang @yadongw  -- Thanks!
/integrate

**Pull request closed without merging**
