### PR TITLE
8286262: Windows: Cleanup deprecation warning suppression

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this cleanup of deprecation warning suppression when building
for Windows.

This change consists of several parts.

(1) Remove the global deprecation warning suppression when building HotSpot
for Windows.

(2) Add macro definitions requesting suppression of selected sets of
deprecation warnings when building HotSpot for Windows.

(3) Remove unnecessary forwarding macros for various POSIX functions in
globalDefinitions_visCPP.hpp.  These were provided to avoid deprecation
warnings (that were previously also being suppressed by the global request).
They are now covered by the new macros provided by change (2) above.

An alternative to item (3) is to not define _CRT_NONSTDC_NO_DEPRECATE (in item
(2)) and either retain the forwarding macros or define os:: wrapper functions
for all of the affected functions.  We might eventually do the latter because
of other reasons for avoiding some of these functions, but the approach being
taken here is simpler.

For documentation of _CRT_NONSTDC_NO_DEPRECATE, see:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996

Similarly for _CRT_SECURE_NO_WARNINGS.

Perhaps similarly for _WINSOCK_DEPRECATED_NO_WARNINGS (though I didn't find
any documentation for the latter).  But it might be better to not supress the
warnings and instead use the alternatives (JDK-8286781).

Testing:
mach5 tier1

/label build
/label hotspot

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286262](https://bugs.openjdk.java.net/browse/JDK-8286262): Windows: Cleanup deprecation warning suppression

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [dd39fb83](https://git.openjdk.java.net/jdk/pull/8718/files/dd39fb83a73ec25fe86f8cf27de5d732a98d55aa)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [dd39fb83](https://git.openjdk.java.net/jdk/pull/8718/files/dd39fb83a73ec25fe86f8cf27de5d732a98d55aa)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8718/head:pull/8718` \
`$ git checkout pull/8718`

Update a local copy of the PR: \
`$ git checkout pull/8718` \
`$ git pull https://git.openjdk.java.net/jdk pull/8718/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8718`

View PR using the GUI difftool: \
`$ git pr show -t 8718`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8718.diff">https://git.openjdk.java.net/jdk/pull/8718.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Sorry Kim I'm having trouble seeing what change corresponds to (1) ??

Also the PR talks only about hotspot, but you're changing the JDK flags as well. ??

**Comment by kimbarrett** [comment]
> Sorry Kim I'm having trouble seeing what change corresponds to (1) ??

The change to CompileJvm.gmk, removing 4996 (deprecation warnings)
from the list of disabled warnings.

> Also the PR talks only about hotspot, but you're changing the JDK flags as well. ??

I forgot to mention that in addition to reformatting the JDK flags a
little bit to be consistent with the JVM flags changes, I also changed
-D_CRT_SECURE_NO_DEPRECATE => -D_CRT_SECURE_NO_WARNINGS. Both are
(still) supported and have the same meaning, but the latter is the more
"modern" (circa VS2005-ish?) spelling.

**Review by dholmes-ora — APPROVED** [review]
All seems quite reasonable.

Thanks,
David

**Comment by kimbarrett** [comment]
Thanks @dholmes-ora and @magicus for reviews.

**Pull request closed without merging**
