### PR TITLE
8263460: DynamicArchiveRelocationTest.java fails in product VM

### PR DESCRIPTION
**Pull request by iklam**
Please review this test bug. 

The handling of -XX:ArchiveRelocationMode=1 is different between fastdebug and product builds:

- fastdebug: (to improve test coverage) -- we always map at the default location, then unmap, and then map again at a random location.
- product: (for faster performance) -- don't attempt to map at the default location. Just map at random location

Therefore, the "unmap" messages are not available in product mode.

I added comments to explain what output is expected, and rearranged the regexp for better matching.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263460](https://bugs.openjdk.java.net/browse/JDK-8263460): DynamicArchiveRelocationTest.java fails in product VM

### Reviewers
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to 27dfc7c593e4e28926a2330e44f5b2e22b89319d
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2947/head:pull/2947`
`$ git checkout pull/2947`

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
LGTM.

**Review by tstuefe — COMMENTED** [review]
The special handling for Windows is not needed anymore?

I have the feeling this could be made simpler in general (not in this fix). E.g. instead of mapping, then unmapping, which causes the execution paths between non-product and product to be quite different, why not just reserve a "rogue" allocation in the middle of the soon-to-map region? Would that not be a more reliable and realistic test?

Cheers, Thomas

**Comment by dcubed-ojdk** [comment]
@ioilam - Any chance that this fix will get integrated before the weekend?
I'm interested in taking the two failures per Tier6 off the board for the weekend.

**Comment by iklam** [comment]
> The special handling for Windows is not needed anymore?

Hi Thomas, thanks for looking into this.

You're correct that the Windows port may work differently. When mapping to the requested address, some of the regions may fail to map due to ASLR, so you are not guaranteed to have two "Unmapping region ..." messages.

Also, this is theoretically not limited to Windows, either. Some other OS ports may also make the requested address unavailable due to ASLR.

Therefore, I decided to get rid of the pattern matching altogether. We know that the native code will try its best to exercise the mapping and unmapping code, so as long as the program exits normally, we know all has gone well :-)


> I have the feeling this could be made simpler in general (not in this fix). E.g. instead of mapping, then unmapping, which causes the execution paths between non-product and product to be quite different, why not just reserve a "rogue" allocation in the middle of the soon-to-map region? Would that not be a more reliable and realistic test?
> 
> Cheers, Thomas

Such a "rouge" region would need to be allocated inside the VM code, since we can't easily do it from the "driver" process of the test, Also, this will cause at least one of the regions to fail to map. As a result, we cannot test the case where all the regions are mapped, but then we have to unmap them due to other reasons.

Admittedly, a different way to test this is to corrupt the CRC of one of the regions. This should be done in appcds/SharedArchiveConsistency.java but we exit the VM and don't exercise the code for unmapping. I have created [JDK-8263538](https://bugs.openjdk.java.net/browse/JDK-8263538) (SharedArchiveConsistency.java should test -Xshare:auto as well)

**Comment by iklam** [comment]
> @ioilam - Any chance that this fix will get integrated before the weekend?
> I'm interested in taking the two failures per Tier6 off the board for the weekend.

Yes, if I can get enough reviews for my latest version :-)

**Review by dcubed-ojdk — APPROVED** [review]
It looks to me like you've done this:

> Therefore, I decided to get rid of the pattern matching altogether

so thumbs up!
I presume you've tested the latest version with 'release' bits.

**Comment by iklam** [comment]
> It looks to me like you've done this:
> 
> > Therefore, I decided to get rid of the pattern matching altogether
> 
> so thumbs up!
> I presume you've tested the latest version with 'release' bits.

Yes, I tested the latest version with both debug and release bits.

**Pull request closed without merging**
