### PR TITLE
8262060: compiler/whitebox/BlockingCompilation.java timed out

### PR DESCRIPTION
**Pull request by lepestock**
Please review this small fix for a test.

Test fails sometimes when run with UsageTracker enabled. For some reason, a loading of ThreadLocalRandom can happen during the test run, and this invalidates Random.nextInt method (because it's not the only implementation now).

Fixed by pre-loading ThreadLocalRandom. Tested by multiple runs with UsageTracker enabled - approx. 1 out of 20-30 test runs fails without the fix and no failures spotted with the fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262060](https://bugs.openjdk.java.net/browse/JDK-8262060): compiler/whitebox/BlockingCompilation.java timed out

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3224/head:pull/3224` \
`$ git checkout pull/3224`

Update a local copy of the PR: \
`$ git checkout pull/3224` \
`$ git pull https://git.openjdk.java.net/jdk pull/3224/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3224`

View PR using the GUI difftool: \
`$ git pr show -t 3224`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3224.diff">https://git.openjdk.java.net/jdk/pull/3224.diff</a>

</details>

### CODE REVIEW

**Review by iignatev — CHANGES_REQUESTED** [review]
Hi Evgeny,

there is no reason for this test to depend on `Random` and hence be dependent on the hierarchy of its subclasses (which I assume is the reason the test fails). so I'd rather fix it by removing the dependency on `Random`, `BlockingCompilation::foo` can return a constant or do some convoluted math/logic computation "locally" if we are afraid that some optimizations can affect the test's behavior.

Cheers,
-- Igor

**Comment by lepestock** [comment]
> Hi Evgeny,
> 
> there is no reason for this test to depend on `Random` and hence be dependent on the hierarchy of its subclasses (which I assume is the reason the test fails). so I'd rather fix it by removing the dependency on `Random`, `BlockingCompilation::foo` can return a constant or do some convoluted math/logic computation "locally" if we are afraid that some optimizations can affect the test's behavior.
> 
> Cheers,
> -- Igor

Hi Igor,

Valid point. I've removed the Random class' dependency now.

// Evgeny.

**Review by iignatev — APPROVED** [review]
LGTM

**Pull request closed without merging**
