### PR TITLE
8260520: Avoid getting permissions in JarFileFactory when no SecurityManager installed

### PR DESCRIPTION
**Pull request by cl4es**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260520](https://bugs.openjdk.java.net/browse/JDK-8260520): Avoid getting permissions in JarFileFactory when no SecurityManager installed

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to 09e4ff9e2f93283498e8ee502f6549986a42f5e5
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Michael McMahon](https://openjdk.java.net/census#michaelm) (@Michael-Mc-Mahon - **Reviewer**) ⚠️ Review applies to 09e4ff9e2f93283498e8ee502f6549986a42f5e5
 * [Sean Mullan](https://openjdk.java.net/census#mullan) (@seanjmullan - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2263/head:pull/2263`
`$ git checkout pull/2263`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Should be okay as the side effect of getPermission is not observable. Make sure to run all the tests before integrating.

**Review by dfuch — APPROVED** [review]
Looks reasonable to me. Make sure to run jdk-tier2 (or jdk_core) just in case :-)

**Comment by cl4es** [comment]
@AlanBateman @dfuch thanks for reviewing. Waiting for a tier1+2 test run before integration.

**Review by Michael-Mc-Mahon — APPROVED** [review]

**Comment by seanjmullan** [comment]
Will you make the same change to `src/java.base/windows/classes/sun/net/www/protocol/jar/JarFileFactory.java`?

**Comment by cl4es** [comment]
> Will you make the same change to `src/java.base/windows/classes/sun/net/www/protocol/jar/JarFileFactory.java`?

Good catch. Let's keep things consistent. :-)

**Review by dfuch — APPROVED** [review]
Windows changes LGTM too.

**Review by seanjmullan — APPROVED** [review]

**Comment by cl4es** [comment]
@seanjmullan @dfuch @Michael-Mc-Mahon @AlanBateman - thanks for reviewing!

/integrate

**Pull request closed without merging**
