### PR TITLE
8259849: Shenandoah: Rename store-val to IU-barrier

### PR DESCRIPTION
**Pull request by rkennke**
We named the IU barriers StoreValEnqueueBarrier and various similar variations of this. Instead of naming it after how it's implemented, we should name it after its purpose: support IU-marking. It also looks confusing to have enqueue_barrier() and similar stuff, where no barrier is actually enqueued.

The renaming was 100% mechanical.

Testing:
 - [x] hotspot_gc_shenandoah (x86_64, x86_32, aarch64)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259849](https://bugs.openjdk.java.net/browse/JDK-8259849): Shenandoah: Rename store-val to IU-barrier

### Reviewers
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**) ⚠️ Review applies to 2d2b0130f4f0b12b95d35cff4c3815acb7e14399
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 3804e64ed98f3190911c0bf6bde868a2dd718e21

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2104/head:pull/2104`
`$ git checkout pull/2104`

### CODE REVIEW

**Review by zhengyu123 — APPROVED** [review]
Some file's copyright year need to be updated. Otherwise, looks good.

**Review by shipilev — APPROVED** [review]
This makes sense.

**Comment by shipilev** [comment]
...except that GHA report these two tests have failed:
gc/shenandoah/options/TestWrongBarrierDisable.java 
gc/shenandoah/options/TestWrongBarrierEnable.java

**Comment by rkennke** [comment]
> ...except that GHA report these two tests have failed:
> gc/shenandoah/options/TestWrongBarrierDisable.java
> gc/shenandoah/options/TestWrongBarrierEnable.java

Right. Those should be fixed now. Only remaining GHA failure is Windows:

configure: error: Could not find a C compiler. 

Do you know what's up there?

**Comment by shipilev** [comment]
> Right. Those should be fixed now. Only remaining GHA failure is Windows:
> 
> configure: error: Could not find a C compiler.
> Do you know what's up there?

Known issue: https://bugs.openjdk.java.net/browse/JDK-8259679

**Pull request closed without merging**
