### PR TITLE
8311530: Deprecate jdk.jsobject module for removal

### PR DESCRIPTION
**Pull request by kevinrushforth**
Deprecate the `jdk.jsobject` module for removal from the JDK, and ship it with JavaFX instead.

See [JDK-8337280](https://bugs.openjdk.org/browse/JDK-8337280) / PR openjdk/jfx#1529 for the JavaFX PR that will include the module with JavaFX. That PR describes the needed test scenarios.

This PR does two things:

1. Deprecates the `jdk.jsobject` module for removal; the javadoc indicates that the module will be delivered with JavaFX
2. Makes `jdk.jsobject` an upgradeable module, which will facilitate the transition by allowing the version of the module shipped with JavaFX to be used in favor of the deprecated module in the JDK itself.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8338250](https://bugs.openjdk.org/browse/JDK-8338250) to be approved
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8311530](https://bugs.openjdk.org/browse/JDK-8311530): Deprecate jdk.jsobject module for removal (**Bug** - P4)
 * [JDK-8338250](https://bugs.openjdk.org/browse/JDK-8338250): Deprecate jdk.jsobject module for removal (**CSR**)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20555/head:pull/20555` \
`$ git checkout pull/20555`

Update a local copy of the PR: \
`$ git checkout pull/20555` \
`$ git pull https://git.openjdk.org/jdk.git pull/20555/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20555`

View PR using the GUI difftool: \
`$ git pr show -t 20555`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20555.diff">https://git.openjdk.org/jdk/pull/20555.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20555#issuecomment-2332644193)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The GHA run shows a spurious failure in macOS (a network timeout cloning the repo). I'll rerun it with no changes to my branch.

**Review by RogerRiggs — APPROVED** [review]
Looks good. I'll review the CSR when its ready.

**Review by AlanBateman — APPROVED** [review]
The changes to make jdk.jsobject an upgradeable module looks right.

I was initially surprised by the wording "will be delivered with JavaFX" but after playing with a few alternatives I concluded that what we have is okay.

**Comment by AlanBateman** [comment]
@kevinrushforth Is the CSR on your list to write?

**Comment by kevinrushforth** [comment]
Yes, this was on hold for a couple weeks; I plan to write the CSR this week.

**Comment by kevinrushforth** [comment]
I've created the CSRs for both the this PR and openjdk/jfx#1529.

**Review by erikj79 — APPROVED** [review]
Build change looks good.

/reviewers 2

**Pull request closed without merging**
