### PR TITLE
8320053: GHA: Cross-compile gtest code

### PR DESCRIPTION
**Pull request by shipilev**
Looking at why GHA did not catch [JDK-8320050](https://bugs.openjdk.org/browse/JDK-8320050), even though it builds hotspot, I realized we do not configure the build with gtest, which means we skip the build checks for gtest VM. It would be useful to cross-compile with all tests enabled, even without running them.

(This would probably make sense to do for JDK native code, but AFAICS it would require defining a few new make targets).

Additional testing:
 - [x] GHA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320053](https://bugs.openjdk.org/browse/JDK-8320053): GHA: Cross-compile gtest code (**Enhancement** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16652/head:pull/16652` \
`$ git checkout pull/16652`

Update a local copy of the PR: \
`$ git checkout pull/16652` \
`$ git pull https://git.openjdk.org/jdk.git pull/16652/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16652`

View PR using the GUI difftool: \
`$ git pr show -t 16652`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16652.diff">https://git.openjdk.org/jdk/pull/16652.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16652#issuecomment-1809911485)

### CODE REVIEW

**Comment by magicus** [comment]
Have you tested this? I can't see how this possibly could work. You'd need a 

```
      - name: 'Get GTest'
        id: gtest
        uses: ./.github/actions/get-gtest
```

section to have a `steps.gtest` to refer to.

**Comment by shipilev** [comment]
> You'd need a section to have a `steps.gtest` to refer to.

True. I hoped it would work out of the box, and was waiting for GHA to catch up. Added the section now, waiting for new GHA run.

**Comment by magicus** [comment]
(If you feel the urge to open a PR before all testing is complete, you can mark it as draft to avoid having it being reviewed before it is ready to review...)

**Review by magicus — APPROVED** [review]
Looks good, but make sure it is run properly through GHA before integrating.

**Comment by shipilev** [comment]
> (If you feel the urge to open a PR before all testing is complete, you can mark it as draft to avoid having it being reviewed before it is ready to review...)

Yeah, I meant to open as draft to get testing done, but misclicked. Apologies.

**Comment by shipilev** [comment]
I think we can proceed with a single review here, right? Would appreciate more reviews anyway! Thanks.

**Review by magicus — APPROVED** [review]
I think you can proceed with just my review, yes. GHA does not get much attention so you're not likely to get many other reviews. And this patch is fairly trivial.

**Review by tstuefe — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
Thanks all!

/integrate

**Pull request closed without merging**
