### PR TITLE
8281941: Change CDS warning messages to use Unified Logging

### PR DESCRIPTION
**Pull request by matias9927**
As an addendum to previous commits that changed CDS logging, this replaces the remaining log messages with Unified logging. There are also old warning messages that used to be prefixed with UseSharedSpaces which have been updated along with their tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8281941](https://bugs.openjdk.org/browse/JDK-8281941): Change CDS warning messages to use Unified Logging

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12890/head:pull/12890` \
`$ git checkout pull/12890`

Update a local copy of the PR: \
`$ git checkout pull/12890` \
`$ git pull https://git.openjdk.org/jdk pull/12890/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12890`

View PR using the GUI difftool: \
`$ git pr show -t 12890`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12890.diff">https://git.openjdk.org/jdk/pull/12890.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
These changes seem fine in themselves.

There are some inconsistencies, IMO, in the choice of log-level for CDS "failures" but that would be for a separate RFE. For example I find it odd that reporting an issue trying to load the shared archive is  a warning, but the actual message the archive could not be used is only "info":
```
[0.001s][warning][cds] Unable to read generic CDS file map header from shared archive
[0.001s][info   ][cds] Unable to use shared archive: invalid archive
```

Thanks.

**Review by calvinccheung — APPROVED** [review]
LGTM

**Comment by matias9927** [comment]
Thank you for the reviews @calvinccheung and @dholmes-ora.
/integrate

**Pull request closed without merging**
