### PR TITLE
8255548: Missing coverage for javax.xml.crypto.dom.DOMCryptoContext

### PR DESCRIPTION
**Pull request by mpdonova**
Implemented tests for the `DomCryptoContext.iterator()` method.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8255548](https://bugs.openjdk.org/browse/JDK-8255548): Missing coverage for javax.xml.crypto.dom.DOMCryptoContext

### Reviewers
 * [Rajan Halade](https://openjdk.org/census#rhalade) (@rhalade - **Reviewer**)
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13445/head:pull/13445` \
`$ git checkout pull/13445`

Update a local copy of the PR: \
`$ git checkout pull/13445` \
`$ git pull https://git.openjdk.org/jdk.git pull/13445/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13445`

View PR using the GUI difftool: \
`$ git pr show -t 13445`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13445.diff">https://git.openjdk.org/jdk/pull/13445.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13445#issuecomment-1505345127)

### CODE REVIEW

**Review by rhalade — APPROVED** [review]
LGTM. @seanjmullan let us know if you have any comments?

**Review by seanjmullan — APPROVED** [review]

**Comment by seanjmullan** [comment]
> LGTM. @seanjmullan let us know if you have any comments?

LGTM.

**Pull request closed without merging**
