### PR TITLE
8285380: Fix typos in security

### PR DESCRIPTION
**Pull request by magicus**
I ran `codespell` on modules owned by the security team (`java.security.jgss java.security.sasl java.smartcardio java.xml.crypto jdk.crypto.cryptoki jdk.crypto.ec jdk.crypto.mscapi jdk.security.auth jdk.security.jgss`), and accepted those changes where it indeed discovered real typos.

I will update copyright years using a script before pushing (otherwise like every second change would be a copyright update, making reviewing much harder).

The long term goal here is to make tooling support for running `codespell`. The trouble with automating this is of course all false positives. But before even trying to solve that issue, all true positives must be fixed. Hence this PR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285380](https://bugs.openjdk.java.net/browse/JDK-8285380): Fix typos in security

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**)
 * [Bradford Wetmore](https://openjdk.java.net/census#wetmore) (@bradfordwetmore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8340/head:pull/8340` \
`$ git checkout pull/8340`

Update a local copy of the PR: \
`$ git checkout pull/8340` \
`$ git pull https://git.openjdk.java.net/jdk pull/8340/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8340`

View PR using the GUI difftool: \
`$ git pr show -t 8340`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8340.diff">https://git.openjdk.java.net/jdk/pull/8340.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
The folks on security-dev will know for sure but I assume that the changes to the imported Apache Santuario code should be dropped as it will make upgrades more complicated.

**Comment by magicus** [comment]
@AlanBateman So there is even more 3rd party code in there? :-( I tried to ignore fixes for all files that I could identify as 3rd party. It's actually a bit annoying that we have imported source code thrown around like this in the source tree, so there is no clear boundary between code we own and code we import from someone else...

**Comment by AlanBateman** [comment]
> @AlanBateman So there is even more 3rd party code in there? :-( I tried to ignore fixes for all files that I could identify as 3rd party. It's actually a bit annoying that we have imported source code thrown around like this in the source tree, so there is no clear boundary between code we own and code we import from someone else...

security-dev can say for sure but the only 3rd party code I see in this change is in the src/java.xml.crypto/share/classes/com/sun/org/apache tree (the package name gives a hint has it was it was re-packaged).

**Review by wangweij — APPROVED** [review]
Looks good to me. Thanks.

**Review by bradfordwetmore — APPROVED** [review]
LGTM.

**Comment by seanjmullan** [comment]
> > @AlanBateman So there is even more 3rd party code in there? :-( I tried to ignore fixes for all files that I could identify as 3rd party. It's actually a bit annoying that we have imported source code thrown around like this in the source tree, so there is no clear boundary between code we own and code we import from someone else...
> 
> security-dev can say for sure but the only 3rd party code I see in this change is in the src/java.xml.crypto/share/classes/com/sun/org/apache tree (the package name gives a hint has it was it was re-packaged).

The `src/java.xml.crypto/share/classes/org/jcp` tree is also 3rd party Apache code.

However, I am ok with including the spelling fixes for the 3rd-party Apache code (this tree and the one Alan mentions above which you already reverted, but can put it back) with this PR. I am a Committer on the Apache Santuario project so I can push these spelling fixes (they should be non-controversial) to their code base and there won't be any conflicts when we merge up the JDK to the next Santuario release.

**Pull request closed without merging**
