### PR TITLE
JDK-8305644: IGV: Node text not updated when switching from/to CFG view

### PR DESCRIPTION
**Pull request by tobiasholenstein**
When switching the layouting mode to or from CFG the node text is not updated.

- Switching to `CFG view` gave the wrong node text: 
fail_to
- with this fix it looks like this
fix_to

- Switching from `CFG view` gave the wrong node text: 
fail_from
- with this fix it looks like this
fix-from

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305644](https://bugs.openjdk.org/browse/JDK-8305644): IGV: Node text not updated when switching from/to CFG view

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13348/head:pull/13348` \
`$ git checkout pull/13348`

Update a local copy of the PR: \
`$ git checkout pull/13348` \
`$ git pull https://git.openjdk.org/jdk.git pull/13348/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13348`

View PR using the GUI difftool: \
`$ git pr show -t 13348`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13348.diff">https://git.openjdk.org/jdk/pull/13348.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13348#issuecomment-1497205454)

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good, thanks for fixing this! I must have missed testing this scenario when merging the changes from JDK-8302644 into JDK-8302738.

**Review by chhagedorn — APPROVED** [review]
Given that this line was dropped by mistake, the fix to add the line again looks good and trivial. Nevertheless, setting a field in a getter method like that seems wrong/unexpected.

**Comment by tobiasholenstein** [comment]
> Given that this line was dropped by mistake, the fix to add the line again looks good and trivial. Nevertheless, setting a field in a getter method like that seems wrong/unexpected.

You are right. Even though re-adding the dropped line fixes the issue, it is still bad practice. I fixed the issue now in the proper way: 
`showCFG` is set in `setShowCFG(boolean enable)` - there is the right place to also set `diagram.setCFG(enable);` and NOT in the `getDiagram()` since getters should be side effect free. Thanks for the input @chhagedorn !

**Review by robcasloz — APPROVED** [review]

**Comment by tobiasholenstein** [comment]
Thanks @chhagedorn and @robcasloz for the reviews!

/integrate

**Pull request closed without merging**
