### PR TITLE
8258252: Move PtrQueue enqueue to PtrQueueSet subclasses

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this refactoring in the PtrQueue/PtrQueueSet hierarchy.

The functions PtrQueue::enqueue and PtrQueue::enqueue_known_active are
removed, along with the helper virtual function PtrQueue::handle_completed_buffer.

Instead we now have G1{Dirty,Redirty}CardQueueSet::enqueue and SATBMarkQueueSet::enqueue/enqueue_known_active, each tailored to the corresponding specific behavior. They use some shared helper routines from PtrQueueSet, and the PtrQueue buffer and index have been made accessible to clients.

Testing:
mach5 tier1-3, 5 (stress tests)
Local (linux-x64) tier1 with -XX:+UseShenandoahGC

/label hotspot

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258252](https://bugs.openjdk.java.net/browse/JDK-8258252): Move PtrQueue enqueue to PtrQueueSet subclasses

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 9dc2a4e514f4e1bba5a4053bcdabb91af1901e2c
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to 9dc2a4e514f4e1bba5a4053bcdabb91af1901e2c

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1776/head:pull/1776`
`$ git checkout pull/1776`

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by rkennke — APPROVED** [review]
Looks good to me, and I ran some more Shenandoah tests which also look good.

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @rkennke for reviews, and @rkennke for additional Shenandoah testing.

**Pull request closed without merging**
