### PR TITLE
8297605: improve DelayQueue removal method javadoc

### PR DESCRIPTION
**Pull request by Martin-Buchholz**
Inviting @DougLea and @viktorklang-ora to review.

As usual, I couldn't resist more fiddling.  
- Added missing tests for take, remove(), remove(Object).
- Improved DelayQueueTest's testing infrastructure
- added more test assertions
- linkified new javadoc definitions

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8304686](https://bugs.openjdk.org/browse/JDK-8304686) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8297605](https://bugs.openjdk.org/browse/JDK-8297605): improve DelayQueue removal method javadoc
 * [JDK-8304686](https://bugs.openjdk.org/browse/JDK-8304686): improve DelayQueue removal method javadoc (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [fb14b2f3](https://git.openjdk.org/jdk/pull/12838/files/fb14b2f361cbefb896eb293a9bb79e09a3275409)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12838/head:pull/12838` \
`$ git checkout pull/12838`

Update a local copy of the PR: \
`$ git checkout pull/12838` \
`$ git pull https://git.openjdk.org/jdk.git pull/12838/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12838`

View PR using the GUI difftool: \
`$ git pr show -t 12838`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12838.diff">https://git.openjdk.org/jdk/pull/12838.diff</a>

</details>

### CODE REVIEW

**Comment by DougLea** [comment]
Thanks. This is overkill, but the wording changes and new tests look OK.

**Comment by viktorklang-ora** [comment]
@Martin-Buchholz I think the updated documentation is clearer. We need some extra reviewers like @AlanBateman or @pron to sign off :)

**Review by AlanBateman — APPROVED** [review]
Wordy but clear, I think it's okay.

**Comment by viktorklang-ora** [comment]
Nice work @Martin-Buchholz! 👍

**Pull request closed without merging**
