### PR TITLE
8286907: keytool should warn about weak PBE algorithms

### PR DESCRIPTION
**Pull request by haimaychao**
Please review the fix to address the problem in keytool -genseckey and -importpass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286907](https://bugs.openjdk.org/browse/JDK-8286907): keytool should warn about weak PBE algorithms

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)
 * [Weijun Wang](https://openjdk.org/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12056/head:pull/12056` \
`$ git checkout pull/12056`

Update a local copy of the PR: \
`$ git checkout pull/12056` \
`$ git pull https://git.openjdk.org/jdk pull/12056/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12056`

View PR using the GUI difftool: \
`$ git pr show -t 12056`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12056.diff">https://git.openjdk.org/jdk/pull/12056.diff</a>

</details>

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]

**Comment by haimaychao** [comment]
Yes, the issue for `PBEWithSHA1AndRC2_40` when `SHA-1` is removed from `jdk.security.legacyAlgorithms` is because Algorithm Decomposer decomposes it to RC2_40 **accordingly** and Constraints map contains RC2 which is built based on `jdk.security.legacyAlgorithms`. Filed JDK-8301127 for this.
Filed JDK-8301130 to track adding MD2 to j`dk.security.legacyAlgorithms`.

**Comment by seanjmullan** [comment]
Yeah, this is a little tricky. My feeling is that if you disable an algorithm like "RC2", it should cover all uses of it no matter what the keysize. If you only want to disable certain keysizes, then you should add a keysize constraint. We would need to make the parsing smarter so that "RC keysize <= 40" covers RC_40 but not RC_128, etc.

Hmac is another good corner case. It would be nice if we could have exceptions, like "SHA512", "!HmacSHA512". But that's a little more involved, and requires some more thought as to whether that is a good idea.

**Comment by haimaychao** [comment]
@wangweij @seanjmullan For the scenario, i.e. PBEWithSHA1AndRC2_40 after SHA1 removal, we probably could
treat RC2_40 as RC2 after decomposing. For another scenario, adding RC2 KeySize < 40, we currently have a similar test case (i.e. AES keySize < 256) in WeakSecretKeyTest.java, and keytool will emit warning as a result of keysize constraint checking. The question arises is does it apply to PBEWithSHA1AndRC2_40 as well? I’d think it should if we treat RC2_40 as RC2 after decomposing. However, the PBEKey generated for PBEWithSHA1AndRC2_40 will have PBEwithMD5andDES algorithm. Algorithm constraint checking on MD5 would take place earlier than keysize constraint checking. As a result, warnings for keysize constraint will not be emitted. These are my current thoughts and more thoughts surely are needed to address JDK-8301127.
I suggest we look at the possible issues with various corner cases in algorithm decomposing and keysize constraints, etc, for PBExxx and Hmacxxx in JDK-8301127. Do you agree JDK-8301127 would serve the need?

**Comment by haimaychao** [comment]
@seanjmullan @wangweij Thanks for the review.

**Pull request closed without merging**
