### PR TITLE
8267630: Start of release updates for JDK 18

### PR DESCRIPTION
**Pull request by jddarcy**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8267630](https://bugs.openjdk.java.net/browse/JDK-8267630): Start of release updates for JDK 18
 * [JDK-8267632](https://bugs.openjdk.java.net/browse/JDK-8267632): Add source 18 and target 18 to javac
 * [JDK-8267631](https://bugs.openjdk.java.net/browse/JDK-8267631): Add SourceVersion.RELEASE_18

### Reviewers
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to 9c7c88bffaa3884bb2e2de9e944ee78a6b09b2d0
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 15479c926687af8ef45af96bddfe074a116c0b05

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4175/head:pull/4175` \
`$ git checkout pull/4175`

Update a local copy of the PR: \
`$ git checkout pull/4175` \
`$ git pull https://git.openjdk.java.net/jdk pull/4175/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4175`

View PR using the GUI difftool: \
`$ git pr show -t 4175`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4175.diff">https://git.openjdk.java.net/jdk/pull/4175.diff</a>

</details>

### CODE REVIEW

**Comment by jddarcy** [comment]
JDK 18 is right around the corner, time for the usual start-of-release changeset for review.

Typical structure for these kinds of changes. I'll update the symbol file information of JDK 17 b25 after that build is promoted.

Usual updates to SourceVersion, javac, HotSpot, and version-oriented tests.

**Review by irisclark — APPROVED** [review]

**Review by erikj79 — APPROVED** [review]
Build change looks good.

Please be aware of the incoming change https://bugs.openjdk.java.net/browse/JDK-8263468 which will add another version field to version-numbers.conf, which may need to be updated too. The exact policy around that is still unclear though.

**Review by irisclark — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,
David

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
