### PR TITLE
8049700: Deprecate obsolete classes and methods in javax/swing/plaf/basic

### PR DESCRIPTION
**Pull request by trebari**
Please review the following fix for jdk17.
In this fix i have deprecated and marked for removal following classes and methods 
   public void intervalAdded(ListDataEvent e)
   public void intervalRemoved(ListDataEvent e)
   protected boolean lt(File a, File b) in BasicDirectoryModel.java

   inner class PropertyChangeHandler, VSBChangeListener, HSBChangeListener, 
   ViewportChangeHandler in BasicScrollPaneUI.java
   inner class MouseInputHandler in BasicMenuItemUI.java
   method BasicToolBarUI.java#createFloatingFrame

From 8049700 not deprecated the paintText(Graphics g, JComponent c, Rectangle textRect, String text) method in BasicButtonUI  as AquaButtonUI, MetalButtonUI and MetalToggleButtonUI overrides it.
Similarly not deprecated ChangeHandler of BasicMenuUI as AquaMenuUI and MotifMenuUI uses this class.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8049700](https://bugs.openjdk.java.net/browse/JDK-8049700): Deprecate obsolete classes and methods in javax/swing/plaf/basic

### Reviewers
 * [Prasanta Sadhukhan](https://openjdk.java.net/census#psadhukhan) (@prsadhuk - **Reviewer**) ⚠️ Review applies to cf0bc946e18ea850cbecc2d0467c1893639a7436
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to 88a8c4754c0c830c9f164674eb8e969129d4be72
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to 88a8c4754c0c830c9f164674eb8e969129d4be72
 * [Alexander Zvegintsev](https://openjdk.java.net/census#azvegint) (@azvegint - **Reviewer**) ⚠️ Review applies to 88a8c4754c0c830c9f164674eb8e969129d4be72
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/1958/head:pull/1958` \
`$ git checkout pull/1958`

Update a local copy of the PR: \
`$ git checkout pull/1958` \
`$ git pull https://git.openjdk.java.net/jdk pull/1958/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1958`

View PR using the GUI difftool: \
`$ git pr show -t 1958`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/1958.diff">https://git.openjdk.java.net/jdk/pull/1958.diff</a>

</details>

### CODE REVIEW

**Review by prsadhuk — COMMENTED** [review]
Please elaborate as to why this methods are to be deprecated.
It will be useful if you give alternate methods to be used in the javadoc in @deprecated tag 
which are supposed to be called by user once these are removed.

**Comment by trebari** [comment]
The methods intervalAdded(ListDataEvent e) ,intervalRemoved(ListDataEvent e) and  lt(File a, File b) of  javax/swing/plaf/basic/BasicDirectoryModel.java  states that "Obsolete - not used" ( in the doc).

The BasicDirectoryModel uses similar methods like fireIntervalAdded, fireIntervalRemoved which calls AbstractListModel#fireIntervalAdded.
But not sure that these are the  alternate methods.Also dont see anything similar to lt(File a, File b).

The method createFloatingFrame in the BasicToolBarUI.java states that it is "No longer used" and also specifies to use BasicToolBarUI.createFloatingWindow(JToolBar).

The class MouseInputHandler in BasicMenuUI.java and classes PropertyChangeHandler, VSBChangeListener, HSBChangeListener, ViewportChangeHandler in BasicScrollPaneUI.java states that(as comments inside the class)
        "This class exists only for backward compatibility. All
        its functionality has been moved into Handler."
we can add the above in the doc for these classes.

**Comment by prsadhuk** [comment]
> 
> 
> The methods intervalAdded(ListDataEvent e) ,intervalRemoved(ListDataEvent e) and lt(File a, File b) of javax/swing/plaf/basic/BasicDirectoryModel.java states that "Obsolete - not used" ( in the doc).
> 
> The BasicDirectoryModel uses similar methods like fireIntervalAdded, fireIntervalRemoved which calls AbstractListModel#fireIntervalAdded.
> But not sure that these are the alternate methods.Also dont see anything similar to lt(File a, File b).
> 
> The method createFloatingFrame in the BasicToolBarUI.java states that it is "No longer used" and also specifies to use BasicToolBarUI.createFloatingWindow(JToolBar).
> 
> The class MouseInputHandler in BasicMenuUI.java and classes PropertyChangeHandler, VSBChangeListener, HSBChangeListener, ViewportChangeHandler in BasicScrollPaneUI.java states that(as comments inside the class)
> "This class exists only for backward compatibility. All
> its functionality has been moved into Handler."
> we can add the above in the doc for these classes.

OK. Please add these statements in the doc, wherever possible.
Also, try to run all jtreg/jck classes with these classes/methods removed so that we dont get any surprises once they are removed.

**Comment by trebari** [comment]
> > The methods intervalAdded(ListDataEvent e) ,intervalRemoved(ListDataEvent e) and lt(File a, File b) of javax/swing/plaf/basic/BasicDirectoryModel.java states that "Obsolete - not used" ( in the doc).
> > The BasicDirectoryModel uses similar methods like fireIntervalAdded, fireIntervalRemoved which calls AbstractListModel#fireIntervalAdded.
> > But not sure that these are the alternate methods.Also dont see anything similar to lt(File a, File b).
> > The method createFloatingFrame in the BasicToolBarUI.java states that it is "No longer used" and also specifies to use BasicToolBarUI.createFloatingWindow(JToolBar).
> > The class MouseInputHandler in BasicMenuUI.java and classes PropertyChangeHandler, VSBChangeListener, HSBChangeListener, ViewportChangeHandler in BasicScrollPaneUI.java states that(as comments inside the class)
> > "This class exists only for backward compatibility. All
> > its functionality has been moved into Handler."
> > we can add the above in the doc for these classes.
> 
> OK. Please add these statements in the doc, wherever possible.
I have updated the documentation for some of the classes. Also changed copyright year.
> Also, try to run all jtreg/jck tests with these classes/methods removed so that we dont get any surprises once they are removed.
i have ran all the jtreg/jck tests ,the link is in bug description.

**Review by prsadhuk — APPROVED** [review]
It probably will need CSR

**Comment by trebari** [comment]
I have created CSR : [JDK-8260921](https://bugs.openjdk.java.net/browse/JDK-8260921)
Please take a look.

**Review by prrace — CHANGES_REQUESTED** [review]
Are these methods all expected to be used only by a L&F rather than an application ?
If by an application, then forRemoval seems too strong to me.
If by a L&F then I think you need to go research what open source L&Fs there are out there and see how many of them are affected. Then we can decide about forRemoval.

**Comment by trebari** [comment]
> Are these methods all expected to be used only by a L&F rather than an application ?
> If by an application, then forRemoval seems too strong to me.
> If by a L&F then I think you need to go research what open source L&Fs there are out there and see how many of them are affected. Then we can decide about forRemoval.

After the fix i have ran all the automated jtreg and jck (link is in the JBS) and not seeing any issues there.
I also ran SwingSet2 with Aqua, Metal, Motif, Nimbus, Windows, Windows Classic, and GTK LookAndFeel
 with debug statement in each of the deprecated methods and class, 
and none of the methods and classes are getting called in any of the LAF's.

For now we can remove the "forRemoval".

**Comment by trebari** [comment]
> Are these methods all expected to be used only by a L&F rather than an application ?
> If by an application, then forRemoval seems too strong to me.
> If by a L&F then I think you need to go research what open source L&Fs there are out there and see how many of them are affected. Then we can decide about forRemoval.
There are open source LAFs which will be affected by removing these.
Like FlatLaf https://www.formdev.com/flatlaf/ uses BasicScrollPaneUI$PropertyChangeHandler.
Also i have removed the "forRemoval" for now.

**Comment by trebari** [comment]
@prrace Please take a look.

**Comment by trebari** [comment]
@prrace any more comments on this ?

**Review by prrace — APPROVED** [review]

**Comment by prrace** [comment]
The CSR still had forRemoval. I've updated it and generally tidied it, but you may want to check my work.

**Comment by trebari** [comment]
I have checked the CSR, made minor corrections. 
Overall looks good, thanks for updating it.

**Review by mrserb — APPROVED** [review]

**Comment by mrserb** [comment]
I think we can file a separate bug to add "for removal" in JDK 19 and then remove them somewhere after JDK 22.

**Comment by trebari** [comment]
> I think we can file a separate bug to add "for removal" in JDK 19 and then remove them somewhere after JDK 22.

I have filed a separate bug for this : https://bugs.openjdk.java.net/browse/JDK-8264743

**Review by azvegint — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Pull request closed without merging**
