### PR TITLE
8297285: Shenandoah pacing causes assertion failure during VM initialization

### PR DESCRIPTION
**Pull request by ashu-mehra**
Please review the fix for the assertion failure seen during VM init due to pacing in shenandoah gc.
The fix is to avoid pacing during VM initialization as the main thread is not yet an active java thread.

Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297285](https://bugs.openjdk.org/browse/JDK-8297285): Shenandoah pacing causes assertion failure during VM initialization

### Reviewers
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11360/head:pull/11360` \
`$ git checkout pull/11360`

Update a local copy of the PR: \
`$ git checkout pull/11360` \
`$ git pull https://git.openjdk.org/jdk pull/11360/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11360`

View PR using the GUI difftool: \
`$ git pr show -t 11360`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11360.diff">https://git.openjdk.org/jdk/pull/11360.diff</a>

</details>

### CODE REVIEW

**Comment by ashu-mehra** [comment]
zero build was failing with following compile error:

```
/usr/bin/ld: /home/runner/work/jdk/jdk/build/linux-x64/hotspot/variant-zero/libjvm/objs/shenandoahPacer.o: in function `JavaThread::is_active_Java_thread() const':
/home/runner/work/jdk/jdk/src/hotspot/share/runtime/javaThread.hpp:514: undefined reference to `JavaThread::is_terminated() const'
```

Pushed a commit to include the necessary header file.

**Comment by ashu-mehra** [comment]
Can I please get reviews for this PR.

**Review by rkennke — APPROVED** [review]
Looks good to me! Thank you, Ashu!

**Comment by ashu-mehra** [comment]
@rkennke thanks for suggesting and reviewing the fix.

**Review by phohensee — COMMENTED** [review]
I'm not familiar with this code, so please bear with me. :) The comment on line 246 says "Thread which is not an active Java thread should also not block.", but the check at line 251 will return (i.e., looks like not block) if the current thread is an active Java thread. Should the check be !current->is_active_Java_thread() instead?

**Comment by ashu-mehra** [comment]
@phohensee you are right. It should be `!current->is_active_Java_thread()`, how did I miss that `!`!
Thanks for catching it in time.

**Review by phohensee — APPROVED** [review]
Looks good now.

**Review by rkennke — APPROVED** [review]

**Pull request closed without merging**
