### PR TITLE
JDK-8303798: REDO - Remove fdlibm C sources

### PR DESCRIPTION
**Pull request by jddarcy**
This PR is a redo of JDK-8302801: Remove fdlibm C sources. The problem with JDK-8302801 was that it neglected (mea culpa) to include a Java implementation of IEEEremainder before the FDLIBM C implementation was deleted. Such an implementation has been successfully provided under JDK-8304028: Port fdlibm IEEEremainder to Java. After JDK-8304028, there are no native methods left in StrictMath.

This PR is the same as JDK-8302801 other than StrictMath.c already being removed under JDK-8304028.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303798](https://bugs.openjdk.org/browse/JDK-8303798): REDO - Remove fdlibm C sources

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13279/head:pull/13279` \
`$ git checkout pull/13279`

Update a local copy of the PR: \
`$ git checkout pull/13279` \
`$ git pull https://git.openjdk.org/jdk.git pull/13279/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13279`

View PR using the GUI difftool: \
`$ git pr show -t 13279`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13279.diff">https://git.openjdk.org/jdk/pull/13279.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13279#issuecomment-1493065532)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
I assume at least tier1-4 has been run, in which case this looks fine.

**Comment by jddarcy** [comment]
> I assume at least tier1-4 has been run, in which case this looks good (same as previous PR).

Right; tier 1 - 4 job was successful other than an unrelated time-out. Previously, with the initial removal attempt there were many failures in tiers 2 and 3.

**Review by irisclark — APPROVED** [review]

**Review by TheShermanTanker — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Seems fine to me.

**Pull request closed without merging**
