### PR TITLE
8305906: HttpClient may use incorrect key when finding pooled HTTP/2 connection for IPv6 address

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which proposes to fix the issue reported in https://bugs.openjdk.org/browse/JDK-8305906?

As noted in that issue, when IPv6 hosts are involved, the HttpClient on certain occasions can end up caching the connection with a key which doesn't match with the key which is then used in a subsequent request against the same target host. 

The commit in this PR now wraps the IPv6 address in a square bracket consistently so that the correct key is used both during storing the connection in the pool and when looking up.

A new jtreg test has been added which reproduces this issue without the fix and verifies the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305906](https://bugs.openjdk.org/browse/JDK-8305906): HttpClient may use incorrect key when finding pooled HTTP/2 connection for IPv6 address (**Bug** - `"4"`)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13456/head:pull/13456` \
`$ git checkout pull/13456`

Update a local copy of the PR: \
`$ git checkout pull/13456` \
`$ git pull https://git.openjdk.org/jdk.git pull/13456/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13456`

View PR using the GUI difftool: \
`$ git pr show -t 13456`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13456.diff">https://git.openjdk.org/jdk/pull/13456.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13456#issuecomment-1506790304)

### CODE REVIEW

**Comment by djelinski** [comment]
This patch improves the situation, but is not sufficient to address all cases. For example, `http://[::1]` will still not use the cache, because the cache key will contain `[0:0:0:0:0:0:0:1]` instead of `[::1]`.

**Comment by jaikiran** [comment]
Thank you for catching that, Daniel. You are indeed right, the fix missed this part. I updated the new `ConnectionReuseTest` to run a test which matches what you described and that too fails, with the fix I had in this PR.

I have now updated the PR to use `HttpRequestImpl.getAddress()` (which returns a `InetSocketAddress`) instead of `HttpRequestImpl.getURI()` while looking up the cache keys. What this does is that it gets rid of the usage of the `URI.getHost()` API completely, during connection cache lookups. Instead, this now relies solely on the `InetAddress` API which always returns a long form address string. This is similar to what we do in the HTTP1 connection caching internally.

With this change the `ConnectionReuseTest` passes, even with the newly added additional test. I will run tier tests to make sure this doesn't impact anything else.

**Comment by djelinski** [comment]
Thanks for the fix, that looks better.

Now that we always use `InetSocketAddress` to build the cache key, do we still need to wrap the hostnames in brackets?

**Review by djelinski — APPROVED** [review]
LGTM

**Comment by jaikiran** [comment]
(can't believe it's already 4 weeks)
Please keep this open, I'll revive this shortly.

**Review by dfuch — APPROVED** [review]

**Comment by jaikiran** [comment]
Hello @dfuch, @djelinski, I've done some minor changes to this PR to have `keyFor` accept a `HttpRequestImpl` instance so that it's clear where the `InetSocketAddress`es get sourced from when constructing the cache key. CI tests with this latest change continue to pass. Requesting a fresh review of this change, please.

**Review by djelinski — APPROVED** [review]

**Review by dfuch — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you both for the reviews.

**Comment by backwaterred** [comment]
Thanks for your change @jaikiran! We've seen this issue in my organization occurring in jdk17, and jdk11. It's nice to see that it has been fixed.

Do you have any plans to backport it?

**Comment by jaikiran** [comment]
Hello Tyler,

> Do you have any plans to backport it?

I haven't been involved in the 11/17 backports in recent times, so I don't have any specific plans to backport this. Having said that, I think this does look like a good candidate for backporting, so if you or anyone has done it before, please do go ahead.

**Pull request closed without merging**
