### PR TITLE
8341944: The zlib library no longer requires dummy byte for raw inflate

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this cleanup PR which removes overrides of `InflaterInputStream.fill` in `ZipFileInflaterInputStream` and `ZipFileSystem::getInputStream`. Associated boolean fields used to track `eof` are also removed.

These overrides exist to provide zlib with an extra dummy byte at the end of raw compressed streams (no wrapping):

```java
// Override fill() method to provide an extra "dummy" byte
// at the end of the input stream. This is required when
// using the "nowrap" Inflater option.
protected void fill() throws IOException {
```
However, zlib has not required such an extra dummy byte since 2003. 

```
Changes in 1.2.0 (9 March 2003)
- New and improved inflate code
    - Raw inflate no longer needs an extra dummy byte at end
``` 

The code in these overrides is effectively dead and removing it cleans up our code and reclaims weirdness dollars for our budget.

Risk: I cannot imagine anyone is building OpenJDK with a 21 year old ZLIB.  Please advise if this is the case or if any zlib fork in use still has this limitation.

Testing: ZIP and ZIPFS tests run green locally. GHA also green. No tests are added or modified, this is a cleanup-only PR. Manually verified that the code is dead by injecting AssertionErrors.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 25 to be approved (needs to be created)

### Issue
 * [JDK-8341944](https://bugs.openjdk.org/browse/JDK-8341944): The zlib library no longer requires dummy byte for raw inflate (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21467/head:pull/21467` \
`$ git checkout pull/21467`

Update a local copy of the PR: \
`$ git checkout pull/21467` \
`$ git pull https://git.openjdk.org/jdk.git pull/21467/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21467`

View PR using the GUI difftool: \
`$ git pr show -t 21467`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21467.diff">https://git.openjdk.org/jdk/pull/21467.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21467#issuecomment-2406893500)
</details>

### CODE REVIEW

**Comment by eirbjo** [comment]
Channeling @simonis for his experience with third-party zlib implementations.

**Comment by LanceAndersen** [comment]
I think we need to be a bit cautious with the proposed change while I understand the desire to remove potentially unneeded code. 

 I have not yet found a specific issue for the for the original need for the overload of fill, but have not looked to hard either, and the constructor in Inflater.java also makes reference to gzip for which we do not have as much test coverage as we do for Zip.

So we might want to hold off on this PR for JDK 24 while we try to do some more archaeological digging.

As far as which zlib with the openJDK,  currently the openjdk project bundles zlib with the windows builds and relies on the zlib bundled with the various OS's 

I would be surprised to find any vendor using a zlib below zlib 1.2.13 or 1.3.1

**Comment by eirbjo** [comment]
> I think we need to be a bit cautious with the proposed change while I understand the desire to remove potentially unneeded code.

I understand the need to be cautious in this area. But I would also like to avoid cargo-culting this for another 21 years :-)  

> I have not yet found a specific issue for the for the original need for the overload of fill, but have not looked to hard either

If we trust the zlib change log, the original need retired with 1.2.0. Any of the performance-motivated forks like chromium-zlib or cloudflare-zlib should have been forked long after this. Perhaps @simonis can confirm. 

>, and the constructor in Inflater.java also makes reference to gzip for which we do not have as much test coverage as we do for Zip.

The extra dummy byte note in the Inflater constructor is now misleading and should probably go too. Would require a CSR. 

The `@param nowrap` note is perhaps also misleading in that it is not actually specific to GZIP. It just tells zlib to expect raw deflated data, without any wrapping, GZIP or zlib. I guess since the only wrapping supported by the JDK is GZIP, the note is maybe okay. But if we do a CSR, I think we should relax this note to not reference GZIP.  

> So we might want to hold off on this PR for JDK 24 while we try to do some more archaeological digging.

That is fair.

> As far as which zlib with the openJDK, currently the openjdk project bundles zlib with the windows builds and relies on the zlib bundled with the various OS's
> 
> I would be surprised to find any vendor using a zlib below zlib 1.2.13 or 1.3.1

Yes, that would indeed be awkward.

**Comment by eirbjo** [comment]
I have updated the `nowrap` constructor of `java.util.zip.Inflater` to remove the note about the extra 'dummy' input byte. I also tightened up the constructor to more clearly explain what the `nowrap` parameter does. The current "will not use" feels a bit loose. The `nowrap` parameter description is update to not mention GZIP and instead just say "expect compressed input without ZLIB headers".

The matching constructor in `java.util.zip.Deflater` is updated to be consistent with the changes in `Inflater`. These should be easy to read side-by-side.

These API changes requires a CSR, which I plan to create once "more archaeological digging" deems this PR can continue safely.

**Pull request closed without merging**
