### PR TITLE
8343483: Remove unnecessary @SuppressWarnings annotations (serviceability)

### PR DESCRIPTION
**Pull request by archiecobbs**
Please review this patch which removes unnecessary `@SuppressWarnings` annotations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343483](https://bugs.openjdk.org/browse/JDK-8343483): Remove unnecessary @SuppressWarnings annotations (serviceability) (**Sub-task** - P5)

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21857/head:pull/21857` \
`$ git checkout pull/21857`

Update a local copy of the PR: \
`$ git checkout pull/21857` \
`$ git pull https://git.openjdk.org/jdk.git pull/21857/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21857`

View PR using the GUI difftool: \
`$ git pr show -t 21857`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21857.diff">https://git.openjdk.org/jdk/pull/21857.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21857#issuecomment-2453034062)
</details>

### CODE REVIEW

**Comment by plummercj** [comment]
How were these discovered and what testing did you do?

**Comment by archiecobbs** [comment]
Hi @plummercj,

> How were these discovered

See [this thread](https://mail.openjdk.org/pipermail/compiler-dev/2024-November/028573.html). There is a proposal to add a new compiler lint warning for unnecessary `@SuppressWarnings` annotations and these were flagged by the prototype. 

> and what testing did you do?

The only testing done was verifying that the JDK still builds and passes the Github checks without them.

**Comment by plummercj** [comment]
Ok. I suppose this is really only a build concern and not a testing concern, so passing the builds should be enough.

**Review by plummercj — APPROVED** [review]

**Comment by archiecobbs** [comment]
Thanks for the review.

**Pull request closed without merging**
