### PR TITLE
JDK-8301477: Replace NULL with nullptr in os/aix

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi, this PR changes all occurrences of NULL to nullptr for the subdirectory os/aix. Unfortunately the script that does the change isn't perfect, and so we
need to comb through these manually to make sure nothing has gone wrong. I also review these changes but things slip past my eyes sometimes.

Here are some typical things to look out for:

1. No changes but copyright header changed (probably because I reverted some changes but forgot the copyright).
2. Macros having their NULL changed to nullptr, these are added to the script when I find them. They should be NULL.
3. nullptr in comments and logs. We try to use lower case "null" in these cases as it reads better. An exception is made when code expressions are in a comment.

An example of this:

```c++
// This function returns null
void* ret_null();
// This function returns true if *x == nullptr
bool is_nullptr(void** x);
```

Note how `nullptr` participates in a code expression here, we really are talking about the specific value `nullptr`.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301477](https://bugs.openjdk.org/browse/JDK-8301477): Replace NULL with nullptr in os/aix

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [f1968b0f](https://git.openjdk.org/jdk/pull/12313/files/f1968b0ff01f09559f847d057947941a5471e156)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [f1968b0f](https://git.openjdk.org/jdk/pull/12313/files/f1968b0ff01f09559f847d057947941a5471e156)
 * [Tyler Steele](https://openjdk.org/census#tsteele) (@backwaterred - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12313/head:pull/12313` \
`$ git checkout pull/12313`

Update a local copy of the PR: \
`$ git checkout pull/12313` \
`$ git pull https://git.openjdk.org/jdk pull/12313/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12313`

View PR using the GUI difftool: \
`$ git pr show -t 12313`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12313.diff">https://git.openjdk.org/jdk/pull/12313.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
LGTM.

My eyes still twitch a bit each time I read "null" in comments, though ;-)

**Review by coleenp — APPROVED** [review]

**Comment by jdksjolen** [comment]
Hi @backwaterred, would you mind testing this patch to confirm that it works? Thanks!

**Comment by backwaterred** [comment]
> Hi @backwaterred, would you mind testing this patch to confirm that it works? Thanks!

Hi @jdksjolen, compiling on AIX took a little bit of work. I can build with [these changes](https://github.com/openjdk/jdk/files/10735924/12313.txt). Let me know if there is a more convenient way to get them to you.

Testing is underway. I will post when it completes.

**Comment by backwaterred** [comment]
All testing looks good. Thanks for these changes, and for pinging me to test them out.

**Comment by jdksjolen** [comment]
- 

> With the patch I added above, testing on AIX looks good. Thanks for your work on these changes, and for pinging me to test them out.

Hi, thanks for providing the patch. I applied it with two changes of my own:

```
-  size_t stack_size = (size_t)nullptr;
+  size_t stack_size = 0;
```

The line above is: ``

And

```
-  while ((*pc2 != (size_t)nullptr) && (searchcount++ < MAX_FUNC_SEARCH_LEN)) {
+ while ((*pc2 != 0) && (searchcount++ < MAX_FUNC_SEARCH_LEN)) {
```

Here I thought maybe we dereference the pointer by accident, and we really meant `while ((pc2 != nullptr))`, but just below that we have:

```c++
  if (*pc2 != 0) {
    trcVerbose("no traceback table found");
    return false;
  }
```

It's unlikely you make the same mistake twice, and this time referring to the value as `0` instead of `NULL`.

**Review by backwaterred — APPROVED** [review]

**Comment by jdksjolen** [comment]
Thanks for the re-approval.

/integrate

**Pull request closed without merging**
