### PR TITLE
8331721: Introduce CollectedHeap helper methods for any GC in progress

### PR DESCRIPTION
**Pull request by shipilev**
Continuation of [JDK-8331573](https://bugs.openjdk.org/browse/JDK-8331573). So far we only have a way to test for STW GCs. We would need these more generic sensing methods for [JDK-8331572](https://bugs.openjdk.org/browse/JDK-8331572).

This patch considers that there can be several concurrent GCs in progress. A notable example of that is Generational ZGC, where minor and major concurrent collections can run at the same time. For G1, concurrent mark can interleave with collection pauses. This is why we track the number of GCs in progress as atomic.
 
Initially, I thought to use `is_gc_active` name freed up by [JDK-8331573](https://bugs.openjdk.org/browse/JDK-8331573), but then I thought better of it. My concern would be that some backports might be confused about what `is_gc_active` name really means, depending on whether JDK-8331573 and this PR is backported or not. To avoid this confusion, I chose `is_any_gc_active` name instead.

This PR is somewhat open for bikeshedding about the names :)

Additional testing:
 - [x] Linux AArch64 server fastdebug, `hotspot_gc`
 - [ ] Linux AArch64 server fastdebug, `all`

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331721](https://bugs.openjdk.org/browse/JDK-8331721): Introduce CollectedHeap helper methods for any GC in progress (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19122/head:pull/19122` \
`$ git checkout pull/19122`

Update a local copy of the PR: \
`$ git checkout pull/19122` \
`$ git pull https://git.openjdk.org/jdk.git pull/19122/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19122`

View PR using the GUI difftool: \
`$ git pr show -t 19122`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19122.diff">https://git.openjdk.org/jdk/pull/19122.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19122#issuecomment-2098942472)

### CODE REVIEW

**Comment by zhengyu123** [comment]
Can you explain the purpose of this change? I assume you want to enable `oopMapCache` only when any gc is active, am I correct?

**Comment by shipilev** [comment]
> Can you explain the purpose of this change? I assume you want to enable `oopMapCache` only when any gc is active, am I correct?

Yes, I want to replace the OopMapCache gating check with `is_any_gc_active()`. But I think tracking concurrent GCs in progress might be useful for other cases, _and_ `OopMapCache` change would require more touchups, so I don't want to cobble these together.

**Comment by zhengyu123** [comment]
> > Can you explain the purpose of this change? I assume you want to enable `oopMapCache` only when any gc is active, am I correct?
> 
> Yes, I want to replace the OopMapCache gating check with `is_any_gc_active()`. But I think tracking concurrent GCs in progress might be useful for other cases, _and_ `OopMapCache` change would require more touchups, so I don't want to cobble these together.

But is it really necessary? IMO, some stack walk code can also benefit from `oopMapCache`, e.g. https://code.devsnc.com/dev/glide-jdk17/blob/995d513f19fadf233b64f1caee386daa5700148d/src/hotspot/share/prims/stackwalk.cpp#L298

**Comment by shipilev** [comment]
> But is it really necessary? IMO, some stack walk code can also benefit from `oopMapCache`, e.g. https://github.com/openjdk/jdk/blob/master/src/hotspot/share/prims/stackwalk.cpp#L345

Ah, hm. Looking closer, I don't quite see why we even want to gate `OopMapCache` with GC checks. I asked Coleen in the bug here: [JDK-8331572](https://bugs.openjdk.org/browse/JDK-8331572).

**Comment by shipilev** [comment]
JDK-8331572 took another turn, so we don't need this. Feel free to reopen if need arises.

**Pull request closed without merging**
