### PR TITLE
8328556: Do not extract large CKO_SECRET_KEY keys from the NSS Software Token

### PR DESCRIPTION
**Pull request by martinuy**
Hi,

I'd like to propose a fix for "8328556: Do not extract large CKO_SECRET_KEY keys from the NSS Software Token". See more details in the JBS ticket [1].

No regressions observed in jdk/sun/security/pkcs11.

Thanks,
Martin.-

--
[1] - https://bugs.openjdk.org/browse/JDK-8328556

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328556](https://bugs.openjdk.org/browse/JDK-8328556): Do not extract large CKO_SECRET_KEY keys from the NSS Software Token (**Bug** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18389/head:pull/18389` \
`$ git checkout pull/18389`

Update a local copy of the PR: \
`$ git checkout pull/18389` \
`$ git pull https://git.openjdk.org/jdk.git pull/18389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18389`

View PR using the GUI difftool: \
`$ git pr show -t 18389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18389.diff">https://git.openjdk.org/jdk/pull/18389.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18389#issuecomment-2008618929)

### CODE REVIEW

**Comment by djelinski** [comment]
Would it be possible to add a regression test for this? I think you should be able to trigger a failure by calculating a HMAC using the same key two times.

**Comment by martinuy** [comment]
> Would it be possible to add a regression test for this? I think you should be able to trigger a failure by calculating a HMAC using the same key two times.

May be possible. To create a large secret key we can use a DH derivation + TLS pre-master generation trick as shown in the TestLargeKeys.java reproducer that I attached to JDK-8328556. Other attempts to create a large secret key may fail due to NSS checks. Then we would need to configure the NSS Software Token in FIPS mode. This is currently not supported by the PKCS11Test library, so we would need to extend it. Notice that there is currently one FIPS standalone test (FipsModeTLS12.java) but the right approach would be to do refactoring in PKCS11Test. The reason why FIPS mode is necessary is because, otherwise, the mechanism for rebuilding keys in the token would be C_CreateObject instead of C_UnwrapKey. Actually, it's not FIPS mode strictly what we need but keys with CKA_SENSITIVE = CK_TRUE. Perhaps we can modify the NSS configuration to set this attribute, but that would be a shortcut and the use case is better represented by FIPS mode. If there is interest in supporting FIPS scenarios, I can do this work. I didn't go this far in my proposal because this bug, in my view, is not very likely to be hit —as far as I know, it haven't been for years since the introduction of JDK-6913047— and the fix is trivial.

**Comment by martinuy** [comment]
Update: I found that an existing PKCS11Test configuration (p11-nss-sensitive.txt) sets CKA_SENSITIVE to CK_TRUE for secret keys. Combining this with the DH large secret key derivation trick led to a viable reproducer without having to introduce a FIPS configuration.

**Review by djelinski — APPROVED** [review]
Thanks for adding the test, the proposed changes look good to me.

**Pull request closed without merging**
