### PR TITLE
8329531: compiler/c2/irTests/TestIfMinMax.java fails with IRViolationException: There were one or multiple IR rule failures.

### PR DESCRIPTION
**Pull request by jaskarth**
This patch fixes an issue with the `TestIfMinMax` IR test where specific random seeds cause the branch probability to be so low that the branch cannot CMove, causing the IR check to fail for min/max reductions. For example, if the first value returned by `Random#nextInt` was `int_min` then the branch will be only taken once, which works out to `1/512 => ~0.002`. This value is smaller than the CMove threshold `0.01`, so it cannot CMove.
I've added sequential values from 1 to 50 and -1 to -50 before inserting random values in the array, so there will be a guaranteed 50 successes and 50 failures for each run. I've also replaced the multiplication by two with an opaque multiplication by one to prevent the randomly generated numbers from becoming larger, like what the test `MinMaxRed_Int` does.

Thoughts and reviews would be appreciated!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329531](https://bugs.openjdk.org/browse/JDK-8329531): compiler/c2/irTests/TestIfMinMax.java fails with IRViolationException: There were one or multiple IR rule failures. (**Bug** - P4)

### Reviewers
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)
 * [Damon Fenacci](https://openjdk.org/census#dfenacci) (@dafedafe - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18734/head:pull/18734` \
`$ git checkout pull/18734`

Update a local copy of the PR: \
`$ git checkout pull/18734` \
`$ git pull https://git.openjdk.org/jdk.git pull/18734/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18734`

View PR using the GUI difftool: \
`$ git pr show -t 18734`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18734.diff">https://git.openjdk.org/jdk/pull/18734.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18734#issuecomment-2048794818)

### CODE REVIEW

**Review by eme64 — APPROVED** [review]
Looks reasonable, thanks for the fix!

**Review by dafedafe — COMMENTED** [review]
Thanks for fixing this @jaskarth.
Quick question: I noticed that by setting `b[i] = 1;` now a few tests always set 1 on the right-hand-side of the max/min operations. Could it possibly limit their scope?

**Comment by jaskarth** [comment]
Thanks for the review @eme64, and thanks for taking a look @dafedafe! I think the scope of the tests shouldn't be limited by this change. The vectorization IR test is the only test that takes the 1s as the right hand argument, and I think functionally the it should behave the same as the true/false ratio will still be roughly equal before and after. Before we were comparing `rand_int < rand_int`, which is true roughly 50% of the time. Comparing against 1 it should still be true roughly 50% of the time since `nextInt()` distributes ints across the whole domain.

**Review by dafedafe — APPROVED** [review]

**Comment by jaskarth** [comment]
Thanks again for the reviews :)

/integrate

**Pull request closed without merging**
