### PR TITLE
8205129: Remove java.lang.Compiler

### PR DESCRIPTION
**Pull request by eirbjo**
Please help review this PR which suggests we remove the class `java.lang.Compiler`. The class seems non-functional for a decade, and was terminally deprecated in Java 9. Time has come to let it go.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8304458](https://bugs.openjdk.org/browse/JDK-8304458) to be approved

### Issues
 * [JDK-8205129](https://bugs.openjdk.org/browse/JDK-8205129): Remove java.lang.Compiler
 * [JDK-8304458](https://bugs.openjdk.org/browse/JDK-8304458): Remove java.lang.Compiler (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13092/head:pull/13092` \
`$ git checkout pull/13092`

Update a local copy of the PR: \
`$ git checkout pull/13092` \
`$ git pull https://git.openjdk.org/jdk.git pull/13092/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13092`

View PR using the GUI difftool: \
`$ git pr show -t 13092`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13092.diff">https://git.openjdk.org/jdk/pull/13092.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13092#issuecomment-1475184087)

### CODE REVIEW

**Comment by eirbjo** [comment]
The actual change in this PR seems trivial (simply removes a file), so I guess it is more useful to review the CSR and the release note:

https://bugs.openjdk.org/browse/JDK-8304458  (CSR)
https://bugs.openjdk.org/browse/JDK-8304459 (Release note)

**Comment by AlanBateman** [comment]
For reference, here's the discussion from 2016 when it was proposed to deprecate j.l.Compiler, for removal. Tim Ellison from IBM engaged in that discussion as one of the replies asked about applications running on the J9 VM using this API.
https://mail.openjdk.org/pipermail/core-libs-dev/2016-September/043365.html

The discussion is also a reminder that -Djava.compiler=NONE is the equivalent of -Xint, I thought that system property was dropped a long time ago.

**Comment by eirbjo** [comment]
> For reference, here's the discussion from 2016 when it was proposed to deprecate j.l.Compiler, for removal. Tim Ellison from IBM engaged in that discussion as one of the replies asked about applications running on the J9 VM using this API. 

So it seems in 2016 IBM in was ok with an eventual removal of this class ("these APIs can be removed without grief")

However, I see that later in the thread Azul Systems raised concerns about a removal:

https://mail.openjdk.org/pipermail/core-libs-dev/2016-September/043585.html
https://mail.openjdk.org/pipermail/core-libs-dev/2016-September/043646.html

Would be good if someone from Azul Systems could give a 2023 assessment on removing this class? 


> The discussion is also a reminder that -Djava.compiler=NONE is the equivalent of -Xint, I thought that system property was dropped a long time ago.

It exists in System.getProperties Javadocs at least:

```
     * <tr><th scope="row">{@systemProperty java.compiler}</th>
     *     <td>Name of JIT compiler to use</td></tr>
```

Was this just for reference or are you suggesting that this PR is blocked by the 'java.compiler' somehow?

**Comment by eirbjo** [comment]
> The discussion is also a reminder that -Djava.compiler=NONE is the equivalent of -Xint, I thought that system property was dropped a long time ago.

https://bugs.openjdk.org/browse/JDK-8041676 suggests to deprecate it, but from the last comment we still seem to be waiting for @dholmes-ora to get back from vacation on the 22nd :-)

**Comment by AlanBateman** [comment]
A search of 3M classes in 130k artifacts found just 8 references to this class. 6 of the 8 are versions of the same thing seem to be an off-label usage in a class named net.openhft.chronicle.core.Jvm where it calls Compiler.enable() instead of Thread.onSpinWait on older JDK releases.

I remember the Azul mails from 2016 on this topic but I don't think they provided sufficient insight why an application would using this barely documented API. Anything relying on these methods to do something is probably very tied to the VM implementation.

-Djava.compiler=NONE pre-dates "full speed debugging" and I would think all traces can be removed now. Yes, there is still a reference to this system property in System.getProperties that could be looked at too. All of these things are low priority. The good thing about removing java.lang.Compiler is that is avoids new developers from stumbling on it.

**Comment by dholmes-ora** [comment]
> > The discussion is also a reminder that -Djava.compiler=NONE is the equivalent of -Xint, I thought that system property was dropped a long time ago.
> 
> https://bugs.openjdk.org/browse/JDK-8041676 suggests to deprecate it, but from the last comment we still seem to be waiting for @dholmes-ora to get back from vacation on the 22nd :-)

I guess I never heard back from @stuart-marks . :( I think [JDK-8041676](https://bugs.openjdk.org/browse/JDK-8041676) needs to be resolved along side this issue.

**Comment by eirbjo** [comment]
I noticed there are quite a few uses of `-Djava.compiler=none` in the demo netbeans project/build files.

I have filed #13101 and #13098 to take care of those usages.

**Comment by stuart-marks** [comment]
I don't know how much interdependency there is between the `java.compiler` system property and the `java.lang.Compiler` class. On the library side I think they're independent. But it sounds like @dholmes-ora thinks they should be resolved at the same time, so maybe there some things going on between them inside the JVM.

The `java.compiler` property still seems to have some actual effect (see src/hotspot/share/runtime/arguments.cpp) so it shouldn't be removed immediately. Instead, it needs to be deprecated and its use should cause a warning to be issued. A comment in that file also mentions `-Xdebug`. The Hotspot help message for that says

    -Xdebug           does nothing. Provided for backward compatibility.

which doesn't appear to be true, as `-Xdebug` seems to have an effect on the interpretation of the `java.compiler` property! Ugh. Well, this appears to be the only effect of `-Xdebug`, so maybe the eventual removal of the `java.compiler` property will make the help message become true.

Anyway it sounds to me like the next step is to deprecate the `java.compiler` property and to have setting it cause a warning to be issued. If @dholmes-ora thinks that removal of `java.lang.Compiler` should wait until after that, I'm ok with it.

P.S. I note that I am finally getting back to @dholmes-ora on this issue, and it is in fact after he has returned from vacation on the 22nd. :-)

**Comment by dholmes-ora** [comment]
> I don't know how much interdependency there is between the java.compiler system property and the java.lang.Compiler class. 
> On the library side I think they're independent.

That may be true today but originally they were very much inter-dependent:
```
/**
 * The <code>Compiler</code> class is provided to support
 * Java-to-native-code compilers and related services. By design, the
 * <code>Compiler</code> class does nothing; it serves as a
 * placeholder for a JIT compiler implementation.
 * <p>
 * When the Java Virtual Machine first starts, it determines if the
 * system property <code>java.compiler</code> exists. (System
 * properties are accessible through <code>getProperty</code>  and ,
 * a method defined by the <code>System</code> class.) If so, it is
 * assumed to be the name of a library (with a platform-dependent
 * exact location and type); the <code>loadLibrary</code> method in
 * class <code>System</code> is called to load that library. If this
 * loading succeeds, the function named
 * <code>java_lang_Compiler_start()</code> in that library is called.
 * <p>
 * If no compiler is available, these methods do nothing.
```
The only part of that we have left today is that `-Djava.compiler=NONE` is an alias for `-Xint` mode.

JDK 9 effectively severed the class from the property by removing the above wording, so in that sense the two issues can be addressed separately. We should have handled the property deprecation back in JDK 9 too (not that there is an actual definition/process of deprecating system properties).

P.S I will try not to take any vacation until after this is resolved. :)

**Comment by dholmes-ora** [comment]
>The only part of that we have left today is that -Djava.compiler=NONE is an alias for -Xint mode.

Edit: ... unless `-Xdebug` is specified in which case it is ignored.

**Comment by AlanBateman** [comment]
I think you should be able to finalize the CSR JDK-8304458.

I think it would be good to remove "java.compiler" from the list of standard properties (table in System.getProperties) in the same release.

**Comment by eirbjo** [comment]
> I think you should be able to finalize the CSR JDK-8304458.

Thanks for the gentle nudge, Alan.

I was actually not aware that finalization could be initiated by the assignee! I've seen the CSR lead handle this workflow previously. I pressed the "Finalize" button.

> I think it would be good to remove "java.compiler" from the list of standard properties (table in System.getProperties) in the same release.

Yes, these seem closely related.

**Comment by eirbjo** [comment]
The CSR for this PR has now been approved.

@jddarcy comments in the CSR:

> Per comments in the PR, please link to any follow-up bugs to remove java.compiler support.

My guess is the "comment" here refers to @AlanBateman comment above that it would be good to handle the removal of -Djava.compiler in the same release:

> I think it would be good to remove "java.compiler" from the list of standard properties (table in System.getProperties) in the same release.

I have linked to [JDK-8041676](https://bugs.openjdk.org/browse/JDK-8041676), even though that issue strictly describes the deprecation of -Djava.compiler, not the removal.

I think what I'm trying to express here is that it's ok to refer to  [JDK-8041676](https://bugs.openjdk.org/browse/JDK-8041676) for the task that deals with the `java.compiler` system property. And that we should take care of [JDK-8041676](https://bugs.openjdk.org/browse/JDK-8041676) in the same release as this PR.

**Comment by eirbjo** [comment]
The CSR for this PR has been approved for a while now. The PR is still looking for reviewers.

I know the change itself is not a very exciting one to review, it is after all just a file being deleted. But we still need a reviewer to approve it :-)

**Review by AlanBateman — APPROVED** [review]

**Comment by eirbjo** [comment]
Good riddance.

/integrate

**Comment by eirbjo** [comment]
This PR is daydreaming about  a sponsor walking by.

**Comment by jaikiran** [comment]
Hello Eirik, I'll run this against our CI just to be sure and if things go fine, will sponsor this.

**Review by jaikiran — APPROVED** [review]

**Comment by eirbjo** [comment]
The Release Note for this PR did not receive any comments.

It would be good if a Reviewer can take a look at the release note and see if it is conforming to the desired style:

https://bugs.openjdk.org/browse/JDK-8304459

Thanks!

**Pull request closed without merging**
