### PR TITLE
8264639: SA: Worker thread for ptrace on Linux should be more robustness

### PR DESCRIPTION
**Pull request by YaSuenag**
LinuxDebuggerLocal has worker thread (LinuxDebuggerLocalWorkerThread) to call ptrace(2) because it have to call from same thread.

LinuxDebuggerLocalWorkerThread does not have queue, so it depends on synchronized statement as following:

https://github.com/openjdk/jdk/blob/66d9961cbd83dbfca20b0af3c20693438d4aff3f/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/LinuxDebuggerLocal.java#L156-L192

If `execute()` is called in same time, `task` would be broken.
Fortunately all of caller of `execute()` are guarded with `synchronized` now. But task worker should be more robustness.

I used `Executors::newSingleThreadExecutor`, so we don't need to take care task queue.

I tested this change with serviceability/sa jtreg tests on Linux x64.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8264639](https://bugs.openjdk.java.net/browse/JDK-8264639): SA: Worker thread for ptrace on Linux should be more robustness

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3321/head:pull/3321` \
`$ git checkout pull/3321`

Update a local copy of the PR: \
`$ git checkout pull/3321` \
`$ git pull https://git.openjdk.java.net/jdk pull/3321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3321`

View PR using the GUI difftool: \
`$ git pr show -t 3321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3321.diff">https://git.openjdk.java.net/jdk/pull/3321.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — COMMENTED** [review]
My first reaction to these changes is that they are fairly extensive, will take a lot of reviewing time, and don't seem to actually fix something that in real life is an issue. So I'm unsure of your motivation for all the work put into this issue.

**Comment by YaSuenag** [comment]
> I'm unsure of your motivation for all the work put into this issue.

When I modified LinuxDebuggerLocal to add ptrace accessor, I couldn't understand why the method should be qualified `synchronized`. ptrace caller should only one thread, so I understand the need of worker thread.
The comment of WorkerThreadTask says the need of worker thread, but it does not mention the caller should be synchronized.

We can just add the comment of course, but we can simplify the worker with modern API. We might add new worker tasks in future, so I thought it's better to refactor in this opportunity.

For example, following the current approach, we need to add new worker task in below:

```
class CreateDwarfParserTask implements WorkerThreadTask {
    DwarfParser result;
    public void doit(LinuxDebuggerLocal debugger) {
        result = new DwarfParser(libptr, rip, rbp, rsp, debugger);
    }
}

CreateDwarfParserTask task = new CreateDwarfParserTask();
workerThread.execute(task);
return task.result;
```

But we can simplify it after this PR:

```
try {
    return ptraceWorkerThreadPool.submit(() -> new DwarfParser(libptr, rip, rbp, rsp, LinuxDebuggerLocal.this))
                                 .get();
} catch (InterruptedException | ExecutionException e) {
    throw new DebuggerException(e);
}
```

This PR will take a lot of reviewing time as you said. If it does not worth to work, I want to add the comment about `synchronized` at least.

**Comment by plummercj** [comment]
Can't this issue also be fixed by simply making `execute()` synchronized? Then you don't need to worry about the caller being synchronized.

My suggestion would to not make this change at this point, since it's not addressing an actual bug the user can run into. You can add documentation in the code, which can also reference the CR. The CR should be changed to an RFE, and for now closed as "Will Not Fix". You can archive a reference to your current change from the CR in case there ever becomes a real need to address this. Does that sound ok?

**Comment by YaSuenag** [comment]
Ok, I will change issue type to RFE, and will close both it and PR.

**Pull request closed without merging**
