### PR TITLE
8318646: Integer#parseInt("") throws empty NumberFormatException message

### PR DESCRIPTION
**Pull request by rgiulietti**
Please review this simple fix to restore the original exception message that existed before [16050](https://github.com/openjdk/jdk/pull/16050).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318646](https://bugs.openjdk.org/browse/JDK-8318646): Integer#parseInt("") throws empty NumberFormatException message (**Enhancement** - P4)

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)
 * [Uwe Schindler](https://openjdk.org/census#uschindler) (@uschindler - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16320/head:pull/16320` \
`$ git checkout pull/16320`

Update a local copy of the PR: \
`$ git checkout pull/16320` \
`$ git pull https://git.openjdk.org/jdk.git pull/16320/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16320`

View PR using the GUI difftool: \
`$ git pr show -t 16320`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16320.diff">https://git.openjdk.org/jdk/pull/16320.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16320#issuecomment-1775747643)

### CODE REVIEW

**Review by cl4es — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]

**Review by bplb — APPROVED** [review]
+1

**Review by jddarcy — APPROVED** [review]

**Review by uschindler — APPROVED** [review]

**Comment by rgiulietti** [comment]
@uschindler You may want to make the Lucene tests more robust by making them immune to exception messages contents.

But thanks for trying out the EA releases on important libraries like Lucene ;-) It is important to have early feedback to gain more information before shipping the GA release.

**Comment by uschindler** [comment]
> @uschindler You may want to make the Lucene tests more robust by making them immune to exception messages contents.
> 
> But thanks for trying out the EA releases on important libraries like Lucene ;-) It is important to have early feedback to gain more information before shipping the GA release.

Thanks for this. Actually this was a bad example. This was just test code, so I will more or less only remove the message check. In that case it would be enough to check for the NumberFormatException. I will provide a fix for this.

This is a very old test from a not so well-maintained module. Anyways it helped a bit to make the code more clean, because the NumberFormatException is now generated in the same way everywhere which makes it more consistent.

I mainly openend the iusse to inform you about that incompatibility because the exception message looks the same since very early java versions. So suddenly chaging it might bring others into the same situation like we were. I agree the spec does not enforce a message, but a more helpful message is always better than the completely empty one. So I would say, this PR is just a cleanup so "enhancement" as said by Alan Bateman is a good categorization.

Thanks for the quick fix. But I will fix the issue in Lucene, too!

P.S.: At other code we do not rely on exception messages. In recent code of MemorySegment we have some ambiguity with IllegalStateException when the scope of a memory segment was closed. I refused to look into the exception message and instead of parsing mesage, when catching exception, I checked if the memorysegment's scope was closed and only then convert the exception to a Lucene "AlreadyClosedException". In all other cases it was rethrowing the original exception. With exception messages you would have to look for some text string in them which is fragile. See this example: https://github.com/apache/lucene/pull/12707

**Pull request closed without merging**
