### PR TITLE
8295173: (tz) Update Timezone Data to 2022e

### PR DESCRIPTION
**Pull request by alvdavi**
Please, review this PR for an update of timezone data. No changes besides the import were needed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295173](https://bugs.openjdk.org/browse/JDK-8295173): (tz) Update Timezone Data to 2022e

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10666/head:pull/10666` \
`$ git checkout pull/10666`

Update a local copy of the PR: \
`$ git checkout pull/10666` \
`$ git pull https://git.openjdk.org/jdk pull/10666/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10666`

View PR using the GUI difftool: \
`$ git pr show -t 10666`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10666.diff">https://git.openjdk.org/jdk/pull/10666.diff</a>

</details>

### CODE REVIEW

**Comment by alvdavi** [comment]
Thanks for the explanation!. I've run that Makefile and i can see the new files, including a displaynames.txt that matches what you're sending. I will update this PR with the proper change

**Review by naotoj — APPROVED** [review]
Looks good. Thanks for the fix.

**Pull request closed without merging**
