### PR TITLE
8270061: Change parameter order of ResourceHashtable

### PR DESCRIPTION
**Pull request by iklam**
The template parameter for ResourceHashtable is currently in this order:
```
template<
    typename K, typename V,
    unsigned (*HASH)  (K const&)           = primitive_hash<K>,
    bool     (*EQUALS)(K const&, K const&) = primitive_equals<K>,
    unsigned SIZE = 256,
    ResourceObj::allocation_type ALLOC_TYPE = ResourceObj::RESOURCE_AREA,
    MEMFLAGS MEM_TYPE = mtInternal
    >
class ResourceHashtable {...}
```

However, more often than not, default values of `HASH` and `EQUALS` will be used, where the other parameters may need to be specified.

We should move the `HASH` and `EQUALS` parameters to the end of the parameter list.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270061](https://bugs.openjdk.java.net/browse/JDK-8270061): Change parameter order of ResourceHashtable

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to dd6afc8ff2f91b90a0dd8a7427d4cf8b6b0e2dda
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to dd6afc8ff2f91b90a0dd8a7427d4cf8b6b0e2dda

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4912/head:pull/4912` \
`$ git checkout pull/4912`

Update a local copy of the PR: \
`$ git checkout pull/4912` \
`$ git pull https://git.openjdk.java.net/jdk pull/4912/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4912`

View PR using the GUI difftool: \
`$ git pr show -t 4912`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4912.diff">https://git.openjdk.java.net/jdk/pull/4912.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good.  Thanks for doing this!

**Review by tstuefe — APPROVED** [review]
Looks good.

One could save even more writing by some more reordering: move MEMFLAGS upfront, since its is usually specified, and make the default allocator C_HEAP, because more users seem to want a C-heap map than a resource area one.

But this is just idle nitpicking, the change is good as it is.

..Thomas

**Comment by coleenp** [comment]
Oh but MEMFLAGS is generally found after the allocation type and I thought there were more resource allocated resource hashtables (at least initially).

**Comment by iklam** [comment]
> Oh but MEMFLAGS is generally found after the allocation type and I thought there were more resource allocated resource hashtables (at least initially).

OK, I'll leave the PR as is without further rearranging the arguments.

Since the class is named ResourceHashtable, using C_HEAP as the default seems a little weird. We are planning to get rid of the "old" Hashtable and then rename ResourceHashtable to Hashtable. We can rethink the default values at that point.

**Comment by tstuefe** [comment]
> > Oh but MEMFLAGS is generally found after the allocation type and I thought there were more resource allocated resource hashtables (at least initially).
> 
> OK, I'll leave the PR as is without further rearranging the arguments.
> 
> Since the class is named ResourceHashtable, using C_HEAP as the default seems a little weird. We are planning to get rid of the "old" Hashtable and then rename ResourceHashtable to Hashtable. We can rethink the default values at that point.

Sure, all good!

**Comment by iklam** [comment]
Thanks @coleenp and @tstuefe for the review.
/integrate

**Pull request closed without merging**
