### PR TITLE
JDK-8325841 - Remove unused references to vmSymbols.hpp

### PR DESCRIPTION
**Pull request by JohnTortugo**
Can I please get some reviews for this change to remove unused names from `vmSymbols.hpp`?

As far as I can tell there is nothing in the code base using these symbols. My search was just a simple grep + some bash script, though. I tested using JTREG on MacOS, Linux Mariner & Alpine from tier1 to 3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325841](https://bugs.openjdk.org/browse/JDK-8325841): Remove unused references to vmSymbols.hpp (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19374/head:pull/19374` \
`$ git checkout pull/19374`

Update a local copy of the PR: \
`$ git checkout pull/19374` \
`$ git pull https://git.openjdk.org/jdk.git pull/19374/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19374`

View PR using the GUI difftool: \
`$ git pr show -t 19374`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19374.diff">https://git.openjdk.org/jdk/pull/19374.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19374#issuecomment-2128080878)

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Subject and description in JBS have to be updated since you removed not only newInstance0.

**Comment by vnkozlov** [comment]
Why GHA testing is not triggered?

**Comment by JohnTortugo** [comment]
> Why GHA testing is not triggered?

I don't know. Maybe it has something to do with the Microsoft fork? It's the only thing I did different in this PR.

**Comment by JohnTortugo** [comment]
@vnkozlov - I'm investigating this GHA issue on my side.

**Comment by vnkozlov** [comment]
I submitted our testing.

**Comment by JohnTortugo** [comment]
GHZ is fixed now. It was a security/configuration issue in our repo.

**Review by vnkozlov — APPROVED** [review]
My testing (tier1 and various build configurations) passed.

**Comment by JohnTortugo** [comment]
Thank you @vnkozlov .

**Review by coleenp — APPROVED** [review]
This looks good.  Hotspot rules are that you need two reviewers before integrating.

**Pull request closed without merging**
