### PR TITLE
8278584: compiler/vectorapi/VectorMaskLoadStoreTest.java failed with "Error: ShouldNotReachHere()"

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

I'd like to fix the vector_length_encoding error in `long_to_maskLE8_avx` and `long_to_maskGT8_avx`.
Since the input parameter of `vector_length_encoding` [1] is the number of vector bytes (not number of vector bits), I believe we shouldn't `mask_len*8` [2][3].

The patch also removes an useless statement [4].

Testing:
   - vector api tests on Linux/x64-{AVX512, AVX2}

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L1219
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L9552
[3] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L9568
[4] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/x86.ad#L9580

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278584](https://bugs.openjdk.java.net/browse/JDK-8278584): compiler/vectorapi/VectorMaskLoadStoreTest.java failed with "Error: ShouldNotReachHere()"

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 579363d8e161d343559141f8a54e619864bf7db4
 * @merykitty (no known github.com user name / role) ⚠️ Review applies to 579363d8e161d343559141f8a54e619864bf7db4
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6808/head:pull/6808` \
`$ git checkout pull/6808`

Update a local copy of the PR: \
`$ git checkout pull/6808` \
`$ git pull https://git.openjdk.java.net/jdk pull/6808/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6808`

View PR using the GUI difftool: \
`$ git pr show -t 6808`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6808.diff">https://git.openjdk.java.net/jdk/pull/6808.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
@jatin-bhateja should review it too.

My main question why we did not catch this in #6646 pre-integration testing?
The test failed only when we run it with `-Xcomp -XX:+DeoptimizeALot` flags running on AVX2 machines. which indicates that these instructions are not used during normal execution of this test or any tests in `jdk/incubator/vector`

@DamonFool, how you trigger failure with the test? May be we should increase NUM_ITER (which is only 5000) to actually trigger C2 compilation with normal execution.

@jatin-bhateja why there are no `jdk/incubator/vector` tests which use these instruction? And if there are why they are not triggered this failure during normal execution?

**Comment by vnkozlov** [comment]
I noticed that the test also uses `-XX:CompileThreshold=100` so `NUM_ITER = 5000` should be enough. So why?

**Comment by merykitty** [comment]
It seems that our `fromLong` tests create a mask from `long` values then immediately convert it back to `long` values using `toLong` to verify the results. Unfortunately, a `VectorMaskToLongNode` and a `VectorLongToMaskNode` together being optimized out leads to us not being able to verify the code emission.

**Comment by vnkozlov** [comment]
To clarify, I want this fix update tests so that the case like this is triggered during normal execution (no '-Xcomp` required).

**Comment by DamonFool** [comment]
> To clarify, I want this fix update tests so that the case like this is triggered during normal execution (no '-Xcomp` required).

Done.

Thanks @vnkozlov and @merykitty for your review.

**Comment by merykitty** [comment]
Hi, we currently don't have any tests to verify the correctness of the generated code. Also, you could modify the current tests in `jdk/incubator/vector/*VectorTests.java` and `compiler/vectorapi/VectorMaskLoadStoreTest.java` since they are effectively don't do anything regarding compiled codes under normal execution.

**Comment by DamonFool** [comment]
> Hi, we currently don't have any tests to verify the correctness of the generated code. 

Hi @merykitty , the problem is that if I verify the results, the bug won't be triggered without `-Xcomp`.
So do you have any idea to reproduce this bug while keeping the verification?

>Also, you could modify the current tests in `jdk/incubator/vector/*VectorTests.java` and `compiler/vectorapi/VectorMaskLoadStoreTest.java` since they are effectively don't do anything regarding compiled codes under normal execution.

This test is actually made from `compiler/vectorapi/VectorMaskLoadStoreTest.java` by removing the results checking logic.

**Comment by DamonFool** [comment]
> Hi, we currently don't have any tests to verify the correctness of the generated code. Also, you could modify the current tests in `jdk/incubator/vector/*VectorTests.java` and `compiler/vectorapi/VectorMaskLoadStoreTest.java` since they are effectively don't do anything regarding compiled codes under normal execution.

Hi @merykitty 
After more experiments, I finally found a way to reproduce this bug without `-Xcomp` and keeping the verification by modifying `compiler/vectorapi/VectorMaskLoadStoreTest.java`.
Please review it.
Thanks.

**Comment by DamonFool** [comment]
> Hi, unfortunately, the tests still don't verify the correctness of the compiled codes, what happened here is that the `IfNode` always goes in one direction make the other path an uncommon trap, the uncommon trap captures all nodes before it including the `VectorLongToMaskNode`, thus throw `ShouldNotReachHere` when trying to emit instructions. The result of the `VectorLongToMaskNode`, however, is only used to feed into the uncommon trap and not used in verification at all.

Nice catch! @merykitty 
What do you think of the update version? 
Thanks.

**Review by merykitty — APPROVED** [review]
Elegant, indeed!

**Review by vnkozlov — APPROVED** [review]
Test's change is clever! Good.

**Comment by PaulSandoz** [comment]
@DamonFool neat test fix, could you add a brief comment as to why disabling `_VectorMaskOp` is required?

**Comment by DamonFool** [comment]
> @DamonFool neat test fix, could you add a brief comment as to why disabling `_VectorMaskOp` is required?

Thanks @PaulSandoz for your testing.

The comment had been added.
Thanks.

**Review by PaulSandoz — APPROVED** [review]

**Comment by DamonFool** [comment]
Thank you all for the review and comment.

@jatin-bhateja , are you OK with the fix?
Will push it tomorrow if there is no objection.
Thanks.

**Pull request closed without merging**
