### PR TITLE
8336242: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleDebugInfoTest.java failed assert(oopDesc::is_oop_or_null(val)) failed: bad oop found (again)

### PR DESCRIPTION
**Pull request by davleopo**
This PR removes the Object based tests from SimpleDebugInfoTests.

These assembler tests are hard to maintain in the context of changes to nmethod entry barriers.
Downstream Graal testing provides sufficient coverage to ensure correctness wrt DebugInfo usage.

See the full discussion history here
https://github.com/openjdk/jdk/pull/19035#issuecomment-2092543435

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336242](https://bugs.openjdk.org/browse/JDK-8336242): compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleDebugInfoTest.java failed assert(oopDesc::is_oop_or_null(val)) failed: bad oop found (again) (**Bug** - P3)

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - **Reviewer**)
 * @abdelhak-zaaim (no known openjdk.org user name / role)
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20389/head:pull/20389` \
`$ git checkout pull/20389`

Update a local copy of the PR: \
`$ git checkout pull/20389` \
`$ git pull https://git.openjdk.org/jdk.git pull/20389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20389`

View PR using the GUI difftool: \
`$ git pr show -t 20389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20389.diff">https://git.openjdk.org/jdk/pull/20389.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20389#issuecomment-2258500466)

### CODE REVIEW

**Comment by davleopo** [comment]
@dougxc  @tkrodriguez  review ping

**Review by dougxc — APPROVED** [review]
LGTM

**Review by abdelhak-zaaim — APPROVED** [review]

**Review by tkrodriguez — APPROVED** [review]

**Pull request closed without merging**
