### PR TITLE
8255441: Cleanup ciEnv/jvmciEnv::lookup_method-s

### PR DESCRIPTION
**Pull request by shipilev**
Static analysis complains there is a potentially uninitialized `dest_method` after the switch, oblivious of `ShouldNotReachHere()`. This can be cleaned up along with related code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255441](https://bugs.openjdk.java.net/browse/JDK-8255441): Cleanup ciEnv/jvmciEnv::lookup_method-s

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/875/head:pull/875`
`$ git checkout pull/875`

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Can you use fatal() and print unexpected `bc` instead of SNRH()?

**Comment by shipilev** [comment]
> Can you use fatal() and print unexpected `bc` instead of SNRH()?

Righto. See new version.

**Review by vnkozlov — APPROVED** [review]
Good.

**Pull request closed without merging**
