### PR TITLE
Make the compiler/sharedstubs/SharedTrampolineTest.java require C2 explicitly

### PR DESCRIPTION
**Pull request by lepestock**
The test seem to only work with C2. A previous change to the test, the JDK-8314838, allowed for passing JVM arguments to the child process. However, if those parameters change the compiler used, the test fails.

This PR makes this requirement (to have C2 as compiler) explicit.

Testing: runs with '-XX:TieredStopAtLevel=3' with old version (failed), fixed version (skipped) and with new version but no additional arguments (passed).

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16258/head:pull/16258` \
`$ git checkout pull/16258`

Update a local copy of the PR: \
`$ git checkout pull/16258` \
`$ git pull https://git.openjdk.org/jdk.git pull/16258/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16258`

View PR using the GUI difftool: \
`$ git pr show -t 16258`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16258.diff">https://git.openjdk.org/jdk/pull/16258.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16258#issuecomment-1770155732)

### CODE REVIEW

**Comment by TobiHartmann** [comment]
You need to remove the test from the problem list (there's also a PR title mismatch). Looking at https://github.com/openjdk/jdk/pull/15609, I thought that the intention was to pass `-XX:-TieredCompilation` to the sub-process, right? Wouldn't that fix the issue as well and doesn't that suggest that https://github.com/openjdk/jdk/pull/15609 does not work as intended?

**Comment by lepestock** [comment]
> You need to remove the test from the problem list
Fixed, thanks.

> (there's also a PR title mismatch)
Fixed.

> #15609 does not work as intended?
The purpose of the previous PR was to enable forwarding of the additional arguments (like -Xcomp, stress options, whatever) to the child process, this does work now.

> I thought that the intention was to pass -XX:-TieredCompilation to the sub-process, right?
Well, the author intention was, I guess, to disable C1 and always work with C2 and tier 4. This is done now. However, it was possible to override that, AFAIU, by providing additional (even conflicting) TierStopAtLevel's, etc - which is causing the failures.

This PR simply states that the test does require C2 and if user adds some conflicting arguments breaking this assumption, the test would simply be skipped.

**Comment by lepestock** [comment]
> Where is the -XX:-TieredCompilation used or passed to?

Yes, you're right. It's never used. Well, the VM seems to go to tier4 straight, and test doesn't fail :). I thought '-XX:-TieredCompilation' gets picked up by `ProcessTools.createTestJvm`, but i doesn't. Fixed now.

**Comment by lepestock** [comment]
... and SharedStubToInterpTest.java needs to get fixed as well...

**Comment by lepestock** [comment]
Closed in favor of the #16277.

**Pull request closed without merging**
