### PR TITLE
8253060: remove test/hotspot/jtreg/test_env.sh

### PR DESCRIPTION
**Pull request by iignatev**
[JDK-8252402](https://bugs.openjdk.java.net/browse/JDK-8252402) removed the last shell test from `test/hotspot/jtreg`, and now `test_env.sh` can be removed so it won't trick anyone into believing that shell tests are acceptable/desirable/supported in hotspot testbase.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253060](https://bugs.openjdk.java.net/browse/JDK-8253060): remove test/hotspot/jtreg/test_env.sh

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/132/head:pull/132`
`$ git checkout pull/132`

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Simple file removal so this is a trivial change.

**Comment by iignatev** [comment]
Thanks, Dan!

**Pull request closed without merging**
