### PR TITLE
8308892: Bad graph detected in build_loop_late after JDK-8305635

### PR DESCRIPTION
**Pull request by chhagedorn**
The cleanup done in [JDK-8305635](https://bugs.openjdk.org/browse/JDK-8305635) wrongly identifies unrelated Parse Predicates which are not cleaned up, yet. It just walks from the entry of the loop up and tries to find each of the three Parse Predicates once but in no particular order. This order insensitive walk is wrong as seen in the following graph (from the attached replay file of this bug):

image

We first find `116 Parse Predicate` for Loop Predicates, then `84 Parse Predicate` for Profiled Loop Predicates and then stop when finding `71 Parse Predicate` for Loop Predicates because we've already found a Parse Predicate for Loop Predicates already. We then wrongly create Loop Predicates (above `116 Parse Predicate`) which are below newly created Profiled Loop Predicates (above `84 Parse Predicate`). This could lead to a bad graph because of data dependencies that rely on the fact that Loop Predicates are above Profiled Loop Predicates:
https://github.com/openjdk/jdk/blob/547a8b40b324917e66c71409b31421feacce79d7/src/hotspot/share/opto/loopPredicate.cpp#L1529-L1543

The fix is straight forward to make the assignment of Parse Predicate projections in `ParsePredicates` aware of the relative ordering constraint. Note that this class will be refactored again in [JDK-8305636](https://bugs.openjdk.org/browse/JDK-8305636). But I think properly fixing this first is better than waiting for JDK-8305636 to go in.

Testing: tier1-4, hs-precheckin-comp, hs-stress-comp

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308892](https://bugs.openjdk.org/browse/JDK-8308892): Bad graph detected in build_loop_late after JDK-8305635

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**) ⚠️ Review applies to [806bdba5](https://git.openjdk.org/jdk/pull/14196/files/806bdba5c47622c1e060f041e0ea3983161770ed)
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14196/head:pull/14196` \
`$ git checkout pull/14196`

Update a local copy of the PR: \
`$ git checkout pull/14196` \
`$ git pull https://git.openjdk.org/jdk.git pull/14196/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14196`

View PR using the GUI difftool: \
`$ git pr show -t 14196`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14196.diff">https://git.openjdk.org/jdk/pull/14196.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14196#issuecomment-1566282531)

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good!

Windows build failure in GHA testing is unrelated.

**Comment by chhagedorn** [comment]
Thanks Roberto for your review!

**Comment by rwestrel** [comment]
> The cleanup done in [JDK-8305635](https://bugs.openjdk.org/browse/JDK-8305635) wrongly identifies unrelated Parse Predicates which are not cleaned up, yet.

So which of the 3 predicates will get cleaned up? Are some of the 3 predicates for another loop that doesn't exist anymore?

**Comment by rwestrel** [comment]
> The useless predicates were added normally for the loop while the additional `116 Parse Predicate` was added with `maybe_add_predicate_after_if()` (the profiled loop predicate was skipped due to `too_may_trap(reason)` being true).

Do I read that correctly that parsing inserts useless/duplicate predicates?

**Comment by chhagedorn** [comment]
After the first IGVN round, after parsing, they become useless because the `If` that triggered the insertion of the predicates with `maybe_add_predicate_after_if()` is folded away. I think it's unfortunate, though, that we eliminate `71 Parse Predicate` and `84 Parse Predicate` instead of `116 Parse Predicate` (so, we cannot add profiled loop predicates anymore). But that might be an edge case.

**Comment by rwestrel** [comment]
Thanks for the explanation. Can a test case be added?

**Comment by chhagedorn** [comment]
Thanks Roland for your review!

I was able to come up with a test that fails with the same graph pattern. I've pushed an update.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by chhagedorn** [comment]
Thanks Tobias for your review! I've simplified the test some more but the fix remains the same.

**Review by TobiHartmann — APPROVED** [review]
Still looks good.

**Pull request closed without merging**
