### PR TITLE
8321468: Remove StringUTF16::equals

### PR DESCRIPTION
**Pull request by cl4es**
https://bugs.openjdk.org/browse/JDK-8215017 removed the only use of `StringUTF16::equals`. At the time I did some performance verification focused on x86 showing that simplifying and only using `StringLatin1::equals` was either neutral or a win. 

I repeated this experiment recently, adding some focused tests on aarch64 where the code generation actually tries to take advantage and generate slightly more efficient code for `StringUTF16::equals`: 
https://github.com/openjdk/jdk/pull/16933#discussion_r1414118658

The indication here is that disabling use of `StringUTF16::equals` was the right choice: any effect from the low-level optimization (one less branch at the tail end) was offset by the `isLatin1()` branch and added code generation (that all gets inlined).

In a `-XX:-CompactStrings` configuration the slightly improved code generation in `StringUTF16::equals` might help, since the `isLatin1()` test and subsequent call to `StringLatin1::equals` would be DCEd. To get the best of both worlds the code in `String::equals` _could_ be sharpened so that we statically pick the best implementation based on `CompactStrings` mode (see comment below). This shows a tiny win when testing with `-XX:-CompactStrings` on M1 (up to -0.2ns/op per `String::equals`; neutral on x86). But is all this complexity worth it for a gain that will get lost in the noise on anything realistic?

This PR instead proposes removing `StringUTF16::equals` and simplifying the mechanisms to support the `StringLatin1/UTF16::equals` pair of intrinsics in hotspot.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321468](https://bugs.openjdk.org/browse/JDK-8321468): Remove StringUTF16::equals (**Enhancement** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16995/head:pull/16995` \
`$ git checkout pull/16995`

Update a local copy of the PR: \
`$ git checkout pull/16995` \
`$ git pull https://git.openjdk.org/jdk.git pull/16995/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16995`

View PR using the GUI difftool: \
`$ git pr show -t 16995`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16995.diff">https://git.openjdk.org/jdk/pull/16995.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16995#issuecomment-1845132291)

### CODE REVIEW

**Comment by cl4es** [comment]
M1 experiment with `-XX:-CompactStrings` and a patch to choose the `StringUTF16::equals` if `COMPACT_STRINGS` is false[1]:
```
Name                          Cnt  Base   Error   Test   Error  Unit  Change
StringEquals.equalsUTF16_3_EQ   5 1,799 ± 0,008  1,585 ± 0,009 ns/op   1,14x (p = 0,000*)
StringEquals.equalsUTF16_3_NE   5 1,622 ± 0,007  1,541 ± 0,011 ns/op   1,05x (p = 0,000*)
  * = significant
```

[1] 
```java
diff --git a/src/java.base/share/classes/java/lang/String.java b/src/java.base/share/classes/java/lang/String.java
index 5869e086191..10451bda83f 100644
--- a/src/java.base/share/classes/java/lang/String.java
+++ b/src/java.base/share/classes/java/lang/String.java
@@ -1900,9 +1900,14 @@ public boolean equals(Object anObject) {
         if (this == anObject) {
             return true;
         }
-        return (anObject instanceof String aString)
-                && (!COMPACT_STRINGS || this.coder == aString.coder)
-                && StringLatin1.equals(value, aString.value);
+        if (anObject instanceof String aString) {
+            if (COMPACT_STRINGS) {
+                return this.coder == aString.coder && StringLatin1.equals(value, aString.value);
+            } else {
+                return StringUTF16.equals(value, aString.value);
+            }
+        }
+        return false;
     }

     /**
```

**Comment by cl4es** [comment]
Can I please get a review for this cleanup?

This PR does not cause a regression to `-XX:-CompactStrings`; a very minor regression as detailed in comments was caused by (https://bugs.openjdk.org/browse/JDK-8215017 ) but if this is a real concern we can recuperate this - independently of this PR - by making intrinsics use `-CompactStrings` as a signal to optimize away the one-byte tail checks.

**Review by RogerRiggs — APPROVED** [review]
LGTM for the core-libs point of view. (And what I understand of the assembler)

**Comment by cl4es** [comment]
> LGTM for the core-libs point of view. (And what I understand of the assembler)

Thanks!

I'll try to get someone from the compiler team to look over the assembler change. @TobiHartmann, can you help get some eyes on this?

**Review by vnkozlov — CHANGES_REQUESTED** [review]
I don't see x86 changes. Why?

**Comment by cl4es** [comment]
> I don't see x86 changes. Why?

The 2-byte variants for `string_equals`, if they ever existed, seems to be gone:
```
// fast string equals
instruct string_equals(rdi_RegP str1, rsi_RegP str2, rcx_RegI cnt, rax_RegI result,
                       legRegD tmp1, legRegD tmp2, rbx_RegI tmp3, rFlagsReg cr)
%{
  predicate(!VM_Version::supports_avx512vlbw());
  match(Set result (StrEquals (Binary str1 str2) cnt));
  effect(TEMP tmp1, TEMP tmp2, USE_KILL str1, USE_KILL str2, USE_KILL cnt, KILL tmp3, KILL cr);

  format %{ "String Equals $str1,$str2,$cnt -> $result    // KILL $tmp1, $tmp2, $tmp3" %}
  ins_encode %{
    __ arrays_equals(false, $str1$$Register, $str2$$Register,
                     $cnt$$Register, $result$$Register, $tmp3$$Register,
                     $tmp1$$XMMRegister, $tmp2$$XMMRegister, false /* char */, knoreg);
  %}
  ins_pipe( pipe_slow );
%}
```

So AFAICT there is nothing to change on x86.

**Comment by vnkozlov** [comment]
You are right. I mistook `string_compareU*`  instructions for it.
Can you check history why we don't have it in x86*.ad?

**Comment by cl4es** [comment]
The x86 `string_equals` instruction pre-dates and was updated for the Compact Strings JEP. No specialized 2-byte variants: https://github.com/openjdk/jdk/commit/7af927f9c10923b61f746eb6e566bcda853dd95a#diff-89791d4b051172965f7ba8f0cb7afbeb7e141f6de924dc07167c5ceefdce6bbe 

A bit strange since distinct 1-byte `array_equalsB` and 2-byte `array_equalsC` were introduced at this time, sharing code. So either an unintended omission, or the benefit of having both variants didn't manifest in benchmarks.

**Comment by vnkozlov** [comment]
Thank you for checking.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by cl4es** [comment]
Thanks!

/integrate

**Pull request closed without merging**
