### PR TITLE
8294486: Remove vmTestbase/nsk/jvmti/ tests ported to serviceability/jvmti.

### PR DESCRIPTION
**Pull request by lmesnik**
The fix removes nsk/jvmti/  tests ported to serviceability/jvmti and forward-ports corresponding fixed. The suspend/resume tests require more work covered by https://bugs.openjdk.org/browse/JDK-8295169.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294486](https://bugs.openjdk.org/browse/JDK-8294486): Remove vmTestbase/nsk/jvmti/ tests ported to serviceability/jvmti.

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10665/head:pull/10665` \
`$ git checkout pull/10665`

Update a local copy of the PR: \
`$ git checkout pull/10665` \
`$ git pull https://git.openjdk.org/jdk pull/10665/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10665`

View PR using the GUI difftool: \
`$ git pr show -t 10665`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10665.diff">https://git.openjdk.org/jdk/pull/10665.diff</a>

</details>

### CODE REVIEW

**Comment by plummercj** [comment]
Can you update the CR to point to the CR that did the porting?

**Comment by lmesnik** [comment]
The tests were ported as a part of Loom. I added tests which are ported to the bug.

**Comment by sspitsyn** [comment]
A question.
I do not see the following tests deleted while they are deleted from the `TEST.qick-groups` :
```
-  vmTestbase/nsk/jvmti/RunAgentThread/agentthr001/TestDescription.java \
-  vmTestbase/nsk/jvmti/RunAgentThread/agentthr001/TestDescription.java \
-  vmTestbase/nsk/jvmti/ThreadEnd/threadend001/TestDescription.java \
-  vmTestbase/nsk/jvmti/ThreadEnd/threadend002/TestDescription.java \
```

**Comment by lmesnik** [comment]
Thank you, I deleted  vmTestbase/nsk/jvmti/ThreadEnd which were ported and returned back RunAgentThread entries.

**Comment by sspitsyn** [comment]
Thank you for the update. One more question.
A couple of tests are not listed in the `test/hotspot/jtreg/TEST.quick-groups`:
```
  test/hotspot/jtreg/vmTestbase/nsk/jvmti/GetFrameLocation/frameloc001
  test/hotspot/jtreg/vmTestbase/nsk/jvmti/SingleStep/singlestep002
```
Is it because these tests were initially missed to be added into this file?

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thanks,
Serguei

**Comment by sspitsyn** [comment]
Okay, thanks.

**Pull request closed without merging**
