### PR TITLE
8275262: [BACKOUT] AArch64: Implement string_compare intrinsic in SVE

### PR DESCRIPTION
**Pull request by nick-arm**
This reverts "8269559: AArch64: Implement string_compare intrinsic in SVE" which caused some unknown failures in Oracle's CI.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275262](https://bugs.openjdk.java.net/browse/JDK-8275262): [BACKOUT] AArch64: Implement string_compare intrinsic in SVE

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5941/head:pull/5941` \
`$ git checkout pull/5941`

Update a local copy of the PR: \
`$ git checkout pull/5941` \
`$ git pull https://git.openjdk.java.net/jdk pull/5941/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5941`

View PR using the GUI difftool: \
`$ git pr show -t 5941`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5941.diff">https://git.openjdk.java.net/jdk/pull/5941.diff</a>

</details>

### CODE REVIEW

**Comment by nick-arm** [comment]
> > The issue is only on (some of) our macOS Aarch64 systems. Let me know if I can provide more info on hardware etc.
> 
> Any info about what failed? A reproducer would be nice.

I just ran tier1 on an M1 Mac with no failures - perhaps it's OS version dependent if it only failed on some systems? I have:

```
$ uname -a
Darwin [...] 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
```

**Comment by theRealAph** [comment]
It might be a spurious failure, then. I guess we need to see the test logs.

**Pull request closed without merging**
