### PR TITLE
JDK-8326898: NSK tests should listen on loopback addresses only

### PR DESCRIPTION
**Pull request by alexmenkov**
Many NSK tests create socket channel for test/target interprocess communication.
The change updates server side to listen only on loopback interface.

Testing - all tests that use then functionality:
 - test/hotspot/jtreg/vmTestbase/nsk/jdb, test/hotspot/jtreg/vmTestbase/nsk/jdi, test/hotspot/jtreg/vmTestbase/nsk/jdwp, test/hotspot/jtreg/vmTestbase/nsk/aod, test/hotspot/jtreg/vmTestbase/nsk/jvmti/AttachOnDemand

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326898](https://bugs.openjdk.org/browse/JDK-8326898): NSK tests should listen on loopback addresses only (**Enhancement** - P4)

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [8d204ba7](https://git.openjdk.org/jdk/pull/18053/files/8d204ba7dfa2dc23ee1d3c7a5b8228abcf411dbf)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to [8d204ba7](https://git.openjdk.org/jdk/pull/18053/files/8d204ba7dfa2dc23ee1d3c7a5b8228abcf411dbf)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18053/head:pull/18053` \
`$ git checkout pull/18053`

Update a local copy of the PR: \
`$ git checkout pull/18053` \
`$ git pull https://git.openjdk.org/jdk.git pull/18053/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18053`

View PR using the GUI difftool: \
`$ git pr show -t 18053`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18053.diff">https://git.openjdk.org/jdk/pull/18053.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18053#issuecomment-1970256232)

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Nice fix.

**Review by plummercj — APPROVED** [review]

**Comment by jaikiran** [comment]
I don't have knowledge of this area, but I'm happy to see this change being done.

**Review by dholmes-ora — APPROVED** [review]
Thanks for the fix!

**Comment by AlanBateman** [comment]
The change is to the listener side, looks fine. Is the connecting side already connecting to the loopback address already?

**Review by lmesnik — APPROVED** [review]

**Comment by alexmenkov** [comment]
Updated connecting side of the IOPipe
Also fixed DebugeeArgumentHandler.getTestHost() (DebugeeArgumentHandler.getDebugeeHost() uses the value) to return empty string.
getTestHost()/getDebugeeHost() are used in some scenarios:
- to create arguments for listening debugee (in the case ":<port>" is passed, so debugee listens on loopback address);
- to connect to a socket (then InetAddress.getByName returns loockback address).

**Comment by alexmenkov** [comment]
Can I get re-review of the fix please

**Review by sspitsyn — APPROVED** [review]
The update looks okay.

**Review by plummercj — APPROVED** [review]
Looks good.

**Pull request closed without merging**
