### PR TITLE
8264868: Reduce inclusion of registerMap.hpp and register.hpp

### PR DESCRIPTION
**Pull request by iklam**
Register.hpp is included 815 times, and registerMap.hpp is include 862 times (out of about 1000 HotSpot .o files).

This can be reduced by refactoring the popular header file **frame.hpp**, so that it doesn't include registerMap.hpp anymore. This reduces the number of .o files that include register.hpp to 612, and that of registerMap.hpp to 109.

The total number of lines of C++ code compiled for HotSpot is reduced by about 0.5%.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264868](https://bugs.openjdk.java.net/browse/JDK-8264868): Reduce inclusion of registerMap.hpp and register.hpp

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 507136ef6f6a65eabf676f44b35bbcf61b17d972
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 507136ef6f6a65eabf676f44b35bbcf61b17d972

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3384/head:pull/3384` \
`$ git checkout pull/3384`

Update a local copy of the PR: \
`$ git checkout pull/3384` \
`$ git pull https://git.openjdk.java.net/jdk pull/3384/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3384`

View PR using the GUI difftool: \
`$ git pr show -t 3384`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3384.diff">https://git.openjdk.java.net/jdk/pull/3384.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
I like StackFrameStream getting its own header file.

**Review by dholmes-ora — APPROVED** [review]
Hi Ioi,

It isn't at all obvious to me how the stackFrameStream refactoring relates to the topic of this RFE. :)

But I don't see anything amiss, and if it improves build time etc, then it seems fine.

Thanks,
David

**Comment by iklam** [comment]
> Hi Ioi,
> 
> It isn't at all obvious to me how the stackFrameStream refactoring relates to the topic of this RFE. :)
> 
> But I don't see anything amiss, and if it improves build time etc, then it seems fine.
> 
> Thanks,
> David

Thanks for the review!

`StackFrameStream` was the only thing in frame.hpp that needed to use `RegisterMap`. Since `StackFrameStream` is used by only 15 .o files, I moved it to its own header file. This makes possible to decouple frame.hpp with registerMap.hpp.

**Comment by iklam** [comment]
Thanks @coleenp and @dholmes-ora for the review.
/integrate

**Pull request closed without merging**
