### PR TITLE
8314819: [JVMCI] HotSpotJVMCIRuntime.lookupType throws unexpected ClassNotFoundException

### PR DESCRIPTION
**Pull request by dougxc**
This PR restores the expected behavior prior to [JDK-8313421](https://bugs.openjdk.org/browse/JDK-8313421) whereby `HotSpotJVMCIRuntime.lookupType` throws `NoClassDefFoundError` instead of `ClassNotFoundException`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314819](https://bugs.openjdk.org/browse/JDK-8314819): [JVMCI] HotSpotJVMCIRuntime.lookupType throws unexpected ClassNotFoundException (**Bug** - P3)

### Reviewers
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**) ⚠️ Review applies to [c62ba346](https://git.openjdk.org/jdk/pull/15393/files/c62ba346670c1aea0ca4c310a3cc9e2cb705221d)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15393/head:pull/15393` \
`$ git checkout pull/15393`

Update a local copy of the PR: \
`$ git checkout pull/15393` \
`$ git pull https://git.openjdk.org/jdk.git pull/15393/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15393`

View PR using the GUI difftool: \
`$ git pr show -t 15393`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15393.diff">https://git.openjdk.org/jdk/pull/15393.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15393#issuecomment-1688973664)

### CODE REVIEW

**Review by tkrodriguez — APPROVED** [review]
Looks good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by TobiHartmann** [comment]
Just wondering, should there be a regression test?

**Comment by dougxc** [comment]
> Just wondering, should there be a regression test?

Yes. The existing tests for `CompilerToVM.lookupType` needed to be adjusted and I expanded them to also test HotSpotJVMCIRuntime.lookupType`: adf985d4c9ba35d9d9d586fad503e0660eee9f91

**Review by TobiHartmann — APPROVED** [review]

**Comment by dougxc** [comment]
Thanks for the reviews.

/integrate

**Pull request closed without merging**
