### PR TITLE
8336466: C2: Parser incorrectly/unnecessarily checks for clinits

### PR DESCRIPTION
**Pull request by shipilev**
As shown in [JDK-8336103](https://bugs.openjdk.org/browse/JDK-8336103), C2 Parser code uses `is_initializer` in the code where we expect to only check for constructors. The fix nominally changes the behavior for C2. I do not believe this is something readily observable, but need to be more explicit.

Additional testing:
 - [x]  Linux AArch64 server fastdebug, all (includes Fuzzer and CTW tests), passed as part of JDK-8336103 testing

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336466](https://bugs.openjdk.org/browse/JDK-8336466): C2: Parser incorrectly/unnecessarily checks for clinits (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20191/head:pull/20191` \
`$ git checkout pull/20191`

Update a local copy of the PR: \
`$ git checkout pull/20191` \
`$ git pull https://git.openjdk.org/jdk.git pull/20191/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20191`

View PR using the GUI difftool: \
`$ git pr show -t 20191`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20191.diff">https://git.openjdk.org/jdk/pull/20191.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20191#issuecomment-2230536830)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too. I submitted this through our testing and will report back once it passed.

**Comment by TobiHartmann** [comment]
All tests passed.

**Comment by shipilev** [comment]
Thanks! I am integrating then.

/integrate

**Pull request closed without merging**
