### PR TITLE
8288732: Reduce runtime of java.util.concurrent microbenchmarks

### PR DESCRIPTION
**Pull request by cl4es**
- Refactor so that various baseline micros are not run repeatedly with different parameter values that does not affect the baseline
- Tune iteration times, counts, forks..

Reduces runtime of java.util.concurrent micros from an estimated 14h43m to 1h21m

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288732](https://bugs.openjdk.org/browse/JDK-8288732): Reduce runtime of java.util.concurrent microbenchmarks

### Reviewers
 * [Eric Caspole](https://openjdk.org/census#ecaspole) (@ericcaspole - Committer)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9214/head:pull/9214` \
`$ git checkout pull/9214`

Update a local copy of the PR: \
`$ git checkout pull/9214` \
`$ git pull https://git.openjdk.org/jdk pull/9214/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9214`

View PR using the GUI difftool: \
`$ git pr show -t 9214`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9214.diff">https://git.openjdk.org/jdk/pull/9214.diff</a>

</details>

### CODE REVIEW

**Review by ericcaspole — APPROVED** [review]
Nice cleanup. The quicker these run with stable performance, the more we can use them every week.

**Comment by cl4es** [comment]
Still waiting for a Reviewer on this one

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Pull request closed without merging**
