### PR TITLE
8295176: some langtools test pollutes source tree

### PR DESCRIPTION
**Pull request by lahodaj**
The `ReleaseOptionThroughAPI.java` test compiles another test source, `ReleaseOption.java`. But it does not specify the output directory, so javac generates the classfile next to the source files into the source directory, causing trouble.

The proposed fix is to add `-d .` to the test, so that the classfile is not generated into the working directory.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295176](https://bugs.openjdk.org/browse/JDK-8295176): some langtools test pollutes source tree

### Reviewers
 * [Srikanth Adayapalam](https://openjdk.org/census#sadayapalam) (@sadayapalam - **Reviewer**) ⚠️ Review applies to [8d452c71](https://git.openjdk.org/jdk/pull/10724/files/8d452c71edabbe43f40942977ec2bf7ccdb6844c)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10724/head:pull/10724` \
`$ git checkout pull/10724`

Update a local copy of the PR: \
`$ git checkout pull/10724` \
`$ git pull https://git.openjdk.org/jdk pull/10724/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10724`

View PR using the GUI difftool: \
`$ git pr show -t 10724`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10724.diff">https://git.openjdk.org/jdk/pull/10724.diff</a>

</details>

### CODE REVIEW

**Comment by sadayapalam** [comment]
Thanks so much for fixing this. It was beginning to irritate me.

The fix is ok, but doing a bit of archaeology, it looks like the fix for JDK-8173605 introduced the problem. JDK-8173605 attempts to remove support for source and target 1.7 option in javac. In so doing, the test ReleaseOption.java
whose objective is to "Verify that javac rejects Java 8 program with --release 7" becomes irrelevant and perhaps the whole test could have been deleted rather than making the negative test (that would fail to compile) into a positive test that compiles fine.

In particular the Summary line in ReleaseOption.java is stale.

It is not clear to me that the test serves any real purpose - compiled directly or through the API.

**Comment by sadayapalam** [comment]
I confirm that the proposed fix solves the problem. 

I suggest a push either after 

- cleaning up the Summary of ReleaseOption.java test OR
- deleting both the tests ReleaseOption.java and ReleaseOptionThroughAPI.java 

Looks good to me.

**Review by sadayapalam — APPROVED** [review]

**Comment by sadayapalam** [comment]
The proposed change restoring the negative nature of the test is better than my suggestions. Thanks, Look good to me.

**Review by vicente-romero-oracle — APPROVED** [review]

**Comment by lahodaj** [comment]
Thanks for the reviews!

**Pull request closed without merging**
