### PR TITLE
8304503: Modernize debugging jvm args in demo netbeans projects

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which suggests to modernize the JVM arguments used to enable debugging in the netbeans project files for demos. 

The netbeans projects found in src/demo/share/nbproject currently use the following outdated combination of jvm arguments to set up debugging:

```xml
<jvmarg value="-Xdebug"/>
<jvmarg value="-Xnoagent"/>
<jvmarg value="-Djava.compiler=none"/>
<jvmarg value="-Xrunjdwp:transport=dt_socket,address=${jpda.address}"/>
```

They should instead just do:

```xml
<jvmarg value="-agentlib:jdwp=transport=dt_socket,server=n,suspend=n,address=${jpda.address}"/>
```

Additionally, the source dir set up in build.properties for these projects do not seem to align with the source layout.

`src.dir=${main.dir}/src` should instead be just `src.dir=${main.dir}/`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304503](https://bugs.openjdk.org/browse/JDK-8304503): Modernize debugging jvm args in demo netbeans projects (**Enhancement** - P4)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13101/head:pull/13101` \
`$ git checkout pull/13101`

Update a local copy of the PR: \
`$ git checkout pull/13101` \
`$ git pull https://git.openjdk.org/jdk.git pull/13101/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13101`

View PR using the GUI difftool: \
`$ git pr show -t 13101`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13101.diff">https://git.openjdk.org/jdk/pull/13101.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13101#issuecomment-1476222745)

### CODE REVIEW

**Comment by eirbjo** [comment]
Note that #13098 suggests to remove a number of netbeans projects for which there no longer seem to exist any corresponding source files. The projects which are suggested for removal are not updated in this PR.

**Comment by eirbjo** [comment]
This PR is a blocking the removal of the `java.compiler` system property.

It would be great to get a review for this low-risk change :-)

**Review by prrace — COMMENTED** [review]
No one has maintained these in a long time.
Did you manually verify all of these with a recent netbeans?

**Comment by prrace** [comment]
I'd be just as happy if you deleted all of these like you propose  in 8304501 ..

**Comment by eirbjo** [comment]
> No one has maintained these in a long time. Did you manually verify all of these with a recent netbeans?

Yes, I downloaded the most recent Netbeans from Apache and verified I could run the debugging tasks. I'm no Netbeans expert, but I feel convinced that I tested it and that it worked. It did fail when I tried with some invalid options.

**Comment by eirbjo** [comment]
> I'd be just as happy if you deleted all of these like you propose in 8304501 ..

Would this require some broader discussion and a concenus?

Or could we simply withdraw this PR and instead broaden the scope of #13098 to remove all Netbeans projects?

If these are just dead files with no current or future use, them perhaps it is better to let them go.

**Comment by eirbjo** [comment]
> Or could we simply withdraw this PR and instead broaden the scope of #13098 to remove all Netbeans projects?

As #13098 is now  integrated, it would now make more sense to create a seperate PR for a removal of these projects.

**Comment by eirbjo** [comment]
After thinking this through I think I would prefer to go ahead with fixing this in this PR, then eventually we can do another PR for a deletion.

@prrace would you consider approving this PR as-is?

**Comment by eirbjo** [comment]
The removal of the `java.compiler` system property just got integrated:


It would be good to get the arcaic usage of `java.compiler` in these Netbeans projects updated.

Looking for reviewers :-)

**Review by prrace — APPROVED** [review]
Ok, since you tested it .. I'm approving, but I think the odds are few people will notice either way.

**Comment by eirbjo** [comment]
> Ok, since you tested it .. I'm approving, but I think the odds are few people will notice either way.

Thanks Phil, I’ve integrated. I’ll consider a removal patch once I get back from vacation. If nobody uses these projects, I agree it would be cleaner to simply remove them.

But for this PR, the purpose was to rid the OpenJDK of reference to the removed property so they don’t show up in code searches. It’s good to have that done, so thanks for your approval 😀

**Pull request closed without merging**
