### PR TITLE
8259619: C1: 3-arg StubAssembler::call_RT stack-use condition is incorrect

### PR DESCRIPTION
**Pull request by shipilev**
SonarCould instance reports this code smell in c1_Runtime_x86.cpp: Identical sub-expressions on both sides of operator "||"

```
int StubAssembler::call_RT(Register oop_result1, Register metadata_result, address entry, Register arg1, Register arg2, Register arg3) {
#ifdef _LP64
  // if there is any conflict use the stack
  if (arg1 == c_rarg2 || arg1 == c_rarg3 ||
      arg2 == c_rarg1 || arg1 == c_rarg3 ||
      arg3 == c_rarg1 || arg1 == c_rarg2) { <---- HERE
    push(arg3);
    push(arg2);
    push(arg1);
    pop(c_rarg1);
    pop(c_rarg2);
    pop(c_rarg3);
  } else {
    mov(c_rarg1, arg1);
    mov(c_rarg2, arg2);
    mov(c_rarg3, arg3);
  }
```

It seems obvious that the right column in the condition should have been `arg1`, `arg2`, `arg3`.

Additional testing:
 - [x] Linux x86_64 `tier1`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259619](https://bugs.openjdk.java.net/browse/JDK-8259619): C1: 3-arg StubAssembler::call_RT stack-use condition is incorrect

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2048/head:pull/2048`
`$ git checkout pull/2048`

### CODE REVIEW

**Review by chhagedorn — CHANGES_REQUESTED** [review]
Good catch! That looks reasonable to me.

Can you also fix this in [c1_Runtime1_aarch64.cpp](https://github.com/openjdk/jdk/blob/563b268c8f23a1f9f5e70065419d4e8661d1d0b4/src/hotspot/cpu/aarch64/c1_Runtime1_aarch64.cpp#L144-L148)?

**Comment by shipilev** [comment]
> Can you also fix this in [c1_Runtime1_aarch64.cpp](https://github.com/openjdk/jdk/blob/563b268c8f23a1f9f5e70065419d4e8661d1d0b4/src/hotspot/cpu/aarch64/c1_Runtime1_aarch64.cpp#L144-L148)?

Oh! Fixed there too.

**Review by chhagedorn — APPROVED** [review]
Thanks, looks good!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
