### PR TITLE
8334315: Shenandoah: reduce GC logging noise

### PR DESCRIPTION
**Pull request by kdnilsen**
Qualify certain log messages as ergo or debug to remove extraneous noise from regular gc logs.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334315](https://bugs.openjdk.org/browse/JDK-8334315): Shenandoah: reduce GC logging noise (**Bug** - P4)

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19795/head:pull/19795` \
`$ git checkout pull/19795`

Update a local copy of the PR: \
`$ git checkout pull/19795` \
`$ git pull https://git.openjdk.org/jdk.git pull/19795/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19795`

View PR using the GUI difftool: \
`$ git pr show -t 19795`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19795.diff">https://git.openjdk.org/jdk/pull/19795.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19795#issuecomment-2218754112)

### CODE REVIEW

**Review by earthling-amzn — APPROVED** [review]

**Review by ysramakrishna — APPROVED** [review]
👍 🚢

**Review by shipilev — APPROVED** [review]

**Comment by shipilev** [comment]
Any reason we are not integrating this? Still noise in GC logs :)

**Pull request closed without merging**
