### PR TITLE
8276125: RunThese24H.java SIGSEGV in JfrThreadGroup::thread_group_id

### PR DESCRIPTION
**Pull request by mgronlun**
Greetings,

please help review this changeset.

Details are listed in the JIRA issue.

Testing: jdk_jfr

Thanks
Markus

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276125](https://bugs.openjdk.java.net/browse/JDK-8276125): RunThese24H.java SIGSEGV in JfrThreadGroup::thread_group_id

### Reviewers
 * [Erik Gahlin](https://openjdk.java.net/census#egahlin) (@egahlin - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6702/head:pull/6702` \
`$ git checkout pull/6702`

Update a local copy of the PR: \
`$ git checkout pull/6702` \
`$ git pull https://git.openjdk.java.net/jdk pull/6702/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6702`

View PR using the GUI difftool: \
`$ git pr show -t 6702`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6702.diff">https://git.openjdk.java.net/jdk/pull/6702.diff</a>

</details>

### CODE REVIEW

**Review by egahlin — APPROVED** [review]

**Review by shipilev — APPROVED** [review]
Looks fine. Probably affects all releases, right? Even before Thread-SMR, the thread oop is not really guaranteed to be here?

**Comment by mgronlun** [comment]
"Looks fine. Probably affects all releases, right? Even before Thread-SMR, the thread oop is not really guaranteed to be here?"

I don't really remember. This is old code, but the sightings started to appear in the last couple of months. Perhaps it is a combo of SMR thread lists AND the Access API coming together? The earlier API in javaClasses.inline.hpp handling null perhaps?

**Comment by sendaoYan** [comment]
Hi, where is the applications/runthese/RunThese24H.java, I can't find the `runthese` sub-directory in `test/hotspot/jtreg/applications` directory.

**Comment by mgronlun** [comment]
> Hi, where is the `applications/runthese/RunThese24H.java`, I can't find the `runthese` sub-directory in `test/hotspot/jtreg/applications` directory.

Unfortunately, this test is an internal, non-public, repository.

**Pull request closed without merging**
