### PR TITLE
8267914: Remove DeferredObjectToKlass workaround

### PR DESCRIPTION
**Pull request by stefank**
In JKD-8229839 we fixed a circular dependency problem between oop.inline.hpp and markWord.inline.hpp.  When JDK-8267464: 
'Circular-dependency resilient inline headers' gets integrated, this workaround isn't needed anymore.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267914](https://bugs.openjdk.java.net/browse/JDK-8267914): Remove DeferredObjectToKlass workaround

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to ade6485025724b1be7e60e6e4a0bd067492bfc64
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4242/head:pull/4242` \
`$ git checkout pull/4242`

Update a local copy of the PR: \
`$ git checkout pull/4242` \
`$ git pull https://git.openjdk.java.net/jdk pull/4242/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4242`

View PR using the GUI difftool: \
`$ git pr show -t 4242`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4242.diff">https://git.openjdk.java.net/jdk/pull/4242.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by stefank** [comment]
Thanks for reviewing!

**Pull request closed without merging**
