### PR TITLE
8331719: Cleanup asserts/code after introducing IsSTWGCActiveMark

### PR DESCRIPTION
**Pull request by xiaotaonan**
Cleanup asserts/code after introducing IsSTWGCActiveMark

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331719](https://bugs.openjdk.org/browse/JDK-8331719): Cleanup asserts/code after introducing IsSTWGCActiveMark (**Enhancement** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19208/head:pull/19208` \
`$ git checkout pull/19208`

Update a local copy of the PR: \
`$ git checkout pull/19208` \
`$ git pull https://git.openjdk.org/jdk.git pull/19208/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19208`

View PR using the GUI difftool: \
`$ git pr show -t 19208`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19208.diff">https://git.openjdk.org/jdk/pull/19208.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19208#issuecomment-2106187666)

### CODE REVIEW

**Comment by xiaotaonan** [comment]
@lgxbslgx

**Review by stefank — APPROVED** [review]

**Review by lgxbslgx — APPROVED** [review]
Looks good.

**Comment by lgxbslgx** [comment]
This issue was assigned by @shipilev . Not know whether he had a patch locally. It may be good for him to have a look.

**Comment by shipilev** [comment]
> This issue was assigned by @shipilev . Not know whether he had a patch locally. It may be good for him to have a look.

Actually, this was assigned to one of our folks. The common courtesy protocol is to _ask_ whether you can take the assignment off someone's hands. For many patches, there is a background that might only be known to current assignee, who might have done some further research into the issue.

For example here, I was planning to also deal with `G1CollectedHeap::do_collection_pause_at_safepoint`, which can be inlined better.

**Comment by lgxbslgx** [comment]
> The common courtesy protocol is to ask whether you can take the assignment off someone's hands. For many patches, there is a background that might only be known to current assignee, who might have done some further research into the issue.

I agree. I think communication is more important than code/patch in an open source community.

> @lgxbslgx

@xiaotaonan  Generally, I will review the patches in HotSpot, especially GC, when I have free time. I am happy to review your patch. But I don't think it is good to CC me if I have not gotten involved in the discussion.

**Comment by xiaotaonan** [comment]
> > This issue was assigned by @shipilev . Not know whether he had a patch locally. It may be good for him to have a look.
> 
> Actually, this was assigned to one of our folks. The common courtesy protocol is to _ask_ whether you can take the assignment off someone's hands. For many patches, there is a background that might only be known to current assignee, who might have done some further research into the issue.
> 
> For example here, I was planning to also deal with `G1CollectedHeap::do_collection_pause_at_safepoint`, which can be inlined better.

Sorry for that,I will close this PR.

**Pull request closed without merging**
