### PR TITLE
8316125: Windows call_stub unnecessarily saves xmm16-31 when UseAVX>=3

### PR DESCRIPTION
**Pull request by djelinski**
Please review this patch that removes saving of xmm16-xmm31 registers from Windows call_stub.

Windows ABI only mandates saving xmm6-xmm15, which we continue to do here.

No new tests. Mach5 tier1-5 builds and tests clean.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8316125](https://bugs.openjdk.org/browse/JDK-8316125): Windows call_stub unnecessarily saves xmm16-31 when UseAVX&gt;=3 (**Enhancement** - P4)

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15688/head:pull/15688` \
`$ git checkout pull/15688`

Update a local copy of the PR: \
`$ git checkout pull/15688` \
`$ git pull https://git.openjdk.org/jdk.git pull/15688/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15688`

View PR using the GUI difftool: \
`$ git pr show -t 15688`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15688.diff">https://git.openjdk.org/jdk/pull/15688.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15688#issuecomment-1716136727)

### CODE REVIEW

**Comment by JornVernee** [comment]
We've discussed this offline. Based on the calling convention described here: https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#callercallee-saved-registers these registers are 'volatile', i.e. _not_ callee saved. That means that in this case, where we have a C function calling into Java, we don't need to save these registers for our C caller.

The relevant parts behind that link copied here (part bolded by me for emphasis):

> The x64 ABI considers the registers RAX, RCX, RDX, R8, R9, R10, R11, and XMM0-XMM5 volatile. When present, the upper portions of YMM0-YMM15 and ZMM0-ZMM15 are also volatile. **On AVX512VL, the ZMM, YMM, and XMM registers 16-31 are also volatile.** When AMX support is present, the TMM tile registers are volatile. Consider volatile registers destroyed on function calls unless otherwise safety-provable by analysis such as whole program optimization.
> 
> The x64 ABI considers registers RBX, RBP, RDI, RSI, RSP, R12, R13, R14, R15, and XMM6-XMM15 nonvolatile. They must be saved and restored by a function that uses them.

**Review by JornVernee — APPROVED** [review]
/reviewers 2

**Comment by dholmes-ora** [comment]
This code originally came from the Intel folk:
https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2015-April/017579.html
It would be good if someone from Intel could review the changes. I always like to try and understand why something was originally done the way it was. Perhaps it predates the Windows ABI defining these as volatile?

**Comment by dholmes-ora** [comment]
I'm guessing this part of the change description covers it:
> The call save regions have been extended for both compilation models to handle their 
respective register banks and are working correctly.

**Comment by vnkozlov** [comment]
@jatin-bhateja or @sviswa7 can you look on this PR?

**Comment by djelinski** [comment]
@jatin-bhateja or @sviswa7 would one of you be able to find out why the current code saves the high XMM registers?
The code was provided by @mcberg2016, but he's no longer around as far as I can tell.

**Review by vnkozlov — APPROVED** [review]

**Review by sviswa7 — APPROVED** [review]
Looks good to me as well.

**Pull request closed without merging**
