### PR TITLE
8262508: Vector API's ergonomics is incorrect

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

The ergonomics (e.g., EnableVectorReboxing/EnableVectorAggressiveReboxing) for Vector API doesn't work as expected.

There are two sets of rules for Vector API.
One is in Arguments::apply_ergo() [1], which sets the flags to be false.
And the other is in Modules::define_module() [2], which sets the flags to be true.

The value of EnableVectorReboxing and EnableVectorAggressiveReboxing may be changed (from specified true to false) in [1] if EnableVectorSupport=false (which is the default value).
It would be wrong when EnableVectorSupport isn't specified in the command line since it will be set true later in [2]
So rules in [1] should not be executed if EnableVectorSupport isn't specified.

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/arguments.cpp#L4081
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/modules.cpp#L462

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262508](https://bugs.openjdk.java.net/browse/JDK-8262508): Vector API's ergonomics is incorrect

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2771/head:pull/2771`
`$ git checkout pull/2771`

### CODE REVIEW

**Comment by DamonFool** [comment]
Could someone help to review this change?
Thanks.

**Review by iwanowww — APPROVED** [review]
Looks good. 

Thanks for fixing it.

**Comment by DamonFool** [comment]
> Looks good.
> 
> Thanks for fixing it.

Thanks @iwanowww for your review.

Will push it tomorrow if there is no other comment.
Thanks.

**Pull request closed without merging**
