### PR TITLE
8239090: Improve CPU feature support in VM_Version

### PR DESCRIPTION
**Pull request by phohensee**
This is a holdover patch previously reviewed when the jdk was under hg control. See the thread starting at

https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-September/039887.html

Reviewed by Volker Simonis (simonis) and Igor Veresov (iveresov).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8239090](https://bugs.openjdk.java.net/browse/JDK-8239090): Improve CPU feature support in VM_Version  

### Reviewers
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)
 * [Volker Simonis](https://openjdk.java.net/census#simonis) (@simonis - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/436/head:pull/436`
`$ git checkout pull/436`

### CODE REVIEW

**Review by veresov — APPROVED** [review]
Looks good.

**Review by simonis — APPROVED** [review]
Hi Paul,

looks good!

Thanks for adding the assertion.

Best regards,
Volker

**Comment by dcubed-ojdk** [comment]
There's no testing information in this PR and the testing mentioned
in the review on hotspot-compiler-dev is minimal. This fix is currently
failing the sun/hotspot/whitebox/CPUInfoTest.java three times in
the JDK16 CI in Tier1. @veresov has a fix that he has tested and will
start the review process soon.

**Pull request closed without merging**
