### PR TITLE
8331011: [XWayland] TokenStorage fails under Security Manager

### PR DESCRIPTION
**Pull request by azvegint**
This fix adds missing doPrivileged calls in TokenStorage, which is used to help take screenshots in Wayland.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331011](https://bugs.openjdk.org/browse/JDK-8331011): [XWayland] TokenStorage fails under Security Manager (**Bug** - P3)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18950/head:pull/18950` \
`$ git checkout pull/18950`

Update a local copy of the PR: \
`$ git checkout pull/18950` \
`$ git pull https://git.openjdk.org/jdk.git pull/18950/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18950`

View PR using the GUI difftool: \
`$ git pr show -t 18950`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18950.diff">https://git.openjdk.org/jdk/pull/18950.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18950#issuecomment-2077010793)

### CODE REVIEW

**Review by prrace — APPROVED** [review]

**Review by honkar-jdk — APPROVED** [review]
LGTM

**Comment by mrserb** [comment]
How hard is it to create a new test for this issue?

**Comment by azvegint** [comment]
> How hard is it to create a new test for this issue?

The issue was discovered by failing a closed test that you wrote some time ago.

**Comment by prrace** [comment]
> > How hard is it to create a new test for this issue?
> 
> The issue was discovered by failing a closed test that you wrote some time ago.

And while we need that existing test to pass I don't think it is worth writing a 2nd test for the same given that SecurityManager is deprecated and at some point that I expect is getting sooner all the time, all such tests will be obsolete.

**Comment by mrserb** [comment]
> The issue was discovered by failing a closed test that you wrote some time ago.
=) ok

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
