### PR TITLE
JDK-8296969: C1: PrintC1Statistics is broken after JDK-8292878

### PR DESCRIPTION
**Pull request by caojoshua**
Issue is coming from https://bugs.openjdk.org/browse/JDK-8292878. This PR adds the `rscratch1` argument to the affected `incrementl` call.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296969](https://bugs.openjdk.org/browse/JDK-8296969): C1: PrintC1Statistics is broken after JDK-8292878

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [7a2c075b](https://git.openjdk.org/jdk/pull/11170/files/7a2c075b210735354ea1d6c7c0be9a418b60b9b7)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Xin Liu](https://openjdk.org/census#xliu) (@navyxliu - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11170/head:pull/11170` \
`$ git checkout pull/11170`

Update a local copy of the PR: \
`$ git checkout pull/11170` \
`$ git pull https://git.openjdk.org/jdk pull/11170/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11170`

View PR using the GUI difftool: \
`$ git pr show -t 11170`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11170.diff">https://git.openjdk.org/jdk/pull/11170.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good! I suggest to additionally add a hello world test with that flag to do some sanity testing.

**Comment by caojoshua** [comment]
> Looks good! I suggest to additionally add a hello world test with that flag to do some sanity testing.

Thanks. I added a basic test.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by navyxliu — APPROVED** [review]
LGTM. I am not a reviewer.

**Pull request closed without merging**
