### PR TITLE
8279339: (ch) Input/Output streams returned by Channels factory methods don't support concurrent read/write ops

### PR DESCRIPTION
**Pull request by AlanBateman**
If someone has a SocketChannel sc then one way to obtain input/output streams is via the Socket adaptor, i.e. sc.socket().getXXXStream. Another way is with Channels.newXXXStream(sc) factory methods. A long standing limitation is that the input/output streams returned by the Channels.newXXXStream methods must synchronize on the channel's blockingLock() to prevent the channel from being configured non-blocking. There is one "blocking lock" per SelectableChannel so problematic when the SelectableChannel is also a ByteChannel as it prevents a thread from writing while another is blocked in read (and vice versa).

The change proposed here is to have Channels.newXXXStream special case the SocketChannel implementation so that it returns the same input/output stream as the socket adaptors. These socket streams make use of non-exposed blocking read/write methods that coordinate with configureBlocking so don't need to synchronize on the blockingLock. The core part of the change is that the inner classes that were in SocketAdaptor are moved to be top-level SocketInputStream and SocketOutputStream classes.

There is some minor cleanup to ChannelInputStream and ChannelOutputStream in this patch. Once pattern matching for switch is permanent, and Markus Karg is done with transferTo, then we can see if we want to refactor that method and/or introduce a sub-class for FileChannel.

I've added a new test to exercise the the read/write methods, with focus on async close and interrupt. It includes tests that do concurrent read + write operations.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279339](https://bugs.openjdk.java.net/browse/JDK-8279339): (ch) Input/Output streams returned by Channels factory methods don't support concurrent read/write ops

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6953/head:pull/6953` \
`$ git checkout pull/6953`

Update a local copy of the PR: \
`$ git checkout pull/6953` \
`$ git pull https://git.openjdk.java.net/jdk pull/6953/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6953`

View PR using the GUI difftool: \
`$ git pr show -t 6953`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6953.diff">https://git.openjdk.java.net/jdk/pull/6953.diff</a>

</details>

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]
This looks good.  Thank you for addressing.

I typically use assertThrows vs expectThrows for consistency with the other assertXXX

**Review by bplb — APPROVED** [review]

**Comment by AlanBateman** [comment]
> I typically use assertThrows vs expectThrows for consistency with the other assertXXX

I've got into the habit of using expectThrows because tests will often need to check the exception cause (assertThrows is void). I don't mind changing it as either will work for this test.

**Comment by LanceAndersen** [comment]
> > I typically use assertThrows vs expectThrows for consistency with the other assertXXX
> 
> I've got into the habit of using expectThrows because tests will often need to check the exception cause (assertThrows is void). I don't mind changing it as either will work for this test.

No need to change.  All good by me either way!

**Review by bplb — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Comment by mkarg** [comment]
Thanks a lot @AlanBateman for fixing this longstanding issue. I am pretty sure, @trishagee is not the only one really appreciating this fix! 🥇👍

**Pull request closed without merging**
