### PR TITLE
8318038: ProblemList runtime/CompressedOops/CompressedClassPointers.java on two platforms

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial ProblemListing for some tests:

[JDK-8318038](https://bugs.openjdk.org/browse/JDK-8318038) ProblemList runtime/CompressedOops/CompressedClassPointers.java on two platforms
[JDK-8318040](https://bugs.openjdk.org/browse/JDK-8318040) ProblemList vmTestbase/nsk/monitoring/ThreadMXBean/findMonitorDeadlockedThreads/find006/TestDescription.java on macosx-aarch64
[JDK-8318042](https://bugs.openjdk.org/browse/JDK-8318042) ProblemList java/nio/channels/vthread/BlockingChannelOps.java#direct-register with GenZGC

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8318038](https://bugs.openjdk.org/browse/JDK-8318038): ProblemList runtime/CompressedOops/CompressedClassPointers.java on two platforms (**Sub-task** - P3)
 * [JDK-8318040](https://bugs.openjdk.org/browse/JDK-8318040): ProblemList vmTestbase/nsk/monitoring/ThreadMXBean/findMonitorDeadlockedThreads/find006/TestDescription.java on macosx-aarch64 (**Sub-task** - P4)
 * [JDK-8318042](https://bugs.openjdk.org/browse/JDK-8318042): ProblemList java/nio/channels/vthread/BlockingChannelOps.java#direct-register with GenZGC (**Sub-task** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16172/head:pull/16172` \
`$ git checkout pull/16172`

Update a local copy of the PR: \
`$ git checkout pull/16172` \
`$ git pull https://git.openjdk.org/jdk.git pull/16172/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16172`

View PR using the GUI difftool: \
`$ git pr show -t 16172`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16172.diff">https://git.openjdk.org/jdk/pull/16172.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16172#issuecomment-1760272998)

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]

**Review by azvegint — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@RogerRiggs and @azvegint - Thanks for the fast reviews!

/integrate

**Pull request closed without merging**
