### PR TITLE
8315361: C2: Create a superclass of SuperWord

### PR DESCRIPTION
**Pull request by fg1417**
As discussed in [JDK-8308994](https://bugs.openjdk.org/browse/JDK-8308994), we should first do some refactoring work before proceeding with the new post loop vectorization. In this patch, we have done the following refactoring. (Most of changes are just moving the code around without real change on logic.)

1) We have created a superclass for shared data structures and utilities for C2's auto-vectorization.

2) We have moved data structures for basic loop info and the field _vector_loop_debug to the superclass. We also drop the class member "_visited" and "_post_visited", and instead use local variables, namely allocating them when using them.

3) Both two vectorizers traverse and store loop body nodes in RPO (Reverse Post-Order) separately. So we withdraw the logic into a new function `collect_nodes_in_reverse_postorder()`, and move the function and related data structures to the superclass. Before, the code for counting the number of reduction uses is mixed in the RPO logic. Now, we have decoupled the code and put it into SuperWord separately.

Tested tier1~3 on x86 and AArch64.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8320668](https://bugs.openjdk.org/browse/JDK-8320668) to be approved

### Integration blocker
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8315361](https://bugs.openjdk.org/browse/JDK-8315361)

### Issues
 * [JDK-8315361](https://bugs.openjdk.org/browse/JDK-8315361): C2 SuperWord: refactor out loop analysis into shared auto-vectorization facility VLoopAnalyzer (**Enhancement** - P4) ⚠️ Title mismatch between PR and JBS.
 * [JDK-8320668](https://bugs.openjdk.org/browse/JDK-8320668): Remove CompileCommand option VectorizeDebug (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16353/head:pull/16353` \
`$ git checkout pull/16353`

Update a local copy of the PR: \
`$ git checkout pull/16353` \
`$ git pull https://git.openjdk.org/jdk.git pull/16353/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16353`

View PR using the GUI difftool: \
`$ git pr show -t 16353`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16353.diff">https://git.openjdk.org/jdk/pull/16353.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16353#issuecomment-1778361219)

### CODE REVIEW

**Comment by eme64** [comment]
Hi @fg1417 I gave it a quick look, generally looks very reasonable.

My question: should we not also move the `velt` (vector element type) and maybe even the dependence graph parts?
If I remember right, then the post-loop-vectorizer also needs some way to determine element type, but not sure about dependence graph. We could also have more classes that have different parts of these features.

**Comment by fg1417** [comment]
> My question: should we not also move the `velt` (vector element type) and maybe even the dependence graph parts? If I remember right, then the post-loop-vectorizer also needs some way to determine element type (`_elem_bt` [here](https://github.com/openjdk/jdk/pull/14581)), but not sure about dependence graph. And also the memory slices may be helpful for all vectorizers. We could also have more classes that have different parts of these features (eg. `Vectorizer` with only basic functionality, and then a `VectorizerWithDependencyGraph`).

Hi @eme64, thanks for your review!

Yes, and both SuperWord and post-loop-vectorizer need to determine vector element type. There are still some deficiencies in current [`compute_vector_element_type()`](https://github.com/openjdk/jdk/blob/b3fec6b5f32c338ae1a84dd20bdcbd3d9b7186f3/src/hotspot/share/opto/superword.cpp#L3350) of SuperWord. For example, some loop cases of subword types, including byte and short, can't be recognized very well. See the description in https://github.com/openjdk/jdk/pull/7954. Maybe the main idea of [`find_vector_element_types()`](https://github.com/openjdk/jdk/blob/bd1b939b21a23675fd072b91d4eab538ff6d2a7d/src/hotspot/share/opto/vmaskloop.cpp#L318) proposed in Pengfei’s post-loop-vectorizer can be improved to solve it?

About the dependence graph part, SuperWord works better than post-loop-vectorizer, because it can support more cases like reading-forward, after your great refactoring 👍 . But now, post-loop-vectorizer can’t support any cases with index offset.

So, maybe both two parts need more complex refactoring and improving, before they can be shared well by two vectorizers, not like code parts in this patch.

Thanks!

**Comment by eme64** [comment]
@fg1417 thanks for the answer. I think I'd be ok with doing only the part you did for now. We can do the `velt` part separately. But I would prefer that we do not integrate the post-loop-vectorizer until we have found a way to unify the `velt` logic.

I think it would be nice to find a solution to what you did in https://github.com/openjdk/jdk/pull/7954. I wonder if we can do some of the work already during IGVN, and simplify the graph (best option if possible). If not, then we would need some sort of pre-processing for the AutoVectorizer, and either modify the graph (maybe not such a good idea) or somehow have a separate mapping of the graph/copy (more overhead / complexity).

How does the post-loop-vectorizer deal with all of this in the current draft?

**Comment by fg1417** [comment]
@eme64 , thanks for your reply.

Actually, the post-loop-vectorizer hasn’t supported this kind of scenario either, out of the same reason. As we all know, it’s not difficult in both two vectorizer to determine the precise type for all candidate nodes, releasing the limitation [here](https://github.com/openjdk/jdk/blob/5207443b360cfe3ee9c53ece55da3464c13f6a9f/src/hotspot/share/opto/superword.cpp#L3400) and [here](https://github.com/openjdk/jdk/blob/bd1b939b21a23675fd072b91d4eab538ff6d2a7d/src/hotspot/share/opto/vmaskloop.cpp#L357). But the issue is how to guarantee the correctness of vector shift left then right operations for subword types.

Post-loop-vectorizer collects all nodes for each statement. With the mapping info from statements to nodes, it would be easier **in the phase of vectorizing** to recognize and then remove the pattern LShiftI – RShiftI, which is generated by scalar width promotion,  from the graph to guarantee the equivalent transformation from scalar to vector.

But, for SuperWord, all nodes in packsets are less organized. As you said, we may need do the removing work in GVN **after vectorization** (maybe less maintainable) or collect related info mapping all nodes to different statements **before loop unrolling**, just like post-loop-vectorizer does (seems costly). Maybe it depends on if C2 in the future will have any separate analysis phase for Auto-Vectorization and where it locates.

Thanks.

**Comment by eme64** [comment]
Hi @fg1417 I will think a bit more about the "useless sign extension" myself (https://github.com/openjdk/jdk/pull/7954). It would probably be nice to have a large collection of shapes. Maybe there is a way to "ignore" these ops and mark them as such. We would then "ignore" them and look through when computing the "velt", and when extending the packset. And we would have to somehow "sanitize" the graph later and remove the packs that are to be "ignored", and just rewire to their inputs.
Or we simply hack away those nodes in some pre-vectorization phase, or while determining the "velt" type. But that all sounds a bit hacky.

---

 
I think we may have to chose **Composition** over the **SuperClass** idea, like @chhagedorn had suggested.

We could make this new utility class a **LoopAnalyzer**, which can then be passed to different **Vectorizers**.
We can then run the LoopAnalyzer only once, and determine `velt`, `dependencies`, `loop membership` etc.
And then we can call multiple Vectorizers (maybe different strategies, or SLP vs widening directly), and each one of those can propose a "vectorization transformation plan". We then determine which one to chose with a cost model.
Having a SuperClass would mean that every Vectorizer needs to rerun the basic analysis, with runtime and memory overhead.

I know this would require a bigger refactoring, where we have to re-route many calls that now to to SuperWord directly to this new LoopAnalyzer. We can also do that in multiple steps, you do one part and I the other, for example.

Here one of my blog-posts that give more ideas about having multiple Vectorizers:
https://eme64.github.io/blog/2023/11/03/C2-AutoVectorizer-Improvement-Ideas.html

**Pull request closed without merging**
