### PR TITLE
JDK-8307908: [ppc] Add failing RTM tests to ProblemList until 8307907 is fixed.

### PR DESCRIPTION
**Pull request by TOatGithub**
From JDK-8307907: 
The support of Transactional Memory has been removed in the Power 10 processor.
The removed instructions are still recognized, but all locking fails. This makes some jtreg tests fail.
Remove implementation from ppc port.
Disable corresponding jtreg tests.
Remove entries refering to ppc from ProblemLists.

Problem list tests on AIX which fail in Power9 Compatibility mode. See JBS for details.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307908](https://bugs.openjdk.org/browse/JDK-8307908): [ppc] Add failing RTM tests to ProblemList until 8307907 is fixed.

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14036/head:pull/14036` \
`$ git checkout pull/14036`

Update a local copy of the PR: \
`$ git checkout pull/14036` \
`$ git pull https://git.openjdk.org/jdk.git pull/14036/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14036`

View PR using the GUI difftool: \
`$ git pr show -t 14036`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14036.diff">https://git.openjdk.org/jdk/pull/14036.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14036#issuecomment-1556965937)

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
LGTM

**Review by GoeLin — APPROVED** [review]
LGTM, too.

**Pull request closed without merging**
