### PR TITLE
8288933: Improve the implementation of Double/Float.isInfinite

### PR DESCRIPTION
**Pull request by merykitty**
Improve the implementation of `Double/Float.isInfinite` to reduce branching. Using `>` comparison with `MAX_VALUE` instead of `==` with `POSITIVE_INFINITY` improves code emission on x86 and produces similar code for arm. This is also the way gcc implements `std::isinf` on x86 and arm (clang uses the pattern `Math.abs(v) == POSITIVE_INFINITY` on arm).

`test/micro/org/openjdk/bench/java/lang/FPComparison.java` has been added in #8525, the results are reshown here:

    Benchmark                      Mode  Cnt     Score     Error    Score     Error   Unit   Ratio
    FPComparison.isInfiniteDouble  avgt    5  1232.800 ±  31.677  621.185 ±  11.935  ns/op    1.98
    FPComparison.isInfiniteFloat   avgt    5  1234.708 ±  70.239  623.566 ±  15.206  ns/op    1.98

Thank you very much.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288933](https://bugs.openjdk.org/browse/JDK-8288933): Improve the implementation of Double/Float.isInfinite

### Reviewers
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9238/head:pull/9238` \
`$ git checkout pull/9238`

Update a local copy of the PR: \
`$ git checkout pull/9238` \
`$ git pull https://git.openjdk.org/jdk pull/9238/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9238`

View PR using the GUI difftool: \
`$ git pr show -t 9238`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9238.diff">https://git.openjdk.org/jdk/pull/9238.diff</a>

</details>

### CODE REVIEW

**Comment by jddarcy** [comment]
@merykitty, the proposed change is functionally correct.

@cl4es, what set of platforms do we usually consider for evaluating performance changes like this?

**Comment by cl4es** [comment]
> @cl4es, what set of platforms do we usually consider for evaluating performance changes like 

A mix of x86 and aarch64 systems, some old, some new. We could run the microbenchmark on our internal performance system to verify the reported performance gain. I assume the first score column is the baseline and the second the patched version, so a 2x gain on x86, right @merykitty?

**Comment by merykitty** [comment]
@cl4es  yes the former numbers are the baseline and the latters are of this patch

**Comment by merykitty** [comment]
May I have a review for this patch, please? Thanks a lot.

**Review by cl4es — APPROVED** [review]
Looks good to me!

(Sorry for the long delay, I've been out for a while and forgot to formally review this.)

**Comment by merykitty** [comment]
@cl4es Thanks very much for your review, I believe this change is trivial, right?
/integrate

**Review by jddarcy — APPROVED** [review]

**Pull request closed without merging**
