### PR TITLE
8286872: Refactor add/modify notification icon (TrayIcon)

### PR DESCRIPTION
**Pull request by aivanov-jdk**
Encapsulate the logic of adding or modifying a notification icon aka tray icon. This is to avoid code duplication between [`AwtTrayIcon::WmTaskbarCreated`](https://github.com/openjdk/jdk/blob/7b988b31c661c6e3e58cf8ced81732e40a79d4f5/src/java.desktop/windows/native/libawt/windows/awt_TrayIcon.cpp#L477) and [`AwtTrayIcon::_UpdateIcon`](https://github.com/openjdk/jdk/blob/7b988b31c661c6e3e58cf8ced81732e40a79d4f5/src/java.desktop/windows/native/libawt/windows/awt_TrayIcon.cpp#L796).

Separating adding and modifying the icon simplifies the methods, the actions are clearer: adding the icon requires sending `NIM_SETVERSION` message whereas modifying the icon doesn't.

To verify the code works as before, I used `TrayIconScalingTest.java`. I killed explorer.exe process to verify the notification icon gets added. Changing DPI of the main display updates the displayed icon as expected.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286872](https://bugs.openjdk.java.net/browse/JDK-8286872): Refactor add/modify notification icon (TrayIcon)

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.java.net/census#azvegint) (@azvegint - **Reviewer**)
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)
 * [Harshitha Onkar](https://openjdk.java.net/census#honkar) (@honkar-jdk - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8749/head:pull/8749` \
`$ git checkout pull/8749`

Update a local copy of the PR: \
`$ git checkout pull/8749` \
`$ git pull https://git.openjdk.java.net/jdk pull/8749/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8749`

View PR using the GUI difftool: \
`$ git pr show -t 8749`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8749.diff">https://git.openjdk.java.net/jdk/pull/8749.diff</a>

</details>

### CODE REVIEW

**Review by azvegint — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
I replaced the calls to `SendTrayMessage(NIM_MODIFY)` with `ModifyTrayIcon()` for consistency and changed both `AddTrayIcon()` and `ModifyTrayIcon()` to inline methods which should remove an overhead of additional function call.

I also moved `SendTrayMessage` into private section of the class, it's used internally only.

**Review by azvegint — APPROVED** [review]
Still looks good.

**Review by azuev-java — APPROVED** [review]

**Review by honkar-jdk — APPROVED** [review]

**Review by honkar-jdk — APPROVED** [review]

**Pull request closed without merging**
