### PR TITLE
8272228: G1: G1CardSetInlinePtr Fix tautological assertion

### PR DESCRIPTION
**Pull request by walulyai**
Hi all,

Please review this cleanup to remove unreliable asserts in G1CardSetInlinePtr.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272228](https://bugs.openjdk.java.net/browse/JDK-8272228): G1: G1CardSetInlinePtr Fix tautological assertion

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5069/head:pull/5069` \
`$ git checkout pull/5069`

Update a local copy of the PR: \
`$ git checkout pull/5069` \
`$ git pull https://git.openjdk.java.net/jdk pull/5069/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5069`

View PR using the GUI difftool: \
`$ git pr show -t 5069`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5069.diff">https://git.openjdk.java.net/jdk/pull/5069.diff</a>

</details>

### CODE REVIEW

**Comment by albertnetymk** [comment]
I think the intention here is sth like: `assert((_value & CardSetPtrTypeMask) == CardSetInlinePtr)`.

**Comment by walulyai** [comment]
> I think the intention here is sth like: `assert((_value & CardSetPtrTypeMask) == CardSetInlinePtr)`.
yes, that might be better than just removing them

**Review by albertnetymk — APPROVED** [review]
The JBS ticket title needs to be updated.

**Review by tschatzl — APPROVED** [review]
Lgtm. Please fix the CR title.

**Comment by walulyai** [comment]
Thanks @albertnetymk and @tschatzl for the reviews.

/integrate

**Pull request closed without merging**
