### PR TITLE
JDK-8303181: Memory leak in ClassLoaderExt::setup_app_search_path

### PR DESCRIPTION
**Pull request by jcking**
Fix memory leak by removing unnecessary `os::strdup` call. The string is passed as a const pointer to all functions.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8303181](https://bugs.openjdk.org/browse/JDK-8303181): Memory leak in ClassLoaderExt::setup_app_search_path

### Reviewers
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12748/head:pull/12748` \
`$ git checkout pull/12748`

Update a local copy of the PR: \
`$ git checkout pull/12748` \
`$ git pull https://git.openjdk.org/jdk pull/12748/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12748`

View PR using the GUI difftool: \
`$ git pr show -t 12748`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12748.diff">https://git.openjdk.org/jdk/pull/12748.diff</a>

</details>

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
Looks good. Thanks!
I also ran tiers 1 and 2 testing and it passed.

**Comment by dholmes-ora** [comment]
The problem here is that to reuse that string you have to know how/where it was originally allocated and know that it will remain safe to touch (assuming it is touched) for the lifetime of the code doing the touching. That might be true in this case but establishing that is a lot of effort, and ensuring it remains true is also then a problem. A strdup and subsequent free makes things a whole lot simpler IMO.

**Comment by jcking** [comment]
@dholmes-ora Switched to `os::strdup_check_oom` with `os::free` per your suggestion.

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks.

**Review by calvinccheung — APPROVED** [review]
Updates look good. Thanks.

**Pull request closed without merging**
