### PR TITLE
8257912: Convert enum iteration to use range-based for loops

### PR DESCRIPTION
**Pull request by iklam**
Now that [range-based for loops](https://github.com/openjdk/jdk/pull/1488) are allowed by the [HotSpot Style Guide](https://github.com/openjdk/jdk/blob/52ab72127ddc3ca6575d9d58503ec39c5dff7ab1/doc/hotspot-style.md), I have converted the more verbose syntax:

```
for (vmIntrinsicsIterator it = vmIntrinsicsRange.begin(); it != vmIntrinsicsRange.end(); ++it) {
  vmIntrinsicID index = *it;
  nt[as_int(index)] = string;
}
```

to

```
  for (vmIntrinsicID index : EnumRange<vmIntrinsicID>{}) {
    nt[as_int(index)] = string;
  }
```

I also removed the "convenient" declarations such as `vmIntrinsicsRange` and `vmIntrinsicsIterator` -- these are useful only when writing a traditional for loop, and are probably confusing to everyone else.  I've left examples in enumIterator.hpp in case anyone wants to write a traditional for loop.

I also added gtest cases for using range-based for loops with `EnumRange<>`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257912](https://bugs.openjdk.java.net/browse/JDK-8257912): Convert enum iteration to use range-based for loops

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 26ad3f0d125ad6ed118c1d9d9f1bf8c1174b0fbc
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 26ad3f0d125ad6ed118c1d9d9f1bf8c1174b0fbc
 * [Gerard Ziemski](https://openjdk.java.net/census#gziemski) (@gerard-ziemski - Committer) ⚠️ Review applies to 26ad3f0d125ad6ed118c1d9d9f1bf8c1174b0fbc

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1707/head:pull/1707`
`$ git checkout pull/1707`

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
Lgtm

**Comment by gerard-ziemski** [comment]
I like the change very much.

Did you consider leaving the convenience symbol "vmSymbolsIterator" as is and then using it in the loop, so instead of:

`for (vmSymbolID index : EnumRange<vmSymbolID>{}) {`

we would have:

`for (vmSymbolID index : vmSymbolsIterator) {`

which would be more concise (but less self-documenting I guess) and more similar to:

`for (JVMFlagOrigin origin : range) {`

**Review by gerard-ziemski — APPROVED** [review]

**Comment by iklam** [comment]
> I like the change very much.
> 
> Did you consider leaving the convenience symbol "vmSymbolsIterator" as is and then using it in the loop, so instead of:
> 
> `for (vmSymbolID index : EnumRange<vmSymbolID>{}) {`
> 
> we would have:
> 
> `for (vmSymbolID index : vmSymbolsIterator) {`
> 
> which would be more concise (but less self-documenting I guess) and more similar to:
> 
> `for (JVMFlagOrigin origin : range) {`

Hi Gerard, thanks for the review.

`vmSymbolsIterator` is the "cursor" type. I think you meant this:

```
for (vmSymbolID index : vmSymbolsRange{}) {...}
```

which is probably less readable, because you have to find out what `vmSymbolsRange` actually is.

I think the following pattern is easier to read. It will also make the iteration of different enum types more consistent. Iteration of any enum type  *E* can be done the same way with EnumRange<*E*>. You don't need to invent a new *E*Range  type.

```
for (MyEnumType e : EnumRange<MyEnumType>{}) {...}`
```

Note that the `{}` is required here because we need to construct an instance of `EnumRange<MyEnumType>` with its no-arg constructor. You can also use `()` but I think that would be less readable -- it's not clear whether you are calling a function or constructing an object. With `{}`, it's clear that we are making an [initialization](https://en.cppreference.com/w/cpp/language/initialization) with the brace operator.

You can also initialize a non-default range with `EnumRange<MyEnumType>{start, end}`, etc.

**Pull request closed without merging**
