### PR TITLE
8258508: Merge G1RedirtyCardsQueue into qset

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to G1RedirtyCardsLocalQueueSet to directly
incorporate the associated queue, simplifying usage.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258508](https://bugs.openjdk.java.net/browse/JDK-8258508): Merge G1RedirtyCardsQueue into qset

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 06057eb0718d4cf5d79fb8e231f15ad4bc026f8f
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to 06057eb0718d4cf5d79fb8e231f15ad4bc026f8f

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2325/head:pull/2325`
`$ git checkout pull/2325`

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]
Looks good!

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @walulyai for reviews.

**Pull request closed without merging**
