### PR TITLE
8258772: Some runtime/cds tests fail with +LogCompilation or +StressX

### PR DESCRIPTION
**Pull request by robcasloz**
Emit warning about TraceDependencies results in `ClassHierarchyWalker::count_find_witness_calls()` only if `TraceDependencies` is actually enabled. Use standard `warning()` function instead of ad hoc printing. Remove warning about using `Stress(LCM|GCM|IGVN)` without `LogCompilation` in `Compile::Compile()`, and add the information to the description of the `StressSeed` option instead. These changes prevent false test failures when using `LogCompilation` or `Stress(LCM|GCM|IGVN)`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258772](https://bugs.openjdk.java.net/browse/JDK-8258772): Some runtime/cds tests fail with +LogCompilation or +StressX

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 4ef1e830909f63b2bc920306a78ca902e72be151
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1863/head:pull/1863`
`$ git checkout pull/1863`

### CODE REVIEW

**Comment by robcasloz** [comment]
/summary
Emit warning about TraceDependencies results in
ClassHierarchyWalker::count_find_witness_calls() only if TraceDependencies is
actually enabled. Use standard warning() function instead of ad hoc printing.
Remove warning about using Stress(LCM|GCM|IGVN) without LogCompilation in
Compile::Compile(), and add the information to the description of the StressSeed
option instead. These changes prevent false test failures when using
LogCompilation or Stress(LCM|GCM|IGVN).

**Comment by robcasloz** [comment]
Tested on hs-tier1-3 with the following configurations:
- no additional options, {windows-x64, linux-x64, linux-aarch64, macosx-x64}, {release, debug};
- `+LogCompilation`, linux-x64, debug; and
- `+StressIGVN`, linux-x64, debug.

Four failures were found using `+LogCompilation`. The failures are independent of these proposed changes (unrelated to warning emission), and have been reported separately (https://bugs.openjdk.java.net/browse/JDK-8258814).

**Review by chhagedorn — APPROVED** [review]
Looks good to me!

**Comment by robcasloz** [comment]
> Looks good to me!

Thanks for reviewing, Christian.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks for the review, Vladimir!

I will postpone my request for integration until I am back from holidays.

**Comment by robcasloz** [comment]
I just realized the headers of the touched files need to be update with the current copyright year. Withdrawing request for integration again, sorry for going back and forth.

**Comment by robcasloz** [comment]
Ready for review after updating copyright headers.

**Review by chhagedorn — APPROVED** [review]

**Review by TobiHartmann — APPROVED** [review]

**Comment by robcasloz** [comment]
Thanks for re-reviewing, Christian and Tobias!

**Pull request closed without merging**
