### PR TITLE
8287854: Dangling reference in ClassVerifier::verify_class

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small change to fix JDK_8287854.  The fix was tested with JCK lang and VM tests, Mach5 tiers 1 and 2 on Linux, Mac OS, and Windows (in progress), and Mach5 tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287854](https://bugs.openjdk.org/browse/JDK-8287854): Dangling reference in ClassVerifier::verify_class

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9075/head:pull/9075` \
`$ git checkout pull/9075`

Update a local copy of the PR: \
`$ git checkout pull/9075` \
`$ git pull https://git.openjdk.java.net/jdk pull/9075/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9075`

View PR using the GUI difftool: \
`$ git pr show -t 9075`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9075.diff">https://git.openjdk.java.net/jdk/pull/9075.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
The change is functionally correct, but this seems like a textbook case for a RAII helper class.

**Comment by iklam** [comment]
> The change is functionally correct, but this seems like a textbook case for a RAII helper class.

I agree with David that RAII is needed here. There's one exit path that's not covered by the existing patch:

```
void ClassVerifier::verify_class(TRAPS) {
   ...
   verify_method(methodHandle(THREAD, m), CHECK_VERIFY(this));
   ...
}
```

**Review by coleenp — COMMENTED** [review]
I think this table should be created in the ClassVerifier constructor instead.  Is there only this one caller of verify_class() ?
    ClassVerifier split_verifier(jt, klass);
    // We don't use CHECK here, or on inference_verify below, so that we can log any exception.
    split_verifier.verify_class(THREAD);

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Needs further work.

**Comment by hseigel** [comment]
Please review this new fix that uses Coleen's suggestion to embed the method_signatures_table in the ClassVerifier class.

Thanks, Harold

**Review by coleenp — APPROVED** [review]
This looks really good. The lifetime of ClassVerifier and this method signature table match.

**Review by dholmes-ora — APPROVED** [review]
Much cleaner solution - thanks Harold and Coleen.

**Pull request closed without merging**
