### PR TITLE
8262409: sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions. SSL test failures caused by java failed with "Server reported the wrong exception"

### PR DESCRIPTION
**Pull request by fguallini**
The test `SSLSocketImplThrowsWrongExceptions` is failing intermittently after the change: [JDK-8259662: Don't wrap SocketExceptions into SSLExceptions in SSLSocketImpl](https://bugs.openjdk.java.net/browse/JDK-8259662)

Since SocketExceptions are not wrapped into SSLException, also need to be caught. Other tests that were expecting a SSLException to be thrown under certain condition were updated with a similar fix in the change previously mentioned.

In addition, thread.sleep was replaced with a CountDownLatch for client/server synchronization

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262409](https://bugs.openjdk.java.net/browse/JDK-8262409): sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions. SSL test failures caused by java failed with "Server reported the wrong exception"

### Reviewers
 * [Rajan Halade](https://openjdk.java.net/census#rhalade) (@rhalade - **Reviewer**)
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4308/head:pull/4308` \
`$ git checkout pull/4308`

Update a local copy of the PR: \
`$ git checkout pull/4308` \
`$ git pull https://git.openjdk.java.net/jdk pull/4308/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4308`

View PR using the GUI difftool: \
`$ git pr show -t 4308`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4308.diff">https://git.openjdk.java.net/jdk/pull/4308.diff</a>

</details>

### CODE REVIEW

**Review by rhalade — APPROVED** [review]

**Review by XueleiFan — APPROVED** [review]

**Comment by cliveverghese** [comment]
Thank you @fguallini for fixing this test. 

Should the SocketException be expected by the client logic as well?
https://github.com/openjdk/jdk/blob/3631a39a4797919acbc7862cb94fa7f7be7f4f8a/test/jdk/sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions.java#L135

**Comment by fguallini** [comment]
> Thank you @fguallini for fixing this test.
> 
> Should the SocketException be expected by the client logic as well?
> https://github.com/openjdk/jdk/blob/3631a39a4797919acbc7862cb94fa7f7be7f4f8a/test/jdk/sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions.java#L135

Thanks, I did look at this but the SocketException was not thrown in the client side in any of the thousands of times I executed the test with the current PR fix, it does not seem to be necessary to expect the exception there

**Comment by cliveverghese** [comment]
Thank you for verifying.

**Pull request closed without merging**
