### PR TITLE
8341997: Tests create files in src tree instead of scratch dir

### PR DESCRIPTION
**Pull request by bplb**
Change property `test.src` to `test.dir`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341997](https://bugs.openjdk.org/browse/JDK-8341997): Tests create files in src tree instead of scratch dir (**Bug** - P2)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21503/head:pull/21503` \
`$ git checkout pull/21503`

Update a local copy of the PR: \
`$ git checkout pull/21503` \
`$ git pull https://git.openjdk.org/jdk.git pull/21503/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21503`

View PR using the GUI difftool: \
`$ git pr show -t 21503`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21503.diff">https://git.openjdk.org/jdk/pull/21503.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21503#issuecomment-2411876692)

### CODE REVIEW

**Review by erikj79 — COMMENTED** [review]
I can't find any reference to `test.dir` in the jtreg documentation. I would expect to see it here https://openjdk.org/jtreg/tag-spec.html#testvars. My understanding is that you should just use the current working directory for temporary files: https://openjdk.org/jtreg/faq.html#scratch-directory

**Comment by bplb** [comment]
The property `test.dir` has been used as a convention but I've no problem with changing it to the CWD.

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
> The property `test.dir` has been used as a convention but I've no problem with changing it to the CWD.

I wasn't aware, but if it's convention, I'm ok with it.

**Comment by erikj79** [comment]
I'm taking this fix for a spin over night in the environment where I noticed the problem.

**Comment by bplb** [comment]
> I'm taking this fix for a spin over night in the environment where I noticed the problem.

I'll hold off integrating until that is over.

**Review by jaikiran — APPROVED** [review]
This test-only change looks OK to me.

**Comment by erikj79** [comment]
> > I'm taking this fix for a spin over night in the environment where I noticed the problem.
> 
> I'll hold off integrating until that is over.

Test successful, thanks for fixing this!

**Comment by bplb** [comment]
> Test successful, thanks for fixing this!

Thanks @erikj79 and @jaikiran for the reviews!

**Pull request closed without merging**
