### PR TITLE
Fix clang build by addressing strict c++17-extensions and deprecated-non-prototype clang warnings

### PR DESCRIPTION
**Pull request by antbob**
Currently clang build (--with-toolchain-type=clang) is broken due to the following warnings that result in errors by default:

```
src/hotspot/os/linux/os_linux.cpp:2843:65: error: 'static_assert' with no message is a C++17 extension [-Werror,-Wc++17-extensions]
  static_assert(MAP_FIXED_NOREPLACE == MAP_FIXED_NOREPLACE_value);
                                                                ^
                                                                , ""
1 error generated.

src/java.base/unix/native/libnet/DefaultProxySelector.c:378:41: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
    proxies = (*g_proxy_resolver_lookup)(resolver, uri, NULL, &error);
                                        ^
src/java.base/unix/native/libnet/DefaultProxySelector.c:397:63: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                                (*g_network_address_parse_uri)(proxies[i], 0,
                                                              ^
src/java.base/unix/native/libnet/DefaultProxySelector.c:402:70: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                            phost = (*g_network_address_get_hostname)(conn);
                                                                     ^
src/java.base/unix/native/libnet/DefaultProxySelector.c:403:66: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                            pport = (*g_network_address_get_port)(conn);
                                                                 ^
src/java.base/unix/native/libnet/DefaultProxySelector.c:445:22: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
        (*g_strfreev)(proxies);
                     ^
src/java.base/unix/native/libnet/DefaultProxySelector.c:448:25: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
        (*g_clear_error)(&error);
                        ^
6 errors generated.
```

These can be rectified by adding related ignore flags to configure:

--with-extra-cxxflags="-Wno-c++17-extensions"
--with-extra-cflags="-Wno-deprecated-non-prototype"

however it would be nice to have clang toolchain build just work out of the box.

While this looks like a "sweep it under the carpet" kinda fix and it would probably have been better to address the warnings in the code, the patch just make things on par with gcc toolchain which is not as strict by default (it might produce similar errors with pedantic tho), see

https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15928/head:pull/15928` \
`$ git checkout pull/15928`

Update a local copy of the PR: \
`$ git checkout pull/15928` \
`$ git pull https://git.openjdk.org/jdk.git pull/15928/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15928`

View PR using the GUI difftool: \
`$ git pr show -t 15928`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15928.diff">https://git.openjdk.org/jdk/pull/15928.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
> While this looks like a "sweep it under the carpet" kinda fix and it would probably have been better to address the warnings in the code, the patch just make things on par with gcc toolchain which is not as strict by default

There are already difference between tool chains. For instance: when compiling on Windows using MSVC, this might produce no warnings. While compiling the same code with GCC can reproduce warnings (and sometimes vice versa). I think it is not unreasonable to expect that the warnings are address in the code in that case, rather than disabling them for one of the compilers.

In this case too: I agree that it would probably be better to address the warnings in the code instead.

**Comment by antbob** [comment]
@JornVernee Here is the patch addressing this in the code. Note that GLib related changes do not really address related code issues as the code is kinda sketchy since its operating on dlsym points so there is no way to actually ensure any safety/correctness of types there without bringing in related GLib includes and libs which I guess is not desired as dependency hence dlsyms use in the first place so it is what it is then.

The only reason this is actually better than simply ignoring those strict clang warnings (as in 1st rev) is for any future code changes that might bring any violations of similar origin. Other than that it is kinda moot.

**Comment by antbob** [comment]
well, it looks like there isn't much interest here to get this fixed so i wont be updating this patch as that would be further waste of time on my part. although i see some related changes are making it to master so hopefully this gets fixed eventually.

**Comment by magicus** [comment]
@antbob I don't think the silence necessarily mean that the no-one is interested in the patch. Just as likely, no-one has noticed the PR. Until it becomes flagged as "ready for review", it will not be announced on the mailing list, which is the primary way people in OpenJDK track new PRs.

In this case, your blocker is `Commit message must refer to an issue`. That is, the PR title must start with a reference to a bug on the JBS bug tracker. Since you are not yet a JDK author, you cannot create such a bug. I have opened https://bugs.openjdk.org/browse/JDK-8319738 for you. I shortened the title a bit, so you will have to update the title of this PR to `8319738: Fix building with clang on Linux`.

**Comment by magicus** [comment]
@antbob The process for contributing to OpenJDK is slightly different than compared to many other (smaller) projects on GitHub. A great resource for understanding how the process works can be found in the Developer's guide: https://openjdk.org/guide/#contributing-to-an-openjdk-project

**Comment by djelinski** [comment]
Wasn't this fixed by #16092?

**Comment by magicus** [comment]
It indeed looks that way; just about the exact same patch. That PR was pushed Oct 17, this PR was created Sep 26. I'm guessing this was just caught in limbo for too long. @antbob Thank you for your effort, even if it the problem was resolved before your patch could be evaluated. I'm going to close the corresponding JBS issue. I recommend you close this PR.

**Comment by antbob** [comment]
@magicus thanks for getting involved and sorting this out! good to hear it is fixed now.

**Pull request closed without merging**
