### PR TITLE
JDK-8312461 JNI warnings in SunMSCApi provider

### PR DESCRIPTION
**Pull request by mcpowers**
https://bugs.openjdk.org/browse/JDK-8312461

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312461](https://bugs.openjdk.org/browse/JDK-8312461): JNI warnings in SunMSCApi provider (**Bug** - P4)

### Reviewers
 * [Valerie Peng](https://openjdk.org/census#valeriep) (@valeriepeng - **Reviewer**) ⚠️ Review applies to [50f1d16a](https://git.openjdk.org/jdk/pull/15113/files/50f1d16aa24c7d1312b13c6774ad96cdf9eda816)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15113/head:pull/15113` \
`$ git checkout pull/15113`

Update a local copy of the PR: \
`$ git checkout pull/15113` \
`$ git pull https://git.openjdk.org/jdk.git pull/15113/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15113`

View PR using the GUI difftool: \
`$ git pr show -t 15113`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15113.diff">https://git.openjdk.org/jdk/pull/15113.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15113#issuecomment-1661110458)

### CODE REVIEW

**Comment by mcpowers** [comment]
I was able to reproduce the problem with mach5 and verify that the WARNING was gone after the fix. The hardest thing about this bug was figuring out how to set `-Xcheck:jni` on the mach5 command line. It's not something I do every day.

**Review by valeriepeng — APPROVED** [review]
Changes look good. 
BTW, need to add noreg-xxx label to the bug.

**Comment by mcpowers** [comment]
@valeriepeng Thanks for the review!

**Review by djelinski — APPROVED** [review]

**Comment by djelinski** [comment]
Please update the copyright.

**Review by djelinski — APPROVED** [review]

**Pull request closed without merging**
