### PR TITLE
8341788: Fix ExceptionOccurred in hotspot

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
A trivial JNI refactoring in Hotspot to use `ExceptionCheck()` over `ExceptionOccurred()` when the usage is treating the return value as a boolean. This is part of the bigger umbrella issue: [JDK-8341542](https://bugs.openjdk.org/browse/JDK-8341542). 

>     ExceptionCheck
>     We introduce a convenience function to check for pending exceptions without creating a local reference to the exception object.
> 
>     jboolean ExceptionCheck(JNIEnv *env);
> 
>     Returns JNI_TRUE when there is a pending exception; otherwise, returns JNI_FALSE.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341788](https://bugs.openjdk.org/browse/JDK-8341788): Fix ExceptionOccurred in hotspot (**Sub-task** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21724/head:pull/21724` \
`$ git checkout pull/21724`

Update a local copy of the PR: \
`$ git checkout pull/21724` \
`$ git pull https://git.openjdk.org/jdk.git pull/21724/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21724`

View PR using the GUI difftool: \
`$ git pr show -t 21724`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21724.diff">https://git.openjdk.org/jdk/pull/21724.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21724#issuecomment-2438935657)

### CODE REVIEW

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
@justin-curtis-lu  you have missed a large number of usages:
```
./share/prims/nativeEntryPoint.cpp:  guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/prims/methodHandles.cpp:    guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/prims/methodHandles.cpp:    guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/prims/methodHandles.cpp:    guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/prims/upcallLinker.cpp:  guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/prims/unsafe.cpp:  if (env->ExceptionOccurred()) {
./share/prims/upcallStubs.cpp:  guarantee(status == JNI_OK && !env->ExceptionOccurred(),
./share/runtime/continuation.cpp:    guarantee(!env->ExceptionOccurred(), "register jdk.internal.vm.Continuation natives");
```

Thanks

**Comment by justin-curtis-lu** [comment]
Thanks for taking a look and catching those other occurrences @dholmes-ora. Addressed in https://github.com/openjdk/jdk/pull/21724/commits/c3ecb692c8fba1ce164169340a7d97785699e58f.
(Updated the JBS subtask issue as well to include those cases)

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks

**Comment by justin-curtis-lu** [comment]
Thank you for the review.
/integrate

**Comment by dholmes-ora** [comment]
@justin-curtis-lu  for future reference note that hotspot generally requires two reviews per PR before integration. This was a very simple change but not "trivial" in the sense documented in the developer guide. Thanks.

**Comment by justin-curtis-lu** [comment]
@dholmes-ora understood, thanks for the heads up.

**Pull request closed without merging**
