### PR TITLE
8277428: G1: Move and inline G1STWIsAliveClosure::do_object_b

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is a trivial patch to move G1STWIsAliveClosure::do_object_b definition to the right file g1CollectedHeap.inline.hpp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277428](https://bugs.openjdk.java.net/browse/JDK-8277428): G1: Move and inline G1STWIsAliveClosure::do_object_b

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6470/head:pull/6470` \
`$ git checkout pull/6470`

Update a local copy of the PR: \
`$ git checkout pull/6470` \
`$ git pull https://git.openjdk.java.net/jdk pull/6470/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6470`

View PR using the GUI difftool: \
`$ git pr show -t 6470`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6470.diff">https://git.openjdk.java.net/jdk/pull/6470.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — CHANGES_REQUESTED** [review]
Without checking performance, I think the definition should be moved to `g1CollectedHeap.inline.hpp`, not the .cpp file (and includes fixed up).

It's used on every reference for a few operations.

**Comment by Hamlin-Li** [comment]
Thanks Thomas.

Not sure if this method be inlined in original code, but I inline it anyway as you suggested.

**Comment by kstefanj** [comment]
A lot of the changes to include `g1CollectedHeap.inline.hpp` look strange to me, are they really needed? And the normal `hpp`-files that now include it are wrong, we should never have normal `hpp`-files including `inline.hpp`-files.

**Comment by Hamlin-Li** [comment]
Thanks Stefan, I remove the unnecessary inline includes.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by kstefanj — APPROVED** [review]
👍

**Comment by Hamlin-Li** [comment]
Thansk @tschatzl @kstefanj for your reviews.

/integrate

**Pull request closed without merging**
