### PR TITLE
JDK-8299481: Remove metaprogramming/removePointer.hpp

### PR DESCRIPTION
**Pull request by jcking**
Code cleanup of pre-C++11 <type_traits> implementations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299481](https://bugs.openjdk.org/browse/JDK-8299481): Remove metaprogramming/removePointer.hpp

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [33dc873a](https://git.openjdk.org/jdk/pull/11817/files/33dc873ae0e4217d9f1e2fe1c8fae298108d0515)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11817/head:pull/11817` \
`$ git checkout pull/11817`

Update a local copy of the PR: \
`$ git checkout pull/11817` \
`$ git pull https://git.openjdk.org/jdk pull/11817/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11817`

View PR using the GUI difftool: \
`$ git pr show -t 11817`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11817.diff">https://git.openjdk.org/jdk/pull/11817.diff</a>

</details>

### CODE REVIEW

**Comment by jcking** [comment]
@kimbarrett Another one.

**Review by tschatzl — APPROVED** [review]

**Review by kimbarrett — APPROVED** [review]

**Pull request closed without merging**
