### PR TITLE
8323086: Shenandoah: Heap could be corrupted by oom during evacuation

### PR DESCRIPTION
**Pull request by earthling-amzn**
When the load reference barrier is unable to evacuate an object, it initiates a degenerated cycle, and allows the from-space reference past the barrier. The degenerated cycle is meant to patch up these references, but if the reference is written above the update-watermark, it will be missed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323086](https://bugs.openjdk.org/browse/JDK-8323086): Shenandoah: Heap could be corrupted by oom during evacuation (**Bug** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - no project role)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17285/head:pull/17285` \
`$ git checkout pull/17285`

Update a local copy of the PR: \
`$ git checkout pull/17285` \
`$ git pull https://git.openjdk.org/jdk.git pull/17285/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17285`

View PR using the GUI difftool: \
`$ git pr show -t 17285`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17285.diff">https://git.openjdk.org/jdk/pull/17285.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17285#issuecomment-1879140424)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Debugging of JDK-8322804 suggests that this is the necessary fix.

**Review by shipilev — APPROVED** [review]
Looks fine.

**Pull request closed without merging**
