### PR TITLE
8255595: delay_to_keep_mmu passes wrong arguments to Monitor wait

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this trivial fix of the second argument in a call to MonitorLocker::wait.  Because the locker is constructed as no-safepoint-checking, the improper second argument is ignored rather than possibly going into an unexpected state.

/summary Remove improper wait argument.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255595](https://bugs.openjdk.java.net/browse/JDK-8255595): delay_to_keep_mmu passes wrong arguments to Monitor wait

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to b42f992c1ea2b455c73b4c049c1b20a1c5454db9
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to b42f992c1ea2b455c73b4c049c1b20a1c5454db9
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Author) ⚠️ Review applies to b42f992c1ea2b455c73b4c049c1b20a1c5454db9

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/934/head:pull/934`
`$ git checkout pull/934`

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good!

**Review by tschatzl — APPROVED** [review]
Lgtm and trivial.

**Comment by albertnetymk** [comment]
I wonder if it's feasible and/or worthwhile to use `clang-tidy` (or sth similar) to detect this kind of error in existing code and prevent it from happening again in new code.

**Review by albertnetymk — APPROVED** [review]

**Comment by kimbarrett** [comment]
> I wonder if it's feasible and/or worthwhile to use `clang-tidy` (or sth similar) to detect this kind of error in existing code and prevent it from happening again in new code.

See https://bugs.openjdk.java.net/browse/JDK-8255596

**Comment by albertnetymk** [comment]
> See https://bugs.openjdk.java.net/browse/JDK-8255596

Thank you, Kim.

**Pull request closed without merging**
