### PR TITLE
JDK-8293344: JDK-8242181 broke stack printing for non-attached threads

### PR DESCRIPTION
**Pull request by tstuefe**
https://bugs.openjdk.org/browse/JDK-8242181 gave us source infos in call stacks on Linux, which is really nice, but it made stack printing more vulnerable. We now require Thread::current, which makes stack printing fail and crash in non-attached threads. Causes truncated or missing stacks in hs-err file resp. crashes if stack printing is used outside error reporting.

I tested the fix manually.

I also am working on a testing facility for cases like these, which I will introduce in a separate RFE (see https://bugs.openjdk.org/browse/JDK-8293346).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293344](https://bugs.openjdk.org/browse/JDK-8293344): JDK-8242181 broke stack printing for non-attached threads

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10158/head:pull/10158` \
`$ git checkout pull/10158`

Update a local copy of the PR: \
`$ git checkout pull/10158` \
`$ git pull https://git.openjdk.org/jdk pull/10158/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10158`

View PR using the GUI difftool: \
`$ git pr show -t 10158`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10158.diff">https://git.openjdk.org/jdk/pull/10158.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
pinging @chhagedorn

**Review by chhagedorn — APPROVED** [review]
Looks good, thanks for fixing this! I guess I've missed that behind the PPC `ifdef`.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for fixing!

**Comment by tstuefe** [comment]
Thanks @chhagedorn and @TheRealMDoerr !

/integrate

**Pull request closed without merging**
