### PR TITLE
8261169: Upgrade HarfBuzz to the latest 2.8.0

### PR DESCRIPTION
**Pull request by prrace**
Upgrade to harfbuzz 2.8

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261169](https://bugs.openjdk.java.net/browse/JDK-8261169): Upgrade HarfBuzz to the latest 2.8.0

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3826/head:pull/3826` \
`$ git checkout pull/3826`

Update a local copy of the PR: \
`$ git checkout pull/3826` \
`$ git pull https://git.openjdk.java.net/jdk pull/3826/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3826`

View PR using the GUI difftool: \
`$ git pr show -t 3826`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3826.diff">https://git.openjdk.java.net/jdk/pull/3826.diff</a>

</details>

### CODE REVIEW

**Review by mrserb — APPROVED** [review]
I assume the build using bundled lib is fine on all our platforms.

**Comment by prrace** [comment]
> I assume the build using bundled lib is fine on all our platforms.

Yes.

**Comment by DamonFool** [comment]
Hi @prrace ,

Our CI/CD got the following build errors on x86_64 with gcc 8.3.1:
```
Building target 'images' in configuration 'linux-x86_64-server-fastdebug'
Updating support/modules_libs/java.base/server/libjvm.so due to 1 file(s)
In file included from /home/jvm/jdk/src/java.desktop/share/native/libharfbuzz/hb-ot-shape-complex-use.cc:33:
hb-ot-shape-complex-use-machine.rl: In instantiation of 'machine_index_t<Iter>::machine_index_t(const machine_index_t<Iter>&) [with Iter = hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<unnamed struct>&, 0>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<unnamed struct>&, 0> >]':
hb-ot-shape-complex-use-machine.rl:249:11:   required from here
hb-ot-shape-complex-use-machine.rl:194:9: error: base class 'struct hb_iter_with_fallback_t<machine_index_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<unnamed struct>&, 0>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<unnamed struct>&, 0> > >, hb_pair_t<unsigned int, hb_pair_t<unsigned int, hb_glyph_info_t&> > >' should be explicitly initialized in the copy constructor [-Werror=extra]
cc1plus: all warnings being treated as errors
gmake[3]: *** [/home/jvm/jdk/build/linux-x86_64-server-fastdebug/support/native/java.desktop/libfontmanager/hb-ot-shape-complex-use.o] Error 1
gmake[2]: *** [java.desktop-libs] Error 1

ERROR: Build failed for target 'images' in configuration 'linux-x86_64-server-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target support_native_java.desktop_libfontmanager_hb-ot-shape-complex-use.o:
In file included from /home/jvm/jdk/src/java.desktop/share/native/libharfbuzz/hb-ot-shape-complex-use.cc:33:
hb-ot-shape-complex-use-machine.rl: In instantiation of 'machine_index_t<Iter>::machine_index_t(const machine_index_t<Iter>&) [with Iter = hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<unnamed struct>&, 0>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<unnamed struct>&, 0> >]':
hb-ot-shape-complex-use-machine.rl:249:11:   required from here
hb-ot-shape-complex-use-machine.rl:194:9: error: base class 'struct hb_iter_with_fallback_t<machine_index_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<unnamed struct>&, 0>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<unnamed struct>&, 0> > >, hb_pair_t<unsigned int, hb_pair_t<unsigned int, hb_glyph_info_t&> > >' should be explicitly initialized in the copy constructor [-Werror=extra]
cc1plus: all warnings being treated as errors

* All command lines available in /home/jvm/jdk/build/linux-x86_64-server-fastdebug/make-support/failure-logs.
```
Could you please have a look?
I'm on a vacation this week.

Thanks.

**Comment by tstuefe** [comment]
Same here. In my case it breaks with gcc 7.5.0, which I believe is still supported.

I opened https://bugs.openjdk.java.net/browse/JDK-8266545.

**Comment by tstuefe** [comment]
https://github.com/openjdk/jdk/pull/3873

**Pull request closed without merging**
