### PR TITLE
8255000: C2: Unify IGVN processing when loop opts are over

### PR DESCRIPTION
**Pull request by iwanowww**
There is a number of use cases when ideal nodes (either individual or even the whole classes) delay some transformations until loop optimizations are over. 

Unfortunately, there are multiple solutions in the code base with their pros and cons: either a custom per-node class logic (e.g., for range check dependent `CastII` or `Opaque4` nodes) or `Compile::major_progress() == 0` as a signal that loop opts are over.   

I propose to introduce a unified approach to reliably process nodes that require (or may benefit from) IGVN pass once loop opts are finally over and migrate existing use cases to it.

After some experimentation, I decided not to rely on `Compile::major_progress()` because: 
  * it's hard to reason about its properties (there are many places where it is adjusted);
  * attempts to verify its monotonicity using asserts triggered too many sporadic failures.

So, I wasn't persuaded that `Compile::major_progress() == 0` is reliable enough and introduced a dedicated flag (`Compile::post_loop_opts_phase()`) which signals that loop opts are over.  

(The patch - 69a93d4 commit - is on top of 8255026 cleanup which is reviewed separately.)  

Testing: tier1-tier5

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ⏳ (1/1 running) | ⏳ (5/5 running) | ⏳ (2/2 running) | ⏳ (2/2 running) |

### Issue
 * [JDK-8255000](https://bugs.openjdk.java.net/browse/JDK-8255000): C2: Unify IGVN processing when loop opts are over

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to 69a93d4da54765bc44995a96145d4c1d04057959
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**) ⚠️ Review applies to 69a93d4da54765bc44995a96145d4c1d04057959
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 69a93d4da54765bc44995a96145d4c1d04057959

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/751/head:pull/751`
`$ git checkout pull/751`

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
There is a lot to like in this cleanup. Thanks!

Reviewed.

**Review by veresov — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Nice clean up.

**Comment by iwanowww** [comment]
Thanks for the reviews, Nils, Igor, and Vladimir.

**Pull request closed without merging**
