### PR TITLE
[java.desktop] Delete MutableInteger, Growable[Byte|Elt|Int|Point|Rect]Array classes.

### PR DESCRIPTION
**Pull request by SWinxy**
Add new records (Elt and Rect) to replace Growable[Elt|Rect]Array classes. `MutableInteger` is not necessary to get a value from `Map`. The GrowableXArray objects are replaced with their respective `List<X>`s, if they even are used at all. For `GrowableEltArray` and `GrowableRectArray`, new classes replace them, with custom methods to transform their arrays to `int` arrays.

/signed

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7098/head:pull/7098` \
`$ git checkout pull/7098`

Update a local copy of the PR: \
`$ git checkout pull/7098` \
`$ git pull https://git.openjdk.java.net/jdk pull/7098/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7098`

View PR using the GUI difftool: \
`$ git pr show -t 7098`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7098.diff">https://git.openjdk.java.net/jdk/pull/7098.diff</a>

</details>

### CODE REVIEW

**Comment by SWinxy** [comment]
Keeping this alive; the PR is being blocked by the OCA.

**Comment by SWinxy** [comment]
Keeping open.

**Comment by TheShermanTanker** [comment]
@SWinxy 8286272

**Comment by TheShermanTanker** [comment]
@SWinxy Sorry about what happened recently, the reviewers can be pretty harsh sometimes, don't take it too hard

**Pull request closed without merging**
