### PR TITLE
8273573: [macos12] ActionListenerCalledTwiceTest.java fails on macOS 12

### PR DESCRIPTION
**Pull request by azvegint**
This test was failing consistently on same machines and at the same time as #8532.

Test failure is also no longer reproducible after #8320 fix.

This is macOS only test, so corresponding `@requires os.family` tag was added. Testing is green.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8273573](https://bugs.openjdk.org/browse/JDK-8273573): [macos12] ActionListenerCalledTwiceTest.java fails on macOS 12

### Reviewers
 * [Prasanta Sadhukhan](https://openjdk.java.net/census#psadhukhan) (@prsadhuk - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to [9dd14689](https://git.openjdk.java.net/jdk/pull/9003/files/9dd14689c50d6e1230aeca1724c184fcae0bca07)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9003/head:pull/9003` \
`$ git checkout pull/9003`

Update a local copy of the PR: \
`$ git checkout pull/9003` \
`$ git pull https://git.openjdk.java.net/jdk pull/9003/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9003`

View PR using the GUI difftool: \
`$ git pr show -t 9003`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9003.diff">https://git.openjdk.java.net/jdk/pull/9003.diff</a>

</details>

### CODE REVIEW

**Review by prsadhuk — APPROVED** [review]
I guess you can remove @author, @modules and also jtreg "Platform" dependency by using System.getProperty("os.name") and update the copyright year

**Comment by prsadhuk** [comment]
However, there are some observations in the JBS by @prrace regarding the test which have not been handled

```
Also I noticed that the test doesn't exit. It appears that the call to

Desktop.getDesktop().setDefaultMenuBar(bar);

is effectively creating another visible window so the AWT thread doesn't exit.

Adding this line below allows the test to exit and should be added to the test
            SwingUtilities.invokeAndWait(() -> Desktop.getDesktop().setDefaultMenuBar(null)); 
```

**Review by mrserb — APPROVED** [review]

**Comment by azvegint** [comment]
> However, there are some observations in the JBS by @prrace regarding the test which have not been handled
> 
> ```
> Also I noticed that the test doesn't exit. It appears that the call to
> 
> Desktop.getDesktop().setDefaultMenuBar(bar);
> 
> is effectively creating another visible window so the AWT thread doesn't exit.
> 
> Adding this line below allows the test to exit and should be added to the test
>             SwingUtilities.invokeAndWait(() -> Desktop.getDesktop().setDefaultMenuBar(null)); 
> ```

BTW this affects only running test in a standalone mode, jtreg handles this. 
But it may be a bad example, so updated.


> I guess you can remove @author, @modules and also jtreg "Platform" dependency by using System.getProperty("os.name") and update the copyright year

Sure, but initially it was just a removal from problemlist.

Updated.

**Review by prsadhuk — APPROVED** [review]
I thought I already approved..

**Comment by azvegint** [comment]
> I thought I already approved..

Sure, it was, but it differs significantly from the approved version. Thanks.

**Pull request closed without merging**
