### PR TITLE
8246677: LinkedTransferQueue and SynchronousQueue synchronization updates

### PR DESCRIPTION
**Pull request by Martin-Buchholz**
/cc core-libs

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8246677](https://bugs.openjdk.java.net/browse/JDK-8246677): LinkedTransferQueue and SynchronousQueue synchronization updates

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Doug Lea](https://openjdk.java.net/census#dl) (@DougLea - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1645/head:pull/1645`
`$ git checkout pull/1645`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Review by DougLea — APPROVED** [review]

**Comment by eastig** [comment]
This PR causes 16x performance regression in SynchronousQueue. Details are in https://bugs.openjdk.java.net/browse/JDK-8267502

**Pull request closed without merging**
