### PR TITLE
8330302: strace004 can still fail

### PR DESCRIPTION
**Pull request by dholmes-ora**
This is a trivial point fix for the `strace` tests to add in the missing event (super)constructors. These tests have started failing more regularly after the `Thread.sleep` code was recently changed.

The fragility of these tests is well known but I simply want to deal with current failures in our CI. It remains a future RFE to fix these tests so they don't need continual updating like this.

Testing:
 - themselves
 - tier 5 (which is where we see CI failures most often)

Thanks

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330302](https://bugs.openjdk.org/browse/JDK-8330302): strace004 can still fail (**Bug** - P3)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20980/head:pull/20980` \
`$ git checkout pull/20980`

Update a local copy of the PR: \
`$ git checkout pull/20980` \
`$ git pull https://git.openjdk.org/jdk.git pull/20980/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20980`

View PR using the GUI difftool: \
`$ git pr show -t 20980`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20980.diff">https://git.openjdk.org/jdk/pull/20980.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20980#issuecomment-2347402599)

### CODE REVIEW

**Comment by AlanBateman** [comment]
So no change to test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/ThreadController.java and test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/SleepingThread.java this time?

Is there a JBS issue to re-write these tests?

**Review by AlanBateman — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the review @AlanBateman . You are right the others should be updated too even though we have never seen the constructor appear in those cases.

I couldn't find a JBS issue so filed [JDK-8340088](https://bugs.openjdk.org/browse/JDK-8340088)[JDK-8340088](https://bugs.openjdk.org/browse/JDK-8340088)

**Review by AlanBateman — APPROVED** [review]

**Review by shipilev — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Thanks for the reviews @AlanBateman and @shipilev !

/integrate

**Comment by viktorklang-ora** [comment]
Nice work, thanks @dholmes-ora!

**Pull request closed without merging**
