### PR TITLE
8313394: Array Elements in OldObjectSample event has the incorrect description

### PR DESCRIPTION
**Pull request by tkiriyama**
With this fix, arrayElements attribute in OldObjectSample event will be -1 if the object is not an array.  
Could anyone please review this fix?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313394](https://bugs.openjdk.org/browse/JDK-8313394): Array Elements in OldObjectSample event has the incorrect description (**Bug** - P4)

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15084/head:pull/15084` \
`$ git checkout pull/15084`

Update a local copy of the PR: \
`$ git checkout pull/15084` \
`$ git pull https://git.openjdk.org/jdk.git pull/15084/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15084`

View PR using the GUI difftool: \
`$ git pr show -t 15084`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15084.diff">https://git.openjdk.org/jdk/pull/15084.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15084#issuecomment-1657898096)

### CODE REVIEW

**Comment by egahlin** [comment]
A better fix is probably to update the description to match the implementation and change the JMC GUI to display integer min value as N/A, similar to the jfr tool and RecordedObject::toString(). 

There may be code that already relies on the current behavior and the min value is used to indicate N/A elsewhere.

**Comment by egahlin** [comment]
> If you are comfortable with the INT_MIN value being used, I agree with your suggestion. In that case, I will only fix the description and withdraw the submitted test in this pull request.
Sounds good.

> Do you know the workflow for changeing the JMC GUI?
There is a wiki page:
https://wiki.openjdk.org/display/jmc/Main
Filing a bug on JMC is probably the first step.

**Comment by tkiriyama** [comment]
Thank you for your advice. I modified the description to match the actual behavior.
After integrated this fix, I will report the issue on JMC.

**Review by egahlin — APPROVED** [review]

**Comment by egahlin** [comment]
You may want to change the name of the bug so it says something about the incorrect description.

**Comment by tkiriyama** [comment]
I see. I fixed the titles of the bug issue and this pull request.

**Pull request closed without merging**
