### PR TITLE
8303409: Add Windows AArch64 ABI support to the Foreign Function & Memory API

### PR DESCRIPTION
**Pull request by swesonga**
There are 2 primary differences between the Windows ARM64 ABI and the macOS/Linux ARM64 ABI: variadic floating point arguments are passed in general purpose registers on Windows (instead of the vector registers). In addition to this, up to 64 bytes of a struct being passed to a variadic function can be placed in general purpose registers. This happens regardless of the type of struct (HFA or other generic struct). This means that a struct can be split across registers and the stack when invoking a variadic function. The Windows ARM64 ABI conventions are documented at https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions

For details about the Foreign Function & Memory API, see JEP 434 at https://openjdk.org/jeps/434

This change is a cherry pick of https://github.com/openjdk/panama-foreign/commit/d379ca1c and https://github.com/openjdk/panama-foreign/commit/08225e4f from https://github.com/openjdk/panama-foreign/pull/754 and includes an additional commit that introduces a VaList implementation for Windows on AArch64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303409](https://bugs.openjdk.org/browse/JDK-8303409): Add Windows AArch64 ABI support to the Foreign Function &amp; Memory API

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12773/head:pull/12773` \
`$ git checkout pull/12773`

Update a local copy of the PR: \
`$ git checkout pull/12773` \
`$ git pull https://git.openjdk.org/jdk pull/12773/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12773`

View PR using the GUI difftool: \
`$ git pr show -t 12773`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12773.diff">https://git.openjdk.org/jdk/pull/12773.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
@swesonga I've filed a new issue here: https://bugs.openjdk.org/browse/JDK-8303409

Please use that issue number in the PR title.

**Review by JornVernee — COMMENTED** [review]
All still looks good (including the VaList impl, though that is less important now since we plan to remove VaList in 21)

I'm running tier 1-4 before giving a checkmark.

**Review by JornVernee — APPROVED** [review]
Tests came back green

**Comment by mcimadamore** [comment]
Many thanks for looking into this port!

**Pull request closed without merging**
