### PR TITLE
8287186: JDK modules participating in preview

### PR DESCRIPTION
**Pull request by PaulSandoz**
Allow JDK modules that use preview features (preview language features or preview API features from dependent modules) to participate without the need to compile with `--enable-preview`.

It's difficult to enable participation using an annotation due to the nature in which symbols are encountered when processing source as there is no guaranteed order to the processing of certain symbols.

Instead a JDK module participates if the `java.base` package `jdk.internal.javac` is exported to that module (@lahodaj clever idea!). An internal annotation `jdk.internal.javac.ParticipatesInPreview` can be declared on the module. Such a declaration cannot be enforced but does by its use require the `jdk.internal.javac`'s export list to be updated.

The modules `jdk.incubator.vector` and `jdk.incubator.concurrent` have been updated accordingly, both of which participate in preview APIs (APIs in `java.lang.foreign` and `Thread.ofVirtual`, respectively).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287186](https://bugs.openjdk.org/browse/JDK-8287186): JDK modules participating in preview

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [9defdf23](https://git.openjdk.org/jdk/pull/9087/files/9defdf23ee120f4a305275195c7b97617e1156ce)
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**) ⚠️ Review applies to [9defdf23](https://git.openjdk.org/jdk/pull/9087/files/9defdf23ee120f4a305275195c7b97617e1156ce)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9087/head:pull/9087` \
`$ git checkout pull/9087`

Update a local copy of the PR: \
`$ git checkout pull/9087` \
`$ git pull https://git.openjdk.org/jdk pull/9087/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9087`

View PR using the GUI difftool: \
`$ git pr show -t 9087`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9087.diff">https://git.openjdk.org/jdk/pull/9087.diff</a>

</details>

### CODE REVIEW

**Comment by PaulSandoz** [comment]
> Can java.management participate too? It would allow sun.management.Util.isVirtual(Thread) to go away (lots of methods in sun.management.ThreadImpl need to test if a thread is virtual).

Pushed update.

**Review by lahodaj — APPROVED** [review]
javac + `jdk.internal.javac` changes look good to me.

**Comment by PaulSandoz** [comment]
@liach it depends on the API and its scope. A constructor of `StructuredTaskScope` specifies that it implicitly uses a virtual thread factory, so it performs a preview runtime check. 

The same check is also performed by `Thread.ofVirtual`, ensuring developers cannot reflectively work around 
`--enable-preview` when creating virtual threads. This approach is feasible since the API surface is so small.

**Pull request closed without merging**
