### PR TITLE
8344310: Remove Security Manager dependencies from javax.crypto and com.sun.crypto packages

### PR DESCRIPTION
**Pull request by seanjmullan**
Now that JEP 486 is integrated, javax.crypto and com.sun.crypto implementation dependencies on System.getSecurityManager and AccessController.doPrivileged can be removed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344310](https://bugs.openjdk.org/browse/JDK-8344310): Remove Security Manager dependencies from javax.crypto and com.sun.crypto packages (**Enhancement** - P3)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Anthony Scarpino](https://openjdk.org/census#ascarpino) (@ascarpino - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22164/head:pull/22164` \
`$ git checkout pull/22164`

Update a local copy of the PR: \
`$ git checkout pull/22164` \
`$ git pull https://git.openjdk.org/jdk.git pull/22164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22164`

View PR using the GUI difftool: \
`$ git pr show -t 22164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22164.diff">https://git.openjdk.org/jdk/pull/22164.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22164#issuecomment-2479908280)
</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Sean, at the class declaration of `JceSecurity` in the `src/java.base/share/classes/javax/crypto/JceSecurity.java.template` file, there's a `@SuppressWarnings("removal")`. It looks like it can be removed.

Other than that the rest of these changes look reasonable to me.

**Comment by seanjmullan** [comment]
> Hello Sean, at the class declaration of `JceSecurity` in the `src/java.base/share/classes/javax/crypto/JceSecurity.java.template` file, there's a `@SuppressWarnings("removal")`. It looks like it can be removed.

Good catch. Fixed.

**Review by jaikiran — APPROVED** [review]
Thank you Sean. These changes look reasonable to me.

**Review by ascarpino — APPROVED** [review]
looks good

**Pull request closed without merging**
