### PR TITLE
8304016: Add BitMap find_last suite of functions

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that adds functions to BitMap for finding the last
set/clear bit in a range.

Testing:
mach5 tier1, including new gtesting for the new functions.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304016](https://bugs.openjdk.org/browse/JDK-8304016): Add BitMap find_last suite of functions

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [b3d2aed1](https://git.openjdk.org/jdk/pull/12988/files/b3d2aed13eb8938d407ee2efd4cad8d47cf3c762)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer) ⚠️ Review applies to [b3d2aed1](https://git.openjdk.org/jdk/pull/12988/files/b3d2aed13eb8938d407ee2efd4cad8d47cf3c762)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12988/head:pull/12988` \
`$ git checkout pull/12988`

Update a local copy of the PR: \
`$ git checkout pull/12988` \
`$ git pull https://git.openjdk.org/jdk.git pull/12988/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12988`

View PR using the GUI difftool: \
`$ git pr show -t 12988`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12988.diff">https://git.openjdk.org/jdk/pull/12988.diff</a>

</details>

### CODE REVIEW

**Comment by kimbarrett** [comment]
I've improved find_first/last_bit_impl since the original PR commit.

(1) In find_last_bit_impl, testing the last bit and the last word has been
improved, shaving off an instruction or two (depending on platform). The
previous version incorrectly expected shifts to set condition codes.

(2) The previous version of find_last_bit_impl expected the compiler to CSE
merge the nearly (and now actually, because of the change above) identical
code for handling found bits in cword. But gcc (at least) doen't seem to do
that, so we do it manually. This doesn't have any performance cost, just saves
20-30% of the (inline) code size.

(3) Applied to find_first_bit_impl a similar technique to (2).

The manual tail merging is a little bit indirect.  It might be that it would
be easier to understand by being more explicit and using a goto.

**Review by xmas92 — APPROVED** [review]
The rewrite made the algorithm more readable, imo.

At some point I would like to type up the `beg` and `end` so it is clear that it is a range with `[beg, end)`

**Comment by kimbarrett** [comment]
Thanks for reviews @stefank and @xmas92

**Pull request closed without merging**
