### PR TITLE
8299580: RISC-V: fail to build with GCC 12 due to stringop-overflow warning

### PR DESCRIPTION
**Pull request by RealFYang**
Release fail to build with GCC-12 due to warnings been treated as errors. But the mentioned HotSpot code looks fine, so this looks to me like a GCC-12 suprious warning. This issue does not menifest on other platforms because they are using inline assembly code instead of calling GCC builtins like __atomic_add_fetch to implement class atomic.

Currently, class atomic is only partially implemented with inline assembly code on RISC-V. Instead of disabling the stringop-overflow warning when building HotSpot, I would prefer reimplementing other functions of class atomic using inline assembly code. That way has the extra benefit of providing us fine-grained control on code generation for these atomics. This is the first version which maps to the original implementation with GCC builtins. I will further improve this part distinguishing different memory ordering requirements.

Testing:
- [x] release and fastdebug build fine with both GCC-11 and GCC-12.
- [x] run tier1-3 tests on HiFive Unmatched.
- [x] run non-trivial benchmark workloads like: renaissance, specjvm2008, specjbb2015, etc.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blockers
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with the updated jcheck configuration)
&nbsp;⚠️ Whitespace errors (failed with the updated jcheck configuration)

### Issue
 * [JDK-8299580](https://bugs.openjdk.org/browse/JDK-8299580): RISC-V: fail to build with GCC 12 due to stringop-overflow warning (**Bug** - P4)

### Reviewers
 * [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - Author)
 * [Yadong Wang](https://openjdk.org/census#yadongwang) (@yadongw - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/11858/head:pull/11858` \
`$ git checkout pull/11858`

Update a local copy of the PR: \
`$ git checkout pull/11858` \
`$ git pull https://git.openjdk.org/jdk.git pull/11858/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11858`

View PR using the GUI difftool: \
`$ git pr show -t 11858`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11858.diff">https://git.openjdk.org/jdk/pull/11858.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/11858#issuecomment-1373088775)

### CODE REVIEW

**Review by feilongjiang — APPROVED** [review]
Looks good.

**Comment by kimbarrett** [comment]
A similar problem has shown up on linux-aarch64 - https://bugs.openjdk.org/browse/JDK-8294031.  I've linked
the two bugs.

It's very interesting that something like this is appearing on multiple platforms.  I've been looking at JDK-8294031
on the assumption that it was aarch64-specific.  And it sure does look like a gcc bug.

**Comment by RealFYang** [comment]
> A similar problem has shown up on linux-aarch64 - https://bugs.openjdk.org/browse/JDK-8294031. I've linked the two bugs.
> 
> It's very interesting that something like this is appearing on multiple platforms. I've been looking at JDK-8294031 on the assumption that it was aarch64-specific. And it sure does look like a gcc bug.

Note that there might be some subtle difference here. I see this issue only triggers when we implement PlatformAdd with GCC builtin __atomic_add_fetch on RISC-V. It does not trigger when we use __atomic_load for PlatformOrderedLoad. So I am not touching PlatformOrderedLoad in this PR.

**Review by yadongw — APPROVED** [review]
lgtm

**Comment by kimbarrett** [comment]
> > A similar problem has shown up on linux-aarch64 - https://bugs.openjdk.org/browse/JDK-8294031. I've linked the two bugs.
> > It's very interesting that something like this is appearing on multiple platforms. I've been looking at JDK-8294031 on the assumption that it was aarch64-specific. And it sure does look like a gcc bug.
> 
> Note that there might be some subtle difference here. I see this issue only triggers when we implement PlatformAdd with builtin __atomic_add_fetch on RISC-V with GCC-12. It does not trigger when we use __atomic_load for PlatformOrderedLoad. So I am not touching PlatformOrderedLoad in this PR.

I think it's the same problem, but perhaps with some platform-specific bits.  This is being discussed internally to
Oracle right now.  I suggest not making this change just yet.  It's unclear that such workarounds will really address
the fundamental problem; they _might_ provide a stop gap for a given version of gcc.

**Comment by RealFYang** [comment]
> > > A similar problem has shown up on linux-aarch64 - https://bugs.openjdk.org/browse/JDK-8294031. I've linked the two bugs.
> > > It's very interesting that something like this is appearing on multiple platforms. I've been looking at JDK-8294031 on the assumption that it was aarch64-specific. And it sure does look like a gcc bug.
> > 
> > 
> > Note that there might be some subtle difference here. I see this issue only triggers when we implement PlatformAdd with builtin __atomic_add_fetch on RISC-V with GCC-12. It does not trigger when we use __atomic_load for PlatformOrderedLoad. So I am not touching PlatformOrderedLoad in this PR.
> 
> I think it's the same problem, but perhaps with some platform-specific bits. This is being discussed internally to Oracle right now. I suggest not making this change just yet. It's unclear that such workarounds will really address the fundamental problem; they _might_ provide a stop gap for a given version of gcc.

Hi, I am happy to know that this issue is under discussion somewhere for a better solution. Since this only triggers for latest GCC-12 and is not a blocking us for now, I can hold on for a while.

**Pull request closed without merging**
