### PR TITLE
8334600: TEST java/net/MulticastSocket/IPMulticastIF.java fails on linux-aarch64

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [f23295ec](https://github.com/openjdk/jdk/commit/f23295ec1dde58d239a2625c9b1645534a2bb625) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Daniel Fuchs on 26 Jun 2024 and was reviewed by Alan Bateman.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334600](https://bugs.openjdk.org/browse/JDK-8334600): TEST java/net/MulticastSocket/IPMulticastIF.java fails on linux-aarch64 (**Bug** - P4)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19945/head:pull/19945` \
`$ git checkout pull/19945`

Update a local copy of the PR: \
`$ git checkout pull/19945` \
`$ git pull https://git.openjdk.org/jdk.git pull/19945/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19945`

View PR using the GUI difftool: \
`$ git pr show -t 19945`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19945.diff">https://git.openjdk.org/jdk/pull/19945.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19945#issuecomment-2197202448)

### CODE REVIEW

**Comment by AlanBateman** [comment]
@dfuch Has you planned to backport this to jdk23?

**Comment by sendaoYan** [comment]
> @dfuch Has you planned to backport this to jdk23?

Before backport to jdk17u-dev and jdk21u-dev, should we backport to jdk23 first.

**Comment by RealCLanger** [comment]
It's a test fix, so I guess it should be fine to bring to jdk23. If not, we shall do it at least in jdk23u.

**Review by RealCLanger — APPROVED** [review]

**Comment by sendaoYan** [comment]
Thanks for the review.
/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
