### PR TITLE
8241354: ZGC still crashes in containers with NUMA due to get_mempolicy is disabled by default

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

ZGC still crashes in containers hosting on NUMA machines due to an fatal error [1], which really limits the usage of zgc.

The reason is that get_mempolicy is blocked by default in dockers [2].
With the default docker configuration, ZGC will always crash with NUMA.

Other collectors are also somehow affected by this restriction.
But unlike zgc, they won't crash and can still work in dockers.
So we'd better fix this bug as soon as possible since more and more people would like to use zgc.

The patch was prepared under the guidance of StefanK [3] and many thanks to him.
And we'd like to provide a user friendly -Xlog:gc+init log in a separate RFE after this issue.

Testing:
  - tier1 ~ tier3 on Linux/x64

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/gc/z/zNUMA_linux.cpp#L64
[2] https://docs.docker.com/engine/security/seccomp/
[3] https://mail.openjdk.java.net/pipermail/hotspot-gc-dev/2020-March/028927.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8241354](https://bugs.openjdk.java.net/browse/JDK-8241354): ZGC still crashes in containers with NUMA due to get_mempolicy is disabled by default

### Reviewers
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)

### Contributors
 * Per Liden `<pliden@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3704/head:pull/3704` \
`$ git checkout pull/3704`

Update a local copy of the PR: \
`$ git checkout pull/3704` \
`$ git pull https://git.openjdk.java.net/jdk pull/3704/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3704`

View PR using the GUI difftool: \
`$ git pr show -t 3704`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3704.diff">https://git.openjdk.java.net/jdk/pull/3704.diff</a>

</details>

### CODE REVIEW

**Review by pliden — CHANGES_REQUESTED** [review]
The approach looks good. However, I'd like to suggest the following adjustments https://github.com/pliden/jdk/commit/9cff734de0f03b4990cab55c7052e3e7f3b6a8f1 on top of this PR, which breaks out the syscall into a separate function and renames a few things.

**Comment by DamonFool** [comment]
> The approach looks good. However, I'd like to suggest the following adjustments [pliden@9cff734](https://github.com/pliden/jdk/commit/9cff734de0f03b4990cab55c7052e3e7f3b6a8f1) on top of this PR, which breaks out the syscall into a separate function and renames a few things.

Thanks @pliden for your review and help.
Updated.

/contributor add @pliden

**Review by pliden — APPROVED** [review]
Thanks for updating. Looks good.

**Comment by DamonFool** [comment]
> Thanks for updating. Looks good.

Thanks @pliden .
Will push it tomorrow if there is no objection.

**Pull request closed without merging**
