### PR TITLE
8311122: Fix typos in java.base

### PR DESCRIPTION
**Pull request by pavelrappo**
Please review this IDE-assisted typo hunt, which I plan to backport to jdk21.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311122](https://bugs.openjdk.org/browse/JDK-8311122): Fix typos in java.base (**Bug** - P4)

### Reviewers
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14718/head:pull/14718` \
`$ git checkout pull/14718`

Update a local copy of the PR: \
`$ git checkout pull/14718` \
`$ git pull https://git.openjdk.org/jdk.git pull/14718/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14718`

View PR using the GUI difftool: \
`$ git pr show -t 14718`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14718.diff">https://git.openjdk.org/jdk/pull/14718.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14718#issuecomment-1613828624)

### CODE REVIEW

**Review by jddarcy — APPROVED** [review]
Looks fine, but please give some time for others reviewers before pushing.

**Comment by pavelrappo** [comment]
> Looks fine, but please give some time for others reviewers before pushing.

Absolutely!

Also, this PR contains a code change (a typo in an error message), which, technically speaking, disqualifies the bug from being "noreg-doc" and requires an appropriate test run. I'll let the PR sit for at least a couple of days.

**Review by naotoj — APPROVED** [review]
LGTM

**Review by mlchung — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by pavelrappo** [comment]
Our CI tests are fine with this change. That said, I'll wait for security-dev to complete the review, and then wait for a few more days so that others could also inspect the change.

**Review by Hamlin-Li — APPROVED** [review]

**Review by seanjmullan — APPROVED** [review]
The changes in the security classes look fine to me.

**Comment by pavelrappo** [comment]
Alright, I think all the areas that this PR touches have been reviewed by area experts.

/integrate

**Pull request closed without merging**
