### PR TITLE
8300247: Harden C1 xchg on AArch64 and PPC

### PR DESCRIPTION
**Pull request by fisk**
In the C1 xchg operation, AArch64 and PPC don't deal well with the input register and output register being the same. In some new code, that can happen. This change aims at solving that issue.

As for AArch64, the xchg implementation in the macro assembler already deals well with the input and output register being the same. So we just need to remove an assert. As for the PPC implementation, @TheRealMDoerr has written a variation that uses a temp operand ensuring that they are not the same register.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300247](https://bugs.openjdk.org/browse/JDK-8300247): Harden C1 xchg on AArch64 and PPC

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to [b361fe26](https://git.openjdk.org/jdk/pull/12065/files/b361fe26fd79a4437a9302537f5271ca034e2f1a)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Contributors
 * Martin Doerr `<mdoerr@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12065/head:pull/12065` \
`$ git checkout pull/12065`

Update a local copy of the PR: \
`$ git checkout pull/12065` \
`$ git pull https://git.openjdk.org/jdk pull/12065/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12065`

View PR using the GUI difftool: \
`$ git pr show -t 12065`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12065.diff">https://git.openjdk.org/jdk/pull/12065.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for including my PPC64 code!

**Comment by fisk** [comment]
Thanks for the review, @theRealAph!

**Comment by RealFYang** [comment]
Hi, I think we could also relex the same assertion for riscv too.
The bottom 'amoswap' instruction used for this case does require that 'dst' and 'obj' in different registers.
Could you please add this extra small change while are you at it? Thanks.

```
diff --git a/src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp b/src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
index aec62aba489..d960d64522c 100644
--- a/src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
+++ b/src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
@@ -1967,7 +1967,8 @@ void LIR_Assembler::atomic_op(LIR_Code code, LIR_Opr src, LIR_Opr data, LIR_Opr
           __ encode_heap_oop(t0, obj);
           obj = t0;
         }
-        assert_different_registers(obj, addr.base(), tmp, dst);
+        assert_different_registers(obj, addr.base(), tmp);
+        assert_different_registers(dst, addr.base(), tmp);
         __ la(tmp, addr);
         (_masm->*xchg)(dst, obj, tmp);
         if (is_oop && UseCompressedOops) {
```

**Comment by fisk** [comment]
@RealFYang Sure - fixed!

**Review by robcasloz — APPROVED** [review]
Looks good.

**Comment by fisk** [comment]
> Looks good.

Thanks for the review!

**Pull request closed without merging**
