### PR TITLE
8282085: The REGISTER_DEFINITION macro is useless after JDK-8269122

### PR DESCRIPTION
**Pull request by TobiHartmann**
After [JDK-8269122](https://bugs.openjdk.java.net/browse/JDK-8269122) (https://github.com/openjdk/jdk/commit/4d2412ef3e1068063acc954a00b4db0fa4b5affb), `REGISTER_DEFINITION` is empty and should be removed together with the files using it.

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282085](https://bugs.openjdk.java.net/browse/JDK-8282085): The REGISTER_DEFINITION macro is useless after JDK-8269122

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7528/head:pull/7528` \
`$ git checkout pull/7528`

Update a local copy of the PR: \
`$ git checkout pull/7528` \
`$ git pull https://git.openjdk.java.net/jdk pull/7528/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7528`

View PR using the GUI difftool: \
`$ git pr show -t 7528`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7528.diff">https://git.openjdk.java.net/jdk/pull/7528.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
Looks good to me.

**Comment by TobiHartmann** [comment]
Thanks for the review!

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks Christian and Vladimir.

**Pull request closed without merging**
