### PR TITLE
8291798: VMRegImpl::print_on is broken after JDK-8289060

### PR DESCRIPTION
**Pull request by TobiHartmann**
The fix for [JDK-8289060](https://bugs.openjdk.org/browse/JDK-8289060) broke printing of  the stack offset because `VMRegImpl::print_on` was not adjusted accordingly:
```
0x00007fa97503a12f: callq 0x00007fa97c6615a0 ; ImmutableOopMap {[825414996]=Oop }
```

The fix is to simply use the `reg2stack` method.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291798](https://bugs.openjdk.org/browse/JDK-8291798): VMRegImpl::print_on is broken after JDK-8289060

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Jie Fu](https://openjdk.org/census#jiefu) (@DamonFool - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9723/head:pull/9723` \
`$ git checkout pull/9723`

Update a local copy of the PR: \
`$ git checkout pull/9723` \
`$ git pull https://git.openjdk.org/jdk pull/9723/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9723`

View PR using the GUI difftool: \
`$ git pr show -t 9723`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9723.diff">https://git.openjdk.org/jdk/pull/9723.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Ah, yes. Looks good.

**Review by DamonFool — APPROVED** [review]

**Comment by TobiHartmann** [comment]
Aleksey, Jie, thanks for the reviews!

**Review by vnkozlov — APPROVED** [review]

**Review by dean-long — APPROVED** [review]

**Comment by TobiHartmann** [comment]
Vladimir, Dean, thanks for the reviews!

**Pull request closed without merging**
