### PR TITLE
8204686: Dynamic parallel reference processing support for Parallel GC

### PR DESCRIPTION
**Pull request by lkorinth**
The first part:
1) sets `ParallelRefProcEnabled` to true if we have multiple threads (in Parallel)
2) removes the field `_adjust_no_of_processing_threads` so that Parallel and G1 handles dynamic resizing the same
3) removes an early return --- `ergo_proc_thread_count()` already adjusts for `ReferencesPerThread == 0`

The second part tries something else. It makes `ParallelRefProcEnabled` default to true for all GCs and does not take into consideration the amount of gc threads. I have talked to Thomas Schatzl  before posting this and we will probably *not* use part two. Reasons include that we can then no longer read the flag ParallelRefProcEnabled to see if we are going to do parallel ref processing as it will be true even if we only have one thread (or are running Serial GC). I still want to show the possibility.

Part three shows the impact on test cases when part two is applied. I will need to adjust part three if we remove Part 2.

Please take an extra look at the removal of the early return, it looks valid to me and `hotspot_gc` passes.

I will try to get this into 17, but if review and CSR takes time I will postpone it to 18. I suggest dropping part 2 and will do so if no one objects.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8204686](https://bugs.openjdk.java.net/browse/JDK-8204686): Dynamic parallel reference processing support for Parallel GC

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Committer) ⚠️ Review applies to 3ef7e2879641bdc4928d3d907a0621a19e0470aa
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 3ef7e2879641bdc4928d3d907a0621a19e0470aa
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 3ef7e2879641bdc4928d3d907a0621a19e0470aa

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4253/head:pull/4253` \
`$ git checkout pull/4253`

Update a local copy of the PR: \
`$ git checkout pull/4253` \
`$ git pull https://git.openjdk.java.net/jdk pull/4253/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4253`

View PR using the GUI difftool: \
`$ git pr show -t 4253`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4253.diff">https://git.openjdk.java.net/jdk/pull/4253.diff</a>

</details>

### CODE REVIEW

**Comment by albertnetymk** [comment]
> we can then no longer read the flag ParallelRefProcEnabled to see if we are going to do parallel ref processing

Given the semantics of `ParallelRefProcEnabled` is "Enable parallel reference processing whenever possible", I think it's fine to forgo that guarantee, `ParallelRefProcEnabled == true` *iff* parallel ref processing.

That being said, I think a possibly better direction is to remove the ambiguity in the semantics, "Perform parallel reference processing", and keep the check for `ParallelGCThreads > 1` before setting `ParallelRefProcEnabled` to `true`.

PS: the current patch looks fine to me as well.

**Comment by tschatzl** [comment]
I think part 2 should be dropped: it is always a help for debugging performance issues to see what `ParallelRefProcEnabled` is (with `-XX:+PrintFlagsFinal`) if it can be determined at startup whether parallel reference processing is (not) active.

I.e. whether there is absolutely no chance that the VM will use parallel gc threads for reference processing is already useful information. Particularly for serial gc it might mislead people if `ParallelRefProcEnabled` were `true` for it. Not sure if changing the description of the flag is necessary, but I see that there might be some ambiguity.

This is not a hard no for keeping part2, but unless there are good reasons to keep it I would suggest dropping this change.

**Comment by lkorinth** [comment]
Hi, and sorry for showing the alternative with the global default set to true. In the CSR I have said I want to go for the option of setting only the Parallel case to true (and only if more than one thread). I will update the code to reflect this as I think it is less of a change.

**Review by albertnetymk — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
Lgtm. Thanks!

**Review by kimbarrett — APPROVED** [review]

**Pull request closed without merging**
