### PR TITLE
8282360: Merge POSIX implementations of ThreadCritical

### PR DESCRIPTION
**Pull request by hseigel**
Please review this small change to merge the Posix (aix, bsd, linux) implementations of ThreadCritical into a single file named src/hotspot/os/posix/threadCritical_posix.cpp.  The change was tested by running Mach5 tiers 1-2 on Linux, Mac OS, and Windows, and Mach5 tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282360](https://bugs.openjdk.java.net/browse/JDK-8282360): Merge POSIX implementations of ThreadCritical

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7622/head:pull/7622` \
`$ git checkout pull/7622`

Update a local copy of the PR: \
`$ git checkout pull/7622` \
`$ git pull https://git.openjdk.java.net/jdk pull/7622/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7622`

View PR using the GUI difftool: \
`$ git pr show -t 7622`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7622.diff">https://git.openjdk.java.net/jdk/pull/7622.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Looks good.

**Review by coleenp — APPROVED** [review]
Nice!

**Review by dholmes-ora — APPROVED** [review]
Hi Harold,

The merge looks good.

The pre-existing use of PTHREAD_MUTEX_INITIALIZER is potentially problematic on FreeBSD - see comments in os_posix.cpp for mutexAttr. But that is a separate problem.

Thanks,
David

**Comment by hseigel** [comment]
Thanks Thomas, Coleen, and David for the reviews.

/integrate

**Pull request closed without merging**
