### PR TITLE
8263989: Cleanup in EA

### PR DESCRIPTION
**Pull request by vnkozlov**
Cleanup/refactoring changes suggested by @iwanowww in Escape Analysis code and few more.

 - fix typos
 - fix code style
 - few renaming
 - small refactoring

Tested tier1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263989](https://bugs.openjdk.java.net/browse/JDK-8263989): Cleanup in EA

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3156/head:pull/3156`
`$ git checkout pull/3156`

To update a local copy of the PR:
`$ git checkout pull/3156`
`$ git pull https://git.openjdk.java.net/jdk pull/3156/head`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
> Looks good.

Thank you Vladimir

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by vnkozlov** [comment]
> Looks good!

Thank you, Nils

**Pull request closed without merging**
