### PR TITLE
8230382: Clean up ConvI2L, CastII and CastLL::Ideal methods

### PR DESCRIPTION
**Pull request by eme64**
This is a cleanup job: move code from `::Ideal` methods that only change types to `::Value` where the code belongs.

`CastLLNode::Ideal` was introduced in [JDK-8229496](https://bugs.openjdk.java.net/browse/JDK-8229496) and reverted (deleted) in [JDK-8242108](https://bugs.openjdk.java.net/browse/JDK-8242108).
Currently, `CastLLNode` does not have its own `::Ideal` method. Hence, I changed nothing for it.

For `ConvI2LNode` and `CastIINode`, I went through a process of first copying the relevant code to `::Value`, calling it from `::Ideal` and asserting that they deliver equivalent results.
These intermediate code results can be found in the comments of [JDK-8230382](https://bugs.openjdk.java.net/browse/JDK-8230382).
I also tried to make the two code versions more similar, where they were unnecessarily different (used `can_reshape` instead of `igvn != NULL`, and removed the dead Overflow/wraparound case which can never happen).
I ran tests: final code and intermediate code versions. Ensures code behaves equivalent and nothing broke.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8230382](https://bugs.openjdk.java.net/browse/JDK-8230382): Clean up ConvI2L, CastII and CastLL::Ideal methods

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7609/head:pull/7609` \
`$ git checkout pull/7609`

Update a local copy of the PR: \
`$ git checkout pull/7609` \
`$ git pull https://git.openjdk.java.net/jdk pull/7609/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7609`

View PR using the GUI difftool: \
`$ git pr show -t 7609`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7609.diff">https://git.openjdk.java.net/jdk/pull/7609.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by eme64** [comment]
Thanks @rwestrel for the review! Thanks @TobiHartmann for the help, corrections and review!
/integrate

**Pull request closed without merging**
