### PR TITLE
8345343: Hide java.lang.classfile.components package to implementation

### PR DESCRIPTION
**Pull request by liach**
The java.lang.classfile.components package was underused and had almost no usage feedback; as a result, it did not caught attention during the preview process of the Class-File API, until the late adoption when Class-File API is sure to become finalized. In the previous rounds of reviews by other engineers, most of the review efforts were devoted to other core modeling and API classes, and components was largely omitted; a few questions were asked, but no solution were proposed and the questions were forgotten.

To compensate in such a short time to the stabilization of JDK 24, we propose to temporarily move this package to jdk.internal instead. This allows us to better consider the role of this package and its members. We considered to continue previewing this package or making it an incubator module, but this is currently not possible as JEP 484 does not provide for any preview API or incubator module - to add such provisions, the JEP must be re-drafted and go through the draft to target process, and now is too late for that.

See https://mail.openjdk.org/pipermail/classfile-api-dev/2024-November/000611.html for initial problem discovery and https://mail.openjdk.org/pipermail/classfile-api-dev/2024-December/000613.html for revision proposal.

Testing: tier 1-3.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires CSR request [JDK-8345344](https://bugs.openjdk.org/browse/JDK-8345344) to be approved

### Issues
 * [JDK-8345343](https://bugs.openjdk.org/browse/JDK-8345343): Hide java.lang.classfile.components package to implementation (**Bug** - P3) ⚠️ Issue is not open.
 * [JDK-8345344](https://bugs.openjdk.org/browse/JDK-8345344): Hide java.lang.classfile.components package to implementation (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22503/head:pull/22503` \
`$ git checkout pull/22503`

Update a local copy of the PR: \
`$ git checkout pull/22503` \
`$ git pull https://git.openjdk.org/jdk.git pull/22503/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22503`

View PR using the GUI difftool: \
`$ git pr show -t 22503`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22503.diff">https://git.openjdk.org/jdk/pull/22503.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22503#issuecomment-2513384307)
</details>

### CODE REVIEW

**Review by asotona — CHANGES_REQUESTED** [review]
I don't see a clear reason for this drastic last-minute change.

**Comment by asotona** [comment]
`java.lang.classfile.components.ClassPrinter` received significant positive feedback in the recent years, it became an essential debugging and logging tool.
`java.lang.classfile.components.ClassRemapper` has been designed based on user requests, it received positive feedback in the recent years and it is an essential component for class instrumentation.
`java.lang.classfile.components.CodeLocalsShifter` and `java.lang.classfile.components.CodeRelabeler` are essential components for class instrumentation and other advanced transformations, they have been designed based on the feedback from JFR class instrumentation conversion from ASM to Class-File API.
`java.lang.classfile.components.CodeStackTracker` has been designed as standalone component (out of the core Class-File API) for performance reasons. It has been strongly requested by users and it has been applied in a prototype of javac using Class-File API to generate classes.

There is no real justification for this change and I suggest to close it.

**Comment by liach** [comment]
After offline discussion, we decide to stick to continued preview status to facilitate adoption. #22501

**Comment by liach** [comment]
After further studies, due to JEP process restrictions, hiding is the only choice at this point. Reopening.

**Pull request closed without merging**
