### PR TITLE
8276678: Malformed Javadoc inline tags in JDK source in com/sun/beans/decoder/DocumentHandler.java

### PR DESCRIPTION
**Pull request by alisenchung**
fixed malformed inline tags

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276678](https://bugs.openjdk.java.net/browse/JDK-8276678): Malformed Javadoc inline tags in JDK source in com/sun/beans/decoder/DocumentHandler.java

### Reviewers
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6298/head:pull/6298` \
`$ git checkout pull/6298`

Update a local copy of the PR: \
`$ git checkout pull/6298` \
`$ git pull https://git.openjdk.java.net/jdk pull/6298/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6298`

View PR using the GUI difftool: \
`$ git pr show -t 6298`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6298.diff">https://git.openjdk.java.net/jdk/pull/6298.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Please check other classes in the jdk desktop module as well. There are 7 such issues.

**Comment by aivanov-jdk** [comment]
> Please check other classes in the jdk desktop module as well. There are 7 such issues.

A similar issue is being reviewed as #6290, it includes 4 files.
Are these split between JBS subcomponents?

**Comment by alisenchung** [comment]
> > Please check other classes in the jdk desktop module as well. There are 7 such issues.
> 
> A similar issue is being reviewed as #6290, it includes 4 files. Are these split between JBS subcomponents?

Looks like Prasanta already fixed the other 5 issues

**Review by mrserb — APPROVED** [review]

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
