### PR TITLE
8325932: Replace ATTRIBUTE_NORETURN with direct [[noreturn]]

### PR DESCRIPTION
**Pull request by TheShermanTanker**
With clang 13 being the minimum required JDK\-8325878, the noreturn bug that requires the ATTRIBUTE\_NORETURN workaround now vanishes, and we can use [[noreturn]] directly within HotSpot. We should remove the workaround as soon as possible, given the chance

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325932](https://bugs.openjdk.org/browse/JDK-8325932): Replace ATTRIBUTE_NORETURN with direct [[noreturn]] (**Enhancement** - P4)

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17868/head:pull/17868` \
`$ git checkout pull/17868`

Update a local copy of the PR: \
`$ git checkout pull/17868` \
`$ git pull https://git.openjdk.org/jdk.git pull/17868/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17868`

View PR using the GUI difftool: \
`$ git pr show -t 17868`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17868.diff">https://git.openjdk.org/jdk/pull/17868.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17868#issuecomment-1945665236)

### CODE REVIEW

**Comment by forax** [comment]
I believe "as soon as possible" should be "once JDK-8325878 is resolved" :)

Now, the reason to use [[noreturn]] instead of ATTRIBUTER_NORETURN macro is that IDEs recognize [[noreturn]] when doing static analysis on the code and that ATTRIBUTER_NORETURN was added as a workaround because a bug (crash) in clang < 12.

**Comment by TheShermanTanker** [comment]
> I believe "as soon as possible" should be "once JDK-8325878 is resolved" :)
> 
> Now, the reason to use [[noreturn]] instead of ATTRIBUTER_NORETURN macro is that IDEs recognize [[noreturn]] when doing static analysis on the code and that ATTRIBUTER_NORETURN was added as a workaround because a bug (crash) in clang < 12.

Yes, I forgot to mention that this is only going in once the clang 13 requirement is integrated

**Comment by tstuefe** [comment]
Thank you for the explanations.

**Comment by TheShermanTanker** [comment]
@kimbarrett Is this good to go now that clang's minimum version has been set to 13?

**Comment by kimbarrett** [comment]
This seems to have gotten lost while waiting for JDK-8325878.  Please re-open and update.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by TheShermanTanker** [comment]
Thanks Kim. Anyone else want to be the second reviewer?

**Review by dholmes-ora — APPROVED** [review]
If this now works fine for all compilers that is great!

Thanks

**Comment by TheShermanTanker** [comment]
Thanks David and Kim for the reviews :)

**Pull request closed without merging**
