### PR TITLE
8296292: Document the default behavior of '$' in regular expressions correctly

### PR DESCRIPTION
**Pull request by rgiulietti**
A small spec change to match established behavior.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8296292](https://bugs.openjdk.org/browse/JDK-8296292): Document the default behavior of '$' in regular expressions correctly
 * [JDK-8296529](https://bugs.openjdk.org/browse/JDK-8296529): Document the default behavior of '$' in regular expressions correctly (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11038/head:pull/11038` \
`$ git checkout pull/11038`

Update a local copy of the PR: \
`$ git checkout pull/11038` \
`$ git pull https://git.openjdk.org/jdk pull/11038/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11038`

View PR using the GUI difftool: \
`$ git pr show -t 11038`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11038.diff">https://git.openjdk.org/jdk/pull/11038.diff</a>

</details>

### CODE REVIEW

**Comment by rgiulietti** [comment]
As this is a spec change only, please consider reviewing the CSR as well.

**Comment by rgiulietti** [comment]
This small change is nothing more than the content of the CSR, which has been approved a couple of days ago. No code changes are involved.

A reviewer would only need to crosscheck that the change and the CSR match.

Thanks in advance

**Review by LanceAndersen — APPROVED** [review]

**Pull request closed without merging**
