### PR TITLE
8305668: PPC: Non-Top Interpreted frames should be independent of ABI_ELFv2

### PR DESCRIPTION
**Pull request by reinrich**
This PR makes parent interpreted Java frames independent of `ABI_ELFv2`.
With the changes `test/jdk/jdk/internal/vm/Continuation/BasicExt.java#COMP_ALL` succeeds on PPC64 Big Endian Linux.

Before:

* `parent_ijava_frame_abi` was derived from `abi_minframe` which depends on `ABI_ELFv2`
* jit_abi is independent of `abi_minframe`
* `frame::metadata_words` is wrong for `parent_ijava_frame_abi` if `ABI_ELFv2` is not defined (big endian)

After changes:

* prefixed structs that depend on `ABI_ELFv2` with `native_`
* introduced `java_abi` which is independent of `ABI_ELFv2`
* `frame::metadata_words` is the size in words of `java_abi`

This is still a little imprecise since `top_ijava_frame_abi` is larger than `java_abi` but the top frame is never frozen as it is always `vmIntrinsics::_Continuation_doYield`

Testing:

PPC64le: most JCK and JTREG tiers 1-4, also in Xcomp mode.
PPC64be Linux: hotspot tier1 tests

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305668](https://bugs.openjdk.org/browse/JDK-8305668): PPC: Non-Top Interpreted frames should be independent of ABI_ELFv2

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to [ea9ddcfe](https://git.openjdk.org/jdk/pull/13372/files/ea9ddcfecef36680d2cfb1effb4f39ba731d9349)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13372/head:pull/13372` \
`$ git checkout pull/13372`

Update a local copy of the PR: \
`$ git checkout pull/13372` \
`$ git pull https://git.openjdk.org/jdk.git pull/13372/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13372`

View PR using the GUI difftool: \
`$ git pr show -t 13372`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13372.diff">https://git.openjdk.org/jdk/pull/13372.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13372#issuecomment-1499083801)

### CODE REVIEW

**Comment by reinrich** [comment]
Hi Tyler, @backwaterred, hope this will help with continuations on AIX... :)

**Comment by reinrich** [comment]
Going back to draft because the following fails with this pr:

```
time make test TEST=test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03
```

**Comment by backwaterred** [comment]
> Going back to draft because the following fails with this pr:
> 
> ```
> time make test TEST=test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03
> ```

Out of curiosity, what is the problem with the above command? It seems to work as expected for me.

```
Building target 'test' in configuration 'aix-ppc64-server-fastdebug'
Test selection 'test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03', will run:
* jtreg:test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03

Running test 'jtreg:test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03'
Passed: serviceability/jvmti/thread/GetThreadState/thrstat03/thrstat03.java
Test results: passed: 1
Report written to /home/hotspot/openjdk/jdk-tyler/build/aix-ppc64-server-fastdebug/test-results/jtreg_test_hotspot_jtreg_serviceability_jvmti_thread_GetThreadState_thrstat03/html/report.html
Results written to /home/hotspot/openjdk/jdk-tyler/build/aix-ppc64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_serviceability_jvmti_thread_GetThreadState_thrstat03
Finished running test 'jtreg:test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03'
Test report is stored in build/aix-ppc64-server-fastdebug/test-results/jtreg_test_hotspot_jtreg_serviceability_jvmti_thread_GetThreadState_thrstat03

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03
                                                         1     1     0     0   
==============================
TEST SUCCESS

Finished building target 'test' in configuration 'aix-ppc64-server-fastdebug'

real    0m41.091s
user    0m42.847s
sys     0m5.076s
```

**Comment by reinrich** [comment]
Thanks for the testing. Are you sure though your build includes the changes of this pr?
There is a problem in exception handling which is related to the changes.

`test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03` crashes in my tests with SIGSEGV:

```
Stack: [0x000004001a0d0000,0x000004001a2d0000],  sp=0x000004001a2cd310,  free space=2036k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xedc318]  frame::interpreter_frame_method() const+0x58  (frame.cpp:398)
V  [libjvm.so+0x11bdd30]  InterpreterRuntime::exception_handler_for_exception(JavaThread*, oopDesc*)+0x120  (interpreterRuntime.cpp:473)
```

Other tests seem to hang.

Also the failures of `test/jdk/jdk/internal/vm/Continuation/BasicExt.java` are related to exception handling.
BTW: does the COMP_ALL variant of BasicExt.java succeed on AIX too with these changes?

**Comment by backwaterred** [comment]
Interesting. I see no such failure on AIX either on my VThread branch, or when checking this PR out directly. I am currently running on Linux/Power to see if I can confirm that I see the failure there.

I don't see any failures in BasicExt.java on my aix/vthread branch with these and other changes (most notably the PollsetPoller implementation).

**Comment by reinrich** [comment]
> Going back to draft because the following fails with this pr:
> 
> ```
> time make test TEST=test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03
> ```

I've overlooked that there's also a [test case with a virtual thread](https://github.com/openjdk/jdk/blob/bc15163386659bfd549576817b4efe7307261ea8/test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState/thrstat03/thrstat03.java#L59).
The test succeeds with `VMContinuations` disabled.

**Comment by reinrich** [comment]
> Interesting. I see no such failure on AIX either on my VThread branch, or when checking this PR out directly. I am currently running on Linux/Power to see if I can confirm that I see the failure there.
> 
> I don't see any failures in BasicExt.java on my aix/vthread branch with these and other changes (most notably the PollsetPoller implementation).

[`VMContinuations` are disabled on AIX](https://github.com/openjdk/jdk/blob/bc15163386659bfd549576817b4efe7307261ea8/src/hotspot/cpu/ppc/globals_ppc.hpp#L59). Have you changed that line?
BasicExt.java is otherwise skipped because [it requires continuations](https://github.com/openjdk/jdk/blob/bc15163386659bfd549576817b4efe7307261ea8/test/jdk/jdk/internal/vm/Continuation/BasicExt.java#L28).
If you run it standalone (w/o jtreg) you should get an `UnsupportedOperationException`

I'm planning to disable `VMContinuations` on PPC big endian platforms for now. This will help testing changes like this pr.

**Comment by backwaterred** [comment]
For reference, I created #13452. It collects some in-progress changes from me, changes from this PR, and some changes from Matthias that enable the Harfbuzz library to build.

> [VMContinuations are disabled on AIX](https://github.com/openjdk/jdk/blob/bc15163386659bfd549576817b4efe7307261ea8/src/hotspot/cpu/ppc/globals_ppc.hpp#L59). Have you changed that line?
BasicExt.java is otherwise skipped because [it requires continuations](https://github.com/openjdk/jdk/blob/bc15163386659bfd549576817b4efe7307261ea8/test/jdk/jdk/internal/vm/Continuation/BasicExt.java#L28).
If you run it standalone (w/o jtreg) you should get an UnsupportedOperationException

With the changes mentioned above, I believe I am running your VThreads implementation on AIX: VMContinuations is indeed set to true, and BasicExt should be running the 'real' vthread impl. The issues I see appear to hang while waiting for my PollsetPoller implementation, so I don't believe anything here is an issue for me.

> I'm planning to disable VMContinuations on PPC big endian platforms for now. This will help testing changes like this pr.

Sounds good. I'll make sure to test my changes on AIX & Linux BE before merging. Thanks again for catching this issue. I was definitely looking in the wrong place for it's cause.

**Comment by reinrich** [comment]
Top of stack when `SharedRuntime::exception_handler_for_return_address` is called. Calling C++ code kills 14 words in the caller. This kills the `method` field of the interpreted frame. On little endian only 12 words are killed which is just enough. At least in this test. If there is no dead space then it can crash too.
```
[0.832s][trace][continuations]  0x00000fffb562da40: 0x00000fffb562db50 #0 method BasicExt$Continuation3Frames.ord103_testMethod_dontinline(JJJLjava/lang/String;)Ljava/lang/String; @ 7
[0.832s][trace][continuations]                                         - 8 locals 9 max stack
[0.832s][trace][continuations]                                         -  codelet: return entry points
[0.832s][trace][continuations]                                         sp for #1
[0.832s][trace][continuations]  0x00000fffb562da38: 0x00000fff9b629690 fresult
[0.832s][trace][continuations]  0x00000fffb562da30: 0x00000000ffb72cd8 lresult
[0.832s][trace][continuations]  0x00000fffb562da28: 0x0000000000000000 oop_tmp
[0.832s][trace][continuations]  0x00000fffb562da20: 0x00000fffb562daa0 sender_sp
[0.832s][trace][continuations]  0x00000fffb562da18: 0x00000fffb562d920 top_frame_sp
[0.832s][trace][continuations]  0x00000fffb562da10: 0x00000fffb562d730 mdx
[0.832s][trace][continuations]  0x00000fffb562da08: 0x00000fffb562d990 esp
[0.832s][trace][continuations]  0x00000fffb562da00: 0x00000fff9b614f87 bcp
[0.832s][trace][continuations]  0x00000fffb562d9f8: 0x00000fff9b612000 cpoolCache
[0.832s][trace][continuations]  0x00000fffb562d9f0: 0x00000fffb562d9d8 monitors
[0.832s][trace][continuations]  0x00000fffb562d9e8: 0x000000000000000b locals
[0.832s][trace][continuations]  0x00000fffb562d9e0: 0x00000000ffcc02b0 mirror
[0.832s][trace][continuations]                                         oop for #0
[0.832s][trace][continuations]  0x00000fffb562d9d8: 0x00000fff9b614fd8 method
[0.832s][trace][continuations]  0x00000fffb562d9d0: 0x00000000ffcc1bf8
[0.832s][trace][continuations]  0x00000fffb562d9c8: 0x0000000000000000
[0.832s][trace][continuations]  0x00000fffb562d9c0: 0x0000000000000001
[0.832s][trace][continuations]  0x00000fffb562d9b8: 0x0000000000000000
[0.832s][trace][continuations]  0x00000fffb562d9b0: 0x0000000000000002
[0.832s][trace][continuations]  0x00000fffb562d9a8: 0x0000000000000000
[0.832s][trace][continuations]  0x00000fffb562d9a0: 0x0000000000000003 DEAD SPACE
[0.832s][trace][continuations]  0x00000fffb562d998: 0x00000000ffb72cd8
[0.832s][trace][continuations]  0x00000fffb562d990: 0x00000fffa9de84dc <- esp
[0.832s][trace][continuations]  0x00000fffb562d988: 0x0000000000000006
[0.832s][trace][continuations]  0x00000fffb562d980: 0x00000fffa9de81a8 return address
[0.832s][trace][continuations]  0x00000fffb562d978: 0x00000000bbaaddf9
[0.832s][trace][continuations]  0x00000fffb562d970: 0x00000fffb562da40 unextended_sp for #0           Range [0x00000fffb562d970, 0x00000fffb562d9d8] has 14 words !!!
```

**Review by TheRealMDoerr — APPROVED** [review]

**Comment by reinrich** [comment]
> This PR LGTM. For the remaining BE issue, shouldn't we push a dummy frame (`push_frame_reg_args(0, R0);`)? Other callers of `SharedRuntime::exception_handler_for_return_address` do that.

Yes, I've done that and it works. I'll come up with a separate PR that will also enable VMContinuations again on PPC64 big endian.

**Comment by reinrich** [comment]
Another round of testing succeeded (tier 1 - 4).
On AIX `serviceability/jvmti/vthread/VThreadNotifyFramePopTest/VThreadNotifyFramePopTest.java` fails because the PollsetPoller is not fully implemented there. @backwaterred is working on it.
Thanks for the reviews. I'm planning to integrate the pr tomorrow.

**Pull request closed without merging**
