### PR TITLE
8270901: Typo PHASE_CPP in CompilerPhaseType

### PR DESCRIPTION
**Pull request by kelthuzadx**
Should be PHASE_CCP instead of PHASE_CPP, it also affects dumped ideal graph XML.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270901](https://bugs.openjdk.java.net/browse/JDK-8270901): Typo PHASE_CPP in CompilerPhaseType

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - **Reviewer**) ⚠️ Review applies to f556d064e0ee8e631f4d7e4e2964805b96150b32

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4917/head:pull/4917` \
`$ git checkout pull/4917`

Update a local copy of the PR: \
`$ git checkout pull/4917` \
`$ git pull https://git.openjdk.java.net/jdk pull/4917/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4917`

View PR using the GUI difftool: \
`$ git pr show -t 4917`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4917.diff">https://git.openjdk.java.net/jdk/pull/4917.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
Looks good to me.

The copyright year should also be updated.
Thanks.

**Comment by kelthuzadx** [comment]
Thank you Jie for review!

**Comment by DamonFool** [comment]
For hotspot changes, it would be better to have a second review & wait for 24 hours before integration. 
Thanks.

**Comment by kelthuzadx** [comment]
> For hotspot changes, it would be better to have a second review & wait for 24 hours before integration.
> Thanks.

Well, it seems a trivial change, maybe one review is okay. For non-trivial changes, we really need more reviews and wait for 24h before merging.

**Comment by dcubed-ojdk** [comment]
@kelthuzadx - HotSpot changes require two reviews and a 24 hour waiting period.
You may propose in your review request that a change is "trivial" and if your
(R)eviewer agrees, then you may integrate with a single (R)eviewer and you don't
have to wait for 24 hours.

**Pull request closed without merging**
