### PR TITLE
8256382: Use try_lock for hs_err EventLog printing

### PR DESCRIPTION
**Pull request by stefank**
The EventLog locks are taken when the hs_err files are generated. Since crashes and asserts can occur when other locks are held, this can cause lock reordering problems if the held locks also are low-rank locks. There's no way to solve this if blocking locks are taken.

I hit this problem when investigating making the GCLogPrecious lock use the lowest lock rank (same as EventLog). See JDK-8254877.

Both GCLogPrecious and EventLog are considered "leaf" locks. No other locks should be taken when those locks are taken. However, if we crash in either of these sub-systems, there will be a lock-reordering error message in the hs_err file, and the rest of the logged info is skipped in the currently logged section.

The proposal is to use try_lock_without_range_check and only log information if the lock could be acquired without blocking. This relies on the new try_lock_without_range_check function from JDK-8255678.

I've tested this by injecting crashes while not holding locks in both GCLogPrecious, while holding locks during EventLog logging, and when not holding the locks, and verified that we get the expected behavior.

Example output while crashing during 'Internal exceptions' logging:
```
Classes redefined (0 events):
No events

Internal exceptions (5 events):
No events printed - crash while holding lock

Events (20 events):
Event: 1,437 loading class java/util/HashMap$KeyIterator
Event: 1,438 loading class java/util/HashMap$KeyIterator done
Event: 1,438 loading class java/lang/module/ModuleDescriptor$Exports
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (8/8 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ❌ (2/9 failed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x86 (hs/tier1 compiler)](https://github.com/stefank/jdk/runs/1458357327)
- [Linux x86 (jdk/tier1 part 3)](https://github.com/stefank/jdk/runs/1458357249)

### Issue
 * [JDK-8256382](https://bugs.openjdk.java.net/browse/JDK-8256382): Use try_lock for hs_err EventLog printing

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1408/head:pull/1408`
`$ git checkout pull/1408`

### CODE REVIEW

**Review by tstuefe — COMMENTED** [review]
Hi Stefan,

can't we just print out unconditionally if VMError::is_error_reported()? Whats the worst that can happen, we crash? Then we would continue with the next reporting step. But we still have a chance to see the event buffer contents even if the event logger itself crashed or asserted.

Side note, some time ago I rewrote the whole event system: https://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2019-March/033150.html to a much simpler implementation and I think that one would also be pretty safe to get printed even if unlocked since it works on a static pre-allocated buffer. But that work somehow got bogged down in review and I never got around to drive it upstream. If there is enough interest I may take up the work again.

**Comment by stefank** [comment]
Hi @tstuefe 

With your proposal, if we have a section that looks like this:
* event log instance 0
* event log instance 1
* event log instance 2
* other type of printing

and we crash at "event log instance 1", then we completely skip printing "event log instance 2" and "other type of printing". My thinking was that that was unfortunate, and I wanted to localize the problem. We often have this problem that one hs_err crash hides important information that was supposed to be written later, because a lot of the code in the hs_err printing isn't hardened and the hs_err sections are on a too high level (IMHO).

With that said, I don't mind skipping the trying to take the lock if we are printing the hs_err file. Do others agree with Thomas?

**Comment by dholmes-ora** [comment]
Don't we have to check not only VMError::is_error_reported, but that it is the current thread that is doing the reporting?

I also think the Thread::current_or_null()==NULL case has to mean we are doing the error reporting very early in VM init - else how can we get in here in a "non attached" thread? Even then I'm not sure that is actually possible either - at what point in VM init have we installed our crash handler?

**Comment by tstuefe** [comment]
> Don't we have to check not only VMError::is_error_reported, but that it is the current thread that is doing the reporting?
> 

You mean my proposal of just not locking altogether?
Its a calculated risk. The chance of someone printing out the even log concurrently to the hs-err reporter doing it is extremely low, and since we have secondary crash reporting the only risk we run is an interrupted error reporting step.

> I also think the Thread::current_or_null()==NULL case has to mean we are doing the error reporting very early in VM init - else how can we get in here in a "non attached" thread?

Thread::current_or_null()==NULL if we crash in a non attached thread or at/before VM init. The former case is typical if the VM is embedded into another launcher and foreign code crashes (not uncommon).

Arguably, in both cases the event log is not very interesting, but I'd still attempt to print it.

> Even then I'm not sure that is actually possible either - at what point in VM init have we installed our crash handler?

**Comment by stefank** [comment]
> Don't we have to check not only VMError::is_error_reported, but that it is the current thread that is doing the reporting?

I found inspiration for this in this piece of code:
```
void ThreadsSMRSupport::print_info_on(outputStream* st) {
  // Only grab the Threads_lock if we don't already own it and if we
  // are not reporting an error.
  // Note: Not grabbing the Threads_lock during error reporting is
  // dangerous because the data structures we want to print can be
  // freed concurrently. However, grabbing the Threads_lock during
  // error reporting can be equally dangerous since this thread might
  // block during error reporting or a nested error could leave the
  // Threads_lock held. The classic no win scenario.
  //
  MutexLocker ml((Threads_lock->owned_by_self() || VMError::is_error_reported()) ? NULL : Threads_lock);
```
Looking at this a bit more I see that the EventLogs typically check this function instead:
```
  // check to see if fatal error reporting is in progress
  static bool fatal_error_in_progress() { return _first_error_tid != -1; }
```
which is used to turn off EventLog logging when we crash. Both these variables are set here:
```
  if (_first_error_tid == -1 &&
      Atomic::cmpxchg(&_first_error_tid, (intptr_t)-1, mytid) == -1) {
...
    // first time
    _error_reported = true;
```

**Comment by stefank** [comment]
@tstuefe @dholmes-ora What's the path forward with this PR? Have your reconciled and come to a conclusion about what you want me to change?

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by dholmes-ora** [comment]
> 
> 
> @tstuefe @dholmes-ora What's the path forward with this PR? Have your reconciled and come to a conclusion about what you want me to change?

I have no particular "wants" in this area I was just trying to evaluate the two proposals. Thomas seems fine with your original proposal now. I thought you were suggesting above you should be using `fatal_error_in_progress()` instead, so I'm not sure if this is your final proposal. If it is then I'm fine with it. There's no perfect solution when it comes to error reporting.
Thanks.

**Comment by tstuefe** [comment]
Yes, I am fine with this. I would have prepared a simpler solution as I originally proposed, but do not want to block this patch.

Thanks, Thomas

**Comment by stefank** [comment]
@dholmes-ora @tstuefe OK. Thanks. I'll go ahead with what I'm currently having, and we can continue to chip away at this in follow-up RFEs (if we find the time to).

**Pull request closed without merging**
