### PR TITLE
8284578: Relax InterpreterCodelet stub alignment

### PR DESCRIPTION
**Pull request by shipilev**
`InterpreterCodelet` is aligned by `CodeEntryAlignment` (`CAE`) twice. First, the entire stub is aligned, which aligns its data section. Then, the code section in the stub is aligned. Since `CAE` is usually larger than the size of `InterpreterCodelet`, we are wasting quite a bit of space for each codelet. In the extreme cases, like PPC that defaults to `CAE=128`, we have 16 bytes of codelet data effectively taking 128 bytes!

This can be made better by relaxing the `InterpreterCodelet` stub alignment to `HeapWordSize`, while leaving its code section alignment the same.

This tangentially touches the only other user for `StubQueue`: `ICStub`. Unfortunately, we cannot do the same kind of relaxation there, because there is a reverse lookup function that needs to reach data section from the code section, which forces us to keep the same alignment for both.

Interpreter sizes on Linux x86_64 release:

```
# Baseline, CEA=32 (default)
code size        =     94K bytes
avg codelet size =    356  bytes

# Baseline, CEA=128 (PPC-like)
code size        =    133K bytes
avg codelet size =    501  bytes

# Patched, CEA=32 (default)
code size        =     89K bytes
avg codelet size =    338  bytes

# Patched, CEA=128 (PPC-like)
code size        =    100K bytes
avg codelet size =    380  bytes
```

Point performance runs (SPECjvm2008:serial with `-Xint` on Linux x86_64 release):

```
Benchmark     Mode  Cnt   Score   Error  Units

# Baseline, CEA=32
Serial.test  thrpt    9  73.427 ± 0.152  ops/s

# Baseline, CEA=128
Serial.test  thrpt    9  70.999 ± 0.246  ops/s

# Patched, CEA=32
Serial.test  thrpt    9  73.991 ± 0.860  ops/s

# Patched, CEA=128
Serial.test  thrpt    9  72.981 ± 0.301  ops/s
```

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug `tier2`
 - [x] Linux x86_64 fastdebug `tier3`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284578](https://bugs.openjdk.java.net/browse/JDK-8284578): Relax InterpreterCodelet stub alignment

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8159/head:pull/8159` \
`$ git checkout pull/8159`

Update a local copy of the PR: \
`$ git checkout pull/8159` \
`$ git pull https://git.openjdk.java.net/jdk pull/8159/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8159`

View PR using the GUI difftool: \
`$ git pr show -t 8159`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8159.diff">https://git.openjdk.java.net/jdk/pull/8159.diff</a>

</details>

### CODE REVIEW

**Comment by dean-long** [comment]
Does your change make this recent change obsolete, or is it still needed?

https://github.com/openjdk/jdk/blob/026b85303c01326bc49a1105a89853d7641fcd50/src/hotspot/share/interpreter/templateInterpreter.cpp#L53

**Comment by shipilev** [comment]
> Does your change make this recent change obsolete, or is it still needed?
> 
> https://github.com/openjdk/jdk/blob/026b85303c01326bc49a1105a89853d7641fcd50/src/hotspot/share/interpreter/templateInterpreter.cpp#L53

Checked, the additional slack space for alignment is still needed for the `compiler/arguments/TestCodeEntryAlignment.java` that tries large `CodeEntryAlignment`-s. `CodeEntryAlignment*2` is too much. `HeapWordSize * 2` is not enough. `HeapWordSize + CodeEntryAlignment` fits the intent of the patch. See new commit.

**Review by vnkozlov — COMMENTED** [review]
Looks good. I will test it.

**Review by vnkozlov — APPROVED** [review]
Testing passed.

**Review by dean-long — APPROVED** [review]
Looks good.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
