### PR TITLE
8345795: Update copyright year to 2024 for hotspot in files where it was missed

### PR DESCRIPTION
**Pull request by magicus**
Some files have been modified in 2024, but the copyright year has not been properly updated. This should be fixed. 

I have located these modified files using:
```
git log --since="Jan 1" --name-only --pretty=format: | sort -u > file.list
```
and then run a script to update the copyright year to 2024 on these files.

I have made a manual sampling of files in the list to verify that they have indeed been modified in 2024.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345795](https://bugs.openjdk.org/browse/JDK-8345795): Update copyright year to 2024 for hotspot in files where it was missed (**Bug** - P4)

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - **Reviewer**) Review applies to [0166c68e](https://git.openjdk.org/jdk/pull/22637/files/0166c68e281bb6f253e8ead5effedf088fb6b6d8)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) Review applies to [0166c68e](https://git.openjdk.org/jdk/pull/22637/files/0166c68e281bb6f253e8ead5effedf088fb6b6d8)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22637/head:pull/22637` \
`$ git checkout pull/22637`

Update a local copy of the PR: \
`$ git checkout pull/22637` \
`$ git pull https://git.openjdk.org/jdk.git pull/22637/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22637`

View PR using the GUI difftool: \
`$ git pr show -t 22637`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22637.diff">https://git.openjdk.org/jdk/pull/22637.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22637#issuecomment-2527769698)
</details>

### CODE REVIEW

**Comment by magicus** [comment]
Apologies for the force push; I accidentally pushed a commit that belonged to another branch here, and I just rolled back that commit.

**Review by dougxc — APPROVED** [review]
JVMCI changes look good.

**Review by sspitsyn — APPROVED** [review]
I've looked at the Serviceability related copyright updates (prims, SA, debugger and tests). They are good.

**Review by dholmes-ora — APPROVED** [review]
I scanned the full diff and also did some random checks. Looks good. Thanks for fixing.

**Review by tschatzl — APPROVED** [review]
lgtm, looked at gc files in both shared and cpu and os specific directories.

**Comment by magicus** [comment]
Thanks for all reviews!
/integrate

**Pull request closed without merging**
