### PR TITLE
8273578: javax/swing/JMenu/4515762/bug4515762.java fails on macOS 12

### PR DESCRIPTION
**Pull request by prsadhuk**
The test sometimes fail on macos12 citing "Action has not been received". Seems like some key events sometimes are not received reliably. 
Proposed fix is to apply mach5 stability fixes which is to set autodelay to 100ms, move frame to center of screen from top-left, added extra waitForIdle(), wait for 1 sec after frame is made visible.
Additionally, it is seen that it mixes Util.hitKeys and robot.keyPress/Release. Changed to make it use robot.keyPress/keyRelease all times. Also, updated test to have specific error message for specific keyevent so that we know which keyevent is not received in case it fails again.

Run on mac12 and all other platforms multiple times and test run is green. Link in JBS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273578](https://bugs.openjdk.java.net/browse/JDK-8273578): javax/swing/JMenu/4515762/bug4515762.java fails on macOS 12

### Reviewers
 * [Jayathirth D V](https://openjdk.java.net/census#jdv) (@jayathirthrao - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to ff8796cef51150d7212073260313ff79babf43a2

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5564/head:pull/5564` \
`$ git checkout pull/5564`

Update a local copy of the PR: \
`$ git checkout pull/5564` \
`$ git pull https://git.openjdk.java.net/jdk pull/5564/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5564`

View PR using the GUI difftool: \
`$ git pr show -t 5564`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5564.diff">https://git.openjdk.java.net/jdk/pull/5564.diff</a>

</details>

### CODE REVIEW

**Review by jayathirthrao — APPROVED** [review]

**Review by mrserb — APPROVED** [review]
Let's see what additional information by this logging we can get next time.

**Comment by mrserb** [comment]
Do you need to remove it from the problem list?

**Comment by jayathirthrao** [comment]
8273578 is used in problem lists: [test/jdk/ProblemList.txt] dont know why this error is shown. I dont see it in problemList.
@prsadhuk please verify before push.

**Review by jayathirthrao — APPROVED** [review]

**Pull request closed without merging**
