### PR TITLE
8314831: NMT tests ignore vm flags

### PR DESCRIPTION
**Pull request by mseledts**
Some NMT tests do not pass Java/JVM test command line options (flags) to the child process. Such tests should be examined and broken down into 2 categories:
  - a test intentionally does not pass flags to child process - mark such tests with "@requires vm.flagless"
  - tests did not pass flags to child process by mistake - fix them to use the right ProcessTools method that passes test flags to child process

For details see the JBS issue, including on how the tests were assigned to each category and the reasoning behind it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314831](https://bugs.openjdk.org/browse/JDK-8314831): NMT tests ignore vm flags (**Sub-task** - P3)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Gerard Ziemski](https://openjdk.org/census#gziemski) (@gerard-ziemski - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15576/head:pull/15576` \
`$ git checkout pull/15576`

Update a local copy of the PR: \
`$ git checkout pull/15576` \
`$ git pull https://git.openjdk.org/jdk.git pull/15576/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15576`

View PR using the GUI difftool: \
`$ git pr show -t 15576`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15576.diff">https://git.openjdk.org/jdk/pull/15576.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15576#issuecomment-1707582289)

### CODE REVIEW

**Comment by mseledts** [comment]
Testing:
  - ran NMT tests (test/hotspot/jtreg/runtime/NMT) w/o flags - PASS
  - ran NMT tests with various flags - see JBS issue for details

**Review by lmesnik — APPROVED** [review]
Changes looks good.

**Review by tstuefe — APPROVED** [review]
Okay. Are createTestJVM and createJavaProcessBuilder equivalent?

**Review by gerard-ziemski — CHANGES_REQUESTED** [review]
The `ProcessTools.createJavaProcessBuilder()` -> `ProcessTools.createTestJvm()` change looks OK, but shouldn't we use `createJavaProcessBuilderIgnoreTestJavaOpts()` for those tests that do not want arguments passed, instead of tagging them with "@requires vm.flagless" or am I understanding the point of https://github.com/openjdk/jdk/pull/15452 incorrectly?

**Comment by mseledts** [comment]
To answer a question from Thomas: Are createTestJVM and createJavaProcessBuilder equivalent?

The difference is that createTestJVM() will pass the main/parent JVM command line flags to the child JVM, while createJavaProcessBuilder() will not.

**Comment by mseledts** [comment]
To answer a question from Gerard: shouldn't we use createJavaProcessBuilderIgnoreTestJavaOpts() ?
A: even though MR for " 8315097: Rename createJavaProcessBuilder #15452 " is related in topic to this change, it is still under discussion and could take some time to make final decision on it. Once decision is done and change 15452 is approved, the global renaming will be applied.

As far as tagging tests with "@requires vm.flagless" - this is our (HotSpot) recommended way of tagging tests that do not pass the JVM args to child VM. This is done in addition to using createJavaProcessBuilder(). This provides us a uniform way of knowing which tests do not pass flags to child VMs, we can make proper test selection when executing with flags based on that information.

**Comment by RogerRiggs** [comment]
Specifically, `createTestJVM()` prepends flags from the system properties `test.vm.opts` and `test.java.opts` usually set by jtreg.

**Comment by gerard-ziemski** [comment]
> To answer a question from Gerard: shouldn't we use createJavaProcessBuilderIgnoreTestJavaOpts() ? A: even though MR for " 8315097: Rename createJavaProcessBuilder #15452 " is related in topic to this change, it is still under discussion and could take some time to make final decision on it. Once decision is done and change 15452 is approved, the global renaming will be applied.
> 
> As far as tagging tests with "@requires vm.flagless" - this is our (HotSpot) recommended way of tagging tests that do not pass the JVM args to child VM. This is done in addition to using createJavaProcessBuilder(). This provides us a uniform way of knowing which tests do not pass flags to child VMs, we can make proper test selection when executing with flags based on that information.

I thought we may want to use 15452, but if we have to get this patch in now, then tweak it later a bit and you're OK with that, then so am I.

**Review by gerard-ziemski — APPROVED** [review]

**Comment by mseledts** [comment]
Thank you Leonid, Thomas, Gerard.

/integrate

**Pull request closed without merging**
