### PR TITLE
8290373: Enable lossy conversion warnings on Windows

### PR DESCRIPTION
**Pull request by JornVernee**
This patch enables lossy conversion warnings (C4244 [1]) for hotspot on Windows/MSVC. Instead of fixing all warnings that were produced from this, I've instead locally disabled the warning in the files that produced warnings. This allows gradually making progress with cleaning up these warnings on a per-file basis, instead of trying to fix all of them in one shot. i.e. it is not meant as a long term solution, but as a way of allowing incremental progress.

Out of the ~1100 files that make up hotspot on Windows x64 , ~290 have warnings for them disabled (not counting aarch64 files), which means that with this patch ~800 files are protected by enabling this warning globally.

Warnings can be fixed in individual files, or groups of files in followup patches, and warnings for those files can be enabled.

I'm working on a patch that does the same for GCC, but it produces warnings in about 150 more files, so I wanted to gather feedback on this approach before continuing with that.

---

To disable warnings for a file, in most cases the following prelude is added after the last `#include` at the start of a file:

    PRAGMA_DIAG_PUSH
    PRAGMA_ALLOW_LOSSY_CONVERSIONS

And then the following is added at the end of the file for cpp files, or before closing the header guard for hpp files:

    PRAGMA_DIAG_POP

1 notable exception are files produced by adlc, which had their code-gen modified to add these lines instead. There were also 2 files that include headers in the middle of the file (ostream.cpp & sharedRuntime.cpp), for which I've added the PRAGMA's after the include block at the start of the file instead. They only included system headers, for which disabling warnings doesn't matter any ways.

[1]: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-170

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290373](https://bugs.openjdk.org/browse/JDK-8290373): Enable lossy conversion warnings on Windows

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9516/head:pull/9516` \
`$ git checkout pull/9516`

Update a local copy of the PR: \
`$ git checkout pull/9516` \
`$ git pull https://git.openjdk.org/jdk pull/9516/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9516`

View PR using the GUI difftool: \
`$ git pr show -t 9516`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9516.diff">https://git.openjdk.org/jdk/pull/9516.diff</a>

</details>

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Small question: What's the equivalent option to disable the same warning for gcc? (slightly related to https://bugs.openjdk.org/browse/JDK-8288293)

**Comment by JornVernee** [comment]
@TheShermanTanker It's `-Wconversion`. You will have to disable the warning for non-hotspot binaries to get the equivalent behavior. See this commit: https://github.com/openjdk/jdk/commit/44bebd84c041d62f374bfb6f61685d86e5e41518

**Comment by dean-long** [comment]
I thought PRAGMA_DIAG_PUSH/POP are for narrowing the scope of the pragma.  So unless we are concatenating .cpp files together, I would think they are not needed for .cpp files if we want to affect the whole file.

**Comment by theRealAph** [comment]
This feels to me like rather a blunt instrument. IMO, it would be better to use checked_cast() where lossy conversions happen. That would make code easier to understand, and it'd give us warnings when things go wrong.

**Comment by JornVernee** [comment]
@theRealAph I think ultimately, each warning site should be inspected, and a bespoke solution should be found. Inserting `checked_cast` is only one of a possible set of solutions. Others being changing the type of variables used, or some wider refactoring.

This change was mostly applied mechanically by parsing the build log, and then using a script to insert these lines, with a manual review + 1 or 2 fixups. Making sure the inserted `checked_cast`s are correct seems much harder.

I think having `PRAGMA_ALLOW_LOSSY_CONVERSIONS` in the file also sends a much clearer message that: warnings in this file have not been looked at/fixed yet, which I don't think `checked_cast` does.

I have my doubts that adding `checked_cast` everywhere is always the correct. In some cases the truncation might be the desired behaviour (just not made explicit with a cast), and I don't want to run the risk of breaking such code where the tests don't catch it (while I also don't want to get into a lengthy process of fixing up those cases one by one).

The approach I've taken preserves the current behavior of the code, but it also allows for fixing these warnings on a per-file basis. This seems to me like an easier and safer way to make progress.

**Comment by theRealAph** [comment]
> This change was mostly applied mechanically by parsing the build log, and then using a script to insert these lines, with a manual review + 1 or 2 fixups. Making sure the inserted `checked_cast`s are correct seems much harder.

It is.

> I think having `PRAGMA_ALLOW_LOSSY_CONVERSIONS` in the file also sends a much clearer message that: warnings in this file have not been looked at/fixed yet, which I don't think `checked_cast` does.

It kinda would, because such casts would have to be considered. But OK.

> The approach I've taken preserves the current behavior of the code, but it also allows for fixing these warnings on a per-file basis (besides enabling the warning for the 800 or so files that don't have warnings right now). This seems to me like an easier and safer way to make progress.

OK, so this is hopefully a temporary fix.

**Comment by JornVernee** [comment]
> > I think having `PRAGMA_ALLOW_LOSSY_CONVERSIONS` in the file also sends a much clearer message that: warnings in this file have not been looked at/fixed yet, which I don't think `checked_cast` does.
> 
> It kinda would, because such casts would have to be considered. But OK.

What I mean is that `checked_cast` can also be used intentionally. So, looking at a particular `checked_cast` it might be hard to tell if this use case should still be address/fixed. or if it has already been addressed and the solution was to use `checked_cast`.

> > The approach I've taken preserves the current behavior of the code, but it also allows for fixing these warnings on a per-file basis (besides enabling the warning for the 800 or so files that don't have warnings right now). This seems to me like an easier and safer way to make progress.
> 
> OK, so this is hopefully a temporary fix.

Yes, this is not meant to be a long term solution. Just a way of allowing for more incremental progress, as well as a stop gap for files that are good today.

**Comment by dholmes-ora** [comment]
So IIUC the idea here is to turn on this warning to catch lossy conversions going forward, but to suppress the warning on all existing cases in the hope that eventually one day they will get looked at and fixed as appropriate.

Is this such an insidious problem that we absolutely must prevent any future occurrences from arising, noting that if they happen if a file already ignoring the warning then we won't notice anyway?

To me this needs to be a first step in a well-defined and resourced plan to actually address these issues, not just the first step with a hope other steps will follow.

Just my 2c.

Cheers.

**Comment by JornVernee** [comment]
I think these warnings are a nice-to-have. Kinda like a certain code style. However, I don't think it's important enough to organize people and go through fixing each and every one of them in the 450 or so files all at once.

The warnings being either unimportant enough to turn them off like we do now, or being important enough to turn them on and fix all of them is, I think, a false dichotomy. In reality, the importance of fixing these warnings seems to be more in the middle. And I think this is what leads to a stalemate (the original JBS issue for this was filed in 2015 [1]). So, instead I'd like to suggest a compromise instead. 

We could have a policy similar to how styling is fixed currently in HotSpot (mostly in the compiler code). In that case styling is fixed in the surrounding code that is touched by a patch.

In the case of these warnings, I propose that when a patch touches a file with lossy conversion warnings disabled, it should also enable the warnings and fix them for that file. Maybe it's useful to rename the macro to something like `PRAGMA_FIXME_LOSSY_CONVERSIONS` for that as well.

[1] : https://bugs.openjdk.org/browse/JDK-8135181

**Comment by dholmes-ora** [comment]
>  I propose that when a patch touches a file with lossy conversion warnings disabled, it should also enable the warnings and fix them for that file.

This contradicts other common recomendations of not mixing unrelated issues in the same PR. Fixing style nits is harmless but fixing an actual lossy conversion issue could itself lead to bugs and unexpected fanout.

**Comment by JornVernee** [comment]
> > I propose that when a patch touches a file with lossy conversion warnings disabled, it should also enable the warnings and fix them for that file.
> 
> This contradicts other common recomendations of not mixing unrelated issues in the same PR. Fixing style nits is harmless but fixing an actual lossy conversion issue could itself lead to bugs and unexpected fanout.

That's a good point. I think that takes piggybacking on other patches off the table then.

**Comment by magicus** [comment]
While I normally appreciate enabling warnings, and fixing them, I tend to side a bit with David on this one. There is a lot of `PRAGMA_ALLOW_LOSSY_CONVERSIONS` in this PR, injected into the files, forever to be forgotten.

I do agree with @JornVernee  that warnings are in a bit of a bind; if we really think a warning is useful, but it has been historically turned off, it is a huge uphill battle to get it enabled, by fixing all historical issues at once. This results in warnings being left turned off, even for new code, since no-one has the time available to address all issues at once.

I'm thinking that part of this problem is due to the lack of granularity that the build systems offers to enable/disable warnings. We have a "global" enable, and then we have a "per dll" disable.

It would not be too hard for me to modify this, so we could make a list of source files for which the conversion warning still needs to be turned off. If this is a coherent list in a single make file, it is much easier to see what remains to be done to actually fix these issues. (This will not work for .hpp files; these will still need the pragma push/pop thing, and should therefore be prioritized when actually fixing this.)

Still, the warnings need to be fixed (or the list will need to be kept indefinitely, which is of course also a valid solution). And we need to be prepared to put in effort to actually resolve these, if we really want this to happen.

**Comment by JornVernee** [comment]
Thanks @magicus turning off warnings in a side file also seems like a decent solution.

I think part of the problem with tackling all warnings at once is that it's (too) hard to decide whether it's worth doing, since there's such a huge volume of warnings. It's much easier to decide that for a couple of files, and then put in the work. i.e. employ a divide and conquer strategy.

Maybe some of the warnings will never be fixed, because it just isn't worth the effort in some cases. But, this still seems better than globally disabling the warning to me.

I think it's mostly an organizational/workflow issue, rather than a technical one.

**Comment by JornVernee** [comment]
I don't think this will go anywhere, so I'll just close the PR.

Thanks for the discussion on the idea!

**Pull request closed without merging**
