### PR TITLE
8290715: Fix incorrect uses of G1CollectedHeap::heap_region_containing()

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that fixes some callers of `G1CollectedHeap::heap_region_containing` to a) fail on trying to get the `Heapregion*` on uncommitted regions and b) change some callers to use the correct `heap_region_containing_or_null` method that had been intended there.

Also remove some now unneccessary asserts as `heap_region_containing` will fail when it previously returned `nullptr`.

Testing: tier1-5

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290715](https://bugs.openjdk.org/browse/JDK-8290715): Fix incorrect uses of G1CollectedHeap::heap_region_containing()

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Sangheon Kim](https://openjdk.org/census#sangheki) (@sangheon - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9584/head:pull/9584` \
`$ git checkout pull/9584`

Update a local copy of the PR: \
`$ git checkout pull/9584` \
`$ git pull https://git.openjdk.org/jdk pull/9584/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9584`

View PR using the GUI difftool: \
`$ git pr show -t 9584`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9584.diff">https://git.openjdk.org/jdk/pull/9584.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by sangheon — APPROVED** [review]
Looks good.

**Comment by tschatzl** [comment]
Thanks @kimbarrett @sangheon for your reviews.

**Pull request closed without merging**
