### PR TITLE
JDK-8286783: Expand use of @inheritDoc in InputStream and OutputStream subclasses

### PR DESCRIPTION
**Pull request by jddarcy**
Make the javadoc in the InputStream and OutputStream subclasses in core libs DRY-er by use of inheritDoc. (Any analagous changes to AudioInputStream in client libs will be done another a separate bug.) When the time comes, will do any necessary merging for the changes in[JDK-8286200.

Please also review the CSR to cover the introduction of implspec and implNote tags: https://bugs.openjdk.java.net/browse/JDK-8286784

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8286783](https://bugs.openjdk.java.net/browse/JDK-8286783): Expand use of @inheritDoc in InputStream and OutputStream subclasses
 * [JDK-8286784](https://bugs.openjdk.java.net/browse/JDK-8286784): Expand use of @inheritDoc in InputStream and OutputStream subclasses (**CSR**)

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8717/head:pull/8717` \
`$ git checkout pull/8717`

Update a local copy of the PR: \
`$ git checkout pull/8717` \
`$ git pull https://git.openjdk.java.net/jdk pull/8717/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8717`

View PR using the GUI difftool: \
`$ git pr show -t 8717`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8717.diff">https://git.openjdk.java.net/jdk/pull/8717.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
Picking FileInputStream at random, I wonder if the `@inheritDoc` on transferTo is needed. Also, I think you've attempted to add `@Override` to all overridden methods but some may have been missed (e.g. readAllBytes and readNBytes).

**Review by pavelrappo — COMMENTED** [review]
1. One the one hand, it's not clear to me what criterion was used for adding `@Override` annotations. On the other hand, the more `@Override` annotations a codebase has, the better.
2. Have you compared the resulting documentation before and after the change? Aside from added `@implSpec` and `@implNote`, were there anything anything different?
3. I wonder if it makes sense to also reduce the size of the doc comments by changing explicit documentation inheritance for the `@param` and `@return` tags to implicit one, i.e. removing the tags on the overrider's side.

**Comment by jddarcy** [comment]
> 1. One the one hand, it's not clear to me what criterion was used for adding `@Override` annotations. On the other hand, the more `@Override` annotations a codebase has, the better.
> 
>     2. Have you compared the resulting documentation before and after the change? Aside from added `@implSpec` and `@implNote`, were there anything anything different?
> 
>     3. I wonder if it makes sense to also reduce the size of the doc comments by changing explicit documentation inheritance for the `@param` and `@return` tags to implicit one, i.e. removing the tags on the overrider's side.

I added the `@Override` annotations to methods I reviewed and/or updated; it was not necessarily an exhaustive process. I have not run specdiff to double-check the expected changes; it would be more thorough to do so. The intention is to only have minor wording changes apart from the `@implSpec` and `@implNote` tags. Stylistically, I'd prefer the explicit `@foo {@inhertiDoc}` idiom to indicate the code just want to use the javadoc from a supertype.

**Review by AlanBateman — APPROVED** [review]
thanks for the updates.

**Comment by jddarcy** [comment]
> thanks for the updates.

Updated the CSR to match this version.

**Pull request closed without merging**
