### PR TITLE
8286800: Assert in PhaseIdealLoop::dump_real_LCA is too strong

### PR DESCRIPTION
**Pull request by chhagedorn**
We sometimes hit the following assert when dumping a bad graph (before crashing with the bad graph assertion):
```
assert(real_LCA != NULL, "must always find an LCA"
``` 
The algorithm is not correct as we should always find an LCA of two nodes. To fix this, I've re-implemented the algorithm and improved the dumped idom chains:
- I limited the node dump to idx + node name to reduce the noise which made it hard to read.
- Reversed the idom chain dumps to reflect the graph structure.

Example output:
```
Bad graph detected in build_loop_late
n:  138  CastPP  === 205 38  [[ 263 140 140 168 ]]  #Test:NotNull *  Oop:Test:NotNull * !jvms: Test::mainTest @ bci:40 (line 154)

[... same output as before ...]

idoms of early "197 IfFalse":
idom[2]:    42  If
idom[1]:    44  IfTrue
idom[0]:   196  If
n:         197  IfFalse

idoms of (wrong) LCA "205 IfTrue":
idom[4]:    42  If
idom[3]:    37  Region
idom[2]:    73  If
idom[1]:    83  IfTrue
idom[0]:   204  If
n:         205  IfTrue

Real LCA of early "197 IfFalse" (idom[2]) and wrong LCA "205 IfTrue" (idom[4]):
  42  If  === 30 41  [[ 43 44 ]] P=0.999000, C=-1.000000 !jvms: Test::mainTest @ bci:32 (line 153)
```
Tested by manually calling `dump_idoms` during a compilation and by running reproducers of different bad graph assertion bugs.

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286800](https://bugs.openjdk.org/browse/JDK-8286800): Assert in PhaseIdealLoop::dump_real_LCA is too strong

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11015/head:pull/11015` \
`$ git checkout pull/11015`

Update a local copy of the PR: \
`$ git checkout pull/11015` \
`$ git pull https://git.openjdk.org/jdk pull/11015/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11015`

View PR using the GUI difftool: \
`$ git pr show -t 11015`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11015.diff">https://git.openjdk.org/jdk/pull/11015.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review!

**Comment by chhagedorn** [comment]
Thank you Roberto for the suggestion! That is indeed cleaner. I've pushed an update accordingly. To make it easier, I've pushed `_early` and `_wrong_lca` to the node lists of `find_real_lca()`.

**Review by robcasloz — APPROVED** [review]
Thanks for taking the suggestion into account, looks good!

**Review by vnkozlov — APPROVED** [review]
Update looks good.

**Comment by chhagedorn** [comment]
Thank you Roberto and Vladimir for your reviews!

/integrate

**Pull request closed without merging**
