### PR TITLE
8309196: Remove Thread.countStackFrames

### PR DESCRIPTION
**Pull request by AlanBateman**
Thread.countStackFrames is/was an ill-defined method that dates from JDK 1.0 for counting the stack frames of a suspended Thread. The method was deprecated in JDK 1.2 (1998), deprecated for removal in Java 9, and re-specified/degraded to throw UOE unconditionally in Java 14.  Java 22 would be a fine time to finally remove this method.

Code that wants to count stack frames should be directed to use j.l.StackWalker, or if a tool, then it can use JVM TI and other tool APIs.

A corpus analysis of 30M classes in 131k artifacts from Maven Central found only 1 usages to this method. The 1 usage appears to be a class that just wraps all methods, it doesn't actually make use of it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8309201](https://bugs.openjdk.org/browse/JDK-8309201) to be approved

### Issues
 * [JDK-8309196](https://bugs.openjdk.org/browse/JDK-8309196): Remove Thread.countStackFrames (**Enhancement** - P4)
 * [JDK-8309201](https://bugs.openjdk.org/browse/JDK-8309201): Remove Thread.countStackFrames (**CSR**)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14257/head:pull/14257` \
`$ git checkout pull/14257`

Update a local copy of the PR: \
`$ git checkout pull/14257` \
`$ git pull https://git.openjdk.org/jdk.git pull/14257/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14257`

View PR using the GUI difftool: \
`$ git pr show -t 14257`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14257.diff">https://git.openjdk.org/jdk/pull/14257.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14257#issuecomment-1571968036)

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
Looks good.

**Review by mlchung — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Yes :)

**Review by jaikiran — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Happy to see this being removed early in JDK 22!

**Comment by AlanBateman** [comment]
Wakeup bot, you should be able to connect the CSR for 22 now.

**Pull request closed without merging**
