### PR TITLE
JDK-8315505: CompileTask timestamp printed can overflow

### PR DESCRIPTION
**Pull request by tstuefe**
Trivial fix to a printing overflow.

Example, VM running for 88 days:

Before
```
 22 Time: Fri Sep  1 12:52:14 2023 CEST elapsed time: 7609888.526691 seconds (88d 1h 51m 28s)
 23 
...
 28 
 29 Current CompileTask:
 30 C2:-980046066 32 22    1    b        java.lang.invoke.MethodHandle::<clinit> (45 bytes)
       ^^^^^^^^^^
```

Now
```
 22 Time: Fri Sep  1 12:46:36 2023 CEST elapsed time: 7609550.966587 seconds (88d 1h 45m 50s)
 23 
 ...
 28 
 29 Current CompileTask:
 30 C2:7609550966 32 22    1    b        java.lang.invoke.MethodHandle::<clinit> (45 bytes)
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315505](https://bugs.openjdk.org/browse/JDK-8315505): CompileTask timestamp printed can overflow (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15533/head:pull/15533` \
`$ git checkout pull/15533`

Update a local copy of the PR: \
`$ git checkout pull/15533` \
`$ git pull https://git.openjdk.org/jdk.git pull/15533/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15533`

View PR using the GUI difftool: \
`$ git pr show -t 15533`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15533.diff">https://git.openjdk.org/jdk/pull/15533.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15533#issuecomment-1748141851)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by tstuefe** [comment]
> Looks good to me.

Trivial, right?

**Comment by TobiHartmann** [comment]
Yes, trivial.

**Pull request closed without merging**
