### PR TITLE
8275847: Scheduling fails with "too many D-U pinch points" on small method

### PR DESCRIPTION
**Pull request by nick-arm**
Since around JDK 16 the following method cannot be compiled by C2 on AArch64:

```java
  public double mergeSync() { return Math.log(Math.sin(value)); }
```

(Reduced from a slightly larger benchmark.)

```
  811 416 ! 3 Test::mergeSync (61 bytes)
  813 417 ! 4 Test::mergeSync (61 bytes)
  816 417 ! 4 Test::mergeSync (61 bytes) COMPILE SKIPPED: too many D-U pinch points (retry at different tier)
  816 418 ! 1 Test::mergeSync (61 bytes)
```

Scheduling::anti_do_def() will create temporary Nodes for each OptoReg killed by the MachProjs from the two runtime leaf calls.  After SVE support was added these runtime calls kill more registers, and the number of new Nodes added by anti_do_def exceeds an internal limit (which is based on the LRG map size and roughly proportional to the method size).

X86 has the same problem if OptoScheduling is enabled because of the wide AVX registers.

The fix here is to ignore OptoRegs which correspond to the high slots of wide vectors (i.e. slots above 64 bits).  The scheduler doesn't run on methods where C->max_vector_size() > 8, so we know these kills can't affect the scheduling result.

The added test fails on the current JDK with:

```
  compiler.lib.ir_framework.shared.TestRunException: Could not compile public double
  compiler.c2.irTests.TestScheduleSmallMethod.testSmallMethodTwoRuntimeCalls(double) at level C2
  after 10s. Last compilation level: 3
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275847](https://bugs.openjdk.java.net/browse/JDK-8275847): Scheduling fails with "too many D-U pinch points" on small method

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6131/head:pull/6131` \
`$ git checkout pull/6131`

Update a local copy of the PR: \
`$ git checkout pull/6131` \
`$ git pull https://git.openjdk.java.net/jdk pull/6131/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6131`

View PR using the GUI difftool: \
`$ git pr show -t 6131`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6131.diff">https://git.openjdk.java.net/jdk/pull/6131.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me but a second review would be good.

/reviewers 2

**Review by vnkozlov — COMMENTED** [review]
Seems fine to me but I need to run testing before approval.

**Review by vnkozlov — APPROVED** [review]
Testing results look good.

**Comment by nick-arm** [comment]
Thanks for the reviews. The Windows x64 build failure looks to be spurious, I re-ran the GitHub actions here: https://github.com/nick-arm/jdk/runs/4133872978

**Pull request closed without merging**
