### PR TITLE
8301630: C2: 8297933 broke type speculation in some cases

### PR DESCRIPTION
**Pull request by rwestrel**
With 8297933, a TypeAryPtr is a lot more likely to have a null _klass
and that breaks TypePtr::speculative_type().

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301630](https://bugs.openjdk.org/browse/JDK-8301630): C2: 8297933 broke type speculation in some cases

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12368/head:pull/12368` \
`$ git checkout pull/12368`

Update a local copy of the PR: \
`$ git checkout pull/12368` \
`$ git pull https://git.openjdk.org/jdk pull/12368/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12368`

View PR using the GUI difftool: \
`$ git pr show -t 12368`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12368.diff">https://git.openjdk.org/jdk/pull/12368.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. I'll re-run testing and report back.

**Comment by rwestrel** [comment]
@TobiHartmann thanks for the review and tests. @chhagedorn 's review was on the previous version of this fix so I'd like another review. Anyone?

**Review by chhagedorn — APPROVED** [review]
The update looks good to me, too!

**Comment by rwestrel** [comment]
@chhagedorn thanks for the review.

**Pull request closed without merging**
