### PR TITLE
JDK-8264572: ForkJoinPool.getCommonPoolParallelism() reports always 1

### PR DESCRIPTION
**Pull request by DougLea**
This reinserts setting common pool parallelism inadvertently clobbered in JDK-8259800

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264572](https://bugs.openjdk.java.net/browse/JDK-8264572): ForkJoinPool.getCommonPoolParallelism() reports always 1

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3324/head:pull/3324` \
`$ git checkout pull/3324`

Update a local copy of the PR: \
`$ git checkout pull/3324` \
`$ git pull https://git.openjdk.java.net/jdk pull/3324/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3324`

View PR using the GUI difftool: \
`$ git pr show -t 3324`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3324.diff">https://git.openjdk.java.net/jdk/pull/3324.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
This looks okay to me, I just wonder if we should have a test to the value of getCommonPoolParallelism.

**Comment by DougLea** [comment]
We once had a test, but now that Runtime.availableProcessors (the only means of checking) can return varying values, we can't include in tck  tests. The error here wasn't caught  because we didn't run the usual performance tests (that catch these problems immediately) because I was focused only on JDK-8259800. Sorry.

**Pull request closed without merging**
