### PR TITLE
8323115: x86-32: Incorrect predicates for cmov instruct transforms with UseSSE

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that fixes generation of CMOV by C2 as controlled by
UseSSE.  The predicates controlling that generation were using implicit
operator precedence that didn't have the expected grouping.  Fixed by adding
parentheses to make the desired grouping explicit.

Testing: Ran GHA with -Wparentheses enabled along with this and other changes
needed to make that work.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323115](https://bugs.openjdk.org/browse/JDK-8323115): x86-32: Incorrect predicates for cmov instruct transforms with UseSSE (**Bug** - P3)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17296/head:pull/17296` \
`$ git checkout pull/17296`

Update a local copy of the PR: \
`$ git checkout pull/17296` \
`$ git pull https://git.openjdk.org/jdk.git pull/17296/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17296`

View PR using the GUI difftool: \
`$ git pr show -t 17296`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17296.diff">https://git.openjdk.org/jdk/pull/17296.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17296#issuecomment-1880527610)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
The fix looks good to me but it's concerning that we never hit this in our testing. Maybe it never fails because the expanded instructions are guarded by `predicate (UseSSE ...` as well.

**Comment by shipilev** [comment]
> The fix looks good to me but it's concerning that we never hit this in testing. Maybe it never fails because the expanded instructions are guarded by `predicate (UseSSE ...` as well.

In my experience fixing bugs in these FPU-related match rules is that it takes a combination of code shape and relevant hardware (that defaults for unusual `UseSSE <= 2`), or specific testing that runs with lower `UseSSE`. I think I was one of the few remaining people who ran x86_32 with `-XX:UseSSE=0`, for example, but finally stopped. I think going forward we would just need to require `UseSSE >= 2` for x86_32, like for x86_64, making these issues go away.

**Comment by kimbarrett** [comment]
Thanks for reviews, @shipilev and @TobiHartmann .

**Comment by iwanowww** [comment]
> The fix looks good to me but it's concerning that we never hit this in testing.

@TobiHartmann it looks more like the bug is benign since the predicates are effectively redundant. The AD instructions have different operands (`regFPR`/`regDPR` vs `regF`/`regD` which also have `UseSSE` predicates) , so they don't conflict at runtime.

**Pull request closed without merging**
