### PR TITLE
8292206: TestCgroupMetrics.java fails as getMemoryUsage() is lower than expected

### PR DESCRIPTION
**Pull request by iklam**
The `testMemoryUsage()` test scenario queries the total memory usage of all processes of the current Linux user, including other concurrently running jtreg test cases. Even if the current process allocates 256MB of ram, it's possible for other dying processes to release much more than that amount. Therefore, it's not possible to guarantee that `Metrics.getMemoryUsage()` would return a higher number.

I am removing this test scenario for now as I don't see it providing any actual value.

If we want to have more in-depth functional tests for the `Metrics.getMemoryXXX()` APIs, we need to do it inside a container in a more controlled setting.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292206](https://bugs.openjdk.org/browse/JDK-8292206): TestCgroupMetrics.java fails as getMemoryUsage() is lower than expected

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [8f27544b](https://git.openjdk.org/jdk/pull/11734/files/8f27544ba801c106c925ecf8383f2fdaa708f5c7)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11734/head:pull/11734` \
`$ git checkout pull/11734`

Update a local copy of the PR: \
`$ git checkout pull/11734` \
`$ git pull https://git.openjdk.org/jdk pull/11734/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11734`

View PR using the GUI difftool: \
`$ git pr show -t 11734`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11734.diff">https://git.openjdk.org/jdk/pull/11734.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Note: theoretically other test scenarios can also fail for the same reason, but we've never seen them fail in our CI pipeline

https://github.com/openjdk/jdk/blob/ba942c24e8894f4422870fb53253f5946dc4f0d1/test/lib/jdk/test/lib/containers/cgroup/MetricsTesterCgroupV1.java  (see lines L250-L254)

```
        oldVal = metrics.getKernelMemoryMaxUsage();
        newVal = getLongValueFromFile(Controller.MEMORY, "memory.kmem.max_usage_in_bytes");
        if (!CgroupMetricsTester.compareWithErrorMargin(oldVal, newVal)) {
            fail(Controller.MEMORY, "memory.kmem.max_usage_in_bytes", oldVal, newVal);
        }
```

`compareWithErrorMargin` checks that the difference is less than 25%, which probably will never happen between the first two lines in the code quoted above. Other usage of `compareWithErrorMargin` in the same test may suffer the same problem.

**Review by dholmes-ora — APPROVED** [review]
Removing this seems reasonable. Thanks for the explanation.

**Comment by jerboaa** [comment]
> I am removing this test scenario for now as I don't see it providing any actual value.

I disagree. It seems useful in the docker/container case as there are APIs in the JDK reporting those metrics and it wouldn't be tested otherwise.

Note that this test is also being used by `TestSystemMetrics.java`. Entrypoint in the `TestSystemMetrics` case is `main()` (over entrypoint `testAll()` via `TestCgroupMetrics`).

> If we want to have more in-depth functional tests for the `Metrics.getMemoryXXX()` APIs, we need to do it inside a container in a more controlled setting.

That's what the above mentioned `TestSystemMetrics.java` does. I take it that test is not problematic? If so, we should just not invoke `testMemoryUsage()` when invoked from `TestCgroupMetrics`.

**Comment by iklam** [comment]
> > I am removing this test scenario for now as I don't see it providing any actual value.
> 
> I disagree. It seems useful in the docker/container case as there are APIs in the JDK reporting those metrics and it wouldn't be tested otherwise.
> 
> Note that this test is also being used by `TestSystemMetrics.java`. Entrypoint in the `TestSystemMetrics` case is `main()` (over entrypoint `testAll()` via `TestCgroupMetrics`).
> 
> > If we want to have more in-depth functional tests for the `Metrics.getMemoryXXX()` APIs, we need to do it inside a container in a more controlled setting.
> 
> That's what the above mentioned `TestSystemMetrics.java` does. I take it that test is not problematic? If so, we should just not invoke `testMemoryUsage()` when invoked from `TestCgroupMetrics`.

Thanks for your review. I've disabled the `testMemorySubsystem()` and `testMemoryUsage()` scenarios only when testing outside of containers (in TestCgroupMetrics.java). These scenarios will be executed by TestSystemMetrics.java, which is executed in a container.

**Review by jerboaa — APPROVED** [review]
Looks good, thanks!

**Comment by iklam** [comment]
Thanks @jerboaa and @dholmes-ora for the review.

Tested with tier5 container tests in our CI.

/integrate

**Pull request closed without merging**
