### PR TITLE
8299498: Usage of constructors of primitive wrapper classes should be avoided in java.lang API docs

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
The javadocs of the following methods used deprecated constructors of the primitive wrapper classes:

java.lang.ArrayStoreException
java.lang.Byte.valueOf(String)
java.lang.Byte.valueOf(String, int)
java.lang.ClassCastException
java.lang.Double.compare(double, double)
java.lang.Float.compare(float, float)
java.lang.Integer.getInteger(String, int)
java.lang.Integer.valueOf(String)
java.lang.Integer.valueOf(String, int)
java.lang.Long.getLong(String, long)
java.lang.Long.valueOf(String)
java.lang.Long.valueOf(String, int)
java.lang.Short.valueOf(String)
java.lang.Short.valueOf(String, int) 

This change replaces the constructors with .valueOf() methods except java.lang.ClassCastException which was already fixed in JDK-8289730

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299498](https://bugs.openjdk.org/browse/JDK-8299498): Usage of constructors of primitive wrapper classes should be avoided in java.lang API docs

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to [fc79e191](https://git.openjdk.org/jdk/pull/11912/files/fc79e1917befcc59c0cb3e61a55dec82c31893a2)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to [fc79e191](https://git.openjdk.org/jdk/pull/11912/files/fc79e1917befcc59c0cb3e61a55dec82c31893a2)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11912/head:pull/11912` \
`$ git checkout pull/11912`

Update a local copy of the PR: \
`$ git checkout pull/11912` \
`$ git pull https://git.openjdk.org/jdk pull/11912/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11912`

View PR using the GUI difftool: \
`$ git pr show -t 11912`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11912.diff">https://git.openjdk.org/jdk/pull/11912.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]

**Review by jddarcy — APPROVED** [review]
Looks fine.

**Comment by mlchung** [comment]
It'd be good to update the javadoc of  `Byte.valueOf(String s)` and `Byte.valueOf(String s, int radix)`  to replace  `new Byte(...)` with `Byte.valueOf`.

**Comment by justin-curtis-lu** [comment]
> It'd be good to update the javadoc of `Byte.valueOf(String s)` and `Byte.valueOf(String s, int radix)` to replace `new Byte(...)` with `Byte.valueOf`.

Thanks for spotting that, I will also add those changes into this PR.

**Comment by justin-curtis-lu** [comment]
> Given that type conversions create the primitive wrapper instances when they are needed, I think the examples should be reconsidered. They needlessly suggest that the wrapper instances need to be explicitly created.

Hi Roger, thanks for the comment,

When I was deciding between autoboxing and using the valueOf() methods, I personally saw the latter as providing more clarity from a documentation standpoint but I understand your concerns. Curious what others think on the decision of using one vs the other.

**Comment by RogerRiggs** [comment]
I see your point about clarity; these snippets are not usage examples, but are showing how the method could be implemented. I'd lean toward the auto-boxing technique to keep the example to a minimum.

Since you are updating the example, perhaps they should use `@snippet lang="java" { .... }` instead of the \@code and blockquote markup.

**Comment by jddarcy** [comment]
> > Given that type conversions create the primitive wrapper instances when they are needed, I think the examples should be reconsidered. They needlessly suggest that the wrapper instances need to be explicitly created.
> 
> Hi Roger, thanks for the comment,
> 
> When I was deciding between autoboxing and using the valueOf() methods, I personally saw the latter as providing more clarity from a documentation standpoint but I understand your concerns. Curious what others think on the decision of using one vs the other.

I concur that it is clearer to readers to have the explicit valueOf call in the code examples.

**Comment by mlchung** [comment]
The code is used to show for example `getInteger(String nm, int val)` is equivalent to calling `getInteger(nm, Integer.valueOf(val))`.   I agree with Justin that it's clearer to use the `valueOf` methods.   In fact, `getInteger(String nam, int val)` example can't be represented with autoboxing.

**Review by RogerRiggs — APPROVED** [review]

**Review by mlchung — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Comment by justin-curtis-lu** [comment]
> Since you are updating the example, perhaps they should use `@snippet lang="java" { .... }` instead of the @code and blockquote markup.

That's a good point and Lance brought that up as well, I will create a separate issue to address instances where that change can be made.

**Pull request closed without merging**
