### PR TITLE
8317294: Classloading throws exceptions over already pending exceptions

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for reproducer. I think we are just missing `return` after throwing the previous exception in `ClassFileParser::check_super_interface_access`. So we re-enter the method again with another exception in hand and fail the assert. This path is special, because we are looping, and we really need to exit after the first exception.

It is not easy to add a regression test that pokes into super-interfaces from some JDK internals.

Additional testing:
 - [x] CTW reproducer no longer fails
 - [x] Linux AArch64 `tier1 tier2 tier3` fastdebug

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317294](https://bugs.openjdk.org/browse/JDK-8317294): Classloading throws exceptions over already pending exceptions (**Bug** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [2b78e5b0](https://git.openjdk.org/jdk/pull/15984/files/2b78e5b0bf7087f9a1dabbb1db05943e761b3d9b)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [2b78e5b0](https://git.openjdk.org/jdk/pull/15984/files/2b78e5b0bf7087f9a1dabbb1db05943e761b3d9b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15984/head:pull/15984` \
`$ git checkout pull/15984`

Update a local copy of the PR: \
`$ git checkout pull/15984` \
`$ git pull https://git.openjdk.org/jdk.git pull/15984/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15984`

View PR using the GUI difftool: \
`$ git pr show -t 15984`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15984.diff">https://git.openjdk.org/jdk/pull/15984.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15984#issuecomment-1740953401)

### CODE REVIEW

**Comment by shipilev** [comment]
Any takers? @coleenp, @dholmes-ora, I think you are the experts in this code.

**Review by dholmes-ora — APPROVED** [review]
Yep this is an oversight from the initial module system implementation.

Thanks.

**Comment by shipilev** [comment]
> This looks fine. I have sort of a preference for the two returns to be after the fthrow so I don't have to look and see what the } below it matches, but if you argue the other way, I don't object.

It is not a bother to replace with two returns, did so in the new commit. I'll wait for GHA to clear before integrating.

**Pull request closed without merging**
