### PR TITLE
8306437: jhsdb cannot resolve image/symbol paths being used for analysis of Windows coredumps

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi! The patch fixes image/symbol lookup by jhsdb on alanysis Windows coredump. It uses executableName as a hint prepending image path with

`<executable_folder>;<executable_folder>\server`

and symbol path with

`srv*https://msdl.microsoft.com/download/symbols;<executable_folder>;<executable_folder>\server`

where the first bit points to Windows symbols located on remote server

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306437](https://bugs.openjdk.org/browse/JDK-8306437): jhsdb cannot resolve image/symbol paths being used for analysis of Windows coredumps

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13530/head:pull/13530` \
`$ git checkout pull/13530`

Update a local copy of the PR: \
`$ git checkout pull/13530` \
`$ git pull https://git.openjdk.org/jdk.git pull/13530/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13530`

View PR using the GUI difftool: \
`$ git pr show -t 13530`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13530.diff">https://git.openjdk.org/jdk/pull/13530.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13530#issuecomment-1514521531)

### CODE REVIEW

**Comment by plummercj** [comment]
Did you read the "Using transported core dumps on Windows" section of transported_core.html?

https://github.com/openjdk/jdk/blob/master/src/jdk.hotspot.agent/doc/transported_core.html#L70

I'd like to know if  you tried everything mentioned and still had issues. I reworked this section recently, but didn't have any first hand experience to go with. Just the old text and some input from those were using jhsdb with Windows.

It would be good if you could update this section to reflect your changes, and also add something regarding `sun.jvm.hotspot.debugger.windbg.imagePath` and `sun.jvm.hotspot.debugger.windbg.imagePath`, which I wasn't aware of when I recently updated this doc.

I understand your changes regarding looking relative to the executable name, but I don't understand how the following works. These are Windows services I'm not familiar with. Can you explain?

      // request Windows symbol table from remote server...
      symbols.append("srv*https://msdl.microsoft.com/download/symbols;");

**Comment by apavlyutkin** [comment]
This public Microsoft symbol server providing debug information for Windows binaries:

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-path#using-a-symbol-server-srv

**Comment by plummercj** [comment]
Are these symbols normally also stored locally, but may not work because they aren't the exact same version that was used on the host that produced the core file?

Would it work the user included "srv*https://msdl.microsoft.com/download/symbols;" in the `sun.jvm.hotspot.debugger.windbg.symbolPath`  property?

**Comment by apavlyutkin** [comment]
Double checked: the routine from https://github.com/openjdk/jdk/blob/master/src/jdk.hotspot.agent/doc/transported_core.html#L70 works fine if applied completely

**Pull request closed without merging**
