### PR TITLE
8325444: GHA: JDK-8325194 causes a regression

### PR DESCRIPTION
**Pull request by RealCLanger**
The [change](https://github.com/openjdk/jdk/commit/d1c82156ba6ede4b798ac15f935289cfcc99d1a0) for [JDK-8325194](https://bugs.openjdk.org/browse/JDK-8325194) broke get-jtreg because the way to determine the build jdk was not correct.

I then tried to use the bootstrap JDK with the correct wiring but it turned out that the build of JTReg fails with the current JDK, see [here](https://github.com/RealCLanger/jdk/actions/runs/7820130826/job/21334120478).

So I propose to fix it by going to the originally proposed solution using `$JAVA_HOME_17_<arch>`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325444](https://bugs.openjdk.org/browse/JDK-8325444): GHA: JDK-8325194 causes a regression (**Bug** - P3)

### Reviewers
 * [George Adams](https://openjdk.org/census#gdams) (@gdams - Author)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17756/head:pull/17756` \
`$ git checkout pull/17756`

Update a local copy of the PR: \
`$ git checkout pull/17756` \
`$ git pull https://git.openjdk.org/jdk.git pull/17756/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17756`

View PR using the GUI difftool: \
`$ git pr show -t 17756`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17756.diff">https://git.openjdk.org/jdk/pull/17756.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17756#issuecomment-1932768904)

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by magicus** [comment]
I don't like this approach. There must be better ways to achieve this, like inputting the correct value as input to the action, or setting it as a global gh variable. Where does even the `$JAVA_HOME_17_arm64` come from? Is it provided by GH? I don't recall setting variables with that weird case style in our GHA files.

**Comment by RealCLanger** [comment]
> I don't like this approach. There must be better ways to achieve this, like inputting the correct value as input to the action, or setting it as a global gh variable. Where does even the `$JAVA_HOME_17_arm64` come from? Is it provided by GH? I don't recall setting variables with that weird case style in our GHA files.

I think (as @gdams told me) these are paths to the Java installation in the Github Runners which happen to be there.

I agree, to avoid the if statement, we could properly set it as input to get-jtreg.

We probably could also use the setup-java action here - however, this will then lead to downloading another JDK, not sure if this is a performance concern.

**Comment by RealCLanger** [comment]
> > I don't like this approach. There must be better ways to achieve this, like inputting the correct value as input to the action, or setting it as a global gh variable. Where does even the `$JAVA_HOME_17_arm64` come from? Is it provided by GH? I don't recall setting variables with that weird case style in our GHA files.
> 
> I think (as @gdams told me) these are paths to the Java installation in the Github Runners which happen to be there.
> 
> I agree, to avoid the if statement, we could properly set it as input to get-jtreg.
> 
> We probably could also use the setup-java action here - however, this will then lead to downloading another JDK, not sure if this is a performance concern.

@magicus I looked a bit more into the alternatives. So, regarding using the correct value as input to the action, I actually don't see that it buys us anything. We'd have switch statements further up and maybe even more.

And as for setup-java, this also would only set up a `JAVA_HOME_{{ MAJOR_VERSION }}_{{ ARCHITECTURE }}` environment which we'd have to reference then. So no gain.

Unless you have some great other idea, I don't see how we could resolve this more elegantly.

**Comment by gdams** [comment]
Noting the discussion here: https://github.com/actions/runner-images/discussions/9266

GitHub are considering removing the architecture prefix

**Comment by RealCLanger** [comment]
OK, I'm ready to integrate. Waiting for blessing from @magicus.

**Review by magicus — APPROVED** [review]
Okay, whatever.

**Pull request closed without merging**
