### PR TITLE
8338139: {ClassLoading,Memory}MXBean::isVerbose methods are inconsistent with their setVerbose methods

### PR DESCRIPTION
**Pull request by stefank**
Hi all,

This pull request contains a backport of commit [9775d571](https://github.com/openjdk/jdk/commit/9775d57168695dc0d758e017fe5069d93d593f3e) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Stefan Karlsson on 20 Aug 2024 and was reviewed by Leonid Mesnik, Daniel D. Daugherty and David Holmes.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8338540](https://bugs.openjdk.org/browse/JDK-8338540) to be approved

### Issues
 * [JDK-8338139](https://bugs.openjdk.org/browse/JDK-8338139): {ClassLoading,Memory}MXBean::isVerbose methods are inconsistent with their setVerbose methods (**Bug** - P1)
 * [JDK-8338540](https://bugs.openjdk.org/browse/JDK-8338540): {ClassLoading,Memory}MXBean::isVerbose methods are inconsistent with their setVerbose methods (**CSR**)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20643/head:pull/20643` \
`$ git checkout pull/20643`

Update a local copy of the PR: \
`$ git checkout pull/20643` \
`$ git pull https://git.openjdk.org/jdk.git pull/20643/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20643`

View PR using the GUI difftool: \
`$ git pr show -t 20643`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20643.diff">https://git.openjdk.org/jdk/pull/20643.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20643#issuecomment-2298793703)

### CODE REVIEW

**Review by kevinjwalls — APPROVED** [review]
Backport looks good.

**Comment by stefank** [comment]
Thanks for the review
/integrate

**Review by dcubed-ojdk — COMMENTED** [review]
Thumbs up. Re-reviewed via GitHub and compared
the JDK24 patch file with the JDK23 patch file.

**Pull request closed without merging**
