### PR TITLE
8256618: Zero: Linux x86_32 build still fails

### PR DESCRIPTION
**Pull request by shipilev**
There is no os::workaround_expand_exec_shield_cs_limit symbol available:

```
/home/buildbot/worker/build-jdkX-linux/build/src/hotspot/os/linux/os_linux.cpp:4545: undefined reference to `os::workaround_expand_exec_shield_cs_limit()'
collect2: error: ld returned 1 exit status
```

That symbol is defined in `os_linux_x86.cpp`, which is not available to Zero that builds `os_linux_zero.cpp`.
[JDK-8248271](https://bugs.openjdk.java.net/browse/JDK-8248271) added the declaration to `os_linux_zero.hpp`, but that is not enough, because the definition is still missing. I propose we move the definition up the hierarchy, to `os_linux.cpp` and protect it firmly with `IA32`.

Additional testing:
 - [x] Linux {x86_32, x86_64} server builds
 - [x] Linux {x86_32, x86_64} zero builds

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ❌ (1/1 failed) | ❌ (1/1 failed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux arm (build hotspot no-pch)](https://github.com/shipilev/jdk/runs/1446907105)
- [Linux ppc64le (build hotspot no-pch)](https://github.com/shipilev/jdk/runs/1446907637)
- [Linux x86 (build debug)](https://github.com/shipilev/jdk/runs/1446687412)
- [Linux x86 (build release)](https://github.com/shipilev/jdk/runs/1446687395)

### Issue
 * [JDK-8256618](https://bugs.openjdk.java.net/browse/JDK-8256618): Zero: Linux x86_32 build still fails

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**) ⚠️ Review applies to c0bce3ff699e92abdac9b9d37166bbeadcb683b9
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1310/head:pull/1310`
`$ git checkout pull/1310`

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks @theRealAph! Anyone else wants to chime in?

**Comment by shipilev** [comment]
Did a minor touch-up, would appreciate another reviewer.

**Review by dholmes-ora — COMMENTED** [review]
I guess I'm somewhat surprised that Zero doesn't need anything that is in os_linux_x86.cpp when building for x86. It sets a bad precedent to move CPU specific code to shared code just because zero doesn't conform to the expected use of cpu specific code.
Does Zero actually need this code, or could we make the call conditional?
Thanks,
David

**Comment by shipilev** [comment]
> I guess I'm somewhat surprised that Zero doesn't need anything that is in os_linux_x86.cpp when building for x86. It sets a bad precedent to move CPU specific code to shared code just because zero doesn't conform to the expected use of cpu specific code.

The way current sources are structured, Zero is the "cpu" unto itself. See that we have `os_cpu/linux_x86` and `os_cpu/linux_zero`, `os/linux` and `os/zero`, etc. I agree it is awkward and have consequences like this patch; it has even more consequences for error handling that wants to do arch-specific decoding... 

That said, the current patch just moves the IA32 definition to `os_linux.cpp`, where the IA32 use already is, and this IMO makes it a tad more consistent than it was before.

> Does Zero actually need this code, or could we make the call conditional?

I think this code applies to all x86 variants. As the alternative, we can skip it for Zero, hoping that Zero x86 would never face a bug like this code tries to work around.

**Comment by theRealAph** [comment]
> 
> I think this code applies to all x86 variants. As the alternative, we can skip it for Zero, hoping that Zero x86 would never face a bug like this code tries to work around.

Well, if we assume Zero will never be used on x86, which seems reasonable, then it doesn't matter. But if it will be used, then there is a real problem with the invocation interface.

**Comment by tstuefe** [comment]
I don't think Zero x86 is widely built or tested so no-one may have noticed until now.

I prefer this to be fixed too. Why leave this unfixed if we can fix it.

If we do not want code duplication but putting it into os_linux.cpp is an eyesore, I'd suggest to move it into an own implementation file, e.g. "os/linux/x86_exec_shield_workaround.cpp", with a clear comment that this is needed for zero. Still ugly but at least not hidden away, and if w

**Comment by shipilev** [comment]
Zero had suffered from years of neglect, and I believe the last time anyone tried to build Zero x86_32 was when Gary Benson did significant work on in back in 2009. The workaround for IA32 landed in 2013. So it stands to reason Zero x86_32 was broken since. In fact, even after this workaround, I see the Zero-specific IA32_ONLY assertions on Hello World.

Zero x86_32 seems to be the only Zero config that fails to build at the moment. So, at this point I am willing to make a concession and just disable the workaround for Zero to get it to build. If we discover the workaround is needed, then we can revisit how Zero uses `os_linux_*` code.

That is what new commit does.

**Review by tstuefe — APPROVED** [review]
Pity but LGTM.

I assume you build zero with a non-zero build VM right? Due to horrific build times? So it does not need to come up to get built.

**Comment by shipilev** [comment]
> I assume you build zero with a non-zero build VM right? Due to horrific build times? So it does not need to come up to get built.

Linux x86_32 bits -- yes, they are effectively cross-compiled, so we first compile Linux x86_64 server (technically, my CI as well as GH actions reuse that binary from the dependent jobs), and then use it as build JDK during Linux x86_32 Zero compilation. `make bootcycle-images` is the go-to test to verify Zero works, as it uses the Zero binary as buildjdk on the second pass. The bootcycle times are bad, but not horrible after all the work I did over the last few weeks ;)

**Review by dholmes-ora — APPROVED** [review]

**Comment by shipilev** [comment]
Okay then, let's go with this.

/integrate

**Pull request closed without merging**
