### PR TITLE
8319883: Zero: Use atomic built-ins for 64-bit accesses

### PR DESCRIPTION
**Pull request by shipilev**
See the bug for reproducer and discussion.

This reimplements related Zero parts using `__atomic_*`: we already use some of those both in Atomic and around Hotspot code. As far as I can see from both GCC and LLVM docs, these would be translated to proper accesses on all target platforms. Doing even the relaxed atomic access for 64-bit platforms is probably an overkill, but for Zero we want baseline correctness first and foremost.

Example current uses of `__atomic_load` on both BSD (I think it assumes clang) and Linux (assumes GCC):
https://github.com/openjdk/jdk/blob/a64fc48e2dbc650b31869dd79b1ba1012376fc51/src/hotspot/os_cpu/bsd_aarch64/atomic_bsd_aarch64.hpp#L115
https://github.com/openjdk/jdk/blob/a64fc48e2dbc650b31869dd79b1ba1012376fc51/src/hotspot/os_cpu/linux_aarch64/atomic_linux_aarch64.hpp#L203
https://github.com/openjdk/jdk/blob/a64fc48e2dbc650b31869dd79b1ba1012376fc51/src/hotspot/os_cpu/linux_riscv/atomic_linux_riscv.hpp#L172

Additional testing:
 - [x] MacOS AArch64 Zero fastdebug; light jcstress tests still pass
 - [x] Linux x86_32 Zero release; previously failing jcstress testing now passes
 - [x] Linux x86_32 Zero fastdebug, `compiler/unsafe java/lang/invoke/VarHandles`
 - [x] Linux x86_32 Zero fastdebug, bootcycle-images

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319883](https://bugs.openjdk.org/browse/JDK-8319883): Zero: Use atomic built-ins for 64-bit accesses (**Bug** - P3)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16600/head:pull/16600` \
`$ git checkout pull/16600`

Update a local copy of the PR: \
`$ git checkout pull/16600` \
`$ git pull https://git.openjdk.org/jdk.git pull/16600/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16600`

View PR using the GUI difftool: \
`$ git pr show -t 16600`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16600.diff">https://git.openjdk.org/jdk/pull/16600.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16600#issuecomment-1805823268)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable. Can I assume that the correct volatile access memory semantics are handled at a higher-level?

Thanks

**Comment by shipilev** [comment]
> Seems reasonable. Can I assume that the correct volatile access memory semantics are handled at a higher-level?

Yes, `Platform(Load|Store)` is about the relaxed accesses. The generic atomic code wraps these in `ScopedFence` that emits `OrderAccess` fences around the access, if stronger semantics is needed. As the follow-up, we might consider specializing `PlatformOrdered(Load|Store)` for Zero to avoid using fences, but it does not look necessary at the moment.

**Comment by shipilev** [comment]
Thanks for review, @dholmes-ora! I think this formally requires another Reviewer, but I am not sure who else is maintaining Zero these days. Maybe @phohensee or @tstuefe can formally ack this.

**Review by kimbarrett — APPROVED** [review]
Looks good.  IWBN to get zero test results before integrating.

**Review by tstuefe — APPROVED** [review]
Looks good.

**Comment by shipilev** [comment]
> Looks good. IWBN to get zero test results before integrating.

Thanks! I already did lots of tests for Linux x86_32 Zero, including full jcstress runs, see "Additional testing" section. I think it is enough for this work to go forward. There are other Zero fixes in pipeline that need to land before we can fully test all combinations of Zero arches.

**Comment by shipilev** [comment]
Integrating to unblock other Zero bugfixing work.

/integrate

**Pull request closed without merging**
