### PR TITLE
8320697: RISC-V: Small refactoring for runtime calls

### PR DESCRIPTION
**Pull request by feilongjiang**
Hi, please review this refactoring for runtime calls.
Major changes:
1. Unified the runtime calls with the existing MacroAssembler::rt_call. This will remove the duplicate code like `relocate(target.rspec() [&] {...}` to emit uncompressed instructions.
2. Removed MacroAssembler::far_branches and made the call sites default to far branches. `branch_range` is 1MB for riscv, and `ReservedCodeCacheSize` will always bigger than `branch_range` in practice. We should remove this unnecessary check and simplify the code logic.
3. Renamed MacroAssembler::la_patchable with MacroAssembler::la making it less confusing.
4. `far_call` in `rt_call` should use `tmp` instead of the default temporary register `t0`
5. Removed some unused codes in `g1BarrierSetAssembler_riscv.cpp`

Testing:
- [x] Tier1-3 tested on hifive unmatched board (release)
- [x] Run non-trivial benchmark workloads (fastdebug)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320697](https://bugs.openjdk.org/browse/JDK-8320697): RISC-V: Small refactoring for runtime calls (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [4e60351f](https://git.openjdk.org/jdk/pull/16816/files/4e60351ff25677cc16f3413496aae68d50c783a3)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**) ⚠️ Review applies to [81347a99](https://git.openjdk.org/jdk/pull/16816/files/81347a993c7057f58a491bca72b6b5553cc64293)

### Contributors
 * Fei Yang `<fyang@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16816/head:pull/16816` \
`$ git checkout pull/16816`

Update a local copy of the PR: \
`$ git checkout pull/16816` \
`$ git pull https://git.openjdk.org/jdk.git pull/16816/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16816`

View PR using the GUI difftool: \
`$ git pr show -t 16816`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16816.diff">https://git.openjdk.org/jdk/pull/16816.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16816#issuecomment-1827043683)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks fine. Happy to see that `MacroAssembler::far_branches` removed and code logic simplied. In fact, the JVM won't start when ReservedCodeCacheSize is less than 2496K.

**Comment by robehn** [comment]
`Renamed MacroAssembler::la_patchable with MacroAssembler::auipc making it explicit that this will emit pc-relative addressing code.`

First, above is not true, as it may emit movptr, it's now an implicit movptr instead. When you thought you were getting auipc.
Secondly auipc is not a mnemonic AFAIK, it means just the instruction auipc. Having it as both is confusing.
Third the one version is now called "la" while the other one is called "auipc" ?

Sorry, but this part is worse now in IMHO.

**Comment by RealFYang** [comment]
> `Renamed MacroAssembler::la_patchable with MacroAssembler::auipc making it explicit that this will emit pc-relative addressing code.`
> 
> First, above is not true, as it may emit movptr, it's now an implicit movptr instead. When you thought you were getting auipc. Secondly auipc is not a mnemonic AFAIK, it means just the instruction auipc. Having it as both is confusing. Third the one version is now called "la" while the other one is called "auipc" ?
> 
> Sorry, but this part is worse now in IMHO.

Yeah, I also see that too :-) I guess the intention is trying to mapping to the aarch64 counterpart MacroAssembler::adrp [1]. 
I did some history searching and seems that the else block is there only to handle some corner cases [2]. 
We might want find a better name for this function but seems not easy to do :-(

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp#L4968
[2] https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2015-November/019895.html

**Comment by robehn** [comment]
> > `Renamed MacroAssembler::la_patchable with MacroAssembler::auipc making it explicit that this will emit pc-relative addressing code.`
> > First, above is not true, as it may emit movptr, it's now an implicit movptr instead. When you thought you were getting auipc. Secondly auipc is not a mnemonic AFAIK, it means just the instruction auipc. Having it as both is confusing. Third the one version is now called "la" while the other one is called "auipc" ?
> > Sorry, but this part is worse now in IMHO.
> 
> Yeah, I see that too :-) I guess the intention is to try to map to the aarch64 counterpart MacroAssembler::adrp [1]. I did some history searching and seems that the else block is there only to handle some corner cases [2]. We might want to find a better name for this function but seems not easy to do :-(
> 
> [1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp#L4968 [2] https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2015-November/019895.html

I think there is an underlying issue with the whole design with masm/asm.
As there is no clear separation between "I want this to happen" and "I want to emit this instruction".
I think methods which have identical name as an instruction should indicate "I want to emit this instruction".

**Comment by feilongjiang** [comment]
> > `Renamed MacroAssembler::la_patchable with MacroAssembler::auipc making it explicit that this will emit pc-relative addressing code.`
> 
> > 
> 
> > First, above is not true, as it may emit movptr, it's now an implicit movptr instead. When you thought you were getting auipc. Secondly auipc is not a mnemonic AFAIK, it means just the instruction auipc. Having it as both is confusing. Third the one version is now called "la" while the other one is called "auipc" ?
> 
> > 
> 
> > Sorry, but this part is worse now in IMHO.
> 
> 
> 
> Yeah, I see that too :-) I guess the intention is to try to map to the aarch64 counterpart MacroAssembler::adrp [1]. 
> 
> I did some history searching and seems that the else block is there only to handle some corner cases [2]. 
> 
> We might want to find a better name for this function but seems not easy to do :-(
> 
> 
> 
> [1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp#L4968
> 
> [2] https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2015-November/019895.html

Thanks fei.
Yes, that's also part of the reason why I rename this function to the new name auipc. The other consideration which I didn't mention is that the old name la_patchable is kind of confusing because we also have other la function which are also pachable too like MacroAssembler::la [1].

I am happy if we can find a better name, suggestions are welcomed.

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L730

**Comment by feilongjiang** [comment]
> I think there is an underlying issue with the whole design with masm/asm. As there is no clear separation between "I want this to happen" and "I want to emit this instruction". I think methods which have identical name as an instruction should indicate "I want to emit this instruction".

Agreed. I can revert the renaming of `auipc` and keep the other parts. IMHO, `la_patchable` is not good enough though. So maybe we could do more refactoring on `la_patchable`, but this should be done in another pr.

**Comment by RealFYang** [comment]
> I think there is an underlying issue with the whole design with masm/asm. As there is no clear separation between "I want this to happen" and "I want to emit this instruction". I think methods which have identical name as an instruction should indicate "I want to emit this instruction".

Do we have any other occurences except for the case here? I am supposing the `auipc` in this change would be the only one which bears such an issue. No?

**Comment by theRealAph** [comment]
> I think there is an underlying issue with the whole design with masm/asm. As there is no clear separation between "I want this to happen" and "I want to emit this instruction". I think methods which have identical name as an instruction should indicate "I want to emit this instruction".

I can see the logic behind that, but certain CPU designers write things like "A "programmer-friendly" assembler may accept a negative immediate between -(2^24 -1) and -1 inclusive, causing it to convert a requested ADD operation to a SUB, or vice versa, and then encode the absolute value of the immediate as for uimm24." So I think maybe that bird has already flown...

**Comment by robehn** [comment]
> > I think there is an underlying issue with the whole design with masm/asm. As there is no clear separation between "I want this to happen" and "I want to emit this instruction". I think methods which have identical name as an instruction should indicate "I want to emit this instruction".
> 
> I can see the logic behind that, but certain CPU designers write things like "A "programmer-friendly" assembler may accept a negative immediate between -(2^24 -1) and -1 inclusive, causing it to convert a requested ADD operation to a SUB, or vice versa, and then encode the absolute value of the immediate as for uimm24." So I think maybe that bird has already flown...

Yes. I think this case is extra confusing as you ask for one instruction for a materializing a pc relative value.
But you can get several instruction loading an absolute value.

If this is okey, the programmer never want a pc relative value, he just wanted that value.
Therefore I think using the name auipc is a bit sub-optimal to tell this story.

**Comment by RealFYang** [comment]
Another way which I think might resolve our concerns is to simply rename `la_patchable` as `la` and overload
existing three `la` assembler functions [1][2][3].

In fact, this `la_patchable` is very similar to the existing `MacroAssembler::la(Register Rd, const address addr)` [1].
The only difference is that `la_patchable` will do some distance checks based on high/low bound of code cache and return
a displacement through its third reference parameter `offset` for the succeeding addi/jalr/ld/st instructions.
While `la` [1] is mainly used by `la`[2] for loading address of an label which is more simpler compared with `la_patchable`.
At the same time, I think `la_patchable` should receive a `address` instead of `Address` since it's always expecting a
literal address. This will also help distinguish with `la`[3] which receives an `Address`.

So the replacement for `la_patchable` looks like `void MacroAssembler::la(Register Rd, const address addr, int32_t &offset)`
And I have tried following add-on change and it seems to work.
[16816-addon.diff.txt](https://github.com/openjdk/jdk/files/13509737/16816-addon.diff.txt)


[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L720
[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L755
[3] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L730

**Comment by robehn** [comment]
> Another way which I think might resolve our concerns is to simply rename `la_patchable` as `la` and overload the existing three `la` assembler functions [1][2][3].

I like this a lot more, thanks!

All onboard ? :)

**Comment by feilongjiang** [comment]
> Another way which I think might resolve our concerns is to simply rename `la_patchable` as `la` and overload the existing three `la` assembler functions [1][2][3].
> So the replacement for `la_patchable` looks like `void MacroAssembler::la(Register Rd, const address addr, int32_t &offset)`

Thanks! It looks much cleaner and clearer.  I will apply your patch later.

**Comment by feilongjiang** [comment]
Applied Fei's patch.
/contributor add @RealFYang

**Review by robehn — APPROVED** [review]
Thank you, looks good! (not a line for line review)

You have some unrelated changes in g1BarrierSet, I don't mind, but pointing that out for the record.

**Comment by feilongjiang** [comment]
> You have some unrelated changes in g1BarrierSet, I don't mind, but pointing that out for the record.

Thanks for the reminder, I've updated the description.

**Comment by robehn** [comment]
Hey!

I notice this:
```
  static int far_branch_size() {   
    if (far_branches()) {                                          
      return 2 * 4;  // auipc + jalr, see far_call() & far_jump()
```

Which is used to determine deopt handler size.

I don't understand how we ever may use movptr here instead with knowing who is calling?

I think we want two methods here one with fixed size ?

**Comment by feilongjiang** [comment]
> I don't understand how we ever may use movptr here instead without knowing who is calling?
> 
> I think we want two methods here one with fixed size ?
I'm not sure if I understand it correctly. Do you mean we should use `movptr` to get fixed instruction size instead of `la_patchbale`?

**Comment by robehn** [comment]
> > I don't understand how we ever may use movptr here instead without knowing who is calling?
> > I think we want two methods here one with fixed size ?
> 
> Hi @robehn, I'm not sure if I understand it correctly. Do you mean we should use `movptr` to get fixed instruction size instead of `la_patchable`?

https://bugs.openjdk.org/browse/JDK-8321315

Let's take here, this PR is good!

**Pull request closed without merging**
