### PR TITLE
JDK-8307520: set minimum supported CPU architecture to Power8 on AIX

### PR DESCRIPTION
**Pull request by JoKern65**
In the compile flags, set the minimum supported CPU architecture to Power8 on AIX, because we do not want to support pwr7 architecture any more.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307520](https://bugs.openjdk.org/browse/JDK-8307520): set minimum supported CPU architecture to Power8 on AIX

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13933/head:pull/13933` \
`$ git checkout pull/13933`

Update a local copy of the PR: \
`$ git checkout pull/13933` \
`$ git pull https://git.openjdk.org/jdk.git pull/13933/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13933`

View PR using the GUI difftool: \
`$ git pr show -t 13933`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13933.diff">https://git.openjdk.org/jdk/pull/13933.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13933#issuecomment-1544038720)

### CODE REVIEW

**Comment by JoKern65** [comment]
Now Pwr8 should be the minimum hardware on AIX to run jdk

**Review by MBaesken — APPROVED** [review]
LGTM

I would recommend to enable the PR also for our nightly makes to check the flag in the build logs.

**Pull request closed without merging**
