### PR TITLE
8253029: [PPC64] Remove obsolete Power6 code

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
New pull request:
Using a branch, updated Copyright, removed some more unused code.

[Previous text]
The recent PPC64 platform files still contain code which is part of a Power6 optimization called Power6Scheduler. However, this functionality was never completely contributed so it was never usable in the OpenJDK.
We should remove it since we're no longer optimizing for Power6.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253029](https://bugs.openjdk.java.net/browse/JDK-8253029): [PPC64] Remove obsolete Power6 code

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/127/head:pull/127`
`$ git checkout pull/127`

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Code changes seem fine.

**Review by RealLucy — APPROVED** [review]

**Comment by RealLucy** [comment]
Hi Martin, 
your changes look good to me. 
Thanks for the tedious comments removal! Not a task you been for. 
Best,
Lutz

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews.

**Pull request closed without merging**
