### PR TITLE
8329636: Deprecate -XX:+PreserveAllAnnotations

### PR DESCRIPTION
**Pull request by alexmenkov**
Tested
  - tier1-3;
  - test/jdk/java/lang/instrument/RetransformRecordAnnotation.java (the only test that uses the option)

CSR needs review as well

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8329808](https://bugs.openjdk.org/browse/JDK-8329808) to be approved

### Issues
 * [JDK-8329636](https://bugs.openjdk.org/browse/JDK-8329636): Deprecate -XX:+PreserveAllAnnotations (**Enhancement** - P4)
 * [JDK-8329808](https://bugs.openjdk.org/browse/JDK-8329808): Deprecate -XX:+PreserveAllAnnotations (**CSR**)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18680/head:pull/18680` \
`$ git checkout pull/18680`

Update a local copy of the PR: \
`$ git checkout pull/18680` \
`$ git pull https://git.openjdk.org/jdk.git pull/18680/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18680`

View PR using the GUI difftool: \
`$ git pr show -t 18680`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18680.diff">https://git.openjdk.org/jdk/pull/18680.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18680#issuecomment-2043936204)

### CODE REVIEW

**Review by coleenp — CHANGES_REQUESTED** [review]
There's a test that this option should be added to in VMDeprecatedOptions.java.

**Review by coleenp — APPROVED** [review]
Looks good.  Now to see if there's any objection in the CSR.

**Review by dholmes-ora — APPROVED** [review]
Code changes are good - assuming CSR proceeds.

Thanks

**Comment by alexmenkov** [comment]
Coleen, David, thank you for the review.
The CSR is approved.
/integrate

**Pull request closed without merging**
