### PR TITLE
8284956: Potential leak awtImageData/color_data when initializes X11GraphicsEnvironment

### PR DESCRIPTION
**Pull request by zhengyu123**
During initializing native data of `X11GraphicsEnvironment`, a single `AwtGraphicsConfigData` is used/reused, not only failed cases, but also succeeded cases. So `AwtGraphicsConfigData` internal states need to be cleanup properly to avoid memory leaks.

Test:
- [x] jdk_awt

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 reviewer, 1 author)

### Issue
 * [JDK-8284956](https://bugs.openjdk.java.net/browse/JDK-8284956): Potential leak awtImageData/color_data when initializes X11GraphicsEnvironment

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to [e6838cf0](https://git.openjdk.java.net/jdk/pull/8317/files/e6838cf02d97da767b0bb95b1237d422bf4ae48b)
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8317/head:pull/8317` \
`$ git checkout pull/8317`

Update a local copy of the PR: \
`$ git checkout pull/8317` \
`$ git pull https://git.openjdk.java.net/jdk pull/8317/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8317`

View PR using the GUI difftool: \
`$ git pr show -t 8317`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8317.diff">https://git.openjdk.java.net/jdk/pull/8317.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]

**Review by shipilev — COMMENTED** [review]
What about `_ColorData::img_grays`, `_ColorData::awt_Colors`, `_ColorData::img_oda_*`?

**Review by gnu-andrew — COMMENTED** [review]
I see `calloc` calls also for `img_grays` and `awt_Colors`. Is there a reason these aren't freed too?

**Comment by zhengyu123** [comment]
> What about `_ColorData::img_grays`, `_ColorData::awt_Colors`, `_ColorData::img_oda_*`?

`_ColorData::img_oda_*` are not malloc'd

```
 awt_data->color_data->img_oda_red   = &(std_img_oda_red[0][0]);
 awt_data->color_data->img_oda_green = &(std_img_oda_green[0][0]);
 awt_data->color_data->img_oda_blue  = &(std_img_oda_blue[0][0]);
```
and `std_img_oda_*` are defined as 
```
JNIEXPORT extern sgn_ordered_dither_array std_img_oda_red;
JNIEXPORT extern sgn_ordered_dither_array std_img_oda_green;
JNIEXPORT extern sgn_ordered_dither_array std_img_oda_blue;
```

**Review by shipilev — APPROVED** [review]

**Comment by zhengyu123** [comment]
Thanks for the reviews, @prrace @shipilev  and @gnu-andrew

**Pull request closed without merging**
