### PR TITLE
8297657: name demangling intermittently fails

### PR DESCRIPTION
**Pull request by fbredber**
Fixes an intermittent name demangling problem (due to the uninitialized AbstractDecoder::_decoder_status field).
The problem affected hs-err stack traces on macosx-aarch64 and macosx-amd64.

I've done manual testing to verify the problem and the solution.
Also run tier1-5 after the fix without seeing any new problems.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297657](https://bugs.openjdk.org/browse/JDK-8297657): name demangling intermittently fails

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13883/head:pull/13883` \
`$ git checkout pull/13883`

Update a local copy of the PR: \
`$ git checkout pull/13883` \
`$ git pull https://git.openjdk.org/jdk.git pull/13883/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13883`

View PR using the GUI difftool: \
`$ git pr show -t 13883`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13883.diff">https://git.openjdk.org/jdk/pull/13883.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13883#issuecomment-1540051976)

### CODE REVIEW

**Review by stefank — COMMENTED** [review]
It looks like this bug could have been prevented if AbstractDecoder had a constructor that initialized _decoder_status with the value passed down from the sub-class. Maybe this RFE could be an opportunity to improve this?

**Review by stefank — APPROVED** [review]

**Review by coleenp — APPROVED** [review]
Yes this looks good.  I didn't see the not_available initialization so passing the initial status is right.

**Comment by fbredber** [comment]
Thanks for the review and comments. Can any of you give me a helping hand (and sponsor) the integration?

**Pull request closed without merging**
