### PR TITLE
8343555: RISC-V: make some verified (on hardware) extension options diagnostic

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this simple patch?
Previously this UseZvfh was changed from experimental to product because we have real hardware to verify the feature, but as pointed out by @RealFYang , this one should ber a diagnostic option, as we don't want to expose too many options to users.
Thanks

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343555](https://bugs.openjdk.org/browse/JDK-8343555): RISC-V: make some verified (on hardware) extension options diagnostic (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21885/head:pull/21885` \
`$ git checkout pull/21885`

Update a local copy of the PR: \
`$ git checkout pull/21885` \
`$ git pull https://git.openjdk.org/jdk.git pull/21885/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21885`

View PR using the GUI difftool: \
`$ git pr show -t 21885`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21885.diff">https://git.openjdk.org/jdk/pull/21885.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21885#issuecomment-2455437756)
</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Thanks. That make sense to me. Since we are having more and more RISC-V extensions, we should rely on linux hwprobe syscall for auto detection and enablement of these extensions in the long run. Seems that we should also similarly handle other ones like `UseRVC`, `UseRVV`, etc.

**Comment by robehn** [comment]
Do it really makes sense to have instruction set selection diagnostic:
https://github.com/openjdk/jdk/blob/dafa2e55adb6b054c342d5e723e51087d771e6d6/src/hotspot/share/runtime/globals.hpp#L59

?

**Comment by Hamlin-Li** [comment]
> Do it really makes sense to have instruction set selection diagnostic:

Do you suggest to keep it as Product or Experimental?

The full sentences are as below:
```
// DIAGNOSTIC options are not meant for VM tuning or for product modes.
//    They are to be used for VM quality assurance or field diagnosis
//    of VM bugs.  They are hidden so that users will not be encouraged to
//    try them as if they were VM ordinary execution options.  However, they
//    are available in the product version of the VM.  Under instruction
//    from support engineers, VM customers can turn them on to collect
//    diagnostic information about VM problems.
```

I think it should not be Experimental anymore, and seems it's better than Product, and can be used in product (`However, they are available in the product version of the VM`). But I'm not quite sure.

**Comment by RealFYang** [comment]
> Do it really makes sense to have instruction set selection diagnostic:

This was once discussed somewhere else before. Again, here is what I am thinking. First of all, we might don't want to expose these options for our end users. You need to add to the release note for newly-added product options. There are quite a few for now and I suppose there will be more and more to come. So it's more reasonable to me to delegate to hwprobe. But if we do that, we still need a way to diagnostic or disable them when issues come (whether performance or functionality related). I don't see a better solution than making them DIAGNOSTIC ones.

**Comment by robehn** [comment]
Now we have normal and exprimental. Changing this one we would have also diagnostic.
And some we get from hwprobe and some not, it's not easy to know which ones to manually turn on, etc...
Wouldn't it make more sense to turn all options which may be enabled hwprobe to diagnostic instead?

**Comment by Hamlin-Li** [comment]
@robehn @RealFYang I guess you two have similar opinion now? but I could be wrong.
Are you suggesting to turn all the Product options (retrieved by hwprobe) to DIAGNOSTIC?

I won't suggest to turn any EXPERIMENTAL to DIAGNOSTIC in this pr, as we need to test it on real hardware first, but if you've tested some of them on real hardware please let me know, I'll do it in this pr.

**Comment by RealFYang** [comment]
> @robehn @RealFYang I guess you two have similar opinion now? but I could be wrong. Are you suggesting to turn all the Product options (retrieved by hwprobe) to DIAGNOSTIC?
> 
> I won't suggest to turn any EXPERIMENTAL to DIAGNOSTIC in this pr, as we need to test it on real hardware first, but if you've tested some of them on real hardware please let me know, I'll do it in this pr.

My personal opinion is that we can make following ones DIAGNOSTIC as well as they have been tested on real hardwares. I agree with you to leave the other EXPERIMENTAL ones as they are. We can turn them DIAGNOSTIC too in the future when the hardware is available.

```
  product(bool, UseRVC, false, "Use RVC instructions")                           \
  product(bool, UseRVV, false, "Use RVV instructions")                           \
  product(bool, UseZba, false, "Use Zba instructions")                           \
  product(bool, UseZbb, false, "Use Zbb instructions")                           \
  product(bool, UseZbs, false, "Use Zbs instructions")                           \
  product(bool, UseZfh, false, "Use Zfh instructions")
```

**Comment by robehn** [comment]
Ok, so the path is:
1: Exprimental (should they be turn on by hwprobe?)
2a: If hwprobe    => Diagnostic
2b: No hwprobe => Normal

Arguably hwprobe should only turn on diagnostic options then ?

**Comment by RealFYang** [comment]
We don't auto-enable Exprimental options through hwprobe until they are fully tested on real hardwares. That's what we do for now.

**Comment by Hamlin-Li** [comment]
Hey, so what's the conclusion for now?

I'm fine with @RealFYang 's proposal above, how do you think? @robehn 
```
  product(bool, UseRVC, false, "Use RVC instructions")                           \
  product(bool, UseRVV, false, "Use RVV instructions")                           \
  product(bool, UseZba, false, "Use Zba instructions")                           \
  product(bool, UseZbb, false, "Use Zbb instructions")                           \
  product(bool, UseZbs, false, "Use Zbs instructions")                           \
  product(bool, UseZfh, false, "Use Zfh instructions")
```

**Comment by robehn** [comment]
Yes, I'm fine with that. Just so we try to keep somekind of common thread.

**Comment by Hamlin-Li** [comment]
@robehn Thanks for the confirmation, updated accordingly.

**Comment by RealFYang** [comment]
Please also update the JBS title to reflect the latest version, as we are targeting more options than UseZvfh.

**Comment by Hamlin-Li** [comment]
> Please also update the JBS title to reflect the latest version, as we are targeting more options than a single UseZvfh.

Thanks, modified.

**Review by RealFYang — APPROVED** [review]
LGTM. Thanks.

**Comment by Hamlin-Li** [comment]
Thanks for your reviews!

/integrate

**Pull request closed without merging**
