### PR TITLE
8258652: Assert in JvmtiThreadState::cur_stack_depth() can noticeably slow down debugging single stepping

### PR DESCRIPTION
**Pull request by plummercj**
There is an assert in `JvmtiThreadState::cur_stack_depth()` that tends to slow down single stepping a lot when running the debuggee with a debug jvm. See CR for details. The fix is to allow disabling of this assert using the new EnableJVMTIStackDepthAsserts global, which defaults to true.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258652](https://bugs.openjdk.java.net/browse/JDK-8258652): Assert in JvmtiThreadState::cur_stack_depth() can noticeably slow down debugging single stepping

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Alex Menkov](https://openjdk.java.net/census#amenkov) (@alexmenkov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1835/head:pull/1835`
`$ git checkout pull/1835`

### CODE REVIEW

**Comment by dholmes-ora** [comment]
This works but I'm concerned if this sets a precedent for adding expensive assertions? Do we already have similar flags?

**Comment by plummercj** [comment]
> This works but I'm concerned if this sets a precedent for adding expensive assertions? Do we already have similar flags?

The one expensive assert is already there. I have since removed the two additional expensive asserts for the incr() and decr() APIs. I don't know of any other similar flag.

**Comment by plummercj** [comment]
Ping! Still need 2 reviews for this one too.

**Review by sspitsyn — APPROVED** [review]
LGTM
Thanks,
Serguei

**Review by dholmes-ora — APPROVED** [review]
LGTM.

Thanks,
David

**Review by alexmenkov — APPROVED** [review]

**Pull request closed without merging**
