### PR TITLE
8278016: Add compiler tests to tier{2,3}

### PR DESCRIPTION
**Pull request by shipilev**
I have been looking at `hotspot:tier4` (catch-all not in lower tiers) run logs, and realized the whole bunch of compiler tests are running there.

Since `hotspot:tier4` runs a lot of `vmTestbase` tests, contributors seldom run it, as it takes many hours. Which means that many compiler tests are not running regularly for many contributors. But these tests are rather fast themselves and cover important compiler features.

We can properly add compiler tests to `tier{2,3}` to expose them on earlier tiers. The split logic between tiers is roughly: fast feature tests go into tier2, slower feature tests and debugging/printing stuff goes to tier3.

Sample times for new subgroups (think about this as "How much time they add to existing tiers"):

```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg:tier2_compiler             243   243     0     0   
==============================

real	2m16.518s
user	35m40.839s
sys	1m35.334s

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg:tier3_compiler             132   132     0     0   
==============================

real	4m31.935s
user	71m54.617s
sys	2m13.073s
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278016](https://bugs.openjdk.java.net/browse/JDK-8278016): Add compiler tests to tier{2,3}

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6622/head:pull/6622` \
`$ git checkout pull/6622`

Update a local copy of the PR: \
`$ git checkout pull/6622` \
`$ git pull https://git.openjdk.java.net/jdk pull/6622/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6622`

View PR using the GUI difftool: \
`$ git pr show -t 6622`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6622.diff">https://git.openjdk.java.net/jdk/pull/6622.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good to me.

**Comment by dholmes-ora** [comment]
@shipilev again I think we need to examine this in terms of impact to our CI. We run different platforms and configurations in different tiers so the costs are not as simple as looking at one run.

Thanks,
David

**Comment by shipilev** [comment]
> @shipilev again I think we need to examine this in terms of impact to our CI. We run different platforms and configurations in different tiers so the costs are not as simple as looking at one run.

Again, I can wait for those who have more insight in Oracle testing pipelines check their workflows with this change. I have no insight in Oracle infra, so somebody else have to do it. Now that Igor left, who should we be talking to?

**Comment by vnkozlov** [comment]
> > @shipilev again I think we need to examine this in terms of impact to our CI. We run different platforms and configurations in different tiers so the costs are not as simple as looking at one run.
> 
> Again, I can wait for those who have more insight in Oracle testing pipelines check their workflows with this change. I have no insight in Oracle infra, so somebody else have to do it. Now that Igor left, who should we be talking to?

@dholmes-ora  I checked and this change does not interfere with our CI. `tier2` and `tier3` introduced by #5241 are not used by our CI. New `tier2_compiler` and `tier3_compiler` groups are also not used. We use different sets in CI. I am not sure how else it can affect our testing.

I also submitted our testing. I will let you know results.

**Comment by dholmes-ora** [comment]
@vnkozlov thanks for that! I didn't realize the HS testing was so isolated from the jtreg group definitions.

Thanks for your patience @shipilev .

**Review by dholmes-ora — APPROVED** [review]

**Comment by vnkozlov** [comment]
I don't see issues with these changes in my testing. I submitted our tier1,2,3 testing in internal infra.

**Comment by shipilev** [comment]
> I don't see issues with these changes in my testing. I submitted our tier1,2,3 testing in internal infra.

Vladimir, are internal infra results good?

**Comment by vnkozlov** [comment]
Yes, all passed. You can integrate.

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
