### PR TITLE
8296912: C2: CreateExNode::Identity fails with assert(i < _max) failed: oob: i=1, _max=1

### PR DESCRIPTION
**Pull request by TobiHartmann**
The fix for [JDK-8284358](https://bugs.openjdk.org/browse/JDK-8284358) added code that aggressively removes dead subgraphs when detecting an unreachable Region by walking up the CFG and replacing all nodes by top (because they must be unreachable as well). In this case, we detect that `280 Region` is unreachable from root and replace `276 Catch` by top while walking up the CFG:

Screenshot from 2022-11-16 12-53-56

Code in `CreateExNode::Identity` does not expect `292 CatchProj` to have a top input when processing `305 CreateEx`. The fix is to simply add a `in(0)->in(0)->is_Catch()` check.

Thanks,
Tobias

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296912](https://bugs.openjdk.org/browse/JDK-8296912): C2: CreateExNode::Identity fails with assert(i < _max) failed: oob: i=1, _max=1

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11181/head:pull/11181` \
`$ git checkout pull/11181`

Update a local copy of the PR: \
`$ git checkout pull/11181` \
`$ git pull https://git.openjdk.org/jdk pull/11181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11181`

View PR using the GUI difftool: \
`$ git pr show -t 11181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11181.diff">https://git.openjdk.org/jdk/pull/11181.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks for the quick review, Christian!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by TobiHartmann** [comment]
Thanks for the review, Vladimir!

**Pull request closed without merging**
