### PR TITLE
8307860: [BACKOUT] JDK-8307194 Add make target for optionally building a complete set of all JDK and hotspot libjvm static libraries

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit 1964954da9ac1d020e0b5ba35893f475d86ec909.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307860](https://bugs.openjdk.org/browse/JDK-8307860): [BACKOUT] JDK-8307194 Add make target for optionally building a complete set of all JDK and hotspot libjvm static libraries

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13918/head:pull/13918` \
`$ git checkout pull/13918`

Update a local copy of the PR: \
`$ git checkout pull/13918` \
`$ git pull https://git.openjdk.org/jdk.git pull/13918/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13918`

View PR using the GUI difftool: \
`$ git pr show -t 13918`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13918.diff">https://git.openjdk.org/jdk/pull/13918.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13918#issuecomment-1542796115)

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
This [BACKOUT] is being tested with a Mach5 Tier1 job set. All build tasks except for
macosx-x64-debug have run and PASSED at this point.

**Review by erikj79 — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@erikj79 - Thanks for the review! I'm still waiting for the macosx-x64-debug build to finish.
The workdir logs show that the build is chugging along...

**Comment by dcubed-ojdk** [comment]
All builds have passed.

/integrate

**Comment by jianglizhou** [comment]
Thank you, @dcubed-ojdk!

**Pull request closed without merging**
