### PR TITLE
8323651: compiler/c2/irTests/TestPrunedExHandler.java fails with -XX:+DeoptimizeALot

### PR DESCRIPTION
**Pull request by JornVernee**
This test can not work with `-XX:+DeoptimizeALot`. Parts of it depend on a particular sequence of compilation and deoptimization, so if DeoptimizeALot deoptimizes things prematurely, the test can fail.

This PR adds `@requires vm.opt.DeoptimizeALot != true` to the test so that it is skipped when `-XX:+DeoptimizeALot` is used.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323651](https://bugs.openjdk.org/browse/JDK-8323651): compiler/c2/irTests/TestPrunedExHandler.java fails with -XX:+DeoptimizeALot (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [956a4f78](https://git.openjdk.org/jdk/pull/17432/files/956a4f782253b15bd22b163fd15a2f171fccc99f)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17432/head:pull/17432` \
`$ git checkout pull/17432`

Update a local copy of the PR: \
`$ git checkout pull/17432` \
`$ git pull https://git.openjdk.org/jdk.git pull/17432/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17432`

View PR using the GUI difftool: \
`$ git pr show -t 17432`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17432.diff">https://git.openjdk.org/jdk/pull/17432.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17432#issuecomment-1892543914)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Thanks, this test runs in the loom with DeoptimizeALot so we've had to exclude it. I assume you'll bump the copyright date before integrating.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Pull request closed without merging**
