### PR TITLE
JDK-8300823: UB: Compile::_phase_optimize_finished is initialized too late

### PR DESCRIPTION
**Pull request by dafedafe**
Clang _Undefined Behaviour Sanitizer_ has pointed out a spurious load of the `bool` field `Compile::_phase_optimize_finished` with non-boolean values.

This is due to `Compile::_phase_optimize_finished` being initialized too late in the `Compile::Init` method (e.g. https://github.com/openjdk/jdk/blob/544c16e0bdd4335b2624158fd1f6521984aa5079/src/hotspot/share/opto/compile.cpp#L983 indirectly invokes `Compile::phase_optimize_finished()` to read the field).

So, moving the `_phase_optimize_finished` initialization (and the initialization of the other 2 fields in the same `ASSERT` block) up in the `Compile::Init` method.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300823](https://bugs.openjdk.org/browse/JDK-8300823): UB: Compile::_phase_optimize_finished is initialized too late

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12192/head:pull/12192` \
`$ git checkout pull/12192`

Update a local copy of the PR: \
`$ git checkout pull/12192` \
`$ git pull https://git.openjdk.org/jdk pull/12192/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12192`

View PR using the GUI difftool: \
`$ git pr show -t 12192`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12192.diff">https://git.openjdk.org/jdk/pull/12192.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by dafedafe** [comment]
@TobiHartmann @chhagedorn thanks a lot for your reviews!

**Pull request closed without merging**
