### PR TITLE
8290730: compiler/vectorization/TestAutoVecIntMinMax.java failed with "IRViolationException: There were one or multiple IR rule failures."

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
… "IRViolationException: There were one or multiple IR rule failures."

The IR test - TestAutoVecIntMinMax.java was introduced in https://bugs.openjdk.org/browse/JDK-8288107 to test IR generation of MaxV and MinV nodes when the MinI/MaxI nodes are auto-vectorized.
However, the corresponding vector ISA support for min/max on x64 machines is only available in SSE versions > 3 and AVX.
The "@requires" annotation in the JTREG test has been modified to use the whitelisted flags instead.
Deleting the entry for this JTREG test in test/hotspot/jtreg/ProblemList.txt.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290730](https://bugs.openjdk.org/browse/JDK-8290730): compiler/vectorization/TestAutoVecIntMinMax.java failed with "IRViolationException: There were one or multiple IR rule failures."

### Reviewers
 * [Jie Fu](https://openjdk.org/census#jiefu) (@DamonFool - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9610/head:pull/9610` \
`$ git checkout pull/9610`

Update a local copy of the PR: \
`$ git checkout pull/9610` \
`$ git pull https://git.openjdk.org/jdk pull/9610/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9610`

View PR using the GUI difftool: \
`$ git pr show -t 9610`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9610.diff">https://git.openjdk.org/jdk/pull/9610.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
LGTM

**Comment by Bhavana-Kilambi** [comment]
There are a couple of macos failures due to "wget". Should these runs be triggered again?

**Comment by TobiHartmann** [comment]
I'll run testing and report back once it passed.

**Review by vnkozlov — APPROVED** [review]
Good.

I looked on Tobias's testing and verified that the test skipped with `UseSSE` < 4 and it is executed and passed in other configured.

**Comment by Bhavana-Kilambi** [comment]
Thank you for testing this patch.

**Review by TobiHartmann — APPROVED** [review]

**Pull request closed without merging**
