### PR TITLE
8271600: C2: CheckCastPP which should closely follow Allocate is sunk of a loop

### PR DESCRIPTION
**Pull request by iwanowww**
`PhaseIdealLoop::try_sink_out_of_loop()` tries to move nodes outside a loop. It doesn't work well for cast nodes which accompany `Allocate` nodes:  the cast reifies the effect instance initialization and turns a raw pointer into an oop. Once the cast node doesn't immediately follow the corresponding `Initialize`, it creates a window where the raw pointer is observed. And it can become so wide that the raw pointer crosses a safepoint and has to be recorded in the oop map (that's the case when the reported assertion failure happens). 

Proposed fix is to keep such cast nodes intact. Moreover, I propose to disable the optimization for all flavors of cast nodes. 
Cast nodes usually accompany runtime checks and I don't see much benefit in moving the cast node away while leaving the runtime check inside the loop.  

Testing: hs-tier1 - hs-tier6

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271600](https://bugs.openjdk.java.net/browse/JDK-8271600): C2: CheckCastPP which should closely follow Allocate is sunk of a loop

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to 4081f893605ef730334c21000365451818e9d752
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5199/head:pull/5199` \
`$ git checkout pull/5199`

Update a local copy of the PR: \
`$ git checkout pull/5199` \
`$ git pull https://git.openjdk.java.net/jdk pull/5199/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5199`

View PR using the GUI difftool: \
`$ git pr show -t 5199`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5199.diff">https://git.openjdk.java.net/jdk/pull/5199.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
The fix looks reasonable to me.

Actually, on a separate note, I had the very same fix in mind for [JDK-8272562](https://bugs.openjdk.java.net/browse/JDK-8272562) where `CastII` nodes are causing problems instead of `CheckCastPP` nodes. In the attached testcase of that bug we sink a (`AddI` -> `CastII` (range [0, maxint]) -> `ConvI2L` (range [0, maxint]) -> ...) chain to an uncommon path of a div by zero check (the `CastII` node is a left over from an already removed range check). After sinking the nodes we have a chain `CastII` -> `AddI` -> `ConvI2L` -> ... (the sunk `CastII` node is removed in this process):

sink_folding

Since these sunk nodes are pinned to the `493 IfFalse` path of the div by zero check `484 If`, we get additional type information for `545 CastII` in `CastII::Value()` that the type can be improved to `[0,0]` (because `489 Phi` must be zero on this path). `133 ConI` is -1. This means that the type of `544 AddI` becomes -1 which is out of the range [0, maxint] of `538 ConvI2L`. `538 ConvI2L` is replaced with top and we are folding away all the nodes up to the `499 Phi` which is then removed which eventually leads to a bad graph assertion failure. If we would just prevent any Constraint nodes to be sunk then we do not run into this problem. 

So, your patch also fixes JDK-8272562 even though it manifests differently. Not sure how to proceed with JDK-8272562 as it's not an actual duplicate but coincidentally requires the same fix. Should I just open a PR with the test only after this patch goes in or do you want to merge my [testcase](https://bugs.openjdk.java.net/secure/attachment/96032/Reduced.java) into your patch?

Thanks,
Christian

**Comment by iwanowww** [comment]
Thanks for the review, Christian.

I took a look at JDK-8272562. Your analysis looks reasonable, but I'm still curious whether the problem is specific to cast nodes. My understanding is the general problem stems from the fact that a computation may be sunk into an effectively dead path. When C2 can't prove that the branch is dead, the dying computation on that path corrupts the graph. Do we need to introduce a more robust solution to guarantee the corruption never happens?

**Comment by rwestrel** [comment]
> Proposed fix is to keep such cast nodes intact. Moreover, I propose to disable the optimization for all flavors of cast nodes.
> Cast nodes usually accompany runtime checks and I don't see much benefit in moving the cast node away while leaving the runtime check inside the loop.

That looks too conservative to me. It's not always the case that a cast is guarded by a test (the test could have been optimized out). Also, if a node is in a loop nest composed of 2 loops and can be sunk out of both loops, this would be done in 2 loop opts pass. First, from the inner loop and then from the outer loop. On the first pass, cast nodes are added to pin the node out of the inner loop. The change you propose would then prevent sinking out of the outer loop.

**Comment by chhagedorn** [comment]
> Thanks for the review, Christian.
> 
> I took a look at JDK-8272562. Your analysis looks reasonable, but I'm still curious whether the problem is specific to cast nodes. My understanding is the general problem stems from the fact that a computation may be sunk into an effectively dead path. When C2 can't prove that the branch is dead, the dying computation on that path corrupts the graph. Do we need to introduce a more robust solution to guarantee the corruption never happens?

I think it is generally a problem that C2 cannot prove that this branch is dead but data could be dying. But it looks like that data can only die when sinking nodes with `CastII` nodes which gives us the improved type information to trigger that. I could not think of/find another testcase where this could occur otherwise. So, going with your originally proposed fix would prevent the problem from happening but it still exists. Might be worth to further investigate why C2 cannot let control die, too, in this case.

> > Proposed fix is to keep such cast nodes intact. Moreover, I propose to disable the optimization for all flavors of cast nodes.
> > Cast nodes usually accompany runtime checks and I don't see much benefit in moving the cast node away while leaving the runtime check inside the loop.
> 
> That looks too conservative to me. It's not always the case that a cast is guarded by a test (the test could have been optimized out). Also, if a node is in a loop nest composed of 2 loops and can be sunk out of both loops, this would be done in 2 loop opts pass. First, from the inner loop and then from the outer loop. On the first pass, cast nodes are added to pin the node out of the inner loop. The change you propose would then prevent sinking out of the outer loop.

If we don't go with that fix, then it makes even more sense to revisit JDK-8272562 to find a better solution. I'll give it another go.

**Comment by iwanowww** [comment]
Ok, I'm fine with limiting the fix for raw-to-oop casts only.

> The change you propose would then prevent sinking out of the outer loop.

I thought that the code at [loopopts.cpp#L1481](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/loopopts.cpp#L1481) would handle it. Anyway.

**Review by rwestrel — APPROVED** [review]

**Comment by rwestrel** [comment]
> Ok, I'm fine with limiting the fix for raw-to-oop casts only.

Thanks for making the change.

> > The change you propose would then prevent sinking out of the outer loop.
> 
> I thought that the code at [loopopts.cpp#L1481](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/loopopts.cpp#L1481) would handle it. Anyway.

Right. Sinking out of the outer loop wouldn't be prevented.

**Comment by iwanowww** [comment]
Thanks for the reviews, Tobias and Roland.

/integrate

**Pull request closed without merging**
