### PR TITLE
8315437: Enable parallelism in vmTestbase/nsk/monitoring/stress/classload tests

### PR DESCRIPTION
**Pull request by shipilev**
Current vmTestbase/nsk/monitoring/stress/classload tests contains 24 tests, each running exclusively. This drags the tier4 test times up. There seem to be no reason to run these tests exclusively, though: they complete in reasonable time, are lightly-threaded, and consume the usual amount of memory.

We should consider enabling parallelism for them and get improved test performance. Currently it is blocked by TEST.properties with exclusiveAccess.dirs directives in them.

Current run on 18-core machine:
2011.95s user 201.83s system 356% cpu 10:20.19 total

Fully parallel:
2274.02s user 128.64s system 2029% cpu 1:58.39 total 

Additional testing:
 - [x] 50x iterations of Linux x86_64 fastdebug `vmTestbase/nsk/monitoring/stress/classload`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315437](https://bugs.openjdk.org/browse/JDK-8315437): Enable parallelism in vmTestbase/nsk/monitoring/stress/classload tests (**Enhancement** - P4)

### Reviewers
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15506/head:pull/15506` \
`$ git checkout pull/15506`

Update a local copy of the PR: \
`$ git checkout pull/15506` \
`$ git pull https://git.openjdk.org/jdk.git pull/15506/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15506`

View PR using the GUI difftool: \
`$ git pr show -t 15506`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15506.diff">https://git.openjdk.org/jdk/pull/15506.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15506#issuecomment-1700554588)

### CODE REVIEW

**Comment by sspitsyn** [comment]
The fix looks okay to me but it'd be nice to find out why the `exclusiveAccess.dirs` were set for these tests initially. I'm not sure, anyone remembers it though.

**Comment by shipilev** [comment]
> The fix looks okay to me but it'd be nice to find out why the `exclusiveAccess.dirs` were set for these tests initially. I'm not sure, anyone remembers it though.

Yeah. I cannot find a good discussion on these tests. 

I suspect it is mostly historical, from the times where machines were small and resource-constrained, so that a stress test made life hard for any other concurrently running test. Today, that is not the case. We have been doing e.g. GC stress tests in tier3, which can hog CPUs for minutes, without ill effects. 

Anyway, this is similar to other parallelism improvements we did over the previous years, e.g. https://bugs.openjdk.org/browse/JDK-8273433, https://bugs.openjdk.org/browse/JDK-8273438.

Would you like to run this PR in your test systems to see if this particular relaxation is problematic?

**Comment by shipilev** [comment]
@lmesnik, may I interest you in this one too?

**Review by lmesnik — APPROVED** [review]
Looks good, CI passed.

**Comment by shipilev** [comment]
Good, any other reviewers for this one? Thanks!

**Comment by shipilev** [comment]
> Good, any other reviewers for this one? Thanks!

Ping? Thanks!

**Review by plummercj — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
