### PR TITLE
8265938: C2's conditional move optimization does not handle top Phi

### PR DESCRIPTION
**Pull request by TobiHartmann**
C2's CCP optimization sets the type of a PhiNode to TOP because it became dead after loop unrolling. Now since that node is not reachable from the bottom due to an infinite loop at the end of the method, CCP does not enqueue the PhiNode for IGVN. As a result, the dead subgraph is not removed. During loop opts, the conditional move optimization fails on the PhiNode because its type is top. The expected behavior is to simply bail out with "COMPILE SKIPPED: infinite loop (retry at different tier)".

I suggest to fix this by simply handling a TOP Phi in the conditional move optimization code.

This issue was reported by John Jiang (johnsjiang@tencent.com).

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265938](https://bugs.openjdk.java.net/browse/JDK-8265938): C2's conditional move optimization does not handle top Phi

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to d0e0e81941a0d41460c0927980d36d8b6db4ff0f
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3684/head:pull/3684` \
`$ git checkout pull/3684`

Update a local copy of the PR: \
`$ git checkout pull/3684` \
`$ git pull https://git.openjdk.java.net/jdk pull/3684/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3684`

View PR using the GUI difftool: \
`$ git pr show -t 3684`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3684.diff">https://git.openjdk.java.net/jdk/pull/3684.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks reasonable to me!

**Comment by TobiHartmann** [comment]
Thanks for the review, Christian!

**Comment by huishi-hs** [comment]
@TobiHartmann Thanks for fixing tencent reported bug! Your fix is good.

Could an early check added after ccp GVN? Check if it is compiling a method currently in inifinite loop and abort compilation earlier?

--- a/src/hotspot/share/opto/compile.cpp
+++ b/src/hotspot/share/opto/compile.cpp
@@ -2287,6 +2287,9 @@ void Compile::Optimize() {
     TracePhase tp("iterGVN2", &timers[_t_iterGVN2]);
     igvn = ccp;
     igvn.optimize();
+    if (root()->req() == 1) {
+      record_method_not_compilable("trivial infinite loop after phase ccp");
+    }
   }
   print_method(PHASE_ITER_GVN2, 2);

**Comment by TobiHartmann** [comment]
@huishi-hs thanks for the review. This version of the fix was also proposed by the reporter but is not sufficient because it assumes that the infinite loop is reachable from all exit paths. This is not the case in my version of the regression test, were the infinite loop is only in the `b == true` branch.

**Comment by huishi-hs** [comment]
> @huishi-hs thanks for the review. This version of the fix was also proposed by the reporter but is not sufficient because it assumes that the infinite loop is reachable from all exit paths. This is not the case in my version of the regression test, were the infinite loop is only in the `b == true` branch.

You're right. Test is modified. Thanks!

**Review by vnkozlov — CHANGES_REQUESTED** [review]
The fix is good.

I think you need System.exit(0) (or something else) at the end of test. Otherwise the test runs forever due to presence of infinite loop in an other thread. I tried.
May be @iignatev can suggest graceful solution for timely exit in such case.

**Comment by iignatev** [comment]
one way to solve it is to make the thread created at L#57 daemon thread (+L64: `thread.setDaemon(true);`).

I'd also recommend you to use `jdk.test.lib.Utils::adjustTimeout` to factor the sleep time at L66: `Thread.sleep(Utils.adjustTimeout(4000));`

**Comment by TobiHartmann** [comment]
Thanks for the reviews and suggestions.

@vnkozlov, how did you run the test? The exact same code is also used in `compiler/loopopts/TestStrangeControl.java` and we never had problems with that test not exiting.

@iignatev Thanks, I've updated the test(s) accordingly.

**Comment by vnkozlov** [comment]
@TobiHartmann I ran test locally (not with jtreg). TestStrangeControl.java has the same issue when run standalone.
I think JTREG may kill process when main thread exits or something like that.

**Review by vnkozlov — APPROVED** [review]
I verified that `thread.setDaemon(true);` solved endless run issue with local testing I observed.

**Comment by iignatev** [comment]
> I think JTREG may kill process when main thread exits or something like that.

correct, jtreg exits the process almost immediately after the main method exits.

**Comment by TobiHartmann** [comment]
> I think JTREG may kill process when main thread exits or something like that.

Ah right, that explains it. Thanks for the review!

**Review by iignatev — APPROVED** [review]

**Pull request closed without merging**
