### PR TITLE
8332676: Remove unused BarrierSetAssembler::incr_allocated_bytes

### PR DESCRIPTION
**Pull request by albertnetymk**
Trivial removing dead code.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332676](https://bugs.openjdk.org/browse/JDK-8332676): Remove unused BarrierSetAssembler::incr_allocated_bytes (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [970ea0f9](https://git.openjdk.org/jdk/pull/19345/files/970ea0f9a3729ee52416f3afa3e87bc13a0fca60)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [970ea0f9](https://git.openjdk.org/jdk/pull/19345/files/970ea0f9a3729ee52416f3afa3e87bc13a0fca60)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19345/head:pull/19345` \
`$ git checkout pull/19345`

Update a local copy of the PR: \
`$ git checkout pull/19345` \
`$ git pull https://git.openjdk.org/jdk.git pull/19345/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19345`

View PR using the GUI difftool: \
`$ git pr show -t 19345`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19345.diff">https://git.openjdk.org/jdk/pull/19345.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19345#issuecomment-2124310047)

### CODE REVIEW

**Review by tschatzl — CHANGES_REQUESTED** [review]
I think `Thread::allocated_bytes_offset()` can now also removed.

**Review by kimbarrett — APPROVED** [review]
Looks good, and trivial (though maybe wait for @tschatzl to circle back).

**Review by tschatzl — APPROVED** [review]
Fine with me, thanks and trivial.

There are two more mentions of `incr_allocated_bytes` in comments, please remove too.

**Comment by albertnetymk** [comment]
Thanks for review.

/integrate

**Pull request closed without merging**
