### PR TITLE
7124527: [macosx] SwingSet2, label is not read by VoiceOver when focus is on textfield for Internalframe and Table demo.

### PR DESCRIPTION
**Pull request by kumarabhi006**
In SwingSet2, few label components are not set for textfield component in InternalFrame and Table demo and due to this VoiceOver doesn't announce the label along with the textfield value. Added a fix for that and verified in SwingSet2.

Apart from that for Selection mode combobox and Autoresize combobox, VoiceOver doesn't announce the combobox panel details along with combobox current item. 

Although the bug doesn't report this but in Slider demo it is observed that VoiceOver announces the slider value and panel details together.

So, added a fix similar to slider demo for combobox in tabledemo.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-7124527](https://bugs.openjdk.org/browse/JDK-7124527): [macosx] SwingSet2, label is not read by VoiceOver when focus is on textfield for Internalframe and Table demo.

### Reviewers
 * [Artem Semenov](https://openjdk.org/census#asemenov) (@savoptik - Committer) ⚠️ Review applies to [70aca9e0](https://git.openjdk.org/jdk/pull/13268/files/70aca9e03078386db7e133e0207ece12f0c10a46)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13268/head:pull/13268` \
`$ git checkout pull/13268`

Update a local copy of the PR: \
`$ git checkout pull/13268` \
`$ git pull https://git.openjdk.org/jdk.git pull/13268/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13268`

View PR using the GUI difftool: \
`$ git pr show -t 13268`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13268.diff">https://git.openjdk.org/jdk/pull/13268.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13268#issuecomment-1491821637)

### CODE REVIEW

**Comment by kumarabhi006** [comment]
@azuev-java Please review the changes.

**Comment by mrserb** [comment]
Looks fine, please update the dates in the copyright block.

**Review by savoptik — APPROVED** [review]
Looks good to me.

**Comment by kumarabhi006** [comment]
> Looks fine, please update the dates in the copyright block.

Copyright year updated.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
