### PR TITLE
8324065: Daylight saving information for `Africa/Casablanca` are incorrect

### PR DESCRIPTION
**Pull request by naotoj**
Fixing incorrect std/dst transitions for time zones that have rules beyond 2037. The year 2037 restriction seems to come from the old `zic` command implementation and thus can be expanded in the JDK. Arbitrary I chose 2100 which is greater than the year 2087 which is the farthest rule at the moment.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324065](https://bugs.openjdk.org/browse/JDK-8324065): Daylight saving information for `Africa/Casablanca` are incorrect (**Bug** - P4)

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to [9ce8f35b](https://git.openjdk.org/jdk/pull/17492/files/9ce8f35b7fb4cd693c7a5ca479232f54429200e1)
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**) ⚠️ Review applies to [9ce8f35b](https://git.openjdk.org/jdk/pull/17492/files/9ce8f35b7fb4cd693c7a5ca479232f54429200e1)
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer) ⚠️ Review applies to [9ce8f35b](https://git.openjdk.org/jdk/pull/17492/files/9ce8f35b7fb4cd693c7a5ca479232f54429200e1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17492/head:pull/17492` \
`$ git checkout pull/17492`

Update a local copy of the PR: \
`$ git checkout pull/17492` \
`$ git pull https://git.openjdk.org/jdk.git pull/17492/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17492`

View PR using the GUI difftool: \
`$ git pr show -t 17492`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17492.diff">https://git.openjdk.org/jdk/pull/17492.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17492#issuecomment-1899100702)

### CODE REVIEW

**Review by irisclark — APPROVED** [review]
Hopefully "2100" is unique enough that you'll be able to easily search/replace the next time you need to extend.

**Comment by naotoj** [comment]
> Hopefully "2100" is unique enough that you'll be able to easily search/replace the next time you need to extend.

Thank you, Iris. Added a comment to clarify the need for possible expansion.

**Review by irisclark — APPROVED** [review]
Still looks good!

**Review by JoeWang-Java — APPROVED** [review]
You've saved generations of engineers from having to look at it again. By then, the dev AI will look at it and ...

**Review by justin-curtis-lu — APPROVED** [review]
LGTM, _NegativeDSTTest.java_ can bump the copyright year to 2024 as well.

**Comment by naotoj** [comment]
> LGTM, _NegativeDSTTest.java_ can bump the copyright year to 2024 as well.

Forgot that! Fixed.

**Pull request closed without merging**
