### PR TITLE
8337938: ZUtils::alloc_aligned allocates without reporting to NMT

### PR DESCRIPTION
**Pull request by jsikstro**
Replaces usage of posix_memalign/_aligned_malloc with os::malloc and manual alignment to report memory usage to NMT. Manually aligning the memory makes the returned address unfreeable by malloc (as clarified by the added comment), which is reasonable since the memory used by ZUtils::alloc_aligned is never freed.

Tested with tiers 1-3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337938](https://bugs.openjdk.org/browse/JDK-8337938): ZUtils::alloc_aligned allocates without reporting to NMT (**Bug** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20523/head:pull/20523` \
`$ git checkout pull/20523`

Update a local copy of the PR: \
`$ git checkout pull/20523` \
`$ git pull https://git.openjdk.org/jdk.git pull/20523/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20523`

View PR using the GUI difftool: \
`$ git pr show -t 20523`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20523.diff">https://git.openjdk.org/jdk/pull/20523.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20523#issuecomment-2277888088)

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Review by kimbarrett — APPROVED** [review]
Looks good, except for some copyrights needing update.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Review by stefank — APPROVED** [review]

**Comment by jsikstro** [comment]
Thank you for the reviews! @stefank @kimbarrett 
/integrate

**Pull request closed without merging**
