### PR TITLE
JDK-8309934: Update GitHub Actions to use JDK 17 for building jtreg

### PR DESCRIPTION
**Pull request by sormuras**
Please review this change to use the pre-installed JDK 17 for building jtreg when running on GitHub Actions.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309934](https://bugs.openjdk.org/browse/JDK-8309934): Update GitHub Actions to use JDK 17 for building jtreg (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14448/head:pull/14448` \
`$ git checkout pull/14448`

Update a local copy of the PR: \
`$ git checkout pull/14448` \
`$ git pull https://git.openjdk.org/jdk.git pull/14448/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14448`

View PR using the GUI difftool: \
`$ git pr show -t 14448`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14448.diff">https://git.openjdk.org/jdk/pull/14448.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14448#issuecomment-1589352777)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by tstuefe** [comment]
Do you know why this helped? 

Will you downport this to JDK 17 too?

**Comment by sormuras** [comment]
> Do you know why this helped?

No, unfortunately not: _"Switching from 11 to 17 seems to mend the (unknown underlying) issue for the time being."_
A test build using the same JDK as pre-installed on GitHub-hosted runners on my local machine did not fail either.

> Will you downport this to JDK 17 too?

No. JDK 17 is archived and it uses JDK 8 to build jtreg within a single-file workflow definition:

- https://github.com/openjdk/jdk17/blob/master/.github/workflows/submit.yml#L88

A backport to JDK 21 makes sense.

**Comment by tstuefe** [comment]
> > Will you downport this to JDK 17 too?
> 
> No. JDK 17 is archived and it uses JDK 8 to build jtreg within a single-file workflow definition:
> 
>     * https://github.com/openjdk/jdk17/blob/master/.github/workflows/submit.yml#L88

Sorry, my mistake, I looked at the wrong test results.

**Pull request closed without merging**
