### PR TITLE
8331081: 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version

### PR DESCRIPTION
**Pull request by cushon**
This change fixes a bug preventing javac from emitting 'compiler.warn.sun.proprietary' diagnostics if `--system` is set to a non-default value. The diagnostics are currently emitted for values of `--release`, and for the default value of `--system`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331081](https://bugs.openjdk.org/browse/JDK-8331081): 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version (**Bug** - P4)

### Reviewers
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19069/head:pull/19069` \
`$ git checkout pull/19069`

Update a local copy of the PR: \
`$ git checkout pull/19069` \
`$ git pull https://git.openjdk.org/jdk.git pull/19069/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19069`

View PR using the GUI difftool: \
`$ git pr show -t 19069`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19069.diff">https://git.openjdk.org/jdk/pull/19069.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19069#issuecomment-2091385097)

### CODE REVIEW

**Comment by lahodaj** [comment]
Traditionally, I don't think javac was ever (supposed to) produce these warnings when the system classes where overridden (using `-bootclasspath` in JDK <9, and `--system` in JDK >= 9).

I believe the idea was that when someone provides their own the system classes, we shall not produce a warning based on some hardcoded knowledge, which may or may not be relevant for the externally provided system classes. That might be overly cautious, especially given that since JDK 9, it is only about `jdk.unsupported`, and it is harder to imagine a usecase where the warning would not be reasonable for that module.

On the code level, I would suggest to re-organize the code so that user packages would not accumulate in `supplementaryFlags` - that seems unnecessary. If the module owning `c` is neither `noModule` nor `jdk_unsupported`, there's no point in putting anything in the map the computation, I think. (Not too terrible, but some user programs use a lot of packages.)

Also, I wonder why not simply use `--release 11`. The set of usecases for which `--system` needs to be used instead of `--release`, and for which the warning is important seems quite limited to me.

**Comment by cushon** [comment]
> Traditionally, I don't think javac was ever (supposed to) produce these warnings when the system classes where overridden (using `-bootclasspath` in JDK <9, and `--system` in JDK >= 9).
> 
> I believe the idea was that when someone provides their own the system classes, we shall not produce a warning based on some hardcoded knowledge, which may or may not be relevant for the externally provided system classes. That might be overly cautious, especially given that since JDK 9, it is only about `jdk.unsupported`, and it is harder to imagine a usecase where the warning would not be reasonable for that module.

Understood, thanks. The motivation here is that I'm stuck using `--system` for some use-cases (more on that below), and all else being equal I'd like to discourage new uses of `jdk.unsupported` APIs, so supporting this diagnostic would be helpful for that.

> On the code level, I would suggest to re-organize the code so that user packages would not accumulate in `supplementaryFlags` - that seems unnecessary. If the module owning `c` is neither `noModule` nor `jdk_unsupported`, there's no point in putting anything in the map the computation, I think. (Not too terrible, but some user programs use a lot of packages.)

Thanks, I can clean that up.

> Also, I wonder why not simply use `--release 11`. The set of usecases for which `--system` needs to be used instead of `--release`, and for which the warning is important seems quite limited to me.

`--release` can't be used together with `--add-exports=`, and can't be used to compile code that uses internal APIs for Java 8 and earlier ([JDK-8206937](https://bugs.openjdk.org/browse/JDK-8206937)). That use-case may be limited and I understand that at least the first part is deliberate, but that's use-case for `--system` I have.

**Review by lahodaj — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
