### PR TITLE
8335643: serviceability/dcmd/vm tests fail for ZGC after JDK-8322475

### PR DESCRIPTION
**Pull request by tstuefe**
The new System.map facility fails its tests when the JVM is using ZGC. The facility is working fine, but the test checks for the java heap to appear as committed non-shared memory segment, but on ZGC we reserve the memory as shared memory.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335643](https://bugs.openjdk.org/browse/JDK-8335643): serviceability/dcmd/vm tests fail for ZGC after JDK-8322475 (**Bug** - P4)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20034/head:pull/20034` \
`$ git checkout pull/20034`

Update a local copy of the PR: \
`$ git checkout pull/20034` \
`$ git pull https://git.openjdk.org/jdk.git pull/20034/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20034`

View PR using the GUI difftool: \
`$ git pr show -t 20034`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20034.diff">https://git.openjdk.org/jdk/pull/20034.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20034#issuecomment-2210161216)

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
@tstuefe Please also remove the problem list entry. See the error from the skara bot. Thanks!

**Comment by tstuefe** [comment]
> @tstuefe Please also remove the problem list entry. See the error from the skara bot. Thanks!

Oh, Skara tells me this now? Or did I never notice :) In any case that's cool. Thanks!

**Review by jerboaa — APPROVED** [review]
Seems fine to me.

**Review by jerboaa — CHANGES_REQUESTED** [review]
Apparently also in `ProblemList-generational-zgc.txt`, which needs to remove those lines.

**Review by jerboaa — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Seems okay.

Thanks for fixing.

**Comment by tstuefe** [comment]
Thanks @dholmes-ora and @jerboaa 
/integrate

**Pull request closed without merging**
