### PR TITLE
JDK-8273808: Cleanup AddFontsToX11FontPath

### PR DESCRIPTION
**Pull request by MBaesken**
Hello please review this small cleanup change.  Seems AddFontsToX11FontPath from fontpath.c is unused/unreferenced and can be removed.

Thanks, Matthias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273808](https://bugs.openjdk.java.net/browse/JDK-8273808): Cleanup AddFontsToX11FontPath

### Reviewers
 * [Pankaj Bansal](https://openjdk.java.net/census#pbansal) (@pankaj-bansal - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5532/head:pull/5532` \
`$ git checkout pull/5532`

Update a local copy of the PR: \
`$ git checkout pull/5532` \
`$ git pull https://git.openjdk.java.net/jdk pull/5532/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5532`

View PR using the GUI difftool: \
`$ git pr show -t 5532`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5532.diff">https://git.openjdk.java.net/jdk/pull/5532.diff</a>

</details>

### CODE REVIEW

**Review by pankaj-bansal — APPROVED** [review]
Looks good to me. I have verified that the function is not referenced anywhere. Just to be sure, I gave a mach5 job also (Link in JBS). Did not see anything wrong.

**Comment by MBaesken** [comment]
Hi Pankaj , thanks for the review and additional testing you did.  Can we count this change as trivial or  should I wait for a second review ?
Best regards, Matthias

**Review by RealLucy — APPROVED** [review]
LGTM.

**Pull request closed without merging**
