### PR TITLE
8345158: IGV: local scheduling should not place successors before predecessors

### PR DESCRIPTION
**Pull request by danielogh**
A slight tweak to consider def-use in scheduleBlock.

Testing: opened a few graphs in control-flow graph mode without any assertion failure.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345158](https://bugs.openjdk.org/browse/JDK-8345158): IGV: local scheduling should not place successors before predecessors (**Sub-task** - P4)

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22481/head:pull/22481` \
`$ git checkout pull/22481`

Update a local copy of the PR: \
`$ git checkout pull/22481` \
`$ git pull https://git.openjdk.org/jdk.git pull/22481/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22481`

View PR using the GUI difftool: \
`$ git pr show -t 22481`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22481.diff">https://git.openjdk.org/jdk/pull/22481.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22481#issuecomment-2511486704)
</details>

### CODE REVIEW

**Review by robcasloz — APPROVED** [review]
Looks good, thanks for fixing this Daniel!

I tested this by examining a few schedules manually (comparing IGV-approximated schedules after matching vs. "real" C2-generated schedules after GCM) and also checked that the changes do not increase the overhead of approximating schedules in IGV (which is still negligible compared to graph layout time).

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too.

**Comment by danielogh** [comment]
Thanks for the reviews!

**Pull request closed without merging**
