### PR TITLE
8261750: Remove internal class sun.net.www.MimeLauncher

### PR DESCRIPTION
**Pull request by FrauBoes**
This change removes sun.net.www.MimeLauncher, a package-private class that is no longer used.

The sun.net.www package is exported to java.net.http and jdk.jartool. The only public access point to a MimeLauncher instance is sun.net.www.MimeEntry::launch, which is not called anywhere in those two package. A related public class, sun.net.www. ApplicationLaunchException, is no longer used anywhere. Therefore, these two can also be considered for removal.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261750](https://bugs.openjdk.java.net/browse/JDK-8261750): Remove internal class sun.net.www.MimeLauncher

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2580/head:pull/2580`
`$ git checkout pull/2580`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Comment by vyommani** [comment]
Looks ok to me.
Vyom

**Review by dfuch — APPROVED** [review]
Looks good to me. Make sure to run tier1/tier2/tier3 to double check that there's no test invoking this.

**Comment by FrauBoes** [comment]
tier1/tier2/tier3 are all clear. Thanks for reviewing!

**Pull request closed without merging**
