### PR TITLE
8261675: ObjectValue::set_visited(bool) sets _visited false

### PR DESCRIPTION
**Pull request by navyxliu**
The setter is error-prone. it unconditionally sets _visited false.
this patch stores the argument to it.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261675](https://bugs.openjdk.java.net/browse/JDK-8261675): ObjectValue::set_visited(bool) sets _visited false

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2560/head:pull/2560`
`$ git checkout pull/2560`

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Wow. This was original changes for first implementation of Escape Analysis 6558600.

But it works because the only place where `set_visited()` is called it sets to `false`:
[debugInfoRec.cpp#L358](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/code/debugInfoRec.cpp#L358)

`is_visited()` is not called at all - `_visited` field is accessed directly only in one place:
[debugInfo.cpp#L161](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/code/debugInfo.cpp#L161)

Would be nice to clean up this mess.

**Comment by vnkozlov** [comment]
In addition to your fix you can consider next changes to avoid dumping unneeded data in debug info (deoptimizer reads objects data only from top frame [deoptimization.cpp#L190](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/deoptimization.cpp#L190):
```
src/hotspot/share/opto/output.cpp
     // We dump the object pool first, since deoptimization reads it in first.
-    C->debug_info()->dump_object_pool(objs);
+    C->debug_info()->dump_object_pool(objs, (depth < max_depth));

src/hotspot/share/code/debugInfoRec.hpp
-  void dump_object_pool(GrowableArray<ScopeValue*>* objects);
+  void dump_object_pool(GrowableArray<ScopeValue*>* objects, bool visited = false);

src/hotspot/share/code/debugInfoRec.cpp
-void DebugInformationRecorder::dump_object_pool(GrowableArray<ScopeValue*>* objects) {
+void DebugInformationRecorder::dump_object_pool(GrowableArray<ScopeValue*>* objects, bool visited) {
   guarantee( _pcs_length > 0, "safepoint must exist before describing scopes");
   PcDesc* last_pd = &_pcs[_pcs_length-1];
   if (objects != NULL) {
     for (int i = objects->length() - 1; i >= 0; i--) {
-      objects->at(i)->as_ObjectValue()->set_visited(false);
+      objects->at(i)->as_ObjectValue()->set_visited(visited);
     }
   }

**Comment by navyxliu** [comment]
> In addition to your fix you can consider next changes to avoid dumping unneeded data in debug info (deoptimizer reads objects data only from top frame [deoptimization.cpp#L190](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/deoptimization.cpp#L190):
> 
> ```
> src/hotspot/share/opto/output.cpp
>      // We dump the object pool first, since deoptimization reads it in first.
> -    C->debug_info()->dump_object_pool(objs);
> +    C->debug_info()->dump_object_pool(objs, (depth < max_depth));
> ```

hi, Vladimir, 

Thank you for reviewing this patch.

I don't understand why it's depth < max_depth instead of <=.  
Further, the effect of this optimization seems limited. this statement is in a loop like this. 
depth < max_depth is almost always true. 

```
  for (int depth = 1; depth <= max_depth; depth++) {
...
    C->debug_info()->dump_object_pool(objs, (depth < max_depth));
...
  }
```

but I get your point. It seems that `Process_OopMap_Node` may dump identical objects in the loop.  I am not sure there are objects overlap different jvmstates.  let me check and create another issue if so.

**Review by vnkozlov — APPROVED** [review]
I am fine with your current change (getter and setter). Let push it.
And I will work on suggested optimization/clean in separate RFE (change will need comments to avoid confusion, as you have).

**Comment by navyxliu** [comment]
Hi, Vladimir, 


> I am fine with your current change (getter and setter). Let push it.
> And I will work on suggested optimization/clean in separate RFE (change will need comments to avoid confusion, as you have).

Sounds good. Thank you for sponsoring it.

**Comment by vnkozlov** [comment]
Note, I think it is trivial change and one review is enough.

**Pull request closed without merging**
