### PR TITLE
8315937: Enable parallelism in vmTestbase/nsk/stress/numeric tests

### PR DESCRIPTION
**Pull request by roy-soumadipta**
'vmTestbase/nsk/stress/numeric' is a small and quick test suite. There seems to be no reason to run these tests exclusively. The tests themselves can be run as performance tests, but they are not executed as such in current configs. We should consider enabling parallelism for them and get improved test performance. Currently it is blocked by 'TEST.properties' with 'exclusiveAccess.dirs' directives in them.

Below are few metrics which shows around 10% improvement in fastdebug mode and around 5% improvement in release mode without any regression:

* fastdebug_before : **72.78s user 20.76s system 272% cpu 34.337 total**
* fastdebug_after    : **73.63s user 19.73s system 303% cpu 30.711 total**
* release_before      : **33.42s user 19.42s system 241% cpu 21.898 total**
* release_after         : **33.47s user 18.60s system 255% cpu 20.364 total**

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8315937](https://bugs.openjdk.org/browse/JDK-8315937): Enable parallelism in vmTestbase/nsk/stress/numeric tests (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15725/head:pull/15725` \
`$ git checkout pull/15725`

Update a local copy of the PR: \
`$ git checkout pull/15725` \
`$ git pull https://git.openjdk.org/jdk.git pull/15725/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15725`

View PR using the GUI difftool: \
`$ git pr show -t 15725`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15725.diff">https://git.openjdk.org/jdk/pull/15725.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15725#issuecomment-1717931009)

### CODE REVIEW

**Comment by shipilev** [comment]
I think the larger improvement comes from the fact that we do not lose parallel VM workers waiting on these short tests, when larger `tier4` suite is running. This looks good to me, but @lmesnik might want to give it a spin.

**Review by shipilev — APPROVED** [review]
Looks good.

/reviewers 2

**Review by lmesnik — APPROVED** [review]
Testing in CI passed.

**Pull request closed without merging**
