### PR TITLE
8326617: String Template FMT removes unnecessary int to long type cast

### PR DESCRIPTION
**Pull request by wenshao**
In the current version, FMT."v =%d\{1}" will call the StringConcatHelper.prepend(long/byte[]/long) method, which should behave the same as STR."v =\{1}". Call StringConcatHelper.prepend(long/byte[]/int), should not convert int to long

Please review and don't hesitate to critique my approach and patch.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326617](https://bugs.openjdk.org/browse/JDK-8326617): String Template FMT removes unnecessary int to long type cast (**Enhancement** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16017/head:pull/16017` \
`$ git checkout pull/16017`

Update a local copy of the PR: \
`$ git checkout pull/16017` \
`$ git pull https://git.openjdk.org/jdk.git pull/16017/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16017`

View PR using the GUI difftool: \
`$ git pr show -t 16017`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16017.diff">https://git.openjdk.org/jdk/pull/16017.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16017#issuecomment-1962436196)

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
Good catch. Out of scope of this issue, but with the commented out code, the `explicitCastArguments` call before the switch can be removed, and `itype` can simply become `ptype`.

**Comment by wenshao** [comment]
@JimLaskey could you please help review the code? Thank you.

**Comment by liach** [comment]
See #18688, String template is being removed for now.

**Pull request closed without merging**
