### PR TITLE
8290688: Optimize x86_64 nmethod entry barriers

### PR DESCRIPTION
**Pull request by fisk**
The current x86_64 nmethod entry barrier is good, but it could be a bit better. In particular, this enhancement targets the following ideas.

1. The alignment of the cmp instruction is 8 bytes. However, we only patch 4 bytes and the instruction length is always 8 bytes. So if we align the start of the instruction to 4 bytes only, that is enough to ensure that the immediate part of the instruction is 4 byte aligned, which is all we need (cf. http://cr.openjdk.java.net/~jrose/jvm/hotspot-cmc.html).

2. Today the fast path (conditionally) jumps over a call to a stub. It is not uncommon for the branch not taken path being better optimized, making it favourable to move the call to a stub out-of-line. This has the additional benefit of not polluting the instruction caches at the nmethod entry with instructions not used in the fast path. A bit messy but we can do it for at least C2 code.

3. For C1 and native wrappers, I don't think they are hot enough to warrant the stub machinery. But at least the jump that jumps over the cold stuff, can be shortened. I can get behind that.

Before addressing this, turning nmethod entry barriers on with G1 (e.g. by enabling loom) leads to a regression in DaCapo tradesoap-large. With this enhancement, the regression goes away, so that the cost of nmethod entry barriers is not visible.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290688](https://bugs.openjdk.org/browse/JDK-8290688): Optimize x86_64 nmethod entry barriers

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9569/head:pull/9569` \
`$ git checkout pull/9569`

Update a local copy of the PR: \
`$ git checkout pull/9569` \
`$ git pull https://git.openjdk.org/jdk pull/9569/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9569`

View PR using the GUI difftool: \
`$ git pr show -t 9569`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9569.diff">https://git.openjdk.org/jdk/pull/9569.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by fisk** [comment]
> Looks good.

Thanks for the review, @vnkozlov!

**Review by reinrich — APPROVED** [review]
Hi Erik,

Looks good to me!

I can imagine that hot taken branches, especially many of them, can become a
performance issue when the hardware fails to predict the target address.

Richard.

**Comment by fisk** [comment]
Thanks for the review @reinrich!

**Pull request closed without merging**
