### PR TITLE
8256820: AArch64: Optimize vector rotate (immediate) with shift and insert instructions

### PR DESCRIPTION
**Pull request by dgbo**
This patch optimizes vectorial rotate (immediate) on aarch64 with shift and insert instructions, i.e. SLI and SRI.

Patch passed jtreg tier1-3 tests with linux-aarch64-server-fastdebug build.
Tests under `test/hotspot/jtreg/compiler/c2/cr6340864/` runned specially for the correctness and passed.

The JMH micro `test/micro/org/openjdk/bench/java/lang/RotateBenchmark.java` is used for performance test.
Witnessed ~15.4% performance improvements on Kunpeng920 (CPU tsv110), but ~15.8% regression on Kunpeng916 (CPU A72).
So a switch `UseSIMDShiftInsertForRotation` is introduced on aarch64 with default value `false`, and set `true` for Kunpeng920.

The `RotateBenchmark.java` JMH micro-benchmark results on Kunpeng920:
```
Benchmark                            (SHIFT)  (TESTSIZE)   Mode  Cnt     Score    Error   Units

# kunpeng 920, -XX:-UseSIMDShiftInsertForRotation
RotateBenchmark.testRotateLeftI           20        1024  thrpt   10  3524.840 ±  2.365  ops/ms
RotateBenchmark.testRotateLeftIImm        20        1024  thrpt   10  3961.288 ±  0.897  ops/ms
RotateBenchmark.testRotateLeftL           20        1024  thrpt   10  1704.321 ± 11.309  ops/ms
RotateBenchmark.testRotateLeftLImm        20        1024  thrpt   10  2137.924 ±  2.215  ops/ms
RotateBenchmark.testRotateRightI          20        1024  thrpt   10  3536.960 ±  7.945  ops/ms
RotateBenchmark.testRotateRightIImm       20        1024  thrpt   10  3961.552 ±  0.673  ops/ms
RotateBenchmark.testRotateRightL          20        1024  thrpt   10  1729.868 ±  0.468  ops/ms
RotateBenchmark.testRotateRightLImm       20        1024  thrpt   10  2132.458 ±  3.385  ops/ms

# kunpeng 920, default, -XX:+UseSIMDShiftInsertForRotation
RotateBenchmark.testRotateLeftI           20        1024  thrpt   10  3504.602 ± 21.609  ops/ms
RotateBenchmark.testRotateLeftIImm        20        1024  thrpt   10  4569.820 ±  7.455  ops/ms
RotateBenchmark.testRotateLeftL           20        1024  thrpt   10  1730.735 ±  0.701  ops/ms
RotateBenchmark.testRotateLeftLImm        20        1024  thrpt   10  2469.796 ±  0.981  ops/ms
RotateBenchmark.testRotateRightI          20        1024  thrpt   10  3540.899 ±  7.679  ops/ms
RotateBenchmark.testRotateRightIImm       20        1024  thrpt   10  4571.876 ±  0.879  ops/ms
RotateBenchmark.testRotateRightL          20        1024  thrpt   10  1731.499 ±  0.877  ops/ms
RotateBenchmark.testRotateRightLImm       20        1024  thrpt   10  2469.454 ±  0.705  ops/ms
```

This also moves all logical and shifting NEON instructions from `aarch64.ad` to `aarch64_neon.ad`,
and has two minor improvements of supporting vector length 4 for `vsraa8B_imm` and `vsrla8B_imm`, vector length 2 for `vsraa4S_imm` and `vsrla4S_imm`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8256820](https://bugs.openjdk.java.net/browse/JDK-8256820): AArch64: Optimize vector rotate (immediate) with shift and insert instructions

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1761/head:pull/1761`
`$ git checkout pull/1761`

### CODE REVIEW

**Review by theRealAph — COMMENTED** [review]
This patch is very hard to review because much of it is just moving things around. Please do this as two PRs, one which does all the moves and one with the substantive changes. Thanks.

**Comment by dgbo** [comment]
Thanks for the quick reply. Deleted all the moves in the updated version.

We tested this on the two servers we have by hand now. It is a pity for us that we didn't see performance improvements on `Cortex-A72`.
Because we have detected microarchitecture in the code already, I thought we could make full use of the flexibility it provided.

We find the shift and insert instructions are used in Linux OS for serveral crypto algorithms for all CPUs [1, 2, 3].
But as of now, we only have the micro benchmarks for JDK as shown before.
I'll try to investigate to see if there is any workload can benifit from this.

Maybe someone from the community can help test this on other CPUs, like `ThunderX`, `Cortex-A73`? Thanks. :)

[1] https://github.com/torvalds/linux/blob/master/arch/arm64/crypto/chacha-neon-core.S
[2] https://github.com/torvalds/linux/blob/master/arch/arm64/crypto/crct10dif-ce-core.S
[3] https://github.com/torvalds/linux/blob/master/arch/arm64/crypto/sha512-armv8.pl

**Comment by dgbo** [comment]
> _Mailing list message from [Andrew Haley](mailto:aph@redhat.com) on [hotspot-dev](mailto:hotspot-dev@openjdk.java.net):_
> 
> On 14/12/2020 11:48, Dong Bo wrote:
> 
> > We tested this on the two servers we have by hand now. It is a pity
> > for us that we didn't see performance improvements on `Cortex-A72`.
> > Because we have detected microarchitecture in the code already, I
> > thought we could make full use of the flexibility it provided.
> > We find the shift and insert instructions are used in Linux OS for
> > serveral crypto algorithms for all CPUs [1, 2, 3].
> 
> I don't want to be unfair to you. There are many small optimizations
> that we have made for which we don't require large-scale benchmarks.
> I'm not going to start insisting that every small change shows a
> gain on such benchmarks.
> 
> But this patch seems to be very marginal: not only does it offer a
> modest gain one one machine, it also shows a modest loss on another.
> Not only that, but we do not know if auto-vectorization is at all
> effective on these OpenJDK's algorithms.
> 
Agree. It's marginal. These crypto algorithms in JDK are not vectorized.
I checked some other Java code in core-libs, didn't find any candidate of this optimization.
The rotate instructions are also negligible or inexistent in applications we investigated, like Spark, Flink, Tomcat.
> My reason for pushing back here is that I want HotSpot to generate "good"
> code for all AArch64 platforms, rather than containing special patterns
> for microarchitectures. There are risks if we allow that. For example,
> mistakes which affect only one machine might be made by accident, and
> they cannot be tested by anyone who does not have that machine. Also,
> the AArch64 back end becomes complex and hard to maintain.
> 
> For example, a simple mistake made during a critical patch update
> might break Kunpeng920, and unless everybody tests on all machines, we
> might not know until it's too late to fix it.
> 
> So, any change which causes divergence between microarchitectures must
> be needed, or it isn't worth the risk. It's not in your interest for
> that to happen, either.
> 
OKAY, this does make sense to us, we don't want to take the possible risk neither.
By far, I think it's not worthy, unless we see a profitable workload one day.
As of now, I am going to withdraw this.

Thanks for the comments.
Best Regards.

**Pull request closed without merging**
