### PR TITLE
8256414: add optimized build to submit workflow

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

Could you please review this small and trivial patch which adds `linux-x64-optimized` build to submit workflow so breakages of this build flavor would be easier to spot?

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ⏳ (3/6 running) | ⏳ (2/2 running) | ⏳ (2/2 running) | ⏳ (2/2 running) |

### Issue
 * [JDK-8256414](https://bugs.openjdk.java.net/browse/JDK-8256414): add optimized build to submit workflow

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to bad0582fc3fb926f4ca99aa091b3103faad2aeda
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to bad0582fc3fb926f4ca99aa091b3103faad2aeda

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1233/head:pull/1233`
`$ git checkout pull/1233`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Thanks a lot, Igor! Looks good.

**Review by shipilev — APPROVED** [review]
Looks fine, but wouldn't you like to add `--disable-precompiled-headers` as well?

**Review by vnkozlov — APPROVED** [review]

**Comment by iignatev** [comment]
> Looks fine, but wouldn't you like to add `--disable-precompiled-headers` as well?

sure, make sense.

**Review by shipilev — APPROVED** [review]

**Comment by iignatev** [comment]
Thanks for the reviews, folks. the build looks green, integrating. 

/integrate

**Comment by dcubed-ojdk** [comment]
@iignatev - did you also change Mach5? I don't have workflow builds enabled
by default since I typically do Mach5 builds...

**Comment by iignatev** [comment]
> @iignatev - did you also change Mach5? I don't have workflow builds enabled
> by default since I typically do Mach5 builds...

Hi Dan, no, not yet. I’m going to change jib profile and tier definitions by a separate RFE.

**Pull request closed without merging**
