### PR TITLE
8269760: idea.sh should not invoke cygpath directly

### PR DESCRIPTION
**Pull request by JornVernee**
From the JBS issue:

Currently idea.sh checks if `CYGPATH` is set, and then continues by invoking `cygpath` directly.

This doesn't work if `CYGPATH` is not actually set to `cygpath`, but to something else, such as `wslpath`.

Instead of invoking `cygpath` directly, the value of the `CYGPATH` variable should be used.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269760](https://bugs.openjdk.java.net/browse/JDK-8269760): idea.sh should not invoke cygpath directly

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4655/head:pull/4655` \
`$ git checkout pull/4655`

Update a local copy of the PR: \
`$ git checkout pull/4655` \
`$ git pull https://git.openjdk.java.net/jdk pull/4655/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4655`

View PR using the GUI difftool: \
`$ git pr show -t 4655`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4655.diff">https://git.openjdk.java.net/jdk/pull/4655.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Not an expert on the value of these variables, but the changes you have look consistent.

**Comment by JornVernee** [comment]
> Not an expert on the value of these variables

My own line of thought is that it is reasonable to expect that anything found in the `CYGPATH` variable is fine to treat as if it were `cygpath` like this (this could be an alternative `cygpath` binary, or a substitutable implementation like `wslpath`)

**Review by erikj79 — APPROVED** [review]

**Pull request closed without merging**
