### PR TITLE
8286581: Make Java process DPI Aware if sun.java2d.dpiaware property is set

### PR DESCRIPTION
**Pull request by rajamah**
I tested by removing dpi-awareness settings from the manifest file, and then running my app with -Dsun.java2d.dpiaware=false. This showed java.exe as "Unaware" in task-manager, and with it set to true I saw "Per-Monitor (v2)" dpi awareness for java.exe.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286581](https://bugs.openjdk.org/browse/JDK-8286581): Make Java process DPI Aware if sun.java2d.dpiaware property is set

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11998/head:pull/11998` \
`$ git checkout pull/11998`

Update a local copy of the PR: \
`$ git checkout pull/11998` \
`$ git pull https://git.openjdk.org/jdk pull/11998/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11998`

View PR using the GUI difftool: \
`$ git pr show -t 11998`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11998.diff">https://git.openjdk.org/jdk/pull/11998.diff</a>

</details>

### CODE REVIEW

**Review by aivanov-jdk — APPROVED** [review]

**Comment by prrace** [comment]
Can you explain why you think this change is needed if its already set ?
And additionally, you describe what happens with explicit setting of the property (when the manifest is disabled) but don't say which is the default.

**Comment by aivanov-jdk** [comment]
> Can you explain why you think this change is needed if its already set ?

Initially, I proposed to remove the property and code associated with it because its value isn't respected as the DPI Awareness is set in the manifest.

You [asked](https://bugs.openjdk.org/browse/JDK-8286581?focusedCommentId=14495409&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14495409) about a custom launcher which may not set the DPI Awareness in the manifest.

If the manifest entries are missing, Java calls [`SetProcessDPIAware`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware) which sets the process DPI Awareness to **System** (`DPI_AWARENESS_CONTEXT_SYSTEM_AWARE`). That is the UI on the _main screen_ is rendered as expected. Yet if the user changes the scale of the main screen or moves the window to a monitor with different scale, the UI will be auto-scaled by Windows, which means it will be blurry.

Java supports **Per-Monitor v2 DPI Awareness** (`DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2`). This fix addresses the difference and sets the DPI Awareness to the correct one in case if the manifest entries are missing for whatever reason.

> And additionally, you describe what happens with explicit setting of the property (when the manifest is disabled) but don't say which is the default.

The default value is `true` for the standard launcher.

https://github.com/openjdk/jdk/blob/ade08e190cc28cf0ce0194fa3fb67e48dc634e07/src/java.desktop/windows/classes/sun/java2d/windows/WindowsFlags.java#L220-L223

**Comment by prrace** [comment]
> You [asked](https://bugs.openjdk.org/browse/JDK-8286581?focusedCommentId=14495409&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14495409) about a custom launcher which may not set the DPI Awareness in the manifest.

OK that is what I expected as the answer .. it really helps reviewers if a PR gives explanation of things like this in the initial description ..

**Review by prrace — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
> OK that is what I expected as the answer .. it really helps reviewers if a PR gives explanation of things like this in the initial description ..

Rajat and I discussed it, I agree providing a short summary of what the problem is helps reviewers as it saves time opening the JBS issue and reading through all the comments.

Thank you!

**Pull request closed without merging**
