### PR TITLE
8333410: [AArch64] Clean unused classes in nativeInst_aarch64.hpp

### PR DESCRIPTION
**Pull request by kuaiwei**
Some classes in nativeInst_aarch64.hpp are unused and can be removed.

I checked with tier1 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333410](https://bugs.openjdk.org/browse/JDK-8333410): [AArch64] Clean unused classes in nativeInst_aarch64.hpp (**Enhancement** - P4)

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19518/head:pull/19518` \
`$ git checkout pull/19518`

Update a local copy of the PR: \
`$ git checkout pull/19518` \
`$ git pull https://git.openjdk.org/jdk.git pull/19518/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19518`

View PR using the GUI difftool: \
`$ git pr show -t 19518`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19518.diff">https://git.openjdk.org/jdk/pull/19518.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19518#issuecomment-2144880361)

### CODE REVIEW

**Review by theRealAph — COMMENTED** [review]
Mmm, interesting. Let me have a look at why these are there.

**Review by theRealAph — APPROVED** [review]
OK, it's some remnants of the Graal-based jaotc. Patch approved.

**Comment by kuaiwei** [comment]
> OK, it's some remnants of the Graal-based jaotc. Patch approved.

Thanks for quick review. Wait for another approve.

**Comment by kuaiwei** [comment]
> Looks good to me, too.

Thanks.

**Comment by kuaiwei** [comment]
@theRealAph @chhagedorn Could you help to sponsor it? Thanks.

**Comment by TheShermanTanker** [comment]
I'll help sponsor, but I'm a little concerned about the "⚠️ Found leading lowercase letter in issue title for 8333410: [AArch64] clean unused classes in nativeInst_aarch64.hpp" - Is that an issue?

**Comment by offamitkumar** [comment]
>"⚠️ Found leading lowercase letter in issue title for 8333410: [AArch64] clean unused classes in nativeInst_aarch64.hpp" - Is that an issue?

I think it's complaining because instead of `clean` it should have been `Clean`; That should not be a problem.

**Comment by TheShermanTanker** [comment]
Ok, good to know

**Comment by kuaiwei** [comment]
> I'll help sponsor, but I'm a little concerned about the "⚠️ Found leading lowercase letter in issue title for 8333410: [AArch64] clean unused classes in nativeInst_aarch64.hpp" - Is that an issue?

I didn't noticed the warning before. It can be fixed after changing title. Thanks.

**Comment by kuaiwei** [comment]
> /sponsor

Thanks

**Pull request closed without merging**
