### PR TITLE
8303810: Restore attribute positions after JDK-8303839 to match JDK-8302124

### PR DESCRIPTION
**Pull request by TheShermanTanker**
[JDK-8303839](https://bugs.openjdk.org/browse/JDK-8303839)'s revert of [[noreturn]] attributes also moved their already existing attributes back to behind their corresponding methods, they should be restored to where [JDK-8302124](https://bugs.openjdk.org/browse/JDK-8302124) requires them to be. Also fixes attribute from [JDK-8292269](https://bugs.openjdk.org/browse/JDK-8292269)

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303810](https://bugs.openjdk.org/browse/JDK-8303810): Restore attribute positions after JDK-8303839 to match JDK-8302124

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12918/head:pull/12918` \
`$ git checkout pull/12918`

Update a local copy of the PR: \
`$ git checkout pull/12918` \
`$ git pull https://git.openjdk.org/jdk pull/12918/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12918`

View PR using the GUI difftool: \
`$ git pr show -t 12918`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12918.diff">https://git.openjdk.org/jdk/pull/12918.diff</a>

</details>

### CODE REVIEW

**Comment by kimbarrett** [comment]
Please don't do this.  This change will just make the redo harder by introducing merge conflicts.

**Comment by dholmes-ora** [comment]
I agree with Kim. Thanks.

**Comment by TheShermanTanker** [comment]
Alright

**Pull request closed without merging**
