### PR TITLE
8281289: Improve with List.copyOf

### PR DESCRIPTION
**Pull request by XueleiFan**
Please review this trivial code clean up, for a little bit better performance.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281289](https://bugs.openjdk.java.net/browse/JDK-8281289): Improve with List.copyOf

### Reviewers
 * [Jamil Nimeh](https://openjdk.java.net/census#jnimeh) (@jnimeh - **Reviewer**)
 * [Hai-May Chao](https://openjdk.java.net/census#hchao) (@haimaychao - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7356/head:pull/7356` \
`$ git checkout pull/7356`

Update a local copy of the PR: \
`$ git checkout pull/7356` \
`$ git pull https://git.openjdk.java.net/jdk pull/7356/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7356`

View PR using the GUI difftool: \
`$ git pr show -t 7356`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7356.diff">https://git.openjdk.java.net/jdk/pull/7356.diff</a>

</details>

### CODE REVIEW

**Review by jnimeh — APPROVED** [review]
Looks good to me.

**Review by haimaychao — APPROVED** [review]

**Comment by haimaychao** [comment]
Looks good to me.

**Comment by XueleiFan** [comment]
/integrate

Thank you for the quick code review @jnimeh @haimaychao!

**Comment by cl4es** [comment]
There's a small compatibility risk with this change, e.g., `List.copyOf(...).contains(null)` will throw NPE while `Collections.unmodifiableList(...).contains(null)` won't.

If we accept that compatibility risk (which should probably be decided by CSR) it might also make sense to use `List.of()` for the empty case, which will reduce the number of List implementation classes returned from the API.

**Comment by XueleiFan** [comment]
> There's a small compatibility risk with this change, e.g., `List.copyOf(...).contains(null)` will throw NPE while `Collections.unmodifiableList(...).contains(null)` won't.
> 
> If we accept that compatibility risk (which should probably be decided by CSR) it might also make sense to use `List.of()` for the empty case, which will reduce the number of List implementation classes returned from the API.

All GOOD points!  Thanks!

I filed a new JDK-8281298, and a new [pull request](https://github.com/openjdk/jdk/pull/7359).

**Pull request closed without merging**
