### PR TITLE
8295315: [REDO] 8276687 Remove support for JDK 1.4.1 PerfData shared memory files

### PR DESCRIPTION
**Pull request by iklam**
Here's redo for https://github.com/openjdk/jdk/pull/10687. This PR has two commits:
- 739b79afb1965b625b2002187ac3fd43f385a639 is the same as in the original PR
- 78455c024ec5c00f1a0ce6c0e13df477c3063fe1 fixes the bug in the original PR.

I have run tiers 1 - 4 so hopefully I got it right this time :-)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295315](https://bugs.openjdk.org/browse/JDK-8295315): [REDO] 8276687 Remove support for JDK 1.4.1 PerfData shared memory files

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - Committer)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11094/head:pull/11094` \
`$ git checkout pull/11094`

Update a local copy of the PR: \
`$ git checkout pull/11094` \
`$ git pull https://git.openjdk.org/jdk pull/11094/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11094`

View PR using the GUI difftool: \
`$ git pr show -t 11094`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11094.diff">https://git.openjdk.org/jdk/pull/11094.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good!

Thanks.

**Review by kevinjwalls — APPROVED** [review]
Looks good to me!

**Review by sspitsyn — APPROVED** [review]
Nice cleanup.
Thanks,
Serguei

**Comment by iklam** [comment]
Thanks @dholmes-ora @kevinjwalls @sspitsyn for the review.
/integrate

**Pull request closed without merging**
