### PR TITLE
8316927: JFR: Move shouldCommit check earlier for socket events

### PR DESCRIPTION
**Pull request by egahlin**
Hi,

The events for socket read and socket write retrieves the remote address even in cases where the event didn't exceed the threshold. By moving the shouldCommit check earlier, it can be avoided. 

Testing: jdk/jdk/jfr

Thanks
Erik

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316927](https://bugs.openjdk.org/browse/JDK-8316927): JFR: Move shouldCommit check earlier for socket events (**Enhancement** - P3)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [3b398bc4](https://git.openjdk.org/jdk/pull/15908/files/3b398bc431da0a217dc43dbedbc1aa5e0df84e58)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to [3b398bc4](https://git.openjdk.org/jdk/pull/15908/files/3b398bc431da0a217dc43dbedbc1aa5e0df84e58)
 * [Markus Grönlund](https://openjdk.org/census#mgronlun) (@mgronlun - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15908/head:pull/15908` \
`$ git checkout pull/15908`

Update a local copy of the PR: \
`$ git checkout pull/15908` \
`$ git pull https://git.openjdk.org/jdk.git pull/15908/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15908`

View PR using the GUI difftool: \
`$ git pr show -t 15908`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15908.diff">https://git.openjdk.org/jdk/pull/15908.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15908#issuecomment-1734841304)

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
The update looks okay. For SC, remoteAddress() just returns the address, it doesn't create a new ISA each time, unlike the Socket code.

At some point I think we should re-format SocketReadEvent to reduce the wildly long lines as it's really hard to look at the changes side-by-side right now. We also need to update sun.nio.ch.Socket{Input,Output}Stream to emit events as they are currently missed so the events are incomplete.

**Comment by AlanBateman** [comment]
Changes in this area only require one reviewer so it's okay to integrate if you want.

**Review by dfuch — APPROVED** [review]
LGTM - I was expecting @tprinzing to review too, but yes you can integrate if you want.

**Comment by tprinzing** [comment]
I was planning to change the convenience function to take functions as arguments.  With this change there is a bunch of duplicated code.

I was planning to push the change for JDK-8310978 today, but I guess that will have to wait as it's impacted by this.

**Review by mgronlun — APPROVED** [review]

**Pull request closed without merging**
