### PR TITLE
8293254: x86_64: Extract arraycopy stub implementations into a separate file

### PR DESCRIPTION
**Pull request by iwanowww**
Move arraycopy stub implementations from `stubGenerator_x86_64.cpp` into `stubGenerator_x86_64_arraycopy.cpp`.

Testing: hs-tier1 - hs-tier4

PS: FTR I left `MacroAssembler::generate_fill_avx3()` intact because it is called from `MacroAssembler::generate_fill()` which is shared between x86_64 and x86_32. Otherwise, I would either need to copy `MacroAssembler::generate_fill()` or put it into a separate file (e.g., `stubGenerator_x86.cpp` or `stubGenerator_x86_arraycopy.cpp`). IMO it doesn't add much value compared to keeping it in `macroAssembler_x86.cpp`.

/cc hotspot

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293254](https://bugs.openjdk.org/browse/JDK-8293254): x86_64: Extract arraycopy stub implementations into a separate file

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to [e518a78d](https://git.openjdk.org/jdk/pull/10128/files/e518a78d1599dcbaf77a09b48fd1494094e5c7f6)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [e518a78d](https://git.openjdk.org/jdk/pull/10128/files/e518a78d1599dcbaf77a09b48fd1494094e5c7f6)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10128/head:pull/10128` \
`$ git checkout pull/10128`

Update a local copy of the PR: \
`$ git checkout pull/10128` \
`$ git pull https://git.openjdk.org/jdk pull/10128/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10128`

View PR using the GUI difftool: \
`$ git pr show -t 10128`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10128.diff">https://git.openjdk.org/jdk/pull/10128.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]
It seems OK, assuming there are no hidden changes, just cut and paste plus renames and adding "__ ".  Considering the number of lines changes, it would be hard for a reviewer to check all the lines without effectively reproducing all the steps.

**Review by vnkozlov — APPROVED** [review]
Good. I agree with you about not moving `generate_fill_avx3`.

**Comment by iwanowww** [comment]
> It seems OK, assuming there are no hidden changes, just cut and paste plus renames and adding "__ "

Yes. Except some additional formatting, it's copy-pasted code with "__" sprinkled where methods on `MacroAssembler` are invoked.

**Comment by iwanowww** [comment]
Thanks for the reviews, Dean and Vladimir.

/integrate

**Pull request closed without merging**
