### PR TITLE
8266426: ZHeapIteratorOopClosure does not handle native access properly

### PR DESCRIPTION
**Pull request by albertnetymk**
Change the inheritance hierarchy of `ZHeapIteratorOopClosure` so that we can know whether we are loading oops from in-heap or outside-heap (only CLD iteration).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266426](https://bugs.openjdk.java.net/browse/JDK-8266426): ZHeapIteratorOopClosure does not handle native access properly

### Reviewers
 * [Stefan Karlsson](https://openjdk.java.net/census#stefank) (@stefank - **Reviewer**)
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)

### Contributors
 * Per Liden `<pliden@openjdk.org>`
 * Erik Österlund `<eosterlund@openjdk.org>`
 * Stefan Karlsson `<stefank@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3838/head:pull/3838` \
`$ git checkout pull/3838`

Update a local copy of the PR: \
`$ git checkout pull/3838` \
`$ git pull https://git.openjdk.java.net/jdk pull/3838/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3838`

View PR using the GUI difftool: \
`$ git pr show -t 3838`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3838.diff">https://git.openjdk.java.net/jdk/pull/3838.diff</a>

</details>

### CODE REVIEW

**Review by stefank — CHANGES_REQUESTED** [review]
This adds an non-trivial is_in call to each visited oop*. I'd like to see if this could instead be solved by letting the used closure "know" when it scans CLDs, and only in that case use NativeAccess.

**Review by stefank — COMMENTED** [review]
Looks good

**Review by pliden — APPROVED** [review]
Looks good.

**Review by stefank — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thank you very much for the help on creating this patch.

/integrate

**Pull request closed without merging**
