### PR TITLE
8324286: Fix backsliding on use of nullptr instead of NULL

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that removes some new (since JDK-8299837) uses of
NULL in HotSpot code.  Most of the changes are in comments, replacing "NULL"
with either "nullptr" (for code snippets) or "null" (for textual description),
as was done for JDK-8299837.  There are a small number of new uses of NULL in
code, which are replaced with nullptr.

Testing: mach5 tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324286](https://bugs.openjdk.org/browse/JDK-8324286): Fix backsliding on use of nullptr instead of NULL (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17516/head:pull/17516` \
`$ git checkout pull/17516`

Update a local copy of the PR: \
`$ git checkout pull/17516` \
`$ git pull https://git.openjdk.org/jdk.git pull/17516/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17516`

View PR using the GUI difftool: \
`$ git pr show -t 17516`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17516.diff">https://git.openjdk.org/jdk/pull/17516.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17516#issuecomment-1903719751)

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good, can be argued as trivial.

**Review by TheShermanTanker — APPROVED** [review]
Easy change to review, so I might as well

**Comment by kimbarrett** [comment]
Thanks for reviews @jdksjolen , @coleenp , and @TheShermanTanker .

**Pull request closed without merging**
