### PR TITLE
8339644: Improve parsing of Day/Month in tzdata rules

### PR DESCRIPTION
**Pull request by naotoj**
Fixing TZDB build tool to accommodate full month/day names. Recently released tzdb2024b included (inadvertently) full month name "April", which is allowed by the spec (zic.8), but never used. This will cause build failure of the JDK. The proposed fix is manually tested by modifying the tzdb files to include full month names, and confirmed the successful build of the JDK.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339644](https://bugs.openjdk.org/browse/JDK-8339644): Improve parsing of Day/Month in tzdata rules (**Bug** - P4)

### Reviewers
 * [Justin Lu](https://openjdk.org/census#jlu) (@justin-curtis-lu - Committer)
 * [Sean Coffey](https://openjdk.org/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20893/head:pull/20893` \
`$ git checkout pull/20893`

Update a local copy of the PR: \
`$ git checkout pull/20893` \
`$ git pull https://git.openjdk.org/jdk.git pull/20893/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20893`

View PR using the GUI difftool: \
`$ git pr show -t 20893`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20893.diff">https://git.openjdk.org/jdk/pull/20893.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20893#issuecomment-2334549986)

### CODE REVIEW

**Review by justin-curtis-lu — APPROVED** [review]

**Review by coffeys — APPROVED** [review]
Thanks for fixing up. Looks good!

**Comment by naotoj** [comment]
Had to modify the fix. According to zic(8):
```
Names must be in English and are case insensitive.  They appear in several contexts, and include month and weekday names and keywords such as “maximum”, “only”, “Rolling”, and “Zone”.  A name can be abbreviated by omitting all but an initial prefix; any abbreviation must be unambiguous in context
```
Thus April can not only either "Apr" or "April", but also "apr", "april", "apri", or "Ap". The fix assumes the source tz files already have unbiguous names.

**Comment by justin-curtis-lu** [comment]
New fix LGTM.

> Month names may be abbreviated as mentioned previously;
> for example, January can appear as
> .q January ,
> .q JANU
> or
> .q Ja ,
> but not as
> .q j

So I think it's safe to assume unambiguous abbreviations.

**Review by justin-curtis-lu — APPROVED** [review]

**Review by coffeys — APPROVED** [review]

**Comment by naotoj** [comment]
Thanks for the reviews!
/integrate

**Pull request closed without merging**
