### PR TITLE
8299608: Add Register + imm32 orq to x86_64 assembler

### PR DESCRIPTION
**Pull request by fisk**
The current x86_64 orq Register + imm32 uses emit_arith, which is rather clever and checks if it can use imm8 instead. However, sometimes you really want it to be imm32 regardless, for example if you are going to patch the code. Such functionality should be added.

Since there seems to be a precedent distinguishing this with testl_imm32(Register, imm32) vs testl(Register, imm32), my proposed patch similarly adds an orq_imm32 that uses emit_arith_imm32.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299608](https://bugs.openjdk.org/browse/JDK-8299608): Add Register + imm32 orq to x86_64 assembler

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [c7f6e63c](https://git.openjdk.org/jdk/pull/11850/files/c7f6e63c65e82c9992f64e32787b19dff249a2e7)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to [c7f6e63c](https://git.openjdk.org/jdk/pull/11850/files/c7f6e63c65e82c9992f64e32787b19dff249a2e7)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [c7f6e63c](https://git.openjdk.org/jdk/pull/11850/files/c7f6e63c65e82c9992f64e32787b19dff249a2e7)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11850/head:pull/11850` \
`$ git checkout pull/11850`

Update a local copy of the PR: \
`$ git checkout pull/11850` \
`$ git pull https://git.openjdk.org/jdk pull/11850/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11850`

View PR using the GUI difftool: \
`$ git pr show -t 11850`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11850.diff">https://git.openjdk.org/jdk/pull/11850.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks okay.

(Also, it is that time of the year when even the simplest patches come with copyright year updates...)

**Review by sviswa7 — APPROVED** [review]
LGTM

**Review by vnkozlov — APPROVED** [review]
Godd.

**Comment by fisk** [comment]
Thanks for the reviews @shipilev, @sviswa7 and @vnkozlov!

**Pull request closed without merging**
