### PR TITLE
8255822: Zero: improve build-time JVMTI handling

### PR DESCRIPTION
**Pull request by shipilev**
Current Zero interpreter has the optimization for JVMTI support. It recognizes that JVMTI is disabled most of the time, and that JVMTI checks in the interpreter code slows it down considerably. (I measured it myself when working on this patch: removing this optimization yields about 20% hit in build times).

Current optimization works as follows. At build time, an XSLT transform is performed on `bytecodeInterpreter.cpp`, yielding `bytecodeInterpreterWithChecks.cpp`. In that new compilation unit, `VM_JVMTI` macro is defined, and a new entry point -- `BytecodeInterpreter::withChecks` -- is defined. Then, both compilation units are compiled. In one of them, `JVMTI` hooks are stripped out. In another, they persist. Then, callers have to choose which entry point to use.

I believe this can be rewritten to use C++ templates instead of XLST and defines dance. This also allows to clean up JVMTI checks a bit.

Additional testing:
 - [x] Linux x86_64 Zero fastdebug build with `-jvmti`
 - [x] Linux x86_64 Zero fastdebug/release build times are not regressing

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255822](https://bugs.openjdk.java.net/browse/JDK-8255822): Zero: improve build-time JVMTI handling

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to 0907c06e55b5a89d7929f8a79b5764dd269d7065

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1061/head:pull/1061`
`$ git checkout pull/1061`

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
This looks like a good cleanup to me - far simpler!

Cheers,
David

**Review by magicus — APPROVED** [review]
Looks good to me. Thanks for the cleanup!

**Review by dholmes-ora — APPROVED** [review]
Still good.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
