### PR TITLE
8330191: Fix typo in precompiled.hpp

### PR DESCRIPTION
**Pull request by caspernorrbin**
Hi all,

The file `precompiled.hpp` has a typo in it, which this PR fixes.

Please consider this PR, thank you!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330191](https://bugs.openjdk.org/browse/JDK-8330191): Fix typo in precompiled.hpp (**Enhancement** - P4)

### Reviewers
 * [Johan Sjölen](https://openjdk.org/census#jsjolen) (@jdksjolen - **Reviewer**)
 * [Sonia Zaldana Calles](https://openjdk.org/census#szaldana) (@SoniaZaldana - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20466/head:pull/20466` \
`$ git checkout pull/20466`

Update a local copy of the PR: \
`$ git checkout pull/20466` \
`$ git pull https://git.openjdk.org/jdk.git pull/20466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20466`

View PR using the GUI difftool: \
`$ git pr show -t 20466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20466.diff">https://git.openjdk.org/jdk/pull/20466.diff</a>

</details>

### CODE REVIEW

**Review by jdksjolen — APPROVED** [review]
Looks good to me.

Thank you, @SoniaZaldana, for noticing the copyright year. You are still very much allowed to perform code reviews, even though you're a Committer. The key rule to remember is that a PR *must* have been reviewed by a *R*eviewer before it can get integrated, but a Committer still count towards the "minimum 2 reviewers" rule.

In other words, could you please approve this PR if you think it looks OK :-)?

**Review by SoniaZaldana — APPROVED** [review]
LGTM. 

In the future, you can use the [update_copyright_year.sh](https://github.com/openjdk/jdk/blob/master/make/scripts/update_copyright_year.sh) script to handle those for you.

**Comment by caspernorrbin** [comment]
Thank you both! @SoniaZaldana & @jdksjolen. I did not know that this script existed, will surely come handy in the future :)

/integrate

**Pull request closed without merging**
