### PR TITLE
8320699: Add parameter to skip progress logging of OutputAnalyzer

### PR DESCRIPTION
**Pull request by stefank**
Tests using ProcessTools.executeProcess gets the following output written to stdout:
[2023-11-24T09:58:16.797540608Z] Gathering output for process 2517117
[2023-11-24T09:58:23.070781345Z] Waiting for completion for process 2517117
[2023-11-24T09:58:23.071045055Z] Waiting for completion finished for process 2517117

This might be good for some use cases and debugging, but some tests spawns a large number of processes and for those this output fills up the log files.

I propose that we add a way to turn of this output for tests where we find this output to be too noisy.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320699](https://bugs.openjdk.org/browse/JDK-8320699): Add parameter to skip progress logging of OutputAnalyzer (**Enhancement** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [9a43b2c9](https://git.openjdk.org/jdk/pull/16807/files/9a43b2c985acad0765013a01bffabaa42698a3f1)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [d0091eb6](https://git.openjdk.org/jdk/pull/16807/files/d0091eb6c1bcd0e0cae3630fcb6bc8b73fdf24e4)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**) ⚠️ Review applies to [9a43b2c9](https://git.openjdk.org/jdk/pull/16807/files/9a43b2c985acad0765013a01bffabaa42698a3f1)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16807/head:pull/16807` \
`$ git checkout pull/16807`

Update a local copy of the PR: \
`$ git checkout pull/16807` \
`$ git pull https://git.openjdk.org/jdk.git pull/16807/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16807`

View PR using the GUI difftool: \
`$ git pr show -t 16807`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16807.diff">https://git.openjdk.org/jdk/pull/16807.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16807#issuecomment-1825472442)

### CODE REVIEW

**Comment by stefank** [comment]
This has been tested with an Oracle-internal stress tests.

**Comment by dholmes-ora** [comment]
I can't help but feel that if you disable this output then you are going to be missing it in the cases that you need it! Something will go wrong and there won't be enough info in the log to know what it was.

**Comment by stefank** [comment]
> I can't help but feel that if you disable this output then you are going to be missing it in the cases that you need it! Something will go wrong and there won't be enough info in the log to know what it was.

My experience is that I won't need it. I've been able to identify numerous hangs, deadlocks, timeouts in the stress tests where I want to use this. Right now I much more annoyed by the log files filling up with thousands upon thousands lines of noise, making it harder to actually find the status of the test.

An alternative to this could be to redirect the output to another file.

**Comment by tstuefe** [comment]
I'm fine with this, but would prefer a global switch instead of hard-coding the value per test and handing it down.

**Comment by jaikiran** [comment]
Hello Stefan, I agree with David that I have found these logs to be useful - it shows that process launched by the test hasn't yet finished and is being waited upon. The log message when written will have a timestamp and can then also help to quickly understand how long it could have taken for this process to complete.

> Right now I much more annoyed by the log files filling up with thousands upon thousands lines of noise, making it harder to actually find the status of the test.

This I agree with. It's a co-incidence that just this week when I was looking at some test logs I happened to see such large amount of unexpected logging (not thousands, but large enough). For example:

```
[2023-11-24T11:47:54.557561Z] Waiting for completion for process 24909
[2023-11-24T11:47:54.557873Z] Waiting for completion finished for process 24909
[2023-11-24T11:47:54.612609Z] Waiting for completion for process 24909
[2023-11-24T11:47:54.612682Z] Waiting for completion finished for process 24909
[2023-11-24T11:47:54.614500Z] Waiting for completion for process 24909
[2023-11-24T11:47:54.614542Z] Waiting for completion finished for process 24909
[2023-11-24T11:47:54.640945Z] Waiting for completion for process 24909
[2023-11-24T11:47:54.641115Z] Waiting for completion finished for process 24909
```
I wonder if something else is going on here, because looking at these logs messages it says that it has finished waiting for a process 24909, yet it keeps repeating those messages. I would have expected it to stop logging after the first:

```
Waiting for completion finished for process 24909
```
I haven't yet had a chance to look at the code to see if there's some bug which is contributing to this extensive logging.

**Comment by jaikiran** [comment]
Perhaps this would help improve/fix the log flooding:

```diff
diff --git a/test/lib/jdk/test/lib/process/OutputBuffer.java b/test/lib/jdk/test/lib/process/OutputBuffer.java
index 3741ccbe2ff..02aedf29f6a 100644
--- a/test/lib/jdk/test/lib/process/OutputBuffer.java
+++ b/test/lib/jdk/test/lib/process/OutputBuffer.java
@@ -120,6 +120,7 @@ public String get() {
     private final StreamTask outTask;
     private final StreamTask errTask;
     private final Process p;
+    private volatile Integer processExitCode; // null represents process hasn't yet exited
 
     private final void logProgress(String state) {
         System.out.println("[" + Instant.now().toString() + "] " + state
@@ -146,14 +147,18 @@ public String getStderr() {
 
     @Override
     public int getExitValue() {
+      Integer exitCode = this.processExitCode;
+      if (exitCode != null) {
+        return exitCode;
+      }
       try {
           logProgress("Waiting for completion");
           boolean aborted = true;
           try {
-              int result = p.waitFor();
+              processExitCode = exitCode = p.waitFor();
               logProgress("Waiting for completion finished");
               aborted = false;
-              return result;
+              return exitCode;
           } finally {
               if (aborted) {
                   logProgress("Waiting for completion FAILED");
```

Other than a quick local test run, I haven't tested it for anything else. It did improve the situation in one of my test and it now only logs it once. In the setup that you are seeing this large amount of logging, would you be able to see if this change helps there too?

**Comment by dholmes-ora** [comment]
@jaikiran that looks like a good fix to me. It doesn't make sense to keep repeating the logging on every `getExitValue` call. Good find!

**Comment by stefank** [comment]
> Other than a quick local test run, I haven't tested it for anything else. It did improve the situation in one of my test and it now only logs it once. In the setup that you are seeing this large amount of logging, would you be able to see if this change helps there too?

The place where I would like to use it we repeatedly spawn a number of different processes to inspect the JVM and the OS. So, I think you have found a separate issue.

**Comment by stefank** [comment]
> Hello Stefan, I agree with David that I have found these logs to be useful - it shows that process launched by the test hasn't yet finished and is being waited upon. The log message when written will have a timestamp and can then also help to quickly understand how long it could have taken for this process to complete.

The test were I want to use this is a long-running stress test that is known to be good at shaking out JVM hangs. It has been written to provide its own output about spawned processes and what they are doing, and have that info written to appropriate files. For me, the OutputAnalyzer logging just adds redundant output to the streams where I don't want the information.

When we do have JVM hangs in these larger tests it's usually is easier to look at the output generated from [test/failure_handler](https://github.com/openjdk/jdk/tree/master/test/failure_handler).

**Comment by jaikiran** [comment]
Hello Stefan,

> The test were I want to use this is a long-running stress test that is known to be good at shaking out JVM hangs. It has been written to provide its own output about spawned processes and what they are doing, and have that info written to appropriate files. For me, the OutputAnalyzer logging just adds redundant output to the streams where I don't want the information.

Thank you for that context. What you are then proposing is for a way to reuse this utility class in specific tests, like the one you are working on, without needing the progress logs. So the idea isn't really to use this new API in all newly developed tests which use this `ProcessTools` library. Plus the implementation in this PR, retains the existing behaviour of logging the progress by default, which is a good thing.

Given that context, I don't have any objection in introducing this enhancemnet. During future reviews, I think, it wouldn't be too difficult to catch misuses of this new API in newer tests where the progress logs shouldn't be disabled.

As for whether this "config" should be externalized - I think it shouldn't be, since whether or not the progress logs will be excessive and too distracting (and thus need to be disabled) would be known at test development time itself.

**Comment by jaikiran** [comment]
> So, I think you have found a separate issue.

I'll open a separate issue for that and propose a change.

**Comment by jaikiran** [comment]
The copyright year on `OutputBuffer.java` will need an update.

**Comment by stefank** [comment]
> Hello Stefan,
> 
> > The test were I want to use this is a long-running stress test that is known to be good at shaking out JVM hangs. It has been written to provide its own output about spawned processes and what they are doing, and have that info written to appropriate files. For me, the OutputAnalyzer logging just adds redundant output to the streams where I don't want the information.
> 
> Thank you for that context. What you are then proposing is for a way to reuse this utility class in specific tests, like the one you are working on, without needing the progress logs. So the idea isn't really to use this new API in all newly developed tests which use this `ProcessTools` library. Plus the implementation in this PR, retains the existing behaviour of logging the progress by default, which is a good thing.

Yes, you summarize this well.

> 
> Given that context, I don't have any objection in introducing this enhancemnet. During future reviews, I think, it wouldn't be too difficult to catch misuses of this new API in newer tests where the progress logs shouldn't be disabled.

Yes, I agree. It would be quite obvious if someone tries to turn this off.

> 
> As for whether this "config" should be externalized - I think it shouldn't be, since whether or not the progress logs will be excessive and too distracting (and thus need to be disabled) would be known at test development time itself.

I agree.

> The copyright year on OutputBuffer.java will need an update.

Fixed.

Thanks for taking a look at this!

**Review by jaikiran — APPROVED** [review]
These changes look good to me. Please wait for another review before integrating.

**Review by dholmes-ora — APPROVED** [review]
Okay.

Thanks

**Review by jaikiran — APPROVED** [review]
Still looks fine.

**Review by lmesnik — APPROVED** [review]
Needed to update copyrights now.

**Comment by stefank** [comment]
> Needed to update copyrights now.

Even when the code was written in 2023?

**Comment by lmesnik** [comment]
I think that commit is going to have date in 2024. So any check is going to compare this date and copyright year. It shouldn't cause fail i CI and files are going to be updated later with  verification scripts.

**Review by dfuch — APPROVED** [review]
Hi Stefan - I see that this is an opt-in, so LGTM

**Pull request closed without merging**
