### PR TITLE
JDK-8324238 : [macOS] java/awt/Frame/ShapeNotSetSometimes/ShapeNotSetSometimes.java fails with the shape has not been applied msg

### PR DESCRIPTION
**Pull request by honkar-jdk**
ShapeNotSetSometimes.java fails on macOS 11 on a random iteration of `colorCheck()` as shown below. The `colorCheck()` is repeated for about 50 times in the test. It is observed to pass on previous attempts and fail on a random attempt such as Attempt# 29 shown here.

Here the point (150, 20) is well in the green area hence the slight color diff picked up by `robot.getPixelColor()` is not due to sampling of color at the edge (which sometimes causes robot to pick up slightly different color).  

```
Attempt 29
Checking 150, 20, java.awt.Color[r=0,g=255,b=1] should be java.awt.Color[r=0,g=255,b=0]
```

Due to the above, I have kept the color sampling points at the same location as earlier and made the following changes to the test:

- Moved the frame to the center of the screen.
- Instead of comparing exact RGB values, used `colorCompare()` which allows color tolerance of 2 per color component to accommodate slight variations when comparing actual vs expected colors.

```
Attempt 27
Checking 150, 130, java.awt.Color[r=255,g=255,b=255] should be java.awt.Color[r=255,g=255,b=255]
Checking 150, 20, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 280, 120, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 150, 250, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 20, 120, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 62, 62, java.awt.Color[r=0,g=243,b=0] should not be java.awt.Color[r=255,g=255,b=255]
Checking 240, 185, java.awt.Color[r=0,g=229,b=0] should not be java.awt.Color[r=255,g=255,b=255]
Attempt 28
Checking 150, 130, java.awt.Color[r=255,g=255,b=255] should be java.awt.Color[r=255,g=255,b=255]
Checking 150, 20, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 280, 120, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 150, 250, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 20, 120, java.awt.Color[r=0,g=255,b=0] should be java.awt.Color[r=0,g=255,b=0]
Checking 62, 62, java.awt.Color[r=0,g=241,b=0] should not be java.awt.Color[r=255,g=255,b=255]
Checking 240, 185, java.awt.Color[r=0,g=227,b=0] should not be java.awt.Color[r=255,g=255,b=255]
Attempt 29
Checking 150, 130, java.awt.Color[r=255,g=255,b=255] should be java.awt.Color[r=255,g=255,b=255]
Checking 150, 20, java.awt.Color[r=0,g=255,b=1] should be java.awt.Color[r=0,g=255,b=0]
----------System.err:(16/962)----------
Checking for transparency failed: point: 370, 420
actual java.awt.Color[r=0,g=255,b=1]
expected java.awt.Color[r=0,g=255,b=0]
java.lang.RuntimeException: Test failed. The shape has not been applied. 
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324238](https://bugs.openjdk.org/browse/JDK-8324238): [macOS] java/awt/Frame/ShapeNotSetSometimes/ShapeNotSetSometimes.java fails with the shape has not been applied msg (**Bug** - P4)

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.org/census#azvegint) (@azvegint - **Reviewer**)
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17563/head:pull/17563` \
`$ git checkout pull/17563`

Update a local copy of the PR: \
`$ git checkout pull/17563` \
`$ git pull https://git.openjdk.org/jdk.git pull/17563/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17563`

View PR using the GUI difftool: \
`$ git pr show -t 17563`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17563.diff">https://git.openjdk.org/jdk/pull/17563.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17563#issuecomment-1909183997)

### CODE REVIEW

**Review by azvegint — APPROVED** [review]

**Review by DamonGuy — APPROVED** [review]
Changes LGTM

**Comment by honkar-jdk** [comment]
I missed pushing the latest update to the test previously. Added it.

**Review by DamonGuy — APPROVED** [review]
I took the latest changes and ran the test again multiple times. Newest changes look like minor stability changes. Still passes. LGTM

**Review by azvegint — APPROVED** [review]

**Pull request closed without merging**
