### PR TITLE
JDK-8293093 NPE in P11KeyStore.getID

### PR DESCRIPTION
**Pull request by mcpowers**
https://bugs.openjdk.org/browse/JDK-8293093

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293093](https://bugs.openjdk.org/browse/JDK-8293093): NPE in P11KeyStore.getID

### Reviewers
 * [Anthony Scarpino](https://openjdk.org/census#ascarpino) (@ascarpino - **Reviewer**)
 * [Xue-Lei Andrew Fan](https://openjdk.org/census#xuelei) (@XueleiFan - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10823/head:pull/10823` \
`$ git checkout pull/10823`

Update a local copy of the PR: \
`$ git checkout pull/10823` \
`$ git pull https://git.openjdk.org/jdk pull/10823/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10823`

View PR using the GUI difftool: \
`$ git pr show -t 10823`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10823.diff">https://git.openjdk.org/jdk/pull/10823.diff</a>

</details>

### CODE REVIEW

**Comment by mcpowers** [comment]
I was finally able to reproduce this failure and was able to verify the fix. Took forever.

**Comment by efge** [comment]
Given the repeated code wouldn't you want to create a small helper method like `getIDNullSafe`?

**Comment by XueleiFan** [comment]
There are some other places, for example in updatePkey(), that use cka_id.  Did you have a chance to check if NPE is possible there as well?

**Comment by ascarpino** [comment]
Looking at the usage of getID(), it seems like debug msgs and exceptions are where the null maybe a problem.  mapLabel() checks for null.  It maybe best to change getID(bytes[]) to return new String("null") then having if() checks for the return value.

**Comment by seanjmullan** [comment]
You should add a `noreg` label (ex: `noreg-trivial` or `noreg-other`) to the bug if you don't plan on writing a regression test.

**Comment by mcpowers** [comment]
@efge Good suggestion. And having `NullSafe` in the name answers an important question.

@XueleiFan Regarding `updatePkey`, `getID` is only used for exception messages. I'm going to use `getIDNullSafe` to prevent an unexpected exception doesn't throw yet another exception.

@ascarpino Agreed.

@seanjmullan `noreg-trivial`

**Comment by XueleiFan** [comment]
@mcpowers Did you want to update line line 203-207 as well?  It might be safe to remove the current getID(byte[]) method.  If the parameter is null, there is an NPE (unexpected); otherwise, the new method should be safe to use.

**Comment by mcpowers** [comment]
@XueleiFan Lines 204 and 206 can't be collapsed into a single call to getIDNullSafe because of square brackets in the output on line 204. I don't want to change existing output in any way. Perhaps I'm not understanding your question.

**Comment by XueleiFan** [comment]
> @XueleiFan Lines 204 and 206 can't be collapsed into a single call to getIDNullSafe because of square brackets in the output on line 204. I don't want to change existing output in any way. Perhaps I'm not understanding your question.

I just feel that it may be not necessary to maintain both getID() and getIDNullSafe().  But no problem if you want to keep the square brackets for toString().

**Review by XueleiFan — APPROVED** [review]

**Comment by mcpowers** [comment]
@XueleiFan Thanks for reviewing this!

**Pull request closed without merging**
