### PR TITLE
More compact header format for small, compressed entries

### PR DESCRIPTION
**Pull request by cl4es**
This draft experiment compresses the `CompressedResourceHeader` from 29 to 12 bytes when all header metadata fits in 16 bits. 

On an image generated with `jlink --compress zip-6 --add-modules java.se,jdk.unsupported,jdk.management`, `lib/modules` shrinks from `33278599` to `32965514`, or a 0.94% space saving.

No significant difference on `org.openjdk.bench.jdk.jimage.Decompress.test`. 

The jimage tool will still be able to read images generated before this patch.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17433/head:pull/17433` \
`$ git checkout pull/17433`

Update a local copy of the PR: \
`$ git checkout pull/17433` \
`$ git pull https://git.openjdk.org/jdk.git pull/17433/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17433`

View PR using the GUI difftool: \
`$ git pr show -t 17433`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17433.diff">https://git.openjdk.org/jdk/pull/17433.diff</a>

</details>

### CODE REVIEW

**Comment by Glavo** [comment]
Share some trivial results I got when developing the [JApp](https://github.com/Glavo/japp) project:

I repackage the cli of the [aya language](https://github.com/aya-prover/aya-dev) into JApp format:

* Only use zstd (compression level 8) to compress resource content: 6.40MiB
* Also use zstd to compress file metadata (resource headers): 6.13MiB
* Use zstd to compress file metadata and non-class file resources, and use zstd and string sharing compressed class files: 5.08MiB

The compression ratios of zstd-8 and  deflate-6 are close, but compression and decompression are much faster.

**Comment by cl4es** [comment]
> The compression ratios of zstd-8 and deflate-6 are close, but compression and decompression are much faster.

Integrating zstd into the openjdk and using it for jimage would be great, no argument there. Especially for compressing data. If it's profitable for compressing these 25-byte metadata headers remain to be seen. deflate-6 can get 25 bytes like this down to maybe 17-19 bytes; a minified 8 byte header (with no measurable(?) overhead) like in this draft might be hard to beat.

**Comment by Glavo** [comment]
> > The compression ratios of zstd-8 and deflate-6 are close, but compression and decompression are much faster.
> 
> Integrating zstd into the openjdk and using it for jimage would be great, no argument there. Especially for compressing data. If it's profitable for compressing these 25-byte metadata headers remain to be seen. deflate-6 can get 25 bytes like this down to maybe 17-19 bytes; a minified 8 byte header (with no measurable(?) overhead) like in this draft might be hard to beat.

I just realized that the resource header in jimage is stored together with the resource content, so the above experience may not apply. 

In JApp, I compress the metadata of all resources in a module together, so the file size is small. But I'm not sure if there is a negative impact on startup time, so jimage may not be able to apply it.

**Comment by cl4es** [comment]
Merged with master after integration of #17443 which made the `contentOffset` field redundant. This allows trimming another 2 bytes from the new header, which equates to a marginally better space saving:

```
jlink --compress=zip-6 --add-modules jdk.compiler,java.se,jdk.unsupported,jdk.management,jdk.jfr,jdk.jcmd
lib/modules 37459449 -> 37072982, -1.03%
```

**Pull request closed without merging**
