### PR TITLE
8342823: Ubsan: ciEnv.cpp:1614:65: runtime error: member call on null pointer of type 'struct CompileTask'

### PR DESCRIPTION
**Pull request by MBaesken**
When running with ubsanized binaries on Linux x86_64,
hs jtreg test compiler/startup/StartupOutput.java
showed this issue

jdk/src/hotspot/share/ci/ciEnv.cpp:1614:65: runtime error: member call on null pointer of type 'struct CompileTask'
    #0 0x7fcea0810117 in ciEnv::dump_replay_data_helper(outputStream*) src/hotspot/share/ci/ciEnv.cpp:1614
    #1 0x7fcea3123577 in VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) src/hotspot/share/utilities/vmError.cpp:1872
    #2 0x7fcea0c01499 in report_fatal(VMErrorType, char const*, int, char const*, ...) src/hotspot/share/utilities/debug.cpp:214
    #3 0x7fcea09e9d85 in RuntimeStub::new_runtime_stub(char const*, CodeBuffer*, short, int, OopMapSet*, bool, bool) src/hotspot/share/code/codeBlob.cpp:413
    #4 0x7fcea066da1d in Runtime1::generate_blob(BufferBlob*, C1StubId, char const*, bool, StubAssemblerCodeGenClosure*) src/hotspot/share/c1/c1_Runtime1.cpp:233
    #5 0x7fcea066dfb0 in Runtime1::generate_blob_for(BufferBlob*, C1StubId) src/hotspot/share/c1/c1_Runtime1.cpp:262
    #6 0x7fcea066dfb0 in Runtime1::initialize(BufferBlob*) src/hotspot/share/c1/c1_Runtime1.cpp:272
    #7 0x7fcea03d2be1 in Compiler::init_c1_runtime() src/hotspot/share/c1/c1_Compiler.cpp:53
    #8 0x7fcea03d2be1 in Compiler::initialize() src/hotspot/share/c1/c1_Compiler.cpp:74
    #9 0x7fcea0acc0c2 in CompileBroker::init_compiler_runtime() src/hotspot/share/compiler/compileBroker.cpp:1771
    #10 0x7fcea0ad9a3f in CompileBroker::compiler_thread_loop() src/hotspot/share/compiler/compileBroker.cpp:1913
    #11 0x7fcea161264a in JavaThread::thread_main_inner() src/hotspot/share/runtime/javaThread.cpp:759
    #12 0x7fcea2ec739a in Thread::call_run() src/hotspot/share/runtime/thread.cpp:234
    #13 0x7fcea251e1d2 in thread_native_entry src/hotspot/os/linux/os_linux.cpp:858
    #14 0x7fcea7c6c6e9 in start_thread (/lib64/libpthread.so.0+0xa6e9) (BuildId: 1b515766201d47a183932ba0c8c8bd0d9ee8755b)
    #15 0x7fcea730f58e in clone (/lib64/libc.so.6+0x11858e) (BuildId: 448a3ddd22596e1adb8fb3dec8921ed5b9d54dc2)

So a nullptr check should be better added .

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342823](https://bugs.openjdk.org/browse/JDK-8342823): Ubsan: ciEnv.cpp:1614:65: runtime error: member call on null pointer of type 'struct CompileTask' (**Bug** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21684/head:pull/21684` \
`$ git checkout pull/21684`

Update a local copy of the PR: \
`$ git checkout pull/21684` \
`$ git pull https://git.openjdk.org/jdk.git pull/21684/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21684`

View PR using the GUI difftool: \
`$ git pr show -t 21684`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21684.diff">https://git.openjdk.org/jdk/pull/21684.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21684#issuecomment-2435398133)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by dean-long** [comment]
There's not much point in generating an incomplete replay file.  How about moving the checks for this->task() to the top of the function?  And we could avoid the call altogether by changing VMError::report_and_die() from:
```
1864      ciEnv* env = ciEnv::current();
1865      if (env != nullptr) {
```
to
```
1864      ciEnv* env = ciEnv::current();
1865      if (env != nullptr && env->task() != nullptr) {
```

**Comment by MBaesken** [comment]
>  How about moving the checks for this->task() to the top of the function? 

Makes sense, better check just once .

**Comment by vnkozlov** [comment]
I think we should do the check in `VMError::report_and_die()` to avoid creating empty replay file.
Note, `dump_replay_data_unsafe()` is called only in that one place.
An other path through `dump_replay_data()` call required Compilation ID which is set only when we have task.
We can use assert instead of check in `ciEnv::dump_replay_data_helper()`.

**Comment by MBaesken** [comment]
> I think we should do the check in `VMError::report_and_die()` to avoid creating empty replay file. Note, `dump_replay_data_unsafe()` is called only in that one place. An other path through `dump_replay_data()` call required Compilation ID which is set only when we have task. We can use assert instead of check in `ciEnv::dump_replay_data_helper()`.

I moved the check and added an assert .

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by MBaesken** [comment]
Hi Vladimir and Martin, thanks for the reviews !

/integrate

**Pull request closed without merging**
