### PR TITLE
8266765: [BACKOUT] JDK-8255493 Support for pre-generated java.lang.invoke classes in CDS dynamic archive

### PR DESCRIPTION
**Pull request by yminqi**
Hi, Please review
  JDK-8255493 integration caused failures tier2/tier3 on test ParallelLambdaLoad.java which not caught in pre-integration tests. Since fix need more time, decided to back out the original fix.
  Tests: tier1,tier2,tier3,tier4

Thanks
Yumin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266765](https://bugs.openjdk.java.net/browse/JDK-8266765): [BACKOUT] JDK-8255493 Support for pre-generated java.lang.invoke classes in CDS dynamic archive

### Reviewers
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3932/head:pull/3932` \
`$ git checkout pull/3932`

Update a local copy of the PR: \
`$ git checkout pull/3932` \
`$ git pull https://git.openjdk.java.net/jdk pull/3932/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3932`

View PR using the GUI difftool: \
`$ git pr show -t 3932`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3932.diff">https://git.openjdk.java.net/jdk/pull/3932.diff</a>

</details>

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
Backout looks good.

**Comment by yminqi** [comment]
> Backout looks good.
Thanks for quick review!

**Pull request closed without merging**
