### PR TITLE
8258813: [TESTBUG] Fix incorrect Vector API test output message

### PR DESCRIPTION
**Pull request by XiaohongGong**
Some vector api tests have incorrect output messages if assertion fails. The root cause is the improper use of `"org.testng.Assert.assertEqual()"`, whose definition with int type is:
```
assertEquals(int actual, int expected, String message);
```

The method needs the actual value be used as the first argument and expected value as the second one. But in some vector api tests, the two arguments are swapped.

For example, here is part of the fail log in VectorReshapeTests we met:
```
 expect: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
 output: [1, 2, 3, 4, 5, 6, 7, 8, 1, 0, 0, 0, 0, 0, 0, 0]
 test VectorReshapeTests.testRebracket128(byte(i)): failure
 java.lang.AssertionError: arrays differ firstly at element [8]; expected value is <1> but was <9>.
   at org.testng.Assert.fail(Assert.java:94)
   at org.testng.Assert.assertEquals(Assert.java:774)
   ...
```

The assertion error should be `"...expected value is <9> but was <1>."`

This does not influence on the test effectiveness. However, the incorrect message is confusing which might mislead people. The simple fix is just to swap the arguments back.

This patch also adjusts the arguments order of all the assertion methods to make the actual values used as the first one. Besides, it also removes two unused assertion methods.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258813](https://bugs.openjdk.java.net/browse/JDK-8258813): [TESTBUG] Fix incorrect Vector API test output message

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**) ⚠️ Review applies to c3fb298644cb549c79ed9853241534cb42cba4d2
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1922/head:pull/1922`
`$ git checkout pull/1922`

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
Thank you for fixing this. So easy to get mixed up between TestNG and JUnit!

It's tempting to change the parameter names of the assert methods to be named `expected` and `accepted`, i'll consider doing that rather than impose that on you.

**Comment by XiaohongGong** [comment]
> Thank you for fixing this. So easy to get mixed up between TestNG and JUnit!
> 
> It's tempting to change the parameter names of the assert methods to be named `expected` and `accepted`, i'll consider doing that rather than impose that on you.

Hi @PaulSandoz, thanks so much for looking at this PR. And I'm so sorry that I forgot to update the copyright to the new year. I'v    committed one more patch to fix them. Do you mind having a looking at it again? Many thanks!

**Review by nsjian — APPROVED** [review]
Looks good to me.

**Comment by PaulSandoz** [comment]
> > Thank you for fixing this. So easy to get mixed up between TestNG and JUnit!
> > It's tempting to change the parameter names of the assert methods to be named `expected` and `accepted`, i'll consider doing that rather than impose that on you.
> 
> Hi @PaulSandoz, thanks so much for looking at this PR. And I'm so sorry that I forgot to update the copyright to the new year. I'v committed one more patch to fix them. Do you mind having a looking at it again? Many thanks!

Copyright changes look good.

**Pull request closed without merging**
