### PR TITLE
8330755: ProblemList files have entries referring to non-existent tests

### PR DESCRIPTION
**Pull request by dougxc**
This PR adds a check for the format of ProblemList files and ensures they only have entries referring to existing tests.

The cleanups in the second commit of this PR were done based on the output of `CheckProblemLists`:
```
> make test TEST=build/problemLists/CheckProblemLists.java
...
STDOUT:
Checking /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList-Virtual.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList-Xcomp.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList-generational-zgc.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList-zgc.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jaxp/ProblemList.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-Virtual.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-Xcomp.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-generational-zgc.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-zgc.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/langtools/ProblemList.txt
Checking /Users/dnsimon/dev/jdk-jdk/open/test/lib-test/ProblemList.txt
Checked 13 problem list files
Test roots:
  /Users/dnsimon/dev/jdk-jdk/open/test/jdk
  /Users/dnsimon/dev/jdk-jdk/open/test/lib-test
  /Users/dnsimon/dev/jdk-jdk/open/test/failure_handler/test
  /Users/dnsimon/dev/jdk-jdk/open/test/jaxp
  /Users/dnsimon/dev/jdk-jdk/open/test/langtools
  /Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg
Following errors found:
/Users/dnsimon/dev/jdk-jdk/open/test/hotspot/jtreg/ProblemList.txt:174: vmTestbase/gc/lock/jni/jnilock002/TestDescription.java does not exist under any test root
vmTestbase/gc/lock/jni/jnilock002/TestDescription.java 8192647 generic-all

/Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-Virtual.txt:77: TestAndIssue[test=java/util/Properties/StoreReproducibilityTest.java, issueId=0000000] duplicates /Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList-Virtual.txt:76
java/util/Properties/StoreReproducibilityTest.java 0000000 generic-all

/Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList.txt:516: java/lang/management/MemoryMXBean/PendingAllGC.sh does not exist under any test root
java/lang/management/MemoryMXBean/PendingAllGC.sh               8158837 generic-all

/Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList.txt:667: javax/swing/JFileChooser/6798062/bug6798062.java does not exist under any test root
javax/swing/JFileChooser/6798062/bug6798062.java 8146446 windows-all

/Users/dnsimon/dev/jdk-jdk/open/test/jdk/ProblemList.txt:775: javax/swing/JTabbedPane/4666224/bug4666224.java does not exist under any test root
javax/swing/JTabbedPane/4666224/bug4666224.java 8144124  macosx-all

STDERR:
java.lang.AssertionError: 5 errors found while checking 13 problem list files
	at CheckProblemLists.main(CheckProblemLists.java:96)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)

```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330755](https://bugs.openjdk.org/browse/JDK-8330755): ProblemList files have entries referring to non-existent tests (**Bug** - P4) ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18879/head:pull/18879` \
`$ git checkout pull/18879`

Update a local copy of the PR: \
`$ git checkout pull/18879` \
`$ git pull https://git.openjdk.org/jdk.git pull/18879/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18879`

View PR using the GUI difftool: \
`$ git pr show -t 18879`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18879.diff">https://git.openjdk.org/jdk/pull/18879.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18879#issuecomment-2068220339)

### CODE REVIEW

**Comment by dougxc** [comment]
I've removed `CheckProblemLists.java` as it overlaps with https://bugs.openjdk.org/browse/CODETOOLS-7903659.

**Comment by LudwikJaniuk** [comment]
While not a blocker IMO, I'm curious about the issues for the removed lines. Taking the first one as an example, I see it's "unresolved" (JDK-8192647) but the file was removed in JDK-8289764.
I don't see any other mentions of "problemlist" in JDK-8192647 so the "problemlist" label should probably also be removed.

I think it would be good to just do a check through the other issues and see if any other bookkeeping needs to be done, or if any surprises pop up.

**Comment by dougxc** [comment]
> While not a blocker IMO, I'm curious about the issues for the removed lines. Taking the first one as an example, I see it's "unresolved" (JDK-8192647) but the file was removed in JDK-8289764. I don't see any other mentions of "problemlist" in JDK-8192647 so the "problemlist" label should probably also be removed.
> 
> I think it would be good to just do a check through the other issues and see if any other bookkeeping needs to be done, or if any surprises pop up.

Ok, I'm pinging people here who git blame associates with some of the removed entries: @walulyai , @lmesnik @kumarabhi006

However, I don't see how removing these entries can cause any problems. Someone who have noticed failing problem listed tests by now.

**Comment by kevinjwalls** [comment]
The tidyup looks good!

I don't understand that this is titled as JDK-8330755 but that's already integrated.  So this needs to be done in a separate JBS entry and if the suggested CheckProblemLists.java is not going to be in it, we remove that from the description.

**Pull request closed without merging**
