### PR TITLE
8318487: Specification of the ListFormat.equals() method can be improved

### PR DESCRIPTION
**Pull request by naotoj**
Spec clarification of `ListFormat.equals()` method, utilizing newly introduced `getLocale()` and `getPatterns()`. A corresponding CSR has also been drafted.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8318567](https://bugs.openjdk.org/browse/JDK-8318567) to be approved

### Issues
 * [JDK-8318487](https://bugs.openjdk.org/browse/JDK-8318487): Specification of the ListFormat.equals() method can be improved (**Bug** - P3)
 * [JDK-8318567](https://bugs.openjdk.org/browse/JDK-8318567): Specification of the ListFormat.equals() method can be improved (**CSR**)

### Reviewers
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16321/head:pull/16321` \
`$ git checkout pull/16321`

Update a local copy of the PR: \
`$ git checkout pull/16321` \
`$ git pull https://git.openjdk.org/jdk.git pull/16321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16321`

View PR using the GUI difftool: \
`$ git pr show -t 16321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16321.diff">https://git.openjdk.org/jdk/pull/16321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16321#issuecomment-1775811402)

### CODE REVIEW

**Review by JoeWang-Java — APPROVED** [review]
Looks fine to me. 

Alternatively (or more explicitly), it could be: Compares the specified object with this {@code ListFormat} for equality. Returns true if the given object is also a {@code ListFormat}  and the two represent the same formats, specifically, if both {@code locale} and {@code patterns}, returned from {@link #getLocale()} and {@link #getPatterns()} respectively, are equal.

**Comment by naotoj** [comment]
Thanks, @JoeWang-Java 
In fact, your suggested style aligns with other `Format` classes, such as `DateFormat`/`NumberFormat`. Modified the wording to align with them.

**Review by JoeWang-Java — APPROVED** [review]
Thanks for the update, looks good again :-). Nice to know the javadoc styles are aligned.

**Review by RogerRiggs — APPROVED** [review]
Looks good.

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Corresponding CSR also Reviewed.

**Pull request closed without merging**
