### PR TITLE
8317358: G1: Make TestMaxNewSize use createTestJvm

### PR DESCRIPTION
**Pull request by lkorinth**
In addition remove deprecated `Long(long)` constructor and rewrite `compareTo` to use `> 0` instead of `== 1`.

Also remove unused `isRunningG1(String[] args)` and `checkIncompatibleNewSize(String[] flags)`

Minimal testing completed, will run tier testing before pushing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317358](https://bugs.openjdk.org/browse/JDK-8317358): G1: Make TestMaxNewSize use createTestJvm (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Stefan Johansson](https://openjdk.org/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16012/head:pull/16012` \
`$ git checkout pull/16012`

Update a local copy of the PR: \
`$ git checkout pull/16012` \
`$ git pull https://git.openjdk.org/jdk.git pull/16012/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16012`

View PR using the GUI difftool: \
`$ git pr show -t 16012`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16012.diff">https://git.openjdk.org/jdk/pull/16012.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16012#issuecomment-1743214549)

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Good.

**Review by kstefanj — CHANGES_REQUESTED** [review]
From what I can tell this test now fails when run with for example `-Xmn1g`. So I'm not sure if it really is a good idea to change this test to use `createTestJvm`. 

We could of course add this option to the requires list, but there are more options that can cause failures as well.

**Review by tschatzl — CHANGES_REQUESTED** [review]
Reconsidering and now tending to agree with @kstefanj about that heap size tests are too sensitive too various options (too many to list them all) to be worth the potential gain by running it with random options.

Maybe some more control about the flags like suggested in some other PR would make my concerns go away.

**Comment by lkorinth** [comment]
I will also take a look at the other comments.

**Comment by lkorinth** [comment]
I want to just give a few clarifications: 

`isRunningG1(String[] args)` that I removed was not really useful from what I understand; the resulting heap region size would always be a 32M (ergonomic max) or less resulting in a successful test run, however when we propagate flags it *will* make a difference.

I could add that code back, and I could add `@require` lines for `-Xmn` etc. I think what would be best though is to ignore all possible breaking flags and just add `flag-sensetive`.

**Comment by kstefanj** [comment]
I'm ok trying that out, we could always add the additional `@reguires` later on if this becomes problematic.

**Comment by lkorinth** [comment]
I have added `@key flag-sensitive`

**Review by kstefanj — APPROVED** [review]

**Review by tschatzl — APPROVED** [review]
Similar to @kstefanj I am a bit doubtful to have a test that is needs constraints on heap size to run with any random flags. This can be seen on the very long list of @requires constraints.
But I am good with doing this experiment and see if it will be annoying enough or not to reconsider.

**Comment by lkorinth** [comment]
Thanks Thomas and Stefan!

/integrate

**Pull request closed without merging**
