### PR TITLE
8317440: Lock rank checking fails when code root set is modified with the Servicelock held after JDK-8315503

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that fixes lock ranking after recent changes to the code root set, now using a CHT.

The issue came up because the lock rank of the CHT lock has been larger than the rank of the Servicethread_lock where it is possible that code roots can be added.

The suggested solution is to fix up the lock rankings to work; actually this PR contains two variants:
1) one that statically sets the lock ranks of the CHT lock (and the ThreadSMR_lock that can be used during CHT operation) to something smaller than Servicethread_lock.
2) one that allows setting of the CHT lock rank via parameter as well (the last commit changed the code to variant 1).

The other lock ranking changes to Metaspace_lock and ContinuationRelativize_lock are simply undos of the respective changes in [JDK-8315503](https://bugs.openjdk.org/browse/JDK-8315503). 

Testing: tier1-8 for variant 2), tier 1-7 for variant 1)

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317440](https://bugs.openjdk.org/browse/JDK-8317440): Lock rank checking fails when code root set is modified with the Servicelock held after JDK-8315503 (**Bug** - P2)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16062/head:pull/16062` \
`$ git checkout pull/16062`

Update a local copy of the PR: \
`$ git checkout pull/16062` \
`$ git pull https://git.openjdk.org/jdk.git pull/16062/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16062`

View PR using the GUI difftool: \
`$ git pr show -t 16062`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16062.diff">https://git.openjdk.org/jdk/pull/16062.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16062#issuecomment-1750132369)

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Variant 1 seems ok. Uses of the CHT shouldn't take locks, so having a low lock ranking for CHT lock seems like it'll be fine (I can't find where it takes the ThreadsSMRDelete_lock).  If any of this breaks, we can try approach #2 next.

**Review by albertnetymk — APPROVED** [review]

**Comment by tschatzl** [comment]
> Variant 1 seems ok. Uses of the CHT shouldn't take locks, so having a low lock ranking for CHT lock seems like it'll be fine (I can't find where it takes the ThreadsSMRDelete_lock). If any of this breaks, we can try approach #2 next.

Thread lists synchronization in `GlobalCounter::write_synchronize()` uses the `ThreadsSMRDelete_lock` via `JavaThreadIteratorWithHandle`->`ThreadsListHandle`->`SafeThreadsListPtr` in the destructor of the latter...

**Comment by tschatzl** [comment]
Thanks @coleenp @albertnetymk for your reviews
/integrate

**Comment by coleenp** [comment]
Going with variant 2.

**Comment by tschatzl** [comment]
> Going with variant 2.

So a new lock rank issue has been found? *sigh*

**Pull request closed without merging**
