### PR TITLE
JDK-8297032: IGV: shortcut to center selected nodes

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Introduce a new shortcut `CTRL-9`/ `CMD-9` to center the nodes that are currently selected in IGV

center_selected_nodes

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297032](https://bugs.openjdk.org/browse/JDK-8297032): IGV: shortcut to center selected nodes

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [692a90bb](https://git.openjdk.org/jdk/pull/11167/files/692a90bb82be4ffea9f7fe4533b8960a750b541e)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11167/head:pull/11167` \
`$ git checkout pull/11167`

Update a local copy of the PR: \
`$ git checkout pull/11167` \
`$ git pull https://git.openjdk.org/jdk pull/11167/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11167`

View PR using the GUI difftool: \
`$ git pr show -t 11167`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11167.diff">https://git.openjdk.org/jdk/pull/11167.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Works as expected on Linux - looks good!

**Review by robcasloz — APPROVED** [review]
Looks good to me! A nit (up to you whether you want to address it in this PR): you might disable the action when no node is selected, similarly to the node extraction action.

**Comment by tobiasholenstein** [comment]
> Looks good to me! A nit (up to you whether you want to address it in this PR): you might disable the action when no node is selected, similarly to the node extraction action.

Thanks for the good input @robcasloz ! 

I addressed your suggestion by making `CenterSelectedNodesAction` a `ModelAwareAction` and overriding the `isEnabled()` function: The action is now disabled if no nodes are selected

**Review by robcasloz — APPROVED** [review]
Thanks for addressing my suggestion, looks good!

**Pull request closed without merging**
