### PR TITLE
8278871: [JVMCI] assert((uint)reason < 2* _trap_hist_limit) failed: oob

### PR DESCRIPTION
**Pull request by dougxc**
This PR fixes a discrepancy between `MethodData::_trap_hist_list` and `Deoptimization::Reason_LIMIT` in terms of JVMCI specific usage.

JVMCI doubles the size of the deopt history for a method so that it can distinguish deopts in a normal method compilation from deopts in an OSR compilation:
```
    union {
      intptr_t _align;
      u1 _array[JVMCI_ONLY(2 *) MethodData::_trap_hist_limit];
    } _trap_hist;
```

To access the history for OSR deopts, the index for a deopt reason needs to be adjusted to the upper half of the history array. The amount used for the adjustment was incorrect and this PR fixes it:

```
  if (update_total_trap_count) {
    uint idx = reason;
#if INCLUDE_JVMCI
    if (is_osr) {
      idx += Reason_TRAP_HISTORY_LENGTH;
    }
#endif
```

I introduced `Reason_TRAP_HISTORY_LENGTH` as a replacement for `25 JVMCI_ONLY(+5),  // decoupled from Deoptimization::Reason_LIMIT` as this decoupling is unnecessary (as dangerous) as far as I can see.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278871](https://bugs.openjdk.java.net/browse/JDK-8278871): [JVMCI] assert((uint)reason < 2* _trap_hist_limit) failed: oob

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to c07e1778a9652daaa300a3f567e6dcf376f21936
 * [Tom Rodriguez](https://openjdk.java.net/census#never) (@tkrodriguez - **Reviewer**) ⚠️ Review applies to d74959032dc183a9a4a59cb82938d10cd47e58a1
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to c07e1778a9652daaa300a3f567e6dcf376f21936

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6855/head:pull/6855` \
`$ git checkout pull/6855`

Update a local copy of the PR: \
`$ git checkout pull/6855` \
`$ git pull https://git.openjdk.java.net/jdk pull/6855/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6855`

View PR using the GUI difftool: \
`$ git pr show -t 6855`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6855.diff">https://git.openjdk.java.net/jdk/pull/6855.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Yes, I looked on history and unfortunately we not always updated `_trap_hist_limit`.
It is not causing any big issues but we may lost some traps information. 

Looks good. I suggest to do regular testing too since change affects shared code.

**Review by tkrodriguez — APPROVED** [review]

**Comment by dean-long** [comment]
It seems a little fragile for asserts checking the array access to know the details of the array size computation (in case it changes in the future):

1999        assert((uint)reason < JVMCI_ONLY(2*) _trap_hist_limit, "oob");

How about using a constant/enum, or better yet, ARRAY_SIZE(_trap_hist._array) instead?

**Review by dean-long — CHANGES_REQUESTED** [review]
Suggest change: use ARRAY_SIZE()

**Comment by dougxc** [comment]
> Suggest change: use ARRAY_SIZE()

Thanks, I was not aware of the `ARRAY_SIZE` macro. I'll also add this macro when backporting this issue to 11.

**Comment by dougxc** [comment]
> Looks good. I suggest to do regular testing too since change affects shared code.

I've run `hs-tier1,hs-tier2,hs-tier3` testing.

**Review by vnkozlov — APPROVED** [review]
Update looks good.

**Review by dean-long — APPROVED** [review]
Looks good.

**Comment by dougxc** [comment]
Thanks for the reviews @tkrodriguez @dean-long @vnkozlov .

**Pull request closed without merging**
