### PR TITLE
8336786: VerifyError with lambda capture and enclosing instance references

### PR DESCRIPTION
**Pull request by cushon**
Hi, please consider this fix for [JDK-8336786](https://bugs.openjdk.org/browse/JDK-8336786). After [JDK-8334037](https://bugs.openjdk.org/browse/JDK-8334037) the handling of capturing `this` in lambdas does not handle synthetic `this` variables declared in supertypes in different packages. This change adjusts the lowering of `this` references to be owned by the enclosing class, instead of the superclass, so they are handle correctly be the capture logic in `capturedDecl` in `LambdaToMethod`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336786](https://bugs.openjdk.org/browse/JDK-8336786): VerifyError with lambda capture and enclosing instance references (**Bug** - P2)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20259/head:pull/20259` \
`$ git checkout pull/20259`

Update a local copy of the PR: \
`$ git checkout pull/20259` \
`$ git pull https://git.openjdk.org/jdk.git pull/20259/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20259`

View PR using the GUI difftool: \
`$ git pr show -t 20259`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20259.diff">https://git.openjdk.org/jdk/pull/20259.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20259#issuecomment-2239540392)

### CODE REVIEW

**Comment by mcimadamore** [comment]
The fix looks reasonable. I came up with something slightly different:
https://github.com/openjdk/jdk/compare/master...mcimadamore:jdk:lambda_encl_capture?expand=1

(perhaps some of the changes in LambdaToMethod from that fix would still be appreciated, such as the extra assert, and the removal of the subclass test, as I don't think that ever does anything).

Where I'm more unsure is in noting that Lower has two modes of capturing an enclosing `this`: a "precise" one, which calls `isMemberOf` and a more fuzzy one, which calls `isSubclass` on the owner. Inner class creation is the only case where we seem to use the fuzzy match.

But the lambda code _always_ uses membership. Effectively, the old `LambdaToMethod` code in `visitNewClass`, attempted to scan all the enclosing scopes, looking a proper owner of the to-be captured `this`. Failing that, we would just go ahead and add the captured enclosing `this` anyway.

I'm sure these little discrepancies are all accidents waiting to happen, in the sense that probably there are examples where Lower and LambdaToMethod would pick different enclosing `this`. This is kind of an unavoidable consequence of having the capture logic being defined in two unrelated places. So, not sure we've seen the end of this, but your fix seems a good step forward.

**Review by mcimadamore — APPROVED** [review]

**Review by mcimadamore — APPROVED** [review]

**Comment by cushon** [comment]
Thanks, switching to `clazz.isSubClass(sym.enclClass(), types)` in LambdaToMethod sounds good, it makes sense that the previous subclass check was a no-op and the more precise membership test shouldn't be necessary after Lower.

To double-check, it sounds like you're leaning towards also keeping the change to `makeOwnerThis`, even though it isn't required with the change to the subclass check in LambdaToMethod?

**Comment by mcimadamore** [comment]
Another possible avenue of things that can change as a result of this PR. In principle, changing the type of `this` from A to B would cause a difference in the bytecode binary qualifier. E.g. if you have `this.m()` you could see a reference to `B::m` where it used to be `A::m`.

But, after inspecting the code paths, it seems that `makeOwnerThis` can only return a plain `this` when you need an enclosing this for:
* an inner class creation expression
* a static accessor generated by Lower (to access some private/protected instance member)

So, in both cases, this PR is only changing the type of a "naked" `this` - therefore no adverse effect on binary qualifiers should occur.

**Comment by mcimadamore** [comment]
> To double-check, it sounds like you're leaning towards also keeping the change to `makeOwnerThis`, even though it isn't required with the change to the subclass check in LambdaToMethod?

Yes. It seems the right thing to do. We want the code to really return the "current" `this`, not just some `this` that might be related with the "current" one. This PR changes `Lower` so that the `this` it produces are the same as those generated by `Attr` itself. And that is a good thing.

**Review by mcimadamore — APPROVED** [review]
Looks good - thanks for fixing!

**Comment by cushon** [comment]
Thanks for the review!

**Pull request closed without merging**
