### PR TITLE
8266187: Memory leak in appendBootClassPath()

### PR DESCRIPTION
**Pull request by Wanghuang-Huawei**
Dear All, 
    I find a memory leak in `appendBootClassPath()`
https://github.com/openjdk/jdk/blob/75a2354dc276e107d64516d20fc72bc7ef3d5f86/src/java.instrument/share/native/libinstrument/InvocationAdapter.c#L950
* we malloc `resolved` from resolve(parent, path)
* we use `resolved` in line 951 
* we don't free() this memory after using.

I think we can fix this bug by adding a free() after line 951 as my commit.
Thank you for your review. Any suggestion is welcome.

Yours , 
Wang Huang

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266187](https://bugs.openjdk.java.net/browse/JDK-8266187): Memory leak in appendBootClassPath()

### Reviewers
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer) ⚠️ Review applies to c973192e250dc45fc3a42358b23f31ce7c911c3b
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**) ⚠️ Review applies to c973192e250dc45fc3a42358b23f31ce7c911c3b
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to c973192e250dc45fc3a42358b23f31ce7c911c3b

### Contributors
 * Wang Huang `<whuang@openjdk.org>`
 * Sun Jianye `<sunjianye@huawei.com>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3751/head:pull/3751` \
`$ git checkout pull/3751`

Update a local copy of the PR: \
`$ git checkout pull/3751` \
`$ git pull https://git.openjdk.java.net/jdk pull/3751/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3751`

View PR using the GUI difftool: \
`$ git pr show -t 3751`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3751.diff">https://git.openjdk.java.net/jdk/pull/3751.diff</a>

</details>

### CODE REVIEW

**Comment by kevinjwalls** [comment]
Hi,
I didn't find it immediately obvious that this was safe, but I followed things and think that it is correct:

The malloc'd pointer gets passed to...
JvmtiEnv::AddToBootstrapClassLoaderSearch(const char* segment) {

which calls	

ClassPathZipEntry* ClassLoader::create_class_path_zip_entry(const char *path, bool is_boot_append) {

..which calls
		
char* ClassLoader::get_canonical_path(const char* orig, Thread* thread) {

...which makes a copy of the string:
  char* orig_copy = NEW_RESOURCE_ARRAY_IN_THREAD(thread, char, strlen(orig)+1);
  strcpy(orig_copy, orig);
...and doesn't apear to keep the pointer.  So yes I think we should free it. 8-)

**Review by kevinjwalls — APPROVED** [review]

**Comment by Wanghuang-Huawei** [comment]
> Hi,
> I didn't find it immediately obvious that this was safe, but I followed things and think that it is correct:
> 
> The malloc'd pointer gets passed to...
> JvmtiEnv::AddToBootstrapClassLoaderSearch(const char* segment) {
> 
> which calls
> 
> ClassPathZipEntry* ClassLoader::create_class_path_zip_entry(const char *path, bool is_boot_append) {
> 
> ..which calls
> 
> char* ClassLoader::get_canonical_path(const char* orig, Thread* thread) {
> 
> ...which makes a copy of the string:
> char* orig_copy = NEW_RESOURCE_ARRAY_IN_THREAD(thread, char, strlen(orig)+1);
> strcpy(orig_copy, orig);
> ...and doesn't apear to keep the pointer. So yes I think we should free it. 8-)

Thank you for your review and explanation.

**Review by Hamlin-Li — APPROVED** [review]
looks good.

**Comment by kevinjwalls** [comment]
Oops - please update the copyright year, thanks! (second year in the header is currently 2019, should become 2021).

**Comment by Wanghuang-Huawei** [comment]
> Oops - please update the copyright year, thanks! (second year in the header is currently 2019, should become 2021).

Thank you for your suggestion.  I have update that.

**Pull request closed without merging**
