### PR TITLE
8305755: [JVMCI] missing barriers in CompilerToVM.readFieldValue for Reference.referent

### PR DESCRIPTION
**Pull request by tkrodriguez**
Add missing GC barrier for reflective read.  I'm not sure the idiom I've chosen it the correct one so please correct me if there's a better way to write this.  In testing, this resolved the issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305755](https://bugs.openjdk.org/browse/JDK-8305755): [JVMCI] missing barriers in CompilerToVM.readFieldValue for Reference.referent

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13389/head:pull/13389` \
`$ git checkout pull/13389`

Update a local copy of the PR: \
`$ git checkout pull/13389` \
`$ git pull https://git.openjdk.org/jdk.git pull/13389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13389`

View PR using the GUI difftool: \
`$ git pr show -t 13389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13389.diff">https://git.openjdk.org/jdk/pull/13389.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13389#issuecomment-1500495228)

### CODE REVIEW

**Review by fisk — CHANGES_REQUESTED** [review]
There are comments suggesting we need to read with Java volatile semantics. It was acquire before, which isn't always strong enough for Java volatiles. With the acquire dropped, I suppose it's even less okay. Looks like you want to use MO_SEQ_CST on these accesses, which precisely matches Java volatiles.

**Comment by tkrodriguez** [comment]
And that will include the G1 barrier required for `Reference.get()` semantics as well?

**Comment by fisk** [comment]
> And that will include the G1 barrier required for `Reference.get()` semantics as well?  And a second question is whether we can safely perform this read for all Reference subtypes.

Yes, as long as you keep ON_UNKNOWN_OOP_REF. And yes, you can safely do this for all reference types.

**Comment by tkrodriguez** [comment]
Thanks.  I've added MO_SEQ_CST to the oop case and changed the other cases to use HeapAccess with MO_SEQ_CST.

**Review by fisk — APPROVED** [review]
Looks good.

**Review by dougxc — APPROVED** [review]

**Pull request closed without merging**
