### PR TITLE
8335395: G1: Verification does not detect references into Free regions

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this improvement to `G1CollectedHeap::is_obj_dead()` where references into free regions were inadvertedly considered as live. This makes verification not fail with a proper error message when encountering references to objects in free regions (it may still fail for other reasons).

The alternative would have been fixing this in verification code only, but that method does not seem that hot, and the additional code not too slow either, but feel free to tell me otherwise and have me move the check.

This has been verified by @christianhaeubl who reported the issue.

Testing: gha

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8335395](https://bugs.openjdk.org/browse/JDK-8335395): G1: Verification does not detect references into Free regions (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19983/head:pull/19983` \
`$ git checkout pull/19983`

Update a local copy of the PR: \
`$ git checkout pull/19983` \
`$ git pull https://git.openjdk.org/jdk.git pull/19983/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19983`

View PR using the GUI difftool: \
`$ git pr show -t 19983`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19983.diff">https://git.openjdk.org/jdk/pull/19983.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19983#issuecomment-2202285422)

### CODE REVIEW

**Comment by albertnetymk** [comment]
> references into free regions were inadvertedly considered as live

Can you provide an running example to illustrate when/how this occurs? To me, `G1CollectedHeap::is_obj_dead` should have `!hs->free()` as precondition... How come the caller can hold such an invalid pointer?

**Comment by tschatzl** [comment]
> > references into free regions were inadvertedly considered as live
> 
> Can you provide an running example to illustrate when/how this occurs? To me, `G1CollectedHeap::is_obj_dead` should have `!hs->free()` as precondition... How come the caller can hold such an invalid pointer?

This occurs in error conditions where the VM/compiler misses some roots after some (internal) changes and incorrectly reclaims regions. I.e. this is purely about heap verification not handling this situation well.

E.g. in case of debug builds it would fail elsewhere (when verifying the classes of referenced objects).

I am open to changing the check in `is_obj_dead` to an assert, making this explicit, and handling this in the `LiveChecker`/verification code to (effectively) print a nice failure message.

**Comment by albertnetymk** [comment]
> I am open to changing the check in is_obj_dead to an assert, making this explicit, and handling this in the LiveChecker/verification code to (effectively) print a nice failure message.

I think that's better, as it isolates real code from verification logic.

**Review by albertnetymk — APPROVED** [review]

**Review by walulyai — APPROVED** [review]

**Comment by tschatzl** [comment]
Thanks @walulyai @albertnetymk for your reviews
/integrate

**Pull request closed without merging**
