### PR TITLE
8274405: Suppress warnings on non-serializable non-transient instance fields in javac and javadoc

### PR DESCRIPTION
**Pull request by jddarcy**
Augmentations to javac's Xlint:serial checking are out for review (#5709) and various javac and javadoc implementation libraries would need some changes to pass under the expanded checks.

The changes are to suppress warnings where non-transient fields in serializable types are not declared with a type statically known to be serializable. That isn't necessarily a correctness issues, but it does merit further scrutiny.

I'll run a script to update the copyright year before pushing.

Sending this change out for review separately in an effort to de-bulk the review needed for the new checks themselves.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274405](https://bugs.openjdk.java.net/browse/JDK-8274405): Suppress warnings on non-serializable non-transient instance fields in javac and javadoc

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**) ⚠️ Review applies to 7ad3a07c2f4023d3555b4699b93295ba9f638e7b
 * [Jonathan Gibbons](https://openjdk.java.net/census#jjg) (@jonathan-gibbons - **Reviewer**) ⚠️ Review applies to ceb0450eb8db577e4b364f9fa69f0b118e983ba2

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5728/head:pull/5728` \
`$ git checkout pull/5728`

Update a local copy of the PR: \
`$ git checkout pull/5728` \
`$ git pull https://git.openjdk.java.net/jdk pull/5728/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5728`

View PR using the GUI difftool: \
`$ git pr show -t 5728`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5728.diff">https://git.openjdk.java.net/jdk/pull/5728.diff</a>

</details>

### CODE REVIEW

**Review by pavelrappo — COMMENTED** [review]
Is there any semantic difference between "not statically Serilizable" and "not a Serilizable type"? Also, there's a typo: Seri-a-lizable.

**Comment by jddarcy** [comment]
> 
> 
> Is there any semantic difference between "not statically Serilizable" and "not a Serilizable type"? Also, there's a typo: Seri-a-lizable.

Same semantics. The first phase of this cleanup used "not statically Serilizable"; however, I thought "not a Serilizable type" is a more precise statement. I can make a pass over the PR and make the wording consistent in the new comments.

**Comment by pavelrappo** [comment]
> > Is there any semantic difference between "not statically Serilizable" and "not a Serilizable type"? Also, there's a typo: Seri-a-lizable.
> 
> Same semantics. The first phase of this cleanup used "not statically Serilizable"; however, I thought "not a Serilizable type" is a more precise statement. I can make a pass over the PR and make the wording consistent in the new comments.

You could update this PR if only to fix the typo; the phrasing is up to you.

**Comment by jddarcy** [comment]
> 
> 
> > > Is there any semantic difference between "not statically Serilizable" and "not a Serilizable type"? Also, there's a typo: Seri-a-lizable.
> > 
> > 
> > Same semantics. The first phase of this cleanup used "not statically Serilizable"; however, I thought "not a Serilizable type" is a more precise statement. I can make a pass over the PR and make the wording consistent in the new comments.
> 
> You could update this PR if only to fix the typo; the phrasing is up to you.

Wording updated.

**Review by pavelrappo — APPROVED** [review]
The javadoc changes look good. Hopefully, those Result errors, whose serial warnings this PR suppresses, will go away in JDK-8267690.

**Review by jonathan-gibbons — APPROVED** [review]
There are 3, maybe just 2,  groups of files in this review.

`sjavac` is an internal utility that ought not to be in the `src/` tree, so the changes there don't matter.

The various `Result` classes and the javadoc exceptions are all "internal" exceptions used for internal control flow, and not intended to be seen by API clients.  As @pavelrappo notes, we have plans to make the `Result` classes go away by rewriting the relevant scanners to make them unnecessary. That leaves the javadoc exceptions. The commented annotations have a slight code-smell about them, in the sense of brushing the warning under the carpet, so to speak. It would be better if there was a better way to remove the cause of the warning, rather than just hiding the warning itself.  But, that's not easy, and the original sin was making `Throwable` (and hence all subtypes) implement `Serializable` in the first place. But, that's the serialization we have and we have to deal with it.

As a final note, I never did like the `Runnable` in the last exception, and seeing it again may be a good reason to try and get rid of it, like those `Result` classes mentioned earlier.   I also note that `DocPath` _could_ be made `Serializable` but `DocFile` cannot reasonably be made serializable (incompatible API change to `Location`) and even thinking about it seems like a case of the tail wagging the elephant!

So, with some disappointment, I accept that the changes you propose are the least bad of the possible solutions, at least for now, and so I approve the review.

**Comment by jddarcy** [comment]
> 
> 
> There are 3, maybe just 2, groups of files in this review.
> 
> `sjavac` is an internal utility that ought not to be in the `src/` tree, so the changes there don't matter.
> 
> The various `Result` classes and the javadoc exceptions are all "internal" exceptions used for internal control flow, and not intended to be seen by API clients. As @pavelrappo notes, we have plans to make the `Result` classes go away by rewriting the relevant scanners to make them unnecessary. That leaves the javadoc exceptions. The commented annotations have a slight code-smell about them, in the sense of brushing the warning under the carpet, so to speak. It would be better if there was a better way to remove the cause of the warning, rather than just hiding the warning itself. But, that's not easy, and the original sin was making `Throwable` (and hence all subtypes) implement `Serializable` in the first place. But, that's the serialization we have and we have to deal with it.
> 
> As a final note, I never did like the `Runnable` in the last exception, and seeing it again may be a good reason to try and get rid of it, like those `Result` classes mentioned earlier. I also note that `DocPath` _could_ be made `Serializable` but `DocFile` cannot reasonably be made serializable (incompatible API change to `Location`) and even thinking about it seems like a case of the tail wagging the elephant!
> 
> So, with some disappointment, I accept that the changes you propose are the least bad of the possible solutions, at least for now, and so I approve the review.

If I were to see

@SuppressWarning("serial") // Type of field not Serializable
Foo foo;

in new code I would question the serial-design of the class; that is one of my goals with augmenting the Xlint:serial checks, notice possibly questionable serial coding patterns sooner.

For types where maintaining cross-release serial compatibility is not strictly needed, one approach would be to mark the fields as transient and give the class a different serialVersionUID. If serial compatibility is needed the conceptually transient field, i.e. one that cannot meaningful be serialized, could be nulled-out in a writeObject method and ignored in a readObject method, at the cost of maintaining those additional methods.

Fortunately, the the javax.lang.model API, the issues with exception classes having non-Serializable fields was recognized during the design and we marked all such fields and transient and documented the corresponding getters to possibly return null.

**Pull request closed without merging**
