### PR TITLE
6595142: (spec) ByteArrayInputStream treats bytes, not characters

### PR DESCRIPTION
**Pull request by bplb**
Replace the two occurrences of `character` with `byte`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6595142](https://bugs.openjdk.org/browse/JDK-6595142): (spec) ByteArrayInputStream treats bytes, not characters

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12505/head:pull/12505` \
`$ git checkout pull/12505`

Update a local copy of the PR: \
`$ git checkout pull/12505` \
`$ git pull https://git.openjdk.org/jdk pull/12505/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12505`

View PR using the GUI difftool: \
`$ git pr show -t 12505`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12505.diff">https://git.openjdk.org/jdk/pull/12505.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Looks okay, I assume you've done a wider search to see if there are any more.

**Comment by djelinski** [comment]
There are similar incorrect comments in SequenceInputStream and BufferedInputStream. There could be others, but "character" is a very popular word, so they are hard to spot.

**Comment by bplb** [comment]
> There are similar incorrect comments in SequenceInputStream and BufferedInputStream. There could be others, but "character" is a very popular word, so they are hard to spot.

Thanks for spotting these. Fixed in 7868641a2c9558e66b51c40b49031095317c3a48.

**Comment by bplb** [comment]
> Looks okay, I assume you've done a wider search to see if there are any more.

I missed the ones that @djelinski spotted. I rescanned `java.io` and don't see any others. Those two are fixed by 7868641a2c9558e66b51c40b49031095317c3a48.

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
