### PR TITLE
8282704: runtime/Thread/StopAtExit.java may leak memory

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Fix memory leak/pinning in runtime/Thread/StopAtExit.java stress test.
Change the test to:
- create and use its own ThreadGroup so it knows the expected thread count
- detect failures to cleanup the ThreadGroup
- these failures to cleanup can occur due to ThreadStop landing during Thread.exit()

The test uses reflection to call the package private ThreadGroup.threadTerminated()
or ThreadGroup.destroy() as needed. Sometimes the manual cleanup is not needed;
in a 30 second run, I typically see between 0-5 manual cleanups on my MBP13.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282704](https://bugs.openjdk.java.net/browse/JDK-8282704): runtime/Thread/StopAtExit.java may leak memory

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7819/head:pull/7819` \
`$ git checkout pull/7819`

Update a local copy of the PR: \
`$ git checkout pull/7819` \
`$ git pull https://git.openjdk.java.net/jdk pull/7819/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7819`

View PR using the GUI difftool: \
`$ git pr show -t 7819`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7819.diff">https://git.openjdk.java.net/jdk/pull/7819.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
I've test this version of the test with Mach5 Tier[1345678] and in
stress kit runs on my Ubuntu 20.04 machine and my M1 MacMini.

**Comment by dholmes-ora** [comment]
Hi Dan,

This problem will go away when I fix:

https://bugs.openjdk.java.net/browse/JDK-8282952

Cheers,
David

**Review by dholmes-ora — APPROVED** [review]
Okay, this is probably about as bullet-proof as you can make it.

Once [JDK-8282952](https://bugs.openjdk.java.net/browse/JDK-8282952) is fixed this should probably be reverted in 19. It will need modifying once the TG destroy() method is removed anyway.

Thanks,
David

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - Thanks for the review!

**Comment by dcubed-ojdk** [comment]
Can I get another review of this test fix?

**Comment by AlanBateman** [comment]
> Can I get another review of this test fix?

In addition to David's comment, I think we are really close to the point where Thread::stop will be degraded to throw UOE unconditionally. The test change is okay for the short term but I expect it will need to change or be removed in the medium term.

**Review by AlanBateman — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@AlanBateman - Thanks for the review!

If Thread.stop() is degraded to throw UOE, then this test will be removed
and I'll create a JVM/TI version of the test for the stress kit.

/integrate

**Pull request closed without merging**
