### PR TITLE
8238373: Punctuation should be same in jlink help usage on Japanese language

### PR DESCRIPTION
**Pull request by tkiriyama**
When showing help for the jlink command in a Japanese locale, delimiters of option's aliases are a mixture of "," and \u3001. Delimiter should be unified to ",".
As the same, there is a inconsistency of delimiters in the jar command help in a Japanese locale, and "," should be used.
Similarly, the javap command help uses space as delimiters other than the module option in all locales. This inconsistency should also be corrected.

Would you please review this fix?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8238373](https://bugs.openjdk.java.net/browse/JDK-8238373): Punctuation should be same in jlink help usage on Japanese language

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to [5163b9df](https://git.openjdk.java.net/jdk/pull/8417/files/5163b9df000c0bbf302b0fc9ffdf4922707cc3f6)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8417/head:pull/8417` \
`$ git checkout pull/8417`

Update a local copy of the PR: \
`$ git checkout pull/8417` \
`$ git pull https://git.openjdk.java.net/jdk pull/8417/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8417`

View PR using the GUI difftool: \
`$ git pr show -t 8417`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8417.diff">https://git.openjdk.java.net/jdk/pull/8417.diff</a>

</details>

### CODE REVIEW

**Comment by tkiriyama** [comment]
> Looks fine to me. Nit: please modify the copyright years for `javap` properties files, as you modified the base (`javap.properties`) file.

I’m sorry for the late reply.  
Thank you for your advice. I modified the copyright years for all files.

**Comment by naotoj** [comment]
I think it's ready for you to integrate. I can sponsor your changes.

**Pull request closed without merging**
