### PR TITLE
8263125: During deoptimization vectors should reassign scalarized payload after all objects are reallocated.

### PR DESCRIPTION
**Pull request by vnkozlov**
Currently during deoptimization Vector's `payload` field values are restored during Vector reallocation: 
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/prims/vectorSupport.cpp#L155 

But for scalar-replaced values this is not correct because payload box object could be re-allocated after allocation of this vector. Scalar-replaced `payload` should be restored during regular fields reassignment (`Deoptimization::reassign_fields()` change).

I renamed incorrect `eliminate_*` names for methods which restore/reallocate objects and locks.

I added checks for EliminateAutoBox and EnableVectorAggressiveReboxing optimizations which can replace allocations with scalar objects independent from Escape Analysis. 
 
I added prints for unexpected StackValue values (stackValue.cpp) and for Vector debug info location type (location.cpp).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263125](https://bugs.openjdk.java.net/browse/JDK-8263125): During deoptimization vectors should reassign scalarized payload after all objects are reallocated.

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to 2eb0b82d725ac07f5d19418a0d8b88e83b9d138b
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**) ⚠️ Review applies to 2eb0b82d725ac07f5d19418a0d8b88e83b9d138b

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2924/head:pull/2924`
`$ git checkout pull/2924`

### CODE REVIEW

**Review by iwanowww — COMMENTED** [review]
I vividly remember I fixed the very same problem before in Panama.

More specifically, why doesn't `VectorSupport::allocate_vector_payload` handle the case?

```
Handle VectorSupport::allocate_vector_payload(InstanceKlass* ik, frame* fr, RegisterMap* reg_map, ScopeValue* payload, TRAPS) {
  if (payload->is_location() &&
      payload->as_LocationValue()->location().type() == Location::vector) {
    // Vector value in an aligned adjacent tuple (1, 2, 4, 8, or 16 slots).
    Location location = payload->as_LocationValue()->location();
    return allocate_vector_payload_helper(ik, fr, reg_map, location, THREAD); // safepoint
  } else {
    // Scalar-replaced boxed vector representation.
    StackValue* value = StackValue::create_stack_value(fr, reg_map, payload);
    return value->get_obj();
  }
}
```

**Comment by vnkozlov** [comment]
Here is the order of scalarized objects in this case:
```
        # jdk.incubator.vector.ShortVector::rearrangeTemplate @ bci:14 (line 2117) L[0]=#ScObj0 L[1]=_ L[2]=#ScObj1 L[3]=#ScObj2 L[4]=_ L[5]=_ STK[0]=#Ptr0x00007f83a4e99850 STK[1]=#Ptr0x00007f83bd684760 STK[2]=#Ptr0x00007f83bca050f0 STK[3]=#4 STK[4]=#ScObj0 STK[5]=#ScObj1
        # ScObj0 jdk/incubator/vector/Short64Vector={ [payload :0]=rsp + #40 }
        # ScObj1 jdk/incubator/vector/Short64Vector$Short64Shuffle={ [payload :0]=#ScObj3 }
        # ScObj2 jdk/incubator/vector/Short64Vector$Short64Mask={ [payload :0]=rsp + #32 }
        # ScObj3 byte[4]={ [0]=rsp + #48 , [1]=rsp + #52 , [2]=rsp + #56 , [3]=RBP }
```
`ScObj1  Short64Shuffle` vector will be processed before `ScObj3 byte[4]` which it references.
VectorSupport::allocate_vector_payload() called only during `ScObj1  Short64Shuffle` reallocation when `ScObj3 byte[4]` is not reallocated yet. As result `value->get_obj()` return NULL. And that is the bug.

I forgot to say that the bug is triggered only with iterative EA I am working on. Without it `byte[]` array is not scalarized and everything works.

I also thought about calling modified `VectorSupport::allocate_vector_payload()` from `Deoptimization::reassign_fields()` to keep checks in one place but it would require more code changes then suggested fix (which is mostly asserts and debug print).

**Comment by iwanowww** [comment]
Thanks for the clarifications, Vladimir. 

I agree that `VectorSupport::allocate_vector_payload` is not the right place to handle the problematic case.

Some cleanup suggestions: now you can remove `StackValue::create_stack_value()`-related code from`VectorSupport::allocate_vector_payload()`, replace `ScopeValue* payload` argument with `Location location`, and turn  
`location.type() == Location::vector` check into an assert.

**Comment by iwanowww** [comment]
> I renamed incorrect eliminate_* names for methods which restore/reallocate objects and locks

Fully agree that `eliminate_allocations`/`eliminate_locks` are confusing, but `restore_*` still look a bit confusing to me.
What do you think about `rematerialize_objects`/`rematerialize_scalarized_objects`/`relock_objects`/`restore_eliminated_locks`?

**Review by iwanowww — APPROVED** [review]

**Review by reinrich — APPROVED** [review]
Hello Vladimir,

your change looks good to me. You might want to add the refactoring Vladimir
suggested.

May I ask why there is a special case to reallocate a vectors payload at all. In
other words: why is the method VectorSupport::allocate_vector_payload_helper()
needed? Is it for support of VectorMask?

Thanks, Richard.

**Comment by vnkozlov** [comment]
> > I renamed incorrect eliminate_* names for methods which restore/reallocate objects and locks
> 
> Fully agree that `eliminate_allocations`/`eliminate_locks` are misleading, but `restore_*` still look a bit confusing to me.
> What do you think about `rematerialize_objects`/`rematerialize_scalarized_objects`/`relock_objects`/`restore_eliminated_locks`?

I selected `rematerialize_objects` and `restore_eliminated_locks`.

**Comment by vnkozlov** [comment]
> Thanks for the clarifications, Vladimir.
> 
> I agree that `VectorSupport::allocate_vector_payload` is not the right place to handle the problematic case.
> 
> Some cleanup suggestions: now you can remove `StackValue::create_stack_value()`-related code from`VectorSupport::allocate_vector_payload()`, replace `ScopeValue* payload` argument with `Location location`, and turn
> `location.type() == Location::vector` check into an assert.

I removed `create_stack_value()` code from `VectorSupport::allocate_vector_payload()` and added asserts for all possible cases I found.

**Comment by iwanowww** [comment]
> May I ask why there is a special case to reallocate a vectors payload at all. In
other words: why is the method VectorSupport::allocate_vector_payload_helper()
needed? Is it for support of VectorMask?

(I assume you are asking about `VectorSupport::allocate_vector_payload()`.)

Special handling is needed because Vector/VectorMask is represented as a single value in scalarized form, but in the boxed form it's a pair of instances: Vector/VectorMask + primitive array (holding the payload). `reassign_fields` doesn't handle such case and that's why it is special-cased.

**Comment by vnkozlov** [comment]
> Hello Vladimir,
> 
> your change looks good to me. You might want to add the refactoring Vladimir
> suggested.
> 
> May I ask why there is a special case to reallocate a vectors payload at all. In
> other words: why is the method VectorSupport::allocate_vector_payload_helper()
> needed? Is it for support of VectorMask?
> 
> Thanks, Richard.

@iwanowww may know correct answer.

As I understand it is because vectors need to re-allocate additional `payload` array to store vectors element:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/prims/vectorSupport.cpp#L129
`create_stack_value()` does not handle new allocations and arrays. It would require a lot changes.

I think it could be done if during debug info generation we describe element's storage as Scalarized array. But it would not help VectorMask as you said.

**Comment by reinrich** [comment]
> 
> 
> > May I ask why there is a special case to reallocate a vectors payload at all. In
> > other words: why is the method VectorSupport::allocate_vector_payload_helper()
> > needed? Is it for support of VectorMask?
> 
> (I assume you are asking about `VectorSupport::allocate_vector_payload()`.)
> 
> Special handling is needed because Vector/VectorMask is represented as a single value in scalarized form

And can't the payload for deoptimization be represented as a scalarized array in that case too? Maybe not because of the special handling a VectorMask requires.

I'm probably not familiar enough with the vector implementation, so sorry for bothering.

IIUC @vnkozlov says this could be done but not for VectorMask.

> I think it could be done if during debug info generation we describe element's storage as Scalarized array. But it would not help VectorMask as you said.

**Comment by reinrich** [comment]
> I think it could be done if during debug info generation we describe element's storage as Scalarized array. But it would not help VectorMask as you said.

I see. Thanks for answering. Change still looks good to me.

**Comment by iwanowww** [comment]
> And can't the payload for deoptimization be represented as a scalarized array in that case too? Maybe not because of the special handling a VectorMask requires.

Vector is special in a very similar way: debug info contains only vector value location. Custom logic is needed to turn it into scalarized array representation. And then there's still a step required to allocate the corresponding typed vector box which wraps the payload.

I'm not saying it is not possible to represent current on-heap shape solely in debug info, but it would require significant refactorings/enhancements of existing machinery. And would complicate possible changes of the on-heap vector/mask shape. It is not something "cut in stone" and can evolve over time.

**Comment by vnkozlov** [comment]
> > And can't the payload for deoptimization be represented as a scalarized array in that case too? Maybe not because of the special handling a VectorMask requires.
> 
> Vector is special in a very similar way: debug info contains only vector value location. Custom logic is needed to turn it into scalarized array representation. And then there's still a step required to allocate the corresponding typed vector box which wraps the payload.
> 
> I'm not saying it is not possible to represent current on-heap shape solely in debug info, but it would require significant refactorings/enhancements of existing machinery. And would complicate possible changes of the on-heap vector/mask shape. It is not something "cut in stone" and can evolve over time.

Yes, I said it too. It can be done but code would be much larger and more complicated.
And, as Vladimir I. correctly pointed, VectorAPI is new code which can be evolved. To have specialized code for it makes it easy to do experiments.

Thank you @iwanowww and @reinrich for reviews.

**Comment by reinrich** [comment]
I see. Thanks for elaborating on my question!

**Pull request closed without merging**
