### PR TITLE
8320237 C2: late inlining of method handle invoke causes duplicate lines in PrintInlining output

### PR DESCRIPTION
**Pull request by tabjy**
This PR resolves [JDK-8320237](https://bugs.openjdk.org/browse/JDK-8320237)

The original behavior produces both a failure and success message upon late inlining which is confusing. The patch removes the failure message if inlining was successful. Huge thanks to @rwestrel for reporting and working out a solution.

Unit test `test/hotspot/jtreg/compiler/inlining/TestDuplicatedLateInliningOutput.java` is added and passing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320237](https://bugs.openjdk.org/browse/JDK-8320237): C2: late inlining of method handle invoke causes duplicate lines in PrintInlining output (**Bug** - P5)

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to [3e53d03a](https://git.openjdk.org/jdk/pull/17147/files/3e53d03aae6f976c4cabe37982fcde4c84634a30)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [3e53d03a](https://git.openjdk.org/jdk/pull/17147/files/3e53d03aae6f976c4cabe37982fcde4c84634a30)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17147/head:pull/17147` \
`$ git checkout pull/17147`

Update a local copy of the PR: \
`$ git checkout pull/17147` \
`$ git pull https://git.openjdk.org/jdk.git pull/17147/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17147`

View PR using the GUI difftool: \
`$ git pr show -t 17147`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17147.diff">https://git.openjdk.org/jdk/pull/17147.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17147#issuecomment-1881552619)

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by vnkozlov — APPROVED** [review]
Looks good to me too.

**Review by TobiHartmann — CHANGES_REQUESTED** [review]
Please do not sponsor this yet. We see various test failures. I'll follow-up shortly.

**Comment by TobiHartmann** [comment]
`compiler/print/PrintInlining.java` fails with `-ea -esa -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -server -XX:+TieredCompilation`:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (workspace/open/src/hotspot/share/opto/compile.cpp:4601), pid=418042, tid=418058
#  assert(_print_inlining_stream->size() > 0) failed: missing inlining msg
#
# JRE version: Java(TM) SE Runtime Environment (23.0) (fastdebug build 23-internal-2024-01-10-0732483.tobias.hartmann.jdk2)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 23-internal-2024-01-10-0732483.tobias.hartmann.jdk2, compiled mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x9db4e6]  Compile::print_inlining_update_delayed(CallGenerator*)+0x1c6

Current CompileTask:
C2:643  171    b  4       java.lang.String::substring (58 bytes)

Stack: [0x00007f59706d4000,0x00007f59707d4000],  sp=0x00007f59707cf220,  free space=1004k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x9db4e6]  Compile::print_inlining_update_delayed(CallGenerator*)+0x1c6  (compile.cpp:4601)
V  [libjvm.so+0x844d7e]  CallGenerator::do_late_inline_helper()+0x8ee  (callGenerator.cpp:687)
V  [libjvm.so+0x9e1a52]  Compile::inline_boxing_calls(PhaseIterGVN&)+0xc2  (compile.cpp:2026)
V  [libjvm.so+0x9e42e3]  Compile::Optimize()+0x583  (compile.cpp:2276)
V  [libjvm.so+0x9e81a4]  Compile::Compile(ciEnv*, ciMethod*, int, Options, DirectiveSet*)+0x1b44  (compile.cpp:860)
V  [libjvm.so+0x83d245]  C2Compiler::compile_method(ciEnv*, ciMethod*, int, bool, DirectiveSet*)+0x1d5  (c2compiler.cpp:142)
V  [libjvm.so+0x9f3bbc]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0x92c  (compileBroker.cpp:2299)
V  [libjvm.so+0x9f4848]  CompileBroker::compiler_thread_loop()+0x468  (compileBroker.cpp:1958)
V  [libjvm.so+0xeb98ec]  JavaThread::thread_main_inner()+0xcc  (javaThread.cpp:721)
V  [libjvm.so+0x179b586]  Thread::call_run()+0xb6  (thread.cpp:220)
V  [libjvm.so+0x14a8d47]  thread_native_entry(Thread*)+0x127  (os_linux.cpp:789)
```

`compiler/cha/StrengthReduceInterfaceCall.java` and `compiler/ciReplay/TestIncrementalInlining.java` fail as well.

**Comment by tabjy** [comment]
@TobiHartmann Thanks for the report.

The tests were crashing in fastdebug config with or without those specific flags. The latest commit should fix the problem. Please take a look. Thank you very much.

**Comment by TobiHartmann** [comment]
Thanks, I'll re-run testing. Could you please explain what the problem was?

**Comment by rwestrel** [comment]
> Could you please explain what the problem was?

I did the fix. For virtual and method handle inline calls, late inlining happens because we couldn't resolve the call to a single target before and the late inlining logic goes through the inlining heuristics again to find one. As a result, a new inlining message is produced. For other type of calls, the call is known to successfully inline but was delayed due to lack of nodes. When late inlining succeeds then, it's because the graph has shrunk enough but there's no new inlining message. The other thing is that the print inlining logic is conditioned on PrintInlining and PrintIntrinsics. When PrintIntrinsics only is true, for method handle and virtual calls, during late inlining no new inlining message is produced.

**Comment by TobiHartmann** [comment]
Thanks for the explanation. `compiler/inlining/TestDuplicatedLateInliningOutput.java` still failed once with `-XX:+UseZGC -XX:+ZGenerational`:
```
java.lang.Exception: No inlining found
	at compiler.inlining.TestDuplicatedLateInliningOutput.lambda$test$1(TestDuplicatedLateInliningOutput.java:77)
	at java.base/java.util.OptionalInt.orElseThrow(OptionalInt.java:273)
	at compiler.inlining.TestDuplicatedLateInliningOutput.test(TestDuplicatedLateInliningOutput.java:77)
	at compiler.inlining.TestDuplicatedLateInliningOutput.main(TestDuplicatedLateInliningOutput.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by tabjy** [comment]
Hi @TobiHartmann,

Thank you for testing, but I've been unsuccessful in reproducing this error so far. Could you please elaborate on which config and the platform you were testing against? Also, am I correct to assume you were passing zgc options to the test harness (e.g., something like `make ... JTREG="VM_OPTIONS=-XX:+UseZGC -XX:+ZGenerational"`), not the actual subprocesses outputing those inlining log? (I did test running subprocesses with zgc options with no failures.) Either way, please advice how you were specifying zgc options.

Sorry if I'm missing something obvious here. I'm new to JDK development. :)

**Comment by rwestrel** [comment]
I think the subprocess needs to be run with `-XX:-BackgroundCompilation` otherwise there's a chance it completes before the compilation finishes and the print inlining output is produced.

**Comment by TobiHartmann** [comment]
Yes, `-XX:+UseZGC -XX:+ZGenerational` were passed via jtreg. The failure seems to be intermittent as it happened only once with a debug build on Windows x64.

**Comment by tabjy** [comment]
I've failed to recreate this failure on Windows after multiple attempts. At this time, I can only suspect it is indeed an intermittent failure caused by what @rwestrel suggested. The latest commit adds the `-XX:-BackgroundCompilation` flag which can hopefully makes the test more stable.

**Comment by TobiHartmann** [comment]
Okay, I'll re-run testing and report back once it passed.

**Review by TobiHartmann — APPROVED** [review]
All tests passed.

**Pull request closed without merging**
