### PR TITLE
8261868: Reduce inclusion of metaspace.hpp

### PR DESCRIPTION
**Pull request by iklam**
metaspace.hpp is included by about 770 out of 1000 HotSpot .o files. Most of these are transitively included via array.hpp and classLoaderData.hpp.

- classLoaderData.hpp doesn't actually need metaspace.hpp.
- array.hpp can be refactored to put a function that depends on metaspace.hpp into array.inline.hpp

Doing the above reduces the number of .o files that include metaspace.hpp to 343. Since this is still a significant number, we should split out the rarely used classes (such as `MetaspaceGC` and `MetaspaceUtils`) into a new header file (metaspaceUtils.hpp, which is included only 30 times).

Also, these 3 includes can now be removed from metaspace.hpp.

```
#include "memory/memRegion.hpp"
#include "memory/metaspaceChunkFreeListSummary.hpp"
#include "memory/virtualspace.hpp"
```

Tested with mach5: tier1, builds-tier2, builds-tier3, builds-tier4 and builds-tier5. Also locally: aarch64, arm, ppc64, s390, x86, and zero.

(I also fixed an unrelated comment in archiveUtils.cpp when I was scanning for the word "Metaspace" in the source files -- the function `MetaspaceShared::commit_to()` no longer exists).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261868](https://bugs.openjdk.java.net/browse/JDK-8261868): Reduce inclusion of metaspace.hpp

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to 700d1c16a12c099cdfa9df2315e807b766dcc19b
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to 700d1c16a12c099cdfa9df2315e807b766dcc19b

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2599/head:pull/2599`
`$ git checkout pull/2599`

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Hi Ioi,

this is very appreciated.

metaspace.hpp is still a bit of a mess. Its the last holdover for the old metaspace implementation and I always wanted to clean it out a bit. Splitting this header into three is a right step.

A lot of that stuff may still vanish and/or be reformed if I have the time (eg metaspaceChunkFreeListSummary).

Assuming this builds and tests fine on all our platform, including the weirder ones, I am fine with this patch. It looks good.

Thanks, Thomas

**Review by calvinccheung — APPROVED** [review]
One more file you may consider updating is share/memory/classLoaderMetaspace.cpp.
It now depends on metaspaceUtils.hpp but it includes it transitively via metaspaceTracer.hpp.
The include of metaspace.hpp is not needed because classLoaderMetaspace.hpp includes it.

Other changes seem good.

Thanks,
Calvin

**Comment by iklam** [comment]
> One more file you may consider updating is share/memory/classLoaderMetaspace.cpp.
> It now depends on metaspaceUtils.hpp but it includes it transitively via metaspaceTracer.hpp.
> The include of metaspace.hpp is not needed because classLoaderMetaspace.hpp includes it.
> 
> Other changes seem good.

I added metaspaceUtils.hpp to classLoaderMetaspace.cpp. I kept metaspace.hpp in there -- our convention is to always explicitly include a header file if we use its contents, even if this header file might be transitively included by other headers.

**Comment by iklam** [comment]
Thanks @tstuefe and @calvinccheung for the review. I re-tested with the latest repo.
/integrate

**Comment by iklam** [comment]
Note: the commit into the openjdk/jdk repo was successful. https://github.com/openjdk/jdk/commit/0f8be6e433b5d30e028558a4bea0659838d6b700

The previous message by the openjdk bot seems to be an error by the bot.

**Pull request closed without merging**
