### PR TITLE
8332098: Add missing @ since tags to jdk.jdi

### PR DESCRIPTION
**Pull request by nizarbenalla**
Please review this simple change where I add "@ since" tags to the package-info file of the following packages

com.sun.jdi
com.sun.jdi.connect
com.sun.jdi.connect.spi
com.sun.jdi.event
com.sun.jdi.request

I used the unix grep command to find the oldest "@ since" in each package and used that value, as it's hard to get the source code of JDK 1-5
TIA

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332098](https://bugs.openjdk.org/browse/JDK-8332098): Add missing @ since tags to jdk.jdi (**Sub-task** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19200/head:pull/19200` \
`$ git checkout pull/19200`

Update a local copy of the PR: \
`$ git checkout pull/19200` \
`$ git pull https://git.openjdk.org/jdk.git pull/19200/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19200`

View PR using the GUI difftool: \
`$ git pr show -t 19200`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19200.diff">https://git.openjdk.org/jdk/pull/19200.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19200#issuecomment-2106351148)

### CODE REVIEW

**Comment by AlanBateman** [comment]
JPDA was added to the JDK in JDK 1.3. The support for pluggable connectors (added com.sun.jdi.connect.spi package) was JDK 5. So I think this looks okay.

**Review by AlanBateman — APPROVED** [review]

**Comment by plummercj** [comment]
Can you fix the summary of the CR to not have backwards quotes. This seems to cause git some grief, as can be seen where the CR is mentioned in the Issue section of the PR description.

**Comment by nizarbenalla** [comment]
Done, I tend to use them for formatting.
And there are users with names such as "@ since" that would keep getting tagged.

**Review by plummercj — APPROVED** [review]

**Comment by jaikiran** [comment]
No changes have been done to the PR since it was last approved by Chris few days back (that's a good thing). I'll go ahead and sponsor this now.

**Pull request closed without merging**
