### PR TITLE
JDK-8273312 : [TESTBUG] sanity/client/SwingSet/src/ButtonDemoScreenshotTest.java fails intermittently on Windows OS.

### PR DESCRIPTION
**Pull request by amresh-sahu**
Problem: In Windows look and feel, Button(in test case ui) starts animating to show the selection and test case captures the animated button image to do the comparisons with initial button image and this comparison fails with Timeout Exception exception. 

Solution: TestHelper class provides the list of look and feel. One more method added to this class to exclude the windows look and feel.

This test has been tested  20 times on mach5 and It is passing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8273312](https://bugs.openjdk.java.net/browse/JDK-8273312): [TESTBUG] sanity/client/SwingSet/src/ButtonDemoScreenshotTest.java fails intermittently on Windows OS.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5380/head:pull/5380` \
`$ git checkout pull/5380`

Update a local copy of the PR: \
`$ git checkout pull/5380` \
`$ git pull https://git.openjdk.java.net/jdk pull/5380/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5380`

View PR using the GUI difftool: \
`$ git pr show -t 5380`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5380.diff">https://git.openjdk.java.net/jdk/pull/5380.diff</a>

</details>

### CODE REVIEW

**Comment by amresh-sahu** [comment]
@shurymury @lawrence-andrew Kindly review my changes.

**Comment by pankaj-bansal** [comment]
Is there a specific reason why this comparison only times out for windows L&F and the test passes on other L&Fs. I mean should not a bug be filled to investigate the reason for the same instead of excluding the Windows L&F from the tested L&Fs.

**Comment by mrserb** [comment]
This animation was disabled by the JDK_8222519, does it meant that "-Dswing.disablevistaanimation=true" is broken?

**Comment by amresh-sahu** [comment]
Thanks @mrserb. Test case passes with -Dswing.disablevistaanimation=true so closed the pull request.

**Pull request closed without merging**
