### PR TITLE
8183374: Refactor java/lang/Runtime shell tests to java

### PR DESCRIPTION
**Pull request by fguallini**
Refactor the following shell tests to java:
test/jdk/java/lang/RuntimeTests/shutdown/ShutdownHooks.sh
test/jdk/java/lang/Runtime/exec/SetCwd.java

In addition, the test SetCwd was running itself in separate java subprocesses in order to exercise Runtime.exec. It was creating a folder structure with multiple test class copies to distinguish between main and child processes to prevent an infinite recursion. That logic is simplified now, tests follow the testng annotations flow whereas the subprocesses entry point is a nested class main

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8183374](https://bugs.openjdk.java.net/browse/JDK-8183374): Refactor java/lang/Runtime shell tests to java

### Reviewers
 * [Sean Coffey](https://openjdk.java.net/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3572/head:pull/3572` \
`$ git checkout pull/3572`

Update a local copy of the PR: \
`$ git checkout pull/3572` \
`$ git pull https://git.openjdk.java.net/jdk pull/3572/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3572`

View PR using the GUI difftool: \
`$ git pr show -t 3572`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3572.diff">https://git.openjdk.java.net/jdk/pull/3572.diff</a>

</details>

### CODE REVIEW

**Comment by fguallini** [comment]
Please, have a look at this PR, it would also need sponsoring, thanks

**Comment by coffeys** [comment]
Looks fine to me.

**Review by coffeys — APPROVED** [review]

**Pull request closed without merging**
