### PR TITLE
8266789: devirtualize find_node and remove of LinkedList

### PR DESCRIPTION
**Pull request by navyxliu**
Devirtualize find, find_node and remove. This patch make both LinkedListImpl
and SortedLinkedList more generic. If the client doesn't use those member functions,
it's not necessary to define equals() for the user-defined class E.

Remove those 3 member functions from the pure interface LinkedList. subclasses
implement them using regular member functions.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8266789](https://bugs.openjdk.java.net/browse/JDK-8266789): devirtualize find_node and remove of LinkedList

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3944/head:pull/3944` \
`$ git checkout pull/3944`

Update a local copy of the PR: \
`$ git checkout pull/3944` \
`$ git pull https://git.openjdk.java.net/jdk pull/3944/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3944`

View PR using the GUI difftool: \
`$ git pr show -t 3944`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3944.diff">https://git.openjdk.java.net/jdk/pull/3944.diff</a>

</details>

### CODE REVIEW

**Comment by navyxliu** [comment]
hi, Reviewers,  
Ping?

**Comment by navyxliu** [comment]
hi, @iklam 
Could you take a look at this. 

thanks, 
--lx

**Comment by iklam** [comment]
If I understand correctly, the design of `LinkedList` provides an abstract base type `LinkedList<T>`, so that you can use

```
LinkedList<MyType>* list = .....;
MyType v = ....;
bool exists = list->find(v);
```

If you remove  the`virtual LinkedList<T>::find() = 0;` declaration, the above code will not work anymore.

Your patch can compile because `find` is currently used only once here, where the implementation type is known at compile time:

```
bool MemBaseline::aggregate_virtual_memory_allocation_sites() {
  SortedLinkedList<VirtualMemoryAllocationSite, compare_allocation_site> allocation_sites;
  ...
    site = allocation_sites.find(tmp);
```

However, this will not work in the future when we have other use of `find` where the exact implementation type is not known.

**Comment by navyxliu** [comment]
hi, Ioi, 

Thank you for reviewing it. Yes, what you said is 100% correct. 

Look, this is the very problem of this LinkedList. You pay for what you don't use. It's very not c++.
To support non-existence use case, C++ has to instantiate template member functions and calll them via vtable.   
(That's how Java works because Java has dynamic solution for devirtualization.)

LinkedList is a ADL container. What's the point to support class hierarchy for it? Why do we need late binding for find()?

```
SortedLinkedList<VirtualMemoryAllocationSite, compare_allocation_site> allocation_sites;
...
site = allocation_sites.find(tmp);
```
This is real code.

I didn't overthrow the design. I just would like to free up from this equals(). I actually don't use find at all.
https://github.com/openjdk/jdk/pull/3135/files#diff-31de33d2853a803965fd4381172f11904a44f42a125b02caec206f72c94f89d6R103

**Comment by iklam** [comment]
By design, the `LinkedList` API supports polymorphism which is used by the existing code. For example: here we are moving from a `LinkedListImpl` into a `SortedLinkedList`.

```
void MemBaseline::malloc_sites_to_size_order() {
...
    SortedLinkedList<MallocSite, compare_malloc_size> tmp;
    tmp.move(&_malloc_sites); // _malloc_sites is a LinkedListImpl<...>
```

It will be odd if you change part of the API to non virtual just so that you can avoid implementing `equals`. I don't think this is the right thing to do.

Regarding the following comments in linkedlist.hpp:

```
  // Select member function 'bool U::equals(const U&) const' if 'U' is of class
  // type. This works because of the "Substitution Failure Is Not An Error"
  // (SFINAE) rule. Notice that this version of 'equal' will also be chosen for
  // class types which don't define a corresponding 'equals()' method (and will
  // result in a compilation error for them). It is not easily possible to
  // specialize this 'equal()' function exclusively for class types which define
  // the correct 'equals()' function because that function can be in a base
  // class, a dependent base class or have a compatible but slightly different
  // signature.
  template <class U>
  static bool equal(const U& a, const U& b, bool (U::*t)(const U&) const) {
    return a.equals(b);
  }
```

If you want to implement SFINAE to filter out element types that don't implement `equals`, maybe you can try this:

https://gist.github.com/fenbf/d2cd670704b82e2ce7fd

**Comment by navyxliu** [comment]
Thanks. I see.  That's fine.  I don't think it's a good idea to keep using SFINAE. 
Let me close it.

**Pull request closed without merging**
