### PR TITLE
8297455: Use the official ToolProvider API to call javac

### PR DESCRIPTION
**Pull request by magicus**
In JDK-8297041, the javacserver was moved out of the JDK itself, and lifted out as a separate buildtool. Due to this, internal classes in jdk.compiler were no longer available. Therefore, the closest way to calling javac as before were to use `com.sun.tools.javac.Main.compile()`. This method is however deprecated for removal, and relying on that was only needed as a temporary measure during the transition.

After the major refactoring of the javacserver tool in JDK-8297444, it will be easy to replace the Main.compile API with the official ToolProvider API instead.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297455](https://bugs.openjdk.org/browse/JDK-8297455): Use the official ToolProvider API to call javac

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [1ab659c0](https://git.openjdk.org/jdk/pull/11299/files/1ab659c0ca4ffab144af95091aa794a3017b4fe3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11299/head:pull/11299` \
`$ git checkout pull/11299`

Update a local copy of the PR: \
`$ git checkout pull/11299` \
`$ git pull https://git.openjdk.org/jdk pull/11299/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11299`

View PR using the GUI difftool: \
`$ git pr show -t 11299`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11299.diff">https://git.openjdk.org/jdk/pull/11299.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Note that this PR is dependent on JDK-8297444 (PR: https://github.com/openjdk/jdk/pull/11298)

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
Just to make sure, will this find the interim javac before the bootjdk javac? How is this enforced?

**Comment by magicus** [comment]
Well, I assume so. If this does not work properly, the problem will most likely be already in JDK-8297444; this patch is just choosing a different path to end up in the same class, as far as I can understand.

The thing that makes (or should make) us chose the interim javac is the `$(INTERIM_LANGTOOLS_ARGS)` which is passed to java when launching the server. (This is since these flags are passed in the config file to the client as `javacmd`). 

I'll add some test output code to the interim compiler to verify that it is actually executed, both in JDK-8297444 and in this PR.

**Comment by magicus** [comment]
I have now verified that the interim compiler is indeed used (made it say bad words and fail at startup, so there is no doubt about it :)). As to the reason why this is so, here is the magic incantation from `$(INTERIM_LANGTOOLS_ARGS)`:

```
    --limit-modules java.base,jdk.zipfs,$(INTERIM_LANGTOOLS_MODULES_COMMA) \
    --add-modules $(INTERIM_LANGTOOLS_MODULES_COMMA) \
    --module-path $(BUILDTOOLS_OUTPUTDIR)/interim_langtools_modules \
    --patch-module java.base=$(BUILDTOOLS_OUTPUTDIR)/gensrc/java.base.interim \
    --add-exports java.base/sun.reflect.annotation=jdk.compiler.interim \
    --add-exports java.base/jdk.internal.jmod=jdk.compiler.interim \
    --add-exports java.base/jdk.internal.misc=jdk.compiler.interim \
    --add-exports java.base/sun.invoke.util=jdk.compiler.interim \
    --add-exports java.base/jdk.internal.javac=java.compiler.interim \
    --add-exports java.base/jdk.internal.javac=jdk.compiler.interim \
```

I hope you are not asking me to explain in detail how or why this works. :-)

**Comment by erikj79** [comment]
> I have now verified that the interim compiler is indeed used (made it say bad words and fail at startup, so there is no doubt about it :)). As to the reason why this is so, here is the magic incantation from `$(INTERIM_LANGTOOLS_ARGS)`:
> 
> ```
>     --limit-modules java.base,jdk.zipfs,$(INTERIM_LANGTOOLS_MODULES_COMMA) \
>     --add-modules $(INTERIM_LANGTOOLS_MODULES_COMMA) \
>     --module-path $(BUILDTOOLS_OUTPUTDIR)/interim_langtools_modules \
>     --patch-module java.base=$(BUILDTOOLS_OUTPUTDIR)/gensrc/java.base.interim \
>     --add-exports java.base/sun.reflect.annotation=jdk.compiler.interim \
>     --add-exports java.base/jdk.internal.jmod=jdk.compiler.interim \
>     --add-exports java.base/jdk.internal.misc=jdk.compiler.interim \
>     --add-exports java.base/sun.invoke.util=jdk.compiler.interim \
>     --add-exports java.base/jdk.internal.javac=java.compiler.interim \
>     --add-exports java.base/jdk.internal.javac=jdk.compiler.interim \
> ```
> 
> I hope you are not asking me to explain in detail how or why this works. :-)

Thanks! Yeah, that rings a bell and I think I understand how it works, but I surely wouldn't be able to replicate this from memory.

**Pull request closed without merging**
