### PR TITLE
8328278: Do not print the tenuring threshold in AgeTable::print_on

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

This patch places the SerialGC code that computes tenuring threshold before per GC instead of after per GC, so that the method `AgeTable::print_on` prints the right tenuring threshold. Just like the current G1 implementation.

Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328278](https://bugs.openjdk.org/browse/JDK-8328278): Do not print the tenuring threshold in AgeTable::print_on (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to [d8945592](https://git.openjdk.org/jdk/pull/18329/files/d89455920cb6d491f33a6bce3cb720de2a03e295)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18329/head:pull/18329` \
`$ git checkout pull/18329`

Update a local copy of the PR: \
`$ git checkout pull/18329` \
`$ git pull https://git.openjdk.org/jdk.git pull/18329/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18329`

View PR using the GUI difftool: \
`$ git pr show -t 18329`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18329.diff">https://git.openjdk.org/jdk/pull/18329.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18329#issuecomment-2002158781)

### CODE REVIEW

**Comment by albertnetymk** [comment]
> so that the method AgeTable::print_on prints the right tenuring threshold

Can you elaborate on this? As I understand the code, whether computing the threshold at the end of young-gc-pause or at the start of (next) young-gc-pause doesn't make any diff in the value of the threshold.

Also, why does this patch remove `age_table()->print_age_table..`?

**Comment by lgxbslgx** [comment]
> Can you elaborate on this? As I understand the code, whether computing the threshold at the end of young-gc-pause or at the start of (next) young-gc-pause doesn't make any diff in the value of the threshold.

Just like the G1, the normal flow is:
- Compute the threshold according to the last age table
- Run GC and tenure according to the threshold
- Print the threshold and the age table

But in current serial GC, the flow is:
- Run GC and tenure according to the new threshold.
- **Compute the new threshold according to the last age table.**
- Print the threshold and the age table.

The last two steps of the serial GC are wrong. Because **the threshold we print is not the threshold we used during GC**.

> Also, why does this patch remove `age_table()->print_age_table..`?

I just moved it to the end of the GC. Notice the `adjust_desired_tenuring_threshold` is moved to the start of the GC.

**Comment by lgxbslgx** [comment]
> 1. the printed threshold and age-table are directly related -- the threshold is calculated from the age-table.
> 2. the printed threshold and age-table are corresponding to the just finished gc-pause (since printing is at the end of gc-pause). IOW, threshold is used during scavenging and age-table is populated during scavenging.
>
> I think what you have in mind is 2 (right?), and that is what G1 does.

Yes, I think the second one is right.

If we use the first one, please consider such condition:
- The threshold used by GC is 13, so the first 14 rows of the age table has non-zero values.
-  Assume the new threshold is computed to 12.
- Then the message we print, `Age table with threshold 12`, is strange, because the age table we then print has 14 rows of non-zero values.

If you still think the second one is better. The `Age table with threshold %u (max threshold %u)` may be revised to a clearer message. And the G1 could be adjusted too.

```C++
void AgeTable::print_on(outputStream* st, uint tenuring_threshold) {
  st->print_cr("Age table with threshold %u (max threshold %u)",
               tenuring_threshold, MaxTenuringThreshold);
```

**Comment by ysramakrishna** [comment]
In https://bugs.openjdk.org/browse/JDK-8328278, you state:

> But the Serial GC computes tenuring threshold and prints new age table both after per GC. It causes the method `AgeTable::print_on` prints the wrong tenuring threshold.

Can you provide examples on how it "prints the wrong tenuring threshold" to illustrate the bug you had in mind that this is attempting to fix?

**Comment by ysramakrishna** [comment]
Where you state above that:

> Then the message we print, Age table with threshold 12, is strange, because the age table we then print has 14 rows of non-zero values.

That's OK, because the threshold 12 is the new threshold computed based on the age table stats presented in the table, corresponding to the demographics recorded in _this_ collection. The new tenuring threshold will be used in the next collection.

May be we can start by sharing, as I requested in my previous comment, with a G1GC and a SerialGC log and discuss what is the bug you are trying to fix. It's better to use concrete examples rather than describing the output in English sentences.

**Comment by lgxbslgx** [comment]
> 1. the printed threshold and age-table are directly related -- the threshold is calculated from the age-table.
> 2. the printed threshold and age-table are corresponding to the just finished gc-pause (since printing is at the end of gc-pause). IOW, threshold is used during scavenging and age-table is populated during scavenging.

@ysramakrishna  Previously, I thought the second point is right. So I said `It causes the method AgeTable::print_on prints the wrong tenuring threshold` in my issue description.

> That's OK, because the threshold 12 is the new threshold computed based on the age table stats presented in the table, corresponding to the demographics recorded in this collection. The new tenuring threshold will be used in the next collection.

But now, you and @albertnetymk said the first one is also acceptable and may be better. So currently, the main problem is not that `AgeTable::print_on prints the wrong tenuring threshold`. The problem becomes: **G1 and Serial have inconsistent behaviour**. The G1 prints the old threshold and the Serial GC prints the new threshold. Such inconsistence is obvious when reading the code. So what we should do now is decide which behaviour is right and unify the behaviour of these two GCs.

**Comment by lgxbslgx** [comment]
> That's OK, because the threshold 12 is the new threshold computed based on the age table stats presented in the table, corresponding to the demographics recorded in this collection. The new tenuring threshold will be used in the next collection.

> So what we should do now is decide which behaviour is right and unify the behaviour of these two GCs.

And now, I lean to agree with you that the new threshold should be printed. The message `Age table with threshold %u` can be interpreted as: the threshold is computed according to the following age table.

**Comment by albertnetymk** [comment]
> because the threshold 12 is the new threshold computed based on the age table stats presented in the table, corresponding to the demographics recorded in this collection.

This is how I interpreted the output as well, but Serial and G1 differ here. The printed format is identical, `-Xlog:gc+age=trace`:

```
# Serial
[4.318s][trace][gc,age] GC(2) Age table with threshold 15 (max threshold 15)

# G1
[3.156s][trace][gc,age] GC(4) Age table with threshold 1 (max threshold 15)
```

In the Serial case, `threshold 15` refers to the threshold that will be use in next gc-pause `GC(3)`, while `threshold 1` refers to the value used in current gc-pause `GC(4)`.

(One should check callers of `AgeTable::print_age_table` to get the actual semantics of the printed threshold.)

> May be we can start by sharing, as I requested in my previous comment, with a G1GC and a SerialGC log and discuss what is the bug you are trying to fix.

Hopefully, with the example above, you agree this is a problem?

**Comment by ysramakrishna** [comment]
> Hopefully, with the example above, you agree this is a problem?

Thank you for the examples, and the explanation, Guoxiong and Albert. I agree that it would seem useful to fix the inconsistency. I'll take a look at the proposed changes in light of this. Sorry for the delay.

**Comment by albertnetymk** [comment]
> I agree that it would seem useful to fix the inconsistency.

Terrific.

Regarding how to address the issue, after considering it further, I believe the threshold is not intrinsically linked to the age table. Therefore, it likely makes sense to exclude it from the age-table `print_age_table`. Specific collectors could choose to include the threshold in the log if they find it valuable. Then, this removes the ambiguity in the `print_age_table` output. What do others think?

**Comment by lgxbslgx** [comment]
> Regarding how to address the issue, after considering it further, I believe the threshold is not intrinsically linked to the age table. Therefore, it likely makes sense to exclude it from the age-table `print_age_table`. Specific collectors could choose to include the threshold in the log if they find it valuable. Then, this removes the ambiguity in the `print_age_table` output. What do others think?

I agree. The threshold doesn't need to be printed in `print_age_table`.

**Comment by lgxbslgx** [comment]
> > Regarding how to address the issue, after considering it further, I believe the threshold is not intrinsically linked to the age table. Therefore, it likely makes sense to exclude it from the age-table `print_age_table`. Specific collectors could choose to include the threshold in the log if they find it valuable. Then, this removes the ambiguity in the `print_age_table` output. What do others think?
> 
> I agree. The threshold doesn't need to be printed in `print_age_table`.

If nobody disagrees, I will change the code today.

**Review by albertnetymk — APPROVED** [review]

**Comment by lgxbslgx** [comment]
@albertnetymk Thanks for the review. I updated one test.

And waiting for another review.

**Review by ysramakrishna — COMMENTED** [review]
It looks as if you are now suppressing the tenuring threshold printing entirely? In a sense that is a crucial part of what one looks at in GC logs. May be I am missing something.

Could you share for both G1 and for Serial, the before and after logs with `+PrintTenuringDistribution` ?

**Comment by lgxbslgx** [comment]
> It looks as if you are now suppressing the tenuring threshold printing entirely? In a sense that is a crucial part of what one looks at in GC logs. May be I am missing something.

When computing the threshold, the threshold will be printed. Please read the method `AgeTable::compute_tenuring_threshold`.

> Could you share for both G1 and for Serial, the before and after logs with `+PrintTenuringDistribution` ?

Currently, the option `-XX:+PrintTenuringDistribution` is not available in mainline, we can use `-Xlog:gc+age*=trace` instead.

**Comment by albertnetymk** [comment]
> Could you share for both G1 and for Serial, the before and after logs with +PrintTenuringDistribution ?

Using `-Xlog:gc+age=trace`:

```
## baseline
[5.527s][debug][gc,age] GC(0) Desired survivor size 6979584 bytes, new threshold 1 (max threshold 15)
[5.527s][trace][gc,age] GC(0) Age table with threshold 1 (max threshold 15)
[5.527s][trace][gc,age] GC(0) - age   1:   13959168 bytes,   13959168 total

## new
[4.196s][debug][gc,age] GC(0) Desired survivor size 6979584 bytes, new threshold 1 (max threshold 15)
[4.196s][trace][gc,age] GC(0) Age table:
[4.196s][trace][gc,age] GC(0) - age   1:   13959160 bytes,   13959160 total
```

@lgxbslgx Could you merge master?

**Comment by lgxbslgx** [comment]
> @lgxbslgx Could you merge master?

Merged just now.

**Review by ysramakrishna — APPROVED** [review]
Thanks for the before / after logs. This looks good to me. Reviewed.

**Comment by lgxbslgx** [comment]
@albertnetymk @ysramakrishna Thanks for the review.

/integrate

**Pull request closed without merging**
