### PR TITLE
8295276: AArch64: Add backend support for half float conversion intrinsics

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
This patch adds aarch64 backend support for library intrinsics that implement conversions between half-precision and single-precision floats.

Ran the following benchmarks to assess the performance with this patch -

org.openjdk.bench.java.math.Fp16ConversionBenchmark.floatToFloat16 org.openjdk.bench.java.math.Fp16ConversionBenchmark.float16ToFloat

The performance (ops/ms) gain with the patch on an ARM NEON machine is shown below -
```

  Benchmark                                      Gain
  Fp16ConversionBenchmark.float16ToFloat         3.42
  Fp16ConversionBenchmark.floatToFloat16         5.85
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295276](https://bugs.openjdk.org/browse/JDK-8295276): AArch64: Add backend support for half float conversion intrinsics

### Reviewers
 * [Nick Gasson](https://openjdk.org/census#ngasson) (@nick-arm - **Reviewer**)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Ningsheng Jian](https://openjdk.org/census#njian) (@nsjian - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10796/head:pull/10796` \
`$ git checkout pull/10796`

Update a local copy of the PR: \
`$ git checkout pull/10796` \
`$ git pull https://git.openjdk.org/jdk pull/10796/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10796`

View PR using the GUI difftool: \
`$ git pr show -t 10796`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10796.diff">https://git.openjdk.org/jdk/pull/10796.diff</a>

</details>

### CODE REVIEW

**Comment by Bhavana-Kilambi** [comment]
Could anyone please take a look at this PR and give their feedback ? Thank you ..

**Review by nick-arm — APPROVED** [review]
Looks OK to me but needs another review.

**Review by theRealAph — APPROVED** [review]

**Review by nsjian — APPROVED** [review]
Looks good.

**Pull request closed without merging**
