### PR TITLE
8327824: Type annotation placed on incorrect array nesting levels

### PR DESCRIPTION
**Pull request by liach**
Please review this patch that fixes placement of type annotations on array types in Javadoc output. This oversight seems to have existed since JDK 8 but was never noticed or reported.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327824](https://bugs.openjdk.org/browse/JDK-8327824): Type annotation placed on incorrect array nesting levels (**Bug** - P4)

### Reviewers
 * [Pavel Rappo](https://openjdk.org/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18211/head:pull/18211` \
`$ git checkout pull/18211`

Update a local copy of the PR: \
`$ git checkout pull/18211` \
`$ git pull https://git.openjdk.org/jdk.git pull/18211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18211`

View PR using the GUI difftool: \
`$ git pr show -t 18211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18211.diff">https://git.openjdk.org/jdk/pull/18211.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18211#issuecomment-1990249510)

### CODE REVIEW

**Comment by pavelrappo** [comment]
I've read your discussion with @cushon in the comment section for [the bug](https://bugs.openjdk.org/browse/JDK-8327824) and I agree that type annotations on arrays are unintuitive. Welp, we should make sure they are documented correctly.

Do you know if there's a test that exercises this particularly surprising bit from [Example 10.2-2. Array Variables and Array Types](https://docs.oracle.com/javase/specs/jls/se21/html/jls-10.html#d5e20110)?

> And perhaps surprisingly, the following field declarations have the same array type:
>
>     int @A [] f @B [];
>     int @B [] @A [] g;

If there isn't, we should add it.

**Review by pavelrappo — COMMENTED** [review]
I looked into it; that wasn't easy :sweat_smile:.

7 years ago a seemingly similar bug, <https://bugs.openjdk.org/browse/JDK-8068737>, was fixed in _javac_. It's only now that javadoc is catching up.

Your change seems to be correct, but it disrupts the visitor's pattern. On the other hand, maybe keeping the change confined to `visitArray` is for the better here.

Here's what's left to be done:

- resolve merge conflicts due to recently integrated https://github.com/openjdk/jdk/pull/18179
- add a couple more test cases; for example, the JLS one that I mentioned earlier and maybe extract something from JBS-8068737

Thanks for doing it.

**Comment by cushon** [comment]
Thanks for this! The changes look good to me overall.

**Comment by liach** [comment]
Now fixed merge conflict and added a test case for JLS 10.2-2, with the 2 styles of declarations present in the parameter and the return type respectively.

**Review by pavelrappo — APPROVED** [review]
This PR passes our CI and looks good; thanks.

**Pull request closed without merging**
