### PR TITLE
8265285: Unnecessary inclusion of bytecodeHistogram.hpp

### PR DESCRIPTION
**Pull request by kelthuzadx**
Remove unnecessary inclusion of bytecodeHistogram.hpp

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265285](https://bugs.openjdk.java.net/browse/JDK-8265285): Unnecessary inclusion of bytecodeHistogram.hpp

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3530/head:pull/3530` \
`$ git checkout pull/3530`

Update a local copy of the PR: \
`$ git checkout pull/3530` \
`$ git pull https://git.openjdk.java.net/jdk pull/3530/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3530`

View PR using the GUI difftool: \
`$ git pr show -t 3530`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3530.diff">https://git.openjdk.java.net/jdk/pull/3530.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Looks like these files refer to `(BytecodeCounter)|(BytecodeHistogram)(BytecodePairHistogram)` but are missing the inclusion of bytecodeHistogram.hpp

- cpu/aarch64/macroAssembler_aarch64.cpp
- cpu/arm/macroAssembler_arm.cpp
- cpu/x86/macroAssembler_x86.cpp

See https://github.com/iklam/tools/blob/main/headers/find_include_problems.sh

**Comment by kelthuzadx** [comment]
> Looks like these files refer to `(BytecodeCounter)|(BytecodeHistogram)(BytecodePairHistogram)` but are missing the inclusion of bytecodeHistogram.hpp
> 
> * cpu/aarch64/macroAssembler_aarch64.cpp
> * cpu/arm/macroAssembler_arm.cpp
> * cpu/x86/macroAssembler_x86.cpp
> 
> See https://github.com/iklam/tools/blob/main/headers/find_include_problems.sh
> 
> The problems can usually be found by building without precompiled headers.

Yes, the inclusion of bytecodeHistogram.hpp in sharedRuntime.hpp should remain, others are really unnecessary.(Build without precompile header)

**Review by dholmes-ora — APPROVED** [review]
Seems okay.

Thanks,
David

**Comment by iklam** [comment]
> > Looks like these files refer to `(BytecodeCounter)|(BytecodeHistogram)(BytecodePairHistogram)` but are missing the inclusion of bytecodeHistogram.hpp
> > 
> > * cpu/aarch64/macroAssembler_aarch64.cpp
> > * cpu/arm/macroAssembler_arm.cpp
> > * cpu/x86/macroAssembler_x86.cpp
> > 
> > See https://github.com/iklam/tools/blob/main/headers/find_include_problems.sh
> > The problems can usually be found by building without precompiled headers.
> 
> Yes, the inclusion of bytecodeHistogram.hpp in sharedRuntime.hpp should remain, others are really unnecessary.(Build without precompile header)

sharedRuntime.hpp does not need to include bytecodeHistogram.hpp, since it doesn't use any of the 3 classes declared in bytecodeHistogram.hpp. You should add sharedRuntime.hpp to the 3 files I listed above instead.

**Comment by kelthuzadx** [comment]
> > > Looks like these files refer to `(BytecodeCounter)|(BytecodeHistogram)(BytecodePairHistogram)` but are missing the inclusion of bytecodeHistogram.hpp
> > > 
> > > * cpu/aarch64/macroAssembler_aarch64.cpp
> > > * cpu/arm/macroAssembler_arm.cpp
> > > * cpu/x86/macroAssembler_x86.cpp
> > > 
> > > See https://github.com/iklam/tools/blob/main/headers/find_include_problems.sh
> > > The problems can usually be found by building without precompiled headers.
> > 
> > 
> > Yes, the inclusion of bytecodeHistogram.hpp in sharedRuntime.hpp should remain, others are really unnecessary.(Build without precompile header)
> 
> sharedRuntime.hpp does not need to include bytecodeHistogram.hpp, since it doesn't use any of the 3 classes declared in bytecodeHistogram.hpp. You should add bytecodeHistogram.hpp to the 3 files I listed above instead.

It's indeed more reasonable but needs more changes, I will try to tweak this later.

> Seems okay.
> 
> Thanks,
> David

Thank you David!

**Comment by kelthuzadx** [comment]
> > > Looks like these files refer to `(BytecodeCounter)|(BytecodeHistogram)(BytecodePairHistogram)` but are missing the inclusion of bytecodeHistogram.hpp
> > > 
> > > * cpu/aarch64/macroAssembler_aarch64.cpp
> > > * cpu/arm/macroAssembler_arm.cpp
> > > * cpu/x86/macroAssembler_x86.cpp
> > > 
> > > See https://github.com/iklam/tools/blob/main/headers/find_include_problems.sh
> > > The problems can usually be found by building without precompiled headers.
> > 
> > 
> > Yes, the inclusion of bytecodeHistogram.hpp in sharedRuntime.hpp should remain, others are really unnecessary.(Build without precompile header)
> 
> sharedRuntime.hpp does not need to include bytecodeHistogram.hpp, since it doesn't use any of the 3 classes declared in bytecodeHistogram.hpp. You should add bytecodeHistogram.hpp to the 3 files I listed above instead.

Hi Ioi, I've added `#include "interpreter/bytecodeHistogram.hpp"` in macroAssembler_<cpu>.cpp you listed above. Build passed w and w/o precompile header in x64.

**Review by iklam — APPROVED** [review]
LGTM

**Review by dholmes-ora — APPROVED** [review]
Still LGTM.

Thanks,
David

**Comment by kelthuzadx** [comment]
Thanks Ioi and David for reviews.

/integrate

**Pull request closed without merging**
