### PR TITLE
8242332: Add SHA3 support to SunPKCS11 provider

### PR DESCRIPTION
**Pull request by valeriepeng**
Could someone please help review this RFE? SunPKCS11 provider is updated with SHA-3 support, including MessageDigest, Hmac Mac, DSA/RSA/RSASSA-PSS/ECDSA Signature, and Hmac KeyGenerator.

As SHA-3 can be used as drop-in replacement for SHA-2 which are already supported by SunPKCS11 provider, the changes for MessageDigest, Mac, and Signature are straightforward. P11KeyGenerator class is updated to support general Hmac key generation including SHA-3 and more. 

While testing against NSS 3.57, there are some unexpected NSS errors with CKM_ECDSA_SHA[224/256/384/512/3_224/3_256/3_384/3_512] and CKM_DSA_SHA[224/256/384/512/3_224/3_256/3_384/3_512], so I disabled those mechanisms in the NSS config file for regression tests. For ECDSA signatures, SunPKCS11 provider will fallback to CKM_ECDSA and do the digesting ourselves.

Thanks,
Valerie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8242332](https://bugs.openjdk.java.net/browse/JDK-8242332): Add SHA3 support to SunPKCS11 provider

### Reviewers
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**) ⚠️ Review applies to 7b0d788278961e6e702c5a5ce7b54738d4d48a4a

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1546/head:pull/1546`
`$ git checkout pull/1546`

### CODE REVIEW

**Comment by valeriepeng** [comment]
Please also review CSR at https://bugs.openjdk.java.net/browse/JDK-8256082
Thanks~

**Review by XueleiFan — APPROVED** [review]
Looks good to me.

**Comment by valeriepeng** [comment]
> 
> 
> Looks good to me.

Thanks for the quick review~

**Pull request closed without merging**
