### PR TITLE
8242652: Throw SkippedException if no JS engine availabe in TestSearchScript

### PR DESCRIPTION
**Pull request by hns**
This is a simple change to throw jtreg.SkippedException if no JavaScript engine is available to run the TestSearchScript test. In my previous attempt I tried to use the SkippedException class already present elsewhere in the test tree, not realizing I couuld just copy/create the exception in the javadoc test library.

Note that while the test is skipped correctly if no JS engine is available, the test will currently fail in the presence of a JS engine such as GraalJS. This is fixed by JDK-8244535.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ❌ (6/6 failed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x64 (build debug)](https://github.com/hns/jdk/runs/1460085272)
- [Linux x64 (build hotspot minimal)](https://github.com/hns/jdk/runs/1460085338)
- [Linux x64 (build hotspot no-pch)](https://github.com/hns/jdk/runs/1460085293)
- [Linux x64 (build hotspot optimized)](https://github.com/hns/jdk/runs/1460085359)
- [Linux x64 (build hotspot zero)](https://github.com/hns/jdk/runs/1460085313)
- [Linux x64 (build release)](https://github.com/hns/jdk/runs/1460085235)
- [Linux x86 (build debug)](https://github.com/hns/jdk/runs/1460085447)
- [Linux x86 (build release)](https://github.com/hns/jdk/runs/1460085431)

### Issue
 * [JDK-8242652](https://bugs.openjdk.java.net/browse/JDK-8242652): Throw SkippedException if no JS engine availabe in TestSearchScript

### Reviewers
 * [Pavel Rappo](https://openjdk.java.net/census#prappo) (@pavelrappo - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1412/head:pull/1412`
`$ git checkout pull/1412`

### CODE REVIEW

**Comment by pavelrappo** [comment]
@hns, why did you decide to duplicate that exception locally instead of using it as a dependency?

**Comment by hns** [comment]
> @hns, why did you decide to duplicate that exception locally instead of using it as a dependency?

The exception class is available in test/lib but I couldn't make the test see and use that class. I tried all combinations of paths (relative to the test class, relative to the repository root, etc). I think it's the correct solution to add the class to the lib folder of the javadoc tests. 

BTW jtreg doesn't provide this class, it is meant to be defined in test library code as described here: https://github.com/openjdk/jtreg/blob/master/src/share/doc/javatest/regtest/faq.md#what-if-a-test-does-not-apply-in-a-given-situation

**Comment by dfuch** [comment]
I would have expected:

```
 * @library /test/lib
```

to do the trick.

**Comment by dfuch** [comment]
> I would have expected:
> 
> ```
>  * @library /test/lib
> ```
> 
> to do the trick.

Oh - I see that `test/jdk/TEST.ROOT` has these three lines below, that `test/langtools/TEST.ROOT` doesn't seem to have. 
Maybe that's related...

````
# Path to libraries in the topmost test directory. This is needed so @library
# does not need ../../ notation to reach them
external.lib.roots = ../../
```

**Comment by hns** [comment]
> ```
> external.lib.roots = ../../
> ```

Thanks @dfuch, that's exactly what was missing, adding that line makes `@library /test/lib` work. I'll update this PR to use the existing exception class.

**Review by pavelrappo — APPROVED** [review]
This change looks good to me. Since you've changed `test/langtools/TEST.ROOT`, please make sure all the langtools tests pass (not just `TestSearchScript.java`) before integrating this change.

**Pull request closed without merging**
