### PR TITLE
Update HttpURLConnection.java

### PR DESCRIPTION
**Pull request by anupamdev20**
Updated commments in getResponseCode method of HttpURLConnection.java

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1091/head:pull/1091`
`$ git checkout pull/1091`

### CODE REVIEW

**Comment by FrauBoes** [comment]
Hi @anupamdev20 I'm happy to sponsor this small fix. To progress, you need to create a JBS issue and have the fix reviewed. Once it's ready, you can `/integrate` to mark the PR as ready for integration, after that I `/sponsor` to integrate.

**Comment by anupamdev20** [comment]
Thanks @FrauBoes . Kindly look at the pull request https://github.com/openjdk/jdk/pull/1250 . This is outdated and I will close it.

**Pull request closed without merging**
