### PR TITLE
8316658: serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java fails intermittently

### PR DESCRIPTION
**Pull request by jpbempel**
increase Metaspace size and loop count to avoid OOME in nominal case

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8316658](https://bugs.openjdk.org/browse/JDK-8316658): serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java	fails intermittently (**Bug** - P3)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [157ef53b](https://git.openjdk.org/jdk/pull/15882/files/157ef53b3d9ba19523ff035c523f5a855d6c7a2c)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15882/head:pull/15882` \
`$ git checkout pull/15882`

Update a local copy of the PR: \
`$ git checkout pull/15882` \
`$ git pull https://git.openjdk.org/jdk.git pull/15882/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15882`

View PR using the GUI difftool: \
`$ git pr show -t 15882`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15882.diff">https://git.openjdk.org/jdk/pull/15882.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15882#issuecomment-1731336589)

### CODE REVIEW

**Comment by jpbempel** [comment]
Thanks!
/integrate

**Comment by dholmes-ora** [comment]
Hold on! I tested a change to 17M only. Sure 24M will work fine to avoid the OOM, but does it still fail without the original fix? The boost to 1000 iterations is untested and may lead to new failures, so I will have to re-test this again before it is integrated.

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
The test still fails with these new settings.  As per JBS I found 17m worked fine with the existing iterations and still caused an unfixed VM to fail. With 24M and 500 iterations the unfixed VM passes.

**Comment by jpbempel** [comment]
On my side, 17M with 500 iterations on an unpatched VM does not fail.
That's why I have boosted the number of iterations and increased the Metaspace to magnify the leak and also avoid fixed cost of loading test infrastructure into Metaspace.
I have tested 17M/700 iterations successfully

**Comment by dholmes-ora** [comment]
Re-testing at 17M/700

**Comment by dholmes-ora** [comment]
Okay 17M/700 seems to work okay in our CI, and fails without the fix.

**Review by dholmes-ora — APPROVED** [review]

**Comment by jpbempel** [comment]
Thanks!
/integrate

**Pull request closed without merging**
