### PR TITLE
8287362: FieldAccessWatch testcase failed on AIX platform

### PR DESCRIPTION
**Pull request by takiguc**
On AIX platform, `test/hotspot/jtreg/serviceability/jvmti/FieldAccessWatch/FieldAccessWatch.java` testcase failed by single testcase execution.

Failure message is:
```
Error occurred during initialization of VM
agent library failed to init: FieldAccessWatch
Failed to set capabilities, error: 98
```
It seems following initialization code affects this issue
```
jvmtiCapabilities caps = {0};
```
So additionally `memset()` is required just for AIX platform

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287362](https://bugs.openjdk.java.net/browse/JDK-8287362): FieldAccessWatch testcase failed on AIX platform

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8904/head:pull/8904` \
`$ git checkout pull/8904`

Update a local copy of the PR: \
`$ git checkout pull/8904` \
`$ git pull https://git.openjdk.java.net/jdk pull/8904/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8904`

View PR using the GUI difftool: \
`$ git pr show -t 8904`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8904.diff">https://git.openjdk.java.net/jdk/pull/8904.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Given 99.9% of the tests don't try to initialize "caps" but instead do the memset, I would suggest it is perfectly fine to delete the initializer and remove the comments related to AIX/xlclang.

You may also need to check
hotspot/jtreg/runtime/jni/FastGetField/libFastGetField.c 
hotspot/jtreg/compiler/jsr292/cr8026328/libTest8026328.c
which have a similar usage for the callbacks structure.

**Comment by TheRealMDoerr** [comment]
I agree with David.
In addition, I suggest reporting this issue to the xlclang folks.

**Comment by takiguc** [comment]
Hello @dholmes-ora and @TheRealMDoerr .
I appreciate your suggestions.
I checked other files which were use `jvmtiEventCallbacks` structure initializer.
`jvmtiEventCallbacks` structure was initialized properly with AIX's xlclang compiler.
It seems only `jvmtiCapabilities` structure initializer does not work as expected with xlclang.
I tried to create small testcase for this issue.
According to `jvmti.h`, `jvmtiCapabilities` structure likes:
```
typedef struct {
    unsigned int can_tag_objects : 1;
    unsigned int can_generate_field_modification_events : 1;
    unsigned int can_generate_field_access_events : 1;
    unsigned int can_get_bytecodes : 1;
......
    unsigned int can_generate_sampled_object_alloc_events : 1;
    unsigned int can_support_virtual_threads : 1;
    unsigned int : 3;
    unsigned int : 16;
    unsigned int : 16;
    unsigned int : 16;
    unsigned int : 16;
    unsigned int : 16;
} jvmtiCapabilities;
```
This structure can handle bits and it has padding data without variable name.
It seems xlclang initializes only variable name is available by initializer.
So last part is not initialized.
If I put dummy variable name into above structure, all bytes are initialized properly.
I checked other source files which used `jvmtiCapabilities` structure, they used `memset()` instead of initializer.
I removed `jvmtiCapabilities` and `jvmtiEventCallbacks` initializer and add `memset()`

**Review by TheRealMDoerr — APPROVED** [review]

**Pull request closed without merging**
