### PR TITLE
8255477: Remove unused method URL.set(String protocol, String host, int port, String file, String ref)

### PR DESCRIPTION
**Pull request by stsypanov**
Hello, while working with `java.net.URL` I've found unused package-private method `URL.set(String protocol, String host, int port, String file, String ref)` which can be safely removed from JDK. Testing: tier1, tier2

Could someone crate an issue for tracking of this simple change?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255477](https://bugs.openjdk.java.net/browse/JDK-8255477): Remove unused method URL.set(String protocol, String host, int port, String file, String ref)

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/779/head:pull/779`
`$ git checkout pull/779`

### CODE REVIEW

**Comment by shipilev** [comment]
Submitted [here](https://bugs.openjdk.java.net/browse/JDK-8255477), please try to update the PR title to "8255477: Remove unused method URL.set(String protocol, String host, int port, String file, String ref)". Also, merge from master to get the test fixes, which should make the "Testing" all green.

**Comment by stsypanov** [comment]
@shipilev thanks for filing the issue! Done.

**Comment by shipilev** [comment]
Please merge from master to get a fresh round of testing. @AlanBateman might want to look at it.

**Comment by stsypanov** [comment]
Done!

**Comment by dfuch** [comment]
I'll have a look at this when I can spare some cycles. @stsypanov did you run tier2 tests?

**Comment by stsypanov** [comment]
@dfuch 
Recent run has some errors:
```
java/net/MulticastSocket/SetOutgoingIf.java: Re-test IPv6 (and specifically MulticastSocket) with latest Linux & USAGI code
java/net/MulticastSocket/Test.java: IPv4 and IPv6 multicasting broken on Linux
java/time/test/java/time/format/TestDateTimeFormatterBuilder.java:
sun/security/pkcs11/Secmod/AddTrustedCert.java: make sure we can add a trusted cert to the NSS KeyStore module
sun/security/util/HostnameMatcher/NullHostnameCheck.java: Verify hostname returns an exception instead of null pointer when creating a new engine
```
First two are related to unavailable network, for them I have `Unexpected exception for MulticastSender(wlp1s0): java.net.SocketException: Network is unreachable` and `java.net.SocketException: Network is unreachable`

For the third I have
```
test test.java.time.format.TestDateTimeFormatterBuilder.test_dayPeriodParse(NARROW, en_US, 1, 30, "at night"): failure
java.time.format.DateTimeParseException: Text 'at night' could not be parsed, unparsed text found at index 1
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1880)
	at test.java.time.format.TestDateTimeFormatterBuilder.test_dayPeriodParse(TestDateTimeFormatterBuilder.java:645)
```
Which also seems to be not related to `URL`.
For the forth I have
```
----------System.err:(21/1603)----------
java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1050)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetCertificateEntry(P11KeyStore.java:516)
	at java.base/java.security.KeyStore.setCertificateEntry(KeyStore.java:1228)
	at AddTrustedCert.main(AddTrustedCert.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storeCert(P11KeyStore.java:1568)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1046)
	... 9 more
```
And the last one is
```
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:238)
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:107)
	at NullHostnameCheck.handshake(NullHostnameCheck.java:124)
	at NullHostnameCheck.main(NullHostnameCheck.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by dfuch** [comment]
Thanks Sergey! 

These errors are strange but I agree: they don't seem to be related to URL; Let me try to build & test your changes in our test system.

best regards,

-- daniel

**Comment by dfuch** [comment]
I believe the errors are caused by the branch not being uptodate with the master. After rebasing my tests have come back green. Unless I hear objections, I'll sponsor this fix for you.

**Review by dfuch — APPROVED** [review]

**Comment by AlanBateman** [comment]
I think Daniel is going to sponsor this.

**Comment by dfuch** [comment]
Sorry - I lost track of this - thanks of reminding me. I will sponsor later today.

**Pull request closed without merging**
