### PR TITLE
8272735: Add missing SubL node transformations

### PR DESCRIPTION
**Pull request by ahmedmuhsin**
This change adds/enables missing subnode transformations for operations of type `long`.
A few comments in the test file `SubINodeIdealizationTests.java` were modified to add clarity and to fix a typo.
Hotspot:tier1 tests were run, this change does not introduce any new failures.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272735](https://bugs.openjdk.java.net/browse/JDK-8272735): Add missing SubL node transformations

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7669/head:pull/7669` \
`$ git checkout pull/7669`

Update a local copy of the PR: \
`$ git checkout pull/7669` \
`$ git pull https://git.openjdk.java.net/jdk pull/7669/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7669`

View PR using the GUI difftool: \
`$ git pr show -t 7669`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7669.diff">https://git.openjdk.java.net/jdk/pull/7669.diff</a>

</details>

### CODE REVIEW

**Comment by ahmedmuhsin** [comment]
Hey @TobiHartmann. Yep, @JohnTortugo and I reviewed this change together offline. The `AddINode` and `AddLNode` items that Cesar listed in his JBS issue were taken care of in [JDK-8278471: Remove unreached rules in AddNode::IdealIL](https://bugs.openjdk.java.net/browse/JDK-8278471#). This PR resolves the items that are left.

**Review by TobiHartmann — APPROVED** [review]
Thanks for clarifying. The change looks good to me.

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too!

**Pull request closed without merging**
