### PR TITLE
8272446 C1: Raw version of UnsafeGet generates load barriers

### PR DESCRIPTION
**Pull request by stefank**
Please review this patch to remove load barriers from the "raw" version of UnsafeGet.

After rebasing the ZGC Generational code to latest openjdk/jdk we hit a crash because a load barrier was generated for some oops that are not supposed to have a load barrier. In upstream ZGC this isn't a problem because these load barriers are just redundant and will find healed good oops. However, in the Generational version un-barriered roots (e.g. thread stacks) have no metadata bits, and we should never perform normal load barriers on them (they are handled by stack watermarks and nmethod barriers).

This load barrier was introduced with:
JDK-8266746: C1: Replace UnsafeGetRaw with UnsafeGet when setting up OSR entry block

which makes UnsafeGet _also_ handle "raw" loads. However, the "raw" path introduced a load barrier. Note that "raw" is often used to denote a function that loads/stores values without using a barrier.

I've tested this with tier1-3 and have had some initial set of eyes looking over the patch, but it would be good to scrutinize this patch and the usage of UnsafeGet in GraphBuilder::setup_osr_entry_block.

@TheRealMDoerr could you check if this patch works with PPC?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272446](https://bugs.openjdk.java.net/browse/JDK-8272446): C1: Raw version of UnsafeGet generates load barriers

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to 6c9f8fc92d1e50d913670263d72e505eefae1948
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**) ⚠️ Review applies to 6c9f8fc92d1e50d913670263d72e505eefae1948

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5109/head:pull/5109` \
`$ git checkout pull/5109`

Update a local copy of the PR: \
`$ git checkout pull/5109` \
`$ git pull https://git.openjdk.java.net/jdk pull/5109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5109`

View PR using the GUI difftool: \
`$ git pr show -t 5109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5109.diff">https://git.openjdk.java.net/jdk/pull/5109.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good.

**Review by veresov — APPROVED** [review]
Looks good.

**Comment by stefank** [comment]
@fisk @veresov Thanks for reviewing!

**Pull request closed without merging**
