### PR TITLE
8258810: Improve enum traits

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review these miscellaneous improvements to the enum iteration facility.
Thanks to @albertnetymk for discussions.

(1) Removed some unneeded stuff from EnumIterationTraits.

(2) Various similar bits of error checking code are unified and shared via
EnumIterationTraits.

(3) Casts between the enum type and the underlying type are now done using
helper functions in EnumIterationTraits.

(4) JDK-8257466 added accessors for the EnumRange bounds and the index for
an enumerator, but didn't account for the possibility of an empty subrange.
Add assertions for that case.

(5) Added some death tests to verify some of the error checking.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258810](https://bugs.openjdk.java.net/browse/JDK-8258810): Improve enum traits

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - Author) ⚠️ Review applies to cb889e87d33c97313e2591dcb7a72288222d9170
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**) ⚠️ Review applies to a4667b70d6629da1c2e19124334f1f2d737459bd
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to a4667b70d6629da1c2e19124334f1f2d737459bd

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1868/head:pull/1868`
`$ git checkout pull/1868`

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]
I think `assert(size() > 0)` is more consistent with preceding documentation than `assert_not_empty()` in `first()` and `last()`. Very subjective though; up to you.

**Review by iklam — APPROVED** [review]
Looks good to me

**Comment by kimbarrett** [comment]
Thanks @albertnetymk and @iklam for reviews.  Still need another reviewer, since @albertnetymk is not yet a committer.

**Review by lfoltan — APPROVED** [review]
LGTM.
Lois

**Pull request closed without merging**
