### PR TITLE
8303418: Improve parameter and variable names in BitMap

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to names in BitMap.

- Parameters that designate a bit in a BitMap are named "bit".
- Parameters that designate a word in the underlying BitMap storage are named "word".
- Parameters that designate a range are named "beg" and "end" resp.

Added helper function `flipped_word` for use by `get_next_bit_impl`, replacing
the odd overload for `map`.

In `get_next_bit_impl`, prefixed the variables "index" and "limit" with
"word_" to make clear the units.

Testing:
mach5 tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303418](https://bugs.openjdk.org/browse/JDK-8303418): Improve parameter and variable names in BitMap

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [59138b0f](https://git.openjdk.org/jdk/pull/12798/files/59138b0f650512009efabf800f045ad061cb5d4e)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer) ⚠️ Review applies to [59138b0f](https://git.openjdk.org/jdk/pull/12798/files/59138b0f650512009efabf800f045ad061cb5d4e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12798/head:pull/12798` \
`$ git checkout pull/12798`

Update a local copy of the PR: \
`$ git checkout pull/12798` \
`$ git pull https://git.openjdk.org/jdk pull/12798/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12798`

View PR using the GUI difftool: \
`$ git pr show -t 12798`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12798.diff">https://git.openjdk.org/jdk/pull/12798.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

It would be great to also fix the unusual spacing between method names and the parameter brackets (and the method body brackets) a little, but that can be a different issue.

**Review by xmas92 — APPROVED** [review]
Nice to see a _bit_ more consistency in the parameter names here.

Not 100% sold on the use of `bit` for a single bit index. But at least consistency makes it clearer. 

As long as `beg` and `end` are used for `[beg,end)` ranges then the names are appropriate. If they ever start to deviate from the `std::begin` and `std::end` semantics they should be changed to avoid confusion.

**Comment by kimbarrett** [comment]
> Not 100% sold on the use of `bit` for a single bit index. But at least consistency makes it clearer.

In this change I was mostly trying to remove outliers in parameter naming.
I'm not wedded to either `bit` or `word`, but that is the common usage.

**Comment by kimbarrett** [comment]
Thanks for reviews @tschatzl and @xmas92

**Pull request closed without merging**
