### PR TITLE
8316396: Endless loop in C2 compilation triggered by AddNode::IdealIL

### PR DESCRIPTION
**Pull request by rwestrel**
A number of SubI nodes are laid out in a binary tree. There are <100
SubI nodes involved but the tree is fairly deep, and balanced and has
200+ millions of nodes that is the relately small number of SubI nodes
are arranged in a way that they build a 200+ millions node tree.

The `AddNode::IdealIL()` transform:

"(a-b)+(c-d)" into "(a+c)-(b+d)"

is applied at the root of the tree. Because `tranform()` is called on
the resulting a+c and b+d, the same transformation is applied to each
and recursively down the tree. So there's no endless loop but very
slow progress because c2 is busy walking and transforming a large
tree. There's a lot of redundant work done on the way, because the
tree is composed of a relatively small number of nodes. The fix I
proposed is to not call `tranform()` but enqueue a+c and b+d with
igvn. Some subtrees are shared in the large tree of `SubI`
nodes. Calling `tranform()` only causes the node in the tree that
called it to be updated while, when delaying to igvn, all uses of the
subtree are updated with the transformed subtree.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316396](https://bugs.openjdk.org/browse/JDK-8316396): Endless loop in C2 compilation triggered by AddNode::IdealIL (**Bug** - P2)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15923/head:pull/15923` \
`$ git checkout pull/15923`

Update a local copy of the PR: \
`$ git checkout pull/15923` \
`$ git pull https://git.openjdk.org/jdk.git pull/15923/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15923`

View PR using the GUI difftool: \
`$ git pr show -t 15923`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15923.diff">https://git.openjdk.org/jdk/pull/15923.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15923#issuecomment-1735598472)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me but I'm wondering if other, similar optimizations aren't affected by this as well? Could you please add a comment, explaining why we avoid transform here?

**Review by TobiHartmann — APPROVED** [review]
Thanks for adding the comment, looks good to me.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Comment by rwestrel** [comment]
@TobiHartmann @vnkozlov thanks for the reviews.

**Pull request closed without merging**
