### PR TITLE
8142362: Lots of code duplication in Copy class

### PR DESCRIPTION
**Pull request by coleenp**
Removed an unused assembly function on one platform (_Copy_conjoint_bytes), and consolidated the linux and bsd x86, and linux and bsd aarch64 copy code that was duplicated.  There's unfortunately now an #ifndef _WINDOWS in copy_x86.hpp and copy_aarch64.hpp, and I couldn't combine the duplicate copy_<arch>.S files because Windows doesn't have this file (and couldn't convince the build system to ignore the .S file for windows).
I didn't think it was worth adding an os_cpu/posix_x86 and os_cpu/posix_aarch64 directory for this small bit of code.

There could be more consolidation but the platform differences are subtle.  This change just moves around code without poking this bear.

Tested with tier1 on Oracle platforms, build on linux-x86-open,linux-s390x-open,linux-arm32-debug,linux-ppc64le-debug and Zero (zero in progress).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8142362](https://bugs.openjdk.java.net/browse/JDK-8142362): Lots of code duplication in Copy class

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6984/head:pull/6984` \
`$ git checkout pull/6984`

Update a local copy of the PR: \
`$ git checkout pull/6984` \
`$ git pull https://git.openjdk.java.net/jdk pull/6984/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6984`

View PR using the GUI difftool: \
`$ git pr show -t 6984`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6984.diff">https://git.openjdk.java.net/jdk/pull/6984.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by coleenp** [comment]
Thanks Vladimir!

**Review by hseigel — APPROVED** [review]
Looks good!
Thanks, Harold

**Comment by coleenp** [comment]
Thanks Harold!
/integrate

**Pull request closed without merging**
