### PR TITLE
8333653: Remove MallocHeader::get_stack

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

A small and trivial enhancement, I think. Today, MallocHeader knows about the `MallocSiteTable` and vice versa. That seems a bit strange to me, as it is just a data carrier. Just have only MallocSiteTable be aware of MallocHeader by deleting a method from MallocHeader.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333653](https://bugs.openjdk.org/browse/JDK-8333653): Remove MallocHeader::get_stack (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [cd0f0572](https://git.openjdk.org/jdk/pull/19562/files/cd0f0572f17b3a3174349715831fe24811ae57ac)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19562/head:pull/19562` \
`$ git checkout pull/19562`

Update a local copy of the PR: \
`$ git checkout pull/19562` \
`$ git pull https://git.openjdk.org/jdk.git pull/19562/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19562`

View PR using the GUI difftool: \
`$ git pr show -t 19562`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19562.diff">https://git.openjdk.org/jdk/pull/19562.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19562#issuecomment-2150212447)

### CODE REVIEW

**Comment by jdksjolen** [comment]
/label add hotspot-runtime

Ping @afshin-zafari,  @tstuefe

**Review by tstuefe — APPROVED** [review]
Yes. Good decoupling.

**Comment by tstuefe** [comment]
I think its trivial. Feel free to push it.

**Comment by jdksjolen** [comment]
Thanks!

/integrate

**Comment by tstuefe** [comment]
@jdksjolen you forgot to remove the nativeCallStack.hpp include. Don't think its needed anymore.

**Pull request closed without merging**
