### PR TITLE
8295191: IR framework timeout options expect ms instead of s

### PR DESCRIPTION
**Pull request by enothum**
The flags `-DTestCompilationTimeout` and `-DWaitForCompilationTimeout` expect values in ms. The example in the README was misleading as one could infer from "default: 10s" that the flag expects values in ms. Therefore I changed the values and units in the example to ms.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295191](https://bugs.openjdk.org/browse/JDK-8295191): IR framework timeout options expect ms instead of s (**Bug** - P5)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14649/head:pull/14649` \
`$ git checkout pull/14649`

Update a local copy of the PR: \
`$ git checkout pull/14649` \
`$ git pull https://git.openjdk.org/jdk.git pull/14649/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14649`

View PR using the GUI difftool: \
`$ git pr show -t 14649`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14649.diff">https://git.openjdk.org/jdk/pull/14649.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14649#issuecomment-1607216513)

### CODE REVIEW

**Comment by enothum** [comment]
Reverted the changes in README.
Changed the code to now expect a value in seconds from the user. 
The timing itself is still implemented in milliseconds, which is why I added MS to the internal variable name.

**Review by chhagedorn — CHANGES_REQUESTED** [review]
That looks good but you also need to update the new variable names here:
https://github.com/openjdk/jdk/blob/c3f10e847999ec254893de5a1a5de32fd07f715a/test/hotspot/jtreg/compiler/lib/ir_framework/test/CustomRunTest.java#L136-L140

**Comment by enothum** [comment]
True good catch, thank you!

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by enothum** [comment]
Thanks for the reviews everyone!

**Pull request closed without merging**
