### PR TITLE
JDK-8298298: NMT: count deltas are printed with 32-bit signed size

### PR DESCRIPTION
**Pull request by tstuefe**
Deltas for counts in NMT differential reports are shown as signed int, restricting them to +-2g. These counts are number of malloc blocks, or number of classes, or number of threads. In all cases number of physically existing somethings.

On large 64-bit machines they can conceivably overflow. Well, at least the malloc block counters. Granted, mallocing even just >2g number of 1 byte blocks costs about 40-50GB due to overhead in libc and NMT (on glibc). But it is conceivable.

Patch changes delta printing from int to ssize_t.

Note that I don't worry about overflowing SSIZE_MIN or SSIZE_MAX here. That would be ridiculous: we just cannot have that many physically existing things. Not on 64bit, not even on 32-bit where ssize_t is int, since in both cases the address space would be the limit. So, if the counters are that large, we have a different problem (probably counter overflow), and so we assert, resp. in release, ignore it.

Note we have the same problem with diff sizes. I expect [8281213](https://bugs.openjdk.org/browse/JDK-8281213) to fix that.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298298](https://bugs.openjdk.org/browse/JDK-8298298): NMT: count deltas are printed with 32-bit signed size

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [22a577f2](https://git.openjdk.org/jdk/pull/11568/files/22a577f2b67935daf56e39d29924a928af9be361)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [5bc8d60a](https://git.openjdk.org/jdk/pull/11568/files/5bc8d60a1d4677470d83e3696d31eaa3584df371)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11568/head:pull/11568` \
`$ git checkout pull/11568`

Update a local copy of the PR: \
`$ git checkout pull/11568` \
`$ git pull https://git.openjdk.org/jdk pull/11568/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11568`

View PR using the GUI difftool: \
`$ git pr show -t 11568`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11568.diff">https://git.openjdk.org/jdk/pull/11568.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Tested: fastdebug and release for 32-bit/64-bit, runtime/NMT and NMT gtests

**Review by shipilev — APPROVED** [review]
Looks okay to me.

**Comment by shipilev** [comment]
Windows builds are failing in GHA, though.

**Comment by tstuefe** [comment]
> Looks okay to me.

Thanks!

> Windows builds are failing in GHA, though.

Really, Windows? No SSIZE_MAX? Sigh

**Comment by tstuefe** [comment]
> Seems reasonable.
> 
> Thanks.

Thanks, David!

**Comment by tstuefe** [comment]
All tests are good.

/integrate

**Pull request closed without merging**
