### PR TITLE
8285383: vmTestbase/nsk/jvmti/scenarios/hotswap/HS204/hs204t001/hs204t001.java failed with "exit code: 96"

### PR DESCRIPTION
**Pull request by alexmenkov**
The fix deletes bad test.

Background:
The test does not work as described in the test summary.
It supposed to redefine test class from ClassLoad/ClassFileLoadHook/ClassPrepare/ClassFileLoadHook callbacks and then suspend the thread and do PopFrame, but actually it does a single redefinition from ClassPrepare. Redefinition from ClassLoad never happens, redefinition from ClassFileLoadHook is commented out.

Actually the scenario is not good at all.
ClassLoad, ClassPrepare and ClassFileLoadHook events are wrong places to redefine classes.
When we redefine a class and try to redefine it again from ClassLoad we actually cannot redefine it. 2nd (3rd, etc.) redefinition should complete before the 1st one, and 2nd version of the class becomes obsolete immediately.
ClassFileLoadHook can be used to replace class bytes, but it should return new class bytes via parameters instead of calling redefineClasses.
Testing for PopFrame does not add any value. With the scenario all redefinition happen before the test object is created, so this PopFrame has nothing to do with class redefinition.
Class redefinition when some methods of the class are executed is covered by other tests from vmTestbase/nsk/jvmti/scenarios/hotswap

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285383](https://bugs.openjdk.org/browse/JDK-8285383): vmTestbase/nsk/jvmti/scenarios/hotswap/HS204/hs204t001/hs204t001.java failed with "exit code: 96"

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10318/head:pull/10318` \
`$ git checkout pull/10318`

Update a local copy of the PR: \
`$ git checkout pull/10318` \
`$ git pull https://git.openjdk.org/jdk pull/10318/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10318`

View PR using the GUI difftool: \
`$ git pr show -t 10318`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10318.diff">https://git.openjdk.org/jdk/pull/10318.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Probably should have made it  clear in the main PR comment that
you are deleting a bad test.

Thumbs up. This is a trivial fix, but you should wait for a review from
a Serviceability team member.

**Comment by lmesnik** [comment]
Do we have a way to reproduce https://bugs.openjdk.org/browse/JDK-8228404 if the test is removed?

**Comment by alexmenkov** [comment]
> Do we have a way to reproduce https://bugs.openjdk.org/browse/JDK-8228404 if the test is removed?

It's hard to consider this test as a reproducer for JDK-8228404
There were 3 "bad oop found" failures - July 2019 (jdk 14), Feb 2020 (jdk 15) and Apr 2022 (jdk 19)
And 1 Kitchensink24HStress.java failure (Jan 2020 (jdk 14))

**Review by lmesnik — APPROVED** [review]
Looks good

**Review by sspitsyn — APPROVED** [review]
LGTM
Thanks,
Serguei

**Pull request closed without merging**
