### PR TITLE
8330247: C2: CTW fail with assert(adr_t->is_known_instance_field()) failed: instance required

### PR DESCRIPTION
**Pull request by JohnTortugo**
The logic in reduce allocation merges (RAM) makes use of `PhaseMacroExpand:;can_eliminate_allocation` to check whether an allocation can be scalar replaced. However, we can only SR allocations of exact types - due to rematerialization logic.

The scalar replacement logic not related to RAM has this check in `split_unique_types` so there is no performance regression by adding this check here.

Tested on Linux x64 tiers1-3.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330247](https://bugs.openjdk.org/browse/JDK-8330247): C2: CTW fail with assert(adr_t-&gt;is_known_instance_field()) failed: instance required (**Bug** - P3)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18851/head:pull/18851` \
`$ git checkout pull/18851`

Update a local copy of the PR: \
`$ git checkout pull/18851` \
`$ git pull https://git.openjdk.org/jdk.git pull/18851/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18851`

View PR using the GUI difftool: \
`$ git pr show -t 18851`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18851.diff">https://git.openjdk.org/jdk/pull/18851.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18851#issuecomment-2065546069)

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Good.

Did you run CTW test from bug report? Is it possible to extract simple reproducer from it and add it to this PR?

**Comment by JohnTortugo** [comment]
Yes, I was able to reproduce the failure using CTW and a JAR file. I'll work to create a test case and include in this PR.

**Comment by JohnTortugo** [comment]
@vnkozlov - I just pushed a test case to trigger the issue. When you have time please run your tests on it. Thank you!

**Comment by vnkozlov** [comment]
I submitted testing.

**Review by vnkozlov — APPROVED** [review]
My testing passed.

**Comment by JohnTortugo** [comment]
Thank you @vnkozlov

**Pull request closed without merging**
