### PR TITLE
8331541: [i386] linking with libjvm.so fails after JDK-8283326

### PR DESCRIPTION
**Pull request by vpa1977**
Hi, 

The     `.type _SafeFetch32_impl,@function` symbol declaration contains a spurious underscore causing an undefined symbol in libjvm.so.

I am not sure about change in default flags. I have removed the flag that allows linking with undefined symbols
because having the flag on might cause bugs like this one or https://bugs.openjdk.org/browse/JDK-8329983 as the build succeeds even if some symbols are not defined.
Openjdk builds successfully without it on amd64, i386, armhf, arm64, s390, ppc64el and riscv64 with this change[1]. riscv64 build was done locally inside vm:
```
Finished building target 'images' in configuration 'linux-riscv64-server-release'
ubuntu@ubuntu:~/jdk$ 
```
Unfortunately I do not know why it was introduced, so I might be missing something.
I am happy to drop it from this one or move it to a separate issue/pr.
 
[1] https://launchpad.net/~vpa1977/+archive/ubuntu/october-21/+sourcepub/16076564/+listing-archive-extra

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331541](https://bugs.openjdk.org/browse/JDK-8331541): [i386] linking with libjvm.so fails after JDK-8283326 (**Bug** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19048/head:pull/19048` \
`$ git checkout pull/19048`

Update a local copy of the PR: \
`$ git checkout pull/19048` \
`$ git pull https://git.openjdk.org/jdk.git pull/19048/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19048`

View PR using the GUI difftool: \
`$ git pr show -t 19048`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19048.diff">https://git.openjdk.org/jdk/pull/19048.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19048#issuecomment-2095356149)

### CODE REVIEW

**Comment by magicus** [comment]
I'm not sure why we have `--allow-shlib-undefined`, but changing this should not affect libjvm building. Do you really see a difference in build success/failure depending on that line?

**Comment by vpa1977** [comment]
> I'm not sure why we have `--allow-shlib-undefined`, but changing this should not affect libjvm building. Do you really see a difference in build success/failure depending on that line?

Hi, 

Thank you for looking at the issue!!! 

Removing the setting just prevents typos like this from getting into code base. I did a rebuild on all arches I had access to validate that master does not have any more undefined symbols.

**Review by djelinski — APPROVED** [review]
Looks good to me. Mach5 and GHA agree that we don't need explicit `allow-shlib-undefined` anymore.

On a side note, our use of `.type` appears to serve no purpose other than introducing errors. Perhaps we could remove all the useless `.type` lines in a follow up PR.

**Comment by magicus** [comment]
Ok, I think I'm understanding this better now. The error occurs since the `.type`, `.globl` and `.hidden` directives do not match -- we define the global symbol to be `SafeFetch32_impl` but then we set the type of the non-existing symbol `_SafeFetch32_impl`. Somehow this tricks the linker into accepting this as an undefined symbol.

The `.type` directive is not without purpose -- it sets the type of the symbol to be a function. If omitted, the type will be `NOTYPE`. Apparently this does not break the program but there is no reason to remove the `.type` directives.

Instead, we should have a common macro, something like this:
```
#define DECLARE_FUNC(func) \
.globl func ; \
.hidden func ; \
.type func,@function ; \
func:

```

in a shared file, and include and use it for all symbols in our hotspot assembly files. I was thinking somewhat along those lines last time I was poking around there (when introducing .hidden for the removal of the hotspot map files), but never really got around to it. This bug really shows why we should do that.

**Review by magicus — APPROVED** [review]
So, after sleeping on this, here is my analysis/verdict:
1) The fix on renaming the `.type` directive looks good. This is the actual bug fix.

2) We can remove `--allow-shlib-undefined`. That just overrides `--no-allow-shlib-
undefined`, which has been the default for years and years, and there is no good reason to have it. It is not strictly related to the bug fix per se, but we can do that in this PR as well to keep things simpler.

3) The reason this could happen was since we used assembler code. A similar problem in C++ code would not have been allowed by the compiler.

4) If we introduce a common macro as I suggest, we can avoid this ever happening again. So while the linker cannot guarantee the consistency when linking libjvm.so (which I really would have liked), by using a stricter scheme when defining symbols in assembly code, we can make sure to avoid it.

**Comment by magicus** [comment]
I created https://bugs.openjdk.org/browse/JDK-8331921 to track setting up proper assembly functions consistently.

**Pull request closed without merging**
