### PR TITLE
8286571: java source launcher from a minimal jdk image containing jdk.compiler fails with --enable-preview option

### PR DESCRIPTION
**Pull request by asotona**
### Problem description
Minimal jdk image created by jlink with the only jdk.compiler module and its dependencies
fails to run java source launcher correctly (for example when --source N is specified).
Failing source launcher is only one the expressions of internal jdk.compiler malfunction, another example is failure to run javac with --release option.

### Root cause
Module jdk.compiler requires zip filesystem (jdk.zipfs module) to parse ct.sym file and so to provide full functionality.
Module jdk.zipfs is not included in the minimal JDK image, because module jdk.compiler does not declare it as "requires" in its module info.

### Alternative patch
The problem can be alternatively resolved by complex code checks in jdk.compiler to provide user with valid error message, however that solution would be just a workaround for jdk.compiler dual functionality (with or without presence of jdk.zipfs module). Compiler functionality without access to ct.sym through jdk.zipfs is very limited. 

### Proposed fix
This patch fixes the problem by explicit declaration of jdk.compiler dependency on jdk.zipfs.
Plus added specific test case.

Please review the patch or raise objections against declaration of jdk.compiler dependent on jdk.zipfs.

Thanks,
Adam

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286571](https://bugs.openjdk.org/browse/JDK-8286571): java source launcher from a minimal jdk image containing jdk.compiler fails with --enable-preview option

### Reviewers
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8747/head:pull/8747` \
`$ git checkout pull/8747`

Update a local copy of the PR: \
`$ git checkout pull/8747` \
`$ git pull https://git.openjdk.java.net/jdk pull/8747/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8747`

View PR using the GUI difftool: \
`$ git pr show -t 8747`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8747.diff">https://git.openjdk.java.net/jdk/pull/8747.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Adam, I don't have necessary knowledge of this area, so I don't know what approach would be preferred.

But a couple of questions:

- If we do decide to add the `jdk.zipfs` dependency to `jdk.compiler` module, do you think the `LimitedImage` test is still relevant? Or should it be removed? The comment on that test states:
> @summary Verify javac behaves properly in absence of zip/jar FileSystemProvider

and it does so by using `--limit-modules`. But now with the `jdk.zipfs` being a dependency, the zip/jar FileSystemProvider will not be absent and the test then would seem unnecessary.

- In the JBS issue corresponding to this PR, you noted that:

>There are actually two different issues:
>
>First in JDKPlatformProvider, which silently swallows ProviderNotFoundException. 

Should something be done there? I see that the catch block happens to reside in the `static` block of that class (which also happens to be a implementation of a Java `service`), so I'm unsure what if anything can be done there.

**Comment by dholmes-ora** [comment]
/label remove hotspot-runtime

Nothing hotspot-runtime related here

**Comment by asotona** [comment]
> Hello Adam, I don't have necessary knowledge of this area, so I don't know what approach would be preferred.
> 
> But a couple of questions:
> 
> * If we do decide to add the `jdk.zipfs` dependency to `jdk.compiler` module, do you think the `LimitedImage` test is still relevant? Or should it be removed? The comment on that test states:
> 
> > @summary Verify javac behaves properly in absence of zip/jar FileSystemProvider
> 
> and it does so by using `--limit-modules`. But now with the `jdk.zipfs` being a dependency, the zip/jar FileSystemProvider will not be absent and the test then would seem unnecessary.

You are right, the test description should change. The test name is LimitedImage and it verifies that javac behaves properly in limited JDK image. I think the purpose of the test is still the same, just results are different (now it pass compilation instead of failing with specific error).

Thanks for pointing it out.

> 
> * In the JBS issue corresponding to this PR, you noted that:
> 
> > There are actually two different issues:
> > First in JDKPlatformProvider, which silently swallows ProviderNotFoundException.
> 
> Should something be done there? I see that the catch block happens to reside in the `static` block of that class (which also happens to be a implementation of a Java `service`), so I'm unsure what if anything can be done there.

Silent swallow of an exception in static initializer of a service is not very good practice and it has significant effect on this issue right now. However it will express itself only in corner cases (like for example broken ct.sym file) after this patch is integrated.

**Comment by lahodaj** [comment]
FWIW, if adding this dependency would be seen unacceptable, we could try to tweak jlink to at least produce a warning when building an image with jdk.compiler but without jdk.zipfs.

**Comment by jaikiran** [comment]
Thank you for changing the description of the test. That part now looks fine to me.

**Comment by plevart** [comment]
My humble opinion: if java.compiler needs jdk.zipfs for full functionality (i.e. using --source N or --release X), does that mean java.compiler is useless without jdk.zipfs? If there is a meaningful functionality left in java.compiler even without jdk.zipfs, then someone might want to use that limited subset of functionality and might not want to include jdk.zipfs in its image.
So what is possible to do with java.compiler without jdk.zipfs?

**Comment by plevart** [comment]
> My humble opinion: if java.compiler needs jdk.zipfs for full functionality....

Sorry, I wrongly assumed it was `java.compiler` (the library module), but this is about `jdk.compiler` (the tool)... Nevertheless, the same question applies: Does `jdk.compiler` have any meaningful functionality even without `jdk.zipfs` ?

**Comment by asotona** [comment]
> > My humble opinion: if java.compiler needs jdk.zipfs for full functionality....
> 
> Sorry, I wrongly assumed it was `java.compiler` (the library module), but this is about `jdk.compiler` (the tool)... Nevertheless, the same question applies: Does `jdk.compiler` have any meaningful functionality even without `jdk.zipfs` ?

Basic compilation works even without presence of jdk.zipfs, however such stripped JDK is for example unable to read jar files on classpath.

**Comment by AlanBateman** [comment]
> Sorry, I wrongly assumed it was `java.compiler` (the library module), but this is about `jdk.compiler` (the tool)... Nevertheless, the same question applies: Does `jdk.compiler` have any meaningful functionality even without `jdk.zipfs` ?

This came up in JDK 9 and the decision at the time was not to require jdk.zipfs as it's a service provider module. The addition of the source launcher, the addition of --enable-preview, and more use of --release N means more ct.sym usage. It probably isn't too interesting to have a small runtime image that contains jdk.compiler and not jdk.zipfs so Adam's proposal mightn't be too bad, it's just a bit weird and not something that we'd want other libraries in the eco system to do.

**Review by lahodaj — APPROVED** [review]
Looks like a reasonable compromise to me.

**Pull request closed without merging**
