### PR TITLE
8256857: ARM32 builds broken after JDK-8254231

### PR DESCRIPTION
**Pull request by shipilev**
Foreign linker broke ARM32 builds. This change stubs out the new entry points, without implementing the actual support yet.

Additional testing:
 - [x] Linux arm fastdebug cross-compilation

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ⏳ (1/1 running) | ⏳ (1/1 running) | ⏳ (1/1 running) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ⏳ (6/9 running) |    |  ⏳ (9/9 running) | ⏳ (3/9 running) |

**Failed test tasks**
- [Linux x86 (build debug)](https://github.com/shipilev/jdk/runs/1446781244)
- [Linux x86 (build release)](https://github.com/shipilev/jdk/runs/1446781218)

### Issue
 * [JDK-8256857](https://bugs.openjdk.java.net/browse/JDK-8256857): ARM32 builds broken after JDK-8254231

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - Committer) ⚠️ Review applies to d20a662439196b539e1e4d5501f9d962a6bb26c2
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1383/head:pull/1383`
`$ git checkout pull/1383`

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
LGTM.

Though, note that the style guide asks to prefer `nullptr` to `NULL`: https://github.com/openjdk/jdk/blob/master/doc/hotspot-style.md#nullptr

```
nullptr

Prefer nullptr (n2431) to NULL. Don't use (constexpr or literal) 0 for pointers.

For historical reasons there are widespread uses of both NULL and of integer 0 as a pointer value.
```

**Comment by shipilev** [comment]
> Though, note that the style guide asks to prefer `nullptr` to `NULL`: https://github.com/openjdk/jdk/blob/master/doc/hotspot-style.md#nullptr

Fixed. Please push your Zero integration first, and then I rebase this one?

**Comment by JornVernee** [comment]
@shipilev Done. Though I'm not a `jdk` reviewer, so another review is needed for this PR.

But, as the person most familiar with the code, it looks good to me.

**Comment by shipilev** [comment]
Thanks @JornVernee, no problem. Anyone to formally ack this? Let's unbreak more builds!

**Comment by shipilev** [comment]
Current patch makes ARM builds pass, but then it fails at runtime with:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/pi/jdk/src/hotspot/cpu/arm/methodHandles_arm.cpp:233), pid=21071, tid=21076
#  assert(ref_kind != 0 || iid == vmIntrinsics::_invokeBasic) failed: must be _invokeBasic or a linkTo intrinsic
```

Let me try and fix that too.

**Comment by shipilev** [comment]
Runtime error is now resolved the [same way Zero resolves it](https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/zero/methodHandles_zero.cpp#L211).

**Review by tstuefe — APPROVED** [review]
LGTM

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
