### PR TITLE
8282633: jarsigner output does not explain why an EC key is disabled if its curve has been disabled

### PR DESCRIPTION
**Pull request by haimaychao**
When a named curve is disabled in `jdk.disabled.namedCurves` property which is included in `jdk.jar.disabledAlgorithms` and `jdk.certpath.disabledAlgorithms`, `jarsigner` should display the disabled named curve as a result of its disabled algorithm constraint checking. This clarifies why an EC key is disabled in its warning and verbose output.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282633](https://bugs.openjdk.java.net/browse/JDK-8282633): jarsigner output does not explain why an EC key is disabled if its curve has been disabled

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7810/head:pull/7810` \
`$ git checkout pull/7810`

Update a local copy of the PR: \
`$ git checkout pull/7810` \
`$ git pull https://git.openjdk.java.net/jdk pull/7810/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7810`

View PR using the GUI difftool: \
`$ git pr show -t 7810`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7810.diff">https://git.openjdk.java.net/jdk/pull/7810.diff</a>

</details>

### CODE REVIEW

**Comment by wangweij** [comment]
I think `include jdk.disabled.namedCurves` can also appear in the legacy algorithms, so it's likely there should also be a "key.bit.eccurve.weak" for jarsigner.

**Comment by haimaychao** [comment]
Individual name curves could be added to `jdk.security.legacyAlgorithms` instead of by `jdk.disabled.namedCurves`, so changed `jarsigner` to display the named curves in the legacy algorithms.

**Comment by haimaychao** [comment]
@wangweij Thanks for the review.

**Pull request closed without merging**
