### PR TITLE
8273218: G1: Rename g1EvacuationInfo to g1EvacInfo

### PR DESCRIPTION
**Pull request by Hamlin-Li**
This is a minor cleanup to rename g1EvacuationInfo to g1EvacInfo, as other similar files are named as EvacXxx.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273218](https://bugs.openjdk.java.net/browse/JDK-8273218): G1: Rename g1EvacuationInfo to g1EvacInfo

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 75a2cfebe47d265971f11ae2efe1a976c55e1e1e
 * [Albert Mingkun Yang](https://openjdk.java.net/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to 75a2cfebe47d265971f11ae2efe1a976c55e1e1e

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5325/head:pull/5325` \
`$ git checkout pull/5325`

Update a local copy of the PR: \
`$ git checkout pull/5325` \
`$ git pull https://git.openjdk.java.net/jdk pull/5325/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5325`

View PR using the GUI difftool: \
`$ git pr show -t 5325`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5325.diff">https://git.openjdk.java.net/jdk/pull/5325.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

Note that because you were so fast posting this, I do not know what others think about the name change in this direction, but I think it's okay. Please wait for further feedback.

**Review by albertnetymk — APPROVED** [review]

**Comment by Hamlin-Li** [comment]
> Lgtm.
> 
> Note that because you were so fast posting this, I do not know what others think about the name change in this direction, but I think it's okay. Please wait for further feedback.

Sure, I will wait for a while before push.
Thanks for your reviews, @tschatzl @albertnetymk

**Comment by albertnetymk** [comment]
Some code seems removed by accident in the latest commit. @Hamlin-Li

**Comment by Hamlin-Li** [comment]
Thanks for reminding, I've fixed the issue.
Yes. I'm not sure how this happened, I generated a patch from one machine, then applied the patch in another one, some source code was missing.

**Comment by tschatzl** [comment]
Since nobody objected for a week, this seems good to go.

**Comment by Hamlin-Li** [comment]
Thanks for your reviews, @tschatzl @albertnetymk

**Pull request closed without merging**
