### PR TITLE
8281043: Intrinsify recursive ObjectMonitor locking for PPC64

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
PPC64 implementation of JDK-8277180.

`java -Xms4g -Xmx4g -jar dacapo-9.12-bach.jar h2 -s huge -t 1 -n 1 --max-iterations=35 --variance=5 --verbose --converge`

Before this patch (2 runs):
`===== DaCapo 9.12 h2 PASSED in 309753 msec =====`
`===== DaCapo 9.12 h2 PASSED in 300755 msec =====`

After:
`===== DaCapo 9.12 h2 PASSED in 285144 msec =====`
`===== DaCapo 9.12 h2 PASSED in 288255 msec =====`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281043](https://bugs.openjdk.java.net/browse/JDK-8281043): Intrinsify recursive ObjectMonitor locking for PPC64

### Reviewers
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7305/head:pull/7305` \
`$ git checkout pull/7305`

Update a local copy of the PR: \
`$ git checkout pull/7305` \
`$ git pull https://git.openjdk.java.net/jdk pull/7305/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7305`

View PR using the GUI difftool: \
`$ git pr show -t 7305`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7305.diff">https://git.openjdk.java.net/jdk/pull/7305.diff</a>

</details>

### CODE REVIEW

**Comment by reinrich** [comment]
Hi Martin,

the change looks good. Have you tested it with a quick micro benchmark?

The copyright needs to be updated.

Cheers, Richard.

**Comment by TheRealMDoerr** [comment]
Thanks for the review! Copyright updated and benchmark results added above.

**Review by reinrich — APPROVED** [review]
Looks good.

Thanks, Richard.

**Review by RealLucy — APPROVED** [review]
Changes look good to me.
Nice performance gain for such a small change!

**Comment by TheRealMDoerr** [comment]
Thanks!
/integrate

**Pull request closed without merging**
