### PR TITLE
JDK-8280002: jmap -histo may leak stream

### PR DESCRIPTION
**Pull request by tstuefe**
Very trivial fix to a handle/memory leak. 

JDK-8215624 added parallel heap iteration to both `jmap -histo` and `jcmd GC.class_histogram`. When called with an explicit file and an invalid argument for number of threads, it leaks the file (bit of memory and a handle).

Reproduce with:

`jmap -histo:parallel=notanumber,file=xx.txt`

Can only be reproduced with jmap. jcmd is safe, arguments are handled correctly in shared code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280002](https://bugs.openjdk.java.net/browse/JDK-8280002): jmap -histo may leak stream

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 4d27428ddcf3b2c69cdc0a11543578f755aa851c
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7078/head:pull/7078` \
`$ git checkout pull/7078`

Update a local copy of the PR: \
`$ git checkout pull/7078` \
`$ git pull https://git.openjdk.java.net/jdk pull/7078/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7078`

View PR using the GUI difftool: \
`$ git pr show -t 7078`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7078.diff">https://git.openjdk.java.net/jdk/pull/7078.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
This is not as trivial, AFAICS. Note that the existing code `delete fs` after checking `if (os != NULL && os != out)`. Does it mean this patch can effectively `delete out`?

**Comment by tstuefe** [comment]
> This is not as trivial, AFAICS. Note that the existing code `delete fs` after checking `if (os != NULL && os != out)`. Does it mean this patch can effectively `delete out`?

Thanks for looking at this. No, it is safe.

`fs` is a temporary fileStream which may or may not be NULL. It is safe to `delete` it. The delete you mention could be moved out of the condition and it would still be fine. The condition is only really needed for the output which should only appear if you don't write to stdout.

**Review by shipilev — APPROVED** [review]
Okay then!

**Comment by tstuefe** [comment]
> Okay then!

Thanks, Alexey!

After your concerns I consider this to be not trivial enough, so I wait for a second reviewer.

**Review by sspitsyn — APPROVED** [review]
Hi Thomas,
Nice catch.
Looks good to me.
Thanks,
Serguei

**Comment by tstuefe** [comment]
Thanks, @shipilev  and @sspitsyn !

/integrate

**Pull request closed without merging**
