### PR TITLE
8344830: [BACKOUT] JDK-8341334: CDS: Parallel relocation

### PR DESCRIPTION
**Pull request by shipilev**
This caused failures in higher tier testing. We are backing this out to figure test failures out without blocking testing. This also backs out related ProblemList additions: [JDK-8344621](https://bugs.openjdk.org/browse/JDK-8344621). Both are clean `git revert`-s.

Additional testing:
 - [x] Linux x86_64 server fastdebug, `runtime/cds`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344830](https://bugs.openjdk.org/browse/JDK-8344830): [BACKOUT] JDK-8341334: CDS: Parallel relocation (**Sub-task** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22314/head:pull/22314` \
`$ git checkout pull/22314`

Update a local copy of the PR: \
`$ git checkout pull/22314` \
`$ git pull https://git.openjdk.org/jdk.git pull/22314/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22314`

View PR using the GUI difftool: \
`$ git pr show -t 22314`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22314.diff">https://git.openjdk.org/jdk/pull/22314.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22314#issuecomment-2493017291)
</details>

### CODE REVIEW

**Comment by shipilev** [comment]
@dholmes-ora ^

**Review by dholmes-ora — APPROVED** [review]
Backout looks good.

Thanks for doing this. We can revisit next week.

**Comment by shipilev** [comment]
Thanks. Trivial, right?

**Review by jaikiran — APPROVED** [review]
I've verified that this backout merely reverts the original changes done for the following two issues:

https://bugs.openjdk.org/browse/JDK-8341334
https://bugs.openjdk.org/browse/JDK-8344621

Looks good to me.

**Comment by shipilev** [comment]
@jaikiran, you think this is trivial, right? I need this ack to integrate without waiting for 24 hours.

**Comment by jaikiran** [comment]
@shipilev, I believe it's trivial, yes.

**Comment by shipilev** [comment]
OK, good. I am integrating then.

/integrate

**Comment by dholmes-ora** [comment]
@shipilev  Backout PRs are considered trivial

https://openjdk.org/guide/#backing-out-a-change

**Pull request closed without merging**
