### PR TITLE
8257208: Fix typo in doc/building.md

### PR DESCRIPTION
**Pull request by HollowMan6**
overriden -> overridden

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257208](https://bugs.openjdk.java.net/browse/JDK-8257208): Fix typo in doc/building.md

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1365/head:pull/1365`
`$ git checkout pull/1365`

### CODE REVIEW

**Comment by magicus** [comment]
Hi @HollowMan6!

Thank you for submitting this PR. As the contribution docs state, you need a sponsor for this PR. I'll be your sponsor.

I have opened a bug issue for this fix:  https://bugs.openjdk.java.net/browse/JDK-8257208

Please update the PR title to `8257208: Fix typo in doc/building.md`.

**Comment by HollowMan6** [comment]
> Hi @HollowMan6!
> 
> Thank you for submitting this PR. As the contribution docs state, you need a sponsor for this PR. I'll be your sponsor.
> 
> I have opened a bug issue for this fix: https://bugs.openjdk.java.net/browse/JDK-8257208
> 
> Please update the PR title to `8257208: Fix typo in doc/building.md`.

@magicus Done! Thanks.

**Review by magicus — APPROVED** [review]

**Comment by HollowMan6** [comment]
@magicus Thanks for reviewing! Now could you please sponsor this change? Thanks!

**Pull request closed without merging**
