### PR TITLE
8295990: Improve make handling of strip flags

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Strip currently has its flags set by guessing based on the OS, it would be more appropriate to instead set them based on properly checking the strip binary instead of speculating what the correct flags are based on the compiler and OS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295990](https://bugs.openjdk.org/browse/JDK-8295990): Improve make handling of strip flags

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [df46df9d](https://git.openjdk.org/jdk/pull/10882/files/df46df9d6e52e5b833124733a25bdca7c5fbf2fd)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10882/head:pull/10882` \
`$ git checkout pull/10882`

Update a local copy of the PR: \
`$ git checkout pull/10882` \
`$ git pull https://git.openjdk.org/jdk pull/10882/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10882`

View PR using the GUI difftool: \
`$ git pr show -t 10882`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10882.diff">https://git.openjdk.org/jdk/pull/10882.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]
This looks good assuming you have verified that it works on all the affected platforms.

**Comment by TheShermanTanker** [comment]
Tested successfully on Linux with gcc and clang, also with the platform specific strip utils targeting MacOS. Windows with Visual C++ (but importantly only with Visual C++) correctly does not perform the check since the toolchain never sets strip. This change seems to have unintentionally split the strip version from the toolchain type as well, instead categorizing it into 3 independent groups: GNU-like, IBM, and Xcode, which may be helpful in the future should any changes to strip be desired

**Review by erikj79 — APPROVED** [review]

**Comment by TheShermanTanker** [comment]
@erikj79 Could i trouble you for a sponsor? Thanks!

**Pull request closed without merging**
