### PR TITLE
8330047: ASAN build error with gcc 13

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all,

This PR addresses [8330047](https://bugs.openjdk.org/browse/JDK-8330047).

This is the workaround suggested in the comments. Might be worthwhile to include this patch as the recommended toolchain version for [building](https://openjdk.org/groups/build/doc/building.html) the JDK is currently gcc 13.2.0.

[Update June 3rd] 
I modified the patch to use @xmas92's suggestion instead. 

Testing: 
- [x] Reproduced build failure with gcc 13.2.0.
- [x] Verified release build is successful after patch with ```--enable-asan```. 

Thanks, 
Sonia

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330047](https://bugs.openjdk.org/browse/JDK-8330047): ASAN build error with gcc 13 (**Bug** - P4)

### Reviewers
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18825/head:pull/18825` \
`$ git checkout pull/18825`

Update a local copy of the PR: \
`$ git checkout pull/18825` \
`$ git pull https://git.openjdk.org/jdk.git pull/18825/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18825`

View PR using the GUI difftool: \
`$ git pr show -t 18825`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18825.diff">https://git.openjdk.org/jdk/pull/18825.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18825#issuecomment-2064030807)

### CODE REVIEW

**Review by kimbarrett — COMMENTED** [review]
I don't think this change should be made.  There are two problems exhibited by the
current code.  One is that ASAN doesn't seem to properly handle alignas attributes.
The other is that we're misusing alignas attributes.  Fixing the latter would both
eliminate the resulting UB and work around the ASAN bug.

**Comment by tstuefe** [comment]
> I don't think this change should be made. There are two problems exhibited by the current code. One is that ASAN doesn't seem to properly handle alignas attributes. The other is that we're misusing alignas attributes. Fixing the latter would both eliminate the resulting UB and work around the ASAN bug.

Could you elaborate on the misusing?

**Comment by kimbarrett** [comment]
> > I don't think this change should be made. There are two problems exhibited by the current code. One is that ASAN doesn't seem to properly handle alignas attributes. The other is that we're misusing alignas attributes. Fixing the latter would both eliminate the resulting UB and work around the ASAN bug.
> 
> Could you elaborate on the misusing?

[This is summarizing the relevant part of an Oracle-internal discussion about
JDK-8330047 that hasn't yet made it to the JBS issue.]

ZMarkStripe is one of several classes with over-aligned members, via
ZCACHE_ALIGNED. As a result, these classes have over-aligned alignment
requirements. Several of these classes are (indirect) members of
ZCollectedHeap, with the result that it too has an over-aligned alignment
requirement. But there is no code (*) to ensure the allocation of the
ZCollectedHeap instance actually meets that alignment requirement.  And an
object must meet its alignment requirements; failure to do so is UB.

The places where ZCACHE_ALIGNED is being used are doing so to ensure there is
padding between members to avoid false sharing. Rather than using alignas (and
imposing alignment requirements that we don't currently meet and don't
actually need) to cause such padding to be inserted, we should instead insert
padding directly, using the facilities in memory/padded.hpp.

(*) C++17 provides a mechanism for heap allocation of over-aligned types, but
(1) we're not yet using C++17, and (2) we might not implement support for
over-aligned NMT-based heap allocation.

**Comment by xmas92** [comment]
This seems to be caused by a some bug in gcc, specifically in the interaction between `-fsanitize=address` and some optimisation pass which uses `memset` (or a similar construct). This bug can be seen without `alignas` all it requires is that for the last field `F` in and object of type `T` `offsetof(F,T) + sizeof(F) != sizeof(T)`.

This simple reproducer will  show the warnings when compiled with ` -fsanitize=address  -O3` and a `-std` `<= c++17`.  No warnings at `-O2` or below.
```C++
class A {
  double d;
  int i;
};

class B {
  A a[16];
  B();
};

B::B() : a() {
  for (int i = 0; i < 16; i++) {
    a[i] = A();
  }
}
```

d399b0903180bf9f5c31b8e142a2e7bc1b8e8763 handles this I believe by changing how this gets optimised. Another way of solving the compilation error would be to make  `offsetof(_overflowed, ZMarkStripe) + sizeof(_overflowed) == sizeof(ZMarkStripe)`.

The simples change to achieve this is the following:
```diff
-class ZStackList {
+class ZCACHE_ALIGNED ZStackList {
```

This over-aligns the type as well as the storage. And all uses (all storage) of `ZStackList` is currently marked with `ZCACHE_ALIGNED` so it will not change anything with regards to object layouts.

My suggestion is that we take my proposed change to parry for this gcc bug. 

_Some notes on the miss-aligned storage  UB:_

_As for the fact that `ZCollectedHeap` is allocated without being aligned (causing UB), this should be fixed as well but should be done separately. So we can keep using `alignas` instead of padding._ _As regardless of how it is done it tends to be more ugly and create more dependencies between nested classes (w.r.t. object layout). _

_Any over-aligned type (alignment `> 16`) will currently cause UB in `offset_of` as well.  For example, as with `ZCollectedHeap` when it gets registered with `VM_STRUCTS`._

**Comment by tstuefe** [comment]
@SoniaZaldana @xmas92 Thanks, Axel, for the analysis. Either fix is fine for me, as long as ASAN builds. Having to switch compiler toolchains is a hassle, and dependencies like these can stack.

**Comment by tstuefe** [comment]
@SoniaZaldana Could you test @xmas92 's fix? I think that would be a reasonable fix.

**Comment by SoniaZaldana** [comment]
Hi @tstuefe, I verified @xmas92's fix and have updated the patch to use their fix instead. Hopefully this can move things along.

**Review by xmas92 — APPROVED** [review]

**Comment by tstuefe** [comment]
> Hi @tstuefe, I verified @xmas92's fix and have updated the patch to use their fix instead. Hopefully this can move things along.

ASAN builds with gcc13 with this patch, I assume?

**Comment by SoniaZaldana** [comment]
> > Hi @tstuefe, I verified @xmas92's fix and have updated the patch to use their fix instead. Hopefully this can move things along.
> 
> ASAN builds with gcc13 with this patch, I assume?

Correct. I also tested with gcc14.

**Review by tstuefe — APPROVED** [review]
Thanks @SoniaZaldana !

/integrate

**Pull request closed without merging**
