### PR TITLE
8302147: Speed up compiler/jvmci/compilerToVM/IterateFramesNative.java

### PR DESCRIPTION
**Pull request by eme64**
We have two run statements.

The `-Xbatch`  version takes `5 sec`, now `1.5-2.3`.
And the `-Xcomp`  took `19` and now takes `0.5`.

I discussed it with @woess the original author of the test. He suggested this fix.
The first run statement still works as before, the second one, which sets `-Dcompiler.jvmci.compilerToVM.IterateFramesNative.checkCompiled=true` and has `CHECK_COMPILED == true` now only runs one iteration. This should be sufficient, we see that the whitebox checks successfully that the methods were compiled.

**Update**
For `-Xbatch`, I simply reduced the iteration count. We had `CompilerWhiteBoxTest.THRESHOLD = 150_000` iterations, now I reduced it to `10_000`, which should be sufficient.

I would have liked to assert compilation in both cases, but the `-Xbatch` case does not always lead to compilation, especially when we have `-XX:-TieredCompilation`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302147](https://bugs.openjdk.org/browse/JDK-8302147): Speed up compiler/jvmci/compilerToVM/IterateFramesNative.java

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [095ee38b](https://git.openjdk.org/jdk/pull/12496/files/095ee38b4d2ab7b2b7dd974dd11745b0fd19b66d)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12496/head:pull/12496` \
`$ git checkout pull/12496`

Update a local copy of the PR: \
`$ git checkout pull/12496` \
`$ git pull https://git.openjdk.org/jdk pull/12496/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12496`

View PR using the GUI difftool: \
`$ git pr show -t 12496`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12496.diff">https://git.openjdk.org/jdk/pull/12496.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Okay.

**Review by vnkozlov — COMMENTED** [review]
Update is good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Comment by eme64** [comment]
Thanks @woess for the help. Thanks @vnkozlov @TobiHartmann for the reviews!
/integrate

**Pull request closed without merging**
