### PR TITLE
8266013: Unexpected replacement character handling on stateful CharsetEncoder

### PR DESCRIPTION
**Pull request by takiguc**
When an invalid character is converted by getBytes() method, the character is converted to replacement byte data.
Shift code (SO/SI) may not be added into right place by EBCDIC Mix charset.
EBCDIC Mix charset encoder is stateful encoder.
Shift code should be added by switching character set.
On x-IBM1364, "\u3000\uD800" should be converted to "\x0E\x40\x40\x0F\x6F", but "\x0E\x40\x40\x6F\x0F"
SI is not in right place.

Also ISO2022 related charsets use escape sequence to switch character set.
But same kind of issue is there.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8266013](https://bugs.openjdk.java.net/browse/JDK-8266013): Unexpected replacement character handling on stateful CharsetEncoder

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3719/head:pull/3719` \
`$ git checkout pull/3719`

Update a local copy of the PR: \
`$ git checkout pull/3719` \
`$ git pull https://git.openjdk.java.net/jdk pull/3719/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3719`

View PR using the GUI difftool: \
`$ git pr show -t 3719`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3719.diff">https://git.openjdk.java.net/jdk/pull/3719.diff</a>

</details>

### CODE REVIEW

**Comment by takiguc** [comment]
Gentle reminder

Currently stateful CharsetEncoder (like EBCDIC Mix, ISO2022 related) cannot handle replacement characters.
Please give me your suggestion or advice.

**Comment by lppedd** [comment]
Hey! Any way this PR could be picked up again? It could be split into two parts, one for EBCDIC, and one for ISO.  
The EBCDIC part should be straightforward as it should not impact template files.

**Pull request closed without merging**
