### PR TITLE
8281811: assert(_base == Tuple) failed: Not a Tuple after JDK-8280799

### PR DESCRIPTION
**Pull request by rwestrel**
The crash occurs because a Shenandoah barrier is expanded between the
Start node and its control projection. One of the test cases I added
also shows the same failure with a barrier expansion between a MemBar
and its control projection. The barrier is expanded at the control
that PhaseIdealLoop assigns to it.

This code:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/loopnode.cpp#L5756
I added back with JDK-8280799 is what's causing the incorrect
placement of the barrier.

The fix I propose is to skip that logic if the loop opts pass is for
barrier expansion as there's no range check elimination then.

/cc hotspot-compiler

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281811](https://bugs.openjdk.java.net/browse/JDK-8281811): assert(_base == Tuple) failed: Not a Tuple after JDK-8280799

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to a9780037aa7897dcd4589f8ef0af1588b20ae83b
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7494/head:pull/7494` \
`$ git checkout pull/7494`

Update a local copy of the PR: \
`$ git checkout pull/7494` \
`$ git pull https://git.openjdk.java.net/jdk pull/7494/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7494`

View PR using the GUI difftool: \
`$ git pr show -t 7494`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7494.diff">https://git.openjdk.java.net/jdk/pull/7494.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — COMMENTED** [review]
Could you explain what exactly is different in the GC specific loop opts pass that makes this code incorrect?

**Comment by rwestrel** [comment]
Thanks for looking at this.

> Could you explain what exactly is different in the GC specific loop opts pass that makes this code incorrect?

The shenandoah barrier is initially a floating macro node. It needs to be expanded to a series of tests and a call. Because it's floating, the usual macro expansion pass cannot be used. Instead, the barrier expansion logic relies on a loop opts pass that assigns control to the barriers. The control flow is then constructed at the barrier's control. That control needs to be a valid control but because of JDK-8280799, it's not always the case.

**Review by TobiHartmann — APPROVED** [review]
Okay, thanks for the explanation. Looks good to me.

**Comment by rwestrel** [comment]
@vnkozlov @TobiHartmann thanks for the review.

**Pull request closed without merging**
