### PR TITLE
8343607: C2: Shenandoah crashes during barrier expansion in Continuation::enter

### PR DESCRIPTION
**Pull request by rwestrel**
If a load barrier is used both in the fallthrough and exception
handling paths out of a call, it needs to be cloned so each path has
its copy of the barrier. In the case of the crash, cloning the barrier
is attempted for a runtime call that doesn't have an exception
handling path. Fix simply detects that corner case.

/cc hotspot-compiler

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343607](https://bugs.openjdk.org/browse/JDK-8343607): C2: Shenandoah crashes during barrier expansion in Continuation::enter (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22663/head:pull/22663` \
`$ git checkout pull/22663`

Update a local copy of the PR: \
`$ git checkout pull/22663` \
`$ git pull https://git.openjdk.org/jdk.git pull/22663/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22663`

View PR using the GUI difftool: \
`$ git pr show -t 22663`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22663.diff">https://git.openjdk.org/jdk/pull/22663.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22663#issuecomment-2531844545)
</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
This looks reasonable to me. @JohnTortugo should take a look too.

**Comment by JohnTortugo** [comment]
LGTM, thanks for fixing.

**Comment by rwestrel** [comment]
@shipilev @JohnTortugo thanks for the reviews

**Pull request closed without merging**
