### PR TITLE
8338693: assert(Atomic::add(&ik->_shared_class_load_count, 1) == 1) failed: shared class loaded more than once

### PR DESCRIPTION
**Pull request by matias9927**
The test vmTestbase/nsk/sysdict/vm/stress/chain/chain007/chain007.java  occasionally fails due to the number of shared classes being incremented even though the shared class is not loaded. This patch moves the assert to only increment once loading is possible.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8338693](https://bugs.openjdk.org/browse/JDK-8338693): assert(Atomic::add(&amp;ik-&gt;_shared_class_load_count, 1) == 1) failed: shared class loaded more than once (**Bug** - P3)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20955/head:pull/20955` \
`$ git checkout pull/20955`

Update a local copy of the PR: \
`$ git checkout pull/20955` \
`$ git pull https://git.openjdk.org/jdk.git pull/20955/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20955`

View PR using the GUI difftool: \
`$ git pr show -t 20955`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20955.diff">https://git.openjdk.org/jdk/pull/20955.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20955#issuecomment-2346415257)

### CODE REVIEW

**Review by kimbarrett — COMMENTED** [review]
Not a review, just a comment in passing.
`_shared_class_load_count` is declared `NOT_PRODUCT`, but should be
`DEBUG_ONLY` if it's only going to be used in an assert.
I kind of cringe at an assert with side-effects, but since it's debug-only data...

**Comment by dholmes-ora** [comment]
Just to be clear, which early return path did the test trigger and why?

**Comment by iklam** [comment]
We have this pattern (in two different functions) for handling loading failure of `load_shared_class()`:

```
if (ik != nullptr && ik->is_shared_boot_class() && !ik->shared_loading_failed()) {
  SharedClassLoadingMark slm(THREAD, ik);
  k = load_shared_class(ik, class_loader, Handle(), nullptr,  pkg_entry, CHECK_NULL);
}
....
~SharedClassLoadingMark() {
  if (HAS_PENDING_EXCEPTION) {
    if (_klass->is_shared()) {
      _klass->set_shared_loading_failed();
    }
  }
}
```

As Matias discovered, `load_shared_class` could "fail" by returning `nullptr` without throwing an exception. Although moving `Atomic::add` a few lines down catches one of such cases, it's not guaranteed that all subsequent failures inside `load_shared_class()` will always throw an exception.

(We cannot make `load_shared_class()` to always throw exception on failure, as there are normal reasons where a shared class cannot be used).

Also, this pattern forces the caller to know that `load_shared_class` must be used with `SharedClassLoadingMark`, so too much implementation details are leaked to the caller. In fact, we seem to have a bug where `SystemDictionary::load_shared_lambda_proxy_class()` calls `load_shared_class` without using `SharedClassLoadingMark`.

I think it's better to remove `SharedClassLoadingMark`, and change `load_shared_class` to this:

```
InstanceKlass* load_shared_class(InstanceKlass* ik,..., TRAPS) {
  InstanceKlass* loaded_ik = load_shared_class_impl(ik, ...., THREAD);  <-- old body of load_shared_class()
  // we *may* have a pending exception here
  if (loaded_ik != ik) {
    assert(loaded_ik == nullptr, "cannot load alternative class");
    ik->set_shared_loading_failed(); // ik may be partially updated. Never load it again.
  }
  return loaded_ik;
}
```

@coleenp: `load_shared_class()` needs exclusive access to the class and it assumes that the exclusivity is provided by the placeholder mechanism. For sanity, Matias is looking at the core dump to confirm that we don't have two threads calling `load_shared_class()` concurrently.

**Comment by coleenp** [comment]
load_shared_class() does have exclusive access because it's in the same class loading path as regular class loading.  I was a bit worried about check_shared_class_super_type() bypassing this, but doesn't appear that it does.

From my debugging of the case where we return null for check_shared_class_super_type() for the interface, the interface did have the shared_loading_failed() misc_flag set, so it appears that fixing all the cases that set this flag properly will fix this bug.

There's a lot of this _method_ and _method_impl_ pattern in this file, so this is okay.

**Review by iklam — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Based in Ioi's comments this seems reasonable.

Thanks

**Comment by matias9927** [comment]
Thanks for the reviews and comments @iklam @dholmes-ora @coleenp and @kimbarrett!
/integrate

**Pull request closed without merging**
