### PR TITLE
8274227: Remove "impl.prefix" jdk system property usage from InetAddress

### PR DESCRIPTION
**Pull request by AlekseiEfimov**
The following fix proposes to remove usages of `"impl.prefix"` JDK system property from the `java.net.InetAddress` class.
This system property  is used to locate concrete implementations of the package private "java.net.InetAddressImpl" interface.

The list of changes:
 -  `impl.prefix` usages are removed
 -  `InetAddressImpl` made sealed interface by only allowing default implementations available in 'java.net' package: `Inet4AddressImpl` and `Inet6AddressImpl`.

tier1-tier3 tests show no failures  with this fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274227](https://bugs.openjdk.java.net/browse/JDK-8274227): Remove "impl.prefix" jdk system property usage from InetAddress

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5755/head:pull/5755` \
`$ git checkout pull/5755`

Update a local copy of the PR: \
`$ git checkout pull/5755` \
`$ git pull https://git.openjdk.java.net/jdk pull/5755/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5755`

View PR using the GUI difftool: \
`$ git pr show -t 5755`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5755.diff">https://git.openjdk.java.net/jdk/pull/5755.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
This looks fine. I've added the CSR label as I think we should create a CSR to track this removal (it was completely undocumented/unsupported and also required adding classes to java.base/java.net so there should be no issue).

**Comment by dfuch** [comment]
LGTM too. Good to see this old code go away!

**Review by dfuch — APPROVED** [review]

**Pull request closed without merging**
