### PR TITLE
8316608: Enable parallelism in vmTestbase/gc/vector tests

### PR DESCRIPTION
**Pull request by roy-soumadipta**
The commit includes changes to unblock parallelism for more `hotspot:tier4` tests. in `vmTestbase/gc/vector` tests.

Below are the before and after run comparisons:
```
# Fastdebug
before: 3480.71s user 83.97s system 830% cpu 7:09.41 total
after: 2214.52s user 63.19s system 2374% cpu 1:35.94 total

# Release
before: 1369.61s user 147.03s system 371% cpu 6:48.63 total
after: 1130.28s user 110.97s system 2478% cpu 50.089 total
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8316608](https://bugs.openjdk.org/browse/JDK-8316608): Enable parallelism in vmTestbase/gc/vector tests (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16028/head:pull/16028` \
`$ git checkout pull/16028`

Update a local copy of the PR: \
`$ git checkout pull/16028` \
`$ git pull https://git.openjdk.org/jdk.git pull/16028/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16028`

View PR using the GUI difftool: \
`$ git pr show -t 16028`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16028.diff">https://git.openjdk.org/jdk/pull/16028.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16028#issuecomment-1745064276)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
I think this is good, but @tschatzl and @lmesnik need to be looped in for visibility.

/reviewers 2

**Review by lmesnik — APPROVED** [review]
testing didn't show any issues

**Pull request closed without merging**
