### PR TITLE
8259867: Move encoding checks into ZipCoder

### PR DESCRIPTION
**Pull request by eirbjo**
ZipFile.Source.initCEN verifies that entry names are encoding into bytes valid in the entry's encoding. It does so by calling encoding-specific checking methods, so it also needs to determine which check method to call for each entry.

By moving the encoding-variant checks into ZipCoder, initCEN can instead simply call ZipCoder.checkEncoding. This makes the code easier to follow and also removes a duplication of flag checking logic found in zipCoderForPos.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259867](https://bugs.openjdk.java.net/browse/JDK-8259867): Move encoding checks into ZipCoder

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**)
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2110/head:pull/2110`
`$ git checkout pull/2110`

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
Welcome back! 

Patch looks good to me. I'll sponsor it after allowing some time for other reviewers to have a look.

**Review by LanceAndersen — APPROVED** [review]
The change looks good to me as well

**Pull request closed without merging**
