### PR TITLE
8281585: Remove unused imports under test/lib and jtreg/gc

### PR DESCRIPTION
**Pull request by lkorinth**
Remove unused imports under test/lib and jtreg/gc. They create lots of warnings if editing using an IDE. Tests in hotspot_gc passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281585](https://bugs.openjdk.java.net/browse/JDK-8281585): Remove unused imports under test/lib and jtreg/gc

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7426/head:pull/7426` \
`$ git checkout pull/7426`

Update a local copy of the PR: \
`$ git checkout pull/7426` \
`$ git pull https://git.openjdk.java.net/jdk pull/7426/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7426`

View PR using the GUI difftool: \
`$ git pr show -t 7426`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7426.diff">https://git.openjdk.java.net/jdk/pull/7426.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks fine. The proof of these changes is in compiling the files - how did you test the non-gc-test changes?

Thanks,
David

**Comment by dholmes-ora** [comment]
Forgot to mention copyright years need updating before integrating! Thanks.

**Comment by lkorinth** [comment]
I have a maven project that compiles test/lib and jtreg/gc, so everything changed does compile, I should have mentioned that. I have updated copyright year on all files now as well.

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks.

**Pull request closed without merging**
