### PR TITLE
JDK-8296665: IGV: Show dialog with stack trace for exceptions

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Currently in IGV when an exception occurs a small red icon in the bottom right corner appears. The user often does not see this and if he sees it, usually not immediately when the error occurs:
exception now

The exception reporting level is changed to `1000` (Level.SEVERE) in IGV to show a dialog with the stack-trace. The user can still close it and continue the work: 
exception suggestion

To test insert something like the following somewhere in the codebase 
```java
try {
    int i=1/0;
} catch (Exception e) {
    throw new RuntimeException(e);
}
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296665](https://bugs.openjdk.org/browse/JDK-8296665): IGV: Show dialog with stack trace for exceptions

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11060/head:pull/11060` \
`$ git checkout pull/11060`

Update a local copy of the PR: \
`$ git checkout pull/11060` \
`$ git pull https://git.openjdk.org/jdk pull/11060/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11060`

View PR using the GUI difftool: \
`$ git pr show -t 11060`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11060.diff">https://git.openjdk.org/jdk/pull/11060.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. If we start hitting too many exceptions, we might need to (temporarily) disable this again.

Just wondering, isn't there a config file or something to put such Netbeans specific settings instead of passing them as `-J-D` args to the JVM?

**Comment by tobiasholenstein** [comment]
> Looks good to me. If we start hitting too many exceptions, we might need to (temporarily) disable this again.
> 
> Just wondering, isn't there a config file or something to put such Netbeans specific settings instead of passing them as `-J-D` args to the JVM?

Unfortunately, the only config file i know is `<netbeans-install-dir>/etc/idealgraphvisualizer.conf` 
(`jdk/open/src/utils/IdealGraphVisualizer/application/target/idealgraphvisualizer/etc/idealgraphvisualizer.conf`). This file can also be modified after compiling IGV and changes the settings without recompiling.

Another way is to set option in code like the following
```Java
System.setProperty("netbeans.exception.report.min.level", "1000");
```

**Comment by TobiHartmann** [comment]
Okay, thanks for the details. It's probably best to leave the patch as is then.

**Review by chhagedorn — APPROVED** [review]
Makes sense to add this back now that IGV is more stable - looks good!

**Comment by tobiasholenstein** [comment]
thanks @TobiHartmann and @chhagedorn for the reviews!

/integrate

**Pull request closed without merging**
