### PR TITLE
8342862: Gtest added by 8339507 appears to be causing 8GB build machines to hang

### PR DESCRIPTION
**Pull request by hanklo6**
We generate each test randomly. The `asmtest.out.h` is currently around 100 KB. We have added the `--full` argument to allow users to create a complete test set.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342862](https://bugs.openjdk.org/browse/JDK-8342862): Gtest added by 8339507 appears to be causing 8GB build machines to hang (**Bug** - P2)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)
 * @abdelhak-zaaim (no known openjdk.org user name / role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21670/head:pull/21670` \
`$ git checkout pull/21670`

Update a local copy of the PR: \
`$ git checkout pull/21670` \
`$ git pull https://git.openjdk.org/jdk.git pull/21670/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21670`

View PR using the GUI difftool: \
`$ git pr show -t 21670`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21670.diff">https://git.openjdk.org/jdk/pull/21670.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21670#issuecomment-2433526374)

### CODE REVIEW

**Comment by vnkozlov** [comment]
Please, change title of the bug in JBS in this PR to:
"Gtest added by 8339507 appears to be causing 8GB build machines to hang"

It seems "JDK-8339507" at the beginning of title confuses our tools/bots to where add PR link and may cause issues later too.

**Review by vnkozlov — COMMENTED** [review]
Please, update instructions comment in `test_assemblerx86.cpp`.

What subset of instructions will be generated by default?
Did you compare compilation time between files with default and "full" sets of instructions.

**Comment by vnkozlov** [comment]
What if we split it into several files? Will combined compilation time be different? At least it will not consume a lot of memory and page swapping.

**Comment by hanklo6** [comment]
> Please, update instructions comment in `test_assemblerx86.cpp`.
> 
> What subset of instructions will be generated by default? Did you compare compilation time between files with default and "full" sets of instructions.

@vnkozlov The default test set includes the original map0/map1 instructions with random registers, address, and immediate. I tested on my machine (i9-13900k with 32cores), with the compilation time being 10s for the default test and 30s for the full test.

**Comment by hanklo6** [comment]
> What if we split it into several files? Will combined compilation time be different? At least it will not consume a lot of memory and page swapping.

But splitting into several files still results in large code size. We are trying to reduce the code size as well.

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Comment by dholmes-ora** [comment]
What if you split into separate test files (.cpp) as well so that rather than one gtest that checks everything you have several smaller ones. That will reduce compilation overhead as required and also allow full coverage, potentially running tests in parallel.

**Comment by sviswa7** [comment]
> What if you split into separate test files (.cpp) as well so that rather than one gtest that checks everything you have several smaller ones. That will reduce compilation overhead as required and also allow full coverage, potentially running tests in parallel.

Do we really want that? Just to put things in perspective the original file size was 45963 lines and the reduced one is now 1293 lines so we are talking about 35 such files. What Hank has done in this PR is to test each instruction with random register, address, and immediate instead of all the combinations that he had before so we still have a decent coverage. The test generator tool continues to have the ability to generate the full combination optionally.

**Comment by TobiHartmann** [comment]
> What Hank has done in this PR is to test each instruction with random register, address, and immediate instead of all the combinations that he had before so we still have a decent coverage. The test generator tool continues to have the ability to generate the full combination optionally.

I think that is good enough and preferable.

**Review by abdelhak-zaaim — APPROVED** [review]

**Pull request closed without merging**
