### PR TITLE
8322636: [JVMCI] HotSpotSpeculationLog can be inconsistent across a single compile

### PR DESCRIPTION
**Pull request by davleopo**
This PR fixes a subtle inconsistency in `HotSpotSpeculationLog` .

Normal uses of `HotSpotSpeculationLog` work by using a `SpeculationReason` and asking the speculation log via `maySpeculate` if the speculation can be performed, i.e., if it failed before for the given method.  An example for this can be seen in Graal https://github.com/oracle/graal/blob/master/compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/nodes/loop/CountedLoopInfo.java#L591C15-L591C15 
The implicit assumption is that the speculation log, `HotSpotSpeculationLog` in particular collects failed speculations at the beginning of a compile and then stays consistent during the compile. Why is that? - Because if there are new failed speculations added to the failed speculations during the compile - the compiler would speculate again on those in an inconsistent way. E.g. at the beginning of a compile a certain speculation has not failed yet and the compiler thinks it can do optimization xyz using a speculation  - later during the compilation process it consults the speculation log but gets a different answer. All those inconsistent speculations that already failed will anyway later fail code installation in jvmci (they will throw a bailout during `HotSpotCodeCacheProvider#installCode` https://github.com/openjdk/jdk/blob/master/src/jdk.internal.vm.ci/share/classes/jdk/vm/ci/hotspot/HotSpotSpeculationLog.java#L192 ). Thus, we should at least return a consistent result during a compile.
The problem for consistency here, that also makes troubles on the graal side, is that `maySpeculate` itself can collect failed speculations if there have not been any previously, i.e., `failedSpeculations == null`.
In order to make the speculation log consistent across an entire JVMCI compile this PR removes the collection of failed speculations in `maySpeculate`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322636](https://bugs.openjdk.org/browse/JDK-8322636): [JVMCI] HotSpotSpeculationLog can be inconsistent across a single compile (**Bug** - P4)

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - **Reviewer**) ⚠️ Review applies to [810e42ad](https://git.openjdk.org/jdk/pull/17183/files/810e42ad74761e700eb09162e48907c4a8722111)
 * [Tom Rodriguez](https://openjdk.org/census#never) (@tkrodriguez - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17183/head:pull/17183` \
`$ git checkout pull/17183`

Update a local copy of the PR: \
`$ git checkout pull/17183` \
`$ git pull https://git.openjdk.org/jdk.git pull/17183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17183`

View PR using the GUI difftool: \
`$ git pr show -t 17183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17183.diff">https://git.openjdk.org/jdk/pull/17183.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17183#issuecomment-1867570779)

### CODE REVIEW

**Comment by davleopo** [comment]
cc @dougxc  @tkrodriguez  can you have a look

**Review by dougxc — APPROVED** [review]
I think it's worth updating the javadoc for maySpeculate to clarify that it returns consistent results for any given speculation for the lifetime of a SpeculationLog object.

**Comment by davleopo** [comment]
> I think it's worth updating the javadoc for maySpeculate to clarify that it returns consistent results for any given speculation for the lifetime of a SpeculationLog object.

@dougxc  done - please check

**Comment by tkrodriguez** [comment]
More specifically it only validates against the speculations that failed before the last call to collectFailedSpeculations which must always be called explicitly.  And we should point out somewhere that installCode will call collectFailedSpeculations before installation and revalidate the current set of speculations, bailing out if any were violated during compilation.  This doesn't seem to be documented anywhere.

**Comment by davleopo** [comment]
@tkrodriguez  where do you want to put it? 

Id suggest to add some additional javadoc to maySpeculate so we end up with something like

```
    /**
     * @return {@code true} if the given speculation can be performed, i.e., it never failed so far, otherwise
     * return {@code false}. Note, that this method returns consistent results for any given speculation for the
     * entire lifetime of the enclosing SpeculationLog object. This means that speculations failed during a
     * compilation will not be updated. Validation of speculations only considers those failed since the last
     * call to {@link #collectFailedSpeculations()}. 
     * 
     * Users of {@link SpeculationLog} must explicitly call {@link #collectFailedSpeculations()} to collect
     * failed speculations. This should be done before starting a compile.
     * 
     * Code installation performs a revalidation of the current set of speculations. If this fails, i.e. since the
     * start of the compile new speculations failed, the compilation is aborted with a bailout. This is done in
     * {@link #getFlattenedSpeculations(boolean)}.
     */
```

**Comment by tkrodriguez** [comment]
So I looked more closely the HotSpot and substrate implementations and I'm not sure we can currently align the implementation and the javadoc.  In the HotSpot world, HotSpotSpeculationLog is a compiler local object that reads data from the real speculation data that's kept in the MDO.  This means that it has full control over when collectFailedSpeculations is called.  SubstrateSpeculationLog is the actual log so if two threads are operating on the same log then one of them could see the effects of a call to collectFailedSpeculations by the other thread.  Maybe in practice 2 threads never do this because it would mean they are compiling the same root method but it doesn't seem guaranteed.  installCode on substrate also doesn't perform the speculation log check that HotSpot does.  So maybe we punt on javadoc updates for now.

**Comment by davleopo** [comment]
I did not consider the substrate runtime compilation use case  - that may actually lead to the same error of inconsistency we have seen as here. Probably not relevant now but if it ever pops up we need to relax the invariant on the graal side then.

Regarding doc changes - what is our final call now ? (a) drop all new doc again or (b) keep (whatever) form of the new doc I added? - Its hotspot specific so not wrong.

**Review by tkrodriguez — APPROVED** [review]
I think for now lets just stick with your updates.  It does seem like the substrate runtime compilation case is potentially exposed to the original problem but we should address that separately.

**Comment by davleopo** [comment]
@tkrodriguez please sponsor

**Pull request closed without merging**
