### PR TITLE
8316563: test tools/jpackage/linux/LinuxResourceTest.java fails on CentOS Linux release 8.5.2111 and Fedora 27

### PR DESCRIPTION
**Pull request by yaqsun**
on some RHEL Linux 8.X and Fedora 27 machines , we run into errors in test tools/jpackage/linux/LinuxResourceTest.java.
It's the same problem as https://bugs.openjdk.org/browse/JDK-8314121. 
But after 8314121, tools/jpackage/linux/LinuxResourceTest.java still reappears. tools/jpackage/linux/LinuxResourceTest.java does not use file src/jdk.jpackage/linux/classes/jdk/jpackage/internal/resources/template.spec.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316563](https://bugs.openjdk.org/browse/JDK-8316563): test tools/jpackage/linux/LinuxResourceTest.java fails on CentOS Linux release 8.5.2111 and Fedora 27 (**Bug** - P4)

### Reviewers
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)
 * [Alexander Matveev](https://openjdk.org/census#almatvee) (@sashamatveev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15832/head:pull/15832` \
`$ git checkout pull/15832`

Update a local copy of the PR: \
`$ git checkout pull/15832` \
`$ git pull https://git.openjdk.org/jdk.git pull/15832/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15832`

View PR using the GUI difftool: \
`$ git pr show -t 15832`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15832.diff">https://git.openjdk.org/jdk/pull/15832.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15832#issuecomment-1751555545)

### CODE REVIEW

**Comment by yaqsun** [comment]
RFR

**Comment by jaikiran** [comment]
Hello @yaqsun, for this PR to trigger the official review process, the title of this PR should match the JBS title. Can you update the PR title to `8316563: test tools/jpackage/linux/LinuxResourceTest.java fails on CentOS Linux release 8.5.2111 and Fedora 27`

**Comment by jaikiran** [comment]
Hello @yaqsun, thank you for fixing the title of this PR. It appears that additionally you have to fix some issues in the proposed code (tab usages) before this PR can generate a review request. Please take a look at the jcheck failure listed in the GitHub actions job of this PR.

**Comment by alexeysemenyukoracle** [comment]
`%define _build_id_links none` must be added to a spec file in LinuxResourceTest.java file. not on `rpmbuild` command line

**Comment by yaqsun** [comment]
> `%define _build_id_links none` must be added to a spec file in LinuxResourceTest.java file. not on `rpmbuild` command line

`%define _build_id_links none` has been added to a spec file in LinuxResourceTest.java file. Please review.

**Review by alexeysemenyukoracle — APPROVED** [review]

**Comment by alexeysemenyukoracle** [comment]
Thank you for updating the patch!

**Review by sashamatveev — APPROVED** [review]

**Comment by theaoqi** [comment]
@yaqsun , I suggest you synchronize with the latest code and trigger testing before integration.

**Comment by yaqsun** [comment]
> @yaqsun , I suggest you synchronize with the latest code and trigger testing before integration.

I've synced to the latest code.

**Pull request closed without merging**
