### PR TITLE
8322744: VirtualThread.notifyJvmtiDisableSuspend should be static

### PR DESCRIPTION
**Pull request by sspitsyn**
The notification method `VirtualThread.notifyJvmtiDisableSuspend` should be static.
The method disables/enables suspend of the current virtual thread, a no-op if the current thread is a platform thread. It is confusing for this to be an instance method, it should be static to make it clearer that it doesn't change the target thread.
The notification method `VirtualThread.notifyJvmtiHideFrames` also has to be static as it does not use/need the virtual thread `this` argument.
One detail to underline is the intrinsic implementation needs to use the argument #0 instead of #1.

Testing:
- The mach5 tiers 1-6 show no regressions

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322744](https://bugs.openjdk.org/browse/JDK-8322744): VirtualThread.notifyJvmtiDisableSuspend should be static (**Bug** - P4)

### Reviewers
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17298/head:pull/17298` \
`$ git checkout pull/17298`

Update a local copy of the PR: \
`$ git checkout pull/17298` \
`$ git pull https://git.openjdk.org/jdk.git pull/17298/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17298`

View PR using the GUI difftool: \
`$ git pr show -t 17298`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17298.diff">https://git.openjdk.org/jdk/pull/17298.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17298#issuecomment-1880530651)

### CODE REVIEW

**Comment by sspitsyn** [comment]
PING! It would be nice to get this reviewed. :)

**Review by pchilano — APPROVED** [review]
Looks good to me. I'm confused about the description saying this method is a no-op if the current thread is a platform thread.

**Review by AlanBateman — APPROVED** [review]

**Comment by sspitsyn** [comment]
Patricio and Alan, thank you a lot for review!

**Pull request closed without merging**
