### PR TITLE
8325679: Optimize ArrayList subList sort

### PR DESCRIPTION
**Pull request by szegedi**
Somewhat surprisingly, `ArrayList$Sublist.sort()` is not specialized and will thus fall back to slower default method of `List.sort()` instead of sorting a range of the array in-place in its backing root `ArrayList`. 

This doesn't change observable behavior, so haven't added tests, and `tier1` tests still all pass except for `test/jdk/java/util/Locale/LocaleProvidersFormat.java` which also currently fails on master too on the machine I tested on.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325679](https://bugs.openjdk.org/browse/JDK-8325679): Optimize ArrayList subList sort (**Enhancement** - P3)

### Reviewers
 * @tsypanovs (no known openjdk.org user name / role) Review applies to [a5537664](https://git.openjdk.org/jdk/pull/17818/files/a5537664b0e659ddc798515f923f45d3c41dcb83)
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17818/head:pull/17818` \
`$ git checkout pull/17818`

Update a local copy of the PR: \
`$ git checkout pull/17818` \
`$ git pull https://git.openjdk.org/jdk.git pull/17818/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17818`

View PR using the GUI difftool: \
`$ git pr show -t 17818`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17818.diff">https://git.openjdk.org/jdk/pull/17818.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17818#issuecomment-1939748312)

### CODE REVIEW

**Comment by JimLaskey** [comment]
Been there since day one?

**Comment by stuart-marks** [comment]
@szegedi Oh interesting catch. Looks like a reasonable optimization. Is this covered by a test, or should a new test be added?

@JimLaskey The `List.sort` method was added in JDK 8, so not really day one. Prior to that one had to call `Collections.sort` which copied to a temp array, sorted, then copied back; this applied equally to full lists and sublists. Since JDK 8, `ArrayList.sort` on the full list did sorting in place but sorting a subList just inherited the default method (which uses the old copy-to-temp-and-sort technique). My guess is that nobody noticed this because sublists aren't used that much, and sorting of subarrays, while arguably necessary for completeness, probably aren't used all that much either.

**Comment by szegedi** [comment]
@stuart-marks you're right that sorting of sublists is rare. I did run into a need for it a few months ago in my day job though, that's how I stumbled upon this. Granted, it was a performance optimization and not a correctness necessity. See, I have a large list of data I read from an external location. Some elements – in at most one identifiable but arbitrarily large stride in the large list – need some extra processing. The algorithm for this processing can be written to be more efficient if it can presume those elements are sorted.

I could still sort the entire list (as the ordering doesn't matter to the final receiver), using a sort that just compares irrelevant elements as equal, so they'd remain as large "already sorted" strides, and only apply the real sort on only the relevant elements:
```
static int fullListCompare(Data d1, Data d2) {
  if (isRelevant(d1)) {
    if (isRelevant(d2)) {
      return sublistCompare(d1, d2);
    } else {
      return -1;
    }
  } else if (isRelevant(d2)) {
    return 1;
  }
  return 0;    
}
```
This'd also have the side effect of moving all the relevant entries to the beginning of the list, but while that's not a problem, it's not necessary either. For this reason, I prefer to scan the list for the stride, reify it as a sublist, and only run a sort with `sublistCompare` on it, and then also do the extra processing of the elements on the sublist too.

So yeah, it is rare this pops up, but it does happen :-)

I'm not sure if there's a test that already exercises sublist sorts. I did find what seems like a setup for a [TCK test for ArrayList](https://github.com/openjdk/jdk/blob/master/test/jdk/java/util/concurrent/tck/ArrayListTest.java) that seems like it is specifically creating a test suite for sublists too, but I haven't looked more closely into how is that supposed to work. I'm happy to write some tests specifically for ArrayList sublist sort if this TCK one doesn't exercise it.

**Review by tsypanovs — APPROVED** [review]

**Comment by pavelrappo** [comment]
> My guess is that nobody noticed this because sublists aren't used that much, and sorting of subarrays, while arguably necessary for completeness, probably aren't used all that much either.

FWIW, `CopyOnWriteArrayList.COWSubList` overrides `sort`.

**Comment by stuart-marks** [comment]
Just to clarify, my comments about "sorting sublists is rare" is a response to "has this been there since day one?" from @JimLaskey, and it's not an argument against adding this. Maybe it's a bit surprising that it hasn't been done, but maybe not, as the case is somewhat rare. (There are a lot of cases in the collections where various collection views inherit slow implementations from default methods or from the Abstract implementations, because nobody has really cared enough to provide optimized implementations, and it would add bulk to the code.)

CopyOnWriteArrayList needs to override subList.sort since it potentially modifies the array, and COWAL needs to make a copy before making any modifications.

Regarding testing: the tests in `test/jdk/java/util/concurrent/tck` are supposed to be the conformance tests for the java.util.concurrent package, so it'd be somewhat odd to have functional tests for non-juc classes added there. (I did find it surprising that there are ArrayList tests there, but a lot of work in the core collections was done in the context of JSR166, so maybe I shouldn't be too surprised.)

There appears to be some coverage of the List.sort() default method in `test/jdk/java/util/List/ListDefault.java'. It does seem to cover sublists. I guess the question is whether this test is focused on the _default implementation_ of List.sort(), or whether it's intended to cover all implementations -- whether the default or overridden -- of the default methods that were added in JDK 8. I think this area is worth a closer look. If the new ArrayList.subList().sort() override is covered already, we might be able to get away without adding a new test. Or possibly some adjustment could be made to this test if necessary.

**Comment by pavelrappo** [comment]
> CopyOnWriteArrayList needs to override subList.sort since it potentially modifies the array, and COWAL needs to make a copy before making any modifications.

I admit, I didn't look into that much; I just skimmed through some overrides of `List.sort`. That said, does it mean that before `List.sort`, `Collections.sort`, which had the same implementation that the default `List.sort` now has, would not be able to be properly sort `CopyOnWriteArrayList`?

(Sorry, if I digress.)

**Comment by stuart-marks** [comment]
(Discussion mainly of historical interest.)

@pavelrappo Correct, historically, `Collections.sort` would fail to sort `CopyOnWriteArrayList`. You have to go back to JDK 7 to see this. The sorting approach used by `Collections.sort` (still present in the default implementation of `List.sort`) gets an array using `toArray()`, sorts it, and then copies the sorted elements back using `ListIterator.set`. Since `CopyOnWriteArrayList` doesn't support modifications using `ListIterator`, it fails with `UnsupportedOperationException`. The overrides of `List.sort` have fixed this problem.

COWAL still has some problems with other things that use similar techniques, such as `Collections.shuffle`. That uses get/set to swap elements, which COWAL does support, but it copies the array on each set() operation.

**Comment by szegedi** [comment]
@stuart-marks > Just to clarify, my comments about "sorting sublists is rare" is a response to "has this been there since day one?" from @JimLaskey, and it's not an argument against adding this.

That's absolutely understood :-) I was just trying to add some color by describing the use case I stumbled upon. 

> There appears to be some coverage of the List.sort() default method in `test/jdk/java/util/List/ListDefault.java'. It does seem to cover sublists. I guess the question is whether this test is focused on the default implementation of List.sort(), or whether it's intended to cover all implementations -- whether the default or overridden -- of the default methods that were added in JDK 8. I think this area is worth a closer look. If the new ArrayList.subList().sort() override is covered already, we might be able to get away without adding a new test. Or possibly some adjustment could be made to this test if necessary.

I confirmed that the code in [ListDefaults.java:403](https://github.com/openjdk/jdk/blob/master/test/jdk/java/util/List/ListDefaults.java#L403) exercises `ArrayList$SubList.sort()`. In the meantime, I also added a more exhaustive stochastic test, although it might be an overkill. I'm inclined to remove it.

**Comment by szegedi** [comment]
Hey folks (@stuart-marks or @JimLaskey) it's been a while – can I get a review?

**Comment by szegedi** [comment]
Keep it open, please.

**Comment by szegedi** [comment]
Keep it open, please.

**Review by liach — COMMENTED** [review]
Can you bump the copyright year of `ArrayList.java`?

Since `ListDefaults` covers your change, can you add your bugid here
https://github.com/openjdk/jdk/blob/1472124489c841642996ae984e21c533ffec8091/test/jdk/java/util/List/ListDefaults.java#L53
and bump the copyright year as well?

**Comment by stuart-marks** [comment]
@szegedi

Hi Attila, sorry for the long delay on this. If you update the PR per @liach's comment on 2024-07-09, I can sponsor it. Thanks.

**Review by liach — APPROVED** [review]
Thanks for the updates!

**Pull request closed without merging**
