### PR TITLE
8296445: C++ syntax error in jdwpTransport.h

### PR DESCRIPTION
**Pull request by pandaapo**
Fix a syntax error in the code in jdwpTransport.h

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296445](https://bugs.openjdk.org/browse/JDK-8296445): C++ syntax error in jdwpTransport.h

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [bf70681a](https://git.openjdk.org/jdk/pull/11008/files/bf70681a007c7f1a7f990105876e732f56f0cfd1)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [bf70681a](https://git.openjdk.org/jdk/pull/11008/files/bf70681a007c7f1a7f990105876e732f56f0cfd1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11008/head:pull/11008` \
`$ git checkout pull/11008`

Update a local copy of the PR: \
`$ git checkout pull/11008` \
`$ git pull https://git.openjdk.org/jdk pull/11008/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11008`

View PR using the GUI difftool: \
`$ git pr show -t 11008`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11008.diff">https://git.openjdk.org/jdk/pull/11008.diff</a>

</details>

### CODE REVIEW

**Comment by DingliZhang** [comment]
Hi @pandaapo thanks for your patch! 
You need to change the name of this PR to `8296445: C++ syntax error in jdwpTransport.h` to match the issue in JBS.

**Comment by pandaapo** [comment]
> Hi @pandaapo thanks for your patch! You need to change the name of this PR to `8296445: C++ syntax error in jdwpTransport.h` to match the issue in JBS.

Thanks.

**Review by plummercj — APPROVED** [review]
Change looks good.

**Comment by alexmenkov** [comment]
Need to update copyright year in the header

**Review by lmesnik — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]

**Comment by pandaapo** [comment]
@lmesnik Thanks for your review. May I change `Copyright (c) 2003, 2017, Oracle and/or its affiliates.` to `Copyright (c) 2003, 2022, Oracle and/or its affiliates.` in the file header?

**Comment by lmesnik** [comment]
Sure, please update the copyright.

**Review by lmesnik — APPROVED** [review]

**Review by lmesnik — APPROVED** [review]

**Pull request closed without merging**
