### PR TITLE
8283606: Tests may fail with zh locale on MacOS

### PR DESCRIPTION
**Pull request by vikeychen**
From the test doc of openjdk https://openjdk.java.net/groups/build/doc/testing.html
> If your locale is non-US, some tests are likely to fail. To work around this you can set the locale to US. On Unix platforms simply setting LANG="en_US" in the environment before running tests should work. On Windows or MacOS, setting JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US" helps for most, but not all test cases.

However, on MacOS 12.1, running `make test-tier1 JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US"` command for tier-1 test, some tests still fail, including the following in tier-1.The tests expects output messages in English, but Chinese message are still produced.

test/hotspot/jtreg/runtime/classFileParserBug/TestEmptyBootstrapMethodsAttr.java
test/langtools/jdk/javadoc/tool/6964914/TestStdDoclet.java
test/langtools/jdk/javadoc/tool/6964914/TestUserDoclet.java
test/langtools/jdk/javadoc/tool/EnsureNewOldDoclet.java
test/langtools/jdk/javadoc/tool/testLocaleOption/TestLocaleOption.java
test/langtools/tools/javac/T8132562/ClassPathWithDoubleQuotesTest.java
test/langtools/tools/javac/options/smokeTests/OptionSmokeTest.java
test/langtools/tools/javac/platform/PlatformProviderTest.java
test/langtools/tools/jdeps/MultiReleaseJar.java

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 reviews required, with at least 1 reviewer)

### Issue
 * [JDK-8283606](https://bugs.openjdk.java.net/browse/JDK-8283606): Tests may fail with zh locale on MacOS

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7924/head:pull/7924` \
`$ git checkout pull/7924`

Update a local copy of the PR: \
`$ git checkout pull/7924` \
`$ git pull https://git.openjdk.java.net/jdk pull/7924/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7924`

View PR using the GUI difftool: \
`$ git pr show -t 7924`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7924.diff">https://git.openjdk.java.net/jdk/pull/7924.diff</a>

</details>

### CODE REVIEW

**Comment by vikeychen** [comment]
Can somebody create an issue for me. I've reported to java bug system, no response yet. Current issue is the similar one.

**Comment by dholmes-ora** [comment]
It is not clear to me why only the listed tests are affected by this e.g.

test/hotspot/jtreg/runtime/classFileParserBug/TestEmptyBootstrapMethodsAttr.java

why is every test that uses `ProcessTools.createJavaProcessBuilder` not affected? And should this be something that is handled inside `ProcessTools.createJavaProcessBuilder` rather than in individual tests?

Also is this really intended as a fix for JDK-8275727 because the PR has now been linked to it! This seems a related but differnet issue.

Thanks,
David

**Comment by vikeychen** [comment]
@dholmes-ora hello, some test case not use `shouldContain` method to check string inclusion，e.g.

test/hotspot/jtreg/runtime/classFileParserBug/TestBadPackageWithInterface.java

 some test use `shouldContain` but output string do contain the expected string and some none english, e.g.

test/hotspot/jtreg/runtime/classFileParserBug/ClassFileParserBug.java

This is do a related but different issue, Can you help me to create an issue for this PR, I've reported to java bug system but not received an issue id.

Thanks

**Comment by dholmes-ora** [comment]
I have filed:

https://bugs.openjdk.java.net/browse/JDK-8283606

please update the PR accordingly.

**Comment by vikeychen** [comment]
@dholmes-ora Thanks, I've updated the PR. 

Tell me if changing the test library is preferable, I will update this PR.
it will include `ProcessTools.createJavaProcessBuilder` , `ExecTask` , `JavadocTask` , `JavacTask`,and maybe modify two tests to use `JavacTask` if applicable.

**Comment by dholmes-ora** [comment]
I think fixing this in the test library is preferable but I'd like to hear from others about the general problem.

**Comment by vikeychen** [comment]
@RogerRiggs I haven't tested on other OS's, I will try to take some time to test it.

from the test doc of openjdk
> If your locale is non-US, some tests are likely to fail. To work around this you can set the locale to US. On Unix platforms simply setting LANG="en_US" in the environment before running tests should work. On Windows or MacOS, setting JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US" helps for most, but not all test cases.

Maybe in linux setting environment before test is enough. At first, I have set `LC_ALL` and `LANG` on MAC, which is not work.

**Comment by iklam** [comment]
> @iklam by adding `JTREG="VM_OPTIONS=-Duser.language=en -Duser.country=US`, tests will still fail. Without adding it, A bunch of tests will fail. most of them are langtool tests, more than 1000 failed test at the time of my test.

I've updated the bug report (https://bugs.openjdk.java.net/browse/JDK-8283606) description. Please change it as you see fit.

Also, please update the summary of this PR so it's clear what the problem is, and how you're fixing it.

**Comment by iklam** [comment]
Can you try if this works for you (without your patch)?

```
export JAVA_TOOL_OPTIONS='-Xlog:gc -Duser.language=en -Duser.country=US' 
make test-only \
    TEST=test/langtools/jdk/javadoc/tool/6964914/TestStdDoclet.java \
    JTREG_OPTIONS=-e:JAVA_TOOL_OPTIONS

make test-only \
    TEST=open/test/langtools/jdk/javadoc/tool/testLocaleOption/TestLocaleOption.java\
    JTREG_OPTIONS=-e:JAVA_TOOL_OPTIONS
```

The `-Xlog:gc` is just for validating that the options are passed to tools such as `javac` and `javadoc` without the need to add the `-J` prefix. You should see something like this:

```
Options: [-J--patch-module=jdk.javadoc=patch, -J-Duser.language=en, -J-Duser.country=GB, -J-Duser.variant=ALLCAPS, -sourcepath, src, -d, testHelloWorldDefault_ALLCAPS/api, p]
[STDOUT]:
[0.022s][info][gc] Using G1
[0.681s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 8M->3M(16M) 9.021ms
....
[STDERR]:
Picked up JAVA_TOOL_OPTIONS: -Xlog:gc -Duser.language=en -Duser.country=US
LOADING SOURCE FILES FOR PACKAGE p...
CONSTRUCTING JAVADOC INFORMATION...
```

If this works, we can avoid changing each test case individually.

**Comment by vikeychen** [comment]
I have updated the summary of this PR.




> export JAVA_TOOL_OPTIONS='-Xlog:gc -Duser.language=en -Duser.country=US' 
> make test-only \
>     TEST=test/langtools/jdk/javadoc/tool/6964914/TestStdDoclet.java \
>     JTREG_OPTIONS=-e:JAVA_TOOL_OPTIONS

This does work for this test and tests that fail before.
However, this will make some other tests fail, e.g.

test/hotspot/jtreg/compiler/jvmci/TestInvalidJVMCIOption.java

`JAVA_TOOL_OPTIONS` will produce a message in stderr, it seems there is no way to suppress it.

**Comment by vikeychen** [comment]
@RogerRiggs I have tested that on Ubuntu 18.04 with zh locale. the above failed tests can succeed without any setting(LC environment or JTREG arg).

The jtreg test runtime seems to set `LC_ALL=C` environment whatever the system `LC_ALL` is.

some related example.
In terminal typing `java`  on ubuntu, the output is obviously system language chinese.  then I set `export LC_ALL=C`, type `java` again, the output is english.
On mac, setting `export LC_ALL=C` will make chinese characters become `???`.

**Comment by dholmes-ora** [comment]
I do not think we should be trying to use JAVA_TOOL_OPTIONS to set "global" test arguments. If setting the locale via -javaoptions does not suffice due to the way tests spawn JVMs without passing on those arguments, then we should deal with the latter on a test-by-test basis IMO. I do not think there can be a single mechanism here that will always work.

**Comment by iklam** [comment]
> I do not think we should be trying to use JAVA_TOOL_OPTIONS to set "global" test arguments. If setting the locale via -javaoptions does not suffice due to the way tests spawn JVMs without passing on those arguments, then we should deal with the latter on a test-by-test basis IMO. I do not think there can be a single mechanism here that will always work.

There's an ideal fix, but I am not sure if we are willing to go there -- instead of hard coding all the expected messages in English, the tests should get the expected output from the localization resources bundles from javac, javadoc, etc.

Otherwise, the current fix is the best we can do. If a test expects an English output, then it should explicitly say so when spawning a new JVM.

The reason that setting LC_ALL, LANG, etc doesn't work on MacOS is here:

https://github.com/openjdk/jdk/blob/c2c0cb2a4372d78658326461562363de9a1a194f/src/java.base/macosx/native/libjava/java_props_macosx.c#L215-L223

The only case for this file to call  `getenv("LANG")` is when `CFLocaleCopyPreferredLanguages()` returns an empty array. I did some googling but I can't find a way where you can affect the results of  `CFLocaleCopyPreferredLanguages()` by twiddling with the settings in a terminal session. It doesn't work even if you use the per-app locale setting as described in here: https://osxdaily.com/2021/06/02/how-change-language-specific-apps-mac/

**Review by iklam — APPROVED** [review]

**Comment by dholmes-ora** [comment]
> If a test expects an English output, then it should explicitly say so when spawning a new JVM.

The problem there is knowing when that is the case. For test/hotspot/jtreg/runtime/classFileParserBug/TestEmptyBootstrapMethodsAttr.java the message "Main method not found in class" comes from the launcher and is a localized error string, but there is no way for the test author to know that without digging into the source to check. We have hundreds of tests that check exception messages and they are not affected by this problem as exception messages are not, it seems, localized. So there is a bit of an inconsistency in that regard.

> There's an ideal fix, but I am not sure if we are willing to go there -- instead of hard coding all the expected messages in 
> English, the tests should get the expected output from the localization resources bundles from javac, javadoc, etc.

How? There's no way to name the desired message so that you could ask for it. And you'd still need to know it was a message that was localized.

The current fix seems okay as a patch of the current set of issues, but really there should be some way to avoid being hit by this with future tests IMO.

**Comment by RogerRiggs** [comment]
In the longer term, I think its worth considering implementing LC_ALL as an override. I created an enhancement request for purposes of discussion.
[JDK-8283697](https://bugs.openjdk.java.net/browse/JDK-8283697) On macOS, the locale cannot be set using LC_ALL environment value

Jtreg does propagate LC_ALL to the subprocesses it spawns and it is documented.
So I'm not sure an immediate fix is necessary if the manual workaround (changing macOs preferences)
is suitable for a couple of weeks.

**Comment by vikeychen** [comment]
I have updated the fix-by-library version.  and changing test library is do good for future tests, even with more locale support  in jvm can make some tests fail I think.  this version influence one test in tier-1.

I think the previous commit is simpler and influence less.

Adding `LC_ALL` support seems promising. I think this is not a small change.

**Comment by iklam** [comment]
> In the longer term, I think its worth considering implementing LC_ALL as an override. I created an enhancement request for purposes of discussion. [JDK-8283697](https://bugs.openjdk.java.net/browse/JDK-8283697) On macOS, the locale cannot be set using LC_ALL environment value
> 
> Jtreg does propagate LC_ALL to the subprocesses it spawns and it is documented. So I'm not sure an immediate fix is necessary if the manual workaround (changing macOs preferences) is suitable for a couple of weeks.

Roger, do you plan to implement the LC_ALL fix shortly? If so, that may make this PR unnecessary.

**Comment by RogerRiggs** [comment]
I will start the process, but it may take a couple of weeks, I expect some discussion about whether to support only LC_ALL vs all of the other env vars, (LANG, LC_*). And it will need a CSR.

**Comment by vikeychen** [comment]
@iklam @dholmes-ora Can you please sponsor this PR or review the library version, since 
 https://bugs.openjdk.java.net/browse/JDK-8283697
> the Posix shell variables LANG, and LC_* on macOs do not provide the same information for region and variant that are provided by the Core Foundation locale settings.
And the timing of changes made via the Control Panel is different

**Comment by iklam** [comment]
I can sponsor this PR but I think we need two reviewers.

**Comment by vikeychen** [comment]
Thanks for that and let's wait for more reviewers.

**Review by RogerRiggs — APPROVED** [review]
Looks fine.

**Comment by iklam** [comment]
I tested the patch on latest JDK repo and passed tiers 1 and 2.
/sponsor

**Comment by vikeychen** [comment]
Thanks Ioi and Roger.

**Pull request closed without merging**
