### PR TITLE
8292314: Cleanup legacy address handling

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Cleanup legacy address check in libsplashscreen obsoleted by http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/75755e92430c

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292314](https://bugs.openjdk.org/browse/JDK-8292314): Cleanup legacy address handling

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to [e528093d](https://git.openjdk.org/jdk/pull/9866/files/e528093d970147597533a2dad021d5fb786bf6d2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9866/head:pull/9866` \
`$ git checkout pull/9866`

Update a local copy of the PR: \
`$ git checkout pull/9866` \
`$ git pull https://git.openjdk.org/jdk pull/9866/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9866`

View PR using the GUI difftool: \
`$ git pr show -t 9866`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9866.diff">https://git.openjdk.org/jdk/pull/9866.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]
It wasn't a mistake. It was deliberate. That function used to be looked up at runtime.
However it was obsoleted by http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/75755e92430c
So it is safe to remove it now.

**Comment by TheShermanTanker** [comment]
I see, will change the issue to reflect that before integrating

**Pull request closed without merging**
