### PR TITLE
8267110: Update java.util to use instanceof pattern variable

### PR DESCRIPTION
**Pull request by pconcannon**
Hi,

Could someone please review my code for updating the code in the `java.util` package to make use of the `instanceof` pattern variable?

Kind regards,
Patrick

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267110](https://bugs.openjdk.java.net/browse/JDK-8267110): Update java.util to use instanceof pattern variable

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to 0ed0bd993fe972ad58ed3c84de08dcc4df1c014c
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to 0ed0bd993fe972ad58ed3c84de08dcc4df1c014c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4088/head:pull/4088` \
`$ git checkout pull/4088`

Update a local copy of the PR: \
`$ git checkout pull/4088` \
`$ git pull https://git.openjdk.java.net/jdk pull/4088/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4088`

View PR using the GUI difftool: \
`$ git pr show -t 4088`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4088.diff">https://git.openjdk.java.net/jdk/pull/4088.diff</a>

</details>

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]
Changes look good.

**Comment by AlanBateman** [comment]
You may need to coordinate with @DougLea on the changes to j.u.concurrent.

**Comment by DougLea** [comment]
Because we still make jdk11-compatible test-release java.util.concurrent jars, we are not big fans of adding non-essential differences to openjdk version. But if there is some advantage to doing this, we'll cope.

**Review by naotoj — APPROVED** [review]
Classes in the i18n area look good.

**Pull request closed without merging**
