### PR TITLE
8263170: ComboBoxModel documentation refers to a nonexistent type

### PR DESCRIPTION
**Pull request by prsadhuk**
javadoc of ComboBoxModel incorrectly specifies "extends ListDataModel" but actually it extends ListModel and there is no such interface as ListDataModel. Rectified the anomaly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263170](https://bugs.openjdk.java.net/browse/JDK-8263170): ComboBoxModel documentation refers to a nonexistent type

### Reviewers
 * [Alexander Zvegintsev](https://openjdk.java.net/census#azvegint) (@azvegint - **Reviewer**) ⚠️ Review applies to 68b4fbe66af0c3754b21a5d204bb4aef1e4303c2
 * [Tejpal Rebari](https://openjdk.java.net/census#trebari) (@trebari - Committer) ⚠️ Review applies to 68b4fbe66af0c3754b21a5d204bb4aef1e4303c2
 * [Pankaj Bansal](https://openjdk.java.net/census#pbansal) (@pankaj-bansal - **Reviewer**) ⚠️ Review applies to 68b4fbe66af0c3754b21a5d204bb4aef1e4303c2
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**) ⚠️ Review applies to 68b4fbe66af0c3754b21a5d204bb4aef1e4303c2
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**) ⚠️ Review applies to 68b4fbe66af0c3754b21a5d204bb4aef1e4303c2

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2886/head:pull/2886`
`$ git checkout pull/2886`

### CODE REVIEW

**Review by azvegint — APPROVED** [review]

**Review by trebari — APPROVED** [review]

**Review by pankaj-bansal — APPROVED** [review]

**Review by aivanov-jdk — APPROVED** [review]

**Review by azuev-java — APPROVED** [review]

**Comment by mrserb** [comment]
I suggest always update the copyright.

**Comment by turbanoff** [comment]
There is one more occurrence of `ListDataModel` in JDK code - https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/javax/swing/ListModel.java#L34
Perhaps it's worth to fix it too.

**Comment by prsadhuk** [comment]
> 
> 
> There is one more occurrence of `ListDataModel` in JDK code - https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/javax/swing/ListModel.java#L34
> Perhaps it's worth to fix it too.

ok. will take a look.

**Pull request closed without merging**
