### PR TITLE
8259859: Missing metaspace NMT memory tag

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this trivial fix that added missing NMT memory tag for metaspace.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259859](https://bugs.openjdk.java.net/browse/JDK-8259859): Missing metaspace NMT memory tag

### Reviewers
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2107/head:pull/2107`
`$ git checkout pull/2107`

### CODE REVIEW

**Comment by zhengyu123** [comment]
Friendly ping!

**Review by iklam — APPROVED** [review]
LGTM and trivial.

**Comment by zhengyu123** [comment]
Thanks, Ioi

**Comment by tstuefe** [comment]
Too late, but looks good, thanks for fixing!

**Pull request closed without merging**
