### PR TITLE
8319850: PrintInlining should print which methods are late inlines

### PR DESCRIPTION
**Pull request by caojoshua**
I'm not 100% sure if this covers all case of late inlines.

Passes jtreg tier1 locally on my Linux machine with a fastdebug build. With sample Java programs and -XX:+PrintInlining, I can see

```
@ 15   java.lang.Float::valueOf (9 bytes)   late inline (boxing method)
```

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319850](https://bugs.openjdk.org/browse/JDK-8319850): PrintInlining should print which methods are late inlines (**Enhancement** - P5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16595/head:pull/16595` \
`$ git checkout pull/16595`

Update a local copy of the PR: \
`$ git checkout pull/16595` \
`$ git pull https://git.openjdk.org/jdk.git pull/16595/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16595`

View PR using the GUI difftool: \
`$ git pr show -t 16595`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16595.diff">https://git.openjdk.org/jdk/pull/16595.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16595#issuecomment-1805249816)

### CODE REVIEW

**Comment by rwestrel** [comment]
`PrintInlining` reports late inlines AFAIK. When running:
```
java -Xcomp -XX:+AlwaysIncrementalInline -XX:+PrintCompilation -XX:+PrintInlining -XX:-TieredCompilation -version
```
for instance, the output includes inlining messages so that does seem to work. There is (complicated) code to keep the `PrintInlining` output ordered when using late inlining. There's an open bug to clean it up: https://bugs.openjdk.org/browse/JDK-8039555 FWIW, I gave it a try at some point but I couldn't find a better solution.
Can you give more details on what you're trying to fix?

**Comment by caojoshua** [comment]
I can see why its confusing. I reworded the JBS title and added more to the summary. 

```
This confused me when first starting looking at compilation units. I would see a method reported as inlined, but in the early compilation phases, I still see the method call. I was not aware of late inlines. I think it would be a nice enhancement for PrintInlining to report which methods are late inlined.
```

Yes, `PrintInlining` reports late inlines, but I think it would be nice for it to explicitly state which inlines are late inlines.

> There's an open bug to clean it up: https://bugs.openjdk.org/browse/JDK-8039555 FWIW, I gave it a try at some point but I couldn't find a better solution.

I can echo this issue, the inlining code does feel a little messy. I hope this patch does not make it worse, I'd say it keeps the messiness the same.

**Comment by rwestrel** [comment]
> Yes, `PrintInlining` reports late inlines, but I think it would be nice for it to explicitly state which inlines are late inlines. I want to print `late inline`.

I get it now and that looks reasonable to me. What about method handle invokes and late inlining of virtual calls. For those 2, the call site is initially found to not be a candidate for inlining and only later the compiler finds that it can inline. Does your change cover those 2 cases?

**Comment by caojoshua** [comment]
> > Yes, `PrintInlining` reports late inlines, but I think it would be nice for it to explicitly state which inlines are late inlines. I want to print `late inline`.
> 
> I get it now and that looks reasonable to me. What about method handle invokes and late inlining of virtual calls. For those 2, the call site is initially found to not be a candidate for inlining and only later the compiler finds that it can inline. Does your change cover those 2 cases?

I reworked so that the patch can handle the cases you just mentioned. It does not explicitly mentions if a call is virtual.

**Comment by caojoshua** [comment]
Rebased because of merge conflict against mater...guess I should not do that. I will just merge next time.

**Comment by caojoshua** [comment]
@rwestrel could you take a look?

**Comment by caojoshua** [comment]
> When `InlineTree::ok_to_inline()` is called, some diagnostic message is recorded for the call site. Do I understand right that with this patch, if the call is inlined late, then that message is dropped and replaced by a new "late inline.." message? If that's the case, isn't it the case that sometimes the `InlineTree::ok_to_inline()` has some useful information that's lost when late inlining happens?

Yeah I think you're right. It should not matter for the string/methodhandle/vector/boxing late inlines. But we can lose information for generic late inlines, for example a hot method that could not get inlined earlier due to lack of budget. I'll look into it.

**Comment by caojoshua** [comment]
Don't plan on working on this atm. Will reopen if I get back to it.

**Pull request closed without merging**
