### PR TITLE
8298059: Linked stack watermarks don't support nesting

### PR DESCRIPTION
**Pull request by fisk**
The KeepStackGCProcessedMark facility used to ensure a thread (possibly remote) remains fully processed in its scope, has not yet had to support nesting. As it turns out, they can now nest after JDK-8294924. So this patch adds support for nesting. Tested ZGC specific tests tier 1-8, general testing 1-3 and manually tested the two tests that failed and got problem listed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298059](https://bugs.openjdk.org/browse/JDK-8298059): Linked stack watermarks don't support nesting

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [39a4eea0](https://git.openjdk.org/jdk/pull/11530/files/39a4eea0b16154207ff6a50937d5e3336c5d3538)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [39a4eea0](https://git.openjdk.org/jdk/pull/11530/files/39a4eea0b16154207ff6a50937d5e3336c5d3538)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11530/head:pull/11530` \
`$ git checkout pull/11530`

Update a local copy of the PR: \
`$ git checkout pull/11530` \
`$ git pull https://git.openjdk.org/jdk pull/11530/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11530`

View PR using the GUI difftool: \
`$ git pr show -t 11530`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11530.diff">https://git.openjdk.org/jdk/pull/11530.diff</a>

</details>

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Comment by pchilano** [comment]
Looks good, but why do we need the lock? Isn't each thread only accessing its own _linked_watermarks field?

**Review by sspitsyn — APPROVED** [review]
Looks okay to me.
Thanks,
Serguei

**Comment by plummercj** [comment]
@fisk Please make sure this gets pushed to 20. If you don't get it pushed before the fork, you'll need update the PR to target the jdk20 fork, or push to 21 and then backport to 20. If you do the later, please first change the fixVersion of the CR from 20 to 21.

**Comment by fisk** [comment]
Thanks for the reviews, @stefank, @pchilano and @sspitsyn!

**Comment by fisk** [comment]
> Looks good, but why do we need the lock? Isn't each thread only accessing its own _linked_watermarks field?

Yeah we don't currently need the lock if this is used in the currently expected way. But I feel like the boundaries of what is the current thread vs effectively current thread such as when handshaking/suspending another thread and running code on it as if it was current, tends to blur the boundaries a bit. And I suppose I figured better safe than sorry so I don't have to fix this code again.

**Comment by dholmes-ora** [comment]
> I feel like the boundaries of what is the current thread vs effectively current thread such as when handshaking/suspending another thread and running code on it as if it was current, tends to blur the boundaries a bit. 

There is only one notion of "current thread" and that is the thread that is executing. Any other threads in the code would be "target threads". What are you suggesting with "effectively current"?

**Comment by fisk** [comment]
> > I feel like the boundaries of what is the current thread vs effectively current thread such as when handshaking/suspending another thread and running code on it as if it was current, tends to blur the boundaries a bit. 
> 
> 
> 
> There is only one notion of "current thread" and that is the thread that is executing. Any other threads in the code would be "target threads". What are you suggesting with "effectively current"?

I meant what you referred to as the target thread.

**Comment by dholmes-ora** [comment]
> I meant what you referred to as the target thread.

Then I do not understand the argument about the locking. If the only data structure we access belongs to the current thread, and only the current thread accesses that data structure, then no locking is needed.

**Comment by fisk** [comment]
> > I meant what you referred to as the target thread.
> 
> 
> 
> Then I do not understand the argument about the locking. If the only data structure we access belongs to the current thread, and only the current thread accesses that data structure, then no locking is needed.

Essentially, what I'm saying is that indeed no locking is currently required as this is only executed on Thread::current(). But I preferred it to be thread safe to guard against potential future code where it isn't used from Thread::current(). If you prefer it, I can remove the locking and replace it with an assert that this is only ever executed from Thread::current(). That way at least such new code would blow up.

**Comment by pchilano** [comment]
> > > I meant what you referred to as the target thread.
> > 
> > 
> > Then I do not understand the argument about the locking. If the only data structure we access belongs to the current thread, and only the current thread accesses that data structure, then no locking is needed.
> 
> Essentially, what I'm saying is that indeed no locking is currently required as this is only executed on Thread::current(). But I preferred it to be thread safe to guard against potential future code where it isn't used from Thread::current(). If you prefer it, I can remove the locking and replace it with an assert that this is only ever executed from Thread::current(). That way at least such new code would blow up.
>
Adding the assert instead sounds good to me. If some future change requires it we can always add the lock at that point. But won't push so whatever you prefer.

**Comment by dholmes-ora** [comment]
Yes please add an assert. Until such code exists that accesses from a different thread you can't really know what the right locking strategy would be - e.g. lock rank, nesting, etc.

**Comment by dholmes-ora** [comment]
Though now I'm looking at the full file, it is hard to tell how this new code interacts with the existing code that already utilises the lock.

**Comment by robehn** [comment]
EscapeBarrier do `KeepStackGCProcessedMark ksgcpm(deoptee_thread())` while the deoptee/target thread is blocked.
So to me it seem like a concurrent handshake may also create a KeepStackGCProcessedMark.
Thus this lock should be needed ?

**Comment by fisk** [comment]
> EscapeBarrier do `KeepStackGCProcessedMark ksgcpm(deoptee_thread())` while the deoptee/target thread is blocked.
> 
> So to me it seem like a concurrent handshake may also create a KeepStackGCProcessedMark.
> 
> Thus this lock should be needed ?

The passed in thread is which thread Thread::current wants to keep processed. So the data structure manipulated is on Thread::current.

**Comment by fisk** [comment]
I pushed a new patch where I assert the stack watermark thread and Thread::current are the same, and then removing the unnecessary locking.

**Review by robehn — APPROVED** [review]
Looks good.

**Review by pchilano — APPROVED** [review]
Looks good!

**Comment by fisk** [comment]
Thanks for the reviews @robehn and @pchilano!

**Pull request closed without merging**
