### PR TITLE
8330266: RISC-V: Restore frm to RoundingMode::rne after JNI

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this patch?
It's exactly the same as https://github.com/openjdk/jdk/pull/18785 which is withdrawn, the reason could be that I deleted the branch `restore-frm-after-jni` after I `/integrate` the pr, but in fact the deletion happened before it's indeed integrated by github, so it caused the withdraw.
Sorry for the inconvenience.

Thanks

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330266](https://bugs.openjdk.org/browse/JDK-8330266): RISC-V: Restore frm to RoundingMode::rne after JNI (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18839/head:pull/18839` \
`$ git checkout pull/18839`

Update a local copy of the PR: \
`$ git checkout pull/18839` \
`$ git pull https://git.openjdk.org/jdk.git pull/18839/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18839`

View PR using the GUI difftool: \
`$ git pr show -t 18839`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18839.diff">https://git.openjdk.org/jdk/pull/18839.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18839#issuecomment-2063878941)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]

**Comment by Hamlin-Li** [comment]
Thanks @RealFYang for your quick review!

/integrate

**Review by robehn — APPROVED** [review]
Thanks!

But the flag RestoreMXCSROnJNICalls is actually "x86 specific".
We should add a new flag that alias this, such as "RestoreFPModeOnJNICalls". Or whatever is good generic name.

**Comment by Hamlin-Li** [comment]
In fact, `RestoreMXCSROnJNICalls` also used on aarch64.
I agree it's not a good name, I think it's better to have a uniform name across platforms, so maybe we should modify the name together in another pr after this pr?

**Comment by robehn** [comment]
> In fact, `RestoreMXCSROnJNICalls` also used on aarch64. I agree it's not a good name, I think it's better to have a uniform name across platforms, so maybe we should modify the name together in another pr after this pr?

Yes, I know. Andrew pointed that out in aarch64 PR.

Yes, we should add a new flag aliasing the old flag. (see argument.cpp)
Then start the processes of deprecating the old flag.

**Comment by Hamlin-Li** [comment]
OK, I created https://bugs.openjdk.org/browse/JDK-8330634 to track RestoreMXCSROnJNICalls renaming

**Comment by Hamlin-Li** [comment]
> OK, I created https://bugs.openjdk.org/browse/JDK-8330634 to track RestoreMXCSROnJNICalls renaming

Oh, I found https://bugs.openjdk.org/browse/JDK-8321535 is already created, and I think Andrew will work on it. Maybe I should close https://bugs.openjdk.org/browse/JDK-8330634 as duplicate.

**Pull request closed without merging**
