### PR TITLE
8285793: C2: optimization  of mask checks in counted loops fail in the presence of cast nodes

### PR DESCRIPTION
**Pull request by rwestrel**
This showed up when working with a panama micro benchmark. Optimization of:

if ((base + (offset << 2)) & 3) != 0) {
}

into:

if ((base & 3) != 0) {

fails if the subgraph contains cast nodes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285793](https://bugs.openjdk.java.net/browse/JDK-8285793): C2: optimization  of mask checks in counted loops fail in the presence of cast nodes

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8447/head:pull/8447` \
`$ git checkout pull/8447`

Update a local copy of the PR: \
`$ git checkout pull/8447` \
`$ git pull https://git.openjdk.java.net/jdk pull/8447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8447`

View PR using the GUI difftool: \
`$ git pr show -t 8447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8447.diff">https://git.openjdk.java.net/jdk/pull/8447.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — COMMENTED** [review]
Looks good. Let me test it.

**Review by vnkozlov — APPROVED** [review]
Tobias already submitted testing.

**Review by TobiHartmann — APPROVED** [review]
Looks good. All tests passed.

**Comment by rwestrel** [comment]
@TobiHartmann @vnkozlov thanks for the reviews and testing

**Pull request closed without merging**
