### PR TITLE
8263303: C2 compilation fails with assert(found_sfpt) failed: no node in loop that's not input to safepoint

### PR DESCRIPTION
**Pull request by rwestrel**
The loop strip mining verification code catches a node which is pinned
in the outer strip mined loop but not referenced from the safepoint
node.

The test case is an example of how this could happen. The array[i]
load is referenced from the safepoint initially through:

(j - 10) * array[i]

It is sunk out of the inner loop and pinned in the outer loop. A
following loop opts round causes j - 10 to constant fold to 0 and as a
consequence the array load is no longer referenced from the safepoint
but pinned in the outer strip mined loop.

I tried to find a way to preserve the invariant that all nodes in the
outer strip mined loop are referenced from the safepoint but found no
robust way for that. So the fix removes that part of the verification
code.

This requires loop cloning code to be adjusted for nodes pinned in the
outer strip mined loop but not referenced from the safepoint.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263303](https://bugs.openjdk.java.net/browse/JDK-8263303): C2 compilation fails with assert(found_sfpt) failed: no node in loop that's not input to safepoint

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4278/head:pull/4278` \
`$ git checkout pull/4278`

Update a local copy of the PR: \
`$ git checkout pull/4278` \
`$ git pull https://git.openjdk.java.net/jdk pull/4278/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4278`

View PR using the GUI difftool: \
`$ git pr show -t 4278`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4278.diff">https://git.openjdk.java.net/jdk/pull/4278.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
That's reasonable. Looks good to me!

**Comment by rwestrel** [comment]
@chhagedorn thanks for the review.

**Review by chhagedorn — APPROVED** [review]

**Comment by vnkozlov** [comment]
Yes, we can't assume that all node in outer loop are referenced by Safepoint node. SP nodes reference only live values in current BC. In the test case it is value 'v'. After constant fold `v' become 0 and that is what SF should see (MulNode::Value() optimizes multiplication by 0). array[i] load should be dead at this point since nothing should be referencing it (except GC barriers, may be).

And I don't get how array[i] is moved from inner loop - it depends on `i` - loop's index.

**Comment by rwestrel** [comment]
Thanks for looking at this @vnkozlov 

> Yes, we can't assume that all node in outer loop are referenced by Safepoint node. SP nodes reference only live values in current BC. In the test case it is value 'v'. After constant fold `v' become 0 and that is what SF should see (MulNode::Value() optimizes multiplication by 0). array[i] load should be dead at this point since nothing should be referencing it (except GC barriers, may be).

The test case has: return v + array[i-1] + f;
array[i-1] is after i is incremented so commons with array[i] in the loop body. That keeps the array[i] load alive.

> And I don't get how array[i] is moved from inner loop - it depends on `i` - loop's index.

It's sunk out of loop because it only has uses out of loop. One of the uses is still indirectly the safepoint at the time sinking happens so it's pinned in the outer loop.

**Review by vnkozlov — APPROVED** [review]
Let me run tests before you push.

**Comment by vnkozlov** [comment]
> Thanks for looking at this @vnkozlov
> 
> > Yes, we can't assume that all node in outer loop are referenced by Safepoint node. SP nodes reference only live values in current BC. In the test case it is value 'v'. After constant fold `v' become 0 and that is what SF should see (MulNode::Value() optimizes multiplication by 0). array[i] load should be dead at this point since nothing should be referencing it (except GC barriers, may be).
> 
> The test case has: return v + array[i-1] + f;
> array[i-1] is after i is incremented so commons with array[i] in the loop body. That keeps the array[i] load alive.

Got it. I assume it happens after constant folding `j - 10` to 0.

> 
> > And I don't get how array[i] is moved from inner loop - it depends on `i` - loop's index.
> 
> It's sunk out of loop because it only has uses out of loop. One of the uses is still indirectly the safepoint at the time sinking happens so it's pinned in the outer loop.

Okay.

**Comment by vnkozlov** [comment]
Testing results are good.

**Comment by rwestrel** [comment]
@vnkozlov thanks for the review

**Pull request closed without merging**
