### PR TITLE
8297295: Remove ThreadGroup.allowThreadSuspension

### PR DESCRIPTION
**Pull request by AlanBateman**
Another small step in the multi-release/multi-year effort to remove cruft from Thread/ThreadGroup.

java.lang.ThreadGroup.allowThreadSuspension(boolean) dates from JDK 1.1 and the Classic VM. The method controlled whether threads were suspended when the GC failed. It appears to have interacted with a callback mechanism that could potentially free memory, allowing the GC to retry. The method was never specified .

The method was deprecated and changed to do nothing in JDK 1.2. It was deprecated for removal in Java 14. 

A corpus analysis of 30M classes in 130k artifacts found 0 usages of this method.

It is time to finally remove this method. The compatibility impact should be negligible. Joe, Stuart and I discussed briefly and think early in JDK 21 is a good time to do this.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8297295](https://bugs.openjdk.org/browse/JDK-8297295): Remove ThreadGroup.allowThreadSuspension
 * [JDK-8297331](https://bugs.openjdk.org/browse/JDK-8297331): Remove ThreadGroup.allowThreadSuspension (**CSR**)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**) ⚠️ Review applies to [427025eb](https://git.openjdk.org/jdk/pull/11373/files/427025ebcfb69cbd4bc43f49495bb162599c5fa8)
 * [Stuart Marks](https://openjdk.org/census#smarks) (@stuart-marks - **Reviewer**) ⚠️ Review applies to [427025eb](https://git.openjdk.org/jdk/pull/11373/files/427025ebcfb69cbd4bc43f49495bb162599c5fa8)
 * [Chris Hegarty](https://openjdk.org/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to [427025eb](https://git.openjdk.org/jdk/pull/11373/files/427025ebcfb69cbd4bc43f49495bb162599c5fa8)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to [427025eb](https://git.openjdk.org/jdk/pull/11373/files/427025ebcfb69cbd4bc43f49495bb162599c5fa8)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11373/head:pull/11373` \
`$ git checkout pull/11373`

Update a local copy of the PR: \
`$ git checkout pull/11373` \
`$ git pull https://git.openjdk.org/jdk pull/11373/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11373`

View PR using the GUI difftool: \
`$ git pr show -t 11373`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11373.diff">https://git.openjdk.org/jdk/pull/11373.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
> Joe, Stuart and I discussed briefly and think early in JDK 21 is a good time to do this.

I guess, this would then mean this PR will be integrated into mainline after 8th December when the branch for JDK 20 will be forked https://openjdk.org/projects/jdk/20/#Schedule?

**Review by jaikiran — APPROVED** [review]
Looks fine to me.

**Comment by stuart-marks** [comment]
@jaikiran wrote:

> I guess, this would then mean this PR will be integrated into mainline after 8th December when the branch for JDK 20 will be forked

Yes, I'm sure this will go in soon after the JDK 20 fork.

**Review by stuart-marks — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Review by jddarcy — APPROVED** [review]
Good for JDK 21.

**Comment by jddarcy** [comment]
Still looks good.

**Pull request closed without merging**
