### PR TITLE
8253040 : Remove unused Matcher::regnum_to_fpu_offset()

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://bugs.openjdk.java.net/browse/JDK-8253040
Tested on: x86_64 - Linux - Tier1

Remove unused method `Matcher::regnum_to_fpu_offset()` from source base.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253040](https://bugs.openjdk.java.net/browse/JDK-8253040): Remove unused Matcher::regnum_to_fpu_offset()

### Reviewers
 * [Aditya Mandaleeka](https://openjdk.java.net/census#adityam) (@adityamandaleeka - Author)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/194/head:pull/194`
`$ git checkout pull/194`

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]
LGTM

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by JohnTortugo** [comment]
@iwanowww - Can you please merge this PR?

**Pull request closed without merging**
