### PR TITLE
8264941: Remove CodeCache::mark_for_evol_deoptimization() method

### PR DESCRIPTION
**Pull request by coleenp**
This change removes the mark_for_evol_deoptimization method and removes the flag that all dependencies are recorded.  Before the change to walk the entire nmethod looking for "old" (redefined) methods with metadata_do(), we used to find methods in the code cache to deoptimize based on evol_method dependencies.  If the dependencies weren't yet recorded, we had to deoptimize all of the methods.  A long time ago, we had a customer who was unhappy with the pause for this when they had late attach.  Now we don't have this problem.
The evol_method dependencies are still used by the compiler to check for old methods during compilation.  I didn't change this but it might be something someone who knows the compiler better can do differently and remove these dependencies too.
Tested with tier1-6.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264941](https://bugs.openjdk.java.net/browse/JDK-8264941): Remove CodeCache::mark_for_evol_deoptimization() method

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4509/head:pull/4509` \
`$ git checkout pull/4509`

Update a local copy of the PR: \
`$ git checkout pull/4509` \
`$ git pull https://git.openjdk.java.net/jdk pull/4509/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4509`

View PR using the GUI difftool: \
`$ git pr show -t 4509`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4509.diff">https://git.openjdk.java.net/jdk/pull/4509.diff</a>

</details>

### CODE REVIEW

**Comment by coleenp** [comment]
Hi @iwanowww can you have a look?

**Review by eastig — COMMENTED** [review]
LGTM

**Comment by coleenp** [comment]
Thanks @eastig .

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thank you both Vladimir.

**Review by sspitsyn — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]
Hi Coleen,
LGTM.
Thanks,
Serguei

**Comment by coleenp** [comment]
Thanks Serguei.  Thanks for the code reviews.
/integrate

**Pull request closed without merging**
