### PR TITLE
8332935: Crash:  assert(*lastPtr != 0) failed: Mismatched JNINativeInterface tables, check for new entries

### PR DESCRIPTION
**Pull request by dholmes-ora**
By using the `int*` type the assert could fail if the lower 32-bits of the function address were all zero. Trivial fix is to change to a type that is guaranteed the right size: `intptr_t*`

Testing was done manually - see the JBS issue.

Also run tier4 testing a sanity as it include `-Xcheck:jni`.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332935](https://bugs.openjdk.org/browse/JDK-8332935): Crash:  assert(*lastPtr != 0) failed: Mismatched JNINativeInterface tables, check for new entries (**Bug** - P2)

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to [4241674b](https://git.openjdk.org/jdk/pull/19491/files/4241674b684223d046947fe68d49dcb908c89179)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19491/head:pull/19491` \
`$ git checkout pull/19491`

Update a local copy of the PR: \
`$ git checkout pull/19491` \
`$ git pull https://git.openjdk.org/jdk.git pull/19491/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19491`

View PR using the GUI difftool: \
`$ git pr show -t 19491`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19491.diff">https://git.openjdk.org/jdk/pull/19491.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19491#issuecomment-2141012783)

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This is a trivial fix. You should consider updating the copyright year.

**Comment by dholmes-ora** [comment]
Thanks for the review @dcubed-ojdk ! Copyright year updated.

**Review by tstuefe — APPROVED** [review]
Okay.

**Comment by dholmes-ora** [comment]
Thanks for the review @tstuefe !

**Pull request closed without merging**
