### PR TITLE
8265125: IGV: cannot edit forms with NetBeans GUI builder

### PR DESCRIPTION
**Pull request by robcasloz**
This change moves all NetBeans-generated .form files to the same directory as their corresponding Java source files. This allows NetBeans to recognize the corresponding Java source files as Swing forms, and open them in "Design" mode:

design

The .form files are only processed by NetBeans, so this change does not affect how IGV is built and run.

Tested manually by reproducing the steps in the [JBS bug report](https://bugs.openjdk.java.net/browse/JDK-8265125) and by checking that IGV can be built and run following the steps in IGV's [README.md](https://github.com/openjdk/jdk/tree/master/src/utils/IdealGraphVisualizer#building-and-running) file.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265125](https://bugs.openjdk.java.net/browse/JDK-8265125): IGV: cannot edit forms with NetBeans GUI builder

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3461/head:pull/3461` \
`$ git checkout pull/3461`

Update a local copy of the PR: \
`$ git checkout pull/3461` \
`$ git pull https://git.openjdk.java.net/jdk pull/3461/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3461`

View PR using the GUI difftool: \
`$ git pr show -t 3461`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3461.diff">https://git.openjdk.java.net/jdk/pull/3461.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Trivial

**Comment by robcasloz** [comment]
> Trivial

Thanks for reviewing, Vladimir!

**Pull request closed without merging**
