### PR TITLE
8336339: (se) SelectionKey.interestOps(int) should not throw ClosedSelectorException

### PR DESCRIPTION
**Pull request by AlanBateman**
If a Selector is closed at around the same time that a registered key's interestOps (or variants) are used to change the interest ops then interestOps may (incorrectly) throw ClosedSelectorException (CSE) These methods are only specified to throw IAE or CancelledKeyException. Related is that closing a Selector ay around the same time that a channel is initially registered that can with NPE when attempting to remove the key for the channel's registration with the selector.

The issue with interestOps dates from JDK 11 when the Selector were mostly re-implemented. The issue with register racing with close may date back further.  The Selector implementations are updated to just queue the update so that CSE is not thrown. An option here would be to not queue or remove the update when racing with close but it's not worth it. For the NPE, the AbstractSelectableChannel.removeKey checks if the keys array has been initialized, which is consistent with other access.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8336339](https://bugs.openjdk.org/browse/JDK-8336339): (se) SelectionKey.interestOps(int) should not throw ClosedSelectorException (**Bug** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20269/head:pull/20269` \
`$ git checkout pull/20269`

Update a local copy of the PR: \
`$ git checkout pull/20269` \
`$ git pull https://git.openjdk.org/jdk.git pull/20269/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20269`

View PR using the GUI difftool: \
`$ git pr show -t 20269`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20269.diff">https://git.openjdk.org/jdk/pull/20269.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20269#issuecomment-2241186247)

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Based on the provided context, the changes look OK to me.

**Review by bplb — APPROVED** [review]
Looks all right to me.

**Comment by AlanBateman** [comment]
Thanks for the review.

**Pull request closed without merging**
