### PR TITLE
8334769: Shenandoah: Move CodeCache_lock close to its use in ShenandoahConcurrentNMethodIterator

### PR DESCRIPTION
**Pull request by zhengyu123**
ShenandoahConcurrentNMethodIterator requires CodeCache_lock at begin and end of iteration.

Currently, the CodeCache_lock is acquired by their callers, which is not very obvious and readable. Let's move the lock inside the methods.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334769](https://bugs.openjdk.org/browse/JDK-8334769): Shenandoah: Move CodeCache_lock close to its use in ShenandoahConcurrentNMethodIterator (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19859/head:pull/19859` \
`$ git checkout pull/19859`

Update a local copy of the PR: \
`$ git checkout pull/19859` \
`$ git pull https://git.openjdk.org/jdk.git pull/19859/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19859`

View PR using the GUI difftool: \
`$ git pr show -t 19859`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19859.diff">https://git.openjdk.org/jdk/pull/19859.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19859#issuecomment-2187031723)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Agree, it looks cleaner that way, and has a symmetry with how `ShenandoahCodeRootsIterator` does it.

**Comment by shipilev** [comment]
@kdnilsen @earthling-amzn might need to take a look.

**Review by earthling-amzn — APPROVED** [review]

**Comment by earthling-amzn** [comment]
Looks good to me.

**Comment by zhengyu123** [comment]
/integrate

Thanks, @shipilev @earthling-amzn and @kdnilsen

**Pull request closed without merging**
