### PR TITLE
8318222: RISC-V: C2 CmpU3

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you review the change to add intrinsic for CmpU3 and CmpUL3?
Thanks!

### functionality
pass jtreg test:
jdk/java/lang/Long/Unsigned.java, jdk/java/lang/Integer/Unsigned.java

#### Long
**before**:
Benchmark                      (size)  Mode  Cnt       Score       Error  Units
Longs.compareUnsignedDirect       500  avgt    5    1454.789 ±   129.557  ns/op
Longs.compareUnsignedIndirect     500  avgt    5    1410.146 ±   120.017  ns/op

**after**:
Benchmark                      (size)  Mode  Cnt       Score       Error  Units
Longs.compareUnsignedDirect       500  avgt    5    1286.129 ±     8.441  ns/op
Longs.compareUnsignedIndirect     500  avgt    5     993.490 ±     0.840  ns/op

#### Integer
**before**:
Benchmark                         (size)  Mode  Cnt       Score       Error  Units
Integers.compareUnsignedDirect       500  avgt    5    1611.753 ±     0.700  ns/op
Integers.compareUnsignedIndirect     500  avgt    5    1775.093 ±     1.520  ns/op

**after**:
Benchmark                         (size)  Mode  Cnt       Score       Error  Units
Integers.compareUnsignedDirect       500  avgt    5    1159.351 ±     0.601  ns/op
Integers.compareUnsignedIndirect     500  avgt    5     776.185 ±     0.924  ns/op

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8318222](https://bugs.openjdk.org/browse/JDK-8318222): RISC-V: C2 CmpU3 (**Sub-task** - P4)
 * [JDK-8318223](https://bugs.openjdk.org/browse/JDK-8318223): RISC-V: C2 CmpUL3 (**Sub-task** - P4)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16314/head:pull/16314` \
`$ git checkout pull/16314`

Update a local copy of the PR: \
`$ git checkout pull/16314` \
`$ git pull https://git.openjdk.org/jdk.git pull/16314/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16314`

View PR using the GUI difftool: \
`$ git pr show -t 16314`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16314.diff">https://git.openjdk.org/jdk/pull/16314.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16314#issuecomment-1775505701)

### CODE REVIEW

**Review by robehn — APPROVED** [review]
Thank you, looks good!

**Review by RealFYang — APPROVED** [review]
LGTM. May I ask on which platform was the JMH tested?
Also I think it's better to perform some regression tests like tier1-3.

**Comment by Hamlin-Li** [comment]
> LGTM. May I ask on which platform was the JMH tested? 

It's `StarFive VisionFive 2 v1.3B`

> Also I think it's safer to perform some regression tests like tier1-3.

Thanks for reminding, I've run the hotspot compiler tests, and related jdk tests found by `grep -nr test/jdk  -we Long.compareUnsigned -we Integer.compareUnsigned`

**Comment by Hamlin-Li** [comment]
/solves JDK-8318223
/integrate

Thanks @robehn @RealFYang for your revewing!

**Pull request closed without merging**
