### PR TITLE
8261075: Create stubRoutines.inline.hpp with SafeFetch implementation

### PR DESCRIPTION
**Pull request by AntonKozlov**
Hi, 

Please reivew a small non-functional change that extracts inline SafeFetch functions to a separate file. This is preliminary work for JEP-391 integration that will reduce the size of that patch.

CC @dcubed-ojdk 

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261075](https://bugs.openjdk.java.net/browse/JDK-8261075): Create stubRoutines.inline.hpp with SafeFetch implementation

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Stefan Karlsson](https://openjdk.java.net/census#stefank) (@stefank - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2542/head:pull/2542`
`$ git checkout pull/2542`

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by tstuefe — COMMENTED** [review]
I would rename the new header safefetch.hpp, just because these functions were never part of the StubRoutines namespace, and the naming is much clearer.

**Comment by AntonKozlov** [comment]
> I would rename the new header safefetch.hpp, just because these functions were never part of the StubRoutines namespace, and the naming is much clearer.

Good idea. It should be safefetch.inline.hpp, right?

**Comment by tstuefe** [comment]
> > I would rename the new header safefetch.hpp, just because these functions were never part of the StubRoutines namespace, and the naming is much clearer.
> 
> Good idea. It should be safefetch.inline.hpp, right?

I don't think so? To my understanding, xxx.inline.hpp is a companion file to an xxx.hpp which you create if you want to remove some of the rarely used functions from a high traffic header. Here, we just have some independent global utility functions.

**Comment by AntonKozlov** [comment]
> To my understanding, xxx.inline.hpp is a companion file to an xxx.hpp which you create if you want to remove some of the rarely used functions from a high traffic header.

Oh, you're right. I had an impression that there are standalone inline.hpp files, and I could not find the opposite in the Hotspot Style Guide. However, now I see inline.hpp are just the way you've described. Thanks!

**Comment by stefank** [comment]
If you put non-trivial code in the header, then it should go into an .inline.hpp file (or .cpp file). From the style-guide:
```
Do not put non-trivial function implementations in .hpp files. If the implementation depends on other .hpp files, put it in a .cpp or a .inline.hpp file.
```
It doesn't matter if there exists a .hpp file or not. However, what's non-trivial becomes a judgment call. I tend to use rule that if it uses code from another header, then it's non-trivial, and should most likely be moved out of the .hpp file.

**Comment by AntonKozlov** [comment]
> It doesn't matter if there exists a .hpp file or not. However, what's non-trivial becomes a judgment call. I tend to use rule that if it uses code from another header, then it's non-trivial, and should most likely be moved out of the .hpp file.

I suppose this file to be on the edge between trivial and not. Later, it will have a W^X transition and will include thread.hpp, I don't want to rename it again. @stefank, what do you think, should it be safefetch.inline.hpp? Or are you fine with safefetch.hpp?

**Comment by stefank** [comment]
I'm fine with leaving it as safefetch.hpp.

**Review by stefank — APPROVED** [review]

**Review by tstuefe — APPROVED** [review]
LGTM

**Review by dcubed-ojdk — APPROVED** [review]
Still thumbs up.

**Comment by AntonKozlov** [comment]
I've messed up with this :( I'm trying to fix @stefank 's note https://github.com/openjdk/jdk/pull/2200#discussion_r572707505. I need to rename a file.hpp included in the safepoint.hpp to file.inline.hpp. This will require renaming safepoint.hpp to safepoint.inline.hpp, polluting the PR #2200 again and defeating the purpose of having this patch extracted. I think the better alternative will be a follow-up patch just renaming safepoint.hpp to safepoint.inline.hpp. I'm going to do the follow-up. Or is there a better alternative? Sorry and thanks.

**Comment by stefank** [comment]
Just so that I understand. Did you really mean safepoint.hpp and not safefetch.hpp? I assume this all has to do with the fact that safefetch.hpp is going to include threadWXSetter.hpp, which you are going to change to threadWXSsetter.inline.hpp, because it includes thread.inline.hpp. If that's the case then I think the easy fix is to just rename safefetch.hpp to safefetch.inline.hpp.

I don't think that will be problematic, or defeat the purpose of this patch. The previous change from stubRoutines.hpp to stubRoutines.inline.hpp has already been successfully been removed from your #2200 patch. If you create a new PR with a safefetch.hpp to safefetch.inline.hpp rename, I can review it as a trivial change and you will be able to push it immediately.

Or did I misunderstand anything? Maybe you could point me to the problematic files?

**Comment by AntonKozlov** [comment]
> Just so that I understand. Did you really mean safepoint.hpp and not safefetch.hpp? 

Definitely safefetch.hpp. Sorry, it seems I was thinking also about another problem at that moment :) 

> I assume this all has to do with the fact that safefetch.hpp is going to include threadWXSetter.hpp, which you are going to change to threadWXSsetter.inline.hpp, because it includes thread.inline.hpp. If that's the case then I think the easy fix is to just rename safefetch.hpp to safefetch.inline.hpp.

This is correct. My main concern was the noise I'm creating in the git repository, but I also think this is the best way in this situation. Thanks for confirmation! The bug is JDK-8263068 and PR is #2844.

**Pull request closed without merging**
