### PR TITLE
8328066: WhiteBoxResizeTest failure on linux-x86: Could not reserve enough space for 2097152KB object heap

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this test-only change which proposes to address https://bugs.openjdk.org/browse/JDK-8328066?

The test launches a JVM with 2G heap (`-Xmx2G`) and as noted in that issue, the failure was observed on linux-86 instance on a GitHub jobs run. 

The commit in this PR proposes to add relevant `@requires` so that the test is only run on 64 bit VM and expects the `os.maxMemory` to be > 2G.

The change has been tested on a linux-x86 run in GitHub actions job, plus even on local and CI 64 bit VM environments. No failures have been noticed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328066](https://bugs.openjdk.org/browse/JDK-8328066): WhiteBoxResizeTest failure on linux-x86: Could not reserve enough space for 2097152KB object heap (**Bug** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to [0a66d740](https://git.openjdk.org/jdk/pull/18290/files/0a66d740c768826c1ca58a440de35641a977404d)
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Mark Sheppard](https://openjdk.org/census#msheppar) (@msheppar - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18290/head:pull/18290` \
`$ git checkout pull/18290`

Update a local copy of the PR: \
`$ git checkout pull/18290` \
`$ git pull https://git.openjdk.org/jdk.git pull/18290/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18290`

View PR using the GUI difftool: \
`$ git pr show -t 18290`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18290.diff">https://git.openjdk.org/jdk/pull/18290.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18290#issuecomment-1996369990)

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Daniel,



> LGTM.
> 
> I see that some other tests have things like:
> 
> ```
> * @requires vm.bits == "64" & os.maxMemory > 4G
> ```
> 
> Not sure what is the preferred form in such cases: two `@requires` or a single one?

As per jtreg doc, semantically they would be the same:

>
> The @requires tag may be used multiple times in a given test. If it is used more than once, the expressions in the individual instances will be enclosed in parentheses and combined with '&'.

However, your suggestion I think is a good one, since it makes it quicker to notice the requirements instead of having it spread across on multiple lines. I'll update the PR to implement your suggestion.

**Comment by msheppar** [comment]
I think the os.maxMemory is an artificial constraint.
a requirement to run on 64 bit machine should be sufficient
@requires vm.bits == "64"

as the issue relates to the max user virtual address space available on 32 bit architecture

**Review by theRealAph — APPROVED** [review]

**Comment by msheppar** [comment]
maybe ask the question: why does the test need 2GB ?  Would 1Gb suffice and that would be within the allocation limits for 32 bit architectures virtual address space.

**Comment by jaikiran** [comment]
Hello Mark,

> maybe ask the question: why does the test need 2GB ? Would 1Gb suffice and that would be within the allocation limits for 32 bit architectures virtual address space.

The reason why 2GB is needed in this test is explained in https://bugs.openjdk.org/browse/JDK-8285386.

I see that Andrew (and previously Daniel) have approved this change and the updated version checks only for `vm.bits == 64` as suggested by you. If you think the current form of the PR looks good, then I'll go ahead and integrate this - since I don't plan to investigate an ideal heap size for running this on 32 bit VMs.

**Review by msheppar — APPROVED** [review]

**Comment by msheppar** [comment]
> The reason why 2GB is needed in this test is explained in https://bugs.openjdk.org/browse/JDK-8285386.

ok thanks ... i'll re-read

**Comment by jaikiran** [comment]
Thank you Mark, Daniel and Andrew for the reviews. I'll go ahead and integrate this now.

**Pull request closed without merging**
