### PR TITLE
8311023: assert(false) failed: EA: missing memory path

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Handling missing cases for VectorizedHashCode while collecting memory nodes for propagating new type information through the graph.

We associate new instance types with CheckCastPP nodes succeeding allocation IR, refresh connectivity of MemoryMerge slices at alias indices corresponding to new instance type and update the memory edges of user memory nodes in the ideal graph to ease out scalar replacements.

Please review and share feedback.

Best Regards,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311023](https://bugs.openjdk.org/browse/JDK-8311023): assert(false) failed: EA: missing memory path (**Bug** - P3)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [75e1642f](https://git.openjdk.org/jdk/pull/14764/files/75e1642ff9d3d4ad11b2d1cb71a687d6f1a34f69)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14764/head:pull/14764` \
`$ git checkout pull/14764`

Update a local copy of the PR: \
`$ git checkout pull/14764` \
`$ git pull https://git.openjdk.org/jdk.git pull/14764/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14764`

View PR using the GUI difftool: \
`$ git pr show -t 14764`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14764.diff">https://git.openjdk.org/jdk/pull/14764.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14764#issuecomment-1619194853)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. Please change the test name to something more descriptive.

**Comment by jatin-bhateja** [comment]
Thanks @chhagedorn , @TobiHartmann

**Pull request closed without merging**
