### PR TITLE
8340279: Open source several AWT Dialog tests - Batch 2

### PR DESCRIPTION
**Pull request by TejeshR13**
Open source these AWT Dialog tests:

java/awt/Dialog/PrintToFileTest/PrintToFileRevoked.java
java/awt/Dialog/PrintToFileTest/PrintToFileGranted.java
java/awt/Dialog/TopmostModalDialogTest.java
java/awt/Dialog/FileDialogFilterTest.java
java/awt/Dialog/DialogSystemMenu/DialogSystemMenu.java

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warnings
&nbsp;⚠️ Patch contains a binary file (test/jdk/java/awt/Dialog/DialogSystemMenu/icon24x24.gif)
&nbsp;⚠️ Patch contains a binary file (test/jdk/java/awt/Dialog/DialogSystemMenu/iconone.gif)
&nbsp;⚠️ Patch contains a binary file (test/jdk/java/awt/Dialog/DialogSystemMenu/icontwo.gif)

### Issue
 * [JDK-8340279](https://bugs.openjdk.org/browse/JDK-8340279): Open source several AWT Dialog tests - Batch 2 (**Bug** - P4) ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) Review applies to [99882abc](https://git.openjdk.org/jdk/pull/21466/files/99882abce1b75f877c32ec05c1e0fa6dbd0e086d)
 * [Abhishek Kumar](https://openjdk.org/census#abhiscxk) (@kumarabhi006 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21466/head:pull/21466` \
`$ git checkout pull/21466`

Update a local copy of the PR: \
`$ git checkout pull/21466` \
`$ git pull https://git.openjdk.org/jdk.git pull/21466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21466`

View PR using the GUI difftool: \
`$ git pr show -t 21466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21466.diff">https://git.openjdk.org/jdk/pull/21466.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21466#issuecomment-2406725183)

### CODE REVIEW

**Comment by DamonGuy** [comment]
@TejeshR13 Seems like you have a merge-conflict that you should resolve since this involves the Problem list.

**Comment by TejeshR13** [comment]
> @TejeshR13 Seems like you have a merge-conflict that you should resolve since this involves the Problem list.

Yeah, have resolved it now.

**Review by prrace — APPROVED** [review]

**Review by kumarabhi006 — APPROVED** [review]

**Pull request closed without merging**
