### PR TITLE
8331734: Atomic MemorySegment VarHandle operations fails for element layouts

### PR DESCRIPTION
**Pull request by mcimadamore**
This PR fixes an issue that has crept into the FFM API implementation.

From very early stages, the FFM API used to disable the alignment check on nested layout elements, in favor of an alignment check against the memory segment base address. The rationale was that the JIT had issue with eliminating redundant alignment checks, and accessing nested elements could never result in alignment issues, since the alignment of the container is provably bigger than that of the contained element. This means that, when creating a var handle for a nested layout element, we set the nested layout alignment to 1 (unaligned), derive its var handle, and then decorate the var handle with an alignment check for the container.

At some point in 22, we tweaked the API to throw `UnsupportedOperationException` when using an access mode incompatible with the alignment constraint of the accessed layout. That is, a volatile read on an `int` is only possible if the access occurs at an address that is at least 4-byte aligned. Otherwise an `UOE` is thrown.

Unfortunately this change broke the aforementioned optimization: creating a var handle for an unaligned layout works, but the resulting layout will *not* support any of the atomic access modes.

Since this optimization is not really required anymore (proper C2 support to hoist/eliminate alignment checks has been added since then), it is better to disable this implementation quirk, and leave optimizations to C2.

(If we really really wanted to optimize things a bit, we could remove the container alignment check in the case the accessed value is the first layout element nested in the container, but this PR doesn't go that far).

I've run relevant benchmarks before/after and found no differences. In part this is because `arrayElementVarHandle` is unaffected. But, even after tweaking the `LoopOverNonConstant` benchmark to add explicit tests for the code path affected, no significant difference was found, sign that C2 is indeed able to spot (and remove) the redundant alignment check. Note: if we know that `aligned_to_N(base)` holds, then it's easy to prove that `aligned_to_M(base + offset + index * scale)` holds, when `N >= M` and with `offset` and `scale` known (the latter a power of two).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331734](https://bugs.openjdk.org/browse/JDK-8331734): Atomic MemorySegment VarHandle operations fails for element layouts (**Bug** - P2)

### Reviewers
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - **Reviewer**) ⚠️ Review applies to [aa5ed595](https://git.openjdk.org/jdk/pull/19124/files/aa5ed59518012e292d04ee3f80a73272f1f0ef15)
 * [Paul Sandoz](https://openjdk.org/census#psandoz) (@PaulSandoz - **Reviewer**) ⚠️ Review applies to [aa5ed595](https://git.openjdk.org/jdk/pull/19124/files/aa5ed59518012e292d04ee3f80a73272f1f0ef15)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19124/head:pull/19124` \
`$ git checkout pull/19124`

Update a local copy of the PR: \
`$ git checkout pull/19124` \
`$ git pull https://git.openjdk.org/jdk.git pull/19124/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19124`

View PR using the GUI difftool: \
`$ git pr show -t 19124`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19124.diff">https://git.openjdk.org/jdk/pull/19124.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19124#issuecomment-2098778844)

### CODE REVIEW

**Review by minborg — APPROVED** [review]
LGTM. As mentioned in the PR notes, additional optimizations could be made and this could be the objective of a future PR.

**Review by PaulSandoz — APPROVED** [review]

**Comment by mcimadamore** [comment]
> * `x_handle` is really meant to provide access to a memory segment modelling (at least) one struct with layout `POINT_LAYOUT`. As such, the initial segment/offset combo should (a) be adequately aligned (according to `POINT_LAYOUT.byteAlignment()`) and have sufficient size (according to `POINT_LAYOUT.byteSize()`)

An example of this approach is attempted here:
https://github.com/openjdk/jdk/compare/master...mcimadamore:jdk:bad_align_segment_var_handle+size_checks?expand=1

Again, no significant performance regression is observed - the root layout checks dominate the value layout checks, and it seems like C2 is able to spot that.

**Comment by mcimadamore** [comment]
I've decided to integrate this for now, as the fix in this PR restores correctness of the implementation.
I will investigate follow up improvements and enhancements separately:
https://bugs.openjdk.org/browse/JDK-8331865

**Pull request closed without merging**
