### PR TITLE
8331015: Obsolete -XX:+UseNotificationThread

### PR DESCRIPTION
**Pull request by alexmenkov**
Obsolete UseNotificationThread flag which was deprecated in JDK 23.

Testing: tier1..tier5

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331015](https://bugs.openjdk.org/browse/JDK-8331015): Obsolete -XX:+UseNotificationThread (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20381/head:pull/20381` \
`$ git checkout pull/20381`

Update a local copy of the PR: \
`$ git checkout pull/20381` \
`$ git pull https://git.openjdk.org/jdk.git pull/20381/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20381`

View PR using the GUI difftool: \
`$ git pr show -t 20381`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20381.diff">https://git.openjdk.org/jdk/pull/20381.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20381#issuecomment-2257319855)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good!

Thanks

**Review by kevinjwalls — APPROVED** [review]
Looks good

**Review by sspitsyn — APPROVED** [review]

**Review by sspitsyn — COMMENTED** [review]
Looks good.

**Review by coleenp — APPROVED** [review]
Thank you for doing this.

**Pull request closed without merging**
