### PR TITLE
8240903: Add test to check that jmod hashes are reproducible

### PR DESCRIPTION
**Pull request by dongbohe**
This creates a regression test for [JDK-8240734](https://bugs.openjdk.java.net/browse/JDK-8240734). This was once blocked 
by a time stamp issue which has been resolved by: [JDK-8276766 ](https://bugs.openjdk.java.net/browse/JDK-8276766)

We found the issue can be produced stably with at least 64 modules.
Note that we need to add the --date jmod option to avoid the timestamp issue.

Testing:
Added test case fails without fix for JDK-8240734, and passes otherwise.
Tested with tier2 on linux x86.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8240903](https://bugs.openjdk.java.net/browse/JDK-8240903): Add test to check that jmod hashes are reproducible

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7948/head:pull/7948` \
`$ git checkout pull/7948`

Update a local copy of the PR: \
`$ git checkout pull/7948` \
`$ git pull https://git.openjdk.java.net/jdk pull/7948/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7948`

View PR using the GUI difftool: \
`$ git pr show -t 7948`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7948.diff">https://git.openjdk.java.net/jdk/pull/7948.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
The existing tests for the jmod tool are in test/jdk/tools/jmod. HashesTest.java might provide inspiration to avoid introducing a shell test.

**Comment by dongbohe** [comment]
> The existing tests for the jmod tool are in test/jdk/tools/jmod. HashesTest.java might provide inspiration to avoid introducing a shell test.

Hi, Alan

I have rewritten this test in Java in the latest commit.

**Comment by dongbohe** [comment]
@AlanBateman Could you please take another look?

**Comment by AlanBateman** [comment]
I think this looks okay. Can you say how long the test runs for you? It creates 130 JMOD files and I'm just wondering if the default timeout is enough when running with debug builds.

**Comment by dongbohe** [comment]
> I think this looks okay. Can you say how long the test runs for you? It creates 130 JMOD files and I'm just wondering if the default timeout is enough when running with debug builds.

The following is the test result on linux x86 with 128 cores, it looks ok.
```java
time make CONF=release run-test TEST=test/jdk/tools/jmod/hashes/HashesOrderTest.java
Finished building target 'run-test' in configuration 'linux-x86_64-server-release'

real	0m24.235s
user	0m52.196s
sys	0m7.170s

time make CONF=slowdebug run-test TEST=test/jdk/tools/jmod/hashes/HashesOrderTest.java
real	2m2.877s
user	5m58.887s
sys	0m10.474s
```

**Comment by AlanBateman** [comment]
Thanks for the timings. I mostly asked because we've had issues with I/O heavy tests on older macOS tests in our CI. Several tests have had to be dialled down or configured to run with very large timeouts. We'll have to see how this one fares.

**Review by AlanBateman — APPROVED** [review]

**Comment by dongbohe** [comment]
Thank you for your review, Alan.
/integrate

**Pull request closed without merging**
