### PR TITLE
8334779: Test compiler/c1/CanonicalizeArrayLength.java is timing out

### PR DESCRIPTION
**Pull request by vnkozlov**
The timeout is cause by running the test with `-Xcomp -XX:+VerifyOops -XX:+PatchALot`.
The test continuously deoptimize and recompile `java.lang.Throwable::<init>` method.
`-XX:+VerifyOops ` adds a lot of external addresses because it use ExternallAddress for error messages.
These messages are unique for each call to `verify_oop()` because they are constructed locally.
I reduced number of loop iteration by 10 to get reasonable execution time (2 mins instead of 20 mins) and got next data:
```
Without VerifyOops:
  External addresses table: 38 entries

With VerifyOops:
  External addresses table: 125922 entries
```
Looks like most of the time VM is spending to grow/reallocate big growable array added by [JDK-8333819](https://bugs.openjdk.org/browse/JDK-8333819).
Before that change these addresses were recorded locally in nmethod's relocation info. When nmethod was deoptimized, its relocation info was discarded together with nmethod.

Only on x86 we declared message address as ExternalAddress. Aarch64 uses movptr() to store address as simple pointer. ARM uses own InlineAddress with RelocInfo::none type of relocation. I verified other platforms: none is using ExternalAddress.

I suggest to use AddressLiteral with RelocInfo::none for x86. With that the global table is small even with -XX:+VerifyOops:
```
  External addresses table: 42 entries
```

Tested tier1,  run test with corresponding flags to verify that time is similar to before [JDK-8333819](https://bugs.openjdk.org/browse/JDK-8333819)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334779](https://bugs.openjdk.org/browse/JDK-8334779): Test compiler/c1/CanonicalizeArrayLength.java is timing out (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19871/head:pull/19871` \
`$ git checkout pull/19871`

Update a local copy of the PR: \
`$ git checkout pull/19871` \
`$ git pull https://git.openjdk.org/jdk.git pull/19871/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19871`

View PR using the GUI difftool: \
`$ git pr show -t 19871`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19871.diff">https://git.openjdk.org/jdk/pull/19871.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19871#issuecomment-2187641955)

### CODE REVIEW

**Comment by dean-long** [comment]
Where are these strings actually located?  Do they need to be relocated if the CodeBuffer expands?

Can we assert that uses of ExternalAddress do not point inside the CodeBuffer/CodeBlob?  You might catch additional cases.

**Comment by vnkozlov** [comment]
> Where are these strings actually located? Do they need to be relocated if the CodeBuffer expands?

Thank you, @dean-long, for looking.
They are not located in CodeCache space, they are external. It is long path from `code_string(ss.as_string())` call but at the end a string is duplicated in C heap:
[codeBuffer.cpp#L1088](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/asm/codeBuffer.cpp#L1088)

But structure which keep track of these strings is part of CodeBlob `CodeBlob:: _dbg_strings` which is not copied by `CodeBuffer::expand()`. `expand()` has similar code to `CodeBuffer::copy_code_to()` except coping `_dbg_strings` and `_asm_remarks`.  So we do have the issue with expand - we may not free space allocated by strings and comments when expanded nmethod is deoptimized.

**Comment by vnkozlov** [comment]
> Can we assert that uses of ExternalAddress do not point inside the CodeBuffer/CodeBlob? You might catch additional cases.

To clarify, these strings are externals and using ExternalAddress for them is correct. But we don't need to use relocation for them (no need to patch) because they don't move and `pushptr()` in `_verify_oops` loads whole 64-bit address into register - no relative addressing. That is why I use `relocInfo::none` for them.

**Comment by vnkozlov** [comment]
I did experiment to see if ExternalAddress reference address in CodeCache. There are few places where it can be changed but it is for different RFE.

**Comment by dean-long** [comment]
How will Leyden relocate these references if they are changed to relocInfo::none?  Maybe these strings should be moved to the nmethod's _immutable_data?

**Comment by vnkozlov** [comment]
> How will Leyden relocate these references if they are changed to relocInfo::none? Maybe these strings should be moved to the nmethod's _immutable_data?

Very nice idea. I was already think about moving oop_maps and relocation info from CodeBlob into _immutable_data. I will include these strings too. In a separate RFE.

Until then Leyden will not support `VerifyOops`.

**Comment by vnkozlov** [comment]
I may need to use section_word relocation for that and add additional section type for _immutable_data.
I would also need to fix it for other platforms which do not have relocation for these strings.
It is not simple change and it needs a separate RFE.

**Comment by vnkozlov** [comment]
I did more investigation and there is an other way to solve this.

I think I can use `external_word_Relocation::spec_for_immediate()` instead of `relocInfo::none` to avoid growing global table (because external_word_Relocation::_target is nullptr in this case) and still mark them as external addresses, so Leyden can see these strings and support `VerifyOops`.

I did local testing and it works. I will test it more and update PR.  Thank you, @dean-long, for this discussion.

**Comment by dean-long** [comment]
I forgot about spec_for_immediate().  I think it will work.  For relocating in Leyden, you may need to enhance 
Relocation::pd_get_address_from_code() to recognize pushptr().

**Comment by vnkozlov** [comment]
Yes, I need add code similar too `oop_Relocation` and `metadata_Relocation` which uses 64-bit immediate because
`pushptr()` -> `lea() + push()` and `lea()` -> `mov_literal64()` for x64:  [macroAssembler_x86.cpp#L641](https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/macroAssembler_x86.cpp#L641)

**Comment by vnkozlov** [comment]
I ran tier7 which uses `-Xcomp -XX:+VerifyOops` flags combination. It passed clean with last update with `external_word_Relocation::spec_for_immediate()`.

**Review by TobiHartmann — APPROVED** [review]
Looks good as stop-the-gap solution. Do you think there are opportunities to improve the GrowableArray situation?

**Comment by vnkozlov** [comment]
> Looks good as stop-the-gap solution. Do you think there are opportunities to improve the GrowableArray situation?

I have already RFE for that: https://bugs.openjdk.org/browse/JDK-8334691

**Comment by TobiHartmann** [comment]
Ah, perfect! Thanks.

**Comment by vnkozlov** [comment]
@dean-long, are you fine with latest version?

**Review by dean-long — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
Thank you, Dean and Tobias, for reviews.

**Pull request closed without merging**
