### PR TITLE
JDK-8258479: Minor cleanups in VMError

### PR DESCRIPTION
**Pull request by tstuefe**
A list of smaller cleanups, each one too small to justify an own issue:

1) VMError exposes is_error_reported(), fatal_error_in_progress() and get_first_error_tid(). These functions are used from outside to check on the state of error handling. They can be combined and duplicate coding removed. Also, VMError::_error_reported can be removed, since its redundant with VMError::_first_error_tid != -1)
2) A lot of methods are unnecessarily public
3) the `env_var` array in vmError.cpp can be limited to file scope
4) definition of VMError static members should be combined to the start of the cpp file
5) the comment describing VMError::report() is misplaced
6) VMError::reset_signal_handlers() is badly named; nothing is reset here, the secondary signal handler is installed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258479](https://bugs.openjdk.java.net/browse/JDK-8258479): Minor cleanups in VMError

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**) ⚠️ Review applies to 47c59b57432de61cad73f6d29da349fa1a1b4e65
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 47c59b57432de61cad73f6d29da349fa1a1b4e65

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1802/head:pull/1802`
`$ git checkout pull/1802`

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
Nice cleanup!  A couple of files need copyright updated.
Lois

**Comment by tstuefe** [comment]
> Nice cleanup! A couple of files need copyright updated.
> Lois

Thank you Lois! I'll fix the copyrights before integrating.

**Review by coleenp — APPROVED** [review]
Looks good! Thank you for this cleanup.

**Comment by tstuefe** [comment]
> Looks good! Thank you for this cleanup.

:) Thanks Coleen!

**Pull request closed without merging**
