### PR TITLE
8255449: Improve the exception message of MethodHandles::permuteArguments

### PR DESCRIPTION
**Pull request by JornVernee**
Hi,

Currently, if MethodHandles::permuteArguments is used with a reorder array that is the wrong size, or one of the indexes in it is out of bounds of the new type, we simply get the exception message:

    bad reorder array [...]

I think we can improve the exception message by splitting these two error cases, and saying in the message exactly what went wrong.

permuteArguments is a tricky API, so improving the error message here should help to improve developer productivity.

This PR proposes splits the error message into e.g.:

    old type parameter count and reorder array length do not match: (int,int,String)int, [0, 0]

For an incorrect reorder array length, and:

    index is out of bounds for new type: 2, (int,String)int

For an out of bounds index.

Thanks,
Jorn

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ❌ (1/9 failed) |

**Failed test task**
- [macOS x64 (hs/tier1 gc)](https://github.com/JornVernee/jdk/runs/1321553024)

### Issue
 * [JDK-8255449](https://bugs.openjdk.java.net/browse/JDK-8255449): Improve the exception message of MethodHandles::permuteArguments

### Reviewers
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/878/head:pull/878`
`$ git checkout pull/878`

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
This looks okay to me. Someone from core-libs should take a look as well.

As the follow-up, maybe reconcile that method returns normally only with `true`, and throws exceptions otherwise. There are some uses like `assert(permuteArgumentChecks(...))` that apparently depend on this, how necessary are those?

**Comment by ChrisHegarty** [comment]
Seems like a reasonable change. Is there an already existing test for "bad" permute args that could be expanded to discern the new exception message?

**Comment by JornVernee** [comment]
> 
> 
> This looks okay to me. Someone from core-libs should take a look as well.
> 
> As the follow-up, maybe reconcile that method returns normally only with `true`, and throws exceptions otherwise. There are some uses like `assert(permuteArgumentChecks(...))` that apparently depend on this, how necessary are those?

It checks that the normalized reorder array is correct as well.

I'm a little reluctant to remove it right now though, since I just discovered a bug in that area: https://bugs.openjdk.java.net/browse/JDK-8255531 and it would be nice to have some extra safety nets when fixing that I think.

I agree it looks a little ugly, but let's leave it for now.

**Comment by JornVernee** [comment]
> 
> 
> Seems like a reasonable change. Is there an already existing test for "bad" permute args that could be expanded to discern the new exception message?

There are several tests for permuteArguments, but none that explicitly test this failure. I'll add some (good idea).

**Comment by JornVernee** [comment]
I've added some negative tests that test for the different failure conditions.

**Comment by ChrisHegarty** [comment]
Thanks for adding additional test coverage @JornVernee.

Writing a tight implementation of assertThrows is non-trivial - I'm not sure that the version you have will fail if the exception is not thrown?  Either way maybe we can reuse some of the junit machinery for this purpose, e.g.:

```
static final Class<IllegalArgumentException> IAE = IllegalArgumentException.class;

public void testReorderTypeMismatch() throws Throwable {
    MethodHandle mh = MethodHandles.empty(MethodType.methodType(void.class, int.class, int.class, String.class));
    MethodType newType = MethodType.methodType(void.class, double.class, String.class);
    var exception = expectThrows(IAE, () -> MethodHandles.permuteArguments(mh, newType, 0, 0, 1));
    assertMatches(exception.getMessage(), ".*parameter types do not match after reorder.*");
}

private static void assertMatches(String str, String pattern) {
    if (!str.matches(pattern)) {
        throw new AssertionError("'" + str + "' did not match the pattern '" + pattern + "'.");
    }
}
```

**Comment by ChrisHegarty** [comment]
My last comment, that suggested to use expectThrows was not appropriate for this junit test ( I mistakenly assumed that that functional was available, but it is not ) - withdrawn.

Thanks for adding the extra check in assertThrows. LGTM.

**Review by ChrisHegarty — APPROVED** [review]

**Review by mlchung — APPROVED** [review]
This looks okay to me.

**Pull request closed without merging**
