### PR TITLE
8315029: [BACKOUT] Generational ZGC: Tests crash with assert(index == 0 || is_power_of_2(index))

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset backs out the changes introduced by [JDK-8312749](https://bugs.openjdk.org/browse/JDK-8312749) and re-enables the problem-listed `test/jdk/java/lang/template/StringTemplateTest.java`. The backed-out issue will be re-addressed in [JDK-8315082](https://bugs.openjdk.org/browse/JDK-8315082).

#### Testing

- tier1-3 (windows-x64, linux-x64, linux-aarch64, macosx-x64, and macosx-aarch64)
- `test/jdk/java/lang/template/StringTemplateTest.java`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315029](https://bugs.openjdk.org/browse/JDK-8315029): [BACKOUT] Generational ZGC: Tests crash with assert(index == 0 || is_power_of_2(index)) (**Sub-task** - P2)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15442/head:pull/15442` \
`$ git checkout pull/15442`

Update a local copy of the PR: \
`$ git checkout pull/15442` \
`$ git pull https://git.openjdk.org/jdk.git pull/15442/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15442`

View PR using the GUI difftool: \
`$ git pr show -t 15442`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15442.diff">https://git.openjdk.org/jdk/pull/15442.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15442#issuecomment-1695327148)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good and trivial.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by robcasloz** [comment]
Thanks Christian and Martin!

**Pull request closed without merging**
