### PR TITLE
8314543: gitattributes: make diffs easier to read

### PR DESCRIPTION
**Pull request by rybak**
Git supports special hunk headers for several languages in diff output, which make it easier to read diffs of files in that language, generated by Git (git-diff, git-show, `git log -p`, etc).  For details, see `git help gitattributes` or [the online documentation](https://git-scm.com/docs/gitattributes).

Add entries to the root .gitattributes file to support showing the hunk headers for Java, C, C++, Markdown, Shell script, HTML, and CSS.  This makes it easier to read diffs generated by Git.

As an example, for j.l.Integer, before, the hunk header just shows the class name, found using the generic hunk header regex:

```diff
$ git show --format='' 71ca85f5a6741a2db55a529192564f94b269fbd9 -- src/java.base/share/classes/java/lang/Integer.java
diff --git a/src/java.base/share/classes/java/lang/Integer.java b/src/java.base/share/classes/java/lang/Integer.java
index 7d200e7edf5..9ec9d3941f8 100644
--- a/src/java.base/share/classes/java/lang/Integer.java
+++ b/src/java.base/share/classes/java/lang/Integer.java
@@ -517,13 +517,9 @@ public final class Integer extends Number
         }

         // We know there are at most two digits left at this point.
-        q = i / 10;
-        r = (q * 10) - i;
-        buf[--charPos] = (byte)('0' + r);
-
-        // Whatever left is the remaining digit.
-        if (q < 0) {
-            buf[--charPos] = (byte)('0' - q);
+        buf[--charPos] = DigitOnes[-i];
+        if (i < -9) {
+            buf[--charPos] = DigitTens[-i];
         }

         if (negative) {
```

After, the hunk shows the method edited by the commit, derived using the regex specific to Java:

```diff
$ git show --format='' 71ca85f5a6741a2db55a529192564f94b269fbd9 -- src/java.base/share/classes/java/lang/Integer.java
diff --git a/src/java.base/share/classes/java/lang/Integer.java b/src/java.base/share/classes/java/lang/Integer.java
index 7d200e7edf5..9ec9d3941f8 100644
--- a/src/java.base/share/classes/java/lang/Integer.java
+++ b/src/java.base/share/classes/java/lang/Integer.java
@@ -517,13 +517,9 @@ static int getChars(int i, int index, byte[] buf) {
         }

         // We know there are at most two digits left at this point.
-        q = i / 10;
-        r = (q * 10) - i;
-        buf[--charPos] = (byte)('0' + r);
-
-        // Whatever left is the remaining digit.
-        if (q < 0) {
-            buf[--charPos] = (byte)('0' - q);
+        buf[--charPos] = DigitOnes[-i];
+        if (i < -9) {
+            buf[--charPos] = DigitTens[-i];
         }

         if (negative) {
```

----

This was [previously discussed](https://mail.openjdk.org/pipermail/skara-dev/2023-August/008108.html) on the skara-dev mailing list.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314543](https://bugs.openjdk.org/browse/JDK-8314543): gitattributes: make diffs easier to read (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Koichi Sakata](https://openjdk.org/census#ksakata) (@jyukutyo - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15334/head:pull/15334` \
`$ git checkout pull/15334`

Update a local copy of the PR: \
`$ git checkout pull/15334` \
`$ git pull https://git.openjdk.org/jdk.git pull/15334/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15334`

View PR using the GUI difftool: \
`$ git pr show -t 15334`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15334.diff">https://git.openjdk.org/jdk/pull/15334.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15334#issuecomment-1682911167)

### CODE REVIEW

**Comment by erikj79** [comment]
I have filed https://bugs.openjdk.org/browse/JDK-8314543 for you. Just update the PR title with (just) the bug ID and Skara will associate the PR with that bug.

**Review by erikj79 — APPROVED** [review]

**Comment by rybak** [comment]
/summary

Git supports special hunk headers for several languages in diff output,
which make it easier to read diffs of files in that language, generated
by Git (git-diff, git-show, `git log -p`, etc).  For details, see
`git help gitattributes` or the online documentation.[1]

Add entries to the root .gitattributes file to support showing the hunk
headers for Java, C, C++, Markdown, Shell script, HTML, and CSS.  This
makes it easier to read diffs generated by Git.

As an example, for j.l.Integer, before, the hunk header just shows the
class name, found using the generic hunk header regex:

    $ git show --format='' 71ca85f5a6741a2db55a529192564f94b269fbd9 -- src/java.base/share/classes/java/lang/Integer.java
    diff --git a/src/java.base/share/classes/java/lang/Integer.java b/src/java.base/share/classes/java/lang/Integer.java
    index 7d200e7edf5..9ec9d3941f8 100644
    --- a/src/java.base/share/classes/java/lang/Integer.java
    +++ b/src/java.base/share/classes/java/lang/Integer.java
    @@ -517,13 +517,9 @@ public final class Integer extends Number
             }

             // We know there are at most two digits left at this point.
    -        q = i / 10;
    -        r = (q * 10) - i;
    -        buf[--charPos] = (byte)('0' + r);
    -
    -        // Whatever left is the remaining digit.
    -        if (q < 0) {
    -            buf[--charPos] = (byte)('0' - q);
    +        buf[--charPos] = DigitOnes[-i];
    +        if (i < -9) {
    +            buf[--charPos] = DigitTens[-i];
             }

             if (negative) {

After, the hunk shows the method edited by the commit, derived using the
regex specific to Java:

    $ git show --format='' 71ca85f5a6741a2db55a529192564f94b269fbd9 -- src/java.base/share/classes/java/lang/Integer.java
    diff --git a/src/java.base/share/classes/java/lang/Integer.java b/src/java.base/share/classes/java/lang/Integer.java
    index 7d200e7edf5..9ec9d3941f8 100644
    --- a/src/java.base/share/classes/java/lang/Integer.java
    +++ b/src/java.base/share/classes/java/lang/Integer.java
    @@ -517,13 +517,9 @@ static int getChars(int i, int index, byte[] buf) {
             }

             // We know there are at most two digits left at this point.
    -        q = i / 10;
    -        r = (q * 10) - i;
    -        buf[--charPos] = (byte)('0' + r);
    -
    -        // Whatever left is the remaining digit.
    -        if (q < 0) {
    -            buf[--charPos] = (byte)('0' - q);
    +        buf[--charPos] = DigitOnes[-i];
    +        if (i < -9) {
    +            buf[--charPos] = DigitTens[-i];
             }

             if (negative) {

[1] https://git-scm.com/docs/gitattributes

**Comment by rybak** [comment]
/summary
Git supports special hunk headers for several languages in diff output,
which make it easier to read diffs of files in that language, generated
by Git (git-diff, git-show, `git log -p`, etc).  For details, see
`git help gitattributes` or the online documentation.[1]

Add entries to the root .gitattributes file to support showing the hunk
headers for Java, C, C++, Markdown, Shell script, HTML, and CSS.  This
makes it easier to read diffs generated by Git.

[1] https://git-scm.com/docs/gitattributes

**Comment by rybak** [comment]
Looks like the summary command strips whitespace from beginning of lines. Because of that the example isn't readable, so I dropped the example from the commit message.

**Comment by erikj79** [comment]
That's a very detailed summary. We generally don't write that much. We try to make sure any relevant information can be found in the bug instead.

**Review by jyukutyo — APPROVED** [review]

**Comment by jyukutyo** [comment]
I'll sponsor you.

**Pull request closed without merging**
