### PR TITLE
8076089: Cleanup: Inline & remove sun.management.Util.newException

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review for this cleanup that's requested in https://bugs.openjdk.java.net/browse/JDK-8076089?

The change here removes a package private method `sun.management.Util.newException(Exception e)` and inlines its implementation at the caller locations.

Given the nature of this change no new jtreg tests have been added.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8076089](https://bugs.openjdk.java.net/browse/JDK-8076089): Cleanup: Inline & remove sun.management.Util.newException

### Reviewers
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer)
 * [Alex Menkov](https://openjdk.java.net/census#amenkov) (@alexmenkov - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7226/head:pull/7226` \
`$ git checkout pull/7226`

Update a local copy of the PR: \
`$ git checkout pull/7226` \
`$ git pull https://git.openjdk.java.net/jdk pull/7226/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7226`

View PR using the GUI difftool: \
`$ git pr show -t 7226`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7226.diff">https://git.openjdk.java.net/jdk/pull/7226.diff</a>

</details>

### CODE REVIEW

**Review by kevinjwalls — APPROVED** [review]
Looks good, thanks.

**Review by alexmenkov — APPROVED** [review]

**Review by dfuch — APPROVED** [review]
LGTM

**Review by sspitsyn — APPROVED** [review]
Good simplification.
Thanks,
Serguei

**Comment by jaikiran** [comment]
Thank you everyone for the reviews.

**Pull request closed without merging**
