### PR TITLE
8268261: C2: assert(n != __null) failed: Bad immediate dominator info.

### PR DESCRIPTION
**Pull request by vnkozlov**
The control for AddP node is set on N483 loop exit projection. AddP is address for Load node from following loop N426. 
After unswithching N483 loop its exit become nested and does not dominate loop N426. Which cause failure during following loop N426 unroll which tries to update control for Load node by looking on controls of its inputs.

I thought about not to place node on loop's exit projection as we do for loop's entry:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/loopnode.cpp#L5354
But it is not always possible.

I suggest to exit current round of loopopts when loop is unswitched and do an other round to recalculate idom data. 
It should not affect compilation speed noticeable because unswitching is rare case.

Tested tier1-3, xcomp. Currently running performance testing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268261](https://bugs.openjdk.java.net/browse/JDK-8268261): C2: assert(n != __null) failed: Bad immediate dominator info.

### Reviewers
 * [Igor Veresov](https://openjdk.java.net/census#iveresov) (@veresov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4879/head:pull/4879` \
`$ git checkout pull/4879`

Update a local copy of the PR: \
`$ git checkout pull/4879` \
`$ git pull https://git.openjdk.java.net/jdk pull/4879/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4879`

View PR using the GUI difftool: \
`$ git pr show -t 4879`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4879.diff">https://git.openjdk.java.net/jdk/pull/4879.diff</a>

</details>

### CODE REVIEW

**Review by veresov — APPROVED** [review]

**Comment by vnkozlov** [comment]
Thank you, Igor.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by vnkozlov** [comment]
Thank you, Vladimir I.

**Pull request closed without merging**
