### PR TITLE
8256535: C2: randomize CCP processing order for stress testing

### PR DESCRIPTION
**Pull request by robcasloz**
Add `StressCCP` option to randomize the selection of the node to be examined in each CCP iteration.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256535](https://bugs.openjdk.java.net/browse/JDK-8256535): C2: randomize CCP processing order for stress testing

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to 95d2cae328bea09ed5caaa6212672d389e1b72d2
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to 95d2cae328bea09ed5caaa6212672d389e1b72d2

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1765/head:pull/1765`
`$ git checkout pull/1765`

### CODE REVIEW

**Comment by robcasloz** [comment]
/summary
Add 'StressCCP' option to randomize the selection of the node to be examined in
each CCP iteration.

**Comment by robcasloz** [comment]
Tested with:

-  test cases updated in this change (`TestStressOptions.java`, `TestGenerateStressSeed.java`, `TestStressIGVNAndCCP.java`)
- 20 repetitions of the `hotspot_compiler` test group with `-XX:+StressCCP`

**Comment by robcasloz** [comment]
I assume the failures in the GitHub pre-submit tests are due to some problem with the GitHub Actions setup, as the same tests pass locally.

**Review by chhagedorn — APPROVED** [review]
Looks good to me! Nice to have another stress option available.

**Comment by robcasloz** [comment]
> Looks good to me! Nice to have another stress option available.

Thanks for reviewing, Christian!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks, Vladimir!

**Review by TobiHartmann — APPROVED** [review]
Looks good. Before integration, please make sure to run this through testing with `-XX:RepeatCompilation` to make sure it does not trigger any bugs right away.

**Comment by robcasloz** [comment]
> Looks good. Before integration, please make sure to run this through testing with `-XX:RepeatCompilation` to make sure it does not trigger any bugs right away.

Thanks Tobias, will do!

**Comment by robcasloz** [comment]
Tested on hs-tier1-3 with `-XX:+StressCCP -XX:+LogCompilation -XX:RepeatCompilation=20` as requested by @TobiHartmann. All 76 failures have been traced to test code not handling `LogCompilation`, `RepeatCompilation` (for example [JDK-8258682](https://bugs.openjdk.java.net/browse/JDK-8258682)), or both. No failure could be attributed to `StressCCP` itself. Requesting integration.

**Comment by robcasloz** [comment]
Postponing integration until I am back from holidays.

**Comment by robcasloz** [comment]
Back from holidays, please sponsor.

**Comment by robcasloz** [comment]
I just realized the headers of the touched files need to be update with the current copyright year. Withdrawing request for integration again, sorry for going back and forth.

**Comment by robcasloz** [comment]
Ready for review after updating copyright headers.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by vnkozlov** [comment]
I don't think you need to wait all reviews again. You only updated Copyright years. I can sponsor after you integrate it.

**Comment by robcasloz** [comment]
> I don't think you need to wait all reviews again. You only updated Copyright years. I can sponsor after you integrate it.

OK, thanks for re-reviewing Vladimir!

**Pull request closed without merging**
