### PR TITLE
8332904: ubsan ppc64le: c1_LIRGenerator_ppc.cpp:581:21: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int'

### PR DESCRIPTION
**Pull request by MBaesken**
When using ubsan on Linux ppc64le we run into some overflows like this one

c1_LIRGenerator_ppc.cpp:581:21: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int'

Seems we have to add casts to get defined behavior.
There are similar places in the coding as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8332904: ubsan ppc64le: c1_LIRGenerator_ppc.cpp:581:21: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int'`

### Issue
 * [JDK-8332904](https://bugs.openjdk.org/browse/JDK-8332904): ubsan ppc64le: c1_LIRGenerator_ppc.cpp:581:21: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int' (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Joachim Kern](https://openjdk.org/census#jkern) (@JoKern65 - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19413/head:pull/19413` \
`$ git checkout pull/19413`

Update a local copy of the PR: \
`$ git checkout pull/19413` \
`$ git pull https://git.openjdk.org/jdk.git pull/19413/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19413`

View PR using the GUI difftool: \
`$ git pr show -t 19413`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19413.diff">https://git.openjdk.org/jdk/pull/19413.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19413#issuecomment-2133642368)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Thank you for fixing it!

**Comment by MBaesken** [comment]
Hi Martin, thanks for the review !
May I get a second review ?

**Review by JoKern65 — COMMENTED** [review]
LGTM

**Review by JoKern65 — APPROVED** [review]

**Comment by MBaesken** [comment]
Thanks for the reviews !

/integrate

**Pull request closed without merging**
