### PR TITLE
8277012: Use blessed modifier order in src/utils

### PR DESCRIPTION
**Pull request by magicus**
I ran bin/blessed-modifier-order.sh on source code in src/utils. This scripts verifies that modifiers are in the "blessed" order, and fixes it otherwise. I have manually checked the changes made by the script to make sure they are sound.

There are no clear ownership of this code, but I believe it's kind of hotspot-related.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277012](https://bugs.openjdk.java.net/browse/JDK-8277012): Use blessed modifier order in src/utils

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6354/head:pull/6354` \
`$ git checkout pull/6354`

Update a local copy of the PR: \
`$ git checkout pull/6354` \
`$ git pull https://git.openjdk.java.net/jdk pull/6354/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6354`

View PR using the GUI difftool: \
`$ git pr show -t 6354`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6354.diff">https://git.openjdk.java.net/jdk/pull/6354.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks fine.

Thanks,
David

**Review by tstuefe — APPROVED** [review]
+1

**Pull request closed without merging**
