### PR TITLE
8256917: Use combo @returns tag in java.compiler javadoc

### PR DESCRIPTION
**Pull request by jddarcy**
Take advantage of upgraded dual-use @return tag.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256917](https://bugs.openjdk.java.net/browse/JDK-8256917): Use combo @returns tag in java.compiler javadoc

### Reviewers
 * [Jonathan Gibbons](https://openjdk.java.net/census#jjg) (@jonathan-gibbons - **Reviewer**)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1708/head:pull/1708`
`$ git checkout pull/1708`

### CODE REVIEW

**Review by jonathan-gibbons — APPROVED** [review]
Pleasantly boring. Nice to see the duplication going away.

In places, I would have tweaked the phrasing or the layout, but I accept that would be out of scope for the intent of this otherwise simple change.

**Review by irisclark — APPROVED** [review]
Straightforward.  I see a few minor differences (e.g. "otherwise returns X" -> "otherwise X"), but nothing significant.  

Fantastic use of the new @returns tag.  I look forward to seeing it used across the JDK.

**Comment by jddarcy** [comment]
> 
> 
> Pleasantly boring. Nice to see the duplication going away.
> 
> In places, I would have tweaked the phrasing or the layout, but I accept that would be out of scope for the intent of this otherwise simple change.



> 
> 
> Pleasantly boring. Nice to see the duplication going away.

The feature is working as intended :-)
 
> In places, I would have tweaked the phrasing or the layout, but I accept that would be out of scope for the intent of this otherwise simple change.

Right; this was a first pass over the JSR 269 API to apply new upgraded @return tag. Fuller use could be made to DRY-out the API on subsequent passes. If I was writing the spec for this API from scratch, I'd incorporate the new facility to being with.

**Comment by jddarcy** [comment]
> 
> 
> Straightforward. I see a few minor differences (e.g. "otherwise returns X" -> "otherwise X"), but nothing significant.

Yes; I didn't limit my pass over the API to cases where there was strict duplication, near duplication was fair game too :-) From an offline specdiff, there weren't any unexpected changes and most of the individual code diffs didn't lead to spec diffs.

> Fantastic use of the new @returns tag. I look forward to seeing it used across the JDK.

Kudos to @jonathan-gibbons and the javadoc team for getting this feature in!

**Pull request closed without merging**
