### PR TITLE
JDK-8310814: Clarify the targetName parameter of Lookup::findClass

### PR DESCRIPTION
**Pull request by mlchung**
This PR updates the spec of `Lookup::findClass` to reflect the current behavior that requires a binary name or a string representing an array class in the form as returned by `Class::getName`.    

`test/jdk/java/lang/invoke/accessClassAndFindClass/TestFindClass.java` already covers the test cases of a nested class and an array class.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8310833](https://bugs.openjdk.org/browse/JDK-8310833) to be approved

### Issues
 * [JDK-8310814](https://bugs.openjdk.org/browse/JDK-8310814): Clarify the targetName parameter of Lookup::findClass (**Bug** - P4)
 * [JDK-8310833](https://bugs.openjdk.org/browse/JDK-8310833): Clarify the targetName parameter of Lookup::findClass (**CSR**)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - Author)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Brent Christian](https://openjdk.org/census#bchristi) (@bchristi-git - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14668/head:pull/14668` \
`$ git checkout pull/14668`

Update a local copy of the PR: \
`$ git checkout pull/14668` \
`$ git pull https://git.openjdk.org/jdk.git pull/14668/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14668`

View PR using the GUI difftool: \
`$ git pr show -t 14668`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14668.diff">https://git.openjdk.org/jdk/pull/14668.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14668#issuecomment-1608308805)

### CODE REVIEW

**Review by liach — APPROVED** [review]
A nice correction and followup of `Class::forName` spec update.

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Review by bchristi-git — APPROVED** [review]
Looks fine.

**Comment by mlchung** [comment]
Thank you for the review.

**Pull request closed without merging**
