### PR TITLE
8270830: Aarch64: Use stp to initialize object on C1

### PR DESCRIPTION
**Pull request by Wanghuang-Huawei**
Here is a trivail patch on aarch64. 
It is found that in C1_MacroAssembler::initialize_object which we can use` stp `to replace` str`.
```c++
@@ -250,13 +249,16 @@ void C1_MacroAssembler::initialize_object(Register obj, Register klass, Register
        for (int i = -unroll; i < 0; i++) {
          if (-i == remainder)
            bind(entry_point);
- str(zr, Address(rscratch1, i * wordSize));
+ stp(zr, zr, Address(rscratch1, i * 2 * BytesPerWord));
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8270830](https://bugs.openjdk.java.net/browse/JDK-8270830): Aarch64: Use stp to initialize object on C1

### Contributors
 * Wang Huang `<whuang@openjdk.org>`
 * Miao Zhuojun `<mouzhuojun@huawei.com>`
 * Wu Yan `<wuyan@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4808/head:pull/4808` \
`$ git checkout pull/4808`

Update a local copy of the PR: \
`$ git checkout pull/4808` \
`$ git pull https://git.openjdk.java.net/jdk pull/4808/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4808`

View PR using the GUI difftool: \
`$ git pr show -t 4808`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4808.diff">https://git.openjdk.java.net/jdk/pull/4808.diff</a>

</details>

### CODE REVIEW

**Comment by nick-arm** [comment]
How have you tested this?

**Comment by snazarkin** [comment]
Should not **unroll** be adjusted after switching to double word write?

**Comment by theRealAph** [comment]
This C1 code is being rewritten to use the common MacroAssembler::zero words which was written for C2. It's shorter and faster and there's less code to maintain. It doesn't make any sense to change the C1 code at this time,

**Comment by wuyan0** [comment]
Thanks for your reply, I will close this pull request.

**Pull request closed without merging**
