### PR TITLE
8307148: Incorrect Javadoc Tags in JDK

### PR DESCRIPTION
**Pull request by kabutz**
The JDK has several Javadoc comments with incorrect tags. For example, in several classes, the @param tag was omitted or misspelled, such as "@object ..." instead of "@param object".

In other cases, @implNote is misspelled as @note or @ImplNote or @implnote.

We also found cases of @returns instead of @return and @throw instead of @throws.

Lastly, there are tags using @deprecation and @Deprecation instead of @deprecated.

This issue might be related in part to https://bugs.openjdk.org/browse/JDK-8210241

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307148](https://bugs.openjdk.org/browse/JDK-8307148): Incorrect Javadoc Tags in JDK (**Bug** - P5)

### Reviewers
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13736/head:pull/13736` \
`$ git checkout pull/13736`

Update a local copy of the PR: \
`$ git checkout pull/13736` \
`$ git pull https://git.openjdk.org/jdk.git pull/13736/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13736`

View PR using the GUI difftool: \
`$ git pr show -t 13736`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13736.diff">https://git.openjdk.org/jdk/pull/13736.diff</a>

</details>

### CODE REVIEW

**Review by jonathan-gibbons — COMMENTED** [review]
Looks good in principle.
Note there was a trailing whitespace issue to be fixed.
Some of the files may be imports from upstream repos, so it's not clear what the policy is for updating these files for minor cleanup like this.
Since the PR covers many areas/components, you should try and get approval from members of the associated teams.

**Comment by kabutz** [comment]
> Looks good in principle. Note there was a trailing whitespace issue to be fixed. Some of the files may be imports from upstream repos, so it's not clear what the policy is for updating these files for minor cleanup like this. Since the PR covers many areas/components, you should try and get approval from members of the associated teams.

Thanks for the feedback Jonathan. I'll try find the project owners of all the various components. This was my fear - it's a very broad change.

**Comment by mrserb** [comment]
The changes in java.desktop module looks fine, I suggest extracting them and creating a separate PR for review.

**Review by jonathan-gibbons — APPROVED** [review]
There are a few places where the text of a description could be improved, but I'm OK to leave those as out-of-scope for this PR which is focussed on fixing tag typos.

**Pull request closed without merging**
