### PR TITLE
8285507: revert fix for JDK-8282704 now that JDK-8282952 is fixed

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Revert (most of) the fix for JDK-8282704 now that JDK-8282952 is fixed.

This fix has been tested with Mach5 Tier[1-7] (about to start a Tier8) and I also ran
my StressWrapper_StopAtExit.java test using {release, fastdebug, and slowdebug}
bits for 12 hours per config. No failures for StressWrapper_StopAtExit.java.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285507](https://bugs.openjdk.java.net/browse/JDK-8285507): revert fix for JDK-8282704 now that JDK-8282952 is fixed

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to a35695adfabc32cc01b3e83eab8d117fb5b1f8f1
 * [Patricio Chilano Mateo](https://openjdk.java.net/census#pchilanomate) (@pchilano - **Reviewer**) ⚠️ Review applies to a35695adfabc32cc01b3e83eab8d117fb5b1f8f1

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8389/head:pull/8389` \
`$ git checkout pull/8389`

Update a local copy of the PR: \
`$ git checkout pull/8389` \
`$ git pull https://git.openjdk.java.net/jdk pull/8389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8389`

View PR using the GUI difftool: \
`$ git pr show -t 8389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8389.diff">https://git.openjdk.java.net/jdk/pull/8389.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
@pchilano and @dholmes-ora - please review this when you get the chance.

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,
David

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - Thanks for the review. Since I made this a dependent PR on
https://github.com/openjdk/jdk/pull/8388 it will have to wait until that PR is
integrated.

**Review by dholmes-ora — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - Thanks for the re-review.

Mach5 Tier[1-7] testing has passed nicely.

**Comment by dcubed-ojdk** [comment]
@pchilano - Please review this fix when you get the chance... Thanks!

**Review by pchilano — APPROVED** [review]
Looks good!

Thanks,
Patricio

**Comment by dcubed-ojdk** [comment]
@pchilano - Thanks for the review!

**Pull request closed without merging**
