### PR TITLE
8310843: Reimplement ByteArray and ByteArrayLittleEndian with Unsafe

### PR DESCRIPTION
**Pull request by Glavo**
Things have changed since https://github.com/openjdk/jdk/pull/14636 was closed, so let me reopen it.

https://github.com/openjdk/jdk/pull/15386 confirmed that `VarHandle` in BALE caused a startup regression. In order to not have any more revert patches, it makes sense to optimize BALE.

The optimization of https://github.com/openjdk/jdk/pull/16245 allows the traditional expression to have good performance, but BA and BALE save us from having to copy these lengthy expressions everywhere. So it makes sense to keep them.

Now here's the question, should I rewrite this PR without `Unsafe`? I'll do some research (e.g. does `Unsafe` have better performance during warmup?), but I'd also like to take some advice.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310843](https://bugs.openjdk.org/browse/JDK-8310843): Reimplement ByteArray and ByteArrayLittleEndian with Unsafe (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19616/head:pull/19616` \
`$ git checkout pull/19616`

Update a local copy of the PR: \
`$ git checkout pull/19616` \
`$ git pull https://git.openjdk.org/jdk.git pull/19616/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19616`

View PR using the GUI difftool: \
`$ git pr show -t 19616`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19616.diff">https://git.openjdk.org/jdk/pull/19616.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19616#issuecomment-2157060148)

### CODE REVIEW

**Comment by liach** [comment]
No matter if we use unsafe or not, keeping multi-byte write and read operations all to one class so we can update them altogether sounds like a good idea. The only risk is that some operations will happen in early startup, such as ClassFile processing, which prohibits some implementations like VarHandle.

**Comment by minborg** [comment]
Would it be possible to add a benchmark for some of the methods here so we can see if there is a difference? Also, it would be interesting to see if startup performance is impacted.

**Comment by wenshao** [comment]
#16245 combining values ​​into larger store, Instead of using Unsafe, can we implement it as follows, similar to the early versions of java.nio.Bits?

```java
class ByteArrayLittleEndian {
    // ...
    public static void setInt(byte[] array, int offset, int value) {
        array[offset    ] = (byte)  value;
        array[offset + 1] = (byte) (value >> 8);
        array[offset + 2] = (byte) (value >> 16);
        array[offset + 3] = (byte) (value >> 24);
    }

	public static void setLong(byte[] bytes, int off, long value) {
        array[offset]     = (byte)  value;
        array[offset + 1] = (byte) (value >> 8);
        array[offset + 2] = (byte) (value >> 16);
        array[offset + 3] = (byte) (value >> 24);
        array[offset + 4] = (byte) (value >> 32);
        array[offset + 5] = (byte) (value >> 40);
        array[offset + 6] = (byte) (value >> 48);
        array[offset + 7] = (byte) (value >> 56);
    }
    // ...
}
```

**Comment by wenshao** [comment]
I submitted a PR #19734 with a set of performance benchmarks for Batch operations that should provide performance numbers that you can use to improve ByteArray and ByteArrayLittleEndian.

**Comment by liach** [comment]
With merge stores, you can probably reimplement these two classes with direct array writes instead of Unsafe, for ease of maintenance.

**Pull request closed without merging**
