### PR TITLE
8304501: Remove orphaned demo netbeans projects

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which suggests we remove the orhphaned `SwingApplet` netbeans project directory.

The `SwingApplet` demo was removed in [JDK-8205119](https://bugs.openjdk.org/browse/JDK-8205119), but the netbeans projects files were left behind.

Additionally, the following netbeans projects reference source files that do not exist (if they ever did?):

- src/demo/share/nbproject/management/FullThreadDump
- src/demo/share/nbproject/management/JTop
- src/demo/share/nbproject/management/MemoryMonitor
- src/demo/share/nbproject/management/VerboseGC
- src/demo/share/nbproject/scripting/jconsole-plugin

The PR deletes files in these directories as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304501](https://bugs.openjdk.org/browse/JDK-8304501): Remove orphaned demo netbeans projects

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13098/head:pull/13098` \
`$ git checkout pull/13098`

Update a local copy of the PR: \
`$ git checkout pull/13098` \
`$ git pull https://git.openjdk.org/jdk.git pull/13098/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13098`

View PR using the GUI difftool: \
`$ git pr show -t 13098`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13098.diff">https://git.openjdk.org/jdk/pull/13098.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13098#issuecomment-1475996900)

### CODE REVIEW

**Comment by eirbjo** [comment]
I notice now that the following netbeans projects also seems orphaned:

- src/demo/share/nbproject/management/FullThreadDump
- src/demo/share/nbproject/management/JTop
- src/demo/share/nbproject/management/MemoryMonitor
- src/demo/share/nbproject/management/VerboseGC
- src/demo/share/nbproject/scripting/jconsole-plugin

Would it make sense to repurpose this PR and issue to clean up all of these? I could rename this to "Removed orphaned demo netbeans projects".

I imagine creating issues/PRs for each of these will add quite a bit of overhead..?

**Comment by mrserb** [comment]
Deleting the SwingApplet looks fine.

**Review by mrserb — APPROVED** [review]

**Comment by eirbjo** [comment]
> Deleting the SwingApplet looks fine.

This PR also deletes five other projects in `management` and ‘scripting`. Are those also okay?

**Review by AlanBateman — COMMENTED** [review]
These were demo/sample code in JDK 5.

**Comment by prrace** [comment]
> Deleting the SwingApplet looks fine.

Ditto.

**Comment by prrace** [comment]
> > These were demo/sample code in JDK 5.
> 
> @mrserb would you please confirm if your review approval applies to `SwingApplet` only or the whole PR? As it stands, it is not clear to me whether this PR is approved or not. Thanks!

I am pretty sure Alan was approving the whole lot of them.

**Comment by eirbjo** [comment]
> I am pretty sure Alan was approving the whole lot of them.

Phil,

Thanks, but it seems Alan did not actually approve anything, he simply left an infomational note.

We still only have the approval from Sergey, and it is still not clear what he approved.

**Comment by AlanBateman** [comment]
> Thanks, but it seems Alan did not actually approve anything, he simply left an infomational note.
> 
> We still only have the approval from Sergey, and it is still not clear what he approved.

Right, I just added a note as I remember these demos from JDK 5. I think you are okay to integrate this change.

**Comment by eirbjo** [comment]
This approved PR is looking for a friendly sponsor.

**Pull request closed without merging**
