### PR TITLE
8305073: Fix VerifyLoopOptimizations - step 2 - verify idom

### PR DESCRIPTION
**Pull request by eme64**
This is the second step in the `VerifyLoopOptimizations` revival.

Last step:
[JDK-8173709](https://bugs.openjdk.org/browse/JDK-8173709) Fix VerifyLoopOptimizations - step 1 - minimal infrastructure 
See PR for all the planned steps: https://github.com/openjdk/jdk/pull/13207

Bug fixing for this step:
[JDK-8308084](https://bugs.openjdk.org/browse/JDK-8308084) C2 fix idom bug in PhaseIdealLoop::create_new_if_for_predicate
(https://github.com/openjdk/jdk/pull/13980)

Next step:
[JDK-8307982](https://bugs.openjdk.org/browse/JDK-8307982) Fix VerifyLoopOptimizations - step 3 - fix ctrl/loop

I added `TestVerifyLoopOptimizations.java` per @robcasloz 's request. It works just like `TestVerifyIterativeGVN.java`, with a simple `-Xcomp -XX:+VerifyLoopOptimizations` on a basically empty test. It fails until this patch is integrated: https://github.com/openjdk/jdk/pull/13980

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305073](https://bugs.openjdk.org/browse/JDK-8305073): Fix VerifyLoopOptimizations - step 2 - verify idom

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13951/head:pull/13951` \
`$ git checkout pull/13951`

Update a local copy of the PR: \
`$ git checkout pull/13951` \
`$ git pull https://git.openjdk.org/jdk.git pull/13951/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13951`

View PR using the GUI difftool: \
`$ git pr show -t 13951`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13951.diff">https://git.openjdk.org/jdk/pull/13951.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13951#issuecomment-1545479187)

### CODE REVIEW

**Comment by eme64** [comment]
I think this is very difficult, if it is even possible at all. The idom info may be wrong, but I'm not sure if it ever leads to a real failure. Honestly, there are too many idom / ctrl / loop "bugs" that I will encounter with this verification work. If we are worried about backports, we can split the fixes from the verification. But finding regression tests that actually mainfest in an assert or wrong execution, that will be an immense effort.

**Comment by robcasloz** [comment]
> If we are worried about backports, we can split the fixes from the verification.

I think this is a good idea, yes.

> But finding regression tests that actually mainfest in an assert or wrong execution, that will be an immense effort.

Fair enough. A low-effort, "catch-all" idea would be to add a test with `-Xcomp -XX:+VerifyLoopOptimizations`, similarly to `TestVerifyIterativeGVN.java`.

**Review by chhagedorn — APPROVED** [review]
Looks good! I also think it's a good idea to go with a Hello World like test.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by eme64** [comment]
Update: the bug fix is pushed (https://github.com/openjdk/jdk/pull/13980) now I can run testing here again.

**Comment by eme64** [comment]
Tests just passed again, up to tier6  and stress testing, with and without the flag.

@robcasloz @vnkozlov @chhagedorn @TobiHartmann Thanks for the reviews and suggestions!
/integrate

**Pull request closed without merging**
