### PR TITLE
8327283: RISC-V: Minimal build failed after JDK-8319716

### PR DESCRIPTION
**Pull request by zifeihan**
Hi, please review this patch that fix the minimal build failed for riscv.

Error log for minimal build:
```
Creating support/modules_libs/java.base/minimal/libjvm.so from 591 file(s)
^@/home/zifeihan/jdk/src/hotspot/cpu/riscv/stubGenerator_riscv.cpp: In member function ‘u_char* StubGenerator::Sha2Generator::generate_sha2_implCompress(Assembler::SEW, bool)’:
/home/zifeihan/jdk/src/hotspot/cpu/riscv/stubGenerator_riscv.cpp:3938:41: error: ‘MaxVectorSize’ was not declared in this scope; did you mean ‘MaxNewSize’?
 3938 |       if (vset_sew == Assembler::e64 && MaxVectorSize == 16) { // SHA512 and VLEN = 128
      |                                         ^~~~~~~~~~~~~
      |                                         MaxNewSize
gmake[3]: *** [lib/CompileJvm.gmk:165: /home/zifeihan/jdk/build/linux-riscv64-minimal-fastdebug/hotspot/variant-minimal/libjvm/objs/stubGenerator_riscv.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
^@gmake[2]: *** [make/Main.gmk:253: hotspot-minimal-libs] Error 2
gmake[2]: *** Waiting for unfinished jobs....
^@
ERROR: Build failed for target 'images' in configuration 'linux-riscv64-minimal-fastdebug' (exit code 2)

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-minimal_libjvm_objs_stubGenerator_riscv.o:
/home/zifeihan/jdk/src/hotspot/cpu/riscv/stubGenerator_riscv.cpp: In member function ‘u_char* StubGenerator::Sha2Generator::generate_sha2_implCompress(Assembler::SEW, bool)’:
/home/zifeihan/jdk/src/hotspot/cpu/riscv/stubGenerator_riscv.cpp:3938:41: error: ‘MaxVectorSize’ was not declared in this scope; did you mean ‘MaxNewSize’?
 3938 |       if (vset_sew == Assembler::e64 && MaxVectorSize == 16) { // SHA512 and VLEN = 128
      |                                         ^~~~~~~~~~~~~
      |                                         MaxNewSize

* All command lines available in /home/zifeihan/jdk/build/linux-riscv64-minimal-fastdebug/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
HELP: Try searching the build log for '] Error'.
HELP: Run 'make doctor' to diagnose build problems.

make[1]: *** [/home/zifeihan/jdk/make/Init.gmk:323: main] Error 2
make: *** [/home/zifeihan/jdk/make/Init.gmk:189: images] Error 2
```

The root cause is that MaxVectorSize is only defined under COMPILER2 , We should use VM_Version::_initial_vector_length instead of MaxVectorSize.  

Testing:

- [x] linux-riscv minimal fastdebug native build

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327283](https://bugs.openjdk.org/browse/JDK-8327283): RISC-V: Minimal build failed after JDK-8319716 (**Bug** - P3)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18114/head:pull/18114` \
`$ git checkout pull/18114`

Update a local copy of the PR: \
`$ git checkout pull/18114` \
`$ git pull https://git.openjdk.org/jdk.git pull/18114/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18114`

View PR using the GUI difftool: \
`$ git pr show -t 18114`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18114.diff">https://git.openjdk.org/jdk/pull/18114.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18114#issuecomment-1978159150)

### CODE REVIEW

**Comment by zifeihan** [comment]
@robehn Could you please take a look？

**Comment by robehn** [comment]
The SHA intrinsic are only used in "LibraryCallKit::inline_digestBase_implCompress" and JVMCI.
So I also I think these (plus md5 and chacha) should be put into a ifdef COMPILER2_OR_JVMCI block. (I was going todo that bu it slipped my mind)

The MaxVectorSize is defined if JVMCI and/or C2 is defined:
`NOT_COMPILER2(product(intx, MaxVectorSize, 64,`

**Comment by zifeihan** [comment]
> The SHA intrinsic are only used in "LibraryCallKit::inline_digestBase_implCompress" and JVMCI. So I think these (plus md5 and chacha) should be put into a ifdef COMPILER2_OR_JVMCI block. (I was going todo that but it slipped my mind)
> 
> The MaxVectorSize is defined if JVMCI and/or C2 is defined: `NOT_COMPILER2(product(intx, MaxVectorSize, 64,`



> The SHA intrinsic are only used in "LibraryCallKit::inline_digestBase_implCompress" and JVMCI. So I think these (plus md5 and chacha) should be put into a ifdef COMPILER2_OR_JVMCI block. (I was going todo that but it slipped my mind)
> 
> The MaxVectorSize is defined if JVMCI and/or C2 is defined: `NOT_COMPILER2(product(intx, MaxVectorSize, 64,`

Yes, You are right. I've considered this way putting the function definition under a ifdef COMPILER2_OR_JVMCI block. But I find that no other CPU does this. I am not sure if there is any other reason for this. But I can do that if we all think it's better.

**Review by RealFYang — COMMENTED** [review]
I agree with @robehn ! We can put those functions definitions into a ifdef COMPILER2_OR_JVMCI block to avoid such a problem. I don't see other uses of them for now.

**Comment by robehn** [comment]
> I agree with @robehn ! We can put those functions definitions into a ifdef COMPILER2_OR_JVMCI block to avoid such a problem. I don't see other uses of them for now.

This also makes it clear that C1/interpreter don't use them, hence if someone needs a speed up there they could try to make use of them.

**Comment by zifeihan** [comment]
@robehn @RealFYang Thanks for your review, I've put those functions definitions into a #if COMPILER2_OR_JVMCI block to avoid such a problem. The reason why #ifdef COMPILER2_OR_JVMCI is not used is because it might be defined as `#define COMPILER2_OR_JVMCI 0`  Can you please look at it again?
```
// COMPILER2 or JVMCI
#if defined(COMPILER2) || INCLUDE_JVMCI
#define COMPILER2_OR_JVMCI 1
#define COMPILER2_OR_JVMCI_PRESENT(code) code
#define NOT_COMPILER2_OR_JVMCI(code)
#define NOT_COMPILER2_OR_JVMCI_RETURN        /* next token must be ; */
#define NOT_COMPILER2_OR_JVMCI_RETURN_(code) /* next token must be ; */
#else
#define COMPILER2_OR_JVMCI 0
#define COMPILER2_OR_JVMCI_PRESENT(code)
#define NOT_COMPILER2_OR_JVMCI(code) code
#define NOT_COMPILER2_OR_JVMCI_RETURN {}
#define NOT_COMPILER2_OR_JVMCI_RETURN_(code) { return code; }
#endif
```

**Comment by RealFYang** [comment]
Hi, I think we can simply move the sha256/512 part together with code for md5, chacha20 and sha1 and add put them into one single #if COMPILER2_OR_JVMCI block. Thanks.

**Comment by zifeihan** [comment]
Hi, I've made the changes for the review, and the minimal/server build was successful.

**Review by robehn — APPROVED** [review]
Thanks!

**Comment by zifeihan** [comment]
@robehn @RealFYang : Thanks all for the review
/integrate

**Pull request closed without merging**
