### PR TITLE
8287227: Shenandoah: A couple of virtual thread tests failed with iu mode even without Loom enabled.

### PR DESCRIPTION
**Pull request by rwestrel**
With JDK-8277654, the load barrier slow path call doesn't produce raw
memory anymore but the IU barrier call still does. I propose removing
raw memory for that call too which also causes the assert that fails
to be removed.

/cc hotspot-compiler

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287227](https://bugs.openjdk.org/browse/JDK-8287227): Shenandoah: A couple of virtual thread tests failed with iu mode even without Loom enabled.

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [5699e042](https://git.openjdk.org/jdk/pull/8958/files/5699e04251d749303eb7e452e264d26e61b7a7eb)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/8958/head:pull/8958` \
`$ git checkout pull/8958`

Update a local copy of the PR: \
`$ git checkout pull/8958` \
`$ git pull https://git.openjdk.org/jdk pull/8958/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8958`

View PR using the GUI difftool: \
`$ git pr show -t 8958`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/8958.diff">https://git.openjdk.org/jdk/pull/8958.diff</a>

</details>

### CODE REVIEW

**Comment by rkennke** [comment]
Is it correct, though? I seem to remember that without the memory edges, we may get reordering of the 'SATB' buffer and index accesses between IU-barriers, which would cause troubles?

**Review by shipilev — APPROVED** [review]
Looks reasonable to me. Please link up JDK-8277654 to this bug.

**Comment by rwestrel** [comment]
> Is it correct, though? I seem to remember that without the memory edges, we may get reordering of the 'SATB' buffer and index accesses between IU-barriers, which would cause troubles?

Ok. I propose a different fix then. The state of the MemoryGraphFixer needs to be updated when LRBs are expanded. It used to be the case before JDK-8277654.

**Review by rkennke — APPROVED** [review]
Looks good to me! Thank you!

**Review by shipilev — APPROVED** [review]
Looks good.

I tested `jdk_loom hotspot_loom` with Linux x86_64 fastdebug Shenandoah, including IU mode, and they pass. Apart from the known `Skynet` failure that is tracked separately.

Also ran Linux x86_64 fastdebug `tier1` with Shenandoah, with some unrelated failures.

**Review by rkennke — APPROVED** [review]

**Comment by rwestrel** [comment]
@rkennke @shipilev thanks for the review and tests

**Pull request closed without merging**
