### PR TITLE
8254335: logging/logStream.hpp includes memory/resourceArea.hpp but doesn't need it

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
While cleaning up the logging in Erik's new code for:

    JDK-8253064 monitor list simplifications and getting rid of TSM

I noticed that logging/logStream.hpp includes memory/resourceArea.hpp
but doesn't need it.

That include was added to logging/logStream.hpp by:

    JDK-8153659 Create a CHeap backed LogStream class

but logging/logStream.hpp has since evolved to no longer
use ResourceMarks in the header file. Looks like that work
was done via:

    JDK-8181917: Refactor UL LogStreams to avoid using resource area

Of course, removing the include of memory/resourceArea.hpp reveals
other code that uses ResourceMark(s), but never bothered to include
memory/resourceArea.hpp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build / test | ✔️ (0/0 passed) | ✔️ (0/0 passed) | ✔️ (0/0 passed) |

### Issue
 * [JDK-8254335](https://bugs.openjdk.java.net/browse/JDK-8254335): logging/logStream.hpp includes memory/resourceArea.hpp but doesn't need it

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/584/head:pull/584`
`$ git checkout pull/584`

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
I ran a Mach5 Tier[1-3] and all tests passed. There was a single failed
test task, but all the tests passed and the artifact upload timed out.

**Review by kimbarrett — APPROVED** [review]

**Review by iklam — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@kimbarrett and @iklam - Thanks for the reviews!

I'm merging and rebuilding now to make sure no new missing includes of
memory/resourceArea.hpp have cropped up.

**Pull request closed without merging**
