### PR TITLE
JDK-8311938: Add default cups include location for configure on AIX

### PR DESCRIPTION
**Pull request by ansteiner**
Add the default include location(/opt/freeware/include/) for cups on AIX. With this set the additional configure parameter --with-cups-include can be removed, which was needed on AIX.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311938](https://bugs.openjdk.org/browse/JDK-8311938): Add default cups include location for configure on AIX (**Enhancement** - P4)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [8894c726](https://git.openjdk.org/jdk/pull/15100/files/8894c7260e4b69f4667cda558fccfbcff9f20f57)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15100/head:pull/15100` \
`$ git checkout pull/15100`

Update a local copy of the PR: \
`$ git checkout pull/15100` \
`$ git pull https://git.openjdk.org/jdk.git pull/15100/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15100`

View PR using the GUI difftool: \
`$ git pr show -t 15100`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15100.diff">https://git.openjdk.org/jdk/pull/15100.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15100#issuecomment-1659735749)

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
I think the check for the cups default location on AIX fits better in the next section, after line 70/79 `# Are the cups headers installed in the default /usr/include location?`

But other than that, looks good to me.

**Comment by MBaesken** [comment]
Looks reasonable, but you would overwrite the with_cups setting on AIX, is this intended   (see line 50 in the same file) ?
Otherwise the COPYRIGHT year needs adjutment.

**Comment by ansteiner** [comment]
@MBaesken: Thanks for the hint about with_cups. The default cups include location will be set in case with_cups is not set only and I updated the copyright year.

**Review by MBaesken — APPROVED** [review]

**Review by RealCLanger — COMMENTED** [review]
Hm, I still think it's clearer to have the AIX default cups check in the next section after `if test "x$CUPS_FOUND" = xno; then`.
Currently,  if somebody sets both, --with-cups= and --with-cups-include, with-cups-include gets precedence. The problem is only theoretical, I guess but I'd find it better if it were:
if test "x${with_cups}" != x; then
...
elif test "x${with_cups_include}" != x; then
...
fi

and then
if test "x$CUPS_FOUND" = xno; then
  Are the cups headers installed in the default /usr/include location?
  if aix
  ...
  else
  ...
  fi
fi

**Comment by ansteiner** [comment]
> Currently, if somebody sets both, --with-cups= and --with-cups-include, with-cups-include gets precedence. The problem is only theoretical

The default for with-cups-include on AIX will be set only if --with-cups is not set. See my last commit. But I will think about your suggestion to do the check in the other section...

**Comment by MBaesken** [comment]
Moving the check down a bit into a 
`if test "x$CUPS_FOUND" = xno; then`
section might have a little benefit , it would detect cups headers on AIX at the standard location in case a bad non working path has been set with '-with-cups' or 'with-cups-include' . But I am okay with both.

**Review by RealCLanger — APPROVED** [review]
Looks good. Maybe you should also set DEFAULT_CUPS=yes, although it doesn't seem to be used anywhere.

**Review by RealCLanger — APPROVED** [review]
Nearly perfect now. 😄

**Review by TheShermanTanker — APPROVED** [review]
Looks good, sorry I missed this until now

**Pull request closed without merging**
