### PR TITLE
8285435: Show file and line in MacroAssembler::verify_oop for AArch64 and RISC-V platforms (Port from x86)

### PR DESCRIPTION
**Pull request by zhengxiaolinX**
Hi team,

Could I have a review of this patch?

This patch ports useful [JDK-8239492](https://bugs.openjdk.java.net/browse/JDK-8239492) and [JDK-8255900](https://bugs.openjdk.java.net/browse/JDK-8255900) to AArch64 and RISC-V platforms, to show exact files and lines when `verify_oop` fails. It is very useful for debugging broken oops.

Add one `__ verify_oops()` in `aarch64.ad` and `riscv.ad` to deliberately crash the VM to see the result:

Before: 
```
build/linux-aarch64-server-slowdebug/images/jdk/bin/java -XX:+VerifyOops -jar demo-0.0.1-SNAPSHOT.jar
......
#  Internal Error (/home/yunyao.zxl/jdk/src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp:2553), pid=420, tid=425
#  fatal error: DEBUG MESSAGE: verify_oop: c_rarg1: broken oop
```

After:
```
build/linux-aarch64-server-slowdebug/images/jdk/bin/java -XX:+VerifyOops -jar demo-0.0.1-SNAPSHOT.jar
...
#  Internal Error (/home/yunyao.zxl/jdk/src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp:2553), pid=420, tid=425
#  fatal error: DEBUG MESSAGE: verify_oop: c_rarg1: broken oop r1 (/home/yunyao.zxl/jdk/src/hotspot/cpu/aarch64/aarch64.ad:1907)
```

Tested AArch64 and RISC-V hotspot jtreg tier1.

Thanks,
Xiaolin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8285435](https://bugs.openjdk.java.net/browse/JDK-8285435): Show file and line in MacroAssembler::verify_oop for AArch64 and RISC-V platforms (Port from x86)

### Reviewers
 * [Nick Gasson](https://openjdk.java.net/census#ngasson) (@nick-arm - **Reviewer**)
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8359/head:pull/8359` \
`$ git checkout pull/8359`

Update a local copy of the PR: \
`$ git checkout pull/8359` \
`$ git pull https://git.openjdk.java.net/jdk pull/8359/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8359`

View PR using the GUI difftool: \
`$ git pr show -t 8359`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8359.diff">https://git.openjdk.java.net/jdk/pull/8359.diff</a>

</details>

### CODE REVIEW

**Review by nick-arm — APPROVED** [review]
Looks OK.

**Review by RealFYang — APPROVED** [review]
Looks fine.

**Comment by zhengxiaolinX** [comment]
Thank you for reviewing! @nick-arm @RealFYang 

/integrate

**Pull request closed without merging**
