### PR TITLE
8298966: Deprecate JMX Subject Delegation and the method JMXConnector.getMBeanServerConnection(Subject) for removal.

### PR DESCRIPTION
**Pull request by kevinjwalls**
Deprecate the Java Management Extension (JMX) Subject Delegation feature for removal in a future release.

Given no known usage, there is no replacement feature for JMX Subject Delegation.

CSR is https://bugs.openjdk.org/browse/JDK-8298967

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8298967](https://bugs.openjdk.org/browse/JDK-8298967) to be approved

### Issues
 * [JDK-8298966](https://bugs.openjdk.org/browse/JDK-8298966): Deprecate JMX Subject Delegation and the method JMXConnector.getMBeanServerConnection(Subject) for removal.
 * [JDK-8298967](https://bugs.openjdk.org/browse/JDK-8298967): Deprecate JMX Subject Delegation and the method JMXConnector.getMBeanServerConnection(Subject) for removal. (**CSR**)

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**)
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11880/head:pull/11880` \
`$ git checkout pull/11880`

Update a local copy of the PR: \
`$ git checkout pull/11880` \
`$ git pull https://git.openjdk.org/jdk pull/11880/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11880`

View PR using the GUI difftool: \
`$ git pr show -t 11880`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11880.diff">https://git.openjdk.org/jdk/pull/11880.diff</a>

</details>

### CODE REVIEW

**Comment by kevinjwalls** [comment]
Updated to sync deprecation text in JMXConnector.java with the updated text in the CSR.

**Comment by kevinjwalls** [comment]
CSR approved.

**Review by mlchung — APPROVED** [review]

**Review by dfuch — APPROVED** [review]

**Comment by kevinjwalls** [comment]
Thanks Mandy and Daniel!

**Pull request closed without merging**
