### PR TITLE
8257845: Integrate JEP 390

### PR DESCRIPTION
**Pull request by dansmithcode**
Integration of [JEP 390](https://bugs.openjdk.java.net/browse/JDK-8249100).

Development has been broken into 5 tasks, each with its own JBS issue:
- [JDK-8252180](https://bugs.openjdk.java.net/browse/JDK-8252180): Deprecate wrapper class constructors for removal (rriggs)
- [JDK-8254047](https://bugs.openjdk.java.net/browse/JDK-8254047): Revise "value-based class" & apply to wrappers (dlsmith)
- [JDK-8252181](https://bugs.openjdk.java.net/browse/JDK-8252181):Define & apply annotation jdk.internal.ValueBased (rriggs)
- [JDK-8252183](https://bugs.openjdk.java.net/browse/JDK-8252183): Add 'lint' warning for @ValueBased classes (sadayapalam)
- [JDK-8257027](https://bugs.openjdk.java.net/browse/JDK-8257027): Diagnose synchronization on @ValueBased classes (lfoltan)

All changes have been previously reviewed and integrated into the [`jep390` branch](https://github.com/openjdk/valhalla/tree/jep390) of the `valhalla` repository. See the subtasks of the 5 JBS issues for these changes, including discussion and links to reviews. (Reviewers: mchung, dlsmith, jlaskey, rriggs, lfoltan, fparain, hseigel.)

CSRs have also been completed or are nearly complete:

- [JDK-8254324](https://bugs.openjdk.java.net/browse/JDK-8254324) for wrapper class constructor deprecation
- [JDK-8254944](https://bugs.openjdk.java.net/browse/JDK-8254944) for revisions to "value-based class"
- [JDK-8256023](https://bugs.openjdk.java.net/browse/JDK-8256023) for new `javac` lint warnings

Here's an overview of the files changed:

- `src/hotspot`: implementing diagnostics when `monitorenter` is applied to an instance of a class tagged with `jdk.internal.ValueBased`. This enhances previous work that produced such diagnostics for the primitive wrapper classes.

- `src/java.base/share/classes/java/lang`: deprecating for removal the wrapper class constructors; revising the definition of "value-based class" in `ValueBased.html` and the description used by linking classes; applying "value-based class" to the primitive wrapper classes; marking value-based classes with `@jdk.internal.ValueBased`.

- `src/java.base/share/classes/java/lang/constant`: no longer designating these classes as "value-based", since they rely heavily on field inheritance.

- `src/java.base/share/classes/java/time`: revising the description used to link to `ValueBased.html`; marking value-based classes with `@jdk.internal.ValueBased`.

- `src/java.base/share/classes/java/util`: revising the description used to link to `ValueBased.html`; marking value-based classes with `@jdk.internal.ValueBased`.

- `src/java.base/share/classes/jdk/internal`: define the `@jdk.internal.ValueBased` annotation.

- `src/java.management.rmi`: removing uses of wrapper class constructors.

- `src/java.xml`: removing uses of wrapper class constructors.

- `src/jdk.compiler`: implementing the `synchronization` lint category, which reports attempts to synchronize on classes and interfaces annotated with `@jdk.internal.ValueBased`.

- `src/jdk.incubator.foreign`: revising the description used to link to `ValueBased.html`. (Applying `@jdk.internal.ValueBased` would require a special module export, which was not deemed necessary for an incubating API.)

- `src/jdk.internal.vm.compiler`: suppressing `javac` deprecation and synchronization warnings in tests

- `src/jdk.jfr`: supplementary changes for HotSpot diagnostics

- `test`: testing new `javac` and HotSpot behavior; removing usages of deprecated wrapper class constructors from tests, or suppressing deprecation warnings; revising the description used to link to `ValueBased.html`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8257845](https://bugs.openjdk.java.net/browse/JDK-8257845): Integrate JEP 390
 * [JDK-8254047](https://bugs.openjdk.java.net/browse/JDK-8254047): [JEP 390] Revise "value-based class" & apply to wrappers
 * [JDK-8252181](https://bugs.openjdk.java.net/browse/JDK-8252181): [JEP 390] Define & apply annotation jdk.internal.ValueBased
 * [JDK-8252183](https://bugs.openjdk.java.net/browse/JDK-8252183): [JEP 390] Add 'lint' warning for @ValueBased classes
 * [JDK-8257027](https://bugs.openjdk.java.net/browse/JDK-8257027): [JEP 390] Diagnose synchronization on @ValueBased classes
 * [JDK-8252180](https://bugs.openjdk.java.net/browse/JDK-8252180): [JEP 390] Deprecate wrapper class constructors for removal

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**)
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)

### Contributors
 * Roger Riggs `<rriggs@openjdk.org>`
 * Srikanth Adayapalam `<sadayapalam@openjdk.org>`
 * Lois Foltan `<lfoltan@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1636/head:pull/1636`
`$ git checkout pull/1636`

### CODE REVIEW

**Comment by dansmithcode** [comment]
I've updated the description to provide an overview for those unfamiliar with this work. Reviewers are welcome, including those who have previously reviewed a subset of these changes.

**Review by RogerRiggs — APPROVED** [review]
For the core libraries parts looks ok.

**Review by hseigel — APPROVED** [review]
The hotspot changes look good.  In a future change, could you add additional classes, such as ProcessHandle to test TestSyncOnValueBasedClassEvent.  Currently, it only tests primitive classes.

**Comment by lfoltan** [comment]
@hseigel thank you for the review.  I have created https://bugs.openjdk.java.net/browse/JDK-8257836 as an RFE to address additional testing.
Lois

**Review by mlchung — APPROVED** [review]
core-libs and hotspot change look okay.

**Review by jddarcy — APPROVED** [review]

**Pull request closed without merging**
