### PR TITLE
8327425: String Template FMT Refactor use call direct instead of MethodHandle

### PR DESCRIPTION
**Pull request by wenshao**
Currently FormatItem uses MethodHandler to handle latin1 and utf16, which is not readable. This PR uses direct calls instead of MethodHandle.

Please review and don't hesitate to critique my approach and patch.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327425](https://bugs.openjdk.org/browse/JDK-8327425): String Template FMT Refactor use call direct instead of MethodHandle (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16021/head:pull/16021` \
`$ git checkout pull/16021`

Update a local copy of the PR: \
`$ git checkout pull/16021` \
`$ git pull https://git.openjdk.org/jdk.git pull/16021/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16021`

View PR using the GUI difftool: \
`$ git pr show -t 16021`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16021.diff">https://git.openjdk.org/jdk/pull/16021.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16021#issuecomment-1980047905)

### CODE REVIEW

**Comment by wenshao** [comment]
label remove security

**Comment by ExE-Boss** [comment]
It’s `MethodHandle`, not `MethodHandler`.

**Pull request closed without merging**
