### PR TITLE
8298240: Replace the usage of ImageLayoutException by the CMMException

### PR DESCRIPTION
**Pull request by mrserb**
ImageLayoutException is used to report any issues with image layout calculation. But since we cannot throw the unspecified exception to the application, all usages of ImageLayoutException are wrapped by the CMMException. And now if such CMMException occurs we have lost at what point the initial exception was raised.

We can pass some additional data around, but it looks like we can just delete the ImageLayoutException and use CMMException instead. 

Additionally:
 * The `public` keyword is removed in a few places if not needed.
 * The PT_XX flags are updated to make it clearly visible how they are related.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298240](https://bugs.openjdk.org/browse/JDK-8298240): Replace the usage of ImageLayoutException by the CMMException

### Reviewers
 * @SWinxy (no known github.com user name / role) ⚠️ Review applies to [146b1c36](https://git.openjdk.org/jdk/pull/11552/files/146b1c36e9c72a1e4bc6c52e3e69604e1b4b77ee)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11552/head:pull/11552` \
`$ git checkout pull/11552`

Update a local copy of the PR: \
`$ git checkout pull/11552` \
`$ git pull https://git.openjdk.org/jdk pull/11552/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11552`

View PR using the GUI difftool: \
`$ git pr show -t 11552`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11552.diff">https://git.openjdk.org/jdk/pull/11552.diff</a>

</details>

### CODE REVIEW

**Review by SWinxy — APPROVED** [review]
In another PR, CMMException should have its documentation updated. It currently says `This exception is thrown if the native CMM returns an error.` But we are also throwing it with checks in Java.

**Comment by mrserb** [comment]
> In another PR, CMMException should have its documentation updated. It currently says `This exception is thrown if the native CMM returns an error.` But we are also throwing it with checks in Java.

We throw it from the "glue code" of the native library, it could be considered to be part of the native CMM engine.

**Review by prrace — APPROVED** [review]
Seems reasonable to me.

**Pull request closed without merging**
