### PR TITLE
8265411: Avoid unnecessary Method::init_intrinsic_id calls

### PR DESCRIPTION
**Pull request by iklam**
`check_methods_for_intrinsics()` in classFileParser.cpp calls `Method::klass_id_for_intrinsics()` to see if a class has intrinsic methods. However, the latter returns any class whose name is included in `vmSymbols`. This causes many unnecessary calls to `Method::init_intrinsic_id()`.

To fix this, we precompute the classes that are known to have intrinsics using `constexpr`. See `vmIntrinsics::class_has_intrinsics`.

After the fix, when running `java -Xshare:off -version`, the number of classes initialized for intrinsics is reduced from 130 to 30.

Testing: mach5 tiers 1~4 passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265411](https://bugs.openjdk.java.net/browse/JDK-8265411): Avoid unnecessary Method::init_intrinsic_id calls

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to eb8e0bf693cdce260ac17ae83136aae00da1257e
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**) ⚠️ Review applies to eb8e0bf693cdce260ac17ae83136aae00da1257e

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3564/head:pull/3564` \
`$ git checkout pull/3564`

Update a local copy of the PR: \
`$ git checkout pull/3564` \
`$ git pull https://git.openjdk.java.net/jdk pull/3564/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3564`

View PR using the GUI difftool: \
`$ git pr show -t 3564`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3564.diff">https://git.openjdk.java.net/jdk/pull/3564.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Ioi,

That all appears fine to me.

Is there any startup impact?

Thanks,
David

**Comment by iklam** [comment]
> Hi Ioi,
> 
> That all appears fine to me.
> 
> Is there any startup impact?
> 
> Thanks,
> David

Hi David, when CDS is turned off, I can see a small improvement in start-up, due to the reduction in intrinsic ID lookup:

```
$ perf stat -r 100 bin/java -Xshare:off -Xint -version

OLD: 191,632,128 cycles 0.074624 sec
NEW: 191,387,603 cycles 0.073704 sec
```

With CDS enabled, the intrinsic ID lookup is done during archive dump time, so this PR makes no difference.

Also, the lookup table itself is generated during C++ compilation, so it has no runtime impact:

```
	.section	.rodata
	.type	_ZL18_intrinsics_lookup, @object
_ZL18_intrinsics_lookup:
	.byte	0
	.byte	0
	.byte	1
	.byte	1
        ....
```

**Review by yminqi — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by yminqi** [comment]
BTW, the the fix works for the problem: adding symbols to vmSymbols.hpp caused debug build failed due this bug.

**Comment by iklam** [comment]
Thanks @dholmes-ora and @yminqi for the review!
/integrate

**Pull request closed without merging**
