### PR TITLE
8258682: compiler/intrinsics/mathexact/sanity tests fail with RepeatCompilation

### PR DESCRIPTION
**Pull request by robcasloz**
Normalize match and suspect counts in the `verify()` method by the number of compilation repetitions, if the `RepeatCompilation` option is used.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258682](https://bugs.openjdk.java.net/browse/JDK-8258682): compiler/intrinsics/mathexact/sanity tests fail with RepeatCompilation

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1840/head:pull/1840`
`$ git checkout pull/1840`

### CODE REVIEW

**Comment by robcasloz** [comment]
/summary
Normalize match and suspect counts in the verify() method by the number of
compilation repetitions, if the RepeatCompilation option is used.

**Comment by robcasloz** [comment]
Tested by running all `compiler/intrinsics` tests, with and without `-XX:+UnlockDiagnosticVMOptions -XX:RepeatCompilation=42`, on windows-x64, linux-x64, linux-aarch64, and macosx-x64 (both debug and release).

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks for reviewing, Vladimir!

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by robcasloz** [comment]
> Looks good!

Thanks Christian!

**Comment by robcasloz** [comment]
/integrate
This change is ready for integration, please sponsor.

**Pull request closed without merging**
