### PR TITLE
8333647: C2 SuperWord: some additional PopulateIndex tests

### PR DESCRIPTION
**Pull request by eme64**
When I did the deep refactoring in https://github.com/openjdk/jdk/pull/19261, I wanted some more tests for `PopulateIndex`. I push them separately to keep the other RFE smaller.

I filed a follow-up RFE for some cases that do not vectorize: https://bugs.openjdk.org/browse/JDK-8332878

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333647](https://bugs.openjdk.org/browse/JDK-8333647): C2 SuperWord: some additional PopulateIndex tests (**Sub-task** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19558/head:pull/19558` \
`$ git checkout pull/19558`

Update a local copy of the PR: \
`$ git checkout pull/19558` \
`$ git pull https://git.openjdk.org/jdk.git pull/19558/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19558`

View PR using the GUI difftool: \
`$ git pr show -t 19558`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19558.diff">https://git.openjdk.org/jdk/pull/19558.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19558#issuecomment-2149873523)

### CODE REVIEW

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Add Oracle's copyright line to these files.

**Comment by eme64** [comment]
> Add Oracle's copyright line to these files.

Nice catch, fixed!

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by eme64** [comment]
Thanks @vnkozlov @chhagedorn for the reviews!
@vnkozlov said I can integrate before the fork, since this is only test changes. I'll do that.
/integrate

**Pull request closed without merging**
