### PR TITLE
8273430: Suspicious duplicate condition in java.util.regex.Grapheme#isExcludedSpacingMark

### PR DESCRIPTION
**Pull request by igraves**
The duplicate condition in this chain of expressions needs to be shrunk to drop a couple of character that are not excluded spacing marks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273430](https://bugs.openjdk.java.net/browse/JDK-8273430): Suspicious duplicate condition in java.util.regex.Grapheme#isExcludedSpacingMark

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5425/head:pull/5425` \
`$ git checkout pull/5425`

Update a local copy of the PR: \
`$ git checkout pull/5425` \
`$ git pull https://git.openjdk.java.net/jdk pull/5425/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5425`

View PR using the GUI difftool: \
`$ git pr show -t 5425`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5425.diff">https://git.openjdk.java.net/jdk/pull/5425.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]
The copyright year in Grapheme.java should be 2021, otherwise looks good.

**Comment by igraves** [comment]
Updating the tests here. Existing ones included code copy/pasted directly from the unit under test. Refactored to a whitebox-style testing that injects accessors into `java.util.regex` so we don't have to modify code in two places to keep it in sync. Also relaxed two private static methods in `java.util.regex.Grapheme` to package-private so the injected accessor class can reach them and expose them for the test.

**Review by naotoj — APPROVED** [review]
Looks good. Nice cleanup!

**Pull request closed without merging**
