### PR TITLE
8324880: Rename get_stack_trace.h

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this trivial change that renames the file
test/hotspot/jtreg/serviceability/jvmti/thread/GetStackTrace/get_stack_trace.h
to get_stack_trace.hpp, and renames uses of NULL in that file.

The updates to #include lines in using files were performed mechanically.

Testing: mach5 tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324880](https://bugs.openjdk.org/browse/JDK-8324880): Rename get_stack_trace.h (**Sub-task** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17623/head:pull/17623` \
`$ git checkout pull/17623`

Update a local copy of the PR: \
`$ git checkout pull/17623` \
`$ git pull https://git.openjdk.org/jdk.git pull/17623/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17623`

View PR using the GUI difftool: \
`$ git pr show -t 17623`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17623.diff">https://git.openjdk.org/jdk/pull/17623.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17623#issuecomment-1916022560)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
LGTM! Thanks

**Review by TheShermanTanker — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thank you for taking care about this!

**Comment by kimbarrett** [comment]
Thanks for reviews, @dholmes-ora , @TheShermanTanker , and @sspitsyn .

**Pull request closed without merging**
