### PR TITLE
8298380: Clean up redundant array length checks in JDK code base

### PR DESCRIPTION
**Pull request by stsypanov**
Newer version of IntelliJ IDEA introduces new [inspection](https://youtrack.jetbrains.com/issue/IDEA-301797/IDEA-should-report-redundant-array-length-check-in-certain-cases) detecting redundant array length check in snippets like
```java
<T> void iterate(T[] items) {
  if (items.length == 0) {
    return;
  }
  for (T item : items) {
    //...
  }
}
```
Here
```java
if (items.length == 0) {
  return;
}
```
is redundant and can be removed as length check is performed by for-each loop.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298380](https://bugs.openjdk.org/browse/JDK-8298380): Clean up redundant array length checks in JDK code base

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Alex Menkov](https://openjdk.org/census#amenkov) (@alexmenkov - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)
 * [Vyom Tewari](https://openjdk.org/census#vtewari) (@vyommani - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11589/head:pull/11589` \
`$ git checkout pull/11589`

Update a local copy of the PR: \
`$ git checkout pull/11589` \
`$ git pull https://git.openjdk.org/jdk pull/11589/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11589`

View PR using the GUI difftool: \
`$ git pr show -t 11589`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11589.diff">https://git.openjdk.org/jdk/pull/11589.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
These all seem fine to me.

You can count this as the review for hotspot and serviceability. :)

**Review by alexmenkov — APPROVED** [review]

**Review by mrserb — APPROVED** [review]
The "client" changes in src/java.desktop looks fine

**Review by vyommani — APPROVED** [review]
java.base changes looks ok to me.

**Comment by RogerRiggs** [comment]
@stsypanov , @TheShermanTanker You jumped the gun a bit on the integration and sponsoring. There was no approval for the core-libs parts from a "R"eviewer.

**Comment by stsypanov** [comment]
@RogerRiggs changes are trivial. Should I revert any of them?

**Comment by RogerRiggs** [comment]
No, just a reminder to be through in the process.

**Pull request closed without merging**
