### PR TITLE
JDK-8307810: Consistently use LockingMode instead of UseHeavyMonitors

### PR DESCRIPTION
**Pull request by tstuefe**
[JDK-8291555](https://bugs.openjdk.org/browse/JDK-8291555) phased out UseHeavyMonitors in favor of LockingMode=0. We forgot to apply these changes to PPC and S390. 

Since UseHeavyMonitors implies LockingMode, but not vice versa, we now have a mismatch if JVM is started with LockingMode=0 but without UseHeavyMonitors. That leads to crashes.

The patch fixes that, and in addition makes sure that if LockingMode=0 is set, we are setting UseHeavyMonitors too.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307810](https://bugs.openjdk.org/browse/JDK-8307810): Consistently use LockingMode instead of UseHeavyMonitors

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13900/head:pull/13900` \
`$ git checkout pull/13900`

Update a local copy of the PR: \
`$ git checkout pull/13900` \
`$ git pull https://git.openjdk.org/jdk.git pull/13900/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13900`

View PR using the GUI difftool: \
`$ git pr show -t 13900`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13900.diff">https://git.openjdk.org/jdk/pull/13900.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13900#issuecomment-1542016974)

### CODE REVIEW

**Comment by tstuefe** [comment]
@MBaesken @TheRealMDoerr could you test this please on your CI and check if this fixes ppcle and s390? Thanks!

**Comment by MBaesken** [comment]
> @MBaesken @TheRealMDoerr could you test this please on your CI and check if this fixes ppcle and s390? Thanks!

I put it into our internal  test queue .

**Comment by offamitkumar** [comment]
Hi @tstuefe, Not sure how correct I am, but UseHeavyMonitors is not implemented for s390x, You may see an Issue open for this [here](https://bugs.openjdk.org/browse/JDK-8278411). So i guess if you set UseHeavyMonitors to true for s390x, then build will fail.

>Looks like the build fails now in arguments.cpp on a few platforms.

@MBaesken does that include s390x ?

**Comment by tstuefe** [comment]
Okay, I removed the setting-of-UseHeavyMonitors. We deprecated it in favour of LockingMode=0, and it is a develop flag now. I originally wanted to synchronize UseHeavyMonitors with LockingMode, but doing this only for debug makes no sense, and in release builds UseHeavyMonitors is const false.

**Comment by MBaesken** [comment]
> @MBaesken does that include s390x ?

I referred to the github action builds above. I think there was no linux s390x build included in those.

**Review by dcubed-ojdk — APPROVED** [review]
Sorry we missed finding the rest of the UseHeavyMonitors uses
during the work on JDK-8291555.

Switching those uses to the appropriate check of LockingMode is the
right solution. We want UseHeavyMonitors to fade into the sands of
history...

**Review by TheRealMDoerr — APPROVED** [review]
Thank you for fixing this! Works on PPC64 and avoids "assert(mark.is_neutral()) failed" when -XX:LockingMode=0 is selected.
@offamitkumar: I think s390 requires additional changes in `MacroAssembler::compiler_fast_lock_object` and `MacroAssembler::compiler_fast_unlock_object`, but that should probably better be done separately.

**Review by offamitkumar — APPROVED** [review]
Build/Tests are good on s390x, 

Thanks for the changes :-)

**Comment by offamitkumar** [comment]
>@offamitkumar: I think s390 requires additional changes in MacroAssembler::compiler_fast_lock_object and MacroAssembler::compiler_fast_unlock_object, but that should probably better be done separately.

Sure Martin, I'll look into. 

Thank you.

**Comment by tstuefe** [comment]
Thanks @offamitkumar @TheRealMDoerr @dholmes-ora @dcubed-ojdk !

/integrate

**Pull request closed without merging**
