### PR TITLE
8342489: compiler/c2/irTests/TestVectorizationMismatchedAccess.java fails on big-endian platforms

### PR DESCRIPTION
**Pull request by offamitkumar**
Adjust TestVectorizationMismatchedAccess.java for Big Endian Platforms

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342489](https://bugs.openjdk.org/browse/JDK-8342489): compiler/c2/irTests/TestVectorizationMismatchedAccess.java fails on big-endian platforms (**Bug** - P4)

### Reviewers
 * [Emanuel Peter](https://openjdk.org/census#epeter) (@eme64 - **Reviewer**)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21736/head:pull/21736` \
`$ git checkout pull/21736`

Update a local copy of the PR: \
`$ git checkout pull/21736` \
`$ git pull https://git.openjdk.org/jdk.git pull/21736/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21736`

View PR using the GUI difftool: \
`$ git pr show -t 21736`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21736.diff">https://git.openjdk.org/jdk/pull/21736.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21736#issuecomment-2441311910)

### CODE REVIEW

**Comment by offamitkumar** [comment]
@MBaesken  can you test it once ? It passes on s390x now.

**Comment by MBaesken** [comment]
please remove the exclusion too (from https://bugs.openjdk.org/browse/JDK-8343055) ; I put this then into our nightly build/test queue and tell you afterwards if all is fine .

**Review by eme64 — APPROVED** [review]
@offamitkumar Thanks for the fix, this looks good to me.

@rwestrel You originally wrote this test, I then added more cases. Do you also agree with this fix?

**Review by eme64 — CHANGES_REQUESTED** [review]
Ah yes, you need to undo this [PR's](https://github.com/openjdk/jdk/pull/21708) change, as asked for above.

**Review by MBaesken — APPROVED** [review]

**Comment by MBaesken** [comment]
Fixes the error on AIX.

**Comment by offamitkumar** [comment]
@eme64, @rwestrel can I get one more approval ?

**Review by eme64 — APPROVED** [review]

**Comment by offamitkumar** [comment]
Thanks @MBaesken @eme64 for testing & approval. 
/integrate

**Pull request closed without merging**
