### PR TITLE
JDK-8292073: NMT: remove unused constructor parameter from MallocHeader

### PR DESCRIPTION
**Pull request by tstuefe**
Trivial change to remove an unused parameter from the constructor of MallocHeader

(Requires JDK-8292073)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292073](https://bugs.openjdk.org/browse/JDK-8292073): NMT: remove unused constructor parameter from MallocHeader

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9802/head:pull/9802` \
`$ git checkout pull/9802`

Update a local copy of the PR: \
`$ git checkout pull/9802` \
`$ git pull https://git.openjdk.org/jdk pull/9802/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9802`

View PR using the GUI difftool: \
`$ git pr show -t 9802`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9802.diff">https://git.openjdk.org/jdk/pull/9802.diff</a>

</details>

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
LGTM.
Thanks for factoring out MallocHeader. Looks significantly cleaner now.

**Review by RealLucy — CHANGES_REQUESTED** [review]
Except for the removed parameter, this PR contains all the changes that come with #9801. 
Why this duplication?

**Comment by tstuefe** [comment]
> Except for the removed parameter, this PR contains all the changes that come with #9801. Why this duplication?

This PR builds on #9801. Sorry for the confusion.

**Comment by RealLucy** [comment]
> This PR builds on #9801. 

Ah I see. I don't like it that much, but for now it's ok.

**Review by RealLucy — APPROVED** [review]
With the give explanation: LGTM:

**Comment by tstuefe** [comment]
> Trivial change to remove an unused parameter from the constructor of MallocHeader
> 
> (Requires JDK-8292073)
> 
> ### Progress
> * [x]  Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
> * [x]  Change must not contain extraneous whitespace
> * [x]  Commit message must refer to an issue
> 
> ### Issue
> * [JDK-8292073](https://bugs.openjdk.org/browse/JDK-8292073): NMT: remove unused constructor parameter from MallocHeader
> 
> ### Reviewers
> * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)
> 
> ### Reviewing
> Using `git`
> Using Skara CLI tools
> Using diff file

**Pull request closed without merging**
