### PR TITLE
8316229: Enhance class initialization logging

### PR DESCRIPTION
**Pull request by dholmes-ora**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316229](https://bugs.openjdk.org/browse/JDK-8316229): Enhance class initialization logging (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15732/head:pull/15732` \
`$ git checkout pull/15732`

Update a local copy of the PR: \
`$ git checkout pull/15732` \
`$ git pull https://git.openjdk.org/jdk.git pull/15732/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15732`

View PR using the GUI difftool: \
`$ git pr show -t 15732`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15732.diff">https://git.openjdk.org/jdk/pull/15732.diff</a>

</details>

### CODE REVIEW

**Comment by olamy** [comment]
Thanks, I will test this with Jetty issue we have.
same flags  `-Xlog:class+init=debug -Xlog:exceptions=debug` or you need more?

**Comment by olamy** [comment]
here you go the logs.
Hope that help!
[jvm.log](https://github.com/openjdk/jdk/files/12605095/jvm.log)

**Comment by olamy** [comment]
sorry mistake on logs file
I re attached
[jvm.log](https://github.com/openjdk/jdk/files/12613020/jvm.log)

**Comment by olamy** [comment]
one more 
[jvm.log](https://github.com/openjdk/jdk/files/12614376/jvm.log)

**Comment by dholmes-ora** [comment]
@olamy thanks for the logs. The new logging was enough to show both which threads are deadlocking and why, and just enough to figure out that we are blocking trying to ensure the superclass/interface is initialized, prior to clinit execution, hence why nothing was evident in the logs.

**Comment by olamy** [comment]
@dholmes-ora Great news! Let us know when you have some fix ready, and we will be happy to test it. Thanks

**Comment by dholmes-ora** [comment]
@olamy a fix for what exactly? This PR will add more logging to show the problem, but the underlying issue is in the library/application code.

**Comment by sbordet** [comment]
@dholmes-ora, the reason we were thinking about a fix is that we have valid Java code that can deadlock class initialization, and this does not seem optimal.

Other class initialization gotchas are known Java puzzlers that lead to `NullPointerException` or `ClassInitializationError`, but at least these hint at what's wrong with the exception and don't deadlock the JVM.

We did not see this problem until Java 21, so thought this problem to be a regression in Java 21.

We will work around the problem in our code, but wanted to report the JVM deadlock as something that might be unexpected new behavior in Java 21.

Thanks!

**Comment by jaikiran** [comment]
Hello Simone,

> We did not see this problem until Java 21, so thought this problem to be a regression in Java 21.

> We will work around the problem in our code, but wanted to report the JVM deadlock as something that might be unexpected new behavior in Java 21.

Having looked at that class hierarchy I think this issue should be reproduced in older JDKs too, when multiple threads are involved. Are you sure the class initialization sequence and the number of threads involved when testing this with older JDKs hasn't changed? Perhaps you could use `-verbose:class` both in older and this patched JDK (along with these above logs) to get hold of the loading logs and compare them to see if there's some difference?

**Comment by joakime** [comment]
Hello Jaikiran,

This codebase (The `jetty-12.0.x` branch), is built (build from scratch + unit testing + integration testing) on our CI against Java 17 and Java 21. (a matrix build)

Eg: 
* https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/1540/pipeline (green build)
* https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/1535/pipeline (lockup build)

This means every branch from `jetty-12.0.x`, all PRs, and close to every commit as well.
The `jetty-12.0.x` branch has 1540 builds so far, and has had 2379 merges into it.
So including builds of branches from jetty-12.0.x, and PRs.
We should be well over 5000 builds with this codebase on Jetty 17.
We switched from jdk19 to jdk21 as our "other jdk" build on July 28.

So that means 5000-ish builds on JDK 17, with no issues related to JVM lockup.
About 3710 builds on JDK 19, with no issues related to JVM lockup.
And finally about  272 builds on JDK 21, with 33 JVM lockups.

And these are just the numbers from our CI.
From our point of view this JVM lockup is new and unique to JDK 21.

**Comment by jaikiran** [comment]
Hello Joakim,

Thank you for those additional details.

> And these are just the numbers from our CI.
> From our point of view this JVM lockup is new and unique to JDK 21.

I am not denying that you are seeing an issue with class initialization only in Java 21. What I was looking for was some (debug) data which would help us understand why/how Java 21 "woke up" an issue with that class hierarchy. Usage of `-verbose:class` and comparing that result between the JDK versions is just a start to trying to get that data to try and narrow it down.

Initial analysis which David explained through those logs so far hasn't suggested a JDK issue - this case where threads can deadlock while doing static initialization of "cyclic" class usages is a known thing (I haven't checked if it is documented anywhere) and isn't specific to Java 21.

If this is something that can be reproduced in a simpler application with specific steps, that would help too.

**Comment by jaikiran** [comment]
> https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/1535/pipeline (lockup build)
> 
> [INFO] EE9 :: Utility Servlets and Filters ................ FAILURE [  02:36 h]

Does it always happen with the tests in `jetty.project/jetty-ee9/jetty-ee9-servlets` Maven module?

**Comment by dholmes-ora** [comment]
It is a fragile design where initialization of a supertype depends on initialization of its own subtypes. That is setting things up for class initialization deadlock, unless the only "entry path" is via initialization of the supertype. As soon as you have code that starts initialization from a subtype - as your HttpTester.Message does - then deadlock is just a matter of threads and timing.

That said, there may have been a change in JDK 21 that exposed this, or made it more likely. I will look into that. It should be easy enough to create a simpler reproducer using the pattern shown in the Jetty code.

**Comment by dholmes-ora** [comment]
It seems likely that [8288064: Class initialization locking](https://bugs.openjdk.org/browse/JDK-8288064), fixed in JDK 20, led to the change in timing that exposed this deadlock, but I cannot see anything functionally wrong it.

**Comment by dholmes-ora** [comment]
I'm going to close this PR and create a new one when I'm ready to integrate the logging changes.

But I have filed  a new issue (that I expect to close as "Not an Issue") so that we can record the discussion etc. https://bugs.openjdk.org/browse/JDK-8316469

PS. I see now the problem did not reproduce with JDK 20 so JDK-8288064 is not the cause, at least not in its own.

**Pull request closed without merging**
