### PR TITLE
8303553: AArch64: Add BCAX backend rule

### PR DESCRIPTION
**Pull request by changpeng1997**
We can use BCAX [1] [2] to merge a bit clear and an exclusive-OR operation. For example, on a 128-bit aarch64 machine which supports NEON and SHA3, following instruction sequence:

```
...
bic     v16.16b, v16.16b, v17.16b
eor     v16.16b, v16.16b, v18.16b
...
```

can be optimized to:

```
...
bcax    v16.16b, v17.16b, v16.16b, v18.16b
...
```

This patch adds backend rules for BCAX, and we can gain almost 10% performance lift on a 128-bit aarch64 machine which supports NEON and SHA3. Similar performance uplift can also be observed on SVE2.

Performance_Before:

```
Benchmark                 Score(op/ms)     Error
TestByte#size(2048)       9779.361         47.184
TestInt#size(2048)        3028.617         7.292
TestLong#size(2048)       1331.216         1.815
TestShort#size(2048)      5828.089         8.975
```

Performance_BCAX_NEON:

```
Benchmark                 Score(op/ms)     Error
TestByte#size(2048)       10510.371        34.931
TestInt#size(2048)        3437.512         81.318
TestLong#size(2048)       1461.023         0.679
TestShort#size(2048)      6238.210         26.452
```

[1]: https://developer.arm.com/documentation/ddi0596/2021-12/SIMD-FP-Instructions/BCAX--Bit-Clear-and-XOR-
[2]: https://developer.arm.com/documentation/ddi0602/2022-12/SVE-Instructions/BCAX--Bitwise-clear-and-exclusive-OR-?lang=en

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303553](https://bugs.openjdk.org/browse/JDK-8303553): AArch64: Add BCAX backend rule

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13222/head:pull/13222` \
`$ git checkout pull/13222`

Update a local copy of the PR: \
`$ git checkout pull/13222` \
`$ git pull https://git.openjdk.org/jdk.git pull/13222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13222`

View PR using the GUI difftool: \
`$ git pr show -t 13222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13222.diff">https://git.openjdk.org/jdk/pull/13222.diff</a>

</details>

### CODE REVIEW

**Comment by theRealAph** [comment]
Do we have any reason to believe that this instruction will ever be matched in a Java application? If not, it's just slowing down compilation for no good reason.

**Comment by changpeng1997** [comment]
> Do we have any reason to believe that this instruction will ever be matched in a Java application? If not, it's just slowing down compilation for no good reason.

Hello.

This computing pattern (a ^ (b & (~c))) can be found in some SHA-3 java implementation, like https://github.com/aelstad/keccakj/blob/07185d29fb6c881570e2d7fd2b160460626dc130/src/main/java/com/github/aelstad/keccakj/core/Keccak1600.java#L309.

I believe this patch can accelerate some SHA-3 applications implemented by Java.

**Comment by theRealAph** [comment]
> This computing pattern (a ^ (b & (~c))) can be found in some SHA-3 java implementation, like https://github.com/aelstad/keccakj/blob/07185d29fb6c881570e2d7fd2b160460626dc130/src/main/java/com/github/aelstad/keccakj/core/Keccak1600.java#L309.
> 
> I believe this patch can accelerate some SHA-3 applications implemented by Java.

OK, thanks. Please benchmark this and let us know the result. It'd also be interesting to know how it compares with our SHA-3 intrinsic.

**Comment by merykitty** [comment]
We have `MacroLogicVNode` in the middle-end, can it be used to leverage the ternary logical instructions of SVE2 by selectively creating the node if the truth table is supported? Thanks a lot.

**Comment by changpeng1997** [comment]
> We have `MacroLogicVNode` in the middle-end, can it be used to leverage the ternary logical instructions of SVE2 by selectively creating the node if the truth table is supported? Thanks a lot.

Hi. I found that there were only two ternary instructions in SVE2 (BCAX, EOR3).
Maybe we need not leverage them in the middle-end by using MacroLogicVNode.

**Comment by changpeng1997** [comment]
> > This computing pattern (a ^ (b & (~c))) can be found in some SHA-3 java implementation, like https://github.com/aelstad/keccakj/blob/07185d29fb6c881570e2d7fd2b160460626dc130/src/main/java/com/github/aelstad/keccakj/core/Keccak1600.java#L309.
> > I believe this patch can accelerate some SHA-3 applications implemented by Java.
> 
> OK, thanks. Please benchmark this and let us know the result. It'd also be interesting to know how it compares with our SHA-3 intrinsic.

I have run the SHA-3 benchmark [1] [2] and I found BCAX instruction cannot be generated since SLP failed to vectorize these code. I tend to agree with you. 
In addition, SHA-3 intrinsic has been removed so we cannot compare with it.

[1]: https://github.com/openjdk/jdk/blob/master/test/micro/org/openjdk/bench/java/security/MessageDigests.java
[2]: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/provider/SHA3.java

**Comment by changpeng1997** [comment]
> `bsl(dst, src2, src3) == (dst & src3) | (src2 & ~src3)` which is a bitwise logical operation

@merykitty Sorry, these instructions are logical-operation instructions indeed.

**Comment by theRealAph** [comment]
> In addition, SHA-3 intrinsic has been removed so we cannot compare with it.

When was it removed?

**Comment by changpeng1997** [comment]
> > In addition, SHA-3 intrinsic has been removed so we cannot compare with it.
> 
> When was it removed?

Sorry, it was disabled.

**Comment by theRealAph** [comment]
> > > In addition, SHA-3 intrinsic has been removed so we cannot compare with it.
> > 
> > 
> > When was it removed?
> 
> Sorry, it was disabled on AArch64 except Apple. #11382

OK, so it seems that adding a BCAX rule is not necessary for the AArch64 port of HotSpot.

In summary:
BCAX was added to the instruction set for SHA-3, but it doesn't help much even in a hand-coded intrinsic. There is no significant performance advantage to be gained from this patch, and it adds a burden. I suggest that you should withdraw it. Thanks.

**Comment by changpeng1997** [comment]
> > > > In addition, SHA-3 intrinsic has been removed so we cannot compare with it.
> > > 
> > > 
> > > When was it removed?
> > 
> > 
> > Sorry, it was disabled on AArch64 except Apple. #11382
> 
> OK, so it seems that adding a BCAX rule is not necessary for the AArch64 port of HotSpot.
> 
> In summary: BCAX was added to the instruction set for SHA-3, but it doesn't help much even in a hand-coded intrinsic. There is no significant performance advantage to be gained from this patch, and it adds a burden. I suggest that you should withdraw it. Thanks.

Ok. Thanks for your review.

**Pull request closed without merging**
