### PR TITLE
8267376: C2: Deduce the result bound of ModXNode

### PR DESCRIPTION
**Pull request by kelthuzadx**
if the divisor is a constant and not equal to 0, it's possible to deduce the final bound of ModXNode given that the following rules:
```
       x % -y ==> [0, y - 1]
       x % y ==> [0, y - 1]
       -x % y ==> [-y + 1, 0]
       -x % -y ==> [-y + 1, 0]
```

FYI: The original purpose of this patch is to eliminate array access range check(e.g. `arr[val%5]`) which discussed in https://github.com/openjdk/jdk/pull/4083#issuecomment-846971247, because ModXNode would be transformed to other nodes during IGVN, RangeCheckNode is still generated when accessing array element. Regardless of eliminating array access range check, it's still reasonable to deduce the bound of % operation if the divisor is known constant.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8267376](https://bugs.openjdk.java.net/browse/JDK-8267376): C2: Deduce the result bound of ModXNode

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4179/head:pull/4179` \
`$ git checkout pull/4179`

Update a local copy of the PR: \
`$ git checkout pull/4179` \
`$ git pull https://git.openjdk.java.net/jdk pull/4179/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4179`

View PR using the GUI difftool: \
`$ git pr show -t 4179`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4179.diff">https://git.openjdk.java.net/jdk/pull/4179.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — COMMENTED** [review]
Can you add a test that exercises this code path?

**Comment by kelthuzadx** [comment]
> Can you add a test that exercises this code path?

Hmm... I have no ideas on how to exercise this code path since idealization checks whether y is a constant value and transforms ModINode to other nodes in that case. Also, there are no such flags to be able to disable IGVN optimization as far as I see. It's unlikely to fall into the branch that y is a type of constant value in ModINode::Value. Do you have any suggestions or ideas? Thanks!

**Comment by TobiHartmann** [comment]
You could try to add an assert that fails if the path is reached, run some more sophisticated testing and extract a simple test case from a failing test.

**Comment by kelthuzadx** [comment]
I've tested it largely with assertions but it can not reach `i2->is_con()` branch currently(since idealization checks whether y is a constant value and transforms ModINode to other nodes), maybe these paths can be used in the future. I believe this is more like a refactor, it simplifies existing ModXNode::Value.

**Pull request closed without merging**
