### PR TITLE
8266181: compiler/eliminateAutobox/TestEliminateBoxInDebugInfo should be in driver mode

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review this small patch that switches the execution mode of TestEliminateBoxInDebugInfo to driver mode and makes a few small cleanups?

from JBS:
> TestEliminateBoxInDebugInfo creates a new JVM and verifies its output, hence it doesn't have to be run in the JDK in test configuration and can be run in driver mode.

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266181](https://bugs.openjdk.java.net/browse/JDK-8266181): compiler/eliminateAutobox/TestEliminateBoxInDebugInfo should be in driver mode

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3746/head:pull/3746` \
`$ git checkout pull/3746`

Update a local copy of the PR: \
`$ git checkout pull/3746` \
`$ git pull https://git.openjdk.java.net/jdk pull/3746/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3746`

View PR using the GUI difftool: \
`$ git pr show -t 3746`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3746.diff">https://git.openjdk.java.net/jdk/pull/3746.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by iignatev** [comment]
I realized that a) I should have used `OutputAnalyzer::stdoutShouldMatch`; b) there is no need to use a regexp here; c) we don't check the exit code. the latest patch addresses this.

**Review by vnkozlov — APPROVED** [review]
Still good.

**Comment by iignatev** [comment]
thanks, Vladimir!

/integrate

**Pull request closed without merging**
