### PR TITLE
8344821: Test CheckDefaultArchiveFile.java fails if classes_coh.jsa is not present

### PR DESCRIPTION
**Pull request by calvinccheung**
JDK image built by Oracle does not include the CDS archives for compact object headers. This fix throws a SkippedException if UseCompactObjectHeaders is enabled and the default CDS archive for COH is not present.

Update:
Instead of fixing the test, we've decided to just removing it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344821](https://bugs.openjdk.org/browse/JDK-8344821): Test CheckDefaultArchiveFile.java fails if classes_coh.jsa is not present (**Bug** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22374/head:pull/22374` \
`$ git checkout pull/22374`

Update a local copy of the PR: \
`$ git checkout pull/22374` \
`$ git pull https://git.openjdk.org/jdk.git pull/22374/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22374`

View PR using the GUI difftool: \
`$ git pr show -t 22374`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22374.diff">https://git.openjdk.org/jdk/pull/22374.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22374#issuecomment-2499268802)
</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
I think I agree with what @iklam said in JBS - this test seems to have no purpose now. I can't tell what exactly it is trying to check for. Depending on the runtime flags the name of the expected "default archive" is different, but it is not mandatory to have an archive file present - unless it is the plain classes.jsa one ?

And what does `Platform.isDefaultCDSArchiveSupported()` actually mean now we have the optional COH archive?

**Comment by calvinccheung** [comment]
I think this test was written for JEP341 where it eliminates and extra step of doing `-Xshare:dump` and enables `-Xshare:auto` by default. At that time, there was only one CDS archive (classes.jsa). It gets more complicated now with the COH option. I'm fine with removing this test. If the "default" archive is not available for some reasons, other tests such as the  dynamic CDS archive tests would fail so we have coverage there.

**Review by iklam — APPROVED** [review]
LGTM

**Comment by iklam** [comment]
There are also other test cases that call `Platform.isDefaultCDSArchiveSupported()`. I  think these probably need to be cleaned up / removed (in separate RFE?)

```
./lib-test/jdk/test/lib/TestMutuallyExclusivePlatformPredicates.java:                "areCustomLoadersSupportedForCDS", "isDefaultCDSArchiveSupported",
./jdk/tools/jlink/plugins/CDSPluginTest.java:        if (!Platform.isDefaultCDSArchiveSupported())
./hotspot/jtreg/runtime/cds/CheckSharingWithDefaultArchive.java:        if (!Platform.isDefaultCDSArchiveSupported()) {
./hotspot/jtreg/runtime/cds/CheckDefaultArchiveFile.java:            if (Platform.isDefaultCDSArchiveSupported()) {
./hotspot/jtreg/runtime/cds/CheckDefaultArchiveFile.java:            if (Platform.isDefaultCDSArchiveSupported()) {
./hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineSharedClass.java:        if (!Platform.isDefaultCDSArchiveSupported()) {
./lib/jdk/test/lib/Platform.java:    public static boolean isDefaultCDSArchiveSupported() {


```

**Review by dholmes-ora — APPROVED** [review]
LGTM2

**Comment by iklam** [comment]
The PR summary needs to be updated.

**Comment by calvinccheung** [comment]
> There are also other test cases that call `Platform.isDefaultCDSArchiveSupported()`. I think these probably need to be cleaned up / removed (in separate RFE?)
> 
> ```
> ./lib-test/jdk/test/lib/TestMutuallyExclusivePlatformPredicates.java:                "areCustomLoadersSupportedForCDS", "isDefaultCDSArchiveSupported",
> ./jdk/tools/jlink/plugins/CDSPluginTest.java:        if (!Platform.isDefaultCDSArchiveSupported())
> ./hotspot/jtreg/runtime/cds/CheckSharingWithDefaultArchive.java:        if (!Platform.isDefaultCDSArchiveSupported()) {
> ./hotspot/jtreg/runtime/cds/CheckDefaultArchiveFile.java:            if (Platform.isDefaultCDSArchiveSupported()) {
> ./hotspot/jtreg/runtime/cds/CheckDefaultArchiveFile.java:            if (Platform.isDefaultCDSArchiveSupported()) {
> ./hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineSharedClass.java:        if (!Platform.isDefaultCDSArchiveSupported()) {
> ./lib/jdk/test/lib/Platform.java:    public static boolean isDefaultCDSArchiveSupported() {
> ```

Other than CheckDefaultArchiveFile.java, the other tests seem to be running fine so far. Will file bug if the other tests start failing.

**Pull request closed without merging**
