### PR TITLE
8316658: serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java	fails intermittently

### PR DESCRIPTION
**Pull request by jpbempel**
…ava fails intermittently

Adjust metaspace to 20MB and iterations to 800
Metaspace usage after those adjustments on linux x64:
 - without leak: 13MB
 - with leak: 26MB

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Error
&nbsp;⚠️ The commit message contains a tab on line 1

### Issue
 * [JDK-8316658](https://bugs.openjdk.org/browse/JDK-8316658): serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java	fails intermittently (**Bug** - P3) ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16777/head:pull/16777` \
`$ git checkout pull/16777`

Update a local copy of the PR: \
`$ git checkout pull/16777` \
`$ git pull https://git.openjdk.org/jdk.git pull/16777/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16777`

View PR using the GUI difftool: \
`$ git pr show -t 16777`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16777.diff">https://git.openjdk.org/jdk/pull/16777.diff</a>

</details>

### CODE REVIEW

**Comment by MBaesken** [comment]
I think you need to remove  the AIX block now , or  adjust it too (see line 36) ?
"-XX:MetaspaceSize=23m -XX:MaxMetaspaceSize=23m"

**Comment by jpbempel** [comment]
> I think you need to remove the AIX block now , or adjust it too (see line 36) ? "-XX:MetaspaceSize=23m -XX:MaxMetaspaceSize=23m"

Right I missed the block! thanks!

**Comment by MBaesken** [comment]
No issues have been observed in our test CI with your PR added.

**Review by MBaesken — APPROVED** [review]

**Comment by lmesnik** [comment]
Seems that comment and fix mismatch,
The failure is intermittent so could you please describe how this fix has been tested. (Which platforms and how many times  executed?)

**Comment by jpbempel** [comment]
> Seems that comment and fix mismatch, The failure is intermittent so could you please describe how this fix has been tested. (Which platforms and how many times executed?)

This fix has been tested on Linux only on my side, and on AIX by [~MBaesken] but still not sure it worth a fix, if CI is already good with the specific block for AIX.

**Comment by jpbempel** [comment]
The special block for AIX is enough to make the test working as expected, I am withdrawing this PR

**Pull request closed without merging**
