### PR TITLE
8285558: IGV: scheduling crashes on control-unreachable CFG nodes

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset relaxes IGV's schedule approximation algorithm to handle CFG nodes that are not reachable from the root node via a control path. This is done by 1) removing the assumption that, after `ServerCompilerScheduler::buildBlocks()`, `Node::block` is non-null for CFG nodes; and 2) leaving the assignment of blockless nodes to an artificial "no block" to `InputGraph::ensureNodesInBlocks()`, which is always called after running the schedule approximation algorithm.

Additionally, the changeset marks unreachable CFG nodes with a warning, making it easier to identify ill-formed graphs:

screenshot of IGV graph where some nodes are marked with a warning

#### Testing

- Tested manually on the two graphs reported in the [JBS issue](https://bugs.openjdk.java.net/browse/JDK-8285558).

- Tested automatically that scheduling tens of thousands of graphs (by instrumenting IGV to schedule parsed graphs eagerly and running `java -Xcomp -XX:-TieredCompilation -XX:PrintIdealGraphLevel=4`) does not introduce any exception or assertion failure.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285558](https://bugs.openjdk.java.net/browse/JDK-8285558): IGV: scheduling crashes on control-unreachable CFG nodes

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8916/head:pull/8916` \
`$ git checkout pull/8916`

Update a local copy of the PR: \
`$ git checkout pull/8916` \
`$ git pull https://git.openjdk.java.net/jdk pull/8916/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8916`

View PR using the GUI difftool: \
`$ git pr show -t 8916`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8916.diff">https://git.openjdk.java.net/jdk/pull/8916.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by robcasloz** [comment]
> Good.

Thanks for reviewing, Vladimir!

**Review by chhagedorn — APPROVED** [review]
Looks good! That's useful to mark them with a warning when analyzing dead loop problems.

**Comment by robcasloz** [comment]
> Looks good! That's useful to mark them with a warning when analyzing dead loop problems.

Thanks for reviewing, Christian!

**Pull request closed without merging**
