### PR TITLE
JDK-8303606: Memory leaks in Arguments::parse_each_vm_init_arg

### PR DESCRIPTION
**Pull request by jcking**
Addresses various memory leaks identified by LSan related to Arguments::parse_each_vm_init_arg.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8303606](https://bugs.openjdk.org/browse/JDK-8303606): Memory leaks in Arguments::parse_each_vm_init_arg

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12867/head:pull/12867` \
`$ git checkout pull/12867`

Update a local copy of the PR: \
`$ git checkout pull/12867` \
`$ git pull https://git.openjdk.org/jdk pull/12867/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12867`

View PR using the GUI difftool: \
`$ git pr show -t 12867`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12867.diff">https://git.openjdk.org/jdk/pull/12867.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Seems okay. Thanks.

**Comment by jcking** [comment]
Friendly poke for a second reviewer. :)

**Pull request closed without merging**
