### PR TITLE
8282414: x86: Enhance the assembler to generate more compact instructions

### PR DESCRIPTION
**Pull request by merykitty**
Hi, this patch enhances the x86 assembler to emit more compact code for some popular instructions.

For common arithmetic instructions against immediates, if the immediate requires more than 1 byte to encode, we can still shave off 1 byte if the register operand is rax.

For test instruction, since the operation does not write the result, we can downgrade a long to an int and an int to a byte instruction if the immediate is positive and encodable using a smaller amount of bytes.

Thank you very much.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282414](https://bugs.openjdk.java.net/browse/JDK-8282414): x86: Enhance the assembler to generate more compact instructions

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7628/head:pull/7628` \
`$ git checkout pull/7628`

Update a local copy of the PR: \
`$ git checkout pull/7628` \
`$ git pull https://git.openjdk.java.net/jdk pull/7628/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7628`

View PR using the GUI difftool: \
`$ git pr show -t 7628`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7628.diff">https://git.openjdk.java.net/jdk/pull/7628.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me and all tests pass. @sviswa7 could you have a look at this as well?

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Comment by merykitty** [comment]
Thank you very much for the testings and reviews.
/integrate

**Pull request closed without merging**
