### PR TITLE
Delete MutableInteger

### PR DESCRIPTION
**Pull request by SWinxy**
A plain Integer object should be used rather than using a wrapping class. It's not necessary to have a separate class to do this.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11657/head:pull/11657` \
`$ git checkout pull/11657`

Update a local copy of the PR: \
`$ git checkout pull/11657` \
`$ git pull https://git.openjdk.org/jdk pull/11657/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11657`

View PR using the GUI difftool: \
`$ git pr show -t 11657`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11657.diff">https://git.openjdk.org/jdk/pull/11657.diff</a>

</details>

### CODE REVIEW

**Comment by SWinxy** [comment]
@TheShermanTanker I got a new change for ya! Relates to [JDK-8286272](https://bugs.openjdk.org/browse/JDK-8286272).

**Comment by mrserb** [comment]
Please check the performance impact, after this change we will create an Integer per glyph, and if the large text is rendered we could create many objects for a not-clear benefit.

**Comment by SWinxy** [comment]
> after this change we will create an Integer per glyph

A new MutableInteger was always created when an XRGlyphCacheEntry was being put into the cache, so I'm not seeing the concern.

> the benefit is not clear

We can use the automatic boxing of primitives instead of relying on a workaround class. One thing I just realized is that the MutableInteger could have its value changed at any time, messing with the map, as opposed to an Integer, which cannot change its value.

**Comment by mrserb** [comment]
> > after this change we will create an Integer per glyph
> 
> A new MutableInteger was always created when an XRGlyphCacheEntry was being put into the cache, so I'm not seeing the concern.

There is a difference between cache the one glyth once, and request that glyth from the cache to render each character in the text. The new integers will be created when we request the data.

> One thing I just realized is that the MutableInteger could have its value changed at any time, messing with the map, as opposed to an Integer, which cannot change its value.

But we do not change the objects added to the map after creation. Only the `tmp` object is changed which is used to request the data from the map.

**Comment by j3graham** [comment]
> > after this change we will create an Integer per glyph
> 
> A new MutableInteger was always created when an XRGlyphCacheEntry was being put into the cache, so I'm not seeing the concern.
> 
> > the benefit is not clear
> 
> We can use the automatic boxing of primitives instead of relying on a workaround class. One thing I just realized is that the MutableInteger could have its value changed at any time, messing with the map, as opposed to an Integer, which cannot change its value.

The new code will create a new object per cache lookup, whereas the old code only created one on insertion. Can’t say whether that still makes a meaningful performance difference.

**Pull request closed without merging**
