### PR TITLE
8294467: Fix sequence-point warnings in Hotspot

### PR DESCRIPTION
**Pull request by shipilev**
There seem to be the only place in Hotspot where this warning fires, yet the warning is disabled wholesale for Hotspot. This is not good.

I can trace the addition of sequence-point exclusion to [JDK-8211029](https://bugs.openjdk.org/browse/JDK-8211029) (Sep 2018), yet the only place where it triggers introduced by [JDK-8259609](https://bugs.openjdk.org/browse/JDK-8259609) (Oct 2021). It seems other places were fixed meanwhile.

I believe the fixed place is just a simple leftover. Right, @rwestrel?

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x]  Linux x86_64 fastdebug `tier2`
 - [x] The build matrix of:
   - GCC 10
   - {i686, x86_64, aarch64, powerpc64le, s390x, armhf, riscv64}
   - {server}
   - {release, fastdebug}

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294467](https://bugs.openjdk.org/browse/JDK-8294467): Fix sequence-point warnings in Hotspot

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [e4308233](https://git.openjdk.org/jdk/pull/10454/files/e4308233bc20a47a084acdd68d6155c4a0fad87a)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [e4308233](https://git.openjdk.org/jdk/pull/10454/files/e4308233bc20a47a084acdd68d6155c4a0fad87a)
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to [e4308233](https://git.openjdk.org/jdk/pull/10454/files/e4308233bc20a47a084acdd68d6155c4a0fad87a)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10454/head:pull/10454` \
`$ git checkout pull/10454`

Update a local copy of the PR: \
`$ git checkout pull/10454` \
`$ git pull https://git.openjdk.org/jdk pull/10454/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10454`

View PR using the GUI difftool: \
`$ git pr show -t 10454`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10454.diff">https://git.openjdk.org/jdk/pull/10454.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks

**Review by TobiHartmann — APPROVED** [review]
Looks good to me. I'll run this through our testing, just to make sure.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by TobiHartmann** [comment]
All tests passed.

**Comment by shipilev** [comment]
Thank you all!

/integrate

**Pull request closed without merging**
