### PR TITLE
8297424: java/net/httpclient/AsyncExecutorShutdown.java fails in AssertionError due to misplaced assert

### PR DESCRIPTION
**Pull request by dfuch**
The `ResponseSubscribers.HttpResponseInputStream` class has an assert that has been observed firing (rarely) when running the `java/net/httpclient/AsyncExecutorShutdown.java` test.

After a thorough analysis of the code and the log failure I am convinced that the issue is due to a misplaced assert.
If cancellation happens asynchronously while the subscriber is being subscribed with the lower layers of the stack, the `HttpResponseInputStream` might get closed and the `LAST_LIST` buffer might be offered after `closed == false` has been observed by the `onSubscribed` method, but before the assertion has been checked. The assertion assumes that the queue must be empty, but it might not if `close` has been called and the `LAST_LIST` buffer has been offered.

Moving the assert from within the synchronized block, to ensure that the observed value of `closed` is consistent with the state of the queue, should fix it. I have tagged the bug as `noreg-hard`, I'm not sure it would be fair to say that `AsyncExecutorShutdown.java` can be used to verify the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297424](https://bugs.openjdk.org/browse/JDK-8297424): java/net/httpclient/AsyncExecutorShutdown.java fails in AssertionError due to misplaced assert

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11332/head:pull/11332` \
`$ git checkout pull/11332`

Update a local copy of the PR: \
`$ git checkout pull/11332` \
`$ git pull https://git.openjdk.org/jdk pull/11332/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11332`

View PR using the GUI difftool: \
`$ git pr show -t 11332`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11332.diff">https://git.openjdk.org/jdk/pull/11332.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Daniel, the change where we move the assert into the synchronized block looks fine to me. Looking at the code I think the check to see that the `buffers` can accomodate at least 2 elements (when `onSubscribe` is called) looks correct to me because the `buffers` will be initialized in the constructor of `HttpResponseInputStream` with a capacity of at least 2. So the assert itself looks correct.

This PR also has changes in the `Stream` class. Some of those changes are typo related fixes, so that's fine. However, it also has other functional changes. Is that intentional and related?

**Comment by dfuch** [comment]
> This PR also has changes in the `Stream` class. Some of those changes are typo related fixes, so that's fine. However, it also has other functional changes. Is that intentional and related?

These are changes I made when investigating the fix, and they are not related. The `pendingSubscriber` is a temporary field that holds the subscriber value until the subscriber is handled and subscribed by the `schedule` loop. It is a bit confusing to see a non null `pendingSubscriber` after it has been handled by that loop. Practically, setting it to `null` or leaving it assigned at this point should have no effect on the behavior of this class... Hmmm... except I see ternary operators that first look at the subscriber and then at the pending subscriber. So this change now introduce a potential race condition if they are executed concurrently with the `schedule` loop. Good observation. I will revert that.

**Review by jaikiran — APPROVED** [review]
Thank you Daniel. The latest changes look good to me.

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
