### PR TITLE
8265293: ProblemList java/foreign/TestDowncall.java on macosx-aarch64

### PR DESCRIPTION
**Pull request by vidmik**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265293](https://bugs.openjdk.java.net/browse/JDK-8265293): ProblemList java/foreign/TestDowncall.java on macosx-aarch64

### Reviewers
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3520/head:pull/3520` \
`$ git checkout pull/3520`

Update a local copy of the PR: \
`$ git checkout pull/3520` \
`$ git pull https://git.openjdk.java.net/jdk pull/3520/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3520`

View PR using the GUI difftool: \
`$ git pr show -t 3520`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3520.diff">https://git.openjdk.java.net/jdk/pull/3520.diff</a>

</details>

### CODE REVIEW

**Review by calvinccheung — APPROVED** [review]
Looks good.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This is a trivial fix and does not need to wait 24 hours.

**Pull request closed without merging**
