### PR TITLE
8299811: SHIFT_JIS compatible charsets should be in java.base module on Linux platform

### PR DESCRIPTION
**Pull request by takiguc**
On Japanese environment, following SHIFT_JIS compatible charsets are there:
* PCK (x-PCK)
* MS932 (windows-31j)
* IBM943C (x-IBM943C)

According to make/data/charsetmapping/charsets,
PCK and MS932 are independent charset and have no dependencies on others.

On RHEL8, SHIFT_JIS encoding is supported
```
$ env LANG=ja_JP.sjis locale charmap
SHIFT_JIS
```
According to make/data/charsetmapping/stdcs-linux,
SJIS (SHIFT_JIS) is in there, also MS932 and PCK are there.
This means these are in java.base module on Linux platform.
But IBM943C is not in stdcs-linux.
I think IBM943C also should be in java.base module because of compatibility.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299811](https://bugs.openjdk.org/browse/JDK-8299811): SHIFT_JIS compatible charsets should be in java.base module on Linux platform

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11908/head:pull/11908` \
`$ git checkout pull/11908`

Update a local copy of the PR: \
`$ git checkout pull/11908` \
`$ git pull https://git.openjdk.org/jdk pull/11908/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11908`

View PR using the GUI difftool: \
`$ git pr show -t 11908`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11908.diff">https://git.openjdk.org/jdk/pull/11908.diff</a>

</details>

### CODE REVIEW

**Comment by naotoj** [comment]
I think the general consensus is to keep the `java.base` module minimal. IIRC, the reason we have `PCK` charsets in Un*x platforms was that it was required to boot Solaris in Japanese env (sorry if I am wrong). So I would remove it from `java.base` if possible. Thus moving those IBM* encodings that are equivalent to SJIS into `java.base` is something I would not want to do. It is definitely not a compatibility issue.

**Comment by takiguc** [comment]
Hello @naotoj .

Sorry, "compatibility" may not be valid wording.
Now Linux is one of native application migration platform from *nix platform.
Since SJIS charset does not have enough supported characters on Japanese environment.
PCK and Cp943C charsets may be covered on this situation.

**Comment by takiguc** [comment]
I'd like to close this PR.
Thanks.

**Pull request closed without merging**
