### PR TITLE
8272364: Parallel GC adaptive size policy may shrink the heap below MinHeapSize

### PR DESCRIPTION
**Pull request by zhengyu123**
This appears to be another miscalculation of gc ergonomics. When `NewSize` is not explicitly set, `MinNewSize` should be derived from `MinHeapSize` using `NewRatio`.

This pull request has dependency on [PR#18539](https://github.com/openjdk/jdk/pull/18539)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8272364](https://bugs.openjdk.org/browse/JDK-8272364): Parallel GC adaptive size policy may shrink the heap below MinHeapSize (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to [49449442](https://git.openjdk.org/jdk/pull/18877/files/49449442ab1fd49502eefb24786b3f00ee6f5063)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to [49449442](https://git.openjdk.org/jdk/pull/18877/files/49449442ab1fd49502eefb24786b3f00ee6f5063)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18877/head:pull/18877` \
`$ git checkout pull/18877`

Update a local copy of the PR: \
`$ git checkout pull/18877` \
`$ git pull https://git.openjdk.org/jdk.git pull/18877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18877`

View PR using the GUI difftool: \
`$ git pr show -t 18877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18877.diff">https://git.openjdk.org/jdk/pull/18877.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18877#issuecomment-2067718324)

### CODE REVIEW

**Comment by rkennke** [comment]
Can the example in the bug-report be turned into a jtreg test?

**Review by albertnetymk — APPROVED** [review]

**Review by rkennke — APPROVED** [review]
Looks good, thank you!

**Comment by zhengyu123** [comment]
/integrate

Thanks for the review, @rkennke @albertnetymk

**Pull request closed without merging**
