### PR TITLE
8302830: AArch64: Fix the mismatch between cas.m4 and aarch64.ad

### PR DESCRIPTION
**Pull request by shqking**
Fix the following mismatch between cas.m4 and aarch64.ad.

```
$ m4 cas.m4 > cas.gen.ad
$ sed  '8930,9404!d' aarch64.ad > res.ad
$ diff -uN cas.gen.ad res.ad | cat -A

--- cas.gen.ad^I2023-02-20 04:18:46.624289978 +0000$
+++ res.ad^I2023-02-20 04:19:08.780351888 +0000$
@@ -15,7 +15,7 @@$
 // This pattern is generated automatically from cas.m4.$
 // DO NOT EDIT ANYTHING IN THIS SECTION OF THE FILE$
 instruct compareAndExchangeB(iRegINoSp res, indirect mem, iRegI oldval, iRegI newval, rFlagsReg cr) %{$
-  $
+$
   match(Set res (CompareAndExchangeB mem (Binary oldval newval)));$
   ins_cost(2 * VOLATILE_REF_COST);$
   effect(TEMP_DEF res, KILL cr);$
...
```

Besides, update the comment since "aarch_ad_cas.m4" was renamed to "cas.m4".

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302830](https://bugs.openjdk.org/browse/JDK-8302830): AArch64: Fix the mismatch between cas.m4 and aarch64.ad

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Xiaohong Gong](https://openjdk.org/census#xgong) (@XiaohongGong - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12647/head:pull/12647` \
`$ git checkout pull/12647`

Update a local copy of the PR: \
`$ git checkout pull/12647` \
`$ git pull https://git.openjdk.org/jdk pull/12647/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12647`

View PR using the GUI difftool: \
`$ git pr show -t 12647`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12647.diff">https://git.openjdk.org/jdk/pull/12647.diff</a>

</details>

### CODE REVIEW

**Comment by theRealAph** [comment]
Whitespace is all messed up. try this:

[foo.zip](https://github.com/openjdk/jdk/files/10784530/foo.zip)

**Comment by shqking** [comment]
> Whitespace is all messed up. try this:
> 
> [foo.zip](https://github.com/openjdk/jdk/files/10784530/foo.zip)

I have updated the patch based on your example.
Would you mind taking another look? Thanks!

**Comment by shqking** [comment]
@theRealAph  Could you help take another look at this PR? Thanks in advance.

**Review by theRealAph — APPROVED** [review]

**Review by XiaohongGong — APPROVED** [review]
LGTM!

**Pull request closed without merging**
