### PR TITLE
8256995: [vector] Improve broadcast operations

### PR DESCRIPTION
**Pull request by PaulSandoz**
Use the raw FP to bits conversion methods (to avoid NaN checks). Improve the x64 code generation when broadcasting a value.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256995](https://bugs.openjdk.java.net/browse/JDK-8256995): [vector] Improve broadcast operations

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Contributors
 * Paul Sandoz `<psandoz@openjdk.org>`
 * Sandhya Viswanathan `<sviswanathan@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1445/head:pull/1445`
`$ git checkout pull/1445`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Assembler changes seems fine.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Pull request closed without merging**
