### PR TITLE
8298725: Add BitMap support for reverse iteration

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this addition of BitMap::reverse_iterate, which is like
BitMap::iterate but visits the set bits in a range from high index to low.

Testing:
mach5 tier1, which includes running the updated gtests on all Oracle-supported
platform

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298725](https://bugs.openjdk.org/browse/JDK-8298725): Add BitMap support for reverse iteration

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [d52a34fb](https://git.openjdk.org/jdk/pull/13151/files/d52a34fbb66fe4ef950a94520d47ff3aa781ab0f)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer) ⚠️ Review applies to [d52a34fb](https://git.openjdk.org/jdk/pull/13151/files/d52a34fbb66fe4ef950a94520d47ff3aa781ab0f)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [d52a34fb](https://git.openjdk.org/jdk/pull/13151/files/d52a34fbb66fe4ef950a94520d47ff3aa781ab0f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13151/head:pull/13151` \
`$ git checkout pull/13151`

Update a local copy of the PR: \
`$ git checkout pull/13151` \
`$ git pull https://git.openjdk.org/jdk.git pull/13151/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13151`

View PR using the GUI difftool: \
`$ git pr show -t 13151`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13151.diff">https://git.openjdk.org/jdk/pull/13151.diff</a>

</details>

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Review by tschatzl — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks for reviews @xmas92 , @stefank , and @tschatzl .

**Pull request closed without merging**
