### PR TITLE
8305442: (bf) Direct and view implementations of CharBuffer.toString(int, int) do not need to catch SIOBE

### PR DESCRIPTION
**Pull request by stsypanov**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305442](https://bugs.openjdk.org/browse/JDK-8305442): (bf) Direct and view implementations of CharBuffer.toString(int, int) do not need to catch SIOBE

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13286/head:pull/13286` \
`$ git checkout pull/13286`

Update a local copy of the PR: \
`$ git checkout pull/13286` \
`$ git pull https://git.openjdk.org/jdk.git pull/13286/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13286`

View PR using the GUI difftool: \
`$ git pr show -t 13286`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13286.diff">https://git.openjdk.org/jdk/pull/13286.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
I suspect this goes back to the original implementation. I assume you'll run the jdk_nio tests.

**Comment by stsypanov** [comment]
@AlanBateman FYI
```
make test TEST=jdk_nio
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk:jdk_nio                              471   471     0     0   
==============================
TEST SUCCESS
```

**Review by bplb — APPROVED** [review]
Looks fine and builds.

**Pull request closed without merging**
