### PR TITLE
8257221: C2: RegMask::is_bound_set split set handling broken since JDK-8221404

### PR DESCRIPTION
**Pull request by cl4es**
This patch adds more tests for RegMask::is_bound* operations, and fixes a bug I introduced in JDK-8221404 where I mixed up the formula for how much we need to shift the "bit" when checking a split set.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux additional | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- |
| Build | ⏳ (5/8 running) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ⏳ (1/2 running) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ⏳ (8/9 running) | ⏳ (3/9 running) |    |  ⏳ (1/9 running) |

### Issue
 * [JDK-8257221](https://bugs.openjdk.java.net/browse/JDK-8257221): C2: RegMask::is_bound_set split set handling broken since JDK-8221404

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 2937939db88a5cf129ed06c249c803b527c603d2
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1486/head:pull/1486`
`$ git checkout pull/1486`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
okay.

**Comment by cl4es** [comment]
@vnkozlov - as we discussed I split out the optimizations to a separate RFE, leaving the new tests and the one-liner bug fix for this PR.

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by neliasso — APPROVED** [review]
Looks good.

**Pull request closed without merging**
