### PR TITLE
8298301: C2: assert(main_cmp->in(2)->Opcode() == Op_Opaque1) failed: main loop has no opaque node?

### PR DESCRIPTION
**Pull request by chhagedorn**
This starts to show up in our CI in various tests after [JDK-8269820](https://bugs.openjdk.org/browse/JDK-8269820) which added a new `OpaqueZeroTripGuardNode` but forgot to update an assert which still checks for `Opaque1` instead of `OpaqueZeroTripGuard`. I've fixed that with this patch.

Currently running tests:
- tier1-4

Thanks,
Christian

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298301](https://bugs.openjdk.org/browse/JDK-8298301): C2: assert(main_cmp->in(2)->Opcode() == Op_Opaque1) failed: main loop has no opaque node?

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [a0151669](https://git.openjdk.org/jdk/pull/11567/files/a0151669821cae5bd6655295ab44c8cefbc0e5e5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11567/head:pull/11567` \
`$ git checkout pull/11567`

Update a local copy of the PR: \
`$ git checkout pull/11567` \
`$ git pull https://git.openjdk.org/jdk pull/11567/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11567`

View PR using the GUI difftool: \
`$ git pr show -t 11567`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11567.diff">https://git.openjdk.org/jdk/pull/11567.diff</a>

</details>

### CODE REVIEW

**Comment by TobiHartmann** [comment]
The fix looks good and trivial.

FTR, my testing for [JDK-8269820](https://bugs.openjdk.org/browse/JDK-8269820) didn't catch this because I only executed the stress job definition for the latest update (I did run full testing for v00 though).

**Review by TobiHartmann — APPROVED** [review]

**Comment by chhagedorn** [comment]
Thanks Tobias for the quick review! I'll try to integrate this as soon as testing is looking (mostly) good to reduce the noise in our CI.

**Review by vnkozlov — COMMENTED** [review]
Looks good.
One more reason to rename all Opaque nodes and find places where they are used.

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review! I totally agree with that.

Testing is mostly done and looks clean. I'll integrate it.

**Pull request closed without merging**
