### PR TITLE
8277619: AArch64: Incorrect parameter type in Advanced SIMD Copy assembler functions

### PR DESCRIPTION
**Pull request by fg1417**
Mov (from general), incorrectly uses SIMD_Arrangement as the parameter
type of the assembler function. However, from Arm ARM [1], it's more
precise to use SIMD_RegVariant here.

The situation is similar to Mov(to general) [2].

Note that as Mov(to general) is an alias of UMOV, we turn to re-use
UMOV encoding for Mov(to general) in this patch.

[1] https://developer.arm.com/documentation/ddi0602/2020-12/SIMD-FP-Instructions/MOV--from-general---Move-general-purpose-register-to-a-vector-element--an-alias-of-INS--general--
[2] https://developer.arm.com/documentation/ddi0602/2020-12/SIMD-FP-Instructions/MOV--to-general---Move-vector-element-to-general-purpose-register--an-alias-of-UMOV-

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277619](https://bugs.openjdk.java.net/browse/JDK-8277619): AArch64: Incorrect parameter type in Advanced SIMD Copy assembler functions

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)
 * [Pengfei Li](https://openjdk.java.net/census#pli) (@pfustc - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6629/head:pull/6629` \
`$ git checkout pull/6629`

Update a local copy of the PR: \
`$ git checkout pull/6629` \
`$ git pull https://git.openjdk.java.net/jdk pull/6629/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6629`

View PR using the GUI difftool: \
`$ git pr show -t 6629`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6629.diff">https://git.openjdk.java.net/jdk/pull/6629.diff</a>

</details>

### CODE REVIEW

**Comment by fg1417** [comment]
The PR does some code cleaning in AArch64 assembler. Can I have your review please?

**Review by theRealAph — APPROVED** [review]

**Review by pfustc — APPROVED** [review]

**Pull request closed without merging**
