### PR TITLE
JDK-8324774: Add DejaVu web fonts

### PR DESCRIPTION
**Pull request by hns**
This change adds the DejaVu web fonts that were previously maintained externally to the open repository so they are available both in JDK API documentation and any API documentation generated with the `javadoc` tool. All files added in this PR are the same as the ones previously maintained externally, with the exception of added license and name/version comments in `dejavu.css`.

Copying of font files to the generated documentation is done by looking for font file names in `dejavu.css`, so font file names can be changed without changing the code. However, the font file list is hard-coded in `APITest.java`. `CheckLibraryVersions.java` is updated to make sure the name and version in the legal file matches the one in the stylesheet. Of course I also performed manual tests to make sure the font and legal files are copied to the output tree and used correctly in browsers.

Once #17411 is integrated, `dejavu.css` should also be added to the list of files checked by the new "pass-through" test.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))
- [x] Change requires CSR request [JDK-8326683](https://bugs.openjdk.org/browse/JDK-8326683) to be approved

### Issues
 * [JDK-8324774](https://bugs.openjdk.org/browse/JDK-8324774): Add DejaVu web fonts (**Enhancement** - P3)
 * [JDK-8327385](https://bugs.openjdk.org/browse/JDK-8327385): Add JavaDoc option to exclude web fonts from generated documentation (**Enhancement** - P3)
 * [JDK-8326683](https://bugs.openjdk.org/browse/JDK-8326683): Add JavaDoc option to exclude web fonts from generated documentation (**CSR**)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [2c6e2163](https://git.openjdk.org/jdk/pull/17633/files/2c6e216310afd8d79c691d9e683068938c16d94e)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17633/head:pull/17633` \
`$ git checkout pull/17633`

Update a local copy of the PR: \
`$ git checkout pull/17633` \
`$ git pull https://git.openjdk.org/jdk.git pull/17633/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17633`

View PR using the GUI difftool: \
`$ git pr show -t 17633`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17633.diff">https://git.openjdk.org/jdk/pull/17633.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17633#issuecomment-1917417106)

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Build changes look trivially fine

**Review by jonathan-gibbons — APPROVED** [review]

**Comment by jonathan-gibbons** [comment]
I like the new stuff for `JavadocTester` wrapped up in this work.

**Pull request closed without merging**
