### PR TITLE
8330577: G1 sometimes sends jdk.G1HeapRegionTypeChange for non-changes

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

  please review this change that avoids posting Free->Free and Old->Old region transitions in JFR.

The reason for these could have been:
  * Free->Free: heap shrinking and full gc
  * Old->Old: heap shrinking, full gc or evacuation failure in an old region

Parts of this change has been contributed by @ansteiner , crediting him for this (the first commit).

Testing: tier1-3, tier5, all "detailed" JFR test cases

Thanks,
  Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330577](https://bugs.openjdk.org/browse/JDK-8330577): G1 sometimes sends jdk.G1HeapRegionTypeChange for non-changes (**Bug** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to [2376c15b](https://git.openjdk.org/jdk/pull/19389/files/2376c15bcb66f4db8fd1ef4d0d62273f08307a2d)
 * [Andreas Steiner](https://openjdk.org/census#asteiner) (@ansteiner - Author) ⚠️ Review applies to [2376c15b](https://git.openjdk.org/jdk/pull/19389/files/2376c15bcb66f4db8fd1ef4d0d62273f08307a2d)

### Contributors
 * Andreas Steiner `<asteiner@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19389/head:pull/19389` \
`$ git checkout pull/19389`

Update a local copy of the PR: \
`$ git checkout pull/19389` \
`$ git pull https://git.openjdk.org/jdk.git pull/19389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19389`

View PR using the GUI difftool: \
`$ git pr show -t 19389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19389.diff">https://git.openjdk.org/jdk/pull/19389.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19389#issuecomment-2129469254)

### CODE REVIEW

**Review by albertnetymk — APPROVED** [review]

**Review by ansteiner — APPROVED** [review]
LGTM

**Comment by tschatzl** [comment]
Thanks @ansteiner @albertnetymk for your reviews
/integrate

**Pull request closed without merging**
