### PR TITLE
8301327: convert assert to guarantee in Handle_IDiv_Exception

### PR DESCRIPTION
**Pull request by afshin-zafari**
The `assert` usages are replaced with `guarantee`.

Tested tier1-4, windows-x64 and windows-x64-debug.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301327](https://bugs.openjdk.org/browse/JDK-8301327): convert assert to guarantee in Handle_IDiv_Exception (**Enhancement** - P4)

### Reviewers
 * [Doug Simon](https://openjdk.org/census#dnsimon) (@dougxc - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15945/head:pull/15945` \
`$ git checkout pull/15945`

Update a local copy of the PR: \
`$ git checkout pull/15945` \
`$ git pull https://git.openjdk.org/jdk.git pull/15945/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15945`

View PR using the GUI difftool: \
`$ git pr show -t 15945`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15945.diff">https://git.openjdk.org/jdk/pull/15945.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15945#issuecomment-1737409220)

### CODE REVIEW

**Comment by dougxc** [comment]
Thanks for doing this. Can you please enhance the error message of each guarantee to include the unexpected/problematic value(s).

**Comment by afshin-zafari** [comment]
> Thanks for doing this. Can you please enhance the error message of each guarantee to include the unexpected/problematic value(s).

The expected and actual values are now printed in the guarantee message.

**Review by dougxc — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Seems reasonable.

Thanks

**Comment by afshin-zafari** [comment]
Thanks for the reviews.
/integrate

**Pull request closed without merging**
