### PR TITLE
JDK-8310919: runtime/ErrorHandling/TestAbortVmOnException.java times out due to core dumps taking a long time on OSX

### PR DESCRIPTION
**Pull request by dafedafe**
Sometimes the test `runtime/ErrorHandling/TestAbortVmOnException.java` times out on MacOS.

This is due to the fact that the test crashes 3 times by design creating a core dump every time and sometimes on MacOS it takes a long time to create core dumps.

Since there is no reason for these crashes to have core dumps, we avoid creating them by using the `-XX:-CreateCoredumpOnCrash` flag.

Additionally adding `-XX:CompileCommand=compileonly,TestAbortVmOnException::*` to restrict the compilation only to `TestAbortVmOnException` methods and thus make the test faster.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8310919](https://bugs.openjdk.org/browse/JDK-8310919): runtime/ErrorHandling/TestAbortVmOnException.java times out due to core dumps taking a long time on OSX (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14704/head:pull/14704` \
`$ git checkout pull/14704`

Update a local copy of the PR: \
`$ git checkout pull/14704` \
`$ git pull https://git.openjdk.org/jdk.git pull/14704/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14704`

View PR using the GUI difftool: \
`$ git pr show -t 14704`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14704.diff">https://git.openjdk.org/jdk/pull/14704.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14704#issuecomment-1612824667)

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by dholmes-ora — APPROVED** [review]
Ship it! Thanks

**Comment by dafedafe** [comment]
@TobiHartmann @dholmes-ora thanks a lot for your reviews!

**Pull request closed without merging**
