### PR TITLE
8342496: C2/Shenandoah: SEGV in compiled code when running jcstress

### PR DESCRIPTION
**Pull request by rwestrel**
The reason for the crash is that compiled code reads from an object
that's null. All field loads from an object are guarded by a null
check. Where is the null check in that case? After the field load:

```
0x00007ffaac91261f:  44 8B 69 0C                      mov    r13d, dword ptr [rcx + 0xc] <- field load
0x00007ffaac912623:  85 C9                            test   ecx, ecx                    <- null check (oops!)
0x00007ffaac912625:  74 5C                            je     0x7ffaac912683
```

When the IR graph is constructed for the test case, the field load is
correctly made dependent on the null check (through a `CastPP` node)
but then something happens that's shenandoah specific and that causes
the field load to become dependent on another check so it can execute
before the null check.

There are several load barriers involved in the process. One of them
is expanded at the null check projection. In the process, control for
the nodes that are control dependent on the null check is updated to
be the region at the end of the just expanded barrier. The `CastPP`
node for the null check gets the `Region` as new control.

Another barrier is expanded right after that one. The 2 are back to
back. They are merged. The `Region` that the `CastPP` depends on goes
away, the `CastPP` is cloned in both branches at the `Region` and one
of them becomes control dependent on the heap stable test of the first
expanded barrier. At this point, one of the `CastPP` is control
dependent on a heap stable test that's after the null check. But then,
the heap stable test is moved out of loop and 2 copies of the loop are
made so one can run without any overhead from barriers. When that
happens, the `CastPP` becomes dependent on a test that dominates the
null check and so the field load that depends on the `CastPP` can be
scheduled before the null check.

The fix I propose is not update the control when the barrier is
expanded for nodes that can float when the test they depend on
moves. This way the `CastPP` remains dependent on the null check.

/cc hotspot-compiler

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342496](https://bugs.openjdk.org/browse/JDK-8342496): C2/Shenandoah: SEGV in compiled code when running jcstress (**Bug** - P3)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21562/head:pull/21562` \
`$ git checkout pull/21562`

Update a local copy of the PR: \
`$ git checkout pull/21562` \
`$ git pull https://git.openjdk.org/jdk.git pull/21562/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21562`

View PR using the GUI difftool: \
`$ git pr show -t 21562`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21562.diff">https://git.openjdk.org/jdk/pull/21562.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21562#issuecomment-2419525426)

### CODE REVIEW

**Comment by shipilev** [comment]
Thanks! I am running tests with this patch.

**Review by shipilev — APPROVED** [review]
Testing says no functional/performance regressions with this patch.

**Review by rkennke — APPROVED** [review]
Looks good to me. Thank you!

**Comment by rwestrel** [comment]
@shipilev @rkennke thanks for the reviews + testing

**Pull request closed without merging**
