### PR TITLE
8339661: ZGC: Move some page resets and verification to callsites

### PR DESCRIPTION
**Pull request by jsikstro**
Currently, `ZPage::reset()` does different things depending on where the page is being reset and what it will be used for. This leads to checks being somewhat hard to understand and to follow the edge-cases of.

By moving some of the reset logic that is now part of `ZPage::reset()` to the callsite, some operations can be made easier to understand the reason behind when reading the code.

Main highlights:
- Clear logic behind initializing remsets at callsites, now guarded by asserts in `ZPage::remset_initialize()`.
- `ZPage::clone_limited()` retains the value of the top-pointer.
- The kind of verification for remsets are now at callsites:
  - Allocations from the page cache, and only if the page got a remset
  - Old-to-old in-place relocations, where only the inactive remset is checked

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339661](https://bugs.openjdk.org/browse/JDK-8339661): ZGC: Move some page resets and verification to callsites (**Enhancement** - P4)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20890/head:pull/20890` \
`$ git checkout pull/20890`

Update a local copy of the PR: \
`$ git checkout pull/20890` \
`$ git pull https://git.openjdk.org/jdk.git pull/20890/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20890`

View PR using the GUI difftool: \
`$ git pr show -t 20890`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20890.diff">https://git.openjdk.org/jdk/pull/20890.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20890#issuecomment-2333979929)

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good!

**Review by fisk — APPROVED** [review]
Nice change! Looks good.

**Comment by jsikstro** [comment]
Thank you for the reviews! @stefank @fisk 
/integrate

**Pull request closed without merging**
