### PR TITLE
8281543: Remove unused code/headerfile dtraceAttacher.hpp

### PR DESCRIPTION
**Pull request by eme64**
`dtraceAttacher.cpp` with all the relevant definitions was deleted [here](https://github.com/openjdk/jdk/commit/071bd521bca2485c6df95c45e4310d39b05bd046)
in connection with [JDK-8244224](https://bugs.openjdk.java.net/browse/JDK-8244224) (Remove the Solaris and SPARC Ports).

I deleted `dtraceAttacher.cpp`, and the 4 include statements of it in 4 `src/hotspot/os/???/attachListener_???.cpp` files.

Ran tests, mostly to check that it still compiles on various platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281543](https://bugs.openjdk.java.net/browse/JDK-8281543): Remove unused code/headerfile dtraceAttacher.hpp

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7544/head:pull/7544` \
`$ git checkout pull/7544`

Update a local copy of the PR: \
`$ git checkout pull/7544` \
`$ git pull https://git.openjdk.java.net/jdk pull/7544/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7544`

View PR using the GUI difftool: \
`$ git pr show -t 7544`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7544.diff">https://git.openjdk.java.net/jdk/pull/7544.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Hi Emanuel,

This looks good and trivial.

AFAICS the existence of these includes was a mistake in the first place. Only `attachListener_solaris.cpp` actually needed it, but a limitation of the ancient `includeDB` mechanism meant it was listed as needed by all `attachListener_<os_family>.cpp` files. Then we got rid of `includeDB` and moved to the standard include mechanism, that dependency was expanded to produce an include entry in each file now being fixed.

Cheers,
David

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Comment by eme64** [comment]
Thanks @dholmes-ora @TobiHartmann for the reviews!
/integrate

**Comment by dholmes-ora** [comment]
Looks like I mis-clicked and hit Comment instead of Approve! Oops.

**Pull request closed without merging**
