### PR TITLE
8291830: jvmti/RedefineClasses/StressRedefine failed: assert(!is_null(v)) failed: narrow klass value can never be zero

### PR DESCRIPTION
**Pull request by coleenp**
The code for RedefineVerifyMark in redefinition replaces the OopHandle mirror so that the verification has the right mirror, but it really should just copy it.  Replacing an OopHandle in the ClassLoaderData didn't set the has_modified_oops flag so GC wasn't noticing that this handle is old.

Tested with tier1-4 and tier6 in progress (linux-x64 and windows-x64 done).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291830](https://bugs.openjdk.org/browse/JDK-8291830): jvmti/RedefineClasses/StressRedefine failed: assert(!is_null(v)) failed: narrow klass value can never be zero

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to [2f8d5517](https://git.openjdk.org/jdk/pull/11444/files/2f8d5517afef45f461bb789f659631f0d1cf7fbd)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to [2f8d5517](https://git.openjdk.org/jdk/pull/11444/files/2f8d5517afef45f461bb789f659631f0d1cf7fbd)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11444/head:pull/11444` \
`$ git checkout pull/11444`

Update a local copy of the PR: \
`$ git checkout pull/11444` \
`$ git pull https://git.openjdk.org/jdk pull/11444/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11444`

View PR using the GUI difftool: \
`$ git pr show -t 11444`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11444.diff">https://git.openjdk.org/jdk/pull/11444.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
Coleen,
This looks good.
Wow, it is great you've found the root cause!
It was not easy for sure.
Thanks,
Serguei

**Comment by coleenp** [comment]
Thanks Serguei!

**Review by fisk — APPROVED** [review]
Looks good.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by coleenp** [comment]
Thanks for reviewing Serguei, Erik.  Kim, thank you for the cleaner implementation with swap and for reviewing.

**Pull request closed without merging**
