### PR TITLE
8260004: Shenandoah: Rename ShenandoahMarkCompact to ShenandoahFullGC

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this patch that renames ShenandoahMarkCompact to ShenandoahFullGC, to be consistent with other GCs.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260004](https://bugs.openjdk.java.net/browse/JDK-8260004): Shenandoah: Rename ShenandoahMarkCompact to ShenandoahFullGC

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to b8dd4e0206da770348eecfdd64c65a13e6600bbd
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**) ⚠️ Review applies to b8dd4e0206da770348eecfdd64c65a13e6600bbd

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2266/head:pull/2266`
`$ git checkout pull/2266`

### CODE REVIEW

**Comment by rkennke** [comment]
This nomenclature might become problematic when generational Shenandoah becomes a thing. Then, what we do now, collecting the complete heap, as opposed to only the young generation, might be mistaken as 'full gc' too.

**Comment by zhengyu123** [comment]
> This nomenclature might become problematic when generational Shenandoah becomes a thing. Then, what we do now, collecting the complete heap, as opposed to only the young generation, might be mistaken as 'full gc' too.

Does "full GC" always means complete heap collection?  G1 calls it FullCollector and supporting classes all prefixing with FullGC ...

**Comment by shipilev** [comment]
I vote for this rename. We already report "Pause Full" for this operation, so it is "Full GC". The generational extension would probably call their phases "young" and "mixed" concurrent GC?

**Review by shipilev — APPROVED** [review]

**Comment by rkennke** [comment]
> I vote for this rename. We already report "Pause Full" for this operation, so it is "Full GC". The generational extension would probably call their phases "young" and "mixed" concurrent GC?

Yes ok. We can consider what to do when generational GC lands, if it is a problem at all.

**Review by rkennke — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
