### PR TITLE
8256508: Improve CompileCommand flag

### PR DESCRIPTION
**Pull request by neliasso**
The current implementation of compile command has two types of options. Types pre-defined options like "compileonly" and the general 'option' type.

'option'-type are not defined, they can accidentally be used with the wrong value type, and the syntax is prone to error.

By pre-defining all compile commands used and giving them types the parsing can be simplified, proper parsing errors can be given and and reasonable syntax can be used.

This:
-XX:CompileCommand=option,java/util/String.toString,int,RepeatCompilation,5

Is superseded by:
-XX:CompileCommand=RepeatCompilation,java/util/String.toString,5

Attention check: Did you spot the error in the old command?

In order not to break anything - the old syntax is kept for now. But even the old command format is improved with verification for the option name and the type of the value.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ❌ (5/6 failed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux x64 (build debug)](https://github.com/neliasso/jdk/runs/1449437478)
- [Linux x64 (build hotspot minimal)](https://github.com/neliasso/jdk/runs/1449437719)
- [Linux x64 (build hotspot no-pch)](https://github.com/neliasso/jdk/runs/1449437500)
- [Linux x64 (build hotspot optimized)](https://github.com/neliasso/jdk/runs/1449437733)
- [Linux x64 (build hotspot zero)](https://github.com/neliasso/jdk/runs/1449437671)
- [Linux x86 (build debug)](https://github.com/neliasso/jdk/runs/1449437411)
- [Linux x86 (build release)](https://github.com/neliasso/jdk/runs/1449437393)

### Issue
 * [JDK-8256508](https://bugs.openjdk.java.net/browse/JDK-8256508): Improve CompileCommand flag

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to 1995972f5126a25d6fc9a9a86f201ca93c8f491b
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 1995972f5126a25d6fc9a9a86f201ca93c8f491b

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1276/head:pull/1276`
`$ git checkout pull/1276`

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
A good usability improvement! 

I've messed up some minor details in these commands in one way or another more times than I've gotten things right on the first try and been left wondering why my commands have no effect. This should help avoid a significant portion of easy mistakes. 

I think the error in the old compile command is that int needs to be intx?

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by neliasso** [comment]
@cl4es @vnkozlov 
I did a very minor update to compilerDirectives.hpp. The Exclude is already handled separately in init_compilecommand_compatibility. This is back to how it was before this PR.

**Review by cl4es — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Please, run pre-integration testing before push.
Latest update is fine to me but I am concern that GIT testing has failures in builds.

**Comment by neliasso** [comment]
> Please, run pre-integration testing before push.
> Latest update is fine to me but I am concern that GIT testing has failures in builds.

Yes - I did a bad merge. Fixed it now. Will do a proper round of testing before pushing.

**Pull request closed without merging**
