### PR TITLE
8252577: HotSpot Style Guide should link to One-True-Brace-Style description

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to provide a link to the Wikipedia description of
One-True-Brace-Style.

As this is a HotSpot Style Guide change, it requires reviewers who are HotSpot
Group Members, though comments from others are welcome.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252577](https://bugs.openjdk.java.net/browse/JDK-8252577): HotSpot Style Guide should link to One-True-Brace-Style description

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to 445e89736e5b4f492b506f1799eb567f5d7385eb
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 445e89736e5b4f492b506f1799eb567f5d7385eb
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 445e89736e5b4f492b506f1799eb567f5d7385eb

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7692/head:pull/7692` \
`$ git checkout pull/7692`

Update a local copy of the PR: \
`$ git checkout pull/7692` \
`$ git pull https://git.openjdk.java.net/jdk pull/7692/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7692`

View PR using the GUI difftool: \
`$ git pr show -t 7692`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7692.diff">https://git.openjdk.java.net/jdk/pull/7692.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by dholmes-ora — APPROVED** [review]

**Comment by kimbarrett** [comment]
Thanks @tstuefe , @dcubed-ojdk , and @dholmes-ora for reviews.

**Pull request closed without merging**
