### PR TITLE
8317601: Windows build on WSL broken after JDK-8317340

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
[JDK-8317340](https://bugs.openjdk.org/browse/JDK-8317340) introduced -pathmap'ing of VS_INCLUDE paths to enable reproducible Windows builds that are not dependent on the Visual Studio tooling install location. This however requires pathmap'ing the Windows long paths generated by the compiler, which is no easy task within WSL.

This PR excludes the VS include pathmap'ing within WSL, which will mean for reproducible builds on WSL, the same VS install location must be used.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317601](https://bugs.openjdk.org/browse/JDK-8317601): Windows build on WSL broken after JDK-8317340 (**Bug** - P4)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**) ⚠️ Review applies to [f8a74318](https://git.openjdk.org/jdk/pull/16069/files/f8a74318c222379a4ac481d65a42a0a25db3b912)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16069/head:pull/16069` \
`$ git checkout pull/16069`

Update a local copy of the PR: \
`$ git checkout pull/16069` \
`$ git pull https://git.openjdk.org/jdk.git pull/16069/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16069`

View PR using the GUI difftool: \
`$ git pr show -t 16069`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16069.diff">https://git.openjdk.org/jdk/pull/16069.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16069#issuecomment-1750455511)

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
@erikj79 for review please, thanks

**Review by djelinski — APPROVED** [review]
Works for me.

**Review by erikj79 — APPROVED** [review]

**Review by erikj79 — COMMENTED** [review]
Could you add a comment on the new UTIL_FIXUP_WIN_LONG_PATH macro that it only works in cygwin?

**Comment by andrew-m-leonard** [comment]
> Could you add a comment on the new UTIL_FIXUP_WIN_LONG_PATH macro that it only works in cygwin?

Yes, good point. Added

**Pull request closed without merging**
