### PR TITLE
8324834: Use _LARGE_FILES on AIX

### PR DESCRIPTION
**Pull request by magicus**
In the same spirit as [JDK-8318696](https://bugs.openjdk.org/browse/JDK-8318696), we should adapt the AIX-specific code in hotspot so it uses the well-defined posix `<foo>` functions, instead of `<foo>64`. By setting the define _LARGE_FILES, this will make `<foo>` behave as `<foo>64`, just as _FILE_OFFSET_BITS=64 does on gcc. (Reference: https://www.ibm.com/docs/en/aix/7.1?topic=volumes-writing-programs-that-access-large-files)

In theory, it should not even be necessary to set this, since we only compile for 64-bit AIX platforms, and this is only relevant on 32-bit platforms. But let's add the define anyway, for good measure. It shows at least that we have thought about the matter. :-)

I have not been able to test this on AIX. I hope someone with AIX access can take this for a spin.

The reason I'm doing this is for [JDK-8324539](https://bugs.openjdk.org/browse/JDK-8324539). After both these bugs are fixed, there will be no more `<foo>64` function calls in the code base.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324834](https://bugs.openjdk.org/browse/JDK-8324834): Use _LARGE_FILES on AIX (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [36abd7e3](https://git.openjdk.org/jdk/pull/17611/files/36abd7e3504394f74d5e5213f175112ef0cd147f)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [5119bdc9](https://git.openjdk.org/jdk/pull/17611/files/5119bdc96ce3256c375a8ac77586704cc292503b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17611/head:pull/17611` \
`$ git checkout pull/17611`

Update a local copy of the PR: \
`$ git checkout pull/17611` \
`$ git pull https://git.openjdk.org/jdk.git pull/17611/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17611`

View PR using the GUI difftool: \
`$ git pr show -t 17611`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17611.diff">https://git.openjdk.org/jdk/pull/17611.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17611#issuecomment-1914533083)

### CODE REVIEW

**Review by TheShermanTanker — COMMENTED** [review]
I believe this has missed 2 callsites in os\_posix.cpp, which recently swapped to the 64 suffixed variant that is controlled the AIX\_ONLY macro
https://github.com/openjdk/jdk/pull/17587

**Comment by MBaesken** [comment]
> I believe this has missed 2 callsites in os_posix.cpp, which recently swapped to the 64 suffixed variant that is controlled the AIX_ONLY macro #17587

Yes the  2 changes 'overlapped' .

**Comment by MBaesken** [comment]
Using the '_LARGE_FILES' should be okay, I checked this in a small example in the binary and it showed the the 64bit/large file function was used.

**Review by erikj79 — APPROVED** [review]
Build change looks good.

**Comment by JoKern65** [comment]
I have to emphasize, that even when exclusively compiling for 64-bit AIX platforms, the  `<foo>` functions do not support large files. Only the `<foo>64` functions do support large files.
For large file support you can either use the `<foo>64` functions and the `<struct>64` structures explicitly or by compiling all sources with the -D_LARGE_FILES flag which just leads to a redefining of all `<foo>` functions and `<struct>` structures as `<foo>64` functions and `<struct>64` structures.

**Comment by RealCLanger** [comment]
As @TheShermanTanker mentioned, 8950d68ddb36d35831fbb4b98969cd0537527070 should be reverted as part of this change.

**Comment by magicus** [comment]
@JoKern65 Thanks for the information; I did not know that. But the only change it makes is it turns the `-D_LARGE_FILES` from "nice" to "essential" -- the patch remains the same.

**Comment by magicus** [comment]
@MBaesken  @RealCLanger Does this look OK now?

**Comment by RealCLanger** [comment]
Looks good from my end now. I leave the final approval to @MBaesken since he ran this through our testing I believe.

**Comment by MBaesken** [comment]
> Looks good from my end now. I leave the final approval to @MBaesken since he ran this through our testing I believe.

I put it into our build/test queue (so far had only a look at the change).
Unfortunately with going away from the <name>64  functions on AIX, it gets very intransparent. In case we lose the compile flag (or the compile flags gets filtered out/is not set for some compilation unit)  we silently fall back to "short files" support instead of "large files" support.

https://www.ibm.com/docs/en/aix/7.1?topic=volumes-writing-programs-that-access-large-files
"It has the disadvantage of creating some ambiguity in the code because the size of the various data items cannot be determined from looking at the code"

**Comment by magicus** [comment]
The define is set in `CFLAGS_OS_DEF_JVM`, which definitely is passed to the compiler when building hotspot. I suspect this worry of yours were more directed at the change for the JDK, [JDK-8324539](https://bugs.openjdk.org/browse/JDK-8324539): Do not use LFS64 symbols in JDK libs. In that PR, the define is set in `CFLAGS_OS_DEF_JDK`, which also is passed to the compiler for all JDK native libs. (If it weren't, large files on AIX would not be the only thing to break.)

**Comment by magicus** [comment]
And also, to turn this "intransparency" on its head: if someone where to introduce a new call to `open` in a JDK library, with the current solution someone of the AIX maintainers would need to spot it, and change it to a `open64` on AIX. With this new solution, all platforms will work properly with the plain POSIX `open`. I think in the long run, that is going to prove less error-prone.

**Comment by MBaesken** [comment]
> I suspect this worry of yours were more directed at the change for the JDK

Yes it is more a general worry, not especially related to Hotspot.
We could also add some kind of check (e.g. static assert  or configure check) to address it.

**Review by MBaesken — APPROVED** [review]

**Comment by magicus** [comment]
I added a compile-time check that hotspot on AIX is indeed compiled with _LARGE_FILES.

@MBaesken Are you happy with this PR now?

**Pull request closed without merging**
