### PR TITLE
8276058: Some swing test fails on specific CI macos system

### PR DESCRIPTION
**Pull request by prsadhuk**
As per JDK-8252813, some tests fails recurringly in CI macos system. This is an attempt to fix the swing tests.
It was seen from the logs that we have color mismatch in these tests.

For example, in PressedIcon test, we had following log

----------System.out:(1/75)----------
color java.awt.Color[r=55,g=55,b=55] COLOR_1Xjava.awt.Color[r=255,g=0,b=0]
----------System.err:(13/842)----------
java.lang.RuntimeException: Colors is different for scale=1!
	at PressedIconTest.main(PressedIconTest.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)

and JInternalFrame test, we had 
----------System.err:(15/939)----------
FRAME_COLOR Red: 255; Green: 200; Blue: 0
Pixel color Red: 55; Green: 55; Blue: 55
java.lang.RuntimeException: Internal frame is not correctly dragged!
	at bug8069348.main(bug8069348.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)

where color is obtained as 55,55,55 instead of required color. The png image generated at failure also did not reveal anything abnormal apart from presence of mouse cursor around the same area where the getPixelColor location is pointing to. And since mouse cursor is also grayish black, it seems robot was wrongly picking up cursor pixels instead of background color.
Modified tests to use location.x-10, location.y-10 to obtain the pixel color. It does not hamper the test as the whole area around the location is coloured with same color in the test so getting pixel color from a bit wide of the centre will not affect the test.
Modified swing tests are passing in the affected system and also in other macos systems and platforms. Link in JBS.

The awt tests that are failing seems to have different root cause and will be handled separately.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276058](https://bugs.openjdk.java.net/browse/JDK-8276058): Some swing test fails on specific CI macos system

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Alexander Zuev](https://openjdk.java.net/census#kizune) (@azuev-java - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6140/head:pull/6140` \
`$ git checkout pull/6140`

Update a local copy of the PR: \
`$ git checkout pull/6140` \
`$ git pull https://git.openjdk.java.net/jdk pull/6140/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6140`

View PR using the GUI difftool: \
`$ git pr show -t 6140`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6140.diff">https://git.openjdk.java.net/jdk/pull/6140.diff</a>

</details>

### CODE REVIEW

**Comment by prsadhuk** [comment]
I have removed the tolerance chnage and PL-ed the test....Any more comments on this PR?

**Comment by mrserb** [comment]
> I have removed the tolerance change and PL-ed the test....Any more comments on this PR?

If tolerance is not needed and the only issue we have is the visible cursor on the screenshot then why do we try to update the tests, maybe we can try to update the jdk instead?

**Comment by prsadhuk** [comment]
> 
> 
> 
> If tolerance is not needed and the only issue we have is the visible cursor on the screenshot then why do we try to update the tests, maybe we can try to update the jdk instead?

I guess it was already discussed before as below to have the stability improvement in the tests and you agreed to it also but if the stance is changed, I do not have issue in withdrawing this PR.

> > The test part of the fix has multiple stability improvements, and there's no reason to throw that out. And moving the pixel capture position to a more safe position is fine too. I just think that -10 isn't sa\fe enough.
> 
> Sure, I have no comments about the changes related to stability, but there are suspicious cases like using tolerance.

**Comment by prrace** [comment]
I don't see a reason to discard the various stability improvements.
The discussion is long so I may not be summarising correctly but 
- A product fix may resolve most of the issues and yet
- Stability fixes are still valuable
- The one test with a colour tolerance update may be better platform problem listed 
- The offset of -10,-10 for the cursor maybe better if it was parameterised and a bit bigger.

**Comment by prsadhuk** [comment]
I guess the last 2 is already taken care of in latest iteration.

**Comment by mrserb** [comment]
It is a good thing to stabilize the tests and provide additional logging/screenshots at the end, but isn't taking the screenshot out of the mouse is a workaround for the bug?

**Comment by prsadhuk** [comment]
It probably is but will not affect the regression testing of these tests for its specific JBS issues it was written for. Also, the CI system will have to be kept offline till a product fix is found and tested so I think it is prudent to apply this patch to make this CI system usable again...

**Comment by mrserb** [comment]
ok, it is up to you.

**Comment by prsadhuk** [comment]
@prrace Do you have any comments? If not, can you please approve?

**Review by prrace — APPROVED** [review]

**Review by azuev-java — APPROVED** [review]

**Comment by mrserb** [comment]
@prsadhuk @prrace Did we report this to Apple? I have found that some of the tck tests could be unstable due to this, and "CGDisplayHideCursor/CGDisplayShowCursor" may cure it, but probably Apple suggests something else?

**Comment by prrace** [comment]
I can't see that we did but I have now.
One thing that occurred to me is that 
 Settings->Accessibility->Display->Shake mouse pointer to locate
is enabled by default and if our tests "warping" the pointer trigger this then maybe it could be why we see the pointer - I can imagine that the mode for large pointer isn't immediately turned off.
So disabling that setting maybe is worth adding to all our systems

**Pull request closed without merging**
