### PR TITLE
8264605: vmTestbase/nsk/jvmti/SuspendThread/suspendthrd003/TestDescription.java failed with "agent_tools.cpp, 471: (foundThread = (jthread) jni_env->NewGlobalRef(foundThread)) != NULL"

### PR DESCRIPTION
**Pull request by lmesnik**
The agentThread variable might have been set by the new agentThread iteration and then deleted in the wrapper from the previous iteration.

The deletion of agentThread variable should be synced with the termination of the agent thread.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264605](https://bugs.openjdk.java.net/browse/JDK-8264605): vmTestbase/nsk/jvmti/SuspendThread/suspendthrd003/TestDescription.java failed with "agent_tools.cpp, 471: (foundThread = (jthread) jni_env->NewGlobalRef(foundThread)) != NULL"

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6515/head:pull/6515` \
`$ git checkout pull/6515`

Update a local copy of the PR: \
`$ git checkout pull/6515` \
`$ git pull https://git.openjdk.java.net/jdk pull/6515/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6515`

View PR using the GUI difftool: \
`$ git pr show -t 6515`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6515.diff">https://git.openjdk.java.net/jdk/pull/6515.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi Leonid,

I don't think this is sufficient. You have moved the cleanup of the agentThread under the protection of the rawMonitor for termination, but unless the initialization of agentThread is also protected by the rawMonitor then you still have a problem AFAICS.

Cheers,
David

**Comment by lmesnik** [comment]
The new thread is started in nsk_jvmti_runAgentThread which is executed under monitors also as well as nsk_jvmti_resetAgentData. 
Could you please point exact location which is not protected? Seems all thread_state changes and agentThread changes are protected.

**Review by sspitsyn — APPROVED** [review]
Hi Leonid,
It looks good to me.
I see the initialization of agentThread is also protected with the data.monitor. This code is a little bit ugly, so it is not clear that startAgentThreadWrapper is executed under rawMonitor protection.
Thanks,
Serguei

**Comment by dholmes-ora** [comment]
Sorry @lmesnik I missed the higher-level use of the monitor when starting the thread.

**Review by dholmes-ora — APPROVED** [review]

**Comment by lmesnik** [comment]
@dholmes-ora, @sspitsyn - Thank you for the review!

**Pull request closed without merging**
