### PR TITLE
8292022: Issues caused by Unary Plus Operator + and Shift Operators priority

### PR DESCRIPTION
**Pull request by GGGGGHT**
(capacity + capacity>>1) The result of this expression is still capacity. So I guess what the author thought at the time might be (capacity + (capacity >> 1)), see https://bugs.openjdk.org/projects/JDK/issues/JDK-8292022

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292022](https://bugs.openjdk.org/browse/JDK-8292022): Issues caused by Unary Plus Operator + and Shift Operators priority

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9698/head:pull/9698` \
`$ git checkout pull/9698`

Update a local copy of the PR: \
`$ git checkout pull/9698` \
`$ git pull https://git.openjdk.org/jdk pull/9698/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9698`

View PR using the GUI difftool: \
`$ git pr show -t 9698`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9698.diff">https://git.openjdk.org/jdk/pull/9698.diff</a>

</details>

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please send me an e-mail at Dalibor.topic@oracle.com so that I can verify your account's OCA.

**Comment by GGGGGHT** [comment]
> Hi, please send me an e-mail at [Dalibor.topic@oracle.com](mailto:Dalibor.topic@oracle.com) so that I can verify your account's OCA.

I have sent the mail

**Review by shipilev — COMMENTED** [review]
I don't see a reason to over-allocate the 1.5x sized ByteBuffer here. So, if we just drop to ` `ByteBuffer.allocate(capacity)`, it would still resolve the problem, leave the current behavior as it is (obviates the need for deeper testing), and would make more sense anyway. Right?

**Comment by GGGGGHT** [comment]
> I don't see a reason to over-allocate the 1.5x sized ByteBuffer here. So, if we just drop to ` `ByteBuffer.allocate(capacity)`, it would still resolve the problem, leave the current behavior as it is (obviates the need for deeper testing), and would make more sense anyway. Right?

Maybe so, but I think direct allocation of 1.5x size may reduce the number of allocations in some extreme cases.

**Comment by shipilev** [comment]
> Maybe so, but I think direct allocation of 1.5x size may reduce the number of allocations in some extreme cases.

On the other hand, it might also waste memory in general case? I think status quo behavior is okay, and we can just change the code to match it.

**Comment by GGGGGHT** [comment]
> > Maybe so, but I think direct allocation of 1.5x size may reduce the number of allocations in some extreme cases.
> 
> On the other hand, it might also waste memory in general case? I think status quo behavior is okay, and we can just change the code to match it.

You are right, I have re-modified this code.

**Pull request closed without merging**
