### PR TITLE
8265227: Move Proc.java from security/testlibrary to test/lib

### PR DESCRIPTION
**Pull request by wangweij**
I'd like to move this tool to test/lib inside a proper named package.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265227](https://bugs.openjdk.java.net/browse/JDK-8265227): Move Proc.java from security/testlibrary to test/lib

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Xue-Lei Andrew Fan](https://openjdk.java.net/census#xuelei) (@XueleiFan - **Reviewer**) ⚠️ Review applies to 4823a1c6c36f00bfd890172d61fe93d9ec4f4a8d
 * [Rajan Halade](https://openjdk.java.net/census#rhalade) (@rhalade - **Reviewer**)
 * [Sibabrata Sahoo](https://openjdk.java.net/census#ssahoo) (@sisahoo - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3496/head:pull/3496` \
`$ git checkout pull/3496`

Update a local copy of the PR: \
`$ git checkout pull/3496` \
`$ git pull https://git.openjdk.java.net/jdk pull/3496/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3496`

View PR using the GUI difftool: \
`$ git pr show -t 3496`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3496.diff">https://git.openjdk.java.net/jdk/pull/3496.diff</a>

</details>

### CODE REVIEW

**Review by RogerRiggs — COMMENTED** [review]
Good idea. Is there a more evocative class name than Proc?

It looks similar to jdk.test.lib.process.ProcessTools.

Would it fit in the  jdk.test.lib.process package? It would make it easier for non-security testers to find and use?   ( I like the fluid construction)

**Comment by wangweij** [comment]
Well, we can certainly rename it. It's only used by several tests.

And we can certainly move it to a different package. I know it has some duplicate functions with other tools so it will be better to do some cleanup first. The best function of this class is it provides several methods (both for child and parent) to simplify inter-process message transport.

**Comment by RogerRiggs** [comment]
I think is fine to move it first and refactor it separately; that's a bigger job.
If its fit for the purpose, the overlap is fine between tools.

**Review by XueleiFan — APPROVED** [review]
Looks good to me.

**Comment by wangweij** [comment]
Use a different method to find out `-add-exports` and `--add-opens` so there is no need to use an internal method. Otherwise, multiple other tests that have `@build jdk.test.lib.process.*` would fail without the extra `@modules` tag.

**Review by rhalade — APPROVED** [review]

**Review by sisahoo — APPROVED** [review]

**Pull request closed without merging**
