### PR TITLE
Fix the consumed event example in the InputEvent javadoc

### PR DESCRIPTION
**Pull request by ebourg**
The InputEvent javadoc states that:

> For example, consuming mousePressed events on a Button component will prevent the Button from being activated.

But this is not the case, as demonstrated by this simple example:

    public static void main(String[] args) {
        Frame frame = new Frame("TEST");
        frame.setSize(200, 200);
        frame.setVisible(true);
        
        Button button = new Button("CLICK ME");
        button.addActionListener(event -> System.out.println("Button activated"));
        button.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                e.consume();
            }
        });
        
        frame.add(button);
    }

Here the mouse pressed event is consumed by the listener, but the action listener is still triggered. The behavior is the same with the Swing components.

I suggest to change the example to mention the TextField component and the key pressed event. In this case, if a listener consumes the event the component doesn't process it and the field remains unchanged.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4389/head:pull/4389` \
`$ git checkout pull/4389`

Update a local copy of the PR: \
`$ git checkout pull/4389` \
`$ git pull https://git.openjdk.java.net/jdk pull/4389/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4389`

View PR using the GUI difftool: \
`$ git pr show -t 4389`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4389.diff">https://git.openjdk.java.net/jdk/pull/4389.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
What platform did you test? I have run your testcase(some build of jdk17) on macOS and the actionlistener is not called if the event was consumed.

**Comment by ebourg** [comment]
I've tested on Windows 10 with Java 8 and OpenJDK 16, with the example above the mouse listener is called first and consumes the event, but the action listener printing "Button activated" is still called.

**Comment by ebourg** [comment]
@bridgekeeper /bonk

**Comment by mrserb** [comment]
I have tested this on the different platforms, and it looks like on the macOS and Linux it works according the specification, and only on windows it is broken.

**Pull request closed without merging**
