### PR TITLE
8318971: Better Error Handling for Jar Tool Processing of "@File"

### PR DESCRIPTION
**Pull request by ryawalla**
Hi all,

Please review this fix for jar tool not producing an archive if there is a missing file supplied.
The current behaviour will recognise missing files as an error but continue processing,
creating a temporary archive and then deleting it without moving to the current directory.
The fix is to return false when a missing file is supplied and exit immediately without continuing with any wasted processing.

Thanks,
Ryan.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Integration blockers
&nbsp;⚠️ Title mismatch between PR and JBS for issue [JDK-8318971](https://bugs.openjdk.org/browse/JDK-8318971)
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with updated jcheck configuration in pull request)
&nbsp;⚠️ Whitespace errors (failed with updated jcheck configuration in pull request)

### Issue
 * [JDK-8318971](https://bugs.openjdk.org/browse/JDK-8318971): Better Error Handling for Jar Tool When Processing Non-existent Files (**Bug** - P3) ⚠️ Title mismatch between PR and JBS. ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16423/head:pull/16423` \
`$ git checkout pull/16423`

Update a local copy of the PR: \
`$ git checkout pull/16423` \
`$ git pull https://git.openjdk.org/jdk.git pull/16423/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16423`

View PR using the GUI difftool: \
`$ git pr show -t 16423`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16423.diff">https://git.openjdk.org/jdk/pull/16423.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16423#issuecomment-1794459674)

### CODE REVIEW

**Comment by AlanBateman** [comment]
This one probably needs discussion to decide if the JDK 8 or current behavior is the right behavior. Once agreed then we will need to add tests to ensure that the behavior doesn't change, and maybe an update to docs too. Have you dug into the history to see if this behavior change was deliberate or just not noticed before now?

**Comment by ryawalla** [comment]
I had a look and its been in since JDK 9 (https://bugs.openjdk.org/browse/JDK-8158295) but haven’t found any mention of this as a specific desired behaviour so I am going with just noticed now. Its not a major blocker as the user can either make sure the missing file is in place or exclude it from being added to the archive and rerun. 

I agree it will need some thought, I was of the opinion that we should fail upfront and notify the user of why. The JDK 8 behaviour doesn’t make sense as the state is recognised as an error and there are tests to validate this, but they do not validate the archive has not been created, in my opinion we shouldn’t continue on and create it. There are other areas in the jar tool in 8 that will clean up (delete) the archive that has been created if there is an error, this case just seems to fall through the cracks.

**Comment by AlanBateman** [comment]
Thanks for checking the history. A plus to going back to JDK 8 behavior is that it make the `@contents` consistent with the file1, file2, file3 case where one/more of the files doesn't exist or a bad file path is specified. It also means that bugs/issues will be detected quicker. So I think it has positives, it's just that it's changing 6+ year old behavior so we have to be sure.

**Comment by LanceAndersen** [comment]
> I had a look and its been in since JDK 9 (https://bugs.openjdk.org/browse/JDK-8158295) but haven’t found any mention of this as a specific desired behaviour so I am going with just noticed now. Its not a major blocker as the user can either make sure the missing file is in place or exclude it from being added to the archive and rerun.
> 
> I agree it will need some thought, I was of the opinion that we should fail upfront and notify the user of why. The JDK 8 behaviour doesn’t make sense as the state is recognised as an error and there are tests to validate this, but they do not validate the archive has not been created, in my opinion we shouldn’t continue on and create it. There are other areas in the jar tool in 8 that will clean up (delete) the archive that has been created if there is an error, this case just seems to fall through the cracks.

As part of the decision process, we should consider the behavior of what simillar  tools do in this area.  We may also want to discuss the merits of whether there should be an option to toggle the behavior

**Comment by jaikiran** [comment]
Hello Ryan, I ran a few experiments and I am unsure if we should be doing this change. Please consider this following scenario, when using the current implementation in mainline:

```console
echo "hello" > hello.txt
jar -cf foo.jar missing.txt missing2.txt hello.txt

**Comment by ryawalla** [comment]
Thanks [jaikiran](https://github.com/jaikiran), the issue with the current functionality on the mainline is that the jar tool is still processing and creating the temp jar file, it just doesn't move it to the working directory where the tool was ran from because there was a missing file supplied and then deletes the temp jar. If you were to run this with many/larger files that causes the jartool to take more time it is more noticeable. 

Maybe it is better to follow the JDK 8 JarTool behaviour and still produce a jar file without the missing files as we are providing a warning to notify that there were missing files not included in the jar.

**Comment by jaikiran** [comment]
>  the issue with the current functionality on the mainline is that the jar tool is still processing and creating the temp jar file, it just doesn't move it to the working directory where the tool was ran from because there was a missing file supplied and then deletes the temp jar. If you were to run this with many/larger files that causes the jartool to take more time it is more noticeable.

Thank you for that detail. I now understand what we are attempting to improve.

In that case, could you experiment by the changing the call sites of `expand(...)` method? Right now in mainline, `expand(...)` method is where we check if a file exists or not and when absent we write a error message and set the `ok = false`.

The current proposed change in this PR throws an exception from here instead of writing the error message and setting `ok = false`. What we could do perhaps, is let expand(...) method continue to stay as-is and continue to write those error messages and set `ok = false`. Then at the call site(s) of expand() where we then create and write to the temporary jar file, we should probably first check if `ok = false` and if it is `false` then just return `false` from the `run()` method so that the temporary jar isn't created and the command exits with a non-zero exit code. That way we still report all missing files and don't end up creating the temporary jar. I haven't looked at the code in detail to see if this is feasible and/or if there are other issues this will show up.

**Comment by ryawalla** [comment]
Thanks Jaikiran, I have amended the logic and now return false when we hit this scenario and it is working as you expected. It will stop processing when we find a missing file and not produce the jar while showing the existing error message. I agree this is better behaviour. I have updated the changes to reflect this.

**Comment by jaikiran** [comment]
Thank you Ryan for trying this change. There's one more place in run() where we call this expand() and that happens when we want to update the jar file. (Previously) line 340 is where this call to expand() happens. Can you add a similar check after that call there and see if things continue to work?

**Comment by AlanBateman** [comment]
> Added and tested and it still works as expected.

@ryawalla Would it be possible to update the PR description so there's a clear summary on the updated proposal? I think it aligns the behavior with what happens when a bad file path is specified on the jar command line, right?

As I mentioned, we'll need to add tests, release note, and see what docs (jar man page?) need to be updated.

**Comment by jaikiran** [comment]
This has been replaced by https://github.com/openjdk/jdk/pull/17088

**Pull request closed without merging**
