### PR TITLE
8211004: javac is complaining about non-denotable types and refusing to generate the class file

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
Please review this fix which is checking if the enclosing class of an anonymous class is denotable or not. Currently javac is failing with an error at class writing time. All this fix is doing is failing during attribution and trying to issue a better error message so that the user knows better how to fix the issue and the position of the offending code,

TIA

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8211004](https://bugs.openjdk.java.net/browse/JDK-8211004): javac is complaining about non-denotable types and refusing to generate the class file

### Reviewers
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**) ⚠️ Review applies to ed71913635226ed8344fa0b2c3e6f6d408e26381

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6886/head:pull/6886` \
`$ git checkout pull/6886`

Update a local copy of the PR: \
`$ git checkout pull/6886` \
`$ git pull https://git.openjdk.java.net/jdk pull/6886/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6886`

View PR using the GUI difftool: \
`$ git pr show -t 6886`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6886.diff">https://git.openjdk.java.net/jdk/pull/6886.diff</a>

</details>

### CODE REVIEW

**Comment by vicente-romero-oracle** [comment]
ping

**Review by lahodaj — APPROVED** [review]
Looks reasonable.

**Comment by vicente-romero-oracle** [comment]
thanks!

**Pull request closed without merging**
