### PR TITLE
8269516: AArch64: Assembler cleanups

### PR DESCRIPTION
**Pull request by theRealAph**
The core of the AArch64 assembler is unnecessarily complex, with multiple indirections from class Assembler. We can get rid of them, which makes libjvm.so faster and smaller. Also, there are some dubious casts from FloatRegister to Register which should use a proper conversion function.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269516](https://bugs.openjdk.java.net/browse/JDK-8269516): AArch64: Assembler cleanups

### Reviewers
 * [Nick Gasson](https://openjdk.java.net/census#ngasson) (@nick-arm - Committer)
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4612/head:pull/4612` \
`$ git checkout pull/4612`

Update a local copy of the PR: \
`$ git checkout pull/4612` \
`$ git pull https://git.openjdk.java.net/jdk pull/4612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4612`

View PR using the GUI difftool: \
`$ git pr show -t 4612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4612.diff">https://git.openjdk.java.net/jdk/pull/4612.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — COMMENTED** [review]
Tested Linux/AArch64 tier1.

**Review by nick-arm — APPROVED** [review]
Looks OK to me

**Review by adinn — APPROVED** [review]
All looks good

**Pull request closed without merging**
