### PR TITLE
8297534: Specify the size of MEMFLAGS

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi!

In MallocHeader we assume that MEMFLAGS can be stored in a uint8_t, see:

```c++
class MallocHeader {

  NOT_LP64(uint32_t _alt_canary);
  const size_t _size;
  const uint32_t _mst_marker;
  const uint8_t _flags;
  const uint8_t _unused;
  uint16_t _canary;
// SNIP!
  inline MEMFLAGS flags() const { return (MEMFLAGS)_flags; }
```

With C++11 we can specify the underlying type of an `enum class`, so let's just do that. If we generate 257 memflags we'll get a compile error. I don't believe that this would lead to any change in the behavior of the code.

Testing: Compiled the code. Running tier1 testing right now.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297534](https://bugs.openjdk.org/browse/JDK-8297534): Specify the size of MEMFLAGS

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [046f6abc](https://git.openjdk.org/jdk/pull/11336/files/046f6abc2c85bb58f5b06a9553b2571e1ab51ed3)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [ce9a1d24](https://git.openjdk.org/jdk/pull/11336/files/ce9a1d243af1abb482b21eba5f3460d8992b8df1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11336/head:pull/11336` \
`$ git checkout pull/11336`

Update a local copy of the PR: \
`$ git checkout pull/11336` \
`$ git pull https://git.openjdk.org/jdk pull/11336/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11336`

View PR using the GUI difftool: \
`$ git pr show -t 11336`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11336.diff">https://git.openjdk.org/jdk/pull/11336.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Good and trivial.

**Review by tschatzl — CHANGES_REQUESTED** [review]
Imo the `_flags` member of `MallocHeader` should then also be of type `MEMFLAGS` as it is now defined what size it is. That saves some casting around in related code too.
I tried the change and it at least compiled, and do not see a reason not to.

**Comment by jdksjolen** [comment]
> Imo the `_flags` member of `MallocHeader` should then also be of type `MEMFLAGS` as it is now defined what size it is. That saves some casting around in related code too. I tried the change and it at least compiled, and do not see a reason not to.

Oh yeah, I agree.

**Review by tstuefe — COMMENTED** [review]
Hmm, I can live with that, though I would have preferred the raw type for clarity. After all, enum should follow the layout of the header, not the other way around.

Can you at least add a static assert that sizeof memflags is 8 bits?

**Review by tstuefe — COMMENTED** [review]
Hmm, I can live with that, though I would have preferred the raw type for clarity. After all, enum should follow the layout of the header, not the other way around.

Can you at least add a static assert that sizeof memflags is 8 bits?

**Comment by jdksjolen** [comment]
> Hmm, I can live with that, though I would have preferred the raw type for clarity. After all, enum should follow the layout of the header, not the other way around.
> 
> Can you at least add a static assert that sizeof memflags is 8 bits?

Absolutely. Would you like that right after the definition of MEMFLAGS then?

**Comment by tstuefe** [comment]
> > Hmm, I can live with that, though I would have preferred the raw type for clarity. After all, enum should follow the layout of the header, not the other way around.
> > Can you at least add a static assert that sizeof memflags is 8 bits?
> 
> Absolutely. Would you like that right after the definition of MEMFLAGS then? (and not after the definition of `MEMFLAGS _flags` in the header)

I don't care much as long as it explodes when MEMFLAGS are changed :-) If you add it to the hpp file, you need to give it debug.hpp too. I leave it up to you.

**Comment by jdksjolen** [comment]
Alright, I added it to `allocation.hpp` with a small comment. Right now gcc gives the type error in the enum definition precedence, which gives you nicer error messages. I also ensured that the static assert gives a compiler error (by removing the enum type first), which it does.

**Comment by tstuefe** [comment]
Still good.

**Comment by jdksjolen** [comment]
/integrate

Thank you for the reviews!

**Pull request closed without merging**
