### PR TITLE
8255013: implement Record Classes as a standard feature in Java, follow-up

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
Hi,

I made the mistake of pushing the fix for [JDK-8246774](https://bugs.openjdk.java.net/browse/JDK-8246774) too soon and had to delta-apply it. This PR is basically proposing to push the same code as [PR-290](https://github.com/openjdk/jdk/pull/290),

Thanks and sorry for the unnecessary loop,
Vicente

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255013](https://bugs.openjdk.java.net/browse/JDK-8255013): implement Record Classes as a standard feature in Java, follow-up

### Reviewers
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**) ⚠️ Review applies to ce1acfcefa573da4d5565d8b62a4461f36fa8b84

### Contributors
 * Vicente Romero `<vromero@openjdk.org>`
 * Harold Seigel `<hseigel@openjdk.org>`
 * Chris Hegarty `<chegar@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/769/head:pull/769`
`$ git checkout pull/769`

### CODE REVIEW

**Review by lahodaj — APPROVED** [review]

**Comment by vicente-romero-oracle** [comment]
we are going live!!! go records!!!

**Pull request closed without merging**
