### PR TITLE
8274471: Verification of OCSP Response signed with RSASSA-PSS fails

### PR DESCRIPTION
**Pull request by wangweij**
Extra parameters need to be set for RSASSA-PSS signatures. We already have a helper method for that.

Some other cleanups:
1. When using GET for OCSP, make sure no double slash.
2. Several throws clauses are not necessary.

No regression test. OCSP needs to access an external server.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274471](https://bugs.openjdk.java.net/browse/JDK-8274471): Verification of OCSP Response signed with RSASSA-PSS fails

### Reviewers
 * [Hai-May Chao](https://openjdk.java.net/census#hchao) (@haimaychao - Committer)
 * [Jamil Nimeh](https://openjdk.java.net/census#jnimeh) (@jnimeh - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5778/head:pull/5778` \
`$ git checkout pull/5778`

Update a local copy of the PR: \
`$ git checkout pull/5778` \
`$ git pull https://git.openjdk.java.net/jdk pull/5778/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5778`

View PR using the GUI difftool: \
`$ git pr show -t 5778`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5778.diff">https://git.openjdk.java.net/jdk/pull/5778.diff</a>

</details>

### CODE REVIEW

**Review by haimaychao — COMMENTED** [review]
As throwing ProviderException is removed from initVerifyWithParam(), could we remove the ProviderException in the try-catch block from the callers of initVerifyWithParam()? For example, one of the callers at:
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/pkcs/SignerInfo.java#L476

**Comment by wangweij** [comment]
> As throwing ProviderException is removed from initVerifyWithParam(), could we remove the ProviderException in the try-catch block from the callers of initVerifyWithParam()? For example, one of the callers at:
> https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/pkcs/SignerInfo.java#L476

`ProviderException` is a `RuntimeException`, so removing it from the method signature does not mean the method will not throw it. Therefore, removing those catch blocks might lead to behavior changes. I'd rather not touch them.

**Comment by wangweij** [comment]
New commit to disallow a verifier `Signature` be created directly from algorithm and key and initialized with a default parameters. For verifiers, params must be provided explicitly (if needed); otherwise, it's an error. Fortunately no code is using this function at the moment.

**Review by haimaychao — APPROVED** [review]
Looks good.

**Review by jnimeh — APPROVED** [review]
Looks good.  I like the algorithm agility enhancements to SimpleOCSPServer and CertificateBuilder.

**Pull request closed without merging**
