### PR TITLE
8142984: Zero: fast accessors should handle both getters and setters

### PR DESCRIPTION
**Pull request by shipilev**
It started as removing the TODO item in `abstractInterpreter.cpp`. Zero is the only implementation that treats `accessor` to mean `getter`, which makes the awkward choice in the entry selection. After going back and forth (including trying to remove the fast accessor methods altogether in [JDK-8255066](https://bugs.openjdk.java.net/browse/JDK-8255066)), I settled on implementing the fast Zero `setter`-s too, plus renaming and whipping the existing `getter` code in shape. The end result seems to be more straight-forward than it was before.

On the plus side, it improves `make bootcycle-images` in release mode from ~47m40s to ~46m50s, because we are saving time doing the `normal_entry` for setters.

The "normal", non-Zero template interpreter is not affected, because it does not have any specializations for `accessor`, `getter` or `setter`, and instead just doing the normal entry.

Testing:
  - [x] Linux x86_64 {fastdebug, release} Zero `make bootcycle-images`
  - [x] Linux aarch64 {fastdebug, release} Zero `make bootcycle-images`
  - [x] Linux x86_64 Zero release jcstress
  - [x] Linux aarch64 Zero release jcstress

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8142984](https://bugs.openjdk.java.net/browse/JDK-8142984): Zero: fast accessors should handle both getters and setters

### Reviewers
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/728/head:pull/728`
`$ git checkout pull/728`

### CODE REVIEW

**Review by gnu-andrew — APPROVED** [review]
Looks good to me.

**Comment by shipilev** [comment]
@coleenp or other runtime folks might want to take a look as well?

**Comment by shipilev** [comment]
Anyone else? :)

**Review by coleenp — APPROVED** [review]
Looks good to me.  For Zero, I suppose these methods improve performance by a lot.

**Comment by shipilev** [comment]
Thanks @gnu-andrew and @coleenp. Yes, these improve Zero performance quite significantly, along with cleaning up some TODOs in shared code. Seems like win-win.

/integrate

**Comment by shipilev** [comment]
> _Mailing list message from [Coleen Phillimore](mailto:coleen.phillimore@oracle.com) on [hotspot-dev](mailto:hotspot-dev@openjdk.java.net):_
> 
> On 11/19/20 12:40 PM, Aleksey Shipilev wrote:
> 
> There's an #if 0 in zeroInterpreter_zero.cpp that you can trivially
> remove also.

D'oh. It does not seem related, thankfully. I'll file another issue to remove that block.

**Pull request closed without merging**
