### PR TITLE
8256430: add linux-x64-optimized to regular testing

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

[8256414](https://bugs.openjdk.java.net/browse/JDK-8256414) /  #1233 added similar profile to submit workflow, this patch defines `linux-x64-optimized` profile in jib-profile so it can be used by mach5 and added to tier1? 

Thanks
-- Igor

/label hotspot-compiler hotspot build
cc-ing @dcubed-ojdk

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ⏳ (3/5 running) | ⏳ (2/2 running) | ⏳ (2/2 running) | ⏳ (2/2 running) |

### Issue
 * [JDK-8256430](https://bugs.openjdk.java.net/browse/JDK-8256430): add linux-x64-optimized to regular testing

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 05c735be7c4baf9fc61f4baf3e1e712729894091
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 05c735be7c4baf9fc61f4baf3e1e712729894091
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to 05c735be7c4baf9fc61f4baf3e1e712729894091
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1244/head:pull/1244`
`$ git checkout pull/1244`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Review by erikj79 — APPROVED** [review]

**Comment by iignatev** [comment]
folks, thanks for your reviews.

/integrate

**Pull request closed without merging**
