### PR TITLE
JDK-8232092 (fs) Files::isWritable returns false on a writeable root directory (win)

### PR DESCRIPTION
**Pull request by nhat-nguyen**
I'm following up on the reviewing thread here: https://mail.openjdk.java.net/pipermail/nio-dev/2020-August/007456.html

All the tests that create symlinks are now properly checked against using `TestUtil.supportsLinks`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8232092](https://bugs.openjdk.java.net/browse/JDK-8232092): (fs) Files::isWritable returns false on a writeable root directory (win)

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/287/head:pull/287`
`$ git checkout pull/287`

### CODE REVIEW

**Review by AlanBateman — COMMENTED** [review]
The update to WindowsFileStore looks okay.

The test has good coverage but I worry that creating X: will not be reliable in some CI environments, esp. if X: exists already or permissions are needed. I'll try your test in our CI and would be good if others did the same.

One terminology nit is that the file system API uses the term "directory". The test uses a mix of "directory" and "folder" would be good to keep it consistent if possible.

I don't think the addition to TestUtil is needed, the createRootTempDirectory method can call Files.createTmpDirectory.

Many of the existing TestNG tests import statically Asserts and could be done here too.

substList should return Stream<Srring>, we try to avoid raw types.

No need to import java.lang.ProcessBuilder, also would be good to clean import the imports, no need for a space between each java.* package.

**Comment by nhat-nguyen** [comment]
> _Mailing list message from [Alan Bateman](mailto:Alan.Bateman@oracle.com) on [nio-dev](mailto:nio-dev@openjdk.java.net):_
> 
> On 24/09/2020 10:52, Alan Bateman wrote:
> 
> > :
> > The test has good coverage but I worry that creating X: will not be reliable in some CI environments, esp. if X: exists
> > already or permissions are needed. I'll try your test in our CI and would be good if others did the same.
> 
> I tried it in our CI and testRealPath fails consistently on all Windows
> clients.? This is JDK-8213216 rather than JDK-8232092. I know Brian was
> looking at JDK-8213216 at one point but we didn't come to a conclusion
> on supporting the scenario without creating inconsistencies. So maybe
> this test should be dropped from SubstDrive.
> 
> -Alan

Thank you Alan for catching this. This is an oversight on my end. I wrote `testRealPath` with the intention that if Brian ever fixes jdk-8213216, he can use this test; unfortunately I forgot to disable it. I have dropped this test case from the test altogether to prevent any future confusion.

> One terminology nit is that the file system API uses the term "directory". The test uses a mix of "directory" and "folder" would be good to keep it consistent if possible.
Fixed!

> I don't think the addition to TestUtil is needed, the createRootTempDirectory method can call Files.createTmpDirectory.
Fixed!
 
> Many of the existing TestNG tests import statically Asserts and could be done here too.
Fixed!

> No need to import java.lang.ProcessBuilder, also would be good to clean import the imports, no need for a space between each java.* package.
Fixed!

> substList should return Stream, we try to avoid raw types.
I'm sorry I'm a bit confused by this. Did you mean to say "should not return stream"? substList returns Stream<String> and not raw Stream. If the convention is try not to return Stream<> at all, I have converted the method to return List<> instead (I made substList return Stream in the first place because I wanted to call anyMatch() on the return result). Please let me know if this is what you expected. 😄

**Comment by AlanBateman** [comment]
The updated test looks much better and passes in our infrastructure since the remove of the toRealPath test. I'm still bothered by the hardcoded "X:". Does subst (and hence substCreate) fail if that volume already exists?

substList can be changed to return List<String>.

**Comment by nhat-nguyen** [comment]
> The updated test looks much better and passes in our infrastructure since the remove of the toRealPath test. I'm still bothered by the hardcoded "X:". Does subst (and hence substCreate) fail if that volume already exists?

subst will fail if that volume already exists. I have added a method to find any available drive to be used with subst; it simply tries calling substCreate with drive letters from Z down to A. If none is available, it will throw a SkipException to skip the whole suite.

> substList can be changed to return List.

What is your opinion on substList returning Stream<String> like you mentioned before? I think it is perhaps cleaner than List<String> because I would call .anyMatch() which is a stream API on the return value of substList.

**Comment by AlanBateman** [comment]
I see the latest version will attempt to find an unused driver letter. I'll try that out now in our infrastructure to make sure that it is stable.

substList returning a Stream is good but it should be Stream<String> rather than just "Stream". Also the method name and comment suggests is returns a List, maybe it should just be renamed to mappedDrives to be a bit clearer. The new findAvailableDrive is also missing the type variable, I think you want Optional<Path> here.

**Comment by nhat-nguyen** [comment]
> substList returning a Stream is good but it should be Stream rather than just "Stream". Also the method name and comment suggests is returns a List, maybe it should just be renamed to mappedDrives to be a bit clearer. The new findAvailableDrive is also missing the type variable, I think you want Optional here.

Thanks Alan for the feedback. I think there's a problem with how webrev is being generated. I have been a bit confused by your comments on the usage of raw types because I actually have them from the beginning. I just double checked the webrevs and they are indeed missing. However, if you look at the Github diff, you will see that I'm using both Stream<String> and Optional<Path>.

**Comment by AlanBateman** [comment]
Indeed, it seems to be interpreting the tags as if they are HTML so looked to me that you were using raw types everyone. Sorry I didn't notice this.

The updated changes look good and happy to sponsor.

**Review by AlanBateman — APPROVED** [review]

**Comment by nhat-nguyen** [comment]
> Indeed, it seems to be interpreting the tags as if they are HTML so looked to me that you were using raw types everyone. Sorry I didn't notice this.
> 
> The updated changes look good and happy to sponsor.

Thank you for all the suggestions!

**Comment by sormuras** [comment]
Wohoo! Next Windows-related bug down.

**Pull request closed without merging**
