### PR TITLE
8330008: [s390x] Test bit "in-memory" in case of DiagnoseSyncOnValueBasedClasses

### PR DESCRIPTION
**Pull request by offamitkumar**
It's trivial update to use `testbit` method to test the bit "in-memory"

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330008](https://bugs.openjdk.org/browse/JDK-8330008): [s390x] Test bit "in-memory" in case of DiagnoseSyncOnValueBasedClasses (**Bug** - P4)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to [127ea97d](https://git.openjdk.org/jdk/pull/18709/files/127ea97db17fdb8a167754da87abc70544f19e49)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18709/head:pull/18709` \
`$ git checkout pull/18709`

Update a local copy of the PR: \
`$ git checkout pull/18709` \
`$ git pull https://git.openjdk.org/jdk.git pull/18709/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18709`

View PR using the GUI difftool: \
`$ git pr show -t 18709`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18709.diff">https://git.openjdk.org/jdk/pull/18709.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18709#issuecomment-2048929480)

### CODE REVIEW

**Comment by offamitkumar** [comment]
@RealLucy would be best if you could take a look at this one as well :-)

**Review by RealLucy — APPROVED** [review]
Hi @RealLucy, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user RealLucy" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Comment by offamitkumar** [comment]
This one also seems a trivial change; Should I wait of another review or integrate.

**Comment by offamitkumar** [comment]
I have done testing with `DiagnoseSyncOnValueBasedClasses=1`.

This test failure I got, but it's failing on master branch as well if we are using same argument:
```
STDOUT:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/amit/mr/jdk/src/hotspot/share/runtime/synchronizer.cpp:485), pid=3628970, tid=3628992
#  fatal error: Synchronizing on object 0x00000000ffe583c8 of klass java.lang.Integer at SplitIfSharedFastLockBehindCastPP.test2(SplitIfSharedFastLockBehindCastPP.java:92)
#
# JRE version: OpenJDK Runtime Environment (23.0) (fastdebug build 23-internal-adhoc.amit.jdk)
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 23-internal-adhoc.amit.jdk, mixed mode, sharing, compressed oops, compressed class ptrs, g1 gc, linux-s390x)
# Problematic frame:
# V  [libjvm.so+0x12b4b8c]  ObjectSynchronizer::handle_sync_on_value_based_class(Handle, JavaThread*)+0x944
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/amit/mr/jdk/build/linux-s390x-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_compiler_loopopts_SplitIfSharedFastLockBehindCastPP_java/scratch/0/core.3628970)
#
# An error report file with more information is saved as:
# /home/amit/mr/jdk/build/linux-s390x-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_compiler_loopopts_SplitIfSharedFastLockBehindCastPP_java/scratch/0/hs_err_pid3628970.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by offamitkumar** [comment]
@TheRealMDoerr would you please provide a second review here.

**Review by TheRealMDoerr — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
> I have done testing with `DiagnoseSyncOnValueBasedClasses=1`.
> 
> This test failure I got, but it's failing on master branch as well if we are using same argument:
> 
> ```
> STDOUT:
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (/home/amit/mr/jdk/src/hotspot/share/runtime/synchronizer.cpp:485), pid=3628970, tid=3628992
> #  fatal error: Synchronizing on object 0x00000000ffe583c8 of klass java.lang.Integer at SplitIfSharedFastLockBehindCastPP.test2(SplitIfSharedFastLockBehindCastPP.java:92)
> #
> # JRE version: OpenJDK Runtime Environment (23.0) (fastdebug build 23-internal-adhoc.amit.jdk)
> # Java VM: OpenJDK 64-Bit Server VM (fastdebug 23-internal-adhoc.amit.jdk, mixed mode, sharing, compressed oops, compressed class ptrs, g1 gc, linux-s390x)
> # Problematic frame:
> # V  [libjvm.so+0x12b4b8c]  ObjectSynchronizer::handle_sync_on_value_based_class(Handle, JavaThread*)+0x944
> #
> # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/amit/mr/jdk/build/linux-s390x-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_compiler_loopopts_SplitIfSharedFastLockBehindCastPP_java/scratch/0/core.3628970)
> #
> # An error report file with more information is saved as:
> # /home/amit/mr/jdk/build/linux-s390x-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_compiler_loopopts_SplitIfSharedFastLockBehindCastPP_java/scratch/0/hs_err_pid3628970.log
> #
> # If you would like to submit a bug report, please visit:
> #   https://bugreport.java.com/bugreport/crash.jsp
> #
> ```

That should get investigated in a new JBS issue.

**Comment by offamitkumar** [comment]
I have opened issue here: https://bugs.openjdk.org/browse/JDK-8330696

Should I integrate this one ?

**Comment by RealLucy** [comment]
> Should I integrate this one ?

Go! The observed crash is obviously unrelated to your change.

**Comment by theRealAph** [comment]
> > Should I integrate this one ?
> 
> Go! The observed crash is obviously unrelated to your change.

It's not a crash, it's a diagnostic for synchronizing on a value-based class, as requested. Given that the test case actually is synchronizing on a value-based class, this is a correct diagnostic message.

**Pull request closed without merging**
