### PR TITLE
8319900: Recursive lightweight locking: riscv64 implementation

### PR DESCRIPTION
**Pull request by zifeihan**
Implementation of recursive lightweight JDK-8319796 for linux-riscv64.

### Correctness testing:

- [x]  Run tier1-3, hotspot:tier4 tests with -XX:LockingMode=1 & -XX:LockingMode=2 on LicheePI 4A (release)
- [x]  Run tier1-3 tests with -XX:LockingMode=1 & -XX:LockingMode=2 on qemu 8.1.0 (fastdebug)

### JMH tested on LicheePI 4A:

```
Before (LockingMode = 2):

Benchmark                                (innerCount)  Mode  Cnt       Score      Error  Units
LockUnlock.testContendedLock                      100  avgt   12     281.603 ±    2.626  ns/op
LockUnlock.testRecursiveLockUnlock                100  avgt   12  196373.917 ± 4669.241  ns/op
LockUnlock.testRecursiveSynchronization           100  avgt   12     274.492 ±    6.049  ns/op
LockUnlock.testSerialLockUnlock                   100  avgt   12   11516.092 ±   69.964  ns/op
LockUnlock.testSimpleLockUnlock                   100  avgt   12   11490.789 ±   58.833  ns/op

After (LockingMode = 2):

Benchmark                                (innerCount)  Mode  Cnt      Score    Error  Units
LockUnlock.testContendedLock                      100  avgt   12    307.013 ±  3.259  ns/op
LockUnlock.testRecursiveLockUnlock                100  avgt   12  59047.222 ± 94.748  ns/op
LockUnlock.testRecursiveSynchronization           100  avgt   12    259.789 ±  1.698  ns/op
LockUnlock.testSerialLockUnlock                   100  avgt   12   6055.775 ± 13.518  ns/op
LockUnlock.testSimpleLockUnlock                   100  avgt   12   6090.986 ± 67.179  ns/op
```

```
Before (LockingMode = 1):

Benchmark                                (innerCount)  Mode  Cnt      Score     Error  Units
LockUnlock.testContendedLock                      100  avgt   12    286.144 ±   2.490  ns/op
LockUnlock.testRecursiveLockUnlock                100  avgt   12  68058.259 ± 286.262  ns/op
LockUnlock.testRecursiveSynchronization           100  avgt   12    263.132 ±   4.075  ns/op
LockUnlock.testSerialLockUnlock                   100  avgt   12   7521.777 ±  35.193  ns/op
LockUnlock.testSimpleLockUnlock                   100  avgt   12   7522.480 ±  26.310  ns/op

After (LockingMode = 1):

Benchmark                                (innerCount)  Mode  Cnt      Score     Error  Units
LockUnlock.testContendedLock                      100  avgt   12    289.034 ±   5.821  ns/op
LockUnlock.testRecursiveLockUnlock                100  avgt   12  68474.370 ± 495.135  ns/op
LockUnlock.testRecursiveSynchronization           100  avgt   12    261.052 ±   4.560  ns/op
LockUnlock.testSerialLockUnlock                   100  avgt   12   7513.187 ±  19.524  ns/op
LockUnlock.testSimpleLockUnlock                   100  avgt   12   7461.287 ± 118.634  ns/op
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319900](https://bugs.openjdk.org/browse/JDK-8319900): Recursive lightweight locking: riscv64 implementation (**Sub-task** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [4bea5ddc](https://git.openjdk.org/jdk/pull/17554/files/4bea5ddccef534a605645d60835019a7a2f1887d)

### Contributors
 * Axel Boldt-Christmas `<aboldtch@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17554/head:pull/17554` \
`$ git checkout pull/17554`

Update a local copy of the PR: \
`$ git checkout pull/17554` \
`$ git pull https://git.openjdk.org/jdk.git pull/17554/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17554`

View PR using the GUI difftool: \
`$ git pr show -t 17554`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17554.diff">https://git.openjdk.org/jdk/pull/17554.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17554#issuecomment-1963223193)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
This looks pretty good. Thanks.

**Comment by zifeihan** [comment]
@RealFYang : Thanks for your review.
/integrate

**Pull request closed without merging**
