### PR TITLE
JDK-8325148: Enable restricted javac warning in java.base

### PR DESCRIPTION
**Pull request by jddarcy**
The restricted javac warning is disabled for java.base, but could be enabled by suppressing the warning in a handful of files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325148](https://bugs.openjdk.org/browse/JDK-8325148): Enable restricted javac warning in java.base (**Enhancement** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [4973b1fb](https://git.openjdk.org/jdk/pull/17677/files/4973b1fb8c4916de475f3cdac82ff04bfc5c3534)
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**) ⚠️ Review applies to [4973b1fb](https://git.openjdk.org/jdk/pull/17677/files/4973b1fb8c4916de475f3cdac82ff04bfc5c3534)
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)
 * [Per Minborg](https://openjdk.org/census#pminborg) (@minborg - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17677/head:pull/17677` \
`$ git checkout pull/17677`

Update a local copy of the PR: \
`$ git checkout pull/17677` \
`$ git pull https://git.openjdk.org/jdk.git pull/17677/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17677`

View PR using the GUI difftool: \
`$ git pr show -t 17677`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17677.diff">https://git.openjdk.org/jdk/pull/17677.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17677#issuecomment-1922259202)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by JornVernee — APPROVED** [review]
This looks good to me. It will be easier to find where we are doing restricted operations like this.

**Comment by jddarcy** [comment]
> This looks good to me. It will be easier to find where we are doing restricted operations like this.

Right; follows the recommended approach of minimizing the scope of the SuppressWarnings annotations too. Thanks.

**Review by mcimadamore — APPROVED** [review]
Looks good - a pity that we cannot disable the warning at the package level - I think it would make sense give blanket approval to the FFM implementation classes. But, even like this it's not too bad. Thanks.

**Review by minborg — APPROVED** [review]
Nice fix. Thanks.

**Review by magicus — APPROVED** [review]
Great, thanks for cleaning up!

**Pull request closed without merging**
