### PR TITLE
8285405: add test and check for negative argument to HashMap::newHashMap et al

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which addresses https://bugs.openjdk.java.net/browse/JDK-8285405?

I've added the test for `LinkedHashMap.newLinkedHashMap(int)` in the existing `test/jdk/java/util/LinkedHashMap/Basic.java` since that test has tests for various APIs of this class.

For `WeakHashMap.newWeakHashMap` and `HashMap.newHashMap`, I have created new test classes under relevant locations, since these classes already have test classes (almost) per API/feature in those locations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285405](https://bugs.openjdk.org/browse/JDK-8285405): add test and check for negative argument to HashMap::newHashMap et al

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to [9ccebd79](https://git.openjdk.org/jdk/pull/9036/files/9ccebd79196732690ccc0a102a5e89f0ca99fe31)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9036/head:pull/9036` \
`$ git checkout pull/9036`

Update a local copy of the PR: \
`$ git checkout pull/9036` \
`$ git pull https://git.openjdk.org/jdk pull/9036/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9036`

View PR using the GUI difftool: \
`$ git pr show -t 9036`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9036.diff">https://git.openjdk.org/jdk/pull/9036.diff</a>

</details>

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Comment by stuart-marks** [comment]
Note that I've integrated [JDK-8284780](https://bugs.openjdk.org/browse/JDK-8284780) (HashSet static factories) so maybe this PR could be updated with tests for those as well.

**Comment by jaikiran** [comment]
Hello Stuart, I'll include tests for those in this PR shortly.

**Comment by jaikiran** [comment]
I've now update the PR to include tests for `HashSet.newHashSet` and `LinkedHashSet.newLinkedHashSet` APIs. Additionally, their implementation too have has been modified to do the necessary negative param check. The copyright year on the `LinkedHashSet.java` file has also been updated accordingly.

P.S: Please ignore the bot message which talks about rebase/force-push. No rebase or force-push was done (only the recommended merge command was used to merge with latest master branch). I will check with the relevant team to see if there's some bug in the bot which generates that message. I have seen that happen recently on few other PRs as well.

**Review by stuart-marks — COMMENTED** [review]
Changes to the files in src are all fine.

I've made a couple individual comments on the NewHashMap.java test. But modifying two files and adding three new files seems rather bulky for what is essentially five copies of the same test. Perhaps they should be consolidated. They could all be written in a single file using a single data provider for five different test methods. (They could even be written as a combo test with a data provider that provides the factory method to call, but that seems like excess complexity.)

I'd suggest adding the data provider and test cases to HashMap/WhiteBoxResizeTest. That test is already testing the factory methods for the five implementations to ensure the right capacity is allocated. Testing them for negative values is only a small step beyond that.

A combo test of {-1, -42, MIN_VALUE} x { newHM, newLHM, ... } doesn't seem to me to warrant the complexity that would entail. Testing different negative values doesn't add much. I'd suggest having a data provider that provides the different factory methods as an IntFunction and then just passes -1 and ensures that the exception is thrown.

**Comment by jaikiran** [comment]
Work is in progress, I'll be reviving this shortly.

**Pull request closed without merging**
