### PR TITLE
8294751: Zero: Allow larger default heaps

### PR DESCRIPTION
**Pull request by shipilev**
Zero is currently defaulting to `MaxRAM=1G` on all machines. It is set in `compiler_globals.pd` under `#if !defined(COMPILER1) && !defined(COMPILER2) && !INCLUDE_JVMCI`.

Zero supports lots of GCs, and there is little sense to penalize it unnecessarily with too small heaps. After [JDK-8292847](https://bugs.openjdk.org/browse/JDK-8292847), this would allow G1 with reasonable heap size on most machines.

Motivational improvements, `SPECjvm2008:serial`:

```
# Baseline, G1
Serial.test  thrpt   10  1619.863 ± 16.694  ops/s

# Baseline, Serial
Serial.test  thrpt   10  1094.438 ± 20.425  ops/s

# Patched, G1
Serial.test  thrpt   10  1623.090 ± 17.553  ops/s

# Patched, Serial
Serial.test  thrpt   10  1624.531 ± 15.792  ops/s  ; <---- matches G1 now, because young is not tiny
```

Before:

```
$ build/linux-x86_64-zero-release/jdk/bin/java -Xlog:gc -Xlog:gc+init Alloc.java
[0.003s][info][gc     ] Using G1
...
[0.005s][info][gc,init] Memory: 125G
...
[0.005s][info][gc,init] Heap Region Size: 1M
[0.005s][info][gc,init] Heap Min Capacity: 8M
[0.005s][info][gc,init] Heap Initial Capacity: 16M
[0.005s][info][gc,init] Heap Max Capacity: 256M
```

After:

```
$ build/linux-x86_64-zero-release/jdk/bin/java -Xlog:gc -Xlog:gc+init Alloc.java
[0.003s][info][gc     ] Using G1
...
[0.007s][info][gc,init] Memory: 125G
...
[0.007s][info][gc,init] Heap Region Size: 16M
[0.007s][info][gc,init] Heap Min Capacity: 16M
[0.007s][info][gc,init] Heap Initial Capacity: 2016M
[0.007s][info][gc,init] Heap Max Capacity: 30208M
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294751](https://bugs.openjdk.org/browse/JDK-8294751): Zero: Allow larger default heaps

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10552/head:pull/10552` \
`$ git checkout pull/10552`

Update a local copy of the PR: \
`$ git checkout pull/10552` \
`$ git pull https://git.openjdk.org/jdk pull/10552/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10552`

View PR using the GUI difftool: \
`$ git pr show -t 10552`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10552.diff">https://git.openjdk.org/jdk/pull/10552.diff</a>

</details>

### CODE REVIEW

**Comment by iklam** [comment]
Do we need to overhaul the other combinations as well? I don't see why we have to artificially limit the heap sizes. Here's the pd value for MaxRAM, which is defined identically for all platforms:

- no C2  = 1GB
- C2 on 32-bit = 4GB
- C2 on 64-bit = 128 GB

Also, if you want to do it for only ZERO for now, I think it's better to set the value inside compiler_globals_pd.hpp

```
#ifdef ZERO
define_pd_global(uint64_t,MaxRAM,                    128ULL*G);
#else 
define_pd_global(uint64_t,MaxRAM,                    1ULL*G);
#endif
```

**Comment by shipilev** [comment]
> Do we need to overhaul the other combinations as well? I don't see why we have to artificially limit the heap sizes. 

Probably. But as always with ergonomics, it might have unintended consequences.
 
> Also, if you want to do it for only ZERO for now, I think it's better to set the value inside compiler_globals_pd.hpp

Yeah, @tstuefe asked about this in the previous PR too. Let's move both flags to that `.hpp` then. See new commit.

**Comment by shipilev** [comment]
GHA re-run returned green. Yet, this PR checks report some failures. This is an infrastructure hiccup.

@tstuefe, the move of these checks to header definitions -- that is what you wanted to see, right?

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
