### PR TITLE
JDK-8248320: Provide a unique accessible name for <nav role="navigation">

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
This change is primarily about removing the lower (bottom) instance of the navigation bar, but as a side effect, it is also a cleanup for the way that the `<header>` and `<footer>` elements are generated for each page.

The header and footer elements are now generated by two new methods on `HtmlDocletWriter`: `getHeader` and `getFooter`. 

The footer is the same for all pages, and now just consists of the "bottom" text (if any) provided with the `-bottom` option. (In JDK API docs, this is all the legal text at the bottom of each page.)  The footer is omitted if there is no bottom text. 

The header is structurally the same for each page, consisting of the "top" text (if any) provided with the `-top` option, and the main navigation bar. The contents of the navigation bar does depend on the kind of page, and so it is generated by a new method `getNavBar`, which is overridden as needed for some pages, to properly customize the properties.

Since there is no longer a lower navbar, the `-footer` option, which could be used to inject user-provided text into the bar bar, is now redundant. For now, it is accepted but generates a warning if used.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ⏳ (3/5 running) | ⏳ (2/2 running) | ⏳ (2/2 running) | ⏳ (2/2 running) |

### Issue
 * [JDK-8248320](https://bugs.openjdk.java.net/browse/JDK-8248320): Provide a unique accessible name for <nav role="navigation">

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.java.net/census#hannesw) (@hns - **Reviewer**) ⚠️ Review applies to 1939efc0a7ae27aac9347017b7c99e8b5fd1ea29

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/710/head:pull/710`
`$ git checkout pull/710`

### CODE REVIEW

**Review by hns — APPROVED** [review]
Looks good, Jon!

In order to clean up, the following could and should probably be removed:
 - `HtmlStyle.bottomNav`
 - Instances of `bottom-nav` in stylesheet.css
 - `*_BOTTOM_NAVBAR` constants in MarkerComments

**Comment by jonathan-gibbons** [comment]
Thanks; I'll take care of that cleanup.

-- Jon

**Pull request closed without merging**
