### PR TITLE
8339794: Open source closed choice tests #1

### PR DESCRIPTION
**Pull request by azvegint**
Few more tests open sourcing.

Testing is green.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339794](https://bugs.openjdk.org/browse/JDK-8339794): Open source closed choice tests #1 (**Bug** - P4)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) Review applies to [d1fa3910](https://git.openjdk.org/jdk/pull/20941/files/d1fa3910ecd51a5ab75d3d94309b5af943b29080)
 * [Jayathirth D V](https://openjdk.org/census#jdv) (@jayathirthrao - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20941/head:pull/20941` \
`$ git checkout pull/20941`

Update a local copy of the PR: \
`$ git checkout pull/20941` \
`$ git pull https://git.openjdk.org/jdk.git pull/20941/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20941`

View PR using the GUI difftool: \
`$ git pr show -t 20941`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20941.diff">https://git.openjdk.org/jdk/pull/20941.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20941#issuecomment-2341997365)

### CODE REVIEW

**Comment by jayathirthrao** [comment]
@azvegint  I see that one of the test jdk/java/awt/Choice/WheelEventsConsumed/WheelEventsConsumed.java is deproblemlisted.
Is this test sufficiently tested in our CI to make sure we don't have some intermittent failure?

**Review by prrace — APPROVED** [review]
We went back and forth on when it makes sense to have a subdirectory, didn't we ?
Not sure this one needs it, there's no history to preserve across moves / renames and the tests don't seem to do anything that steps on other tests.
So I'm approving, but think about that.

**Comment by azvegint** [comment]
> @azvegint I see that one of the test jdk/java/awt/Choice/WheelEventsConsumed/WheelEventsConsumed.java is deproblemlisted. Is this test sufficiently tested in our CI to make sure we don't have some intermittent failure?

It is not intermittent, it always fails on Windows and macos, they just behave differently and do not deliver MouseWheelEvent when outside of the Choice component.
The original fix was for 1.6(there was no support for macos from Sun at the time). I tried 6u45 on Windows and it still fails.

This test is not in the problem list because it is now only linux `@requires (os.family == "linux")`

**Comment by azvegint** [comment]
> We went back and forth on when it makes sense to have a subdirectory, didn't we ? Not sure this one needs it, there's no history to preserve across moves / renames and the tests don't seem to do anything that steps on other tests. So I'm approving, but think about that.

Moved from separate dirs

**Pull request closed without merging**
