### PR TITLE
JDK-8292583: Comment for ciArrayKlass::make is wrong

### PR DESCRIPTION
**Pull request by dafedafe**
The comment for ciArrayKlass::make is wrong (probably a result of a copy/paste).

Fixing the comment.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292583](https://bugs.openjdk.org/browse/JDK-8292583): Comment for ciArrayKlass::make is wrong

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12740/head:pull/12740` \
`$ git checkout pull/12740`

Update a local copy of the PR: \
`$ git checkout pull/12740` \
`$ git pull https://git.openjdk.org/jdk pull/12740/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12740`

View PR using the GUI difftool: \
`$ git pr show -t 12740`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12740.diff">https://git.openjdk.org/jdk/pull/12740.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good and trivial.

**Review by robcasloz — APPROVED** [review]

**Comment by dafedafe** [comment]
@TobiHartmann @robcasloz thanks a lot for your reviews!

**Pull request closed without merging**
