### PR TITLE
8303702: Provide ThreadFactory to create platform/virtual threads for com/sun/jdi tests

### PR DESCRIPTION
**Pull request by lmesnik**
Provide a way to start debugee threads as platform or virtual for debugee in com/sun/jdi tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303702](https://bugs.openjdk.org/browse/JDK-8303702): Provide ThreadFactory to create platform/virtual threads for com/sun/jdi tests

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to [9951ab3e](https://git.openjdk.org/jdk/pull/12894/files/9951ab3e6ad04dfd7884e5c81e843c966f185435)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12894/head:pull/12894` \
`$ git checkout pull/12894`

Update a local copy of the PR: \
`$ git checkout pull/12894` \
`$ git pull https://git.openjdk.org/jdk pull/12894/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12894`

View PR using the GUI difftool: \
`$ git pr show -t 12894`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12894.diff">https://git.openjdk.org/jdk/pull/12894.diff</a>

</details>

### CODE REVIEW

**Review by plummercj — CHANGES_REQUESTED** [review]

**Comment by plummercj** [comment]
I think all of the following could also be converted, although most will be a bit harder to accomplish since they create subclasses of the Thread class.

```
JdbStopThreadidTest
InterruptHangTest
InvokeHangTest
MultiBreakpointsTest
SimulResumerTest
TwoThreads
ResumeOneThread
```

**Review by plummercj — APPROVED** [review]
Looks good. Thanks for getting these test updated.

**Comment by dcubed-ojdk** [comment]
What kind of testing has been done on these changes?

**Comment by lmesnik** [comment]
I am did the local execution of :jdk_jdi, the execution of :jdk_jdi with wrapper. 
(Last time I missed to remove extra problem list and missed one issue.)

Also, I've submitted tier1-5 testing in mach5. (To cover different GC/Comp options and platforms). It still in progress.

**Comment by dcubed-ojdk** [comment]
Thanks for documenting the testing in the PR!

**Review by sspitsyn — APPROVED** [review]
The fix as it is looks good.
In general, there are more `jdk_jdi` tests that could support virtual threads.
Is there any plan about it?
Thanks,
Serguei

**Pull request closed without merging**
