### PR TITLE
8283519: Hsdis with capstone should annotate output

### PR DESCRIPTION
**Pull request by djelinski**
Sample output after the changes:
```
[Stub Code]
  0x000001cd0a937e20:   nopl		(%rax, %rax)        ;   {no_reloc}
  0x000001cd0a937e25:   movabsq		$0x0, %rbx          ;   {static_stub}
  0x000001cd0a937e2f:   jmp		0x1cd0a937e2f       ;   {runtime_call}
[Exception Handler]
  0x000001cd0a937e34:   callq		0x1cd0a3ca480       ;   {runtime_call handle_exception_from_callee Runtime1 stub}
  0x000001cd0a937e39:   movabsq		$0x7ff8df21a850, %rcx;   {external_word}
  0x000001cd0a937e43:   andq		$0xfffffffffffffff0, %rsp
  0x000001cd0a937e47:   movabsq		$0x7ff8deef30c0, %r10;   {runtime_call MacroAssembler::debug64}
  0x000001cd0a937e51:   callq		*%r10
  0x000001cd0a937e54:   hlt		
[Deopt Handler Code]
  0x000001cd0a937e55:   movabsq		$0x1cd0a937e55, %r10;   {section_word}
  0x000001cd0a937e5f:   pushq		%r10
  0x000001cd0a937e61:   jmp		0x1cd0a325ca0       ;   {runtime_call DeoptimizationBlob}
  0x000001cd0a937e66:   hlt		
  0x000001cd0a937e67:   hlt		
```
before the changes none of the annotations (like `[Stub Code]` or `;   {no_reloc}`) were present.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283519](https://bugs.openjdk.java.net/browse/JDK-8283519): Hsdis with capstone should annotate output

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7904/head:pull/7904` \
`$ git checkout pull/7904`

Update a local copy of the PR: \
`$ git checkout pull/7904` \
`$ git pull https://git.openjdk.java.net/jdk pull/7904/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7904`

View PR using the GUI difftool: \
`$ git pr show -t 7904`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7904.diff">https://git.openjdk.java.net/jdk/pull/7904.diff</a>

</details>

### CODE REVIEW

**Comment by djelinski** [comment]
tested on Windows 10 (vs2019) and Ubuntu 20.04. Additionally compared the output of PrintAssembly with capstone vs binutils; there were only cosmetic differences.

**Comment by magicus** [comment]
Thank you for fixing this! The original capstone implementation was mostly a stub.

**Review by JornVernee — APPROVED** [review]
LGTM

**Pull request closed without merging**
