### PR TITLE
8278482: G1: Improve HeapRegion::block_is_obj

### PR DESCRIPTION
**Pull request by albertnetymk**
Adding assertions to `HeapRegion::block_is_obj` and its callers, and removing some dead code based on the assertions.

Test: tier1-5

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278482](https://bugs.openjdk.java.net/browse/JDK-8278482): G1: Improve HeapRegion::block_is_obj

### Reviewers
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to d430c6373875a0ee05f6c4c82941ef9f58a8a218
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6781/head:pull/6781` \
`$ git checkout pull/6781`

Update a local copy of the PR: \
`$ git checkout pull/6781` \
`$ git pull https://git.openjdk.java.net/jdk pull/6781/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6781`

View PR using the GUI difftool: \
`$ git pr show -t 6781`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6781.diff">https://git.openjdk.java.net/jdk/pull/6781.diff</a>

</details>

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good.

**Review by tschatzl — CHANGES_REQUESTED** [review]

**Review by Hamlin-Li — APPROVED** [review]
looks good

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
