### PR TITLE
8283839: [JVMCI] add support for querying indy bootstrap method target and arguments

### PR DESCRIPTION
**Pull request by dougxc**
This PR adds support to JVMCI for obtaining the call info for the bootstrap method associated with an invokedynamic or constantdynamic constant pool entry.

In the context of Native Image, this is necessary to be able to defer execution of select bootstrap methods to image run time (as opposed to executing the bootstrap method during Native Image build time).

I've also included a minor change to adopt use of the `jvms` javadoc tag in JVMCI Java code. This is preferable to the HTML links previously used in that the latter refer to a specific JDK release.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283839](https://bugs.openjdk.java.net/browse/JDK-8283839): [JVMCI] add support for querying indy bootstrap method target and arguments

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8273/head:pull/8273` \
`$ git checkout pull/8273`

Update a local copy of the PR: \
`$ git checkout pull/8273` \
`$ git pull https://git.openjdk.java.net/jdk pull/8273/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8273`

View PR using the GUI difftool: \
`$ git pr show -t 8273`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8273.diff">https://git.openjdk.java.net/jdk/pull/8273.diff</a>

</details>

### CODE REVIEW

**Comment by dougxc** [comment]
> Looks good (not an expert on JVMCI but i could follow the change). I am presuming no CSR is required for the new public method.

Since JVMCI is not public API (no packages in `jdk.internal.vm.ci` are exported unqualified), I don't believe a CSR is needed.

**Comment by dougxc** [comment]
Thanks for the review @PaulSandoz .

**Review by vnkozlov — APPROVED** [review]
Seems fine.

**Comment by dougxc** [comment]
Thanks for the review @vnkozlov .

**Pull request closed without merging**
