### PR TITLE
8275259: Add support for Java level DCmd

### PR DESCRIPTION
**Pull request by D-D-H**
(RFC: https://mail.openjdk.java.net/pipermail/serviceability-dev/2021-October/039796.html)

I proposed to extend DCmd to allow Java developers to customize their own diagnostic commands last week.

At present, I have implemented a preliminary version.

In the current implementation, I provided some simple APIs in the Java layer (under sun.management.cmd) for defining and registering commands.

- Executable interface
  Java diagnostic commands need to implement this interface, the interface only contains a simple method:
```
    /**
     * @param output the output when this executable is running
     */
    void execute(PrintWriter output);
```

- Add two annotations (@Command and @Parameter) to describe the command meta info

- Use Factory API to register command, the following forms are supported
```
@Command(name = "My.Echo", description = "Echo description")
class Echo implements Executable {

    @Parameter(name = "text", ordinal=0, isMandatory = true)
    String text;

    @Parameter(name = "repeat", isMandatory = true, defaultValue = "1")
    int repeat;

    @Override
    public void execute(PrintWriter out) {
        for (int i = 0 ; i < repeat; i++) {
            out.println(text);
        }
    }
}

Factory.register(Echo.class);
```

```
Factory.register("My.Date", output -> {
    output.println(new Date());
});
```

- When the command is running, the VM will call `Executor.executeCommand` to execute the command. In the implementation of Executor, I introduced a simple timeout mechanism to prevent the command channel from being blocked.

At the VM layer, I extended the existing DCmd framework(implemented JavaDCmd and JavaDCmdFactoryImpl) to be compatible with existing functions (jmx, help, etc.).

In terms of security, considering that the SecurityManager will be deprecated, there are not too many considerations for the time being.

Any input is appreciated.

Thanks,
Denghui

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8275259](https://bugs.openjdk.java.net/browse/JDK-8275259): Add support for Java level DCmd

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5938/head:pull/5938` \
`$ git checkout pull/5938`

Update a local copy of the PR: \
`$ git checkout pull/5938` \
`$ git pull https://git.openjdk.java.net/jdk pull/5938/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5938`

View PR using the GUI difftool: \
`$ git pr show -t 5938`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5938.diff">https://git.openjdk.java.net/jdk/pull/5938.diff</a>

</details>

### CODE REVIEW

**Comment by D-D-H** [comment]
> > In the current implementation, I provided some simple APIs in the Java layer (under sun.management.cmd)
> 
> An API that is expected to be used by application code can't go in the unsupported/internal-use-only sun.management namespace. This would have to be a new external facing supported API.
> 
> Cheers, David

Thanks.
 I consider putting the API into `javax.management.dcmd`. What do you think?

**Comment by D-D-H** [comment]
> Ah right - so you're really looking at extending the capabilities of the
> DiagnosticCommandMBean to add a way to register a Java diagnostic command.

Yes, but we could not add registration API to DiagnosticCommandMBean directly.

There are already some VM diagnostic commands that depend on Java methods directly, this extension could also bring benefit to this scenario I think.

Hope folks from serviceability could take a look at it:)

Denghui

**Comment by D-D-H** [comment]
Hi Thomas,

> Hi,
> 
> Interesting proposal. I have some questions.
> 
> * Will hanging java user code block the attach listener thread? If yes, how would you solve that?

In my current implementation, I use a simple timeout mechanism to solve this problem.

Create a Thread to run the command, and use `java.util.concurrent.Future#get(long, java.util.concurrent.TimeUnit)` to get the result.

For more details please refer to Executor.java.


> * Will this require changes to the jcmd client, or will this work with any jcmd client, up- and downward the JDK versions? (the nice thing about jcmd is that all the logic resides at the hotspot and I can use any client to talk to any hotspot)
> 

At present, I only extend the DCMD framework and do not modify the code of jcmd. So it works with any jcmd client and jmx client, up and downward JDK versions I think.

> Cheers, Thomas
> 
> P.S. I think it may be worthwhile to discuss this on the serviceability-dev mailing list first.

Denghui

**Comment by D-D-H** [comment]
Hi Erik,
> To understand what is needed (namespacing, error handling, safety, lifecycle etc.) and if this is actually useful for Java, I think you need to write 2-3 commands for a few popular frameworks, for example Spring.
> 
> If we can't come up with 5-10 commands where this functionality would solve real problems users face, it's unlikely somebody will use it. It will just be a maintenance burden in the JDK. Once an API is added, it's hard to remove.
> 
> The scope of this seem to be JEP level.
> 
> (JFR is not a valid use case, since we don't want to add a dependency on annotation classes in the jdk.jcmd module).

Thanks for the comments.

I will investigate whether there is a scenario to apply this extension in the current mainstream framework.

Denghui

**Comment by tstuefe** [comment]
> Hi Thomas,
> 
> > Hi,
> > Interesting proposal. I have some questions.
> > 
> > * Will hanging java user code block the attach listener thread? If yes, how would you solve that?
> 
> In my current implementation, I use a simple timeout mechanism to solve this problem.
> 
> Create a Thread to run the command, and use `java.util.concurrent.Future#get(long, java.util.concurrent.TimeUnit)` to get the result.
> 
> For more details please refer to Executor.java.
> 
> > * Will this require changes to the jcmd client, or will this work with any jcmd client, up- and downward the JDK versions? (the nice thing about jcmd is that all the logic resides at the hotspot and I can use any client to talk to any hotspot)
> 
> At present, I only extend the DCMD framework and do not modify the code of jcmd. So it works with any jcmd client and jmx client, up and downward JDK versions I think.
> 
> > Cheers, Thomas
> > P.S. I think it may be worthwhile to discuss this on the serviceability-dev mailing list first.
> 
> Denghui

Hi Denghui,

thanks for your answers. I'm ambivalent here. I worry about the growing complexity of jcmd, and about unforeseen consequences if we open this door. OTOH I can see this as a useful feature. I'll wait for a consensus.

Thanks, Thomas

**Comment by D-D-H** [comment]
Thanks for the commands, the following is my thought.

Compared with the user's own implementation of a DiagnosticCommandMBean, the main benefits of this extension are:

Users can directly use `jcmd` to invoke (better user experience, of course, users can also invoke through a jmx client like jconsole), and use `jcmd pid help` to list all VM commands and user-defined commands. And all parameters or options are pre-parsed, making the implementation of the command simpler and focusing on their own logic. 

I am not an expert in the security field, but I feel that implementing a DiagnosticCommandMBean by the users does not seem to be more secure than the method in the proposal. I mean the users can still do whatever they want.

Just like Chris said, it seems that not many people are interested in this proposal. I plan to close this PR first.
If there are any others who want this in place, we can continue to discuss it in the RFC thread of this proposal.

Denghui,
Thanks

**Pull request closed without merging**
