### PR TITLE
8292386: jvmti/thread/SuspendThread/suspendthrd03 failed with "FAIL: Status is 2"

### PR DESCRIPTION
**Pull request by lmesnik**
This test duplicates runtime/handshake/HandshakeSuspendExitTest.java and might be deleted.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292386](https://bugs.openjdk.org/browse/JDK-8292386): jvmti/thread/SuspendThread/suspendthrd03 failed with "FAIL: Status is 2"

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10662/head:pull/10662` \
`$ git checkout pull/10662`

Update a local copy of the PR: \
`$ git checkout pull/10662` \
`$ git pull https://git.openjdk.org/jdk pull/10662/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10662`

View PR using the GUI difftool: \
`$ git pr show -t 10662`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10662.diff">https://git.openjdk.org/jdk/pull/10662.diff</a>

</details>

### CODE REVIEW

**Review by sspitsyn — APPROVED** [review]
I think, the failing status is a test issue but it is hard to prove.
This test is over complicated and hard to understand and work with.
Additionally, it duplicates matching nsk test: suspendthrd003.
It is nice to remove it. We already have enough test coverage in this area.
Thanks,
Serguei

**Comment by dcubed-ojdk** [comment]
I'm okay with deleting these two files:

test/hotspot/jtreg/serviceability/jvmti/thread/SuspendThread/suspendthrd03/libsuspendthrd03.cpp
test/hotspot/jtreg/serviceability/jvmti/thread/SuspendThread/suspendthrd03/suspendthrd03.java

but can someone explain why this test was ported/created in the first place?

And did the Loom project do this with other tests and, if so, why?

**Review by dcubed-ojdk — APPROVED** [review]

**Comment by lmesnik** [comment]
> I'm okay with deleting these two files:
> 
> test/hotspot/jtreg/serviceability/jvmti/thread/SuspendThread/suspendthrd03/libsuspendthrd03.cpp test/hotspot/jtreg/serviceability/jvmti/thread/SuspendThread/suspendthrd03/suspendthrd03.java
> 
> but can someone explain why this test was ported/created in the first place?
> 
> And did the Loom project do this with other tests and, if so, why?

The idea was to improve these tests to test virtual threads. However, the suspend/resume have already some coverage in vthread. So these tests remain unchanged. Currently, I think it is needed to remove this test and might be simplify nsk/jvmti original.

**Comment by sspitsyn** [comment]
> The idea was to improve these tests to test virtual threads.
> However, the suspend/resume have already some coverage in vthread.

In fact, we have pretty extensive test SR coverage for virtual threads.

**Pull request closed without merging**
