### PR TITLE
8330103: Compiler memory statistics should keep separate records for C1 and C2

### PR DESCRIPTION
**Pull request by tstuefe**
See JBS description.

This simple enhancement changes compiler memory statistic such that we keep the record of the most recent compilation not only per method, but per method and per compiler. That way, recompiling method X with C2 will not overwrite memory statistics from a prior C1 compilation, and vice versa.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330103](https://bugs.openjdk.org/browse/JDK-8330103): Compiler memory statistics should keep separate records for C1 and C2 (**Enhancement** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Claes Redestad](https://openjdk.org/census#redestad) (@cl4es - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18740/head:pull/18740` \
`$ git checkout pull/18740`

Update a local copy of the PR: \
`$ git checkout pull/18740` \
`$ git pull https://git.openjdk.org/jdk.git pull/18740/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18740`

View PR using the GUI difftool: \
`$ git pr show -t 18740`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18740.diff">https://git.openjdk.org/jdk/pull/18740.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18740#issuecomment-2051183379)

### CODE REVIEW

**Comment by tstuefe** [comment]
Ping @cl4es

**Comment by tstuefe** [comment]
> Looks fine. Can you give an example of new output?

Thanks, @vnkozlov .
 
Certainly: [x.txt](https://github.com/openjdk/jdk/files/14965446/x.txt)

The difference is subtle. Notice how we now see e.g. `StringCoding::countPositives` twice in the summary listing (lines 21 and 69), once for C1, once for C2.

**Comment by vnkozlov** [comment]
Good.

**Review by cl4es — APPROVED** [review]
Nice - thanks for doing this!

**Comment by tstuefe** [comment]
Thanks @cl4es !

/integrate

**Pull request closed without merging**
