### PR TITLE
8286623: Bundle zlib by default with JDK on macos aarch64

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change to the build system which now makes bundled zlib as the default for macos aarch64 systems? 

We have been running into various intermittent failures on macos aarch64 systems for several months now. After investigation we have been able to ascertain that the root cause of the issue lies within the zlib that's shipped on macos aarch64 systems. The complete details about that issue is available at https://bugs.openjdk.java.net/browse/JDK-8282954. 
We have filed a bug with Apple for their inputs on what we can do to fix it in that shipped library. Given the nature of that issue, we don't have a timeline on when/if the solution for that will be available. Until that time, at least, the proposal is to use bundled zlib (which doesn't reproduce those failures) by default on macos aarch64.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286623](https://bugs.openjdk.java.net/browse/JDK-8286623): Bundle zlib by default with JDK on macos aarch64

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8675/head:pull/8675` \
`$ git checkout pull/8675`

Update a local copy of the PR: \
`$ git checkout pull/8675` \
`$ git pull https://git.openjdk.java.net/jdk pull/8675/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8675`

View PR using the GUI difftool: \
`$ git pr show -t 8675`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8675.diff">https://git.openjdk.java.net/jdk/pull/8675.diff</a>

</details>

### CODE REVIEW

**Comment by jaikiran** [comment]
Dummy commit to initiate a mail to core-libs mailing list too.

**Review by LanceAndersen — APPROVED** [review]
Hi Jai,

Thank you for your efforts with testing and reaching out to Apple.

Given we do not see the issue with the bundled zlib, this is our best path forward for stability on macOS aarch64.

Once we can determine the cause with the help of Apple, we can switch back to the zlib that comes with macOS on this platform.

**Review by magicus — APPROVED** [review]
LGTM

**Review by erikj79 — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you everyone for the reviews.

**Comment by mrserb** [comment]
@jaikiran Do you have a plan to backport this fix to the 17 and below?

**Pull request closed without merging**
