### PR TITLE
JDK-8313253: Rename methods in javadoc Comparators class

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a fairly simple change, to simply rename methods in the `Comparators` class, to remove the `make` prefix from the method names, and (for consistency) in one case, remove `get`.  There are some updates to the more problematic javadoc comments as well.

It would be nice to think that the implementation of some methods could be improved by chaining use of simpler standard comparators, but that would be a different task.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313253](https://bugs.openjdk.org/browse/JDK-8313253): Rename methods in javadoc Comparators class (**Enhancement** - P4)

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.org/census#hannesw) (@hns - **Reviewer**)
 * [Pavel Rappo](https://openjdk.org/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15057/head:pull/15057` \
`$ git checkout pull/15057`

Update a local copy of the PR: \
`$ git checkout pull/15057` \
`$ git pull https://git.openjdk.org/jdk.git pull/15057/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15057`

View PR using the GUI difftool: \
`$ git pr show -t 15057`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15057.diff">https://git.openjdk.org/jdk/pull/15057.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15057#issuecomment-1653994001)

### CODE REVIEW

**Review by hns — APPROVED** [review]
Looks good to me.

**Comment by hns** [comment]
@jonathan-gibbons I also suspect comparators can be unified/simplified. There is a JBS issue for this and I plan to look into this soon. https://bugs.openjdk.org/browse/JDK-8256984

**Review by pavelrappo — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
