### PR TITLE
8302514: Misleading error generated when empty class file encountered

### PR DESCRIPTION
**Pull request by archiecobbs**
When javac encounters an empty class file, you get the following strange error referring to `java.lang.AutoCloseable`:
```
Test.java:3: error: cannot access Empty
        new Empty();
            ^
  bad class file: ./Empty.class
    class file contains wrong class: java.lang.AutoCloseable
    Please remove or make sure it appears in the correct subdirectory of the classpath.
1 error
```
This is a side effect of javac blindly reading past the end of the data in a data buffer. Further investigation revealed three distinct bugs in this area of the code:

1. There are several unchecked corner cases in `ByteBuffer` and `ArrayUtils` that could potentially lead to `ArrayIndexOutOfBoundsException`s and/or infinite loops. Instead we should "fail fast" on any attempt to read or allocate data out of bounds.
1. The method `ByteBuffer.appendStream()` assumes that the result from `InputStream.available()` is always accurate, but this is not guaranteed. As a result, class files could (in theory) be read incorrectly by the compiler, especially when they come from non-standard sources.
1. There is no systematic protection against truncated class files. Instead, depending on where exactly it is truncated, a truncated class file generates one of several possible different errors:
   * `index 25926 is not within pool size 13`
   * `bad constant pool tag: 0 at 28317`
   * `unexpected constant pool tag: 10 at 11`
   * `class file is invalid for class Empty`
   * `class file contains wrong class: java.lang.AutoCloseable`

This patch fixes issues 1 and 2, and addresses 3 by having `ByteBuffer` throw a new unchecked `UnderflowException` if ever data is read past the end of the buffer. Then `PoolReader`, `ClassReader`, and `ModuleNameReader` are updated to catch this exception and convert it into a bad class file error. As a result, truncated class files generate a consistent `class file truncated at offset X` error regardless of where they are truncated.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302514](https://bugs.openjdk.org/browse/JDK-8302514): Misleading error generated when empty class file encountered

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)
 * [Julian Waters](https://openjdk.org/census#jwaters) (@TheShermanTanker - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12574/head:pull/12574` \
`$ git checkout pull/12574`

Update a local copy of the PR: \
`$ git checkout pull/12574` \
`$ git pull https://git.openjdk.org/jdk pull/12574/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12574`

View PR using the GUI difftool: \
`$ git pr show -t 12574`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12574.diff">https://git.openjdk.org/jdk/pull/12574.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks sensible to me

**Comment by TheShermanTanker** [comment]
Sponsoring out of goodwill

**Review by TheShermanTanker — APPROVED** [review]

**Pull request closed without merging**
