### PR TITLE
8297487: G1 Remark: no need to keep alive oop constants of nmethods on stack

### PR DESCRIPTION
**Pull request by reinrich**
This pr removes the stackwalks to keep alive oops of nmethods found on stack during G1 remark as it seems redundant. The oops are already kept alive by the [nmethod entry barrier](https://github.com/openjdk/jdk/blob/f26bd4e0e8b68de297a9ff93526cd7fac8668320/src/hotspot/share/gc/shared/barrierSetNMethod.cpp#L85)

Additionally it fixes a comment that says nmethod entry barriers are needed to deal with continuations which, afaik, is not the case. Please correct me and explain if I'm mistaken.

Testing: the patch is included in our daily CI testing since a week. That is most JCK and JTREG tests, also in Xcomp mode, Renaissance benchmark and SAP specific tests with fastdebug and release builds on the standard platforms plus PPC64. There was no failure I could attribute to this change.

I tried to find a jtreg test that is sensitive to the keep alive by omitting it in the nmethod entry barrier and also in G1 remark but without success.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297487](https://bugs.openjdk.org/browse/JDK-8297487): G1 Remark: no need to keep alive oop constants of nmethods on stack

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [37ee165b](https://git.openjdk.org/jdk/pull/11314/files/37ee165b7eb7b15aca8ea597825a9ad3bd70921e)
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**) ⚠️ Review applies to [37ee165b](https://git.openjdk.org/jdk/pull/11314/files/37ee165b7eb7b15aca8ea597825a9ad3bd70921e)
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11314/head:pull/11314` \
`$ git checkout pull/11314`

Update a local copy of the PR: \
`$ git checkout pull/11314` \
`$ git pull https://git.openjdk.org/jdk pull/11314/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11314`

View PR using the GUI difftool: \
`$ git pr show -t 11314`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11314.diff">https://git.openjdk.org/jdk/pull/11314.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm. Will push it through our tier1-5

**Comment by reinrich** [comment]
> Lgtm. Will push it through our testing.

Thanks!

**Comment by tschatzl** [comment]
One other note: since the ARM32 port does not have this nmethod walk safety net during Remark pause anymore and it does not implement nmethod barriers it may be good to talk to ARM32 maintainers about this change. I do not know who maintains ARM32 code.

We at Oracle do not support ARM32 so it should be good, but it may help ARM32 maintainers to keep this now removed code after all.

**Comment by reinrich** [comment]
> One other note: since the ARM32 port does not have this nmethod walk safety net during Remark pause anymore and it does not implement nmethod barriers (at least that's what that `nullptr` return value by that removed comment indicates to me) it may be good to talk to ARM32 maintainers about this change. I do not know who maintains ARM32 code.
> 
> We at Oracle do not support ARM32 so it should be good, but it may help ARM32 maintainers to keep this now removed code after all.

Good point. It is myy understanding (also stated in the JBS item) that G1 concurrent marking requires the keep alive of oop constants by the nmethod entry barriers for SATB correctness. So without the entry barriers ARM32 has an issue there already because the keep alive during the remark pause is not sufficient, is it?

There's a JBS item [JDK-8291302](https://bugs.openjdk.org/browse/JDK-8291302) to implement the nmethod entry barrier assigned to @bulasevich. Boris are there plans to implement the nmethod entry barriers on ARM32 in the near future given that they are required for G1 correctness?

**Comment by tschatzl** [comment]
> > We at Oracle do not support ARM32 so it should be good, but it may help ARM32 maintainers to keep this now removed code after all.
> 
> Good point. It is myy understanding (also stated in the JBS item) that G1 concurrent marking requires the keep alive of oop constants by the nmethod entry barriers for SATB correctness. So without the entry barriers ARM32 has an issue there already because the keep alive during the remark pause is not sufficient, is it?

That is true, but it might make the problem larger than necessary - although admittedly, the comments indicate some magic hand-waving of the effectiveness of this additional walk through the nmethods on thread stacks.

Imho G1 has worked well enough with that level of wrongness for a long time on the other platforms, so keeping this (little amount of) code may help ARM32 maintainers to tide over a little bit (i.e. not make their platforms potentially crash left and right) until they are ready with their nmethod barrier implementation.

I'm good either way you choose.

**Comment by reinrich** [comment]
I would like to get rid of the stackwalks if they are unnecessary, for pause time reduction but also to ease understanding the code. I'm not in a hurry though.
I've posted on the porters list to get some feedback from ARM32 maintainers.

**Review by albertnetymk — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
ARM32 issue is solved: https://github.com/openjdk/jdk/commit/245f0cf4ac9dc655bfe2abb1c88c6ed1ddffd291

**Comment by reinrich** [comment]
> Looks good.

Thank you Erik. I'll integrate this after another round of tests.

**Pull request closed without merging**
