### PR TITLE
8251317: Support for CLDR version 38

### PR DESCRIPTION
**Pull request by naotoj**
Hi,

Please review the changes for upgrading the CLDR data to version 38. The vast majority of the changes are simply the changes in CLDR upstream, and others are mainly test changes due to the locale data change.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (8/8 passed) |

### Issue
 * [JDK-8251317](https://bugs.openjdk.java.net/browse/JDK-8251317): Support for CLDR version 38

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Brent Christian](https://openjdk.java.net/census#bchristi) (@bchristi-git - **Reviewer**)
 * [Joe Wang](https://openjdk.java.net/census#joehw) (@JoeWang-Java - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1279/head:pull/1279`
`$ git checkout pull/1279`

### CODE REVIEW

**Comment by naotoj** [comment]
Looks like the generated webrev is empty, possibly due to this issue (https://bugs.openjdk.java.net/browse/SKARA-732). Here is the one manually generated:
https://cr.openjdk.java.net/~naoto/cldr/webrev.00/

**Review by erikj79 — APPROVED** [review]
Looks fine from a build point of view.

**Review by bchristi-git — APPROVED** [review]
Changes seem fine to me.

**Review by JoeWang-Java — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
