### PR TITLE
8265358: ProblemList jdk/jshell/ToolBasicTest.java on macOS-aarch64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
A set of trivial ProblemListing for macos-aarch64 Tier2 test failures:

- JDK-8265358 ProblemList jdk/jshell/ToolBasicTest.java on macOS-aarch64
- JDK-8265361 ProblemList a few compiler/whitebox tests on macos-aarch64
- JDK-8265363 ProblemList java/net/Socket/UdpSocket.java on macos-aarch64
- JDK-8265368 ProblemList 3 java/net/httpclient/websocket tests on macos-aarch64
- JDK-8265370 ProblemList java/net/MulticastSocket/Promiscuous.java on macos-aarch64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8265358](https://bugs.openjdk.java.net/browse/JDK-8265358): ProblemList jdk/jshell/ToolBasicTest.java on macOS-aarch64
 * [JDK-8265361](https://bugs.openjdk.java.net/browse/JDK-8265361): ProblemList a few compiler/whitebox tests on macos-aarch64
 * [JDK-8265363](https://bugs.openjdk.java.net/browse/JDK-8265363): ProblemList java/net/Socket/UdpSocket.java on macos-aarch64
 * [JDK-8265368](https://bugs.openjdk.java.net/browse/JDK-8265368): ProblemList 3 java/net/httpclient/websocket tests on macos-aarch64
 * [JDK-8265370](https://bugs.openjdk.java.net/browse/JDK-8265370): ProblemList java/net/MulticastSocket/Promiscuous.java on macos-aarch64

### Reviewers
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**) ⚠️ Review applies to 5fb3de6aadd51de2c359457c96a6a1edb140d002
 * [Mikael Vidstedt](https://openjdk.java.net/census#mikael) (@vidmik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3549/head:pull/3549` \
`$ git checkout pull/3549`

Update a local copy of the PR: \
`$ git checkout pull/3549` \
`$ git pull https://git.openjdk.java.net/jdk pull/3549/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3549`

View PR using the GUI difftool: \
`$ git pr show -t 3549`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3549.diff">https://git.openjdk.java.net/jdk/pull/3549.diff</a>

</details>

### CODE REVIEW

**Review by bplb — APPROVED** [review]

**Review by vidmik — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@bplb and @vidmik - Thanks for the reviews.

I'm removing the changes for JDK-8265366 at @fguallini's request.

**Review by vidmik — APPROVED** [review]

**Pull request closed without merging**
