### PR TITLE
8272352: Java launcher can not parse Chinese character when system locale is set to UTF-8

### PR DESCRIPTION
**Pull request by naotoj**
Java runtime has been detecting the Windows system locale encoding using `GetLocaleInfo(GetSystemDefaultLCID(), LOCALE_IDEFAULTANSICODEPAGE, ...)`, but it returns the *legacy* ANSI code page value, e.g, 1252 for US-English. In order to detect whether the user has selected `UTF-8` as the default, the code page has to be queried with `GetACP()`.
Also, the case if the call to `GetLocaleInfo` fails changed to fall back to `UTF-8` instead of `Cp1252`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8272352](https://bugs.openjdk.java.net/browse/JDK-8272352): Java launcher can not parse Chinese character when system locale is set to UTF-8

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8434/head:pull/8434` \
`$ git checkout pull/8434`

Update a local copy of the PR: \
`$ git checkout pull/8434` \
`$ git pull https://git.openjdk.java.net/jdk pull/8434/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8434`

View PR using the GUI difftool: \
`$ git pr show -t 8434`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8434.diff">https://git.openjdk.java.net/jdk/pull/8434.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
Is it possible to write a jtreg test for this fix?
Thanks.

**Comment by naotoj** [comment]
> Is it possible to write a jtreg test for this fix? Thanks.

I am happy to write a test if possible, but AFAIK it requires configuring Windows settings (and reboot), so I don't think jtreg is capable of doing so. Thus I added `noreg-hard` to the JBS issue.

**Review by RogerRiggs — APPROVED** [review]
Looks good.

**Pull request closed without merging**
