### PR TITLE
8320931: [REDO] dsymutil command leaves around temporary directories

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change will attempts to workaround an issue in dsymutil?

The previous attempt to use `--reproducer Off` has shown that it fails to build on some other Xcode versions other than 14.3.1. Users have reported it to fail on  Xcode 15.0.1 and Xcode from a 12.4 devkit. The `--reproducer` option isn't being recognized on those versions.

This current PR proposes to use an alternate workaround, one which just sets an environment variable that Xcode 14.3.1 recognizes and prevents the creation of the leftover `dsymutil-*` temporary directories. Since this new approach uses an environment variable to workaround the issue, the command itself shouldn't ideally run into any usage issues. Once we agree upon this change, before integrating, I'll ask for inputs from those who had run into build issues to verify this alternate approach doesn't cause problems.

I have locally verified that this new approach continues to work and doesn't create those temporary directories. Additionally tier1, tier2, tier3 has completed successfully in our CI environment with this change.

Magnus, Erik, I looked around to see if there's any convention in setting such environment variables that will be used when invoking external tools during the build. I didn't find any similar usage. Although the current change in this PR is working, if there's a different and better way to do this, please do let me know.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320931](https://bugs.openjdk.org/browse/JDK-8320931): [REDO] dsymutil command leaves around temporary directories (**Bug** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16876/head:pull/16876` \
`$ git checkout pull/16876`

Update a local copy of the PR: \
`$ git checkout pull/16876` \
`$ git pull https://git.openjdk.org/jdk.git pull/16876/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16876`

View PR using the GUI difftool: \
`$ git pr show -t 16876`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16876.diff">https://git.openjdk.org/jdk/pull/16876.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16876#issuecomment-1831314200)

### CODE REVIEW

**Comment by magicus** [comment]
Hm, I'm not entirely sure about this. It looks quite ugly, and we'll be stuck with it like forever. :-(

First of all, I think you should add the env var prefix to the DSYMUTIL variable itself, in configure. This is not only to make the makefile less ugly, but since you'd want the same workaround if we were to execute dsymutil elsewhere. (I actually missed this in the previous version of the fix.)

Then, I think it might be worth adding a version check of dsymutil, before prepending this variable, so that we can eventually get rid of this.

**Comment by jaikiran** [comment]
Hello Magnus, thank you for those inputs. Based on that I've now modified this PR to check if the `dsymutil` supports the `--reproducer` option and only if it supports it, I then use that option.

I started off with using the `DSYMUTIL_REPRODUCER_PATH` environment variable usage and thought of checking the `dsymutil` version to decide whether or not to set that environment variable. However, it's extremely unclear which exact version of `dsymutil` should be considered as supporting it. In the upstream llvm project, the commit that introduced this auto generation of temporary directories (along with the `--reproducer` option) is this one https://github.com/llvm/llvm-project/commit/33b6891db24dd1e6702b4f04d2b08c1bf417dbee and going by the git tags associated with that commit, it would appear that even 15.0.x version of dsymutil would support the `--reproducer` option. However, we have had reports that `--reproducer` isn't supported on:
```console
Apple LLVM version 15.0.0
  Optimized build.
  Default target: arm64-apple-darwin23.1.0
  Host CPU: apple-m1
``` 
I think we can't rely on the version numbers of dsymutil alone to decide whether or not to set the `DSYMUTIL_REPRODUCER_PATH` environment variable.

So I decided to add a check in the build configuration to see if `--reproducer` option is supported by `dsymutil` and since we were checking for this option anyway, then I felt that when this option is supported, it makes sense to set `--reproducer Off` instead of the `DSYMUTIL_REPRODUCER_PATH` environment variable.

I have tested this change locally with:

```
dsymutil --version
Apple LLVM version 14.0.0 (clang-1400.0.29.202)
  Optimized build.
  Default target: arm64-apple-darwin23.1.0
  Host CPU: apple-a12
```
which doesn't support this option and with:

```
Apple LLVM version 14.0.3 (clang-1403.0.22.14.1)
  Optimized build.
  Default target: arm64-apple-darwin23.1.0
  Host CPU: apple-m1
```
which supports this option. I've verified that the build change correctly sets the `--reproducer Off` when this option is supported and the temporary directories don't get created.

tier1, tier2 and tier3 testing with this change is currently in progress.

**Review by magicus — APPROVED** [review]
I think it looks good. It would be great if we could have this tested by the people who ran into issues with the original implementation. I don't know who they were, though. I'll see if I can dig through the archives and find some to ping.

**Comment by jaikiran** [comment]
@RealCLanger Hello Christoph, in https://bugs.openjdk.org/browse/JDK-8320863 you noted that you ran into a build issue with Xcode version 13.1. Would you be able to test this current proposed patch in this PR against that setup and see if it builds fine?

**Comment by erikj79** [comment]
I have verified that configuring with an older devkit works as intended, i.e. the `--reproducer` option is not added to `DSYMUTIL`.

**Comment by magicus** [comment]
I have now tested this with Xcode 15.0 as well and confirm that it works. I think this means that you can safely integrate now.

**Comment by jaikiran** [comment]
Thank you Magnus and others for helping review and test this change.

**Pull request closed without merging**
