### PR TITLE
8255982: Extend BasicJMapTest to test with different GC Heap

### PR DESCRIPTION
**Pull request by linzang**
The implementation of jmap tool depends on the implementation of object iteration by different GC heap.
This patch extend the BasicJMapTest to cover differet GC Heap.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255982](https://bugs.openjdk.java.net/browse/JDK-8255982): Extend BasicJMapTest to test with different GC Heap

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 02b379206c2a86a161169b3e1a18c9821ce68d01
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1094/head:pull/1094`
`$ git checkout pull/1094`

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
I believe this would fail when some GCs are not available. For example, in Minimal/Zero only Serial and Parallel are available. ZGC and Shenandoah are not available on all platforms. Plus, specifying another GC with `TEST_VM_OPTS` would probably fail with "multiple GCs selected".

You need to split the tests like this:

```
/*
 * @test
 * @summary Unit test for jmap utility
 * @key intermittent
 * @requires vm.gc.Parallel
 * @library /test/lib
 * @build jdk.test.lib.hprof.*
 * @build jdk.test.lib.hprof.model.*
 * @build jdk.test.lib.hprof.parser.*
 * @build jdk.test.lib.hprof.util.*
 * @run main/othervm/timeout=240 -XX:+UseParallelGC BasicJMapTest
 */

/*
 * @test
 * @summary Unit test for jmap utility
 * @key intermittent
 * @requires vm.gc.G1
 * @library /test/lib
 * @build jdk.test.lib.hprof.*
 * @build jdk.test.lib.hprof.model.*
 * @build jdk.test.lib.hprof.parser.*
 * @build jdk.test.lib.hprof.util.*
 * @run main/othervm/timeout=240 -XX:+UseG1GC BasicJMapTest
 */
...
```

Maybe there is a way to clean up multiple `@build` tags to make the test config less verbose.

**Comment by linzang** [comment]
Hi @shipilev, 
Thanks for reviewing, I have updated the refine commit. 
One problem is about epsilonGC, this test case keep fail with OOME even with -Xmx set to 4GB. I think it may be better to set up a new issue to investigate whether the OOME is expected, as it may take more efforts that is not quite related with testing jmap. so I didn't include it for this test in this PR.  
What do you think?

Thanks!
Lin

**Review by shipilev — APPROVED** [review]
I think it is fine to omit Epsilon from this testing. There is another trick you can use: `@test id=serial` would name the tests appropriately, not just "id#":

```
Running test 'jtreg:test/jdk/sun/tools/jmap/BasicJMapTest.java'
Passed: sun/tools/jmap/BasicJMapTest.java#parallel
Passed: sun/tools/jmap/BasicJMapTest.java#serial
Passed: sun/tools/jmap/BasicJMapTest.java#z
Passed: sun/tools/jmap/BasicJMapTest.java#g1
Passed: sun/tools/jmap/BasicJMapTest.java#shenandoah
Test results: passed: 5
```

I also tested this patch with x86_32 that implicitly disables Z, and it passes. Also passes with TEST_VM_OPTS="-XX:+UseSerialGC", with only one config automatically selected.

@iignatev might want to ack this, as our resident test overseer.

**Comment by linzang** [comment]
@shipilev Thanks for guidance!  Added the id tag. -Lin

**Review by iignatev — CHANGES_REQUESTED** [review]
Hi @linzang ,

it all looks good to me, I'd, however, keep `@build` tags as they were before, this is one of a few difference b/w jdk and hotspot test suites ( in this particular case, it actually matters as discrepancies can lead to sporadic failures). in jdk test-suite, people use a sufficient set of  `@build` tag.

-- Igor

**Comment by linzang** [comment]
Hi @iignatev,
Thanks for your explanation!  recovered the @build tag.
-Lin

**Review by iignatev — APPROVED** [review]

**Pull request closed without merging**
