### PR TITLE
JDK-8295934: IGV: keep node selection when changing view or graph

### PR DESCRIPTION
**Pull request by tobiasholenstein**
In IGV nodes can be selected by clicking on it. When a user selects nodes in a certain view, e.g. "Cluster nodes into blocks" view, and then change to e.g. "Sea of nodes" view, the selection should be kept. Same when the user goes a different graph in the same group, the selection should be kept (as long as the nodes are still present)

New selection features:
- When opening a new graph and no nodes where selected previously the root nodes is centered. 
- When a graph in the same group is opened, the previously selected nodes as selected as well if they are present in the graph. The selected nodes are centered in the new graph. 
- The selected nodes are kept when changing the view, or the properties of the view (e.g. "show neighboring nodes semi-transparent") 
cluster_view
desired

- When "show neighboring nodes semi-transparent" is disabled, previously semi-transparent nodes that were selected are now unselected (because they are not visible anymore)
- It would also be desired adjust the scroll pane to center the selected nodes when changing view, graph, etc.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295934](https://bugs.openjdk.org/browse/JDK-8295934): IGV: keep node selection when changing view or graph

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [c365e70a](https://git.openjdk.org/jdk/pull/11062/files/c365e70a22c9fb3f12cd87d770f2aa1d7874e29e)
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11062/head:pull/11062` \
`$ git checkout pull/11062`

Update a local copy of the PR: \
`$ git checkout pull/11062` \
`$ git pull https://git.openjdk.org/jdk pull/11062/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11062`

View PR using the GUI difftool: \
`$ git pr show -t 11062`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11062.diff">https://git.openjdk.org/jdk/pull/11062.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me functionality-wise.

**Review by robcasloz — CHANGES_REQUESTED** [review]
Keeping the user's node selection across views and related graphs is a useful enhancement, thanks!

As a user, I only have an objection to selecting the Root node when opening a new graph without a previous selection: I would rather not select any node in that situation. Selecting the Root node forces the attention of the user to an arbitrary part of the graph, and this node is not relevant to all views, e.g. the CFG view of the current "Final Code" graph.

Regarding the code changes, I think it would be better for ease of reviewing and traceability to leave cleanups and unrelated refactorings (such as removal of unused imports in `GraphViewerImplementation.java` or not passing a `SceneAnimator` to `LineWidget.java`) to separate RFEs.

**Comment by tobiasholenstein** [comment]
> Keeping the user's node selection across views and related graphs is a useful enhancement, thanks!
> 
> As a user, I only have an objection to selecting the Root node when opening a new graph without a previous selection: I would rather not select any node in that situation. Selecting the Root node forces the attention of the user to an arbitrary part of the graph, and this node is not relevant to all views, e.g. the CFG view of the current "Final Code" graph.
> 
> Regarding the code changes, I think it would be better for ease of reviewing and traceability to leave cleanups and unrelated refactorings (such as removal of unused imports in `GraphViewerImplementation.java` or not passing a `SceneAnimator` to `LineWidget.java`) to separate RFEs.

Hi @robcasloz 
Thanks for your comment! 
I agree that the root not should not be selected. I changed the PR accordingly: now the root node is only centered but not selected anymore. 

I also agree that import of untouched files should not be touches. I reverted that. 

The `SceneAnimator` in `LineWidget.java` was removed because in order to implement this PR I had to refactor the `processOutputSlot()` method which is the only place there `LineWidget.java` is initiated.

**Review by robcasloz — APPROVED** [review]
Looks good now, thanks for addressing my feedback and for the explanation about `LineWidget.java`.

**Comment by tobiasholenstein** [comment]
Thanks @TobiHartmann and @robcasloz for the reviews!

/integrate

**Pull request closed without merging**
