### PR TITLE
8340171: CDS: Enhance bitmap truncation

### PR DESCRIPTION
**Pull request by shipilev**
Current CDS archive ships multiple bitmaps. Archival/loading code makes a useful optimization: it truncates the bitmaps at the beginning when it is known the prefix contains many zeroes. The object sorting code additionally sorts the pointer-rich objects at the end of the archive, increasing the zero-prefix length.

This optimization works less efficiently after [JDK-8338912](https://bugs.openjdk.org/browse/JDK-8338912), which moved the (pointer-rich) roots array at the beginning of the archive. We need to enhance current bitmap handling mechanism to truncate bitmaps better.

This PR does two things: a) enables bitmap truncation for both leading and trailing zeros; b) sorts the oop-rich objects at the beginning, where the oop-rich roots array is.

CDS archive sizes:

```
# Before JDK-8338912
$ ls -la build/linux-x86_64-server-release/images/jdk/lib/server/*.jsa
15450112 build/linux-x86_64-server-release/images/jdk/lib/server/classes.jsa
15851520 build/linux-x86_64-server-release/images/jdk/lib/server/classes_nocoops.jsa

# After JDK-8338912: +8..12K regression in size
$ ls -la build/linux-x86_64-server-release/images/jdk/lib/server/*.jsa
15462400 build/linux-x86_64-server-release/images/jdk/lib/server/classes.jsa
15859712 build/linux-x86_64-server-release/images/jdk/lib/server/classes_nocoops.jsa

# After this fix: recovered to pre-JDK-8338912 levels
$ ls -la build/linux-x86_64-server-release/images/jdk/lib/server/*.jsa
15450112 build/linux-x86_64-server-release/images/jdk/lib/server/classes.jsa
15851520 build/linux-x86_64-server-release/images/jdk/lib/server/classes_nocoops.jsa
```

Additional testing:
 - [x] Linux x86_64 server fastdebug, `runtime/cds`, `tier1`
 - [x]  Linux x86_64 server fastdebug, `all`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340171](https://bugs.openjdk.org/browse/JDK-8340171): CDS: Enhance bitmap truncation (**Enhancement** - P4)

### Reviewers
 * [Matias Saavedra Silva](https://openjdk.org/census#matsaave) (@matias9927 - **Reviewer**)
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21010/head:pull/21010` \
`$ git checkout pull/21010`

Update a local copy of the PR: \
`$ git checkout pull/21010` \
`$ git pull https://git.openjdk.org/jdk.git pull/21010/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21010`

View PR using the GUI difftool: \
`$ git pr show -t 21010`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21010.diff">https://git.openjdk.org/jdk/pull/21010.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21010#issuecomment-2352331151)

### CODE REVIEW

**Review by matias9927 — APPROVED** [review]
Looks good! Just one question:
Since the pointer rich objects are now at the beginning, does that mean that the number of leading zeros is now very small? We might be losing the benefit of truncating if it's only a few bits.

**Comment by shipilev** [comment]
>  Since the pointer rich objects are now at the beginning, does that mean that the number of leading zeros is now very small? We might be losing the benefit of truncating if it's only a few bits.

Maybe. I think we keep the leading truncation to cater for native ptrs bitmap, the object with which are logically "in the middle". My first iteration flipped leading-truncate to trailing-truncate completely, and footprint regressed a bit, I assumed because of that. So I opted to make a more general leading- and trailing-truncate to avoid surprises in future.

**Review by iklam — APPROVED** [review]
LGTM.

Currently we have lots of pointers in the tables at the end of the  RO region. If we change those pointers to relative offsets, then `FileMapInfo::remove_bitmap_zeros` would be able to remove more zeros from there.

**Comment by rose00** [comment]
I'm racking my brain to figure out if there is some kind of regression test we could write to detect a future situation like this:  (a) Someone changes the AOT cache so that there is a burst of new oops or metadata pointers injected, and then (b) the pointer bitmap loses its clever compression.  How will we notice such a thing?

I have an idea; this is the best I've got ATM:  Print a log message that gives the density of one-bits in the pointer map (out of total map size).  Maybe also the density of non-zero WORDS in the pointer map.  It's a "figure of merit"; 50-100% would be awesomely good, 1% would be very bad .  Write a regression test that detects if that metric goes out of some reasonable range, for some representative workload.  It has to be a tentative failure, kind of like a test timeout or excessive pause time.

**Comment by shipilev** [comment]
> I'm racking my brain to figure out if there is some kind of regression test we could write to detect a future situation like this: (a) Someone changes the AOT cache so that there is a burst of new oops or metadata pointers injected, and then (b) the pointer bitmap loses its clever compression. How will we notice such a thing?

Hey, I filed https://bugs.openjdk.org/browse/JDK-8340516 for this. It would probably take a some time to figure out, since there is an ambiguity in how to achieve this. So I would rather see it addressed separately.

**Comment by shipilev** [comment]
Monday morning, I am integrating :)

/integrate

**Pull request closed without merging**
