### PR TITLE
8265332: gtest/LargePageGtests.java OOMEs on -XX:+UseSHM cases

### PR DESCRIPTION
**Pull request by shipilev**
It looks like some `+UseSHM` test cases added by [JDK-8213269](https://bugs.openjdk.java.net/browse/JDK-8213269) reliably blow up the VM log reader with OOME. There are lots of `OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory.` in the log, if you increase the test heap size. AFAIU, many of those messages are expected from the new test cases.

I believe ultimately this test produces a virtually unbounded number of warning messages, which would eventually blow out the Java heap in test infra parsers. This is a reliable tier1 failure on my TR 3970X, probably because it has enough cores to run 30 threads concurrently for 15 seconds all spewing warning messages.

#### Try 1

The first attempt recognizes that `ConcurrentTestRunner` runs a time-bound number of iterations, which means the faster machine is, the more warning messages would be printed. Then, the way out is to make `ConcurrentTestRunner` to cap the number of iterations, so that VM output length is more predictable.

Test times before:

```
# default
[       OK ] os_linux.reserve_memory_special_concurrent_vm (15003 ms)

# -XX:+UseLargePages
[       OK ] os_linux.reserve_memory_special_concurrent_vm (16121 ms)

# -XX:+UseLargePages -XX:LargePageSizeInBytes=1G
[       OK ] os_linux.reserve_memory_special_concurrent_vm (15006 ms)

# -XX:+UseLargePages -XX:+UseSHM
[       OK ] os_linux.reserve_memory_special_concurrent_vm (15030 ms)
```

Test times after:

```
# default
[       OK ] os_linux.reserve_memory_special_concurrent_vm (15003 ms)

# -XX:+UseLargePages
[       OK ] os_linux.reserve_memory_special_concurrent_vm (16071 ms)

# -XX:+UseLargePages -XX:LargePageSizeInBytes=1G
[       OK ] os_linux.reserve_memory_special_concurrent_vm (15006 ms)

# -XX:+UseLargePages -XX:+UseSHM
[       OK ] os_linux.reserve_memory_special_concurrent_vm (1190 ms)

```
The major difference is that the last mode gets capped by `maxIteration`. This fixes the test failure, as `-XX:+UseSHM` case would produce lots of warnings on my machine.

#### Try 2

The second attempt run the tests with `-XX:-PrintWarnings` to avoid warning log overload.

Additional testing:
 - [x] `os_linux` gtest
 - [x] `gtest/LargePageGtests.java` used to fail, now passes

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265332](https://bugs.openjdk.java.net/browse/JDK-8265332): gtest/LargePageGtests.java OOMEs on -XX:+UseSHM cases

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3542/head:pull/3542` \
`$ git checkout pull/3542`

Update a local copy of the PR: \
`$ git checkout pull/3542` \
`$ git pull https://git.openjdk.java.net/jdk pull/3542/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3542`

View PR using the GUI difftool: \
`$ git pr show -t 3542`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3542.diff">https://git.openjdk.java.net/jdk/pull/3542.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
I think a better and simpler way would be to make those messages conditional. IMHO only fatal error information should be unconditionally printed. This is not fatal, since if we get no large pages the VM would just happily switch to small pages. I wanted to quieten these messages for a long time, but never dared because of backward compatibility. But maybe we should just do it.

Another useful fix, for a different RFE maybe, would be to limit size of output from chatty sub processes in the test framework to something sensible.

**Comment by shipilev** [comment]
All right! How about we run these tests with `-XX:-PrintWarnings` then? See new, much simpler commit.

**Review by tstuefe — APPROVED** [review]
Good and trivial. Thanks!

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
