### PR TITLE
8341481: [perf] vframeStreamCommon constructor may be optimized

### PR DESCRIPTION
**Pull request by IvaVladimir**
Optimize constructor to skip extra copy for registers. The tier1 tests are OK. The Specjvm2008 benchmark reports ~1% improvement.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341481](https://bugs.openjdk.org/browse/JDK-8341481): [perf] vframeStreamCommon constructor may be optimized (**Enhancement** - P4)

### Reviewers
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22173/head:pull/22173` \
`$ git checkout pull/22173`

Update a local copy of the PR: \
`$ git checkout pull/22173` \
`$ git pull https://git.openjdk.org/jdk.git pull/22173/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22173`

View PR using the GUI difftool: \
`$ git pr show -t 22173`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22173.diff">https://git.openjdk.org/jdk/pull/22173.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22173#issuecomment-2480234907)
</details>

### CODE REVIEW

**Comment by dwhite-intel** [comment]
@kimbarrett - Hi! This is the issue with copy constructors that I mentioned in the parking lot a while back.

The existing code for stack walking by vFrames is allocating multiple KB for 2 temporary RegisterMap structs, and copying between them via default copy constructors. The temps are unnecessary. 

We believe the performance boost in SPECjbb and SPECjvm:serial are more due to not polluting the L1 cache (improving cache hit rates of other code) than the actual instruction overhead of the copy.

I tried to make the RegisterMap copy constructor private so no one would use it, but there are one or two cases that still use the copy constructor that we didn't have a fix for - maybe you'll see something. Oops, I can't find the examples right off.

**Review by sspitsyn — APPROVED** [review]
Looks good to me.

**Comment by IvaVladimir** [comment]
/integrate
Thanks for your review!

**Pull request closed without merging**
