### PR TITLE
8334248: Invalid error for early construction local class constructor method reference

### PR DESCRIPTION
**Pull request by archiecobbs**
The new "flexible constructors" JEP 482 specifies that a local class declared in an early construction context does not have an immediate outer instance, i.e., it has the same behavior as an anonymous class would in that situation.

However, the compiler still (incorrectly) tries to verify that an outer instance exists in the case of a method reference to the local class' constructor.

Example:

````java

import java.util.function.Supplier;

class EarlyLocalCtorRef {

    EarlyLocalCtorRef() {
        class InnerLocal { }
        this(InnerLocal::new);
    }

    EarlyLocalCtorRef(Supplier<Object> s) {
    }
}
````

Expected output: Successful compilation.

Actual output:

````
EarlyLocalCtorRef.java:5: error: cannot reference this before supertype constructor has been called
        this(InnerLocal::new);
             ^ 
````

The fix is to not look for an implicit outer instance for classes that don't have one when encountering a constructor method reference.

**NOTE:** The test added here will fail until [JDK-8333313](https://bugs.openjdk.org/browse/JDK-8333313) is fixed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8334248](https://bugs.openjdk.org/browse/JDK-8334248): Invalid error for early construction local class constructor method reference (**Bug** - P4)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**) ⚠️ Review applies to [18491c44](https://git.openjdk.org/jdk/pull/19705/files/18491c44689375d12c3b756d9b5c9883c61848c5)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19705/head:pull/19705` \
`$ git checkout pull/19705`

Update a local copy of the PR: \
`$ git checkout pull/19705` \
`$ git pull https://git.openjdk.org/jdk.git pull/19705/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19705`

View PR using the GUI difftool: \
`$ git pr show -t 19705`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19705.diff">https://git.openjdk.org/jdk/pull/19705.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19705#issuecomment-2166275181)

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Looks good

**Comment by archiecobbs** [comment]
FYI, I said `/integrate` already but we should probably wait for `/sponsor` until [JDK-8333313](https://bugs.openjdk.org/browse/JDK-8333313) is fixed so we don't break the build.

**Comment by mcimadamore** [comment]
> FYI, I said `/integrate` already but we should probably wait for `/sponsor` until [JDK-8333313](https://bugs.openjdk.org/browse/JDK-8333313) is fixed so we don't break the build.

Why would this fix break the build?

**Comment by mcimadamore** [comment]
> > FYI, I said `/integrate` already but we should probably wait for `/sponsor` until [JDK-8333313](https://bugs.openjdk.org/browse/JDK-8333313) is fixed so we don't break the build.
> 
> Why would this fix break the build?

Ah ok, it's a test issue...

**Comment by mcimadamore** [comment]
Please edit the `integrate` command so that this PR cannot be integrated by accident

**Comment by mcimadamore** [comment]
```
class Outer {
    void m() { }

    class Inner {
        Inner() {
            class Foo { void g() { m(); } }
            super();
            class Bar { static void r() { new Foo(); } };
        }
    }
}
```

This seems very related to what's being fixed here. I'm worried that the fix might not go deep enough. E.g. what about the method-reference variant of the above:

```
```
class Outer {
    void m() { }

    class Inner {
        Inner() {
            class Foo { void g() { m(); } }
            super();
            class Bar { static void r() { Supplier<Foo> sfoo = Foo::new; } };
        }
    }
}
```

**Comment by archiecobbs** [comment]
> I'm worried that the fix might not go deep enough. E.g. what about the method-reference variant of the above:

A couple of random thoughts...

For me with all current patches applied, the compiler correctly handles the version of `Outer.java` with `Foo::new`:
```
Outer.java:10: error: invalid constructor reference
            class Bar { static void r() { Supplier<Foo> sfoo = Foo::new; } };
                                                               ^
  cannot access constructor Foo()
    an enclosing instance of type Outer.Inner is not in scope
```
But it throws the usual NPE on the `Foo.new()` version:
```
java.lang.NullPointerException: Cannot read field "sym" because "this.lvar[0]" is null
	at jdk.compiler.interim/com.sun.tools.javac.jvm.Code.emitop0(Code.java:572)
	at jdk.compiler.interim/com.sun.tools.javac.jvm.Items$SelfItem.load(Items.java:369)
	at jdk.compiler.interim/com.sun.tools.javac.jvm.Gen.visitIdent(Gen.java:2357)
```
So `Outer.java` doesn't seem to be a evidence that the fix in PR #19705 is incorrect. It might be of course, but if so it would be for some other reason.

I guess the question is: must we invoke `resolveImplicitThis()` when the constructed class has `NOOUTERTHIS`?

* If so, then how do you explain the counter-example (from amber-dev email) for method references when you do that (showing a bogus error being generated):
```
$ cat EarlyLocalTest3.java
public class EarlyLocalTest3 {

    class Test {
        Test() {
            class InnerLocal { }
            Runnable r = InnerLocal::new;
            r.run();
            super();
        }
    }
}
$ javac -enable-preview --release 24 EarlyLocalTest3.java
../test/langtools/tools/javac/SuperInit/EarlyLocalTest3.java:6: error: cannot reference this before supertype constructor has been called
            Runnable r = InnerLocal::new;
                         ^
```
* If not, then there must be some other cause for the bug. Regarding this possibility, note there is another bug relating to "bogus capture in static context" e.g. [JDK-8322882](https://bugs.openjdk.org/browse/JDK-8322882). So there may be a common root cause these share.

**Comment by mcimadamore** [comment]
> > I'm worried that the fix might not go deep enough. E.g. what about the method-reference variant of the above:
> 
> A couple of random thoughts...
> 
> For me with all current patches applied, the compiler correctly handles the version of `Outer.java` with `Foo::new`:
> 
> ```
> Outer.java:10: error: invalid constructor reference
>             class Bar { static void r() { Supplier<Foo> sfoo = Foo::new; } };
>                                                                ^
>   cannot access constructor Foo()
>     an enclosing instance of type Outer.Inner is not in scope
> ```

The fix is still not doing its job. But it seems another check kicks in, and saves the day - namely:

https://github.com/openjdk/jdk/blob/master/src/jdk.compiler/share/classes/com/sun/tools/javac/comp/Resolve.java#L3713

Note that the error message you get is not the same error message mentioned in this PR - meaning that the check you tweaked is now effectively disabled in this case.


> 
> But it throws the usual NPE on the `Foo.new()` version:
> 
> ```
> java.lang.NullPointerException: Cannot read field "sym" because "this.lvar[0]" is null
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Code.emitop0(Code.java:572)
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Items$SelfItem.load(Items.java:369)
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Gen.visitIdent(Gen.java:2357)
> ```

In this case the check that rescued the above example is not ran, as that check is specific to method references. So the compiler just crashes.

> 
> So `Outer.java` doesn't seem to be a evidence that the fix in PR #19705 is incorrect. It might be of course, but if so it would be for some other reason.
> 
> I guess the question is: must we invoke `resolveImplicitThis()` when the constructed class has `NOOUTERTHIS`?

I'm actually checking what we should do from a JLS perspective. I see some rules in 15.9.2, but it seems to me that the only relevant case to check, for local and anon class creation is that they don't occur in a static context. In all other cases, I don't think it's possible to refer to a local class w/o the necessary enlcosing instance (if you don't have the enclosing instance you are not in the same scope as the local class, so you can't even name it). We're discussing this with Dan and Gavin.
> 
>     * If so, then how do you explain the counter-example (from amber-dev email) for method references when you do that (showing a bogus error being generated):
> 
> 
> ```
> $ cat EarlyLocalTest3.java
> public class EarlyLocalTest3 {
> 
>     class Test {
>         Test() {
>             class InnerLocal { }
>             Runnable r = InnerLocal::new;
>             r.run();
>             super();
>         }
>     }
> }
> $ javac -enable-preview --release 24 EarlyLocalTest3.java
> ../test/langtools/tools/javac/SuperInit/EarlyLocalTest3.java:6: error: cannot reference this before supertype constructor has been called
>             Runnable r = InnerLocal::new;
>                          ^
> ```
Well, there is logic inside Resolve::resolveSelf which seems to look for "env.info.ctorPrologue" and issue the above error if the flag is set. It might be that this code needs an update.
> 
>     * If not, then there must be some other cause for the bug. Regarding this possibility, note there is another bug relating to "bogus capture in static context" e.g. [JDK-8322882](https://bugs.openjdk.org/browse/JDK-8322882). So there may be a common root cause these share.

I think it is the same issue. Attr::visitNewClass has code that is 1-1 with the one you have in this fix. The only difference between the method reference code and the `new` code is the presence of that additional enclosing instance check (the correctness of which I'm also not sure) when the method reference is being resolved, as I explained earlier. If that check wasn't there the two programs would fail in exactly the same way.

**Comment by archiecobbs** [comment]
Ah, gotcha. Thanks for the explanations.

**Comment by mcimadamore** [comment]
> > I'm worried that the fix might not go deep enough. E.g. what about the method-reference variant of the above:
> 
> A couple of random thoughts...
> 
> For me with all current patches applied, the compiler correctly handles the version of `Outer.java` with `Foo::new`:
> 
> ```
> Outer.java:10: error: invalid constructor reference
>             class Bar { static void r() { Supplier<Foo> sfoo = Foo::new; } };
>                                                                ^
>   cannot access constructor Foo()
>     an enclosing instance of type Outer.Inner is not in scope
> ```
> 
> But it throws the usual NPE on the `Foo.new()` version:
> 
> ```
> java.lang.NullPointerException: Cannot read field "sym" because "this.lvar[0]" is null
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Code.emitop0(Code.java:572)
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Items$SelfItem.load(Items.java:369)
> 	at jdk.compiler.interim/com.sun.tools.javac.jvm.Gen.visitIdent(Gen.java:2357)
> ```
> 
> So `Outer.java` doesn't seem to be a evidence that the fix in PR #19705 is incorrect. It might be of course, but if so it would be for some other reason.
> 
> I guess the question is: must we invoke `resolveImplicitThis()` when the constructed class has `NOOUTERTHIS`?
> 
>     * If so, then how do you explain the counter-example (from amber-dev email) for method references when you do that (showing a bogus error being generated):
> 
> 
> ```
> $ cat EarlyLocalTest3.java
> public class EarlyLocalTest3 {
> 
>     class Test {
>         Test() {
>             class InnerLocal { }
>             Runnable r = InnerLocal::new;
>             r.run();
>             super();
>         }
>     }
> }
> $ javac -enable-preview --release 24 EarlyLocalTest3.java
> ../test/langtools/tools/javac/SuperInit/EarlyLocalTest3.java:6: error: cannot reference this before supertype constructor has been called
>             Runnable r = InnerLocal::new;
>                          ^
> ```
> 
>     * If not, then there must be some other cause for the bug. Regarding this possibility, note there is another bug relating to "bogus capture in static context" e.g. [JDK-8322882](https://bugs.openjdk.org/browse/JDK-8322882). So there may be a common root cause these share.

As far as I can tell, that additional check for method reference is there "only" to generate a better error message. And, in fact, the check in Resolve dominates the one in Attr: even if the check you tweaked in this PR is commented out completely, no regression test fails.

Apparently the Attr check was added here:
https://bugs.openjdk.org/browse/JDK-8173456

As far as I can tell, the only reason the check was added was to issue an error in cases like `super(V::new)`, which sounds familiar. In other words, instead of enhancing the existing check in `Resolve` (the one above), we ended up adding another one. 

Ideally we should only keep the check in Resolve, but augment it so that it detects the issue described in 8173456.

**Comment by archiecobbs** [comment]
> As far as I can tell, that additional check for method reference is there "only" to generate a better error message. And, in fact, the check in Resolve dominates the one in Attr: even if the check you tweaked in this PR is commented out completely, no regression test fails.

That may have been true before "flexible constructors", but it's not now - when that check is commented out, this program compiles successfully for me (erroneously), leading to a verifier error:
```java
class Q {
    class Inner { }
    public Q() {
        this(Inner::new);
    }
    public Q(Runnable r) {
    }
    public static void main(String[] args) {
        new Q();
    }
}
```
> Ideally we should only keep the check in Resolve (as that generates a better error), but augment it so that it detects the issue described in 8173456.

I agree that the remaining problem seems to be within `Resolve.resolveImplicitThis()`.

See commit e0f5d183651 to this PR where I tried to fix it... I'm curious if it that change looks correct to you?

In any case, when that commit is combined with all the other patches floating around (yours & mine), all of the `langtools_javac` regression tests (including the test for JDK-8173456) are passing, and the `Q.java` example above now correctly yields:
```
Q.java:4: error: cannot reference this before supertype constructor has been called
        this(Inner::new);
             ^
1 error
```

**Comment by mcimadamore** [comment]
The patch seems to be doing something sensible (e.g. take into account that not all enclosing instances are accessible). However, as I mentioned last week, I believe we need to wait for the spec to weigh in on this matter. The checks we're tweaking correspond to this statement in the JLS (15.9.2):

```
 If C is an inner local class, then:
 ...
Otherwise, let O be the immediately enclosing class or interface declaration of C, and let U be the immediately enclosing class or interface declaration of the class instance creation expression. 
 If U is not an inner class of O or O itself, then a compile-time error occurs. 
 ```
 
 Now, if C is a local class, is there ever a case where "new C" can appear from _outside_ the lexical context in which C is defined? I don't think that's possible (Dan and Gavin seems to agree). If that's the case, then the only thing we need to check for local/anon classes is that the creation expression does not occur in a static context. This is already covered by the existing rules:

```
If C occurs in a static context, then i has no immediately enclosing instance.

Otherwise, if the class instance creation expression occurs in a static context, then a compile-time error occurs.
```

It seems to me that these rules override any other rule when it comes to local/anon classes. If so, maybe the code in `visitNew` and `visitReference` should just add a static check when the target class is a local/anon class, and leave `resolveImplicitThis` alone.

**Comment by mcimadamore** [comment]
Thinking more, my understanding of the spec is that we should never check for `hasOuterInstance` in `Attr`/`Resolve`. The spec seems to be defined in terms of the innermost enclosing instance (e.g. `getEnclosingType`), and then adds extra checks, to make sure the enclosing type is indeed accessible.

So, when we see either `new A`, or `A::new`, we should check:

* if A has as an enclosing instance. If not, there's nothing more to check.
* if the innermost enclosing instance of A is O, then we need to check if the expression occurs in the early-construction context for O. If so, error.

I don't think stuff like `NOOUTERTHIS` should even play a role here.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Comment by archiecobbs** [comment]
> And, according to this interpretation, the program in this PR should be rejected.

OK, I want to be slow & careful here because there are a few different things flying around.

First, just to state the obvious, the spec that applies here is the one attached to [JDK-8329079](https://bugs.openjdk.org/browse/JDK-8329079) (CSR for "flexible constructors").

One explicit goal of that spec is to have the compiler treat local and anonymous classes the same way with respect to outer instances. The reason for this is that we want it to be possible to define a usable local class in the constructor prologue. Practically speaking, that means:
* It's legal to define a local class in the constructor prologue.
* It's possible to instantiate that local class in the constructor prologue.

Those two goals imply that the `EarlyLocalCtorRef` given in this PR should successfully compile:
```java
class EarlyLocalCtorRef {

    EarlyLocalCtorRef() {
        class InnerLocal { }
        this(InnerLocal::new);
    }

    EarlyLocalCtorRef(Supplier<Object> s) {
    }
}
```

Now of course you/we should confirm this with Dan and Gavin, but FWIW that's my understanding of what this new spec is _supposed_ to say and consequently how the compiler is _supposed_ to behave.

So I'd say up front that if the spec doesn't actually say that, then that's a bug in the spec, not the compiler.

In any case, if you are saying the spec does in fact have a rule that disallows the above program, I don't yet see how. There is no static context involved here, so the "static context" clause you cited doesn't apply (instead, it's an early construction context).

More background: To elaborate on "treat local and anonymous classes the same way with respect to outer instances": this means `EarlyLocalCtorRef` should compile, even though class `InnerLocal` would "normally" have an outer instance of type `EarlyLocalCtorRef` (but really doesn't).

Why? It's for the same reason - has the same motivating logic - that this anonymous class example has always compiled, even though the anonymous `Runnable` class would "normally" have an outer instance of type `EarlyAnonRef` (but really doesn't):
```java
class EarlyAnonRef {

    EarlyAnonRef() {
        this(() -> new Runnable() { public void run() { } });
    }

    EarlyAnonRef(Runnable r) {
    }
}
```
It would be illegal for the anonymous `Runnable` class to refer to `EarlyAnonRef.this`, as it would be for `InnerLocal` to refer to `EarlyLocalCtorRef.this`. But that doesn't (i.e., shouldn't) mean these classes can't be declared and instantiated where they are.

At least, this is my current understanding of what the spec is meant to say and also what the spec actually says. Please confirm with Dan & Gavin though.

**Comment by mcimadamore** [comment]
> At least, this is my current understanding of what the spec is meant to say and also what the spec actually says. Please confirm with Dan & Gavin though.

They confirmed that this is what the behavior should be. We're not yet 100% sure the JLS needs further tweaks to support this in full, but I might have read too much into the spec trying to say that the enclosing instance for InnerLocal was EarlyAnonRef.

**Comment by mcimadamore** [comment]
Btw, as I was looking at this area, I realized that the following code:

```
class EarlyLocalClass {
   EarlyLocalClass() {
      class Local {
         void foo() {
            EarlyLocalClass.this.hashCode();    // this should FAIL
         }
      }
}
```

Fails as expected. But, interestingly, the error is issued very late (in `Lower` rather than in `Attr`). This has to do with the logic that sets `AttrContext::ctorPrologue`: this field is set to `false` as soon as we encounter a local class. So, by the time we see the reference to `EarlyLocalClass.this.hashCode()`, `ctorPrologue` is not set, and no error is issued.

**Comment by archiecobbs** [comment]
> But, interestingly, the error is issued very late (in Lower rather than in Attr). This has to do with the logic that sets AttrContext::ctorPrologue: this field is set to false as soon as we encounter a local class.

Any ugliness is surely due to my incomplete understanding of compiler internals. The assumption is that a new `Env` is created when we encounter a new class declaration, and so the `ctorPrologue` flag is only valid for the current class. So that would make sense that it is reset inside the local class (new `Env` there). Consistent with that, the `Resolve.findVar()`  method recurses up through each enclosing `Env`'s and checks the corresponding `ctorPrologue` flag, which corresponds to the scope in which the variable is ultimately found, for being in an early construction context But this may be incomplete or skipped in the `EarlyLocalClass.this` example... ?

**Comment by mcimadamore** [comment]
> > But, interestingly, the error is issued very late (in Lower rather than in Attr). This has to do with the logic that sets AttrContext::ctorPrologue: this field is set to false as soon as we encounter a local class.
> 
> Any ugliness is surely due to my incomplete understanding of compiler internals. The assumption is that a new `Env` is created when we encounter a new class declaration, and so the `ctorPrologue` flag is only valid for the current class. So that would make sense that it is reset inside the local class (new `Env` there). Consistent with that, the `Resolve.findVar()` method recurses up through each enclosing `Env`'s and checks the corresponding `ctorPrologue` flag, which corresponds to the scope in which the variable is ultimately found, for being in an early construction context But this may be incomplete or skipped in the `EarlyLocalClass.this` example... ?

The problem is that I don't think there's a new env creation in `visitClassDef`. This calls `Attr::attribClass` which is where the new env is fetched/created. So I think maybe you need to move the place where you set the flag to false?

**Comment by mcimadamore** [comment]
So, in the context of this PR, I think two things need to happen:
* we need to fix the `env.ctorPrologue` logic so that errors are correctly reported as part of `Attr` and not `Lower`
* we need to remove dependencies from `NOOUTERTHIS`. The idea is that we only need to call `resolveSelfXYZ` if the class being constructed is a member inner class. For local class just checking if it's static would suffice. This logic should be applied in at least three places:
- `Attr::visitNewClass`
- `Attr::visitReference`
- `Resolve::enclosingInstanceMissing`

Then, optional cleanup activities:

* decide whether to keep the `Resolve::enclosingInstanceMissing` check, or the one in `Attr::visitReference` as they are likely redundant.
* instead of the current fix, where you check for early construction context in the new `Resolve::resolveImplicitThis`, it might make sense to add the check in the loops inside `Resolve::resolveSelf` and `Resolve::resolveSelfContainingInternal`, as both methods are looping over `env` anyway.

**Comment by archiecobbs** [comment]
> The problem is that I don't think there's a new env creation in visitClassDef. This calls Attr::attribClass which is where the new env is fetched/created. So I think maybe you need to move the place where you set the flag to false?

I'm sure you're probably right but I'm not sure I fully grok this. It seems like the only correct place to set the flag (a) to true is at the start of the constructor, and (b) to false is after processing the superclass constructor invocation parameters. But it may very well be that the flag itself is stored in the wrong place, which I think is what you are saying... ?

> I think two things need to happen...

OK, unfortunately I'm not confident I can tackle all that myself (I don't even fully understand it completely). Would love for you to take the wheel if you can - as long as all the tests I've been running still pass then I'll be OK with whatever you come up with :) FWIW all current fixes & tests I've been working with (including your two refactorings) are [here](https://github.com/archiecobbs/jdk/tree/javac-pre-capture-fixes). Thanks.

**Comment by mcimadamore** [comment]
> I'm sure you're probably right but I'm not sure I fully grok this. It seems like the only correct place to set the flag (a) to true is at the start of the constructor, and (b) to false is after processing the superclass constructor invocation parameters. But it may very well be that the flag itself is stored in the wrong place, which I think is what you are saying... ?

I agree with (a) and (b). But note that the flag is also (c) set to false inside `Attr::visitClassDef`. I believe this was done to avoid an inner class "inherit" the state from the parent class. But the operation of setting the flag to false occurs on the same "env" as the _enclosing_ class (as we have not yet accessed/created the env for the inner class, that will happen in `Attr::attribClass`). I think this is probably solved by just moving the code for (c) around.

**Comment by mcimadamore** [comment]
> OK, unfortunately I'm not confident I can tackle all that myself (I don't even fully understand it completely). Would love for you to take the wheel if you can - as long as all the tests I've been running still pass then I'll be OK with whatever you come up with :) FWIW all current fixes & tests I've been working with (including your two refactorings) are [here](https://github.com/archiecobbs/jdk/tree/javac-pre-capture-fixes). Thanks.

I'm happy to take a look.

**Comment by archiecobbs** [comment]
> But note that the flag is also (c) set to false inside Attr::visitClassDef. I believe this was done to avoid an inner class "inherit" the state from the parent class. But the operation of setting the flag to false occurs on the same "env" as the enclosing class (as we have not yet accessed/created the env for the inner class, that will happen in Attr::attribClass). I think this is probably solved by just moving the code for (c) around.

Ah - gotcha. Interestingly, this bug doesn't change which programs compile, but it does change the error message that gets generaged - and during which phase of compilation it is generated (another `Attr` vs. `Lower` thing). I've created [JDK-8334488](https://bugs.openjdk.org/browse/JDK-8334488) to track this and will fix.

> I'm happy to take a look.

Great - thanks. Let me know if I can help.

**Comment by archiecobbs** [comment]
Closing this PR per [discussion on amber-dev](https://mail.openjdk.org/pipermail/amber-dev/2024-June/008865.html).

**Pull request closed without merging**
