### PR TITLE
8268131: 2 java/foreign tests timed out

### PR DESCRIPTION
**Pull request by mcimadamore**
This patch increases time out for both TestUpcall and TestDowncall. These tests were already long-running, but with JEP-412, they were beefed up even more, so now they time out on some debug builds.

This patch also address a minor issue in TestResourceScope which can sometimes lead to intermittent failure, depending on how threads are scheduled.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268131](https://bugs.openjdk.java.net/browse/JDK-8268131): 2 java/foreign tests timed out

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to b432907653ecf3acb902053db5de4b80069a234d

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4321/head:pull/4321` \
`$ git checkout pull/4321`

Update a local copy of the PR: \
`$ git checkout pull/4321` \
`$ git pull https://git.openjdk.java.net/jdk pull/4321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4321`

View PR using the GUI difftool: \
`$ git pr show -t 4321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4321.diff">https://git.openjdk.java.net/jdk/pull/4321.diff</a>

</details>

### CODE REVIEW

**Comment by mcimadamore** [comment]
> _Mailing list message from [Joe Darcy](mailto:joe.darcy@oracle.com) on [core-libs-dev](mailto:core-libs-dev@mail.openjdk.java.net):_
> 
> Can the test cases be broken into pieces or otherwise decomposed into
> several shorter-running tests?
> 
> -Joe
> 
> On 6/2/2021 2:35 PM, Maurizio Cimadamore wrote:

I believe they can - but it would require more work - for now the goal was to bring tier4 testing back to stable.

**Comment by dcubed-ojdk** [comment]
I would definitely prefer to have Tier4 quiet down for the upcoming code fork
so increasing the timeout is good from my GK POV.

These two tests were using the default timeout of 120 seconds/2 minutes and
with a default timeoutFactor of 4 (set by the test task), the total timeout was
480 seconds/8 minutes.

I recommend change the timeout from 720 to 240. That will give you a total
timeout of 960 seconds/16 minutes. For the TestDowncall.java failure, that
should cover that case. For the TestUpcall.java failure, we don't know if
doubling the total timeout will cover that case or not because that test
didn't pass while the timeout handler is running.

However, doubling is a good start for a bump. Also, using a higher timeout
value doesn't hurt anything if the test doesn't timeout.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

You might starting with 240 instead of 720 for the initial timeout bump.

**Comment by mcimadamore** [comment]
I've adjusted timeout to 2409, following suggestions - let's see what happens.

**Pull request closed without merging**
