### PR TITLE
8272334: com.sun.net.httpserver.HttpExchange: Improve API doc of getRequestHeaders

### PR DESCRIPTION
**Pull request by FrauBoes**
This is a doc-only fix that improves the wording of the API doc of `getRequestHeaders()`. The other changes are trivial cleanup.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272334](https://bugs.openjdk.java.net/browse/JDK-8272334): com.sun.net.httpserver.HttpExchange: Improve API doc of getRequestHeaders

### Reviewers
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**)
 * [Michael McMahon](https://openjdk.java.net/census#michaelm) (@Michael-Mc-Mahon - **Reviewer**) ⚠️ Review applies to 5fdccc3213e8b6f9c8f733c721d3b922381426cb
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5100/head:pull/5100` \
`$ git checkout pull/5100`

Update a local copy of the PR: \
`$ git checkout pull/5100` \
`$ git pull https://git.openjdk.java.net/jdk pull/5100/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5100`

View PR using the GUI difftool: \
`$ git pr show -t 5100`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5100.diff">https://git.openjdk.java.net/jdk/pull/5100.diff</a>

</details>

### CODE REVIEW

**Review by dfuch — APPROVED** [review]

**Comment by dfuch** [comment]
Please have Michael review the changes too before pushing. I don't think this needs a CSR - would other reviewers agree?

**Review by Michael-Mc-Mahon — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]

**Comment by FrauBoes** [comment]
CSR https://bugs.openjdk.java.net/browse/JDK-8272565

**Review by ChrisHegarty — APPROVED** [review]

**Review by dfuch — APPROVED** [review]

**Pull request closed without merging**
