### PR TITLE
8321374: Add a configure option to explicitly set CompanyName property in VersionInfo resource for Windows exe/dll

### PR DESCRIPTION
**Pull request by fthevenet**
When building OpenJDK on the Windows platform, version information are embedded as compiled resources into every native library and executable, which typically contain version numbers, copyright information, product name and vendor name (called "Company name" in this context).

Currently, the value for "Company name" is always the same as that of "vendor-name" but it It would be really useful to some build scenarios to allow for the "company name" property embedded in the VersionInfo compiled resources to be different from the "vendor name" property that is used within the JVM (e.g. java -version). 

This PR adds  a "--with-jdk-rc-company-name" configure option which can be used to set "Company name" to its own value, independently of "'vendor-name", in the same fashion as the existing "--with-jdk-rc-name", used to override the values of "File description" and "Product name".

If "--with-jdk-rc-company-name" isn't used, then the vendor-name value is used instead, reproducing the same behavior than without this patch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321374](https://bugs.openjdk.org/browse/JDK-8321374): Add a configure option to explicitly set CompanyName property in VersionInfo resource for Windows exe/dll (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16972/head:pull/16972` \
`$ git checkout pull/16972`

Update a local copy of the PR: \
`$ git checkout pull/16972` \
`$ git pull https://git.openjdk.org/jdk.git pull/16972/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16972`

View PR using the GUI difftool: \
`$ git pr show -t 16972`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16972.diff">https://git.openjdk.org/jdk/pull/16972.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16972#issuecomment-1843082700)

### CODE REVIEW

**Comment by fthevenet** [comment]
NB: Test "GathererTest::testMassivelyComposedGatherers" in tier1 on linux-86 is failing for reasons unrelated to this PR.

**Review by erikj79 — APPROVED** [review]

**Review by magicus — APPROVED** [review]

**Comment by fthevenet** [comment]
Thanks for the reviews @erikj79 and @magicus.
Could one of you please sponsor this?

Cheers!

**Comment by fthevenet** [comment]
Thanks @magicus

**Pull request closed without merging**
