### PR TITLE
8326831 Clarify test harness control variables in make help

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Clarifying text in `make help` output on how to list variables for e.g. JTREG='...'.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326831](https://bugs.openjdk.org/browse/JDK-8326831): Clarify test harness control variables in make help (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18028/head:pull/18028` \
`$ git checkout pull/18028`

Update a local copy of the PR: \
`$ git checkout pull/18028` \
`$ git pull https://git.openjdk.org/jdk.git pull/18028/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18028`

View PR using the GUI difftool: \
`$ git pr show -t 18028`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18028.diff">https://git.openjdk.org/jdk/pull/18028.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18028#issuecomment-1966614083)

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
I'll note that you still need to run configure to execute `make test-only JTREG=help`. Should this really be necessary?

**Comment by LudwikJaniuk** [comment]
Also, while `make test-only JTREG=help` lists the valid options, it still does nothing to document their meaning.

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
> I'll note that you still need to run configure to execute make test-only JTREG=help. Should this really be necessary?

I agree that it would be convenient, in some rare usecase, to be able to run this without configure, but the added complexity needed to implement that is hardly worth the effort. In practice, if you are about to run `make test`, and trying to construct your command line, you would have already run configure.

> Also, while `make test-only JTREG=help` lists the valid options, it still does nothing to document their meaning.

The documentation for running tests can be found in `doc/testing.md`. The help output from make is just meant to be a short version reminder for common cases. The list is constructed programmatically from the makefile constructs used to define the possible parameters, so it's guaranteed to be up to date. That is also why you must call the same target as when using the parameter (`test` or `test-only` in this case) as otherwise you wouldn't end up in the makefile where the parameters are defined. You can't really expect makefiles to be fully self documenting as we are limited by what we can reasonably implement in makefiles after all, and these makefiles are really pushing the boundaries of that already.

**Comment by LudwikJaniuk** [comment]
Thanks for the insight Erik!

**Comment by lgxbslgx** [comment]
I use the command `make test-only JTREG=help` locally, the outputed message seems an error (shown below). Does it work as expected?

```
Building target 'test-only' in configuration 'linux-x86_64-server-fastdebug'
Valid keywords for JTREG:
RunTests.gmk:205: *** Re-run without 'help' to continue.  Stop.
JOBS TIMEOUT_FACTOR FAILURE_HANDLER_TIMEOUT TEST_MODE ASSERT VERBOSE RETAIN TEST_THREAD_FACTORY MAX_MEM RUN_PROBLEM_LISTS RETRY_COUNT REPEAT_COUNT MAX_OUTPUT REPORT OPTIONS JAVA_OPTIONS VM_OPTIONS KEYWORDS EXTRA_PROBLEM_LISTS LAUNCHER_OPTIONS.
gmake[2]: *** [make/Main.gmk:797: test] Error 2

ERROR: Build failed for target 'test-only' in configuration 'linux-x86_64-server-fastdebug' (exit code 2) 

No indication of failed target found.
HELP: Try searching the build log for '] Error'.
HELP: Run 'make doctor' to diagnose build problems.

make[1]: *** [/home/lgx/source/java/fast-jdk/make/Init.gmk:323: main] Error 2
make: *** [/home/lgx/source/java/fast-jdk/make/Init.gmk:189: test-only] Error 2
```

The location of the `RunTests.gmk:205: *** Re-run without 'help' to continue.  Stop.` is wrong. But it sometimes works good (Shown below).

```
Building target 'test-only' in configuration 'linux-x86_64-server-fastdebug'
Valid keywords for JTREG:
JOBS TIMEOUT_FACTOR FAILURE_HANDLER_TIMEOUT TEST_MODE ASSERT VERBOSE RETAIN TEST_THREAD_FACTORY MAX_MEM RUN_PROBLEM_LISTS RETRY_COUNT REPEAT_COUNT MAX_OUTPUT REPORT OPTIONS JAVA_OPTIONS VM_OPTIONS KEYWORDS EXTRA_PROBLEM_LISTS LAUNCHER_OPTIONS.
RunTests.gmk:205: *** Re-run without 'help' to continue.  Stop.
gmake[2]: *** [make/Main.gmk:797: test] Error 2

ERROR: Build failed for target 'test-only' in configuration 'linux-x86_64-server-fastdebug' (exit code 2) 

No indication of failed target found.
HELP: Try searching the build log for '] Error'.
HELP: Run 'make doctor' to diagnose build problems.

make[1]: *** [/home/lgx/source/java/fast-jdk/make/Init.gmk:323: main] Error 2
make: *** [/home/lgx/source/java/fast-jdk/make/Init.gmk:189: test-only] Error 2
```

**Comment by LudwikJaniuk** [comment]
It's interesting that the order of those two lines can change. I have no idea what causes it.

**Review by lgxbslgx — APPROVED** [review]
> I have no idea what causes it.

Nevermind. The patch looks good.

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
