### PR TITLE
8345659: Fix broken alignment after ReservedSpace splitting in GC code

### PR DESCRIPTION
**Pull request by stefank**
The Serial and Parallel GCs create a ReservedSpace for the total heap and then splits it into a young generation ReservedSpace and an old generation ReservedSpace. The latter operation creates an ReservedSpace with an alignment that doesn't match the base address. This bug is benign because the ReservedSpaces are short-lived and we don't look at the alignment. However, if we are to add stricter checks when creating ReservedSpaces we need to fix this. 

Tested with tier1-3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8345659](https://bugs.openjdk.org/browse/JDK-8345659): Fix broken alignment after ReservedSpace splitting in GC code (**Enhancement** - P4)

### Reviewers
 * [Albert Mingkun Yang](https://openjdk.org/census#ayang) (@albertnetymk - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22602/head:pull/22602` \
`$ git checkout pull/22602`

Update a local copy of the PR: \
`$ git checkout pull/22602` \
`$ git pull https://git.openjdk.org/jdk.git pull/22602/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22602`

View PR using the GUI difftool: \
`$ git pr show -t 22602`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22602.diff">https://git.openjdk.org/jdk/pull/22602.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22602#issuecomment-2522754841)
</details>

### CODE REVIEW

**Review by albertnetymk — COMMENTED** [review]
I wonder if doing the same for `first_part` makes it more symmetric/readable.

**Comment by stefank** [comment]
> I wonder if doing the same for first_part makes it more symmetric/readable.

I think it is unclear if that would help readability or not. The `first_part` reserved space has the same base as the `heap_rs`, so it is kind of natural that it inherits the alignment from `heap_rs`. To me it seems somewhat redundant to explicitly specifying `HeapAlignment` again. Any other reviewers that prefer one or the other way?

**Comment by albertnetymk** [comment]
I meant sth like `heap_rs.first_part(MaxNewSize, GenAlignment);`; then, both generations can check they are compliant wrt `GenAlignment`. Checking the `HeapAlignment` compliance, it should be done before this; at another abstraction level.

**Comment by stefank** [comment]
You are right, that seems like a good thing to do.

**Review by albertnetymk — APPROVED** [review]

**Review by xmas92 — APPROVED** [review]
lgtm.

The alignment always require extra thinking as it has multiple meanings. It is both the required alignment of the base, but it is also the granularity / alignment of the size. But we have the same meaning when it comes to HeapAlignment, SpaceAlignment and GenAlignment. So the partition size does not break this invariant.

It is unfortunate that we do not assert that these invariants are maintained when we partition a reserved space. Something like:
```diff
ReservedSpace::ReservedSpace(char* base, size_t size, size_t alignment, size_t page_size,
                             bool special, bool executable) : _fd_for_heap(-1) {
  assert((size % os::vm_allocation_granularity()) == 0,
         "size not allocation aligned");
+ assert(alignment != 0, "must be set");
+ assert(size % alignment == 0, "must be");
+ assert((uintptr_t)base % alignment == 0, "must be");
  initialize_members(base, size, alignment, page_size, special, executable);
}
```

But I know you are working on refactoring and improving the ReservedSpace. Let us hope we can make this more robust in the future.

**Comment by stefank** [comment]
>  but it is also the granularity / alignment of the size

I don't think that this is a strict requirement throughout the JVM's usage of ReservedSpace. AFAIU, the alignment only strictly applies to the base pointer, but some users has also has an 'alignment' requirement (as opposed to a 'page_size' requirement) on the size. Let's take an extra round thinking about that for the ReservedSpace rewrites.

> But I know you are working on refactoring and improving the ReservedSpace. Let us hope we can make this more robust in the future.

Yes, I have extra verification in my other patch.

**Comment by stefank** [comment]
Thanks both for reviewing!

**Comment by stefank** [comment]
So, for completeness of the discussion. AFAICT, we have `partition`, `last_part`, `first_part`, and `space_for_range` that all completely skips verifying against `alignment`. The intention is to try to enforce the alignment in an up-coming RFE.

**Pull request closed without merging**
