### PR TITLE
JDK-8299479: Remove metaprogramming/decay.hpp

### PR DESCRIPTION
**Pull request by jcking**
Code cleanup of pre-C++11 <type_traits> implementations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299479](https://bugs.openjdk.org/browse/JDK-8299479): Remove metaprogramming/decay.hpp

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [3c70a1cd](https://git.openjdk.org/jdk/pull/11816/files/3c70a1cd149dbf44b0dd56ed72e5acbbc549f730)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11816/head:pull/11816` \
`$ git checkout pull/11816`

Update a local copy of the PR: \
`$ git checkout pull/11816` \
`$ git pull https://git.openjdk.org/jdk pull/11816/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11816`

View PR using the GUI difftool: \
`$ git pr show -t 11816`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11816.diff">https://git.openjdk.org/jdk/pull/11816.diff</a>

</details>

### CODE REVIEW

**Comment by jcking** [comment]
@kimbarrett Another one.

**Review by tschatzl — APPROVED** [review]

**Comment by jcking** [comment]
Forgot to remove the actual header apparently, updated.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Pull request closed without merging**
