### PR TITLE
8329726: Use non-short forward jumps in lightweight locking

### PR DESCRIPTION
**Pull request by rkennke**
This turns a few short-jumps to long-jumps in x86 lightweight locking code paths. When running with -XX:+ShowMessageBoxOnError, MA::stop() generates more code and jccb is not sufficient to address this.

Two of the jccb are in ASSERT path anyway. However, another is also in a product path. We *could* generate jccb or jcc conditionally on ShowMessageBoxOnError, however, I don't think it is worth the trouble. WDYT?

Unfortunately, I could not make a simple test-case, because ShowMessageBoxOnError stops and waits on error, which would make jtreg time-out.

Testing:
 - [x] manual test with dacapo as provided in the bug report
 - [ ] tier1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329726](https://bugs.openjdk.org/browse/JDK-8329726): Use non-short forward jumps in lightweight locking (**Bug** - P3)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [f6231d8f](https://git.openjdk.org/jdk/pull/18657/files/f6231d8f81dea88e1a87af6b4bb5d69c43056240)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [025755b2](https://git.openjdk.org/jdk/pull/18657/files/025755b2d834669bb54d9cf8404383ba3a5f0194)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - **Reviewer**) ⚠️ Review applies to [f6231d8f](https://git.openjdk.org/jdk/pull/18657/files/f6231d8f81dea88e1a87af6b4bb5d69c43056240)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18657/head:pull/18657` \
`$ git checkout pull/18657`

Update a local copy of the PR: \
`$ git checkout pull/18657` \
`$ git pull https://git.openjdk.org/jdk.git pull/18657/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18657`

View PR using the GUI difftool: \
`$ git pr show -t 18657`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18657.diff">https://git.openjdk.org/jdk/pull/18657.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18657#issuecomment-2039829792)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
Sad to give up a short jump in synchronization code just for asserts. Maybe we give up on code readability a bit? E.g.:

```
#ifdef ASSERT
  // Check that locked label is reached with ZF set.
  Label zf_bad_zero;
  jcc(Assembler::zero, zf_correct);
  jmp(zf_bad_zero)
#endif

  bind(slow_path);

#ifdef ASSERT
  // Check that slow_path label is reached with ZF not set.
  Label zf_bad_nonZero;
  jcc(Assembler::notZero, zf_bad_nonZero);
  stop("Fast Lock ZF != 1");
  bind(zf_bad_zero);
  stop("Fast Lock ZF == 0");
  bind(zf_correct);
#endif
```

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by TobiHartmann** [comment]
Could you please add a regression test for this?

**Comment by TobiHartmann** [comment]
> Unfortunately, I could not make a simple test-case, because ShowMessageBoxOnError stops and waits on error, which would make jtreg time-out.

Although a time out is a bit of a confusing failure mode for the test, I think it would be better than no test at all, right?

**Comment by rkennke** [comment]
> > Unfortunately, I could not make a simple test-case, because ShowMessageBoxOnError stops and waits on error, which would make jtreg time-out.
> 
> Although a time out is a bit of a confusing failure mode for the test, I think it would be better than no test at all, right?

Right. I added a test-case with a short timeout. It fails without the change, and passes with it.

**Review by xmas92 — APPROVED** [review]
lgtm.

**Review by shipilev — APPROVED** [review]

**Comment by TobiHartmann** [comment]
Looks good but I think it's safer to use the default timeout because otherwise we risk a false-positive timeout on slow machines when running with additional flags like -XX:+DeoptimizeALot.

**Pull request closed without merging**
