### PR TITLE
8253372: [TESTBUG] update tests which require jvmti - hotspot

### PR DESCRIPTION
**Pull request by alexmenkov**
This is subtask which covers test in hotspot/jtreg except test/hotspot/jtreg/vmTestbase/nsk/jvmti (there is a separate issue for it: JDK-8253371)

In most tests just "@requires vm.jvmti" is added,
in several test '@requires vm.flavor != "minimal"' is removed (when this requirement is only to ensure test VM has JVMTI included)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253372](https://bugs.openjdk.java.net/browse/JDK-8253372): [TESTBUG] update tests which require jvmti - hotspot

### Reviewers
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/314/head:pull/314`
`$ git checkout pull/314`

### CODE REVIEW

**Comment by plummercj** [comment]
How did you determine the list of tests that need jvmti?

**Review by sspitsyn — APPROVED** [review]
Alex, It looks good.
Did you test it in minimal config?

**Review by iklam — APPROVED** [review]
The CDS test changes look good to me. Thanks for doing this.

**Comment by alexmenkov** [comment]
> 
> 
> How did you determine the list of tests that need jvmti?

I tried to run all hotspot tests, but it failed due timeout. Main reason is absence of management (management module presents in minimal, but contains only stubs). There is a separate issue for management requirement: JDK-8252474
So I got the list by combining 2 ways:
- search for known functionalities which require jvmti (java.instrument, javaagent/agentlib)
- run subsets of the tests and looked at the failure reasons

So I can miss some tests which need to be updated, but it will be much simpler to identify them after JDK-8252474 is fixed

**Comment by alexmenkov** [comment]
> 
> Did you test it in minimal config?

Sure. The updated tests are skipped with minimal VM

**Pull request closed without merging**
