### PR TITLE
8322805: Eliminate -Wparentheses warnings in x86 code

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to eliminate some -Wparentheses warnings. This
involved simply adding a few parentheses to make some implicit operator
precedence explicit.

Testing: mach5 tier1

Also ran mach5 tier1 with these changes in conjunction enabling -Wparentheses
and other changes needed to make that work.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322805](https://bugs.openjdk.org/browse/JDK-8322805): Eliminate -Wparentheses warnings in x86 code (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17211/head:pull/17211` \
`$ git checkout pull/17211`

Update a local copy of the PR: \
`$ git checkout pull/17211` \
`$ git pull https://git.openjdk.org/jdk.git pull/17211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17211`

View PR using the GUI difftool: \
`$ git pr show -t 17211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17211.diff">https://git.openjdk.org/jdk/pull/17211.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17211#issuecomment-1873643444)

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good, and again trivial IMO.

Thanks

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by kimbarrett** [comment]
Thanks for reviews @dholmes-ora and @vnkozlov .

**Pull request closed without merging**
