### PR TITLE
8256325: Remove duplicate asserts in PhaseMacroExpand::expand_macro_nodes

### PR DESCRIPTION
**Pull request by TobiHartmann**
[JDK-8239072](https://bugs.openjdk.java.net/browse/JDK-8239072) added a default case to the switch statement in PhaseMacroExpand::expand_macro_nodes:
https://hg.openjdk.java.net/jdk/jdk/rev/cf319f17c647#l3.67

This allows to merge the "expansion must have deleted one node from macro list" asserts and remove the duplicate asserts.

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8256325](https://bugs.openjdk.java.net/browse/JDK-8256325): Remove duplicate asserts in PhaseMacroExpand::expand_macro_nodes

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to c3dde8c5fb4a8d31672e81dcc8244b49a2d2621e
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - **Reviewer**) ⚠️ Review applies to c3dde8c5fb4a8d31672e81dcc8244b49a2d2621e

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1200/head:pull/1200`
`$ git checkout pull/1200`

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks pretty simple and good. 

While you are here, you could also capitalize the macro and drop redundant semicolon:
```
    debug_only(int old_macro_count = C->macro_count(););
```
to:
```
    DEBUG_ONLY(int old_macro_count = C->macro_count();)
```

**Review by cl4es — APPROVED** [review]
Looks good and trivial.

**Comment by TobiHartmann** [comment]
@shipilev, @cl4es thanks for the reviews. I've updated `debug_only` to `DEBUG_ONLY`.

**Pull request closed without merging**
