### PR TITLE
8300863: Remove C-style array declarations in java.io

### PR DESCRIPTION
**Pull request by minborg**
Some variables are declared using old-style declarations. These should be modified to conform to modern style. 

This is a task derived from https://github.com/openjdk/jdk/pull/11848

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300863](https://bugs.openjdk.org/browse/JDK-8300863): Remove C-style array declarations in java.io

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12139/head:pull/12139` \
`$ git checkout pull/12139`

Update a local copy of the PR: \
`$ git checkout pull/12139` \
`$ git pull https://git.openjdk.org/jdk pull/12139/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12139`

View PR using the GUI difftool: \
`$ git pr show -t 12139`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12139.diff">https://git.openjdk.org/jdk/pull/12139.diff</a>

</details>

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]

**Review by RogerRiggs — APPROVED** [review]

**Review by jddarcy — APPROVED** [review]
Nice cleanup.

**Review by irisclark — APPROVED** [review]

**Comment by erikj79** [comment]
Something is causing high contention in the bot, it's under investigation. In the meantime, all you can do is retry this /integrate command until it goes through.

**Pull request closed without merging**
