### PR TITLE
8263134: HotSpot Style Guide should disallow inheriting constructors

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to explicitly disallow the use of inheriting
constructors:
(http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2540.htm).

The C++11/14 specification has a lot of problems. These were addressed in
C++17 (and as a DR that affects C++11/14):
(http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0136r1.html).

Use of inheriting constructors now runs the risk of encountering those bugs,
inconsistent behavior between different compilers or compiler versions, and
behavior changes for future support of C++17.

This is a modification of the Style Guide, so rough consensus among the
HotSpot Group members is required to make this change. Only Group members
should vote for approval (via the github PR), though reasoned objections or
comments from anyone will be considered. A decision on this proposal will not
be made before Friday 18-Mar-2022 at 12h00 UTC.

Since we're piggybacking on github PRs here, please use the PR review process
to approve (click on Review Changes > Approve), rather than sending a "vote:
yes" email reply that would be normal for a CFV.

/label hotspot

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263134](https://bugs.openjdk.java.net/browse/JDK-8263134): HotSpot Style Guide should disallow inheriting constructors

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 3e2be799d9a567330486f091a339b77ccbacb8b9
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 3e2be799d9a567330486f091a339b77ccbacb8b9
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 3e2be799d9a567330486f091a339b77ccbacb8b9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7698/head:pull/7698` \
`$ git checkout pull/7698`

Update a local copy of the PR: \
`$ git checkout pull/7698` \
`$ git pull https://git.openjdk.java.net/jdk pull/7698/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7698`

View PR using the GUI difftool: \
`$ git pr show -t 7698`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7698.diff">https://git.openjdk.java.net/jdk/pull/7698.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
This seems reasonable as it is no real hardship to explicitly declare all constructors. Personally I think it is clearer as well otherwise you have to go and lookup the base class to see what the constructor semantics are.

Thanks.

**Review by vnkozlov — APPROVED** [review]
Approved.

**Comment by kimbarrett** [comment]
Thanks @vnkozlov , @dholmes-ora , and @dcubed-ojdk for reviews.

**Pull request closed without merging**
