### PR TITLE
8341482: Attach API access to /proc filesystem should use doPrivileged

### PR DESCRIPTION
**Pull request by larry-cable**
this is a fix to: https://bugs.openjdk.org/browse/JDK-8327114 

to resolve an issue detected in: 

https://bugs.openjdk.org/browse/JDK-8341246

/proc/**/* file accesses should be performed as "privileged" actions to avoid security mgr exceptions.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341482](https://bugs.openjdk.org/browse/JDK-8341482): Attach API access to /proc filesystem should use doPrivileged (**Bug** - P4)

### Reviewers
 * @slovdahl (no known openjdk.org user name / role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21312/head:pull/21312` \
`$ git checkout pull/21312`

Update a local copy of the PR: \
`$ git checkout pull/21312` \
`$ git pull https://git.openjdk.org/jdk.git pull/21312/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21312`

View PR using the GUI difftool: \
`$ git pr show -t 21312`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21312.diff">https://git.openjdk.org/jdk/pull/21312.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21312#issuecomment-2389573892)

### CODE REVIEW

**Comment by larry-cable** [comment]
@kevinjwalls @slovdahl @jerboaa @sendaoYan @dcubed-ojdk

**Comment by jerboaa** [comment]
@larry-cable [JDK-8327114](https://bugs.openjdk.org/browse/JDK-8327114) is fixed. This PR should get integrated with a new bug. It cannot use the same bug unless it's a backport, which this clearly isn't. Also the permission issue is fixed with https://github.com/openjdk/jdk/pull/21269 (integrated).

**Comment by kevinjwalls** [comment]
I tested and saw the permission problem in the test was fixed by the policy update.  But it's correct that it should really have a doPrivileged call, in case this happens with a Security Manager, and there's untrusted code which then calls into attach (with whatever policy permits that to happen...).

While SM is planned for removal very soon, it would be good have the doPrivileged in the implementation so any backports can benefit.

**Comment by jerboaa** [comment]
Yes, agreed. But we need a new bug for this.

**Comment by larry-cable** [comment]
done

**Comment by larry-cable** [comment]
wondering if the other filesystem operations in VirtualMachineImpl also need to be wrapped in doPrivileged blocks - since I'm not aware of any issues I'll assume not and patiently wait for the SecurityManager to be consigned to history.

**Review by slovdahl — APPROVED** [review]
Thanks @larry-cable for looking into this!

The following test passes on my Ubuntu 24.04 with this PR at least.

`TestJcmdWithSideCar` with Docker:
```
make test TEST="jtreg:test/hotspot/jtreg/containers/docker/TestJcmdWithSideCar.java" JTREG="JAVA_OPTIONS=-Djdk.test.container.command=docker"
```

`TestJcmdWithSideCar` with Podman:
```
make test TEST="jtreg:test/hotspot/jtreg/containers/docker/TestJcmdWithSideCar.java" JTREG="JAVA_OPTIONS=-Djdk.test.container.command=podman"
```

```
make test TEST="jtreg:test/hotspot/jtreg/containers"
make test TEST="jtreg:test/hotspot/jtreg/serviceability"
```

FWIW, the `SecurityManager` PR (#21498) has been opened now. Ideally we would get this one in before it's merged.

**Comment by larry-cable** [comment]
closed superceded by 8342449

**Pull request closed without merging**
