### PR TITLE
8330163: C2: improve CMoveNode::Value() when condition is always true or false

### PR DESCRIPTION
**Pull request by rwestrel**
This is another small change from something I ran into while working
on 8275202. `CMoveNode::Value` can be improved when the condition is
known to be always true or false. That doesn't affect IGVN (as the
`CMove` is removed in that case) but it can be useful for passes that
propagates types such as CCP. In the IR tests, the backbranch of the
loop is never taken when the root of the compilation is `test1`. With
the change, CCP can eliminate it. Without, it can't.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8330163](https://bugs.openjdk.org/browse/JDK-8330163): C2: improve CMoveNode::Value() when condition is always true or false (**Enhancement** - P4)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18757/head:pull/18757` \
`$ git checkout pull/18757`

Update a local copy of the PR: \
`$ git checkout pull/18757` \
`$ git pull https://git.openjdk.org/jdk.git pull/18757/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18757`

View PR using the GUI difftool: \
`$ git pr show -t 18757`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18757.diff">https://git.openjdk.org/jdk/pull/18757.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18757#issuecomment-2051609350)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Nice.

**Comment by merykitty** [comment]
Can we check `Identity` during `PhaseCCP` instead? I see other inferences such as `AndINode` that may benefit from it.

Thanks.

**Comment by rwestrel** [comment]
> Can we check `Identity` during `PhaseCCP` instead? I see other inferences such as `AndINode` that may benefit from it.

Can you give more details on the cases that are not covered by CCP currently? Can `Value` be extended instead of changing CCP?

In any case, that would be out of the scope of this change, right?

**Comment by merykitty** [comment]
@rwestrel

> Can you give more details on the cases that are not covered by CCP currently?

For example, given `a & b`, during CCP, if the current value of `a` is `-1`, then `AndINode::Value` would yield `TypeInt::INT` while we can return a more rigorous value of `b`.

> Can Value be extended instead of changing CCP? In any case, that would be out of the scope of this change, right?

I think that if the issue is simply improving `CMoveNode::Value` then you are right, it would be out of the scope. However, given the reasoning for the issue being that it can improve CCP, I think it would be more generalised if we can consult `Identity` during CCP instead, maybe simply changing: `const Type* new_type = n->Value(this);` into `const Type* new_type = n->Identity(this)->Value(this);` would be adequate.

https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/phaseX.cpp#L1810

Or even better, if we can incorporate `Identity` into `Value` of all nodes then it may have a positive impact on all use sites of `Value`, too.

Cheers,
Quan Anh

**Comment by rwestrel** [comment]
> For example, given `a & b`, during CCP, if the current value of `a` is `-1`, then `AndINode::Value` would yield `TypeInt::INT` while we can return a more rigorous value of `b`.

Ok. But in that case `AndINode::Value` could be improved, right? Are there cases you can think of where calling `Identity` would result in a type that's narrower than what `Value` could compute.

> I think that if the issue is simply improving `CMoveNode::Value` then you are right, it would be out of the scope. However, given the reasoning for the issue being that it can improve CCP, I think it would be more generalised if we can consult `Identity` during CCP instead, maybe simply changing: `const Type* new_type = n->Value(this);` into `const Type* new_type = n->Identity(this)->Value(this);` would be adequate.

I think it's debatable whether it's the right thing to do and, in any case, it would be quite a bit of extra work. So I intend to go with the small improvement to `CMoveNode::Value`.

**Comment by merykitty** [comment]
I see, please go ahead, thanks a lot for your response.

**Comment by rwestrel** [comment]
@chhagedorn @vnkozlov thanks for the reviews

**Pull request closed without merging**
