### PR TITLE
8307378: Allow collectors to provide specific values for GC notifications' actions

### PR DESCRIPTION
**Pull request by earthling-amzn**
At the end of a GC pause, a `GarbageCollectionNotificationInfo` may be emitted. The notification has a `gcAction` field which presently originates from the field `_gc_end_message` in `GCMemoryManager`. Concurrent collectors such as Shenandoah, ZGC and G1 may have more (brief) pauses in their cycle than they have memory managers. This makes it difficult for gc notification listeners to determine the phase of the cycle that emitted the notification. We are proposing a change to allow collectors to define specific values for the `gcAction` to make it easier for notification listeners to classify the gc phase responsible for the notification.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307378](https://bugs.openjdk.org/browse/JDK-8307378): Allow collectors to provide specific values for GC notifications' actions

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - no project role) ⚠️ Review applies to [d1792bb6](https://git.openjdk.org/jdk/pull/13785/files/d1792bb67c5b46f7e1aaa8ce32fb536840d8882e)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13785/head:pull/13785` \
`$ git checkout pull/13785`

Update a local copy of the PR: \
`$ git checkout pull/13785` \
`$ git pull https://git.openjdk.org/jdk.git pull/13785/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13785`

View PR using the GUI difftool: \
`$ git pr show -t 13785`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13785.diff">https://git.openjdk.org/jdk/pull/13785.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13785#issuecomment-1533509390)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]

**Comment by stefank** [comment]
The proposed patch introduces two ways to inject these messages, which makes the code slightly harder to follow. I wonder if it wouldn't be easier if we just had one, a bit more flexible, way to provide the message. What do you think about something like this:
https://github.com/stefank/jdk/commit/52e9fe84c2bc14b21824068d71419d0e1f0796c1

**Comment by earthling-amzn** [comment]
@stefank - Unifying the code path looks great to me. I was just trying to minimize the changes. Should I cherry pick your commit into the branch for the PR?

**Comment by stefank** [comment]
I see that I dropped the ZGC changes when I rebased my proposed patch. Thanks for fixing that.

**Review by stefank — APPROVED** [review]

**Pull request closed without merging**
