### PR TITLE
8263992: Remove dead code NativeLookup::base_library_lookup

### PR DESCRIPTION
**Pull request by iklam**
Please review this removal of dead code, and unused parameter of `in_base_library` for the functions that remain. The word `base_library_lookup` does not exist in any C source code in the entire JDK.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263992](https://bugs.openjdk.java.net/browse/JDK-8263992): Remove dead code NativeLookup::base_library_lookup

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 039ca6866e1ccc53c8458ad0202e9266cb80aae6
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3139/head:pull/3139`
`$ git checkout pull/3139`

To update a local copy of the PR:
`$ git checkout pull/3139`
`$ git pull https://git.openjdk.java.net/jdk pull/3139/head`

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Good going - you got rid of some CATCHes + trivial.

**Review by dholmes-ora — COMMENTED** [review]
Hi Ioi,

Looks good but  do we have a problem with the notion of "in base library" ??? Should we perhaps have been using this method elsewhere?

Thanks,
David

**Comment by iklam** [comment]
> Hi Ioi,
> 
> Looks good but do we have a problem with the notion of "in base library" ??? Should we perhaps have been using this method elsewhere?
> 
> Thanks,
> David

This function was last used here in 2014. (JDK-8031819: Remove legacy jdk checks and code)

So one has found any use of it for the past 6+ years. I think it's pretty dead.

http://hg.openjdk.java.net/jdk9/jdk9/hotspot/diff/afe58d604f28/src/share/vm/prims/jvm.cpp

**Comment by iklam** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-dev](mailto:hotspot-dev@openjdk.java.net):_
> 
> On 23/03/2021 2:12 pm, Ioi Lam wrote:
> 
> > On Tue, 23 Mar 2021 03:21:52 GMT, David Holmes <dholmes at openjdk.org> wrote:
> > > Hi Ioi,
> > > Looks good but do we have a problem with the notion of "in base library" ??? Should we perhaps have been using this method elsewhere?
> > > Thanks,
> > > David
> > 
> > 
> > This function was last used here in 2014. (JDK-8031819: Remove legacy jdk checks and code)
> > So one has found any use of it for the past 6+ years. I think it's pretty dead.
> > http://hg.openjdk.java.net/jdk9/jdk9/hotspot/diff/afe58d604f28/src/share/vm/prims/jvm.cpp
> 
> Yes it looks like this should have been removed as part of 8031819.
> 
> But I remain a little confused as to what "in base library" means in the
> rest of the code.
> 
> Cheers,
> David

I removed the `int& in_base_library` parameter. There were only 2 callers that passed this parameter, but they don't use the returned value.

I also removed unnecessary inclusion of nativeLookup.hpp.

**Review by dholmes-ora — APPROVED** [review]
Looks even better! Thanks.

Of course now I'm going to have to go and find out why in_base_library was introduced :)

Cheers,
David

**Comment by iklam** [comment]
Thanks David for the review. Builds from tiers 1-5 passed.
/integrate

**Pull request closed without merging**
