### PR TITLE
8288428: javax/swing/JInternalFrame/Test6505027.java fails frequently in MacOS 12 machines

### PR DESCRIPTION
**Pull request by manukumarvs**
javax/swing/JInternalFrame/Test6505027.java seems to be unstable in MacOS machines, especially in MacOSX 12 machines and it fails intermittently in CI causing some noise.
It seems to be a testbug as adding some stability improvements fix the issue.

Fix:
Some stability improvements have been done and the test has been run 10 times per platform in mach5 and got full PASS.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288428](https://bugs.openjdk.org/browse/JDK-8288428): javax/swing/JInternalFrame/Test6505027.java fails frequently in MacOS 12 machines

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9202/head:pull/9202` \
`$ git checkout pull/9202`

Update a local copy of the PR: \
`$ git checkout pull/9202` \
`$ git pull https://git.openjdk.org/jdk pull/9202/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9202`

View PR using the GUI difftool: \
`$ git pr show -t 9202`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9202.diff">https://git.openjdk.org/jdk/pull/9202.diff</a>

</details>

### CODE REVIEW

**Comment by manukumarvs** [comment]
Any volunteers?

**Comment by manukumarvs** [comment]
Any volunteers please?

**Comment by prsadhuk** [comment]
I dont see this test failing in our CI systems "frequently"...last time it failed is June8 on a CI system which had some history of config issue, and that too on jdk17 binary and not on mainline..before that it fails on June1 due to some infra issue on mainline..and before that on June19 2021 on jdk11 binary again due to infra issue..so I dont think it's worth tinkering as of now..

also, the test has some quirks as I see. press() method is never called...it uses internal SwingTest class to start the test which I am not sure is needed

**Comment by manukumarvs** [comment]
> I don't see this test failing in our CI systems "frequently"...last time it failed is June8 on a CI system which had some history of config issue, and that too on jdk17 binary and not on mainline..before that it fails on June1 due to some infra issue on mainline..and before that on June19 2021 on jdk11 binary again due to infra issue..so I dont think it's worth tinkering as of now..
> 
> also, the test has some quirks as I see. press() method is never called...it uses internal SwingTest class to start the test which I am not sure is needed

I have seen it failing around 35 times last month alone and not all failures were system issues(failures link attached as a confidential comment in bug), but yes, this was mostly failing on JDK18, JDK17 or JDK11 and I think this fails only for MacOS 12 machines. But anyway I felt it better to fix the test if some instability is there.

**Comment by manukumarvs** [comment]
Any volunteers?

**Comment by manukumarvs** [comment]
Any volunteers?

**Comment by prrace** [comment]
How do the changes made here improve stability ? What I see is just that you are adding a new condition under which it will fail.

**Review by prrace — COMMENTED** [review]
Like several other tests fixes I don't understand how this improves stability

**Review by honkar-jdk — COMMENTED** [review]
Copyright year needs to be changed https://github.com/openjdk/jdk/blob/7995b9b9c63bbb76e44d0dbf7f180294afd87453/test/jdk/javax/swing/JInternalFrame/Test6505027.java#L2

Author tag in jtreg header is no longer used. It can be removed.

**Pull request closed without merging**
