### PR TITLE
8311532: Option to disable Krb5LoginModule::login method

### PR DESCRIPTION
**Pull request by alexeybakhtin**
JGSS is implemented in the JVM in 2 levels: the standard Java security provider for Kerberos in sun.security.jgss.krb5.Krb5MechFactory and the JAAS login module for Kerberos in com.sun.security.auth.module.Krb5LoginModule. The problem is that in this hierarchy, the login module doesn't go through the provider, but tries to read the credential cache (which is blocked by the credential guard in Win platform). This is not an issue if Kerberos is used via the JGSS API because it automatically does the JAAS login as needed, and won't do it at all if a native implementation is used. However many libraries (even some built-in ones in the JVM) still needlessly call login() before using JGSS.

This patch represents the configuration option ( `“doNotLogin”` ) to allow skipping the login, with a system property (`“sun.security.auth.skipLogin”`) to set the default value if this option is not provided. This way it would not break the regular Java Kerberos provider and allow users to both individually (via JAAS configs) and globally (via the property) set the expected behavior

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 22 to be approved (needs to be created)

### Issue
 * [JDK-8311532](https://bugs.openjdk.org/browse/JDK-8311532): Option to disable Krb5LoginModule::login method (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15254/head:pull/15254` \
`$ git checkout pull/15254`

Update a local copy of the PR: \
`$ git checkout pull/15254` \
`$ git pull https://git.openjdk.org/jdk.git pull/15254/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15254`

View PR using the GUI difftool: \
`$ git pr show -t 15254`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15254.diff">https://git.openjdk.org/jdk/pull/15254.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15254#issuecomment-1675523642)

### CODE REVIEW

**Comment by eirbjo** [comment]
Any particular reason why the configuration option is not called `skipLogin`? Seems to me that setting "doNot" to `true` requires a bit of unnecessary metal boolean algebra and is easier to get wrong. Or is this for consistency with `doNotPrompt`?

My general preference is to avoid using "negative" options such that when something is disabled or skipped, the value can be set to `false` instead of `true`. So I would prefer `doLogin=false` over `skipLogin=true`. But I guess this is a matter of preference and consistency is also important..

**Comment by alexeybakhtin** [comment]
Hello @eirbjo 

Thank you for the review!
Naming, of course, can be discussed and changed. I am mostly concerned about the general idea of disabling the login method.
I've tried to make different naming for the System property and configuration option, so they are not messed up.
I propose `doNotLogin` option name for consistency with `doNotPrompt` and compatibility with current behavior. You just need to add `doNotLogin=true` to change the behavior. The default value, if neither is set, is the old behavior.
Using system and configuration options would definitely not break the regular Java Kerberos provider and allow users to both individually (via JAAS configs) and globally (via the property) set the behavior as they need it – i.e. they could set the option in JAAS to not skip the login if they need the private keys to be added to the Subject, and leave it to the system property if they only care for JGSS to work.

**Comment by eirbjo** [comment]
> Naming, of course, can be discussed and changed.

Yes, naming is hard :-)

> I've tried to make different naming for the System property and configuration option, so they are not messed up.

I would think having two different names for essentially the same think (just different scopes) would make it easier to mess things up?

If consistency with `doNotPrompt` is important, would it not be better to have:

`doNotLogin` for the configuration option and

`sun.security.auth.doNotLogin` for the system property?

I'm not sure using different names here would reduce the risk of mistakes. But my guess is as good as yours. Is there precedence for doing it this way?

One could claim that this is non-important details, but I think getting it right here can help prevent misconfigurations.

My opinions here are weakly held. Perhaps some other reviewers could chime in?

**Comment by alexeybakhtin** [comment]
OK. You convinced me. I will rename the system property to `sun.security.auth.doNotLogin` if no other suggestions.

**Comment by eirbjo** [comment]
`sun.security.auth.doNotLogin` does not indicate at all that this property  is related to Kerberos .

Would it be worth adding `krb5` somewhere in the name, something like:

`sun.security.auth.krb5.doNotLogin` ?

**Comment by seanjmullan** [comment]
You will need to also file a CSR as you are adding a new system property and configuration option. I would also like to review this but may need a few days.

**Comment by alexeybakhtin** [comment]
CSR is submitted: https://bugs.openjdk.org/browse/JDK-8315562

**Pull request closed without merging**
