### PR TITLE
8321703: jdeps generates illegal dot file containing nodesep=0,500000

### PR DESCRIPTION
**Pull request by mlchung**
Trivial fix.  Call `PrintWriter::format` with null `Locale` to format with no localization.
 
This PR also fixes JDK-8325262 to print `FindException` message without the stack trace to indicate clearer that the given module path is incorrect.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8321703](https://bugs.openjdk.org/browse/JDK-8321703): jdeps generates illegal dot file containing nodesep=0,500000 (**Bug** - P4)
 * [JDK-8325262](https://bugs.openjdk.org/browse/JDK-8325262): jdeps can drop printing stack trace when FindException is thrown due to modules not found (**Enhancement** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17713/head:pull/17713` \
`$ git checkout pull/17713`

Update a local copy of the PR: \
`$ git checkout pull/17713` \
`$ git pull https://git.openjdk.org/jdk.git pull/17713/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17713`

View PR using the GUI difftool: \
`$ git pr show -t 17713`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17713.diff">https://git.openjdk.org/jdk/pull/17713.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17713#issuecomment-1928522513)

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Mandy, the changes look OK to me.

**Review by AlanBateman — APPROVED** [review]
Looks okay. (JDK-8325262 should probably be changed to be Bug rather than Enhancement)

**Comment by mlchung** [comment]
Thanks for the review.

**Pull request closed without merging**
