### PR TITLE
8263097: Update JMH devkit to 1.28

### PR DESCRIPTION
**Pull request by cl4es**
Currently at 1.26, so there are a few good improvements and a few bug fixes - notably resolving a build reproducibility issue.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263097](https://bugs.openjdk.java.net/browse/JDK-8263097): Update JMH devkit to 1.28

### Reviewers
 * [Eric Caspole](https://openjdk.java.net/census#ecaspole) (@ericcaspole - Committer) ⚠️ Review applies to bd98cf7f03c629a31f6d8bddfd16990712000653
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2848/head:pull/2848`
`$ git checkout pull/2848`

### CODE REVIEW

**Review by ericcaspole — APPROVED** [review]
Good!
Eric

**Comment by erikj79** [comment]
Should also updated jib-profiles.js Oracle builds get the new version.

**Comment by cl4es** [comment]
Uploaded and verified jib picks up the new version.

**Review by erikj79 — APPROVED** [review]

**Comment by cl4es** [comment]
Thank you for reviewing, Eric and Erik!

/integrate

**Pull request closed without merging**
