### PR TITLE
8299847: RISC-V: Improve PrintOptoAssembly output of CMoveI/L nodes

### PR DESCRIPTION
**Pull request by RealFYang**
Witnessed some incorrect/strange branch condition code in PrintOptoAssembly output on RISC-V which is quite misleading. While this won't affect release build, we should fix this for debug build. This also fixes the pipeline for those nodes and bumps the BRANCH_COST a little bit as I think control transfer instructions should have higher cost than regular integer computational instructions.

With this fix, we have some new PrintOptoAssembly output like following snippet:
```
   460 202     B41: #  out( B42 ) <- in( B40 )  Freq: 55.6844
   461 202 +   li R7, #0       # int, #@loadConI
   462 204 +   addiw  R28, R9, #1      #@addI_reg_imm
   463 208 +   li R29, #0      # int, #@loadConI
   464 20a +   CMove R28, (R28 lt R29), R28, R7        #@cmovI_cmpI      <=============
```

Testing: Tier1 tested on HiFive Unmatched board.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299847](https://bugs.openjdk.org/browse/JDK-8299847): RISC-V: Improve PrintOptoAssembly output of CMoveI/L nodes

### Reviewers
 * [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - Author) ⚠️ Review applies to [f28dbcbd](https://git.openjdk.org/jdk/pull/11919/files/f28dbcbd4e7d16ba3d90d9776fa167e6373a4015)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11919/head:pull/11919` \
`$ git checkout pull/11919`

Update a local copy of the PR: \
`$ git checkout pull/11919` \
`$ git pull https://git.openjdk.org/jdk pull/11919/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11919`

View PR using the GUI difftool: \
`$ git pr show -t 11919`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11919.diff">https://git.openjdk.org/jdk/pull/11919.diff</a>

</details>

### CODE REVIEW

**Review by feilongjiang — APPROVED** [review]
LGMT, thanks.

**Review by shipilev — APPROVED** [review]
Looks okay, but shouldn't CMove instructions be `pipe_class_compare`?

**Review by shipilev — APPROVED** [review]
Still good.

**Comment by RealFYang** [comment]
Thanks all for the review.
/integrate

**Pull request closed without merging**
