### PR TITLE
8241192: [macosx] Wrong letter typed after ´ symbol when using Finnish layout

### PR DESCRIPTION
**Pull request by prsadhuk**
If we press " ´ " (on U.S. keyboard layout it is the [+] button just before the [delete] button), and then press "s" , 2 "´" characters are entered in a text field instead of "´s" with "Finish" keyboard layout.
This is because, although " ´ " is construed as "complex" char and inserted properly the next "s" character is treated as non-complex character as it's utf8Length is 1 and utf16Length is 2, so we need to explicitly make it a "complex" char sequence if the code point is 0x73 ie "s" in Finnish layout for it to be inserted properly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8241192](https://bugs.openjdk.java.net/browse/JDK-8241192): [macosx] Wrong letter typed after ´ symbol when using Finnish layout

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7262/head:pull/7262` \
`$ git checkout pull/7262`

Update a local copy of the PR: \
`$ git checkout pull/7262` \
`$ git pull https://git.openjdk.java.net/jdk pull/7262/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7262`

View PR using the GUI difftool: \
`$ git pr show -t 7262`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7262.diff">https://git.openjdk.java.net/jdk/pull/7262.diff</a>

</details>

### CODE REVIEW

**Comment by prrace** [comment]
"This is because, although " ´ " is construed as "complex" char and inserted properly the next "s" character is treated as non-complex character as it's utf8Length is 1 and utf16Length is 2, so we need to explicitly make it a "complex" char sequence if the code point is 0x73 ie "s" in Finnish layout for it to be inserted properly."

I know nothing about this area, so some questions.
" although " ´ " is construed as "complex" char and inserted properly "

Since we had no special treatment of this char, what was treating it as complex  and why ?

Why do we need to make s be a complex char (whatever that actually means here ??) in order to display as s ??
Sounds backwards.

Really I just can't make sense of the explanation. Can you point me to docs as well as re-explaining it ?

**Comment by prsadhuk** [comment]
Actually, this method "insertText" gets called when the user commits text generated from an input method, which in this case, is from Finnish keyboard layout [https://github.com/openjdk/jdk/blame/master/src/java.desktop/macosx/native/libawt_lwawt/awt/AWTView.m#L946]
I don't think there is any docs for it and most of it came along with the macos port. The "complex" char is basically the "aStringIsComplex" condition I am talking about.

As per the conditions written in this method [https://github.com/openjdk/jdk/blame/master/src/java.desktop/macosx/native/libawt_lwawt/awt/AWTView.m#L975-L991] the Input method event is generated or CInputMethod#insertText for that **particular language** is called only when these conditions are satisfied. If these conditions are not met, then keyevent gets handled by CPlatformResponder#handleKeyEvent without taking "current "language " into account

"s" is therefore routed through CInputMethod#insertText by satisfying the condition so that it gets inserted as per Finnish "language" selected.

**Comment by prrace** [comment]
Doesn't it seem odd to you that we need to enumerate some of these cases ?
I had to look up what Kotoeri is .. and I suspect it is actually obsolete and we can get rid of it ?
But why do one or two cases need special treatment and hundreds of others not ?
@naotoj - Naoto do you understand any of this ?

**Comment by naotoj** [comment]
> @naotoj - Naoto do you understand any of this ?

No. But the fix seems somewhat ad-hoc to me.

**Comment by prrace** [comment]
> > @naotoj - Naoto do you understand any of this ?
> 
> No. But the fix seems somewhat ad-hoc to me.

Exactly.

**Comment by prsadhuk** [comment]
It might seem ad-hoc but the InputMethod event design in mac is such that (which has been there from beginning of macport days) that we need to fix in this way as far I can tell (it has been fixed like this earlier also without any regression).
 The https://github.com/openjdk/jdk/blame/master/src/java.desktop/macosx/native/libawt_lwawt/awt/AWTView.m#L946 statement seems to suggest that as well, in my opinion, to send Input method event if we get such insertText "out of the blue!"

**Comment by prsadhuk** [comment]
@dmarkov20 @alitvinv Since you have touched this file and fixed similar issue earlier, can you please review?

**Comment by NikitkoCent** [comment]
Hey, folks! With my environment the patch fixes only the `´` + `s` combination, but does nothing with all other broken keys, i.e. all except `e`, `u`, `i`, `o`, `a`.

Can you please verify you are reproducing this behavior too?

My environment:
* macOS 11.6.1;
* Xcode 13.2.1;
* Boot JDK 17.0.1 (for building);
* Finnish layout for testing.

Repro:
```java
package com.company;

import javax.swing.*;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.AttributedCharacterIterator;

public class KeyboardWindow {
    final JFrame frame;
    final JTextArea textArea;

    KeyboardWindow() {
        frame = new JFrame();
        frame.setSize(300, 200);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setTitle("Keyboard Window");

        textArea = new JTextArea();

        textArea.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                //System.out.println("keyTyped 0x" + Integer.toHexString(e.getKeyChar()) + ": " + e + "\n");
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //System.out.println("keyPressed: " + e + "\n");
            }

            @Override
            public void keyReleased(KeyEvent e) {
                //System.out.println("keyReleased: " + e + "\n");
            }
        });

        textArea.addInputMethodListener(new InputMethodListener() {
            @Override
            public void inputMethodTextChanged(InputMethodEvent event) {
                //System.out.println("inputMethodTextChanged: " + event + "\n");
            }

            @Override
            public void caretPositionChanged(InputMethodEvent event) {
                //System.out.println("caretPositionChanged: " + event + "\n");
            }
        });

        frame.add(textArea);

        frame.pack();
        frame.setSize(300, 300);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(KeyboardWindow::new);
    }
}
```

**Comment by dmarkov20** [comment]
It seems we fail to detect accented symbols at least for “Finish” keyboard layout (other layouts might be affected too). 
I would expect that the function `keyDown()` will set `fProcessingKeystroke` flag to `NO` and then `insertText()` will do the rest but it does not work and requires investigation.

**Comment by NikitkoCent** [comment]
As far as I understand the bug affects all of keyboard layouts have [combining characters](https://en.wikipedia.org/wiki/Combining_character) except the `U.S. International PC` layout because it's handled explicitly at [CPlatformResponder.java:189-191](https://github.com/openjdk/jdk/blob/51f4420711b8cace5733180b3291779f11291895/src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformResponder.java#L189).

**Comment by prrace** [comment]
Please withdraw this until we are more sure about the right fix.

**Pull request closed without merging**
