### PR TITLE
8255675: Typo in java.net.HttpURLConnection

### PR DESCRIPTION
**Pull request by anupamdev20**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8255675](https://bugs.openjdk.java.net/browse/JDK-8255675): Typo in java.net.HttpURLConnection

### Reviewers
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1250/head:pull/1250`
`$ git checkout pull/1250`

### CODE REVIEW

**Comment by anupamdev20** [comment]
Hello All,

Could you please review this fix?

Bug: https://bugs.openjdk.java.net/browse/JDK-8255675

Problem description: In the getResponseCode method, the following comment was unclear:
"If we can't a status-line then re-throw any exception"

Fix: Comment is changed to 
"If we can't find a status-line then re-throw any exception"

Apart from that there was another small typo which I fixed:
"We're got the response code already" is changed to
"We've got the response code already"

**Review by ChrisHegarty — APPROVED** [review]

**Comment by Michael-Mc-Mahon** [comment]
What is the effect if this change is integrated as is (from the master branch)? The normal procedure is to merge from a separate branch.

**Comment by FrauBoes** [comment]
> What is the effect if this change is integrated as is (from the master branch)? The normal procedure is to merge from a separate branch.

@anupamdev20 note the bot comment above, pushing from your master branch will diverge it. You can get around this with the steps described.

> ⚠️ @anupamdev20 a branch with the same name as the source branch for this pull request (`master`) is present in the [target repository](https://github.com/openjdk/jdk). If you eventually integrate this pull request then the branch `master` in your [personal fork](https://github.com/anupamdev20/jdk) will diverge once you sync your personal fork with the upstream repository.
> 
> To avoid this situation, create a new branch for your changes and reset the `master` branch. You can do this by running the following commands in a local repository for your personal fork. _Note_: you do _not_ have to name the new branch `NEW-BRANCH-NAME`.
> 
> ```
> $ git checkout -b NEW-BRANCH-NAME
> $ git branch -f master 537b40e0137614999d07d9678632a24f98057634
> $ git push -f origin master
> ```
> 
> Then proceed to create a new pull request with `NEW-BRANCH-NAME` as the source branch and close this one.

**Pull request closed without merging**
