### PR TITLE
8228748: Remove GCLocker::_doing_gc

### PR DESCRIPTION
**Pull request by albertnetymk**
Some refactoring in `GCLocker` and more comments in `jni_lock` on how the synchronization works there.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8228748](https://bugs.openjdk.java.net/browse/JDK-8228748): Remove GCLocker::_doing_gc

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to 17ff21e705be0635d513cbbb0e91af551e6e79f7
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer)
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2602/head:pull/2602`
`$ git checkout pull/2602`

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.  Copyright for gcLocker.hpp needs to be updated.

**Review by walulyai — APPROVED** [review]
Lgtm!

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Review by pliden — APPROVED** [review]
Looks good.

**Review by tschatzl — APPROVED** [review]

**Pull request closed without merging**
