### PR TITLE
8255721: Remove no-op clean_weak_method_links methods

### PR DESCRIPTION
**Pull request by cl4es**
ProfileData:: and DataLayout::clean_weak_method_links are both virtual but empty methods with no overrides, so removing them and simplifying MethodData::clean_weak_method_links should be a minor clean-up and possibly speed-up redefinition a notch.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8255721](https://bugs.openjdk.java.net/browse/JDK-8255721): Remove no-op clean_weak_method_links methods

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 4d5c18f4ab2aa21522ec00cc73684a54e20ad889
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/990/head:pull/990`
`$ git checkout pull/990`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Review by TobiHartmann — APPROVED** [review]

**Comment by cl4es** [comment]
@vnkozlov @TobiHartmann - thank you for reviewing!

/integrate

**Pull request closed without merging**
