### PR TITLE
8262721: Add Tests to verify single iteration loops are properly optimized

### PR DESCRIPTION
**Pull request by rwestrel**
That came up in previous:

https://github.com/openjdk/jdk/pull/2529#discussion_r583054321

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262721](https://bugs.openjdk.java.net/browse/JDK-8262721): Add Tests to verify single iteration loops are properly optimized

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7368/head:pull/7368` \
`$ git checkout pull/7368`

Update a local copy of the PR: \
`$ git checkout pull/7368` \
`$ git pull https://git.openjdk.java.net/jdk pull/7368/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7368`

View PR using the GUI difftool: \
`$ git pr show -t 7368`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7368.diff">https://git.openjdk.java.net/jdk/pull/7368.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good! Approved.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by rwestrel** [comment]
@neliasso @chhagedorn thanks for the reviews.

**Comment by rwestrel** [comment]
@vnkozlov are the proposed tests what you had in mind?

**Review by vnkozlov — APPROVED** [review]
Yes, this is exactly what I wanted.

**Pull request closed without merging**
