### PR TITLE
8305904: java/lang/Character, java/lang/String and java/text/Normalizer tests read the unicode data files from src directories.

### PR DESCRIPTION
**Pull request by mahendrachhipa**
Following tests read the unicode data files (http://www.unicode.org/Public/UNIDATA/ ) from src directory. For tests, these files should be in test directories. No source code is using these files. Only tests are using these files. Tests are :
java/lang/Character/CharPropTest.java
java/lang/Character/CheckProp.java
java/lang/Character/CheckScript.java
java/lang/Character/CheckUnicode.java
java/lang/Character/UnicodeBlock/CheckBlocks.java
java/lang/Character/UnicodeCasingTest.java
java/lang/String/SpecialCasingTest.java
java/lang/String/UnicodeCasingTest.java
java/text/Normalizer/ConformanceTest.java

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305904](https://bugs.openjdk.org/browse/JDK-8305904): java/lang/Character, java/lang/String and java/text/Normalizer tests read the unicode data files from src directories.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13447/head:pull/13447` \
`$ git checkout pull/13447`

Update a local copy of the PR: \
`$ git checkout pull/13447` \
`$ git pull https://git.openjdk.org/jdk.git pull/13447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13447`

View PR using the GUI difftool: \
`$ git pr show -t 13447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13447.diff">https://git.openjdk.org/jdk/pull/13447.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13447#issuecomment-1505595266)

### CODE REVIEW

**Comment by naotoj** [comment]
Hi Mahendra,

What's the point of having the Unicode data files duplicate? That would cause a possible mismatch between the files between src and test.

**Comment by RogerRiggs** [comment]
Are you aware of the uses in the makefiles?  
```
make/modules/java.base/Gendata.gmk
make/modules/java.base/gendata/GendataBreakIterator.gmk
make/modules/java.base/gensrc/GensrcCharacterData.gmk
```

**Comment by naotoj** [comment]
Missed that the intended change is not duplicating but moving from src->test. No this is not correct.

**Comment by mahendrachhipa** [comment]
> 

Hi Roger,
 Sorry I was not aware of uses in makefiles. I will undo the changes.

**Comment by AlanBateman** [comment]
I assume this PR should be closed.

**Pull request closed without merging**
