### PR TITLE
8254125: Assertion in cppVtables.cpp during builds on 32bit Windows

### PR DESCRIPTION
**Pull request by iklam**
**Problem:** when iterating over the cloned vtables, the original code assumes that they are laid out consecutively in memory. However, since [JDK-8224509](https://bugs.openjdk.java.net/browse/JDK-8224509), the memory allocated for each of the the cloned vtables is now 8-byte aligned. This introduces gaps between the cloned vtables, and causes the assert to fail.

**Fix:** the fix is to no longer assume the consecutive memory layout. Instead, use the CppVtables::_index array to access each individual cloned vtable.

**Note:** I also cleaned up the code significantly. I feel the original code is pretty hard to understand, so if I just do the bare minimum to fix the bug, it will be pretty hard to review. 

I would suggest that the reviewers look at just the new version of the code and see if it's working as described (instead of looking at the diff to understand what the bug was and how it has been fixed).

This version still uses the x-macro CPP_VTABLE_TYPES_DO to enumerate over the classes whose vtables need to be cloned. I plan to change that into templates in a future RFE.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254125](https://bugs.openjdk.java.net/browse/JDK-8254125): Assertion in cppVtables.cpp during builds on 32bit Windows

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 5002b8206a9575d74c5f980c3847b8c3d22e7e58
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to 5002b8206a9575d74c5f980c3847b8c3d22e7e58

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/591/head:pull/591`
`$ git checkout pull/591`

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
This looks reasonable to me, but after testing it on x86_32, I wonder if https://bugs.openjdk.java.net/browse/JDK-8254606 is the problem with this patch, or a different issue.

**Comment by iklam** [comment]
> This looks reasonable to me, but after testing it on x86_32, I wonder if https://bugs.openjdk.java.net/browse/JDK-8254606 is the problem with this patch, or a different issue.

[JDK-8254606](https://bugs.openjdk.java.net/browse/JDK-8254606) is also caused by [JDK-8224509](https://bugs.openjdk.java.net/browse/JDK-8224509), which has missed some cases where `align_up(xxx, SharedSpaceObjectAlignment)` is necessary.

Since the cppVtables assertion fix cannot be easily validated by itself, I've decided to also include the `align_up` fixes in this PR.

I have tested the fix on linux-x86 (32-bit) but the latest repo seems a bit flaky. Even if I disable CDS, sometime I get failures in (non-CDS) test cases like `There cannot be a NullPointerException at bci 14 of method byte java.lang.String.coder()`.

I was able to run all 200+ CDS tests cases, and I would get about 5 failures due with the above error message. If I ran the failed tests again, they passed. So I **think** I have fixed the 32-bit issues with CDS, but there are probably other problems with the 32-bit build.

Note that Oracle no longer supports the 32-bit x86 VMs. So my fix is intended to ensure that the CDS code is using SharedSpaceObjectAlignment properly, and I can only test thoroughly on our supported platforms.

**Comment by shipilev** [comment]
> I have tested the fix on linux-x86 (32-bit) but the latest repo seems a bit flaky. Even if I disable CDS, sometime I get failures in (non-CDS) test cases like `There cannot be a NullPointerException at bci 14 of method byte java.lang.String.coder()`.

That's https://bugs.openjdk.java.net/browse/JDK-8254611 -- I integrated the fix, please merge from master. That said, there are a few failing tests in `tier1` anyway, you can ignore them:
 - gc/metaspace/TestCapacityUntilGCWrapAround.java
 - java/foreign/TestMismatch.java
 - java/util/stream/test/org/openjdk/tests/java/util/stream/SpliteratorTest.java
 - tools/javac/lambda/T8031967.java

**Comment by iklam** [comment]
> > I have tested the fix on linux-x86 (32-bit) but the latest repo seems a bit flaky. Even if I disable CDS, sometime I get failures in (non-CDS) test cases like `There cannot be a NullPointerException at bci 14 of method byte java.lang.String.coder()`.
> 
> That's https://bugs.openjdk.java.net/browse/JDK-8254611 -- I integrated the fix, please merge from master.

Thanks for the info. I merged and all CDS tests passed.

**Review by shipilev — APPROVED** [review]
I tested the new patch, and it passes `tier1` on `x86_32` (well, with some known failures).

**Review by calvinccheung — APPROVED** [review]

**Comment by iklam** [comment]
> In the function `ArchiveBuilder::gather_klass_and_symbol(MetaspaceClosure::Ref* ref, bool read_only)`
> Instead of `BytesPerWord`, is `BytesPerInt` more appropriate since the `ref->size()` returns an int?

Hi Calvin, thanks for the review.

For the line `int bytes = ref->size() * BytesPerWord;`,  `ref->size()` has the same API as all the `size()` methods of the `MetaspaceObj` classes. I.e., "the number of words needed to hold this object". That's why we need to multiple by `BytesPerWord` to calculate the number of bytes needed.

**Pull request closed without merging**
