### PR TITLE
8271225: Add floorDivExact() method to java.lang.[Strict]Math

### PR DESCRIPTION
**Pull request by bplb**
Add methods `floorDivExact(int,int)` and `floorDivExact(long,long)` to `java.lang.Math` and `java.lang.StrictMath`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271225](https://bugs.openjdk.java.net/browse/JDK-8271225): Add floorDivExact() method to java.lang.[Strict]Math

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4941/head:pull/4941` \
`$ git checkout pull/4941`

Update a local copy of the PR: \
`$ git checkout pull/4941` \
`$ git pull https://git.openjdk.java.net/jdk pull/4941/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4941`

View PR using the GUI difftool: \
`$ git pr show -t 4941`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4941.diff">https://git.openjdk.java.net/jdk/pull/4941.diff</a>

</details>

### CODE REVIEW

**Comment by bplb** [comment]
The `floorDivExact()` methods are identical to their `floorDiv()` counterparts aside from that they throw an `ArithmeticException` when the dividend is `MIN_VALUE` and the divisor is `-1`. These methods behave with respect to the methods `floorDiv()` as the methods `divideExact()` behave with respect to the division operator `/`.

**Comment by rgiulietti** [comment]
Hello @bplb,

the doc of floorDivExact() is not, well..., exact.

For example,
> The floor rounding mode gives different results from truncation
when the exact result is negative.

The truth is that the results are different when the exact quotient _is not an integer and is negative_.
The description following this sentence is imprecise as well.

The doc seems to have been copied and adapted from the doc of floorDiv(), which is imprecise in the first place.
You might want to take a look at [PR 4963](https://github.com/openjdk/jdk/pull/4963) which addresses this and wait until that one is thoroughly discussed for mathematical accuracy and correct wording.


Greetings
Raffaello

**Comment by bplb** [comment]
@rgiulietti Yes, that doc was copied. I tend to agree that it would be better to get 4963 right and hold off on this PR until then.

**Comment by bplb** [comment]
CSR updated to match this PR.

**Comment by bplb** [comment]
The CSR for this PR has been approved.

**Review by jddarcy — APPROVED** [review]

**Pull request closed without merging**
