### PR TITLE
8264397: Use the blessed modifier order in jdk.incubator.foreign

### PR DESCRIPTION
**Pull request by alblue**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8264397](https://bugs.openjdk.java.net/browse/JDK-8264397): Use the blessed modifier order in jdk.incubator.foreign

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3253/head:pull/3253` \
`$ git checkout pull/3253`

Update a local copy of the PR: \
`$ git checkout pull/3253` \
`$ git pull https://git.openjdk.java.net/jdk pull/3253/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3253`

View PR using the GUI difftool: \
`$ git pr show -t 3253`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3253.diff">https://git.openjdk.java.net/jdk/pull/3253.diff</a>

</details>

### CODE REVIEW

**Comment by cl4es** [comment]
This one should probably be fixed in the upstream repo over at https://github.com/openjdk/panama-foreign (I believe). /ping @JornVernee @mcimadamore

**Comment by alblue** [comment]
Happy to submit a fix elsewhere if that's the right thing to do?

**Comment by mcimadamore** [comment]
Hi @alblue, thanks for the contribution. We will make sure to integrate this at some point, but I don't think now is the right moment to do this kind of stylistic changes to the API/implementation. If you want to integrate the fix now, I'd suggest to file a PR against https://github.com/openjdk/panama-foreign, and we'll be happy to sponsor the change. That way you'd be guaranteed the change would be included in the next incubation round.

**Comment by alblue** [comment]
Have submitted change to the panama-foreign branch; let me know if that's the appropriate place and I can abandon this PR.

**Comment by alblue** [comment]
Going to upstream this patch into opendjk/panama-foreign

**Pull request closed without merging**
