### PR TITLE
8272970: Parallelize runtime/InvocationTests/

### PR DESCRIPTION
**Pull request by shipilev**
Current runtime/InvocationTests/ are long and serial. They take about half an hour on a modern desktop, mostly using a single CPU. They can be parallelized better, at least on sub-test level. This would be important as [JDK-8272914](https://bugs.openjdk.java.net/browse/JDK-8272914) would start to run them in tier3.

Sample run times:

```
$ time CONF=linux-x86_64-server-fastdebug make run-test TEST=runtime/InvocationTests/

# Before
real	32m2.188s
user	59m12.818s
sys	0m45.612s

# After
real	17m21.110s
user	63m31.851s
sys	0m55.391s
```

I think we can technically go even deeper, for example parallelising by `packageSet` in the generators themselves, but that would be much more intrusive. I think 17 minutes is already quite good, given other tests running in prospective `hotspot:tier3`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272970](https://bugs.openjdk.java.net/browse/JDK-8272970): Parallelize runtime/InvocationTests/

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - **Reviewer**) ⚠️ Review applies to 3651efa3188b7218cf755aaf5204f6b4c9e366de

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5250/head:pull/5250` \
`$ git checkout pull/5250`

Update a local copy of the PR: \
`$ git checkout pull/5250` \
`$ git pull https://git.openjdk.java.net/jdk pull/5250/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5250`

View PR using the GUI difftool: \
`$ git pr show -t 5250`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5250.diff">https://git.openjdk.java.net/jdk/pull/5250.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Anyone else wants to take a look. @iignatev, maybe?

**Review by iignatev — APPROVED** [review]
LGTM. one nit: it should be possible to reduce clutter by removing `@compile` actions, could you please either do that here or file an RFE? 

PS I wish jtreg had a way not to duplicate all these tags, perhaps w/ some kind of a preprocessor.

**Comment by dholmes-ora** [comment]
@iignatev  At least some of the compile commands must remain. The top level test doesn't reference the actual test classes directly so must explicitly compile them. Any classes those directly reference do not need an explicit compile-command.

**Comment by shipilev** [comment]
> LGTM. one nit: it should be possible to reduce clutter by removing `@compile` actions, could you please either do that here or file an RFE?

Right. The generators are referencing the `shared/` stuff implicitly, so we can drop `@compile` for them. Tests still pass without them. See new commit.

**Review by dholmes-ora — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks, I think this is good to go in.

/integrate

**Pull request closed without merging**
