### PR TITLE
8292458: Atomic operations on scoped enums don't build with clang

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to allow the Atomic class to support scoped enum
values on all platforms.  We do this by adding PrimitiveConversions::Translate
support for enums (converting to/from the underlying type), and changing
relevant Atomic operations to use that translation instead of trying to handle
enums on the integer code path.

Testing:
mach5 tier1-3, including gtests added by this change

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292458](https://bugs.openjdk.org/browse/JDK-8292458): Atomic operations on scoped enums don't build with clang

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**) ⚠️ Review applies to [33e1c850](https://git.openjdk.org/jdk/pull/9895/files/33e1c85062568825100f761b1d37af110ff803bd)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [33e1c850](https://git.openjdk.org/jdk/pull/9895/files/33e1c85062568825100f761b1d37af110ff803bd)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9895/head:pull/9895` \
`$ git checkout pull/9895`

Update a local copy of the PR: \
`$ git checkout pull/9895` \
`$ git pull https://git.openjdk.org/jdk pull/9895/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9895`

View PR using the GUI difftool: \
`$ git pr show -t 9895`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9895.diff">https://git.openjdk.org/jdk/pull/9895.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good. Thank you for fixing this.

**Review by stefank — APPROVED** [review]
Looks good. Thanks for fixing.

**Comment by kimbarrett** [comment]
Thanks @fisk and @stefank for reviews.

**Pull request closed without merging**
