### PR TITLE
8308506: Reduce testing time by removing combinations tested

### PR DESCRIPTION
**Pull request by lkorinth**
Juggle3.java and Juggle3Quick.java tests many combinations of array juggling on different kinds of arrays. It tests:

- Primitive arrays (three for each kind of primitive)
- Object arrays
- Random arrays
- A version with hashing

However when testing using primitive arrays, there is --- from a gc perspective --- no extra logic tested by going through all combinations. By removing these, we can save time and put our resources on testing other stuff.

I will keep three versions of primitive array tests (low, medium and high) with different kinds of arrays.

Also, the random array test will still test all primitive versions of arrays.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308506](https://bugs.openjdk.org/browse/JDK-8308506): Reduce testing time by removing combinations tested

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14078/head:pull/14078` \
`$ git checkout pull/14078`

Update a local copy of the PR: \
`$ git checkout pull/14078` \
`$ git pull https://git.openjdk.org/jdk.git pull/14078/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14078`

View PR using the GUI difftool: \
`$ git pr show -t 14078`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14078.diff">https://git.openjdk.org/jdk/pull/14078.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14078#issuecomment-1557082411)

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

Note that for `Juggle3`, the changes keeps 

  boolean-medium
  float-high
  double-low
  double-high

i.e. three levels run _four_ times unlike the description suggests.

**Comment by lkorinth** [comment]
> Lgtm.
> 
> Note that for `Juggle3`, the changes keeps
> 
> boolean-medium float-high double-low double-high
> 
> i.e. three levels run _four_ times unlike the description suggests.

Juggle3 tests are the union of Juggle3.java and Juggle3Quick.java; It is an unfortunate arrangement because jtreg does not allow to create test groups from test IDs.

If you look at both files you will see that I am keeping:  byte-low, boolean-medium, float-high and all three *hashed* double.

**Review by lmesnik — APPROVED** [review]

**Comment by lkorinth** [comment]
Thanks Thomas and Leonid!

**Pull request closed without merging**
