### PR TITLE
8253757: Add LLVM-based backend for hsdis

### PR DESCRIPTION
**Pull request by magicus**
Third time's a charm! After the two previous closed PRs for this issue, I think this functionality is finally ready to enter mainline. :)

This code is at it's core the same as the previous PR. The main C++ hsdis implementation is still the one @luhenry wrote, with some changes. As in the previous PR, I extracted the LLVM-specific part into a separate file. In addition to the last PR, I have also fixed a warning, and added a patch inspired by @nick-arm for getting past instructions unknown to LLVM.

Thanks to the prototype written by @JornVernee (and his graciously providing me with a working version of LLVM build for Windows), this PR now has full support for LLVM on Windows (as well as Linux and macOS).

Finally, I have cleaned up the integration in autoconf and Hsdis.gmk, and written a thorough guide in the README on how to build witth LLVM, on Windows and on saner platforms. :)

I'm pretty sure this means that all comments and criticism in the previous PR has been addressed.

Huge thanks to everyone who has helped me with getting this PR in place. I have a hard time remember a feature that has been so tricky to get in place, for something to seemingly simple...

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253757](https://bugs.openjdk.java.net/browse/JDK-8253757): Add LLVM-based backend for hsdis

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Ludovic Henry](https://openjdk.java.net/census#luhenry) (@luhenry - Author)

### Contributors
 * Magnus Ihse Bursie `<ihse@openjdk.org>`
 * Ludovic Henry `<luhenry@openjdk.org>`
 * Jorn Vernee `<jvernee@openjdk.org>`
 * Nick Gasson `<ngasson@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7531/head:pull/7531` \
`$ git checkout pull/7531`

Update a local copy of the PR: \
`$ git checkout pull/7531` \
`$ git pull https://git.openjdk.java.net/jdk pull/7531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7531`

View PR using the GUI difftool: \
`$ git pr show -t 7531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7531.diff">https://git.openjdk.java.net/jdk/pull/7531.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]
Build changes look good. I can't comment on the hsdis implementation.

**Comment by luhenry** [comment]
Thanks again for pushing that forward! It's always good to have an alternative especially for porting to new platforms and architectures.

**Pull request closed without merging**
