### PR TITLE
8254855: Clean up and remove unused code in vmIntrinsics

### PR DESCRIPTION
**Pull request by cl4es**
- Remove unused code and constants
- Guard some code only used for assertions by ASSERT
- Adjust log2_FLAG_LIMIT (could have been 3 also before removing F_RNY)

Testing: tier1-3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8254855](https://bugs.openjdk.java.net/browse/JDK-8254855): Clean up and remove unused code in vmIntrinsics

### Reviewers
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Ioi Lam](https://openjdk.java.net/census#iklam) (@iklam - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/688/head:pull/688`
`$ git checkout pull/688`

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by dholmes-ora** [comment]
I don't agree with removing F_RNY just because we don't currently have intrinisics that match that shape! If someone were to add one then they would now have to repair the infrastructure code needed to support that.

**Comment by cl4es** [comment]
> I don't agree with removing F_RNY just because we don't currently have intrinisics that match that shape! If someone were to add one then they would now have to repair the infrastructure code needed to support that.

Several potentially useful permutations of static, native and synchronized are already missing, so I felt that removing a no longer used variant to be in the spirit of the existing code. I think the infrastructure is easy to repair if it's ever needed (at least easier than the act of adding an intrinsics), but if you feel strongly about it I'll add it back.

**Review by iklam — APPROVED** [review]
LGMT. I try to find the last time for_boxing() and verify_method()  were used, and they weren't even used in JDK7! So we have been carrying around this junk for quite a while.

**Comment by vnkozlov** [comment]
vmIntrinsics::verify_method() become unused after next change:
http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/75596850f863

**Comment by vnkozlov** [comment]
for_boxing() and for_unboxing() were added for JSR 292 reference implementation:
http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/aa62b9388fce

and then removed when JSR 292 was rewritten:
http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/1d7922586cf6?revcount=480

**Review by vnkozlov — APPROVED** [review]

**Comment by cl4es** [comment]
Thanks for reviewing - and digging up the history on when these went out of fashion. The JSR 292 rewrite also removed the concept of ricochetStubs. Getting rid of some remnants of that is another cleanup I have lined up.

/integrate

**Pull request closed without merging**
