### PR TITLE
8287970: riscv: jdk/incubator/vector/*VectorTests failing

### PR DESCRIPTION
**Pull request by feilongjiang**
[JDK-8284960](https://bugs.openjdk.org/browse/JDK-8284960) added a new vector operation VectorOperations.BIT_COUNT, which needs the support of PopCountV*. The following tests failed when enabling `UseRVV`:

jdk/incubator/vector/Byte256VectorTests.java
jdk/incubator/vector/ByteMaxVectorTests.java
jdk/incubator/vector/Int256VectorTests.java
jdk/incubator/vector/IntMaxVectorTests.java
jdk/incubator/vector/Short256VectorTests.java
jdk/incubator/vector/ShortMaxVectorTests.java

Tests are failing with "assert(n_type->isa_vect() == __null || lrg._is_vector || ireg == Op_RegD || ireg == Op_RegL || ireg == Op_RegVectMask) failed: vector must be in vector registers" because C2 instruct "vpopcountI" stores the result into a general-purpose register (GPR) instead of a vector register.

Currently, riscv vector extension `vpopc.m` instruction counts the number of mask elements of the active elements of the vector source mask register that has the value 1 and writes the result to a scalar x register. \[1] `PopCountV*` needs to write back the pop counting results to vector registers, there is no single instruction in rvv that can satisfy the requirement.  So we decide to remove the vpopcountI instruct for now.

\[1]: https://github.com/riscv/riscv-v-spec/releases/download/v1.0/riscv-v-spec-1.0.pdf

Additional Tests:
- [x] jdk/incubator/vector (release with UseRVV on QEMU)
- [x] hotspot:tier1 (release with UseRVV on QEMU without new failure)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287970](https://bugs.openjdk.org/browse/JDK-8287970): riscv: jdk/incubator/vector/*VectorTests failing

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [6a05b12c](https://git.openjdk.java.net/jdk/pull/9079/files/6a05b12cda5022dceb5552533f0c3bfc03e3065c)
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to [6a05b12c](https://git.openjdk.java.net/jdk/pull/9079/files/6a05b12cda5022dceb5552533f0c3bfc03e3065c)
 * [Yadong Wang](https://openjdk.java.net/census#yadongwang) (@yadongw - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9079/head:pull/9079` \
`$ git checkout pull/9079`

Update a local copy of the PR: \
`$ git checkout pull/9079` \
`$ git pull https://git.openjdk.java.net/jdk pull/9079/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9079`

View PR using the GUI difftool: \
`$ git pr show -t 9079`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9079.diff">https://git.openjdk.java.net/jdk/pull/9079.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Can you instead add Op_PopCountVI to op_vec_supported()?
Current change looks trivial and fine too.

**Comment by feilongjiang** [comment]
> Can you instead add Op_PopCountVI to op_vec_supported()? Current change looks trivial and fine too.

done

**Review by RealFYang — APPROVED** [review]
Changes looks fine and safe to me.

**Review by dean-long — APPROVED** [review]

**Comment by yadongw** [comment]
Please make sure SuperWord works properly without the match rule of PopCountVI and PopCountVL. See hotspot/jtreg/compiler/vectorization/TestPopCountVector.java and hotspot/jtreg/compiler/vectorization/TestPopCountVectorLong.java.

**Review by yadongw — APPROVED** [review]
lgtm

**Comment by feilongjiang** [comment]
> Please make sure SuperWord works properly without the match rule of PopCountVI and PopCountVL. See hotspot/jtreg/compiler/vectorization/TestPopCountVector.java and hotspot/jtreg/compiler/vectorization/TestPopCountVectorLong.java.

TestPopCountVector.java and TestPopCountVectorLong.java still passed with this change.

**Comment by feilongjiang** [comment]
@vnkozlov @dean-long @RealFYang @yadongw -- Thanks for the review!

/integrate

**Pull request closed without merging**
