### PR TITLE
8252406: Introduce Thread::as_Java_thread() convenience function

### PR DESCRIPTION
**Pull request by dholmes-ora**
This is a rather large but generally simple cleanup.

We use a lot of raw C-style casts to "(JavaThread*)" typically after checking "thread->is_Java_thread()". To simplify this pattern, and make the code look somewhat cleaner we introduce a convenience function Thread::as_Java_thread(), which asserts is_Java_thread() and returns "this" cast to "JavaThread*". A const version, as_const_Java_thread(), was also added to allow use in cases where we start with "const Thread *".

Summary of changes:
- changed raw casts to use as_Java_thread()
- removed redundant checks of is_Java_thread() as it is now done in as_Java_thread()
- Removed checks that are checking the type system e.g.
```
void foo(JavaThread* t) {
  assert(t->is_Java_thread(), "must be")
```
the only way the assert can fire is if someone deliberately bypasses the type system, and if we are going to worry about that then we would need asserts like this on every method that expects a JavaThread! The right place for the assertion is at the head of any such call chain.

- Removed asserts that are already guaranteed in the caller.
- Use JavaThread::current() where appropriate. 
- Use pre-existing "thread" variable where available rather than casting THREAD

Change locations found by grepping for variations of the cast syntax "(JavaThread*)" - it is possible some may have been missed.

Testing: tiers 1-3

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252406](https://bugs.openjdk.java.net/browse/JDK-8252406): Introduce Thread::as_Java_thread() convenience function

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 689951708fccd0073873e645bf683bc34b75a772
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 50dd8b3874d2557d465d7216061906f5e69cb16b
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/37/head:pull/37`
`$ git checkout pull/37`

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
Drive-by comment: Shenandoah changes look good.

**Comment by dholmes-ora** [comment]
Thanks @shipilev ! Sending this out for RFR now.

**Review by shipilev — APPROVED** [review]
Shenandoah parts still look good. Formally approving.

**Review by coleenp — APPROVED** [review]

**Comment by coleenp** [comment]
I'll look at v5 diffs but if I don't, this is still reviewed.  Nice cleanup.

**Review by kimbarrett — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
This is a really nice set of cleanup changes.

I have a few comments.

https://openjdk.github.io/cr/?repo=jdk&pr=37&range=06#frames-33
  51   if (thread->is_Java_thread())
  52     return thread->as_Java_thread()->thread_state() == _thread_in_vm;
  53   else
  54     return thread->is_VM_thread();
      nit - this code needs braces. Not your bug, but since you've touched this
      code, do you mind fixing it?

Note: I included the link the webrev had me on, but I have no idea what
file that is...

https://openjdk.github.io/cr/?repo=jdk&pr=37&range=06#frames-80

276   guarantee(current == get_thread() || current == get_thread()->active_handshaker(),
277                     "must be current thread or direct handshake");

    nit - the indent on L277 looks wrong in the webrev, but it looks right in
    this paste. I don't know which is telling the truth.

https://openjdk.github.io/cr/?repo=jdk&pr=37&range=06#frames-101

 358     this->as_Java_thread()->set_stack_overflow_limit();
 359     this->as_Java_thread()->set_reserved_stack_activation(stack_base());
    nit - do you really need 'this->' here?

https://openjdk.github.io/cr/?repo=jdk&pr=37&range=06#frames-107

old code:
2074   if (thread_id == 0) {
2075     // current thread
2076     if (THREAD->is_Java_thread()) {
2077       return ((JavaThread*)THREAD)->cooked_allocated_bytes();
2078     }
2079     return -1;

new code:
2074   if (thread_id == 0) { // current thread
2075     return thread->cooked_allocated_bytes();

If the calling thread is not a JavaThread and passes a thread_id ==0,
I don't think the returns are equivalent.

The craziness in the JavaThread::pd_get_top_frame() functions made my head hurt.
Thanks for cleaning that up!

**Comment by dcubed-ojdk** [comment]
I don't see how to add myself as a reviewer... what am I missing?

**Review by dcubed-ojdk — APPROVED** [review]

**Review by dcubed-ojdk — APPROVED** [review]
Incremental looks good to me.

**Pull request closed without merging**
