### PR TITLE
JDK-8272853: improve `JavadocTester.runTests`

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review a medium simple test-only fix to improve the `JavadocTester` `runTests` methods.

Currently, there are two overloads: one to invoke no-args test methods, and another to invoke test methods with args, such as a method-specific `Path`.  This latter one is slightly inconvenient to use, since it requires the boilerplate use of a function to create the arguments.

The first overload is updated in a backwards compatible way, to examine the parameters of methods annotated with `@Test`, and to recognize common patterns: namely no-args methods and `(Path)` methods, without the need for any additional function.  The second overload is retained by backwards compatibility, until if and when we decide it is no longer required.

In addition, two new overloads are added, similar to the first two, but with the addition of an extra parameter to decide which methods should be invoked. This is primarily a debugging aid.  Using these overloads, it is easy to specify, on the command line used to run the test, the methods to be executed.

A new test is added to test the new functionality.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272853](https://bugs.openjdk.java.net/browse/JDK-8272853): improve `JavadocTester.runTests`

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.java.net/census#hannesw) (@hns - **Reviewer**) ⚠️ Review applies to 438781356aaf3759c2655d31913a7f62a9a8b6fa

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6983/head:pull/6983` \
`$ git checkout pull/6983`

Update a local copy of the PR: \
`$ git checkout pull/6983` \
`$ git pull https://git.openjdk.java.net/jdk pull/6983/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6983`

View PR using the GUI difftool: \
`$ git pr show -t 6983`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6983.diff">https://git.openjdk.java.net/jdk/pull/6983.diff</a>

</details>

### CODE REVIEW

**Comment by hns** [comment]
Making the boilerplate to call test methods with a path object obsolete is a very welcome enhancement. Can and should we update existing tests that use the explicit method -> path function to the new form?

You say that the new forms that take a list of method names could be used by passing the method names as command line arguments. That functionality is not included in this PR as far as I can see. Is that planned for a later time?

**Review by hns — APPROVED** [review]
Sorry for letting this linger for so long. I asked some questions in the comments, but that was not meant to block the PR. The changes look good to me.

**Comment by jonathan-gibbons** [comment]
@hns I tweaked the new "self-test" to address failures seen on some platforms.  
I weakened the constraint that `IllegalArgumentException` should _always_ be thrown before _any_ sub-tests are executed. While this may be good as a general principle, it doesn't work so well when the `ILA` comes from a nested call. Rather than twist the code so that `ILA` is always thrown early, I left `JavadocTester` alone, and just relaxed the code in `TestRunTests.java` to allow `ILA` to be thrown later, in some situations.

FWIW, the issue did not show up earlier, because the order of methods returned by `getDeclaredMethods` is explicitly undefined and may vary across platforms.

**Comment by hns** [comment]
Thanks for the explanation, looks good to me!

**Pull request closed without merging**
