### PR TITLE
8319115: GrowableArray: Do not initialize up to capacity

### PR DESCRIPTION
**Pull request by jdksjolen**
Hi,

There's no reason to initialize the memory for the elements in the range `[_len, _capacity)` on resize, so let's not do it.

Currently running testing tier1-3.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8319115](https://bugs.openjdk.org/browse/JDK-8319115): GrowableArray: Do not initialize up to capacity (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16418/head:pull/16418` \
`$ git checkout pull/16418`

Update a local copy of the PR: \
`$ git checkout pull/16418` \
`$ git pull https://git.openjdk.org/jdk.git pull/16418/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16418`

View PR using the GUI difftool: \
`$ git pr show -t 16418`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16418.diff">https://git.openjdk.org/jdk/pull/16418.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16418#issuecomment-1785411747)

### CODE REVIEW

**Comment by jdksjolen** [comment]
I moved this into draft because I forgot to delete a couple of places where we also do this. I'll open it up when tests seems to be passing again.

**Comment by stefank** [comment]
Isn't the intention of the current code that we should always have fully constructed objects up to _capacity?

After this change, it now seems like we're operating on non-constructed objects in append:
```
  int append(const E& elem) {
    if (this->_len == this->_capacity) grow(this->_len);
    int idx = this->_len++;
    this->_data[idx] = elem; <<< HERE
    return idx;
}
```

Contrast this to std::vector::push_back, which first 'creates' an object in the array and then 'assigns' to it. GrowableArray implemented the 'create' part in the `grow` function.

**Comment by jdksjolen** [comment]
Hi Stefan,

> Isn't the intention of the current code that we should always have fully constructed objects up to _capacity?
> 
Yes, this is the intention of the current code. 
> After this change, it now seems like we're operating on non-constructed objects in append:
> 
> ```
>   int append(const E& elem) {
>     if (this->_len == this->_capacity) grow(this->_len);
>     int idx = this->_len++;
>     this->_data[idx] = elem; <<< HERE
>     return idx;
> }
> ```
> 
I see this as with this patch this will call the copy assignment operator and as `this->_data[idx]` isn't initialized at that point this code will technically be UB, am I right in that interpretation? This is one of the snippets of code that made me put this back into draft, I noticed that there are many places where we do depend on this.

> Contrast this to std::vector::push_back, which first 'creates' an object in the array and then 'assigns' to it. GrowableArray implemented the 'create' part in the `grow` function.

Reading cppreference https://en.cppreference.com/w/cpp/container/vector/push_back and https://en.cppreference.com/w/cpp/named_req/CopyInsertable it seems that `push_back` will call the copy constructor with placement new, so there's no separate creation and thereafter assignment.

This PR is tightly related to https://github.com/openjdk/jdk/pull/16409 . My goal is to avoid unnecessary calling of copy constructors and copy assignment operators in order to make it viable later on for move semantics to be used for `GrowableArray`.

**Comment by merykitty** [comment]
In addition to constructing elements on inserting operations, you will need to destroy them when calling `clear`, `remove`, etc. I think this patch may help us be able to or get closer to the possibility to use `GrowableArray` for non-default-constructible types, which is valueable.

**Comment by stefank** [comment]
> I see this as with this patch this will call the copy assignment operator and as this->_data[idx] isn't initialized at that point this code will technically be UB, am I right in that interpretation?

Right. This is what I was reacting to.

> Reading cppreference https://en.cppreference.com/w/cpp/container/vector/push_back and https://en.cppreference.com/w/cpp/named_req/CopyInsertable it seems that push_back will call the copy constructor with placement new, so there's no separate creation and thereafter assignment.

OK. I was mislead by the comment inside std::vector:
```
       *  This is a typical stack operation.  The function creates an
       *  element at the end of the %vector and assigns the given data
       *  to it.  Due to the nature of a %vector this operation can be
       *  done in constant time if the %vector has preallocated space
       *  available.
```

I made a small test and it shows that push_back uses the copy constructor as you say.

**Pull request closed without merging**
