### PR TITLE
6633375: FileOutputStream_md.c should be merged into FileOutputStream.c

### PR DESCRIPTION
**Pull request by bplb**
Merge identical Unix and Windows versions of FileOutputStream_md.c into single, common FileOutputStream.c.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-6633375](https://bugs.openjdk.java.net/browse/JDK-6633375): FileOutputStream_md.c should be merged into FileOutputStream.c

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4589/head:pull/4589` \
`$ git checkout pull/4589`

Update a local copy of the PR: \
`$ git checkout pull/4589` \
`$ git pull https://git.openjdk.java.net/jdk pull/4589/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4589`

View PR using the GUI difftool: \
`$ git pr show -t 4589`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4589.diff">https://git.openjdk.java.net/jdk/pull/4589.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — COMMENTED** [review]
Looks good. Would you consider removing `fos_fd` and passing it as a `jlong` as suggested in the issue?

**Comment by bplb** [comment]
The `fileOpen()`, `writeSingle()`, and `writeBytes()` functions called here all expect to receive a field ID. This might be worth investigating as a separate issue.

**Review by naotoj — APPROVED** [review]
Fine by me.

**Comment by bplb** [comment]
> Fine by me.

Thanks!

**Pull request closed without merging**
