### PR TITLE
8328822: C2: "negative trip count?" assert failure in profile predicate code

### PR DESCRIPTION
**Pull request by rwestrel**
The assert failure is caused by:
```
ABS(min_jint) = min_jint
```

Given the `ABS` is part of a floating computation, the fix I propose
is to cast the value to float before the `ABS`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328822](https://bugs.openjdk.org/browse/JDK-8328822): C2: "negative trip count?" assert failure in profile predicate code (**Bug** - P3)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18707/head:pull/18707` \
`$ git checkout pull/18707`

Update a local copy of the PR: \
`$ git checkout pull/18707` \
`$ git pull https://git.openjdk.org/jdk.git pull/18707/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18707`

View PR using the GUI difftool: \
`$ git pr show -t 18707`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18707.diff">https://git.openjdk.org/jdk/pull/18707.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18707#issuecomment-2046761628)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks good and simple enough to me.

**Review by chhagedorn — APPROVED** [review]
Looks good to me, too.

**Comment by rwestrel** [comment]
@shipilev @chhagedorn thanks for the reviews

**Pull request closed without merging**
