### PR TITLE
8075916: The regression-swing case failed as colored text is not shown on disabled checkbox and radio button with Nimbus LAF

### PR DESCRIPTION
**Pull request by prsadhuk**
CheckBox.disabledText and RadioButton.disabledText color UIProperty is not honoured by Nimbus L&F when disabled text is drawn for JCheckBox and JRadioButton, so disabled text color was rendered incorrectly.
Fix is to honour these UIProperty color if they are set by user, else use the color from the component or via getColorForState().

Closed test as mentioned in JBS is used to check the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8075916](https://bugs.openjdk.org/browse/JDK-8075916): The regression-swing case failed as colored text is not shown on disabled checkbox and radio button with Nimbus LAF

### Reviewers
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Author) ⚠️ Review applies to [a9b7c028](https://git.openjdk.org/jdk/pull/10177/files/a9b7c028e039118b26193624e4b074c1928fd899)
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10177/head:pull/10177` \
`$ git checkout pull/10177`

Update a local copy of the PR: \
`$ git checkout pull/10177` \
`$ git pull https://git.openjdk.org/jdk pull/10177/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10177`

View PR using the GUI difftool: \
`$ git pr show -t 10177`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10177.diff">https://git.openjdk.org/jdk/pull/10177.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
>⚠️ Failed to retrieve information on issue 8075916.
JBS issue is closed.

**Comment by prsadhuk** [comment]
Its open now

**Comment by jayathirthrao** [comment]
Does this fix the issue in GTK LAF also? I see a comment in JBS that same issue is with GTK LAF.

**Comment by jayathirthrao** [comment]
Closed test case mentioned in JBS runs only in Default LAF. We need to explicitly specify LAF.
Also it looks like closed test is unstable:
1) With default LAF test hangs in my mac
2) With Nimbus LAF it passes without the fix.

Its better to add separate regression test to verify this fix.

**Comment by prsadhuk** [comment]
> Closed test case mentioned in JBS runs only in Default LAF. We need to explicitly specify LAF. Also it looks like closed test is unstable:
> 
>     1. With default LAF test hangs in my mac
> 
>     2. With Nimbus LAF it passes without the fix.
> 
> 
> Its better to add separate regression test to verify this fix.

I dont see this problem. In my mac BigSur, default LAF passed and Nimbus L&F fails without the fix.

**Comment by jayathirthrao** [comment]
> > Closed test case mentioned in JBS runs only in Default LAF. We need to explicitly specify LAF. Also it looks like closed test is unstable:
> > ```
> > 1. With default LAF test hangs in my mac
> > 
> > 2. With Nimbus LAF it passes without the fix.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Its better to add separate regression test to verify this fix.
> 
> I dont see this problem. In my mac BigSur, default LAF passed and Nimbus L&F fails without the fix.

I have Monterey. I think its better to have open test case which verifies the behavior specific to Nimbus LAF(and may be GTK LAF if that is also getting fixed under this bug)

**Comment by prsadhuk** [comment]
> > > Closed test case mentioned in JBS runs only in Default LAF. We need to explicitly specify LAF. Also it looks like closed test is unstable:
> > > ```
> > > 1. With default LAF test hangs in my mac
> > > 
> > > 2. With Nimbus LAF it passes without the fix.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Its better to add separate regression test to verify this fix.
> > 
> > 
> > I dont see this problem. In my mac BigSur, default LAF passed and Nimbus L&F fails without the fix.
> 
> I have Monterey. I think its better to have open test case which verifies the behavior specific to Nimbus LAF(and may be GTK LAF if that is also getting fixed under this bug)

I tested on Monterey also and there also I didn't see this problem. 
Default L&F passed and Nimbus L&F failed without fix.

**Comment by jayathirthrao** [comment]
> > > > Closed test case mentioned in JBS runs only in Default LAF. We need to explicitly specify LAF. Also it looks like closed test is unstable:
> > > > ```
> > > > 1. With default LAF test hangs in my mac
> > > > 
> > > > 2. With Nimbus LAF it passes without the fix.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Its better to add separate regression test to verify this fix.
> > > 
> > > 
> > > I dont see this problem. In my mac BigSur, default LAF passed and Nimbus L&F fails without the fix.
> > 
> > 
> > I have Monterey. I think its better to have open test case which verifies the behavior specific to Nimbus LAF(and may be GTK LAF if that is also getting fixed under this bug)
> 
> I tested on Monterey also and there also I didn't see this problem. Default L&F passed and Nimbus L&F failed without fix.

Okay. I have new M1 machine may be it is machine specific issue.

**Review by TejeshR13 — APPROVED** [review]
Fix tested and verified.

**Comment by prsadhuk** [comment]
> Please provide the regression test which iterates over all Look-and-Feels to make sure the setting is always honoured.

Test added

**Review by aivanov-jdk — APPROVED** [review]

**Comment by mrserb** [comment]
The spec for the changed method mention that the "getColorForState" should be called for the component if the app did not specify the color explicetly. Should the fix do the same instead of direct call of "UIManager.getColor"? And if it does not work should we updated the skin to include these props?

**Pull request closed without merging**
