### PR TITLE
8329545: [s390x] Fix garbage value being passed in Argument Register

### PR DESCRIPTION
**Pull request by sid8606**
Fix sign extension on 4 byte load from argument stack slot to GPR.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329545](https://bugs.openjdk.org/browse/JDK-8329545): [s390x] Fix garbage value being passed in Argument Register (**Bug** - P2)

### Reviewers
 * [Amit Kumar](https://openjdk.org/census#amitkumar) (@offamitkumar - Committer)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18601/head:pull/18601` \
`$ git checkout pull/18601`

Update a local copy of the PR: \
`$ git checkout pull/18601` \
`$ git pull https://git.openjdk.org/jdk.git pull/18601/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18601`

View PR using the GUI difftool: \
`$ git pr show -t 18601`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18601.diff">https://git.openjdk.org/jdk/pull/18601.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18601#issuecomment-2034359986)

### CODE REVIEW

**Review by offamitkumar — APPROVED** [review]
I have done `{tier1} X {fastdebug, slowdebug, release}` test and do not see any new failure appearing. 

Thanks Sid for fixing it.

**Comment by sid8606** [comment]
@TheRealMDoerr please review this patch.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by sid8606** [comment]
Thanks for the reviews. I integrate now.
/integrate

**Pull request closed without merging**
