### PR TITLE
8305669: RuntimeException when running benchmarks through make on Windows/WSL

### PR DESCRIPTION
**Pull request by liach**
This patch replaces `FIXPATH` with `FixPath` on individual path argumenets. The root cause might be that JMH requires passing VM args to benchmarks in quotes, which might have triggered incorrect detections in `FIXPATH` (as in comparison, `$1_MICRO_JAVA_OPTIONS += --add-opens=java.base/java.io=ALL-UNNAMED` right above this patch seems to work fine)
Also removed a useless and wrong Java flag to the java running javac, originally intended to enable running `make test TEST="loom.obsolete"` benchmarks.

Since I only have a windows cygwin environment, I am not quite sure if this works elsewhere.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305669](https://bugs.openjdk.org/browse/JDK-8305669): RuntimeException when running benchmarks through make on Windows/WSL

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13550/head:pull/13550` \
`$ git checkout pull/13550`

Update a local copy of the PR: \
`$ git checkout pull/13550` \
`$ git pull https://git.openjdk.org/jdk.git pull/13550/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13550`

View PR using the GUI difftool: \
`$ git pr show -t 13550`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13550.diff">https://git.openjdk.org/jdk/pull/13550.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13550#issuecomment-1515629753)

### CODE REVIEW

**Comment by JornVernee** [comment]
This patch is not working for me on WSL. It results in:

```
/mnt/h/openjdk/git-jdk2/build/windows-release/images/jdk/bin/java
```

The command is missing a trailing `.exe`, which is needed on WSL. I think `FIXPATH` on the entire invocation takes care of this.

**Comment by liach** [comment]
As I see, other places where java execution is used uses `$$(JAVA)` to extract the Java executable without fixpath. However, micro testing allows arbitrary JDK, which makes configuring the right path somewhat harder as a consequence, as it seems the build code to extract java executable is part of configure and there is no easily reusable code elsewhere.

**Comment by JornVernee** [comment]
Simpler reproducer: 

```
bash -x /mnt/h/openjdk/git-jdk2/build/windows-release/fixpath print '-Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED'
```

Shows:
```
++ print_command_line '-Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED'
++ converted_args=
++ for arg in "$@"
++ [[ -Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED =~ ^@(.*$) ]]
++ convert_path '-Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED'
++ [[ -Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED =~ : ]]
++ arg='-Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED'
++ winpath=
++ [[ -Djava.library.path=/mnt/h/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED =~ ^([^/]*|-[^:=]*[:=]|.*file://|/[a-zA-Z:]{1,3}:?)(/mnt/)([a-z])(/[^/]+.*$) ]]
++ prefix=-Djava.library.path=
++ winpath='h:/openjdk/git-jdk2/build/windows-release/images/test/micro/native --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base/jdk.internal.classfile.impl=ALL-UNNAMED'
++ [[ 20 -eq 2 ]]
++ [[ '' != true ]]
++ winpath='h:\openjdk\git-jdk2\build\windows-release\images\test\micro\native --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base\jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.impl=ALL-UNNAMED'
++ [[ h:\openjdk\git-jdk2\build\windows-release\images\test\micro\native --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base\jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.impl=ALL-UNNAMED != '' ]]
++ result='-Djava.library.path=h:\openjdk\git-jdk2\build\windows-release\images\test\micro\native --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports=java.base\jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.attribute=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.constantpool=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.instruction=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.java.lang.constant=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.components=ALL-UNNAMED --add-exports=java.base\jdk.internal.classfile.impl=ALL-UNNAMED'
```

i.e. fixpath thinks all of the stuff after `/mnt/h` is a part of the path

**Comment by JornVernee** [comment]
FWIW, I've just been working around this issue so far by temporarily removing the --add-exports flags. They are only needed to run the classfile API benchmarks. An alternative solution, if fixpath can't be fixed, is to pass the flags in the benchmark files themselves: https://github.com/openjdk/jdk/compare/master...JornVernee:jdk:WinBenchFail

**Comment by liach** [comment]
> Simpler reproducer:
> 
> ```
> bash -x ./make/scripts/fixpath.sh print '-Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> ```
> 
> Shows:
> 
> ```
> + print_command_line '-Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> + converted_args=
> + for arg in "$@"
> + [[ -Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED =~ ^@(.*$) ]]
> + convert_path '-Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> + [[ -Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED =~ : ]]
> + arg='-Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> + winpath=
> + [[ -Djava.library.path=/mnt/h/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED =~ ^([^/]*|-[^:=]*[:=]|.*file://|/[a-zA-Z:]{1,3}:?)(/mnt/)([a-z])(/[^/]+.*$) ]]
> + prefix=-Djava.library.path=
> + winpath='h:/xyz --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> + [[ 20 -eq 2 ]]
> + [[ '' != true ]]
> + winpath='h:\xyz --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> + [[ h:\xyz --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED != '' ]]
> + result='-Djava.library.path=h:\xyz --add-exports=java.base\jdk.internal.org.objectweb.asm=ALL-UNNAMED'
> ```
> 
> i.e. fixpath thinks all of the stuff after `/mnt/h` is a part of the path

Do you know if fixpath will take unix-style path with spaces as input? If it should reject spaces, then we can run fixpath before quote and reject this quoted argument with space, which is known to be absent in unix paths.

**Comment by JornVernee** [comment]
> Do you know if fixpath will take unix-style path with spaces as input? If it should reject spaces, then we can run fixpath before quote and reject this quoted argument with space, which is known to be absent in unix paths.

I'm not sure. I'll ask around.

**Comment by liach** [comment]
Since I have WSL setup [fixed](https://mail.openjdk.org/pipermail/build-dev/2023-May/039249.html), I have tested this patch in cygwin, wsl 1, and a linux target wsl 2 environments. All three runs normally.

This patch is indeed ugly, but I don't think we have reliable ways to tell FixPath to only consider a space part of a Windows directory name when it's quoted, especially quotes can be further complicated by escapes. Thus I just did the simple, by exporting the needed functionalities and replace the needed parts for jmh invocation.

**Review by erikj79 — APPROVED** [review]

**Comment by liach** [comment]
Per Claes https://github.com/openjdk/jdk/pull/13671#discussion_r1188840349 we should move the open and export additions to the individual tests instead of adding them during building of the microbenchmark suite. I will wait for others opinions before deciding the way to go.

**Comment by erikj79** [comment]
> Per Claes [#13671 (comment)](https://github.com/openjdk/jdk/pull/13671#discussion_r1188840349) we should move the open and export additions to the individual tests instead of adding them during building of the microbenchmark suite. I will wait for others opinions before deciding the way to go.

If there is a way to supply them in the tests themselves (similar to how we do for jtreg tests), then I agree that is a better idea than adding them globally for the whole test run.

**Comment by liach** [comment]
Thanks for the conclusions. A quick peek into the benchmarks show there are currently three types of exports/opens:
1. java.io opens, present since the beginning of the benchmark suite
2. classfile and asm opens for the Class-File API benchmarks
3. jdk.internal.vm for a few loom benchmarks, added incorrectly to javac's vm args upon loom integration

The latter two cases are easy to take care of; loom one is used by some of those deprecated benchmarks. I don't know where the first java.io opens is required and might need others help to investigate that.

In addition, I think users can still pass in `--add-exports` and `--add-opens` with `MICRO_JAVA_OPTIONS` from test arguments, which may still get FixPath'd and break. If that is the case, this patch would still have some value.

**Comment by liach** [comment]
Withdrawing this patch, as #13671 fixes benchmark running. The one for loom can be fixed in a separate rfe.

**Pull request closed without merging**
