### PR TITLE
8223051: support loops with long (64b) trip counts

### PR DESCRIPTION
**Pull request by rwestrel**
Last webrev was:

https://cr.openjdk.java.net/~roland/8223051/webrev.03/

This PR includes a few minor changes:

- The change in callnode.cpp that Vladimir requested in: https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-August/039551.html

- Extra comments that John requested in: https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-August/039621.html

- A couple extra counters to collect more detailed statistics

8252696 (Loop unswitching may cause out of bound array load to be
executed) was the only bug that was uncovered by extended testing and
it's fixed now.

This was previously reviewed by Tobias, Vladimir and John. Given the
last changes were either requested by reviewers or a straighforward
improvement to statistics, and unless someone objects, I intend to
push this in the next few days with the reviewer list I just
mentioned.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8223051](https://bugs.openjdk.java.net/browse/JDK-8223051): support loops with long (64b) trip counts

### Reviewers
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**) ⚠️ Review applies to 2dd3a151b65f11bb2603e8b92c052daf5e5e6844
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to 2dd3a151b65f11bb2603e8b92c052daf5e5e6844
 * [John R Rose](https://openjdk.java.net/census#jrose) (@rose00 - **Reviewer**) ⚠️ Review applies to 2dd3a151b65f11bb2603e8b92c052daf5e5e6844

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/318/head:pull/318`
`$ git checkout pull/318`

### CODE REVIEW

**Review by iwanowww — APPROVED** [review]
Looks good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Review by rose00 — APPROVED** [review]
Good to go.  Thanks for patiently working all the issue.

**Pull request closed without merging**
