### PR TITLE
8302795: Shared archive failed on old version class with jsr bytecode

### PR DESCRIPTION
**Pull request by calvinccheung**
Please review this simple fix for avoid writing in to CDS archive during runtime while loading a shared old class (major_version < 50) with methods containg the jsr byte code.
Otherwise, JVM crashes with the following message in the hs err log:
`Error accessing class data sharing archive. Mapped file inaccessible during execution, possible disk/network problem.`

Passed tiers 1 - 4 testing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302795](https://bugs.openjdk.org/browse/JDK-8302795): Shared archive failed on old version class with jsr bytecode

### Reviewers
 * [Yumin Qi](https://openjdk.org/census#minqi) (@yminqi - **Reviewer**)
 * [Matias Saavedra Silva](https://openjdk.org/census#matsaave) (@matias9927 - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12752/head:pull/12752` \
`$ git checkout pull/12752`

Update a local copy of the PR: \
`$ git checkout pull/12752` \
`$ git pull https://git.openjdk.org/jdk pull/12752/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12752`

View PR using the GUI difftool: \
`$ git pr show -t 12752`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12752.diff">https://git.openjdk.org/jdk/pull/12752.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — COMMENTED** [review]
Sorry I'm having a little trouble following the problem and solution here. The problem IIUC:
- If we load a class with JSR bytecodes then we have to rewrite those to avoid the use of JSR.
- If we dumped such a class into the shared archive it is in the RO part of the archive.
- If we attempt to rewrite a class in the RO section then we crash.

The solution would seem to be a choice of:
a) don't rewrite the class; or
b) don't archive it

The solution presented here seems to be (a) but I thought we had to rewrite classes with JSR bytecodes ???

**Comment by calvinccheung** [comment]
> 
> The solution would seem to be a choice of: a) don't rewrite the class; or b) don't archive it
> 
> The solution presented here seems to be (a) but I thought we had to rewrite classes with JSR bytecodes ???

Option b is harder to do because we currently cannot link old classes during dump time. So we can't simply do the following check to see is a jsr bytecode is present during dump time.
`m->has_jsrs()`

In order to do the above check during dump time, for an "old" class, we'll need to check all the methods and for each method check all the byte codes and see if a jsr bytecode is present.

I'll try to implement the above.

**Comment by calvinccheung** [comment]
I have pushed a commit. The fix is make the _methods array writable during dump time for "old" classes with the jsr byte code.
Ran tiers 1 - 3 testing successfully.

**Review by dholmes-ora — COMMENTED** [review]
I'm not familiar enough with CDS to review this in detail sorry. The approach sounds reasonable.

Thanks

**Review by yminqi — APPROVED** [review]
LGTM. We know after 49.0 (java 5), jsr will not be generated, so this should not be a problem for dynamic dumping too.

**Review by matias9927 — APPROVED** [review]
This makes sense, rewriting the method should rewrite the JSR bytecodes and any matching RET bytecodes. LGTM!

**Comment by calvinccheung** [comment]
Thanks @yminqi and @matias9927 for the review.

/integrate

**Pull request closed without merging**
