### PR TITLE
8283467: runtime/Thread/StopAtExit.java needs updating

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
A small fix to convert the runtime/Thread/StopAtExit.java from using the
java.lang.Thread.stop() method to using the JVM/TI StopThread() method.

This fix has been tested with Mach5 Tier[134567] (upper tiers in process)
and StressWrapper_StopAtExit.java testing for 4 hours for each config {release,
fastdebug,slowdebug}. No failures and no memory leaks were observed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283467](https://bugs.openjdk.java.net/browse/JDK-8283467): runtime/Thread/StopAtExit.java needs updating

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 8d31eb4e346ff68444f199d4687d8de939f5e8fa
 * [Patricio Chilano Mateo](https://openjdk.java.net/census#pchilanomate) (@pchilano - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7910/head:pull/7910` \
`$ git checkout pull/7910`

Update a local copy of the PR: \
`$ git checkout pull/7910` \
`$ git pull https://git.openjdk.java.net/jdk pull/7910/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7910`

View PR using the GUI difftool: \
`$ git pr show -t 7910`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7910.diff">https://git.openjdk.java.net/jdk/pull/7910.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,
David

**Comment by dholmes-ora** [comment]
You will need to re-test now that JDK-8282952 has integrated.

**Comment by dcubed-ojdk** [comment]
@dholmes-ora - Thanks for the review.

I'm definitely planning on a retest of this fix. Was there anything
in particular that you are worried about?

**Comment by dcubed-ojdk** [comment]
Merged with master to pickup the fix for:

JDK-8282952 Thread::exit should be immune to Thread.stop
https://bugs.openjdk.java.net/browse/JDK-8282952

Retesting with Mach5 Tier[13] which are still running.
Also doing a 30 minute stress run of my StressWrapper_StopAtExit.java
in {release,fastdebug,slowdebug} configs.

**Comment by dcubed-ojdk** [comment]
Could use a second reviewer for this test fix.

**Comment by dholmes-ora** [comment]
> I'm definitely planning on a retest of this fix. Was there anything in particular that you are worried about?

Nope not worried at all. Just wanted to ensure things were in sync.

**Comment by dcubed-ojdk** [comment]
Still need a second reviewer for this test fix...

**Review by pchilano — APPROVED** [review]
LGTM!

Thanks,
Patricio

**Pull request closed without merging**
