### PR TITLE
8270893: IndexOutOfBoundsException while reading large TIFF file

### PR DESCRIPTION
**Pull request by jayathirthrao**
We are incorrectly passing source offset to ImageInputStream.readFully() which is getting used on destination buffer. streamPos maintained in each implementation of stream maintain's appropriate source offset while reading the data. Since we are completely utilizing destination buffer any offset greater than 0 would cause IOOBE. In our case we should use 0 as offset value.

Also to hit this code we need stream/file with at-least 1MB of IFD data, that's why there is no regression test. This change can be verified using image attached in JBS. All test run is green.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270893](https://bugs.openjdk.java.net/browse/JDK-8270893): IndexOutOfBoundsException while reading large TIFF file

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to 81d54f09e93564c21367779435640fde6dce1dde
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4836/head:pull/4836` \
`$ git checkout pull/4836`

Update a local copy of the PR: \
`$ git checkout pull/4836` \
`$ git pull https://git.openjdk.java.net/jdk pull/4836/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4836`

View PR using the GUI difftool: \
`$ git pr show -t 4836`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4836.diff">https://git.openjdk.java.net/jdk/pull/4836.diff</a>

</details>

### CODE REVIEW

**Comment by jayathirthrao** [comment]
RFR(Adding comment to check whether will we get RFR mail)

**Comment by jayathirthrao** [comment]
Ping

**Comment by mrserb** [comment]
Is it possible to create a testcase for this fix? Probably this regression should be fixed in jdk17?

**Comment by prrace** [comment]
> Is it possible to create a testcase for this fix? Probably this regression should be fixed in jdk17?

FWIW the fixer had already written :
"Also to hit this code we need stream/file with at-least 1MB of IFD data, that's why there is no regression test"

Maybe 1Mb isn't actually a blocker, and it would be good to learn if we can create a TIFF image of that size and have github accept it.

But we definitely should run all the relevant existing regression tests.

As for JDk 17, we are in RDP 2 and this has been out there for exactly (?) 12 months until the first report and will need backporting anyway to other release trains.
So it is safer to put in 18 and backport later to a 17 update

**Review by prrace — APPROVED** [review]
Approving but I would like some more evidence that a test is not practical.

**Comment by jayathirthrao** [comment]
> > Is it possible to create a testcase for this fix? Probably this regression should be fixed in jdk17?
> 
> FWIW the fixer had already written :
> "Also to hit this code we need stream/file with at-least 1MB of IFD data, that's why there is no regression test"
> 
> Maybe 1Mb isn't actually a blocker, and it would be good to learn if we can create a TIFF image of that size and have github accept it.
> 
> But we definitely should run all the relevant existing regression tests.
> 
> As for JDk 17, we are in RDP 2 and this has been out there for exactly (?) 12 months until the first report and will need backporting anyway to other release trains.
> So it is safer to put in 18 and backport later to a 17 update

Sure i will take a look at creating regression test case for this issue and see whether we can hit this particular path.
All client tier test cases were run and CI job link is present in the JBS and it is green with fix.
Yes i am planning to backport it to the trains where the original issue was fixed.

**Comment by mrserb** [comment]
We can save the header of the image as a binary array and then generate the image on the fly by filling the content with zeros. So it is not necessary to store such file in the repo.

**Comment by jayathirthrao** [comment]
I went through TIFF spec and image provided in the bug to understand whether we can find a way to pass similar data to reproduce the issue.

The image attached in JBS has ICCProfile as one of the TIFFTag(This is considered as UNDEFINED tag by our standard reader) and its count is more than 1024000. And for this ICCProfile tag corresponding data is also present in the stream, it is not some corrupt header scenario where we can just write bad data in header and hit the issue. We divide the tag data in chunks on 1024000 bytes, when we are done reading first chunk of ICCProfile data and start reading the second chunk we hit this issue.

So to add regression test for this scenario i need more than 1024000 bytes of data in one of the TIFFTag type where the present change is done. We will not be able to pass that amount of data in byteArray stream. Also if we want to pass raw data as part of a TIFFTag i need relevant TIFFtag data like ICCProfile in the image attached in JBS.

 So i am leaving discussion open so that others can give inputs on ways we can put relevant data into our TIFFImageWriter to hit this issue.

**Comment by mrserb** [comment]
1024000 bytes does not look like a big problem especially if it is generated on the fly during the test execution?
You can try to load the data for our PYCC color profile and set one of its tag data to a big chunk like icSigCopyrightTag, or you can try to just fill it by zeros at the end.

**Comment by jayathirthrao** [comment]
@mrserb added regression test, please review.

**Review by mrserb — APPROVED** [review]
Thank you! look fine.
BTW Looks like stream.readFully(unit, 0, sz) can be simplified to the stream.readFully(unit)?

**Comment by jayathirthrao** [comment]
> Thank you! look fine.
> BTW Looks like stream.readFully(unit, 0, sz) can be simplified to the stream.readFully(unit)?

Thanks for the review. Yes we can simplify readFully(), looks like we have other instances of similar usage of readFully() in this file. I would like to cleanup all of them but then i dont want to face issues while backporting it to different trains. So i would not refactor readFully() in this PR, if needed i will do refactoring as part of another bug.

**Pull request closed without merging**
