### PR TITLE
8323693: Update some copyright announcements in the new files created in 8234502

### PR DESCRIPTION
**Pull request by LizBing**
see 'https://github.com/openjdk/jdk/pull/17398#pullrequestreview-1819022919'

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323693](https://bugs.openjdk.org/browse/JDK-8323693): Update some copyright announcements in the new files created in 8234502 (**Task** - P4)

### Reviewers
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17412/head:pull/17412` \
`$ git checkout pull/17412`

Update a local copy of the PR: \
`$ git checkout pull/17412` \
`$ git pull https://git.openjdk.org/jdk.git pull/17412/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17412`

View PR using the GUI difftool: \
`$ git pr show -t 17412`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17412.diff">https://git.openjdk.org/jdk/pull/17412.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17412#issuecomment-1890260722)

### CODE REVIEW

**Review by plummercj — APPROVED** [review]
Looks good.

**Comment by LizBing** [comment]
This patch seems trivial. I wonder if it needs two reviews.

**Review by dholmes-ora — APPROVED** [review]
Yes this could be considered trivial, but Reviewed anyway.

Thanks

**Comment by LizBing** [comment]
thanks for the review.
/integrate

**Pull request closed without merging**
