### PR TITLE
JDK-8273783: Simplify Metaspace arena guard handling

### PR DESCRIPTION
**Pull request by tstuefe**
Hi,

may I please have reviews for this patch.

This simplifies metaspace arena guard handling and reduces the complexity guard mode brings to metaspace and its tests. It makes future modifications easier (esp. wrt Lilliput).

----

Metaspace has a guard mode which I added as part of JEP 387. It means that metaspace allocations are bracketed by canaries which, if broken, indicate a buffer overrun in metaspace. It can be switched on and off using -XX:+MetaspaceGuardAllocations, is by default off, and a debug-only feature.

I was always a bit unhappy with the implementation though since it seemed too complex and one needed a bit of lateral thinking when looking at arenas. This is because guard prefixes change block size, cause problems with deallocations, require thinking about user pointer alignment etc.

When investigating how to compress compressed class pointers beyond 32-bit for Lilliput, working around all that special handling became too complicated and therefore I'd like a simpler solution.

The new mechanism uses the fact that Metaspace is an arena allocator and we therefore know that (almost) all subsequent allocations are adjacent to each other in memory. Therefore, instead of adding guards as prefixes/suffixes with each allocation, we can just allocate the guard block as a separate block after each user allocation, as if the guard were just another user allocation. 

The result is exactly the same as before: all real allocations are separated in memory by a guard. But to most of the metaspace, these guard blocks are just normal allocations. A lot of special handling can be removed. And we don't have to disable deallocation handling in guard mode.

The guard blocks are chained together via a simple pointer list and verifying them just means walking that list and examining the eyecatcher. Note that the guard has two eyecatchers, bracketing the next pointer between them - that way we don't have to do a sanity check on the pointer since an overwriter would likely have overwritten one of the eyecatchers before corrupting the pointer.

Small caveats:
- the first block in a chunk has no leading fence
- the last block in a chunk *may* have no trailing fence
- the guard now costs 24 bytes, up from 16 before.

Note that all these caveats could be easily solved with a bit more intricate bit fiddling. However, I opted for simplicity here. Guard mode is only activated on demand, if one suspects a problem, and I think it works good enough this way.

Tests:
- Nightlies at SAP
- manual tests on x64 and x86 with and without guards
- manual gtests
- manual metaspace jtreg tests

Thanks, Thomas

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273783](https://bugs.openjdk.java.net/browse/JDK-8273783): Simplify Metaspace arena guard handling

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5518/head:pull/5518` \
`$ git checkout pull/5518`

Update a local copy of the PR: \
`$ git checkout pull/5518` \
`$ git pull https://git.openjdk.java.net/jdk pull/5518/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5518`

View PR using the GUI difftool: \
`$ git pr show -t 5518`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5518.diff">https://git.openjdk.java.net/jdk/pull/5518.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi Thomas,

I can't really review this, but I'm running it through our internal tier 1-3 testing.

David

**Comment by tstuefe** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@mail.openjdk.java.net):_
> 
> On 17/09/2021 11:54 am, David Holmes wrote:
> 
> > On Wed, 15 Sep 2021 06:10:36 GMT, Thomas Stuefe <stuefe at openjdk.org> wrote:
> > > Hi,
> > > may I please have reviews for this patch.
> > > This simplifies metaspace arena guard handling and reduces the complexity guard mode brings to metaspace and its tests. It makes future modifications easier (esp. wrt Lilliput).
> > 
> > 
> > I can't really review this, but I'm running it through our internal tier 1-3 testing.
> 
> That testing passed - one unrelated crash.
> 
> David

 Thank you David!

**Review by coleenp — APPROVED** [review]
This looks good, and much simpler!

**Comment by tstuefe** [comment]
> This looks good, and much simpler!

Thank you Coleen!

**Review by RealLucy — APPROVED** [review]
LGTM.
Much simpler code now. I like the KISS principle (keep it simple and <you select the last word>.

**Comment by tstuefe** [comment]
> LGTM.
> Much simpler code now. I like the KISS principle (keep it simple and (you select the last word).

:-) Yep, me too. Thanks!

**Pull request closed without merging**
