### PR TITLE
8269113: Javac throws when compiling switch (null)

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

When we use `switch(null)` in the source code, the type of the selector is `BottomType`.
So the statement `Type seltype = selector.type;` of the method `TransPatterns::handleSwitch` will get a `BottomType`.
Then compiler mistakenly uses this `BottomType` to construct a new `VarSymbol`.

```
            VarSymbol temp = new VarSymbol(Flags.SYNTHETIC,
                    names.fromString("selector" + tree.pos + target.syntheticNameChar() + "temp"),
                    seltype,     // <--------here is a BottomType
                    currentMethodSym);
```

At last, when the compiler uses the new `VarSymbol temp` to construct a new `JCVariableDecl`(the code shown as below), it crashes at the method `TreeMaker::Type` because the method `TreeMaker::Type` can't handle the type `BottomType`.

```
statements.append(make.at(tree.pos).VarDef(temp, !hasNullCase ? attr.makeNullCheck(selector)
                                                                          : selector));
```

This patch changes the type from `BottomType` to `syms.objectType` and adds the corresponding test.
Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269113](https://bugs.openjdk.java.net/browse/JDK-8269113): Javac throws when compiling switch (null)

### Reviewers
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4679/head:pull/4679` \
`$ git checkout pull/4679`

Update a local copy of the PR: \
`$ git checkout pull/4679` \
`$ git pull https://git.openjdk.java.net/jdk pull/4679/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4679`

View PR using the GUI difftool: \
`$ git pr show -t 4679`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4679.diff">https://git.openjdk.java.net/jdk/pull/4679.diff</a>

</details>

### CODE REVIEW

**Review by lahodaj — APPROVED** [review]
Looks good to me. Might make sense to submit against openjdk/jdk17 and integrate there?

**Comment by lgxbslgx** [comment]
@lahodaj thanks for your review. I will move this patch to JDK 17 later.

**Comment by lahodaj** [comment]
I am sorry, but it may not be so simple. I apologize for that, I need to do some more investigations, sorry.

**Comment by lgxbslgx** [comment]
Never mind. I will continue to contact or assist you in this PR. If the final patch is not large, it could be moved to JDK 17 at last.

**Pull request closed without merging**
