### PR TITLE
8318027: Support alternative name to jdk.internal.vm.compiler

### PR DESCRIPTION
**Pull request by dougxc**
The Graal code base has [renamed](https://github.com/oracle/graal/commit/1e41203d10db321f86723eac90f6cd0573b08b33) its module to `jdk.compiler.graal` as part of preparations for Project Galahad. Due to the way Java modules work, this requires a JDK change. The core of the issue is that the [service](https://github.com/openjdk/jdk/blob/56aa1e8dc8047cbc29d554889c64beb6eca0b8eb/src/jdk.internal.vm.ci/share/classes/module-info.java#L37) by which HotSpot requests a Graal compilation is defined in JVMCI. Since JVMCI is in the boot layer, the service can only be implemented by a provider in the boot layer and the package defining the service must be exported to the provider's defining module. This export currently targets [`jdk.internal.vm.compiler`](https://github.com/openjdk/jdk/blob/56aa1e8dc8047cbc29d554889c64beb6eca0b8eb/src/jdk.internal.vm.ci/share/classes/module-info.java#L28) and so the binding fails for the new Graal module. To address this, this PR reflects the Graal module renaming, including adjusting the qualified export.

Edit: The target of the rename is now `jdk.graal.compiler` - see https://github.com/openjdk/jdk/pull/16189#issuecomment-1773764186

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318027](https://bugs.openjdk.org/browse/JDK-8318027): Support alternative name to jdk.internal.vm.compiler (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [6b729561](https://git.openjdk.org/jdk/pull/16189/files/6b7295613abf6344866d17c6f22e20c029cca800)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [6b729561](https://git.openjdk.org/jdk/pull/16189/files/6b7295613abf6344866d17c6f22e20c029cca800)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [193e22a6](https://git.openjdk.org/jdk/pull/16189/files/193e22a674670d832be17e705f72f782b70c7dec)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16189/head:pull/16189` \
`$ git checkout pull/16189`

Update a local copy of the PR: \
`$ git checkout pull/16189` \
`$ git pull https://git.openjdk.org/jdk.git pull/16189/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16189`

View PR using the GUI difftool: \
`$ git pr show -t 16189`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16189.diff">https://git.openjdk.org/jdk/pull/16189.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16189#issuecomment-1772751340)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by magicus — APPROVED** [review]
Build changes look trivially good.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Why you replaced pair of copyright years with one year in module-info.Java files? Instead of updating last year only.
Why also update 'since' there?
Even if you changed location these files existed already.

**Comment by dougxc** [comment]
> Why you replaced pair of copyright years with one year in module-info.Java files? Instead of updating last year only. Why also update 'since' there? Even if you changed location these files existed already.

The files may be renamed from git's point of view, but I would argue that these are new modules and so should have a new `@since` tag. Otherwise, someone seeing that `jdk.compiler.graal` existed `@since 9` may be a little surprised/confused if they look for it in a JDK 9 binary. Same thinking applies to the copyright dates. Happy to fix it if this is the wrong way to think about it.

**Comment by vnkozlov** [comment]
Copyright is associated with file and should be kept, only update last year.
I don't know rules about 'since'. But there will be no confusion for developers. Everyone knows that these files were created for Graal from the start.

**Comment by mbreinhold** [comment]
The `@since` tag should reflect the release in which the tagged element was introduced (i.e., 22), not the release in which some predecessor of the element was introduced.

**Comment by dougxc** [comment]
Ok, thanks for the clarification. What about the copyright dates on the `module-info.java` files?

**Comment by mbreinhold** [comment]
Vladimir was right about the copyright dates — they should record the year in which the content was created and last updated, regardless of the content’s name.

**Review by AlanBateman — APPROVED** [review]
The module config and test update looks fine.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by jonathan-gibbons** [comment]
The proposed name `jdk.compiler.graal` makes it seem like the module is strongly related to the `jdk.compiler` module, which contains `javac` and related tools, whereas these modules are completely unrelated.

Is there not a better name that can be used?

**Comment by mbreinhold** [comment]
Jon makes a good point. If memory serves, wasn’t the name `jdk.graal.compiler` suggested previously? That would avoid the overlap with the name of the existing `jdk.compiler` module.

**Comment by dougxc** [comment]
Based on external discussion, agreement has been reached to rename to `jdk.graal.compiler` instead of `jdk.compiler.graal`.
Not only does this avoid the confusion with `jdk.compiler` pointed out by @jonathan-gibbons but it also establishes the namespace `jdk.graal` for Graal subprojects.

**Review by Hamlin-Li — APPROVED** [review]

**Review by AlanBateman — APPROVED** [review]

**Comment by dougxc** [comment]
Thanks for all the reviews and careful consideration on this naming change. It will have long term consequences so getting it right is important.

/integrate

**Pull request closed without merging**
