### PR TITLE
8257589: HotSpot Style Guide should link to rfc7282

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to the link for the definition of "rough consensus".
The current link is to a Wikipedia article that references rfc7282.  We should
instead link directly the the RFC.  This change was requested during the
review of JDK-8247976, but not made at that time. (I'm not sure whether it was
intentionally deferred or missed/forgotten.)

As this is a HotSpot Style Guide change, it requires reviewers who are HotSpot
Group Members, though comments from others are welcome.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257589](https://bugs.openjdk.java.net/browse/JDK-8257589): HotSpot Style Guide should link to rfc7282

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 8ba75e76f3e16f3ced1b49114f668d23dcee9a7b
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 8ba75e76f3e16f3ced1b49114f668d23dcee9a7b

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7693/head:pull/7693` \
`$ git checkout pull/7693`

Update a local copy of the PR: \
`$ git checkout pull/7693` \
`$ git pull https://git.openjdk.java.net/jdk pull/7693/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7693`

View PR using the GUI difftool: \
`$ git pr show -t 7693`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7693.diff">https://git.openjdk.java.net/jdk/pull/7693.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by dholmes-ora — APPROVED** [review]
Glad I don't have to figure out when consensus exists! :)

**Pull request closed without merging**
