### PR TITLE
JDK-8273914: Indy string concat changes order of operations

### PR DESCRIPTION
**Pull request by cushon**
This change makes string concatenation call `toString` on the arguments eagerly, to preserve the correct evaluation order of the arguments and the calls to `toString`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8273914](https://bugs.openjdk.java.net/browse/JDK-8273914): Indy string concat changes order of operations
 * [JDK-8274863](https://bugs.openjdk.java.net/browse/JDK-8274863): Indy string concat changes order of operations (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)
 * [Jan Lahoda](https://openjdk.java.net/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5844/head:pull/5844` \
`$ git checkout pull/5844`

Update a local copy of the PR: \
`$ git checkout pull/5844` \
`$ git pull https://git.openjdk.java.net/jdk pull/5844/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5844`

View PR using the GUI difftool: \
`$ git pr show -t 5844`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5844.diff">https://git.openjdk.java.net/jdk/pull/5844.diff</a>

</details>

### CODE REVIEW

**Comment by cushon** [comment]
> Okay, can you please add a comment to the jasm file that explains that.

Done

**Comment by lahodaj** [comment]
How about code like:
```
        StringBuilder builder2 = new StringBuilder("foo");
        Object oo = builder2;
        oo += "" + builder2.append("bar"); 
```

Should that be covered as well? From looking at the patch (not really trying it), it does not seem to be covered?

**Comment by cushon** [comment]
> > ```
> >         StringBuilder builder2 = new StringBuilder("foo");
> >         Object oo = builder2;
> >         oo += "" + builder2.append("bar"); 
> > ```
> >   
> > Should that be covered as well? From looking at the patch (not really trying it), it does not seem to be covered?
> 
> Tried it, still not correct:
> 
> I believe `if (shouldConvertToStringEagerly(argType))` branch should be handled for first argument as well, i.e. code should be shaped as:
> 
> @cushon, could you do this change and add a relevant test case?

Fixed, thanks!

**Comment by cushon** [comment]
> This pull request has been inactive for more than 4 weeks

The [CSR is still in progress](https://bugs.openjdk.java.net/browse/JDK-8274863?focusedCommentId=14458216&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14458216)

**Comment by cushon** [comment]
The CSR has been [approved for 19](https://bugs.openjdk.java.net/browse/JDK-8274863?focusedCommentId=14462390&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14462390), this is ready for review pending integration after the JDK 18 branch is cut.

**Comment by cushon** [comment]
@lahodaj would you be willing to review for the compiler group?

**Review by vicente-romero-oracle — APPROVED** [review]
the compiler changes look good to me

**Review by lahodaj — APPROVED** [review]
Looks reasonable.

**Pull request closed without merging**
