### PR TITLE
8278581: Improve reference processing statistics log output

### PR DESCRIPTION
**Pull request by albertnetymk**
The first commit renames `Cleared` to `Dropped` and added `Processed` in the log output.

The second commit compressed the log output into one line per ref-type. The final log format looks like:

```
[11.803s][debug][gc,phases,ref  ] GC(0)   SoftReference Discovered: 0, Dropped: 0, Processed: 0
[11.803s][debug][gc,phases,ref  ] GC(0)   WeakReference Discovered: 1147, Dropped: 752, Processed: 395
[11.803s][debug][gc,phases,ref  ] GC(0)   FinalReference Discovered: 0, Dropped: 0, Processed: 0
[11.803s][debug][gc,phases,ref  ] GC(0)   PhantomReference Discovered: 242, Dropped: 2, Processed: 240
```

Test: hotspot_gc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278581](https://bugs.openjdk.java.net/browse/JDK-8278581): Improve reference processing statistics log output

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6806/head:pull/6806` \
`$ git checkout pull/6806`

Update a local copy of the PR: \
`$ git checkout pull/6806` \
`$ git pull https://git.openjdk.java.net/jdk pull/6806/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6806`

View PR using the GUI difftool: \
`$ git pr show -t 6806`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6806.diff">https://git.openjdk.java.net/jdk/pull/6806.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by kstefanj — APPROVED** [review]

**Comment by albertnetymk** [comment]
Thanks for the review.

/integrate

**Comment by pliden** [comment]
A bit late to the party, and maybe not directly related to your change, but I just thought I should mention that the output in ZGC looks like this:
```
[1.813s][info][gc,ref         ] GC(0) Soft: 87 encountered, 0 discovered, 0 enqueued
[1.813s][info][gc,ref         ] GC(0) Weak: 246 encountered, 83 discovered, 82 enqueued
[1.813s][info][gc,ref         ] GC(0) Final: 2 encountered, 0 discovered, 0 enqueued
[1.813s][info][gc,ref         ] GC(0) Phantom: 53 encountered, 48 discovered, 36 enqueued
```
IMHO, "enqueued" is a better name than "Processed" in this context (you could argue that all references goes through some level of processing, not just the ones that are eventually enqueued). Having "dropped" seems superfluous to me. Also, having "encountered" is useful to see how many there are in total.

**Comment by albertnetymk** [comment]
> "enqueued" is a better name than "Processed" in this context

"enqueued" could be misleading due to its similarity with `Reference::enqueue()/ReferenceQueue` though.

> Having "dropped" seems superfluous to me.

Kim prefers having all three metrics, so I went for the current approach. (I agree there's some redundancy here.)

"Having all 3 of Discovered, Dropped (though with a better name?), and Processed would be nice since it avoids needing to calculate one from the other two."

> having "encountered" is useful to see how many there are in total.

True, but I am not sure how useful "knowing the total #refs" is. After all, only discovered-ref affects the duration of ref-processing. Ref-encountering happens along with marking, but #encountered doesn't directly affect marking phase duration.

**Comment by pliden** [comment]
> "enqueued" could be misleading due to its similarity with Reference::enqueue()/ReferenceQueue though.

I actually think it's a good that it eludes to Reference::enqueue(). Even if the enqueuing onto the ReferenceQueue happens in the next step, the enqueuing onto the pending list is the precursor.

> True, but I am not sure how useful "knowing the total #refs" is. After all, only discovered-ref affects the duration of ref-processing. Ref-encountering happens along with marking, but #encountered doesn't directly affect marking phase duration.

I've found "encountered" to be very useful when debugging.

**Pull request closed without merging**
