### PR TITLE
8263154: [macos] DMG builds have finder errors

### PR DESCRIPTION
**Pull request by sashamatveev**
- Issue was reproducible when install-dir points to some invalid location.
 - Fixed by defaulting DMG drag and drop location to /Applications folder and --install-dir will be ignored with warning for DMG.
 - I do not see any way to support other valid, but uncommon locations for drag and drop. For example: /Users/USERNAME/Applications is not possible to support since user name is not known. /usr/bin requires root privileges and should contain symbolic links. Locations which does not exist also not possible to support, since DMG cannot create paths. So /Applications/MyCompany is not possible for DMG.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263154](https://bugs.openjdk.java.net/browse/JDK-8263154): [macos] DMG builds have finder errors

### Reviewers
 * [Andy Herrick](https://openjdk.java.net/census#herrick) (@andyherrick - **Reviewer**)
 * [Alexey Semenyuk](https://openjdk.java.net/census#asemenyuk) (@alexeysemenyukoracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3505/head:pull/3505` \
`$ git checkout pull/3505`

Update a local copy of the PR: \
`$ git checkout pull/3505` \
`$ git pull https://git.openjdk.java.net/jdk pull/3505/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3505`

View PR using the GUI difftool: \
`$ git pr show -t 3505`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3505.diff">https://git.openjdk.java.net/jdk/pull/3505.diff</a>

</details>

### CODE REVIEW

**Review by andyherrick — COMMENTED** [review]
Doesn't much of this argument apply to pkg builds too ?
I hate to abandon install-dir option entirely for dmg, and just printing a warning and ignoring the argument is contrary to what is done for other arguments.
Is there any way, in the apple script, to check if the install-dir exists, and to use it if it does ?
Also wouldn't it be useful (for both pkg and dmg) to have ability to install into the users home directory ?
just specifying ~ or ~/Applications gets expanded before going in script if not quoted, and doesn't work if it is quoted.
Unless we define a meaning for non-fully qualified path in install-dir that should probably be a hard error..

**Comment by sashamatveev** [comment]
Not sure if I understood question about PKG. PKG can create destination folders and will have root access once elevated, so user can specify any locations for --install-dir in case of PKG.
Well DMG is not an installer it is just disk image which contains app (think of it as archive file), so we cannot really support all functionality with DMG as with actual installers.
Yes, I can check if install-dir exist with apple script, but destination machine might not have this folder. Permissions might be different on folder on machine which generates DMG and machine which will install it.
If PKG cannot be install into user home Applications folder, then it is another bug.

Also, if someone really want --install-dir to some other location they can overwrite apple script we using via resource folder. This fix only affects apple script we generate to customize DMG. Extra step for user, but I think it will not be common anyway.

**Comment by andyherrick** [comment]
Since target directory shown by apple script is only a suggestion, and user can drag app to anywhere in finder, I may be able to be convinced to ignore install-dir on dmg builds.
I don't think we should use Log.info() to say given install-dir is ignored, it should just be Log.verbose(). (I started the bad precedence when I used Log.info for messages about foreign app-image, this should have been Log.verbose() too).

**Comment by sashamatveev** [comment]
Should we always show warning messages, especially that output will be different from what user expected? I can switch to Log.verbose(), but I still think it should be displayed always.

**Comment by andyherrick** [comment]
It's my feeling that there should probably be no stdout/stderr from the jpackage tool other than what is specified (--help, --version, and hard errors).  If that is consensus we should also change the warnings about foreign app-image to Log.verbose, if not we can leave this Log.info() as is.

**Review by andyherrick — APPROVED** [review]
Consensus is to leave as Log.info() - so all looks good.

**Pull request closed without merging**
