### PR TITLE
JDK-8280492: Use cross-module syntax for cross-module links

### PR DESCRIPTION
**Pull request by jddarcy**
Use presumed syntax that will be introduced by JDK-8280488.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280492](https://bugs.openjdk.java.net/browse/JDK-8280492): Use cross-module syntax for cross-module links

### Reviewers
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to b74e7d859506dac118d76043990f1fde94d64fa0
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**) ⚠️ Review applies to b74e7d859506dac118d76043990f1fde94d64fa0
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to b74e7d859506dac118d76043990f1fde94d64fa0
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to b74e7d859506dac118d76043990f1fde94d64fa0
 * [Alexey Ivanov](https://openjdk.java.net/census#aivanov) (@aivanov-jdk - **Reviewer**) ⚠️ Review applies to b74e7d859506dac118d76043990f1fde94d64fa0

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7189/head:pull/7189` \
`$ git checkout pull/7189`

Update a local copy of the PR: \
`$ git checkout pull/7189` \
`$ git pull https://git.openjdk.java.net/jdk pull/7189/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7189`

View PR using the GUI difftool: \
`$ git pr show -t 7189`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7189.diff">https://git.openjdk.java.net/jdk/pull/7189.diff</a>

</details>

### CODE REVIEW

**Comment by jddarcy** [comment]
This should be the (near) final step to fully enable all doclint checks during the javac portion of the build. The "reference" doclint check is currently disabled in the build command for several modules. The problematic references are cross-module @see and @link tags. This PR changes those tags to use a to a new proposed syntax for cross-module references.

Before this PR is pushed, the javadoc changes need to be made and I'll update the make files to enable the "reference" warning category.

**Review by irisclark — APPROVED** [review]

**Review by mrserb — APPROVED** [review]

**Review by LanceAndersen — APPROVED** [review]

**Review by dfuch — APPROVED** [review]

**Comment by dfuch** [comment]
LGTM. I hope in the future IDEs will pick that rule up and offer some help when writing `{@link }` `@see`...

**Comment by pavelrappo** [comment]
> LGTM. I hope in the future IDEs will pick that rule up and offer some help when writing `{@link }` `@see`...

They will do it quicker, if you create new or support existing bugs in their bug trackers.

**Comment by pavelrappo** [comment]
> Use presumed syntax that will be introduced by JDK-8280488.

Is that a wrong bug? If you are talking about module-prefix syntax for links, then it was introduced in JDK 15; JDK-8164408: Add module support for @see, @link and @linkplain javadoc tags.

**Comment by jddarcy** [comment]
> > Use presumed syntax that will be introduced by JDK-8280488.
> 
> Is that a wrong bug? If you are talking about module-prefix syntax for links, then it was introduced in JDK 15; JDK-8164408: Add module support for @see, @link and @linkplain javadoc tags.

Ah; thanks Pavel for the additional context. Bug JDK-8280488 will allow (i.e. ignore) cross-module @see/@link references during javac compilation. So while the syntax in this PR is already valid per JDK-8164408, I cannot (yet) enable the "reference" doctlint check in the javac build due to the cross-module situation.

I'll double-check the syntax in this PR generates the expected links in the result of the docs builds, give the bug a more descriptive title, and get these changes pushed. Enabling the reference warning can be done under another bug.

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
