### PR TITLE
JDK-8303443: IGV: Syntax highlighting and resizing for filter editor

### PR DESCRIPTION
**Pull request by tobiasholenstein**
In the Filter window of the IdealGraphVisualizer (IGV) the user can double-click on a filter to edit the javascript code. 

- Previously, the code window was not resizable and had no syntax highlighting
editor_old

- Now, the code window can be resized by the user and has basic syntax highlighting for `keywords`, `strings` and `comments`
editor_new

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303443](https://bugs.openjdk.org/browse/JDK-8303443): IGV: Syntax highlighting and resizing for filter editor

### Reviewers
 * [Roberto Castañeda Lozano](https://openjdk.org/census#rcastanedalo) (@robcasloz - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12803/head:pull/12803` \
`$ git checkout pull/12803`

Update a local copy of the PR: \
`$ git checkout pull/12803` \
`$ git pull https://git.openjdk.org/jdk pull/12803/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12803`

View PR using the GUI difftool: \
`$ git pr show -t 12803`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12803.diff">https://git.openjdk.org/jdk/pull/12803.diff</a>

</details>

### CODE REVIEW

**Review by robcasloz — CHANGES_REQUESTED** [review]
Thanks for improving this area of IGV!

I found a few issues in the changeset:

1. The proposed font ("Courier") is not very readable on my system (Ubuntu Linux):

courier

I suggest using the logical font "Monospaced" instead [for portability](https://docs.oracle.com/en/java/javase/19/docs/api/java.desktop/java/awt/Font.html):

 monospaced

2. The changeset edits the generated code area of `EditFilterDialog.java`, making it out of sync with `EditFilterDialog.form`. Would it be possible to change that part of `EditFilterDialog.java` using NetBeans' GUI Builder instead? (so that `EditFilterDialog.form` stays on sync). 

3. When I run IGV, make some change in a filter, close IGV, then re-run it again, I end up with the same filters loaded multiple times:

filters

**Comment by tobiasholenstein** [comment]
> Thanks for improving this area of IGV!
> 
> I found a few issues in the changeset:
> 
> 1. The proposed font ("Courier") is not very readable on my system (Ubuntu Linux):
> 
> courier
> 
> I suggest using the logical font "Monospaced" instead [for portability](https://docs.oracle.com/en/java/javase/19/docs/api/java.desktop/java/awt/Font.html):
> 
> monospaced
> 
> 2. The changeset edits the generated code area of `EditFilterDialog.java`, making it out of sync with `EditFilterDialog.form`. Would it be possible to change that part of `EditFilterDialog.java` using NetBeans' GUI Builder instead? (so that `EditFilterDialog.form` stays on sync).
> 3. When I run IGV, make some change in a filter, close IGV, then re-run it again, I end up with the same filters loaded multiple times:
> 
> filters

@robcasloz thanks for the feedback! I fixed 1) and 2) as suggested. 
Regarding 3) I decided to remove it from this PR. Better to add this functionality separately

**Review by robcasloz — APPROVED** [review]
Thanks for addressing my comments, looks good!

**Review by TobiHartmann — APPROVED** [review]
Works well for me too.

**Comment by tobiasholenstein** [comment]
thanks @robcasloz and @TobiHartmann for the reviews! 

/integrate

**Pull request closed without merging**
