### PR TITLE
8316929: Shenandoah: Shenandoah degenerated GC and full GC need to cleanup old OopMapCache entries

### PR DESCRIPTION
**Pull request by zhengyu123**
During STW root scan, interpreted frame's oop map may be cached. But due to limited cache size (32 entries per instance class), entries may be evicted to old entries list due to collision, should be cleanup in VM_Operation's doit_epilogue(), or risk leaking memory.

Test:
  hotspot_gc_shenandoah (fastdebug and release on MacOSX)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316929](https://bugs.openjdk.org/browse/JDK-8316929): Shenandoah: Shenandoah degenerated GC and full GC need to cleanup old OopMapCache entries (**Bug** - P3)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15921/head:pull/15921` \
`$ git checkout pull/15921`

Update a local copy of the PR: \
`$ git checkout pull/15921` \
`$ git pull https://git.openjdk.org/jdk.git pull/15921/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15921`

View PR using the GUI difftool: \
`$ git pr show -t 15921`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15921.diff">https://git.openjdk.org/jdk/pull/15921.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15921#issuecomment-1735487709)

### CODE REVIEW

**Comment by earthling-amzn** [comment]
This looks good to me. Does the issue also affect 17?

**Comment by zhengyu123** [comment]
> This looks good to me. Does the issue also affect 17?

Yes. I updated affected versions in bug.

**Comment by zhengyu123** [comment]
@earthling-amzn @rkennke @shipilev Could you please review? Thanks!

**Review by shipilev — COMMENTED** [review]
This looks okay, but I think you can "just" add `OMC::cleanup_old_entries` in `VM_ShenandoahReferenceOperation` destructor, without introducing the intermediary?

**Comment by zhengyu123** [comment]
> This looks okay, but I think you can "just" add `OMC::cleanup_old_entries` in `VM_ShenandoahReferenceOperation` destructor, without introducing the intermediary?



> This looks okay, but I think you can "just" add `OMC::cleanup_old_entries` in `VM_ShenandoahReferenceOperation` destructor, without introducing the intermediary?

Place the call in `doit_epilogue()` for the symmetry with other [GCs](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/gc/shared/gcVMOperations.cpp#L135). But you are right, we don't need another  VM operation.

**Review by shipilev — APPROVED** [review]
Looks fine, thanks!

**Comment by zhengyu123** [comment]
Thanks, @shipilev

**Pull request closed without merging**
