### PR TITLE
8253860: PPC: Relocation::pd_set_data_value conflates compressed oops and klasses

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Casting narrow Klass pointer to a narrow Oop is problematic. Note that `NativeMovConstReg::set_narrow_oop` only supports narrow Oops.
It turns out, that the problematic code is unused. We never patch narrow Klass pointers in the instruction stream on PPC64 (`metadata_Relocation::pd_fix_value` has an empty implementation). In contrast to that, narrow Oops in the instructions stream always get patched when the nmethod gets installed (by `fix_oop_relocations`). This makes sense as Metadata doesn't get relocated, but Oops may be moved by GC and the instructions need to get the current value during nmethod installation.
Note that the initial constants we were using for narrow Oops in the instruction stream were not correct (Oop compression missing, not updated by GC). So, I think it's better to use 0 to avoid confusion.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253860](https://bugs.openjdk.java.net/browse/JDK-8253860): PPC: Relocation::pd_set_data_value conflates compressed oops and klasses

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6716/head:pull/6716` \
`$ git checkout pull/6716`

Update a local copy of the PR: \
`$ git checkout pull/6716` \
`$ git pull https://git.openjdk.java.net/jdk pull/6716/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6716`

View PR using the GUI difftool: \
`$ git pr show -t 6716`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6716.diff">https://git.openjdk.java.net/jdk/pull/6716.diff</a>

</details>

### CODE REVIEW

**Comment by dean-long** [comment]
Looks reasonable to me.

**Review by dean-long — APPROVED** [review]

**Comment by reinrich** [comment]
Hi Martin,

your change looks good, but...

> It turns out, that the problematic code is unused. We never patch narrow Klass
> pointers in the instruction stream on PPC64 (metadata_Relocation::pd_fix_value
> has an empty implementation)

I wonder if this is actually correct looking at

https://github.com/openjdk/jdk/blob/62a7f5d3236ab2248518a475b1d8b71cb4bf1313/src/hotspot/share/code/compiledMethod.cpp#L657

My understanding of the comment is that the corresponding static stub can be
executed by some JavaThread T after the Method* for the interpreter was set to
NULL. NULL is handled in BarrierSetAssembler::c2i_entry_barrier():

https://github.com/openjdk/jdk/blob/965ea8d9cd29aee41ba2b1b0b0c67bb67eca22dd/src/hotspot/cpu/ppc/gc/shared/barrierSetAssembler_ppc.cpp#L191

On PPC only the Method* in the metadata pool is set to NULL but not in the
constant pool. So T can reach the entry barrier with a stale value for
R19_method, can't it?

What do you think?

Cheers, Richard.

**Comment by TheRealMDoerr** [comment]
Thanks for the review, Dan!
Thanks for reviewing and asking this interesting questions, Richard!
Doesn't x86 have the same issue? `metadata_Relocation::pd_fix_value` is empty on that platform as well and the `Method*` lives in the instructions stream (`CompiledStaticCall::emit_to_interp_stub` uses `mov_metadata`).
I think it's a bad design if Metadata is replicated in an extra constant section on PPC64. I'll be glad to see this go away. There's already a JEP proposed which would remove inline caches (https://openjdk.java.net/jeps/8221828). But we shouldn't wait for that. We should check if we need to fix it and file a new issue if needed.
This PR doesn't depend on that because it only addresses narrow Oop and Klass constants in the instruction stream. Not uncompressed Method* in constant sections.

**Comment by reinrich** [comment]
> Thanks for reviewing and asking this interesting questions, Richard! Doesn't
> x86 have the same issue?  `metadata_Relocation::pd_fix_value` is empty on that
> platform as well and the `Method*` lives in the instructions stream
> (`CompiledStaticCall::emit_to_interp_stub` uses `mov_metadata`).

No, x86 doesn't have that issue. There the Method pointer is embedded in the
instruction stream very much as in an ordinary data structure.

The `Atomic::store` at
https://github.com/openjdk/jdk/blob/62a7f5d3236ab2248518a475b1d8b71cb4bf1313/src/hotspot/share/code/compiledMethod.cpp#L685
directly changes the Method* in the instruction stream. The fix-up is not
needed.

> I think it's a bad design if Metadata is replicated in an extra constant
> section on PPC64.

This might be for historic reasons. I think there used to be a dedicated
register for the TOC which had to be set in the prologue. With the "global TOC"
R29_TOC pointing to code cache start it should be possible to load directly from
the Metadata section. Then no additional fixup would be needed.

> I'll be glad to see this go away. There's already a JEP proposed which
> would remove inline caches (https://openjdk.java.net/jeps/8221828). But we
> shouldn't wait for that. We should check if we need to fix it and file a new
> issue if needed. This PR doesn't depend on that because it only addresses
> narrow Oop and Klass constants in the instruction stream. Not uncompressed
> Method* in constant sections.

I agree to handle it separately.

**Review by reinrich — APPROVED** [review]
Looks good to me.

Thanks, Richard.

**Comment by TheRealMDoerr** [comment]
Excellent! Thanks for checking and approving this one!
/integrate

**Pull request closed without merging**
