### PR TITLE
8258142: Simplify G1RedirtyCardsQueue

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to G1RedirtyCardsQueue to separate the local qset
from the queue. This simplifies the implementation, though requires clients
to deal with the local qset explicitly. This is an enabling step toward
desired simplifications of the PtrQueue hierarchy. This change also
simplifies the interaction between the local qset and the global qset.

Testing:
mach5 tier1-5

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258142](https://bugs.openjdk.java.net/browse/JDK-8258142): Simplify G1RedirtyCardsQueue

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 6a48914fc3c48294c55180886c99c309df556b58
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to 6a48914fc3c48294c55180886c99c309df556b58

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1755/head:pull/1755`
`$ git checkout pull/1755`

### CODE REVIEW

**Comment by kimbarrett** [comment]
/summary Separate local redirty qset from redirty queue.

**Review by tschatzl — APPROVED** [review]
Lgtm. Thanks.

**Review by walulyai — APPROVED** [review]
looks good

minor:
maybe maintain the postfix `_qset ` in the naming of `_rdclqs` as done for `_shared_qset` and `_local_qset`

**Comment by kimbarrett** [comment]
> minor:
> maybe maintain the postfix `_qset ` in the naming of `_rdclqs` as done for `_shared_qset` and `_local_qset`

Yeah, "rdclqs" is a little opaque.  Changing to rdc_local_qset.

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @walulyai for reviewing.

**Pull request closed without merging**
