### PR TITLE
8261846: [JVMCI] c2v_iterateFrames can get out of sync with the StackFrameStream

### PR DESCRIPTION
**Pull request by tkrodriguez**
c2v_iterateFrames mixes a StackFrameSteam and vframes and the vframe factory method can silently skip stub frames. The could leave the StackFrameStream out of sync with the vframe walk. This can cause the iteration fail in strange ways and assert in fastdebug builds.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261846](https://bugs.openjdk.java.net/browse/JDK-8261846): [JVMCI] c2v_iterateFrames can get out of sync with the StackFrameStream

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 45f83f121512b0012739a999fda99ede3f6731e1

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2594/head:pull/2594`
`$ git checkout pull/2594`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Update copyright year in vframe.hpp.
Otherwise good.

**Comment by dean-long** [comment]
Hi Tom.  This code could be simplified and made faster using vframeStream as the iterator and vframeStream:asJavaVFrame to get the vframe.  If you don't need the locals of every frame, then vframeStream::next is faster than vframe::sender.  See JDK-8214329.

**Comment by tkrodriguez** [comment]
@dean-long I think it would be possible to rewrite this to use vframeStream though it would still need to build vframes because of the introspection it does on compiled frames.  It would be a major rewrite though and in general this code is working just fine so I don't think I want to tackle that.

**Comment by dougxc** [comment]
Looks good to me.

**Comment by dean-long** [comment]
@tkrodriguez OK, I filed a separate RFE for my suggestion.

**Pull request closed without merging**
