### PR TITLE
8297384: Add IR tests for existing idealizations of arithmetic nodes

### PR DESCRIPTION
**Pull request by CptGit**
I noticed some idealizations have no associated IR tests so I included for them.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297384](https://bugs.openjdk.org/browse/JDK-8297384): Add IR tests for existing idealizations of arithmetic nodes

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to [c0931397](https://git.openjdk.org/jdk/pull/11049/files/c093139714df3507676799860be2c3e7a087035a)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11049/head:pull/11049` \
`$ git checkout pull/11049`

Update a local copy of the PR: \
`$ git checkout pull/11049` \
`$ git pull https://git.openjdk.org/jdk pull/11049/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11049`

View PR using the GUI difftool: \
`$ git pr show -t 11049`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11049.diff">https://git.openjdk.org/jdk/pull/11049.diff</a>

</details>

### CODE REVIEW

**Comment by CptGit** [comment]
> Hi, do you need a JBS issue for this?

Hi, I do not have an OpenJDK account, so can you open one issue for me? Thanks!

**Comment by kelthuzadx** [comment]
Okay, I filed [JDK-8297384 Add IR tests for existing idealizations of arithmetic nodes](https://bugs.openjdk.org/browse/JDK-8297384) for this patch.

**Comment by CptGit** [comment]
> Okay, I filed [JDK-8297384 Add IR tests for existing idealizations of arithmetic nodes](https://bugs.openjdk.org/browse/JDK-8297384) for this patch.

Thanks a lot! I included the bug id in this PR. Could you please help review the PR if you get a chance, thanks!

**Review by chhagedorn — APPROVED** [review]
Nice additional tests! They look good.

**Comment by CptGit** [comment]
> Nice additional tests! They look good.

Thank you for reviewing. I noticed `RotateLeftNodeIntIdealizationTests.java` and `RotateLeftNodeLongIdealizationTests.java` failed on x86. Does this matter should we make sure they pass?

**Comment by CptGit** [comment]
> We should make sure to make them pass on x86 as well such that GHA is clean after the integration of this PR. I've had a quick look on the match rules and it seems that we only use `RotateLeft/Right` nodes on x86_64, aarch64 and riscv. We could restrict these tests to only run on these architectures with `@requires os.arch == "x86_64" | os.arch == "aarch64" | os.arch == "riscv64"`.

Thanks for your help! I have added the restrictions and the GHA should be clean now. I have a question though: where did you see the architectures where RotateLeft/Right nodes are used? so that I can know when the the same case happens again. Thanks.

**Comment by chhagedorn** [comment]
> > We should make sure to make them pass on x86 as well such that GHA is clean after the integration of this PR. I've had a quick look on the match rules and it seems that we only use `RotateLeft/Right` nodes on x86_64, aarch64 and riscv. We could restrict these tests to only run on these architectures with `@requires os.arch == "x86_64" | os.arch == "aarch64" | os.arch == "riscv64"`.
> 
> Thanks for your help! I have added the restrictions and the GHA should be clean now. I have a question though: where did you see the architectures where RotateLeft/Right nodes are used? so that I can know when the the same case happens again. Thanks.

Since `RotateLeft/Right` are not macro nodes or other intermediate nodes like `Opaque*` which go away during optimizations, we need to find a match rule for them in order to build the mach graph. I therefore just searched for `match\(.*Rotate` and only found rules in `aarch64.ad`, `x86_64.ad` and `riscv_b.ad` (in `x86.ad`, we only find rules for the vector rotate nodes `Rotate.*V`).

**Pull request closed without merging**
