### PR TITLE
8273512: Fix the copyright header of x86 macroAssembler files

### PR DESCRIPTION
**Pull request by sviswa7**
Fix the copyright header of x86 macroAssembler files to match others.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273512](https://bugs.openjdk.java.net/browse/JDK-8273512): Fix the copyright header of x86 macroAssembler files

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 4e7f94d70c88d71be95748c895eebc6a0b415f16
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5424/head:pull/5424` \
`$ git checkout pull/5424`

Update a local copy of the PR: \
`$ git checkout pull/5424` \
`$ git pull https://git.openjdk.java.net/jdk pull/5424/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5424`

View PR using the GUI difftool: \
`$ git pr show -t 5424`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5424.diff">https://git.openjdk.java.net/jdk/pull/5424.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — CHANGES_REQUESTED** [review]
Hi Sandhya,

Hotspot files do not have the "Classpath exception".

Thanks,
David

**Comment by sviswa7** [comment]
Thanks @dholmes-ora.  I have removed the classpath exception. Let me know if the patch looks good to you now.

**Review by dholmes-ora — APPROVED** [review]
Hi Sandhya,

Under the assumption that this is indeed the right way to apply Intel copyrights I can approve this PR.

Thanks,
David

**Review by TobiHartmann — CHANGES_REQUESTED** [review]
What about this one?
https://github.com/openjdk/jdk/blob/0417fcf13f7f2159499d325f2b3ace49d2643557/src/hotspot/cpu/aarch64/macroAssembler_aarch64_log.cpp#L2

Other files look good and consistent with the Intel copyright in `src/jdk.incubator.vector/linux/native/libsvml/*`.

**Comment by sviswa7** [comment]
Thanks a lot @TobiHartmann. I have corrected that line as well.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
