### PR TITLE
8284458: CodeHeapState::aggregate() leaks blob_name

### PR DESCRIPTION
**Pull request by zhengyu123**
Please review this small patch to fix a possible memory leak.

Test:
- [x] hotspot_serviceability

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284458](https://bugs.openjdk.java.net/browse/JDK-8284458): CodeHeapState::aggregate() leaks blob_name

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.java.net/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8132/head:pull/8132` \
`$ git checkout pull/8132`

Update a local copy of the PR: \
`$ git checkout pull/8132` \
`$ git pull https://git.openjdk.java.net/jdk pull/8132/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8132`

View PR using the GUI difftool: \
`$ git pr show -t 8132`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8132.diff">https://git.openjdk.java.net/jdk/pull/8132.diff</a>

</details>

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Looks good to me.
Good catch! Thanks for finding and fixing the leak.

**Comment by zhengyu123** [comment]
Thanks for the review, @RealLucy

**Review by lmesnik — APPROVED** [review]

**Comment by zhengyu123** [comment]
Thanks, @lmesnik

**Pull request closed without merging**
