### PR TITLE
JDK-8264517: C2: make MachCallNode::return_value_is_used() only available for x86

### PR DESCRIPTION
**Pull request by tobiasholenstein**
Added #ifndef _LP64 guard to the MachCallNode::return_value_is_used() method in src/hotspot/share/opto/machnode.* because it is only used for 32-bit x86.

Thanks, 
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264517](https://bugs.openjdk.java.net/browse/JDK-8264517): C2: make MachCallNode::return_value_is_used() only available for x86

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/5435/head:pull/5435` \
`$ git checkout pull/5435`

Update a local copy of the PR: \
`$ git checkout pull/5435` \
`$ git pull https://git.openjdk.java.net/jdk pull/5435/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5435`

View PR using the GUI difftool: \
`$ git pr show -t 5435`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/5435.diff">https://git.openjdk.java.net/jdk/pull/5435.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Pull request closed without merging**
