### PR TITLE
8312440: assert(cast != nullptr) failed: must have added a cast to pin the node

### PR DESCRIPTION
**Pull request by rwestrel**
The test has a loop nest with 2 loops. A node is sunk out of the inner
loop. A cast is created to pin the node out of loop. The logic added
by 8308103 looks for an existing cast with the same inputs. It finds
one and uses that one. That existing cast was created before the
current round of loop opts. Eventhough it has the right out of inner
loop (but in outer loop) control input, it was assigned a control out
of both loops (the control is legal, it just happens that no use keeps
the cast in the outer loop). Next, the same node is sunk out of the
outer loop. The logic for sinking nodes looks for an input in the
outer loop (otherwise why would the node be in the outer loop) and
find none even though there should be one. The assert fires. The
reason is that the cast input has control out of loop. The fix I
propose is to not use an existing cast if it doesn't have the expected
control.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312440](https://bugs.openjdk.org/browse/JDK-8312440): assert(cast != nullptr) failed: must have added a cast to pin the node (**Bug** - P3)

### Reviewers
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14999/head:pull/14999` \
`$ git checkout pull/14999`

Update a local copy of the PR: \
`$ git checkout pull/14999` \
`$ git pull https://git.openjdk.org/jdk.git pull/14999/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14999`

View PR using the GUI difftool: \
`$ git pr show -t 14999`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14999.diff">https://git.openjdk.org/jdk/pull/14999.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14999#issuecomment-1648036028)

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good to me.

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too. Testing passed.

**Comment by rwestrel** [comment]
@chhagedorn @vnkozlov @TobiHartmann thanks for the reviews

**Pull request closed without merging**
