### PR TITLE
8287567: AArch64: Implement post-call NOPs

### PR DESCRIPTION
**Pull request by theRealAph**
Post-call NOPs (introduced with Loom virtual threads) are not implemented in the AArch64 port. Given that these are a significant optimization on x86, we should have them on AArch64 too. 

I looked at a variety of possible instruction sequences, and ended up with `nop; movk zr, lo; movk zr, hi`. `movk` is typically one of the fastest AArch64 instructions, so it should be suitable. It's not possible to patch the `movk` instructions concurrently with this code executing, but as far as I can tell the offsets in post-call NOPs are only ever patched while the code is being installed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287567](https://bugs.openjdk.java.net/browse/JDK-8287567): AArch64: Implement post-call NOPs

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**)
 * [Rickard Bäckman](https://openjdk.java.net/census#rbackman) (@rickard - **Reviewer**)
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8955/head:pull/8955` \
`$ git checkout pull/8955`

Update a local copy of the PR: \
`$ git checkout pull/8955` \
`$ git pull https://git.openjdk.java.net/jdk pull/8955/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8955`

View PR using the GUI difftool: \
`$ git pr show -t 8955`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8955.diff">https://git.openjdk.java.net/jdk/pull/8955.diff</a>

</details>

### CODE REVIEW

**Comment by adinn** [comment]
@theRealAph Do you have any info on how much of a difference post call NOPs make to AArch64? Was there a benchmark used to justify their use in x86_64 that could tell us what the benefit is?

**Comment by pron** [comment]
The NOPs make a big difference for various stack walking operations, and while we did see some negative effects, they're probably very minor. However, because they're only generated in JDK 19 if preview is enabled, we can perform a deeper performance analysis later.

**Comment by dean-long** [comment]
Is there any advantage to having the first instruction be "nop" instead of a branch that skips over the movks? 
```
b done
movk zr, lo
movk zr, hi
done:
```
 I was going to suggest:
```
 b done
 (raw data)
 done:
```
but then it might be hard for NativePostCallNop::check() to prevent false positives.

**Comment by rickard** [comment]
> Is there any advantage to having the first instruction be "nop" instead of a branch that skips over the movks?
> 
> ```
> b done
> movk zr, lo
> movk zr, hi
> done:
> ```
> 
> I was going to suggest:
> 
> ```
>  b done
>  (raw data)
>  done:
> ```
> 
> but then it might be hard for NativePostCallNop::check() to prevent false positives.

The NOP is required for deoptimization.

**Comment by dean-long** [comment]
> The NOP is required for deoptimization.

I could be wrong, but I thought aarch64 allowed undefined instructions to be patched on top of branch instructions too.

**Comment by theRealAph** [comment]
> > The NOP is required for deoptimization.
> 
> I could be wrong, but I thought aarch64 allowed undefined instructions to be patched on top of branch instructions too.

That's true.

**Comment by theRealAph** [comment]
@dean-long , are you happy with that explanation?

**Comment by theRealAph** [comment]
> > @dean-long , are you happy with that explanation?
> 
> Yes, and thanks for the interesting performance data.

It probably makes no difference, to be honest. I'm just a bit more confident right now to match an instruction that I am 100% certain never gets emitted by the compiler.

> I had an ulterior motive for my question. I was hoping there would be a platform-independent pattern that new ports could use initially, then optimize later. I think the
> 
> ```
>  b done
>  (raw data)
>  done:
> ```
> 
> pattern will work as long as call sites without a post-call NOP disambiguate by using a regular NOP. Then NativePostCallNop::check() will only see either a NOP or a branch.

True, although you'd have to find them all.

We could perhaps argue that  JMP *+ 2 (or however the offset works out) will never be emitted by a compiler, and I think it won't be with current C1 and C2, but it feels rather icky to me.

**Pull request closed without merging**
