### PR TITLE
8280543: Update the "java" and "jcmd" tool specification for CDS

### PR DESCRIPTION
**Pull request by iklam**
The discussion of CDS in the man pages need to be cleaned up and updated to match the latest functionalities and intended usage. 

For java.md:

- Reorganized the flow of the doc: Overview -> How to use -> How to create -> Restrictions and notes. I think this will be easier to read.
- Added information about `jcmd VM.cds static_dump|dynamic_dump`
- Removed a few sections that are no longer relevant or are uncommon usage (config files, sharing across two different apps)
- Removed discussion of uncommon error conditions (such as array classes)
- Removed detailed error messages. I think a simple note like "unsupported" will be good enough for readers of the man page.
- Removed discussion of different version of JDK (these should have been in release note)

For jcmd.md:

- Added some more details about default file name and output directory.

For ease of reviewing, please see the pre-rendered HTML pages:

http://cr.openjdk.java.net/~iklam/jdk19/8280543-update-java-and-jcmd-manpage-for-cds2/specs/man/

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280543](https://bugs.openjdk.java.net/browse/JDK-8280543): Update the "java" and "jcmd" tool specification for CDS

### Reviewers
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**) ⚠️ Review applies to edb4215595eca874b913fa2c2da2033519bc0d05
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**) ⚠️ Review applies to edb4215595eca874b913fa2c2da2033519bc0d05
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**) ⚠️ Review applies to edb4215595eca874b913fa2c2da2033519bc0d05

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7255/head:pull/7255` \
`$ git checkout pull/7255`

Update a local copy of the PR: \
`$ git checkout pull/7255` \
`$ git pull https://git.openjdk.java.net/jdk pull/7255/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7255`

View PR using the GUI difftool: \
`$ git pr show -t 7255`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7255.diff">https://git.openjdk.java.net/jdk/pull/7255.diff</a>

</details>

### CODE REVIEW

**Review by hseigel — APPROVED** [review]
LGTM.  The copyright in jcmd.1 needs updating.
Thanks, Harold

**Review by sspitsyn — APPROVED** [review]
The jcmd update looks good.
Thanks,
Serguei

**Review by calvinccheung — APPROVED** [review]
LGTM

**Comment by iklam** [comment]
Thanks @hseigel @calvinccheung @sspitsyn for the review.
/integrate

**Pull request closed without merging**
