### PR TITLE
8315554: C1: Replace "cmp reg, 0" with "test reg, reg" on x86

### PR DESCRIPTION
**Pull request by shipilev**
Noticed this when looking at C1 profiling code. There are plenty of usages for `cmp reg, 0` in C1 x86 code, both in generic `LIR_Assembler::comp_op`, and in some profiling paths.

`test reg, reg` is a denser idiom for this comparison. The difference between `cmp` and `test` on x86 seems to be only with AF (aux carry flag). For ubiquitous int/pointer comparisons, this distinction is irrelevant. 

C2 already does this transformation in .ad match rules.

Code size improvements with `-Xcomp -XX:+CITime -XX:TieredStopAtLevel=... Hello`:

```
# Before 
 tier1: nmethod total size: 430104 bytes
 tier2: nmethod total size: 467336 bytes
 tier3: nmethod total size: 923384 bytes

# After
 tier1: nmethod total size: 427584 bytes (-0.59%)
 tier2: nmethod total size: 464352 bytes (-0.64%)
 tier3: nmethod total size: 918328 bytes (-0.55%)
```

Additional testing:
  - [x] Linux x86_64 `tier1 tier2 tier3` x (C1 level 1, 2, 3) x (Parallel, G1, Shenandoah)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315554](https://bugs.openjdk.org/browse/JDK-8315554): C1: Replace "cmp reg, 0" with "test reg, reg" on x86 (**Enhancement** - P4)

### Reviewers
 * [Igor Veresov](https://openjdk.org/census#iveresov) (@veresov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15543/head:pull/15543` \
`$ git checkout pull/15543`

Update a local copy of the PR: \
`$ git checkout pull/15543` \
`$ git pull https://git.openjdk.org/jdk.git pull/15543/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15543`

View PR using the GUI difftool: \
`$ git pr show -t 15543`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15543.diff">https://git.openjdk.org/jdk/pull/15543.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15543#issuecomment-1705628584)

### CODE REVIEW

**Review by veresov — APPROVED** [review]

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by shipilev** [comment]
Our tests here look fine. Mind if I ask @TobiHartmann, @chhagedorn or @veresov to give this one a spin in Oracle test CIs?

**Comment by chhagedorn** [comment]
Already done - results look good on Windows and Linux! We currently have quite a load for MacOS testing, so it will probably not finish in a timely manner. But I guess it's fine to not wait for that and move forward.

**Comment by shipilev** [comment]
All right then!

/integrate

**Pull request closed without merging**
