### PR TITLE
8320712: Rewrite BadFactoryTest in pure Java

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which rewrites the BadFactoryTest to pure Java/JUnit. The test is currently implemented using a mix of shell script and a Java main method. 

Reviewers may notice the following changes:

- The shell script file `BadFactoryTest.sh` has been retired and jtreg tags moved over to `BadFactoryTest.java`
- The main method has been replaced with a JUnit `@Test` method
- The service definition file used to be packaged into a jar file, now the source directory is instead directly added to the classpath using `@library /javax/script/JDK_8196959`
- The `@summary` tag was updated since the existing summary was slightly confusing
- To make jtreg happy, the SecurityManager-enabled invocation now runs with `-Djava.security.manager=allow` instead of just `-Djava.security.manager`
- A sanity check was added to verify that `ScriptEngineManager` can actually find and load `BadFactory`. Such a check would have detected the issue which inspired this rewrite, see  #16585.

Verified by running:

```
% make test TEST="test/jdk/javax/script/JDK_8196959"
  [..]
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/javax/script/JDK_8196959               1     1     0     0   
```

Note that the original issue JDK-8196959 is not available in JBS, so my understanding of what the original test does is based on code inspection.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320712](https://bugs.openjdk.org/browse/JDK-8320712): Rewrite BadFactoryTest in pure Java (**Enhancement** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Athijegannathan Sundararajan](https://openjdk.org/census#sundar) (@sundararajana - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/16830/head:pull/16830` \
`$ git checkout pull/16830`

Update a local copy of the PR: \
`$ git checkout pull/16830` \
`$ git pull https://git.openjdk.org/jdk.git pull/16830/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16830`

View PR using the GUI difftool: \
`$ git pr show -t 16830`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/16830.diff">https://git.openjdk.org/jdk/pull/16830.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/16830#issuecomment-1829921788)

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello Eirik, what's being proposed here looks good to me. It's good that this is being migrated from a shell based test to a java based test. So if you are interested in pursuing this further, please reopen the PR.

The only part that is unclear to me is the use of `@library /javax/script/JDK_8196959`. Does the test fail if that isn't added?

**Comment by eirbjo** [comment]
> The only part that is unclear to me is the use of `@library /javax/script/JDK_8196959`. Does the test fail if that isn't added?

Thanks! I must have thought this was required to put the service definition file on the classpath. But it isn't.

I have removed the `@library` tag and also merged with a more recent master.

**Review by jaikiran — APPROVED** [review]
Thank you for the update. This test-only change looks OK to me.

Hello Sundar @sundararajana, given your past work on this test, do you have any thoughts on this change?

**Comment by eirbjo** [comment]
> Hello Sundar @sundararajana, given your past work on this test, do you have any thoughts on this change?

@jaikiran We have not heard back from @sundararajana in the last week. It would be nice to see this low-risk change integrated. 

I'm sure we can respond to any post-integration feedback with a follow-up PR. Do you agree?

**Review by sundararajana — APPROVED** [review]
LGTM

**Comment by jaikiran** [comment]
Hello Eirik @eirbjo, please give me a few more hours. I just now noticed that this test resides in tier2, so github actions job doesn't cover it. I'll trigger a CI run and once it's done successfully, you can go ahead and integrate this.

**Comment by eirbjo** [comment]
> Hello Eirik @eirbjo, please give me a few more hours. I just now noticed that this test resides in tier2, so github actions job doesn't cover it. I'll trigger a CI run and once it's done successfully, you can go ahead and integrate this.

Whoops, I just integrated after the approval from @sundararajana, seconds before this comment.

What is the best action here, just have a rollback PR ready in case of failures?

**Comment by jaikiran** [comment]
> 
> Whoops, I just integrated after the approval from @sundararajana, seconds before this comment.

That's alright. 

> 
> What is the best action here, just have a rollback PR ready in case of failures?

Typically when such failures happen, depending on the noise it creates in the CI, the change is either backed out https://openjdk.org/guide/#backing-out-a-change or a JBS issue is created to fix the issue, leaving the original change around. We don't need to do anything for now. I'll keep a watch on the test run.

**Pull request closed without merging**
