### PR TITLE
8299437: Make InetSocketAddressHolder shallowly immutable

### PR DESCRIPTION
**Pull request by minborg**
This PR proposes to make the class `java.net.InetSocketAddress.InetSocketAddressHolder` shallowly immutable

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299437](https://bugs.openjdk.org/browse/JDK-8299437): Make InetSocketAddressHolder shallowly immutable

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - Committer)
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11809/head:pull/11809` \
`$ git checkout pull/11809`

Update a local copy of the PR: \
`$ git checkout pull/11809` \
`$ git pull https://git.openjdk.org/jdk pull/11809/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11809`

View PR using the GUI difftool: \
`$ git pr show -t 11809`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11809.diff">https://git.openjdk.org/jdk/pull/11809.diff</a>

</details>

### CODE REVIEW

**Review by djelinski — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]
Looks fine to me.

**Review by AlanBateman — APPROVED** [review]
Well spotted, I don't know why these fields weren't final from the start.

**Pull request closed without merging**
