### PR TITLE
8256831: MIPS Zero builds fail with undefined __atomic_compare_exchange_8

### PR DESCRIPTION
**Pull request by shipilev**
If you try to build `linux-mipsel-zero-fastdebug`, this happens:

```
/home/shade/jdk/build/linux-mipsel-zero-fastdebug/hotspot/variant-zero/libjvm/objs/jvmtiRedefineClasses.o: In function `unsigned long long Atomic::PlatformCmpxchg<8u>::operator()<unsigned long long>(unsigned long long volatile*, unsigned long long, unsigned long long, atomic_memory_order) const':
/home/shade/jdk/src/hotspot/os_cpu/linux_zero/atomic_linux_zero.hpp:130: undefined reference to `__atomic_compare_exchange_8'
/home/shade/jdk/src/hotspot/os_cpu/linux_zero/atomic_linux_zero.hpp:130: undefined reference to `__atomic_compare_exchange_8'
/home/shade/jdk/src/hotspot/os_cpu/linux_zero/atomic_linux_zero.hpp:130: undefined reference to `__atomic_compare_exchange_8'
/home/shade/jdk/src/hotspot/os_cpu/linux_zero/atomic_linux_zero.hpp:130: undefined reference to `__atomic_compare_exchange_8'
```

I think it relates to [JDK-8253970](https://bugs.openjdk.java.net/browse/JDK-8253970) that introduced `atomic_compare_exchange` on those paths, but maybe the issue exists for longer. 

Various other reports for build failures like this suggest the binary should link with `libatomic`. GCC's `libatomic` is the library that provides runtime support for atomics not supported in hardware, which seems to include 8-byte CAS for MIPS, but not any other OpenJDK platform.

The alternative would be to massage the otherwise generic Zero code to unimplement the 8-byte CAS.

Attention @DamonFool, who must be running into this problem for their MIPS builds?

Testing:
 - [x] Linux mipsel Zero fastdebug build (together with JDK-8256829 fix)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ❌ (1/1 failed) | ❌ (1/1 failed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux arm (build hotspot no-pch)](https://github.com/shipilev/jdk/runs/1444991540)
- [Linux ppc64le (build hotspot no-pch)](https://github.com/shipilev/jdk/runs/1444991613)
- [Linux x86 (build debug)](https://github.com/shipilev/jdk/runs/1444773970)
- [Linux x86 (build release)](https://github.com/shipilev/jdk/runs/1444773951)

### Issue
 * [JDK-8256831](https://bugs.openjdk.java.net/browse/JDK-8256831): MIPS Zero builds fail with undefined __atomic_compare_exchange_8

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1375/head:pull/1375`
`$ git checkout pull/1375`

### CODE REVIEW

**Comment by DamonFool** [comment]
Thanks @shipilev for fixing it.

I don't have a mips machine at hand.
Maybe, people from Loongson can verify this fix.  @theaoqi , @xiangzhai
Thanks.

**Review by magicus — CHANGES_REQUESTED** [review]
This is incorrect. The `-l` prefix indicates a library to link with. As such, it belongs to LIBS, not LDFLAGS. 

I'm not sure if we still have a global LIBS variable that is added to all compile lines. We used to have since Solaris Studio required `-lc` for every non-trivial file, but it might have been purged with the Solaris platform. 

Otherwise this looks like something that belong in LIBJVM LIBS.

**Comment by shipilev** [comment]
> Otherwise this looks like something that belong in LIBJVM LIBS. In fact, if it is _only_ needed for the hotspot build, it is really where it belong. And even if it's needed in an additional library or two, it should be added on those places. Only if like more or less all libraries require this should it be added as a global flag.

So, would adding to `BASIC_JVM_LIBS` at `LIB_SETUP_LIBRARIES` step in `make/autoconf/libraries.m4` be a good place then?

**Comment by magicus** [comment]
@shipilev Looks like you found the place! :-)

But make sure to build all the JDK libraries as well, to see if it is needed by elsewhere as well.

**Comment by glaubitz** [comment]
As a heads-up. I have a working Loongson 2k board at home now (mips64el). So, in case something needs to be tested natively on MIPS, let me know.

**Comment by shipilev** [comment]
> So, would adding to `BASIC_JVM_LIBS` at `LIB_SETUP_LIBRARIES` step in `make/autoconf/libraries.m4` be a good place then?

This seems to work. It would seem only JVM is needed to be built with `-latomic`, which makes sense, as the problematic use is in VM code).

**Comment by shipilev** [comment]
> As a heads-up. I have a working Loongson 2k board at home now (mips64el). So, in case something needs to be tested natively on MIPS, let me know.

Oh, cool! Can it build `mipsel`, not `mips64el`? If so, please try to compile `linux-mipsel-zero-fastdebug` there?

**Review by magicus — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks, I'll wait for either of @glaubitz, @theaoqi or @xiangzhai to confirm this fixes the native `mipsel` builds for them, and then integrate.

**Comment by theaoqi** [comment]
The native build of linux-mipsel-zero-release passed. I only have mips64el and 64-bit OS, so I tested the patch by using a mipsel docker image.

Some messages during the build:
```
/usr/bin/objcopy: /home/aoqi/work/openjdk/jdk/build/linux-mipsel-zero-release/support/modules_libs/java.prefs/libprefs.debuginfo: section `.note.gnu.build-id' can't be allocated in segment 0
LOAD: .MIPS.abiflags .reginfo .note.gnu.build-id .dynamic .hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .init .text .MIPS.stubs .fini .eh_frame
```
However, I think the native build issue has been solved.

**Comment by shipilev** [comment]
Thanks for testing!

/integrate

**Pull request closed without merging**
