### PR TITLE
8223347: Integration of Vector API (Incubator)

### PR DESCRIPTION
**Pull request by PaulSandoz**
This pull request is for integration of the Vector API. It was previously reviewed under conditions when mercurial was used for the source code control system. Review threads can be found here (searching for issue number 8223347 in the title):

https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-April/thread.html
https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-May/thread.html
https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-July/thread.html

If mercurial was still being used the code would be pushed directly, once the CSR is approved. However, in this case a pull request is required and needs explicit reviewer approval. Between the final review and this pull request no code has changed, except for that related to merging.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8223347](https://bugs.openjdk.java.net/browse/JDK-8223347): Integration of Vector API (Incubator)

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to f2a45af82537d6e442c678989e3f75006f8f59c0
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**) ⚠️ Review applies to f2a45af82537d6e442c678989e3f75006f8f59c0
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to f2a45af82537d6e442c678989e3f75006f8f59c0
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to f2a45af82537d6e442c678989e3f75006f8f59c0
 * forax - no project role ⚠️ Added manually
 * briangoetz - **Reviewer** ⚠️ Added manually
 * aph - **Reviewer** ⚠️ Added manually
 * epavlova - Committer ⚠️ Added manually
 * coleenp - **Reviewer** ⚠️ Added manually

### Contributors
 * Vivek Deshpande `<vdeshpande@openjdk.org>`
 * Qi Feng `<qfeng@openjdk.org>`
 * Ian Graves `<igraves@openjdk.org>`
 * Jean-Philippe Halimi `<jphalimi@openjdk.org>`
 * Vladimir Ivanov `<vlivanov@openjdk.org>`
 * Ningsheng Jian `<njian@openjdk.org>`
 * Razvan Lupusoru `<rlupusoru@openjdk.org>`
 * Smita Kamath `<svkamath@openjdk.org>`
 * Rahul Kandu `<rkandu@openjdk.org>`
 * Kishor Kharbas `<kkharbas@openjdk.org>`
 * Eric Liu `<Eric.Liu2@arm.com>`
 * Aaloan Miftah `<someusername3@gmail.com>`
 * John R Rose `<jrose@openjdk.org>`
 * Shravya Rukmannagari `<srukmannagar@openjdk.org>`
 * Paul Sandoz `<psandoz@openjdk.org>`
 * Sandhya Viswanathan `<sviswanathan@openjdk.org>`
 * Lauren Walkowski `<lauren.walkowski@arm.com>`
 * Yang Zang `<Yang.Zhang@arm.com>`
 * Joshua Zhu `<jzhu@openjdk.org>`
 * Wang Zhuo `<wzhuo@openjdk.org>`
 * Jatin Bhateja `<jbhateja@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/367/head:pull/367`
`$ git checkout pull/367`

### CODE REVIEW

**Comment by PaulSandoz** [comment]
/review credit briangoetz, aph, chegar, erikj, kvn, epavlova, coleenp

**Comment by PaulSandoz** [comment]
/reviewer credit briangoetz, aph, chegar, erikj, kvn, epavlova, coleenp

**Comment by PaulSandoz** [comment]
/contributor add  jbhateja
/contributor add  vdeshpande
/contributor add  qfeng
/contributor add  igraves
/contributor add  jphalimi
/contributor add  vlivanov
/contributor add  njian
/contributor add  rlupusoru
/contributor add  svkamath
/contributor add  rkandu
/contributor add  kkharbas
/contributor add  Eric Liu <Eric.Liu2@arm.com>
/contributor add  Aaloan Miftah <someusername3@gmail.com>
/contributor add  jrose
/contributor add  srukmannagar
/contributor add  psandoz
/contributor add  sviswanathan
/contributor add  Lauren Walkowski <lauren.walkowski@arm.com>
/contributor add  Yang Zang <Yang.Zhang@arm.com>
/contributor add  jzhu
/contributor add  wzhuo

**Review by erikj79 — COMMENTED** [review]
Build changes look ok.

**Comment by DamonFool** [comment]
Hi @PaulSandoz , 

This integration seems to miss https://github.com/openjdk/panama-vector/pull/1, which had fixed crashes on AVX512 machines.

Thanks.

**Comment by PaulSandoz** [comment]
@DamonFool we can follow up later for that fix (and others in `vectorIntrinsics`), after this PR integrates. I don't want to perturb the code that has already been reviewed, which requires yet more additional review.

**Comment by DamonFool** [comment]
Hi @PaulSandoz ,

I think it would be better to integrate it [1] in this MR.

I have tested this MR on our AVX512 machines and it still crashes.
Also, for the sake of maintenance, it seems NOT a good idea to push a problematic commit into the jdk main-line repo. 

As for the review process, I don't think it's a problem since the fix [1] is clear and small enough.

What do you think?

Thanks.

[1] https://github.com/openjdk/panama-vector/commit/1af35c357066743935bd3f48ce3610a41761f89a

**Comment by PaulSandoz** [comment]
@DamonFool I appreciate your efforts on this but i want to hold back on that issue and follow up very quickly after integration of this PR. This change has been through an extremely long and arduous review process, and i want to stick to what was reviewed and not ask reviewers to go through further cycles on what overall is a very large change.
Unfortunately this change is in a holding pattern waiting for the CSR to be approved thereby increasing the window where we might find further issues (that if we had already integrated may have be dealt with separately perhaps in a less timely fashion with respect to that integration).
Unless an issue is extremely severe I think we should queue them up in `panama-vector/vectorIntrinsics` (there is at least one more for ARM SVE that is queued up). Since the issue you describe effects one instruction, for one type, on AVX512, its impact is limited and will be mitigated by a quick follow up.

**Comment by DamonFool** [comment]
Okay.
I can understand it.

Vector API is very valuable to us.
Hope the follow-ups can be integrated as soon as possible.
And thank you all for your great work.

Best regards,
Jie

**Review by ChrisHegarty — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
Good

**Review by jddarcy — APPROVED** [review]

**Review by erikj79 — APPROVED** [review]
Build changes look good.

**Comment by katyapav** [comment]
There are several gc tests crashed in panama-vector tier3 testing which seems are not observed in openjdk repo.
The crashes look like:
#  assert(oopDesc::is_oop(obj)) failed: not an oop: 0xfffffffffffffff1
#
# JRE version: Java(TM) SE Runtime Environment (16.0+3) (fastdebug build 16-panama+3-216)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 16-panama+3-216, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xd8ef94]  HandleArea::allocate_handle(oop)+0x144

and the issue is actually tracked by JDK-8233199.

This issue needs to be at least analyzed before integrating Vector API.

**Comment by sviswa7** [comment]
@katyapav Is the failure observed on vector-unstable branch of panama-vector?  
The code in this pull request is from vector-unstable branch.
The bug report https://bugs.openjdk.java.net/browse/JDK-8233199 refers to repo-valhalla and not panama-vector:vector-unstable.
@PaulSandoz is doing final testing of the pull request today before integration tomorrow hopefully.

**Comment by katyapav** [comment]
@sviswa7 you are right, the failure is observed on vector-unstable branch of panama-vector.
I referred to JDK-8233199 because it seems both panama-vector and valhalla-repo have the same issue/crash.
@PaulSandoz also mentioned that panama-vector was not in sync with master and this is perhaps the issue is in vector-unstable. He said that he tested the PR separately and didn't observe this issue in the PR.

**Pull request closed without merging**
