### PR TITLE
8178966: Don't swallow early bootstrap exceptions in Boolean.getBoolean, Integer.getInteger and Long.getLong

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which removes exceptional control flow in `Boolean::getBoolean`, `Integer::getInteger` and `Long::getLong`.

These methods are catching `IllegalArgumentException` and `NullPointerException`, thrown by `System::getProperty` via `System::checkKey`. This PR replaces the exceptional control flow with explicit checks that the system property name is non-null and non-empty before calling into `System::getProperty`.

As JDK-8178966 points out, there is a possibility that System.getProperty could throw one of NPE and IAE for other reasons than the name being null or empty. This risk is reduced now that custom security managers cannot interfere. Adding to that, if such exceptions are thrown today, they are masked by these methods catching and swallowing them by returning false or default values. It's better to expose such  bugs if they exist.

GHA results pending. Local tier2 ran successfully.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8178966](https://bugs.openjdk.org/browse/JDK-8178966): Don't swallow early bootstrap exceptions in Boolean.getBoolean, Integer.getInteger and Long.getLong (**Bug** - P4)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Contributors
 * Peter Levart `<plevart@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22183/head:pull/22183` \
`$ git checkout pull/22183`

Update a local copy of the PR: \
`$ git checkout pull/22183` \
`$ git pull https://git.openjdk.org/jdk.git pull/22183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22183`

View PR using the GUI difftool: \
`$ git pr show -t 22183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22183.diff">https://git.openjdk.org/jdk/pull/22183.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22183#issuecomment-2481540243)
</details>

### CODE REVIEW

**Review by jaikiran — APPROVED** [review]
Hello Eirik, this looks reasonable to me. Is this something that you want to add Peter as a contributor to, given his original proposal in the issue?

I can't think of any reason not to do this change, but it would be good to have one more review for this one. So please wait for one before integrating.

**Comment by eirbjo** [comment]
> Is this something that you want to add Peter as a contributor to, given his original proposal in the issue?

Thanks! Yes indeed, the JBS even included a patch with a suggsted change. Not sure why it was never integratd. 

> I can't think of any reason not to do this change, but it would be good to have one more review for this one. 

Yes, setting reviewers to 2 for this one :-)

**Review by RogerRiggs — CHANGES_REQUESTED** [review]
Circumventing and duplicating the checks in System.getProperty isn't good coding technique and is not necessary for performance improvement or code size.

**Comment by eirbjo** [comment]
> Circumventing and duplicating the checks in System.getProperty isn't good coding technique and is not necessary for performance improvement or code size.

My understanding of JDK-8178966 is that the motivation was correctness rather than performance. 

`Boolean::getBoolean` and friends are not specified to throw `IAE` or `NPE`, but to return false 'if the specified name is empty or {@code null}'. So the implementation must either check for null and emptiness, or it must catch the exceptions and hope they came from `System::checkKey` and nothing else.

I'm not sure what your alternative solution is here? Drop the PR / issue?

We can't simply drop the null and emptiness checks, since that could throw unspecified IAE/NPE.

**Review by RogerRiggs — APPROVED** [review]
ok, I withdraw my concern.  
The spec for the methods is explicit about the null and empty checks; as is the suggested fix.

**Pull request closed without merging**
