### PR TITLE
8331608: Consolidate EncodeGCModeConcurrentFrameClosure and TransformStackChunkClosure

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

After [JDK-8296875](https://bugs.openjdk.org/browse/JDK-8296875), the classes `EncodeGCModeConcurrentFrameClosure` and `TransformStackChunkClosure` almost have the same code. This patch consolidates them into one.

The tests `make test-hotspot_loom` and `make test-hotspot_gc` passed locally (linux & x64). Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331608](https://bugs.openjdk.org/browse/JDK-8331608): Consolidate EncodeGCModeConcurrentFrameClosure and TransformStackChunkClosure (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19084/head:pull/19084` \
`$ git checkout pull/19084`

Update a local copy of the PR: \
`$ git checkout pull/19084` \
`$ git pull https://git.openjdk.org/jdk.git pull/19084/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19084`

View PR using the GUI difftool: \
`$ git pr show -t 19084`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19084.diff">https://git.openjdk.org/jdk/pull/19084.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19084#issuecomment-2092878720)

### CODE REVIEW

**Review by stefank — CHANGES_REQUESTED** [review]
There doesn't seem to be a need to place the `derived_cl` closures in the callers. Could you keep it within `do_frame` as we used to do in `TransformStackChunkClosure`?

**Comment by lgxbslgx** [comment]
> There doesn't seem to be a need to place the `derived_cl` closures in the callers. Could you keep it within `do_frame` as we used to do in `TransformStackChunkClosure`?

If moving it into `do_frame`, everytime the `do_frame` is invoked, we need to construct a `RelativizeClosure` object. Will it cost more running time?

**Comment by stefank** [comment]
> > There doesn't seem to be a need to place the `derived_cl` closures in the callers. Could you keep it within `do_frame` as we used to do in `TransformStackChunkClosure`?
> 
> If moving it into `do_frame`, everytime the `do_frame` is invoked, we need to construct a `RelativizeClosure` object. Will it cost more running time?

I don't think you need to worry about that. It could have been worth thinking about if there was a large state that needed to be set up for every frame, but that's not the case here. The compiler will likely handle this well. If you are still not convinced I think you could disassemble the code with and without the suggestion and compare the two.

**Comment by lgxbslgx** [comment]
> I don't think you need to worry about that. It could have been worth thinking about if there was a large state that needed to be set up for every frame, but that's not the case here. The compiler will likely handle this well. If you are still not convinced I think you could disassemble the code with and without the suggestion and compare the two.

OK. I updated the code just now.

**Comment by lgxbslgx** [comment]
Kindly ping for review.

**Pull request closed without merging**
