### PR TITLE
8008243: Zero: Implement fast bytecodes

### PR DESCRIPTION
**Pull request by shipilev**
This work improves Zero performance considerably, without complicating the interpreter all that much. This work is based on much earlier patch by @rkennke, then edited by @jerboaa, and finally polished by me here :)

SPECjvm benchmarks improve across the board, with lowest improvement on `Derby` (+6%) and largest on `Compress` (+50%). Given that Zero is used to implement the JVM on emerging platforms that are still rather slow themselves, it makes sense to make Zero quantifiably faster. Even 10% improvement means more than 2 hours a day worth of CPU time.

Additional testing:
 - [x] Linux x86_64 Zero fastdebug bootcycle-images
 - [x]  Linux x86_64 Zero fastdebug `tier1`
 - [x] Linux x86_64 Zero fastdebug fuzzer tests (no failures = no new behaviors introduced)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8008243](https://bugs.openjdk.java.net/browse/JDK-8008243): Zero: Implement fast bytecodes

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to da31a9d5978c43e98a7c1421732279a9606fcbd9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/1938/head:pull/1938` \
`$ git checkout pull/1938`

Update a local copy of the PR: \
`$ git checkout pull/1938` \
`$ git pull https://git.openjdk.java.net/jdk pull/1938/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1938`

View PR using the GUI difftool: \
`$ git pr show -t 1938`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/1938.diff">https://git.openjdk.java.net/jdk/pull/1938.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Hold on, bot, we are not done yet.

**Comment by shipilev** [comment]
Not now, bot.

**Comment by shipilev** [comment]
Not yet, bot.

**Comment by shipilev** [comment]
Not now, bot.

**Comment by shipilev** [comment]
Not now, bot. This is a draft PR.

**Comment by shipilev** [comment]
Not now, bot. This is a draft PR.

**Comment by shipilev** [comment]
This should wait for `tier1` stabilization for Zero. But otherwise it is still on track.

/open

**Comment by shipilev** [comment]
I realized that there are feature flags (`RewriteBytecodes`) that govern such translation. New patch implements that handling, thus giving us an escape hatch if the translation is incorrect. Since field accesses are hot and checking the flag within the interpreter slows it down measurably, I opted to specialize `BytecodeInterpreter` a bit more.

**Comment by shipilev** [comment]
> I realized that there are feature flags (`RewriteBytecodes`) that govern such translation. New patch implements that handling, thus giving us an escape hatch if the translation is incorrect. Since field accesses are hot and checking the flag within the interpreter slows it down measurably, I opted to specialize `BytecodeInterpreter` a bit more.

@coleenp, @rkennke -- can I ask you to take another look at this?

**Review by rkennke — APPROVED** [review]
Looks good to me! Thanks!

**Comment by shipilev** [comment]
Re-ran Fuzzer in both `-XX:+RewriteBytecodes` and `-XX:-RewriteBytecodes`, still looks fine.

/integrate

**Comment by DamonFool** [comment]
A regression was found here: https://github.com/openjdk/jdk/pull/6479
Please review.
Thanks.

**Pull request closed without merging**
