### PR TITLE
8272691: Fix HotSpot style guide terminology for "non-local variables"

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this fix to incorrect terminology used in one place.  The
correct terminology (per C++14 3.6.2) is "non-local variables".

As this is a HotSpot Style Guide change, it requires reviewers who are HotSpot
Group Members, though comments from others are welcome.

/label hotspot

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8272691](https://bugs.openjdk.java.net/browse/JDK-8272691): Fix HotSpot style guide terminology for "non-local variables"

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 8d37a1b3779f665ca55db786468bb45797f6411c
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 8d37a1b3779f665ca55db786468bb45797f6411c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7695/head:pull/7695` \
`$ git checkout pull/7695`

Update a local copy of the PR: \
`$ git checkout pull/7695` \
`$ git pull https://git.openjdk.java.net/jdk pull/7695/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7695`

View PR using the GUI difftool: \
`$ git pr show -t 7695`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7695.diff">https://git.openjdk.java.net/jdk/pull/7695.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up.

**Review by dholmes-ora — APPROVED** [review]
Looks good.

Thanks,

**Comment by kimbarrett** [comment]
Thanks @dcubed-ojdk and @dholmes-ora for reviews.

**Pull request closed without merging**
