### PR TITLE
JDK-8307006: ProblemList gtest/NMTGtest.java on aix

### PR DESCRIPTION
**Pull request by MBaesken**
gtest/NMTGtest.java on aix currently crashes on AIX, better problem list it for now.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307006](https://bugs.openjdk.org/browse/JDK-8307006): ProblemList gtest/NMTGtest.java on aix

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13693/head:pull/13693` \
`$ git checkout pull/13693`

Update a local copy of the PR: \
`$ git checkout pull/13693` \
`$ git pull https://git.openjdk.org/jdk.git pull/13693/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13693`

View PR using the GUI difftool: \
`$ git pr show -t 13693`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13693.diff">https://git.openjdk.org/jdk/pull/13693.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13693#issuecomment-1526049408)

### CODE REVIEW

**Comment by MBaesken** [comment]
Hi Martin, thanks for approving.

/integrate

**Comment by tstuefe** [comment]
Is there an issue open for the original problem? If yes, could you please link it to this issue?

**Comment by MBaesken** [comment]
> Is there an issue open for the original problem? If yes, could you please link it to this issue?

Yes this one is a subissue of 
https://bugs.openjdk.org/browse/JDK-8306561
which is the real bug.

**Comment by tstuefe** [comment]
> > Is there an issue open for the original problem? If yes, could you please link it to this issue?
> 
> Yes this one is a subissue of https://bugs.openjdk.org/browse/JDK-8306561 which is the real bug.

Ah ok missed that. Thanks!

**Pull request closed without merging**
