### PR TITLE
8263376: CTW (Shenandoah): assert(mems <= 1) failed: No node right after call if multiple mem projections

### PR DESCRIPTION
**Pull request by rwestrel**
This is another case of anti-dependence analysis being too conservative.

In TestBadRawMemoryAfterCall.test2(), test

if (i == 42) {

is split thru the Phi that merges values from the fallthru and
exception paths. As a consequence, control flow at the call is
roughly:
```
a.m() call
|         \       
fallthru  exception
|             |
if (i == 42)  |
|      \      |
|       Region1
\        /
  Region2
```
When anti-dependence analysis runs for the load after the call, it
starts from the memory state out of the call on the fallthru path. One
use is a memory Phi at Region2 (say Phi2). Another path leads to
Region1 at, say, Phi1.

When anti-dependence analysis then goes over Phis, it processes Phi2,
goes over the its inputs and finds that 2 are reachable: the one that
has a direct edge to the memory state on the fallthru path and the one
from Phi1. As a consequence, control for the load is set to be right
after the call, which is too conservative.

When following the memory edges, the code stops at Phi1. It doesn't
process uses of Phi1. Any anti-dependence that's needed between the
load and Phi1 is then taken into account when Phis are processed. When
inputs to Phi2 are processed, considering the Phi2->Phi1 is too
conservative. As mentioned above, anti-dependences for Phi1 are taken
into account separately. I think it's true for all Phi->Phi edges that
they can be safely ignored. That's what I propose as a fix.

/cc shenandoah,hotspot-compiler

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263376](https://bugs.openjdk.java.net/browse/JDK-8263376): CTW (Shenandoah): assert(mems <= 1) failed: No node right after call if multiple mem projections

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to a47fa7b72268ecbc43cd26a85dfdfd8fa53bbb32
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**) ⚠️ Review applies to a47fa7b72268ecbc43cd26a85dfdfd8fa53bbb32

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3006/head:pull/3006`
`$ git checkout pull/3006`

To update a local copy of the PR:
`$ git checkout pull/3006`
`$ git pull https://git.openjdk.java.net/jdk pull/3006/head`

### CODE REVIEW

**Comment by rwestrel** [comment]
Anyone for a review of this relatively simple change? Change is in shared code.

**Review by vnkozlov — APPROVED** [review]
Okay.

**Review by chhagedorn — APPROVED** [review]
You should also add the bug number to the test.

Otherwise, looks good to me.

**Comment by rwestrel** [comment]
> You should also add the bug number to the test.
 
done.

> Otherwise, looks good to me.

Thanks for the review.

**Comment by rwestrel** [comment]
> Okay.

thanks for the review

**Pull request closed without merging**
