### PR TITLE
8291266: RenderPerfTest: missing content while rendering some primitives

### PR DESCRIPTION
**Pull request by avu**
Do not cause redundant endEncoder calls with batch processing of drawing primitives

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291266](https://bugs.openjdk.org/browse/JDK-8291266): RenderPerfTest: missing content while rendering some primitives

### Reviewers
 * [Ajit Ghaisas](https://openjdk.org/census#aghaisas) (@aghaisas - Committer)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9756/head:pull/9756` \
`$ git checkout pull/9756`

Update a local copy of the PR: \
`$ git checkout pull/9756` \
`$ git pull https://git.openjdk.org/jdk pull/9756/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9756`

View PR using the GUI difftool: \
`$ git pr show -t 9756`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9756.diff">https://git.openjdk.org/jdk/pull/9756.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Is it possible to integrate DrawTest.java as a test case?

**Comment by avu** [comment]
Looks like the only way is to use Robot. The problem is not reproducible with VolatileImage. I'll try to come up with something reliable.

**Comment by prrace** [comment]
Does this only show up as a problem on certain configurations ?
I ran your original test on my 16" x64 macbook pro and I wasn't sure what it was trying to show ...

**Comment by avu** [comment]
The problem is only reproducible on M1 hardware (I've just double-checked that it's not reproducible on x64). The idea of the test is to trigger batch rendering introduced in [JDK-8288948](https://bugs.openjdk.org/browse/JDK-8288948)

**Review by aghaisas — APPROVED** [review]
Looks good to me!

**Review by prrace — APPROVED** [review]

**Pull request closed without merging**
