### PR TITLE
8294541 - java/io/BufferedInputStream/TransferTo.java fails with OOME

### PR DESCRIPTION
**Pull request by mkarg**
Fixes 8294541

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294541](https://bugs.openjdk.org/browse/JDK-8294541): java/io/BufferedInputStream/TransferTo.java fails with OOME

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10524/head:pull/10524` \
`$ git checkout pull/10524`

Update a local copy of the PR: \
`$ git checkout pull/10524` \
`$ git pull https://git.openjdk.org/jdk pull/10524/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10524`

View PR using the GUI difftool: \
`$ git pr show -t 10524`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10524.diff">https://git.openjdk.org/jdk/pull/10524.diff</a>

</details>

### CODE REVIEW

**Comment by bplb** [comment]
This patch still failed on macOS:
```
Seed from RandomFactory = 9174133304664648308L
test TransferTo.testNullPointerException(): success
test TransferTo.testStreamContents(): failure
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:132)
	at java.base/java.io.InputStream.transferTo(InputStream.java:791)
	at java.base/java.io.BufferedInputStream.implTransferTo(BufferedInputStream.java:611)
	at java.base/java.io.BufferedInputStream.transferTo(BufferedInputStream.java:595)
	at TransferTo.checkTransferredContents(TransferTo.java:198)
	at TransferTo.testStreamContents(TransferTo.java:133)
```
I wonder whether a `FileOutputStream` (open on a sparse file?) should be used instead of a `ByteArrayOutputStream` with heap memory cranked up?

**Comment by mkarg** [comment]
As the files are not zero'ed by intention (to detect differences), sparse won't help, so next you'd eventually run into quota trouble (IIRC we already had this a year ago). IMHO we should increase RAM a bit further (really, it is cheap these days), or reduce that size of the tested data itself.

**Comment by AlanBateman** [comment]
> As the files are not zero'ed by intention (to detect differences), sparse won't help, so next you'd eventually run into quota trouble (IIRC we already had this a year ago). IMHO we should increase RAM a bit further (really, it is cheap these days), or reduce that size of the tested data itself.

I also pasted an example into the bug where 1Gb isn't enough. If it requires too much then the test may have to be skipped on 32-bit builds.

**Comment by mkarg** [comment]
I increased `-Xmx` from 1G to 1.2G, and cannot reproduce the reported cases anymore. I gave it ten more random attempts which all passed, too.

**Comment by AlanBateman** [comment]
> I increased `-Xmx` from 1G to 1.2G, and cannot reproduce the reported cases anymore. I gave it ten more random attempts which all passed, too.

I did some testing with this value and it does seem be enough.  The alternative is to reduce MAX_SIZE_INCR.

**Review by AlanBateman — APPROVED** [review]

**Comment by mkarg** [comment]
Did a final test with `MIN_SIZE = 100_000_000` and it did pass. So I agree that it should be safe to /integrate now. Thanks, Alan! :-)

**Pull request closed without merging**
