### PR TITLE
8271128: InlineIntrinsics support for 32-bit ARM

### PR DESCRIPTION
**Pull request by mychris**
Hi,

please review this patch, which adds support for InlineIntrinsics to the 32-bit ARM port. The old aarch32 port had this intrinsic implemented and enabled by default.

Like on many other platforms, the 32-bit ARM port simply calls into the `SharedRuntime` to intrinsify the basic `java.lang.Math` methods. InlineIntrinsics is already implemented for C1 on 32-bit ARM, which does the same thing.

testing: hotspot tier1 on ARMv5TE (soft-float) and ARMv7-A (hard-float)

There is already the micro benchmark `test/micro/org/openjdk/bench/java/lang/MathBench.java` which I used. The soft-float benchmarks are not that meaningful, since I performed them in QEMU.

__hard-float__ `-Xint -XX:+InlineIntrinsics`

| Benchmark                     | (seed) |  Mode | Cnt |    Score |       Error |  Units |
| :---------------------------- | -----: | ----: | --: | -------: | ----------: | -----: |
| MathBench.absDouble           |      0 | thrpt |   5 | 1169.574 | +/- 133.694 | ops/ms |
| MathBench.cosDouble           |      0 | thrpt |   5 |  759.902 | +/- 573.852 | ops/ms |
| MathBench.expDouble           |      0 | thrpt |   5 |  854.753 | +/-  67.217 | ops/ms |
| MathBench.log10Double         |      0 | thrpt |   5 |  902.034 | +/-  22.413 | ops/ms |
| MathBench.logDouble           |      0 | thrpt |   5 |  895.470 | +/- 113.811 | ops/ms |
| MathBench.powDouble           |      0 | thrpt |   5 |  936.136 | +/-  40.661 | ops/ms |
| MathBench.sinDouble           |      0 | thrpt |   5 |  864.670 | +/-  68.329 | ops/ms |
| MathBench.sqrtDouble          |      0 | thrpt |   5 | 1082.589 | +/-  92.570 | ops/ms |
| MathBench.tanDouble           |      0 | thrpt |   5 |  853.715 | +/- 122.427 | ops/ms |

__hard-float__ `-Xint -XX:-InlineIntrinsics`

| Benchmark                     | (seed) |  Mode | Cnt |    Score |       Error |  Units |
| :---------------------------- | -----: | ----: | --: | -------: | ----------: | -----: |
| MathBench.absDouble           |      0 | thrpt |   5 |  450.907 | +/-  10.402 | ops/ms |
| MathBench.cosDouble           |      0 | thrpt |   5 |  592.242 | +/-  14.011 | ops/ms |
| MathBench.expDouble           |      0 | thrpt |   5 |  167.614 | +/-   7.530 | ops/ms |
| MathBench.log10Double         |      0 | thrpt |   5 |  572.099 | +/-  55.089 | ops/ms |
| MathBench.logDouble           |      0 | thrpt |   5 |  596.588 | +/-  24.976 | ops/ms |
| MathBench.powDouble           |      0 | thrpt |   5 |  212.673 | +/-   4.060 | ops/ms |
| MathBench.sinDouble           |      0 | thrpt |   5 |  584.873 | +/-  42.774 | ops/ms |
| MathBench.sqrtDouble          |      0 | thrpt |   5 |  514.690 | +/-  30.568 | ops/ms |
| MathBench.tanDouble           |      0 | thrpt |   5 |  566.586 | +/-  23.995 | ops/ms |

__soft-float__ `-Xint -XX:+InlineIntrinsics`

| Benchmark                     | (seed) |  Mode | Cnt |    Score |       Error |  Units |
| :---------------------------- | -----: | ----: | --: | -------: | ----------: | -----: |
| MathBench.absDouble           |      0 | thrpt |   5 |  279.575 | +/-  56.455 | ops/ms |
| MathBench.cosDouble           |      0 | thrpt |   5 |  137.005 | +/-  72.561 | ops/ms |
| MathBench.expDouble           |      0 | thrpt |   5 |  117.778 | +/-  30.186 | ops/ms |
| MathBench.log10Double         |      0 | thrpt |   5 |  107.957 | +/-  10.158 | ops/ms |
| MathBench.logDouble           |      0 | thrpt |   5 |  101.341 | +/-   3.914 | ops/ms |
| MathBench.powDouble           |      0 | thrpt |   5 |  222.220 | +/-   3.854 | ops/ms |
| MathBench.sinDouble           |      0 | thrpt |   5 |  112.715 | +/-   9.088 | ops/ms |
| MathBench.sqrtDouble          |      0 | thrpt |   5 |  119.341 | +/-  76.528 | ops/ms |
| MathBench.tanDouble           |      0 | thrpt |   5 |  105.224 | +/-  30.477 | ops/ms |

__soft-float__ `-Xint -XX:-InlineIntrinsics`

| Benchmark                     | (seed) |  Mode | Cnt |    Score |       Error |  Units |
| :---------------------------- | -----: | ----: | --: | -------: | ----------: | -----: |
| MathBench.absDouble           |      0 | thrpt |   5 |  173.150 | +/-  36.279 | ops/ms |
| MathBench.cosDouble           |      0 | thrpt |   5 |  129.774 | +/-   8.795 | ops/ms |
| MathBench.expDouble           |      0 | thrpt |   5 |   53.524 | +/-   1.679 | ops/ms |
| MathBench.log10Double         |      0 | thrpt |   5 |  132.503 | +/-   4.274 | ops/ms |
| MathBench.logDouble           |      0 | thrpt |   5 |  135.483 | +/-   1.150 | ops/ms |
| MathBench.powDouble           |      0 | thrpt |   5 |   54.266 | +/-   0.699 | ops/ms |
| MathBench.sinDouble           |      0 | thrpt |   5 |  105.636 | +/-   4.647 | ops/ms |
| MathBench.sqrtDouble          |      0 | thrpt |   5 |  204.550 | +/-   7.206 | ops/ms |
| MathBench.tanDouble           |      0 | thrpt |   5 |  101.072 | +/-   3.701 | ops/ms |

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271128](https://bugs.openjdk.java.net/browse/JDK-8271128): InlineIntrinsics support for 32-bit ARM

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to 3c20c980b870e94ac4958159ec0faae90c4fbc8b

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/4927/head:pull/4927` \
`$ git checkout pull/4927`

Update a local copy of the PR: \
`$ git checkout pull/4927` \
`$ git pull https://git.openjdk.java.net/jdk pull/4927/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4927`

View PR using the GUI difftool: \
`$ git pr show -t 4927`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/4927.diff">https://git.openjdk.java.net/jdk/pull/4927.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
This looks okay to me, but I think `hotspot-tier1` testing is inadequate for this. Please run at least full `tier1`, which should include JDK tests for `java.lang.Math`.

**Comment by mychris** [comment]
Sorry, I forgot to mention this.
I tested the java.lang.Math methods for which the new intrinsics are implemented manually, by comparing the results of the intrinsics with the results of the corresponding java.lang.StrictMath method. Since both, StrictMath and the intrinsics use the same algorithm on 32-bit ARM, it is possible to do that.
But I agree, doing some more testing doesn't hurt. I will start jdk tier1 as well and will report back as soon as they are done, will definitely take some time though.

**Comment by mychris** [comment]
`jdk:tier1` tests on soft-float and hard-float are good. `IeeeRecommendedTests` on soft-float has some issues, but this is because I don't use an external soft float library, but the glibc implementation for floating point arithmetic, which doesn't have the required precision. Probably one should pick up [JDK-8215902](https://bugs.openjdk.java.net/browse/JDK-8215902) again and fix this situation.

**Comment by shipilev** [comment]
> `jdk:tier1` tests on soft-float and hard-float are good. 

Thanks, we are good then.

> `IeeeRecommendedTests` on soft-float has some issues, but this is because I don't use an external soft float library, but the glibc implementation for floating point arithmetic, which doesn't have the required precision.

This is pre-existing, right? Meaning, it is not worse with this PR?

**Comment by mychris** [comment]
> > `IeeeRecommendedTests` on soft-float has some issues, but this is because I don't use an external soft float library, but the glibc implementation for floating point arithmetic, which doesn't have the required precision.
> 
> This is pre-existing, right? Meaning, it is not worse with this PR?

Yes, this PR doesn't change anything. The test case also uses the `Math` and `StrictMath` functions and the problem is identical for both implementations.

**Review by shipilev — APPROVED** [review]
Good to go then.

**Comment by mychris** [comment]
Thanks for the review Aleksey, very much appreciated.
/integrate

**Comment by shipilev** [comment]
Sorry for not catching this earlier, but I think `java_lang_math_abs` and `java_lang_math_sqrt` are not transcendental, so it is awkward to call `generate_transcendental_entry` for them? I think that's just a naming problem, maybe call it `generate_math_runtime_entry`? (If you fix this, maybe also pull from master to get clean GHA runs).

**Comment by mychris** [comment]
> Sorry for not catching this earlier, but I think `java_lang_math_abs` and `java_lang_math_sqrt` are not transcendental, so it is awkward to call `generate_transcendental_entry` for them? I think that's just a naming problem, maybe call it `generate_math_runtime_entry`? (If you fix this, maybe also pull from master to get clean GHA runs).

I chose that name because of the aarch64 implementation, which uses the same name (but doesn't generate calls for neither `abs`, nor `sqrt`). I renamed it to `generate_math_runtime_call`, since it only generates the call to the runtime function.

**Comment by shipilev** [comment]
> > Sorry for not catching this earlier, but I think `java_lang_math_abs` and `java_lang_math_sqrt` are not transcendental, so it is awkward to call `generate_transcendental_entry` for them? I think that's just a naming problem, maybe call it `generate_math_runtime_entry`? (If you fix this, maybe also pull from master to get clean GHA runs).
> 
> I chose that name because of the aarch64 implementation, which uses the same name (but doesn't generate calls for neither `abs`, nor `sqrt`). I renamed it to `generate_math_runtime_call`, since it only generates the call to the runtime function.

Thanks, that looks better. `transcendental_entry` local variable too?

**Comment by mychris** [comment]
> Thanks, that looks better. `transcendental_entry` local variable too?

Sorry, should have seen this myself.
Done.

**Review by shipilev — APPROVED** [review]
I'd prefer `use_runtime_function` to be called `use_runtime_call`, but this is fine as well. I can sponsor this for you.

**Comment by mychris** [comment]
> I'd prefer `use_runtime_function` to be called `use_runtime_call`
Done.

> I can sponsor this for you.
Thanks, I guess I have to integrate again?

/integrate

**Comment by shipilev** [comment]
Yup, I'll wait for GHA to clear the ARM build, and then sponsor.

**Comment by shipilev** [comment]
ARM builds are clean. 

/sponsor

**Pull request closed without merging**
