### PR TITLE
8286177: C2: "failed: non-reduction loop contains reduction nodes" assert failure

### PR DESCRIPTION
**Pull request by robcasloz**
[JDK-8279622](https://bugs.openjdk.java.net/browse/JDK-8279622) introduced an assertion in the SLP analysis verifying that the examined loop does not contain inconsistent reduction information. The assertion is placed at the beginning of the SLP analysis, and can fail even for loops that are not vectorizable by SLP (and hence without risk of being miscompiled). This is the case for the [reported issue](https://bugs.openjdk.java.net/browse/JDK-8286177) and for many other recent failures triggered by JavaFuzzer-generated test cases. This changeset postpones the assertion to the SLP output phase to ensure that it only fails when the program really risks being miscompiled.

Given that many transformations can invalidate reduction information (see for example the JBS reports for [JDK-8261147](https://bugs.openjdk.java.net/browse/JDK-8261147), [JDK-8279622](https://bugs.openjdk.java.net/browse/JDK-8279622), and [JDK-8286177](https://bugs.openjdk.java.net/browse/JDK-8286177)), a more fundamental fix would be to remove the possibility of inconsistent reduction information by construction, by running the reduction analysis on-demand. I have filed a [RFE](https://bugs.openjdk.java.net/browse/JDK-8287087) to explore this idea after JDK 19.

#### Testing

  - hs-tier1-5 (windows-x64, linux-x64, linux-aarch64, and macosx-x64; debug mode).
  - Tested that the assertion, in its new placement, would still have caught the bug reported in [JDK-8279622](https://bugs.openjdk.java.net/browse/JDK-8279622) in the original scenario.
  - Tested that the assertion, in its new placement, does not fail for 27 JavaFuzzer-generated test cases that trigger the assertion in its original placement.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286177](https://bugs.openjdk.java.net/browse/JDK-8286177): C2: "failed: non-reduction loop contains reduction nodes" assert failure

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8805/head:pull/8805` \
`$ git checkout pull/8805`

Update a local copy of the PR: \
`$ git checkout pull/8805` \
`$ git pull https://git.openjdk.java.net/jdk pull/8805/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8805`

View PR using the GUI difftool: \
`$ git pr show -t 8805`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8805.diff">https://git.openjdk.java.net/jdk/pull/8805.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
That looks reasonable to go with this lower-risk fix for JDK 19 since the assertion warns about a problem that has been around for quite some time. It makes sense to revisit this again later and propose a full fix in JDK 20 to avoid similar problems with wrongly marked reduction nodes in the future.

**Comment by robcasloz** [comment]
> That looks reasonable to go with this lower-risk fix for JDK 19 since the assertion warns about a problem that has been around for quite some time. It makes sense to revisit this again later and propose a full fix in JDK 20 to avoid similar problems with wrongly marked reduction nodes in the future.

Thanks for the review, Christian! I just filed a [RFE](https://bugs.openjdk.java.net/browse/JDK-8287087) for this.

**Review by vnkozlov — APPROVED** [review]
I agree with suggested change.

**Comment by robcasloz** [comment]
> I agree with suggested change.

Thanks for reviewing, Vladimir!

**Pull request closed without merging**
