### PR TITLE
8332740: [BACKOUT] JDK-8331081 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This reverts commit 2170e99cb49a4ef2086ecec7515a72d56148d0f2.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332740](https://bugs.openjdk.org/browse/JDK-8332740): [BACKOUT] JDK-8331081 'internal proprietary API' diagnostics if --system is configured to an earlier JDK version (**Bug** - P1)

### Reviewers
 * [Mikael Vidstedt](https://openjdk.org/census#mikael) (@vidmik - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19352/head:pull/19352` \
`$ git checkout pull/19352`

Update a local copy of the PR: \
`$ git checkout pull/19352` \
`$ git pull https://git.openjdk.org/jdk.git pull/19352/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19352`

View PR using the GUI difftool: \
`$ git pr show -t 19352`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19352.diff">https://git.openjdk.org/jdk/pull/19352.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19352#issuecomment-2125536128)

### CODE REVIEW

**Review by vidmik — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@vidmik - Thanks for the lightning fast review! I'm gonna hold off until I get a single
passed Tier1 build task with the [BACKOUT] that previously failed.

**Review by prrace — APPROVED** [review]

**Comment by prrace** [comment]
I got unlucky and just synced in this breakage to my local repo. It would be good to see it backed out.

**Review by lahodaj — APPROVED** [review]
Looks good. Sorry for the trouble.

**Comment by dcubed-ojdk** [comment]
@prrace  and @lahodaj - Thanks for the reviews.

macosx-aarch64-open-debug has passed so I am...

/integrate

**Pull request closed without merging**
