### PR TITLE
8302312: Make ParGCRareEvent_lock G1 specific

### PR DESCRIPTION
**Pull request by tschatzl**
Hi all,

please have a look at this renaming of ParGCRareEvent_lock to G1RareEvent_lock to align with it only being used in G1. Previously it had been used with CMS too, but that one's gone now.

Testing: local compilation, gha

Based on PR#12511

Thanks,
Thomas

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302312](https://bugs.openjdk.org/browse/JDK-8302312): Make ParGCRareEvent_lock G1 specific

### Reviewers
 * [Stefan Johansson](https://openjdk.org/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to [0631598e](https://git.openjdk.org/jdk/pull/12531/files/0631598e4748097663987a3455f38b3e25cdecbf)
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [0631598e](https://git.openjdk.org/jdk/pull/12531/files/0631598e4748097663987a3455f38b3e25cdecbf)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12531/head:pull/12531` \
`$ git checkout pull/12531`

Update a local copy of the PR: \
`$ git checkout pull/12531` \
`$ git pull https://git.openjdk.org/jdk pull/12531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12531`

View PR using the GUI difftool: \
`$ git pr show -t 12531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12531.diff">https://git.openjdk.org/jdk/pull/12531.diff</a>

</details>

### CODE REVIEW

**Review by kstefanj — APPROVED** [review]
Looks good and trivial.

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by tschatzl** [comment]
Thanks @kstefanj @kimbarrett for your reviews.

/integrate

**Pull request closed without merging**
