### PR TITLE
8293660: Fix frame::sender_for_compiled_frame frame size assert

### PR DESCRIPTION
**Pull request by shipilev**
The condition and assert messages are contradicting each other here:

```
frame frame::sender_for_compiled_frame(RegisterMap* map) const {
  ...
  assert(_cb->frame_size() >= 0, "must have non-zero frame size");
  intptr_t* sender_sp = unextended_sp() + _cb->frame_size();
```

I found this in x86_32 Loom port, where a entry generator bug caused zero-sized frames. I believe the assert message is correct, and the condition is not: sender SP should be different from (unextended) SP. In fact, if allowed to proceed, the tests can then fail the later assert, assuming `sp() == unextended_sp()`:

```
  assert(sender_sp != sp(), "must have changed");
```

This code predates OpenJDK history, and assert was copy-pasted in this form to many arches. 

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293660](https://bugs.openjdk.org/browse/JDK-8293660): Fix frame::sender_for_compiled_frame frame size assert

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to [be483145](https://git.openjdk.org/jdk/pull/10242/files/be48314555c862584d0b227286f273c65c9f4cc0)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10242/head:pull/10242` \
`$ git checkout pull/10242`

Update a local copy of the PR: \
`$ git checkout pull/10242` \
`$ git pull https://git.openjdk.org/jdk pull/10242/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10242`

View PR using the GUI difftool: \
`$ git pr show -t 10242`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10242.diff">https://git.openjdk.org/jdk/pull/10242.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]
This looks fine.  You could probably even use >= 2.  More correct would probably be >= metadata_words, but some ports are setting that value to 0, which will probably break things with loom.

There are also some places under hotspot/agent/src/share/classes that are doing the equivalent in Java:

  Assert.that(cb.getFrameSize() > 0, "CodeBlob must have non-zero frame size");

which would probably be low-risk to fix in this PR if you wanted.

**Comment by shipilev** [comment]
> This looks fine. You could probably even use >= 2. More correct would probably be >= metadata_words, 
> but some ports are setting that value to 0, which will probably break things with loom.

Yeah, I'd prefer to keep the most accepting form. It seems we really want to catch the zero case to guarantee stack walking progress.

> There are also some places under hotspot/agent/src/share/classes that are doing the equivalent in Java:
> Assert.that(cb.getFrameSize() > 0, "CodeBlob must have non-zero frame size");
> which would probably be low-risk to fix in this PR if you wanted.

Fixed those in new commit.

**Comment by shipilev** [comment]
Any other reviews?

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
