### PR TITLE
8286430: make test TEST="gtest:<sometag>" exits with error when it shouldn't

### PR DESCRIPTION
**Pull request by jerboaa**
`make test TEST="gtest:<sometag"` fails for me with google test version `1.10.0`. It expects `suites` to be present in the google test output whereas the OpenJDK build infra code expects `cases`. I'm not sure when/if that changed, but here is a proposed fix.

Thoughts?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8286430](https://bugs.openjdk.java.net/browse/JDK-8286430): make test TEST="gtest:<sometag>" exits with error when it shouldn't

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8605/head:pull/8605` \
`$ git checkout pull/8605`

Update a local copy of the PR: \
`$ git checkout pull/8605` \
`$ git pull https://git.openjdk.java.net/jdk pull/8605/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8605`

View PR using the GUI difftool: \
`$ git pr show -t 8605`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8605.diff">https://git.openjdk.java.net/jdk/pull/8605.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
Apparently gtest 1.8.1 uses `cases`. I've updated the patch to handle both: `suites` and `cases`. If somebody could test it with gtest 1.8.1 I'd appreciate it.

**Review by magicus — APPROVED** [review]

**Comment by jerboaa** [comment]
Thanks for the review, Magnus. I'll wait until tomorrow for integration.

**Comment by erikj79** [comment]
> Apparently gtest 1.8.1 uses `cases`. I've updated the patch to handle both: `suites` and `cases`. If somebody could test it with gtest 1.8.1 I'd appreciate it.

Verified that it works with 1.8.1, which does indeed use `cases`.

**Pull request closed without merging**
