### PR TITLE
8252545: runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryError.java timed out

### PR DESCRIPTION
**Pull request by hseigel**
Please review this change to fix JDK-8252545.  The fix uses -Xm128m to reduce the size of the heap, lessening the amount  of time needed to get an OutOfMemoryError exception.  The fix also simplifies things by including test TestHeapDumpOnOutOfMemoryErrorInMetaspace.java with this test.  (Hopefully, this won't increase the likelihood of timeouts.)

The fix was tested by running Mach5 tier 3 on Linux, Mac OS, and Windows, and running the test 100 times on Linxu x64 with the same JVM options that were used when the test last timed out: "-XX:MaxRAMPercentage=6 -XX:+UseParallelGC -XX:+UseNUMA".

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252545](https://bugs.openjdk.java.net/browse/JDK-8252545): runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryError.java timed out

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2226/head:pull/2226`
`$ git checkout pull/2226`

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Hi Harold,

looks good and makes sense. I even believe we could drop the Metaspace test to the default timeout; the longest runtimes I found since JDK-8212218 are about 12-15 seconds on our slow platforms (leave that up to you though).

**Review by coleenp — APPROVED** [review]
LGTM!

**Comment by hseigel** [comment]
Thanks Thomas and Coleen for the reviews!  I'll keep the Metaspace timeout as is for now to reduce the chances of that test timing out.

/integrate

**Comment by plummercj** [comment]
I think SQE prefers multiple @test sections rather than multiple @run commands. You might want to check with @lmesnik or @iignatev  on this.

**Comment by iignatev** [comment]
> I think SQE prefers multiple @test sections rather than multiple @run commands. You might want to check with @lmesnik or @iignatev on this.

That’s correct, if `@run` are independent, it’s preferable to split them into multiple test description sections, ie multiple blocks with `@test` as this allows greater control over their execution and test results are easier to interpret. 

Cheers,
— Igor

**Comment by hseigel** [comment]
Thanks Igor and Chris.  I create https://bugs.openjdk.java.net/browse/JDK-8260466 for the @run -> @test issue.

**Pull request closed without merging**
