### PR TITLE
8329774: Break long lines in jdk/src/jdk.hotspot.agent/doc /transported_core.html

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
I used "fold -sw 120" and removed trailing whitespaces.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8329774](https://bugs.openjdk.org/browse/JDK-8329774): Break long lines in jdk/src/jdk.hotspot.agent/doc /transported_core.html (**Enhancement** - P5)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18654/head:pull/18654` \
`$ git checkout pull/18654`

Update a local copy of the PR: \
`$ git checkout pull/18654` \
`$ git pull https://git.openjdk.org/jdk.git pull/18654/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18654`

View PR using the GUI difftool: \
`$ git pr show -t 18654`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18654.diff">https://git.openjdk.org/jdk/pull/18654.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18654#issuecomment-2039735429)

### CODE REVIEW

**Comment by plummercj** [comment]
I think using 100 would be more consistent with the rest of the file, although you may need to undo some long "code" lines after the initial reformat.

**Comment by LudwikJaniuk** [comment]
I followed your suggestion, and also fixed a typo.

**Review by kevinjwalls — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
