### PR TITLE
8304303: implement VirtualThread class notifyJvmti methods as C2 intrinsics

### PR DESCRIPTION
**Pull request by sspitsyn**
This is needed for future performance/scalability improvements in JVMTI support of virtual threads.
The update includes the following:

1. Refactored the `VirtualThread` native methods:
    `notifyJvmtiMountBegin`     and `notifyJvmtiMountEnd`      => `notifyJvmtiMount`
    `notifyJvmtiUnmountBegin` and `notifyJvmtiUnmountEnd` => `notifyJvmtiUnmount`
2. Still useful implementation of old native methods is moved from `jvm.cpp` to `jvmtiThreadState.cpp`:
     `JVM_VirtualThreadMountStart`       => `VTMS_mount_begin`
     `JVM_VirtualThreadMountEnd`         => `VTMS_mount_end`
     `JVM_VirtualThreadUnmountStart`  = > `VTMS_unmount_begin`
     `JVM_VirtualThreadUnmountEnd`    => `VTMS_mount_end`
3. Intrinsified the `VirtualThread` native methods: `notifyJvmtiMount`, `notifyJvmtiUnmount`, `notifyJvmtiHideFrames`.
4. Removed the`VirtualThread` static boolean state variable `notifyJvmtiEvents` and its support in `javaClasses`.
5. Added static boolean state variable `_VTMS_notify_jvmti_events` to the jvmtiVTMSTransitionDisabler class as a replacement of the `VirtualThread` `notifyJvmtiEvents` variable.

Implementing the same methods as C1 intrinsics can be needed in the future but is a low priority for now.  

Testing:
 - Ran mach5 tiers 1-6. No regressions were found.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304303](https://bugs.openjdk.org/browse/JDK-8304303): implement VirtualThread class notifyJvmti methods as C2 intrinsics

### Reviewers
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)
 * [Leonid Mesnik](https://openjdk.org/census#lmesnik) (@lmesnik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/13054/head:pull/13054` \
`$ git checkout pull/13054`

Update a local copy of the PR: \
`$ git checkout pull/13054` \
`$ git pull https://git.openjdk.org/jdk pull/13054/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13054`

View PR using the GUI difftool: \
`$ git pr show -t 13054`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13054.diff">https://git.openjdk.org/jdk/pull/13054.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
The most important case is when there is no JVMTI env. If I read the changes correctly, the overhead for park/continue changes from one volatile-read (notifyJvmtiEvents) to two plain-writes (JavaThread::_is_in_VTMS_transition).

If a JVMTI env has been created then there is no benefit for the moment as there is still a call into the runtime to interact with JvmtiVTMSTransitionDisabler. So I think you are saying that is for follow-on PRs.

**Review by lmesnik — APPROVED** [review]
I haven't reviewed C2 changes, all other changes look good to me.

**Comment by sspitsyn** [comment]
> The most important case is when there is no JVMTI env. If I read the changes correctly, the overhead for park/continue changes from one volatile-read (notifyJvmtiEvents) to two plain-writes (JavaThread::_is_in_VTMS_transition).
> 
> If a JVMTI env has been created then there is no benefit for the moment as there is still a call into the runtime to interact with JvmtiVTMSTransitionDisabler. So I think you are saying that is for follow-on PRs.
@AlanBateman Yes, your conclusion is correct.

**Comment by sspitsyn** [comment]
Thank you for review, Leonid!

**Pull request closed without merging**
