### PR TITLE
8301248: Less side effects in InstanceRefKlass::trace_reference_gc

### PR DESCRIPTION
**Pull request by fisk**
The InstanceRefKlass::trace_reference_gc function is called when using oop_iterate on a reference object. Since oop_iterate is a general iterator that can be used for anything, including verification code, it would be desirable for this code to not have subtle side effects. We currently apply load barriers which "fix" pointers in the heap. As a result, verification code that was meant to detect bugs, can end up fixing and hiding the bug. This CR aims to address this by limiting the logging to addresses, and not following them.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301248](https://bugs.openjdk.org/browse/JDK-8301248): Less side effects in InstanceRefKlass::trace_reference_gc

### Reviewers
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)

### Contributors
 * Stefan Karlsson `<stefank@openjdk.org>`
 * Axel Boldt-Christmas `<aboldtch@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12258/head:pull/12258` \
`$ git checkout pull/12258`

Update a local copy of the PR: \
`$ git checkout pull/12258` \
`$ git pull https://git.openjdk.org/jdk pull/12258/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12258`

View PR using the GUI difftool: \
`$ git pr show -t 12258`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12258.diff">https://git.openjdk.org/jdk/pull/12258.diff</a>

</details>

### CODE REVIEW

**Review by rkennke — APPROVED** [review]
Changes look reasonable to me. If I remember correctly, there have been issues with this code and Shenandoah in the past, but I don't quite remember what it was. Maybe it was the fact that barriers have been used there (because of ZGC?), and Shenandoah barriers did not like that? Not sure. Quite likely no longer an issue - at least I don't see how it could be -, but maybe run 'make test TEST=hotspot_gc_shenandoah' to be extra sure?

**Review by stefank — APPROVED** [review]

**Comment by fisk** [comment]
Thanks for the review @rkennke and @stefank! And yeah IIRC the Shenandoah issue had something to do with load barrier triggering relocation, and the new object being after TAMS, messing up some reference processing code as some referent then became live while it should have been dead really.

**Pull request closed without merging**
