### PR TITLE
8283715: Update ObjectStreamClass to be final

### PR DESCRIPTION
**Pull request by stuart-marks**
Pretty much just what it says.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8283715](https://bugs.openjdk.java.net/browse/JDK-8283715): Update ObjectStreamClass to be final
 * [JDK-8283811](https://bugs.openjdk.java.net/browse/JDK-8283811): Update ObjectStreamClass to be final (**CSR**)

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to 4b9bf9903dd71b0f34da89ebc3397ff180881c5a
 * [Jaikiran Pai](https://openjdk.java.net/census#jpai) (@jaikiran - Committer)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to 77b6d79f70038a41686e497b8d2aada57ed35b40
 * [Daniel Fuchs](https://openjdk.java.net/census#dfuchs) (@dfuch - **Reviewer**) ⚠️ Review applies to 77b6d79f70038a41686e497b8d2aada57ed35b40

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8009/head:pull/8009` \
`$ git checkout pull/8009`

Update a local copy of the PR: \
`$ git checkout pull/8009` \
`$ git pull https://git.openjdk.java.net/jdk pull/8009/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8009`

View PR using the GUI difftool: \
`$ git pr show -t 8009`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8009.diff">https://git.openjdk.java.net/jdk/pull/8009.diff</a>

</details>

### CODE REVIEW

**Comment by stuart-marks** [comment]
Please review CSR request [JDK-8283811](https://bugs.openjdk.java.net/browse/JDK-8283811).

**Review by jddarcy — APPROVED** [review]

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
The test failures caught by GitHub Actions jobs look related to the area of this change:

```
2022-03-29T02:21:21.2187570Z 	at CheckCSMs.main(CheckCSMs.java:98)
2022-03-29T02:21:21.2188140Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2022-03-29T02:21:21.2188650Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
2022-03-29T02:21:21.2189060Z 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
2022-03-29T02:21:21.2189420Z 	at java.base/java.lang.Thread.run(Thread.java:828)
2022-03-29T02:21:21.2189590Z 
2022-03-29T02:21:21.2190030Z JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected non-final instance method: 
2022-03-29T02:21:21.2190400Z java/io/ObjectStreamField#getType ()Ljava/lang/Class;
```

**Comment by dfuch** [comment]
Yes - it looks like jdk/internal/reflect/CallerSensitive/CheckCSMs.java needs to be updated.

**Comment by RogerRiggs** [comment]
Close by is `java.io.ObjectStreamField` which seems also useful to make final.
Though it does have a public constructor so is more likely to raise a compatibility concern.

**Comment by stuart-marks** [comment]
Yes, the CheckCSMs test needed to be updated to remove ObjectStreamClass#forClass from the list of non-final CSMs, as that method is now part of a final class. The error message about ObjectStreamField#getType is misleading; I've fixed up the error reporting for this case.

**Comment by stuart-marks** [comment]
It would indeed be interesting to make adjustments to ObjectStreamField. However, it's publicly subclassable, and it's not serializable, so a different set of dynamics apply. I'd like to consider that effort separately from this PR.

**Review by mlchung — APPROVED** [review]

**Comment by mlchung** [comment]
Looks good.   Thanks for improving the error reporting in CheckCSMs test.

**Comment by jaikiran** [comment]
Hello Stuart, the test change looks fine to me. Just a minor note - the copyright year of the test will need an update.

**Comment by stuart-marks** [comment]
@jaikiran Thanks, I've updated the copyright year. I will integrate when I can keep an eye on the subsequent builds.

**Review by jaikiran — APPROVED** [review]

**Pull request closed without merging**
