### PR TITLE
8300997: Add curl support to createJMHBundle.sh

### PR DESCRIPTION
**Pull request by eirbjo**
Please review this PR which updates make/devkit/createJMHBundle.sh to add support for curl instead of wget when downloading JMH dependencies.

This would reduce friction for MacOS devs who would like to run micros without installing wget first.

File download is extracted to a function taking the Maven directory, artifactId and version as input. The function builds the correct download URL and checks which of curl / wget is available.

Tested on MacOS 12.6.2 and Ubuntu 20.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300997](https://bugs.openjdk.org/browse/JDK-8300997): Add curl support to createJMHBundle.sh

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12164/head:pull/12164` \
`$ git checkout pull/12164`

Update a local copy of the PR: \
`$ git checkout pull/12164` \
`$ git pull https://git.openjdk.org/jdk pull/12164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12164`

View PR using the GUI difftool: \
`$ git pr show -t 12164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12164.diff">https://git.openjdk.org/jdk/pull/12164.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
Filed https://bugs.openjdk.org/browse/JDK-8300997

**Review by erikj79 — APPROVED** [review]

**Comment by eirbjo** [comment]
@erikj79 Thanks for your review and help with the JBS, much appreciated!

Will you also be willing to sponsor?

**Pull request closed without merging**
