### PR TITLE
8278185: Custom JRE cannot find non-ASCII named module inside

### PR DESCRIPTION
**Pull request by toshiona**
Could you review this fix?

Problem:
Custom JRE generated by jlink cannot find non-ASCII named modules included inside the JRE.

Cause and fix:
If module or package name was composed by ASCII then non-ASCII characters, 
ImageStringsReader:stringFromByteBufferMatches() miscalculated the length of matched string. The first part of ASCII characters was missing. This patch corrected the value.

Testing:
tier1 and tier2 on Linux have no regression.
I wasn't able to create an automate test for this issue. I appreciate any advice.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278185](https://bugs.openjdk.java.net/browse/JDK-8278185): Custom JRE cannot find non-ASCII named module inside

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**) ⚠️ Review applies to d281e85d8bfea5388ab9f4be2f9a7661bfd93b22

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/6693/head:pull/6693` \
`$ git checkout pull/6693`

Update a local copy of the PR: \
`$ git checkout pull/6693` \
`$ git pull https://git.openjdk.java.net/jdk pull/6693/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6693`

View PR using the GUI difftool: \
`$ git pr show -t 6693`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/6693.diff">https://git.openjdk.java.net/jdk/pull/6693.diff</a>

</details>

### CODE REVIEW

**Review by JimLaskey — CHANGES_REQUESTED** [review]
Change looks reasonable. Please supply a regression test.

**Comment by AlanBateman** [comment]
Yes, I think we would be good to have a test. If it's too hard using the tools then a test that uses the image reader API directly would be okay. @naotoj may have some suggestions too.

**Comment by naotoj** [comment]
Regression tests for `ResourceBundle` class have tests that dynamically generate modules. Although I have not used non-ASCII module names, tests under `test/jdk/java/util/ResourceBundle/modules` may shed some light on the subject.

**Comment by toshiona** [comment]
Thank you so much for the valuable advices, Jim, Alan, and Naoto.

The created test calls `ImageStringsReader.stringFromByteBufferMatches()` directly.
It's a package private method, and I tried to use library style.

The upper public method, `BasicImageReader.match()`, is hard to prepare data.
Calling jlink is also complex for me. So, I choose this way.

**Comment by naotoj** [comment]
There is a jlink plugin test case that dynamically creates custom jimages with locale data variations. That might be of your interest: `test/jdk/tools/jlink/plugins/IncludeLocalesPluginTest.java`.

**Comment by toshiona** [comment]
Thank you again for valuable information, Sato-san.
I've replaced the testcase with the one using helper classes.

One tricky part is using InMemory methods, because non-ASCII name file may not be created.
Non-ASCII name file was packed in a jar file directly.

**Review by naotoj — APPROVED** [review]
Thanks for updating the test. Looks good to me.
I might be tempted to change the test case name, as `Strings` is too generic. Maybe to `JImageNonAsciiNameTest.java` or similar.

**Comment by toshiona** [comment]
@naotoj 
Thank you very much for the review.
Could you sponsor the change please?

**Comment by naotoj** [comment]
Sure, I can. But I would like @JimLaskey to have a final look at it.

**Comment by JimLaskey** [comment]
> Sure, I can. But I would like @JimLaskey to have a final look at it.

Standing by

**Pull request closed without merging**
