### PR TITLE
JDK-8265496: improve null check in DeflaterOutputStream/InflaterInputStream

### PR DESCRIPTION
**Pull request by Hamlin-Li**
code like below will create Deflater before null check, although it's not a real mem leak, but it's better to do null check before new Deflater.

        try {
            DeflaterOutputStream dos = new DeflaterOutputStream(null);
        } catch (NullPointerException e) {
            passed = true;
        }
Similar issues exist in several other classes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265496](https://bugs.openjdk.java.net/browse/JDK-8265496): improve null check in DeflaterOutputStream/InflaterInputStream

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3681/head:pull/3681` \
`$ git checkout pull/3681`

Update a local copy of the PR: \
`$ git checkout pull/3681` \
`$ git pull https://git.openjdk.java.net/jdk pull/3681/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3681`

View PR using the GUI difftool: \
`$ git pr show -t 3681`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3681.diff">https://git.openjdk.java.net/jdk/pull/3681.diff</a>

</details>

### CODE REVIEW

**Review by vyommani — COMMENTED** [review]
Changes looks OK to me, did you change  "DataOutputStreamTest.java" as well. I can see only copyright changes ?.

**Comment by Hamlin-Li** [comment]
It's changed by another patch sometimes ago, but I missed to update the copyright.

**Review by LanceAndersen — APPROVED** [review]
Hi Hamlin,

The change looks fine.  Please add the noreg-trivial change to the issue given there is not a test update for this so that you do not get pinged by a bot

**Review by naotoj — APPROVED** [review]

**Comment by Hamlin-Li** [comment]
> Hi Hamlin,
> 
> The change looks fine. Please add the noreg-trivial change to the issue given there is not a test update for this so that you do not get pinged by a bot

Hi Lance, Thanks for reminding.

**Comment by Hamlin-Li** [comment]
Thanks @LanceAndersen @naotoj @vyommani for your review.

**Pull request closed without merging**
