### PR TITLE
8263392: Allow current thread to be specified in ExceptionMark

### PR DESCRIPTION
**Pull request by iklam**
`ExceptionMark`, usually used via the `EXCEPTION_MARK` marco, is used to guarantee that an exception is not thrown within a block of code. I made two changes to improve efficiency:

- Avoid calling `Thread::current()` if a thread object is already available.
- Avoid passing a reference to the `ExceptionMark` constructor. This helps C++ generate slightly better code.

This new variant of `ExceptionMark` is mainly intended for future clean up of `TRAPS/CHECK/THREAD` code, where an exception context is temporarily needed but we will guarantee that all exceptions will be handled. I modified `SharedRuntime::monitor_exit_helper()` to use this pattern:

Old style:

```
void a_func_that_never_throws() {
  EXCEPTION_MARK;
  a_func_that_could_throw(THREAD);
  if (HAS_PENDING_EXCEPTION) {
      // handle it
    CLEAR_PENDING_EXCEPTION;
  }
}
```

New style:

```
void a_func_that_never_throws(Thread* current) { // pass thread to avoid calling Thread::current()
  ExceptionMark em(current);
  Thread* THREAD = current; // For exception macros.
  a_func_that_could_throw(THREAD);
  if (HAS_PENDING_EXCEPTION) {
      // handle it
      CLEAR_PENDING_EXCEPTION;
  }
}
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263392](https://bugs.openjdk.java.net/browse/JDK-8263392): Allow current thread to be specified in ExceptionMark

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 91eefd7141f33a39fbe7ef9e83ba1bbaaea95698
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [Yumin Qi](https://openjdk.java.net/census#minqi) (@yminqi - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/2950/head:pull/2950`
`$ git checkout pull/2950`

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good! Thanks for doing this cleanup.

David

**Review by calvinccheung — APPROVED** [review]
Looks good.

**Review by coleenp — APPROVED** [review]
This looks good.  It would be nice to replace more EXCEPTION_MARK as we find them.

**Review by yminqi — APPROVED** [review]
This change is good.

**Comment by iklam** [comment]
Thanks @dholmes-ora @calvinccheung @coleenp @yminqi for the review.
/integrate

**Pull request closed without merging**
