### PR TITLE
8259339: AllocateUninitializedArray C2 intrinsic fails with void.class input

### PR DESCRIPTION
**Pull request by TobiHartmann**
Since [JDK-8150465](https://bugs.openjdk.java.net/browse/JDK-8150465), `LibraryCallKit::inline_unsafe_newArray` is also used by the `_allocateUninitializedArray` intrinsic. To handle a `void.class` input, a runtime (slow) call to the intrinsified method is emitted. We hit a guarantee in `generate_method_call_static` because a wrong intrinsic id is passed. Also, the call to `Unsafe.allocateUninitializedArray0` should be virtual.

I found this when running Valhalla stress testing with `-XX:PerMethodTrapLimit=0` but it easily reproduces without (see modified test).

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259339](https://bugs.openjdk.java.net/browse/JDK-8259339): AllocateUninitializedArray C2 intrinsic fails with void.class input

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1965/head:pull/1965`
`$ git checkout pull/1965`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by TobiHartmann** [comment]
Thanks Vladimir!

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Comment by TobiHartmann** [comment]
Thanks Christian!

**Pull request closed without merging**
