### PR TITLE
8296656: java.lang.NoClassDefFoundError exception on running fully legitimate code

### PR DESCRIPTION
**Pull request by archiecobbs**
This bug and a few others fall into the "output file clash" bucket. This is when the compiler thinks it's writing out two separate files, but due to the way the O/S filesystem maps `Path`'s to actual files, it's really writing the same file twice.

This is usually due to case-insensitive filesystems, but can also be due to how a filesystem "normalizes" file names. For example, on MacOS, compiling this class will generate such a clash:
```java
public class Test {
    interface Cafe\u0301 {
    }
    interface Caf\u00e9 {
    }
}
```
The reason is that `\u0301` is the Unicode character "Combining Acute Accent" which means "stick an accent over the previous character". So MacOS normalizes a `e` followed by a `\u0301` into a Unicode `\u00e9`, that is, `é`. However, the Java language treats these the two names `Cafe\u0301` and `Caf\u00e9` as distinct.

It's infeasible to truly "fix" this problem, so we resort here to a salve, which is to add a new compiler flag `--detect-output-file-clashes` that enables detection of output file clashes. When the flag is enabled, and a clash is detected, an error is immediately thrown. For example, compiling the example above gives this:
```
$ javac --help-extra
  ...
  --detect-output-file-clashes
        Generate an error if any output file is overwritten during compilation. This can occur, for example,
        on case-insensitive filesystems. This applies to class files, native header files, and source files.
  ...
$ javac --detect-output-file-clashes Test.java
Test.java:4: error: error while writing Café: output file clash: /Users/archie/test/Test$Café.class
    interface Caf\u00e9 {
    ^
1 error
```
This at least gives people at risk of encountering this problem a way to turn a runtime error into a compile-time error.

**Outstanding Questions**
* Is making this optional via an (extended) flag `--detect-output-file-clashes` the best way to address this?
* Does the new field `BaseFileManager.outputFilesWritten` ever need to be cleared? Can the file manager be used for multiple compilations? If so, is there some "reset" step we should hook into?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8304533](https://bugs.openjdk.org/browse/JDK-8304533) to be approved

### Issues
 * [JDK-8296656](https://bugs.openjdk.org/browse/JDK-8296656): java.lang.NoClassDefFoundError exception on running fully legitimate code
 * [JDK-8287885](https://bugs.openjdk.org/browse/JDK-8287885): Local classes cause ClassLoader error if the type names are similar but not same
 * [JDK-8304533](https://bugs.openjdk.org/browse/JDK-8304533): Add new lint flag "output-file-clash" (**CSR**)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12754/head:pull/12754` \
`$ git checkout pull/12754`

Update a local copy of the PR: \
`$ git checkout pull/12754` \
`$ git pull https://git.openjdk.org/jdk.git pull/12754/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12754`

View PR using the GUI difftool: \
`$ git pr show -t 12754`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12754.diff">https://git.openjdk.org/jdk/pull/12754.diff</a>

</details>

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks good to me

**Comment by vicente-romero-oracle** [comment]
tier1-4 green

**Comment by davidalayachew** [comment]
Thanks @archiecobbs and @vicente-romero-oracle

Sorry for having sent this so late, it's hard to keep up with the traffic of the mailing lists. I only found this because I looked up my old JBS submission from last year on a whim.

What's the best way I should go about testing this? I see instructions on how to build the JDK from the source code. Is that the best way? Or are there any prebuilt versions that contain this fix that you all can think of from the top of your head?

Thanks again for your time, help, and patience!
David Alayachew

**Comment by davidalayachew** [comment]
And just for context, I am the original submitter of 8287885

**Comment by archiecobbs** [comment]
> What's the best way I should go about testing this?

Using whatever your original example was. Or some simple example like this on a case-insensitive filesystem:
```java
public class Test {
    interface Inner {
    }
    interface INNER {
    }
}
```

> I see instructions on how to build the JDK from the source code. Is that the best way?

As far as I know that's the best way... but I could be unaware of pre-built preview images somewhere.

**Comment by davidalayachew** [comment]
> > What's the best way I should go about testing this?
> 
> Using whatever your original example was. Or some simple example like this on a case-insensitive filesystem:
> 
> ```java
> public class Test {
>     interface Inner {
>     }
>     interface INNER {
>     }
> }
> ```
> 
> > I see instructions on how to build the JDK from the source code. Is that the best way?
> 
> As far as I know that's the best way... but I could be unaware of pre-built preview images somewhere.

Ok, beautiful. I'll get on that now. Thanks again to you both!

**Comment by davidalayachew** [comment]
Finished building the jdk from source and tested the fix. It worked!

Here is a demonstration for those who are following along.

```
$ cat abc.java
public class abc
{

        public static class XYZ {}
        public static class xyz {}

        public static void main(String[] args)
        {

                System.out.println("abc");

                XYZ a = new XYZ();

                System.out.println("tuv");

                xyz b = new xyz();

                System.out.println("xyz");

        }

}

$ javac abc.java -Xlint:output-file-clash
warning: [output-file-clash] output file written more than once: C:\Users\david\_WORKSPACE\_PROGRAMMING\_JAVA\abc$xyz.class
1 warning
```


As you can see, if I use the -Xlint warning above, I now get a warning if any of my classes generate the same filename multiple times. This is perfect, as I now know at compile time that this is something to watch out for.

Thank you for fixing this Archie/Vicente!

**Pull request closed without merging**
