### PR TITLE
8315220: Event NativeLibraryLoad breaks invariant by taking a stacktrace when thread is in state _thread_in_native

### PR DESCRIPTION
**Pull request by mgronlun**
Greetings,

This change set fixes the issue of taking a JFR stack trace in the wrong thread state for the NativeLibraryLoad and NativeLibraryUnload events.

A follow-up change set, [JDK-8315364](https://bugs.openjdk.org/browse/JDK-8315364) will add assertions to the JFR stack trace code to help find similar issues earlier.

There are a few additional improvements:

The event declaration in metadata.xml now includes the generating thread since a stack trace without the generating thread is subpar.

In os_linux.cpp, the NativeLibraryLoad event was located after the call to dlopen(), which means that the event, declared durational, fails to capture the duration of the call.

Finally, the test is extended to validate the captured stack trace.

Testing: jdk_jfr, stress testing

Thanks
Markus

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315220](https://bugs.openjdk.org/browse/JDK-8315220): Event NativeLibraryLoad breaks invariant by taking a stacktrace when thread is in state _thread_in_native (**Bug** - P3)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [aa4bc48a](https://git.openjdk.org/jdk/pull/15535/files/aa4bc48aba1ac99d82ae06b184428240a2506631)
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15535/head:pull/15535` \
`$ git checkout pull/15535`

Update a local copy of the PR: \
`$ git checkout pull/15535` \
`$ git pull https://git.openjdk.org/jdk.git pull/15535/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15535`

View PR using the GUI difftool: \
`$ git pr show -t 15535`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15535.diff">https://git.openjdk.org/jdk/pull/15535.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15535#issuecomment-1702653779)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]
LGTM (we tested it also for some days in our internal infrastructure)

**Review by egahlin — APPROVED** [review]

**Comment by mgronlun** [comment]
Thank you @egahlin and @MBaesken, for your reviews.

**Pull request closed without merging**
