### PR TITLE
8250888: nsk/jvmti/scenarios/general_functions/GF08/gf08t001/TestDriver.java fails

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

`TestDriver.java` used `sun.hotspot.WhiteBox.getBooleanVMFlag("Use*GC")` which could return null.
This patch uses `sun.hotspot.gc.GC` instead of `sun.hotspot.WhiteBox` to avoid the NullPointerException.
Thank you for taking the time to review.

Best Regards.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (6/6 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8250888](https://bugs.openjdk.java.net/browse/JDK-8250888): nsk/jvmti/scenarios/general_functions/GF08/gf08t001/TestDriver.java fails

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1319/head:pull/1319`
`$ git checkout pull/1319`

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
I believe it should be `isSelected()` rather than `isSupported()`. Try to run the test with different GCs like this to verify:

`make run-test TEST=nsk/jvmti/scenarios/general_functions/GF08/gf08t001/TestDriver.java TEST_VM_OPTS=-XX:+UseShenandoahGC`

**Review by plummercj — APPROVED** [review]
The changes look good, but I think the fact that when you used `isSupported()` you didn't see any failures indicates that proper testing was not done with all GCs. Please be sure to do this testing. In fact you might want to first try testing with `isSupported()` to confirm that you do see failures.

**Review by sspitsyn — APPROVED** [review]
Hi Guoxiong,
It looks good to me.
Thanks,
Serguei

**Comment by lgxbslgx** [comment]
I run the test locally using the following command before I submit this patch.
```
make test TEST="jtreg:hotspot/jtreg/vmTestbase/nsk/jvmti/scenarios/general_functions/GF08/gf08t001/TestDriver.java"  TEST_VM_OPTS=-XX:+UseShenandoahGC
```
This test passes which misleads me that my patch is right.

In any case, I apologize for this mistake and will try my best to do more testing before submitting patches in the future.
Thank you very much for taking the time to review.

Best Regards.

**Comment by shipilev** [comment]
I tested this patch with Serial, Parallel, G1, Shenandoah, Z and it passes.

**Pull request closed without merging**
