### PR TITLE
8291895: Remove PRAGMA_NONNULL_IGNORED from x86 and AArch64

### PR DESCRIPTION
**Pull request by theRealAph**
I fixed the underlying bugs, so the warnings are now superfluous. Build on GCC 11.0.3 and GCC head.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291895](https://bugs.openjdk.org/browse/JDK-8291895): Remove PRAGMA_NONNULL_IGNORED from x86 and AArch64

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/9742/head:pull/9742` \
`$ git checkout pull/9742`

Update a local copy of the PR: \
`$ git checkout pull/9742` \
`$ git pull https://git.openjdk.org/jdk pull/9742/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9742`

View PR using the GUI difftool: \
`$ git pr show -t 9742`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/9742.diff">https://git.openjdk.org/jdk/pull/9742.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
Nice.

`PRAGMA_DIAG_POP` should be removed along with `PRAGMA_DIAG_PUSH`. See how Windows/MSVC builds complain about it. This probably warrants retesting on GCCs.

**Comment by theRealAph** [comment]
> Nice.
> 
> `PRAGMA_DIAG_POP` should be removed along with `PRAGMA_DIAG_PUSH`. See how Windows/MSVC builds complain about it. This probably warrants retesting on GCCs.

LOL! I never even noticed them.  :-)

**Review by shipilev — APPROVED** [review]
GCC 11 x86_64 and x86_32 builds completed fine. GCC 12 x86_64 build completed fine.

Looks good, as long as GHA is happy.

**Pull request closed without merging**
