### PR TITLE
8264193: Remove TRAPS parameters for modules and defaultmethods

### PR DESCRIPTION
**Pull request by hseigel**
Please review this change for JDK-8264193 to remove unneeded TRAPS parameters from modules and default methods files.  Besides removing TRAPS, Modules::get_named_module() was changed to return an oop instead of a jobject, removing its need for a TRAPS parameter.

This change was tested with Mach5 tiers 1 and 2 on Linux, Mac OS, and Windows, and Mach5 tiers 3-5 on Linux x64.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264193](https://bugs.openjdk.java.net/browse/JDK-8264193): Remove TRAPS parameters for modules and defaultmethods

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)
 * [Calvin Cheung](https://openjdk.java.net/census#ccheung) (@calvinccheung - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3247/head:pull/3247` \
`$ git checkout pull/3247`

Update a local copy of the PR: \
`$ git checkout pull/3247` \
`$ git pull https://git.openjdk.java.net/jdk pull/3247/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3247`

View PR using the GUI difftool: \
`$ git pr show -t 3247`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3247.diff">https://git.openjdk.java.net/jdk/pull/3247.diff</a>

</details>

### CODE REVIEW

**Review by lfoltan — APPROVED** [review]
Looks good Harold!
Lois

**Review by calvinccheung — APPROVED** [review]
LGTM.

**Review by coleenp — APPROVED** [review]
Looks good!!

**Review by dholmes-ora — APPROVED** [review]
Great cleanup Harold!

Thanks,
David

**Comment by hseigel** [comment]
Thanks Lois, Calvin, Coleen, and David for the reviews!

/integrate

**Pull request closed without merging**
