### PR TITLE
8340792: -XX:+PrintInterpreter: instructions should only be printed if printing all InterpreterCodelets

### PR DESCRIPTION
**Pull request by reinrich**
With `-XX:+PrintInterpreter` the instructions of the generated interpreter are printed at startup.

But also after startup when printing an interpreted frame the instructions of the corresponding `InterpreterCodelet` are also printed. This can become a problem with `-Xlog:continuations=trace` because large sections of the interpreter are printed repeatedly and redundantly.

With this change the instructions are only printed when printing all codelets, i.e. normally once at start-up.

I've tested with the reproducer from the JBS-Issue.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340792](https://bugs.openjdk.org/browse/JDK-8340792): -XX:+PrintInterpreter: instructions should only be printed if printing all InterpreterCodelets (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21158/head:pull/21158` \
`$ git checkout pull/21158`

Update a local copy of the PR: \
`$ git checkout pull/21158` \
`$ git pull https://git.openjdk.org/jdk.git pull/21158/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21158`

View PR using the GUI difftool: \
`$ git pr show -t 21158`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21158.diff">https://git.openjdk.org/jdk/pull/21158.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21158#issuecomment-2373552055)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Review by coleenp — APPROVED** [review]
Looks fine.

**Comment by reinrich** [comment]
Thanks for the reviews.
/integrate

**Pull request closed without merging**
