### PR TITLE
JDK-8311870: Split CompressedKlassPointers from compressedOops.hpp

### PR DESCRIPTION
**Pull request by tstuefe**
In preparation for some Lilliput-related changes, I'd like to get some purely mechanical code moves out of the way. It would also improve separation of concerns and reduces include header bloat.

In particular, this patch does:

1) Move `CompressedKlassPointers` from `compressedOops.(cpp|hpp|inline.hpp)` to `compressedKlass.(cpp|hpp|inline.hpp)`

2) flatten the `NarrowPtrStruct _narrow_klass` to `address _base; int _shift` (its implicit null check member is not needed for Klass and it has little merit otherwise).

3) moved `narrowKlass` from `oopsHierarchy.hpp` to `compressedKlass.hpp`

4) remove `KlassAlignment` and `LogKlassAlignment` (the word-sized variants, not xxxInBytes) since they are unused

5) Move `KlassEncodingMetaspaceMax`, `LogKlassAlignmentInBytes` and `KlassAlignmentInBytes` to compressedKlass.hpp

6) Fixed all include issues (including existing missing includes)

7) Fixed VM struct because of (2)

Note that nothing functional is changed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311870](https://bugs.openjdk.org/browse/JDK-8311870): Split CompressedKlassPointers from compressedOops.hpp (**Enhancement** - P4)

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - **Reviewer**)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14826/head:pull/14826` \
`$ git checkout pull/14826`

Update a local copy of the PR: \
`$ git checkout pull/14826` \
`$ git pull https://git.openjdk.org/jdk.git pull/14826/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14826`

View PR using the GUI difftool: \
`$ git pr show -t 14826`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14826.diff">https://git.openjdk.org/jdk/pull/14826.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14826#issuecomment-1630874838)

### CODE REVIEW

**Comment by tstuefe** [comment]
pinging @rkennke

**Review by iklam — APPROVED** [review]
Looks reasonable to me.

**Comment by tstuefe** [comment]
> Looks reasonable to me.

Thank you Ioi.

**Review by rkennke — APPROVED** [review]
Looks good to me!

**Comment by tstuefe** [comment]
> Looks good to me!

Thank you @rkennke !

/integrate

**Pull request closed without merging**
