### PR TITLE
8343486: Remove unnecessary @SuppressWarnings annotations and -Xlint:-foo options

### PR DESCRIPTION
**Pull request by archiecobbs**
Please review this patch which removes unnecessary `@SuppressWarnings` annotations and `-Xlint:-foo` options.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343486](https://bugs.openjdk.org/browse/JDK-8343486): Remove unnecessary @SuppressWarnings annotations and -Xlint:-foo options (**Bug** - P5)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21859/head:pull/21859` \
`$ git checkout pull/21859`

Update a local copy of the PR: \
`$ git checkout pull/21859` \
`$ git pull https://git.openjdk.org/jdk.git pull/21859/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21859`

View PR using the GUI difftool: \
`$ git pr show -t 21859`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21859.diff">https://git.openjdk.org/jdk/pull/21859.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21859#issuecomment-2453040160)
</details>

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Changes under `make` looks good, thanks for cleaning this up!

I'm not sure who should review the changes under `src`. The `i18n` label does not seem correct for changes in dynalink and jsobject.

**Comment by archiecobbs** [comment]
Thanks for the quick review.

**Comment by magicus** [comment]
Eh... I tried to say that I had only reviewed part of this PR. Maybe I should have made that clearer by bumping the number of required reviewers as well; I usually do that but I forgot it this time.

The changes look fairly benign so I guess there is no harm done this time.

**Comment by archiecobbs** [comment]
> Eh... I tried to say that I had only reviewed part of this PR. Maybe I should have made that clearer by bumping the number of required reviewers as well; I usually do that but I forgot it this time.

Argh, sorry... I was just blindly assuming the bot knew what it was doing... my mistake.

In any case it's probably worth getting another pair of eyes to review the other changes... if there ends up being an issue I'm happy to address it in another PR.

Thanks.

**Comment by magicus** [comment]
It's never quite that simple. As the bot is fond of saying, "This change now passes all automated pre-integration checks. [...] This project also has non-automated pre-integration requirements"...

**Comment by liach** [comment]
Sorry for coming late, but I think bidi/icu is an external library and its updates are tracked by i18n engineers.  We might have to revert those specific changes for library parity dependent on i18n engineers' discretion.

/cc i18n

**Comment by naotoj** [comment]
> Sorry for coming late, but I think bidi/icu is an external library and its updates are tracked by i18n engineers. We might have to revert those specific changes for library parity dependent on i18n engineers' discretion.

Thank you, Chen. I was aware that the ICU file was modified and I thought it was OK, as ICU sources are already diverted, not identical to the upstream. So unless the modification conflicts with the upstream it's fine.

**Pull request closed without merging**
