### PR TITLE
read() returns a byte. This PR Changes return type to reflect that

### PR DESCRIPTION
**Pull request by EvModder**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22858/head:pull/22858` \
`$ git checkout pull/22858`

Update a local copy of the PR: \
`$ git checkout pull/22858` \
`$ git pull https://git.openjdk.org/jdk.git pull/22858/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22858`

View PR using the GUI difftool: \
`$ git pr show -t 22858`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22858.diff">https://git.openjdk.org/jdk/pull/22858.diff</a>

</details>

### CODE REVIEW

**Comment by liach** [comment]
Before talking about the other problems, do you realize the range of a `byte` is -128 to 127 instead of 0 to 255, and thus most usages of unsigned bytes in the core libraries are statically typed as int?

**Comment by EvModder** [comment]
Ah... I see.
I also see some cases where -1 is returned as an EOF or error indicator, from functions which typically return unsigned `byte`.

Which, while it pains me, means that this PR is definitely something to scrap.  It'd take a full library rewrite to change this kind of behavior, and I don't see myself (or anyone else) attempting that.

**Comment by liach** [comment]
FYI If you have read the JVMS, you will notice that in bytecode bytes are just ints that happen to be within -128 and 127. Not being able to use a smaller data type isn't much of a loss here luckily.

**Comment by EvModder** [comment]
Thank you @liach, that is good to know.
I was mainly inspired to do the PR because always casting the result `int` to `byte` felt like incorrect usage.
In C++ and some other languages, it is common to return `StatusOr<T>`, in this case `StatusOr<byte>`, which would help prevent "magic values" like the `-1` integer in a unsigned byte return from functions like `read()` here in `InputStream`

**Comment by liach** [comment]
You know, Java has to compile to bytecode and consider binary compatibility, so it cannot change signatures. Currently such wrappers are too expensive; we might get these in the core libraries once value objects arrive

**Pull request closed without merging**
