### PR TITLE
8344336: SM cleanup of java.lang.System, Runtime, String, StackWalker

### PR DESCRIPTION
**Pull request by RogerRiggs**
Removed use of SecurityManager to check permissions.
Relaxed defensive copying of byte arrays (due to lack of SM)

Refresh of PR#22168 Including review comments made there.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8344336](https://bugs.openjdk.org/browse/JDK-8344336): SM cleanup of java.lang.System, Runtime, String, StackWalker (**Enhancement** - P4)

### Reviewers
 * [Daniel Fuchs](https://openjdk.org/census#dfuchs) (@dfuch - **Reviewer**)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22282/head:pull/22282` \
`$ git checkout pull/22282`

Update a local copy of the PR: \
`$ git checkout pull/22282` \
`$ git pull https://git.openjdk.org/jdk.git pull/22282/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22282`

View PR using the GUI difftool: \
`$ git pr show -t 22282`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22282.diff">https://git.openjdk.org/jdk/pull/22282.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22282#issuecomment-2489417009)
</details>

### CODE REVIEW

**Review by dfuch — COMMENTED** [review]
The changes to SystemLogger looks OK to me. Maybe you could get rid of the LoggerFinder `private static Void checkPermission()` method altogether?

**Review by dfuch — COMMENTED** [review]
And also of the associated private constructor `LoggerFinder(Void)` as well as the 
```
static final RuntimePermission LOGGERFINDER_PERMISSION =
new RuntimePermission("loggerFinder");
```
constant (which should no longer be needed now?)

**Comment by dfuch** [comment]
Note: I am taking care of the implementation classes in https://github.com/openjdk/jdk/pull/22281.

**Comment by AlanBateman** [comment]
I agree with Daniel that LOGGERFINDER_PERMISSION and the special constructor to ensure the permission check can be removed. I skimmed through the rest, including the change to Module since the other PR, and it looks fine.

**Review by AlanBateman — APPROVED** [review]
I did another pass over this, looks okay.

**Review by dfuch — APPROVED** [review]
Thanks for the updates to LoggerFinder. LGTM now.

**Review by LanceAndersen — APPROVED** [review]
Looks good jai

**Pull request closed without merging**
