### PR TITLE
8293961: Unused ClassPathZipEntry::contents_do

### PR DESCRIPTION
**Pull request by matias9927**
Removed unused function and ran tier1 to verify. Please review.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293961](https://bugs.openjdk.org/browse/JDK-8293961): Unused ClassPathZipEntry::contents_do

### Reviewers
 * [Calvin Cheung](https://openjdk.org/census#ccheung) (@calvinccheung - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10413/head:pull/10413` \
`$ git checkout pull/10413`

Update a local copy of the PR: \
`$ git checkout pull/10413` \
`$ git pull https://git.openjdk.org/jdk pull/10413/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10413`

View PR using the GUI difftool: \
`$ git pr show -t 10413`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10413.diff">https://git.openjdk.org/jdk/pull/10413.diff</a>

</details>

### CODE REVIEW

**Review by calvinccheung — COMMENTED** [review]
Hi Matias,

The cleanup looks good. I think more cleanup could be done in classLoader.cpp.
Can you check if the following could be removed?

```
typedef jzentry* (*GetNextEntry_t)(jzfile *zip, jint n);

static GetNextEntry_t    GetNextEntry       = NULL;

  GetNextEntry = CAST_TO_FN_PTR(GetNextEntry_t, dll_lookup(_zip_handle, "ZIP_GetNextEntry", path));
```
Thanks,
Calvin

**Comment by matias9927** [comment]
The code you posted could indeed be removed. I verified that everything still works with tier 1 tests.

**Review by calvinccheung — APPROVED** [review]
Updated fix looks good. Thanks.

**Review by dholmes-ora — APPROVED** [review]
LGTM2

Thanks

**Pull request closed without merging**
