### PR TITLE
8327240: Obsolete Tier2CompileThreshold/Tier2BackEdgeThreshold product flags

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR removes the unused options ```Tier2CompileThreshold``` and ```Tier2BackEdgeThreshold```. 

Testing: 
- [x] Verified warning is issued as support was removed. 

Thanks, 
Sonia

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] Change requires CSR request [JDK-8331082](https://bugs.openjdk.org/browse/JDK-8331082) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8327240](https://bugs.openjdk.org/browse/JDK-8327240): Obsolete Tier2CompileThreshold/Tier2BackEdgeThreshold product flags (**Enhancement** - P4)
 * [JDK-8331082](https://bugs.openjdk.org/browse/JDK-8331082): Obsolete Tier2CompileThreshold/Tier2BackEdgeThreshold product flags (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18904/head:pull/18904` \
`$ git checkout pull/18904`

Update a local copy of the PR: \
`$ git checkout pull/18904` \
`$ git pull https://git.openjdk.org/jdk.git pull/18904/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18904`

View PR using the GUI difftool: \
`$ git pr show -t 18904`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18904.diff">https://git.openjdk.org/jdk/pull/18904.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18904#issuecomment-2072533727)

### CODE REVIEW

**Comment by chhagedorn** [comment]
Since these are product flags, you need a CSR and then first obsolete the flag (I think deprecation can be skipped since the flag is unused). You can have a look at the following PR which also aimed to remove an unused product flag recently by first obsoleting it:

https://github.com/openjdk/jdk/pull/18648

**Comment by dean-long** [comment]
Shouldn't we first ask the question: why aren't they used?  Maybe there is a bug, and in fact they should be used.

**Comment by chhagedorn** [comment]
I had a quick look at the git history. The only use of `Tier2CompileThreshold` that has been around since initial load was removed with https://github.com/openjdk/jdk/pull/888. For `Tier2BackEdgeThreshold`, the only use was removed when tiered compilation was introduced with [JDK-6953144](https://bugs.openjdk.org/browse/JDK-6953144). There is, however, a single test that uses `Tier2BackEdgeThreshold` which should also be updated if these flags are going to be removed:
https://github.com/openjdk/jdk/blob/20546c1ea064daa8e2faa71142904ea2c62b3311/test/hotspot/jtreg/vmTestbase/jit/t/t105/t105.java#L34

This suggests that it's fine to remove these. But maybe @veresov can comment on this.

**Comment by tstuefe** [comment]
@SoniaZaldana I would:
- first raise the question on hotspot-compiler-dev. 
- since this is a product flag, it needs a CSR, so you need to create one. There are many examples in JBS, e.g. https://bugs.openjdk.org/browse/JDK-8320162
- then you can go ahead with this change.

**Pull request closed without merging**
