### PR TITLE
8167015: compiler/codecache/jmx/PoolsIndependenceTest.java timeout

### PR DESCRIPTION
**Pull request by lepestock**
Fixed some issues in the test:

1. Replaced obvious mistake with event duration equal to `beginTimestamp - lastEventTimestamp` (giving negative value)
2. Using timeouts to address the problem with notification not being sent due to code cache usage never hitting the limit. Possible explanations:
    Code cache was cleaned just after setting the limit;
    CodeCacheUtils silently failed the blob allocation, causing the notification to never get fired
3. Provided some additional info in both the test log, and failure messages.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8167015](https://bugs.openjdk.java.net/browse/JDK-8167015): compiler/codecache/jmx/PoolsIndependenceTest.java timeout

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to 5d41df630b6d33e7aef302c8bc772b78fc8108c8
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jdk pull/3033/head:pull/3033`
`$ git checkout pull/3033`

To update a local copy of the PR:
`$ git checkout pull/3033`
`$ git pull https://git.openjdk.java.net/jdk pull/3033/head`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks reasonable.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Pull request closed without merging**
