### PR TITLE
8284840: Update CLDR to Version 42.0

### PR DESCRIPTION
**Pull request by naotoj**
This is to update the CLDR data from version 41 to version 42. The vast majority of the changes are basically replacing the CLDR data, along with tools/testcase alignments to those upstream changes:

https://unicode-org.atlassian.net/browse/CLDR-14032 (" at " is no longer used for standard date/time format)
https://unicode-org.atlassian.net/browse/CLDR-14831 (NBSP prefixed to `a`, instead of a normal space )
https://unicode-org.atlassian.net/browse/CLDR-11510 (Fix first day of week info for China (CN))
https://unicode-org.atlassian.net/browse/CLDR-15966 (Japanese: Support numbers up to 9999京)

Here is the link to CLDR v42's release notes: https://cldr.unicode.org/index/downloads/cldr-42

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8284840](https://bugs.openjdk.org/browse/JDK-8284840): Update CLDR to Version 42.0

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Joe Wang](https://openjdk.org/census#joehw) (@JoeWang-Java - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10820/head:pull/10820` \
`$ git checkout pull/10820`

Update a local copy of the PR: \
`$ git checkout pull/10820` \
`$ git pull https://git.openjdk.org/jdk pull/10820/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10820`

View PR using the GUI difftool: \
`$ git pr show -t 10820`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10820.diff">https://git.openjdk.org/jdk/pull/10820.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by JoeWang-Java** [comment]
Are the first two items (CLDR-14032, CLDR-14831) considered a behavior change (e.g. the format string will be different) that could use a CSR or the release notes to document it? I see the later points to the CLDR release notes, but maybe a statement in our release notes could be clearer?

**Comment by naotoj** [comment]
> Are the first two items (CLDR-14032, CLDR-14831) considered a behavior change (e.g. the format string will be different) that could use a CSR or the release notes to document it? I see the later points to the CLDR release notes, but maybe a statement in our release notes could be clearer?

Yes. These translation changes affect formatting. We don't usually file a CSR for such changes, but cover them in our release notes.

**Comment by naotoj** [comment]
Draft release notes: https://bugs.openjdk.org/browse/JDK-8284841

**Review by JoeWang-Java — APPROVED** [review]
Release notes look good to me.

**Comment by srl295** [comment]
hi folks 👋 looking good… congats on the quick update!

**Comment by AlanBateman** [comment]
> Yes. These translation changes affect formatting. We don't usually file a CSR for such changes, but cover them in our release notes.

Indeed and periodically CLDR upgrades do cause breakage somewhere, often it will be a library or application tests that compare some result that is outdated due to changes that impact the formatting.

**Comment by srl295** [comment]
> > Yes. These translation changes affect formatting. We don't usually file a CSR for such changes, but cover them in our release notes.
> 
> Indeed and periodically CLDR upgrades do cause breakage somewhere, often it will be a library or application tests that compare some result that is outdated due to changes that impact the formatting.

Yes, although libraries and tests shouldn't be testing against cultural formatting whose goal is to produce the updated best result, not the same result.  For example we had an internal corporate client which needed to use fixed formatting, instead of culturally sensitive formatting, because they really wanted exactly the same output every time, because the output data was going to be consumed by machine and not just by humans.

**Comment by MrDevitt** [comment]
>  https://unicode-org.atlassian.net/browse/CLDR-11510 (Fix first day of week info for China (CN))
Due to this feature, the result in jdk 21 of `calendar.get(Calendar.WEEK_OF_YEAR)` has changed from that in previous jdk version, which is unexpected in my application. Is there a way to make `calendar.setFirstDayOfWeek(Calendar.SUNDAY)` as default value so that I don't need to change it every time I create a new calendar? @naotoj

**Pull request closed without merging**
