### PR TITLE
8243559: Remove root certificates with 1024-bit keys

### PR DESCRIPTION
**Pull request by seanjmullan**
This change removes five root certificates with 1024-bit RSA public keys from the system-wide `cacerts` keystore. These are older VeriSign and Thawte root CA certificates which are no longer necessary to retain and should have minimal compatibility risk if removed.

See the CSR for more details: https://bugs.openjdk.java.net/browse/JDK-8256502

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) | ✔️ (9/9 passed) | ✔️ (9/9 passed) | ✔️ (9/9 passed) |

### Issue
 * [JDK-8243559](https://bugs.openjdk.java.net/browse/JDK-8243559): Remove root certificates with 1024-bit keys

### Reviewers
 * [Weijun Wang](https://openjdk.java.net/census#weijun) (@wangweij - **Reviewer**) ⚠️ Review applies to dd7a3508b876de673edb26681a9ee00696628d58

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1387/head:pull/1387`
`$ git checkout pull/1387`

### CODE REVIEW

**Comment by wangweij** [comment]
Looks fine.

One nit: I see that the `VerifyCACerts.java` test has a whole bunch of `@bug` ids. Maybe we should add this new one as well?

**Review by wangweij — APPROVED** [review]

**Comment by seanjmullan** [comment]
> Looks fine.
> 
> One nit: I see that the `VerifyCACerts.java` test has a whole bunch of `@bug` ids. Maybe we should add this new one as well?

Good catch. I will add it.

**Pull request closed without merging**
