### PR TITLE
8306855: [s390x] fix difference in abi sizes

### PR DESCRIPTION
**Pull request by offamitkumar**
This PR equals the interpreter, native abi sizes. JIT abi is completely removed as it was not being used anywhere in s390x code base. Apart form it, `z_abi_16` was replaced by `z_common_abi` and some other renaming followed this ladder.

Builds `slowdebug, fastdebug, release, optimized` are okay. `tier1-tests on fastdebug-build` are not affected as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306855](https://bugs.openjdk.org/browse/JDK-8306855): [s390x] fix difference in abi sizes

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13650/head:pull/13650` \
`$ git checkout pull/13650`

Update a local copy of the PR: \
`$ git checkout pull/13650` \
`$ git pull https://git.openjdk.org/jdk.git pull/13650/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13650`

View PR using the GUI difftool: \
`$ git pr show -t 13650`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13650.diff">https://git.openjdk.org/jdk/pull/13650.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13650#issuecomment-1522154580)

### CODE REVIEW

**Comment by offamitkumar** [comment]
x86 test failure is unrelated..

@RealLucy , @TheRealMDoerr , @reinrich Please review this PR.

Thank you :)

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Seems like `uint64_t toc` was taken from PPC64, but doesn't make sense for s390x. At least, I couldn't find it in the ABI spec.

**Comment by offamitkumar** [comment]
Thanks @TheRealMDoerr  for Review..

>LGTM. Seems like uint64_t toc was taken from PPC64, but doesn't make sense for s390x. At least, I couldn't find it in the ABI spec.


I had the same issue findind uses for `tmp` and `toc`; it appears they were never used.

**Comment by offamitkumar** [comment]
Thanks @RealLucy for a quick review-response.. 

/integrate

**Pull request closed without merging**
