### PR TITLE
8254345: com/sun/jdi/JdwpAttachTest.java reports error incorrectly

### PR DESCRIPTION
**Pull request by alexmenkov**
Please review a trivial fix for JdwpAttachTest

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254345](https://bugs.openjdk.java.net/browse/JDK-8254345): com/sun/jdi/JdwpAttachTest.java reports error incorrectly

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/619/head:pull/619`
`$ git checkout pull/619`

### CODE REVIEW

**Review by plummercj — CHANGES_REQUESTED** [review]
I think you got this backward. `expectedResult` indicates whether or not a successful attach was expected. Since we are not in the exception handling part of the code here, that means it did succeed, but the else part is handling the case where we did not expect it to succeed. Therefore the error message is correct, basically saying the attached succeeded but shouldn't have. However, if you look in the exception handling block, that's were the code message is wrong. That's that code that is executed when the attach failed. If it was not expected to fail, the code should complain that it was NOT able to attach, but instead it complains that it was able to attach.

**Comment by alexmenkov** [comment]
@plummercj Yes, you are right. Thank you for the catch.
I updated all 4 messages for consistency

**Review by sspitsyn — APPROVED** [review]
Hi Alex,
It looks good.
Thanks,
Serguei

**Review by plummercj — APPROVED** [review]
Looks good!

**Pull request closed without merging**
