### PR TITLE
8325109: Sort method modifiers in canonical order

### PR DESCRIPTION
**Pull request by magicus**
This is a follow-up on [JDK-8324053](https://bugs.openjdk.org/browse/JDK-8324053). I have run the bin/blessed-modifier-order.sh on the entire code base, and manually checked the result. I have reverted all but these trivial and uncontroversial changes.

Almost all of these are about moving `static` to its proper position; a few do not involve `static` but instead puts `final` or `abstract` in the correct place.

I have deliberately stayed away from `default` in this PR, since they should probably get a more thorough treatment, see https://github.com/openjdk/jdk/pull/17468#pullrequestreview-1829238473.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325109](https://bugs.openjdk.org/browse/JDK-8325109): Sort method modifiers in canonical order (**Bug** - P4)

### Reviewers
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)
 * [Joe Darcy](https://openjdk.org/census#darcy) (@jddarcy - **Reviewer**)
 * [Pavel Rappo](https://openjdk.org/census#prappo) (@pavelrappo - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17670/head:pull/17670` \
`$ git checkout pull/17670`

Update a local copy of the PR: \
`$ git checkout pull/17670` \
`$ git pull https://git.openjdk.org/jdk.git pull/17670/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17670`

View PR using the GUI difftool: \
`$ git pr show -t 17670`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17670.diff">https://git.openjdk.org/jdk/pull/17670.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17670#issuecomment-1921169225)

### CODE REVIEW

**Review by dfuch — COMMENTED** [review]
Changes to IPAdressUtil look fine. I eyeballed the rest and didn't spot any issue.

**Review by aivanov-jdk — APPROVED** [review]
Looks good to me.

I looked through all the changes.

**Review by RogerRiggs — APPROVED** [review]
lgtm; all look good

**Review by jddarcy — APPROVED** [review]
Looks fine; I just suggest double-checking on the current maintenance procedures for the java.util.concurrent code.

**Review by pavelrappo — APPROVED** [review]
Changes to jdk.javadoc look fine.

**Comment by magicus** [comment]
>  I just suggest double-checking on the current maintenance procedures for the java.util.concurrent code.

@jddarcy Any idea how to do that? I tried searching for JSR-166 and java.util.concurrent, but all I could find was talk about a now-deleted mailing list concurrency-interest, and a link to a [CVS repo for JDK8](http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/jsr166/src/jdk8/java/util/).

**Comment by magicus** [comment]
@DougLea Doug, do you have anything to say about the changes in `java.util.concurrent`?

**Comment by magicus** [comment]
Just to confirm publicly, there is no need for any special handling of `java.util.concurrent` any longer; the JDK repo is the single source of truth nowadays.

**Pull request closed without merging**
