### PR TITLE
8299673: Simplify object pinning interactions with string deduplication

### PR DESCRIPTION
**Pull request by fisk**
When raw char* String contents are exposed to JNI code, we 

1. Load the string.value and pin it 
2. Run native code 
3. Load the string.value and unpin it 

Given this sequence we would be in trouble if between 1 and 3, string deduplication changed the value object. Then the pinning and unpinning wouldn't be balanced. 

The current approach for dealing with this is to have a bunch of code to guard against deduplication. An alternative simpler solution is to just change step 3 to pass in the same value. We already have enough information available to do that. Then the pinning and unpinning is also balanced, and we don't need to have any special interactions with string deduplication and can decouple these orthogonal concerns.

It's worth noting though that the contract of pin_object now makes it explicit that pinned objects must not be recycled, even if not otherwise reachable. That seems to come naturally for region based pinning, but is worth keeping in mind. The exposed char* might be the only thing referencing the string value when string dedup happens concurrently.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299673](https://bugs.openjdk.org/browse/JDK-8299673): Simplify object pinning interactions with string deduplication

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**) ⚠️ Review applies to [3e1eb94d](https://git.openjdk.org/jdk/pull/11923/files/3e1eb94d390f4fe35b8a3fe3b46cdcf8e322d70e)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [3e1eb94d](https://git.openjdk.org/jdk/pull/11923/files/3e1eb94d390f4fe35b8a3fe3b46cdcf8e322d70e)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Contributors
 * Stefan Karlsson `<stefank@openjdk.org>`
 * Axel Boldt-Christmas `<aboldtch@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/11923/head:pull/11923` \
`$ git checkout pull/11923`

Update a local copy of the PR: \
`$ git checkout pull/11923` \
`$ git pull https://git.openjdk.org/jdk pull/11923/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11923`

View PR using the GUI difftool: \
`$ git pr show -t 11923`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/11923.diff">https://git.openjdk.org/jdk/pull/11923.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by fisk** [comment]
Thank you for the reviews, @kimbarrett and @stefank!

**Review by dholmes-ora — APPROVED** [review]
Initially I was a bit unsure about the conceptual model here, as I was thinking that pinning is a very general concept, where in fact it only relates to these JNI "critical" functions. So in that sense every GC must support pinning as required by those functions, so this simplification looks very neat. Thanks.

**Comment by fisk** [comment]
Thanks for the review, @dholmes-ora!

**Pull request closed without merging**
