### PR TITLE
8256016: Dacapo24H.java failed with "assert(false) failed: unscheduable graph"

### PR DESCRIPTION
**Pull request by chhagedorn**
In the replay compilation, a `CastPP` node belonging to a null-check `If` node floats above its null-check and is then split through a phi. This results in a broken control input for the `CastPP` node which eventually makes the graph unschedulable.

The problem can be traced back to the optimization done in `IfNode::simple_subsuming()`:

missing_data_dependencies

The dominating test `8792 If` subsumes the original null-check `6691 If` and its condition is replaced by the constant `230 ConI`. However, we forget to rewire data dependencies, in this case `6694 CastPP`, to the `8794 IfTrue` projection of the dominating test. This is a problem because `6691 If` is not yet removed by igvn but we already apply the Ideal optimization for the newly created `8792 If` node. We find that `8800 If` is an identical test that dominates `8792 If`. All control dependent data nodes are updated to the dominating `8802 IfTrue` projection and the dominated test `8792 If` is removed. But in this step, we do not find the `6694 CastPP` at `8794 IfTrue` because we have not updated its control input and `6691 If` was not yet removed such that it could have ended up at `8794 IfTrue`.

The fix is to rewire any data dependencies of the always taken projection of the subsumed test in `IfNode::simple_subsuming()` to the corresponding projection of the dominating test.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux aarch64 | Linux arm | Linux ppc64le | Linux s390x | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ❌ (1/1 failed) | ❌ (1/1 failed) | ❌ (1/1 failed) | ✔️ (6/6 passed) | ❌ (2/2 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |     |     |  ✔️ (9/9 passed) |    |  ✔️ (9/9 passed) | ✔️ (9/9 passed) |

**Failed test tasks**
- [Linux arm (build hotspot no-pch)](https://github.com/chhagedorn/jdk/runs/1447636503)
- [Linux ppc64le (build hotspot no-pch)](https://github.com/chhagedorn/jdk/runs/1447636583)
- [Linux s390x (build hotspot no-pch)](https://github.com/chhagedorn/jdk/runs/1447636397)
- [Linux x86 (build debug)](https://github.com/chhagedorn/jdk/runs/1447336559)
- [Linux x86 (build release)](https://github.com/chhagedorn/jdk/runs/1447336542)

### Issue
 * [JDK-8256016](https://bugs.openjdk.java.net/browse/JDK-8256016): Dacapo24H.java failed with "assert(false) failed: unscheduable graph"

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/1410/head:pull/1410`
`$ git checkout pull/1410`

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by chhagedorn** [comment]
@vnkozlov @iwanowww Thanks for your reviews!

**Pull request closed without merging**
