### PR TITLE
8303900: Rename BitMap search functions

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this renaming of the following functions in BitMap:

get_next_one_offset => find_first_set_bit
get_next_zero_offset => find_first_clear_bit
get_next_one_offset_aligned_right => find_first_set_bit_aligned_right

Note that ShenandoahMarkBitMap::get_next_one_offset is not being renamed.  For
some reason that class contains a copy of a sizable chunk of the code from
some version of BitMap.  (Not sure why it doesn't use an internal BitMapView
rather than code copying.)

Testing:
mach5 tier1-5

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303900](https://bugs.openjdk.org/browse/JDK-8303900): Rename BitMap search functions

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**) ⚠️ Review applies to [94fa65a5](https://git.openjdk.org/jdk/pull/12951/files/94fa65a59b87bc70722a92a6ebc31d8769aa2785)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer) ⚠️ Review applies to [94fa65a5](https://git.openjdk.org/jdk/pull/12951/files/94fa65a59b87bc70722a92a6ebc31d8769aa2785)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12951/head:pull/12951` \
`$ git checkout pull/12951`

Update a local copy of the PR: \
`$ git checkout pull/12951` \
`$ git pull https://git.openjdk.org/jdk pull/12951/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12951`

View PR using the GUI difftool: \
`$ git pr show -t 12951`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12951.diff">https://git.openjdk.org/jdk/pull/12951.diff</a>

</details>

### CODE REVIEW

**Review by stefank — APPROVED** [review]
Looks good.

**Review by xmas92 — APPROVED** [review]
lgtm

**Comment by kimbarrett** [comment]
Thanks for reviews @stefank and @xmas92

**Pull request closed without merging**
