### PR TITLE
8283806: [BACKOUT] JDK 19 L10n resource files update - msgdrop 10

### PR DESCRIPTION
**Pull request by alisenchung**
This reverts commit c0aecd15ae8d7abf37901f785fccaff2317c3b23.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283806](https://bugs.openjdk.java.net/browse/JDK-8283806): [BACKOUT] JDK 19 L10n resource files update - msgdrop 10

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - Author)
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8005/head:pull/8005` \
`$ git checkout pull/8005`

Update a local copy of the PR: \
`$ git checkout pull/8005` \
`$ git pull https://git.openjdk.java.net/jdk pull/8005/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8005`

View PR using the GUI difftool: \
`$ git pr show -t 8005`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8005.diff">https://git.openjdk.java.net/jdk/pull/8005.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
I confirm that this is an exact backout of [JDK-8280400](https://bugs.openjdk.java.net/browse/JDK-8280400).

**Review by naotoj — APPROVED** [review]
LGTM

**Pull request closed without merging**
