### PR TITLE
8339793: Fix incorrect APX feature enabling with -XX:-UseAPX

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Currently VM_Supports::supports_apx_f() returns a true value even if user explicitly pass -XX:-UseAPX runtime flag, this enables APX specific code and register set.

This bug fix patch turn off the APX_F feature if UseAPX runtime flag is explicitly set to false value.

Best Regards,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339793](https://bugs.openjdk.org/browse/JDK-8339793): Fix incorrect APX feature enabling with -XX:-UseAPX (**Bug** - P4)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/20921/head:pull/20921` \
`$ git checkout pull/20921`

Update a local copy of the PR: \
`$ git checkout pull/20921` \
`$ git pull https://git.openjdk.org/jdk.git pull/20921/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20921`

View PR using the GUI difftool: \
`$ git pr show -t 20921`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/20921.diff">https://git.openjdk.org/jdk/pull/20921.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/20921#issuecomment-2338967315)

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.

**Review by TobiHartmann — APPROVED** [review]
Looks good to me too.

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
