### PR TITLE
8253948: Memory leak in ImageFileReader

### PR DESCRIPTION
**Pull request by zhengyu123**
ImageFileReader allocates ImageModuleData in ImageFileReader::open(), but never free.

Also renamed module_data to _module_data to be consistent with other member variables.

Test:
- [x] tier1 on Linux x86_64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253948](https://bugs.openjdk.java.net/browse/JDK-8253948): Memory leak in ImageFileReader

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/490/head:pull/490`
`$ git checkout pull/490`

### CODE REVIEW

**Comment by zhengyu123** [comment]
/label add hotspot-runtime

ImageFileReader is also used in hotspot runtime

**Review by AlanBateman — COMMENTED** [review]
The jimage file is opened at startup and should never be closed. However the jrtfs provider (used by IDEs and other tools to access the resources in a target run-time image) may run into it so good to get it fixed.

Can you fix the formatting to use 4-space indentation consistently?

**Comment by AlanBateman** [comment]
I should have been clearer. The indentation issues are with changed lines 375, 446-447, and 581.

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
