### PR TITLE
JDK-8285977: Add links to IEEE 754 specification

### PR DESCRIPTION
**Pull request by jddarcy**
Please review the addition of @-see links from classes that mention the IEEE 754 floating-point standard to an IEEE page about the standard. The URL in the initial version of the PR is the top search result on the IEEE home page for "754 standard".

Another candidate page to use is

https://ieeexplore.ieee.org/servlet/opac?punumber=8766227

which is (apparently) a stable citation page for the standard.

These links may be upgraded to the the forthcoming @-spec facility in the future. ( JDK-6251738).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 reviews required, with at least 1 reviewer)

### Issue
 * [JDK-8285977](https://bugs.openjdk.java.net/browse/JDK-8285977): Add links to IEEE 754 specification

### Reviewers
 * [Jonathan Gibbons](https://openjdk.java.net/census#jjg) (@jonathan-gibbons - **Reviewer**) ⚠️ Review applies to [244fe910](https://git.openjdk.java.net/jdk/pull/8511/files/244fe9107f079808ed28d858ee4aaeb8caf9acd4)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**) ⚠️ Review applies to [244fe910](https://git.openjdk.java.net/jdk/pull/8511/files/244fe9107f079808ed28d858ee4aaeb8caf9acd4)
 * [Brian Burkhalter](https://openjdk.java.net/census#bpb) (@bplb - **Reviewer**) ⚠️ Review applies to [244fe910](https://git.openjdk.java.net/jdk/pull/8511/files/244fe9107f079808ed28d858ee4aaeb8caf9acd4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8511/head:pull/8511` \
`$ git checkout pull/8511`

Update a local copy of the PR: \
`$ git checkout pull/8511` \
`$ git pull https://git.openjdk.java.net/jdk pull/8511/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8511`

View PR using the GUI difftool: \
`$ git pr show -t 8511`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8511.diff">https://git.openjdk.java.net/jdk/pull/8511.diff</a>

</details>

### CODE REVIEW

**Review by jonathan-gibbons — APPROVED** [review]
I endorse the use of a URL with a host-name like `standards.ieee.org`

**Review by irisclark — APPROVED** [review]

**Review by bplb — APPROVED** [review]

**Comment by rgiulietti** [comment]
What about the DOI URL? Probably even more stable.
https://doi.org/10.1109/IEEESTD.2019.8766229

**Comment by jddarcy** [comment]
> What about the DOI URL? Probably even more stable. https://doi.org/10.1109/IEEESTD.2019.8766229

Hmm. I'd rather use the IEEE URL for now; if that turns out to problematic, we can switch to the DOI one.

**Comment by rgiulietti** [comment]
The DOI URL currently brings you to exactly the same IEEExplore page.

**Pull request closed without merging**
