### PR TITLE
8254264: Remove redundant cross_modify_fence()

### PR DESCRIPTION
**Pull request by pchilano**
Hi all,

Please review the following patch that removes some uneeded uses of cross_modify_fence() in common code, in particular from ~ThreadBlockInVM(), ~ThreadBlockInVMWithDeadlockCheck() and java_suspend_self_with_safepoint_check(). These fences were added before each JavaThread had to disarm itself (8230594). After a safepoint/handshake each JavaThread will always call SafepointMechanism::process_if_requested_slow() when transitioning out of the safe state and will execute a cross_modify_fence().
Tested with mach5 tiers1-7.

Thanks,
Patricio

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Testing

|     | Linux x32 | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ✔️ (1/1 passed) | ✔️ (5/5 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ⏳ (3/9 running) | ⏳ (9/9 running) | ⏳ (1/9 running) |

### Issue
 * [JDK-8254264](https://bugs.openjdk.java.net/browse/JDK-8254264): Remove redundant cross_modify_fence()

### Reviewers
 * [Robbin Ehn](https://openjdk.java.net/census#rehn) (@robehn - **Reviewer**) ⚠️ Review applies to 38fef27af0dac992c45237b913ffa2e40a2cfc72
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to 38fef27af0dac992c45237b913ffa2e40a2cfc72
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 38fef27af0dac992c45237b913ffa2e40a2cfc72

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/655/head:pull/655`
`$ git checkout pull/655`

### CODE REVIEW

**Review by robehn — APPROVED** [review]
Thanks!

**Review by dholmes-ora — APPROVED** [review]

**Comment by robehn** [comment]
> > And just to be clear any action that changes code such that a
> > cross-modify-fence is needed by other threads, has to perform a global
> > safepoint/handshake?
> 
> I'm not sure of that. But we added these fences for the case where the
> code got patched during a safepoint. Maybe Robbin knows the answer.? : )

On x86 we have two options complaint option according to the manual:

(* OPTION 1 *)
Store modified code (as data) into code segment;
Jump to new code or an intermediate location;
Execute new code;

(* OPTION 2 *)
Store modified code (as data) into code segment;
Execute a serializing instruction; (* For example, CPUID instruction *)
Execute new code;

- Code patching that happens outside a safepoint do options 1 and don't need CMF.
  If CMF is needed on some arch, it must be encoded into the instruction stream while patching.
  (whether this is really safe, thinking of spectre, is another story :) )
  See e.g. NativeGeneralJump::replace_mt_safe()
- Code patching that happens inside a safepoint do options 2 and need CMF.
  We only actual need CMF for safepoints, but since we do not know why we where armed we must emit it.
  So can be optimize by keeping track of the safepoint id and for which safepoint id we have emitted CMF for per java thread.

**Comment by a74nh** [comment]
I merged this patch together with https://github.com/openjdk/jdk/pull/428 (which makes AArch64 use cross modify fence) and ran it on AArch64 with the "-XX:+VerifyCrossModifyFence" set. A complete tier1 ran successfully, and I'm waiting on the results of a much wider run.

**Comment by pchilano** [comment]
Thanks @robehn and @dholmes-ora for the reviews!

**Comment by pchilano** [comment]
> I merged this patch together with #428 (which makes AArch64 use cross modify fence) and ran it on AArch64 with the "-XX:+VerifyCrossModifyFence" set. A complete tier1 ran successfully, and I'm waiting on the results of a much wider run.

Ok, let me know when you are okay and I will integrate.

**Comment by dcubed-ojdk** [comment]
Heads-up: The build and test tasks appear to be unhappy.

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up! Had to read through the comments a couple of
times along with the code before I convinced myself all was
okay. Thanks for testing Mach5 Tier[1-7].

**Comment by pchilano** [comment]
> Heads-up: The build and test tasks appear to be unhappy.

Yes, commit v1 was done after 8173585 was pushed but before the issues introduced by it were fixed. I can merge with master to make it happy.  : )

**Comment by pchilano** [comment]
> Thumbs up! Had to read through the comments a couple of
> times along with the code before I convinced myself all was
> okay. Thanks for testing Mach5 Tier[1-7].

Thanks Dan!

**Comment by dcubed-ojdk** [comment]
Why is the commit history only showing a single commit if there was a merge in the past?
(I might be missing something trivial here since I'm still a GitHub newbie.)

**Comment by pchilano** [comment]
> Why is the commit history only showing a single commit if there was a merge in the past?
> (I might be missing something trivial here since I'm still a GitHub newbie.)

Not sure, where are you seeing the merge?

**Comment by dcubed-ojdk** [comment]
Sorry Patricio. I saw the comment from a74nh above ("I merged this patch together with...")
and I just assumed it was you replying to David H. My mistake.

**Comment by a74nh** [comment]
> > I merged this patch together with #428 (which makes AArch64 use cross modify fence) and ran it on AArch64 with the "-XX:+VerifyCrossModifyFence" set. A complete tier1 ran successfully, and I'm waiting on the results of a much wider run.
> 
> Ok, let me know when you are okay and I will integrate.

I've run this across all our tests and machines now, and everything passes ok.

**Pull request closed without merging**
